### ISSUE TITLE
Change function ReplaceDescription on table 81- Gen. Journal Line as global function

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27088]
### Describe the request

Dear Team,

On table Gen. Jouranl Line, fucntion ReplaceDescription is a local function currently. Could you please convert it to be a global fucntion.

![2024-08-16_11h54_10](https://github.com/user-attachments/assets/2db03b48-66f3-4232-8651-478b09b8cad3)

Thank you for you considering.

### Additional context

I have requirement to call the function outside the objects.
Internal work item: [AB#544532](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544532)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24010.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 24013.
