### ISSUE TITLE
[Event Request] Codeunit 7001 "Price Asset - Service Cost" –  OnAfterFillBestLine

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#27090]
### Describe the request

Codeunit 7001 "Price Asset - Service Cost" ???  OnAfterFillBestLine

Could we please have a publisher OnAfterFillBestLine
in function FillBestLine  Codeunit 7001 "Price Asset - Service Cost" ?

```

    procedure FillBestLine(PriceCalculationBuffer: Record "Price Calculation Buffer"; AmountType: Enum "Price Amount Type"; var PriceListLine: Record "Price List Line")
    begin
        if not ServiceCost.Get(PriceCalculationBuffer."Asset No.") then
            exit;

        if AmountType <> AmountType::Discount then
            case PriceCalculationBuffer."Price Type" of
                PriceCalculationBuffer."Price Type"::Sale:
                    PriceListLine."Unit Price" := ServiceCost."Default Unit Price";
            end;

        
        // >>>>>>>>
        OnAfterFillBestLine(PriceCalculationBuffer, AmountType, PriceListLine);
        // <<<<<<<< 
    end;




// >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillBestLine(PriceCalculationBuffer: Record "Price Calculation Buffer"; AmountType: Enum "Price Amount Type"; var PriceListLine: Record "Price List Line")
    begin
    end;
// <<<<<<<< 

```

### Additional context

We have to remember that the price was not found in the price list, but via the master data. This is easily possible for resources and item with this event. This event is missing for service costs.
Internal work item: [AB#544529](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544529)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23752.
