### ISSUE TITLE
[Event Change Request] Report 1001 "Inventory Valuation" for IntegrationEvent OnItemOnAfterGetRecordOnAfterValueEntrySetInitialFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#27098]
### Describe the request

Please change **IncludeSender** to true on publisher OnItemOnAfterGetRecordOnAfterValueEntrySetInitialFilters

Current IntegrationEvent:
```
[IntegrationEvent(false, false)]
local procedure OnItemOnAfterGetRecordOnAfterValueEntrySetInitialFilters(var ValueEntry: Record "Value Entry"; Item: Record Item)
begin
end;
```
Proposed change:
```
[IntegrationEvent(true, false)]
local procedure OnItemOnAfterGetRecordOnAfterValueEntrySetInitialFilters(var ValueEntry: Record "Value Entry"; Item: Record Item)
begin
end;
```

### Additional context

We add a Boolean setting which can be Set on the Request Page. Based on this setting we set different additional filters on the passed ValueEntry. So Include sender gives us the possibility to expose a procedure added in a report extension which returns the current value set in the Request Page.
Internal work item: [AB#545021](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545021)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23206.
