### ISSUE TITLE
[Event Request] table 5409 "Prod. Order Routing Line", table 99000830 "Planning Routing Line" and table 99000764 "Routing Line"

### ISSUE THREAD

**Issue by aydin81** [microsoft/ALAppExtensions#27093]
### Describe the request

We need 2 new Events for Update "Work Center " and "Machine Center" values with handle per var variable in follow table:
- table 5409 "Prod. Order Routing Line"
- table 99000764 "Routing Line"
- table 99000830 "Planning Routing Line"

 OnBeforeWorkCenterTransferFields(Rec, xRec, WorkCenter, IsHandled);
 OnBeforeMachineCtrTransferFields(Rec, xRec, WorkCenter, MachineCenter, IsHandled );

We would like self decision if we overwrite the values, when the "type" or "No." changed.

Thanks.

### Additional context

    local procedure WorkCenterTransferFields()
	var
        IsHandled: Boolean;
    begin	
        IsHandled := false;
	OnBeforeWorkCenterTransferFields(Rec, xRec, WorkCenter, IsHandled);
        if IsHandled then
            exit;
		
        "Work Center No." := WorkCenter."No.";
        "Work Center Group Code" := WorkCenter."Work Center Group Code";
        "Setup Time Unit of Meas. Code" := WorkCenter."Unit of Measure Code";
        "Run Time Unit of Meas. Code" := WorkCenter."Unit of Measure Code";
        "Wait Time Unit of Meas. Code" := WorkCenter."Unit of Measure Code";
        "Move Time Unit of Meas. Code" := WorkCenter."Unit of Measure Code";
        Description := WorkCenter.Name;
        "Flushing Method" := WorkCenter."Flushing Method";
        "Unit Cost per" := WorkCenter."Unit Cost";
        "Direct Unit Cost" := WorkCenter."Direct Unit Cost";
        "Indirect Cost %" := WorkCenter."Indirect Cost %";
        "Overhead Rate" := WorkCenter."Overhead Rate";
        "Unit Cost Calculation" := WorkCenter."Unit Cost Calculation";
        FillDefaultLocationAndBins();
        OnAfterWorkCenterTransferFields(Rec, WorkCenter);
    end;

    local procedure MachineCtrTransferFields()
    begin
        WorkCenter.Get(MachineCenter."Work Center No.");
        WorkCenterTransferFields();

        IsHandled := false;
        OnBeforeMachineCtrTransferFields(Rec, xRec, WorkCenter, MachineCenter, IsHandled);
        if IsHandled then
            exit;
		
        Description := MachineCenter.Name;
        "Setup Time" := MachineCenter."Setup Time";
        "Wait Time" := MachineCenter."Wait Time";
        "Move Time" := MachineCenter."Move Time";
        "Fixed Scrap Quantity" := MachineCenter."Fixed Scrap Quantity";
        "Scrap Factor %" := MachineCenter."Scrap %";
        "Minimum Process Time" := MachineCenter."Minimum Process Time";
        "Maximum Process Time" := MachineCenter."Maximum Process Time";
        "Concurrent Capacities" := MachineCenter."Concurrent Capacities";
        if "Concurrent Capacities" = 0 then
            "Concurrent Capacities" := 1;
        "Send-Ahead Quantity" := MachineCenter."Send-Ahead Quantity";
        "Setup Time Unit of Meas. Code" := MachineCenter."Setup Time Unit of Meas. Code";
        "Wait Time Unit of Meas. Code" := MachineCenter."Wait Time Unit of Meas. Code";
        "Move Time Unit of Meas. Code" := MachineCenter."Move Time Unit of Meas. Code";
        "Flushing Method" := MachineCenter."Flushing Method";
        "Unit Cost per" := MachineCenter."Unit Cost";
        "Direct Unit Cost" := MachineCenter."Direct Unit Cost";
        "Indirect Cost %" := MachineCenter."Indirect Cost %";
        "Overhead Rate" := MachineCenter."Overhead Rate";
        FillDefaultLocationAndBins();
        OnAfterMachineCtrTransferFields(Rec, WorkCenter, MachineCenter);
    end;

Internal work item: [AB#545023](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545023)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
