### ISSUE TITLE
[Event Requet] Table 246 "Requisition Line" - OnBeforeValidateVendorItemNo

### ISSUE THREAD

**Issue by Jattzia1978** [microsoft/ALAppExtensions#27094]
### Describe the request

I need to be able to default some custom fields when the value of the field "Vendor Item No." is modified. Therefore, I request the following event:

field(22; "Vendor Item No."; Text[50])
{
    Caption = 'Vendor Item No.';

        trigger OnValidate()
        var
            IsHandled: Boolean;
        begin
            IsHandled := false;
            OnBeforeValidateVendorItemNo(Rec, xRec, IsHandled);
            if IsHandled then
                exit;
        end;       
}

[IntegrationEvent(false, false)]
local procedure OnBeforeValidateVendorItemNo(var RequisitionLine: Record "Requisition Line"; xRequisitionLine: Record "Requisition Line"; var IsHandled: Boolean);
begin
end;

### Additional context

Allows you to change values of other fields when the value of "Vendor Item No." is modified
Internal work item: [AB#544697](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544697)

**Comment by AleksandricMarko** [comment]
Hello @Jattzia1978 
Why event with IsHandled pattern if you want just to update some additional fields? Why not OnAfterValidate event?

**Comment by Jattzia1978** [comment]
Hi @AleksandricMarko,

You are correct, this would work. I will close the request
