### ISSUE TITLE
Handle check code on field Base Unit of Measure on function RunCheck (codeunit "Item Jnl.-Check Line")

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27105]
### Describe the request

Dear team,

On codeunit 12 - "Item Jnl.-Check Line", function RunCheck, I'd like to handle check code on field "Base Unit of Measure" as below:

![2024-08-20_14h27_46](https://github.com/user-attachments/assets/586accc5-60e8-441b-8060-dfd557b17bcf)
......
IsHandled := false;
OnBeforeGetItem(Item, IsHandled);
if not IsHandled then
	if Item.Get(ItemJournalLine."Item No.") then
		Item.TestField("Base Unit of Measure", ErrorInfo.Create());
.......
 
The IntegrationEvent should belike:
[IntegrationEvent(false, false)]
local procedure OnBeforeGetItem(var Item: Record Item; var IsHandled: Boolean)
begin
end;

Please consider in it.
Thank you in advance!

### Additional context

It don't check Base Unit of Measure on my business.

Internal work item: [AB#545014](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545014)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25075.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25754.
