### ISSUE TITLE
[Event Change Request] Codeunit 3998 Retention Policy Scheduler - Event OnAfterCanScheduleJobQueueEntry

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#27103]
### Describe the request

We need an new Event in the function CanScheduleJobQueueEntry

````
local procedure CanScheduleJobQueueEntry(var RetentionPolicySetup: Record "Retention Policy Setup"): Boolean
var
    ResultL: Boolean; <-- NEW VAR
    begin
        if RetentionPolicySetup.IsTemporary() then
            exit(false);

        if GetCurrentModuleExecutionContext() <> ExecutionContext::Normal then
            exit(false);

        if not TaskScheduler.CanCreateTask() then
            exit(false);

	ResultL := true;
	OnAfterCanScheduleJobQueueEntry(RetentionPolicySetup,ResultL); <-- NEW EVENT
	exit(ResultL) <--- CHANGE
    end;
````

````
    [IntegrationEvent(false, false)]
    local procedure OnAfterCanScheduleJobQueueEntry(var RetentionPolicySetup: Record "Retention Policy Setup"; var ResultP: Boolean)
    begin
    end;
````

### Additional context

We need a way to control the scheduling of the job queue.
Internal work item: [AB#545016](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545016)

**Comment by Groenbech96** [comment]
Can you add more information about what and why you need to control the schedule?

**Comment by ChrSt89** [comment]
Hi,

There are customers where we cannot automatically schedule the task because other jobs are already scheduled and may be active and are currently in the process.


That's why we want to have the possibility that the job is not planned automatically.

**Comment by Groenbech96** [comment]
I would suggest to use OnBeforeIsReadyToStart on the JobQueueEntry table, to ensure that jobs are not ready to run, if that is the root issue, instead of altering the logic for retension policy
