### ISSUE TITLE
[Request-For-External] table 39 "Purchase Line" CalcBaseQty

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27109]
### Describe the request

Can you change procedure CalcBaseQty to global in table 39 "Purchase Line"?

### Additional context

I want to avoid duplication
Internal work item: [AB#545256](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545256)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23634.
