### ISSUE TITLE
[Event Request] codeunit 1002 "Job Create-Invoice" - OnBeforeGetCustomerNo

### ISSUE THREAD

**Issue by kristjano** [microsoft/ALAppExtensions#27106]
### Describe the request

Add new event to method GetCustomerNo so customization can handle this diffrently.

```
local procedure GetCustomerNo(Job: Record Job; JobPlanningLine: Record "Job Planning Line"; SellToCustomerNo: Boolean): Code[20]
var
    JobTask: Record "Job Task";
    IsHandled: Boolean;
    CustomerNo: Code[20];
begin
    IsHandled := true;
    OnBeforeGetCustomerNo(Job, JobPlanningLine, SellToCustomerNo, CustomerNo, IsHandled);
    if IsHandled then
        exit(CustomerNo);

    ...
end;
```
Event signature:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetCustomerNo(Job: Record Job; JobPlanningLine: Record "Job Planning Line"; SellToCustomerNo: Boolean; var CustomerNo: Code[20]; var IsHandled: Boolean)
begin
end;
```

### Additional context

I need to be able to handle differently how we get the customer from the Job Planning Line.
Internal work item: [AB#545182](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545182)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23206.
