### ISSUE TITLE
[Event Request] codeunit "Check Gen. Jnl. Line. Backgr.".CheckGenJnlLineDocBalance() - OnBeforeCheckGenJnlLineDocBalance

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#27119]
### Describe the request

Please add a new event `OnBeforeCheckGenJnlLineDocBalance` to method `CheckGenJnlLineDocBalance` in `codeunit "Check Gen. Jnl. Line. Backgr."`:
```al
  local procedure CheckGenJnlLineDocBalance(GenJnlLine: Record "Gen. Journal Line"; var TempErrorMessage: Record "Error Message" temporary)
  var
     ...
+    IsHandled: Boolean;
  begin
+    IsHandled := false;
+    OnBeforeCheckGenJnlLineDocBalance(GenJnlLine, TempErrorMessage, IsHandled);
+    if IsHandled then
+        exit;

     GenJnlLine.SetRange("Journal Template Name", GenJnlLine."Journal Template Name");
     ...
  end;

+ [IntegrationEvent(false, false)]
+ local procedure OnBeforeCheckGenJnlLineDocBalance(GenJournalLine: Record "Gen. Journal Line"; var TempErrorMessage: Record "Error Message"; var IsHandled: Boolean)
+ begin
+ end;
```

### Additional context

As designed; it is needed to skip the balance check.
Internal work item: [AB#545883](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545883)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.
