### ISSUE TITLE
[Event Requet] Codeunit 6500 "Item Tracking Management" - OnBeforeExitFindInInventory

### ISSUE THREAD

**Issue by Jattzia1978** [microsoft/ALAppExtensions#27117]
### Describe the request

I need to customize the filters in procedure FindInInventory, therefore, I request the following event:

procedure FindInInventory(ItemNo: Code[20]; VariantCode: Code[20]; SerialNo: Code[50]): Boolean
    var
        ItemLedgerEntry: Record "Item Ledger Entry";
    begin
        ItemLedgerEntry.SetCurrentKey("Serial No.", "Item No.", Open, "Variant Code", Positive);
        ItemLedgerEntry.SetRange("Item No.", ItemNo);
        ItemLedgerEntry.SetRange(Open, true);
        ItemLedgerEntry.SetRange("Variant Code", VariantCode);
        ItemLedgerEntry.SetRange(Positive, true);
        if SerialNo <> '' then
            ItemLedgerEntry.SetRange("Serial No.", SerialNo);

        OnBeforeExitFindInInventory(ItemLedgerEntry);
        exit(not ItemLedgerEntry.IsEmpty());
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforeExitFindInInventory(var ItemLedgerEntry: Record "Item Ledger Entry");
begin
end;

### Additional context

This is needed to ensure a unique serial no. across all inventory instead of per item.
The modification was done for a customer in Navision 2018 and he is now migrating to BC
We need to remove the filter on the Item No. and Variant Code fields

Internal work item: [AB#545886](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545886)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23666.
