### ISSUE TITLE
[Bug]: UpdateErrors() on Intrastat Report page is not called when executing Validation Codeunit ID set in VAT Reports Configuration

### ISSUE THREAD

**Issue by matjaz-sega** [microsoft/ALAppExtensions#27114]
### Describe the issue

We are using custom CU for exporting Intrastat Report. To be able to make file, we also need to use custom CU for validation because of this condition in CreateFile action:
![image](https://github.com/user-attachments/assets/3944146d-ec85-4c4e-bca5-66c09a68b5fa)

For our validation we want to use standard code, therefore our validation CU calls the same procedure as standard:
![image](https://github.com/user-attachments/assets/a5da5064-84ec-4069-a4f7-7fd01f8ae227)

When we execute ChecklistReport action, check is performed normally but UpdateErrors() is not called:
![image](https://github.com/user-attachments/assets/a04ced8a-aee8-4310-9b77-fcdd938e8e4a)

If any error is logged, line is colored red but Error Messages part is empty:
![image](https://github.com/user-attachments/assets/77bb874e-6e74-4c71-b8c5-3f8765111388)

Refreshing with F5 does not help. Only after you close and reopen the Intrastat Report page, Error Messages part is populated correctly:
![image](https://github.com/user-attachments/assets/a0f58cd9-5738-451e-b105-9498fc1a3496)

### Expected behavior

In ChecklistReport action, UpdateErrors() should be called after validation codeunit is executed. Calling this function from validation CU is impossible, because, a) the function is local, and b) validation CU has no access to CurrentPage object.

Furthermore, CreateFile action also needs to be refactured, because it doesn't call UpdateErrors() after calling validation CU.

Actually, I would reconsider the choice to only allow usage of Content CU and Validation CU in tandem. As our case shows, sometimes standard validation is enough and you only need custom export logic. So further refactoring of CreateFile action might be in order, separating these two steps and enabling us to choose, where to use standard and where to go custom.

### Steps to reproduce

Create Validation CU with copy of standard code as shown above and Content CU (can be dummy).
Set both codeunits to be used in VAT Reports Configuration.
Configure Intrastat Report Checklist. Example:
![image](https://github.com/user-attachments/assets/a43ff111-13bc-40c9-817e-898bf0728cc3)
Prepare Intrastat Report Lines with errors (value missing in fields that are set up in Intrastat Report Checklist). Example:
![image](https://github.com/user-attachments/assets/ce2392fe-9672-4b59-8fa4-4a7428a61de3)
Execute Checklist Report action. Line is colored red but Error Messages is empty:
![image](https://github.com/user-attachments/assets/3092d728-8672-402b-ab77-5a2d76ebca83)

### Additional context

I found another open issue regarding UpdateErrors() function. That issue requests that the procedure is made protected, but that only enables a workaround (replacing standard actions with custom ones) and does not fix the bug.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by RadoArvay** [comment]
I was planning to solve this in the issue [BusinessCentralApps issues 890](https://github.com/microsoft/BusinessCentralApps/issues/890) but I did a mistake in a placing and I am waiting for a transfer.
Btw: in your issue Release action is missing - that need to be fixed as well.

So, the question is who will provide the fix to avoid duplicity?

P.S. Issue #26961 is also for our modifications, but it solves different problems.

**Comment by RadoArvay** [comment]
So, the approved issue cannot be transfered from the other repository. We should continue on yours.

**Comment by matjaz-sega** [comment]
@RadoArvay Do you have a prepared solution already? If not, I can prepare a PR and you can provide feedback on it.

**Comment by RadoArvay** [comment]
@matjaz-sega No, I have not. I have not started yet.

**Comment by RadoArvay** [comment]
@matjaz-sega Anything new about it?

**Comment by matjaz-sega** [comment]
@RadoArvay Sorry, I was really busy these 2 weeks. I'll try to do it by the end of the week.
