### ISSUE TITLE
[Event Requet] Codeunit 6501 "Item Tracking Data Collection" - OnBeforeAddSelectedTrackingToDataSet

### ISSUE THREAD

**Issue by Jattzia1978** [microsoft/ALAppExtensions#27118]
### Describe the request

I need to add custom code after the entries are selected but before the item tracking lines are modified

procedure SelectMultipleTrackingNo(var TempTrackingSpecification: Record "Tracking Specification" temporary; MaxQuantity: Decimal; CurrentSignFactor: Integer)
    var
        ...
    begin
        ...

        ItemTrackingSummaryForm.GetSelected(TempEntrySummary);
            if TempEntrySummary.IsEmpty() then
                exit;

        // Swap sign on the selected entries if parent is a negative supply line
        if CurrentSignFactor > 0 then // Negative supply lines
            if TempEntrySummary.Find('-') then
                repeat
                    TempEntrySummary."Selected Quantity" := -TempEntrySummary."Selected Quantity";
                    TempEntrySummary.Modify();
                until TempEntrySummary.Next() = 0;

        // Modify the item tracking lines with the selected quantities
        OnBeforeAddSelectedTrackingToDataSet(TempEntrySummary, TempTrackingSpecification, CurrentSignFactor);
        AddSelectedTrackingToDataSet(TempEntrySummary, TempTrackingSpecification, CurrentSignFactor);
    end;

### Additional context

The modification was done for a customer in Navision 2018 and he is now migrating to BC
They have a custom RMA requisition worksheet.
We need to be able to swap sign for those entries but the current code is only called if the CurrentSignFactor is positive, which is not the case in our modification.
Internal work item: [AB#545885](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545885)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23666.
