### ISSUE TITLE
[Event Request] table 454 "Approval Entry" - CanCurrentUserEdit

### ISSUE THREAD

**Issue by UrbMigle** [microsoft/ALAppExtensions#27113]
### Describe the request

Hey,

In the CanCurrentUserEdit procedure, there is no way to add any additional checks or conditions to alter the return value. Please add an event publisher OnBeforeCanCurrentUserEdit() with IsHandled pattern and a return value to be able to do so.

Current procedure:
```
    procedure CanCurrentUserEdit(): Boolean
    var
        UserSetup: Record "User Setup";
    begin
        if not UserSetup.Get(UserId) then
            exit(false);
        exit((UserSetup."User ID" in ["Sender ID", "Approver ID"]) or UserSetup."Approval Administrator");
    end;
```
With added return value and event publisher:
```
    procedure CanCurrentUserEdit() IsEditable: Boolean  <--
    var
        UserSetup: Record "User Setup";
        IsHandled: Boolean; <--
    begin
        IsHandled := false; <--
        OnBeforeCanCurrentUserEdit(Rec, IsEditable, IsHandled); <--
        if IsHandled then <--
            exit(IsEditable); <--

        if not UserSetup.Get(UserId) then
            exit(false);
        exit((UserSetup."User ID" in ["Sender ID", "Approver ID"]) or UserSetup."Approval Administrator");
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCanCurrentUserEdit(var ApprovalEntry: Record "Approval Entry"; var IsEditable: Boolean; var IsHandled: Boolean)
    begin
    end;
```

Thank you!

### Additional context

Please add event publisher to be able to alter the return value of CanCurrentUserEdit procedure.
Internal work item: [AB#545888](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545888)

**Comment by Groenbech96** [comment]
We wont allow complete override of this function. 
Can you elaborate on what functionality is not met in current design.

**Comment by UrbMigle** [comment]
The standard functionality allows either the sender or the approver to edit the current entry.
We would like to extend that additional users (approval administrators, "super" approval users, etc.) would be able to modify the entries as well.

Our procedure currently looks like that:

```
    procedure CanCurrentUserEdit(): Boolean
    var
        UserSetup: Record "User Setup";
        ApprovalsMgmt: Codeunit "Approvals Mgmt.";
    begin
        if not UserSetup.Get(UserId) then
            exit(false);

        if (UserSetup."User ID" in ["Sender ID", "Approver ID"]) or
          UserSetup."Approval Administrator" or
          ApprovalsMgmt.CheckUserAsSuperApprover("Document Type", "Table ID")
        then
            exit(true);

        exit(CurrentUserIsApproverOrSharedApprover());
    end;
```

How could we allow additional users to edit entries?

**Comment by Groenbech96** [comment]
After internal discussion, this is not something we want to change. Will close as wont fix.
