### ISSUE TITLE
Codeunit 64 + 74: Useless checks on Shipment / Receipt Lines

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#2712]
In Codeunit 64 + 74 there is a more or less useless check on `VAT Bus. Posting Group` that removes a lot of flexibility. I mean this one:

````
      [...]
      IF TransferLine THEN BEGIN
        SalesShptLine := SalesShptLine2;
        >>>SalesShptLine.TESTFIELD("VAT Bus. Posting Group",SalesHeader."VAT Bus. Posting Group");
        SalesShptLine.InsertInvLineFromShptLine(SalesLine);
        CalcUpdatePrepmtAmtToDeductRounding(SalesShptLine,SalesLine,PrepmtAmtToDeductRounding);
      [...]
````

This has been here for a very long time already, and it's been removed by us on every single installation.

With this check in place I have no way of invoicing a document to the correct customer / vendor in case I have chosen the wrong during shipment / receipt. There is no valid fiscal reason to enforce the same category as the target invoice header and infact, it blocks a lot of our apps that only work with this check gone.

If removing this is not an option, at least give us a way to handle it via events or similar. In which case see #578. If this got applied to both sales & purchase we could "fake" our way out by injecting the current invoice header posting group onto the Sales Shipment Line / Purch. Receipt Line and essentially bypass the check.

Also: note that both related codeunits 6638 `Sales-Get Return Receipts` and 6648 `Purch.-Get Return Shipments` **do not** have this check.

Thanks.

**Comment by Addice73** [comment]
Is blocking legal/fiscal need in italy
