### ISSUE TITLE
[Event Change Request] codeunit 5752 "Get Source Doc. Outbound" - event OnBeforeCreateFromPurchaseReturnOrder

### ISSUE THREAD

**Issue by dorinbirsan** [microsoft/ALAppExtensions#27121]
### Describe the request

The current event change would benefit the fact that we could add IsHandled and thus handle the respective section of code, like OnBeforeCreateFromSalesOrder already has, so that we can skip the warehouse creation for the other documents as well.

This event change happens in codeunit 5752 "Get Source Doc. Outbound" for procedure CreateFromPurchaseReturnOrder    

Current:

    procedure CreateFromPurchaseReturnOrder(PurchHeader: Record "Purchase Header")
    begin
        OnBeforeCreateFromPurchaseReturnOrder(PurchHeader);
        ShowResult(CreateFromPurchReturnOrderHideDialog(PurchHeader));
    end;

Requested:

    ...

    procedure CreateFromPurchaseReturnOrder(PurchHeader: Record "Purchase Header")
    var
        IsHandled: Boolean;
    begin
        OnBeforeCreateFromPurchaseReturnOrder(PurchHeader, IsHandled);
        if IsHandled then
            exit;
            
        ShowResult(CreateFromPurchReturnOrderHideDialog(PurchHeader));
    end;

    ...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateFromPurchaseReturnOrder(PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;

    ...

### Additional context

Justification: we request the event since in BC22 it was introduced that in the actions Create Warehouse Shipment and Create Warehouse receipt the document is released automatically in case it was open.
That conflicts now with existing custom logic, that the warehouse document is created already after the release of a document, leading to the issue that it is now tried two times to create the warehouse document.

Also, it is not possible to use the OnBeforeCreateWhseShipmentHeaderFromWhseRequest event since this event is called both in the Rec.PerformManualRelease()  (since the Whse Shipment is created automatically during the release process)  and in the GetSourceDocOutbound.CreateFromPurchaseReturnOrder() functions. Because of this we cannot properly handle it. Once the shipment is created during the Release process, we want to handle the behavior of the GetSourceDocOutbound.CreateFromPurchaseReturnOrder() function call so that it does not attempt to create the whse shipment a second time. 
![image](https://github.com/user-attachments/assets/342ac0c3-672c-469d-a28e-539f6cb3ab91)

Internal work item: [AB#546689](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546689)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23666.
