### ISSUE TITLE
[Event Request] Codeunit 6500 "Item Tracking Management"

### ISSUE THREAD

**Issue by Mariangela-DeMaio-EOS** [microsoft/ALAppExtensions#27123]
### Describe the request

Hello,
we need an event in the Codeunit 6500 "Item Tracking Management" in the procedure "InsertReservEntryToOutboundTransferLine" before insert the Reservation Entry.
`                
                 
        local procedure InsertReservEntryToOutboundTransferLine(var ReservEntry: Record "Reservation Entry"; 
        ItemLedgEntryBuf: Record "Item Ledger Entry"; TransferLine: Record "Transfer Line"; QtyBase: Decimal; var EntriesExist: 
        Boolean)
        begin
        if not ItemLedgEntryBuf.TrackingExists() or (QtyBase = 0) then
        exit;

        Clear(ReservEntry);
        InitReservEntry(ReservEntry, ItemLedgEntryBuf, QtyBase, TransferLine."Shipment Date", EntriesExist);
        ReservEntry.SetSource(Database::"Transfer Line", 0, TransferLine."Document No.", TransferLine."Line No.", '', 0);
        ReservEntry."Reservation Status" := ReservEntry."Reservation Status"::Surplus;
        ReservEntry.Description := TransferLine.Description;
        ReservEntry.UpdateItemTracking();

        // Start Event
            OnBeforeInsertReservEntryToOutboundTransferLine(ReservEntry, ItemLedgEntryBuf, TransferLine, QtyBase, EntriesExist);
        // End Event

        ReservEntry.Insert();
    end;`

     [IntegrationEvent(false, false)]
     local procedure OnBeforeInsertReservEntryToOutboundTransferLine(var ReservEntry: Record "Reservation Entry"; 
     ItemLedgEntryBuf: Record "Item Ledger Entry"; TransferLine: Record "Transfer Line"; QtyBase: Decimal; var EntriesExist: 
     Boolean)
    begin
    end;

`

### Additional context

We have to modify the Reservation Entry.
Internal work item: [AB#546696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546696)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23666.
