### ISSUE TITLE
[Event Change Request] codeunit 6620 - Copy Document Mgt. - event OnBeforeInitAndCheckSalesDocuments

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#27126]
### Describe the request

Please make the parameter "RecalculateLines" a parameter that is passed by VAR so that I can influence the rest of the functions based on different inputs

Existing event: 
```
[IntegrationEvent(false, false)]
local procedure OnBeforeInitAndCheckSalesDocuments(FromDocType: enum "Sales Document Type From"; FromDocNo: Code[20]; FromDocOccurrenceNo: Integer; FromDocVersionNo: Integer; var FromSalesHeader: Record "Sales Header"; var ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; MoveNegLines: boolean; IncludeHeader: Boolean; RecalculateLines: Boolean; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```

Proposed change: 
```
[IntegrationEvent(false, false)]
local procedure OnBeforeInitAndCheckSalesDocuments(FromDocType: enum "Sales Document Type From"; FromDocNo: Code[20]; FromDocOccurrenceNo: Integer; FromDocVersionNo: Integer; var FromSalesHeader: Record "Sales Header"; var ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; MoveNegLines: boolean; IncludeHeader: Boolean; var RecalculateLines: Boolean; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```

### Additional context

This change allows to influence the following code sequence without copying the whole function and skipping the BC standard logic using the IsHandled pattern. 
Internal work item: [AB#546688](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546688)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23666.
