### ISSUE TITLE
[EVENT REQUESTS] Item Attribute Value Selection (Table 7504)

### ISSUE THREAD

**Issue by MarkusW-BSG** [microsoft/ALAppExtensions#27136]
### Describe the request

For implementing process customizations from BC13 to the current BC24 I need three new events in Table 7504 related to special value handling.

1. Function InsertItemAttributeValue
![image](https://github.com/user-attachments/assets/1d4884ed-7c62-4fc2-aebf-aca6b41c46c5)

**Requested Event** (Call before the Insert):

procedure InsertItemAttributeValue(var ItemAttributeValue: Record "Item Attribute Value"; TempItemAttributeValueSelection: Record "Item Attribute Value Selection" temporary)
    var
        ValDecimal: Decimal;
        ValDate: Date;
    begin
        ...
        end;
        **OnBeforeInsertItemAttributeValue(ItemAttributeValue,TempItemAttributeValueSelection);**
        ItemAttributeValue.Insert();

2. Function FindAttributeValueFromRecord
![image](https://github.com/user-attachments/assets/2273cd0b-cd1e-485b-8e3f-0e0985a5d999)

**Requested Event** (Call before the exit()):
procedure FindAttributeValueFromRecord(var ItemAttributeValue: Record "Item Attribute Value"; ItemAttributeValueSelection: Record "Item Attribute Value Selection"): Boolean
    var
        ValDecimal: Decimal;
        ValDate: Date;
    begin
       ...
        **OnBeforeFindAttributeValueFromRecord(ItemAttributeValue,ItemAttributeValueSelection);**
        exit(ItemAttributeValue.FindFirst());
    end;

3. Function GetAttributeValueID
![image](https://github.com/user-attachments/assets/23585fea-7f26-4f69-b25e-8b163094134c)

**Requested Event** (Call before the insert):
procedure GetAttributeValueID(var TempItemAttributeValueToInsert: Record "Item Attribute Value" temporary): Integer
    var
        ItemAttributeValue: Record "Item Attribute Value";
        ItemAttribute: Record "Item Attribute";
        ValDecimal: Decimal;
        ValDate: Date;
        ValInteger: Integer;
    begin
        if not FindAttributeValue(ItemAttributeValue) then begin
...
        TempItemAttributeValueToInsert.TransferFields(ItemAttributeValue);
        **OnGetAttributeValueIDOnBeforeInsert(TempItemAttributeValueToInsert, ItemAttributeValue);**
        TempItemAttributeValueToInsert.Insert();
        exit(ItemAttributeValue.ID);
   end;

### Additional context

As described in related request #27131 we implemented a different way of handling item attributes for steel industry. An item attribute value needs to handle two different values. A decimal value in "our" unit and additional in the "imperial unit".

Finding, inserting and getting values to / from this table therefore needs events to implement. :-)
Thanks in advance
Markus 
Internal work item: [AB#546847](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546847)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
