### ISSUE TITLE
[Extensibility request] page 9103 "Pending Approval FactBox" - make ApprovalCommentLine protected

### ISSUE THREAD

**Issue by UrbMigle** [microsoft/ALAppExtensions#27135]
### Describe the request

Hello,

We need to apply additional filters for the ApprovalCommentLine variable, also we want to use the variable in additional custom fields. To do so, we need it to be protected instead of global. Could you please change it to that?

```
...
    trigger OnAfterGetRecord()
    begin
        ApprovalCommentLine.SetRange("Table ID", Rec."Table ID");
        ApprovalCommentLine.SetRange("Record ID to Approve", Rec."Record ID to Approve");
        if ApprovalCommentLine.FindLast() then;
    end;

    protected var <------
        ApprovalCommentLine: Record "Approval Comment Line";
}

```

Thank you!

### Additional context

To apply additional filters and use ApprovalCommentLine in different contexts, we need it to be made protected instead of it being global.
Internal work item: [AB#546861](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546861)

**Comment by Groenbech96** [comment]
Cant you set filters on your own version of the variable? To find the same record?
