### ISSUE TITLE
[EVENT REQUESTS] Item Attribute (Table 7500)

### ISSUE THREAD

**Issue by MarkusW-BSG** [microsoft/ALAppExtensions#27131]
### Describe the request

For implementing process customizations from BC13 to the current BC24 I need two new events in Table 7500 related to special translations.

1. Function GetTranslatedName
![image](https://github.com/user-attachments/assets/89c07ed6-169d-4017-99d7-b7f068f41a4e)

**Requested Event** (Call at first line of the function):
procedure GetTranslatedName(LanguageID: Integer): Text[250]
    var
        Language: Codeunit Language;
        LanguageCode: Code[10];
        **TranslatedName: Text[250];**
        **Ishandled: boolean;**
    begin
      **OnBeforeGetTranslatedName(LanguageID, TranslatedName, Ishandled);
      If Ishandled then
         exit(TranslatedName);**
...

2. Function GetAttributeTranslation
![image](https://github.com/user-attachments/assets/fea72580-f21a-4e3a-870c-45c668bb334c)

**Requested Event**

local procedure GetAttributeTranslation(LanguageCode: Code[10])
    begin
        if (ItemAttributeTranslation."Attribute ID" <> ID) or (ItemAttributeTranslation."Language Code" <> LanguageCode) then
            if not ItemAttributeTranslation.Get(ID, LanguageCode) then begin
                ItemAttributeTranslation.Init();
                ItemAttributeTranslation."Attribute ID" := ID;
                ItemAttributeTranslation."Language Code" := LanguageCode;
                ItemAttributeTranslation.Name := Name;
                **OnAfterCreateNewTranslation(Rec, ItemAttributeTranslation);**
            end;
    end;

Event Definition
Rec: Not VAR
ItemAttributeTranslation: VAR

### Additional context

In steel industry an item has dozens of attributes, defining the grade, chemical and mechanical specification of a steel.

Additionally, those attributes need to be displayed on certificate reports sent to customers in addition to the shipping note in different languages.

On these certificates, those attributes are displayed in a different way than in our "internal" view in NAV. For example with addional information, more or less detailed.

Therefore we have additional "display names" implemented in our system
Internal work item: [AB#546842](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546842)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
