### ISSUE TITLE
[Event Request] Codeunit 5940 - ServContractManagement - FillTempServiceLedgerEntries

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#27130]
### Describe the request

I propose to add this extensibility event to the ServContractManagement codeunit in the procedure FillTempServiceLedgerEntries. 

```
local procedure FillTempServiceLedgerEntries(ServiceContractHeader: Record "Service Contract Header")
var
    ServiceLedgerEntry: Record "Service Ledger Entry";
    //NEW VARIABLE
    SkipInsert: Boolean;
begin
    if TempServLedgEntriesIsSet then
        exit;
    TempServLedgEntry.DeleteAll();
    ServiceLedgerEntry.SetRange("Service Contract No.", ServiceContractHeader."Contract No.");
    ServiceLedgerEntry.SetRange("Entry Type", ServiceLedgerEntry."Entry Type"::Sale);
    if not ServiceLedgerEntry.FindSet() then
        exit;
    repeat
        TempServLedgEntry := ServiceLedgerEntry;
        
        //NEW EVENT
        SkipInsert := false;
        FillTempServiceLedgerEntriesOnBeforeInsertTempEntry(TempServLedgEntry, SkipInsert);
        if not SkipInsert then      
        //NEW EVENT        
            TempServLedgEntry.Insert();
    until ServiceLedgerEntry.Next() = 0;
    TempServLedgEntriesIsSet := true;
end;

[IntegrationEvent(false, false)]
local procedure FillTempServiceLedgerEntriesOnBeforeInsertTempEntry(TempServLedgEntry: Record "Service Ledger Entry" temporary; var SkipInsert: Boolean)
begin
end;
```

### Additional context

For my business case, I need to perform checks on the service ledger entry and decide if it should be inserted or not. 
Internal work item: [AB#546844](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546844)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
