### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - OnPmtTolVendBaforeCalcVendApplnAmount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27148]
### Describe the request

Hello, can you please add a new Event OnPmtTolVendBaforeCalcVendApplnAmount in codeunit 426 "Payment Tolerance Management"?

```
    procedure PmtTolVend(var VendLedgEntry: Record "Vendor Ledger Entry"): Boolean
    var
.
.
.
        GLSetup.Get();
        VendEntryApplID := UserId();
        if VendEntryApplID = '' then
            VendEntryApplID := '***';
        OnPmtTolVendOnAfterSetVendEntryApplId(VendLedgEntry, VendEntryApplID);

        DelVendPmtTolAcc(VendLedgEntry, VendEntryApplID);
        VendLedgEntry.CalcFields("Remaining Amount");
        OnPmtTolVendBaforeCalcVendApplnAmount(VendLedgEntry);
        CalcVendApplnAmount(
          VendLedgEntry, GLSetup, AppliedAmount, ApplyingAmount, AmounttoApply, PmtDiscAmount,
          MaxPmtTolAmount, VendEntryApplID, ApplnRoundingPrecision);
```

```
    [IntegrationEvent(false, false)]
    local procedure OnPmtTolVendBaforeCalcVendApplnAmount(var VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and need to recalculate it for it's further uses.
Internal work item: [AB#546856](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546856)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24468.
