### ISSUE TITLE
[Request-For-External] codeunit 360 "Accounting Period Mgt." AccPeriodEndDate / AccPeriodStartOrEnd

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#27145]
### Describe the request

Hello colleagues,

Please make procedures global in codeunit 360 "Accounting Period Mgt.":
AccPeriodEndDate
AccPeriodStartOrEnd

### Additional context

We would like to use standard function instead of ours.
Internal work item: [AB#546862](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546862)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26357.
