### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - OnPmtTolCustBeforeCalcCustApplnAmount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27147]
### Describe the request

Hello, can you please add a new Event OnPmtTolCustBeforeCalcCustApplnAmount in codeunit 426 "Payment Tolerance Management"?

```
    procedure PmtTolCust(var CustLedgEntry: Record "Cust. Ledger Entry"): Boolean
    var
.
.
.
        CustEntryApplId := UserId();
        if CustEntryApplId = '' then
            CustEntryApplId := '***';
        OnPmtTolCustOnAfterSetCustEntryApplId(CustLedgEntry, CustEntryApplId);

        DelCustPmtTolAcc(CustLedgEntry, CustEntryApplId);
        CustLedgEntry.CalcFields("Remaining Amount");
        OnPmtTolCustBeforeCalcCustApplnAmount(CustLedgEntry);
        CalcCustApplnAmount(
          CustLedgEntry, GLSetup, AppliedAmount, ApplyingAmount, AmounttoApply, PmtDiscAmount,
          MaxPmtTolAmount, CustEntryApplId, ApplnRoundingPrecision);

        OriginalAppliedAmount := AppliedAmount;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnPmtTolCustBeforeCalcCustApplnAmount(var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and need to recalculate it for it's further uses.
Internal work item: [AB#546859](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546859)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24468.
