### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - OnUpdateCustAmountsForApplicationAfterCalcRemainingAmount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27153]
### Describe the request

Hello, can you please add a new Event OnUpdateCustAmountsForApplicationAfterCalcRemainingAmount in codeunit 426 "Payment Tolerance Management"?

```
    local procedure UpdateCustAmountsForApplication(var AppliedCustLedgEntry: Record "Cust. Ledger Entry"; var CustLedgEntry: Record "Cust. Ledger Entry"; var TempAppliedCustLedgEntry: Record "Cust. Ledger Entry" temporary)
    begin
        AppliedCustLedgEntry.CalcFields("Remaining Amount");
        OnUpdateCustAmountsForApplicationAfterCalcRemainingAmount(AppliedCustLedgEntry);
        TempAppliedCustLedgEntry := AppliedCustLedgEntry;
        if CustLedgEntry."Currency Code" <> AppliedCustLedgEntry."Currency Code" then
            AppliedCustLedgEntry.UpdateAmountsForApplication(CustLedgEntry."Posting Date", CustLedgEntry."Currency Code", true, true);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnUpdateCustAmountsForApplicationAfterCalcRemainingAmount(var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and need to recalculate it for it's further uses.
Internal work item: [AB#546983](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546983)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24468.
