### ISSUE TITLE
[Event Request] codeunit 5632 "FA Jnl.-Post Line" - OnCalcResultOnDisposalAfterCalcGainLoss

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27160]
### Describe the request

Hello, can you please add a new Event OnCalcResultOnDisposalAfterCalcGainLoss in codeunit 5632 "FA Jnl.-Post Line"?

```
    local procedure CalcResultOnDisposal(FANo: Code[20]; DeprBookCode: Code[10]): Integer
    var
        FADeprBook: Record "FA Depreciation Book";
        FALedgEntry: Record "FA Ledger Entry";
    begin
        FADeprBook."FA No." := FANo;
        FADeprBook."Depreciation Book Code" := DeprBookCode;
        FADeprBook.CalcFields("Gain/Loss");
        OnCalcResultOnDisposalAfterCalcGainLoss(FADeprBook);
        if FADeprBook."Gain/Loss" <= 0 then
            exit(FALedgEntry."Result on Disposal"::Gain);

        exit(FALedgEntry."Result on Disposal"::Loss);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnCalcResultOnDisposalAfterCalcGainLoss(var FADepreciationBook: Record "FA Depreciation Book")
    begin
    end;
```

### Additional context

We have additional values to calculate the Gain/Loss and need to recalculate it to get the correct return value.
Internal work item: [AB#546990](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546990)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.
