### ISSUE TITLE
[EVENT REQUESTS] Inventory Profile (Table 99000853)

### ISSUE THREAD

**Issue by MarkusW-BSG** [microsoft/ALAppExtensions#27166]
### Describe the request

For implementing process customizations from BC13 to the current BC24 I need one new event in Table 99000853 related to special quantity handling.

To calculate the correct quantity for reservation (as described in the additional context it's vital to have more than one Unit and Quantity for any process) I need a new event

**Function CalcReservedQty**
![image](https://github.com/user-attachments/assets/0f566477-0096-4a71-8d0c-29c92e207fe5)

Within the repeat until loop the following event should be called
**CalcReservedQtyOnGetNextRecord(ReservationEntry);**

Thinking about it, for other implementations (not for ours) an event giving the ability to change the filter for the reservations being valid for the function, an event after setting the filters would be a nice for customizations.

![image](https://github.com/user-attachments/assets/38201306-912d-4cab-9be6-0a472ce1cd98)
**CalcReservedQtyOnAfterSetFilters(ReservationEntry);**

Sorry, but going on migrating the changes I found three more places I need new events. Sorry for that. :-)

**2. Event - Function TransferQtyFromItemTrgkEntry**
![image](https://github.com/user-attachments/assets/3e4620d7-5a50-4efe-a014-da4bd0965c16)
**OnAfterTransferQtyFromItemTrgkEntry(Rec, TrackingReservationEntry)**

**3. Event - Function ReduceQtyByItemTracking**
![image](https://github.com/user-attachments/assets/1bdef312-8034-495d-90a4-04344951b625)
**OnAfterReduceQtyByItemTracking(Rec, NewInventoryProfile)**

**4. Event - Function ChangeSign**
![image](https://github.com/user-attachments/assets/411ef550-87d6-4723-b097-73a1a11dca78)
**OnAfterChangeSign(Rec);**

### Additional context

In Steel Industry, one quantity is not enough for any process. Therefore our current Business Central is customized for using a second quantity. Every item has furthermore two inventories instead of one. An inventory measured by the base UOM (the standard) and a second one measure by its second UOM.

Example:
A customer orders approx. 2 tons of steel sheets, /.100 pieces.
Quantity: 2000
UOM: KG
Sec. Quantity: 100
Sec. UOM: PCE
Internal work item: [AB#546995](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546995)

**Comment by MarkusW-BSG** [comment]
@JesperSchulz 

Hi Jesper, I am sorry but I added three more events I need to be added. Can you please approve them and add to your work item?

Thanks very much and sorry for that. :-)

Greetings
Markus

**Comment by JakovljevicDusan** [comment]
Instead of CalcReservedQtyOnGetNextRecord(ReservationEntry), new event outside loop is implemented: OnCalcReservedQtyOnBeforeReservationEntryLoop(ReservationEntry, ReservedQty, IsHandled);

**Comment by MarkusW-BSG** [comment]
@JakovljevicDusan 
Hi Dusan,
thanks for the info. Thanks for this information. Would work for me and I think for others, too. :-)

Do you have any information about the three more events I added to the request?

Regards
Markus

**Comment by JakovljevicDusan** [comment]
> @JakovljevicDusan Hi Dusan, thanks for the info. Thanks for this information. Would work for me and I think for others, too. :-)
> 
> Do you have any information about the three more events I added to the request?
> 
> Regards Markus

Yes, to be released in 25.1

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24822.
