### ISSUE TITLE
[EVENT REQUESTS] Table 99000849 "Action Message Entry"

### ISSUE THREAD

**Issue by MarkusW-BSG** [microsoft/ALAppExtensions#27164]
### Describe the request

For implementing process customizations from BC13 to the current BC24 I need three new events in Table 7504 related to special quantity handling.

For function SumUp it is necessary to have three new events in this function

**New Events**
![image](https://github.com/user-attachments/assets/0a104c4f-fccb-4604-b40a-ea33e9389e80)

   procedure SumUp(var ActionMessageEntry: Record "Action Message Entry")
    var
        ActionMessageEntry2: Record "Action Message Entry";
        ReservEntry: Record "Reservation Entry";
        ReservEntry2: Record "Reservation Entry";
        ProdOrderComp: Record "Prod. Order Component";
        TypeArray: array[5] of Boolean;
    begin
        ActionMessageEntry2 := ActionMessageEntry;
...
        ActionMessageEntry."New Date" := 0D;
        ActionMessageEntry.Quantity := 0;
       **OnAfterAssignMessageEntry(ActionMessageEntry,ActionMessageEntry2);**
...
        ActionMessageEntry.Type := ActionMessageEntry.Type::" ";
        if ActionMessageEntry2.FindSet() then
            repeat
                if ActionMessageEntry2.Quantity <> 0 then begin
                    ActionMessageEntry.Quantity += ActionMessageEntry2.Quantity;
                    TypeArray[2] := true;
                   **OnAfterAssignQuantity(ActionMessageEntry,ActionMessageEntry2);**
...
        if TypeArray[5] then
            ActionMessageEntry.Type := ActionMessageEntry.Type::Cancel;
        **OnAfterAssignEntryType(ActionMessageEntry,ActionMessageEntry2);**
        ActionMessageEntry2."New Date" := ActionMessageEntry."New Date";
...

 

### Additional context

In Steel Industry, one quantity is not enough for any process. Therefore our current Business Central is customized for using a second quantity. Every item has furthermore two inventories instead of one. An inventory measured by the base UOM (the standard) and a second one measure by its second UOM.

Example:
A customer orders approx. 2 tons of steel sheets, /.100 pieces.
Quantity: 2000
UOM: KG
Sec. Quantity: 100
Sec. UOM: PCE
Internal work item: [AB#546994](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546994)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25075.
