### ISSUE TITLE
[Event Request] table 25 "Vendor Ledger Entry" - OnValidateAmounttoApplyBeforeError

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27172]
### Describe the request

Hello, can you please add a new Event OnValidateAmounttoApplyBeforeError in table 25 "Vendor Ledger Entry"?

```
        field(84; "Amount to Apply"; Decimal)
        {
            AutoFormatExpression = Rec."Currency Code";
            AutoFormatType = 1;
            Caption = 'Amount to Apply';

            trigger OnValidate()
            begin
                TestField(Open, true);
                CalcFields("Remaining Amount");
                OnValidateAmounttoApplyBeforeError(Rec);

                if AreOppositeSign("Amount to Apply", "Remaining Amount") then
                    FieldError("Amount to Apply", StrSubstNo(MustHaveSameSignErr, FieldCaption("Remaining Amount")));

                if Abs("Amount to Apply") > Abs("Remaining Amount") then
                    FieldError("Amount to Apply", StrSubstNo(MustNotBeLargerErr, FieldCaption("Remaining Amount")));
            end;
        }
```

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateAmounttoApplyBeforeError(var VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and need to recalculate it to prevent the field error from been thrown falsely.
Internal work item: [AB#547367](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547367)

**Comment by AndersLarsenMicrosoft** [comment]
same as https://github.com/microsoft/ALAppExtensions/issues/27171

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
