### ISSUE TITLE
[Event Request] table 23 Vendor - OnAfterGetBalanceAsCustomer

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27173]
### Describe the request

Hello, can you please add a new Event OnAfterGetBalanceAsCustomer in table 23 Vendor?

```
    procedure GetBalanceAsCustomer(var LinkedCustomerNo: Code[20]) BalanceAsCustomer: Decimal;
    var
        Customer: Record Customer;
    begin
        BalanceAsCustomer := 0;
        LinkedCustomerNo := GetLinkedCustomer();
        if Customer.Get(LinkedCustomerNo) then begin
            OnGetBalanceAsCustomerOnBeforeCalcBalance(Customer);
            Customer.CalcFields("Balance (LCY)");
            BalanceAsCustomer := Customer."Balance (LCY)";
            OnAfterGetBalanceAsCustomer(Customer, BalanceAsCustomer);
        end;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetBalanceAsCustomer(Customer: Record Customer; var BalanceAsCustomer: Decimal)
    begin
    end;
```

### Additional context

We have additional values to calculate the Balance (LCY) and need to recalculate it to prevent false values from being shown.
Internal work item: [AB#547366](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547366)

**Comment by AndersLarsenMicrosoft** [comment]
already added

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
