### ISSUE TITLE
[Event Request] codeunit 86 "Sales-Quote to Order" - OnRunOnBeforeValidateSalesPerson

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27177]
### Describe the request

Hello, can you please add a new Event OnRunOnBeforeValidateSalesPerson in codeunit 86 "Sales-Quote to Order"?

```
    trigger OnRun()
    var
.
.
.
        Cust.Get(Rec."Sell-to Customer No.");
        Cust.CheckBlockedCustOnDocs(Cust, Rec."Document Type"::Order, true, false);
        if Rec."Sell-to Customer No." <> Rec."Bill-to Customer No." then begin
            Cust.Get(Rec."Bill-to Customer No.");
            Cust.CheckBlockedCustOnDocs(Cust, Rec."Document Type"::Order, true, false);
        end;
        Rec.CalcFields("Amount Including VAT", "Work Description");
        OnRunOnBeforeValidateSalesPerson(Rec);
        Rec.ValidateSalesPersonOnSalesHeader(Rec, true, false);

        Rec.CheckForBlockedLines();

        CheckInProgressOpportunities(Rec);

        CreateSalesHeader(Rec, Cust);

        TransferQuoteToOrderLines(SalesQuoteLine, Rec, SalesOrderLine, SalesOrderHeader, Cust);
        OnAfterInsertAllSalesOrderLines(SalesOrderLine, Rec, SalesOrderHeader);
```

```
    [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeValidateSalesPerson(var SalesHeader: Record "Sales Header")
    begin
    end;
```

### Additional context

We have additional values to calculate the Amount Including VAT and need to recalculate it before being inserted.
Internal work item: [AB#547369](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547369)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23666.
