### ISSUE TITLE
[Event Request] table 296 "Reminder Line" - OnValidateAppliesToDocumentNoAfterCalcRemainingAmount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27185]
### Describe the request

Hello, can you please add a new Event OnValidateAppliesToDocumentNoAfterCalcRemainingAmount in table 296 "Reminder Line"?

```
        field(28; "Applies-to Document No."; Code[20])
        {
.
.
.
                    GetReminderLevel(ReminderLevel, NextLineFeeLevel, NextLineFeeLevel);
                    "Posting Date" := ReminderHeader."Posting Date";
                    "Document Date" := ReminderHeader."Document Date";
                    "Due Date" := ReminderHeader."Due Date";
                    "No. of Reminders" := NextLineFeeLevel;

                    CustLedgEntry.CalcFields("Remaining Amount");
                    OnValidateAppliesToDocumentNoAfterCalcRemainingAmount(CustLedgEntry);
                    Validate(Amount, ReminderLevel.GetAdditionalFee(
                        CustLedgEntry."Remaining Amount",
                        ReminderHeader."Currency Code",
                        true,
                        ReminderHeader."Posting Date"));
```

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateAppliesToDocumentNoAfterCalcRemainingAmount(var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and have to recalculate it before it gets validated onto the Amount.
Internal work item: [AB#547373](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547373)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25389.
