### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt." - OnUpdateSalesInvoiceDiscountValueAfterCalcAmount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27189]
### Describe the request

Hello, can you please add a new Event OnUpdateSalesInvoiceDiscountValueAfterCalcAmount in codeunit 6620 "Copy Document Mgt."?

```
    local procedure UpdateSalesInvoiceDiscountValue(var SalesHeader: Record "Sales Header")
    begin
        if IncludeHeader and RecalculateLines then begin
            SalesHeader.CalcFields(Amount);
            OnUpdateSalesInvoiceDiscountValueAfterCalcAmount(SalesHeader);
            if SalesHeader."Invoice Discount Value" > SalesHeader.Amount then begin
                SalesHeader."Invoice Discount Value" := SalesHeader.Amount;
                SalesHeader.Modify();
            end;
        end;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnUpdateSalesInvoiceDiscountValueAfterCalcAmount(var SalesHeader: Record "Sales Header")
    begin
    end;
```

### Additional context

We have additional values to calculate the Amount and need to recalculate it before being allocated and the record being modified.
Internal work item: [AB#547398](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547398)

**Comment by TKapitan** [comment]
It's not needed for your use case, you can use the existing event (with one more calcfield).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
