### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt." - OnUpdateVendLedgEntryAfterCalcRemainingAmount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27188]
### Describe the request

Hello, can you please add a new Event OnUpdateVendLedgEntryAfterCalcRemainingAmount in codeunit 6620 "Copy Document Mgt."?

```
    procedure UpdateVendLedgEntry(var ToPurchHeader: Record "Purchase Header"; FromDocType: Enum "Gen. Journal Document Type"; FromDocNo: Code[20])
    var
.
.
.
            if VendLedgEntry.FindFirst() then begin
                if FromDocType = "Purchase Document Type From"::"Posted Invoice" then begin
                    ToPurchHeader."Applies-to Doc. Type" := ToPurchHeader."Applies-to Doc. Type"::Invoice;
                    ToPurchHeader."Applies-to Doc. No." := FromDocNo;
                end else begin
                    ToPurchHeader."Applies-to Doc. Type" := ToPurchHeader."Applies-to Doc. Type"::"Credit Memo";
                    ToPurchHeader."Applies-to Doc. No." := FromDocNo;
                end;
                VendLedgEntry.CalcFields("Remaining Amount");
                OnUpdateVendLedgEntryAfterCalcRemainingAmount(VendLedgEntry);
                VendLedgEntry."Amount to Apply" := VendLedgEntry."Remaining Amount";
                VendLedgEntry."Accepted Payment Tolerance" := 0;
                VendLedgEntry."Accepted Pmt. Disc. Tolerance" := false;
                CODEUNIT.Run(CODEUNIT::"Vend. Entry-Edit", VendLedgEntry);
            end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnUpdateVendLedgEntryAfterCalcRemainingAmount(var VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and need to recalculate it before being allocated and the record being modified.
Internal work item: [AB#547397](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547397)

**Comment by TKapitan** [comment]
It's not needed for your use case, you can use the existing event (with one more calcfield).

**Comment by TKapitan** [comment]
Directly in the Vend. Entry - Modify

**Comment by mildddd** [comment]
Hi,

As @TKapitan suggested, you can use the event in Vend. Entry - Modify, but also OnBeforeUpdateVendLedgEntry in codeunit 6620.

I will close the case.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
