### ISSUE TITLE
[Event Request] codeunit 1255 "Match Bank Payments" - OnSetCustAppicationDataBeforeCustEntryEdit

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27198]
### Describe the request

Hello, can you please add a new Event OnSetCustAppicationDataBeforeCustEntryEdit in codeunit 1255 "Match Bank Payments"?

```
    local procedure SetCustAppicationData(EntryNo: Integer; AppliesToID: Code[50])
    var
        CustLedgEntry: Record "Cust. Ledger Entry";
    begin
        CustLedgEntry.Get(EntryNo);
        CustLedgEntry.CalcFields("Remaining Amount");
        CustLedgEntry."Applies-to ID" := AppliesToID;
        CustLedgEntry."Amount to Apply" := CustLedgEntry."Remaining Amount";
        OnSetCustAppicationDataBeforeCustEntryEdit(CustLedgEntry);
        CODEUNIT.Run(CODEUNIT::"Cust. Entry-Edit", CustLedgEntry);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnSetCustAppicationDataBeforeCustEntryEdit(var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and need to recalculate it before being allocated and the record being modified.
Internal work item: [AB#547388](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547388)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26242.
