### ISSUE TITLE
[Event Request] table 1248 "Ledger Entry Matching Buffer" - OnInsertFromVendorLedgerEntryBeforeSetFields

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27197]
### Describe the request

Hello, can you please add a new Event OnInsertFromVendorLedgerEntryBeforeSetFields in table 1248 "Ledger Entry Matching Buffer"?

```
    procedure InsertFromVendorLedgerEntry(VendorLedgerEntry: Record "Vendor Ledger Entry"; UseLCYAmounts: Boolean; var UsePaymentDiscounts: Boolean)
    begin
        Clear(Rec);
        OnInsertFromVendorLedgerEntryBeforeSetFields(VendorLedgerEntry);
        "Entry No." := VendorLedgerEntry."Entry No.";
        "Account Type" := "Account Type"::Vendor;
        "Account No." := VendorLedgerEntry."Vendor No.";
        "Due Date" := VendorLedgerEntry."Due Date";
        "Posting Date" := VendorLedgerEntry."Posting Date";
        "Document No." := VendorLedgerEntry."Document No.";
        "External Document No." := VendorLedgerEntry."External Document No.";
        "Payment Reference" := VendorLedgerEntry."Payment Reference";
```

```
    [IntegrationEvent(false, false)]
    local procedure OnInsertFromVendorLedgerEntryBeforeSetFields(var VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;
```

### Additional context

We have additional values to calculate the Remaining Amount and need to recalculate it before being allocated and the record being modified.
Internal work item: [AB#547399](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547399)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23666.
