### ISSUE TITLE
[Extensibility request] 5964 "Service Quote" - make IsServiceLinesEditable protected

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#27202]
### Describe the request

Hello,
we need to set the variable IsServiceLinesEditable from a page extension. Can you therefore please define the variable IsServiceLinesEditable as a protected variable.

```
    var
        ServOrderMgt: Codeunit ServOrderManagement;
        UserMgt: Codeunit "User Setup Management";
        FormatAddress: Codeunit "Format Address";
        ChangeExchangeRate: Page "Change Exchange Rate";
        IsBillToCountyVisible: Boolean;
        IsSellToCountyVisible: Boolean;
        IsShipToCountyVisible: Boolean;
        DocNoVisible: Boolean;

    protected var
        IsServiceLinesEditable: Boolean;
```

Or another variant, set the function to global:
```
    procedure ActivateFields()
    begin
        IsSellToCountyVisible := FormatAddress.UseCounty(Rec."Country/Region Code");
        IsBillToCountyVisible := FormatAddress.UseCounty(Rec."Bill-to Country/Region Code");
        IsShipToCountyVisible := FormatAddress.UseCounty(Rec."Ship-to Country/Region Code");
        IsServiceLinesEditable := Rec.ServiceLinesEditable();
    end;
```

Or the best way, which also fixes the scrolling problem, as in the service order:
```
    trigger OnAfterGetCurrRecord()
    begin
        SetControlAppearance();
    end;

    local procedure SetControlAppearance()
    begin
        IsServiceLinesEditable := Rec.ServiceLinesEditable();
    end;
```
Many thanks

### Additional context

We copy the service documents, as in sales, with the header. The service quote lines cannot be edited after copy with header. The same problem exists when scrolling through the data records if the data record with which the page was opened did not have a customer. Currently, the variable is only set when opening and validating the customer on the page. 
Internal work item: [AB#547394](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547394)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24757.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25748.
