### ISSUE TITLE
[Change Request] table 5601 "FA Ledger Entry" und table 179 "Reversal Entry" - field(27; "FA Posting Category"; Option)

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27218]
### Describe the request

Hello, can you please change the Option field "FA Posting Category" in table 15 "G/L Account" and table 179 "Reversal Entry" from Option to an Enum?

```
table 5601 "FA Ledger Entry"
{
.
.
.
        field(12; "FA Posting Category"; Enum "FA Ledger Entry FA Posting Cat")
        {
            Caption = 'FA Posting Category';
        }
```

```
table 179 "Reversal Entry"
{
.
.
.
        field(27; "FA Posting Category"; Enum "FA Ledger Entry FA Posting Cat")
        {
            AccessByPermission = TableData "Fixed Asset" = R;
            Caption = 'FA Posting Category';
        }
```

```
enum 50007 "FA Ledger Entry FA Posting Cat"
{

    Extensible = true;

    value(0; " ")
    {
    }
    value(1; "Disposal")
    {
        Caption = 'Verkauf';
    }
    value(2; "Bal. Disposal")
    {
        Caption = 'Gegenkto. Verkauf';
    }
}
```

### Additional context

We have to extend the Enum for our posting routine.
Internal work item: [AB#547606](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547606)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26016.
