### ISSUE TITLE
[Event Request] table 37 "Sales Line" - Field 5407 "Unit of Measure Code" - OnValidateUnitOfMeasureCodeOnBeforeTestField

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27219]
### Describe the request

Hello, can you please add a new Event OnValidateUnitOfMeasureCodeOnBeforeTestField in table 37 "Sales Line" for field 5407 "Unit of Measure Code" ?

            trigger OnValidate()
            var
                Item: Record Item;
                UnitOfMeasureTranslation: Record "Unit of Measure Translation";
                ShouldPlanPriceCalc: Boolean;
            begin
                TestJobPlanningLine();
                TestStatusOpen();

                IsHandled := false;
                OnValidateUnitOfMeasureCodeOnBeforeTestField(Rec, IsHandled);
                if not IsHandled then begin
                    TestField("Quantity Shipped", 0);
                    TestField("Qty. Shipped (Base)", 0);
                    TestField("Return Qty. Received", 0);
                    TestField("Return Qty. Received (Base)", 0);
                end;

                if "Unit of Measure Code" <> xRec."Unit of Measure Code" then begin
                    TestField("Shipment No.", '');
                    TestField("Return Receipt No.", '');
                end;

                CheckAssocPurchOrder(FieldCaption("Unit of Measure Code"));

                if "Unit of Measure Code" = '' then
                    "Unit of Measure" := ''
                else begin
                    OnValidateUnitOfMeasureCodeOnBeforeGetUnitOfMeasure(Rec, xRec, SalesHeader, CurrFieldNo);
                    if not UnitOfMeasure.Get("Unit of Measure Code") then
                        UnitOfMeasure.Init();
                    "Unit of Measure" := UnitOfMeasure.Description;
                    GetSalesHeader();
                    if SalesHeader."Language Code" <> '' then begin
                        UnitOfMeasureTranslation.SetRange(Code, "Unit of Measure Code");
                        UnitOfMeasureTranslation.SetRange("Language Code", SalesHeader."Language Code");
                        if UnitOfMeasureTranslation.FindFirst() then
                            "Unit of Measure" := UnitOfMeasureTranslation.Description;
                    end;
                end;
                OnValidateUnitOfMeasureCodeOnAfterGetUnitOfMeasure(Rec, SalesHeader);

                ItemReferenceMgt.EnterSalesItemReference(Rec);
                OnValidateUnitOfMeasureCodeOnAfterEnterSalesItemReference(Rec);

                case Type of
                    Type::Item:
                        begin
                            GetItem(Item);
                            GetUnitCost();
                            ShouldPlanPriceCalc := "Unit of Measure Code" <> xRec."Unit of Measure Code";
                            OnValidateUnitOfMeasureCodeOnAfterCalcShouldPlanPriceCalc(Rec, ShouldPlanPriceCalc);
                            if ShouldPlanPriceCalc then
                                PlanPriceCalcByField(FieldNo("Unit of Measure Code"));
                            CheckItemAvailable(FieldNo("Unit of Measure Code"));
                            "Gross Weight" := Item."Gross Weight" * "Qty. per Unit of Measure";
                            "Net Weight" := Item."Net Weight" * "Qty. per Unit of Measure";
                            "Unit Volume" := Item."Unit Volume" * "Qty. per Unit of Measure";
                            "Units per Parcel" :=
                              Round(Item."Units per Parcel" / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision());
                            "Qty. Rounding Precision" := UOMMgt.GetQtyRoundingPrecision(Item, "Unit of Measure Code");
                            "Qty. Rounding Precision (Base)" := UOMMgt.GetQtyRoundingPrecision(Item, Item."Base Unit of Measure");

                            OnAfterAssignItemUOM(Rec, Item, CurrFieldNo, xRec);
                            if (xRec."Unit of Measure Code" <> "Unit of Measure Code") and (Quantity <> 0) then
                                SalesWarehouseMgt.SalesLineVerifyChange(Rec, xRec);
                            if "Qty. per Unit of Measure" > xRec."Qty. per Unit of Measure" then
                                InitItemAppl(false);
                            OnValidateUnitOfMeasureCodeOnAfterGetItemData(Rec, xRec, Item);
                        end;
                    Type::Resource:
                        begin
                            if "Unit of Measure Code" = '' then begin
                                GetResource();
                                "Unit of Measure Code" := Resource."Base Unit of Measure";
                            end;
                            AssignResourceUoM();
                            if "Unit of Measure Code" <> xRec."Unit of Measure Code" then
                                PlanPriceCalcByField(FieldNo("Unit of Measure Code"));
                            ApplyResUnitCost(FieldNo("Unit of Measure Code"));
                        end;
                    Type::"G/L Account", Type::"Fixed Asset",
                    Type::"Charge (Item)", Type::" ":
                        "Qty. per Unit of Measure" := 1;
                end;
                UpdateQuantityFromUOMCode();
                UpdateUnitPriceByField(FieldNo("Unit of Measure Code"));
            end;

[IntegrationEvent(false, false)]
local procedure OnValidateUnitOfMeasureCodeOnBeforeTestField(var Rec : Record "Sales Line"; var IsHandled : Boolean)
begin
end;

### Additional context

We want to avoid displaying testfield() errors to the user.
Internal work item: [AB#547607](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547607)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
