### ISSUE TITLE
[Change Request] table 15 "G/L Account" - field(9; "Income/Balance"; Option)

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27216]
### Describe the request

Hello, can you change the Option field "Income/Balance" in table 15 "G/L Account" from Option to an Enum?

```
        field(9; "Income/Balance"; Enum "G/L Acc Income/Balance")
        {
            Caption = 'Income/Balance/Finance';

            trigger OnValidate()
            var
                CostType: Record "Cost Type";
            begin
                if ("Income/Balance" = "Income/Balance"::"Balance Sheet") and ("Cost Type No." <> '') then begin
                    if CostType.Get("No.") then begin
                        CostType."G/L Account Range" := '';
                        CostType.Modify();
                    end;
                    "Cost Type No." := '';
                end;
            end;
        }
```

```
enum 50000 "G/L Acc Income/Balance"
{
    AssignmentCompatibility = true;
    Extensible = true;

    value(0; "Income Statement") { Caption = 'GuV'; }
    value(1; "Balance Sheet") { Caption = 'Bilanz'; }
}
```

### Additional context

We have to extend the Enum for our posting routine. Unfortunately we can not use the Enum ???G/L Account Income/Balance??? because it has more OptionMemebers than the original Option field.
Internal work item: [AB#547601](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547601)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26125.
