### ISSUE TITLE
[Event Request] codeunit 5601 "FA Insert G/L Account" - OnCalcDisposalAmountAfterCalcFields

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27213]
### Describe the request

Hello, can you please add a new Event OnCalcDisposalAmountAfterCalcFields in codeunit 5601 "FA Insert G/L Account"?

```
    local procedure CalcDisposalAmount(FALedgEntry: Record "FA Ledger Entry")
    begin
        DisposalEntryNo := TempFAGLPostBuf."Entry No.";
        FADeprBook.Get(FALedgEntry."FA No.", FALedgEntry."Depreciation Book Code");
        FADeprBook.CalcFields("Proceeds on Disposal", "Gain/Loss");
        OnCalcDisposalAmountAfterCalcFields(FADeprBook);
        DisposalAmount := FADeprBook."Proceeds on Disposal";
        GainLossAmount := FADeprBook."Gain/Loss";
        FAPostingGr2.Get(FALedgEntry."FA Posting Group");

        OnAfterCalcDisposalAmount(FAPostingGr2);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnCalcDisposalAmountAfterCalcFields(var FADepreciationBook: Record "FA Depreciation Book")
    begin
    end;
```

### Additional context

We have additional values to calculate the GainLoss and need to recalculate it to prevent false values from being shown.
Internal work item: [AB#547600](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547600)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.
