### ISSUE TITLE
[Change Request] table 220 "Business Unit" - field(23; "File Format"; Option)

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27217]
### Describe the request

Hello, can you please change the Option field "File Format" in table 220 "Business Unit" from Option to an Enum?

```
        field(23; "File Format"; Enum "Business Unit File Format")
        {
            Caption = 'File Format';
        }
```

```
enum 50005 "Business Unit File Format"
{
    Extensible = true;
    value(0; "Version 4.00 or Later (.xml)")
    {
        Caption = 'Version 4.00 oder h??her (.xml)';
    }
    value(1; "Version 3.70 or Earlier (.txt)")
    {
        Caption = 'Version 3.70 oder niedriger (.txt)';
    }
}
```

### Additional context

We have to extend the Enum for an external file format.
Internal work item: [AB#547603](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/547603)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25843.
