### ISSUE TITLE
Read Access to Global variables

### ISSUE THREAD

**Issue by jbeckerBER** [microsoft/ALAppExtensions#2722]
Hi,

would it be possible to have read-only access from a extension to global variables of an object?
E.g. I want to know on page 46 if the Variable "LocationCodeMandatory" is true or not.
But this is just an example. It would be great if this would be possible in general in all object types.

**Comment by ikoletic** [comment]
This seems like a product suggestion already recorded on [BC Ideas](https://experience.dynamics.com/ideas/idea/?ideaid=8aa70fdb-2b67-e911-b047-0003ff688f4c). Please vote for it there.
