### ISSUE TITLE
[Change Request] table 7317 "Warehouse Receipt Line" - field(21; "Qty. to Receive"; Decimal) - "OnBeforeValidateQtyToReceive" function in "Validate" trigger

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27227]
### Describe the request

Hello, please can you add the ???xRec??? record parameter as input to the ???OnBeforeValidateQtyToReceive(Rec, IsHandled, CurrFieldNo)??? function?

OnBeforeValidateQtyToReceive(Rec, IsHandled, CurrFieldNo);
to
OnBeforeValidateQtyToReceive(xRec,Rec, IsHandled, CurrFieldNo);

### Additional context

We need to check certain values in the ???xRec??? record before validating the new value selected for the ???Qty to receive??? field. We need to be able to reassign the old value of this field (xRec) in certain cases.
Internal work item: [AB#548193](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548193)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
