### ISSUE TITLE
[Event Request] CU304 "No. Series - Impl." - procedure GetNextNo()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#27229]
### Describe the request

Add 2 event in CU304 "No. Series - Impl." - procedure GetNextNo()

### Additional context

procedure GetNextNo(var NoSeriesLine: Record "No. Series Line"; UsageDate: Date; HideErrorsAndWarnings: Boolean): Code[20]
begin
----------------------- ADD EVENT ----------------------
OnBeforeGetNextNo(var NoSeriesLine);

.....

----------------------- ADD EVENT ----------------------
OnAfterGetNextNo(var NoSeriesLine);
Internal work item: [AB#548200](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548200)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
