### ISSUE TITLE
Copy Document Mgt. OnAfterCopyServContractLines has a wrong obsolete message pointing to wrong replacement

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#27224]
### Describe the request

Copy Document Mgt. - OnAfterCopyServContractLines has a wrong obsolete message pointing to wrong replacement.

```AL
    [IntegrationEvent(false, false)]
    [Obsolete('Replaced by event OnGetServiceContractTypeCaseElse in codeunit Copy Service Contract Mgt.', '24.0')]
    local procedure OnAfterCopyServContractLines(ToServiceContractHeader: Record "Service Contract Header"; FromDocType: Option; FromDocNo: Code[20]; var FormServiceContractLine: Record "Service Contract Line")
    begin
    end;
```

I assume it will be replaced by `OnAfterCopyServiceContractLines`.

### Additional context

Better developer experience.
Applies to BC 24.x

**Comment by JesperSchulz** [comment]
Would you like to fix that? In that case I would transfer the issue to the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

**Comment by MODUSCarstenScholling** [comment]
Hi @JesperSchulz, I would love to, but both myself and my colleagues have too many other tasks and blocking issues to deal with since the release of BC 24 that I don't have the time for non-blocking things. That was just something I stumbled across a few weeks ago.

**Comment by JesperSchulz** [comment]
That's perfectly fine - I know the feeling 😉 I'll get this code updated myself. I will close this issue, given it doesn't related to extensibility or code in this repo.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24186.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 24195.
