### ISSUE TITLE
[Event Request] Table 5878 Phys. Invt. Record Line - Procedure CheckSerialNo() - OnBeforeCheckSerialNo and OnValidateSerialNoOnAfterCheckSerialNo

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#27228]
### Describe the request

Hello, 
Please add these two events to table Table 5878 "Phys. Invt. Record Line":

1. OnBeforeCheckSerialNo

    procedure CheckSerialNo()
    var
        PhysInvtRecordLine: Record "Phys. Invt. Record Line";
		
	IsHandled: Boolean; // NEW
    
    begin
	
        // >> NEW
	Clear(IsHandled);
	OnBeforeCheckSerialNo(Rec, IsHandled);
	if not IsHandled then begin
	// << NEW
			
		PhysInvtRecordLine.Reset();
		PhysInvtRecordLine.SetRange("Order No.", "Order No.");
		PhysInvtRecordLine.SetRange("Item No.", "Item No.");
		if PhysInvtRecordLine.FindSet() then
			repeat
				if "Serial No." <> '' then
					if PhysInvtRecordLine."Serial No." = "Serial No." then
						if (PhysInvtRecordLine."Line No." <> "Line No.") or (PhysInvtRecordLine."Recording No." <> "Recording No.") then
							if Abs(PhysInvtRecordLine."Quantity (Base)") + Abs("Quantity (Base)") > 1 then
								Error(SerialNoAlreadyExistErr, "Serial No.", "Item No.");
			until PhysInvtRecordLine.Next() = 0;
			
	end; // NEW
		
    end;
	
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckSerialNo(var PhysInvtRecordLine: Record "Phys. Invt. Record Line"; var IsHandled: Boolean)
    begin
    end;

2.  OnValidateSerialNoOnAfterCheckSerialNo

	field(130; "Serial No."; Code[50])
	{	
		[...]

		trigger OnValidate()
		var
			IsHandled: Boolean; // NEW
		begin
			CheckSerialNo();
			
			// >> NEW
			Clear(IsHandled);
			OnValidateSerialNoOnAfterCheckSerialNo(Rec, IsHandled);
			if not IsHandled then
			// << NEW
			
				if "Serial No." <> '' then
					Validate(Quantity, 1);
		end;
	}
		
    [IntegrationEvent(false, false)]
    local procedure OnValidateSerialNoOnAfterCheckSerialNo(var PhysInvtRecordLine: Record "Phys. Invt. Record Line"; var IsHandled: Boolean)
    begin
    end;	

Best Regards
Thomas H??sel

### Additional context

We need to circumvent all "Serial No."-quantity-equals-one-checks for our customer uses different UoM and e.g. all checks target the Quantity fields instead of Quantity(Base).
Internal work item: [AB#548192](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548192)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
