### ISSUE TITLE
[Event Parameter Request] Codeunit 442 > OnBeforePostPrepayments > PreviewMode

### ISSUE THREAD

**Issue by supercruel** [microsoft/ALAppExtensions#2723]
We need the Parameter "PreviewMode" in the "OnBeforePostPrepayments" event in Codeunit 442 for our AddOn.

Alternative or maybe even better:
2 new [External] Functions in the Codeunit:
GetSuppressCommit
GetPreviewMode

Thanks

**Comment by AlexanderYakunin** [comment]
Second option implemented
