### ISSUE TITLE
[Event Request] Codeunit 8612 "Config. Template Management" - Function "InsertTemplate" - Add event OnAfterModifyRecordWithField

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27232]
### Describe the request

Hello, can you please add a new Event "OnAfterModifyRecordWithField" in codeunit 8612 "Config. Template Management" - Function "InsertTemplate" ?

LOCAL InsertTemplate(VAR RecRef : RecordRef;ConfigTemplateHeader : Record "Config. Template Header";SkipFields : Boolean;VAR TempSkipField : Record Field)
ConfigTemplateLine.SETRANGE("Data Template Code",ConfigTemplateHeader.Code);
IF ConfigTemplateLine.FINDSET THEN
  REPEAT
    CASE ConfigTemplateLine.Type OF
      ConfigTemplateLine.Type::Field:
        IF ConfigTemplateLine."Field ID" <> 0 THEN BEGIN
          IF SkipFields THEN
            SkipCurrentField := ShouldSkipField(TempSkipField,ConfigTemplateLine."Field ID",ConfigTemplateLine."Table ID")
          ELSE
            SkipCurrentField := FALSE;

          IF NOT SkipCurrentField THEN BEGIN
            FieldRef := RecRef.FIELD(ConfigTemplateLine."Field ID");
            ModifyRecordWithField(RecRef,FieldRef,ConfigTemplateLine."Default Value",ConfigTemplateLine."Language ID");
          END;
        END;
      ConfigTemplateLine.Type::Template:
        IF ConfigTemplateLine."Template Code" <> '' THEN
          IF ConfigTemplateHeader2.GET(ConfigTemplateLine."Template Code") THEN
            IF ConfigTemplateHeader2."Table ID" = ConfigTemplateHeader."Table ID" THEN
              InsertTemplate(RecRef,ConfigTemplateHeader2,SkipFields,TempSkipField)
            ELSE BEGIN
              UpdatingRelatedTable := TRUE;
              RecRef2.OPEN(ConfigTemplateHeader2."Table ID");
              UpdateRecord(ConfigTemplateHeader2,RecRef2);
              UpdatingRelatedTable := FALSE;
            END;
    END;

    OnAfterModifyRecordWithField(RecRef,ConfigTemplateHeader);

  UNTIL ConfigTemplateLine.NEXT = 0;

[IntegrationEvent] OnAfterModifyRecordWithField(VAR RecRef : RecordRef;ConfigTemplateHeader : Record "Config. Template Header")
begin
end;

### Additional context

We need to update information in related tables at the end of each iteration.
Internal work item: [AB#548199](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548199)

**Comment by Groenbech96** [comment]
Do you have to do it for both Template and Field type?

**Comment by ROUCHY-Yoann** [comment]
Yes, please.

**Comment by ROUCHY-Yoann** [comment]
I confirm, thank you.

**Comment by Groenbech96** [comment]
After internal discussion, we concluded that **no more** events should be added InsertTemplate 
There is already 4 events in this function. 

I will close this as wont fix.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
