### ISSUE TITLE
[Event Request] CU5944 - Procedure CheckServContractNextPlannedServiceDate() - OnBeforeFindServContractLine

### ISSUE THREAD

**Issue by bkurmann** [microsoft/ALAppExtensions#27237]
### Describe the request

Please add a new integration event "OnBeforeFindServContractLine" in Codeunit 5944 SignServContractDoc in prodedure CheckServContractNextPlannedServiceDate. Parameter is ServContractLine of type var.
  

    local procedure CheckServContractNextPlannedServiceDate(ServContractHeader: Record "Service Contract Header"): Boolean
    var
        ServContractLine: Record "Service Contract Line";
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        ServContractLine.Reset();
        ServContractLine.SetRange("Contract Type", ServContractHeader."Contract Type");
        ServContractLine.SetRange("Contract No.", ServContractHeader."Contract No.");
        ServContractLine.SetRange("Next Planned Service Date", 0D);

        OnBeforeFindServContractLine(ServContractLine);           // new event   

        if ServContractLine.FindFirst() then
            if not ConfirmManagement.GetResponseOrDefault(
                 StrSubstNo(Text022, ServContractLine.FieldCaption("Next Planned Service Date")), true)
            then
                exit(false);
        exit(true);
    end;

### Additional context

In our service extension we allow additional line types like "Title" on service contract lines.
When the service contract is signed we have no possibilities to skip the confirmation dialog in function CheckServContractNextPlannedServiceDate that is shown because "Next Planned Service Date" is of course 0D in title lines.

The event would give us the possibility to put addtional filters on Service Contract Lines before the check is executed.
Internal work item: [AB#548955](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548955)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24747.
