### ISSUE TITLE
[EVENT REQUESTS] Codeunit 22 ("Item Jnl.-Post Line")

### ISSUE THREAD

**Issue by MarkusW-BSG** [microsoft/ALAppExtensions#27231]
### Describe the request

It is possible to swap Codeunit 22 for nearly all functionality to an own copy of this codeunit. 

Direct Run via event OnBeforeRunWithCheck
Unapply via event OnBeforeUnApply
![image](https://github.com/user-attachments/assets/e935e159-f22d-4426-b36f-a81e5af59091)

But this is not implemented for all functionality called from outside the codeunit, therefore this should be implemented to be fully customizable for the following functions

**1. Re-Apply**
![image](https://github.com/user-attachments/assets/7507b43d-bc3a-456f-81ff-8635ee197107)
**Requested event:**
OnBeforeReApply(ItemLedgEntry: Record "Item Ledger Entry"; ApplyWith: Integer; var IsHandled: boolean)

**2. All the other application- and re-application functions except UnApply**
All functions except Unapply and Re-Apply do not seem to need events as they call the above functions in a way (but I am not sure, please check :-)

**3. RunPostWithReservation**
![image](https://github.com/user-attachments/assets/9c588114-2c3a-4476-9935-dd28682178e1)
**Requested event:**
OnBeforeRunPostWithReservation(var ItemJnlLine2: Record "Item Journal Line"; var ReservationEntry: Record "Reservation Entry"; var ReturnValue: Boolean; var IsHandled: boolean)

Call should be
OnBeforeRunPostWithReservation(...)
If IsHandled then exit(ReturnValue)

**4. CollectValueEntryRelation**
![image](https://github.com/user-attachments/assets/3c0dc22c-155b-477e-8e8a-8848676a1e2e)

**Requested event:**
analogous to OnBeforeCollectTrackingSpecification

**5. CollectItemEntryRelation**
See 4.

** 6. UndoValuePostingWithJob**
![image](https://github.com/user-attachments/assets/ea4a4472-7472-488f-a40f-47302bfd5a20)
See 1.

### Additional context

In Steel Industry, one quantity is not enough for any process. Therefore our current Business Central is customized for using a second quantity. Every item has furthermore two inventories instead of one. An inventory measured by the base UOM (the standard) and a second one measure by its second UOM.

Example:
A customer orders approx. 2 tons of steel sheets, /.100 pieces.
Quantity: 2000
UOM: KG
Sec. Quantity: 100
Sec. UOM: PCE

As the changes in Codeunit 22 are too massive and can not be handled via the existing events, we want to do our changes via the entry points in Codeunit 22 and pass to "our" customized Codeunit 22, where only a minor amount of new events is needed. :-) 
Internal work item: [AB#548196](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548196)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25798.
