### ISSUE TITLE
[Event Request] table 18 Customer - "Enterprise No." (11310) (Belgium)

### ISSUE THREAD

**Issue by Sara-Handerek** [microsoft/ALAppExtensions#27238]
### Describe the request

On the customer table, we want to be able to by-pass/adapt the standard validation done on the "Enterprise No." field, which is a field specific to the Belgium package. We would like to have the possibility to by-pass the validation, like what is done for the "VAT Registration No." which is its counterpart.

### **Current Code**
        field(11310; "Enterprise No."; Text[50])
        {
            Caption = 'Enterprise No.';

            trigger OnValidate()
            begin
                if "Enterprise No." <> DelChr("Enterprise No.", '=', '0123456789') then begin
                    if not Country.DetermineCountry("Country/Region Code") then
                        Error(Text11302, FieldCaption("Enterprise No.") + ' ' + "No.");
                    if not EnterpriseNoMgt.MOD97Check("Enterprise No.") then
                        Error(Text11300, FieldCaption("Enterprise No."));
                    "VAT Registration No." := '';
                end;
            end;
        }

### **Extensibility Request**
        field(11310; "Enterprise No."; Text[50])
        {
            Caption = 'Enterprise No.';

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateEnterpriseNo(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;

                if "Enterprise No." <> DelChr("Enterprise No.", '=', '0123456789') then begin
                    if not Country.DetermineCountry("Country/Region Code") then
                        Error(Text11302, FieldCaption("Enterprise No.") + ' ' + "No.");
                    if not EnterpriseNoMgt.MOD97Check("Enterprise No.") then
                        Error(Text11300, FieldCaption("Enterprise No."));
                    "VAT Registration No." := '';
                end;
            end;
        }

### Additional context

We want to be able to by-pass the standard validation done on the "Enterprise No." field, which is a field specific toe the Belgium package. For the moment, we can only enter a enterprise number in this field if our customer has the 'BE' country specified. However, in our Business, we have customer that have a main address in Belgium, but are using a VAT number from another neighbor country. Therefore, we are blocked.
Internal work item: [AB#548965](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548965)

**Comment by Sara-Handerek** [comment]
Sorry, in the additional context, I made a mistake in my explanation.
Here is the correction, if you need it ;)
"...we have customer that have a main address in a neighbor country (NL/FR), but are using a VAT number from BELGIUM. Therefore, we are blocked as we cannot enter the info in the field.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24337.
