### ISSUE TITLE
[Change Request] codeunit 90 "Purch.-Post" - Procedure "SaveTempWhseSplitSpec" - Remove local property

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27236]
### Describe the request

Hello, can you please change the procedure "SaveTempWhseSplitSpec" from local to global in codeunit 90 ""Purch.-Post"" ?

local procedure SaveTempWhseSplitSpec(PurchLine3: Record "Purchase Line")
begin
...
end;

TO : 

procedure SaveTempWhseSplitSpec(PurchLine3: Record "Purchase Line")
begin
...
end;

### Additional context

We need to call this function from a new instance of codeunit 90.
Internal work item: [AB#548953](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548953)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24772.

**Comment by ROUCHY-Yoann** [comment]
Hello, 
Can you confirm that this request will be taken into account?

Because there have been 2 versions since the validation of the ticket but still not delivered.
Thanks in advance.

**Comment by JesperSchulz** [comment]
I just verified that the change was completed. It was made for 2025 wave 1 and the changes will hence release in April. We usually don't backport "request for external"s to minor releases.
