### ISSUE TITLE
[Event Change Request] Codeunit 5988 "Serv-Documents Mgt."- OnBeforeServCrMemoLineInsert

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27249]
### Describe the request

We want to copy the value of a blob field from the service line to the cr. memo line. To do this, we request to add the global ServLine variable as a parameter in the OnBeforeServCrMemoLineInsert event:

```
local procedure PrepareCrMemoLine(var PassedServLine: Record "Service Line")
begin
    // TempSrvLine is initialized (in Sales module) in RoundAmount
    // procedure, and likely does not differ from initial ServLine.
    ServCrMemoLine.Init();
    ServCrMemoLine.TransferFields(PassedServLine);
    ServCrMemoLine."Document No." := ServCrMemoHeader."No.";
    ServCrMemoLine.Quantity := PassedServLine."Qty. to Invoice";
    ServCrMemoLine."Quantity (Base)" := PassedServLine."Qty. to Invoice (Base)";
    PassedServLine.CalcFields(PassedServLine."Service Item Line Description");
    ServCrMemoLine."Service Item Line Description" := PassedServLine."Service Item Line Description";
    //NEW BEGIN
    OnBeforeServCrMemoLineInsert(ServCrMemoLine, PassedServLine, ServLine);
    //NEW END
    ServCrMemoLine.Insert();
    OnAfterServCrMemoLineInsert(ServCrMemoLine, PassedServLine);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeServCrMemoLineInsert(var ServiceCrMemoLine: Record "Service Cr.Memo Line"; ServiceLine: Record "Service Line"; ServLine: Record "Service Line")
begin
end;
```

### Additional context

The Blob field in the PassedServLine parameter is empty and therefore currently not copied because the TempServiceLine is passed to the procedure.
Internal work item: [AB#548958](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548958)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24747.
