### ISSUE TITLE
[Event Request] Report 12152 "Create Subcontr.Transf. Order"

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#27241]
### Describe the request

In function CheckPurchLine of report 12152 I need an event OnAfterProdOrderComponentSetFilters(var ProdOrderComponent: Record Prod. Order Component; PurchLine: Record Purchase Line)
![image](https://github.com/user-attachments/assets/d629e171-47b5-40bb-94f0-a8a7ea943816)

### Additional context

I need this event to add additional filters based on custom fields on Production Order Component
Internal work item: [AB#548964](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548964)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24337.
