### ISSUE TITLE
[Event Change Request] Codeunit 5988 "Serv-Documents Mgt."- OnBeforeServInvLineInsert 

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27248]
### Describe the request

We want to copy the value of a blob field from the service line to the invoice line. To do this, we request to add the global ServLine variable as a parameter in the OnBeforeServInvLineInsert event:

```
local procedure PrepareInvoiceLine(var PassedServLine: Record "Service Line")
begin
    ServInvLine.Init();
    ServInvLine.TransferFields(PassedServLine);
    ServInvLine."Document No." := ServInvHeader."No.";
    ServInvLine.Quantity := PassedServLine."Qty. to Invoice";
    ServInvLine."Quantity (Base)" := PassedServLine."Qty. to Invoice (Base)";
    PassedServLine.CalcFields(PassedServLine."Service Item Line Description");
    ServInvLine."Service Item Line Description" := PassedServLine."Service Item Line Description";

    if PassedServLine."Document Type" = PassedServLine."Document Type"::Order then
        ServInvLine."Order No." := PassedServLine."Document No.";
    //NEW BEGIN
    OnBeforeServInvLineInsert(ServInvLine, PassedServLine, ServLine);
    //NEW END
    ServInvLine.Insert();
    OnAfterServInvLineInsert(ServInvLine, PassedServLine);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeServInvLineInsert(var ServiceInvoiceLine: Record "Service Invoice Line"; ServiceLine: Record "Service Line"; ServLine: Record "Service Line")
begin
end;
```

### Additional context

The Blob field in the PassedServLine parameter is empty and therefore currently not copied because the TempServiceLine is passed to the procedure.
Internal work item: [AB#548956](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548956)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24747.
