### ISSUE TITLE
codeunit 5802 "Inventory Posting To G/L" - event publisher

### ISSUE THREAD

**Issue by exnihiloo** [microsoft/ALAppExtensions#27243]
### Describe the request

Hello, would it be possible to add OnBeforeInitGLItemLedgerRelation event to codeunit 5802 "Inventory Posting To G/L" to the procedure CreateGLItemLedgRelationEntry, like this:

``````al
local procedure CreateGLItemLedgRelationEntry(GLReg: Record "G/L Register")
var
    IsHandled: Boolean; //new variable
begin
IsHandled := false;
OnBeforeInitGLItemLedgerRelation(IsHandled); //New Event
if IsHandled then
     exit;
GLItemLedgRelation.Init();
GLItemLedgRelation."G/L Entry No." := GLReg."To Entry No.";
GLItemLedgRelation."Value Entry No." := TempGLItemLedgRelation."Value Entry No.";
GLItemLedgRelation."G/L Register No." := GLReg."No.";
OnBeforeGLItemLedgRelationInsert(GLItemLedgRelation, TempGlobalInvtPostingBuffer, GLReg, TempGLItemLedgRelation);
GLItemLedgRelation.Insert();
       ...
``````

``````al
[IntegrationEvent(false, false)]
local procedure OnBeforeInitGLItemLedgerRelation(var IsHandled: Boolean; )
begin
end;
``````

Internal work item: [AB#548957](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548957)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24822.
