### ISSUE TITLE
[Change Request] codeunit 90 "Purch.-Post" - Procedure "OnBeforePostItemJnlLine" - Add parameter "WhseRcptHeader" (Record "Warehouse Receipt Header")

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27240]
### Describe the request

Hello, can you please add to the procedure "OnBeforePostItemJnlLine", the input parameter "WhseRcptHeader" : Record "Warehouse Receipt Header", in codeunit 90 ""Purch.-Post"" ?

[IntegrationEvent(false, false)]
local procedure OnBeforePostItemJnlLine(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var QtyToBeReceived: Decimal; var QtyToBeReceivedBase: Decimal; var QtyToBeInvoiced: Decimal; var QtyToBeInvoicedBase: Decimal; var ItemLedgShptEntryNo: Integer; var ItemChargeNo: Code[20]; var TrackingSpecification: Record "Tracking Specification"; CommitIsSupressed: Boolean; var IsHandled: Boolean; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; var Result: Integer)
begin
end;

TO : 

[IntegrationEvent(false, false)]
local procedure OnBeforePostItemJnlLine(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var QtyToBeReceived: Decimal; var QtyToBeReceivedBase: Decimal; var QtyToBeInvoiced: Decimal; var QtyToBeInvoicedBase: Decimal; var ItemLedgShptEntryNo: Integer; var ItemChargeNo: Code[20]; var TrackingSpecification: Record "Tracking Specification"; CommitIsSupressed: Boolean; var IsHandled: Boolean; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; var Result: Integer; var WhseRcptHeader: Record "Warehouse Receipt Header")
begin
end;

### Additional context

We need to check some parameter on "Warehouse Receipt Header" record before initializing and post Item Journal line.
Internal work item: [AB#548954](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548954)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24747.
