### ISSUE TITLE
Add parameter at function OnModifyOnBeforeTestCheckPrinted on table "Gen. journal Line"

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27255]
### Describe the request

Dear team,
Please help to add parameter (xRec: record "Gen. journal Line") at function OnModifyOnBeforeTestCheckPrinted on table "Gen. journal Line" as below
![2024-09-13_10h47_16](https://github.com/user-attachments/assets/c2be4735-4f49-400f-82c3-3e81f78e29e4)
Thank you

### Additional context

N/A
Internal work item: [AB#548944](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548944)

**Comment by GiangLNT56** [comment]
Could you please reply me?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26357.
