### ISSUE TITLE
[Event Request] add a new parameter to the publisher OnTransferFieldData of coudeunit 5336 "Integration Record Synch."

### ISSUE THREAD

**Issue by omerfaruknav** [microsoft/ALAppExtensions#27259]
### Describe the request

Please add global variable ParameterSourceRecordRef as a parameter to the publisher OnTransferFieldData of codeunit 5336 "Integration Record Synch." 

### Additional context

Reason: When the required field contains two fields on its primary key and the currently synced field is the second field of the pk , I need to get the first field from the source record. (For example, I want to sync Item Variant field on sales line, to pass it to Dataverse with correct variant record I need to know the item no on the line.) 
Internal work item: [AB#548948](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548948)

**Comment by onbuyuka** [comment]
I don't see the need for ParameterSourceRecordRef in this scenario. You can always get to the source RecordRef from source FieldRef: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-record-method
