### ISSUE TITLE
Need to add publisher at functions ShowVendorEntries and ShowVendorEntriesDue on page "Vendor Purchase Lines" 

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27252]
### Describe the request

Dear team, 
On page "Vendor Purchase Lines", please help to add 2 more publishers at function ShowVendorEntries and function ShowVendorEntriesDue for additional filter on record VendorLedgEntry before running page.
![2024-09-12_17h50_02](https://github.com/user-attachments/assets/2b912b86-d458-4010-8c42-49efa0cbbf47)
Thank you.

### Additional context

I'd like to add some more additional filter on Vendor Ledger Entry before the page is run.
Internal work item: [AB#548949](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548949)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24752.
