### ISSUE TITLE
Request to add publisher at function ReverseAmounts on table "Invoice Posting Buffer"

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27254]
### Describe the request

Dear team,
On table "Invoice Posting Buffer", please help to add publisher after function ReverseAmounts to have more customization on this
![2024-09-12_17h51_57](https://github.com/user-attachments/assets/70d0aed9-6baa-4ffb-98fe-9e687424697f)
Thank you.

### Additional context

I'd like to have more customization on this function
Internal work item: [AB#548947](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/548947)

**Comment by GiangLNT56** [comment]
Hi there, Can you reply me?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.
