### ISSUE TITLE
table 5900 "Service Header" SetHideValidationDialog

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27266]
### Describe the request

I'm using the procedure SetHideValidationDialog in table 5900 "Service Header".
But I'm still getting a question when the currency factor is updated.
Looks like it's missing a check.

```
Current:
    local procedure ConfirmCurrencyFactorUpdate()
    var
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        if ConfirmManagement.GetResponseOrDefault(Text015, true) then
            Validate("Currency Factor")
        else
            "Currency Factor" := xRec."Currency Factor";
    end;

New:
    local procedure ConfirmCurrencyFactorUpdate()
    var
        ConfirmManagement: Codeunit "Confirm Management";
        Confirmed:Boolean;
    begin
        if not GetHideValidationDialog() then
            Confirmed := ConfirmManagement.GetResponseOrDefault(Text015, true);
        else
            Confirmed := true;

        if Confirmed then
            Validate("Currency Factor")
        else
            "Currency Factor" := xRec."Currency Factor";
    end;
```

### Additional context

View description.
Internal work item: [AB#550941](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550941)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25201.
