### ISSUE TITLE
[Event Request] Codeunit 1255 "Match Bank Payments" Fix OnFindMatchingEntriesOnBeforeFindFirst parameters

### ISSUE THREAD

**Issue by kontax85** [microsoft/ALAppExtensions#27264]
### Describe the request

The parameters used to call OnFindMatchingEntriesOnBeforeFindFirst are: _TempBankAccReconciliationLine, TempLedgerEntryMatchingBuffer, AccountType, ApplyEntries._

The event has the following parameters:
_var TempBankAccReconciliationLine: Record "Bank Acc. Reconciliation Line" temporary; var TempLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; AccountType: Enum "Gen. Journal Account Type"; var SkipOtherEntries: Boolean_

The last parameter ApplyEntries is actually SkipOtherEntries on the event publisher, the current situation is misleading and the variable SkipOtherEntries cannot actually be updated by the event.

Suggested update: add an additional parameter to actually manage SkipOtherEntries variable.

### Additional context

The variable _SkipOtherEntries_ cannot be updated, but there is a wrong parameter in the event publisher.
Internal work item: [AB#549349](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549349)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26242.
