### ISSUE TITLE
[Event Request] Codeunit 7201 "CDS Integration Impl." - GetOwningTeamName

### ISSUE THREAD

**Issue by SidiSaleck** [microsoft/ALAppExtensions#27268]
### Describe the request

Dear Microsoft Team,

We require the addition of an event to allow us to modify the OwningTeamName to an already existing team, similar to how it's handled for the BusinessUnitName (procedure GetDefaultBusinessUnitName). This would enable us to adapt the standard integration to meet our specific requirements.

For context, we would need something along the lines of the following code:

```
local procedure GetOwningTeamName(BusinessUnitName: Text) TeamName: Text[160]
var
    IsHandled: Boolean;
begin
   // >>> NEW
    OnBeforeGetOwningTeamName(TeamName, IsHandled);
    if IsHandled then
        exit;
  //  <<<

    TeamName := CopyStr(StrSubstNo(TeamNameTemplateTok, BusinessUnitName), 1, MaxStrLen(TeamName));
end;
```

Thank you for considering this request, and we look forward to your response.

Kind regards,
Sidi

### Additional context

The goal is to trigger the event OnBeforeGetOwningTeamName, which would allow us to manage the assignment of the owning team in a flexible way.
Internal work item: [AB#549352](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549352)

**Comment by onbuyuka** [comment]
We cannot implement this. GetOwningTeamName is a procedure that takes a Business Unit Name and puts "BCI - " in front of it. This a helper procedure, and this event would change the behavior of this procedure completely.
