### ISSUE TITLE
[Change Request] codeunit 5624 "Cancel FA Ledger Entries"

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27275]
### Describe the request

Hello, can you please set the local procedure InsertGenJnlLine to global and init the DeprBookCode? 

```
    procedure InsertGenJnlLine(var FALedgEntry: Record "FA Ledger Entry"; BalAccount: Boolean)
    var
        FAInsertGLAcc: Codeunit "FA Insert G/L Account";
    begin
        if not GenJnlUsedOnce then begin
            GenJnlLine.LockTable();
            if DeprBook.Code = '' then
                DeprBook.Get(FALedgEntry."Depreciation Book Code");
            FAJnlSetup.GenJnlName(DeprBook, GenJnlLine, GenJnlNextLineNo);
            GenJnlUsedOnce := true;
            GenJnlDocumentNo :=
              FAJnlSetup.GetGenJnlDocumentNo(GenJnlLine, FALedgEntry."FA Posting Date", false);
        end;

        FALedgEntry.MoveToGenJnl(GenJnlLine);
        GenJnlLine."Document No." := GenJnlDocumentNo;
```

### Additional context

Function is needed inside our Event Subscriber for Event OnTransferLineOnBeforeInsertJnlLine.
Together with making function global. Depreciation Book might not initialized if called. So we added a "get" there.

Internal work item: [AB#549347](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549347)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25725.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26133.
