### ISSUE TITLE
Codeunit 10752 "SII Doc. Upload Management" : Add event OnInvokeBatchSoapRequestOnBeforeGetCertificate

### ISSUE THREAD

**Issue by yvoj** [microsoft/ALAppExtensions#27273]
### Describe the request

Hi team,

For ES users we need to be able to send an SII-request without the SII-certificate included in the XML.
To be able to do so, we need a new event in CU 10752 in local procedure '_InvokeBatchSoapRequest_'.
New event : _OnInvokeBatchSoapRequestOnBeforeGetCertificate.

**Current:** 
local procedure InvokeBatchSoapRequest(SIISession: Record "SII Session"; var TempSIIHistoryBuffer: Record "SII History" temporary; RequestText: Text; RequestType: Option InvoiceIssuedRegistration,InvoiceReceivedRegistration,PaymentSentRegistration,PaymentReceivedRegistration,CollectionInCashRegistration; var ResponseText: Text): Boolean
    var
        CertificateEnabled: Boolean;
        Cert: DotNet X509Certificate2;
        WebRequest: DotNet WebRequest;
        HttpWebRequest: DotNet HttpWebRequest;
        RequestStream: DotNet Stream;
        Encoding: DotNet Encoding;
        ByteArray: DotNet Array;
        Uri: DotNet Uri;
        HttpWebResponse: DotNet HttpWebResponse;
        StatusCode: DotNet HttpStatusCode;
        WebServiceUrl: Text;
        StatusDescription: Text[250];
    begin
        Session.LogMessage('0000CNO', StrSubstNo(BatchSoapRequestMsg, RequestType), Verbosity::Normal, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', VATSIITok);
        CertificateEnabled := GetIsolatedCertificate(Cert);
        if not CertificateEnabled then begin
            Session.LogMessage('0000CNP', NoCertificateErr, Verbosity::Error, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', VATSIITok);
            ProcessBatchResponseCommunicationError(TempSIIHistoryBuffer, NoCertificateErr);
            exit(false);
        end;
        case RequestType of
            RequestType::InvoiceIssuedRegistration:
                WebServiceUrl := SIISetup.InvoicesIssuedEndpointUrl;
            RequestType::InvoiceReceivedRegistration:
                WebServiceUrl := SIISetup.InvoicesReceivedEndpointUrl;
            RequestType::PaymentReceivedRegistration:
                WebServiceUrl := SIISetup.PaymentsReceivedEndpointUrl;
            RequestType::PaymentSentRegistration:
                WebServiceUrl := SIISetup.PaymentsIssuedEndpointUrl;
            RequestType::CollectionInCashRegistration:
                WebServiceUrl := SIISetup.CollectionInCashEndpointUrl;
        end;
        OnInvokeBatchSoapRequestOnBeforeStoreRequestXML(RequestText, RequestType, WebServiceUrl);
        SIISession.StoreRequestXml(RequestText);
        Commit();
		.....
		......
		.......
 
**To adjust:**
local procedure InvokeBatchSoapRequest(SIISession: Record "SII Session"; var TempSIIHistoryBuffer: Record "SII History" temporary; RequestText: Text; RequestType: Option InvoiceIssuedRegistration,InvoiceReceivedRegistration,PaymentSentRegistration,PaymentReceivedRegistration,CollectionInCashRegistration; var ResponseText: Text): Boolean
    var
        CertificateEnabled: Boolean;
        Cert: DotNet X509Certificate2;
        WebRequest: DotNet WebRequest;
        HttpWebRequest: DotNet HttpWebRequest;
        RequestStream: DotNet Stream;
        Encoding: DotNet Encoding;
        ByteArray: DotNet Array;
        Uri: DotNet Uri;
        HttpWebResponse: DotNet HttpWebResponse;
        StatusCode: DotNet HttpStatusCode;
        WebServiceUrl: Text;
        StatusDescription: Text[250];
        **IsHandled: Boolean;**
    begin
        Session.LogMessage('0000CNO', StrSubstNo(BatchSoapRequestMsg, RequestType), Verbosity::Normal, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', VATSIITok);
		**OnInvokeBatchSoapRequestOnBeforeGetCertificate(RequestText, RequestType, Session, IsHandeld);
		if IsHandeld then 
			exit;**
        CertificateEnabled := GetIsolatedCertificate(Cert);
        if not CertificateEnabled then begin
            Session.LogMessage('0000CNP', NoCertificateErr, Verbosity::Error, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', VATSIITok);
            ProcessBatchResponseCommunicationError(TempSIIHistoryBuffer, NoCertificateErr);
            exit(false);
        end;
        case RequestType of
            RequestType::InvoiceIssuedRegistration:
                WebServiceUrl := SIISetup.InvoicesIssuedEndpointUrl;
            RequestType::InvoiceReceivedRegistration:
                WebServiceUrl := SIISetup.InvoicesReceivedEndpointUrl;
            RequestType::PaymentReceivedRegistration:
                WebServiceUrl := SIISetup.PaymentsReceivedEndpointUrl;
            RequestType::PaymentSentRegistration:
                WebServiceUrl := SIISetup.PaymentsIssuedEndpointUrl;
            RequestType::CollectionInCashRegistration:
                WebServiceUrl := SIISetup.CollectionInCashEndpointUrl;
        end;
        OnInvokeBatchSoapRequestOnBeforeStoreRequestXML(RequestText, RequestType, WebServiceUrl);
        SIISession.StoreRequestXml(RequestText);
        Commit();
		.....
		......
		.......

### Additional context

Our Spanish customers want to be able to create the SII-XML message without the SII-certificate included and send it to an intermediate certificate-provider.
This provider has a private 'vault' where ALL SII-certificates are stored. The provider will add the proper certificate to the message and forward the message to the Spanish SII-VAT-declaration endpoint.
The Spanish customer is not allowed (legally) to handle and/or store the certificates themselves.
By this restriction, they can not use the SII out-of-the-box solution in BC.  
Internal work item: [AB#549341](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549341)

**Comment by JesperSchulz** [comment]
@yvoj, I assume this is the event publisher you would like?
```
    [IntegrationEvent(false, false)]
    local procedure OnInvokeBatchSoapRequestOnBeforeGetCertificate(var RequestText: Text; RequestType: Option InvoiceIssuedRegistration,InvoiceReceivedRegistration,PaymentSentRegistration,PaymentReceivedRegistration,CollectionInCashRegistration; SIISession: Record "SII Session"; var IsHandled: Boolean);
    begin
    end;
```

By session, I assume you mean SIISession? Please also pay attention to "var" in list of parameters.

**Comment by SorenKlemmensen** [comment]
Hi Jesper, I think that looks correct, but I will check it with our team and we will get back to you to confirm. Thanks for picking this one up so fast.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24680.

**Comment by JesperSchulz** [comment]
Event as suggested above will ship with 25.1.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24763.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 24801.
