### ISSUE TITLE
[Event Request] T38 "Purchase Header" - procedure OnValidate() - field "Buy-from Vendor No."

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#27277]
### Describe the request

Add a event in Table 38 "Purchase Header" - procedure OnValidate() - field "Buy-from Vendor No."

### Additional context

field(2; "Buy-from Vendor No."; Code[20])

----------------------- ADD EVENT ----------------------
OnValidateBuyFromVendorNoOnBeforeValidateResponsibilityCenter(Rec, xRec, CurrFieldNo, IsHandled);
if not IsHandled then
   "Responsibility Center" := UserSetupMgt.GetRespCenter(1, Vend."Responsibility Center");
Internal work item: [AB#549348](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549348)

**Comment by AleksandricMarko** [comment]
Already exist event
![image](https://github.com/user-attachments/assets/13b30a65-cfe0-45c3-9ab0-54aa186291c1)
