### ISSUE TITLE
[Event Request] Purchase Header - Validate Buy-from Vendor No. check Registered

### ISSUE THREAD

**Issue by KacMac** [microsoft/ALAppExtensions#27271]
### Describe the request

Hi AL-Team,
due to customer customization on Purchase Header table, we need to have additional event exposed. It concerns au version of BC.

In onvalidate "Buy-from Vendor No." there is this code

                GetVend("Buy-from Vendor No.");
                if not (BasManagement.VendorRegistered("Buy-from Vendor No.") or Vend."Foreign Vend") then begin
                    PurchSetup.Get();
                    if PurchSetup."Vendor Registration Warning" then
                        if not Confirm(Text1500000, false, "Buy-from Vendor No.") then
                            Error('');
                end;
 

requested code:

                GetVend("Buy-from Vendor No.");
                OnBeforeCheckVendorRegistered(Rec, SkipCheckVendorRegistered);
                if not SkipCheckVendorRegistered then
                  if not (BasManagement.VendorRegistered("Buy-from Vendor No.") or Vend."Foreign Vend") then begin
                      PurchSetup.Get();
                      if PurchSetup."Vendor Registration Warning" then
                          if not Confirm(Text1500000, false, "Buy-from Vendor No.") then
                              Error('');
                  end;

Requested Publisher signature: [IntegrationEvent(false, false)] local procedure OnBeforeCheckVendorRegistered(PurchaseHeader: Record "Purchase Header"; var SkipCheckVendorRegistered: Boolean)

Ideally above piece of code could be moved into separate procedure where ishandled pattern could be used.

### Additional context

Some customers still need to process Purchase Invoices for Vendors which aren't registered, but Items are GST Free.
Internal work item: [AB#549340](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549340)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24747.
