### ISSUE TITLE
Event Update: Add ShowDialog in OnAfterBankDepositPost event in codeunit 1690 "Bank Deposit-Post"

### ISSUE THREAD

**Issue by daniloziva** [microsoft/ALAppExtensions#27270]
### Describe the request

Dear MSFT team,

I would appreciate it if you could add a parameter to Bank Deposit Post that lets me control displaying of the Posted Bank Deposit page after the deposit is posted.

Before
```
        OnAfterBankDepositPost(Rec, PostedBankDepositHeader);

        Page.Run(Page::"Posted Bank Deposit", PostedBankDepositHeader);
```

After
```
        OnAfterBankDepositPost(Rec, PostedBankDepositHeader, ShowDialog);

        if ShowDialog then
          Page.Run(Page::"Posted Bank Deposit", PostedBankDepositHeader);
```

### Additional context

Our clients use bank deposits in combination with Shopify and Paypal payouts, so there is a lot of automated posting of Bank deposits. With the current setup, we cannot accomplish this. 
Internal work item: [AB#549356](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549356)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.

**Comment by daniloziva** [comment]
Thanks!
