### ISSUE TITLE
[Event Request] Table 5062 Attachment - OnAfterConstDiskFileName

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27284]
### Describe the request

We want to overwrite the DiskFileName in the ConstDiskFileName() procedure. Therefore, I request the following event:
```
procedure ConstDiskFileName() DiskFileName: Text
begin
    DiskFileName := "Storage Pointer" + '\' + Format("No.") + '.' + "File Extension";
//NEW
    OnAfterConstDiskFileName(DiskFileName, Rec);
//NEW
end;

[IntegrationEvent(false, false)]
local procedure OnAfterConstDiskFileName(var DiskFileName: Text; Attachment: Record Attachment)
begin
end;
```

### Additional context

Allows you to change the DiskFileName with your own business logic.
Internal work item: [AB#549877](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549877)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24822.
