### ISSUE TITLE
[Change Request] page 5855 Posted Purchase Document Lines – Make procedure ChangeSubMenu(NewMenuType: Integer) global and variable CurrentMenuType protected

### ISSUE THREAD

**Issue by SinaTitgemeyer** [microsoft/ALAppExtensions#27286]
### Describe the request

Hi,
we have a request about the page 5855 ???Posted Purchase Document Lines".

Could you please change the variable ???CurrentMenuType??? to protected and change the procedure ChangeSubMenu(NewMenuType: Integer) to global, similar to the page 5850 "Posted Sales Document Lines".

```
var
        CopyDocMgt: Codeunit "Copy Document Mgt.";
        OldMenuType: Integer;
        LinesNotCopied: Integer;
        MissingExCostRevLink: Boolean;
        Text000: Label 'The document lines that have a G/L account that does not allow direct posting have not been copied to the new document.';
        OriginalQuantity: Boolean;
        Text002: Label 'Document Type Filter';
        PostedRcptsVisible: Boolean;
        PostedInvoicesVisible: Boolean;
        PostedReturnShptsVisible: Boolean;
        PostedCrMemosVisible: Boolean;
        CurrentMenuTypeOpt: Option x0,x1,x2,x3;

    protected var
        ToPurchHeader: Record "Purchase Header";
        ShowRevLineEnable: Boolean;
        ShowRevLinesOnly: Boolean;
//Start
        CurrentMenuType: Integer;
//End
```

```
//Start
    procedure ChangeSubMenu(NewMenuType: Integer)
//End
    begin
        if OldMenuType <> NewMenuType then
            SetSubMenu(OldMenuType, false);
        SetSubMenu(NewMenuType, true);
        OldMenuType := NewMenuType;
        CurrentMenuType := NewMenuType;
    end;
```

### Additional context

We want to set an item filter on the subpages. Also we want the user to get the last used document filter type when he opens the page.
Internal work item: [AB#549884](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/549884)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
