### ISSUE TITLE
[Event Request] OnBeforePageBackgroundTaskCompleted on page 9060 "SO Processor Activities"

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#27292]
### Describe the request

On page 9060 "SO Processor Activities", we need to have Integration event in the "OnPageBackgroundTaskCompleted" trigger. Adding an event will help us to add extra filters we need to the table. Right now , we tried OnAfterGetRecord trigger and we are setting range on table, finding the record and assigning some values to the table fields, but it is giving error on notifications - "Activities: Microsoft Dynamics 365 Business Central Server attempted to issue a client callback to show a confirmation dialog box: Your change might update related records, which can take a while. Do you want to continue? (Page 9060 SO Processor Activities). Client callbacks are not supported on Microsoft Dynamics 365 Business Central Server. The disallowed callback was issued from the OnPageBackgroundTaskCompleted or OnPageBackgroundTaskError trigger."

![image](https://github.com/user-attachments/assets/8e0456c4-662e-46b3-b076-2cb3f8e0660d)

This error is coming because of code "CurrPage.update" in OnPageBackgroundTaskCompleted  trigger.

new code with event added:-  

 trigger OnPageBackgroundTaskCompleted(TaskId: Integer; Results: Dictionary of [Text, Text])
    var
        SOActivitiesCalculate: Codeunit "SO Activities Calculate";
        UIHelperTriggers: Codeunit "UI Helper Triggers";
        PrevUpdatedOn: DateTime;
    begin
        if TaskId <> CalcTaskId then
            exit;
        OnBeforePageBackgroundTaskCompleted(TaskId,CalcTaskId ,Results,Handled);
        if Handled  then
         exit;
                ............
end;

[IntegrationEvent(true, true)]
 procedure OnBeforePageBackgroundTaskCompleted(TaskId: Integer; CalcTaskId :Integer ; Results: Dictionary of [Text, Text]:var Handled : Boolean)
begin
end;

1. 

### Additional context

Need set range and find the record but as in OnPageBackgroundTaskCompleted trigger, there is a CurrPage.Update() which is causing an error to show in Notification activities, We have code on "OnAfterGetRecord" where we are setting range on record and doing findfirst() which causes the page OnPageBackgroundTaskCompleted triggered and notification error pops up.
Internal work item: [AB#550446](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550446)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25061.
