### ISSUE TITLE
report 402 "Purchase Document - Test" ShowDim variable is not a protected var

### ISSUE THREAD

**Issue by RobynGee** [microsoft/ALAppExtensions#27291]
### Describe the request

report 402 "Purchase Document - Test" ShowDim variable is not a protected var the way it is in report 2 "General Journal - Test"

### Additional context

would like to extend the report and have access to the user's choice of Show Dimensions
Internal work item: [AB#550428](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550428)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24772.
