### ISSUE TITLE
[Event Request] codeunit 393 "Reminder-Issue" - OnAfterGlobalReminderHeaderChecks

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27298]
### Describe the request

Hello, can you please add a new Event OnAfterGlobalReminderHeaderChecks in codeunit 393 "Reminder-Issue"?

```
    trigger OnRun()
    var
.
.
.
        GlobalReminderHeader.TestField("Posting Date");
        GlobalReminderHeader.TestField("Document Date");
        GlobalReminderHeader.TestField("Due Date");
        GlobalReminderHeader.TestField("Customer Posting Group");
        OnAfterGlobalReminderHeaderChecks(GlobalReminderHeader);

        if ErrorMessageHandler.HasErrors() then
            if ErrorMessageHandler.ShowErrors() then
                Error('');
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGlobalReminderHeaderChecks(var ReminderHeader: Record "Reminder Header")
    begin
    end;
```

### Additional context

We have additional checks after the standard testfields.
Internal work item: [AB#550460](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550460)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25389.
