### ISSUE TITLE
[Event Request] page 9106 "Customer Ledger Entry FactBox" - OnGetNoOfAppliedEntries

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27294]
### Describe the request

Hello, can you please add a new Event OnGetNoOfAppliedEntries in page 9106 "Customer Ledger Entry FactBox"?

```
    local procedure GetNoOfAppliedEntries(CustLedgerEntry: Record "Cust. Ledger Entry"): Integer
    var
        IsHandled: Boolean;
        ReturnedValue: Integer;
    begin
        OnGetNoOfAppliedEntries(CustLedgerEntry, ReturnedValue, IsHandled);
        if IsHandled then
            exit(ReturnedValue);
        GetAppliedEntries(CustLedgerEntry);
        exit(CustLedgerEntry.Count);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnGetNoOfAppliedEntries(CustLedgerEntry: Record "Cust. Ledger Entry"; var ReturnedValue: Integer; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

We need a more complex logic to find applied entries as the posting structure within the german localisation has changed in the past.
The logic we use has to find all entries according to the current posting logic as well as the legacy posting logic.
Internal work item: [AB#550445](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550445)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26357.
