### ISSUE TITLE
[Event Request] Codeunit 28000 "Post Code Check"

### ISSUE THREAD

**Issue by RobynGee** [microsoft/ALAppExtensions#27290]
### Describe the request

In the procedure VerifyCity can a new subscription be created at the end:
OnAfterValidateCity(Rec, CityTxt, PostCode, CountyTxt, CountryCode, UseDialog);  
Similar to the Post Code table ValidateCity procedure

In the procedure VerifyPostCode can a subscription be created at the end:
OnAfterVerifyPostCode(Rec, CityTxt, PostCode, CountyTxt, CountryCode, UseDialog);
Similar to the Post Code table ValidatePostCode procedure

### Additional context

These two procedures are run by the OnBeforeValidatePostCode and BeforeValidateCity and return handled, so they are run as a substitute to the W1 Post Code table validation, so should provide the same options for subscription in post code handling.

OnBeforeValidatePostCode(Rec, PostCode, CurrFieldNo, IsHandled);
                if not IsHandled then
                    PostCode.ValidatePostCode(City, "Post Code", County, "Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);

                OnBeforeValidateCity(Rec, PostCode, CurrFieldNo, IsHandled);
                if not IsHandled then
                    PostCode.ValidateCity(City, "Post Code", County, "Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);
Internal work item: [AB#550427](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550427)

**Comment by JakovljevicDusan** [comment]
Hi @RobynGee ,
Please specify exact variables that are needed for these two events.

**Comment by RobynGee** [comment]
local procedure OnAfterValidateCity(var PostCodeRec: Record "Post Code"; var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; UseDialog: Boolean)

local procedure OnAfterValidatePostCode(var PostCodeRec: Record "Post Code"; var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; UseDialog: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27687.
