### ISSUE TITLE
[Event Request] codeunit 393 "Reminder-Issue" - OnAfterSetPostingInformation

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27305]
### Describe the request

Hello, can you please add a new Event OnAfterSetPostingInformation in codeunit 393 "Reminder-Issue"?

```
    local procedure InitGenJnlLine(AccType: Enum "Gen. Journal Account Type"; AccNo: Code[20]; SystemCreatedEntry: Boolean)
    begin
.
.
.
        TempGenJnlLine.Validate("Account No.");
        if TempGenJnlLine."Account Type" = TempGenJnlLine."Account Type"::"G/L Account" then begin
            TempGenJnlLine."Gen. Posting Type" := TempGenJnlLine."Gen. Posting Type"::Sale;
            TempGenJnlLine."Gen. Bus. Posting Group" := GlobalReminderHeader."Gen. Bus. Posting Group";
            TempGenJnlLine."VAT Bus. Posting Group" := GlobalReminderHeader."VAT Bus. Posting Group";
            OnAfterSetPostingInformation(TempGenJnlLine, AccNo)
        end;
        TempGenJnlLine.Validate("Currency Code", GlobalReminderHeader."Currency Code");
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetPostingInformation(var TempGenJnlLine: Record "Gen. Journal Line"; AccNo: Code[20])
    begin
    end;
```

### Additional context

We want to fill some additional fields in TempGenJnlLine needed for the german localisation.
Internal work item: [AB#550259](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550259)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25389.
