### ISSUE TITLE
[Event Request] Codeunit 99000838 "Prod. Order Comp.-Reserve"

### ISSUE THREAD

**Issue by PawelBartos-Integro** [microsoft/ALAppExtensions#27304]
### Describe the request

Could you please add is handled to the existing event OnBeforeTransferPOCompToItemJnlLineCheckILE.

### Additional context

The reason is that in old BC16 we got code below:
![image](https://github.com/user-attachments/assets/4a46aabc-7161-418d-b388-775e57c59576)
Without event modification we cannot upgrade it to the BC24.
Alternatively please move the event OnBeforeTransferPOCompToItemJnlLineCheckILE to the begining of procedure.
![image](https://github.com/user-attachments/assets/72d54538-a98b-4bfb-8103-2a11afc475a3)

Internal work item: [AB#550467](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550467)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25061.
