### ISSUE TITLE
[Event Request] Core Localization Pack for Czech - codeunit 11755 "Registration Log Mgt. CZL" - AssistEditRegNo

### ISSUE THREAD

**Issue by StanislovasMiknius** [microsoft/ALAppExtensions#27319]
### Describe the request

Please add the following Event OnBeforeAssistEditRegNo in codeunit 11755 "Registration Log Mgt. CZL":

```
    local procedure AssistEditRegNo(AccountType: Enum "Reg. Log Account Type CZL"; AccountNo: Code[20])
    var
        AssistedRegistrationLogCZL: Record "Registration Log CZL";
        IsHandled: Boolean;
    begin
        //>> New event
        OnBeforeAssistEditRegNo(AccountType, AccountNo, IsHandled);
        if IsHandled then
            exit;
        //>> End

        CheckAndLogUnloggedRegistrationNumbers(AssistedRegistrationLogCZL, AccountType, AccountNo);
        Commit();
        Page.RunModal(Page::"Registration Log CZL", AssistedRegistrationLogCZL);
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssistEditRegNo(AccountType: Enum "Reg. Log Account Type CZL"; AccountNo: Code[20]; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

This event is needed because currently Page::"Registration Log CZL" is always opened from drilldown of Customer Card -> "Registration No." field and there is a need to use different page. This event will also be useful for Contact Card and Vendor Card pages.
Internal work item: [AB#550250](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550250)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26416.
