### ISSUE TITLE
[Event Request] table 55 "Invoice Posting Buffer" - OnAfterSetAccount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27311]
### Describe the request

Hello, can you please add a new Event OnAfterSetAccount in table 55 "Invoice Posting Buffer"?

```
    procedure SetAccount(AccountNo: Code[20]; var TotalVAT: Decimal; var TotalVATACY: Decimal; var TotalAmount: Decimal; var TotalAmountACY: Decimal)
    begin
        TotalVAT := TotalVAT - "VAT Amount";
        TotalVATACY := TotalVATACY - "VAT Amount (ACY)";
        TotalAmount := TotalAmount - Amount;
        TotalAmountACY := TotalAmountACY - "Amount (ACY)";
        "G/L Account" := AccountNo;
        OnAfterSetAccount(Rec, "G/L Account");
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetAccount(var InvoicePostingBuffer: Record "Invoice Posting Buffer"; AccountNo: Code[20])
    begin
    end;
```

### Additional context

We assign an additional field in the InvoicePostingBuffer that is linked to the G/L Account.
Internal work item: [AB#550255](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550255)

**Comment by grobyns** [comment]
@RZ440 Why can't you use one of the 4 events available in the Update function on Table 55 "Invoice Post Buffer"? Afaik the update method should always be called so you should have the required info there but Maybe there is a scenario where it is not sufficient so I'd like to understand that better.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26737.
