### ISSUE TITLE
[Bug]: Event OnInitSourceDocumentHeaderOnBeforeTransHeaderModify missing in codeunit 5748 "Transfer Whse. Post Shipment"

### ISSUE THREAD

**Issue by Enrico-Marini-EOS** [microsoft/ALAppExtensions#27320]
### Describe the issue

In this codeunit 5748 "Transfer Whse. Post Shipment" the events OnInitSourceDocumentHeaderOnBeforeTransferHeaderUpdatePostingDate and OnInitSourceDocumentHeaderOnBeforeTransHeaderModify are commented, but they are not defined and it is different from the codeunits 5746 "Sales Whse. Post Shipment" and 5747 "Purch. Whse. Post Shipment"

### Expected behavior

The possibility to subscribe to those events OnInitSourceDocumentHeaderOnBeforeTransferHeaderUpdatePostingDate and OnInitSourceDocumentHeaderOnBeforeTransHeaderModify for insert custom code

### Steps to reproduce

Compare sales and purchase codeunits with the transfer codeunit

### I will provide a fix for a bug

- [x] I will provide a fix for a bug
Internal work item: [AB#550240](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550240)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24747.
