### ISSUE TITLE
Event OnAfterNavigateShowRecords obsoleted in BC25 but not replaced

### ISSUE THREAD

**Issue by DennyHW** [microsoft/ALAppExtensions#27322]
### Describe the request

The event **OnAfterNavigateShowRecords**() in page **page 344 Navigate**
has been deprecated in BC 25.0 without a replacement.

Please revert the obsolete tag or suggest the new event.

![immagine](https://github.com/user-attachments/assets/4e78f1c5-7cc2-4608-9004-427605d8c403)

![immagine](https://github.com/user-attachments/assets/d543eb5f-08da-4edd-b327-deb054b1c7ce)

### Additional context

Refactor not completed
Internal work item: [AB#550252](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550252)

**Comment by RadoArvay** [comment]
But I can see `OnAfterShowRecords` event in the current NextMinor 25.0.23364.24538.
There is also an obsoleting reason '_Replaced by event OnAfterShowRecords()_'.
