### ISSUE TITLE
[Event Request] Page 9800 Users - function SetUserName

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#27321]
Please add event OnBeforeSetUserName to Page 9800 Users function SetUserName:
```
    local procedure SetUserName()
    var
        IsHandled: Boolean;
    begin
        //>> New event
        OnBeforeSetUserName(Rec, XRec, WindowsUserName, IsHandled);
        if not IsHandled then
        //<< End
            "User Name" := WindowsUserName;

        ValidateUserName();
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetUserName(var User: Record User; var xUser: Record User; WindowsUserName: Text[208]; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

I see that similar requests already rejected due to security concern:
https://github.com/microsoft/ALAppExtensions/issues/24665
https://github.com/microsoft/ALAppExtensions/issues/25958

But I think there is no problem with security - "User Name" can be changed after user is created. It is allowed and works ok.
Problem is with new user creation - our customer wants to remove domain name. When they do that just after user creation, rename is triggered, it checks a lot of tables and causes huge number of locks. So we want to have an option to change the "User Name" just before it's creation.
Internal work item: [AB#550251](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550251)

**Comment by onbuyuka** [comment]
This is just not the right way to go. Security concerns aside, SetUserName is a local procedure in the list page called on validation for Windows User Name. Let's assume we added this event, how about the same logic in the User Card? Then another event, then another...

Also not to mention Windows User Name field is only visible on premise, which you most certainly don't need an event for...

If you would like to change the username then you should do it on the table level, by subscribing to OnInsert/OnModify triggers.

**Comment by nikolakukrika** [comment]
Why cannot you use OnBeforeInsert trigger and a subscriber to change the name?

**Comment by ViktorasDanielius** [comment]
It's OK, we will try to solve the issue in different way. You can close this request.
