### ISSUE TITLE
[Protected var] Report 11308 "VAT Annual Listing"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#27327]
### Describe the request

Can you please make all variables from the requestpage of report 11308 "VAT Annual Listing" available as protected vars? This allows us to act upon the options when extending the report.

Please move below globals to the **protected** region:

- WrongVATRegNoList
- VATAnnualList
- intYear
- Minimum
- IncludeCountry
- Country

### Additional context

x
Internal work item: [AB#550475](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550475)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25470.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25584.
