### ISSUE TITLE
report 202 "Sales Document - Test" ShowDim

### ISSUE THREAD

**Issue by RobynGee** [microsoft/ALAppExtensions#27324]
### Describe the request

report 202 "Sales Document - Test" does not have ShowDim as a protected var the way it is in report 2 General Journal - Test.  Can this be made available for access by report extension.

### Additional context

Would like to have access to the users choice on Show Dimensions in report extension
Internal work item: [AB#550418](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550418)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24772.
