### ISSUE TITLE
[Protected vars] Fixed Asset - Book Value 01

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#27330]
### Describe the request

Please make some variables as **protected** vars in report 5605 "Fixed Asset - Book Value 01"

```
StartingDate: Date;
EndingDate: Date;
```

### Additional context

x
Internal work item: [AB#550936](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550936)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25286.
