### ISSUE TITLE
[Event Request] Table 5077 Segment Line - OnBeforeHandleTrigger

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27331]
### Describe the request

We want to run our own business logic in the HandleTrigger() procedure. Therefore we request to add the following event:

```
internal procedure HandleTrigger()
var
	TempBlob: Codeunit "Temp Blob";
	FileMgt: Codeunit "File Management";
	DocumentSharing: Codeunit "Document Sharing";
	Telemetry: Codeunit Telemetry;
	ImportedFileName: Text;
	//NEW
	IsHandled: Boolean;
	//MEW
begin
	//NEW
	IsHandled := false;
	OnBeforeHandleTrigger(Rec, TempAttachment, Merged, IsHandled);
	if IsHandled then
		exit;
	//NEW
	GlobalInteractionTemplate.Get("Interaction Template Code");
	case GlobalInteractionTemplate."Wizard Action" of
		GlobalInteractionTemplate."Wizard Action"::" ":
			if "Attachment No." <> 0 then begin
				LoadTempAttachment(false);
				Subject := Description;
	// ...
	
[IntegrationEvent(false, false)]
local procedure OnBeforeHandleTrigger(var SegmentLine: Record "Segment Line"; var TempAttachment: Record Attachment temporary; var Merged: Boolean; var IsHandled: Boolean)
begin
end;
```

### Additional context

Allows you to run your own business logic or change a single case block in the HandleTrigger() procedure. 
We want to change the business logic in the WizardAction::Import case block.
Internal work item: [AB#550937](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550937)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25061.
