### ISSUE TITLE
[Event Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnFinishPostingOnBeforeResetFirstEntryNo

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27344]
### Describe the request

Hello, can you please add "GenJournalLine" and "IsTransactionConsistent" to the event OnFinishPostingOnBeforeResetFirstEntryNo in codeunit 12 "Gen. Jnl.-Post Line"?

```
    procedure FinishPosting(GenJournalLine: Record "Gen. Journal Line") IsTransactionConsistent: Boolean
    var
.
.
.
        GlobalGLEntry.Consistent(IsTransactionConsistent);

        if CostAccountingSetup.Get() then
            if CostAccountingSetup."Auto Transfer from G/L" then
                TransferGlEntriesToCA.GetGLEntries();

        OnFinishPostingOnBeforeResetFirstEntryNo(GlobalGLEntry, NextEntryNo, FirstEntryNo, GenJournalLine, IsTransactionConsistent);
        FirstEntryNo := 0;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnFinishPostingOnBeforeResetFirstEntryNo(var GLEntry: Record "G/L Entry"; NextEntryNo: Integer; FirstEntryNo: Integer; GenJournalLine: Record "Gen. Journal Line"; IsTransactionConsistent: Boolean)
    begin
    end;
```

### Additional context

We would like to add further information to the posted entries and write additional data but only if some conditions in the GenJournalLine are fulfilled and the transaction is complete.
Internal work item: [AB#550927](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550927)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26401.
