### ISSUE TITLE
[Function Visibility]Function CalcDiscount() in table Service Line 

### ISSUE THREAD

**Issue by jhoek** [microsoft/ALAppExtensions#27348]
### Describe the request

Please consider changing the visibility of CalcDiscount() (currently local) to either _protected_ or perhaps even _public_. 

### Additional context

We want to use the OnBeforeUpdateUnitPriceByField event from UpdateUnitPriceByField() to bypass the existing calculation (using the Handled pattern). Of course, our logic also needs to take discounts into account, which is why we would like to be able to call CalcDiscount() from our event subscriber. 
Internal work item: [AB#550918](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550918)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25201.
