### ISSUE TITLE
[Event Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCheckGLAccDimError

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27345]
### Describe the request

Hello, can you please add a new event OnAfterCheckGLAccDimError in codeunit 12 "Gen. Jnl.-Post Line"?

```
    procedure CheckGLAccDimError(GenJnlLine: Record "Gen. Journal Line"; GLAccNo: Code[20])
    var
.
.
.
        if ((GenJnlLine.Amount = 0) and (GenJnlLine."Amount (LCY)" = 0)) and (not IsGainLossAccount(GenJnlLine."Source Currency Code", GLAccNo)) then
            exit;

        TableID[1] := DATABASE::"G/L Account";
        AccNo[1] := GLAccNo;
        if DimMgt.CheckDimValuePosting(TableID, AccNo, GenJnlLine."Dimension Set ID") then begin
            OnAfterCheckGLAccDimError();
            exit;
        end;

        if GenJnlLine."Line No." <> 0 then
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckGLAccDimError()
    begin
    end;
```

### Additional context

We would like to set/reset a flag if the dim value must be checked/has been checked because, in special cases, we want to allow posting a blocked dimension if the posting is an addition to an existing posting.
Internal work item: [AB#550923](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550923)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26401.
