### ISSUE TITLE
[Event Request] codeunit 926 "Assembly Line-Reserve" - TransferAsmLineToItemJnlLineOnBeforeTransferReservationEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#27340]
### Describe the request

    procedure TransferAsmLineToItemJnlLine(var AssemblyLine: Record "Assembly Line"; var ItemJournalLine: Record "Item Journal Line"; TransferQty: Decimal; CheckApplFromItemEntry: Boolean): Decimal
    var
        OldReservationEntry: Record "Reservation Entry";
        IsHandled: Boolean;
    begin
        ....
        if ReservationEngineMgt.InitRecordSet(OldReservationEntry) then begin
            repeat
                OldReservationEntry.TestField("Item No.", AssemblyLine."No.");
                OldReservationEntry.TestField("Variant Code", AssemblyLine."Variant Code");
                OldReservationEntry.TestField("Location Code", AssemblyLine."Location Code");

                if CheckApplFromItemEntry then begin
                    OldReservationEntry.TestField("Appl.-from Item Entry");
                    CreateReservEntry.SetApplyFromEntryNo(OldReservationEntry."Appl.-from Item Entry");
                end;

                IsHandled := false;
                TransferAsmLineToItemJnlLineOnBeforeTransferReservationEntry(OldReservationEntry, AssemblyLine, ItemJournalLine, IsHandled);
                if not IsHandled then
                    TransferQty := CreateReservEntry.TransferReservEntry(
                        Database::"Item Journal Line",
                        ItemJournalLine."Entry Type".AsInteger(), ItemJournalLine."Journal Template Name",
                        ItemJournalLine."Journal Batch Name", 0, ItemJournalLine."Line No.",
                        ItemJournalLine."Qty. per Unit of Measure", OldReservationEntry, TransferQty);

            until (ReservationEngineMgt.NEXTRecord(OldReservationEntry) = 0) or (TransferQty = 0);
            CheckApplFromItemEntry := false;
        end;
        exit(TransferQty);
    end;

    [IntegrationEvent(false, false)]
    local procedure TransferAsmLineToItemJnlLineOnBeforeTransferReservationEntry(var ReservationEntry: Record "Reservation Entry"; var AssemblyLine: Record "Assembly Line"; var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

### Additional context

The use of T337 Reservation Entry using warehouse shipments and picks with item tracking lines is not fun and does not work with many of our customers. We have developed our own WMS decades ago and introduced
ReservationEntry."Whse Qty to Handle Base A109" to allow one assembly/sales/purchase/transfer/service line to be split into multiple warehouse lines and therefore need an extra field to assign pick quantities etc.
Internal work item: [AB#550928](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550928)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25061.
