### ISSUE TITLE
[Bug]: Prod. Order Components (99000818, List) Slow in Italian Localization

### ISSUE THREAD

**Issue by andreaantoniazzi85** [microsoft/ALAppExtensions#27349]
### Describe the issue

The page "Prod. Order Components" (99000818) in the IT version is very slow on opening, when there is a significant number of records in the "Item Ledger Entry Table".
The problem is related to the field ???Qty. transf. to Subcontractor???
Adding this key we see a significant increase in performance:

tableextension 50000 AltTBILEKey extends "Item Ledger Entry"
{
    keys
    {
        key(TrasfComp; "Entry Type", "Location Code", "Prod. Order No.", "Prod. Order Line No.", "Prod. Order Comp. Line No.","Subcontr. Purch. Order No.")
        { }
    }
}

### Expected behavior

Faster page loading and line browsing

### Steps to reproduce

It is not possibile to replicate in a Cronus database because there a few lines in the Item Ledger Entry table

### I will provide a fix for a bug

- [X] I will provide a fix for a bug
Internal work item: [AB#550940](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550940)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26570.
