### ISSUE TITLE
[Event Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeFinishPosting

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27343]
### Describe the request

Hello, can you please add "TempGLEntryVATEntryLink", "BalanceCheckAmount", "BalanceCheckAmount2", "BalanceCheckAddCurrAmount", "BalanceCheckAddCurrAmount2", and "IsHandled" to the event OnBeforeFinishPosting in codeunit 12 "Gen. Jnl.-Post Line"?

```
    procedure FinishPosting(GenJournalLine: Record "Gen. Journal Line") IsTransactionConsistent: Boolean
    var
        CostAccountingSetup: Record "Cost Accounting Setup";
        TransferGlEntriesToCA: Codeunit "Transfer GL Entries to CA";
        IsTransactionConsistentExternal: Boolean;
        LastSourceCurrencyVATAmount: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeFinishPosting(GenJournalLine, TempGLEntryBuf, TempGLEntryVATEntryLink, BalanceCheckAmount, BalanceCheckAmount2, BalanceCheckAddCurrAmount, BalanceCheckAddCurrAmount2, IsHandled);
        if IsHandled then
            exit;

        IsTransactionConsistent :=
          (BalanceCheckAmount = 0) and (BalanceCheckAmount2 = 0) and
          (BalanceCheckAddCurrAmount = 0) and (BalanceCheckAddCurrAmount2 = 0);
        IsTransactionConsistentExternal := IsTransactionConsistent;
        GlobalGLEntry.Consistent(IsTransactionConsistent);
```

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeFinishPosting(var GenJournalLine: Record "Gen. Journal Line"; var TempGLEntryBuf: Record "G/L Entry" temporary; var TempGLEntryVATEntryLink: Record "G/L Entry - VAT Entry Link" temporary; BalanceCheckAmount: Decimal; BalanceCheckAmount2: Decimal; BalanceCheckAddCurrAmount: Decimal; BalanceCheckAddCurrAmount2: Decimal; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

We would like to post additional entries if the transaction is consistent so we need to know the "Balance" fields or, alternatively, "IsTransactionConsistent". Furthermore, we would like to read amounts from the VAT Entries connected to the G/L Entries. And in some very special cases we would like to skip the procedure.
Internal work item: [AB#550921](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/550921)

**Comment by dcenic** [comment]
We will not make the consistency check completely optional and customizable like this. It would open up for disasters.
Events are raised before and after FinishPosting is called - you can find the related VAT Entries by subscribing to those events.
