### ISSUE TITLE
 [Event Request] CU10861 "Payment-Apply" - local procedure Apply()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#27354]
### Describe the request

Add a event in CU10861 "Payment-Apply" - local procedure Apply()

### Additional context

local procedure Apply(var PaymentLine: Record "Payment Line")
.....
 case AccType of
            AccType::Customer:
                begin
                end;
            AccType::Vendor:
                begin
                end;
            else
----------------------- ADD EVENT ----------------------
        IsHandled := false;
        OnElseAccTypeOnApply(var PaymentLine, var GenJnlLine, IsHandled)
        if not IsHandled then
                Error(
                    Text005,
                    GenJnlLine.FieldCaption("Account Type"), GenJnlLine.FieldCaption("Bal. Account Type"));
Internal work item: [AB#551202](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551202)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25286.
