### ISSUE TITLE
[Global Procedure request] codeunit 445 "Purch.-Post Prepmt. (Yes/No)" - GetReport

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#27357]
### Describe the request

Can you make procedure GetReport global like it has already been done on the sales side codeunit 443 "Sales-Post Prepayment (Yes/No)"?

[Old code]
local procedure GetReport(var PurchHeader: Record "Purchase Header"; DocumentType: Option Invoice,"Credit Memo")

[New code]
procedure GetReport(var PurchHeader: Record "Purchase Header"; DocumentType: Option Invoice,"Credit Memo")

### Additional context

We are implementing a lifecycle addon (working together with approval, workflow and prepayment) and want to create an action:
local procedure PostAndPrintPrepaymentInvoice(var PurchaseHeader: Record "Purchase Header") 
but we are unable to use GetReport
Internal work item: [AB#551204](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551204)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.
