### ISSUE TITLE
Get AccountId from table Sent Email

### ISSUE THREAD

**Issue by TNaundorf** [microsoft/ALAppExtensions#27352]
### Describe the request

Please add the following function to the Sent Email table;

```
    /// <summary>
    /// Get the account id of the sent email.
    /// </summary>
    /// <returns>Account id.</returns>
    procedure GetAccountId(): Guid
    begin
        exit(Rec."Account Id");
    end;
```

### Additional context

To have the possiblity to archive the sent emails in a custom table we need the possibility to get the account id of the sent email so that we are able to resend the email from our custom archive. 
Internal work item: [AB#551203](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551203)

**Comment by Groenbech96** [comment]
Please open PR with your suggested contribution on BCApps https://github.com/microsoft/BCApps
