### ISSUE TITLE
[Change Request] Add field "Job Planning Line No." on tables "Purch. Inv. Line", "Purch. Rcpt. Line", "Purch. Cr. Memo Line", "Return Shipment Line"

### ISSUE THREAD

**Issue by mtaanquist** [microsoft/ALAppExtensions#27358]
### Describe the request

Copy the "Job Planning Line No." field from table 39 "Purchase Line" to the tables:
table 121 "Purch. Rcpt. Line"
table 123 "Purch. Inv. Line"
table 125 "Purch. Cr. Memo Line"
table 6651 "Return Shipment Line"

The same could be done to the posted sales lines, for tables:
table 111 "Sales Shipment Line"
table 113 "Sales Invoice Line"
table 115 "Sales Cr.Memo Line"
table 6661 "Return Receipt Line"

### Additional context

We have a lot of customers that use Job Planning Lines to manage purchasing items and services. In that flow, we usually end up with requests to add flowfields to purchase lines and the posted versions.

However, while we can easily make a flowfield to calculate the quantity on purchase lines, we are not able to do a flowfield for e.g. "Received Qty." with a sum of "Purch. Rcpt. Line" because the "Job Planning Line No." is missing, when it is there on the Purchase Line.

Adding the table fields shouldn't need other code, as it should copy it over via TransferFields. When we have to implement this ourselves, we will always require code to set the value during posting, which we would then be able to avoid.
Internal work item: [AB#551256](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551256)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26037.
