### ISSUE TITLE
[Parameter Add] Report 94 "Close Income Statement", add parameter "RealMode at event OnBeforeValidateEndDate

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#27360]
### Describe the request

In reference to [25963](https://github.com/microsoft/ALAppExtensions/issues/25963), this has solved only part of the problem.
We are requesting to add the 'RealMode' parameter at OnBeforeValidateEndDate( like below

OnBeforeValidateEndDate(EndDateReq, FiscalYearStartDate, FiscYearClosingDate, OK, Result, RealMode, IsHandled);

### Additional context

This is because we would like to handle the below part of code 
        if not OK then begin
            if not RealMode then
                exit;
            Error(Text015);
        end;
Internal work item: [AB#551482](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551482)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25286.
