### ISSUE TITLE
[Enum Request] TAB 5065 - Document Type

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2736]
Please provide enum support on field Document Type in table 5065 Interaction Log Entry.

Please also provide OnAfterShowDocument publisher with access to Rec in function ShowDocument.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
