### ISSUE TITLE
[Change Request] codeunit 905 "Assembly Line Management" - Event "OnCopyAssemblyDataOnAfterToAssemblyLineInsert" - Add parameter "FromAssemblyHeader" : Record "Assembly Header"

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27367]
### Describe the request

Hello, can you please add to the procedure "OnCopyAssemblyDataOnAfterToAssemblyLineInsert", the input parameter FromAssemblyHeader: Record "Assembly Header", in codeunit 905 "Assembly Line Management" ?

FROM : 

[IntegrationEvent(false, false)]
local procedure OnCopyAssemblyDataOnAfterToAssemblyLineInsert(var AssemblyLine: Record "Assembly Line"; var ToAssemblyLine: Record "Assembly Line")
begin
end;

TO : 

[IntegrationEvent(false, false)]
local procedure OnCopyAssemblyDataOnAfterToAssemblyLineInsert(var AssemblyLine: Record "Assembly Line"; var ToAssemblyLine: Record "Assembly Line"; FromAssemblyHeader: Record "Assembly Header")
begin
end;

### Additional context

We need to check some values on "Assembly Header" record after "Assembly Line" was inserted.
Internal work item: [AB#554321](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554321)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
