### ISSUE TITLE
[Change Request] Codeunit 415 "Release Purchase Document" - Function "Code" - Add function

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27365]
### Describe the request

Hello, please can you add a new event in Codeunit 415 "Release Purchase Document" / Function "Code" called "OnCodeOnAfterModifyHeader" ?

New function "OnCodeOnAfterModifyHeader" will be place juste after the following action (line 109): 
=> PurchaseHeader.Modify(true);
and before the "IF" statement (line 111) : 
=> if NotOnlyDropShipment then

Function will be : 

[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterModifyHeader(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; PreviewMode: Boolean; var LinesWereModified: Boolean; NotOnlyDropShipment : Boolean)
begin
end;

### Additional context

We need to check certain values in the "Purchase Header" record and change the value for the variable "NotOnlyDropShipment" before testing it.
Internal work item: [AB#554329](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554329)

**Comment by JakovljevicDusan** [comment]
Parameter added to OnCodeOnBeforeModifyHeader
