### ISSUE TITLE
table 55 "Invoice Posting Buffer" - ClearVATFields procedure event request

### ISSUE THREAD

**Issue by SYL-denisg** [microsoft/ALAppExtensions#27369]
### Describe the request

Hello, we have nte need to be able to override the clearing of the VAT fields in the ClearVATFields proceudre, as well as to do some addtional processing, clearing our related fields.

Thank you!

Denis

```
.....

table 55 "Invoice Posting Buffer"

.....

    procedure ClearVATFields()
    // New event var begin
    var IsHandled: Boolean;
    // New event var end
    begin
        // New event call begin
        OnBeforeClearVATFields(Rec, IsHandled);
        if IsHandled then
            exit;

        // New event call end
        "VAT Amount" := 0;
        "VAT Base Amount" := 0;
        "VAT Amount (ACY)" := 0;
        "VAT Base Amount (ACY)" := 0;
        NonDeductibleVAT.ClearNonDeductibleVAT(Rec);
        "VAT Difference" := 0;
        "VAT %" := 0;
    end;

.....

    // New event definition begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeClearVATFields(var InvoicePostingBuffer: Record "Invoice Posting Buffer"; var IsHandled: Boolean)
    begin
    end;
    // New event definition end

}


```

### Additional context

Our invoice posting process requires us to do some additional work on our fields and related records, and this point in the code is where we had the process working using the old Invoice Post. Buffer table.
Internal work item: [AB#554331](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554331)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25885.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25853.
