### ISSUE TITLE
[Change Request] Codeunit 7237 MasterDataMgt.Subscribers procedure RenameDestination - manage tables with 6 fields

### ISSUE THREAD

**Issue by vanahearth** [microsoft/ALAppExtensions#27364]
### Describe the request

We are using the Master Data Management functionality and have synchronized the Item Reference table. The synchronization fails because the primary key of the table has 6 fields, and the RenameDestination function of codeunit 7237 MasterDataMgt.Subscribers handles the renaming of the primary key up to 5 fields.  

![image](https://github.com/user-attachments/assets/f22295ce-e2ba-40a6-9e48-947c8cd0ec94)

### Additional context

Since this is a table from the Base Application, is it possible to manage tables with 6 fields in the primary key or have an event available to bypass the error?  
Internal work item: [AB#554323](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554323)

**Comment by pri-kise** [comment]
This should definitely be fixed in the first party app.
I think we shouldn't stop at 6 primary keys.

**Comment by pri-kise** [comment]
Normally @JesperSchulz approves the issues here, but he is off work for about a week.

@vanahearth would you fix this via PR?

**Comment by dcenic** [comment]
For 25.x, we will add an event so that partners can subscribe and do the RecRef rename if primary key has more than 5 fields. There is no dynamic way of doing the RecRef.Rename with an arbitrary number of PK fields - it needs to be coded.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25879.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25876.
