### ISSUE TITLE
[Event Request] Application "Tests-Marketing", Codeunit 136210 "Contact Employee"

### ISSUE THREAD

**Issue by JoergPernberg** [microsoft/ALAppExtensions#27361]
### Describe the request

Can you please raise the OnTestInitialize-Event at the beginning of the procedure Initialize()?
![image](https://github.com/user-attachments/assets/92b71cc8-1069-49ad-9f5e-714f60eead7b)

### Additional context

The event is needed to perform some setups before running the tests in the codeunit
Internal work item: [AB#551382](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/551382)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27498.
