### ISSUE TITLE
[Event (Change) Request] Service Contract Header - OnBeforeCreateDims(...)

### ISSUE THREAD

**Issue by Aize-S** [microsoft/ALAppExtensions#27378]
### Describe the request

It would make sense to add two parameters to the event publisher OnBeforeCreateDims in table 5965 "Service Contract Header":
- CurrFieldNo
- DefaultDimSource (alternatively, change the procedure InitDefaultDimensionSources from local to global (or protected))

### Additional context

I want to handle dimension creation myself, but I want to know from which field it is called and which DefaultDimensions are in the source when the procedure CreateDim is called.
Internal work item: [AB#554334](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554334)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
