### ISSUE TITLE
[Event-Request] Table 111 "Sales Shipment Line" - OnBeforeGetSalesInvLine()

### ISSUE THREAD

**Issue by janellyn** [microsoft/ALAppExtensions#27379]
### Describe the request

Please add event OnBeforeGetSalesInvLine() in Table 111 "Sales Shipment Line" in procedure GetSalesInvLines before SalesInvLine.Get() on 916 row:

```
OnBeforeGetSalesInvLine(SalesInvLine);
if SalesInvLine.Get(ValueEntry."Document No.", ValueEntry."Document Line No.") then begin
TempSalesInvLine.Init();
TempSalesInvLine := SalesInvLine;
if TempSalesInvLine.Insert() then;
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetSalesInvLine(var SalesInvLine: Record "Sales Invoice Line")
begin
end;
```

### Additional context

We need this event to AutoCalcFields in Sales Inv. Line before Get in the loop
Internal work item: [AB#554336](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554336)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
