### ISSUE TITLE
[Event Request] Codeunit 5912 "ServLedgEntries-Post" - OnBeforeFinishServiceRegister

### ISSUE THREAD

**Issue by BITNilsRoolf** [microsoft/ALAppExtensions#27376]
### Describe the request

Please add new Event OnBeforeFinishServiceRegister in procedure FinishServiceRegister

```al
    procedure FinishServiceRegister(var PassedServEntryNo: Integer; var PassedWarrantyEntryNo: Integer)
    begin
        OnBeforeFinishServiceRegister(ServiceRegister);        

        PassedServEntryNo := NextServLedgerEntryNo;
        PassedWarrantyEntryNo := NextWarrantyLedgerEntryNo;

        ServiceRegister."To Warranty Entry No." := NextWarrantyLedgerEntryNo - 1;
        ServiceRegister."To Entry No." := NextServLedgerEntryNo - 1;

        if ServiceRegister."To Warranty Entry No." < ServiceRegister."From Warranty Entry No." then begin
            ServiceRegister."To Warranty Entry No." := 0;
            ServiceRegister."From Warranty Entry No." := 0;
        end;

        if ServiceRegister."To Entry No." >= ServiceRegister."From Entry No." then
            ServiceRegister.Insert();
    end;
``` 

Event Definition:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeFinishServiceRegister(var ServiceRegister: Record "Service Register")
begin
end;
``` 

### Additional context

We are currently moving a customer from C/AL to AL and we are unable to provide the requirement for this procedure due to missing events.
Internal work item: [AB#554340](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554340)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
