### ISSUE TITLE
Event OnPostSourceDocumentOnBeforePrintTransferShipment Commented in "Transfer Whse. Post Shipment" CodeUnit

### ISSUE THREAD

**Issue by AimeneAmi** [microsoft/ALAppExtensions#27373]
### Describe the request

I'm using several events in "Whse.-Post Shipment" that will be obeslete for 25 so i started to replace one by one with the new events 

Codeunit::"Whse.-Post Shipment", 'OnPostSourceDocumentOnBeforePrintSalesShipment' ===>  Codeunit::"Sales Whse. Post Shipment", 'OnPostSourceDocumentOnBeforePrintSalesShipment'

Codeunit::"Whse.-Post Shipment", 'OnPostSourceDocumentOnBeforePrintSalesInvoice' ===> Codeunit::"Sales Whse. Post Shipment", 'OnPostSourceDocumentOnBeforePrintSalesInvoice'

Codeunit::"Whse.-Post Shipment", 'OnPostSourceDocumentOnBeforePrintPurchReturnShipment' ===> Codeunit::"Purch. Whse. Post Shipment", 'OnPostSourceDocumentOnBeforePrintPurchReturnShipment'

Codeunit::"Whse.-Post Shipment", 'OnPostSourceDocumentOnBeforePrintPurchCreditMemo' ===>  Codeunit::"Purch. Whse. Post Shipment", 'OnPostSourceDocumentOnBeforePrintPurchCreditMemo'

Codeunit::"Whse.-Post Shipment", 'OnPostSourceDocumentOnBeforePrintServiceShipment' ===> Codeunit::"Serv. Whse Post-Shipment", 'OnPostSourceDocumentOnBeforePrintServiceShipment'

Codeunit::"Whse.-Post Shipment", 'OnPostSourceDocumentOnBeforePrintServiceInvoice' ===> Codeunit::"Serv. Whse Post-Shipment", 'OnPostSourceDocumentOnBeforePrintServiceInvoice'

The issue that i found is that the event f Codeunit::"Whse.-Post Shipment", 'OnPostSourceDocumentOnBeforePrintTransferShipment' is commented in the new codeunit

![image](https://github.com/user-attachments/assets/167b2268-d6ae-4417-b209-ee7512959b9d)

### Additional context

I need this event to maintain my customer extension, i tried to find i new way to implement my code but the first useful event i found is in a table so this may impact other scenario 
So for us this the best way to keep our development working without regression 
 
Internal work item: [AB#554328](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554328)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25798.
