### ISSUE TITLE
[Event-Request] Codeunit 5857 "Copy Invt. Document Mgt." - OnBeforeFindFromInvtRcptLine

### ISSUE THREAD

**Issue by janellyn** [microsoft/ALAppExtensions#27371]
### Describe the request

Please add event OnBeforeFindFromInvtRcptLine() in Codeunit 5857 "Copy Invt. Document Mgt." in procedure CopyItemDoc before FromInvtRcptLine.Find('-') on 226 row:

```
OnBeforeFindFromInvtRcptLine(FromInvtRcptLine);
if FromInvtRcptLine.Find('-') then
repeat
FromInvtDocLine.TransferFields(FromInvtRcptLine);
CopyInvtDocLine(
ToInvtDocHeader, ToInvtDocLine, FromInvtDocHeader, FromInvtDocLine,
NextLineNo, LinesNotCopied, LinesSkipApplies);
until FromInvtRcptLine.Next() = 0;

[IntegrationEvent(false, false)]
local procedure OnBeforeFindFromInvtRcptLine(var FromInvtRcptLine: Record "Invt. Receipt Line")
begin
end;
```

### Additional context

We need this event to CalcFields in Invt. Receipt Line before loop
Internal work item: [AB#554333](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554333)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
