### ISSUE TITLE
[Event Request] Codeunit 5988 "Serv-Document Mgt." - OnAfterWarrantyLedgerEntryModify

### ISSUE THREAD

**Issue by BITNilsRoolf** [microsoft/ALAppExtensions#27387]
### Describe the request

Please add event OnAfterWarrantyLedgerEntryModify in procedure PrepareShiptmentLine

```al
local procedure PrepareShipmentLine(var PassedServLine: Record "Service Line"; passedWarrantyNo: Integer)
var
    WarrantyLedgerEntry: Record "Warranty Ledger Entry";
begin
...
    if Invoice and Ship then begin
          WarrantyLedgerEntry.Reset();
          WarrantyLedgerEntry.SetCurrentKey("Service Order No.", "Posting Date", "Document No.");
          WarrantyLedgerEntry.SetRange("Service Order No.", ServShptLine."Order No.");
          WarrantyLedgerEntry.SetRange("Document No.", ServShptLine."Document No.");
          WarrantyLedgerEntry.SetRange(Type, ServShptLine.Type);
          WarrantyLedgerEntry.SetRange("No.", ServShptLine."No.");
          WarrantyLedgerEntry.SetRange(Open, true);
          WarrantyLedgerEntry.ModifyAll(Open, false);
          OnAfterWarrantyLedgerEntryModify(ServShptLine);
    end;
end;
``` 

Event definition:

```al
[IntegrationEvent(false, false)]
local procedure OnAfterWarrantyLedgerEntryModify(ServShptLine: Record "Service Shipment Line")
begin
end;
``` 

### Additional context

We want to modify after the WarrantyLedgerEntry Table our own Ledger Entry Table
Internal work item: [AB#554347](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554347)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
