### ISSUE TITLE
[Event Request] table 4812 "Intrastat Report Line" - OnSetIntrastatReportHeaderFilters

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#27381]
### Describe the request

Please add a new event `OnSetIntrastatReportHeaderFilters` to `table 4812 "Intrastat Report Line"`, to method `SetIntrastatReportHeaderFilters`.

```al
  procedure SetIntrastatReportHeaderFilters(var IntrastatReportHeader2: Record "Intrastat Report Header")
  var
      IntrastatReportHeader3: Record "Intrastat Report Header";
  begin
      IntrastatReportHeader3.Get("Intrastat No.");
      IntrastatReportHeader2.SetRange("Corrective Entry", false);
      ...
      IntrastatReportHeader2.SetRange(Type, IntrastatReportHeader3.Type);
+     OnSetIntrastatReportHeaderFilters(IntrastatReportHeader2,IntrastatReportHeader3);
  end;

+ [IntegrationEvent(false, false)]
+ local procedure OnSetIntrastatReportHeaderFilters(var IntrastatReportHeader2: Record "Intrastat Report Header"; IntrastatReportHeader3: Record "Intrastat Report Header")
+ begin
+ end;
```

### Additional context

Just to add additional filters.
Internal work item: [AB#554335](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554335)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27480.
