### ISSUE TITLE
[Event Request] Codeunit 15000300 "Repeating Order to Order"

### ISSUE THREAD

**Issue by auzscr** [microsoft/ALAppExtensions#27389]
### Describe the request

Can I get an event OnBeforeRun here?

codeunit 15000300 "Repeating Order to Order"
{
    TableNo = "Sales Header";

    trigger OnRun()
    var
        GLSetup: Record "General Ledger Setup";
    begin
	// >>>>>>>>>>>>
	OnBeforeRun(Rec);
	// <<<<<<<<<<<<
        Rec.TestField("Document Type", Rec."Document Type"::"Blanket Order");

### Additional context

I need to do some checks on sales header before creating order.
Internal work item: [AB#554362](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554362)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
