### ISSUE TITLE
[Event Request] Codeunit 5920 "ServItemManagement" - OnBeforeServiceItemInsert

### ISSUE THREAD

**Issue by BITNilsRoolf** [microsoft/ALAppExtensions#27383]
### Describe the request

Please add new Event OnBeforeServiceItemInsert in procedure CreateServItemOnServItemLine

```al
procedure CreateServItemOnServItemLine(var ServItemLine: Record "Service Item Line")
var
    ConfirmManagement: Codeunit "Confirm Management";
    NoSeries: Codeunit "No. Series";
#if not CLEAN24
    NoSeriesMgt: Codeunit NoSeriesManagement;
#endif
    IsHandled: Boolean;
begin
...
OnBeforeServiceItemInsert(ServItem, ServItemLine);
ServItem.Insert();
ServItem.Validate(Description, ServItemLine.Description);
Clear(ServHeader);
ServHeader.Get(ServItemLine."Document Type", ServItemLine."Document No.");
...
end;
``` 

Event definition:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeServiceItemInsert(var ServiceItem: Record "Service Item"; ServiceItemLine: Record "Service Item Line")
begin
end;
``` 

### Additional context

In my business case I need to do same checks before inserting the Service Item
Internal work item: [AB#554341](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554341)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
