### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick" - Function "ProcessDoNotFillQtytoHandle" - Add event OnBeforeProcessDoNotFillQtytoHandle

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27388]
### Describe the request

Hello, can you please add a new Event "OnBeforeProcessDoNotFillQtytoHandle" in codeunit 7312 "Create Pick" - Function "ProcessDoNotFillQtytoHandle" ?

local procedure ProcessDoNotFillQtytoHandle(var WarehouseActivityLine: Record "Warehouse Activity Line")
begin
        OnBeforeProcessDoNotFillQtytoHandle(WarehouseActivityLine, TempWarehouseActivityLine, CreatePickParameters);

        if CreatePickParameters."Do Not Fill Qty. to Handle" then begin
            WarehouseActivityLine."Qty. to Handle" := 0;
            WarehouseActivityLine."Qty. to Handle (Base)" := 0;
            WarehouseActivityLine.Cubage := 0;
            WarehouseActivityLine.Weight := 0;
        end;

        OnAfterProcessDoNotFillQtytoHandle(WarehouseActivityLine, TempWarehouseActivityLine);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeProcessDoNotFillQtytoHandle(var WarehouseActivityLine: Record "Warehouse Activity Line"; var TempWarehouseActivityLine: Record "Warehouse Activity Line" temporary; var CreatePickParameters: Record "Create Pick Parameters")
begin
end;

### Additional context

We must perform actions and not set fields to zero in the case of CreatePickParameters.???Do Not Fill Qty. to Handle??? field is set to ???false???.
Internal work item: [AB#554363](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554363)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
