### ISSUE TITLE
[EVENT PUBLISHER CHANGE] in event "OnInsertPurchLinesOnBeforeAppStdVendPurchCodes" in table 175 "Standard Vendor Purchase Code"

### ISSUE THREAD

**Issue by PawelBartos-Integro** [microsoft/ALAppExtensions#27393]
### Describe the request

Hello.
Please add variable PurchHeader to the event "OnInsertPurchLinesOnBeforeAppStdVendPurchCodes" in the table "Standard Vendor Purchase Code".

### Additional context

We want to handle the code in diffrent way curent but we need to have a context of document.

![Image](https://github.com/user-attachments/assets/042f8d69-ceb3-43cd-a7d4-fe7f633b1e68)

In our opinion the publishes should look like this:
OnlnsertPurchLinesOnBeforeApplyStdVendPurchCodes(StdVendPurchCode, PurchHeader, IsHandled) ;
Internal work item: [AB#554364](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554364)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
