### ISSUE TITLE
[Event Modification] page 99000883 "Sales Order Planning"– OnBeforeCreateOrder - Add additional var parameter HideValidationDialog

### ISSUE THREAD

**Issue by andresteunenberg1964** [microsoft/ALAppExtensions#27398]
### Describe the request

Could you add a new Boolean variable as a var parameter to the existing event OnBeforeCreateOrder because we want to customize the behavior of creating production orders from the sales planning page . We would like to have the possibility (customization) that the message that a production order is created will be skipped.
 
    local procedure CreateOrder(CreateProdOrder: Boolean; var SalesLine: Record "Sales Line"; var EndLoop: Boolean; var OrdersCreated: Boolean)
    var
        CreateProdOrderFromSale: Codeunit "Create Prod. Order from Sale";
    Begin
       // Old to be removed:            
      //  OnBeforeCreateOrder(Rec, SalesLine, CreateProdOrder);

      // New as replacement: 
       OnBeforeCreateOrder(Rec, SalesLine, CreateProdOrder, HideValidationDialog);

        if CreateProdOrder then begin
            OrdersCreated := true;
        // Add New
            CreateProdOrderFromSale.SetHideValidationDialog(HideValidationDialog);

            CreateProdOrderFromSale.CreateProductionOrder(SalesLine, NewStatus, NewOrderType);
            if NewOrderType = NewOrderType::ProjectOrder then
                EndLoop := true;
        end;
    end;

 
Original Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateOrder(var SalesPlanningLine: Record "Sales Planning Line"; var SalesLine: Record "Sales Line"; var CreateProdOrder: Boolean);
    begin
    end;
 
Modified Event as replacement:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateOrder(var SalesPlanningLine: Record "Sales Planning Line"; var SalesLine: Record "Sales Line"; var CreateProdOrder: Boolean, var HideValidationDialog; Boolean);
    begin
    end;

 

### Additional context

Our Customer creates production orders from the sales order planning page. When the order contains many item lines, for every production order created a popup (message) will appear. We want to skip these messages.
Internal work item: [AB#554766](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554766)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25798.
