### ISSUE TITLE
Change Option Field "Line Discount Type" in Table 5902 "Service Line" to Enum Field

### ISSUE THREAD

**Issue by BITNilsRoolf** [microsoft/ALAppExtensions#27391]
### Describe the request

Please change the "Line Discount Type" field in table "Service Line" to an enum field so it can be extensible

```al
field(5997; "Line Discount Type"; Option)
{
    Caption = 'Line Discount Type';
    Editable = false;
    OptionCaption = ' ,Warranty Disc.,Contract Disc.,Line Disc.,Manual';
    OptionMembers = " ","Warranty Disc.","Contract Disc.","Line Disc.",Manual;
}
``` 

### Additional context

We need to add an additional value, as option field this is not possible
Internal work item: [AB#554360](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554360)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25843.
