### ISSUE TITLE
Event Request - Transfer Line -OnBeforeValidateShortcutDimCode()

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#27396]
### Describe the request

Hello, can you please add IsHandled for this event publisher OnBeforeValidateShortcutDimCode()
for examples
   [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateShortcutDimCode(var TransferLine: Record "Transfer Line"; var xTransferLine: Record "Transfer Line"; FieldNumber: Integer; var ShortcutDimCode: Code[20], Ishandled:boolean)
    begin
    end;

![Image](https://github.com/user-attachments/assets/66834f30-2234-45c2-9d94-dfa2498f06f5)

### Additional context

we need Ishandled

**Comment by nikolakukrika** [comment]
We cannot allow shipping validation of the shortcut dimension values or Item line dimensions, so this request is rejected. 
Please implement an alternative design and ask for new events.
