### ISSUE TITLE
[EVENT PUBLISHER CHANGE] in event "OnBeforeToPurchLineInsert" in codeunit 378 "Transfer Extended Text"

### ISSUE THREAD

**Issue by tobiasschuermann-gws** [microsoft/ALAppExtensions#27394]
### Describe the request

The current event signature look like this:
`[IntegrationEvent(false, false)]
local procedure OnBeforeToPurchLineInsert(var ToPurchLine: Record "Purchase Line"; PurchLine: Record "Purchase Line"; TempExtTextLine: Record "Extended Text Line" temporary; var NextLineNo: Integer; LineSpacing: Integer; var IsHandled: Boolean)
`
Compared to the same event for the sales line there is a var parameter missing for the Purchline Record.

So it should look like this:
`[IntegrationEvent(false, false)]
local procedure OnBeforeToPurchLineInsert(var ToPurchLine: Record "Purchase Line"; var PurchLine: Record "Purchase Line"; TempExtTextLine: Record "Extended Text Line" temporary; var NextLineNo: Integer; LineSpacing: Integer; var IsHandled: Boolean)
`

Thanks in advance,
Tobi

### Additional context

We need the var parameter, because we want to skip the description line of standard texts and just insert the extended text lines.
Internal work item: [AB#554365](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554365)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25639.
