### ISSUE TITLE
[Event Request] Codeunit 5805 "Item Charge Assgnt. (Purch.)" - Function "AssignItemCharges" - Add event "OnBeforeAssignByMenuText"

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27395]
### Describe the request

Hello, can you please add a new Event "OnBeforeAssignByMenuText" in codeunit 5805 "Item Charge Assgnt. (Purch.)" - Function "OnBeforeAssignByMenuText" ?

procedure AssignItemCharges(PurchLine: Record "Purchase Line"; TotalQtyToAssign: Decimal; TotalAmtToAssign: Decimal; TotalQtyToHandle: Decimal; TotalAmtToHandle: Decimal; SelectionTxt: Text)
    var
        Currency: Record Currency;
        PurchHeader: Record "Purchase Header";
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        ItemChargesAssigned: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeAssignItemCharges(PurchLine, TotalQtyToAssign, TotalAmtToAssign, IsHandled);
        if IsHandled then
            exit;

        PurchLine.TestField("Qty. to Invoice");
        PurchHeader.Get(PurchLine."Document Type", PurchLine."Document No.");
        if not Currency.Get(PurchHeader."Currency Code") then
            Currency.InitRoundingPrecision();

        ItemChargeAssgntPurch.SetRange("Document Type", PurchLine."Document Type");
        ItemChargeAssgntPurch.SetRange("Document No.", PurchLine."Document No.");
        ItemChargeAssgntPurch.SetRange("Document Line No.", PurchLine."Line No.");

        if not ItemChargeAssgntPurch.IsEmpty() then begin
            ItemChargeAssgntPurch.ModifyAll("Amount to Assign", 0);
            ItemChargeAssgntPurch.ModifyAll("Qty. to Assign", 0);
            ItemChargeAssgntPurch.ModifyAll("Amount to Handle", 0);
            ItemChargeAssgntPurch.ModifyAll("Qty. to Handle", 0);
            ItemChargeAssgntPurch.FindSet();

           IsHandled := false;
           OnBeforeAssignByMenuText(ItemChargeAssgntPurch, Currency, PurchHeader, TotalQtyToAssign, TotalAmtToAssign, TotalQtyToHandle, TotalAmtToHandle, SelectionTxt);
           if IsHandled then
             exit;

            case SelectionTxt of
                AssignEquallyMenuText():
                    AssignEqually(ItemChargeAssgntPurch, Currency, TotalQtyToAssign, TotalAmtToAssign, TotalQtyToHandle, TotalAmtToHandle);
                AssignByAmountMenuText():
                    AssignByAmount(ItemChargeAssgntPurch, Currency, PurchHeader, TotalQtyToAssign, TotalAmtToAssign, TotalQtyToHandle, TotalAmtToHandle);
                AssignByWeightMenuText():
                    AssignByWeight(ItemChargeAssgntPurch, Currency, TotalQtyToAssign);
                AssignByVolumeMenuText():
                    AssignByVolume(ItemChargeAssgntPurch, Currency, TotalQtyToAssign);
                else begin
                    OnAssignItemCharges(
                      SelectionTxt, ItemChargeAssgntPurch, Currency, PurchHeader, TotalQtyToAssign, TotalAmtToAssign, ItemChargesAssigned);
                    if not ItemChargesAssigned then
                        Error(ItemChargesNotAssignedErr);
                end;
            end;
        end;
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforeAssignByMenuText(var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; Currency: Record Currency; PurchHeader: Record "Purchase Header"; TotalQtyToAssign: Decimal; TotalAmtToAssign: Decimal; TotalQtyToHandle: Decimal; TotalAmtToHandle: Decimal; SelectionTxt: Text; IsHandled: Boolean)
begin
end;

### Additional context

We need to use those variables: TotalQtyToAssign,TotalAmtToAssign in "AssignByVolume" standard function and not execute all the standard code.
Internal work item: [AB#554366](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/554366)

**Comment by JakovljevicDusan** [comment]
Added variables to OnBeforeAssignItemCharges

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25798.
