### ISSUE TITLE
[Event Request] codeunit 1521 "Workflow Response Handling" (local procedure CreateNotificationEntry) - OnCreateNotificationEntry

### ISSUE THREAD

**Issue by ArnisVe** [microsoft/ALAppExtensions#27404]
**Describe the request**

Hello, We require an event for procedure CreateNotificationEntry.

    local procedure CreateNotificationEntry(WorkflowStepInstance: Record "Workflow Step Instance"; var Variant: Variant)
    var
        ApprovalEntry: Record "Approval Entry";
        WorkflowStepArgument: Record "Workflow Step Argument";
        NotificationEntry: Record "Notification Entry";
        RecRef: RecordRef;
        IsHandled: Boolean;
    begin
        OnCreateNotificationEntry(WorkflowStepInstance, Variant, IsHandled);
        if IsHandled then
            exit;

        RecRef.GetTable(Variant);
        case RecRef.Number of
            Database::"Approval Entry":
                begin
                    ApprovalEntry := Variant;
                    IsHandled := false;
                    OnBeforeCreateNotificationEntry(WorkflowStepInstance, ApprovalEntry, IsHandled);
                    if IsHandled then
                        exit;

                    if WorkflowStepArgument.Get(WorkflowStepInstance.Argument) then
                        NotificationEntry.CreateNotificationEntry(WorkflowStepArgument."Notification Entry Type", WorkflowStepArgument.GetNotificationUserID(ApprovalEntry), ApprovalEntry, WorkflowStepArgument."Link Target Page", WorkflowStepArgument."Custom Link", CopyStr(UserId(), 1, 50));
                end;
            Database::"Incoming Document",
            Database::"Gen. Journal Line",
            Database::"Purchase Header",
            Database::"Purch. Inv. Header":
                if WorkflowStepArgument.Get(WorkflowStepInstance.Argument) then
                    if WorkflowStepArgument."Notify Sender" then
                        NotificationEntry.CreateNotificationEntry(WorkflowStepArgument."Notification Entry Type", CopyStr(UserId(), 1, 50), Variant, WorkflowStepArgument."Link Target Page", WorkflowStepArgument."Custom Link", CopyStr(UserId(), 1, 50))
                    else
                        NotificationEntry.CreateNotificationEntry(WorkflowStepArgument."Notification Entry Type", WorkflowStepArgument."Notification User ID", Variant, WorkflowStepArgument."Link Target Page", WorkflowStepArgument."Custom Link", CopyStr(UserId(), 1, 50));
            else begin
                ApprovalEntry.SetRange("Record ID to Approve", RecRef.RecordId);
                if ApprovalEntry.FindFirst() then begin
                    Variant := ApprovalEntry;
                    CreateNotificationEntry(WorkflowStepInstance, Variant);
                end else
                    Error(UnknownRecordErr);
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateNotificationEntry(var WorkflowStepInstance: Record "Workflow Step Instance"; var Variant: Variant; var IsHandled: Boolean)
    begin
    end;

**Additional context**

We have our own custom table and would like to use the existing functionality with workflows for creating notification entries without the need to go through Approval Entry table.

**Comment by nikolakukrika** [comment]
Can you use an alternative design? IsHandled event with a variant is a rather broad approach.
There are already events around this code that can be used to handle the request, we are also skipping this table in case of the Power Automate events. 

Examples of the existing events that can be used:
codeunit 1521 "Workflow Response Handling"
        OnBeforeExecuteResponse(Variant, ResponseWorkflowStepInstance, xVariant, IsHandled);
