### ISSUE TITLE
[Event Request] Table 472 "Job Queue Entry".SetDefaultValues

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27415]
### Describe the request

Please add new parameter to existing event and new event.

 ```
    local procedure SetDefaultValues(SetupUserId: Boolean)
    var
        Language: Codeunit Language;
        //--------------------------------------------OnSetDefaultValuesOnBeforeSetUserID:BEGIN
        IsHandled: Boolean;
    //-----------------------------------------------OnSetDefaultValuesOnBeforeSetUserID:END
    begin
        "Last Ready State" := CurrentDateTime();
        "User Language ID" := Language.GetLanguageIdOrDefault(Language.GetUserLanguageCode());
        //---------------------------------------------OnSetDefaultValuesOnBeforeSetUserID:BEGIN
        OnSetDefaultValuesOnBeforeSetUserID(Rec, xRec, SetupUserId, IsHandled);
        //---------------------------------------------OnSetDefaultValuesOnBeforeSetUserID:END
        if not IsHandled then
            if SetupUserId then
                "User ID" := UserId();
        "No. of Attempts to Run" := 0;
        if "Job Timeout" = 0 then
            "Job Timeout" := DefaultJobTimeout();

        //----------------------------------------------------------OnAfterSetDefaultValues:BEGIN
        //OnAfterSetDefaultValues(Rec);
        OnAfterSetDefaultValues(Rec, xRec);
        //----------------------------------------------------------OnAfterSetDefaultValues:END
    end;
 
//----------------------------------------------------------OnAfterSetDefaultValues:BEGIN
    [IntegrationEvent(true, false)]
    //local procedure OnAfterSetDefaultValues(var JobQueueEntry: Record "Job Queue Entry")
    local procedure OnAfterSetDefaultValues(var JobQueueEntry: Record "Job Queue Entry"; xJobQueueEntry: Record "Job Queue Entry")
    begin
    end;
    //----------------------------------------------------------OnAfterSetDefaultValues:END

    //-----------------------------------------------OnSetDefaultValuesOnBeforeSetUserID:BEGIN
    [IntegrationEvent(true, false)]
    local procedure OnSetDefaultValuesOnBeforeSetUserID(var JobQueueEntry: Record "Job Queue Entry"; xJobQueueEntry: Record "Job Queue Entry"; var SetupUserId: Boolean; var IsHandled: Boolean)
    begin
    end;
    //------------------------------------------------OnSetDefaultValuesOnBeforeSetUserID:END
```

### Additional context

We have different logic for filling userID to job queue entry.
Internal work item: [AB#555033](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555033)

**Comment by darjoo** [comment]
Hi @fridrichovsky, what do you mean you have a different logic for filling userID?

Setting a different userID does not mean the Job Queue will be run under that other userID that is set on the record.
I do not see any value in this if what you want to do is change the userID to be someone else than the one actually running the Job Queue.

**Comment by fridrichovsky** [comment]
Hi @darjoo,
Job Queue Entry have one problem for us. If I change parameters or insert record it set current userid(). It is ok for postponded invoicing, but we have more jobs where current user do not have enough permission for that job. So we need keep there preset user that have enough permissions. We preset user id by setups. 
Example:
ICT guy who works with Job Queues and who can change parameters do not have permission for value entry table that is required by adjustment job. So this quy can not change parameters because it change userid to him but job fail because permissions. So we need keep there userid that have permissions for value entry and we do not want add permissions to ICT guy.

What I see we can skip parameter IsHandled because it is duplication for "SetupUserId"

**Comment by darjoo** [comment]
@fridrichovsky What kind of parameters is the ICT guy changing?

There are a few parameters that causes the UserId to be changed.
- "User ID"
- "Object Type to Run"
- "Object ID to Run"
- "Parameter String"

There is another event you could consider if what you want is to avoid the updating of the UserId. 
OnModifyOnAfterRunParametersChangedCalculated that is run in the OnModify trigger, it has the `RunParametersChanged` var parameter.

I would highly suggest not to avoid changing the "User ID" field as it's purely a visibility field and does not affect who runs the underlying task running.

**Comment by fridrichovsky** [comment]
Hi @darjoo,
Are you sure that is for visibility what I know from older version this field was used when new session was started for job queue entry. So we had problem with permission during job running.

Your suggested event looks good and I can imagine that I can use it.

**Comment by darjoo** [comment]
@fridrichovsky Which version are you talking about? 
I do not remember this ever changing who ran the underlying task since I first started touching Job Queues back in ~v15.

I'll close the request as the event should suffice. But do @ me and let me know which version used to be different, as I'd like to know that.
