### ISSUE TITLE
Shopify Sync Inventory - Missing parameters in interrface/event

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/ALAppExtensions#27413]
### Describe the request

1. Make Shpfy Shop Location non-internal.
![Image](https://github.com/user-attachments/assets/2f3d4871-e8c6-426b-ac07-251b184bd536)

2. Extend Shpfy Stock Calculation with the Shpfy Shop Location OR Shpfy Shop as a parameter for a GetStock procedure.
![Image](https://github.com/user-attachments/assets/cc65b549-dcb0-47dc-9546-2fd298fe0aa9)

3. Extend the OnAfterCalculationStock with the Shpfy Shop Location as a parameter
![Image](https://github.com/user-attachments/assets/804a21ac-3530-456a-bfa4-26189fd1f87d)

### Additional context

When synchronizing inventory from Business Central to Shopify there's multiple different options for the stock calculation.
However when Shopify receives the Inventory it will always subtract the commited stock (open orders) and the result becomes the available stock in Shopify.
To accomodate this Business Central must always synchronize an inventory level that is Inventory + Committed. 

**One Shopify Shop**
Committed should be equal to outstanding quantity from all sales lines.
In theory this could be made using the current implementation if you're only using one Shopify Shop.

**Multiple Shopify Shops**

When working with multiple Shops the "Committed" quantity is different per shop, which means that the outstanding quantity on sales lines must also be filtered per shop.
This is not possible currently.
There's two ways to do it, but neither works:

1. Creating an Enumextension and a new implementation for Shpfy Stock Calculation
This is not possible because the interface does not include the shop, shop location or anything. Which means you're not able to do the sales line calculation here.

2. Subscribing to OnAfterCalculationStock
This is also not possible because the OnAfterCalculationStock does not include the ShopLocation (only the Stock Filter), so there is no option to check which implementation is selected.
Shopify Shop Location table is also marked as internal, so no way of checking manually.

**Solutions**
I would prefer to have the interface extended to include the Shopify Shop Location as a parameter.
If that's not possible, it would also be enough to include the Shopify Shop Location as a parameter on the OnAfterCalculationStock - However, this requires you to make a new implementation AND an event subscriber.

Internal work item: [AB#555031](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555031)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25763.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25849.
