### ISSUE TITLE
Error on "Verify Registration" at "Email Microsoft Entra application registration"

### ISSUE THREAD

**Issue by wansong-yu** [microsoft/ALAppExtensions#27412]
### Describe the request

1. Describe the issue
We installed BC 24.2 India version On-Prem and repeated again on W1 version
We are trying to configure the mailing functionality in Business Central but receiving the following error while clicking "Verify Registration" action on the "Email Microsoft Entra application registration" page.
![Image](https://github.com/user-attachments/assets/65040883-fafe-4447-bde0-e347f86733cd)

2. Actual behavior
An error "A DotNet variable has not been instantiated. Attempting to call Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.LastErrorMessage in CodeUnit OAuth2Impl: GetLastErrorMessage" is shown

### Additional context

The whole email features (M365 connections) cannot work

**Comment by JesperSchulz** [comment]
That could be a product defect and must hence get reported to support, to ensure it is addressed within the right SLA and in all supported versions of Business Central.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
