### ISSUE TITLE
[Event Request] Codeunit 5813 "Undo Purchase Receipt Line" - OnCheckPurchRcptLineOnBeforeTestFields

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#27426]
### Describe the request

Hi there,

Could you please add event OnCheckPurchRcptLineOnBeforeTestFields to procedure CheckPurchRcptLine to CU 5813 "Undo Purchase Receipt Line"?

```al
if PurchRcptLine.Type = PurchRcptLine.Type::Item then begin
    //NEW CODE BEGIN
    IsHandled := false;
    OnCheckPurchRcptLineOnBeforeTestFields(IsHandled, PurchRcptLine)
    if not IsHandled then begin
    //NEW CODE END
        PurchRcptLine.TestField("Prod. Order No.", '');
        PurchRcptLine.TestField("Sales Order No.", '');
        PurchRcptLine.TestField("Sales Order Line No.", 0);
    //NEW CODE BEGIN
    end;
    //NEW CODE END

    UndoPostingMgt.TestPurchRcptLine(PurchRcptLine);
```

```al
    [IntegrationEvent(false, false)]
    local procedure  OnCheckPurchRcptLineOnBeforeTestFields(var IsHandled: Boolean; var PurchRcptLine: Record "Purch. Rcpt. Line")
    begin
    end;
```

### Additional context

We have to disable tests of Sales Order fields - to handle extended drop shipment process
Internal work item: [AB#555537](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555537)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25893.
