### ISSUE TITLE
[Event Request] codeunit 31305 "Item Jnl-Post Line Handler CZA", procedure CheckInventoryPostingGroupOnPostItemOnBeforeSetAverageTransfer()

### ISSUE THREAD

**Issue by mtomEBS** [microsoft/ALAppExtensions#27420]
### Describe the request

I would like to ask for a new publisher in the codeunit 31305 "Item Jnl-Post Line Handler CZA", procedure CheckInventoryPostingGroupOnPostItemOnBeforeSetAverageTransfer(). Whether it would be possible to add to the following code a way to bypass the testfield in the Czech version.
Other possibility would be to control this behaviour by setup in BC. Thank you.

```
[EventSubscriber(ObjectType::Codeunit,Codeunit::"Item Jnl.-Post Line", 'OnPostItemOnBeforeSetAverageTransfer', '', false, false)]
local procedure CheckInventoryPostingGroupOnPostItemOnBeforeSetAverageTransfer(var ItemJnlLine: Record "Item Journal Line"; CalledFromAdjustment: Boolean)
    var
         Item: Record Item;
         IsHandled: Boolean;     // NEW EVENT
     begin
         if ItemJnlLine."Item No." = '' then
             exit;
 
         // NEW EVENT ->
         IsHandled := false;
         OnBeforeTestFieldInventoryPostingGroup(ItemJnlLine, IsHandled)
         if IsHandled then
           exit;
         // <- NEW EVENT
 
         Item.Get(ItemJnlLine."Item No.");
         if not (ItemJnlLine."Inventory Posting Group" = '') and (Item.Type = Item.Type::Inventory) then
             if not CalledFromAdjustment and (Item.Type = Item.Type::Inventory) then
                 ItemJnlLine.TestField("Inventory Posting Group", Item."Inventory Posting Group");
     end;
 
   // NEW EVENT
   [IntegrationEvent(false, false)]
   local procedure OnBeforeTestFieldInventoryPostingGroup(var ItemJnlLine: Record "Item Journal Line";  var IsHandled: Boolean)
   begin
   end;

```

### Additional context

Good morning,

We would like to ask you whether it would be possible to add to the following code a way to bypass the testfield in the Czech version.

1.Either by setup in BC OR
2.Providing our developers with an event so that we can subscribe and to it and bypass in our extension.

Thank you,

```
if not (ItemJnlLine."Inventory Posting Group" = '') and (Item.Type = Item.Type::Inventory) then
  if not CalledFromAdjustment and (Item.Type = Item.Type::Inventory) then
    ItemJnlLine.TestField("Inventory Posting Group", Item."Inventory Posting Group");
```
Internal work item: [AB#555040](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555040)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26416.
