### ISSUE TITLE
[Request-For-External] COD2677 "Gen. Journal Alloc. Acc. Mgt." - Procedure VerifySelectedAllocationAccountNo()

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27432]
### Describe the request

Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

```
[Request-For-External] codeunit 2677 "Gen. Journal Alloc. Acc. Mgt." - Procedure from Internal to Global

procedure VerifySelectedAllocationAccountNo(var GenJournalLine: Record "Gen. Journal Line")
```	

### Additional context

Duplicated the actions from General Journal to a own Journal.
Internal work item: [AB#555532](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555532)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26242.
