### ISSUE TITLE
[Request for External] REP295 "Combine Shipments" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27434]
### Describe the request

Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
[Request for External] REP295 "Combine Shipments" - Protected variables

    protected var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
        SalesShptLine: Record "Sales Shipment Line";
        PostingDateReq: Date;
        DocDateReq: Date;
        VATDateReq: Date;
        CalcInvDisc: Boolean;
        PostInv: Boolean;
        OnlyStdPmtTerms: Boolean;
        CopyTextLines: Boolean;
        VATDateEnabled: Boolean;
    // NEW ++ <<<
        HasAmount: Boolean;
        NoOfSalesInvErrors: Integer;
        Cust: Record Customer;
        LanguageMgt: Codeunit Language;
        ReportLanguage: Integer;
        ReportFormatRegion: Text[80];
	// NEW ++ >>>	
```	

### Additional context

Get access to the parameters out of Sender-Events
Internal work item: [AB#555531](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555531)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26068.
