### ISSUE TITLE
[Event Request] Table 37 - Sales Line - Procedure CalcUnitPriceUsingUOMCoef - OnAfterCalcUnitPriceUsingUOMCoef

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27436]
### Describe the request

Please add the following Event/-s OnAfterCalcUnitPriceUsingUOMCoef to procedure CalcUnitPriceUsingUOMCoef in Table 37 - Sales Line.

```
[Event Request] TAB37 - Sales Line - Procedure CalcUnitPriceUsingUOMCoef
    procedure CalcUnitPriceUsingUOMCoef()
    var
        SalesInvoiceLine: Record "Sales Invoice Line";
    begin
        GetSalesInvoiceLine(SalesInvoiceLine);

        if SalesInvoiceLine."Line No." = 0 then
            exit;

        "Unit Price" := ("Qty. per Unit of Measure" * SalesInvoiceLine."Unit Price") / SalesInvoiceLine."Qty. per Unit of Measure";

        OnAfterCalcUnitPriceUsingUOMCoef(Rec,SalesInvoiceLine);
    end;
```

```
 [IntegrationEvent(false, false)]
 local procedure OnAfterCalcUnitPriceUsingUOMCoef(var SalesLine : Record "Sales Line"; SalesInvoiceLine: Record "Sales Invoice Line")
    begin
    end;
```

### Additional context

Change the calculation
Internal work item: [AB#555527](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555527)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
