### ISSUE TITLE
[Event Request] Additional variable IsHandled to event  OnPreReportOnBeforeCopyPurchReturnDoc - report 6697 "Create Ret.-Related Documents"

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#27439]
### Describe the request

Hi there,

Could you please add additional variables (with logic) - IsHandled, TempRetRelDoc to event OnPreReportOnBeforeCopyPurchReturnDoc in report 6697 "Create Ret.-Related Documents"?

```al
        if CreatePRO then begin
        PROPurchHeader."Document Type" := PROPurchHeader."Document Type"::"Return Order";
        Clear(CopyDocMgt);
        CopyDocMgt.SetProperties(true, false, false, false, true, false, false);
        //NEW CODE BEGIN
        IsHandled := false;
        OnPreReportOnBeforeCopyPurchReturnDoc(CopyDocMgt, SROSalesHeader, PROPurchHeader, IsHandled, TempRetRelDoc);
        if not IsHandled then begin
        //NEW CODE END
          CopyDocMgt.CopyFromSalesToPurchDoc(VendorNo, SROSalesHeader, PROPurchHeader);
          OnPreReportOnAfterCopyPurchReturnDoc(SROSalesHeader, PROPurchHeader);
          TempRetRelDoc."Entry No." := 1;
          TempRetRelDoc."Document Type" := TempRetRelDoc."Document Type"::"Purchase Return Order";
          TempRetRelDoc."No." := PROPurchHeader."No.";
          TempRetRelDoc.Insert();
        //NEW CODE BEGIN
        end;
        //NEW CODE END
    end;

```
    [IntegrationEvent(false, false)]
    local procedure OnPreReportOnBeforeCopyPurchReturnDoc(var CopyDocumentMgt: Codeunit "Copy Document Mgt."; var SROSalesHeader: Record "Sales Header"; var PROPurchHeader: Record "Purchase Header"; var IsHandled: Boolean; var TempRetRelDoc: Record "Returns-Related Document")
    begin
    end;

### Additional context

We have to handle additional scenario in PRO case. 
Internal work item: [AB#555525](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555525)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
