### ISSUE TITLE
[Request-For-External] COD6532 "Continuous Item Tracking" - Procedure GetInput()

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27431]
### Describe the request

Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

```
[Request-For-External] Page 6532 "Continuous Item Tracking" - Procedure from Internal to Global

procedure GetInput(): Text

```	

### Additional context

Call the procedure from a copied custom Item Tracking Page with similar behavior than PAG6510
Internal work item: [AB#555530](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555530)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26068.
