### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnPostVendOnBeforeInsertDtldCVLedgEntry

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27444]
### Describe the request

Hello, can you please add a new event OnPostVendOnBeforeInsertDtldCVLedgEntry in codeunit 12 "Gen. Jnl.-Post Line"?

```
    local procedure PostVend(var GenJournalLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
.
.
.
        OnPostVendOnAfterInitVendLedgEntry(GenJournalLine, VendLedgEntry, Vend);
        if not Vend."Block Payment Tolerance" then
            CalcPmtTolerancePossible(
                GenJournalLine, VendLedgEntry."Pmt. Discount Date", VendLedgEntry."Pmt. Disc. Tolerance Date",
                VendLedgEntry."Max. Payment Tolerance");

        TempDtldCVLedgEntryBuf.DeleteAll();
        TempDtldCVLedgEntryBuf.Init();
        OnPostVendOnBeforeCopyCVLedgEntryBuf(CVLedgEntryBuf, GenJournalLine, Vend);
        TempDtldCVLedgEntryBuf.CopyFromGenJnlLine(GenJournalLine);
        TempDtldCVLedgEntryBuf."CV Ledger Entry No." := VendLedgEntry."Entry No.";
        OnPostVendAfterTempDtldCVLedgEntryBufInit(GenJournalLine, TempDtldCVLedgEntryBuf);

        CVLedgEntryBuf.CopyFromVendLedgEntry(VendLedgEntry);
        TempDtldCVLedgEntryBuf.InsertDtldCVLedgEntry(TempDtldCVLedgEntryBuf, CVLedgEntryBuf, true);
        CVLedgEntryBuf.Open := CVLedgEntryBuf."Remaining Amount" <> 0;
        CVLedgEntryBuf.Positive := CVLedgEntryBuf."Remaining Amount" > 0;
        OnPostVendOnAfterCopyCVLedgEntryBuf(CVLedgEntryBuf, GenJournalLine);

        CalcPmtDiscPossible(GenJournalLine, CVLedgEntryBuf);
```

```
    [IntegrationEvent(false, false)]
    local procedure OnPostVendOnBeforeInsertDtldCVLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; var TempDetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; var VendLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;
```

### Additional context

We would like to fill additional fields in GenJournalLine, TempDtldCVLedgEntryBuf, and CVLedgEntryBuf.
This event is similar to the existing event OnPostCustOnBeforeInsertDtldCVLedgEntry in procedure PostCust.
Internal work item: [AB#555522](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555522)

**Comment by dcenic** [comment]
Rejected. You can fill additional fields in GenJournalLine, TempDtldCVLedgEntryBuf, and CVLedgEntryBuf by utilizing existing events in this code:
OnPostVendOnBeforeCopyCVLedgEntryBuf(CVLedgEntryBuf, GenJournalLine, Vend);
OnPostVendAfterTempDtldCVLedgEntryBufInit(GenJournalLine, TempDtldCVLedgEntryBuf);
Also, these two function calls raise additional events inside with which you can achieve your goal
        CVLedgEntryBuf.CopyFromVendLedgEntry(VendLedgEntry);
        TempDtldCVLedgEntryBuf.InsertDtldCVLedgEntry(TempDtldCVLedgEntryBuf, CVLedgEntryBuf, true);
