### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeCheckBankAccPostingGroup

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27448]
### Describe the request

Hello, can you please add a new event OnBeforeCheckBankAccPostingGroup in codeunit 12 "Gen. Jnl.-Post Line"?

```
    local procedure PostBankAcc(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
.
.
.
        BankAcc.Get(GenJnlLine."Account No.");
        BankAcc.TestField(Blocked, false);
        IsHandled := false;
        OnPostBankAccOnBeforeCheckCurrencyCode(GenJnlLine, BankAcc, IsHandled);
        if not IsHandled then
            if GenJnlLine."Currency Code" = '' then
                BankAcc.TestField("Currency Code", '')
            else
                if BankAcc."Currency Code" <> '' then
                    GenJnlLine.TestField("Currency Code", BankAcc."Currency Code");

        IsHandled := false;
        OnBeforeCheckBankAccPostingGroup(GLSetup, GenJnlLine, IsHandled);
        if not IsHandled then begin
            BankAcc.TestField("Bank Acc. Posting Group");
            BankAccPostingGr.Get(BankAcc."Bank Acc. Posting Group");
        end;

        BankAccLedgEntry.LockTable();
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckBankAccPostingGroup(GeneralLedgerSetup: Record "General Ledger Setup"; GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

In some cases we are not using the Bank Acc. Posting Group but a G/L Account that depends on the customer or vendor. Therefore, we would like to be able to skip checking the Bank Acc Posting Group to avoid an error message.
Internal work item: [AB#555517](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555517)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
