### ISSUE TITLE
[event publisher insert] in event "Copy Document Mgt." (Codeunit 6620) proc "CopySalesCrMemoLinesToDoc"

### ISSUE THREAD

**Issue by hobali** [microsoft/ALAppExtensions#27459]
Dear Support,

Could you please create a new publisher in "Copy Document Mgt." (Codeunit 6620) and a bit the following code, at procedure "CopySalesCrMemoLinesToDoc"? The publishers name could be: "OnAfterFindSalesLineBufOnBeforeGetNextLineNo".

<<<<< Original Code >>>>>
```
// Sorting according to Sales Line Document No.,Line No.
        FromSalesLineBuf.SetCurrentKey("Document Type", "Document No.", "Line No.");
        if FromSalesLineBuf.FindSet() then begin
            NextLineNo := GetLastToSalesLineNo(ToSalesHeader);
            repeat
                ToLineCounter := ToLineCounter + 1;
```

<<<<< Modified >>>>>
```
[IntegrationEvent(false, false)]
local procedure OnAfterFindSalesLineBufOnBeforeGetNextLineNo(ToSalesHeader: Record "Sales Header"; var IsHandled: Boolean; var NextLineNo: Integer; TempSalesLineBuf: Record "Sales Line" temporary)
    begin
    end;
```

```
// Sorting according to Sales Line Document No.,Line No.
        FromSalesLineBuf.SetCurrentKey("Document Type", "Document No.", "Line No.");
        if FromSalesLineBuf.FindSet() then begin
            IsHandled := false;
            OnAfterFindSalesLineBufOnBeforeGetNextLineNo(ToSalesHeader, IsHandled, NextLineNo, TempSalesLineBuf);
            if not IsHandled then
                NextLineNo := GetLastToSalesLineNo(ToSalesHeader);
            repeat
                ToLineCounter := ToLineCounter + 1;
```

Additional context
We need to skip the Release part of the code for several times due to a customer condition.

Thank you in advance.
Internal work item: [AB#555511](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555511)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
