### ISSUE TITLE
[Event Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnBeforePostApply, OnApplyCustLedgEntryOnAfterRecalculateAmounts, OnApplyVendLedgEntryOnAfterRecalculateAmounts

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27455]
### Describe the request

Hello, can you please change parameter "GenJnlLine" to "var" in the events OnBeforePostApply, OnApplyCustLedgEntryOnAfterRecalculateAmounts, and OnApplyVendLedgEntryOnAfterRecalculateAmounts in codeunit 12 "Gen. Jnl.-Post Line"?

```
   [IntegrationEvent(false, false)]
    local procedure OnBeforePostApply(var GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; var OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var NewCVLedgEntryBuf2: Record "CV Ledger Entry Buffer")
    begin
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnApplyCustLedgEntryOnAfterRecalculateAmounts(var TempOldCustLedgerEntry: Record "Cust. Ledger Entry" temporary; OldCustLedgerEntry: Record "Cust. Ledger Entry"; CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; var GenJournalLine: Record "Gen. Journal Line")
    begin
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnApplyVendLedgEntryOnAfterRecalculateAmounts(var TempOldVendorLedgerEntry: Record "Vendor Ledger Entry" temporary; OldVendorLedgerEntry: Record "Vendor Ledger Entry"; CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; var GenJournalLine: Record "Gen. Journal Line")
    begin
    end;
```

### Additional context

In some cases we would like to change data in the GenJnlLine based on the two entries applied to each other.
Internal work item: [AB#555508](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555508)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26401.
