### ISSUE TITLE
[Event Change Request] Codeunit 392 "Reminder-Make", OnBeforeFindAndMarkReminderCandidates; TempCustLedgEntryOnHold is not a temporary variable

### ISSUE THREAD

**Issue by KoenLagerwaard** [microsoft/ALAppExtensions#27452]
### Describe the request

[Event Change Request] Codeunit 392 "Reminder-Make", OnBeforeFindAndMarkReminderCandidates; TempCustLedgEntryOnHold is not a temporary variable

The event OnBeforeFindAndMarkReminderCandidates has a variable:  **var TempCustLedgEntryOnHold: Record "Cust. Ledger Entry";** that is not temporary but the Global variable that is linked is temporary:  **TempCustLedgerEntryOnHold: Record "Cust. Ledger Entry" temporary;**

The event variable should be: **var TempCustLedgEntryOnHold: Record "Cust. Ledger Entry temporary";** as then it is the same as the global variable.

### Additional context

I am working on my own way of determining when to create reminders and found this issue. I therefore cannot determine in my own way whether or not to create reminders for the Customer Ledger Entries.
Internal work item: [AB#555515](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555515)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
