### ISSUE TITLE
[Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - procedure PostGLAcc

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27457]
### Describe the request

Hello, can you please change parameter "GenJnlLine" to "var" in procedure PostGLAcc in codeunit 12 "Gen. Jnl.-Post Line"?

```
    local procedure PostGLAcc(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
        GLAcc: Record "G/L Account";
        GLEntry: Record "G/L Entry";
        VATPostingSetup: Record "VAT Posting Setup";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostGLAcc(GenJnlLine, GLEntry, GLEntryNo, IsHandled, TempGLEntryBuf);
        if not IsHandled then begin
```

### Additional context

We would like to use a global variable in the table containing an undetermined number of temporary records.
Internal work item: [AB#555765](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555765)

**Comment by mynjj** [comment]
For the same reasons as in https://github.com/microsoft/ALAppExtensions/issues/27456 this is potentially a breaking change. (there is still nontrivial code after PostGLAcc like f. ex. CheckPostUnrealizedVAT which depend on these values).

See alternatives in the comment of that issue.
