### ISSUE TITLE
[Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - procedure CheckGenJnlLine

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27456]
### Describe the request

Hello, can you please change parameter "GenJournalLine" to "var" in procedure CheckGenJnlLine in codeunit 12 "Gen. Jnl.-Post Line"?

```
    local procedure CheckGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; CheckLine: Boolean)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckGenJnlLine(GenJournalLine, CheckLine, IsHandled);
        if IsHandled then
            exit;

        if CheckLine then begin
            if OverrideDimErr then
                GenJnlCheckLine.SetOverDimErr();
            OnCheckGenJnlLineOnBeforeRunCheck(GenJournalLine);
            GenJnlCheckLine.RunCheck(GenJournalLine);
        end;
    end;
```

### Additional context

We would like to mark some lines with a special flag to handle them in a special way later during posting.
Internal work item: [AB#555766](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555766)

**Comment by mynjj** [comment]
This is potentially a breaking change: `GenJnlCheckLine.RunCheck` has `GenJournalLine` as `var`, the current behavior would just ignore any modifications done in that procedure. If we change it, any changes done there will live through the posting (not only the ones from your events and custom fields/flags), and it's unclear if that will affect later on.

The possibility of creating hard to debug issues exists (although unlikely) and more if there are events.

There are alternatives to what you want to do, like having a separate table related to `GenJournalLine` with any fields/flags you need. Then you can in these events update accordingly these external tables. If you don't want to persist it, this table can be temporary and be in a SingleInstance subscriber, or manually binding events that start at the beginning and end of codeunit 12.
