### ISSUE TITLE
Issue with Control Add-in in AL extension

### ISSUE THREAD

**Issue by rajprince0** [microsoft/ALAppExtensions#2745]
I'm getting this follow Error, I was trying to use pingpong Addin in my Extension

**Microsoft.Dynamics.Nav.Client.PingPong.PingPongAddIn;PublicKeyToken=31bf3856ad364e35, The page contains a control add-in that is not permitted. Contact your system administrator.**

Here is my below code declaration of dotnet

dotnet
{
    assembly("Microsoft.Dynamics.Nav.Client.PingPong")
    {
        type("Microsoft.Dynamics.Nav.Client.PingPong.PingPongAddIn";PingPongAddIn)
        {
            IsControlAddIn = true;
        }
    }
}

and here is my Addin Page.

page 50148 PingPongAddin
{
    // version RG

    PageType = CardPart;
    UsageCategory = Lists;
    Caption = 'PingPong';

    layout
    {
        area(content)
        {
            usercontrol(PingPongControl; PingPongAddin)
            {
                trigger Pong()
                begin
                    Message('Pong received.');
                end;

                trigger AddInReady()
                begin
                    Message('Ready');
                end;

            }
        }
    }

    actions
    {
    }

}

Here is my Screenshot as well. Anybody have any idea how to rectify this problem
![apps](https://user-images.githubusercontent.com/48588664/59032868-e88b1380-8884-11e9-816a-d5d71cecc10d.PNG)
![dotnetpage](https://user-images.githubusercontent.com/48588664/59032871-e88b1380-8884-11e9-8222-1e3fbcd683cb.PNG)
![PingpongPage](https://user-images.githubusercontent.com/48588664/59032873-e88b1380-8884-11e9-8e2b-7a6892c14ad0.PNG)

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
