### ISSUE TITLE
[event publisher insert] in event "Copy Document Mgt." (Codeunit 6620) proc "CopyFromArchSalesDocDimToHdr"

### ISSUE THREAD

**Issue by hobali** [microsoft/ALAppExtensions#27468]
Dear Support,

Could you please create a new publisher in "Copy Document Mgt." (Codeunit 6620) and a bit the following code, at procedure "CopyFromArchSalesDocDimToHdr"? The publishers name could be: "OnAfterSetDimensonsToSalesHeader".

<<<<< Original Code >>>>>
```
ToSalesHeader."Shortcut Dimension 1 Code" := FromSalesHeaderArchive."Shortcut Dimension 1 Code";
ToSalesHeader."Shortcut Dimension 2 Code" := FromSalesHeaderArchive."Shortcut Dimension 2 Code";
ToSalesHeader."Dimension Set ID" := FromSalesHeaderArchive."Dimension Set ID";
```

<<<<< Modified >>>>>
```
[IntegrationEvent(false, false)]
local procedure OnAfterSetDimensonsToSalesHeader(var ToSalesHeader: Record "Sales Header"; FromSalesHeaderArchive: Record "Sales Header Archive")
    begin
    end;
```

```
ToSalesHeader."Shortcut Dimension 1 Code" := FromSalesHeaderArchive."Shortcut Dimension 1 Code";
ToSalesHeader."Shortcut Dimension 2 Code" := FromSalesHeaderArchive."Shortcut Dimension 2 Code";
ToSalesHeader."Dimension Set ID" := FromSalesHeaderArchive."Dimension Set ID";
OnAfterSetDimensonsToSalesHeader(ToSalesHeader, FromSalesHeaderArchive);
```

Additional context
We need to skip the Release part of the code for several times due to a customer condition.

Thank you in advance.
Internal work item: [AB#555503](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555503)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25893.
