### ISSUE TITLE
[event publisher insert] in event "Copy Document Mgt." (Codeunit 6620) proc "InsertOldSalesDocNoLine"

### ISSUE THREAD

**Issue by hobali** [microsoft/ALAppExtensions#27467]
Dear Support,

Could you please create a new publisher in "Copy Document Mgt." (Codeunit 6620) and a bit the following code, at procedure "InsertOldSalesDocNoLine"? The publishers name could be: "OnAfterSkipCopyFromDescOnBeforeNextLineNoSales".

<<<<< Original Code >>>>>
```
if ShouldSkipCopyFromDescription() then
            exit;

        NextLineNo := NextLineNo + 10000;
        ToSalesLine2.Init();
```

<<<<< Modified >>>>>
```
[IntegrationEvent(false, false)]
local procedure OnAfterSkipCopyFromDescOnBeforeNextLineNoSales(var ToSalesHeader: Record "Sales Header"; var NextLineNo: Integer; var IsHandled: Boolean)
    begin
    end;
```
Add IsHandled to local vars
```
if ShouldSkipCopyFromDescription() then
            exit;
        IsHandled := false;
        OnAfterSkipCopyFromDescOnBeforeNextLineNoSales(ToSalesHeader, NextLineNo, IsHandled);
        if not IsHandled then
          NextLineNo := NextLineNo + 10000;
        ToSalesLine2.Init();
```

Additional context
We need to skip the Release part of the code for several times due to a customer condition.

Thank you in advance.
Internal work item: [AB#555504](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555504)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
