### ISSUE TITLE
[Event Change Request] Table 38 "Purchase Header" - OnBeforeConfirmUpdateAllLineDim

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27476]
### Describe the request

We requested this event in this [Issue](https://github.com/microsoft/ALAppExtensions/issues/27076). The event was not implemented in the right way so a small code change has to happen: 

```
    procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)
    var
        ConfirmManagement: Codeunit "Confirm Management";
        NewDimSetID: Integer;
        ReceivedShippedItemLineDimChangeConfirmed: Boolean;
        IsHandled: Boolean;
        DefaultAnswer: Boolean;
    begin
//...
        if NewParentDimSetID = OldParentDimSetID then
            exit;
        if not GetHideValidationDialog() then begin
            DefaultAnswer := true;
            OnUpdateAllLineDimOnBeforeConfirmUpdateAllLineDim(Rec, DefaultAnswer);
//NEW
            if not ConfirmManagement.GetResponseOrDefault(Text051, DefaultAnswer) then
//NEW
                exit;
        end;
```

### Additional context

Allows to change the default answer of the dimension change confirm.
Internal work item: [AB#555494](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555494)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25808.
