### ISSUE TITLE
[event publisher insert] in event "Due Date-Adjust" (codeunit 10700) procedure "PurchAdjustDueDate"

### ISSUE THREAD

**Issue by J4V13R578** [microsoft/ALAppExtensions#27473]
### Describe the request

Dear Support,

Could you please create two new publisher in "Due Date-Adjust" (Codeunit 10700) at procedure "PurchAdjustDueDate". The publishers name could be: "onBeforeSetNonPaymentPeriodFilterAndFields" and "OnBeforeSetPaymentDayFilterAndFields".

<<<<< Original Code >>>>>
       

        if VendorNo = '' then
            exit;
        if not Vendor.Get(VendorNo) then
            exit;

        if Vendor."Non-Paymt. Periods Code" <> '' then
            SetNonPaymentPeriodFilterAndFields(NonPaymentPeriod, NonPaymentPeriod."Table Name"::Vendor, Vendor."Non-Paymt. Periods Code")
        else begin
            CompanyInfo.Get();
            SetNonPaymentPeriodFilterAndFields(
              NonPaymentPeriod, NonPaymentPeriod."Table Name"::"Company Information", CompanyInfo."Non-Paymt. Periods Code")
        end;
        if Vendor."Payment Days Code" <> '' then
            SetPaymentDayFilterAndFields(PaymentDay, PaymentDay."Table Name"::Vendor, Vendor."Payment Days Code")
        else
            SetPaymentDayFilterAndFieldsFromCompany(PaymentDay);

<<<<< Modified >>>>>

        if VendorNo = '' then
            exit;
        if not Vendor.Get(VendorNo) then
            exit;

        IsHandled := false;
        onBeforeSetNonPaymentPeriodFilterAndFields(NonPaymentPeriod, Vendor, IsHandled);
        if not IsHandled then
            if Vendor."Non-Paymt. Periods Code" <> '' then
                SetNonPaymentPeriodFilterAndFields(NonPaymentPeriod, NonPaymentPeriod."Table Name"::Vendor, Vendor."Non-Paymt. Periods Code")
            else begin
                CompanyInfo.Get();
                SetNonPaymentPeriodFilterAndFields(
                  NonPaymentPeriod, NonPaymentPeriod."Table Name"::"Company Information", CompanyInfo."Non-Paymt. Periods Code")
            end;

        IsHandled := false;
        OnBeforeSetPaymentDayFilterAndFields(PaymentDay, Vendor, IsHandled);
        if not IsHandled then
            if Vendor."Payment Days Code" <> '' then
                SetPaymentDayFilterAndFields(PaymentDay, PaymentDay."Table Name"::Vendor, Vendor."Payment Days Code")
            else
                SetPaymentDayFilterAndFieldsFromCompany(PaymentDay);

        AdjustDate(NonPaymentPeriod, PaymentDay, DueDate, MinDate, MaxDate);

    [IntegrationEvent(false, false)]
    local procedure onBeforeSetNonPaymentPeriodFilterAndFields(var NonPaymentPeriod: Record "Non-Payment Period"; Vendor: Record Vendor; IsHandled: Boolean)
    begin
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetPaymentDayFilterAndFields(var PaymentDay: Record "Payment Day"; Vendor: Record Vendor; IsHandled: Boolean)
    begin
    end;   

Thank you in advance.

### Additional context

We need to skip the Release part of the code for several times due to a vendor condition.

Internal work item: [AB#555496](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555496)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27480.
