### ISSUE TITLE
[Event Request] table 38 "Purchase Header" - procedure "PayToAddressEqualsOldBuyFromAddress"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#27477]
### Describe the request

    //current
    local procedure PayToAddressEqualsOldBuyFromAddress(): Boolean
    begin
        if (xRec."Buy-from Address" = "Pay-to Address") and
           (xRec."Buy-from Address 2" = "Pay-to Address 2") and
           (xRec."Buy-from City" = "Pay-to City") and
           (xRec."Buy-from County" = "Pay-to County") and
           (xRec."Buy-from Post Code" = "Pay-to Post Code") and
           (xRec."Buy-from Country/Region Code" = "Pay-to Country/Region Code")
        then
            exit(true);
    end;

    //after event added
    local procedure PayToAddressEqualsOldBuyFromAddress(): Result: Boolean
    begin
        Result := (xRec."Buy-from Address" = "Pay-to Address") and
           (xRec."Buy-from Address 2" = "Pay-to Address 2") and
           (xRec."Buy-from City" = "Pay-to City") and
           (xRec."Buy-from County" = "Pay-to County") and
           (xRec."Buy-from Post Code" = "Pay-to Post Code") and
           (xRec."Buy-from Country/Region Code" = "Pay-to Country/Region Code");
        OnAfterPayToAddressEqualsOldBuyFromAddress(xRec, Rec, Result);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterPayToAddressEqualsOldBuyFromAddress(xPurchaseHeader: Record "Purchase Header"; PurchaseHeader: Record "Purchase Header"; var Result: Boolean)
    begin
    end;

### Additional context

    In Turkish localization, it is necessary to make a calculation like below procedure.   
 
    local procedure HasDifferentPayToAddress(Vendor: Record Vendor) Result: Boolean
    begin
        Result := ("Pay-to Address" <> Vendor.Address) or
          ("Pay-to Address 2" <> Vendor."Address 2") or
          ("Pay-to City" <> Vendor.City) or
          ("Pay-to Country/Region Code" <> Vendor."Country/Region Code") or
          ("Pay-to County" <> Vendor.County) or
          ("Pay-to Post Code" <> Vendor."Post Code") or
          ("Pay-to Contact" <> Vendor.Contact);
        OnAfterHasDifferentPayToAddress(Rec, Vendor, Result);
    end;
Internal work item: [AB#555493](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555493)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25808.
