### ISSUE TITLE
[event publisher insert] in event "Copy Document Mgt." (Codeunit 6620) proc "CheckFirstLineShipped"

### ISSUE THREAD

**Issue by hobali** [microsoft/ALAppExtensions#27471]
Dear Support,

Could you please create a new publisher in "Copy Document Mgt." (Codeunit 6620) and a bit the following code, at procedure "CheckFirstLineShipped"? The publishers name could be: "OnAfterSetSalesCombDocLineNoOnCheckFirstLineShipped".

<<<<< Original Code >>>>>
```
if (DocNo = '') and (ShipmentLineNo = 0) and FirstLineShipped then begin
            FirstLineShipped := false;
            SalesCombDocLineNo := NextLineNo;
            NextLineNo := NextLineNo + 10000;
        end;
```

<<<<< Modified >>>>>
```
[IntegrationEvent(false, false)]
local procedure OnAfterSetSalesCombDocLineNoOnCheckFirstLineShipped(FromSalesLineArchive: Record "Sales Line Archive"; NextLineNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

```
if (DocNo = '') and (ShipmentLineNo = 0) and FirstLineShipped then begin
            FirstLineShipped := false;
            SalesCombDocLineNo := NextLineNo;
            IsHandled := false;
            OnAfterSetSalesCombDocLineNoOnCheckFirstLineShipped(FromSalesLineArchive, NextLineNo, IsHandled);
            if not IsHandled then
                NextLineNo := NextLineNo + 10000;
        end;
```

Additional context
We need to skip the Release part of the code for several times due to a customer condition.

Thank you in advance.
Internal work item: [AB#555502](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555502)

**Comment by tomasevicst** [comment]
Hi, 

Not sure what is the purpose for this publisher. Do you want to skip set NextLineNo?
Isn't it better to have OnAfterCheckFirstLineShipped publisher at the end of procedure?

**Comment by hobali** [comment]
Hi! 
Not necessary skip, In the other hand just change the NextLineNo based on some custom code, with check etc.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
