### ISSUE TITLE
[Request-For-External] Page 40 "Item Journal" - CurrentJnlBatchName

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27472]
### Describe the request

We want to change the CurrentJnlBatchName based on own business logic in a PageExt. Therefore we request to make CurrentJnlBatchName a protected var.

### Additional context

Allows you to change the CurrentJnlBatchName in a PageExtension.
Internal work item: [AB#555500](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555500)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26068.
