### ISSUE TITLE
Codeunit 6166 - "EDoc Import PEPPOL BIS 3.0" - Event publisher request

### ISSUE THREAD

**Issue by AmineAbdouli** [microsoft/ALAppExtensions#27496]
### Describe the request

Hello,
I would like to request the addition of new events within the "ParseInvoice" and "ParseCreditMemo" functions of Codeunit 6166 - "EDoc Import PEPPOL BIS 3.0".
Specifically, we are seeking to add events that would allow us to map additional fields with the corresponding XML files during the import process.
The addition of these events would provide us with the flexibility needed to extend the standard functionality and accommodate custom requirements for field mapping in our implementation.

### Additional context

	local procedure ParseInvoice(EDocument: Record "E-Document"; var PurchaseHeader: Record "Purchase Header" temporary; var PurchaseLine: Record "Purchase Line" temporary; var DocumentAttachment: Record "Document Attachment"; DocumentAttachmentData: Codeunit "Temp Blob"; var TempXMLBuffer: Record "XML Buffer" temporary)
	var
		Base64Convert: Codeunit "Base64 Convert";
		OutStream: OutStream;
		InStream: InStream;
		Path, Value : Text;
	begin
		Path := TempXMLBuffer.Path;
		Value := TempXMLBuffer.Value;
		case Path of
			.
			.
			.
			.
		end;
		OnAfterParseInvoice(EDocument, PurchaseHeader, PurchaseLine, DocumentAttachment, DocumentAttachmentData, TempXMLBuffer, Path, Value);
	end;

	[IntegrationEvent(false, false)]
	internal procedure OnAfterParseInvoice(EDocument: Record "E-Document"; var PurchaseHeader: Record "Purchase Header" temporary; var PurchaseLine: Record "Purchase Line" temporary; var DocumentAttachment: Record "Document Attachment"; DocumentAttachmentData: Codeunit "Temp Blob"; var TempXMLBuffer: Record "XML Buffer" temporary; Path: Text; Value: Text)
	begin
	end;

### Additional context

		
	local procedure ParseCreditMemo(EDocument: Record "E-Document"; var PurchaseHeader: Record "Purchase Header" temporary; var PurchaseLine: record "Purchase Line" temporary; var DocumentAttachment: Record "Document Attachment"; DocumentAttachmentData: Codeunit "Temp Blob"; var TempXMLBuffer: Record "XML Buffer" temporary)
	var
		Base64Convert: Codeunit "Base64 Convert";
		OutStream: OutStream;
		InStream: InStream;
		Path, Value : Text;
	begin
		Path := TempXMLBuffer.Path;
		Value := TempXMLBuffer.Value;
		case Path of
			.
			.
			.
			.
		end;
		OnAfterParseCreditMemo(EDocument, PurchaseHeader, PurchaseLine, DocumentAttachment, DocumentAttachmentData, TempXMLBuffer, Path, Value);
	end;

	[IntegrationEvent(false, false)]
	internal procedure OnAfterParseCreditMemo(EDocument: Record "E-Document"; var PurchaseHeader: Record "Purchase Header" temporary; var PurchaseLine: Record "Purchase Line" temporary; var DocumentAttachment: Record "Document Attachment"; DocumentAttachmentData: Codeunit "Temp Blob"; var TempXMLBuffer: Record "XML Buffer" temporary; Path: Text; Value: Text)
	begin
	end;
Internal work item: [AB#555759](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555759)

**Comment by Groenbech96** [comment]
@AmineAbdouli ping :)

**Comment by AmineAbdouli** [comment]
The reason is to add the path value (AllowanceChargeReason) in a custom field within the imported document lines, as our partner requires this information to be included.
the paths :
 - '/CreditNote/cac:CreditNoteLine/cac:AllowanceCharge/cbc:AllowanceChargeReason'
 - '/Invoice/cac:InvoiceLine/cac:AllowanceCharge/cbc:AllowanceChargeReason'

**Comment by Groenbech96** [comment]
Im curious. Why is CreateInvoiceAllowanceChargeLines not providing that for you?

**Comment by AmineAbdouli** [comment]
@Groenbech96 
because CreateInvoiceAllowanceChargeLines is currently saved in the description field in line while we need to get the item description in this field.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27619.
