### ISSUE TITLE
[Event Request] Report 106 "Customer Detailed Aging" - OnAfterGetCustLedgerEntryOnBeforeUpdateTotal

### ISSUE THREAD

**Issue by BITNilsRoolf** [microsoft/ALAppExtensions#27493]
### Describe the request

Please add event OnAfterGetCustLedgerEntryOnBeforeUpdateTotal in the OnAfterGetRecord trigger of dataitem "Cust. Ledger Entry"

```al
trigger OnAfterGetRecord()
begin
    if "Due Date" = 0D then
        OverDueMonths := 0
    else
        OverDueMonths := CalcFullMonthsBetweenDates("Due Date", EndDate);
    if ("Remaining Amount" = 0) and OnlyOpen then
        CurrReport.Skip();
    OnAfterGetCustLedgerEntryOnBeforeUpdateTotal("Cust. Ledger Entry");
    TempCurrencyTotalBuffer.UpdateTotal(
      "Currency Code", "Remaining Amount", "Remaining Amt. (LCY)", Counter);
end;
``` 

Event definition:

```al
[IntegrationEvent(false, false)]
local procedure OnAfterGetCustLedgerEntryOnBeforeUpdateTotal(var CustLedgerEntry: Record "Cust. Ledger Entry")
begin
end;
``` 

### Additional context

We need to reduce the value of field "Remaining Amount" and "Reminaing Amt. (LCY)" before the UpdateTotal procedure is called.
Internal work item: [AB#555761](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555761)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26351.
