### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line".CreateGLEntryBalAcc - OnAfterInsertGLEntryBalAcc

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27492]
### Describe the request

Hello, could we get this event OnAfterInsertGLEntryBalAcc on Codeunit 12-"Gen. Jnl.-Post Line"?

```
procedure CreateGLEntryBalAcc(GenJnlLine: Record "Gen. Journal Line"; AccNo: Code[20]; Amount: Decimal; AmountAddCurr: Decimal; BalAccType: Enum "Gen. Journal Account Type"; BalAccNo: Code[20])
var
    GLEntry: Record "G/L Entry";
begin
    OnBeforeCreateGLEntryBalAcc(GenJnlLine, AccNo, Amount, AmountAddCurr, BalAccType, BalAccNo);

    InitGLEntry(GenJnlLine, GLEntry, AccNo, Amount, AmountAddCurr, true, true);
    GLEntry."Bal. Account Type" := BalAccType;
    GLEntry."Bal. Account No." := BalAccNo;
    InsertGLEntry(GenJnlLine, GLEntry, true);
    OnMoveGenJournalLine(GenJnlLine, GLEntry.RecordId);
    //
    OnAfterInsertGLEntryBalAcc(GenJnlLine);
   //
end;
```

```
[IntegrationEvent(**TRUE**, false)]
local procedure OnAfterInsertGLEntryBalAcc(GenJnlLine : Record "Gen. Journal Line");
begin
end;
```

### Additional context

I'd like to add this event to be able to change logic that for my specific business
Internal work item: [AB#555764](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555764)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26401.
