### ISSUE TITLE
[Event Request/Request for External] CU 99000809

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#2749]
Hi,

I requested 3 Events in #1227 . Now in 14.1 i can only see the first Event. We would need the other 2 event aswell.

Function Calculate (handler pattern)
https://user-images.githubusercontent.com/41729653/52715899-e3384f00-2f9d-11e9-972b-19291ec77ee8.png
parameter:
VAR ReqLine : Record "Requisition Line"
PlanningResiliency : Boolean
VAR IsHandled : Boolean

Function Calculate (handler pattern)
https://user-images.githubusercontent.com/41729653/52716045-301c2580-2f9e-11e9-9899-d16a592a3a49.png
parameters:
VAR ReqLine : Record "Requisition Line"
VAR SKU : Record "Stockkeeping Unit"
PlanningResiliency : Boolean
VAR IsHandled : Boolean

Additionally we need Function CheckMultiLevelStructure to be global/external

Thanks in advance

**Comment by AlexanderYakunin** [comment]
Please check again. All events are available, first one in function TransferRouting, second one is called OnCalculateOnBeforeTransferBOM(ReqLine,SKU,PlanningResiliency,IsHandled);

**Comment by AlexanderYakunin** [comment]
The only remaining thing is to make CheckMultiLevelStructure to be global/external.
