### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line".UnapplyVendLedgEntry- OnUnapplyVendLedgEntryOnAfterCreateGLEntriesForTotalAmounts

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27494]
### Describe the request

Please include Sender for this event:

```
[IntegrationEvent(**TRUE**, false)]
local procedure OnUnapplyVendLedgEntryOnAfterCreateGLEntriesForTotalAmounts(var GenJournalLine: Record "Gen. Journal Line"; DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry"; GLReg: Record "G/L Register")
begin
end;
```

### Additional context

I need to continue the logic with current context of codeunit "Gen. Jnl.-Post Line"
Internal work item: [AB#555760](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555760)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26401.
