### ISSUE TITLE
[Event Request] Page 52 "Purchase Credit Memo"

### ISSUE THREAD

**Issue by Martinezrm98** [microsoft/ALAppExtensions#27502]
### Describe the request

Dear ALAppExtensions Team,
Please add the following Event to procedure PostDocument in Page 52 "Purchase Credit Memo": 

```
IsScheduledPosting := Rec."Job Queue Status" = Rec."Job Queue Status"::"Scheduled for Posting";
DocumentIsPosted := (not PurchaseHeader.Get(Rec."Document Type", Rec."No.")) or IsScheduledPosting;
//new event:
OnPostOnAfterSetDocumentIsPosted(PurchaseHeader, IsScheduledPosting, DocumentIsPosted);

if IsScheduledPosting then
    CurrPage.Close();
CurrPage.Update(false);

...

[IntegrationEvent(false, false)]
local procedure OnPostOnAfterSetDocumentIsPosted(PurchaseHeader: Record "Purchase Header"; var IsScheduledPosting: Boolean; var DocumentIsPosted: Boolean)
begin
end;
```

### Additional context

We need the access to the IsScheduledPosting variable at this point
Internal work item: [AB#555751](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555751)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
