### ISSUE TITLE
[Bug]: Modifying VAT Statement Report Line on DE version of BC

### ISSUE THREAD

**Issue by iCutura** [microsoft/ALAppExtensions#27500]
### Describe the issue

There is an issue in the DE version of the BC (maybe on other version as well).

In table 742 "VAT Statement Report Line" there is an onModify trigger which has this line:

_**VATReportHeader.Get("VAT Report Config. Code", "VAT Report No.");**_

On DE version of the app table 740 "VAT Report Header" has this primary key:

**_key(Key1; "No.")_**

W1 version has this primary key:

**_key(Key1; "VAT Report Config. Code", "No.")_**

### Expected behavior

There should not be an error when modifying VAT Statement Report Line.

### Steps to reproduce

Modify VAT Statement Report Line.

### I will provide a fix for a bug

- [x] I will provide a fix for a bug
Internal work item: [AB#556661](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556661)

**Comment by JesperSchulz** [comment]
Unfortunately we do not support contributions for local versions yet 😟 I will create a bug to get your issue inspected.

**Comment by JesperSchulz** [comment]
Bug has been created. Closing issue.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27186.

**Comment by iCutura** [comment]
Hi @JesperSchulz thanks for the information.

Is it possibble for these changes to be implemented in BC24 version?

**Comment by JesperSchulz** [comment]
> Hi [@JesperSchulz](https://github.com/JesperSchulz) thanks for the information.
> 
> Is it possibble for these changes to be implemented in BC24 version?

Sure, consider it done!

**Comment by iCutura** [comment]
Thanks a lot. Let me know when it's done and which version can I use to upgrade our client.

**Comment by JesperSchulz** [comment]
> Thanks a lot. Let me know when it's done and which version can I use to upgrade our client.

Done. PR was merged into 24.8.27868.0. Changes will ship with 24.9.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 27868.
