### ISSUE TITLE
Expose SustainabilityAccount table using a v2 Page API

### ISSUE THREAD

**Issue by arvind1234** [microsoft/ALAppExtensions#27508]
### Describe the request

Add a v2 Page API to expose SustainabilityAccount table

### Additional context

This is required to read the Total emissions data from Business central

**Comment by onbuyuka** [comment]
We already have this https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/Sustainability/app/src/APIs/SustainabilityAccounts.Page.al
