### ISSUE TITLE
Table 232 Gen. Journal Batch - Integration events not working in AL anymore

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#2750]
Integration events OnCheckGenJournalLineExportRestrictions and OnMoveGenJournalBatch from Table 232 Gen. Journal Batch cannot be used for extension development anymore.

Calls like GenJnlBatch.OnMoveGenJournalBatch and GenJournalBatch.OnCheckGenJournalLineExportRestrictions are not working anymore.

Can you make them available externally again?

New version:
 - AL version: 3.0.124247
 - Image: mcr.microsoft.com/businesscentral/sandbox:14.1.32615.0-ca-ltsc2019

![image](https://user-images.githubusercontent.com/40229810/59056666-006c9280-8899-11e9-9859-e79ac8220779.png)

Previous version:
 - AL Version: 2.1.106653
 - Image: microsoft/bcsandbox:13.5.29614.0-ca-ltsc2019

![image](https://user-images.githubusercontent.com/40229810/59056831-57726780-8899-11e9-9ebe-46c70504c001.png)

Also, in both versions properties window in C-Side for functions is not showing properties correctly. As you can see even though property Local is set to No, I cannot see FunctionVisibility property:

![image](https://user-images.githubusercontent.com/40229810/59057092-e67f7f80-8899-11e9-9560-fe78c7f7fb65.png)

I can see it once I switch Local property to Yes which is absurd, since this property should be visible when Local is set to No:

![image](https://user-images.githubusercontent.com/40229810/59057181-2181b300-889a-11e9-99f3-ac015933469b.png)

**Comment by RomanZanizdra** [comment]
Hi zulezmaj. No, these events will not be public because this wrong. This is also wrong design usage of them. It can be reworked in upcoming release.

**Comment by RomanZanizdra** [comment]
I'll close issue for now. Feel free to reopen it if any questions.

**Comment by zulezmaj** [comment]
Hi @RomanZanizdra, but why would there be publishers in table which you cannot access from AL?
