### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnBeforeSendToPostWithLines

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27514]
### Describe the request

Can you add event OnBeforeSendToPostWithLines in procedure SendToPostWithLines?
Just like similar procedures for sales and purchase.

```
    procedure SendToPostWithLines(CodeunitId: Integer; var TempServLine: Record "Service Line" temporary) IsSuccess: Boolean
    var
        ErrorContextElement: Codeunit "Error Context Element";
        ErrorMessageMgt: Codeunit "Error Message Management";
        ErrorMessageHandler: Codeunit "Error Message Handler";
        ServPostYesNo: Codeunit "Service-Post (Yes/No)";
        // >>>>>>>>>>
        IsHandled: Boolean;
        // <<<<<<<<<<
    begin
        // >>>>>>>>>>
        IsHandled := false;
        OnBeforeSendToPostWithLines(Rec, IsSuccess, IsHandled, CodeunitId, TempServLine);
        if IsHandled then
            exit(IsSuccess);
        // <<<<<<<<<<

        Commit();
        ErrorMessageMgt.Activate(ErrorMessageHandler);
        ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, '');

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSendToPostWithLines(var ServiceHeader: Record "Service Header"; var IsSuccess: Boolean; var IsHandled: Boolean; PostingCodeunitID: Integer; var TempServLine: Record "Service Line" temporary)
    begin
    end;  
```

### Additional context

I'm to add a similar customization as I have done for sales and service.
Internal work item: [AB#555738](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555738)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
