### ISSUE TITLE
[Event Request] codeunit 5760 "Whse.-Post Receipt" - Add publisher 'OnBeforeModifyLineInUpdateAttachedLine'

### ISSUE THREAD

**Issue by someC0d3r** [microsoft/ALAppExtensions#27513]
### Describe the request

![Image](https://github.com/user-attachments/assets/f374f4d1-2210-496f-b2dd-727f54383223)

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeModifyLineInUpdateAttachedLine(var SalesLine: Record "Sales Line"; var WarehouseReceiptLine: Record "Warehouse Receipt Line"; var ModifyLine: Boolean; var QtyToHandle: Decimal)
begin
end;
```

### Additional context

Publisher can be used to make modifications to the "Attached/Assigned" (field: SalesReceivablesSetup."Auto Post Non-Invt. via Whse.") logic.
Internal work item: [AB#555746](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555746)

**Comment by alexei-dobriansky** [comment]
@someC0d3r Any chance you could share a hint on what changes they have in mind?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
