### ISSUE TITLE
[Event Change Request] Codeunit 826 "Purch. Post Invoice Events" - RunOnCalculateVATAmountsOnAfterGetReverseChargeVATPostingSetup

### ISSUE THREAD

**Issue by tekoWeMa** [microsoft/ALAppExtensions#27515]
### Describe the request

Hello, could you please add the Parameter "TempInvoicePostBuffer" to the Procedure RunOnCalculateVATAmountsOnAfterGetReverseChargeVATPostingSetup in Codeunit 816 "Purch. Post Invoice" and to the Event OnCalculateVATAmountsOnAfterGetReverseChargeVATPostingSetup in the Codeunit 826 "Purch. Post Invoice Events"

```
procedure RunOnCalculateVATAmountsOnAfterGetReverseChargeVATPostingSetup(var VATPostingSetup: Record "VAT Posting Setup")
    begin
        OnCalculateVATAmountsOnAfterGetReverseChargeVATPostingSetup(VATPostingSetup);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCalculateVATAmountsOnAfterGetReverseChargeVATPostingSetup(var VATPostingSetup: Record "VAT Posting Setup")
    begin
    end;
```

Eventsubscriber in "Old" Purch. Post Codeunit:

```
#if not CLEAN23
    [Obsolete('Moved to Purchase Invoice Posting implementation. Use the new event OnCalculateVATAmountsOnAfterGetReverseChargeVATPostingSetup in codeunit 826 "Purch. Post Invoice Events".', '20.0')]
    [IntegrationEvent(false, false)]
    local procedure OnPostInvoicePostingBufferOnAfterVATPostingSetupGet(var VATPostingSetup: Record "VAT Posting Setup"; var TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; var IsHandled: Boolean)
    begin
    end;
#endif
```

### Additional context

This was already the Case in the Old Purch.- Post Codeunit.
We would like to change the Vat% in the Posting buffer to change the Reverse charge VAT for Swiss Billing to abroad companies.
Internal work item: [AB#555755](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555755)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26491.
