### ISSUE TITLE
[Event Request] codeunit 5746 "Sales Whse. Post Shipment" - Add publisher 'OnBeforeUpdateAttachedLine'

### ISSUE THREAD

**Issue by someC0d3r** [microsoft/ALAppExtensions#27510]
### Describe the request

![Image](https://github.com/user-attachments/assets/4d3c8ecd-04e4-4237-84a2-522d732ca873)

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateAttachedLine(var SalesLine: Record "Sales Line"; var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var ModifyLine: Boolean; var IsHandled: Boolean)
begin
end;
```

### Additional context

Publisher can be used to make modifications to the "Attached/Assigned" (field: SalesReceivablesSetup."Auto Post Non-Invt. via Whse.") logic.
Internal work item: [AB#555743](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555743)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
