### ISSUE TITLE
[Event Request] codeunit 4810 IntrastatReportManagement - OnAfterCalculateNetweight

### ISSUE THREAD

**Issue by EdwinR21** [microsoft/ALAppExtensions#27516]
### Describe the request

Can you please add the following event in codeunit 4810 IntrastatReportManagement in the procedure RecalculateWaightAndSupplUOMQty:
![Image](https://github.com/user-attachments/assets/de32bc32-288d-480b-bf2a-ed68f75bf6a1)

![Image](https://github.com/user-attachments/assets/7f3e8f45-209a-409d-acaf-8cc71307fde3)

### Additional context

Our customers in the Fashion can have a different Net Weight per Variant Code. When you choose "Suggest Lines" in the Intrastat Report there is an event we can interfere, so that Net Weight is taken from the Variant Code (we added variant code in the Intrastat Report Line), but when choosing "Recalc. Weight/Suppl. UOM" there is no event we can interfere to get net weight from the variant code and that is why we need the event described above.
Internal work item: [AB#555739](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555739)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27498.
