### ISSUE TITLE
[Event Request] codeunit 5760 "Whse.-Post Receipt" - Add publisher 'OnBeforeUpdateAttachedLine'

### ISSUE THREAD

**Issue by someC0d3r** [microsoft/ALAppExtensions#27512]
### Describe the request

![Image](https://github.com/user-attachments/assets/ab5baeb3-6ea8-4de1-8bf6-82482dfefa42)

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateAttachedLine(var SalesLine: Record "Sales Line"; var WarehouseReceiptLine: Record "Warehouse Receipt Line"; var ModifyLine: Boolean; var IsHandled: Boolean)
begin
end;

### Additional context

Publisher can be used to make modifications to the "Attached/Assigned" (field: SalesReceivablesSetup."Auto Post Non-Invt. via Whse.") logic.
Internal work item: [AB#555744](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555744)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
