### ISSUE TITLE
[var Request] Codeunit 90 "Purch.-Post" - ArchiveUnpostedOrder #14412

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#27522]
### Describe the request

Related to #14412

In #14412, the ArchiveUnpostedOrder function has been modified to allow **SalesHeader** to be passed by **var**.
This allows functions in the ArchiveManagement receiving SalesHeader  as var parameter, to modify the SalesHeader record, without impacting the posting routine. (OK)

We would like to see same behavior in the **"Purch.-Post"** codeunit. The ArchiveUnpostedOrder function should be modified to allow **PurchHeader** to be passed **by** var as well. There's tens of subscribers with var PurchHeader, allowing to modify the PurchHeader in the posting routine, but only the ArchiveUnpostedOrder prevents from doing so. (NOK)

![Image](https://github.com/user-attachments/assets/644a39fd-87e8-49ac-b2e4-38b2b47b0788)

Old code

` procedure ArchiveUnpostedOrder(PurchHeader: Record "Purchase Header")`

New code

` procedure ArchiveUnpostedOrder(var PurchHeader: Record "Purchase Header")`

Can you please include the change in a next BC **25** minor update.

### Additional context

(Simplified) scenario:
- When creating a **sales** order, the user can assign a version number to it. Archiving the sales order takes this version number and store it on the archived order.
- When a new archived order is created via different paths, the version on the archived order is increased, and the sales order is to be updated accordingly with the latest version number.
- When posting a sales shipment, an archived order is created (increasing the version) and the sales order is updated accordingly (as part of the ArchiveUnpostedOrder logic in the sales - posting routine, since SalesHeader gets passed by var) - all OK

Failing scenario:
- When creating a **purchase** order, the user can assign a version number to it. Archiving the purchase order takes this version number and store it on the archived order.
- When a new archived order is created via different paths, the version on the archived order is increased, and the purchase order is to be updated accordingly with the latest version number.
- When posting a purchase receipt, an archived order is created (increasing the version) and the purchase order **NOT** is updated accordingly (since the ArchiveUnpostedOrder logic in the purchase posting routine, since PurchHeader is not passed by var) - NOK
Internal work item: [AB#555740](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555740)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28358.
