### ISSUE TITLE
Page : "Posted Service Shpt. - Update" - Procedure RecordChanged

### ISSUE THREAD

**Issue by alessandrowolf87** [microsoft/ALAppExtensions#27533]
### Describe the request

Hi,
can you please add a new event in the procedure RecordChanged of "Posted Service Shpt. - Update" page

//>New Event
OnAfterRecordChanged(Rec, xServiceShptHeader, IsChanged);
//<New Event

//>Old Procedure

local procedure RecordChanged(): Boolean
    begin
        exit(
          (Rec."Additional Information" <> xServiceShptHeader."Additional Information") or
          (Rec."Additional Notes" <> xServiceShptHeader."Additional Notes") or
          (Rec."Additional Instructions" <> xServiceShptHeader."Additional Instructions") or
          (Rec."TDD Prepared By" <> xServiceShptHeader."TDD Prepared By") or
          (Rec."Shipment Method Code" <> xServiceShptHeader."Shipment Method Code") or
          (Rec."Shipping Agent Code" <> xServiceShptHeader."Shipping Agent Code") or
          (Rec."3rd Party Loader Type" <> xServiceShptHeader."3rd Party Loader Type") or
          (Rec."3rd Party Loader No." <> xServiceShptHeader."3rd Party Loader No."));
    end;

//<Old Procedure

//>New Procedure

local procedure RecordChanged(): Boolean
    begin
        IsChanged :=
          (Rec."Additional Information" <> xServiceShptHeader."Additional Information") or
          (Rec."Additional Notes" <> xServiceShptHeader."Additional Notes") or
          (Rec."Additional Instructions" <> xServiceShptHeader."Additional Instructions") or
          (Rec."TDD Prepared By" <> xServiceShptHeader."TDD Prepared By") or
          (Rec."Shipment Method Code" <> xServiceShptHeader."Shipment Method Code") or
          (Rec."Shipping Agent Code" <> xServiceShptHeader."Shipping Agent Code") or
          (Rec."3rd Party Loader Type" <> xServiceShptHeader."3rd Party Loader Type") or
          (Rec."3rd Party Loader No." <> xServiceShptHeader."3rd Party Loader No."));

           OnAfterRecordChanged(Rec, xServiceShptHeader, IsChanged);
    end;

//<New Procedure

### Additional context

Because there are others fields that I can edit in a posted service shipment, but I can't manage them
Internal work item: [AB#556056](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556056)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
