### ISSUE TITLE
[Event Request] table 5841 "Standard Cost Worksheet" - OnBeforeGetResCosts

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#27531]
### Describe the request

    local procedure GetResCosts()
    begin
        OnBeforeGetResCosts(Rec, Res);

        "Standard Cost" := Res."Unit Cost";
        "New Standard Cost" := Res."Unit Cost";
        "Overhead Rate" := 0;
        "New Overhead Rate" := 0;
        "Indirect Cost %" := Res."Indirect Cost %";
        "New Indirect Cost %" := Res."Indirect Cost %";
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetResCosts(var StandardCostWorksheet: Record "Standard Cost Worksheet"; var Resource: Record Resource)
    begin
    end;

### Additional context

All the other OnBefore Type events exist (Item/Work- and Machine Center) but why not the one also for silly old Resource. The most underappreciated table.
Internal work item: [AB#555730](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/555730)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25981.
