### ISSUE TITLE
Get Source of Tenant Media Table

### ISSUE THREAD

**Issue by Kenozakesy** [microsoft/ALAppExtensions#27534]
### Describe the request

Hallo,

We currently have a tenant media table that has a total size of ~78 Gigabyte. We would like to now were this data is coming from.
We created a solution for this in which we went through every field were the field type was either media or mediaset.

however we only get ~46 gigabytes back in our calculation. 
At this point we have tried many options. Like finding the orphans of these 2 tables among other things.

What I would like to know whether or not it is possible to use the Media Id of a record in the table tenant media to find the record it is used in. (E.g. an image on a item) as far as I know this is not possible.

Any other suggestions or tips are welcome

### Additional context

N/A

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/forums/thread/?groupid=e78817ab-a926-4d31-96cc-aef040a4eb04)
[mibuso forum](https://forum.mibuso.com/)
[Viva Engage](https://www.yammer.com/dynamicsnavdev)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.

**Comment by JesperSchulz** [comment]
If you're running out of DB space, this would also warrant a support case of course. With a support case, we could look into the specifics of your environment and help you. Without access to your environment, it's hard to guess.
