### ISSUE TITLE
[Bug]: Shopify Connector : Cannot sync catalog price from BC to Shopify for catalog larger than 100 products

### ISSUE THREAD

**Issue by glachana** [microsoft/ALAppExtensions#27535]
### Describe the issue

When users try to synchronize prices through the action available on Shopify Catalogs page. Only the 100 first prices are synchronized. So if the Shopify Catalog contains more than 100 product, only 100 of them will be updated.

This problem results from a difference between two GraphQL requests made during this process: 

> **1) codeunit 30296 "Shpfy GQL CatalogPrices"**
> '{"query": "query { catalog(id: \"gid://shopify/Catalog/{{CatalogId}}\") { id priceList {id currency prices(first:100) {edges {cursor node {variant {id product {id}} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'
> 
> **2) codeunit 30297 "Shpfy GQL NextCatalogPrices"**
> '{"query": "query { catalog(id: \"gid://shopify/Catalog/{{CatalogId}}\") { id priceList {id prices(first:100, after:\"{{After}}\") {edges {cursor node {variant {id} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'

Some necessary nodes are missing in NextCatalogPrices. Here is a fixed request : 

> '{"query": "query { catalog(id: \"gid://shopify/Catalog/{{CatalogId}}\") { id priceList {id **_currency_** prices(first:100, after:\"{{After}}\") {edges {cursor node {variant {id **_product {id}_**} price {amount} compareAtPrice {amount}}} pageInfo {hasNextPage}}}}}"}'

Indeed, the lack of node variant.product.id node in Shopify's response does not allow the connector to work properly, since this json node is used in the codeunit 30290 "Shpfy Catalog API"

![Image](https://github.com/user-attachments/assets/decf947f-9b19-4139-b12d-c83479247706)

### Expected behavior

Being able to sync prices for catalogs with more than 100 products. 

### Steps to reproduce

1. Setup Shopify connector to sync catalogs
2. Go to page Shpfy Catalogs (30159, List)
3. Use action Get Catalog
4. Check Sync Prices on a record related to a Shopify Catalog with more than 100 products / prices
5. Use action Sync Prices

### Additional context

Issue found in version 24.5.23489.24156 and 25.0.23364.25445 of Shopify Connector
It would be great if a patch could be released for Business Central Saas 24.5.

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Confirmed. That's a bug. Approved.
