### ISSUE TITLE
add OnBeforeUpdateLines event to "VAT Amount Line".UpdateLines procedure

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#27536]
### Describe the request

Hello, could you please add OnBeforeUpdateLines event to "VAT Amount Line "table, with all parameters from UpdateLines procedure + IsHandled parameter + IncludeSender attribute?  Like here:

```
    procedure UpdateLines(var TotalVATAmount: Decimal; Currency: Record Currency; CurrencyFactor: Decimal; PricesIncludingVAT: Boolean; VATBaseDiscountPercHeader: Decimal; TaxAreaCode: Code[20]; TaxLiable: Boolean; PostingDate: Date)
    var
        PrevVATAmountLine: Record "VAT Amount Line";
        SalesTaxCalculate: Codeunit "Sales Tax Calculate";
        VATBaseDiscountPerc: Decimal;
        IsHandled: Boolean;  // << New Variable
    begin
        // New Code >>
        IsHandled := false;
        OnBeforeUpdateLines(TotalVATAmount, Currency, CurrencyFactor, PricesIncludingVAT, VATBaseDiscountPercHeader, TaxAreaCode, TaxLiable, PostingDate, IsHandled);
        if IsHandled then
            exit;
        // New Code << 
        if FindSet() then
            repeat ..


// New Event >>
    [IntegrationEvent(true, false)]
    procedure OnBeforeUpdateLines(var TotalVATAmount: Decimal; Currency: Record Currency; CurrencyFactor: Decimal; PricesIncludingVAT: Boolean; VATBaseDiscountPercHeader: Decimal; TaxAreaCode: Code[20]; TaxLiable: Boolean; PostingDate: Date; var IsHandled: Boolean)
    begin
    end;
 // New Event <<
```

### Additional context

VATAmountLine.UpdateLines procedure already has 10 events, but for our PTE scenario at least two more events are required. I think it would be better to add an "IsHandled" event with all parameters from the UpdateLines procedure and the IncludeSender attribute, which should cover all possible extensibility scenarios.
Internal work item: [AB#556049](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556049)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26491.
