### ISSUE TITLE
[Event Request] Audit Mapping Helper OnBeforeGetGLAccountForMapping

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#27538]
### Describe the request

Need and event OnBeforeGetGLAccountForMapping at before procedute GetGLAccountForMapping

`[IntegrationEvent(false, false)]`
`local procedure OnBeforeGetGLAccountForMapping(var GLAccount: Record "G/L Account")`
`begin`
`end;`

### Additional context

This event need to exclude some GL Accounts From mapping
Internal work item: [AB#556048](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556048)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26491.
