### ISSUE TITLE
codeunit 32000000 "Ref. Payment Management" needs event to handle increment value of line numbers.

### ISSUE THREAD

**Issue by Jupentti1** [microsoft/ALAppExtensions#27537]
### Describe the request

    procedure SetLines(RefPaymentImported: Record "Ref. Payment - Imported"; JnlBatchName: Code[20]; JnlTemplateName: Code[20])
    var
        LineNoIncrement: Integer;
    begin
        LineNoIncrement := 10000;
        GLSetup.Get();
        GenJnlTemplate.Get(JnlTemplateName);
        GenJnlLine.Reset();
        GenJnlLine.SetCurrentKey("Journal Template Name", "Journal Batch Name", "Line No.");
        GenJnlLine.SetFilter("Journal Template Name", JnlTemplateName);
        GenJnlLine.SetFilter("Journal Batch Name", JnlBatchName);
        if GenJnlLine.FindLast() then begin
            LastDocNro := IncStr(GenJnlLine."Document No.")
        end else
            GetNroSeries(JnlBatchName, JnlTemplateName);
        OnBeforeSetLineNo(LineNoIncrement, GenJnlLine);
        LineNro := GenJnlLine."Line No." + LineNoIncrement;

        RefPaymentImported.Ascending(true);
        RefPaymentImported.SetRange("Posted to G/L", false);
        RefPaymentImported.SetRange(Matched, true);
        RefPaymentImported.SetFilter("Entry No.", '<>%1', 0);
        CustLedgEntry.Reset();
        if RefPaymentImported.FindSet() then
            repeat
                BankAcc.SetRange("No.", RefPaymentImported."Bank Account Code");
                if BankAcc.FindFirst() then
                    AccCode := BankAcc."No."
                else
                    AccCode := '';
                CustLedgEntry.SetRange("Entry No.", RefPaymentImported."Entry No.");
                GenJnlLine.Reset();
                GenJnlLine.SetCurrentKey("Journal Template Name", "Journal Batch Name", "Applies-to Doc. No.", "Reference No.");
                GenJnlLine.SetRange("Journal Template Name", JnlTemplateName);
                GenJnlLine.SetRange("Journal Batch Name", JnlBatchName);
                GenJnlLine.SetRange("Applies-to Doc. No.", RefPaymentImported."Document No.");
                GenJnlLine.SetRange("Reference No.", RefPaymentImported."Reference No.");
                GenJnlLine.SetRange(Comment, RefPaymentImported."Filing Code");
                RefPmtImportTemp.SetRange("Account No.", RefPaymentImported."Account No.");
                RefPmtImportTemp.SetRange("Filing Code", RefPaymentImported."Filing Code");
                if (CustLedgEntry.FindFirst() or (not RefPmtImportTemp.FindFirst())) and (not GenJnlLine.FindFirst()) then begin
                    GenJnlLine.Init();
                    GenJnlLine."Journal Template Name" := JnlTemplateName;
                    GenJnlLine.Validate("Journal Batch Name", JnlBatchName);
                    GenJnlLine."Line No." := LineNro;
                    GenJnlLine.Validate("Posting Date", RefPaymentImported."Banks Posting Date");
                    GenJnlLine.Validate("Account Type", 1);
                    GenJnlLine.Validate("Account No.", CustLedgEntry."Customer No.");
                    GenJnlLine.Validate("Document Type", 1);
                    GenJnlLine.Validate("Applies-to Doc. Type", 2);
                    GenJnlLine."Applies-to Doc. No." := CustLedgEntry."Document No.";
                    GenJnlLine."Document No." := LastDocNro;
                    GenJnlLine.Validate("Bal. Account Type", 3);
                    GenJnlLine."Reference No." := RefPaymentImported."Reference No.";
                    GenJnlLine."Source Code" := GenJnlTemplate."Source Code";
                    GenJnlLine.Validate("Currency Code", CustLedgEntry."Currency Code");
                    GenJnlLine.Validate(Amount, RefPaymentImported.Amount * -1);
                    GenJnlLine.Comment := RefPaymentImported."Filing Code";
                    GenJnlLine.Validate("Bal. Account No.", GetBalAccountNo(GenJnlLine, AccCode, CustLedgEntry));
                    OnSetLinesOnBeforeGenJnlLineInsert(CustLedgEntry, GenJnlLine);
                    GenJnlLine.Insert(true);
                    LineNro += LineNoIncrement;
                    LastDocNro := IncStr(LastDocNro);
                end;
            until RefPaymentImported.Next() = 0;
    end;

    [Scope('OnPrem')]
    procedure GetNroSeries(JnlBatchName: Code[20]; JnlTemplateName: Code[20])
    begin
        GenJnlBatch.SetFilter("Journal Template Name", JnlTemplateName);
        GenJnlBatch.SetFilter(Name, JnlBatchName);
        if GenJnlBatch.FindFirst() then
            LastDocNro := NoSeriesBatch.GetNextNo(GenJnlBatch."No. Series");
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetLineNo(var LineNoIncrement: Integer,var GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

### Additional context

Codeunit 32000000 "Ref. Payment Management" has procedure SetLines that will generate Gen. Journal Lines according to Ref. Payment Imported table. 
Now as we have big imported Ref. Payment files the LineNro integer variable will be maxed out after 2147 records. 

We need to handle what is the incremental value of LineNro and therefore we need an event to handle the LineNro increment value and small change with variable to set incremental value instead of the hard coded 10000. 
Please add this to code to make it more flexible.
Internal work item: [AB#556050](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556050)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.
