### ISSUE TITLE
[Event Request] Codeunit 6762 "Reminder - Send" - OnBeforeGetDocumentSendingProfile

### ISSUE THREAD

**Issue by ghulammustafa-d360** [microsoft/ALAppExtensions#27543]
### Describe the request

     local procedure GetDocumentSendingProfile(var IssuedReminderHeader: Record "Issued Reminder Header"; var DocumentSendingProfile: 
     Record "Document Sending Profile") DocumentSendingProfileFound:Boolean
     var
          DefaultDocumentSendingProfile: Record "Document Sending Profile";
          Customer: Record Customer;
          IsHandled: Boolean;

     begin
        OnBeforeGetDocumentSendingProfile(IssuedReminderHeader, DocumentSendingProfile, DocumentSendingProfileFound ,IsHandled);
        if IsHandled then
           exit;
        Clear(DocumentSendingProfile);
        Customer.Get(IssuedReminderHeader."Customer No.");

        if Customer."Document Sending Profile" <> '' then
            if DocumentSendingProfile.Get(Customer."Document Sending Profile") then
                exit(true);

        DefaultDocumentSendingProfile.SetRange(Default, true);
        if not DefaultDocumentSendingProfile.FindFirst() then
            exit(false);

        exit(DocumentSendingProfile.GetBySystemId(DefaultDocumentSendingProfile.SystemId));
     end;

     [IntegrationEvent(false, false)]
     local procedure OnBeforeGetDocumentSendingProfile(var IssuedReminderHeader: Record "Issued Reminder Header"; var DocumentSendingProfile: 
     Record "Document Sending Profile"; var DocumentSendingProfileFound; var IsHandled: Boolean)
     begin
     end;

### Additional context

The reason why we need it, is that we provide the option to have a different Document Sending Profile for Reminders. We want an OnBefore Event "OnBeforeGetDocumentSendingProfile", include all Parameters + IsHandled so that we can handle it.
Internal work item: [AB#556051](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556051)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26491.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26724.
