### ISSUE TITLE
[Event Request] codeunit 7110 "Analysis Report Management" - OnBeforeCalcSalesAmount

### ISSUE THREAD

**Issue by angelocitro** [microsoft/ALAppExtensions#27558]
### Describe the request

Could you please add the event OnBeforeCalcSalesAmount in codeunit 7110 "Analysis Report Management"?

```
 local procedure CalcSalesAmount(var ItemStatisticsBuf: Record "Item Statistics Buffer"; Invoiced: Boolean): Decimal
var IsHandled: Boolean
      Result: Decimal;    
begin
       OnBeforeCalcSalesAmount(ItemStatisticsBuf, Invoiced, IsHandled, Result);
       if IsHandled then
         exit(Result);
[...]
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeCalcSalesAmount(var ItemStatisticsBuf: Record "Item Statistics Buffer"; Invoiced: Boolean; var IsHandled: Boolean, var Result: Boolean)
begin 
end;
```

### Additional context

I would like to calculate the "Sales Amount (Actual)" filtering the Value Entry with "Reason Code"
Internal work item: [AB#556645](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556645)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26527.
