### ISSUE TITLE
Table 36 Sales Header procedure CreateDimFromDefaultDim

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#27551]
### Describe the request

Please add OnBeforeCreateDimFromDefaultDim(..) in CreateDimFromDefaultDim. 
Details below.

```
    procedure CreateDimFromDefaultDim(FieldNo: Integer)
    var
        DefaultDimSource: List of [Dictionary of [Integer, Code[20]]];
        IsHandled: Boolean;
    begin
        OnBeforeCreateDimFromDefaultDim(Rec, FieldNo, IsHandled);
        if IsHandled then
            exit;
        InitDefaultDimensionSources(DefaultDimSource, FieldNo);
        CreateDim(DefaultDimSource);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateDimFromDefaultDim(var Rec: Record "Sales Header"; FieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

We want to be able to skip the recreation of default dimensions if the dimension in Sales Header will not be changed by changing the Responsilibity center (for example).
Internal work item: [AB#556641](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556641)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26485.
