### ISSUE TITLE
[Event Request] table 5902 "Service Line"–  OnBeforeValidateLineAmount

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#27557]
### Describe the request

[Event Request] table 5902 "Service Line"???  OnBeforeValidateLineAmount

Could we please have a publisher OnBeforeValidateLineAmount in trigger OnValidate of the field ???Line Amount??? at table 5902 "Service Line"?
```
        field(103; "Line Amount"; Decimal)
        {
            AutoFormatExpression = Rec."Currency Code";
            AutoFormatType = 1;
            CaptionClass = GetCaptionClass(FieldNo("Line Amount"));
            Caption = 'Line Amount';

            trigger OnValidate()
            var
                ServAmountsMgt: Codeunit "Serv-Amounts Mgt.";
                LineDiscountAmountExpected: Decimal;
                // >>>>>>>>
                IsHandled: Boolean;
                // <<<<<<<< 
            begin
               // >>>>>>>>
               IsHandled := false;
               OnBeforeValidateLineAmount(Rec, xRec, CurrFieldNo, IsHandled);
               if IsHandled then
                   exit;
               // <<<<<<<< 

                TestField(Type);
                TestQtyFromLineAmount();
                TestField("Unit Price");
                Currency.Initialize("Currency Code");

 // >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateLineAmount(var ServiceLine: Record "Service Line"; xServiceLine: Record "Service Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
// <<<<<<<< 

```

### Additional context

We want to calculate bundle sums, the new sum must be entered on the bundle line and then the amount is distributed to other lines.
The event is also available for sale in this way.
Internal work item: [AB#556644](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556644)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
