### ISSUE TITLE
[Event Request] Codeunit 99000809 "Planning Line Management" - TransferBOM

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#27560]
To be able to overrule the filter on the field ???Worksheet Line No.??? in table ???Planning Routing Line??? in procedure TransferBOM in codeunit 99000809 ???Planning Line Management???, I want to request an event publisher to be added like this:

**BC Code**
local procedure TransferBOM(ProdBOMNo: Code[20]; Level: Integer; LineQtyPerUOM: Decimal; ItemQtyPerUOM: Decimal)
[...]

            if ProdBOMLine[Level].Find('-') then
                repeat
                    IsHandled := false;
                    OnTransferBOMOnBeforeTransferPlanningComponent(ReqLine, ProdBOMLine[Level], Blocked, IsHandled);
                    if not IsHandled then begin
                        if ProdBOMLine[Level]."Routing Link Code" <> '' then begin
                            PlanningRtngLine2.SetRange("Worksheet Template Name", ReqLine."Worksheet Template Name");
                            PlanningRtngLine2.SetRange("Worksheet Batch Name", ReqLine."Journal Batch Name");
                            PlanningRtngLine2.SetRange("Worksheet Line No.", ReqLine."Line No.");
                            PlanningRtngLine2.SetRange("Routing Link Code", ProdBOMLine[Level]."Routing Link Code");
                            ### OnBeforePlanningRtngLineTransferBOM(PlanningRtngLine2, ProdBOMLine[Level], ReqLine);
                            PlanningRtngLine2.FindFirst();

    [IntegrationEvent(false, false)]
    local procedure OnBeforePlanningRtngLineTransferBOM(var PlanningRoutingLine: Record "Planning Routing Line"; ProductionBOMLine: Record "Production BOM Line"; RequisitionLine: Record "Requisition Line")
    begin
    end;

Internal work item: [AB#556647](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556647)

**Comment by JakovljevicDusan** [comment]
Please use OnTransferBOMOnAfterCalculateReqQty, which is going to be expanded with ReqLine

**Comment by stephanpl** [comment]
Unfortunately, in our situation the PlanningRtngLine2.FindFirst(); will then still fail because there is no planning routing line available for each requisition line.

**Comment by JakovljevicDusan** [comment]
Clear. Ok, adding new publisher.
I guess OnTransferBOMOnBeforeTransferPlanningComponent is too cumbersome to use for this purpose and adding if PlanningRtngLine2.FindFirst() can be risky.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26527.
