### ISSUE TITLE
[Event Request] Table 39 "Purchase Line".GetItemTranslation and [Event Request] Table 37 "Sales Line".GetItemTranslation

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27574]
### Describe the request

We asked for new events that was closed immediately after first comment from your side. There was not space for discussion and you do not communicate on closed issues. It is reason why I create new one.

My comment was:
Hello @JakovljevicDusan,
please reopen issue. I understand that it is small function, but there is big issue. First of all I will copy standard code. It means when you change code Our code will do it its way all time. Big issue is that I can not somehow raise your event. It means that application that need this event for working will work wrong way. This is not good solution. 

Closed issues. 
https://github.com/microsoft/ALAppExtensions/issues/27485
https://github.com/microsoft/ALAppExtensions/issues/27427

### Additional context

We need change get translations.
Internal work item: [AB#556371](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556371)

**Comment by JakovljevicDusan** [comment]
Hi @fridrichovsky,

Please add more details on "Big issue is that I can not somehow raise your event.". Can you share sample code? Or is it because of IsHandled?

**Comment by fridrichovsky** [comment]
Hello @JakovljevicDusan,
Our customer use different logic for language code. So I need change language code for ItemTranslation in their extension/application. So if i use event OnBeforeGetItemTranslation I can do get Item translation my way. So I copy standard code and I use my function PurchHeader.GetTranslationLanguageCode() for get language code and I add my function FillTranslations(); to the end of the function.
```
        GetPurchHeader();
        if ItemTranslation.Get("No.", "Variant Code", PurchHeader.GetTranslationLanguageCode()) then begin
            Description := ItemTranslation.Description;
            "Description 2" := ItemTranslation."Description 2";
            //OnAfterGetItemTranslation(Rec, PurchHeader, ItemTranslation);
        end;
        FillTranslations();
```

Problem is that we have different our module application/extension that subscribing event OnAfterGetItemTranslation. This application does not work properly now because event is not raised when is code running by customer appliaction. I can not add event calling to customer application because events are as local procedures and they can not be raised externally.

**Comment by fridrichovsky** [comment]
It is general question if I can some how raise standard events. Because it happens all time when we use isHandled for some functions where are standard events we would like raise events in our code but for "same" place.

**Comment by JakovljevicDusan** [comment]
Thanks @fridrichovsky
I understand the issue better now. Will get back soon.

**Comment by JakovljevicDusan** [comment]
Hi @fridrichovsky,

We've analyzed the issue. Our advice is still to subscribe to OnBeforeGetItemTranslation with IsHandled := true and to implement/reimplement functionality that is needed. That includes functionality from another app that is not going to be executed because OnAfterGetItemTranslation is not raised.
We are aware this is not the neatest solution and of disadvantages of using IsHandled "pattern" to skip code, but we also don't want to add a lot of event publishers that would not going to be used often.
