### ISSUE TITLE
[Public Access/Event Request] Manufacturing Codeunit Functions

### ISSUE THREAD

**Issue by marknitek** [microsoft/ALAppExtensions#27573]
### Change Access from local to **public** for CheckMakeOrderLine
```
procedure CheckMakeOrderLine(var ProdOrderComp: Record "Prod. Order Component"; var ProdOrderLine: Record "Prod. Order Line"; Direction: Option Forward,Backward; MultiLevel: Boolean; LetDueDateDecrease: Boolean): Boolean
begin
end;
```

### Change Access from local to **public** for ReserveMultiLevelStructure
```
procedure ReserveMultiLevelStructure(var ProdOrderComp2: Record "Prod. Order Component")
begin
end;
``` 

### Modify OnBeforeCalculate Event
Make `DeleteRelations` a `var` Parameter to allow to control if Relations are deleted.
> Consider making `CalcRouting` and `CalcComponents` `var` parameters too (we do not need it currently but it would make sense
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculate(var ItemLedgerEntry: Record "Item Ledger Entry"; var CapacityLedgerEntry: Record "Capacity Ledger Entry"; Direction: Option Forward,Backward; CalcRouting: Boolean; CalcComponents: Boolean; var DeleteRelations: Boolean; LetDueDateDecrease: Boolean; var IsHandled: Boolean; var ProdOrderLine: Record "Prod. Order Line"; var ErrorOccured: Boolean)
    begin
    end;
```

### Additional context

In Order to allow for Custom Logic to explode Prod. Order Lines based on their BOM (Components) we need accassiblity to the functions described above to make a custom `CheckStructure` Function which then can call `CheckMakeOrderLine` and `ReserveMultiLevelStructure` for specific Components.

Additionally we also require some additional internal Vars to be exposed and be modified.

Internal work item: [AB#556658](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556658)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26622.
