### ISSUE TITLE
[Enum Request] Warehouse Activity Header - "Sorting Method"

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/ALAppExtensions#2758]
Hi Everyone,

it would be awesome if you could consider converting the option field ID: 7; "Sorting Method" in table ID: 5766 "Warehouse Activity Header" into an extensible Enumeration.
This would enable us to implement custom sorting methods.

The underlying logic is already extensible via events.

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by AlexCeg** [comment]
Would it be possible to extend the SortPick variable in report 5754 (Create Pick) as well? It is used in the request page and is the default value for the warehouse activity header, when it is created by this report. 

Thank you.
