### ISSUE TITLE
[Event Request] NL Report 11000000 "Get Proposal Entries"

### ISSUE THREAD

**Issue by IesMeulmeester** [microsoft/ALAppExtensions#27585]
### Describe the request

**EventRequest NL Report 11000000 "Get Proposal Entries"**
Add onbefore OnPreDataItem even publishers to set DataItem filters.

**DataItem: ("Cust. Ledger Entry"; "Cust. Ledger Entry")**

_Trigger OnPreDataItem() add event publisher OnBeforePreDataItem_

```
trigger OnPreDataItem()
begin
    OnBeforeOnPreDataItem("Cust. Ledger Entry"); <= NEW EVENT

    if TransactionmodeTable."Account Type" <> TransactionmodeTable."Account Type"::Customer then
        CurrReport.Break();
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnPreDataItem(var CustLedgerEntry: Record "Cust. Ledger Entry")
begin
end;
```

**DataItem: ("Vendor Ledger Entry"; "Vendor Ledger Entry")**

_Trigger OnPreDataItem() add event publisher OnBeforePreDataItem_
```
trigger OnPreDataItem()
begin
    OnBeforeOnPreDataItem("Vendor  Ledger Entry"); <= NEW EVENT

    if TransactionmodeTable."Account Type" <> TransactionmodeTable."Account Type"::Vendor then
        CurrReport.Break();
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnPreDataItem(var VendorLedgerEntry: Record "Vendor Ledger Entry")
begin
end;
```

**DataItem: ("Employee Ledger Entry"; "Employee Ledger Entry")**

_Trigger OnPreDataItem() add event publisher OnBeforePreDataItem_
```
trigger OnPreDataItem()
begin
    OnBeforeOnPreDataItem("Employee Ledger Entry"); <= NEW EVENT

    if TransactionmodeTable."Account Type" <> TransactionmodeTable."Account Type"::Vendor then
        CurrReport.Break();
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnPreDataItem(var EmployeeLedgerEntry: Record  "Employee Ledger Entry")
begin
end;
```

### Additional context

Add events to the OnPreDataItem triggers to set additional filters on the data items
Internal work item: [AB#556655](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556655)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26724.
