### ISSUE TITLE
Codeunit 2678 "Sales Alloc. Acc. Mgt." - Procedure VerifySelectedAllocationAccountNo from internal to global

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#27583]
### Describe the request

Can the procedures please be set from internal to global.

```
codeunit 2678 "Sales Alloc. Acc. Mgt."
procedure VerifySelectedAllocationAccountNo(var SalesLine: Record "Sales Line")
```

Unfortunately, it was only implemented here for purchase.
https://github.com/microsoft/ALAppExtensions/issues/26313

### Additional context

We would like to use this functionality in our document pages.
Internal work item: [AB#556654](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556654)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27005.
