### ISSUE TITLE
Table 36 "Sales Header" - Procedure UpdateSalesOrderLineIfExist from internal to global

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#27584]
### Describe the request

Can the procedure please be set from internal to global.

```
table 36 "Sales Header"
...
procedure UpdateSalesOrderLineIfExist()
```

### Additional context

We would like to use this functionality in our document pages.
Internal work item: [AB#556656](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556656)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
