### ISSUE TITLE
page 5871 "Item Availability by BOM Level" - RefreshPage and IsCalculated

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27588]
### Describe the request

Can you change IsCalculated to protected var and make the procedure RefreshPage protected?

### Additional context

To be able to add my own field that is used later in the calculation, but also need to trigger an update.
Internal work item: [AB#556904](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556904)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
