### ISSUE TITLE
[Event Request] Codeunit 1311 "Activities Mgt." #17668

### ISSUE THREAD

**Issue by PeterSchoenmaker** [microsoft/ALAppExtensions#27593]
### Describe the request

Dear ALAppExtensions team,

On behalve of 4PS I would like to request integration event 'OnBeforeDrillDownNoOfReservedFromStockSalesOrders' to be added to procedure
'DrillDownNoOfReservedFromStockSalesOrders' in codeunit 1311 "Activities Mgt."

    procedure DrillDownNoOfReservedFromStockSalesOrders()
    var
        [SecurityFiltering(SecurityFilter::Filtered)]
        SalesHeader: Record "Sales Header";
    begin
        //**4PS>MS.sn https://github.com/microsoft/ALAppExtensions/issues/XXXXX
        OnBeforeDrillDownNoOfReservedFromStockSalesOrders(SalesHeader);
        //**4PS>MS.EN

        SalesHeader.SetRange("Document Type", SalesHeader."Document Type"::Order);
        if SalesHeader.FindSet() then
            repeat
                if SalesHeader.GetQtyReservedFromStockState() = Enum::"Reservation From Stock"::Full then
                    SalesHeader.Mark(true);
            until SalesHeader.Next() = 0;
        SalesHeader.MarkedOnly(true);
        Page.Run(Page::"Sales Order List", SalesHeader);
    end;

    //**4PS>MS.sn https://github.com/microsoft/ALAppExtensions/issues/XXXXX
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDrillDownNoOfReservedFromStockSalesOrders(var SalesHeader: Record "Sales Header")
    begin
    end;
    //**4PS>MS.en

### Additional context

The main reason is the performance. Customers with lots of sales orders (>30000) this procedure took 30 secs or more.
With the integration event we van filter sales headers first to limit the number of sales orders to be counted.
Internal work item: [AB#556909](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556909)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
