### ISSUE TITLE
[Event Change Request] Table 5080 "To-do" - OnBeforeConfirmReassignmentOpenedNotMeetingToDo

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27599]
### Describe the request

We want to set the salesperson code to the value of the previous to-do with own business logic. Therefore we request to add the xRec to the OnBeforeConfirmReassignmentOpenedNotMeetingToDo Event:

```
local procedure ConfirmReassignmentOpenedNotMeetingToDo()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
//NEW
    OnBeforeConfirmReassignmentOpenedNotMeetingToDo(Rec, xRec, IsHandled);
//NEW
    if IsHandled then
        exit;

[IntegrationEvent(false, false)]
local procedure OnBeforeConfirmReassignmentOpenedNotMeetingToDo(var ToTask: Record "To-do"; xToTask: Record "To-do"; var IsHandled: Boolean)
begin
end;
```

### Additional context

Enables you to access the previous To-do record.
Internal work item: [AB#556994](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556994)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26622.
