### ISSUE TITLE
[Event Request] Codeunit 1311 "Activities Mgt." #17668

### ISSUE THREAD

**Issue by PeterSchoenmaker** [microsoft/ALAppExtensions#27592]
### Describe the request

Dear ALAppExtensions team,

On behalve of 4PS I would like to request integration event 'OnBeforeCalcNoOfReservedFromStockSalesOrders' to be added to procedure 
'CalcNoOfReservedFromStockSalesOrders' in codeunit 1311 "Activities Mgt."

    procedure CalcNoOfReservedFromStockSalesOrders() Number: Integer
    var
        [SecurityFiltering(SecurityFilter::Filtered)]
        SalesHeader: Record "Sales Header";
        ReservationEntry: Record "Reservation Entry";
        IsHandled: Boolean; //**4PS>MS.n https://github.com/microsoft/ALAppExtensions/issues/XXXXX
    begin
        //**4PS>MS.sn https://github.com/microsoft/ALAppExtensions/issues/XXXXX
        OnBeforeCalcNoOfReservedFromStockSalesOrders(SalesHeader, Number, IsHandled);
        if IsHandled then
            exit;
        //**4PS>MS.en            

        Number := 0;

        ======

    //**4PS>MS.sn https://github.com/microsoft/ALAppExtensions/issues/XXXXX
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcNoOfReservedFromStockSalesOrders(var SalesHeader: Record "Sales Header"; var Number: Integer; var IsHandled: Boolean)
    begin
    end;
    //**4PS>MS.en

### Additional context

The main reason is that this new BC23.1 function', a new tile 'Completely reserved from stock' on the activities page, runs too long (sometimes 30 seconds). We have customers with over 30000 sales orders and more lines. Most of them completely handled. 
With this integration event we can limit the number of sales orders by filtering them first before continuing. In a local test (with way less data than the customers) it went from 8 sec to less than 0,2 sec. 
Internal work item: [AB#556908](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556908)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26525.
