### ISSUE TITLE
[Event Change Request] Table 7317 "Warehouse Receipt Line" - OnBeforeValidateQtyToReceive

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27596]
### Describe the request

We want to check if the WarehouseReceiptLine."Qty. to Receive" is changed. Therefore we request to add xRec as a new parameter to the OnBeforeValidateQtyToReceive Event: 

```
trigger OnValidate()
var
    BinContent: Record "Bin Content";
    WMSMgt: Codeunit "WMS Management";
    IsHandled: Boolean;
begin
    IsHandled := false;
//NEW
    OnBeforeValidateQtyToReceive(Rec, xRec, IsHandled, CurrFieldNo);
//NEW
    if not OverReceiptProcessing() then
        if not IsHandled then
            if "Qty. to Receive" > "Qty. Outstanding" then
                Error(Text002, "Qty. Outstanding");

[IntegrationEvent(false, false)]
local procedure OnBeforeValidateQtyToReceive(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; xWarehouseReceiptLine: Record "Warehouse Receipt Line"; var IsHandled: Boolean; CurrentFieldNo: Integer)
begin
end;
```

### Additional context

Allows you to access the previous Warehouse Receipt Line record.
Internal work item: [AB#556995](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556995)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26622.
