### ISSUE TITLE
[Event Request] Table 99000764 "Routing Line" - OnBeforeValidateStandardTaskCode

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27601]
### Describe the request

We want to handle the Standard Task Code validate with own business logic. Therefore we request to add the following event:

```
trigger OnValidate()
var
    StandardTask: Record "Standard Task";
//NEW
    IsHandled: Boolean;
//NEW
begin
//NEW
    IsHandled := false;
    OnBeforeValidateStandardTaskCode(Rec, xRec, IsHandled);
    if IsHandled then
        exit;
//NEW
    if "Standard Task Code" = '' then
        if "Standard Task Code" <> xRec."Standard Task Code" then begin
            DeleteRelations();
            exit;
        end;

[IntegrationEvent(false, false)]
local procedure OnBeforeValidateStandardTaskCode(var RoutingLine: Record "Routing Line"; xRoutingLine: Record "Routing Line"; var IsHandled: Boolean)
begin
end;
```

### Additional context

Allows yo to handle the Standard Task Code field validation.
Internal work item: [AB#557000](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557000)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26622.
