### ISSUE TITLE
[Event Request] Page 5905 "Service Lines" - OnPostOnBeforeInsertTempServiceLine

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27604]
### Describe the request

We want to copy the value of a blob field before posting the service line. Therefore we request to add the following event:

```
trigger OnAction()
var
    ServiceLine: Record "Service Line";
    TempServiceLine: Record "Service Line" temporary;
begin
    Rec.Modify(true);
    CurrPage.SaveRecord();
    CurrPage.SetSelectionFilter(ServiceLine);

    if ServiceLine.FindSet() then
        repeat
            TempServiceLine.Init();
            TempServiceLine := ServiceLine;
//NEW
            OnPostOnBeforeInsertTempServiceLine(ServiceLine, TempServiceLine);
//NEW
            TempServiceLine.Insert();
        until ServiceLine.Next() = 0
    else
        exit;

[IntegrationEvent(false, false)]
local procedure OnPostOnBeforeInsertTempServiceLine(ServiceLine: Record "Service Line"; var TempServiceLine: Record "Service Line" temporary)
begin
end;
```

### Additional context

Allows you to change or copy field vales before posting the service line.
Internal work item: [AB#557002](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557002)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26622.
