### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick" - Function "OnBeforeProcessDoNotFillQtytoHandle" - Add new parameter "IsHandled "

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27602]
### Describe the request

Hello, can you please add the new parameter "IsHandled " to the Event "OnBeforeProcessDoNotFillQtytoHandle" in codeunit 7312 "Create Pick" ?
And can you please a "if" condiciton test after "OnBeforeProcessDoNotFillQtytoHandle" function : 

NOW: 

local procedure ProcessDoNotFillQtytoHandle(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
        OnBeforeProcessDoNotFillQtytoHandle(WarehouseActivityLine, TempWarehouseActivityLine, CreatePickParameters);

        if CreatePickParameters."Do Not Fill Qty. to Handle" then begin
            WarehouseActivityLine."Qty. to Handle" := 0;
            WarehouseActivityLine."Qty. to Handle (Base)" := 0;
            WarehouseActivityLine.Cubage := 0;
            WarehouseActivityLine.Weight := 0;
        end;

        OnAfterProcessDoNotFillQtytoHandle(WarehouseActivityLine, TempWarehouseActivityLine);
    end;

AFTER:

local procedure ProcessDoNotFillQtytoHandle(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
        IsHandled := false;
        OnBeforeProcessDoNotFillQtytoHandle(WarehouseActivityLine, TempWarehouseActivityLine, CreatePickParameters, IsHandled);
         if IsHandled then
            exit;

        if CreatePickParameters."Do Not Fill Qty. to Handle" then begin
            WarehouseActivityLine."Qty. to Handle" := 0;
            WarehouseActivityLine."Qty. to Handle (Base)" := 0;
            WarehouseActivityLine.Cubage := 0;
            WarehouseActivityLine.Weight := 0;
        end;

        OnAfterProcessDoNotFillQtytoHandle(WarehouseActivityLine, TempWarehouseActivityLine);
    end;

### Additional context

We need to set a "IsHandled" variable to not test the "Do Not Fill Qty. to Handle" field in "if" statement.
Internal work item: [AB#556998](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/556998)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26622.
