### ISSUE TITLE
[Event Request] Codeunit 5817 function PostItemJnlLine

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#2760]
Hello Team,

we need a new handle Publisher:

--OLD
CLEAR(ItemJnlLine2);
ItemJnlLine2 := ItemJnlLine;
IF ItemJnlLine2."Job No." <> '' THEN BEGIN

--NEW
HandledL := FALSE;
OnBeforePostItemJnlLine(var ItemJnlLine, var HandledL);
if NOT HandledL then begin
CLEAR(ItemJnlLine2);
ItemJnlLine2 := ItemJnlLine;
IF ItemJnlLine2."Job No." <> '' THEN BEGIN
...
END;
ItemJnlPostLine.RUN(ItemJnlLine);
END;  <<NEW

IF ItemJnlLine2."Job No." <> '' THEN

thanks

**Comment by AlexanderYakunin** [comment]
Please explain why toy need this? I need scenario how you use Job No.

**Comment by ThomasBrendel** [comment]
Hello,

you have on many places the Testfield on Job No. and do different things while working with Job.
Especially while posting.
Because we have an underlying Job Structure and need "normal" behaviour, we have to handle most of your "special"   "if job no. THEN" to go into the normal routine instead of the "special job routine"

In this case you have a structure like this:

if job no then begin
"jobroutine"
..
end else begin
"normal routine"
end;


so we have the "job no" also, but need to do the normal routine only.
Thats why we need a handle publisher to change to the "normal" routine below
