### ISSUE TITLE
[Change Request] codeunit 5760 "Whse.-Post Receipt" - Procedure "PostWhseJnlLine" - Remove local property

### ISSUE THREAD

**Issue by ROUCHY-Yoann** [microsoft/ALAppExtensions#27607]
### Describe the request

Hello, can you please change the procedure "PostWhseJnlLine" from local to global in codeunit 5760 "Whse.-Post Receipt" ?

local procedure PostWhseJnlLine(var PostedWhseRcptHeader: Record "Posted Whse. Receipt Header"; var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var TempWhseSplitSpecification: Record "Tracking Specification" temporary)
begin
end;

TO:

procedure PostWhseJnlLine(var PostedWhseRcptHeader: Record "Posted Whse. Receipt Header"; var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var TempWhseSplitSpecification: Record "Tracking Specification" temporary)
begin
end;

### Additional context

We need to call this function from a new instance of codeunit 5760.
Internal work item: [AB#557549](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557549)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
