### ISSUE TITLE
[Scope Change Request] Local procedure ErrorHelperHeader should be global on Correct Posted Sales Invoice

### ISSUE THREAD

**Issue by rub7** [microsoft/ALAppExtensions#27618]
### Describe the request

In `codeunit 1313 "Correct Posted Purch. Invoice"` exists `procedure ErrorHelperHeader(HeaderErrorType: Enum "Correct Purch. Inv. Error Type"; PurchInvHeader: Record "Purch. Inv. Header")`

On the related codeunit on Sales `codeunit 1303 "Correct Posted Sales Invoice"` this procedure is *local*:
`local procedure ErrorHelperHeader(HeaderErrorType: Enum "Correct Sales Inv. Error Type"; SalesInvoiceHeader: Record "Sales Invoice Header")`

### Additional context

Procedure `ErrorHelperHeader` should be global on `codeunit 1303 "Correct Posted Sales Invoice"`

Internal work item: [AB#557540](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557540)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
