### ISSUE TITLE
[Event Request] codeunit 1005 "Job Calculate Batches" - New Event OnBeforeEndCreateInvoice

### ISSUE THREAD

**Issue by petmoe** [microsoft/ALAppExtensions#27612]
### Describe the request

In codeunit 1005 "Job Calculate Batches", procedure EndCreateInvoice, we would like a new integration event that will allow us to avoid throwing the standard message.
____

   procedure EndCreateInvoice(NoOfInvoices: Integer)
    //>>New Code Begin
    var
        IsHandled: Boolean;
    //<<New Code End
    begin
        //>>New Code Begin
        OnBeforeEndCreateInvoice(NoOfInvoices, IsHandled);
        if IsHandled then
            exit;
        //<<New Code End
        Commit();
        if NoOfInvoices <= 0 then
            Message(Text005);
        if NoOfInvoices = 1 then
            Message(Text006);
        if NoOfInvoices > 1 then
            Message(Text007, NoOfInvoices);
    end;
    //>>New Code Begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeEndCreateInvoice(var NoOfInvoices: Integer; var IsHandled: Boolean)
    begin
    end;
    //<<New Code End
____

### Additional context

There is currently no events that can be used to avoid getting the standard message if you want to use the Project Invoicing batch job. 
Internal work item: [AB#557543](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557543)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26919.
