### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - Function CheckItemCharge

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#27619]
### Describe the request

In codeunit 90 "Purch.-Post" I need an event in function CheckItemCharge: OnBeforeCheckItemCharge(ItemChargeAssignmentPurch: Record "Item Charge Assignment (Purch)"; IsHandled: Boolean) 

![Image](https://github.com/user-attachments/assets/4de3bd7f-70ec-4bb1-9d40-51ee6f7149a8)

### Additional context

I need it to skip checks based on several conditions.
Internal work item: [AB#557539](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557539)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26919.
