### ISSUE TITLE
page 903 "Assembly Lines" - Set UsageCategory = Lists

### ISSUE THREAD

**Issue by Doriano-Ponzo-EOS** [microsoft/ALAppExtensions#27617]
### Describe the request

Change UsageCategory on page "Assembly Lines" to allow users to search it with "Tell Me".

Similar page is "Sales Lines" (516) with "UsageCategory = Lists;"

### Additional context

To allow users to search it with "Tell Me".
Internal work item: [AB#559878](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559878)

**Comment by JesperSchulz** [comment]
This is not the right place to report bugs, but given this is a tiny change, I'll swiftly do it.

**Comment by Doriano-Ponzo-EOS** [comment]
Sorry and thank you. How can I understand when will it be released?

**Comment by JesperSchulz** [comment]
> Sorry and thank you. How can I understand when will it be released?

Is this urgent? Currently it's set to release with 26 in April, but I could backport if this is something you really need 😊

**Comment by Doriano-Ponzo-EOS** [comment]
Honestly, it's not urgent on 2024, but it will be in 2025 due to new customers live.

To avoid to duplicate the page, can you please backport the fix?

**Comment by JesperSchulz** [comment]
> Honestly, it's not urgent on 2024, but it will be in 2025 due to new customers live.
> 
> To avoid to duplicate the page, can you please backport the fix?

Sure! Expected release is with 25.3 in January.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27743.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 28081.
