### ISSUE TITLE
[Event Change Request] COD6620 Copy-Document - procedure CopyPurchDocLine - Event OnCopyPurchLineOnBeforeValidateQuantity

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27614]
### Describe the request

We would like add ShouldNegQuantity(var) to the following events.

Original:

```

Codeunit 6620 - Copy Document - procedure CopyPurchDocLine- Event OnCopyPurchLineOnBeforeValidateQuantity

        RecalculateAndApplyPurchLine(ToPurchHeader, ToPurchLine, FromPurchLine, RecalculateAmount);

        OnCopyPurchLineOnBeforeValidateQuantity(ToPurchLine, RecalculateLines, FromPurchLine, MoveNegLines);

        if MoveNegLines and (ToPurchLine.Type <> ToPurchLine.Type::" ") then begin
            ToPurchLine.Validate(Quantity, -FromPurchLine.Quantity);
            OnCopyPurchLineOnAfterValidateQuantityMoveNegLines(ToPurchLine, FromPurchLine);
            ToPurchLine."Appl.-to Item Entry" := FromPurchLine."Appl.-to Item Entry"
        end;

    [IntegrationEvent(false, false)]
    local procedure OnCopyPurchLineOnBeforeValidateQuantity(var ToPurchLine: Record "Purchase Line"; RecalculateLines: Boolean; FromPurchaseLine: Record "Purchase Line"; MoveNegLines: Boolean)
    begin
    end;
```

Change:

```
        RecalculateAndApplyPurchLine(ToPurchHeader, ToPurchLine, FromPurchLine, RecalculateAmount);

        ShouldNegQuantity :=  MoveNegLines and (ToPurchLine.Type <> ToPurchLine.Type::" ");
        OnCopyPurchLineOnBeforeValidateQuantity(ToPurchLine, RecalculateLines, FromPurchLine, MoveNegLines,ShouldNegQuantity );

        if ShouldNegQuantity then begin
            ToPurchLine.Validate(Quantity, -FromPurchLine.Quantity);
            OnCopyPurchLineOnAfterValidateQuantityMoveNegLines(ToPurchLine, FromPurchLine);
            ToPurchLine."Appl.-to Item Entry" := FromPurchLine."Appl.-to Item Entry"
        end;

    [IntegrationEvent(false, false)]
    local procedure OnCopyPurchLineOnBeforeValidateQuantity(var ToPurchLine: Record "Purchase Line"; RecalculateLines: Boolean; FromPurchaseLine: Record "Purchase Line"; MoveNegLines: Boolean; var ShouldNegQuantity  : Boolean)
    begin
    end;
```

### Additional context

Add a additional condition to the if-clause.

As alternative an IsHandled-Event could be added to OnCopyPurchLineOnBeforeValidateQuantity. But than the additional event OnCopyPurchLineOnAfterValidateQuantityMoveNegLines would be skipped.
Internal work item: [AB#557544](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557544)

**Comment by AleksandricMarko** [comment]
Hello @MH1612 
Is there chance for you to change the value of the "MoveNegLines" variable?
Probably the effect will be the same

**Comment by SKeiler** [comment]
Hi @AleksandricMarko,

is difficult. The MoveNegLines-Parameter has a lot of logic around and we should need an additional event to reset the parameter (and we need a binding to know that we have manipulate the MoveNegLines). It would be more easier with the Should-Solution.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27480.
