### ISSUE TITLE
[Event Change Request] TAB39 Purchase Line - procedure CopyPurchDocLine - Event OnValidateLocationCodeOnBeforeDropShipmentError

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27615]
### Describe the request

We would like add PurchaseLine(var) to the following events.

Original:

```
TAB39 - Purchase Line - procedure Validate "No."- Event OnValidateLocationCodeOnBeforeDropShipmentError

    [IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeDropShipmentError(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; xPurchaseLine: Record "Purchase Line")
    begin
    end;
```

Change:

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeDropShipmentError(VAR PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; xPurchaseLine: Record "Purchase Line")
    begin
    end;
```

### Additional context

Modify the Purchase Line in the Event
Internal work item: [AB#557545](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557545)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26919.
