### ISSUE TITLE
[Event Change Request] TAB39 Purchase Line - field "No." - Validate - Event OnValidateLocationCodeOnBeforeSpecialOrderError

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27616]
### Describe the request

We would like add PurchaseLine(var) to the following events.

Original:

```
TAB39 - Purchase Line - Validate "No." - Event OnValidateLocationCodeOnBeforeSpecialOrderError

    [IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeSpecialOrderError(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; CurrFieldNo: Integer; xPurchaseLine: Record "Purchase Line")
    begin
    end;
```

Change:

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeSpecialOrderError(VAR PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; CurrFieldNo: Integer; xPurchaseLine: Record "Purchase Line")
    begin
    end;
```

### Additional context

Change the Purchase Line in the event
Internal work item: [AB#557541](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557541)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26919.
