### ISSUE TITLE
[Change Request] Protected variables in report `report 86 "Adjust Add. Reporting Currency"`

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#27610]
### Describe the request

Please make variables protected in report `report 86 "Adjust Add. Reporting Currency"`

```
GLSetup: Record "General Ledger Setup";
Currency: Record Currency;
```

### Additional context

It's necessary for filling custom fields in G/L Entry related to ACY
Internal work item: [AB#557548](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557548)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27697.
