### ISSUE TITLE
Change protection level of variables CompanyAddr  in Report 1309 "Standard Sales - Return Rcpt.", Report 6636 "Purchase - Return Shipment", Report 407 "Purchase - Credit Memo", Report 408 "Purchase - Receipt"

### ISSUE THREAD

**Issue by SerhiiKorniichuk1** [microsoft/ALAppExtensions#27621]
Hello, please, change these var to protected var:

1.Report 1309 "Standard Sales - Return Rcpt."

Current:
var
CompanyAddr: array[8] of Text[100];

Should be:
protected var
CompanyAddr: array[8] of Text[100];

2.Report 6636 "Purchase - Return Shipment"

Current:
var
CompanyAddr: array[8] of Text[100];

Should be:
protected var
CompanyAddr: array[8] of Text[100];

3.Report 407 "Purchase - Credit Memo"

Current:
var
CompanyAddr : array[8] of Text[100];

Should be:
protected var
CompanyAddr: array[8] of Text[100];

4.Report 408 "Purchase - Receipt"

Current:
var
CompanyAddr: array[8] of Text[100];

Should be:
protected var
CompanyAddr: array[8] of Text[100];
Internal work item: [AB#557538](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557538)

**Comment by SerhiiKorniichuk1** [comment]
we had an issue https://github.com/microsoft/ALAppExtensions/issues/26118
I made a mistake to specifying in most lines ShipToAddr :(
I would be very grateful if you could add this in the nearest app, since the company I work for has been waiting for a number of modifications to the tasks for half a year now..... if it lasts for half a year I will be very uncomfortable

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
