### ISSUE TITLE
[Request-For-External] TAB36 "Sales Header" - Procedure SetBillToCustomerNo

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#27629]
### Describe the request

Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

```
[Request-For-External] TAB36 "Sales Header" - Procedure from Internal to Global

procedure SetBillToCustomerNo(var Cust: Record Customer)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetBillToCustomerNo(Rec, Cust, IsHandled, xRec, CurrFieldNo);
        if IsHandled then
            exit;

        if Cust."Bill-to Customer No." <> '' then
            Validate("Bill-to Customer No.", Cust."Bill-to Customer No.")
        else begin
            if "Bill-to Customer No." = "Sell-to Customer No." then
                SkipBillToContact := true;
            Rec.Validate("Bill-to Customer No.", Rec."Sell-to Customer No.");
            SkipBillToContact := false;
        end;
    end;

```	

### Additional context

Use it out of the TableExtension
Internal work item: [AB#557529](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557529)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
