### ISSUE TITLE
[Global Procedure Request] - codeunit 7312 "Create Pick" - local procedure to global procedure

### ISSUE THREAD

**Issue by lhadhazi9940** [microsoft/ALAppExtensions#27624]
Dear Support,
Could You please modify the CreateNewWhseDoc from local procedure to global proceedure in codeunit 7312 "Create Pick"?

<<<<< Original >>>>>

` local procedure CreateNewWhseDoc(OldNo: Code[20]; OldSourceNo: Code[20]; OldLocationCode: Code[10]; var FirstWhseDocNo: Code[20]; var LastWhseDocNo: Code[20]; var NoOfSourceDoc: Integer; var NoOfLines: Integer; var WhseDocCreated: Boolean)`

<<<<< Modified >>>>>

`procedure CreateNewWhseDoc(OldNo: Code[20]; OldSourceNo: Code[20]; OldLocationCode: Code[10]; var FirstWhseDocNo: Code[20]; var LastWhseDocNo: Code[20]; var NoOfSourceDoc: Integer; var NoOfLines: Integer; var WhseDocCreated: Boolean)`

**Additional context**
After an upgrade, we have to reuse this from a custom procedure, and we can not call it due to it is a local procedure.

Thanks for Your help in advance!
Internal work item: [AB#557536](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557536)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26910.
