### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" Function InsertCapLedgEntry

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#27622]
### Describe the request

In codeunit 22 "Item Jnl.-Post Line" I need an event in function InsertCapLedgEntry: OnBeforeOnInsertCapLedgEntry(var IsHandled: Boolean; var CapLedgEntry: Record "Capacity Ledger Entry"; ItemJournalLine: Record "Item Journal Line")
![Image](https://github.com/user-attachments/assets/1fb8eb14-1e06-41e4-8646-76770a18f18b)

### Additional context

I need it to skip the whole function in some cases based on fields in in the Item Journal Line
Internal work item: [AB#557535](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557535)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26919.
