### ISSUE TITLE
[Event Change Request] Codeunit 90 "Purch.-Post" - OnPostItemJnlLineOnAfterPostItemJnlLineJobConsumption

### ISSUE THREAD

**Issue by ChristianFeitl** [microsoft/ALAppExtensions#27627]
### Describe the request

The publisher ```OnPostItemJnlLineOnAfterPostItemJnlLineJobConsumption``` has parameters ```TempReservationEntry``` and ```TempHandlingSpecification``` which should provide a reference to temporary tables maintained globally and by the function ```PostItemJnlLine``` in ```Codeunit 90 Purch.-Post```. The parameters are missing the var keyword and therefore the records in the temporary tables cannot be accessed in subscribers.

Current:
```
    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineOnAfterPostItemJnlLineJobConsumption(var ItemJournalLine: Record "Item Journal Line"; PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; OriginalItemJnlLine: Record "Item Journal Line"; TempReservationEntry: Record "Reservation Entry"; TrackingSpecification: Record "Tracking Specification"; QtyToBeInvoiced: Decimal; QtyToBeReceived: Decimal; var PostJobConsumptionBeforePurch: Boolean)
    begin
    end;
```

New:
```
    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineOnAfterPostItemJnlLineJobConsumption(var ItemJournalLine: Record "Item Journal Line"; PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; OriginalItemJnlLine: Record "Item Journal Line"; **var** TempReservationEntry: Record "Reservation Entry" **temporary**; **var** TrackingSpecification: Record "Tracking Specification" **temporary**; QtyToBeInvoiced: Decimal; QtyToBeReceived: Decimal; var PostJobConsumptionBeforePurch: Boolean)
    begin
    end;
```

### Additional context

There is no way to work around the issue in our specific situation.
The customer cannot work with item tracking in some parts of our application because of this.
Internal work item: [AB#557533](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557533)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 26919.
