### ISSUE TITLE
Codeunit 5722 (Item Category Management): Add a new event in procedure UpdatePresentationOrderIterative()

### ISSUE THREAD

**Issue by 1AviSingh1** [microsoft/ALAppExtensions#27637]
### Describe the request

I would like to request Microsoft Dynamics Business Central AL team to publish a new event with the need of get better control over the procedure `UpdatePresentationOrderIterative()` in Codeunit 5722 as shown in the below code snippet which is requested as a new event in the tags // NEW EVENT BEGIN ----- // NEW EVENT END and also attaching the further details for the requirement at end of this request.

Thank you!

       `IsHandled := false;
        OnBeforeUpdatePresentationOrderIterative(var TempItemCategory: Record "Item Category" Temporary, var IsHandled: Boolean);
        if IsHandled then
            exit;

        PresentationOrder := 0;
        TempCurItemCategory.Copy(ItemCategory, true);

        ItemCategory.SetCurrentKey("Parent Category");
        ItemCategory.Ascending(false);
        ItemCategory.SetRange("Parent Category", '');
        if ItemCategory.FindSet(false) then
            repeat
                TempStack.Push(ItemCategory.RecordId());
        until ItemCategory.Next() = 0;
`

// NEW EVENT
`
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdatePresentationOrderIterative(var ItemCategory: Record "Item Category", var IsHandled: Boolean)
begin
end;
`

### Additional context

![Image](https://github.com/user-attachments/assets/f5e70088-2259-4eca-9832-f235c3feed5c)

Internal work item: [AB#558162](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558162)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27498.
