### ISSUE TITLE
[Event Request] Table 32 Item Ledger Entry

### ISSUE THREAD

**Issue by simcrest** [microsoft/ALAppExtensions#2763]
We have a customer that requires us to modify the function VerifyOnInventory(). Here is our request:
![eventrequest](https://user-images.githubusercontent.com/15910725/59111992-25e8b300-8910-11e9-90db-7474ac848434.png)
IsHandled is VAR returning a boolean from the subscriber whether to exit or not.

**Comment by AlexanderYakunin** [comment]
This is already available in 14.X, you are working with old code base
[External] VerifyOnInventory()
IsHandled := FALSE;
OnBeforeVerifyOnInventory(Rec,IsHandled);
IF IsHandled THEN
  EXIT;

**Comment by simcrest** [comment]
Very good Thanks.
