### ISSUE TITLE
[Event Request] Codeunit 1222 "SEPA CT-Prepare Source" - OnBeforeInsertTempJnlLines and OnAfterInsertTempJnlLines

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#27638]
### Describe the request

Could you add the required events in Codeunit 1222 "SEPA CT-Prepare Source"?

_Current code:_

local procedure CreateTempJnlLines(var FromGenJnlLine: Record "Gen. Journal Line"; var TempGenJnlLine: Record "Gen. Journal Line" temporary)
...
                TempGenJnlLine.Amount := CarteraDoc."Remaining Amount";
                TempGenJnlLine.Insert();
            until CarteraDoc.Next() = 0;

_Requested:_

local procedure CreateTempJnlLines(var FromGenJnlLine: Record "Gen. Journal Line"; var TempGenJnlLine: Record "Gen. Journal Line" temporary)
...
                TempGenJnlLine.Amount := CarteraDoc."Remaining Amount";
                OnBeforeInsertTempJnlLines(TempGenJnlLine, CarteraDoc);  //NEW
                TempGenJnlLine.Insert();
                OnAfterInsertTempJnlLines(TempGenJnlLine, CarteraDoc);  //NEW
            until CarteraDoc.Next() = 0;

//>NEW
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertTempJnlLines(var TempGenJnlLine: Record "Gen. Journal Line"; CarteraDoc: Record "Cartera Doc.")
begin
end;

[IntegrationEvent(false, false)]
local procedure OnAfterInsertTempJnlLines(var TempGenJnlLine: Record "Gen. Journal Line"; CarteraDoc: Record "Cartera Doc.")
begin
end;
//<NEW

### Additional context

As it works with "Cartera Doc.", it affects only in the Spanish localization.
Internal work item: [AB#558164](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558164)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27186.
