### ISSUE TITLE
[Event Request] Table 5900 "Service Header" : OnBeforeValidateStartingDate, OnBeforeValidateStartingTime, OnBeforeValidateFinishingDate, OnBeforeValidateFinishingTime

### ISSUE THREAD

**Issue by jchaloupka-pdw** [microsoft/ALAppExtensions#27642]
### Describe the request

Can you please create the following 4 integration events: OnBeforeValidateStartingDate, OnBeforeValidateStartingTime, OnBeforeValidateFinishingDate and OnBeforeValidateFinishingTime in table 5900 Service Header and add them into OnValidate() trigger of the related table fields - Starting Date, Starting Time, Ending Date and Ending Time?

`[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateStartingDate(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;`

`[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateStartingTime(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;`

`[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateFinishingDate(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;`

`[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateFinishingTime(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;`

```
field(5929; "Starting Date"; Date)
{
  Caption = 'Starting Date';

  trigger OnValidate()
  var
    IsHandled: Boolean;  
  begin
    IsHandled := false;
    OnBeforeValidateStartingDate(Rec, xRec, CurrFieldNo, IsHandled);
    if IsHandled then
      exit;
  ...
  end;
}
```

### Additional context

We need to maintain our own logic for the mentioned 4 fields and therefore we need these integration events.
Internal work item: [AB#558157](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558157)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27498.
