### ISSUE TITLE
table 5902 "Service Line" - GetDate

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27640]
### Describe the request

Can you change the procedure GetDate in Sales Line to be global?

### Additional context

I'm using it to get the date in custom code, and I dont want to duplicate the code.
Internal work item: [AB#558160](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558160)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27466.
