### ISSUE TITLE
[Performance] Codeunit 11000001 "Financial Interface Telebank" -   SetApplyCVLedgerEntries - use AutoCalcField 

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#27643]
### Describe the request

Please make use of the SetAutoCalcFields instead of Calcfields on the Procedure "SetApplyCVLedgerEntries" from codeunit 11000001 "Financial Interface Telebank". This way the Microsoft code can be used by external parties as it will have ok performance.
This is regarding the Dutch Localization for telebanking.
The concerning procedure is called in a loop a lot of times, so it has a large performance impact.

Change: 
CustLedgerEntry.CalcFields("Payments in Process");
VendorLedgerEntry.CalcFields("Payments in Process");
EmployeeLedgerEntry.CalcFields("Payments in Process");

To 
CustLedgerEntry.SetAutoCalcFields("Payments in Process");
VendorLedgerEntry.SetAutoCalcFields("Payments in Process");
EmployeeLedgerEntry.SetAutoCalcFields("Payments in Process");

### Additional context

The microsoft code we extend upon should have a good performance.
Internal work item: [AB#558156](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558156)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27186.

**Comment by AndersLarsenMicrosoft** [comment]
We had to revert the suggested fix as it brokkes some scenarios with the the filter not being Applied. A rearrange may have solved this issue but that will be on another checkin
