### ISSUE TITLE
[Bug]: Remove `[Scope('OnPrem')]` from `SetBatchMode` in Codeunit 426

### ISSUE THREAD

**Issue by AlaWeslati** [microsoft/ALAppExtensions#27647]
### Describe the issue

The `SetBatchMode` function in codeunit `Payment Tolerance Management` (ID 426) is unnecessarily restricted to on-prem environments with the `[Scope('OnPrem')]` attribute, even though it does not rely on on-prem-specific functionality.  

### Expected behavior

The `[Scope('OnPrem')]` attribute should be removed, allowing the `SetBatchMode` function to be used in both SaaS and on-prem environments.  

### Steps to reproduce

1. Attempt to use the `SetBatchMode` function in an extension targeting SaaS.  
2. Observe that the function is unavailable due to the `[Scope('OnPrem')]` restriction.  

### Additional context

This change will increase the usability of the `SetBatchMode` function without introducing any breaking changes.  

### I will provide a fix for a bug

- [x] I will provide a fix for a bug
Internal work item: [AB#557865](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/557865)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27075.
