### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post".OnBeforePostCommitPurchaseDoc

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27644]
### Describe the request

Please make parameter "ModifyHeader" as var.

```
    [IntegrationEvent(false, false)]
    // ------------------------------------------------------------------OnBeforePostCommitPurchaseDoc:BEGIN
    //local procedure OnBeforePostCommitPurchaseDoc(var PurchaseHeader: Record "Purchase Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; PreviewMode: Boolean; ModifyHeader: Boolean; var CommitIsSupressed: Boolean; var TempPurchLineGlobal: Record "Purchase Line" temporary)
    local procedure OnBeforePostCommitPurchaseDoc(var PurchaseHeader: Record "Purchase Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; PreviewMode: Boolean; var ModifyHeader: Boolean; var CommitIsSupressed: Boolean; var TempPurchLineGlobal: Record "Purchase Line" temporary)
    // ------------------------------------------------------------------OnBeforePostCommitPurchaseDoc:END
    begin
    end;
```

### Additional context

We need change parameter. 
Internal work item: [AB#558158](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558158)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27498.
