### ISSUE TITLE
[Remove Internal] Table 8068 "Sales Service Commitment" in "Subscription & Recurring Billing" App

### ISSUE THREAD

**Issue by PierreGlicinski** [microsoft/ALAppExtensions#27668]
### Describe the request

As described in the title, I would like to request whether the "Access = Internal" from the table "Sales Service Commitment" can be removed.

Why?
![Image](https://github.com/user-attachments/assets/9171fa6e-5a00-41e2-9211-6c0350dacac3)

The app is already being delivered in cloud systems and is automatically installed there. Since my customers can already use this functionality, I am now under pressure as a "partner" to integrate the corresponding app into my own apps.

If I read the code correctly, there are two fundamental checks to determine whether the corresponding record is a recurring invoice:

The "Recurring Billing" flag, which I can access externally.
A check for "IsContractRenewal." At this point, entries in the "Sales Service Commitment" table are searched for. However, I cannot access this point externally and, therefore, cannot determine whether "Recurring Billing" is necessary.

I can understand that events are not available everywhere right away. I can also understand that not all functions or codeunits are open. But when it comes to tables, I really don't understand this approach at all.

As of now, putting the "dirty tricks" aside, I have no way to read records from this table and, therefore, cannot perform the necessary checks to determine whether a recurring invoice is being used at all.

If app combinations lead to errors, the current situation creates a rather unpleasant problem for me.

Therefore, my request???and my thanks in advance!
Best regards,
Pierre

### Additional context

Remove Internal from Table 
Internal work item: [AB#558488](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558488)

**Comment by BardurKnudsen** [comment]
Sounds very reasonable to me.

**Comment by AndersLarsenMicrosoft** [comment]
As state on Yammer we will start opening up with 26 for subscription billing

**Comment by AndersLarsenMicrosoft** [comment]
se above

**Comment by AndersLarsenMicrosoft** [comment]
we announced in Yammer that most of the removal will be removed with 26.1 was delayed ro 26.1 due to a terminologi refresh
