### ISSUE TITLE
Page Acc. Schedule Overview - SetDimFilters

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#27669]
### Describe the request

Please make the procedure SetDimFilters global. 

**Current**

` local procedure SetDimFilters(DimNo: Integer; DimValueFilter: Text)`

**New**
`procedure SetDimFilters(DimNo: Integer; DimValueFilter: Text)`

### Additional context

I would like to override the dimensions which are displayed when filtering dimension values. This can be achieved by hiding the standard field but I need to replicate this function in my page extension which I would like to avoid. 
Internal work item: [AB#558491](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558491)

**Comment by BardurKnudsen** [comment]
Sounds like a good change

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27380.
