### ISSUE TITLE
[Page UsageCategory Request] page 5178 "Job Task Archive Lines"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#27676]
### Describe the request

Please set the property of page 5178 "Job Task Archive Lines"

UsageCategory = Lists;

### Additional context

Customers want to be able to search for this list page and create menu views etc.
Internal work item: [AB#559876](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559876)

**Comment by BardurKnudsen** [comment]
Bug

**Comment by JesperSchulz** [comment]
This is not the right place to report product defects, but I'll take care of this one.

**Comment by Duizy1971** [comment]
Sorry Jesper, I probably choose the wrong category from the many available options.

**Comment by JesperSchulz** [comment]
🤣 And I didn't even notice it was you, @Duizy1971! I know that you very well know the processes. But anyway, I've just created a PR to fix this, so this should be taken care of!
I wish you a great weekend! And thanks for reporting!

**Comment by JesperSchulz** [comment]
Issue fixed in master branch.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27743.
