### ISSUE TITLE
[Bug]: codeunit 5748 "Transfer Whse. Post Shipment" ModifyHeader

### ISSUE THREAD

**Issue by ChristiaanJansen** [microsoft/ALAppExtensions#27675]
### Describe the issue

codeunit 5748 "Transfer Whse. Post Shipment"

Integrationevents OnInitSourceDocumentHeaderOnBeforeTransferHeaderUpdatePostingDate and OnInitSourceDocumentHeaderOnBeforeTransHeaderModify where boolean "ModifyHeader" should by ByVar. 

  [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnBeforeTransferHeaderUpdatePostingDate(var TransferHeader: Record "Transfer Header"; var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseShipmentLine: Record "Warehouse Shipment Line"; ModifyHeader: Boolean; IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnBeforeTransHeaderModify(var TransferHeader: Record "Transfer Header"; var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; ModifyHeader: Boolean)
    begin
    end;

### Expected behavior

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnBeforeTransferHeaderUpdatePostingDate(var TransferHeader: Record "Transfer Header"; var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var ModifyHeader: Boolean; IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnBeforeTransHeaderModify(var TransferHeader: Record "Transfer Header"; var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var ModifyHeader: Boolean)
    begin
    end;

### Steps to reproduce

Create transfer order --> create whse shipment --> post whse Shipment 

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug
Internal work item: [AB#558501](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558501)

**Comment by BardurKnudsen** [comment]
OK

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27498.
