### ISSUE TITLE
[Event Request] Codeunit 7308 Replenishment.UseForReplenishment

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27679]
### Describe the request

please do procedure UseForReplenishment as global that can be called from another objects

### Additional context

We need run this function from our code.
Internal work item: [AB#558505](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558505)

**Comment by BardurKnudsen** [comment]
Could also be move the code to a public method on the Bin Content record object, so the consuming code would look like this:

if BinContent.UseForReplenishment() then ...

instead of

if Replenishment.UseForReplenishment(BinContent) then ...

**Comment by fridrichovsky** [comment]
Hello yeas it can be.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27466.
