### ISSUE TITLE
[Extensibility Enhancement] Provide access to Caption and Request Page Caption through Report Extension

### ISSUE THREAD

**Issue by petmoe** [microsoft/ALAppExtensions#27682]
### Describe the request

When you create a Report Extension you can modify existing fields on the Request Page of the report, changing captions and behavior of those fields but you cannot change the caption on the report or on the request page.
We would like the Caption of the Report and the Request Page to be accessible through the Report Extension object the same way as it is in a Page Extension object.  

### Additional context

When extending the functionality of an existing report we would like to be able to reflect this in the Caption. 
E.g. if the existing Request Page caption says "Create Sales Invoice" but we extended the report, adding the ability to create Sales Order, we would like to be able to change the Request Page caption to "Create Sales Document".

However, in the current setup we cannot just extend the existing report; we will have to copy the entire standard report to a new object and modify it to get this result.

**Comment by BardurKnudsen** [comment]
Good idea, but is not something we can do via AL. Instead, create a new idea on aka.ms/bcideas for the platform.

**Comment by petmoe** [comment]
Thanks, Bardur - will do...
