### ISSUE TITLE
Change variable FreightAmount to protected on page 10026 "Sales Order Shipment"

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#27688]
### Describe the request

To give visibility to page extension, change variable FreightAmount from "var" to "protected var" on page 10026 "Sales Order Shipment".

### Additional context

We;re adding a posting option that requires visibility of the FreightAmount variable.
Internal work item: [AB#558848](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558848)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27466.
