### ISSUE TITLE
[Subscription Request] - Table 36 "Sales Header" - OnBeforeSetWorkDescription

### ISSUE THREAD

**Issue by lhadhazi9940** [microsoft/ALAppExtensions#27684]
### Describe the request

Dear Support,
Could You please add a new subscription for the beginning of the SetWorkDescription procedure?
<<<<< Original >>>>>
```
    procedure SetWorkDescription(NewWorkDescription: Text)
    var
        OutStream: OutStream;
    begin
        Clear("Work Description");
        "Work Description".CreateOutStream(OutStream, TEXTENCODING::UTF8);
        OutStream.WriteText(NewWorkDescription);
        Modify();
    end;
```

<<<<< Modified >>>>>
```
    procedure SetWorkDescription(NewWorkDescription: Text)
    var
        OutStream: OutStream;
    begin
        OnBeforeSetWorkDescription(Rec,NewWorkDescription);
        Clear("Work Description");
        "Work Description".CreateOutStream(OutStream, TEXTENCODING::UTF8);
        OutStream.WriteText(NewWorkDescription);
        Modify();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetWorkDescription(var SalesHeader: Record "Sales Header"; var NewWorkDescription: Text)
    begin
    end;
```

Thanks for in advance!
BR,
Laszlo

### Additional context

With these modifications we are able to modify and read the content of the work description avoiding the multiple database operations.
Internal work item: [AB#558508](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558508)

**Comment by BardurKnudsen** [comment]
OK

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27498.
