### ISSUE TITLE
[Bug]: Copy/Paste Error on MaxStrLen

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#27695]
### Describe the issue

The MaxStrLen should be checking for the correct variables. This is most likely a copy&paste error and was overlooked as these lines are quite long:

https://github.com/microsoft/ALAppExtensions/blob/07aa6c5540cf21e8bc90dfbace5d9b137055aa0f/Apps/W1/EDocument/app/src/Format/EDocImportPEPPOLBIS30.Codeunit.al#L121-L122

### Expected behavior

-

### Steps to reproduce

-

### Additional context

-

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Of course approved.

**Comment by dannoe** [comment]
Looks like @aholstrup1 has already addressed this issue.
