### ISSUE TITLE
Request for protected variables - Fixed Asset Journal page

### ISSUE THREAD

**Issue by mynhardt7** [microsoft/ALAppExtensions#27692]
### Describe the request

On page 5629 "Fixed Asset Journal", can the following to variables please be made protected (the same as was done on page 5628 "Fixed Asset G/L Journal")

CurrentJnlBatchName: Code[10];
FADescription: Text[100];

### Additional context

Needed for page customisations.
Internal work item: [AB#558856](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558856)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27697.
