### ISSUE TITLE
Request for protected variables - Purchase Journal page

### ISSUE THREAD

**Issue by mynhardt7** [microsoft/ALAppExtensions#27690]
### Describe the request

On page 254 "Purchase Journal"", can the following to variables please be made protected (the same as was done on page 253 "Sales Journal")

AccName: Text[100];
BalAccName: Text[100];

### Additional context

Needed for page customisations.
Internal work item: [AB#558849](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558849)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27466.
