### ISSUE TITLE
[Public procedure] Query "Qty. Reserved From Item Ledger" - SetSourceFilter

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#27696]
### Describe the request

Can you please expose function **SetSourceFilter** in Query "Qty. Reserved From Item Ledger"?

### Additional context

We want to calculate the ReservedQtyFromInventory for a given Sales / Purchase order by location, forcing us to copy the functions from codeunit 99000832 "Sales Line-Reserve" GetReservedQtyFromInventory.

Doing so fails to compile due to the missing access to **SetSourceFilter**.

```
internal procedure GetReservedQtyFromInventoryWithLocation(SalesHeader: Record "Sales Header"; LocationCode: Code[10]): Decimal
    var
        ReservationEntry: Record "Reservation Entry";
        QtyReservedFromItemLedger: Query "Qty. Reserved From Item Ledger";
    begin
        ReservationEntry.SetSource(Database::"Sales Line", SalesHeader."Document Type".AsInteger(), SalesHeader."No.", 0, '', 0);
        QtyReservedFromItemLedger.SetSourceFilter(ReservationEntry); // MISSING     
        QtyReservedFromItemLedger.SetFilter(Location_Code, LocationCode);
        QtyReservedFromItemLedger.Open();
        if QtyReservedFromItemLedger.Read() then
            exit(QtyReservedFromItemLedger.Quantity__Base_);

        exit(0);
    end;
```
Internal work item: [AB#558855](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558855)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27466.
