### ISSUE TITLE
[Protected var Request] Report 11703 "Accounting Sheets CZL"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27697]
### Describe the request

Please do this variable as protected:
TempGLEntry: Record "G/L Entry" temporary;

### Additional context

We need use values from mentioned table buffer
Internal work item: [AB#558853](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558853)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27466.
