### ISSUE TITLE
[Event Request] Codeunit 333 - Req. Wksh.-Make Order - OnBeforeUpdateAssociatedSalesLine

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#27707]
### Describe the request

Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeUpdateAssociatedSalesLine` to be added to Codeunit 333 Req. Wksh.-Make Order with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateAssociatedSalesLine(var PurchOrderLine: Record "Purchase Line"; var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;
```

which would be called as follows from `InsertPurchOrderLine`:
```al
        if ReqLine2.Reserve then
            ReserveBindingOrderToPurch(PurchOrderLine, ReqLine2);

        IsHandled := false; //new
        OnBeforeUpdateAssociatedSalesLine(PurchOrderLine, ReqLine2, IsHandled); //new
        if not IsHandled then //new
            if PurchOrderLine."Drop Shipment" or PurchOrderLine."Special Order" then begin
```

### Additional context

We would like to be able to connect the special order purchase line to a service line.
Internal work item: [AB#558867](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558867)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27465.
