### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeValidateCustomerDiscGroup

### ISSUE THREAD

**Issue by skuchana93** [microsoft/ALAppExtensions#27705]
### Describe the request

In Table 36, please include the OnBeforeValidateCustomerDiscGroup event within the OnValidate trigger of the "Customer Disc. Group" field.

**Actual Code:**
trigger OnValidate()
begin
        TestStatusOpen();
       MessageIfSalesLinesExist(FieldCaption("Customer Disc. Group"));
end;

**Required Code with a new event request:**
trigger OnValidate()
var
     IsHandled: Boolean;
begin
       IsHandled := false;
       OnBeforeValidateCustomerDiscGroup(Rec, xRec, CurrFieldNo, IsHandled);
       if IsHandled then
          exit;
       TestStatusOpen();
       MessageIfSalesLinesExist(FieldCaption("Customer Disc. Group"));
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeValidateCustomerDiscGroup(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; CurrentFieldNo: Integer; var IsHandled: Boolean)
begin
end;

### Additional context

This new event is necessary to enable subscription for implementing custom code and to provide the option to bypass the base code when needed.
Internal work item: [AB#558865](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/558865)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27465.
