### ISSUE TITLE
[Event Request] Codeunit 7000 "Sales Price Calc. Mgt." - OnAfterFindSalesLineResPrice

### ISSUE THREAD

**Issue by skuchana93** [microsoft/ALAppExtensions#27716]
### Describe the request

In codeunit 7000, please provide CalledByFieldNo (local variable) in OnAfterFindSalesLineResPrice event in FindSalesLinePrice procedure.

**Actual Code:**
SalesLine.Type::Resource:
                begin
                    SetResPrice(SalesLine."No.", SalesLine."Work Type Code", SalesLine."Currency Code");
                    OnFindSalesLinePriceOnAfterSetResPrice(SalesLine, ResPrice);
                    CODEUNIT.Run(CODEUNIT::"Resource-Find Price", ResPrice);
                    OnAfterFindSalesLineResPrice(SalesLine, ResPrice);
                    if not (CalledByFieldNo = SalesLine.FieldNo(Quantity)) then begin
                        ConvertPriceToVAT(false, '', '', ResPrice."Unit Price");
                        ConvertPriceLCYToFCY(ResPrice."Currency Code", ResPrice."Unit Price");
                        SalesLine."Unit Price" := ResPrice."Unit Price" * SalesLine."Qty. per Unit of Measure";
                    end;
                end;

**Required Event:**
SalesLine.Type::Resource:
                begin
                    SetResPrice(SalesLine."No.", SalesLine."Work Type Code", SalesLine."Currency Code");
                    OnFindSalesLinePriceOnAfterSetResPrice(SalesLine, ResPrice);
                    CODEUNIT.Run(CODEUNIT::"Resource-Find Price", ResPrice);
                    **OnAfterFindSalesLineResPrice(SalesLine, ResPrice, CalledByFieldNo);**
                    if not (CalledByFieldNo = SalesLine.FieldNo(Quantity)) then begin
                        ConvertPriceToVAT(false, '', '', ResPrice."Unit Price");
                        ConvertPriceLCYToFCY(ResPrice."Currency Code", ResPrice."Unit Price");
                        SalesLine."Unit Price" := ResPrice."Unit Price" * SalesLine."Qty. per Unit of Measure";
                    end;
                end;

**[IntegrationEvent(false, false)]
    local procedure OnAfterFindSalesLineResPrice(var SalesLine: Record "Sales Line"; var ResPrice: Record "Resource Price", CalledByFieldNo: Integer)
    begin
    end;**

### Additional context

This new addition to the event is required to utilize the scope of the variable in the custom code.
Internal work item: [AB#559343](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559343)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27687.
