### ISSUE TITLE
[Event Request] Codeunit 10090 "Export Payments (ACH)" - OnBeforeStartExportBatchAddDataToPrnString

### ISSUE THREAD

**Issue by skuchana93** [microsoft/ALAppExtensions#27712]
### Describe the request

In Codeunit 10090, please include the OnBeforeStartExportBatchAddDataToPrnString event within the StartExportBatch procedure.

**Actual Code:**
procedure StartExportBatch(ServiceClassCode: Code[10]; EntryClassCode: Code[10]; SourceCode: Code[10]; SettleDate: Date)
    var
        BatchHeaderRec: Text[250];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeStartExportBatch(ServiceClassCode, EntryClassCode, SourceCode, SettleDate, IsHandled);
        if IsHandled then
            exit;
        if not FileIsInProcess then
            Error(ExportFileNotStartedErr);
        if BatchIsInProcess then
            Error(ExportFileNotCompletedErr);
        BatchIsInProcess := true;
        BatchNo := BatchNo + 1;
        BatchHashTotal := 0;
        TotalBatchDebit := 0;
        TotalBatchCredit := 0;
        EntryAddendaCount := 0;
        TraceNo := 0;
        BatchHeaderRec := '';
        AddNumToPrnString(BatchHeaderRec, 5, 1, 1);                                               // Record Type
        AddToPrnString(BatchHeaderRec, ServiceClassCode, 2, 3, Justification::Right, '0');          // Service Class Code
        AddToPrnString(BatchHeaderRec, CompanyInformation.Name, 5, 36, Justification::Left, ' ');   // Company Name (+ Discretionary Data)
        AddFedIDToPrnString(BatchHeaderRec, CompanyInformation."Federal ID No.", 41, 10);         // Company ID
        AddToPrnString(BatchHeaderRec, EntryClassCode, 51, 3, Justification::Left, ' ');            // Entry Class Code
        AddToPrnString(BatchHeaderRec, SourceCode, 54, 10, Justification::Left, ' ');               // Entry Description
        AddToPrnString(BatchHeaderRec, Format(WorkDate(), 0, '<Year><Month,2><Day,2>'), 64, 6, Justification::Left, ' ');   // Descriptive Date
        AddToPrnString(BatchHeaderRec, Format(SettleDate, 0, '<Year><Month,2><Day,2>'), 70, 6, Justification::Left, ' ');
        // Effective Entry Date
        AddNumToPrnString(BatchHeaderRec, 1, 79, 1);                                              // Originator Status Code
        AddToPrnString(BatchHeaderRec, BankAccount."Transit No.", 80, 8, Justification::Left, ' '); // Originating DFI ID
        AddNumToPrnString(BatchHeaderRec, BatchNo, 88, 7);                                        // Batch Number
        ExportPrnString(BatchHeaderRec);
    end;

**Required Code with a new event request:**
procedure StartExportBatch(ServiceClassCode: Code[10]; EntryClassCode: Code[10]; SourceCode: Code[10]; SettleDate: Date)
    var
        BatchHeaderRec: Text[250];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeStartExportBatch(ServiceClassCode, EntryClassCode, SourceCode, SettleDate, IsHandled);
        if IsHandled then
            exit;
        if not FileIsInProcess then
            Error(ExportFileNotStartedErr);
        if BatchIsInProcess then
            Error(ExportFileNotCompletedErr);
        BatchIsInProcess := true;
        BatchNo := BatchNo + 1;
        BatchHashTotal := 0;
        TotalBatchDebit := 0;
        TotalBatchCredit := 0;
        EntryAddendaCount := 0;
        TraceNo := 0;
        BatchHeaderRec := '';
        **OnBeforeStartExportBatchAddDataToPrnString(BatchHeaderRec, ServiceClassCode, EntryClassCode, SourceCode, SettleDate, IsHandled);
        if not IsHandled then begin**
        AddNumToPrnString(BatchHeaderRec, 5, 1, 1);                                               // Record Type
        AddToPrnString(BatchHeaderRec, ServiceClassCode, 2, 3, Justification::Right, '0');          // Service Class Code
        AddToPrnString(BatchHeaderRec, CompanyInformation.Name, 5, 36, Justification::Left, ' ');   // Company Name (+ Discretionary Data)
        AddFedIDToPrnString(BatchHeaderRec, CompanyInformation."Federal ID No.", 41, 10);         // Company ID
        AddToPrnString(BatchHeaderRec, EntryClassCode, 51, 3, Justification::Left, ' ');            // Entry Class Code
        AddToPrnString(BatchHeaderRec, SourceCode, 54, 10, Justification::Left, ' ');               // Entry Description
        AddToPrnString(BatchHeaderRec, Format(WorkDate(), 0, '<Year><Month,2><Day,2>'), 64, 6, Justification::Left, ' ');   // Descriptive Date
        AddToPrnString(BatchHeaderRec, Format(SettleDate, 0, '<Year><Month,2><Day,2>'), 70, 6, Justification::Left, ' ');
        // Effective Entry Date
        AddNumToPrnString(BatchHeaderRec, 1, 79, 1);                                              // Originator Status Code
        AddToPrnString(BatchHeaderRec, BankAccount."Transit No.", 80, 8, Justification::Left, ' '); // Originating DFI ID
        AddNumToPrnString(BatchHeaderRec, BatchNo, 88, 7);                                        // Batch Number
        **end;**
        ExportPrnString(BatchHeaderRec);
    end;
    **[IntegrationEvent(false, false)]
    local procedure OnBeforeStartExportBatchAddDataToPrnString(var BatchHeaderRec: Text[250]; ServiceClassCode: Code[10]; EntryClassCode: 
    Code[10]; SourceCode: Code[10]; SettleDate: Date; var IsHandled: Boolean)
    begin
    end;**

### Additional context

This new event is necessary to enable subscription for implementing custom code and to provide the option to bypass the base code when needed.
Internal work item: [AB#559345](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559345)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27697.
