### ISSUE TITLE
[Request for External] table 5902 "Service Line" LineRequiresShipmentOrReceipt

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27719]
### Describe the request

Can you change procedure LineRequiresShipmentOrReceipt to global in table 5902 "Service Line"?

### Additional context

I'm using event OnBeforeValidateQtyToConsumeBase to override the quantity check, but the I have to add the lines after this event.
That includes LineRequiresShipmentOrReceipt, but it is not global, and i want to avoid duplicating the code.
Internal work item: [AB#559339](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559339)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
