### ISSUE TITLE
[Request for External] table 18 Customer LookupContactList

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27722]
### Describe the request

Can you change LookupContactList to global in table 18 Customer?

### Additional context

I need to use the procedure from a custom variabel field, and i dont want to duplicate the code.
Internal work item: [AB#559337](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559337)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
