### ISSUE TITLE
[Event Request] - 5348 "CRM Quote to Sales Quote" - OnBeforeGetCoupledCustomer

### ISSUE THREAD

**Issue by cesarbs77** [microsoft/ALAppExtensions#27725]
### Describe the request

Dear Support,

Could you please add a new event at the beginning of the procedure GetCoupledCustomer(CRMQuote: Record "CRM Quote"; var Customer: Record Customer): Boolean as it exists in the same function in the codeunit codeunit 5343 "CRM Sales Order to Sales Order"

    procedure GetCoupledCustomer(CRMQuote: Record "CRM Quote"; var Customer: Record Customer): Boolean
    var
        CRMAccount: Record "CRM Account";
        CRMIntegrationRecord: Record "CRM Integration Record";
        NAVCustomerRecordId: RecordID;
        CRMAccountId: Guid;
        IsHandled: Boolean; // ADDED //
    begin
		//>> ADDED 
        IsHandled := false;
        OnBeforeGetCoupledCustomer(CRMQuote, Customer, Result, IsHandled);
        if IsHandled then
            exit(Result);
		//<< ADDED 
		
        if IsNullGuid(CRMQuote.CustomerId) then
            Error(NoCustomerErr, CannotCreateSalesQuoteInNAVTxt, CRMQuote.Description, CRMProductName.CDSServiceName());
		........
		........
	end;
	
	//>> ADDED 
	[IntegrationEvent(false, false)]
	local procedure OnBeforeGetCoupledCustomer(CRMQuote: Record "CRM Quote"; var Customer: Record Customer; var Result: Boolean; var IsHandled: Boolean)
	begin		
	end;
	//<< ADDED 		

### Additional context

This new event is necessary to define the same procedure in qoute creation as in order creation
Internal work item: [AB#559336](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559336)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27687.
