### ISSUE TITLE
[Event Request] - table 15 "G/L Account" - OnBeforeCheckSalesOrdersPrepmtToDeduct

### ISSUE THREAD

**Issue by Christina-WH** [microsoft/ALAppExtensions#27723]
### Describe the request

Dear Support,

Could you please add a new event at??the beginning of the local procedure CheckSalesOrdersPrepmtToDeduct(FldCaption: Text)

?? ?? local procedure CheckSalesOrdersPrepmtToDeduct(FldCaption: Text)
?? ?? var
?? ?? ?? ?? ??GeneralPostingSetup: Record "General Posting Setup";
?? ?? ?? ?? ??//
?? ?? ?? ?? ??IsHandled := false;
?? ?? ?? ?? ??//
?? ?? begin
?? ???? ???? ??//
?? ?? ?? ?? ??IsHandled := false;
?? ?? ?? ?? ??OnBeforeCheckSalesOrdersPrepmtToDeduct(Rec, IsHandled);
?? ?? ?? ?? ??if IsHandled then
?? ?? ?? ?? ?? ?? exit;
?? ?? ?? ?? ??//
?? ?? ?? ?? GeneralPostingSetup.SetLoadFields("Gen. Bus. Posting Group", "Gen. Prod. Posting Group");
?? ?? ?? ?? GeneralPostingSetup.FilterGroup(-1);
?? ?? ?? ?? GeneralPostingSetup.SetRange("Sales Prepayments Account", "No.");
?? ?? ?? ?? if GeneralPostingSetup.FindSet() then
?? ?? ?? ?? ?? ?? repeat
?? ?? ?? ?? ?? ?? ?? ?? GeneralPostingSetup.CheckPrepmtSalesLinesToDeduct(
?? ?? ?? ?? ?? ?? ?? ?? ?? ?? StrSubstNo(CannotChangeSetupOnPrepmtAccErr, '%1', FldCaption, "No."));
?? ?? ?? ?? ?? ?? until GeneralPostingSetup.Next() = 0;
?? ?? end;
?? ?? //

?? ?? [IntegrationEvent(true, false)]
?? ?? local procedure OnBeforeCheckSalesOrdersPrepmtToDeduct(var GLAccount: Record "G/L Account"; var IsHandled: Boolean)
?? ?? begin
?? ?? end;
?? ?? //

Thanks in advance
Christina

### Additional context

The new event is necessary to realize own checks for Sales Orders
Internal work item: [AB#559353](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559353)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27697.
