### ISSUE TITLE
[Bug]: The author of the "Subscription Billing"-module is present in internalsVisibleTo of app.json

### ISSUE THREAD

**Issue by joandrsn** [microsoft/ALAppExtensions#27727]
### Describe the issue

The original author of the subscription billing module is present in `internalsVisibleTo`-structure of the `app.json`.
https://github.com/microsoft/ALAppExtensions/blob/194511817157c0328de0ddccd81118373aec1041/Apps/W1/SubscriptionBilling/App/app.json#L16-L26

### Expected behavior

That only tests are present in the internalsVisibleTo-structure.

### Steps to reproduce

Look at app.json

### Additional context

This could give an advantage to that partner. Other partners do not have access to the internals.

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Indeed a known issue (reference: AB#555170). In general, the app is still "work in progress". It will get improved in the coming months.
