### ISSUE TITLE
[Event Request] Codeunit 57 "Document Totals" - OnBeforePurchaseCalculateTotalsNoRounding

### ISSUE THREAD

**Issue by skuchana93** [microsoft/ALAppExtensions#27739]
### Describe the request

In Codeunit 57, please include the OnBeforePurchaseCalculateTotalsNoRounding event within the PurchaseCalculateTotalsNoRounding procedure.

**Actual Code:**
procedure PurchaseCalculateTotalsNoRounding(var TempCurrentPurchaseLine: Record "Purchase Line"; var VATAmount: Decimal; var TempTotalPurchaseLine: Record "Purchase Line"; var TaxAreaCode: Code[20])
    var
        PurchaseLine: Record "Purchase Line";
    begin
        Clear(TempTotalPurchaseLine);
        PurchaseLine.SetRange("Document Type", TempCurrentPurchaseLine."Document Type");
        PurchaseLine.SetRange("Document No.", TempCurrentPurchaseLine."Document No.");
        if PurchaseLine.FindSet() then
            repeat
                if ((PurchaseLine."Tax Group Code" = '') or
                   ((PurchaseLine."Tax Area Code" = '') and (TaxAreaCode <> '')))
                then begin
                    TempTotalPurchaseLine.Amount += (PurchaseLine."Line Amount" - PurchaseLine."Inv. Discount Amount");
                    TempTotalPurchaseLine."Inv. Discount Amount" += PurchaseLine."Inv. Discount Amount";
                    TempTotalPurchaseLine."Amount Including VAT" += (PurchaseLine."Line Amount" - PurchaseLine."Inv. Discount Amount");
                end else begin
                    TempTotalPurchaseLine.Amount += PurchaseLine.Amount;
                    TempTotalPurchaseLine."Inv. Discount Amount" += PurchaseLine."Inv. Discount Amount";
                    TempTotalPurchaseLine."Amount Including VAT" += PurchaseLine."Amount Including VAT";
                end
            until PurchaseLine.Next() = 0;
        VATAmount := TempTotalPurchaseLine."Amount Including VAT" - TempTotalPurchaseLine.Amount;
    end;

**Required code with a new event request:**
procedure PurchaseCalculateTotalsNoRounding(var TempCurrentPurchaseLine: Record "Purchase Line"; var VATAmount: Decimal; var TempTotalPurchaseLine: Record "Purchase Line"; var TaxAreaCode: Code[20])
    var
        PurchaseLine: Record "Purchase Line";
        **IsHandled: Boolean;**
    begin
        **IsHandled := false;
        OnBeforePurchaseCalculateTotalsNoRounding(TempCurrentPurchaseLine, VATAmount, TempTotalPurchaseLine, TaxAreaCode, IsHandled);
        if IsHandled then
        exit;**
        Clear(TempTotalPurchaseLine);
        PurchaseLine.SetRange("Document Type", TempCurrentPurchaseLine."Document Type");
        PurchaseLine.SetRange("Document No.", TempCurrentPurchaseLine."Document No.");
        if PurchaseLine.FindSet() then
            repeat
                if ((PurchaseLine."Tax Group Code" = '') or
                   ((PurchaseLine."Tax Area Code" = '') and (TaxAreaCode <> '')))
                then begin
                    TempTotalPurchaseLine.Amount += (PurchaseLine."Line Amount" - PurchaseLine."Inv. Discount Amount");
                    TempTotalPurchaseLine."Inv. Discount Amount" += PurchaseLine."Inv. Discount Amount";
                    TempTotalPurchaseLine."Amount Including VAT" += (PurchaseLine."Line Amount" - PurchaseLine."Inv. Discount Amount");
                end else begin
                    TempTotalPurchaseLine.Amount += PurchaseLine.Amount;
                    TempTotalPurchaseLine."Inv. Discount Amount" += PurchaseLine."Inv. Discount Amount";
                    TempTotalPurchaseLine."Amount Including VAT" += PurchaseLine."Amount Including VAT";
                end
            until PurchaseLine.Next() = 0;
        VATAmount := TempTotalPurchaseLine."Amount Including VAT" - TempTotalPurchaseLine.Amount;
    end;

**[IntegrationEvent(false, false)]
local procedure OnBeforePurchaseCalculateTotalsNoRounding(var TempCurrentPurchaseLine: Record "Purchase Line"; var VATAmount: Decimal; var TempTotalPurchaseLine: Record "Purchase Line"; var TaxAreaCode: Code[20]; var IsHandled: Boolean)
begin
end;**

### Additional context

This new event is necessary to enable subscription for implementing custom code and to provide the option to bypass the base code when needed.
Internal work item: [AB#559361](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559361)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27959.
