### ISSUE TITLE
[Event Request] Codeunit 57 "Document Totals" - OnBeforePurchaseUpdateTotals

### ISSUE THREAD

**Issue by skuchana93** [microsoft/ALAppExtensions#27738]
### Describe the request

In Codeunit 57, please include the OnBeforePurchaseUpdateTotals event within the PurchaseUpdateTotals procedure.

**Actual Code:**
    local procedure PurchaseUpdateTotals(var PurchaseHeader: Record "Purchase Header"; CurrentPurchaseLine: Record "Purchase Line"; var TotalsPurchaseLine: Record "Purchase Line"; var VATAmount: Decimal; Force: Boolean): Boolean
    begin
        PurchaseHeader.CalcFields(Amount, "Amount Including VAT", "Invoice Discount Amount");
        if (PreviousTotalPurchaseHeader.Amount = PurchaseHeader.Amount) and
           (PreviousTotalPurchaseHeader."Amount Including VAT" = PurchaseHeader."Amount Including VAT") and
           (PreviousTotalPurchVATDifference = CalcTotalPurchVATDifference(PurchaseHeader))
        then
            exit(true);
        if not Force then
            if not PurchaseCheckNumberOfLinesLimit(PurchaseHeader) then
                exit(false);
        if not PurchaseHeader."Tax Liable" then
            PurchaseCalculateTotalsWithInvoiceRounding(CurrentPurchaseLine, VATAmount, TotalsPurchaseLine)
        else
            PurchaseCalculateTotalsNoRounding(CurrentPurchaseLine, VATAmount, TotalsPurchaseLine, PurchaseHeader."Tax Area Code");
        exit(true);
    end;

**Required code with new event request.**
local procedure PurchaseUpdateTotals(var PurchaseHeader: Record "Purchase Header"; CurrentPurchaseLine: Record "Purchase Line"; var TotalsPurchaseLine: Record "Purchase Line"; var VATAmount: Decimal; Force: Boolean): Boolean
    var
    **IsHandled: Boolean;
    Result: Boolean;**
    begin
        **IsHandled := false;
        OnBeforePurchaseUpdateTotals(PurchaseHeader, PreviousTotalPurchaseHeader, CurrentPurchaseLine, TotalsPurchaseLine, VATAmount, Force, IsHandled, Result);
        if IsHandled then
        exit(Result);**
        PurchaseHeader.CalcFields(Amount, "Amount Including VAT", "Invoice Discount Amount");
        if (PreviousTotalPurchaseHeader.Amount = PurchaseHeader.Amount) and
           (PreviousTotalPurchaseHeader."Amount Including VAT" = PurchaseHeader."Amount Including VAT") and
           (PreviousTotalPurchVATDifference = CalcTotalPurchVATDifference(PurchaseHeader))
        then
            exit(true);
        if not Force then
            if not PurchaseCheckNumberOfLinesLimit(PurchaseHeader) then
                exit(false);
        if not PurchaseHeader."Tax Liable" then
            PurchaseCalculateTotalsWithInvoiceRounding(CurrentPurchaseLine, VATAmount, TotalsPurchaseLine)
        else
            PurchaseCalculateTotalsNoRounding(CurrentPurchaseLine, VATAmount, TotalsPurchaseLine, PurchaseHeader."Tax Area Code");
        exit(true);
    end;

**[IntegrationEvent(false, false)]
    local procedure OnBeforePurchaseUpdateTotals(var PurchaseHeader: Record "Purchase Header"; var PreviousTotalPurchaseHeader: Record "Purchase Header"; CurrentPurchaseLine: Record "Purchase Line"; var TotalsPurchaseLine: Record "Purchase Line"; var VATAmount: Decimal; Force: Boolean; var IsHandled: Boolean; var Result: Boolean)
    begin
    end;**

### Additional context

This new event is necessary to enable subscription for implementing custom code and to provide the option to bypass the base code when needed.
Internal work item: [AB#559362](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559362)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27959.
