### ISSUE TITLE
[Events Request] Page 99000883 "Sales Order Planning" - OnCreateOrdersOnBeforeFindSet and OnCreateOrdersOnBeforeCreateProdOrder event changes

### ISSUE THREAD

**Issue by MasterBasketWeaver** [microsoft/ALAppExtensions#27731]
### Describe the request

Hello,

I'm requesting several events on Page 99000883 "Sales Order Planning" be changed to include additional parameters for more extensible and granular control.

**OnCreateOrdersOnBeforeFindSet**

Current:

```
OnCreateOrdersOnBeforeFindSet(Rec);
if not Rec.FindSet() then
    exit;
```

Requested:

```
OnCreateOrdersOnBeforeFindSet(Rec, IsHandled, OrdersCreated);
if IsHandled or not Rec.FindSet() then
    exit;
```

**OnCreateOrdersOnBeforeCreateProdOrder**

Current:
```
OnCreateOrdersOnBeforeCreateProdOrder(Rec, SalesLine, IsHandled);
if IsHandled then
    exit;
if SalesLine."Outstanding Qty. (Base)" > SalesLine."Reserved Qty. (Base)" then begin
    // code
end;
```

Requested:
```
OnCreateOrdersOnBeforeCreateProdOrder(Rec, SalesLine, IsHandled, OrdersCreated, EndLoop);
if not IsHandled then
    if SalesLine."Outstanding Qty. (Base)" > SalesLine."Reserved Qty. (Base)" then begin
        // code
    end;
```

Thank you.

### Additional context

Currently there is no way to override the functionality to display a message in the CreateProdOrder() function on line 553. By updating the OnCreateOrdersOnBeforeFindSet publisher to include the OrdersCreated variable the message display could be controlled via extensions.

Changing OnCreateOrdersOnBeforeCreateProdOrder to skip a specific block of code instead of exiting the function gives more granular control to allow specific Production Orders to be skipped, instead of handling the entire creation process.
Internal work item: [AB#559358](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559358)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27687.
