### ISSUE TITLE
Codeunit 7000 "Sales Price Calc. Mgt." - OnCalcBestUnitPriceOnAfterCalcBestUnitPriceConvertPrice

### ISSUE THREAD

**Issue by skuchana93** [microsoft/ALAppExtensions#27733]
### Describe the request

In codeunit 7000, please include the **OnCalcBestUnitPriceOnAfterCalcBestUnitPriceConvertPrice** event within the **CalcBestUnitPrice** procedure.

**Actual Code:**
procedure CalcBestUnitPrice(var SalesPrice: Record "Sales Price")
    var
        BestSalesPrice: Record "Sales Price";
        BestSalesPriceFound: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeCalcBestUnitPrice(SalesPrice, IsHandled);
        if IsHandled then
            exit;
        FoundSalesPrice := SalesPrice.FindSet();
        if FoundSalesPrice then
            repeat
                IsHandled := false;
                OnCalcBestUnitPriceOnBeforeCalcBestUnitPriceConvertPrice(SalesPrice, Qty, IsHandled);
                if not IsHandled then
                    if IsInMinQty(SalesPrice."Unit of Measure Code", SalesPrice."Minimum Quantity") then begin
                        CalcBestUnitPriceConvertPrice(SalesPrice);
                        case true of
                            ((BestSalesPrice."Currency Code" = '') and (SalesPrice."Currency Code" <> '')) or
                            ((BestSalesPrice."Variant Code" = '') and (SalesPrice."Variant Code" <> '')):
                                begin
                                    BestSalesPrice := SalesPrice;
                                    BestSalesPriceFound := true;
                                end;
                            ((BestSalesPrice."Currency Code" = '') or (SalesPrice."Currency Code" <> '')) and
                          ((BestSalesPrice."Variant Code" = '') or (SalesPrice."Variant Code" <> '')):
                                if (BestSalesPrice."Unit Price" = 0) or
                                   (CalcLineAmount(BestSalesPrice) > CalcLineAmount(SalesPrice))
                                then begin
                                    BestSalesPrice := SalesPrice;
                                    BestSalesPriceFound := true;
                                end;
                        end;
                    end;
            until SalesPrice.Next() = 0;
        OnAfterCalcBestUnitPrice(SalesPrice, BestSalesPrice);
        // No price found in agreement
        if not BestSalesPriceFound then begin
            ConvertPriceToVAT(
              Item."Price Includes VAT", Item."VAT Prod. Posting Group",
              Item."VAT Bus. Posting Gr. (Price)", Item."Unit Price");
            ConvertPriceToUoM('', Item."Unit Price");
            ConvertPriceLCYToFCY('', Item."Unit Price");
            Clear(BestSalesPrice);
            BestSalesPrice."Unit Price" := Item."Unit Price";
            BestSalesPrice."Allow Line Disc." := AllowLineDisc;
            BestSalesPrice."Allow Invoice Disc." := AllowInvDisc;
            OnAfterCalcBestUnitPriceAsItemUnitPrice(BestSalesPrice, Item);
        end;
        SalesPrice := BestSalesPrice;
    end;

**Required code with a new event:**
procedure CalcBestUnitPrice(var SalesPrice: Record "Sales Price")
    var
        BestSalesPrice: Record "Sales Price";
        BestSalesPriceFound: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeCalcBestUnitPrice(SalesPrice, IsHandled);
        if IsHandled then
            exit;
        FoundSalesPrice := SalesPrice.FindSet();
        if FoundSalesPrice then
            repeat
                IsHandled := false;
                OnCalcBestUnitPriceOnBeforeCalcBestUnitPriceConvertPrice(SalesPrice, Qty, IsHandled);
                if not IsHandled then
                    if IsInMinQty(SalesPrice."Unit of Measure Code", SalesPrice."Minimum Quantity") then begin
                        CalcBestUnitPriceConvertPrice(SalesPrice);
                        case true of
                            ((BestSalesPrice."Currency Code" = '') and (SalesPrice."Currency Code" <> '')) or
                            ((BestSalesPrice."Variant Code" = '') and (SalesPrice."Variant Code" <> '')):
                                begin
                                    BestSalesPrice := SalesPrice;
                                    BestSalesPriceFound := true;
                                end;
                            ((BestSalesPrice."Currency Code" = '') or (SalesPrice."Currency Code" <> '')) and
                          ((BestSalesPrice."Variant Code" = '') or (SalesPrice."Variant Code" <> '')):
                                if (BestSalesPrice."Unit Price" = 0) or
                                   (CalcLineAmount(BestSalesPrice) > CalcLineAmount(SalesPrice))
                                then begin
                                    BestSalesPrice := SalesPrice;
                                    BestSalesPriceFound := true;
                                end;
                        end;
                    end;
           **OnCalcBestUnitPriceOnAfterCalcBestUnitPriceConvertPrice(SalesPrice, BestSalesPrice, Item, Qty);**
            until SalesPrice.Next() = 0;
        OnAfterCalcBestUnitPrice(SalesPrice, BestSalesPrice);
        // No price found in agreement
        if not BestSalesPriceFound then begin
            ConvertPriceToVAT(
              Item."Price Includes VAT", Item."VAT Prod. Posting Group",
              Item."VAT Bus. Posting Gr. (Price)", Item."Unit Price");
            ConvertPriceToUoM('', Item."Unit Price");
            ConvertPriceLCYToFCY('', Item."Unit Price");
            Clear(BestSalesPrice);
            BestSalesPrice."Unit Price" := Item."Unit Price";
            BestSalesPrice."Allow Line Disc." := AllowLineDisc;
            BestSalesPrice."Allow Invoice Disc." := AllowInvDisc;
            OnAfterCalcBestUnitPriceAsItemUnitPrice(BestSalesPrice, Item);
        end;
        SalesPrice := BestSalesPrice;
    end;

**[IntegrationEvent(false, false)]
    local procedure OnCalcBestUnitPriceOnAfterCalcBestUnitPriceConvertPrice(var SalesPrice: Record "Sales Price"; var BestSalesPrice: Record "Sales Price"; var Item: Record Item; Qty: Decimal)
    begin
    end;**

### Additional context

This new event is necessary to enable subscription for implementing custom code and to provide the option to bypass the base code when needed.
Internal work item: [AB#559363](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559363)

**Comment by JakovljevicDusan** [comment]
As an alternative, parameter Item is added to OnCalcBestUnitPriceOnBeforeCalcBestUnitPriceConvertPrice. Please use this publisher.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27687.
