### ISSUE TITLE
[Extensibility Request] Report 698 "Get Sales Orders" Add a new function SetHideDialog

### ISSUE THREAD

**Issue by elweilando** [microsoft/ALAppExtensions#27746]
### Describe the request

With https://github.com/microsoft/ALAppExtensions/issues/13078, the report Report 698 "Get Sales Orders" has been extended, so that an event can be used to control whether the dialog can be displayed. 

The disadvantage, however, is that as soon as the user executes the report manually in the Req. worksheet, the event also takes effect there.

A useful feature would be to make it possible to set HideDialog via a dedicated function. This would allow the object to be defined more precisely in a custom batch process without interrupting the information for the user when executing it manually.

```
   procedure SetHideDialog(NewHideDialog: Boolean)
    begin
        HideDialog := NewHideDialog;
    end;
```

### Additional context

We have currently automated the creation of direct purchase orders for a customer. However, the job queue always runs into errors because of this message if there are no corresponding lines that can be pulled via GetOrders. 
Although the existing event would prevent this message, it would also generally no longer produce a message if the user executes the process manually.

Since we have to instantiate GetOrder at this point anyway, it would be more targeted to be able to set only via the HideDialog function.
Internal work item: [AB#559869](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559869)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
