### ISSUE TITLE
[Event Request] Page 973 "Time Sheet Card" & Page 953 "Manager Time Sheet List" - OnOpenPage trigger

### ISSUE THREAD

**Issue by massnicolas19** [microsoft/ALAppExtensions#27747]
### Describe the request

Hi team,

We need a new trigger to implement my custom code in OnOpenPage() triggers of "Time Sheet Card" & "Manager Time Sheet List" pages. 
You will find a code suggestion below.

**Page 973 "Time Sheet Card" :**

```
trigger OnOpenPage()
var
    IsHandled: Boolean;    
 begin
        IsHandled := false;
        OnBeforeOnOpenPage(Rec, IsHandled);
        if IsHandled then
            exit;

        CheckSetDefaultOwnerFilter();
        RemoveFilterFromLinesExistField();

        OnAfterOnOpenPage(Rec);
 end;
```
```
[IntegrationEvent(false, false)]
    local procedure OnBeforeOnOpenPage(var TimeSheetHeader: Record "Time Sheet Header"; var IsHandled: Boolean);
    begin
    end;
```

**Page 953 "Manager Time Sheet List" :** 

```
trigger OnOpenPage()
var
    IsHandled: Boolean;     
begin
       IsHandled := false;
       OnBeforeOnOpenPage(Rec, IsHandled);
       if IsHandled then
            exit;

        TimeSheetAdminActionsVisible := true;
        if UserSetup.Get(UserId) then
            CurrPage.Editable := UserSetup."Time Sheet Admin.";
        TimeSheetAdminActionsVisible := UserSetup."Time Sheet Admin.";

        TimeSheetMgt.FilterTimeSheets(Rec, Rec.FieldNo("Approver User ID"));

        OnAfterOnOpenPage(Rec);
 end;
```
```
[IntegrationEvent(false, false)]
    local procedure OnBeforeOnOpenPage(var TimeSheetHeader: Record "Time Sheet Header"; var IsHandled: Boolean);
    begin
    end;
```

Thanks in advance for your help.

### Additional context

We wrote a custom development for Delegation of Timesheet and the current code does not allow us to open the page when the current user is not "Time Sheet Admin". We would like to override this standard check.  

We also need to add new filters on "Manager Time Sheet List" page. 
Internal work item: [AB#559855](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559855)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27959.
