### ISSUE TITLE
[Bug]: UI bug in BC25  when searching in related tables, the "Select from full list" buttons are displayed with needing to scroll further for Ukrainian language interface

### ISSUE THREAD

**Issue by SerhiiKorniichuk1** [microsoft/ALAppExtensions#27754]
### Describe the issue

Hello, a bug has been detected in the UI.
When working with the Ukrainian language in the new version, the layout has shifted, specifically, the buttons have disappeared. They can only be found by scrolling down.
![Image](https://github.com/user-attachments/assets/c26c8a33-d2a3-4d2e-8fa1-1c6972c82b44)

### Expected behavior

When searching in related tables, the "Select from full list" buttons are displayed without needing to scroll further as in BC24.

### Steps to reproduce

searching in related tables

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
