### ISSUE TITLE
[Scope Change] Table - "Cash Flow Worksheet Line" 846

### ISSUE THREAD

**Issue by simonela93** [microsoft/ALAppExtensions#27759]
### Describe the request

Please remove the scope OnPrem for procedure ShowSource in Cash Flow Worksheet Line table. This does not make any sense because the function can be used also in the BC Online version.

Thanks in advance,
Simone Laboranti

### Additional context

I need to use this function in a extension.
Internal work item: [AB#559842](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559842)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 28254.
