### ISSUE TITLE
[Event Request] Report 99001043 Exchange Production BOM Item - Trigger OnPreReport - OnAfterCheckParameters

### ISSUE THREAD

**Issue by mavohra** [microsoft/ALAppExtensions#27768]
### Describe the request

Please add an Event OnAfterCheckParameters in trigger OnPreReport, at the end of CheckParameters() procedure. 
It is in Report 99001043 "Exchange Production BOM Item"

 ```
 local procedure CheckParameters()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckParameters(StartingDate, FromBOMType, FromBOMNo, ToBOMType, ToBOMNo, IsHandled);
        if IsHandled then
            exit;

        if StartingDate = 0D then
            Error(Text000);

        if FromBOMType = FromBOMType::" " then
            Error(Text001);

        if FromBOMNo = '' then
            Error(Text002);

        if (FromBOMType = ToBOMType) and (FromBOMNo = ToBOMNo) then
            Error(ItemBOMExchangeErr, FromBOMType, FromBOMNo, ToBOMType, ToBOMNo);
    end;
     OnAfterCheckParameters(FromBOMType, ToBOMType, FromBOMNo, ToBOMNo); // <------ NEW EVENT
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterCheckParameters(var FromBOMType: Enum "BOM Type"; var ToBOMType: Enum "BOM Type"; var FromBOMNo: Code[20]; var ToBOMNo: Code[20])
begin
end;
```

### Additional context

I want this event so that i can add my customization AFTER the checkparameter procedure is called. 
Internal work item: [AB#559831](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559831)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27959.
