### ISSUE TITLE
[Scope Change] Page - "Check Credit Limit" 343

### ISSUE THREAD

**Issue by simonela93** [microsoft/ALAppExtensions#27763]
### Describe the request

Please remove the scope OnPrem for procedure SalesHeaderShowWarningAndGetCause in Check Credit Limit Page. This does not make any sense because the function can be used also in the BC Online version.

Thanks in advance,
Simone Laboranti

### Additional context

I need to use this function in a extension.
Internal work item: [AB#559834](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559834)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
