### ISSUE TITLE
[Bug]: Custom Page in Profile BC24

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#27767]
### Describe the issue

Hi Team,

While customizing the JF Purchasing Agent 2 profile, I've accidently moved the Lines fast tab from right below the General fast tab to above the General fast tab on both these screens.  I need these both reversed back as it will not allow me to move them.  The way it happened is I was attempting to highlight a cell to copy and as I did that the lines jumped to the top both times it happened.  This seems like a bug of some sort.  I was using the Chrome browser both times if that is of any importance.

please find the attachedhttps://github.com/user-attachments/assets/265fc354-64d4-45f0-9fab-5a564cace78f
 video

### Expected behavior

while doing the personalize design in Custom page in profile, it should be Line tab under General tab. 

### Steps to reproduce

Please find the attached video to reproduce the issue

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
