### ISSUE TITLE
[Event Request] Codeunit 7043 - Price Asset - Resource - OnAfterFillBestLine

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#27770]
### Describe the request

Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterFillBestLine` to be added to Codeunit 7043 Price Asset - Resource to be corrected to the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillBestLine(PriceCalculationBuffer: Record "Price Calculation Buffer"; AmountType: Enum "Price Amount Type"; var PriceListLine: Record "Price List Line" temporary)
    begin
    end;
```

which would be called as follows from `FillBestLine`:
```al

```

### Additional context

Because the event publisher is called with a temporary "Price List Line" record, temporary should be added to the the PriceListLine parameter. Our CodeCop is complaining about this.
Internal work item: [AB#559830](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/559830)

**Comment by JakovljevicDusan** [comment]
We cannot do this, because it can be breaking change since procedure could be called with non-temporary record. In other codeunits similar event OnAfterFillBestLine is also without temporary.
