### ISSUE TITLE
Codeunit 9856 "Permission Set Relation Impl." from internal to public

### ISSUE THREAD

**Issue by Elio-Cometto-EOS** [microsoft/ALAppExtensions#27776]
### Describe the request

Change the access level of Codeunit 9856 "Permission Set Relation Impl." from **internal** to **public**

### Additional context

Could you make the Codeunit 9856 "Permission Set Relation Impl." public instead of with access = internal?
I need to use the procedure **RefreshPermissionSetTree** to check which direct and nested permissions are assigned to a specific user. 
I cannot replicate the functionality because some DotNet variables are used.

Thank you in advance for your support.

**Comment by nikolakukrika** [comment]
@Elio-Cometto-EOS Impl. codeunits contain the private methods that are never ever going to be made public. 
You have a facade codeunit that is exposing the functionality. 

Please go to the BCApps repo and open an issue to add RefreshPermissionSetTree to the public interface. If it gets approved you can contribute to the codebase and create a PR to extend the public facade.
