### ISSUE TITLE
[Request for External] Page 354 Item Turnover Lines - make local proc public - ShowValueEntries

### ISSUE THREAD

**Issue by KaMu0608** [microsoft/ALAppExtensions#27789]
### Describe the request

Could you please change the local procedure ShowValueEntries in the page 354 Item Turnover Lines to public.
You already did that for the procedure ShowItemEntries.
Thank you

### Additional context

We want to call the function from our extension.
Internal work item: [AB#560514](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560514)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
