### ISSUE TITLE
[Event Request] Сodeunit 7314 "Warehouse Availability Mgt." - procedure CalcQtyOutstandingPick

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#27780]
### Describe the request

We need the following event in order to be able to remove some filters from WarehouseActivityLine:

      local procedure CalcQtyOutstandingPick(SourceType: Integer; SourceSubType: Option; SourceID: Code[20]; SourceRefNo: Integer; SourceProdOrderLine: Integer; var WarehouseActivityLine: Record "Warehouse Activity Line"): Decimal
          var
              WhseActivityLine: Record "Warehouse Activity Line";
          begin
              if SourceType = Database::"Prod. Order Component" then
                  WhseActivityLine.SetSourceFilter(SourceType, SourceSubType, SourceID, SourceProdOrderLine, SourceRefNo, true)
              else
                  WhseActivityLine.SetSourceFilter(SourceType, SourceSubType, SourceID, SourceRefNo, -1, true);
              WhseActivityLine.SetFilter("Action Type", '%1|%2', WhseActivityLine."Action Type"::Take, WhseActivityLine."Action Type"::" ");
              OnCalcQtyOutstandingPickOnAfterSetFilters(WhseActivityLine, SourceType, SourceSubType, SourceID, SourceRefNo, SourceProdOrderLine);
      
              WhseActivityLine.CalcSums("Qty. Outstanding (Base)");
      
              // For not yet committed warehouse activity lines
              WarehouseActivityLine.CopyFilters(WhseActivityLine);
              WarehouseActivityLine.CalcSums("Qty. Outstanding (Base)");
              // new event begin
              OnCalcQtyOutstandingPickOnAfterCalcSums(WarehouseActivityLine, WhseActivityLine);
              // new event end
              exit(WhseActivityLine."Qty. Outstanding (Base)" + WarehouseActivityLine."Qty. Outstanding (Base)");
          end;

      // new event publisher:
      [IntegrationEvent(false, false)]
          local procedure OnCalcQtyOutstandingPickOnAfterCalcSums(var WarehouseActivityLine: Record "Warehouse Activity Line"; var WhseActivityLine: Record "Warehouse Activity Line");
          begin
          end;

### Additional context

We had a problem with multi-order picking in combination with break bulk. The warehouse shipment document contains lines for picking an item for different sales orders in base unit of measure. The item was available in a "bigger" unit of measure on the bin. 
The system has created pick lines for each warehouse shipment line in such a way that there is always a breakbulk. However, a single breakbulk would have been sufficient to pick the complete quantity of the item. From our point of view, the problem is that the filter on the source document is not removed from WarehouseActivityLine at the end of the above-mentioned function. This is why we need the event, among other things. 
However, if the behavior is indeed a bug, it would of course be desirable for this to be fixed as well.

Internal work item: [AB#560228](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560228)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27959.
