### ISSUE TITLE
[Change Request][BE Localization] page 31 "Item List" - TempFilterItemAttributesBuffer, TempItemFilteredFromAttributes

### ISSUE THREAD

**Issue by LukeJiricek** [microsoft/ALAppExtensions#27791]
### Describe the request

Hello,
on behalf of our team at Prodware Czech Republic, I would like to request the following variables to be made accessible as protected var:

**TempFilterItemAttributesBuffer**: Record "Filter Item Attributes Buffer" temporary;
**TempItemFilteredFromAttributes**: Record Item temporary;

### Additional context

These variables are needed in our custom app. Thank you.
Internal work item: [AB#560511](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560511)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28358.
