### ISSUE TITLE
Request: Enable Keys in Item Ledger Entry Table

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/ALAppExtensions#278]
Transfer feature is not working right now.
Transferring manually from AL GitHub: https://github.com/Microsoft/AL/issues/1285

Would it be possible to enable the "Serial No." and "Lot No." keys in the Item Ledger Entry Table please? Currently they are disabled by default and our product relies on them.
Thanks

**Comment by JesperSchulz** [comment]
I will enable the keys in our base application.
