### ISSUE TITLE
[Change Request] Delete [Scope('OnPrem')] from procedure InitializeRequest, report 94 "Close Income Statement"

### ISSUE THREAD

**Issue by TarasKozachenko** [microsoft/ALAppExtensions#27802]
### Describe the request

Delete [Scope('OnPrem')] from procedure InitializeRequest, report 94 "Close Income Statement", because it doesn't look right.
It should be the same as in procedure InitializeRequestTest.

    [Scope('OnPrem')]
    procedure InitializeRequest(EndDateReq2: Date; GenJnlTemplate2: Code[10]; GenJnlBatchName2: Code[10]; DocNo2: Code[10]; PostingDescription2: Text[50]; ClosePerBusUnit2: Boolean; ClosePerDept2: Boolean; ClosePerProj2: Boolean; RetainedAccNo: Code[20])
    begin
        EndDateReq := EndDateReq2;
        GenJnlLine."Journal Template Name" := GenJnlTemplate2;
        GenJnlLine."Journal Batch Name" := GenJnlBatchName2;
        DocNo := DocNo2;
        PostingDescription := PostingDescription2;
        ClosePerBusUnit := ClosePerBusUnit2;
        ClosePerGlobalDim1 := ClosePerDept2;
        ClosePerGlobalDim2 := ClosePerProj2;
        RetainedEarningsGLAcc."No." := RetainedAccNo;
    end;

    >>>>>>>>>>>>>
    procedure InitializeRequest(EndDateReq2: Date; GenJnlTemplate2: Code[10]; GenJnlBatchName2: Code[10]; DocNo2: Code[10]; PostingDescription2: Text[50]; ClosePerBusUnit2: Boolean; ClosePerDept2: Boolean; ClosePerProj2: Boolean; RetainedAccNo: Code[20])
    begin
    <<<<<<<<<<<<

### Additional context

We need to pass parameters before executing the report, but this parameter does not give us this opportunity.
Internal work item: [AB#560500](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560500)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 28271.
