### ISSUE TITLE
[Bug]: Allow Creation of Shopify Sales Orders without updating Shopify

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/ALAppExtensions#27807]
### Describe the issue

Currently it is not possible to create a sales order from a Shopify Order, without BC updating the order in Shopify. 
For Production environments this makes sense.
However, it prohibits the ability to do copies of production and reproduce scenarios in a Sandbox without impacting production Shopify.

I would like to make the update to shopify dependent on the setting "Allow Outgoing Requests" on the Shopify Shop.

Under the current solution, if "Allow Outgoing Requests" is disabled, all sales order creation will fail.

### Expected behavior

If Allow Outgoing Requests is enabled, the update to shopify should happen.
If Allow Outgoing Requests is disabled, the sales order should be created, but shopify should not be updated.

### Steps to reproduce

1. Import Shopify Order
2. Disable "Allow Outgoing Requests"
3. Try to create sales order

### Additional context

Andrei have already given the green light on Viva Engange

![Image](https://github.com/user-attachments/assets/61d3e3ea-b336-4b04-959c-f984b5ff96c5)

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by onbuyuka** [comment]
We will fix this by adding a new setting on shop card "Add Business Central Doc. No. as Attribute"
