### ISSUE TITLE
Remove "Internal" from Shpfy Order API.CancelOrder procedure

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/ALAppExtensions#27805]
### Describe the request

I would like to get the "Internal" removed for the function CancelOrder in codeunit Shpfy Orders API. 
This will allow us to automatically cancel orders in Shopify based on actions in BC.

![Image](https://github.com/user-attachments/assets/be0f1a5c-3f7d-49ab-9e91-848aa41ed829)

### Additional context

I have a customer requesting an automated Cancel order flow initiated from their WMS.
Scenario is:

1. Warehouse employee deletes order in WMS with specific reason code.
2. Sales Order in BC is deleted through API request from WMS
3. On delete of Sales Order by WMS cancel order in Shopify

This would be fairly easy to do if just the CancelOrder procedure was not marked as internal

**Comment by AndreiPanko** [comment]
We haven't figured out the extensibility model for functions yet. See conversation on VivaEngage https://www.yammer.com/dynamicsnavdev/threads/2724989901758464

Thanks,
Andrei Panko
PM, Microsoft
