### ISSUE TITLE
[Change Request] Delete [Scope('OnPrem')] from procedure SetHidePrintDialog, codeunit 6 "Fiscal Year-Close"

### ISSUE THREAD

**Issue by TarasKozachenko** [microsoft/ALAppExtensions#27801]
### Describe the request

Delete [Scope('OnPrem')] from procedure SetHidePrintDialog, codeunit 6 "Fiscal Year-Close", because it doesn't look right.

**[Scope('OnPrem')]**
procedure SetHidePrintDialog(NewHidePrintDialog: Boolean)
begin
    HidePrintDialog := NewHidePrintDialog;
end;

.>>>>>>>>>>>>
procedure SetHidePrintDialog(NewHidePrintDialog: Boolean)
<<<<<<<<<<<<
begin
    HidePrintDialog := NewHidePrintDialog;
end;

### Additional context

We need to hide the dialog box, but we can't do it because of the "[Scope('OnPrem')]" parameter.
Internal work item: [AB#560501](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560501)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 28271.
