### ISSUE TITLE
[Change Request] Delete [Scope('OnPrem')] from procedure SetHidePrintDialog, report 7000080 "Post Payment Order"

### ISSUE THREAD

**Issue by TarasKozachenko** [microsoft/ALAppExtensions#27803]
### Describe the request

Delete [Scope('OnPrem')] from procedure SetHidePrintDialog, report 7000080 "Post Payment Order", because it doesn't look right.

    [Scope('OnPrem')]
    procedure SetHidePrintDialog(NewHidePrintDialog: Boolean)
    begin
        HidePrintDialog := NewHidePrintDialog;
    end;

    >>>>>>>>>>>>
    procedure SetHidePrintDialog(NewHidePrintDialog: Boolean)
    <<<<<<<<<<<<
    begin
        HidePrintDialog := NewHidePrintDialog;
    end;

### Additional context

We need to hide the dialog box, but we can't do it because of the "[Scope('OnPrem')]" parameter.
Internal work item: [AB#560498](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560498)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
