### ISSUE TITLE
[Event Request] table 7005 "Price Source" - OnAfterFilterPriceLines

### ISSUE THREAD

**Issue by PetroKharchenko** [microsoft/ALAppExtensions#27809]
### Describe the request

Please implement an event in table 7005, "Price Source", to apply additional filtering logic after the initial filters on Price Source have been applied:
1. Add a publisher method: OnAfterFilterPriceLines.
2. Modify the procedure FilterPriceLines to include a call to the added publisher method.

Code example:
```
table 7005 "Price Source"
{

...

    procedure FilterPriceLines(var PriceListLine: Record "Price List Line") Result: Boolean;
    begin
        PriceListLine.SetRange("Source Type", "Source Type");
        if IsSourceNoAllowed() then begin
            if "Source No." = '' then
                exit;

            PriceListLine.SetRange("Source No.", "Source No.");
            if "Parent Source No." <> '' then
                PriceListLine.SetRange("Parent Source No.", "Parent Source No.");
        end else
            PriceListLine.SetRange("Source No.");
        // requested change >>
        OnAfterFilterPriceLines(Rec, PriceListLine);
        // requested change <<
    end;

...

    // requested change >>
    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterPriceLines(PriceSource: Record "Price Source"; var PriceListLine: Record "Price List Line")
    begin
    end;
    // requested change <<
	
}
```

### Additional context

The Price Lists functionality is quite extensible from the side of Price Asset, but has limited extensibility from the side of Price Sources. For instance, the filtering of Price List Line records on Price Asset is implemented as a method in the Price Asset interface, allowing customizations by adding custom implementations of this interface. On the other hand, filtering of Price List Line records on Price Source is implemented directly in the table 7005 "Price Source" in a non-extensible way. 
Technically, Price Sources can be also extended, but currently it is not possible to apply filters based on additional fields in the Price Source table. To implement this filtering, it should be sufficient to have an event triggered after the filters on Price Source are applied in the FilterPriceLines procedure in table 7005, "Price Source".
Internal work item: [AB#560628](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560628)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
