### ISSUE TITLE
[Request for External] codeunit 90 "Purch.-Post" OnPostItemJnlLineOnAfterPrepareItemJnlLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27815]
### Describe the request

Can you include QtyToBeInvoiced as parameter in event OnPostItemJnlLineOnAfterPrepareItemJnlLine in codeunit 90 "Purch.-Post"?

### Additional context

Need it in addition to QtyToBeReceived
Internal work item: [AB#561094](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561094)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28412.
