### ISSUE TITLE
Add missing TempJobPlanningLine parameter to OnBeforeCreateNewInvoice

### ISSUE THREAD

**Issue by DF1229** [microsoft/ALAppExtensions#27818]
### Describe the request

The event `OnBeforeCreateNewInvoice` from codeunit `1002 "Job Create-Invoice"` seems to be missing a crucial parameter.
To be able to implement the same functionality as the procedure that calls this event (which gets skipped if `IsHandled` is set to true by the event subscriber), we need access to the `TempJobPlanningLine` variable.

Suggested fix would be to update the event declaration like demonstrated below:
```al
// OnBeforeCreateNewInvoice(JobTask, InvoicePerTask, OldJobNo, OldJobTaskNo, LastJobTask, NewInvoice, IsHandled);
OnBeforeCreateNewInvoice(JobTask, InvoicePerTask, OldJobNo, OldJobTaskNo, LastJobTask, NewInvoice, TempJobPlanningLine, IsHandled);
```

### Additional context

We need this update to be able to keep existing customer-facing functionality when upgrading from older BC versions.
Internal work item: [AB#561098](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561098)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
