### ISSUE TITLE
[Change Request] Add a SetHideValidationDialog procedure in codeunit 205 "Alt. Cust. VAT Reg. Doc. Impl."

### ISSUE THREAD

**Issue by cscheidsteff** [microsoft/ALAppExtensions#27812]
### Describe the request

We request the implementation of a SetHideValidationDialog functionality for a need-based control of showing/suppressing the modal Confirmation Dialog raised within procedure ConfirmChanges() in codeunit "Alt. Cust. VAT Reg. Doc. Impl." (205)

### Additional context

In the procedure mentioned above a modal dialog is shown that can only be suppressed by registering a NotifactionID in ???My Notifications???. This is not a suitable option in connection with a batch processing situation

![Image](https://github.com/user-attachments/assets/2d677d64-a21a-4912-829e-06d50844f757)

Internal work item: [AB#560630](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560630)

**Comment by ventselartur** [comment]
Hello @cscheidsteff ,

Thank you for your request.
How exactly do you suggest implementing the SetHideValidationDialog functionality here and how do you expect to call it during the bath processing?

Artur

**Comment by cscheidsteff** [comment]
Hi Artur,

I suggest to do it by extending the parameters in the following functions (or alternatively by overloading these functions):

1.
![Image](https://github.com/user-attachments/assets/c735a167-2633-4aa9-ae52-b7ae44b19572)

2.
![Image](https://github.com/user-attachments/assets/168e6515-4ee7-43c0-8bb2-c7827a48f3c2)

3.
![Image](https://github.com/user-attachments/assets/6b03fffb-241d-4e50-9b79-c5023ee85942)

4.
![Image](https://github.com/user-attachments/assets/10f07a94-dcd5-4f46-850d-6cc9c731c0fe)

The additional parameter would then also have to be added in the interface "Alt. Cust. VAT Reg. Doc." and its corresponding implementations.

regards
Carsten

**Comment by ventselartur** [comment]
@cscheidsteff , thank you

If the purpose is to call the GetHideValidationDialog function inside of the implementation in the ConfirmChanges function, why do i need to change the interface? The result of the GetHideValidationDialog function can be called this way internally:

![Image](https://github.com/user-attachments/assets/189ebf57-d711-4391-9766-5ea69bab58fe)


Would that be enough if i only make this change?

**Comment by cscheidsteff** [comment]
you're absolutely right and that would be enough of course. So sorry for this nonsense :(

**Comment by cscheidsteff** [comment]
@ventselartur thanks again for your suggestion. As I wrote yesterday, this approach would solve our problem. Would you plan to implement it this way?

**Comment by ventselartur** [comment]
@cscheidsteff , yes. Expect it in 25.3.
Thanks for your request!

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 28217.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28220.
