### ISSUE TITLE
[Event Request] page 5966 "Service Quote Lines" OnOpenPageOnBeforeSetSelectionFilter event

### ISSUE THREAD

**Issue by Sara-Handerek** [microsoft/ALAppExtensions#27811]
### Describe the request
We need to initialize the filter when the 'Service Quote lines' page is opened.
For the moment, the existing events do not allow the initialization of the filter correctly when the page is opened.

### Current code
```
page 5966 "Service Quote Lines"

    trigger OnOpenPage()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnOpenPage(Rec, FaultAreaCodeVisible, SymptomCodeVisible, FaultCodeVisible, ResolutionCodeVisible, IsHandled);
        if not IsHandled then begin
            Clear(SelectionFilter);           // This line makes it impossible to initialize the filter when the page is opened.
            SetSelectionFilter();
            ...
   end;
```

### Extensibility request
```
page 5966 "Service Quote Lines"

    trigger OnOpenPage()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnOpenPage(Rec, FaultAreaCodeVisible, SymptomCodeVisible, FaultCodeVisible, ResolutionCodeVisible, IsHandled);
        if not IsHandled then begin
            Clear(SelectionFilter);
            OnOpenPageOnBeforeSetSelectionFilter(SelectionFilter);      // <NEW>
            SetSelectionFilter();
            ...
   end;

    [IntegrationEvent(false, false)]
    local procedure OnOpenPageOnBeforeSetSelectionFilter(var SelectionFilter: Option)
    begin
    end;
```

### How to open the page
Go to the "Service Quote" page.
> On the lines, select the "Quote" tab.
>> Click on the button "Service Lines"
>>> The page "Service Quote Lines" is opened.

### Additional context

My extensibility request is inspired from what already exists for the page 5905 "Service Lines".

### Existing code
  ```
page 5905 "Service Lines"

  trigger OnOpenPage()
    var
        PriceCalculationMgt: Codeunit "Price Calculation Mgt.";
    begin
        ExtendedPriceEnabled := PriceCalculationMgt.IsExtendedPriceCalculationEnabled();
        Clear(SelectionFilter);
        SelectionFilter := SelectionFilter::"Lines per Selected Service Item";
        OnOpenPageOnBeforeSetSelectionFilter(SelectionFilter);
        SetSelectionFilter();
   end;

    [IntegrationEvent(false, false)]
    local procedure OnOpenPageOnBeforeSetSelectionFilter(var SelectionFilter: Option)
    begin
    end;
```
Internal work item: [AB#560631](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/560631)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
