### ISSUE TITLE
[Event Request] table 39 "Purchase Line" OnValidateIndirectCostOnBeforeCheckCostingMethod

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27819]
### Describe the request

Can you add a event to be able to override the costing method check when validating cost %?
```
            trigger OnValidate()
            var
                Item: Record Item;
            begin
                TestField("No.");
                TestStatusOpen();

                CheckLineTypeOnIndirectCostPercentUpdate();

                // >>>>>>>>>>>
                OnValidateIndirectCostOnBeforeCheckCostingMethod(Rec,IsHandled);
                if not IsHandled then
                // >>>>>>>>>>>
                if (Type = Type::Item) and ("Prod. Order No." = '') then begin
                    GetItem(Item);
                    Item.TestField(Type, Item.Type::Inventory);
                    if Item."Costing Method" = Item."Costing Method"::Standard then
```

### Additional context

We have made custom code to handle subcontracting for service. I need to skip this check when that is the case.
Internal work item: [AB#561093](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561093)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
