### ISSUE TITLE
[Request for External] table 39 "Purchase Line" CheckDropShipment

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27822]
### Describe the request

Can you change procedure CheckDropShipment to global in "Purchase Line"?

### Additional context

I need to call the same procedure for ?? custom field, and as there is an event in the procedure i dont want to duplicate the code in case it should be skipped for other customizations.
Internal work item: [AB#561104](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561104)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
