### ISSUE TITLE
LookupPageId property for table 780 "Certificate of Supply"

### ISSUE THREAD

**Issue by nevenamark** [microsoft/ALAppExtensions#27827]
### Describe the request

Hello. We need LookupPageId property specified for table 780 "Certificate of Supply" as corresponding list page 780 "Certificates of Supply".

Currently, the following properties are defined on the table level:

```
table 780 "Certificate of Supply"
{
    Caption = 'Certificate of Supply';
    DataClassification = CustomerContent;
...
}
```

After the requested change, table 780 "Certificate of Supply" would have the following properties:

```
table 780 "Certificate of Supply"
{
    Caption = 'Certificate of Supply';
    DataClassification = CustomerContent;
    LookupPageId = "Certificates of Supply";
...
}
```

### Additional context

We need this property in order to enable setting up of a generic cue to give detailed insight into existing Certificates of Supply.
Internal work item: [AB#561280](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561280)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28358.
