### ISSUE TITLE
[Event Request] table 39 "Purchase Line" OnValidateUnitOfMeasureCodeOnAfterCalcShouldUpdateItemReference

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#27820]
### Describe the request

Can you add a event to be able to override the field updates when validating unit of measure code?

```
                ShouldUpdateItemReference := Type = Type::Item;
                OnValidateUnitOfMeasureCodeOnAfterCalcShouldUpdateItemReference(Rec, ShouldUpdateItemReference);
                if ShouldUpdateItemReference then
                    UpdateItemReference();
                // >>>>>>>>>>>
                OnValidateUnitOfMeasureCodeOnBeforeUpdateNonSubcontractingDocument(Rec,IsHandled);
                if not IsHandled then
                // >>>>>>>>>>>                    
                if "Prod. Order No." = '' then
                    case Type of
                        Type::Item:
                            begin
                                GetItem(Item);
```

### Additional context

We have made custom code to handle subcontracting for service. I need to skip this check when that is the case.
Internal work item: [AB#561092](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561092)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
