### ISSUE TITLE
[Event Request] Table 5093 "Opportunity Entry".FinishWizard

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27838]
### Describe the request

Please remove scope OnPrem for function FinishWizard. We do not see reason why it should be only for onprem.

```
[Scope('OnPrem')]
  procedure FinishWizard()
  var
      OppEntry: Record "Opportunity Entry";
  begin
      UpdateEstimates();
      OppEntry := Rec;
      InsertEntry(OppEntry, "Cancel Old To Do", false);
      OnFinishWizardOnAfterInsertEntry(OppEntry);
      Delete();
  end;
```

### Additional context

We do not see reason why it should be only for onprem.
Internal work item: [AB#561117](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561117)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28339.
