### ISSUE TITLE
[Protected Var] Report 99001045 "Calc. Machine Center Calendar"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27839]
### Describe the request

Change global variables to protected one

```
    protected var
        StartingDate: Date;
        EndingDate: Date;
```

### Additional context

We need access to global vars
Internal work item: [AB#561112](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561112)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28358.
