### ISSUE TITLE
[Event Request] table 900 "Assembly Header" - OnAfterValidateDates

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#27843]
### Describe the request

Could you please create a new integration Event in table 900 "Assembly Header" at the end of procedure ValidateDates

```
    procedure ValidateDates(FieldNumToCalculateFrom: Integer; DoNotValidateButJustAssign: Boolean)
    var
        NewDueDate: Date;
        NewEndDate: Date;
        NewStartDate: Date;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidateDates(Rec, FieldNumToCalculateFrom, DoNotValidateButJustAssign, IsHandled);
        if IsHandled then
            exit;

        CalculateNewDates(FieldNumToCalculateFrom, NewDueDate, NewEndDate, NewStartDate);
        if DoNotValidateButJustAssign then
            AssignNewDates(FieldNumToCalculateFrom, NewDueDate, NewEndDate, NewStartDate)
        else
            DoValidateDates(FieldNumToCalculateFrom, NewDueDate, NewEndDate, NewStartDate);

        if "Due Date" < "Ending Date" then
            Error(Text015, FieldCaption("Due Date"), "Due Date", FieldCaption("Ending Date"), "Ending Date");
        if "Ending Date" < "Starting Date" then
            Error(Text015, FieldCaption("Ending Date"), "Ending Date", FieldCaption("Starting Date"), "Starting Date");

// >> NEW
OnAfterValidateDates(Rec, FieldNumToCalculateFrom, DoNotValidateButJustAssign);
// << NEW
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnAfterValidateDates(var AssemblyHeader: Record "Assembly Header"; FieldNumToCalculateFrom: Integer; var DoNotValidateButJustAssign: Boolean)
    begin
    end;

```

### Additional context

There is no event in this table, where i can get the calculated dates values. To use the OnAfterModifyEvent is not the way, because every change in this table would raise my event. 

It would be fine for me, when there is no var parameter, cause i don't want to modify the values.

Internal work item: [AB#561121](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561121)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
