### ISSUE TITLE
[Event Request] Table 5093 "Opportunity Entry".FinishWizard

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#27841]
### Describe the request

Please add new event
```
procedure FinishWizard()
var
    OppEntry: Record "Opportunity Entry";
begin
    UpdateEstimates();
    OppEntry := Rec;
    //-----------------------------------------------OnFinishWizardOnAfterUpdateEstimates:BEGIN
    OnFinishWizardOnAfterUpdateEstimates(OppEntry);
    //-----------------------------------------------OnFinishWizardOnAfterUpdateEstimates:END
    InsertEntry(OppEntry, "Cancel Old To Do", false);
    OnFinishWizardOnAfterInsertEntry(OppEntry);
    Delete();
end;

//-----------------------------------------------OnFinishWizardOnAfterUpdateEstimates:BEGIN
[IntegrationEvent(true, false)]
local procedure OnFinishWizardOnAfterUpdateEstimates(var OppEntry: Record "Opportunity Entry")
begin
end;
//-----------------------------------------------OnFinishWizardOnAfterUpdateEstimates:END
```

### Additional context

We need change record before insert entry
Internal work item: [AB#561120](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561120)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
