### ISSUE TITLE
[Event Request] Incorrect parameter in event OnAfterCopyFromInsertReservEntry of codeunit 99000830 "Create Reserv. Entry"

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#27844]
### Describe the request

Change as "var" the QtyToHandleAndInvoiceIsSet parameter in integration event OnAfterCopyFromInsertReservEntry.

Old code:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromInsertReservEntry(var InsertReservEntry: Record "Reservation Entry"; var ReservEntry: Record "Reservation Entry"; FromReservEntry: Record "Reservation Entry"; Status: Enum "Reservation Status"; QtyToHandleAndInvoiceIsSet: Boolean)
    begin
    end;

New code:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromInsertReservEntry(var InsertReservEntry: Record "Reservation Entry"; var ReservEntry: Record "Reservation Entry"; FromReservEntry: Record "Reservation Entry"; Status: Enum "Reservation Status"; **var** QtyToHandleAndInvoiceIsSet: Boolean)
    begin
    end;

### Additional context

In the codeunit 99000830 "Create Reserv. Entry" there is the followinc code. The variable QtyToHandleAndInvoiceIsSet shoud be used to change the following behaviour of updating quantities. But it is not as var parameter and we cannot change it.

            OnAfterCopyFromInsertReservEntry(InsertReservEntry2, ReservEntry2, ReservEntry, Status, QtyToHandleAndInvoiceIsSet);

            if not QtyToHandleAndInvoiceIsSet then begin
                ReservEntry2."Qty. to Handle (Base)" := ReservEntry2."Quantity (Base)";
                ReservEntry2."Qty. to Invoice (Base)" := ReservEntry2."Quantity (Base)";
            end;

Internal work item: [AB#561119](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561119)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28338.
