### ISSUE TITLE
[Protected Variable] ShowLotSN in report 1308 "Standard Sales - Shipment"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#27851]
### Describe the request

Please set variable ShowLotSN to protected in order that the value can be used inside of Report extension.
![Image](https://github.com/user-attachments/assets/107e263c-7b74-44dd-8b19-b58a5806b541)

### Additional context

We are having solution specific printout of serial Nos in the Sales Shipment Report.
Internal work item: [AB#561282](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561282)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28358.
