### ISSUE TITLE
[Request for External] Codeunit 5988 "Serv-Documents Mgt." - Event OnPostDocumentLinesOnAfterSortLines

### ISSUE THREAD

**Issue by germanaltamiranoAW** [microsoft/ALAppExtensions#27859]
### Describe the request

Dear ALAppExtensions team,
I would like to request a modification to codeunit 5988 "Serv-Documents Mgt.", specifically to the IntegrationEvent OnPostDocumentLinesOnAfterSortLines included in the PostDocumentLines procedure
Add parameters TempVATAmountLine and TempVATAmountLineForSLE

```
LineCount := 0;

        // init cu for posting SLE type Usage
        ServPostingJnlsMgt.InitServiceRegister(NextServLedgerEntryNo, NextWarrantyLedgerEntryNo);
        OnPostDocumentLinesOnBeforeFilterServiceLine(ServHeader, ServLine); 
        if not ApplicationAreaMgmt.IsSalesTaxEnabled() then begin
            ServLine.CalcVATAmountLines(1, ServHeader, ServLine, TempVATAmountLine, Ship);
            ServLine.CalcVATAmountLines(2, ServHeader, ServLine, TempVATAmountLineForSLE, Ship);
        end;

        GetZeroServiceLineRecID(ServHeader, ZeroServiceLineRecID);
        ErrorMessageMgt.PushContext(ErrorContextElementProcessLine, ZeroServiceLineRecID, 0, PostDocumentLinesMsg);

        ServLine.Reset();
        SortLines(ServLine);
        OnPostDocumentLinesOnAfterSortLines(ServHeader, ServLine); // MODIFY EVENT
        ServLedgEntryNo := FindFirstServLedgEntry(ServLine);
```

The event should be like this

```
 [IntegrationEvent(false, false)]
local procedure OnPostDocumentLinesOnAfterSortLines(var ServHeader: Record "Service Header"; var ServLine: Record "Service Line";var TempVATAmountLine: Record "VAT Amount Line" temporary;var TempVATAmountLineForSLE: Record "VAT Amount Line" temporary)
begin
end;
```

### Additional context

This modification will allow us to better manage calculations in statistics with VAT amounts in our developments.

Internal work item: [AB#561382](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561382)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28412.
