### ISSUE TITLE
[Event Request] Codeunit 7110 Analysis Report Management - Procedure CalcQuantity - OnBeforeCalcQuantity

### ISSUE THREAD

**Issue by mavohra** [microsoft/ALAppExtensions#27860]
### Describe the request

Please add the event OnBeforeCalcQuantity in procedure CalcQuantity in Codeunit 7110 Analysis Report Management.

```
local procedure CalcQuantity(var ItemStatisticsBuf: Record "Item Statistics Buffer"; Invoiced: Boolean): Decimal
begin
    OnBeforeCalcQuantity(ItemStatisticsBuf, Invoiced, IsHandled, Result); // <--- New Event
    if IsHandled then 
        exit(Result);

    if ItemStatisticsBuf.GetFilter("Source No. Filter") = '' then
        ItemStatisticsBuf.SetRange("Source Type Filter");

    if AnalysisLineTemplate."Item Analysis View Code" = '' then begin
        ItemStatisticsBuf.SetRange(ItemStatisticsBuf."Entry Type Filter");
        if Invoiced then begin
            ItemStatisticsBuf.CalcFields("Invoiced Quantity");
            exit(ItemStatisticsBuf."Invoiced Quantity");
        end;
        ItemStatisticsBuf.CalcFields(Quantity);
        exit(ItemStatisticsBuf.Quantity);
    end;
    ItemStatisticsBuf.SetRange(ItemStatisticsBuf."Entry Type Filter");
    if Invoiced then begin
        ItemStatisticsBuf.CalcFields("Analysis - Invoiced Quantity");
        exit(ItemStatisticsBuf."Analysis - Invoiced Quantity");
    end;
    ItemStatisticsBuf.CalcFields("Analysis - Quantity");
    exit(ItemStatisticsBuf."Analysis - Quantity");
end;

```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcQuantity(var ItemStatisticsBuf: Record "Item Statistics Buffer"; Invoiced: Boolean; var IsHandled: Boolean; var Result: Decimal)
begin
end;
```

### Additional context

Our customization allows handling alternative quantities based on specific conditions and we'd like to make changes in the procedure.

This event request is part of a series of four related event requests for Codeunit 7110 Analysis Report Management. The requested events aim to enable customization of key procedures for handling alternative quantities and budget data.

The four requested events are:

OnBeforeCalcQuantity in the CalcQuantity procedure.
OnBeforeCalcBudgetQuantity in the CalcBudgetQuantity procedure.
OnBeforeDrillDownQuantity in the DrillDownQuantity procedure.
OnBeforeDrillDownBudgetQuantity in the DrillDownBudgetQuantity procedure.

The remaining 3 events will be requested in a separate request. 

These events are required to implement custom logic without modifying the base application. 

Thank you.
Internal work item: [AB#561386](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561386)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28412.
