### ISSUE TITLE
[Bug]: Testfield when creating new Vendor

### ISSUE THREAD

**Issue by onzema** [microsoft/ALAppExtensions#27866]
### Describe the issue

When creating a new Vendor with the extension E-Document installed there's this code (in pageextension 6161 "E-Doc. Vendor Page") that doesn't allow to create new vendors

> trigger OnAfterGetCurrRecord()
>     begin
>         Rec.TestField("No.");
>         ParticipantIdCount := ServiceParticipant.GetParticipantIdCount(Enum::"E-Document Source Type"::Vendor, Rec."No.");
>     end;

i think it could be something like this instead

>     trigger OnAfterGetCurrRecord()
>     begin
>         ParticipantIdCount := 0;
>         if Rec.("No.") <> '' then
>             ParticipantIdCount := ServiceParticipant.GetParticipantIdCount(Enum::"E-Document Source Type"::Vendor, Rec."No.");
>     end;

This is in BC 25.2.27733.28023 SaaS in the Spanish version
And the extension is one of this (I don't know exactly)
E-Document Connector - Avalara
E-Document Core
E-Document Core Demo Data
E-Document Format for Factura-E
E-Documents Connector with External Endpoints

pd: I don't know if this goes here. sorry if it's not the place. I would really appreciate if you point me where to address this.

Thanks

### Expected behavior

I should be allowed to create new vendors

### Steps to reproduce

Go to Vendor List and create a New Vendor

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by RadoArvay** [comment]
Discussed on [Viva Engage](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=3109981592264704) (and should be already fixed).

**Comment by onzema** [comment]
Oh... thanks i will have a look and close this.
but I updated an environment yesterday and this problem is still there, i can assure you that.
Thank you!

**Comment by RadoArvay** [comment]
It is fixed, but it will be available in the build 28099, as mentioned there.
