### ISSUE TITLE
[Event Request] Codeunit 7110 Analysis Report Management - Procedure CalcBudgetQuantity - OnBeforeCalcBudgetQuantity

### ISSUE THREAD

**Issue by mavohra** [microsoft/ALAppExtensions#27861]
### Describe the request

Please add the event OnBeforeCalcBudgetQuantity in procedure CalcBudgetQuantity in Codeunit 7110 Analysis Report Management.

```
local procedure CalcBudgetQuantity(var ItemStatisticsBuf: Record "Item Statistics Buffer"): Decimal
begin
    OnBeforeCalcBudgetQuantity(ItemStatisticsBuf, IsHandled, Result); // <---- New Event
    if IsHandled then
        exit(Result);
        
    if ItemStatisticsBuf.GetFilter("Source No. Filter") = '' then
        ItemStatisticsBuf.SetRange(ItemStatisticsBuf."Source Type Filter");

    if AnalysisLineTemplate."Item Analysis View Code" = '' then begin
        ItemStatisticsBuf.CalcFields(ItemStatisticsBuf."Budgeted Quantity");
        exit(ItemStatisticsBuf."Budgeted Quantity");
    end;
    ItemStatisticsBuf.CalcFields(ItemStatisticsBuf."Analysis - Budgeted Quantity");
    exit(ItemStatisticsBuf."Analysis - Budgeted Quantity");
end;

```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcBudgetQuantity(var ItemStatisticsBuf: Record "Item Statistics Buffer"; var IsHandled: Boolean; var Result: Decimal)
begin
end;

```

### Additional context

Our customization allows handling alternative budget quantities based on specific conditions, and we'd like to make changes in the procedure.

**Event 2/4**
Internal work item: [AB#561385](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/561385)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 28412.
