### ISSUE TITLE
[Event Request] Report 188 - Create Reminders

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#2796]
Requesting 2 new event publisher on report 188 - Create Reminders (**Both:** IncludeSender=Yes; GlobalVarAccess=Yes).

### Event 1 - OnBeforePreReport
**Event**
```
[Integration(TRUE,TRUE)]
LOCAL [IntegrationEvent] OnBeforePreReport()
```

**Code**
```
OnPreReport()
>>> New Code
OnBeforePreReport;
<<< New Code End

CustLedgEntry.COPY(CustLedgEntry2);
IF CustLedgEntryLineFeeOnFilters.GETFILTERS <> '' THEN
  CustLedgEntryLineFeeOn.COPYFILTERS(CustLedgEntryLineFeeOnFilters);
```

### Event 2 - OnBeforePostReport
**Event**
```
[Integration(TRUE,TRUE)]
LOCAL [IntegrationEvent] OnBeforePostReport()
```

**Code**
```
OnPostReport()
>>> New Code
OnBeforePostReport;
<<< New Code End
```

**Comment by AlexanderYakunin** [comment]
We cannot use property GlobalVarAccess, it will be discontinued. Please specify all needed parameters.

**Comment by bleisibach** [comment]
I checked with the developer. According to him, he does not need the GlobalVarAccess. It seems I have misinterpreted his internal request. Still, he needs to have both event publishers. Both: IncludeSender=No; GlobalVarAccess=No. Thank you.
