### ISSUE TITLE
How to extend the DataClassification

### ISSUE THREAD

**Issue by devhigh1992** [Microsoft/ALAppExtensions#280]
Is there anyway to extend the DataClassification?

I want to add
- Quality Control
- Warehouse and Packaging

Thanks

**Comment by dNsl9r** [comment]
The DataClassification Options are fixed, but maybe Microsoft will extend it if you give them a good reason to do so.
More about DataClassification Property: https://docs.microsoft.com/en-us/dynamics-nav/dataclassification-property

**Comment by GiorgosPa** [comment]
Hello,
the DataClassification property is meant for privacy classifications. These classifications are taken into account for privacy features such as Data Classification Worksheet and Data Privacy Wizard. Why do you want these values extended.

**Comment by devhigh1992** [comment]
Sorry for confusing you, and I also got so confused with this "DataClassification". I'll ask again when I truly understand the real purpose of this feature in the connection with segmenting data for a custom module.
