### ISSUE TITLE
Event Request Table 5062 – Attachment

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#2801]
The"RunAttachment" feature requires a publisher (OnforeRunAttachment). This must have the variables involved in the process (segment line, etc.) as well as an IsHandled parameter.
![image](https://user-images.githubusercontent.com/26924867/59486831-fb03df00-8e7a-11e9-9280-ed90d110523f.png)

**Comment by AlexanderYakunin** [comment]
Please specify needed event.

**Comment by AlexanderYakunin** [comment]
Event information missing, no reply from partner, cannot implement

**Comment by KaiSwitalla** [comment]
Hello all,
here my suggestion of a signature of this publisher:
OnBeforeRunAttachment(Caption : Text[260];IsTemporary : Boolean;LanguageCode : Code[10],var IsHandled)

**Comment by KaiSwitalla** [comment]
Hello,
based on my phone call with jared hall last week, here is a better definition for this function. I also added an description of the event(s) needed. 
Additionally i developed the events by my own. Take a look at the C/AL  object i'va added.
Here you can see the exact publishers, parameters, function name etc.
My Code is documented like:
// A/ Event Request
OnBeforeSomething...
// E/ Event Request

Requested Event in CU 5052 - Function "ProcessDeliverySorter"
- OnBeforeRunAttachment(SegLine,WordCaption,IsTemporary,IsVisible,Handler,Handled);

[Tab 5062 Attachment.txt](https://github.com/microsoft/ALAppExtensions/files/3440991/Tab.5062.Attachment.txt)
