### ISSUE TITLE
Extension Table 5064 – Interaction Template

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#2802]
The two option fields must be of the type enumeration.
![image](https://user-images.githubusercontent.com/26924867/59486866-1a027100-8e7b-11e9-967a-0d654a6bb4ff.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
