### ISSUE TITLE
Event Request Table 5065 – Interaction Log Entry - OpenAttachment

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#2804]
The "OpenAttachment" feature must add at least two publishers. 
•	OnBeforeOpenAttachment ( incl.IsHandled)
•	OnAfterCopyFieldsFromInteractLogEntry

![image](https://user-images.githubusercontent.com/26924867/59486969-6cdc2880-8e7b-11e9-9af5-7e08256b9ab8.png)

TheSetCancelledCheckmarkfeature must receive a publisher "OnBeforeCancelledCheckMark." There must be an IsHandled parameter.

![image](https://user-images.githubusercontent.com/26924867/59486983-79608100-8e7b-11e9-9807-31728408c2f8.png)

Alternatively, an intervention in the above function "ToggleCanceledCheckmark" would be possible as long as one gets influence on the filtering and selection of the activity log posts to be deleted.

**Comment by AlexanderYakunin** [comment]
First event already exist. For the second ask, please specify event with parameters and place in the code. Without this information it cannot be implemented.

**Comment by AlexanderYakunin** [comment]
Event information missing, no reply from partner, cannot implement

**Comment by KaiSwitalla** [comment]
Hello all,

here your information about the second publisher.
![image](https://user-images.githubusercontent.com/26924867/60644498-98c54b00-9e36-11e9-8324-35e29e186d75.png)

**Comment by KaiSwitalla** [comment]
Hello,
based on my phone call with jared hall yesterday, here is a better definition for this function. I also added an description of the event(s) needed. 
Additionally i developed the events by my own. Take a look at the C/AL  object i'va added.
Here you can see the exact publishers, parameters, function name etc.
I also splitted this event request. This one is about function "OpenAttachment". I made a new one for the second function.
My Code is documented like:
// A/ Event Request
OnBeforeSomething...
// E/ Event Request

Requested Event in CU 5052 - Function "ProcessDeliverySorter"
- OnBeforeOpenAttachment
- OnAfterOpenAttachment

[Tab 5065 Interaction Log Entry.txt](https://github.com/microsoft/ALAppExtensions/files/3440749/Tab.5065.Interaction.Log.Entry.txt)

in Addition:
i can not agree to your comment that the first event allready exists. I found the event "OnOpenAttachmentOnBeforeShowAttachment(Rec,SegLine);" in your code. But that event is only triggered in a specific case. It is not like a "OnBefore..." Event.

I hope you allready have all needed information.

**Comment by KaiSwitalla** [comment]
https://github.com/microsoft/ALAppExtensions/issues/3561
