### ISSUE TITLE
Event Request Table 5075 – Logged Segment

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#2805]
Compare requirements Table 5065 …

![image](https://user-images.githubusercontent.com/26924867/59487019-9bf29a00-8e7b-11e9-97a5-7fb98238ead6.png)

**Comment by StanPesotskiy** [comment]
Hi @KaiSwitalla, 
We all want to spend less time on navigating through multiple requests searching for actual content. 
You could help us if you would:
- put all required information into each request, not just mention another one;
- If you mention another request, you can put a direct link into text;
- add the label name as a prefix to your request name. So this one could be "[event-request] Table 5075 – Logged Segment"
 
Thank you.

**Comment by AlexanderYakunin** [comment]
No reply, closing

**Comment by KaiSwitalla** [comment]
Hello all,
here is the Link to my post mentioned 
[https://github.com/microsoft/ALAppExtensions/issues/2804](url)

The "event request" label is allready added.
The prefix is added to the name.

**Comment by KaiSwitalla** [comment]
Hello,
based on my phone call with jared hall last week, here is a better definition for this function. I also added an description of the event(s) needed. 
Additionally i developed the events by my own. Take a look at the C/AL  object i'va added.
Here you can see the exact publishers, parameters, function name etc.
My Code is documented like:
// A/ Event Request
OnBeforeSomething...
// E/ Event Request

Requested Event in CU 5052 - Function "ProcessDeliverySorter"
- OnBeforeToggleCanceledCheckmark(Rec,Handled);

[Tab 5075 Logged Segment.txt](https://github.com/microsoft/ALAppExtensions/files/3440914/Tab.5075.Logged.Segment.txt)
