### ISSUE TITLE
Extension Table 5097 – Criteria Line  Segment

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#2808]
The Field Action needs to be an Enumeration.
![image](https://user-images.githubusercontent.com/26924867/59487223-41a60900-8e7c-11e9-9158-9389f3d453d4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
