### ISSUE TITLE
Extension Table 5099 – Saved Segment Criteria Line

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#2809]
The Field Action needs to be an Enumeration.
![image](https://user-images.githubusercontent.com/26924867/59487903-508dbb00-8e7e-11e9-9260-a7e8105f16df.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
