### ISSUE TITLE
Extension Report 5185 – Log Segment

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#2810]
It must be possible to extend options/parameters on the prop page and also pass them on to the "LogSegment"function(if necessary "Log Segment Parameter Buffer" Table?).
![image](https://user-images.githubusercontent.com/26924867/59487969-7d41d280-8e7e-11e9-9725-784ac97310a9.png)

See also comments on Codeunit 5051 "SegManagement." Since an object of the type report is not expandable via extension, we suggest a page of the kind "CommonDialog" (or the like).

**Comment by KaiSwitalla** [comment]
Hello,
based on my phone call with jared hall last week, we will replace the action with our own version. So, you can solve this issue in a future release of your choice.

**Comment by AlexanderYakunin** [comment]
Thank you, closing this request
