### ISSUE TITLE
Extension Sales and Inventory Forecast throws an error on new Purchase Order/Purchase Invoice

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#2817]
In 14.1. as soon as I try to create new Purchase Order or Purchase Invoice I am receiving the following error:

![image](https://user-images.githubusercontent.com/40229810/59488139-ff31fb80-8e7e-11e9-8d9e-54473c4ec32a.png)

To reproduce it, go to Purchase Orders / Purchase Invoices page and try to create a new one and it should appear.

As soon as I uninstalled this extension the error has been gone:

![image](https://user-images.githubusercontent.com/40229810/59488262-6059cf00-8e7f-11e9-9b1e-014a2f7539cf.png)

Line highlighted below from Codeunit 2004 Machine Learning KeyVaultMgmt. is throwing the error:

![image](https://user-images.githubusercontent.com/40229810/59488573-4076db00-8e80-11e9-9a6a-123955b11598.png)

Error happens because function GetAzureKeyVaultSecret called from the first line of this procedure returns nothing for SecretValue and therefore JSON file is not properly generated.

Function KeyValuePairInBuffer from 2200 Azure Key Vault Management from my perspective is not working properly too, because when I use debugger to track the error I can see that variable ValueFound will be set to TRUE, but variable ValueToReturn will be empty:

![image](https://user-images.githubusercontent.com/40229810/59488913-212c7d80-8e81-11e9-932f-ebf411ee2aa3.png)

![image](https://user-images.githubusercontent.com/40229810/59489095-90a26d00-8e81-11e9-9aae-4bea606592df.png)

![image](https://user-images.githubusercontent.com/40229810/59489122-9ac46b80-8e81-11e9-9196-905ec7ebb51e.png)

When I was tracking this error using debugger I have discovered that  Codeunit 2200 Azure Key Vault Management throwing an error because global text constant ApplicationSecretsTxt contains 1026 characters:

![image](https://user-images.githubusercontent.com/40229810/59489302-10303c00-8e82-11e9-893e-9756f8cc3639.png)

In 13.5. it was 956 characters.

**Versions:**
 - AL Language:  3.0.124247
 - Business Central: 14.1.
 - Image: mcr.microsoft.com/businesscentral/sandbox:14.1.32615.0-ca-ltsc2019

**Comment by StanPesotskiy** [comment]
Please report this issue via the standard support channel.
