### ISSUE TITLE
[Event Request] ShowPostedConfirmationMessage on Page 42

### ISSUE THREAD

**Issue by jbeckerBER** [microsoft/ALAppExtensions#2820]
Please add an event on before ShowPostedConfirmationMessage to Page 42

**Comment by AlexanderYakunin** [comment]
Do you know that you can simply disable this message by removal instruction 'ShowPostedConfirmationMessage' in User Preference?

**Comment by sbeh** [comment]
@AlexanderYakunin Could you explain further please? I can't find a page thats build on top of Table 1306 User Preference. Searching around I found "My Notifications" which comes close (Table 1518), but it doesn't include a setting for "ShowPostedConfirmationMessage".

**Comment by AlexanderYakunin** [comment]
Please look here in Sales Order page:

        case Navigate of
            "Navigate After Posting"::"Posted Document":
                begin
                    if InstructionMgt.IsEnabled(InstructionMgt.ShowPostedConfirmationMessageCode) then
                        ShowPostedConfirmationMessage();

                    if DocumentIsScheduledForPosting or DocumentIsPosted then
                        CurrPage.Close();
                end;

**Comment by sbeh** [comment]
@AlexanderYakunin Yes, found that code already. But your statement

> Do you know that you can simply disable this message by removal instruction 'ShowPostedConfirmationMessage' in User Preference?

Made it sound simpler for me than modifying standard code. (Because the event is missing, which this issues was about.)

**Comment by db-bc** [comment]
just search for My Notifications and disable this one:
![image](https://user-images.githubusercontent.com/63455896/128322080-69783057-46fb-4e5b-baa7-774030b314d4.png)
