### ISSUE TITLE
[Event Request] C90 OnBeforeUpdPostingDescriptionOnInvoice

### ISSUE THREAD

**Issue by SandroKiedis** [microsoft/ALAppExtensions#2822]
I refer to my [old Request](https://github.com/microsoft/ALAppExtensions/issues/1784) 

I quote AlexanderYakunin
> We don't have this code in latest version, please check you request
![54812855-6e3af200-4c8c-11e9-8876-c1fb8b8907ce](https://user-images.githubusercontent.com/47424839/59500719-51344a80-8e9a-11e9-9b5b-f3d91ccccea0.png)

If I misinterpreted something, I am truly sorry. The latest Version I know of is the RTM Version of the Microsoft Dynamics 365 Business Central – 2019 Spring Release (Version CH). Where the function "UpdPostingDescriptionInvoice" exists.

Thanks for clarification & Kind regards

**Comment by AlexanderYakunin** [comment]
This is CH specific, please always provide country code if ask is not for W1.
