### ISSUE TITLE
[Event Request] T7317 Qty. to Receive - OnValidate()

### ISSUE THREAD

**Issue by MarcelloDellaCostaCapBS** [microsoft/ALAppExtensions#2823]
Hello Team,
we need a new publisher (OnBeforeQuantityCheck) and a standard code modification (IF HandleError THEN) in order to skip standard code 

```
Qty. to Receive - OnValidate()

OnBeforeQuantityCheck(Rec, HandleError);
IF Not HandleError THEN

IF "Qty. to Receive" > "Qty. Outstanding" THEN
  ERROR(
    Text002,
    "Qty. Outstanding");

```

**Comment by AlexanderYakunin** [comment]
We already have this
Qty. to Receive - OnValidate()
IsHandled := FALSE;
OnBeforeValidateQtyToReceive(Rec,IsHandled);
IF NOT IsHandled THEN
  IF "Qty. to Receive" > "Qty. Outstanding" THEN
    ERROR(Text002,"Qty. Outstanding");
