### ISSUE TITLE
Table 5601 - add а field to the key

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#283]
could you add field "Index Entry" field in exist key in table 5601 (FA Ledger Entry)

old key:
FA No.,Depreciation Book Code,FA Posting Category,FA Posting Type,FA Posting Date,Part of Book Value,Reclassification Entry

new key:
FA No.,Depreciation Book Code,FA Posting Category,FA Posting Type,FA Posting Date,Part of Book Value,Reclassification Entry,**Index Entry**

**Comment by JesperSchulz** [comment]
The key is already very long. What is the purpose of this request? Could you provide a little more context to help us triage this request.

**Comment by Halilovast** [comment]
In our localization we have custom report that calculate amount with filtering Index Entry (in codeunit 5626). But we can create new key with table extension for our purpose. 

I'll close the issue.
