### ISSUE TITLE
[Event Request] Codeunit 5763 - OnPostUpdateWhseDocumentsOnBeforeModify

### ISSUE THREAD

**Issue by makuhn** [microsoft/ALAppExtensions#2839]
Add new integration event **OnPostUpdateWhseDocumentsOnBeforeModify** in Codeunit 5763.

Function PostUpdateWhseDocuments:
```
              WhseShptLine2."Qty. Outstanding (Base)" := "Qty. Outstanding (Base)" - "Qty. to Ship (Base)";
              WhseShptLine2.Status := WhseShptLine2.CalcStatusShptLine;
+             OnPostUpdateWhseDocumentsOnBeforeModify(WhseShptLine2);
              WhseShptLine2.MODIFY;
              OnAfterPostUpdateWhseShptLine(WhseShptLine2);
```
New publisher function:
```
    [Integration]
    LOCAL PROCEDURE OnPostUpdateWhseDocumentsOnBeforeModify@100000001(VAR WhseShptLine@100000000 : Record 7321);
    BEGIN
    END;
```

**Comment by AlexanderYakunin** [comment]
You already have this
      END ELSE BEGIN
        OnBeforePostUpdateWhseShptLine(WhseShptLine2);
        WhseShptLine2."Qty. Shipped" := "Qty. Shipped" + "Qty. to Ship";
        WhseShptLine2.VALIDATE("Qty. Outstanding","Qty. Outstanding" - "Qty. to Ship");
        WhseShptLine2."Qty. Shipped (Base)" := "Qty. Shipped (Base)" + "Qty. to Ship (Base)";
        WhseShptLine2."Qty. Outstanding (Base)" := "Qty. Outstanding (Base)" - "Qty. to Ship (Base)";
        WhseShptLine2.Status := WhseShptLine2.CalcStatusShptLine;
        WhseShptLine2.MODIFY;
        OnAfterPostUpdateWhseShptLine(WhseShptLine2);
      END;

**Comment by makuhn** [comment]
We cannont use the already existing event because our code depends on field `Qty. Shipped` which is updated after the already existing event.

**Comment by AlexanderYakunin** [comment]
But you can use OnAfterPostUpdateWhseShptLine(WhseShptLine2); and update this?

**Comment by makuhn** [comment]
We have extended table Whse. Shipment Line by new fields. These fields are updated based on `Qty. Shipped`. If we use OnAfterPostUpdateWhseShptLine then an additional Modify is required.
