### ISSUE TITLE
Function expose Request - Codeunit 396 NoSeriesManagement - IT Version

### ISSUE THREAD

**Issue by Nyryus** [Microsoft/ALAppExtensions#284]
Hi,

please expose on the italian version in the codeunit 396 NoSeriesManagement the functions CheckSalesDocNoGaps, CheckPurchDocNoGaps.

Thank you in advance

**Comment by darjoo** [comment]
Hi, we have accepted your request. Thanks! You'll see it in the next minor release. Congrat's on helping the extension development community!
