### ISSUE TITLE
Idea to implement record time state system

### ISSUE THREAD

**Issue by devhigh1992** [Microsoft/ALAppExtensions#285]
in AX we have validtimestate https://docs.microsoft.com/en-us/dynamicsax-2012/developer/valid-time-state-tables-and-date-effective-data

plus system fields for created date time, last modified date time, created by and last modified by 

I'm trying to achieve the same result with BC but the InitValue for a date time field only accept 0DT, 
any suggestion would be appriciated.

I'm looking for a system event where every table in the system calls it when a record is inserted, modified or deleted.

Thank you

**Comment by JesperSchulz** [comment]
This GitHub repository is dedicated to handling issues with published apps and extensibility requests for the latest release of Business Central.

To register your idea please use one of the following resources:
- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for AL compiler and developer tools, see [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)
