### ISSUE TITLE
Enum Request - Warehouse Request (Table 5765) - Field 11 "Destination type"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#2851]
Please implement the field 11 ("Destination type") in Table 5765 ("Warehouse Request") as Enum.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
