### ISSUE TITLE
GB localization does not show field Language in My Settings page

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/ALAppExtensions#286]
The GB localization has an extra setting in Page 9176 My Settings on the field Language. The property Visible is set to only show if you are running in Preview mode.

I have no idea why it should be limited to Preview mode only. Can this setting be removed so it works like other localizations (e.g. US version)?

**Comment by JesperSchulz** [comment]
We've logged a bug for our team. As this issue isn't related to extensibility as such, we'll close this issue and won't report back on progress or status, but we're on it ;-)

**Comment by JesperSchulz** [comment]
A quick update afterall ;-) Issue has been fixed in latest build (preview).
