### ISSUE TITLE
[Request for External] Codeunit 1201-"Process Data Exch." SetField method

### ISSUE THREAD

**Issue by muratkarabek** [microsoft/ALAppExtensions#2860]
Hi,

We need to use "SetField" method in "codeunit 1201" from our extension. It's not local and not external as well. Could you please make it external?

Thanks in advance!

**Comment by RomanZanizdra** [comment]
Hi muratkarabek. I'm afraid we cannot make this function External because it declared as unsafe due to insertion in the system table. Looks like you should find another way.

**Comment by RomanZanizdra** [comment]
Hi again. After taking a look one more time at system table is used in the function you asked to be external, I reconsidered it is safe and it will be exposed as external.
