### ISSUE TITLE
[Event Request] Codeunit 99000773 OnAfterTransferBOMComponent and OnBeforeProdOrderCompModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#2862]
In the existing Event trigger OnAfterTransferBOMComponent and OnBeforeProdOrderCompModify in codeunit 99000773 we Need the LineQtyPerUOM and ItemQtyPerUOM as additional Parameters to calculate our own fields:

OnAfterTransferBOMComponent(VAR ProdOrderLine,VAR ProdBOMLine[Level],VAR ProdOrderComp,LineQtyPerUOM : Decimal;ItemQtyPerUOM : Decimal);

OnBeforeProdOrderCompModify(ProdOrderComp,ProdBOMLine[Level],LineQtyPerUOM : Decimal;ItemQtyPerUOM : Decimal);

**Comment by AlexanderYakunin** [comment]
These parameters already exists, which version you are looking into?

**Comment by GuntherGebauer** [comment]
I am using NAVW114.01 BC365 Spring CU01 OnPrem - there the Parameters do not yet exist. I am waiting for BC365 Spring OnPrem CU02 which is not yet available. I have not checked the internal builds yet.
