### ISSUE TITLE
Add IsHandled logic to error preventing applications after posting date

### ISSUE THREAD

**Issue by jaytmalik** [microsoft/ALAppExtensions#2869]
This error prevents flexibility in allowing users to manage flexible payment applications.  Users need an option to apply payments flexibly when needed.

 IF TempGenJnlLine."Posting Date" < VendLedgEntry."Posting Date" THEN
    //               ERROR(
    //                 Text015,TempGenJnlLine."Document Type",TempGenJnlLine."Document No.",
    //                 VendLedgEntry."Document Type",VendLedgEntry."Document No.");

**Comment by AlexanderYakunin** [comment]
Please provide object identification and event specification. We do not accept requests without this information.

**Comment by jaytmalik** [comment]
Sorry.  Trying to get used to requesting things properly.

Table 81. in ValidateApplyRequirements function.

Required behavior is to control circumstances when we do not want the system to generate an error because it should be a user option to determine whether payments can be applied if before the invoice date.

Our code is tagged (//TC) here to show how we prevent an error based on P&P Setup option.

  TempGenJnlLine."Account Type"::Vendor:
    IF TempGenJnlLine."Applies-to ID" <> '' THEN BEGIN
      VendLedgEntry.SETCURRENTKEY("Vendor No.","Applies-to ID",Open);
      VendLedgEntry.SETRANGE("Vendor No.",TempGenJnlLine."Account No.");
      VendLedgEntry.SETRANGE("Applies-to ID",TempGenJnlLine."Applies-to ID");
      VendLedgEntry.SETRANGE(Open,TRUE);
      IF VendLedgEntry.FINDSET THEN
        REPEAT
          IF TempGenJnlLine."Posting Date" < VendLedgEntry."Posting Date" THEN
            ERROR(
              Text015,TempGenJnlLine."Document Type",TempGenJnlLine."Document No.",
              VendLedgEntry."Document Type",VendLedgEntry."Document No.");
        UNTIL VendLedgEntry.NEXT = 0;
    END ELSE
      IF TempGenJnlLine."Applies-to Doc. No." <> '' THEN BEGIN
        VendLedgEntry.SETCURRENTKEY("Document No.");
        VendLedgEntry.SETRANGE("Document No.",TempGenJnlLine."Applies-to Doc. No.");
        IF TempGenJnlLine."Applies-to Doc. Type" <> TempGenJnlLine."Applies-to Doc. Type"::" " THEN
          VendLedgEntry.SETRANGE("Document Type",TempGenJnlLine."Applies-to Doc. Type");
        VendLedgEntry.SETRANGE("Vendor No.",TempGenJnlLine."Account No.");
        VendLedgEntry.SETRANGE(Open,TRUE);
        //TC-BEGIN
        PurchSetup.GET; //TC
        IF VendLedgEntry.FIND('-') THEN
          IF NOT PurchSetup."Allow Early AP Payments" THEN //TC
            IF TempGenJnlLine."Posting Date" < VendLedgEntry."Posting Date" THEN
              ERROR(
                Text015,TempGenJnlLine."Document Type",TempGenJnlLine."Document No.",
                VendLedgEntry."Document Type",VendLedgEntry."Document No.");
        //TC-END
      END;

This may be a good option to add to the base product, thus eliminating a need fr an IsHandled event to replace the error code.

**Comment by AlexanderYakunin** [comment]
Already done, see this:

LOCAL CheckIfPostingDateIsEarlier(GenJournalLine : Record "Gen. Journal Line";ApplyPostingDate : Date;ApplyDocType : ' ,Payment,Invoice,Credit Memo,Finance Charge Memo,Reminder,Refund';ApplyDocNo : Code[20])
IsHandled := FALSE;
OnBeforeCheckIfPostingDateIsEarlier(GenJournalLine,ApplyPostingDate,ApplyDocType,ApplyDocNo,IsHandled);
IF IsHandled THEN
  EXIT;

IF GenJournalLine."Posting Date" < ApplyPostingDate THEN
  ERROR(
    Text015,GenJournalLine."Document Type",GenJournalLine."Document No.",ApplyDocType,ApplyDocNo);
