### ISSUE TITLE
Expose function ProcessAndGenerateEFTFile

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#2870]
Hello,

Could you please expose function ProcessAndGenerateEFTFile in CU 10098 - Generate EFT, we need it for extension development?

Thanks,
Radovan

**Comment by RomanZanizdra** [comment]
Hi Radovan.
I'm not sure we are ready to expose this function as external for SaaS development, it is in unsafe functions list. Could we found some other ways?

**Comment by radovandokic** [comment]
Hi Roman,
There is another way, to add publisher in page 10810 - Generate EFT Files, in OnOpen trigger;

![image](https://user-images.githubusercontent.com/34686682/60883260-0532b680-a24a-11e9-9a75-fbd77a97b69a.png)

We need to pass our Settlement Date, and to prevent end users to change it.

Can you add this publisher? I can create new request if needed.
