### ISSUE TITLE
Thi is likely a base defect versus an event requirement in table 81.

### ISSUE THREAD

**Issue by jaytmalik** [microsoft/ALAppExtensions#2871]
CASE AccType OF
  AccType::Customer:
    IF "Applies-to ID" <> '' THEN BEGIN
      IF FindFirstCustLedgEntryWithAppliesToID(AccNo,"Applies-to ID") THEN BEGIN
        CustLedgEntry.SETRANGE("Exported to Payment File",TRUE);
        "Exported to Payment File" := CustLedgEntry.FINDFIRST;
      END
    END ELSE
      IF "Applies-to Doc. No." <> '' THEN BEGIN //TC2018
        IF FindFirstCustLedgEntryWithAppliesToDocNo(AccNo,"Applies-to Doc. No.") THEN BEGIN
          "Exported to Payment File" := CustLedgEntry."Exported to Payment File";
          "Applies-to Ext. Doc. No." := CustLedgEntry."External Document No.";
        END;
        SetAmountWithCustLedgEntry; //TC2018
      END; //TC2018

**Comment by StanPesotskiy** [comment]
Could you provide a scenario explaining the problem related to extensibility?

**Comment by jaytmalik** [comment]
I think this is a bug with base software, and should not require an extension.  When a user picks and Applies-to Doc. No, the amount on the journal line is usually filled in based on the document selected for payment.  We had to add this base function in this function to conform to expected base behavior.  It's in the function SetJournalLineFieldsFromApplication in table 81, and should be in each case condition in this function (see TC2018 tags below._.

LOCAL SetJournalLineFieldsFromApplication()
"Exported to Payment File" := FALSE;
GetAccTypeAndNo(Rec,AccType,AccNo);
CASE AccType OF
  AccType::Customer:
    IF "Applies-to ID" <> '' THEN BEGIN
      IF FindFirstCustLedgEntryWithAppliesToID(AccNo,"Applies-to ID") THEN BEGIN
        CustLedgEntry.SETRANGE("Exported to Payment File",TRUE);
        "Exported to Payment File" := CustLedgEntry.FINDFIRST;
      END
    END ELSE
      IF "Applies-to Doc. No." <> '' THEN BEGIN //TC2018
        IF FindFirstCustLedgEntryWithAppliesToDocNo(AccNo,"Applies-to Doc. No.") THEN BEGIN
          "Exported to Payment File" := CustLedgEntry."Exported to Payment File";
          "Applies-to Ext. Doc. No." := CustLedgEntry."External Document No.";
        END;
        SetAmountWithCustLedgEntry; //TC2018
      END; //TC2018
  AccType::Vendor:
    IF "Applies-to ID" <> '' THEN BEGIN
      IF FindFirstVendLedgEntryWithAppliesToID(AccNo,"Applies-to ID") THEN BEGIN
        VendLedgEntry.SETRANGE("Exported to Payment File",TRUE);
        "Exported to Payment File" := VendLedgEntry.FINDFIRST;
      END
    END ELSE
      IF "Applies-to Doc. No." <> '' THEN BEGIN //TC2018
        IF FindFirstVendLedgEntryWithAppliesToDocNo(AccNo,"Applies-to Doc. No.") THEN BEGIN
          "Exported to Payment File" := VendLedgEntry."Exported to Payment File";
          "Applies-to Ext. Doc. No." := VendLedgEntry."External Document No.";
        END;
        SetAmountWithVendLedgEntry; //TC2018
      END; //TC2018
  AccType::Employee:
    IF "Applies-to ID" <> '' THEN BEGIN
      IF FindFirstEmplLedgEntryWithAppliesToID(AccNo,"Applies-to ID") THEN BEGIN
        EmplLedgEntry.SETRANGE("Exported to Payment File",TRUE);
        "Exported to Payment File" := EmplLedgEntry.FINDFIRST;
      END
    END ELSE
      IF "Applies-to Doc. No." <> '' THEN BEGIN //TC2018
        IF FindFirstEmplLedgEntryWithAppliesToDocNo(AccNo,"Applies-to Doc. No.") THEN
          "Exported to Payment File" := EmplLedgEntry."Exported to Payment File";
        SetAmountWithEmplLedgEntry; //TC2018
      END; //TC2018
END;

I think it would be very difficult to do this with an event because the base function is already here to correct the problem for the user.  An example of the code we would be trying to replicate is, and it seems there are too many variables needed to do this as an extension.:

LOCAL SetAmountWithCustLedgEntry()
IF "Currency Code" <> CustLedgEntry."Currency Code" THEN
  CheckModifyCurrencyCode(GenJnlLine."Account Type"::Customer,CustLedgEntry."Currency Code");
IF Amount = 0 THEN BEGIN
  CustLedgEntry.CALCFIELDS("Remaining Amount");
  SetAmountWithRemaining(
    PaymentToleranceMgt.CheckCalcPmtDiscGenJnlCust(Rec,CustLedgEntry,0,FALSE),
    CustLedgEntry."Amount to Apply",CustLedgEntry."Remaining Amount",CustLedgEntry."Remaining Pmt. Disc. Possible");
END;

**Comment by StanPesotskiy** [comment]
Functions SetAmountWithCustLedgEntry/SetAmountWithVendLedgEntry/SetAmountWithEmplLedgEntry are called in "Applies-to Doc. No.".OnLookup by functions LookUpAppliesToDocCust/Vend/Empl.
But it is not called in onvalidate triggers. This is not an extensibility issue. 
If you come up with a scenario (with repro steps) this would be a normal hotfix request that should be reported via the standard support channel.

**Comment by jaytmalik** [comment]
Thanks for the review.

We are never going to use the support channel as Microsoft charges us $500 each time we do this and we do not need the hassle of clearing these charges.

Microsoft needs a better way for partners to communicate defects thst we are unable to fix in Business Central.

Jay Malik
CEO, Tangicloud Technologies, Inc.
jay@tangicloud.com<mailto:jay.malik@centerlinesft.com>
877-786-9604 ext. 101<tel:877-786-9604;101> | www.tangicloud.com<http://www.tangicloud.com/>
CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

On Jun 19, 2019, at 12:55 AM, Stan Pesotskiy <notifications@github.com<mailto:notifications@github.com>> wrote:


Functions SetAmountWithCustLedgEntry/SetAmountWithVendLedgEntry/SetAmountWithEmplLedgEntry are called in "Applies-to Doc. No.".OnLookup by functions LookUpAppliesToDocCust/Vend/Empl.
But it is not called in onvalidate triggers. This is not an extensibility issue.
If you come up with a scenario (with repro steps) this would be a normal hotfix request that should be reported via the standard support channel.
