### ISSUE TITLE
[Bug / Application Refactoring] COD 11 - DateNotAllowed

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2882]
I'm working on a W1 extension that builds correct against a W1 database. When trying to build the same extension against a BE database (after downloading the BE symbols), the extension fails on one function call (**DateNotAllowed**), that has been modified by BC in the BE localisation, with an extra parameter 'TemplateName'. How to manage this scenario? 

![image](https://user-images.githubusercontent.com/25268332/59710421-3ef33d00-9209-11e9-874c-18fdaa9760b7.png)

_I want to avoid having to create a second BE extension with one object only (seems a lot of overhead, knowing the extension will be installed on other country databases as well)_

**Comment by StanPesotskiy** [comment]
This can only be resolved by move of BE localisation to W1 that MS usually does to minimise difference between country versions. Before this is done (no commitments now) you will have to have a special version of the extension for BE market.

**Comment by Pieterheinevdm** [comment]
What is the status of this issue?
can perhaps the function DateNotAllowed be overloaded by adding also the W1 version of this function to the BE lokalisation?
![image](https://user-images.githubusercontent.com/16033297/83640451-6ecb5a00-a5ac-11ea-8251-d0f83ab226d0.png)

**Comment by StanPesotskiy** [comment]
That had not been implemented.
Adding an overloaded function can be done.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
