### ISSUE TITLE
[Extensibility enhancement] Codeunit 5752 - Function GetSingleOutboundDoc

### ISSUE THREAD

**Issue by PauliusRudminas** [microsoft/ALAppExtensions#2883]
Perhaps the MODIFY could be moved to other place? Because in R5753, if anything subscribes to Warehouse Request - OnPostDataItem OnAfterCreateWhseDocuments, and modifies the headers - it will break the status modification in C5752, because of old entry modification. 

The problem was found in the case of Warehouse Shipment Creation (Warehouse Receipt Creation works fine, as it bypasses C5752, but I think the same could be done for inbound case).

I suggest maybe moving the modification to R5753, as with my subscriber, I update header, also update status, tehn commented out the code in C5752 and it seems to work ok:

![image](https://user-images.githubusercontent.com/32515561/59744204-b1e8cc00-927a-11e9-8a80-638010759680.png)

**Comment by AlexanderYakunin** [comment]
This is already fixed in master and will be available for next major update
