### ISSUE TITLE
Codeunit 5704 OnBeforeGetNextNo() additional Var TransHeader

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#2888]
Hello,

we need the additional variable TransHeader in the new Publisher OnBeforeGetNextNo().
Is this possible?

Thanks in advance,
best regards,
K.

**Comment by AlexanderYakunin** [comment]
Codeunit 7304 does not have OnBeforeGetNextNo. Please verify your request

**Comment by AlexanderYakunin** [comment]
I'm closing this request. Please create new one when you can make this event ask with needed information (event name and parameters, place in the code).

**Comment by KReinmann** [comment]
Oh, I'm sorry, I made a mistake in the description. I meant Codeunit 5704. With issue #998 a new publisher was set.

**Comment by KReinmann** [comment]
Hi,
@AlexanderYakunin

Are there new insights here?
Thanks in advance,
best regards,
Kathrin

**Comment by AlexanderYakunin** [comment]
We have OnBeforeGenNextNo(TransShptHeader,TransHeader);

Type in event name should be corrected later, cannot touch it right now.

**Comment by KReinmann** [comment]
Perfect, thank you for your answer.
