### ISSUE TITLE
[Event Request] Codeunit 7312 - Function CreateTempLine2

### ISSUE THREAD

**Issue by PauliusRudminas** [microsoft/ALAppExtensions#2889]
Publisher with handler pattern is needed in function CreateTempLine2 (C7312), for custom line creation. At the moment we are using it to bypass bin assignment.

The parameters are the same as for function, except for additional WhseSource parameter.
I've set up parameters IncludeSender and GlobalVarAccess to True, as I think that would be useful, so including those would also be appreciated.

![image](https://user-images.githubusercontent.com/32515561/59750151-05611700-9287-11e9-9b98-770182f5f50c.png)

**Comment by AlexanderYakunin** [comment]
Why you need to bypass bin assignment using events? You can do it using Location setup.
