### ISSUE TITLE
[Event Request] Codeunit 7313 - Function SetValues

### ISSUE THREAD

**Issue by PauliusRudminas** [microsoft/ALAppExtensions#2890]
Publisher needed (modification of existing one) with parameters in function SetValues (C7313), same as in C7312 - for overwriting values.  At the moment we are using it to overwrite DoNotFillQtyToHandle parameter.

![image](https://user-images.githubusercontent.com/32515561/59750893-37bf4400-9288-11e9-9692-cf4cbaf5a64f.png)

**Comment by bcmako** [comment]
What is the preferred approach here? On the one hand parameters are extended, on the other hand the property "GlobalVarAccess" is set in the Publisher.
