### ISSUE TITLE
[Event Request] Codeunit 7322 - Function CreateTempHandlingSpec

### ISSUE THREAD

**Issue by PauliusRudminas** [microsoft/ALAppExtensions#2892]
Publisher with handler pattern is needed in function CreateTempHandlingSpec (C7322) - for custom tracking setup. 

Parameters are the same as for function. GlobarVarAccess and Include sender are set to true.

![image](https://user-images.githubusercontent.com/32515561/59751627-8d482080-9289-11e9-97af-deec81776b51.png)

**Comment by AlexanderYakunin** [comment]
We do not provide GlobalVar access, this property was discontinued.
