### ISSUE TITLE
Event request cod90 OnBeforePostCombineSalesOrderShipment

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#2897]
Can the OnBeforePostCombineSalesOrderShipmentpublisher be added to codeunit:90:"Purch.-Post"?

code:
[Modified.txt](https://github.com/microsoft/AL/files/3301050/Modified.txt)
[Original.txt](https://github.com/microsoft/AL/files/3301051/Original.txt)

**Comment by AlexanderYakunin** [comment]
Closed as duplicate of #2898
