### ISSUE TITLE
Import Configuration Package on Install

### ISSUE THREAD

**Issue by Frederig** [Microsoft/ALAppExtensions#290]
Hi,

I've created an app which needs some default setup data.
After installation I can manually import a configuration package but what I would like is to automatically import the configuration package on installation if the setup table is still empty.

I created a Codeunit of the subtype 'install' and added trigger OnInstallAppPerCompany() and I also added the rapidstart file in a subfolder in the app but I don't know how to handle the import from here.

I could not find an example on how to do this in blogs or documentation.

![image](https://user-images.githubusercontent.com/43371288/48120252-eff82900-e271-11e8-8e0a-6f79d7852186.png)

**Comment by JesperSchulz** [comment]
This GitHub repository is dedicated to handling issues with published apps and extensibility requests for the latest release of Business Central.

To get help on general questions please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
