### ISSUE TITLE
[Enum Request] Table "Comment Line" 97 field "Table Name" 

### ISSUE THREAD

**Issue by mou5a123** [microsoft/ALAppExtensions#2901]
Please implement the field "**Table Name**" in Table "**Comment Line**" 97 as Enum.

**Comment by SirBETE** [comment]
Please search first: #1509 & #643

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
