### ISSUE TITLE
[BUG] Page 5870 Item Filter 

### ISSUE THREAD

**Issue by AndriiHrynyuk** [microsoft/ALAppExtensions#2907]
Hi,

We are having the bug on Item Filter field on Page 5870 BOM Structure. The issue seems to be present only in web client.

Steps to reproduce : 

1. Open the Item List.
2.  Filter the items using Search.
3. Navigate to the Card of any item that is on a list.
4. Press "Structure" action.
5. When page BOM Structure is opened, enter the number of an item that was outside the filters applied on the Item List page. 
6. You will receive an error 'There is no Item within the filter. Filters: ...'.

The issue is caused by the RefreshPage function that is invoked when Item Filter is validated.
![image](https://user-images.githubusercontent.com/45200121/59827260-e0c97580-9340-11e9-929b-6efa9b94f754.png)

The system applies filters to an item that was previously copied from a Rec in InitItem function.
![image](https://user-images.githubusercontent.com/45200121/59827201-b5468b00-9340-11e9-95ac-08334195c841.png)

Creating the copy of InitItem function, where item is not copied but retrieved with GET seems to solve the problem.
![image](https://user-images.githubusercontent.com/45200121/59828036-c42e3d00-9342-11e9-9655-1929836774d5.png)

Could you please investigate this issue and provide a solution?

Thank you in advance!

**Comment by StanPesotskiy** [comment]
Hi @AndriiHrynyuk ,
Thank you for the request. You put good repro steps and it can be handled by the support team.
To submit a new technical support incident go to partner dashboard: https://partner.microsoft.com/.
This ALAppExtensions section on GitHub is for issues related to extensibility (mostly events and external methods).
