### ISSUE TITLE
TAB37 Sales Line - GetSalesHeader - Return SalesHeader

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#2909]
Shouldn't `GetSalesHeader` on TAB37 Sales Line return the current Sales Header?
So we can use that same global record?
```
[External] GetSalesHeader(VAR SalesHeader : record "Sales header")
TESTFIELD("Document No.");
IF ("Document Type" <> SalesHeader."Document Type") OR ("Document No." <> SalesHeader."No.") THEN BEGIN
  SalesHeader.GET("Document Type","Document No.");
  IF SalesHeader."Currency Code" = '' THEN
    Currency.InitRoundingPrecision
  ELSE BEGIN
    SalesHeader.TESTFIELD("Currency Factor");
    Currency.GET(SalesHeader."Currency Code");
    Currency.TESTFIELD("Amount Rounding Precision");
  END;
END;
```

**Comment by fvet** [comment]
Some scenarios might even need to access the **Currency** global that is set by the same function.
So ideally, the function (GetSalesHeaderAndCurrency) should return Currency as well. (Either we should have access to global vars on the base objects)

**Comment by SirBETE** [comment]
#1446

**Comment by SirBETE** [comment]
#1446

**Comment by StanPesotskiy** [comment]
This cannot be done in the released version as we cannot modify public methods, but is going to be done for Tables 37/39 in October 2019 release, where it is possible to overload functions.
