### ISSUE TITLE
[External] Codeunit 7312 Create Pick - CalcQtyToPickBase

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#2913]
Dear AL team,

We would like to call the function "CalcQtyToPickBase" from outside. To do this, the TempWhseActivLine would have to be passed as an additional parameter. With that you have the possibility to call this function in event subscriber, for example in OnBeforeCalcBin.

**Comment by RomanZanizdra** [comment]
Hi bcmako.
Couple of questions for clarification.
1) Are you sure about the name of event, I cannot find it.
2) TempWhseActivLine is global variable. If I understand you correctly it will be build inside CalcQtyToPickBase function returned back as you asked by var. What's next?

**Comment by RomanZanizdra** [comment]
Hi bcmako. Any update from you?

**Comment by RomanZanizdra** [comment]
bcmako?

**Comment by bcmako** [comment]
Hi Roman,

please excuse the late feedback. I was on vacation. 
Regarding topic 1: The correct name of the event is OnBeforeCalcPickBin
Regarding topic 2: The CalcPickBinBase function calculates the quantity for picking and calculates a subtotal based on the TempWhseActiveLine, which is already filled at this time and is available as global. For my concrete requirement it is then sufficient that the function CalcPickBinBase becomes global/external. The TempWhseActiveLine parameter is not required.
Thank you very much for your support.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
