### ISSUE TITLE
[Event Request] Codeunit 2 Company-Initialize

### ISSUE THREAD

**Issue by MarcoEymer** [microsoft/ALAppExtensions#2919]
Could we please have a new event OnBeforeCompanyInitalize in the OnRun()-Trigger

`OnRun()

Window.OPEN(Text000);

//>>>>
OnBeforeCompanyInitialize;
//<<<<

InitSetupTables;
AddOnIntegrMgt.InitMfgSetup;
InitSourceCodeSetup;
[...]
`

**Comment by AlexanderYakunin** [comment]
Already implemented as OnBeforeRun

**Comment by MarcoEymer** [comment]
> Already implemented as OnBeforeRun

Okay, nice - but where will i find it? Not in BC13 CU7 or BC14RTM
