### ISSUE TITLE
[Event Request] Codeunit 415  OnBeforeReleasePurchaseDoc(PurchaseHeader,PreviewMode)

### ISSUE THREAD

**Issue by sradouan** [microsoft/ALAppExtensions#2927]
[Event Request] Codeunit 415  OnBeforeReleasePurchaseDoc(PurchaseHeader,PreviewMode)

Any Idea on How to bypass the CheckPurchaseReleaseRestrictions?
I want to be able to change the boolean variable (SkipCheckReleaseRestrictions) before the function.
OnBeforeReleasePurchaseDoc(PurchaseHeader,PreviewMode);
IF NOT (PreviewMode OR SkipCheckReleaseRestrictions) THEN
CheckPurchaseReleaseRestrictions;
Thanks.
Version: Platform 14.0.29530.0 + Application 29537 (US Dynamics NAV 14.0)

**Comment by AlexanderYakunin** [comment]
You need to use this function:

[External] SetSkipCheckReleaseRestrictions()
SkipCheckReleaseRestrictions := TRUE;

**Comment by sradouan** [comment]
Hi Alexander, 
I'm not able to use it from my codeunit, the code unit 415 is not a single instance.
Thanks for the answer.
