### ISSUE TITLE
[Event Request] Codeunit 21, 1 new Event in DACH Localization

### ISSUE THREAD

**Issue by AndreBreitenbach** [Microsoft/ALAppExtensions#293]
We need 1 new Events in Codeunit 21 (DACH Localization) to handle ISV Code.
1)	Function CheckBlockShipmentWhenNegativeInventory
![image](https://user-images.githubusercontent.com/40287548/45421496-80105c80-b68d-11e8-9c28-ea5038738a4c.png)
The Event needs the following parameters:
![image](https://user-images.githubusercontent.com/40287548/45421504-87376a80-b68d-11e8-8731-b06ff00cb14e.png)

Thanks

**Comment by JesperSchulz** [comment]
I am trying to find heads and tails in this issue, but I cannot seem to find function CheckBlockShipmentWhenNegativeInventory in any version of BC, neither W1 nor DACH nor DE. I'm hence closing this issue, as I believe the functionality has been removed / replaced with the mentioned W1-feature. I can, however, not find that feature based on the information I have in this issue.
Please open a new issue, if you need further assistance on this one. For this one, I don't see any work we can do.
