### ISSUE TITLE
Event Request / Suggestion: Codeunit 6620 Copy Document Mgt. - Document Types

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/ALAppExtensions#294]
Most of the events in Codeunit 6620 Copy Document Mgt. pass some kind of "Document Type". Be it FromDocType or ToDocType or similar. The problem here is, that it is an option that is defined as a global variable inside the codeunit. The subscriber has no way of knowing what exactly the passed value actually means.

At the moment I have created a copy of the variables `PurchDocType` and `SalesDocType` a.s.o. inside my subscribers to know what the passed value means - hoping that they will never change.

It would be way cleaner if you would instead pass the classic SourceType, SourceSubtype, SourcID-pairs that uniquely identify the source record and does not require any kind of option or enu,m. This would also make it possibly extensible.

**Comment by JesperSchulz** [comment]
Closing issue, as the suggestion was added to backlog.
