### ISSUE TITLE
[Event Request] Page 6510 Function WriteToDatabase 

### ISSUE THREAD

**Issue by sharkphoenix** [microsoft/ALAppExtensions#2942]
Please add after the Line
"  FOR ModifyLoop := 1 TO 2 DO BEGIN
    IF TempItemTrackLineModify.FIND('-') THEN
      REPEAT
        IF xTempItemTrackingLine.GET(TempItemTrackLineModify."Entry No.") THEN BEGIN"
(Page 6510 Function WriteToDatabase)

The event:
OnModifyDatabase(tempitemtracklinemodify);

And also after the line:

     " IF TempItemTrackLineModify.GET(TempItemTrackLineInsert."Entry No.") THEN
        TempItemTrackLineInsert.TRANSFERFIELDS(TempItemTrackLineModify);"

 the Event:
OnInsertDatabaseEntry(TempItemTrackLineInsert);

We want to create automatically the Lot and Serial No. Informations and transfer fields.

**Comment by AlexanderYakunin** [comment]
First event already exists
      IF xTempItemTrackingLine.GET(TempItemTrackLineModify."Entry No.") THEN BEGIN
          // Process decreases before increases
          OnWriteToDatabaseOnBeforeRegisterDecrease(TempItemTrackLineModify);
          Decrease := (xTempItemTrackingLine."Quantity (Base)" > TempItemTrackLineModify."Quantity (Base)");
   
Second event also exist
      IF TempItemTrackLineModify.GET(TempItemTrackLineInsert."Entry No.") THEN
        TempItemTrackLineInsert.TRANSFERFIELDS(TempItemTrackLineModify);
      OnWriteToDatabaseOnBeforeRegisterInsert(TempItemTrackLineInsert);
      IF NOT RegisterChange(TempItemTrackLineInsert,TempItemTrackLineInsert,ChangeType::Insert,FALSE) THEN
