### ISSUE TITLE
[Event Change Request] Codeunit 5988 OnAfterInitialize(VAR ServiceHeader : Record "Service Header";VAR ServiceLine : Record "Service Line")

### ISSUE THREAD

**Issue by ricardopaiva** [microsoft/ALAppExtensions#2946]
The event OnAfterInitialize(VAR ServiceHeader : Record "Service Header";VAR ServiceLine : Record "Service Line") should include the CloseCondition as an additional parameter like this:

OnAfterInitialize(VAR ServiceHeader : Record "Service Header";VAR ServiceLine : Record "Service Line";VAR CloseCondition : Boolean)

We have a few customers that keep the Service Order document even when it is totally shipped and invoiced/consumed.
Business Central deletes the Service Order if you post it from the Service Order itself and it is completely invoiced/consumed. With the request event you can change the default behavior and keep the service order using the following subscribers:

    [EventSubscriber(ObjectType::Codeunit, 5988, 'OnAfterInitialize', '', false, false)]
    local procedure UpdateCloseCondition_OnAfterInitialize_ServDocumentsMgt(var ServiceHeader: Record "Service Header"; var ServiceLine: Record "Service Line"; var CloseCondition: Boolean)
    begin
        if ServiceHeader."Document Type" = ServiceHeader."Document Type"::Order then
            CloseCondition := false;
    end;

    [EventSubscriber(ObjectType::Codeunit, 5988, 'OnBeforeFinalize', '', false, false)]
    local procedure UpdateCloseCondition_OnBeforeFinalize_ServDocumentsMgt(var ServiceHeader: Record "Service Header"; var CloseCondition: Boolean)
    begin
        if ServiceHeader."Document Type" = ServiceHeader."Document Type"::Order then
            CloseCondition := false;
    end;

Without the OnAfterInitialize subscriber, the Service Order is not deleted but the Qty. Shipped/Qty. Invoiced/Qty. Consumed fields are not updated.

**Comment by AlexanderYakunin** [comment]
This is already done
OnAfterInitialize(PassedServiceHeader,PassedServiceLine,CloseCondition);

**Comment by ricardopaiva** [comment]
Great news.

@AlexanderYakunin this is my first event request. By “This is already done” do you mean and can I assume that it will be available in the next BC Cumulative Update, which is the 9th?

Thanks
