### ISSUE TITLE
[Key Request] Table 5108 "Sales Line Archive" - Two new keys

### ISSUE THREAD

**Issue by esuarkfalo** [microsoft/ALAppExtensions#2958]
For page sorting we need two new keys with Standard fields only. Currently it is not passible to use a table Extension to create new keys on existing tables.

The new keys are:

**1. First key**

Document Type,Sell-to Customer No.,Type,No.

**2. Second key**

Document Type,Bill-to Customer No.,Type,No.

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
