### ISSUE TITLE
[Event Request] Codeunit 11, 80, 90 and more

### ISSUE THREAD

**Issue by stephanweidmann** [Microsoft/ALAppExtensions#296]
In posting and check codeunits, the CheckDimValuePosting will be called with a generated TableID/NoArray

Since most CreateDim functions now allow to add own dimension source tables via
OnAfterCreateDimTableIDs(Rec,CurrFieldNo,TableID,No); there should be the possibility to extend the check .
(If you Setup that master data XY must be posted with Dimension X Value Y, this should be checked here.)

  TableID[5] := DATABASE::Campaign;
  No[5] := "Campaign No.";
  OnAfterCreatedTableDims(GenJnlLine,TableID,No); // NEW
  IF NOT DimMgt.CheckDimValuePosting(TableID,No,"Dimension Set ID") THEN
    ThrowGenJnlLineError(GenJnlLine,Text012,DimMgt.GetDimValuePostingErr);
should allow this.

There are several positions where this Publisher should be added.

CU 11: 
CU 80, 90,  CheckDimValuePostingHeader, CheckDimValuePostingLine
CU 1011 and many more

**Comment by JesperSchulz** [comment]
Closing issue, as work is in progress.
