### ISSUE TITLE
[Key Request] Table 39 "Purchase Line" - Two new keys

### ISSUE THREAD

**Issue by esuarkfalo** [microsoft/ALAppExtensions#2963]
For page sorting we need two new keys with Standard fields only. Currently it is not passible to use a table Extension to create new keys on existing tables.

The new keys are:

**1. First key**

Document Type,Buy-from Vendor No.,Type,No.

**2. Second key**

Document Type,Pay-to Vendor No.,Type,No.

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
