### ISSUE TITLE
[Key Request] Table 125 "Purch. Cr. Memo Line" - Two new keys

### ISSUE THREAD

**Issue by esuarkfalo** [microsoft/ALAppExtensions#2967]
For page sorting we need two new keys with Standard fields only. Currently it is not passible to use a table Extension to create new keys on existing tables.

The new keys are:

**1. First key**

Buy-from Vendor No.,Type,No.

**2. Second key**

Pay-to Vendor No.,Type,No.

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
