### ISSUE TITLE
[Key Request] Table 36 "Sales Header" - One new key

### ISSUE THREAD

**Issue by esuarkfalo** [microsoft/ALAppExtensions#2969]
Currently it is not passible to use a table Extension to create new keys on existing tables. In these special case it is not possible to use a query for substitution of a key.

**New Key**

Document Type,Combine Shipments,Bill-to Customer No.,Sell-to Customer No.,Currency Code,EU 3-Party Trade,Dimension Set ID

**Comment by AlexanderYakunin** [comment]
In general we do not add keys for partner extensions. Please provide justification why do you need this key.

**Comment by esuarkfalo** [comment]
Sorry for the delayed answer to this specific request. The requested key above is used in the reports 295 "Combine Shipments" (for orders and invoices) and 663 (for return orders and credit memos).

With the CU02 (365BC Spring 19) and CU09 (365BC Fall 18) Microsoft has implemented a part of our solution in the the report 295, but not in report 6653. With this implementation the invoices will also be created when the "sell-to customer no." changes.

But without the requested key this will not really work as expected. Let me explain it.

Currently the report is using the key "Document Type,Combine Shipments,Bill-to Customer No.,Currency Code,EU 3-Party Trade,Dimension Set ID".

Assume that you have 10 orders where the values of the fields in this key are equal. But the value in the "sell-to customer no." are different in the following order:
Cust1, Cust2, Cust1, Cust1, Cust3, Cust2, Cust1, Cust2, Cust2 and Cust3.

With the current Standard implementation you will get 8 invoices in the following order
Cust1, Cust2, Cust1 (2 Orders), Cust3, Cust2, Cust1, Cust2 (2 orders) and Cust3.

But an user expect 3 invoices one per cust.

Using the requested key instead you will get only the expected 3 invoices
Cust1 (4 orders), Cust 2 (4 orders) and cust3 (2 orders).

Therefore you Need the requested key for a correct working. And you should implement the changes of report 295 also in the report 6653.

**Comment by AlexanderYakunin** [comment]
With latest enhancements for table keys in extensions it should be possible to solve such issues.
