### ISSUE TITLE
[Event Request] Codeunit 333 Issue 1339 Not Completely Implemented

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#297]
According to #1339 (shipped) I should find new events to extend the document grouping by customized fields in D365BC RTM. But some are still missing:

**Function Code**
```
[...]
  SETCURRENTKEY(
    "Worksheet Template Name","Journal Batch Name","Vendor No.",
    "Sell-to Customer No.","Ship-to Code","Order Address Code","Currency Code",
    "Ref. Order Type","Ref. Order Status","Ref. Order No.",
    "Location Code","Transfer-from Code","Purchasing Code");
  // >> NEW
  OnBeforeFindReqLines(VAR ReqLine);
  // << NEW
  
  IF FIND('-') THEN
[...]
```

**From** https://github.com/Microsoft/AL/issues/1339#issuecomment-361897790 (Jan 31)
- **Function  Code (end)** 
Code refactoring for new event OnCheckNewNameNecessary

**Comment by SKeiler** [comment]
Hello,

is here something new? We also have the Event Request OnBeforeFindReqLines to change the existing Keys (post 1) and FinalizeOrderHeader (post 3). 

Post 4 seems to be solved.

**Comment by NKarolak** [comment]
@SKeiler 
**OnBeforeFindReqLines** has been solved in 14.05 using **OnBeforeSetReqLineSortingKey**:
![image](https://user-images.githubusercontent.com/34504100/64961579-23deaa80-d896-11e9-9dd3-41f2bf0a836f.png)

**FinalizeOrderHeader** is also solved, using **OnFinalizeOrderHeaderOnAfterSetFiltersForNonRecurringReqLine**

![image](https://user-images.githubusercontent.com/34504100/64961827-98b1e480-d896-11e9-8d6d-7181e81ed703.png)

**Comment by NKarolak** [comment]
@AlexanderYakunin  The last open issue is this request part:

**Function InsertPurchOrderLine** 
![capture](https://user-images.githubusercontent.com/34504100/46292903-94a38e80-c581-11e8-87d7-6ec0d010f688.JPG)

What is the current state?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
