### ISSUE TITLE
[Key Request] Table 25 "Vendor Ledger Entry" - One new key

### ISSUE THREAD

**Issue by esuarkfalo** [microsoft/ALAppExtensions#2970]
Currently it is not passible to use a table Extension to create new keys on existing tables. In these special case it is not possible to use a query for substitution of a key.

**New Key**

External Document No.,Vendor No.,Open,Positive

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
