### ISSUE TITLE
[Key Request] Table 17 "G/L Entry" - One new key

### ISSUE THREAD

**Issue by esuarkfalo** [microsoft/ALAppExtensions#2972]
Currently it is not passible to use a table Extension to create new keys on existing tables. In these special case it is not possible to use a query for substitution of a key.

**New Key**

Gen. Posting Type,VAT Bus. Posting Group,VAT Prod. Posting Group,Posting Date,G/L Account No.

**Comment by AlexanderYakunin** [comment]
In general we do not add keys for partner extensions. Please provide justification why do you need this key.

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
