### ISSUE TITLE
[Event Request] T6651 InsertInvLineFromRetShptLine()

### ISSUE THREAD

**Issue by MarcelloDellaCostaCapBS** [microsoft/ALAppExtensions#2976]
Hello Team,
we need a new publisher (OnBeforeInsertInvLineFromRetShptLine) with variables passed by var in order to modify standard PurchLine

PurchLine.Description := STRSUBSTNO(Text000,"Document No.");

OnBeforeInsertInvLineFromRetShptLine(PurchLine);

PurchLine.INSERT;
NextLineNo := NextLineNo + 10000;

**Comment by AlexanderYakunin** [comment]
This event already exists for long time?

  OnBeforeInsertInvLineFromRetShptLine(PurchLine,PurchOrderLine,Rec);
  PurchLine.INSERT;
  OnAfterInsertInvLineFromRetShptLine(PurchLine,PurchOrderLine,Rec);
