### ISSUE TITLE
[Event Request] Codeunit 80/90: Issue 1338 not solved as expected

### ISSUE THREAD

**Issue by NKarolak** [Microsoft/ALAppExtensions#298]
With #1338 ("ships in future update") I was supposted to suppress the document deletion even after complete invoicing.
However, the final implementation (D365BC OnPrem RTM) does not allow it, at least there is no new KeepOrder variable as suggested in Issue 1338:
![capture](https://user-images.githubusercontent.com/34504100/46290478-7dfa3900-c57b-11e8-9b91-b0f2150c111a.JPG)

If I was supposed to use the **OnBeforeFinalizePosting** event instead, then its parameter **EverythingInvoiced** needs to be VAR instead.

**Comment by AlexanderYakunin** [comment]
Parameter EverythingInvoiced is VAR in COD80 event OnBeforeFinalizePosting, please check in BC code, not in NAV2018.

**Comment by AlexanderYakunin** [comment]
LOCAL [IntegrationEvent] OnBeforeFinalizePosting(VAR SalesHeader : Record "Sales Header";VAR TempSalesLineGlobal : TEMPORARY Record "Sales Line";VAR EverythingInvoiced : Boolean;SuppressCommit : Boolean)

**Comment by NKarolak** [comment]
Maybe some mismatch between docker and DVD? I have used the DVD: https://mbs.microsoft.com/partnersource/germany/support/support-news/bconpremdownload

**Comment by NKarolak** [comment]
The VAR parameter has been added in D365BC CU1 On-Prem
