### ISSUE TITLE
Codeunit 60 Sales-Calc. Discount - Handling service charge

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#2980]
We would like to request a small refactoring of handling service charge and a publisher to overrule default handling. Our proposal would be to change the following code in fucntion CalculateInvoiceDiscount (also reduces redundant code):

First place where sales line exists:

          IF NOT TempServiceChargeLine.ISEMPTY THEN BEGIN
            TempServiceChargeLine.FINDLAST;
            SalesLine2.GET("Document Type","Document No.",TempServiceChargeLine."Line No.");
            ///// START --> replace code by function
            //IF SalesHeader."Prices Including VAT" THEN
            //  SalesLine2.VALIDATE(
            //    "Unit Price",
            //    ROUND(
            //      (1 + SalesLine2."VAT %" / 100) * CustInvDisc."Service Charge",
            //      Currency."Unit-Amount Rounding Precision"))
            //ELSE
            //  SalesLine2.VALIDATE("Unit Price",CustInvDisc."Service Charge");
            // introduce new function
            SalesLineSetServiceCharge(SalesLine2, SalesHeader);
            ///// END
            SalesLine2.MODIFY;
          END ELSE BEGIN

Next place after new sales line is created : 

            IF SalesLine2."Document Type" IN
               [SalesLine2."Document Type"::"Return Order",SalesLine2."Document Type"::"Credit Memo"]
            THEN
              SalesLine2.VALIDATE("Return Qty. to Receive",SalesLine2.Quantity)
            ELSE
              SalesLine2.VALIDATE("Qty. to Ship",SalesLine2.Quantity);
            ///// START --> replace code by function
            //IF SalesHeader."Prices Including VAT" THEN
            //  SalesLine2.VALIDATE(
            //    "Unit Price",
            //    ROUND(
            //      (1 + SalesLine2."VAT %" / 100) * CustInvDisc."Service Charge",
            //      Currency."Unit-Amount Rounding Precision"))
            //ELSE
            //  SalesLine2.VALIDATE("Unit Price",CustInvDisc."Service Charge");
            // introduce new function
            SalesLineSetServiceCharge(SalesLine2, SalesHeader);
            ///// END
            SalesLine2.INSERT;

New function where we move the standard code and add a handled publisher construction:

    LOCAL PROCEDURE SalesLineSetServiceCharge@11095586(VAR SalesLine2@11095585 : Record 37;SalesHeader@11095587 : Record 36);
    VAR
      IsHandled@11095588 : Boolean;
    BEGIN
      ///// START
      OnBeforeSetServiceCharge(SalesLine2, SalesHeader, CustInvDisc, IsHandled);
      IF (IsHandled) THEN
      BEGIN
        EXIT;
      END;
      ///// END

      IF SalesHeader."Prices Including VAT" THEN
        SalesLine2.VALIDATE(
          "Unit Price",
          ROUND(
            (1 + SalesLine2."VAT %" / 100) * CustInvDisc."Service Charge",
            Currency."Unit-Amount Rounding Precision"))
      ELSE
        SalesLine2.VALIDATE("Unit Price",CustInvDisc."Service Charge");
    END;

Signature of the publisher:

    [Integration]
    LOCAL PROCEDURE OnBeforeSetServiceCharge@11095588(VAR SalesLine@11095585 : Record 37;SalesHeader@11095586 : Record 36;CustInvoiceDisc@11095587 : Record 19;VAR IsHandled@11095588 : Boolean);
    BEGIN
    END;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
