### ISSUE TITLE
Amount In Words 

### ISSUE THREAD

**Issue by vikihdw** [Microsoft/ALAppExtensions#299]
FormatNoText not available in D365 BC US Check report. 

someone please help me on this... how to show "amount in words" in D365 Business Central US 

the Function "FormatNoText" Available in D365 BC W1, GB version but not in US.

**Comment by mazhelez** [comment]
Hi @vikihdw,

Have you tried using `FormatNoText` in REP10400 (_Check Translation Management_)?
I hope it helps!

**Comment by vikihdw** [comment]
Hi @mazhelez 

yeah, we tried that one but which is specific to BC US and REP 10400 not available in D365 BC GB version

we are developing Common extension App for US and GB Version of BC, let me know how we can approach in this case.
