### ISSUE TITLE
Extension using the Reservation System is Impossible

### ISSUE THREAD

**Issue by johndcollins** [microsoft/ALAppExtensions#3003]
I'm trying to make an extension where I have a Journal Line and other standard functionality where i want to use the reservation system, however, it's impossible to use the existing reservation system because the functions are either hidden, not available in extension development or used in a codeunit that I can't extend. I basically have to re-write all reservation codeunits to be able to do this.

**Comment by AlexanderYakunin** [comment]
Reservation system is complex module and cannot be enabled for extensions at once. Please provide more detailed information about missing external procedures, events or anything else needed for you.

**Comment by RomanZanizdra** [comment]
Hi johndcollins.
Any update from your side?

**Comment by RomanZanizdra** [comment]
Hi johndcollins.
I suggest to close this issue for now. Feel free to re-open it when you will have enough information to provide for your requirements.
