### ISSUE TITLE
[Event Request] Page 30 - OnAfterSetFieldsVisible

### ISSUE THREAD

**Issue by SSZurmussen7112** [microsoft/ALAppExtensions#3008]
Hi Team,

To be able to manipulate the visibility of controls on page 30 Item Card, some changes would be needed. For our function especially the Description control is needed. But to be prepared to manage also other controls I suggest the following changes:

- A new global variable: DescriptionFieldVisible : BOOLEAN

`      DescriptionFieldVisible@50000 : Boolean;
`
- Assign this new global variable into the property Visible of control Description
- Create a new local function: SetFieldsVisible

```
    LOCAL PROCEDURE SetFieldsVisible@50003();
    BEGIN
      // >> NEW
      SetNoFieldVisible;

      DescriptionFieldVisible := TRUE;

      OnAfterSetFieldsVisible;
      // << NEW
    END;
```
- Use this new function in the OnOpenPage-trigger instead of SetNoFieldVisible

```
    OnOpenPage=VAR
                 PermissionManager@1000 : Codeunit 9002;
               BEGIN
                 IsFoundationEnabled := ApplicationAreaMgmtFacade.IsFoundationEnabled;
                 EnableControls;
                 // >> NEW
                 // SetNoFieldVisible;
                 SetFieldsVisible;
                 // << NEW
                 IsSaaS := PermissionManager.SoftwareAsAService;
               END;
```
- Create a new publisher: OnAfterSetFieldVisible with GlobalVarAccess: Yes

```
    [Integration(DEFAULT,TRUE)]
    LOCAL PROCEDURE OnAfterSetFieldsVisible@50001();
    BEGIN
      // NEW
    END;
```

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
We'd prefer not to make this kind of changes in pages without strong justification why you need this? Do you also consider effect for other partners and customers. And we cannot use property GlobalVarAccess, this property have been discontinued.

**Comment by SSZurmussen7112** [comment]
At first: Thanks for the quick reply!
I need such changes to replace the NAV standard Description-control with an own one. And my own Description-control contains some programming in the OnLookup-trigger to allow only a selection of descriptions from an own table, a kind of Item Description Catalog.
My idea was to have a publisher were I can hide existing controls. And with my suggestion in future it would be very easy to hide also other controls. Each time you have only to create a new global BOOLEAN variable and put it to the Visible-property of such control.
Is there any other chance to hide a NAV standard control?
If not I have to change my programming, e.g.: "Please enter a "?" to open the Item Description Catalog"

**Comment by SSZurmussen7112** [comment]
After some research it would be enough to get only the mentioned global variable:

`DescriptionFieldVisible@50000 : Boolean;`

And this new global variable must be inserted into the property Visible of control Description. (It's nearly the same as in field "No.")

The rest I can manage with the standard events of pages.
Is this possible for you?

Thanks and have a nice weekend!
Regards,
Stephan
