### ISSUE TITLE
Table 36 new publisher in fct. ConfirmUpdateCurrencyFactor

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#3011]
Hello,

for our application we ne a new publisher in table 38 Purchase Header - function ConfirmUpdateCurrencyFactor() as described bellow:
![image](https://user-images.githubusercontent.com/46744680/60253080-c6a50f80-98cb-11e9-8270-89b5afb89d90.png)
Thanks in advance,
best regards,
Kathrin

**Comment by KReinmann** [comment]
Hi, 
I noticed a mistake in my description of Headline (T36), the screenshot Shows the Table 38. I hope the new Publisher was integrated to T38?

Best regards,
Kathrin

**Comment by StanPesotskiy** [comment]
It has been added as OnBeforeConfirmUpdateCurrencyFactor(Rec,HideValidationDialog); to Tab36.
Please create another request for Tab38.
