### ISSUE TITLE
[Event Request] Codeunit 7307 - OnUpdateProdCompLineOnBeforeProdCompLine

### ISSUE THREAD

**Issue by makuhn** [microsoft/ALAppExtensions#3019]
Add new integration event **OnUpdateProdCompLineOnBeforeProdCompLine** in Codeunit 7307.

Function UpdateProdCompLine:
```
      ProdCompLine."Completely Picked" :=
        ProdCompLine."Qty. Picked" = ProdCompLine."Expected Quantity";
+     OnUpdateProdCompLineOnBeforeProdCompLine(ProdCompLine, QtyToHandleBase);
      ProdCompLine.MODIFY;
    END;
```
New publisher function:
```
    [Integration]
    LOCAL PROCEDURE OnUpdateProdCompLineOnBeforeProdCompLine@100000001(VAR ProdCompLine@100000000 : Record 5407;QtyToHandleBase@100000001 : Decimal);
    BEGIN
    END;
```

**Comment by AlexanderYakunin** [comment]
This event already exists OnBeforeProdCompLineModify(ProdCompLine,WhseActivityLine);
Variable QtyToHandleBase do not exist in this context.

**Comment by makuhn** [comment]
I cannot find this event in actual insider build. 

It is sufficient for us if parameter `QtyToHandleBase` is added to the existing event assuming the event is placed directly before `ProdCompLine.MODIFY` statement.
