### ISSUE TITLE
Service Order Stats. Page - Nothing Is Displayed

### ISSUE THREAD

**Issue by thebiggfudge** [microsoft/ALAppExtensions#3039]
If there is sales tax on a service transaction, and when you click on Statistics, the form is an empty box. After some investigation it is because the service stats. pages don't have ApplicationArea set. I am manually having to set the ApplicationArea on all the controls on the forms for anything to show.

**Comment by AlexanderYakunin** [comment]
Thank you, this is already fixed as hot fix.
