### ISSUE TITLE
[Event Request] Codeunit 5836 , 1 new Event in Function „CalcProdOrderLineExpCost“

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#3052]
We need new some "forgotten Events from the old Issue-Repo" in Codeunit 5836 to handle own ISV Code (https://github.com/Microsoft/AL/issues/3351)

1. Function CalcProdOrderLineExpCost
![image](https://user-images.githubusercontent.com/40287548/60414516-ada4a300-9bd8-11e9-9d5c-eaf79ba335fc.png)
The Event needs the following parameters:
![image](https://user-images.githubusercontent.com/40287548/60414528-b4331a80-9bd8-11e9-8e51-b4f46a590c4d.png)

2. Function CalcActTimeAndQtyBase
![image](https://user-images.githubusercontent.com/40287548/60414582-dc227e00-9bd8-11e9-9aed-6ee81ade469b.png)
The Event needs the following parameters:
![image](https://user-images.githubusercontent.com/40287548/60414594-e3e22280-9bd8-11e9-8979-78aa7dfbc6ba.png)

3. Function CalcActOperOutputAndScrap
![image](https://user-images.githubusercontent.com/40287548/60414610-f2c8d500-9bd8-11e9-9b2e-bf239e80ef9b.png)
The event needs the following parameters:
![image](https://user-images.githubusercontent.com/40287548/60414623-fe1c0080-9bd8-11e9-8851-6342b0b84af0.png)

Thanks

**Comment by AndreBreitenbach** [comment]
Request 1 is now available but Requests 2 and 3 for filtering are still missing in BC14.3! 
Could you please give us any Infos why?? 
Thanks

**Comment by AlexanderYakunin** [comment]
Last 2 events have been implemented at July 19, so probably they will be available in next update only.

**Comment by AndreBreitenbach** [comment]
Would it be possible to add some more info like "planned in release 14.3"?? This would help us partners very much!
