### ISSUE TITLE
C13 - New Event Request - Function UpdateAndDeleteLines

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#306]
In our localization we have setup to "Auto Increment Batch", and most of our customer prefer to do not increment batch name automatically. For purpose we need event before auto increment. 
 
new integration event:
LOCAL [IntegrationEvent] OnBeforeIncStrBatchName(VAR SkipAutoIncr : Boolean)

------------------
LOCAL **UpdateAndDeleteLines**(VAR GenJnlLine : Record "Gen. Journal Line")
OnBeforeUpdateAndDeleteLines(GenJnlLine,SuppressCommit);
....................................
  GenJnlLine3.RESET;
  GenJnlLine3.SETRANGE("Journal Template Name",GenJnlLine."Journal Template Name");
  GenJnlLine3.SETRANGE("Journal Batch Name",GenJnlLine."Journal Batch Name");
  **// new code 
  OnBeforeIncStrBatchName(SkipAutoIncr);**
  IF NOT GenJnlLine3.FINDLAST THEN 
  **// new code
    IF NOT SkipAutoIncr THEN**
    IF INCSTR(GenJnlLine."Journal Batch Name") <> '' THEN BEGIN
      GenJnlBatch.DELETE;
      IF GenJnlTemplate.Type = GenJnlTemplate.Type::Assets THEN
        FAJnlSetup.IncGenJnlBatchName(GenJnlBatch);
      GenJnlBatch.Name := INCSTR(GenJnlLine."Journal Batch Name");
      IF GenJnlBatch.INSERT THEN;
      GenJnlLine."Journal Batch Name" := GenJnlBatch.Name;
      OnAfterIncrementBatchName(GenJnlBatch,GenJnlLine2."Journal Batch Name");
    END;

**Comment by JesperSchulz** [comment]
A fix for this went in on the 23-11-2018. The fix diverts from the suggested one, but nonetheless, it should address the wanted behavior. Closing issue.
