### ISSUE TITLE
Download files from folder in BC-Oncloud Version ?

### ISSUE THREAD

**Issue by TharunMuthu** [microsoft/ALAppExtensions#3071]
Hi All,

Is it possible to read multiple files from that particular folder( from static IP address or using VPN ) in BC -OnCloud Version ? 

Thanks .

**Comment by GiorgosPa** [comment]
You can use HttpClient to achieve that. It will look like this
```
foreach urltofile from urls do begin
    HttpClient.Get(urltofile,HttpResponseMessage);
    HttpResponseMessage.Content.ReadAs(InStream);
    dosomething(InStream);
end;
```
