### ISSUE TITLE
[Even Request] Codeunit 6500 Item Tracking Managment - OnBeforeWhseItemTrackingLinkeInsert(WhseItemTRackingLine)

### ISSUE THREAD

**Issue by maksym-ch** [Microsoft/ALAppExtensions#308]
Hi, we need to implement additional business logic before inserting Whse. Item Tracking Line (CheckWhseItemTrkg function).
We have already publisher (insider build 25530): 
**LOCAL [IntegrationEvent] OnBeforeWhseItemTrackingLineInsert(VAR WhseItemTrackingLine : Record "Whse. Item Tracking Line")**
![todo 6500 checkwhseitemtrkg unresolved](https://user-images.githubusercontent.com/44081671/48250172-13ec7380-e406-11e8-9a7c-7350db859909.png)
Could you please extend the mentioned publisher in the following way:
**_LOCAL [IntegrationEvent] OnBeforeWhseItemTrackingLineInsert(ReservationEntry : Record "Reservation Entry";VAR WhseItemTrackingLine : Record "Whse. Item Tracking Line")_**

The new usage should be the following: 
**OnBeforeWhseItemTrackingLineInsert(SourceReservEntry, WhseItemTrackingLine);**

Thank you,

**Comment by AlexanderYakunin** [comment]
This event already implemented in BC

**Comment by NKarolak** [comment]
@AlexanderYakunin I think you have missed what the user wrote under the screenshot ;-) This is not a request for a new publisher, but to extend an existing one.
