### ISSUE TITLE
Expand Table 85 Acc. Schedule Line

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#3113]
Is it posible to expend the Table 85 for all of the 8 Dimensiones
- New Fields ("Dimension 5 Filter" ... "Dimension 8 Filter"
- New Fields ("Dimension 5 Totaling" ... "Dimension 8 Totaling"
- Expand Function "LookUpDimFilter" (5...8)
- Expand Function "GetCaptionClass" (5...8)

**Comment by AlexanderYakunin** [comment]
See #3119
