### ISSUE TITLE
Expand Table 95 G/L Budget Name

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#3118]
Is it posible to expend the Table 95 for all of the 8 Dimensiones

- New Fields ( "Budget Dimension 5 Code" ... " Budget Dimension 5 Code")
- Expand Trigger "OnModify" (5...8)
- Expand Function "UpdateGLBudgetEntryDim" (5..8)

**Comment by AlexanderYakunin** [comment]
See #3119
