### ISSUE TITLE
Expand Table 96 G/L Budget Entry

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#3119]
Is it posible to expand the Table 96 for all of the 8 Dimensiones

- New Fields (" Budget Dimension 5 Code" .. " Budget Dimension 8 Code"
- Expand Trigger "OnInsert" (UpdateDimSet(5...8))
- Expand Function "OnLookupDimCode"
  - DimOption as Enum and expand with Dimension 5-8
  - Expand Code with Dimension 5-8
- Expand Function "GetCaptionClass" (5...8)
- Expand Function "ShowDimensions" (5...8)

**Comment by AlexanderYakunin** [comment]
Currently we cannot extend number of dimensions in G/L Budget or Analysis View as it will require changes in primary keys. This is not allowed for cloud at this moment.  We will revert back to this ask if it when it will be possible in the future versions.
