### ISSUE TITLE
Expand Codeunit 8 AccSchedManagement

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#3120]
Is it posible to expand the Codeunit 8 for all of the 8 Dimensiones

- Expand Function "CheckAnalysisView"
- Expand Function "CalcGLAcc"
- Expand Function "CalcCFAccount"
- Expand Function "ConvDimTotalingFilter"
- Expand Function "HasDimFilter"
- Expand Function "DrillDownOnGLAccount"
- Expand Function "DrillDownOnCFAccount"

**Comment by AlexanderYakunin** [comment]
See #3119
