### ISSUE TITLE
Questeion - Max level of dependencies

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#3121]
Hi,
I heard the max level of dependencies is 4. Is that correct?
That would cause some problems so we need to know fast so we can plan on how to continue with developing extensions.

**Comment by atoader** [comment]
Hi! What do you mean by max level of dependencies? For a given project, only objects from the first level of dependencies can be referenced.

**Comment by LFlamme** [comment]
Hi, with level i mean if you think of the dependencies as tree.

a->b Level 1
a-> b->c Level 2
a-> b -> c-> d Level 3
a-> b -> c-> d->e Level 4

**Comment by atoader** [comment]
Hi! There is no such limit that I am aware off.
