### ISSUE TITLE
Expand Codeunit 762 Acc. Sched. Chart Management

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#3126]
Is it posible to expand the Codeunit 762 for all of the 8 Dimensiones

- Expand Function "DrillDownOnCFAccount" ("Dimension 5 Totaling" ... "Dimension 5 Totaling")
- Expand Function "DrillDownOnGLAccount" ("Dimension 5 Totaling" ... "Dimension 5 Totaling")

**Comment by AlexanderYakunin** [comment]
We cannot do it now due to needed change of primary keys
