### ISSUE TITLE
Expand Page 120 G/L Budget Entries

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#3131]
Is it posible to expand the Page 120 for all of the 8 Dimensiones

- New Fields ("Budget Dimension 5 Code" ... Budget Dimension 8 Code")
- Expand Trigger "OnInit" (5-8)
- Expand Trigger "OnOpenPage" (5-8)
- Expand Trigger "OnNewRecord" (5-8)

**Comment by AlexanderYakunin** [comment]
See #3119
