### ISSUE TITLE
Codeunit 11000006 CBG Statement Reconciliation - MatchCBGStatementLine (2) (Dutch Localization)

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3136]
We would like to perform some additional matching. To make this possible we require the following publisher in function MatchCBGStatementLine.

                IF EntriesCount = 1 THEN BEGIN
                  EmployeeLedgerEntry.GET(EntryNo);
                  CBGStatementlineRec."Applies-to Doc. Type" := EmployeeLedgerEntry."Document Type";
                  CBGStatementlineRec."Applies-to Doc. No." := EmployeeLedgerEntry."Document No.";
                  CBGStatementlineRec."Reconciliation Status" := CBGStatementlineRec."Reconciliation Status"::Applied;
                  NumberOfLinesApplied := NumberOfLinesApplied + 1;
                  IF RecChanged THEN
                    NumberOfLinesChanged := NumberOfLinesChanged - 1;
                  RecChanged := TRUE;
                END;
              END;
            END;
         END;
      END;

      ///// START
      OnAfterMatchCBGStatementLine(CBGStatementlineRec, NumberOfLinesChanged, RecChanged, EntriesCount, EntryNo);
      ///// END

      IF RecChanged THEN
        CBGStatementlineRec.MODIFY(TRUE);
    END;

The signature of the publisher:

    [Integration]
    LOCAL PROCEDURE OnBeforeFindNAC@11095590(VAR CBGStatementLine@11095587 : Record 11401;VAR NumberOfLinesChanged@11095586 : Integer;VAR RecChanged@11095585 : Boolean);
    BEGIN
    END;

Many thanks.

**Comment by rvanbekkum** [comment]
We need the same event publisher, but would like some additional parameters. For that we would a signature like below with at least those parameters so that we can customize the matching/filtering:
```
LOCAL [IntegrationEvent] 
OnAfterMatchCBGStatementLine
(
  CBGStatement : Record "CBG Statement";
  VAR CBGStatementline : Record "CBG Statement Line"; 
  TransactionModeFilter : Text; 
  EntriesCount : Integer; 
  RecChanged : Boolean;
  VAR NumberOfLinesApplied : Integer; 
  VAR NumberOfLinesChanged : Integer
)
```

Which would be called as follows:
```pascal
OnAfterMatchCBGStatementLine(CBGStatementRec,CBGStatementlineRec,strFilter,
                                  EntriesCount,RecChanged,NumberOfLinesApplied,NumberOfLinesChanged);
```

**Comment by lv-janpieter** [comment]
This publisher has been incorrectly implemented. Some VAR indicators are missing. I will raise a new issue.

**Comment by AlexanderYakunin** [comment]
Please do not add requirements in comments, these are not tracked by us. Close wrong request and create new one instead.
