### ISSUE TITLE
Expose function T 77 -  SendEmailToVendorDirectly

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#3142]
Hi,

Can you please expose function SendEmailToVendorDirectly and SendEmailToCustomerDirectly in table 77 - Report Selections?
With it, we can avoid any unwanted dialog and confirmations which usually appears when we send emails through report selections.

Thanks!

**Comment by RomanZanizdra** [comment]
Hi radovandokic. We don't have a plan to make these functions external at this moment.
Why can't you use SendEmailToCust or similar one for vendor? There is a possibility to manage dialog via parameter, plus there is an event for more flexibility.

**Comment by RomanZanizdra** [comment]
I close current issue for now. You can re-open it later if you think something else can be done here.
