### ISSUE TITLE
[Event Request] Page 5806 Purch. Receipt Lines - OnAfterInitialize

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#3144]
Page 5806 is used for the Purchase Item Charge Assignment functionality, which we want to extend.

we would like to have this function exposed as an Event
```
[External] Initialize(NewItemChargeAssgntPurch : Record "Item Charge Assignment (Purch)";NewUnitCost : Decimal)
ItemChargeAssgntPurch := NewItemChargeAssgntPurch;
UnitCost := NewUnitCost;
```

We would like to be able to manipulate the data presentation according to the "Item Charge Assignment (Purch)" from which it is called.

**Comment by StanPesotskiy** [comment]
Do you think that 
OnAfterInitialize(var NewItemChargeAssgntPurch ,var UnitCost ) in the end of Initialize()
will help you?

**Comment by JulianTillmann** [comment]
If the NewItemChargeAssgntPurch-Rec has all the Information where the item charge assignment was started then it should be fine for my Case Right now. 

Also Page 5805 "Item Charge Assignment (Purch)" could use some Integration Events as well. should I open another EventRequest here on GitHub or could you Maybe design the whole Item charge functionality (puchase & Sales) with Integration Events? I'm sure there will be cases with the upcoming Fall release where us and other Partners Need to Change the behaviour extensively.

**Comment by StanPesotskiy** [comment]
I can add OnAfterInitialize event to rep5805 in scope of this request, but all other events should be requested separately in all details (where to put, what parameters).
