### ISSUE TITLE
Codeunit 80 + 90 - OnBeforePostLines weirdness #547

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#3149]
I can't find this solution in version 14.0.29530. Will it be fixed in the next version?

**Comment by StanPesotskiy** [comment]
OnBeforePostLines() are pretty old events. They existed already in build 26767 and exist now.
![image](https://user-images.githubusercontent.com/41332028/60704303-b4028a00-9f0c-11e9-9112-1669b21fc7bd.png)
![image](https://user-images.githubusercontent.com/41332028/60704323-c8468700-9f0c-11e9-8758-e78a7d768013.png)

**Comment by TxusMoyano** [comment]
The question is not the event exists. The issue #547 is about  the TEMP PURCHLINE GLOBAL variable is not passed as TEMPORARY in the Integration Event definition of these events. 

Thank you.

**Comment by TxusMoyano** [comment]
Or TempSalesLineGlobal

**Comment by StanPesotskiy** [comment]
I see now. Though, what is weird in not declaring the parameter as TEMPORARY? It is allowed to pass either temporary or normal record variable to such parameter. Is there a scenario broken by such a declaration?

**Comment by TxusMoyano** [comment]
Sorry, it was a testing mistake
