### ISSUE TITLE
The type or method ... cannot be used for 'Extension' development.

### ISSUE THREAD

**Issue by HegedusZsolt** [Microsoft/ALAppExtensions#315]
We need below methods to be opened for our app. Please check.

Codeunit 1297: 
- GetResponseStream
- Initialize
- SetTimeout
- SetMethod
- SetContentType
- SetReturnType
- AddHeader
- AddBodyAsText
- AddBodyBlob
- ProcessFaultXMLResponse

Codeunit 9750:
- CreateWebService

**Comment by IhorHandziuk** [comment]
Thank you for your request. 
Procedure CreateWebService in codeunit 9750 will be external in the next release. 
Regarding procedures in codeunit 1297, please, take a look at our AL type [HttpRequestMessage](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httprequestmessage/httprequestmessage-data-type) instead, as we want people to use our native types in extension development if possible.

**Comment by HegedusZsolt** [comment]
Thank you for your fast response, but we can't use HTTP AL type, because there is only basic authentication, but we need NTLM. That's why we would like to use codeunit 1297 instead.

Is it possible to make it extension available or extend HTTP AL type with credentials?
