### ISSUE TITLE
Extensibility Issue: Codeunit 12 InitVAT

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#3151]
In Codeunit 12 there is method `InitVAT` that looks like the code block below. I have a problem with the marked line - it is blocking us from implementing local fiscal regulations. See blow.

![image](https://user-images.githubusercontent.com/8897936/60663868-b5767880-9e60-11e9-962e-23314aa0291c.png)

I would suggest that you do not execute this check if the field `System-Created Entry` is `true`. We need to make certain system postings that do cause this check to trigger, but the posting is correct as it is, according to local fiscal regulations.

Another way would be to implement an event with the handled pattern, if that suits you better. I am OK with that. Either way: we need to be able to control this.

FYI, @Addice73 ... 

Thanks

**Comment by StanPesotskiy** [comment]
Try to use the event OnBeforeInitVAT(), exists from Build 24318:
![image](https://user-images.githubusercontent.com/41332028/60704597-9681f000-9f0d-11e9-8f8b-0a8b74bd13c2.png)
![image](https://user-images.githubusercontent.com/41332028/60704517-5ae72600-9f0d-11e9-946f-549cfcc5d959.png)

**Comment by hemisphera** [comment]
That should work, thank you. Sorry, I've looked up the wrong DB and therefore didn't see that there was an event already. Thanks!
