### ISSUE TITLE
Extensibility NL local report 11405 'Submit Elec. Tax Declaration'

### ISSUE THREAD

**Issue by Jeeve65** [microsoft/ALAppExtensions#3152]
Report 11405 opens a Request Page where the user needs to upload two certificates, and enter the password for one of these certificates.

We need an event that (1) enables us to provide these three things (2 certificates, 1 password), and (2) if these are provided, suppresses  the opening of the Request Page.

Security is very important here; it is imperative that the data that is entered through the event is not available to other apps that should subscribe to the same event; so the 'usual' way to have a Handled parameter and some VAR parameters may not be secure enough.

**Comment by Jeeve65** [comment]
For the security bit: possible solution (only on SaaS)
Create a single-instance codeunit; have an [External]  function that allows Apps to set the 2 certificates and the password, but have the functions to read the certificate be [Internal] so that other Apps cannot use that.

**Comment by StanPesotskiy** [comment]
For the new features please submit a product suggestion on https://aka.ms/bcideas
