### ISSUE TITLE
[Replace Option with Enum] NL local table 11409 'Elec. Tax Declaration Header', field 41 'Declaration Period' 

### ISSUE THREAD

**Issue by Jeeve65** [microsoft/ALAppExtensions#3153]
The list of possible periods for the VAT declaration is not complete. (quarterly declaration, starting in the 2nd or 3rd month of a 'standard' quarter is not possible now)

We expect that this will be fixed by Microsoft, but until that time, making the mentioned field extensible will suffice.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
