### ISSUE TITLE
Add decimal places information to page metadata

### ISSUE THREAD

**Issue by HegedusZsolt** [Microsoft/ALAppExtensions#316]
We like to use decimal places metadata in our solution.

Please add a new field "Decimal Places" to virtual table 2000000192 (Page Control Field)

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
