### ISSUE TITLE
Problem: function "MergeWordLayout" in codeunit 9651 "Document Report Mgt." -> Usage of parameter "PrinterName" on event "OnBeforeMergeDocument"

### ISSUE THREAD

**Issue by pro4dynamix** [microsoft/ALAppExtensions#3163]
Hello,

we are using the "OnBeforeMergeDocument" event in funktion "MergeWordLayout" (Codunit 9651 "Document Report Mgt.") in order to provide a alternate ISV solution for printing/exporting reports.

The standard call, which is allready implemented is:
**OnBeforeMergeDocument(ReportID,ReportAction,InStrXmlData,_PrinterName_,OutStrWordDoc,Handled,FileName = '');**

But we need the parameter "FileName" instead of "PrinterName":
**OnBeforeMergeDocument(ReportID,ReportAction,InStrXmlData,_FileName_,OutStrWordDoc,Handled,FileName = '');**

Maybe this is a bug or a unfortunate implementing in the current solution. 

If we do not get the "FileName" as parameter in the event call, we do not have a chance to implement a different version of for example "SAVEASPDF" in the "OnBeforeMergeDocument". Because "PrinterName" is only filled, if the ReportAction is "Print". We can not access the "FileName", which is nessesary in this case.

I think, this would be a great benefit, even for everyone, who wants to use this "OnBeforeMergeDocument" event and it would not crash current implementions, because the "FileName" even holds the printername, if the ReportAction is "Print".

Best regrads
Jürgen Markgraf

**Comment by StanPesotskiy** [comment]
Right, PrinterName parameter gets a value only if report action is printing.
The internal FileName value will not be exposed due to security reasons, the only thing we provide is a flag IsFileNameBlank. It was added as an answer to [GitHub 3125]( https://github.com/Microsoft/AL/issues/3125)
