### ISSUE TITLE
Create Dot Net Control Addin (.CS extension )  from AL ?

### ISSUE THREAD

**Issue by TharunMuthu** [microsoft/ALAppExtensions#3169]
Hi All,

Is it there any link or reference like how to call .CS file from AL ?  
![2019-07-07_11-02-09](https://user-images.githubusercontent.com/44170162/60763435-fe1f7300-a0a6-11e9-9c62-76c2933668e9.jpg)

Thanks

**Comment by atoader** [comment]
HI! It is not possible. A .NET Add-In must be created as a separate assembly that is referenced from AL as described here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-dotnet-controladdins .

To get more help for your question please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
