### ISSUE TITLE
[Event Request] Table 296 Reminder Line: OnAfterSetCustLedgEntryView

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#3198]
Hi,

and another event request for the Reminders :) 
Thanks in advance! 

**Function**: SetCustLedgEntryView
**Publisher**: OnAfterSetCustLedgEntryView
![grafik](https://user-images.githubusercontent.com/40355993/60813857-da3a5b00-a194-11e9-9764-03cac77bace0.png)

**Properties:**
![grafik](https://user-images.githubusercontent.com/40355993/60813872-e0303c00-a194-11e9-846e-c3a15ec889e3.png)

**Parameters:**
![grafik](https://user-images.githubusercontent.com/40355993/60813893-e9210d80-a194-11e9-97f6-437d1ce337a9.png)

**Comment by StanPesotskiy** [comment]
Are all parameters should be passed by value?

**Comment by GeekEding** [comment]
Sorry - wrong Screenshot; should be look like this:

![grafik](https://user-images.githubusercontent.com/40355993/61430281-cecff800-a929-11e9-805a-1a27d245e440.png)
