### ISSUE TITLE
[Event Request] Table 2000005 Export Protocol - OnBeforeExportPaymentLines

### ISSUE THREAD

**Issue by OSHK** [Microsoft/ALAppExtensions#32]
We need the following publisher to override the ExportPaymentLines function with custom functionality:
_Table 2000005 Export Protocol - Function ExportPaymentLines:_
[**IsHandled := FALSE;**
**OnBeforeExportPaymentLines(Rec,PmtJnlLine,IsHandled)** (_event at the beginning of the function_)
**IF IsHandled THEN
    EXIT;**](url)
Thank you in advance!

**Comment by AlexanderYakunin** [comment]
Why do you ask for BE specific functionality?

**Comment by OSHK** [comment]
Currently, we have C\AL add-on that is created for the BE market and based on the BE localization of MS Dynamics Nav. 
We would like to move all C\AL customization to AL extensions and create a separate application, that will be available for our BE customers. 
According to our business logic, we need to adjust existing ExportPaymentLines function, and we need the requested event to do that.

Is it possible to add such event for BE specific functionality?
