### ISSUE TITLE
[Function Expose] Codeunit 1631 - Office Host Management - InvokeExtension

### ISSUE THREAD

**Issue by robjones85** [microsoft/ALAppExtensions#3213]
Looking at the "InvokeFunction" function in OnPrem CAL, it seems to already be marked as External. However when attempting to reference the function in an AL extension targeting the Cloud, it returns the error "The type or method 'InvokeExtension' cannot be used for 'Extension' development."

**Comment by RomanZanizdra** [comment]
Hi. We don't have plans to make function InvokeExtension available externally for AL development.

**Comment by RomanZanizdra** [comment]
I close current issue. You can re-open it later if you think something else can be done here.
