### ISSUE TITLE
DK: OIOUBL currencyID blank in xml file 

### ISSUE THREAD

**Issue by AnitaZinck** [microsoft/ALAppExtensions#3232]
Export of posted Sales Invoice to OIOUBL file still have som "blanks CurrencyID fields in the file 

PaymentTerms
<cbc:Amount currencyID="">12402.53</cbc:Amount>

Sales Line Example
  <cbc:LineExtensionAmount currencyID="">1854.00</cbc:LineExtensionAmount>

TaxTotal (document) Tax on lines are OK
<cbc:TaxableAmount currencyID="">9922.02</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="">2480.51</cbc:TaxAmount>

BusinessCentral (cloud) fault - on prem is OK

**Comment by StanPesotskiy** [comment]
This issue seems to be a bug not related to extensibility. 
Please use the standard support channel to report it.
