### ISSUE TITLE
New Key for Table 32 "Item Ledger Entry"

### ISSUE THREAD

**Issue by CKL-CAalstede** [microsoft/ALAppExtensions#3233]
Dear Microsoft,

We would like to add the following Key to Table 32 "Item Ledger Entry". In our ISV process only the Postivie Entries are of relevance so being able to sort all Negative Entries out will bring huge Performance issues.
The key should be as follows:
 Item No.,Positive,Entry Type,Variant Code,Location Code,Posting Date;

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
