### ISSUE TITLE
New Key Table 5802 "Value Entry"

### ISSUE THREAD

**Issue by CKL-CAalstede** [microsoft/ALAppExtensions#3234]
Dear Microsoft,

We would like to add the following Keys to Table 5802 "Value Entry". Our ISV bases the revaluation of Item Inventory Values on certain criterias. In order to sum all relevant Fields without having Performance Issues the following keys are necessary.

Item Ledger Entry No.,Entry Type,Posting Date;
   SumIndexFields=Invoiced Quantity,Cost Amount (Actual);

Item No.,Valuation Date,Location Code,Variant Code,Item Ledger Entry Type;
   SumIndexFields=Cost Amount (Expected),Cost Amount (Actual),Cost Amount (Expected)(ACY),Cost Amount (Actual) (ACY),Item Ledger Entry Quantity;

Item No.,Entry Type,Cost per Unit,Item Ledger Entry Type,Posting Date;
                                                   MaintainSQLIndex=No
 
Item No.,Entry Type,Location Code,Variant Code,Cost per Unit,Item Ledger Entry Type,Posting Date;

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
