### ISSUE TITLE
[Error Change] Codeunit 12 Gen. Jnl.-Post Line: CalcPmtDiscIfAdjVAT

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#3236]
Hi,

we would like to ask for a code change in Codeunit 12. We had several customer who got this error while posting a general journal with a lot of lines. 
![grafik](https://user-images.githubusercontent.com/40355993/60944357-de778d00-a2e8-11e9-97e9-540fb4d477f4.png)

This error is created here: 
![grafik](https://user-images.githubusercontent.com/40355993/60942672-be919a80-a2e3-11e9-825e-7391a2b1bf3e.png)

This is a problem if there are a lot of lines in the journal and you didn't know, which line makes this problem. 
If you do a small code change with an seperate error message like this: Everything would be fine!

![grafik](https://user-images.githubusercontent.com/40355993/60942727-f7317400-a2e3-11e9-989a-15c5d9b695d8.png)

This is our text for the TextConst "**VatPostingSetupNotFoundError**": 
%1 does not exist in \Gen. Jnl. Batch: '%2' \LineNo.: '%3' \Account No.: '%4'. \%5: '%6', \%7: '%8'.

Then the error looks like this: 
![grafik](https://user-images.githubusercontent.com/40355993/60944407-023ad300-a2e9-11e9-8241-8c51caa2acdd.png)

Thanks!

**Comment by AlexanderYakunin** [comment]
Thank you for your suggestion! We accept and complete such suggestions from aka.ms/bcideas portal, using votes. Please publish your suggestion there.
