### ISSUE TITLE
Codeunit 7000000 CarteraManagement - Procedure VendUnrealizedVAT (Local to Global)

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#3240]
We need to have the Procedure "VendUnrealizedVAT" to be Global instead Local

**Comment by RomanZanizdra** [comment]
Hi. Is something wrong with VendUnrealizedVAT2 function which is external?

**Comment by RomanZanizdra** [comment]
I close current issue for now. You can re-open it later if you think something else can be done here.
