### ISSUE TITLE
[Module] Date-Time Dialog - Getter/Setter functions

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#3253]
On https://github.com/microsoft/ALAppExtensions/blob/master/Modules/System/Date-Time%20Dialog/src/DateTimeDialog.Page.al, can we have functions to dynamically:

- Change the PageCaption (E.g. 'Input Start Date')
- Change the Field Captions (E.g. 'Start Date', 'Start Time')
- Change the Visibility property (E.g. hide the 'Time' field since we only need to enter a date)
- Change the ShowMandatory property (E.g. 'Start Date' must be filled before closing the page)

**Comment by RomanZanizdra** [comment]
Hi fvet.
I think the change you are asking for has no sense. I think you can have your own page for your own particular purposes. 
I'll close current issue for now. Feel free to re-open it if you still think something else can be done here.
