### ISSUE TITLE
[Event Request] Report 7000080 Post Payment Order - OnAfterGetAccountNo

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#3256]
We need a new event in report 7000080 "Post Payment Order":

**LOCAL [IntegrationEvent] OnAfterGetAccountNo(VAR CarteraDoc : Record "Cartera Doc.";VAR AccountNo : Code[20];VAR BalanceAccount : Code[20])**

Called from:

_**Cartera Doc. - OnPreDataItem()**_
...
...
IF "Document Type" = "Document Type"::Bill THEN BEGIN
  VendPostingGr.TESTFIELD("Bills in Payment Order Acc.");
  VendPostingGr.TESTFIELD("Bills Account");
  AccountNo := VendPostingGr."Bills in Payment Order Acc.";
  BalanceAccount := VendPostingGr."Bills Account";
END ELSE BEGIN
  VendPostingGr.TESTFIELD("Invoices in  Pmt. Ord. Acc.");
  VendPostingGr.TESTFIELD("Payables Account");
  AccountNo := VendPostingGr."Invoices in  Pmt. Ord. Acc.";
  BalanceAccount := VendPostingGr."Payables Account";
END;
**//Init insert ---------------------
OnAfterGetAccountNo("Cartera Doc.",AccountNo,BalanceAccount);
//End insert ---------------------**
IF BGPOPostBuffer.GET(AccountNo,BalanceAccount,VendLedgEntry."Entry No.") THEN BEGIN
  BGPOPostBuffer.Amount := BGPOPostBuffer.Amount + "Remaining Amount";
...
...

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
