### ISSUE TITLE
Table 77 Report Selections - GetEmailBodyInPdf

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3274]
We would like to requist the following additional publisher in function GetEmailBodyInPdf:

    [Internal]
    PROCEDURE GetPdfReport@52(VAR ServerEmailBodyFilePath@1001 : Text[250];ReportUsage@1002 : Integer;RecordVariant@1004 : Variant;CustNo@1003 : Code[20]);
    VAR
      TempBodyReportSelections@1000 : TEMPORARY Record 77;
    BEGIN
      ///// START
      OnBeforeGetPdfReport(ServerEmailBodyFilePath, ReportUsage, RecordVariant, CustNo, IsHandled);
      IF IsHandled THEN
        EXIT;
      ///// END

      ServerEmailBodyFilePath := '';

      FindPrintUsage(ReportUsage,CustNo,TempBodyReportSelections);

      ServerEmailBodyFilePath :=
        SaveReportAsPDF(TempBodyReportSelections."Report ID",RecordVariant,TempBodyReportSelections."Custom Report Layout Code");
    END;

The signature of the publisher:

    [Integration]
    LOCAL PROCEDURE OnBeforeGetPdfReport@11095588(VAR ServerEmailBodyFilePath@11095589 : Text[250];ReportUsage@11095588 : Integer;RecordVariant@11095587 : Variant;CustNo@11095586 : Code[20];VAR IsHandled@11095590 : Boolean);
    BEGIN
    END;

Many thanks.

**Comment by StanPesotskiy** [comment]
function GetEmailBodyInPdf is internal and is not called from BaseApp now. It will be removed.
How did you plan to use it?

**Comment by lv-janpieter** [comment]
Thanks for pointing out this error! It seems like we made a mistake with the upgrade (2017 > 2019).
Our requirement is that we always filter the report selections on an additional field from the sourcedocument. That requires a lot of places to integrate because the recordvariant usually is only parsed to the first function, but is not taken down to to for instance the FilterPrintUsage function. Integration would be more easy if the recordvariant was parsed all the way down the call stack and also parsed to the integration trigger.

The code above is wrong, this should have been the 'GetPdfReport' function. I will modify the request.

**Comment by lv-janpieter** [comment]
> Thanks for pointing out this error! It seems like we made a mistake with the upgrade (2017 > 2019).
> Our requirement is that we always filter the report selections on an additional field from the sourcedocument. That requires a lot of places to integrate because the recordvariant usually is only parsed to the first function, but is not taken down to to for instance the FilterPrintUsage function. Integration would be more easy if the recordvariant was parsed all the way down the call stack and also parsed to the integration triggers in these functions.
> 
> The code above is wrong, this should have been the 'GetPdfReport' function. I will modify the request.
