### ISSUE TITLE
Table 77 Report Selections - GetCustomReportSelection

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3275]
We would like to requist the following additional publisher in function GetCustomReportSelection:

    LOCAL PROCEDURE GetCustomReportSelection@23(VAR CustomReportSelection@1000 : Record 9657;AccountNo@1001 : Code[20];TableNo@1002 : Integer) : Boolean;
    BEGIN
      CustomReportSelection.SETRANGE("Source Type",TableNo);
      CustomReportSelection.SETRANGE("Source No.",AccountNo);
      IF CustomReportSelection.ISEMPTY THEN
        EXIT(FALSE);

      CustomReportSelection.SETFILTER("Use for Email Attachment",GETFILTER("Use for Email Attachment"));
      CustomReportSelection.SETFILTER("Use for Email Body",GETFILTER("Use for Email Body"));

      ///// START
      OnAfterGetCustomReportSelection(CustomReportSelection, AccountNo, TableNo);
      ///// END
    END;

The signature of the publisher:

    [Integration]
    LOCAL PROCEDURE OnAfterGetCustomReportSelection@11095593(VAR CustomReportSelection@11095587 : Record 9657;AccountNo@11095586 : Code[20];TableNo@11095585 : Integer);
    BEGIN
    END;

Many thanks.

**Comment by TimothyWatkins** [comment]
On this note - I was wondering whether it would be worth while exposing the SelectTempReportSelectionsToPrint(TempReportSelections,TempNameValueBuffer,WithCheck,ReportUsage,TableNo); function (Table 77) as an integrationevent - then we would have the ability to overwrite any standard report selections made by the system. We would like the ability to print specific reports on a document level and not just a customer or usage level.

**Comment by lv-janpieter** [comment]
> On this note - I was wondering whether it would be worth while exposing the SelectTempReportSelectionsToPrint(TempReportSelections,TempNameValueBuffer,WithCheck,ReportUsage,TableNo); function (Table 77) as an integrationevent - then we would have the ability to overwrite any standard report selections made by the system. We would like the ability to print specific reports on a document level and not just a customer or usage level.

We don't have this requirement, however if you need this, just create a new issue and they will probably follow up on your request.
