### ISSUE TITLE
Bug with pageparts in a group (in the Webclient)

### ISSUE THREAD

**Issue by VladyslavKharkovchuk** [microsoft/ALAppExtensions#3285]
**Describe**:
When view and edit modes are changed on the pages with pageparts in a group, the error "Sorry, something went wrong. Refresh the page and try again." appears.

**Specific conditions to reproduce**:
•  The page contains a group, which contains a subpage.
•  The subpage has editable fields.
•  When page opens, the group with the subpage should be collapsed.

![Screen1](https://user-images.githubusercontent.com/52788054/61061277-9baad780-a404-11e9-866f-a33c586777a1.jpg)
![Screen2](https://user-images.githubusercontent.com/52788054/61061282-9e0d3180-a404-11e9-8602-57fb0d1516ad.jpg)

If the group is expanded before changing of the mode to/from View/Edit, does not show the same error and works fine.

**Business Central Versions**:
14.1: the error "Sorry, something went wrong. Refresh the page and try again." appears.
14.0: nothing happens with dialog window "Working on it ..."
13.0: everything works perfectly.

**Comment by StanPesotskiy** [comment]
Please report this issue via the standard support channel.
