### ISSUE TITLE
Codeunit 426 'Payment Tolerance Management' - remove COMMIT

### ISSUE THREAD

**Issue by rgrygoryshchak** [microsoft/ALAppExtensions#3286]
Hi,

**Report 1201 (Post Direct Debit Collection)**

**LOCAL CreateJnlLine(VAR DirectDebitCollectionEntry : Record "Direct Debit Collection Entry") : Boolean**
```
...
    GenJnlLine.VALIDATE("Applies-to Doc. No.",CustLedgEntry."Document No.");
...

```

This line would cause COMMIT in codeunit 426 'Payment Tolerance Management':

**Table 81 'Gen. Journal Line'**

**Applies-to Doc. No. - OnValidate()**

```
...
IF ("Applies-to Doc. No." <> xRec."Applies-to Doc. No.") AND (Amount <> 0) THEN BEGIN
  IF xRec."Applies-to Doc. No." <> '' THEN

    /// Has COMMIT too
    PaymentToleranceMgt.DelPmtTolApllnDocNo(Rec,xRec."Applies-to Doc. No.");

  SetApplyToAmount;

  /// Has COMMIT
  PaymentToleranceMgt.PmtTolGenJnl(Rec);

  xRec.ClearAppliedGenJnlLine;
END;
...
```

Regards, Roman.

**Comment by StanPesotskiy** [comment]
@rgrygoryshchak
I am afraid we cannot simply remove commit calls. 
Could you share what scenarios are broken by these calls?

**Comment by rgrygoryshchak** [comment]
I know you cannot just remove COMMIT's, but you could redesign code ;-)

I have tried to explain scenario in original post . 

Next line from report 1201 (Post Direct Debit Collection) would cause unwanted COMMIT:

GenJnlLine.VALIDATE("Applies-to Doc. No.",CustLedgEntry."Document No.");

This is BUG!

Regards, Roman.

**Comment by StanPesotskiy** [comment]
In order to redesign we need to take into account all old scenarios that had led to these appearance of these commits and a new scenario you found that is broken by them. 
You have to provide a real business case that is broken because of these commits. Otherwise it is not accepted as a bug, but is by design.

**Comment by rgrygoryshchak** [comment]
Sorry, are you saying that it is by design to have COMMIT in the middle of report 1201? 

In that case it would be beneficial for all to have explicit COMMIT in this report.

Roman.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
