### ISSUE TITLE
Sales Price / Sales Line Discount / Purchase Price / Purchase Price Discount

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3287]
Dear ALAppExtensions team.

I would like to adress an issue about a design choice that makes it very hard to make handling pricing and discounts extensible. I think a lot of engineers are strugling with the way the Price and Discount tables are set up. 

I'm referring to tables:
- 1304 Sales Price and Line Disc Buff
- 1315 Purch. Price Line Disc. Buff.
- 7002 Sales Price
- 7004 Sales Line Discount
- 7012 Purchase Price
- 7014 Purchase Line Discount

The problem is that setting up prices and discounts are very restricted because all the selection criteria fields have been put into the primary key. There are many variations where our customers have more selection criteria for prices and discounts. And there we hit a dead end because if we want to allow setting up prices and discounts with more criteria we have to extend the tables primary key.

Since extending primary keys is not possible in extensions, and probably very hard to introduce in future updates, would it be possible to consider changing the Primary Key of these tables to just an "Entry No." field? And make all other keys secondary? If we have this it will allow us to extend this functionality to our own requirement.

The only other solution is that we completely replace these tables.

I know this is not an easy thing, requires quite some refactoring and conversion of data. However hope you will consider this.

Many thanks.

**Comment by pschwambornMC** [comment]
What is the status of this issue?
We also need this kind of enhancement.

**Comment by lv-janpieter** [comment]
@pschwambornMC 
Thanks for bringing this issue to the attention again. In my experience Microsoft is not reading replies of topics already labelled. Would you mind creating a new issue with your question referencing this issue #3287 and issue #3469? Maybe they will scale up priority if more people are asking. Many thanks.

**Comment by StanPesotskiy** [comment]
With the April'2020 release we have shipped the new mechanism of price calculation that is trying to make pricing extensible. 
Join the conversation on Yammer https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=568981905506304
