### ISSUE TITLE
Codeunit 370 Bank Acc. Reconciliation Post - CloseBankAccLedgEntry - OnBeforeCloseBankAccLedgEntry

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#3294]
Dear Development Team,

We would like to request a publisher in Codeunit 370 Bank Acc. Reconciliation Post in the CloseBankAccLedgEntry function right before modifying the Bank Account Ledger Entry.
In this Publisher, we would like to have access to both "Bank Account Ledger Entry" and "Bank Account Recon. Line" tables.

![image](https://user-images.githubusercontent.com/39408604/61113854-08ff4c80-a487-11e9-9b57-8e04144ca953.png)

Much appreciated.

Cheers,
Marton Nagy

**Comment by StanPesotskiy** [comment]
The best way to request a new event is to implement it locally, verify how it works for you and then send to us the code snippets. It does not guarantee we will simply copy&paste but it helps understand what you really need. 
I assume you need to pass BankAccLedgEntry by reference and BankAccReconLine by value?

**Comment by martonnagy** [comment]
Hi Stan,

OK, will do next time.

Yes, please.

Cheers,
Marton
