### ISSUE TITLE
OnBeforePostInvPostBuffer Event Signatures in Codeunit 80 and 90

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#3296]
Dear Development Team,

can you "syncronize" the Event Signatures of the OnBeforePostInvPostBuffer Events in the two Posting Codeunits?

As you can see below
- The parameters are in a different order.
- SalesHeader is not a var, whereas PurchHeader is.
- CommitIsSuppressed in spelt with a single P in Suppressed in Codeunit 90. 

![image](https://user-images.githubusercontent.com/39408604/61122920-f42cb400-a49a-11e9-9f2f-d051b854b5e0.png)

Figure 1-Codeunit 80 (Sales-Post) 

![image](https://user-images.githubusercontent.com/39408604/61122952-03136680-a49b-11e9-9c2e-f509375cd358.png)

Figure 2-Codeunit 90 (Purch.-Post) 

Cheers,
Marton

**Comment by StanPesotskiy** [comment]
Unfortunately we are limited in renaming and moving parameters after the event is released to not break solutions built on it.
Though we can add VAR for SalesHeader parameter.

**Comment by martonnagy** [comment]
Hi Stan,

makes sense...adding the VAR would be useful!

Cheers,
Marton
