### ISSUE TITLE
[Refactoring] Codeunit 13 Gen. Jnl.-Post Batch: ProcessBalanceOfLines

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#3300]
Hi,

can you add this condition to the function ProcessBalanceOfLines?
![grafik](https://user-images.githubusercontent.com/40355993/61128817-41b51b00-a4b3-11e9-8a9c-33ae3ffffbef.png)

Thanks!

**Comment by StanPesotskiy** [comment]
Can you give a bit more information about a scenario that requires such a change?

**Comment by GeekEding** [comment]
Hi,
for sure! 

We have a module for G/L Open Entries. 

In this case we can use partial applications with different currencies. 
If there is a rounding residual we get the scenario with Amount = 0 and Amount (LCY) <> 0. 

This is only a system created posting; you can't do it manually in the system.

**Comment by RomanZanizdra** [comment]
Hi. Let's do in the following way. The condition Amount <> 0 will be replaced with the IsNonZeroAmount function. This function will contain event publisher. You can subscribe on it and change the result in dependency on your particular amount
    local procedure IsNonZeroAmount(GenJournalLine: Record "Gen. Journal Line") Result: Boolean
    begin
        Result := GenJournalLine.Amount <> 0;
        OnAfterIsNonZeroAmount(GenJournalLine, Result);
    end;

**Comment by GeekEding** [comment]
Hi,
that sounds good; thank you!
