### ISSUE TITLE
[Event Request] Table T5896 "Inventory Adjmt. Entry (Order)" - "CalcOvhdCost"

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#3302]
Hello together,

Please add an Event to T5896 "Inventory Adjmt. Entry (Order)" ant the end of the function "CalcOvhdCost".

```
...
"Single-Lvl Mfg. Ovhd Cost(ACY)" := ROUND("Single-Lvl Mfg. Ovhd Cost(ACY)",AmtRndgPrecACY);

// MML00002100 +++
OnAfterCalcOvhdCost(xRec, Rec, GLSetup, OutputQty, AmtRndgPrec, AmtRndgPrecACY, CalcCurrencyFactor)
// MML00002100 ---
```

Thanks in advance,
Benjamin

**Comment by StanPesotskiy** [comment]
What parameters should be passed by reference?

**Comment by BenjaminHochstetter** [comment]
Hello Stan,

`Rec` must be passed by reference
`xRec` and `GLSetup` can be passed by reference for better performance.

Thanks in advance,
Benjamin
