### ISSUE TITLE
[Event Request] CU5812 "Calculate Standard Cost" - OnBeforeCalLotSizeCalcMfgItem

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#3304]
Hello togehter,

Please add an event `CU5812 "Calculate Standard Cost" `in to function` "CalcMfgItem"`

```
    END ELSE BEGIN
      SLMat := "Unit Cost";
      RUMat := "Unit Cost";
    END;

  // MML00002100 +++
  OnBeforeCalLotSizeCalcMfgItem(SLMat, SLCap, SLSub, SLCapOvhd, SLMfgOvhd, Item, LotSize, MfgItemQtyBase, Level, CalculationDate);
  // MML00002100 ---

  "Single-Level Material Cost" := CalcCostPerUnit(SLMat,LotSize);
  "Single-Level Capacity Cost" := CalcCostPerUnit(SLCap,LotSize);
  "Single-Level Subcontrd. Cost" := CalcCostPerUnit(SLSub,LotSize);
```

Event Publischer:
`[IntegrationEvent] OnBeforeCalLotSizeCalcMfgItem(VAR slMatVar : Decimal;VAR slCapVar : Decimal;VAR slSubVar : Decimal;VAR slCapOvhdVar : Decimal;VAR slMfgOvhdVar : Decimal;VAR itemVar : Record Item;lotSizePar : Decimal;mfgItemQtyBasePar : Decimal;levelPar : Integer;calcDatePar : Date)`

Thanks in advanced,
Benjamin

**Comment by StanPesotskiy** [comment]
What parameters should be passed by reference?

**Comment by BenjaminHochstetter** [comment]
Hi Stan,

The parameter `slMat, slCap, slSub, slCapOvhd, MfgOvhd, item` should be passed by reference

Thanks in advance,
Benjamin
