### ISSUE TITLE
[Refactoring]: Get VAT Account in CU12

### ISSUE THREAD

**Issue by grabnar** [microsoft/ALAppExtensions#3306]
We need an option to change VAT account when posting VAT through vat posting setup in Codeunit 12, to a something else. Now is an option to get only realized VAT account or Unrealized VAT account for sales or purchase from VAT Posting Setup.

Functions in VAT posting setup table should have additional parameter Gen. Journal line or something like that, that we have possibility to add third or fourth option of VAT Account added to VAT posting setup (Non-deductible VAT Account, Postponed VAT Account,... )

Solution with changing VAT Prod. posting group or VAT Business posting group, is not an option. 

Current functions are in table VAT Posting Setup, they should be changed:

[External] GetSalesAccount(Unrealized : Boolean) : Code[20]
IF Unrealized THEN BEGIN
  IF "Sales VAT Unreal. Account" = '' THEN
    PostingSetupMgt.SendVATPostingSetupNotification(Rec,FIELDCAPTION("Sales VAT Unreal. Account"));
  TESTFIELD("Sales VAT Unreal. Account");
  EXIT("Sales VAT Unreal. Account");
END;
IF "Sales VAT Account" = '' THEN
  PostingSetupMgt.SendVATPostingSetupNotification(Rec,FIELDCAPTION("Sales VAT Account"));
TESTFIELD("Sales VAT Account");
EXIT("Sales VAT Account");

[External] GetPurchAccount(Unrealized : Boolean) : Code[20]
IF Unrealized THEN BEGIN
  IF "Purch. VAT Unreal. Account" = '' THEN
    PostingSetupMgt.SendVATPostingSetupNotification(Rec,FIELDCAPTION("Purch. VAT Unreal. Account"));
  TESTFIELD("Purch. VAT Unreal. Account");
  EXIT("Purch. VAT Unreal. Account");
END;
IF "Purchase VAT Account" = '' THEN
  PostingSetupMgt.SendVATPostingSetupNotification(Rec,FIELDCAPTION("Purchase VAT Account"));
TESTFIELD("Purchase VAT Account");
EXIT("Purchase VAT Account");

[External] GetRevChargeAccount(Unrealized : Boolean) : Code[20]
IF Unrealized THEN BEGIN
  IF "Reverse Chrg. VAT Unreal. Acc." = '' THEN
    PostingSetupMgt.SendVATPostingSetupNotification(Rec,FIELDCAPTION("Reverse Chrg. VAT Unreal. Acc."));
  TESTFIELD("Reverse Chrg. VAT Unreal. Acc.");
  EXIT("Reverse Chrg. VAT Unreal. Acc.");
END;
IF "Reverse Chrg. VAT Acc." = '' THEN
  PostingSetupMgt.SendVATPostingSetupNotification(Rec,FIELDCAPTION("Reverse Chrg. VAT Acc."));
TESTFIELD("Reverse Chrg. VAT Acc.");
EXIT("Reverse Chrg. VAT Acc.");

**Comment by AlexanderYakunin** [comment]
You can extend table VAT Posting Setup with more account fields and add needed procedures for them. There is no need to change signatures of existing procedures.

**Comment by grabnar** [comment]
We have problem at least whith this part of code in CU12 in function InsertVAT (now there is no way to post VAT to account defined in new filed from table VAT posting setup):

  // VAT for G/L entry/entries
  IF (GLEntryVATAmount <> 0) OR
     ((SrcCurrGLEntryVATAmt <> 0) AND (SrcCurrCode = AddCurrencyCode))
  THEN
    CASE "Gen. Posting Type" OF
      "Gen. Posting Type"::Purchase:
        CASE VATPostingSetup."VAT Calculation Type" OF
          VATPostingSetup."VAT Calculation Type"::"Normal VAT",
          VATPostingSetup."VAT Calculation Type"::"Full VAT":
            **CreateGLEntry(GenJnlLine,VATPostingSetup.GetPurchAccount(UnrealizedVAT),
              GLEntryVATAmount,SrcCurrGLEntryVATAmt,TRUE);**
          VATPostingSetup."VAT Calculation Type"::"Reverse Charge VAT":
            BEGIN
              **CreateGLEntry(GenJnlLine,VATPostingSetup.GetPurchAccount(UnrealizedVAT),
                GLEntryVATAmount,SrcCurrGLEntryVATAmt,TRUE);
              CreateGLEntry(GenJnlLine,VATPostingSetup.GetRevChargeAccount(UnrealizedVAT),
                -GLEntryVATAmount,-SrcCurrGLEntryVATAmt,TRUE);**
            END;
          VATPostingSetup."VAT Calculation Type"::"Sales Tax":
            IF "Use Tax" THEN BEGIN
              InitGLEntryVAT(GenJnlLine,TaxJurisdiction.GetPurchAccount(UnrealizedVAT),'',
                GLEntryVATAmount,SrcCurrGLEntryVATAmt,TRUE);
              InitGLEntryVAT(GenJnlLine,TaxJurisdiction.GetRevChargeAccount(UnrealizedVAT),'',
                -GLEntryVATAmount,-SrcCurrGLEntryVATAmt,TRUE);
            END ELSE
              InitGLEntryVAT(GenJnlLine,TaxJurisdiction.GetPurchAccount(UnrealizedVAT),'',
                GLEntryVATAmount,SrcCurrGLEntryVATAmt,TRUE);
        END;
      "Gen. Posting Type"::Sale:
        CASE VATPostingSetup."VAT Calculation Type" OF
          VATPostingSetup."VAT Calculation Type"::"Normal VAT",
          VATPostingSetup."VAT Calculation Type"::"Full VAT":
            **CreateGLEntry(GenJnlLine,VATPostingSetup.GetSalesAccount(UnrealizedVAT),
              GLEntryVATAmount,SrcCurrGLEntryVATAmt,TRUE);**
          VATPostingSetup."VAT Calculation Type"::"Reverse Charge VAT":
            ;
          VATPostingSetup."VAT Calculation Type"::"Sales Tax":
            InitGLEntryVAT(GenJnlLine,TaxJurisdiction.GetSalesAccount(UnrealizedVAT),'',
              GLEntryVATAmount,SrcCurrGLEntryVATAmt,TRUE);
        END;
    END;
END;
