### ISSUE TITLE
[Event Request] Report 7000097 Reject Docs. - OnAfterPostGenJournal

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#3311]
We need a new event in Report 7000097 "Reject Docs.":

**OnAfterPostGenJournal(VAR GenJnlLine : Record "Gen. Journal Line";CustLedgEntry : Record "Cust. Ledger Entry")**

Called from:

**_CustLedgEntry - OnPostDataItem()_**
IF GenJnlLine.FIND('-') THEN
  REPEAT
    IF ArePostedDocs THEN BEGIN
      PostedDoc2.SETRANGE("Document No.",GenJnlLine."Document No.");
      IF PostedDoc2.FIND('-') THEN
        REPEAT
          PostedBillGr.GET(PostedDoc2."Bill Gr./Pmt. Order No.");
          DocPost.CloseBillGroupIfEmpty(PostedBillGr,PostingDate);
        UNTIL PostedDoc2.NEXT = 0;
    END;
  UNTIL GenJnlLine.NEXT = 0;
**//init insert ---------------------------------------------
OnAfterPostGenJournal(GenJnlLine,CustLedgEntry);
//End insert ---------------------------------------------**
PostGenJournal;
.....
.....

**Comment by StanPesotskiy** [comment]
the requested event is named AnAfterPostGenJournal but the next line is PostGenJournal. 
Did you mean OnBefore?

**Comment by TxusMoyano** [comment]
Yes, sorry. It's really **OnBeforePostGenJournal**.

Thank you.
