### ISSUE TITLE
PAGE 6510 OnAfterSetSourceSpec Make Global Var Access

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#3327]
Can we make publisher OnAfterSetSourceSpec on Page 6510 Item tracking Lines Publisher GlobalVarAccess = TRUE?

**Comment by StanPesotskiy** [comment]
"Events should not expose global variables. This warning will become an error in a future release." This is the standard AL warning. We are not going to turn GlobalVarAccess on.
We will have to refactor the page to make it extensible. 

Can you describe a scenario that you would like to implement? 
What page's behaviour you would like to modify?

**Comment by MatthewMcCarthy7** [comment]
Right now we have fields OnOpenPage that determine if fields should be visible and editable based on whether it was a Reclass RunFormMode and Inbound.  So I would need a new function/access to the variables FormRunMode and Inbound, so I could set the visibility correct on my fields

![image](https://user-images.githubusercontent.com/32099690/61336768-7a246400-a7e7-11e9-9399-12c7873bb441.png)

**Comment by MatthewMcCarthy7** [comment]
This is handled by functions GetEditableSettings, and GetVisibleSettings that are now in the latest wave 2 release.
