### ISSUE TITLE
[Event Request] Report 951 Suggest Res. Jnl. Lines -OnBeforeInsertResJnlLine in OnPostDataItem()

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/ALAppExtensions#3332]
Please add publisher for object **Report 951 Suggest Res. Jnl. Lines** inside trigger **Resource - OnPostDataItem()** called:

``OnBeforeInsertResJnlLine(ResJnlLine,TimeSheetHeader,TempTimeSheetLine,TimeSheetDetail,ResJnlTemplate,ResJnlBatch);``

Publisher should be invoked before ResJnlLine.INSERT:

![image](https://user-images.githubusercontent.com/20359384/61273944-fd739480-a7aa-11e9-9503-75a27c63d991.png)

**Comment by StanPesotskiy** [comment]
Should ResJnlLine only be passed by reference?
