### ISSUE TITLE
Codeunit 5830 Calc. Availability Overview

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3334]
New Event Request in function InsertEntry

OnBeforeInsertAvailabilityCalcOverview(VAR AvailabilityCalcOverview)

**Comment by ThorstenEngelsGOB** [comment]
And in the same Codeunit in function UpdateRunningTotals

OnBeforeModifyAvailabilityCalcOverview(VAR AvailabilityCalcOverview)

**Comment by StanPesotskiy** [comment]
please put a few lines of code surrounding the requested event to make sure we understand the request right.
