### ISSUE TITLE
Codeunit 5878 Phys. Invt. Rec.-Reopen

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3335]
Please add the event trigger OnBeforePhysInvtOrderLineModify

**Comment by StanPesotskiy** [comment]
Please provide enough details:

where to put it? put some code context...
what parameters should it have?

**Comment by ThorstenEngelsGOB** [comment]
PhysInvtOrderLine."On Recording Lines" := PhysInvtOrderLine."No. Finished Rec.-Lines" <> 0;
        
        // S/NEW
        OnBeforePhysInvtOrderLineModify(PhysInvtOrderLine);
        // E/NEW
        
       PhysInvtOrderLine.MODIFY;
