### ISSUE TITLE
Codeunit 5880 Phys. Invt. Order-Finish

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3336]
Please add the event trigger OnBeforePhysInvtOrderLineModify

**Comment by StanPesotskiy** [comment]
Please provide enough details:

where to put it? put some code context...
what parameters should it have?

**Comment by ThorstenEngelsGOB** [comment]
O.K. the first Publisher here:
        PhysInvtOrderLine.CalcCosts;

        // S/NEW
        OnBeforePhysInvtOrderLineModify(PhysInvtOrderLine);
        // E/NEW

        PhysInvtOrderLine.MODIFY;


The second here
                PhysInvtOrderLine2."Neg. Qty. (Base)" := PhysInvtOrderLine2."Quantity (Base)";

              // S/New
              OnBeforePhysInvtOrderLineTwoModify(PhysInvtOrderLine2);
              // E/New

              PhysInvtOrderLine2.MODIFY;

Both Publisher in function Code
