### ISSUE TITLE
Codeunit 5882 Phys. Invt. Order-Reopen

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3337]
Please add the event trigger OnBeforePhysInvtOrderLineModify

**Comment by StanPesotskiy** [comment]
Please provide enough details:
- where to put it? put some code context...
- what parameters should it have?

**Comment by ThorstenEngelsGOB** [comment]
;O) there is only one PhysInvtOrderLine.MODIFY; The Codeunit is very small, Parameter only the Phys. Inventory Line

**Comment by kwettermann** [comment]
Do you have any update on this event @jobulsin ? BC15CU2 and 16.0.10727.0 sandbox does not have this event.
