### ISSUE TITLE
Codeunit 5522 Order Planning Mgt.

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3356]
Please insert new Publisher in function InsertAltSupplyLocation

      TempReqLine."Quantity (Base)" := AvailableQtyBase;

      // S/NEW
      OnBeforeInsertTempReqLine(TempReqLine);;
      // E/NEW

      TempReqLine.INSERT;

**Comment by StanPesotskiy** [comment]
Would passing TempReqLine by value be enough?

**Comment by ThorstenEngelsGOB** [comment]
Please by VAR - thx
