### ISSUE TITLE
Codeunit 5531 Calc. Inventory Page Data

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3357]
1) Please insert new Publisher in funcion TransferToPeriodDetails in the end of the function, NOT as an Else Part of the SourceType

OnAfterTransferToPeriodDetails(InventoryPageData,FromInvtEventBuf)

2) Please Insert a new Publisher in function DetailsFor PeriodEntry:

InvtPageData.COPY(PeriodInvtPageData);

// S/New
OnBeforeModifyInvtPageDataOnAfterCopyPeriodInvtPageData(InvtPageData);
// E/NEW

InvtPageData.MODIFY;

**Comment by StanPesotskiy** [comment]
Should all parameters be passe by value or by reference? Please put it explicitly.

**Comment by ThorstenEngelsGOB** [comment]
Please by VAR, Thx
