### ISSUE TITLE
Page 10053: Service Stats Tax Included Code Issue

### ISSUE THREAD

**Issue by thebiggfudge** [microsoft/ALAppExtensions#3358]
On the "Service Stats." page, in the **OnAfterGetRecord** method, the call to **ServAmtsMgt.SumServiceLinesTemp** is before the call to **SalesTaxCalculate.DistTaxOverServLines**. This causes the total that was summed in **ServAmtsMgt.SumServiceLinesTemp** to be incorrect when sales tax is included in the price. There is code around the **SalesTaxCalculate.DistTaxOverServLines** code to call **ServAmtsMgt.SumServiceLinesTemp** after the call to **SalesTaxCalculate.DistTaxOverServLines**. I believe that the commented out code should be uncommented.

**Comment by StanPesotskiy** [comment]
Please report this issue via the standard support channel. This is not related to extensibility.
