### ISSUE TITLE
Codeunit 5431 Calc. Item Plan - Plan Wksh.

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3359]
Please Insert an Event in function CheckPreconditions with handled Flag to be able to switch off the checks as required or to insert your own checks.

**Comment by StanPesotskiy** [comment]
Please provide your code suggestions as you would do this. 
This speeds up the process significantly.

**Comment by ThorstenEngelsGOB** [comment]
LOCAL CheckPreconditions()
IsHandled := FALSE;
OnBeforeCheckPreconditions(Item,MPS,MRP,FromDate,ToDate,IsHandled);
IF IsHandled THEN
  EXIT;
