### ISSUE TITLE
Table 1304 Sales Price and Line Disc Buff

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3369]
1) Please Insert a new Publisher in function LoadSalesPrice

OnBeforeInsertSalesPriceAndLineDiscBuff(VAR Rec, SalesPrice);

2) Please Insert a new Publisher in function InsertNewPriceLine

OnBeforeInsertSalesPrice(VAR SalesPrice, Rec);

3) Please Insert a new Publisher in function InsertNewDiscountLine

OnBeforeInsertSalesLineDiscount(VAR SalesLineDiscount, Rec);

**Comment by StanPesotskiy** [comment]
We get hundreds of event requests per month. If you want your requests to be handled quick and precise please provide the code snipets making no place for guesses from our side. If your suggestion is relevant and passes our review it will be simply implemented as you want with minimal adjustments. 
The simplest way is to implement an event in your local DB and copy&paste pieces of code you have added with few lines around your change to make sure we understand, where exactly you put this code.

**Comment by ThorstenEngelsGOB** [comment]
I'm well aware of that and I'll be happy to give you the code locations. In this case the functions and the code locations are so unique that I didn't specify them.
But I will improve and promise to describe the next requests in more detail.
BTW...You could have saved the whole requests for the insert, modify or delete places, if it would be possible for the subscriber to query for an origin, something like a caller ID or something similar.
