### ISSUE TITLE
[Key Request] a new key request on VAT Entry table

### ISSUE THREAD

**Issue by muratkarabek** [microsoft/ALAppExtensions#3374]
Hi,

We need the key below on table 254-"VAT Entry".

> Type,Document Type,Bill-to/Pay-to No.,Document Date,Transaction No. (SIFs: Base)

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
We are going to deliver possibility for partners to add table keys soon. Closing this old request for now.
