### ISSUE TITLE
Table 112 Sales Invoice Header GetSellToCustomerFaxNo FunctionVisibility

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#3381]
Dear Development Team,

can you change the FunctionVisibility of the GetSellToCustomerFaxNo Function in Table 112 "Sales Invoice Header" to External? It's causing issues when trying to compile Report 1306 for example.

All other functions "around it" are External:

![image](https://user-images.githubusercontent.com/39408604/61443761-0b0f5280-a942-11e9-9dc9-c56ffbf7dcc4.png)

Cheers,
Marton

**Comment by miljance** [comment]
Hi, it doesn't seem that the function GetSellToCustomerFaxNo has been exposed externaly as it got the property:
[Scope('OnPrem')]

Could you please check the function exposure once again?

**Comment by martonnagy** [comment]
> miljance <notifications@github.com>
> Fri 29/11/2019 14:52
> 
> Hi, it doesn't seem that the function GetSellToCustomerFaxNo has been exposed externaly as it got > the property:
> [Scope('OnPrem')]
> 
> Could you please check the function exposure once again?

Hi,

so do you want me to check this is V15? Because when I've reported this V14 was the latest version...

Cheers,
Marton

**Comment by miljance** [comment]
> > miljance [notifications@github.com](mailto:notifications@github.com)
> > Fri 29/11/2019 14:52
> > Hi, it doesn't seem that the function GetSellToCustomerFaxNo has been exposed externaly as it got > the property:
> > [Scope('OnPrem')]
> > Could you please check the function exposure once again?
> 
> Hi,
> 
> so do you want me to check this is V15? Because when I've reported this V14 was the latest version...
> 
> Cheers,
> Marton

Hi,

No, the Table 112 seems just fine. The Scope property is however present in the table 36. For that purpose I opened a new Issue:
https://github.com/microsoft/ALAppExtensions/issues/5086#issue-530385236
