### ISSUE TITLE
Inconsistent Event Signatures in Codeunit 90

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#3382]
Dear Development Team

Whilst my colleague continued working with Codeunit 90 events in BC140, more issues with parameter names and spelling noticed.

### Example Event Signature in Codeunit 90:

- Usage of **PurchHeader** and **PurchaseHeader** is inconsistent as is **PurchaseLine** and **PurchLine**.
- _CommitIsSuppressed_ is misspelt in most events, though not all.
- Possibly missing **VAR** from OnAfterDivideAmount?

OnAfterCheckPurchDoc(VAR **PurchHeader**: Record "Purchase Header"; _CommitIsSupressed_: Boolean; WhseShip: Boolean; WhseReceive: Boolean)

OnAfterCheckAndUpdate(VAR **PurchaseHeader**: Record "Purchase Header"; _CommitIsSuppressed_: Boolean; PreviewMode: Boolean)

OnAfterCheckTrackingAndWarehouseForReceive(VAR **PurchaseHeader**: Record "Purchase Header"; VAR Receive: Boolean; _CommitIsSupressed_: Boolean)

OnAfterCheckTrackingAndWarehouseForShip(VAR **PurchaseHeader**: Record "Purchase Header"; VAR Ship: Boolean; _CommitIsSupressed_: Boolean)

OnAfterCreatePostedDeferralScheduleFromPurchDoc(VAR **PurchaseLine**: Record "Purchase Line"; VAR PostedDeferralHeader: Record "Posted Deferral Header")

OnAfterDeleteAfterPosting(**PurchHeader**: Record "Purchase Header"; PurchInvHeader: Record "Purch. Inv. Header"; PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; _CommitIsSupressed_: Boolean)

OnAfterDivideAmount(**PurchHeader**: Record "Purchase Header"; VAR **PurchLine**: Record "Purchase Line"; QtyType: 'General,Invoicing,Shipping'; PurchLineQty: Decimal; VAR TempVATAmountLine: TEMPORARY Record "VAT Amount Line"; VAR TempVATAmountLineRemainder TEMPORARY Record “VAT Amount Line”)

[IntegrationEvent] OnAfterPostPurchaseDoc(VAR **PurchaseHeader**: Record "Purchase Header"; VAR GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; PurchRcpHdrNo: Code[20]; RetShptHdrNo: Code[20]; PurchInvHdrNo: Code[20]; PurchCrMemoHdrNo: Code[20]; _CommitIsSupressed_: Boolean)

OnAfterPostPurchaseDocDropShipment(SalesShptNo: Code[20]; _CommitIsSupressed_: Boolean)

OnAfterUpdatePostingNos(VAR **PurchaseHeader**: Record "Purchase Header"; VAR NoSeriesMgt: Codeunit NoSeriesManagement; _CommitIsSupressed_: Boolean)

OnAfterCheckMandatoryFields(VAR **PurchaseHeader**: Record "Purchase Header"; _CommitIsSupressed_: Boolean)

OnAfterFillInvoicePostBuffer(VAR InvoicePostBuffer: Record "Invoice Post. Buffer"; **PurchLine**: Record "Purchase Line"; VAR TempInvoicePostBuffer: TEMPORARY Record "Invoice Post. Buffer"; _CommitIsSupressed_: Boolean)

### Comparison with Codeunit 80 (Sales-Post):

- SalesHeader and SalesLine are consistent and predictable.
- CommitIsSuppressed is consistently and correctly spelt.

OnBeforePostLines(VAR **SalesLine**: Record "Sales Line"; **SalesHeader**: Record "Sales Header"; _CommitIsSuppressed_: Boolean; PreviewMode: Boolean)

OnBeforePostSalesDoc(VAR **SalesHeader**: Record "Sales Header"; _CommitIsSuppressed_: Boolean; PreviewMode: Boolean)

OnBeforePostCommitSalesDoc(VAR **SalesHeader**: Record "Sales Header"; VAR GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; PreviewMode: Boolean; ModifyHeader: Boolean; _CommitIsSuppressed_: Boolean; VAR TempSalesLineGlobal: TEMPORARY Record “Sales Line”)

OnAfterCheckSalesDoc(VAR **SalesHeader**: Record "Sales Header"; _CommitIsSuppressed_: Boolean; WhseShip: Boolean; WhseReceive: Boolean)

OnAfterCheckAndUpdate(VAR **SalesHeader**: Record "Sales Header"; _CommitIsSuppressed_: Boolean; PreviewMode: Boolean)

OnAfterCheckTrackingAndWarehouseForReceive(VAR **SalesHeader**: Record "Sales Header"; VAR Receive: Boolean; _CommitIsSuppressed_: Boolean; VAR TempWhseShptHeader: TEMPORARY Record "Warehouse Shipment Header"; VAR TempWhseRcptHeader

OnAfterCheckTrackingAndWarehouseForShip(VAR **SalesHeader**: Record "Sales Header"; VAR Ship: Boolean; _CommitIsSuppressed_: Boolean; VAR TempWhseShptHeader: TEMPORARY Record "Warehouse Shipment Header"; VAR TempWhseRcptHeader: TEMPORARY Record “Warehouse Receipt Header”)

OnAfterCreatePostedDeferralScheduleFromSalesDoc(VAR **SalesLine**: Record "Sales Line"; VAR PostedDeferralHeader: Record "Posted Deferral Header")

OnAfterDeleteAfterPosting(**SalesHeader**: Record "Sales Header"; SalesInvoiceHeader: Record "Sales Invoice Header"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; _CommitIsSuppressed_: Boolean)

OnAfterFillInvoicePostBuffer(VAR InvoicePostBuffer: Record "Invoice Post. Buffer"; **SalesLine**: Record "Sales Line"; VAR TempInvoicePostBuffer: TEMPORARY Record "Invoice Post. Buffer"; _CommitIsSuppressed_: Boolean)

I've already logged issue #3294 in specifically for a Function

Cheers,
Marton

**Comment by StanPesotskiy** [comment]
Unfortunately we are limited in renaming/moving parameters of events that were already released.
We can add VAR and add new parameters to the end of the list of the existing events.
