### ISSUE TITLE
[Function Expose] Table 9650 - Custom Report Layout - ImportLayoutBlob

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#3385]
Dear ALAppExtensions team,

Through this issue we would like to request procedure `ImportLayoutBlob` to be made **external**.
Currently, we have a copy of its implementation in a custom procedure for our extension, but it would be better if we can just call the existing procedure.

**Comment by rvanbekkum** [comment]
Same goes for procedure `InitBuiltInLayout`, see issue #3160.

**Comment by RomanZanizdra** [comment]
Hi rvanbekkum. Seems we will not be able to expose ImportLayoutBlob function.
For InitBuilt… function I don't see any problems, it will be processed.
I will close current issue for now. Feel free to re-open it if you think something else can be done here.
