### ISSUE TITLE
Report 11000003 Paymt. History - Change Status - UpdateDirectDebitMandate (NL)

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3386]
We would like to have the function 'UpdateDirectDebitMandate' global and external. 

In fact you may want to consider moving the function to the payment history line table because it stands on its own and is generic enough. However I leave that up to you.

Many thanks.

**Comment by RomanZanizdra** [comment]
Ok, let's just make it external and available for AL development for now. Will see what's next.
