### ISSUE TITLE
Report 11000013 SEPA ISO20022 Pain 008.001.02 - AddPaymentInformation (NL)

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3390]
We would like to adjust the 'BtchBookg' parameter in the SEPA xml file. To make this possible we require the following code change and publisher:

    LOCAL PROCEDURE AddPaymentInformation@1000001(XMLNodeCurr@1000000 : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";PaymentHistoryLine@1000003 : Record 11000002;VAR BankAcc@1000004 : Record 270);
    VAR
      Customer@1000013 : Record 18;
      LocalFunctionalityMgt@1000007 : Codeunit 11400;
      XMLNewChild@1000001 : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";
      PaymentInformationId@1000002 : Text[60];
      TotalAmount@1000006 : Text[50];
      LineCount@1000005 : Text[20];
      BtchBookg@1000000001 : Text;
    BEGIN
      Customer.GET(PaymentHistoryLine."Account No.");

      ///// START
      BtchBookg := 'false';
      OnBeforeAddPaymentInformation(PaymentHistoryLine, BankAcc, Customer, BtchBookg);
      ///// LV20190718JB/e
      AddElement(XMLNodeCurr,'PmtInf','','',XMLNewChild);
      XMLNodeCurr := XMLNewChild;

      PaymentInformationId := PaymentHistoryLine."Our Bank" + PaymentHistoryLine."Run No." + FORMAT(PaymentHistoryLine."Line No.");
      IF STRLEN(PaymentInformationId) > 35 THEN
        PaymentInformationId := COPYSTR(PaymentInformationId,STRLEN(PaymentInformationId) - 34);

      AddElement(XMLNodeCurr,'PmtInfId',PaymentInformationId,'',XMLNewChild);
      AddElement(XMLNodeCurr,'PmtMtd','DD','',XMLNewChild);

      ///// START
      //AddElement(XMLNodeCurr,'BtchBookg','false','',XMLNewChild);
      AddElement(XMLNodeCurr,'BtchBookg',BtchBookg,'',XMLNewChild);
      ///// END

      LocalFunctionalityMgt.GetPmtHistLineCountAndAmtPmtInf(TotalAmount,LineCount,"Payment History",PaymentHistoryLine);
      AddElement(XMLNodeCurr,'NbOfTxs',LineCount,'',XMLNewChild);
      AddElement(XMLNodeCurr,'CtrlSum',TotalAmount,'',XMLNewChild);

And the signature of the publisher:

    [Integration]
    LOCAL PROCEDURE OnBeforeAddPaymentInformation@11095585(PaymentHistoryLine@11095585 : Record 11000002;VAR BankAccount@11095587 : Record 270;VAR Customer@11095586 : Record 18;VAR BatchBookg@11095588 : Text);
    BEGIN
    END;

Many thanks.

**Comment by fvet** [comment]
@lv-janpieter, FYI, seems like in BE a new setting had been introduced: #2365

**Comment by lv-janpieter** [comment]
@fvet
Yeah would be nice if SEPA was delivered as a seperate extension instead of localized for each country...

**Comment by lv-janpieter** [comment]
This publisher has been incorrectly implemented. The call of the publisher should happen after Customer.GET. I will issue a new request.
