### ISSUE TITLE
Report 11000013 SEPA ISO20022 Pain 008.001.02 - ExportSEPAFile (NL)

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3391]
One of our customers has a requirement to include a hash signature to the SEPA file. So we need a possibility to edit the exported file before being downloaded. To make this possible we would like to request the following publisher:

    LOCAL PROCEDURE ExportSEPAFile@1000005();
    VAR
      FileMgt@1000003 : Codeunit 419;
      XMLDOMManagement@1000006 : Codeunit 6224;
      XMLRootElement@1000002 : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlElement";
      XMLNodeCurr@1000001 : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";
      XMLNewChild@1000000 : DotNet "'System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Xml.XmlNode";
      StreamWriter@1000005 : DotNet "'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.StreamWriter";
      UTF8Encoding@1000004 : DotNet "'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Text.UTF8Encoding";
      ServerTempFileName@1170000001 : Text[250];
    BEGIN
      XMLDOMManagement.LoadXMLDocumentFromText('<?xml version="1.0" encoding="UTF-8"?><Document></Document>',XMLDomDoc);
      XMLRootElement := XMLDomDoc.DocumentElement;
      XMLRootElement.SetAttribute('xmlns','urn:iso:std:iso:20022:tech:xsd:pain.008.001.02');
      XMLRootElement.SetAttribute('xmlns:xsi','http://www.w3.org/2001/XMLSchemainstance');
      XMLNodeCurr := XMLDomDoc.SelectSingleNode('Document');
      AddElement(XMLNodeCurr,'CstmrDrctDbtInitn','','',XMLNewChild);

      ExportGroupHeader(XMLNewChild);
      ExportPaymentInformation(XMLNewChild);

      ServerTempFileName := FileMgt.ServerTempFileName('xml');
      StreamWriter := StreamWriter.StreamWriter(ServerTempFileName,FALSE,UTF8Encoding.UTF8Encoding(FALSE));
      OnBeforeXMLDomDocSave(XMLDomDoc);
      XMLDomDoc.Save(StreamWriter);
      StreamWriter.Close;
      ///// START
      OnBeforeDownloadFile("Payment History", ServerTempFileName);
      ///// END

      FileMgt.DownloadToFile(ServerTempFileName,ExportFileName);

      CLEAR(XMLDomDoc);
    END;

And the signature of the publisher:

    [Integration]
    LOCAL PROCEDURE OnBeforeDownloadFile@11095586(PaymentHistory@11095585 : Record 11000001;ServerTempFileName@11095586 : Text);
    BEGIN
    END;

Many thanks.

**Comment by StanPesotskiy** [comment]
We will not expose the server file name. What would be another API to help you?

**Comment by lv-janpieter** [comment]
Some banks are offering additional security to ensure the banking file has not been modified between exporting from BC and receiving by the bank. We generate a hash, the bank also knows how to generate a hash and if they are not equal the bank won't accept the file.

In this case the generated hash has to be written at the end of the file, outside the XML structure. The only place we can still do this is between closing the streamwriter and donwloading the file.
The functionality is quite important from a security perspective because it prevents adding payments by editing the file. Would you agree if I provided you the code we use to manipulate the file? And that we provide the content to be written by using a new publisher?

If not we would really like you to reconsider providing the ServerTempFileName.

Many thanks.

**Comment by lv-janpieter** [comment]
I see you have labeled this is issue for refactoring. I was mistaken, we do need the whole file to calculate a checksum. So the proposed publisher just to provide you with a text would not work because without the file we will not be able to calculate a checksum.

We wouldn't mind if you included everything in the NL base. So this is all the code involved. AddHashToFile is called after StreamWriter.Close;

- Checksum is a field of type text length 50
- Add Checksum is a boolean field on table "Export Protocol"


      PROCEDURE AddHashToFile@1000000004(ServerTempFileName@1000000000 : Text);
      VAR
        lrecExportProtocol@1000000006 : Record 11000005;
        lfFile@1000000005 : File;
        ltCRLF@1000000004 : Text[2];
        lcuEncryptionManagement@1000000001 : Codeunit 11199961;
      BEGIN
        IF (ServerTempFileName = '') THEN
        BEGIN
          EXIT;
        END;

        lrecExportProtocol.GET("Export Protocol");
        IF NOT lrecExportProtocol."Add Checksum" THEN
        BEGIN
          EXIT;
        END;

        Checksum := GetSHA1FromFile(ServerTempFileName);

        MODIFY;

        ltCRLF[1] := 13;
        ltCRLF[2] := 10;

        lfFile.TEXTMODE  := TRUE;
        lfFile.WRITEMODE := TRUE;
        lfFile.OPEN(ServerTempFileName);
        lfFile.SEEK(lfFile.LEN);
        lfFile.WRITE(ltCRLF + Checksum);
        lfFile.SEEK(lfFile.POS - 2);
        lfFile.TRUNC;
        lfFile.CLOSE;
      END;

.

      LOCAL PROCEDURE GetSHA1FromFile@11095585(InputFileName@11095585 : Text) : Text;
      VAR
        lclsSHA1CryptoServiceProvider@11095586 : DotNet "'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Security.Cryptography.SHA1CryptoServiceProvider";
      BEGIN
        lclsSHA1CryptoServiceProvider := lclsSHA1CryptoServiceProvider.SHA1CryptoServiceProvider();
        EXIT(GetHashStringFromFile(InputFileName, lclsSHA1CryptoServiceProvider));
      END;

.

      LOCAL PROCEDURE GetHashStringFromFile@11095588(InputFileName@11095585 : Text;HashAlgorithm@11095586 : DotNet "'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.Security.Cryptography.HashAlgorithm") : Text;
      VAR
        lclsFileStream@11095587 : DotNet "'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.FileStream";
        lclsBitConverter@11095588 : DotNet "'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.BitConverter";
        lclsHashString@11095589 : DotNet "'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.String";
        ltReturnHash@11095590 : Text;
      BEGIN
        IF NOT GetFileStream(InputFileName, lclsFileStream) THEN
        BEGIN
          EXIT('');
        END;

        lclsHashString := lclsBitConverter.ToString(HashAlgorithm.ComputeHash(lclsFileStream));
        ltReturnHash := lclsHashString.Replace('-', '');
        lclsFileStream.Close();

        EXIT(ltReturnHash);
      END;

**Comment by PredragMaricic** [comment]
Hi,

Sorry for the huge delay, We have CryptographyManagement.Codeunit.al with relevant functions (GenerateHash)  that you can use. Please take a look and contact me if needed.

**Comment by lv-janpieter** [comment]
Hi @PredragMaricic thanks for replying. Generating the hash is not the main problem although of course we would start using this codeunit when we could.

However main problem is we need access to the file (or perhaps filestream may also succeed) to be able to add the hash to the end of the file. The hash is generated from the file so I'm not even sure a filestream will work. As long as the file is not exposed we are unable to add the hash to the file in an automatic and secure way.

So either there are 2 options:
- by a publisher that exposed the server filename, however this is denied see @StanPesotskiy reply.
- or the functionality is added as standard solution.

Right now we have to make a replacement report for this export because we cannot sign the file and this is against security policy of some of our customers because an unsigned file allows the user to manually edit this file.

**Comment by PredragMaricic** [comment]
Got it. Let me see what I can do.

**Comment by PredragMaricic** [comment]
Hi,
Can I have your contact email to discuss a few points? Or you can send me email: pmaricic@microsoft.com

**Comment by PredragMaricic** [comment]
Hi Jan,

I sent you a code containing your proposals. Can you please take a look, so that we can proceed?

Thanks,
Predrag

**Comment by PredragMaricic** [comment]
The update will be delivered with update 17.4.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for releasee 17.
