### ISSUE TITLE
[Event Request] SelectTempReportSelectionsToPrint T77

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/ALAppExtensions#3394]
We would like to ability to manipulate which reports are printed/emailed without having to overwrite or use the standard report selections or document layout records. We would like to print/email specific reports on a document level not just a usage or customer level. Being able to populate the temp tables in T77 with our own reports would allow us to do this.

A new Event along the lines of : (for printing)
`OnAfterSelectTempReportSelectionsToPrint(RecordVariant : Variant; var TempReportSelections: Record "Report Selections" temporary;var TempNameValueBuffer: Record "Name/Value Buffer" temporary;WithCheck: Boolean;ReportUsage: Option;TableNo: Integer)`
With the RecordVariant and TempReportSelections we could subscribe to this event and manipulate the temp table based on the document number (as an example).

The report selection for emailing uses different logic – it would be good if these functions could be aligned (for selecting the reports to use) and again allow an integration point to manipulate the reports selected on a document level.

**Comment by StanPesotskiy** [comment]
What about adding an event OnSendEmailDirectlyOnBeforeSendFiles() to SendEmailDirectly just before the loop on TempAttachReportSelections:
  ```
SendEmailDirectly(...)
...
OnSendEmailDirectlyOnBeforeSendFiles(ReportUsage,RecordVariant,DefaultEmailAddress,TempAttachReportSelections,CustomReportSelection);
  WITH TempAttachReportSelections DO BEGIN
    OfficeAttachmentManager.IncrementCount(COUNT - 1);
    REPEAT
```
Would it help to customise report selection for emailing?
