### ISSUE TITLE
CU 5802 New Publisher OnAfterCreateItemLedgRelationEntry

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#3396]
Hi,
Is it possible to add new publisher in codeunit 5802 in function CreateGLItemLedgRelationEntry
After row **GLItemLedgRelation.INSERT;**
It should have parameters: 
OnAfterCreateItemLedgRelationEntry(**VAR GLItemLedgRelation**,GlobalInvtPostBuf,GLReg,TempGLItemLedgRelation);

**Comment by StanPesotskiy** [comment]
There is already
```
OnBeforeGLItemLedgRelationInsert(GLItemLedgRelation,GlobalInvtPostBuf);
GLItemLedgRelation.INSERT;
```
would it help you if we add parameters GLReg and TempGLItemLedgRelation?

**Comment by jelicastakic** [comment]
Yes, that would be ok. Thanks
