### ISSUE TITLE
[Event Request] Codeunit "User Setup Management" - 

### ISSUE THREAD

**Issue by Tino-T** [microsoft/ALAppExtensions#3402]
We need to be able to control the allowed posting period.

Our suggestion is to include an event in Codeunit `User Setup Management` (ID 5700) in the function `IsPostingDateValid`:

![image](https://user-images.githubusercontent.com/19926375/61529508-c78c1580-aa21-11e9-9f21-f90612bf001c.png)

**Comment by agolution** [comment]
I like
