### ISSUE TITLE
[Event Modification Request] Table 37 - Sales Line - SalesLine as VAR parameter in OnBeforeCheckAssocPurchOrder

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#3411]
Dear ALAppExtensions team,
Through this issue we would like to request parameter `SalesLine` in event publisher `OnBeforeCheckAssocPurchOrder` to be made **VAR**.

We found that the global variables of the record are _not_ kept when the record _is not_ passed as VAR, but the global variable values _are_ kept if it _is_ passed as VAR.
We did not know about this behaviour, is it intended?

**Comment by lv-janpieter** [comment]
Indeed this is how it has always been. VAR passes a reference. If not using VAR there will be a new instance and only fields are parsed. opinion).

We work often with a Getter and Setter function on the table setting a global variable.
It is the only way to let our subscribers have some information about where the process is originating from. There are a lot of processes automatically creating sales lines. And we try to avoid using single instance codeunits (bad practice in my opinion).

We had the exact same problem with this publisher not being able to use our Getter functions on the sales line. Thanks for requesting.
