### ISSUE TITLE
Table 37 Sales Line - fct. CalcPlannedShptDate new publisher

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#3417]
Hi,

for our application, we need a new Publisher in fct. CalcPlannedShptDate() as follows:

![image](https://user-images.githubusercontent.com/46744680/61616967-188e4a80-ac6a-11e9-8b57-7880a932b526.png)

thanks in advance,
best regards,
Kathrin

**Comment by StanPesotskiy** [comment]
Should Rec be passed by reference (with VAR) or by value (without VAR)?

**Comment by KReinmann** [comment]
The Rec should be passed by reference (with VAR) 
Thanks a lot.

**Comment by KReinmann** [comment]
And would it be possible to have an Parameter IsHandled?
