### ISSUE TITLE
[Event-Request] REP2000005 File SEPA Payments

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/ALAppExtensions#342]
We want to create the (NON-)SEPA payments file automatically.
Therefore we would like an event/function that allows us to set the parameters of the requestpage on the file payments reports and also another to hide that requestpage.

When clicking the ExportPaymentLines action on the PAG2000001 EB Payment Journal, the following code gets executed:
In TAB2000005 Export Protocol
```
ExportPaymentLines(VAR PmtJnlLine : Record "Payment Journal Line")
IF CheckPaymentLines(PmtJnlLine) THEN BEGIN
  TESTFIELD("Export Object ID");
  PmtJnlLineToExport.COPY(PmtJnlLine);
  PmtJnlLineToExport.SETRANGE(Status,PmtJnlLineToExport.Status::Created);
  PmtJnlLineToExport.SETRANGE("Export Protocol Code",Code);
  PmtJnlLineToExport.SETRANGE("Journal Batch Name",PmtJnlLine."Journal Batch Name");
  PmtJnlLineToExport.SETRANGE("Journal Template Name",PmtJnlLine."Journal Template Name");

  IF "Export Object Type"="Export Object Type"::Report THEN
////Here we would need something to hide the requestpage
////Such as: OnBeforeRunReportExportPaymentLines(VAR Rec, VAR ShowRequestpage, VAR PmtJnlLineToExport)
    REPORT.RUNMODAL("Export Object ID",TRUE,FALSE,PmtJnlLineToExport)
  ELSE BEGIN
    IF PmtJnlLine."Exported To File" THEN
      IF NOT CONFIRM(ExportAgainQst) THEN
        EXIT;
```
In both File payment reports (REP2000005 File SEPA Payments and REP2000006 File Non Euro SEPA Payments), we would need an event that's let us fill in the requestpage.
Something like
`OnAfterInit(VAR GenJnlLine, VAR AutomaticPosting, VAR IncludeDimText, VAR ExecutionDate, VAR FileName)`

Could these be provided please? :)
Version BE Dynamics NAV 13.0 (25789)

**Comment by wbor-nvt** [comment]
We are also working on a solution that requires running REP2000005 & REP2000006 with no Request Page.
TAB2000005 has already received the necessary OnBeforeExportPaymentLinesOnRunReport event.

There is still no way to alter the Global variables set in the Request page however.
Is this still planned for future update?

Ideal would be an OnBeforePreReport trigger 
`OnBeforePreReport(VAR GenJnlLine, VAR AutomaticPosting, VAR IncludeDimText, VAR ExecutionDate, VAR FileName)`

**Comment by BertDeTemmerman** [comment]
> @BertDeTemmerman Did you get your requested event in the meanwhile, to set the request page parameters, such as ExecutionDate?
> 
> > Something like
> > OnAfterInit(VAR GenJnlLine, VAR AutomaticPosting, VAR IncludeDimText, VAR ExecutionDate, VAR FileName)

Short: No.
Long: No.

But we can skip the 2nd report now ...
I think we just copied those reports or didn't implement this.

    local procedure PostPaymentJournal(var GenJnlLine: Record "Gen. Journal Line"; var PaymentJournalLine: Record "Payment Journal Line"; BalancingPostingDate: Date)
    var
        PaymentJournalPost: Report "Payment Journal Post";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostPaymentJournal(GenJnlLine, PaymentJournalLine, AutomaticPosting, BalancingPostingDate, IsHandled);
        if IsHandled then
            exit;

        PaymentJournalPost.SetParameters(GenJnlLine, AutomaticPosting, REPORT::"File SEPA Payments", BalancingPostingDate);
        PaymentJournalPost.SetTableView(PaymentJournalLine);
        PaymentJournalPost.RunModal;
    end;
