### ISSUE TITLE
[ENUM Request] Table 5405 - "Production Order" - Field 9 "Source Type"

### ISSUE THREAD

**Issue by cosmo-skol** [microsoft/ALAppExtensions#3426]
Hello AL-Team,
we need the field "Source Type" as ENUM to allow the production orders to have more source types.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
