### ISSUE TITLE
Variant Code in Production Header

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#3433]
Hi,

in the Production the Variant Code is only available on the production order line. 
I think thats not a good solution, because this way when we want to get a Production order to a specific Variant, we have to search in by the line and then get the Header using the line.

Please add field "Variant Code" to production Order (5405)

**Comment by AlexanderYakunin** [comment]
Thank you for your suggestion! We accept and complete such suggestions from aka.ms/bcideas portal, using votes. Please publish your suggestion there.
