### ISSUE TITLE
[Event Request] Codeunit 5882 "Phys. Invt. Order-Reopen" - OnRun()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#3441]
Could you please add an OnAfterPhysInvtOrderReopen()-Event in COD5882 Fct. OnRun()?

```
OnRun(VAR Rec : Record "Phys. Invt. Order Header")
PhysInvtOrderHeader.COPY(Rec);
Code;
Rec := PhysInvtOrderHeader;

OnAfterPhysInvtOrderReopen(Rec) // New Event
```

Publisher:

`LOCAL [IntegrationEvent] OnAfterPhysInvtOrderReopen(PhysInvtOrderHeader : Record "Phys. Invt. Order Header")`

many thanks
Stefan

**Comment by kwettermann** [comment]
Do you have any update on this event @jobulsin ? BC15CU2 and 16.0.10727.0 sandbox does not have this event.
