### ISSUE TITLE
RecreateSalesLines and RecreatePurchLines in T36 and T38

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3445]
A request for external was issued in issue #1280 and marked as 'Shipped in Future update'. However this change has not been performed in the spring release so I think something went wrong. 

Could you add global and external property on:

T36 Sales Header - RecreateSalesLines
T38 Purchase Header - RecreatePurchLines

Many thanks.

**Comment by RomanZanizdra** [comment]
Looks like the spring update was already frozen for changes when mentioned issue was processed. These procedures are external now and will be available for AL development in the next update.
