### ISSUE TITLE
Codeunit 7324 - Whse.-Activity-Post - OnCodeOnBeforeCommit()

### ISSUE THREAD

**Issue by JaniCunha** [microsoft/ALAppExtensions#3450]
Hi, 
I need an event on Codeunit 7324 - Whse.-Activity-Post, inside the Code function but before Commit.
Something like this: 

![image](https://user-images.githubusercontent.com/44140058/61696952-31f8ca80-ad2e-11e9-9dc9-18889e1a864b.png)

Thank You.

**Comment by StanPesotskiy** [comment]
There is OnAfterCode event in COD7324. Can't you use it?:
```
  OnAfterCode(WhseActivLine);

  COMMIT;
  OnAfterPostWhseActivHeader(WhseActivHeader);

  CLEAR(WhseJnlRegisterLine);
END;
```

**Comment by JaniCunha** [comment]
I think so. I didn't see this event in my Docker image. I installed a new one and now I already have this event. I will run some tests to confirm.
Thank you.
