### ISSUE TITLE
[Event Request] Codeunit 6520 - Item Tracing Mgt. - OnAfterRetrieveHistoryData

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#3463]
Hello AL-Team,
please add the following Publisher in function "RetrieveHistoryData":

```
LOCAL RetrieveHistoryData(EntryNo : Integer;VAR SerialNoFilter : Text;VAR LotNoFilter : Text;VAR ItemNoFilter : Text;VAR VariantFilter : Text;VAR TraceMethod : 'Origin->Usage,Usage->Origin';VAR ShowComponents : 'No,Item-tracked only,All') : Boolean
[...]
      ItemNoFilter := ItemNoFilter + "Item No. Filter";
      VariantFilter := VariantFilter + "Variant Filter";
    END;

    // >> New
    OnAfterRetrieveHistoryData(TempTraceHistory);
    // << New
  UNTIL NEXT = 0;
  EXIT(TRUE);
END;

```
Publisher definition currently used by us
IncludeSender: false
GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterRetrieveHistoryData(VAR TempTraceHistory : Record "Item Tracing History Buffer")

**Comment by NKarolak** [comment]
Note: implemented as **OnRetrieveHistoryDataOnAfterTraceHistoryLine**
`local procedure OnRetrieveHistoryDataOnAfterTraceHistoryLine(var TempItemTracingHistoryBuffer: Record "Item Tracing History Buffer" temporary)`
