### ISSUE TITLE
[Event Request] Codeunit 6520 - Item Tracing Mgt. - OnBeforeInsertTraceHistory

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#3464]
Hello AL-Team,
please add the following Publisher in function "UpdateHistory":

```
LOCAL UpdateHistory(SerialNoFilter : Text;LotNoFilter : Text;ItemNoFilter : Text;VariantFilter : Text;TraceMethod : 'Origin->Usage,Usage->Origin';ShowComponents : 'No,Item-tracked only,All') OK : Boolean
[...]
    IF Level = 0 THEN BEGIN
      "Trace Method" := TraceMethod;
      "Show Components" := ShowComponents;
    END;

    // >> New
    OnBeforeInsertTraceHistory(TempTraceHistory);
    // << New

    INSERT;

    LevelCount += 1;
[...]
```
Publisher definition currently used by us
IncludeSender: false
GlobaVarAccess: false
LOCAL [IntegrationEvent] OnBeforeInsertTraceHistory(VAR TempTraceHistory : Record "Item Tracing History Buffer")

**Comment by NKarolak** [comment]
Note: implemented as **OnBeforeItemTracingHistoryBufferInsert**
`local procedure OnBeforeItemTracingHistoryBufferInsert(var ItemTracingHistoryBuffer: Record "Item Tracing History Buffer")`
