### ISSUE TITLE
[Event Request] Page 6520 - Item Tracing - OnAfterInitFilters

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#3467]
Hello AL-Team,
please add the following Publisher in function "InitFilters":

```
[External] InitFilters(VAR ItemTrackingEntry : Record "Item Tracing Buffer")
SerialNoFilter := ItemTrackingEntry.GETFILTER("Serial No.");
LotNoFilter := ItemTrackingEntry.GETFILTER("Lot No.");
ItemNoFilter := ItemTrackingEntry.GETFILTER("Item No.");
VariantFilter := ItemTrackingEntry.GETFILTER("Variant Code");
TraceMethod := TraceMethod::"Usage->Origin";
ShowComponents := ShowComponents::"Item-tracked Only";

// >> New
OnAfterInitFilters(ItemTrackingEntry,TraceMethod,ShowComponents);
// << New
```
Publisher definition currently used by us
IncludeSender: false
GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterInitFilters(VAR ItemTracingBuffer : Record "Item Tracing Buffer";VAR TraceMethod2 : 'Origin->Usage,Usage->Origin';VAR ShowComponents2 : 'No,Item-tracked Only,All')

**Comment by NKarolak** [comment]
Note: implemented as
`local procedure OnAfterInitFilters(var ItemTracingBuffer: Record "Item Tracing Buffer"; var TraceMethod: Option Forward,Backward; var ShowComponents: Option No,"Item-tracked only",All)`
