### ISSUE TITLE
[Event Request] Page 6520 - Item Tracing - OnAfterUpdateTraceText

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#3468]
Hello AL-Team,
please add the following Publisher in function "UpdateTraceText":

```
LOCAL UpdateTraceText()
[...]
IF Overflow THEN
  TraceText := Text003
ELSE
  TraceText := STRSUBSTNO(Text002,SerialNoFilter,LotNoFilter,ItemNoFilter,VariantFilter,
      SELECTSTR(TraceMethod + 1,Text004) ,SELECTSTR(ShowComponents + 1,Text005));

// >> New
OnAfterUpdateTraceText(TraceText,SerialNoFilter,LotNoFilter,ItemNoFilter,VariantFilter,TraceMethod,ShowComponents);
// << New
```
Publisher definition currently used by us
IncludeSender: false
GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterUpdateTraceText(VAR TrText : Text;SerialFilter : Text;LotFilter : Text;ItemFilter : Text;VarFilter : Text;TrMethod : Option;WithComponents : Option)

**Comment by NKarolak** [comment]
Note: implemented as
`local procedure OnAfterUpdateTraceText(var TraceText: Text; SerialNoFilter: Text; LotNoFilter: Text; ItemNoFilter: Text; VariantFilter: Text; TraceMethod: Option Forward,Backward; ShowComponents: Option No,"Item-tracked only",All)  `
