### ISSUE TITLE
Table 36 Sales Header - TestSalesLineFieldsBeforeRecreate

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3472]
The publisher requested in issue #1488 has been implemented incorrectly.
The variable 'Rec' is parsed while it should be 'SalesLine'.

    LOCAL PROCEDURE TestSalesLineFieldsBeforeRecreate@68();
    VAR
      IsHandled@1000 : Boolean;
    BEGIN
      IsHandled := FALSE;
      ///// START
      //OnBeforeTestSalesLineFieldsBeforeRecreate(Rec,IsHandled);
      OnBeforeTestSalesLineFieldsBeforeRecreate(SalesLine,IsHandled);
      ///// END
      IF IsHandled THEN
        EXIT;
      
      SalesLine.TESTFIELD("Job No.",'');
      SalesLine.TESTFIELD("Job Contract Entry No.",0);
      SalesLine.TESTFIELD("Quantity Invoiced",0);

**Comment by NKarolak** [comment]
Note: implemented as
`LOCAL [IntegrationEvent] OnBeforeTestSalesLineFieldsBeforeRecreate(VAR SalesHeader : Record "Sales Header";VAR IsHandled : Boolean;VAR SalesLine : Record "Sales Line")`

**Comment by lv-janpieter** [comment]
Fine with me. Probably they didn't want to make a breaking change.
