### ISSUE TITLE
[Event Request] Table 167 Job OnBeforeCalcRecognizedProfitAmount

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/ALAppExtensions#3477]
Hi,

Need a published event in the table 167 Job: OnBeforeCalcRecognizedProfitAmount

![image](https://user-images.githubusercontent.com/29598240/61772688-2a4f2980-adf3-11e9-907e-098c55c6bcf8.png)

Thanks

**Comment by StanPesotskiy** [comment]
What parameters do you need?

**Comment by JulienDecottignies** [comment]
Hi,

Sorry I only need the Sender. 
The procedure that handle the event looks like this:

`local procedure OnBeforeCalcRecognizedProfitAmount(var Sender: Record Job)`
