### ISSUE TITLE
Expose functions NAV2018 for mailing

### ISSUE THREAD

**Issue by Chingyz** [Microsoft/ALAppExtensions#348]
Can you expose functions necessary to use mailing in AL code(codeunit 397, functions SendEmailToVendor,SendEmailToCust in table 77)?

Thank you in advance.

**Comment by IhorHandziuk** [comment]
Thank you for your request. 
Functions SendEmailToVendor and SendEmailToCust will be external in the future release as well as some functions from codeunit 397 (CreateMessage, CollectAddresses, ValidateEmail, CollectCurrentUserEmailAddresses, FormatTextForHtml). If you would like other procedures from COD397 to be external, please, open a new issue.

**Comment by Chingyz** [comment]
Just to be sure, will this only apply for BC or also NAV2018?

**Comment by Chingyz** [comment]
@IhorHandziuk Unfortunately the functions SendEmailToVendor, SendEmailToCust (Tab77)  and CreateMessage(Cod397) are not external in the new update (CU13).
Can you make these functions and function 'Send' (Cod397) external?

Thank you in advance.
