### ISSUE TITLE
Table 461 Prepayment Inv. Line Buffer

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#3489]
Please Insert a new Publisher in function FillFromGLAcc

...
IF CompressPrepayment THEN
  Description := GLAcc.Name;
// S/NEW
OnAfterFillFromGLAcc((Rec, GLAcc); // << New event
// E/NEW

**Comment by StanPesotskiy** [comment]
Should Rec be passed by ref and GLAcc by value? 
Please don't forget to mention it explicitly. The simplest way would be a copy&paste of your real implementation or at least a screen.

**Comment by ThorstenEngelsGOB** [comment]
By VAR is the most common way for publisher ;O)
I haven't added a hook yet, so in most cases my requests for publishers are just suggestions. Only when the publisher comes we displace our development into the subscriber. This is the default of the development management
