### ISSUE TITLE
Job Planning Line Invoice 1022 - InitFromJobPlanningLine

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/ALAppExtensions#3490]
EventRequest please add an event to InitFromJobPlanningLine in T1022 Job Planning Line Invoice to such that additional fields can be added to the Job Planning Line Invoice record created for this process.

Might be good to add one to InitFromSales too.

**Comment by StanPesotskiy** [comment]
Please provide samples of code where we can clearly see where exactly you need to put this event and what parameters (with/without VAR) there are.

**Comment by GreatScott000** [comment]
The event signature would look like this:
`OnAfterInitFromJobPlanningLine(var JobPlanningLineInvoice: Record "Job Planning Line Invoice"; JobPlanningLine: Record "Job Planning Line")`
It should be called from the InitFromJobPlanningLine function in Job Planning Line Invoice (Table 1022).
