### ISSUE TITLE
Removal or move of COMMIT in function MergeWordLayout in CU 9651 Document Report Mgt.

### ISSUE THREAD

**Issue by plagijat** [microsoft/ALAppExtensions#3496]
Hello,

We want to implement Invoice Preview functionality in our AL solution similar to Posting Preview which is even more user friendly since the user can see how the invoice will look before posting it. 
For this we need removal of the several COMMIT calls which are being indirectly called by reports. One of these is in function MergeWordLayout before `OnAfterMergeWordDocument(ReportID,InStrXmlData,OutTempBlob);`.

Can you please remove this COMMIT or move it to that part of the solution which needs the actual COMMIT to be implemented (RUNMODAL or whatever is the issue).
Another solution would be to implement a publisher function or a function which handles the suppression of COMMIT (like SetSuppressCommit in CU80). But I do not know how this can be implemented since this functionality is triggered by system Codeunit 2000000005 Reporting Triggers.

Also for the complete solution I would ask you to look at the issue [#926](https://github.com/microsoft/ALAppExtensions/issues/926) which we also need to be implemented to able to skip COMMITS during report generation. This could also be done by allowing the users to set the Reports in a Preview mode so that the call for codeunits that increments the number of printed documents can be skipped.

Thanks,
Zoran

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
