### ISSUE TITLE
[Function Expose] Codeunit 9651 Document Report Mgt. - function TryXmlMergeWordDocument

### ISSUE THREAD

**Issue by plagijat** [microsoft/ALAppExtensions#3497]
Hello,

Can you make function TryXmlMergeWordDocument external since we could use it in our app and probably overcome problems created with COMMIT in the same CU in function MergeWordLayout.
Please see [#3496](https://github.com/microsoft/ALAppExtensions/issues/3496).

Thanks,
Zoran

**Comment by RomanZanizdra** [comment]
Hi Zoran. Seems we don't have plans to make mentioned function external and available for AL development.

**Comment by RomanZanizdra** [comment]
You can re-open issue later if you think something else should be done here.
