### ISSUE TITLE
Enum Request : Table 1022 ("Job Planning Line Invoice"), field 4 ("Document Type")

### ISSUE THREAD

**Issue by CSTEENSGAARD** [microsoft/ALAppExtensions#3509]
Please implement field 4 ("Document Type") in Table 1022 ("Job Planning Line Invoice") as an Enum.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
