### ISSUE TITLE
[EventRequest] CU6620 – Function CopyServContractLines

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#3524]
We need a new Publisher „OnAfterCopyServContractLines“ in function CopyServContractLines in CU6620 
![image](https://user-images.githubusercontent.com/40287548/61930476-226fc080-af7e-11e9-9345-8f276b058380.png)
Thanks

**Comment by StanPesotskiy** [comment]
I assume, FromServContractLine should be passed by reference (with VAR) and other params by value, right?

**Comment by AndreBreitenbach** [comment]
At the moment we only need the parameter as “by value”.




MODUS Consult AG
James-Watt-Straße 6
D-33334 Gütersloh
E-Mail contact@modusconsult.de
Internet www.modusconsult.de

Vorstand: Stefan Sagowski, Klaus Wagner
Aufsichtsratsvorsitzender: Dr. Thomas Olemotz

Amts­ge­richt Güters­loh, HRB 7786
USt-ID-Nr. DE257988856

Entdecken Sie unsere Webinare für Business-IT und treffen Sie uns live vor Ort: https://www.modusconsult.de/unternehmen/modus-consult-live
Haben Sie Lust auf eine neue Herausforderung? https://www.modus-karriere.de/

Wir nehmen das Thema Datenschutz sehr ernst. Deswegen informieren wir Sie über die Verarbeitung Ihrer personenbezogenen Daten durch die MODUS Consult AG und die Ihnen nach dem Datenschutzrecht zustehenden Rechte auf https://www.modusconsult.de/datenschutz.

Die 1995 gegründete MODUS Consult AG bietet integrative, ganzheitliche Leistungen aus einer Hand. Von ERP und CRM über DMS und BI bis zu Systemberatung und -technik basieren unsere Lösungen und unser Know-how auf der Erfahrung von über 20 Jahren erfolgreicher Zusammenarbeit mit über 1.000 Kunden. Mit unseren zertifizierten Branchenlösungen auf Basis von Microsoft Dynamics setzen wir als Microsoft Gold Partner höchste Qualitätsansprüche an uns und an die gemeinsam mit unseren Partnern geschaffenen Lösungen.
Die MODUS Consult AG ist ein Unternehmen der Bechtle Grupp


Von: Stan Pesotskiy <notifications@github.com>
Gesendet: Montag, 29. Juli 2019 09:52
An: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
Cc: Breitenbach, André <Andre.Breitenbach@modusconsult.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/ALAppExtensions] [EventRequest] CU6620 – Function CopyServContractLines (#3524)


I assume, FromServContractLine should be passed by reference (with VAR) and other params by value, right?
