### ISSUE TITLE
TempBlob Expose TryGetImageFormatAsTxt()

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#3540]
It would be great if we could you the TryGetImageFormatAsTxt() function in AL 
![image](https://user-images.githubusercontent.com/35929603/61943531-ee0afd00-af9b-11e9-9500-71a46a03f88c.png)

**Comment by RomanZanizdra** [comment]
Hi JulianTillmann.
There are no plans for now to make mentioned function external and available for AL development. Let me know if there is any gap on functions or events you needed for development. I close issue for now, feel free to re-open it.

**Comment by JulianTillmann** [comment]
There is a gap, we would have to handle a Blobl without HASVALUE() ourselves. 

Please reconsider making the try function external or making the external GetImageType() function a Try-function.

**Comment by RomanZanizdra** [comment]
In the next release GetImageType will be like below. It will be working with stream. Why do you need it "try" function? May be you need an event somewhere in the function?
![image](https://user-images.githubusercontent.com/43471583/62108289-5d416380-b2b2-11e9-8ab8-78bec6b27d3a.png)

**Comment by JulianTillmann** [comment]
It would just be nice to use this function without having to handle wether there is Content in the blob or not.

**Comment by RomanZanizdra** [comment]
So what do you expect as "exit" value of the function in the case of empty stream passed as parameter?

**Comment by RomanZanizdra** [comment]
Ping.
Is it ok to have an empty value (' ') on exit in the case of incoming stream is empty?

**Comment by RomanZanizdra** [comment]
I re-open issue and give you an event before analyzing end of stream with Handled variable. You will be able to skip further processing if set Handled to true in your event subscriber and get empty string on exit.

**Comment by RomanZanizdra** [comment]
Hi again JulianTillmann. After some internal discussions I still have a couple of questions to you.
1) From where do you call GetImageType function? Do you call from extension or somehow else?
2) If you call it from your code why can't you check the stream before and just skip the function call.
Waiting for your answers with more information and clarification.

**Comment by JulianTillmann** [comment]
sorry for the delay, lot's of Things to do ;-) 

We're creating an extension in AL 

We're trying to use Blob-Images in RDLC Reports. My Scenario would be: 
- I have a Blob field for an Image
- I have three columns 
  - Blob -> the Image itself
  - NOT Blob.HasValue -> to set the Hide-Value in the RDLC Image field
  - Blob.GetImageType() -> to set the ImageType in the RDLC Image field

So when the Report ist rendered it should use any Image in the correct image type if it exists and if not, the part of the layout doesn't show. 

Would this be possible or do I need to rethink my solution?

**Comment by RomanZanizdra** [comment]
I suggest you to process Blob.HasValue or Stream.EOS on your side, in the extension. It will be easier then to have a subscriber as I suggested initially and more flexible for analysis "exit value" if the blob/stream are empty.

**Comment by RomanZanizdra** [comment]
So, let's close t again.
