### ISSUE TITLE
Table 37 Sales Line - UpdateVATOnLines

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3552]
To handle excise related stuff we need to be able to adjust the Amounts calculated in function UpdateVATOnLines. To make this possible with a minimum footprint we would like to request a publisher which is called on 2 different places. 

                IF QtyType = QtyType::General THEN
                  IF SalesHeader."Prices Including VAT" THEN BEGIN
                    IF (VATAmountLine.CalcLineAmount = 0) OR ("Line Amount" = 0) THEN BEGIN
                      VATAmount := 0;
                      NewAmountIncludingVAT := 0;
                    END ELSE BEGIN
                      VATAmount :=
                        TempVATAmountLineRemainder."VAT Amount" +
                        VATAmountLine."VAT Amount" * CalcLineAmount / VATAmountLine.CalcLineAmount;
                      NewAmountIncludingVAT :=
                        TempVATAmountLineRemainder."Amount Including VAT" +
                        VATAmountLine."Amount Including VAT" * CalcLineAmount / VATAmountLine.CalcLineAmount;
                    END;
                    ///// START
                    UpdateVATOnLinesOnAdjustAmounts(VAR Rec, SalesHeader, TempVATAmountLineRemainder, VATAmountLine, VAR VATAmount, VAR NewAmountIncludingVAT);
		        ///// END
                    NewAmount :=
                      ROUND(NewAmountIncludingVAT,Currency."Amount Rounding Precision") -
                      ROUND(VATAmount,Currency."Amount Rounding Precision");
                    NewVATBaseAmount :=
                      ROUND(
                        NewAmount * (1 - SalesHeader."VAT Base Discount %" / 100),Currency."Amount Rounding Precision");
                  END ELSE BEGIN
                    IF "VAT Calculation Type" = "VAT Calculation Type"::"Full VAT" THEN BEGIN
                      VATAmount := CalcLineAmount;
                      NewAmount := 0;
                      NewVATBaseAmount := 0;
                    END ELSE BEGIN
                      NewAmount := CalcLineAmount;
                      NewVATBaseAmount :=
                        ROUND(
                          NewAmount * (1 - SalesHeader."VAT Base Discount %" / 100),Currency."Amount Rounding Precision");
                      IF VATAmountLine."VAT Base" = 0 THEN
                        VATAmount := 0
                      ELSE
                        VATAmount :=
                          TempVATAmountLineRemainder."VAT Amount" +
                          VATAmountLine."VAT Amount" * NewAmount / VATAmountLine."VAT Base";
                    END;
		        ///// START
                    UpdateVATOnLinesOnAdjustAmounts(VAR Rec, SalesHeader, TempVATAmountLineRemainder, VATAmountLine, VAR VATAmount, VAR NewAmountIncludingVAT);
		        ///// END
                    NewAmountIncludingVAT := NewAmount + ROUND(VATAmount,Currency."Amount Rounding Precision");
                  END
                ELSE BEGIN
                  IF VATAmountLine.CalcLineAmount = 0 THEN
                    VATDifference := 0
                  ELSE
                    VATDifference :=
                      TempVATAmountLineRemainder."VAT Difference" +
                      VATAmountLine."VAT Difference" * (LineAmountToInvoice - InvDiscAmount) / VATAmountLine.CalcLineAmount;
                  IF LineAmountToInvoice = 0 THEN
                    "VAT Difference" := 0
                  ELSE
                    "VAT Difference" := ROUND(VATDifference,Currency."Amount Rounding Precision");
                END;

Many thanks.

**Comment by StanPesotskiy** [comment]
I think there might be a problem in the second call. You return a proper value to NewAmountIncludingVAT, but in the next line it will be overwritten:
```
                UpdateVATOnLinesOnAdjustAmounts(VAR Rec, SalesHeader, TempVATAmountLineRemainder, VATAmountLine, VAR VATAmount, VAR NewAmountIncludingVAT);
	        ///// END
                NewAmountIncludingVAT := NewAmount + ROUND(VATAmount,Currency."Amount Rounding Precision");

```

**Comment by lv-janpieter** [comment]
You are right. That would falsy imply we could change this variable. We only change NewAmountIncludingVAT in the first line. Maybe it is better to create 2 different publishers. The second publisher is without the NewAmountIncludingVAT.
