### ISSUE TITLE
[Event Request] codeunit 1220 "SEPA CT-Export File" - OnBeforeBLOBExport

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#3557]
Can you add event OnBeforeBLOBExport in codeunit 1220 "SEPA CT-Export File"?

![image](https://user-images.githubusercontent.com/46031720/61997561-758f6380-b0a3-11e9-8702-913f9b7300f6.png)

![image](https://user-images.githubusercontent.com/46031720/61997583-e2a2f900-b0a3-11e9-983d-9c9d3a247631.png)

**Comment by StanPesotskiy** [comment]
What params should be passed by reference?

**Comment by auzhhv** [comment]
> What params should be passed by reference?

FileCreated and IsHandled :)
