### ISSUE TITLE
[Event Request] codeunit 1221 "SEPA CT-Fill Export Buffer" - OnBefore/OnAfterUpdateGenJnlFields

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#3558]
Can you add events in function UpdateGenJnlFields in codeunit 1221 "SEPA CT-Fill Export Buffer"?

![image](https://user-images.githubusercontent.com/46031720/61997630-88eefe80-b0a4-11e9-8e7a-bd455f152862.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
