### ISSUE TITLE
Event Request Table 5065 – Interaction Log Entry - SetCanceledCheckmark

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#3561]
Hello,
based on my phone call with jared hall last week, here is a better definition for this function. I also added an description of the event(s) needed. 
Additionally i developed the events by my own. Take a look at the C/AL  object i'va added.
Here you can see the exact publishers, parameters, function name etc.
My Code is documented like:
// A/ Event Request
OnBeforeSomething...
// E/ Event Request

Requested Event in CU 5052 - Function "ProcessDeliverySorter"
- OnBeforeSetCanceledCheckmark(Rec,CanceledCheckmark,RemoveUniqueAttachment,Handled); 

![tab5065canceledcheckmark](https://user-images.githubusercontent.com/26924867/62031291-497cfb00-b1e7-11e9-994d-59c28bb8e766.png)

**Comment by StanPesotskiy** [comment]
If I understand correctly the requested event should look like:
```
SetCanceledCheckmark(CanceledCheckmark : Boolean;RemoveUniqueAttachment : Boolean)
OnBeforeSetCanceledCheckmark(Rec,CanceledCheckmark,RemoveUniqueAttachment,IsHandled);
IF IsHandled THEN
  EXIT;

IF Canceled AND NOT CanceledCheckmark THEN BEGIN
```
Its declaration: 
`LOCAL [IntegrationEvent] OnBeforeSetCanceledCheckmark(VAR InteractionLogEntry : Record "Interaction Log Entry";CanceledCheckmark : Boolean;RemoveUniqueAttachment : Boolean;VAR IsHandled : Boolean)`

Put explicitly if you want to set property **IncludeSender** to true.

Please follow this approach and we will be adding new events fast and correct.
