### ISSUE TITLE
[Event Request / Application Refactoring] COD 170 - Automatic insert recurring purchase lines

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#3563]
Customers are complaining about the 'refactored' insert of recurring purchase lines. They have to confirm (= extra click) the notification, where in the past lines used to be insert **automatically**. See https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=78120765612032

To (temporarily) workaround the notification, we'd like to be able to overrule the 'CheckShowPurchRecurringLinesNotification' function in COD 170 via an event publisher with VAR access to PurchaseHeader.

In addition, please put functions CanGetPurchRecurringLines / GetPurchRecurringLines global, so we can write following code in our subscribers:

```
IF CanGetPurchRecurringLines(PurchaseHeader) THEN
  GetPurchRecurringLines(Rec); 
```

Even better would be **not** to provide any publishers at all and fix the behavior as it used to be in previous versions. See https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=78120765612032

PS: Please provide the same for Sales as well.

**Comment by fvet** [comment]
@StanPesotskiy / @jobulsin Can you please comment how this has been solved? By means of an event or did you change the application behavior back to normal?

**Comment by StanPesotskiy** [comment]
@fvet we have added events: 
- OnBeforeShowGetSalesRecurringLinesNotification(SalesHeader,IsHandled);
- OnBeforeShowGetPurchRecurringLinesNotification(PurchHeader,IsHandled);

and made CanGetPurchRecurringLines / GetPurchRecurringLines external.
