### ISSUE TITLE
[Event Request] Identity Management - ValidateKeyStrength

### ISSUE THREAD

**Issue by SKeiler** [Microsoft/ALAppExtensions#357]
Hello,

could there inserted an event in the procedure ValidateKeyStrength in the "Identity Management"-Codeunit (CU9801) to add own password rules. 

The Event should influence the return parameter of the ValidateKeyStrength-function.

**Comment by AlexanderYakunin** [comment]
Implementation of this ask decrease level of security of user authentication. Can you please explain in details why do you need this as we need to raise Security Risk request for this ask?

**Comment by SKeiler** [comment]
In which case the Event request would decrease the level of security? The Event should be run additional to the existing security checks, not as replacement?!

For some of our customers we host our vertical in our own cloud environment (like Azure, but local hosted). But our security rules are stronger than the NAV-defaults (for example password length with 14 chars insteadt of only 8).

**Comment by AlexanderYakunin** [comment]
Can you please provide code how you would like to implement this event?

**Comment by SKeiler** [comment]
Something like this. The new KeyTestPass-variable is bool.

![keypass](https://user-images.githubusercontent.com/45033081/49232978-43831000-f3f5-11e8-80dd-2bb01f4c1ba9.jpg)

Instead of the new variable you could also add a name vor the Return Value and use this as parameter.

**Comment by AlexanderYakunin** [comment]
How you are going to calculate KeyTestPass in event without passing parameter Key?

**Comment by SKeiler** [comment]
Ohh sorry, I only build a fast example without test it. Yes, sure, the Key-Parameter has to be accessible in the event, too.

**Comment by JesperSchulz** [comment]
The request was rejected due to security concerns. We cannot pass key values around as parameters. Closing issue. Please reconsider and open a new issue, if you find a secure solution you'd like us to proceed with.
