### ISSUE TITLE
OIOUBL - Incorrect app initialization (ref. to removed field)

### ISSUE THREAD

**Issue by Koubek** [microsoft/ALAppExtensions#3570]
**Description**

We have detected some situations when the extension tries to reference the field coming from *C/SIDE* despite the fact that the field was *removed* (`ObsoleteState=Removed`).
The error is:

`'Field OIOUBL Code (13600) of table Payment Terms (3) is obsoleted, reason: Moved to OIOUBL extension, the same table, same field name prefixed with OIOUBL-.'.`

**Scenarios**

- The easiest way how to get the error is to create a new company and then try to open it. I used the following docker image:
`mcr.microsoft.com/businesscentral/onprem:1904-rtm-dk`

![image](https://user-images.githubusercontent.com/24265973/62050824-5105c980-b212-11e9-825c-9330fe943890.png)

- The same error also appears in situations when you try to install the extension in a database that was previously prepared (companies created).

- Next situation is when you run somehow extension, you have also companies created but without data in the following table:
`OIOUBL-Profile`
In this case, Codeunit 2 (e.g. during the data upgrade) will trigger the same code and the same error will appear.

**Possible Reason**

I think the problem is here:
https://github.com/microsoft/ALAppExtensions/blob/aca4ea6c432a1a4179b0c6647fc5bd6830563685/AddOns/OIOUBL/app/src/upgrade/COD13623.MigrateToExtensionV2.al#L59

You reference *C/SIDE* field that was marked as  *Removed* in a Codeunit that isn't *Upgrade* Codeunit type. And according to this article this isn't possible: [devenv-obsoletestate-property](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-obsoletestate-property).

This code is being executed only during the scenarios I have described so I think this is the reason. Maybe I am wrong. But the error exists.

**Comment by StanPesotskiy** [comment]
Please report this issue via the standard support channel.
