### ISSUE TITLE
[EventRequest] Codeunit 22 OnBeforeInsertCapLedgEntry / OnAfterInsertCapLedgEntry

### ISSUE THREAD

**Issue by simplyQQ** [Microsoft/ALAppExtensions#358]
Currently it's not possible to add any new information to capacity ledger entries.

Please add those events.

**Comment by AlexanderYakunin** [comment]
There are both events available in BC COD22 InsertCapLedgEntry procedure:

        OnBeforeInsertCapLedgEntry(CapLedgEntry,ItemJnlLine);
        CapLedgEntry.INSERT;
        OnAfterInsertCapLedgEntry(CapLedgEntry,ItemJnlLine);

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
