### ISSUE TITLE
New key to be added in T337 Reservation Entry

### ISSUE THREAD

**Issue by RishtaCader** [microsoft/ALAppExtensions#3584]
Hello Team,

We need a new key in table 337 Reservation Entry :
"Item No.","Location Code","Expiration Date","Lot No.","Serial No."

Thank you.

**Comment by AlexanderYakunin** [comment]
Why you cannot use any of existing keys?

**Comment by RishtaCader** [comment]
Hello,

We are doing an upgrade for a company, and the new key created by a third party is being used in some reports. The need of the Expiration Date in a key is necessary as this is used for some calculation. There is no existing key involving the Expiration Date.

Thank you.

**Comment by AlexanderYakunin** [comment]
Which version do you use? Do you know what you can calculate totals without adding fields to key?

**Comment by RishtaCader** [comment]
Hello,

We have a custom report that we need to sort by Expiration Date. We are migrating from Nav2013R2 to Business Central.

Thank you.

**Comment by AlexanderYakunin** [comment]
Based on this information I assume you works OnPrem and can do you customization yourself. Or you want to use cloud version?

**Comment by RishtaCader** [comment]
Hello,

We are using Business Central Cloud. We need to sort the report using the following key:
"Item No.","Location Code","Expiration Date","Lot No.","Serial No."

Thank you.

**Comment by AlexanderYakunin** [comment]
We cannot add keys this way as it will affect all cloud customer. if you only need it for one report, you can reach needed results using temporary table to copy data from Reservation Entry first and then sort it using key in this custom table.

**Comment by RishtaCader** [comment]
Hello,

Thank you for the solution. We will work towards it.
