### ISSUE TITLE
Field "External Document No." missing on page "Recurring General Journal"

### ISSUE THREAD

**Issue by bvbeek** [Microsoft/ALAppExtensions#359]
Please can you add this field?

**Comment by JesperSchulz** [comment]
This repository is for questions and issues related to application extensibility. For functional improvement requests, please visit [Business Central - Ideas](http://aka.ms/bcideas).

But as this field already is on the source table, you can add the field yourself by using the designer (cogwheel in the upper right corner -> design):

![image](https://user-images.githubusercontent.com/19796701/48493377-fb2bf580-e82b-11e8-84d4-42d83ecaa2e5.png)

If you believe we have a bug in the base product, we suggest that you open a support case or file a bug in Collaborate. 

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 

- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.

**Comment by bvbeek** [comment]
@JesperSchulz thank you for your answer. I know that's possible but we want to prevent our customer to modify pages to create page-extensions. Why does Microsoft not add all these basic fields on the page? There are more fields wich are not on the page by default, and every partner/developer will add this fields and had to merge it again into the next version.

**Comment by JesperSchulz** [comment]
Thanks for getting back to me on this one. I will have one of our program managers confirm, if these fields indeed are added by every partner and that every customer needs those to be added and if so, we will revisit your request! Of course we don't want every user to have to add basic fields. But we also need to be careful with flooding cards and lists with fields, only a subset of our users are interested in. We'll look into it once more. Thanks for reporting!

**Comment by JesperSchulz** [comment]
The feedback I received was to ask you to create a single entry on our ideas site http://aka.ms/bcideas. The advantage of the ideas page is, that other partners can vote for your suggestion and if it receives sufficient votes, we will process it. This repo is mainly for extensibility issues and is hence the wrong forum to request such change. But please go right ahead and request the fields to be added on bcideas! We'll take it from there...
