### ISSUE TITLE
How to Export payments to Nordea Corporate Access in SEPA format to domestic banks and FIK creditors?

### ISSUE THREAD

**Issue by AndyDegard** [Microsoft/ALAppExtensions#360]
In Denmark Nordea is shutting down the Unitel and other older formats for importing payments. Only SEPA format is usable from january 1.st.

How can NAVDK Export payments in SEPA formatted file with payments to domestic bank accounts and to FIK creditor?

Please help if someone knows how to do this.

Also where should I put this request to make someone in Business Central team at Microsoft work on this? I was sent to Github from Community/DynamicsBusinessCentral.
Where should a customer direct this type of question?

Thank you

Anders

**Comment by JesperSchulz** [comment]
This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central. Hence this is not the right place to post your question either. I'm a little puzzled as to why you were sent here, as this is clearly a question for one of the following:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

If this is a feature request, you can post your idea to [Business Central - Ideas](http://aka.ms/bcideas). After closing this issue, I will send it to one of our program managers to look into, if this is something that needs attention as a regulatory compliance feature. I'm afraid that's the best I can do for you here.

**Comment by JesperSchulz** [comment]
I just received confirmation that you should post the idea to [Business Central - Ideas](http://aka.ms/bcideas) for further processing. Thanks for reporting!

**Comment by AndyDegard** [comment]
Thank you for the replies. The problem is not really an idea, but I tried.
I cannot post this problem to Business Central - Ideas, because that requires installing some app that I do not want on my computer. The app requires access to all sorts of data on my profile that I should not need to give up.
Is there somewhere else I can direct this problem to.
Business Central support. Where is that?
