### ISSUE TITLE
I have seen a new event which gives acces to variable CuotaDeducibleValue has been created.

### ISSUE THREAD

**Issue by MikelIG11** [microsoft/ALAppExtensions#3602]
I have seen a new event which gives acces to variable CuotaDeducibleValue has been created.

[EventSubscriber(ObjectType::Codeunit, Codeunit::"SII XML Creator", 'OnAfterCalculateCuotaDeducibleValue', '', false, false)]
 
However, to Spanish Tax Agency requeriments we still need to have access to change CuotaSoportada value, which shows VATAmountDiff value.

Thank  you.

Something like this:

Codeunit 10750 SII XML Creator – procedure HandleReplacementPurchCorrectiveInvoice()

 

Name: OnBeforeFillCorrectiveCuotaIVA

Parameters (all by reference except AmountNodeName):
-	TempVATEntryPerPercent
-	AmountNodeName
-	VATAmountDiff

LOCAL [IntegrationEvent] OnBeforeFillCorrectiveCuotaIVA (VAR TempVATEntryPerPercent : TEMPORARY Record "VAT Entry"; AmountNodeName : Text;VAR VATAmountDiff : Decimal)
![event](https://user-images.githubusercontent.com/53006842/61379762-71479700-a8a8-11e9-84c4-377d5b085d7f.jpg)

_Originally posted by @MikelIG11 in https://github.com/microsoft/ALAppExtensions/issues/2102#issuecomment-512257020_

**Comment by AlexanderYakunin** [comment]
You already have this:

    // fill XML
    XMLDOMManagement.AddElementWithPrefix(XMLNode,'DetalleIVA','','sii',SiiTxt,XMLNode);
    XMLDOMManagement.AddElementWithPrefix(
      XMLNode,'TipoImpositivo',FormatNumber(TempVATEntryPerPercent."VAT %"),'sii',SiiTxt,TempXMLNode);
    XMLDOMManagement.AddElementWithPrefix(XMLNode,'BaseImponible',FormatNumber(BaseAmountDiff),'sii',SiiTxt,TempXMLNode);
    **OnBeforeAddVATAmountPurchDiffElement(TempVATEntryPerPercent,VATAmountDiff);**
   XMLDOMManagement.AddElementWithPrefix(XMLNode,'CuotaSoportada',FormatNumber(VATAmountDiff),'sii',SiiTxt,TempXMLNode);

**Comment by MikelIG11** [comment]
Thank you Alexander, you are right.
