### ISSUE TITLE
[Event Request] Table 77 Report Selections: OnBeforeGetEmailBodyVendorText

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3620]
This request #2232 is marked as 'Ships in future update', however is still missing. We also have this requirement. Can you look into this? We need the handled pattern before the 'FindEmailBodyUsageVendor' function.

_Originally posted by @lv-janpieter in https://github.com/microsoft/ALAppExtensions/issues/2232#issuecomment-517626793_

**Comment by AlexanderYakunin** [comment]
This is already done for master (=15.X). We have no option to do the same for 14.X.
