### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment: New Event OnPostSourceDocumentOnBeforePrintSalesInvoice()

### ISSUE THREAD

**Issue by Cosimo2001** [microsoft/ALAppExtensions#3624]
Please add missing event in Codeunit 5763 "Whse.-Post Shipment", before printing invoice:

IF Print THEN
  IF "Source Document" = "Source Document"::"Sales Order" THEN BEGIN
    IsHandled := FALSE;
    OnPostSourceDocumentOnBeforePrintSalesShipment(SalesHeader,IsHandled);
    IF NOT IsHandled THEN BEGIN
      SalesShptHeader."No." := SalesHeader."Last Shipping No.";
      SalesShptHeader.SETRECFILTER;
      SalesShptHeader.PrintRecords(FALSE);
    END;
    IF Invoice THEN BEGIN
      **OnPostSourceDocumentOnBeforePrintSalesInvoice(SalesHeader,IsHandled); // NEW EVENT**
      **IF NOT IsHandled THEN BEGIN                                                                         // NEW EVENT**
        SalesInvHeader."No." := SalesHeader."Last Posting No.";
        SalesInvHeader.SETRECFILTER;
        SalesInvHeader.PrintRecords(FALSE);
      END;
    END;

**Comment by AlexanderYakunin** [comment]
This is already implemented:
        IF Print THEN
          IF "Source Document" = "Source Document"::"Sales Order" THEN BEGIN
            IsHandled := FALSE;
            OnPostSourceDocumentOnBeforePrintSalesShipment(SalesHeader,IsHandled);
            IF NOT IsHandled THEN BEGIN
              SalesShptHeader."No." := SalesHeader."Last Shipping No.";
              SalesShptHeader.SETRECFILTER;
              SalesShptHeader.PrintRecords(FALSE);
            END;
            IF Invoice THEN BEGIN
              IsHandled := FALSE;
              OnPostSourceDocumentOnBeforePrintSalesInvoice(SalesHeader,IsHandled);
              IF NOT IsHandled THEN BEGIN
                SalesInvHeader."No." := SalesHeader."Last Posting No.";
                SalesInvHeader.SETRECFILTER;
                SalesInvHeader.PrintRecords(FALSE);
              END;
            END;
          END;
