### ISSUE TITLE
[Event Request] Page 498 - Reservation - OnAfterCaseOfUpdateReservMgt

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#3625]
Although [this very old Event Request](https://github.com/microsoft/AL/issues/2239) was confirmed to be shipped already spring 2018, the event was never shipped, even not in BC 15.

Therefore, we request again:
In **page 498 Reservation**, function **UpdateReservMgt**, please add the following event:
```
[...]
  DATABASE::"Service Line":
    ReservMgt.SetServLine(ServiceLine);
  DATABASE::"Job Planning Line":
    ReservMgt.SetJobPlanningLine(JobPlanningLine);
END;

// >> NEW
OnAfterCaseOfUpdateReservMgt(ReservEntry,ReservMgt,JobJnlLine);
// << NEW
[...]
```

IncludeSender: false
**GlobaVarAccess: true**
`LOCAL [IntegrationEvent] OnAfterCaseOfUpdateReservMgt(VAR ReservEntry : Record "Reservation Entry";VAR ReservMgt : Codeunit "Reservation Management";VAR JobJnlLine : Record "Job Journal Line")`

**Comment by AlexanderYakunin** [comment]
Well, you already have this event
  DATABASE::"Job Planning Line":
    ReservMgt.SetJobPlanningLine(JobPlanningLine);
  ELSE
    OnUpdateReservMgt(ReservEntry,ReservMgt);
END;

We cannot implement your ask exectly as described as JobJnlLine is your variable, we don;t have it in W1.

**Comment by NKarolak** [comment]
@AlexanderYakunin 
Oops, of course you are right about JobJnlLine.
Please keep this issue open; I need to investigate about how to replace the request. If a replacement is not possible, I will close the issue myself, thanks.

**Comment by NKarolak** [comment]
@AlexanderYakunin Why was the case set to "ships-in-future-update" and closed despite having asked to keep it open? What does it actually mean? Will you really consider it, just without parameter JobJnlLine?

**Comment by AlexanderYakunin** [comment]
Hi Natalie! Because we already have OnUpdateReservMgt(ReservEntry,ReservMgt) event for this CASE so the issue is already fixed (based on another request). You can process other tables in your subscriber code. We resolve such cases as Fixed to deliver right message to all people asked for the same.

**Comment by AlexanderYakunin** [comment]
When you will have corrected ask for same place, simply open new request (and add reference to this one if needed).

**Comment by NKarolak** [comment]
But OnUpdateReservMgt does not have GlobaVarAccess = true. Even though I had highlighted GlobVarAccess in my request, it easily gets overlooked. So my request is not the same. Do I still need to open a new request, or can you already tell me that GlobaVarAccess = true won't be accepted anyway?

**Comment by AlexanderYakunin** [comment]
No, it is not overlooked. We do not add GlobalVarAccess anymore as this property is discontinued for next major release in AL. We are removing this property everywhere and ready to immediately respond to partner requests for adding additional events/parameters to mitigate this issue for you.
