### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - ExchangeAmtLCYToFCY2

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3626]
Issue 2949 'Ships in future update' however it isn't changed in CU2 or the daily build. I will issue a new ticket. Can you have a look at this? 

Many thanks.

_Originally posted by @lv-janpieter in https://github.com/microsoft/ALAppExtensions/issues/2949#issuecomment-517731410_

**Comment by AlexanderYakunin** [comment]
We do not implement requests for external into CU's, we can only do it for master.

**Comment by lv-janpieter** [comment]
@AlexanderYakunin 
What does this mean? That this request will not be shipped?

**Comment by AlexanderYakunin** [comment]
This is under investigation, if done it will be shipped in next major update, not in CU's.

**Comment by lv-janpieter** [comment]
Ok thanks. I don't understand why this particular issue is more complex than all other external requests. I must assume you have good reasons. However we will find a way arround.
