### ISSUE TITLE
[EventRequest] Codeunit 99000774 - Function CalculateRoutingLine

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#3640]
In BC14.3 the requested Publishers from issue https://github.com/microsoft/ALAppExtensions/issues/2693 with the "Handled-Pattern" is available now, 
but the 2 requested Publishers "OnBeforeCalcCostInclSetup" and "OnAfterCalcCostInclSetup" are still missing! 
Can you please give me an update what happened here with the missing requests?
![image](https://user-images.githubusercontent.com/40287548/62465464-36da6700-b78f-11e9-86b7-4ac0b29a9e57.png)

**Comment by AlexanderYakunin** [comment]
We will add it based on this request. We cannot reliably track additional comments, please always create new requests and close old one, if you want to change you requirements.

**Comment by AndreBreitenbach** [comment]
Ok, I'll keep that in mind! Thanks
