### ISSUE TITLE
[Event Request] Codeunit 5836 - 2 missing Events

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#3641]
Request 1 is now available in 14.3 but Requests 2 and 3 for filtering are still missing in BC14.3!
Could you please give us any Infos why?? See https://github.com/microsoft/ALAppExtensions/issues/3052 for Details.

Function CalcActTimeAndQtyBase
![image](https://user-images.githubusercontent.com/40287548/62465564-7acd6c00-b78f-11e9-9979-265df23a02b3.png)
The Event needs the following parameters:
![image](https://user-images.githubusercontent.com/40287548/62465673-c122cb00-b78f-11e9-8420-cbc903f92c2f.png)

Function CalcActOperOutputAndScrap
![image](https://user-images.githubusercontent.com/40287548/62465621-9fc1df00-b78f-11e9-8be3-b9d65ed91f6e.png)
The Event needs the following parameters:
![image](https://user-images.githubusercontent.com/40287548/62465735-e6afd480-b78f-11e9-85ff-504eac45354e.png)

Thanks

**Comment by AlexanderYakunin** [comment]
1. Event available
  SetFilterByProdOrderRoutingLine(
    ProdOrderLine."Prod. Order No.",ProdOrderLine."Line No.",
    ProdOrderLine."Routing No.",ProdOrderLine."Routing Reference No.");
  SETRANGE("Operation No.",OperationNo);
  OnCalcActTimeAndQtyBaseOnAfterFilterCapLedgEntry(CapLedgEntry);

2. Event also available
  SetFilterByProdOrderRoutingLine(
    ProdOrderLine."Prod. Order No.",ProdOrderLine."Line No.",
    ProdOrderRtngLine."Routing No.",ProdOrderRtngLine."Routing Reference No.");
  SETRANGE("Last Output Line",TRUE);
  OnCalcActOperOutputAndScrapOnAfterFilterCapLedgEntry(CapLedgEntry);
  CALCSUMS("Output Quantity","Scrap Quantity");

**Comment by AndreBreitenbach** [comment]
Sorry, but both Events are not available in 14.3? Perhaps in InsiderPreview?
