### ISSUE TITLE
Posting Group filter on Customer and Vendor

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#3646]
Hi,

Is it possible to add Customer Posting Group Filter (FlowFilter) on table Customer and Vendor Posting Group Filter(FlowFilter) on table Vendor. It should be applied on all FlowFields that are related to Detailed entries?
That fields are: Balance, Balance (LCY), Net Change, Net Change (LCY), Balance Due, Balance Due (LCY), Debit Amount, Credit Amount, Debit Amount (LCY), Credit Amount (LCY).

Tables Detailed Cust. Ledg. Entry and Detailed Vendor Ledg. Entry should have new field Customer Posting Group or Vendor Posting Group.

This is necessary because of cases where posting groups are changed, and in standard NAV we don't have correct values on Customer and Vendor Cards.

Thanks in advance.

**Comment by jelicastakic** [comment]
@AlexanderYakunin 
Can you give me information on whether this will be delivered?

**Comment by AlexanderYakunin** [comment]
@ikoletic - can you help guide partner to Idea site for submitting this kind of suggestions?

**Comment by ikoletic** [comment]
Hi all

This doesn't sound like extensibility request but is more a feature request. I'd kindly ask you to record product suggestions and feature requests on https://aka.ms/bcideas so community and other partners can chip in / vote for suggestions.
