### ISSUE TITLE
Question Regarding System Apps Deployment

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/ALAppExtensions#3650]
Hey Guys, 
I just a quick question regarding System app. We see that you are splitting into multiple tiny modules. I believe you are developing and maintaining them indidvidually. Will you group them into one app in the end? Or deploy as separate apps?

Best Regards, 
Gintautas

**Comment by AlexanderYakunin** [comment]
Yes, this is one System app.

**Comment by gintuoklis** [comment]
If you are developing it as and app, how do ensure that these modules are not dependent on each other? Are you risking of building another monolith design?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help to answer this question?

**Comment by gintuoklis** [comment]
I could clarify my question. Do you maintain each module separately and combine them under one System app. For e.g. using git submodules functionality?

**Comment by gintuoklis** [comment]
hey guys, 
I know you are busy,  but could you please tell us more about development process? ping @JesperSchulz , @AlexanderYakunin

**Comment by mazhelez** [comment]
Hi, @gintuoklis 

Thanks for paying attention to our work.

To answer your question - yes, we indeed develop separate system modules. However, due to lack of capability for wrapping them into groups or bundles, we build them as one single app - _System Application_.

As for the development process, the current mode of introducing no breaking changes somehow ties our hands, but we are nevertheless convinced that modularizing the "monolith" is the way to go.

**Comment by gintuoklis** [comment]
Hi @mazhelez,
Thanks for the reply. I am asking this because we are in process of designing our development process for AL. One of the decisions is where to store all those extensions. In single repo, or seperate repos. Would it be possible to have a contact with you, so you could tell more about your development process. How did you setup your build & deployment pipelines and etc...

Best Regards, 
Gintautas

**Comment by mazhelez** [comment]
@gintuoklis 

You're asking me to explain the work of several teams around here 😃
Besides, I don't see how your development process should be related to ours.

In any case, one repo or multiple repos, the choice is yours and both approaches have pros and cons. While my vote would go for separate repos for _System Application_ and _Base Application_, it depends heavily on your resources and willingness to support that infrastructure.
