### ISSUE TITLE
[Event Request] Table 37 Sales Line OnValidateNoOnAfterInitHeaderDefaults

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#3658]
Dear,

I need an Integration Event in Table Sales Line 

![OnValidateNoOnAfterInitHeaderDefaults](https://user-images.githubusercontent.com/45877379/62599987-526a7c80-b90b-11e9-9d64-aeff94524b55.jpg)

Thanks & Regards

Ashwini Tripathi

**Comment by SirBETE** [comment]
There's already an `OnAfterInitHeaderDefaults` in `InitHeaderDefaults`.

**Comment by ashwinitripathi** [comment]
Please check the Parameter I request is different as need to restore values from old lines due to Overwrite from Header. Reason why TempSalesLine is requested as additional Parameter.

**Comment by SirBETE** [comment]
Oh yes, sorry ... :)
