### ISSUE TITLE
[Event Request] Report 5753 - Get Source Documents - OnBeforeWarehouseRequestOnAfterGetRecord

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#3682]
Hi AL-team,

additional parameters were requested in ticket #1885. It looks like the parameter OldWhseHeaderCreated has been overlooked. Can you customize the event as follows?

`LOCAL [IntegrationEvent] OnBeforeWarehouseRequestOnAfterGetRecord(VAR WarehouseRequest : Record "Warehouse Request";VAR WhseHeaderCreated : Boolean;VAR SkipRecord : Boolean;VAR BreakReport : Boolean;OldWhseHeaderCreated : Boolean)`

**Comment by AlexanderYakunin** [comment]
We don't have OldWhseHeaderCreated variable in this report.
