### ISSUE TITLE
[Event Request] Codeunit 80 - Sales-Post

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/ALAppExtensions#369]
Hello, we need a modification on standard publsiher "OnAfterFinalizePostingOnBeforeCommit". We need to have access to global variables "GenJnlLineDocNo", "GenJnlLineExtDocNo", "GenJnlLineDocType" and "SrcCode"
Is possible to modify event property GlobalVarAccess to YES ? 

Some days ago I requested the same modification but in C90 https://github.com/Microsoft/ALAppExtensions/issues/161

Thanks,

**Comment by InnovaACAdmin** [comment]
In request #161 I made a new commentary. I don´t know if you are advised about messages written on closed requests.

**Comment by JesperSchulz** [comment]
Usually, closed issues aren't revisited. It's always better to create a new issue (or reopen the issue), if you have further questions.

**Comment by AlexanderYakunin** [comment]
Already done
