### ISSUE TITLE
[Event Change] Report 5753 - Get Source Documents - Sales Line.OnAfterGetRecord: OnSalesLineOnAfterGetRecordOnBeforeCreateShptHeader

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#3693]
Hi AL-team, 

can you pass the parameter WarehouseRequest in publisher OnSalesLineOnAfterGetRecordOnBeforeCreateShptHeader by var?

```
    [Integration]
    LOCAL PROCEDURE OnSalesLineOnAfterGetRecordOnBeforeCreateShptHeader@47(SalesLine@1000 : Record 37;VAR WarehouseRequest@1001 : Record 5765;WarehouseShipmentHeader@1002 : Record 7320;VAR WhseHeaderCreated@1003 : Boolean;VAR OneHeaderCreated@1004 : Boolean);
    BEGIN
    END;
```

**Comment by bcmako** [comment]
Hi,

could you please pass the parameter "WarehouseShipmentHeader" by var, too?

**Comment by NKarolak** [comment]
@bcmako Microsoft does not read our comments after the issue has been processed. You need to create a new GitHub issue for a publisher update.

**Comment by bcmako** [comment]
@NKarolak Thank you!
