### ISSUE TITLE
 [Event Request] Table 5965 Service Contract Header - Next Invoice Date - OnValidate

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3704]
For our case the validation of Next Invoice Date is too strict. To allow our case we require the following publisher called in 2 places:

    Next Invoice Date - Onvalidate

      IF "Next Invoice Date" = 0D THEN BEGIN
        "Next Invoice Period Start" := 0D;
        "Next Invoice Period End" := 0D;
        EXIT;
      END;
      IF "Last Invoice Date" <> 0D THEN
        IF "Last Invoice Date" > "Next Invoice Date" THEN BEGIN
          ServLedgEntry.SETRANGE(Type,ServLedgEntry.Type::"Service Contract");
          ServLedgEntry.SETRANGE("No.","Contract No.");
          IF NOT ServLedgEntry.ISEMPTY THEN
            ERROR(Text023,FIELDCAPTION("Next Invoice Date"),FIELDCAPTION("Last Invoice Date"));
          "Last Invoice Date" := 0D;
        END;

      IF "Next Invoice Date" < "Starting Date" THEN
        ERROR(Text024,FIELDCAPTION("Next Invoice Date"),FIELDCAPTION("Starting Date"));

      IF Prepaid THEN BEGIN
        //// START
        //IF "Next Invoice Date" <> CALCDATE('<-CM>',"Next Invoice Date") THEN
	    OnBeforeCheckNextInvoiceDate(VAR Rec, VAR IsHandled);
        IF "Next Invoice Date" <> CALCDATE('<-CM>',"Next Invoice Date") AND (NOT IsHandled) THEN
        ///// END
          ERROR(Text026,FIELDCAPTION("Next Invoice Date"));
        TempDate := CalculateEndPeriodDate(TRUE,"Next Invoice Date");
        IF "Expiration Date" <> 0D THEN
          IF "Next Invoice Date" > "Expiration Date" THEN
            "Next Invoice Date" := 0D
          ELSE
            IF TempDate > "Expiration Date" THEN
              TempDate := "Expiration Date";
        IF ("Next Invoice Date" <> 0D) AND (TempDate <> 0D) THEN BEGIN
          "Next Invoice Period Start" := "Next Invoice Date";
          "Next Invoice Period End" := TempDate;
        END ELSE BEGIN
          "Next Invoice Period Start" := 0D;
          "Next Invoice Period End" := 0D;
        END;
      END ELSE BEGIN
	    ////// START
        //IF "Next Invoice Date" <> CALCDATE('<CM>',"Next Invoice Date") THEN
	    OnBeforeCheckNextInvoiceDate(VAR Rec, VAR IsHandled);
        IF "Next Invoice Date" <> CALCDATE('<CM>',"Next Invoice Date") AND (NOT IsHandled) THEN
	    ///// END
          ERROR(Text028,FIELDCAPTION("Next Invoice Date"));
        TempDate := CalculateEndPeriodDate(FALSE,"Next Invoice Date");
        IF TempDate < "Starting Date" THEN
          TempDate := "Starting Date";

Many thanks.

**Comment by AlexanderYakunin** [comment]
Can you please add [Event Request] prefix for title of your requests? It will improve visibility for us.

**Comment by lv-janpieter** [comment]
Only 1 of the 2 requested publishers have been added. I will create a new issue.
