### ISSUE TITLE
Missing Event on Page Document Attachment Factbox (1174) 

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#3716]
Dear Development Team,

our developer found this limitation, I reckon this is a new Event Request.
Can you please have a look and let us know?

It’s currently impossible to extent the Document Attachment Factbox to support new tables. In several places the Document Attachment functionality has case statements with ‘CASE “Table ID” OF’ or ‘CASE RecRef.NUMBER OF’ that can be extended via events.

Two of those places are:

Table Document Attachment (1173) – OnBeforeInsertAttachment Event: Before inserting the record, the event is called with both the attachment record (Rec) and the RecRef so you can add additional case statements. In use, the RecRef (called FromRecRef) appears to be set when OpenForRecRef is called from the page (see below).

Page Document Attachment Details (1173) – OnAfterOpenForRecRef Event: Before opening the page, the OpenForRecRef procedure can be called. This procedure sets FromRecRef as mentioned above as well as the filters on the page. As before, this event is called with both the attachment record (Rec) and the RecRef so you can add additional case statements.

The problem is that on the factbox itself, the OnDrillDown trigger has the following code. Notice that after the case statement, it immediately calls OpenForRecRef on the Document Attachment Details page:

```
**Documents - OnDrillDown()**
CASE "Table ID" OF
DATABASE::Customer:
  BEGIN
    RecRef.OPEN(DATABASE::Customer);
    IF Customer.GET("No.") THEN
    RecRef.GETTABLE(Customer);
  END;
  (etc)
END;

DocumentAttachmentDetails.OpenForRecRef(RecRef);
DocumentAttachmentDetails.RUNMODAL;
```

Because it’s not currently possible to extend the code in the OnDrillDown trigger you cannot add code to retrieve a RecRef for any other tables and to make it worse, the RecRef is then sent to OpenForRecRef, which will be unable to handle the new table because the RecRef will be incorrect. Since OpenForRecRef sets the RecRef used in both events described above, neither of those events will function properly on any table not supported in this trigger.

An event after the case statement and before the call to OpenForRecRef would fix the issue.

Cheers,
martonnagy

**Comment by AlexanderYakunin** [comment]
You already have event OnBeforeDrillDown(Rec,RecRef) in CASE statement for Documents - OnDrillDown() in page 1174 and related event OnAfterOpenForRecRef(Rec,RecRef) in OpenForRecRef(RecRef : RecordRef) in page 1173. So you have it already. Are you aware about this?

**Comment by martonnagy** [comment]
Hi Alexander,

will have a look and let you know.

Thanks

**Comment by martonnagy** [comment]
Hi Alexander,

yes, this is exactly what we are looking for.

I'm closing the issue now.

Marton
