### ISSUE TITLE
[Event Request] Page 498 - OnDrillDownTotalQty

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#3719]
Since requests with GlobalVarAccess are not anymore supported, we request [again](https://github.com/microsoft/AL/issues/2240) (but this time slightly modified):

In **page 498 Reserveration**, function **DrillDownTotalQuantity**, please add the following event almost at the end:

```
[…]
        DATABASE::"Assembly Line":
          BEGIN
            AvailableAssemblyLines.SetAssemblyLine(AssemblyLine,ReservEntry2);
            AvailableAssemblyLines.RUNMODAL;
          END ;
      END;
    END;
END;

// >> ---------------- NEW
OnDrillDownTotalQty(
  Rec,ReservEntry,ReservEntry2,QtyToReserveBase,QtyReservedBase,Location,
  SalesLine,PurchLine,ItemJnlLine,ReqLine,ProdOrderLine,ProdOrderComp,AssemblyHeader,AssemblyLine,
  PlanningComponent,ServiceLine,TransLine,JobPlanningLine);
// << ---------------- NEW

UpdateReservFrom;
```
**IncludeSender = Yes** (important)
Signature:
`LOCAL [IntegrationEvent] OnDrillDownTotalQty(VAR EntrySummary : Record "Entry Summary";ReservEntry : Record "Reservation Entry";ReservEntry2 : Record "Reservation Entry";QtyToReserveBase : Decimal;QtyReservedBase : Decimal;Location : Record Location;SalesLine : Record "Sales Line";PurchLine : Record "Purchase Line";ItemJnlLine : Record "Item Journal Line";ReqLine : Record "Requisition Line";ProdOrderLine : Record "Prod. Order Line";ProdOrderComp : Record "Prod. Order Component";AssemblyHeader : Record "Assembly Header";AssemblyLine : Record "Assembly Line";PlanningComponent : Record "Planning Component";ServiceLine : Record "Service Line";TransLine : Record "Transfer Line";JobPlanningLine : Record "Job Planning Line")`

**Comment by NKarolak** [comment]
@AlexanderYakunin Since this event is missing in the BC Insider - has this event request been denied, and if so, why? What shall we do instead?

**Comment by AlexanderYakunin** [comment]
We plan to change design of Reservation to more extendable soon, this event will prevents us from making required changes. Change have been made but reverted.

**Comment by NKarolak** [comment]
Current state in BC 16 (page 498 redesigned):

**DrillDownTotalQuantity**:
```
    local procedure DrillDownTotalQuantity()
    var
        Location: Record Location;
        AvailableItemTrackingLines: Page "Avail. - Item Tracking Lines";
    begin
        if HandleItemTracking and ("Entry No." <> 1) then begin
            Clear(AvailableItemTrackingLines);
            AvailableItemTrackingLines.SetItemTrackingLine(
                "Table ID", "Source Subtype", ReservEntry, ReservMgt.IsPositive, ReservEntry."Shipment Date");
            AvailableItemTrackingLines.RunModal;
            exit;
        end;

        ReservEntry2 := ReservEntry;
        if not Location.Get(ReservEntry2."Location Code") then
            Clear(Location);

        OnDrillDownTotalQuantity(SourceRecRef, Rec, ReservEntry2, Location, QtyToReserveBase - QtyReservedBase);

        UpdateReservFrom;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnDrillDownTotalQuantity(SourceRecRef: RecordRef; EntrySummary: Record "Entry Summary"; ReservEntry: Record "Reservation Entry"; Location: Record Location; MaxQtyToReserve: Decimal)
```

**Comment by AlexanderYakunin** [comment]
Remaning part is now in SalesLineReserve.Codeunit.al (check subscribers here). Same for other tables.
