### ISSUE TITLE
[Application Enhancement] Table 18/23/27/... - Customer/Vendor/Item - OnDelete, Change occurrences to something other than ''

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#3722]
Dear ALAppExtensions team,

This issue is **closely** related to issues #1682 and #3721.

In the `OnDelete` trigger, of among others table 18, the occurrences of the "No." (PK) of the deleted record are replaced with `''`.
For example:
```pascal
        ServContract.SetFilter(Status, '<>%1', ServContract.Status::Canceled);
        ServContract.SetRange("Customer No.", "No.");
        if not ServContract.IsEmpty then
            Error(
              Text007,
              TableCaption, "No.");

        ServContract.SetRange(Status);
        ServContract.ModifyAll("Customer No.", ''); // << Targeting these statements
```
Could you make a change in accordance so that occurrences of deleted records will be replaced with dedicated nos. for deliberately deleted records?
That is, you will then still be able to make the distinction between empty nos. and nos. for deliberately deleted records (and this will also prevent erroneous behavior in other places).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
