### ISSUE TITLE
[Bug] Table 18 - Customer - OnDelete, Check for Service Header records with Bill-to Customer No.

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#3724]
Dear ALAppExtensions team,

In the `OnDelete` trigger of table 18 Customer, there seems to be bug in the check whether a `Service Header` record with `Bill-to Customer No.` = `Rec."No."` exists.
It concerns the following code:
```pascal
        ServHeader.SetCurrentKey("Customer No.", "Order Date");
        ServHeader.SetRange("Customer No.", "No.");
        if ServHeader.FindFirst then
            Error(
              Text013,
              TableCaption, "No.", ServHeader."Document Type");

        ServHeader.SetRange("Bill-to Customer No.");
        if ServHeader.FindFirst then
            Error(
              Text013,
              TableCaption, "No.", ServHeader."Document Type");
```
The first block checks whether there are `Service Header` records with `Customer No.` = `Rec."No."`, which seems correct.
The second block however first clears the filter on the field `Bill-to Customer No.`, even though there is none, and then runs the same check.

I think this should be the following (or something similar, like for Sales Header records):
```pascal
        ServHeader.SetCurrentKey("Customer No.", "Order Date");
        ServHeader.SetRange("Customer No.", "No.");
        if ServHeader.FindFirst then
            Error(
              Text013,
              TableCaption, "No.", ServHeader."Document Type");

        ServHeader.SetRange("Customer No.");
        ServHeader.SetRange("Bill-to Customer No.", "No.");
        if ServHeader.FindFirst then
            Error(
              Text013,
              TableCaption, "No.", ServHeader."Document Type");
```
Could you look into this?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
