### ISSUE TITLE
[Event Requests] Codenit 80

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#3729]
We need a possibility to skip creating Shipment Lines for Service and Non-Inventory Items.

For that purpose we would need following changes in Codeunit 80:
PostItemLine - External
PostItemJnlLine - External
PostUpdateOrderLine - External
GetCountryCode - External
GetCountryRegionCode - External
OnBeforeInsertPostedHeaders(SalesHeader : Record "Sales Header",Handled: boolean) - Publisher in the function InsertPostedHeaders
OnBeforeCheckDocumentType(SalesHeader : Record "Sales Header";ExecuteDocCheck : Boolean,CheckDocumentType:boolean, Handled: boolean) - Publisher in the function CheckDocumentType

Some other approach for achieving the same goal would also be fine.

**Comment by AlexanderYakunin** [comment]
We require events definitions and placement in the code for processing of requests. This is more DCR request, please use Yammer to discuss this and get other partners vote for this suggestion. Or provide detailed specification of needed events and other changes for our investigation.

**Comment by miljance** [comment]
Hi,

As I have succesfully achieved what our need was I would therefore only ask for following:
PostItemJnlLine - External

This function has no variable parameter and could be used externally.

Please let me know whether this can be realized through such request.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
