### ISSUE TITLE
[Bug] Codeunit 7600 - ReverseSign

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#3733]
In **codeunit 7600 Calendar Management**, function **ReverseSign**, we believe we found a standard bug causing run-time errors. It could be fixed as follows:

```
EVALUATE(Formula,DateFormulaExpr);
NewDateFormulaExpr := CONVERTSTR(FORMAT(Formula),'+-','-+');
IF NOT (DateFormulaExpr[1] IN ['+','-']) THEN
  // >> ----- NEW
  IF NewDateFormulaExpr <> '<0D>' THEN
  // >> ----- NEW
    NewDateFormulaExpr := '-' + NewDateFormulaExpr;
EXIT(NewDateFormulaExpr);
```

**Comment by NKarolak** [comment]
Hi @AlexanderYakunin , this change did it not make into the latest bc insider images for BC 14 and BC 15.
Is it only postponed, or did you solve it differently (if so: where)? Thank you.

**Comment by AlexanderYakunin** [comment]
This is in but you will see it in 15.1 or 14.6

**Comment by jobulsin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
