### ISSUE TITLE
Event Request code unit 398 Sales Tax Calculate OnAfterCallExternalTaxEngineForDoc

### ISSUE THREAD

**Issue by robertmallon** [Microsoft/ALAppExtensions#374]
![image](https://user-images.githubusercontent.com/18425278/48576172-b8414f00-e90b-11e8-923a-523199adf838.png)

**Comment by AlexanderYakunin** [comment]
Please provide more details

**Comment by AlexanderYakunin** [comment]
As no details provided, we cannot execute this request.

**Comment by JesperSchulz** [comment]
Hi! We haven't heard from you in a while. Hopefully that's because you found a solution to the issue. For good housekeeping reasons we're closing issue, but if the problem still exists please submit a new request.
