### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post  – ReleaseSalesDocument

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#3745]
[Event Request] Codeunit 80 Sales-Post  – ReleaseSalesDocument

Could we please have two publishers OnReleaseSalesDocOnBeforeSetReleaseStatus and OnReleaseSalesDocOnAfterSetReleaseStatus in function ReleaseSalesDocument  Codeunit 80 Sales-Post ? 

```
local procedure ReleaseSalesDocument(var SalesHeader: Record "Sales Header")
    var
        SalesHeaderCopy: Record "Sales Header";
        TempAsmHeader: Record "Assembly Header" temporary;
        ReleaseSalesDocument: Codeunit "Release Sales Document";
        LinesWereModified: Boolean;
        SavedStatus: Option;
    Begin
..
 if not (PreviewMode or SuppressCommit) then begin
                Modify;
                Commit;
            end;

            // >>>>>>>>
            OnReleaseSalesDocOnBeforeSetReleaseStatus(var SalesHeader, SavedStatus, PreviewMode, SuppressCommit);
            // <<<<<<<<  

            Status := Status::Released;

            // >>>>>>>>
            OnReleaseSalesDocOnAfterSetReleaseStatus(var SalesHeader, SavedStatus, PreviewMode, SuppressCommit);
            // <<<<<<<<  

        end;
    end;

```

**Comment by AlexanderYakunin** [comment]
Can you explain why do you need this?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
