### ISSUE TITLE
New event request- codeunit 8 - function CalcCellValue

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#376]
new integration event:

LOCAL [IntegrationEvent] OnBeforeInsertResultCalcCellValue(ColumnLayout : Record "Column Layout";VAR Result : Decimal)
----------------------

**CalcCellValue**(AccSchedLine : Record "Acc. Schedule Line";ColumnLayout : Record "Column Layout";CalcAddCurr : Boolean) : Decimal
Result := 0;
IF AccSchedLine.Totaling <> '' THEN
  IF AccSchedCellValue.GET(AccSchedLine."Line No.",ColumnLayout."Line No.") THEN BEGIN
..................................................
    **OnBeforeInsertResultCalcCellValue(ColumnLayout,Result);**
    AccSchedCellValue."Row No." := AccSchedLine."Line No.";
    AccSchedCellValue."Column No." := ColumnLayout."Line No.";
    AccSchedCellValue.Value := Result;
    AccSchedCellValue."Has Error" := DivisionError;
    AccSchedCellValue."Period Error" := PeriodError;
    AccSchedCellValue.INSERT;
  END;
EXIT(Result);

**Comment by AlexanderYakunin** [comment]
Please check latest version of D365 Business Central before creating new ask, we already have event OnAfterCalcCellValue(VAR AccSchedLine : Record "Acc. Schedule Line";VAR ColumnLayout : Record "Column Layout";VAR Result : Decimal) in this place.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
