### ISSUE TITLE
[Event Change Request] Report 730 - OnAfterCopyItem

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#3763]
In **report 730 Copy Item**, publisher **OnAfterCopyItem**, please add the following parameters (from global variables):
- CopyUnitOfMeasure
- CopyVariants
- CopyItemVendor

@AlexanderYakunin Please note that it would be actually better to provide all Copy* variables.
Another extensibility obstacle is that the Request Page cannot be extended with our own checkboxes. If we wanted to add some kind of automatic popup (for displaying custom checkboxes), this would make the **test codeunit 134462 ERM Copy Item** fail.

**Comment by SSZurmussen7112** [comment]
Additionally to the request above, we need the already global function SetItem as [External]. Then we can start such copy item function out from programm code.
One comment: In my opinion the item copy function should not be managed by a report. If it would be managed by a page, partner would be able to add own fields via page extension, to be able to set marks which [partner] tables should be copied.

**Comment by AlexanderYakunin** [comment]
I agree we need a page here and will make sure you will get it soon.

**Comment by NKarolak** [comment]
Hi @AlexanderYakunin, what about my initial request state? Has it been forgotten?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by NKarolak** [comment]
In BC 16, report 730 is replaced with page 729 Copy Item, based on record "Copy Item Buffer".
The event to go with is **OnAfterValidateUserInput** (called in OnQueryClosePage):
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterValidateUserInput(var CopyItemBuffer: Record "Copy Item Buffer")
```

**SetItem** is already set to global there, too 👍
