### ISSUE TITLE
[Function Expose] Page 9652 "Report Layout Selection" - Fct. UpdateRec

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#3769]
Please change the Visibility of Function UpdateRec in Page "Report Layout Selection" to External:

````
AL-Code:

-     local procedure UpdateRec()
+     procedure UpdateRec()
````

**Comment by jobulsin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
