### ISSUE TITLE
[Application] Consistent actions on Sales / Purchase

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#3771]
_Please provide fix on next BC14 cumulative update if possible._

Please update the purchase document pages having Send/Print/Mail action to the same structure as the sales pages. Code should be consistent between Sales and Purchase.

E.g. PAG 143 contains 'SalesInvHeader := Rec;' whereas the code on PAG 146 does not.

![image](https://user-images.githubusercontent.com/25268332/63211948-89f0da00-c0fe-11e9-8af9-81aa25c5de48.png)

- [ ] Available in BC14

**Comment by jobulsin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
