### ISSUE TITLE
 [Event Request] Codeunit 90 Purch.-Post - OnAfterUpdateInvoicedQtyOnRcptLine

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#3775]
We need a new event in Codeunit 90 "Purch.-Post":

**LOCAL [IntegrationEvent] OnAfterUpdateInvoicedQtyOnRcptLine(VAR PurchRcptLine : Record "Purch. Rcpt. Line";VAR PurchLine : Record "Purchase Line";VAR PurchHeader : Record "Purchase Header";VAR PurchInvHeader : Record "Purch. Inv. Header";VAR QtyToBeInvoiced : Decimal;VAR QtyToBeInvoicedBase : Decimal;VAR SuppressCommit : Boolean)**

Called from:

_**LOCAL PostItemTracking(PurchHeader : Record "Purchase Header";PurchLine : Record "Purchase Line";VAR TempTrackingSpecification : TEMPORARY Record "Tracking Specification";TrackingSpecificationExists : Boolean)**_
...
...
...
          PurchRcptLine.TESTFIELD("Unit of Measure Code",PurchLine."Unit of Measure Code");
          PurchRcptLine.TESTFIELD("Variant Code",PurchLine."Variant Code");
          PurchRcptLine.TESTFIELD("Prod. Order No.",PurchLine."Prod. Order No.");
          UpdateQtyToBeInvoicedForReceipt(
            QtyToBeInvoiced,QtyToBeInvoicedBase,
            TrackingSpecificationExists,PurchLine,PurchRcptLine,TempTrackingSpecification);
          IF TrackingSpecificationExists THEN BEGIN
            TempTrackingSpecification."Quantity actual Handled (Base)" := QtyToBeInvoicedBase;
            TempTrackingSpecification.MODIFY;
          END;
          IF TrackingSpecificationExists THEN
            ItemTrackingMgt.AdjustQuantityRounding(
              RemQtyToInvoiceCurrLine,QtyToBeInvoiced,
              RemQtyToInvoiceCurrLineBase,QtyToBeInvoicedBase);
          RemQtyToBeInvoiced := RemQtyToBeInvoiced - QtyToBeInvoiced;
          RemQtyToBeInvoicedBase := RemQtyToBeInvoicedBase - QtyToBeInvoicedBase;
          UpdateInvoicedQtyOnPurchRcptLine(PurchRcptLine,QtyToBeInvoiced,QtyToBeInvoicedBase);
	  **//Init insert ----------------------------------------
          OnAfterUpdateInvoicedQtyOnRcptLine(PurchRcptLine,PurchLine,PurchHeader,PurchInvHeader,QtyToBeInvoiced,QtyToBeInvoicedBase,SuppressCommit);
	  //End insert ----------------------------------------**
          IF PurchLine.Type = PurchLine.Type::Item THEN
            PostItemJnlLine(
              PurchHeader,PurchLine,
              0,0,
              QtyToBeInvoiced,QtyToBeInvoicedBase,
              ItemEntryRelation."Item Entry No.",'',TempTrackingSpecification);
...
...
...

**Comment by AlexanderYakunin** [comment]
Do you really need everything with VAR?

**Comment by TxusMoyano** [comment]
Yes, at least PurchRcptLine,PurchLine,PurchHeader,PurchInvHeader
