### ISSUE TITLE
[Event Request] Table 39 Purchase Line  – FormatType

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#3776]
[Event Request] Table 39 Purchase Line  – FormatType
For a further use of Type Option 3 (Resource in Sales) in Purchase it will be very helpful if you can fulfil following wishes for new Publisher
Could we please have a publisher OnBeforeFormatType in function FormatType Table 39 Purchase Line?

```
[External] FormatType() : Text[20]
// >>>>>>>> 
OnBeforeFormatType(Rec,Var IsHandeld);
If IsHandeld then
  Exit
// <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
