### ISSUE TITLE
[Event Request] Report 402 Purchase Document – Test - DataItem RoundLoop - OnAfterGetRecord

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#3778]
[Event Request] Report 402 Purchase Document – Test - DataItem RoundLoop - OnAfterGetRecord

For a further use of Type Option 3 (Resource in Sales) in Purchase it will be very helpful if you can fulfil following wishes for new Publisher
Could we please have a publisher OnPurchaseTypeCaseElse in DataItem RoundLoop Report 402 Purchase Document - Test?
```
  IF NOT "Prepayment Line" AND ("Prepmt. Line Amount" > 0) THEN
    IF "Prepmt. Line Amount" > "Prepmt. Amt. Inv." THEN
      AddError(STRSUBSTNO(Text042,FIELDCAPTION("Prepmt. Line Amount")));

  CASE Type OF
    Type::"G/L Account":
      BEGIN
…
…
                  FA.FIELDCAPTION(Inactive),FALSE,FA.TABLECAPTION,"No."));
          END ELSE
            AddError(
              STRSUBSTNO(
                Text008,
                FA.TABLECAPTION,"No."));
      END;
// >>>>>>>> 
    ELSE BEGIN
      OnPurchaseTypeCaseElse(Type,”No.”,Text);
      IF Text <> ‘’ THEN 
        AddError(Text);
    END;
// <<<<<<<<  

  END;

  IF "Line No." > OrigMaxLineNo THEN BEGIN
    AddDimToTempLine("Purchase Line");

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
