### ISSUE TITLE
[Function Expose] Codeunit 41

### ISSUE THREAD

**Issue by miljance** [Microsoft/ALAppExtensions#378]
Following Functions would be really usefull as External Functions:
FindText
ReadCharacter
GetMyFilterText
AddToFilter

Publisher would be also much appreciated in Function GetMyFilterText:
OnBeforeGetMyFilterText
I am not sure for parameters of this publishers but we currently want to include further tables appart from currently included:
MyTableNo IN [DATABASE::"My Customer",DATABASE::"My Vendor",DATABASE::"My Item"]

Currently we have following statement on this position:
MyTableNo IN [DATABASE::"My Customer",DATABASE::"My Vendor",DATABASE::"My Item", DATABASE::"My Job", DATABASE::"My Contact"]

**Comment by IhorHandziuk** [comment]
Thank you for your request. We are now making a big effort on refactoring Text management and then open-sourcing it. We really want to refactor all the procedures above. 
Please, consider using regex for achieving the same result as FindText and ReadCharacter. Alternatively, please, wait until we refactor the code.
