### ISSUE TITLE
Codeunit 22 "Item Jnl.-Post Line" OnBeforeTempItemEntryRelationInsert (external)

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#3780]
Could you please add a new publisher event to codeunit 22 and call it before inserting the temp item entry relation entry? This will allow me to then manipulate some custom data per transaction which I am using on after post for other functionality.

![OnBeforeTempItemEntryRelationInsert - 1](https://user-images.githubusercontent.com/50593101/63274310-8def3a00-c26d-11e9-94d6-f0d56b82729a.jpg)
![OnBeforeTempItemEntryRelationInsert - 2](https://user-images.githubusercontent.com/50593101/63274312-8e87d080-c26d-11e9-9c2c-83ad68b3e590.jpg)
![OnBeforeTempItemEntryRelationInsert](https://user-images.githubusercontent.com/50593101/63274313-8e87d080-c26d-11e9-9b3f-d7711e89e7c1.jpg)

**Comment by AlexanderYakunin** [comment]
Please check latest code, both events already exists
