### ISSUE TITLE
Codeunit 22 "Item Jnl.-Post Line" OnAfterCreateItemJnlLineFromEntry (External)

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#3781]
Could you add a new publisher event to codeunit 22 and call it at the end of the CreateItemJnlLinefromEntry function? This will allow me to update some custom fields on the item journal line which I then use during posting.

![OnAfterCreateItemJnlLineFromEntry -1](https://user-images.githubusercontent.com/50593101/63274830-7d8b8f00-c26e-11e9-92db-f454d6588a49.jpg)
![OnAfterCreateItemJnlLineFromEntry](https://user-images.githubusercontent.com/50593101/63274831-7d8b8f00-c26e-11e9-9bf3-289a7c195db7.jpg)

**Comment by AlexanderYakunin** [comment]
This event already exists
OnAfterCreateItemJnlLineFromEntry(ItemJnlLine,ItemLedgEntry);
