### ISSUE TITLE
[Event Request] COD230 - OnBeforeGetJournalSimplePageModePreference

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#3783]
Hello,

we would like to deactivate the initial simple mode and Need an Event for that on COD230. 

![image](https://user-images.githubusercontent.com/45033081/63324714-e8999c00-c328-11e9-8b22-dac77f91805d.png)

Thank you!

**Comment by AlexanderYakunin** [comment]
This function is external so you can use it directly in extension ( I assume you are looking into old version)

[External] SetJournalSimplePageModePreference(SetToSimpleMode : Boolean;PageIdToSet : Integer)
// sets journal page preference for a page
// preference set to simple page if SetToSimpleMode is true; else set to classic mode

**Comment by SKeiler** [comment]
Yes sure, but we would like to create the JournalUserPreferences Record before it is read from database if not exists (so the shown FINDFIRST in the Picture will be always true). And yes, we want to use the SetJournalSimplePageModePreference-procedure for that. 

Without the Event we would have to synchronize periodically the JournalUserPreferences-Table with the User-Table and the possible pages. That would be much more complex.

**Comment by AlexanderYakunin** [comment]
OK, no problems to add this event
