### ISSUE TITLE
[Event Request] TAB290 VAT Amount Line - InsertNewLine

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#3784]
Could TAB290 VAT Amount Line - `InsertNewLine` be split in a sales and purchase function, with each calling an event?

Example structure:
```
SalesInsertNewLine(SalesLine)
   With SalesLine do
      InsertNewLine("VAT Identifier","VAT Calculation Type","Tax Group Code",FALSE,"VAT %","Line 
       Amount" >= 0,FALSE);
   OnInsertNewLineSales(VAR Rec, SalesLine)
```
Same for purchase

We would like to fill in an extra field for sales and purchase on the VAT Amount Line but are unable to cause the `InsertNewLine` function only accepts the values from the fields ...

+ Could the calls to `InsertNewLine`, like in TAB37 Sales Line - CalcVATAmountLines, be changed to the new functions?

**Comment by dtkb** [comment]
Where was this shipped? BC160 in table 290 still just calls `InsertNewLine()` from e.g. `CalcVATAmountLines()`, and that is not extensible as it provides no events. So we'll have to copy and paste the base code again.

**Comment by SirBETE** [comment]
BC16.1 has 
```
    procedure InsertLine(): Boolean
    var
        VATAmountLine: Record "VAT Amount Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnInsertLine(Rec, IsHandled);
        if IsHandled then
            exit(true);

        if not (("VAT Base" <> 0) or ("Amount Including VAT" <> 0)) then
            exit(false);

        Validate(Positive, "Line Amount" >= 0);
        VATAmountLine := Rec;
        if Find then begin
            "Line Amount" += VATAmountLine."Line Amount";
            "Inv. Disc. Base Amount" += VATAmountLine."Inv. Disc. Base Amount";
            "Invoice Discount Amount" += VATAmountLine."Invoice Discount Amount";
            Quantity += VATAmountLine.Quantity;
            "VAT Base" += VATAmountLine."VAT Base";
            "Amount Including VAT" += VATAmountLine."Amount Including VAT";
            "VAT Difference" += VATAmountLine."VAT Difference";
            "Pmt. Discount Amount" += VATAmountLine."Pmt. Discount Amount";
            "VAT Amount" := "Amount Including VAT" - "VAT Base";
            "Calculated VAT Amount" += VATAmountLine."Calculated VAT Amount";
            "VAT Base (Lowered)" += VATAmountLine."VAT Base (Lowered)";
            OnInsertLineOnBeforeModify(Rec, VATAmountLine);
            Modify;
        end else begin
            "VAT Amount" := "Amount Including VAT" - "VAT Base";
            Insert;
        end;

        exit(true);
    end;
```

**Comment by dtkb** [comment]
Thanks. I might not be looking at latest 16.x code.

Has that replaced previous sites where `InsertNewLine()` was used, including in e.g. `Purchase Line` - `CalcVATAmountLines()`?

**Comment by SirBETE** [comment]
Yeah

BC16.1 (Original-16.1.12629.12805-be-al) uses in `procedure CalcVATAmountLines` for table 37 "Sales Line":
```
if not VATAmountLine.Get(
  "VAT Identifier", "VAT Calculation Type", "Tax Group Code", false, "Line Amount" >= 0)
then
  VATAmountLine.InsertNewLine(
  "VAT Identifier", "VAT Calculation Type", "Tax Group Code", false, "VAT %", "Line Amount" >= 0, false);
```

**Comment by dtkb** [comment]
Yeah, but you showed `InsertLine()`, but that's calling `InsertNewLine()`. Does the latter just delegate to the former? It seems to me they do different things (with unfortunately ambiguous names).

**Comment by SirBETE** [comment]
Oh yes, now you mention it. I looked over it ...
@jobulsin Could you give us a hand here?
What's the flow? How and where can we intervene?
