### ISSUE TITLE
[Event Request] Table 5741 - OnBeforeValidateItemDescription

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/ALAppExtensions#3788]
Could you please add a new integration event "OnBeforeValidateItemDescription" for the Transfer Line table (5741) for field "Description" (13)

We try to avoid the search for an item (via a SQL LIKE command) and want to skip the CONFIRM dialog (therefore we are open to any other options).

```
    [Integration]
    LOCAL PROCEDURE OnBeforeValidateItemDescription@21(VAR Rec@1000 : Record 5741;xRec@1001 : Record 5741;CurrFieldNo@1002 : Integer;VAR IsHandled@1003 : Boolean);
    BEGIN
    END;
```

```
{ 13  ;   ;Description;Text100;TableRelation=Item WHERE (Type=CONST(Inventory),Blocked=CONST(No));
  OnValidate=VAR
     Item@1001 : Record 27;
     ReturnValue@1003 : Text[50];
     ItemDescriptionIsNo@1000 : Boolean;
+    IsHandled@1004 : Boolean;
     BEGIN
+      IsHandled := FALSE;
+      OnBeforeValidateItemDescription(Rec,xRec,CurrFieldNo,IsHandled);
+      IF IsHandled THEN
+       EXIT;
```

**Comment by AlexanderYakunin** [comment]
This issue will be solved soon in different way.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
