### ISSUE TITLE
[EventRequest] table 32 “Item Ledger Entry”, VerifyOnInventory [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3796]
Please add a new publisher event **OnVerifyOnIventory** in Table 32 on External function **VerifyOnInventory** and call at the start of the function

![2019-08-20 14_16_53-Window](https://user-images.githubusercontent.com/54017538/63346417-3926ee80-c355-11e9-843f-a7fa71bd37b2.png)

Please add the corresponding Integration Event In the bottom of the table
![2019-08-20 14_17_01-Window](https://user-images.githubusercontent.com/54017538/63346420-3d530c00-c355-11e9-8f04-790730889e70.png)

**Comment by AlexanderYakunin** [comment]
This event already exist
