### ISSUE TITLE
Codeunit 8 - Function CalcCellValue - Change Local Function to External

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#380]
Could you change Local = No of function CalcCellValue , because we need use this function out of codeunit  8 (AccSchedManagement) when use event 
  OnBeforeCalcCellExit(AccSchedLine,ColumnLayout,CalcAddCurr,Result)

**Comment by darjoo** [comment]
Hi! We have accept your request and made `CalcCellValue` external. We usually include these types of changes in the next minor release, so look for it there.

**Comment by Halilovast** [comment]
Hi @darjoo , thanks.
