### ISSUE TITLE
[EventRequest] table 5741 “Transfer Line”, CalcBaseQty [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3808]
Please add a new publisher event OnBeforeCalcBaseQty at the start of the function CalcBaseQty in table 5741
![2019-08-20 14_38_02-Window](https://user-images.githubusercontent.com/54017538/63347792-2bbf3380-c358-11e9-97c3-9014b957db75.png)

Please add the corresponding Integration Event In the bottom of the table.

![2019-08-20 14_38_16-Window](https://user-images.githubusercontent.com/54017538/63347799-2eba2400-c358-11e9-990d-b0f65673f015.png)

**Comment by AlexanderYakunin** [comment]
Local function already replaced by UnitOfMeasureManagement.CalcBaseQty, theerefore we cannot implement this event
