### ISSUE TITLE
[EventRequest] table 5767 “Warehouse Activity Line”, ChechWhseDocLine[External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3809]
Please add a new publisher event OnBeforeCheckWhseDocLine at the start of the function CheckWhseDocLine in table 5767

![2019-08-20 14_39_13-Window](https://user-images.githubusercontent.com/54017538/63347854-51e4d380-c358-11e9-9d12-aafa48e9719b.png)
Please add the corresponding Integration Event In the bottom of the table.
![2019-08-20 14_39_21-Window](https://user-images.githubusercontent.com/54017538/63347861-57421e00-c358-11e9-8635-048c857e4d4e.png)

**Comment by AlexanderYakunin** [comment]
We already have it!
[External] CheckWhseDocLine()
IsHandled := FALSE;
OnBeforeCheckWhseDocLine(Rec,IsHandled);
IF IsHandled THEN
  EXIT;
