### ISSUE TITLE
[Event FRequest] Table 37 - Update Amounts

### ISSUE THREAD

**Issue by GaryFrostick** [microsoft/ALAppExtensions#3819]
There is a current event in the UpdateAmounts function (OnAfterUpdateAmounts), however there is a problem with this in that if code that subscribes to the event amends the amounts then the resulting prepayments will be incorrectly calculated.

I would therefore propose a new event in this function prior to code that calculates prepayments.
To preserver the integrity of the other code something along the lines of a event that can result an additional amount that can be added/subtracted from the total would be ideal.

**Comment by AlexanderYakunin** [comment]
Please suggest new event placement and definition.

**Comment by AlexanderYakunin** [comment]
Closing as no event definition provided
