### ISSUE TITLE
[Application Request] Multiple Email attachments

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#3820]
_We want to enable adding multiple attachments in standard feature for sending Purchase Orders (as well Posted Sales Invoces and Memos)_

https://github.com/microsoft/AL/issues/3601 has been closed for almost a year, but still no standard solution to send mails with more than 7 attachments.

We'd like to be able to call SMTPMail.AddAttachment before actually sending the mail.

Related to https://experience.dynamics.com/ideas/idea/?ideaid=e12d2e5e-3cc9-e811-b96f-0003ff689b02 (90+ votes)

**Comment by fvet** [comment]
Table 9501 "Email Attachment" seems to be available for this purpose, but nowhere used ...

**Comment by AlexanderYakunin** [comment]
We cannot make this as a fix, this work is planned for next major version.

**Comment by fvet** [comment]
@AlexanderYakunin Fine enough! I suppose this will be part of BC 16 ('20 wave 1 release)?

This is important too know, since we need to refactor our entire mail integration (targeted for BC 16) and multiple attachments is one of them. 

Having the options to add multiple attachments to any outgoing mail (whether via **Report Selections, Mail Management, Document-Mailing, Mail, SMTP Mail** codeunits) would reduce our footprint on standard objects a lot.
