### ISSUE TITLE
[Function Expose]DownloadAndOpenExcel

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/ALAppExtensions#383]
Can you please expose DownloadAndOpenExcel on the "Excel Buffer" table? I cannot find any Extension-enabled functions that allow me to download a spreadsheet.

**Comment by JesperSchulz** [comment]
I cannot expose DownloadAndOpenExcel, as that implementation uses files, which we'd like to avoid in the cloud. Instead I've backported our latest chages to the Excel Buffer, which amonst others includes a function by the name SaveToStream(VAR ResultStream : OutStream;EraseFileAfterCompletion : Boolean). Using DOWNLOADFROMSTREAM afterwards, you will be able to download your spreadsheet. I hope that works for you! If not, please let me know.

**Comment by DavidRoys** [comment]
That sounds perfect. I’ll try it out. Do I just grab the latest insider build to see these changes?

**Comment by DavidRoys** [comment]
@JesperSchulz - I'm trying to get this working now and it appears this does not work. Excel Buffer.SaveToStream uses files.

```
[External] SaveToStream(VAR ResultStream : OutStream;EraseFileAfterCompletion : Boolean)
ExcelFile.OPEN(FileNameServer);
ExcelFile.CREATEINSTREAM(FileStream);
COPYSTREAM(ResultStream,FileStream);
ExcelFile.CLOSE;
IF EraseFileAfterCompletion THEN
  FILE.ERASE(FileNameServer);
```
Can I reopen this issue? Or maybe there is another way to solve this problem?

**Comment by DavidRoys** [comment]
Hi @JesperSchulz - is there any way to get this re-opened or can you give some indication as to how ExcelBuffer can be downloaded? The SaveToStream and DownloadFromStream combinations suggested do not work because SaveToStream requires a file on the server.
