### ISSUE TITLE
rad.json

### ISSUE THREAD

**Issue by JSebastianN** [microsoft/ALAppExtensions#3838]
I do not seem to be able to have my GIT client ignore rad.json

This file get modified constantly and have no business being tracked.

This might be a GIT issue, but still, why introduce this in a way that will annoy every developer?

**Comment by AndriusAndrulevicius** [comment]
Have you tried adding **/rad.json to .gitignore?

**Comment by JSebastianN** [comment]
Thanks that did it

**Comment by JSebastianN** [comment]
Thanks that did it
