### ISSUE TITLE
[EventRequest] Codeunit 73 “Puch Explode Bom”, OnRun[Trigger]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3850]
Please add a new publisher event OnBeforeOnRun at the start of the OnRun Trigger in codeunit 73

![2019-08-22 08_53_47-EventReques2 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63492759-6640e180-c4ba-11e9-9b76-7e836f84708a.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.

![2019-08-22 08_53_54-EventReques2 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63492772-6b059580-c4ba-11e9-9917-a5dc0133e0e1.png)

**Comment by AndriusPil** [comment]
Hi guys,

Thank you for adding this event in version 14.00, but it looks like this event is missing in the Wawe2 version (15.0) is it possible to bring it back?
