### ISSUE TITLE
[EventRequest] Codeunit 246 “Item Jnl.-Explode BOM”, OnRun Trigger

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3853]
Please add a new publisher event OnBeforeOnRun at the start of the OnRun Trigger in codeunit 246

![2019-08-22 09_07_08-EventReques5 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63493595-401c4100-c4bc-11e9-9e2d-3e99523540e5.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.

![2019-08-22 09_07_13-EventReques5 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63493602-427e9b00-c4bc-11e9-833d-9f46725a227a.png)

**Comment by AndriusPil** [comment]
Hi guys,

Thank you for adding this event in version 14.00, but it looks like this event is missing in the Wawe2 version (15.0) is it possible to bring it back?
