### ISSUE TITLE
[EventRequest] Codeunit 5750 “Whse.- Create Source Document”, FromSalesLine2ShptLine[External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3859]
Please add a new publisher event OnBeforeCreateShptLineFromSalesLine at the end of the function FromSalesLine2ShptLine in codeunit 5750

![2019-08-22 09_39_34-EventReques9 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63495772-cd619480-c4c0-11e9-9b42-4c42e15ce774.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.

![2019-08-22 09_39_46-EventReques9 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63495780-d05c8500-c4c0-11e9-9566-d5e49504d49c.png)

**Comment by AlexanderYakunin** [comment]
Not sure I understand your ask. OnBefore event cannot be added in the end, it sholuld be in the beginning of procedure. Can you please verify this ask and provide exact location of new event in the code?

**Comment by TjaTrimit** [comment]
My bad, Missing snippet, we do not want it in the end, but before 
If TotalOutstandingWhseShptQtyBase like in the image below.

![2019-08-28 13_18_09-Window](https://user-images.githubusercontent.com/54017538/63851410-8e3ab400-c996-11e9-8a1f-87b0c372598b.png)
