### ISSUE TITLE
[EventRequest] Codeunit 5802 “Inventory Posting To G/L”, BufferInvtPosting [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3862]
Please add a new publisher event OnBeforeBufferInvtPosting at the start of the function BufferInvtPosting in codeunit 5802

![2019-08-22 10_01_55-EventRequest pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63497397-f172a500-c4c3-11e9-9a9f-07f08f77b555.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.
![2019-08-22 10_02_01-EventRequest pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63497403-f33c6880-c4c3-11e9-8be2-cabecdf388d2.png)

**Comment by AlexanderYakunin** [comment]
We already have this event
[External] BufferInvtPosting(VAR ValueEntry : Record "Value Entry") : Boolean
IsHandled := FALSE;
OnBeforeBufferInvtPosting(ValueEntry,Result,IsHandled);
IF IsHandled THEN
  EXIT;

**Comment by AlexanderYakunin** [comment]
I missed that RunOnlyCheck is another global variable in codeunit, will be added as parameter. Result is needed as this function should return value.
