### ISSUE TITLE
[EventRequest] Codeunit 80 “Sales Post”, ShouldPostWhseJnlLine [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3875]
Please add a new publisher event OnBeforeCheckShouldPostWhseJnlLine at the start of the function ShouldPostWhseJnlLine in codeunit 80

![2019-08-22 12_52_33-EventReques5 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63509162-c300c400-c4db-11e9-8d13-06bf9000ea05.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.

![2019-08-22 12_52_47-EventReques5 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63509167-c6944b00-c4db-11e9-8e74-c418c8316db8.png)

**Comment by AlexanderYakunin** [comment]
This event already implemented

**Comment by TjaTrimit** [comment]
Which version was that being implemented?
