### ISSUE TITLE
[EventRequest] Codeunit 80 “Sales Post”, CheckWarehouse [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3876]
Please add a new publisher event OnBeforeCheckWarehouse at the start of the function CheckWarehouse in codeunit 80

![2019-08-22 12_56_16-EventReques5 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63509353-43272980-c4dc-11e9-9206-b4762567a4db.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.
![2019-08-22 12_56_22-EventReques5 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63509358-46221a00-c4dc-11e9-9545-a9ab9bf5be6e.png)

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 14.6.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 14.6.
