### ISSUE TITLE
[EventRequest] Codeunit 5763 “Whse.-Post Shipment”, [External] CreatePostedShptLine

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3882]
Please add a new publisher event OnCreatePostedShptLineOnBeforePostWhseJnlLine at the end of the function  CreatePostedShptLine in codeunit 5763

![2019-08-22 13_25_20-EventReques7 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63511003-55a36200-c4e0-11e9-83a8-4a0ce2d523e5.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.

![2019-08-22 13_25_30-EventReques7 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63511010-589e5280-c4e0-11e9-9720-c051f1b6a7a0.png)

**Comment by AlexanderYakunin** [comment]
We already have this event, seems you are looking for very old code. Please use latest code from 14.3 or insider builds from 15.0 for ordering events
