### ISSUE TITLE
[EventRequest] Table 39 “purchase Line”, CreateDim

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3886]
Please add a new publisher event OnBeforeGetDefaultDimID in the middle of of the function CreateDim in table 39
![2019-08-22 13_53_25-EventReques9 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63512508-49210880-c4e4-11e9-89c3-c6ddc3fa55a6.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.
![2019-08-22 13_53_43-EventReques9 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63512509-4c1bf900-c4e4-11e9-9e12-0a5d341f27dc.png)

**Comment by AlexanderYakunin** [comment]
You already have OnAfterCreateDimtableIDs with needed parameters

**Comment by TjaTrimit** [comment]
We have an issue since we need that publisher because the following
`Shortcut Dimension 1 code` := '';
`Shortcut Dimension 2 code` := '';
is set to being blank. And we need those parameters in our publisher.

**Comment by TjaTrimit** [comment]
> You already have OnAfterCreateDimtableIDs with needed parameters

Never mind, we have found another solution that works for us by creating and using a singleinstance codeunit. So we can close this one
