### ISSUE TITLE
[Function Expose] Table 5767 - CheckIncreaseCapacity

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/ALAppExtensions#3891]
```
-   LOCAL PROCEDURE CheckIncreaseCapacity@6(DeductLineCapacity@1003 : Boolean);
+   [External]
+   PROCEDURE CheckIncreaseCapacity@6(DeductLineCapacity@1003 : Boolean);
```

**Comment by jobulsin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
