### ISSUE TITLE
[feature request] Table 15 G/L Account

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#3897]
Hello Team, 

we need a new field in G/L Account that can expand the tablefilter when using lookup in Salesline, Purchaseline and so on.

Actually we expand the normal tablefilter of the field No. 

Direct Posting=CONST(Yes),Account Type=CONST(Posting),Blocked=CONST(No),M365 Assignment Sales/Purchase=FILTER(Sales|Sales and Purchase)

Because we cant expand table relations, it is up to you to handle that. Also we cant use a "programmed lookup"!

The reason is for purpose of hinder posting to purchaseaccounts in the salesarea and vice versa.
and much more important not seeing G/L Accounts with personal important information 
(personal datainformation, when having a "one person" account with salary) for everyone around.

so every G/L account becomes that Option field ('BLANK', Sales, Purchase, 'Sales|Purchase')
and in every Page where a lookup into the G/L Account is possible, it reacts on that table relation.

It would improve greatly "personal data" issues.

**Comment by AlexanderYakunin** [comment]
Please read this article https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tablerelation-property
You can extend table relations in table extension and therefore should be able to do this yourself.
