### ISSUE TITLE
[Event Request] Table 5991 Service Shipment Line - InsertInvLineFromShptLine

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#3899]
We have a requirement to add text lines of our own and modify the description of the already created text line. To make this possible we require the following publisher:

    [External]
    PROCEDURE InsertInvLineFromShptLine@2(VAR ServiceLine@1000 : Record 5902);
    VAR
      ServiceInvHeader@1011 : Record 5900;
      ServiceOrderHeader@1008 : Record 5900;
      ServiceOrderLine@1005 : Record 5902;
      TempServiceLine@1002 : TEMPORARY Record 5902;
      ServDocReg@1013 : Record 5936;
      TransferOldExtLines@1007 : Codeunit 379;
      ItemTrackingMgt@1009 : Codeunit 6500;
      ExtTextLine@1006 : Boolean;
      NextLineNo@1001 : Integer;
      lrecServiceOrderHeader@11095585 : Record 5900;
      lbAddYourRefTextLine@11095586 : Boolean;
    BEGIN
      SETRANGE("Document No.","Document No.");

      TempServiceLine := ServiceLine;
      IF ServiceLine.FIND('+') THEN
        NextLineNo := ServiceLine."Line No." + 10000
      ELSE
        NextLineNo := 10000;

      IF ServiceInvHeader."No." <> TempServiceLine."Document No." THEN
        ServiceInvHeader.GET(TempServiceLine."Document Type",TempServiceLine."Document No.");

      IF ServiceLine."Shipment No." <> "Document No." THEN BEGIN
        ServiceLine.INIT;
        ServiceLine."Line No." := NextLineNo;
        ServiceLine."Document Type" := TempServiceLine."Document Type";
        ServiceLine."Document No." := TempServiceLine."Document No.";
        ServiceLine.Description := STRSUBSTNO(Text000,"Document No.");
        ServiceLine."Shipment No." := "Document No.";
        ServiceLine.INSERT;
        NextLineNo := NextLineNo + 10000;
      END;

      ///// START
      OnBeforeInsertInvLineFromShptLineOnAfterInsertTextLine(VAR ServiceLine, Rec, VAR NextLineNo);
      ///// END

      TransferOldExtLines.ClearLineNumbers;

Many thanks.

**Comment by AlexanderYakunin** [comment]
Why in this place? So it will run event if ServiceLine is not inserted?

**Comment by lv-janpieter** [comment]
We need it after the INSERT so I wouldn't mind if it was put inside the IF condition, however I thought this position would be more generic.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
