### ISSUE TITLE
[Event Request] Codeunit 427 OnAfterICOutBoxSalesHeaderTransferFieldsFromSalesInvHdr

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#3910]
In codeunit 427 similar to the existing Event trigger OnAfterICOutBoxSalesHeaderTransferFields we Need a new Event trigger in procedure CreateOutboxSalesInvTrans, CreateOutboxSalesCrMemoTrans, CreateOutboxPurchDocTrans:

[External] CreateOutboxSalesInvTrans(SalesInvHdr : Record "Sales Invoice Header")
IsHandled := FALSE;
OnBeforeCreateOutboxSalesInvTrans(SalesInvHdr,IsHandled);
IF IsHandled THEN
  EXIT;

Customer.GET(SalesInvHdr."Bill-to Customer No.");
ICPartner.GET(Customer."IC Partner Code");
IF ICPartner."Inbox Type" = ICPartner."Inbox Type"::"No IC Transfer" THEN
  EXIT;

GLSetup.LOCKTABLE;
GetGLSetup;
TransactionNo := GLSetup."Last IC Transaction No." + 1;
GLSetup."Last IC Transaction No." := TransactionNo;
GLSetup.MODIFY;
WITH SalesInvHdr DO BEGIN
  OutboxTransaction.INIT;
  OutboxTransaction."Transaction No." := TransactionNo;
  OutboxTransaction."IC Partner Code" := Customer."IC Partner Code";
  OutboxTransaction."Source Type" := OutboxTransaction."Source Type"::"Sales Document";
  OutboxTransaction."Document Type" := OutboxTransaction."Document Type"::Invoice;
  OutboxTransaction."Document No." := "No.";
  OutboxTransaction."Posting Date" := "Posting Date";
  OutboxTransaction."Document Date" := "Document Date";
  OutboxTransaction."Transaction Source" := OutboxTransaction."Transaction Source"::"Created by Current Company";
  OutboxTransaction.INSERT;
END;
ICOutBoxSalesHeader.TRANSFERFIELDS(SalesInvHdr);
OnAfterICOutBoxSalesHeaderTransferFieldsFromSalesInvHdr(ICOutBoxSalesHeader,SalesInvHdr);  <-- new Event Trigger
ICOutBoxSalesHeader."Document Type" := ICOutBoxSalesHeader."Document Type"::Invoice;
ICOutBoxSalesHeader."IC Partner Code" := OutboxTransaction."IC Partner Code";

[External] CreateOutboxSalesCrMemoTrans(SalesCrMemoHdr : Record "Sales Cr.Memo Header")
IsHandled := FALSE;
OnBeforeCreateOutboxSalesCrMemoTrans(SalesCrMemoHdr,IsHandled);
IF IsHandled THEN
  EXIT;

Customer.GET(SalesCrMemoHdr."Bill-to Customer No.");
ICPartner.GET(Customer."IC Partner Code");
IF ICPartner."Inbox Type" = ICPartner."Inbox Type"::"No IC Transfer" THEN
  EXIT;

GLSetup.LOCKTABLE;
GetGLSetup;
TransactionNo := GLSetup."Last IC Transaction No." + 1;
GLSetup."Last IC Transaction No." := TransactionNo;
GLSetup.MODIFY;
WITH SalesCrMemoHdr DO BEGIN
  OutboxTransaction.INIT;
  OutboxTransaction."Transaction No." := TransactionNo;
  OutboxTransaction."IC Partner Code" := Customer."IC Partner Code";
  OutboxTransaction."Source Type" := OutboxTransaction."Source Type"::"Sales Document";
  OutboxTransaction."Document Type" := OutboxTransaction."Document Type"::"Credit Memo";
  OutboxTransaction."Document No." := "No.";
  OutboxTransaction."Posting Date" := "Posting Date";
  OutboxTransaction."Document Date" := "Document Date";
  OutboxTransaction."Transaction Source" := OutboxTransaction."Transaction Source"::"Created by Current Company";
  OutboxTransaction.INSERT;
END;
ICOutBoxSalesHeader.TRANSFERFIELDS(SalesCrMemoHdr);
OnAfterICOutBoxSalesHeaderTransferFieldsFromSalesCrMemoHdr(ICOutBoxSalesHeader,SalesCrMemoHdr);  <-- new event Trigger
ICOutBoxSalesHeader."Document Type" := ICOutBoxSalesHeader."Document Type"::"Credit Memo";

[External] CreateOutboxPurchDocTrans(PurchHeader : Record "Purchase Header";Rejection : Boolean;Post : Boolean)
OnBeforeCreateOutboxPurchDocTrans(PurchHeader,Rejection,Post);

GLSetup.LOCKTABLE;
GetGLSetup;
TransactionNo := GLSetup."Last IC Transaction No." + 1;
GLSetup."Last IC Transaction No." := TransactionNo;
GLSetup.MODIFY;
Vendor.GET(PurchHeader."Buy-from Vendor No.");
Vendor.CheckBlockedVendOnDocs(Vendor,FALSE);
WITH PurchHeader DO BEGIN
  OutboxTransaction.INIT;
  OutboxTransaction."Transaction No." := TransactionNo;
  OutboxTransaction."IC Partner Code" := Vendor."IC Partner Code";
  OutboxTransaction."Source Type" := OutboxTransaction."Source Type"::"Purchase Document";
  CASE "Document Type" OF
    "Document Type"::Order:
      OutboxTransaction."Document Type" := OutboxTransaction."Document Type"::Order;
    "Document Type"::Invoice:
      OutboxTransaction."Document Type" := OutboxTransaction."Document Type"::Invoice;
    "Document Type"::"Credit Memo":
      OutboxTransaction."Document Type" := OutboxTransaction."Document Type"::"Credit Memo";
    "Document Type"::"Return Order":
      OutboxTransaction."Document Type" := OutboxTransaction."Document Type"::"Return Order";
  END;
  OutboxTransaction."Document No." := "No.";
  OutboxTransaction."Posting Date" := "Posting Date";
  OutboxTransaction."Document Date" := "Document Date";
  IF Rejection THEN
    OutboxTransaction."Transaction Source" := OutboxTransaction."Transaction Source"::"Rejected by Current Company"
  ELSE
    OutboxTransaction."Transaction Source" := OutboxTransaction."Transaction Source"::"Created by Current Company";
  OutboxTransaction.INSERT;
END;
ICOutBoxPurchHeader.TRANSFERFIELDS(PurchHeader);
OnAfterICOutBoxPurchHeaderTransferFieldsFromPurchHeader(ICOutBoxSalesHeader,PurchHeader);  <-- new event Trigger
ICOutBoxPurchHeader."IC Transaction No." := OutboxTransaction."Transaction No.";

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
