### ISSUE TITLE
Breaking changes, missing tables?

### ISSUE THREAD

**Issue by janrik** [microsoft/ALAppExtensions#3911]
Good day,

with the exception of table TemplBlob, I could not find a mention in the "breaking changes" document for the following objects, which seem to be missing in version 15.0 (docker-inside-preview).

- Table AbllObjWithCaption,
- Table 'Table Metadata'
- Table Record Link
- Table Date
- Table Integer
- Table Windows Language
- Table Object
- Table Active Session
- Table Profile
- Table User
- Codeunit TextManagement

We are using all of these in our extensions - how are we supposed to rebuild all the functionality if these are indeed missing?

**Comment by janrik** [comment]
- Page Session List also missing
- Record "Record Link" is missing, but I still get a separate error from the variable pointing to it, saying "Field 'URL1' is removed. Reason 'URL' was introduced."

**Comment by atoader** [comment]
@janrik what do you mean these tables are removed ? At what package are you looking?

**Comment by janrik** [comment]
@atoader Good day and thank you for your reply.

I am trying to compile an extension, with app.json parameters target=Cloud and runtime=4.0. I have the following dependencies defined
        "appId" : "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
        "name" : "System Application","publisher" : "Microsoft","version" : "15.0.0.0"
        "appId" : "437dbf0e-84ff-417a-965d-ed2bb9650972",
        "name" : "BaseApp","publisher" : "Microsoft","version" : "15.0.0.0"

The symbols are downloaded fine, files:
Microsoft_BaseApp_15.0.35473.0.app
Microsoft_System Application_15.0.35473.0.app

But VS Code tells me the tables/objects I listed previously do not exist. Am I missing something?

**Comment by atoader** [comment]
Have you added a dependency on the platform?
```
{
    "id":  "3f63a3de-6597-4097-9f34-b0ff7f92e6b0",
    "name":  "DemoTool",
    "publisher":  "Microsoft",
    "version":  "15.0.0.0",
    "platform":  "15.0.0.0",
    "target":  "OnPrem",
    "dependencies":  [
                         {
                             "appId":  "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
                             "name":  "System Application",
                             "publisher":  "Microsoft",
                             "version":  "15.0.0.0"
                         },
                         {
                             "appId":  "437dbf0e-84ff-417a-965d-ed2bb9650972",
                             "name":  "BaseApp",
                             "publisher":  "Microsoft",
                             "version":  "15.0.0.0"
                         }
                     ],
    "showMyCode":  true
}

```

The tables you are talking about are system tables and they are part of the "System.app" package which is different from the "System Application.app" package. To have the "System.app" package downloaded you need to specify the "platform" property in your app.json

**Comment by janrik** [comment]
Ok, thank you, I'll pull the newest docker and try. I was under the impression that application and platform -parameters could be left out. So now we have one extra version and dependency to maintain in every extensions app.json - instead of application&platform, we now have platform, system application and baseapp?

**Comment by atoader** [comment]
The application parameter can be left out because it has been replaced by 2 real AL applications, the BaseApp (soon to be renamed to Base Application) and the System Application, but the platform property is still there.

I will close this issue. Please let me know if you encounter any other issue.

**Comment by janrik** [comment]
Hello again,

I pulled the newest bcsandbox-master:fi-ltsc2019. Extension BaseApp does not exist.

It has apparently been renamed to "Base Application" (I just noticed you wrote this as well). Could you please stop making undocumented changes like this that break existing solutions? :/

Original problem was solved, thank you. But I doubt changes like these are more important than all the wasted time of all partners refactoring their solutions. Hopefully the amount of breaking changes will diminish radically.
