### ISSUE TITLE
[Event Request] Codeunit 427 OnBeforeSalesHeaderFromICInboxSalesHeader

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#3912]
In codeunit 427 in procedure CreateSalesDocument and CreatePurchDocument we Need a new Event trigger to modify the Sales/Purchase Header fields:

[External] CreateSalesDocument(ICInboxSalesHeader : Record "IC Inbox Sales Header";ReplacePostingDate : Boolean;PostingDate : Date)
IsHandled := FALSE;
OnBeforeCreateSalesDocument(ICInboxSalesHeader,ReplacePostingDate,PostingDate,IsHandled);
IF IsHandled THEN
  EXIT;

WITH ICInboxSalesHeader DO BEGIN
  SalesHeader.INIT;
  …
  SalesHeader."Dimension Set ID" :=
    DimMgt.GetCombinedDimensionSetID(DimensionSetIDArr,
      SalesHeader."Shortcut Dimension 1 Code",SalesHeader."Shortcut Dimension 2 Code");
  DimMgt.UpdateGlobalDimFromDimSetID(SalesHeader."Dimension Set ID",SalesHeader."Shortcut Dimension 1 Code",
    SalesHeader."Shortcut Dimension 2 Code");
  OnBeforeSalesHeaderFromICInboxSalesHeader(VAR SalesHeader;ICInboxSalesHeader);  <-- new event trigger
  SalesHeader.MODIFY;

[External] CreatePurchDocument(ICInboxPurchHeader : Record "IC Inbox Purchase Header";ReplacePostingDate : Boolean;PostingDate : Date)
WITH ICInboxPurchHeader DO BEGIN
  PurchHeader.INIT;
  PurchHeader."No." := '';
  …
  PurchHeader."Dimension Set ID" :=
    DimMgt.GetCombinedDimensionSetID(DimensionSetIDArr,
      PurchHeader."Shortcut Dimension 1 Code",PurchHeader."Shortcut Dimension 2 Code");
  DimMgt.UpdateGlobalDimFromDimSetID(PurchHeader."Dimension Set ID",PurchHeader."Shortcut Dimension 1 Code",
    PurchHeader."Shortcut Dimension 2 Code");
  OnBeforePurchHeaderFromICInboxPurchHeader(VAR PurchHeader;ICInboxPurchHeader);  <-- new event trigger
  PurchHeader.MODIFY;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
