### ISSUE TITLE
[Event Request] Codeunit 1314 OnCreatePurchaseHeaderOnBeforeInit

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#3913]
we Need a new Event trigger OnCreatePurchaseHeaderOnBeforeInit in codeunit 1314 in procedure CreatePurchaseHeader

LOCAL CreatePurchaseHeader(VAR PurchaseHeader : Record "Purchase Header";SalesHeader : Record "Sales Header";Vendor : Record Vendor)
PurchaseHeader.INIT;

IF SalesHeader."Document Type" IN [SalesHeader."Document Type"::Invoice,SalesHeader."Document Type"::Order] THEN
  PurchaseHeader.VALIDATE("Document Type",PurchaseHeader."Document Type"::Invoice)
ELSE
  ERROR(TypeNotSupportedErr,FORMAT(SalesHeader."Document Type"));

OnCreatePurchaseHeaderOnBeforeInit(VAR PurchaseHeader,SalesHeader);  // <-- new Event Trigger
PurchaseHeader.InitRecord;
PurchaseHeader.VALIDATE("Buy-from Vendor No.",Vendor."No.");
OnCreatePurchaseHeaderOnBeforeInsert(PurchaseHeader,SalesHeader,Vendor);
PurchaseHeader.INSERT(TRUE);

**Comment by AlexanderYakunin** [comment]
Already exist
OnBeforeInitRecord(PurchaseHeader,SalesHeader,Vendor);
PurchaseHeader.InitRecord;
PurchaseHeader.VALIDATE("Buy-from Vendor No.",Vendor."No.");
