### ISSUE TITLE
[Event Request] Table 5902 - OnBeforeCopyFromServItem()

### ISSUE THREAD

**Issue by CptBlaubart** [microsoft/ALAppExtensions#3918]
We'd like to skip a few dialogues based on settings in our extension. Unfortunately the "HideReplacementDialog"-boolean is not readable. So we can't reliably set and reset it correctly. Because it would be bad design anyway. We'd prefer to have a proper "IsHandled" event.

Please add the following event:
``` AL-Language

    [BusinessEvent(false)]
    local procedure OnBeforeCopyFromServItem(VAR ServiceLine : Record "Service Line";ServiceItem : Record "Service Item";ServiceItemComp : Record "Service Item Component";var IsHandled: Boolean)
    begin
    end;
```

And implement it like this:
```AL-Language
    local procedure CopyFromServItem()
    var
        ServItem2: Record "Service Item";
        ServItemComponent: Record "Service Item Component";
+       IsHandled: Boolean;
    begin
+       OnBeforeCopyFromServItem(Rec, SalesLine, ServItem2, ServItemComponent, IsHandled);
+       if IsHandled then
+           exit;
        if ServItem."Item No." = "No." then begin
          ServItemLine.Reset;
          if not HideReplacementDialog then begin
            ReplaceServItemAction := ReplaceServItem;
            if not ReplaceServItemAction then
              exit;
          end;
        end else begin
        ...
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by CptBlaubart** [comment]
Soooo, I assume this didn't make it into the Fall release 2019? - Most of our existing Customers are reluctant to give away their hosting. So we're kinda bound to develop our solution packages for the OnPrem releases. :-/
