### ISSUE TITLE
[Event Duplicate] Codeunit 5750 Whse.-Create Source Document - OnFromPurchLine2ShptLineOnBeforeCreateShptLine

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#3923]
Hi AL-team,

in function FromPurchLine2ShptLine a event publisher has been implemented twice:

![image](https://user-images.githubusercontent.com/47382840/63696187-70484480-c81a-11e9-961e-f9381eb9de6d.png)

I think the publisher "OnFromPurchLine2ShptLineOnBeforeCreateShptLine" could be deleted.

**Comment by AlexanderYakunin** [comment]
No, we cannot delete any event, this is breaking change
