### ISSUE TITLE
[Event Request] Codeunit 7000 - Change Line Discount

### ISSUE THREAD

**Issue by xgaronnat** [Microsoft/ALAppExtensions#393]
Hi,

Coud it be possible to modify line discounts content in FindSalesLineDisc() with a new event that should allow partners to change the discounts lines based on criteria coming from the original context (Sales Line, Service Line... etc implemented with RecRefDocLine parameter)

`AddAdditionnalLineDisc(FromSalesLineDisc,ToSalesLineDisc,DocLineRecRef,CustNo,ContNo,CustDiscGrCode,CampaignNo,ItemNo,ItemDiscGrCode,VariantCode,UOM,CurrencyCode,StartingDate,ShowAll);
`
![image](https://user-images.githubusercontent.com/7318801/48704474-eddd8500-ebf6-11e8-9be9-8a63e09ac108.png)

Thanks,
Xavier.

**Comment by AlexanderYakunin** [comment]
We already have many events in COD7000, can you please review it before asking for new one. Seems existing events can do this.

**Comment by xgaronnat** [comment]
Hi,
Sure but the problem is that the FindSalesLineDisc() dot not allow to go back to the Sales (or Service) Line source record.
Best regards,
Xavier.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply. Kindly open a new issue, if you still have unresolved problems. We will then look into it once more. Thanks!
