### ISSUE TITLE
codeunit 7322 “Create Inventory Pick/Movement”, Code [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3937]
Please add a new publisher event OnBeforeCreatePickOrMove in Codeunit 7322 on function Code and call it at the end of the function.

![2019-08-27 09_36_58-Codeunit 6036600 added publisher (Post on git) pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63750714-47718f00-c8ae-11e9-979d-4234dd3bbcf8.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![2019-08-27 09_37_08-Codeunit 6036600 added publisher (Post on git) pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63750717-49d3e900-c8ae-11e9-8e01-5c6a1ac5b48b.png)

**Comment by TjaTrimit** [comment]
What is the status on this request? @AlexanderYakunin

**Comment by AlexanderYakunin** [comment]
We already have this event

        if not HideDialog then
            if not GetWhseRequest(WhseRequest) then
                exit;

        IsHandled := false;
        OnBeforeCreatePickOrMoveLines(WhseRequest, WhseActivHeader, LineCreated, IsHandled);
        if IsHandled then
            exit;

        GetSourceDocHeader;
        UpdateWhseActivHeader(WhseRequest);

        case WhseRequest."Source Document" of
