### ISSUE TITLE
[EventRequest] codeunit 7324 “Whse.-Activity-Post”, UpdateSourceDocument[Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#3952]
Please add a new publisher event OnUpdateSourceDocumentOnAfterGetPurchaseLine in Codeunit 7324 on function UpdateSourceDocument and call as shown in the image below

![2019-08-27 10_25_44-Codeunit 6036600 added publisher (Post on git) pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63754465-3b3d0000-c8b5-11e9-9353-229c4c6ba85f.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![2019-08-27 10_25_49-Codeunit 6036600 added publisher (Post on git) pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63754471-3d9f5a00-c8b5-11e9-88d4-d9b820af28c1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
