### ISSUE TITLE
Codeunit 7312 and 7313 OnBeforeWhseActivHeaderInsert

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#3954]
we Need to set 2 individual fields in OnBeforeWhseActivHeaderInsert in codeunit 7312 which are both Code10 fields. Those values for the new WhseActivHeader are set via external function SetValues - but SetValues is not able to submit individual fields.

So either OnBeforeWhseActivHeaderInsert gets global var Access or is there any other possibility to fill any individual record and submit for using in OnBeforeWhseActivHeaderInsert  ?

**Comment by AlexanderYakunin** [comment]
No GlobalVarAccess anymore. Which fields do you need here?

**Comment by GuntherGebauer** [comment]
As mentioned above in CreateWhseActivHeader we Need two Code10 individual fields WhseActivHeader."Document Category Code" and WhseActivHeader."Equipment Group Code" to be set.
As CU7312/7313 are called from Reports 5754,7305 and 7318 actually we deliver those values within those Reports for CU7312 and 7313. But now those values cannot be set anymore to WhseActivHeader in CU7312 and 7313.
Is there a better technique to deliver those values from those report to the new created WarehouseActivityHeader ? (as BC365 works as well with e.g. CreatePutAway.SetValues to set those values for CU7312/7313)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
