### ISSUE TITLE
[EventRequest] codeunit 427 “Copy Document Mgt.”, OutboxSalesLineToInbox[local]

### ISSUE THREAD

**Issue by jenniferdellarocca** [microsoft/ALAppExtensions#3966]
Please add a new publisher event OnBeforeInsertICInboxPurchLine in Codeunit 427 on function OutboxSalesLineToInbox and call it as shown in the image below:
![image](https://user-images.githubusercontent.com/54579270/63764716-bc9d8e00-c8c7-11e9-83ad-23dda6ec7c99.png)

Please add the corresponding Integration Event In the bottom of the codeunit
![image](https://user-images.githubusercontent.com/54579270/63764732-c45d3280-c8c7-11e9-9696-24b3f205d3da.png)

**Comment by AlexanderYakunin** [comment]
Already exists
  OnBeforeICInboxPurchLineInsert(ICInboxPurchLine,ICOutboxSalesLine);
  INSERT;
  OnAfterICInboxPurchLineInsert(ICInboxPurchLine,ICOutboxSalesLine);
