### ISSUE TITLE
[EventRequest] codeunit 427 “Copy Document Mgt.”, OutboxPurchLineToInbox[local]

### ISSUE THREAD

**Issue by jenniferdellarocca** [microsoft/ALAppExtensions#3967]
Please add a new publisher event OnBeforeInsertICInboxSalesLine in Codeunit 427 on function OutboxPurchLineToInbox and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/54579270/63764947-43eb0180-c8c8-11e9-8134-685bfabad38a.png)

Please add the corresponding Integration Event in the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54579270/63765102-9cba9a00-c8c8-11e9-9425-26f957ec6201.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
