### ISSUE TITLE
[Event Request] Codeunit 7324 OnBeforeTempWhseActivLineModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#3968]
we Need a new Event trigger OnBeforeTempWhseActivLineModify in codeunit 7324 in procedure InsertTempWhseActivLine:

LOCAL InsertTempWhseActivLine(WhseActivLine : Record "Warehouse Activity Line";ItemTrackingRequired : Boolean)
OnBeforeInsertTempWhseActivLine(WhseActivLine,ItemTrackingRequired);

WITH WhseActivLine DO BEGIN
  TempWhseActivLine.SetSourceFilter(
    "Source Type","Source Subtype","Source No.","Source Line No.","Source Subline No.",FALSE);
  IF TempWhseActivLine.FIND('-') THEN BEGIN
    TempWhseActivLine."Qty. to Handle" += "Qty. to Handle";
    TempWhseActivLine."Qty. to Handle (Base)" += "Qty. to Handle (Base)";
    //++++++++++++++++++++++
    OnBeforeTempWhseActivLineModify(VAR TempWhseActivLine,WhseActivLine);
    //----------------------
    TempWhseActivLine.MODIFY;
  END ELSE BEGIN
    TempWhseActivLine.INIT;
    TempWhseActivLine := WhseActivLine;
    OnBeforeTempWhseActivLineInsert(TempWhseActivLine,WhseActivLine);
    TempWhseActivLine.INSERT;
    IF ItemTrackingRequired AND
       ("Activity Type" IN ["Activity Type"::"Invt. Pick","Activity Type"::"Invt. Put-away"])
    THEN
      ItemTrackingMgt.SynchronizeWhseActivItemTrkg(WhseActivLine);
  END;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
