### ISSUE TITLE
[Event Request] Codeunit 90 - Purch.-Post

### ISSUE THREAD

**Issue by frivadulla** [Microsoft/ALAppExtensions#397]
Hello!!

It would be wonderful to have this event:
`
LOCAL [IntegrationEvent] AfterRoundAmountsWithCurrency(VAR pCurrExchRate : Record "Currency Exchange Rate";VAR pPurchLine : Record "Purchase Line";VAR pPurchHeader : Record "Purchase Header";VAR pTotalPurchLine : Record "Purchase Line";VAR pTotalPurchLineLCY : Record "Purchase Line", VAR pUsedate : Date)`

Located inside the function **RoundAmount**  :

```
.
.
.
          TotalPurchLine."VAT Difference",PurchHeader."Currency Factor")) -
      TotalPurchLineLCY."VAT Difference";
    "Pmt. Disc. Rcd. Amount" :=
      ROUND(
        CurrExchRate.ExchangeAmtFCYToLCY(
          Usedate,PurchHeader."Currency Code",
          TotalPurchLine."Pmt. Disc. Rcd. Amount",PurchHeader."Currency Factor")) -
      TotalPurchLineLCY."Pmt. Disc. Rcd. Amount";

    _//-- EVENTS--
    AfterRoundAmountsWithCurrency(CurrExchRate, PurchLine, PurchHeader, TotalPurchLine, TotalPurchLineLCY, Usedate);
    //++ EVENTS++_
  END;
  IncrAmount(PurchHeader,PurchLine,TotalPurchLineLCY);
  Increment(TotalPurchLineLCY."Unit Cost (LCY)",ROUND(PurchLineQty * "Unit Cost (LCY)"));
END;
.
.
.
```

Thanks in advance!!!

**Comment by AlexanderYakunin** [comment]
Events in RoundAmount already exists

**Comment by frivadulla** [comment]
> 
> 
> Events in RoundAmount already exists

Checked in daily build and the event is there. Sorry for inconvenience!!!
