### ISSUE TITLE
[EventRequest] codeunit 5763 “Whse.-Post Shipment”, PostSourceDocument[local]

### ISSUE THREAD

**Issue by jenniferdellarocca** [microsoft/ALAppExtensions#3973]
Please add a new publisher event OnPostSourceDocumentOnBeforePrintTransferShipment in Codeunit 5763 on function PostSourceDocument and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/54579270/63765743-fc657500-c8c9-11e9-9d08-affec8c07db4.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54579270/63765929-61b96600-c8ca-11e9-872a-b7ce2938e413.png)

**Comment by Enomis82** [comment]
Any news about this request? The same code it's already implemented in Sales and Purchase

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
