### ISSUE TITLE
[EventRequest]Table 270 Bank Account

### ISSUE THREAD

**Issue by BenjaminHochstetter** [Microsoft/ALAppExtensions#398]
Please add an Event to function
"    LOCAL PROCEDURE IsContactUpdateNeeded@49() : Boolean;"
overwrite if an update is necessary:
...
  // MML00001835 +++
  OnAfterIsUpdateNeeded...(xRec, Rec, UpdateNeeded)
  // MML00001835 ---

**Comment by rvanbekkum** [comment]
Shouldn't this event be named `OnBeforeIsContactUpdateNeeded(Rec, xRec, UpdateNeeded)` to be in line with the other tables that implement this event, like T18, T23?
