### ISSUE TITLE
[EventRequest] codeunit 80 “Sales-Post”, PostPayment[local]

### ISSUE THREAD

**Issue by jenniferdellarocca** [microsoft/ALAppExtensions#3987]
Please add a new publisher event OnBeforePostPayment in Codeunit 80 on function PostPayment and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/54579270/63776203-2e360600-c8e1-11e9-97fe-5a685db2e19b.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54579270/63776318-748b6500-c8e1-11e9-97bd-afb032ca9861.png)

**Comment by AlexanderYakunin** [comment]
I cannot find PostPayment in W1, which country is this?

**Comment by jenniferdellarocca** [comment]
The country is Italy (IT)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
