### ISSUE TITLE
Codeunit 5530 GetDocumentEntries scope change

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#3989]
Dear Development Team,

We would like to request to change the scope of the `GetDocumentEntries` function in Codeunit 5530 "Calc. Item Availability" from Local to Global.

![image](https://user-images.githubusercontent.com/39408604/63776510-76512a80-c8d9-11e9-8f7a-c8590af67866.png)

Cheers,
Marton

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
