### ISSUE TITLE
[Event Request] Table 39 Purchase Line – Description – OnValidate

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#3995]
Event Request] Table 39 Purchase Line – Description – OnValidate

Could we please have a publisher OnBeforeValidateDescriptionWithHandled in function Description – OnValidate() of Table 39 Purchase Line?

```
trigger OnValidate()
var
    Item: Record Item;
    ApplicationAreaMgmtFacade: Codeunit "Application Area Mgmt. Facade";
    FindRecordMgt: Codeunit "Find Record Management";
    ConfirmManagement: Codeunit "Confirm Management";
    ReturnValue: Text[50];
    DescriptionIsNo: Boolean;
    IsHandled: Boolean;
begin
    // >>>>
    IsHandled := false;
    OnBeforeValidateDescriptionWithHandled(var Rec, xRec, var IsHandled);
    if IsHandled then
        exit;
    // <<<<
    if Type = Type::" " then
        exit;

    if ("No." <> '') and (Type in [Type::Item, Type::"Charge (Item)"]) then begin
        case Type of
            Type::Item:
                begin
                    if (StrLen(Description) <= MaxStrLen(Item."No.")) and ("No." <> '') then
                        DescriptionIsNo := Item.Get(Description)
                    else
                        DescriptionIsNo := false;

                    if not DescriptionIsNo then begin

```

**Comment by AlexanderYakunin** [comment]
This search by description functionality fixed, probably you don't need to disable it anymore

**Comment by ttaeufer** [comment]
Unfortunately, it's not just about the fix. We also have to deactivate the functionality due to our business logic like in table 37-„Sales Line.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
