### ISSUE TITLE
[EventRequest] Codeunit 99000773 “Calculate Prod. Order”, TransferBOMProcessItem[local]

### ISSUE THREAD

**Issue by jenniferdellarocca** [microsoft/ALAppExtensions#3997]
Please add a new publisher event OnAfterInsertProdOrderCompLine in Codeunit 99000773 on function TransferBOMProcessItem and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/54579270/63782914-6abb2f00-c8ec-11e9-9242-7a6671d90240.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54579270/63783048-9dfdbe00-c8ec-11e9-91c0-278c93a92c5d.png)

**Comment by AlexanderYakunin** [comment]
This event already exist
  OnAfterProdOrderCompInsert(ProdOrderComp,ProdBOMLine[Level]);
