### ISSUE TITLE
[Event Request] Report 5753 OnSalesLineAfterCreateRcptHeader

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4003]
In Report 5753 we Need several new Event trigger:

Sales Line - OnAfterGetRecord()
VerifyItemNotBlocked("No.");
IF "Location Code" = "Warehouse Request"."Location Code" THEN
  CASE RequestType OF
    RequestType::Receive:
      IF WhseActivityCreate.CheckIfSalesLine2ReceiptLine("Sales Line") THEN BEGIN
        OnSalesLineOnAfterGetRecordOnBeforeCreateRcptHeader(
          "Sales Line","Warehouse Request",WhseReceiptHeader,WhseHeaderCreated,OneHeaderCreated);
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
          CreateReceiptHeader;

        //+++++++++++++++++++++++++++++++
        OnSalesLineAfterCreateRcptHeader(VAR WhseReceiptHeader,WhseHeaderCreated,"Sales Header");
        //-------------------------------

        IF NOT WhseActivityCreate.SalesLine2ReceiptLine(WhseReceiptHeader,"Sales Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
    RequestType::Ship:
      IF WhseActivityCreate.CheckIfFromSalesLine2ShptLine("Sales Line") THEN BEGIN
        IF Cust.Blocked <> Cust.Blocked::" " THEN BEGIN
          IF NOT SalesHeaderCounted THEN BEGIN
            SkippedSourceDoc += 1;
            SalesHeaderCounted := TRUE;
          END;
          CurrReport.SKIP;
        END;
        OnSalesLineOnAfterGetRecordOnBeforeCreateShptHeader(
          "Sales Line","Warehouse Request",WhseShptHeader,WhseHeaderCreated,OneHeaderCreated);
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
          CreateShptHeader;

        //+++++++++++++++++++++++++++++++
        OnSalesLineAfterCreateShptHeader(VAR WhseShptHeader,WhseHeaderCreated,"Sales Header");
        //-------------------------------

        IF NOT WhseActivityCreate.FromSalesLine2ShptLine(WhseShptHeader,"Sales Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
  END;

Purchase Line - OnAfterGetRecord()
VerifyItemNotBlocked("No.");
IF "Location Code" = "Warehouse Request"."Location Code" THEN
  CASE RequestType OF
    RequestType::Receive:
      IF WhseActivityCreate.CheckIfPurchLine2ReceiptLine("Purchase Line") THEN BEGIN
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
          CreateReceiptHeader;

        //+++++++++++++++++++++++++++++++
        OnPurchLineAfterCreateRcptHeader(VAR WhseReceiptHeader,WhseHeaderCreated,"Purchase Header");
        //-------------------------------

        IF NOT WhseActivityCreate.PurchLine2ReceiptLine(WhseReceiptHeader,"Purchase Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
    RequestType::Ship:
      IF WhseActivityCreate.CheckIfFromPurchLine2ShptLine("Purchase Line") THEN BEGIN
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
          CreateShptHeader;

        //+++++++++++++++++++++++++++++++
        OnPurchLineAfterCreateShptHeader(VAR WhseShptHeader,WhseHeaderCreated,"Purchase Header");
        //-------------------------------

        IF NOT WhseActivityCreate.FromPurchLine2ShptLine(WhseShptHeader,"Purchase Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
  END;

Transfer Line - OnAfterGetRecord()
CASE RequestType OF
  RequestType::Receive:
    IF WhseActivityCreate.CheckIfTransLine2ReceiptLine("Transfer Line") THEN BEGIN
      OnTransferLineOnAfterGetRecordOnBeforeCreateRcptHeader(
        "Transfer Line","Warehouse Request",WhseReceiptHeader,WhseHeaderCreated,OneHeaderCreated);
      IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
        CreateReceiptHeader;

      //+++++++++++++++++++++++++++++++
      OnTransLineAfterCreateRcptHeader(VAR WhseReceiptHeader,WhseHeaderCreated,"Transfer Header");
      //-------------------------------

      IF NOT WhseActivityCreate.TransLine2ReceiptLine(WhseReceiptHeader,"Transfer Line") THEN
        ErrorOccured := TRUE;
      LineCreated := TRUE;
    END;
  RequestType::Ship:
    IF WhseActivityCreate.CheckIfFromTransLine2ShptLine("Transfer Line") THEN BEGIN
      OnTransferLineOnAfterGetRecordOnBeforeCreateShptHeader(
        "Transfer Line","Warehouse Request",WhseShptHeader,WhseHeaderCreated,OneHeaderCreated);
      IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
        CreateShptHeader;

      //+++++++++++++++++++++++++++++++
      OnTransLineAfterCreateShptHeader(VAR WhseShptHeader,WhseHeaderCreated,"Transfer Header");
      //-------------------------------

      IF NOT WhseActivityCreate.FromTransLine2ShptLine(WhseShptHeader,"Transfer Line") THEN
        ErrorOccured := TRUE;
      LineCreated := TRUE;
    END;
END;

**Comment by AlexanderYakunin** [comment]
We already have OnAfterCreateRcptHeader event (and same for other cases), why you cannot use it?

**Comment by GuntherGebauer** [comment]
OnBeforeWhseReceiptHeaderInsert and OnAfterCreateRcptHeader inside Procedure CreateReceiptHeader does not know and do not deliver the source from where the WhseReceiptHeader is created, e.g. the SalesHeader, the TransHeader and the PurchHeader.
We Need fields from those headers to add to WhseReceiptHeader´.

So no, we cannot use the existing triggers for our Purpose.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
