### ISSUE TITLE
Please make all public functions in "Intrastat Jnl. Line" EXTERNAL

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/ALAppExtensions#401]
In order to activate external creation of Intrastat Journal Lines, please make all public procedures also EXTERNAL.
Especially the following:
* CalcStartEndDate
* GetIntrastatCountryCode
* ValidateSourceEntryNo
* FindSourceCurrency
* SetVATEntryFilters
* ClearFieldValues
* SetIntrastatJnlBatchFilters
* CalcTotalWeight

**Comment by JesperSchulz** [comment]
I assume this is for the IT version only?

**Comment by ThomasBrodkorb** [comment]
Well, I did not check in other country versions yet (even though the INTRASTAT is wrong at least in AT version as well).
In this case, the request is for the IT version only (if those functions are IT specific).
