### ISSUE TITLE
Procedure InsertForExtension is Missing in Manual Setup

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#4010]
The [Refenced Procedure](https://github.com/microsoft/ALAppExtensions/blob/717ee9718de4bef65a941386f632cf5f7fc70244/AddOns/SalesAndInventoryForecast/app/src/Cod1850.SalesForecastHandler.al#L273) does not exist in the [Manual Setup Codeunit](https://github.com/microsoft/ALAppExtensions/blob/eba51324b45c26c474eeb925dd4c14137941e53d/Modules/System/Manual%20Setup/src/ManualSetup.Codeunit.al#L1).

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Thanks for reporting! We've fixed it! Have a lovely weekend.
