### ISSUE TITLE
[Event Request] Codeunit 427 ICInboxOutbox - SendSalesDoc

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#4011]
Please insert new Publisher in function SendSalesDoc

ICPartner.TESTFIELD(Blocked,FALSE);

// S/NEW
OnBeforeReleaseSalesDocument(VAR SalesHeader : Record "Sales Header";Post : Boolean);
// E/NEW

IF NOT Post THEN
  CODEUNIT.RUN(CODEUNIT::"Release Sales Document",SalesHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
