### ISSUE TITLE
[Event Request] Codeunit 427 ICInboxOutboxMgt - SendPurchDoc

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#4012]
Please insert new Publisher in function SendPurchDoc

ICPartner.TESTFIELD(Blocked,FALSE);

// S/NEW
OnBeforeReleasePurchDocument(VAR PurchHeader : Record "Purchase Header";Post : Boolean);
// E/NEW

IF NOT Post THEN
CODEUNIT.RUN(CODEUNIT::"Release Purchase Document",PurchHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
