### ISSUE TITLE
Codeunit 427 ICInboxOutboxMgt - CreateOutboxSalesInvTrans

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#4013]
Please Insert new Publisher in function CreateOutboxSalesInvTrans

UpdateICOutboxSalesLineReceiptShipment(ICOutBoxSalesLine,ICOutBoxSalesHeader);

// S/NEW
OnBeforeInsertICOutBoxSalesLine(VAR ICOutBoxSalesLine, SalesInvLine, 
 ICOutBoxSalesLine, ICOutBoxSalesHeader);
// E/NEW

INSERT(TRUE);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
