### ISSUE TITLE
Codeunit 427 ICInboxOutboxMgt - CreateOutboxSalesCrMemoTrans

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#4014]
Please Insert new Publisher in function CreateOutboxSalesCrMemoTrans

UpdateICOutboxSalesLineReceiptShipment(ICOutBoxSalesLine,ICOutBoxSalesHeader);

// S/NEW
OnBeforeInsertICOutBoxSalesLine(VAR ICOutBoxSalesLine, SalesCrMemoLine,
ICOutBoxSalesLine, ICOutBoxSalesHeader);
// E/NEW

INSERT(TRUE);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
