### ISSUE TITLE
[EventRequest] OnBeforeLookup in T37 Sales - and T39 Purchase Line

### ISSUE THREAD

**Issue by MisterTrojan** [microsoft/ALAppExtensions#4015]
Heyy,

i need Event to be able to handle Lookup by my own.
Eg. if I don't want the lookup to be able to run.

I need this Events on all used Table "Lookup" Trigger in "Sales Line" and "Purchase Line".
If you also can create These Events for all the Sales and purchase page it would be more than perfect :)

Maybe also for "Sales Header" and "Purchase Header".

If it's possible please create it with a Handled Param.

**Comment by AlexanderYakunin** [comment]
We do not accept this kind of event requests, please be specific and request events you need with name, list of parameters and placement in the code.

**Comment by MisterTrojan** [comment]
**Event**
OnBeforeLookup[Fieldname](Rec,LookupHandled)
if LookupHandled then
   Exit;


**Placements**
I would this for the fields, were a lookup is coded.
Sales Line:
- Appl.-to Item Entry
- Blanket Order No.
- Blanket Order Line No.
- Bin Code
- Cross-Reference No.
- Appl.-from Item Entry

Purchase Line:
- Blanket Order No.
- Blanket Order Line No.
- Job Planning Line No.
- Bin Code
- Cross-Reference No.

Otherwise if you have the possibility to give us the OnLookup Trigger like you made the OnValidate OnBefore/OnAfter Trigger, this would be really exciting.

**Comment by StanPesotskiy** [comment]
Please provide the signature of the event along with the fragments of code that could define location of the event call unambiguously. 
The best way is to copy the actual AL code you would implement.
