### ISSUE TITLE
Page 160-161 Global Variables Issue

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#402]
Hello everyone!!

I was wondering if its possible to make the global variables "TotalSalesLine" and "TotalPurchLine" accesible from outside the page in order just to do something like the following
![evento_pagina161](https://user-images.githubusercontent.com/7207127/48896632-625b3280-ee48-11e8-8af8-642b1b2e80bd.JPG)

(No problem here if only the previous variables are accesible and not the "TotalAmount2" or "TotalAmount1" because these two ones are filled here:

```
IF "Prices Including VAT" THEN BEGIN
  TotalAmount2 := TotalPurchLine.Amount;
  TotalAmount1 := TotalAmount2 + VATAmount;
  TotalPurchLine."Line Amount" := TotalAmount1 + TotalPurchLine."Inv. Discount Amount"
    + TotalPurchLine."Pmt. Disc. Rcd. Amount";
END ELSE BEGIN
  TotalAmount1 := TotalPurchLine.Amount;
  TotalAmount2 := TotalPurchLine."Amount Including VAT";
END;
```

It´s not a big issue because this are only informative fields, but customers also demand those kind of things, so it would be nice to add information to this page in a simply way.

Kind regards!!!

**Comment by frivadulla** [comment]
Any notice on this??

**Comment by StanPesotskiy** [comment]
@frivadulla
 There is an event OnAfterCalculateTotals() that is called in the end of CalculateTotals(). 
`   OnAfterCalculateTotals(Rec,TotalPurchLine,TotalPurchLineLCY,TempVATAmountLine);
`
Would it be helpful if we include TotalAmount1 and TotalAmount2 as parameters by var?

**Comment by frivadulla** [comment]
> 
> 
> @frivadulla
> There is an event OnAfterCalculateTotals() that is called in the end of CalculateTotals().
> ` OnAfterCalculateTotals(Rec,TotalPurchLine,TotalPurchLineLCY,TempVATAmountLine);`
> Would it be helpful if we include TotalAmount1 and TotalAmount2 as parameters by var?

I think that should be ok for my functionality.

**Comment by frivadulla** [comment]
> 
> 
> @frivadulla
> There is an event OnAfterCalculateTotals() that is called in the end of CalculateTotals().
> ` OnAfterCalculateTotals(Rec,TotalPurchLine,TotalPurchLineLCY,TempVATAmountLine);`
> Would it be helpful if we include TotalAmount1 and TotalAmount2 as parameters by var?

is this confirmed to be done?

Thx and kind regards.

**Comment by StanPesotskiy** [comment]
yes, this is the call now:         
`OnAfterCalculateTotals(Rec, TotalPurchLine, TotalPurchLineLCY, TempVATAmountLine, TotalAmount1, TotalAmount2);`
