### ISSUE TITLE
[Event Request] Report 7315 OnBeforeAdjmtBinQuantityBufferModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4020]
In Report 7315 we Need a new Event trigger OnBeforeAdjmtBinQuantityBufferModify in DataItem Integer - OnAfterGetRecord():

Integer - OnAfterGetRecord()
WITH AdjmtBinQuantityBuffer DO BEGIN
  Location.RESET;
  Item.COPYFILTER("Location Filter",Location.Code);
  Location.SETRANGE("Directed Put-away and Pick",TRUE);
  IF Location.FINDSET THEN
    REPEAT
      WhseEntry.SETRANGE("Location Code",Location.Code);
      WhseEntry.SETRANGE("Bin Code",Location."Adjustment Bin Code");
      IF WhseEntry.FINDSET THEN
        REPEAT
          IF WhseEntry."Qty. (Base)" <> 0 THEN BEGIN
            RESET;
            SETRANGE("Item No.",WhseEntry."Item No.");
            SETRANGE("Variant Code",WhseEntry."Variant Code");
            SETRANGE("Location Code",WhseEntry."Location Code");
            SETRANGE("Bin Code",WhseEntry."Bin Code");
            SETRANGE("Unit of Measure Code",WhseEntry."Unit of Measure Code");
            IF WhseEntry."Lot No." <> '' THEN
              SETRANGE("Lot No.",WhseEntry."Lot No.");
            IF WhseEntry."Serial No." <> '' THEN
              SETRANGE("Serial No.",WhseEntry."Serial No.");
            IF FINDSET THEN BEGIN
              "Qty. to Handle (Base)" := "Qty. to Handle (Base)" + WhseEntry."Qty. (Base)";
              //++++++++++++++++++++++++++++++++
              OnBeforeAdjmtBinQuantityBufferModify(VAR AdjmtBinQuantityBuffer,WhseEntry);
              //--------------------------------
              MODIFY;
            END ELSE BEGIN
              INIT;
              "Item No." := WhseEntry."Item No.";
              "Variant Code" := WhseEntry."Variant Code";
              "Location Code" := WhseEntry."Location Code";
              "Bin Code" := WhseEntry."Bin Code";
              "Unit of Measure Code" := WhseEntry."Unit of Measure Code";
              "Base Unit of Measure" := Item."Base Unit of Measure";
              "Lot No." := WhseEntry."Lot No.";
              "Serial No." := WhseEntry."Serial No.";
              "Qty. to Handle (Base)" := WhseEntry."Qty. (Base)";
              "Qty. Outstanding (Base)" := WhseEntry."Qty. (Base)";
              OnBeforeAdjmtBinQuantityBufferInsert(AdjmtBinQuantityBuffer,WhseEntry);
              INSERT;
            END;
          END;
        UNTIL WhseEntry.NEXT = 0;
    UNTIL Location.NEXT = 0;

**Comment by AlexanderYakunin** [comment]
Seems this is code for 13.X, we do not accept event requests for this version. Anyway, this is already implemented in newer versions.
