### ISSUE TITLE
[EventRequest] Report 790 “Calculate Inventory”, InsertItemJnlLine[local]

### ISSUE THREAD

**Issue by jenniferdellarocca** [microsoft/ALAppExtensions#4035]
Please add a new publisher event OnBeforeInsertItemJnlLine in Report 790 on InsertItemJnlLine and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/54579270/63862443-e2e92980-c9ac-11e9-848a-7febe05f0def.png)

Please also add the corrisponding Integration Event at the bottom of the Report:

![image](https://user-images.githubusercontent.com/54579270/63862477-ef6d8200-c9ac-11e9-9fbf-afa8956921c5.png)

**Comment by AlexanderYakunin** [comment]
We already have it, please use latest version of code:
    INSERT(TRUE);
    OnAfterInsertItemJnlLine(ItemJnlLine);

**Comment by Enomis82** [comment]
We haven't accesso to variable QuantityOnHandBuffer, can you change firm of event?
