### ISSUE TITLE
[Event Request] OnBeforeCloseReservEntry

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#404]
To support migrating a NAV add-on to an extension/app...impossible without this change.

In codeunit 22, in the function ApplyItemLedgEntry, i need to add an additional TESTFIELD condition on the OldItemLedgEntry variable.  So, i would like a new event added right before the line:

ReservEngineMgt.CloseReservEntry(ReservEntry,FALSE,FALSE);

That passes the ItemJnlLine and OldItemLedgEntry variables in

**Comment by AlexanderYakunin** [comment]
We already have event OnApplyItemLedgEntryOnBeforeCloseReservEntry(OldItemLedgEntry,ItemJnlLine) here

**Comment by RHansenEpimatic** [comment]
Thanks Alexander.  I clearly have an old build of D365 BC as i don't see that event.  I'll look at getting a newer build...i was recently set up for the ready to go program on collaborate so i should have access there.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
