### ISSUE TITLE
Undocumented breaking changes CalenderMgt, System Indicator, codeunits..

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#4043]
Good day,

here are some of the undocumented breaking changes in 15.0.0.0 docker preview that I have found.

Please advise.

1. '"System Indicator"' does not contain a definition for 'Company+Database' / '"System Indicator"' does not contain a definition for 'Company'
2. 'Codeunit "Calendar Management"' does not contain a definition for 'CheckCustomizedDateStatus'
3. No overload for method CalendarMgt.'CheckDateStatus' takes 3 arguments
4. No overload for method CalendarMgt.'CustomizedChangesExist' takes 4 arguments
5. 'Codeunit "File Management"' does not contain a definition for 'IsWebClient'
6. 'Codeunit "Sales-Post Prepayments"' does not contain a definition for 'BuildInvLineBuffer2'
7. No overload for method SMTPMail.'CreateMessage' takes 6 arguments
8. SMTPMail.AddCC parameters changed
9. 'Codeunit "SMTP Mail"' does not contain a definition for 'TrySend'

**Comment by darjoo** [comment]
Hi @navdotnetreqs,

I've now updated the breaking changes document with all the errors you have listed.

**Comment by navdotnetreqs** [comment]
Thanks.
