### ISSUE TITLE
[EventRequest] CU6620 OnBeforeInsertToPurchLine Parameter

### ISSUE THREAD

**Issue by MisterTrojan** [microsoft/ALAppExtensions#4051]
Heyy,

please set the Parameters equal to the Sales Version OnBeforeInsertToSalesLine (eg. DocLineNo is missing atm)

**Comment by AlexanderYakunin** [comment]
They are exactly the same, please compare in latest version:

            OnBeforeInsertToPurchLine(
                ToPurchLine, FromPurchLine, FromPurchDocType, RecalculateLines, ToPurchHeader, DocLineNo, NextLineNo);
            OnBeforeInsertToSalesLine(
                ToSalesLine, FromSalesLine, FromSalesDocType, RecalculateLines, ToSalesHeader, DocLineNo, NextLineNo);
