### ISSUE TITLE
[Refactoring] Page 255 / Page 256

### ISSUE THREAD

**Issue by riki815** [microsoft/ALAppExtensions#4053]
Hello,

I'm referring to this version of Business Central: 14.0.29530.0

I have a problem with this two pages, 255 "Cash Receipt Journal" and 256 "Payment Journal", in the OnOpenPage trigger there is a condition that skip some methods if the page is opened from batch, but the method "SetDimensionsVisibility" must be executed anyway.

The code is correct for pages 253 and 254.

Page 253:
![253](https://user-images.githubusercontent.com/16220695/63945246-450c6200-ca73-11e9-8a1c-c2872365ad95.jpg)

Page 255:
![255](https://user-images.githubusercontent.com/16220695/63945259-4a69ac80-ca73-11e9-9540-8edf8700f57e.jpg)

Thanks, Riccardo.

**Comment by AlexanderYakunin** [comment]
This is already fixed

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
