### ISSUE TITLE
Install Extension in [AL] code

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/ALAppExtensions#4054]
I can't seem to find an external function to install/uninstall an extension (SAAS) in AL code.
The scenario is I have an extension which when a specific field is set, should install a second extension if published. Also the reverse, the ability to uninstall an extension as well.
Can the NavExtensionInstallationMgmt.InstallNavExtension(PackageID : GUID;Lcid : Integer) be made external, or is there another method of installing/uninstalling extensions via AL code.

**Comment by TimothyWatkins** [comment]
The obvious answer to this is, extensions can be installed using the Microsoft.NAV.Install/Uninstall API call externally. I understand the security concerns about installing extensions it in product, but I wonder whether logic dictates that installing an extension externally via API or directly from in product code should have the same security measures? Both methods are controlled by an "external source" which is not user...maybe using in product code could be forced to make sure the user has super access?

**Comment by StanPesotskiy** [comment]
Your request is not related to the AL **application** extensibility. 
Please post it at https://www.yammer.com/dynamicsnavdev/ where the wider community may give you a valid answer.
