### ISSUE TITLE
Exposing function GetApplicationAreaBuffer in CU 9178 Application Area Mgmt.

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#4057]
Hi,

Can you make function GetApplicationAreaBuffer in CU 9178 Application Area Mgmt. available externally or add function that calls it in CU 9179 Application Area Mgmt. Facade which will be available externally?

Thanks!

**Comment by grobyns** [comment]
Hi,

Application Area Buffer is an internal implementation. Exposing it will hinder future refactoring efforts. 
Please provide more info about why you need it and what you are trying to accomplish.

br/Gert
