### ISSUE TITLE
[Event Request] Table 7002 - OnValidateSalesCodeOnAfterGetCustomerPriceGroup

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#4058]
Please add a new integration event **OnValidateSalesCodeOnAfterGetCustomerPriceGroup** in **Table 7002**.

```
    { 2   ;   ;Sales Code          ;Code20        ;TableRelation=IF (Sales Type=CONST(Customer Price Group)) "Customer Price Group" ELSE IF (Sales Type=CONST(Customer)) Customer
ELSE IF (Sales Type=CONST(Campaign)) Campaign;
    OnValidate=BEGIN
      IF "Sales Code" <> '' THEN
        CASE "Sales Type" OF
          "Sales Type"::"All Customers":
            ERROR(Text001,FIELDCAPTION("Sales Code"));
          "Sales Type"::"Customer Price Group":
            BEGIN
              CustPriceGr.GET("Sales Code");                                                                        
+             OnValidateSalesCodeOnAfterGetCustomerPriceGroup(Rec,CustPriceGr);
              "Price Includes VAT" := CustPriceGr."Price Includes VAT";
              "VAT Bus. Posting Gr. (Price)" := CustPriceGr."VAT Bus. Posting Gr. (Price)";
              "Allow Line Disc." := CustPriceGr."Allow Line Disc.";
              "Allow Invoice Disc." := CustPriceGr."Allow Invoice Disc.";
            END;
            [...]
```

New integration event
```
[Integration]
LOCAL PROCEDURE OnValidateSalesCodeOnAfterGetCustomerPriceGroup@100000000(VAR SalesPrice@100000000 : Record 7002;CustomerPriceGroup@100000001 : Record 6);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
