### ISSUE TITLE
[Event Request] Table 82 - OnValidateType

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#4059]
Please add a new integration event **OnValidateType** in **Table 82**.

```
    { 9   ;   ;Type                ;Option        ;OnValidate=BEGIN
      "Test Report ID" := REPORT::"Inventory Posting - Test";
      "Posting Report ID" := REPORT::"Item Register - Quantity";
      "Whse. Register Report ID" := REPORT::"Warehouse Register - Quantity";
      SourceCodeSetup.GET;
      CASE Type OF
        [...]
+       ELSE
+         OnValidateType(Rec,SourceCodeSetup);
      END;
    [...]
```

New integration event
```
[Integration]
LOCAL PROCEDURE OnValidateType@100000000(VAR ItemJournalTemplate@100000000 : Record 82;VAR SourceCodeSetup@100000001 : Record 242);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
