### ISSUE TITLE
[Event Request]  New events for ApplyItemLedgEntry function

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#406]
To support migrating a NAV add-on to an extension/app...

In codeunit 22 in the function ApplyItemLedgEntry, I need a couple changes:

First, in the section for "IF UseReservationApplication..." I need to be able to add another TESTFIELD condition.  So, i would like a new event before the "ReservEngineMgt.CloseReservEntry..." line that passes the item ledger entry and the ItemJnlLine variables in.

Second, further down where the ItemLedgEntry2 variable is being filtered with a series of SETRANGE calls, I need to add another filter.  So, i would like a new event added that passes the ItemLedgEntry2 and ItemLedgEntry variables in...maybe "OnBeforeSetEntryFindMethod" right before the code that sets the EntryFindMethod to '+' or '-' depending on costing method.

**Comment by RHansenEpimatic** [comment]
Thanks again.  As per my other thread, i need to get the latest build so i'm seeing these newer events.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
