### ISSUE TITLE
Exposing function GetApplicationAreaSetupRec in CU 9178 Application Area Mgmt.

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#4064]
Hi,

Can you make function GetApplicationAreaSetupRec in CU 9178 Application Area Mgmt. available externally or add function that calls it in CU 9179 Application Area Mgmt. Facade which will be available externally?

Need this so I can find the proper Application Area Setup record for the user.

Thanks!

**Comment by grobyns** [comment]
Hi,

Application area setup per user or per profile is not supported. This was originally planned but never implemented.
Only application area setup per company is supported. You should use 'GetApplicationAreaSetupRecFromCompany' to get the correct setup record.

br/Gert

**Comment by zulezmaj** [comment]
> Hi,
> 
> Application area setup per user or per profile is not supported. This was originally planned but never implemented.
> Only application area setup per company is supported. You should use 'GetApplicationAreaSetupRecFromCompany' to get the correct setup record.
> 
> br/Gert

Hi Gert,

Then we were driven in wrong direction by design of table Application Area Setup and its usage in Codeunit Application Area Mgmt.:

![image](https://user-images.githubusercontent.com/40229810/64173384-714f2680-ce57-11e9-8296-f3d23c369baf.png)

These 3 fields are all part of PK and each of them can be omitted. So, that is why we thought that we can use this to provide more control regarding managing application areas to our clients.

Additionally, based on the picture given below we thought that highest rank (or hierarchy) has setup per user, then per profile and eventually per company. 

![image](https://user-images.githubusercontent.com/40229810/64173592-f1758c00-ce57-11e9-93f3-07f0df7b7edb.png)

Managing application areas per these 3 levels wasn't enough for us to cover all user cases, so we introduced additional setup where we are also controlling it per user group (if this setup is set for specific user group) and it comes on the top of it.

That's why I asked for function GetApplicationAreaBuffer to be exposed in #4057 for external usage, because then based on Application Area Setup record assigned to user when he/she logs in, by using function APPLICATIONAREA can enable or disable some application areas if there is record in that new table where we control this per user group.

**Comment by grobyns** [comment]
Hi,

Setting different application areas per user could lead to some users not being able to complete their tasks. It is one of the reasons why we chose not to support it. If you create setup records per user (or profile) the system should respect it though.

The application area buffer is only used to transpose the setup record to a list for display to the user. The application areas list was made non-editable as we did not want users to be able to edit the application areas in this way. Instead, we added the Experience Tier. An experience tier sets up a collection of application areas as on experience. The experience tier is selected per company so everyone in the company gets the same collection of application areas. You can customize the experience tier or add your own but you cannot define an experience tier per user. 

In your case, if you want to make application areas selectable per user, you would have to build your own setup and functions to manage it all and then simply read and write the application area setup for the specific users yourself. You shouldn't rely on our implementation anymore as we do not support setting application areas per user and we handle the ui of it through experience tiers, not application areas.

br/Gert

**Comment by zulezmaj** [comment]
Hi,

OK, then I will make our own setup for application areas, but can you please expose function GetApplicationAreaBuffer mentioned in #4057 anyway? Just one external function in Codeunit 9179 Application Area Mgmt. Facade which calls it will be enough.

I don't see that it is big work and can harm system anyhow, because it is just loading data into buffer table (temp record). Otherwise I will need to make my function which is just copy/paste of it. 

Thank you in advance,
Nemanja

**Comment by grobyns** [comment]
Hi,

Since you are building your own feature you are better off copying the logic and not using the application area buffer table at all. When we revisit this functionality and refactor the code we would break your solution. You should take as little dependency on our code as possible so that your code will continue to run even when we change the code on our side. 
The reason for having the facade codeunit is exactly that, to minimize the bits you are dependent on so we are free to change the underlying implementations.

br/Gert
