### ISSUE TITLE
[EventRequest] Report 790 “Calculate Inventory”, Item Ledger Entry -  OnAfterGetRecord()(Trigger)

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4067]
Please add a new publisher event OnAfterGetRecItemLedgerEntryBeforeBuffer in Report 790 on Trigger  Item Ledger Entry -  OnAfterGetRecord() and call it as shown in the image below

![image](https://user-images.githubusercontent.com/54017538/64095637-ab3d0180-cd5f-11e9-8767-7d0dfc679b7a.png)

Please add the corresponding Integration Event In the bottom of the Report

![image](https://user-images.githubusercontent.com/54017538/64095648-b3953c80-cd5f-11e9-9775-2d16946c4b0e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
