### ISSUE TITLE
[EventRequest] codeunit 7312 “Create Pick”, CalcTotalQtyAssgndOnWhse[local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4073]
Please add a new publisher event OnAfterCalcTotalQtyAssgndOnWhse in Codeunit 7312 on function CalcTotalQtyAssgndOnWhse and call it as shown in the image below

![image](https://user-images.githubusercontent.com/54017538/64096961-44b9e280-cd63-11e9-9151-74ffd721b3b8.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/64096971-4c798700-cd63-11e9-9cea-9e37208c43db.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
