### ISSUE TITLE
Warranty Date of items

### ISSUE THREAD

**Issue by developmentleasba** [microsoft/ALAppExtensions#4074]
Good morning from Spain,
We are Leasba Consulting S.L., Microsoft partners. We detected that when you take a lot of the table 338 to add it to the item tracking lines , this lot loses the **warranty date**. This happens in the product diaries when you add the lot for a component  of the production order. The only exception is in the reclassification diary where it does not lose the warranty date.
Is there a solution to this problem?
Regards!

**Comment by AlexanderYakunin** [comment]
Can you please create hotfix requests with repro steps via technical support. We do not process bugs here.
