### ISSUE TITLE
[EventRequest] Table 38 “Purchase header”, UpdateAllLineDim[External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4078]
Please add a new publisher event OnUpdateAllLineDimOnBeforeModifyPurchLine as shown in the picture below in the function UpdateAllLineDim in table 38

![image](https://user-images.githubusercontent.com/54017538/64098026-14c00e80-cd66-11e9-80c3-f8b3118bab64.png)

Please add the corresponding Integration Event In the bottom of the Codeunit.

![image](https://user-images.githubusercontent.com/54017538/64097996-f8bc6d00-cd65-11e9-84a7-5c6cf06ef726.png)

**Comment by AlexanderYakunin** [comment]
This event already exist
