### ISSUE TITLE
[Event Request] Codeunit 5940 ServContractManagement

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#4080]
Requesting 2 new event publisher in codeunit 5940 ServContractManagement

### Event 1 - OnAfterFilterServContractLine
`LOCAL [IntegrationEvent] OnAfterFilterServContractLine(VAR ServContractLine : Record "Service Contract Line";ContractNo : Code[20];ContractType : Option)`

### Code 1
```
LOCAL FilterServContractLine(VAR ServContractLine : Record "Service Contract Line";ContractNo : Code[20];ContractType : Option;LineNo : Integer)
ServContractLine.RESET;
ServContractLine.SETRANGE("Contract No.",ContractNo);
ServContractLine.SETRANGE("Contract Type",ContractType);
IF LineNo <> 0 THEN
  ServContractLine.SETRANGE("Line No.",LineNo);

>>> New Code
OnAfterFilterServContractLine(ServContractLine,ContractNo,ContractType);
<<< New Code End
```

### Event 2 - OnCreateAllServLinesOnAfterServContractLineSetFilters
`LOCAL [IntegrationEvent] OnCreateAllServLinesOnAfterServContractLineSetFilters(ServiceContractHeader : Record "Service Contract Header";VAR ServiceContractLine : Record "Service Contract Line")`

### Code 2
```
[External] CreateAllServLines(InvNo : Code[20];ServContractToInvoice : Record "Service Contract Header")
GetNextInvoicePeriod(ServContractToInvoice,InvoiceFrom,InvoiceTo);
WITH ServContractToInvoice DO BEGIN
  IF ServHeader.GET(ServHeader."Document Type"::Invoice,InvNo) THEN BEGIN
    ServContractLine.RESET;
    ServContractLine.SETRANGE("Contract Type","Contract Type");
    ServContractLine.SETRANGE("Contract No.","Contract No.");

    >>> New Code
    OnCreateAllServLinesOnAfterServContractLineSetFilters(ServContractToInvoice,ServContractLine);
    <<< New Code End

    IF NOT "Contract Lines on Invoice" THEN
      CreateHeadingServLine(ServHeader,"Contract Type","Contract No.");
    IF ServContractLine.FIND('-') THEN
.
.
.
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
