### ISSUE TITLE
Typo in procedurename 'GetDefautlTestRunner' in TestRunnerMgt.Codeunit.al

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4094]
Dear ALAppExtensions team,
I noticed there is a typo in file [TestRunnerMgt.Codeunit.al](https://github.com/microsoft/ALAppExtensions/blob/eba51324b45c26c474eeb925dd4c14137941e53d/Modules/DevTools/TestFramework/TestRunner/src/TestRunnerMgt.Codeunit.al).
Procedure `GetDefautlTestRunner` should be called `GetDefaultTestRunner`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
