### ISSUE TITLE
Action GetTestCodeunits and GetTestsByRange in AL Test Tool have the same implementation

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4095]
Dear ALAppExtensions team,
There seems to be no difference in functionality between actions `GetTestCodeunits` and `GetTestsByRange` actions on page `AL Test Tool`, i.e., they have the same implementation in their `OnAction` trigger.
Could you look into this?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
