### ISSUE TITLE
Add DotNet String.Normalize

### ISSUE THREAD

**Issue by SmartNavisys** [microsoft/ALAppExtensions#4097]
I am working building an extension based on an existing product. One critical component is logic that converts diacritics and special characters for SharePoint communications to their simple asciii counterparts. In C/AL this makes use of the following:
DotNet NormalizationForm
DotNet String

Would it be possible to request that this be added to AL extension development? The closest parallel I could find was ReplaceXMLInvalidCharacters in Codeunit XML DOM Management, however this relies on replacing all invalid characters with a specified parameter for the replacement character instead of a set of replacements.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help?

**Comment by JesperSchulz** [comment]
We will look into this!

**Comment by JesperSchulz** [comment]
Do you need the NormalizationForm parameter, or will the Sting.Normalize function without parameter suffice?

**Comment by SmartNavisys** [comment]
I can't say I'm too familiar with this, but the code I need to upgrade to extensions is:
var:
        TextToChange: Codeunit DotNet_String;
        NormalizationForm: DotNet NormalizationForm;
code:
TextToChange := TextToChange.Normalize(NormalizationForm.FormD);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by JesperSchulz** [comment]
We will backport the fix to be released with next minor update.

**Comment by SmartNavisys** [comment]
Excellent, many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
