### ISSUE TITLE
[Event Request] Codeunit 7322 - Function InsertPickOrMoveBinWhseActLine

### ISSUE THREAD

**Issue by PauliusRudminas** [microsoft/ALAppExtensions#4098]
Hello,

Some time ago, I submitted a request for a publisher, that would let me bypass this particular function and solve the activity creation process on my own. Here is the link to an old issue:
Issue ID - 2893; link: [https://github.com/microsoft/ALAppExtensions/issues/2893](https://github.com/microsoft/ALAppExtensions/issues/2893)
The publisher was provided in the BU 140 CU2, and I'd like to thank you for that!

However, I'm seeing it is missing a lot of the parameters that I specified. Without these parameters, I don't think I can sidestep the base code and also create the activity in my own way.

So the parameters used in my solution were these:

LOCAL [IntegrationEvent] OnBeforeInsertPickOrMoveBinWhseActLine(

VAR WhseRequest : Record "Warehouse Request";
VAR WhseActivHeader : Record "Warehouse Activity Header";
VAR NewWhseActivLine : Record "Warehouse Activity Line";
BinCode : Code[20];
DefaultBin : Boolean;
VAR RemQtyToPickBase : Decimal;
IsInvtMovement : Boolean;
AutoCreation : Boolean;
PostingDate : Date;
VendorDocNo : Code[20];
VAR LineCreated : Boolean;
VAR NextLineNo : Integer)

The parameters I see now in the BC 140 CU2 and BC 140 CU3 releases are the folowing:

 LOCAL PROCEDURE OnBeforeInsertPickOrMoveBinWhseActLine@74(

NewWhseActivLine@1003 : Record 5767;
BinCode@1002 : Code[20];
DefaultBin@1001 : Boolean;
VAR RemQtyToPickBase@1000 : Decimal;
VAR IsHandled@1004 : Boolean);

Is there a reason to why the parameters that I specified were not included? I've submitted multiple request for similar publishers, and as I've checked - there were no similar instances - all the parameters were included for every other request.

Please let me know if it would be possible for you to update this publisher with the requested parameters, or whether there are issues.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
