### ISSUE TITLE
[Event Request] Codeunit 22 - Function PostItem

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4102]
We are using BC 14.0 - 14.0.29530.

We need to change the rules about when the blocked check is run, based on some fields in the item journal line. To do this, we need function PostItem in codeunit 22 to be modified, around line 426. The change would need to be something like this:

    IF Item.GET("Item No.") THEN BEGIN
      OnBeforeBlockedCheck(ItemJnlLine,BlockedCheckIsHandled); // NEW
      //IF NOT CalledFromAdjustment THEN // OLD
      IF NOT CalledFromAdjustment AND NOT BlockedCheckIsHandled THEN // NEW
        Item.TESTFIELD(Blocked,FALSE);
      Item.CheckBlockedByApplWorksheet;
    END;

With a new event definition:

    LOCAL [IntegrationEvent] OnBeforeBlockedCheck(VAR ItemJnlLine : Record "Item Journal Line";VAR BlockedCheckIsHandled : Boolean)

--- EDIT ---
Just realised another change will be necessary. This time to function PrepareItem. The PrepareItem function will need to be something like this:

    LOCAL PrepareItem(VAR ItemJnlLineToPost : Record "Item Journal Line")
    ItemJnlLine.COPY(ItemJnlLineToPost);

    GetGLSetup;
    GetInvtSetup;
    OnBeforeCheckItem(ItemJnlLineToPost,IsHandled); // NEW
    IF NOT IsHandled then // NEW
    CheckItem(ItemJnlLineToPost."Item No.");

    OnAfterPrepareItem(ItemJnlLineToPost);

With a new event definition:

    LOCAL [IntegrationEvent] OnBeforeCheckItem(VAR ItemJnlLine : Record "Item Journal Line", VAR IsHandled)

**Comment by AlexanderYakunin** [comment]
Look at latest version, this is already fixed

**Comment by Mullsey** [comment]
> 
> 
> Look at latest version, this is already fixed

Thanks Alexander. I am now looking at version 14.0.35570.

I can see that the code in PostItem has changed a little, but not quite what I need. This:

    Item.TESTFIELD(Blocked,FALSE);

has been replaced with:

    DisplayErrorIfItemIsBlocked(Item);

and DisplayErrorIfItemIsBlocked gives me no ability to handle the error.

So I guess if the function DisplayErrorIfItemIsBlocked  in table 83 gave me the ability to handle it (and prevent the rest of the function being run), that would solve my problem.

Nothing has changed for the PrepareItem function though.
