### ISSUE TITLE
[Event Correction Request] Codeunit 5870 - OnBeforeTransferProdBOMLine

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#4106]
The event requested in #3679 was implemented incorrectly, thus we cannot use it at all (please see explanation in the link). 

Instead, please create it as follows in **codeunit 5870 Calculate BOM Tree**, function **GenerateProdCompSubTree**:
```
WITH ProdBOMLine DO BEGIN
  SETRANGE("Production BOM No.",ParentItem."Production BOM No.");
  SETRANGE("Version Code",VersionMgt.GetBOMVersion(ParentItem."Production BOM No.",WORKDATE,TRUE));
  SETFILTER("Starting Date",'%1|..%2',0D,ParentBOMBuffer."Needed by Date");
  SETFILTER("Ending Date",'%1|%2..',0D,ParentBOMBuffer."Needed by Date");
  // >> ----DELETE
  // SETFILTER("Quantity per",'>%1',0);
  // << ----DELETE
  IF FINDSET THEN BEGIN
    IF ParentItem."Replenishment System" <> ParentItem."Replenishment System"::"Prod. Order" THEN
      EXIT(TRUE);
    REPEAT
      // >> ----NEW
      OnBeforeTransferProdBOMLine(BOMBuffer,ProdBOMLine,ParentItem,ParentBOMBuffer,EntryNo,TreeType);
      IF "Quantity per" > 0 THEN BEGIN
      // << ----NEW
        IF "No." <> '' THEN
          CASE Type OF

[...]

          END;
      // >> ----NEW
      END;
      // << ----NEW
    UNTIL NEXT = 0;
    FoundSubTree := TRUE;
  END;
END;
```

**Comment by AlexanderYakunin** [comment]
We have first event to disable filtering by "Quantity per", so if you set IsHandled = true you can skip this filtering here:
            IsHandled := false;
            OnBeforeFilterByQuantityPer(ProdBOMLine, IsHandled);
            if not IsHandled then
                SetFilter("Quantity per", '>%1', 0);

Adding of IF "Quantity per" > 0 THEN BEGIN within REPEAT loop change business logic right way for you, but may be breaking for others. Can you suggest how we should adopt requested event OnBeforeTransferProdBOMLine to solve your case and also let others use unchanged business logic?

**Comment by NKarolak** [comment]
Then what about:

```
[...]
WITH ProdBOMLine DO BEGIN
  SETRANGE("Production BOM No.",ParentItem."Production BOM No.");
  SETRANGE("Version Code",VersionMgt.GetBOMVersion(ParentItem."Production BOM No.",WORKDATE,TRUE));
  SETFILTER("Starting Date",'%1|..%2',0D,ParentBOMBuffer."Needed by Date");
  SETFILTER("Ending Date",'%1|%2..',0D,ParentBOMBuffer."Needed by Date");
  IsHandled := FALSE;
  OnBeforeFilterByQuantityPer(ProdBOMLine,IsHandled);
  IF NOT IsHandled THEN
    SETFILTER("Quantity per",'>%1',0);
  IF FINDSET THEN BEGIN
    IF ParentItem."Replenishment System" <> ParentItem."Replenishment System"::"Prod. Order" THEN
      EXIT(TRUE);
    REPEAT
      // >> ------- NEW
      IsHandled := FALSE;
      OnBeforeTransferProdBOMLine(BOMBuffer,ProdBOMLine,ParentItem,ParentBOMBuffer,EntryNo,TreeType,IsHandled);
      IF NOT IsHandled THEN
      // << ------- NEW
        IF "No." <> '' THEN
          [...]   
    UNTIL NEXT = 0;
    FoundSubTree := TRUE;
  END;
END;
[...]
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
