### ISSUE TITLE
Check changestatus in Service Contract Header

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#4109]
![Skjermbilde2](https://user-images.githubusercontent.com/35260264/64166266-0990df80-ce47-11e9-8466-de2ed94f2cb5.JPG)
![Skjermbilde3](https://user-images.githubusercontent.com/35260264/64166269-0ac20c80-ce47-11e9-93ef-b6154bd9a7ff.JPG)
![Skjermbilde4](https://user-images.githubusercontent.com/35260264/64166274-0c8bd000-ce47-11e9-8a73-cc8af5371932.JPG)

**Comment by AlexanderYakunin** [comment]
Can you explain what you actually want us to do with this?

**Comment by DanielHaglo** [comment]
Replace Testfield with CheckStatus, so we can use the function SuspendStatusCheck. There is already a function CheckChangeStatus, but its only used in a couple of places.

 And add HideValidationDialog so we can override the confirm.

Do you not agree?

**Comment by GiorgosPa** [comment]
@AlexanderYakunin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
