### ISSUE TITLE
Blank Option Value Issue

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4112]
Just wondering, what could we do to pass this Blank Option Value Issue
[Blank Option Value Issue.docx](https://github.com/microsoft/ALAppExtensions/files/3569942/Blank.Option.Value.Issue.docx)
?

**Comment by AlexanderYakunin** [comment]
Can you explain your case in more details? It looks like you own code, not our app?

**Comment by Teming** [comment]
Sorry.   That example is our own code.  Here is an example from table 5902 Service Line with an option that has a blank value for the first option.

[Blank Option Value Issue.docx](https://github.com/microsoft/ALAppExtensions/files/3574765/Blank.Option.Value.Issue.docx)

**Comment by Teming** [comment]
sorry, wrong attachment.  Here you go!  
If we try to specify some specific actions to do when Type = Type::"0", we would get an AL error.   I think we might be able to do "type" = "type" :: " " ; however, that means we could not have more than one " ".

![Blank Option Example](https://user-images.githubusercontent.com/49729094/64276951-2268c600-cf17-11e9-9014-b909a70a0588.PNG)

**Comment by AlexanderYakunin** [comment]
You cannot have more than one " " value in enum.
