### ISSUE TITLE
[Parameters] PAG 344 OnBeforeNavigateShowRecords

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4118]
New parameters are available on PAG 344 in **OnBeforeNavigateShowRecords** (via #2176). However, parameters should be exposed with **VAR** access, so we can 'mark' the records that apply to the search conditions so that 'SalesInvHeader.FINDFIRST' in FindRecords does not result in errors.

![image](https://user-images.githubusercontent.com/25268332/64241554-4373eb80-cf04-11e9-866c-2dcbd374ac57.png)

- [ ] Solved in BC14

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
