### ISSUE TITLE
Item Attribute new Event Publisher

### ISSUE THREAD

**Issue by JonasPatto** [microsoft/ALAppExtensions#4129]
Hello Microsoft Team,

if you want to extend the item Attributes with new fields you run into a lot of problems saving those new values from the "Item Attribute Value Selection" into the "Item Attribute Value Mapping" Table due to a lack of suiting events. 

My Suggestion:

in Page 7504 "Item Attribute Value List" has the only Event Publisher (OnBeforeItemAttributeValueMappingModify(ItemAttributeValueMapping,ItemAttributeValue,RelatedRecordCode))
 which could help in this situation but the problem with it is that you don't have access to the current Record so you can't apply your custom field values to the corresponding Mapping-Record. My Suggestion here would be to add the current Record in the Publisher. But it would be weird to call the Value-OnValidate Trigger just to apply your custom changes, wouldn't it? So here is my other suggestion: 
Add two new Event Publisher either in the Table 7504 "Item Attribute Value Selection" or Page 7504 "Item Attribute Value List" each in the Insert-Trigger and Modify-Trigger with the current Record, the corresponding ItemAttributeValueMapping-Record and ItemAttributeValue like this:

OnBeforeInsertItemAttributeValueMapping(ItemAttributeValueMapping, ItemAttributeValue, Rec)
OnAfterModifyItemAttributeValueMapping(ItemAttributeValueMapping, Rec)

My third suggestion would be:

Fill the two fields "Inherited-From Table ID" and "Inherited-From Key Value" in the Table 7504 "Item Attribute Value Selection" with actual values. If these fields storage the correct Informations we could easily filter for the Item Attribute Value Mapping Record and apply our changes without a new Event Publisher. Currently those fields are always empty (see picture)
![ItemAttributeValueSelection](https://user-images.githubusercontent.com/48987445/64320548-16d0da00-cfbf-11e9-8470-9dd97ed061fa.png)

Thanks for your help in advance.

Best Regards

Jonas

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
