### ISSUE TITLE
[Key Request] New Key for Table "FA Posting Group" 5606

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#4131]
The following case describes, why the key in the “FA Posting Group” (T5606) should be extended with the field “Depreciation Book”:
When a company manages the same group of fixed asset simultaneously in two depreciation books, for example due to different financial statements (e.g. US GAAP, IFRS), different depreciation periods or interest rates and would like to post the expenses to different accounts e.g.:
FA Posting Group “C1”, Depreciation Book “US GAAP”, depreciation period 10 years, interest rate 2%, Depreciation Expense Acc. “440011”, Interest Expense Account “480011”
FA Posting Group “C1”, Depreciation Book “IFRS”, depreciation period 12 years, interest rate 0%, Depreciation Expense Acc. “I440011”, Interest Expense Account “I480011” (“I” for IFRS)
Then they need to be able to set these parameters in Table 5606 based on the depreciation book in combination with the FA Posting Group.

**Comment by AlexanderYakunin** [comment]
We currently cannot change primary keys.

**Comment by AlexanderYakunin** [comment]
It should be possible to add events to extend business logic for your scenarios. Please suggest.

**Comment by ddagkappeler** [comment]
In the Table 81 there is a get() on the FAPostingGr in the Function GetFAVATSetup(). We need the posibility to change the FAPostingGroup.
- New Event "OnAfterGetPostingGroup"
or
- Or an extension for the Event OnGetFAVATSetupOnBeforeCheckGLAcc

```
OnGetFAVATSetupOnBeforeCheckGLAcc(Rec, LocalGlAcc, ShouldExit);
If ShouldExit then 
exit;
```

**Comment by ddagkappeler** [comment]
In the Codeunit "FA Get G/L Account No." 5602 in the Function GetMaintenanceAccNo() we need the posibility to change the FAPostingGroup like in the Function GetAccNo().

**Comment by ddagkappeler** [comment]
In the Codeunit "FA Insert G/L Account" 5601 in the Function InsertBufferBalAcc() we need the posibility to change the FAPostingGroup or change the ALAccNo.

In the Function CalcDisposalAmount() we need the posibility to change the FAPostingGr2

**Comment by ddagkappeler** [comment]
@bc-ghost Do I have to create new tickets for these inputs?

**Comment by AlexanderYakunin** [comment]
Yes, please. Old bug have been already closed.
