### ISSUE TITLE
Codeunit 5530 New Event in TryGetQtyOnInventory w/ Handled Pattern

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#4134]
Dear Development Team,

would it be possible to add a new Event w/ the Handled Pattern into the TryGetQtyOnInventory function? That would give us a way to implement our own Inventory Calculation

Thanks,
Marton

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
