### ISSUE TITLE
Extending an Option-field

### ISSUE THREAD

**Issue by Wildrik** [microsoft/ALAppExtensions#4137]
This concerns using an enum extension to extend an Option-field. Cf. https://github.com/microsoft/AL/issues/4559.

There is support for enums and enum extensions in AL as described here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums. Hoewever, contrary to the answer in the issue above, as far as I see this is not of any help in extending an Option-field in e.g. the Sales Line table (table 37). An enum is an object and not just a datatype. It is quite different from an Option in this regard.

To migrate our solution from C/SIDE to AL we need to extend the Option-field 'Type' in the Sales Line with several of our own members. This would be possible if this Option-field was replaced with an enum that we could extend.

Am I right in asserting that it is not possible to extend an Option-field with an enum extension? If so: what other solutions are available to extend an Option-field? If I am wrong: how do I build an enum extension for an Option-field? I do not find any description of this in the documentation.

**Comment by AlexanderYakunin** [comment]
You can only build enum extension for enum field. Please wait until we will be able to convert selected options into enums. You can also create your Enum Requests if this is not yet requested by others
