### ISSUE TITLE
[EventModification] Codeunit 7010 - PurchLinePriceExists & PurchLineLineDiscExists

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/ALAppExtensions#4139]
You have added two events with the requests [425] and [426], but both events do not handle the global variable "DateCaption". Therefore this variable will stay empty (if IsHandled = TRUE)

I suggest you add "DateCaption" to both events.
```
- OnBeforePurchLinePriceExists(PurchLine,PurchHeader,TempPurchPrice,ShowAll,IsHandled);
+ OnBeforePurchLinePriceExists(PurchLine,PurchHeader,TempPurchPrice,DateCaption,ShowAll,IsHandled);
- OnBeforePurchLineLineDiscExists(PurchLine,PurchHeader,TempPurchLineDisc,ShowAll,IsHandled);
+ OnBeforePurchLineLineDiscExists(PurchLine,PurchHeader,TempPurchLineDisc,DateCaption,ShowAll,IsHandled);
```

**Comment by ralf-escher** [comment]
Same problem exists for Codeunit 7000 - OnBeforeSalesLinePriceExists and OnBeforeSalesLineLineDiscExists, but this time you call the event with 
`SalesHeaderStartDate(SalesHeader,DateCaption)`
as parameter, which makes things somehow difficult to manipulate DateCaption

**Comment by ralf-escher** [comment]
Do get access to the Start Date handling in the Price Calculation Management and therefore access to the global variable `DateCaption `I applied for new events in both codeunits: #4345 and #4346

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by ralf-escher** [comment]
@AlexanderYakunin 
maybe you can take a look into #4345 and #4346
Due to #4346 I closed that issue (sorry for the confusion)
