### ISSUE TITLE
[Event Request] - Codeunit 5056 - function InsertNewContact

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4140]
We are using BC 14.0.35570.

The client we are upgrading has a different number series for each kind of contact. Is there a way we can have greater control over this? I can suggest a number of ways this could be handled if needed.

**Comment by AlexanderYakunin** [comment]
Please do not ask theoretical questions (if you know how to solve your issue and want to save time). Ask for what you need.

**Comment by Mullsey** [comment]
OK. This is an example of what I think can work. And I must appologise - I meant codeunit 5056 (creating contacts from customers). I have changed the subject accordingly.

    [External] InsertNewContact(VAR Cust : Record Customer;LocalCall : Boolean)
    IF NOT LocalCall THEN BEGIN
      RMSetup.GET;
      RMSetup.TESTFIELD("Bus. Rel. Code for Customers");
    END;

    IF ContBusRel.UpdateEmptyNoForContact(Cust."No.",Cust."Primary Contact No.",ContBusRel."Link to Table"::Customer) THEN
      EXIT;

    WITH Cont DO BEGIN
      INIT;
      TRANSFERFIELDS(Cust);
      OnAfterTransferFieldsFromCustToCont(Cont,Cust);
      VALIDATE(Name);
      VALIDATE("E-Mail");
      OnBeforeAssignNumber(Cont, AssignNumberHandled); // NEW
      IF NOT AssignNumberHandled then begin // NEW
    	  "No." := '';
    	  "No. Series" := '';
    	  RMSetup.TESTFIELD("Contact Nos.");
    	  NoSeriesMgt.InitSeries(RMSetup."Contact Nos.",'',0D,"No.","No. Series");
      end; // NEW
      Type := Type::Company;
      TypeChange;
      SetSkipDefault;
      OnBeforeContactInsert(Cont,Cust);
      INSERT(TRUE);
    END;

With the event like this:

    LOCAL [IntegrationEvent] OnBeforeAssignNumber(VAR Contact : Record Contact; VAR AssignNumberHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
