### ISSUE TITLE
Breaking change, Tempblob.ToBase64String()

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#4142]
Good day,

breaking change in deleting the tempblob table from platform 15. The replacement codeunit "Temp Blob" does not have a ToBase64String-function.

.

**Comment by GiorgosPa** [comment]
The functionality has been moved out of the TempBlob on purpose. There is now a Base64 Helpers Codeunit that is doing the same based on Streams.  See an example of usage bellow
```
var
    Base64Helpers: Codeunit "Base64 Helpers";
    TempBlob: Codeunit "Temp Blob";
    ....
begin
    TempBlob.CreateInStream(InStream);
    Base64Text := Base64Helpers.ToBase64String(InStream);
```

**Comment by janrik** [comment]
Thank you. In my opinion all of the changes that break existing solutions should primarily be avoided, but if necessary to do, they should be mentioned proactively in the BREAKINGCHANGES.md - not just after someone runs into trouble.

**Comment by GiorgosPa** [comment]
Thank you I will add them

**Comment by arivascarmona** [comment]
I have the following code and I don't know how to transform it so as not to use the TEMPBLOB table
<pre>
var
    TempBlob: Record TempBlob temporary; 
    Out: OutStream; 
    RecRef: RecordRef; 
    Report: Report "Order Confirmation"; 
...       
begin
...
    TempBlob.Blob.CreateOutStream(Out); 
    Report.SaveAs('', ReportFormat::Pdf, Out, Recref); 
    exit(TempBlob.ToBase64String());
end
</pre>
Any ideas?

**Comment by janrik** [comment]
> I have this code and I don't know how to transform it so as not to use the TEMPBLOB table
> 
> var
>     TempBlob: Record TempBlob temporary; 
>     Out: OutStream; 
>     RecRef: RecordRef; 
>     Report: Report "Order Confirmation"; 
> ...       
> begin
> ...
>     TempBlob.Blob.CreateOutStream(Out); 
>     Report.SaveAs('', ReportFormat::Pdf, Out, Recref); 
>     exit(TempBlob.ToBase64String());
> end
> Any ideas?

maybe something like

    local procedure fuu():text;
    var
    Base64: codeunit "Base64 Convert";
    TempBlob: Codeunit "Temp Blob"; 
    Out: OutStream; 
    InStr: InStream;
    RecRef: RecordRef; 
    Report: Report "Order Confirmation";      
begin
    TempBlob.CreateOutStream(Out); 
    Report.SaveAs('', ReportFormat::Pdf, Out, Recref); 
    TempBlob.CreateInStream(InStr);
    exit(Base64.ToBase64(InStr));
end
