### ISSUE TITLE
[Event Request] - Codeunit 7000 - function CalcBestUnitPrice

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4148]
We are using BC 14.0.35570.

The client we are upgrading various specific rules with pricing. One of these is that the customer does not always get the best price. If a campaign price exists, the customer will automatically get this.

To enable this, I think the CalcBestUnitPrice function needs to have an event added to it. Something like this:

    [External] CalcBestUnitPrice(VAR SalesPrice : Record "Sales Price")
    OnBeforeCalcBestUnitPrice(SalesPrice, BestSalesPriceFound, IsHandled); //NEW
    IF IsHandled then // NEW
    	exit; // NEW
    WITH SalesPrice DO BEGIN
      FoundSalesPrice := FINDSET;
      IF FoundSalesPrice THEN

With an event definition:

    LOCAL [IntegrationEvent] OnBeforeCalcBestUnitPrice(VAR SalesPrice : Record "Sales Price", VAR BestSalesPriceFound: Boolean, VAR IsHandled: Boolean)

**Comment by Mullsey** [comment]
I ended up up replicating the entirity of codeunit 7000 in an al codeunit, and using the OnBeforeFindSalesLinePrice event to call my custom codeunit, so most of codeunit 7000 is never touched.

Not sure if I should close this issue. It would be nice to be able to do what I'm after without replicating the whole codeunit. But I'm able to get around my problem like this.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
