### ISSUE TITLE
[Event Request] - Codeunit 7000 - function ActivatedCampaignExists

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4149]
We are using BC 14.0.35570.

The client we are upgrading to BC has specific rules as to if a campaign can be used (Campaigns are only used if specifically selected).

Being able to handle the ActivatedCampaignExists function would enable us to take care of this scenario.

**Comment by StanPesotskiy** [comment]
@Mullsey 
Do you mean you need a OnBeforeActivatedCampaignExists(... , var IsHandled) event? 
Please provide the signature of the event how you would like to see it.

**Comment by Mullsey** [comment]
Yeah. Thats what I meant. Like this:

    [External] ActivatedCampaignExists(VAR ToCampaignTargetGr : Record "Campaign Target Group";CustNo : Code[20];ContNo : Code[20];CampaignNo : Code[20]) : Boolean
    IF NOT ToCampaignTargetGr.ISTEMPORARY THEN
      ERROR(TempTableErr);
    OnBeforeActivatedCampaignExists(VAR ToCampaignTargetGr, CustNo ,ContNo,CampaignNo, Handled);
    IF Handled then
      exit;

    WITH FromCampaignTargetGr DO BEGIN

And event:

    LOCAL [IntegrationEvent] OnBeforeActivatedCampaignExists(VAR ToCampaignTargetGr : Record "Campaign Target Group";CustNo : Code[20];ContNo : Code[20];CampaignNo : Code[20]; VAR Handled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
