### ISSUE TITLE
[EventModification] Table 36 Sales Header - RecreateSalesLines

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4154]
Is it possible to add IsConfirmed (as reference) to RecreateSalesLines, and use IsHandled to skip the entire code in the function?

First part of RecreateSalesLines:
![image](https://user-images.githubusercontent.com/46031720/64508970-0aaa8c80-d2df-11e9-8016-dd310abaa496.png)

Last part of RecreateSalesLines:
![image](https://user-images.githubusercontent.com/46031720/64509015-244bd400-d2df-11e9-90b9-3e9024c790b8.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
