### ISSUE TITLE
[EventModification] Table 38 Purchase Header - RecreatePurchLines

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4155]
Is it possible to add IsConfirmed (as reference) to RecreatePurchLines, and use IsHandled to skip the entire code in the function?

First part of RecreatePurchLines:
![image](https://user-images.githubusercontent.com/46031720/64509224-8efd0f80-d2df-11e9-9b9e-a4175913a0d3.png)

Last part of RecreatePurchLines:
![image](https://user-images.githubusercontent.com/46031720/64509254-9f14ef00-d2df-11e9-89c5-848e3d65b5ea.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
