### ISSUE TITLE
[Event Request] OnBeforeSetDefaultType in Purch. * Subforms

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4157]
Hi.

I can see that OnBeforeSetDefaultType has been added for sales * subforms, but not for purch * subforms. Can this be added to the purchase module aswell?

![image](https://user-images.githubusercontent.com/46031720/64510128-aa691a00-d2e1-11e9-90cb-113ae92d6501.png)

**Comment by j4ck4l** [comment]
This SetDefaultType structure (with OnBefore handled event) is only present on Sales Order Subform (Page 46) and Sales Invoice Subform (Page 47). 

Is it possible that is modification can be made on Sales Quote Subform (Page 95), Sales Cr. Memo Subform (Page 96), Blanket Sales Order Subform (Page 508) and Sales Return Order Subform (Page 6631) as well?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
