### ISSUE TITLE
Wave2: Codeunit 10 Type Helper WriteRecordLinkNote method is missed

### ISSUE THREAD

**Issue by beniukdima** [microsoft/ALAppExtensions#4160]
Hi,
I am using AL 4.0 and bcinsider.azurecr.io/bcsandbox-master image of 15.0.0.0 vesion
I've found that the Codeunit 10 TypeHelper doesn't have
WriteRecordLinkNote method which contains code that is used when adding a new comments to the order.
Where this method has been moved in a new version?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help to answer?

**Comment by darjoo** [comment]
@beniukdima We are updating the Breaking Changes document with this specific issue at the moment. I'll write again once the update is in.

**Comment by darjoo** [comment]
@beniukdima The document has now been updated.
