### ISSUE TITLE
Add. Event Parameters - Table 5870 „BOM Buffer“ - Business Central Version 15

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#4161]
Could you please add the 2 additional Publisher Parameters in Table 5870 which were requested in Issue

https://github.com/microsoft/ALAppExtensions/issues/2572

also in Business Central Version 15.

The 2 add. Parameters were already added in Business Central 14 Builds (e.g. 14.3.34444.0 – BC14 CU2) but not in Business Central 15 Builds (e.g. 15.0.35903).

Details of the Issue 2572:

Please add the Parameters ParentItem and ParentQtyPer to the Parameters of Publisher OnTransferFromProdCompCopyFields in Table 5870

Modified Call in Function TransferFromProdComp:
````
- OnTransferFromProdCompCopyFields(Rec,ProdBOMLine);
+ OnTransferFromProdCompCopyFields(Rec,ProdBOMLine,ParentItem,ParentQtyPer);
````

Modified Publisher:
````
- LOCAL PROCEDURE OnTransferFromProdCompCopyFields@49(VAR BOMBuffer@1001 : Record 5870;ProductionBOMLine@1000 : Record 99000772);
+ LOCAL PROCEDURE OnTransferFromProdCompCopyFields@49(VAR BOMBuffer@1001 : Record 5870;Productio
````

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
