### ISSUE TITLE
Expose procedure in Table "Option Lookup Buffer".FormatOption

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#4162]
Hi,

Could you please expose "Option Lookup Buffer".FormatOption, we need it for extension development?

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
