### ISSUE TITLE
Increase of Field Length No. in Table "Item Attribute Value Mapping"

### ISSUE THREAD

**Issue by scriddler** [microsoft/ALAppExtensions#4164]
Hi,
is there any possibility that the field length of **"No."** will become **40** instead of **20** in the table "Item Attribute Value Mapping" (other suggestion would be adding a new "guid" field and use it in the key, too). This would be very helpful for anyone who would like to extend this table - for example if you want to use this table for "Item Variants", too.
My idea was to extend "Item Variant" with a "Guid" field and then use this value on "Item Attribute Value Mapping" in the field "No." to allow creation of Attributes for Item Variants, too (not only for Item and Item Category).
Thanks for your answers,
best regards, 
Gerald

**Comment by AlexanderYakunin** [comment]
No, this is currently not possible, this is breaking change.

**Comment by scriddler** [comment]
Okay, thx at least for your answer.
regards
Gerald
