### ISSUE TITLE
[Application Request] PAG 98 - Remove BE delta / Add ALL posting group fields

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4169]
PAG 98 - W1 - contains only the 'VAT Prod Posting Group' field
PAG 98 - W1 - our add-on - added the 'VAT Bus Posting Group' field
PAG 98 - BE - contains ALL 'Posting Group' fields
PAG 98 - BE- our add-on -> merge conflict due to already added 'VAT Bus Posting Group' field

I'm aware we should prefix our own control names, to solve the problem. However, fields would then be available twice in BE, which should be avoided (=confusing). So **please resolve the BE delta**. (and either add ALL posting group fields or remove the BE change)

![image](https://user-images.githubusercontent.com/25268332/64558999-8a6b4200-d345-11e9-9ba8-69d015bfa00d.png)

PS: Please review any other similar sales / purchase subpages.

Question : Don't know how we'll ever be aware of these kind of (unnecessary) mods once all is on extensions.... Any CodeCop suggestions?

**Comment by jobulsin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
