### ISSUE TITLE
[Request for External] codeunit 1236 "Suggest Col. Definition - XML" - GenerateDataExchColDef

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4171]
Can you make function GenerateDataExchColDef external in codeunit "Suggest Col. Definition - XML"?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
