### ISSUE TITLE
[Event Request] COD 1247 - OnAfterCreateGeneralJournalLineTemplate

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4172]
Can't find the #2367 in the latest sandbox / images / BC 14 cu. Has this been solved?

- [ ] Solved in BC14

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
