### ISSUE TITLE
[External Function] REP 2000005 / 2000006 - NewConsolidatedPayment

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4174]
In #2777, a new OnAfterNewConsolidatedPayment is provided to modify the NewConsolidatedPayment return value. However, I would like to skip the Account Type / Account No / ... conditions and build my own.

> ...
> To construct our new function, following functions must be global
> 
> CheckNewGroup
> IsPaymentMessageTooLong
> 

Seems like to above functions have not been updated? Can you please set the procedures 'CheckNewGroup' and 'IsPaymentMessageTooLong' in both reports to external?

We should be able to achieve code below:

![image](https://user-images.githubusercontent.com/25268332/64593666-bec71880-d3ae-11e9-9196-85785e8719ff.png)

- [ ] Available in BC 14

**Comment by AlexanderYakunin** [comment]
They are global

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
