### ISSUE TITLE
GetPlatformVersion

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#4178]
Please add the GetPlatformVersion Version again.
Formerly this function was located in the Tenant Management Codeunit.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by DuttaSoumya** [comment]
Hi @ChrisBlankDe ,

The GetPlatformVersion returned a very technical term about the platform build number used internally by MS. The only place it was actually used is **page 1920 "Container Sandbox Environment"**, where the function has been moved to as a Local function. We would like to know the justification for you to use it. If you simply wish to have an application identifier, would it be enough for you to use any of the procedures defined in either of the two APIs:

1. codeunit 457 "Environment Information"
2. codeunit 417 "Tenant Information"

These can be found in [the module Environment Information](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Environment%20Information).

Best regards.

**Comment by GiorgosPa** [comment]
@DuttaSoumya

**Comment by DuttaSoumya** [comment]
Hi @ChrisBlankDe , 

What I meant was that the user cannot do much about, in most cases does not even understand, the version details for the platform. In case of error, the application service for the user can be pulled up by the troubleshooter, and the app service always runs on a specific app + platform version. 

One more thing, could you please point me to the help topic on this procedure- we may have overlooked it when taking this function out.

Cheers,
Dutta.

**Comment by JesperSchulz** [comment]
We haven't heard from you in a while. Hopefully that's because you found a solution to the issue. For good housekeeping reasons we're closing issue, but if the problem still exists please submit a new request.
