### ISSUE TITLE
[Event Request] COD 396 NoSeriesManagement - OnGetNextNo3OnBeforeModify

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4180]
Following this Yammer thread
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=97831429193728

Our finance consultants do not want to have 'Empty Posted Documents' created when deleting a non-posted document that has already a pre-assigned posting no. Seems like a specific aversion of empty documents with Belgian accountants.

Therefore we created an option **not** to create empty documents (to fill the gap of posted document no. series) upon deletion of the non-posted document. Users had to reset the 'Last No. Used' before creating/posting a new document, which is cumbersome. Instead we store the no. in a separate table, and want to re-use this number when creating a new document (instead of increasing the 'last no. used') (This approach is also not 100% fail-safe since numbers might be stored and never re-used ...)

Can you please provide a **OnGetNextNo3OnBeforeModify**(VAR NoSeriesLine, VAR IsHandled) event on exact place below? (OnAfterGetNextNo3 is not usable for this scenario)

```
IF ModifySeries THEN BEGIN
  OnGetNextNo3OnBeforeModify(VAR NoSeriesLine, VAR IsHandled); // >> Add event here ...
  IF NOT IsHandled THEN // >> ... to skip the MODIFY
    NoSeriesLine.MODIFY
END ELSE
  LastNoSeriesLine := NoSeriesLine;
```

![image](https://user-images.githubusercontent.com/25268332/64604829-24250480-d3c3-11e9-9c89-1e63f377dbee.png)

PS: Ideally, if MS could avoid to increase / define the actual posted no. series at the beginning of the posting routine (UpdatePostingNos before COMMIT), and include the no. series update as part of the transaction (after the COMMIT), this would solve all of the above work-arounds ...

- [ ] Available in BC 14

**Comment by fvet** [comment]
@AlexanderYakunin 
Could you please advice the path MS is thinking to deliver this request? 

OnGetNextNo3OnBeforeModify is one of the last remaining publisher to get our Belgian localisation on extensions (although I personally think it's not the nicest solution...).

Or can we expect MS to include setting the actual posted no. series as part of the transaction (after the commit) or would that be a major breaking change?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
