### ISSUE TITLE
[EventRequest] Codeunit 333 Req. Wksh.-Make Order - OnBeforeCheckInsertFinalizePurchaseOrderHeader

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4181]
We would like to request a change on the already existing OnBeforeCheckInsertFinalizePurchaseOrderHeader publisher.

- Parameter PurchOrderHeader we would like to have as 'VAR'.
- We would like an additional parameter providing 'OrderCounter' as VAR.

This way we can allow users to add some lines to already existing purchase orders.

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
