### ISSUE TITLE
[Event Request] - Report 7304 "Get Outbound Source Documents" - Custom filters

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4185]
We are using BC 14.0.35570.

The client we are upgrading does not want picks to be created all warehouse shipments, even items are available for them. To do this, we are currently (in 2009) programatically placing an additional filter on the "Warehouse Shipment Header" dataitem in the OnPreDataItem trigger for this dataitem.

If we could have an event in the OnPreDataItem trigger in the "Warehouse Shipment Header" dataitem, that would allow us to set filters on "Warehouse Shipment Header", we would much appreciate it.

**Comment by AlexanderYakunin** [comment]
Can you please provide definition of requested event with name, parameters and location in the code? You can look into other requests in the list and follow. We should not guess how you events should looks like.

**Comment by Mullsey** [comment]
Sorry - I have been providing samples of what I want for other requests. I just got a bit lazy for this one.

So the following code in report 7304 would suffice:

    Warehouse Shipment Header - OnPreDataItem()
    IF "Whse. Pick Request"."Document Type" <>
       "Whse. Pick Request"."Document Type"::Shipment
    THEN
      CurrReport.BREAK;
    OnWhseShipHeaderOnPreDataItem("Warehouse Shipment Header"); // NEW

With the event definition like this:

    LOCAL [IntegrationEvent] OnWhseShipHeaderOnPreDataItem(VAR WarehouseShipmentHeader: Record "Warehouse Shipment Header");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
