### ISSUE TITLE
[Event Request] - Report 5754 - Suppress "Nothing to Handle" error

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4186]
We are using BC 14.0.35570.

The client we are upgrading has had warehouse pick creation linked to releasing of sales orders. So when an order is released, a warehouseshipment is automatically cretaed, and a pick created from that. When the pick creation process is run from the release function, we suppress the "Nothing to handle" error message by passing a new boolean variable into report 5754 (Create Pick) before we run it, and skip the error if it has been set to true.

Is there some way we can be allowed to do the same thing in BC? Maybe by an event before the error message is shown? Or similar code being implemented in standard BC?

**Comment by AlexanderYakunin** [comment]
Please suggest event

**Comment by Mullsey** [comment]
I'm not sure an event would really be enough, because the behaviour will change depending on where the code is called from:

- Called manually from the warehouse shipment - we want the message
- Called programatically, we want to be able to hide the message

I think we will need to modify three objects to enable this (this is what we needed to do in NAV 2009).

I have detailed the changes needed in the attached word document.

[20191011 Suppress Nothing to handled message.docx](https://github.com/microsoft/ALAppExtensions/files/3715439/20191011.Suppress.Nothing.to.handled.message.docx)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
