### ISSUE TITLE
[Event Request] - Report 5754 - Control which report is printed

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4187]
We are using BC 14.0.35570.

At the moment report 5754 (Create Pick) does not allow us to control which report is printed. Can we have an event which we can use to print out a different report?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
