### ISSUE TITLE
[Event Request] - Report 7318

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4188]
We are using BC 14.0.35570.

In report 7318 (Whse.-Shipment - Create Pick), in the OnAfterGetRecord trigger of the "Warehouse Shipment Line" dataitem, we need the ability to add more filters to the WhseWkshLine variable. An event something like this:

    Warehouse Shipment Line - OnAfterGetRecord()
    IF Location."Directed Put-away and Pick" THEN
      CheckBin(0,0);

    WhseWkshLine.RESET;
    WhseWkshLine.SETCURRENTKEY(
      "Whse. Document Type","Whse. Document No.","Whse. Document Line No.");
    WhseWkshLine.SETRANGE(
      "Whse. Document Type",WhseWkshLine."Whse. Document Type"::Shipment);
    WhseWkshLine.SETRANGE("Whse. Document No.",WhseShptHeader."No.");

    WhseWkshLine.SETRANGE("Whse. Document Line No.","Line No.");
    OnAfterSetWhseWkshLineFilter(WhseWkshLine, "Warehouse Shipment Line" WhseShptHeader); // NEW
    IF NOT WhseWkshLine.FINDFIRST THEN BEGIN

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
