### ISSUE TITLE
Function Expose Request: Table 370: CreateBookAndOpenExcel

### ISSUE THREAD

**Issue by tejabalusu** [Microsoft/ALAppExtensions#419]
Hi,

Please expose the below function from Table 370 Excel Buffer,

Functions--
CreateBook
CreateBookAndOpenExcel

**Comment by JesperSchulz** [comment]
CreateBook cannot be exposed, as it uses a file name as parameter. Please use CreateNewBook instead. The same is true for CreateBookAndOpenExcel, but you can use the exposed functions CreateNewBook, WriteSheet, CloseBook and OpenExcel yourself to work around that (which make up CreateBookAndOpenExcel).
We're looking into a more pure file handling for future versions of Business Central. The Excel Buffer will receive a makeover as well. Stay tuned!
