### ISSUE TITLE
[Event Request] TAB 37 - UpdateBaseAmounts()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#4190]
Could you please add a new event in TAB 37 UpdateBaseAmounts():

```
LOCAL UpdateBaseAmounts(NewAmount : Decimal;NewAmountIncludingVAT : Decimal;NewVATBaseAmount : Decimal)
Amount := NewAmount;
"Amount Including VAT" := NewAmountIncludingVAT;
"VAT Base Amount" := NewVATBaseAmount;
IF NOT SalesHeader."Prices Including VAT" AND (Amount > 0) AND (Amount < "Prepmt. Line Amount") THEN
  "Prepmt. Line Amount" := Amount;
IF SalesHeader."Prices Including VAT" AND ("Amount Including VAT" > 0) AND ("Amount Including VAT" < "Prepmt. Line Amount") THEN
  "Prepmt. Line Amount" := "Amount Including VAT";

OnAfterUpdateBaseAmounts(Rec,xRec,CurrFieldNo); // New Event
```

Publisher:
`LOCAL [IntegrationEvent] OnAfterUpdateBaseAmounts(VAR SalesLine : Record "Sales Line";VAR xSalesLine : Record "Sales Line";CurrentFieldNo : Integer)`

many thanks
stefan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
