### ISSUE TITLE
[EventRequest] Report 513 Move IC Trans. to Partner Comp - TransferToPartner

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4194]
Issue #3615 has only partly been delivered. Can you also implement the second publisher? Many thanks.

_Originally posted by @lv-janpieter in https://github.com/microsoft/ALAppExtensions/issues/3615#issuecomment-530433148_

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
