### ISSUE TITLE
[Event Request] Codeunit 211 - OnBeforeCheckPostingDate

### ISSUE THREAD

**Issue by BE-Ouaali** [microsoft/ALAppExtensions#4195]
Please add a new integration event OnBeforeCheckPostingDatein Codeunit 211.

```
    [Integration]
    LOCAL PROCEDURE OnBeforeCheckPostingDate@1000(VAR ResJnlLine@1000: Record 207;VAR SkipCheckPostingDate@1001 : Boolean);
    BEGIN
    END;
```

Call for function:

```
[External]
    PROCEDURE RunCheck@1(VAR ResJnlLine@1000 : Record 207);
    VAR
      [...]
+     SkipCheckPostingDate@1010: Boolean;
    BEGIN
      [...]
      WITH ResJnlLine DO BEGIN
        IF EmptyLine THEN
          EXIT;

        TESTFIELD("Resource No.");
        TESTFIELD("Posting Date");
        TESTFIELD("Gen. Prod. Posting Group");

+       OnBeforeCheckPostingDate(ResJnlLine,SkipCheckPostingDate);
+       IF NOT SkipCheckPostingDate THEN BEGIN
          IF "Posting Date" <> NORMALDATE("Posting Date") THEN
            FIELDERROR("Posting Date",Text000);

          UserSetupManagement.CheckAllowedPostingDate("Posting Date");
+       END;

        [...]
      END;

      OnAfterRunCheck(ResJnlLine);
    END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
