### ISSUE TITLE
[EventRequest] Report 11000013 SEPA ISO20022 Pain 008.001.02 - AddPaymentInformation (NL)

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4196]
This publisher in issue #3390 has been incorrectly implemented. The call of the publisher should happen after Customer.GET because customer is provided as a parameter and the result should be maintained and not overwritten by the Customer.GET. 

Could you move the call of the publisher to the correct place? Many thanks.

_Originally posted by @lv-janpieter in https://github.com/microsoft/ALAppExtensions/issues/3390#issuecomment-530446960_

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
