### ISSUE TITLE
[Event Request] Codeunit 5005396 Print Document Comfort

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#4197]
Hi, in https://github.com/microsoft/AL/issues/3754
i requested an event. This was not implemented since we could pick other Reports by using report selection. I just realized this is not what we need the event for. We need it to apply additional filters.
Please add that event.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
