### ISSUE TITLE
[EventRequest] Table 37 “Sales Line”, GetSalesHeader [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4201]
Please add a new publisher event OnBeforeGetSalesHeader as shown in the picture below in the function  GetSalesHeader in table 39

![image](https://user-images.githubusercontent.com/54017538/64769064-e8b54200-d54a-11e9-83d6-5a4f5a673a38.png)

Please add the corresponding Integration Event In the bottom of the table

![image](https://user-images.githubusercontent.com/54017538/64769076-ef43b980-d54a-11e9-8b4a-00815bb66fab.png)

**Comment by AlexanderYakunin** [comment]
Please check latest build, you probably don't need this anymore

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
