### ISSUE TITLE
[EventRequest] Table 39 “Puchase Line”, GetPurchHeader ()

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4207]
Please add a new publisher event OnBeforeGetPurchHeader as shown in the picture below in the function GetPurchHeader in table 39

![image](https://user-images.githubusercontent.com/54017538/64771715-b78b4080-d54f-11e9-8cde-282dd65c5fd3.png)

Please add the corresponding Integration Event In the bottom of the table

![image](https://user-images.githubusercontent.com/54017538/64771722-bbb75e00-d54f-11e9-924c-2cfa1a594c42.png)

**Comment by AlexanderYakunin** [comment]
Please check latest build, you probably don't need this anymore

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
