### ISSUE TITLE
[EventRequest] Codeunit 80 - OnRun

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4213]
We would like to allow negative invoices, it happens some times when customers return more then they buy. Usually the order at that point is already created. To make this possible we require the following publisher.

            SalesSetup.GET;
            SalesHeader := Rec;
            FillTempLines(SalesHeader,TempSalesLineGlobal);
            TempServiceItem2.DELETEALL;
            TempServiceItemComp2.DELETEALL;

            IF SalesHeader.Invoice THEN
              // Check that the invoice amount is zero or greater
              IF "Document Type" IN ["Document Type"::Invoice,"Document Type"::Order] THEN BEGIN
                ///// START
                SkipNegativeInvoicingAmountCheck := FALSE;
                OnCheckNegativeInvoicingAmountCheck(SalesHeader, VAR SkipNegativeInvoicingAmountCheck);
                IF NOT SkipNegativeInvoicingAmountCheck THEN
                BEGIN
                ///// END
                  TempSalesLineGlobal.CalcVATAmountLines(1,SalesHeader,TempSalesLineGlobal,TempVATAmountLine);
                  IF TempVATAmountLine.GetTotalLineAmount(FALSE,'') < 0 THEN
                    ERROR(TotalInvoiceAmountNegativeErr);
                ///// START
                END;
                ///// END
              END;

            // Header
            CheckAndUpdate(SalesHeader);

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
