### ISSUE TITLE
[EventRequest] Table 5741 “Transfer Line”, ShowDimensions[External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4220]
Please add a new publisher event OnShowDimensions as shown in the picture below in the function ShowDimensions in table 5741

![image](https://user-images.githubusercontent.com/54017538/64777662-fffc2b80-d55a-11e9-90a9-efa76848301d.png)

Please add the corresponding Integration Event In the bottom of the table

![image](https://user-images.githubusercontent.com/54017538/64777670-068aa300-d55b-11e9-9aee-9ff5fa45ea84.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
