### ISSUE TITLE
[EventRequest] Report 7304 “Get Outbound Source Documents”,  Whse. Pick Request - OnAfterGetRecord

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4221]
Please add a new publisher event  OnAfterGetRecordWhsePickRequest in report 7304 on trigger  Whse. Pick Request - OnAfterGetRecord and call it in the start of the trigger

![image](https://user-images.githubusercontent.com/54017538/64778047-93356100-d55b-11e9-9af7-01bcf276a9a4.png)

Please add the corresponding Integration Event In the bottom of the report

![image](https://user-images.githubusercontent.com/54017538/64778063-992b4200-d55b-11e9-8b00-2cf59383f233.png)

**Comment by AlexanderYakunin** [comment]
We already have this event
            trigger OnAfterGetRecord()
            begin
                OnBeforeWhsePickRequestOnAfterGetRecord("Whse. Pick Request", PickWkshTemplate, PickWkshName, LocationCode, LineCreated);
            end;

**Comment by TjaTrimit** [comment]
Okay, then you can ignore this request. Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
