### ISSUE TITLE
[EventRequest] Report 5754 “Create Pick”, SetPickFilters [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4222]
Please add a new publisher event OnBeforeSetPickFilters in report 5753 on SetPickFilters  and call it as shown in the picture

![image](https://user-images.githubusercontent.com/54017538/64778435-70f01300-d55c-11e9-92e0-98d24c0f5914.png)

Please add the corresponding Integration Event In the bottom of the report

![image](https://user-images.githubusercontent.com/54017538/64778478-76e5f400-d55c-11e9-9153-793c2204d5b0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
