### ISSUE TITLE
[EventRequest] Report 5754 “Create Pick”, SetPickFilters [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4223]
Please add a new publisher event OnAfterSetPickFilters in report 5753 on SetPickFilters and call it as shown in the picture

![image](https://user-images.githubusercontent.com/54017538/64778769-c62c2480-d55c-11e9-8b9b-a5cfe7374133.png)

Please add the corresponding Integration Event In the bottom of the report

![image](https://user-images.githubusercontent.com/54017538/64778794-d217e680-d55c-11e9-901e-8bd4633a99c2.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
