### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnBeforeAdjustReorderQty

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#4224]
Please add a new Publisher Call OnBeforeAdjustReorderQty in Procedure AdjustReorderQty of Codeunit 99000854 "Inventory Profile Offsetting"

Add new local Var. IsHandled in Fct. AdjustReorderQty

Add Call of Publisher in procedure AdjustReorderQty

````
+        OnBeforeAdjustReorderQty(OrderQty, SKU, SupplyLineNo, MinQty, DeltaQty, IsHandled);
+        if IsHandled then
+            exit(DeltaQty);
+
         // Copy of this procedure exists in COD5400- Available Management
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnBeforeAdjustReorderQty(OrderQty: Decimal; var SKU: Record "Stockkeeping Unit"; SupplyLineNo: Integer; MinQty: Decimal; var DeltaQty: Decimal; var IsHandled: Boolean)
+    begin
+    end;
````

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
