### ISSUE TITLE
Table 36 - Tableextensions - RecreateSalesLines - global function ?

### ISSUE THREAD

**Issue by kdldk** [microsoft/ALAppExtensions#4226]
I need to recalculate salesline when changing "Customer Price Group" - but the standard function at T36 "RecreateSalesLines" is Local and not available.

Is it possible to make the function global ? - or do I need to clone the function into a tableextension ex. (ChangeCustPriceGrpRecalculateSalesLine)

I think the best way to do it is 

        Modify("Customer Price Group")
        {
            trigger OnAfterValidate()
            var 
            begin
                RecreateSalesLines(FieldCaption("Customer Price Group"));
            end;
        }

and not 

        Modify("Customer Price Group")
        {
            trigger OnAfterValidate()
            var 
            begin
                //ChangeCustPriceGrpRecalculateSalesLine = Clone of "RecreateSalesLine"
                ChangeCustPriceGrpRecalculateSalesLine(FieldCaption("Customer Price Group"));
            end;
        }

**Comment by AlexanderYakunin** [comment]
You need to use event in this function

**Comment by kdldk** [comment]
OK - but stil have to clone the code from T36 because "RecalculateSalesLine" are a local function

**Comment by AlexanderYakunin** [comment]
This function is global. Please recheck 
    procedure RecreateSalesLines(ChangedFieldName: Text[100])
    var
        TempSalesLine: Record "Sales Line" temporary;
