### ISSUE TITLE
[Event Request] Codeunit 99000774 - Calculate Routing Line

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#4227]
Please add a new Publisher in Codeunit 99000774 - Function CreateCapNeed:
![image](https://user-images.githubusercontent.com/40287548/64791836-9a1e9c80-d578-11e9-9f89-77e00ad5b0ea.png)
Please add Paramter "NextCapNeedLineNo" as VAR

**Comment by AndreBreitenbach** [comment]
Sorry, i missed to add "Direction option "Forward,Backward" as a parameter.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by AndreBreitenbach** [comment]
@AlexanderYakunin 
Publisher is available, but Parameter "VAR NextCapNeedLineNo: Integer;" is missing. Could you please reopen this issue and fix this?

**Comment by AndreBreitenbach** [comment]
@AlexanderYakunin: Could you please reopen this issue and fix this?! 
In Codeunit "Calculate Planning Route Line", 'OnAfterCreatePlanningCapNeed' the Parameter is VAR!
Thanks!

**Comment by AndreBreitenbach** [comment]
opened new issue: https://github.com/microsoft/ALAppExtensions/issues/6140
