### ISSUE TITLE
[Event Request] Codeunit 99000810 - Calculate Planning Routing Line

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#4228]
Please add a new Publisher in Codeunit 99000810- Function CreatePlanningCapNeed:
![image](https://user-images.githubusercontent.com/40287548/64793073-bf140f00-d57a-11e9-98f6-d98c43ff0e38.png)
Please add Parameter "NextCapNeedLineNo" as VAR

**Comment by AndreBreitenbach** [comment]
Sorry, just saw that i typed "ProdOrderRtngLine" instead of "PlanningRoutingLine".
Wrong usage of Copy&Paste :)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by AndreBreitenbach** [comment]
Any news on this? This publisher is still missing in 16.0.10798.0?

**Comment by AlexanderYakunin** [comment]
Thank you for reminding! This event have been mistakenly closed and not implemented yet. I reactivated internal request and we will process it this week. Sorry for mistake on our side.

**Comment by AlexanderYakunin** [comment]
This request cannot be implemented due to missing event specification. Please update list of parameters in event and define which parameters should have VAR.

Something like this EventName(Param1, var Param2, Param3)

**Comment by AndreBreitenbach** [comment]
Please implement Publisher as followed:

OnAfterCreatePlanningCapNeed(
VAR NextCapNeedLineNo: Integer; 
PlanningRoutingLine: Record "Planning Routing Line";
ReqLine: Record "Requisition Line"; 
NeedDate: Date; 
StartingTime: Time; 
EndingTime: Time; 
TimeType: option "Setup Time","Run Time"; 
NeedQty: Decimal; 
ConCurrCap: Decimal; 
CalendarEntry: Record "Calendar Entry"; 
LotSize: Decimal; 
RemainNeedQty: Decimal; 
FirstInBatch: Boolean; 
Direction: Option "Forward","Backward"
);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
