### ISSUE TITLE
[Event Request] Codeunit 9800 - OnBeforeStartPermissionRecorder

### ISSUE THREAD

**Issue by RHaest** [microsoft/ALAppExtensions#4229]
Please add a new integration event OnBeforeStartPermissionRecorder in codeunit 9800 with SessionID as a var.

![image](https://user-images.githubusercontent.com/32772769/64840963-954ffc00-d5fd-11e9-8a95-83b053b979cc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
