### ISSUE TITLE
[Event Change] TAB 179 in Function InsertReversalEntry 

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#4231]
Hey,
please include FALedgEntry as a Parameter to Event **OnAfterInsertReversalEntry**, because GlobalVarAccess is no longer available in Wave2.
![grafik](https://user-images.githubusercontent.com/40355993/64842922-eb27a280-d603-11e9-988d-4f34f7c18dd3.png)

![grafik](https://user-images.githubusercontent.com/40355993/64842958-0abecb00-d604-11e9-819d-0b3429b736a5.png)

Thanks in Advance

**Comment by AlexanderYakunin** [comment]
This event is not suitable for FALedgEntry, if you need to add fields to this table, we'd better add event in InsertFromFALedgEntry procedure before TempResersalEntry Insert? This way it can be done for all ledger entry tables, not only for FA Ledger Entry.  

Please confirm.

**Comment by GeekEding** [comment]
Hi Alexander,
That sounds possible for us, but we need the TempRevertTransactionNo in the InsertFromFALedgEntry function too. 

Should look like this I think:
**New Parameter in Function InsertFromFALedgEntry**
![grafik](https://user-images.githubusercontent.com/40355993/65673026-546ad500-e04a-11e9-91ad-c09a5a201065.png)

**New Event in InsertFromFALedgEntry in the end of the function**
![grafik](https://user-images.githubusercontent.com/40355993/65673053-62205a80-e04a-11e9-8a16-c049f37b91d5.png)

**Parameters:**
![grafik](https://user-images.githubusercontent.com/40355993/65673067-69476880-e04a-11e9-9c78-a95740b77f14.png)

Hope this is possible.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
