### ISSUE TITLE
[Event Request] page 255 and 256 - OnBeforeImportPayments/ReturnData (Norwegian Localization) Ref #3559

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4232]
When creating issue #3559 i forgot to include one parameter. Can you add Rec aswell to both events?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
