### ISSUE TITLE
[Event Request] Page 345 Reconciliation: OnBeforeInsertGLAccNetChange

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#4233]
Hi together,

one question about the Event Request [#2597](https://github.com/microsoft/ALAppExtensions/issues/2597):

This new Event is integrated in the actual Cumulative Update: 
![grafik](https://user-images.githubusercontent.com/40355993/64843500-908f4600-d605-11e9-8660-19052a3d37d7.png)

![grafik](https://user-images.githubusercontent.com/40355993/64843328-2a0a2800-d605-11e9-802f-fe2220f7b781.png)

But if I try to use it in the Wave 02 Preview: It is not found: 
![grafik](https://user-images.githubusercontent.com/40355993/64843375-40b07f00-d605-11e9-82d1-5f940f7fb787.png)

See AL Code here:
![grafik](https://user-images.githubusercontent.com/40355993/64844289-9ab24400-d607-11e9-945f-dd9bc84ffc72.png)

Can you integrate it into the Wave 02 Preview too?

Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
