### ISSUE TITLE
[EventRequest] Report 292 “Copy Sales Document”, OnPreReport()

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4234]
Please add a new publisher event OnBeforePreReport in report 292 on OnBeforePreReport and call it as shown in the picture

![image](https://user-images.githubusercontent.com/54017538/64852754-3e0c5480-d61a-11e9-8e7e-977f012f0841.png)

Please add the corresponding Integration Event In the bottom of the report

![image](https://user-images.githubusercontent.com/54017538/64852769-43699f00-d61a-11e9-961d-3845bd344cff.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by TjaTrimit** [comment]
you are very welcome
