### ISSUE TITLE
[EventRequest] codeunit 80 “Sales Post”, LOCAL PostUpdateOrderLine([local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4235]
Please add a new publisher event OnBeforePostUpdateOrderLine in Codeunit 80 on function PostUpdateOrderLine and call it as shown in the image below

![image](https://user-images.githubusercontent.com/54017538/64852862-7dd33c00-d61a-11e9-94cc-2ba65673e0fa.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/64852870-8297f000-d61a-11e9-8ee8-d4c5c6bea05c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
