### ISSUE TITLE
[EventRequest] codeunit 398 “Sales Tax Calculate”, AddSalesLine[external] BC 14-0

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4250]
Please add a new publisher event OnBeforeAddSalesLine in Codeunit 398 on function AddSalesLine and call it as shown in the image below

![image](https://user-images.githubusercontent.com/54017538/64859357-4e2c3000-d62a-11e9-8ab3-a9e66260df49.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/64859364-54baa780-d62a-11e9-9909-eccc9c371e65.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
