### ISSUE TITLE
[EventRequest] codeunit 398 “Sales Tax Calculate”, AddPurchLine [External] BC 14-0

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4251]
Please add a new publisher event OnBeforeAddPurchLine in Codeunit 398 on function AddPurchLine and call it as shown in the image below

![image](https://user-images.githubusercontent.com/54017538/64859525-c3980080-d62a-11e9-85f1-f00f69461145.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/64859533-c8f54b00-d62a-11e9-841b-eff1ab07f2dd.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
