### ISSUE TITLE
[Event Request] Add var to existing publisher in TAB81.OnGetFAVATSetupOnBeforeCheckGLAcc(VAR GenJournalLine : Record "Gen. Journal Line";GLAccount : Record "G/L Account")

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/ALAppExtensions#4253]
Can you add Var for parameter **GLAccount** in existing **Table 81 Gen. Journal Line** publisher:

``OnGetFAVATSetupOnBeforeCheckGLAcc(VAR GenJournalLine : Record "Gen. Journal Line";GLAccount : Record "G/L Account")``

So it's: 
``OnGetFAVATSetupOnBeforeCheckGLAcc(VAR GenJournalLine : Record "Gen. Journal Line";VAR GLAccount : Record "G/L Account")``

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
