### ISSUE TITLE
"Item Tracking Doc. Management".FindInvoiceEntries (External function) leaves the filter on the By-Reference-Parameter)

### ISSUE THREAD

**Issue by finn777** [microsoft/ALAppExtensions#4254]
======
PROBLEM DESCRIPTION:
"Item Tracking Doc. Management".FindInvoiceEntries (External function) leaves the filter on the By-Reference-Parameter
Codeunit 6503 "Item Tracking Doc. Management", [External] function FindInvoiceEntries().
It’s a standard global function to retrieve item tracking information based on a posted sales invoice line. 
It retrieves item tracking information from ItemLedgerEntries and fills a temporary Tracking Specification Buffer but leaves the filter on the By-Reference-Parameter.
+
The same problem for FindShptRcptEntries

BUSINESS IMPACT: 
System does not work as expected. 

BEFORE YOU START:

STEPS TO REPRO
BC 14.x (W1) CU04
1-Create local Docker container: BCONPREM-144-W1
I used script:

===
```
$accept_eula = $true
$containername = 'BCONPREM-144-W1'
$navdockerimage = 'mcr.microsoft.com/businesscentral/onprem:14.4.35602.0-w1'
$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
$licenseFile = "D:\_DEVDOCKER\build.flf"
New-BCContainer  -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -usessl:$false `
                 -updateHosts `
                 -licenseFile $licenseFile `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -includeAL `
                 -memoryLimit 10G `
                 -alwaysPull
```

===
2-Create a new ‘Purchase Order’
Header:
- Vendor = 10000
- Vendor Invoice No. = 1
Line:
- Type = Item
- No. = 80102-T // “Item Tracking Code” = SNALL, no entries for this item
- Location Code = BLUE
- Quantity = 3
Press Line \ Item Tracking Lines, add 3 lines: SN1, SN2, SN3
Post ‘Purchas Order’

3-Create a new ‘Sales Invoice’
Header:
- Customer = 10000
Line:
- Type = Item
- No. = 80102-T
- Location Code = BLUE
- Quantity = 3
Press Line \ Related Information \ Item Tracking Lines, add 3 lines: SN1, SN2, SN3
Post ‘Sales Invoice’
![image](https://user-images.githubusercontent.com/16433990/64939463-b9b01080-d869-11e9-94ee-87428ec91cc3.png)

4-Create a small AL extension:
// Create a call for the external function FindInvoiceEntries() of Cod6503 "Item Tracking Doc. Management“
===

```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
    SalesInvLine: Record "Sales Invoice Line";
    TempTrackingSpecBuffer: Record "Tracking Specification" temporary;
    ItemTrackingDocMgt: Codeunit "Item Tracking Doc. Management";
    begin
        //Message('App published: Hello world');
        SalesInvLine.SetRange("No.",'80102-T');
        SalesInvLine.FindLast();
        ItemTrackingDocMgt.FindInvoiceEntries(TempTrackingSpecBuffer,DATABASE::"Sales Invoice Line", 0, 
                                              SalesInvLine."Document No.", '', 0, SalesInvLine."Line No.", 
                                              SalesInvLine.Description);
        Message('Test 1: %1', TempTrackingSpecBuffer.Count);
        TempTrackingSpecBuffer.Reset();
        Message('Test 2: %1', TempTrackingSpecBuffer.Count);                                 
    end;
}

```
===

![image](https://user-images.githubusercontent.com/16433990/64938821-c92e5a00-d867-11e9-9f70-008a69d23ff7.png)
![image](https://user-images.githubusercontent.com/16433990/64938827-cf243b00-d867-11e9-9489-855779f698f6.png)

 
5-Run the code, you get the following Messages:
Test 1: 1
Test 2: 3
The FindInvoiceEntries-function sets a filter to the TempTrackingSpecBuffer-Variable (by reference) which is not reset, hence you don’t get the correct buffer. 

![image](https://user-images.githubusercontent.com/16433990/64938371-51136480-d866-11e9-93e6-13c91b506285.png)
![image](https://user-images.githubusercontent.com/16433990/64938374-54a6eb80-d866-11e9-832a-08716e3b43c6.png)
![image](https://user-images.githubusercontent.com/16433990/64938381-5b356300-d866-11e9-9443-ee8ceb53ce3c.png)
 
ACTUAL RESULTS
"Item Tracking Doc. Management".FindInvoiceEntries (External function) leaves the filter on the By-Reference-Parameter

PARTNER EXPECTED RESULTS (Customer / Partner / SP)
The partner suggest fix:
 
![image](https://user-images.githubusercontent.com/16433990/64938412-80c26c80-d866-11e9-8594-960a29ac073b.png)

TROUBLESHOOTING
On standard CRONUS There is not a button a user can press where this case would happen, but the function is declared as external and therefore meant as an API to be extended in customization and extension scenarios.

ADDITIONAL TECHNICAL INFORMATION
Standard system has RESET a bit later in the code:

![image](https://user-images.githubusercontent.com/16433990/64938439-95066980-d866-11e9-8dc5-c4824a650fe2.png)

I’ve checked the code history: COD 6503 has been added for NAV 2016 (9.0) release (~ August 2015) ), the function FindInvoiceEntries does not change since this period…

DEV team just add an external tag ~ October 2018
287388 - [Event Request][GitHub #124] [Function Expose] Codeunit 6503 - FindShptRcptEntries, FindInvoiceEntries (106)
https://github.com/microsoft/ALAppExtensions/issues/124
+
The same problem for FindShptRcptEntries
 
![image](https://user-images.githubusercontent.com/16433990/64938484-c41cdb00-d866-11e9-8bc6-b91d5f6aa481.png)

======

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
