### ISSUE TITLE
[Event Request] COD 700 - OnBeforeGetConditionalListPageID

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4255]
Please provide OnBeforeGetConditionalListPageID(RecordRef) publisher with 'Handled' pattern.

Use case: When extending purchase header document types / or duplicating pages, overruling the standard list pages could be needed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
