### ISSUE TITLE
[Event Request] Codeunit 7326 - Whse. Item Tracking FEFO

### ISSUE THREAD

**Issue by hhout** [microsoft/ALAppExtensions#4256]
Hi,

We would like to request an event in in “Whse. Item Tracking FEFO” (CodeUnit 7326) called from “Create Pick” (CU 7312) so we can add extra check(s) on creating an EntrySummary.
For our checks it is required to know from which source document the EntrySummary is created.

**Event:**
```
LOCAL IsItemTrackingBlocked(ItemNo : Code[20];VariantCode : Code[10];LotNo : Code[50];SerialNo : Code[50]) : Boolean
IF LotNoInformation.GET(ItemNo,VariantCode,LotNo) THEN
  IF LotNoInformation.Blocked THEN
    EXIT(TRUE);
IF SerialNoInformation.GET(ItemNo,VariantCode,SerialNo) THEN
  IF SerialNoInformation.Blocked THEN
    EXIT(TRUE);
// START EVENT ++
OnIsItemTrackingBlockedOnAfterBlockedChecks(SourceReservationEntry, ItemNo,VariantCode,LotNo,IsBlocked,Ishandled);
If Ishandled then
  If IsBlocked then
   Exit(True);
// END EVENT --
EXIT(FALSE);
```

**Publisher function:**
```
LOCAL [IntegrationEvent] OnIsItemTrackingBlockedOnAfterBlockedChecks (Var SourceReservationEntry: Record  “Reservation Entry” ;ItemNo : Code[20];VariantCode : Code[10];LotNo : Code[50];VAR IsBlocked : Boolean; VAR IsHandled : Boolean)
```

Thanks in advance!

**Comment by dcenic** [comment]
@AlexanderYakunin As per ISV request, can you please make sure that this new event makes it to the releases/15.1 branch as well as in master branch.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
