### ISSUE TITLE
[Event Request] Codeunit 10752 - OnBeforeSendRequest

### ISSUE THREAD

**Issue by aetxebarria** [microsoft/ALAppExtensions#4257]
As you probably now, in spain there is an inmediate supply of information on VAT, and there are standard objects in NAV that develop this.

There is a codeunit that creates the XML sent to the service. In the header of the created XML, there are 3 URLs, related to the schema, and validated into the server. But depending on the county, the schema is different. Those URLs are defined in global text constants. These are the constants:
-SoapenvTxt
-SiiTxt
-SiiLRTxt
In the onPremise version, we’ve changed the value of those text contants, but of course, in the cloud version, that is not possible.

All this happens in the codeunit 10752. The ideal solution might be to allow to change that values into a configuration table  like the endpoints in the "SII configuration page".
But if not possible, may be we could work with the generated XML suscribing to an event here:

![imagen](https://user-images.githubusercontent.com/41778563/64949722-1e736700-d87a-11e9-9f5e-44c9da4745e6.png)

Thank you

**Comment by opennexoiberica** [comment]
Not only that, but on other occasions it is legally necessary to name the nodes with other names such as <detailleIGIC> and these texts are put into fire in the codeunit so it cannot be resolved or in the next version. Therefore, I believe that access to the complete file is the best way to adapt it now and in the future. We support this request.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by aetxebarria** [comment]
Hello
I'm just looking in the base app of the last version, and I'm not abble to find the event in the codeunit. Is the fix published already?
Thank you very much
