### ISSUE TITLE
[Extension request]change on  Table 39 “Puchase Line”, No.- OnValidate

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4258]
We would like to have the following commented line removed and replaced it with GetPuchHeader function call
see picture

![image](https://user-images.githubusercontent.com/54017538/64954023-acece600-d884-11e9-9124-ffd63ed46219.png)

Reason: It is the only place you are calling GetPuchaseHeader directly, all other places it's being called though the function. we would like sPurchHeader.GET("Document Type","Document No."); to be removed and then insert the function call instead since we have allready requested an eventrequest (issue #4207 ) in GetPuchHeader function. 

![image](https://user-images.githubusercontent.com/54017538/64954478-fe49a500-d885-11e9-931e-c201bf20c078.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
