### ISSUE TITLE
[EventRequest] report 25 - "Account Schedule" TransferValues [local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4260]
Please add a new publisher event OnAfterTransferValues in report 25 on Function transferValues and call it as shown in the picture, and also add the following code:

_**IF DateFilterHidden <> '' THEN BEGIN
  EVALUATE(StartDate,COPYSTR(DateFilterHidden,1,STRPOS(DateFilterHidden,'.')));
  EVALUATE(EndDate,COPYSTR(DateFilterHidden,(STRPOS(DateFilterHidden,'.')+2)));
END;**_

 as seen in the picture

![image](https://user-images.githubusercontent.com/54017538/64956683-79618a00-d88b-11e9-8d1c-d32442d924e2.png)

Please add the corresponding Integration Event In the bottom of the report

![image](https://user-images.githubusercontent.com/54017538/64956798-bcbbf880-d88b-11e9-9f71-d46c06ae2268.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
