### ISSUE TITLE
Codeunit 13 - GLEntry - global variable declaration - SecurityFiltering property - should be set as Ignored

### ISSUE THREAD

**Issue by CBIZGIT** [microsoft/ALAppExtensions#4261]
Codeunit 13 (Bug) - GLEntry - global variable declaration - SecurityFiltering property - should be set as Ignored

Without this an unwanted error can be thrown when GLEntry.FINDLAST is called if the last GLEntry falls outside the security filter! Precedent for this correction is already established in Codeunit 12 in similar usage for same named variable (local).

Thanks

**Comment by atoader** [comment]
@CBIZGIT the correct place to submit event requests is: https://github.com/microsoft/ALAppExtensions

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
