### ISSUE TITLE
[Event-Request] Report 202 - Sales Document - Test (CheckDimValuePosting)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4262]
Following the advice of @AlexanderYakunin, 

> please always open new issue if you cannot find something what should be implemented

`#2177 has been closed for a while now, but we cannot find the solution in the latest docker images. Can you please verify?

- [ ] Solved in BC14

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
