### ISSUE TITLE
[External Function] COD1400 DocumentNoVisibility - Expose ForceShowNoSeriesForDocNo / CheckNumberSeries

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4265]
Following the advice of @AlexanderYakunin, 

> please always open new issue if you cannot find something what should be implemented

#1899 has been closed for a while now, but we cannot find the solution in the latest docker images. Can you please verify?

- [ ] Solved in BC14

**Comment by fvet** [comment]
Seems like ForceShowNoSeriesForDocNo is available on 16.0.10467.0-w1, CheckNumberSeries not?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
