### ISSUE TITLE
[Event Request] - Page 344 - GlobalVarAccess on OnAfterNavigateShowRecords / OnBeforeNavigateShowRecords

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4266]
Following the advice of @AlexanderYakunin, 

> please always open new issue if you cannot find something what should be implemented

#2176 has been closed for a while now, but we cannot find the solution in the latest docker images. Can you please verify?

- [ ] Solved in BC14

**Comment by AlexanderYakunin** [comment]
No, we do not provide GlobalVar Access anymore.,
