### ISSUE TITLE
[Event Request / Application Change] TAB 79 CheckIBAN - IBANError

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4267]
Following the advice of @AlexanderYakunin, 

> please always open new issue if you cannot find something what should be implemented

#2335 has been closed for a while now, but we cannot find the solution in the latest docker images. Can you please verify?

- [ ] Solved in BC14

**Comment by mazhelez** [comment]
The solution is available in _major_ release 15.0 and the releases after it. It was never backported to previous releases.

Make sure you reference the right docker image! 😉
