### ISSUE TITLE
[Application Code] TAB 297 - GetCustomerVATRegistrationNumber / Lbl

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4268]
Following the advice of @AlexanderYakunin, 

> please always open new issue if you cannot find something what should be implemented

#2884 has been closed for a while now, but we cannot find the solution in the latest docker images. Can you please verify?

- [ ] Solved in BC14

**Comment by AlexanderYakunin** [comment]
Seems you are looking for Extensibility Enhancements in 14.X, but we didn't implement it here.  We only do it for Master and therefore this is also available in 15.0 (aka October release)

![image](https://user-images.githubusercontent.com/31849120/65127463-24935000-da00-11e9-9f71-b635e7e7056a.png)
