### ISSUE TITLE
[FunctionVisibilityRequest]Page 161 Purchase Statistics

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#4269]
Due to Polish Localization App building, we need one function in Page 161 to be external. OnAssistEdit for the new field requires to call UpdateVATOnPurchLines function.
Function: UpdateVATOnPurchLines
Current function signature: LOCAL UpdateVATOnPurchLines()
Requested function signature: [External] UpdateVATOnPurchLines()

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
