### ISSUE TITLE
[Event Change] Report 7390 OnBeforeWhseJnlLineInsert

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#4270]
Hi AL team,

we have to insert additional lines for a separate criteria. Therefore we need an additional paramter "NextLineNo" as VAR in the OnBeforeWhseJnlLineInsert:

![image](https://user-images.githubusercontent.com/47382840/65054089-4b547680-d96d-11e9-9aad-c46721654d39.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
