### ISSUE TITLE
[Parameter Request] COD 700 - OnBeforeGetDefaultLookupPageID(RecordRef)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4271]
Function GetDefaultLookupPageIDByVar in COD 700 Page Management has RecRelatedVariant as parameter, but the parameter is lost in the publisher OnBeforeGetDefaultLookupPageID.

Please include **RecordRef** as parameter on OnBeforeGetDefaultLookupPageID as well.

- [ ] Solved in BC14

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
