### ISSUE TITLE
[Event Request] Codeunit 6620 - Copy Document Mgt. - OnBeforeCreateJobPlanningLine

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#4273]
Requesting 1 new event publisher with handled pattern in codeunit 6620 Copy Document Mgt.

**Event**
`LOCAL [IntegrationEvent] OnBeforeCreateJobPlanningLine(SalesHeader : Record "Sales Header";SalesLine : Record "Sales Line";VAR JobContractEntryNo : Integer;VAR IsHandled : Boolean)
`
**Code**
```
LOCAL CreateJobPlanningLine(SalesHeader : Record "Sales Header";SalesLine : Record "Sales Line";JobContractEntryNo : Integer) : Integer
>>> New Code
OnBeforeCreateJobPlanningLine(SalesHeader,SalesLine,JobContractEntryNo,IsHandled);
IF IsHandled THEN
  EXIT;
<<< New Code End

JobPlanningLine.SETCURRENTKEY("Job Contract Entry No.");
JobPlanningLine.SETRANGE("Job Contract Entry No.",JobContractEntryNo);
IF JobPlanningLine.FINDFIRST THEN BEGIN
.
.
.
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
