### ISSUE TITLE
[EventRequest]Codeunit 570 G/L Account Category Mgt.

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#4275]
Due to Polish Localization App building, we need two publishers in CU570. We need to override the initialization of account categories.

Function: OnInitializeCompany

// START
OnBeforeInitializeAccountCategories;
// STOP 
InitializeAccountCategories;
CODEUNIT.RUN(CODEUNIT::"Categ. Generate Acc. Schedules");
// START
OnAfterInitializeAccountCategories;
// STOP

Publishers signatures: 
LOCAL [IntegrationEvent] OnBeforeInitializeAccountCategories()
LOCAL [IntegrationEvent] OnAfterInitializeAccountCategories()

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
