### ISSUE TITLE
[Event Request] Codeunit 6224 - OnBeforeNewChild

### ISSUE THREAD

**Issue by opennexoiberica** [microsoft/ALAppExtensions#4276]
The functionality of the SII for Spain is not fully developed for all communities. Adjustments to 'Fixed texts' are necessary for nodes that cannot be adapted in any other way. With the proposed event it could be adapted for all cases.

**CODEUNIT 6224 XML DOM Management**
AddElementWithPrefix()
**<new> OnBeforeNewChild(var NodeName);**
NewChildNode := XMLNode.OwnerDocument.CreateElement(Prefix,NodeName,NameSpace);

**Comment by opennexoiberica** [comment]
Sorry I closed without wanting the request. PLEASE TREAT AS OPEN.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
