### ISSUE TITLE
[EventRequest] Report 790 Calculate Inventory - Item Ledger Entry - OnPreDataItem

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4278]
We would like to do additional filtering on item ledger entry. To make this possible we would like to request the following publisher. Please also add Item parameter as VAR so we have access to the applied filters.

    { 7209;1   ;DataItem;                    ;
               DataItemTable=Table32;
               DataItemTableView=SORTING(Item No.,Entry Type,Variant Code,Drop Shipment,Location Code,Posting Date);
               OnPreDataItem=BEGIN
                               WhseEntry.SETCURRENTKEY("Item No.","Bin Code","Location Code","Variant Code");
                               Item.COPYFILTER("Bin Filter",WhseEntry."Bin Code");

                               IF ColumnDim = '' THEN
                                 TempDimBufIn.SETRANGE("Table ID",DATABASE::Item)
                               ELSE
                                 TempDimBufIn.SETRANGE("Table ID",DATABASE::"Item Ledger Entry");
                               TempDimBufIn.SETRANGE("Entry No.");
                               TempDimBufIn.DELETEALL;

                               ///// START
                               OnAfterItemLedgerOnPreDataItem(VAR "Item Ledger Entry", VAR Item);
                               ///// END
                             END;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
