### ISSUE TITLE
[EventRequest] Report 6001 Batch Post Service Orders - Service Header - OnAfterGetRecord

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4279]
We have requirement that we can have our own customized service post handling and a system that is able to skip records on certain conditions. To make this possible we would like to request the following publisher in the "Service Header" dataitem:

               OnAfterGetRecord=VAR
                                  IsHandled@11095585 : Boolean;
                                  IsSkipped@11095586 : Boolean;
                                BEGIN
                                  IF CalcInvDisc THEN
                                    CalculateInvoiceDiscount;

                                  Counter := Counter + 1;
                                  Window.UPDATE(1,"No.");
                                  Window.UPDATE(2,ROUND(Counter / CounterTotal * 10000,1));
                                  ///// START
                                  OnHandleServicePost(VAR "Service Header", ReplacePostingDate, ReplaceDocumentDate, PostingDateReq, ShipReq, InvReq, VAR IsHandled, VAR IsSkipped);
                                  IF IsSkipped THEN
                                    EXIT;
                                  IF IsHandled THEN BEGIN
                                    CounterOK := CounterOK + 1;
                                    IF MARKEDONLY THEN
                                      MARK(FALSE);
                                    EXIT;
                                  END;
                                  ///// END
                                  CLEAR(ServPost);
                                  ServPost.SetPostingDate(ReplacePostingDate,ReplaceDocumentDate,PostingDateReq);
                                  ServPost.SetPostingOptions(ShipReq,FALSE,InvReq);
                                  ServPost.SetHideValidationDialog(TRUE);
                                  IF ServPost.RUN("Service Header") THEN BEGIN
                                    CounterOK := CounterOK + 1;
                                    IF MARKEDONLY THEN
                                      MARK(FALSE);
                                  END;
                                END;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
