### ISSUE TITLE
[Event-Request] Codeunit 7301 Whse. Jnl.-Register Line - OnAfterCode

### ISSUE THREAD

**Issue by Jos-Reynders** [microsoft/ALAppExtensions#4280]
Please add an Integration Event OnAfterCode to Codeunit 7301 Whse. Jnl.-Register Line, to be triggered at the end of the local procedure CODE:

LOCAL PROCEDURE Code@2();
VAR
  GlobalWhseEntry@1000 : Record 7312;
BEGIN
  OnBeforeCode(WhseJnlLine);

  WITH WhseJnlLine DO BEGIN
    ...
  END;

  +OnAfterCode(WhseJnlLine);
END;

[Integration]
LOCAL PROCEDURE OnAfterCode@1100084000(VAR WarehouseJournalLine@1100084000 : Record 7311);
BEGIN
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
