### ISSUE TITLE
[EventRequest] Codeunit 6620 Copy Document Mgt. - CopySalesDoc

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4281]
We would like to request the following publisher:

    PROCEDURE CopySalesDoc@16(FromDocType@1007 : Option;FromDocNo@1006 : Code[20];VAR ToSalesHeader@1008 : Record 36);
    VAR
      ...
    BEGIN
      WITH ToSalesHeader DO BEGIN
        ...

        ToSalesLine.SETRANGE("Document Type","Document Type");
        IF CreateToHeader THEN BEGIN
          ///// START
          CopySalesDocOnBeforeInsertToSalesHeader(VAR ToSalesHeader, FromSalesHeader, MoveNegLines);
          ///// END
          INSERT(TRUE);
          ToSalesLine.SETRANGE("Document No.","No.");
        END ELSE BEGIN

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
