### ISSUE TITLE
[EventRequest] Codeunit 6620 Copy Document Mgt. - CopySalesDocUpdateHeader

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4282]
We would like to request an additional parameter 'RecalculateLines' to be added to the already exiting publisher OnBeforeModifySalesHeader.

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
