### ISSUE TITLE
[EventRequest] Codeunit 6620 Copy Document Mgt. - CopyPurchDoc

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4283]
We would like to request the following publisher:

    PROCEDURE CopyPurchDoc@22(FromDocType@1005 : Option;FromDocNo@1004 : Code[20];VAR ToPurchHeader@1017 : Record 38);
    VAR
      ...
    BEGIN
        ...

        ToPurchLine.LOCKTABLE;

        IF CreateToHeader THEN BEGIN
          ///// START
          CopyPurchDocOnBeforeInsertToPurchHeader(VAR ToPurchHeader, FromPurchHeader, MoveNegLines);
          ///// END
          INSERT(TRUE);
          ToPurchLine.SETRANGE("Document Type","Document Type");
          ToPurchLine.SETRANGE("Document No.","No.");
        END ELSE BEGIN

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
