### ISSUE TITLE
[EventRequest] Codeunit 6620 Copy Document Mgt. - CopyPurchLine

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#4285]
We would like to request an additional parameter 'DocLineNo' to the already existing publisher OnAfterInsertToSalesLine. We need it to be able to copy related information from the original document to the new document.

OnAfterInsertToPurchLine(ToPurchLine,FromPurchLine,RecalculateLines,**DocLineNo**);

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
