### ISSUE TITLE
[Event Request] Codeunit 1405,1406,1407 OnBeforeHeaderModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4287]
we Need new Event trigger like OnBeforeSalesShptHeaderModify in codeunit 391:

Codeunit 1405:
OnRun(VAR Rec : Record "Purch. Inv. Header")
PurchInvHeader := Rec;
PurchInvHeader.LOCKTABLE;
PurchInvHeader.FIND;
PurchInvHeader."Payment Reference" := "Payment Reference";
PurchInvHeader."Creditor No." := "Creditor No.";
PurchInvHeader."Ship-to Code" := "Ship-to Code";
//++++++++++++++++++++++++++++++++++++++
OnBeforePurchInvHeaderModify(VAR PurchInvHeader,Rec);
//--------------------------------------
PurchInvHeader.TESTFIELD("No.","No.");
PurchInvHeader.MODIFY;
Rec := PurchInvHeader;

Codeunit 1406:
OnRun(VAR Rec : Record "Return Shipment Header")
ReturnShipmentHeader := Rec;
ReturnShipmentHeader.LOCKTABLE;
ReturnShipmentHeader.FIND;
ReturnShipmentHeader."Ship-to County" := "Ship-to County";
ReturnShipmentHeader."Ship-to Country/Region Code" := "Ship-to Country/Region Code";
//++++++++++++++++++++++++++++++++++++++
OnBeforeReturnShipmentHeaderModify(VAR ReturnShipmentHeader,Rec);
//--------------------------------------
ReturnShipmentHeader.TESTFIELD("No.","No.");
ReturnShipmentHeader.MODIFY;
Rec := ReturnShipmentHeader;

Codeunit 1407:
OnRun(VAR Rec : Record "Return Receipt Header")
ReturnReceiptHeader := Rec;
ReturnReceiptHeader.LOCKTABLE;
ReturnReceiptHeader.FIND;
ReturnReceiptHeader."Bill-to County" := "Bill-to County";
ReturnReceiptHeader."Bill-to Country/Region Code" := "Bill-to Country/Region Code";
ReturnReceiptHeader."Shipping Agent Code" := "Shipping Agent Code";
ReturnReceiptHeader."Package Tracking No." := "Package Tracking No.";
//++++++++++++++++++++++++++++++++++++++
OnBeforeReturnReceiptHeaderModify(VAR ReturnReceiptHeader,Rec);
//--------------------------------------
ReturnReceiptHeader.TESTFIELD("No.","No.");
ReturnReceiptHeader.MODIFY;
Rec := ReturnReceiptHeader;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
