### ISSUE TITLE
Pages 1350 ff Posted Sales Shipment - Update

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4288]
As Pages 1350-1353 are created to update posted documents we Need the same pages and codeunits also for 
Table 120 "Purch. Rcpt. Header", 112 "Sales Invoice Header", 114 "Sales Cr.Memo Header", 124 "Purch. Cr. Memo Hdr."

**Comment by RomanZanizdra** [comment]
Hi @GuntherGebauer.
What particular fields do you expect to be allowed for update on the mentioned pages?

**Comment by GuntherGebauer** [comment]
In Page 1352 "Posted Return Shpt. - Update" the ship-to fields may be updated, so we would need the same for Table 120 on a new page.

Additional we have copied the fields from Page 1350 "Posted Sales Shipment - Update" from table 110 also to purchases, e.g. table 120, so we would like than to extend the new page with those fields "Shipping Agent Code", "Shipping Agent Service Code", "Package Tracking No." and additional individual fields.

Also other fields regarding shipment/receipt may be updated like "Transaction Specification".

So the new codeunits must all have Event trigger to handle individual fields as well.

For 112 "Sales Invoice" and 114 "Sales Cr. Memo Header" we have of course also individual fields to be updated in the same way as the Standard does this for 122 "Purch. Inv. Header" and 124 "Purch. Cr. Memo Hdr.". In special we would like to update "Salesperson Code", "GLN Sell to Cust.", "GLN Bill to Cust.", "GLN Ship to Adr."

**Comment by RomanZanizdra** [comment]
If I correctly understood the change related to pages 1350-1353 they show fields which was available for editing on the posted document pages. I don't see such fields for example on the Posted Sales Invoice or Posted Purchase Credit Memo. So may be just adding fields "the same as for ..." is not an option. Do i understand correctly that you need to update your own fields based on the standard page? If so then you can just use an extension for that purpose. If not then i suggest to create a topic on the ideas site with particular list of fields to be allowed for edition and let other people to overview and vote for that. 
Does it make sense?

**Comment by RomanZanizdra** [comment]
Any feedback?

**Comment by RomanZanizdra** [comment]
@GuntherGebauer ?

**Comment by GuntherGebauer** [comment]
You  do not think that "Package Tracking No." and "Shipping Agent Code"  is needed as well for table 120 and 6650? We need both for our customers and then it would be better to have the same logic in Standard. 
But I can add those to ideas.

**Comment by RomanZanizdra** [comment]
@GuntherGebauer  I'm not about these particular fields. I've just explained what was the basis for change. And, yes, please create request on the ideas. Let's give PMs and others the possibility to observe requirements and vote for them. 
Can we close current issue for now?
