### ISSUE TITLE
[Event Request] Codeunit 22 - OnafterInsertCapValueEntries in PostOutput

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#4289]
We need a new Publisher in CU22 - Function "PostOutput"

![image](https://user-images.githubusercontent.com/40287548/65229099-f67b4200-dacb-11e9-97a9-09ad622d2f07.png)

Both Parameters should be "by Reference".
Thanks

**Comment by AndreBreitenbach** [comment]
Please add CalledFromAdjustment and PostToGL (both Boolean) as Parameters.
![image](https://user-images.githubusercontent.com/40287548/65303243-c3918680-db7d-11e9-8c19-7e7f30925727.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
