### ISSUE TITLE
[EventRequest] Table 5740 Transfer Header - AddTransferLineFromReceiptLine

### ISSUE THREAD

**Issue by SigfredoBeerman** [microsoft/ALAppExtensions#4290]
An event is request to subscribe after transfer line is added from receipt

**Comment by AlexanderYakunin** [comment]
Sigfredo, this is partner area, why do you ask for event?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
