### ISSUE TITLE
[Event Request] TAB 37 Sales Line - UpdateDates()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#4291]
Could you please add a new event in TAB 37 Fct. UpdateDates():

```
LOCAL UpdateDates()
// New Event ...
IsHandled := FALSE;
OnBeforeUpdateDates(Rec,IsHandled);
IF IsHandled THEN
  EXIT;
// ... New Event

IF CurrFieldNo = 0 THEN BEGIN
  PlannedShipmentDateCalculated := FALSE;
  PlannedDeliveryDateCalculated := FALSE;
END;
IF "Promised Delivery Date" <> 0D THEN
  VALIDATE("Promised Delivery Date")
ELSE
  IF "Requested Delivery Date" <> 0D THEN
    VALIDATE("Requested Delivery Date")
  ELSE
    VALIDATE("Shipment Date");

OnAfterUpdateDates(Rec);
```
Publisher:

`LOCAL [IntegrationEvent] OnBeforeUpdateDates(VAR SalesLine : Record "Sales Line";VAR IsHandled : Boolean)`

A similar event is requested for Tab 39 Purchase Line: https://github.com/microsoft/ALAppExtensions/issues/4216 

many thanks
stefan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
