### ISSUE TITLE
[Event Request] Codeunit 393 Reminder-Issue 

### ISSUE THREAD

**Issue by DMSDevTSO** [microsoft/ALAppExtensions#4292]
Hello, 
Codeunit 393 
Function OnRun

In this function we would need a event as following: 

![image](https://user-images.githubusercontent.com/55543353/65248661-d0b56380-daf2-11e9-9f21-af04ed25982f.png)

![image](https://user-images.githubusercontent.com/55543353/65248572-a95e9680-daf2-11e9-8ef8-9e1102d2a7ab.png)

![image](https://user-images.githubusercontent.com/55543353/65248422-74524400-daf2-11e9-9d0b-4be9e0a8a006.png)

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
