### ISSUE TITLE
table 5902 Local CopyFromServItem

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4293]
Is it possible to make this one be seen for the table extension which extends table 5902?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Teming** [comment]
It is still shown as Local Procedure in BC 15.  Did we miss something?  

![image](https://user-images.githubusercontent.com/49729094/68875494-ed27e380-06d0-11ea-8636-9ee1e83f4533.png)

**Comment by Teming** [comment]
Should I open a new issue case or is there any way to reopen this case?  Thanks.
