### ISSUE TITLE
[Function Request] TempBlob TryDownloadFromUrl

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/ALAppExtensions#4294]
We've been looking at the breaking changes and [the TempBlob changes are rather big and very breaking](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md#blob-storage-module).

There's two breaking changes here that are an issue for us:
1. No direct access to BLOB field. We've been using this in reports as we generate some images externally.
2. TryDownloadFromUrl is such a nice function for us, because again, we're often getting images from external sources. I know we can reproduce this with http request, but it's a lot more lines.

At this point we're looking at creating our own internal temp blob table just because of these two.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by grobyns** [comment]
Hi,

regarding point 1:
I do not know your code so I do not know how you retrieve the images you generate externally but I imagine you would use streams, not the blob field directly. You can of course still add your own blob field(s) if you really need to.

regarding point 2:
TryDownloadFromUrl is not a safe method. It could be used to read files from disk on the server which we do not want to allow. The IsAllowedPath was added for that reason. The function also uses the WebClient class which is not recommended and the HttpClient class should be used instead.
As you mentioned, you can add your own helper method to download the data so that is a good option.

br/Gert

**Comment by mjmatthiesen** [comment]
@grobyns:
1: Ignore the source. We want the blob field because we are feeding it to reports. This is very common practise for on the fly data generation for reports. Right now it seems like we need all the steps from 2 to do this.

2:
It's really just the aspect of going from one line to half a dozen.
`http.get(url, response);
response.content.read(in);
tempblob.createoutstream(out);
copystream(out, in);
recref.settable(recwithblob)
tempblob.torecref(recref, blobfield)`
Now this will end up having to live in helper functions, common lib, something, because you don't want to do this every time. This is what trydownload should become.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by grobyns** [comment]
Hi,

I'm not sure what more is needed here, the way to fix these issues is as you say, to build your own helper methods.

br/Gert

**Comment by mjmatthiesen** [comment]
I'd argue that you've ended up removing functionality that many many ISVs/partners now have to reintroduce, potentially badly.

In general, this entire move to AL and the restructuring is good, but we shouldn't be seeing a reduction of functionality as a result.

**Comment by JesperSchulz** [comment]
Closing issue as per Gert's comment and:
1) we won't be exposing the internals of our BlobStorage module to grant access to the blob field. The idea of creating that module was to hide the internal implementation details, in case we'd want to replace those with something else one day. By exposing the internals, we again will be tied to the current (subideal) design. Please do create your own TempBlob if it is needed - we would prefer other developers to move away from using TempBlob.
2) We will not be reintroducing an unsafe method. But we may look into creating a safe replacement. For now, please use the code you suggested.
