### ISSUE TITLE
[Event Request] Page 1350,  1351, 1352 and 1353 - OnAfterRecordChanged

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4295]
Hi. Can you add OnAfterRecordChanged in function RecordChanged in page 1350,  1351, 1352 and 1353?

Something like this:
![image](https://user-images.githubusercontent.com/46031720/65302957-f71fe100-db7c-11e9-8296-5d86ad9c1c16.png)

Edit: 
Can you also add the xRecord as parameter? 
Example: xSalesShipmentHeader in page 1350.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
