### ISSUE TITLE
Add Field "Variant Code"

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#4297]
Hi,

we need field "Variant Code" Code [10] to be added to tables 
5005271(Delivery Reminder Line) and 
5005273(Issued Deliv. Reminder Line).
This makes sense, since in all other tables where there is the number, there is also the variant code.

Thanks

**Comment by AlexanderYakunin** [comment]
Thank you for your suggestion! We accept and complete such suggestions from aka.ms/bcideas portal, using votes. Please publish your suggestion there.
