### ISSUE TITLE
[event request] page 131

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#4298]
Hi, in https://github.com/microsoft/AL/issues/3400 i requested an event and it was confirmed and set to "ships in future update" in august 2018. Still it seems like it wasnt implemented. Please kindly add the event :)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
