### ISSUE TITLE
[Event Request] Signature Change codeunit: "Inventory Posting To G/L"

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#4299]
We Need the following signature
1.

codeunit:  "Inventory Posting To G/L"

Trigger  OnPostInvtPostBufferOnBeforeFind

(var GlobalInvtPostBuf: Record "Invt. Posting Buffer";   var TempGLItemLedgRelation: Record "G/L - Item Ledger Relation")

 

2.
Codeunit:  Gen. Jnl.-Post Line

Trigger:  OnAfterInsertGlobalGLEntry

(var TempGLEntryBuf: Record "G/L Entry"; var GlobalGLEntry: Record "G/L Entry"; var NextEntryNo: Integer;)

**Comment by Bssivivek** [comment]
@shashiBssi thanks!!
Hi Team - can you please approve this request on priority please. this is really urgent for us.

**Comment by AlexanderYakunin** [comment]
We already have that:

1.     [IntegrationEvent(TRUE, false)]
    local procedure OnPostInvtPostBufferOnBeforeFind(var GlobalInvtPostBuf: Record "Invt. Posting Buffer"; var TempGLItemLedgRelation: Record "G/L - Item Ledger Relation")
    begin
    end;

2.     [IntegrationEvent(false, false)]
    local procedure OnAfterInsertGlobalGLEntry(var GLEntry: Record "G/L Entry"; var TempGLEntryBuf: Record "G/L Entry"; var NextEntryNo: Integer)
    begin
    end;
