### ISSUE TITLE
[Event Request] OnBeforeShowAttachment

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#4300]
Hi, 
we need a new Publisher in Table 5065 Interaction Log Entry.
Place:
![image](https://user-images.githubusercontent.com/34675109/65328592-f5730f00-dbb6-11e9-83f8-fb92511b3a09.png)
Publisher:
![image](https://user-images.githubusercontent.com/34675109/65328717-3ec35e80-dbb7-11e9-94f0-3079ea093391.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
