### ISSUE TITLE
[External Function] REP 2000019 - SetPaymJnlLine

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4302]
Please set global function 'SetPaymJnlLine' to external in report 2000019

- [ ] Solved in BC14

Duplicate of #2773 (worked previously when using 'Internal' as target, using target as 'Extension' failed)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
