### ISSUE TITLE
[External Functions] COD 2000000 PmtJrnlManagement - Mod97Test ...

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4303]
Can you please set functions Mod97Test / PrintTestReport / GetAccount to external?

- [ ] Solved in BC 14

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
