### ISSUE TITLE
[Event Request] TAB 38 - OnAfterGetReportSelectionsUsageFromDocumentType

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4304]
It was mentioned in #260 that an event publisher **OnAfterGetReportSelectionsUsageFromDocumentType** would be made available on TAB 38, but can't find the implementation.

PS: TAB 38 GetReportSelectionsUsageFromDocumentType seems like a duplicate (besides the DocTxt) of COD 229 GetPurchDocTypeUsage. Both should at least support the same document types or maybe even joined into one function?

![image](https://user-images.githubusercontent.com/25268332/65376678-1add4700-dca3-11e9-8df0-3bc96f398a9b.png)

- [ ] Solved in BC14

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
