### ISSUE TITLE
[Event Request] COD 80 / 90 - OnBeforePostItemTrackingErrors

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4305]
COD 80 - **PostItemTracking** - We would like to skip the errors in case RemQtyToBeInvoiced is higher than the Qty to receive / Qty to ship.
- [ ] Solved in BC14

Therefore, can you please move the code below to 2 new procedures:
- '**ThrowInvoiceGreaterThanReturnReceiptErr**' with a OnBefore... publisher with access to SalesLine and include the Handled pattern to skip the error
- '**ThrowQuantityToInvoiceGreaterErr**' with a OnBefore... publisher with access to SalesLine and include the Handled pattern to skip the error.

![image](https://user-images.githubusercontent.com/25268332/65377147-bcb36280-dca8-11e9-9694-9d18ba81d64e.png)

COD 80 - **PostItemTrackingForShipment** - We would like to skip the ShipmentInvoiceErr error.
- [ ] Solved in BC14

Therefore, can you please move the code below to a new procedure:
- '**ShipmentInvoiceErr**' with a OnBefore... publisher with access to SalesLine and include the Handled pattern to skip the error.

![image](https://user-images.githubusercontent.com/25268332/65377210-61ce3b00-dca9-11e9-9382-25866a58ce85.png)

COD 90- **PostItemTracking** - We would like to skip the errors in case RemQtyToBeInvoiced is higher than the Qty to ship / Qty to receive.
- [ ] Solved in BC14

Therefore, can you please move the code below to 2 new procedures:
- '**ThrowInvoiceGreaterThanReturnShipmentErr**' with a OnBefore... publisher with access to PurchLine and include the Handled pattern to skip the error
- '**ThrowQuantityToInvoiceGreaterErr**' with a OnBefore... publisher with access to PurchLine and include the Handled pattern to skip the error.

![image](https://user-images.githubusercontent.com/25268332/65377232-a6f26d00-dca9-11e9-8795-7f0b44bf34e5.png)

COD 90 - **PostItemTrackingForReceipt** - We would like to skip the ReceiptInvoicedErr error.
- [ ] Solved in BC14

Therefore, can you please move the code below to a new procedure:
- '**ReceiptInvoicedErr**' with a OnBefore... publisher with access to PurchLine and include the Handled pattern to skip the error.

![image](https://user-images.githubusercontent.com/25268332/65377243-d1442a80-dca9-11e9-92c7-acac05e19f1b.png)

COD 90 - **PostItemTrackingForShipment** - We would like to skip the ReturnShipmentInvoicedErrerror.
- [ ] Solved in BC14

Therefore, can you please move the code below to a new procedure:
- '**ReturnShipmentInvoicedErr**' with a OnBefore... publisher with access to PurchLine and include the Handled pattern to skip the error.

![image](https://user-images.githubusercontent.com/25268332/65377248-e9b44500-dca9-11e9-995e-e82928b42cec.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
