### ISSUE TITLE
[Event Parameters / External Functions] COD 397 Initialize / AttachFile / Send 

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4306]
While awaiting for a final 'multi attachment' mail solution, would you be able to at least provide access to the needed functions so we can at least build our own multi attachment mail via the event **OnBeforeCreateAndSendMessage** in codeunit 397 mail? 

We currently miss:

- **Initialize** : please set to 'External'
- **OnBeforeCreateAndSendMessage** : Please include the '**Runmodal**' parameter
- **AttachFile** : please set to 'External'
- **Send** : please set to 'External'

![image](https://user-images.githubusercontent.com/25268332/65391847-0619b580-dd6e-11e9-8e89-e09066d9678a.png)

I was thinking of using **OnBeforeCreateMessage** instead. However, this lacks the Mail codeunit as '**Sender**' (because we need to build further on the OutlookMessageHelper global), so we would be able calling **AttachFile** (please set to 'External') from here... (although I'm afraid OutlookMessageHelper.AttachmentFileNames.Clear will clear my attachments)

A better option might be adding an OnAfterCreateMessage publisher with access to the Mail codeunit as '**Sender**' 

![image](https://user-images.githubusercontent.com/25268332/65407456-dce73c80-dde2-11e9-882a-cabc270cfe33.png)

- [ ] Solved in BC14

**Comment by AlexanderYakunin** [comment]
Assigning to team @JesperSchulz @AndreiPanko

**Comment by darjoo** [comment]
Hi @fvet, do you require this in 14 or 15?
If 15, please take a look at the SMTPMail.Codeunit.al and see if what we have done to that works for you.

-Darrick
