### ISSUE TITLE
[Event Parameter] COD 9520 - OnBeforeSentViaSMTP

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4307]
Please provide var acces to the '**SMTPMail**' variable in COD 9520 **OnBeforeSentViaSMTP**.
We'd like to call '**SMTPMail**.AddAttachment' in the subscriber so we can include multiple attachments to the mail.
Please also make function **AddAttachment** in COD 400 external.

Another option might be to have an **OnAfterCreateMessage** in COD 400 with var access to the **Sender** (SMTP Mail Codeunit) or the  **Mail** (dotNet) variable, in combination with the function **AddAttachment** to be put to External.

- [ ] Solved in BC14

**Comment by AlexanderYakunin** [comment]
First part if not a problem, but AddAttachment only works OnPrem.

**Comment by fvet** [comment]
Ok for addattachment on prem. We need to support onprem but without modifying the base app.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
