### ISSUE TITLE
[External] Codeunit 7000 Functions externally available

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4309]
Could you please make following functions in Codeunit 7000 externally available?
IsInMinQty
ConvertPriceToVAT
ConvertPriceToUoM
ConvertPriceLCYToFCY

**Comment by ChrisBlankDe** [comment]
We are waiting for ConvertPriceToVAT() and ConvertPriceLCYToFCY() to bring our App to AppSource and no reactions from Microsoft.... a little bit discouraging.

Need further informations? @AlexanderYakunin

**Comment by AlexanderYakunin** [comment]
This is done for 15.1, you should get it shortly

**Comment by ChrisBlankDe** [comment]
Found it in the preview. THX
