### ISSUE TITLE
 OnPostInvtPostBufferOnBeforeFind   Signature Change request

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#4310]
Current 
codeunit: "Inventory Posting To G/L"

Trigger OnPostInvtPostBufferOnBeforeFind
![image](https://user-images.githubusercontent.com/38439762/65424992-97e6f880-de2a-11e9-85f4-07abe6a1826b.png)

Required

(var GlobalInvtPostBuf: Record "Invt. Posting Buffer"; var TempGLItemLedgRelation: Record "G/L - Item Ledger Relation")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Bssivivek** [comment]
@AlexanderYakunin it should be great if you can let us know the ETA because our product release for V15 is still pending because of this. It should be great if you can help us out on this.
