### ISSUE TITLE
OnAfterInsertGlobalGLEntry  Signature Change request

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#4311]
Current
Codeunit: Gen. Jnl.-Post Line

Trigger: OnAfterInsertGlobalGLEntry

![image](https://user-images.githubusercontent.com/38439762/65425243-29566a80-de2b-11e9-8845-5096318d56e8.png)

Required
(var TempGLEntryBuf: Record "G/L Entry"; var GlobalGLEntry: Record "G/L Entry"; var NextEntryNo: Integer;)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Bssivivek** [comment]
@AlexanderYakunin it should be great if you can let us know the ETA because our product release for V15 is still pending because of this. It should be great if you can help us out on this.
