### ISSUE TITLE
Breaking change in Purchase Line - TestStatusOpen

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#4312]
Issue #3717 was implemented in the last update, but not as requested. Instead of applying the logic from Purchase Line to Sales Line as requested, it was done the other way around.

This is breaking our solution. The OnBeforeTestStatusOpen is used to suspend the status-check in specific situations. Now it is not possible anymore to bypass the status-check by subscribing to this event. I don't see any reason why the OnBeforeTestStatusOpen is moved down a few lines, it doesn't make any sense to me.

Please revert the change asap and, please, please, never introduce this kind of breaking changes again with cumulative updates!

@jobulsin @JesperSchulz

**Comment by JesperSchulz** [comment]
Thanks for reporting. I would guess this was a mistake, as we may not do breaking changes without one years prior announcement - not in cumulative updates and not in major releases either! Now I wonder how we can make gated checks to prevent this from happening again???!!! So you're saying an even was moved? That should be rather hard to detect... I'll brainstorm a little :-)
Again, thanks for letting us know. A bug was created and we will be fixing this asap.

**Comment by AlexanderYakunin** [comment]
I wonder how OnBeforeTestStatusOpen could have been used to suspend status check, this event is not handled and does not have access to SuspendStatusCheck variable? I assume you manipulated by  "System-Created Entry" field to skip it, but this is not a good idea.

Event was moved simply to provide access to Sales/Purchase Header variable, it makes sence after GetPurchHeader, not before.

Anyway, we can add event before if StatusCheckSuspended then. Does it help?

    procedure TestStatusOpen()
    begin
        OnTestStatusOpenOnBeforeStatusCheckSuspended(Rec, StatusCheckSuspended); // NEW
        if StatusCheckSuspended then
            exit;

        GetPurchHeader;
        OnBeforeTestStatusOpen(Rec, PurchHeader);

        if not "System-Created Entry" then
            if HasTypeToFillMandatoryFields then
                PurchHeader.TestField(Status, PurchHeader.Status::Open);

        OnAfterTestStatusOpen(Rec, PurchHeader);

**Comment by ajkauffmann** [comment]
That's easy... You can suspend status check just by calling the function SuspendStatusCheck() on the Rec variable that is passed with the OnBeforeTestStatusOpen event.

I believe you shouldn't pass the global variable StatusCheckSuspended. Keep that variable hidden (that's called encapsulation in object oriented design 😉). Instead, the function SuspendStatusCheck() perfectly does the job. 

So, if the goal is to call GetPurchHeader() before, which makes a lot of sense, then just move GetPurchHeader up to before the event. No need to introduce yet another event. Code will look like this:

```
procedure TestStatusOpen()
begin
    GetPurchHeader;
    OnBeforeTestStatusOpen(Rec, PurchHeader);
    
    if StatusCheckSuspended then
        exit;

    if not "System-Created Entry" then
        if HasTypeToFillMandatoryFields then
            PurchHeader.TestField(Status, PurchHeader.Status::Open);

    OnAfterTestStatusOpen(Rec, PurchHeader);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
