### ISSUE TITLE
[Event Request] Codeunit 365 Format Address for function SalesInvShipTo

### ISSUE THREAD

**Issue by Yehudo** [microsoft/ALAppExtensions#4314]
We need an event publisher **OnBeforeSalesInvShipTo(AddrArray,SalesInvHeader,Handled,Result)** with handled pattern and result at the begining of the function **SalesInvShipTo** in codeunit 365 (Format Address).

![grafik](https://user-images.githubusercontent.com/53296632/65486418-abcf4080-dea4-11e9-84a7-ddb31fd1cf18.png)

Just like the one in function SalesHeaderShipTo:

![grafik](https://user-images.githubusercontent.com/53296632/65486599-2e580000-dea5-11e9-90f9-e368c8a9f8ce.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
