### ISSUE TITLE
[EventRequest] codeunit 6622 “Copy Document Mgt.”, RecalculatePurchLine [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4315]
Please add a new publisher event OnAfterRecalculatePurchLine  in Codeunit 6622 on function RecalculatePurchLine and call it as shown in the image below after the IF statement.

![image](https://user-images.githubusercontent.com/54017538/65486704-78d97c80-dea5-11e9-9394-1b76fbfeff08.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/65486717-7e36c700-dea5-11e9-867d-447a4f297dfa.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
