### ISSUE TITLE
[EventRequest] codeunit 6622 “Copy document mgt”,  RecalculatePurchLine [Local] 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4316]
Please add a new publisher event OnBeforeRecalculatePurchLine in Codeunit 6622 on function RecalculatePurchLine and call it in the start of the function

![image](https://user-images.githubusercontent.com/54017538/65486864-e1c0f480-dea5-11e9-8dec-031b50cee262.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/65486866-e7b6d580-dea5-11e9-8d30-c86d530cfb0e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by TjaTrimit** [comment]
What is the status on this publisher, we can't seem to find it in the currentbuild 15.2 .
