### ISSUE TITLE
[EventRequest] codeunit 6620 “Copy Document Mgt.”, CopyPurchLine [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4317]
Please add a new publisher event OnBeforeUpdatePurchaseLine  in Codeunit 6620 on function CopyPurchLine and call it as shown in the image below 

![image](https://user-images.githubusercontent.com/54017538/65486893-f56c5b00-dea5-11e9-8a19-f65de01ca02b.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/65486902-fac9a580-dea5-11e9-87af-ec95474acc41.png)

**Comment by AlexanderYakunin** [comment]
We already have event slightly below, maybe this is sufficient for your purpose:

    local procedure UpdatePurchLine(var ToPurchHeader: Record "Purchase Header"; var ToPurchLine: Record "Purchase Line"; var FromPurchHeader: Record "Purchase Header"; var FromPurchLine: Record "Purchase Line"; var CopyThisLine: Boolean; RecalculateAmount: Boolean; FromPurchDocType: Option; var CopyPostedDeferral: Boolean)
    var
        VATPostingSetup: Record "VAT Posting Setup";
        DeferralDocType: Integer;
    begin
        OnBeforeUpdatePurchLine(
          ToPurchHeader, ToPurchLine, FromPurchHeader, FromPurchLine,
          CopyThisLine, RecalculateAmount, FromPurchDocType, CopyPostedDeferral);
