### ISSUE TITLE
[EventRequest] codeunit 6620 “Copy Document Mgt.”, CopySalesLine [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4318]
Please add a new publisher event OnBeforeUpdateSalesLine in Codeunit 6620 on function CopySalesLine and call it as shown in the image below

![image](https://user-images.githubusercontent.com/54017538/65487263-d15d4980-dea6-11e9-87f6-9c24e7812562.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/65487032-467c4f00-dea6-11e9-92f1-de18833f3451.png)

**Comment by AlexanderYakunin** [comment]
Same question as for purchase side, can you use event below

    local procedure UpdateSalesLine(var ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; var FromSalesHeader: Record "Sales Header"; var FromSalesLine: Record "Sales Line"; var CopyThisLine: Boolean; RecalculateAmount: Boolean; FromSalesDocType: Option; var CopyPostedDeferral: Boolean)
    var
        VATPostingSetup: Record "VAT Posting Setup";
        DeferralDocType: Integer;
    begin
        OnBeforeUpdateSalesLine(
          ToSalesHeader, ToSalesLine, FromSalesHeader, FromSalesLine,
          CopyThisLine, RecalculateAmount, FromSalesDocType, CopyPostedDeferral);
