### ISSUE TITLE
[Event Request] Codeunit 1305 - OnBeforeCreateSalesInvoiceLineLoop

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#4319]
Hi AL team,

we need the following event publisher similiar to "OnBeforeTransferQuoteLineToOrderLineLoop" in codeunit 86:

![image](https://user-images.githubusercontent.com/47382840/65487279-d8845780-dea6-11e9-9b6b-f126745b0187.png)

All parameters should be passed by var:
OnBeforeCreateSalesInvoiceLineLoop(VAR SalesQuoteLine, VAR SalesQuoteHeader, VAR SalesInvoiceHeader, VAR IsHandled);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
