### ISSUE TITLE
[EventRequest] codeunit 6622 “Copy Document Mgt.”, CheckItemAvailability [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4320]
Please add a new publisher event OnBeforeAvailabilityCheck in Codeunit 6622 on function CheckItemAvailability and call it as shown in the image below 

![image](https://user-images.githubusercontent.com/54017538/65487350-0073bb00-dea7-11e9-8e87-633f094f474b.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/65487362-049fd880-dea7-11e9-880a-0ba5eb689042.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
