### ISSUE TITLE
[Event Request] Table 37 - CheckItemAvailable

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4321]
Hi!

We need an additional event in the end of the CheckItemAvailable function on the Sales Line table.
![image](https://user-images.githubusercontent.com/55734714/65491598-a75c5500-deaf-11e9-89e5-8bc43b2c6049.png)

![image](https://user-images.githubusercontent.com/55734714/65492756-c9ef6d80-deb1-11e9-8db7-f831bdc16816.png)

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
