### ISSUE TITLE
[BC15 | Module "Temp Blob"] Copying the contents from Blob to Blob in the new Temp Blob module leads to unwanted results and errors

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/ALAppExtensions#4323]
Unfortunately, I noticed that existing functionalities can no longer be implemented because the methods for the streams in connection with the code unit "Temp Blob" were changed. This mainly includes the stream functions.

In the past, for example, you could do the following:

`TempBlob.Blob := TempBlob2. Blob`

So you could simply copy the content from one to the other. This is no longer possible at all.

If I try to copy the whole thing with streams now, e.g. as follows:

```
TempBlob.CreateInStream(IStream);
TempBlob2.CreateOutStream(OStream);
CopyStream(OStream,IStream);
```

Then I can transfer the content, but unlike the top direct solution, both the IStream and OStream positions have been changed to EOS. I also don't have the possibility to change them anymore. This doesn't change when I create a new InStream. The position remains fixed.

```
TempBlob3.CreateOutStream(OStream2);
TempBlob2.CreateInStream(IStream2);
CopyStream(OStream2,IStream2); // Empty Temp Blob
```

This, in my view, KO criteria for the use of TempBlob, and leads to the fact that existing functions can no longer be used. From my point of view, there is an urgent need for improvement here.

**Comment by grobyns** [comment]
Hi,

Can you provide a complete repro? I'm not having any luck reproducing the issue. Here's the method I used _(just add to any page and run)_
```
    trigger OnOpenPage()
    var
        TempBlob: Codeunit "Temp Blob";
        TempBlob2: Codeunit "Temp Blob";
        TempBlob3: Codeunit "Temp Blob";
        InStream1: InStream;
        InStream2: InStream;
        InStream3: InStream;
        OutStream1: OutStream;
        OutStream2: OutStream;
        OutStream3: OutStream;
        BlobString: Text;
    begin
        TempBlob.CreateOutStream(Outstream1);
        OutStream1.WriteText('Hello World!');

        TempBlob.CreateInStream(InStream1);
        TempBlob2.CreateOutStream(Outstream2);
        CopyStream(OutStream2, InStream1);

        TempBlob2.CreateInStream(InStream2);
        Tempblob3.CreateOutStream(OutStream3);
        CopyStream(OutStream3, InStream2);

        TempBlob3.CreateInStream(InStream3);
        InStream3.ReadText(BlobString);

        Message(BlobString);
    end;
```
The result as expected is a message with 'Hello World!'

I'm not sure what the difference is between this code and yours.

br/Gert

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by grobyns** [comment]
little mishap with the bot there... I'm closing the issue as there was no reply for 7d.
thx,
Gert
