### ISSUE TITLE
[Event Request] Table 37 - OpenItemTrackingLines

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4324]
Hi!

We need an additional event before the call to ReserveSalesLine.CallItemTracking in the OpenItemTrackingLines function on the Sales Line table. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/65498216-cb259800-debb-11e9-969c-e2723b21b6e0.png)

![image](https://user-images.githubusercontent.com/55734714/65498280-e395b280-debb-11e9-95cf-8d60ca13ae23.png)

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by andersnordmann** [comment]
By mistake I never requested the IsHandled to be a var parameter. Could this be remedied?
Thanks, Anders
