### ISSUE TITLE
[Event Request] COD 99000889 – AvailabilityManagement

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4325]
Please add integration event as described below in COD 99000889 in order to be able to complete our Intercompany extension

**[IntegrationEvent]** OnBeforeSourceTypeCase(VAR OrderPromisingLine : Record "Order Promising Line")

**[IntegrationEvent]** OnAfterSourceTypeCase(VAR OrderPromisingLine : Record "Order Promising Line")

Please add new publisher event “**OnBeforeSourceTypeCase** in COD 99000889 – AvailabilityManagement in function CalcAvailableToPromiseLine

Please add new publisher event **OnAfterSourceTypeCase** in COD 99000889 – AvailabilityManagement  in function CalcAvailableToPromiseLine

![image](https://user-images.githubusercontent.com/28138717/65500891-49843900-dec0-11e9-8115-b2d8ab00ff43.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
