### ISSUE TITLE
[BC15 | Module "Data Compression"] Various important and missing functions are missing

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/ALAppExtensions#4326]
The new module "Data Compression" lacks some important functions that were available before. These are the following:

- UploadZip
- OpenZipFromTempBlob
- DownloadZip
- SaveZipToTempBlob

Furthermore, it would be desirable if the function "IsGzip" would also be available in the cloud. So far this is only visible in the "OnPrem" version.

Please make these functions available again, because otherwise large changes must be made to the existing source code. Furthermore, some of these functions cannot be easily replaced, because they are based internally on DotNet, and this is a well-known fact that Microsoft reserves this right in the cloud.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by darjoo** [comment]
Hi @FSharpCSharp, you are able to reproduce all those functions with by combining existing functionality.

UploadZip:
UploadIntoStream -> DataCompression.OpenZipArchive -> Depends on what you want to do next.

OpenZipFromTempBlob:
This is now called OpenZipArchive and takes in the new Temp Blob codeunit.

DownloadZip:
SaveZipArchive -> CopyStream -> DownloadFromStream

SaveZipToTempBlob:
SaveZipArchive, an overload which takes in a var Temp Blob codeunit.

**Comment by FSharpCSharp** [comment]
@darjoo 
Thanks for the clues. I understand that you are making changes to the application. But from my point of view these are also "Breaking Changes", which should also be explained there. If this had been communicated a bit better, several programs would not break now.

Personally, I find the reasons partly undecided and very flimsy.

I also don't really like the way you deal with criticism. To simply close the topic, but without doing anything, be it a better documentation or something similar, is personally incomprehensible to me. Sometimes I wish that Microsoft didn't simply deny all reasonable requests, underpinned by very strange arguments.
