### ISSUE TITLE
[EventModification] Table 77 Report Selections - OnBeforeGetVendorEmailAddress

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#4327]
Hello, Is it possible to add RecVar as a parameter in the event GetVendorEmailAddress?

Event OnBeforeGetVendorEmailAddress in Table 77:
![top](https://user-images.githubusercontent.com/54173532/65507860-2319ca00-decf-11e9-9e41-35053f0b222e.PNG)

Parameters:
![buttom](https://user-images.githubusercontent.com/54173532/65507879-30cf4f80-decf-11e9-9749-97e7d491cebb.PNG)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
