### ISSUE TITLE
[Event Request] Table 38 - Ship-to Code - OnValidate

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4328]
Hi!

We need an event before the purchase line check on OnValidate of Ship-to Code on the Purchase Header table. We need a SkipCheck pattern included.
![image](https://user-images.githubusercontent.com/55734714/65509209-3b3f1880-ded2-11e9-8246-23ddc4b6c323.png)

![image](https://user-images.githubusercontent.com/55734714/65509346-8ce7a300-ded2-11e9-8d6f-a10b624e4faf.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
