### ISSUE TITLE
Codeunit 80 - OnBeforePostCustomerEntry

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#4329]
Hi,

Is it possible to add parameter in existing publisher: OnBeforePostCustomerEntry in codeunit 80?
Additional parameter is GenJnlPostLine and it should be pass by var.

LOCAL [IntegrationEvent] OnBeforePostCustomerEntry(VAR GenJnlLine : Record "Gen. Journal Line";VAR SalesHeader : Record "Sales Header";VAR TotalSalesLine : Record "Sales Line";VAR TotalSalesLineLCY : Record "Sales Line";CommitIsSuppressed : Boolean;PreviewMode : Boolean;**VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
