### ISSUE TITLE
MatrixMgt.GenerateDimColumnCaption

### ISSUE THREAD

**Issue by amoldj** [Microsoft/ALAppExtensions#433]
I'm developing a new Matrix Page where in I need to use the standard ### 'GenerateDimColumnCaption' function from CU 9200 - Matrix Management; but following error is reported in AL:

The type or method 'GenerateDimColumnCaption' cannot be used for 'Extension' development.

**Comment by IhorHandziuk** [comment]
Thank you for your request, this procedure will be external in the future release.
