### ISSUE TITLE
Codeunit 90 - OnBeforePostVendorEntry

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#4330]
Hi,
Is it possible to add parameter in existing publisher OnBeforePostVendorEntry in codeunit 90?
Additional parameter is codeunit GenJnlPostLine and it should be pass by var.
LOCAL [IntegrationEvent] OnBeforePostVendorEntry(VAR GenJnlLine : Record "Gen. Journal Line";VAR PurchHeader : Record "Purchase Header";VAR TotalPurchLine : Record "Purchase Line";VAR TotalPurchLineLCY : Record "Purchase Line";PreviewMode : Boolean;CommitIsSuppressed : Boolean;**VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
