### ISSUE TITLE
[Event Request] Table 39 - Location Code - OnValidate

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4331]
Hi!

We need an additional event before the Drop Shipment check on OnValidate on Location Code in the Purchase Line table. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/65519441-35533280-dee6-11e9-8cbf-81313e3b5b4f.png)

![image](https://user-images.githubusercontent.com/55734714/65519461-3dab6d80-dee6-11e9-98ec-b29e1864da8c.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
