### ISSUE TITLE
[Event Request] Codeunit 11 Gen. Jnl.-Check Line

### ISSUE THREAD

**Issue by brijeshkarnatak** [microsoft/ALAppExtensions#4332]
Hi!

Can we add a parameter variable GenJnlLine : Record "Gen. Journal Line to the event “OnBeforeCheckSalesDocNoIsNotUsed” to make it more efficiently handled. The parameter should be added to function CheckSalesDocNoIsNotUsed at the first place. The snip of the same is below.

 
![image](https://user-images.githubusercontent.com/36695176/65526656-17e68e80-df0f-11e9-9536-76a58f104f0c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
