### ISSUE TITLE
Request Page Parameters Helper - ConvertParametersToFilter only works correctly if dataitem has default name

### ISSUE THREAD

**Issue by JuricaB** [microsoft/ALAppExtensions#4333]
Function ConvertParametersToFilter in CU Request Page Parameter Helper does not handle reports with non-default data item names correctly.

E.g. Sales reports in range 13xx have first data item named Header (tables are Sales Header, Sales Inv. Header etc.). 
Using the function on RecordRef Sales Invoice Header and Blob containing saved parameters does not apply the view to recordref. 

Compare to using same function on report 1322 which has dataitem Purchase Header (default named).

This is caused by GetFiltersForTable which compares value of "name" node attribute from saved parameters to table caption, name or Table Number of RecRef.

As BC already has correct values for data item table ID in Report Data Items virtual table, GetFiltersForTable should be updated to set correct filters based on Report Data Items.

**Comment by IhorHandziuk** [comment]
Hi, @JuricaB , thank you for your request.
Querying "Report Data Items" table proved to be too computationally expensive. We will apply a simpler fix, which will check if the data item name is a substring of the related table. It is not a general solution, but it will fix the problem with the Sales reports that you mentioned above.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
