### ISSUE TITLE
[Event Request] Codeunit 99000757, Function UpdateUnitCostOnProdOrder

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#4334]
We need a new Publisher in Codeunit 99000757, Function UpdateUnitCostOnProdOrder:
![image](https://user-images.githubusercontent.com/40287548/65573701-c4565e00-df6b-11e9-81d8-e50855fa9364.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
