### ISSUE TITLE
[Eventrequest] codeunit 12173

### ISSUE THREAD

**Issue by giann85** [microsoft/ALAppExtensions#4336]
Hi AL team,
please add new publisher event on Codeunit 12173 into trigger  OnRun, like this:

![image](https://user-images.githubusercontent.com/43236847/65497755-05db0080-debb-11e9-876e-ec8a5bd36c6d.png)

All parameters should be passed by var.

This is necessary to manage a particular withholding system in Italy, which has a percentage and amount of 0.

if is possible   change   the  functionvisibility to   External  on   function   "PostTax".

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
