### ISSUE TITLE
[Event Request] Table 37 Sales Line OnBeforeSetDefaultItemQuantity

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4338]
Hi AL-Team,
can you please add the following Publisher in function SetDefaultItemQuantity?
```
LOCAL SetDefaultItemQuantity()
// NEW >>>
OnBeforeSetDefaultItemQuantity(Rec);
// NEW <<<
GetSalesSetup;
IF SalesSetup."Default Item Quantity" THEN BEGIN
  VALIDATE(Quantity,1);
  CheckItemAvailable(CurrFieldNo);
END;

LOCAL [IntegrationEvent] OnBeforeSetDefaultItemQuantity(VAR SalesLine : Record "Sales Line")

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
