### ISSUE TITLE
Codeunit 226 - OnBeforePostApplyCustLedgEntry and OnBeforePostUnapplyCustLedgEntry

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#4339]
Hi,

Is it possible to add parameter in existing publishers: OnBeforePostApplyCustLedgEntry and OnBeforePostUnapplyCustLedgEntry in codeunit 226?
An additional parameter on both is GenJnlPostLine and it should be pass by var.
**OnBeforePostApplyCustLedgEntry**(VAR GenJournalLine : Record "Gen. Journal Line";CustLedgerEntry : Record "Cust. Ledger Entry";**VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line"**)

**OnBeforePostUnapplyCustLedgEntry**(VAR GenJournalLine : Record "Gen. Journal Line";CustLedgerEntry : Record "Cust. Ledger Entry";DetailedCustLedgEntry : Record "Detailed Cust. Ledg. Entry";**VAR GenJnlPostLine : Codeunit "Gen. Jnl-Post Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
