### ISSUE TITLE
Codeunit 227 - OnBeforePostApplyVendLedgEntry and OnBeforePostUnapplyVendLedgEntry

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#4340]
Hi,

Is it possible to add parameter in existing publishers: OnBeforePostApplyVendLedgEntry and OnBeforePostUnapplyVendLedgEntry in codeunit 227?
An additional parameter on both is GenJnlPostLine and it should be pass by var.
**OnBeforePostApplyVendLedgEntry**(VAR GenJournalLine : Record "Gen. Journal Line";VendorLedgerEntry : Record "Vendor Ledger Entry";**VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line**")
**OnBeforePostUnapplyVendLedgEntry**(VAR GenJournalLine : Record "Gen. Journal Line";VendorLedgerEntry : Record "Vendor Ledger Entry";DetailedVendorLedgEntry : Record "Detailed Vendor Ledg. Entry";**VAR GenJnlPostLine : Codeunit "Gen. Jnl-Post Line**")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
