### ISSUE TITLE
Codeunit 12 - OnAfterCalcPmtDiscPossible

### ISSUE THREAD

**Issue by ronnymeegdes** [microsoft/ALAppExtensions#4341]
Hi,

For an extension on NAV2018 CU21

Please add the following publisher event at the end of the CalcPmtDiscPossible function in codeunit 12:
`OnAfterCalcPmtDiscPossible(GenJnlLine,CVLedgEntryBuf);`

With this integration event
`LOCAL [IntegrationEvent] OnAfterCalcPmtDiscPossible(GenJnlLine : Record "Gen. Journal Line";VAR CVLedgEntryBuf : Record "CV Ledger Entry Buffer")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
