### ISSUE TITLE
[Event Request] COD 170 - OnBeforeCanGetPurchRecurringLines

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4342]
Can you please provide an OnBeforeCanGetPurchRecurringLines publisher with VAR access to PurchHeader with either the Handled pattern, or access to the 'Return' value so we can extend the test to skip the CanGetPurchRecurringLines logic?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
