### ISSUE TITLE
[Event Request] COD 9520 - DownloadPdfOnClient

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4343]
We currently mail documents (OnPrem) that are (still) stored on a file server. (= ServerPdfFilePath) When creating the mail, the server file is downloaded to the client (= ok), after which the server file is erased, which should be avoided! (ServerPdfFilePath is part of the 'DMS' / file server and should be kept). Please provide publisher around the ERASE statement so we can **skip** the deletion of ServerPdfFilePath.

![image](https://user-images.githubusercontent.com/25268332/65636847-649b9980-dfe3-11e9-9052-7bdf381acb2c.png)

- [ ] Solved in BC14

**Comment by AlexanderYakunin** [comment]
If you work OnPrem you should fdo you modification yourself. We do not provide events for OnPrem use.

**Comment by AlexanderYakunin** [comment]
We cannot add such event for Server path as it will be also available for SaaS.  But you can add it for your OnPrem customers for your special file storage solution.,
