### ISSUE TITLE
[Event Request] Codeunit Purch. Price Calc. Mgt. - OnBeforePurchHeaderStartDate

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/ALAppExtensions#4346]
To get access to the Start Date handling in codeunit Purch. Price Calc. Mgt. (7010) and to the global variable "DateCaption" I would like to apply for a new integration event `OnBeforePurchHeaderStartDate`.

Publisher:
```
 [Integration]
    LOCAL PROCEDURE OnBeforePurchHeaderStartDate@100(VAR PurchHeader@1000 : Record 38;VAR DateCaption@1001 : Text[30];VAR StartDate@1002 : Date;VAR IsHandled@1003 : Boolean);  
```

Please add following code at function `PurchHeaderStartDate`:

```
    LOCAL PROCEDURE PurchHeaderStartDate@31(PurchHeader@1000 : Record 38;VAR DateCaption@1001 : Text[30]) StartDate@1002 : Date;
    VAR
+     IsHandled@1003 : Boolean;
    BEGIN
+     OnBeforePurchHeaderStartDate(PurchHeader,DateCaption,StartDate,IsHandled);
+     IF IsHandled THEN
+       EXIT;

      WITH PurchHeader DO
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
