### ISSUE TITLE
Codeunit 226 - OnAfterPostUnapplyCustLedgEntry

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#4347]
Hi,

Is it possible to add parameter in existing publisher: OnAfterPostUnapplyCustLedgEntry in codeunit 226?
An additional parameter is GenJnlPostLine.

OnAfterPostUnapplyCustLedgEntry(GenJournalLine : Record "Gen. Journal Line";CustLedgerEntry : Record "Cust. Ledger Entry";DetailedCustLedgEntry : Record "Detailed Cust. Ledg. Entry";**VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
