### ISSUE TITLE
Codeunit 227 - OnAfterPostUnapplyVendLedgEntry

### ISSUE THREAD

**Issue by jelicastakic** [microsoft/ALAppExtensions#4348]
Hi,

Is it possible to add parameter in existing publisher: OnAfterPostUnapplyVendLedgEntry in codeunit 227?
An additional parameter is GenJnlPostLine and it should be pass by var.
OnAfterPostUnapplyVendLedgEntry(GenJournalLine : Record "Gen. Journal Line";VendorLedgerEntry : Record "Vendor Ledger Entry";DetailedVendorLedgEntry : Record "Detailed Vendor Ledg. Entry";**VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
