### ISSUE TITLE
[Event Request] TAB 77 - SendEmailDirectly

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4349]
We've made a modification to the mailing experience, so we can provide 'editable' body layouts before mailing, merge watermarks / other documents to the server PDF created, define other To/CC addresses, ... => ignoring the standard way an 'E-mail Item' is composed, but still adhering as much as possible to the doc. sending profile > report selections > _document mailing > email item_ > mail management > mail flow to send a mail

To only place we see to integrate our mods is in the SendEmailDirectly, where based on the report selections, the PDF is created serverside and then offered to 'Document Mailing' codeunit to be sent.

OnSendEmailDirectlyOnBeforeSendFiles is of no use, since this would only allow to modify the TempAttachReportSelections, not to manipulate the PDF / mail item. We need the event later, when SaveReportAsPDF has been completed.

So can you please provide an event on the place below with VAR access to variables RecordVariant,ServerAttachmentFilePath,ServerEmailBodyFilePath,DocNo,EmailAddress,DocName including the Handled pattern?

![image](https://user-images.githubusercontent.com/25268332/65675993-6a2ec900-e04f-11e9-8a96-c7ad3de965e8.png)

PS : The above is not the most ideal / readable place - but currently the only solution. **Better** would be to have an OnBeforeEmailFile in COD 260 Document-Mailing, allowing to skip (Handled pattern) the current logic. Only missing thing here is the **RecordVariant** context (needed to define which email address, body text, ... is needed). Adding RecordVariant to EmailFile would be great in combination the with new publisher.

- [ ] Solved in BC 14

**Comment by AlexanderYakunin** [comment]
Assigning to team @JesperSchulz @AndreiPanko

**Comment by fvet** [comment]
@JesperSchulz @AndreiPanko 
Any update on how the above might be implemented? It's on of our last 5 remaining major missing events to be ready for BC 16 ;)

Thinking about it, the latter option to have a OnBeforeEmailFileInternal publisher and include RecordVariant in OnBeforeEmailFileInternal, EmailFileInternal, OnBeforeSendEmail would open up most possibilities.

**Comment by IhorHandziuk** [comment]
Thank you for your request, @fvet , and sorry for such a long delay.

Regarding the first (worse) option: unfortunately, it's impossible to have a `var RecordVariant: Variant` as a parameter and modify some fields of the record inside the function (it's a limitation of AL language).

Regarding the second option: it's not exactly clear from the message if you will need the `RecordVariant `variable to be passed as `var` as well (I would assume that yes). If yes, then it's impossible for the same reason as the approach above. If no, can you, please, provide the complete example of what changes you want us to make, so we can evaluate them.

**Comment by IhorHandziuk** [comment]
Hi! We haven't heard from you in a while. Hopefully that's because you found a solution to the issue. For good housekeeping reasons we're closing issue, but if the problem still exists please submit a new request.
