### ISSUE TITLE
[Event Request] Codeunit 311 - SalesLineShowWarning / SetFilterOnItem

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4350]
Can you add events OnBeforeSalesLineShowWarning and OnBeforeSetFilterOnItem in codeunit 311 "Item-Check Avail."?

![image](https://user-images.githubusercontent.com/46031720/65678179-2342d280-e053-11e9-917f-4af4806518f4.png)

![image](https://user-images.githubusercontent.com/46031720/65678242-41a8ce00-e053-11e9-9875-eea860db9e32.png)

![image](https://user-images.githubusercontent.com/46031720/65678288-51c0ad80-e053-11e9-9c40-dee2177dd9d4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
