### ISSUE TITLE
[Event Request] Codeunit 22, Function ApplyCapNeed

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#4355]
We need a new Publisher to set an additional filter in CU22, Function ApplyCapNeed
![image](https://user-images.githubusercontent.com/40287548/65694479-387d2880-e076-11e9-8bf5-183c49c4c013.png)

Please add Parameter "ProdOrderCapNeed" byReference
Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
