### ISSUE TITLE
[Event Request] Page 5600 Fixed Asset Card - OnAfterLoadDepreciationBooks

### ISSUE THREAD

**Issue by LucaMartinengo** [microsoft/ALAppExtensions#4356]
Hi,

Please, add a new event in page 5600 Fixed Asset Card for code intervention after the loading of the global depreciation book.

For us, the customization is needed to set the default visualization of the page as "not simple", but it can be useful also with other parameters of personalization.

![image](https://user-images.githubusercontent.com/39652483/65694241-d0c6dd80-e075-11e9-9292-9cdf23ee8001.png)

Best regards,
Luca Martinengo

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
