### ISSUE TITLE
[Request for External] Exposing function SetLineDisc in CU 7000 Sales Price Calc. Mgt.

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#4357]
To implement the standard pricing logic for your own tables/modules it would be helpful if the `SetLineDisc()` function were no longer private.

We also need `ConvertPriceToVAT()` and `ConvertPriceLCYToFCY()` from the same code unit. These are already requested in #4309.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
