### ISSUE TITLE
[Event Request] Table 7302 CalcQtyAvailToTake

### ISSUE THREAD

**Issue by martonnagy** [microsoft/ALAppExtensions#4362]
Dear Development Team,

we would like to request a new Event Publisher in Table 7302 "Bin Content", Function CalcAvailToTake with the Handled Pattern:

![image](https://user-images.githubusercontent.com/39408604/65758167-7e86ca80-e110-11e9-8400-05a9c07af34e.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
