### ISSUE TITLE
[Event Code Change Request] Table 39 - "Purchase Line" - OnBeforeJobTaskIsSet

### ISSUE THREAD

**Issue by cosmo-skol** [microsoft/ALAppExtensions#4366]
Hello AL-Team,
the current implementation of the event publisher "OnBeforeJobTaskIsSet" allows only to force the return value to TRUE, but not to force it to FALSE.
I suggest the following change:

[External] JobTaskIsSet() : Boolean

```
// >> Change 
// JobTaskSet := FALSE;
// OnBeforeJobTaskIsSet(Rec,JobTaskSet);

// EXIT(
//   (("Job No." <> '') AND ("Job Task No." <> '') AND (Type IN [Type::"G/L Account",Type::Item])) OR
//   JobTaskSet);

JobTaskSet := ("Job No." <> '') AND ("Job Task No." <> '') AND (Type IN [Type::"G/L Account",Type::Item]);
OnBeforeJobTaskIsSet(Rec,JobTaskSet);

EXIT(JobTaskSet);
// << Change

```

This would allow the event subscribers to change the value of JobTaskSet both ways.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
