### ISSUE TITLE
Microsoft.Dynamics.Nav.NavUserAccount.NavUserAccountHelper

### ISSUE THREAD

**Issue by navaddict** [microsoft/ALAppExtensions#4367]
I use the DotNet command shown in the subject line in a few places in my Solution and I can't see anything related to it on here so I need a non-DotNet alternative in AL please...

**Comment by navaddict** [comment]
Help....anyone.... please?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Sorry, this one somehow got dropped between chairs. Could you be more specific as to which methods you are using? There is always the possibility to add a wrapper module (like we did for [Math](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Math)) or to expose a method or two through existing modules.

**Comment by JesperSchulz** [comment]
Closing due to lack of response. If the issue still exists, kindly open a new issue in this repository. Thank you!
