### ISSUE TITLE
Oct 19 Release EnvironmentInformation.IsInvoicing doesn't exist?

### ISSUE THREAD

**Issue by benjaminknapper** [microsoft/ALAppExtensions#4369]
Going through some extensions upgrading to Oct Release Preview

![image](https://user-images.githubusercontent.com/11381404/65778936-73ca3680-e10c-11e9-92e2-b98c51d9ce7b.png)

Following ALAppExtensions/BREAKINGCHANGES.md I encountered the error below

**Error: 'Codeunit "Identity Management"' does not contain a definition for 'IsInvAppId'**

The solution is as follows in that document, however, I am not seeing that function as a selection.
**Solution: Function has been moved to codeunit 457 "Environment Information", function IsInvoicing.**

![image](https://user-images.githubusercontent.com/11381404/65779143-d7ecfa80-e10c-11e9-9a69-1eb54fe9c645.png)

**Comment by AndreiPanko** [comment]
That is correct. This is internal method and should not be used from extensions. For Apps that are running on top of Business Central this method always returns False. It means if you have condition if IsInvoicing then DoSomething end; - you can completely remove it, this code is not executed anyway.
