### ISSUE TITLE
[Event Request] TAB 38 Purchase Header - Order Address Code - OnValidate()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#4372]
Could you please add a new event in TAB 38 Fct. "Order Address Code" - OnValidate()?

```
Order Address Code - OnValidate()
IF "Order Address Code" <> '' THEN BEGIN
	[..]
END ELSE BEGIN
  GetVend("Buy-from Vendor No.");
  "Buy-from Vendor Name" := Vend.Name;
  "Buy-from Vendor Name 2" := Vend."Name 2";
  CopyBuyFromVendorAddressFieldsFromVendor(Vend,TRUE);
  "Registration No." := Vend."Registration No.";

  IF IsCreditDocType THEN BEGIN
    "Ship-to Name" := Vend.Name;
    "Ship-to Name 2" := Vend."Name 2";
    CopyShipToVendorAddressFieldsFromVendor(Vend,TRUE);
    "Ship-to Contact" := Vend.Contact;
    "Shipment Method Code" := Vend."Shipment Method Code";
    // New Event ...
    IsHandled := FALSE;
    OnBeforeUpdateLocationWithVendorLocation(Rec,IsHandled);
    IF NOT IsHandled THEN
    // ... New 
      IF Vend."Location Code" <> '' THEN
        VALIDATE("Location Code",Vend."Location Code");
  END
END;
```

Publisher:
`LOCAL [IntegrationEvent] OnBeforeUpdateLocationWithVendorLocation(VAR PurchaseHeader : Record "Purchase Header";VAR IsHandled : Boolean)`

many thanks
Stefan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
