### ISSUE TITLE
[Event Request] TAB 38 Purchase Header "VAT Base Discount % - OnValidate()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#4373]
Could you please add a new event in TAB 38 "VAT Base Discount % - OnValidate()"?

```
VAT Base Discount % - OnValidate()

[..]

IF ("VAT Base Discount %" = xRec."VAT Base Discount %") AND
   (CurrFieldNo <> 0)
THEN
  EXIT;

// New Event ...
IsHandled := FALSE;
OnBeforeUpdateAmounts(Rec, xRec, CurrFieldNo, IsHandled);
IF IsHandled THEN
  EXIT;
// ... New Event 

PurchLine.SETRANGE("Document Type","Document Type");
PurchLine.SETRANGE("Document No.","No.");
PurchLine.SETFILTER(Type,'<>%1',PurchLine.Type::" ");
PurchLine.SETFILTER(Quantity,'<>0');
PurchLine.LOCKTABLE;
IF PurchLine.FINDSET THEN BEGIN
  MODIFY;
  REPEAT
    PurchLine.UpdateAmounts;
    PurchLine.MODIFY;
  UNTIL PurchLine.NEXT = 0;
END;
PurchLine.RESET;
```

Publisher:

`LOCAL [IntegrationEvent] OnBeforeUpdateAmounts(PurchaseHeader : Record "Purchase Header";xPurchaseHeader : Record "Purchase Header";CallingFieldNo : Integer;VAR IsHandled : Boolean)`

A similar event has already been requested for TAB 36 Sales Header: https://github.com/microsoft/ALAppExtensions/issues/4117

many thanks
Stefan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
