### ISSUE TITLE
Add xRec to Event Sales Header - OnBeforeInitRecord()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4375]
Hi there,

we need an additional parameter xRec in Sales Header Event Publisher OnBeforeInitRecord():

```
        IsHandled := false;
        //OnBeforeInitRecord(Rec, IsHandled); // OLD
        OnBeforeInitRecord(Rec, **xRec**, IsHandled); // NEW
        if not IsHandled then
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitRecord(var SalesHeader: Record "Sales Header"; **xSalesHeader: Record "Sales Header";** var IsHandled: Boolean)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
