### ISSUE TITLE
Add xRec to Event Purchase Header - OnAfterInitNoSeries()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4377]
Hi there,

we need an additional parameter xRec in Purchase Header Event Publisher OnAfterInitNoSeries():

```
            "Prepmt. Cr. Memo No." := xRec."Prepmt. Cr. Memo No.";
        end;

        //OnAfterInitNoSeries(Rec); // OLD
        OnAfterInitNoSeries(Rec, xRec); // NEW
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterInitNoSeries(var PurchHeader: Record "Purchase Header"; xPurchHeader: Record "Purchase Header")
    begin
    end;
```
Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
