### ISSUE TITLE
Add xRec to Event Purchase Header - OnBeforeInitRecord()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4378]
Hi there,

we need an additional parameter xRec in Purchase Header Event Publisher OnBeforeInitRecord():

```
        IsHandled := false;
        //OnBeforeInitRecord(Rec, IsHandled); // OLD
        OnBeforeInitRecord(Rec, xRec, IsHandled); // NEW
        if not IsHandled then
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitRecord(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
