### ISSUE TITLE
Add Event Publisher in Purchase Header - OnBeforeAssistEdit()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4380]
Hi there,

we need a new Event Publisher OnBeforeAssistEdit() in Purchase Header:

```
    begin
        // NEW++
        Handled := false;
        OnBeforeAssistEdit(SalesHeader, OldSalesHeader);
        if Handled then
            exit;
        // NEW--
        GetPurchSetup;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssistEdit(var PurchHeader: Record "Purchase Header"; OldPurchHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
