### ISSUE TITLE
Add Event Publisher in Incoming Document - OnBeforeCreateSalesHeaderFromIncomingDoc()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4381]
Hi there,

we need a new Event Publisher OnBeforeCreateSalesHeaderFromIncomingDoc() in Incoming Document:

```
        end;
        OnBeforeCreateSalesHeaderFromIncomingDoc(SalesHeader); // NEW
        SalesHeader.Insert(true);
        OnAfterCreateSalesHeaderFromIncomingDoc(SalesHeader);
```

```
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeCreateSalesHeaderFromIncomingDoc(var SalesHeader: Record "Sales Header")
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
