### ISSUE TITLE
Remove wrongly named Event Publisher in Correct Posted Sales Invoice - OnBeforeSelesHeaderInsert()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4382]
Hi there,

please remove one wrongly named Event Publisher OnBeforeSelesHeaderInsert() in Correct Posted Sales Invoice:

```
        SalesHeader.SetAllowSelectNoSeries;
        //OnBeforeSelesHeaderInsert(SalesHeader, SalesInvoiceHeader, CancellingOnly); // REMOVE
        OnBeforeSalesHeaderInsert(SalesHeader, SalesInvoiceHeader, CancellingOnly);
        SalesHeader.Insert(true);
```

Or did you leave this intentionally?

Thanks,
Carsten

**Comment by AlexanderYakunin** [comment]
Yes, we cannot remove any event, we can only [Obsolete] them for removal in 1 year

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
