### ISSUE TITLE
Add Event Publisher in Transfer Line - OnAfterInitQtyToShip()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4383]
Hi there,

we need a new Event Publisher OnAfterInitQtyToShip() in Transfer Line:

```
        "Qty. to Ship" := "Outstanding Quantity";
        "Qty. to Ship (Base)" := "Outstanding Qty. (Base)";
        OnAfterInitQtyToShip(Rec, CurrFieldNo); // NEW
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterInitQtyToShip(var TransferLine: Record "Transfer Line"; CurrFieldNo: Integer)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
