### ISSUE TITLE
Add Event Publisher in Transfer Line - OnAfterInitQtyToReceive()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4384]
Hi there,

we need a new Event Publisher OnAfterInitQtyToReceive() in Transfer Line:

```
            "Qty. to Receive (Base)" := "Qty. to Ship (Base)";
        end;
        OnAfterInitQtyToReceive(Rec, CurrFieldNo); // NEW
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterInitQtyToReceive(var TransferLine: Record "Transfer Line"; CurrFieldNo: Integer)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
