### ISSUE TITLE
Add Event Publisher in Transfer Line - OnAfterInitOutstandingQty()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4385]
Hi there,

we need a new Event Publisher OnAfterInitOutstandingQty() in Transfer Line:

```
        "Outstanding Qty. (Base)" := "Quantity (Base)" - "Qty. Shipped (Base)";
        "Completely Shipped" := (Quantity <> 0) and ("Outstanding Quantity" = 0);
        OnAfterInitOutstandingQty(Rec, CurrFieldNo); // NEW
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterInitOutstandingQty(var TransferLine: Record "Transfer Line"; CurrFieldNo: Integer)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
