### ISSUE TITLE
Add Event Publisher in Transfer Line - OnAfterInitQtyInTransit()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4386]
Hi there,

we need a new Event Publisher OnAfterInitQtyInTransit() in Transfer Line:

```
            "Qty. in Transit (Base)" := 0;
        end;
        "Completely Received" := (Quantity <> 0) and (Quantity = "Quantity Received");
        OnAfterInitQtyInTransit(Rec, CurrFieldNo); // NEW
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterInitQtyInTransit(var TransferLine: Record "Transfer Line"; CurrFieldNo: Integer)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
