### ISSUE TITLE
Add Event Publisher in Transfer Line - OnAfterUpdateWithWarehouseShipReceive()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4387]
Hi there,

we need a new Event Publisher OnAfterUpdateWithWarehouseShipReceive() in Transfer Line:

```
            if ("In-Transit Code" = '') and ("Quantity Shipped" = "Quantity Received") then
                Validate("Qty. to Receive", "Qty. to Ship");
        end;
        OnAfterUpdateWithWarehouseShipReceive(Rec, CurrFieldNo); // NEW
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterUpdateWithWarehouseShipReceive(var TransferLine: Record "Transfer Line"; CurrFieldNo: Integer)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
