### ISSUE TITLE
Add Event Publisher in Warehouse Receipt Line - OnBeforeInitOutstandingQtys()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4389]
Hi there,

we need a new Event Publisher OnBeforeInitOutstandingQtys() in Warehouse Receipt Line:

```
    procedure InitOutstandingQtys()
    begin
        // NEW++
        OnBeforeInitOutstandingQtys(Rec, CurrFieldNo, Handled);
        if Handled then
            exit;
        // NEW--
        Validate("Qty. Outstanding", Quantity - "Qty. Received");
```

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeInitOutstandingQtys(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; CurrFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
