### ISSUE TITLE
Please change the scope of Table Filter Page GetViewFilter() and GetFilterFieldsList() from OnPrem to Cloud?

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4390]
Hi there,

can you please change the scope of Table Filter Page GetViewFilter() and GetFilterFieldsList() from OnPrem to Cloud?
What is the reason for having these OnPrem only?

Thanks,
Carsten

**Comment by AlexanderYakunin** [comment]
Provided references does not exist in our Base App. Please create new request with correct object and procedure names

**Comment by MODUSCarstenScholling** [comment]
Hi Alex,

can you please let me know, what build are you referring to? 
I still find page 9805 "Table Filter" in 15.1.37793.0-de. Do you refer to 16 builds or newer 15.x builds?

Cheers,
Carsten

**Comment by AlexanderYakunin** [comment]
W1 Page 9805 does not contains GetViewFilter() and GetFilterFieldsList() in 15.X or Master. But they exists in DE version. Please always provide country code in requests if this is not for W1.

**Comment by MODUSCarstenScholling** [comment]
Oups, I'm sorry. Wasn't aware of these kinds of differences.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
