### ISSUE TITLE
Could you please make the following procedures global (remove local): Sales Header - ShippedSalesLinesExist(), ReturnReceiptExist()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4392]
Hi there,

Could you please make the following procedures global (remove local): Sales Header - ShippedSalesLinesExist(), ReturnReceiptExist()
This is useful and should not be re-implemented by every partner...

Thanks,
Carsten

**Comment by AlexanderYakunin** [comment]
They are already external

**Comment by MODUSCarstenScholling** [comment]
Thanks Alex,

I see it in the latest 16.x release. 

Cheers,
Carsten
