### ISSUE TITLE
Could you please make the following procedures global (remove local): Purchase Header - ReceivedPurchLinesExist(), ReturnShipmentExist()

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4393]
Hi there,

Could you please make the following procedures global (remove local): Purchase Header - ReceivedPurchLinesExist(), ReturnShipmentExist()
This is useful and should not be re-implemented by every partner...

Thanks,
Carsten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
