### ISSUE TITLE
OnAfterSetupObjectNoList event (COD408) only works for tables with global dimension fields

### ISSUE THREAD

**Issue by TeusV** [microsoft/ALAppExtensions#4396]
Previously (I think since solving issue #193) The OnAfterSetupObjectNoList event in COD408 could be used to add tables with dimension support, with or without global dimension fields. Currently it is either useless or blocks you from changing global dimensions.

It is mentioned in #193 that:
> "Table ID" in table 352 is verified against the list of table IDs returned by COD408.DefaultDimObjectNoList().
> This function collects all tables that match the following conditions:
> 
> * have fields related to global dimensions
> * do not have "Dimension Set ID" field
> * their primary key include one field
> 
> If the extension table satisfies these conditions, its ID will be accepted by table 352 automatically.
> If the table does not get to the list it can still be added by subscription to the event COD408.OnAfterSetupObjectNoList() and modifying the buffer table.

Previously the event was at the bottom of where all tables with dimension support are collected - SetupObjectNoList(); now it is at the bottom of the place where tables with global dimension fields are collected - DefaultDimObjectNoWithGlobalDimsList().

This is not a problem when setting up default dimensions, you can then pick the table you added dimension support for (with or without global dimension fields) allright.
But it is a problem when you change global dimensions. In that case, your custom table is added as well, and when it does not have global dimension fields, you will get an error as a result of there being no global dimension field:
```
"Unable to convert from Microsoft.Dynamics.Nav.Runtime.NavBigInteger to System.String."
```

Call stack:  

| Object Type | Object ID | Object Name | Function Name |
| - | - | - | - |
| Table | 483 | Change Global Dim. Log Entry | GetFieldRefValues |
| Codeunit | 483 | Change Global Dimensions | ChangeDimsOnRecord |
| Codeunit | 483 | Change Global Dimensions | ChangeDimsOnTable |
| Codeunit | 483 | Change Global Dimensions | RunTask |
| Codeunit | 483 | Change Global Dimensions | ProcessTableList |
| Codeunit | 483 | Change Global Dimensions | StartSequential |
| Page | 577 | Change Global Dimensions | StartSequential - OnAction |

I think this event would be better in place at the end of DefaultDimObjectNoWithoutGlobalDimsList() than at the end of DefaultDimObjectNoWithGlobalDimsList(), because you would *only* need it to add a table to the buffer that does *not* have global dimension fields, since if it *does* have these fields, it would already be added to the buffer automatically based on field name. Either way it would end up after a call of DefaultDimObjectNoList.

**Comment by StanPesotskiy** [comment]
The new event OnAfterDefaultDimObjectNoWithoutGlobalDimsList has been added on 30.Oct for [GitHub issue #4472](https://github.com/microsoft/ALAppExtensions/issues/4472)
```
    local procedure DefaultDimObjectNoWithoutGlobalDimsList(var TempAllObjWithCaption: Record AllObjWithCaption temporary)
    begin
         ...
         OnAfterDefaultDimObjectNoWithoutGlobalDimsList(TempAllObjWithCaption);
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
