### ISSUE TITLE
Procedure OnFindReportSelections() in Table Report Selections does not work as expected

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/ALAppExtensions#4397]
Hi there,

I have the feeling that the procedure OnFindReportSelections() in Table Report Selections does not work as expected.

First of all, for OnFindReportSelections() publisher, the existing signature is wrong: FilterReportSelections <> ReturnReportSelections must be switched: First Parameter is not the filtered record but the target. Last parameter is not the target but the filtered Rec:

```
    [IntegrationEvent(TRUE, false)]
    local procedure OnFindReportSelections(var FilterReportSelections: Record "Report Selections"; var IsHandled: Boolean; var ReturnReportSelections: Record "Report Selections")
    begin
    end;

```

When working with Custom Report Selections (Section?), these should overrule any default report selections. Therefore the call should be placed before OnFindReportSelections().
Or add AccountNo as a parameter to the publisher. But I would suggest the below order.

Could you please have a look into it?

Best regards,
Carsten

```
// Suggested code:
local procedure FindReportSelections(var ReportSelections: Record "Report Selections"; AccountNo: Code[20]; TableNo: Integer): Boolean
var
    Handled: Boolean;
begin
    if CopyCustomReportSectionToReportSelection(AccountNo, ReportSelections, TableNo()) then
        exit(true);

    OnFindReportSelections(ReportSelections, Handled, Rec);
    if Handled then
        exit(true);

    exit(CopyReportSelectionToReportSelection(ReportSelections));
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
