### ISSUE TITLE
[Event Request] CU 990000774 - OnBeforeInsertProdOrderCapNeed

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4401]
Can you add event OnBeforeInsertProdOrderCapNeed to function CreateCapNeed in CU 990000774?

![image](https://user-images.githubusercontent.com/46031720/65936991-b9457700-e41e-11e9-876b-4f5595cab9eb.png)

LOCAL [IntegrationEvent] OnBeforeInsertProdOrderCapNeed(VAR ProdOrderCapNeed : Record "Prod. Order Capacity Need";VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line";ProdOrder : Record "Production Order")

![image](https://user-images.githubusercontent.com/46031720/65937059-ee51c980-e41e-11e9-86f1-dfaead915d73.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
