### ISSUE TITLE
[Event Request] TAB 5405 - OnBeforeUpdateEndingDate

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4402]
Can you add event OnBeforeUpdateEndingDate in function UpdateEndingDate in table 5405 "Production Order"?

![image](https://user-images.githubusercontent.com/46031720/65939750-0fb6b380-e427-11e9-8e8e-f305bccbc5dd.png)

LOCAL [IntegrationEvent] OnBeforeUpdateEndingDate(VAR ProdOrderLine : Record "Prod. Order Line";VAR ProductionOrder : Record "Production Order";VAR IsHandled : Boolean)
![image](https://user-images.githubusercontent.com/46031720/65939812-2f4ddc00-e427-11e9-9f59-44f35c95c61e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
