### ISSUE TITLE
[Function Expose] BC (150) Wave 2 Codeunit 1293 "Isolated Storage Management"

### ISSUE THREAD

**Issue by Unidelcius** [microsoft/ALAppExtensions#4403]
Hello,

In BC (150) Wave 2 Codeunit "Isolated Storage Management" has no access restrictions but all functions has Scope set to OnPrem and cannot be accessed if application is developed for Cloud. 

Please expose these functions to be accessible by Cloud solutions.

Thank you!

**Comment by PaulIvan** [comment]
Hi @Unidelcius ,

This is very much intended, the isolated storage wrapper was added specifically for onprem and internal use due to security reasons. 

Please use the isolated storage system functions https://docs.microsoft.com/en-us/dotnet/standard/io/isolated-storage. The documentation I see is a bit outdated, there is also a SetEncrypted function. :)

**Comment by Unidelcius** [comment]
Hello @PaulIvan ,

according to this blog https://cloudblogs.microsoft.com/dynamics365/it/2019/08/14/changes-in-secret-management/ 

> Isolated Storage is safe, and sensitive data is always encrypted in online version (in OnPrem version the settings is controlled by user)

So as I understand you can use Isolated Storage for Cloud applications. Also this codeunit is only a wrapper for code which can be implemented manually no matter if target is set to Cloud or OnPrem, so I do not see why it wouldn't be available for both.

If I am missing something please explain. 

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by PaulIvan** [comment]
@Unidelcius once you call this wrapper which is in base app from extensions you can set and get secrets from and to isolated storage that are set within the context of the baseapp and we do not want that to happen.

Say extension x sets a secret to isolated storage using the wrapper from base app. now every other extension that uses the wrapper can retrieve get that secret. This is not what we want and it is a bad security practice.

For onprem and internal use we might want to have this ability though, that is why the wrapper exists in this way. Please consider using the system functions.
