### ISSUE TITLE
[Event Request] COD 99000774 - OnAfterCalcRoutingLineBack/OnAfterCalcRoutingLineForward

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4404]
Can you add event OnAfterCalcRoutingLineBack in function  CalcRoutingLineBack and OnAfterCalcRoutingLineForward in function CalcRoutingLineForward, in codeunit 99000774 
 "Calculate Routing Line"?

CalcRoutingLineBack:
![image](https://user-images.githubusercontent.com/46031720/65940063-d894d200-e427-11e9-8271-118700967130.png)

CalcRoutingLineForward:
![image](https://user-images.githubusercontent.com/46031720/65940129-011ccc00-e428-11e9-9666-ed72fb7c42d7.png)

Events:
![image](https://user-images.githubusercontent.com/46031720/65940202-2f021080-e428-11e9-943d-04c1a33e2ed7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
