### ISSUE TITLE
[Event Modification] COD 99000774 - OnAfterCalculateRoutingLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4405]
Can you add a parameter Direction to event OnAfterCalculateRoutingLine in codeunit 99000774
"Calculate Routing Line"?

![image](https://user-images.githubusercontent.com/46031720/65940259-5c4ebe80-e428-11e9-9c07-9c59cfc2d9b6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
