### ISSUE TITLE
[Event Request] Table 39 - Variant Code - OnValidate

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4406]
Hi!

We need an additional event before the Drop Shipment check on OnValidate on Variant Code in the Purchase Line table. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/65945134-983b5100-e433-11e9-9c8d-2cf7bb3e430a.png)

![image](https://user-images.githubusercontent.com/55734714/65945167-ac7f4e00-e433-11e9-92c2-71e67a93a069.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
