### ISSUE TITLE
[New Function] Page 99000888 - Get2

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4407]
Is it possible to add a new function as external in page 99000888 "Work Center Load Lines" to get variables that was initialized in function Set, so I can use them in page extension?

Edit: I forgot to set all parameters to VAR
![image](https://user-images.githubusercontent.com/46031720/65946718-09303800-e437-11e9-9c7a-032049db453c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
