### ISSUE TITLE
[Event Request] Table 39 - Unit of Measure Code - OnValidate

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4409]
Hi!

We need an additional event before the Drop Shipment check on OnValidate on Unit of Measure Code in the Purchase Line table. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/65948437-8e691c00-e43a-11e9-8385-bcfe47fbc45f.png)

![image](https://user-images.githubusercontent.com/55734714/65948467-9c1ea180-e43a-11e9-892e-d7575375da4d.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
