### ISSUE TITLE
[Event Request] Table 39 - CrossReferenceNoLookUp

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4410]
Hi!

We need an additional event before the PAGE.RUNMODAL call in the CrossReferenceNoLookUp function on the Purchase Line table.
![image](https://user-images.githubusercontent.com/55734714/65950373-37654600-e43e-11e9-9439-9727c54624b1.png)

![image](https://user-images.githubusercontent.com/55734714/65950418-4d730680-e43e-11e9-9191-e26b10e3e77d.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
