### ISSUE TITLE
[GlobalVarAccess] Report 795 Adjust Cost - Item Entries, OnBeforePreReport; add variables: ItemNoFilter, ItemCategoryFilter, PostToGL

### ISSUE THREAD

**Issue by finn777** [microsoft/ALAppExtensions#4412]
since [https://github.com/microsoft/AL/issues/3285](https://github.com/microsoft/AL/issues/3285) GlobalVarAccess was Yes
Now is not possible for 15.x
I need such variables: ItemNoFilter, ItemCategoryFilter, PostToGL

Please adopt:

AdjustCostItemEntries.Report.al

```
    trigger OnPreReport()
    var
        ItemLedgEntry: Record "Item Ledger Entry";
        ValueEntry: Record "Value Entry";
        ItemApplnEntry: Record "Item Application Entry";
        AvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point";
        Item: Record Item;
        UpdateItemAnalysisView: Codeunit "Update Item Analysis View";
    begin
        // mofify, alexef
        OnBeforePreReport(ItemNoFilter, ItemCategoryFilter, PostToGL);
...
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterPreReport()
    begin
    end;
    // modify, alexef
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforePreReport(ItemNoFilter: Text[250]; ItemCategoryFilter: Text[250]; PostToGL: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
