### ISSUE TITLE
Oct 19 Release OnAfterCopyLinks doesn't exist?

### ISSUE THREAD

**Issue by GregoryAA** [microsoft/ALAppExtensions#4415]
Hello AL team,

Going through some extensions upgrading to Oct Release Preview
![image](https://user-images.githubusercontent.com/45356755/65964379-8d011900-e465-11e9-836e-e4d3a4ba6740.png)

Following ALAppExtensions/BREAKINGCHANGES.md I encountered the error below:

The event 'OnAfterCopyLinks' is not found in the target

![image](https://user-images.githubusercontent.com/45356755/65964669-1b759a80-e466-11e9-94ef-93a5f4f7b055.png)

Where can I find this event in new release?

**Comment by GregoryAA** [comment]
the issue is urgent! Could you explain why you delete the event that was alredy presented in 14.0 version? 
Because of this, we can’t update the application presented in AppSource!

**Comment by NKarolak** [comment]
There seems to be a general issue, see https://github.com/microsoft/ALAppExtensions/issues/4462

**Comment by JesperSchulz** [comment]
A few events got lost in the process of converting BaseApp code into modules (parallel work). We're currently analyzing our two code bases (14.x and 15.0) and will be comparing the list of events - if an event in the System Application is missing and it wasn't removed intentionally, we'll bring the back into 15.0 and upwards as a hotfix. We hope to have rolled out the fix before end of week. This effort is limited to the System Application though and will hence not cover the mentioned issue #4462, which is caused by something else.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.0.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.1.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.0.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.0.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
