### ISSUE TITLE
[Event Request] Table 414 - Document No. - OnLookup

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4416]
Hi!

We need an additional event on OnLookup on Document No. in the IC Outbox Transaction table.
![image](https://user-images.githubusercontent.com/55734714/65969530-3bf12500-e465-11e9-8be9-5880fba75a49.png)

![image](https://user-images.githubusercontent.com/55734714/65969575-4f03f500-e465-11e9-95a9-35059c239731.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
