### ISSUE TITLE
[Event request] Pages 160,161,402,403 OnOpenPageOnBeforeSetEditable 

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4417]
In the existing eventtrigger OnOpenPageOnBeforeSetEditable we Need as additional Parameter the actual records which is always transfered to the statistic page to set AllowInvDisc depending on record values:

We Need this on the statistic pages 160,161,402,403

old:
LOCAL [IntegrationEvent] OnOpenPageOnBeforeSetEditable(VAR AllowInvDisc : Boolean;VAR AllowVATDifference : Boolean)

new:
LOCAL [IntegrationEvent] OnOpenPageOnBeforeSetEditable(VAR AllowInvDisc : Boolean;VAR AllowVATDifference : Boolean;rec: "Sales Header");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
