### ISSUE TITLE
[Event Request] Pages 396, 399, 5755, 5756, 5757, 6655, 6665 and Pages 397,398,400,401

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4418]
We Need a new eventtrigger to calculate with our own values on the statistic pages:
We Need this on the pages 396, 399, 5755, 5756, 5757, 6655, 6665 and Pages 397,398,400,401 with the corresponding records:

Page 396:
OnAfterGetRecord()
CLEARALL;

SalesShptLine.SETRANGE("Document No.","No.");

IF SalesShptLine.FIND('-') THEN
  REPEAT
    LineQty := LineQty + SalesShptLine.Quantity;
    TotalNetWeight := TotalNetWeight + (SalesShptLine.Quantity * SalesShptLine."Net Weight");
    TotalGrossWeight := TotalGrossWeight + (SalesShptLine.Quantity * SalesShptLine."Gross Weight");
    TotalVolume := TotalVolume + (SalesShptLine.Quantity * SalesShptLine."Unit Volume");
    IF SalesShptLine."Units per Parcel" > 0 THEN
      TotalParcels := TotalParcels + ROUND(SalesShptLine.Quantity / SalesShptLine."Units per Parcel",1,'>');
    //++++++++++++++++++++++++++++++++++++++
    OnAfterSalesShptLineFind(SalesShptLine, VAR TotalNetWeight, VAR TotalGrossWeight, VAR TotalVolume, VAR TotalParcels);
    //--------------------------------------
  UNTIL SalesShptLine.NEXT = 0;

and so on with the other pages like

Page 5755:
OnAfterGetRecord()
CLEARALL;

TransLine.SETRANGE("Document No.","No.");
TransLine.SETRANGE("Derived From Line No.",0);
IF TransLine.FIND('-') THEN
  REPEAT
    LineQty := LineQty + TransLine.Quantity;
    TotalNetWeight := TotalNetWeight + (TransLine.Quantity * TransLine."Net Weight");
    TotalGrossWeight := TotalGrossWeight + (TransLine.Quantity * TransLine."Gross Weight");
    TotalVolume := TotalVolume + (TransLine.Quantity * TransLine."Unit Volume");
    IF TransLine."Units per Parcel" > 0 THEN
      TotalParcels := TotalParcels + ROUND(TransLine.Quantity / TransLine."Units per Parcel",1,'>');
    //++++++++++++++++++++++++++++++++++++++
    OnAfterTransLineFind(TransLine, VAR TotalNetWeight, VAR TotalGrossWeight, VAR TotalVolume, VAR TotalParcels);
    //--------------------------------------
  UNTIL TransLine.NEXT = 0;

Page 397:
OnAfterGetRecord()
CLEARALL;

IF "Currency Code" = '' THEN
  currency.InitRoundingPrecision
ELSE
  currency.GET("Currency Code");

SalesInvLine.SETRANGE("Document No.","No.");
IF SalesInvLine.FIND('-') THEN
  REPEAT
    CustAmount := CustAmount + SalesInvLine.Amount;
    AmountInclVAT := AmountInclVAT + SalesInvLine."Amount Including VAT";
    IF "Prices Including VAT" THEN
      InvDiscAmount := InvDiscAmount + SalesInvLine."Inv. Discount Amount" / (1 + SalesInvLine."VAT %" / 100)
    ELSE
      InvDiscAmount := InvDiscAmount + SalesInvLine."Inv. Discount Amount";
    CostLCY := CostLCY + (SalesInvLine.Quantity * SalesInvLine."Unit Cost (LCY)");
    LineQty := LineQty + SalesInvLine.Quantity;
    TotalNetWeight := TotalNetWeight + (SalesInvLine.Quantity * SalesInvLine."Net Weight");
    TotalGrossWeight := TotalGrossWeight + (SalesInvLine.Quantity * SalesInvLine."Gross Weight");
    TotalVolume := TotalVolume + (SalesInvLine.Quantity * SalesInvLine."Unit Volume");
    IF SalesInvLine."Units per Parcel" > 0 THEN
      TotalParcels := TotalParcels + ROUND(SalesInvLine.Quantity / SalesInvLine."Units per Parcel",1,'>');
    IF SalesInvLine."VAT %" <> VATPercentage THEN
      IF VATPercentage = 0 THEN
        VATPercentage := SalesInvLine."VAT %"
      ELSE
        VATPercentage := -1;
    TotalAdjCostLCY :=
      TotalAdjCostLCY + CostCalcMgt.CalcSalesInvLineCostLCY(SalesInvLine) +
      CostCalcMgt.CalcSalesInvLineNonInvtblCostAmt(SalesInvLine);
    //+++++++++++++++++++++++++++++++++++++++++
    OnAfterSalesInvLineFind(SalesInvLine,VAR TotalNetWeight, VAR TotalGrossWeight, VAR TotalVolume, VAR TotalParcels);
    //-----------------------------------------
  UNTIL SalesInvLine.NEXT = 0;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
