### ISSUE TITLE
[Parameter Request] TAB 255 - LookupPostCode 

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4419]
On BC14, I've lots (500+) of overflow warnings (AA0139) on postcode related functions (e.g. LookupPostCode). In https://github.com/microsoft/AL/issues/4838, I wanted to know how to get rid of these warnings, but no answer yet ...

![image](https://user-images.githubusercontent.com/25268332/66050112-dd8f7980-e52c-11e9-97f6-cb53856a19bd.png)

In my opinion, the CityTxt and CountyTxt parameters need to have a fixed length again, since they need to be in accordance with the 'Post Code' table definition. The code parameters have, the texts don't, so it makes no sense ... 

Looking into the LookupPostCode function, following code is called ...

`if PostCodeRec.Get(PostCode, CityTxt)`

which would result in an error if CityTxt is too large. Return value is also limited to 50 only.

`CityTxt := PostCodeRec.City;`

Can you please provide a fix so I can ignore these warnings

**Comment by AlexanderYakunin** [comment]
To suppress some unwanted warnings you can create json file (e.g. “suppress.json”):
{
    "name": "Suppress",
    "rules": [
                               {
            "id": "AL0432",
            "action": "None"
        }
    ]
}

And target it in settings.json: "al.ruleSetPath": "suppress.json"

**Comment by fvet** [comment]
@AlexanderYakunin I want to avoid excluding these CodeCop warnings via the rulesets, since this would disable the rule for all of our objects as well. The added value of this rule is we can ensure to clean up our app based on the warnings. 

With this issue I want to know how MS can deliver their Base Application without any warnings on the standard functions and introduce a fixed parameter length again on the above postcode functions.
