### ISSUE TITLE
[Question] Renaming extension fields.

### ISSUE THREAD

**Issue by sirhc101** [microsoft/ALAppExtensions#4425]
I need to rename two fields of my extension due to warning `AL0468` (`Length of the table field name must not exceed 30 characters.`)
Now I simply have the question: How?

I first thought simply rename it because field id is still the same, but it does not work properly. The extension deployment status list is showing me, that it failed and it identified a remove action.
Well, then I thought maybe I need to use the `Table Sync. Setup` and `Data Upgrade Mgt.` codeunit, but the pre-compiler is decline this due to my `Cloud` development target.

So what is the proper way to rename a field? I read something with using `schemaUpdateMode` set to `recreate` instead of `synchronize`, but this would delete all extension data, right?

Thanks in advance.

**Comment by ashikivor** [comment]
You can use "schemaUpdateMode": "ForceSync", this will not delete the extension data.

And regarding the warning AL0468, I suppose you are assigning some value to the field from some other variable or fields, which is giving you a warning.

**Comment by sirhc101** [comment]
@ashikivor How do I do this in a productive cloud environment, not a sandbox or a docker container!?

AL0468 is just a warning, that the field name is exceed 30 characters. It's not because of an assignment or so. Just because of the name which is "to long"

**Comment by StanPesotskiy** [comment]
Your request is not related to the AL **application** extensibility. 
Please post it at https://www.yammer.com/dynamicsnavdev/ where the wider community may give you a valid answer.
