### ISSUE TITLE
table 5901 - make local functions external

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4426]
Please make the following functions externally accessible.  Thank you.

![image](https://user-images.githubusercontent.com/49729094/66084352-6cf05900-e53c-11e9-8c4c-fe828382e5b7.png)

![image](https://user-images.githubusercontent.com/49729094/66084388-898c9100-e53c-11e9-8d24-5a094790d433.png)

![image](https://user-images.githubusercontent.com/49729094/66084465-b50f7b80-e53c-11e9-969b-ea3cf8b28779.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
