### ISSUE TITLE
[Request for External] Exposing function CalcAvailableQty in CU 99000889 AvailabilityManagement

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4431]
To finalize our Intercompany addon we would like to request to have function CalcAvailableQty in CU 99000889 AvailabilityManagement as external to be able to use this in our extension.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
