### ISSUE TITLE
[Request] More explanatory error message in Table 11000003 (NL)

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#4433]
We would like the following errormessage in function "Amount (Entry) - OnValidate()" to be more explanatory:

ERROR(Text1000003);

**Suggested TextConstant Change:**
Text1000003=ENU=The sign does not correspond with the outstanding %1 %2 %3 %4 %5.;NLD=Het teken komt niet overeen met de openstaande %1 %2 %3 %4 %5.

**Suggested Code Change:**
```
CASE "Account Type" OF
  "Account Type"::Customer: ERROR(Text1000003, CustEntries.TABLECAPTION, CustEntries.FIELDCAPTION("Entry No."),
                                  CustEntries."Entry No.", CustEntries.FIELDCAPTION("Customer No."), CustEntries."Customer No.");
  "Account Type"::Vendor:   ERROR(Text1000003, VendEntries.TABLECAPTION, VendEntries.FIELDCAPTION("Entry No."),
                                  VendEntries."Entry No.", VendEntries.FIELDCAPTION("Vendor No."), VendEntries."Vendor No.");
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
