### ISSUE TITLE
Error in Breaking Changes

### ISSUE THREAD

**Issue by RasmusTidselbak** [microsoft/ALAppExtensions#4442]
The section Environment Information, describes that IsInvAppId has changed to IsInvoicing, but there is not a function Called IsInvoicing in the codeunit.

> Error: 'Codeunit "Identity Management"' does not contain a definition for 'IsInvAppId'
> 
> Solution: Function has been moved to codeunit 457 "Environment Information", function IsInvoicing.

**Comment by AndreiPanko** [comment]
Thank you for reporting. Fixed now: https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md#base-application
