### ISSUE TITLE
[Event Request] Codeunit 80 - f(x) FinalizePosting

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4444]
Hi!

We need an additional event before the CreateOutboxSalesInvTrans/CreateOutboxCrMemoTrans in f(x) FinalizePosting in the Sales-Post codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/66198042-e18dd980-e69b-11e9-9497-03979579e2c8.png)

![image](https://user-images.githubusercontent.com/55734714/66198091-f5394000-e69b-11e9-8bdb-0dbf840b859a.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
