### ISSUE TITLE
[Event Request] Codeunit 80 - f(x) SendICDocument

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4446]
Hi!

We need an additional event before the IC Status is set in f(x)SendICDocument in the Sales-Post codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/66199943-2a479180-e6a0-11e9-81a2-4ebf4264f967.png)

![image](https://user-images.githubusercontent.com/55734714/66199978-3c293480-e6a0-11e9-8c4b-1ba9e4ae31d6.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
