### ISSUE TITLE
Move objects from BaseApp to OIOUBL [DK]

### ISSUE THREAD

**Issue by JeppeDueHansen** [microsoft/ALAppExtensions#4447]
We are trying to install the OIOUBL extension in a W1 database, but for some reason there are 2 objects that are placed in the BaseApp in the DK localization. Shoudnt they be placed in the Extension OIOUBL? (or if shared with other danish extensios, it should be placed in a "BaseAppDK" extension that they can depend on). 
The objects are
OIOUBLProfile.Table.al
VATReconciliation.Report.al

**Comment by AlexanderYakunin** [comment]
No problems found on install OIOUBL extension over W1 database. As for mentioned DK objects:
- OIOUBLProfile.Table.al - is an obsolete table
- VATReconciliation.Report.al is not related to OIOUBL
