### ISSUE TITLE
[Event Request] Codeunit 80 - f(x) PostItemTracking

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4448]
Hi!

We need an additional event before RemQtyToBeInvoiced is checked against SalesLine."Qty. to Ship" in f(x) PostItemTracking in the Sales-Post codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/66205502-d9d73080-e6ad-11e9-88dc-c51e272db6b5.png)

![image](https://user-images.githubusercontent.com/55734714/66205527-e9ef1000-e6ad-11e9-9a0e-4a865945709d.png)

Thanks!

**Comment by AlexanderYakunin** [comment]
Already done like this

    local procedure PostItemTrackingCheckShipment(SalesLine: Record "Sales Line"; RemQtyToBeInvoiced: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostItemTrackingCheckShipment(SalesLine, RemQtyToBeInvoiced, IsHandled);
        if IsHandled then
            exit;

        if Abs(RemQtyToBeInvoiced) > Abs(SalesLine."Qty. to Ship") then begin
            if SalesLine."Document Type" = SalesLine."Document Type"::Invoice then
                Error(QuantityToInvoiceGreaterErr, SalesLine."Shipment No.");
            Error(ShipmentLinesDeletedErr);
        end;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
