### ISSUE TITLE
[Event Request] Codeunit 57 Document Totals : **OnAfterCalculatePostedSalesInvoiceTotals**

### ISSUE THREAD

**Issue by Hamdi-Amine** [microsoft/ALAppExtensions#4454]
Hello Team,
We need a new event in Codeunit 57 "Document Totals" to update amounts.
Event Publisher : # OnAfterCalculatePostedSalesInvoiceTotals

![image](https://user-images.githubusercontent.com/23724827/66254677-79112c00-e771-11e9-92ba-12404d9ebfa9.png)

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
