### ISSUE TITLE
[Function Expose] Codeunit 10527 "HMRCSubmissionHelpers"

### ISSUE THREAD

**Issue by robjones85** [microsoft/ALAppExtensions#4455]
Please can the scope of function "CreateIRMark" be changed to allow cloud access? Or a wrapper function added to accept standard al XmlDocument variable rather than DotNet.

Another alternative could be a wrapper providing access to the xml transformation / sha1 hashing algorithm tools which we would require to integrate with other GovTalk services.

**Comment by AlexanderYakunin** [comment]
We cannot expose functions with a native DotNet parameters.

As for the any refactoring – this is on obsolete GB GovTalk feature. From the 1st of April 2019 it is mandatory to use Making Tax Digital instead of GovTalk).
