### ISSUE TITLE
[Event Request] Table 99000829 - OnBeforeGtWMSDefaultBin gone in BC15

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#4462]
In **table 99000829 Planning Component**, event [**OnBeforeGetWMSDefaultBin**](https://github.com/microsoft/ALAppExtensions/issues/1743)  was present until BC14, and is now missing again in BC15 RTM. How come, will it be added again?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
