### ISSUE TITLE
[Event Request] Codeunit 5817 ReapplyJobConsumption 

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#4467]
Hello Team, 

we asked about a Publisher in function ReapplyJobConsumption and you already implemented it. (Githubentry 2761)

------ OLD CODE 
      IsHandled := false;
      OnBeforeReapplyJobConsumption(ItemRcptEntryNo,IsHandled);
      if IsHandled then
        exit;

      // Purchase receipt and job consumption are reapplied with with fixed cost application
      FindItemReceiptApplication(ItemApplnEntry,ItemRcptEntryNo);
      ItemJnlPostLine.UnApply(ItemApplnEntry);
      ItemLedgEntry.Get(ItemApplnEntry."Inbound Item Entry No.");
      ItemJnlPostLine.ReApply(ItemLedgEntry,ItemApplnEntry."Outbound Item Entry No.");

----NEW CODE
Publisher is GONE!!!

Please reimplement this publisher again.

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
