### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post OnAfterAssocItemJnlLine

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4470]
We have added fields in our extension to the Item Journal Line table whose values are based on SalesLine fields.  In order to update the related fields in the Item Journal Line table when the Item Journal Line is initialized, we need a parameter to be added to the OnAfterInitAssocItemJnlLine event for the SalesLine variable.

This is called at the end of Local function InitAssocItemJnlLine within the Sales-Post codeunit 80

Ex:  OnAfterInitAssocItemJnlLine(ItemJnlLine,PurchOrderHeader,PurchOrderLine,SalesHeader,SalesLine);

**Comment by sboeve** [comment]
Apologies, I should have also stated that SalesLine will need to be passed into InitAssocItemJnlLine function within the codeunit in order to accomplish this.

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
