### ISSUE TITLE
[Event Request] DimensionManagement

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#4472]
We need a new Publisher in Codeunit 408 DimensionManagement:
![image](https://user-images.githubusercontent.com/34675109/66380063-f4175400-e9b6-11e9-9a33-dceb58e7255e.png)
Parameter should be VAR.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
