### ISSUE TITLE
SharePoint authentication using tokens

### ISSUE THREAD

**Issue by SmartNavisys** [microsoft/ALAppExtensions#4473]
We have an application that connects to SharePoint and generates tokens by dint of setup and REST requests to store and refresh data suchs as:
Site URL
Client Id
Client Secret
Bearer Realm
Redirect URL
Refresh Token
Access Token

Going forward though, it would be better to store and retrieve this information using standardised logic. I notice many functions for Azure Directory that do exactly this (eg Codeunit 6303 "Azure AD Auth Flow", although they are only exposed for OnPrem, or have DotNet variables in the function parameters.

Are there plans to expand this for general use in extensions? Would be nice to handle tokens centrally, if not at least expose some of the functions for updating an Access Token.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help with this question?

**Comment by JesperSchulz** [comment]
We don't have any plans to start on this work, from what I know. To get traction on your idea, I would suggest one of the following two:
1) Log your idea on [aka.ms/bcideas](aka.ms/bcideas), get some votes for it and have us implement it.
2) Create a PR for a new [Module](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System) yourself, which satisfies your needs! We'd be happy to accept your code, if it follows our standards! That would be the fastest way to get your code in!
