### ISSUE TITLE
[Event Request] Table 38 OnBeforeUpdatePurchLineAmounts

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4479]
as just added in table 36 with the new trigger OnBeforeUpdateSalesLineAmounts we Need the same trigger in table 38:

LOCAL UpdatePurchAmountLines()
//++++++++++++++++++++++++++++++++
IsHandled := FALSE;
OnBeforeUpdatePurchLineAmounts(Rec,xRec,CurrFieldNo,IsHandled);
IF IsHandled THEN
  EXIT;
//--------------------------------

PurchLine.RESET;
PurchLine.SETRANGE("Document Type","Document Type");
PurchLine.SETRANGE("Document No.","No.");
PurchLine.SETFILTER(Type,'<>%1',PurchLine.Type::" ");
PurchLine.SETFILTER(Quantity,'<>0');
PurchLine.LOCKTABLE;
IF PurchLine.FINDSET THEN BEGIN
  MODIFY;
  REPEAT
    PurchLine.UpdateAmounts;
    PurchLine.MODIFY;
  UNTIL PurchLine.NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
