### ISSUE TITLE
[Event Request] Codeunit 5815 OnCheckSalesShptLine(SalesShptLine)

### ISSUE THREAD

**Issue by sauerkreut** [Microsoft/ALAppExtensions#448]
We request the following integration event:
OnCheckSalesShptLine(SalesShptLine) in Codeunit 5815

On function "LOCAL CheckSalesShptLine"

`....`
`OnBeforeCheckSalesShptLine(SalesShptLine);`
` `
`WITH SalesShptLine DO BEGIN`
`  // >>> NEW EVENT`
`  OnCheckSalesShptLine(SalesShptLine);`
`  // <<< NEW EVENT`
`  TESTFIELD(Type,Type::Item);`
`....`

LOCAL [IntegrationEvent] OnCheckSalesShptLine(VAR SalesShptLine : Record "Sales Shipment Line")
Var	Name	DataType	Subtype	Length
Yes	SalesShptLine	Record	Sales Shipment Line	

Thank you for your attention

**Comment by AlexanderYakunin** [comment]
You can use OnBeforeCheckSalesShptLine(SalesShptLine);

**Comment by sauerkreut** [comment]
My bad. Of course. Sorry for giving you more work here.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
