### ISSUE TITLE
[Fix] Page 5905 "Service Lines" - QuantityOnAfterValidate

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#4482]
Hello togehter,

In Page 5905 "Service Lines" at the end of the function `QuantityOnAfterValidate` there is this Code:
```
IF (Type = Type::Item) AND
   ((Quantity <> xRec.Quantity) OR ("Line No." = 0)) AND
   NOT UpdateIsDone
THEN
  CurrPage.UPDATE(TRUE);
```
The result of this code (combined with the code in OnInsert and GetNextLineNo) is: 
that a new line that is added between two existing lines is added at the end.

**Scenario:**
1. Use "New Line" between existing lines (Don't leave the line, so it is not stored and autosplitkey isn't activated).
2. Select Type::Item and a Item No. (Don't leave the line, so it is not stored and autosplitkey isn't activated).
3. Validate the Qty of the new line. (GetNextLineNo; There is a FindLast)

**Result:** the new line is added at the end of the document.

Expected behaviour:
The line is added between the existing lines. Like it is when I use a resource or it is on page 5966 "Service Quote Lines".

Please fix the code or add an Event to skip the code.

```
OnInsertRecord(BelowxRec : Boolean) : Boolean
IF NOT AddExtendedText THEN
  "Line No." := GetNextLineNo(xRec,BelowxRec);
```
```
[External] GetNextLineNo(ServiceLineSource : Record "Service Line";BelowxRec : Boolean) : Integer
... 
IF ServiceLine.FIND('+') THEN
  IF NOT ServiceLine.GET(ServiceLineSource."Document Type",ServiceLineSource."Document No.",ServiceLineSource."Line No.") THEN
    NextLineNo := ServiceLine."Line No." + LineStep
  ELSE
    IF BelowxRec THEN BEGIN
      ServiceLine.FINDLAST;
...
```

Thanks in advanced,
Benjamin

**Comment by StanPesotskiy** [comment]
Hi @BenjaminHochstetter
You are saying that "a new item line is added at the end of the document."
Please describe the whole scenario, so we could repro, and what the expected behaviour is.

**Comment by BenjaminHochstetter** [comment]
Hi @StanPesotskiy,
Thank you for your answer.
I added not the scanario to the request.

**Comment by StanPesotskiy** [comment]
I see that new service line jumps to the end of the list if quantity is changed before insert.
This is unusual behaviour, but "fixing" it by adding an event is not correct. This issue has no relation to extensibility.
If it is a bug then it should be fixed appropriately. Please create a hotfix request via the standard support channel.
