### ISSUE TITLE
table 5902 Service Line & table 5964 Service Contract Line - Make local functions external

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4484]
Please make the following functions externally accessible. Thank you.

![image](https://user-images.githubusercontent.com/49729094/66433586-9c94da80-e9ee-11e9-83cf-9a6daf6d08a0.png)
![image](https://user-images.githubusercontent.com/49729094/66435176-3dd16000-e9f2-11e9-935c-4349b73e63a5.png)
![image](https://user-images.githubusercontent.com/49729094/66435215-59d50180-e9f2-11e9-9690-1af8f5706302.png)
![image](https://user-images.githubusercontent.com/49729094/66435522-07481500-e9f3-11e9-8e59-d63c7e25db8a.png)
![image](https://user-images.githubusercontent.com/49729094/66435951-f0ee8900-e9f3-11e9-9275-eaa5071b9808.png)
![image](https://user-images.githubusercontent.com/49729094/66436093-4b87e500-e9f4-11e9-9a40-893e57a1ab82.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
