### ISSUE TITLE
[Event Request] Table 6651 OnInsertInvLineFromRetShptLineOnBeforeValidatePurchaseLine and 6661 OnInsertInvLineFromRetRcptLineOnBeforeValidateSalesLineQuantity

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4485]
In the new trigger OnInsertInvLineFromRetShptLineOnBeforeValidatePurchaseLine in table 6651 we Need the PurchaseLine as VAR Argument. The same with the trigger OnInsertInvLineFromRetRcptLineOnBeforeValidateSalesLineQuantity in table 6661 and SalesLine.
See also table 111 OnInsertInvLineFromShptLineOnBeforeValidateQuantity, where this is already solved:

Table 6651
old:
LOCAL [IntegrationEvent] OnInsertInvLineFromRetShptLineOnBeforeValidatePurchaseLine(VAR ReturnShipmentLine : Record "Return Shipment Line";PurchaseLine : Record "Purchase Line";VAR IsHandled : Boolean)
New:
LOCAL [IntegrationEvent] OnInsertInvLineFromRetShptLineOnBeforeValidatePurchaseLine(VAR ReturnShipmentLine : Record "Return Shipment Line";VAR PurchaseLine : Record "Purchase Line";VAR IsHandled : Boolean)

Table 6661:
old:
LOCAL [IntegrationEvent] OnInsertInvLineFromRetRcptLineOnBeforeValidateSalesLineQuantity(VAR ReturnReceiptLine : Record "Return Receipt Line";SalesLine : Record "Sales Line";VAR IsHandled : Boolean)
new:
LOCAL [IntegrationEvent] OnInsertInvLineFromRetRcptLineOnBeforeValidateSalesLineQuantity(VAR ReturnReceiptLine : Record "Return Receipt Line";VAR SalesLine : Record "Sales Line";VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
