### ISSUE TITLE
[Event Request] Table 5050 OnBeforeVendorInsert

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4486]
Please add VAR Contact as additional parameter to OnBeforeVendorInsert in table 5050. We Need the same logic as in the existing trigger OnBeforeCustomerInsert

Old:
LOCAL [IntegrationEvent] OnBeforeVendorInsert(VAR Vend : Record Vendor)
New:
LOCAL [IntegrationEvent] OnBeforeVendorInsert(VAR Vend : Record Vendor;VAR Contact : Record Contact)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
