### ISSUE TITLE
[Request for External] Table 5741, 5876, 5877, 5902 and 901 TestStatusOpen

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4489]
Please make TestStatusOpen in tables 5741, 5876, 5877, 5902 and 901 global and external, as this has been done already in tables 37 and 39:

old:
LOCAL TestStatusOpen()
new:
[External] TestStatusOpen()

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
