### ISSUE TITLE
[Event Request] Codeunit 5816 OnCheckReturnRcptLine(ReturnRcptLine)

### ISSUE THREAD

**Issue by sauerkreut** [Microsoft/ALAppExtensions#449]
We request the following integration event:
OnCheckReturnRcptLine(ReturnRcptLine) on Codeunit 5816

On function "LOCAL CheckReturnRcptLine"

`....`
`OnBeforeCheckReturnRcptLine(ReturnRcptLine);`
` `
`WITH ReturnRcptLine DO BEGIN`
`  // >>> NEW EVENT` 
`  OnCheckReturnRcptLine(ReturnRcptLine);`
`  // <<<< NEW EVENT`
`  TESTFIELD(Type,Type::Item);`
`....`

LOCAL [IntegrationEvent] OnCheckReturnRcptLine(VAR ReturnRcptLine : Record "Return Receipt Line")
Var	Name	DataType	Subtype	Length
Yes	ReturnRcptLine	Record	Return Receipt Line	

Thank you for your attention

**Comment by AlexanderYakunin** [comment]
You can use OnBeforeCheckReturnRcptLine(ReturnRcptLine)

**Comment by sauerkreut** [comment]
My bad. Of course. Sorry for giving you more work here.

**Comment by sauerkreut** [comment]
Issue can be closed. Thank you for your attention.

**Comment by sauerkreut** [comment]
Same as #448. Issue can be closed. Thank you for your attention.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
