### ISSUE TITLE
EVENTREQUEST 7310 Whse.-Shipment Release, function CreateWhsePickRqst

### ISSUE THREAD

**Issue by keshavopk** [microsoft/ALAppExtensions#4491]
In Codeunit 7310 Whse.-Shipment Release, function CreateWhsePickRqst, please add the following events:
 […]
CALCFIELDS("Completely Picked");
 WhsePickRqst."Completely Picked" := "Completely Picked";
 //>>>>NEW
 OnBeforeInsertionPickRequest(Var WhsePickRqst, WhseShptHeader)
 //<<<<NEW
 IF NOT WhsePickRqst.INSERT THEN
 WhsePickRqst.MODIFY;
 //.>>>>NEW
 OnAfterInsertionPickRequest(Var WhsePickRqst)
 //.<<<<NEW

[…]

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
