### ISSUE TITLE
[Event Request] Report 7390 - OnAfterOnPostReport

### ISSUE THREAD

**Issue by BE-Ouaali** [microsoft/ALAppExtensions#4492]
Please add a new integration event OnAfterOnPostReport in Report 7390.

```
    [Integration]
    LOCAL PROCEDURE OnAfterOnPostReport@1000(VAR WarehouseJournalLine@1000 : Record 7311);
    BEGIN
    END;

```

Call for function:

```
    OnPostReport=BEGIN
+                   OnAfterOnPostReport(WhseJnlLine);
                 END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
