### ISSUE TITLE
[Event Request] Codeunit 99000854 OnPrepareTempTracking

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4494]
we Need a new Event OnPrepareTempTracking in codeunit 99000854 

LOCAL PrepareTempTracking(VAR FromTrkgReservEntry : Record "Reservation Entry";VAR ToTrkgReservEntry : Record "Reservation Entry";IsSurplus : Boolean;IssueActionMessage : Boolean;Binding : ' ,Order-to-Order')
IF NOT IsSurplus THEN BEGIN
  ToTrkgReservEntry."Quantity (Base)" := -FromTrkgReservEntry."Quantity (Base)";
  ToTrkgReservEntry.Quantity :=
    ROUND(ToTrkgReservEntry."Quantity (Base)" / ToTrkgReservEntry."Qty. per Unit of Measure",UOMMgt.QtyRndPrecision);
END ELSE
  ToTrkgReservEntry."Suppressed Action Msg." := NOT IssueActionMessage;

ToTrkgReservEntry.Positive := ToTrkgReservEntry."Quantity (Base)" > 0;
FromTrkgReservEntry.Positive := FromTrkgReservEntry."Quantity (Base)" > 0;

FromTrkgReservEntry.Binding := Binding;
ToTrkgReservEntry.Binding := Binding;

//++++++++++++++++++++++++++++++++++++++
OnPrepareTempTracking(VAR FromTrkgReservEntry : Record "Reservation Entry";VAR ToTrkgReservEntry : Record "Reservation Entry";IsSurplus : Boolean);
//--------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
