### ISSUE TITLE
[Event Request] Codeunit 99000854 OnAfterSetQtyToHandle

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4495]
we Need a new Event OnAfterSetQtyToHandle in codeunit 99000854:

LOCAL SetQtyToHandle(VAR TrkgReservEntry : Record "Reservation Entry")
IF NOT TrkgReservEntry.TrackingExists THEN
  EXIT;

IF (TrkgReservEntry."Reservation Status" = TrkgReservEntry."Reservation Status"::Tracking) AND
   (TrkgReservEntry."Source Type" = DATABASE::"Sales Line") AND NOT TrkgReservEntry.Positive
THEN BEGIN
  TrkgReservEntry."Qty. to Handle (Base)" := 0;
  TrkgReservEntry."Qty. to Invoice (Base)" := 0;
END ELSE BEGIN
  TrkgReservEntry."Qty. to Handle (Base)" := TrkgReservEntry."Quantity (Base)";
  TrkgReservEntry."Qty. to Invoice (Base)" := TrkgReservEntry."Quantity (Base)";
END;
//++++++++++++++++++++++++++++++++++++++++++
OnAfterSetQtyToHandle(VAR TrkgReservEntry : Record "Reservation Entry");
//------------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
