### ISSUE TITLE
[Event Request] Codeunit 99000854 OnAdjustPlanLineAfterValidateQuantity

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4496]
wen Need a new Event trigger OnAdjustPlanLineAfterValidateQuantity in codeunit 99000854 

LOCAL AdjustPlanLine(VAR Supply : Record "Inventory Profile")
OnBeforeAdjustPlanLine(ReqLine,Supply);

WITH Supply DO BEGIN
  ReqLine."Action Message" := "Action Message";
  ReqLine.BlockDynamicTracking(TRUE);
  IF "Action Message" IN
     ["Action Message"::New,
      "Action Message"::"Change Qty.",
      "Action Message"::Reschedule,
      "Action Message"::"Resched.& Chg. Qty.",
      "Action Message"::Cancel]
  THEN BEGIN
    IF "Qty. per Unit of Measure" = 0 THEN
      "Qty. per Unit of Measure" := 1;
    ReqLine.VALIDATE(
      Quantity,
      ROUND("Remaining Quantity (Base)" / "Qty. per Unit of Measure",UOMMgt.QtyRndPrecision));
    ReqLine."Original Quantity" := "Original Quantity";
    ReqLine."Net Quantity (Base)" :=
      (ReqLine."Remaining Quantity" - ReqLine."Original Quantity") *
      ReqLine."Qty. per Unit of Measure";
    //+++++++++++++++++++++++++++++++++++++++++++++++
    OnAdjustPlanLineAfterValidateQuantity(VAR RequisitionLine : Record "Requisition Line";VAR SupplyInventoryProfile : Record "Inventory Profile");
    //-----------------------------------------------
  END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
