### ISSUE TITLE
[Request for External] codeunit 9150 "My Records Filter Sub."

### ISSUE THREAD

**Issue by plagijat** [microsoft/ALAppExtensions#4497]
Hi,

We have the similar functionality as in CU 9150 "My Records Filter Sub." but with different tables.
Can you make functions in this codeunit external so that anyone can reuse this code to extend Filter Text with own/different tables:

- GetMyFilterText
- AddToFilter

Also, in GetMyFilterText function that exit when checking MyTableNo should be changed to allow different tables also.

It was already asked in #378 to make those functions globaly available (external).

Thanks,
Zoran

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
