### ISSUE TITLE
[Event Request] Report 5753 OnPurchaseLineOnAfterGetRecordOnBeforeCreateRcptHeader and OnPurchaseLineOnAfterGetRecordOnBeforeCreateShptHeader

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4498]
Please add in Report 5753 on dataitem "Purchase Line" the same trigger as already implemented on the other dataitems as "Sales Line", "Transfer Line":

Purchase Line - OnAfterGetRecord()
IsHandled := FALSE;
OnBeforePurchaseLineOnAfterGetRecord("Purchase Line","Warehouse Request",RequestType,IsHandled);
IF IsHandled THEN
  CurrReport.SKIP;

VerifyItemNotBlocked("No.");
IF "Location Code" = "Warehouse Request"."Location Code" THEN
  CASE RequestType OF
    RequestType::Receive:
      IF WhseActivityCreate.CheckIfPurchLine2ReceiptLine("Purchase Line") THEN BEGIN
        //++++++++++++++++++++++++++++++++++
        OnPurchaseLineOnAfterGetRecordOnBeforeCreateRcptHeader(
          "Purchase Line","Warehouse Request",WhseReceiptHeader,WhseHeaderCreated,OneHeaderCreated);
        //----------------------------------
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
          CreateReceiptHeader;
        IF NOT WhseActivityCreate.PurchLine2ReceiptLine(WhseReceiptHeader,"Purchase Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
    RequestType::Ship:
      IF WhseActivityCreate.CheckIfFromPurchLine2ShptLine("Purchase Line") THEN BEGIN
        //++++++++++++++++++++++++++++++++++
        OnPurchaseLineOnAfterGetRecordOnBeforeCreateShptHeader(
          "Purchase Line","Warehouse Request",WhseShptHeader,WhseHeaderCreated,OneHeaderCreated);
        //----------------------------------
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
          CreateShptHeader;
        IF NOT WhseActivityCreate.FromPurchLine2ShptLine(WhseShptHeader,"Purchase Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
  END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
