### ISSUE TITLE
[Request for External] codeunit 6503 "Item Tracking Doc. Management"

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4506]
It's possible to change the function RetrieveEntriesFromShptRcpt and FindReservEntries in [External] form LOCAL? we don't need all operation of external procedure that call this inside (like open page)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
