### ISSUE TITLE
[Event-Request]  Codeunit 90 OnPostItemJnlLineJobConsumption event

### ISSUE THREAD

**Issue by JJODonovan** [microsoft/ALAppExtensions#4508]
I had previously requested that GlobalVarAccess be added to the OnPostItemJnlLineJobConsumption event in the PurchPost Codeunit but as this is no longer supported I would like to request that the ItemJnlPostLine Codenunit variable be added to the event publisher.  In order to be able to override the code in the PostItemJnlLineJobConsumption function (where the OnPostItemJnlLineJobConsumption event is raised) it is necessary to be able to use the same instance of the ItemJnlPostLine Codeunit that is used as a globlal in PurchPost and this is only possible if it is added as a var parameter to the event publisher.    Otherwise it is not possible to override this code by creating our own event handler for it.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
