### ISSUE TITLE
New Event in codeunit 5942

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4511]
Please add a new event in the OnRun trigger, 

  IF TemplateDisc.FIND('-') THEN
    REPEAT
      ContractDisc := TemplateDisc;
      ContractDisc."Contract Type" := ServContract."Contract Type";
      ContractDisc."Contract No." := ServContract."Contract No.";
      ContractDisc.INSERT;
    UNTIL TemplateDisc.NEXT = 0;

  //New event
  OnSetupServiceContract(ServContract,ContractTemplate);

  Rec := ServContract;

where
[IntegrationEvent] OnSetupServiceContract(var ServContract: Record "Service Contract header";ContractTemplate: Record "Service Contract Template");

Thank you very much.

![image](https://user-images.githubusercontent.com/49729094/66593113-5eb9c280-eb64-11e9-88c4-96dd31d46c17.png)

**Comment by AlexanderYakunin** [comment]
Please create request for latest code base, this code is not actual anymore for 15.X

**Comment by AlexanderYakunin** [comment]
No update, closing
