### ISSUE TITLE
[Event Request] Codeunit 7010 - GetPurchLineLineDisc

### ISSUE THREAD

**Issue by evamariamartingomez** [microsoft/ALAppExtensions#4515]
Hi,  

I would like the same Event 'OnAfterGetSalesLineLineDisc' that is in Codeunit 7000 - GetSalesLineLineDisc but in Codeunit 7010 - GetPurchLineLineDisc

![OnAfterGetSalesLineLneDisc](https://user-images.githubusercontent.com/56435545/66646269-00edaf00-ec26-11e9-8108-9475279cfe58.jpg)

Thank you in advance,

Eva Maria

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
