### ISSUE TITLE
250 Million Records Data Deletion

### ISSUE THREAD

**Issue by mpopelka** [microsoft/ALAppExtensions#4523]
Attempting to delete 250 million records Change Log Entries. So far this is what has been attempted in the Process Only Report extension to delete. Was attempted in both UI report run and as Job Queue Entry. Logic would work for small dataset for example in Cronus Company. Has something like this been resolved or come up before for BC Saas?
 
1.       Filter table id and datetime range and deleteall(true/false) – **Ran into SQL table error (UI)**
2.       No filters loop through all records and check if Table ID and Dates within specified range than delete individual record. – **Said successful but records still there (UI & Job Queue Entry)**
3.       No filters loop through all records and check if Table ID and Dates within specified range than delete individual record and commit after N records - **Said successful but records still there (Job Queue Entry)**
4.       Do a get on key values of specific record and delete – **Ran into Object specific permissions to delete change logs so updated object permission and attempted 2-4 again. All said successful but record still there. (UI & Job Queue Entry)**
5.       Do a get on key values of specific record than delete and commit - **Said successful but record still there. Commit after delete of 1 record took hours. (UI & Job Queue Entry)**
6.       Currently as last resort looping all records doing a delete and commit to see if it will delete all records. – **Running for 1 week straight (Job Queue Entry)**

**Comment by mpopelka** [comment]
**Update** So far the only thing that appears to be working is #6 delete and commit each record based on looking at the database GB start and current size. Previous attempts 2 and 3 did not result in a smaller database size.

The Job Queue Entry is still running and based on the rate it is going it could run for a couple more weeks. The main issue appears to be committing since looping through all records only takes about 3 hrs in the UI based on messages.

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
