### ISSUE TITLE
Conditional Operator

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/ALAppExtensions#4525]
Would it be possible to implement conditional operators as it is available in C#?
[https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator)

**Comment by AlexanderYakunin** [comment]
Please post this kind of questions here https://github.com/microsoft/AL/issues
