### ISSUE TITLE
Temp Blob Management - Additional Property for FileName

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/ALAppExtensions#4526]
Please allow for a FileName [Text250] property in TempBlob codeunit to store the name of the attachment together with the name.

**Comment by ashikivor** [comment]
This link can help you. 

https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md#blob-storage-module

**Comment by ThomasBrodkorb** [comment]
Hello ashikivor,

in what regard will that help with the request to add a new property to the Temp Blob Management codeunit?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Hi Thomas!

It was a deliberate decision not to add file names to the modules, as we want to encourage to move away from the concept of files in the cloud. If you really need a file name to be added to a persisted blob, please create a dictionary/table of your own where you map your file name to the blob entry.

**Comment by ThomasBrodkorb** [comment]
Sorry, but that makes no sense.
People do upload and download FILES to and from the cloud.
No matter what your plans are, a Document Management System needs file names to suggest when downloading from cloud.
To compare files, you need to compare name size and content.

So in the end, the decision renders the TempBlob useless as it contains no useful helpers anymore.

As far as I understood, this is part of the SYSTEM layer and intended to be the base structure we as programmers are supposed to use.
This is like giving someone a hammer without a hammerhead because you decide that nails should not be used in the future anymore.

**Comment by JesperSchulz** [comment]
Point taken! I'll try to gather some more input and some feedback on the "usefullness" (or lack of the same) of the Blob Storage module. For now though, you should be able to add a key/value pair (blob id/file name) quite easily yourself to unblock yourself.
