### ISSUE TITLE
Base64 Convert - Additional parameter type for ToBase64 and FromBase64

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/ALAppExtensions#4527]
The new "Temp Blob" codeunit lacks the Base64 support available originally.
The new "Base64 Convert" codeunit lacks the function overloads for parameter type "Temp Blob" codeunit.

Please add the following functions to the "Base64 Convert" codeunit:
procedure FromBase64(Base64String: Text; VAR TempBlob : Codeunit "Temp Blob")
procedure ToBase64(VAR TempBlob : Codeunit "Temp Blob") : Text

Alternatively, would be the same effect to add similar functions to the "Temp Blob" codeunit:

procedure FromBase64(Base64String: Text)
procedure ToBase64() : Text

**Comment by ashikivor** [comment]
Try using this 
![image](https://user-images.githubusercontent.com/28855499/66843272-d3c63700-ef6c-11e9-8cf2-8cb488e40ebc.png)
