### ISSUE TITLE
COD 483 - Missing permissions

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#4528]
Hello,

is it possible to extent permissions in COD 483 to all protected tables?
We added global dimensions in table 254 VAT Entry and the Job now breaks down because of missing Permissions for table 254.
In past we added the missing permission…
Also possible are new handled Events before modifying the records, in function ChangeDimsOnRecord, ChangeDependentRecords and TestDirectModifyPermission.

I’m looking forward to your reply.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
