### ISSUE TITLE
[Event Request] Table 38 OnValidatePricesIncludingVATOnBeforePurchLineModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4529]
in table 38 on field 35 "Prices Including VAT" we Need the same Event trigger OnValidatePricesIncludingVATOnBeforePurchLineModify as already implemented in table 36 on field 35:

Prices Including VAT - OnValidate()
TestStatusOpen;

IF "Prices Including VAT" <> xRec."Prices Including VAT" THEN BEGIN
  PurchLine.SETRANGE("Document Type","Document Type");
  PurchLine.SETRANGE("Document No.","No.");
  PurchLine.SETFILTER("Direct Unit Cost",'<>%1',0);
  PurchLine.SETFILTER("VAT %",'<>%1',0);
  IF PurchLine.FIND('-') THEN BEGIN
    IF GetHideValidationDialog OR NOT GUIALLOWED THEN
      RecalculatePrice := TRUE
    ELSE
      RecalculatePrice :=
        ConfirmManagement.ConfirmProcess(
          STRSUBSTNO(
            Text025 +
            Text027,
            FIELDCAPTION("Prices Including VAT"),PurchLine.FIELDCAPTION("Direct Unit Cost")),
          TRUE);
    OnAfterConfirmPurchPrice(Rec,PurchLine,RecalculatePrice);
    PurchLine.SetPurchHeader(Rec);

    IF "Currency Code" = '' THEN
      Currency.InitRoundingPrecision
    ELSE
      Currency.GET("Currency Code");

    PurchLine.FINDSET;
    REPEAT
      PurchLine.TESTFIELD("Quantity Invoiced",0);
      PurchLine.TESTFIELD("Prepmt. Amt. Inv.",0);
      IF NOT RecalculatePrice THEN BEGIN
        PurchLine."VAT Difference" := 0;
        PurchLine.UpdateAmounts;
      END ELSE BEGIN
        VatFactor := 1 + PurchLine."VAT %" / 100;
        IF VatFactor = 0 THEN
          VatFactor := 1;
        IF NOT "Prices Including VAT" THEN
          VatFactor := 1 / VatFactor;
        PurchLine."Direct Unit Cost" :=
          ROUND(PurchLine."Direct Unit Cost" * VatFactor,Currency."Unit-Amount Rounding Precision");
        PurchLine."Line Discount Amount" :=
          ROUND(
            PurchLine.Quantity * PurchLine."Direct Unit Cost" * PurchLine."Line Discount %" / 100,
            Currency."Amount Rounding Precision");
        LineInvDiscAmt := InvDiscRounding + PurchLine."Inv. Discount Amount" * VatFactor;
        PurchLine."Inv. Discount Amount" := ROUND(LineInvDiscAmt,Currency."Amount Rounding Precision");
        InvDiscRounding := LineInvDiscAmt - PurchLine."Inv. Discount Amount";
        IF "Prices Including VAT" THEN
          PurchLine."Line Amount" := PurchLine."Amount Including VAT" + PurchLine."Inv. Discount Amount"
        ELSE
          PurchLine."Line Amount" := PurchLine.Amount + PurchLine."Inv. Discount Amount";
      END;
      //++++++++++++++++++++++++++++
      OnValidatePricesIncludingVATOnBeforePurchLineModify(VAR PurchHeader : Record "Purchase Header";VAR PurchLine : Record "Purchase Line";Currency : Record Currency;RecalculatePrice : Boolean)      
      //----------------------------
      PurchLine.MODIFY;
    UNTIL PurchLine.NEXT = 0;
  END;
  OnAfterChangePricesIncludingVAT(Rec);
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
