### ISSUE TITLE
[Event Request] Codeunit 5520 Function GetSalesLineNeededQty

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4530]
Publisher:
OnBeforeGetSalesLineNeededQty(SalesLine : Record "Sales Line";NeededQty: Decimal ;Handled: boolean)

Additionally the return Value for the function GetSalesLineNeededQty should be appropriately named:
GetSalesLineNeededQty(SalesLine : Record "Sales Line") NeededQty : Decimal

Second Publisher needed:
OnAfterGetUnplanned(VAR Rec : Record "Unplanned Demand") just before Windows.CLOSE.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by cghasvi** [comment]
I see this event is present i version 15.3.40074.41129 but is IsHandled-code missing?  Maybe:
       if IsHandled then
            exit(NeededQty);
