### ISSUE TITLE
[Event Request] Codeunit 80 - f(x) PostItemTrackingForShipment

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4531]
Hi!

We need an additional event before ShipmentInvoiceErr is thrown in f(x) PostItemTrackingForShipment in the Sales-Post codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/66740668-03dddf00-ee74-11e9-9a49-5f87774e57c8.png)

![image](https://user-images.githubusercontent.com/55734714/66740680-0cceb080-ee74-11e9-8d8d-d0bac24fc323.png)
Thanks!

**Comment by AlexanderYakunin** [comment]
We already have it!

            end else begin
                IsHandled := false;
                OnPostItemTrackingForShipmentOnBeforeShipmentInvoiceErr(SalesLine, IsHandled);
                if not IsHandled then
                    Error(
                      ShipmentInvoiceErr, SalesLine."Shipment Line No.", SalesLine."Shipment No.");
            end;

**Comment by andersnordmann** [comment]
Thanks! Sorry I missed it :)
