### ISSUE TITLE
BaseApp Source

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#4532]
Hi, 

are there any plans on putting the base app sources on this or another GitHub repository? 

Thanks
Julian

**Comment by AlexanderYakunin** [comment]
No, but this is available to authorized partners using other means.

**Comment by JulianTillmann** [comment]
okay, you mean like the product DVD right? then this case can be closed then

**Comment by NKarolak** [comment]
On the BC 15 DVD, you find the Base app objects under "Dynamics 365 Business Central 2019 Release Wave 2.DE.36649\Applications\BaseApp\Source\Base Application.Source.zip"
