### ISSUE TITLE
[Event Request] Codeunit 6501 - f(x) AssistEditTrackingNo

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4535]
Hi!

We need an additional event before the RetrieveLookupData call in f(x) AssistEditTrackingNo in the Item Tracking Data Collection codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/66748861-8cff1100-ee88-11e9-9641-74f2a846f9a8.png)

![image](https://user-images.githubusercontent.com/55734714/66748870-96887900-ee88-11e9-948f-c310bfc884bf.png)
Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
