### ISSUE TITLE
Add Text fields to Invoice Post. Buffer and Invt. Posting Buffer

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#4536]
We can see a lot of Event publishers there to alter the posting summary into G/L and Item Ledger.  However it lacks facility to add an additional field to summarize by.  A very popular customer request is to post invoice line description to G/L entry and summarize to G/L Postings by it.  To support this can you please add a new text field called "Posting Description" to  Invoice Post. Buffer and Invt. Posting Buffer (table 48 & 49) and add it to the primary key and hence existing events such as OnAfterInvPostBufferPrepareSales on table 49 and OnAfterCopyGenJnlLineFromInvPostBuffer on table 81 can be better used for such popular customer requirement.  It will give above event publisher for more meaning in standard cronus database.

So please add the text filed of size 50 to table 48 & 49 and add it to the primary key so it has a lot of scope for customization.

**Comment by AlexanderYakunin** [comment]
We already have field Additional Identifier Text[250] for this purpose. FYI - We cannot change primary keys anymore, this is breaking change for cloud. If you have specific event change requests, please created them separately.

**Comment by Rama-M** [comment]
Hi Alex,

Now a days extension is the only option for any customisation. Using extension we could not alter primary key of any standard table such as invoice posting buffer.

Also had a look at the fields in invoice posting buffer in business central - release 2 and could not see any text field with length 250.

So stuck on these kind of customisation (which is a very popular request from customer) in future versions of NAV.

It is not a good idea to sacrifice the ability to customize, as it will lead customers going away from NAV and choose other systems instad. Please forward this request to the product development team highlighting the high commercial impact of taking away the ability to change standard objects, but not giving the same ability through extension.

Thanks

Rama Mathanmohan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
