### ISSUE TITLE
[Event Request] Codeunit 333 - OnFinalizeOrderHeaderOnAfterSetFiltersForNonRecurringReqLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4538]
Can you add IsHandled to event OnFinalizeOrderHeaderOnAfterSetFiltersForNonRecurringReqLine in codeunit 333 "Req. Wksh.-Make Order", procedure FinalizeOrderHeader?

![image](https://user-images.githubusercontent.com/46031720/66773886-66f56300-eec0-11e9-9698-211415b93e8c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
