### ISSUE TITLE
[Event Request] Change Event in Codeunit 99000773

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#4540]
**Please Change Event in Codeunit 99000773 like “same” Event in Codeunit 99000809**

Codeunit  99000773 Calculate Prod. Order.

```
[External] Calculate(ProdOrderLine2 : Record "Prod. Order Line";Direction : 'Forward,Backward';CalcRouting : Boolean;CalcComponents : Boolean;DeleteRelations : Boolean;LetDueDateDecrease : Boolean) : Boolean
ProdOrderLine := ProdOrderLine2;

OnBeforeCalculate(ItemLedgEntry,CapLedgEntry);

IF ProdOrderLine.Status = ProdOrderLine.Status::Released THEN BEGIN
  ItemLedgEntry.SETCURRENTKEY("Order Type","Order No.");
…

```
Like

Codeunit 99000809 Planning Line Management

```
[External] Calculate(VAR ReqLine2 : Record "Requisition Line";Direction : 'Forward,Backward';CalcRouting : Boolean;CalcComponents : Boolean;PlanningLevel : Integer)
IsHandled := FALSE;
OnBeforeCalculate(ReqLine2,Direction,CalcRouting,CalcComponents,PlanningLevel,IsHandled);
IF IsHandled THEN
  EXIT;

ReqLine := ReqLine2;
IF ReqLine."Action Message" <> ReqLine
…

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
