### ISSUE TITLE
[Request for External] Table 5741 InitQtyInTransit InitOutstandingQty InitQtyToShip InitQtyToReceive

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4542]
please makew the following procedures in table 5741 public and external - this has been done for similar procedures in tbale 37 and 39:

InitQtyInTransit;
InitOutstandingQty;
InitQtyToShip;
InitQtyToReceive;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
