### ISSUE TITLE
[Event Request] Table 901 OnAfterInitRemaining and OnAfterInitQtyToConsume

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4543]
please add in table 901 OnAfterInitRemaining and OnAfterInitQtyToConsume which are similar existing in table 900:

[External] InitRemainingQty()
"Remaining Quantity" := MaxValue(Quantity - "Consumed Quantity",0);
"Remaining Quantity (Base)" := MaxValue("Quantity (Base)" - "Consumed Quantity (Base)",0);
OnAfterInitRemaining(Rec,CurrFieldNo);

[External] InitQtyToConsume()
GetHeader;
"Quantity to Consume" :=
  MinValue(MaxQtyToConsume,CalcQuantity("Quantity per",AssemblyHeader."Quantity to Assemble"));
"Quantity to Consume (Base)" :=
  MinValue(
    MaxQtyToConsumeBase,
    CalcBaseQty(CalcQuantity("Quantity per",AssemblyHeader."Quantity to Assemble (Base)")));

OnAfterInitQtyToConsume(Rec,CurrFieldNo);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
