### ISSUE TITLE
[Event Request] Page 6510 OnAddReservEntriesToTempRecSetOnBeforeInsert

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4545]
Please add the  additional Parameter Color and SwapSign to OnAddReservEntriesToTempRecSetOnBeforeInsert on Page 6510:

old:
LOCAL [IntegrationEvent] OnAddReservEntriesToTempRecSetOnBeforeInsert(VAR TempTrackingSpecification : TEMPORARY Record "Tracking Specification";ReservationEntry : Record "Reservation Entry")
new:
LOCAL [IntegrationEvent] OnAddReservEntriesToTempRecSetOnBeforeInsert(VAR TempTrackingSpecification : TEMPORARY Record "Tracking Specification";ReservationEntry : Record "Reservation Entry";SwapSign : Boolean;Color : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
