### ISSUE TITLE
[Event Request] Page 6510 OnBeforeAddToGlobalRecordSet

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4546]
Please add the additional Parameter CurrentSignFactor to OnBeforeAddToGlobalRecordSet

old:
LOCAL [IntegrationEvent] OnBeforeAddToGlobalRecordSet(VAR TrackingSpecification : Record "Tracking Specification";EntriesExist : Boolean)
new:
LOCAL [IntegrationEvent] OnBeforeAddToGlobalRecordSet(VAR TrackingSpecification : Record "Tracking Specification";EntriesExist : Boolean;CurrentSignFactor : Integer);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
