### ISSUE TITLE
Codeunit 311- ShowWarningForThisItem

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#4547]
Please Insert a new Publisher in function ShowWarningForThisItem

[External] ShowWarningForThisItem(ItemNo : Code[20]) : Boolean
IF NOT Item.GET(ItemNo) THEN
  EXIT(FALSE);

--------NEW-------
IsHandled := false;
OnBeforeShowWarningForThisItem(ItemNo,IsHandled,ShowWarning);
If IsHandled then
  EXIT(ShowWarning);
--------NEW------

IF Item.IsNonInventoriableType THEN
  EXIT(FALSE);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
