### ISSUE TITLE
[Event Request] Codeunit 7313 OnBeforeWhseActivHeaderInsert

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4549]
Please add an additional Parameter PostedWhseReceiptLine to the trigger OnBeforeWhseActivHeaderInsert:

old:
LOCAL [IntegrationEvent] OnBeforeWhseActivHeaderInsert(VAR WarehouseActivityHeader : Record "Warehouse Activity Header")
new:
LOCAL [IntegrationEvent] OnBeforeWhseActivHeaderInsert(VAR WarehouseActivityHeader : Record "Warehouse Activity Header";PostedWhseReceiptLine : Record "Posted Whse. Receipt Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
