### ISSUE TITLE
[Event Request] Codeunit 99000832, 99000833, 99000834, 99000836, 99000837, 99000838 OnAfterFilterReservFor

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4550]
please add a new Event trigger OnAfterFilterReservFor in codeunits 99000832, 99000833, 99000834, 99000836 

codeunit 99000832:
[External] FilterReservFor(VAR FilterReservEntry : Record "Reservation Entry";SalesLine : Record "Sales Line")
FilterReservEntry.SetSourceFilter(
  DATABASE::"Sales Line",SalesLine."Document Type",SalesLine."Document No.",SalesLine."Line No.",FALSE);
FilterReservEntry.SetSourceFilter2('',0);

//+++++++++++++++++++++++++++++++++++++
OnAfterFilterReservFor(VAR FilterReservEntry;SalesLine);
//-------------------------------------

codeunit 99000833:
[External] FilterReservFor(VAR FilterReservEntry : Record "Reservation Entry";ReqLine : Record "Requisition Line")
FilterReservEntry.SetSourceFilter(DATABASE::"Requisition Line",0,ReqLine."Worksheet Template Name",ReqLine."Line No.",FALSE);
FilterReservEntry.SetSourceFilter2(ReqLine."Journal Batch Name",0);

//+++++++++++++++++++++++++++++++++++++
OnAfterFilterReservFor(VAR FilterReservEntry;ReqLine);
//-------------------------------------

codeunit 99000834:
[External] FilterReservFor(VAR FilterReservEntry : Record "Reservation Entry";PurchLine : Record "Purchase Line")
FilterReservEntry.SetSourceFilter(
  DATABASE::"Purchase Line",PurchLine."Document Type",PurchLine."Document No.",PurchLine."Line No.",FALSE);
FilterReservEntry.SetSourceFilter2('',0);

//+++++++++++++++++++++++++++++++++++++
OnAfterFilterReservFor(VAR FilterReservEntry;PurchLine);
//-------------------------------------

codeunit 99000836:
[External] FilterReservFor(VAR FilterReservEntry : Record "Reservation Entry";TransLine : Record "Transfer Line";Direction : 'Outbound,Inbound')
FilterReservEntry.SetSourceFilter(DATABASE::"Transfer Line",Direction,TransLine."Document No.",TransLine."Line No.",FALSE);
FilterReservEntry.SetSourceFilter2('',TransLine."Derived From Line No.");

//+++++++++++++++++++++++++++++++++++++
OnAfterFilterReservFor(VAR FilterReservEntry;TransLine,Direction);
//-------------------------------------

codeunit 99000837:
[External] FilterReservFor(VAR FilterReservEntry : Record "Reservation Entry";ProdOrderLine : Record "Prod. Order Line")
FilterReservEntry.SetSourceFilter(DATABASE::"Prod. Order Line",ProdOrderLine.Status,ProdOrderLine."Prod. Order No.",0,FALSE);
FilterReservEntry.SetSourceFilter2('',ProdOrderLine."Line No.");

//+++++++++++++++++++++++++++++++++++++
OnAfterFilterReservFor(VAR FilterReservEntry;ProdOrderLine);
//-------------------------------------

codeunit 99000838:
[External] FilterReservFor(VAR FilterReservEntry : Record "Reservation Entry";ProdOrderComp : Record "Prod. Order Component")
FilterReservEntry.SetSourceFilter(
  DATABASE::"Prod. Order Component",ProdOrderComp.Status,ProdOrderComp."Prod. Order No.",ProdOrderComp."Line No.",FALSE);
FilterReservEntry.SetSourceFilter2('',ProdOrderComp."Prod. Order Line No.");

//+++++++++++++++++++++++++++++++++++++
OnAfterFilterReservFor(VAR FilterReservEntry;ProdOrderComp);
//-------------------------------------

**Comment by AlexanderYakunin** [comment]
We do major refactoring of reservation system and going to deprecate these functions. Instead we will use functions like SalesLine.SetReservationFilters(FilterReservEntry). This is already implemented in Master and you check check it in preview builds. Would it be better to implement events in table functions?

**Comment by AlexanderYakunin** [comment]
Please reply

**Comment by GuntherGebauer** [comment]
yes, would be nice to have those new Events then in the tables
e.g. in T37 in SalesLine.SetReservationFilters(FilterReservEntry) the Event 
OnAfterFilterReservFor(VAR FilterReservEntry;SalesLine);
