### ISSUE TITLE
[Event Parameter] Codeunit 22 Item Jnl.-Post Line OnBeforeRunWithCheck Add Sender

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#4551]
Could you please add var access to the sender (ref. Codeunit 22 Item Jnl.-Post Line) for "OnBeforeRunWithCheck" ?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
