### ISSUE TITLE
CarteraManagement extensibility 

### ISSUE THREAD

**Issue by amparomoll** [microsoft/ALAppExtensions#4552]
In issues 2853: CarteraManagement extensibility, it was requested to be able to extend this codeunit.

The specific request was:

In order to implement adequate tests, we need this functions to be exposed in codeunit CarteraManagement in Spanish localization:
InsertReceivableDocs
InsertPayableDocs
RemoveReceivableDocs
RemovePayableDocs
Also, we need 2 integration events in function RemoveReceivableDocs and RemovePayableDocs.

On 20 Jun were added, but now, the 2 events exist but the other functions are not accesible from Cloud because the property Scop is Onprem

[Scope('OnPrem')]
    procedure InsertPayableDocs(var CarteraDoc2: Record "Cartera Doc.")

We need to access the functions again

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
