### ISSUE TITLE
Make public access to ValidatePasswordStrength and ValidatePassword

### ISSUE THREAD

**Issue by plagijat** [microsoft/ALAppExtensions#4553]
ValidatePasswordStrength has been moved from IdentityManagement Codeunit. Please make publicly accessible the following functions from the Codeunit "Password Dialog Impl.":

- ValidatePassword
- ValidatePasswordStrength

These functions can be reused for other implementations of checking passwords in different apps.

Thanks,
Zoran M.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by mazhelez** [comment]
Hey, @plagijat 

The functions you mentioned are part of the implementation and are not supposed to be exposed.

Anyway, thank you for showing interest in the _Password Dialog_ module.
In case you wish to use it, please do it through its public API. If you feel that something is missing, please, open a PR.
