### ISSUE TITLE
[Request for External] Page 96, 97 InsertExtendedText

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4555]
Please make InsertExtendedText on page 96 public and external. This is already done on pages 46, 47, 95 and 98.

old:
LOCAL InsertExtendedText(Unconditionally : Boolean)
new:
[External] InsertExtendedText(Unconditionally : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
