### ISSUE TITLE
[Event Request] - Codeunit 7304 - Suppress batch name increment

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4559]
We are using BC 14.0.35570.

We would like to be able to suppress the incrementing of batch names for warehouse journal batches similar to how we can for item journal batches (CU 23). Copying the item journal functionality should be fine, like this:

    IF NOT WhseJnlLine3.FINDLAST THEN BEGIN // the "BEGIN" bit is new
	  IncrBatchName := INCSTR("Journal Batch Name") <> ''; // New
	  OnBeforeIncrBatchName(WhseJnlLine,IncrBatchName);
      //IF INCSTR("Journal Batch Name") <> '' THEN BEGIN // Old
	  IF IncrBatchName THEN BEGIN // New
        WhseJnlBatch.DELETE;
        WhseJnlBatch.Name := INCSTR("Journal Batch Name");
        IF WhseJnlBatch.INSERT THEN;
        "Journal Batch Name" := WhseJnlBatch.Name;
      END;
	end; // New

With the event definition:

    LOCAL [IntegrationEvent] OnBeforeIncrBatchName(VAR WhseJnlLine : Record "Warehouse Journal Line";VAR IncrBatchName : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
