### ISSUE TITLE
[Event Request] - Codeunit 5751 - Ability to not autofil qty to handle

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4560]
We are using BC 14.0.35570.

When creating warehouse documents, we want to be able control if the "Qty. to Handle" is populated.

To do this, I beleive the function CreateWhseReceiptHeaderFromWhseRequest will need to be modified, as below:

    LOCAL CreateWhseReceiptHeaderFromWhseRequest(VAR WarehouseRequest : Record "Warehouse Request") : Boolean
    IF WarehouseRequest.ISEMPTY THEN
      EXIT(FALSE);
    
    CLEAR(GetSourceDocuments);
    GetSourceDocuments.USEREQUESTPAGE(FALSE);
    GetSourceDocuments.SETTABLEVIEW(WarehouseRequest);
    GetSourceDocuments.SetHideDialog(TRUE);
    OnBeforeGetSourceDocumentsRun(GetSourceDocuments,WarehouseRequest); // New
    GetSourceDocuments.RUNMODAL;

With the event definition:

    LOCAL [IntegrationEvent] OnBeforeGetSourceDocumentsRun(VAR GetSourceDocuments : Report "Get Source Documents";VAR WarehouseRequest : Record "Warehouse Request")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
