### ISSUE TITLE
[Event Request] Table 37 OnAfterCopyFromItem

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4561]
Please add CurrentFieldNo as additional Parameter to the Event trigger OnAfterCopyFromItem

old:
LOCAL [IntegrationEvent] OnAfterCopyFromItem(VAR SalesLine : Record "Sales Line";Item : Record Item)
new:
LOCAL [IntegrationEvent] OnAfterCopyFromItem(VAR SalesLine : Record "Sales Line";Item : Record Item;CurrentFieldNo : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
