### ISSUE TITLE
[Event Request] Table 39 OnAfterAssignItemValues

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4562]
Please add CurrentFieldNo as additional Parameter to the Event trigger OnAfterAssignItemValues:

old:
LOCAL [IntegrationEvent] OnAfterAssignItemValues(VAR PurchLine : Record "Purchase Line";Item : Record Item)
new:
LOCAL [IntegrationEvent] OnAfterAssignItemValues(VAR PurchLine : Record "Purchase Line";Item : Record Item;CurrentFieldNo : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
