### ISSUE TITLE
[Event Request] Table 37 OnAfterAssignItemUOM

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4563]
Please add the additional Parameter CurrentFieldNo to OnAfterAssignItemUOM:

old:
LOCAL [IntegrationEvent] OnAfterAssignItemUOM(VAR SalesLine : Record "Sales Line";Item : Record Item)
new:
LOCAL [IntegrationEvent] OnAfterAssignItemUOM(VAR SalesLine : Record "Sales Line";Item : Record Item;CurrentFieldNo : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
