### ISSUE TITLE
[Request for External] Table 900 CheckIsNotAsmToOrder

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4565]
Please make Procedure CheckIsNotAsmToOrder in table 900 public and external

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
