### ISSUE TITLE
Codeunit 90 Purch.-Post - Redesign Publisher

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#4567]
A publisher has been added for option 3 of the purchase line so that developers can react to it. Unfortunately this publisher is dead, because it is simply unusable. The publisher has no reference to any global parameter used in the codeunit. No Gen Jnl Line, no document no., no srccode, only PO Header an Line. The Property GlobalVarAccess is also deactivated.

Publisher OnBeforePostResourceLine(PurchaseHeader,PurchaseLine,IsHandled);

What's that supposed to do?
If you have developed a posting routine for resources as a partner, you cannot use the Publisher.
Please change.
Example

PostResourceLineGOB(PurchLine,PurchHeader,GenJnlLineDocNo,GenJnlLineExtDocNo,SrcCode);

**Comment by AlexanderYakunin** [comment]
We have a plan here, this is just step 1.
