### ISSUE TITLE
Table 37 Sales Line - OnAfterValidateCrossReferenceNo

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#4568]
Please correct the publisher and insert the var option for parameter SalesLine
OLD
LOCAL [IntegrationEvent] OnAfterValidateCrossReferenceNo(SalesLine : Record "Sales Line";ItemCrossReference : Record "Item Cross Reference")

NEW
LOCAL [IntegrationEvent] OnAfterValidateCrossReferenceNo(VAR SalesLine : Record "Sales Line";ItemCrossReference : Record "Item Cross Reference")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
