### ISSUE TITLE
New Publisher in CU57 in Procedure CalculateSalesPageTotals

### ISSUE THREAD

**Issue by Surya-mst** [Microsoft/ALAppExtensions#457]
Please provide new publisher in Codeunit 57 Function "CalculateSalesPageTotals" as shown below with **TotSalesLine VAR**.

[IntegrationEvent] OnAfterCalcSalesPageTotals(SalesHeader : Record "Sales Header";VAR TotSalesLine : Record "Sales Line";SalesLine : Record "Sales Line")

![image](https://user-images.githubusercontent.com/34340535/49082593-24a74100-f270-11e8-8b18-1e0ae53c529e.png)

**Comment by AlexanderYakunin** [comment]
You probably have old version, please check latest D365 BC code base as this code is different here

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
