### ISSUE TITLE
[Event Request] Codeunit 5802 Inventory Posting To G/L - OnBeforeGetInvPostingGroupCode

### ISSUE THREAD

**Issue by florindanu** [microsoft/ALAppExtensions#4571]
Hello,

In our accounting the WIP Inventory is managed in a different way and we need a new Integration event in Codeunit 5802 Inventory Posting To G/L to support this:

    LOCAL PROCEDURE GetInvPostingGroupCode@32(ValueEntry@1000 : Record 5802;WIPInventory@1001 : Boolean;InvPostingGroupCode@1002 : Code[20]) : Code[20];
    VAR
      Item@1003 : Record 27;
    BEGIN
      IF WIPInventory THEN
        // Start Code
        OnBeforeGetInvPostingGroupCode(ValueEntry,InvPostingGroupCode);
        // End Code
        IF ValueEntry."Source No." <> ValueEntry."Item No." THEN
          IF Item.GET(ValueEntry."Source No.") THEN
            EXIT(Item."Inventory Posting Group");

      EXIT(InvPostingGroupCode);
    END;

Event declaration:

    [Integration]
    LOCAL PROCEDURE OnBeforeGetInvPostingGroupCode@44(ValueEntry@1000 : Record 5802;InvPostingGroupCode@1001 : Code[20]);
    BEGIN
    END;

Many thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
