### ISSUE TITLE
Issue with Extensibility of Pages General Journal, Sales Journal, Purchase Journal, Cash Receipt Journal and Recurring General Journal

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#4572]
Hi,

Can you make global variables **AccName** and **BalAccName** (probably through some Get and Set procedures) and procedure **ShowShortcutDimCode(ShortcutDimCode)** or just global variable **ShortcutDimCode** accessible from page extensions, so we can write some code in page extension to work like this one below?
_GenJnlManagement.GetAccounts(Rec, AccName, BalAccName);
ShowShortcutDimCode(ShortcutDimCode);_

Need this on the following pages:
- General Journal
- Sales Journal
- Purchase Journal
- Cash Receipt Journal
- Recurring General Journal

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
This procedure is part of Gen. Journal Line table (not related pages) and already External. Please explain in details what you would like to do?

    procedure ShowShortcutDimCode(var ShortcutDimCode: array[8] of Code[20])
    begin
        DimMgt.GetShortcutDimensions("Dimension Set ID", ShortcutDimCode);
    end;

**Comment by zulezmaj** [comment]
@AlexanderYakunin is there any news about this?

**Comment by AlexanderYakunin** [comment]
These functions needs to run if you change Account No. or Bal. Account No. Why do you need to run it for your custom field?

**Comment by zulezmaj** [comment]
> These functions needs to run if you change Account No. or Bal. Account No. Why do you need to run it for your custom field?

Because my custom field in its OnValidate trigger on table level has code that populates "Account No." (therefore related variable for account name should be update too) and updates "Dimension Set ID" which means that ShortcutDimCode variable values are updated. 

Workaround is to call CurrPage.Update(); in its OnValidate trigger, but calling this 2 functions is more elegant way.

**Comment by AlexanderYakunin** [comment]
Can you simply use Validate("Account No.") instead?

**Comment by zulezmaj** [comment]
Code in OnValidate trigger in my custom field in table extension already populates both of them ("Account No.", "Dimension Set ID") using Validate, but what I want to achieve with calling functions GenJnlManagement.GetAccounts(Rec,AccName,BalAccName) and ShowShortcutDimCode(ShortcutDimCode) is to have related columns updated right away when value is entered into my field.

**Comment by AlexanderYakunin** [comment]
These functions does not have any relation to the page and belongs to another objects. You need to reconsider your design, or simply use UpdatePage.
