### ISSUE TITLE
Accessing externally global variable ShortcutDimCode on document subform pages

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#4573]
Hi,

I need a way to access global variable **ShortcutDimCode** in order to have code like this _ShowShortcutDimCode(ShortcutDimCode);_ in my page extensions for the following pages:
- Sales Order Subform
- Sales Invoice Subform
- Purchase Order Subform
- Purch. Invoice Subform
- Sales Quote Subform
- Sales Cr. Memo Subform
- Purchase Quote Subform
- Purch. Cr. Memo Subform
- Sales Return Order Subform
- Purchase Return Order Subform

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
If you have "Dimension Set ID", you can get ShortcutDimCode using DimMgt.GetShortcutDimensions("Dimension Set ID", ShortcutDimCode) in your code.
