### ISSUE TITLE
[Request for External] Table 5996 Standard Service Code, and table 5998 functions GetNextLineNo and InsertExtendedText

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4575]
Please make the following functions externally accessible.  Thank you.

![image](https://user-images.githubusercontent.com/49729094/66951616-cd959080-f028-11e9-8f87-f035d2bc89aa.png)

![image](https://user-images.githubusercontent.com/49729094/66952348-72649d80-f02a-11e9-9717-6fe05f7b8503.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
