### ISSUE TITLE
PTE Upgrade Fails with Error: The record in table Custom Report Layout already exists.

### ISSUE THREAD

**Issue by SorenAU** [microsoft/ALAppExtensions#4576]
15.0.36510.0-AU
MyApp includes 2 Custom Report Layouts (as [name].layoutdate) that are automatically inserted by the BC installer i.e. not by the extension code.
These Custom Report Layout records are successfully inserted on the initial deployment; but subsequent attempt to deploy a newer extension version Fail.
This problem has only started on BC v15 as upgrades have worked fine with v13 and v14 where the pre-existing records were deleted and replaced by the newer versions.

Steps to Repro:
 1 - Package a new PTE v1 and include a Custom Report Layout file (created using Export-NAVAppReportLayout cmdlet).
 2 - Install PTE v1.
 3 - The Custom Report Layout is created.
 4 - Package same PTE as v2.
 5 - Install PTE v2.
Expected results:
 1 - The v1 Custom Report Layout is replaced by v2.
Actual results:
 1 - Deployment fails.

Deployment Error Details (short) -
Deployment failed. Errors: App ID : [MyAppId] 0 Message :
{ A request to the Data Plane Admin Service failed.
Http status code: BadRequest
Error: {
ExtensionChangeFailed; Could not upgrade the extension [MyAppName] for tenant [MyTenantId] due to the following error: The record in table Custom Report Layout already exists. Identification fields and values: Code='MCH-72203-EMAIL'
{AppUpgradeCodeExecutionFailure}}
- Job Id: cba0696b-7461-4f22-80c1-d58fcfdbcb17

-------
Please Note:
I have in the past had to patch the inserted Custom Report Layout records in the Install/Upgrade Codeunits as BC incorrectly flags them as being Built-In (bug); but without actually inserting a Custom Layout in T9650 HandleW10Layout().

**Comment by AlexanderYakunin** [comment]
Hello! This area is for extensibility requests, if you need support you can create ticket from your cloud app or contact Technical Support.
