### ISSUE TITLE
[Event Request] Page 498 Function SetSalesLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4581]
Publisher needed in function SetSalesLine in the page 498:

IsHandled := FALSE;
OnSetSalesLineOnBeforeTestJobNo(var CurrentSalesLine:Record "Sales Line",var IsHandled: boolean);
IF NOT IsHandled THEN
  CurrentSalesLine.TESTFIELD("Job No.",'');

**Comment by AlexanderYakunin** [comment]
We cannot add more events to reservation area now due to major rework of reservation system. Please check latest preview builds from Master to check if this is still relevant for new design.
