### ISSUE TITLE
[Event Request] Table 37 - OnBeforeShowReservation

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4582]
The publisher OnBeforeShowReservation has two parameters:
OnBeforeShowReservation(SalesLine: Record "Sales Line"; var IsHandled: Boolean)

The first parameter should be passed as a var in order to be able to update the Sales Line.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
