### ISSUE TITLE
Codeunit 311 Item-Check Avail. Functions ShowAndHandleAvailabilityPage and ShowWarning 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4583]
Please make the following functions externally accessible. Thank you.

![image](https://user-images.githubusercontent.com/49729094/67023387-b9a56980-f0d0-11e9-91b3-20670c6d3b36.png)

![image](https://user-images.githubusercontent.com/49729094/67023485-dfcb0980-f0d0-11e9-99aa-f6c7382f7eba.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
