### ISSUE TITLE
Page 55 Purch. Invoice Subform-make local functions external - SetItemChargeFieldsStyle

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4585]
Thanks!

![image](https://user-images.githubusercontent.com/49729094/67030620-c7152080-f0dd-11e9-9e87-34f0df4f9033.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
