### ISSUE TITLE
"Purch. Price Calc. Mgt.": CalcBestDirectUnitCost global, new global function SetItem, new global function SetVendor

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#4586]
we need the function CalcBestDirectUnitCost to be global. In addition to use CalcBestDirectUnitCost correctly we need two more global functions in the Codeunit "Purch. Price Calc. Mgt.": 

![image](https://user-images.githubusercontent.com/34675109/67074928-727baf00-f18a-11e9-910a-329e95778fa8.png)

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
