### ISSUE TITLE
[Event Request] Table 37 - OnBeforeAutoReserve

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4587]
The Publisher in the Function AutoReserve has following signature:
OnBeforeAutoReserve(SalesLine : Record "Sales Line";VAR IsHandled : Boolean)

but should be
OnBeforeAutoReserve(var SalesLine : Record "Sales Line";VAR IsHandled : Boolean)
in order that the Sales Line can be updated

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
