### ISSUE TITLE
[Request for External] Report 5753 "Get Source Documents" CreateReceiptHeader()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#4588]
Could you please change procedure CreateReceiptHeader() to global & external?

many thanks
Stefan

```
  local procedure CreateReceiptHeader()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateRcptHeader(WhseReceiptHeader, "Warehouse Request", "Purchase Line", IsHandled);
        if IsHandled then
            exit;

[...]
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
