### ISSUE TITLE
[Event Request] Table 36 - OnAfterUpdateBillToCust

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#4594]
Although we have the events OnAfterUpdateBillToCont, OnAfterUpdateSellToCont and OnAfterUpdateSellToCust on the SalesHeaderTable,  I am missing the event OnAfterUpdateBillToCust(VAR SalesHeader : Record "Sales Header";Contact : Record Contact) and request the implementation of this event. 
Thank you for your attention.
[Request based on BC14CU4. I didn't check newer versions but could not find any event request here on github.]

**Comment by AlexanderYakunin** [comment]
You have event OnUpdateBillToCustOnAfterSalesQuote(Rec, SearchContact); for this purpose

**Comment by sauerkreut** [comment]
Sir,
your mentioned event is only triggered if the "Document Type" = "Document Type"::Quote.
In the local function "UpdateSellToCust" the event OnAfterUpdateSellToCust(Rec,Cont); is correctly implemented.
I still request to implement the event OnAfterUpdateBillToCust(VAR SalesHeader : Record "Sales Header";Contact : Record Contact) at the end of the local function "UpdateBillToCust"
Thank you.

**Comment by AlexanderYakunin** [comment]
OK

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
