### ISSUE TITLE
[Event Request] Codeunit 408 OnBeforeSaveDefaultDim

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#4595]
Please add a new publisher event to the function SaveDefaultDim as follows:

```
[External] SaveDefaultDim(TableID : Integer;No : Code[20];FieldNumber : Integer;ShortcutDimCode : Code[20])
//>> Start New Publisher Call
OnBeforeSaveDefaultDim(TableID, No, FieldNumber, ShortcutDimCode, IsHandled);
IF IsHandled THEN
  EXIT;
//<< End New Publisher Call
GetGLSetup;
IF ShortcutDimCode <> '' THEN BEGIN
  IF DefaultDim.GET(TableID,No,GLSetupShortcutDimCode[FieldNumber])
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeSaveDefaultDim(TableID : Integer;No : Code[20];FieldNumber : Integer;ShortcutDimCode : Code[20];VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
