### ISSUE TITLE
[Event Request] Codeunit 408 OnBeforeCheckDim

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#4596]
Please add a new publisher event to the function CheckDim as follows:

```
[External] CheckDim(DimCode : Code[20]) Result : Boolean
//>> Start New Publisher Call
OnBeforeCheckDim(DimCode, Result, IsHandled);
IF IsHandled THEN
  EXIT;
//<< End New Publisher Call

IF Dim.GET(DimCode) THEN BEGIN
IF Dim.Blocked THEN BEGIN
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeCheckDim(DimCode : Code[20];Result : Boolean;IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
