### ISSUE TITLE
[Event Request] Codeunit 408 OnBeforeCheckDimValue

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#4597]
Please add a new publisher event to the function CheckDimValue as follows:

```
[External] CheckDimValue(DimCode : Code[20];DimValCode : Code[20]) Result : Boolean
//>> Start New Publisher Call
OnBeforeCheckDimValue(DimCode, DimValCode, Result, IsHandled);
IF IsHandled THEN
  EXIT;
//<< End New Publisher Call

IF (DimCode <> '') AND (DimValCode <> '') THEN
IF DimVal.GET(DimCode,DimValCode) THEN BEGIN
  IF DimVal.Blocked THEN BEGIN
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeCheckDimValue(DimCode : Code[20];DimValCode : Code[20];Result : Boolean;IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
