### ISSUE TITLE
[Event Request] Codeunit 408 OnBeforeUpdateDefaultDim

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#4599]
Please add a new publisher event to the function UpdateDefaultDim as follows:

```
[External] UpdateDefaultDim(TableID : Integer;No : Code[20];VAR GlobalDim1Code : Code[20];VAR GlobalDim2Code : Code[20])
//>> Start New Publisher Call
OnBeforeUpdateDefaultDim(TableID, No, GlobalDim1Code, GlobalDim2Code, IsHandled);
IF IsHandled THEN
  EXIT;
//<< End New Publisher Call

GetGLSetup;
IF DefaultDim.GET(TableID,No,GLSetupShortcutDimCode[1]) THEN
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeUpdateDefaultDim(TableID : Integer;No : Code[20];VAR GlobalDim1Code : Code[20];VAR GlobalDim2Code : Code[20];VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
