### ISSUE TITLE
Control Addin is not loading the html resource

### ISSUE THREAD

**Issue by dbsae** [microsoft/ALAppExtensions#4600]
Need Urgent help.

We have Control Addin in which we are loading the html resource . Below the code of files. But when we running on Business central 15 version it's giving us the an error.

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://msasiseaas3331-t5kqfo.applicationservices.businesscentral.dynamics.com/Resources/ExtractedResources/9B4AE231/Equation/MKEquation.html?_v=15.0.36437.0

In On-Premise version is working perfectly. It was working perfectly on cloud as well but suddenly it not founding the resource. but when we click this link it show the html.

**Control Addin Code**
controladdin ftext
{
Scripts =
'Equation/Scripts/jquery-3.3.1.min.js',
'Equation/Scripts/Html.js',
'Equation/Scripts/Equation.js';
StartupScript = 'Equation/Scripts/loadHtml.js';
StyleSheets = 'Equation/Styles/CEquation.css';
Images = 'Equation/MKEquation.html';

RequestedHeight = 750;
RequestedWidth = 420;
HorizontalStretch = true;

procedure SendEquation(vEquation: Text);
event ControlReady();
}

**Load Html.js**
$(document).ready(function(){
dbs.com.loadControlHtml("Equation/MKEquation.html", function () {
Microsoft.Dynamics.NAV.InvokeExtensibilityMethod("ControlReady", [],true);
});
});

**Html.js**
(function ($) {
window.dbs = {
com: {
loadHtml: function (url, callback) {
var url = Microsoft.Dynamics.NAV.GetImageResource(url);
$.get(url, function (data) {
callback(data);
});
},
loadControlHtml: function (url, callback) {
this.loadHtml(url, function (data) {
document.getElementById("controlAddIn").innerHTML = data;
callback();
});
}
}
};
})(jQuery);

**Comment by thpeder** [comment]
Hi @dbsae,

It works just fine for me. I simply took your code and tweaked the names a bit and added a html file which showed up when I went to the page.
Can you still reproduce the issue?

**Comment by dbsae** [comment]
> Hi @dbsae,
> It works just fine for me. I simply took your code and tweaked the names a bit and added a html file which showed up when I went to the page.
> Can you still reproduce the issue?

Dear Thomas

We tried alot to fixed it. But it's not loading the physical html file. So finally we put all the html code in JavaScript function. 
But we are planning to lot of thing to creating via Control Addin  for example organization Chart...etc

Please let us know how what are the tweaked you have done so will try the same. 
Thanks
**Noman Mansoor**

**Comment by thpeder** [comment]
You can find the code I tested with in my repository [thpeder/UsercontrolLoadHtml](https://github.com/thpeder/UsercontrolLoadHtml)

**Comment by atoader** [comment]
This issue has been closed because it needs more information and has not had recent activity. Please open a new issue if you believe this has not been resolved and reference the current issue.
