### ISSUE TITLE
[Event Request] T37 - OnValidateVATProdPostingGroupOnAfterCheckVATCalcType

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#4601]
I would like to request an event on Table 37 - VAT Prod. Posting Group - OnValidate():

Original: 
`IF SalesHeader."Prices Including VAT" AND (Type IN [Type::Item,Type::Resource]) THEN`
` "Unit Price" :=`
`...`

New:
`IsHandled := FALSE;`
`OnValidateVATProdPostingGroupOnBeforeCheckVATCalcType(Rec,VATPostingSetup,IsHandled);`
`IF NOT IsHandled THEN`
`  IF SalesHeader."Prices Including VAT" AND (Type IN [Type::Item,Type::Resource]) THEN`
`    "Unit Price" :=`
`...`

Thank you for your attention.

**Comment by sauerkreut** [comment]
Event name could also be 
OnValidateVATProdPostingGroupOnBeforeUpdateUnitPrice(Rec,VATPostingSetup,IsHandled);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
