### ISSUE TITLE
Table 7317 - Make function CalcBaseQty external

### ISSUE THREAD

**Issue by Nyryus** [microsoft/ALAppExtensions#4602]
Please expose function CalcBaseQty in the table 7317 Warehouse Receipt Line and set it to external. Thank you.

![immagine](https://user-images.githubusercontent.com/40896051/67219706-c4d9fb80-f428-11e9-9c08-570f5ce6f119.png)

**Comment by AlexanderYakunin** [comment]
This function is not used anymore, use UOMMgt.CalcBaseQty.
