### ISSUE TITLE
Page 5901 Service Order Subform/Page 5905 Service Lines - make local functions external 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4603]
Thanks.  

![image](https://user-images.githubusercontent.com/49729094/67214957-a48d4b00-f3ee-11e9-8dd0-347760076cf0.png)

![image](https://user-images.githubusercontent.com/49729094/67218422-58450980-f3f4-11e9-8a80-e4a961e48b73.png)

![image](https://user-images.githubusercontent.com/49729094/67218574-9e01d200-f3f4-11e9-93c0-aa966ded414e.png)

![image](https://user-images.githubusercontent.com/49729094/67218897-25e7dc00-f3f5-11e9-8a3a-40cbd04613e0.png)

![image](https://user-images.githubusercontent.com/49729094/67225309-00f96600-f401-11e9-9a63-615aa0607fef.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
