### ISSUE TITLE
[Event Request] Report 7306 Get Inbound Source Documents

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#4604]
Could we please have a publisher OnPostedWhseReceiptLineOnPreDataItem called in the upper Trigger? 

Purpose: We need to modify the applied Filter-

Reason for asking:
•	The Report if firm used in Codeunit 5751 Get Source Doc. Inbound, Procedure GetSingleWhsePutAwayDoc
•	This Procedure is Used in Page 7352 Put-away Worksheet as AdtionButton. The Call uses Global Page Variables. Those Variables are not accessible for PageExtension.

```
Posted Whse. Receipt Line - OnPreDataItem()
//>>>>>>
//Application: Set Filters on "Posted Whse. Receipt Line"
OnPostedWhseReceiptLineOnPreDataItem("Posted Whse. Receipt Line");
//<<<<<<



New Publisher in this Report:
LOCAL [IntegrationEvent] OnPostedWhseReceiptLineOnPreDataItem(
VAR PostedWhseReceiptLine: Record "Posted Whse. Receipt Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
