### ISSUE TITLE
Item Attributes Value Selection Extensability

### ISSUE THREAD

**Issue by JonasPatto** [microsoft/ALAppExtensions#4605]
References: 
https://github.com/microsoft/ALAppExtensions/issues/4129
https://github.com/microsoft/ALAppExtensions/issues/2274

Hello Microsoft-Team,

in those 2 issues we described the problem with the extensability from Item Attributes Values. With BC15 you gave us some Publisher but they only solved half the problems. While you can now save your custom Value in the "Item Attribute Mapping" and "Item Attribute Value Selection" Table it is still difficult get the value from the Mapping-Table (Possible with bad coding in my opinion). 

Why is this so? 
The current Code fills the Item Attribute Value Selection from the Item Attribute Mapping Table by filtering for the "ID" and "Value". From this filter you can only get the value which is saved within the Item Attribute Value Selection Table while ignoring the value within the Mapping Table. 

Why is this important for me?
For our Extension the customer can apply a, let's call it a sorting priority. This information is pre-stored in the "Item Attribute Value" Table and will be transfered to the "Item Attribute Value Selection" Table but they can change the value anytime in the "Item Attribute Value Selection"-Page if necessary. While I can save the correct Value in the Mapping-Table it'll still be displayed wrong for the customer if he reopens the Page due to the fact that the Microsoft-Code takes my Custom-Field Value from the "wrong" Table and I want to fix that. 

My current Solution:

I tried out a few ideas to solve this problem with the current Events and I even found a solution but it's really bad for the single reason that I HAVE TO save the "Item No." in the "Item Attribute Value"-Table which shouldn't know in which Item it is used.

Code:

![image](https://user-images.githubusercontent.com/48987445/67271473-dff54b80-f4ba-11e9-82aa-2788b0ebba29.png)
![image](https://user-images.githubusercontent.com/48987445/67271560-074c1880-f4bb-11e9-88c7-f6d253599852.png)
![image](https://user-images.githubusercontent.com/48987445/67271620-23e85080-f4bb-11e9-9e3a-a548ffd0320b.png)

Extensability Enhancement Idea:

Extend one procedure by 2 parameters and use them:

In Table 7504 "Item Attribute Value Selection" extend the procedure "PopulateItemAttributeValueSelection" so it looks like this:
![image](https://user-images.githubusercontent.com/48987445/67271999-f64fd700-f4bb-11e9-8ed4-4413b0391cc0.png)

As you can see the Call to "InsertRecord" needs to be adjusted as well.

The last thing to do is to change the call to the "PopulateItemAttributeValueSelection" in the Page 7504 "Item Attribute Value List" like this:
![image](https://user-images.githubusercontent.com/48987445/67272148-475fcb00-f4bc-11e9-9000-206047258865.png)

I can provide my Test-Project if needed.

Thanks.

Best Regards

Jonas Be Patto

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
