### ISSUE TITLE
[Event Request] Codeunit 5830 Calc. Availability Overview

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4607]
Publisher desired on the end of the function CalcRunningTotals:
OnAfterCalcRunningTotals(VAR RunningTotal : Decimal;VAR InventoryRunningTotal : Decimal;VAR SupplyRunningTotal : Decimal;VAR DemandRunningTotal : Decimal)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
