### ISSUE TITLE
[Event Request] Table 1003

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4608]
Publisher needed in Table 1003, end of the function FilterLinesWithItemToPlan:
OnAfterFilterLinesWithItemToPlan(VAR Item : Record Item)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
