### ISSUE TITLE
[Event Request] Codeunit 1002 Job Create-Invoice - CreateSalesInvoice

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#4609]
Could we please have a supplement at publisher OnBeforeGetInvoiceNo in function CreateSalesInvoice  - Codeunit 1002 Job Create-Invoice? 

```

[External] CreateSalesInvoice(VAR JobPlanningLine : Record "Job Planning Line";CrMemo : Boolean)
IF NOT CrMemo THEN BEGIN
  GetSalesInvoiceNo.SetCustomer(JobPlanningLine."Job No.");
  GetSalesInvoiceNo.RUNMODAL;
  IsHandled := FALSE;
  

// >>>>>>>>
//OnBeforeGetInvoiceNo(JobPlanningLine,Done,NewInvoice,PostingDate,I//nvoiceNo,IsHandled);
//
OnBeforeGetInvoiceNo(VAR JobPlanningLine,Done,NewInvoice,PostingDate,InvoiceNo,IsHandled);
// <<<<<<<<     
  IF NOT IsHandled THEN
    GetSalesInvoiceNo.GetInvoiceNo(Done,NewInvoice,PostingDate,InvoiceNo);
END ELSE BEGIN
  GetSalesCrMemoNo.SetCustomer(JobPlanningLine."Job No.");
  GetSalesCrMemoNo.RUNMODAL;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
