### ISSUE TITLE
Table 5901 Service Item No. On Validate trigger 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4612]
This is a follow up for issue #2697.   Sorry, I am not sure how to re-open the issue.   I did comment on the original case.   Thanks very much!!

**Comment by Teming** [comment]
Any suggestion?

**Comment by AlexanderYakunin** [comment]
Please explain what you need to change? It is difficult to understand exactly.

**Comment by Teming** [comment]
Base NAV 
![image](https://user-images.githubusercontent.com/49729094/71102433-7d50c100-2186-11ea-9020-290858a096d4.png)

We have to add the highlighted line (IF "Service Item No." <> '' THEN) around line 202; otherwise, IF "Service Item No." = '', the EXIT command in line 214 would be executed.  If that is the case, the warranty info re-initialization between lines 217 and 224 will not be executed.

![image](https://user-images.githubusercontent.com/49729094/71102761-02d47100-2187-11ea-9384-7db35ff46c58.png)

**Comment by RomanZanizdra** [comment]
Hi @Teming .
The first thing I would like to mention is that empty "Service item No." is not preventing the service order from posting. It could be empty. The next thing, there are three blocks of code (on the picture below). The 1 and 3 blocks will be working only if the value was updated and new value differs from the previous. The 2 block will be working only in the case of validate but the value was not changed. So adding the condition you suggested will not lead us to the 3 block even if we skip "exit" in the 2 block. So I don't see any sense in adding condition in the second block. And finally there is a standard event OnAfterValidate/OnBeforeValidate, you can use for any purposes.

**Comment by RomanZanizdra** [comment]
And if you think there is a bug please log it via appropriate support channel.
