### ISSUE TITLE
Page 46 Sales order Subform-make local functions external

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4615]
Thanks!

![image](https://user-images.githubusercontent.com/49729094/67302229-9a3a8200-f4be-11e9-9fd6-5685e724ad0d.png)

![image](https://user-images.githubusercontent.com/49729094/67302337-c1914f00-f4be-11e9-921d-5c3fab64947c.png)

![image](https://user-images.githubusercontent.com/49729094/67302451-e84f8580-f4be-11e9-9966-26af44d57ab4.png)

![image](https://user-images.githubusercontent.com/49729094/67302573-103ee900-f4bf-11e9-850f-271bbba32f02.png)

**Comment by AlexanderYakunin** [comment]
Already done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
