### ISSUE TITLE
customerFinancialDetails v1.0 API Entity (not finding the al object)

### ISSUE THREAD

**Issue by ccorreia83** [microsoft/ALAppExtensions#4616]
I'm checking the information about moving from beta to v1.0 API (https://docs.microsoft.com/pt-br/dynamics-nav/api-reference/v1.0/moving-from-beta-to-v1), for what I check one of the changes for example is a new entity called customerFinancialDetails.
I'm looking for the API page that has the code, so I can see from where is the code, but I don't find any API page with reference to customerFinancialDetails.

Also if I check salesInvoice API page the structure in the page is the beta structure, where can we find the API pages to v1.0 changes?

I'm using BC 15 wave 2.

**Comment by nikolakukrika** [comment]
The API V1 pages are an extension.  You can find the code under:
W1DVD\Extensions\APIV1.Source.zip

**Comment by nikolakukrika** [comment]
The pages in the baseApplication are Beta API pages and these pages will be removed soon.
