### ISSUE TITLE
table 1301 item Template - make local functions "AddToArray" external

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4621]
Thanks.

![image](https://user-images.githubusercontent.com/49729094/67429214-b23cff00-f5ad-11e9-9a02-e6699c73cff4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
