### ISSUE TITLE
[Event Request] Report 5753 - CheckFillQtyToHandle

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4622]
We are using BC 14.0.35570.

We want to be able to override the DoNotFillQtytoHandle variable when running the CheckFillQtyToHandle function. It will be used when creating warehouse documents via the web service. Something like this:

    LOCAL CheckFillQtyToHandle()
    OnBeforeCheckFillQtyToHandle(DoNotFillQtytoHandle,RequestType); // New
    IF DoNotFillQtytoHandle AND (RequestType = RequestType::Receive) THEN BEGIN
      WhseReceiptLine.RESET;
      WhseReceiptLine.SETRANGE("No.",WhseReceiptHeader."No.");
      WhseReceiptLine.DeleteQtyToReceive(WhseReceiptLine);
    END;

With the event definition like this:

    LOCAL [IntegrationEvent] OnBeforeCheckFillQtyToHandle(VAR DoNotFillQtytoHandle: Boolean; RequestType: Option)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
