### ISSUE TITLE
[Event Request] Codeunit 5752 - CheckSalesHeader

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4623]
We are using BC 14.0.35570.

In the CheckSalesHeader function in Codeunit 5752, we would like the ability to change the value of ShowError.

It seems like the existing event OnBeforeCheckTransferHeader almost does this, but the ShowError parameter is not passed by reference. If we could change this from:

    LOCAL [IntegrationEvent] OnBeforeCheckTransferHeader(VAR TransferHeader : Record "Transfer Header";ShowError : Boolean)

to 

    LOCAL [IntegrationEvent] OnBeforeCheckTransferHeader(VAR TransferHeader : Record "Transfer Header";VAR ShowError : Boolean)

We would get the functionality we are after.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
