### ISSUE TITLE
[Event Request] - Codeunit 5752 - ShowResult

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4624]
We are using BC 14.0.35570.

We would like to be able to suppress the ShowResult messages/dialog in codeunit 5752.

Suggested new code:

    LOCAL ShowResult(WhseShipmentCreated : Boolean)
    OnBeforeShowResult(WhseShipmentCreated, Handled); // New
    IF Handled then // New
      EXIT; // New
    IF WhseShipmentCreated THEN BEGIN
      GetSourceDocuments.ShowShipmentDialog;
      OpenWarehouseShipmentPage;
    END ELSE
      MESSAGE(Text004,WarehouseRequest.TABLECAPTION);

With the event definition:

    LOCAL [IntegrationEvent] OnBeforeShowResult(WhseShipmentCreated: Boolean; VAR Handled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
