### ISSUE TITLE
[Event Request] - Codeunit 5760 PostSourceDocument

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4625]
We are using BC 14.0.35570.

We would like the ability to handle the PostSourceDocument function. So, something like this would work for us:

    LOCAL PostSourceDocument(WhseRcptLine : Record "Warehouse Receipt Line")
    OnBeforePostSourceDocument(WhseRcptLine, PurchHeader, SalesHeader, TransHeader, CounterSourceDocOK, HideValidationDialog, Handled); // New 
    IF Handled then // New
      EXIT; // New
    WhseSetup.GET;
    WITH WhseRcptLine DO BEGIN

With an event definition:

    LOCAL [IntegrationEvent] OnBeforePostSourceDocument(WhseRcptLine : Record "Warehouse Receipt Line"; VAR PurchHeader: Record "Purchase Header"; VAR SalesHeader: Record "Sales Header"; VAR TransHeader: Record "Transfer Header";VAR CounterSourceDocOK: Integer;  HideValidationDialog: Boolean; VAR Handled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
