### ISSUE TITLE
[EventRequest] Table 5773 "Registered Whse. Activity Line", ShowWhseDoc() [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4626]
Please add a new publisher event OnShowWhseDoc as shown in the picture below in the function ShowWhseDoc in table 5773

![image](https://user-images.githubusercontent.com/54017538/67457864-148d1280-f635-11e9-8f28-52add22d3b74.png)

Please add the corresponding Integration Event In the bottom of the table

![image](https://user-images.githubusercontent.com/54017538/67457923-3c7c7600-f635-11e9-93b6-1695cceef014.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
