### ISSUE TITLE
[EventRequest] Page 46 “Sales Order Subform”, UpdateEditableOnRow [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4627]
Please add a new publisher event OnAfterUpdateEditableRows as shown in the picture below in the function UpdateEditableOnRow in page 46

![image](https://user-images.githubusercontent.com/54017538/67458372-55d1f200-f636-11e9-9194-2f956cb3493d.png)

Please add the corresponding Integration Event In the bottom of the page soruce code

![image](https://user-images.githubusercontent.com/54017538/67458324-320eac00-f636-11e9-98b2-b9ce66063f4c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
