### ISSUE TITLE
[Enhancement] Codeunit 249 LogCustomer,LogVendor and LogContact

### ISSUE THREAD

**Issue by BartPermentier** [Microsoft/ALAppExtensions#463]
This does not work correctly in the BE version of BC since Belgian Customers use the field "Enterprise No." and not "VAT Registration No.".
Proposed solution:
![image](https://user-images.githubusercontent.com/24684493/49093726-06881380-f265-11e8-8ffa-102e63af3a8b.png)

Btw use the same solution for LogVendor and LogContact

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix it, as this repo only is for extensibility related issues. We suggest that you open a support case or file a bug in Collaborate. 

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
