### ISSUE TITLE
[EventRequest] Page 55 “Puch. Invoice Subform”, UpdateEditableOnRow [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4630]
Please add a new publisher event OnAfterUpdateEditableRows as shown in the picture below in the function UpdateEditableOnRow in page 55

![image](https://user-images.githubusercontent.com/54017538/67459121-1906fa80-f638-11e9-8c3b-553e4495d79f.png)

Please add the corresponding Integration Event In the bottom of the page soruce code
![image](https://user-images.githubusercontent.com/54017538/67459082-01c80d00-f638-11e9-96f1-f41cae05bd24.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
