### ISSUE TITLE
[EventRequest] Page 95 “Sales Quote Subform”, UpdateEditableOnRow [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4631]
Please add a new publisher event OnAfterUpdateEditableRows as shown in the picture below in the function UpdateEditableOnRow in page 95

![image](https://user-images.githubusercontent.com/54017538/67459373-b82bf200-f638-11e9-8e9e-936b4cc25e01.png)

Please add the corresponding Integration Event In the bottom of the page soruce code

![image](https://user-images.githubusercontent.com/54017538/67459341-a2b6c800-f638-11e9-9af0-01cffd8d71ca.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
