### ISSUE TITLE
[EventRequest] Page96 “Sales Cr. Memo Subform”, UpdateEditableOnRow [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4632]
Please add a new publisher event OnAfterUpdateEditableRows as shown in the picture below in the function UpdateEditableOnRow in page 96

![image](https://user-images.githubusercontent.com/54017538/67459479-f88b7000-f638-11e9-8a95-3b2f57635eac.png)

Please add the corresponding Integration Event In the bottom of the page soruce code

![image](https://user-images.githubusercontent.com/54017538/67459488-fd502400-f638-11e9-88d0-49aec75962fc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
