### ISSUE TITLE
[EventRequest] Page 97 “Purchase Quote Subform”, UpdateEditableOnRow [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4633]
Please add a new publisher event OnAfterUpdateEditableRows as shown in the picture below in the function UpdateEditableOnRow in page 97

![image](https://user-images.githubusercontent.com/54017538/67459624-5324cc00-f639-11e9-8430-9ec6b813a206.png)

Please add the corresponding Integration Event In the bottom of the page soruce code

![image](https://user-images.githubusercontent.com/54017538/67459673-6b94e680-f639-11e9-911e-70a18a228131.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
