### ISSUE TITLE
[EventRequest] Page 515 “Item Avail. by Location Lines”,Set [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4635]
Please add a new publisher event OnAfterSet as shown in the picture below in the function Set in page 515

![image](https://user-images.githubusercontent.com/54017538/67460055-57051e00-f63a-11e9-8e2c-44ca60ea38c4.png)

Please add the corresponding Integration Event In the bottom of the page soruce code

![image](https://user-images.githubusercontent.com/54017538/67460066-61bfb300-f63a-11e9-89ba-5eaa1f1d0beb.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
