### ISSUE TITLE
[EventRequest] Page 515 “Item Avail. by Location Lines”, OnAfterSetItemFilter[Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4636]
Please add a new publisher event OnAfterSetItemFilter as shown in the picture below in the function SetItemFilter in page 515

![image](https://user-images.githubusercontent.com/54017538/67460151-9469ab80-f63a-11e9-83ae-e4439350af94.png)

Please add the corresponding Integration Event In the bottom of the page soruce code

![image](https://user-images.githubusercontent.com/54017538/67460188-a64b4e80-f63a-11e9-960f-e2f5a010e484.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
