### ISSUE TITLE
[EventRequest] Page 5827 “Item Statistics”, SetItem [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4637]
Please add a new publisher event OnAfterSetItem as shown in the picture below in the function Set in page 5827

![image](https://user-images.githubusercontent.com/54017538/67460372-1d80e280-f63b-11e9-8b90-0dd155c201de.png)

Please add the corresponding Integration Event In the bottom of the page soruce code

![image](https://user-images.githubusercontent.com/54017538/67460314-f7f3d900-f63a-11e9-949a-1db4010984e8.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
