### ISSUE TITLE
HideValidationDialog in table 5900,5901,5740 function UpdateAllLineDim

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#4638]
Hi,

we implement your changes except on Table 5901 Service Item Line,5900 Service Header, There is no implementation, will it be in the future? also on table 5740 Transfer Header

_Originally posted by @VladimirVeljovic in https://github.com/microsoft/ALAppExtensions/issues/1229#issuecomment-545834959_

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
