### ISSUE TITLE
[EventRequest] Table 5741 - OnBeforeCheckTransHeader

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4639]
Can you add event OnBeforeCheckTransHeader to table 5741 "Transfer Line"?

![image](https://user-images.githubusercontent.com/46031720/67477325-28973b00-f65a-11e9-87b6-cee5f72a6089.png)

![image](https://user-images.githubusercontent.com/46031720/67477348-30ef7600-f65a-11e9-8ea9-4c0352155f23.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
