### ISSUE TITLE
[Event Request] Codeunit 353 Item Availability Forms Mgt – ShowItemAvailFromPurchLine

### ISSUE THREAD

**Issue by Olli-GITHUB** [microsoft/ALAppExtensions#4643]
Dear ALAppExtensions Team,

we would like to request the following code extensions to be added in codeunit 353 Item Availability Forms Mgt – ShowItemAvailFromSalesLine.

Code Change as followed
```
WITH PurchLine DO BEGIN
//Old Code  
//  TESTFIELD(Type,Type::Item);
//  TESTFIELD("No.");
//  Item.RESET;
//  Item.GET("No.");
//  FilterItem(Item,"Location Code","Variant Code","Expected Receipt Date");
// 
//  OnBeforeShowItemAvailFromPurchLine(Item,PurchLine);

// >> New Code
  TESTFIELD(Type,Type::Item);
  TESTFIELD("No.");
  Item.RESET;
  Item.GET("No.");
  FilterItem(Item,"Location Code","Variant Code","Expected Receipt Date");

  OnBeforeShowItemAvailFromPurchLine(Item,PurchLine,IsHandled);
  IF IsHandled THEN
    EXIT;
// >> New Code
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
