### ISSUE TITLE
[Event Request] Table 246 Requisition Line Ending Time OnValidate before SetDueDate

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4645]
We currently do not call the SetDueDate function in the Ending Time OnValidate trigger in the Requisition Line table.

Would like to request an event prior to that to allow bypassing of the call to SetDueDate.

Example:
TESTFIELD(Type,Type::Item);
IF ReqLine.GET("Worksheet Template Name","Journal Batch Name","Line No.") THEN
  PlanningLineMgt.RecalculateWithOptionalModify(Rec,1,FALSE)
ELSE
  CalcStartingDate('');

****NEW EVENT
OnBeforeValidateEndingTimeSetDueDate(var Rec: Record "Requisition Line"; CurrFieldNo: Integer; var IsHandled: Boolean);
if not IsHandled then
****NEW Code end
    IF (CurrFieldNo IN [FIELDNO("Ending Date"),FIELDNO("Ending Date-Time")]) AND 
            (CurrentFieldNo <> FIELDNO("Due Date")) THEN
      SetDueDate;

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
