### ISSUE TITLE
[Event Request] Table 246 Requisition Line Starting Time OnValidate before SetDueDate

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4647]
We currently do not call the SetDueDate function in the Starting Time OnValidate trigger of the Requisition Line table.

Would request that an event be created to allow us to bypass this functionality.

Example:
TESTFIELD(Type,Type::Item);
IF ReqLine.GET("Worksheet Template Name","Journal Batch Name","Line No.") THEN
  PlanningLineMgt.Recalculate(Rec,0)
ELSE
  CalcEndingDate('');

CheckEndingDate(ValidateFields);
***** NEW EVENT
OnBeforeValidateStartingTimeSetDueDate(var Rec: Record "Requisition Line"; var IsHandled: Boolean);
if not IsHandled then
***** NEW CODE END
    SetDueDate;

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
