### ISSUE TITLE
[Upgrade] Error while performing Sync step on thirdparty applicaiton while upgrading Database from BC14 to BC15 Wave2

### ISSUE THREAD

**Issue by Surya-mst** [microsoft/ALAppExtensions#4648]
We are performing data upgrade from BC14 to BC15 Wave2 which includes our third party extensions.

Followed below link to perform the upgrade process.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application

Scenario: One of the BC15 apps has a change in field length which has reduced from 20 to 10 from earlier version.

But while executing Task 11 in the above link (publish, sync and install third party apps). we are able to publish the modified app but we are unable to perform sync step for the app, due to schema error as field length is reduced.

Also included upgrade codeunit in the modified latest app to handle the  changes of field lengths, which will be executing at the next step (NAVApp-DataUpgrade). 

kindly let us know if we are missing any steps.

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
