### ISSUE TITLE
"Library - Cartera Payables" and "Library - Cartera Receivables" extensibility

### ISSUE THREAD

**Issue by amparomoll** [microsoft/ALAppExtensions#4649]
In order to implement adequate tests in Spanish Location, we need to access the functions of codeunits "Library - Cartera Payables" and "Library- Cartera Receivables.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
