### ISSUE TITLE
Expose "InitializeRequest" in Report 1002 "Post Inventory Cost to G/L"

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/ALAppExtensions#465]
Please expose the InitializeRequest function in Report 1002 in order to allow automatic cost posting on a daily (nightly) job.

**Comment by JesperSchulz** [comment]
"InitializeRequest" in Report 1002 "Post Inventory Cost to G/L" was exposed in a recent larger fix pack. The changes are already in preview builds and will ship soon.
