### ISSUE TITLE
New Publisher in Codeunit 7010 "Purch. Price Calc. Mgt."

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#4651]
Hi,

we need one more Publisher in Function FindPurchLineDisc in Codeunit 7010 "Purch. Price Calc. Mgt.":
![image](https://user-images.githubusercontent.com/34675109/67553194-e8dd5b80-f70c-11e9-8460-50bfe904cc0b.png)
![image](https://user-images.githubusercontent.com/34675109/67553231-fa266800-f70c-11e9-807e-cb5a00d1e842.png)
It's equivalent to the Function in Codeunit 7000 "Sales Price Calc. Mgt.".

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
