### ISSUE TITLE
[Event Request] Table 225 - OnBeforePostCodeRecFindFirst

### ISSUE THREAD

**Issue by danooooo1** [microsoft/ALAppExtensions#4652]
Please add a new integration event OnBeforePostCodeRecFindFirst in Table 225 - function ValidatePostCode(...)
```
procedure ValidatePostCode(var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; UseDialog: Boolean)
    var
        PostCodeRec: Record "Post Code";
        PostCodeRec2: Record "Post Code";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidatePostCode(CityTxt, PostCode, CountyTxt, CountryCode, UseDialog, IsHandled);
        if IsHandled then
            exit;

        if PostCode <> '' then begin
            if StrPos(PostCode, '*') = StrLen(PostCode) then
                PostCodeRec.SetFilter(Code, PostCode)
            else
                PostCodeRec.SetRange(Code, PostCode);

            OnBeforePostCodeRecFindFirst(PostCodeRec);

            if not PostCodeRec.FindFirst then
                exit;

            if CountryCode <> '' then begin
                PostCodeRec.SetRange("Country/Region Code", CountryCode);
                if not PostCodeRec.FindFirst then
                    PostCodeRec.SetRange("Country/Region Code");
            end;

            PostCodeRec2.Copy(PostCodeRec);
            if UseDialog and (PostCodeRec2.Next = 1) and GuiAllowed then
                if PAGE.RunModal(PAGE::"Post Codes", PostCodeRec, PostCodeRec.Code) <> ACTION::LookupOK then
                    exit;
            PostCode := PostCodeRec.Code;
            CityTxt := PostCodeRec.City;
            CountryCode := PostCodeRec."Country/Region Code";
            CountyTxt := PostCodeRec.County;
        end;
    end;
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforePostCodeRecFindFirst(var PostCode: Record "Post Code")
begin
end;
```

I need to set filter on field City of Record PostCodeRec, because more cities can have same post code in Slovakia.

**Comment by AlexanderYakunin** [comment]
We already have that
    procedure ValidatePostCode(var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; UseDialog: Boolean)
    var
        PostCodeRec: Record "Post Code";
        PostCodeRec2: Record "Post Code";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidatePostCode(CityTxt, PostCode, CountyTxt, CountryCode, UseDialog, IsHandled);
        if IsHandled then
            exit;

**Comment by danooooo1** [comment]
Hi, how should I set filter on Record PostCodeRec using OnBeforeValidatePostCode? If OnBeforeValidatePostCode had a parameter (VAR PostCodeRec: Record "Post Code", ...) then it's possible to set new filter on it, but this parameter is not included in the procedure. Thanks

**Comment by AlexanderYakunin** [comment]
This change possible, will be done

**Comment by danooooo1** [comment]
I'm not sure if I understand correctly. Does it mean, that adding parameter to procedure is possible? In that case I can absolutely agree with that

**Comment by AlexanderYakunin** [comment]
No, it will be new event for adding filter, as you requested originally

**Comment by danooooo1** [comment]
Thank you very much for that and for your help

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
