### ISSUE TITLE
New Publisher in Codeunit 7010 "Purch. Price Calc. Mgt."

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#4653]
Hi,
we need one more Publisher in Function FindPurchLineLineDisc in Codeunit 7010 "Purch. Price Calc. Mgt." and new Variable:
![image](https://user-images.githubusercontent.com/34675109/67567640-94e16f80-f72a-11e9-8bc2-df471dcbf22d.png)
![image](https://user-images.githubusercontent.com/34675109/67567789-d70ab100-f72a-11e9-8a69-70f04ef1666a.png)
It's equivalent to the Function in Codeunit 7000 "Sales Price Calc. Mgt.".

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
