### ISSUE TITLE
[Event Change] Codeunit 13 Gen. Jnl.-Post Batch - OnBeforeIfCheckBalance

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#4654]
Dear Team,

we would like to have different condition when calling Check Balance(GenTonLine);
Could be this event extended with "IsHandled pattern"?
IsHandled would be then used in IF statement after this event:
```
 if ForceCheckBalance or ("Posting Date" <> LastDate) or GenJnlTemplate."Force Doc. Balance" and
                   (("Document Type" <> LastDocType) or ("Document No." <> LastDocNo))

```
Current  event publisher:
```
  [IntegrationEvent(false, false)]
    local procedure OnBeforeIfCheckBalance(GenJnlTemplate: Record "Gen. Journal Template"; GenJnlLine: Record "Gen. Journal Line"; var LastDocType: Option; var LastDocNo: Code[20]; var LastDate: Date; var CheckIfBalance: Boolean; CommitIsSuppressed: Boolean)
    begin
    end;
```
New event publisher:
```
  [IntegrationEvent(false, false)]
    local procedure OnBeforeIfCheckBalance(GenJnlTemplate: Record "Gen. Journal Template"; GenJnlLine: Record "Gen. Journal Line"; var LastDocType: Option; var LastDocNo: Code[20]; var LastDate: Date; var CheckIfBalance: Boolean; CommitIsSuppressed: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by boych83** [comment]
Ok, thanks.

BR,
Bojan
