### ISSUE TITLE
[Event Request ]Codeunit 6501 "Item Tracking Data Collection" - in function TrackingAvailable

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4655]
Please insert OnBeforeTrackingAvailable(TempTrackingSpecification, Ishandled)
with handler pattern in begin of the procedure TrackingAvailable

[IntegrationEvent(false, false)]
local procedure OnBeforeAssistEditTrackingNo(var TempTrackingSpecification: Record "Tracking Specification" temporary;var IsHandled: Boolean)
begin
end;

**Comment by AlexanderYakunin** [comment]
Please recheck title and content, it does not match our app.

**Comment by MortenRa** [comment]
Updated title to correct COD

**Comment by AlexanderYakunin** [comment]
Thanks, clear now

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
