### ISSUE TITLE
Codeunit 22 Allow Negative Consumption

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/ALAppExtensions#4656]
We have a customer that has a requirement to have production orders be able to consume raw materials to negative inventory. Codeunit 22 has two places that prevent that.
There are two places we had to modify:

// Post Routing Link with negative output quantity
//IF "Output Quantity" >= 0 THEN
IF "Output Quantity" <> 0 THEN
  FlushOperation(ProdOrder,ProdOrderLine);

// Allow posting of negative output without Applies-to Entry
MfgItem.GET(ProdOrderLine."Item No.");
IF ("Applies-to Entry" <> 0) OR (MfgItem."Costing Method" <> MfgItem."Costing Method"::Standard) THEN BEGIN
  TESTFIELD("Applies-to Entry");
  ItemLedgerEntry.GET("Applies-to Entry");
  TESTFIELD("Lot No.",ItemLedgerEntry."Lot No.");
  TESTFIELD("Serial No.",ItemLedgerEntry."Serial No.");
END;

I have attached our modified version of Cod22. I am not actually sure what the event publisher structure should look like.
[COD22.txt](https://github.com/microsoft/ALAppExtensions/files/3772569/COD22.txt)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by kylehardin6** [comment]
Any chance this will make the 15.2 list?

**Comment by kylehardin6** [comment]
Looks like this is included in 15.3 Tasty, tasty new events...
