### ISSUE TITLE
[Event Request] Codeunit 427 ICInboxOutBox function SendSalesDoc , skiptestfield

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4657]
We would Like to be able to suppress this check in the function SendSalesDoc in order to finalize and control when to send the IC document in our intercompany app.

![image](https://user-images.githubusercontent.com/28138717/67583308-a129f480-f74b-11e9-9492-fe7e1f9f2e88.png)

OnBeforeTestField(SkipTestField)

IF NOT SkipTestField Then
 SalesHeader.TestField("Send IC Document");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
