### ISSUE TITLE
[Event Request] Codeunit 427 in function CreateOutboxSalesDocTrans

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4658]
In Procede CreateOutboxSalesDocTrans(SalesHeader: Record "Sales Header"; Rejection: Boolean; Post: Boolean)

Please add event with Handler Pattern in begin of procedure

IsHandled := false;
 OnBeforeCreateOutboxSalesDocTrans(SalesHeader, IsHandled);
 if IsHandled then
   exit;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
