### ISSUE TITLE
Add UpdateTypeText in OnAfterGetCurrRecord trigger in Sales Invoice Subform page

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#4659]
Hi,

Could you please add call to UpdateTypeText in OnAfterGetCurrRecord  in page 47 - Sales Invoice Subform?
You did it for all other subforms for Sales and Purchase documents (Quotes, Orders, Invoice and Memos - 7 pages), only in Sales Invoice Subform is missing. We can override Type in page extensions, but not variable TypeAsText which is used as a page control.

Screenshot from Sales Order Subform:
![image](https://user-images.githubusercontent.com/34686682/67619616-02aa9b80-f7fe-11e9-9825-e4dc06bdcd6e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
