### ISSUE TITLE
Webservice & SoapURL Page 810, Table 9900

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#466]
In Page 810 with Table 9900 Microsoft has a function GetSoapUrl.
It is called at Page 810 to show the SOAPURL 

If you have a COMPANYNAME with a "&" inside the name (which is pretty common in germany) it will interpreted with an "%26". Consuming programs will make a difference between "&" and "%26" and have problems to change that.
Normally the "&" in an URL will be the cut between URL and parameter.
In our case the "&" in a companyname have to be left unchanged. The inherent command "GETURL" changed it always into a "%26"...so we have to change it back into "&".

We need publishers in those functions to do that in future
![image](https://user-images.githubusercontent.com/42136602/49139320-bacf7b80-f2f1-11e8-801c-a94bbaab75dc.png)

Or you have to change the GETURL-command accordingly which would be much more flexible

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix it. We suggest that you open a support case or file a bug in Collaborate. 

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
