### ISSUE TITLE
[Event Requst ] Codeunit 900  Assembly Post in functon PostLines

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4661]
Please add new integration event in procedure PostLines

![image](https://user-images.githubusercontent.com/28138717/67658796-f12ad600-f95a-11e9-81f6-2b91890fc4a1.png)

[IntegrationEvent(false, false)]
    local procedure OnAfterInitQtyToConsume(var AssemblyLine: Record "Assembly Line";QtyToConsumeBase: Decimal)
    begin
    end;

**Comment by AlexanderYakunin** [comment]
We already have event OnAfterInitQtyToConsume(Rec, xRec, CurrFieldNo); in InitQtytoConsume, which have same purpose. Do we need extra event? Should it be OnBeforeAssemblyLineModify() event?

**Comment by MortenRa** [comment]
Yes please add 
OnBeforeAssemblyLineModify(AssemblyLine, QtyToConsumeBase)

That would help us aswell

**Comment by MortenRa** [comment]
Any Updates on this one

**Comment by MortenRa** [comment]
@AlexanderYakunin Any updates on this one, it is still missing

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
