### ISSUE TITLE
[Event Request] Codeunit 5704 - OnBeforeUpdateWithWarehouseShipReceive

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4662]
Please add integration event to OnRun trigger right before TransLine.UpdateWithWarehouseShipReceive;

![image](https://user-images.githubusercontent.com/28138717/67659234-38fe2d00-f95c-11e9-80ec-92386b1f51dd.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateWithWarehouseShipReceive(TransLine);(TransferLine: Record "Transfer Line")
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
