### ISSUE TITLE
[Event Request] Table 18/23/27 - Customer/Vendor/Item - OnAfterSetCrossColumnSearchFilters

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4665]
Dear ALAppExtensions team,
Please see issue #2170. This issue was marked as "ships in future update", but has not been added as far as I could see (checked all recent 14.x, 15.x and 16.x releases).
Could you please add the requested event?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
