### ISSUE TITLE
[Issue] COD221 Resource-Find Price, unable to set return value

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4667]
Can this publisher please be update to allow the return type to be returned?
Current: 
```
    LOCAL PROCEDURE FindResPrice@1() : Boolean;
    VAR
      IsHandled@1000 : Boolean;
    BEGIN
      IsHandled := FALSE;
      OnBeforeFindResPrice(ResPrice,IsHandled);
      IF IsHandled THEN
        EXIT;
```

Suggested:
```
    LOCAL PROCEDURE FindResPrice@1() ReturnBool : Boolean;
    VAR
      IsHandled@1000 : Boolean;
    BEGIN
      IsHandled := FALSE;
      OnBeforeFindResPrice(ResPrice,IsHandled,ReturnBool);
      IF IsHandled THEN
        EXIT(ReturnBool);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
