### ISSUE TITLE
[Event request] COD1002 Job Create-Invoice, OnBeforeTestTransferred

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4670]
Can OnBeforeTestTransferred please be added.
Place to be added:
```
LOCAL PROCEDURE TestTransferred@3(JobPlanningLine@1000 : Record 1003);
VAR
  IsHandled@1100366000 : Boolean;
BEGIN
  //<< DC
  OnBeforeTestTransferred(JobPlanningLine, IsHandled, SalesHeader2);
  IF IsHandled THEN
	EXIT;
  //>> DC
```

Publisher:
```
[Integration(DEFAULT,TRUE)]
PROCEDURE OnBeforeTestTransferred@1100366000(VAR JobPlanningLine@1100366000 : Record 1003;VAR IsHandled@1100366001 : Boolean;VAR SalesHeader2@1100366002 : Record 36);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
