### ISSUE TITLE
[Event Request] - Codeunit 5763 (Whse.-Post Shipment) - CreatePostedShptHeader

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4671]
We are using BC 14.0.35570.

After the CreatePostedShptHeader function is complete (in codeunit 5763), we would like the ability to update the WhseShptHeader parameter.

Something like this:

    WhseComment.SETRANGE("Table Name",WhseComment."Table Name"::"Whse. Shipment");
    WhseComment.SETRANGE(Type,WhseComment.Type::" ");
    WhseComment.SETRANGE("No.",WhseShptHeader."No.");
    IF WhseComment.FIND('-') THEN
      REPEAT
        WhseComment2.INIT;
        WhseComment2 := WhseComment;
        WhseComment2."Table Name" := WhseComment2."Table Name"::"Posted Whse. Shipment";
        WhseComment2."No." := PostedWhseShptHeader."No.";
        WhseComment2.INSERT;
      UNTIL WhseComment.NEXT = 0;
    OnAfterCreatePostedShptHeader(PostedWhseShptHeader,WhseShptHeader) // New

With the event definition:

    LOCAL [IntegrationEvent] OnAfterCreatePostedShptHeader(VAR PostedWhseShptHeader : Record "Posted Whse. Shipment Header";VAR WhseShptHeader : Record "Warehouse Shipment Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
