### ISSUE TITLE
[Event Request] Codeunit 5778 (Whse. Create Pick) - OnRun

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4672]
We are using BC 14.0.35570.

In Codeunit 5778, in OnRun, we would like to take greater control of the WhseCreatePick report is run. Something like this would suffice:

    OnRun(VAR Rec : Record "Whse. Worksheet Line")
    OnBeforeWhseCreatePickRun(Rec, WhseCreatePick, CreatePickHandled); // New
    IF NOT CreatePickHandled then begin // New
        WkshPickLine.COPY(Rec);
        WhseCreatePick.SetWkshPickLine(WkshPickLine);
        WhseCreatePick.RUNMODAL;
    end; // New
    IF WhseCreatePick.GetResultMessage THEN
      AutofillQtyToHandle(Rec);
    CLEAR(WhseCreatePick);

With the event definition:

    OnBeforeWhseCreatePickRun(VAR WkshPickLine : Record "Whse. Worksheet Line",var WhseCreatePick: Report "Create Pick",var Handled)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
