### ISSUE TITLE
[Event Request] Report 5753

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#4673]
This request is in reference to issue #4003.

Please add the parameter **WarehouseRequest: Record "Warehouse Request"** to the following events in **Report 5753**:

- OnSalesLineAfterCreateRcptHeader
- OnSalesLineAfterCreateShptHeader
- OnPurchLineAfterCreateShptHeader
- OnTransLineAfterCreateRcptHeader
- OnAfterProcessDocumentLine

**Comment by AlexanderYakunin** [comment]
We already have this parameter, although your event names does not correspond to existing events. Please recheck.

**Comment by kwettermann** [comment]
The corresponding events are:
- OnSalesLineOnAfterCreateRcptHeader
- OnSalesLineOnAfterCreateShptHeader
- OnPurchaseLineOnAfterCreateRcptHeader
- OnTransferLineOnAfterCreateRcptHeader

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
