### ISSUE TITLE
Codeunit 7010 CalcBestLineDisc request for external

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#4675]
Hi,
we need the function CalcBestLineDisc in Codeunit 7010 "Purch. Price Calc. Mgt." to be external.
![image](https://user-images.githubusercontent.com/34675109/67761992-b00ef080-fa44-11e9-97fa-281ca07134a9.png)
In the equivalent Sales Codeunit 7000 it's already external.

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
