### ISSUE TITLE
[Event Request] COD951 Time Sheet Approval Management, OnBeforeSubmit

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4677]
Can the procedure Submit be updated for an event in the following way please.

Suggestion: 
```
[External]
PROCEDURE Submit@1(VAR TimeSheetLine@1000 : Record 951);
VAR
  isHandled@1100366000 : Boolean;
BEGIN
  //<< DC
  OnBeforeSubmit(TimeSheetLine, isHandled);
  IF isHandled THEN
	EXIT;
  //>> DC
```

Publisher:
```
[Integration(DEFAULT,TRUE)]
PROCEDURE OnBeforeSubmit@1100366000(VAR TimeSheetLine@1100366000 : Record 951;VAR isHandled@1100366001 : Boolean);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
