### ISSUE TITLE
[Event Request] Table 7321 OnBeforeCalcStatusShptLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4678]
we Need a new Event trigger OnBeforeCalcStatusShptLine in table 7321:

[External] CalcStatusShptLine() : Integer
//++++++++++++++++++++++++++++++++++++++
IsHandled = FALSE;
OnBeforeCalcStatusShptLine(VAR WhseShptLine; VAR IsHandled : Boolean; VAR NewStatus : Integer);
IF IsHandled THEN
  EXIT(NewStatus);
//--------------------------------------

IF (Quantity = "Qty. Shipped") OR ("Qty. (Base)" = "Qty. Shipped (Base)") THEN
  EXIT(Status::"Completely Shipped");
IF "Qty. Shipped" > 0 THEN
  EXIT(Status::"Partially Shipped");
IF (Quantity = "Qty. Picked") OR ("Qty. (Base)" = "Qty. Picked (Base)") THEN
  EXIT(Status::"Completely Picked");
IF "Qty. Picked" > 0 THEN
  EXIT(Status::"Partially Picked");
EXIT(Status::" ");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
