### ISSUE TITLE
[Event Request] Codeunit 90 - procedure ReleasePurchDocument

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#4679]
can we have an 
- onbeforeReleasePurchDoc(PurchHeader)
- onafterReleasePurchDoc(PurchHeader)

similar to the events in CU80 - procedure ReleaseSalesDocument

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
