### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by Hornsyld** [Microsoft/ALAppExtensions#468]
Suggestion/Enhancement for better error messages to the users of NAV/Business Central.

I suggest that on errors caused by setup there will be a hyperlink to the page where the missing setup is needed. It can be setup like, VAT posting grp, customer posting grp, vendor posting grp, currency ect.

Below you will see example on what error you get when you try posting with a Gen. Journal with currency that have not been setup. The error message is really bad - so in this instance a new user to NAV/Business Central would get totally lost. I looked at some of the posting grps before checking the currency page, but this would have been easier if there was a hyperlink of some kind to the page where the error is. I have attached a picture of how it could look.

Can the link be to the page where the field needs to be entered if it makes sence. So in this example you could also create a G/L Account with the No. that the error gives. I would make sense to link to the currency page and not the Chart of accounts.

![curreny error](https://user-images.githubusercontent.com/6792253/49155310-eca90800-f31a-11e8-9611-9d3c48e41fcd.png)

![curreny error after](https://user-images.githubusercontent.com/6792253/49156655-20396180-f31e-11e8-8d70-dec6c0d8f8de.png)

Looking forward to hear your toughts.

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
