### ISSUE TITLE
[Event request] Table 7321, 7326 and 7317 OnAutoFillQtyToHandle

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4680]
we Need a new Event trigger OnAutoFillQtyToHandle in table 7321 and 7326 before modifying the relevant record:

table 7321:
[External] AutofillQtyToHandle(VAR WhseShptLine : Record "Warehouse Shipment Line")
WITH WhseShptLine DO BEGIN
  NotEnough := FALSE;
  SetHideValidationDialog(TRUE);
  IF FIND('-') THEN
    REPEAT
      GetLocation("Location Code");
      IF Location."Require Pick" THEN
        VALIDATE("Qty. to Ship (Base)","Qty. Picked (Base)" - "Qty. Shipped (Base)")
      ELSE
        VALIDATE("Qty. to Ship (Base)","Qty. Outstanding (Base)");
      //+++++++++++++++++++++++++++++++++++++++
      OnAutoFillQtyToHandle(VAR WhseShptLine);
      //---------------------------------------
      MODIFY;
      IF NOT NotEnough THEN
        IF ("Qty. to Ship (Base)" < "Qty. Outstanding (Base)") AND
           ("Shipping Advice" = "Shipping Advice"::Complete)
        THEN
          NotEnough := TRUE;
    UNTIL NEXT = 0;
  SetHideValidationDialog(FALSE);
  IF NotEnough THEN
    MESSAGE(Text005);
END;

Table 7326:
[External] AutofillQtyToHandle(VAR WhseWkshLine : Record "Whse. Worksheet Line")
WITH WhseWkshLine DO BEGIN
  NotEnough := FALSE;
  SetHideValidationDialog(TRUE);
  LOCKTABLE;
  IF FIND('-') THEN
    REPEAT
      VALIDATE("Qty. to Handle","Qty. Outstanding");
      //+++++++++++++++++++++++++++++++++++++++
      OnAutoFillQtyToHandle(VAR WhseWkshLine);
      //---------------------------------------
      MODIFY;
      IF NOT NotEnough THEN
        IF "Qty. to Handle" < "Qty. Outstanding" THEN
          NotEnough := TRUE;
    UNTIL NEXT = 0;
  SetHideValidationDialog(FALSE);
  IF NotEnough THEN
    MESSAGE(Text011);
END;

OnAfterAutofillQtyToHandle(WhseWkshLine);

Table 7317:
[External] AutofillQtyToReceive(VAR WhseReceiptLine : Record "Warehouse Receipt Line")
WITH WhseReceiptLine DO BEGIN
  IF FIND('-') THEN
    REPEAT
      VALIDATE("Qty. to Receive","Qty. Outstanding");
      //+++++++++++++++++++++++++++++++++++++++
      OnAutoFillQtyToReceive(VAR WhseReceiptLine);
      //---------------------------------------
      MODIFY;
    UNTIL NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
