### ISSUE TITLE
codeunit 5931 Resource Skill Mgt - make local external - AssignRelationWithUpdate

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4681]
Thanks!

![image](https://user-images.githubusercontent.com/49729094/67783564-cfa41a00-fa40-11e9-943a-9e38b2d16fca.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
