### ISSUE TITLE
Page 42 Sales Order - make local external - Post

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4682]
Thanks

![image](https://user-images.githubusercontent.com/49729094/67784230-d3846c00-fa41-11e9-9e44-12019f4ef7b9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
