### ISSUE TITLE
Event Request Codeunit 5987 Serv-Posting Journals Mgt.

### ISSUE THREAD

**Issue by brijeshkarnatak** [microsoft/ALAppExtensions#4683]
The Event OnBeforeTransferValuesToJobJnlLine is missing on function PostJobJnlLine in codeunit 5987 Serv-Posting Journals Mgt.

**Comment by AlexanderYakunin** [comment]
We already have OnAfterTransferValuesToJobJnlLine event for transfer fields, why do you need OnBefore transfer event?

**Comment by brijeshkarnatak** [comment]
In case if we wish to modify the service line temporarily before validating the Job Journal Line = "No."

**Comment by AlexanderYakunin** [comment]
We do not use this pattern, why do you need to modify Service Line temporarily, if you can simply update Job Journal Line using existing OnAfter event?
