### ISSUE TITLE
COD1003 Job Task-Indent, OnBeforeModifyJT

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4685]
Can we please have this event in the following way
```
[External]
PROCEDURE Indent@1(JobNo@1000 : Code[20]);
BEGIN
  Window.OPEN(Text004);
  JT.SETRANGE("Job No.",JobNo);
  WITH JT DO
	IF FIND('-') THEN
	  REPEAT
		Window.UPDATE(1,"Job Task No.");

		IF "Job Task Type" = "Job Task Type"::"End-Total" THEN BEGIN
		  IF i < 1 THEN
			ERROR(
			  Text005,
			  "Job Task No.");
		  Totaling := JTNo[i] + '..' + "Job Task No.";
		  i := i - 1;
		END;

		Indentation := i;
		//<< DC
		OnBeforeModifyJT(JT, JobNo);
		//>> DC
		MODIFY;
```
Publisher:
```
[Integration(DEFAULT,TRUE)]
PROCEDURE OnBeforeModifyJT@1100366000(VAR JT@1100366000 : Record 1001;VAR JobNo@1100366001 : Code[20]);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
