### ISSUE TITLE
[Event Request] CodeUnit 228 OnAfterCalcSalesDiscount and OnAfterCalcPurchDiscount

### ISSUE THREAD

**Issue by FSplett** [microsoft/ALAppExtensions#4687]
Please add a new Event Triggers OnAfterCalcSalesDiscount and OnAfterCalcPurchDiscount in CodeUnit 228.

LOCAL CalcSalesDisc(VAR SalesHeader : Record "Sales Header")
SalesSetup.GET;
IF SalesSetup."Calc. Inv. Discount" THEN BEGIN
  SalesLine.RESET;
  SalesLine.SETRANGE("Document Type",SalesHeader."Document Type");
  SalesLine.SETRANGE("Document No.",SalesHeader."No.");
  SalesLine.FINDFIRST;
  OnCalcSalesDiscOnBeforeRun(SalesHeader,SalesLine);
  CODEUNIT.RUN(CODEUNIT::"Sales-Calc. Discount",SalesLine);
  SalesHeader.GET(SalesHeader."Document Type",SalesHeader."No.");
  COMMIT;
END;
//+++++++++++++++++++++++++++
OnAfterCalcSalesDiscount(VAR SalesHeader; SalesLine);
//----------------------------------------------

LOCAL CalcPurchDisc(VAR PurchHeader : Record "Purchase Header")
PurchSetup.GET;
IF PurchSetup."Calc. Inv. Discount" THEN BEGIN
  PurchLine.RESET;
  PurchLine.SETRANGE("Document Type",PurchHeader."Document Type");
  PurchLine.SETRANGE("Document No.",PurchHeader."No.");
  PurchLine.FINDFIRST;
  OnCalcPurchDiscOnBeforeRun(PurchHeader,PurchLine);
  CODEUNIT.RUN(CODEUNIT::"Purch.-Calc.Discount",PurchLine);
  PurchHeader.GET(PurchHeader."Document Type",PurchHeader."No.");
  COMMIT;
END;
//+++++++++++++++++++++++++++
OnAfterCalcPurchDiscount(VAR PurchHeader; PurchLine);
//----------------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
