### ISSUE TITLE
[Event Request] CodeUnit 80 & CodeUnit 90 OnAfterSetPostingFlags

### ISSUE THREAD

**Issue by FSplett** [microsoft/ALAppExtensions#4688]
Please add the Event Trigger OnAfterSetPostingFlags in CodeUnits 80 and 90.

**CodeUnit 80:**
LOCAL CheckAndUpdate(VAR SalesHeader : Record "Sales Header")
WITH SalesHeader DO BEGIN
  // Check
  ErrorMessageMgt.PushContext(RECORDID,0,CheckSalesHeaderMsg);
  CheckMandatoryHeaderFields(SalesHeader);
  IF GenJnlCheckLine.IsDateNotAllowed("Posting Date",SetupRecID) THEN
    ErrorMessageMgt.LogContextFieldError(
      FIELDNO("Posting Date"),STRSUBSTNO(PostingDateNotAllowedErr,FIELDCAPTION("Posting Date")),
      SetupRecID,ErrorMessageMgt.GetFieldNo(SetupRecID.TABLENO,GLSetup.FIELDNAME("Allow Posting From")),
      ErrorMessageMgt.GetHelpCodeForAllowedPostingDate);

  SetPostingFlags(SalesHeader);
  //+++++++++++++++++++++++++++++++++++++
  OnAfterSetPostingFlags(VAR SalesHeader, VAR TempSalesLineGlobal);
  //------------------------------------------------------------
  IF NOT HideProgressWindow THEN
    InitProgressWindow(SalesHeader);

-----

**CodeUnit 90:**
WITH PurchHeader DO BEGIN
  // Check
  ErrorMessageMgt.PushContext(RECORDID,0,CheckPurchHeaderMsg);
  CheckMandatoryHeaderFields(PurchHeader);
  IF GenJnlCheckLine.IsDateNotAllowed("Posting Date",SetupRecID) THEN
    ErrorMessageMgt.LogContextFieldError(
      FIELDNO("Posting Date"),STRSUBSTNO(PostingDateNotAllowedErr,FIELDCAPTION("Posting Date")),
      SetupRecID,ErrorMessageMgt.GetFieldNo(SetupRecID.TABLENO,GLSetup.FIELDNAME("Allow Posting From")),
      ErrorMessageMgt.GetHelpCodeForAllowedPostingDate);

  SetPostingFlags(PurchHeader);
  //+++++++++++++++++++++++++++++++++++++
  OnAfterSetPostingFlags(VAR PurchHeader, VAR TempPurchLineGlobal);
  //------------------------------------------------------------
  InitProgressWindow(PurchHeader);

  InvtPickPutaway := "Posting from Whse. Ref." <> 0;
  "Posting from Whse. Ref." := 0;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
