### ISSUE TITLE
event request - Table Segment Line - procedure StartWizard

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#4692]
in table Segment Line there is procedure "StartWizard" 
at the beginning there is an event:
OnBeforeStartWizard(Rec);

Could this event be extended with the isHandled principle? 
like this:

isHandled := false;
OnBeforeStartWizard(Rec,isHandled);
if isHandled then exit;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
