### ISSUE TITLE
[Event Request] COD5900 ServOrderManagement, OnBeforeUpdateResponseDateTime

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4693]
Can we please get OnBeforeUpdateResponseDateTime added in the following way
```
[External]
PROCEDURE UpdateResponseDateTime@7(VAR ServItemLine@1000 : Record 5901;Deleting@1005 : Boolean);
VAR
  ServItemLine2@1006 : Record 5901;
  ServHeader@1007 : Record 5900;
  NewResponseDate@1001 : Date;
  NewResponseTime@1002 : Time;
  IsHandled@1100366000 : Boolean;
BEGIN
  //<< DC
  OnBeforeUpdateResponseDateTime(ServItemLine, Deleting, IsHandled);
  IF IsHandled THEN
	EXIT;
  //>> DC
```
Publisher:
```
[Integration(DEFAULT,TRUE)]
PROCEDURE OnBeforeUpdateResponseDateTime@1100366000(VAR ServItemLine@1100366000 : Record 5901;VAR Deleting@1100366001 : Boolean;VAR IsHandled@1100366002 : Boolean);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
