### ISSUE TITLE
Report 594 Get Item Ledger Entries - How to exclude records?

### ISSUE THREAD

**Issue by josejggil** [microsoft/ALAppExtensions#4694]
Hi.

We are trying to do with extension what is shown in the following image

![image](https://user-images.githubusercontent.com/47104041/67865246-43b8ed80-fb27-11e9-9c3b-7a5a9e445ae3.png)

With existing events it is not possible. Any ideas?

A greeting

**Comment by AlexanderYakunin** [comment]
You can request needed event, but not for 14.X version. We only do events for 15.X.

**Comment by josejggil** [comment]
Ok, it could be interesting
Thanks
