### ISSUE TITLE
[Event Request] - Codeunit 5057 - function InsertNewContact

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4696]
We are using BC 14.0.35570.

This is kind of similar to issue 4140 (https://github.com/microsoft/ALAppExtensions/issues/4140)

The client we are upgrading has a different number series for each kind of contact (including vendor).

Adding an event to codeunit 5057 - Function InsertNewContact would allow this:

    [External] InsertNewContact(VAR Vend : Record Vendor;LocalCall : Boolean)
    IF NOT LocalCall THEN BEGIN
      RMSetup.GET;
      RMSetup.TESTFIELD("Bus. Rel. Code for Vendors");
    END;
    
    IF ContBusRel.UpdateEmptyNoForContact(Vend."No.",Vend."Primary Contact No.",ContBusRel."Link to Table"::Vendor) THEN
      EXIT;
    
    WITH Cont DO BEGIN
      INIT;
      TRANSFERFIELDS(Vend);
      OnAfterTransferFieldsFromVendToCont(Cont,Vend);
      VALIDATE(Name);
      VALIDATE("E-Mail");
      OnBeforeAssignNumber(Cont, AssignNumberHandled); // NEW
      IF NOT AssignNumberHandled then begin // NEW
    	  "No." := '';
    	  "No. Series" := '';
    	  RMSetup.TESTFIELD("Contact Nos.");
    	  NoSeriesMgt.InitSeries(RMSetup."Contact Nos.",'',0D,"No.","No. Series");
      end; // NEW
      Type := Type::Company;
      TypeChange;
      SetSkipDefault;
      OnBeforeContactInsert(Cont,Vend);
      INSERT(TRUE);
    END;

With an event definition:

    LOCAL [IntegrationEvent] OnBeforeAssignNumber(VAR Contact : Record Contact; VAR AssignNumberHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
