### ISSUE TITLE
[Event Request] DACH Report 11517 OnBeforeUpdateTempItemStatisticsBuffer

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4697]
please add a new Event trigger OnBeforeUpdateTempItemStatisticsBuffer in DACH Report 11517 

CalcInventoryValue(ItemLedgEntry : Record "Item Ledger Entry")
WITH ValueEntry2 DO BEGIN
  SETCURRENTKEY("Item Ledger Entry No.");
  SETRANGE("Item Ledger Entry No.",ItemLedgEntry."Entry No.");
  SETRANGE("Posting Date",0D,StatusDate);

  IF FINDLAST THEN BEGIN
    CALCSUMS("Cost Amount (Actual)","Cost Amount (Expected)","Invoiced Quantity","Cost Posted to G/L");

    BufferRecExists := TempItemStatisticsBuffer.GET("Inventory Posting Group");
    IF NOT BufferRecExists THEN BEGIN
      TempItemStatisticsBuffer.INIT;
      TempItemStatisticsBuffer.Code := "Inventory Posting Group";
    END;

    TempItemStatisticsBuffer."Inv. Valuation Actual" += "Cost Amount (Actual)";
    TempItemStatisticsBuffer."Inv. Posted to GL" += "Cost Posted to G/L";
    TempItemStatisticsBuffer."Inv. Valuation Exp." += "Cost Amount (Expected)";
    ValueEntry."Cost Amount (Actual)" += "Cost Amount (Actual)";
    ValueEntry."Cost Amount (Expected)" += "Cost Amount (Expected)";
    ValueEntry."Cost Posted to G/L" += "Cost Posted to G/L";
    ValueEntry."Invoiced Quantity" += "Invoiced Quantity";
    //+++++++++++++++++++++++++++++++++++++++++
    OnBeforeUpdateTempItemStatisticsBuffer(VAR TempItemStatisticsBuffer;VAR ValueEntry;ValueEntry2;ItemLedgEntry);
    //-----------------------------------------

    IF BufferRecExists THEN
      TempItemStatisticsBuffer.MODIFY
    ELSE
      TempItemStatisticsBuffer.INSERT;
  END;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
