### ISSUE TITLE
[EventRequest] Table 27 “Item”, FindItemVend [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4698]
Please add a new publisher event OnAfterSetFilterBeforeFindItemVend in Table 27 on function FindItemVend and call it at the start of the function.

![image](https://user-images.githubusercontent.com/54017538/67935744-ce9ef400-fbca-11e9-9a0d-ff9029b9678b.png)

Please add the corresponding Integration Event In the bottom of the table

![image](https://user-images.githubusercontent.com/54017538/67935769-d9598900-fbca-11e9-8c0d-0cea17016de9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
