### ISSUE TITLE
[Event Request] COD951 Time Sheet Approval Management, OnBeforeApprove

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4701]
Can we please have OnBeforeApprove in the following way
```
[External]
PROCEDURE Approve@12(VAR TimeSheetLine@1000 : Record 951);
VAR
  isHandled@1100366000 : Boolean;
BEGIN
  //<< DC
  OnBeforeApprove(TimeSheetLine, isHandled);
  IF isHandled THEN
	EXIT;
  //>> DC
```
Publisher:
```
[Integration(DEFAULT,TRUE)]
PROCEDURE OnBeforeApprove@1100366002(VAR TimeSheetLine@1100366000 : Record 951;VAR IsHandled@1100366001 : Boolean);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
