### ISSUE TITLE
[Event Request] COD5930 ServAllocationManagement, OnBeforeCancelAllocation

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4702]
Can we please have OnBeforeCancelAllocation added in the following way
```
[External]
PROCEDURE CancelAllocation@3(VAR ServOrderAlloc@1000 : Record 5950);
VAR
  ServHeader@1001 : Record 5900;
  ServItemLine@1002 : Record 5901;
  RepairStatus@1003 : Record 5927;
  RepairStatus2@1004 : Record 5927;
  AddReasonCodeCancelation@1005 : Page 6002;
  ReasonCode@1006 : Code[10];
  RepairStatusCode@1007 : Code[10];
  IsHandled@1100366000 : Boolean;
BEGIN
  //<< DC
  OnBeforeCancelAllocation(ServOrderAlloc, IsHandled);
  IF IsHandled THEN
	EXIT;
  //>> DC
```
Publisher:
```
[Integration(DEFAULT,TRUE)]
PROCEDURE OnBeforeCancelAllocation@1100366000(VAR ServOrderAlloc@1100366000 : Record 5950;VAR IsHandled@1100366001 : Boolean);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
