### ISSUE TITLE
[Event Request] Table 5740 OnAfterGetTransferRoute

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4704]
please add a new Event "OnAfterGetTransferRoute" in table 5740 and two calls to this new event

Transfer-from Code - OnValidate()
TestStatusOpen;
...
        TransferRoute.GetTransferRoute(
          "Transfer-from Code","Transfer-to Code","In-Transit Code",
          "Shipping Agent Code","Shipping Agent Service Code");
        //++++++++++++++++++++++++++++++++++++++++
        OnAfterGetTransferRoute(VAR rec : "Trans Header";TransferRoute);
        //----------------------------------------
        TransferRoute.GetShippingTime(

Transfer-to Code - OnValidate()
TestStatusOpen;
...
        TransferRoute.GetTransferRoute(
          "Transfer-from Code","Transfer-to Code","In-Transit Code",
          "Shipping Agent Code","Shipping Agent Service Code");
        //++++++++++++++++++++++++++++++++++++++++
        OnAfterGetTransferRoute(VAR rec : "Trans Header";TransferRoute);
        //----------------------------------------
        TransferRoute.GetShippingTime(

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
