### ISSUE TITLE
[Event Request] COD5941 ContractDiscount-Find, OnBeforeFindContractDiscount

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4705]
Can we please have the OnBeforeFindContractDiscount, added to the OnRun function in the following way:
```
OnRun=VAR
		IsHandled@1100366000 : Boolean;
	  BEGIN
		//<< DC
		OnBeforeFindContractDiscount(Rec, IsHandled);
		IF IsHandled THEN
		  EXIT;
		//>> DC
```
Publisher:
```
[Integration(DEFAULT,TRUE)]
PROCEDURE OnBeforeFindContractDiscount@1100366000(VAR Rec@1100366000 : Record 5972;VAR IsHandled@1100366001 : Boolean);
BEGIN
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
