### ISSUE TITLE
[Event Request] Codeunit 1032 - Job Planning Line-Reserve - Additional parameter in OnBeforeCheckReservedQtyBase

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4707]
Dear ALAppExtensions team,

Through this issue we would like to request an additional parameter for event publisher `OnBeforeCheckReservedQtyBase` to be added to Codeunit 1032 Job Planning Line-Reserve resulting in the following signature:
```
LOCAL [IntegrationEvent] OnBeforeCheckQuantityToReserve(JobPlanningLine : Record "Job Planning Line";QtyBase : Decimal;VAR IsHandled : Boolean)
```
so, adding decimal parameter `QtyBase`.

which would be called as follows from `CheckReservedQtyBase`:
```pascal
    local procedure CheckReservedQtyBase(JobPlanningLine: Record "Job Planning Line"; QuantityBase: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        // OnBeforeCheckReservedQtyBase(JobPlanningLine, IsHandled); << OLD
        OnBeforeCheckReservedQtyBase(JobPlanningLine,QuantityBase,IsHandled); // << NEW
        if IsHandled then
            exit;

        if Abs(JobPlanningLine."Remaining Qty. (Base)") < Abs(JobPlanningLine."Reserved Qty. (Base)") + QuantityBase then
            Error(
              Text000,
              Abs(JobPlanningLine."Remaining Qty. (Base)") - Abs(JobPlanningLine."Reserved Qty. (Base)"));
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
