### ISSUE TITLE
[Event Request] Codeunit 5981 - Service-Post (Yes/No) - OnBeforePostDocument + OnBeforePostDocumentWithLines

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4708]
Dear ALAppExtensions team,

Please see issue #1363. It was flagged as 'ships-in-future-update', but it seems like the requested event publishers have not been added. (Seems like there was a typo though: 5980 should have been 5981)
Could you please add the requested event publishers?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
