### ISSUE TITLE
[Event Request] Codeunit 6620 - Copy Document Mgt. - OnAfterInitFromSalesLine

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4709]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterInitFromSalesLine` to be added to Codeunit 6620 Copy Document Mgt. with the following signature:
```
LOCAL [IntegrationEvent] OnAfterInitFromSalesLine(VAR FromSalesLine: Record "Sales Line"; VAR FromSalesLineBuf: Record "Sales Line")
```
with **VAR** parameters `FromSalesLine` and `FromSalesLineBuf`.

which would be called as follows from `InitFromSalesLine`:
```pascal

    local procedure InitFromSalesLine(var FromSalesLine2: Record "Sales Line"; var FromSalesLineBuf: Record "Sales Line")
    begin
        // Empty buffer fields
        FromSalesLine2 := FromSalesLineBuf;
        FromSalesLine2."Shipment No." := '';
        FromSalesLine2."Shipment Line No." := 0;
        FromSalesLine2."Return Receipt No." := '';
        FromSalesLine2."Return Receipt Line No." := 0;
        OnAfterInitFromSalesLine2(FromSalesLine2, FromSalesLineBuf); // << NEW
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
