### ISSUE TITLE
[Event Request] Codeunit 6620 - Copy Document Mgt. - OnAfterCleanSpecialOrderDropShipmentInSalesLine/OnAfterCleanSpecialOrderDropShipmentInPurchLine

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4710]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterCleanSpecialOrderDropShipmentInSalesLine/OnAfterCleanSpecialOrderDropShipmentInPurchLine` to be added to Codeunit 6620 Copy Document Mgt. with the following signature:
```
OnAfterCleanSpecialOrderDropShipmentInSalesLine(VAR SalesLine: Record "Sales Line");
```
with **VAR** parameter `SalesLine/PurchaseLine`.

which would be called as follows from `CleanSpecialOrderDropShipmentInSalesLine/CleanSpecialOrderDropShipmentInPurchLine`:
```pascal
    local procedure CleanSpecialOrderDropShipmentInSalesLine(var SalesLine: Record "Sales Line")
    begin
        SalesLine."Purchase Order No." := '';
        SalesLine."Purch. Order Line No." := 0;
        SalesLine."Special Order Purchase No." := '';
        SalesLine."Special Order Purch. Line No." := 0;
        OnAfterCleanSpecialOrderDropShipmentInSalesLine(SalesLine);
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
