### ISSUE TITLE
[Event Request] Table 246 Requisition Line - OnBeforeGetDirectCost and OnAfterCreateDimTableIDs

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4712]
Both of events use FieldNo as parameters which in al Extension is a Function.  Is it possible to use a different name other than FieldNo?    Thanks.  

![image](https://user-images.githubusercontent.com/49729094/67968512-e92e9880-fbdd-11e9-8644-7daa7b3b425c.png)

![image](https://user-images.githubusercontent.com/49729094/67968598-1713dd00-fbde-11e9-88cf-a2c9e218c1f5.png)

![image](https://user-images.githubusercontent.com/49729094/67968986-b2a54d80-fbde-11e9-9be9-a8b22d5594e8.png)

**Comment by AlexanderYakunin** [comment]
This is because you use WITH ReqLine, please do not use it and you can compile. It will be nice to change name for this parameters but this is breaking change for subscribers.
