### ISSUE TITLE
[Event Request] Table 36 (Sales Header) - "Bill-to Customer No." - OnValidate

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4713]
We are using BC 14.0.35570.

We would like to run additional code when in Table 36 the "Bill-to Customer No." field is changed and confirmed. To this end, something like this would do the trick:

    Bill-to Customer No. - OnValidate()
    TestStatusOpen;
    BilltoCustomerNoChanged := xRec."Bill-to Customer No." <> "Bill-to Customer No.";
    IF BilltoCustomerNoChanged THEN
      IF xRec."Bill-to Customer No." = '' THEN
        InitRecord
      ELSE BEGIN
        IF GetHideValidationDialog OR NOT GUIALLOWED THEN
          Confirmed := TRUE
        ELSE
          Confirmed := CONFIRM(ConfirmChangeQst,FALSE,BillToCustomerTxt);
        IF Confirmed THEN BEGIN
          OnAfterBilltoCustChangeConfirmed(Rec); // New
          SalesLine.SETRANGE("Document Type","Document Type");
          SalesLine.SETRANGE("Document No.","No.");
    
          CheckShipmentInfo(SalesLine,TRUE);
          CheckPrepmtInfo(SalesLine);
          CheckReturnInfo(SalesLine,TRUE);

          SalesLine.RESET;
        END ELSE
          "Bill-to Customer No." := xRec."Bill-to Customer No.";
      END;

With an event definition:

    LOCAL [IntegrationEvent] OnAfterBilltoCustChangeConfirmed(VAR SalesHeader : Record "Sales Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Mullsey** [comment]
Are you able to give me an idea of when this will be available? This (and a lot of other requests I have made) is holding up an upgrade, and we would like to give the client an idea of when we will be able to implment their old modifications in BC.
