### ISSUE TITLE
[Event Request] - Codeunit 312 (Cust-Check Cr. Limit) - SalesHeaderCheck

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4714]
We are using BC 14.0.35570.

We would like to be able to suppress the credit check for sales headers under certain circumstances, and to run extra code when a check is done and the customer is over their credit limit.

Something like this would do the trick:

    [External] SalesHeaderCheck(VAR SalesHeader : Record "Sales Header") CreditLimitExceeded : Boolean
    IF NOT GUIALLOWED THEN
      EXIT;
    OnBeforeSalesHeaderCheck(SalesHeader, IsHandled); // New
    IF IsHandled then // New
      EXIT; // New

    OnNewCheckRemoveCustomerNotifications(SalesHeader.RECORDID,TRUE);

    IF NOT CustCheckCreditLimit.SalesHeaderShowWarningAndGetCause(SalesHeader,AdditionalContextId) THEN
      SalesHeader.OnCustomerCreditLimitNotExceeded
    ELSE
      OnSalesHeaderCheckLimitExceeded(SalesHeader); // New
      IF InstructionMgt.IsEnabled(GetInstructionType(FORMAT(SalesHeader."Document Type"),SalesHeader."No.")) THEN BEGIN
        CreditLimitExceeded := TRUE;

        CreateAndSendNotification(SalesHeader.RECORDID,AdditionalContextId,'');
        SalesHeader.OnCustomerCreditLimitExceeded;
      END;

With the event definitions:

    LOCAL [IntegrationEvent] OnBeforeSalesHeaderCheck(VAR SalesHeader : Record "Sales Header", VAR IsHandled: Boolean)

    LOCAL [IntegrationEvent] OnSalesHeaderCheckLimitExceeded(VAR SalesHeader : Record "Sales Header");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Mullsey** [comment]
I'm looking at the latest BC15, and I can see that half of this has been implemented - thanks for that.

But the event OnSalesHeaderCheckLimitExceeded (or an equivalent) has not been added. Is this likely to happen?

**Comment by NKarolak** [comment]
Usually Microsoft does not reply nor correct events based on already closed issues.
In order to get it fixed, you will need to create a new issue.
