### ISSUE TITLE
[Event Request] - Table 5050 (Contact) - CreateVendor

### ISSUE THREAD

**Issue by Mullsey** [microsoft/ALAppExtensions#4715]
We are using BC 14.0.35570.

Before a vendor is inserted, we would like to run some code (Setting the primary key of the vendor from a field on the contact).

There is an event before the vendoris inserted, but unfortunately they dont include the contact, so we cant do what we want.

If the code could be modified to include the current contact, that would solve you problem. Like this:

    Vend.SetInsertFromContact(TRUE);
    //OnBeforeVendorInsert(Vend);
    OnBeforeVendorInsert(Vend,Rec); // New
    Vend.INSERT(TRUE);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
