### ISSUE TITLE
[Event Request] Table 5050 - Contact - OnBeforeBankAccountInsert

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4716]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeBankAccountInsert` to be added to Table 5050 Contact with the following signature:
```
LOCAL [IntegrationEvent] OnBeforeBankAccountInsert(VAR BankAccount : Record "Bank Account")
```
with **VAR** parameter `BankAccount`.

which would be called as follows from `CreateBankAccount`:
```pascal
[External] CreateBankAccount()
TESTFIELD("Company No.");
RMSetup.GET;
RMSetup.TESTFIELD("Bus. Rel. Code for Bank Accs.");

CLEAR(BankAcc);
BankAcc.SetInsertFromContact(TRUE);
OnBeforeBankAccountInsert(BankAcc); // << NEW
BankAcc.INSERT(TRUE);
BankAcc.SetInsertFromContact(FALSE);
...
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
