### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeDeleteSalesLines

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4717]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeDeleteSalesLines` to be added to Table 36 Sales Header with the following signature:
```
    [Integration]
    LOCAL PROCEDURE OnBeforeDeleteSalesLines(VAR SalesLine: Record 37);
    BEGIN
    END;
```
with **VAR** parameter `SalesLine`.

which would be called as follows from `DeleteSalesLines`:
```pascal
    LOCAL PROCEDURE DeleteSalesLines();
    VAR
      ReservMgt: Codeunit 99000845;
    BEGIN
      OnBeforeDeleteSalesLines(SalesLine); // << NEW
      IF SalesLine.FINDSET THEN BEGIN
        ReservMgt.DeleteDocumentReservation(DATABASE::"Sales Line","Document Type","No.",GetHideValidationDialog);
        REPEAT
          SalesLine.SuspendStatusCheck(TRUE);
          SalesLine.DELETE(TRUE);
        UNTIL SalesLine.NEXT = 0;
      END;
    END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
