### ISSUE TITLE
[Function Expose] Page 55/96/.. - Purch. Invoice Subform/Sales Cr. Memo Subform - GetReceipt/GetReturnReceipt

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#4718]
Dear ALAppExtensions team,

Through this issue we would like to request procedures `GetReceipt` and `GetReturnReceipt` to be exposed, just like `GetShipment` in Page 47.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
