### ISSUE TITLE
PAG950 Time Sheet, Submit/Reopen

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#4719]
Can onBefore events with isHandled be added to the Submit and Reopen local functions please, our use case is adding a parameter to the Process function which it calls:
```
LOCAL PROCEDURE Submit@2();
VAR
  Action@1001 : 'Submit Selected,Submit All,Reopen Selected,Reopen All';
  ActionType@1002 : 'Submit,Reopen';
BEGIN
  CASE ShowDialog(ActionType::Submit) OF
	//<< DC
	1:
	  Process(Action::"Submit All",TRUE);
	2:
	  Process(Action::"Submit All",FALSE);
	3:
	  Process(Action::"Submit Selected",FALSE);
	//>> DC
  END;
END;
```

**Comment by AlexanderYakunin** [comment]
Can you be more detailed and specify events?

**Comment by Nameyka-DC** [comment]
Apologies for the vagueness of my original statement. Currently trying to override the functionality behind Submit and Reopen. In al we have disabled to current Submit/Reopen page actions and recreated them to use our new function. However, it would be better suited to have events in order to override these functions. Not sure whether the best place for this would be the page action, or the actual functions. The events for the page actions are: 

Reopen:
```
OnAction=VAR
		 IsHandled@1100366000 : Boolean;
	   BEGIN
		 //<< DC
		 OnBeforeReopenAction(Rec, IsHandled);
		 IF IsHandled THEN
		   EXIT;
		 //>> DC

		 Reopen;
	   END;
```

Submit: 
```
OnAction=VAR
		 IsHandled@1100366000 : Boolean;
	   BEGIN
		 //<< DC
		 OnBeforeSubmitAction(Rec, IsHandled);
		 IF IsHandled THEN
		   EXIT;
		 //>> DC

		 Submit;
	   END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
