### ISSUE TITLE
[Application Refactoring] - Page 1290/1294

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#4725]
Hello,

we are using action "Import Bank Transactions" from both pages (list and worksheet).
Both actions do not appear to behave the same in the "Match Bank Payments" part of implementation which is done when bank transactions are imported.

We've added additional fields on table 274 "Bank Account. Reconciliation Line" regarding our legislation and those fields need to be populated and they are depending on value of "Account no." field.

When action is called from list page(1294),  CU 1254 is executed and we subscribed on OnAfterMatchBankPayments() event publisher where our things are done.
This is not true in case action from a worksheet page (1290) is called. "Account No." is populated through page functions.

This should behave same way not matter from where is called, list page or worksheet.

**Comment by RomanZanizdra** [comment]
Hi @boych83.
As you already mentioned these actions work in a little bit different way, one just imports statement, the other one imports and process statement. I'm not sure we should make these two actions behave the same way. In order to cover your requirements you can subscribe on "AfterAction" on the page and run  ProcessStatement function which is available for external call or run the codeunit for which you already have a subscriber.
Let me know if there are any concerns on suggested solution.

**Comment by boych83** [comment]
Hi @RomanZanizdra.

I've described import transaction as example on this page but then we found problematic also other actions regarding updating "Account No." field (without validation).  
Yes, I can use page action subscriber you suggested but is this doable (subscribing on page action) for other actions?

e.g: Manual Application - this action opens new page on which I can accept application. When page is closed "Account No." is populated. Here I need to subscribe OnBeforeActionEvenet() to do Comit() before my things are done on  OnAfterActionEvent().
So proper way to do this is to Identify all actions which updates value of "Account No." without validation and add page action subscribers?
What about subscriber on OnAfterGetRecord()? Would be this to costly?

BR,
Bojan

**Comment by RomanZanizdra** [comment]
@boych83 I don't fully understand your case. If you want to make two actions behave absolutely the same way it's obvious they should call the same code or the same sequence of functions. In that case you even don't need to subscribe on "AfterAction..." event, you can for example subscribe on the OnAfterImportBankTransactions event (PAG1290), run any code you want and then just skip further standard import by setting SubscriberInvoked = true. 
Or use standard import and then run codeunit "Match Bank Pmt. Appl." without using ProcessStatement function in the "OnAfterAction..." subscriber.
Or create your own function and copy code there from one of the actions.
Can you be more detailed in description of your case, and what do you finally want to get?

**Comment by boych83** [comment]
We've added additional fields to TAB274 regarding our legislation. Values of our fields depend on value of "Account No." and default values are populated when "Account No." field is validated (e.g.: when user manually inserts entries).
There are page actions (ImportTransactions, Apply Manually,..) on PAG1290 that updates the value of the "Account No." field without validation. 
If value of "Account No." is updated after page action it should be validated otherwise I need to identify all those actions to mimic logic from validate trigger of "Account No." to page action subscriber or to other subscribers.

**Comment by RomanZanizdra** [comment]
Are you sure that validate of "Account No." field is not working while doing manual application. I've just put a message on validate, run manual application from 1290, set applied flag and saw the message.
But actually it doesn't matter. Do you have any strong requirements or restrictions that your own fields should be filled while doing import, "on-fly"? Is it a problem to go through reconciliation lines one more time after they were imported and call simple validate for "Account No." or fill your fields in dependency on the already set "account no." fields? May be you need some additional events you can subscribe and do things you need? Let me know.

**Comment by boych83** [comment]
I will look at current subscribers associated with page actions and the logic behind.
I'm currently using OnAfterGetRecordEvent(). With redesign code will be moved to other subscribers.
I will open new issue, if additional subscriber will be needed.

Thanks for your help.

BR,
Bojan
