### ISSUE TITLE
The request for path /v2.0/Production-Wave2/dev/metadata failed with code ServiceUnavailable. Reason: Service Unavailable

### ISSUE THREAD

**Issue by manisharma31** [microsoft/ALAppExtensions#4726]
Error is coming up when publishing the extension to production, when we published on SandBox Wave2 there was no problem.

Error: a server-side error occured while processing the request.
Request ID: 68d8f6fc-1f08-42e7-8c7c-a74234bb2312
Session ID: 6b71b903-e6ea-46b4-b953-1c3f23cb1ece

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
The request for path /v2.0/Production-Wave2/dev/metadata failed with code ServiceUnavailable. Reason: Service Unavailable

This is on Saas i.e. cloud.

**Comment by AlexanderYakunin** [comment]
This area is not monitored for service or bug requests, please use regular support options.
