### ISSUE TITLE
[Event Request] COD6501 OnAssistEditTrackingNoOnBeforeSetSources  

### ISSUE THREAD

**Issue by chris-amco** [microsoft/ALAppExtensions#4727]
Hi
I am trying to convert a NAV2018 feature that prevents use of inventory received after the document posting date (e.g. if its receipt date is tomorrow, it cannot be sold today). 

When the user selects lots via the Item Tracking Lines page, lots whose receipt date is after the document posting date should not be shown. When the user chooses lots via Process > Select Entries, I can filter out unwanted receipts by subscribing to OnSelectMultipleTrackingNoOnBeforeSetSources. However if they choose to click the Assist Edit button in the Lot No. field, I cannot exclude the unwanted receipts because C6501.AssistEdit() lacks a similar event. Would it be possible to add one?

Thank you in advance.
Chris

SelectMultipleTrackingNo()
`        // Initialize form
        ItemTrackingSummaryForm.Caption := Text011;
        ItemTrackingSummaryForm.SetTableView(TempGlobalEntrySummary);
        TempGlobalEntrySummary.SetFilter("Table ID", '<>%1', 0); // Filter out summations
        OnSelectMultipleTrackingNoOnBeforeSetSources(TempTrackingSpecification, TempGlobalEntrySummary, MaxQuantity);
        ItemTrackingSummaryForm.SetSources(TempGlobalReservEntry, TempGlobalEntrySummary);
`

AssistEditTrackingNo()
`    
      ItemTrackingSummaryForm.SetCurrentBinAndItemTrkgCode(CurrBinCode, CurrItemTrackingCode); // Add OnAssistEditTrackingNoOnBeforeSetSources  here...
        ItemTrackingSummaryForm.SetSources(TempGlobalReservEntry, TempGlobalEntrySummary);
        ItemTrackingSummaryForm.LookupMode(SearchForSupply);
        ItemTrackingSummaryForm.SetSelectionMode(false);`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
