### ISSUE TITLE
[Event Request] Report 702 OnAfterCheckDimension

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4728]
Please add a new Event trigger "OnAfterCheckDimension" in Report 702:

Item Journal Line - OnAfterGetRecord()
OnBeforeItemJournalLineOnAfterGetRecord("Item Journal Line",ErrorCounter,ErrorText);

NoOfEntries["Entry Type" + 1] := 1;
...

DimSetEntry.SETRANGE("Dimension Set ID","Dimension Set ID");
IF NOT DimMgt.CheckDimIDComb("Dimension Set ID") THEN
  AddError(DimMgt.GetDimCombErr);

//+++++++++++++++++++++++++++++++++++++++++++++
OnAfterCheckDimension("Item Journal Line";ItemJnlTemplate;QtyError);
//---------------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
