### ISSUE TITLE
Excel buffer functions

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4729]
Is this the right place to request additional features for extending Excel Buffer / Excel integration (OnPrem)?

We used to have an OfficeHelper add-in to manipulate Excel files (client-side) by **protecting a range**, **password protecting the Workbook** and **adding custom properties** to the Excel file.  What would be the alternatives for the modern client to manipulate the generated Excels?

```
OfficeHelper.ProtectRange(XlApp, ProtectedColumns.xlColID + '1', ProtectedColumns.xlColID + Format(MaxRowNo));
OfficeHelper.SetPasswordOnWorkSheet(XlApp, ProtectionPassword);
OfficeHelper.AddCustomPropertyToActiveWorksheet(XlApp, WorksheetProperties.Code1, WorksheetProperties.Text1);
```

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Unsure if we can provide a solution. @AndreiPanko, what is your take on this?

**Comment by JesperSchulz** [comment]
I'm afraid I don't have an answer for you here on the spot. We realize that certain capabilities went away with the retirement of the windows client - such as running client side add-ins. So far, we've mostly been able though to develop server side equivalents, which also in this case seems viable! We also know, that our Office integration story is due for a little refresh after the move to the new client - work we do have in our backlog, but which I don't know when we'll get to!
Unfortunately I don't know enough about the functionality you need to advise you, if this indeed would work server side. Maybe the community can help you (e.g. mibuso forum?).

If you would like Microsoft to take a stab at this, I would advice you to create an idea on [aka.ms/bcideas](aka.ms/bcideas) to get this routed to a team, which may have the capacity to execute on it. I'm afraid the workload is higher than what we can deal with through an issue in this repo. Sorry that I cannot be of more help on this issue right now.
