### ISSUE TITLE
Refactoring Codeunit 7000, function SetUoM

### ISSUE THREAD

**Issue by Zoltero** [microsoft/ALAppExtensions#4730]
Codeunit has some External functions to find correct agreement price.
One of these is CalcBestUnitPrice which we are subscribing.
Unfortunate this function uses a local function to convert the price to UoM.
It uses a variable to calculate the unit price.  But this variable is not initalized and it is not
possible to initialize it from outside the Codeunit 7000.
As a result it will set the unit price to 0.
The request is to refactor the function SetUoM from Local to External function.

**Comment by AlexanderYakunin** [comment]
This function is already external in 15.X. Please use actual version for your request.
