### ISSUE TITLE
Extending the Base App DotNet errors

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4731]
I'm in the process of extending the Base App in AL for Wave 2 as there are a few areas that we still need to customize for our extension until fixes have been implemented.

I've gotten the errors down to 12 which all seem to revolve around Microsoft.Dynamics.Nav.Runtime library not being found.  Screenshot is below.
![image](https://user-images.githubusercontent.com/31968749/68133780-040b5080-feef-11e9-9b15-85bd12dc8be2.png)

I have a dependency defined to the System Application.
I have included additional assemblyProbingPaths:
        "./.netpackages",
        "C:\\Windows\\assembly",
        "C:\\Program Files\\Assemblies",
        "C:\\Program Files\\Microsoft Dynamics 365 Business Central\\150",
        "C:\\Program Files (x86)\\Microsoft Dynamics 365 Business Central\\150",
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.7.2",
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\WindowsPowerShell"

Could you perhaps point me in the direction to finding where this should be found to include in the app?  Thanks!

**Comment by sboeve** [comment]
Nevermind!  It turns out that some paths in the assemblyprobingPaths were not accurate locations for our server.  I switched those and all seems to be good.

**Comment by sboeve** [comment]
Sorry still getting used to how long it takes to see if you have an error in the code.  I still have the above mentioned errors and require assistance.

**Comment by NKarolak** [comment]
The syntax for your additional al.assemblyProbingPaths must be adjusted.
Instead of (e.g.) "C:\Windows\assembly", you'll need "C:\\Windows\\assembly",

"./.netpackages" is usually ".netpackages"

**Comment by sboeve** [comment]
Thank you for your response, I did have all of my paths set with the "\\" as opposed to a single. 

I do not have a .netpackages folder as it was not part of the zip file for the base NAV/BC app.  Should it have been?

Is it possible that with the CD Version of the base app there is a dll at that was not included for Microsoft.Dynamics.NAV.Runtime ?  i've searched the entire server for this and also the CD folders and have not found it.

Or is there somewhere else this dll is supposed to come from?

Thanks!

**Comment by NKarolak** [comment]
I don' know where to find it all on DVD, but if you create a BC docker container (in my case, called BC1500) to develop against, this is the path you should add:
![image](https://user-images.githubusercontent.com/34504100/68277726-16f95e80-0070-11ea-9135-521136439dc6.png)
