### ISSUE TITLE
Blob Fieldref CreateInStream 

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#4732]
As presented in the  [Breaking Changes](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md#blob-storage-module
) the TempBlob table will be removed. 

This creates an issue when using FieldRef for a field of type Blob. In the past we were able to do the following
```
if FldRef.Type() = FieldType::Blob then begin
       FldRef.CalcField();
       TempBlob.Blob := FldRef.Value();
       TempBlob.StartReadingTextLines(TEXTENCODING::UTF8);
       while TempBlob.MoreTextLines() do
              Something(TempBlob);
end;

```

A field of type Blob has the "CreateInStream" method as seen in Report  1304 "Standard Sales - Quote"
`Header."Work Description".CreateInStream(WorkDescriptionInstream, TEXTENCODING::UTF8);`
but that's missing in the FieldRef. 

How do you propose to handle Blobs with FieldRef?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by IhorHandziuk** [comment]
Hi @JulianTillmann. The `Temp Blob` codeunit has a function `FromFieldRef`. 
After copying the value of the FieldRef , you will be able to create an InStream from the TempBlob codeunit.
