### ISSUE TITLE
[Event Request] Codeunit 427 - f(x) OutboxPurchHdrToInbox

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4733]
Hi!

We need an additional event before ICPartner is fetched in f(x) OutboxPurchHdrToInbox in the ICInboxOutboxMgt codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/68199160-c75a5a80-ffbd-11e9-8178-5f3962c1f0a3.png)

![image](https://user-images.githubusercontent.com/55734714/68199198-d6d9a380-ffbd-11e9-9f25-585988e2a0f5.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
