### ISSUE TITLE
Extensibility issues: Page 9249 Analysis by Dimensions Matrix

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#4734]
The page `Analysis by Dimensions Matrix` is currently not extendible.

Issue 1: The methods `Load` and `Load2` should be revised and replaced with some kind of key/value buffer which we can extend and pass our own values down from the matrix options page. At the moment we cannot add custom parameters.

Issue 2: Events are required to hook into `CalcAmount`, `CalcActualAmount` and `CalcBudgAmount`. At the moment it is not possible to add custom calculations to this matrix.

My suggestions: 

- Add the classic `OnBefore` and `OnAfter` pair, where the former also implements the handled pattern.
- Make sure that the new events for `CalcAmount` continue correctly buffering the calculated value in `AVBreakdownBuffer`.
- Parameters required are (at least): 
  - the current `AnalysisViewEntry`
  - Include the sending page so that we have access to the various methods that set filters (`SetCommonFilters`, `SetDimFilters`, `SetCommonBudgetFilters`, `SetDimBudgetFilters`). These methods also need to become public and external.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
