### ISSUE TITLE
Extensibility issues: Page 9233 G/L Balance by Dim. Matrix

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#4736]
The page 9233 `G/L Balance by Dim. Matrix` is currently not extendible. The same identical concepts that I have already described in issue #4734 apply to this page as well.

In short:
- We need a key/value buffer to pass calculation parameters to this page from the options page
- We need events to allow customizing the calculation of the value
- We need the set-filter methods to become public and external in order to reuse them in our calculations

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
