### ISSUE TITLE
[Event Request] Codeunit 80 - Procedure CheckAndUpdate - Set SrcCode

### ISSUE THREAD

**Issue by franckgolob** [microsoft/ALAppExtensions#4737]
Hi,
For some of our ISVs or custom developments, in some cases,
We need to post Sales Invoices or Sales Cr.Memos with another Source Code than the one set in Source Code Setup.
In order to do that,
In the Codeunit 80, Procedure CheckAndUpdate, can you add an event to update the source code like this:

```
local procedure CheckAndUpdate(var SalesHeader: Record "Sales Header")
...
begin
    with SalesHeader do begin
        ...
        SourceCodeSetup.Get;
        SrcCode := SourceCodeSetup.Sales;
        // >>NEW
        OnAfterSetSrcCode(SrcCode, SourceCodeSetup, SalesHeader);
        // <<NEW
        ...
    end;
    ...
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterSetSrcCode(var SrcCode: Code[10]; SourceCodeSetup: Record "Source Code Setup"; SalesHeader: Record "Sales Header")
begin
end;
```

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
