### ISSUE TITLE
[Event request] Table 39 - OnAfterCreateDim

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#4739]
OnAfterCreateDim needed in the Table 39:
OnAfterCreateDim(var SalesLine: Record "Sales Line"; CallingFieldNo: Integer)

The same would be needed in the Table 37:
https://github.com/microsoft/ALAppExtensions/issues/1501

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
