### ISSUE TITLE
Include TableNo on Fields.Lookup Page

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4740]
If table numbers are not meant to dissappear soon, it would be nice if we would have the 'Table No' field available on the 'FieldsLookup' page (hidden by default?). Our consultant often now the table no. by heart and searching seems faster (in RTC)

Having table no / table name vs field no / field name seems logic?

https://github.com/microsoft/ALAppExtensions/blob/master/Modules/System/Field%20Selection/src/FieldsLookup.Page.al

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
