### ISSUE TITLE
LanguageManagement.ApplicationLanguage / LookupApplicationLanguage

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4742]
Can you please update the 'BreakingChanges' document?

> 'LanguageManagement.ApplicationLanguage' (Codeunit LanguageManagement) is now replaced by 'Language.**GetDefaultApplicationLanguageId**' (Codeunit Language)

> 'LanguageManagement.LookupApplicationLanguage' (Codeunit LanguageManagement) is now replaced by 'Language.**LookupApplicationLanguageId**' (Codeunit Language)

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Thank you for reporting! I will do so right away!
