### ISSUE TITLE
[Event request] Codeunit 12 - OnBeforeInsertGLBookEntry and OnAfterInsertGLBookEntry (IT localization)

### ISSUE THREAD

**Issue by demiliani** [microsoft/ALAppExtensions#4743]
In the Italian localization, we have the need to posted "Extra G/L" movements. These movements must be posted into the G/L Entry table but not in the GL Book Entry table.
In codeunit 12, _Procedure FinishPosting(GenJnlLine: Record "Gen. Journal Line") IsTransactionConsistent: Boolean_ should be modified as follows:
**ORIGINAL CODE:****
SourceCodeSetup.Get;
 InsertGLBookEntry(GlobalGLEntry);
OnAfterInsertGlobalGLEntry(GlobalGLEntry);

**REQUESTED MODIFICATION:**
SourceCodeSetup.Get;
**Handled:=false;
OnBeforeInsertGLBookEntry(GlobalGLEntry, Handled);**
InsertGLBookEntry(GlobalGLEntry, Handled);
**OnAfterInsertGLBookEntry(GlobalGLEntry);**
OnAfterInsertGlobalGLEntry(GlobalGLEntry);

and then add Handled in the standard InsertGLBookEntry procedure:
procedure InsertGLBookEntry(NewGLEntry: Record "G/L Entry")
begin
  **if Handled then
    exit;**
  ...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
