### ISSUE TITLE
[Event Request] COD 7317 Whse. Integration Management - OnBeforeCheckBinTypeCode

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#4744]
Please Add event request to COD 7317 Whse. Integration Management  in function CheckBinTypeCode

[IntegrationEvent(false, false)]
local procedure OnBeforeCheckBinTypeCode(SourceTable: Integer; BinCodeFieldCaption: Text[30], Location: Record Location BinCode: Code[20], AdditionalIdentifier: Option, IsHandled: Boolean);

With Handler Pattern as shown in below 

![image](https://user-images.githubusercontent.com/28138717/68309068-2eefd300-00ae-11ea-8a77-cd821cc74920.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by MortenRa** [comment]
Hi, I can see that this is available in the next major release, would it be possible to put it into the current release as we have an app ready for appsource but is missing this last event. thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
