### ISSUE TITLE
[Event Request] Codeunit 427 - f(x) CreateOutboxPurchDocTrans

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4745]
Hi!

We need an additional event before OutboxTransaction is inserted in f(x) CreateOutboxPurchDocTrans in the ICInboxOutboxMgt codeunit.
![image](https://user-images.githubusercontent.com/55734714/68308995-11bb0480-00ae-11ea-8a88-0078259ca457.png)

![image](https://user-images.githubusercontent.com/55734714/68309182-5646a000-00ae-11ea-8fdf-b821a90c5fff.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
