### ISSUE TITLE
Codeunit 99000854 OnBeforeForecastConsumption

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#4746]
Can we add new event in Codeunit 99000854.

    local procedure ForecastConsumption(var DemandInvtProfile: Record "Inventory Profile"; var Item: Record Item; OrderDate: Date; ToDate: Date) UpdatedOrderDate: Date
    var
        ForecastEntry: Record "Production Forecast Entry";
        ForecastEntry2: Record "Production Forecast Entry";
        NextForecast: Record "Production Forecast Entry";
        CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
        TotalForecastQty: Decimal;
        ReplenishmentLocation: Code[10];
        ForecastExist: Boolean;
        NextForecastExist: Boolean;
        ReplenishmentLocationFound: Boolean;
        ComponentForecast: Boolean;
        ComponentForecastFrom: Boolean;
        **IsHandled: Boolean;     // New**
    begin
        **OnBeforeForecastConsumption(DemandInvtProfile,Item,OrderDate,ToDate,UpdatedOrderDate,IsHandled);   // New**

    // NEW +
    **[IntegrationEvent(false, false)]
    local procedure OnBeforeForecastConsumption(var DemandInvtProfile: Record "Inventory Profile"; var Item: Record Item; OrderDate: Date; ToDate: Date; var UpdatedOrderDate: Date; var IsHandled: Boolean);
    begin
    end;**
    // NEW -

**Comment by MatthewMcCarthy7** [comment]
Sorry forgot to add the Is Handled piece.

    local procedure ForecastConsumption(var DemandInvtProfile: Record "Inventory Profile"; var Item: Record Item; OrderDate: Date; ToDate: Date) UpdatedOrderDate: Date
    var
        ForecastEntry: Record "Production Forecast Entry";
        ForecastEntry2: Record "Production Forecast Entry";
        NextForecast: Record "Production Forecast Entry";
        CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
        TotalForecastQty: Decimal;
        ReplenishmentLocation: Code[10];
        ForecastExist: Boolean;
        NextForecastExist: Boolean;
        ReplenishmentLocationFound: Boolean;
        ComponentForecast: Boolean;
        ComponentForecastFrom: Boolean;
        IsHandled: Boolean;             // NEW
    begin
        // NEW+
        OnBeforeForecastConsumption(DemandInvtProfile,Item,OrderDate,ToDate,UpdatedOrderDate,IsHandled);
        if IsHandled then
            exit;
        // NEW-
        UpdatedOrderDate := OrderDate;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
