### ISSUE TITLE
Assisted Setup - what is current correct way to remove / re-register custom entries?

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#4747]
I have encountered the issue when I cannot find a way to remove (own) registered Assisted Setup entry. Neither completed, nor untouched.
Could you please specify how is it handled and if handled at all.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by darjoo** [comment]
Hi @PaulFurlet,
Currently there isn't a way to remove an entry but with the PR #5299, the functionality to remove Assisted Setup entries will be coming. 

We do have functionality to reset a current entry, thanks to #4541. The action will be coming in 15.3, the above functionality should as well.

-Darrick

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
