### ISSUE TITLE
[EventRequest]Add new Var to codeunit 6620 “Copy Document Mgt.”, CopyPurchLine [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4748]
We had previously requested upon CopyPurchLine, and received a possible sufficient way to work it out from [AlexanderYakunin ](https://github.com/microsoft/ALAppExtensions/issues/4317). We have tried working with it, and we want to request that you add a new VAR NextlineNo, by adding this to OnBeforeInsertPurchLine it works for our part., notice this is not for OnBeforeUpdatePuchLine, but on the Insert. 

![Inkedny vaiabel i codeunit 6620_LI](https://user-images.githubusercontent.com/54017538/68368720-ef21fd80-0138-11ea-8a87-9827ff4fb4ae.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/54017538/68368728-f34e1b00-0138-11ea-9bb0-83ee61c07221.png)

Please let us know if this is sufficient.

**Comment by AlexanderYakunin** [comment]
Already added

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertToPurchLine(var ToPurchLine: Record "Purchase Line"; FromPurchLine: Record "Purchase Line"; FromDocType: Option; RecalcLines: Boolean; var ToPurchHeader: Record "Purchase Header"; DocLineNo: Integer; var NexLineNo: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
