### ISSUE TITLE
[EventRequest] Table 37 IsCalcVATAmountLinesHandled - OnBeforeCalcVATAmountLines

### ISSUE THREAD

**Issue by BartPermentier** [microsoft/ALAppExtensions#4749]
This Event already exists but does not contain a very important variable from the function.
Please add the variable QtyType to:

- IsCalcVATAmountLinesHandled 
- OnBeforeCalcVATAmountLines

![image](https://user-images.githubusercontent.com/24684493/68382012-230a1c80-0153-11ea-8694-ca64b5d28b7e.png)
![image](https://user-images.githubusercontent.com/24684493/68382225-8e53ee80-0153-11ea-8e79-99b25915bb53.png)
![image](https://user-images.githubusercontent.com/24684493/68382328-c6f3c800-0153-11ea-8683-18d7cf0e2e2c.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
