### ISSUE TITLE
[EventRequest] codeunit 6620 “Copy Document Mgt.”, CopyArchSalesLine [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4750]
Please add a new publisher event OnCopyArchSalesLineOnBeforeToSalesLineInsert in Codeunit 6620 on function CopyArchSalesLines and call it as shown in the image below (in the end of the function) 

![image](https://user-images.githubusercontent.com/54017538/68386290-01f9f980-015c-11ea-93b3-1e4f4c45e16c.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/68386121-ac255180-015b-11ea-9ee8-b45c4765e667.png)

Please let me know if this is sufficient !

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
