### ISSUE TITLE
[EventRequest] codeunit 6620 “Copy Document Mgt.”, CopyArchPuchLine [Local] 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4751]
Please add a new publisher event OnCopyArchPurchLineOnBeforeToPurchLineInsert in Codeunit 6620 on function CopyArchPurchLine and call it as shown in the image below (in the end of the function)

![image](https://user-images.githubusercontent.com/54017538/68386561-96fcf280-015c-11ea-8c86-46346d62e5e5.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/68386618-b72cb180-015c-11ea-824f-beb2ffcf8054.png)

Please let me know if this is sufficient !

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
