### ISSUE TITLE
"Home Page" Field in "Base Application" - Different Length

### ISSUE THREAD

**Issue by g-franck** [microsoft/ALAppExtensions#4753]
Hi,
Can you standardize the length of "Home Page" Field in "Base Application" ?

In table 79 "Company Information", it's a Text[80]:
```
        field(35; "Home Page"; Text[80])
        {
            Caption = 'Home Page';
            ExtendedDatatype = URL;
        }
```

In table 5714 "Responsibility Center", it's a Text[90]:
```
        field(103; "Home Page"; Text[90])
        {
            Caption = 'Home Page';
            ExtendedDatatype = URL;
        }
```

Thanks

**Comment by AlexanderYakunin** [comment]
It is 80 in most places, except few with 90 chars, but we cannot decrease field length. Is this really critical for any reason?

**Comment by franckgolob** [comment]
Of course you cannot decrease field length. But maybe you can all increase to 90, or 100.
"Home Page" field in table 14 "Location" is also a Text[90].
It's not critical, but it was just a note to warn of a possible overflow, ex:

```
TableX."Home Page-Text[80]" := TableY."Home Page-Text[90]";
```

**Comment by AlexanderYakunin** [comment]
We will make a fix for any reported overflow issues, currently didn't get any.
