### ISSUE TITLE
EnumRequest - Multiple Tables

### ISSUE THREAD

**Issue by libin80** [microsoft/ALAppExtensions#4754]
We are in process of upgrading a DB from NAV 2017 to BC. The following fields has additional option values. Would like the following fields to be Extended. Appreciate if you can provide a target release, for planning our deliverables.

Table 17 - G/L Entry
----------------------
Document Type
Bal. Account Type
Source Type

Table 21 - Cust. Ledger Entry
----------------------
Document Type
Bal. Account Type

Table 25 - Vendor Ledger Entry
----------------------
Document Type
Bal. Account Type

Table 36 - Sales Header
----------------------
Bal. Account Type

Table 37 - Sales Line
----------------------
Type

Table 38 - Purchase Header
----------------------
Bal. Account Type

Table 39 - Purchase Line
----------------------
Type

Table 80 - Gen. Journal Template
----------------------
Type
Bal. Account Type

Table 81 - Gen. Journal Line
----------------------
Document Type
Account Type
Bal. Account Type
Source Type

Table 110 - Sales Shipment Header
----------------------
Bal. Account Type

Table 111 - Sales Shipment Line
----------------------
Type

Table 112 - Sales Invoice Header
----------------------
Bal. Account Type

Table 113 - Sales Invoice Line
----------------------
Type

Table 114 - Sales Cr. Memo Header
----------------------
Bal. Account Type

Table 115 - Sales Cr. Memo Line
----------------------
Type

Table 120 - Purch. Receipt Header
----------------------
Bal. Account Type

Table 121 - Purch. Receipt Line
----------------------
Type

Table 122 - Purch. Inv. Header
----------------------
Bal. Account Type

Table 123 - Purch. Inv. Line
----------------------
Type

Table 124 - Purch. Cr. Memo Header
----------------------
Bal. Account Type

Table 125 - Purch. Cr. Memo Line
----------------------
Type

**Comment by AlexanderYakunin** [comment]
Please create individual requests per each option field. We cannot process bulk requests.
