### ISSUE TITLE
Codeunit 99000809 OnTransferBOMOnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#4755]
In Codeunit 99000809 can we add RequisitionLine to the Publisher OnTransferBOMOnBeforeGetDefaultBin.

OnTransferBOMOnBeforeGetDefaultBin(PlanningComponent, ProdBOMLine , ReqLine);

    [IntegrationEvent(false, false)]
    local procedure OnTransferBOMOnBeforeGetDefaultBin(var PlanningComponent: Record "Planning Component"; var ProductionBOMLine: Record "Production BOM Line"; RequisitionLine: Record "Requisition Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
