### ISSUE TITLE
Codeunit 99000854 Make External and Global

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#4757]
In codeunit 99000854 Inventory Profile Offsetting, can we make functions **ForecastInitDemand**, **FindReplishmentLocation**, and **CheckForecastExist** Global and External

**Comment by AlexanderYakunin** [comment]
We can do it for next version. Is this Ok for you?

**Comment by MatthewMcCarthy7** [comment]
Yes.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
