### ISSUE TITLE
[Event Request] Sales Line - OnUpdateAmountOnBeforeCheckCreditLimit change

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#4758]
Can the CurrFieldNo be added to the OnUpdateAmountOnBeforeCheckCreditLimit event in the Sales Line table (37) please?

![image](https://user-images.githubusercontent.com/34585093/68462187-f235f000-0203-11ea-80e8-29a9f17aaab0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
