### ISSUE TITLE
EventSubscriber - Table 38 Purchase Header OnDelete trigger

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4759]
Kindly add below code in Table 38 Purchase Header - OnDelete Trigger

OnBeforePostedDocsToPrintCreatedMsg(IsHandled);
If IsHandled then
Exit;

![image](https://user-images.githubusercontent.com/53224672/68474200-ce49cd00-024a-11ea-8168-3be2cb34a70d.png)

**Comment by pradeepmn91** [comment]
![image](https://user-images.githubusercontent.com/53224672/68474458-7364a580-024b-11ea-9915-c005cf28294f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
