### ISSUE TITLE
EnumRequest - Table 80 Gen. Journal Template - Field - Type

### ISSUE THREAD

**Issue by libin80** [microsoft/ALAppExtensions#4772]
EnumRequest - Table 80 Gen. Journal Template - Field - Type

**Comment by AlexanderYakunin** [comment]
Already done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
