### ISSUE TITLE
EnumRequest - Table 122 Purch. Inv. Header - field - Bal. Account Type

### ISSUE THREAD

**Issue by libin80** [microsoft/ALAppExtensions#4786]
EnumRequest - Table 122 Purch. Inv. Header - field - Bal. Account Type

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by libin80** [comment]
Can you kindly confirm when this Enum request will be available?
