### ISSUE TITLE
[Event Request] Purchase Header Buy-from Vendor No. - OnValidate() trigger

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4790]
please add an event OnValidateBuyFromVendorNoAfterRecreateLines in table 38 - Purchase Header - Field  Buy-from Vendor No. - OnValidate() trigger, after RecreatePurchaseLines function call

![image](https://user-images.githubusercontent.com/53224672/68478973-38686f00-0257-11ea-8332-fbc1d0954e86.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
