### ISSUE TITLE
[Event Request] Codeunit 423 OnBeforeIsLogActive

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/ALAppExtensions#4792]
Problem: With the current Events its not possible to prevent changelog from logging certain processes when BC **is already running**. These processes are like syncing certain data between companies at certain moments, normally we would like to log changes on these tables for instance, but not in these processes. 

Please add a new publisher event to the function IsLogActive as follows:

```
LOCAL IsLogActive(TableNumber : Integer;FieldNumber : Integer;TypeOfChange : 'Insertion,Modification,Deletion') : Boolean
//>> Start New Publisher Call
OnBeforeIsLogActive(TableNumber,FieldNumber,TypeOfChange,IsHandled);
IF IsHandled THEN
  EXIT(FALSE);
//<< End New Publisher Call

IF IsAlwaysLoggedTable(TableNumber) THEN
  EXIT(TRUE);
.
.
```

New Publisher Event:
```
LOCAL [IntegrationEvent] OnBeforeIsLogActive(TableNumber : Integer;FieldNumber : Integer;TypeOfChange : 'Insertion,Modification,Deletion';VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
