### ISSUE TITLE
Table 77 "Report Selections" - Field 1 "Usage" - Option to Enum (Extensible)

### ISSUE THREAD

**Issue by franckgolob** [microsoft/ALAppExtensions#4793]
Hi,
I saw that in the MASTER database you started to convert Option fields to Enum, and all were extensible. That's very good news.
In addition to issues #260 and #2011 ,
Can you give us more information about a possible release of these requests ? (No/Yes, When ...)
Thanks.

**Comment by AlexanderYakunin** [comment]
This is work in progress and should be completed in November.
