### ISSUE TITLE
[Event Request] T36 / T38 / T5900 OnAfterSetOperationType

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#4794]
Problem: With the current Events its not possible to extend the function "SetOperationType" (Italian Localization) in tables 36, 38 and 5900.

Please add a new publisher event to the function SetOperationType as follows:

    PROCEDURE SetOperationType@1130000();
    BEGIN
      IF "Document Type" <> "Document Type"::"Credit Memo" THEN
        IF "VAT Bus. Posting Group" <> '' THEN BEGIN
          VATBusPostingGroup.GET("VAT Bus. Posting Group");
          IF VATBusPostingGroup."Default Sales Operation Type" <> '' THEN
            VALIDATE("Operation Type",VATBusPostingGroup."Default Sales Operation Type");
        END;

      // Start New Publisher Call
      OnAfterSetOperationType(Rec);
      // End New Publisher Call
    END;

New Publisher Event:

    LOCAL PROCEDURE OnAfterSetOperationType@1000000001(VAR SalesHeader@1000000000 : Record 36);
    BEGIN
    END;

Thank you
Fabio

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
