### ISSUE TITLE
Undocumented breaking change  

### ISSUE THREAD

**Issue by rdebath** [microsoft/ALAppExtensions#4795]
Message:
```
Codeunit 'Password Helper' is missing
```

There doesn't seem to be a substitute.
I actually only need a secure source of random bytes; they don't have to match any particular password entropy limitations. A limited amount of bias is also acceptable.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
