### ISSUE TITLE
ReCalc Method in Codeunit: 3010801 "QuoteMgt"

### ISSUE THREAD

**Issue by lucahochreutener** [microsoft/ALAppExtensions#4799]
Hi 

Is it possible that I can use this Method for Extension Developement? Currently I am using this Function for my automated tests.

![image](https://user-images.githubusercontent.com/24219934/68574190-a7b5ad00-0469-11ea-97cf-6dfe2f8cd0d7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
