### ISSUE TITLE
[Event Request] Page 6510 Item Tracking Lines - OnRegisterModifyChange

### ISSUE THREAD

**Issue by maksym-ch** [Microsoft/ALAppExtensions#48]
Hi,
We need to implement additional business logic after registering changes.
The following publisher is needed to be added (when changes are registered with type = modify):
Page 6510 Item Tracking Lines -Function RegisterChange() -
**OnRegisterModifyChange(FromTrackingSpecification : Record "Tracking Specification";VAR ToTrackingSpecification : Record "Tracking Specification")**
![p6510 - 02](https://user-images.githubusercontent.com/44081671/47075971-60c59b80-d206-11e8-99c8-e5d347f75cda.png)

**Comment by AndriiHrynyuk** [comment]
Hi,
The publisher in the last BC differs from the one that was requested here. Added event publisher 
`LOCAL [IntegrationEvent] OnRegisterChangeOnAfterModify(VAR NewTrackingSpecification : Record "Tracking Specification";OldTrackingSpecification : Record "Tracking Specification")` 
does not contain the OldTrackingSpecification parameter by var. 

Could you please modify the mentioned publisher in the following way:
`LOCAL [IntegrationEvent] OnRegisterChangeOnAfterModify(VAR NewTrackingSpecification : Record "Tracking Specification";var OldTrackingSpecification : Record "Tracking Specification")` ?

Thanks.
