### ISSUE TITLE
[Event Request] OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify

### ISSUE THREAD

**Issue by hydhart** [microsoft/ALAppExtensions#4800]
This Integration Event, i want to ask is it possible to make it one of the parameter to be var.

![image](https://user-images.githubusercontent.com/41423177/68576133-17df2580-04a0-11ea-9b2d-915b1870ae04.png)

LOCAL [IntegrationEvent] OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify(**VAR** **ItemLedgerEntry : Record "Item Ledger Entry"**;VAR OldItemLedgerEntry : Record "Item Ledger Entry";ItemJournalLine : Record "Item Journal Line")

the bold one.
i needed this for my custom. the logic just like remaining quantity.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
