### ISSUE TITLE
Table 38 Purchase Header On Rename Trigger

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4802]
Kindly add below code in Table 38 Purchase Header - Onrename Trigger

OnBeforePurchaseHeaderRename(IsHandled);
If IsHandled then
Exit;

![image](https://user-images.githubusercontent.com/53224672/68579550-64bffd80-049a-11ea-9e24-62e30c9a3d78.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
