### ISSUE TITLE
Table 38 Purchase Header -[External] UpdateAllLineDim(NewParentDimSetID : Integer;OldParentDimSetID : Integer) Function  

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4803]
Kindly add the below event code in function updateallLineDim in purchase header

OnBeforeUpdateAllLineDimConfirmProcess(SupressConfirmationDialog,DefaultButton)
IF SupressConfirmationDialog THEN 
  IF NOT DefaultButton THEN
    EXIT;
ELSE

![image](https://user-images.githubusercontent.com/53224672/68579861-25de7780-049b-11ea-9cff-649263f63a3f.png)

**Comment by AlexanderYakunin** [comment]
We cannot implement it this way as code have been changed. Please take latest code and reconsider.
