### ISSUE TITLE
Table 81 New Publisher UpdateCountryCodeAndVATRegNo

### ISSUE THREAD

**Issue by wfelberbauer** [microsoft/ALAppExtensions#4804]
Can you add 2 publisher in the function **UpdateCountryCodeAndVATRegNo**:

**OnBefore**UpdateCountryCodeAndVATRegNo(Rec, xRec);
......
**OnAfter**UpdateCountryCodeAndVATRegNo(Rec,xRec);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
