### ISSUE TITLE
Table 39 Purchase Line [External] InitQtyToReceive() Function

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4807]
Kindly add below code in Table 39 Purchase Line - InitQtyToReceive() Function

OnBeforeInitQtyToReceive(Rec,CurrFieldNo,IsHandled);
IF IsHandled THEN
  EXIT;

![image](https://user-images.githubusercontent.com/53224672/68589905-300c7000-04b3-11ea-8507-7faf0d050962.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
