### ISSUE TITLE
Table 39 Purchase Line [External] InitQtyToInvoice() Function

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4808]
Kindly add below code in Table 39 Purchase Line - InitQtyToInvoice() Function

OnBeforeInitQtyToInvoice(Rec,CurrFieldNo,IsHandled);
IF IsHandled THEN
  EXIT;

![image](https://user-images.githubusercontent.com/53224672/68590094-b5902000-04b3-11ea-8a8a-5d8419f1e54c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
