### ISSUE TITLE
Transfer Order Subform - Drilldown on Qty Shipped and Qty Received

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4810]
Could the following two drilldown definitions be further clarified?   Thanks very much.

![image](https://user-images.githubusercontent.com/49729094/68595234-0cbbd380-0467-11ea-8f38-d749c56926f5.png)

![image](https://user-images.githubusercontent.com/49729094/68595293-2b21cf00-0467-11ea-95d4-2a07f98cfff8.png)

Suggestion:  
![image](https://user-images.githubusercontent.com/49729094/68595395-5d333100-0467-11ea-9166-ecb74537eb51.png)

![image](https://user-images.githubusercontent.com/49729094/68595459-74721e80-0467-11ea-8470-3b089d23d069.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
