### ISSUE TITLE
[Event Request] Table 81 - Gen. Journal Line - ClearCustVendApplnEntry

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#4821]
Could you please create an Integration event in Table 81 - Gen. Journal Line - , in function ClearCustVendApplnEntry?

```
[External] ClearCustVendApplnEntry()
GetAccTypeAndNo(Rec,AccType,AccNo);
CASE AccType OF
....
END;

// >>>>
OnAfterClearCustVendApplnEntry(Rec,AccType,AccNo,xRec);
// <<<<
```

Event signature:
```
LOCAL [IntegrationEvent] OnAfterClearCustVendApplnEntry(VAR GenJournalLine : Record "Gen. Journal Line";AccType : 'G/L Account,Customer,Vendor,Bank Account,Fixed Asset,IC Partner,Employee';AccNo : Code[20];xGenJournalLine : Record "Gen. Journal Line")

```

For our extension: we need to clear our fields too.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
