### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - CalcPmtDiscPossible

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#4826]
Could you please create an Integration event in Codeunit 12 Gen. Jnl.-Post Line, in function CalcPmtDiscPossible?

```
LOCAL CalcPmtDiscPossible(GenJnlLine : Record "Gen. Journal Line";VAR CVLedgEntryBuf : Record "CV Ledger Entry Buffer")
// >>>>>>>
IsHandled := FALSE;
OnBeforeCalcPmtDiscPossible(GenJnlLine,CVLedgEntryBuf,IsHandled);
IF IsHandled THEN
  EXIT;
// <<<<<<<

WITH GenJnlLine DO
....
```

Event signature:
```
LOCAL [IntegrationEvent] OnBeforeCalcPmtDiscPossible(GenJnlLine : Record "Gen. Journal Line";VAR CVLedgEntryBuf : Record "CV Ledger Entry Buffer";VAR IsHandled : Boolean)
```

Similar to OnBeforeCalcPmtDisc event in CalcPmtDisc function (in the same codeunit).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
