### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - CreateGLEntriesForTotalAmounts

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#4827]
Could you please create an Integration event in Codeunit 12 Gen. Jnl.-Post Line, in function CreateGLEntriesForTotalAmounts?

```
LOCAL CreateGLEntriesForTotalAmounts(...)
....
WITH InvPostBuf DO BEGIN
  RESET;
  IF FINDSET THEN
    REPEAT
      IF (Amount <> 0) OR ("Amount (ACY)" <> 0) AND (AddCurrencyCode <> '') THEN BEGIN
        DimMgt.UpdateGenJnlLineDim(GenJnlLine,"Dimension Set ID");
        // >>>>>>>>>
        OnBeforeCreateGLEntryForTotalAmounts(GenJnlLine,InvPostBuf,GLAccNo);
        // <<<<<<<<<
        CreateGLEntryForTotalAmounts(GenJnlLine,Amount,"Amount (ACY)",AdjAmountBuf,SavedEntryNo,GLAccNo);
        GLEntryInserted := TRUE;
      END;
    UNTIL NEXT = 0;
END;
....
```

Event signature:
```
LOCAL [IntegrationEvent] OnBeforeCreateGLEntryForTotalAmounts(VAR GenJnlLine : Record "Gen. Journal Line";VAR TempInvPostBuf : TEMPORARY Record "Invoice Post. Buffer";VAR Account : Code[20])
```

We are not able to use existing event OnBeforeCreateGLEntriesForTotalAmounts, because we need to change GLAccNo variable for each record in TempInvPostBuf table.
For our extension we need to fill some of our fields too.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
