### ISSUE TITLE
[Event Request] Codeunit 1101 - CA Jnl.-Check Line - RunCheck

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#4829]
Could you please create an Integration event in Codeunit 1101 - CA Jnl.-Check Line, in function RunCheck?

```
[External] RunCheck(VAR CostJnlLine : Record "Cost Journal Line")
WITH CostJnlLine DO BEGIN
....
  IF GenJnlCheckLine.DateNotAllowed("Posting Date") THEN
    FIELDERROR("Posting Date",Text005);
  // >>>>
  OnAfterCheckCostJnlLine(CostJnlLine);
  // <<<<
END;
```

Event signature:
```
LOCAL [IntegrationEvent] OnAfterCheckCostJnlLine(VAR CostJnlLine : Record "Cost Journal Line")
```

(Similar to Integration event OnAfterCheckGenJnlLine in Codeunit 11 Gen. Jnl.-Check Line.)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
