### ISSUE TITLE
[Event Request] Codeunit 1102 - CA Jnl.-Post Line - RunWithCheck

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#4830]
Could you please create an Integration event in Codeunit 1102 CA Jnl.-Post Line, in function RunWithCheck?

```
[External] RunWithCheck(VAR CostJnlLine2 : Record "Cost Journal Line")
CostJnlLine.COPY(CostJnlLine2);
Code;
CostJnlLine2 := CostJnlLine;
// >>>>
OnAfterRunWithCheck(CostJnlLine2);
// <<<<
```

Event signature:
```
LOCAL [IntegrationEvent] OnAfterRunWithCheck(VAR CostJournalLine : Record "Cost Journal Line")
```

(Similar to Integration event OnAfterRunWithCheck in Codeunit 12 Gen. Jnl.-Post Line.)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
