### ISSUE TITLE
[Event Request] codeunit 1209 "Export Payment File" - OnBeforeExportPaymentFile

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4833]
Can you added event OnBeforeExportPaymentFile to codeunit 1209 "Export Payment File"?

Both parameters as reference.

![image](https://user-images.githubusercontent.com/46031720/68649663-831e0b80-0523-11ea-908d-2879b6fdebf7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
