### ISSUE TITLE
[EventRequest] Report 7052 " Suggest Sales Price on Wksh.", Sales price - OnAfterGetRecord() [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#4834]
Please add a new publisher event OnBeforeModifyOrInsertSalesPriceWksh in report 7304 on trigger Sales price - OnAfterGetRecord() and call it as shown in the picture below in the end of the function

![image](https://user-images.githubusercontent.com/54017538/68650944-76e77d80-0526-11ea-9251-470c0c9896ba.png)

Please add the corresponding Integration Event In the bottom of the report

![image](https://user-images.githubusercontent.com/54017538/68650957-7f3fb880-0526-11ea-9212-752de2d9c834.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
