### ISSUE TITLE
Functions for handling of attchments in 5103 "Interaction Tmpl. Language" without scope OnPrem

### ISSUE THREAD

**Issue by GerritHolzGOB** [microsoft/ALAppExtensions#4835]
To be able to extend the functionality of Interaction Templates, we need the scope of the functions in the table "Interaction Tmpl. Language" to be removed. 

As the functionality is called in the webclient anyway, the scope does not need to be restricted. We consider this scope restriction as an artifact from v14.

Please remove the Scope('OnPrem') annotation for follwing functions:

```cal
[Scope('OnPrem')]
procedure CreateAttachment()

[Scope('OnPrem')]
procedure OpenAttachment()

[Scope('OnPrem')]
procedure CopyFromAttachment()

[Scope('OnPrem')]
procedure ImportAttachment()

[Scope('OnPrem')]
procedure ExportAttachment()

[Scope('OnPrem')]
procedure RemoveAttachment(Prompt: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
