### ISSUE TITLE
[Event Request] Codeunit 427 - f(x) MoveOutboxTransToHandledOutbox

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4839]
Hi!

We need two additional events in f(x) MoveOutboxTransToHandledOutbox in the ICInboxOutboxMgt codeunit - before and after the execution of transferfields from ICOutboxTrans to HandledICOutboxTrans.
![image](https://user-images.githubusercontent.com/55734714/68664046-f9306b80-053f-11ea-9d85-5d28b14052e3.png)

![image](https://user-images.githubusercontent.com/55734714/68664068-00577980-0540-11ea-93c9-ebffca407dd4.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
