### ISSUE TITLE
[EventRequest] codeunit 1102 “CA. Jnl.-Post Line” procedure CreateCostRegister

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4840]
Please add a new publisher events OnBeforeInsertCostRegister and OnBeforeModifyCostRegister in Codeunit 1102 on function CreateCostRegister and call it as shown in the image below
![image](https://user-images.githubusercontent.com/26144133/68664917-6c86ad00-0541-11ea-9118-75bebce2af0a.png)

Please add the corresponding Integration Event In the bottom of the codeunit
`LOCAL [IntegrationEvent] CGK_OnBeforeInsertCostRegister(VAR CostRegister : Record "Cost Register";CostJournalLine : Record "Cost Journal Line";SourceCodeSetup : Record "Source Code Setup")`
`LOCAL [IntegrationEvent] CGK_OnBeforeModifyCostRegister(VAR CostRegister : Record "Cost Register";CostJournalLine : Record "Cost Journal Line";SourceCodeSetup : Record "Source Code Setup")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
