### ISSUE TITLE
[Event Request] codeunit 1209 "Export Payment File" - OnAfterExportPaymentFile

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#4843]
Can you added event OnAfterExportPaymentFile to codeunit 1209 "Export Payment File"?

Rec as Var.

![image](https://user-images.githubusercontent.com/46031720/68669612-41a15680-054b-11ea-8332-e001ff504c23.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
