### ISSUE TITLE
[Event Request] Table 18 - Customer - OnBeforeLookupCity

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4845]
Hi AL-Team,
can you please add the following Publisher in City OnLookup Trigger? 
We have detailed behaviors for customer, vendor and contact and need to know from where the check is called.
```
trigger OnLookup()
            begin
                // NEW >>>
                OnBeforeLookupCity(Rec, PostCode);
                // NEW <<<
                PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");
            end;

       [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupCity(var Rec: Record Customer; var PostCode: Record "Post Code")
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
