### ISSUE TITLE
[Enum Request] Table 32 "Item Ledger Entry" - field "Document Type"

### ISSUE THREAD

**Issue by nego777** [microsoft/ALAppExtensions#4846]
Please convert field type Document Type to enum in table 32 Item Ledger Entry.
Best regards,
Dragos

**Comment by AlexanderYakunin** [comment]
This is done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
