### ISSUE TITLE
Codeunit 20 PostingPreviewEventHandler - ShowEntries

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#4848]
i would like to create a different pages for the entries and for that i need a publisher event in codeunit 20 postingprevieweventhandler - function "ShowEntries" with all the temp tables as parameters.

onbeforeshowentries(TempGLEntry,TempCustLedgEntry,TempDtldCustLedgEntry,TempVendLedgEntry,TempDtldVendLedgEntry,TempEmplLedgEntry,TempDtldEmplLedgEntry,TempVATEntry,TempValueEntry,TempItemLedgerEntry,TempFALedgEntry,TempBankAccLedgerEntry,TempResLedgerEntry,TempServiceLedgerEntry,TempWarrantyLedgerEntry,TempMaintenanceLedgerEntry,TempJobLedgerEntry,IsHandled)
if IsHandled then exit;

**Comment by AlexanderYakunin** [comment]
No, we cannot do this as your approach is not extendable. Why you want different pages, can you customize existing ones? What is wrong with our pages?

**Comment by bartpattijn** [comment]
Hi Alexander,

We have a big BPO customer with over 2000 end customers and they need the preview posting with result in 1 page with

  *   General ledger entries
  *   VAT entries
  *   VAT amounts by VAT statement Row no. (this we have for the moment in page extension on the VAT entries Preview page.
But they find this to time consuming to first get the page with al entries listed and then to click through the different entry types.
So we would need to make this combined on a single page.
Do you see another way of accomplishing this?

Met vriendelijke groeten,​
[Christiaens]
[cid:image010.png@01D5A6CB.0949C8A0]
[cid:image011.png@01D5A6CB.0949C8A0]
[cid:image012.png@01D5A6CB.0949C8A0]
[cid:image013.jpg@01D5A6CB.0949C8A0]
[cid:image014.png@01D5A6CB.0949C8A0]
Bart Pattijn
ERP Consultant
Christiaens NV
e:
bart.pattijn@christiaens.net
t:
0032 51 78 83 83
w:
www.christiaens.net
a:
Passendalestraat 199
B‑8980
Passendale
[LinkedIn]<https://www.linkedin.com/company/christiaens-nv/>
[YouTube]<https://www.youtube.com/channel/UCGBiFesfXKF0ErJfSZ1XxvQ>
[Twitter]<https://twitter.com/Christiaens_net>
[Facebook]<https://www.facebook.com/christiaensnv/>
[Teamviewer]<https://get.teamviewer.com/christiaens>

Van: Alexander Yakunin <notifications@github.com>
Verzonden: vrijdag 29 november 2019 14:56
Aan: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
CC: Bart Pattijn <Bart.Pattijn@christiaens.net>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/ALAppExtensions] Codeunit 20 PostingPreviewEventHandler - ShowEntries (#4848)


No, we cannot do this as your approach is not extendable. Why you want different pages, can you customize existing ones? What is wrong with our pages?

**Comment by AlexanderYakunin** [comment]
If you can make page extension, we can move temp tables to protected var area, and you will have fill access. Does it works for you?

**Comment by bartpattijn** [comment]
Hi Alexander,

Yes that works for me.
I can make a page extension in which I can then show the entries they need.

Thanks!

Met vriendelijke groeten,​
[Christiaens]
[cid:image012.png@01D5B016.54F418B0]
[cid:image013.png@01D5B016.54F418B0]
[cid:image014.png@01D5B016.54F418B0]
[cid:image015.jpg@01D5B016.54F418B0]
Bart Pattijn
ERP Consultant
Christiaens NV
e:
bart.pattijn@christiaens.net
t:
0032 51 78 83 83
w:
www.christiaens.net
a:
Passendalestraat 199
B‑8980
Passendale
[LinkedIn]<https://www.linkedin.com/company/christiaens-nv/>
[YouTube]<https://www.youtube.com/channel/UCGBiFesfXKF0ErJfSZ1XxvQ>
[Twitter]<https://twitter.com/Christiaens_net>
[Facebook]<https://www.facebook.com/christiaensnv/>
[Teamviewer]<https://get.teamviewer.com/christiaens>

Van: Alexander Yakunin <notifications@github.com>
Verzonden: woensdag 11 december 2019 11:22
Aan: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
CC: Bart Pattijn <Bart.Pattijn@christiaens.net>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/ALAppExtensions] Codeunit 20 PostingPreviewEventHandler - ShowEntries (#4848)


If you can make page extension, we can move temp tables to protected var area, and you will have fill access. Does it works for you?

**Comment by AlexanderYakunin** [comment]
Unfortunately, we were not able to change this design based on this request. We have slice for this work for the future release.
