### ISSUE TITLE
Table 36 "Sales Header" - TESTFIELD("Quantity Shipped",0)

### ISSUE THREAD

**Issue by SKeiler** [Microsoft/ALAppExtensions#485]
Could you please redesign the code and move all TESTFIELD's for Quantity Shipped in Table 36 to one function and add a "OnAfter"-Event to this new function. Background is, that we want to add an additional check similar to the Quantity Shipped-Field.

**Comment by JesperSchulz** [comment]
We'll look into it! But could you provide a few more details on what you'd like to achieve? Just to make sure we're not going down the wrong path. Thanks!

**Comment by SKeiler** [comment]
Hi Jesper,

which kind of further details you need? There are two pieces of source Code in BC (CU0) in Table 36 which do a SalesLine.TESTFIELD("Quantity Shipped",0). In our ISV we have an additional field in table 37 which we want to check if it's zero too in this cases. So it would be great if the two checks can be transfered to one function and this function has also an event to have to possibility to check our field too.

**Comment by JesperSchulz** [comment]
Great, that how I understood it :-) Thanks for clarifying. We're on it!

**Comment by JesperSchulz** [comment]
This issue has been resolved. Please verify in recent preview. If it does not meet your expectations, please open a new issue, as we don't monitor closed issues. Thanks!
