### ISSUE TITLE
[Event Request] Table 18 - Customer - OnBeforeValidatePostCode

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4850]
Hi AL-Team,
can you please add the following Publisher in Post Code OnValidate Trigger? We have detailed checks for customer, vendor and contact and need to know from where the check is called.

```
            trigger OnValidate()
            begin
                // TSO KT BEG
                OnBeforeValidatePostCode(Rec, PostCode);
                // TSO KT END
                PostCode.ValidatePostCode(City, "Post Code", County, "Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);

                OnAfterValidatePostCode(Rec, xRec);
            end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidatePostCode(var Rec: Record Customer; var PostCode: Record "Post Code")
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
