### ISSUE TITLE
Expose function Initialize in table Assisted Setup

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#4851]
Could you please expose function Initialize, in table Assisted Setup?
We need it for extension development.

Thanks,
Radovan

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
There is no such function in the latest version of the table: https://github.com/microsoft/ALAppExtensions/blob/master/Modules/System/Assisted%20Setup/src/AssistedSetup.Table.al. Please open a new request, if there are other functions you would like us to expose. Or even better, create a pull request in this repository with the requested changes.
