### ISSUE TITLE
Event Request Codeunit 5988 - Serv-Documents Mgt.

### ISSUE THREAD

**Issue by brijeshkarnatak** [microsoft/ALAppExtensions#4852]
I am working, on NAV 15, Wave 2. Missing the event (OnAfterUpdateFillInvPostingBuffer) right after

ServAmountsMgt.FillInvPostingBuffer(InvPostingBuffer,ServLine,ServiceLineACY,ServHeader);

In case some amount need to be split. 

OR could be on Codeunit 5986 function UpdInvPostingBuffer

OnAfterUpdateInvPostBuffer

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by brijeshkarnatak** [comment]
Thanks for consideration and wish you Happy Merry Christmas & New year -2020. Are you releasing in Jan-2020, please keep posted. Thanks!
