### ISSUE TITLE
[EventRequest] codeunit 1105 “Transfer GL Entries to CA” procedure GetGLEntries

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4853]
Please add a new publisher event OnBeforePostCostJournalLines in Codeunit 1105 on function GetGLEntries and call it as shown in the image below
![image](https://user-images.githubusercontent.com/26144133/68690300-14b46a00-0572-11ea-85ed-ba18ba4d5cff.png)
Please add the corresponding Integration Event In the bottom of the codeunit
`LOCAL [IntegrationEvent] OnBeforePostCostJournalLines(VAR TempCostJnlLine : TEMPORARY Record "Cost Journal Line";VAR TotalDebit : Decimal;VAR TotalCredit : Decimal;VAR NoOfJnlLines : Integer;VAR BatchRun : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
