### ISSUE TITLE
[Code Defect] Codeunit 5704 "TransferOrder-Post Shipment" on procedure InsertTransShptHeader

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4854]
Probably inside italian localization there is a wrong code regarding noseries assignement
![image](https://user-images.githubusercontent.com/26144133/68691213-abcdf180-0573-11ea-9f6a-caebfa223890.png)

code below 
`TransShptHeader."No." := NoSeriesMgt.GetNextNo(NoSeries,TransHeader."Posting Date",TRUE);`
must be changed in 
`TransShptHeader."No." := NoSeriesMgt.GetNextNo(TransShptHeader."No. Series",TransHeader."Posting Date",TRUE);`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
