### ISSUE TITLE
Event Request Codeunit 80 - Compare with Cdu 90

### ISSUE THREAD

**Issue by DennyHW** [microsoft/ALAppExtensions#4855]
I hope to find in codeunit 80 the "sames" event of codeunit 90.

For example :
OnBeforeUpdateSalesLineBeforePost(...)
OnAfterUpdateSalesLineBeforePost(...)
OnBeforeTestSalesLine(...);
OnAfterTestSalesLine(...)

Thanks.

**Comment by AlexanderYakunin** [comment]
The structure is not exactly the same, please order what you need with place and parameters.

**Comment by DennyHW** [comment]
In cdu 80 function UpdateSalesLineBeforePost(...) i need the events :
**OnBeforeUpdateSalesLineBeforePost**(SalesLine,SalesHeader,WhseShip,WhseReceive,RoundingLineInserted,SuppressCommit)
**OnAfterUpdateSalesLineBeforePost**(SalesLine,WhseShip,WhseReceive)
placed as first and last instruction of the function, as done in cdu 90 function UpdatePurchLineBeforePost(...). Thanks.

**Comment by AlexanderYakunin** [comment]
But you have it! 

    local procedure UpdatePurchLineBeforePost(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line")
    begin
        OnBeforeUpdatePurchLineBeforePost(PurchLine, PurchHeader, WhseShip, WhseReceive, RoundingLineInserted, SuppressCommit);
........

        OnAfterUpdatePurchLineBeforePost(PurchLine, WhseShip, WhseReceive);
    end;

Where you are searching for events? We only deliver for 15.X versions.

**Comment by AlexanderYakunin** [comment]
We already have it for SalesPost (and for PurchPost):

    local procedure UpdateSalesLineBeforePost(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line")
    begin
        OnBeforeUpdateSalesLineBeforePost(SalesLine, SalesHeader, WhseShip, WhseReceive, RoundingLineInserted, SuppressCommit);

        with SalesLine do begin
            if not (SalesHeader.Ship or RoundingLineInserted) then begin
                "Qty. to Ship" := 0;
                "Qty. to Ship (Base)" := 0;
            end;
            if not (SalesHeader.Receive or RoundingLineInserted) then begin
                "Return Qty. to Receive" := 0;
                "Return Qty. to Receive (Base)" := 0;
            end;

            JobContractLine := false;
            if (Type = Type::Item) or (Type = Type::"G/L Account") or (Type = Type::" ") then
                if "Job Contract Entry No." > 0 then
                    PostJobContractLine(SalesHeader, SalesLine);
            if Type = Type::Resource then
                JobTaskSalesLine := SalesLine;

            if (SalesHeader."Document Type" = SalesHeader."Document Type"::Invoice) and ("Shipment No." <> '') then begin
                "Quantity Shipped" := Quantity;
                "Qty. Shipped (Base)" := "Quantity (Base)";
                "Qty. to Ship" := 0;
                "Qty. to Ship (Base)" := 0;
            end;

            if (SalesHeader."Document Type" = SalesHeader."Document Type"::"Credit Memo") and ("Return Receipt No." <> '') then begin
                "Return Qty. Received" := Quantity;
                "Return Qty. Received (Base)" := "Quantity (Base)";
                "Return Qty. to Receive" := 0;
                "Return Qty. to Receive (Base)" := 0;
            end;

            if SalesHeader.Invoice then begin
                if Abs("Qty. to Invoice") > Abs(MaxQtyToInvoice) then
                    InitQtyToInvoice;
            end else begin
                "Qty. to Invoice" := 0;
                "Qty. to Invoice (Base)" := 0;
            end;

            if (Type = Type::Item) and ("No." <> '') then begin
                GetItem(Item);
                if (Item."Costing Method" = Item."Costing Method"::Standard) and not IsShipment then
                    GetUnitCost;
            end;
        end;

        OnAfterUpdateSalesLineBeforePost(SalesLine, SalesHeader, WhseShip, WhseReceive, SuppressCommit);
    end;

**Comment by DennyHW** [comment]
What i suggested is for Purchase posting (codeunit 90).
In BC14 they 're not present.
if you have already entered them in 15.x, thanks in advance.

**Comment by AlexanderYakunin** [comment]
We do not provide events for 14.X since March 2019, please always use 15.X code base for requests. Just to save time for both of us.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
