### ISSUE TITLE
Page 354 Item Turnover Lines - make local proc external - ShowItemEntries

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4857]
I have checked the latest release, it's still local.  Thanks.

![image](https://user-images.githubusercontent.com/49729094/68711860-8687b600-0568-11ea-9021-8b2007787ebb.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
