### ISSUE TITLE
Page 30 Item Card - make local external -  EnableControls

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#4858]
I have checked the latest release, it's still local. Thanks.

![image](https://user-images.githubusercontent.com/49729094/68712385-9f449b80-0569-11ea-9633-9801991e09db.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
