### ISSUE TITLE
[Event Request] Codeunit 7324 Whse.-Activity-Post - CreatePostedActivHeader

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#4859]
I request 4 new events in Codeunit 7324 in function CreatePostedActivHeader:

Original
PostedInvtPutAwayHdr.INSERT(TRUE);

New with PostedInvtPutAwayHdr as VAR
OnBeforePostedInvtPutAwayHdrInsert(PostedInvtPutAwayHdr, WhseActivHeader);
PostedInvtPutAwayHdr.INSERT(TRUE);
OnAfterPostedInvtPutAwayHdrInsert(PostedInvtPutAwayHdr, WhseActivHeader);

Original
PostedInvtPickHdr.INSERT(TRUE);

New with PostedInvtPickHdr as VAR
OnBeforePostedInvtPickHdrInsert(PostedInvtPickHdr, WhseActivHeader);
PostedInvtPickHdr.INSERT(TRUE);
OnAfterPostedInvtPickHdrInsert(PostedInvtPickHdr, WhseActivHeader);

Thank you for your attention.
Regards
Walter

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
