### ISSUE TITLE
COD10-TypeHelper function EvaluateUTCDateTime

### ISSUE THREAD

**Issue by wmstreet** [Microsoft/ALAppExtensions#486]
I am receiving a UTC date from an external web service call, it is in the format
2018-11-06 21:25:06
Which in US Eastern Time would be 11/6/2018 4:25PM.
In C/AL we used dotnet System.DateTime calls to properly convert to a DateTime variable.
In AL we tried using COD10-TypeHelper function EvaluateUTCDateTime, but with the above format, it just returns an empty datetime. Could I receive some feedback on the recommended way to accomplish this.

**Comment by JesperSchulz** [comment]
Sorry, you're barking up the wrong tree here. We'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
