### ISSUE TITLE
[Event Request] Codeunit 5802 - Inventory Posting To G/l - OnBeforeGetInvPostingSetup

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#4860]
Hello everyone,

it would be nice to have the following event. Its required to use the same accounts to all locations in a ISV that we are developing. 

This has been working correctly in previous versions.

Event location:
```
LOCAL SetAccNo(VAR InvtPostBuf : Record "Invt. Posting Buffer";ValueEntry : Record "Value Entry";AccType : Option;BalAccType : Option)
WITH InvtPostBuf DO BEGIN
  "Account No." := '';
  "Account Type" := AccType;
  "Bal. Account Type" := BalAccType;
  "Location Code" := ValueEntry."Location Code";
  "Inventory Posting Group" :=
    GetInvPostingGroupCode(ValueEntry,AccType = "Account Type"::"WIP Inventory",ValueEntry."Inventory Posting Group");
  "Gen. Bus. Posting Group" := ValueEntry."Gen. Bus. Posting Group";
  "Gen. Prod. Posting Group" := ValueEntry."Gen. Prod. Posting Group";
  "Posting Date" := ValueEntry."Posting Date";

  //--NEW EVENT --
  OnBeforeGetInvPostingSetup(UseInvtPostSetup, CalledFromItemPosting, InvtPostBuf, InvtPostSetup, GenPostingSetup, lHandled);

  IF NOT lHandled THEN
  //++NEW EVENT ++


  IF UseInvtPostSetup THEN BEGIN
    IF CalledFromItemPosting THEN
      InvtPostSetup.GET("Location Code","Inventory Posting Group")
    ELSE
      IF NOT InvtPostSetup.GET("Location Code","Inventory Posting Group") THEN
        EXIT;
.
.
.
.
```

Event declaration:

`LOCAL [IntegrationEvent] OnBeforeGetInvPostingSetup(pUseInvtPostSetup : Boolean;pCalledFromItemPosting : Boolean;VAR pInvtPostBuf : Record "Invt. Posting Buffer";VAR pInvtPostSetup : Record "Inventory Posting Setup";VAR pGenPostingSetup : Record "General Posting Setup";VAR pHandled : Integer)`

Thanks in advice!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
