### ISSUE TITLE
[Event Request] Codeunit 6620 OnBeforeCopySalesDocUpdateHeader and OnBeforeCopyPurchDocUpdateHeader

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4862]
please add new event trigger OnBeforeCopySalesDocUpdateHeader and OnBeforeCopyPurchDocUpdateHeader in codeunit 6620:

LOCAL CopySalesDocUpdateHeader(FromDocType : Option;FromDocNo : Code[20];VAR ToSalesHeader : Record "Sales Header";FromSalesHeader : Record "Sales Header";FromSalesShptHeader : Record "Sales Shipment Header";FromSalesInvHeader : Record "Sales Invoice 
WITH ToSalesHeader DO BEGIN
  CheckCustomer(FromSalesHeader,ToSalesHeader);
  OldSalesHeader := ToSalesHeader;
  //+++++++++++++++++++++++++++++++++++++
  OnBeforeCopySalesDocUpdateHeader(VAR ToSalesHeader,FromSalesHeader);
  //-------------------------------------
  CASE FromDocType OF
    SalesDocType::Quote,
    SalesDocType::"Blanket Order",
    SalesDocType::Order,
    SalesDocType::Invoice,
    SalesDocType::"Return Order",
    SalesDocType::"Credit Memo":
      BEGIN
         ....

LOCAL CopyPurchDocUpdateHeader(FromDocType : Option;FromDocNo : Code[20];VAR ToPurchHeader : Record "Purchase Header";FromPurchHeader : Record "Purchase Header";FromPurchRcptHeader : Record "Purch. Rcpt. Header";FromPurchInvHeader : Record "Purch. Inv
WITH ToPurchHeader DO BEGIN
  IF Vend.GET(FromPurchHeader."Buy-from Vendor No.") THEN
    Vend.CheckBlockedVendOnDocs(Vend,FALSE);
  IF Vend.GET(FromPurchHeader."Pay-to Vendor No.") THEN
    Vend.CheckBlockedVendOnDocs(Vend,FALSE);
  OldPurchHeader := ToPurchHeader;
  //+++++++++++++++++++++++++++++++++++++++++++
  OnBeforeCopyPurchDocUpdateHeader(VAR ToPurchHeader,FromPurchHeader);
  //-------------------------------------------
  CASE FromDocType OF
    PurchDocType::Quote,
    PurchDocType::"Blanket Order",
    PurchDocType::Order,
    PurchDocType::Invoice,
    PurchDocType::"Return Order",
    PurchDocType::"Credit Memo":
      BEGIN
        ….

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
