### ISSUE TITLE
[Event Request] Table 39 in Function ValidateReturnReasonCode: OnBeforeValidateReturnReasonCode

### ISSUE THREAD

**Issue by AsierIber** [microsoft/ALAppExtensions#4883]
We need the Event OnBeforeValidateReturnReasonCode in Table 39 (in Function ValidateReturnReasonCode)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
