### ISSUE TITLE
[Event Request] Table 18 - Customer - OnBeforeGetSalesLCY

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4884]
Hi AL-Team,
can you please add the following Publisher in procedure GetSalesLCY?

```
 procedure GetSalesLCY(): Decimal
    var
        CustomerSalesYTD: Record Customer;
        AccountingPeriod: Record "Accounting Period";
        StartDate: Date;
        EndDate: Date;
    begin
        // NEW >>>>
        OnBeforeGetSalesLCY(Rec,CustomerSalesYTD);
        // NEW <<<<
        StartDate := AccountingPeriod.GetFiscalYearStartDate(WorkDate);
        EndDate := AccountingPeriod.GetFiscalYearEndDate(WorkDate);
        ...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetSalesLCY(var Rec: Record Customer;var CustomerSalesYTD: Record Customer)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
