### ISSUE TITLE
[Event Request] Codeunit 431 - f(x) SendToInternalPartner

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#4885]
Hi!

We need an additional event before the "Move IC Trans. to Partner Comp" report is executed in f(x) SendToInternalPartner in the IC Outbox Export codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/68773099-3faec480-062b-11ea-993d-eb49b72e7981.png)

![image](https://user-images.githubusercontent.com/55734714/68773109-463d3c00-062b-11ea-9ad4-509c06f590d0.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
