### ISSUE TITLE
[Event Request] Codeunit  2500 - "Extension Installation Impl" - onBefore & onAfter InstallExtensionSilently

### ISSUE THREAD

**Issue by LD-ocn5** [microsoft/ALAppExtensions#4886]
Hi, 
with the possibility to extend the pages 'Extension Management' and  'Extension Details' gone we would like to get some ways to check if an extension ist currently beeing installed. 
We have some funktionalities in our (onPrem) app that might interfere with the initialisation of app data like "No. Series"-Entrys etc. as our app is managing these for all companies in the database.

We do have a trigger to disable that functionality and would like to call it on these events.

```
procedure InstallExtensionSilently(PackageID: Guid; Lcid: Integer): Boolean
    begin
        CheckPermissions();
        AssertIsInitialized();
        // NEW >>>>
        OnBeforeInstallExtension;
        // NEW <<<<
        DotNetNavAppALInstaller.ALInstallNavApp(PackageID, Lcid);

        // NEW >>>>
        OnAfterInstallExtension;
        // NEW <<<<

        if not IsInstalledByPackageId(PackageID) then
            exit(false);

        exit(true);
    end;
```

**Comment by darjoo** [comment]
Hi @LD-ocn5,
Please try the following with [GetExecutionContext](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/session/session-getexecutioncontext-method)
```
procedure SomeTrigger()
    begin
        if GetExecutionContext() <> ExecutionContext::Normal then
            exit;

        <Other logic>
    end;
```

What this would do is exit and not execute the logic if the current session is in a execution context other than normal. The other execution contexts are install, uninstall and upgrade which I assume is the scenarios you're trying to avoid.

-Darrick

**Comment by darjoo** [comment]
I will be closing this issue now. If the above solution does not achieve what you're looking for, please reopen it.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
