### ISSUE TITLE
[EventRequest] Report 790 “Calculate Inventory”

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4888]
Please change event OnBeforeQuantityOnHandBufferFindAndInsert in Report 790 on Warehouse Entry - OnAfterGetRecord() and including "Warehouse Entry" Record as parameter as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68790694-0c2e6300-0648-11ea-9884-e8bf5a104c4d.png)

And add a new publisher event OnBeforeInsertItemJnlLine in InsertItemJnlLine procedure as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68790736-2700d780-0648-11ea-886d-c4bd5a599180.png)
Please also add the Integration Event at the bottom of the Report:
`LOCAL [IntegrationEvent] OnBeforeInsertItemJnlLine(VAR ItemJournalLine : Record "Item Journal Line";QuantityOnHandBuffer : Record "Inventory Buffer")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
