### ISSUE TITLE
[Event Request] Table 18 - Customer - OnBeforeInsert

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4891]
Hi AL-Team,
can you please add the following publisher with handled pattern to the OnInsert trigger?

```
    trigger OnInsert()
    var
        Handled: Boolean;
    begin
        // NEW >>>>
        OnBeforeInsert(Rec, Handled);
        if Handled then
            exit;
        // NEW <<<<
       ....

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsert(var Rec: Record Customer;var  Handled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
