### ISSUE TITLE
[Event Request] Table 21- Cust. Ledger Entry - OnBeforeSetAmountToApply

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4893]
Hi AL-Team,
can you please add the following publisher in procedure SetAmountToApply?

```
 procedure SetAmountToApply(AppliesToDocNo: Code[20]; CustomerNo: Code[20])
    begin
        // NEW >>>>
        OnBeforeSetAmountToApply(Rec);
        // NEW <<<<
        SetCurrentKey("Document No.");
        ...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetAmountToApply(var Rec: Record "Cust. Ledger Entry")
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
