### ISSUE TITLE
[External Function] REP 2000005 / 2000006 - OnAfterNewConsolidatedPayment

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4895]
In #2777 new events (OnAfterNewConsolidatedPayment) have been added and functions (CheckNewGroupset, IsPaymentMessageTooLong) are set to External. However, how can we subscribe to a Report event and **access the report global functions**?? 

I suppose the (Curr)Report should be passed as extra parameter in event OnAfterNewConsolidatedPayment (both for report 'File SEPA Payments' and 'File Non Euro SEPA Payments'), so we can access the global functions?

![image](https://user-images.githubusercontent.com/25268332/68852575-7858a780-06d8-11ea-8c11-356f5cf753d6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
