### ISSUE TITLE
[EventRequest] codeunit 12 “Gen. Jnl.-Post Line”, HandleBill

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4896]
Please add a new publisher event OnBeforeHandleBill in Codeunit 12 on function HandleBill and call it as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68853200-adb1c500-06d9-11ea-9534-8deca595e565.png)
Please add the corresponding Integration Event In the bottom of the codeunit
`LOCAL [IntegrationEvent] OnBeforeHandleBill(CustLedgerEntry : Record "Cust. Ledger Entry";IsUnapply : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
