### ISSUE TITLE
[EventRequest] Report 5692 “Calculate Depreciation”, OnPostReport

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4897]
Please add a new publisher event CGK_OnBeforeFinalConfirm in Codeunit 5692 on trigger OnPostReport and call it as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68855174-fe2b2180-06dd-11ea-9229-2350d01c856c.png)
Please add the corresponding Integration Event In the bottom of the codeunit
`LOCAL [IntegrationEvent] OnBeforeFinalConfirm(DeprBook : Record "Depreciation Book";GenJournalLine : Record "Gen. Journal Line";GenJnlLineCreatedCount : Integer;VAR IsHandled : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
