### ISSUE TITLE
[Event Change] Table 5876 Inconsistent Position of OnCalcQtyAndLastItemLedgExpectedSetWhseEntryFilters and OnCalcQtyAndLastItemLedgExpectedSetItemLedgEntryFilters

### ISSUE THREAD

**Issue by meikcremer** [microsoft/ALAppExtensions#4898]
The position of the events OnCalcQtyAndLastItemLedgExpectedSetWhseEntryFilters and OnCalcQtyAndLastItemLedgExpectedSetItemLedgEntryFilters are not consistent:

OnCalcQtyAndLastItemLedgExpectedSetWhseEntryFilters is triggered AFTER Calcsums()
OnCalcQtyAndLastItemLedgExpectedSetItemLedgEntryFilters  is triggered BEFORE Calcsums()

From my point of view BEFORE performing Calcsums would be the correct position for both events, in order to add additional filtering.

**Comment by finn777** [comment]
Looks this story start from this Github entry #832

**Comment by meikcremer** [comment]
That's correct, but since the original issue was closed I was not sure if a new issue would be better ;) - thanks for indirectly clarifying

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
