### ISSUE TITLE
[EventRequest] codeunit 99000832 “Sales Line-Reserve”, BindToProdOrder

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4899]
Please add a new publisher event OnBeforeBindToProdOrder in Codeunit 99000832 on function BindToProdOrder and call it as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68861044-050c6100-06eb-11ea-8c24-accebec8dba1.png)
Please add the corresponding Integration Event In the bottom of the codeunit
`LOCAL [IntegrationEvent] OnBeforeBindToProdOrder(SalesLine : Record "Sales Line";ProdOrderLine : Record "Prod. Order Line";ReservQty : Decimal;ReservQtyBase : Decimal;VAR IsHandled : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
