### ISSUE TITLE
Table 6502 Expose and Make Global TestSetSpecific & TestRemoveSpecific

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [Microsoft/ALAppExtensions#490]
Can you make TestSetSpecific & TestRemoveSpecific on Table 6502 External and Global?

**Comment by JesperSchulz** [comment]
We are trying very hard not to expose our internal implementation such as local functions, as every function we expose turns into an API we cannot break (or at least should not break). This reduces our ability to refactor our business logic in the future. We are hence a little protective when it comes to making local functions global ;-) From looking into the code, it is not clear to me why you would need to have these functions exposed, other than for convenience. Did I miss something, or did you just want to prevent having to duplicate code?

**Comment by MatthewMcCarthy7** [comment]
This was to prevent making duplicate code.  I understand not wanting to break other API, but we want to follow the same business logic as what the functions are performing.  So if we copy the function and then you change the function we will most likely not now it was changed or will take some time to find out and could provide different functionality than what the original function was doing.  Isn't the point of having test scripts so if the base app is refactored it would catch those and we would update the app for the next release?
