### ISSUE TITLE
[Event Requests] Codeunit 12184 - Fattura Doc. Helper (Italian localisation)

### ISSUE THREAD

**Issue by JamalEddi** [microsoft/ALAppExtensions#4906]
Hi Team,

We need to add an event to Codeunit 12184 so that we can change the name of the generated XML file, the current file has an incorrect name.

[Scope('OnPrem')]
    **procedure GetFileName(ProgressiveNo: Code[20]): Text[40]**
    var
        CompanyInformation: Record "Company Information";
        ZeroNo: Code[10];
        BaseString: Text;
    begin
  // - country code + the transmitter's unique identity code + unique progressive number of the file
        CompanyInformation.Get;
        BaseString := CopyStr(DelChr(ProgressiveNo, '=', ',?;.:/-_ '), 1, 10);
        ZeroNo := PadStr('', 10 - StrLen(BaseString), '0');
**// >>> NEW
OnBeforExitFileName();
// <<< NEW**
        exit(CompanyInformation."Country/Region Code" +
          CompanyInformation."Fiscal Code" + '_' + ZeroNo + BaseString);
    end;

**Comment by AlexanderYakunin** [comment]
1. How you are going to change file name with this event? You should add parameters to event.
2. Can you explain what is wrong with this file name? We'd better fix it.

**Comment by AlexanderYakunin** [comment]
No reply, closing
