### ISSUE TITLE
[Code Defect] Report 12173 "Issued Cust Bills Floppy" on procedure RECORD51

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4908]
Inside procedure RECORD51 please change code to normalize value as code below
![image](https://user-images.githubusercontent.com/26144133/68872881-08a9e300-06ff-11ea-8253-597adfe5a504.png)

Variable Text0001 is a text constant
Name	ConstValue
Text0001	ABCDEFGHIJKLMNOPQRSTUVWXYZ-/\|"£$%&()'#@*_

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Enomis82** [comment]
As discussion with Søren Alexandersen via email, please change code as below

![image](https://user-images.githubusercontent.com/26144133/72279264-0815c600-3636-11ea-9e9e-d2f6e28f3014.png)
