### ISSUE TITLE
[Event Request] Expose Global Variables Codeunit 333 OnBeforeCarryOutReqLineAction

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4909]
We have the need to access some of the global variables in the OnBeforeCarryOutReqLineAction event within the ReqWkshMakeOrder Codeunit in order to perform different functionality than in the base procedure and then potentially bypass the base procedure code using the IsHandled condition.

Can you please expose them in that event?

example:
[IntegrationEvent(false, TRUE)]
local procedure OnBeforeCarryOutReqLineAction(var RequisitionLine: Record "Requisition Line"; var Failed: Boolean; var IsHandled: Boolean)
begin
end;

**Comment by AlexanderYakunin** [comment]
Can you please specify parameters you want to add?

**Comment by AlexanderYakunin** [comment]
FYI -  we have no possibility to use GlobalVarAccess anymore, this property had been deprecated.

**Comment by AlexanderYakunin** [comment]
Request cannot be implemented, closing
