### ISSUE TITLE
[Event Request] Events to add new entities for CRM Integration

### ISSUE THREAD

**Issue by geeknikolai** [Microsoft/ALAppExtensions#491]
I put this on the ideas site (https://experience.dynamics.com/insider/public-profile/ideas/dynamics-financials/ID0004561) but this site seems to be a better place. 

This document outlines the code you need to add (in NAV) for integrating new entities with CRM. https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--customizing-microsoft-dynamics-crm-integration-in-dynamics-nav This still applies with BC but it doesn't completely work in the extension model. Some of the code has some events or can be handled with new objects, but not all of it. Specifically: Codeunit 5150 Integration Management, Function CreateIntegrationPageList Codeunit 5334 CRM Setup Defaults, Function ResetConfiguration Codeunit 5334 CRM Setup Defaults, Function GetCRMTableNo Codeunit 5334 CRM Setup Defaults, Function GetTableIDCRMEntityNameMapping Can we have some events added in these functions, or the functions that call these?

**Comment by AlexanderYakunin** [comment]
Please be specific and provide definition of events you need.

**Comment by CanuckNav74** [comment]
@AlexanderYakunin  would it make more sense to field your request to the team who engineered the CRM connector for BC/NAV? They would know best on any and all missing aspects that makes life difficult for extending the CRM capabilities via AL. Any event gaps would be best identified by those who engineered the product. In my opinion that feedback shouldn't come from a second-hand source (something may be missed). 

I too ran into similar challenges. Most notably, event pubs not currently present in COD5150 as well as the inability to extend a base CRM entity table from AL. 

The current design makes it difficult (if not impossible in some cases) to extend the CRM capabilities in BC/AL with regards to custom field and/or entity mappings. 

The online BC documentation available does not go into any details above and beyond configuring the core product for CRM connectivity. link: https://docs.microsoft.com/en-ca/dynamics365/business-central/marketing-integrate-dynamicscrm

**Comment by srenders** [comment]
You might also want to have a look at this issue: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1207545665

**Comment by AndersLarsenMicrosoft** [comment]
Hi 
Thanks for raising this question. We have realized that we have some gabs in how to extend our CRM (Sales) integration and CDS overall. Beside raising more events in our code, we also need to enable partners to create tables of type CRM as extensions. 

To be honest I do not know when we will have this in place, but hopefully I will be able to post an update in Q1 2019 

Thanks
Anders

**Comment by CanuckNav74** [comment]
@AndersLarsenMicrosoft I'm a little lost on your last comment. VS Code (I'm on AL Language 2.0.56865) allows me to create new table objects where TableType = CRM. I don't get any intellisense errors on neither the TableType nor ExternalName property, nor any errors on the CRM-specific field properties (ExternalName, ExternalAccess, ExternalType).

According to this github [issue](https://github.com/Microsoft/AL/issues/1813), it should be possible to create new CRM tables for BC targeted for both internal and external provided you're not using an old version of AL Language. 

The only issue I encounter (besides event pubs missing in the CRM codeunits) is when I try to "Extend" an existing CRM table (which is not possible).

**Comment by JesperSchulz** [comment]
I do not see any actionable work in this issue and I will hence close it. If you have specific events you would like us to add, please open a new issue and we will process those asap. For general updates on CRM integration extensibility initiatives, please use other channels.
