### ISSUE TITLE
[EventRequest] report 12173 “Issued Cust Bills Floppy”, RECORD50

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4910]
Please add a new publisher event OnBeforeRECORD50 in report 12173 on function RECORD50 and call it as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68874621-cfbf3d80-0701-11ea-8337-69a089cf8fad.png)

Please add the corresponding Integration Event In the bottom of the report
`LOCAL [IntegrationEvent] OnBeforeRECORD50(VAR OutText : Text[120];Lines : Record "Issued Customer Bill Line";VAR IsHandled : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
