### ISSUE TITLE
[EventRequest] report 12172 “Cust Bills Floppy”, RECORD50

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4911]
Please add a new publisher event OnBeforeRECORD50 in report 12172 on function RECORD50 and call it as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68875273-d8fcda00-0702-11ea-86e2-2f1bd3fed1a3.png)

Please add the corresponding Integration Event In the bottom of the report
`LOCAL [IntegrationEvent] OnBeforeRECORD50(VAR OutText : Text[120];Lines : Record "Customer Bill Line";VAR IsHandled : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
