### ISSUE TITLE
[EventRequest] Codeunit 90 “Purch.-Post”, PostCombineSalesOrderShipment

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4912]
Please add a new publisher event FindingDropShptBuffer in Codeunit 90 on function PostCombineSalesOrderShipment and call it as shown in the image below:
![image](https://user-images.githubusercontent.com/26144133/68875938-ec5c7500-0703-11ea-85b8-e4d99644afe7.png)

Please add the corresponding Integration Event In the bottom of the codeunit
`LOCAL [IntegrationEvent] FindingDropShptBuffer(VAR DropShptPostBuffer : Record "Drop Shpt. Post. Buffer";PurchRcptNo : Code[20];SalesShptLine : Record "Sales Shipment Line";VAR TempTrackingSpecification : Record "Tracking Specification")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
