### ISSUE TITLE
[Event Request] Codeunit 80: OnBeforeUpdatePostingDescription

### ISSUE THREAD

**Issue by rjoehl** [microsoft/ALAppExtensions#4913]
Hi

We'd like the following Event/Code added in the Codeunit 80, our Goal is to add our own Posting Description.
![image](https://user-images.githubusercontent.com/19507020/68876086-2ded2000-0704-11ea-9dad-9ede0cbe1155.png)

Marked is the Code we'd like to have added.
The Codeunit Versions are: NAVW114.06,NAVCH14.06
Thank you for your Time

**Comment by AlexanderYakunin** [comment]
We do not provide events for 14.X, this version is OnPrem and you can add event into code if you need it.

**Comment by rjoehl** [comment]
Hi, you are correct for Version14.X. In the future we would like to offer our App in the Public Cloud, (Version 15.X) where we require this Event.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
