### ISSUE TITLE
[Event Request] Table "Error Message": OnBeforeLogSimpleMessage

### ISSUE THREAD

**Issue by pzentner** [microsoft/ALAppExtensions#4914]
Please add an event "OnBeforeLogSimpleMessage" to table Error Message, function "LogSimpleMessage". It should follow the implementation of "OnBeforeLogMessage" in function "LogMessage". 

Use case is to be able to react on captured errors during posting, for instance. LogLastError logs a simple message, therefore, there is no event that can capture that.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
