### ISSUE TITLE
[Event Request] Codeunit 226 - GetApplicationDate(..)

### ISSUE THREAD

**Issue by munching** [microsoft/ALAppExtensions#4915]
Dear AL team,

I'd like to kindly ask you to add an event to Codeunit 226, to the beginning of procedure GetApplicationDate(). Something like the below would do:
![image](https://user-images.githubusercontent.com/8672591/68877135-39dddf80-070e-11ea-8c58-d3fc3d5a3548.png)

The event signature:
![CustEntryApplyPostedEntries-OnBeforeGetApplicationDate](https://user-images.githubusercontent.com/8672591/68877336-8cb79700-070e-11ea-8ca4-05e635670bee.png)

The idea is that we'd like to apply additional filters to ApplyToCustLedgEntry that would make a more strict set of allowed ApplyTo entries when picking date.

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
