### ISSUE TITLE
[Event Request] Codeunit 90 Purch-Post OnCheckAssocOrderLinesOnBeforeCheckOrderLine

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4916]
We require that the SalesOrderLine variable be added to this event signature as well.  It does not need to be passed in by VAR.

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
