### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post PostcombineSalesOrderShipment

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4917]
We have the need to modify records in our ISV's tables after the ServItemMgt.CreateServItemOnSalesLineShpt function is called in the PostcombineSalesOrderShipment function of the PurchPost codeunit.

We request the following event:
OnBeforeSalesPostUpdateBlanketOrderLine(VAR SalesOrderLine: Record "Sales Line"; SalesShptLine: Record "Sales Shipment Line")

Ex:
SalesOrderLine."Qty. to Ship" := SalesShptLine.Quantity;
SalesOrderLine."Qty. to Ship (Base)" := SalesShptLine."Quantity (Base)";
ServItemMgt.CreateServItemOnSalesLineShpt(SalesOrderHeader, SalesOrderLine, SalesShptLine);
*****New EVENT  
                        OnBeforeSalesPostUpdateBlanketOrderLine(SalesOrderLine, SalesShptLine);

SalesPost.UpdateBlanketOrderLine(SalesOrderLine, true, false, false);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
