### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post PostSalesTaxToGL

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4918]
In this issue #1809, an event was requested for OnBeforeGenJnlPostLine(GenJnlLine).  It will occur before the below line of code, in the PostSalesTxToGL function of the Purch.-Post codeunit.

GenJnlPostLine.RunWithCheck(GenJnlLine);

We require an additional parameter added to this event as well.  TempSalesTaxAmtLine

Please see below for example:
OnBeforeGenJnlPostLine(VAR GenJnlLine: Record "Gen. Journal Line"; TempSalesTaxAmountLine: Record "Sales Tax Amount Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
