### ISSUE TITLE
[Event Request] codeunit 80 Sales-Post PostSalesTaxToGL

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4919]
We require the ability to perform additional functionality after the PostSalesTaxToGL function is complete in the Sales Post codeunit.

We request an additional event be added as the last line of this function:
OnAfterPostSalesTaxToGL(var SalesHeader : Record "Sales Header";GenJnlLineDocType : Integer;GenJnlLineDocNo : Code[20];GenJnlLineExtDocNo : Code[35])

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
