### ISSUE TITLE
[Event Request] Codeunit 9801 - Identity Management / OnAfterChangeWebServicesKey

### ISSUE THREAD

**Issue by gertlynge** [Microsoft/ALAppExtensions#492]
Hi,
For updating WebServicesKeys in i.e. Azure Key Vault, it would be nice to have a event to subscribe to whenever a WebServicesKey is changed.
I suggest that it should only provide one parameter: the UserSecurityID-GUID.
If the subscriber needs the actual Key or ExpiryDate, they can just call the functions to retrieve them. This way the event just notify about the change - it does not expose sensitive information in any way.
The publisher should be called from these 3 existing functions:
- CreateWebServicesKey
- CreateWebServicesKeyNoExpiry
- ClearWebServicesKey

**Comment by AlexanderYakunin** [comment]
Due to security reasons we are not going to provide integration events in this area.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
