### ISSUE TITLE
[Event Request] Codeunit 442 - OnAfterBuildInvLineBuffer

### ISSUE THREAD

**Issue by Fred-Cleverli** [microsoft/ALAppExtensions#4920]
Hi.

I want to sort the Buffer (TempPrepmtInvLine) to my key.
I added fields to the buffer and need a different sorting.

Part of C442:
  ...
  // Create Lines
  TempPrepmtInvLineBuffer.DELETEALL;
  CalcVATAmountLines(SalesHeader,SalesLine,TempVATAmountLine,DocumentType);
  TempVATAmountLine.DeductVATAmountLine(TempVATAmountLineDeduct);
  UpdateVATOnLines(SalesHeader,SalesLine,TempVATAmountLine,DocumentType);
  BuildInvLineBuffer(SalesHeader,SalesLine,DocumentType,TempPrepmtInvLineBuffer,TRUE);

  **OnAfterBuildInvLineBuffer(VAR TempPrepmtInvLineBuffer,);**

  TempPrepmtInvLineBuffer.FIND('-');
  REPEAT
    LineCount := LineCount + 1;
   ...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
