### ISSUE TITLE
[Event Request] Table 23 - Vendor - OnBeforeGetVedorNoOpenCard

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4921]
Hi AL-Team,
can you please add the following Publisher in GetVendorNoOpenCard?

```
procedure GetVendorNoOpenCard(VendorText: Text[100]; ShowVendorCard: Boolean): Code[20]
    var
        Vendor: Record Vendor;
        VendorNo: Code[20];
        NoFiltersApplied: Boolean;
        VendorWithoutQuote: Text;
        VendorFilterFromStart: Text;
        VendorFilterContains: Text;
    begin
        // NEW >>>>
        OnBeforeGetVendorNoOpenCard(Rec, Vendor);
        // NEW <<<<
        if VendorText = '' then
            exit('');

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetVendorNoOpenCard(var Rec: Record Vendor; var Vendor: Record Vendor)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
