### ISSUE TITLE
[External Function] Codeunit 57 Document Totals: SalesDocTotalsNotUpToDate

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#4926]
We need that function as External.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
