### ISSUE TITLE
[Event Request] Codeunit 57 Document Totals: SalesDeltaUpdateTotals

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#4927]
Hello,
we need a new Event (like marked) in the last row of this function.

![salesdelta](https://user-images.githubusercontent.com/42680907/68942916-0d77a100-07aa-11ea-99fc-60ecff64498d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
