### ISSUE TITLE
[Event Request] Codeunit 57 Document Totals: PurchaseDeltaUpdateTotals

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#4928]
Hello,
we need a new Event in the last row of this function like mentioned below.

![purchdelta](https://user-images.githubusercontent.com/42680907/68943290-0c933f00-07ab-11ea-84b1-df233421b9a4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
