### ISSUE TITLE
[Event Change] Table 295 - Reminder Header

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4929]
Hi Al-team, 

We use the events from the functions GetNoSeriesCode and GetIssuingNoSeriesCode to overwrite the number series codes from the setup. If you also use these functions in the following places, we could completely outsource our customizations.

```
OnInsert()
SalesSetup.GET;
IF "No." = '' THEN BEGIN
  TestNoSeries;
  NoSeriesMgt.InitSeries(GetNoSeriesCode,xRec."No. Series","Posting Date","No.","No. Series");
END;
"Posting Description" := STRSUBSTNO(Text000,"No.");
IF ("No. Series" <> '') AND
    // NEW >>>>
    // (SalesSetup."Reminder Nos." = SalesSetup."Issued Reminder Nos.")
	(SalesSetup."Reminder Nos." = GetIssuingNoSeriesCode())
	// NEW <<<<
THEN
  "Issuing No. Series" := "No. Series"
ELSE
  // NEW >>>>
  // NoSeriesMgt.SetDefaultSeries("Issuing No. Series",SalesSetup."Issued Reminder Nos.");
  NoSeriesMgt.SetDefaultSeries("Issuing No. Series",GetIssuingNoSeriesCode());  
  // NEW <<<<
```

In table Finance Charge Memo Header(302) and table Delivery Reminder Header (5005270) it behaves in the same way.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
