### ISSUE TITLE
Codeunit 5056 Move Event OnAfterTransferFieldsFromCustToCont to next line

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#4930]

**Comment by mboon75** [comment]
Please move the OnAfterTransferFieldsFieldsFromCustToCont to next line or make the variable ContNo available to the subscriber
No we do not have access to the original contact number.
![image](https://user-images.githubusercontent.com/32514251/68946057-503d7700-07b2-11ea-92de-bea97e2cde4f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
