### ISSUE TITLE
[Event Request] Report 730 "Copy Item".

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#4932]
Hello.

We need a new event in Report 730 so that we can add tables to be copied after we know the Item to copy from (for better information to user) and before RUNMODAL gives us trouble:

...
**OnPreReport()**
CheckTargetItemNo;

IF NOT SourceItem.GET(SourceItem."No.") THEN
  ERROR(SourceItemDoesNotExistErr,SourceItem."No.");

IF (TargetItemNo = '') AND (TargetNoSeries = '') THEN
  ERROR(SpecifyTargetItemNoErr);

InvtSetup.GET;

**OnBeforeCopyItem(SourceItem."No."); // Call to new Publisher Event**

FOR i := 1 TO NumberOfCopies DO
  CopyItem(i);

CopySuccessful := TRUE;

**OnPostReport()**
...
**LOCAL [IntegrationEvent] OnBeforeCopyItem(FromItemNo : Code[20])**

**Comment by AlexanderYakunin** [comment]
We already have page 730 with needed extensibility in Master, please refer to this version for your development.

**Comment by KristjanGaukur** [comment]
Hmmm... Page 730 is connected to the Job table, and not Items.
How can I use that to extend Report 730 which is used to copy Items?
(In the Report Request Options Page there are a number of connected tables to the Item table selectable for "also copy" - and I need to add even more (of our own) tables to copy. How can I do that with Page 730?)

**Comment by KristjanGaukur** [comment]
Hi @AlexanderYakunin .
Did you see my reply? (I forgot to @ you in it.)

**Comment by AlexanderYakunin** [comment]
My mistake, page 729 "Copy Item". You can use page extension and few events for this page to extend with more tables.
