### ISSUE TITLE
[Event Requests] Codeunit 22 "Item Jnl.-Post Line": Need a pair of Events to handle "Cost is Adjusted"

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#4933]
Hello.

In Codeunit 22, in function SetOrderAdjmtProp we need **a pair of Events** to control (set, and then set back) the "Cost is Adjusted" field.

WITH InvtAdjmtEntryOrder DO
  IF GET(OrderType,OrderNo,OrderLineNo) THEN BEGIN
    IF "Allow Online Adjustment" OR "Cost is Adjusted" THEN BEGIN
      LOCKTABLE;
      **OnSetOrderBeforeCostIsAdjustedCheck(InvtAdjmtEntryOrder); // New event.**
      IF "Cost is Adjusted" THEN BEGIN
        "Cost is Adjusted" := FALSE;
        ModifyOrderAdjmt := TRUE;
      END;
      **OnSetOrderAfterCostIsAdjustedCheck(InvtAdjmtEntryOrder); // New event.**
      IF "Allow Online Adjustment" THEN BEGIN
        …
**LOCAL [IntegrationEvent] OnSetOrderBeforeCostIsAdjustedCheck(VAR InvtAdjmtEntryOrder : Record "Inventory Adjmt. Entry (Order)")**

**LOCAL [IntegrationEvent] OnSetOrderAfterCostIsAdjustedCheck(VAR InvtAdjmtEntryOrder : Record "Inventory Adjmt. Entry (Order)")**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
