### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post": Need to affect "Sales Line Disc. Account"

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#4934]
Hello.

In Codeunit 80, function FillInvoicePostingBuffer, we need to overwrite the GenPostingSetup."Sales Line Disc. Account" field with our own selected value, for posting.

…
IF SalesSetup."Discount Posting" IN
   [SalesSetup."Discount Posting"::"Line Discounts",SalesSetup."Discount Posting"::"All Discounts"]
THEN BEGIN
  CalcLineDiscountPosting(SalesHeader,SalesLine,SalesLineACY,InvoicePostBuffer);
  IF (InvoicePostBuffer.Amount <> 0) OR (InvoicePostBuffer."Amount (ACY)" <> 0) THEN BEGIN
    **OnFillInvoicePostingBufferOnSetAccount_u(SalesLine,GenPostingSetup); // New event**
    InvoicePostBuffer.SetAccount(
      GenPostingSetup.GetSalesLineDiscAccount,TotalVAT,TotalVATACY,TotalAmount,TotalAmountACY);
    InvoicePostBuffer.UpdateVATBase(TotalVATBase,TotalVATBaseACY);
    UpdateInvoicePostBuffer(TempInvoicePostBuffer,InvoicePostBuffer,TRUE);
  END;
END;
…
**LOCAL [IntegrationEvent] OnFillInvoicePostingBufferOnSetAccount_u(SalesLine : Record "Sales Line";VAR GenPostingSetup : Record "General Posting Setup")**

**Comment by AlexanderYakunin** [comment]
Why you need to do this? Can you simple update general posting setup data for you accounting regulation?

**Comment by KristjanGaukur** [comment]
We have an additional table with discount types, and based on the entry we find in this table we grab the Account No. we want to use for the discount type being posted. So, we are not just putting in one specific Account No,, but a variable one based on the discount type.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
