### ISSUE TITLE
[Event Request] XMLPort 5876 Import Phys. Invt. Recording - Phys. Invt. Record Line - Import::OnBeforeInsertRecord

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#4936]
I request 2 events in XMLPort 5876 on the Phys. Invt. Record Line - Import::OnBeforeInsertRecord-Trigger

Original:
PhysInvtRecordLine.MODIFY;

New:
OnImportOnBeforePhysInvtRecordLineMofify(PhysInvtRecordLine);
PhysInvtRecordLine.MODIFY;

Original:
PhysInvtRecordLine.INSERT;

New:
OnImportOnBeforePhysInvtRecordLineInsert(PhysInvtRecordLine);
PhysInvtRecordLine.INSERT;

Thank you for your attention.
Kind regards
Walter

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
