### ISSUE TITLE
EventRequest Table-83 -Item Journal line - Function- LookupItemNo()

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4937]
Kindly add below code in Table 83 Item Journal Line - LookupItemNo()  Function

IsHandled := FALSE;
OnBeforeLookupItemNo(Rec,IsHandled);
IF IsHandled THEN
  EXIT;

![image](https://user-images.githubusercontent.com/53224672/68993181-2d3ac200-089b-11ea-8fe5-7d87d6be8015.png)

**Comment by AlexanderYakunin** [comment]
This event already done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
