### ISSUE TITLE
EventRequest- Table- 5600- Fixed Asset- OnDelete trigger

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#4938]
Kindly add below code in Table 5600 Fixed Asset - OnDelete() Trigger
IsHandled := FALSE;
OnBeforeFADelete(Rec,IsHandled);
IF IsHandled THEN
EXIT

![image](https://user-images.githubusercontent.com/53224672/68993278-3710f500-089c-11ea-8eef-19aa047b6090.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
