### ISSUE TITLE
Please add a suppress option on the Confirms in the Assemble-to-Order Link table

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#4944]
Hi

In the Assemble-to-Order Link table (T904) there are three confimation questions to the user.  We would like a SetHideValidation function or something similar to be able to bypass these confirmations as we need to call the RollUpCosts and RollUpPrices from our extension without user interference.

Regards

Chris

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Mycoplasmm226** [comment]
Cncollins.....regards....you are guilty of illegally obtaining intrusion into another users Headdress to obtain personal information in which identify theft among 18 other charges were committed.
