### ISSUE TITLE
[Event Request] Table 37 Sales Line - CrossReferenceNoLookUp

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#4945]
We need a new event in Table 37;

**LOCAL [IntegrationEvent] OnAfterItemCrossReferenceFilter(VAR ItemCrossReference : Record "Item Cross Reference")**

Called from function CrossReferenceNoLookup - :

**[External] CrossReferenceNoLookUp()**
CASE Type OF
  Type::Item:
    BEGIN
      GetSalesHeader;
      ItemCrossReference.RESET;
      ItemCrossReference.SETCURRENTKEY("Cross-Reference Type","Cross-Reference Type No.");
      ItemCrossReference.SETFILTER(
        "Cross-Reference Type",'%1|%2',
        ItemCrossReference."Cross-Reference Type"::Customer,
        ItemCrossReference."Cross-Reference Type"::" ");
      ItemCrossReference.SETFILTER("Cross-Reference Type No.",'%1|%2',SalesHeader."Sell-to Customer No.",'');
      **_//INIT-INSERT
      OnAfterItemCrossReferenceFilter(ItemCrossReference");
      //END-INSERT_**
      IF PAGE.RUNMODAL(PAGE::"Cross Reference List",ItemCrossReference) = ACTION::LookupOK THEN BEGIN
        "Cross-Reference No." := ItemCrossReference."Cross-Reference No.";
        ValidateCrossReferenceNo(ItemCrossReference,FALSE);
        PriceCalcMgt.FindSalesLineLineDisc(SalesHeader,Rec);
        PriceCalcMgt.FindSalesLinePrice(SalesHeader,Rec,FIELDNO("Cross-Reference No."));
        OnCrossReferenceNoLookupOnBeforeValidateUnitPrice(SalesHeader,Rec);
        VALIDATE("Unit Price");
      END;
    END;
  Type::"G/L Account",Type::Resource:
    BEGIN
      GetSalesHeader;
      SalesHeader.TESTFIELD("Sell-to IC Partner Code");
      IF PAGE.RUNMODAL(PAGE::"IC G/L Account List",ICGLAcc) = ACTION::LookupOK THEN
        "Cross-Reference No." := ICGLAcc."No.";
    END;
END;

**Comment by TxusMoyano** [comment]
Sorry.  They are two parameters in the event:

**LOCAL [IntegrationEvent] OnAfterItemCrossReferenceFilter(SalesLine : Record "Sales Line";VAR ItemCrossReference : Record "Item Cross Reference")**

And in the call:

**//INIT-INSERT
OnAfterItemCrossReferenceFilter(Rec,ItemCrossReference);
//END-INSERT**

**Comment by AlexanderYakunin** [comment]
Event already exist
OnCrossReferenceNoLookUpOnAfterSetFilters(ItemCrossReference, Rec);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
