### ISSUE TITLE
Tables 36 and 38: Why are integration events set to OnPrem?

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#4946]
Talking about BC 15.2, in table 36 Sales Header, there are three events with Scope OnPrem:

```
    [IntegrationEvent(TRUE, false)]
    [Obsolete('Function scope will be changed to OnPrem')]
    procedure OnCheckSalesPostRestrictions()
    begin
    end;

    [IntegrationEvent(TRUE, false)]
    [Scope('OnPrem')]
    procedure OnCustomerCreditLimitExceeded()
    begin
    end;

    [IntegrationEvent(TRUE, false)]
    [Scope('OnPrem')]
    procedure OnCustomerCreditLimitNotExceeded()
    begin
    end;
```
On the purchase side, T38, we can find
```
    [IntegrationEvent(TRUE, false)]
    [Obsolete('Function scope will be changed to OnPrem')]
    procedure OnCheckPurchasePostRestrictions()
    begin
    end;
```

OnCheckSalesPostRestrictions and OnCheckPurchasePostRestrictions have been set to Obselete only recently.
I am subscribing to them in my SaaS app , and I wonder what to do now? Why are these OnPrem anyway?

**Comment by AlexanderYakunin** [comment]
@atoader - can you help to answer this question?

**Comment by atoader** [comment]
Hi! The Scope attribute applies to the procedure, not the event. Usually, these procedures should be local and invoked only from within the object. In certain cases, the event is invoked by another object so the method must be public. At the same time, we do not want extension to raise this event so the method is marked as OnPrem

**Comment by NKarolak** [comment]
Hi @atoader , please tell that the AL compiler ;-)
I do not want to raise the event; I am only subscribing to it:

![image](https://user-images.githubusercontent.com/34504100/69126553-c5f25d00-0aa8-11ea-8bde-1887fa99e24b.png)

**Comment by atoader** [comment]
Hi! I get the problem now. The obsolete message bubbles up to subscribers. The change to OnPrem will not break your code, but it will break any direct callers.

**Comment by atoader** [comment]
@thloke

**Comment by NKarolak** [comment]
@atoader, @thloke,  this is still not fixed in BC 16

**Comment by atoader** [comment]
We are aware of it. The bug has not been marked as in-progress and it is still on our backlog. I will be publishing a doc on our GitHub process in a few weeks to provide more clarity on how we accept bugs and when to expect the fixes.

**Comment by lthomsen** [comment]
@atoader This gives us a current fail on our appSource submission because it translates to a compile error on BC16. I understand that there's a timeline for bugfixes, but right now, you're effectively breaking my submission.
Please refer to Ryan Weigel from the appSource submission team for the submission error.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by atoader** [comment]
@lthomsen the warning above cannot break AppSource submissions. If the submission is still failing, please ask Ryan to CC me.
