### ISSUE TITLE
[Event Request] Table 5050 - Contact - CheckForExistingRelationships

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#4949]
We need a new event in table 5050 Contact: 

**LOCAL [IntegrationEvent] OnBeforeCheckForExistingRelationships(Contact : Record Contact;LinkToTable : ' ,Customer,Vendor,Bank Account';VAR IsHandled : Boolean)**

called from ChecForExistingRelationships function:

**[External] CheckForExistingRelationships(LinkToTable : ' ,Customer,Vendor,Bank Account')**
**_//INIT-INSERT
OnBeforeCheckForExistingRelationships(Rec,LinkToTable,IsHandled);
IF IsHandled THEN
  EXIT;
//END-INSERT_**
Contact := Rec;
ContBusRel."Link to Table" := LinkToTable;

IF "No." <> '' THEN BEGIN
  IF ContBusRel.FindByContact(LinkToTable,Contact."No.") THEN
    ERROR(
      AlreadyExistErr,
      Contact.TABLECAPTION,"No.",ContBusRel.TABLECAPTION,ContBusRel."Link to Table",ContBusRel."No.");
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
