### ISSUE TITLE
[Event Request] Table 5050 Contact - OnAfterShowCustVendBank

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#4950]
We need a new event in table 5050 Contact, named OnAfterShowCustVendBank:

**LOCAL [IntegrationEvent] OnAfterShowCustVendBank(VAR Contact : Record Contact;VAR ContBusRel : Record "Contact Business Relation";FormSelected : Integer)**

called from ShowCustVendBank function:

**[External] ShowCustVendBank()**
FormSelected := TRUE;

ContBusRel.RESET;

IF "Company No." <> '' THEN
  ContBusRel.SETFILTER("Contact No.",'%1|%2',"No.","Company No.")
ELSE
  ContBusRel.SETRANGE("Contact No.","No.");
ContBusRel.SETFILTER("No.",'<>''''');

CASE ContBusRel.COUNT OF
  0:
    ERROR(Text010,TABLECAPTION,"No.");
  1:
    ContBusRel.FINDFIRST;
  ELSE
    FormSelected := PAGE.RUNMODAL(PAGE::"Contact Business Relations",ContBusRel) = ACTION::LookupOK;
END;

IF FormSelected THEN
  CASE ContBusRel."Link to Table" OF
    ContBusRel."Link to Table"::Customer:
      BEGIN
        Cust.GET(ContBusRel."No.");
        PAGE.RUN(PAGE::"Customer Card",Cust);
      END;
    ContBusRel."Link to Table"::Vendor:
      BEGIN
        Vend.GET(ContBusRel."No.");
        PAGE.RUN(PAGE::"Vendor Card",Vend);
      END;
    ContBusRel."Link to Table"::"Bank Account":
      BEGIN
        BankAcc.GET(ContBusRel."No.");
        PAGE.RUN(PAGE::"Bank Account Card",BankAcc);
      END;
  END;
**_//INIT-INSERT
OnAfterShowCustVendBank(Rec,ContBusRel,FormSelected);
//END-INSERT_**

**Comment by TxusMoyano** [comment]
Sorry. The FormSelected parameter is **_Boolean_**

**LOCAL [IntegrationEvent] OnAfterShowCustVendBank(VAR Contact : Record Contact;VAR ContBusRel : Record "Contact Business Relation";FormSelected : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
