### ISSUE TITLE
[Extensibility / Enum Request] Page 9233 "G/L Balance by Dim. Matrix" Global var LineDimOption

### ISSUE THREAD

**Issue by wbor-nvt** [microsoft/ALAppExtensions#4951]
Hello,

Please provide a way to check the value of the global var "LineDimOption" on page 9233 "G/L Balance by Dim. Matrix" through a PageExtension.
Ideally we can check the value with an Enum, or maybe a protected var would work in this case?

**Comment by AlexanderYakunin** [comment]
Hello, please be more specific and explain what you are going to achieve? There is no variable LineDimOption, but LineDimCode. There is also option DimOption: Option "G/L Account",Period,"Business Unit","Dimension 1","Dimension 2". Let me know what should be extended?

**Comment by wbor-nvt** [comment]
In the BC15.1, this option is still split in the LineDimOption & ColumnDimOption
![image](https://user-images.githubusercontent.com/53901977/71086337-002f4700-219a-11ea-9118-c958863b36fe.png)
I assume the DimOption will be enough.

In my case I have a PageExtension and I want to display extra fields depending on the value of this Option. (e.g. show some extra information on the G/L Account). Of course I want to hide these fields if the page is not using G/L Accounts. I need a way to check the current value of this global variable.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
