### ISSUE TITLE
Revenue and Vat checklist Report display error

### ISSUE THREAD

**Issue by RishtaCader** [microsoft/ALAppExtensions#4953]
Hello,

I'm having an issue while generating the report "Revenue and Vat Checklist" on the Cronus BE Company.
Environment Information: Business Central Saas 
Version: 15.0.36560.0
Localisation: Belgium (BE)

The pdf or excel is not generating, and while previewing it i got the error message below:

![image](https://user-images.githubusercontent.com/40292845/69135894-55146a80-0ad3-11ea-92ec-20e73bb5dd3e.png)

![image](https://user-images.githubusercontent.com/40292845/69135855-41690400-0ad3-11ea-978c-d7dab4729752.png)

Regards,
Rishta

**Comment by AlexanderYakunin** [comment]
This area is not suitable for reporting bugs, please use technical support or create ticket online.
