### ISSUE TITLE
T38 RecreatePurchLines extend OnBeforeRecreatePurchLines with handler

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#4959]
Hi,
we would like to skip and exit from T38 - funtion RecreatePurchLines here: 
![image](https://user-images.githubusercontent.com/53824412/69160187-6c5e5280-0ae9-11ea-9c11-b7e41ebe4d1e.png)

OnBeforeRecreatePurchLines should contain also some variable IsHandle, as we can write our code below and exit the rest of the function.

**Comment by AlexanderYakunin** [comment]
Please look into 15.X release first. You  may change your design after that. FYI - we do not provide events for 14.X.

**Comment by AlexanderYakunin** [comment]
Please create new request based on 15.X code base.
