### ISSUE TITLE
[Function expose] : Codeunit 8800 Custom Layout Reporting

### ISSUE THREAD

**Issue by AMCJN** [Microsoft/ALAppExtensions#496]
Hi,

Can 2 functions in codeunit 8800 Custom Layout Reporting please be external ?

Function InitializeData
Function ProcessReport

Thanks.

**Comment by IhorHandziuk** [comment]
Thank you for your request. 
We are now working on a greater effort with replacing/refactoring file usages in the base application (which will affect this functionality). The intent is to deliver it in the next major release (Spring). 
Please, wait until we complete this task.
