### ISSUE TITLE
Codeunit 99000854 OnBeforeForecastConsumption Add Parameters

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#4960]
In Codeunit 99000854 OnBeforeForecastConsumption from #4746 can we add CurrForecast, ExcludeForecastBefore, UseParm, and LineNo to the function.  

    local procedure ForecastConsumption(var DemandInvtProfile: Record "Inventory Profile"; var Item: Record Item; OrderDate: Date; ToDate: Date) UpdatedOrderDate: Date
    var
        ForecastEntry: Record "Production Forecast Entry";
        ForecastEntry2: Record "Production Forecast Entry";
        NextForecast: Record "Production Forecast Entry";
        CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
        TotalForecastQty: Decimal;
        ReplenishmentLocation: Code[10];
        ForecastExist: Boolean;
        NextForecastExist: Boolean;
        ReplenishmentLocationFound: Boolean;
        ComponentForecast: Boolean;
        ComponentForecastFrom: Boolean;
        IsHandled: Boolean;             // NEW
    begin
        // NEW+
        OnBeforeForecastConsumption(DemandInvtProfile,Item,OrderDate,ToDate,UpdatedOrderDate,IsHandled,CurrForecast,ExcludeForecastBefore,UseParm,LineNo);
        if IsHandled then
            exit;
        // NEW-

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeForecastConsumption(var DemandInvtProfile: Record "Inventory Profile"; var Item: Record Item; OrderDate: Date; ToDate: Date; var UpdatedOrderDate: Date; var IsHandled: Boolean; var CurrForecast: Code[10]; var ExcludeForecastBefore: Date; var UseParm: Boolean; var LineNo: Integer)
    begin
    end;
    // NEW -

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
