### ISSUE TITLE
Marketing Setup - AddLast

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#4961]
Following the recommendations to better use AddLast / AddFirst instead of AddBefore / AddAfter with an anchor, I was wondering how I could add a group on the Marketing Seyup page?

![image](https://user-images.githubusercontent.com/25268332/69170507-79377200-0afa-11ea-8aee-43aefa595b62.png)

Using addlast(Content) does not seem to work, since it is added after the systemparts. Should the systemparts not be added in a separate area(factboxes) instead?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
