### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line AppliedEntriesToReadjust()

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4964]
We need to be able to effect whether or not "Applied Entry to Adjust" and ModifyEntry is set to true in the UpdateItemLedgEntry function of the Item Jnl.-Post Line codeunit.

We are requesting an event be added in the AppliedEntriesToReadjust function to allow this manipulation.

Example:
Local AppliedEntriesToReadjust(ItemLedgEntry : Record "Item Ledger Entry") : Boolean
*** New Event Code***
OnBeforeAppliedEntriesToReadjust(ItemLegEntry : Record "Item Ledger Entry", var Result : Boolean, var IsHandled : Boolean);
If IsHandled then
   Exit(Result);
*** New Code End***

With ItemLedgEntry Do
   Exit("Entry Type" IN  ["Entry Type"::Output, "Entry Type"::"Assembly Output"]);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
