### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line OnAfterUndoQuantityPosting

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4965]
We perform additional functionality using the ItemJnlLine and Item Ledger Entry records.

Could you please add another parameter to the OnAfterUndoQuantityPosting event for the ItemJnlLine variable within the UndoQuantityPosting function of the Item Jnl.-Post Line codeunit?

It does not need to be passed in by var.

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
