### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line UpdateUnitCost

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#4966]
Within the UpdateUnitCost function of the Item Jnl.-Post Line codeunit, we only update the LastDirectCost for an Inbound entry under certain conditions.

We are requesting a way to handle this within the OnUpdateUnitCostOnBeforeCalculateLastDirectCost event and bypass the base functionality.

Example:
![image](https://user-images.githubusercontent.com/31968749/69185617-1ab3c900-0ae5-11ea-8c3f-0fef99805a4a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
