### ISSUE TITLE
[Event Request] Codeunit 407 (Adjust Gen. Journal Balance): OnBeforeInsertGenJournalLine

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#4968]
Codeunit 407 (Adjust Gen. Journal Balance)

**Integration Event Definition:**
```
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertGenJournalLine(var GenJournalLine: Record "Gen. Journal Line"; GenJournalLine2: Record "Gen. Journal Line"; PrevGenJournalLine2: Record "Gen. Journal Line")
begin
end;
```

**Invocation in InsertCorrectionLines function:**
```
"Recurring Frequency" := PrevGenJnlLine2."Recurring Frequency";
"Posting No. Series" := PrevGenJnlLine2."Posting No. Series";
OnBeforeInsertGenJournalLine(NewGenJnlLine,GenJnlLine2,PrevGenJnlLine2);
if TempCurrTotalBuffer."Total Amount (LCY)" <> 0 then
    Insert;
```
This will permit us to set some custom fields during this process.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
