### ISSUE TITLE
CU 99000845 "Reservation Management" - Event OnBeforeAutoReserve<...> : add First/Search parameters

### ISSUE THREAD

**Issue by xgaronnat** [Microsoft/ALAppExtensions#497]
Hi,

On triggers OnBeforeAutoReserveTransLine (and other similar events), could you add Search and NextStep parameters to let us change the FIND behaviour (seek First or Last record).

Thanks,
Xavier.

ps : IMOO NextStep should be deducted from Search value

**Comment by xgaronnat** [comment]
Hi,
Search and NextStep parameters are not in VAR so useless... 
Could you change it for next CU ?
Thanks,
Xavier.

**Comment by xgaronnat** [comment]
Hi,
Any chance to see Search and NextStep passed as VAR parameters ?
Thanks,
Xavier.

**Comment by rvanbekkum** [comment]
@xgaronnat I think you need to open a new issue for that, because comments seem to be usually ignored.
