### ISSUE TITLE
[Event Request] Codeunit 90 (Purch.-Post): OnCheckReleasedStatus

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#4975]
Please add a **OnCheckReleasedStatus** integration event to Codeunit 90 (Purch.-Post)

We would like to remove the requirement that the Purchase Document has been Released in order to preview posting.

**Integration Event Definition:**
```
[IntegrationEvent(false, false)]
local procedure OnCheckReleasedStatus(PurchaseHeader: Record "Purchase Header"; PreviewMode: Boolean; var IsHandled: Boolean)
begin
end;
```

**Invocation in ReleasePurchDocument function:**
```
        LinesWereModified := ReleasePurchaseDocument.ReleasePurchaseHeader(PurchHeader, PreviewMode);
        if LinesWereModified then
            RefreshTempLines(PurchHeader, TempPurchLineGlobal);
======> OnCheckReleasedStatus(PurchHeader,PreviewMode,IsHandled);
======> if not IsHandled then
            TestField(Status, Status::Released);
======> IsHandled := false;
        Status := PrevStatus;
        RestorePurchaseHeader(PurchHeader, PurchaseHeaderCopy);
        if not PreviewMode then begin
```

**Comment by AlexanderYakunin** [comment]
We have solution for this here
    local procedure TestStatusRelease(PurchHeader: Record "Purchase Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeTestStatusRelease(PurchHeader, IsHandled);
        if not IsHandled then
            PurchHeader.TestField(Status, PurchHeader.Status::Released);
    end;
