### ISSUE TITLE
[Event Request] Codeunit 80 (Sales-Post): OnCheckReleasedStatus

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#4976]
Please add a **OnCheckReleasedStatus** integration event to Codeunit 80 (Sales-Post)

We would like to remove the requirement that the Sales Document has been Released in order to preview posting.

**Integration Event Definition:**
```
[IntegrationEvent(false, false)]
local procedure OnCheckReleasedStatus(SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var IsHandled: Boolean)
begin
end;
```

**Invocation in ReleaseSalesDocument function:**
```
        LinesWereModified := ReleaseSalesDocument.ReleaseSalesHeader(SalesHeader, PreviewMode);
        if LinesWereModified then
            RefreshTempLines(SalesHeader, TempSalesLineGlobal);
======> OnCheckReleasedStatus(SalesHeader,PreviewMode,IsHandled);
======> if not IsHandled then
            TestField(Status, Status::Released);
======> IsHandled := false;
        Status := PrevStatus;
        RestoreSalesHeader(SalesHeader, SalesHeaderCopy);
        if not PreviewMode then begin
```

**Comment by AlexanderYakunin** [comment]
We already have solution for this here
    local procedure TestStatusRelease(SalesHeader: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeTestStatusRelease(SalesHeader, IsHandled);
        if not IsHandled then
            SalesHeader.TestField(Status, SalesHeader.Status::Released);
    end;
