### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeValidateBillToName

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4979]
Hi AL-Team,

can you please add the following Publisher to Bill-to Name OnValidate?

 ```
trigger OnValidate()
            var
                Customer: Record Customer;
            begin
                // NEW >>>>
                OnBeforeValidateBillToName(Rec, Customer);
                // NEW <<<<
                if ShouldLookForCustomerByName("Bill-to Customer No.") then 
                ....
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateBillToName(var Rec: Record "Sales Header"; var Customer: Record Customer)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
