### ISSUE TITLE
[EventRequest] Codeunit 7010 - FindPurchLinePrice

### ISSUE THREAD

**Issue by JulianSheeper** [Microsoft/ALAppExtensions#498]
Hi,

we need a new event in Codeunit 7010 to override the FindPurchLinePrice behaviour.
It needs to have **GlobalVarAccess set to Yes/True** because we need to modify the Vendor in the event subscriber.
I suggest the following new event:

![image](https://user-images.githubusercontent.com/11839572/49351685-be576e00-f708-11e8-9f3b-32b46611741f.png)

Thanks,
Julian

**Comment by JesperSchulz** [comment]
Seems like this request wasn't picked up by our work item creation automatisation. I will try to re-tag the issue. Sorry for the delay!

**Comment by AlexanderYakunin** [comment]
I think you can use existing events here

LOCAL PurchLinePriceExists(PurchHeader : Record "Purchase Header";VAR PurchLine : Record "Purchase Line";ShowAll : Boolean) : Boolean
WITH PurchLine DO
  IF (Type = Type::Item) AND Item.GET("No.") THEN BEGIN
    IsHandled := FALSE;
    **OnBeforePurchLinePriceExists(PurchLine,PurchHeader,TempPurchPrice,ShowAll,IsHandled);**
    IF NOT IsHandled THEN
      FindPurchPrice(
        TempPurchPrice,"Pay-to Vendor No.","No.","Variant Code","Unit of Measure Code",
        PurchHeader."Currency Code",PurchHeaderStartDate(PurchHeader,DateCaption),ShowAll);
    **OnAfterPurchLinePriceExists(PurchLine);**
    EXIT(TempPurchPrice.FIND('-'));
  END;
EXIT(FALSE);
