### ISSUE TITLE
T38 - RecreatePurchLines handling of PurchLine."Drop Shipment" AND PurchLine."Special Order"

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#4981]
in Tbale 38 in function RecreatePurchLines  we need to handle "Drop Shipment" and "Special Order" but case conditions are now well because he included Service Header in Purchase. Maybe you can think about including some Variants in some new event publisher like OnHandleDropShipmentAndSpecialOrder and include handler to skip standard testfields, because we want to skip it in case of Service (we have extended Purchase line with field "Purchasing Code Source"::Service,Sales). Described in picture:
![image](https://user-images.githubusercontent.com/53824412/69240539-ff0bf980-0b9c-11ea-80af-39e24c62248e.png)

Thank you in advance

**Comment by AlexanderYakunin** [comment]
Please use 15.X code and specify event and it's location in the code. When it can be processed as event-request for 15.X. Without this information we have to classify it as Extensibility Requests and it will take more time and will not be delivered in 15.X but for next version only.

**Comment by VladimirVeljovic** [comment]
So, on Table 38 in function RecreatePurchLines we have a lot of checks it PurchaseLine is for "Drop Shipment" or "Special Order" and we would like to handle it.
Old code:
![image](https://user-images.githubusercontent.com/53824412/71438983-11c3a200-26f8-11ea-911a-3a87ea4bec0f.png)
New Code:
![image](https://user-images.githubusercontent.com/53824412/71439163-d7a6d000-26f8-11ea-8cc6-a18a0a9f5f91.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
