### ISSUE TITLE
T38 - function TransferSavedFieldsDropShipment needed events OnBefore and OnAfter

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#4982]
Hi,
we want to include some code OnBefore and OnAfter TransferSavedFieldsDropShipment so we would like to have events there with handlers. In goal to check what will execute on Special order or something else.
![image](https://user-images.githubusercontent.com/53824412/69241410-0b915180-0b9f-11ea-8a8a-532f4624fec1.png)

**Comment by AlexanderYakunin** [comment]
Please provide event definition and placing

**Comment by VladimirVeljovic** [comment]
OnBeforeTransferSavedFieldsDropShipment/OnAfterTransferSavedFieldsDropShipment
and
OnBeforeTransferSavedFieldsSpecialOrder/OnAfterTransferSavedFieldsSpecialOrder

![image](https://user-images.githubusercontent.com/53824412/69409080-96da2680-0d08-11ea-8c61-554a3531eef6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
