### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeLookupCity

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#4983]
Hi AL-Team,
can you please add the following Publisher in City OnLookup Trigger?

```
            trigger OnLookup()
            begin
                // NEW >>>>
                OnBeforeLookupCity(Rec, PostCode);
                // NEW <<<<
                                PostCode.LookupPostCode("Ship-to City", "Ship-to Post Code", "Ship-to County", "Ship-to Country/Region Code");
            end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupCity(var Rec: Record "Sales Header"; var PostCode: Record "Post Code")
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
We don't have field City in Sales Header, we have Sell-to, Bill-to and Ship-to City. Please correct you request.

**Comment by MattiLE** [comment]
Hi Alexander, sorry for the unclear description. The Publisher should be inserted at Ship-to City. I've modified the request.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
