### ISSUE TITLE
[Event Request] Base Application, Codeunit 130411 “Sys. Warmup Scenarios”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#4985]
[Event Request] Base Application, Codeunit 130411 “Sys. Warmup Scenarios”

Could you please insert an Initialize-Call at the beginning of test procedure WarmupInvoicePosting and an Initialize procedure like in other testfunctions?
![Pic1](https://user-images.githubusercontent.com/45795262/69251029-09d08980-0bb1-11ea-94e1-6c9683402a18.jpg)

Example from other test function
![Pic2](https://user-images.githubusercontent.com/45795262/69251062-17860f00-0bb1-11ea-9c51-86be442a7939.jpg)
![Pic3](https://user-images.githubusercontent.com/45795262/69251072-1b199600-0bb1-11ea-97e8-18dcfbb86ac2.jpg)

**Comment by AlexanderYakunin** [comment]
This is special internal codeunit, what do you want to do here?

**Comment by JoergPernberg** [comment]
We insert all test codeunits in our default test suite.
In the OnTestInitialize-Subscriber we do some solution specific setup.

If the event is raised, the test will run successful in our solution.

**Comment by AlexanderYakunin** [comment]
We cannot make this change as this codeunit run without access to test libraries in our infrastructure.
