### ISSUE TITLE
[Event Request] Base Application, Codeunit 134262 "Bank Pmt. Appl. Tolerance"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#4986]
[Event Request] Base Application, Codeunit 134262 "Bank Pmt. Appl. Tolerance"
![Pic1](https://user-images.githubusercontent.com/45795262/69251396-9b3ffb80-0bb1-11ea-934f-2077fbbe8b46.jpg)

Could you please insert an Initialize-Call at the beginning of all test procedures in the codeunit and an Initialize procedure like in other test codeunits?
![Pic2](https://user-images.githubusercontent.com/45795262/69251425-a85cea80-0bb1-11ea-94a2-0da71416f9c5.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by JoergPernberg** [comment]
Is there anything new about this issue? Still waiting for the event in BC16 CU1.
