### ISSUE TITLE
[Event Request] Application Tests-Bank, Codeunit 134267 "Payment Proposal UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#4987]
[Event Request] Application Tests-Bank, Codeunit 134267 "Payment Proposal UT"
![Pic1](https://user-images.githubusercontent.com/45795262/69251711-1ef9e800-0bb2-11ea-98e8-bb681f1fcf9f.jpg)

Could you please insert an OnTestInitialize at the beginning of the procedure Initialize?
![Pic2](https://user-images.githubusercontent.com/45795262/69251730-27522300-0bb2-11ea-8224-596cf8d498be.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
