### ISSUE TITLE
[Event Request] Application Tests-Bank, Codeunit 134268 "Payment Proposal UT 2"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#4988]
[Event Request] Application Tests-Bank, Codeunit 134268 "Payment Proposal UT 2"
![Pic1](https://user-images.githubusercontent.com/45795262/69251907-6e401880-0bb2-11ea-928c-01cc22cec99f.jpg)

Could you please insert an OnTestInitialize at the beginning of the procedure Initialize?

![Pic2](https://user-images.githubusercontent.com/45795262/69251938-7a2bda80-0bb2-11ea-9ab9-5e399915a06b.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
