### ISSUE TITLE
[Event Request] Application Tests-Bank, Codeunit 134269 "Matching on Payment Discounts"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#4989]
[Event Request] Application Tests-Bank, Codeunit 134269 "Matching on Payment Discounts"
![Pic1](https://user-images.githubusercontent.com/45795262/69252054-b52e0e00-0bb2-11ea-818b-e531a1222687.jpg)

Could you please insert an OnTestInitialize at the beginning of the procedure Initialize?
![Pic2](https://user-images.githubusercontent.com/45795262/69252075-be1edf80-0bb2-11ea-8c6e-1d7115e9b388.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
