### ISSUE TITLE
[EventRequest] Report 99001025 “Refresh Production Order” on procedure "Production Order - OnAfterGetRecord"

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#4990]
Please add a new publisher event OnBeforeCalcRoutingCalcComponent in Report 99001025 on function "Production Order - OnAfterGetRecord" and call it as shown in the image below
![image](https://user-images.githubusercontent.com/26144133/69817463-f0f05580-11fa-11ea-9a26-bad82eaa6219.png)

Please add the corresponding Integration Event In the bottom of the report
`LOCAL [IntegrationEvent] OnBeforeCalcRoutingCalcComponent(ProdOrder : Record "Production Order";VAR ProdOrderLine : Record "Prod. Order Line";VAR CalcComponents : Boolean;VAR CalcRoutings : Boolean, VAR SkipLine)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
