### ISSUE TITLE
TAB60 OnBeforeSaveFileToClient

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#4991]
Please add following Event

OnBeforeSaveFileToClient(ReportUsage, RecordVariant, DocNo, DocName, ToCust, ServerFilePath, ClientFilePath, HandledL);

LOCAL [IntegrationEvent] OnBeforeSaveFileToClient(ReportUsage : Integer;RecordVariant : Variant;DocNo : Code[20];DocName : Text[150];ToCust : Code[20];VAR ServerFilePath : Text;VAR ClientFilePath : Text;VAR Handled : Boolean)

**Comment by AlexanderYakunin** [comment]
We do not implement with server file path due to security limitations
