### ISSUE TITLE
[Event Request] Codeunit 1101 CA Jnl.-Check Line - OnBeforeRunCheck

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#4992]
We need a new event function in CU 1101 "CA Jnl.-CheckLine", named OnBeforeRunCheck

**LOCAL [IntegrationEvent] OnBeforeRunCheck(VAR CostJnlLine : Record "Cost Journal Line")**

called from RunCheck Function:

**[External] RunCheck(VAR CostJnlLine : Record "Cost Journal Line")**
**_//INIT-INSERT
OnBeforeRunCheck(CostJnlLine);
//END-INSERT_**
WITH CostJnlLine DO BEGIN
  TESTFIELD("Posting Date");
  TESTFIELD("Document No.");

  SourceCodeSetup.GET;
  TESTFIELD(Amount);
  IF ("Cost Type No." = '') AND (
........
........
........

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
