### ISSUE TITLE
Table 99000832 VerifyChange, request new publishers onBefore and OnAfter

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#4994]
Hi, we would like to make additional conditions for triggering ReserveSalesLine.VerifyChange from table 37 OnModify trigger. We can control and solve our problem with adding new onBefore event in table 99000832 in funtion VerifyChange. Also we would neet IsHandled and CurrentFieldNo to control from were we want to trigger our conditions.

**Comment by AlexanderYakunin** [comment]
CurrentFieldNo is not available in scope of SalesLineReserve codeunit. And not useful in OnModify trigger of table Sales Line. Please create new request with required event definition/parameters/placement in the code. This requests cannot be processed.
