### ISSUE TITLE
[Event Request] Page 1208 Direct Debit Collect. Entries - OnBeforeCheckSEPA

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#4995]
We need a new event function in Page 1208 "Direct Debit Collect. Entries", named OnBeforeCheckSEPA, with a local variable IsHandled of boolean:

**LOCAL [IntegrationEvent] OnBeforeCheckSEPA(VAR DirectDebitCollectionEntry : Record;VAR IsHandled : Boolean)**

called from:

**OnModifyRecord() : Boolean**
TESTFIELD(Status,Status::New);
CALCFIELDS("Direct Debit Collection Status");
TESTFIELD("Direct Debit Collection Status","Direct Debit Collection Status"::New);
**_//INIT-INSERT
IsHandled:=FALSE;
OnBeforeCheckSEPA(Rec,IsHandled);
IF NOT IsHandled then
//END-INSERT_**
CODEUNIT.RUN(CODEUNIT::"SEPA DD-Check Line",Rec);
HasLineErrors := HasPaymentFileErrors;

**Comment by TxusMoyano** [comment]
**LOCAL [IntegrationEvent] OnBeforeCheckSEPA(VAR DirectDebitCollectionEntry : Record "Direct Debit Collection Entry";VAR IsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
