### ISSUE TITLE
T37 - OnDelete event needed before function CleanSpecialOrderFieldsAndCheckAssocPurchOrder

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#4996]
Hi,
if its possible we need event  on t37 right before funtion CleanSpecialOrderFieldsAndCheckAssocPurchOrder  because we want to control delete and clean with connected special order. Example: 

![image](https://user-images.githubusercontent.com/53824412/69341741-693ea000-0c6a-11ea-8383-da0ebc8de8cf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
