### ISSUE TITLE
T37 OnDelete event needed for extending SalesLine filter

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#4997]
Hi,
we need on T37 OnDelete event is needed for extending SalesLine filter:

before:
![image](https://user-images.githubusercontent.com/53824412/69341947-ca667380-0c6a-11ea-9c96-8b41c437484c.png)

after our change:
![image](https://user-images.githubusercontent.com/53824412/69342468-ecacc100-0c6b-11ea-82aa-39fbadf7c3c9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
