### ISSUE TITLE
[Event Request] Codeunit 5057 VendCont-Update - OnBeforeTransferFieldsFromVendToCont

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#4998]
We need a new Event function in Codeunit 5057 "VendCont-Update", named OnBeforeTransferFieldsFromVendToCont:

**LOCAL [IntegrationEvent] OnBeforeTransferFieldsFromVendToCont(VAR Contact : Record Contact;Vendor : Record Vendor)**

called from:

**[External] OnModify(VAR Vend : Record Vendor)**
WITH ContBusRel DO BEGIN
  SETCURRENTKEY("Link to Table","No.");
  SETRANGE("Link to Table","Link to Table"::Vendor);
  SETRANGE("No.",Vend."No.");
  IF NOT FINDFIRST THEN
    EXIT;
  Cont.GET("Contact No.");
  OldCont := Cont;
END;

ContNo := Cont."No.";
NoSeries := Cont."No. Series";
SalespersonCode := Cont."Salesperson Code";
**_//INIT-INSERT
OnBeforeTransferFieldsFromVendToCont(Cont,Vend);
//END-INSERT_**
Cont.VALIDATE("E-Mail",Vend."E-Mail");
Cont.TRANSFERFIELDS(Vend);
OnAfterTransferFieldsFromVendToCont(Cont,Vend);
Cont."No." := ContNo ;
Cont."No. Series" := NoSeries;
Cont."Salesperson Code" := SalespersonCode;
Cont.VALIDATE(Name);
Cont.OnModify(OldCont);
Cont.MODIFY(TRUE);

Vend.GET(Vend."No.");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
