### ISSUE TITLE
[Event Request] Page 345 OnBeforeSaveNetChange

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#4999]
Please add a new Event trigger OnBeforeSaveNetChange on page 345:

LOCAL SaveNetChange(AccType : Integer;AccNo : Code[20];NetChange : Decimal)
//++++++++++++++++++++++++++++
OnBeforeSaveNetChange(VAR Rec: "G/L Account Net Change"; GenJnlLine: Record "Gen. Journal Line"; AccType : Integer;AccNo : Code[20];NetChange : Decimal)
//----------------------------
IF AccNo = '' THEN
  EXIT;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
