### ISSUE TITLE
[Event Request] OnAfterNoOnAfterValidate on Pages 46, 47, 54, 55, 95-98, 508,510 , 6651, 6661

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5001]
Please enter a new Event trigger OnAfterNoOnAfterValidate in the corrsponding subpages, so that we can react on the Event before other Code execution is done later:

LOCAL NoOnAfterValidate()
InsertExtendedText(FALSE);
IF (Type = Type::"Charge (Item)") AND ("No." <> xRec."No.") AND
   (xRec."No." <> '')
THEN
  CurrPage.SAVERECORD;

SaveAndAutoAsmToOrder;

IF Reserve = Reserve::Always THEN BEGIN
  CurrPage.SAVERECORD;
  IF ("Outstanding Qty. (Base)" <> 0) AND ("No." <> xRec."No.") THEN BEGIN
    AutoReserve;
    CurrPage.UPDATE(FALSE);
  END;
END;

//++++++++++++++++++++++++++++++++++++++
OnAfterNoOnAfterValidate(VAR rec);
//--------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
