### ISSUE TITLE
[Event Request] Codeunit 5631 FA Jnl.-Check Line - OnCheckConsistencyOnBeforeCheckQuantity

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5002]
There is a event call in Codeunit 5631 "FA Jnl.-Check Line" named OnCheckConsistencyOnBeforeCheckQuantity, in function CheckConsistency:

**LOCAL CheckConsistency()**
IF GenJnlPosting THEN
  WITH GenJnlLine DO BEGIN
    IF "Journal Template Name" = '' THEN
      Quantity := 0;
    FieldErrorText :=
      STRSUBSTNO(Text011,
        FIELDCAPTION("FA Posting Type"),"FA Posting Type");
    IF ("FA Error Entry No." > 0) AND ("FA Posting Type" = "FA Posting Type"::Maintenance) THEN
      FIELDERROR("FA Error Entry No.",FieldErrorText);
    IF "FA Posting Type" <> "FA Posting Type"::"Acquisition Cost" THEN
      CASE TRUE OF
        "Depr. Acquisition Cost":
          FIELDERROR("Depr. Acquisition Cost",FieldErrorText);
        "Salvage Value" <> 0:
          FIELDERROR("Salvage Value",FieldErrorText);
        "Insurance No." <> '':
          FIELDERROR("Insurance No.",FieldErrorText);
        Quantity <> 0:
          BEGIN
            **_IsHandled := FALSE;
            OnCheckConsistencyOnBeforeCheckQuantity(GenJnlLine,IsHandled);
            IF NOT IsHandled THEN_**
              IF "FA Posting Type" <> "FA Posting Type"::Maintenance THEN
                FIELDERROR(Quantity,FieldErrorText);
          END;
      END;
.........
..........
..........

**We need the same check in the "IF NOT GenJnlPosting" block of code:**

**LOCAL CheckConsistency()**
IF GenJnlPosting THEN
  WITH GenJnlLine DO BEGIN
    IF "Journal Template Name" = '' THEN
      Quantity := 0;
    FieldErrorText :=
      STRSUBSTNO(Text011,
        FIELDCAPTION("FA Posting Type"),"FA Posting Type");
    IF ("FA Error Entry No." > 0) AND ("FA Posting Type" = "FA Posting Type"::Maintenance) THEN
      FIELDERROR("FA Error Entry No.",FieldErrorText);
    IF "FA Posting Type" <> "FA Posting Type"::"Acquisition Cost" THEN
      CASE TRUE OF
        "Depr. Acquisition Cost":
          FIELDERROR("Depr. Acquisition Cost",FieldErrorText);
        "Salvage Value" <> 0:
          FIELDERROR("Salvage Value",FieldErrorText);
        "Insurance No." <> '':
          FIELDERROR("Insurance No.",FieldErrorText);
        Quantity <> 0:
          BEGIN
            IsHandled := FALSE;
            OnCheckConsistencyOnBeforeCheckQuantity(GenJnlLine,IsHandled);
            IF NOT IsHandled THEN
              IF "FA Posting Type" <> "FA Posting Type"::Maintenance THEN
                FIELDERROR(Quantity,FieldErrorText);
          END;
      END;
    IF ("FA Posting Type" <> "FA Posting Type"::Maintenance) AND
       ("Maintenance Code" <> '')
    THEN
      FIELDERROR("Maintenance Code",FieldErrorText);
    IF "FA Posting Type" = "FA Posting Type"::Maintenance THEN BEGIN
      IF "Depr. until FA Posting Date" THEN
        FIELDERROR("Depr. until FA Posting Date",FieldErrorText);
    END;
    IF ("FA Posting Type" <> "FA Posting Type"::Depreciation) AND
       ("FA Posting Type" <> "FA Posting Type"::"Custom 1") AND
       ("No. of Depreciation Days" <> 0)
    THEN
      FIELDERROR("No. of Depreciation Days",FieldErrorText);
    IF "FA Posting Type" = "FA Posting Type"::Disposal THEN BEGIN
      IF "FA Reclassification Entry" THEN
        FIELDERROR("FA Reclassification Entry",FieldErrorText);
      IF  "Budgeted FA No." <> '' THEN
        FIELDERROR("Budgeted FA No.",FieldErrorText);
    END;
    FieldErrorText := STRSUBSTNO(Text012,
        FIELDCAPTION("Account No."),FA.FIELDCAPTION("Budgeted Asset"));
    IF FA."Budgeted Asset" AND ("Budgeted FA No." <> '') THEN
      FIELDERROR("Budgeted FA No.",FieldErrorText);
    IF ("FA Posting Type" = "FA Posting Type"::"Acquisition Cost") AND
       ("Insurance No." <> '') AND
       (DeprBook.Code <> FASetup."Insurance Depr. Book")
    THEN
      TESTFIELD("Insurance No.",'');
    IF FA."Budgeted Asset" THEN
      FIELDERROR("Account No.",STRSUBSTNO(Text013,FA.FIELDCAPTION("Budgeted Asset")));
  END;

**_IF NOT GenJnlPosting THEN_**
  WITH FAJnlLine DO BEGIN
    FieldErrorText :=
      STRSUBSTNO(Text011,
        FIELDCAPTION("FA Posting Type"),"FA Posting Type");
    IF ("FA Error Entry No." > 0) AND ("FA Posting Type" = "FA Posting Type"::Maintenance) THEN
      FIELDERROR("FA Error Entry No.",FieldErrorText);
    IF "FA Posting Type" <> "FA Posting Type"::"Acquisition Cost" THEN
      CASE TRUE OF
        "Depr. Acquisition Cost":
          FIELDERROR("Depr. Acquisition Cost",FieldErrorText);
        "Salvage Value" <> 0:
          FIELDERROR("Salvage Value",FieldErrorText);
        Quantity <> 0:
          **_//INIT-INSERT
            IsHandled := FALSE;
            OnCheckConsistencyOnBeforeCheckQuantity(GenJnlLine,IsHandled);
            IF NOT IsHandled THEN
          //END-INSERT_**
          IF "FA Posting Type" <> "FA Posting Type"::Maintenance THEN
            FIELDERROR(Quantity,FieldErrorText);
        "Insurance No." <> '':
          FIELDERROR("Insurance No.",FieldErrorText);
      END;
    IF ("FA Posting Type" = "FA Posting Type"::Maintenance) AND
       "Depr. until FA Posting Date"
    THEN
      FIELDERROR("Depr. until FA Posting Date",FieldErrorText);
    IF ("FA Posting Type" <> "FA Posting Type"::Maintenance) AND
       ("Maintenance Code" <> '')
    THEN
      FIELDERROR("Maintenance Code",FieldErrorText);
    IF ("FA Posting Type" <> "FA Posting Type"::Depreciation) AND
       ("FA Posting Type" <> "FA Posting Type"::"Custom 1") AND
       ("No. of Depreciation Days" <> 0)
    THEN
      FIELDERROR("No. of Depreciation Days",FieldErrorText);
    IF "FA Posting Type" = "FA Posting Type"::Disposal THEN BEGIN
      IF "FA Reclassification Entry" THEN
        FIELDERROR("FA Reclassification Entry",FieldErrorText);
      IF  "Budgeted FA No." <> '' THEN
        FIELDERROR("Budgeted FA No.",FieldErrorText);
    END;
    FieldErrorText := STRSUBSTNO(Text012,
        FIELDCAPTION("FA No."),FA.FIELDCAPTION("Budgeted Asset"));
    IF FA."Budgeted Asset" AND ("Budgeted FA No." <> '') THEN
      FIELDERROR("Budgeted FA No.",FieldErrorText);
    IF ("FA Posting Type" = "FA Posting Type"::"Acquisition Cost") AND
       ("Insurance No." <> '') AND
       (DeprBook.Code <> FASetup."Insurance Depr. Book")
    THEN
      TESTFIELD("Insurance No.",'');
  END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
