### ISSUE TITLE
Breaking-Changes - "Email Item".GetBodyText

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5003]
`"Method 'GetBodyText' is marked for removal. Reason: Function scope will be changed to OnPrem"
`

What will be the replacement for Saas?

**Comment by AlexanderYakunin** [comment]
@Jesper

**Comment by mazhelez** [comment]
Hey @fvet 

The function is question was never meant to be exposed for extensions development. Currently, there is no alternative.
