### ISSUE TITLE
Selected Items List Refreshing when using Search - Select Items Page

### ISSUE THREAD

**Issue by Kushal5** [microsoft/ALAppExtensions#5004]
The users are able to select multiple items from “Select Items” functionality in Sales Order, sales invoice and sales quote. 

However, once the users search for a different items on the “Select Items Page”, the items that was selected previously are unchecked and it does not appear on the sales order. 

Is it possible to select the items and even search and select the new items and all items are populated in the sales order, sales invoice and sales quote?

**Comment by AlexanderYakunin** [comment]
This question is not related to AL Extensibility, please raise this issue via technical support (if you think this is a bug) or use aka.ms/bcideas to suggest this improvement.
