### ISSUE TITLE
T38 OnRecreatePurchLinesOnBeforeInsertPurchLine include parameter ChangedFieldName

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5005]
for our process we need the parameter in event OnRecreatePurchLinesOnBeforeInsertPurchLine (located in function RecreatePurchLines).
Also in function TransferSavedFields we need the same parameter ChangedFieldName

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
