### ISSUE TITLE
T38 RecreatePurchLines event needed if Attach to Line No is deferent then 0.

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5006]
Hi 

we need event in funtion RecreatePurchLines if IF TempPurchLine."Attached to Line No." <> 0  

we already created ours:

![image](https://user-images.githubusercontent.com/53824412/69421632-d4977900-0d21-11ea-91ec-a5b0cc423e5f.png)

**Comment by AlexanderYakunin** [comment]
This event placed after condition and work independently of  TempPurchLine."Attached to Line No." value. Is this correct?

Also please use 15.X code base. You can add needed event, test it and then make request with exact event specification.

**Comment by VladimirVeljovic** [comment]
hi, yes thats true. i already implemented publisher as it is described in the picture

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
