### ISSUE TITLE
Codeunit 80 - UpdateBlanketOrderLine Change of functionality

### ISSUE THREAD

**Issue by MarceldeWinter** [microsoft/ALAppExtensions#5007]
Hello,

In the UpdateBlanketOrderLine function there is a test for the sell-to customer no.  
We need to have the option to skip this check on the sell-to customer no because multiple customers can make use of the same blanket order in our add-on.

![CU80](https://user-images.githubusercontent.com/32643781/69426699-1d552f00-0d2e-11ea-9e39-df4e2952a6de.JPG)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
