### ISSUE TITLE
EventRequest-CodeUnit90

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#5008]
CU 90 - Purch.-Post - function CheckAndUpdate()
Require an event after the code
SourceCodeSetup.GET;
  SrcCode := SourceCodeSetup.Purchases;

**OnAfterSrcCodeInitialize(PurchHeader,SrcCode);**

![image](https://user-images.githubusercontent.com/53224672/69479228-fa577780-0e20-11ea-8808-3ba16b22949d.png)

**Comment by AlexanderYakunin** [comment]
We already have this event
            OnCheckAndUpdateOnAfterSetSourceCode(PurchHeader, SourceCodeSetup, SrcCode);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
