### ISSUE TITLE
Ability to send e-mail from Business Central

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#5009]
Currently SMTP functionality can be used to send e-mails from the base application in Business Central. This integrates with for instance posted sales documents. We use the functionality heavily and it has been working without problems. 

There are now however safer method(s) to send e-mails, a lot has happened since SMTP has been introduced in the 80's. Is it possible to provide us with functionality that integrates with the standard application (for f.i. sending Sales Invoices) that makes use of those safer method(s)?

The reason I'm asking this is that it seems that SMTP doesn't work in combination with two-factor auth. We found this out because of the new requirements for all CSP's to enable two-factor authentication for all users. The only way we could send e-mails from Business Central now is when we enable legacy applications for an account. Can two-factor auth also be taken into account when considering this request?

**Comment by darjoo** [comment]
Hi @Pieter-kok, we do support accounts with MFA. However you are required to use an App password. The following are some documentation to help you with this.

https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-setup-email
https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq#can-i-use-multi-factor-authentication
https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords

If you have further issues, please re-open the issue.

-Darrick

**Comment by pieter-kok** [comment]
According to our tests, the app passwords only work when ‘enable legacy applications’ is enabled. Can you please elaborate on your statement?

**Comment by pieter-kok** [comment]
Hi @darjoo 

According to our tests, the app passwords only worked when ‘enable legacy applications’ is enabled. Can you please elaborate on your statement? 

We are aware that app passwords should work, but they didn’t.

**Comment by darjoo** [comment]
Hi @pieter-kok,

What do you mean by 'enable legacy applications'? This isn't a setting that I know of unfortunately.

By using the https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords documentation, you'd be able to set up an App Password for the specific account. But I assume you already knew that, I'm unclear as to what elaboration you're looking for.

**Comment by pieter-kok** [comment]
Hi @darjoo,

We created an app password again for SMTP this morning to check whether it started working.
This wasn't the case.

When we disable the baseline policy: Block legacy authentication (see: attachments), the app password works. As a CSP we are not allowed to disable this policy. But with this policy enabled we cannot make use of the SMTP functionality of Business Central.

![Baseline Policy](https://user-images.githubusercontent.com/34770900/70782380-282c3e00-1d87-11ea-91f4-b77a3679db56.jpg)

![Block Legacy Application](https://user-images.githubusercontent.com/34770900/70782390-2bbfc500-1d87-11ea-98a7-f3d0af0a9322.jpg)

The kind of elaboration I was looking for is some guidance with this problem. Our perception is that app passwords don't work with this policy enabled. What can we do as a CSP to both apply to Microsoft policy and make use of Business Central at the same time.

We would also encourage development of a standard e-mail functionality using Graph instead of SMTP, as an alternative to this old protocol.

**Comment by darjoo** [comment]
Hi @pieter-kok,
Thanks for the additional information. I'll investigate into that setting and if we have any workaround this.

**Comment by markmlandman** [comment]
@darjoo keep in mind that there are other issues with the SMTP functionality. This issue is blocking, but having no control regarding the sender and no insight in the send emails is also a hassle.
