### ISSUE TITLE
[Parameters] PAG 344 OnBeforeNavigateShowRecords

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5010]
Extension to #4118 

Please also add following variables to OnBeforeNavigateShowRecords with VAR access.

- SISalesHeader
- SCMSalesHeader

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
