### ISSUE TITLE
[Parameters] PAG 344 OnAfterNavigateFindRecords

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5011]
In PAG 344, OnAfterNavigateFindRecords, we would like to have VAR access to following parameters:

- var SalesInvHeader: Record "Sales Invoice Header"
- var SalesCrMemoHeader: Record "Sales Cr.Memo Header"
- var PurchInvHeader: Record "Purch. Inv. Header"
- var PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."
- var SISalesHeader: Record "Sales Header"
- var SCMSalesHeader: Record "Sales Header"

This is the code we would like to achieve:
```
[EventSubscriber(Objecttype::Page, 344, 'OnAfterNavigateFindRecords', '', false, false)]
    local procedure OnAfterNavigateFindRecords(var DocumentEntry: Record "Document Entry"; DocNoFilter: Text; PostingDateFilter: Text; var SalesInvHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; var SISalesHeader: Record "Sales Header"; var SCMSalesHeader: Record "Sales Header")
    begin
        NavigateSISalesHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true, SISalesHeader);
        NavigateSCMSalesHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true, SCMSalesHeader);
        NavigateSalesInvoiceHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true, SalesInvHeader);
        NavigateSalesCrMemoHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true, SalesCrMemoHeader);
        NavigatePIPurchaseHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true);
        NavigatePCMPurchaseHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true);
        NavigatePurchPreInvHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true);
        NavigatePurchPreCrMemoHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true);
        NavigatePurchInvHeader(DocumentEntry, DocNoFilter, PostingDateFilter, true, PurchInvHeader);
        NavigatePurchCrMemoHdr(DocumentEntry, DocNoFilter, PostingDateFilter, true, PurchCrMemoHeader);
    end;
```

**Comment by AlexanderYakunin** [comment]
If you want to extend this page using page extension, we can make these vars protected. Then they will be available in your extension like global before. Is this ok for you?

**Comment by AlexanderYakunin** [comment]
We cannot change parameter signature to VAR without strong justification (this may be breaking change for others). Provided code sample does not help to understand why do you need VAR. Please provide explanation.

**Comment by fvet** [comment]
@AlexanderYakunin 

_I cannot make the mod via a page extension, only via the subscribers in a codeunit ..._

**Usecase**
Our add-on introduces a new entity 'Transport Order'. Using the standard Navigate functionality, we've included all our custom transaction / document tables, so users can search on 'Document No.' = 'Transport Order No.'.

In addition, searching on 'Transport Order No.' should also return all sales / purchase / invoices / credit memos that have a link to this transport order.

Searching on a document no (invoice number) 'A' will by default return the 'Sales Invoice A' in Business Central. However, in our add-on, searching on a document no (transport order) 'B', should also return 'Sales Invoice A' (when linked with transport order B)

**Implementation**
- OnAfterNavigateFindRecords: Here we search on our custom tables + would like to apply a filter (thus VAR access) on e.g. Sales Invoice Header 
- If any invoice matches the filters, SetSourceForSales is called
```
if NoOfRecords(DATABASE::"Sales Invoice Header") = 1 then begin
            SalesInvHeader.FindFirst; // ERROR occurs here
            SetSource(
              SalesInvHeader."Posting Date", Format("Table Name"), SalesInvHeader."No.",
              1, SalesInvHeader."Bill-to Customer No.");
        end;
```

--> If the SalesInvHeader would not have been set by var, an error will occur / wrong result on the SalesInvHeader.FINDFIRST line. Therefore we'd like to be able to overrule the filters set.

Having our custom filters, we could benefit from standard functionality such as **ShowRecords** as well, to show the result on matching sales invoices, instead of having to duplicate lots of the existing page code.


PS: Looking to this from another perspective, we might imagine another extension allowing to navigate by 'Purchase Order No.' and return a list of orders + receipts (using marks) + invoices (using marks).

**Comment by AlexanderYakunin** [comment]
I'd suggest you design you own related documents search for Transport order.

**Comment by fvet** [comment]
Will do so. 
Too bad one missing parameter forces us to fully deprecate or redesign our extension...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
