### ISSUE TITLE
[Application] Consistent actions on Sales / Purchase

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5012]
Following #3771

BC 15.1 contains a fix for the **Posted Purchase Invoice** page.
However, the Posted Purchase Invoice**s** page has not been reviewed.

Page PostedSalesInvoices contains following code:

```
trigger OnAction()
                var
                    SalesInvHeader: Record "Sales Invoice Header";
                begin
                    SalesInvHeader := Rec; // = CORRECT
                    CurrPage.SetSelectionFilter(SalesInvHeader);
                    SalesInvHeader.PrintRecords(true);
                end;
```

Page PostedPurchaseInvoices still misses the fix:

```
trigger OnAction()
                var
                    PurchInvHeader: Record "Purch. Inv. Header";
                begin
                    PurchInvHeader:= Rec; // = TO FIX > PLEASE ADD THIS LINE 
                    CurrPage.SetSelectionFilter(PurchInvHeader);
                    PurchInvHeader.PrintRecords(true);
                end;

```
PS: Please also check for the purchase credit memos too.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
