### ISSUE TITLE
Expose several functions in Codeunit 7000 - Sales Price Calc. Mgt.

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#5014]
Please expose the following functions in codeunit 7000:
- ConvertPriceToVAT
- SetCurrency
- SetVAT
- SetUoM

Thank you for your attention.

**Comment by AlexanderYakunin** [comment]
All these procedures are external.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
