### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeValidateAppliesToDocNo

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5016]
Hi AL-Team,

can you please add the following Publisher to Applies-to Doc. No. OnValidate? 

trigger OnValidate()
            begin
                // NEW >>>> 
                OnBeforeValidateAppliesToDocNo(Rec, CustLedgEntry);
                // NEW <<<<
                if "Applies-to Doc. No." <> '' then
                    TestField("Bal. Account No.", '');

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateAppliesToDocNo(var Rec: Record "Sales Header"; var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
