### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeLookupShipToPostCode

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5017]
Hi AL-Team,
can you please add the following Publisher in Ship-to Post Code OnLookup Trigger?

  trigger OnLookup()
            begin
                // NEW >>>>
                OnBeforeLookupShipToPostCode(Rec, PostCode);
                // NEW <<<< 
                PostCode.LookupPostCode("Ship-to City", "Ship-to Post Code", "Ship-to County", "Ship-to Country/Region Code");
            end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupShipToPostCode(var Rec: Record "Sales Header"; var PostCode: Record "Post Code")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
