### ISSUE TITLE
[EventRequest] Codeunit 80 "Sales Post", PostItemCharge [local] 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5018]
Please Extend with 3 parameter:
- TempItemChargeAssgntSales
- SalesLine
- ItemLedgEntryNo

on publisher event OnAfterPostItemCharge on trigger PostItemCharge() and call it as shown in the picture below in the end of the function

![image](https://user-images.githubusercontent.com/54017538/69527668-149e6c00-0f6d-11ea-9e07-8d442bd906f6.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/69527703-208a2e00-0f6d-11ea-8b68-7d40342279f4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
