### ISSUE TITLE
[EventRequest] Codeunit 80 "Sales Post", PostUpdateOrderLine[local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5019]
Extend with 1 parameter: on publisher event OnBeforePostUpdateOrderLine
- SalesSetup (as VAR)
 on trigger PostUpdateOrderLine() and call it as shown in the picture below in the end of the function

![image](https://user-images.githubusercontent.com/54017538/69527936-9db5a300-0f6d-11ea-83cc-cfa4bade1bee.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/69527964-a60dde00-0f6d-11ea-953e-41851b9ea382.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
