### ISSUE TITLE
[Function Expose] Page 5471 RegisterFieldSet

### ISSUE THREAD

**Issue by BartPermentier** [Microsoft/ALAppExtensions#502]
Hey,

could you please expose the function RegisterFieldSet so that we can add fields to this page with pageextensions.

**Comment by AndersLarsenMicrosoft** [comment]
The pages of type API are intended to be extended as we would like them to identical across tenants. You can however create your own API as an extension. 
Thanks
Anders

**Comment by JesperSchulz** [comment]
The fix was rejected. I've removed the "ships-in-future-update" tag to reflect the correct status.
