### ISSUE TITLE
[EventRequest] Codeunit 90 "PurchPost", PostUpdateOrderLine[local] 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5020]
On publisher event OnBeforePostUpdateOrderLine please change parameter PurchSetup To VAR
in trigger PostUpdateOrderLine in codeunit 90

![image](https://user-images.githubusercontent.com/54017538/69528306-4401a880-0f6e-11ea-8b48-8fa2b99b4b89.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/69528331-4cf27a00-0f6e-11ea-977c-8940a4d5ffa5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
