### ISSUE TITLE
[EventRequest] Report 5753 " GetSourceDocument", Warehouse Request OnAfterGetRecord() [External] 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5021]
Please Extend with 1 parameter:
- OneHeaderCreated 

in publisher event OnBeforeWarehouseRequestOnAfterGetRecord in report 5753 on trigger Warehouse Request - OnAfterGetRecord()

Please add the extra parameter in corresponding Integration Event In the bottom of the report in:

LOCAL [IntegrationEvent] OnBeforeWarehouseRequestOnAfterGetRecord(VAR WarehouseRequest : Record "Warehouse Request";VAR WhseHeaderCreated : Boolean;VAR SkipRecord : Boolean;VAR BreakReport : Boolean;RequestType : 'Receive,Ship';VAR WhseReceiptHeader :

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
