### ISSUE TITLE
[EventRequest] Table 37 " Sales Line.", GetSalesHeader [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5028]
In table 37 please extend publisher OnBeforeGetSalesHeader with 1 parameter
Extend with 1 parameter:
- Currency (As VAR)

And add it aswell in the event as shown in the picture 

![image](https://user-images.githubusercontent.com/54017538/69538350-5ede1800-0f82-11ea-84ff-5d49d7d76424.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
