### ISSUE TITLE
[EventRequest] Table 5741 " TransferLine.", GetTransHeader [External]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5029]
In the table TransferLine on Trigger GetTransHeader extend it with the publisher OnBeforeGetTransHeader with 3 new parameters
- TransferLine (as VAR)
- TransferHeader (as VAR)
- IsHandled (as VAR)

an do it for the publisher event aswell as shown in the picture 

![image](https://user-images.githubusercontent.com/54017538/69538952-bcbf2f80-0f83-11ea-8c98-f90068e0ffd2.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
