### ISSUE TITLE
[Event Request] Codeunit 8 AccSchedManagement - CalcCell 

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#5032]
Hi,
can you please add the following Publisher in CalcCell?

procedure CalcCell(var AccSchedLine: Record "Acc. Schedule Line"; var ColumnLayout: Record "Column Layout"; CalcAddCurr: Boolean): Decimal
    var
        Result: Decimal;
    begin
        // begin
        OnBeforeCalcCell(AccSchedLine,ColumnLayout,CalcAddCurr);
        //end
        AccountScheduleLine.CopyFilters(AccSchedLine);
....................................

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcCell(VAR AccSchedLine : Record "Acc. Schedule Line";VAR ColumnLayout : Record "Column Layout";CalcAddCurr : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
