### ISSUE TITLE
[Event Request] Codeunit 8 AccSchedManagement - CalcCellValue

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#5033]
Hi,
can you please add the following Publisher in CalcCellValue?

      procedure CalcCellValue(AccSchedLine: Record "Acc. Schedule Line"; ColumnLayout: Record "Column Layout"; CalcAddCurr: Boolean): Decimal
    var
        GLAcc: Record "G/L Account";
        CostType: Record "Cost Type";
        CFAccount: Record "Cash Flow Account";
        Result: Decimal;
    begin
        Result := 0;
        // new
       OnBeforeCalcCellValue(AccSchedLine,ColumnLayout,CalcAddCurr,Result);

        if AccSchedLine.Totaling = '' then
            exit(Result);
......................
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcCellValue(VAR AccSchedLine : Record "Acc. Schedule Line";VAR ColumnLayout : Record "Column Layout";CalcAddCurr : Boolean;VAR Result : Decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
