### ISSUE TITLE
[Event Request] Codeunit 80 - PostItemJnlLine

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#5036]
Hi,
can you please add the following Publisher in PostItemJnlLine? Thanks

      local procedure PostItemJnlLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; QtyToBeShipped: Decimal; QtyToBeShippedBase: Decimal; QtyToBeInvoiced: Decimal; QtyToBeInvoicedBase: Decimal; ItemLedgShptEntryNo: Integer; ItemChargeNo: Code[20]; TrackingSpecification: Record "Tracking Specification"; IsATO: Boolean): Integer
.........  
          
            if ItemChargeNo <> '' then begin
                "Item Charge No." := ItemChargeNo;
                SalesLine."Qty. to Invoice" := QtyToBeInvoiced;
                // new
                OnPostItemJnlLineCopyItemCharge(ItemJnlLine,TempItemChargeAssgntSales);
            end else
                "Applies-from Entry" := SalesLine."Appl.-from Item Entry";

...........................

    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineCopyItemCharge(VAR ItemJournalLinePar : Record "Item Journal Line";VAR ItemChargeAssignmentSalesPar : Record "Item Charge Assignment (Sales)")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
