### ISSUE TITLE
[Event Request] Codeunit 90 - PostItemJnlLine

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#5037]
Hi,
can you please add the following Publisher in PostItemJnlLine? Thanks

        local procedure PostItemJnlLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; QtyToBeReceived: Decimal; QtyToBeReceivedBase: Decimal; QtyToBeInvoiced: Decimal; QtyToBeInvoicedBase: Decimal; ItemLedgShptEntryNo: Integer; ItemChargeNo: Code[20]; TrackingSpecification: Record "Tracking Specification"): Integer
...............................

            if ItemChargeNo <> '' then begin
                "Item Charge No." := ItemChargeNo;
                PurchLine."Qty. to Invoice" := QtyToBeInvoiced;
                // new
                OnPostItemJnlLineCopyItemCharge(ItemJnlLine,TempItemChargeAssgntPurch);
            end;

......................................

    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineCopyItemCharge(VAR ItemJournalLinePar : Record "Item Journal Line";VAR ItemChargeAssignmentPurchPar : Record "Item Charge Assignment (Purch)")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
