### ISSUE TITLE
AA0137 unused Variables in Caption Class

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/ALAppExtensions#5038]
Hallo,

I have a problem with the code analyser AA0137 in combination with CaptionClass. I created a Page with a label 
`QtyPicked: Label 'Qty. Picked (%1)';`
and a field
```
field("Calc Qty Picked"; CalcQtyPicked)
 {
   Caption = 'Qty. Picked';
   CaptionClass = StrSubstNo(QtyPicked, UnitofMeasure.Description);
   DecimalPlaces = 0 : 5;
   Editable = false;
}
```
My problem is, that I got a Error with "Variable 'QtyPicked' is unused in 'Page'. AL(AA0137)

**Comment by AlexanderYakunin** [comment]
@MarcHansenMicrosoft

**Comment by MarcHansenMicrosoft** [comment]
This is already fixed
