### ISSUE TITLE
EventRequest-CodeUnit-96- function- CreatePurchHeader

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#5039]
Kindly add below code in CodeUnit 96 Purch.-Quote to Order - CreatePurchHeader Function.

  PurchOrderHeader."No." := '';
  PurchOrderHeader."Quote No." := "No.";

  **

> **OnBeforePurchOrderInit(PurchOrderHeader,PurchHeader);**

**

  PurchOrderHeader.InitRecord;
  PurchOrderLine.LOCKTABLE;
  PurchOrderHeader.INSERT(TRUE);

![image](https://user-images.githubusercontent.com/53224672/69625790-57476d80-106d-11ea-97a2-f2195cbe3325.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
