### ISSUE TITLE
[Event Request] Application “Tests-CRM Integration”, Codeunit 139183 "CRM Integration Mapping"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5042]
[Event Request] Application “Tests-CRM Integration”, Codeunit 139183 "CRM Integration Mapping"
![Pic1](https://user-images.githubusercontent.com/45795262/69635852-9a95e200-1055-11ea-96a6-f1698c2efae1.png)

Could you please insert an OnTestInitialize-Raiser at the beginning of the procedure Initialize?

![Pic2](https://user-images.githubusercontent.com/45795262/69635856-9e296900-1055-11ea-917a-b29c9dcbd3dd.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
