### ISSUE TITLE
[Event Request] Application “Tests-CRM Integration”, Codeunit 139175 "CRM Sales Order Integr. 

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5043]
[Event Request] Application “Tests-CRM Integration”, Codeunit 139175 "CRM Sales Order Integr. Test"
![Pic1](https://user-images.githubusercontent.com/45795262/69636048-07a97780-1056-11ea-9945-63d0e04ef0bb.png)

Could you please insert an OnTestInitialize-Raiser at the beginning of the procedure Initialize?
![Pic2](https://user-images.githubusercontent.com/45795262/69636051-0a0bd180-1056-11ea-8b64-487f234de16f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
