### ISSUE TITLE
[Event Request] Application “Tests-CRM Integration”, Codeunit 139173 "CRM Synch. Helper Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5044]
[Event Request] Application “Tests-CRM Integration”, Codeunit 139173 "CRM Synch. Helper Test"
![Pic1](https://user-images.githubusercontent.com/45795262/69636167-4b03e600-1056-11ea-8ce0-81967b453b85.png)

Could you please insert an OnTestInitialize-Raiser at the beginning of the following procedures?
-	TestUpdateCRMInvoiceStateActive
-	TestUpdateCRMInvoiceStatePaid
-	TestUpdateCRMInvoiceStatePartial
-	TestUpdateCRMInvoiceWithCreateBillsPaymentMethod
![Pic2](https://user-images.githubusercontent.com/45795262/69636175-4f300380-1056-11ea-8a65-2e3c0f458a23.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
