### ISSUE TITLE
[Event Request] Application “Tests-CRM Integration”, Codeunit 139162 "CRM Integration Mgt Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5045]
[Event Request] Application “Tests-CRM Integration”, Codeunit 139162 "CRM Integration Mgt Test"
![Pic1](https://user-images.githubusercontent.com/45795262/69636304-90281800-1056-11ea-98c6-ff5bc0da4fda.png)

Could you please insert an OnTestInitialize at the beginning of the procedure Initialize?

![Pic2](https://user-images.githubusercontent.com/45795262/69636306-928a7200-1056-11ea-9ad2-851f58c49ea3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
