### ISSUE TITLE
[Event Request] Application “Tests-CRM Integration”, Codeunit 139161 "CRM Integration Record 

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5046]
[Event Request] Application “Tests-CRM Integration”, Codeunit 139161 "CRM Integration Record Test"

![Pic1](https://user-images.githubusercontent.com/45795262/69636431-e1380c00-1056-11ea-9f25-d384b1346674.png)

Could you please insert an OnTestInitialize at the beginning of the procedure RemovalOfCoupledSalesHeaderWithLinesIsNotBlocked?

![Pic2](https://user-images.githubusercontent.com/45795262/69636439-e39a6600-1056-11ea-8e65-528e88991c3c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
