### ISSUE TITLE
[Event Request] Application “Tests-Cash Flow”, Codeunit 135203 "CF Frcst. Azure AI"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5047]
[Event Request] Application “Tests-Cash Flow”, Codeunit 135203 "CF Frcst. Azure AI"

![Pic1](https://user-images.githubusercontent.com/45795262/69636543-1f353000-1057-11ea-81d6-848699745589.png)

Could you please insert an OnTestInitialize at the beginning of the procedure Initialize?

![Pic2](https://user-images.githubusercontent.com/45795262/69636549-22302080-1057-11ea-9958-c0bdab89a04e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
