### ISSUE TITLE
[Event Change] Table 5065 - Interaction Log Entry - OnOpenAttachmentOnBeforeShowAttachment

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5048]
Hi Al-team, 
can you please pass the Segment Line record parameter as var in the following publishers?

```
    [IntegrationEvent(false, false)]
    local procedure OnOpenAttachmentOnBeforeShowAttachment(var InteractionLogEntry: Record "Interaction Log Entry";var SegmentLine: Record "Segment Line"; var Attachment: Record Attachment)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
