### ISSUE TITLE
Codeunit 5058 BankCont-Update

### ISSUE THREAD

**Issue by cmuris** [microsoft/ALAppExtensions#5049]
We need the following event in function InsertNewContact:

  SetSkipDefault;
  _OnBeforeContactInsert(Cont, BankAcc);_
  Insert(true);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeContactInsert(var Contact: Record Contact; BankAccount: Record "Bank Account")
    begin
    end;

there is a related request #3941 which isn't shipped yet. 

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
