### ISSUE TITLE
[Event Request] Codeunit 60 Sales-Calc. Discount - Handling service charge

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#5051]
Can you tell me when you will handle issue #2980? It is labeled as refactoring maybe that is why it is delayed? In my opinion it is just moving 2 bits of same code to a function that will not change functionality so it may not need a refactoring label. 

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
