### ISSUE TITLE
Event Request CodeUnit-230 GenJnlManagement - Function-TemplateSelection

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#5052]
Kindly add below event at the end of function- TemplateSelection  - CodeUnit 230 -GenJnlManagement - 

**OnAfterTemplateSelection(GenJnlTemplate,GenJnlLine,JnlSelected,OpenFromBatch);**

![image](https://user-images.githubusercontent.com/53224672/69698551-9926f100-110b-11ea-8114-3971a0ee63ee.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
