### ISSUE TITLE
Event Request CodeUnit-230 GenJnlManagement - Function-GetAccounts

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#5053]
Kindly add below event at the function- GetAccounts - CodeUnit 230 -GenJnlManagement -

OnAfterGetGLAccName(GenJnlLine,AccName);

![image](https://user-images.githubusercontent.com/53224672/69701742-a21bc080-1113-11ea-8ccd-431974ea9023.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
