### ISSUE TITLE
Event Request CodeUnit-230 GenJnlManagement - Function-GetAccounts

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#5054]
Kindly add below event at the end of function- GetAccounts - CodeUnit 230 -GenJnlManagement -

OnAfterGetGLBalAccName(GenJnlLine,BalAccName);

![image](https://user-images.githubusercontent.com/53224672/69701849-e7d88900-1113-11ea-9f30-4e33daeb2164.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by pradeepmn91** [comment]
can you kindly update release date for this EventRequest
