### ISSUE TITLE
EventRequest Codeunit 7030 - OnAfterAddSegLinetoTargetGr

### ISSUE THREAD

**Issue by cmuris** [microsoft/ALAppExtensions#5056]
We need the fowolling Event

    [IntegrationEvent(false, false)]
    local procedure OnAfterAddSegLinetoTargetGroup(var CampaignTargetGroup: Record "Campaign Target Group"; var SegmentLine: Record "Segment Line")
    begin
    end;

called here:
procedure AddSegLinetoTargetGr

            if ("Campaign No." <> '') and "Campaign Target" then begin
                ContBusRel.SetCurrentKey("Link to Table", "Contact No.");
                ContBusRel.SetRange("Link to Table", ContBusRel."Link to Table"::Customer);
                ContBusRel.SetRange("Contact No.", "Contact Company No.");
                if ContBusRel.FindFirst then
                    InsertTargetGroup(CampaignTargetGr.Type::Customer, ContBusRel."No.", "Campaign No.")
                else
                    InsertTargetGroup(
                      CampaignTargetGr.Type::Contact, "Contact Company No.", "Campaign No.");
                //New Event
                OnAfterAddSegLinetoTargetGroup(CampaignTargetGr, SegLine);
                //New Event
            end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
