### ISSUE TITLE
[Event Request] Table 7311 - Warehouse Journal Line - OnBeforeCheckBinOutbound

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5058]
Hi AL-Team,
can you please add the following Publisher with Handled Pattern to CheckBin?

local procedure CheckBin(LocationCode: Code[10]; BinCode: Code[20]; Inbound: Boolean)
    var
        BinContent: Record "Bin Content";
        WhseJnlLine: Record "Warehouse Journal Line";
        // NEW >>>>
        HandledOutbound: Boolean;
        // NEW <<<<
    begin
        if (BinCode <> '') and ("Item No." <> '') then begin
            GetLocation(LocationCode);
            if BinCode = Location."Adjustment Bin Code" then
                exit;
            BinContent.SetProposalMode(StockProposal);
            if Inbound then begin
                GetBinType(LocationCode, BinCode);
                if Location."Bin Capacity Policy" in
                   [Location."Bin Capacity Policy"::"Allow More Than Max. Capacity",
                    Location."Bin Capacity Policy"::"Prohibit More Than Max. Cap."]
                then begin
                    WhseJnlLine.SetCurrentKey("To Bin Code", "Location Code");
                    WhseJnlLine.SetRange("To Bin Code", BinCode);
                    WhseJnlLine.SetRange("Location Code", LocationCode);
                    WhseJnlLine.SetRange("Journal Template Name", "Journal Template Name");
                    WhseJnlLine.SetRange("Journal Batch Name", "Journal Batch Name");
                    WhseJnlLine.SetRange("Line No.", "Line No.");
                    WhseJnlLine.CalcSums("Qty. (Absolute)", Cubage, Weight);
                end;
                if BinContent.Get(
                     "Location Code", BinCode, "Item No.", "Variant Code", "Unit of Measure Code")
                then
                    BinContent.CheckIncreaseBinContent(
                      "Qty. (Absolute, Base)", WhseJnlLine."Qty. (Absolute, Base)",
                      WhseJnlLine.Cubage, WhseJnlLine.Weight, Cubage, Weight, false, false)
                else begin
                    GetBin(LocationCode, BinCode);
                    Bin.CheckIncreaseBin(
                      BinCode, "Item No.", "Qty. (Absolute)",
                      WhseJnlLine.Cubage, WhseJnlLine.Weight, Cubage, Weight, false, false);
                end;
            end else begin
                // NEW >>>>
                OnBeforeCheckBinOutbound(Rec, HandledOutbound)
                if not HandledOutbound then begin
                    // NEW <<<<
                    BinContent.Get(
                      "Location Code", BinCode, "Item No.", "Variant Code", "Unit of Measure Code");
                    if BinContent."Block Movement" in [
                                                       BinContent."Block Movement"::Outbound, BinContent."Block Movement"::All]
                    then
                        if not StockProposal then
                            BinContent.FieldError("Block Movement");
                // NEW >>>>
                end;
                // NEW <<<<
            end;
            BinContent.SetProposalMode(false);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckBinOutbound(var Rec: Record "Warehouse Journal Line"; var HandledOutbound: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
