### ISSUE TITLE
[Event Request] Table 83 - Item Journal Line - OnBeforeDisplayErrorIfItemIsBlocked

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5059]
Hi AL-Team,
can you please add the following Publisher with Handled Pattern to DisplayErrorIfItemIsBlocked?

```
procedure DisplayErrorIfItemIsBlocked(Item: Record Item)
    var
        Handled: Boolean;
    begin
        // NEW >>>>
        OnBeforeDisplayErrorIfItemIsBlocked(Rec, Handled);
        if Handled then
            exit;
        // NEW <<<<
        if Item.Blocked then
            Error(BlockedErr);
        ....

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDisplayErrorIfItemIsBlocked(var Rec: Record "Item Journal Line"; var Handled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
