### ISSUE TITLE
Table 5050 Contact - ContactToCustBusinessRelationExist

### ISSUE THREAD

**Issue by mynavblog** [Microsoft/ALAppExtensions#506]
Dear Team,
Please mark function ContactToCustBusinessRelationExist in Table 5050 Contact as External

![image](https://user-images.githubusercontent.com/37371997/49379431-63754500-f70f-11e8-964c-aa18dc2d2a66.png)

Thank you,
Krzysztof

**Comment by JesperSchulz** [comment]
The function was exposed as part of a recent bigger fix pack. The function will be marked as external in the upcoming update.
