### ISSUE TITLE
[Event Request] Codeunit 7322 Create Inventory Pick/Movement - OnBeforeUpdatePlaceLine

### ISSUE THREAD

**Issue by NAVRockClimber** [microsoft/ALAppExtensions#5063]
Hi AL-Team,

can you please add the following Publisher to the procedure MakeLine in Codeunit  7322 Create Inventory Pick/Movement?

```
if Location."Bin Mandatory" and IsInvtMovement then begin
  // Place Action for inventory movement
  // >> New Event
  OnBeforeUpdatePlaceLine(NewWhseActivLine, PlaceBinCode);
  // << New Event
  NextLineNo := NextLineNo + 10000;
  NewWhseActivLine."Line No." := NextLineNo;
  NewWhseActivLine."Action Type" := NewWhseActivLine."Action Type"::Place;
  NewWhseActivLine."Bin Code" := PlaceBinCode;
  NewWhseActivLine.Insert;
  UpdateHandledWhseActivityLineBuffer(NewWhseActivLine, TakeBinCode);
end;
```

Event Publisher:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdatePlaceLine(var WarehouseActivityLine: Record "Warehouse Activity Line"; PlaceBinCode: Code[20])
begin
end;
```

Thank you very much.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
