### ISSUE TITLE
[Event Request] Codeunit 12171 - Vend. Bill List-Change Status

### ISSUE THREAD

**Issue by DennyHW** [microsoft/ALAppExtensions#5064]
Can you insert event like in functions like:

**FromOpenToSent**
OnBeforeChangeStatusToSent(VAR VendorBillHeader : Record "Vendor Bill Header")
...
OnAfterChangeStatusToSent(VAR VendorBillHeader : Record "Vendor Bill Header")

**FromSentToOpen**
OnBeforeChangeStatusToOpen(VAR VendorBillHeader : Record "Vendor Bill Header")
...
OnAfterChangeStatusToOpen(VAR VendorBillHeader : Record "Vendor Bill Header")

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
