### ISSUE TITLE
[Event Request] COD 22 - SplitJnlLine - SkipError

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5065]
Similar to the way Errors have been skipped in codeunit 80 Sales-Post (e.g. OnPostItemTrackingForShipmentOnBeforeShipmentInvoiceErr), we would like to skip the error below in "Item Jnl.-Post Line"(Codeunit 22), function SplitJnlLine

```
...
end else
      // Move code to separate function with OnBefore publisher
                if (ItemJnlLine2."Item Charge No." = '') and (ItemJnlLine2."Job No." = '') then
                    if not ItemJnlLine2.Correction then // Undo quantity posting.
                        Error(Text011);
```

Can you please provide an event publisher with Handled pattern and acces to ItemJnlLine2, so we can skip the error?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
