### ISSUE TITLE
T39 OnDelete Event needed before modifying SalesOrderLine

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5066]
Hi ,
we would need an event onDelete trigger on this place:
![image](https://user-images.githubusercontent.com/53824412/69734938-1fedc500-1130-11ea-819c-167b0dda7c58.png)
because we have to check other contitions for other fields.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
