### ISSUE TITLE
Assembly Order - RefreshOnActivate

### ISSUE THREAD

**Issue by YannRobertCargo** [microsoft/ALAppExtensions#5067]
Hello.
On an assembly order, if we cancel a reservation on a line, then close the "Reservation Entries" window to come back on the assembly order, the "Reserved quantity" flowfield is not updated. We have to leave the assembly order and come back to it to update it.

This behavious works fine on a sales order. I think this is because the "Sales Order" page has the property "RefreshOnActivate" set to true, which is not the case for the "Assembly Order" page.
Could you please set this property on the "Assembly Order" Page aswell ? 

I do need it as one of my extensions needs to update some info related to reservations. I believe I am stuck as the "OnAfterGetRecord" trigger is not fired after closing the "Reservations Entries" page.

Unless there is an other solution ?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
