### ISSUE TITLE
T39 OnDelete event on filtering PurchLine2 before delete

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5068]
we would like to event on T39 OnDelete PurchLine2 before delete:

![image](https://user-images.githubusercontent.com/53824412/69737770-42361180-1135-11ea-8d05-ec1a2e5d4366.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
