### ISSUE TITLE
[Event Request] Application “Tests-Data Exchange”, Codeunit 139158 "Invoice Mapping Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5069]
[Event Request] Application “Tests-Data Exchange”, Codeunit 139158 "Invoice Mapping Tests"
![Pic1](https://user-images.githubusercontent.com/45795262/69738581-a6a5a080-1136-11ea-9d95-87407fc99012.png)

Could you please insert an OnTestInitialize-Raiser at the beginning of the procedure Initialize?
![Pic2](https://user-images.githubusercontent.com/45795262/69738593-aad1be00-1136-11ea-90ec-93395bf145d4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
