### ISSUE TITLE
[Event Request] Codeunit 2000000 PmtJrnlManagement - OnBeforeCalculateTotals

### ISSUE THREAD

**Issue by OSHK** [Microsoft/ALAppExtensions#507]
We need the following publisher to override a standard **CalculateTotals** function according to the business logic in our solution:

_Codeunit 2000000 PmtJrnlManagement - OnBeforeCalculateTotals (event at the beginning of the function)_
```
IsHandled := FALSE;
OnBeforeCalculateTotals(PaymentJnlLine,LastPaymentJnlLine,Balance,TotalAmount,ShowAmount,ShowTotalAmount);
IF IsHandled THEN
  EXIT;
```

Thank you in advance!

**Comment by fvet** [comment]
@JesperSchulz 

I've checked the NAVBE14.00 version of CU 2000000 (Belgian localisation / checked on DVD, not on Docker) but couldn't find the 'OnBeforeCalculateTotals' publisher?
