### ISSUE TITLE
[Event Request] Application “Tests-Data Exchange”, Codeunit 139157 "Invoice Premapping Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5070]
[Event Request] Application “Tests-Data Exchange”, Codeunit 139157 "Invoice Premapping Tests"
![Pic1](https://user-images.githubusercontent.com/45795262/69738747-d94f9900-1136-11ea-9519-075e124e5c74.png)

Could you please insert an OnTestInitialize-Raiser at the beginning of the procedure Initialize?
![Pic2](https://user-images.githubusercontent.com/45795262/69738757-dc4a8980-1136-11ea-86d3-c2909b73c6ad.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
