### ISSUE TITLE
[Event Request] CU 5763 OnAfterInitPostedShptLine

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#5071]
Hi,

please add this event similarly as CU 5760

```
UpdateWhseShptLineBuf(WhseShptLine);
WITH PostedWhseShptLine DO BEGIN
  INIT;
  TRANSFERFIELDS(WhseShptLine);
  "No." := PostedWhseShptHeader."No.";
  OnAfterInitPostedShptLine(WhseShptLine,PostedWhseShptLine); // AHD BC FUTURE
  Quantity := WhseShptLine."Qty. to Ship";
```

`LOCAL [IntegrationEvent] OnAfterInitPostedShptLine(VAR WarehouseShipmentLine : Record "Warehouse Shipment Line";VAR PostedWhseShipmentLine : Record "Posted Whse. Shipment Line")`

Thank you
S.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
