### ISSUE TITLE
[Event Request] CU 5763 OnBeforeRegisterWhseJnlLines

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#5072]
Hi,

please add this event similarly as CU 5760

```
IF Location."Bin Mandatory" THEN BEGIN
  CreateWhseJnlLine(TempWhseJnlLine,PostedWhseShptLine);
  WMSMgt.CheckWhseJnlLine(TempWhseJnlLine,0,0,FALSE);
  OnBeforeRegisterWhseJnlLines(TempWhseJnlLine,PostedWhseShptLine); // AHD BC FUTURE
  ItemTrackingMgt.SplitWhseJnlLine(TempWhseJnlLine,TempWhseJnlLine2,TempHandlingSpecification,FALSE);
```

`LOCAL [IntegrationEvent] OnBeforeRegisterWhseJnlLines(VAR TempWarehouseJournalLine : TEMPORARY Record "Warehouse Journal Line";VAR PostedWhseShipmentLine : Record "Posted Whse. Shipment Line")`

Thank you
S.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
