### ISSUE TITLE
[Event Request] Codeunit 5060 Duplicate Management

### ISSUE THREAD

**Issue by cmuris** [microsoft/ALAppExtensions#5073]
Hi,

please add the following 3 Events:

No.1

    [IntegrationEvent(false, false)]
    local procedure OnMakeContIndex(var Contact: Record Contact;var IsHandled : Boolean)
    begin
    end;

called here:

    procedure MakeContIndex(Cont: Record Contact)
    var
        DuplSearchStringSetup: Record "Duplicate Search String Setup";
        IsHandled : Boolean;
    begin
        // Event
        OnMakeContIndex(Cont,IsHandled);
        if (IsHandled) then 
          exit;
        // Event
        RMSetup.Get;

No. 2

    [IntegrationEvent(false, false)]
    local procedure OnRemoveContIndex(Cont: Record Contact; KeepAccepted: Boolean; var IsHandled : Boolean)
    begin
    end;

called here

    procedure RemoveContIndex(Cont: Record Contact; KeepAccepted: Boolean)
    var
        DuplContSearchString: Record "Cont. Duplicate Search String";
        DuplCont: Record "Contact Duplicate";
        IsHandled: boolean;
    begin
        // Event
        OnRemoveContIndex(Cont, KeepAccepted, IsHandled);
        if IsHandled then
          exit;
        // Event

No. 3 

    [IntegrationEvent(false, false)]
    local procedure OnLaunchDuplicateForm(Cont: Record Contact; var IsHandled : Boolean)
    begin
    end;

called here

    procedure LaunchDuplicateForm(Cont: Record Contact)
    var
        DuplCont: Record "Contact Duplicate";
        IsHandled: Boolean;
    begin
        // Event
        OnLaunchDuplicateForm(Cont,IsHandled);
        if IsHandled then
          exit;
        // Event

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
