### ISSUE TITLE
Add publisher T5050 - Contact

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#5074]
Hello,

Could you please add a publisher in function CreateVendor? We need it for extension development, to update vendor's related records:
![image](https://user-images.githubusercontent.com/34686682/69796274-fedbb180-11cd-11ea-940d-6755348784ee.png)

You have a similar publisher in CreateCustomer, before updating Quotes:
![image](https://user-images.githubusercontent.com/34686682/69796423-50843c00-11ce-11ea-8add-ea6fa77dac79.png)

Thanks,
Radovan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
