### ISSUE TITLE
[Event Request] Table 901 Assembly Line OnAfterUnitCost

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#5075]
[IntegrationEvent(false, false)]
 local procedure OnAfterUnitCost(var AssemblyLine: Record "Assembly Line"; var UnitCost: Decimal)
  begin
  end;

    procedure GetUnitCost(): Decimal
    var
        UnitCost: Decimal;
    begin
        GetItemResource;

        case Type of
            Type::Item:
                if GetSKU then
                    UnitCost := StockkeepingUnit."Unit Cost" * "Qty. per Unit of Measure"
                else
                    UnitCost := Item."Unit Cost" * "Qty. per Unit of Measure";
            Type::Resource:
                UnitCost := Resource."Unit Cost" * "Qty. per Unit of Measure";
        end;
       
        OnAfterUnitCost(Rec,UnitCost);    //New Event 

        exit(RoundUnitAmount(UnitCost));
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
