### ISSUE TITLE
[Event Request] Table 37 Sales Line  OnBeforeGetUnitCost Change Rec parameter to Var Rec

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#5076]
Current...
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetUnitCost(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

    After...
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetUnitCost(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
