### ISSUE TITLE
[Event Request] COD 1250 - GetAccountMapping

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5077]
What has happened with #2715? It was shipped in BC 14, but I can't find it in BC 15.1, neither in a - not so recent - BC 16 insider build.

![image](https://user-images.githubusercontent.com/25268332/69814660-f77bce80-11f4-11ea-9076-223995929722.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
