### ISSUE TITLE
[Event Request] COD 1255 - OnFindTextMappingsOnBeforeCalculateStringNearness

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5078]
What has happened with #2716? It was available in BC 14, but no longer in BC 15.1 neither in a BC 16 insider preview.

OnFindTextMappingsOnBeforeCalculateStringNearness publisher is missing...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
