### ISSUE TITLE
[Key Request] Add new Key on Table 12144 "GL Book Entry" - Italian Localization

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5079]
Can you add a new key "G/L Account No.","Posting Date" on table 12144 "GL Book Entry".

**Comment by Enomis82** [comment]
any news about this request?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
