### ISSUE TITLE
[EventRequest] Codeunit 6500 “Item Tracking Management” on procedure "SumUpItemTracking"

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5080]
lease add a new publisher event SumUpItemTrackingOnBeforeInsertTrackingSpec in Codeunit 6500 on function SumUpItemTracking" and call it as shown in the image below
![image](https://user-images.githubusercontent.com/26144133/69820051-85a98200-1200-11ea-9196-2f2f417ec58d.png)

Please add the corresponding Integration Event In the bottom of the codeunit
`LOCAL [IntegrationEvent] SumUpItemTrackingOnBeforeInsertTrackingSpec(ReservEntry : Record "Reservation Entry";VAR TrackingSpec : Record "Tracking Specification")`

**Comment by AlexanderYakunin** [comment]
We already have this event, please use 15.X code base for your requests:

                        OnBeforeTempHandlingSpecificationInsert(TempHandlingSpecification, ReservEntry);
                        TempHandlingSpecification.Insert;
