### ISSUE TITLE
[EventRequest] Page 6510 “Item Tracking Lines” on procedure "RegisterChange"

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5081]
Please add a new publisher event OnRegisterChangeOnAfterFullDelete in Page 6510 on function "RegisterChange" and call it as shown in the image below
![image](https://user-images.githubusercontent.com/26144133/69820361-3adc3a00-1201-11ea-9f5b-db603b575140.png)

Please add the corresponding Integration Event In the bottom of the Page
`LOCAL [IntegrationEvent] OnRegisterChangeOnAfterFullDelete(ReservEntry : Record "Reservation Entry")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
