### ISSUE TITLE
[EventRequest] Codeunit 12 "Gen. Jnl.-Post Line" OnAfterApplyCustLedgerEntry

### ISSUE THREAD

**Issue by cmuris** [microsoft/ALAppExtensions#5082]
Please add the following event

    [IntegrationEvent(false, false)]
    local procedure OnAfterApplyCustLedgerEntry(var GenJournalLine: record "Gen. Journal Line"; var OldCustLedgEntry: record "Cust. Ledger Entry"; var NewCVLedgEntryBuf: record "CV Ledger Entry Buffer")
    begin
    end;

to function ApplyCustLedgEntry

            TempOldCustLedgEntry.Delete;

            // Event
            OnAfterApplyCustLedgerEntry(GenJnlLine, OldCustLedgEntry, NewCVLedgEntryBuf);
            // Event

            Completed := FindNextOldCustLedgEntryToApply(GenJnlLine, TempOldCustLedgEntry, NewCVLedgEntryBuf);
        until Completed;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
