### ISSUE TITLE
[Event Request] Codeunit 416 New event OnBeforeCheckExistingServiceLines(ServiceHeader,IsHandled);

### ISSUE THREAD

**Issue by ricardopaiva** [microsoft/ALAppExtensions#5084]
In the codeunit 416 - Release Service Document it would be great to have a new event called, for example, OnBeforeCheckExistingServiceLines(ServiceHeader,IsHandled), with the Handled pattern implemented.

**Purpose**: Allow to skip the existing line verification when releasing the service order.

So instead of:

```
  OnBeforeReleaseServiceDoc(ServiceHeader);

  IF "Document Type" = "Document Type"::Quote THEN
    TESTFIELD("Bill-to Customer No.");
  ServLine.SETRANGE("Document Type","Document Type");
  ServLine.SETRANGE("Document No.","No.");
  ServLine.SETFILTER(Type,'<>%1',ServLine.Type::" ");
  ServLine.SETFILTER(Quantity,'<>0');
  IF ServLine.ISEMPTY THEN
    ERROR(Text001,"Document Type","No.");
  InvtSetup.GET;
```

We would have this:

```
  OnBeforeReleaseServiceDoc(ServiceHeader);

  IF "Document Type" = "Document Type"::Quote THEN
    TESTFIELD("Bill-to Customer No.");
    
  IsHandled := FALSE;
  OnBeforeCheckExistingServiceLines(ServiceHeader,IsHandled);
  IF NOT IsHandled THEN BEGIN
    
    ServLine.SETRANGE("Document Type","Document Type");
    ServLine.SETRANGE("Document No.","No.");
    ServLine.SETFILTER(Type,'<>%1',ServLine.Type::" ");
    ServLine.SETFILTER(Quantity,'<>0');
    IF ServLine.ISEMPTY THEN
      ERROR(Text001,"Document Type","No.");
  
  END;
  
  InvtSetup.GET;
```

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by ricardopaiva** [comment]
Hi all,

I believe that you will do further testing before adding and releasing this new code but I would like you to know that the code I've suggested is not working properly.
The solution should be:

  OnBeforeReleaseServiceDoc(ServiceHeader);

  IF "Document Type" = "Document Type"::Quote THEN
    TESTFIELD("Bill-to Customer No.");
        
  ServLine.SETRANGE("Document Type","Document Type");
  ServLine.SETRANGE("Document No.","No.");
  ServLine.SETFILTER(Type,'<>%1',ServLine.Type::" ");
  ServLine.SETFILTER(Quantity,'<>0');
  IsHandled := FALSE;
  OnBeforeCheckExistingServiceLines(ServiceHeader,IsHandled);
  IF NOT IsHandled THEN BEGIN
    IF ServLine.ISEMPTY THEN
      ERROR(Text001,"Document Type","No.");
  END;
  
  InvtSetup.GET;
