### ISSUE TITLE
[Event Request] Table 5940 - Service Item - New event OnBeforeCheckExistingServiceLines(ServiceItem,IsHandled);

### ISSUE THREAD

**Issue by ricardopaiva** [microsoft/ALAppExtensions#5085]
In the table 5940 - Service Item it would be great to have a new event called, for example, OnBeforeCheckServItemLinesExist(ServiceItem,IsHandled), with the Handled pattern implemented.

**Purpose**: Change the standard validations. For example, if you want to allow to change the service item customer's as long as there are no service order in other status than Finished (we have customer's that ask us to keep the service orders in the system ad eternum so the service orders won't be deleted after posting but the status will be Finished).

So instead of:

```
Customer No. - OnValidate()
IF "Customer No." <> xRec."Customer No." THEN BEGIN
  IF CheckifActiveServContLineExist THEN
    ERROR(
      Text004,
      FIELDCAPTION("Customer No."),"Customer No.",TABLECAPTION,"No.");
  ServItemLinesExistErr(FIELDCAPTION("Customer No."));
  IF ServLedgEntryExist THEN
```

We would have this:

```
Customer No. - OnValidate()
IF "Customer No." <> xRec."Customer No." THEN BEGIN
  IF CheckifActiveServContLineExist THEN
    ERROR(
      Text004,
      FIELDCAPTION("Customer No."),"Customer No.",TABLECAPTION,"No.");
  IsHandled := FALSE;
  OnBeforeCheckServItemLinesExist(ServiceItem,IsHandled);
  IF NOT IsHandled THEN
    ServItemLinesExistErr(FIELDCAPTION("Customer No."));
  IF ServLedgEntryExist THEN
```

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
