### ISSUE TITLE
[Event Request] Page 130 - Posted Sales Shipment & Page 142 - Posted Sales Shipments - OnBeforePrintRecord

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5087]
Hi AL-Team,
can you please add the following publisher to action Print?
We want to add further information from the Rec to the SalesShptHeader variable.

```
            action("&Print")
            {
                ApplicationArea = Basic, Suite;
                Caption = '&Print';
                Ellipsis = true;
                Image = Print;
                Promoted = true;
                PromotedCategory = Category4;
                ToolTip = 'Print the shipping notice.';

                trigger OnAction()
                begin
                    // NEW >>>>
                    OnBeforePrintRecord(Rec, SalesShptHeader);
                    // NEW <<<<
                    CurrPage.SetSelectionFilter(SalesShptHeader);
                    SalesShptHeader.PrintRecords(true);
                end;
            }

    [IntegrationEvent(false, false)]
    local procedure OnBeforePrintRecord(var Rec: Record "Sales Shipment Header"; var SalesShptHeader: Record "Sales Shipment Header")
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
