### ISSUE TITLE
Codeunit 2000001 CheckPaymJnlLine "CheckBeneficiaryBankForSEPA"

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#5089]
can following change be made to codeunit 2000001 CheckPaymJnlLine function "CheckBeneficiaryBankForSEPA"

WITH PmtJnlLine DO BEGIN
  CheckIBANForSEPA(PmtJnlLine,EuroSEPA);
  IF IfForeignBank(PmtJnlLine."Bank Account") THEN //new code
    ErrorEmptyFieldInLine("Line No.","SWIFT Code",FIELDCAPTION("SWIFT Code"));

  IF NOT ErrorEmptyFieldInLine("Line No.","Bank Country/Region Code",FIELDCAPTION("Bank Country/Region Code")) THEN
    CheckSEPAAllowed(EuroSEPA,"Line No.","Bank Country/Region Code");
END;

new function: 
IfForeignBank(codBank; code[20])
GetBankAccount(codBank);
CompanyInformation.GET;
IF BankAcc."Country/Region Code" <> CompanyInformation."Country/Region Code" THEN
  EXIT(TRUE);

this because the SWIFT code is no longer mandatory for belgian bank transfer and therefor is not always present.

or event in place of this code is also a possibility, so we can skip the error.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.
