### ISSUE TITLE
[Extensibility] Table 5902 - Service Line

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#5091]
### **Event OnAfterResourseFindCost**

Please pass parameter _ResourceCost_ by reference.

### Existing Code
`LOCAL [IntegrationEvent] OnAfterResourseFindCost(VAR ServiceLine : Record "Service Line"; ResourceCost : Record "Resource Cost")`

### New Code
`LOCAL [IntegrationEvent] OnAfterResourseFindCost(VAR ServiceLine : Record "Service Line";VAR ResourceCost : Record "Resource Cost")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
