### ISSUE TITLE
[Event-Request] Codeunit 9520 - Mail Management - SendMailOrDownload

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/ALAppExtensions#5095]
In **https://github.com/microsoft/ALAppExtensions/issues/4308** a new **OnBeforeRunMailDialog** event was added so we can override the standard behavior with a custom Mail Dialog. This for example allows us to make an editable variant of the Email Dialog.

The **SendMailOrDownload** function currently does not provide the possibility to retrieve the changed Email Item after it was processed. Therefore it would handy if the following event was created:

**OnAfterSendMailOrDownload(var IsSent: boolean; var TempEmailItem)**

**Comment by daansaveyn** [comment]
@fvet

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
