### ISSUE TITLE
[Event Request] Codeunit 63 OnAfterInitOfExplodedBOMLineToSalesLine

### ISSUE THREAD

**Issue by makuhn** [Microsoft/ALAppExtensions#510]
Add new integration event OnAfterInitOfExplodedBOMLineToSalesLine in Codeunit 63.

Function ExplodeBOMCompLines:
```
        REPEAT
          ToSalesLine.INIT;
+         OnAfterInitOfExplodedBOMLineToSalesLine(ToSalesLine,SalesLine,FromBOMComp);
          NextLineNo := NextLineNo + LineSpacing;
          ToSalesLine."Line No." := NextLineNo;
```
New publisher function:
```
    [Integration]
    LOCAL PROCEDURE OnAfterInitOfExplodedBOMLineToSalesLine@5172324(VAR ToSalesLine@1000 : Record 37;SalesLine@1001 : Record 37;BOMComponent@1002 : Record 90);
    BEGIN
    END;
```

**Comment by AlexanderYakunin** [comment]
Can you explain how you will use this event? ToSalesLine is totally empty at this point. You have another event after filling fields in ToSalesLine, why this is not enough?

**Comment by makuhn** [comment]
We checked our code. We can change it to use already existing events. Thanks for you convenience.
