### ISSUE TITLE
[Extensibility] Protection level for ShipToOptions, BillToOptions and PayToOptions

### ISSUE THREAD

**Issue by cstuber** [microsoft/ALAppExtensions#5101]
Please add the following functions to Pages 41, 42, 43, 49, 50, 51, 52, 507 and 6640.
```
    procedure SetShipToOptions(NewShipToOptions: Option)
    begin
        ShipToOptions := NewShipToOptions
    end;

    procedure GetShipToOptions(): Option;
    begin
        exit(ShipToOptions)
    end;
```
Please add the following functions to Pages 41, 42, 43 and 507.
```
    procedure SetBillToOptions(NewBillToOptions: Option)
    begin
        BillToOptions := NewBillToOptions
    end;

    procedure GetBillToOptions(): Option;
    begin
        exit(BillToOptions)
    end;
```
Please add the following functions to Pages 49, 50 and 51.
```
    procedure SetPayToOptions(NewPayToOptions: Option)
    begin
        PayToOptions := NewPayToOptions
    end;

    procedure GetPayToOptions(): Option;
    begin
        exit(PayToOptions)
    end;
```

**Comment by cstuber** [comment]
I did some further investigation and found this documentation about the protection level of global variables. https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-protected-variables

Making the Options protected seems to be an easier solution.

I suggest you move `ShipToOptions` to `protected var` in Pages 41, 42, 43, 49, 50, 51, 52, 507 and 6640 and do the equivalent for `BillToOptions` in Pages 41, 42, 43 and 507 and `PayToOptions` in Pages 49, 50 and 51.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
