### ISSUE TITLE
[Application Refactoring] Report 840 "Suggest Worksheet Lines"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5103]
Following #1391

**Short-term fixes**
To extend cashflow, we're forced to **duplicate** report 840 since it cannot be extended easily with new source types. As a consequence, the original report references need to be updated in these 2 places:

**codeunit 841 "Cash Flow Management" > UpdateCashFlowForecast** 
- [ ] OnBeforeUpdateCashFlowForecast is available, but it would be better if following code was moved to a **separate function with an OnBefore publisher and handled pattern**, to overrule the default report, so we could duplicate less code.

```
SuggestWorksheetLines.InitializeRequest(
          Sources, CashFlowSetup."CF No. on Chart in Role Center", CashFlowForecast."Default G/L Budget Name", true);
        SuggestWorksheetLines.UseRequestPage := false;
        SuggestWorksheetLines.Run;
```
- [ ] Page "Cash Flow Worksheet" : we're forced to duplicate the action SuggestWorksheetLines, but **DeleteErrors** is not exposed. Please make it **external**. Another idea might be to replace SuggestWkshLines.RunModal by a report.RUNMODAL (with report ID) so we could use report substitution.

PS: These are only workarounds to ease duplication of the report. 
In the end, duplicating the report should be avoided ...

**Long-term fix**
- [ ] To make the report 840 extensible, we're awaiting on report extensions to add parameters to requestpage, add dataitems, ... so we should no longer duplicate.

- [ ] Function **NoOptionsChosen** (on report 840) needs to be extensible so we can add conditions based on extra globals / source types (which is not supported by the fixed array ConsiderSource)

**Comment by fvet** [comment]
Example code:
Right now, I need to copy following code, only to replace the report id ...

![image](https://user-images.githubusercontent.com/25268332/70044758-3af28600-15c3-11ea-83ed-0fdcbef76863.png)

**Comment by RomanZanizdra** [comment]
Hi @fvet .
"DeleteErrors" function will be external. 
About first point, I see it won't fix for now. I understand it will allow you to copy less code than now but in general it will not help you. Until reports will be extensible and some variables will be replaced with enums and lists.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
