### ISSUE TITLE
[Event Request] Page 6631 - Sales Return Order Subform - OnAfterQuantityOnAfterValidate

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5106]
Hi AL-Team,
can you please add the following publisher with "IncludeSender" to QuantityOnAfterValidate?

```
    local procedure QuantityOnAfterValidate()
    begin
        if Reserve = Reserve::Always then begin
            CurrPage.SaveRecord;
            AutoReserve;
            CurrPage.Update(false);
        end;

        // NEW >>>>
        OnAfterQuantityOnAfterValidate();
        // NEW <<<<
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterQuantityOnAfterValidate()
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
