### ISSUE TITLE
[Event Request] TAB 847 - OnBeforeDrillDownOnEntries

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5107]
Following #1391 

Table 847 "Cash Flow Forecast Entry"
- Field "Source Type": Seems not be converted to an extendable enum. We will refactor to a blank source type option in combination with custom fields Please provide an **OnBeforeDrillDownOnEntries**(var CashFlowForecast: Record "Cash Flow Forecast", var CFForecastEntry) publisher in function DrillDownOnEntries.

**Comment by AlexanderYakunin** [comment]
We already have enum. Please use it instead.
