### ISSUE TITLE
[Enum Request] TAB "Cash Flow Forecast"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5108]
Following #1391

Seems like 'Source Type / Source Type Filter' are not extendable. Extendable enums might help.
We have currently introduced a new custom field instead, but are forced to duplicate flowfields like 'Amount (LCY') since flowfield definitions are not extendable including new flowfilters. 

 What is the best way forward to extend CF with new source types (in screenshot below the values 'Services' and 'Costs')? Extendable enums (forcing us to do another refactoring ...)?

![image](https://user-images.githubusercontent.com/25268332/70048064-bc4d1700-15c9-11ea-918f-1ba91fbe0e8c.png)

In case extensible enums are provided, please review ALL related cashflow objects (e.g. table "Cash Flow Account", "Cash Flow Forecast Entry", ...).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
