### ISSUE TITLE
CU 1303 CreateCreditMemo new event needed

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5109]
Hi, we need new event in funtion CreateCreditMemo, in goal of opening another page.
You can see described in our custom publisher:
![image](https://user-images.githubusercontent.com/53824412/70050707-e570a600-15cf-11ea-9e83-81fe79960907.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
