### ISSUE TITLE
Add parameter in CU "Document-Mailing" function EmailFileAndHtmlFromStream

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#5110]
Hi,

Could you please add DocumentNo as a parameter into EmailFileAndHtmlFromStream function? And pass its value to EmailFileInternal?

Function EmailFileAndHtmlFromStream uses FALSE for IsFromPostedDoc and we will never get the value for PostedDocNo, so we cannot use it later in publishers OnBeforeSendEmail and OnAfterEmailSentSuccesfully.

![image](https://user-images.githubusercontent.com/34686682/70050928-5adc7680-15d0-11ea-9c64-77913b53e1a8.png)

**Comment by radovandokic** [comment]
A new function could look like this

![image](https://user-images.githubusercontent.com/34686682/70052212-1a322c80-15d3-11ea-852a-6f2d5f2a6399.png)

**Comment by radovandokic** [comment]
In the image above, I made a mistake. I put DocumentNo (in EmailFileInternal function) in the wrong place, it should be after **CopyStr(ToEmailAddress, 1, MaxStrLen(TempEmailItem."Send to"))**, it is 7th parameter in EmailFileInternal function.

**Comment by RomanZanizdra** [comment]
Hi @radovandokic .
We are not able to add/remove parameters for the external functions. 
I suggest you to create your own function by copy/paste of the current one and pass parameter that you need.

**Comment by radovandokic** [comment]
Hi @RomanZanizdra,
It is strange that you cannot add a parameter that already exists in the inner function EmailFileInternal. And instead of empty string, send code(20).
Anyway, your suggestion cannot be applied since many functions used in EmailFileAndHtmlFromStream cannot be used for extension development

![image](https://user-images.githubusercontent.com/34686682/73931989-a0236a00-48d9-11ea-944e-84dcda4d2eec.png)

**Comment by RomanZanizdra** [comment]
@radovandokic , there will be an overloaded function in order you will be able to pass document number.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
