### ISSUE TITLE
[Event Request] Page 55 - Purch. Invoice Subform - OnAfterNoOnAfterValidate

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5111]
Hi AL-Team,
can you please add the following publisher with "IncludeSender" to NoOnAfterValidate?   

 ```
procedure NoOnAfterValidate()
    begin
        UpdateEditableOnRow;
        InsertExtendedText(false);
        if (Type = Type::"Charge (Item)") and ("No." <> xRec."No.") and
           (xRec."No." <> '')
        then
            CurrPage.SaveRecord;

        // NEW >>>>
        OnAfterNoOnAfterValidate();
        // NEW <<<<
    end;
    
[IntegrationEvent(true, false)]
    local procedure OnAfterNoOnAfterValidate()
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
