### ISSUE TITLE
[External Functions] Page "Cash Flow Availability Lines"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5113]
Following #1391 

Please add access to following functions / globals to list extra source types on page "Cash Flow Availability Lines" :

- [ ] Procedure **FormatStr** should be global

![image](https://user-images.githubusercontent.com/25268332/70054352-af372480-15d7-11ea-9e16-3ead254efb22.png)

- [ ] Global variable **RoundingFactor** must be accessible. (via a Getter?)

![image](https://user-images.githubusercontent.com/25268332/70054370-bbbb7d00-15d7-11ea-8434-b9fd1f341495.png)

_This would allow us to include new source types and extending the page, with a final solution including extensible enums (so we could reuse the standard GetAmount / DrillDownEntriesFromSource functions again)_

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
