### ISSUE TITLE
[Event Request] Page 508 - "Blanket Sales Order Subform" - OnAfterNoOnAfterValidate

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5116]
Hi AL-Team,
can you please add the following publisher with "IncludeSender" to NoOnAfterValidate?

```

local procedure NoOnAfterValidate()
    begin
        InsertExtendedText(false);

        // NEW >>>>
        OnAfterNoOnAfterValidate();
        // NEW <<<<

        SaveAndAutoAsmToOrder;
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterNoOnAfterValidate()
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
This event with access to Rec already exist

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
