### ISSUE TITLE
[Event Request] report 15000062 "Remittance - Import (Bank)" (Norwegian Localization) - update

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#5117]
Ref issue #4456

Can you add **VAR to parameter BalanceEntryAmountLCY** when adding event OnBeforeInsertBalanceGenJournalLine in report 15000062 "Remittance - Import (Bank)"?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
