### ISSUE TITLE
[Event Request] Page 47 - "Sales Invoice Subform" - OnAfterValidateAutoReserve

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5119]
Hi AL-Team,
can you please add the following publisher with "IncludeSender" to ValidateAutoReserve?
```
    local procedure ValidateAutoReserve()
    begin
        if Reserve = Reserve::Always then begin
            CurrPage.SaveRecord;
            AutoReserve;
        end;

        // NEW >>>>
        OnAfterValidateAutoReserve();
        // NEW <<<<
    end;    

[IntegrationEvent(true, false)]
    local procedure OnAfterValidateAutoReserve()
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
