### ISSUE TITLE
[Event Request] Table 381 - OnCheckCust, OnCheckVendor

### ISSUE THREAD

**Issue by makuhn** [Microsoft/ALAppExtensions#512]
Add new integration events **OnCheckCust**, **OnCheckVendor** in table 381.

Function CheckCust:
```
        UNTIL (Cust.NEXT = 0) OR Finish;
      END;
+     OnCheckCust(VATRegNo,Number,t,Finish,Check);
      IF Check = FALSE THEN
        MESSAGE(STRSUBSTNO(Text002,t));
```
Function CheckVendor:
```
        UNTIL (Vend.NEXT = 0) OR Finish;
      END;
+     OnCheckVendor(VATRegNo,Number,t,Finish,Check);
      IF Check = FALSE THEN
        MESSAGE(STRSUBSTNO(Text003,t));
```
New publisher functions:
```
    [Integration]
    LOCAL PROCEDURE OnCheckCust@5172325(VATRegNo@5172323 : Text[20];Number@5172322 : Code[20];VAR MessageText@5172324 : Text;VAR Finish@5172325 : Boolean;VAR Check@5172326 : Boolean);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnCheckVendor@5172326(VATRegNo@5172323 : Text[20];Number@5172322 : Code[20];VAR MessageText@5172324 : Text;VAR Finish@5172325 : Boolean;VAR Check@5172326 : Boolean);
    BEGIN
    END;
```

**Comment by AlexanderYakunin** [comment]
We already have handled events to prevent/replace our check before each Check function.

**Comment by makuhn** [comment]
We can also use the already existing events. We added the additional events in order to extend the message that is raised. This is not possible with the already existing events. We can implement our functionality also by subscribing the existing events. This could lead to the situation that two messages are raised - one within our subscriber and a second one with base application code - which is not optimal from a usability point of view.

**Comment by makuhn** [comment]
@AlexanderYakunin Can you give me a status update to this issue? Are you taking over the proposed events or should we change our code?

**Comment by AlexanderYakunin** [comment]
I can add these events in addition to existing

**Comment by makuhn** [comment]
Thanks for quick response

**Comment by JesperSchulz** [comment]
It looks to me as if this has been implemented. If anything is missing, please open a new issue, as we don't revisit closed issues. I hope you find everything is as requested.
