### ISSUE TITLE
Table 39 Purchase Line - Expose procedure ShowDeferralSchedule

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#5121]
Hi,

Can you please make procedure ShowDeferralSchedule() in Table 39 Purchase Line available for extensions development? Right now because of [Scope('OnPrem')] it cannot be used while developing extensions.

Thanks,
Nemanja

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
