### ISSUE TITLE
[Event Request] Codeunit 365 Format Address for function PurchHeaderShipTo

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#5126]
Hello,

please add following event publisher to the function PurchHeaderShipTo.

OnBeforePurchHeaderShipTo(AddrArray,PurchHeader,Handled);
IF Handled THEN
  EXIT;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
