### ISSUE TITLE
[Event Request] Codeunit 365 Format Address for function SalesShptBillTo

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#5127]
Hello,

please add following event publisher to the function SalesShptBillTo.

OnBeforeSalesShptBillTo(AddrArray,ShipToAddr,SalesShptHeader,Handled);
IF Handled THEN
EXIT;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
