### ISSUE TITLE
[Event Request] ItemJnlPostLine.Codeunit OnAfterCalculateExpirationDate

### ISSUE THREAD

**Issue by TeusV** [microsoft/ALAppExtensions#5128]
In our solution, the expiration calculation is not always the same per item (we manage it per Item Variant). Therefore, we would like to calculate the expiration date in a different way. Also, we want to base it on the Posting Date instead of the Document Date. An event as the below (CalcExpirationDate being a var parameter) would make this possible. (If this date would be by var in OnBeforeCheckExpirationDate, that would also work, but we're not interested in changing anything in in the checks on the expiration date, we just want to calculate it differently.)
``` al
                <...>
                if Format(ItemTrackingCode."Warranty Date Formula") <> '' then
                    CalcWarrantyDate := CalcDate(ItemTrackingCode."Warranty Date Formula", ItemJnlLine2."Document Date");
                if Format(Item."Expiration Calculation") <> '' then
                    CalcExpirationDate := CalcDate(Item."Expiration Calculation", ItemJnlLine2."Document Date");

                OnAfterCalculateExpirationDate(ItemJnlLine2, CalcExpirationDate);

                if SignFactor * ItemJnlLine2.Quantity < 0 then // Demand
                    if ItemTrackingCode."SN Specific Tracking" or ItemTrackingCode."Lot Specific Tracking" then
                        LateBindingMgt.ReallocateTrkgSpecification(TempTrackingSpecification);
                <...>
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
