### ISSUE TITLE
[Event Request] TAB 5964 "Service Contract Line"

### ISSUE THREAD

**Issue by AndreaAntolini** [microsoft/ALAppExtensions#5133]
Requesting new Event Publishers:

### **Event 1**
 
`LOCAL [IntegrationEvent] OnBeforeErrorsameservitem(VAR Rec : Record "Service Contract Line";xRec : Record "Service Contract Line";CurrFieldNo : Integer;VAR IsHandled : Boolean)`
 
**"Service Item no." - OnValidate:**
 
```
//> New code
OnBeforeErrorsameservitem(rec,xrec,currfieldno,ishandled);
If IsHandled  THEN BEGIN
//< New code
 
  ServContractLine.RESET;
  ServContractLine.SETRANGE("Contract No.","Contract No.");
  ServContractLine.SETRANGE("Contract Type","Contract Type");
  ServContractLine.SETRANGE("Service Item No.","Service Item No.");
  ServContractLine.SETFILTER("Line No.",'<>%1',"Line No.");
  IF NOT ServContractLine.ISEMPTY THEN
    ERROR(Text003);

//> New code
END;
//< New code
```

### **Event 2**

`LOCAL [IntegrationEvent] OnBeforeErrorCust(VAR Rec : Record "Service Contract Line";xRec : Record "Service Contract Line";CurrFieldNo : Integer;VAR IsHandled : Boolean)`
 
**"Service Item no." - OnValidate:**
 
```
//> New code
OnBeforeErrorCust(rec,xrec,currfieldno,ishandled);
IF Ishandled  THEN
//< New code
 
  IF ServItem."Customer No." <> ServContractHeader."Customer No." THEN
ERROR(Text000,"Customer No.");


```

**Comment by AlexanderYakunin** [comment]
We never provide events which change business logic. You cannot use with IsHandled := true. Please rework you ask for false case.

Please use proper event names.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
