### ISSUE TITLE
[Event Request] Codeunit 5940 “ServContractManagement”

### ISSUE THREAD

**Issue by AndreaAntolini** [microsoft/ALAppExtensions#5134]
Requesting a new IntegrationEvent:

`Local [IntegrationEvent]  OnBeforeErrorsamesCust(VAR Rec : Record "Service Contract Line";VAR IsHandled : Boolean)`

**Function LookupServItemNo()**
  
```
ServItem.FILTERGROUP(2);
 
//> New code
 OnBeforeErrorsamesCust(rec,ishandled);
IF Ishandled  THEN
//< New code
 
IF ServiceContractLine."Customer No." <> '' THEN
  ServItem.SETRANGE("Customer No.",ServiceContractLine."Customer No.");
ServItem.FILTERGROUP(0);

```

**Comment by AlexanderYakunin** [comment]
Name of suggested events is confusing, do you need to skip this line:
ServItem.SETRANGE("Customer No.",ServiceContractLine."Customer No.");

**Comment by AndreaAntolini** [comment]
Rewritten:

`Local [IntegrationEvent]  OnBeforeCustFilter(VAR Rec : Record "Service Contract Line";VAR SkipFilter: Boolean)`

**Function LookupServItemNo()**
  
```
ServItem.FILTERGROUP(2);
 
//> New code
 OnBeforeCustFilter(rec,SkipFilter);
IF NOT SkipFilter THEN
//< New code
 
IF ServiceContractLine."Customer No." <> '' THEN
  ServItem.SETRANGE("Customer No.",ServiceContractLine."Customer No.");
ServItem.FILTERGROUP(0);

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
