### ISSUE TITLE
Need SIFT changes to sales line for better performance

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#5141]
In AL Can you please perform the following performance critical changes to the base application.

Alter  key(Key4; "Document Type", "Bill-to Customer No.", "Currency Code", "Document No.")
to 
 key(Key4; "Document Type", "Bill-to Customer No.", "Currency Code")
to remove "Document No." field and to add "Prepmt. Amount Inv. (LCY)","Prepmt. VAT Amount Inv. (LCY)" fields to SumIndexFields for better scalable performance.

**Comment by AlexanderYakunin** [comment]
No, we cannot make this kind of changes. Please clarify if you are working with Cloud tenants, if not please do it yourself for your customers.

**Comment by Rama-M** [comment]
BC release 2 do not allow any Index or SIFT change on base application. Hence we really on Microsoft to do such performance critical changes for us.

Other option is Microsoft to allow index and SIFT change on base objects through extension. So please allow this ability to the solution center like us to make such changes like we used to do in C/Side.

Another option is allowing us to modify base objects through C/side development environment as before.


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Rama-M** [comment]
Any update on this performance critical change please ?

**Comment by AlexanderYakunin** [comment]
As I told you above we cannot make this kind of changes for one partner. It should be investigated if this change is really needed and which customer scenarios need this. This forum is not right place for such asks, we cannot do this investigation. If this is really critical please create support request on behalf of your partner company and work via Support to get answer. I'm closing this here as we cannot help.
