### ISSUE TITLE
CU 1322 Event needed 

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5142]
Hi we need event on cu 1322 before PAGE.RUN, like our example:

![image](https://user-images.githubusercontent.com/53824412/70240327-4ed9eb80-176d-11ea-9a41-588b2762a077.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
