### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 132522 "Sales-Calc. Discount Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5144]
[Event Request] Application “Tests-ERM”, Codeunit 132522 "Sales-Calc. Discount Test"
![Pic1](https://user-images.githubusercontent.com/45795262/70246317-d9bfe380-1777-11ea-9ee3-359157442c4a.png)

Could you please insert an OnTestInitialize at the beginning of procedure Initialize?
![Pic2](https://user-images.githubusercontent.com/45795262/70246323-dcbad400-1777-11ea-9499-a1cbab55090b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
