### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 132570 "Credit Transfer Register UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5145]
[Event Request] Application “Tests-ERM”, Codeunit 132570 "Credit Transfer Register UT"

![Pic1](https://user-images.githubusercontent.com/45795262/70246469-1a1f6180-1778-11ea-9920-3a772037cbcb.png)

Could you please insert an OnTestInitialize at the beginning of procedure Initialize?
![Pic2](https://user-images.githubusercontent.com/45795262/70246480-1d1a5200-1778-11ea-8b0c-ed6028ae4a35.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
