### ISSUE TITLE
[Event Request] COD365 - OnAfterCustomAddressFormatFound

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5147]
Hello,

could you please add an Event on COD365 so that it is possible to expand the Custom Address Formats.

A little special sase: It would be really needful to also get the SourceRecRef of the called function. For example is the SalesHeaderSellTo-function originally called, so the SalesHeader should be accessible.

The AddrArray should be a VAR-parameter. 

![image](https://user-images.githubusercontent.com/45033081/70248603-6cae4d00-177b-11ea-99fb-de2bace1c6e9.png)

**Comment by AlexanderYakunin** [comment]
We cannot implement this change. Please look for other options, probably in source tables.

**Comment by SKeiler** [comment]
And what's the reason why?!
