### ISSUE TITLE
[EventRequest] Codeunit 442 Sales-Post Prepayments

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#5149]
Due to Polish Localization App building, we need a publisher in Codeunit 442. We need to do some changes in the Prepayment Invoice Line Buffer so that the compression of the buffer is done according to slightly different rules than the standard approach.
Function: Code
 
…
// START/BC14PL
OnAfterCreateLinesOnBeforeGLPosting(SalesHeader, SalesInvHeader, SalesCrMemoHeader, TempPrepmtInvLineBuffer, DocumentType, LineNo);
// STOP /BC14PL
 
 // G/L Posting
LineCount := 0;
IF NOT "Compress Prepayment" THEN
TempPrepmtInvLineBuffer.CompressBuffer;
TempPrepmtInvLineBuffer.SETRANGE(Adjustment,FALSE);
TempPrepmtInvLineBuffer.FINDSET(TRUE);
REPEAT
…
 
Publisher signature:   [Integration]  LOCAL PROCEDURE OnAfterCreateLinesOnBeforeGLPosting@34(VAR SalesHeader@1000 : Record 36;SalesInvoiceHeader@1003 : Record 112;SalesCrMemoHeader@1001 : Record 114;VAR PrepaymentInvLineBuffer@1005 : Record 461;DocumentType@1004 : Option;VAR LastLineNo@1002 : Integer);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
