### ISSUE TITLE
Table 5901 : Service Item Line - Out of Memory

### ISSUE THREAD

**Issue by BenjaminHochstetter** [Microsoft/ALAppExtensions#515]
Create a new Service Item Line and select a first "Repair Status", "Service Price Group", ...
--> Out of Memory
Response Time (Hours) - OnValidate()
Calls "UpdateResponseTimeHours;"
```
IF ("Response Time (Hours)" <> xRec."Response Time (Hours)") OR ("Response Time (Hours)" = 0) THEN BEGIN
    SkipResponseTimeHrsUpdate := TRUE;
    GetServHeader;
    CalculateResponseDateTime(ServHeader."Order Date",ServHeader."Order Time");
  END ELSE
    UpdateResponseTimeHours;
```
UpdateResponseTimeHours()
Calls VALIDATE("Response Time (Hours)",CalculateResponseTimeHours)
```
  IF NOT SkipResponseTimeHrsUpdate THEN BEGIN
    IF "Response Time (Hours)" <> xRec."Response Time (Hours)" THEN
      VALIDATE("Response Time (Hours)",CalculateResponseTimeHours)
    ELSE
      IF "Response Date" = 0D THEN
        VALIDATE("Response Time (Hours)",CalculateResponseTimeHours)
      ELSE
        "Response Time (Hours)" := CalculateResponseTimeHours;
    SkipResponseTimeHrsUpdate := FALSE
  END;
```

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate. 

To open a support case, you can:
- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
