### ISSUE TITLE
[EventRequest] Codeunit 442 Sales-Post Prepayments

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#5150]
Due to Polish Localization App building, we need a publisher in Codeunit 442. Polish localization adds a feature of postponing vat on documents. We need the publisher to automatically postpone the vat after posting Prepayment Sales Cr. Memo.
Function: Code
 
…
  // Update lines & header
  UpdateSalesDocument(SalesHeader,SalesLine,DocumentType,GenJnlLineDocNo);
  IF Status <> Status::"Pending Prepayment" THEN
    Status := Status::"Pending Prepayment";
  MODIFY;
END;
 
// START/BC14PL
OnAfterPostPrepaymentsOnBeforeThrowPreviewModeError(SalesHeader,SalesInvHeader,SalesCrMemoHeader,GenJnlPostLine);
// STOP /BC14PL
 
IF PreviewMode THEN BEGIN
  Window.CLOSE;
  GenJnlPostPreview.ThrowError;
END;
…
 
Publisher signature:   [Integration]  LOCAL PROCEDURE OnAfterPostPrepaymentsOnBeforeThrowPreviewModeError@77(VAR SalesHeader@1000 : Record 36;VAR SalesInvoiceHeader@1001 : Record 112;VAR SalesCrMemoHeader@1002 : Record 114;VAR GenJnlPostLine@1003 : Codeunit 12);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
