### ISSUE TITLE
[EventRequest] Page 402 Sales Order Statistics

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#5151]
Due to Polish Localization App building, we need a publisher and a small code modification in Page 402. Polish localization adds a feature of setting the total amount including vat of the prepayment via Sales Order Statistics. Since there is no access to the public members of the page, even from a page extension, we need this changes in code.
 
Trigger: OnValidate field PrepmtTotalAmount2
BEGIN
// START/BC14PL
OnBeforeValidatePrepmtTotalAmount2(Rec, PrepmtTotalAmount, PrepmtTotalAmount2);
           UpdatePrepmtAmount;
// STOP /BC14PL
END;
 
Publisher signature:  [Integration] LOCAL PROCEDURE OnBeforeValidatePrepmtTotalAmount2@12(SalesHeader@1002 : Record 36;VAR PrepmtTotalAmount@1000 : Decimal;VAR PrepmtTotalAmount2@1001 : Decimal);

**Comment by AlexanderYakunin** [comment]
How about using of protected vars?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
