### ISSUE TITLE
[EventRequest] Codeunit 444 Purchase-Post Prepayments

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#5153]
Due to Polish Localization App building, we need a publisher in Codeunit 444. We need to do some changes in the Prepayment Invoice Line Buffer so that the compression of the buffer is done differently than the standard approach.
Function: Code
 
…
// START/BC14PL
OnAfterCreateLinesOnBeforeGLPosting(PurchHeader, PurchInvHeader, PurchCrMemoHeader, TempPrepmtInvLineBuffer, DocumentType, LineNo);
// STOP /BC14PL
 
 // G/L Posting
LineCount := 0;
IF NOT "Compress Prepayment" THEN
        TempPrepmtInvLineBuffer.CompressBuffer;
TempPrepmtInvLineBuffer.SETRANGE(Adjustment,FALSE);
TempPrepmtInvLineBuffer.FINDSET(TRUE);
REPEAT
…
 
Publisher signature:   [Integration]  LOCAL PROCEDURE OnAfterCreateLinesOnBeforeGLPosting@34(VAR PurchHeader@1000 : Record 38;PurchInvHeader@1003 : Record 122;PurchCrMemoHdr@1001 : Record 124;VAR PrepaymentInvLineBuffer@1005 : Record 461;DocumentType@1004 : Option;VAR LastLineNo@1002 : Integer);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
