### ISSUE TITLE
[EventRequest] Codeunit 444 Purchase-Post Prepayments

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#5154]
Due to Polish Localization App building, we need a publisher in Codeunit 444. Polish localization adds a feature of postponing vat on documents. We need the publisher to automatically postpone the vat after posting Prepayment Purchase Cr. Memo.
Function: Code
 
…
  // Update lines & header
  UpdatePurchaseDocument(PurchHeader, PurchLine, DocumentType, GenJnlLineDocNo);
  IF Status <> Status::"Pending Prepayment" THEN
    Status := Status::"Pending Prepayment";
  MODIFY;
END;
 
// START/BC14PL
OnAfterPostPrepaymentsOnBeforeThrowPreviewModeError(SalesHeader,SalesInvHeader,SalesCrMemoHeader,GenJnlPostLine);
// STOP /BC14PL
 
IF PreviewMode THEN BEGIN
  Window.CLOSE;
  GenJnlPostPreview.ThrowError;
END;
…
 
Publisher signature:   [Integration]  LOCAL PROCEDURE OnAfterPostPrepaymentsOnBeforeThrowPreviewModeError@77(VAR PurchHeader@1000 : Record 38;VAR PurchInvoiceHeader@1001 : Record 122;VAR PurchCrMemoHeader@1002 : Record 124;VAR GenJnlPostLine@1003 : Codeunit 12);

**Comment by AlexanderYakunin** [comment]
Not sure I understand why you need this event. Please clarify.

**Comment by wokw** [comment]
Hi,
please find a short description from our documentation:
The Postponed VAT feature is used every time the VAT amount is to be suspended as it is not possible to settle it at a given time. 

The Postponed VAT functionality will be described based on sales credit memos, but it can be used in the following documents: Purchase Order, Purchase Invoice, Purchase Return Order, Purchase Credit Memo, Sales Order, Sales Invoice, Sales Return Order, Sales Credit Memo. The Postponed VAT field can be edited in general journal lines and in the VAT Additional Info window. After VAT transactions are posted, the postponed VAT date information is saved in posted documents, including: Posted Purchase Invoice, Posted Purchase Credit Memo, Posted Sales Invoice, Posted Sales Credit Memo. Postponed VAT is also saved in the following tables: VAT Entry and Detailed VAT Entry. 

In the subscriber we have the following code:

[EventSubscriber(ObjectType::Codeunit, Codeunit::"Purchase-Post Prepayments", 'OnAfterPostPrepaymentsOnBeforeThrowPreviewModeError', '', false, false)]
    local procedure 
...
    var
        VATManagement: Codeunit "ITI VATManagement";
    begin
        if PurchCrMemoHdr."ITI Postponed VAT" then
            VATManagement.PostponeVATForPurchaseDocument(PurchaseHeader, PurchInvHeader, PurchCrMemoHdr, GenJnlPostLine, SuppressCommit, PreviewMode);
    end;

Please let me know if you need additional info.
Regards
Wojciech

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
