### ISSUE TITLE
[EventRequest] Tab 39 Purchase Line

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#5156]
Due to Polish Localization App building, we need a publisher in Table 39. Polish localization modifies how the prepayment amount to deduct is calculated and we need to overwrite the standard behaviour
Function: CalcPrepaymentToDeduct
BEGIN
      // START/BC14PL
      IsHandled := false;
      OnBeforeCalcPrepaymentToDeduct(Rec, IsHandled);
       IF IsHandled THEN
            EXIT;
      // STOP/ BC14PL
      IF ("Qty. to Invoice" <> 0) AND ("Prepmt. Amt. Inv." <> 0) THEN BEGIN
        GetSalesHeader;
        IF ("Prepayment %" = 100) AND NOT IsFinalInvoice THEN
          "Prepmt Amt to Deduct" := GetLineAmountToHandle("Qty. to Invoice")
        ELSE
          "Prepmt Amt to Deduct" :=
            ROUND(
              ("Prepmt. Amt. Inv." - "Prepmt Amt Deducted") *
              "Qty. to Invoice" / (Quantity - "Quantity Invoiced"),Currency."Amount Rounding Precision")
      END ELSE
        "Prepmt Amt to Deduct" := 0
      
    END;
 
Publisher signature: [Integration] LOCAL PROCEDURE OnAfterCalcPrepaymentToDeduct@229(VAR PurchaseLine@1000 : Record 39; VAR IsHandled@1001 : Boolean);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
