### ISSUE TITLE
CU 7302 ShowSourceDocLine event needed

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5157]
Hi
before running the PAGE.RUNMODAL on any source type we have a solution prototype that would be good to be implemented as event:

![image](https://user-images.githubusercontent.com/53824412/70252105-13e1b300-1781-11ea-8a11-a9603c3c120e.png)

and the publisher signature would be:

![image](https://user-images.githubusercontent.com/53824412/70252143-2825b000-1781-11ea-973b-1979b41ec82b.png)

..in the goal of opening another page like:
![image](https://user-images.githubusercontent.com/53824412/70252262-68852e00-1781-11ea-93ab-9e262d590d22.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by VladimirVeljovic** [comment]
just to mension it would be also good to add for other options in same function DATABASE::"Prod. Order Component":, DATABASE::"Assembly Line": DATABASE::"Service Line":
