### ISSUE TITLE
[EventRequest] Codeunit 22 Item Jnl.-Post Line

### ISSUE THREAD

**Issue by dariocarozzi** [microsoft/ALAppExtensions#5158]
Hello,

could you please add an Event on COD22 so that it is possible to expand postitem() function
The Event like other Event in CU22 that include GlobalItemLedgEntry and ItemJnlLine.

Thanks!

![image](https://user-images.githubusercontent.com/51317290/70253210-10e7c200-1783-11ea-93de-220c11c1d9ff.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by dariocarozzi** [comment]
good morning, are there any news?
