### ISSUE TITLE
[Event Publisher Update Request] Codeunit 5813 Undo Purchase Receipt Line

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5159]
Hello.
In Codeunit 5813, publisher **OnBeforePostItemJnlLine**, the **parameter DocLineNo** needs to be **VAR**.

We are using this Codeunit to handle Type::"G/L Account" entries along with the Type::Item entries.
Part of that is to create purchase Accrual lines for the "G/L Account" lines, and for that we need to assign a new **DocLineNo** before we exit with an "IsHandled".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
