### ISSUE TITLE
[Event Request] Codeunit 5805 Item Charge Assgnt. (Purch.)

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5160]
Hello.
In Codeunit 5805 we need a new Event Publiser to get past the "Applies-to Doc. Type" filtering
after line
...
ItemChargeAssgntPurch.SETFILTER("Applies-to Doc. Type",'<>%1',ItemChargeAssgntPurch."Applies-to Doc. Type"::"Transfer Receipt");
**OnAfterAssignItemChargeAssgntPurchFilters**
...
    [Integration]
    LOCAL PROCEDURE OnAfterAssignItemChargeAssgntPurchFilters(**VAR ItemChargeAssgntPurch** : Record 5805);
    BEGIN
      // Add Event-Publisher for ItemCharge filtering.
    END;
...
We need to be able to handle Item Charges for "Transfer Receipt" documents.

PS: I thought I had created this issue a few days ago, but it doesn't show up as part of my issues. Hopefully I'm not duplicating it.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
