### ISSUE TITLE
[Bug] Codeunit 260 Document-Mailing

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5161]
Hello.
In codeunit 260, function "GetAttachmentFileName", 
...after line...
**ReportSelections.Usage::"P.Order",**
... add the line...
**ReportSelections.Usage::"P.Invoice",**
... before line...
**ReportSelections.Usage::"V.Remittance",**

Purchase Invoice should not show a text constant starting with "**Sales**…".
...
So the code will be:
    CASE ReportUsage OF
      ReportSelections.Usage::JQ,
      ReportSelections.Usage::"P.Order",
      **ReportSelections.Usage::"P.Invoice", // Added P.Invoice for CASE to not show "Sales...".**
      ReportSelections.Usage::"V.Remittance",
      ReportSelections.Usage::"P.V.Remit.":
        AttachmentFileName := STRSUBSTNO(JobsReportAsPdfFileNameMsg,EmailDocumentName,PostedDocNo);
...
PS: I tried to create this issue before, but cannot find it now. Hopefully I am not duplicating it.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
