### ISSUE TITLE
[Event Request] PAG 232 / 233 - OnBeforeSetApplyingCustLedgEntry / OnBeforeSetApplyingVendLedgEntry - IncludeSender

### ISSUE THREAD

**Issue by wbor-nvt** [microsoft/ALAppExtensions#5163]
Please set IncludeSender=true on
- Page 232 Apply Customer Entries - OnBeforeSetApplyingCustLedgEntry 
- Page 233 Apply Vendor Entries - OnBeforeSetApplyingVendLedgEntry

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
