### ISSUE TITLE
[Function Request] Codeunit 7171 Sales Info-Pane Management

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5164]
Hello.
In Codeunit 7171 we are sending a temporary "Sales Line" entry to get information for which does not connect to an existing "Sales Header".
So, we **need a new function** in the codeunit **to set a Temporary "Sales Header"** so that the GetSalesHeader function will not throw an error.
This way we can use this codeunit to get the relevant information without existing Sales Header or Sales Line.

...
**SetSalesHeader**(TmpSalesHeader : Record "Sales Header")
SalesHeader := TmpSalesHeader;

**Comment by RomanZanizdra** [comment]
Hi @KristjanGaukur.
There is an event OnBeforeGetSalesHeader() in the GetSalesHeader() function. You can use it to modify sales header in a way to completely skip getting of it.

**Comment by KristjanGaukur** [comment]
Hi @RomanZanizdra .
I have looked into all the newest versions of BC14 and BC15, and I do not find this event in Codeunit 7171. (But I find it in Table 37, f.ex.)
I need to let the codeunit know that the SalesHeader should not be fetched (as we are working with temporary data).

**Comment by RomanZanizdra** [comment]
Hi @KristjanGaukur .
Sorry for a little bit confusing you. Let's take a look at the function GetSalesHeader in the COD7171.
    local procedure GetSalesHeader(var SalesLine: Record "Sales Line")
    begin
        if (SalesLine."Document Type" <> SalesHeader."Document Type") or
           (SalesLine."Document No." <> SalesHeader."No.")
        then
            SalesHeader.Get(SalesLine."Document Type", SalesLine."Document No.");
    end;
We see that sales header is get when "document type" and "document no." in the line differs from the header. As you use temporary sales line then you can set "document type" to "quote" and "document no." to ''. Then header will not be read. For other cases where GetSalesHeader done in the sales line table, you can subscribe on OnBefore... event and skip getting of header. Does it make sense?
Also want to mention that originally functions with GetSalesHeader was not designed for temporary variables.

**Comment by KristjanGaukur** [comment]
Hi @RomanZanizdra .
This works for me. Thank you very much. I will close the issues.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
