### ISSUE TITLE
[Function Request] Codeunit 7181 Purchases Info-Pane Management

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5165]
Hello.
In Codeunit 7181 we are sending a temporary "Purchase Line" entry to get information for which does not connect to an existing "Purchase Header".
So, we **need a new function** in the codeunit **to set a Temporary "Purchase Header"** so that the GetPurchHeader function will not throw an error.
This way we can use this codeunit to get the relevant information without existing Purchase Header or Purchase Line.
...
**SetPurchHeader**(TmpPurchHeader : Record "Purchase Header")
PurchHeader := TmpPurchHeader;

**Comment by RomanZanizdra** [comment]
Hi @KristjanGaukur.
Here is the same recommendation as for [#5164 ]

**Comment by KristjanGaukur** [comment]
Hi @RomanZanizdra .
Same comment as for #5164:
I have looked into all the newest versions of BC14 and BC15, and I do not find this event in Codeunit 7181. (But I find it in Table 39, f.ex.)
I need to let the codeunit know that the SalesHeader should not be fetched (as we are working with temporary data).

**Comment by KristjanGaukur** [comment]
Hi @RomanZanizdra .
The solution from #5164 works here to. Thank you very much. I will close the issues.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
