### ISSUE TITLE
[Functions as Global] Codeunit 7010 Purch. Price Calc. Mgt.

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5166]
Hello.

We are utilizing 8 of the Purchase Price finding functions in Codeunit 7010 from outside the Codeunit (to get the correct Purchase Prices into a different table).
We need the following **8 function**s set **as GLOBAL**:

1 CalcBestDirectUnitCost
2 CalcBestLineDisc
3 FindPurchPrice
4 FindPurchLineDisc
5 SetCurrency
6 SetVAT
7 SetUoM
8 SetLineDisc

**Comment by AlexanderYakunin** [comment]
7 out of 8 procedures are already External in Master. Only SetLineDisc is local and can be made external. Please use latest code base for external requests, it will save time for both sides.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
