### ISSUE TITLE
Different Variable size in Codeunit 5812 Calculate Standard Cost

### ISSUE THREAD

**Issue by Hamdi-Amine** [microsoft/ALAppExtensions#5167]
Hello Team,
We need to increase a "PBOMVersionCode" variable size in codeunit 5812 Calculate Standard Cost.
it's must be 20 caracters. 

![image](https://user-images.githubusercontent.com/23724827/70326553-17367680-1835-11ea-9242-d721f6acd399.png)

![image](https://user-images.githubusercontent.com/23724827/70327346-eb1bf500-1836-11ea-85a4-2f43b9b7bf56.png)

Thanks.

**Comment by AlexanderYakunin** [comment]
We have Code[20] here
    local procedure SetProdBOMFilters(var ProdBOMLine: Record "Production BOM Line"; var PBOMVersionCode: Code[20]; ProdBOMNo: Code[20])

**Comment by Hamdi-Amine** [comment]
But the variable passed as an argument in function **SetProdBOMFilters**  is **code[10]**.
