### ISSUE TITLE
[EventRequest] Codeunit 22 Item Jnl.-Post Line

### ISSUE THREAD

**Issue by dariocarozzi** [microsoft/ALAppExtensions#5168]
Hello,

could you please add an Event on COD22 so that it is possible to expand ApplyItemLedgEntry function
The Event is necessary to change AppliedQty

Thanks!

![image](https://user-images.githubusercontent.com/51317290/70328191-bdd04680-1838-11ea-987c-bea07ac92791.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by dariocarozzi** [comment]
good morning, are there any news?
