### ISSUE TITLE
CU 12 additional parameter on event OnBeforeCustLedgEntryInsert and OnBeforeVendLedgEntryInsert needed

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5169]
hi,
we need additional parameter on event OnBeforeCustLedgEntryInsert and OnBeforeVendLedgEntryInsert, with existing variable GLReg.
so it would like OnBeforeCustLedgEntryInsert(CustLedgEntry,GenJnlLine,GLReg);
OnBeforeVendLedgEntryInsert(VendLedgEntry,GenJnlLine,GLReg);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
