### ISSUE TITLE
CU12 addition parameter needed on event  OnAfterVendLedgEntryInsert and OnAfterCustLedgEntryInsert

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5170]
Hi,
we need additional parameter OnAfterVendLedgEntryInsert,OnAfterCustLedgEntryInsert
DtldLedgEntryInserted which is standard

it would look like:

OnAfterVendLedgEntryInsert(VendLedgEntry,GenJnlLine,DtldLedgEntryInserted);
OnAfterCustLedgEntryInsert(CustLedgEntry,GenJnlLine,DtldLedgEntryInserted);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
