### ISSUE TITLE
 CU12 addition parameter needed on event OnAfterCustLedgEntryInsert and OnAfterVendLedgEntryInsert

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5171]
Hi,
we need additional parameter OnAfterCustLedgEntryInsert and OnAfterVendLedgEntryInsert 
DtldLedgEntryInserted which is standard

it would look like:

OnAfterCustLedgEntryInsert(CustLedgEntry,GenJnlLine,DtldLedgEntryInserted);
OnAfterVendLedgEntryInsert(VendLedgEntry,GenJnlLine,DtldLedgEntryInserted);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SUD-D365** [comment]
It would have been great if ** DtldLedgEntryInserted ** passed as VAR in the given events.
I have a scenario in which i need to prevent execution of below code
 **DtldCustLedgEntry.SetZeroTransNo(NextTransactionNo)**
