### ISSUE TITLE
CU12 additional parameter needed on event OnBeforeInsertGlobalGLEntry

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5172]
Hi 
we need additional parameter on event OnBeforeInsertGlobalGLEntry
GLReg. so:
OnBeforeInsertGlobalGLEntry(GlobalGLEntry,GenJnlLine,GLReg);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
