### ISSUE TITLE
[Event Request] Table 5741 Transfer Line OnBeforeCheckItemAvailable

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#5173]
[External] CheckItemAvailable(CalledByFieldNo : Integer)
//>NEW CODE
IsHandled := FALSE;
OnBeforeCheckItemAvailable(Rec,CalledByFieldNo,IsHandled,CurrFieldNo);
IF IsHandled THEN
  EXIT;
//<NEW CODE

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
