### ISSUE TITLE
CU 249 VAT Registraion Log Mgt

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#5174]
when importing customer through Webservice with "VAT Reg. No. Srv Config" enabled we have an issue with the confirm that is in CU 249 "VAT Registration Log Mgt" in procedure "UpdateRecordFromVATRegLog"

is it possible to provide an IF GUIALLOWED statement to prevent the confirm being triggered?

UpdateRecordFromVATRegLog(VAR RecordRef : RecordRef;RecordVariant : Variant;VATRegistrationLog : Record "VAT Registration Log")
RecordRef.GETTABLE(RecordVariant);
CASE VATRegistrationLog.Status OF
  VATRegistrationLog.Status::Valid:
    BEGIN
      IF HasAddress(VATRegistrationLog) THEN
        ConfirmQst := ValidVATNoQst
      ELSE
        ConfirmQst := ValidVATNoNoAddressQst;

**IF GUIALLOWED THEN**      
    IF CONFIRM(ConfirmQst) THEN
        PopulateFieldsFromVATRegLog(RecordRef,RecordVariant,VATRegistrationLog)
   **ELSE
        PopulateFieldsFromVATRegLog(RecordRef,RecordVariant,VATRegistrationLog)**
    END;
  VATRegistrationLog.Status::Invalid:
    MESSAGE(InvalidVatRegNoMsg);
  ELSE
    MESSAGE(NotVerifiedVATRegMsg);
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
