### ISSUE TITLE
[Access Request] Table 81 - Gen. Journal Line

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5182]
Hi Al team,

I would like to access the following functions and variables from the extension object

```
protected procedure GetCurrency()
    // local procedure GetCurrency()
    begin
        if "Additional-Currency Posting" =
           "Additional-Currency Posting"::"Additional-Currency Amount Only"
        then begin
            if GLSetup."Additional Reporting Currency" = '' then
                ReadGLSetup;
            CurrencyCode := GLSetup."Additional Reporting Currency";
        end else
            CurrencyCode := "Currency Code";    

protected var
        Currency: Record Currency;
        CurrExchRate: Record "Currency Exchange Rate";
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SWE-Tina** [comment]
Please keep this request in mind ;-). We need to call this function as well and want to avoid having duplicates. Thanks :)
