### ISSUE TITLE
[Access Request] Table 7321- Warehouse Shipment Line

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5183]
Hi Al team,

I would like to access the following variables from the extension object

```
    protected var
        WhseShptHeader: Record "Warehouse Shipment Header";
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
