### ISSUE TITLE
[Access Request] Table 5080 - To-do 

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5185]
Hi Al team,

I would like to access the following variables from the extension object

```
    protected var 
        TempRMCommentLine: Record "Rlshp. Mgt. Comment Line" temporary;
        TempTaskInteractionLanguage: Record "To-do Interaction Language" temporary;
TempAttachment: Record Attachment temporary;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
