### ISSUE TITLE
[Event Request] Codeunit 1101 - CA Jnl.-Check Line - RunCheck

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5188]
Could you please create an Integration event in Codeunit 1101 - CA Jnl.-Check Line, in function RunCheck?

```
[External] RunCheck(VAR CostJnlLine : Record "Cost Journal Line")
WITH CostJnlLine DO BEGIN
....
  // >>>>
  IsHandled := FALSE;
  OnRunCheckOnBeforeDateNotAllowed(CostJnlLine,IsHandled);
  IF NOT IsHandled THEN
  // <<<<
    IF GenJnlCheckLine.DateNotAllowed("Posting Date") THEN
      FIELDERROR("Posting Date",Text005);
....
END;
```

Event signature:

```
LOCAL [IntegrationEvent] OnRunCheckOnBeforeDateNotAllowed(VAR CostJnlLine : Record "Cost Journal Line";VAR IsHandled : Boolean)
```

We need this in our product to set the allowed posting date specifically for Cost Accounting.

**Comment by AlexanderYakunin** [comment]
We already have this possibility here
    procedure DateNotAllowed(PostingDate: Date): Boolean
    var
        SetupRecordID: RecordID;
    begin
        exit(IsDateNotAllowed(PostingDate, SetupRecordID));
    end;

    procedure IsDateNotAllowed(PostingDate: Date; var SetupRecordID: RecordID) DateIsNotAllowed: Boolean
    var
        UserSetupManagement: Codeunit "User Setup Management";
    begin
        DateIsNotAllowed := not UserSetupManagement.IsPostingDateValidWithSetup(PostingDate, SetupRecordID);
        OnAfterDateNoAllowed(PostingDate, DateIsNotAllowed);
        exit(DateIsNotAllowed);
    end;

**Comment by almatlansag** [comment]
In that existing event we cannot tell which journal is being posted (General or Cost Journal).
We would like to set the allowed posting date specifically for Cost Accounting.
Could you please check again?
Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
