### ISSUE TITLE
[Event Request] Codeunit 1100 - Cost Account Mgt - GetCostTypesFromChartDirect

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5189]
Could you please create an Integration event in Codeunit 1100 Cost Account Mgt, in function GetCostTypesFromChartDirect?

```
[External] GetCostTypesFromChartDirect()
....
WITH GLAcc DO BEGIN
  ....
      // >>>>
      OnGetCostTypesFromChartDirectOnBeforeCostTypeInsert(GLAcc,CostType,CostTypeExists);
      // <<<<
      IF NOT CostTypeExists THEN
        IF CostType.INSERT THEN BEGIN
          RecsCreated := RecsCreated + 1;
          "Cost Type No." := "No.";
        END;
  ....
END;

IndentCostTypes(TRUE);
```
Event signature:
```
LOCAL [IntegrationEvent] OnGetCostTypesFromChartDirectOnBeforeCostTypeInsert(VAR GLAcc : Record "G/L Account";VAR CostType : Record "Cost Type";VAR CostTypeExists : Boolean)
```
We need this in our product to transfer more fields.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
