### ISSUE TITLE
[Event Request] Codeunit 1100 - Cost Account Mgt - GetCostTypesFromChartDirect

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5190]
Could you please create an Integration event in Codeunit 1100 Cost Account Mgt, in function GetCostTypesFromChartDirect?

```
[External] GetCostTypesFromChartDirect()
....
WITH GLAcc DO BEGIN
  ....
END;

IndentCostTypes(TRUE);
// >>>>
OnAfterGetCostTypesFromChartDirect();
// <<<<
```
Event signature:
```
LOCAL [IntegrationEvent] OnAfterGetCostTypesFromChartDirect()
```
We need this in our product to update cost types.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
