### ISSUE TITLE
[Event Request] Codeunit 1100 - Cost Account Mgt - UpdateCostTypeFromGLAcc

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5191]
Could you please create an Integration event in Codeunit 1100 Cost Account Mgt, in function UpdateCostTypeFromGLAcc?

```
[External] UpdateCostTypeFromGLAcc(VAR GLAcc : Record "G/L Account";VAR xGLAcc : Record "G/L Account";CallingTrigger : 'OnInsert,OnModify,,OnRename')
....
CASE CallingTrigger OF
  ....
END;
// >>>>
OnAfterUpdateCostTypeFromGLAcc(CostType,GLAcc,xGLAcc,CallingTrigger);
// <<<<
IndentCostTypes(FALSE);
MESSAGE(Text017,CostType.TABLECAPTION,GLAcc."No.");
```
Event signature:
```
LOCAL [IntegrationEvent] OnAfterUpdateCostTypeFromGLAcc(VAR CostType : Record "Cost Type";VAR GLAcc : Record "G/L Account";VAR xGLAcc : Record "G/L Account";CallingTrigger : 'OnInsert,OnModify,,OnRename')
```
We need this in our product to update more fields.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
