### ISSUE TITLE
[Function Expose] Table 111 Sales Shipment Line: GetSalesInvLines

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5193]
Hello.

We need to get function GetSalesInvLines in table 111 "Sales Shipment Line" as GLOBAL, so that we can handle our special Item Charge management code correctly.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
