### ISSUE TITLE
v15 Modified Table Field Captions Reverted

### ISSUE THREAD

**Issue by mpopelka** [microsoft/ALAppExtensions#5194]
v15 upgrade was done on a tenant that had multiple table extensions created to modify base BC field captions, and all of the captions have reverted to their base caption. Republishing the extension does not resolve the issue. Page field caption changes and new custom table fields set with a caption still work. Has this functionality been removed?

Version: Platform 15.0.38375.0 + Application 15.0.36560.0

**Comment by mpopelka** [comment]
Will this issue be fixed any time soon? The caption changes are heavily utilized for the tenant.

**Comment by RomanZanizdra** [comment]
Hi @mpopelka .
Let me clarify the scenario. There is table which has an extension. Captions for fields are modified in this extension. After upgrade captions returned back. For which captions it returned back, standard field captions from table or captions from the page represented described table? Republishing of extension doesn't help. If captions on the page was updated on upgrade then you need to extend the page and update captions there. Can you also be more precise in your description, what table are talking about, what was changed there?

**Comment by RomanZanizdra** [comment]
Hi @mpopelka . Any update from you, or we can close the issue?

**Comment by RomanZanizdra** [comment]
Hi @mpopelka . Let's close it for now due to lack of information to figure out what is the problem and where is it.
Feel free to re-open the issue with more detailed and relevant description or contact support channel.

**Comment by mpopelka** [comment]
Yes the issue can be closed a minor release since the first major release to v15 must have fixed the issue.
