### ISSUE TITLE
Access Global Variables on Page "Service Tasks"

### ISSUE THREAD

**Issue by kvamsdal** [microsoft/ALAppExtensions#5195]
We need access to the variable "ResourceGroupFilter" on the page "Service Tasks". We can access the SetResourceGroupFilter procedure, but are not able to set the ResourceGroupFilter.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
