### ISSUE TITLE
[Function Expose] Table 121 Purch. Rcpt. Line: GetPurchInvLines

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5197]
Hello.
We need to get function GetPurchInvLines in table 121 "Purch. Rcpt. Line" as GLOBAL, so that we can handle our special Item Tracking management code for Lots correctly.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
