### ISSUE TITLE
[Access Request] Table 36 - Sales Header

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5198]
Hi Al team,

I would like to access the following variables from the extension object
    
```
protected var
        SalesLine: Record "Sales Line";
        SalesHeader: Record "Sales Header";
```

**Comment by AlexanderYakunin** [comment]
We have many events in Sales Header table, why do you need these variables exposed?

**Comment by AlexanderYakunin** [comment]
Exposing these VARs directly will block our further changes here. Please provide event requests instead.
