### ISSUE TITLE
[Access Request] Table 210 - Job Journal Line

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5199]
Hi Al team,

I would like to access the following variables from the extension object
   
 ```
// local procedure GetItemTranslation()
    protected procedure GetItemTranslation()
    begin
        GetJob;
        if ItemTranslation.Get("No.", "Variant Code", Job."Language Code") then begin
            Description := ItemTranslation.Description;
            "Description 2" := ItemTranslation."Description 2";
        end;
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
