### ISSUE TITLE
[Access Request] Page 46 - Sales Order Subform

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5200]
Hi Al team,

I would like to access the following variables from the extension object
```
    protected var
        IsBlankNumber: Boolean;
        IsCommentLine: Boolean;
       ShortcutDimCode: array[8] of Code[20];
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
