### ISSUE TITLE
[Access Request] Page 354 - Item Turnover Lines

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5201]
Hi Al team,

I would like to access the following variables and functions from the extension object

```
    protected var
        Item: Record Item;
```

```
// local procedure SetDateFilter()
    protected procedure SetDateFilter()
    begin
        if AmountType = AmountType::"Net Change" then
            Item.SetRange("Date Filter", "Period Start", "Period End")
        else
            Item.SetRange("Date Filter", 0D, "Period End");
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
