### ISSUE TITLE
[Event Request] Codeunit 1105 - Transfer GL Entries to CA - SkipGLEntry

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5202]
Could you please create an Integration event in Codeunit 1105 Transfer GL Entries to CA, in function SkipGLEntry?

```
LOCAL SkipGLEntry(GLEntry : Record "G/L Entry") : Boolean
// >>>>
OnBeforeSkipGLEntry(GLEntry,IsHandled,DoSkip);
IF IsHandled THEN
  EXIT(DoSkip);
// <<<<
GLAcc.GET(GLEntry."G/L Account No.");
CASE TRUE OF // exit on first TRUE, skipping the other checks
  ....
END;
```

Event signature:
```
LOCAL [IntegrationEvent] OnBeforeSkipGLEntry(GLEntry : Record "G/L Entry";VAR IsHandled : Boolean;VAR DoSkip : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
