### ISSUE TITLE
[Function Expose] Table 123 Purch. Inv. Line: FilterPstdDocLineValueEntries

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5205]
Hello.
We need function FilterPstdDocLineValueEntries in Table 123 "Purch. Inv. Line" set as GLOBAL.
We are checking the posted lines for our own copying of entries related to the Purch. Inv. Lines.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
