### ISSUE TITLE
Page 5415 - OnAfterSet

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#5207]
On Page 5415 "Item Avail. by Variant Lines" can we add a new publisher called **OnAfterSet**.

    procedure Set(var NewItem: Record Item; NewAmountType: Option "Net Change","Balance at Date")
    begin
        Item.Copy(NewItem);
        PeriodStart := Item.GetRangeMin("Date Filter");
        PeriodEnd := Item.GetRangeMax("Date Filter");
        AmountType := NewAmountType;
        OnAfterSet(Rec,Item,AmountType);         // NEW
        CurrPage.Update(false);
    end;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnAfterSet(ItemVariant: Record "Item Variant"; var Item: Record Item; AmountType: Option "Net Change","Balance at Date")
    begin
    end;   
    // NEW -

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
