### ISSUE TITLE
Cue Setup inaccessible

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/ALAppExtensions#5208]
Why is Cue Setup table not accessible for AL development?

I would like my install codeunit to set data in the CUe Setup table and from the activities page I would want the user to be able to access it too.

**Comment by atoader** [comment]
Hi, Luc! The right place to post questions like this is https://github.com/microsoft/ALAppExtensions . I've transferred the issue for you.

**Comment by AlexanderYakunin** [comment]
We decided to hide implementation of Cues, you should use codeunit 9701 "Cues And KPIs" instead.

**Comment by lvanvugt** [comment]
Hi Alexander, what is the reasoning behind?

**Comment by AlexanderYakunin** [comment]
You have API for operations with Cue Setup, and we can change internal implementation if needed. This is key principle of System App design.

**Comment by lvanvugt** [comment]
@AlexanderYakunin to m COD9701 doesn't look that straight forward. I.e. which function to use to allow me to add cue setup records for my activities page?

**Comment by AlexanderYakunin** [comment]
Please work with @JesperSchulz for System App related questions.

**Comment by miljance** [comment]
I think it should be possible to insert records in this table. Access Internal does not seem right if the table can be used System Wide.

**Comment by JesperSchulz** [comment]
We're going to look into this request once more.

**Comment by miljance** [comment]
Thanks. If table is not planned to be made externally available maybe the Cue Codeunit might be extended in order to allow setting up the default values in a similar manner as this PR:
https://github.com/microsoft/ALAppExtensions/pull/6808

**Comment by mazhelez** [comment]
@miljance 

Have you tried using [InsertData method](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Cues%20and%20KPIs#insertdata-method-)?

**Comment by lvanvugt** [comment]
> Have you tried using [InsertData method](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Cues%20and%20KPIs#insertdata-method-)?

Indeed that's what I did and it is working fine. Thanx.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
