### ISSUE TITLE
[Function Expose] Table 6651 Return Shipment Line: GetPurchCrMemoLines

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5210]
Hello.
We need function GetPurchCrMemoLines in Table 6651 "Return Shipment Line" set as GLOBAL.
We are checking the lines for our own handling of specific item charges.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
