### ISSUE TITLE
[Function Expose] Table 6661 Return Receipt Line: GetSalesCrMemoLines

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5211]
Hello.
We need function GetSalesCrMemoLines in Table 6661 "Return Receipt Line" set as GLOBAL.
We are checking the lines for our own handling of specific item charges.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
