### ISSUE TITLE
[EventRequest] Table 37 "Sales Line" [External] HasTypeToFillMandatoryFields

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5212]
We requested this back in septemper #4199, but we are missing some of the parameters 

From a newly pulled docker base app we can see the publisher is there but not with the parameters needed (see Screenshot) 

![image](https://user-images.githubusercontent.com/54017538/70520402-cb8a1280-1b3d-11ea-960a-d6cfdf4e8c5c.png)
![image](https://user-images.githubusercontent.com/54017538/70520373-bf9e5080-1b3d-11ea-84fa-fed41ac7a8ce.png)

Can we request does parameters so it looks like the following

![image](https://user-images.githubusercontent.com/54017538/70520528-fb391a80-1b3d-11ea-82e9-578884ffee98.png)
![image](https://user-images.githubusercontent.com/54017538/70520534-fffdce80-1b3d-11ea-8d94-d42ee603b231.png)

**Comment by AlexanderYakunin** [comment]
Handled event is not needed in this case, you simply assign ReturnValue in OnAfter event.
