### ISSUE TITLE
[Event Request] Codeunit 7312 OnBeforeWhseActivHeaderInsert

### ISSUE THREAD

**Issue by keshavopk** [microsoft/ALAppExtensions#5213]
Please add an additional Parameter TempWhseActivLine to the trigger OnBeforeWhseActivHeaderInsert:

OLD :- 
LOCAL [IntegrationEvent] OnBeforeWhseActivHeaderInsert(VAR WarehouseActivityHeader : Record "Warehouse Activity Header")
NEW:-
LOCAL [IntegrationEvent] OnBeforeWhseActivHeaderInsert(VAR WarehouseActivityHeader : Record "Warehouse Activity Header";TempWhseActivLine : Record "Warehouse Activity Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
