### ISSUE TITLE
[Event Request] Codeunit 5407 Prod. Order Status Management

### ISSUE THREAD

**Issue by RolandCsiba** [microsoft/ALAppExtensions#5214]
Please add a new Event in function CheckBeforeFinishProdOrder:

![image](https://user-images.githubusercontent.com/23257656/70525355-72bf7780-1b47-11ea-94ff-b2f0cf78dfd9.png)

Event:
LOCAL [IntegrationEvent] OnCheckMissingConsumption(VAR ProductionOrder : Record "Production Order";VAR ProdOrderLine : Record "Prod. Order Line";VAR ProdOrderComp : Record "Prod. Order Component";VAR ShowWarning : Boolean)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
