### ISSUE TITLE
[EventRequest] Table 39 “Puchase Line”,[External] HasTypeToFillMandatoryFields

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5215]
We have requested this before, and it was closed on sep 18th #4208 . But we are missing some parameters. 

from a newly pulled docker image containing the latest version of the base app the external HasTypeToFillMandatoryFields looks like this 
![image](https://user-images.githubusercontent.com/54017538/70529348-9c30d100-1b50-11ea-8885-24c69ff36221.png)
![image](https://user-images.githubusercontent.com/54017538/70529382-b2d72800-1b50-11ea-88c9-73399f0aa9a6.png)

but what we requested was the following 

![image](https://user-images.githubusercontent.com/54017538/70529404-bff41700-1b50-11ea-805d-479951ea543f.png)

is it possible to get this request :) ?

**Comment by AlexanderYakunin** [comment]
Handled event is not needed in this case, you simply assign ReturnValue in OnAfter event.
