### ISSUE TITLE
[EventRequest] Table 39 “Puchase Line”,UpdateWithWarehouseReceive[External] missing parameter

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5216]
Can we have another parameter on this, we requested it back on #4217 puchaseHeader: record "Puchase Header"

there are only 2 parameters right now, IsHandled and Vaar PurchaseLine

 
![image](https://user-images.githubusercontent.com/54017538/70529719-8e2f8000-1b51-11ea-8988-b59ba5e7cfc6.png)
![image](https://user-images.githubusercontent.com/54017538/70529742-98517e80-1b51-11ea-95b3-2a44cf7d77a6.png)

![image](https://user-images.githubusercontent.com/54017538/70529775-a6070400-1b51-11ea-8006-9feaf3630d16.png)

Thank you !

**Comment by AlexanderYakunin** [comment]
No, you should use GetPurchHeader at this point. We have following below

        GetPurchHeader;
        OnAfterUpdateWithWarehouseReceive(PurchHeader, Rec);

so you have access to PurchHeader if needed.
