### ISSUE TITLE
[EventRequest] Table 18 Customer - Get* Amount functions

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5217]
We require adjustments to the amount calculation. To make this possible we would like to request the following publishers which allow us to use different calculation:
1. Add more fields in current event

[External] GetTotalAmountLCY() : Decimal
OnBeforeGetTotalAmountLCY(Rec,**ReturnValue**,**IsHandled**);
**IF IsHandled THEN
  EXIT(ReturnValue);**

**Publisher**
LOCAL [IntegrationEvent] OnBeforeGetTotalAmountLCY(VAR Customer : Record Customer;VAR ReturnValue : Decimal;VAR IsHandled : Boolean)

2. In function  GetSalesLCY()  new event 

[External] GetSalesLCY() : Decimal
**OnBeforeGetSalesLCY(Rec,ReturnValue,IsHandled);
IF IsHandled THEN
  EXIT(ReturnValue);**

**Publisher** 
LOCAL [IntegrationEvent] OnBeforeGetSalesLCY(VAR Customer : Record Customer;VAR ReturnValue: Decimal;VAR IsHandled : Boolean)

3. In function [External] CalcOverdueBalance() OverDueBalance : Decimal new event 

**OnBeforeCalcOverdueBalance(Rec,OverDueBalance,IsHandled);
IF IsHandeled THEN
   EXIT;**

**Publisher**
LOCAL [IntegrationEvent] OnBeforeCalcOverdueBalance(VAR Customer : Record Customer;VAR OverDueBalance: Decimal;VAR IsHandled : Boolean)

4.  In Function [External] GetInvoicedPrepmtAmountLCY() : Decimal new event 

**OnBeforeGetInvoicedPrepmtAmountLCY(Rec,ReturnValue,IsHandled);
IF IsHandled THEN
  EXIT(ReturnValue);**

**Publisher** 
LOCAL [IntegrationEvent] OnBeforeGetInvoicedPrepmtAmountLCY(VAR Customer : Record Customer;VAR ReturnValue: Decimal;VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
