### ISSUE TITLE
[Access Request] Page 397 - Sales Invoice Statistics & Page 398 Sales Credit Memo Statistics & Page 6033 Service Invoice Statistics

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5221]
Hi Al team,

I would like to access the following variables from the extension object

```
    protected var
        AmountLCY: Decimal;
        CostLCY: Decimal;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
