### ISSUE TITLE
[EventRequest] Table 23 Vendor - Get* Amount functions

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5223]
We require adjustments to the amount calculation. To make this possible we would like to request the following publishers which allow us to use different calculation:

1. In function [External] CalcOverDueBalance() OverDueBalance : Decimal new event

[External] CalcOverDueBalance() OverDueBalance : Decimal
**OnBeforeCalcOverDueBalance(Rec,OverDueBalance ,IsHandled);
IF IsHandled THEN
EXIT(OverDueBalance );**

Publisher:
**LOCAL [IntegrationEvent] OnBeforeCalcOverDueBalance(VAR Vendor : Record Vendor;VAR OverDueBalance : Decimal;VAR IsHandled : Boolean)**

2. In function [External] GetInvoicedPrepmtAmountLCY() : Decimal new event

[External] GetInvoicedPrepmtAmountLCY() : Decimal
**OnBeforeGetInvoicedPrepmtAmountLCY(Rec,ReturnValue,IsHandled);
IF IsHandled THEN
EXIT(ReturnValue);**

Publisher:
**LOCAL [IntegrationEvent] OnBeforeGetInvoicedPrepmtAmountLCY(VAR Vendor : Record Vendor;VAR ReturnValue: Decimal;VAR IsHandled : Boolean)**

3. In function [External] GetTotalAmountLCY() : Decimal new event

[External] GetTotalAmountLCY() : Decimal
**OnBeforeGetTotalAmountLCY(Rec,ReturnValue,IsHandled);
IF IsHandled THEN
EXIT(ReturnValue);**

Publisher:
**LOCAL [IntegrationEvent] OnBeforeGetTotalAmountLCY(VAR Vendor : Record Vendor;VAR ReturnValue: Decimal;VAR IsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
