### ISSUE TITLE
[Access Request] Page 7326 - Whse. Phys. Invt. Journal

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5227]
Hi Al team,

I would like to access the following variables from the extension object
 
```
 protected var
        ItemDescription: Text[100];
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
