### ISSUE TITLE
[Access Request] Page 7352 - Put-AwayWorksheet

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5228]
Hi Al team,

I would like to access the following variables from the extension object

   ```
 protected var
        CurrentSortingMethod: Option " ",Item,Document,"Shelf/Bin No.","Due Date";
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
