### ISSUE TITLE
Variables wrong length in page 2000001 "EB Payment Journal"

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#5229]
page 2000001 "EB Payment Journal" contains a field "Account No;".
When entered the name of the corresponding 'No.'s ' is retrieved as variables on the page.
But these variables are still only text50. 
So there's a risk on overflow.

```
                field("Account No."; "Account No.")
                {
                    ApplicationArea = Basic, Suite;
                    ToolTip = 'Specifies the customer or vendor number that the entry on the journal line will be posted to.';

                    trigger OnValidate()
                    begin
                        PmtJrnlMgt.GetAccount(Rec, AccName, BankAccName);
                        ShowShortcutDimCode(ShortcutDimCode);
                    end;
                }

var
        AccName: Text[50];
        BankAccName: Text[50];
```

But
`procedure GetAccount(var PaymentJnlLine: Record "Payment Journal Line", var AccName: Text[100], var BankAccName: Text[100])`

using BC15CU0 onprem

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
