### ISSUE TITLE
[Access Request] Page 95 - Sales Quote Subform

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5232]
Hi Al team,

I would like to access the following variables from the extension object

```
protected var 
ShortcutDimCode: array[8] of Code[20];
```

**Comment by AlexanderYakunin** [comment]
We cannot make this as we currently do not support arrays as protected variables.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
