### ISSUE TITLE
[Event Request] Codeunit 1002 Job Create-Invoice

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#5234]
Requesting new event publisher on codeunit 1002 Job Create-Invoice.
OnDeleteSalesLineOnBeforeJobPlanningLineModify(var JobPlanningLine)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
