### ISSUE TITLE
[Event Request] Codeunit 365 Format Address

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5235]
We need to extend new event requests (that allready exists in any functions, like OnBeforeSalesHeaderBillTo) in Codeunit 365 - Format Address:

LOCAL [IntegrationEvent] OnBeforePurchHeaderBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchHeader : Record "Purchase Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchHeaderPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchHeader : Record "Purchase Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchHeaderShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchHeader : Record "Purchase Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesShptSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesShptHeader : Record "Sales Shipment Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesShptBillTo(VAR AddrArray : ARRAY [8] OF Text[100];ShipToAddr : ARRAY [8] OF Text[100];VAR SalesShptHeader : Record "Sales Shipment Header";VAR Handled : Boolean;VAR Result : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesInvSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesInvHeader : Record "Sales Invoice Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesInvShipTo(VAR AddrArray : ARRAY [8] OF Text[100];CustAddr : ARRAY [8] OF Text[100];VAR SalesInvHeader : Record "Sales Invoice Header";VAR Handled : Boolean;VAR Result : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesCrMemoSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesCrMemoHeader : Record "Sales Cr.Memo Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesCrMemoShipTo(VAR AddrArray : ARRAY [8] OF Text[100];CustAddr : ARRAY [8] OF Text[100];VAR SalesCrMemoHeader : Record "Sales Cr.Memo Header";VAR Handled : Boolean;VAR Result : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesRcptSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnRcptHeader : Record "Return Receipt Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesRcptBillTo(VAR AddrArray : ARRAY [8] OF Text[100];ShipToAddr : ARRAY [8] OF Text[100];VAR ReturnRcptHeader : Record "Return Receipt Header";VAR Handled : Boolean;VAR Result : Boolean)

LOCAL [IntegrationEvent] OnBeforeSalesRcptShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnRcptHeader : Record "Return Receipt Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchRcptBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchRcptHeader : Record "Purch. Rcpt. Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchRcptPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchRcptHeader : Record "Purch. Rcpt. Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchRcptShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchRcptHeader : Record "Purch. Rcpt. Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchInvBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchInvHeader : Record "Purch. Inv. Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchInvPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchInvHeader : Record "Purch. Inv. Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchInvShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchInvHeader : Record "Purch. Inv. Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchCrMemoBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchCrMemoHeader : Record "Purch. Cr. Memo Hdr.";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchCrMemoPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchCrMemoHeader : Record "Purch. Cr. Memo Hdr.";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchCrMemoShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchCrMemoHeader : Record "Purch. Cr. Memo Hdr.";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchShptBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnShptHeader : Record "Return Shipment Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchShptPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnShptHeader : Record "Return Shipment Header";VAR Handled : Boolean)

LOCAL [IntegrationEvent] OnBeforePurchShptShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnShptHeader : Record "Return Shipment Header";VAR Handled : Boolean)

called from functions:

[External] PurchHeaderBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchHeader : Record "Purchase Header")
**//INIT-INSERT
OnBeforePurchHeaderBuyFrom(AddrArray,PurchHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchHeader DO
  FormatAddr(
    AddrArray,"Buy-from Vendor Name","Buy-from Vendor Name 2","Buy-from Contact","Buy-from Address","Buy-from Address 2",
    "Buy-from City","Buy-from Post Code","Buy-from County","Buy-from Country/Region Code");

[External] PurchHeaderPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchHeader : Record "Purchase Header")
**//INIT-INSERT
OnBeforePurchHeaderPayTo(AddrArray,PurchHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchHeader DO
  FormatAddr(
    AddrArray,"Pay-to Name","Pay-to Name 2","Pay-to Contact","Pay-to Address","Pay-to Address 2",
    "Pay-to City","Pay-to Post Code","Pay-to County","Pay-to Country/Region Code");

[External] PurchHeaderShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchHeader : Record "Purchase Header")
**//INIT-INSERT
OnBeforePurchHeaderShipTo(AddrArray,PurchHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchHeader DO
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");

[External] SalesShptSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesShptHeader : Record "Sales Shipment Header")
**//INIT-INSERT
OnBeforeSalesShptSellTo(AddrArray,SalesShptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH SalesShptHeader DO
  FormatAddr(
    AddrArray,"Sell-to Customer Name","Sell-to Customer Name 2","Sell-to Contact","Sell-to Address","Sell-to Address 2",
    "Sell-to City","Sell-to Post Code","Sell-to County","Sell-to Country/Region Code");

[External] SalesShptBillTo(VAR AddrArray : ARRAY [8] OF Text[100];ShipToAddr : ARRAY [8] OF Text[100];VAR SalesShptHeader : Record "Sales Shipment Header") : Boolean
**//INIT-INSERT
OnBeforeSalesShptBillTo(AddrArray,ShipToAddr,SalesShptHeader,Handled,Result);
IF Handled THEN
  EXIT(Result);
//END-INSERT**

WITH SalesShptHeader DO BEGIN
  FormatAddr(
    AddrArray,"Bill-to Name","Bill-to Name 2","Bill-to Contact","Bill-to Address","Bill-to Address 2",
    "Bill-to City","Bill-to Post Code","Bill-to County","Bill-to Country/Region Code");
  IF "Bill-to Customer No." <> "Sell-to Customer No." THEN
    EXIT(TRUE);
  FOR i := 1 TO ARRAYLEN(AddrArray) DO
    IF ShipToAddr[i] <> AddrArray[i] THEN
      EXIT(TRUE);
END;
EXIT(FALSE);

[External] SalesInvSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesInvHeader : Record "Sales Invoice Header")
**//INIT-INSERT
OnBeforeSalesInvSellTo(AddrArray,SalesInvHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH SalesInvHeader DO
  FormatAddr(
    AddrArray,"Sell-to Customer Name","Sell-to Customer Name 2","Sell-to Contact","Sell-to Address","Sell-to Address 2",
    "Sell-to City","Sell-to Post Code","Sell-to County","Sell-to Country/Region Code");

[External] SalesInvShipTo(VAR AddrArray : ARRAY [8] OF Text[100];CustAddr : ARRAY [8] OF Text[100];VAR SalesInvHeader : Record "Sales Invoice Header") : Boolean
**//INIT-INSERT
OnBeforeSalesInvShipTo(AddrArray,CustAddr,SalesInvHeader,Handled,Result);
IF Handled THEN
  EXIT(Result);
//END-INSERT**

WITH SalesInvHeader DO BEGIN
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");
  IF "Sell-to Customer No." <> "Bill-to Customer No." THEN
    EXIT(TRUE);
  FOR i := 1 TO ARRAYLEN(AddrArray) DO
    IF AddrArray[i] <> CustAddr[i] THEN
      EXIT(TRUE);
END;
EXIT(FALSE);

[External] SalesCrMemoSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesCrMemoHeader : Record "Sales Cr.Memo Header")
**//INIT-INSERT
OnBeforeSalesCrMemoSellTo(AddrArray,SalesCrMemoHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH SalesCrMemoHeader DO
  FormatAddr(
    AddrArray,"Sell-to Customer Name","Sell-to Customer Name 2","Sell-to Contact","Sell-to Address","Sell-to Address 2",
    "Sell-to City","Sell-to Post Code","Sell-to County","Sell-to Country/Region Code");

[External] SalesCrMemoShipTo(VAR AddrArray : ARRAY [8] OF Text[100];CustAddr : ARRAY [8] OF Text[100];VAR SalesCrMemoHeader : Record "Sales Cr.Memo Header") : Boolean
**//INIT-INSERT
OnBeforeSalesCrMemoShipTo(AddrArray,CustAddr,SalesCrMemoHeader,Handled,Result);
IF Handled THEN
  EXIT(Result);
//END-INSERT**

WITH SalesCrMemoHeader DO BEGIN
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");
  IF "Sell-to Customer No." <> "Bill-to Customer No." THEN
    EXIT(TRUE);
  FOR i := 1 TO ARRAYLEN(AddrArray) DO
    IF AddrArray[i] <> CustAddr[i] THEN
      EXIT(TRUE);
END;
EXIT(FALSE);

[External] SalesRcptSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnRcptHeader : Record "Return Receipt Header")
**//INIT-INSERT
OnBeforeSalesRcptSellTo(AddrArray,ReturnRcptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH ReturnRcptHeader DO
  FormatAddr(
    AddrArray,"Sell-to Customer Name","Sell-to Customer Name 2","Sell-to Contact","Sell-to Address","Sell-to Address 2",
    "Sell-to City","Sell-to Post Code","Sell-to County","Sell-to Country/Region Code");

[External] SalesRcptBillTo(VAR AddrArray : ARRAY [8] OF Text[100];ShipToAddr : ARRAY [8] OF Text[100];VAR ReturnRcptHeader : Record "Return Receipt Header") : Boolean
**//INIT-INSERT
OnBeforeSalesRcptBillTo(AddrArray,ShipToAddr,ReturnRcptHeader,Handled,Result);
IF Handled THEN
  EXIT(Result);
//END-INSERT**

WITH ReturnRcptHeader DO BEGIN
  FormatAddr(
    AddrArray,"Bill-to Name","Bill-to Name 2","Bill-to Contact","Bill-to Address","Bill-to Address 2",
    "Bill-to City","Bill-to Post Code","Bill-to County","Bill-to Country/Region Code");
  IF "Bill-to Customer No." <> "Sell-to Customer No." THEN
    EXIT(TRUE);
  FOR i := 1 TO ARRAYLEN(AddrArray) DO
    IF AddrArray[i] <> ShipToAddr[i] THEN
      EXIT(TRUE);
END;
EXIT(FALSE);

[External] SalesRcptShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnRcptHeader : Record "Return Receipt Header")
**//INIT-INSERT
OnBeforeSalesRcptShipTo(AddrArray,ReturnRcptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH ReturnRcptHeader DO
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");

[External] PurchRcptBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchRcptHeader : Record "Purch. Rcpt. Header")
**//INIT-INSERT
OnBeforePurchRcptBuyFrom(AddrArray,PurchRcptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchRcptHeader DO
  FormatAddr(
    AddrArray,"Buy-from Vendor Name","Buy-from Vendor Name 2","Buy-from Contact","Buy-from Address","Buy-from Address 2",
    "Buy-from City","Buy-from Post Code","Buy-from County","Buy-from Country/Region Code");

[External] PurchRcptPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchRcptHeader : Record "Purch. Rcpt. Header")
**//INIT-INSERT
OnBeforePurchRcptPayTo(AddrArray,PurchRcptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchRcptHeader DO
  FormatAddr(
    AddrArray,"Pay-to Name","Pay-to Name 2","Pay-to Contact","Pay-to Address","Pay-to Address 2",
    "Pay-to City","Pay-to Post Code","Pay-to County","Pay-to Country/Region Code");

[External] PurchRcptShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchRcptHeader : Record "Purch. Rcpt. Header")
**//INIT-INSERT
OnBeforePurchRcptShipTo(AddrArray,PurchRcptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchRcptHeader DO
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");

[External] PurchInvBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchInvHeader : Record "Purch. Inv. Header")
**//INIT-INSERT
OnBeforePurchInvBuyFrom(AddrArray,PurchInvHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchInvHeader DO
  FormatAddr(
    AddrArray,"Buy-from Vendor Name","Buy-from Vendor Name 2","Buy-from Contact","Buy-from Address","Buy-from Address 2",
    "Buy-from City","Buy-from Post Code","Buy-from County","Buy-from Country/Region Code");

[External] PurchInvPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchInvHeader : Record "Purch. Inv. Header")
**//INIT-INSERT
OnBeforePurchInvPayTo(AddrArray,PurchInvHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchInvHeader DO
  FormatAddr(
    AddrArray,"Pay-to Name","Pay-to Name 2","Pay-to Contact","Pay-to Address","Pay-to Address 2",
    "Pay-to City","Pay-to Post Code","Pay-to County","Pay-to Country/Region Code");

[External] PurchInvShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchInvHeader : Record "Purch. Inv. Header")
**//INIT-INSERT
OnBeforePurchInvShipTo(AddrArray,PurchInvHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchInvHeader DO
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");

[External] PurchCrMemoBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchCrMemoHeader : Record "Purch. Cr. Memo Hdr.")
**//INIT-INSERT
OnBeforePurchCrMemoBuyFrom(AddrArray,PurchCrMemoHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchCrMemoHeader DO
  FormatAddr(
    AddrArray,"Buy-from Vendor Name","Buy-from Vendor Name 2","Buy-from Contact","Buy-from Address","Buy-from Address 2",
    "Buy-from City","Buy-from Post Code","Buy-from County","Buy-from Country/Region Code");

[External] PurchCrMemoPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchCrMemoHeader : Record "Purch. Cr. Memo Hdr.")
**//INIT-INSERT
OnBeforePurchCrMemoPayTo(AddrArray,PurchCrMemoHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchCrMemoHeader DO
  FormatAddr(
    AddrArray,"Pay-to Name","Pay-to Name 2","Pay-to Contact","Pay-to Address","Pay-to Address 2",
    "Pay-to City","Pay-to Post Code","Pay-to County","Pay-to Country/Region Code");

[External] PurchCrMemoShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR PurchCrMemoHeader : Record "Purch. Cr. Memo Hdr.")
**//INIT-INSERT
OnBeforePurchCrMemoShipTo(AddrArray,PurchCrMemoHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH PurchCrMemoHeader DO
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");

[External] PurchShptBuyFrom(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnShptHeader : Record "Return Shipment Header")
**//INIT-INSERT
OnBeforePurchShptBuyFrom(AddrArray,ReturnShptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH ReturnShptHeader DO
  FormatAddr(
    AddrArray,"Buy-from Vendor Name","Buy-from Vendor Name 2","Buy-from Contact","Buy-from Address","Buy-from Address 2",
    "Buy-from City","Buy-from Post Code","Buy-from County","Buy-from Country/Region Code");

[External] PurchShptPayTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnShptHeader : Record "Return Shipment Header")
**//INIT-INSERT
OnBeforePurchShptPayTo(AddrArray,ReturnShptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH ReturnShptHeader DO
  FormatAddr(
    AddrArray,"Pay-to Name","Pay-to Name 2","Pay-to Contact","Pay-to Address","Pay-to Address 2",
    "Pay-to City","Pay-to Post Code","Pay-to County","Pay-to Country/Region Code");

[External] PurchShptShipTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ReturnShptHeader : Record "Return Shipment Header")
**//INIT-INSERT
OnBeforePurchShptShipTo(AddrArray,ReturnShptHeader,Handled);
IF Handled THEN
  EXIT;
//END-INSERT**

WITH ReturnShptHeader DO
  FormatAddr(
    AddrArray,"Ship-to Name","Ship-to Name 2","Ship-to Contact","Ship-to Address","Ship-to Address 2",
    "Ship-to City","Ship-to Post Code","Ship-to County","Ship-to Country/Region Code");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
