### ISSUE TITLE
[Event Request] Codeunit 10753 “SII Job Upload Pending Docs.", - OnBeforeCreateSIIRequestForCustLedgEntry

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5237]
We need a new Event function in Codeunit 10753 “SII Job Upload Pending Docs.", named OnBeforeCreateSIIRequestForCustLedgEntry:

**LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForCustLedgEntry(CustLedgerEntry : Record "Cust. Ledger Entry";VAR IsHandled : Boolean)**

called from CreateSIIRequestForCustLedgEntry function, with a local boolean IsHandled var:

**_CreateSIIRequestForCustLedgEntry(VAR CustLedgEntry : Record "Cust. Ledger Entry")_**
IF NOT SIISetup.IsEnabled THEN
  EXIT;

**//INIT-INSERT
OnBeforeCreateSIIRequestForCustLedgEntry(CustLedgEntry,IsHandled);
IF IsHandled THEN
  EXIT;
//END-INSERT**

WITH CustLedgEntry DO BEGIN
  IF ISTEMPORARY OR
     (NOT ("Document Type" IN ["Document Type"::"Credit Memo","Document Type"::Invoice]))
  THEN
    EXIT;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
