### ISSUE TITLE
Functions from former TextManagement

### ISSUE THREAD

**Issue by Yu-457** [microsoft/ALAppExtensions#5239]
Hi Team,
im Missing the following functions

MakeText
MakeDateText
MakeTimeText
MakeDateTimeText

I couldnt find them in the breakingchanges.md regarding the TextManagement Codeunit. 
Can you help me on this please?`

Kind Regards

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by Yu-457** [comment]
Hi all, 
any news on this one? Will this get a fix?

Best Regards

**Comment by JesperSchulz** [comment]
Sorry that this one took "a little" longer, but I had to take a loooong walk down memory lane to figure out, what these helpers were doing. At some point, for reasons I could not dig out, the platform stopped calling these functions, which rendered them useless. When refactoring the TextManagement codeunit into the Filter Token System Module, we hence decided not to move those functions forward, as they have little to no purpose for us now. Unfortunately, that change somehow wasn't mentioned in the breaking change document - we're going to add a section soon. If you still need those functions for your implementation, please create copy of them in your solution.

**Comment by JesperSchulz** [comment]
Created PR to update breaking changes: #6308.

**Comment by CorpitalFDP** [comment]
Is the function in the MakeText where ? was used as a lookup to standard text implemented in another way or is it totally removed.

**Comment by JesperSchulz** [comment]
That functionality was removed a long time ago. I couldn't identify the last version where that worked, but it has been gone for a few releases now. I didn't dig too deep and hence don't know why that feature was discontinued. Is it sorely missed?

**Comment by CorpitalFDP** [comment]
One of our customers upgraded from NAV 2017 to BC Cloud has reported this as a bug after the upgrade.
I will check how widely they use this function and find a solution.

**Comment by Yu-457** [comment]
Hello Jesper, 
first of all thanks for the reply. 
I think for us its "okay" to use the original methods and just copy them. 
For the use case, and maybe for a re-evaluation of the topic, on the long term. 

We've been using it within our isv solution to emulate some questionnaire. 
Our customers are capable to configure a questionnaire in the addon to track certain informations. 
For this questionnaire we wanted to enable our customers to configure fields that behave like NAV would. So for a date field the typical constants should be evaluated. Options, numbers, texts. Everything basically should behave as if the field were a really strongly typed field to prevent wrong entries. 
The field in the backend was of course just a text-field, but we emulated the full standard behaviour on this. 
The requirement was to be able to attach an unlimited number of fields to our isv tables without customizing the solution. And without knowing beforhand which informations/data are needed. 
To transfer those fields again in an interface to a third party connection. This data could be contract data with all types of fields or just plain text references. Our customers can configure an interface to a third party connection without the need of any programming. 

We basically took the idea from the contact questionnaire and put it in our solution and enhanced it.  

So it would be really neat if we would have access to the full standard stack of the functions you are using for all types of fields. 
But in the short term i think and hope that we should be able to work with a copy of the old ones

Br
