### ISSUE TITLE
[Event Request] Codeunit 5640 Duplicate Depr. Book - OnBeforeGenJnlLineDuplicate

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5240]
We need a new Event in Codeunit 5640 "Duplicate Depr. Book", named OnBeforeGenJnlLineDuplicate:

**LOCAL [IntegrationEvent] OnBeforeGenJnlLineDuplicate(VAR GenJournalLine : Record "Gen. Journal Line";VAR FAAmount2 : Decimal)**

called from 

**_[External] DuplicateGenJnlLine(VAR GenJnlLine : Record "Gen. Journal Line";FAAmount2 : Decimal)_**
WITH GenJnlLine DO BEGIN
  **//INIT-INSERT
  OnBeforeGenJnlLineDuplicate(GenJnlLine,FAAmount2);
  //END-INSERT**
  FAAmount := FAAmount2;
  DeprBook.GET("Depreciation Book Code");
  IF "Insurance No." <> '' THEN
    InsertInsurance(TRUE,GenJnlLine,FAJnlLine2);
  IF ("Duplicate in Depreciation Book" = '') AND
     (NOT "Use Duplication List")
  THEN
    EXIT;
  ExchangeRate := GetExchangeRate("Account No.",DeprBook);
  IF "Duplicate in Depreciation Book" <> '' THEN BEGIN
    DeprBook.GET("Duplicate in Depreciation Book");
    CreateLine(TRUE,GenJnlLine,FAJnlLine2);
    EXIT;
  END;
  IF "Use Duplication List" THEN
    IF DeprBook.FIND('-') THEN
      REPEAT
        IF DeprBook."Part of Duplication List" AND (DeprBook.Code <> "Depreciation Book Code") THEN
          IF FADeprBook.GET("Account No.",DeprBook.Code) THEN
            CreateLine(TRUE,GenJnlLine,FAJnlLine2);
      UNTIL DeprBook.NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
