### ISSUE TITLE
[Event Request] Codeunit 408 DimensionManagement

### ISSUE THREAD

**Issue by IvoMol** [microsoft/ALAppExtensions#5242]
We are using external SQL tables, that contains fields like 'Global Dimension *', but we don't want to use them as Global Dimensions.

Please add integration evet into Codeunit 408:

    [IntegrationEvent(false, false)]
    local procedure **OnBeforeSetupObjectNoList**(var TempDimField: Record "Field" temporary)
    begin
    end;

called from function DefaultDimObjectNoWithGlobalDimsList:

    procedure **DefaultDimObjectNoWithGlobalDimsList**(var TempAllObjWithCaption: Record AllObjWithCaption temporary)
    var
        TempDimField: Record "Field" temporary;
        TempDimSetIDField: Record "Field" temporary;
    begin
        TempDimField.SetFilter(
          TableNo, '<>%1&<>%2&<>%3',
          DATABASE::"General Ledger Setup", DATABASE::"Job Task", DATABASE::"Change Global Dim. Header");
        TempDimField.SetFilter(ObsoleteState, '<>%1', TempDimField.ObsoleteState::Removed);
        TempDimField.SetFilter(FieldName, '*Global Dimension*');
        TempDimField.SetRange(Type, TempDimField.Type::Code);
        TempDimField.SetRange(Len, 20);
        FillNormalFieldBuffer(TempDimField);
        TempDimSetIDField.SetRange(RelationTableNo, DATABASE::"Dimension Set Entry");
        FillNormalFieldBuffer(TempDimSetIDField);
        **// ->
        OnBeforeSetupObjectNoList(TempDimField); // new publisher to exclude next tables and/or fields from global dimensions
        // <-**
        if TempDimField.FindSet then
            repeat
                TempDimSetIDField.SetRange(TableNo, TempDimField.TableNo);
                if TempDimSetIDField.IsEmpty then
                    DefaultDimInsertTempObject(TempAllObjWithCaption, TempDimField.TableNo);
            until TempDimField.Next = 0;
        OnAfterSetupObjectNoList(TempAllObjWithCaption);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
