### ISSUE TITLE
[Event Request] Table 36 - OnValidatePaymentTermsCodeOnBeforeCalculatePrepaymentDueDate

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5243]
Please add a new integration event OnValidatePaymentTermsCodeOnBeforeCalculatePrepaymentDueDate in Table 36

```
Payment Terms Code - OnValidate()
*Some code and then*
IF xRec."Payment Terms Code" = "Prepmt. Payment Terms Code" THEN BEGIN
  IF xRec."Prepayment Due Date" = 0D THEN
+  IsHandled := FALSE;
+  OnValidatePaymentTermsCodeOnBeforeCalculatePrepaymentDueDate(Rec,xRec,CurrFieldNo,IsHandled);
+  IF NOT IsHandled THEN
      "Prepayment Due Date" := CALCDATE(PaymentTerms."Due Date Calculation","Document Date");
  VALIDATE("Prepmt. Payment Terms Code","Payment Terms Code");
END;
```

New integration event
```
[Integration]
LOCAL PROCEDURE OnValidatePaymentTermsCodeOnBeforeCalculatePrepaymentDueDate(VAR SalesHeader: Record 36;VAR xSalesHeader: Record 36;CurrFieldNo: Integer;VAR IsHandled: Boolean);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
