### ISSUE TITLE
[Event Request]  Codeunit 10753 SII Job Upload Pending Docs. - OnBeforeCreateSIIRequestForDtldVendLedgEntry

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5244]
We need a new Event function in Codeunit 10753 “SII Job Upload Pending Docs.", named OnBeforeCreateSIIRequestForDtldVendLedgEntry:

**LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForDtldVendLedgEntry(DetailedVendorLedgEntry : Record "Detailed Vendor Ledg. Entry";VAR IsHandled : Boolean)**

called from CreateSIIRequestForDtldVendLedgEntry function, with a local boolean IsHandled var:

**_CreateSIIRequestForDtldVendLedgEntry(VAR DetailedVendorLedgEntry : Record "Detailed Vendor Ledg. Entry")_**
IF NOT SIISetup.IsEnabled THEN
  EXIT;
**//INIT-INSERT
OnBeforeCreateSIIRequestForDtldVendLedgEntry(DetailedVendorLedgEntry,IsHandled);
IF IsHandled THEN
  EXIT;
//END-INSERT**

WITH DetailedVendorLedgEntry DO BEGIN
  IF ISTEMPORARY THEN
    EXIT;

  IF ("Document Type" <> "Document Type"::Payment) OR
     ("Entry Type" <> "Entry Type"::Application) OR
     Unapplied OR
     ("Initial Document Type" = "Initial Document Type"::Payment) OR
     (NOT IsVendCashflowBased(DetailedVendorLedgEntry))
  THEN
    EXIT;

  VendorLedgerEntry.GET("Vendor Ledger Entry No.");
  IF VendorLedgerEntry."Document Type" = VendorLedgerEntry."Document Type"::Bill THEN BEGIN
    VendorLedgerEntry.SETRANGE("Document Type",VendorLedgerEntry."Document Type"::Invoice);
    VendorLedgerEntry.SETRANGE("Document No.",VendorLedgerEntry."Document No.");
    IF NOT VendorLedgerEntry.FINDFIRST THEN
      EXIT;
  END;

  SIIDocUploadState.CreateNewVendPmtRequest(
    "Entry No.",
    VendorLedgerEntry."Entry No.",
    VendorLedgerEntry."External Document No.","Posting Date");
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
