### ISSUE TITLE
[Event Request] Codeunit 10753 SII Job Upload Pending Docs. - OnBeforeCreateSIIRequestForDtldCustLedgEntry

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5245]
We need a new Event function in Codeunit 10753 “SII Job Upload Pending Docs.", named OnBeforeCreateSIIRequestForDtldCustLedgEntry:

**LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForDtldCustLedgEntry(DetailedCustLedgEntry : Record "Detailed Cust. Ledg. Entry";VAR IsHandled : Boolean)**

called from CreateSIIRequestForDtldCustLedgEntry function, with a local boolean IsHandled var:

**_CreateSIIRequestForDtldCustLedgEntry(VAR DetailedCustLedgEntry : Record "Detailed Cust. Ledg. Entry")_**
IF NOT SIISetup.IsEnabled THEN
  EXIT;
**//INIT-INSERT
OnBeforeCreateSIIRequestForDtldCustLedgEntry(DetailedCustLedgEntry,IsHandled);
IF IsHandled THEN
  EXIT;
//END-INSERT**
WITH DetailedCustLedgEntry DO BEGIN
  IF ISTEMPORARY THEN
    EXIT;

  IF ("Document Type" <> "Document Type"::Payment) OR
     ("Entry Type" <> "Entry Type"::Application) OR
     Unapplied OR
     ("Initial Document Type" = "Initial Document Type"::Payment) OR
     (NOT IsCustCashflowBased(DetailedCustLedgEntry))
  THEN
    EXIT;

  CustLedgerEntry.GET("Cust. Ledger Entry No.");
  IF CustLedgerEntry."Document Type" = CustLedgerEntry."Document Type"::Bill THEN BEGIN
    CustLedgerEntry.SETRANGE("Document Type",CustLedgerEntry."Document Type"::Invoice);
    CustLedgerEntry.SETRANGE("Document No.",CustLedgerEntry."Document No.");
    IF NOT CustLedgerEntry.FINDFIRST THEN
      EXIT;
  END;

  SIIDocUploadState.CreateNewCustPmtRequest(
    "Entry No.",
    CustLedgerEntry."Entry No.",
    CustLedgerEntry."Document No.","Posting Date");
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
