### ISSUE TITLE
[EventRequest] Codeunit 80 “Sales Post”, PostItemCharge [Local] missing parameter

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5246]
We requested this before back in #3874 but we are missing two parameters

TempItemChargeAssgntSales and ItemEntryNo

 
![image](https://user-images.githubusercontent.com/54017538/70625255-580e0100-1c22-11ea-8aa2-b1e8c8b4fc04.png)

from a pulled base app it's as follows

![image](https://user-images.githubusercontent.com/54017538/70625320-77a52980-1c22-11ea-992c-b64ceea5201f.png)
![image](https://user-images.githubusercontent.com/54017538/70625352-868bdc00-1c22-11ea-9b27-3a03fdd93b8f.png)

Is it possible to extend this with the two extra parameters from #3874 as mentioned ?

**Comment by AlexanderYakunin** [comment]
This is already done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
