### ISSUE TITLE
[EventRequest] codeunit 80 “Sales Post”, LOCAL PostUpdateOrderLine([local]  Missing parameters

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5247]
We requested this before on #4235 but we are missing one parameter 

VAR salesSetup : record Sales & receivables setup

![image](https://user-images.githubusercontent.com/54017538/70625984-dae38b80-1c23-11ea-9eb5-d4e5a0c18fe7.png)

From the pulled base app the publisher is as follows

![image](https://user-images.githubusercontent.com/54017538/70626117-19794600-1c24-11ea-90e1-d0384d56f33e.png)

![image](https://user-images.githubusercontent.com/54017538/70626086-0a929380-1c24-11ea-9886-62734cd8168b.png)

is it possible to extend this publisher as mentioned in #4235 with  VAR salesSetup : Record "Sales & Receivables Setup"

**Comment by AlexanderYakunin** [comment]
We added GetSalesSetup instead, as we agreed during design discussions.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
