### ISSUE TITLE
[EventRequest] Codeunit 22 “Item Jnl. – Post Line”, UpdateUnitCost [Local] missing parameter

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5248]
We have requested this before on #3845 but we are missing one parameter itemJournalLine : Record "Item Journal Line". 

![image](https://user-images.githubusercontent.com/54017538/70626775-56920800-1c25-11ea-85eb-4fbc7f7bd8a4.png)

from a newly pulled base app the publisher looks like the following
![image](https://user-images.githubusercontent.com/54017538/70626827-6d385f00-1c25-11ea-93b1-d1256bd63398.png)

![image](https://user-images.githubusercontent.com/54017538/70626849-76c1c700-1c25-11ea-8e39-210cab8dacb7.png)

is it possible to request a parameter extension to this publisher as mentioned in #3845

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
