### ISSUE TITLE
Table 11011 function CheckDate event needed

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5250]
Hi, 
we would like to extend check in funtion CheckDate therefore we need event like:

![image](https://user-images.githubusercontent.com/53824412/70629403-3add3080-1c2a-11ea-9c31-367f1104fcd6.png)

**Comment by AlexanderYakunin** [comment]
Please provide country code and full name of table.

**Comment by VladimirVeljovic** [comment]
oh yes, sorry...

table: 11011 "Sales VAT Advance Notification"
country code: DE

thanks

**Comment by AlexanderYakunin** [comment]
Table 11011 "Sales VAT Advance Notification" does not contain procedure CheckDate. Request cannot be processed.

**Comment by VladimirVeljovic** [comment]
Sorry thank you. We will refacture our code
