### ISSUE TITLE
Table 11011 function CalcEndDate event needed

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5251]
hi
we would like to have event on funtion CalcEndDate  to check other periods like:

![image](https://user-images.githubusercontent.com/53824412/70630368-c0151500-1c2b-11ea-8616-f089aabd7089.png)

**Comment by AlexanderYakunin** [comment]
Please provide country code and full name of table.

**Comment by AlexanderYakunin** [comment]
Table 11011 "Sales VAT Advance Notification" does not contain procedure CalcEndDate. Request cannot be processed.

**Comment by VladimirVeljovic** [comment]
> Sales VAT Advance Notification

you are right, sorry i mistakenly looked 14.x code instead of 15.x
