### ISSUE TITLE
[Access Request] Table 5954 "Work-Hour Template" - CalculateWeekTotal

### ISSUE THREAD

**Issue by plagijat** [microsoft/ALAppExtensions#5253]
Hi,

Can you make function CalculateWeekTotal in Table 5954 "Work-Hour Template" publicly available?
It can be reused in Extension Apps and processing of Work-Hour Templates.

Best,
Zoran M.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
