### ISSUE TITLE
[Event Request] Codeunit 13 - CopyGenJnlLineBalancingData(..)

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#5254]
Dear AL team,

I'd like to kindly ask you to consider adding the following event to Codeunit 13 "Gen. Jnl.-Post Batch", procedure CopyGenJnlLineBalancingData(..):
![GenJnlPostBatch-CopyGenJnlLineBalancingData](https://user-images.githubusercontent.com/42442951/70631595-0c655280-1c36-11ea-9b76-595d3f04b9bc.png)

Event signature:
![GenJnlPostBatch-OnAfterCopyGenJnlLineBalancingData](https://user-images.githubusercontent.com/42442951/70631622-18511480-1c36-11ea-8001-63753c286e76.png)

Thing is that we'd like to transfer some additional custom fields at this point along with the current fields.

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
