### ISSUE TITLE
[Event Request] Codeunit 9520 - OnAfterCheckValidEmailAddress

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5255]
#1758 has been wrongfully closed.

In codeunit 9520 "Mail Management", function CheckValidEmailAddress**es** indeed has the OnBeforeCheckValidEmailAddress publisher. (it should have been named OnBeforeCheckValidEmailAddress**es** instead)

However, function ValidateEmailAddressField calls CheckValidEmailAddress directly, so an additional OnAfterCheckValidEmailAddress would allow us to call ValidateEmailAddressField and add a custom regex mail validation via the new publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by daansaveyn** [comment]
When will this be available? I've checke the latest **BC16.1** but there's no sign of a **OnAfterCheckValidEmailAddres**s:

![image](https://user-images.githubusercontent.com/48217797/82897708-54640180-9f58-11ea-9d8a-c33388c4f541.png)
