### ISSUE TITLE
[Event Change Request] Table 121 Purch. Rcpt. Line: OnAfterCopyFromPurchRcptLine

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5256]
Hello.
In table 121 "Purch. Rcpt. Line", the publisher **OnAfterCopyFromPurchRcptLine** has 2 parameters.
InsertInvLineFromRcptLine (which is the only place that calls this publisher) is handling the copying of receipt lines over to invoice lines - and we need to affect the "Direct Unit Cost" that is used.

So, if in the publisher **OnAfterCopyFromPurchRcptLine** we would get the variable **PurchOrderLine** as an additional **VAR** parameter, we could set our specific "Direct Unit Cost" to be used, and not have to conditionalize the line
**PurchLine.VALIDATE("Direct Unit Cost",PurchOrderLine."Direct Unit Cost");**

PS: If it is not possible to add to the publisher, then a new publisher where we can handle the **PurchOrderLine** variable would be welcomed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
