### ISSUE TITLE
[Event Request] Codeunit 10750 SII XML Creator - OnBeforeGenerateXML

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5257]
We need a new event function in Codeunit 10750 "SII XML Creator", named OnBeforeGenerateXML:

**LOCAL [IntegrationEvent] OnBeforeGenerateXML(LedgerEntry : Variant;VAR XMLDocOut : DotNet "System.Xml.XmlDocument";UploadType : Option;IsCreditMemoRemoval : Boolean;VAR IsHandled : Boolean;VAR Result : Boolean)**

called from GenerateXML procedure, with two local variables of boolean type (IsHandled,Result):

**_GenerateXml(LedgerEntry : Variant;VAR XMLDocOut : DotNet "System.Xml.XmlDocument";UploadType : Option;IsCreditMemoRemoval : Boolean) : Boolean_**

**//INIT-INSERT
OnBeforeGenerateXML(LedgerEntry,XMLDocOut,UploadType,IsCreditMemoRemoval,IsHandled,Result);
IF IsHandled THEN
  EXIT(Result);
//END-INSERT**
GetSIISetup;
IF NOT IsInitialized THEN
  XMLDocOut := XMLDocOut.XmlDocument;

RecordRef.GETTABLE(LedgerEntry);
CASE RecordRef.NUMBER OF
  DATABASE::"Cust. Ledger Entry":
    BEGIN
      RecordRef.SETTABLE(CustLedgerEntry);
      IF UploadType = UploadTypeGlb::"Collection In Cash" THEN
        EXIT(CreateCollectionInCashXml(XMLDocOut,CustLedgerEntry,UploadType));
      EXIT(CreateInvoicesIssuedLedgerXml(CustLedgerEntry,XMLDocOut,UploadType,IsCreditMemoRemoval));
    END;
  DATABASE::"Vendor Ledger Entry":
    BEGIN
      RecordRef.SETTABLE(VendorLedgerEntry);
      EXIT(CreateInvoicesReceivedLedgerXml(VendorLedgerEntry,XMLDocOut,UploadType,IsCreditMemoRemoval));
    END;
.......
.......
.......

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
