### ISSUE TITLE
[Event Request] Table 36 - OnBeforeCheckShipmentInfo

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5259]
Hi, we would need event in standard function CheckShipmentInfo.. 
Event should look something like this:

```
LOCAL CheckShipmentInfo(VAR SalesLine : Record "Sales Line";BillTo : Boolean)
OnBeforeCheckShipmentInfo(Rec,xRec,SalesLine,BillTo,IsHandled);
IF IsHandled THEN
   EXIT:
```

Publisher should be:
```
LOCAL [IntegrationEvent] OnBeforeCheckShipmentInfo(VAR Rec : Record "Sales Header";xRec : Record "Sales Header";VAR SalesLine : Record "Sales Line";BillTo : Boolean;VAR IsHandled : Boolean)

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
