### ISSUE TITLE
Query 7150 - "Item Analysis View Source"

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5262]
Hi AL-Team,
can you add the following column to the query?
![Query7150](https://user-images.githubusercontent.com/48024891/70703809-1daf6d00-1cd1-11ea-9e84-6924aae2f3e3.png)

**Comment by AlexanderYakunin** [comment]
This change will finally require change of primary key in table Item Analysis View Entry table. Currently this is not possible.
