### ISSUE TITLE
[Event Request] Table 5601 function ConvertPostingType

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#5263]
Hello Team,

the publisher OnAfterConvertPostingType(Rec,FAJnlLine); has wrong parameter.
you set the rec as VAR instead of FAJnlLine.
It has to be changed, because you exited FAJnlLine afterwards:

OnAfterConvertPostingType(Rec,FAJnlLine);
EXIT(FAJnlLine."FA Posting Type");

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
