### ISSUE TITLE
[Event Request] Table 61 - Extend case statement with event

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5264]
Hi, we would like to have following events in order to extend functionality for other documents too..

1. In Function GetDocumentNo we would like something like this:

![image](https://user-images.githubusercontent.com/54843470/70704112-a62e0d80-1cd1-11ea-8676-8d4bdc405c0f.png)

Publisher will be:
```
LOCAL [IntegrationEvent] OnAfterGetDocumentNoBeforeError(DocumentVariant : Variant;VAR ReturnCode : Code[20];VAR IsHandled : Boolean)
```

2.We need event in function GetDocumentUsageForSalesHeader 
```
LOCAL GetDocumentUsageForSalesHeader(VAR DocumentUsage : Option;SalesHeader : Record "Sales Header")
OnBeforeGetDocumentUsageForSalesHeader(Rec,SalesHeader,DocumentUsage,IsHandled);
IF IsHandled THEN
  EXIT;
```
Publisher will be:
```
LOCAL [IntegrationEvent] OnBeforeGetDocumentUsageForSalesHeader(ElectronicDocumentFormat : Record "Electronic Document Format";SalesHeader: Record "Sales Header";VAR DocumentUsage : Option;VAR IsHandled : Boolean)
```

3. We need event in function GetDocumentUsageForServiceHeader, same as it is in previous but for Service
```
LOCAL GetDocumentUsageForServiceHeader(VAR DocumentUsage : Option;ServiceHeader: Record "Service Header")
OnBeforeGetDocumentUsageForServiceHeader(Rec,ServiceHeader,DocumentUsage,IsHandled);
IF IsHandled THEN
  EXIT;
```
Publisher will be:
```
LOCAL [IntegrationEvent] OnBeforeGetDocumentUsageForSalesHeader(ElectronicDocumentFormat : Record "Electronic Document Format";ServiceHeader: Record "Service Header";VAR DocumentUsage : Option;VAR IsHandled : Boolean)
```

4. In function GetDocumentType something like this
![image](https://user-images.githubusercontent.com/54843470/70705767-f490db80-1cd4-11ea-9e96-3ba34503a4d8.png)
Publisher will be:
```
LOCAL [IntegrationEvent] OnAfterGetDocumentType(DocumentVariant : Variant;VAR ReturnText : Text[50];VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
