### ISSUE TITLE
[Event Request] Table 5876 function CalcQtyAndTrackLinesExpected()

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#5265]
Hello Team, 

we need a new publisher to set more filter after this place:

  END ELSE BEGIN
    IF PhysInvtTrackingMgt.GetTrackingNosFromWhse(Item) THEN BEGIN
      WhseEntry.RESET;
      WhseEntry.SETCURRENTKEY("Location Code","Bin Code","Item No.","Variant Code");
      WhseEntry.SETRANGE("Location Code","Location Code");
      WhseEntry.SETRANGE("Bin Code","Bin Code");
      WhseEntry.SETRANGE("Item No.","Item No.");
      WhseEntry.SETRANGE("Variant Code","Variant Code");
      WhseEntry.SETRANGE("Registering Date",0D,PhysInvtOrderHeader."Posting Date");

-->NEW
     OnAfterFilterWhseEntry(Rec, VAR WhseEntry);

Thank you

**Comment by AlexanderYakunin** [comment]
We already have this event:

OnCalcQtyAndTrackLinesExpectedOnAfterSetWhseEntryFilters(WhseEntry, Rec);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
