### ISSUE TITLE
[Event Request] Table 337 - OnBeforeLock

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5271]
Hi, we would like new event on function Lock in table 337 Reservation Entry

Event should look like this:
```
[External] Lock()
OnBeforeLock(Rec,IsHandled);
IF IsHandled THEN
  EXIT;
```

Publisher should look like this:
```
LOCAL [IntegrationEvent] OnBeforeLock(VAR Rec : Record "Reservation Entry";VAR IsHandled: Boolean)
```

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this? Skipping of lock is dangerous thing.

**Comment by NemanjaKutlesic** [comment]
We have modification to check if Rec ISEMPTY, if it is, then we skip the Lock function

**Comment by AlexanderYakunin** [comment]
Need for locking is not related to the fact if you have no records for current item. This is needed for multi user system anyway.

**Comment by NemanjaKutlesic** [comment]
Okay, we will check if we have any problems with this in future..
