### ISSUE TITLE
T 7302 OnBeforeGetWhseLocation event needs var on parameter CurrentLocationCode

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5272]
Hi,
we need in table 7302 on event OnBeforeGetWhseLocation return value of parameter CurrentLocationCode. Could you please put VAR there.

![image](https://user-images.githubusercontent.com/53824412/70720270-cd95d200-1cf3-11ea-8569-af5a6ba25725.png)

**Comment by AlexanderYakunin** [comment]
Please check latest code in 15.X before doing request, we already have this implemented. In general we do not accept requests for 14.X code base, so please use 15.X AL code instead.

**Comment by VladimirVeljovic** [comment]
OK thanks, i see that you put VAR there. Tnx
