### ISSUE TITLE
[Bug] Codeunit 6620 - procedure CopyFromPurchLineItemChargeAssign

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#5273]
Hi,

When we copy from "Posted Purchase Cr. Memo with Charge (Item) lines" to Purchase Invoice, system fill wrong qty. and amount to table "Item Charge Assignment (Purch)", because calculated quantity is with (-) value.
Can you change following code:

local procedure CopyFromPurchLineItemChargeAssign

                        if ToPurchLine."Unit Cost" = 0 then
                            QtyToAssign := 0
                        else
                           // old 
                           //QtyToAssign := ValueEntry."Cost Amount (Actual)" * CurrencyFactor / ToPurchLine."Unit Cost";
                           // new
                           QtyToAssign := ABS(ValueEntry."Cost Amount (Actual)" * CurrencyFactor / ToPurchLine."Unit Cost");
                        SumQtyToAssign += QtyToAssign;

**Comment by RomanZanizdra** [comment]
Hi @Halilovast .
I cannot confirm the case you described. All quantities and amounts are correct when copy purchase document from posted credit memo.
Anyway, if you still think this is a bug, please reach out to the relevant support channels as specified in Product Support.

- On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 

- On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
