### ISSUE TITLE
[Event Request] Report 5692 Calculate Depreciation - OnBeforeCalculateDepreciation

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5274]
We need a new event function in Report 5692 - Calculate Depreciation, called OnBeforeCalculateDepreciation:

**LOCAL [IntegrationEvent] OnBeforeCalculateDepreciation(FANo : Code[20];VAR TempGenJournalLine : TEMPORARY Record "Gen. Journal Line";VAR TempFAJournalLine : TEMPORARY Record "FA Journal Line";VAR DeprAmount : Decimal;VAR NumberOfDays : Integer;DeprBookCode : Code[10];DeprUntilDate : Date;EntryAmounts : ARRAY [4] OF Decimal;DaysInPeriod : Integer)**

called from:

**_Fixed Asset - OnAfterGetRecord()_**
IF Inactive OR Blocked THEN
  CurrReport.SKIP;

**//INIT-INSERT
OnBeforeCalculateDepreciation("No.",TempGenJnlLine,TempFAJnlLine,DeprAmount,NumberOfDays,DeprBookCode,DeprUntilDate,EntryAmounts,DaysInPeriod);
//END-INSERT**

CalculateDepr.Calculate(
  DeprAmount,Custom1Amount,NumberOfDays,Custom1NumberOfDays,
  "No.",DeprBookCode,DeprUntilDate,EntryAmounts,0D,DaysInPeriod);
.....
.....
.....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
