### ISSUE TITLE
[Event Request] Report 5692 Calculate Depreciation - OnBeforeGetBalAcc2

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5276]
We need a new event function in Report 5692 "Calculate Depreciation", named OnBeforeGetBalAcc2:

**LOCAL [IntegrationEvent] OnBeforeGetBalAcc2(VAR GenJournalLine : Record "Gen. Journal Line";VAR GenJnlNextLineNo : Integer;VAR BalAccount : Boolean)**

called from

**_Fixed Asset - OnPostDataItem()_**
....
....
....
      "Line No." := GenJnlNextLineNo;
      OnBeforeGenJnlLineInsert(TempGenJnlLine,GenJnlLine);
      INSERT(TRUE);
      GenJnlLineCreatedCount += 1;
**//INIT-INSERT
      OnBeforeGetBalAcc2(GenJnlLine,GenJnlNextLineNo,BalAccount);
//END-INSERT**
      IF BalAccount THEN
        FAInsertGLAcc.GetBalAcc2(GenJnlLine,GenJnlNextLineNo);
    UNTIL TempGenJnlLine.NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
