### ISSUE TITLE
[Event Request] Report 5706 Create Stockkeeping Unit - OnBeforeItemOnPreDataItem

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5278]
We need a new event function in Report 5706 "Create Stockkeeping Unit", named- OnBeforeItemOnPreDataItem:

**LOCAL [IntegrationEvent] OnBeforeItemOnPreDataItem(VAR Item : Record Item)**

called from:

**_Item - OnPreDataItem()_**
**//INIT-INSERT
OnBeforeItemOnPreDataItem(Item);
//END-INSERT**
Location.SETRANGE("Use As In-Transit",FALSE);

DialogWindow.OPEN(
  Text000 +
  Text001 +
  Text002);

SaveFilters := TRUE;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
