### ISSUE TITLE
[Event Request] Report 5706 Create Stockkeeping Unit - OnBeforeItemOnAfterGetRecord

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5279]
We need a new event function in Report 5706 "Create Stockkeeping Unit", named  OnBeforeItemOnAfterGetRecord:

**LOCAL [IntegrationEvent] OnBeforeItemOnAfterGetRecord(VAR Item : Record Item;VAR IsHandled : Boolean)**

called from "Item - OnAfterGetRecord", including a local boolean var named IsHandled:

**_Item - OnAfterGetRecord()_**
**//INIT-INSERT
OnBeforeItemOnAfterGetRecord(Item,IsHandled);
IF IsHandled THEN
  CurrReport.SKIP;
//END-INSERT**
IF SaveFilters THEN BEGIN
  LocationFilter := GETFILTER("Location Filter");
  VariantFilter := GETFILTER("Variant Filter");
  SaveFilters := FALSE;
END;
SETFILTER("Location Filter",LocationFilter);
SETFILTER("Variant Filter",VariantFilter);
....
....
....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
