### ISSUE TITLE
[Event Request] Report 7000096 Redraw Receivable Bills - OnBeforeCheckUnrealizedVAT

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5280]
We need a new event function in Report 7000096 "Redraw Receivable Bills", named OnBeforeCheckUnrealizedVAT:

**LOCAL [IntegrationEvent] OnBeforeCheckUnrealizedVAT(CustLedgerEntry : Record "Cust. Ledger Entry";VAR IsHandled : Boolean)**

called from CheckUnrealizedVAT function, including a local boolean var named IsHandled:

**_CheckUnrealizedVAT(CustLedgEntry : Record "Cust. Ledger Entry")_**
**//INIT-INSERT
OnBeforeCheckUnrealizedVAT(CustLedgEntry,IsHandled);
IF IsHandled THEN
  EXIT;
//END-INSERT**
CustLedgEntry2.SETCURRENTKEY("Document No.","Document Type","Customer No.");
CustLedgEntry2.SETRANGE("Document No.",CustLedgEntry."Document No.");
CustLedgEntry2.SETRANGE("Document Type",CustLedgEntry."Document Type");
CustLedgEntry2.SETRANGE("Customer No.",CustLedgEntry."Customer No.");
IF CustLedgEntry2.FINDFIRST THEN
  ExistVATNOReal := GenJnlPostLine.CustFindVATSetup(VATPostingSetup,CustLedgEntry2,TRUE);
IF ExistVATNOReal THEN
  ERROR(Text1100101);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
