### ISSUE TITLE
[Event Request] Report 7000097 Reject Docs. - OnBeforeCustFindVATSetup

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5281]
We need a new event function in Report 7000097 "Reject Docs.", named OnBeforeCustFindVATSetup:

**LOCAL [IntegrationEvent] OnBeforeCustFindVATSetup(VAR VATSetup : Record "VAT Posting Setup";CustLedgerEntry : Record "Cust. Ledger Entry";VAR IsFromJournal : Boolean)**

called from:

**_CustLedgEntry - OnAfterGetRecord()_**
IsRedrawn := CarteraManagement.CheckFromRedrawnDoc("Bill No.");
DocCount := DocCount + 1;
Window.UPDATE(1,DocCount);

IF GLSetup."Unrealized VAT" AND
   (("Document Type" = "Document Type"::Bill) OR ("Document Type" = "Document Type"::Invoice))
THEN BEGIN
  FromJnl := FALSE;
  IF PostedDoc."From Journal" THEN
    FromJnl := TRUE;
**//INIT-INSERT  
OnBeforeCustFindVATSetup(VATPostingSetup,CustLedgEntry,FromJnl);
//END-INSERT**
  ExistsNoRealVAT := GenJnlPostLine.CustFindVATSetup(VATPostingSetup,CustLedgEntry,FromJnl);
END;

IF ArePostedDocs THEN BEGIN
  PostedDoc.GET(PostedDoc.Type::Receivable,"Entry No.");
  PostedBillGr.GET(PostedDoc."Bill Gr./Pmt. Order No.");
  IF PostedBillGr."Dealing Type" = PostedBillGr."Dealing Type"::Discount THEN
....
....
....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
