### ISSUE TITLE
[Event Request] Report 7000099 Post Bill Group - OnBeforeDocOnPostDataItem

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5282]
We need a new event function in Report 7000099 "Post Bill Group", named OnBeforeDocOnPostDataItem:

**LOCAL [IntegrationEvent] OnBeforeDocOnPostDataItem(VAR CarteraDoc : Record "Cartera Doc.";VAR BGPOPostBuffer : TEMPORARY Record "BG/PO Post. Buffer")**

called from:

**_Doc - OnPostDataItem()_**
**//INIT-INSERT
OnBeforeDocOnPostDataItem(Doc,BGPOPostBuffer);
//END-INSERT**
GroupAmount := 0;
SumLCYAmt := 0;
IF NOT BGPOPostBuffer.FIND('-') THEN
  EXIT;
....
....
....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
