### ISSUE TITLE
[Event Request] Report 295

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#5283]
Start of the Trigger "Sales Shipment Line"
```
OnBeforeSalesShipmentLineOnAfterGetRecord(var "Sales Shipment Line";var Handled boolean)
IF Handled THEN
  CurrReport.SKIP;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
