### ISSUE TITLE
Notes and RecordLinks are not displayed if no further Factbox is active

### ISSUE THREAD

**Issue by frobiii** [microsoft/ALAppExtensions#5284]
On a page that only has the system factboxes RecordLinks and Notes, these are not displayed.
RecordLinks and Notes are only displayed if there is at least one other Factbox on the page.
Applies to all bc standard and individual pages.

Example not working:

```
pageextension 50100 "Test Factboxes" extends "Shipping Agents"
{
    layout
    {
        modify(Control1900383207)
        {
            Visible = true;
        }

        modify(Control1905767507)
        {
            Visible = true;
        }
    }
}

```

Result: You can see the factbox area but no record links and notes.

Example with any other factbox, doesnt matter which, no SubPageLink...

```
pageextension 50100 "Test Factboxes" extends "Shipping Agents"
{
    layout
    {
        modify(Control1900383207)
        {
            Visible = true;
        }

        modify(Control1905767507)
        {
            Visible = true;
        }

        addfirst(factboxes)
        {
            part(Test; "Customer Details FactBox")
            {
                ApplicationArea = All;
            }
        }
    }
}
```

Result: Works as expected

**Comment by AlexanderYakunin** [comment]
@kotelko

**Comment by AlexanderYakunin** [comment]
This is By Design

**Comment by frobiii** [comment]
I don't get it. Why do you even add system factboxes to this pages when it's not possible to display them?
What is the reason you disigned it like this? It worked in roletailored client.
