### ISSUE TITLE
[EventRequest] Codeunit 7150 - OnAfterInitializeTempItemAnalysisViewEntry 

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5285]
Hi,
we need the following event in Codeunit 7150 (Function: UpdateAnalysisViewEntry) when inserting or updating the Item Analysis View Entry:

Event: OnAfterInitializeTempItemAnalysisViewEntry
![59437115-3eb20680-8df1-11e9-8566-e0cdeb7c3248](https://user-images.githubusercontent.com/48024891/70785717-5a3f9f00-1d8b-11ea-8711-0e374f615472.png)

The following parameters are required:
LOCAL [IntegrationEvent] OnAfterInitializeTempItemAnalysisViewEntry(VAR TempItemAnalysisViewEntry : TEMPORARY Record "Item Analysis View Entry";ItemAnalysisViewSource : Query "Item Analysis View Source";ItemAnalysisView : Record "Item Analysis View")

Thanks

**Comment by AlexanderYakunin** [comment]
This event already exist
OnAfterInitializeTempItemAnalysisViewEntry(TempItemAnalysisViewEntry, ItemAnalysisView);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by MattiLE** [comment]
Hi Alexander, 
you are right. But one of the requested paremeter is missing: 
Can you please add the variable ItemAnalysisViewSource as var to the publisher?

**Comment by AlexanderYakunin** [comment]
Yes
