### ISSUE TITLE
Serial No. And Lot No. Used together - Need to bypass Qty. [-1,0,1] Check on Serial No

### ISSUE THREAD

**Issue by RabePienaar** [microsoft/ALAppExtensions#5286]
In certain scenarios business would like to use a combination of serial and lot no. together when tracking inventory. 

Example 1 - Manufacturing Company produces metal piping from a single coil of metal. Coil No = Serial No and Lot No = Unique No per Production Run. the metal coil base unit of measure is KG so Coil 001 = 234 KG and quantity stored in Item Ledger Entry is 234. 

Example 2 - Lot No. is used to track 12 Boxes of Product all assigned the same lot, these 12 Boxes are all put onto the same Pallet where Pallet No. is represented by Serial No.

Both these scenarios are currently not possible unless making changes to base version on the following objects :

**1. Table 336 - Tracking Specification - Function CheckSerialNoQty - Need to call validate SkipSerialNoQtyValidation**

       
        // Change Required ********************************
        if SkipSerialNoQtyValidation then
          exit;
        // Change Required ********************************
        
        if "Serial No." = '' then
            exit;
        if not ("Quantity (Base)" in [-1, 0, 1]) then
            Error(Text003, FieldCaption("Quantity (Base)"), FieldCaption("Serial No."));
        if not ("Qty. to Handle (Base)" in [-1, 0, 1]) then
            Error(Text003, FieldCaption("Qty. to Handle (Base)"), FieldCaption("Serial No."));
        if not ("Qty. to Invoice (Base)" in [-1, 0, 1]) then
            Error(Text003, FieldCaption("Qty. to Invoice (Base)"), FieldCaption("Serial No."));

**2. Codeunit 22 - Item Jnl.-Post Line - Function InsertItemLedgEntry**

    

    **2.1. Add New Procedure**

    procedure SetSkipSerialNoQtyValidation(NewVal: Boolean)
    begin
        SkipSerialNoQtyValidation := NewVal;
    end;

    **2.2. Modify Procedure - InsertItemLedgEntry**

                if ItemTrackingCode."SN Specific Tracking" then begin
                    if ItemLedgEntry.Quantity > 0 then
                        CheckItemSerialNo(ItemJnlLine);

                    // Change Required ********************************
                    if not SkipSerialNoQtyValidation then
                    // Change Required ********************************
                    if not (ItemLedgEntry.Quantity in [-1, 0, 1]) then
                        Error(Text033);
                    
                end;

**Alternative :**

I'm able to bypass the checks on table 336 - using the onbeforevalidate and onafervalidate triggers, but have no option to bypass the check on the codeunit at this stage. I also do not see a option on how to add a IntegrationEvent in order to bypass the check.

The requested changes has zero impact on item tracking, item reservations, etc.

Regards
Rabe Pienaar

**Comment by AlexanderYakunin** [comment]
We have OnBefore events in both places and you can easily bypass using them. We also implements SkipSerialNoQtyValidation for consistency.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
