### ISSUE TITLE
[Event Request] Report 790 - Calculate Inventory

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5289]
Hi AL-Team,

can you please add the following Publisher?

procedure InsertItemJnlLine(ItemNo: Code[20]; VariantCode2: Code[10]; DimEntryNo2: Integer; BinCode2: Code[20]; Quantity2: Decimal; PhysInvQuantity: Decimal)
    var
        ItemLedgEntry: Record "Item Ledger Entry";
        ReservEntry: Record "Reservation Entry";
        WhseEntry: Record "Warehouse Entry";
        WhseEntry2: Record "Warehouse Entry";
        Bin: Record Bin;
        DimValue: Record "Dimension Value";
        CreateReservEntry: Codeunit "Create Reserv. Entry";
        DimMgt: Codeunit DimensionManagement;
        EntryType: Option "Negative Adjmt.","Positive Adjmt.";
        NoBinExist: Boolean;
        OrderLineNo: Integer;
    begin
        OnBeforeFunctionInsertItemJnlLine(ItemNo, VariantCode2, DimEntryNo2, BinCode2, Quantity2, PhysInvQuantity);

        with ItemJnlLine do begin
            if NextLineNo = 0 then begin
                LockTable;
                SetRange("Journal Template Name", "Journal Template Name");
                SetRange("Journal Batch Name", "Journal Batch Name");
                if FindLast then
                    NextLineNo := "Line No.";

                SourceCodeSetup.Get;
            end;
            NextLineNo := NextLineNo + 10000;

            if (Quantity2 <> 0) or ZeroQty then begin
                if (Quantity2 = 0) and Location."Bin Mandatory" and not Location."Directed Put-away and Pick"
                then
                    if not Bin.Get(Location.Code, BinCode2) then
                        NoBinExist := true;

                Init;
                // NEW >>>>
                OnBeforeValidateItemJnlLine(ItemJnlLine);
                // NEW <<<<
                "Line No." := NextLineNo;
                Validate("Posting Date", PostingDate);
                if PhysInvQuantity >= Quantity2 then
                    Validate("Entry Type", "Entry Type"::"Positive Adjmt.")
                else
                    Validate("Entry Type", "Entry Type"::"Negative Adjmt.");
                Validate("Document No.", NextDocNo);
                Validate("Item No.", ItemNo);
                Validate("Variant Code", VariantCode2);
                Validate("Location Code", Location.Code);
                if not NoBinExist then
                    Validate("Bin Code", BinCode2)
                else
                    Validate("Bin Code", '');
                Validate("Source Code", SourceCodeSetup."Phys. Inventory Journal");
                "Qty. (Phys. Inventory)" := PhysInvQuantity;
                "Phys. Inventory" := true;
                Validate("Qty. (Calculated)", Quantity2);
                "Posting No. Series" := ItemJnlBatch."Posting No. Series";
                "Reason Code" := ItemJnlBatch."Reason Code";

                "Phys Invt Counting Period Code" := PhysInvtCountCode;
                "Phys Invt Counting Period Type" := CycleSourceType;

                if Location."Bin Mandatory" then
                    "Dimension Set ID" := 0;
                "Shortcut Dimension 1 Code" := '';
                "Shortcut Dimension 2 Code" := '';

                ItemLedgEntry.Reset;
                ItemLedgEntry.SetCurrentKey("Item No.");
                ItemLedgEntry.SetRange("Item No.", ItemNo);
                if ItemLedgEntry.FindLast then
                    "Last Item Ledger Entry No." := ItemLedgEntry."Entry No."
                else
                    "Last Item Ledger Entry No." := 0;

                Insert(true);
                OnAfterInsertItemJnlLine(ItemJnlLine);

                if Location.Code <> '' then
                    if Location."Directed Put-away and Pick" then begin
                        WhseEntry.SetCurrentKey(
                          "Item No.", "Bin Code", "Location Code", "Variant Code", "Unit of Measure Code",
                          "Lot No.", "Serial No.", "Entry Type");
                        WhseEntry.SetRange("Item No.", "Item No.");
                        WhseEntry.SetRange("Bin Code", Location."Adjustment Bin Code");
                        WhseEntry.SetRange("Location Code", "Location Code");
                        WhseEntry.SetRange("Variant Code", "Variant Code");
                        if "Entry Type" = "Entry Type"::"Positive Adjmt." then
                            EntryType := EntryType::"Negative Adjmt.";
                        if "Entry Type" = "Entry Type"::"Negative Adjmt." then
                            EntryType := EntryType::"Positive Adjmt.";
                        WhseEntry.SetRange("Entry Type", EntryType);
                        // NEW <<<<
                        OnBeforeFindWhseEntry(WhseEntry, ItemJnlLine);
                        // NEW >>>>
                        if WhseEntry.Find('-') then
                            repeat
                                WhseEntry.SetRange("Lot No.", WhseEntry."Lot No.");
                                WhseEntry.SetRange("Serial No.", WhseEntry."Serial No.");
                                WhseEntry.CalcSums("Qty. (Base)");

                                WhseEntry2.SetCurrentKey(
                                  "Item No.", "Bin Code", "Location Code", "Variant Code", "Unit of Measure Code",
                                  "Lot No.", "Serial No.", "Entry Type");
                                WhseEntry2.CopyFilters(WhseEntry);
                                case EntryType of
                                    EntryType::"Positive Adjmt.":
                                        WhseEntry2.SetRange("Entry Type", WhseEntry2."Entry Type"::"Negative Adjmt.");
                                    EntryType::"Negative Adjmt.":
                                        WhseEntry2.SetRange("Entry Type", WhseEntry2."Entry Type"::"Positive Adjmt.");
                                end;
                                WhseEntry2.CalcSums("Qty. (Base)");
                                if Abs(WhseEntry2."Qty. (Base)") > Abs(WhseEntry."Qty. (Base)") then
                                    WhseEntry."Qty. (Base)" := 0
                                else
                                    WhseEntry."Qty. (Base)" := WhseEntry."Qty. (Base)" + WhseEntry2."Qty. (Base)";

                                if WhseEntry."Qty. (Base)" <> 0 then begin
                                    if "Order Type" = "Order Type"::Production then
                                        OrderLineNo := "Order Line No.";
                                    CreateReservEntry.CreateReservEntryFor(
                                      DATABASE::"Item Journal Line",
                                      "Entry Type",
                                      "Journal Template Name",
                                      "Journal Batch Name",
                                      OrderLineNo,
                                      "Line No.",
                                      "Qty. per Unit of Measure",
                                      Abs(WhseEntry.Quantity),
                                      Abs(WhseEntry."Qty. (Base)"),
                                      WhseEntry."Serial No.",
                                      WhseEntry."Lot No.");
                                    if WhseEntry."Qty. (Base)" < 0 then             // only Date on positive adjustments
                                        CreateReservEntry.SetDates(WhseEntry."Warranty Date", WhseEntry."Expiration Date");
                                    CreateReservEntry.CreateEntry(
                                      "Item No.",
                                      "Variant Code",
                                      "Location Code",
                                      Description,
                                      0D,
                                      0D,
                                      0,
                                      ReservEntry."Reservation Status"::Prospect);
                                end;
                                WhseEntry.Find('+');
                                WhseEntry.SetRange("Lot No.");
                                WhseEntry.SetRange("Serial No.");
                            until WhseEntry.Next = 0;
                    end;

                if ColumnDim = '' then
                    DimEntryNo2 := CreateDimFromItemDefault;

                if DimBufMgt.GetDimensions(DimEntryNo2, TempDimBufOut) then begin
                    TempDimSetEntry.Reset;
                    TempDimSetEntry.DeleteAll;
                    if TempDimBufOut.Find('-') then begin
                        repeat
                            DimValue.Get(TempDimBufOut."Dimension Code", TempDimBufOut."Dimension Value Code");
                            TempDimSetEntry."Dimension Code" := TempDimBufOut."Dimension Code";
                            TempDimSetEntry."Dimension Value Code" := TempDimBufOut."Dimension Value Code";
                            TempDimSetEntry."Dimension Value ID" := DimValue."Dimension Value ID";
                            if TempDimSetEntry.Insert then;
                            "Dimension Set ID" := DimMgt.GetDimensionSetID(TempDimSetEntry);
                            DimMgt.UpdateGlobalDimFromDimSetID("Dimension Set ID",
                              "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
                            Modify;
                        until TempDimBufOut.Next = 0;
                        TempDimBufOut.DeleteAll;
                    end;
                end;
            end;
        end;
        OnAfterFunctionInsertItemJnlLine(ItemNo, VariantCode2, DimEntryNo2, BinCode2, Quantity2, PhysInvQuantity, ItemJnlLine);
    end;    

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateItemJnlLine(var ItemJournalLine: Record "Item Journal Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindWhseEntry(var WhseEntry: Record "Warehouse Entry"; var ItemJournalLine: Record "Item Journal Line")
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
Why do you need event after Init? 
Second event is fine and can be added after getting clarification for first one.

**Comment by MattiLE** [comment]
Hi Alexander, 
I would like to set global variables, which will be required in the further process. The publisher before init is also ok.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
