### ISSUE TITLE
Update extension

### ISSUE THREAD

**Issue by developmentleasba** [microsoft/ALAppExtensions#5290]
Good morning from Spain.
We are Leasba Consulting S.L., Microsoft partner. We want to update an extensión to a higher version but the following error appears: "The application object of type 'Table' with the ID '50102' is defined in multiple apps. The apps are: ExtensionName by Leasba Consulting, SL 1.0.4.4; ExtensionName by Leasba Consulting, SL 1.0.4.5."
How could we fix it? We can't unistall the extension because it has a Table with data.
Best, Alejandro

**Comment by TrippyZ** [comment]
Cloud or onprem?

**Comment by developmentleasba** [comment]
Cloud

**Comment by AlexanderYakunin** [comment]
Please create ICM ticket for such kind of situation, this is wrong place to ask for DevOps support.
