### ISSUE TITLE
[Event Request] Codeunit 7322 "Create Inventory Pick/Movement" - OnWhseRequestCreatePickCaseElse

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5292]
Could we please have a Publisher OnWhseRequestCreatePickCaseElse in Codeunit 7322 in the Case Structure for a ELSE Statement ?
Code example:

	case WhseRequest."Source Document" of
            WhseRequest."Source Document"::"Purchase Order":
                CreatePickOrMoveFromPurchase(PurchHeader);
            WhseRequest."Source Document"::"Purchase Return Order":
                CreatePickOrMoveFromPurchase(PurchHeader);
            WhseRequest."Source Document"::"Sales Order":
                CreatePickOrMoveFromSales(SalesHeader);
            WhseRequest."Source Document"::"Sales Return Order":
                CreatePickOrMoveFromSales(SalesHeader);
            WhseRequest."Source Document"::"Outbound Transfer":
                CreatePickOrMoveFromTransfer(TransferHeader);
            WhseRequest."Source Document"::"Prod. Consumption":
                CreatePickOrMoveFromProduction(ProdHeader);
            WhseRequest."Source Document"::"Assembly Consumption":
                CreatePickOrMoveFromAssembly(AssemblyHeader);
            **// start kvspsa - Event Raiser
            else
                OnWhseRequestCreatePickCaseElse(WhseRequest, WhseActivHeader, Location, HideDialog, CompleteShipment, CheckLineExist);
        // stop kvspsa**
        end;

**Comment by AlexanderYakunin** [comment]
Please define which parameters need VAR.

**Comment by MiRo65** [comment]
local procedure OnWhseRequestCreatePickCaseElse(WarehouseRequest: Record "Warehouse Request"; WarehouseActivityHeader: Record "Warehouse Activity Header"; Location: Record Location; HideDialog: Boolean; var CompleteShipment: Boolean; CheckLineExist: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
