### ISSUE TITLE
AddAttachment - Method is obsoleted and can not be used for extension development

### ISSUE THREAD

**Issue by RaviThakkarNAV** [microsoft/ALAppExtensions#5295]
I have one scenario where I want to Export to Excel on Report using Excel Buffer and send that Excel file as an attachment via Email from SMTP Email configuration. 

I tried to utilize the old methods of Send Email with AddAttachment method but it is no longer possible.

Can you please, suggest if any other possible way to  it ?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by TrippyZ** [comment]
Provide your existing code sample

**Comment by JuricaB** [comment]
@RaviThakkarNAV you need to use AddAtachmentStream function (from SMTP Mail codeunit) instead of AddAttachment:
![image](https://user-images.githubusercontent.com/24306390/71382214-ca77db80-263b-11ea-8b69-e06bb8a9ab33.png)

**Comment by JesperSchulz** [comment]
Exactly @JuricaB. Files are not to be used in the cloud. Please use the stream equivalents instead.
