### ISSUE TITLE
[Event Request] Codeunit 6620 

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#5296]
Hi,
can you please add the following 2 Publishers 

    local procedure CopyFromPurchLineItemChargeAssign
    ........................
        if ValueEntry.FindSet then begin
            repeat
                if ItemLedgerEntry.Get(ValueEntry."Item Ledger Entry No.") then
                    if ItemLedgerEntry."Document Type" = ItemLedgerEntry."Document Type"::"Purchase Receipt" then begin
                        Item.Get(ItemLedgerEntry."Item No.");
                        CurrencyFactor := FromPurchHeader."Currency Factor";

                        if not Currency.Get(FromPurchHeader."Currency Code") then begin
                            CurrencyFactor := 1;
                            Currency.InitRoundingPrecision;
                        end;

                        if ToPurchLine."Unit Cost" = 0 then
                            QtyToAssign := 0
                        else
                            QtyToAssign := ValueEntry."Cost Amount (Actual)" * CurrencyFactor / ToPurchLine."Unit Cost";
                        SumQtyToAssign += QtyToAssign;

                        ItemChargeAssgntPurch.InsertItemChargeAssgntWithAssignValuesTo(
                          ToItemChargeAssignmentPurch, ToItemChargeAssignmentPurch."Applies-to Doc. Type"::Receipt,
                          ItemLedgerEntry."Document No.", ItemLedgerEntry."Document Line No.", ItemLedgerEntry."Item No.", Item.Description,
                          QtyToAssign, 0, ItemChargeAssgntNextLineNo, TempToItemChargeAssignmentPurch);
                    end;
                    // new
                    OnAfterInsertValueEntryItemChargeAssgntPurch(FromPurchHeader,ToPurchLine,ValueEntry,TempToItemChargeAssignmentPurch,ToItemChargeAssignmentPurch,ItemChargeAssgntNextLineNo);
            until ValueEntry.Next = 0;

.............................................

    local procedure CopyFromSalesLineItemChargeAssign
    ........................
        if ValueEntry.FindSet then begin
            repeat
                if ItemLedgerEntry.Get(ValueEntry."Item Ledger Entry No.") then
                    if ItemLedgerEntry."Document Type" = ItemLedgerEntry."Document Type"::"Sales Shipment" then begin
                        Item.Get(ItemLedgerEntry."Item No.");
                        CurrencyFactor := FromSalesHeader."Currency Factor";

                        if not Currency.Get(FromSalesHeader."Currency Code") then begin
                            CurrencyFactor := 1;
                            Currency.InitRoundingPrecision;
                        end;

                        QtyToAssign := ValueEntry."Cost Amount (Actual)" * CurrencyFactor / ToSalesLine."Unit Price";
                        SumQtyToAssign += QtyToAssign;

                        ItemChargeAssgntSales.InsertItemChargeAssgntWithAssignValuesTo(
                          ToItemChargeAssignmentSales, ToItemChargeAssignmentSales."Applies-to Doc. Type"::Shipment,
                          ItemLedgerEntry."Document No.", ItemLedgerEntry."Document Line No.", ItemLedgerEntry."Item No.", Item.Description,
                          QtyToAssign, 0, ItemChargeAssgntNextLineNo, TempToItemChargeAssignmentSales);
                    end;
                    //new 
                    OnAfterInsertValueEntryItemChargeAssgntSales(FromSalesHeader,ToSalesLine,ValueEntry,TempToItemChargeAssignmentSales,ToItemChargeAssignmentSales,ItemChargeAssgntNextLineNo);
            until ValueEntry.Next = 0;

---------------------

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertValueEntryItemChargeAssgntSales(FromSalesHeader : Record "Sales Header";ToSalesLine : Record "Sales Line";ValueEntry : Record "Value Entry";VAR TempToItemChargeAssignmentSales : TEMPORARY Record "Item Charge Assignment (Sales)";VAR ToItemChargeAssignmentSales : Record "Item Charge Assignment (Sales)";VAR ItemChargeAssgntNextLineNo : Integer)
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertValueEntryItemChargeAssgntPurch(FromPurchHeader : Record "Purchase Header";ToPurchLine : Record "Purchase Line";ValueEntry : Record "Value Entry";VAR TempToItemChargeAssignmentPurch : TEMPORARY Record "Item Charge Assignment (Purch)";VAR ToItemChargeAssignmentPurch : Record "Item Charge Assignment (Purch)";VAR ItemChargeAssgntNextLineNo : Integer)

**Comment by AlexanderYakunin** [comment]
Please clarify how new events should be placed. You added them under if ItemLedgerEntry."Document Type" = ItemLedgerEntry."Document Type"::"Sales Shipment" then begin .. end, but evenbts should be aligned to the left and be under statement  if ItemLedgerEntry.Get(ValueEntry."Item Ledger Entry No.") then. Please add begin..end where necessary and provide correct alignment, or event can be implemented in wrong place. Put on hold until getting clarification.

**Comment by Halilovast** [comment]
Yes, my mistake. I need event for each Value Entries, and please check my edited request bellow.
Thank you.

    local procedure CopyFromPurchLineItemChargeAssign
    ........................
        if ValueEntry.FindSet then begin
            repeat
                if ItemLedgerEntry.Get(ValueEntry."Item Ledger Entry No.") then
                    if ItemLedgerEntry."Document Type" = ItemLedgerEntry."Document Type"::"Purchase Receipt" then begin
                        Item.Get(ItemLedgerEntry."Item No.");
                        CurrencyFactor := FromPurchHeader."Currency Factor";

                        if not Currency.Get(FromPurchHeader."Currency Code") then begin
                            CurrencyFactor := 1;
                            Currency.InitRoundingPrecision;
                        end;

                        if ToPurchLine."Unit Cost" = 0 then
                            QtyToAssign := 0
                        else
                            QtyToAssign := ValueEntry."Cost Amount (Actual)" * CurrencyFactor / ToPurchLine."Unit Cost";
                        SumQtyToAssign += QtyToAssign;

                        ItemChargeAssgntPurch.InsertItemChargeAssgntWithAssignValuesTo(
                          ToItemChargeAssignmentPurch, ToItemChargeAssignmentPurch."Applies-to Doc. Type"::Receipt,
                          ItemLedgerEntry."Document No.", ItemLedgerEntry."Document Line No.", ItemLedgerEntry."Item No.", Item.Description,
                          QtyToAssign, 0, ItemChargeAssgntNextLineNo, TempToItemChargeAssignmentPurch);
                    end;
                // begin
                OnAfterInsertValueEntryItemChargeAssgntPurch(FromPurchHeader,ToPurchLine,ValueEntry,TempToItemChargeAssignmentPurch,ToItemChargeAssignmentPurch,ItemChargeAssgntNextLineNo);
                // end
            until ValueEntry.Next = 0;

.............................................

    local procedure CopyFromSalesLineItemChargeAssign
    ........................
        if ValueEntry.FindSet then begin
            repeat
                if ItemLedgerEntry.Get(ValueEntry."Item Ledger Entry No.") then
                    if ItemLedgerEntry."Document Type" = ItemLedgerEntry."Document Type"::"Sales Shipment" then begin
                        Item.Get(ItemLedgerEntry."Item No.");
                        CurrencyFactor := FromSalesHeader."Currency Factor";

                        if not Currency.Get(FromSalesHeader."Currency Code") then begin
                            CurrencyFactor := 1;
                            Currency.InitRoundingPrecision;
                        end;

                        QtyToAssign := ValueEntry."Cost Amount (Actual)" * CurrencyFactor / ToSalesLine."Unit Price";
                        SumQtyToAssign += QtyToAssign;

                        ItemChargeAssgntSales.InsertItemChargeAssgntWithAssignValuesTo(
                          ToItemChargeAssignmentSales, ToItemChargeAssignmentSales."Applies-to Doc. Type"::Shipment,
                          ItemLedgerEntry."Document No.", ItemLedgerEntry."Document Line No.", ItemLedgerEntry."Item No.", Item.Description,
                          QtyToAssign, 0, ItemChargeAssgntNextLineNo, TempToItemChargeAssignmentSales);
                    end;
                // begin
                OnAfterInsertValueEntryItemChargeAssgntSales(FromSalesHeader,ToSalesLine,ValueEntry,TempToItemChargeAssignmentSales,ToItemChargeAssignmentSales,ItemChargeAssgntNextLineNo);
                // end  
            until ValueEntry.Next = 0;


---------------------

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertValueEntryItemChargeAssgntSales(FromSalesHeader : Record "Sales Header";ToSalesLine : Record "Sales Line";ValueEntry : Record "Value Entry";VAR TempToItemChargeAssignmentSales : TEMPORARY Record "Item Charge Assignment (Sales)";VAR ToItemChargeAssignmentSales : Record "Item Charge Assignment (Sales)";VAR ItemChargeAssgntNextLineNo : Integer)
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertValueEntryItemChargeAssgntPurch(FromPurchHeader : Record "Purchase Header";ToPurchLine : Record "Purchase Line";ValueEntry : Record "Value Entry";VAR TempToItemChargeAssignmentPurch : TEMPORARY Record "Item Charge Assignment (Purch)";VAR ToItemChargeAssignmentPurch : Record "Item Charge Assignment (Purch)";VAR ItemChargeAssgntNextLineNo : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
