### ISSUE TITLE
[Event Request] Codeunit 84 - Blnkt Sales Ord. to Ord. (Y/N) - OnAfterCreateSalesOrder

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#5297]
Dear ALAppExtensions team,

Through this issue we would like to request to have an event `OnAfterCreateSalesOrder`, the same way as we have a `OnAfterCreatePurchOrder` event for codeunit 94 Blnkt Purch Ord. to Ord. (Y/N).

This event publisher would have the following signature:
```pascal
LOCAL [IntegrationEvent] OnAfterCreateSalesOrder(VAR SalesHeader : Record "Sales Header";VAR SkipMessage : Boolean)
```
so with two **VAR** parameters.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
