### ISSUE TITLE
REP11005 VAT Statement Germany - OnBeforeCalcAmountVATEntryTotaling - Add IncludeSender

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5300]
Hello,

could you please activate the IncludeSender-Property in the existing Event "OnBeforeCalcAmountVATEntryTotaling" in Report 11005 "VAT Statement Germany"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
