### ISSUE TITLE
PAG 475 - OnBeforeOpenPageVATEntryTotaling - Add IncludeSender 

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5301]
Hello,
could you please activate the IncludeSender-Property in the existing Event "OnBeforeOpenPageVATEntryTotaling" in Report 475 "OnBeforeOpenPageVATEntryTotaling"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
