### ISSUE TITLE
PAG475 - OnBPSBeforeCurrPageUpdateInUpdateForm

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5302]
Hello,

could you please add the following Event:
![image](https://user-images.githubusercontent.com/45033081/70911439-35a92880-2012-11ea-8f40-b7d66a1f9e5a.png)

![image](https://user-images.githubusercontent.com/45033081/70911466-4194ea80-2012-11ea-8ff4-73f30cc60fa6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
