### ISSUE TITLE
[Event Request] Codeunit 7322 OnWhseRequestCheckSourceDocCaseElse

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5303]
Could we please have an Event in Codeunit 7322 in function CheckSourceDoc to create an Case-ELSE in this Case-Structure:

        case WhseRequest."Source Document" of
            WhseRequest."Source Document"::"Purchase Order":
                exit(SetFilterPurchLine(PurchLine, PurchHeader));
            WhseRequest."Source Document"::"Purchase Return Order":
                exit(SetFilterPurchLine(PurchLine, PurchHeader));
            WhseRequest."Source Document"::"Sales Order":
                exit(SetFilterSalesLine(SalesLine, SalesHeader));
            WhseRequest."Source Document"::"Sales Return Order":
                exit(SetFilterSalesLine(SalesLine, SalesHeader));
            WhseRequest."Source Document"::"Outbound Transfer":
                exit(SetFilterTransferLine(TransferLine, TransferHeader));
            WhseRequest."Source Document"::"Prod. Consumption":
                exit(SetFilterProductionLine(ProdOrderComp, ProdHeader));
            WhseRequest."Source Document"::"Assembly Consumption":
                exit(SetFilterAssemblyLine(AssemblyLine, AssemblyHeader));
            // start kvspsa - Event Raiser
            else begin
                    IsHandled := false;
                    **OnWhseRequestCheckSourceDocCaseElse**(WhseRequest, WhseActivHeader, CheckLineExist, Result, IsHandled);
                    if IsHandled then
                        exit(Result);
                end;
        // stop kvspsa

------------
Event including EventHandler:
local procedure **OnWhseRequestCheckSourceDocCaseElse**(WarehouseRequest: Record "Warehouse Request"; WhseActivHeader: Record "Warehouse Activity Header"; CheckLineExist: Boolean; var ReturnValue: Boolean; var IsHandled: Boolean);
    begin
    end;

Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
