### ISSUE TITLE
[Event Request] Codeunit 7322 - OnWhseRequestAutoCreatePickOrMoveCaseElse

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5304]
Could we please have en Event in Codeunit 7322 in function AutoCreatePickOrMove in the Case-Structure:

        case WhseRequest."Source Document" of
            WhseRequest."Source Document"::"Purchase Order":
                CreatePickOrMoveFromPurchase(PurchHeader);
            WhseRequest."Source Document"::"Purchase Return Order":
                CreatePickOrMoveFromPurchase(PurchHeader);
            WhseRequest."Source Document"::"Sales Order":
                CreatePickOrMoveFromSales(SalesHeader);
            WhseRequest."Source Document"::"Sales Return Order":
                CreatePickOrMoveFromSales(SalesHeader);
            WhseRequest."Source Document"::"Outbound Transfer":
                CreatePickOrMoveFromTransfer(TransferHeader);
            WhseRequest."Source Document"::"Prod. Consumption":
                CreatePickOrMoveFromProduction(ProdHeader);
            WhseRequest."Source Document"::"Assembly Consumption":
                CreatePickOrMoveFromAssembly(AssemblyHeader);
            // start kvspsa - Event Raiser
            else
                **OnWhseRequestAutoCreatePickOrMoveCaseElse**(WhseRequest, WhseActivHeader, Location, HideDialog, CompleteShipment, CheckLineExist);
        // stop kvspsa
        end;
-----
Event:
    local procedure **OnWhseRequestAutoCreatePickOrMoveCaseElse**(WarehouseRequest: Record "Warehouse Request"; WarehouseActivityHeader: Record "Warehouse Activity Header"; Location: Record Location; HideDialog: Boolean; var CompleteShipment: Boolean; CheckLineExist: Boolean);
    begin
    end;
------
Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
