### ISSUE TITLE
Scope of OnAfterPostPurchaseDoc event in PurchPost.Codeunit.al

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/ALAppExtensions#5305]
Hello

The OnAfterPostPurchaseDoc event in the purchase posting codeunit is set to OnPrem. Makes no sense to me, could this be changed to also allow it to be used for the cloud?

Thanks,
Daniel

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
