### ISSUE TITLE
[Event Modification] Codeunit 427 - f(x) OutboxPurchHdrToInbox (relates to #4733)

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#5306]
Hi
We need the ICPartner to be a var parameter of the OnBeforeOutboxPurchHdrToInbox event, as there is a check on ICPartner."Customer No." which will be executed after the event is triggered, and it isn't bypassed when the IsHandled flag is set. (Incidentally, the error that's raised here needs an additional parameter.)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
