### ISSUE TITLE
[Event Request] Codeunit 21 RunCheck

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#5311]
Hello Team,

we need a new publisher:

old code : 

WITH ItemJnlLine DO BEGIN
  IF EmptyLine THEN BEGIN
    IF NOT IsValueEntryForDeletedItem THEN
      EXIT;
  END ELSE
    IF NOT OnlyStopTime THEN
      TESTFIELD("Item No.");

  IF Item.GET("Item No.") THEN
    Item.TESTFIELD("Base Unit of Measure");

  TESTFIELD("Posting Date");

new code:

WITH ItemJnlLine DO BEGIN
  IF EmptyLine THEN BEGIN
    IF NOT IsValueEntryForDeletedItem THEN
      EXIT;
  END ELSE
    IF NOT OnlyStopTime THEN
      TESTFIELD("Item No.");

  IF Item.GET("Item No.") THEN
    Item.TESTFIELD("Base Unit of Measure");

 handled := false;
 OnAfterGetItem(Item, ItemJnlLine, handled);
  IF handled THEN
    EXIT;

  TESTFIELD("Posting Date");

Thanks

**Comment by AlexanderYakunin** [comment]
Please provide event definition for OnAfterGetItem(Item, ItemJnlLine, handled);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
