### ISSUE TITLE
[Event Request] Codeunit 57 Function SalesDeltaUpdateTotals

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#5317]
Hello Team,

we need a new handled publisher to activate code or not, because we have Sales Positions that are not created for being totalled.

HandledL := FALSE;
OnBeforeCalculateDelta(SalesLine, HandledL);
IF NOT HandledL THEN BEGIN
    TotalSalesLine."Line Amount" += SalesLine."Line Amount" - xSalesLine."Line Amount";
    TotalSalesLine."Amount Including VAT" += SalesLine."Amount Including VAT" - xSalesLine."Amount Including VAT";
    TotalSalesLine.Amount += SalesLine.Amount - xSalesLine.Amount;
    VATAmount := TotalSalesLine."Amount Including VAT" - TotalSalesLine.Amount;
    IF SalesLine."Inv. Discount Amount" <> xSalesLine."Inv. Discount Amount" THEN BEGIN
      IF (InvoiceDiscountPct > -0.01) AND (InvoiceDiscountPct < 0.01) THEN // To avoid decimal overflow later
        InvDiscountBaseAmount := 0
      ELSE
        InvDiscountBaseAmount := InvoiceDiscountAmount / InvoiceDiscountPct * 100;
      InvoiceDiscountAmount += SalesLine."Inv. Discount Amount" - xSalesLine."Inv. Discount 
  Amount";
      IF (InvoiceDiscountAmount = 0) OR (InvDiscountBaseAmount = 0) THEN
        InvoiceDiscountPct := 0
      ELSE
        InvoiceDiscountPct := ROUND(100 * InvoiceDiscountAmount / InvDiscountBaseAmount,0.00001);
    END;

END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
