### ISSUE TITLE
[Event Request] Codeunit 5760 - Function CreatePutAwayDoc

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5318]
Publisher is needed in function CreatePutAwayDoc C5760, for modifying WhseActivHeader:

![image](https://user-images.githubusercontent.com/48024891/71079982-8fcdf900-218c-11ea-9a34-ff0644c7e2e2.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterLoopThroughtPutAwayDoc(var WarehouseActivityHeader: Record "Warehouse Activity Header")
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
We already have this event
