### ISSUE TITLE
[Event Request] Codeunit 1102 - CA Jnl.-Post Line - Code

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5320]
Could you please create an Integration event in Codeunit 1102 CA Jnl.-Post Line, in function Code?
(Similar to Codeunit 12 Gen. Jnl.-Post Line, OnBeforeCode event.)

```
LOCAL Code()
// >>>>
IsPosted := FALSE;
OnBeforeCode(CostJnlLine,IsPosted,CostRegister);
IF IsPosted THEN
  EXIT;
// <<<<

WITH CostJnlLine DO BEGIN
  IF EmptyLine THEN
    EXIT;
...
```

Event signature:
```
LOCAL [IntegrationEvent] OnBeforeCode(VAR CostJnlLine : Record "Cost Journal Line";VAR IsPosted : Boolean;VAR CostRegister : Record "Cost Register")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
