### ISSUE TITLE
[Event Request] Codeunit 1104 - Cost Account Allocation - CalcLineShare

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5321]
Could you please create an Integration event in Codeunit 1104 Cost Account Allocation, in function CalcLineShare?

```
[External] CalcLineShare(VAR CostAllocationTarget : Record "Cost Allocation Target")
// >>>>>
IsHandled := FALSE;
OnBeforeCalcLineShare(CostAllocationTarget,IsHandled);
IF IsHandled THEN
  EXIT;
// <<<<<
WITH CostAllocationTarget DO BEGIN
  ....
END;
```

Event signature:
```
LOCAL [IntegrationEvent] OnBeforeCalcLineShare(VAR CostAllocationTarget : Record "Cost Allocation Target";VAR IsHandled : Boolean)
```
Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
