### ISSUE TITLE
[Event Request] Codeunit 1104 - Cost Account Allocation - CalcDateFilter

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5322]
Could you please create an Integration event in Codeunit 1104 Cost Account Allocation, in function CalcDateFilter?

```
LOCAL CalcDateFilter(CostAllocationTarget : Record "Cost Allocation Target")
// >>>>>
IsHandled := FALSE;
OnBeforeCalcDateFilter(CostAllocationTarget,StartDate,EndDate,IsHandled);
IF IsHandled THEN
  EXIT;
// <<<<<
AccPeriod.RESET;
StartDate := 0D;
EndDate := DMY2DATE(31,12,9999);
....
```

Event signature:
```
LOCAL [IntegrationEvent] OnBeforeCalcDateFilter(VAR CostAllocationTarget : Record "Cost Allocation Target";VAR StartDate : Date;VAR EndDate : Date;VAR IsHandled : Boolean)
```
Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
