### ISSUE TITLE
[Event Request] Report 87 - Change Publisher OnAfterCopyGenPostingSetup

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5323]
In this request
#311 (comment)
it was asked for a Publisher containing the flags to trigger which area (Sales / purchase / inventory / manufacturing) should be copied
![image](https://user-images.githubusercontent.com/48024891/71082086-c9a0fe80-2190-11ea-8fa5-196910dd2b3f.png)

The Publisher was added in the meantime, but the flags are missing.
==> Please add them - otherwise the Publisher doesn't make sense.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
