### ISSUE TITLE
[External] COD 9561 ConvertToPdf

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5324]
In codeunit 9651 "Document Report Mgt." - ConvertToPdf / TryConvertWordBlobToPdf uses the WordToPdf dotnet ("Microsoft.Dynamics.Nav.PdfWriter.WordToPdf").

We've created our own Word document frame with variable datasets, avoiding to use coded report datasets. The result is a WordBlob that however needs to be converted to PDF. Currently, we've duplicated the ConvertToPdf  code, using the WordToPdf  dotnet. However, this is not cloud proof.

Could you please expose ConvertToPdf ?

**Comment by miljance** [comment]
We also need this function exposure.

**Comment by hougaard** [comment]
I need this too for the Sharepoint Connector (AppSource app)

**Comment by fvet** [comment]
@AlexanderYakunin Any short term plans to have this fixed in an upcoming CU? (Saas proof)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
