### ISSUE TITLE
Report 6653 - Combine Return Receipts add OnFinalizeSalesInvHeader event

### ISSUE THREAD

**Issue by JJODonovan** [microsoft/ALAppExtensions#5325]
Can you please add an OnFinalizeSalesInvHeader Event publisher to Report 6653 (Combine Return Receipts) to match the event published in Report 295 (Combine Shipments)?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
