### ISSUE TITLE
Codeunit 1305 "Sales-Quote to Invoice" OnAfterInsertAllSalesInvLines

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#5326]
Hi,
we want to subscribe the publisher OnAfterInsertAllSalesInvLines and work with the new Inserted "Sales Invoice Lines". Unfortunately the referenced SalesInvoiceLine is not the same variable as the one that is used for insert. It would be helpful to place the publisher at the end of the function with the right variable:
![image](https://user-images.githubusercontent.com/34675109/71086454-4684a600-219a-11ea-8822-747d69e3f8ff.png)
thanks

**Comment by AlexanderYakunin** [comment]
We cannot make this kind of changes. And you have Onbefore/OnAfter events in the loop to work with SalesInvoiceLine record. What else do you need, please explain.

**Comment by pschwambornMC** [comment]
maybe the OnAfterInsertSalesInvoiceLine Publisher works for our purposes. Nevertheless I think the SalesInvoiceLine Variable in the OnAfterInsertAllSalesInvLines Publisher isn't useful because you can't  retrieve the new created Records in this Variable.

**Comment by AlexanderYakunin** [comment]
You have access to SalesInvoiceLine  in event OnAfterInsertSalesInvoiceLine, as SalesInvoiceLinedefined as VAR. I'm closing this request, please create new if you need something else.
