### ISSUE TITLE
Customer Contact Synchronization runs Code twice

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#5328]
As seen in Business Central docker image onprem:14.6.36463.0-de

the customer to contact synchronization runs the same code twice 

In Codeunit 5056 "CustCont-Update" OnModify() there are those two lines 
> Cont.OnModify(OldCont); 
>Cont.MODIFY(TRUE);

But in Table 5050 Contact the OnModify()-Trigger runs the OnModify-Method. Which is called right before the MODIFY(TRUE). 

![image](https://user-images.githubusercontent.com/35929603/71093083-c74a9e80-21a8-11ea-86cf-61b8483de299.png)
![image](https://user-images.githubusercontent.com/35929603/71093235-1b558300-21a9-11ea-98cd-c40f6632c376.png)
![image](https://user-images.githubusercontent.com/35929603/71093314-3e803280-21a9-11ea-8cff-6c19c96a4b5f.png)

So the Code in the OnModify-Function is called twice. Please change this behaviour.

**Comment by AlexanderYakunin** [comment]
This design have been significantly changed since creation of this request and we cannot make this change without clear reason why we should do it? If there are any issues related with current resign, please report normal hotfix using Support channels, as we cannot make such changes without good repro steps and understanding which issue should be fixed.

**Comment by JulianTillmann** [comment]
If you've changed the design, does it still run the same code twice? 

That would be bad because: it's redundant! It hinders performance by doing the same thing again and any subscription to that code would have to check if they've already run before.

**Comment by AlexanderYakunin** [comment]
If that's is the case, you must create bug via Support. This forum is for extensibility related requests, you ask have no relation to extensibility and will never reach right team to fix it from here. If you see real performance issues for your online customer, you can also raise ICM ticket.

**Comment by JulianTillmann** [comment]
I've done that and they sent me here, see case REG:119120325000229

**Comment by JulianTillmann** [comment]
@AlexanderYakunin 
So what's next here?

**Comment by JulianTillmann** [comment]
That's a huge disappointment! 

Communication wise this has been a very, very bad experience :-(
