### ISSUE TITLE
[Event Change] Report 699 - Calculate Plan - Req. Wksh. - OnAfterOnOpenPage

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5329]
Hi al-team, 

can you please add the following parameters to the Publisher OnAfterOnOpenPage?

```
        trigger OnOpenPage()
        begin
            MfgSetup.Get;
            UseForecast := MfgSetup."Current Production Forecast";
            // NEW FromDate, ToDate
            OnAfterOnOpenPage(FromDate,ToDate);
        end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterOnOpenPage(var FromDate: Date; var ToDate: Date)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
