### ISSUE TITLE
[Event Request] Codeunit 8 Function InsertGLAccounts

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#5331]
Some of our customer will follow to insert multi language field data from masters, while inserting GL Accounts data to Accounts Schedules. At this stage user can have choose required language selection. to overcome this problem, can you please add below event handler in Codeunit 8 Function InsertGLAccounts.
------------------------------------------------------------------------------------
[External] InsertGLAccounts(VAR AccSchedLine : Record "Acc. Schedule Line")
//NEW CODE
OnBeforeInsertGLAccounts(LanguageID);
//NEW CODE

GLAccList.LOOKUPMODE(TRUE);
IF GLAccList.RUNMODAL = ACTION::LookupOK THEN BEGIN
  GLAccList.SetSelection(GLAcc);
  AccCounter := GLAcc.COUNT;
  IF AccCounter > 0 THEN BEGIN
    AccSchedLineNo := AccSchedLine."Line No.";
    MoveAccSchedLines(AccSchedLine,AccCounter); 
-------------------------------------------------------------------------------------
Event Function:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertGLAccounts(VAR LanguageID : Integer)
begin
end

**Comment by AlexanderYakunin** [comment]
What is LanguageID? We don;t have such statement, we have GlobalLanguageID or WindowslanguageID. And why do you need this parameter? 

Please correct your request.

**Comment by dharma534** [comment]
Please add GlobalLanguageID. before initiating InsertGLAccounts function user can choose language option using STRMENU function. Example: In GLAccount master we have custom Text field for Japanese text. At the time of Inserting GL Accounts to Account schedule page, user can choose either current global language english (ENU) or Japanese (JPN) if they choose global language then description (ENU) text insert else Japanese field text insert. Reason I am passing parameter i have one more function in same InsertGLAccounts function after **AccSchedLine.Description := GLAcc.Name;**
--InitLanguage Function--
SelectLangID := GLOBALLANGUAGE;
IF STRMENU(LTextENUorJPN) = 1 THEN
  SelectLangID := 1041;
--------------

**Comment by AlexanderYakunin** [comment]
I can only add OnBeforeInsertGLAccounts(AccSchedLine). GlobalLanguageID is function and it shouldn't be a parameter. In general I'd recommend another solution for you, simply add field Language ID to account schedule table, I assume same language should be used in one account schedule. Asking user select it each time is not a good idea.

**Comment by dharma534** [comment]
thanks for your recommend. please add event as you suggested OnBeforeInsertGLAccounts(AccSchedLine). i can manage it for my requirement.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
