### ISSUE TITLE
[Event Request] Codeunit 8 Function InsertGLAccounts

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#5332]
### Some of our customer will follow to insert multi language field data from masters, while inserting GL Accounts data to Accounts Schedules. Can you please add below event handler in Codeunit 8 Function InsertGLAccounts.######

[External] InsertGLAccounts(VAR AccSchedLine : Record "Acc. Schedule Line")
GLAccList.LOOKUPMODE(TRUE);
IF GLAccList.RUNMODAL = ACTION::LookupOK THEN BEGIN
  GLAccList.SetSelection(GLAcc);
  AccCounter := GLAcc.COUNT;
  IF AccCounter > 0 THEN BEGIN
    AccSchedLineNo := AccSchedLine."Line No.";
    MoveAccSchedLines(AccSchedLine,AccCounter);
    IF GLAcc.FINDSET THEN
      REPEAT
        AccSchedLine.INIT;
        AccSchedLineNo := AccSchedLineNo + 10000;
        AccSchedLine."Line No." := AccSchedLineNo;
        AccSchedLine.Description := GLAcc.Name;
       
       //NEW CODE >>>>
        OnAfterAccScheduleLineDescUpdate(GLAcc."No.",AccSchedLine.Description,LanguageID);
        //NEW CODE <<<<

        AccSchedLine.VALIDATE(Indentation,GLAcc.Indentation);
        AccSchedLine.Bold := GLAcc."Account Type" <> GLAcc."Account Type"::Posting;
        IF GLAcc."Account Type" IN
           [GLAcc."Account Type"::Posting,GLAcc."Account Type"::Total,GLAcc."Account Type"::"End-Total"]
        THEN BEGIN
          AccSchedLine.Totaling := GLAcc."No.";
          AccSchedLine."Row No." := COPYSTR(GLAcc."No.",1,MAXSTRLEN(AccSchedLine."Row No."));
        END;
        IF GLAcc."Account Type" IN
           [GLAcc."Account Type"::Total,GLAcc."Account Type"::"End-Total"]
        THEN
          AccSchedLine."Totaling Type" := AccSchedLine."Totaling Type"::"Total Accounts"
        ELSE
          AccSchedLine."Totaling Type" := AccSchedLine."Totaling Type"::"Posting Accounts";
        AccSchedLine.INSERT;
      UNTIL GLAcc.NEXT = 0;
  END;
END;

-------------------
Event Function:
[IntegrationEvent(false, false)]
local procedure OnAfterAccScheduleLineDescUpdate(GLAccNo : Code[20];VAR TargetAccDescText : Text[100];LanguageID : Integer)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
