### ISSUE TITLE
External deployment is not enabled. (Modules\System\Extension Management\src\ExtensionManagement.Codeunit.al)

### ISSUE THREAD

**Issue by louagej** [microsoft/ALAppExtensions#5333]
Dear,

In the codeunit `Extension Management` (a public codeunit), the function `UploadExtension` (*Uploads an extension, using a File Stream and based on the Locale Identifier*) is available.

I can call the function without any warning but I'll receive an run-time error , saying:

 > External deployment is not enabled. Please contact your system administrator.

![2019_12_19_000](https://user-images.githubusercontent.com/7229592/71153587-c4e45500-2239-11ea-94b3-5ff76beca23f.png)

The problem is that I can't change the `ExtensionAllowedTargetLevel` from `Internal` to `External` since we're having an On Premise environment.

This is how I call the function
```al
    procedure PublishAndInstallExtension(PackageID: Guid; WindowsLanguageID: Integer): Boolean
    var
        ExtensionManagement: Codeunit "Extension Management";
        Instr2: InStream;
    begin
        DownloadSourceCode(PackageID, Instr2); //Own Local function to get my app in a Instream object
        ExtensionManagement.UploadExtension(Instr2, 1033);
        ExtensionManagement.InstallExtension(PackageID, 1033, true);
    end;
```

I think (hope) that the validation of ExtensionAllowedTargetLevel is not necessary here and you'll be able to make this function run without error in a  On Premise environment.

![2019_12_19_001](https://user-images.githubusercontent.com/7229592/71154012-de39d100-223a-11ea-9fcf-3ade35af14fe.png)

**Comment by atoader** [comment]
Hi! We have discussed this issue internally and it is by design. The extension management page was never meant to work for on-prem installations. 
We will improve the error message, but I recommend that you open an idea on BCIdeas or upvote an existing one.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by louagej** [comment]
@bc-ghost ,
 :smiley:  :rocket:

**Comment by atoader** [comment]
My bad, I should have closed the internal tracking item with a different substate. Please ignore bc-ghost.
