### ISSUE TITLE
OnAfterCreateFieldRefArray Event Table 1301 not usable

### ISSUE THREAD

**Issue by Stef1974** [microsoft/ALAppExtensions#5334]
This event accepts an Array[30] as a parameter but this array has been declared on the OnInsert/OnModify triggers of the table as Array[17] so it's not possible to add any elements to it by using this event.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
