### ISSUE TITLE
Assembly Line - AutoReserve Function

### ISSUE THREAD

**Issue by YannRobertCargo** [microsoft/ALAppExtensions#5337]
Hello,
We are working on an extension around reservations. We don’t want to automatically reserve when the user inputs a quantity so we set « Reserve »  to « Manual » on our items. However, we offer our users an action that reserves all the lines on a sales order or an assembly order. 

To do so, we wanted to use the function « AutoReserve » of tables « Sales Line » and « Assembly Line ». It works for the sales lines but not for the assembly lines because the function « AutoReserve » of « Assembly Line » excludes the lines when « Reserve » is not equal to « Always ». 
![image](https://user-images.githubusercontent.com/47186314/71245469-0bf34880-2315-11ea-9374-f2d86fa16f27.png)

We don’t understand this behaviour, all the more when we request the process « Automatic Reservation » on the page « Reservation workskeet », Business Central reserves the line even if the « Reserve » field is assigned to Manual 
![image](https://user-images.githubusercontent.com/47186314/71245118-558f6380-2314-11ea-996a-06260e617cc6.png)

Is that an expected behaviour, if so, what is the reason ? 
We are not blocked by the issue. For the time being, we have simply duplicated the function without this excluding condition like the function « AutoReserve » for « Sales line ».

**Comment by YannRobertCargo** [comment]
@jfpanarotto

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
