### ISSUE TITLE
[Event Request] Codeunit 5611 Function CalculateDeprAmount

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#5338]
We have some country defined custom depreciation method using calculating FA depreciation Amount. (Under Last Entry Metod)

LOCAL CalculateDeprAmount() : Decimal
WITH FA DO BEGIN
  IF DateFromProjection > 0D THEN
    FirstDeprDate := DateFromProjection
  ELSE BEGIN
    FirstDeprDate := DepreciationCalc.GetFirstDeprDate("No.",DeprBookCode,Year365Days);
    IF FirstDeprDate > UntilDate THEN
      EXIT(0);
    UseDeprStartingDate := DepreciationCalc.UseDeprStartingDate("No.",DeprBookCode);
    IF UseDeprStartingDate THEN
      FirstDeprDate := DeprStartingDate;
  END;
  IF FirstDeprDate < DeprStartingDate THEN
    FirstDeprDate := DeprStartingDate;
  NumberOfDays := DepreciationCalc.DeprDays(FirstDeprDate,UntilDate,Year365Days);
  Factor := 1;
  IF NumberOfDays <= 0 THEN
    EXIT(0);
  IF DaysInPeriod > 0 THEN BEGIN
    Factor := DaysInPeriod / NumberOfDays;
    NumberOfDays := DaysInPeriod;
  END;
  UseHalfYearConvention := SetHalfYearConventionMethod;
  // Method Last Entry
  IF UseDeprStartingDate OR
     (DateFromProjection > 0D) OR
     (DeprMethod = DeprMethod::BelowZero) OR
     (DeprBook."Periodic Depr. Date Calc." = DeprBook."Periodic Depr. Date Calc."::"Last Entry")
  THEN BEGIN
    NumberOfDays2 := NumberOfDays;
    IF UseHalfYearConvention THEN
      Amount := CalcHalfYearConventionDepr
    ELSE
      CASE DeprMethod OF
        DeprMethod::StraightLine:
          Amount := CalcSLAmount;
        DeprMethod::DB1:
          Amount := CalcDB1Amount;
        DeprMethod::DB2:
          Amount := CalcDB2Amount;
        DeprMethod::DB1SL,
        DeprMethod::DB2SL:
          Amount := CalcDBSLAmount;
        DeprMethod::Manual:
          Amount := 0;
        DeprMethod::"User-Defined":
          Amount := CalcUserDefinedAmount(UntilDate);
        DeprMethod::BelowZero:
          Amount := DepreciationCalc.CalcRounding(DeprBookCode,CalcBelowZeroAmount);

//NEW CODE >>>>  
DeprMethod::JPDB:  OnAfterBelowZeroCustomDeprMethodAmountCalculate(FADeprBook,CalcDB1Amount,BookValue,DeprBasis,DaysInFiscalYear,NumberOfDays,Amount,FALSE);
//NEW CODE <<<<

END;
END
    // Method Last Depreciation Entry
  ELSE BEGIN
***

Event Signature
[IntegrationEvent(false, false)]
local procedure OnAfterBelowZeroCustomDeprMethodAmountCalculate(VAR FADeprBook : Record "FA Depreciation Book";DB1Amount : Decimal;BookValue : Decimal;DeprBasis : Decimal;DaysInFiscalYear : Integer;NumberOfDays : Integer;VAR ResultDeprAmount : Decimal;IsAddResultAmount : Boolean))
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
