### ISSUE TITLE
[Event Request] Codeunit 5611 Function CalculateDeprAmount

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#5339]
We have some country defined custom depreciation method using calculating FA depreciation Amount. (Under Last Depreciation Entry Method)

ELSE BEGIN
    ELSE BEGIN
    IF UseHalfYearConvention THEN
      DeprBook.TESTFIELD(
        "Periodic Depr. Date Calc.",DeprBook."Periodic Depr. Date Calc."::"Last Entry");
    Amount := 0;
    StartingDate := 0D;
    EndingDate := 0D;
    DepreciationCalc.GetDeprPeriod(
      "No.",DeprBookCode,UntilDate,StartingDate,EndingDate,NumberOfDays,Year365Days);
    FirstDeprDate := StartingDate;
    NumberOfDays2 := DepreciationCalc.DeprDays(FirstDeprDate,UntilDate,Year365Days);
    WHILE NumberOfDays > 0 DO BEGIN
      DepreciationCalc.CalculateDeprInPeriod(
        "No.",DeprBookCode,EndingDate,Amount,Sign,
        BookValue,DeprBasis,SalvageValue,MinusBookValue);
      IF DepreciationCalc.GetSign(
           BookValue,DeprBasis,SalvageValue,MinusBookValue) <> 1
      THEN
        EXIT(0);
      CASE DeprMethod OF
        DeprMethod::StraightLine:
          Amount := Amount + CalcSLAmount;
        DeprMethod::DB1:
          Amount := Amount + CalcDB1Amount;
        DeprMethod::DB2:
          Amount := Amount + CalcDB2Amount;
        DeprMethod::Manual:
          Amount := 0;
        DeprMethod::"User-Defined":
          Amount := Amount + CalcUserDefinedAmount(EndingDate);

//NEW CODE >>>>
DeprMethod::JPDB: OnAfterUserDefinedCustomDeprMethodAmountCalculate(FADeprBook,CalcDB1Amount,BookValue,DeprBasis,DaysInFiscalYear,NumberOfDays,Amount,TRUE);
//NEW CODE <<<<
END

Event Signature
[IntegrationEvent(false, false)]
local procedure OnAfterUserDefinedCustomDeprMethodAmountCalculate(VAR FADeprBook : Record "FA Depreciation Book";DB1Amount : Decimal;BookValue : Decimal;DeprBasis : Decimal;DaysInFiscalYear : Integer;NumberOfDays : Integer;VAR ResultDeprAmount : Decimal;IsAddResultAmount : Boolean))
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
