### ISSUE TITLE
Missing event on Codeunit 408 OnAfterCollectDefaultDimsToCheck

### ISSUE THREAD

**Issue by xgaronnat** [microsoft/ALAppExtensions#5341]
Hi,
Could you add a new event in codeunit 408 in function CheckDimValuePosting() :
```
LastErrorID := GetLastDimErrorID;
DimSetEntry.RESET;
DimSetEntry.SETRANGE("Dimension Set ID",DimSetID);
CollectDefaultDimsToCheck(TableID,No,TempDefaultDim);
OnAfterCollectDefaultDimsToCheck(TableID,No,TempDefaultDim);
WITH TempDefaultDim DO BEGIN

```

Here the desired event signature : 
`[IntegrationEvent] OnAfterCollectDefaultDimsToCheck(TableID : ARRAY [10] OF Integer;No : ARRAY [10] OF Code[20];VAR TempDefaultDim : TEMPORARY Record "Default Dimension")
`

Thanks a lot,
Xavier.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
