### ISSUE TITLE
[Event Request] Codeunit 1106 - CostJnlManagement - TemplateSelection

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5342]
Could you please create an Integration event in Codeunit 1106 CostJnlManagement, in function TemplateSelection?

```
[External] TemplateSelection(VAR CostJnlLine : Record "Cost Journal Line";VAR JnlSelected : Boolean)
// >>>>
IsHandled := FALSE;
OnBeforeTemplateSelection(CostJnlLine,JnlSelected,IsHandled);
IF IsHandled THEN
  EXIT;
// <<<<
JnlSelected := TRUE;
CostJnlTemplate.RESET;
....
```

Event signature:

```
LOCAL [IntegrationEvent] OnBeforeTemplateSelection(VAR CostJnlLine : Record "Cost Journal Line";VAR JnlSelected : Boolean;VAR IsHandled : Boolean)
```

We created Recurring Cost Journal (similar to Recurring General Journal) and we need this event to differentiate from standard cost journal.
Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
