### ISSUE TITLE
[Event Request] Codeunit 1106 - CostJnlManagement - OpenJnlBatch

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#5343]
Could you please create an Integration event in Codeunit 1106 CostJnlManagement, in function OpenJnlBatch?

```
[External] OpenJnlBatch(VAR CostJnlBatch : Record "Cost Journal Batch")
// >>>>
IsHandled := FALSE;
OnBeforeOpenJnlBatch(CostJnlBatch,IsHandled);
IF IsHandled THEN
  EXIT;
// <<<<
IF CostJnlBatch.GETFILTER("Journal Template Name") <> '' THEN
  EXIT;
....
```

Event signature:
```
LOCAL [IntegrationEvent] OnBeforeOpenJnlBatch(VAR CostJnlBatch : Record "Cost Journal Batch";VAR IsHandled : Boolean)
```
We created Recurring Cost Journal (similar to Recurring General Journal) and we need this event to differentiate from standard cost journal.
Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
