### ISSUE TITLE
New Line not working in Dialog Object in v15

### ISSUE THREAD

**Issue by benjaminknapper** [microsoft/ALAppExtensions#5345]
It seems that with v15 the ability to do a new line within a Dialog object has changed or been broken.

The following code has been written and deployed against a Production environment running v14 and a Sandbox environment running v15.1:

![image](https://user-images.githubusercontent.com/11381404/71289535-fd1b8e80-2332-11ea-8517-8cf8ba94e84c.png)

The outcomes of this code differ based on the version it is run on.

V14
![v14](https://user-images.githubusercontent.com/11381404/71289688-4835a180-2333-11ea-8db8-cdf126696f0e.png)
![v14 Message](https://user-images.githubusercontent.com/11381404/71289690-49ff6500-2333-11ea-808d-69d90dcf922d.png)

V15.1
![v15](https://user-images.githubusercontent.com/11381404/71289700-51bf0980-2333-11ea-9ce1-81dd5d882dcc.png)
![v15 Message](https://user-images.githubusercontent.com/11381404/71289701-54216380-2333-11ea-8c12-5909bc16857f.png)

**Comment by AndreiPanko** [comment]
Thank you for reporting that. We already know about that bug and working on it.
Be aware that bugs should be submitted via proper channels:
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
