### ISSUE TITLE
Page 42 Sales Order PostDocument function external access

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#5346]
In page 42 there is a function "PostDocument" which is only local.
we would like to add a button "post&print" and would therefor need acces to this function.
is it possible to make this function external?

procedure PostDocument(PostingCodeunitID: Integer; Navigate: Option)
    var
        SalesHeader: Record "Sales Header";
        LinesInstructionMgt: Codeunit "Lines Instruction Mgt.";
        InstructionMgt: Codeunit "Instruction Mgt.";
    begin
        if ApplicationAreaMgmtFacade.IsFoundationEnabled then
            LinesInstructionMgt.SalesCheckAllLinesHaveQuantityAssigned(Rec);

        SendToPosting(PostingCodeunitID);

        DocumentIsScheduledForPosting := "Job Queue Status" = "Job Queue Status"::"Scheduled for Posting";
        DocumentIsPosted := (not SalesHeader.Get("Document Type", "No.")) or DocumentIsScheduledForPosting;
        OnPostOnAfterSetDocumentIsPosted(SalesHeader, DocumentIsScheduledForPosting, DocumentIsPosted);

        CurrPage.Update(false);

        if PostingCodeunitID <> CODEUNIT::"Sales-Post (Yes/No)" then
            exit;

        case Navigate of
            NavigateAfterPost::"Posted Document":
                begin
                    if InstructionMgt.IsEnabled(InstructionMgt.ShowPostedConfirmationMessageCode) then
                        ShowPostedConfirmationMessage;

                    if DocumentIsScheduledForPosting then
                        CurrPage.Close();
                end;
            NavigateAfterPost::"New Document":
                if DocumentIsPosted then begin
                    Clear(SalesHeader);
                    SalesHeader.Init;
                    SalesHeader.Validate("Document Type", SalesHeader."Document Type"::Order);
                    OnPostOnBeforeSalesHeaderInsert(SalesHeader);
                    SalesHeader.Insert(true);
                    PAGE.Run(PAGE::"Sales Order", SalesHeader);
                end;
        end;
    end;

**Comment by AlexanderYakunin** [comment]
This functions have been already made external
    procedure PostDocument(PostingCodeunitID: Integer; Navigate: Option)

**Comment by bartpattijn** [comment]
This must be released on next CU?
Because on BC15 CU2 the procedure is still local:

 local procedure PostDocument(PostingCodeunitID: Integer; Navigate: Option)
    var
        SalesHeader: Record "Sales Header";
        LinesInstructionMgt: Codeunit "Lines Instruction Mgt.";
        InstructionMgt: Codeunit "Instruction Mgt.";
    begin
        if ApplicationAreaMgmtFacade.IsFoundationEnabled then
            LinesInstructionMgt.SalesCheckAllLinesHaveQuantityAssigned(Rec);




Met vriendelijke groeten,​
[Christiaens]
[Christiaens Connect | 18 02 20 | Inschrijven]<https://mailchi.mp/christiaens/christiaens-connect-180220>
Bart Pattijn
ERP Consultant
Christiaens NV
e:
bart.pattijn@christiaens.net
t:
0032 51 78 83 83
w:
www.christiaens.net
a:
Passendalestraat 199
B‑8980
Passendale
[LinkedIn]<https://www.linkedin.com/company/christiaens-nv/>
[YouTube]<https://www.youtube.com/channel/UCGBiFesfXKF0ErJfSZ1XxvQ>
[Twitter]<https://twitter.com/Christiaens_net>
[Facebook]<https://www.facebook.com/christiaensnv/>
[Teamviewer]<https://get.teamviewer.com/christiaens>

Van: Alexander Yakunin <notifications@github.com>
Verzonden: maandag 13 januari 2020 14:50
Aan: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
CC: Bart Pattijn <Bart.Pattijn@christiaens.net>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/ALAppExtensions] Page 42 Sales Order PostDocument function external access (#5346)


This functions have been already made external
procedure PostDocument(PostingCodeunitID: Integer; Navigate: Option)
