### ISSUE TITLE
Page 42 Sales Order bug

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#5350]
On page 42 sales order it is possible to change the customer through the "sell-to customer name" field to any value even when it should result in error.
for example when status = released, or when there is already shipped.
if you change throught the "Sell-to Customer No." field the errors are thrown, but when changing through the "sell-to customer name" there are no errors and the "sell-to" fields are changed.

**Comment by AndreiPanko** [comment]
Thank you for reaching out. Your suggestion seems to be a product bug. Please reach out to the relevant support channels as specified in Product Support 

- On premises - https://support.microsoft.com/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
- On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/pcv/dashboard/overview
