### ISSUE TITLE
[Enum Request] Table 311 and 312  Field "Default Posting Date"

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#5351]
Table 311 "Sales & Receivables Setup" Field "Default Posting Date"
Table 312 "Purchases & Payables Setup" Field "Default Posting Date"

We don't require additional publishers to make additional options work.
Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
