### ISSUE TITLE
Table 39 (Purchase Line) - OnAfterAddItem Event

### ISSUE THREAD

**Issue by JJODonovan** [microsoft/ALAppExtensions#5352]
Can you please add an OnAfterAddItem event to the Purchase Line to be called from the AddItems function (in the same way that this has been added to the Sales Line table)?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
