### ISSUE TITLE
Codeunit 11 Gen. Jnl.-Check Line (Previous Request ID #4332 which is done)

### ISSUE THREAD

**Issue by brijeshkarnatak** [microsoft/ALAppExtensions#5353]
Hi!

The Parameter is added on the function (CheckSalesDocNoIsNotUsed) now on "Update 15.2 for Microsoft Dynamics 365 Business Central 2019 Release Wave 2", but if we can add a parameter variable GenJnlLine : Record "Gen. Journal Line to the event “OnBeforeCheckSalesDocNoIsNotUsed” to make it more efficiently handled.

OnBeforeCheckSalesDocNoIsNotUsed(GenJnlLine : Record "Gen. Journal Line", ISHandled);

**Comment by AlexanderYakunin** [comment]
This is already done
        IsHandled := false;
        OnBeforeCheckSalesDocNoIsNotUsed(GenJournalLine."Document Type", GenJournalLine."Document No.", IsHandled, GenJournalLine);
        if IsHandled then
            exit;
