### ISSUE TITLE
T38 RecreatePurchLines extend OnBeforeRecreatePurchLines with handler and skip execution of entire code

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5354]
i think we didnt understood each other on ticket https://github.com/microsoft/ALAppExtensions/issues/4994. We need something OnBeforeRecreatePurchLines so we can skip execution of entire code.
Pseudo code:

![image](https://user-images.githubusercontent.com/53824412/71415660-16874800-265d-11ea-9abb-b79518126aed.png)

**Comment by AlexanderYakunin** [comment]
You can skip this procedure using existing event OnRecreatePurchLinesOnBeforeConfirm(Rec, xRec, ChangedFieldName, HideValidationDialog, Confirmed, IsHandled) by setting Confirmed = false and IsHandled = true. There is no need for additional event for this purpose.
