### ISSUE TITLE
[Enum Request] Table 5900 Service Header - Status

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#5355]
We would like to be able to give the user the ability to cancel a service order.
To make this possible we would like to extend the 'Status' field of table '5900 Service Header'.
Could you makt his field 'ENUM' ?

We do not require additional publisher for our functionality.

Many thanks.

**Comment by AlexanderYakunin** [comment]
This field have been converted to enum two months ago. Enum "Service Document Status"

Please make sure you use Master (aka Preview) code for enum request.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
