### ISSUE TITLE
[Enum Request] Table 5940 Service Item

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#5356]
e would like to be able to give the user the ability to cancel a service item.
To make this possible we would like to extend the 'Status' field of table '5940 Service Item'.
Could you makt his field 'ENUM' ?

We do not require additional publisher for our functionality.

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
