### ISSUE TITLE
[Event Request] Table 5964 Service Contract Line - Line Amount - Onvalidate

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#5357]
We would like to request the following publisher for table 5964 "Service Contract LIne" field "Line Amount". Same solution as the field "Line Discount %".

        field(24; "Line Amount"; Decimal)
        {
            AutoFormatType = 1;
            BlankZero = true;
            Caption = 'Line Amount';

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestStatusOpen;

                // START -->
                IsHandled := false;
                OnBeforeValidateLineAmount(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                // --< END

                TestField("Line Value");
                Currency.InitRoundingPrecision;
                "Line Discount Amount" := Round("Line Value" - "Line Amount", Currency."Amount Rounding Precision");
                "Line Discount %" := "Line Discount Amount" / "Line Value" * 100;
                Profit := Round("Line Amount" - "Line Cost", Currency."Amount Rounding Precision");
            end;
        }

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
