### ISSUE TITLE
[Event Request] Table 5964 Service Contract Line - UpdateContractAnnualAmount

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#5358]
We would like to place additional filters on service contract line. To make this possible we would like to requiest the following publisher:

    procedure UpdateContractAnnualAmount(Deleting: Boolean)
    var
        OldServContractHeader: Record "Service Contract Header";
        ServContractLine2: Record "Service Contract Line";
    begin
        GetServContractHeader;
        if not ServContractHeader."Allow Unbalanced Amounts" then begin
            ServContractLine.Reset;
            ServContractLine.SetRange("Contract Type", "Contract Type");
            ServContractLine.SetRange("Contract No.", "Contract No.");
            ServContractLine.SetFilter("Line No.", '<>%1', "Line No.");
            // START -->
            OnBeforeCalculateLineAmount(VAR ServContractLine);
            // <-- END 
            ServContractLine.CalcSums("Line Amount");
            OldServContractHeader := ServContractHeader;
            if Deleting then
                ServContractHeader."Annual Amount" := ServContractLine."Line Amount"
            else begin
                ServContractHeader."Annual Amount" := ServContractLine."Line Amount" + "Line Amount";
                if not "New Line" then
                    ContractGainLossEntry.AddEntry(4, "Contract Type", "Contract No.", "Line Amount" - xRec."Line Amount", '')

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
