### ISSUE TITLE
[Event Request] Table 5965 Service Contract Header - Next Invoice Date - OnValidate

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#5359]
Issue #3704 only has been partly implemented. Could you also add the second requested publisher of this issue? Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
