### ISSUE TITLE
CU 22 function UpdateUnitCost event needed OnAfterUpdateUnitCost

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5363]
HI
we need on CU 22 function UpdateUnitCost event needed OnAfterUpdateUnitCost, because we want to do somthing with LastDirectCost after it is finally set

![image](https://user-images.githubusercontent.com/53824412/71447085-e5754900-272a-11ea-9f2c-23e8f4714005.png)

**Comment by AlexanderYakunin** [comment]
I cannot implement requests without information about which parameters should use VAR. We have no simple way to add missing VAR anymore so all requests without clear specification will not be done. Please create another request with this information.

**Comment by VladimirVeljovic** [comment]
Hi,
no need for var, only to inspect other stuff

![image](https://user-images.githubusercontent.com/53824412/72259510-f241da00-3610-11ea-8cae-c246c9d40209.png)
