### ISSUE TITLE
Requesting GUIALLOWED-check in Codeunit 1255 "Match Bank Payments" on all DIALOGs 

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#5365]
Dear AL-team,

please encapsulate all Window.OPEN, Window.UPDATE and Window.Close with GUIALLOWED in the codeunit 1255 "Match Bank Payments" to allow to run the codeunit with code called by a JobQueue(-entry). [BC14CU7]
Thank you for your attention.
Regards
Walter

**Comment by RomanZanizdra** [comment]
Hi @sauerkreut .
Could you be so kind to explain what kind of problems you met? If I understand correctly there are no any problems on working together correctly of window open/update/close and job queues.

**Comment by sauerkreut** [comment]
Hi @RomanZanizdra 
sorry for my late reply. I was running a Codeunit via NAS and called functions in Codeunit 1255 "Match Bank Payments". The NAS "refused" to run the Window.Open statement and returned an error (in the event log). That was on BC14CU4(!). Referencing it to BC14CU**7** was wrong.
I think, all Dialog-functions should be encapsulated with Guiallowed.

**Comment by RomanZanizdra** [comment]
Hi @sauerkreut . Do you get the same result with the latest version? Can you try the same on 15 versionfor example?

**Comment by sauerkreut** [comment]
Hello @RomanZanizdra . We are currently in the transition from 14 to 15. I will install the extension on 15 in a few days and will let you know as soon an possible.
