### ISSUE TITLE
[Event Request] Table 5092 - CreateOppFromOppOnAfterInit

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5369]
Hi, we need event in CreateOppFromOpp function on table 5092 Opportunity
```
DeleteAll;
Init;
New-> CreateOppFromOppOnAfterInit(Rec,Opp);
"Creation Date" := WorkDate;
SetDefaultSalesCycle;
if Cont.Get(Opp.GetFilter("Contact Company No.")) then begin
...
...
```

Publisher:
```
LOCAL [IntegrationEvent] CreateOppFromOppOnAfterInit (VAR Rec : Record Opportunity;VAR Opp : Record Opportunity)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
