### ISSUE TITLE
[Event Request] Table 5092 - OnAfterInsertOpportunity

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5370]
Hi, we need event in InsertOpportunity function in table 5092 Opportunity

At the end of the function event will be:

`OnAfterInsertOpportunity(Rec,Opp);`

Publisher will be:
```
LOCAL [IntegrationEvent] OnAfterInsertOpportunity(VAR Rec : Record Opportunity;VAR Opp : Record Opportunity)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
