### ISSUE TITLE
CU22 event needed in function CollectTrackingSpecification

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#5373]
Hi we need a event in function CollectTrackingSpecification CU22 like:

![image](https://user-images.githubusercontent.com/53824412/71476829-52e6af80-27e7-11ea-866f-3c8092c0f9cd.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
