### ISSUE TITLE
In Codeunit 8612 make function InsertTamplate external

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5374]
Hey, 

we would like that function InsertTablate in Codeunit 8612 - Config. Template Management to be External instead of Local function.

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
