### ISSUE TITLE
[Event Request] Report 393 - Vendor - OnPostDataItem()

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#5375]
....
DimSetEntry.LOCKTABLE;
GenJnlLine.LOCKTABLE;
GenJnlTemplate.GET(GenJnlLine."Journal Template Name");
GenJnlBatch.GET(GenJnlLine."Journal Template Name",GenJnlLine."Journal Batch Name");
GenJnlLine.SETRANGE("Journal Template Name",GenJnlLine."Journal Template Name");
GenJnlLine.SETRANGE("Journal Batch Name",GenJnlLine."Journal Batch Name");
IF GenJnlLine.FINDLAST THEN BEGIN
  LastLineNo := GenJnlLine."Line No.";
  GenJnlLine.INIT;
END;

Window2.OPEN(Text008);

PayableVendLedgEntry.RESET;
PayableVendLedgEntry.SETRANGE(Priority,1,2147483647);
MakeGenJnlLines;
PayableVendLedgEntry.RESET;
PayableVendLedgEntry.SETRANGE(Priority,0);
MakeGenJnlLines;
PayableVendLedgEntry.RESET;
PayableVendLedgEntry.DELETEALL;

//New Code >>>>
OnAfterPostDataItem(GenJnlBatch,GenJnlLine2."Bal. Account Type",GenJnlLine2."Bal. Account No.");
//New Code <<<<

Window2.CLOSE;
Window.CLOSE;
ShowMessage(MessageText);

Event Signature
Local [IntegrationEvent] OnAfterPostDataItem(VAR GenJnlBatch : Record "Gen. Journal Batch";BalAccType : Integer;BalAccNo : Code[20])

**Comment by dharma534** [comment]
Please consider this event

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
