### ISSUE TITLE
[Event Request] Report 5692 Fixed Asset OnPostDataItem()

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#5376]
......
IF GenJnlLineTmp.FIND('-') THEN
    REPEAT
      INIT;
      "Line No." := 0;
      FAJnlSetup.SetGenJnlTrailCodes(GenJnlLine);
      LineNo := LineNo + 1;
      Window.UPDATE(3,LineNo);
      "Posting Date" := PostingDate;
      "FA Posting Date" := DeprUntilDate;
      IF "Posting Date" = "FA Posting Date" THEN
        "FA Posting Date" := 0D;
      "FA Posting Type" := GenJnlLineTmp."FA Posting Type";
      "Account Type" := "Account Type"::"Fixed Asset";
      VALIDATE("Account No.",GenJnlLineTmp."Account No.");
      Description := PostingDescription;
      "Document No." := DocumentNo2;
      "Posting No. Series" := NoSeries;
      VALIDATE("Depreciation Book Code",DeprBookCode);
      VALIDATE(Amount,GenJnlLineTmp.Amount);
      "No. of Depreciation Days" := GenJnlLineTmp."No. of Depreciation Days";
      "FA Error Entry No." := GenJnlLineTmp."FA Error Entry No.";
      GenJnlNextLineNo := GenJnlNextLineNo + 1000;
      "Line No." := GenJnlNextLineNo;
      INSERT(TRUE);
      GenJnlLineCreatedCount += 1;
      IF BalAccount THEN
        FAInsertGLAcc.GetBalAcc2(GenJnlLine,GenJnlNextLineNo);
    UNTIL GenJnlLineTmp.NEXT = 0;
END;

//New Code >>>>
OnAfterPostDataItemFAReport();
//New Code <<<<

Event Signature
Local [IntegrationEvent] OnAfterPostDataItem()

**Comment by dharma534** [comment]
Please consider this event

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
