### ISSUE TITLE
[Event Request] Table 5715 - OnAfterSetItemVariantDescription

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5379]
Hi, we need event in function SetItemVariantDescription in table 5715 Item Substitution..
After logic event will be:
```
OnAfterSetItemVariantDescription(Type , Number, Variant, Description);
```
Publisher:
```
LOCAL [IntegrationEvent] OnAfterSetItemVariantDescription(Type : Integer;Number : Code[20];Variant : Code[10];VAR Description : Text[100])
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
