### ISSUE TITLE
[Event Request] Table 5718 - OnValidateVendorNo

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5380]
1. Hi, we need event OnValidate trigger for field Vendor No. in table 5718 Nonstock Item

```
Vendor No. - OnValidate()
New-> OnValidateVendorNo(Rec,xRec,IsHandled);
if IsHandled then
   exit;
if ("Vendor Item No." <> xRec."Vendor Item No.") and
   ("Item No." <> '')
then
   Error(Text001);

if "Vendor Item No." <> xRec."Vendor Item No." then
   if CheckVendorItemNo("Vendor No.", "Vendor Item No.") then
      Error(Text002, "Vendor No.", "Vendor Item No.");
```

Publisher:
```
LOCAL [IntegrationEvent] OnValidateVendorNo(VAR Rec : Record "Nonstock Item";xRec : Record "Nonstock Item";VAR IsHandled : Boolean)
```

Also if you can make function **CheckVendorItemNo** as **External** so we can call it from that Event

2. We need exactly the same event and behavior on Vendor Item No. - OnValidate()

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
