### ISSUE TITLE
[Event Request]  Codeunit 7301 Whse. Jnl.-Register Line Change Parameter OnInitWhseEntryCopyFromWhseJnlLine

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#5381]
[Event Request]  
Object: Codeunit 7301 Whse. Jnl.-Register Line 
Event: OnInitWhseEntryCopyFromWhseJnlLine
Param: WarehouseJournalLine 

Could you please pass the parameter WarehouseJournalLine as Var ?

**Comment by aconcato** [comment]
Any update on it?

**Comment by aconcato** [comment]
Recreated maybe your bcghost  is not working.. Codeunit 7301 Whse. Jnl.-Register Line Change Parameter OnInitWhseEntryCopyFromWhseJnlLine #5901

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
