### ISSUE TITLE
[Event Request] Table 5718 - OnModifyBeforeError

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5382]
Hi, we need event in Modify trigger in table 5718 Nonstock Item..

Event will be placed here:
```
New->   OnModifyBeforeError(Rec,IsHandled);
New->   if IsHandled then
New->       exit;
        Item.SetRange("No.", ItemNo);
        if not Item.IsEmpty then
            Error(Text001);
```
Publisher will be:
```
LOCAL [IntegrationEvent] OnModifyBeforeError(VAR NonstockItem : Record "Nonstock Item";VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
