### ISSUE TITLE
Add 2 Functions Page 6520

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [Microsoft/ALAppExtensions#539]
Can you add 2 new Functions on Page 6520 GetFilters & Set Filters and make them Global and External.  We need the ability to change the filter variables, from other filters that we add.  

GetFilters
![image](https://user-images.githubusercontent.com/32099690/49540402-40709f80-f88d-11e8-828a-3dd42d92ae05.png)
![image](https://user-images.githubusercontent.com/32099690/49540418-4a929e00-f88d-11e8-8a60-9e51c7664562.png)

SetFilters
![image](https://user-images.githubusercontent.com/32099690/49540431-5716f680-f88d-11e8-965d-96b5bfa34661.png)
![image](https://user-images.githubusercontent.com/32099690/49540453-6138f500-f88d-11e8-8490-2d9d14677b03.png)

**Comment by MatthewMcCarthy7** [comment]
I was checking in on the status of this request.

**Comment by IhorHandziuk** [comment]
Thank you for the request and sorry for the late reply. This functions will be available in the next update.

**Comment by MatthewMcCarthy7** [comment]
I just pulled the new daily builds and realized there is an issue with the Function name GetFilters does not work since that is a System function name.  Can GetFilters be rename to GetVariableFilters and SetFilters be rename to SetVariableFilters.
