### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134046 "ERM Prices Incl VAT Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5393]
[Event Request] Application “Tests-ERM”, Codeunit 134046 "ERM Prices Incl VAT Doc"
![pic1](https://user-images.githubusercontent.com/45795262/71524115-530cab00-28cc-11ea-812d-ce6a16a29d25.png)

Could you please insert an OnAfter… Event at the end of procedure CreateSingleLinePurchaseDoc? By this we can do some additional modifications for our branch solution. So that the standard tests will also run successful in our solution.
![pic2](https://user-images.githubusercontent.com/45795262/71524125-59028c00-28cc-11ea-88c9-41344515c57c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
