### ISSUE TITLE
[Bug] COD 700 - OnBeforeGetConditionalListPageID

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5394]
#4255 is wrongly coded.

The code does not use the PageID set by any possible subscribers. It must be refactored to return the pageId

![image](https://user-images.githubusercontent.com/25268332/71548945-eb328f00-29b5-11ea-8c1f-9e645d0b1de8.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
