### ISSUE TITLE
[Event Parameters] COD Mail Management - OnBeforeRunMailDialog

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5395]
Following #4308

Can you please also provide access to the following 2 globals by adding 2 VAR parameters in OnBeforeRunMailDialog:

- DoEdit
- Cancelled

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
