### ISSUE TITLE
[Event Request] COD1173 - OnBeforeCopyAttachmentsForPostedDocsLines

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5396]
Hello,

we would need an Event in the CopyAttachmentsForPostedDocsLines-procedure to skip the Source Code in this function (otherwise it would help us if the souce Code would make an additional check that the ToRecRef is initialized).

![image](https://user-images.githubusercontent.com/45033081/71574234-2cc35700-2ae8-11ea-93bd-f94ac93c9165.png)

**Comment by AlexanderYakunin** [comment]
Can you suggest how you would like to update/extend this code for ToRecRef?

**Comment by SKeiler** [comment]
Hi Alexander,

do you mean what I wrote in Spaces?

It would help us if there would be an additional 

IF ToRecRef.NUMBER = 0 THEN BEGIN
  EXIT;
END;

That  would make the code safer that it could Can not be fail anymore.

Also we have the requirement that we delete a (already posted) sales doc without a invoice/credit Memo was created (because it was an internal doc). That  fails now because of this source code.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
