### ISSUE TITLE
Page 5600 Fixed Asset Card acces to functions

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#5397]
Would it be possible to have the functions:
 - LoadDepreciationBooks
 - SaveSimpleDepriciationBook
 - ShowAcquireNotification
to be accessible from a page extension?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
