### ISSUE TITLE
[Event Request] COD1380 BatchProcess - Reopen

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5398]
Hi, I would like to reopen the Issue #2509 (https://github.com/microsoft/ALAppExtensions/issues/2509) because there is an error in the MS-implementation (see the last comment)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
