### ISSUE TITLE
[Event Request] Table 5876 - CalcQtyAndTrackLinesExpectedOnPhysInvtTrackingNotGet

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5399]
Hi, we need event in table 5876 on function CalcQtyAndTrackLinesExpected on following place:
![image](https://user-images.githubusercontent.com/54843470/71577160-5c2b9100-2af3-11ea-8fcc-9777e6593ac4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
