### ISSUE TITLE
The type or method 'OnRoleCenterOpen' cannot be used for 'Extension' development 

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/ALAppExtensions#54]
The type or method 'OnRoleCenterOpen' cannot be used for 'Extension' development

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
OnRoleCenterOpen is an integration event. Events are generally not exposed for extension development. This one, however, might be an exception, seeing that it is needed for new role centers, which CAN be developed through extensions. Tagging issue as request-for-external.

**Comment by JesperSchulz** [comment]
I will introduce a new public, external function by the name RaiseOnOpenRoleCenterEvent, as we'd perfarebly would like to avoid exposing events.
