### ISSUE TITLE
[Event Request] Table 5900 - OnValidate Customer No. OnValidateCustomerNoOnBeforeDeleteLines

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5400]
Hi, we would like a new event On Validate Customer No. in table 5900 Service Header, we have modification to change lines instead of deleting them when you change Customer No.

Event would be placed here:
![image](https://user-images.githubusercontent.com/54843470/71577850-0ad0d100-2af6-11ea-975b-e38ae90a9b4f.png)
Publisher will be:
```
[IntegrationEvent(false, false)]
local procedure OnValidateCustomerNoOnBeforeDeleteLines(ServiceHeader: Record "Service Header";var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
