### ISSUE TITLE
[Event Request] Table 5900 - OnValidate Ship-to Code OnValidateShiptoCodeOnBeforeDeleteLines

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5401]
Hi, we need event in table 5900 On Validate Ship-to Code, we have modification to avoid deleting lines..
![image](https://user-images.githubusercontent.com/54843470/71578964-9e0c0580-2afa-11ea-9fdc-fbf473c43e01.png)

Publisher:
```
[IntegrationEvent(false, false)]
local procedure OnValidateShiptoCodeOnBeforeDeleteLines(ServiceHeader: Record "Service Header";var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
