### ISSUE TITLE
[Event Request] Table 5900 - OnValidate Payment Terms Code OnValidatePaymentTermsCodeOnBeforeValidateDueDate

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5402]
Hi, we need event in table 5900 On Validate Payment Terms Code, we have modification to change Due Date only when it is 0D...

![image](https://user-images.githubusercontent.com/54843470/71579289-3656ba00-2afc-11ea-9de8-90d10ed08eae.png)

Publisher:

```
[IntegrationEvent(false, false)]
local procedure OnValidatePaymentTermsCodeOnBeforeValidateDueDate(ServiceHeader: Record "Service Header";var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
