### ISSUE TITLE
[Event Request] Table 5900 - OnValidate VAT Base Discount % OnValidateVATBaseDiscount

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5403]
Hi, we need event in table 5900 On Validate VAT Base Discount %, event will be:

![image](https://user-images.githubusercontent.com/54843470/71579456-e7f5eb00-2afc-11ea-8836-322c15ee0a5e.png)

Publisher will be:
```
[IntegrationEvent(false, false)]
local procedure OnValidateVATBaseDiscount(ServiceHeader: Record "Service Header";var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
