### ISSUE TITLE
[Event Request] Table 5900 - OnRecreateServLines

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5404]
Hi, we need event in Table 5900 on function RecreateServLines, we have modification to apply our own recreate logic... Event will be following:
![image](https://user-images.githubusercontent.com/54843470/71579613-ad408280-2afd-11ea-9ae7-3ed8dd467a03.png)

Publisher will be:
```
[IntegrationEvent(false, false)]
local procedure OnRecreateServLines(ServiceHeader: Record "Service Header";var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
