### ISSUE TITLE
[Event Request] Table 5901 - OnAfeterSetUpNewLine

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5408]
Hi, we need event in function SetUpNewLine in table 5901, you can see implementation on picture:
![image](https://user-images.githubusercontent.com/54843470/71580946-3e662800-2b03-11ea-9549-cd5d0e59c61e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
