### ISSUE TITLE
[Event Change] Codeunit 5987 Serv-Posting Journals Mgt. - Function PostCustomerEntry - Event OnBeforePostCustomerEntry

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5409]
Hey,

on Codeunit 5987 Serv-Posting Journals Mgt. , function PostCustomerEntry, we would like that event OnBeforePostCustomerEntry has additional parameter TotalServiceLine(Record 5902).

Original publisher definition:
```
LOCAL [IntegrationEvent] OnBeforePostCustomerEntry(VAR GenJournalLine : Record "Gen. Journal Line";ServiceHeader : Record "Service Header")
```

Changed publisher definition:
```
LOCAL [IntegrationEvent] OnBeforePostCustomerEntry(VAR GenJournalLine : Record "Gen. Journal Line";ServiceHeader : Record "Service Header";VAR TotalServiceLine : Record "Service Line")
```
Function code:
```
  Amount := -TotalServiceLine."Amount Including VAT";
  "Source Currency Amount" := -TotalServiceLine."Amount Including VAT";
  "Amount (LCY)" := -TotalServiceLineLCY."Amount Including VAT";
  "Sales/Purch. (LCY)" := -TotalServiceLineLCY.Amount;
  "Profit (LCY)" := -(TotalServiceLineLCY.Amount - TotalServiceLineLCY."Unit Cost (LCY)");
  "Inv. Discount (LCY)" := -TotalServiceLineLCY."Inv. Discount Amount";
  "System-Created Entry" := TRUE;

  OnBeforePostCustomerEntry(GenJnlLine,ServiceHeader, TotalServiceLine); // <-- Added parameter
  GenJnlPostLine.RunWithCheck(GenJnlLine);
  OnAfterPostCustomerEntry(GenJnlLine,ServiceHeader,GenJnlPostLine);
END;
```

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
