### ISSUE TITLE
REP94 - OnBeforeCheckDimPostingRules - Add GenJnlLine-Parameter

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5410]
Could you please expand the existing OnBeforeCheckDimPostingRules-Event in REP94 and add a GenJnlLine-Parameter.

![image](https://user-images.githubusercontent.com/45033081/71582728-b9334100-2b0b-11ea-93cc-f880ea62d3f7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
