### ISSUE TITLE
PAG99000883 - OnBeforeCalculatePlanAndDelivDates 

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5412]
Hi,

could you please add an Event in CalculatePlanAndDelivDates-function in PAG99000883 with a VAR Item Parameter.

![image](https://user-images.githubusercontent.com/45033081/71582850-2b0b8a80-2b0c-11ea-98fb-0ecf5a68b868.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
