### ISSUE TITLE
TAB7354 - OnBeforeCheckWhseClass

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5413]
Hi,

could you please add an Event in TAB7354 in CheckWhseClass-function. There should be a handled-Event and a parameter to set the return value of the CheckWhseClass-function.

![image](https://user-images.githubusercontent.com/45033081/71583010-df0d1580-2b0c-11ea-8e1f-b53f3f8c4d7b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
