### ISSUE TITLE
[Event Request] Codeunit 5987 - Serv-Posting Journals Mgt. - Function PostResJnlLine - Event OnBeforePostResJnlLine

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5414]
Hey,
we would like a event OnBeforePostResJnlLine in Codeunit 5987 - Serv-Posting Journals Mgt. on function PostResJnlLine .

Codeunit 5987 - Serv-Posting Journals Mgt. - Function PostResJnlLine :
```
LOCAL PostResJnlLine(ServiceHeader : Record "Service Header";ServiceLine : Record "Service Line";DocNo : Code[20];ExtDocNo : Code[35];SrcCode : Code[10];PostingNoSeries : Code[20];EntryType : Option;Qty : Decimal;UnitPrice : Decimal;TotalPrice : Decim
WITH ResJnlLine DO BEGIN
  INIT;
  CopyDocumentFields(DocNo,ExtDocNo,SrcCode,PostingNoSeries);
  CopyFromServHeader(ServiceHeader);
  CopyFromServLine(ServiceLine);

  "Entry Type" := EntryType;
  Quantity := Qty;
  "Unit Cost" := ServiceLine."Unit Cost (LCY)";
  "Total Cost" := ServiceLine."Unit Cost (LCY)" * Quantity;
  "Unit Price" := UnitPrice;
  "Total Price" := TotalPrice;

  OnBeforePostResJnlLine(ResJnlLine,ServiceHeader,ServiceLine); //NEW
  ResJnlPostLine.RunWithCheck(ResJnlLine);
END;
```

Publisher definition:
```
LOCAL [IntegrationEvent] OnBeforePostResJnlLine(VAR ResJnlLine : Record "Res. Journal Line";ServiceHeader : Record "Service Header";ServiceLine : Record "Service Line")
```

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
