### ISSUE TITLE
[Event Request] Table 5901 - OnCheckWarranty

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5415]
Hi, we need event in function CheckWarranty in table 5901, you can see implementation on picture:

![image](https://user-images.githubusercontent.com/54843470/71587476-1df79700-2b1e-11ea-8093-e74cef8c07d3.png)

Publisher:
```
[IntegrationEvent(false, false)]
local procedure OnCheckWarranty(var ServiceItemLine: Record "Service Item Line";var Warranty:Boolean;var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
