### ISSUE TITLE
[Event Request] Table 9650 OnBeforeUpdateLayout

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#5416]
Publisher desired in Table  9650 on the start of the function UpdateLayout.

OnBeforeUpdateLayout(var LayoutUpdated: boolean;var Handled: boolean);
If Handled then
  Exit(LayoutUpdated)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
