### ISSUE TITLE
[Event Request] Codeunit 9651 OnBeforeMergeWordDocument

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#5417]
Please Extend the publisher OnBeforeMergeWordDocument with following parameters:

Handled := false;
OnBeforeMergeWordDocument(ReportID : Integer;ReportAction : 'SaveAsPdf,SaveAsWord,SaveAsExcel,Preview,Print,SaveAsHtml';VAR InStrXmlData : InStream;PrinterName : Text;InStrWordDoc: InStream;OutStrWordDoc: OutStream;VAR Handled : Boolean;FileName : Text; var TempBlob: Codeunit "Temp Blob");
If Handled then
  Exit;

**Comment by AlexanderYakunin** [comment]
Please explain what you are going to achieve with this event?You want to add as parameters several local variables, which are not initialized at this point. At the same time you want to handle and exit after this event? Please remove unnecessary parameters and define local variables inside of your code.
