### ISSUE TITLE
[Event Request] Codeunit 9651 OnAfterMergeWordDocumentBeforeCommit

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#5418]
Please add following Publisher in Codeunit 9651:

Handled := false;
OnAfterMergeWordDocumentBeforeCommit(ReportID : Integer;ReportAction : 'SaveAsPdf,SaveAsWord,SaveAsExcel,Preview,Print,SaveAsHtml';VAR InStrXmlData : InStream;PrinterName : Text;VAR Handled : Boolean;FileName : Text; var TempBlob: Codeunit "Temp Blob");
If Handled then
Exit;

**Comment by AlexanderYakunin** [comment]
Please specify procedure name, position and explain how you would like to have OnAfter event with handled pattern. Usually this is last event in the code.

**Comment by miljance** [comment]
Procedure: MergeWordLayout
Position: Just above two following lines of code:
```
Commit;
OnAfterMergeWordDocument(ReportID, InStrXmlData, TempBlobOut);
```
"OnAfter" with handled Pattern like described above. The function should be in the middle of the function MergeWordLayout and being able to exit in the middle of the function. There is already other publisher with "OnAfter" naming which is in the middle of the function.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
