### ISSUE TITLE
[Event Request] Codeunit 93 - OnAfterRun

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5419]
Hi, we would like on after run new event like it is in CU 94:

In 94 it is: 
![image](https://user-images.githubusercontent.com/54843470/71618557-59e33880-2bc0-11ea-818f-eef47571401d.png)

In 93 we need it here:
![image](https://user-images.githubusercontent.com/54843470/71618603-a169c480-2bc0-11ea-91ec-a8ae01713f5a.png)

Publisher
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreatePurchOrder(var PurchaseHeader: Record "Purchase Header"; var SkipMessage: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
