### ISSUE TITLE
[Event Request] Codeunit 249 - InsertVATRegistrationLog

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5421]
We need new event in function InsertVATRegistrationLog, on following place:

```
LOCAL InsertVATRegistrationLog(VATRegNo : Text[20];CountryCode : Code[10];AccountType : Option;AccountNo : Code[20])
WITH VATRegistrationLog DO BEGIN
  INIT;
  "VAT Registration No." := VATRegNo;
  "Country/Region Code" := CountryCode;
  "Account Type" := AccountType;
  "Account No." := AccountNo;
  "User ID" := USERID;
  INSERT(TRUE);
New->  OnAfterInsertVATRegistrationLog(VATRegistrationLog );
END;
```

Publisher:
```
LOCAL [IntegrationEvent] OnAfterInsertVATRegistrationLog(VAR VATRegistrationLog : Record "VAT Registration Log")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
