### ISSUE TITLE
page 11300 Financial Journal UpdateStatementAmounts

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#5424]
is it possible to have an event in page Financial Journal at the end of function UpdateStatementAmounts;

procedure UpdateStatementAmounts()
    begin
        FilterGroup(2);
        GenJnlTemplate.Get(GetFilter("Journal Template Name"));
        FilterGroup(0);
        if GenJnlTemplate.Type = GenJnlTemplate.Type::Financial then
            GenJnlTemplate.TestField("Bal. Account No.");
        case GenJnlTemplate."Bal. Account Type" of
            0:
                begin
                    GLAccount.Get(GenJnlTemplate."Bal. Account No.");
                    GLAccount.CalcFields(Balance);
                    if GLAccount.Balance <> BalanceLastStatement then begin
                        BalanceLastStatement := GLAccount.Balance;
                        StatementEndingBalance := 0
                    end;
                end;
            3:
                begin
                    BankAccount.Get(GenJnlTemplate."Bal. Account No.");
                    BankAccount.CalcFields(Balance);
                    if BankAccount.Balance <> BalanceLastStatement then begin
                        BalanceLastStatement := BankAccount.Balance;
                        StatementEndingBalance := 0;
                    end;
                end;
        end;
       OnAfterUpdateStatementAmounts(Rec,var StatementEndingbalance); //new event
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
