### ISSUE TITLE
[Event Request] Codeunit 5932 - Service-Get Shipment - Function CalcAvailableInventory - Event OnBeforeCalcAvailableInventory

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5425]
Hey,
we would like a event SetServiceShptLineAdditionalFilters in Codeunit 5932 - Service-Get Shipment on function OnRun.

Codeunit 5932 - Service-Get Shipment  - Function OnRun:

```
OnRun(VAR Rec : Record "Service Line")
ServiceHeader.GET("Document Type","Document No.");
ServiceHeader.TESTFIELD("Document Type",ServiceHeader."Document Type"::Invoice);

CLEAR(ServiceShptLine);
ServiceShptLine.SETCURRENTKEY("Bill-to Customer No.");
ServiceShptLine.SETRANGE("Bill-to Customer No.",ServiceHeader."Bill-to Customer No.");
ServiceShptLine.SETFILTER("Qty. Shipped Not Invoiced",'<>0');
ServiceShptLine.SETRANGE("Currency Code",ServiceHeader."Currency Code");

SetServiceShptLineAdditionalFilters(ServiceShptLine); //NEW

ServiceShptLine.FILTERGROUP(2);

GetServiceShipments.SETTABLEVIEW(ServiceShptLine);
GetServiceShipments.SetServiceHeader(ServiceHeader);
GetServiceShipments.LOOKUPMODE(TRUE);
GetServiceShipments.RUNMODAL;
```

Publisher definition:

```
LOCAL [IntegrationEvent] SetServiceShptLineAdditionalFilters(VAR ServiceShptLine : Record "Service Shipment Line")
```

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
