### ISSUE TITLE
[Event Request] Codeunit 5703 - Catalog Item Management - Function NonstockItemDel- Event OnAfterNonstockItemDel

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5426]
Hey,
we would like a event OnAfterNonstockItemDel in Codeunit 5703 - Catalog Item Management on function NonstockItemDel.

Codeunit 5703 - Catalog Item Management - Function NonstockItemDel:

```
[External] NonstockItemDel(VAR Item : Record Item)
ItemVend.SETRANGE("Item No.",Item."No.");
ItemVend.SETRANGE("Vendor No.",Item."Vendor No.");
ItemVend.DELETEALL;

ItemCrossReference.SETRANGE("Item No.",Item."No.");
ItemCrossReference.SETRANGE("Variant Code",Item."Variant Filter");
ItemCrossReference.DELETEALL;

OnAfterNonstockItemDel(Item);
```

Publisher definition:

```
LOCAL [IntegrationEvent] OnAfterNonstockItemDel(VAR Item : Record Item)
```

Thanks in addition.
Best regards

**Comment by AlexanderYakunin** [comment]
Here is full code of this procedure, please provide exact position of requested event. Either name or position of event is not correct in your request.

    procedure NonstockItemDel(var Item: Record Item)
    var
        ItemCrossReference: Record "Item Cross Reference";
    begin
        ItemVend.SetRange("Item No.", Item."No.");
        ItemVend.SetRange("Vendor No.", Item."Vendor No.");
        ItemVend.DeleteAll();

        ItemCrossReference.SetRange("Item No.", Item."No.");
        ItemCrossReference.SetRange("Variant Code", Item."Variant Filter");
        ItemCrossReference.DeleteAll();

        NonStock.SetCurrentKey("Item No.");
        NonStock.SetRange("Item No.", Item."No.");
        if NonStock.Find('-') then
            NonStock.ModifyAll("Item No.", '');
    end;

**Comment by StefanSosic** [comment]
Hey, its possition, it should be on bottom.
Procedure with added event:
```
procedure NonstockItemDel(var Item: Record Item)
var
    ItemCrossReference: Record "Item Cross Reference";
begin
    ItemVend.SetRange("Item No.", Item."No.");
    ItemVend.SetRange("Vendor No.", Item."Vendor No.");
    ItemVend.DeleteAll();

    ItemCrossReference.SetRange("Item No.", Item."No.");
    ItemCrossReference.SetRange("Variant Code", Item."Variant Filter");
    ItemCrossReference.DeleteAll();

    NonStock.SetCurrentKey("Item No.");
    NonStock.SetRange("Item No.", Item."No.");
    if NonStock.Find('-') then
        NonStock.ModifyAll("Item No.", '');

    OnAfterNonstockItemDel(Item);
end;
```

Publisher definition:
```
LOCAL [IntegrationEvent] OnAfterNonstockItemDel(VAR Item : Record Item)
```

Thanks.

Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
