### ISSUE TITLE
[Function expose] Table 7326 - AssignedQtyOnReservedLines

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/ALAppExtensions#5430]
```
- local procedure AssignedQtyOnReservedLines(): Decimal
+ procedure AssignedQtyOnReservedLines(): Decimal
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
