### ISSUE TITLE
COD408 - OnAfterSetSourceCode

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5431]
Hello,

we need an Event in the SetSourceCode-procedure in COD408 to have the possibility to overwrite the source Code. As a little special we need the Source Record to set the Source Code dependent on this record, for example the Sales Header.

![image](https://user-images.githubusercontent.com/45033081/71659358-99885c80-2d47-11ea-9b25-19ef497254e0.png)

**Comment by AlexanderYakunin** [comment]
We cannot change signature for external function, this is breaking change. Please find another solution for your requirements.

**Comment by SKeiler** [comment]
Okay and how it should be possible to add own Document Source Codes include a own Dimension priority?

In COD408 there is an Event (OnGetRecDefaultDimID) where it is possible to Change the source Code for Dimension finding!

**Comment by SKeiler** [comment]
Than you should do a design change. Please add a new function SetSourceCode2 which is called from COD481 instead of the "SetSourceCode"-procedure. The new function should first call the (old) SetSourceCode-Function and than calls the Event like described above.

**Comment by AlexanderYakunin** [comment]
I understand you requirement and we will find solution.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
