### ISSUE TITLE
[SaaS] E-mail Item - add AddAttachmentStream function

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#5433]
Sending mails via "E-Mail item" table is easy. Adding attachments is currently only supported in OnPrem via the "Attachment File Path" fields.

Please also provide support on 'E-mail Item' table to allow sending (unlimited number of) attachments in a Saas environment. We'd like to be able adding attachments via Streams instead. (similar to the SMTP mailing)

See more info:
http://www.mynavblog.com/2019/12/17/sending-mails-in-the-cloud/

**Comment by JesperSchulz** [comment]
Hi Frédéric!

Thanks for the input! As you know, this is quite a popular request with numerous asks and votes registered on aka.ms/bcideas ([here's one example, where you even replied](https://experience.dynamics.com/ideas/idea/?ideaid=e12d2e5e-3cc9-e811-b96f-0003ff689b02)). We are currently working on a mail-story refresh, where this idea definitely is considered.
Until the new solution is ready, please keep using codeunit "SMTP Mail" to create mails with attachments in the cloud (function AddAttachmentStream).
Work is in progess ;-)
