### ISSUE TITLE
[Event Request] Table 5902 - TestBinCode

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5434]
1. Hi, we need new event OnBeforeTestBinCode in table 5902 in function TestBinCode, implementation is shown on following image: 
![image](https://user-images.githubusercontent.com/54843470/71717772-6dd5a700-2e19-11ea-9adc-1d10937ccc10.png)

2. **We need exactly the same event and behavior in function GetDefaultBin**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
