### ISSUE TITLE
[Event Request] Table 5902 - CopyFromServItem

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5435]
Hi, we need new event in function CopyFromServItem in table 5902, with following implementation: 
![image](https://user-images.githubusercontent.com/54843470/71719878-040ccb80-2e20-11ea-99fb-611e6859f861.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
