### ISSUE TITLE
[Event Request] Codeunit 5972 - Service Info-Pane Management - Function CalcNoOfServItemComponents- Event OnBeforeCalcNoOfServItemComponents

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5437]
Hey,
we would like a event OnBeforeCalcNoOfServItemComponents in Codeunit 5972 - Service Info-Pane Management on function CalcNoOfServItemComponents.

Codeunit 5972 - Service Info-Pane Management - Function CalcNoOfServItemComponents:

```
[External] CalcNoOfServItemComponents(VAR ServItemLine : Record "Service Item Line") : Integer
//+++NEW
OnBeforeCalcNoOfServItemComponents(ServItemLine, IsHandled);
IF IsHandled THEN
  EXIT(0);
//---NEW
IF ServItem.GET(ServItemLine."Service Item No.") THEN BEGIN
  ServItemComponent.RESET;
  ServItemComponent.SETRANGE(Active,TRUE);
  ServItemComponent.SETRANGE("Parent Service Item No.",ServItemLine."Service Item No.");
  EXIT(ServItemComponent.COUNT);
END;
```

Publisher definition:

```
LOCAL [IntegrationEvent] OnBeforeCalcNoOfServItemComponents(VAR ServItemLine : Record "Service Item Line";VAR IsHandled : Boolean)
```

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
