### ISSUE TITLE
[Event Request] Codeunit 5972 - Service Info-Pane Management - Function CalcNoOfSkilledResources- Event OnBeforeCalcNoOfSkilledResources

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5439]
Hey,
we would like a event OnBeforeCalcNoOfSkilledResources in Codeunit 5972 - Service Info-Pane Management on function CalcNoOfSkilledResources.

Codeunit 5972 - Service Info-Pane Management - Function CalcNoOfSkilledResources:

```
[External] CalcNoOfSkilledResources(VAR ServItemLine : Record "Service Item Line") : Integer
//+++NEW
OnBeforeCalcNoOfSkilledResources(ServItemLine, IsHandled);
IF IsHandled THEN
  EXIT(0);
//---NEW
IF ServItem.GET(ServItemLine."Service Item No.") THEN BEGIN
  Res.RESET;
  IF Res.FIND('-') THEN
    REPEAT
      IF ServOrderAllocMgt.ResourceQualified(Res."No.",ResourceSkillType::"Service Item",ServItem."No.") THEN
        NoOfSkilledResources += 1;
    UNTIL Res.NEXT = 0;
  EXIT(NoOfSkilledResources);
END;
```

Publisher definition:

```
LOCAL [IntegrationEvent] OnBeforeCalcNoOfSkilledResources(VAR ServItemLine : Record "Service Item Line";VAR IsHandled : Boolean)
```

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
