### ISSUE TITLE
[Event Request] Table 5902 - CopyFromItem 

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5440]
Hi, we need new event in function CopyFromItem in table 5902, with following implementation:

![image](https://user-images.githubusercontent.com/54843470/71721005-daee3a00-2e23-11ea-97b0-c123b586b206.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
