### ISSUE TITLE
[Event Request] Codeunit 5610 - Calculate Depreciation - Function Calculate - Event OnBeforeCheckDeprDaysInFiscalYear

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5441]
Hey,
we would like a event OnBeforeCheckDeprDaysInFiscalYear in Codeunit 5610 - Calculate Depreciation on function Calculate .

Codeunit 5610 - Calculate Depreciation - Function FUNCTIONCalculate AME:

```
[External] Calculate(VAR DeprAmount : Decimal;VAR Custom1Amount : Decimal;VAR NumberOfDays : Integer;VAR Custom1NumberOfDays : Integer;FANo : Code[20];DeprBookCode : Code[10];UntilDate : Date;EntryAmounts : ARRAY [4] OF Decimal;DateFromProjection : Date;DaysInPeriod : Integer)
DeprAmount := 0;
Custom1Amount := 0;
NumberOfDays := 0;
Custom1NumberOfDays := 0;
IF NOT DeprBook.GET(DeprBookCode) THEN
  EXIT;
IF NOT FADeprBook.GET(FANo,DeprBookCode) THEN
  EXIT;

//+++TRASER
OnBeforeCheckDeprDaysInFiscalYear(FADeprBook, IsHandled);
IF IsHandled THEN
  EXIT;
//---TRASER

CheckDeprDaysInFiscalYear(DateFromProjection = 0D,UntilDate);

IF DeprBook."Use Custom 1 Depreciation" AND
   (FADeprBook."Depr. Ending Date (Custom 1)" > 0D)
THEN
  CalculateCustom1Depr.Calculate(
    DeprAmount,Custom1Amount,NumberOfDays,
    Custom1NumberOfDays,FANo,DeprBookCode,UntilDate,
    EntryAmounts,DateFromProjection,DaysInPeriod)
ELSE
  CalculateNormalDepr.Calculate(
    DeprAmount,NumberOfDays,FANo,DeprBookCode,UntilDate,
    EntryAmounts,DateFromProjection,DaysInPeriod);
```

Publisher definition:

```
LOCAL [IntegrationEvent] OnBeforeCheckDeprDaysInFiscalYear(VAR FADeprBook : Record "FA Depreciation Book";VAR IsHandled : Boolean)
```

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
