### ISSUE TITLE
[Event Request] Table 5902 - CheckItemAvailable

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5445]
Hi, we need following event in function CheckItemAvailable in table 5902 on before check is Nonstock, or before all checks..
![image](https://user-images.githubusercontent.com/54843470/71721559-cf9c0e00-2e25-11ea-9308-a4d8f68c65cf.png)

Publisher:
```
local procedure OnCheckItemAvailable(var ServiceLine: Record "Service Line"; CalledByFieldNo: Integer;var IsHandled: Boolean)
```

**Comment by AlexanderYakunin** [comment]
Can you explain which condition you need to track for exit? Why you want to insert event in this place?

**Comment by NemanjaKutlesic** [comment]
1. We have modification to validate "Needed by Date" with WORKDATE for some conditions
2. We have modification to not exit for Nonstock Item in some cases - so we need to skip that check in this way, i think due to number of modifications it is good to have event like this
3. In some cases we want to hide Notification
4. We have a plenty of modifications

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
