### ISSUE TITLE
[Event Request] Codeunit 5920 - ServItemManagement - Function InitNewServItemComponent - Event AdditionalInitOfNewServItemComponent

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#5446]
Hey,
we would like a event AdditionalInitOfNewServItemComponentin Codeunit 5920 - ServItemManagement on function InitNewServItemComponent .

Codeunit 5920 - ServItemManagement - Function InitNewServItemComponent :

```
LOCAL InitNewServItemComponent(VAR NewServItemComponent : Record "Service Item Component";ServiceLine : Record "Service Line";NextLineNo : Integer;PostingDate : Date)
WITH NewServItemComponent DO BEGIN
  INIT;
  "Parent Service Item No." := ServiceLine."Service Item No.";
  "Line No." := NextLineNo;
  Active := TRUE;
  "No." := ServiceLine."No.";
  Type := Type::Item;
  "Date Installed" := PostingDate;
  Description := ServiceLine.Description;
  "Description 2" := ServiceLine."Description 2";
  "Variant Code" := ServiceLine."Variant Code";
  "Service Order No." := ServiceLine."Document No.";
  "Last Date Modified" := TODAY;
  
   AdditionalInitOfNewServItemComponent(NewServItemComponent); // NEW 
END;
```

Publisher definition:

```
LOCAL [IntegrationEvent] AdditionalInitOfNewServItemComponent(VAR NewServItemComponent : Record "Service Item Component")
```

Thanks in addition.
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
