### ISSUE TITLE
[Event Request] Codeunit 84 - OnRun

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5447]
Hi, we need following event OnRun Codeunit 84, implementation:
![image](https://user-images.githubusercontent.com/54843470/71725083-f9a7fd00-2e32-11ea-975b-9a6336f606ef.png)

**Comment by AlexanderYakunin** [comment]
We already have this event
        OnAfterCreateSalesOrder(SalesOrderHeader, SkipMessage);
        if not SkipMessage then
            Message(OrderCreatedMsg, SalesOrderHeader."No.", "No.");

**Comment by NemanjaKutlesic** [comment]
**It will be shipped in future?**
I'm checking it in Base App verison 15.2.39558.0 and i cannot see it
![image](https://user-images.githubusercontent.com/54843470/72347944-84adb080-36d9-11ea-8110-cc0c203a3f0a.png)

**Comment by NemanjaKutlesic** [comment]
It is shipped in 16.x version. So i will close this
