### ISSUE TITLE
[Event Request] Codeunit 80 - PostItemChargePerShpt, PostItemChargePerRetRcpt

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5448]
1. In #2730 event OnPostItemChargePerShptOnBeforeTestJobNo is requested, we would need also in that event to have SalesLine as variable(with var)

So new implementation would be:
```
OnPostItemChargePerShptOnBeforeTestJobNo(SalesShptLine, SalesLine, IsHandled);
```
Publisher:
```
local procedure OnPostItemChargePerShptOnBeforeTestJobNo(SalesShipmentLine: Record "Sales Shipment Line"; var SalesLine: Record "Sales Line"; var SkipTestJobNo: Boolean)
```
2. Exactly the same thing in PostItemChargePerRetRcpt with event OnPostItemChargePerRetRcptOnBeforeTestFieldJobNo

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
