### ISSUE TITLE
[Event Request] Codeunit 80 - UpdateAssosOrderPostingNos

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5449]
Hi, we would need 2 new events onBefore and onAfter ReleasePurchaseHeader in function UpdateAssosOrderPostingNos in codeunit 80

![image](https://user-images.githubusercontent.com/54843470/71726106-5e188b80-2e36-11ea-8b6b-f35f9025f872.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
