### ISSUE TITLE
[Event Request] Codeunit 80 - UpdateLastPostingNos

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5450]
Hi, we would need new event in function UpdateLastPostingNos in codeunit 80, like it is on picture: 
![image](https://user-images.githubusercontent.com/54843470/71726263-d5e6b600-2e36-11ea-8ccb-8cb0797279b3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
