### ISSUE TITLE
[Event Request] Codeunit 80 - SaveInvoiceSpecification

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5451]
Hi, we would need new event in following place:
![image](https://user-images.githubusercontent.com/54843470/71726569-c6b43800-2e37-11ea-8d18-6cad34c8e9f8.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
