### ISSUE TITLE
[Event Request] Codeunit 80 - OnPostATOOnBeforePostedATOLinkInsert v2

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5452]
Like it is extended in #3826 , we also need to extend this event.
Event should be:

```
LOCAL [IntegrationEvent] OnPostATOOnBeforePostedATOLinkInsert(VAR PostedATOLink : Record "Posted Assemble-to-Order Link";VAR AsmHeader : Record "Assembly Header"; SalesLine: Record "Sales Line");
```
So we need VAR for AsmHeader and SalesLine

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
