### ISSUE TITLE
Codeunit 905 Assembly Line Management - OnAfterTransferBOMComponent

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#5458]
Hi,

Please add variable AshHeader to Publisher OnAfterTransferBOMComponent in Codeunit 905 Assembly Line Management.

            if "Location Code" <> '' then
                if AssemblyLine.IsInventoriableItem then
                    AssemblyLine.Validate("Location Code", "Location Code");

            OnAfterTransferBOMComponent(AssemblyLine, BOMComponent, AsmHeader);   // AsmHeader Added

            AssemblyLine.Modify(true);

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferBOMComponent(var AssemblyLine: Record "Assembly Line"; BOMComponent: Record "BOM Component"; AssemblyHeader: Record "Assembly Header") //Assembly Header Added
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
