### ISSUE TITLE
[Event Request] Codeunit 5940 Function CalcContractLineAmount

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#5462]
Requesting to add below event. thanks

AmountCalculated := 0;
AmountCalculated :=
  AnnualAmount / 12 * NoOfMonthsAndMPartsInPeriod(PeriodStarts,PeriodEnds);

//>>>New Code
OnAfterCalcContractLineAmount(AnnualAmount,PeriodStarts,PeriodEnds,AmountCalculated);
**//<<<New Code

Event
LOCAL [IntegrationEvent] OnAfterCalcContractLineAmount(AnnualAmount : Decimal;PeriodStarts : Date;PeriodEnds : Date;VAR AmountCalculated : Decimal)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 15.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
