### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeInsertGLEntryBuffer event

### ISSUE THREAD

**Issue by adesz444** [microsoft/ALAppExtensions#5463]
Hi

Please add the `TotalAmount` and `TotalAddCurrAmount` global variables as var to the OnBeforeInsertGLEntryBuffer parameter list. 

Original: 
`OnBeforeInsertGLEntryBuffer(TempGLEntryBuf,GenJnlLine,BalanceCheckAmount,BalanceCheckAmount2,BalanceCheckAddCurrAmount,BalanceCheckAddCurrAmount2,NextEntryNo);`

New:
`OnBeforeInsertGLEntryBuffer(TempGLEntryBuf,GenJnlLine,BalanceCheckAmount,BalanceCheckAmount2,BalanceCheckAddCurrAmount,BalanceCheckAddCurrAmount2,TotalAmount,TotalAddCurrAmount,NextEntryNo);`

There are some cases when we have to insert new GL Entries manually here, but we cannot handle residuals since all entries are temporary at this stage and these two global variables are used in `HandleAddCurrResidualGLEntry` function. 

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
