### ISSUE TITLE
[Event Request] Codeunit 80 and 90 OnUpdateAssocOrderOnAfterModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5464]
we Need two new Event trigger in codeunit 80 and 90:

Codeunit 80:
LOCAL UpdateAssocOrder(VAR TempDropShptPostBuffer : TEMPORARY Record "Drop Shpt. Post. Buffer")
TempDropShptPostBuffer.RESET;
IF TempDropShptPostBuffer.ISEMPTY THEN
  EXIT;
CLEAR(PurchOrderHeader);
TempDropShptPostBuffer.FINDSET;
REPEAT
  IF PurchOrderHeader."No." <> TempDropShptPostBuffer."Order No." THEN BEGIN
    PurchOrderHeader.GET(PurchOrderHeader."Document Type"::Order,TempDropShptPostBuffer."Order No.");
    PurchOrderHeader."Last Receiving No." := PurchOrderHeader."Receiving No.";
    PurchOrderHeader."Receiving No." := '';
    PurchOrderHeader.MODIFY;
    //+++++++++++++++++++++++++++++++++++
    OnUpdateAssocOrderOnAfterModifyPurchHeader(VAR PurchOrderHeader);
    //-----------------------------------
    ReservePurchLine.UpdateItemTrackingAfterPosting(PurchOrderHeader);
  END;

Codeunit 90:
LOCAL UpdateAssocOrder(VAR TempDropShptPostBuffer : TEMPORARY Record "Drop Shpt. Post. Buffer")
TempDropShptPostBuffer.RESET;
IF TempDropShptPostBuffer.ISEMPTY THEN
  EXIT;
SalesSetup.GET;
IF TempDropShptPostBuffer.FINDSET THEN BEGIN
  REPEAT
    SalesOrderHeader.GET(
      SalesOrderHeader."Document Type"::Order,
      TempDropShptPostBuffer."Order No.");
    SalesOrderHeader."Last Shipping No." := SalesOrderHeader."Shipping No.";
    SalesOrderHeader."Shipping No." := '';
    SalesOrderHeader.MODIFY;
    //+++++++++++++++++++++++++++++++++++
    OnUpdateAssocOrderOnAfterModifySalesHeader(VAR SalesOrderHeader);
    //-----------------------------------
    ReserveSalesLine.UpdateItemTrackingAfterPosting(SalesOrderHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
