### ISSUE TITLE
[Event Request] Report 11511 - OnBeforeSetTargetItemNo

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#5465]
Please add a new integration event **OnBeforeSetTargetItemNo** in **Report 11511**.

```
    local procedure SetTargetItemNo(NewItemNo: Code[20]; var TargetItemNo: Code[20]; var TargetNoSeries: Code[20])
    begin
+       OnBeforeSetTargetItemNo(NewNoSeries, NewItemNo, SourceItem);
        [...]
```

New integration event
```
[IntegrationEvent(false, false)]
local procedure OnBeforeSetTargetItemNo(var NewNoSeries: Code[20]; NewItemNo: Code[20]; SourceItem: Record Item);
begin
end;
```

**Comment by AlexanderYakunin** [comment]
This DACH feature have been replaced by W1 page 730 Copy Item due to better extensiblit capabilities for pages after multiple partner requests. Can you please convert to using this page instead. Old report 11511 is being deprecated.
