### ISSUE TITLE
Event Request: Codeunit 80 + 90 - OnBeforePostLines weirdness

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/ALAppExtensions#547]
In Codeunit 80 and Codeunit 90 we have the events `OnBeforePostLines`. These events pass `PurchLine` (and `SalesLine` respectively) by VAR.

The problem is, that they point to the *real* instance of the tables, while the codeunits itself operate mainly on a temporary copy. This temporary copy however is created (via `FillTempLines`) **before** `OnBeforePostLines` is called.

Now if anyone modifies the document lines in those events ...
- Problem 1: the posting codeunits will obviously not 'see' these changes.
- Problem 2: further down the posting process, `ModifyTempLine` is called which writes changes on the temporary copy back to the *real* document line and obviosuly errors out, because timestamps no longer match.

Maybe this event is not meant to modify document lines? In which case it is weird that they are passed at all. Why do so? And why do so by `VAR`? This is why I consider it a bug. So I'd suggest to pass the temporary instance `TempPurchLine` (and `TempSalesLine` respectively) instead of the real one.

**Comment by JesperSchulz** [comment]
A fix for this went in mid December. Somehow, our automation did not report that back to this issue. Apologies! I hope you find everything is as requested. If not, please open a new issue, as we don't revisit closed issues. Thanks for reporting!
