### ISSUE TITLE
[Event Request] Report 790 - OnItemOnPreDataItemOnBeforeGetItemJnlTemplate

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#5472]
Please add a new integration event **OnItemOnPreDataItemOnBeforeGetItemJnlTemplate** in **Report 790**.

```
           [...]
           trigger OnPreDataItem()
            var
                ItemJnlTemplate: Record "Item Journal Template";
                ItemJnlBatch: Record "Item Journal Batch";
            begin
+               OnItemOnPreDataItemOnBeforeGetItemJnlTemplate(ItemJnlTemplate, ItemJnlBatch);
                if PostingDate = 0D then
                    Error(Text000);
                [...]
```

New integration event
```
[IntegrationEvent(false, false)]
local procedure OnItemOnPreDataItemOnBeforeGetItemJnlTemplate(var ItemJournalTemplate: Record "Item Journal Template"; var ItemJournalBatch: Record "Item Journal Batch")
begin
end;
```

**Comment by AlexanderYakunin** [comment]
Does it make any sense here? If you get them in this event, they will be overwritten by next statements
                ItemJnlTemplate.Get(ItemJnlLine."Journal Template Name");
                ItemJnlBatch.Get(ItemJnlLine."Journal Template Name", ItemJnlLine."Journal Batch Name");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
