### ISSUE TITLE
[Extensibility Bug] IntrastatChecklistDE.Report.al - OldTariffNo

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#5475]
The OldTariffNo is declared as Code[10]. In the trigger OnAfterGetRecord() of the dataitem("Intrastat Jnl. Line"; "Intrastat Jnl. Line") the "Tariff No." of type Code[20] is being assigned to Code[10]. Therefore the OldTariffNo should be extended to Code[20].

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
