### ISSUE TITLE
Event request : OnAfterSetPaymentLine

### ISSUE THREAD

**Issue by stijn9830** [microsoft/ALAppExtensions#5476]
A customer wants to choose the vendor bank account on the purchase invoice. This should can be the preferred bank account, but they can change it manually.

Can there be an event after 'onvalidate account no' on T2000001
or afterSetpaymLine on R2000019 ?

thx

![image](https://user-images.githubusercontent.com/56073675/71877662-10e43480-312a-11ea-895f-e08a6d406bdc.png)

**Comment by AlexanderYakunin** [comment]
Please define event specification with parameters (add VAR in needed).

**Comment by AlexanderYakunin** [comment]
Closing requests ad no information have been provided. Please create new request with required information.
