### ISSUE TITLE
[Event Request] Codeunit 9025 "Small Business Report Catalog" OnBeforeRunAgedAccountsPayableReport / OnBeforeRunAgedAccountsReceivableReport

### ISSUE THREAD

**Issue by wbor-nvt** [microsoft/ALAppExtensions#5479]
Hello,

Please add these Events to codeunit 9025 "Small Business Report Catalog" to allow substitution of the reports

`    
    [IntegrationEvent(false,false)]
    local procedure OnBeforeRunAgedAccountsReceivableReport(UseRequestPage: Boolean ; var Handled : Boolean)
    begin
    end;`
`
[IntegrationEvent(false,false)]
    local procedure OnBeforeRunAgedAccountsPayableReport(UseRequestPage: Boolean ; var Handled : Boolean)
    begin
    end;`

![image](https://user-images.githubusercontent.com/53901977/71900460-25422480-315e-11ea-8f9f-07af500f7280.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
