### ISSUE TITLE
[Event Request] Codeunit 453 Job Queue - Enqueue

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#5480]
Can we get an event `OnBeforeEnqueueJobQueueEntry` in Codeunit 453 "Job Queue - Enqueue" to add our own logic before the job is enqueued?

```
local procedure EnqueueJobQueueEntry(var JobQueueEntry: Record "Job Queue Entry")
    var
        SavedStatus: Option;
    begin
        OnBeforeEnqueueJobQueueEntry(JobQueueEntry); //NEW
        with JobQueueEntry do begin
            SavedStatus := Status;
            InitEntryForSchedulerWithDelayInSec(JobQueueEntry, 1);
            if IsNullGuid(ID) then
                Insert(true)
            else begin
                if CanScheduleTask(JobQueueEntry) then
                    CancelTask; // clears "System Task ID"
                Modify;
            end;

...
[IntegrationEvent(false, false)]
local procedure OnBeforeEnqueueJobQueueEntry(var JobQueueEntry : Record "Job Queue Entry")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
