### ISSUE TITLE
Report 10156 Purchase Order Status Item Description

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#5481]
Item Description field has been expanded to 100 characters.  It seems that the report 10156 Purchase Order Status could expand the print size for it.  Also, Item No. field on the same report could be expanded if possible.  Thanks very much.

![image](https://user-images.githubusercontent.com/49729094/71905810-e351b800-3136-11ea-80b4-fd91e19c1e64.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
