### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134327 "ERM Purchase Order"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5482]
[Event Request] Application “Tests-ERM”, Codeunit 134327 "ERM Purchase Order"
![pic1](https://user-images.githubusercontent.com/45795262/71907205-d4d1c380-316b-11ea-8a2a-6b6d42204390.png)

Could you please insert the Initialize procedure or an OnTestInitialize Event at the beginning of the procedures CreatePurchaseLineWithJobTaskFCY? 
![pic2](https://user-images.githubusercontent.com/45795262/71907213-d7ccb400-316b-11ea-8079-e18afc0cfa52.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
