### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134266 "Payment Recon. E2E Tests 2"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5483]
[Event Request] Application “Tests-ERM”, Codeunit 134266 "Payment Recon. E2E Tests 2"
![pic1](https://user-images.githubusercontent.com/45795262/71907414-44e04980-316c-11ea-9a66-c06a4ea2952c.png)

Could you please insert an OnTestInitialize Event at the beginning of the procedures Initialize? 
![pic2](https://user-images.githubusercontent.com/45795262/71907416-4742a380-316c-11ea-85ad-d0216961986e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
