### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134265 "Payment Recon. E2E Tests 1"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5484]
[Event Request] Application “Tests-ERM”, Codeunit 134265 "Payment Recon. E2E Tests 1"
![pic1](https://user-images.githubusercontent.com/45795262/71907529-84a73100-316c-11ea-88fa-da56cbab6ae0.png)

Could you please insert an OnTestInitialize Event at the beginning of the procedures Initialize? 
![pic2](https://user-images.githubusercontent.com/45795262/71907540-8a047b80-316c-11ea-91b4-6d5aae78f631.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
