### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134154 "ERM Intercompany III"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5485]
[Event Request] Application “Tests-ERM”, Codeunit 134154 "ERM Intercompany III"
![pic1](https://user-images.githubusercontent.com/45795262/71907662-c20bbe80-316c-11ea-8542-7fef5e66891c.png)

Could you please insert an OnTestInitialize Event at the beginning of the procedures Initialize? 
![pic2](https://user-images.githubusercontent.com/45795262/71907666-c637dc00-316c-11ea-966d-a48bd3d940ab.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
