### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134099 "Purchase Documents"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5486]
[Event Request] Application “Tests-ERM”, Codeunit 134099 "Purchase Documents"
![pic1](https://user-images.githubusercontent.com/45795262/71907797-0d25d180-316d-11ea-9c70-76b54c72a4fe.png)

Could you please insert an OnTestInitialize Event at the beginning of the procedures Initialize? 
![pic2](https://user-images.githubusercontent.com/45795262/71907824-1adb5700-316d-11ea-88be-711eda1b53b5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
