### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134098 "ERM Invoice Disc. Distribution"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5487]
[Event Request] Application “Tests-ERM”, Codeunit 134098 "ERM Invoice Disc. Distribution"
![pic1](https://user-images.githubusercontent.com/45795262/71907905-4cecb900-316d-11ea-9424-eaa307b172ba.png)

Could you please insert an OnTestInitialize Event at the beginning of the procedures Initialize? 
![pic2](https://user-images.githubusercontent.com/45795262/71907912-4fe7a980-316d-11ea-92ee-ef6ada2550fd.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
