### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134091 "ERM Additional Currency II"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5488]
[Event Request] Application “Tests-ERM”, Codeunit 134091 "ERM Additional Currency II"
![pic1](https://user-images.githubusercontent.com/45795262/71908007-8291a200-316d-11ea-9130-e1cd36052daf.png)

Could you please insert an OnTestInitialize Event at the beginning of the procedures Initialize? 
![pic2](https://user-images.githubusercontent.com/45795262/71908016-858c9280-316d-11ea-8b55-64f1771895b7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
