### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134071 "Test Suppress Commit in Post

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5489]
[Event Request] Application “Tests-ERM”, Codeunit 134071 "Test Suppress Commit in Post
![pic1](https://user-images.githubusercontent.com/45795262/71908223-e2884880-316d-11ea-96e2-c3a146bfa847.png)

Could you please insert an OnTestInitialize Event at the beginning of the following procedures? 
•	TestPostSalesDocumentCommit
•	TestPostSalesDocumentNoCommit
•	TestPostSalesDocumentPreview
•	TestPostSalesDocumentTwice
•	TestPostPurchaseDocumentTwice
•	TestPostSalesPrepaymentInvoiceCommit
•	TestPostSalesPrepaymentInvoiceNoCommit
•	TestCarryOutReqWkshCommit
•	TestCarryOutReqWkshNoCommit
•	TestPostOneOfEachCommit
•	TestPostOneOfEachNoCommit

![pic2](https://user-images.githubusercontent.com/45795262/71908232-e7e59300-316d-11ea-9d7f-128ef0317205.png)

![pic3](https://user-images.githubusercontent.com/45795262/71908249-ecaa4700-316d-11ea-8d41-0e71ca0273a5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
