### ISSUE TITLE
[Event Request] Codeunit 5063 OnRestoreSalesLinesOnAfterValidateQuantity

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5490]
we nees a new Event trigger OnRestoreSalesLinesOnAfterValidateQuantity in codeunit 5063 ArchiveManagement:

LOCAL RestoreSalesLines(VAR SalesHeaderArchive : Record "Sales Header Archive";SalesHeader : Record "Sales Header")
RestoreSalesLineComments(SalesHeaderArchive,SalesHeader);

SalesLineArchive.SETRANGE("Document Type",SalesHeaderArchive."Document Type");
SalesLineArchive.SETRANGE("Document No.",SalesHeaderArchive."No.");
SalesLineArchive.SETRANGE("Doc. No. Occurrence",SalesHeaderArchive."Doc. No. Occurrence");
SalesLineArchive.SETRANGE("Version No.",SalesHeaderArchive."Version No.");
IF SalesLineArchive.FINDSET THEN
  REPEAT
    WITH SalesLine DO BEGIN
      INIT;
      TRANSFERFIELDS(SalesLineArchive);
      INSERT(TRUE);
      OnRestoreSalesLinesOnAfterSalesLineInsert(SalesLine,SalesLineArchive);
      IF Type <> Type::" " THEN BEGIN
        VALIDATE("No.");
        IF SalesLineArchive."Variant Code" <> '' THEN
          VALIDATE("Variant Code",SalesLineArchive."Variant Code");
        IF SalesLineArchive."Unit of Measure Code" <> '' THEN
          VALIDATE("Unit of Measure Code",SalesLineArchive."Unit of Measure Code");
        VALIDATE("Location Code",SalesLineArchive."Location Code");
        IF Quantity <> 0 THEN
          VALIDATE(Quantity,SalesLineArchive.Quantity);
        //+++++++++++++++++++++++++++++++++++++++++++
        OnRestoreSalesLinesOnAfterValidateQuantity(VAR Salesline, SalesLineArchive);
        //-------------------------------------------
        VALIDATE("Unit Price",SalesLineArchive."Unit Price");
        VALIDATE("Unit Cost (LCY)",SalesLineArchive."Unit Cost (LCY)");
        VALIDATE("Line Discount %",SalesLineArchive."Line Discount %");
        IF SalesLineArchive."Inv. Discount Amount" <> 0 THEN
          VALIDATE("Inv. Discount Amount",SalesLineArchive."Inv. Discount Amount");
        IF Amount <> SalesLineArchive.Amount THEN
          VALIDATE(Amount,SalesLineArchive.Amount);
        VALIDATE(Description,SalesLineArchive.Description);
      END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
