### ISSUE TITLE
[Event Request] Codeunit 427 OnCreateSalesLinesOnAfterLineNo and OnCreatePurchLinesOnAfterLineNo

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5492]
we Need 2 new Event trigger OnCreateSalesLinesOnAfterLineNo and OnCreatePurchLinesOnAfterLineNo in codeunit 427 ICInboxOutboxMgt:

[External] CreateSalesLines(SalesHeader : Record "Sales Header";ICInboxSalesLine : Record "IC Inbox Sales Line")
WITH ICInboxSalesLine DO BEGIN
  SalesLine.INIT;
  SalesLine.TRANSFERFIELDS(ICInboxSalesLine);
  SalesLine."Document Type" := SalesHeader."Document Type";
  SalesLine."Document No." := SalesHeader."No.";
  SalesLine."Line No." := "Line No.";
  //+++++++++++++++++++++++++++++++++++++++++
  OnCreateSalesLinesOnAfterLineNo(VAR SalesLine,ICInboxSalesLine);
  //-----------------------------------------
  CASE "IC Partner Ref. Type" OF

[External] CreatePurchLines(PurchHeader : Record "Purchase Header";ICInboxPurchLine : Record "IC Inbox Purchase Line")
WITH ICInboxPurchLine DO BEGIN
  PurchLine.INIT;
  PurchLine.TRANSFERFIELDS(ICInboxPurchLine);
  PurchLine."Document Type" := PurchHeader."Document Type";
  PurchLine."Document No." := PurchHeader."No.";
  PurchLine."Line No." := "Line No.";
  PurchLine.INSERT(TRUE);
  PurchLine."Receipt No." := '';
  PurchLine."Return Shipment No." := '';
  //+++++++++++++++++++++++++++++++++++++++++
  OnCreatePurchLinesOnAfterInsert(VAR PurchLine,ICInboxPurchLine);
  //-----------------------------------------

**Comment by AlexanderYakunin** [comment]
I have a question, do you have specific reason to add this event just after Line No. assignment? Looks like next code until Insert statement is not dependent of Line No., so we can add generic OnBeforeInsert event to manage your case and many others?

**Comment by GuntherGebauer** [comment]
we want to call our own function on VAR Salesline or VAR Purchaseline in TableExtension or our own triggers which are necessary before quantity is validated.
Because with Salesline it is first insert and then modify, but with Purchaseline it is codeed only Validates and later insert without modify - and we Need the same trigger at the same coding Position, we wanted to have this trigger OnAfterLineNo.

If you would Change Sales according to Purchase to Code it Salesline.Insert and later Salesline.validate(Quantity) and Salesline.modify - in this case we could easily live with the trigger OnCreateSalesLineOnAfterInsert and OnCreatePurchLineOnAfterInsert

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
