### ISSUE TITLE
[Event Request] Codeunit 90 - functions: UpdatePostingNos - event: OnBeforeFindVendorLedgerEntries

### ISSUE THREAD

**Issue by ClaudioNuBe** [microsoft/ALAppExtensions#5496]
Hello, 
we would like a event OnBeforeFindVendorLedgerEntries in Codeunit 90 - "Purch.-Post" on function UpdatePostingNos.

Codeunit 90 - "Purch.-Post" on function UpdatePostingNos:
```
IF PurchSetup."Ext. Doc. No. Mandatory" OR (GenJnlLineExtDocNo <> '') THEN BEGIN
  VendLedgEntry.RESET;
  VendLedgEntry.SETCURRENTKEY("External Document No.");
  IF ("Document Type" = "Document Type"::Invoice) OR ("Document Type" = "Document Type"::Order) THEN BEGIN
    TESTFIELD("Vendor Invoice No.");
    VendLedgEntry.SETRANGE("Document Type","Document Type"::Invoice);
    VendLedgEntry.SETRANGE("External Document No.","Vendor Invoice No.");
  END ELSE
    IF ("Document Type" = "Document Type"::"Credit Memo") OR ("Document Type" = "Document Type"::"Return Order") THEN BEGIN
      TESTFIELD("Vendor Cr. Memo No.");
      VendLedgEntry.SETRANGE("Document Type","Document Type"::"Credit Memo");
      VendLedgEntry.SETRANGE("External Document No.","Vendor Cr. Memo No.");
    END;
  VendLedgEntry.SETRANGE("Vendor No.","Pay-to Vendor No.");
  //****************New Event********************************
  OnBeforeFindVendorLedgerEntries(PurchHeader,VendLedgEntry);
  //*********************************************************
  IF VendLedgEntry.FINDFIRST THEN
    ERROR(PurchaseAlreadyExistsErr,VendLedgEntry."Document Type",GenJnlLineExtDocNo);
END;
```
Publisher definition:
```
LOCAL [IntegrationEvent] OnBeforeFindVendorLedgerEntries(VAR PurchaseHeader : Record "Purchase Header";VAR VendorLedgerEntry : Record "Vendor Ledger Entry")
```
We need an event like this to filter "Vendor Ledger Entry" by year, because often "Vendor Invoice No." is unique only by year

Thank You
  Claudio

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
