### ISSUE TITLE
[Event Request] Codeunit 5944 SignServContractDoc

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#5503]
Requesting 1 new event publisher on codeunit 5944 SignServContractDoc

### **Event - OnAfterSetStartingDateForNewLines**
**Event**
`LOCAL [IntegrationEvent] OnAfterSetStartingDateForNewLines(ServiceContractHeader : Record "Service Contract Header";VAR StartingDate : Date)`

**Code**
```
[External] AddendumToContract(ServContractHeader : Record "Service Contract Header")
OnBeforeAddendumToContract(ServContractHeader);
...
ServContractLine.RESET;
ServContractLine.SETCURRENTKEY("Contract Type","Contract No.",Credited,"New Line");
ServContractLine.SETRANGE("Contract Type",FromServContractHeader."Contract Type");
ServContractLine.SETRANGE("Contract No.",FromServContractHeader."Contract No.");
ServContractLine.SETRANGE("New Line",TRUE);
StartingDate := WORKDATE;

>>> New Code
OnAfterSetStartingDateForNewLines(FromServContractHeader,StartingDate);
<<< New Code

IF ServContractLine.FINDSET THEN
...
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
