### ISSUE TITLE
[Event Request] Report 99001015 OnBeforeInsertReqWkshLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5506]
we Need as additional parameter ProdOrderLine in the existing Event OnBeforeInsertReqWkshLine, as the trigger is fired for each ProdOrderLine calling InsertReqWkshLine:

old:
LOCAL [IntegrationEvent] OnBeforeInsertReqWkshLine(VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line";VAR WorkCenter : Record "Work Center";VAR ReqLine : Record "Requisition Line";VAR IsHandled : Boolean)

new:
LOCAL [IntegrationEvent] OnBeforeInsertReqWkshLine(VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line";VAR WorkCenter : Record "Work Center";VAR ReqLine : Record "Requisition Line";VAR IsHandled : Boolean; ProdOrderLine : Record "Prod. Order Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
