### ISSUE TITLE
table 5901 make 'CheckTempDateErrorDate' external 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#5507]
Please make 'CheckTempDateErrorDate' external 
![image](https://user-images.githubusercontent.com/49729094/72002856-3d757a80-3216-11ea-8fb6-9b47d342b3b9.png)

Thanks very much.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
