### ISSUE TITLE
Redesign Publisher in ReWshMakeOrder.Codeunit.al

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#5508]
procedure InsertPurchOrderLine(var ReqLine2: Record "Requisition Line"; var PurchOrderHeader: Record "Purchase Header")
    var
        PurchOrderLine2: Record "Purchase Line";
        AddOnIntegrMgt: Codeunit AddOnIntegrManagement;
        DimensionSetIDArr: array[10] of Integer;
    begin
        **OnBeforeInsertPurchOrderLine(ReqLine2, PurchOrderHeader, NextLineNo);**

        with ReqLine2 do begin
            if ("No." = '') or ("Vendor No." = '') or (Quantity = 0) then
                exit;

            if CheckInsertFinalizePurchaseOrderHeader(ReqLine2, PurchOrderHeader, true) then begin
                InsertHeader(ReqLine2);
                LineCount := 0;
                NextLineNo := 0;
                PrevPurchCode := "Purchasing Code";
                PrevShipToCode := "Ship-to Code";
                PrevLocationCode := "Location Code";
            end;
**<==> NEW
            OnAfterCheckInsertFinalizeBeforeInsertPurchOrderLine(ReqLine2, PurchOrderHeader, NextLineNo);
NEW <==>**
            LineCount := LineCount + 1;
            if not PlanningResiliency then
                Window.Update(4, LineCount);

            TestField("Currency Code", PurchOrderHeader."Currency Code");

            InitPurchOrderLine(PurchOrderLine, PurchOrderHeader, ReqLine2);

==================================
What you can see here is the, in my opinion, wrongly placed publisher OnBeforeInsertPurchOrderLine. The problem is that the PurchaseOrder header is passed here, but it is not filled in the first pass in the code unit. Only after this the function CheckInsertFinalize is started, which detects in the first run that the PurchaseOrderHeader is not available and can be used in the function InsertHeader(ReqLine2) .
If, for example, you want to create an additional information line when creating the purchase order, there is no reference to the purchasing header created later. 
An additional Publisher could also help, which you call up after the CheckFinalize function. However, this should contain the same parameters as the first publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
