### ISSUE TITLE
[Function Expose] Codeunit 1001 Function PostPlanningLine

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5509]
Requesting the following function to be external:

Codeunit 1001:
**LOCAL PostPlanningLine(JobPlanningLine : Record "Job Planning Line")**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
