### ISSUE TITLE
[Event Request] Report 1003 - Post Invt. Cost to G/L - Test - OnAfterOnPreDataItem

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5510]
Hi AL-Team,

can you please add the following Publisher to PostValueEntryToGL OnPreDataItem?
```
trigger OnPreDataItem()
                begin
                    InvtPost.SetRunOnlyCheck(false, true, true);
                    TempCapValueEntry.DeleteAll;
                    // NEW >>>>
                    OnAfterOnPreDataItem(PostValueEntryToGL, CompanyName)
                    // NEW <<<<
                end;
```

   ```
 [IntegrationEvent(false, false)]
    local procedure OnAfterOnPreDataItem(var PostValueEntryToGL: Record "Post Value Entry to G/L"; CompanyName: Text)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
