### ISSUE TITLE
[Event Request] Report 1003 - Post Invt. Cost to G/L - Test - OnBeforePreReport

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5511]
Hi AL-Team,

can you please add the following Publisher to OnPreReport?
```
trigger OnPreReport()
    begin
        // NEW >>>>
        OnBeforePreReport(PostValueEntryToGL, ItemValueEntry);
        // NEW <<<<

        ValueEntryFilter := PostValueEntryToGL.GetFilters;
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnBeforePreReport(var PostValueEntryToGL: Record "Post Value Entry to G/L"; var ItemValueEntry: Record "Value Entry")
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
