### ISSUE TITLE
[Event Change] Report 1002 - Post Inventory Cost to G/L - OnBeforePreReport

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5513]
Hi AL-Team,

can you please add the parameter PostValueEntryToGL, ItemValueEntry and Item as var to publisher OnBeforePreReport?

```
    trigger OnPreReport()
    begin
        // NEW >>>>
        // OnBeforePreReport;
        OnBeforePreReport(PostValueEntryToGL, ItemValueEntry, Item);
        // NEW <<<<

        ValueEntryFilter := PostValueEntryToGL.GetFilters;
        InvtSetup.Get;
    end;
```

 ```
[IntegrationEvent(TRUE, false)]
    // NEW >>>>
    local procedure OnBeforePreReport(var PostValueEntryToGL: Record "Post Value Entry to G/L"; var ItemValueEntry: Record "Value Entry"; var Item: Record Item)
    // local procedure OnBeforePreReport()
    // NEW <<<<
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
