### ISSUE TITLE
[Event Request]  Codeunit 1001 - new event publisher OnPostInvoiceContractLineBeforeCheckBillToCustomer

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5514]
Requesting a new publisher event in Codeunit 1001 inside function PostInvoiceContractLine:

![image](https://user-images.githubusercontent.com/28901234/72059957-ef6e7e80-32ca-11ea-8d52-d0a916331e39.png)

**LOCAL [IntegrationEvent] OnPostInvoiceContractLineBeforeCheckBillToCustomer(SalesHeader : Record "Sales Header";VAR SalesLine : Record "Sales Line";VAR JobPlanningLine : Record "Job Planning Line";VAR BillToCustomerChecked : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
