### ISSUE TITLE
Table 36 - CopyShipToCustomerAddressFieldsFromShipToAddr; CopyBillToCustomerAddressFieldsFromCustomer

### ISSUE THREAD

**Issue by isolsona** [microsoft/ALAppExtensions#5515]
Hi Al team,

I would like to access the following functions from the extension object.

//local procedure CopyShipToCustomerAddressFieldsFromShipToAddr(ShipToAddr: Record "Ship-to Address")
procedure CopyShipToCustomerAddressFieldsFromShipToAddr(ShipToAddr: Record "Ship-to Address")

//local procedure CopyBillToCustomerAddressFieldsFromCustomer(var BillToCustomer: Record Customer)
local procedure CopyBillToCustomerAddressFieldsFromCustomer(var BillToCustomer: Record Customer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
