### ISSUE TITLE
[Event Request] Codeunit 1001 - OnValidateRelationshipBeforeCheckLineDiscount

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5516]
Requesting a new publisher event in Codeunit 1001 inside function ValidateRelationship:

![image](https://user-images.githubusercontent.com/28901234/72064315-85a6a280-32d3-11ea-9efc-947142f89fd6.png)

**LOCAL [IntegrationEvent] OnValidateRelationshipBeforeCheckLineDiscount(VAR SalesLine : Record "Sales Line";VAR JobPlanningLine : Record "Job Planning Line";VAR LineDiscountChecked : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
