### ISSUE TITLE
Bug: OnBeforeCustLedgerEntryFind Event in Codeunit 392 Reminder-Make 

### ISSUE THREAD

**Issue by noclogic** [microsoft/ALAppExtensions#5517]
## Problem
Method call `OnBeforeCustLedgerEntryFind(CustLedgEntry, ReminderHeader, Cust);` in Codeunit 392 Reminder-Make has the wrong attribute `ReminderHeader`, it should be `ReminderHeaderReq`.

## Situtation
Variables within the codeunit are set by the method `Set`.
Within the Set method the global variable `ReminderHeaderReq` is set.
Also later in the method `MakeReminder`the global variable `ReminderHeaderReq` is used.

The content of `ReminderHeader` is transfered by assignment to variable `ReminderHeaderReq` in method `Code`.

### Conclusion
`ReminderHeaderReq` is the current variable and should be used, not `ReminderHeader`.

## Solution
Drop variable `ReminderHeader`, include instead variable `ReminderHeaderReq` in method `OnBeforeCustLedgerEntryFind()`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
