### ISSUE TITLE
[Event Request] Table 37 - new event publisher OnCopyFromResourceBeforeCheckResourceBlocked

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5518]
Requesting a new publisher event in Table 37 inside function CopyFromResource:

![image](https://user-images.githubusercontent.com/28901234/72066205-e6d07500-32d7-11ea-8868-d0a73fd05fbe.png)

**LOCAL [IntegrationEvent] OnCopyFromResourceBeCheckResourceBlocked(VAR Resource : Record Resource;VAR ResourceCheckedBlocked : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
