### ISSUE TITLE
[Function Expose] Page 31 Item List - SelectInItemList

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#5520]
We would like to have the ability to extend  the base Item List page with a different procedure that will filter the item records according to a filter passed into the page and then call the SelectInItemList procedure that is currently local on the ItemListPage.

Could you please expose the SelectInItemList procedure so that we don't have to duplicate the code in our extension object?

This is the procedure I'd like exposed:
![image](https://user-images.githubusercontent.com/31968749/72077573-74569980-32c5-11ea-817b-023c1a7b932b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
