### ISSUE TITLE
[Event Request] codeunit 5674 FADimensionManagement - OnBeforeCheckFAAllocDim

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5522]
Could we please have 1 event raised in function CheckFAAllocDim.
CodeExample:

    begin
        // start kvspsa - Event Raiser
        **OnBeforeCheckFAAllocDim(FAAlloc);**
        // stop kvspsa
        if not DimMgt.CheckDimIDComb(DimSetID) then
            Error(
              Text000,
              FAAlloc.TableCaption, FAAlloc.Code, FAAlloc."Allocation Type", FAAlloc."Line No.",
              DimMgt.GetDimCombErr);

        TableID[1] := DimMgt.TypeToTableID1(0);
        No[1] := FAAlloc."Account No.";

Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
