### ISSUE TITLE
[Event Request] Table 81 - CreateTempJobJnlLine 

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5524]
Requesting a new publisher event in Table 81 inside function CreateTempJobJnlLine:

![image](https://user-images.githubusercontent.com/28901234/72080184-3ae95280-32f4-11ea-8011-ca66a612fcf6.png)

**LOCAL [IntegrationEvent] OnCreateTempJobJnlLineBeforeValidateJobNo(VAR TempJobJournalLine : Record "Job Journal Line";GenJournalLine : Record "Gen. Journal Line";xGenJournalLine : Record "Gen. Journal Line";CurrFieldNo : Integer)**

**Comment by AlexanderYakunin** [comment]
Why you cannot use existing OnBeforeCreateTempJobJnlLine event with same set of parameters?

**Comment by dagnybjork** [comment]
Because I need to set values to fields in the record TempJobJnlLine and CLEAR is run after the existing event so it would clear the value I set on TempJobJnlLine.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
