### ISSUE TITLE
[Event Request] Codeunit 7312 - OnBeforeCalcBWPickBin Publisher

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#5525]
Please set IncludeSender to True for the Publisher OnBeforeCalcBWPickBin in the Codeunit 7312 "Create Pick"

````
-     [IntegrationEvent(false, false)]
+     [IntegrationEvent(true, false)]
````

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
