### ISSUE TITLE
[Event Request] Codeunit 212 - OnPostResJnlLineBeforeCheckResBlocked

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5526]
Requesting a new publisher event in Codeunit 212 inside function Code:

![image](https://user-images.githubusercontent.com/28901234/72088855-eb5e5300-3302-11ea-91b6-d2661f677e5e.png)

**LOCAL [IntegrationEvent] OnPostResJnlLineBeforeCheckResBlocked(VAR Resource : Record Resource;VAR ResourceCheckedBlocked : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
