### ISSUE TITLE
Event Request in Codeunit 99000773 - OnBeforeValidateDirectUnitCost

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#5529]
In function Transfer Routing we need a publisher to handle own Direct Cost Calculations

                CostCalcMgt.RoutingCostPerUnit(
                  ProdOrderRoutingLine.Type,
                  ProdOrderRoutingLine."No.",
                  ProdOrderRoutingLine."Direct Unit Cost",
                  ProdOrderRoutingLine."Indirect Cost %",
                  ProdOrderRoutingLine."Overhead Rate",
                  ProdOrderRoutingLine."Unit Cost per",
                  ProdOrderRoutingLine."Unit Cost Calculation");
**==> NEW
                OnBeforeValidateDirectUnitCost(ProdOrderLine, RoutingLine,ProdOrderRoutingLine);
<== NEW**
                ProdOrderRoutingLine.Validate("Direct Unit Cost");
                ProdOrderRoutingLine."Starting Time" := ProdOrderLine."Starting Time"

**Comment by AlexanderYakunin** [comment]
Should you have handled event even before CostCalcMgt.RoutingCostPerUnit?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
