### ISSUE TITLE
[Event Enhancement] Table 77 - OnBeforeSetReportLayout

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/ALAppExtensions#5531]
In table 77, the existing event "OnBeforeSetReportLayout" must be enhanced with a parameter because this information is required.

![image](https://user-images.githubusercontent.com/22373356/72146953-cec32900-339d-11ea-9bcd-38f4f1d2cd5f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
