### ISSUE TITLE
[Event Request] Table 77 - OnAfterPrintDocumentsWithCheckGUIYesNoCommon

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/ALAppExtensions#5532]
In table 77, a new event is required within the function "PrintDocumentsWithCheckGUIYesNoCommon" to intervene in the running process. 

The event should have the following properties:

1. the name should be "OnAfterPrintDocumentsWithCheckGUIYesNoCommon" and it must be called before exiting the function

2. the event must have the following parameters:

| Var |     Name      | DataType | Subtype | Length |
|-----|---------------|----------|---------|--------|
| No  | ReportUsage   | Integer  |         |        |
| No  | RecordVariant | Variant  |         |        |

3. the event should be positioned at the following programme point:
![image](https://user-images.githubusercontent.com/22373356/72147664-59f0ee80-339f-11ea-98c6-ef1bbb7d1ef9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
