### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" procedure CheckWhseItemTrkgSetup

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5533]
Could you please add a publisher in the codeunit 6500 "Item Tracking Management" procedure CheckWhseItemTrkgSetup --> OnAfterCheckWhseItemTrkgSetup

```
procedure CheckWhseItemTrkgSetup(ItemNo: Code[20]; var SNRequired: Boolean; var LNRequired: Boolean; ShowError: Boolean)
    var
        ItemTrackingCode: Record "Item Tracking Code";
        Item: Record Item;
    begin
        SNRequired := false;
        LNRequired := false;
        if Item."No." <> ItemNo then
            Item.Get(ItemNo);
        if Item."Item Tracking Code" <> '' then begin
            if ItemTrackingCode.Code <> Item."Item Tracking Code" then
                ItemTrackingCode.Get(Item."Item Tracking Code");
            SNRequired := ItemTrackingCode."SN Warehouse Tracking";
            LNRequired := ItemTrackingCode."Lot Warehouse Tracking";
            // New Event
            OnAfterCheckWhseItemTrkgSetup(ItemTrackingCode);
            
        end;
        if not (SNRequired or LNRequired) and ShowError then
            Error(Text005, Item.FieldCaption("No."), ItemNo);
    end;
```

```
  [IntegrationEvent(false, false)]
    local procedure OnAfterCheckWhseItemTrkgSetup(var ItemTrackingCode: record "Item Tracking Code")
    begin
    end;         
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
