### ISSUE TITLE
[Request for External] codeunit 5626 "FA General Report" change the scope for function SetAquisitionDate

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5536]
Hi, Can you change the scope of function SetAquisitionDate from OnPrem to Cloud?

codeunit 5626 "FA General Report" 
![image](https://user-images.githubusercontent.com/26144133/72150621-37160880-33a6-11ea-8e2b-1e0a1e34dc32.png)

Thaks a Lot

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
