### ISSUE TITLE
[Event Request] New publisher event in Table 167 - function UpdateCust

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5538]
Requesting a new publisher event in Table 167 in function UpdateCust()

![image](https://user-images.githubusercontent.com/28901234/72154408-780f1c80-33a8-11ea-9ef4-e69c02a274ca.png)

**LOCAL [IntegrationEvent] OnUpdateCustOnBeforeUpdateCurrencyCode(VAR Job : Record Job;xJob : Record Job;Customer : Record Customer;VAR CurrencyCodeIsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
