### ISSUE TITLE
[Request for External] table 12187 "VAT Plafond Period" change the scope for function CalcAmounts

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5542]
Hi, Can you change the scope of function CalcAmounts from OnPrem to Cloud?

table 12187 "VAT Plafond Period"
![image](https://user-images.githubusercontent.com/26144133/72154943-38e5c900-33b2-11ea-8f3d-206385638f58.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
