### ISSUE TITLE
[Event Request] Table 210 - inside OnValidate Work Type Code

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5544]
Requesting a new event in Table 210 to be able to exit validation and control whether "Line Discount %" is validated.

![image](https://user-images.githubusercontent.com/28901234/72159787-0db0a900-33b5-11ea-805e-03af067760f6.png)

**LOCAL [IntegrationEvent] OnBeforeValidateWorkTypeCode(VAR JobJournalLine : Record "Job Journal Line";VAR xJobJournalLine : Record "Job Journal Line";VAR HandleDiscount : Boolean;VAR IsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
