### ISSUE TITLE
requesting [EventRequest] codeunit 6620 “Copy document mgt”,  RecalculatePurchLine [Local] 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5547]
We have requested this event before [4316](https://github.com/microsoft/ALAppExtensions/issues/4316) back in september, but this is not in the current build 15.2 ?

Please add a new publisher event OnBeforeRecalculatePurchLine in Codeunit 6620 on function RecalculatePurchLine and call it in the start of the function

![image](https://user-images.githubusercontent.com/54017538/65486864-e1c0f480-dea5-11e9-8dec-031b50cee262.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![image](https://user-images.githubusercontent.com/54017538/65486866-e7b6d580-dea5-11e9-8d30-c86d530cfb0e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
