### ISSUE TITLE
re requesting [EventRequest] codeunit 7322 “Create Inventory Pick/Movement”, GetSourceDocHeader()[Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#5548]
We requested this event back in august, but we cannot seem ti find it in the base app  15.2 current build. What is the status for this event. [3945](https://github.com/microsoft/ALAppExtensions/issues/3945)

Please add a new publisher event OnBeforeOnGetSourceDocHeader in Codeunit 7322 on function GetSourceDocHeader and call it at the start of the function.

![2019-08-27 09_51_28-Codeunit 6036600 added publisher (Post on git) pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63751847-70931f00-c8b0-11e9-9a57-a930848b5761.png)

Please add the corresponding Integration Event In the bottom of the codeunit

![2019-08-27 09_51_34-Codeunit 6036600 added publisher (Post on git) pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/54017538/63751854-7426a600-c8b0-11e9-9bd0-0c0b38c2e65c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
