### ISSUE TITLE
[EventRequest] Table 124 PurchCrMemoHdr.al

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#5550]
Hi MS,

Can you please hook an event on below code.
![image](https://user-images.githubusercontent.com/33481576/72250680-270a5d00-3622-11ea-8f8b-373080bda92e.png)

There is need of filtering VendorLedgerEntry before page run.
![image](https://user-images.githubusercontent.com/33481576/72250876-abf57680-3622-11ea-8872-67f8a62d9cc7.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
