### ISSUE TITLE
[EventRequest] table 124 PurchCrMemoHdr.al

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#5551]
Hi MS,

Please help us by adding a publisher on table 124 (PurchCrMemoHdr) in start of **Navigate** function.
![image](https://user-images.githubusercontent.com/33481576/72251215-71400e00-3623-11ea-86fa-772683642523.png)
![image](https://user-images.githubusercontent.com/33481576/72251257-89b02880-3623-11ea-8e9e-9557642d63e8.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
