### ISSUE TITLE
[EventRequest] table 122 PurchInvHdr.al

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#5552]
Hi MS,

Please help us by adding a publisher on table 122 (PurchInvHdr) as below.
![image](https://user-images.githubusercontent.com/33481576/72251841-6f2a7f00-3624-11ea-99b2-96819f11e0f0.png)

![image](https://user-images.githubusercontent.com/33481576/72251921-86696c80-3624-11ea-8269-995b1991a83d.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
