### ISSUE TITLE
[EventRequest] Table 122 PurchInvHdr.al

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#5553]
Hi MS,

Please help us by adding an integration event into table 122 in start of **Navigate** function like below.
![image](https://user-images.githubusercontent.com/33481576/72252373-2cb57200-3625-11ea-85d5-95023cfc61b5.png)

![image](https://user-images.githubusercontent.com/33481576/72252424-3ccd5180-3625-11ea-9597-f6cc13c918df.png)

Thanks
SUD

**Comment by AlexanderYakunin** [comment]
Please help me understand why do you need this event? Are you going to replace "Posting Date" or"No."?

**Comment by SUD-D365** [comment]
Oh Thanks @AlexanderYakunin  for your prompt revert. I am really in need of your help.
Ok so before going with this event only there is a whole vertical that we need to convert in Full Cloud.
So that is why there are several events that we want to get from MS in next releases.

For this event we are trying to pass a new custom field filter along with "Posting Date" and "No." so that we can show filtered value while navigating to the entries.

Also if there is any other process to fasten up our vertical in to full cloud with help of MS then please let me know. Any help would be highly appreciated.

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SUD-D365** [comment]
Any update about the requested event?

**Comment by AlexanderYakunin** [comment]
This request have been closed by our automation by mistake, as we still cannot implement such event. Don't understand how you can pass Rec to Navigate page using this event, you need procedure in page Navigate for passing Rec at least?
