### ISSUE TITLE
[EventRequest] Table 120 PurchRcptHdr.al

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#5554]
Hi MS,

Please help us by adding below integration event in Table120 (PurchRcptHdr.al).
![image](https://user-images.githubusercontent.com/33481576/72253121-caf60780-3626-11ea-9135-d159302dd489.png)

![image](https://user-images.githubusercontent.com/33481576/72253145-da755080-3626-11ea-9233-a6f4aca6eab2.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
