### ISSUE TITLE
[EventRequest] Table 114,112 SalesCrMemoHdr.al, SalesInvHdr.al

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#5555]
Hi MS,

Please help us by adding below events on Table 114 (SalesCrMemoHdr.al).
![image](https://user-images.githubusercontent.com/33481576/72253355-60919700-3627-11ea-9bc3-df351278d080.png)

![image](https://user-images.githubusercontent.com/33481576/72253391-74d59400-3627-11ea-928e-8a669b954094.png)

![image](https://user-images.githubusercontent.com/33481576/72253416-83bc4680-3627-11ea-9e86-328b41b2b759.png)

Same events are requested for Table112 (SalesInvHdr.al). Do i need to create seperate issue?

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SUD-D365** [comment]
Any update about **OnNavigateBeforeRun** event?
