### ISSUE TITLE
[EventRequest] Table110 (SalesShpmtHdr.al)

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#5556]
Hi MS,

Please help us by adding below events on Table 110 (SalesShpmtHdr.al).
![image](https://user-images.githubusercontent.com/33481576/72253956-be72ae80-3628-11ea-9901-187cde086288.png)
![image](https://user-images.githubusercontent.com/33481576/72253992-db0ee680-3628-11ea-87f2-dc0a383bf6ab.png)

![image](https://user-images.githubusercontent.com/33481576/72254018-eb26c600-3628-11ea-9c81-3762d416f861.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SUD-D365** [comment]
Any update about **OnNavigateBeforeRun** event?
