### ISSUE TITLE
Table 112 Extend Event Parameter OnBeforeSendRecords

### ISSUE THREAD

**Issue by bstanienda** [microsoft/ALAppExtensions#5557]
Please integrate the parameter "DocumentSendingProfile" to the event OnBeforeSendRecords in Table 112

**Comment by AlexanderYakunin** [comment]
Why do you need this? This is local variable and you can define it in your code?

**Comment by bstanienda** [comment]
We need this, because we have an own outsourced event subscriber to OnBeforeSendRecord where we call the function „DocumentSendingProfile.SendCustomerRecords“ with an own different „Usage“. When we define a local variable DocumentSendingProfile in our Event Subsriber, the values in the former Variable DocumentSendingProfile in Table 112 are lost.

Kind regards,
Bianca Stanienda
Senior Developer
- Product Engineer -
Phone +49 5241 9217-235
Fax +49 5241 9217-400
bianca.stanienda@modusconsult.de<mailto:bianca.stanienda@modusconsult.de>



MODUS Consult GmbH
James-Watt-Straße 6
D-33334 Gütersloh

Telefon: +49 5241 9217-0
Telefax: +49 5241 9217-400

contact@modusconsult.de
www.modusconsult.de

Geschäftsführung: Bernhard Alsdorf, Birgit Merschmann, Stefan Sagowski, Klaus Wagner

Handelsregister beim Amtsgericht Gütersloh, HRB 11619
USt-IdNr.: DE 257988856

Entdecken Sie unsere Webinare für Business-IT und treffen Sie uns live vor Ort: https://www.modusconsult.de/unternehmen/modus-consult-live
Bleiben Sie auf dem aktuellsten Stand und erhalten Sie mit unserem Newsletter alle Neuigkeiten aus unserem Unternehmen: https://www.modusconsult.de/unternehmen/newsletter
Haben Sie Lust auf eine neue Herausforderung? https://www.modus-karriere.de

Wir nehmen das Thema Datenschutz sehr ernst. Deswegen informieren wir Sie über die Verarbeitung Ihrer personenbezogenen Daten durch die MODUS Consult GmbH und die Ihnen nach dem Datenschutzrecht zustehenden Rechte auf https://www.modusconsult.de/datenschutz.

Die 1995 gegründete MODUS Consult GmbH bietet integrative, ganzheitliche Leistungen aus einer Hand. Von ERP und CRM über DMS und BI bis zu Systemberatung und -technik basieren unsere Lösungen und unser Know-how auf der Erfahrung von 25 Jahren erfolgreicher Zusammenarbeit mit über 1.000 Kunden. Mit unseren zertifizierten Branchenlösungen auf Basis von Microsoft Dynamics setzen wir als Microsoft Gold Partner höchste Qualitätsansprüche an uns und an die gemeinsam mit unseren Partnern geschaffenen Lösungen.

Die MODUS Consult GmbH ist ein Unternehmen der Bechtle-Gruppe.


Von: Alexander Yakunin <notifications@github.com>
Gesendet: Mittwoch, 15. Januar 2020 14:41
An: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
Cc: Stanienda, Bianca <Bianca.Stanienda@modusconsult.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/ALAppExtensions] Table 112 Extend Event Parameter OnBeforeSendRecords (#5557)


Why do you need this? This is local variable and you can define it in your code?

**Comment by AlexanderYakunin** [comment]
Here is code of this procedure:
    procedure SendRecords()
    var
        DocumentSendingProfile: Record "Document Sending Profile";
        DummyReportSelections: Record "Report Selections";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSendRecords(DummyReportSelections, Rec, DocTxt, IsHandled);
        if not IsHandled then
            DocumentSendingProfile.SendCustomerRecords(
              DummyReportSelections.Usage::"S.Invoice", Rec, DocTxt, "Bill-to Customer No.", "No.",
              FieldNo("Bill-to Customer No."), FieldNo("No."));
    end;

You have all needed data in Rec variable (=SalesInvoiceHeader in event). Variable DocumentSendingProfile is empty before event call. So you simply need to use this code in your event subscriber:
DocumentSendingProfile.SendCustomerRecords(
              DummyReportSelections.Usage::"S.Invoice", SalesInvoiceHeader, DocTxt, SalesInvoiceHeader."Bill-to Customer No.", SalesInvoiceHeader."No.",
              SalesInvoiceHeader.FieldNo("Bill-to Customer No."), SalesInvoiceHeader.FieldNo("No."));
