### ISSUE TITLE
[Event-Request] Codeunit 229 - Document-Printout - GetPurchDocTypeUsage

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#556]
We need to print (and mail) a draft 'Purchase Invoice' via codeunit 229. 
Please extend the CASE statement below to support other document types before raising an ERROR.

```
LOCAL GetPurchDocTypeUsage(PurchHeader : Record "Purchase Header") : Integer
CASE PurchHeader."Document Type" OF
  PurchHeader."Document Type"::Quote:
    EXIT(ReportSelections.Usage::"P.Quote");
  PurchHeader."Document Type"::"Blanket Order":
    EXIT(ReportSelections.Usage::"P.Blanket");
  PurchHeader."Document Type"::Order:
    EXIT(ReportSelections.Usage::"P.Order");
  PurchHeader."Document Type"::"Return Order":
    EXIT(ReportSelections.Usage::"P.Return");
  ELSE
    ERROR('');
END;
```

PS: The codeunit contains lots of other similar CASE statements, please update these as well.

**Comment by AlexanderYakunin** [comment]
Thanks for you request! We currently put on hold changes to Table 77 as we want to provide better extensible approach for report selection. Please implement printing of your document in your extension instead of using table 77 for now.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.

**Comment by fvet** [comment]
@JesperSchulz, I agree 'report selections/usage' is to be refactored, however, we're using the 'Document-Print' codeunit as much as possible and want to avoid code duplication to print our custom document types. Can you instead provide a 'OnBeforeGetPurchDocTypeUsage(PurchHeader)'  with Handled pattern to allow us to hook into the GetPurchDocTypeUsage procedure? This would help us moving forward.

**Comment by fvet** [comment]
@JesperSchulz Any chance in reopening this issue and providing at least a publisher in GetPurchDocTypeUsage (we can work around the report selection usage limitations and wait for a final solution, but we can't work around the ERROR('') that blocks us from using COD 229). We want to avoid having to duplicate all 'PrintPurchHeader' logic ...
