### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134347 "ERM Document Line Tracking"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5562]
[Event Request] Application “Tests-ERM”, Codeunit 134347 "ERM Document Line Tracking"
![pic1](https://user-images.githubusercontent.com/45795262/72267986-45bc2400-3621-11ea-9d0a-bb7785dbbb67.png)

Could you please insert the OnTestInitialize Event at the beginning of all test procedures?
![pic2](https://user-images.githubusercontent.com/45795262/72268005-4eacf580-3621-11ea-9397-e974e8451275.png)
![pic3](https://user-images.githubusercontent.com/45795262/72268011-510f4f80-3621-11ea-852d-c88a8c001c0e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by JoergPernberg** [comment]
Is there anything new about this issue? Still waiting for the event in BC16 CU1.
