### ISSUE TITLE
[Event Request] Table 37 - OnBeforeUpdatePrepmtSetupFields

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#5564]
Please extend the Event with CurrFieldNo
`OnBeforeUpdatePrepmtSetupFields(Rec,IsHandled,CurrFieldNo);`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
