### ISSUE TITLE
 D365 for Sales integration stopped working

### ISSUE THREAD

**Issue by AndreyHrynyuk** [microsoft/ALAppExtensions#5565]
Hi,

Starting from an automatic update of the Business Central Production instance to version 15.2.39060.0 we have encountered the issues with the D365 for Sales integration. No synchronization for new records is performed and no log entries are created. The standard synchronization jobs for example for customer - account are not processed.

There is no customizations that can somehow affect standard sync process in any way and everything worked before the update.

Could you please advice how to solve this issue?

Thanks!

Update date :  10.01.20

**Comment by AlexanderYakunin** [comment]
This portal is primarily for extensibility and integration requests for extension development. Please do not use this portal for bug or hotfix requests. We cannot follow up on those, you need to create request for technical support instead and provide details and repro steps.
