### ISSUE TITLE
Codeunit 368 Format Document / Procedure SetPurchaseLine: Additional parameters

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#5568]
The function SetPurchaseLine in CU368 should have additional parameters "FormattedVATPercentage" / "FormattedLineAmount" according to the function SetSalesLine to be able to format the Line Amount in report 1322 "Standard Purchase - Order"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
