### ISSUE TITLE
Table 175 Update existing Publisher

### ISSUE THREAD

**Issue by JonasPatto** [microsoft/ALAppExtensions#5569]
Refering to #4505

Hello Microsoft-Team!

In this Issue you added the Publisher "OnInsertPurchLinesOnBeforeApplyStdVendPurchCodes" in Table 175.
We need a "Handler" added to this publisher because we need to skip the Report and the following Code in certain situation

![image](https://user-images.githubusercontent.com/48987445/72337148-596b9700-36c2-11ea-9d7c-da4d69ee0533.png)

Kind Regards

Jonas Be Patto

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
