### ISSUE TITLE
Codeunit 12 Existing Events more arguments or GlobalVarAccess

### ISSUE THREAD

**Issue by rdebath** [Microsoft/ALAppExtensions#557]
Currently from trigger `OnBeforeContinuePosting` I need to access the CU12 global variables `GLReg` and `NextEntryNo` also in `OnAfterGLFinishPosting` I'm using `GLReg`, `TempGLEntryBuf`, `NextTransactionNo` and `NextEntryNo`.  (all with modification - byVar) 

Please can you set `GlobalVarAccess` to yes on these events.

**Comment by rdebath** [comment]
Um, I don't see any label; has this been classified as an event-request, rejected-event-request or something else?

**Comment by JesperSchulz** [comment]
Something seems to have been off with our issue <-> work item automation. This issue appears to have been resolved end of December. Closing issue. If you find issues, please open a new issue, as we don't revisit closed issues. Thanks!
