### ISSUE TITLE
[Event Request] codeunit 11 "Gen. Jnl.-Check Line" OnAfterAssignTableIdAndNoOnCheckDimensions

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5572]
Could we please an event OnAfterAssignTableIdAndNoOnCheckDimensions in Codeunit 11 in function CheckDimensions?

Code Example:

        with GenJnlLine do begin
            if not DimMgt.CheckDimIDComb("Dimension Set ID") then
                ThrowGenJnlLineError(GenJnlLine, Text011, DimMgt.GetDimCombErr);

            TableID[1] := DimMgt.TypeToTableID1("Account Type");
            No[1] := "Account No.";
            TableID[2] := DimMgt.TypeToTableID1("Bal. Account Type");
            No[2] := "Bal. Account No.";
            TableID[3] := DATABASE::Job;
            No[3] := "Job No.";
            TableID[4] := DATABASE::"Salesperson/Purchaser";
            No[4] := "Salespers./Purch. Code";
            TableID[5] := DATABASE::Campaign;
            No[5] := "Campaign No.";
            // start kvspsa - Event Raiser
            **OnAfterAssignTableIdAndNoOnCheckDimensions(GenJnlLine, TableID, No);**
            // stop kvspsa
            if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
                ThrowGenJnlLineError(GenJnlLine, Text012, DimMgt.GetDimValuePostingErr);
        end;

Event:
[IntegrationEvent(false, false)]
    local procedure OnAfterAssignTableIdAndNoOnCheckDimensions(var GenJournalLine: Record "Gen. Journal Line"; var TableID: array[10] of Integer; var No: array[10] of Code[20])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
