### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeRunWithoutCheck

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5573]
Could we please an event OnBeforeRunWithoutCheck in Codeunit 12 in function RunWithoutCheck?

Code Example:
    procedure RunWithoutCheck(var GenJnlLine2: Record "Gen. Journal Line"): Integer
    var
        GenJnlLine: Record "Gen. Journal Line";
    begin
        // start kvspsa - Event Raiser
        **OnBeforeRunWithoutCheck(GenJnlLine);**
        // stop kvspsa
        GenJnlLine.Copy(GenJnlLine2);
        Code(GenJnlLine, false);
        OnAfterRunWithoutCheck(GenJnlLine);
        GenJnlLine2 := GenJnlLine;
        exit(GLEntryNo);
    end;

Event:
[IntegrationEvent(TRUE, false)]
    local procedure OnBeforeRunWithoutCheck(var GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
