### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterAssignGenJnlLineValuesOnPostFixedAsset

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5574]
Could we please an event OnAfterAssignGenJnlLineValuesOnPostFixedAsset in Codeunit 12 in function PostFixedAsset?

Code Example:

        with GenJnlLine do begin
            InitGLEntry(GenJnlLine, GLEntry, '', "Amount (LCY)", "Source Currency Amount", true, "System-Created Entry");
            GLEntry."Gen. Posting Type" := "Gen. Posting Type";
            GLEntry."Bal. Account Type" := "Bal. Account Type";
            GLEntry."Bal. Account No." := "Bal. Account No.";
            InitVAT(GenJnlLine, GLEntry, VATPostingSetup);
            GLEntry2 := GLEntry;
            FAJnlPostLine.GenJnlPostLine(
              GenJnlLine, GLEntry2.Amount, GLEntry2."VAT Amount", NextTransactionNo, NextEntryNo, GLReg."No.");
            ShortcutDim1Code := "Shortcut Dimension 1 Code";
            ShortcutDim2Code := "Shortcut Dimension 2 Code";
            DimensionSetID := "Dimension Set ID";
            Correction2 := Correction;
            // start kvspsa - Event Raiser
            **OnAfterAssignGenJnlLineValuesOnPostFixedAsset(GenJnlLine);**
            // stop kvspsa
        end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterAssignGenJnlLineValuesOnPostFixedAsset(GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
