### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeInitGLEntryOnPostFixedAsset

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5575]
Could we please an event OnBeforeInitGLEntryOnPostFixedAsset in Codeunit 12 in function PostFixedAsset?

Code Example:
        with TempFAGLPostBuf do
            if FAJnlPostLine.FindFirstGLAcc(TempFAGLPostBuf) then
                repeat
                    GenJnlLine."Shortcut Dimension 1 Code" := "Global Dimension 1 Code";
                    GenJnlLine."Shortcut Dimension 2 Code" := "Global Dimension 2 Code";
                    GenJnlLine."Dimension Set ID" := "Dimension Set ID";
                    GenJnlLine.Correction := Correction;
                    // start kvspsa - Event Raiser
                    **OnBeforeInitGLEntryOnPostFixedAsset(GenJnlLine, TempFAGLPostBuf);**
                    // stop kvspsa
                    FADimAlreadyChecked := "FA Posting Group" <> '';
                    CheckDimValueForDisposal(GenJnlLine, "Account No.");

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeInitGLEntryOnPostFixedAsset(var GenJnlLine: Record "Gen. Journal Line"; FAGLPostBuf: Record "FA G/L Posting Buffer");
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
