### ISSUE TITLE
Event Request Codeunit 5812 Calculate Standard Cost - OnBeforeCalcRtngCostPerUnit

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#5576]
We need a Publisher in function CalcRtngCostPerUnit to calculate own Costs per Unit:

CASE Type OF
  Type::"Work Center":
    GetWorkCenter(No,WorkCenter);
  Type::"Machine Center":
    GetMachineCenter(No,MachineCenter);
END;
**==> NEW
IsHandled := false;
OnBeforeCalcRtngCostPerUnit(Type,DirUnitCost,IndirCostPct,OvhdRate,UnitCost,UnitCostCalculation,WorkCenter,MachineCenter,IsHandled)
if not IsHandled then
==> NEW**
CostCalcMgt.RoutingCostPerUnit2(Type,DirUnitCost,IndirCostPct,OvhdRate,UnitCost,UnitCostCalculation,WorkCenter,MachineCenter);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
