### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforePostVATOnPostFixedAsset

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5577]
Could we please have an event OnBeforePostVATOnPostFixedAsset in Codeunit 12 in function PostFixedAsset?

Code Example:
        GenJnlLine."Shortcut Dimension 1 Code" := ShortcutDim1Code;
        GenJnlLine."Shortcut Dimension 2 Code" := ShortcutDim2Code;
        GenJnlLine."Dimension Set ID" := DimensionSetID;
        GenJnlLine.Correction := Correction2;
        // start kvspsa - Event Raiser
        **OnBeforePostVATOnPostFixedAsset(GenJnlLine);**
        // stop kvspsa
        GLEntry := GLEntry2;
        if VATEntryGLEntryNo = 0 then
            VATEntryGLEntryNo := GLEntry."Entry No.";
        TempGLEntryBuf."Entry No." := VATEntryGLEntryNo; // Used later in InsertVAT(): GLEntryVATEntryLink.InsertLink(TempGLEntryBuf."Entry No.",VATEntry."Entry No.")
        PostVAT(GenJnlLine, GLEntry, VATPostingSetup);

        FAJnlPostLine.UpdateRegNo(GLReg."No.");
        OnMoveGenJournalLine(GenJnlLine, GLEntry.RecordId);

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforePostVATOnPostFixedAsset(var GenJnlLine: Record "Gen. Journal Line");
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
