### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCalcPmtDiscount

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5579]
Could we please have an event OnAfterCalcPmtDiscount in Codeunit 12 in function CalcPmtDisc?

Code Example:
            DtldCVLedgEntryBuf.InitDtldCVLedgEntryBuf(
              GenJnlLine, NewCVLedgEntryBuf, DtldCVLedgEntryBuf,
              DtldCVLedgEntryBuf."Entry Type"::"Payment Discount", PmtDisc, PmtDiscLCY, PmtDiscAddCurr, 0, 0, 0);

            // start kvspsa - Event Raiser
            **OnAfterCalcPmtDiscount(DtldCVLedgEntryBuf, OldCVLedgEntryBuf2, PmtDisc, PmtDiscLCY);**
            // stop kvspsa

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterCalcPmtDiscount(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf2: Record "CV Ledger Entry Buffer"; PmtDisc: Decimal; PmtDiscLCY: Decimal);
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
