### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5580]
Could we please have an event OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT in Codeunit 12 in function CalcPmtDiscIfAdjVAT?

Code Example:
                if VATPostingSetup."Adjust for Payment Discount" then begin
                    if LastConnectionNo <> VATEntry2."Sales Tax Connection No." then begin
                        if LastConnectionNo <> 0 then begin
                            DtldCVLedgEntryBuf := DtldCVLedgEntryBuf2;
                            DtldCVLedgEntryBuf."VAT Amount (LCY)" := -TotalVATAmount;
                            DtldCVLedgEntryBuf.InsertDtldCVLedgEntry(DtldCVLedgEntryBuf, NewCVLedgEntryBuf, false);
                            // start kvspsa - Event Raiser
                            **OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT(DtldCVLedgEntryBuf, OldCVLedgEntryBuf, DtldCVLedgEntryBuf.Amount, DtldCVLedgEntryBuf."Amount (LCY)");**
                            // stop kvspsa
                            InsertSummarizedVAT(GenJnlLine);
                        end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; Amount: Decimal; AmountLCY: Decimal);
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
