### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCalcPmtDiscTolerance

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5582]
Could we please have an event OnAfterCalcPmtDiscTolerance in Codeunit 12 in function CalcPmtDiscTolerance?

Code Example:
        DtldCVLedgEntryBuf.InitDtldCVLedgEntryBuf(
          GenJnlLine, NewCVLedgEntryBuf, DtldCVLedgEntryBuf,
          DtldCVLedgEntryBuf."Entry Type"::"Payment Discount Tolerance", PmtDiscTol, PmtDiscTolLCY, PmtDiscTolAddCurr, 0, 0, 0);

        // start kvspsa - Event Raiser
        **OnAfterCalcPmtDiscTolerance(DtldCVLedgEntryBuf, OldCVLedgEntryBuf, PmtDiscTol, PmtDiscTolLCY);**
        // stop kvspsa
    end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterCalcPmtDiscTolerance(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; PmtDiscTol: Decimal; PmtDiscTolLCY: Decimal);
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
