### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldCustLedgEntries

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5584]
Could we please have an event OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldCustLedgEntries in Codeunit 12 in function PostDtldCustLedgEntries?

Code Example:
        CreateGLEntriesForTotalAmounts(
          GenJnlLine, TempInvPostBuf, AdjAmount, SaveEntryNo, CustPostingGr.GetReceivablesAccount, LedgEntryInserted);

        // start kvspsa - Event Raiser
        **OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldCustLedgEntries(TempGLEntryBuf, GlobalGLEntry, NextTransactionNo);**
        // stop kvspsa
        DtldLedgEntryInserted := not DtldCVLedgEntryBuf.IsEmpty;
        DtldCVLedgEntryBuf.DeleteAll;
    end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldCustLedgEntries(var TempGLEntryBuf: Record "G/L Entry"; var GlobalGLEntry: Record "G/L Entry"; NextTransactionNo: Integer)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
