### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeVendPostApplyVendLedgEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5585]
Could we please have an event OnBeforeVendPostApplyVendLedgEntry in Codeunit 12 in function VendPostApplyVendLedgEntry?

Code Example:
    begin
        // start kvspsa - Event Raiser
        **OnBeforeVendPostApplyVendLedgEntry(GenJnlLinePostApply);**
        // stop kvspsa
        GenJnlLine := GenJnlLinePostApply;
        VendLedgEntry.TransferFields(VendLedgEntryPostApply);
        with GenJnlLine do begin

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeVendPostApplyVendLedgEntry(GenJnlLinePostApply: Record "Gen. Journal Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
