### ISSUE TITLE
CU Integration Management - CreateIntegrationPageList - event request

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#5586]
is it possible to add an event in cu integration management in function CreateIntegrationPageList at the end so that we can add pages for added tables to ingration.

OnAfterCreateIntegrationPageList(var TempNameValueBuffer,var NextID)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
