### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldVendLedgEntries

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5587]
Could we please have an event OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldVendLedgEntries in Codeunit 12 in function PostDtldVendLedgEntries?

Code Example:
        CreateGLEntriesForTotalAmounts(
          GenJnlLine, TempInvPostBuf, AdjAmount, SaveEntryNo, VendPostingGr.GetPayablesAccount, LedgEntryInserted);
        // start kvspsa - Event Raiser
        **OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldVendLedgEntries(TempGLEntryBuf, GlobalGLEntry, NextTransactionNo);**
        // stop kvspsa
        DtldLedgEntryInserted := not DtldCVLedgEntryBuf.IsEmpty;
        DtldCVLedgEntryBuf.DeleteAll;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeDtldCVLedgEntryBufDeleteallOnPostDtldVendLedgEntries(var TempGLEntryBuf: Record "G/L Entry"; var GlobalGLEntry: Record "G/L Entry"; NextTransactionNo: Integer)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
