### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCreateGLEntryOnPostDtldCVLedgEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5588]
Could we please have an event OnAfterCreateGLEntryOnPostDtldCVLedgEntry in Codeunit 12 in function PostDtldCVLedgEntry?

Code Example:
                "Entry Type"::"Payment Discount Tolerance":
                    begin
                        CreateGLEntry(GenJnlLine, AccNo, -"Amount (LCY)", -"Additional-Currency Amount", false);
                        // start kvspsa - Event Raiser
                        **OnAfterCreateGLEntryOnPostDtldCVLedgEntry("Entry No.", TempGLEntryBuf."Entry No.", AccNo);**
                        // stop kvspsa
                        if not Unapply then
                            CollectAdjustment(AdjAmount, -"Amount (LCY)", -"Additional-Currency Amount");
                    end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterCreateGLEntryOnPostDtldCVLedgEntry(EntryNo: Integer; GLEntryBufEntryNo: Integer; AccountNo: Code[20])
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Using Entry no as parameter is not a good idea, as next time we wll need to add more fields as parameters. We should use record variables instead. In this case no need for AccNo as it will be already assigned to TempGLEntryBuf.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
