### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCreateGLEntryVATOnPostDtldCVLedgEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5589]
Could we please have an event OnAfterCreateGLEntryVATOnPostDtldCVLedgEntry in Codeunit 12 in function PostDtldCVLedgEntry?

Code Example:
                "Entry Type"::"Payment Discount Tolerance (VAT Excl.)":
                    begin
                        if not Unapply then
                            CreateGLEntryVATCollectAdj(
                              GenJnlLine, AccNo, -"Amount (LCY)", -"Additional-Currency Amount", -"VAT Amount (LCY)", DtldCVLedgEntryBuf,
                              AdjAmount)
                        else
                            CreateGLEntryVAT(
                              GenJnlLine, AccNo, -"Amount (LCY)", -"Additional-Currency Amount", -"VAT Amount (LCY)", DtldCVLedgEntryBuf);
                        // start kvspsa - Event Raiser
                        **OnAfterCreateGLEntryVATOnPostDtldCVLedgEntry("Entry No.", TempGLEntryBuf."Entry No.", AccNo);**
                        // stop kvspsa
                    end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterCreateGLEntryVATOnPostDtldCVLedgEntry(EntryNo: Integer; GLEntryBufEntryNo: Integer; AccountNo: Code[20])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
