### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterUpdateCustLedgEntryOnUnapplyCustLedgEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5590]
Could we please have an event OnAfterUpdateCustLedgEntryOnUnapplyCustLedgEntry in Codeunit 12 in function UnapplyCustLedgEntry?

Code Example:
            DtldCustLedgEntry2.Unapplied := true;
            DtldCustLedgEntry2."Unapplied by Entry No." := NewDtldCustLedgEntry."Entry No.";
            DtldCustLedgEntry2.Modify;

            UpdateCustLedgEntry(DtldCustLedgEntry2);
            // start kvspsa - Event Raiser
            **OnAfterUpdateCustLedgEntryOnUnapplyCustLedgEntry(DtldCustLedgEntry2, TempGLEntryBuf, GlobalGLEntry, NextTransactionNo);**
        // stop kvspsa
        until DtldCustLedgEntry2.Next = 0;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterUpdateCustLedgEntryOnUnapplyCustLedgEntry(DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry"; var TempGLEntryBuf: Record "G/L Entry"; var GlobalGLEntry: Record "G/L Entry"; NextTransactionNo: Integer)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
