### ISSUE TITLE
[Event-Request] Codeunit 7301 Whse. Jnl.-Register Line - OnDeleteFromBinContentOnBeforeDeleteFromBinContent

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5591]
Hi AL team,  
we need the following events OnDeleteFromBinContentOnBeforeDeleteFromBinContent,  OnDeleteFromBinContentOnBeforeCheckQuantity in function "DeleteFromBinContent":

                FromBinContent.SetRange("Serial No. Filter");
                FromBinContent.CalcFields("Quantity (Base)");
                if FromBinContent."Quantity (Base)" + "Qty. (Base)" = 0 then
                    if (FromBinContent."Positive Adjmt. Qty. (Base)" = 0) and
                       (FromBinContent."Put-away Quantity (Base)" = 0) and
                       (not FromBinContent.Fixed)
                    // origin code
                    - then
                    - FromBinContent.Delete();
                    // new code begin
                    + then begin
                    +    OnDeleteFromBinContentOnBeforeDeleteFromBinContent(FromBinContent);
                    +    FromBinContent.Delete();
                    +end;
                    // new code end
            end else begin
                // new code begin
                + OnDeleteFromBinContentOnBeforeCheckQuantity(FromBinContent, WhseEntry);
                // new code end
                FromBinContent.CalcFields(Quantity);

    [IntegrationEvent(false, false)]
    local procedure OnDeleteFromBinContentOnBeforeDeleteFromBinContent(BinContent: Record "Bin Content")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnDeleteFromBinContentOnBeforeCheckQuantity(var BinContent: Record "Bin Content"; WarehouseEntry: Record "Warehouse Entry")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
