### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterUpdateVendLedgEntryOnUnapplyVendLedgEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5592]
Could we please have an event OnAfterUpdateVendLedgEntryOnUnapplyVendLedgEntry in Codeunit 12 in function UnapplyVendLedgEntry?

Code Example:
            UpdateVendLedgEntry(DtldVendLedgEntry2);
            // start kvspsa - Event Raiser
            **OnAfterUpdateVendLedgEntryOnUnapplyVendLedgEntry(DtldVendLedgEntry2, TempGLEntryBuf, GlobalGLEntry, NextTransactionNo);**
        // stop kvspsa
        until DtldVendLedgEntry2.Next = 0;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterUpdateVendLedgEntryOnUnapplyVendLedgEntry(DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry"; var TempGLEntryBuf: Record "G/L Entry"; var GlobalGLEntry: Record "G/L Entry"; NextTransactionNo: Integer)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
