### ISSUE TITLE
[Event-Request] Codeunit 7301 Whse. Jnl.-Register Line - OnInsertToBinContentOnBeforeInsertBinContent

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5593]
Hi AL team,

we need the following event in function _InsertToBinContent_:

               BinContent.Fixed := BinContent.Default;
            end;
            // new event begin
            + OnInsertToBinContentOnBeforeInsertBinContent(BinContent, WhseEntry);
            // new event end
            BinContent.Insert;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnInsertToBinContentOnBeforeInsertBinContent(var BinContent: Record "Bin Content"; WarehouseEntry: Record "Warehouse Entry")
    begin
    end;

**Comment by AlexanderYakunin** [comment]
This event already implemented
