### ISSUE TITLE
[Event-Request] Codeunit 7301 Whse. Jnl.-Register Line - OnUpdateDefaultBinContentOnBeforeModifyBinContent

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5594]
Hi AL team,

we need the following event in function _UpdateDefaultBinContent_:

        if BinContent.FindFirst then
            if BinContent."Bin Code" <> BinCode then begin
                BinContent.Default := false;
                // new event begin
                + OnUpdateDefaultBinContentOnBeforeModifyBinContent(BinContent);
                // new event end
                BinContent.Modify;
            end;

        if BinContent."Bin Code" <> BinCode then begin
            BinContent2.SetRange("Location Code", LocationCode);
            BinContent2.SetRange("Item No.", ItemNo);
            BinContent2.SetRange("Variant Code", VariantCode);
            BinContent2.SetRange("Bin Code", BinCode);
            BinContent2.FindFirst;
            BinContent2.Default := true;
            // new event begin
            + OnUpdateDefaultBinContentOnBeforeModifyBinContent(BinContent2);
            // new event end
            BinContent2.Modify;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateDefaultBinContentOnBeforeModifyBinContent(var BinContent: Record "Bin Content")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
