### ISSUE TITLE
Add parameter to event - report 15000062 "Remittance - Import (Bank)" (Norwegian Localization) 

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#5595]
Hi. Can you add parameter BalanceEntryAmountLCY as reference to event OnAfterProcessBETFOR23and04 in report 15000062 "Remittance - Import (Bank)"?

![image](https://user-images.githubusercontent.com/46031720/72351619-fccba480-36e0-11ea-9fa3-089f119c245a.png)

![image](https://user-images.githubusercontent.com/46031720/72351733-30a6ca00-36e1-11ea-846c-8fba5ffaf650.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
