### ISSUE TITLE
OnAfterRecordChanged - Sales Shipment Header

### ISSUE THREAD

**Issue by YannRobertCargo** [microsoft/ALAppExtensions#5596]
Hello, 
Following [this issue](https://github.com/microsoft/ALAppExtensions/issues/4295), an event "OnAfterRecordChanged" has been added to page 1350 (Sales Shipment Header - Update) to allow us to detect changes on custom fields.
However, the record sent to the event is not the same event used to detect the changes in the function :
![image](https://user-images.githubusercontent.com/47186314/72356172-1375f980-36e9-11ea-8f84-62214050e63d.png)
While testing subscribing to the event : 
![image](https://user-images.githubusercontent.com/47186314/72356333-62239380-36e9-11ea-88bb-bca9c0900ed4.png)
Both of the records have the new value of the field thus I cannot compare them.

Could you please correct the event call with xSalesShipmentHeader instead of xRec ?

The problem might be also present in pages 1351, 1352 and 1353.
I briefly glanced at page 1351 and the code is the same but can't test it at the moment as we do not need those.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
