### ISSUE TITLE
OnBeforeGetSourceDocumentsRun Event in Codeunit 5751 "Get Source Doc. Inbound" has the wrong position

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#5597]
The OnBeforeGetSourceDocumentsRun Event in Codeunit 5751 "Get Source Doc. Inbound" has the wrong position in my opinion. It is run after the GetSourceDocuments.RunModal. Can you fix this?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
