### ISSUE TITLE
[Code Change] Page 5786 - Source Document Filter Card

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#5599]
Hi al team, 

i have requested ticket #5130 
I saw in the Master DB that the code has already been moved to the function and the requested event is thrown there.
My plan was to set more global variables to the page in my extension object, which control the property Enabled on some fields. I cannot implement this with my requested event, because the page extension was not initialized when the OnInit trigger of the page was executed.

Is it possible that the function "InitializeControls" is no longer called in the OnInit of the page but in the OnOpenPage? 

```
trigger OnInit()
    begin
        // NEW >>>>
        // InitializeControls();
        // NEW <<<<
    end;

    trigger OnOpenPage()
    begin
        // NEW >>>>
        InitializeControls();
        // NEW <<<<
        DataCaption := CurrPage.Caption;
        FilterGroup := 2;
        if GetFilter(Type) <> '' then
            DataCaption := DataCaption + ' - ' + GetFilter(Type);
        FilterGroup := 0;
        CurrPage.Caption(DataCaption);

        EnableControls;
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
