### ISSUE TITLE
[Event-Request] Codeunit 7304 Whse. Jnl.-Register Batch - OnBeforeDeleteWhseJournalLineAndSetupNewLine

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5600]
Hi AL Team,

we need the following event in function _Code_:

             Init;
            "Line No." := WhseRegNo;

            // Update/delete lines
            // new event/code begin
            - if WhseRegNo <> 0 then begin
            + ForceDeleteAndSetupNewLine := WhseRegNo <> 0;
            + OnBeforeDeleteWhseJournalLineAndSetupNewLine(WhseJnlLine, WhseRegNo, ForceDeleteAndSetupNewLine);
            + if ForceDeleteAndSetupNewLine then begin
            // new event/code end  
                // Not a recurring journal
                WhseJnlLine2.CopyFilters(WhseJnlLine);
...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteWhseJournalLineAndSetupNewLine(var WarehouseJournalLine: Record "Warehouse Journal Line"; WhseRegNo: Integer; var ForceDeleteAndSetupNewLine: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
