### ISSUE TITLE
[Event-Request] Codeunit 7304 Whse. Jnl.-Register Batch - OnCheckLinesOnBeforeCheckWhseJnlLine

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5601]
Hi AL team,

we need the following event in function _CheckLines_:

                    ...
                    if not HideDialog then
                    Window.Update(2, LineCount);

                // new event begin
                + OnCheckLinesOnBeforeCheckWhseJnlLine(WhseJnlLine, IsHandled);
                + if not IsHandled then
                // new event end   
                    WMSMgt.CheckWhseJnlLine(WhseJnlLine, 4, "Qty. (Absolute, Base)", false);

...

    [IntegrationEvent(false, false)]
    local procedure OnCheckLinesOnBeforeCheckWhseJnlLine(WarehouseJournalLine: Record "Warehouse Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
