### ISSUE TITLE
Event Request Codeunit 5812 Calculate Standard Cost - OnAfterSetProperties

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#5602]
In the SetProperties function, we need a Publisher to record the values that were previously set. It is necessary to do this in order to transfer them to other functions that are required in the other Publishers/Subscibers used. This is what the GlobalVarAccess property in the publishers was intended for, but it is not used anywhere.
**SetProperties(NewCalculationDate : Date;NewCalcMultiLevel :....**
.....
MaxLevel := 50;
MfgSetup.GET;
GLSetup.GET;
**==> New
OnAfterSetProperties(NewCalculationDate : Date;NewCalcMultiLevel : Boolean;NewUseAssemblyList : Boolean;NewLogErrors : Boolean;NewStdCostWkshName : Text[50];NewShowDialog : Boolean)
==> New**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
