### ISSUE TITLE
[Event Request] Codeunit 64 Sales-Get Shipment: Function CreateInvLines

### ISSUE THREAD

**Issue by NGMex** [microsoft/ALAppExtensions#5603]
Hi, 

I'd like to request a new event.  
You already added the same event to the purchase codeunit 74 Purch.-Get Receipt, however, in the sales one it's missing:
```al
procedure CreateInvLines(var SalesShptLine2: Record "Sales Shipment Line")
var
    Window: Dialog;
    LineCount: Integer;
    TransferLine: Boolean;
    PrepmtAmtToDeductRounding: Decimal;
begin
    with SalesShptLine2 do begin
        SetFilter("Qty. Shipped Not Invoiced", '<>0');
        OnCreateInvLinesOnBeforeFind(SalesShptLine2); // requested event
        if FindSet then begin
    // [...]
```
And the event itself:
```al
[IntegrationEvent(false, false)]
local procedure OnCreateInvLinesOnBeforeFind(var SalesShptLine : Record "Sales Shipment Line")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
