### ISSUE TITLE
Wrong Solution in BREAKINGCHANGES.md for "Type Helper". IsAlphanumeric

### ISSUE THREAD

**Issue by elweilando** [microsoft/ALAppExtensions#5604]
> Error: 'Codeunit "Type Helper"' does not contain a definition for 'IsAlphanumeric'
> Solution: Function has been removed. The alternative is in codeunit 3001 DotNet_Regex, function IsAlphanumeric.

But in Codeunit 3001 DotNet_Regex exists no function 'IsAlphanumeric'

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by mazhelez** [comment]
Hi @elweilando 

Thank you very much for reporting this issue. It is indeed a bug in the breaking change documentation.

PR #6527 aims to fix it.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
