### ISSUE TITLE
[Event Request] Codeunit 5063 ArchiveManagement: Function StoreSalesDocument

### ISSUE THREAD

**Issue by NGMex** [microsoft/ALAppExtensions#5605]
Hi,

I'd like to request another event for ArchiveManagement at the beginning of StoreSalesDocument:
```al
    procedure StoreSalesDocument(var SalesHeader: Record "Sales Header"; InteractionExist: Boolean)
    var
        SalesLine: Record "Sales Line";
        SalesHeaderArchive: Record "Sales Header Archive";
        SalesLineArchive: Record "Sales Line Archive";
        IsHandled: Boolean;
    begin
        // >>> NEW
        OnBeforeStoreSalesDocument(SalesHeader, IsHandled);
        if IsHandled then
            exit;
        // <<< NEW
        SalesHeaderArchive.Init;
    // [...]
```

And the event itself:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeStoreSalesDocument(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
```

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
