### ISSUE TITLE
[Access Request] Page 9700 - Mail Dialog

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#5606]
Hello AL Team,
I need access to the variable "EmailItem" in a PageExtension.

Please change the page variable as below:

```
    protected var
        EmailItem: Record "Email Item";
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
