### ISSUE TITLE
[Event Request] Codeunit 7322 Create Inventory Pick/Movement OnAfterInsertWhseActivLine 

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#5609]
Hi,
Codeunit 7322 Create Inventory Pick/Movement 
Publisher OnAfterInsertWhseActivLine 

I do need access to:

Var RemQtyToPickBase
Var CompleteShipment
Var ReservationExists
and Property Include Sender True

**Comment by AlexanderYakunin** [comment]
Please provide exact code location for new event. We cannot implement without this information.

**Comment by aconcato** [comment]
> Please provide exact code location for new event. We cannot implement without this information.

Hi Alexander,
The Event is already there "OnAfterInsertWhseActivLine" on CU 7322, I'm asking to extend this standard event.
Unfortunately the architecture of Codeunit Create Inventory Pick/Movement is not great and currently I have replicated the entire  CU, but probably adding these parameters  and property sender with give us more flexibility.
Please let me know if something it's not clear.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
