### ISSUE TITLE
[Access Request] Page 10007 Customer Credit Info CustLedgerEntry variable access

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#5610]
We have the need to further filter the CustLedgerEntry records in our page extension of the Customer Credit Info page.

We request that you make the below variable Protected:
CustLedgerEntry: array[4] of Record "Cust. Ledger Entry";

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
