### ISSUE TITLE
[Access Request] Page 256 Payment Journal make ApplyEntriesActionEnabled protected

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#5611]
We utilize the below variable in our Payment Journal page extension object and would request that it be made protected.

ApplyEntriesActionEnabled: Boolean;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
