### ISSUE TITLE
[Event Request] Codeunit 1006 - new event publisher OnBeforeCopyJobPrices

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5612]
Requesting a new publisher event in codeunit 1006 (Copy Job) inside function CopyJobPrices:

![image](https://user-images.githubusercontent.com/28901234/72532049-96728d80-386a-11ea-89a1-8ebf45ab4982.png)

**LOCAL [IntegrationEvent] OnBeforeCopyJobPrices(VAR SourceJob : Record Job;VAR TargetJob : Record Job)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
