### ISSUE TITLE
[Event Request] Codeunit 1011 - new event publisher OnRunCheckBeforeTestChargeable

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5614]
Requesting a new publisher event in codeunit 1011 inside function RunCheck:

![image](https://user-images.githubusercontent.com/28901234/72539475-42ba7100-3877-11ea-8808-13ce01d6dc4e.png)

**LOCAL [IntegrationEvent] OnRunCheckBeforeTestChargeable(VAR JobJournalLine : Record "Job Journal Line";VAR CheckChargeable : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
