### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134774 "G/L Report UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5615]
[Event Request] Application “Tests-ERM”, Codeunit 134774 "G/L Report UT"
![pic1](https://user-images.githubusercontent.com/45795262/72599075-5a463800-3911-11ea-8d4b-daf6e54d3a5e.png)

Could you please insert the OnTestInitialize Event at the beginning of every test procedure?

![pic2](https://user-images.githubusercontent.com/45795262/72599095-5fa38280-3911-11ea-9b55-62baad16572a.png)

![pic3](https://user-images.githubusercontent.com/45795262/72599113-6500cd00-3911-11ea-9707-fc04cce9799a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
