### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134773 "New Document from Vendor List"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5616]
[Event Request] Application “Tests-ERM”, Codeunit 134773 "New Document from Vendor List"
![pic1](https://user-images.githubusercontent.com/45795262/72599259-9da0a680-3911-11ea-87ee-7b7d4edcd50f.png)

Could you please insert the OnTestInitialize Event at the beginning of every test procedure?

![pic2](https://user-images.githubusercontent.com/45795262/72599280-a5f8e180-3911-11ea-9985-87e1217f4560.png)

![pic3](https://user-images.githubusercontent.com/45795262/72599288-aabd9580-3911-11ea-81e5-2750531543d8.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
