### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134770 "New Document from Vendor Card"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5617]
[Event Request] Application “Tests-ERM”, Codeunit 134770 "New Document from Vendor Card"
![pic1](https://user-images.githubusercontent.com/45795262/72599390-e8bab980-3911-11ea-8254-cc3b22a7b639.png)

Could you please insert the OnTestInitialize Event at the beginning of every test procedure?
![pic2](https://user-images.githubusercontent.com/45795262/72599401-ece6d700-3911-11ea-91de-ad52be4285ce.png)
![pic3](https://user-images.githubusercontent.com/45795262/72599411-f07a5e00-3911-11ea-8426-f6f0c9b94c73.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
