### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134658 "Edit Posted Documents"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5618]
[Event Request] Application “Tests-ERM”, Codeunit 134658 "Edit Posted Documents"
![pic1](https://user-images.githubusercontent.com/45795262/72599507-21f32980-3912-11ea-91c4-9b47c9f98afc.png)

Could you please insert the OnTestInitialize Event at the beginning of every test procedure?
![pic2](https://user-images.githubusercontent.com/45795262/72599517-261f4700-3912-11ea-9b94-a7ef5269f427.png)
![pic3](https://user-images.githubusercontent.com/45795262/72599523-29b2ce00-3912-11ea-9b95-35ac13d8f23c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
