### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134462 "ERM Copy Item"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5619]
[Event Request] Application “Tests-ERM”, Codeunit 134462 "ERM Copy Item"
![pic1](https://user-images.githubusercontent.com/45795262/72599632-5ff04d80-3912-11ea-93e8-87c5705053b5.png)

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure?
![pic2](https://user-images.githubusercontent.com/45795262/72599641-62eb3e00-3912-11ea-9014-34cb69c310e3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
