### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134461 "ERM Item Cross Reference Purch"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5620]
[Event Request] Application “Tests-ERM”, Codeunit 134461 "ERM Item Cross Reference Purch"
![pic1](https://user-images.githubusercontent.com/45795262/72599771-a04fcb80-3912-11ea-84e3-bce35aed23bc.png)

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure?
![pic2](https://user-images.githubusercontent.com/45795262/72599775-a34abc00-3912-11ea-86de-1901502c5cc2.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
