### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134460 "ERM Item Cross Reference Sales"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5621]
[Event Request] Application “Tests-ERM”, Codeunit 134460 "ERM Item Cross Reference Sales"
![pic1](https://user-images.githubusercontent.com/45795262/72599886-d3925a80-3912-11ea-9724-59f03f25eda4.png)

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure?
![pic2](https://user-images.githubusercontent.com/45795262/72599896-d725e180-3912-11ea-9e11-09da562233a1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
