### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134406 "ERM SEPA Direct Debit Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5622]
[Event Request] Application “Tests-ERM”, Codeunit 134406 "ERM SEPA Direct Debit Test"
![pic1](https://user-images.githubusercontent.com/45795262/72600024-1d7b4080-3913-11ea-9ab7-7d2bbfe15165.png)

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure?
![pic2](https://user-images.githubusercontent.com/45795262/72600039-23712180-3913-11ea-85a1-f06a58913e49.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
