### ISSUE TITLE
[Event Request] Codeunit 6620 - new publisher event in function LinkJobPlanningLine, OnLinkJPLOnAfterInsertJPLI

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5623]
Requesting a new publisher event in codeunit 6620 (Copy Document Mgt.) inside function LinkJobPlanningLine:

![image](https://user-images.githubusercontent.com/28901234/72603741-82ce3200-3911-11ea-8bcc-597a8f8e9cc5.png)

**LOCAL [IntegrationEvent] OnLinkJPLOnAfterInsertJPLI(VAR JobPlanningLineInvoice : Record "Job Planning Line Invoice";VAR JobPlanningLine : Record "Job Planning Line")**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
