### ISSUE TITLE
Lines Instruction Mgt.SalesCheckAllLinesHaveQuantityAssigned ErrorMessage

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5624]
Hello,
if BC is installed in SaaS the the test in Codeunit 1320
Lines Instruction Mgt.SalesCheckAllLinesHaveQuantityAssigned ErrorMessage
will bring a wrong error message if in sales Order is a resource line without a Quantity.
Because in SaaS the IsFoundationEnabled is true and in that Case the function LinesInstructionMgt.SalesCheckAllLinesHaveQuantityAssigned(Rec) is called:
----------------------------------------------------------------------------------
**Page page 42 "Sales Order"**

    local procedure PostDocument(PostingCodeunitID: Integer; Navigate: Option)
    var
        SalesHeader: Record "Sales Header";
        LinesInstructionMgt: Codeunit "Lines Instruction Mgt.";
        InstructionMgt: Codeunit "Instruction Mgt.";
    begin
        if ApplicationAreaMgmtFacade.IsFoundationEnabled then
            LinesInstructionMgt.SalesCheckAllLinesHaveQuantityAssigned(Rec);
----------------------------------------------------------------------------------------
**Codeunit 1320 Lines Instruction Mgt.**
SalesLine.SETRANGE("Document No.",SalesHeader."No.");
SalesLine.SETRANGE("Document Type",SalesHeader."Document Type");
SalesLine.SETFILTER(Type,'<>%1',SalesLine.Type::" ");
SalesLine.SETFILTER("No.",'<>%1','');
SalesLine.SETRANGE(Quantity,0);

IF NOT SalesLine.ISEMPTY THEN
  ERROR(LinesMissingQuantityErr);
------------------------------------------------
And the ErrorMessage is: 
One or more document lines with a value in the Item No. field do not have a quantity specified.

But it is not an item line but a resource line.
----------
Please Change the ErrorMessage or the testing.

Kind regards

Michael Romano

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
