### ISSUE TITLE
[Event Request] Codeunit 99000830 - TransferReservEntry

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#5625]
Hi, please can you add new event in function **TransferReservEntry**, in Codeunit 99000830 "Create Reserv. Entry" on following place:
![image](https://user-images.githubusercontent.com/54843470/72617420-34348e00-3939-11ea-81f3-4a69ee125e69.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
