### ISSUE TITLE
Event correction on OnBeforeConfirmUpdateContractNo of table Service Header

### ISSUE THREAD

**Issue by StephanFeijen** [microsoft/ALAppExtensions#5626]
Event OnBeforeConfirmUpdateContractNo of table Service Header has parameters Confirmed and IsHandled.
Definition now is as follows using by value parameters:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmUpdateContractNo(var ServiceHeader: Record "Service Header"; Confirmed: Boolean; HideValidationDialog: Boolean; IsHandled: Boolean)
    begin
    end;

Is it possible to define them as by reference parameters?
Then I can use the parameters Confirmed and IsHandled in the subscriber.

New definition using by reference parameters:
    local procedure OnBeforeConfirmUpdateContractNo(var ServiceHeader: Record "Service Header"; var Confirmed: Boolean; HideValidationDialog: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
