### ISSUE TITLE
[Event Request] Report 7052 "Suggest Sales Price on Wksh." - OnBeforeSetNewUnitPrice

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5627]
Hi AL team,

we need the following event in _OnAfterGetRecord_ trigger of dataitem _"Sales Price"_:

                  ...
                  SalesPriceWksh."New Unit Price" :=
                  Round(SalesPriceWksh."New Unit Price", Currency2."Unit-Amount Rounding Precision");

                // new event begin
                + OnBeforeSetNewUnitPrice(SalesPriceWksh, PriceLowerLimit, SetNewUnitPriceIsHandled);
                + if not SetNewUnitPriceIsHandled then
                    // new event end
                    if SalesPriceWksh."New Unit Price" > PriceLowerLimit then
                        SalesPriceWksh."New Unit Price" := SalesPriceWksh."New Unit Price" * UnitPriceFactor;
                if RoundingMethod.Code <> '' then begin
                    RoundingMethod."Minimum Amount" := SalesPriceWksh."New Unit Price";
                    if RoundingMethod.Find('=<') then begin
                        ...

    + [IntegrationEvent(false, false)]
    + local procedure OnBeforeSetNewUnitPrice(var SalesPriceWorksheet: Record "Sales Price Worksheet"; PriceLowerLimit: Decimal; var IsHandled: Boolean)
    + begin
    + end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
