### ISSUE TITLE
[Event Request] Report 7052 "Suggest Sales Price on Wksh." - OnAfterPostReport

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5628]
Hi AL team,

we need the following event in _OnPostReport_ trigger:

    trigger OnPostReport()
    begin
        // new event begin
    +     OnAfterPostReport();
        // new event end
    end;

    + [IntegrationEvent(false, false)]
    + local procedure OnAfterPostReport()
    + begin
    + end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
