### ISSUE TITLE
[Event Request] Report 6032 "Post Prepaid Contract Entries" - OnBeforePost...

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5629]
Hi AL team,

we need the following events in function _PostGenJnlLine_:

            var
                + IsNonPrepaidAccountPostingHandled: Boolean;
                + IsPrepaidAccountPostingHandled: Boolean;
            ...
            GenJnlLine."Gen. Prod. Posting Group" := '';
            GenJnlLine."VAT Bus. Posting Group" := '';
            GenJnlLine."VAT Prod. Posting Group" := '';
            // new event begin
            + OnBeforePostNonPrepaidAccount(GenJnlLine, TempServLedgEntry, IsNonPrepaidAccountPostingHandled);
            + If not IsNonPrepaidAccountPostingHandled then
                // new event end
                GenJnlPostLine.RUN(GenJnlLine);
            //TSO VSO012353 BEG

            ServContractAccGr.Get(TempServLedgEntry."Serv. Contract Acc. Gr. Code");
            ServContractAccGr.TestField("Prepaid Contract Acc.");
            GenJnlLine.Validate("Account No.", ServContractAccGr."Prepaid Contract Acc.");
            GenJnlLine.Validate(Amount, -TempServLedgEntry."Amount (LCY)");
            GenJnlLine."Shortcut Dimension 1 Code" := TempServLedgEntry."Global Dimension 1 Code";
            GenJnlLine."Shortcut Dimension 2 Code" := TempServLedgEntry."Global Dimension 2 Code";
            GenJnlLine."Dimension Set ID" := TempServLedgEntry."Dimension Set ID";
            GenJnlLine."Gen. Posting Type" := GenJnlLine."Gen. Posting Type"::" ";
            GenJnlLine."Gen. Bus. Posting Group" := '';
            GenJnlLine."Gen. Prod. Posting Group" := '';
            GenJnlLine."VAT Bus. Posting Group" := '';
            GenJnlLine."VAT Prod. Posting Group" := '';

            // new event begin
            + OnBeforePostPrepaidAccount(GenJnlLine, TempServLedgEntry, IsPrepaidAccountPostingHandled);
            + If not IsPrepaidAccountPostingHandled then
                // new event end
                GenJnlPostLine.RUN(GenJnlLine);

        until TempServLedgEntry.Next = 0;
        ...

    + [IntegrationEvent(false, false)]
    + local procedure OnBeforePostNonPrepaidAccount(var GenJournalLine: Record "Gen. Journal Line"; var TempServiceLedgerEntry: Record "Service Ledger Entry" temporary; var IsHandled: Boolean)
    + begin
    + end;

    + [IntegrationEvent(false, false)]
    + local procedure OnBeforePostPrepaidAccount(var GenJournalLine: Record "Gen. Journal Line"; var TempServiceLedgerEntry: Record "Service Ledger Entry" temporary; var IsHandled: Boolean)
    + begin
    + end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
