### ISSUE TITLE
[Event Request] Table 1003 - OnValidateNo

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5630]
Requesting a new publisher event in table 1003, inside OnValidate trigger for field "No.":

![image](https://user-images.githubusercontent.com/28901234/72739741-30547600-3b9c-11ea-825c-105019bc51f3.png)

**LOCAL [IntegrationEvent] OnValidateNoTypeResource(VAR JobPlanningLine : Record "Job Planning Line";VAR xJobPlanningLine : Record "Job Planning Line";VAR IsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
