### ISSUE TITLE
[Event Request] Table 1003, OnBeforeValidateWorkTypeCode

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5631]
Requesting a new publisher event in table 1003 inside OnValidate() on Work Type Code

![image](https://user-images.githubusercontent.com/28901234/72790284-4100fc80-3c2d-11ea-8bb5-4574086f9980.png)

**LOCAL [IntegrationEvent] OnBeforeValidateWorkTypeCode(VAR JobPlanningLine : Record "Job Planning Line";VAR xJobPlanningLine : Record "Job Planning Line";VAR IsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
