### ISSUE TITLE
[Event Request] Report 5899 CalculateInventoryValue - OnBeforeOnAfterGetRecord

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5632]
New Event in Report 5899 "Calculate Inventory Value" - OnBeforeOnAfterGetRecord:

![image](https://user-images.githubusercontent.com/22153733/72793287-90015e80-3c3a-11ea-9b86-168d76f988f7.png)

IntegrationEvent
OnBeforeOnAfterGetRecord
var Item: Record Item; var SkipItem: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
