### ISSUE TITLE
[Event Request] Table 1003, OnBeforeValidateQtyToTransferToInvoice

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#5633]
Requesting a new publisher event in table 1003 inside OnValidate() on Qty. to Transfer to Invoice

![image](https://user-images.githubusercontent.com/28901234/72794933-b2907900-3c34-11ea-8baa-780f824133dd.png)

**LOCAL [IntegrationEvent] OnBeforeValidateQtyToTransferToInvoice(VAR JobPlanningLine : Record "Job Planning Line";VAR xJobPlanningLine : Record "Job Planning Line";VAR IsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
