### ISSUE TITLE
[Question] GetPstdDocLinesToRevere - Function scope will be changed to OnPrem

### ISSUE THREAD

**Issue by hhout** [microsoft/ALAppExtensions#5634]
Hi,

We’re extending the function ‘GetPstdDocLinesToRevere’ for one of our modules, we can see a remark in standard code for this function: [Obsolete('Function scope will be changed to OnPrem')].
What will be the replacement for Business Central SaaS?

**Table 36 "Sales Header"**
{
    Caption = 'Sales Header';
    DataCaptionFields = "No.", "Sell-to Customer Name";
    LookupPageID = "Sales List";

**The Obsolete code shown below, [Obsolete('Function scope will be changed to OnPrem')]:**

[Obsolete('Function scope will be changed to OnPrem')]
procedure GetPstdDocLinesToRevere()
var
       SalesPostedDocLines: Page "Posted Sales Document Lines";
begin
        GetCust("Sell-to Customer No.");
        SalesPostedDocLines.SetToSalesHeader(Rec);
        SalesPostedDocLines.SetRecord(Cust);
        SalesPostedDocLines.LookupMode := true;
        if SalesPostedDocLines.RunModal = ACTION::LookupOK then
            SalesPostedDocLines.CopyLineToDoc;
        Clear(SalesPostedDocLines);
end;

This function is run when you select ‘Get Posted Doc&ument Lines to Reverse’ via the Sales Return Order ribbon, Process menu option.
In the opened page a user can select posted shipment lines to add to the return order automatically.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
