### ISSUE TITLE
[Event Request] New Event in Report 5899 CalculateInventoryValue - OnAfterPreDataItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5635]
New Event in Report 5899 "Calculate Inventory Value" - OnAfterPreDataItem

![image](https://user-images.githubusercontent.com/22153733/72800861-9565a580-3c48-11ea-9f74-a17460cd6565.png)
[..…]
![image](https://user-images.githubusercontent.com/22153733/72800910-af06ed00-3c48-11ea-8354-305e8f1c3be7.png)

Integration Event
OnAfterPreDataItem
var Item: Record Item

This is primarily to be able to set a different filter on the item.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
