### ISSUE TITLE
[Event Request] New Event in Table 5895 InventoryAdjustmentBuffer

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5636]
New Event in Table 5895 "Inventory Adjustment Buffer" - OnAfterSumCostsTillValuationDateGetItem

![image](https://user-images.githubusercontent.com/22153733/72801493-e3c77400-3c49-11ea-819e-4d9b162e3f97.png)

Integration Event
OnAfterSumCostsTillValuationDateGetItem
var Item2: Record Item; var ValueEntry: Record "Value Entry"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
