### ISSUE TITLE
Email body issue in 15.2

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#5637]
Hi,

There is a function in CU 260 called EmailFileAndHtmlFromStream. It has a parameter HideDialog. That parameter is passed to function EmailFileInternal and so on. 
In BC v15.2 you added changes and below IF statement will not change HtmlFormated to true (like it does when the dialog is opened):
IF TempEmailItem."Message Type" = TempEmailItem."Message Type"::"From Email Body Template" THEN
            HtmlFormated := true;

which later causes:
CreateMessage (codeunit 400 "SMTP Mail") will always have HtmlFormated = False and this leaves our emails without HTML body:
 if HtmlFormatted then
            AddBody(Body)
        else
            AddTextBody(Body);

End result is an email with a body like this:

![image](https://user-images.githubusercontent.com/34686682/72805559-7f111700-3c53-11ea-8403-1887568c1dec.png)

While fixing this, please add PostedDocNo parameter in EmailFileAndHtmlFromStream, so we could pass it to EmailFileInternal.

Thanks,
Radovan

**Comment by darjoo** [comment]
Hi @radovandokic,
The CreateMessage issue has been hotfixed in 15.2. However, if you're still experiencing that issue, please send us an email at bc-app-foundation@service.microsoft.com with the details and your tenant information.

Regarding the PostedDocNo, that would be a separate request.

**Comment by radovandokic** [comment]
Hi @darjoo, where to find that hotfix? I am using this image mcr.microsoft.com/businesscentral/sandbox:15.2.39558.0-ca

**Comment by darjoo** [comment]
The hotfix unfortunately does not roll out to onprem images.
Please use the Cloud sandbox for development with the hotfix.

**Comment by ivandjordjevic** [comment]
@darjoo Did you mean that this should be available on insider builds? 

bcinsider.azurecr.io/bcsandbox

**Comment by darjoo** [comment]
@ivandjordjevic 
Yes, it should have it. From what I read that repo contains the image for the next (insider) minor release, and as such, it should.
