### ISSUE TITLE
[Event Request] codeunit 17 "Gen. Jnl.-Post Reverse" - OnReverseOnBeforeFinishPosting new parameter 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5638]
Could we please have an additional parameter GLReg in event OnReverseOnBeforeFinishPosting in Codeunit 17?

Event:

local procedure OnReverseOnBeforeFinishPosting(var ReversalEntry: Record "Reversal Entry"; var ReversalEntry2: Record "Reversal Entry"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var GLReg: Record "G/L Register")

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
