### ISSUE TITLE
[Event Request] codeunit 5520 "Get Unplanned Demand" - OnBeforeOpenPlanningWindow + OnBeforeClosePlanningWindow

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5639]
Could we please have 2 events OnBeforeOpenPlanningWindow + OnBeforeClosePlanningWindow in Codeunit 17?

Code Example:
        // start kvspsa - Code Modification
        //OpenWindow(Text000, SalesLine.Count + ProdOrderComp.Count + ServLine.Count + JobPlanningLine.Count);
        RecCounter := SalesLine.Count + ProdOrderComp.Count + ServLine.Count + JobPlanningLine.Count;
        OnBeforeOpenPlanningWindow(RecCounter);
        OpenWindow(Text000, RecCounter);
        // stop kvspsa
        GetUnplannedSalesLine(Rec);
        GetUnplannedProdOrderComp(Rec);
        GetUnplannedAsmLine(Rec);
        GetUnplannedServLine(Rec);
        GetUnplannedJobPlanningLine(Rec);
        // start kvspsa - Event Raiser
        OnBeforeClosePlanningWindow(Rec, Window, NoOfRecords, i);
        // stop kvspsa
        Window.Close;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeOpenPlanningWindow(var RecCounter: Integer)
    begin
    end;

    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeClosePlanningWindow(var UnplannedDemand: Record "Unplanned Demand"; var Window: Dialog; NoOfRecords: Integer; var WorkedRecords: Integer)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
