### ISSUE TITLE
[Event Request] codeunit  427 ICInboxOutboxMgt - OnICPartnerRefTypeCaseElseOnCreateSalesLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5641]
Could we please have an event OnICPartnerRefTypeCaseElseOnCreateSalesLines in Codeunit 427 in function CreateSalesLines?

Code Example:
                "IC Partner Ref. Type"::"Charge (Item)":
                    begin
                        SalesLine.Type := SalesLine.Type::"Charge (Item)";
                        SalesLine.Validate("No.", "IC Partner Reference");
                    end;
                // start kvspsa - Event Raiser
                else
                    OnICPartnerRefTypeCaseElseOnCreateSalesLines(ICInboxSalesLine, SalesLine, SalesHeader);
            // stop kvspsa
            end;
            SalesLine."Currency Code" := SalesHeader."Currency Code";
            SalesLine.Description := Description;

Event:
    local procedure OnICPartnerRefTypeCaseElseOnCreateSalesLines(ICInboxSalesLine: Record "IC Inbox Sales Line"; var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
