### ISSUE TITLE
[Question] Adding a publisher on the beginning of every method.

### ISSUE THREAD

**Issue by pcucuk** [microsoft/ALAppExtensions#5642]
Would it make sense to add a publisher on the beginning of every method, no matter if it's external or not?

Here's the general idea:

```
global vars:
   SomeInt: Integer

procedure DoSomething(var Variable1, Variable2) output : Boolean
{
   OnBeforeDoSomething(var Variable1, Variable2, SomeInt, var output , IsHandled);
   IF NOT IsHandled THEN BEGIN
      IF SomeInt > 5 THEN BEGIN
         Variable1.Field := 'Value';
         output := true;
      END;
   END;
   EXIT(output);
}
```

This would allow us to integrate any of our custom processes into existing ones seamlessly.

Sometimes I'll want the _DoSomething_ procedure to do nothing, sometimes I'll want to have my own check against the value of _SomeInt_. Whatever a developer could thing of as far as _DoSomething_ goes they could implement. This isn't to say that this would be a replacement for other publishers throughout the procedure, but I believe it is important to be able to override a procedure - just like you can in most other programming languages.

**Comment by AlexanderYakunin** [comment]
We have no plans to follow this way.
