### ISSUE TITLE
[Event Request] codeunit  427 ICInboxOutboxMgt - OnAfterTransferFieldsOnCreatePurchLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5643]
Could we please have an event OnAfterTransferFieldsOnCreatePurchLines in Codeunit 427 in function CreatePurchLines?

Code Example:
        with ICInboxPurchLine do begin
            PurchLine.Init;
            PurchLine.TransferFields(ICInboxPurchLine);
            // start kvspsa - Event Raiser
            OnAfterTransferFieldsOnCreatePurchLines(ICInboxPurchLine, PurchLine);
            // stop kvspsa
            PurchLine."Document Type" := PurchHeader."Document Type";

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferFieldsOnCreatePurchLines(ICInboxPurchLine: Record "IC Inbox Purchase Line"; var PurchLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
