### ISSUE TITLE
[Event Request] codeunit  427 ICInboxOutboxMgt - OnICPartnerRefTypeCaseElseOnCreatePurchLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5644]
Could we please have an event OnICPartnerRefTypeCaseElseOnCreatePurchLines in Codeunit 427 in function CreatePurchLines?

Code Example:
                "IC Partner Ref. Type"::"Cross reference":
                    begin
                        PurchLine.Validate(Type, PurchLine.Type::Item);
                        PurchLine.Validate("Cross-Reference No.", "IC Partner Reference");
                    end;
                // start kvspsa - Event Raiser
                else
                    OnICPartnerRefTypeCaseElseOnCreatePurchLines(ICInboxPurchLine, PurchLine, PurchHeader);
            // stop kvspsa

            end;
            PurchLine."Currency Code" := PurchHeader."Currency Code";

Event:
    [IntegrationEvent(false, false)]
    local procedure OnICPartnerRefTypeCaseElseOnCreatePurchLines(ICInboxPurchLine: Record "IC Inbox Purchase Line"; var PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
