### ISSUE TITLE
[Event Request] codeunit  427 ICInboxOutboxMgt - OnAfterAssignFieldsOnCreatePurchLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5645]
Could we please have an event OnAfterAssignFieldsOnCreatePurchLines in Codeunit 427 in function CreatePurchLines?

Code Example:
                UpdatePurchLineReceiptShipment(PurchLine);
            end;
            PurchLine."Shortcut Dimension 1 Code" := '';
            PurchLine."Shortcut Dimension 2 Code" := '';

            // start kvspsa - Event Raiser
            OnAfterAssignFieldsOnCreatePurchLines(ICInboxPurchLine, PurchLine);
            // stop kvspsa
            DimMgt.SetICDocDimFilters(
              ICDocDim, DATABASE::"IC Inbox Purchase Line", "IC Transaction No.", "IC Partner Code", "Transaction Source", "Line No.");
            DimensionSetIDArr[1] := PurchLine."Dimension Set ID";
            DimensionSetIDArr[2] := DimMgt.CreateDimSetIDFromICDocDim(ICDocDim);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignFieldsOnCreatePurchLines(ICInboxPurchLine: Record "IC Inbox Purchase Line"; var PurchLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
