### ISSUE TITLE
[Event Request] codeunit  427 ICInboxOutboxMgt - OnAfterCreatePurchLinesOnAfterModify

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5646]
Could we please have an event OnAfterCreatePurchLinesOnAfterModify in Codeunit 427 in function CreatePurchLines?

Code Example:
            OnAfterCreatePurchLines(ICInboxPurchLine, PurchLine);
            PurchLine.Modify;
            // start kvspsa - Event Raiser
            OnAfterCreatePurchLinesOnAfterModify(ICInboxPurchLine, PurchLine);
            // stop kvspsa
        end;
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreatePurchLinesOnAfterModify(ICInboxPurchLine: Record "IC Inbox Purchase Line"; var PurchLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
