### ISSUE TITLE
[Event Request] codeunit  427 ICInboxOutboxMgt - OnBeforeICOutboxSalesLineDeleteOnMoveOutboxTransToHandledOutbox

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5647]
Could we please have an event OnBeforeICOutboxSalesLineDeleteOnMoveOutboxTransToHandledOutbox in Codeunit 427 in function MoveOutboxTransToHandledOutbox?

Code Example:
                if ICOutboxSalesLine.Find('-') then
                    repeat
                        HandledICOutboxSalesLine.TransferFields(ICOutboxSalesLine, true);
                        OnBeforeHandledICOutboxSalesLineInsert(HandledICOutboxSalesLine, ICOutboxSalesLine);
                        HandledICOutboxSalesLine.Insert;

                        MoveICDocDimToHandled(
                          DATABASE::"IC Outbox Sales Line", DATABASE::"Handled IC Outbox Sales Line", ICOutboxSalesHdr."IC Transaction No.",
                          ICOutboxSalesHdr."IC Partner Code", ICOutboxSalesHdr."Transaction Source", ICOutboxSalesLine."Line No.");
                        // start kvspsa - Event Raiser
                        OnBeforeICOutboxSalesLineDeleteOnMoveOutboxTransToHandledOutbox(ICOutboxSalesLine, HandledICOutboxSalesLine);
                        // stop kvspsa
                        ICOutboxSalesLine.Delete;
                    until ICOutboxSalesLine.Next = 0;
                ICOutboxSalesHdr.Delete;
            until ICOutboxSalesHdr.Next = 0;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeICOutboxSalesLineDeleteOnMoveOutboxTransToHandledOutbox(ICOutboxSalesLine: Record "IC Outbox Sales Line"; HandledICOutboxSalesLine: Record "Handled IC Outbox Sales Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
