### ISSUE TITLE
[Event Request] codeunit  5651 "Insurance Jnl.-Check Line" - OnBeforeCheckDimIDCombOnRunCheck

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5648]
Could we please have an event OnBeforeCheckDimIDCombOnRunCheck in Codeunit 5651 "Insurance Jnl.-Check Line" in function RunCheck?

Code Example:
        with InsuranceJnlLine do begin
            if "Insurance No." = '' then
                exit;
            TestField("Insurance No.");
            TestField("Document No.");
            TestField("Posting Date");
            TestField("FA No.");
            if CallNo = 0 then begin
                FASetup.Get;
                FASetup.TestField("Insurance Depr. Book");
            end;
            CallNo := 1;

            // start kvspsa - Event Raiser
            OnBeforeCheckDimIDCombOnRunCheck(InsuranceJnlLine);
            // stop kvspsa

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDimIDCombOnRunCheck(var InsuranceJnlLine: Record "Insurance Journal Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
