### ISSUE TITLE
[Event Request] codeunit  1011 "Job Jnl.-Check Line" - OnAfterCreateDimTableIDsJobJnlLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5649]
Could we please have an event OnAfterCreateDimTableIDsJobJnlLine in Codeunit 1011 "Job Jnl.-Check Line" in function CheckDim?

Code Example:
            TableID[3] := DATABASE::"Resource Group";
            No[3] := "Resource Group No.";
            // start kvspsa - Event Raiser
            OnAfterCreateDimTableIDsJobJnlLine(JobJnlLine, TableID, No);
            // stop kvspsa
            if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then begin

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDimTableIDsJobJnlLine(var JobJnlLine: Record "Job Journal Line"; var TableIDVar: array[10] of Integer; var NoVar: array[10] of Code[20])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
