### ISSUE TITLE
[Event Request] codeunit 1013 "Job Jnl.-Post Batch" - OnBeforeTestFieldDocumentNoOnRepeatPostLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5650]
Could we please have an event OnBeforeTestFieldDocumentNoOnRepeatPostLines in Codeunit 1013 "Job Jnl.-Post Batch" in function Code?

Code Example:
                if "Posting No. Series" = '' then begin
                    "Posting No. Series" := JobJnlBatch."No. Series";
                    //start kvspsa - Code Modification
                    //TestField("Document No.");
                    IsHandled := false;
                    DoTestField := true;
                    OnBeforeTestFieldDocumentNoOnRepeatPostLines(DoTestField, IsHandled);
                    if IsHandled and DoTestField then
                        TestField("Document No.");
                    // stop kvspsa
                end else
                    if not EmptyLine then

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestFieldDocumentNoOnRepeatPostLines(var DoTestField: Boolean; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
