### ISSUE TITLE
[Event Request] codeunit 1013 "Job Jnl.-Post Batch" - OnBeforeDeleteNonRecJnlLines new parameters 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5651]
Could we please have additional parameters in event OnBeforeDeleteNonRecJnlLines in Codeunit 1013?

Event:

OnBeforeDeleteNonRecJnlLines(JobJnlLine, JobJnlLine2, JobJnlLine3, JobJnlBatch, IsHandled);

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
