### ISSUE TITLE
Item Charge Assignment (Purch) - CreateSalesShptChargeAssgnt no longer works

### ISSUE THREAD

**Issue by tfbtrading** [microsoft/ALAppExtensions#5652]
We have code https://community.dynamics.com/business/f/dynamics-365-business-central-forum/377901/code-that-automatically-assigned-charges-worked-in-15-1-and-has-stopped-working-in-15-2-of-business-central documented here that creates item charge assignment. This has stopped working in 15.2 update without reporting errors at compile time or runtime. It just no longer creates an assignment.

**Comment by RomanZanizdra** [comment]
Hi @tfbtrading . I would like to suggest you to go through your code by yourself (may be using debugger) and identify the particular place and root cause why item charge assignments are not inserted. And if this is an application bug then please log it in the relevant support channel. Let's close the current issue for now.

**Comment by tfbtrading** [comment]
I have reviewed our code. I still believe that since the code works prior to an update and failed afterwards it is a genuine bug. We have traced it to the fact that it appears there is a delayed insert on the line. You can resolve the bug by first moving out of the row (forcing a line insert) and then back into it. For me the bug is that it doesn’t report any error and the code should actually first ensure the line is inserted and if not save that line.

Kind regards,

Russell Kallman
Sales & Operations Mgr
TFB Trading Australia Pty Ltd

**Comment by RomanZanizdra** [comment]
Hi @tfbtrading . It's very difficult to discuss words about code. I kindly ask you to show me the particular code and place where you think there is a problem.

**Comment by RomanZanizdra** [comment]
Hi @tfbtrading , any update from your side?

**Comment by RomanZanizdra** [comment]
@tfbtrading , I suggest to close current issue. Feel free to re-open it when there will be enough information to discuss or log a bug in a relevant support channel.
