### ISSUE TITLE
Purchase Line OnBeforeAssignHeaderValues

### ISSUE THREAD

**Issue by thomasbook** [microsoft/ALAppExtensions#5653]
Can we have  a OnBeforeAssignHeaderValues for the Validation of the No. field?

                **OnBeforeAssignHeaderValues(Rec, PurchHeader);**

                "System-Created Entry" := TempPurchLine."System-Created Entry";
                GetPurchHeader;
                InitHeaderDefaults(PurchHeader);
                UpdateLeadTimeFields;
                UpdateDates;

                OnAfterAssignHeaderValues(Rec, PurchHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
