### ISSUE TITLE
[Enum Request] Table 5956 Resource Skill- Field : 4 - "Assigned From" ; 5 - "Source Type"

### ISSUE THREAD

**Issue by Mahendarmyak** [microsoft/ALAppExtensions#5654]
Please add **Enum** for the Table **5956 "Resource Skill"**- Fields : **4 - "Assigned From" ; 5 - "Source Type"**

![image](https://user-images.githubusercontent.com/34544585/72870441-3ec29f00-3d0e-11ea-8958-dfda525fbd4b.png)

Thanks & Regards,
Mahendar.M

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
