### ISSUE TITLE
[Event Request] codeunit 1012 "Job Jnl.-Post Line" - OnBeforeHandleJobRegister

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5655]
Could we please have an event OnBeforeHandleJobRegister in Codeunit 1012 "Job Jnl.-Post Line" in function Code?

Code Example:
            if "Document Date" = 0D then
                "Document Date" := "Posting Date";

            // start kvspsa - Event Raiser
            OnBeforeHandleJobRegister(JobJnlLine);
            // stop kvspsa

            if JobReg."No." = 0 then begin
                JobReg.LockTable;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeHandleJobRegister(var JobJournalLine: Record "Job Journal Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
