### ISSUE TITLE
[Event Request] codeunit 1012 "Job Jnl.-Post Line" - OnAfterRunCode new parameter 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5656]
Could we please have additional parameters in event OnAfterRunCode in Codeunit 1012?

        OnAfterRunCode(JobJnlLine, JobJnlLine2, JobLedgEntryNo);  // Standard Event misses Variable JobJnlLine as parameter!!

Event:

    local procedure OnAfterRunCode(var JobJournalLine: Record "Job Journal Line"; JobJournalLine2: Record "Job Journal Line"; JobLedgEntryNo: Integer)
    begin
    end;

**Comment by AlexanderYakunin** [comment]
JobJnlLine2 is copy of JobJnlLine. Do you really need JobJnlLine?

**Comment by MiRo65** [comment]
ok, we have checked once more, and we decided to cancel this request because we can use JobJnlLine2.
Thank you.
