### ISSUE TITLE
[Event Request] codeunit 1012 "Job Jnl.-Post Line" - OnBeforeQtyPriceAndCostJobLedgEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5657]
Could we please have an event OnBeforeQtyPriceAndCostJobLedgEntry in Codeunit 1012 "Job Jnl.-Post Line" in function CreateJobLedgEntry?

Code Example:
        JobLedgEntry.Init;
        JobTransferLine.FromJnlLineToLedgEntry(JobJnlLine2, JobLedgEntry);

        // start kvspsa - Event Raiser
        IsHandled := false;
        OnBeforeQtyPriceAndCostJobLedgEntry(JobLedgEntry, JobJnlLine2, IsHandled);
        if not IsHandled then begin
            // stop kvspsa
            if JobLedgEntry."Entry Type" = JobLedgEntry."Entry Type"::Sale then begin
                JobLedgEntry.Quantity := -JobJnlLine2.Quantity;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeQtyPriceAndCostJobLedgEntry(var JobLedgerEntry: Record "Job Ledger Entry"; var JobJournalLine: Record "Job Journal Line"; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
