### ISSUE TITLE
[Event Request] codeunit 1012 "Job Jnl.-Post Line" - OnAfterSetJobLedgEntryGLAccountEntryType

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5658]
Could we please have an event OnAfterSetJobLedgEntryGLAccountEntryType in Codeunit 1012 "Job Jnl.-Post Line" in function CreateJobLedgEntry?

Code Example:
        with JobJnlLine2 do
            case Type of
                Type::Resource:
                    if "Entry Type" = "Entry Type"::Usage then
                        if ResLedgEntry.FindLast then begin
                            JobLedgEntry."Ledger Entry Type" := JobLedgEntry."Ledger Entry Type"::Resource;
                            JobLedgEntry."Ledger Entry No." := ResLedgEntry."Entry No.";
                        end;
                Type::Item:
                    begin
                        JobLedgEntry."Ledger Entry Type" := "Ledger Entry Type"::Item;
                        JobLedgEntry."Ledger Entry No." := "Ledger Entry No.";
                        JobLedgEntry."Serial No." := "Serial No.";
                        JobLedgEntry."Lot No." := "Lot No.";
                    end;
                Type::"G/L Account":
                    begin
                        JobLedgEntry."Ledger Entry Type" := JobLedgEntry."Ledger Entry Type"::" ";
                        if GLEntryNo > 0 then begin
                            JobLedgEntry."Ledger Entry Type" := JobLedgEntry."Ledger Entry Type"::"G/L Account";
                            JobLedgEntry."Ledger Entry No." := GLEntryNo;
                            GLEntryNo := 0;
                        end;
                        // start kvspsa - Event Raiser
                        OnAfterSetJobLedgEntryGLAccountEntryType(JobLedgEntry, JobJnlLine2);
                        // stop kvspsa
                    end;
            end;
        if JobLedgEntry."Entry Type" = JobLedgEntry."Entry Type"::Sale then begin

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetJobLedgEntryGLAccountEntryType(var JobLedgerEntry: Record "Job Ledger Entry"; var JobJournalLine: Record "Job Journal Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
