### ISSUE TITLE
[Event Request] codeunit 1012 "Job Jnl.-Post Line" - OnBeforeAssignItemJnlLineOnPostItem

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5659]
Could we please have an event OnBeforeAssignItemJnlLineOnPostItem in Codeunit 1012 "Job Jnl.-Post Line" in function PostItem?

Code Example:
                    if ApplyToJobContractEntryNo then
                        ItemJnlLine."Job Contract Entry No." := JobPlanningLine."Job Contract Entry No.";

                    // start kvspsa - Event Raiser
                    OnBeforeAssignItemJnlLineOnPostItem(JobJnlLine, JobJnlLine2, ItemJnlLine);
                    // stop kvspsa
                    ItemLedgEntry.LockTable;
                    ItemJnlLine2 := ItemJnlLine;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignItemJnlLineOnPostItem(var JobJournalLine: Record "Job Journal Line"; var JobJournalLine2: Record "Job Journal Line"; var ItemJournalLine: Record "Item Journal Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
