### ISSUE TITLE
[Event Request] codeunit 1001 "Job Post-Line" - OnBeforeJobJnlPostLineOnPostGenJnlLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5660]
Could we please have an event OnBeforeJobJnlPostLineOnPostGenJnlLine in Codeunit 1001 "Job Post-Line" in function PostGenJnlLine?

Code Example:
        JobTransferLine.FromGenJnlLineToJnlLine(GenJnlLine, JobJnlLine);

        // start kvspsa - Event Raiser
        OnBeforeJobJnlPostLineOnPostGenJnlLine(JobJnlLine, GenJnlLine, JobJnlPostLine);
        // stop kvspsa
        JobJnlPostLine.SetGLEntryNo(GLEntry."Entry No.");
        JobJnlPostLine.RunWithCheck(JobJnlLine);
        JobJnlPostLine.SetGLEntryNo(0);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeJobJnlPostLineOnPostGenJnlLine(var JobJnlLine: Record "Job Journal Line"; var GenJnlLine: Record "Gen. Journal Line"; var JobJnlPostLine: Codeunit "Job Jnl.-Post Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
