### ISSUE TITLE
[Event Request] codeunit 1001 "Job Post-Line" - OnBeforePostJobOnPurchaseLine new parameter 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5661]
Could we please have additional parameters (TempPurchaseLineJob, TempJobJournalLine, Sourcecode,) in event OnBeforePostJobOnPurchaseLine in Codeunit 1001?

        // start kvspsa - Event Raiser
        OnBeforePostJobOnPurchaseLine(PurchHeader, PurchInvHeader, PurchCrMemoHdr, PurchLine, JobJnlLine, TempPurchaseLineJob, TempJobJournalLine, Sourcecode, IsHandled);
        // stop kvspsa
        if IsHandled then
            exit;

Event:

    local procedure OnBeforePostJobOnPurchaseLine(var PurchHeader: Record "Purchase Header"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; var PurchLine: Record "Purchase Line"; var JobJnlLine: Record "Job Journal Line"; var TempPurchaseLineJob: Record "Purchase Line"; var TempJobJournalLine: Record "Job Journal Line"; var Sourcecode: Code[10]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
