### ISSUE TITLE
[Event Request] codeunit 1630 "Office Management" - OnBeforeGetStandardHandlerCodeunit

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5662]
Could we please have an event OnBeforeGetStandardHandlerCodeunit in Codeunit 1630 "Office Management" in function GetHandlerCodeunit?

Code Example:
        HostType := GetHostType;
        // start kvspsa - Event Raiser
        OnBeforeGetStandardHandlerCodeunit(OfficeAddinContext, HostType, ExternalHandler);
        if ExternalHandler > 0 then
            exit(ExternalHandler);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetStandardHandlerCodeunit(OfficeAddinContext: Record "Office Add-in Context"; HostType: Text; var HandlerCodeunit: Integer)
    begin
    end;

Thank you and kind regards

**Comment by StanPesotskiy** [comment]
There is already OnGetExternalHandlerCodeunit event:
```
codeunit 1630 "Office Management"
...
        OnGetExternalHandlerCodeunit(OfficeAddinContext, HostType, ExternalHandler);
        if ExternalHandler > 0 then
            exit(ExternalHandler);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
