### ISSUE TITLE
[Event Request] codeunit 99000778 OrderTrackingManagement - OnAfterSetVariant

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5663]
Could we please have an event OnAfterSetVariant in Codeunit 99000778 OrderTrackingManagement in function SetVariant?

Code Example:
    procedure SetVariant(var VariantVar: Variant)
    var
        JobUsageLink: Record "Job Usage Link";
        JobLedgEntry: Record "Job Ledger Entry";
    begin
        OnAfterSetVariant(VariantVar, ReservEntry, CaptionText);
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetVariant(var VariantVar: Variant; var ReservEntry: Record "Reservation Entry"; var CaptionText: Text)
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Procedure SetVariant does not exist in codeunit 99000778 OrderTrackingManagement.

**Comment by ChrisBlankDe** [comment]
This is part of a larger customization which allows to use dynamic records in order tracking.
Currently on page 99000822 "Order Tracking" there are set functions for different tables (SetSalesLine,SetPurchLine,SetItemLedgEntry,SetServLine,SetPlanningComponent,...). imho this is not easily extensible.
We have solved this as generic as possible with a SetVariantRec function:
```
    // page 99000822 "Order Tracking"
    // start kvspsa - Method added
    procedure SetVariantRec(VariantRec: Variant; CurrItemNoPar: Code[20]; CurrQuantityPar: Decimal; StartingDatePar: Date; EndingDatePar: Date)
    begin
        TrackingMgt.SetVariant(VariantRec);

        CurrItemNo := CurrItemNoPar;
        CurrQuantity := CurrQuantityPar;
        StartingDate := StartingDatePar;
        EndingDate := EndingDatePar;
    end;
    // stop kvspsa
```

Furthermore, we have added the necessary function to codeunit 99000778 OrderTrackingManagement. Furthermore, of course, we also added an event duch which can be used to handle record handling:
```
     // codeunit 99000778 OrderTrackingManagement
     // start kvspsa - Code Modification
    procedure SetVariant(var VariantVar: Variant)
    var
        JobUsageLink: Record "Job Usage Link";
        JobLedgEntry: Record "Job Ledger Entry";
    begin
        OnAfterSetVariant(VariantVar, ReservEntry, CaptionText);
    end;
    // stop kvspsa

    // start kvspsa - Event Publisher
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetVariant(var VariantVar: Variant; var ReservEntry: Record "Reservation Entry"; var CaptionText: Text)
    begin
    end;
    // stop kvspsa
```

To access this in an extnesion is quite simple:

A Page Action calls a function on the source record which looks like this:

```
    // Custom Extension Table
    procedure ShowTracking()
    var
        OrderTrackingLoc: Page "Order Tracking";
    begin
        OrderTrackingLoc.SetVariantRec(Rec, "No.", "Quantity (Base)", "Starting Date", "Ending Date");
        OrderTrackingLoc.RunModal();
    end;
```
through an eventsubscriber we can then react to this specific record and execute our code:

```
    // Custom Extension Codeunit
    [EventSubscriber(ObjectType::Codeunit, Codeunit::OrderTrackingManagement, 'OnAfterSetVariant', '', false, false)]
    local procedure OnAfterSetVariant(var VariantVar: Variant; var ReservEntry: Record "Reservation Entry"; var CaptionText: Text)
    var
        PSPBudgetLine: Record "KVSPSA Job Budget Line";
        DataTypeMgt: Codeunit "Data Type Management";
        ReservBudgetLine: Codeunit "KVSPSA Budgetline-Reserve";
        ReservEngineMgt: Codeunit "Reservation Engine Mgt.";
        RecRef: RecordRef;
    begin
        if not VariantVar.IsRecord() then
            exit;
        if not DataTypeMgt.GetRecordRef(VariantVar, RecRef) then
            exit;
        if RecRef.Number() = Database::"KVSPSA Job Budget Line" then begin
            RecRef.SetTable(PSPBudgetLine);
            PSPBudgetLine.Testfield(Type, PSPBudgetLine.Type::Item);
            ReservEntry."Source Type" := Database::"KVSPSA Job Budget Line";
            ReservEngineMgt.InitFilterAndSortingLookupFor(ReservEntry, false);
            ReservBudgetLine.FilterReservFor(ReservEntry, PSPBudgetLine);
            CaptionText := ReservBudgetLine.Caption(PSPBudgetLine);
        end;
    end;
```

i think many partners who have customized the order tracking would be happy about such a generic modification.

**Comment by AlexanderYakunin** [comment]
You definitely need to look into our latest preview code base for Reservation, it will simplify you conversion. There are many improvements for extensibility in this area.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
