### ISSUE TITLE
[Event Request] Table 5847 AverageCostCalcOverview - OnAfterSetItemFilters

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5664]
New Event for Table 5847 "Average Cost Calc. Overview" - OnAfterSetItemFilters

![image](https://user-images.githubusercontent.com/22153733/72877871-234d9900-3cfa-11ea-8e8f-d2cdcfc2febd.png)

Integration Event
OnAfterSetItemFilters
var ValueEntry: Record "Value Entry"; var AvgCostCalcOverview: Record "Average Cost Calc. Overview"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
