### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnBeforePostItemTrackingLineOnPostPurchLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5665]
Could we please have an event OnBeforePostItemTrackingLineOnPostPurchLine in Codeunit 90 "Purch.-Post" in function PostPurchLine?

Code Example:
            RemQtyToBeInvoiced := "Qty. to Invoice";
            RemQtyToBeInvoicedBase := "Qty. to Invoice (Base)";
            
            // Job Credit Memo Item Qty Check
            if IsCreditDocType then
                if ("Job No." <> '') and (Type = Type::Item) and ("Qty. to Invoice" <> 0) then
                    JobPostLine.CheckItemQuantityPurchCredit(PurchHeader, PurchLine);
            // start kvspsa 
            OnBeforePostItemTrackingLineOnPostPurchLine(PurchHeader, PurchLine);
            // stop kvspsa

            PostItemTrackingLine(PurchHeader, PurchLine);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemTrackingLineOnPostPurchLine(PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
