### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnCaseType3OnPostPurchLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5666]
Could we please have an event OnCaseType3OnPostPurchLine in Codeunit 90 "Purch.-Post" in function PostPurchLine?

Code Example:
            case Type of
                Type::"G/L Account":
                    PostGLAccICLine(PurchHeader, PurchLine, ICGenJnlLineNo);
                Type::Item:
                    PostItemLine(PurchHeader, PurchLine, TempDropShptPostBuffer);
                3:
                    // start kvspsa - Code Modification
                    //PostResourceLine(PurchHeader, PurchLine);
                    OnCaseType3OnPostPurchLine(PurchHeader, PurchLine, xPurchLine, PurchInvHeader, PurchCrMemoHeader, PurchRcptHeader, ReturnShptHeader);
                // stop kvspsa
                Type::"Charge (Item)":
                    PostItemChargeLine(PurchHeader, PurchLine);
            end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnCaseType3OnPostPurchLine(PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line";PurchInvHeader: Record "Purch. Inv. Header"; PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; PurchRcptHeader: Record "Purch. Rcpt. Header"; ReturnShptHeader: Record "Return Shipment Header")
    begin
    end;

Thank you and kind regards

**Comment by MiRo65** [comment]
Hi,
I think enlarging the existing standard event PostResourceLine by these additional parameters whould helb us of course:  xPurchLine, PurchInvHeader, PurchCrMemoHeader, PurchRcptHeader, ReturnShptHeader.

Thank you.

Kind regards
Michael

**Comment by ChrisBlankDe** [comment]
The new Example looks like this (Purch.-Post.Codeunit.al):
```
    local procedure PostResourceLine(PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        // start kvspsa - Code Modification
        // PostResourceLine(PurchHeader, PurchLine);
        //OnBeforePostResourceLine(PurchaseHeader, PurchaseLine, IsHandled);
        OnBeforePostResourceLine(PurchaseHeader, PurchaseLine, xPurchLine, PurchInvHeader, PurchCrMemoHeader, PurchRcptHeader, ReturnShptHeader, IsHandled);
        // stop kvspsa
        if not IsHandled then
            Error(CannotPurchaseResourcesErr);
    end;
[...]
    [IntegrationEvent(false, false)]
    // start kvspsa - Code Modification
    // local procedure OnBeforePostResourceLine(PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    local procedure OnBeforePostResourceLine(PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var xPurchLine: Record "Purchase Line"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; var PurchRcptHeader: Record "Purch. Rcpt. Header"; var ReturnShptHeader: Record "Return Shipment Header"; var IsHandled: Boolean)
    // stop kvspsa
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
As we are implementing purchase of resources, this event is not needed. Please follow latest code base.
