### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterCreateJobPurchLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5667]
Could we please have an event OnAfterCreateJobPurchLine in Codeunit 90 "Purch.-Post" in function PostGLAccICLine?

Code Example:
        if (PurchLine."No." <> '') and not PurchLine."System-Created Entry" then begin
            GLAcc.Get(PurchLine."No.");
            GLAcc.TestField("Direct Posting");
            if (PurchLine."Job No." <> '') and (PurchLine."Qty. to Invoice" <> 0) then begin
                CreateJobPurchLine(JobPurchLine, PurchLine, PurchHeader."Prices Including VAT");
                // start kvspsa - Event Raiser
                OnAfterCreateJobPurchLine(JobPurchLine, PurchLine);
                // stop kvspsa
                JobPostLine.PostJobOnPurchaseLine(PurchHeader, PurchInvHeader, PurchCrMemoHeader, JobPurchLine, SrcCode);
            end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateJobPurchLine(var JobPurchaseLine: Record "Purchase Line"; PurchaseLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
