### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterWhseJnlPostLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5668]
Could we please have an event OnAfterWhseJnlPostLine in Codeunit 90 "Purch.-Post" in function PostItemJnlLineWhseLine?

Code Example:
                WhseJnlPostLine.Run(TempWhseJnlLine2);
                if RevertWarehouseEntry(TempWhseJnlLine2, PurchLine."Job No.", PostBefore) then
                    WhseJnlPostLine.Run(TempWhseJnlLine2);
                // start kvspsa - Event Raiser
                OnAfterWhseJnlPostLine(TempWhseJnlLine3, PurchLine);
            // stop kvspsa
            until TempWhseJnlLine2.Next = 0;
        TempWhseTrackingSpecification.DeleteAll;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterWhseJnlPostLine(var WarehouseJournalLine: Record "Warehouse Journal Line"; PurchaseLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
