### ISSUE TITLE
[Event Request] New Event in Table 5804 AvgCostAdjmtEntryPoint - OnAfterSetAvgCostAjmtFilter

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5669]
New Event in Table 5804 "Avg. Cost Adjmt. Entry Point" - OnAfterSetAvgCostAjmtFilter

![image](https://user-images.githubusercontent.com/22153733/72881194-978b3b00-3d00-11ea-9887-085ac1ae8878.png)

Integration Event
OnAfterSetAvgCostAjmtFilter
var AvgCostAdjmtPoint: Record ""Avg. Cost Adjmt. Entry Point"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
