### ISSUE TITLE
Could the procedure SetSumLinesFilter in table 5767 "Warehouse Activity Line" be set to external?

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#5670]
In table 5767 "Warehouse Activity Line" procedure `SetSumLinesFilter` is [Scope('OnPrem')].
Could this be removed?
Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
