### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforePostJob

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#5671]
Please add a new publisher event to the function UpdateDefaultDim as follows:

```
LOCAL PostJob(GenJnlLine : Record "Gen. Journal Line";GLEntry : Record "G/L Entry")
//>> Start New Publisher Call
OnBeforePostJob(GenJnlLine, GLEntry, JobLine);
//<< End New Publisher Call
IF JobLine THEN BEGIN
  JobLine := FALSE;
  JobPostLine.PostGenJnlLine(GenJnlLine,GLEntry);
END;
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforePostJob(GenJnlLine : Record "Gen. Journal Line";GLEntry : Record "G/L Entry";IsJobLine : Boolean)
```

**Comment by AndriiPochekailov** [comment]
Dear BaseApp team,

I'd like to join in to this request by asking your to also consider implementing "IsHandled" pattern here similar to how it's done in PostVAT procedure:
![GenJnlPostLine - PostVAT](https://user-images.githubusercontent.com/42442951/73277545-ff56ef80-41f2-11ea-901a-dcfe087d9b0d.png)

Thanks.

**Comment by ptijsma** [comment]
Hi Andrii,

This is in fact handled in a similar way right?
If you set JobLine to FALSE in the subscriber, you achieve the exact same thing, except that it's not explicitly using an IsHandled variable by name.

Regards,
Peter

**Comment by AndriiPochekailov** [comment]
Hi ptijsma,
Thank you for you comment. Actually you are right, I didn't realize it.
@microsoft please ignore my comments to this issue.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
