### ISSUE TITLE
Event Request codeunit 99000813 "Carry Out Action": OnAfterFindTempProdOrder

### ISSUE THREAD

**Issue by lukas-pfeifhofer** [microsoft/ALAppExtensions#5672]
In codeunit 99000813 "Carry Out Action" please insert a new event in procedure InsertProdOrder():
````
    begin
        Item.Get(ReqLine."No.");
        MfgSetup.Get();
        if FindTempProdOrder(ReqLine) then
            HeaderExist := ProdOrder.Get(TempProductionOrder.Status, TempProductionOrder."No.");
       // >>>
	   OnAfterFindTempProdOrder(ReqLine, ProdOrder, HeaderExists);
       // <<<
````
The parameter `ProdOrder` should be passed by reference (VAR).

**Comment by lukas-pfeifhofer** [comment]
… and also the parameter `HeaderExists` should be passed by reference (VAR).
The definition of the new event should looks like:

    [IntegrationEvent(false, false)]
    local procedure OnAfterFindTempProdOrder(var ReqLine: Record "Requisition Line"; var ProdOrder: Record "Production Order"; var HeaderExists: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
