### ISSUE TITLE
Event Request codeunit 99000774 "Calculate Routing Line": OnBeforeScheduleRoutingLine

### ISSUE THREAD

**Issue by lukas-pfeifhofer** [microsoft/ALAppExtensions#5673]
In codeunit  99000774 "Calculate Routing Line" please change the parameters of the event `OnBeforeScheduleRoutingLine`: add a new parameter `IsHandled`.

The new definition of the event should be: 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeScheduleRoutingLine(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var IsHandled: Boolean)
    begin
    end;

The new code should looks like:

        OnBeforeScheduleRoutingLine(ProdOrderRoutingLine, IsHandled);

        if not IsHandled then
            if ProdOrderRoutingLine."Schedule Manually" then
                CalculateRoutingLineFixed
            else begin
                if Direction = Direction::Backward then
                    CalcRoutingLineBack(CalcStartEndDate)
                else
                    CalcRoutingLineForward(CalcStartEndDate);
            end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
