### ISSUE TITLE
Event Request codeunit 99000773 "Calculate Prod. Order": OnBeforeCalcStartEndDate

### ISSUE THREAD

**Issue by lukas-pfeifhofer** [microsoft/ALAppExtensions#5674]
In codeunit 99000773 "Calculate Prod. Order" please insert a new event in procedure `CalculateRoutingFromActual`:

        repeat
            // >>>
	        OnCalculateRoutingFromActualOnBeforeCalcStartEndDate(ProdOrderRoutingLine, CalcStartEnd);
            // <<<
            if CalcStartEndDate and not ProdOrderRoutingLine."Schedule Manually" then
                if ((Direction = Direction::Forward) and (ProdOrderRoutingLine."Previous Operation No." <> '')) or
                   ((Direction = Direction::Backward) and (ProdOrderRoutingLine."Next Operation No." <> ''))
                then begin
                    ProdOrderRoutingLine."Starting Time" := 0T;
                    ProdOrderRoutingLine."Starting Date" := 0D;
                    ProdOrderRoutingLine."Ending Time" := 235959T;
                    ProdOrderRoutingLine."Ending Date" := CalendarMgt.GetMaxDate;
                end;
            CalculateRoutingLine.CalculateRoutingLine(ProdOrderRoutingLine, Direction, CalcStartEndDate);
            CalcStartEndDate := true;
        until ProdOrderRoutingLine.Next = 0;

The definition of the new event should looks like:

    [IntegrationEvent(false, false)]
    local procedure OnCalculateRoutingFromActualOnBeforeCalcStartEndDate(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var CalcStartEndDate: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
