### ISSUE TITLE
Event Request codeunit 99000854 "Inventory Profile Offsetting": OnSetAcceptActionOnBeforeAcceptActionMsg

### ISSUE THREAD

**Issue by lukas-pfeifhofer** [microsoft/ALAppExtensions#5675]
In codeunit 99000854 "Inventory Profile Offsetting" please insert a new event in procedure `SetAcceptAction`:

                    // >>>
                    OnSetAcceptActionOnBeforeAcceptActionMsg(ReqLine, AcceptActionMsg);
                    // <<<

                    if AcceptActionMsg then
                        AcceptActionMsg := PlanningTransparency.ReqLineWarningLevel(ReqLine) = 0;

                    if not AcceptActionMsg then begin
                        "Accept Action Message" := false;
                        Modify;
                    end;

The definition of the new event should looks like:

    [IntegrationEvent(false, false)]
    local procedure OnSetAcceptActionOnBeforeAcceptActionMsg(var RequisitionLine: Record "Requisition Line"; var AcceptActionMsg: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
