### ISSUE TITLE
[Event Request] New Event in Table 5804 AvgCostAdjmtEntryPoint - OnAfterValuationExistsGetItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5676]
New Event in Table 5804 "Avg. Cost Adjmt. Entry Point" - OnAfterValuationExistsGetItem

![image](https://user-images.githubusercontent.com/22153733/72891552-c4e1e400-3d14-11ea-8762-b97a7c3e1825.png)

This is to be able to temporarily change the "Costing Method" on the Item variable.

Integration Event
OnAfterValuationExistsGetItem
var Item: Record Item; ValueEntry: Record "Value Entry"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
