### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterPostItemJnlLineBeforeJobPost

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5677]
Could we please have an event OnAfterPostItemJnlLineBeforeJobPost in Codeunit 90 "Purch.-Post" in function PostItemJnlLineJobConsumption?

Code Example:
                ItemJnlPostLine.RunPostWithReservation(ItemJournalLine, TempReservationEntry);

                // start kvspsa - Code Modification
                IsHandled := false;
                OnAfterPostItemJnlLineBeforeJobPost(PurchHeader, PurchInvHeader, PurchCrMemoHeader, PurchRcptHeader, ReturnShptHeader, PurchLine, SrcCode, QtyToBeReceived, IsHandled);
                if IsHandled then
                    exit;
                // stop kvspsa

                if QtyToBeInvoiced <> 0 then begin
                    "Qty. to Invoice" := QtyToBeInvoiced;
                    JobPostLine.PostJobOnPurchaseLine(PurchHeader, PurchInvHeader, PurchCrMemoHeader, PurchLine, SrcCode);
                end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterPostItemJnlLineBeforeJobPost(var PurchaseHeader: Record "Purchase Header"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; var PurchRcptHeader: Record "Purch. Rcpt. Header"; var ReturnShipmentHeader: Record "Return Shipment Header"; PurchaseLine: Record "Purchase Line"; SourceCode: Code[10]; QtyToBeReceived: Decimal; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
