### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterPurchRcptLineTestFieldsOnPostItemTrackingForReceipt

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5678]
Could we please have an event OnAfterPurchRcptLineTestFieldsOnPostItemTrackingForReceipt in Codeunit 90 "Purch.-Post" in function PostItemTrackingForReceipt?

Code Example:
                    PurchRcptLine.TestField("Variant Code", PurchLine."Variant Code");
                    PurchRcptLine.TestField("Prod. Order No.", PurchLine."Prod. Order No.");
                    // start kvspsa - Event Raiser
                    OnAfterPurchRcptLineTestFieldsOnPostItemTrackingForReceipt(PurchRcptLine, PurchLine);
                    // stop kvspsa
                    UpdateQtyToBeInvoicedForReceipt(
                      QtyToBeInvoiced, QtyToBeInvoicedBase,
                      TrackingSpecificationExists, PurchLine, PurchRcptLine, TempTrackingSpecification);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterPurchRcptLineTestFieldsOnPostItemTrackingForReceipt(PurchRcptLine: Record "Purch. Rcpt. Line"; PurchLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
