### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterUpdateInvoicedQtyOnPurchRcptLine new parameter 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5679]
Could we please have additional parameter (PurchHeader) in event OnAfterUpdateInvoicedQtyOnPurchRcptLine in Codeunit 90?

                    // start kvspsa - Event Raiser - Need additional parameter "PurchHeader"!
                    OnAfterUpdateInvoicedQtyOnPurchRcptLineKVSPSA(
                      PurchHeader, PurchInvHeader, PurchCrMemoHeader, PurchRcptHeader, ReturnShptHeader, PurchRcptLine, PurchLine, TempTrackingSpecification, TrackingSpecificationExists,
                      QtyToBeInvoiced, QtyToBeInvoicedBase);
                    // stop kvspsa

Event:

    local procedure OnAfterUpdateInvoicedQtyOnPurchRcptLine(PurchHeader: Record "Purchase Header"; PurchInvHeader: Record "Purch. Inv. Header"; PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; PurchRcptHeader: Record "Purch. Rcpt. Header"; ReturnShptHeader: Record "Return Shipment Header"; PurchRcptLine: Record "Purch. Rcpt. Line"; PurchaseLine: Record "Purchase Line"; TempTrackingSpecification: Record "Tracking Specification" temporary; TrackingSpecificationExists: Boolean; QtyToBeInvoiced: Decimal; QtyToBeInvoicedBase: Decimal)
    begin
    end;

**Comment by AlexanderYakunin** [comment]
We already have this variable here
        OnAfterUpdateInvoicedQtyOnPurchRcptLine(
          PurchInvHeader, PurchRcptLine, PurchaseLine, TempTrackingSpecification, TrackingSpecificationExists,
          QtyToBeInvoiced, QtyToBeInvoicedBase, PurchaseHeader, SuppressCommit);
