### ISSUE TITLE
[Event Request] Codeunit 415 - Release Purchase Document - OnAfterRelease

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/ALAppExtensions#568]
Dear dev. team,

First off: this is not the same event as the existing OnAfterReleasePurchaseDoc or OnAfterManualReleasePurchaseDoc, but instead this is intended for the Release function. Perhaps the name for the event could be changed if not clear enough.

We would like to request the following event-publisher in Codeunit 415, that should be called at the end of the Release function:

```pascal
Release(VAR PurchHeader : Record "Purchase Header";PurchLine : Record "Purchase Line";RealRelease : Boolean;OriginatingFromSubform : Boolean)
...

OnAfterRelease(PurchHeader, PurchLine, RealRelease, OriginatingFromSubform); // ** New event
```

The signature for this event-publisher would be as follows:

```pascal
LOCAL [IntegrationEvent] OnAfterRelease(VAR PurchHeader : Record "Purchase Header";PurchLine : Record "Purchase Line";RealRelease : Boolean;OriginatingFromSubform : Boolean)
```

**Comment by AlexanderYakunin** [comment]
We don't have Release function in COD415. Pleas make sure you base your requests on BC code base.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.

**Comment by rvanbekkum** [comment]
@AlexanderYakunin @JesperSchulz My apologies, the `Release` procedure is part of the NL version/localization.
Could the event publisher be added to this procedure?

**Comment by rvanbekkum** [comment]
@JesperSchulz Could this issue be reopened?

**Comment by AlexanderYakunin** [comment]
We need to understand why do we have alternative release function for NL localization. This is definetely not a local functionality and not anyhow connected with legislation. If we implement event here, we will block future possibility of consolidation. Can you help us understand what is the purpose of this function and why you cannot use Code funtcion in this codeunit?

**Comment by AlexanderYakunin** [comment]
I see it now, this is legacy implementation of totals in Purch. Credit Memo, it can be replaced by actual implementation we already have and aligned with W1.

**Comment by rvanbekkum** [comment]
Yes, it did seem out of place, it does not look like there is really any localization-specific functionality here apart from the function being used for the totals in invoices or cr. memos pages (which is not part of W1 at the moment).

In our old NAV2018 implementation we hooked into this function as well, because from this function documents could be released as well. So that's why we originally also requested to have eventing added here for our extensions to hook into.

If this can be phased out and alligned with W1, for example with a next major release, then this would be ok as well.
Is this what you are planning to do?
