### ISSUE TITLE
[Event Request] codeunit 99000833 "Req. Line-Reserve" - OnBeforeTransferReservationsReqLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5680]
Could we please have an event OnBeforeTransferReservationsReqLine in Codeunit 99000833 "Req. Line-Reserve" in function TransferReqLineToReqLine?

Code Example:
        NewReqLine.TestField("No.", OldReqLine."No.");
        NewReqLine.TestField("Variant Code", OldReqLine."Variant Code");
        NewReqLine.TestField("Location Code", OldReqLine."Location Code");

        // start kvspsa - Event Raiser
        OnBeforeTransferReservationsReqLine(OldReservEntry, OldReqLine, NewReqLine);
        // stop kvspsa

        if TransferAll then begin
            OldReservEntry.SetRange("Source Subtype", 0);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationsReqLine(var OldReservEntry: Record "Reservation Entry"; var OldReqLine: Record "Requisition Line"; var NewReqLine: Record "Requisition Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
