### ISSUE TITLE
[Event Request] codeunit 99000833 "Req. Line-Reserve" - OnBeforeTransferReservationsPurchLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5681]
Could we please have an event OnBeforeTransferReservationsPurchLine in Codeunit 99000833 "Req. Line-Reserve" in function TransferReqLineToPurchLine?

Code Example:
        PurchLine.TestField("No.", OldReqLine."No.");
        PurchLine.TestField("Variant Code", OldReqLine."Variant Code");
        PurchLine.TestField("Location Code", OldReqLine."Location Code");
        // start kvspsa - Event Raiser
        OnBeforeTransferReservationsPurchLine(OldReservEntry, OldReqLine, PurchLine);
        // stop kvspsa

        OldReservEntry.TransferReservations(
          OldReservEntry, OldReqLine."No.", OldReqLine."Variant Code", OldReqLine."Location Code",
          TransferAll, TransferQty, PurchLine."Qty. per Unit of Measure",
          DATABASE::"Purchase Line", PurchLine."Document Type", PurchLine."Document No.", '', 0, PurchLine."Line No.");

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationsPurchLine(var OldReservEntry: Record "Reservation Entry"; var OldReqLine: Record "Requisition Line"; var PurchLine: Record "Purchase Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
