### ISSUE TITLE
[Event Request] codeunit 99000833 "Req. Line-Reserve" - OnBeforeTransferReservationsProdOrderLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5682]
Could we please have an event OnBeforeTransferReservationsProdOrderLine in Codeunit 99000833 "Req. Line-Reserve" in function TransferPlanningLineToPOLine?

Code Example:
        NewProdOrderLine.TestField("Item No.", OldReqLine."No.");
        NewProdOrderLine.TestField("Variant Code", OldReqLine."Variant Code");
        NewProdOrderLine.TestField("Location Code", OldReqLine."Location Code");
        // start kvspsa - Event Raiser
        OnBeforeTransferReservationsProdOrderLine(OldReservEntry, OldReqLine, NewProdOrderLine);
        // stop kvspsa
        OldReservEntry.TransferReservations(
          OldReservEntry, OldReqLine."No.", OldReqLine."Variant Code", OldReqLine."Location Code",
          TransferAll, TransferQty, NewProdOrderLine."Qty. per Unit of Measure",
          DATABASE::"Prod. Order Line", NewProdOrderLine.Status, NewProdOrderLine."Prod. Order No.", '', NewProdOrderLine."Line No.", 0);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationsProdOrderLine(var OldReservEntry: Record "Reservation Entry"; var OldReqLine: Record "Requisition Line"; var NewProdOrderLine: Record "Prod. Order Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
