### ISSUE TITLE
[Event Request] codeunit 99000833 "Req. Line-Reserve" - OnBeforeTransferReservationsAsmHeader

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5683]
Could we please have an event OnBeforeTransferReservationsAsmHeader in Codeunit 99000833 "Req. Line-Reserve" in function TransferPlanningLineToAsmHdr?

Code Example:
        NewAsmHeader.TestField("Item No.", OldReqLine."No.");
        NewAsmHeader.TestField("Variant Code", OldReqLine."Variant Code");
        NewAsmHeader.TestField("Location Code", OldReqLine."Location Code");
        // start kvspsa - Event Raiser
        OnBeforeTransferReservationsAsmHeader(OldReservEntry, OldReqLine, NewAsmHeader);
        // stop kvspsa
        OldReservEntry.TransferReservations(
          OldReservEntry, OldReqLine."No.", OldReqLine."Variant Code", OldReqLine."Location Code",
          TransferAll, TransferQty, NewAsmHeader."Qty. per Unit of Measure",
          DATABASE::"Assembly Header", NewAsmHeader."Document Type", NewAsmHeader."No.", '', 0, 0);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationsAsmHeader(var OldReservEntry: Record "Reservation Entry"; var OldReqLine: Record "Requisition Line"; var NewAsmHeader: Record "Assembly Header")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
