### ISSUE TITLE
[Event Request] codeunit 99000845 "Reservation Management" - OnBeforeCreateReservation new parameter 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5684]
Could we please have additional parameters (Description, ExpectedDate, Quantity, QuantityBase) in event OnBeforeCreateReservation in Codeunit 99000845?

        //OnBeforeCreateReservation(TrackingSpecification, CalcReservEntry, CalcItemLedgEntry);

        // start kvspsa - Event Raiser
        OnBeforeCreateReservation(TrackingSpecification, CalcReservEntry, CalcItemLedgEntry, Description, ExpectedDate, Quantity, QuantityBase);
        // stop kvspsa

Event:

    local procedure OnBeforeCreateReservation(var TrkgSpec: Record "Tracking Specification"; var ReservEntry: Record "Reservation Entry"; var ItemLedgEntry: Record "Item Ledger Entry"; Description: Text[100]; ExpectedDate: Date; Quantity: Decimal; QuantityBase: Decimal)
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Please check latest preview code, we already have new event just after old one:

OnCreateReservation(SourceRecRef, TrackingSpecification, CalcReservEntry, Description, ExpectedDate, Quantity, QuantityBase);
