### ISSUE TITLE
[Event Request] codeunit 99000845 "Reservation Management" - OnSourceTypeCaseElseOnCalculateRemainingQty

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5685]
Could we please have an event OnSourceTypeCaseElseOnCalculateRemainingQty in Codeunit 99000845 "Reservation Management" in function CalculateRemainingQty?

Code Example:
            DATABASE::"Job Planning Line":
                begin
                    ForJobPlanningLine.CalcFields("Reserved Quantity", "Reserved Qty. (Base)");
                    RemainingQty := ForJobPlanningLine."Remaining Qty." - Abs(ForJobPlanningLine."Reserved Quantity");
                    RemainingQtyBase := ForJobPlanningLine."Remaining Qty. (Base)" - Abs(ForJobPlanningLine."Reserved Qty. (Base)");
                end;
            // start kvspsa - Code Modification
            else begin
                    IsHandled := false;
                    OnSourceTypeCaseElseOnCalculateRemainingQty(CalcReservEntry, RemainingQty, RemainingQtyBase, IsHandled);
                    if not IsHandled then
                        Error(Text003); // Standard-Error Message
                end;
        //else
        //    Error(Text003);
        // stop kvspsa
        end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnSourceTypeCaseElseOnCalculateRemainingQty(CalcReservEntry: Record "Reservation Entry"; var RemainingQty: Decimal; var RemainingQtyBase: Decimal; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Here is how this functions looks like after refactoring. We have no CASE statement here anymore, everything works on source table subscriber model.

    procedure CalculateRemainingQty(var RemainingQty: Decimal; var RemainingQtyBase: Decimal)
    begin
        CalcReservEntry.TestField("Source Type");

        OnCalculateRemainingQty(SourceRecRef, CalcReservEntry, RemainingQty, RemainingQtyBase);
    end;
