### ISSUE TITLE
[Event Request] codeunit 99000845 "Reservation Management" - OnAfterInitItemLedgerEntryFilter

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5686]
Could we please have an event OnAfterInitItemLedgerEntryFilter in Codeunit 99000845 "Reservation Management" in function InitFilter?

Code Example:
        case EntryID of
            1:
                begin // Item Ledger Entry
                    CalcItemLedgEntry.Reset;
                    CalcItemLedgEntry.SetCurrentKey("Item No.", Open, "Variant Code", Positive, "Location Code");
                    CalcItemLedgEntry.SetRange("Item No.", CalcReservEntry."Item No.");
                    CalcItemLedgEntry.SetRange(Open, true);
                    CalcItemLedgEntry.SetRange("Variant Code", CalcReservEntry."Variant Code");
                    CalcItemLedgEntry.SetRange(Positive, Positive);
                    CalcItemLedgEntry.SetRange("Location Code", CalcReservEntry."Location Code");
                    CalcItemLedgEntry.SetRange("Drop Shipment", false);
                    if FieldFilterNeeded(CalcReservEntry, Positive, 0) then
                        CalcItemLedgEntry.SetFilter("Lot No.", GetFieldFilter);
                    if FieldFilterNeeded(CalcReservEntry, Positive, 1) then
                        CalcItemLedgEntry.SetFilter("Serial No.", GetFieldFilter);
                    // start kvspsa - Event Raiser
                    OnAfterInitItemLedgerEntryFilter(CalcItemLedgEntry);
                    // stop kvspsa
                end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterInitItemLedgerEntryFilter(var CalcItemLedgEntry: Record "Item Ledger Entry")
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Code above does not exist anymore. Please check in preview version (=16.0)

You already have this event in ItemLedgerEntry.SetReservationFilters(ReservEntry);
