### ISSUE TITLE
[Event Request] codeunit 86 "Sales-Quote to Order" - OnBeforeDeleteSalesQuote new parameter 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5687]
Could we please have additional parameter (SalesQuoteLine) in event OnBeforeDeleteSalesQuote in Codeunit 86?

        //OnBeforeDeleteSalesQuote(Rec, SalesOrderHeader, IsHandled);
        // start kvspsa - Event Raiser
        OnBeforeDeleteSalesQuoteKVSPSA(Rec, SalesOrderHeader, SalesQuoteLine, IsHandled);
        // stop kvspsa

Event:

    local procedure OnBeforeDeleteSalesQuote(var QuoteSalesHeader: Record "Sales Header"; var OrderSalesHeader: Record "Sales Header"; var SalesQuoteLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
