### ISSUE TITLE
[Event Request] codeunit 5051 SegManagement - OnBeforeInsertSegmentLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5688]
Could we please have an event OnBeforeInsertSegmentLine in Codeunit 5051 SegManagement in function LogDocument?

Code Example:
        TempSegmentLine."Salesperson Code" := SalespersonCode;
        TempSegmentLine."Opportunity No." := OpportunityNo;
        // start kvspsa - Event Raiser
        OnBeforeInsertSegmentLine(TempSegmentLine);
        // stop kvspsa
        TempSegmentLine.Insert;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertSegmentLine(var SegmentLine: Record "Segment Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
