### ISSUE TITLE
[Event Request] codeunit 5988 "Serv-Documents Mgt." - OnBeforePostJobJnlLineQtyToShipOnPostDocumentLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5689]
Could we please have an event OnBeforePostJobJnlLineQtyToShipOnPostDocumentLines in Codeunit 5988 "Serv-Documents Mgt." in function PostDocumentLines?

Code Example:
                    if Consume and ("Document Type" = "Document Type"::Order) then begin
                      //start kvs
                      OnBeforePostJobJnlLineQtyToShipOnPostDocumentLines();
                       //stop kvs
                      if ServPostingJnlsMgt.PostJobJnlLine(ServHeader, ServLine, RemQtyToBeConsumed) then
                        UpdateServiceLedgerEntry(NextServLedgerEntryNo - 1)
                      else
                        if (Type = Type::Resource) and (RemQtyToBeConsumed <> 0) then
                          ServPostingJnlsMgt.PostResJnlLineConsume(ServLine, ServShptHeader);
                    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostJobJnlLineQtyToShipOnPostDocumentLines()
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
