### ISSUE TITLE
[Event Request] codeunit 5988 "Serv-Documents Mgt." - OnAfterFillInvPostingBufferOnPostDocumentLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5690]
Could we please have an event OnAfterFillInvPostingBufferOnPostDocumentLines in Codeunit 5988 "Serv-Documents Mgt." in function PostDocumentLines?

Code Example:
                    if (Type <> Type::" ") and ("Qty. to Invoice" <> 0) then
                        // Copy sales to buffer
                        ServAmountsMgt.FillInvPostingBuffer(InvPostingBuffer, ServLine, ServiceLineACY, ServHeader);

                    // start kvspsa - Event Raiser
                    OnAfterFillInvPostingBufferOnPostDocumentLines(ServHeader, ServLine);
                    // stop kvspsa  

                    // prepare posted document lines
                    if Ship then
                        PrepareShipmentLine(TempServiceLine, WarrantyNo);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillInvPostingBufferOnPostDocumentLines(var ServiceHeader: Record "Service Header"; var ServiceLine: Record "Service Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
