### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - OnBeforeCopyCheckSCDimToTempSCDim

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5692]
Could we please have an event OnBeforeCopyCheckSCDimToTempSCDim in Codeunit 5940 ServContractManagement in function CopyCheckSCDimToTempSCDim?

Code Example:
        if ServiceLine."Line No." = 0 then
            if not DimMgt.CheckDimIDComb(ServHeader."Dimension Set ID") then
                Error(Text028,
                  ServHeader."Document Type", ServHeader."No.", DimMgt.GetDimCombErr);

        if ServiceLine."Line No." <> 0 then
            if not DimMgt.CheckDimIDComb(ServiceLine."Dimension Set ID") then
                Error(Text029,
                  ServHeader."Document Type", ServHeader."No.", ServiceLine."Line No.", DimMgt.GetDimCombErr);
        // start kvspsa - Event Raiser
        OnAfterCheckDimComb(ServHeader, ServiceLine);
        // stop kvspsa

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyCheckSCDimToTempSCDim(ServContract: Record "Service Contract Header")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
