### ISSUE TITLE
[Event Request] New Event in Table 5802 ValueEntry - OnAfterSumCostsTillValuationDateGetItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5693]
New Event in Table 5802 "Value Entry" - OnAfterSumCostsTillValuationDateGetItem

![image](https://user-images.githubusercontent.com/22153733/72897439-42f8b780-3d22-11ea-86e4-92ec60bdf818.png)

This is to be able to temporarily change the Costing Method on the Item variable.

Integration Event
OnAfterSumCostsTillValuationDateGetItem
var Item2: Record Item; var ValueEntry: Record "Value Entry"

**Comment by AlexanderYakunin** [comment]
Done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
