### ISSUE TITLE
[Event Request] codeunit 951 "Time Sheet Approval Management" - OnAfterSubmitBeforeModify

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5694]
Could we please have an event OnAfterSubmitBeforeModify in Codeunit 951 "Time Sheet Approval Management" in function Submit?

Code Example:
            UpdateApproverID;
            Status := Status::Submitted;
            // start kvspsa - Event Raiser
            OnAfterSubmitBeforeModify(TimeSheetLine);
            // stop kvspsa
            Modify(true);
            OnAfterSubmit(TimeSheetLine);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterSubmitBeforeModify(var TimeSheetLine: Record "Time Sheet Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
