### ISSUE TITLE
[Event Request] codeunit 951 "Time Sheet Approval Management" - OnAfterReopenSubmittedBeforeModify

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5695]
Could we please have an event OnAfterReopenSubmittedBeforeModify in Codeunit 951 "Time Sheet Approval Management" in function ReopenSubmitted?

Code Example:
    procedure ReopenSubmitted(var TimeSheetLine: Record "Time Sheet Line")
    begin
        with TimeSheetLine do begin
            if Status = Status::Open then
                exit;
            TestField(Status, Status::Submitted);
            Status := Status::Open;
            // start kvspsa - Event Raiser
            OnAfterReopenSubmittedBeforeModify(TimeSheetLine);
            // stop kvspsa
            Modify(true);
            OnAfterReopenSubmitted(TimeSheetLine);
        end;
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterReopenSubmittedBeforeModify(var TimeSheetLine: Record "Time Sheet Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
