### ISSUE TITLE
[Event Request] codeunit 951 "Time Sheet Approval Management" - OnAfterReopenApprovedBeforeModify

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5696]
Could we please have an event OnAfterReopenApprovedBeforeModify in Codeunit 951 "Time Sheet Approval Management" in function ReopenApproved?

Code Example:
    procedure ReopenApproved(var TimeSheetLine: Record "Time Sheet Line")
    begin
        with TimeSheetLine do begin
            if Status = Status::Submitted then
                exit;
            TestField(Status, Status::Approved);
            TestField(Posted, false);
            CheckApproverPermissions(TimeSheetLine);
            CheckLinkedServiceDoc(TimeSheetLine);
            UpdateApproverID;
            Status := Status::Submitted;
            // start kvspsa - Event Raiser
            OnAfterReopenApprovedBeforeModify(TimeSheetLine);
            // stop kvspsa
            Modify(true);
            OnAfterReopenApproved(TimeSheetLine);
        end;
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterReopenApprovedBeforeModify(var TimeSheetLine: Record "Time Sheet Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
