### ISSUE TITLE
[Event Request] codeunit 951 "Time Sheet Approval Management" - OnAfterRejectBeforeModify

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5697]
Could we please have an event OnAfterRejectBeforeModify in Codeunit 951 "Time Sheet Approval Management" in function Reject?

Code Example:
    procedure Reject(var TimeSheetLine: Record "Time Sheet Line")
    begin
        with TimeSheetLine do begin
            if Status = Status::Rejected then
                exit;
            TestField(Status, Status::Submitted);
            CheckApproverPermissions(TimeSheetLine);
            Status := Status::Rejected;
            // start kvspsa - Event Raiser
            OnAfterRejectBeforeModify(TimeSheetLine);
            // stop kvspsa
            Modify(true);
            OnAfterReject(TimeSheetLine);
        end;
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterRejectBeforeModify(var TimeSheetLine: Record "Time Sheet Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
