### ISSUE TITLE
[Event Request] New Event in Codeunit 5899 CalcInventoryValueCheck - OnAfterCheckCalculatePerSetFilter

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5698]
New Event in Codeunit 5899 "Calc. Inventory Value-Check" - OnAfterCheckCalculatePerSetFilter

![image](https://user-images.githubusercontent.com/22153733/72898211-ee563c00-3d23-11ea-87b3-80d1057ef28b.png)

This is to be able to change the filter on the Item2 variable.

Integration Event
OnAfterCheckCalculatePerSetFilter
var Item2: Record Item; var ItemChk: Record Item; PostingDate2: Date

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
