### ISSUE TITLE
[Event Request] codeunit 951 "Time Sheet Approval Management" - OnAfterApproveBeforeModify

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5699]
Could we please have an event OnAfterApproveBeforeModify in Codeunit 951 "Time Sheet Approval Management" in function Approve?

Code Example:
    procedure Approve(var TimeSheetLine: Record "Time Sheet Line")
    begin
        with TimeSheetLine do begin
            if Status = Status::Approved then
                exit;
            TestField(Status, Status::Submitted);
            CheckApproverPermissions(TimeSheetLine);
            Status := Status::Approved;
            "Approved By" := UserId;
            "Approval Date" := Today;
            // start kvspsa - Event Raiser
            OnAfterApproveBeforeModify(TimeSheetLine);
            // stop kvspsa
            Modify(true);
            case Type of
                Type::Absence:
                    PostAbsence(TimeSheetLine);
                Type::Service:
                    AfterApproveServiceOrderTmeSheetEntries(TimeSheetLine);
            end;
            OnAfterApprove(TimeSheetLine);
        end;
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterApproveBeforeModify(var TimeSheetLine: Record "Time Sheet Line")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
