### ISSUE TITLE
[Event Request] New Event in Codeunit 5899 CalcInventoryValueCheck - OnBeforeFindOpenOutboundEntry

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5700]
New Event in Codeunit 5899 "Calc. Inventory Value-Check" - OnBeforeFindOpenOutboundEntry 

![image](https://user-images.githubusercontent.com/22153733/72898993-6a9d4f00-3d25-11ea-8d0a-c6fb31708036.png)

Integration Event
OnBeforeFindOpenOutboundEntry
var Item2: Record Item; PostingDate2: Date

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
