### ISSUE TITLE
[Event Request] New Event in Codeunit 5899 CalcInventoryValueCheck - OnAfterCheckCalculatePer

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5701]
New Event in Codeunit 5899 "Calc. Inventory Value-Check" - OnAfterCheckCalculatePer

![image](https://user-images.githubusercontent.com/22153733/72899388-324a4080-3d26-11ea-8b26-32b67f2ea62e.png)

Integration Event
OnAfterCheckCalculatePer
var Item2: Record Item

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
