### ISSUE TITLE
[Event Request] New Event in Codeunit 5896 CalcInventoryAdjmtOrder - OnAfterCalculateGetItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5702]
New Event in Codeunit 5896 "Calc. Inventory Adjmt. - Order" - OnAfterCalculateGetItem

![image](https://user-images.githubusercontent.com/22153733/72899993-65410400-3d27-11ea-8860-da91e82483ae.png)

Integration Event
OnAfterCalculateGetItem
var Item2: Record Item; var SourceInvtAdjmtEntryOrder: Record "Inventory Adjmt. Entry (Order)"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
