### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 135301 "O365 Sales Item Charge Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5703]
[Event Request] Application “Tests-ERM”, Codeunit 135301 "O365 Sales Item Charge Tests"
![pic1](https://user-images.githubusercontent.com/45795262/72900558-658dcf00-3d28-11ea-8dfe-56fe9582ee50.png)

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/72900567-69b9ec80-3d28-11ea-9c39-bbfdeb071705.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
