### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 135300 "O365 Purch Item Charge Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5704]
[Event Request] Application “Tests-ERM”, Codeunit 135300 "O365 Purch Item Charge Tests"
![pic1](https://user-images.githubusercontent.com/45795262/72900676-a2f25c80-3d28-11ea-811a-30bf080084eb.png)

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/72900693-a84fa700-3d28-11ea-91d0-53926cbbe5c1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
