### ISSUE TITLE
[Event Request] New Event in Codeunit 5895 InventoryAdjustment - OnAfterIsAvgCostItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5705]
New Event in Codeunit 5895 "Inventory Adjustment" - OnAfterIsAvgCostItem

The new event needs to come with a variation of the Handled Pattern which I like to call Exit Plus Pattern. A Handled Pattern could be implemented instead, but the Exit Plus Pattern is leaner and more elegant in this context.

![image](https://user-images.githubusercontent.com/22153733/72901094-66733080-3d29-11ea-85e7-24b8705d80e0.png)

Integration Event
OnAfterIsAvgCostItem
var Item2: Record Item; var AvgCostItem: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
