### ISSUE TITLE
[Event Request] New Event in Codeunit 5895 InventoryAdjustment - OnAfterInsertAvgCostAdjmtEntryPoint

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5706]
New Event in Codeunit 5895 "Inventory Adjustment" - OnAfterInsertAvgCostAdjmtEntryPoint

![image](https://user-images.githubusercontent.com/22153733/72901816-b7375900-3d2a-11ea-9f6b-d9b9d9efae20.png)

Integration Event
OnAfterInsertAvgCostAdjmtEntryPoint
var ToAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
