### ISSUE TITLE
[Event Request] New Event in Codeunit 5895 InventoryAdjustment - OnBeforeUpdateItemUnitCost

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5707]
New Event in Codeunit 5895 "Inventory Adjustment" - OnBeforeUpdateItemUnitCost

The new event needs to implement the Handled Pattern as well.

![image](https://user-images.githubusercontent.com/22153733/72902441-bf43c880-3d2b-11ea-8b1a-aefb77a402a5.png)

Integration Event
OnBeforeUpdateItemUnitCost
var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point"; var IsHandled : Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
