### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeInitAmounts

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#5708]
Please add a new publisher event to the function UpdateDefaultDim as follows:
	
```
LOCAL InitAmounts(VAR GenJnlLine : Record "Gen. Journal Line") : Decimal
//>> Start New Publisher Call
OnBeforeInitAmounts(GenJnlLine, Currency, IsHandled);
IF IsHandled THEN
  EXIT(Currency."Amount Rounding Precision");
//<< End New Publisher Call
WITH GenJnlLine DO BEGIN
  IF "Currency Code" = '' THEN BEGIN
    Currency.InitRoundingPrecision;
    "Amount (LCY)" := Amount;
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeInitAmounts(VAR GenJnlLine : Record "Gen. Journal Line";VAR Currency : Record Currency;VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
