### ISSUE TITLE
[Event Request] New Event in Codeunit 5895 InventoryAdjustment - OnAfterGetVisitedEntries

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5709]
New Event in Codeuenit 5895 "Inventory Adjustment" - OnAfterGetVisitedEntries

![image](https://user-images.githubusercontent.com/22153733/72906870-32047200-3d33-11ea-806a-b3db2d5a97c5.png)

Integration Event
OnAfterGetVisitedEntries
var ExcludedValueEntry: Record "Value Entry"; OutbndValueEntry: Record "Value Entry"; 
var ItemLedgEntryInChain: Record "Item Ledger Entry"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
