### ISSUE TITLE
[Event Request] New Event in Codeunit 5895 InventoryAdjustment - OnAfterGetValuationPeriod

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5710]
New Event in Codeunit 5895 "Inventory Adjustment" - OnAfterGetValuationPeriod

![image](https://user-images.githubusercontent.com/22153733/72908462-c8399780-3d35-11ea-8996-bbbeb59fe438.png)

Integration Event
OnAfterGetValuationPeriod
var CalendarPeriod: Record Date; Item2: Record Item

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
