### ISSUE TITLE
[Event Request] New Event in Codeunit 5895 InventoryAdjustment - OnBeforeCopyILEToILE

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5711]
New Event in Codeunit 5895 "Inventory Adjustment" - OnBeforeCopyILEToILE

![image](https://user-images.githubusercontent.com/22153733/72908947-8a893e80-3d36-11ea-967b-355bea466189.png)

Integration Event
OnBeforeCopyILEToILE
var Item2: Record Item; ItemLedgEntry: Record "Item Ledger Entry"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
