### ISSUE TITLE
Need to set up TableTriggerSetup to provide user a message when record is renamed 

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#5712]
I tried to give the user a message, when (s)he renames a record.

One Subscriber for Codeunit 49, one for Codeunit 200000002

No of my message was shown.
Using the Event recorder, I have not found the event for the global rename.

Version:
 DE Business Central 15.2 (Platform 15.0.39461.0 + Application 15.2.39040.39489)

Is this an error in the system app?
Should I open a support request directly?

` [EventSubscriber(ObjectType::Codeunit, Codeunit::GlobalTriggerManagement, 'OnBeforeOnDatabaseRename', '', false, false)]
    local procedure MyProcedure(RecRef: RecordRef)
    begin
        message('Renamed GlobalTriggerMgt');
    end;`

`    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Global Triggers", 'OnDatabaseRename', '', false, false)]
    local procedure MyProcedure2(RecRef: RecordRef)
    begin
        message('Renamed (Global Triggers)');
    end;
`

**Comment by stephanweidmann** [comment]
Ok, you need to set the TableTriggerSetup now, then it will work. 

This is new and was not necessary in BC 14. 

Hope this will help someone. 

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"GlobalTriggerManagement", 'GetDatabaseTableTriggerSetup', '', false, false)]
    local procedure MyProcedure3(var OnDatabaseRename: Boolean)
    begin
        OnDatabaseRename := true;
    end;

**Comment by AlexanderYakunin** [comment]
Thank you for information. I've updated title with more details and close this issue
