### ISSUE TITLE
[Event Request] New Event in Codeunit 5847 GetAverageCostCalcOverview - OnAfterEntriesExistGetItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5713]
New Event in Codeunit 5847 "Get Average Cost Calc Overview" - OnAfterEntriesExistGetItem

![image](https://user-images.githubusercontent.com/22153733/72931474-34c88c80-3d5e-11ea-9d3d-35bfa032053b.png)

Integration Event
OnAfterEntriesExistGetItem
var Item2: Record Item; var AvgCostCalcOverview: Record "Average Cost Calc. Overview"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
