### ISSUE TITLE
[Event Request] New Event in Codeunit 5847 GetAverageCostCalcOverview - OnAfterCalculateGetItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5714]
New Event in Codeunit 5847 "Get Average Cost Calc Overview" - OnAfterCalculateGetItem

![image](https://user-images.githubusercontent.com/22153733/72931977-2464e180-3d5f-11ea-8876-a4105fd311c1.png)

Integration Event
OnAfterCalculateGetItem
var Item2: Record Item; var AvgCostCalcOverview: Record "Average Cost Calc. Overview"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
