### ISSUE TITLE
[Event Request] New Event in Codeunit 5847 GetAverageCostCalcOverview - OnBeforeInsert

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5715]
New Event in Codeunit 5847 "Get Average Cost Calc Overview" - OnBeforeInsert

Small, non-invasive modifications to the code (BEGIN - END statement) are necessary as well.

![image](https://user-images.githubusercontent.com/22153733/72932653-76f2cd80-3d60-11ea-8202-357cc9324826.png)
![image](https://user-images.githubusercontent.com/22153733/72932990-262fa480-3d61-11ea-8344-92f06c6994ae.png)

Integration Event
OnBeforeInsert
var AvgCostCalcOverview: Record "Average Cost Calc. Overview"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
