### ISSUE TITLE
[Event Request] New Event in Codeunit 23 ItemJnlPostBatch - OnAfterGetItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5716]
New Event in Codeunit 23 "Item Jnl.-Post Batch" - OnAfterGetItem

![image](https://user-images.githubusercontent.com/22153733/72933917-fed9d700-3d62-11ea-8dd3-4a4d96ee7a0d.png)

Integration Event
OnAfterGetItem
var Item: Record Item; ItemJnlLine4: Record "Item Journal Line"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
