### ISSUE TITLE
[Event Request] New Event in Codeunit 22 ItemJnlPostLine - OnBeforeGetItem

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5717]
New Event in Codeunit 22 "Item Jnl.-Post Line" - OnBeforeGetItem

Further code changes are necessary. They are spread across the codeunit; they are, however, not disruptive or invasive - nobody needs to make changes to their code because of the changes implemented here.

The reason for the changes is that frequent Item.Get statements need to be replaced by a call to a local procedure called GetItem, because the Item variable needs to be manipulated every time it gets assigned. Technically this would be possible by raising the publisher OnBeforeGetItem several times (i.e. after each Item.Get statement); that, however, is bad practice. Another possibility would be to add and raise a different publisher after each Item.Get statement. That, however, is uneconomical. Thus, the most economical and transparent architecture is to replace each Item.Get statement by a call to the local procedure GetItem and to raise the OnBeforeGetItem publisher once in the local procedure GetItem.

The new local procedure GetItem needs to look like this:

![image](https://user-images.githubusercontent.com/22153733/72939164-a4de0f00-3d6c-11ea-9635-d0992ba6ff43.png)

Statements of Item.Get need to be replaced by GetItem in the following places:

- local procedure "Code":

![image](https://user-images.githubusercontent.com/22153733/72939361-01412e80-3d6d-11ea-91cd-4514f6e081e6.png)

- in local procedure PostOutput:
 
![image](https://user-images.githubusercontent.com/22153733/72939526-50875f00-3d6d-11ea-8da9-e76e707af96e.png)

- in procedure PostItem:

![image](https://user-images.githubusercontent.com/22153733/72940074-6e08f880-3d6e-11ea-9f4b-7399d29f0663.png)

- in procedure UnApply:

![image](https://user-images.githubusercontent.com/22153733/72940209-b6281b00-3d6e-11ea-9f3a-2fd4602447f0.png)

- in procedure ReApply:

![image](https://user-images.githubusercontent.com/22153733/72940326-fc7d7a00-3d6e-11ea-961e-27f50e38c7ef.png)

- in procedure ReApply (2nd time):

![image](https://user-images.githubusercontent.com/22153733/72940475-45353300-3d6f-11ea-864a-ab34331427bf.png)

- local procedure UndoQuantityPosting:

![image](https://user-images.githubusercontent.com/22153733/72941214-b45f5700-3d70-11ea-985b-d9789c099195.png)

- in local procedure InsertItemAsmEntryRelation:

![image](https://user-images.githubusercontent.com/22153733/72941293-e40e5f00-3d70-11ea-8972-01c932fecc15.png)

Integration Event
OnBeforeGetItem
var Item: Record Item; ItemNo: Code[20]; Unconditionally: Boolean;
var HasGotItem: Boolean; var IsHandled : Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
