### ISSUE TITLE
 Codeunit 100 "Calc. G/L Acc. Where-Used" change the scope for function CheckPostingGroups

### ISSUE THREAD

**Issue by abhishekv290691** [microsoft/ALAppExtensions#5718]
Hi , 
Please make the CheckPostingGroups function in Codeunit 100 "Calc. G/L Acc. Where-Used" as external.

![image](https://user-images.githubusercontent.com/49511747/72946704-dd650380-3dd3-11ea-8bc6-f12faa032c41.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
