### ISSUE TITLE
[Event Request] New Event in Codeunit 5804 ItemCostManagement - OnAfterCalcQty

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5719]
New Event in Codeunit 5804 ItemCostManagement - OnAfterCalcQty

On top of implementing the new integration event, some code in the local procedure CalculateQuantity which raises the event needs to be modified as well. The changes are non-invasive and do not necessitate any changes for other developers. They only implement a version of the Handled Pattern which I call Exit Plus Pattern. The Handled Pattern could be implemented instead.

This is how the local procedure CalculateQuantity needs to look (including the code which raises the new integration event):

![image](https://user-images.githubusercontent.com/22153733/72975702-8827f280-3dd1-11ea-8039-c03b14498d07.png)

Integration Event
OnAfterCalcQty
var ValueEntry: Record "Value Entry"; var Item: Record Item; var CalcQty: Decimal

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
