### ISSUE TITLE
Codeunits 313-322 avoid commits

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#5720]
Hello,

for external use we need an enhancement of Codeunit 313 to 322 to avoid COMMIT.

Unfortunatley the provided function to supress the commit is useless for us right now. The calls in standard source code look always like this.
 "CODEUNIT.Run(CODEUNIT::"Sales-Printed", "Sales Header");"
 So there is no chance to call a "SuppressCommit" function.
 Could you please check it and provide a feedback / solution?

Thank you in advance,
 best regards,
 K.

**Comment by plagijat** [comment]
Hi,

We also need to suppress this explicit Commit in suggested Codeunits.

Thanks,
Zoran M.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
