### ISSUE TITLE
[Event Request] New Event in Codeunit 23 ItemJnlPostBatch - OnBeforeCalcAppliedAmount

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5721]
New Event in Codeunit 23 "Item Jnl.-Post Batch" - OnBeforeCalcAppliedAmount

The new event is raised in local procedure ItemJnlPostSumLine:

![image](https://user-images.githubusercontent.com/22153733/72979382-7e55bd80-3dd8-11ea-9c57-44199fde82dd.png)

Integration Event
OnBeforeCalcAppliedAmount
var ItemJournalLine: Record "Item Journal Line"; ItemLedgEntry: Record "Item Ledger Entry"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
