### ISSUE TITLE
Codeunit 5802 Inventory Posting To G/L - OnAfterInitTempInvtPostBuf

### ISSUE THREAD

**Issue by florindanu** [microsoft/ALAppExtensions#5722]
Hello,

I've developed an extension in a BC 14.1 container. I've created a subscription function related to event OnAfterInitTempInvtPostBuf from Codeunit 5802 Inventory Posting To G/L, raised in function InitInvtPostBuf from the same codeunit:

    procedure InitInvtPostBuf(ValueEntry: Record "Value Entry"; AccType: Option; BalAccType: Option; CostToPost: Decimal; CostToPostACY: Decimal; InterimAccount: Boolean)
    begin
        OnBeforeInitInvtPostBuf(ValueEntry);

        PostBufDimNo := PostBufDimNo + 1;
        SetAccNo(TempInvtPostBuf[PostBufDimNo], ValueEntry, AccType, BalAccType);
        SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo], CostToPost, CostToPostACY, InterimAccount);
        TempInvtPostBuf[PostBufDimNo]."Dimension Set ID" := ValueEntry."Dimension Set ID";
        OnAfterInitTempInvtPostBuf(TempInvtPostBuf, ValueEntry);

        PostBufDimNo := PostBufDimNo + 1;
        SetAccNo(TempInvtPostBuf[PostBufDimNo], ValueEntry, BalAccType, AccType);
        SetPostBufAmounts(TempInvtPostBuf[PostBufDimNo], -CostToPost, -CostToPostACY, InterimAccount);
        TempInvtPostBuf[PostBufDimNo]."Dimension Set ID" := ValueEntry."Dimension Set ID";
        OnAfterInitTempInvtPostBuf(TempInvtPostBuf, ValueEntry);

        OnAfterInitInvtPostBuf(ValueEntry);
    end;

My subscription function is something like that:

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Inventory Posting To G/L", 'OnAfterInitTempInvtPostBuf', '', false, false)]
    local procedure SetGLCorrectionOnAfterInitTempInvtPostBuf(var TempInvtPostBuf: array[4] of Record "Invt. Posting Buffer"; ValueEntry: Record "Value Entry"; PostBufDimNo: Integer)
    var
        InvtSetup: Record "Inventory Setup";
    begin
        InvtSetup.Get();
        if InvtSetup.FDAPostExpCostConvAsCorr then begin
            CASE ValueEntry."Document Type" OF
                ValueEntry."Document Type"::"Purchase Receipt":
                    BEGIN
                        IF ((ValueEntry."Cost Amount (Expected)" < 0) AND (ValueEntry."Cost Amount (Actual)" > 0)) OR
                            ((ValueEntry."Cost Amount (Expected) (ACY)" < 0) AND (ValueEntry."Cost Amount (Actual) (ACY)" > 0)) THEN
                            TempInvtPostBuf[PostBufDimNo].FDAGLCorrection := TempInvtPostBuf[PostBufDimNo]."Interim Account"; .......

TempInvtPostBuf is an array of "Invt. Posting Buffer" records and I needed to know the index of current element to manage the business rules according specific requirements. I used the global variable PostBufDimNo added as last parameter of subscription function. This was possible because in BC 14.1 the event has property GlobalVarAccess = TRUE.

    [IntegrationEvent(TRUE, TRUE)]
    local procedure OnAfterInitTempInvtPostBuf(var TempInvtPostBuf: array[4] of Record "Invt. Posting Buffer" temporary; ValueEntry: Record "Value Entry")
    begin
    end;

Today, I tried to upgrade my extension to BC 15.2 and I failed because in this version the event OnAfterInitTempInvtPostBuf has GlobalVarAccess = false.

    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterInitTempInvtPostBuf(var TempInvtPostBuf: array[4] of Record "Invt. Posting Buffer" temporary; ValueEntry: Record "Value Entry")
    begin
    end;

Please add to event OnAfterInitTempInvtPostBuf the index of the array as parameter:

    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterInitTempInvtPostBuf(var TempInvtPostBuf: array[4] of Record "Invt. Posting Buffer" temporary; ValueEntry: Record "Value Entry"; PostBufDimNo: Integer)
    begin
    end;

Or set again to TRUE GlobalVarAccess (I suppose not recommended).

Many thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
