### ISSUE TITLE
Codeunit 5988 Serv-Documents Mgt. - extend field size ExtDocNo - Bug

### ISSUE THREAD

**Issue by Aswin2u** [microsoft/ALAppExtensions#5723]
Field size needs to be expanded from 20 to 35 seems a **bug** in service module
Global variable - GenJnlLineExtDocNo  - Code - 20 to 35, cannot process with Service Order having 35 chars in External Document Number.
SetGenJnlLineDocNos()

Similarly need to be updated in Code Unit 5987 - Serv-Posting Journals Mgt.,
ServPostingJnlsMgt.SetGenJnlLineDocNos()
ServPostingJnlsMgt.PostResJnlLineSale()
ServPostingJnlsMgt.PostGenGnlLineSale()
ServPostingJnlsMgt.PostGenJnlLineReceivable()
ServPostingJnlsMgt.PostGenJnlLineBalancing()

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
