### ISSUE TITLE
[Event Request] New Event in Codeunit 23 ItemJnlPostBatch - OnBeforePostSumLine

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5724]
New Event in Codeunit 23 "Item Jnl.-Post Batch" - OnBeforePostSumLine

- in local procedure ItemJnlPostSumLine:

![image](https://user-images.githubusercontent.com/22153733/72981077-38025d80-3ddc-11ea-998c-c578eb8a1051.png)

Integration Event
OnBeforePostSumLine
var ItemJournalLine: Record "Item Journal Line"; ItemLedgEntry: Record "Item Ledger Entry"; 
var IncludeExpectedCost : Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
