### ISSUE TITLE
[Request for External] Table 9650 - Custom Report Layout 

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#5725]
Hello AL-team,
I would like to copy the following base-actions from page 9650 "Custom Reports Layouts" into my own page:

- **Action -> Function name in table**
- NewLayout -> CopyBuiltInLayout
- CopyRec -> CopyRecord
- ImportLayout -> ImportLayout
- ExportLayout -> ExportLayout
- EditLayout -> EditLayout
- UpdateWordLayout -> UpdateLayout

But all these functions are restricted with "OnPrem". Would you please change the scope to external or tell me the alternative working with layouts in the cloud? 
Thank you very much!

**Comment by tomddlc** [comment]
If the above is not possible, please consider adding "Stream" versions, like in the ExcelBuffer table, where OpenBook is OnPrem while OpenBookStream is not.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
