### ISSUE TITLE
[Event Request] New Event in Codeunit 23 ItemJnlPostBatch - OnBeforePostLine

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5726]
New Event in Codeunit 23 "Item Jnl.-Post Batch" - OnBeforePostLine

![image](https://user-images.githubusercontent.com/22153733/72982916-73069000-3de0-11ea-8e59-8cd8fee77b22.png)

Integration Event
OnBeforePostLine
var ItemJnlLine: Record "Item Journal Line"; var SuppressCommit: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
