### ISSUE TITLE
[Event Request] New Event in Codeunit 23 ItemJnlPostBatch - OnAfterCopyRegNos

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5727]
New Event in Codeunit 23 "Item Jnl.-Post Batch" - OnAfterCopyRegNos

- in local procedur "Code":

![image](https://user-images.githubusercontent.com/22153733/72993397-9982f600-3df5-11ea-91ac-7fbd661bc65e.png)

Integration Event
OnAfterCopyRegNos
var ItemJnlLine: Record "Item Journal Line"; var ItemRegNo: Integer; var WhseRegNo: Integer

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
