### ISSUE TITLE
[Event Request] Report 7000082 Settle Docs. in Posted PO - OnBeforePostedDocOnPreDataItem 

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5729]
In versión 14.0.35570.0 the event allready exists, but the second parameter PostingDate is NOT declared as VAR. ¿Can you fix it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
