### ISSUE TITLE
[Event Request] New Event to Table 5409 in Function CalcStartingEndingDates(Direction1 : 'Forward,Backward')

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5733]
New Event to Table 5409 in Function CalcStartingEndingDates(Direction1 : 'Forward,Backward')

Add new local variable IsHandled (Boolean)
![1](https://user-images.githubusercontent.com/56544591/73061669-013f4c80-3e9b-11ea-9e82-2b5f56ac1ec4.png)

**LOCAL [IntegrationEvent] OnBeforeCalculateRouting**(VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line";VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
