### ISSUE TITLE
[Event Request] Page 9300 Sales Quotes - OnBeforeStatisticsAction

### ISSUE THREAD

**Issue by evamariamartingomez** [microsoft/ALAppExtensions#5734]
Hi,

I would like the same Event 'OnBeforeStatisticsAction' in the Statistics Action that is in **Page 41 SalesQuote** but in **Page 9300 Sales Quotes**

Thank you in advance,

Eva Maria

![Page41_SalesQuote](https://user-images.githubusercontent.com/56435545/73062690-3cdb1600-3e9d-11ea-9401-1dc85df95f30.png)
![Page9300_SalesQuotes](https://user-images.githubusercontent.com/56435545/73062691-3cdb1600-3e9d-11ea-8dcd-5172e53c1478.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
