### ISSUE TITLE
[Event Request] Codeunit 374 Bank Acc. Recon. Apply Entries - OnAfterApplyEntries #3428

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5736]
#3428 

In versión 14.0.35570.0 there are a new event named OnfAfterApplyCheckLedgEntry. This event is not like the event we need. Our event is out of WITH named OnBeforeApplyAmount, at end of ApplyEnties procedure.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
