### ISSUE TITLE
[Event Request] Table 5896 "Inventory Adjmt. Entry (Order)" "Add Single Level Costs

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#5737]
I am working on a solution for a client dealing with sharing manufacturing costs across multiple production order lines and need a series of events for onbefore and onafter adding a single level cost to allow us to manipulate the costs being applied on a per line basis. I am requesting the following events

Name
OnBeforeAddSingleLvlMaterialCost
OnAfterAddSingleLvlMaterialCost
OnBeforeAddSingleLvlCapacityCost
OnAfterAddSingleLvlCapacityCost
OnBeforeAddSingleLvlSubcontrdCost
OnAfterAddSingleLvlSubcontrdCost
OnBeforeAddSingleLvlCapOvhdCost
OnAfterAddSingleLvlCapOvhdCost
OnBeforeAddSingleLvlMfgOvhdCost
OnAfterAddSingleLvlMfgOvhdCost

![Table 5896 events 1](https://user-images.githubusercontent.com/50593101/73075810-bfa6a580-3e8a-11ea-8e2d-84104fc4fa93.jpg)

Each would have the same variables passed:
Var	Name	DataType	Subtype	Length
Yes	InventoryAdjmtEntryOrder	Record	Inventory Adjmt. Entry (Order)	
Yes	CostAmtLCY	Decimal		
Yes	CostAmtACY	Decimal		

![Table 5896 events 3](https://user-images.githubusercontent.com/50593101/73075823-ca613a80-3e8a-11ea-81f3-21fc7dbee2b4.jpg)

The events would be raised before or after the associated function for adding the single level cost.

![Table 5896 events 2](https://user-images.githubusercontent.com/50593101/73075864-e533af00-3e8a-11ea-86a9-88dd9a3eaf01.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
