### ISSUE TITLE
[Event Request] New Event in Codeunit 23 ItemJnlPostBatch - OnAfterUpdateAnalysisView

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5738]
New Event in Codeunit 23 "Item Jnl.-Post Batch" - OnAfterUpdateAnalysisView

- in local procedure "Code":

![image](https://user-images.githubusercontent.com/22153733/73076087-ae2ac100-3ebd-11ea-8948-bacf078c9845.png)

Integration Event
OnAfterUpdateAnalysisView
var ItemReg: Record "Item Register"

**Comment by AlexanderYakunin** [comment]
Done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
