### ISSUE TITLE
[Event Request] Codeunit 5896 "Calc. Inventory Adjmt. - Order" OnBeforeFindItemLedgEntryCalcActualMaterialCosts

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#5739]
I am working on a solution for a client dealing with sharing manufacturing costs across multiple production order lines and need an events for OnBeforeFindItemLedgEntryCalcActualMaterialCosts

![Codeunit 5896 events 1](https://user-images.githubusercontent.com/50593101/73076529-4a3bd480-3e8c-11ea-8230-94a0cdbd4837.jpg)

The variables needed are:
Var	Name	DataType	Subtype	Length
Yes	InvtAdjmtEntryOrder	Record	Inventory Adjmt. Entry (Order)	
Yes	ItemLedgEntry	Record	Item Ledger Entry	

![Codeunit 5896 events 3](https://user-images.githubusercontent.com/50593101/73076616-748d9200-3e8c-11ea-9e32-c6fb115ebaf7.jpg)

This would be called in the CalcActualMaterialCosts function before the Find so filters could be changed to get all the lines instead of the single line.

![Codeunit 5896 events 2](https://user-images.githubusercontent.com/50593101/73076716-a43c9a00-3e8c-11ea-8e9e-5decc9e5f4ff.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
