### ISSUE TITLE
[Event Request] Codeunit 5896 "Calc. Inventory Adjmt. - Order" OnBeforeFindCapLedgEntryCalcActualCapacityCosts

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#5740]
I am working on a solution for a client dealing with sharing manufacturing costs across multiple production order lines and need an events for OnBeforeFindCapLedgEntryCalcActualCapacityCosts

![Codeunit 5896 events 1b](https://user-images.githubusercontent.com/50593101/73077098-7c016b00-3e8d-11ea-8a2c-fcd940935bd6.jpg)

The variables needed are:
Var	Name	DataType	Subtype	Length
Yes	InvtAdjmtEntryOrder	Record	Inventory Adjmt. Entry (Order)	
Yes	CapLedgEntry	Record	Capacity Ledger Entry	

![Codeunit 5896 events 3b](https://user-images.githubusercontent.com/50593101/73077166-a4896500-3e8d-11ea-8324-605a577dc797.jpg)

This would be called in the CalcActualCapacityCosts function before the Find so filters could be changed to get all the lines instead of the single line.

![Codeunit 5896 events 2b](https://user-images.githubusercontent.com/50593101/73077203-b8cd6200-3e8d-11ea-9cf8-f67c9ef2c0c3.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
