### ISSUE TITLE
[Event Request] New Event in Codeunit 5802 InventoryPostingToGL - OnAfterInsertGLItemLedgRelationing

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5742]
New Event in Codeunit 5802 "Inventory Posting To G/L" - OnAfterInsertGLItemLedgRelation

![image](https://user-images.githubusercontent.com/22153733/73079002-b554cd80-3ec3-11ea-8a87-2b659618cca8.png)

Integration Event
OnAfterInsertGLItemLedgRelation
<No Parameters>

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
