### ISSUE TITLE
[Event Request] New Event in Codeunit 5802 InventoryPostingToGL - OnAfterSetDesc

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5743]
New Event in Codeunit 5802 "Inventory Posting To G/L" - OnAfterSetDesc

![image](https://user-images.githubusercontent.com/22153733/73080171-b1c24600-3ec5-11ea-882e-e15bb934592b.png)

Integration Event
OnAfterSetDesc
var GenJnlLine: Record "Gen. Journal Line"; var InvtPostBuf: Record "Invt. Posting Buffer"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
