### ISSUE TITLE
[Event Request] New Event in Codeunit 5802 InventoryPostingToGL - OnBeforeCheckAccountNo

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5744]
New Event in Codeunit 5802 "Inventory Posting To G/L" - OnBeforeCheckAccountNo

- in local procedure SetAccNo:

![image](https://user-images.githubusercontent.com/22153733/73080947-f9959d00-3ec6-11ea-851b-be5c01d6b2fb.png)

Integration Event
OnBeforeCheckAccountNo
var InvtPostBuf: Record "Invt. Posting Buffer"; InvtPostSetup: Record "Inventory Posting Setup"; 
GenPostingSetup: Record "General Posting Setup"; CalledFromItemPosting: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
