### ISSUE TITLE
[Event Request] New Event to Table 5409 in Function CheckPreviousAndNext()

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5745]
New Event to Table 5409 in Function CheckPreviousAndNext()

![2](https://user-images.githubusercontent.com/56544591/73081443-e800c500-3ec7-11ea-88a6-c482231fa90e.png)

**LOCAL [IntegrationEvent] OnCheckPreviousAndNext**(TempRec : TEMPORARY Record "Prod. Order Routing Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
