### ISSUE TITLE
[Event Request] New Event in Codeunit 5802 InventoryPostingToGL - OnAfterGetPostingSetups

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5746]
New Event in Codeunit 5802 "Inventory Posting To G/L" - OnAfterGetPostingSetups

- in local procedure SetAccNo:

![image](https://user-images.githubusercontent.com/22153733/73081582-2bf3ca00-3ec8-11ea-95dc-0e65aa30d5d5.png)

Integration Event
OnAfterGetPostingSetups
var InvtPostBuf: Record "Invt. Posting Buffer"; var InvtPostSetup: Record "Inventory Posting Setup"; var GenPostingSetup: Record "General Posting Setup"; ValueEntry: Record "Value Entry"; UseInvtPostSetup: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by AlexanderYakunin** [comment]
Event for same purpose already implemented
