### ISSUE TITLE
[Event Request] New Event in Codeunit 7600 added in Function CalcTimeSubtract(Time : Time;Value : Integer) Result : Time

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5747]
New Event in Codeunit 7600 added in Function CalcTimeSubtract(Time : Time;Value : Integer) Result : Time

![3](https://user-images.githubusercontent.com/56544591/73082104-18952e80-3ec9-11ea-8ecf-e22a814cc352.png)

**LOCAL [IntegrationEvent] OnBeforeCalcTimeSubtract**(VAR Value : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
