### ISSUE TITLE
[Event Request] New Event added in Codeunit 99000774 added in Function CreateLoadForward(TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';Write : Boolean;LoadFactor : Decimal)

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5748]
New Event added in Codeunit 99000774 added in Function **CreateLoadForward**(TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';Write : Boolean;LoadFactor : Decimal)

Add new local variable IsHandled (Boolean)

![4](https://user-images.githubusercontent.com/56544591/73082201-4e3a1780-3ec9-11ea-92f5-c709a0c8a85f.png)

**LOCAL [IntegrationEvent] OnBeforeCalculateEndingTimeInCreateLoadForward**(VAR EndingTime : Time;CalendarEntry : Record "Calendar Entry";AvQtyBase : Decimal;RelevantEfficiency : Decimal;ConCurrCap : Decimal;VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
