### ISSUE TITLE
[Event Request] New Event added in Codeunit 99000774 in Function LoadCapForward(CapType : 'Work Center,Machine Center';CapNo : Code[20];TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';Write : Boolean)

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5749]
New Event added in Codeunit 99000774 in Function **LoadCapForward**(CapType : 'Work Center,Machine Center';CapNo : Code[20];TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';Write : Boolean)

Add new local variable: IsHandled (Boolean)

![5a](https://user-images.githubusercontent.com/56544591/73526384-69e57680-4411-11ea-9ee1-30c7d1e971a1.png)

**LOCAL [IntegrationEvent] OnBeforeLoadCapForward**(TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';VAR ProdStartingTime : Time;VAR ProdStartingDate : Date;VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line";VAR IsHandled : Boolean)

**Comment by AlexanderYakunin** [comment]
You have mismatch between title, content and event definition. Please recheck and correct, I need to know exactly which event do you need.

**Comment by SDave-orderbase** [comment]
Hello Alexander,

I hope you are fine. Thanks for your comment!
I have corrected the image. Sorry for inconvenience. Is it okay now?

Best regards,
Shreyas

Von: Alexander Yakunin <notifications@github.com>
Gesendet: Freitag, 31. Januar 2020 08:42
An: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
Cc: Shreyas Dave <s.dave@orderbase.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] New Event added in Codeunit 99000774 in Function LoadCapForward(CapType : 'Work Center,Machine Center';CapNo : Code[20];TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';Write : Boolean) (#5...


You have mismatch between title, content and event definition. Please recheck and correct, I need to know exactly which event do you need.

**Comment by AlexanderYakunin** [comment]
Why do you need new local variables StartDateTime and EndingDateTime?

**Comment by SDave-orderbase** [comment]
Hello Alexander,

after consulting a developer we decided that it is possible to rewrite our code. We can do without the two new local variables. I have updated my post and the image again.

Thanks in advance!
Shreyas

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
