### ISSUE TITLE
[Event Request] New Event added in Codeunit 99000774 in Function CalculateRoutingLine(VAR ProdOrderRoutingLine2 : Record "Prod. Order Routing Line";Direction : 'Forward,Backward';CalcStartEndDate : Boolean)

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5750]
New Event added in Codeunit 99000774 in Function **CalculateRoutingLine**(VAR ProdOrderRoutingLine2 : Record "Prod. Order Routing Line";Direction : 'Forward,Backward';CalcStartEndDate : Boolean)

![7](https://user-images.githubusercontent.com/56544591/73083599-c43f7e00-3ecb-11ea-89a6-c4760631b021.png)

**LOCAL [IntegrationEvent] OnCalculateRoutingLineCalcStartEndDate**(ProdOrderRoutingLine : Record "Prod. Order Routing Line";VAR CalcStartEndDate : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
