### ISSUE TITLE
[Event Request] New Event added in Codeunit 99000774 LOCAL FinitelyLoadCapForward(TimeType : 'Setup Time,Run Time';ConstrainedCapacity : Record "Capacity Constrained Resource";ResourceIsConstrained : Boolean;ParentWorkCenter : Record "Capacity Constrained Resource";ParentIsConstrained : Boolean)

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5752]
New Event added in Codeunit 99000774 **LOCAL FinitelyLoadCapForward**(TimeType : 'Setup Time,Run Time';ConstrainedCapacity : Record "Capacity Constrained Resource";ResourceIsConstrained : Boolean;ParentWorkCenter : Record "Capacity Constrained Resource";ParentIsConstrained : Boolean)

Add new local variable IsHandled (Boolean)

![9](https://user-images.githubusercontent.com/56544591/73083961-68292980-3ecc-11ea-9ad5-037951a8e75c.png)

**LOCAL [IntegrationEvent] OnBeforeCalculateStartTimeInFinitelyLoadCapForward**(VAR IsHandled : Boolean)

**Comment by SDave-orderbase** [comment]
Dear Alexander,

I had made several event requests in January and all were confirmed quite some time ago. Is it possible to answer, when you can give further comment on this specific event request?

Thanks in advance,
Kind regards,

Shreyas Dave

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
