### ISSUE TITLE
[Event Request] Added New Event in Codeunit 99000787 in Function Copy(ProdOrder2 : Record "Production Order";Direction : 'Forward,Backward';VariantCode : Code[10];LetDueDateDecrease : Boolean) : Boolean

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5753]
Added New Event in Codeunit 99000787 in Function Copy(ProdOrder2 : Record "Production Order";Direction : 'Forward,Backward';VariantCode : Code[10];LetDueDateDecrease : Boolean) : Boolean

![10](https://user-images.githubusercontent.com/56544591/73084055-8e4ec980-3ecc-11ea-8e16-27e571a317b3.png)

**LOCAL [IntegrationEvent] OCAfterCopyProdOrder**(ErrorOccured : Boolean;VAR ProdOrder : Record "Production Order")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
