### ISSUE TITLE
[Event Request] New Event added in Codeunit 99000810 in Function LOCAL CreateLoadBack(TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';Write : Boolean)

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5754]
New Event added in Codeunit 99000810 in Function **LOCAL CreateLoadBack**(TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';Write : Boolean)

Add new local variable IsHandled (Boolean)

![11](https://user-images.githubusercontent.com/56544591/73084169-c2c28580-3ecc-11ea-9a95-66efc563bb2b.png)

**LOCAL [IntegrationEvent] OnBeforeCalculateCreateLoadBack**(VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
