### ISSUE TITLE
[Event Request] Add New Event in Codeunit 99000810 in Function LoadCapForward

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5755]
Add New Event in Codeunit 99000810 in Function LoadCapForward

Add new local variable IsHandled(Boolean)

![12](https://user-images.githubusercontent.com/56544591/73084253-eb4a7f80-3ecc-11ea-9722-dbb4edcddba0.png)

**LOCAL [IntegrationEvent] OnBeforeLoadCapForward**(TimeType : 'Setup Time,Run Time,Wait Time,Move Time,Queue Time';VAR ProdStartingDate : Date;VAR ProdStartingTime : Time;VAR PlanningRoutingLine : Record "Planning Routing Line";VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
