### ISSUE TITLE
[Event Request] New Event added in Codeunit 99000810 in Function LOCAL CalcMoveAndWaitBack()

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5756]
New Event added in Codeunit 99000810 in Function **LOCAL CalcMoveAndWaitBack**()

Add new local variables: IsHandled(Boolean)

![13a](https://user-images.githubusercontent.com/56544591/73526640-eed09000-4411-11ea-9aed-f611c6f15e7b.png)

**LOCAL [IntegrationEvent] OnBeforeCalcWaitBack**(VAR PlanningRoutingLine : Record "Planning Routing Line";WorkCenter : Record "Work Center";VAR ProdEndingDate : Date;VAR ProdEndingTime : Time;VAR UpdateDates : Boolean;VAR IsHandled : Boolean)

**Comment by SDave-orderbase** [comment]
Updated post without two new local variables.

StartTime(DateTime), Endtime(DateTime) have been removed like in https://github.com/microsoft/ALAppExtensions/issues/5749

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
