### ISSUE TITLE
[Event Request] Add New Event in Codeunit 99000810 in Function CalculateRouteLine(VAR PlanningRoutingLine2 : Record "Planning Routing Line";Direction : 'Forward,Backward';CalcStartEndDate : Boolean;ReqLine2 : Record "Requisition Line")

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5757]
Add New Event in Codeunit 99000810 in Function **CalculateRouteLine**(VAR PlanningRoutingLine2 : Record "Planning Routing Line";Direction : 'Forward,Backward';CalcStartEndDate : Boolean;ReqLine2 : Record "Requisition Line")

![14](https://user-images.githubusercontent.com/56544591/73084522-66139a80-3ecd-11ea-9bd6-a39d10bd2c40.png)

**LOCAL [IntegrationEvent] OnCalculateRoutingLineCalcStartEndDate**(VAR PlanningRoutingLine : Record "Planning Routing Line";VAR CalcStartEndDate : Boolean)

**Comment by SDave-orderbase** [comment]
Dear Alexander,

I had made several event requests in January and all were confirmed quite some time ago. Is it possible to answer, when you can give further comment on this specific event request?

Thanks in advance,
Kind regards,

Shreyas Dave

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
