### ISSUE TITLE
[Event Request] New Code added in Codeunit 99000815 in Function [External] SalesLineCheck(SalesLine : Record "Sales Line";ForceRequest : Boolean)

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5758]
New Code added in Codeunit 99000815 in Function [External] SalesLineCheck(SalesLine : Record "Sales Line";ForceRequest : Boolean)

Add new local variable IsHandled (Boolean)

![15](https://user-images.githubusercontent.com/56544591/73084633-9b1fed00-3ecd-11ea-8781-61634aa4b3ff.png)

**LOCAL [IntegrationEvent] OnReservationCheckDateConflUpdateDate**(VAR FilterReservEntry : Record "Reservation Entry";Date : Date;VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
