### ISSUE TITLE
[Event Request] Add new Event in Codeunit 99000815 in Function [External] ProdOrderLineCheck(ProdOrderLine : Record "Prod. Order Line";ForceRequest : Boolean)

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5759]
Add new Event in Codeunit 99000815 in Function [External] ProdOrderLineCheck(ProdOrderLine : Record "Prod. Order Line";ForceRequest : Boolean)

Add new local variable IsHandled (Boolean)

![16](https://user-images.githubusercontent.com/56544591/73084718-c9053180-3ecd-11ea-8906-e56d930982a7.png)

**LOCAL [IntegrationEvent] OnReservationCheckDateConflUpdateDate**(VAR FilterReservEntry : Record "Reservation Entry";Date : Date;VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
