### ISSUE TITLE
[Event Request] Add new Event in Codeunit 99000815 in Function [External] ProdOrderComponentCheck(ProdOrderComp : Record "Prod. Order Component";ForceRequest : Boolean;IsCritical : Boolean) : Boolean

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5760]
Add new Event in Codeunit 99000815 in Function [External] ProdOrderComponentCheck(ProdOrderComp : Record "Prod. Order Component";ForceRequest : Boolean;IsCritical : Boolean) : Boolean

Add new variable IsHandled (Boolean)

![17](https://user-images.githubusercontent.com/56544591/73084809-edf9a480-3ecd-11ea-8634-caf750f4bcb3.png)

**LOCAL [IntegrationEvent] OnReservationCheckDateConflUpdateDate**(VAR FilterReservEntry : Record "Reservation Entry";Date : Date;VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
