### ISSUE TITLE
[Event Request] New Event added in Codeunit 99000774 in Function CalcMoveAndWaitBack()

### ISSUE THREAD

**Issue by SDave-orderbase** [microsoft/ALAppExtensions#5761]
New Event added in Codeunit 99000774 in Function **CalcMoveAndWaitBack**()

Add new local variable IsHandled(Boolean)

![6](https://user-images.githubusercontent.com/56544591/73085287-bdfed100-3ece-11ea-8e0a-f8b882898d11.png)

**LOCAL [IntegrationEvent] OnBeforeCalcWaitBack**(VAR ProdEndingTime : Time;VAR ProdEndingDate : Date;VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line";VAR UpdateDates : Boolean;VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
