### ISSUE TITLE
[Event Request] New Event in Report 1003 PostInvtCostToGLTest - OnAfterGetAccountName

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5762]
New Event in Report 1003 "Post Invt. Cost to G/L - Test" - OnAfterGetAccountName

This requires additional, non-invasive code in the local procedure GetAccountName and a new local variable:

![image](https://user-images.githubusercontent.com/22153733/73087059-2307f600-3ed2-11ea-9f92-75da71a5ca3b.png)
![image](https://user-images.githubusercontent.com/22153733/73087193-6f533600-3ed2-11ea-9d52-61ff6c2c098d.png)

Integration Event
OnAfterGetAccountName
var TempInvtPostToGLTestBuf: Record "Invt. Post to G/L Test Buffer"; 
InvtPostSetup: Record "Inventory Posting Setup"; GenPostSetup: Record "General Posting Setup"; 
var AccountName: Text[80]

**Comment by AlexanderYakunin** [comment]
Done

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
