### ISSUE TITLE
[Event Request] New Event in Table 48 InvtPostingBuffer - OnAfterUseInvtPostSetup

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#5763]
New Event in Table 48 "Invt. Posting Buffer" - OnAfterUseInvtPostSetup

This requires additional non-disruptive code changes in the procedure UseInvtPostSetup. An Exit Plus Pattern (variation of the Handled Pattern) needs to be implemented:

![image](https://user-images.githubusercontent.com/22153733/73088456-90b52180-3ed4-11ea-8ba2-13a6fa65c84a.png)

Integration Event
OnAfterUseInvtPostSetup
var Rec : Record "Invt. Posting Buffer"; var IsValidAccountType: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
