### ISSUE TITLE
[Event Request] Table 36 Sales Header - In Function RecreateSalesLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5765]
Dear,

I request for below Event:

![image](https://user-images.githubusercontent.com/45877379/73153595-5b8a1880-40fa-11ea-9b27-43a6c4e4b0d2.png)

Definition of Integration as below:

![image](https://user-images.githubusercontent.com/45877379/73153633-87a59980-40fa-11ea-8720-d832dd104a85.png)

thanks & regards

Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
FYI - CurrFieldNo parameter cannot have VAR

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
