### ISSUE TITLE
[Event Request] Table 83 Item Journal Line - Function TestItemFields

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5766]
Dear,

I request below Integration 

![image](https://user-images.githubusercontent.com/45877379/73154253-c0467280-40fc-11ea-8c82-c6743f095993.png)

Definition of Integration is

![image](https://user-images.githubusercontent.com/45877379/73154272-d2c0ac00-40fc-11ea-9213-8a0516839333.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
