### ISSUE TITLE
[Event Request] Table 337 Reservation Entry - In Function TestItemFields

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5767]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73155332-5e880780-4100-11ea-8f56-6cb4a400fde1.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73155352-6e075080-4100-11ea-9774-cb469817fd94.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
