### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - function ApplyItemLedgEntry

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5768]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73155550-1b7a6400-4101-11ea-8c76-723fe56a37f1.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73155567-246b3580-4101-11ea-862a-5e9f7366856e.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
