### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - function InitValueEntry

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5769]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73155665-65fbe080-4101-11ea-85ea-0fa3914a3f2d.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73155679-6e541b80-4101-11ea-9d02-a4aac3aae56f.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
