### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - function SetupSplitJnlLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5770]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73155836-ec182700-4101-11ea-837f-e5298fe16b9f.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73155849-f5a18f00-4101-11ea-9097-b7e5bfd65853.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
