### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - function SplitJnlLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5771]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73156079-9132ff80-4102-11ea-87e5-dc858cca70f8.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73156088-9abc6780-4102-11ea-8235-b7e49430e555.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
