### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - function CheckItemTracking

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5772]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73156202-08689380-4103-11ea-8da3-e580c23ac63c.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73156206-11f1fb80-4103-11ea-9b84-8c29f3d9314c.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
