### ISSUE TITLE
[Event Request] Codeunit 74 Purch.-Get Receipt - function CreateInvLines

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5773]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73157380-c6415100-4106-11ea-9a78-7a2bbb1df9b0.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73157390-d0634f80-4106-11ea-98ec-7e3fd584fb7a.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
