### ISSUE TITLE
[Request for external] Exposing functions NoOnAfterValidate, UpdateEditableOnRow, UpdateTypeText and DeltaUpdateTotals #3316

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#5774]
The issue #3316 is closed and labeled as "ships-in-future-update", but it's not implemented. Is it a mistake or will it be included in future versions?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
