### ISSUE TITLE
[Event Request] Codeunit 74 Purch.-Get Receipt - function CreateInvLines

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5776]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73160358-c3e2f500-410e-11ea-9da9-77552083617e.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73160363-ca716c80-410e-11ea-850b-84fa1922aa79.png)

thanks & regards

Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
We already have this event here

    procedure GetItemChargeAssgnt(var PurchRcptLine: Record "Purch. Rcpt. Line"; QtyToInvoice: Decimal)
    var
        PurchOrderLine: Record "Purchase Line";
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetItemChargeAssgnt(PurchRcptLine, QtyToInvoice, IsHandled);
        if IsHandled then
            exit;
