### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - function UpdateAssocOrder

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5777]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73160465-13c1bc00-410f-11ea-99e1-52a85651179a.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73160472-1a503380-410f-11ea-9b69-3070faf81389.png)

thanks & regards

Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
Please use existing event OnUpdateAssocOrderOnBeforeModifyPurchLine(PurchOrderLine, TempDropShptPostBuffer);

**Comment by ashwinitripathi** [comment]
Accept your Suggestion, you can defer this requirement. I didn't noticed the Availability as was not available in initial version on which I started my upgrade.
