### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - function UpdateAssosOrderPostingNos

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5778]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73160578-613e2900-410f-11ea-92e1-8622d2f9894b.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73160588-6bf8be00-410f-11ea-9764-4c3d235a76dc.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
