### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - function PostItemJnlLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5780]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73161378-6603dc80-4111-11ea-8712-2e19eb0e359a.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73160855-212b7600-4110-11ea-907b-66e564fc42e2.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
