### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - function PostItemJnlLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5781]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73161474-977ca800-4111-11ea-90e3-86c5ce6cd8ef.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73161481-9d728900-4111-11ea-8ae1-99c5998eaa03.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
