### ISSUE TITLE
[Event Request] Codeunit 6500 Item Tracking Management - function SplitWhseJnlLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5782]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73161980-c0ea0380-4112-11ea-9d1d-e7288f5ab2e9.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73161988-c6dfe480-4112-11ea-840d-178d0f503b43.png)

thanks & regards

Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
We can simply add parameter TempWhseJnlLine2 to existing event OnSplitWhseJnlLineOnAfterCheckWhseItemTrkgSetup. We do not implement conditional logic between event, this is possible reason for tricky bugs.

**Comment by ashwinitripathi** [comment]
I accept your suggestion. Please do the same, it will fulfil my requirement.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
