### ISSUE TITLE
[Event Request] Codeunit 6500 Item Tracking Management - function SumUpItemTracking

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5783]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73162081-05759f00-4113-11ea-8ac0-5b66292bd780.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73162091-0ad2e980-4113-11ea-8c33-8ab97e0c1ae6.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
