### ISSUE TITLE
Business Chart trigger DataPointClicked

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#5784]
Hi,

I am using v15.2 container (mcr.microsoft.com/businesscentral/sandbox:15.2.39558.0-ca) and I am not sure how to resolve this error:
![image](https://user-images.githubusercontent.com/34686682/73161504-f3343a80-40eb-11ea-82d2-8eb4689ca485.png)

In v14.1 we had code like this and everything was working as expected:
![image](https://user-images.githubusercontent.com/34686682/73161921-e7954380-40ec-11ea-82ce-6be1839fb7de.png)

I couldn't find documentation on how to handle this change.

Thank you,
Radovan

**Comment by radovandokic** [comment]
Hi @AlexanderYakunin , do you have any info about this?

**Comment by AlexanderYakunin** [comment]
This forum is for extensibility requests (events, enums etc.), not for support issues. We cannot answer questions of this type. You can ask other partners using community forums or create request to Support to resolve your issue.
