### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. - function CopySalesDoc

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5785]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73162217-54233900-4113-11ea-96a4-3aadfa9100b2.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73162228-5be2dd80-4113-11ea-9e34-a47f76131603.png)

thanks & regards

Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
Probably you wanted to write "if not IsHandled then"?

**Comment by ashwinitripathi** [comment]
Yes, You are correct, my logic wants to skip Copying Sales Line below code.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
