### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. - function CopySalesDoc

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5786]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73162616-34404500-4114-11ea-9abc-62f48dbf1675.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73162622-3a362600-4114-11ea-9db7-7707ab2fc55a.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
