### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. - function CopySalesDocUpdateHeader

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5787]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73164284-a7978600-4117-11ea-9cc6-047e065da5a2.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73164296-b120ee00-4117-11ea-8f94-1d02e4cfde1f.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
