### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. - function CheckCreditLimit

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5788]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73164447-fba26a80-4117-11ea-9142-a47f8042fc27.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73164463-01984b80-4118-11ea-8606-0b4a566a28b2.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
