### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. - function SalesHeaderStartDate

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5789]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73164694-68b60000-4118-11ea-8e31-a7b2d763e255.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73164713-74092b80-4118-11ea-9799-3ee9e61b479e.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
