### ISSUE TITLE
how to change/remove code from default table function using AL ?

### ISSUE THREAD

**Issue by TharunMuthu** [Microsoft/ALAppExtensions#579]
Good Evening All!
Can you please advice how to change/remove  code from default table function .
let say for my example if **i want to remove highlighted one line code from GetDimensionSetID function in Table 480  !**
Can you please advice  how to achieve this from AL ?(with out touching default code) 

![capture](https://user-images.githubusercontent.com/44170162/49742315-3c9cad00-fcd3-11e8-85e8-fc47801407c6.JPG)

**Comment by mynavblog** [comment]
Hi,
As I understand Idea of the AL and extensions is: you do not change standard code. This is base of code and should not be touch at all. 

Question is why you want to remove the line? And especially this one?

Best regards,
Krzysztof

**Comment by TharunMuthu** [comment]
> Hi,
> As I understand Idea of the AL and extensions is: you do not change standard code. This is base of code and should not be touch at all.
> 
> Question is why you want to remove the line? And especially this one?
> 
> Best regards,
> Krzysztof

Hi,

Thanks for your reply i understand AL can support only extension . I hope after few years Microsoft will remove CAL completely  so on that time definitely they will allow us to  change default code .  
and answer for your question : we are trying to do some customization in default .Anyway that one will not possible from AL .
Once again thanks for your reply .
