### ISSUE TITLE
[Event Request] Codeunit 7010 Purch. Price Calc. Mgt. - function PurchHeaderStartDate

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5790]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73164875-c9453d00-4118-11ea-8f13-ebdce5691372.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73164891-cea28780-4118-11ea-97bf-d923c42f81f0.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
