### ISSUE TITLE
[Event Request] Codeunit 99000830 Create Reserv. Entry - function TransferReservEntry

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5795]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73165987-f0047300-411a-11ea-9a3a-e9a387403cdb.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73165995-f5fa5400-411a-11ea-963d-1dee960c4eb0.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
