### ISSUE TITLE
[Event Request] Codeunit 99000831 Reservation Engine Mgt. - function CloseReservEntry

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5796]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73166126-3ce84980-411b-11ea-8317-270e827da41c.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73166147-470a4800-411b-11ea-81c9-865e8c9e262d.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
