### ISSUE TITLE
[Event Request] Codeunit 99000832 Sales Line-Reserve - function CreateReservation

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5800]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73167048-1e834d80-411d-11ea-8f79-b0610920c87c.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73167061-2511c500-411d-11ea-87fe-32d47d66d0dc.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
