### ISSUE TITLE
[Event Request] Codeunit 99000832 Sales Line-Reserve - function TestSalesLineModification

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5801]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73167179-67d39d00-411d-11ea-8961-c42cd3344df2.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73167193-6c985100-411d-11ea-80ab-098bc31e27dd.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
