### ISSUE TITLE
[Event Request] Codeunit 99000832 Sales Line-Reserve - function TestSalesLineModification

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5802]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73167307-a36e6700-411d-11ea-93f6-72235b758b5d.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73167321-a9fcde80-411d-11ea-8b29-56b5f3b01f62.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
