### ISSUE TITLE
[Event Request] Codeunit 99000834 Purch. Line-Reserve - function VerifyChange

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5803]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73167461-e7fa0280-411d-11ea-9550-e882b5e28806.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73167481-ecbeb680-411d-11ea-8a25-7616618c3974.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
