### ISSUE TITLE
[Event Request] Codeunit 99000835 Item Jnl. Line-Reserve - function TransferItemJnlToItemLedgEntry

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5804]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73167613-298aad80-411e-11ea-9210-b1eabf2930d2.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73167628-2ee7f800-411e-11ea-85ab-71bdb0341e17.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
