### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - function AutoReserveOneLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5805]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73167805-900fcb80-411e-11ea-9ad1-a5eab0f73063.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73167816-956d1600-411e-11ea-8143-8145812e2b8d.png)

thanks & regards

Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
Which version you are referring to? We do not provide events for 14.X and reservation code in 15.x/16.x is quite different.

**Comment by ashwinitripathi** [comment]
This is upgrade from 2009 to BC 14. Project was started with release of BC 14 and now we have converted all customization to Extension friendly code and stabilized the solution. And customer database is highly customized around Variant Code, Tracking & Reservation. It has integration from 5 outside software application to place order till invoice document moves between these system and updated. Once customization is stable then we can think to moving to higher version. We will convert to AL then continue with higher version.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
