### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - function DeleteReservEntries2

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5806]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73167930-cf3e1c80-411e-11ea-874e-4ddc42e3261c.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73167941-d9601b00-411e-11ea-89ee-a51b4078199d.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
