### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - function  InitFilter

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5807]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73168142-41166600-411f-11ea-8fd7-18c70853495d.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73168157-4673b080-411f-11ea-8984-b7d03c82154b.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
