### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - function InitFilter

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5808]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73168240-78851280-411f-11ea-85dc-4db1896c7b24.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73168253-7d49c680-411f-11ea-9ca1-f9748508f1a0.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
