### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - function CalcReservedQtyOnPick

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5809]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73168589-1c6ebe00-4120-11ea-8aff-66fe1d6a0d75.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73168597-21cc0880-4120-11ea-9e70-634ba26436c0.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
