### ISSUE TITLE
[Event-Request] Outlook add-in extensibility

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#581]
Just tried to extend the 'Outlook Add-in' features (Document View / New ...) without touching the base code, but all code is fully hardcoded around sales / purchase document and heavily uses options / cases with limited event publisher. Can this module be reviewed to support other application areas / custom areas by using the platform objects already available (1630 object range)

Also see http://www.twity.de/2016/11/25/extending-the-new-office-add-ins-of-microsoft-dynamics-nav-2017/

**Comment by JesperSchulz** [comment]
Removing event-request tag again, as this isn't an event-request but rather an extensibility request. We will triage your request soon.

**Comment by jaredha** [comment]
I really like this scenario. This is a great scenario for extending the Document View add-in. You should be able to create a new add-in that does the ticket lookup, and would sit right next to the Document View add-in, without modifying the base app code. But we'll look into adding extensibility options for adding document types to the Document View add-in itself. Thanks for the feedback!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
