### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - function CalcReservedQtyOnPick

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5810]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73168711-63f54a00-4120-11ea-9c12-e2280938be4d.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73168728-69eb2b00-4120-11ea-9c15-4f0b7e271ad6.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
