### ISSUE TITLE
[Event Request] Codeunit 353 Item Availability Forms Mgt - function CalculateNeed

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5811]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73168846-be8ea600-4120-11ea-86fe-3faa6a8e42c6.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73168853-c3ebf080-4120-11ea-8778-f8b5855222e4.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
