### ISSUE TITLE
[Event Request] Codeunit 7130 Item Budget Management - function FindRec

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5812]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73169782-d6ffc000-4122-11ea-8279-e17650151895.png)

Definition of Integration as below

**IncludeSender = Yes**

![image](https://user-images.githubusercontent.com/45877379/73169790-de26ce00-4122-11ea-931e-012b12c47fb3.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
