### ISSUE TITLE
[Event Request] Codeunit 7130 Item Budget Management - function NextRec

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5813]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73169895-22b26980-4123-11ea-9e65-82b68d8621bd.png)

Definition of Integration as below

**IncludeSender = Yes**

![image](https://user-images.githubusercontent.com/45877379/73169923-378efd00-4123-11ea-823e-b10fe2f0c1ff.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
