### ISSUE TITLE
[Event Request] Codeunit 7130 Item Budget Management - function CopyItemToBuf

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#5814]
Dear,

I request for below Integration

![image](https://user-images.githubusercontent.com/45877379/73170047-7755e480-4123-11ea-93a9-3489db703595.png)

Definition of Integration as below

![image](https://user-images.githubusercontent.com/45877379/73170065-7cb32f00-4123-11ea-818c-48e6f5012d13.png)

thanks & regards

Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
