### ISSUE TITLE
TAB36 - OnInitRecord - OnBeforeSalesShipmentDateIsSetToWorkdate

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#5818]
Hello,

we want to change to initialization of the shipment date in TAB36. Unfortunaly in the OnInitRecord-Procedure the "Shipment Date" is Always set to the Workdate (Independent if it's empty or not).

So there are 2 possibilities:
1. Overwrite the Shipment Date only of it's empty (than we can use the existing OnBeforeInitRecord to set the Shipment Date).
![image](https://user-images.githubusercontent.com/45033081/73173284-5088b580-4105-11ea-8490-30177e72ba18.png)

2. Add an Event with a IsHandled.
![image](https://user-images.githubusercontent.com/45033081/73173409-904f9d00-4105-11ea-9156-c7b1fd662392.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
