### ISSUE TITLE
[Event Request] report 5914 "Delete Invoiced Service Orders"

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5819]
Could you please add a publisher in the report 5914 "Delete Invoiced Service Orders" Dataitem: "Service Header"

```
  dataitem("Service Header"; "Service Header")
        {
            DataItemTableView = SORTING("Document Type", "No.") WHERE("Document Type" = CONST(Order));
            RequestFilterFields = "No.", "Customer No.", "Bill-to Customer No.";
            RequestFilterHeading = 'Service Order';

            trigger OnAfterGetRecord()
            var
                ApprovalsMgmt: Codeunit "Approvals Mgmt.";
            begin
                Window.Update(1, "No.");
                // New Event
                OnBeforeOnAfterGetRecordServiceHeader("Service Header");
                

                ItemChargeAssgntService.Reset;
                ItemChargeAssgntService.SetRange("Document Type", "Document Type");
                ItemChargeAssgntService.SetRange("Document No.", "No.");
```

```
  local procedure OnBeforeOnAfterGetRecordServiceHeader(var ServiceHeader: Record "Service Header");
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
