### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforePostVend

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#5824]
Please add a new publisher event to the function PostVend as follows:
	
```
LOCAL PostVend(GenJnlLine : Record "Gen. Journal Line";Balancing : Boolean)
//>> Start New Publisher Call
OnBeforePostVend(GenJnlLine); //C09032.n
//<< End New Publisher Call
PurchSetup.GET;
WITH GenJnlLine DO BEGIN
  Vend.GET("Account No.");
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforePostVend(GenJournalLine : Record "Gen. Journal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
