### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeCheckAmountRounding

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#5825]
Please add a new publisher event to the function InsertGLEntry as follows:
	
```
[External] InsertGLEntry(GenJnlLine : Record "Gen. Journal Line";GLEntry : Record "G/L Entry";CalcAddCurrResiduals : Boolean)

WITH GLEntry DO BEGIN
  TESTFIELD("G/L Account No.");

//>> Start New Publisher Call
  OnBeforeCheckAmountRounding(GLEntry,Checked);
  IF NOT Checked THEN
//<< End New Publisher Call
    IF Amount <> ROUND(Amount) THEN
      FIELDERROR(
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeCheckAmountRounding(VAR GLEntry : Record "G/L Entry";VAR Checked : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
