### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - CheckAndUpdate

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#5826]
Dear BaseApp team,

I'd like to kindly ask you to consider adding new event to CheckAndUpdate procedure right after CalcInvDiscount:
![SalesPost - CheckAndUpdate](https://user-images.githubusercontent.com/42442951/73184143-a587f400-4124-11ea-81b3-39678d479fa9.png)

We'd like to check additional things right before we try to release certain types of documents.
The desired event signature is as follows:
![SalesPost - OnAfterCalcInvDiscount](https://user-images.githubusercontent.com/42442951/73184279-dc5e0a00-4124-11ea-8d11-2540ac398c03.png)

Thanks in advance.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
