### ISSUE TITLE
New OnBeforeFindResPrice event in CodeUnit 221 is flawed.

### ISSUE THREAD

**Issue by sigmundurruedenet** [microsoft/ALAppExtensions#5828]
In issue [https://github.com/Microsoft/ALAppExtensions/issues/1184](url) a very valid issue is raised and promised in a future release. Now it has been implemented but I would argue that the code is somewhat flawed, or just wrong. Maybe I am missing something or I might be using the event in a weird way. Clarification would be nice. Anyways, here is my reasoning and explanation why I think it is at least somewhat flawed.

In mbertelsmann's implementation we subscribe to the event, do what we want, and then set the IsHandled to true if we do not want the standard code to run. We do this so that the ResPrice variable is not changed from what we set it to in our event. Perfect!

In the implementation that we got now this is not the case. We are forced to make FindResPrice method control which way the if statement in line 6 goes. If FindResPrice returns true then we override ResPrice with ResPrice2. If FindResPrice returns false then we override ResPrice with some values. Either way we override ResPrice and we cannot skip it.

Is this really how it was meant to behave? 

P.S. OnAfterFindResPrice is also never run if we find something with all those ResPrice2.GET statements. Would it not be better to EXIT(TRUE) after OnAfterFindResPrice?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
