### ISSUE TITLE
[Event Request] codeunit 950 "Time Sheet Management" - OnBeforeFilterTimeSheets

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5830]
Could we please have an event OnBeforeFilterTimeSheets in Codeunit 950 "Time Sheet Management" in function FilterTimeSheets?

Code Example:
    procedure FilterTimeSheets(var TimeSheetHeader: Record "Time Sheet Header"; FieldNo: Integer)
    var
        UserSetup: Record "User Setup";
        // start kvspsa - Variables added
        IsHandled: Boolean;
    // stop kvspsa
    begin
        // start kvspsa - Event Raiser
        IsHandled := false;
        OnBeforeFilterTimeSheets(TimeSheetHeader, FieldNo, IsHandled);
        If IsHandled then
            exit;
        // stop kvspsa
        if UserSetup.Get(UserId) then;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFilterTimeSheets(var TimeSheetHeader: Record "Time Sheet Header"; FieldNoPar: Integer; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
