### ISSUE TITLE
[Event Request] codeunit 950 "Time Sheet Management" - OnBeforeCopyTimeSheet

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5831]
Could we please have an event OnBeforeCopyTimeSheet in Codeunit 950 "Time Sheet Management" in function CopyPrevTimeSheetLines?

Code Example:
        FromTimeSheetHeader.SetRange("Resource No.", ToTimeSheetHeader."Resource No.");
        if FromTimeSheetHeader.Next(-1) <> 0 then begin
            FromTimeSheetLine.SetRange("Time Sheet No.", FromTimeSheetHeader."No.");
            FromTimeSheetLine.SetFilter(Type, '<>%1&<>%2', FromTimeSheetLine.Type::Service, FromTimeSheetLine.Type::"Assembly Order");
            if FromTimeSheetLine.FindSet then
                repeat
                    // start kvspsa - Event Raiser
                    LineCanBeCopied := false;
                    OnBeforeCopyTimeSheet(FromTimeSheetLine, LineCanBeCopied);
                    if not LineCanBeCopied then
                        QtyLineNotCopiedLoc += 1
                    else begin
                        // stop kvspsa
                        LineNo := LineNo + 10000;
                        ToTimeSheetLine.Init;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyTimeSheet(var FromTimeSheetLine: Record "Time Sheet Line"; var LineCanBeCopied: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
