### ISSUE TITLE
[Event Request] codeunit 950 "Time Sheet Management" - OnAfterCopyTimeSheetLines

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5832]
Could we please have an event OnAfterCopyTimeSheetLines in Codeunit 950 "Time Sheet Management" in function CopyPrevTimeSheetLines?

Code Example:
                        ToTimeSheetLine.Description := FromTimeSheetLine.Description;
                        ToTimeSheetLine.Chargeable := FromTimeSheetLine.Chargeable;
                        ToTimeSheetLine."Work Type Code" := FromTimeSheetLine."Work Type Code";
                        OnBeforeToTimeSheetLineInsert(ToTimeSheetLine, FromTimeSheetLine);
                        ToTimeSheetLine.Insert;
                until FromTimeSheetLine.Next = 0;
            // start kvspsa - Event Raiser
            OnAfterCopyTimeSheetLines(QtyLineNotCopiedLoc);
            // stop kvspsa
        end;
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyTimeSheetLines(QtyLinesNotCopied: Integer)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
