### ISSUE TITLE
[Event Request] codeunit 950 "Time Sheet Management" - OnAfterGetActivityInfo

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5833]
Could we please have an event OnAfterGetActivityInfo in Codeunit 950 "Time Sheet Management" in function GetActivityInfo?

Code Example:
                Type::"Assembly Order":
                    begin
                        ActivityCaption := FieldCaption("Assembly Order No.");
                        ActivityID := "Assembly Order No.";
                    end;
                Type::Service:
                    begin
                        ActivityCaption := FieldCaption("Service Order No.");
                        ActivityID := "Service Order No.";
                    end;
            end;
        // start kvspsa - Event Raiser
        OnAfterGetActivityInfo(TimeSheetLine, ActivityCaption, ActivityID, ActivitySubCaption, ActivitySubID)
        // stop kvspsa
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetActivityInfo(TimeSheetLine: Record "Time Sheet Line"; var ActivityCaption: Text[30]; var ActivityID: Code[20]; var ActivitySubCaption: Text[30]; var ActivitySubID: Code[20])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
