### ISSUE TITLE
[Event Request] codeunit 5817 "Undo Posting Management" - OnBeforeTestfieldsOnRepeatTempItemLedgEntryOnCheckItemLedgEntries

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5834]
Could we please have an event OnBeforeTestfieldsOnRepeatTempItemLedgEntryOnCheckItemLedgEntries in Codeunit 5817 "Undo Posting Management" in function CheckItemLedgEntries?

Code Example:
    begin
        with TempItemLedgEntry do begin
            Find('-'); // Assertion: will fail if not found.
            ValueEntry.SetCurrentKey("Item Ledger Entry No.");
            ItemRec.Get("Item No.");
            if ItemRec.IsNonInventoriableType then
                exit;

            repeat
                // start kvspsa - Event Raiser
                OnBeforeTestfieldsOnRepeatTempItemLedgEntryOnCheckItemLedgEntries(TempItemLedgEntry);
                // stop kvspsa
                if Positive then begin
                    if ("Job No." = '') and
                       not (("Order Type" = "Order Type"::Assembly) and
                            PostedATOLink.Get(PostedATOLink."Assembly Document Type"::Assembly, "Document No."))
                    then
                        TestField("Remaining Quantity", Quantity);
                end else

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestfieldsOnRepeatTempItemLedgEntryOnCheckItemLedgEntries(var TempItemLedgEntry: Record "Item Ledger Entry")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
