### ISSUE TITLE
[Event Request] codeunit 5813 "Undo Purchase Receipt Line" - OnItemRcptEntryNoSetOnPostItemJnlLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5835]
Could we please have an event OnItemRcptEntryNoSetOnPostItemJnlLine in Codeunit 5813 "Undo Purchase Receipt Line" in function PostItemJnlLine?

Code Example:
            if "Item Rcpt. Entry No." <> 0 then begin
                if "Job No." <> '' then
                    UndoPostingMgt.TransferSourceValues(ItemJnlLine, "Item Rcpt. Entry No.");

                // start kvspsa - Event Raiser
                IsHandled := false;
                OnItemRcptEntryNoSetOnPostItemJnlLine(ItemJnlLine, PurchRcptHeader, PurchRcptLine, SourceCodeSetup, IsHandled);
                if IsHandled then
                    exit(ItemJnlLine."Item Shpt. Entry No.");
                // stop kvspsa

                UndoPostingMgt.PostItemJnlLine(ItemJnlLine);
                if "Job No." <> '' then begin

Event:
    [IntegrationEvent(false, false)]
    local procedure OnItemRcptEntryNoSetOnPostItemJnlLine(var ItemJnlLine: Record "Item Journal Line"; var PurchRcptHeader: Record "Purch. Rcpt. Header"; var PurchRcptLine: Record "Purch. Rcpt. Line"; SourceCodeSetup: Record "Source Code Setup"; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
We already have this
                IsHandled := false;
                OnPostItemJnlLineOnBeforeUndoPosting(ItemJnlLine, PurchRcptHeader, PurchRcptLine, SourceCodeSetup, IsHandled);
                if IsHandled then
                    exit(ItemJnlLine."Item Shpt. Entry No.");
