### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnBeforePostSourceDocument

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5837]
Could we please have an event OnBeforePostSourceDocument in Codeunit 7324 "Whse.-Activity-Post" in function PostSourceDocument?

Code Example:
    begin
        // start kvspsa - Event Raiser
        OnBeforePostSourceDocument(WhseActivHeader, PostedSourceType, PostedSourceNo, PostedSourceSubType);
        // stop kvspsa
        with WhseActivHeader do
            case "Source Type" of
                DATABASE::"Purchase Line":
                    begin

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostSourceDocument(var WhseActivityHeader: Record "Warehouse Activity Header"; var PostedSourceType: Integer; var PostedSourceNo: Code[20]; var PostedSourceSubType: Integer)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
