### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnAfterCode new parameter 

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5838]
Could we please have additional parameter (PrintDoc) in event OnAfterCode in Codeunit 86?

            if PrintDoc then
                case "Source Document" of
                    "Source Document"::"Purchase Order",
                  "Source Document"::"Purchase Return Order":
                        PurchPostPrint.GetReport(PurchHeader);
                    "Source Document"::"Sales Order",
                  "Source Document"::"Sales Return Order":
                        SalesPostPrint.GetReport(SalesHeader);
                    "Source Document"::"Inbound Transfer":
                        TransferOrderPostPrint.PrintReport(TransHeader, Selection::Receipt);
                    "Source Document"::"Outbound Transfer":
                        TransferOrderPostPrint.PrintReport(TransHeader, Selection::Shipment);
                end;

            // start kvspsa - New Parameter
            OnAfterCode(WhseActivLine, PrintDoc);
            // stop kvspsa

            Commit;
            OnAfterPostWhseActivHeader(WhseActivHeader);

Event:

    local procedure OnAfterCode(var WarehouseActivityLine: Record "Warehouse Activity Line"; PrintDoc: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
