### ISSUE TITLE
[Event Request] page 956 "Actual/Sched. Summary FactBox" - OnBeforeUpdateData

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5839]
Could we please have an event OnBefoereUpdateData in page 956 "Actual/Sched. Summary FactBox" in function UpdateData?

Code Example:
    begin
        // start kvspsa - Event Raiser
        OnBeforePostSourceDocument(WhseActivHeader, PostedSourceType, PostedSourceNo, PostedSourceSubType);
        // stop kvspsa
        with WhseActivHeader do
            case "Source Type" of
                DATABASE::"Purchase Line":
                    begin

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeUpdateData(var TimeSheetHeader: Record "Time Sheet Header"; var MonthQty: Decimal; var MonthDescription: Text[50]; var MonthCapacity: Decimal)
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Incorrect request data, please correct.

**Comment by StHillmann** [comment]
Code Example:
```
procedure UpdateData(TimeSheetHeader: Record "Time Sheet Header")
    begin
        // start kvspsa - Event Raiser
        OnBeforeUpdateData(TimeSheetHeader, MonthQty, MonthDescription, MonthCapacity);
        // stop kvspsa
        TimeSheetMgt.CalcActSchedFactBoxData(TimeSheetHeader, DateDescription, DateQuantity, TotalQtyText, TotalQuantity, AbsenceQty);
        PresenceQty := TotalQuantity - AbsenceQty;
        CurrPage.Update(false);
    end;
```

Event:
```
[IntegrationEvent(TRUE, false)]
local procedure OnBeforeUpdateData(var TimeSheetHeader: Record "Time Sheet Header"; var MonthQty: Decimal; var MonthDescription: Text[50]; var MonthCapacity: Decimal)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
