### ISSUE TITLE
Function Expose] Codeunit 5940 ServContractManagement - functions: CreateServiceLedgerEntry, CreateServLine

### ISSUE THREAD

**Issue by mynavblog** [Microsoft/ALAppExtensions#584]
Dear Team,

Please set as external functions in Codeunit 5940 ServContractManagement:

CreateServiceLedgerEntry

![image](https://user-images.githubusercontent.com/37371997/49795675-e1060a00-fd3a-11e8-9a7f-a1ca8725e9b6.png)

CreateServLine

![image](https://user-images.githubusercontent.com/37371997/49795701-f7ac6100-fd3a-11e8-9ba7-fe2f1a1abd7c.png)

Thank you in advance.

Best regards,
Krzysztof

**Comment by JesperSchulz** [comment]
Both functions were marked as external as part of a bigger effort to expose safe, public functions. Your issue will be resolved in a future update.
