### ISSUE TITLE
[Event Request] page 9192 "Company Creation Wizard" - OnAfterCreateNewCompany

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5841]
Could we please have an event OnAfterCreateNewCompany in page 9192 "Company Creation Wizard" in function FinishAction?

Code Example:
    begin
        AssistedCompanySetup.CreateNewCompany(NewCompanyName);
        // start kvspsa - Event Raiser
        OnAfterCreateNewCompany(NewCompanyData, UseKVSPSA);
        // stop kvspsa
        AssistedCompanySetup.SetUpNewCompany(NewCompanyName, NewCompanyData);

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterCreateNewCompany(var NewCompanyData: Option "Evaluation Data","Standard Data","None","Extended Data","Full No Data",,,,,,,,,,"PSA Wizard"; var UseKVSPSA: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
