### ISSUE TITLE
[Event Request] page 9192 "Company Creation Wizard" - OnAfterCompanyCreated

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5842]
Could we please have an event OnAfterCompanyCreated in page 9192 "Company Creation Wizard" in function FinishAction?

Code Example:
        CompanyCreated := true;
        // start kvspsa - Event Raiser
        OnAfterCompanyCreated(NewCompanyName, NewCompanyData, UseKVSPSA);
        // stop kvspsa
        CurrPage.Close;
        if not (NewCompanyData in [NewCompanyData::None, NewCompanyData::"Full No Data"]) then
            Message(CompanySetUpInProgressMsg, NewCompanyName);
    end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterCompanyCreated(NewCompanyName: Text[30]; NewCompanyData: Option "Evaluation Data","Standard Data","None","Extended Data","Full No Data",,,,,,,,,,"PSA Wizard"; UseKVSPSA: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
