### ISSUE TITLE
[Event Request] page 9192 "Company Creation Wizard" - OnHandlingCaseElseOnUpdateDataDescription

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5843]
Could we please have an event OnHandlingCaseElseOnUpdateDataDescription in page 9192 "Company Creation Wizard" in function UpdateDataDescription?

Code Example:
    local procedure UpdateDataDescription()
    var
        TenantLicenseState: Codeunit "Tenant License State";
    begin
        case NewCompanyData of
            NewCompanyData::"Evaluation Data":
                NewCompanyDataDescription := EvaluationDataTxt;
            NewCompanyData::"Standard Data":
                NewCompanyDataDescription := StandardDataTxt;
            NewCompanyData::"Extended Data":
                NewCompanyDataDescription := ExtendedDataTxt;
            NewCompanyData::None, NewCompanyData::"Full No Data":
                NewCompanyDataDescription := NoDataTxt;
            // start kvspsa - Event Raiser
            else
                OnHandlingCaseElseOnUpdateDataDescription(NewCompanyData, NewCompanyDataDescription, NoDataTxt);
        // stop kvspsa
        end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnHandlingCaseElseOnUpdateDataDescription(NewCompanyData: Option "Evaluation Data","Standard Data","None","Extended Data","Full No Data",,,,,,,,,,"PSA Wizard"; var NewCompanyDataDescription: Text; NoDataTxt: Text)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
