### ISSUE TITLE
[Event Request] page 5856 "Get Post.Doc - P.RcptLn Sbfrm" - OnBeforeCalcReceivedPurchNotReturnedOnIsShowRec

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5844]
Could we please have an event OnBeforeCalcReceivedPurchNotReturnedOnIsShowRec in page 5856 in function IsShowRec?

Code Example:
    begin
        with PurchRcptLine2 do begin
            RemainingQty := 0;
            if RevQtyFilter and (Type = Type::" ") then
                exit("Attached to Line No." = 0);
            if Type <> Type::Item then
                exit(true);
            // start kvspsa - Code Modification
            //if ("Job No." <> '') or ("Prod. Order No." <> '') then
            //    exit(not RevQtyFilter);
            IsHandled := false;
            OnBeforeCalcReceivedPurchNotReturnedOnIsShowRec(PurchRcptLine2, RevQtyFilter, IsHandled);
            if IsHandled then
                exit(not RevQtyFilter);
            // stop kvspsa
            CalcReceivedPurchNotReturned(RemainingQty, RevUnitCostLCY, FillExactCostReverse);

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeCalcReceivedPurchNotReturnedOnIsShowRec(PurchRcptLine: Record "Purch. Rcpt. Line"; var RevQtyFilter: Boolean; var IsHandled: Boolean);
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Sorry, I cannot make this change. You should not remove our code.

**Comment by MiRo65** [comment]
ok, sorry, I change my code example:

Code Example:
begin
with PurchRcptLine2 do begin
RemainingQty := 0;
if RevQtyFilter and (Type = Type::" ") then
exit("Attached to Line No." = 0);
if Type <> Type::Item then
exit(true);
if ("Job No." <> '') or ("Prod. Order No." <> '') then
 exit(not RevQtyFilter);
// start kvspsa - Code Modification
IsHandled := false;
OnBeforeCalcReceivedPurchNotReturnedOnIsShowRec(PurchRcptLine2, RevQtyFilter, IsHandled);
if IsHandled then
exit(not RevQtyFilter);
// stop kvspsa
CalcReceivedPurchNotReturned(RemainingQty, RevUnitCostLCY, FillExactCostReverse);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
