### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterAssignCurrentEntryStatusOnSetSourceSpec

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5845]
Could we please have an event OnAfterAssignCurrentEntryStatusOnSetSourceSpec in page 6510 in function SetSourceSpec?

Code Example:
TempReservEntry.DeleteAll;
        LastEntryNo := 0;
        if ItemTrackingMgt.IsOrderNetworkEntity(TrackingSpecification."Source Type",
             TrackingSpecification."Source Subtype") and not (FormRunMode = FormRunMode::"Drop Shipment")
        then
            CurrentEntryStatus := CurrentEntryStatus::Surplus
        else
            CurrentEntryStatus := CurrentEntryStatus::Prospect;

        // start kvspsa - Event Raiser
        OnAfterAssignCurrentEntryStatusOnSetSourceSpec(TrackingSpecification, CurrentEntryStatus);
        // stop kvspsa

        // Set controls for Qty to handle:
        SetControls(Controls::Handle, GetHandleSource(TrackingSpecification));
        // Set controls for Qty to Invoice:
        SetControls(Controls::Invoice, GetInvoiceSource(TrackingSpecification));

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterAssignCurrentEntryStatusOnSetSourceSpec(TrackingSpecification: Record "Tracking Specification"; var CurrentEntryStatus: Option Reservation,Tracking,Surplus,Prospect)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
