### ISSUE TITLE
[Event Request] page 361 "Res. Availability Lines" - OnBeforeCalcLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5846]
Could we please have an event OnBeforeCalcLine in page 361 in function CalcLine?

Code Example:
    local procedure CalcLine()
    // start kvspsa - Variables added
        IsHandled: Boolean;
    // stop kvspsa
    begin
        Resource.CalcFields(Capacity, "Qty. on Order (Job)", "Qty. Quoted (Job)", "Qty. on Service Order", "Qty. on Assembly Order");
        // start kvspsa - Code Modification
        QtyOnOrderJob := Resource."Qty. on Order (Job)";
        QtyQuotedJob := Resource."Qty. Quoted (Job)";
        QtyOnServiceOrder := Resource."Qty. on Service Order";
        IsHandled := false;
        OnBeforeCalcLine(Resource, CapacityAfterOrders, CapacityAfterQuotes, NetAvailability, QtyOnOrderJob, QtyQuotedJob, QtyOnServiceOrder, IsHandled);
        if IsHandled then
            exit;
        // stop kvspsa
        CapacityAfterOrders := Resource.Capacity - Resource."Qty. on Order (Job)";
        CapacityAfterQuotes := CapacityAfterOrders - Resource."Qty. Quoted (Job)";
        NetAvailability := CapacityAfterQuotes - Resource."Qty. on Service Order" - Resource."Qty. on Assembly Order";

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeCalcLine(var Resource: Record Resource; var CapacityAfterOrders: Decimal; var CapacityAfterQuotes: Decimal; var NetAvailability: Decimal; var QtyOnOrderJob: Decimal; var QtyQuotedJob: Decimal; var QtyOnServiceOrder: Decimal; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
We already have event here
OnAfterCalcLine(Resource, CapacityAfterOrders, CapacityAfterQuotes, NetAvailability, Rec);
