### ISSUE TITLE
[Event Request] page 228 "Res. Gr. Allocated per Job" - OnActionShowMatrix

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5847]
Could we please have an event OnActionShowMatrix in page 228 in function ShowMatrix?

Code Example:
                trigger OnAction()
                var
                    HorizontalRecord: Record "Job Planning Line";
                    ResGrpPerJobFormWithMatrix: Page "ResGrp. Alloc. per Job Matrix";
                    // start kvspsa - Variables added
                    IsHandled: Boolean;
                // stop kvspsa
                begin
                    // start kvspsa - Event Raiser
                    IsHandled := false;
                    OnActionShowMatrix(JobRec, ResourceGrFilter, MatrixColumnCaptions, MatrixRecords, IsHandled);
                    If IsHandled then
                        exit;
                    // stop kvspsa
                    HorizontalRecord.SetRange("Resource Group No.", ResourceGrFilter);
                    HorizontalRecord.SetRange(Type, HorizontalRecord.Type::Resource);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnActionShowMatrix(var JobRec: Record Job; ResourceGrFilter: Text; MatrixColumnCaptions: Array[32] of Text; MatrixRecords: Array[32] of Record Date; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
