### ISSUE TITLE
[Event Request] page 362 "Res. Gr. Availability Lines" - OnBeforeCalcLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5848]
Could we please have an event OnBeforeCalcLine in page 362 in function CalcLine?

Code Example:
    local procedure CalcLine()
    var
        // start kvspsa - Variables added
        IsHandled: Boolean;
    // stop kvspsa
    begin
        ResGr.CalcFields(Capacity, "Qty. on Order (Job)", "Qty. Quoted (Job)", "Qty. on Service Order");

        // start kvspsa - Code Modification
        QtyOnOrderJob := ResGr."Qty. on Order (Job)";
        QtyQuotedJob := ResGr."Qty. Quoted (Job)";
        QtyOnServiceOrder := ResGr."Qty. on Service Order";
        IsHandled := false;
        OnBeforeCalcLine(ResGr, CapacityAfterOrders, CapacityAfterQuotes, QtyOnOrderJob, QtyQuotedJob, QtyOnServiceOrder, IsHandled);
        if IsHandled then
            exit;
        // stop kvspsa

        CapacityAfterOrders := ResGr.Capacity - ResGr."Qty. on Order (Job)" - ResGr."Qty. on Service Order";
        CapacityAfterQuotes := CapacityAfterOrders - ResGr."Qty. Quoted (Job)";

        OnAfterCalcLine(ResGr, CapacityAfterOrders, CapacityAfterQuotes);
    end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeCalcLine(var ResourceGroup: Record "Resource Group"; var CapacityAfterOrders: Decimal; var CapacityAfterQuotes: Decimal; var QtyOnOrderJob: Decimal; var QtyQuotedJob: Decimal; var QtyOnServiceOrder: Decimal; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
We already have this event
OnAfterCalcLine(ResGr, "Availability After Orders", "Net Availability", Rec);
