### ISSUE TITLE
[Event Request] page 498 Reservation - OnCaseElsePurchaseLinesOnDrillDownTotalQuantity

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5849]
Could we please have an event OnCaseElsePurchaseLinesOnDrillDownTotalQuantity in page 498 in function DrillDownTotalQuantity?

Code Example:
                        DATABASE::"Assembly Line":
                            begin
                                AvailablePurchLines.SetAssemblyLine(AssemblyLine, ReservEntry2);
                                AvailablePurchLines.RunModal;
                            end;
                        // start kvspsa - Event Raiser
                        else
                            OnCaseElsePurchaseLinesOnDrillDownTotalQuantity(Rec, ReservEntry2, AvailablePurchLines);
                    // stop kvspsa
                    end;
                end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnCaseElsePurchaseLinesOnDrillDownTotalQuantity(var EntrySummary: Record "Entry Summary"; var ReservationEntry: Record "Reservation Entry"; var AvailablePurchLines: Page "Available - Purchase Lines")
    begin
    end;

Thank you and kind regards

**Comment by AlexanderYakunin** [comment]
Please review latest preview code base, you don't need this anymore.
