### ISSUE TITLE
[Event Request] page 498 Reservation - OnAfterGetQtyPerUOMFromSource

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5850]
Could we please have additional parameters (QtyReserved, QtyReservedBase, QtyToReserve, QtyToReserveBase) in event OnAfterGetQtyPerUOMFromSource in page 498?

            DATABASE::"Service Line":
                QtyPerUOM := GetQtyPerUomFromServiceLine;
            DATABASE::"Job Planning Line":
                QtyPerUOM := GetQtyPerUomFromJobPlanningLine;
        end;

        // start kvspsa - Additional Parameters
        OnAfterGetQtyPerUOMFromSource(ReservEntry, QtyReserved, QtyReservedBase, QtyToReserve, QtyToReserveBase, QtyPerUOM);
        // stop kvspsa                

    end;

Event:

    local procedure OnAfterGetQtyPerUOMFromSource(var ReservationEntry: Record "Reservation Entry"; var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal; var QtyPerUOM: Decimal)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
