### ISSUE TITLE
[Event Request] page 221 "Resource Allocated per Job" - OnActionShowMatrix

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5851]
Could we please have an event OnActionShowMatrix in page 221 in function ShowMatrix?

Code Example:
                trigger OnAction()
                var
                    HorizontalRecord: Record "Job Planning Line";
                    ResAllPerJobFormWithMatrix: Page "Resource Alloc. per Job Matrix";
                    // start kvspsa - Variables added
                    IsHandled: Boolean;
                // stop kvspsa
                begin
                    // start kvspsa - Event Raiser
                    IsHandled := false;
                    OnActionShowMatrix(JobRec, ResourceFilter, MatrixColumnCaptions, MatrixRecords, AmountType, IsHandled);
                    If IsHandled then
                        exit;
                    // stop kvspsa
                    HorizontalRecord.SetRange("No.", ResourceFilter);
                    HorizontalRecord.SetRange(Type, HorizontalRecord.Type::Resource);

Event:
    [IntegrationEvent(false, false)]
    local procedure OnActionShowMatrix(var JobRec: Record Job; ResourceFilter: Text; MatrixColumnCaptions: Array[32] of Text; MatrixRecords: Array[32] of Record Date; AmountType: Option "Net Change","Balance at Date"; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
