### ISSUE TITLE
[Event Request] page 5793 "Source Documents" - OnActionCardCaseElse

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5852]
Could we please have an event OnActionCardCaseElse in page 5793 in function action(Card)?

actions
    {
        area(navigation)
        {
            group("&Line")
            {
                Caption = '&Line';
                Image = Line;
                action(Card).....

Code Example:
                            "Source Document"::"Service Order":
                                begin
                                    ServiceHeader.Get("Source Subtype", "Source No.");
                                    PAGE.Run(PAGE::"Service Order", ServiceHeader);
                                end;
                            // start kvspsa - Event Raiser
                            else
                                OnActionCardCaseElse(Rec);
                        // stop kvspsa
                        end;
                    end;

Event:
    [IntegrationEvent(TRUE, false)]
    local procedure OnActionCardCaseElse(WarehouseRequest: Record "Warehouse Request")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
