### ISSUE TITLE
[Event Request] report 950 "Create Time Sheets" - OnAfterGetRecordResourceNotTimeAdmin

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5853]
Could we please have an event OnAfterGetRecordResourceNotTimeAdmin in report 950 in DataItem Integer - OnAfterGetRecord?

Code Example:
dataset
    {
        dataitem("Integer"; "Integer")
        {
            DataItemTableView = SORTING(Number);
            dataitem(Resource; Resource)
            {
                DataItemTableView = WHERE("Use Time Sheet" = CONST(true));
                RequestFilterFields = "No.", Type;

                trigger OnAfterGetRecord()
                var
                    TimeSheetMgt: Codeunit "Time Sheet Management";
                begin
                    // start kvspsa - Event Raiser
                    if not IsTimeAdmin then
                        OnAfterGetRecordResourceNotTimeAdmin("No.");
                    // stop kvspsa
                    if CheckExistingPeriods then begin
                        TimeSheetHeader.Init;
                        TimeSheetHeader."No." := NoSeriesMgt.GetNextNo(ResourcesSetup."Time Sheet Nos.", Today, true);
                        TimeSheetHeader."Starting Date" := StartingDate;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordResourceNotTimeAdmin(ResourceNo: Code[20])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
