### ISSUE TITLE
[event-request]ApprovalMgmt - Refactoring required for Event to work as expected

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#5854]
Hi 

In the IsSufficientApprover procedure, the OnAfterIsSufficientApprover event is not called when the ApprovalEntryArgument Table ID is found in the Case statement.  

Please can you refactor the code so instead of exiting from the case statement and bypassing the OnAfterIsSufficientApprover event, the exit is changed to a IsSufficient := ... 

E.g.

Current
======
procedure IsSufficientApprover(UserSetup: Record "User Setup"; ApprovalEntryArgument: Record "Approval Entry"): Boolean
    var
        IsSufficient: Boolean;
    begin
        case ApprovalEntryArgument."Table ID" of
            DATABASE::"Purchase Header":
                exit(IsSufficientPurchApprover(UserSetup, ApprovalEntryArgument."Document Type", ApprovalEntryArgument."Amount (LCY)"));
            DATABASE::"Sales Header":
                exit(IsSufficientSalesApprover(UserSetup, ApprovalEntryArgument."Amount (LCY)"));
            DATABASE::"Gen. Journal Batch":
                Message(ApporvalChainIsUnsupportedMsg, Format(ApprovalEntryArgument."Record ID to Approve"));
            DATABASE::"Gen. Journal Line":
                exit(IsSufficientGenJournalLineApprover(UserSetup, ApprovalEntryArgument));
        end;

        IsSufficient := true;
        OnAfterIsSufficientApprover(UserSetup, ApprovalEntryArgument, IsSufficient);
        exit(IsSufficient);
    end;

Suggested
=======
procedure IsSufficientApprover(UserSetup: Record "User Setup"; ApprovalEntryArgument: Record "Approval Entry"): Boolean
    var
        IsSufficient: Boolean;
    begin
        case ApprovalEntryArgument."Table ID" of
            DATABASE::"Purchase Header":
                IsSufficient := IsSufficientPurchApprover(UserSetup, ApprovalEntryArgument."Document Type", ApprovalEntryArgument."Amount (LCY)");
            DATABASE::"Sales Header":
                IsSufficient := IsSufficientSalesApprover(UserSetup, ApprovalEntryArgument."Amount (LCY)");
            DATABASE::"Gen. Journal Batch":
                Message(ApporvalChainIsUnsupportedMsg, Format(ApprovalEntryArgument."Record ID to Approve"));
            DATABASE::"Gen. Journal Line":
                IsSufficient := IsSufficientGenJournalLineApprover(UserSetup, ApprovalEntryArgument);
            ELSE
              IsSufficient := true;
        end;
        
        OnAfterIsSufficientApprover(UserSetup, ApprovalEntryArgument, IsSufficient);
        exit(IsSufficient);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
