### ISSUE TITLE
Video in BC

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#5855]
Hi,

I am copying question from Yammer since nobody is familiar with this.
How to add a new video with a certain category, when a function which has category is not visible in AL, even if it is documented 5 months ago - https://github.com/microsoft/ALAppExtensions/blob/master/Modules/System/Video/src/Video.Codeunit.al 

It has 4 overloads, but in AL we can see only 2. We are on 15.2 version.
![image](https://user-images.githubusercontent.com/34686682/73451079-13bbf900-4367-11ea-9842-3babe4874dd3.png)
 

An additional question is how to filter Product Videos page for any category when the page cannot be accessed from the extension.
Thanks

**Comment by darjoo** [comment]
@DuttaSoumya

**Comment by StanPesotskiy** [comment]
Your request is not related to the AL **application** extensibility. 
Please post it at https://www.yammer.com/dynamicsnavdev/ where the wider community may give you a valid answer.
