### ISSUE TITLE
[Event Request] Report 511 "Complete IC Inbox Action" - OnBeforeValidateJournalTemplate

### ISSUE THREAD

**Issue by wbor-nvt** [microsoft/ALAppExtensions#5856]
Hello,

I would like to make a change to the validation of the Journal Template during the "Complete IC Inbox Action". (Report 511)

Current Code in the OnPreDataItem Trigger of the "IC Inbox Transaction" DataItem:
![image](https://user-images.githubusercontent.com/53901977/73450470-bf644980-4365-11ea-8bac-71de95481e66.png)

I wish to replace 'GenJnlTemplate.TestField(Type, GenJnlTemplate.Type::Intercompany);' with my own code.

Modification:

            trigger OnPreDataItem()
            var 
                IsHandled: Boolean;
            begin
                if TempGenJnlLine."Journal Template Name" <> '' then begin
                    GenJnlTemplate.Get(TempGenJnlLine."Journal Template Name");
                    IsHandled := false;
                    OnBeforeValidateJournalTemplate(TempGenJnlLine, GenJnlTemplate, IsHandled);
                    if not IsHandled then begin 
                        GenJnlTemplate.TestField(Type, GenJnlTemplate.Type::Intercompany);
                    end;
                    TempGenJnlLine.SetRange("Journal Template Name", GenJnlTemplate.Name);
                    TempGenJnlLine.SetRange("Journal Batch Name", GenJnlBatch.Name);
                end;
                GetGLSetup;
            end;

Publisher:

    [IntegrationEvent(false,false)]
    local procedure OnBeforeValidateJournalTemplate(var TempGenJnlLine: Record "Gen. Journal Line"; GenJnlTemplate: Record "Gen. Journal Template"; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
