### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnBeforeInsertApplEntry

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#5857]
Please add a new publisher event to the function InsertApplEntry as follows:
	
```
LOCAL InsertApplEntry(ItemLedgEntryNo : Integer;InboundItemEntry : Integer;OutboundItemEntry : Integer;TransferedFromEntryNo : Integer;PostingDate : Date;Quantity : Decimal;CostToApply : Boolean)
//>> Start New Publisher Call
OnBeforeInsertApplEntry(ItemLedgEntryNo, InboundItemEntry, OutboundItemEntry, TransferedFromEntryNo, PostingDate, Quantity, CostToApply, IsHandled);
IF IsHandled THEN
  EXIT;
//<< End New Publisher Call

IF Item.IsNonInventoriableType THEN
  EXIT;
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeInsertApplEntry(VAR ItemLedgEntryNo : Integer;VAR InboundItemEntry : Integer;VAR OutboundItemEntry : Integer;VAR TransferedFromEntryNo : Integer;VAR PostingDate : Date;VAR Quantity : Decimal;VAR CostToApply : Boolean;VAR IsHandled : Boolean)
--> Property: GlobalVarAccess set to Yes
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SjoerddeClippelaar** [comment]
Dear Microsoft,

The variables in this new event are not by **var**. Could you change that? We would like to reset the variables.

![image](https://user-images.githubusercontent.com/50202846/90238603-80d83d00-de26-11ea-8a9f-9a1528c06f9c.png)
