### ISSUE TITLE
[Event Request] Codeunit 396 NoSeriesManagement - OnBeforeNoSeriesLineFindLast

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#5859]
Please add a new publisher event to the function SetNoSeriesLineFilter as follows:
	
```
[External] SetNoSeriesLineFilter(VAR NoSeriesLine : Record "No. Series Line";NoSeriesCode : Code[20];StartDate : Date)
.
.
//>> Start New Publisher Call
OnBeforeNoSeriesLineFindLast(NoSeriesLine);
//<< End New Publisher Call
IF NoSeriesLine.FINDLAST THEN BEGIN
  NoSeriesLine.SETRANGE("Starting Date",NoSeriesLine."Starting Date");
  NoSeriesLine.SETRANGE(Open,TRUE);
END;
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeNoSeriesLineFindLast(VAR NoSeriesLine : Record "No. Series Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
