### ISSUE TITLE
[Event Request] Page 46 - "Sales Order Subform" - NoOnAfterValidateOnBeforeSaveAndAutoAsmToOrder

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5860]
Hi AL team,

can you please add the following publisher with "IncludeSender" to NoOnAfterValidate?

    procedure NoOnAfterValidate()
    begin
        InsertExtendedText(false);
        if (Type = Type::"Charge (Item)") and ("No." <> xRec."No.") and
           (xRec."No." <> '')
        then
            CurrPage.SaveRecord;

        // new event begin
        + NoOnAfterValidateOnBeforeSaveAndAutoAsmToOrder();
        // new event end
        SaveAndAutoAsmToOrder;
        ...

    [IntegrationEvent(true, false)]
    local procedure NoOnAfterValidateOnBeforeSaveAndAutoAsmToOrder()
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
