### ISSUE TITLE
Codeunit 99000809 OnTransferAsmBOMOnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#5861]
In Codeunit 99000809 can we add a Publisher **OnTransferAsmBOMOnBeforeGetDefaultBin** in function TransferAsmBOM.

OnTransferAsmBOMOnBeforeGetDefaultBin(PlanningComponent, AsmBOMComp[Level], ReqLine);  //NEW

    // NEW
    [IntegrationEvent(false, false)]
    local procedure OnTransferAsmBOMOnBeforeGetDefaultBin(var PlanningComponent: Record "Planning Component"; var AsmBOMComp: Record "BOM Component"; RequisitionLine: Record "Requisition Line")
    begin
    end; 
    // END  

![image](https://user-images.githubusercontent.com/32099690/73482194-7eb30300-435a-11ea-9044-c76530013c6d.png)

![image](https://user-images.githubusercontent.com/32099690/73482257-a013ef00-435a-11ea-961c-5b18a5e7159f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
