### ISSUE TITLE
[Event Request] Codeunit 7010 - OnBeforeCalcBestDirectUnitCost

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#5863]
Please add a new integration event **OnBeforeCalcBestDirectUnitCost** in **Codeunit 7010**.

```
    local procedure CalcBestDirectUnitCost(var PurchPrice: Record "Purchase Price")
    var
        BestPurchPrice: Record "Purchase Price";
        IsHandled: Boolean;
        BestPurchPriceFound: Boolean;
    begin
+       OnBeforeCalcBestDirectUnitCost(PurchPrice, BestPurchPrice, BestPurchPriceFound, IsHandled)
+       if IsHandled then
+           exit;
        [...]
```

New integration event
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcBestDirectUnitCost(var PurchPrice: Record "Purchase Price"; var BestPurchPrice: Record "Purchase Price"; var BestPurchPriceFound: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
