### ISSUE TITLE
Refactoring: Codeunit 7302 WMS Management

### ISSUE THREAD

**Issue by Hamdi-Amine** [microsoft/ALAppExtensions#5865]
Hello,
I request a code refactoring in codeunit WMS Management (7302) exactly in CreateWhseJnlLine method , the issue that i'm facing is  when i post a negative or positive adjustement transcation with code ( No worksheet : Journal template and journalbatch are empty) with minimum two lots (**WhseLNRequired** is True) and the location is manadatory and bins also mandatory , as result the system post two item ledger entries but only one warehouse ledger entry .

![image](https://user-images.githubusercontent.com/23724827/73543324-98257f00-442e-11ea-9339-a7339bbc1a27.png)

Thanks

**Comment by AlexanderYakunin** [comment]
We don;t know how you are doing this? Can you please provide more information about your scenario and suggested change?
