### ISSUE TITLE
[Event Change] Report 5753 OnBeforeWhseReceiptHeaderInsert

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#5866]
Hi AL team,

can you please pass the parameter WarehouseRequest by var?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
