### ISSUE TITLE
[Request for External] codeunit 12104 LocalApplicationManagement change the scope for function CheckSameMonth and CheckData

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5867]
Hi, Can you change the scope of function CheckSameMonth and CheckData from OnPrem to Cloud?

codeunit 12104 LocalApplicationManagement (probably is only in Italian Localization)
![image](https://user-images.githubusercontent.com/26144133/73549674-54894000-4443-11ea-80ac-ab626e427b2b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
