### ISSUE TITLE
[Request for External] table 39 "Purchase Line" change the scope for function ShowDeferrals

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5868]
Hi, Can you change the scope of function ShowDeferralsfrom OnPrem to Cloud?

table 39 "Purchase Line"
![image](https://user-images.githubusercontent.com/26144133/73549882-c9f51080-4443-11ea-8396-e78b5d8d951c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
