### ISSUE TITLE
[Request for External] table 36 "Sales Header" change the scope for function AssistEdit

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5869]
Hi, Can you change the scope of function AssistEdit OnPrem to Cloud?

table 36 "Sales Header"
![image](https://user-images.githubusercontent.com/26144133/73550105-44259500-4444-11ea-9c59-f00d0789fb93.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
