### ISSUE TITLE
[Request for External] codeunit 82 "Sales-Post + Print" change the scope for function PostAndEmail

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#5870]
Hi, Can you change the scope of function PostAndEmail OnPrem to Cloud?

codeunit 82 "Sales-Post + Print"
![image](https://user-images.githubusercontent.com/26144133/73550363-beeeb000-4444-11ea-94fa-b402cca12c35.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
