### ISSUE TITLE
Finding system application source code for the system application package

### ISSUE THREAD

**Issue by bent-rasmussen** [microsoft/ALAppExtensions#5872]
Given a specific version of system application, e.g. 15.1.37881.38516, we need to find the corresponding source code. Ideally, this would be possible from VS Code via 'AL: download source', but this is not possible, as system application has ShowMyCode = false. This is rather strange for an open source project by the way.

Is there a way to find which commit corresponds to a given version? There are no tags in the repository, so no obvious way to map the system application version to a commit.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
The reason that ShowMyCode is set to false, is to prevent the System Application from being debugged. The system application holds confidential variables, which values we cannot allow developers to see. That's the short version of, why ShowMyCode currently is set to false.

There is no link between the commits here on GitHub and released versions, as the code here on GitHub currently is a copy of our real repository - we're not using GitHub as our true source of code yet. But you should be able to find the code of the System Application based on the build number in the same way, you would find the Base Application! All code is regularly made available in various places. You can read more about how to [get the code for a specific version through Docker here](https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/).

**Comment by JesperSchulz** [comment]
Btw., I will of course take your feedback and see, if we can narrow down the security scope, so that we can make most of the code visible, while just hiding code which needs to be hidden due to security - that however will require a larger work investment and won't get done in the near future.
