### ISSUE TITLE
[Event Request] report 2 "General Journal - Test" - OnAfterAssignTableIdAndNoOnCheckDimensions

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5873]
Could we please have an event OnAfterAssignTableIdAndNoOnCheckDimensions in report 2 in procedure CheckDimensions?

Code Example:
        with GenJournalLine do begin
            if not DimMgt.CheckDimIDComb("Dimension Set ID") then
                AddError(DimMgt.GetDimCombErr);

            TableID[1] := DimMgt.TypeToTableID1("Account Type");
            No[1] := "Account No.";
            TableID[2] := DimMgt.TypeToTableID1("Bal. Account Type");
            No[2] := "Bal. Account No.";
            TableID[3] := DATABASE::Job;
            No[3] := "Job No.";
            TableID[4] := DATABASE::"Salesperson/Purchaser";
            No[4] := "Salespers./Purch. Code";
            TableID[5] := DATABASE::Campaign;
            No[5] := "Campaign No.";
            // start kvspsa - Event Raiser
            OnAfterAssignTableIdAndNoOnCheckDimensions(GenJournalLine, TableID, No);
            // stop kvspsa
            if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
                AddError(DimMgt.GetDimValuePostingErr);
        end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignTableIdAndNoOnCheckDimensions(var GenJournalLine: Record "Gen. Journal Line"; var TableID: Array[10] of Integer; var No: Array[10] of Code[20])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
