### ISSUE TITLE
[Event Request] report 2 "General Journal - Test" - OnAfterTestJobFields

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5874]
Could we please have an event OnAfterTestJobFields in report 2 in procedure TestJobFields?

Code Example:
        with GenJnlLine do begin
            if ("Job No." = '') or ("Account Type" <> "Account Type"::"G/L Account") then
                exit;
            if not Job.Get("Job No.") then
                AddError(StrSubstNo(Text071, Job.TableCaption, "Job No."))
            else
                  if Job.Blocked > Job.Blocked::" " then
                    AddError(
                      StrSubstNo(
                        Text072, Job.FieldCaption(Blocked), Job.Blocked, Job.TableCaption, "Job No."));

            if "Job Task No." = '' then
                AddError(StrSubstNo(Text002, FieldCaption("Job Task No.")))
            else
                if not JT.Get("Job No.", "Job Task No.") then
                    AddError(StrSubstNo(Text071, JT.TableCaption, "Job Task No."))
            // start kvspsa - Event Raiser
            OnAfterTestJobFields(GenJnlLine, ErrorCounter, ErrorText);
            // stop kvspsa
        end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterTestJobFields(var GenJournalLine: Record "Gen. Journal Line"; var ErrorCounter: Integer; var ErrorText: Array[50] of Text[250])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
