### ISSUE TITLE
[Event Request] Report 1005 "Job Journal - Test" - OnCheckJobJournalLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5875]
Could we please have an event OnCheckJobJournalLine in report 1005 in DataItem ErrorLoop OnAfterGetRecord?

Code Example:
                        if Type <> Type::"G/L Account" then
                            if "Gen. Prod. Posting Group" = '' then
                                AddError(StrSubstNo(Text001, FieldCaption("Gen. Prod. Posting Group")))
                            else
                                if not GenPostingSetup.Get("Gen. Bus. Posting Group", "Gen. Prod. Posting Group") then
                                    AddError(
                                      StrSubstNo(
                                        Text004, GenPostingSetup.TableCaption,
                                        "Gen. Bus. Posting Group", "Gen. Prod. Posting Group"));

                        if "Document No." = '' then
                            AddError(StrSubstNo(Text001, FieldCaption("Document No.")));
                        // start kvspsa - Event Raiser
                        OnCheckJobJournalLine("Job Journal Line", ErrorCounter, ErrorText);
                        // stop kvspsa

                        if "No." = '' then
                            AddError(StrSubstNo(Text001, FieldCaption("No.")))
                        else

Event:
    [IntegrationEvent(false, false)]
    local procedure OnCheckJobJournalLine(JobJournalLine: Record "Job Journal Line"; var ErrorCounter: Integer; var ErrorText: Array[50] of Text[250])
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
