### ISSUE TITLE
[Event Request] Report 1005 "Job Journal - Test" - OnAfterAssignTableIdAndNoOnAfterGetRecordJobJnlLine

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5876]
Could we please have an event OnAfterAssignTableIdAndNoOnAfterGetRecordJobJnlLine in report 1005 in DataItem ErrorLoop OnAfterGetRecord?

Code Example:
                        TableID[1] := DATABASE::Job;
                        No[1] := "Job No.";
                        TableID[2] := DimMgt.TypeToTableID2(Type);
                        No[2] := "No.";
                        TableID[3] := DATABASE::"Resource Group";
                        No[3] := "Resource Group No.";
                        // start kvspsa - Event Raiser
                        OnAfterAssignTableIdAndNoOnAfterGetRecordJobJnlLine("Job Journal Line", TableID, No);
                        // stop kvspsa
                        if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
                            AddError(DimMgt.GetDimValuePostingErr);
                    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignTableIdAndNoOnAfterGetRecordJobJnlLine(var JobJournalLine: Record "Job Journal Line"; var TableID: Array[10] of Integer; var No: Array[10] of Code[20]);
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
