### ISSUE TITLE
[Event Request] Report 953 "Move Time Sheets to Archive" - OnBeforePreDataItemTimesheetHeader

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5877]
Could we please have an event OnBeforePreDataItemTimesheetHeader in report 953 in DataItem Time Sheet Header OnPreDataItem?

Code Example:
            trigger OnPreDataItem()
            begin
                // start kvspsa - Event Raiser
                OnBeforePreDataItemTimesheetHeader("Time Sheet Header");
                // stop kvspsa
                CounterTotal := Count;
                Window.Open(Text001);
            end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePreDataItemTimesheetHeader(var TimeSheetHeader: Record "Time Sheet Header")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
