### ISSUE TITLE
[Event Request] Report 1095 "Update Job Item Cost" - OnFilterValueEntryOnAfterGetRecordItemLedgerEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5878]
Could we please have an event OnFilterValueEntryOnAfterGetRecordItemLedgerEntry in report 1095 in DataItem "Job Ledger Entry" OnAfterGetRecord?

Code Example:
                        ValueEntry.SetRange("Job No.", "Job Ledger Entry"."Job No.");
                        ValueEntry.SetRange("Job Task No.", "Job Ledger Entry"."Job Task No.");
                        // start kvspsa - Event Raiser
                        OnFilterValueEntryOnAfterGetRecordItemLedgerEntry(ValueEntry, "Job Ledger Entry");
                        // stop kvspsa
                        ValueEntry.SetRange("Job Ledger Entry No.", "Job Ledger Entry"."Entry No.");
                        ValueEntry.SetRange("Item Ledger Entry No.", "Entry No.");
                        ValueEntry.SetRange("Item Ledger Entry Type", ValueEntry."Item Ledger Entry Type"::"Negative Adjmt.");
                        ValueEntry.SetRange("Document Type", ValueEntry."Document Type"::"Purchase Invoice");

Event:
    [IntegrationEvent(false, false)]
    local procedure OnFilterValueEntryOnAfterGetRecordItemLedgerEntry(var ValueEntry: Record "Value Entry"; JobLedgerEntry: Record "Job Ledger Entry")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
