### ISSUE TITLE
[Event Request] Report 1095 "Update Job Item Cost" - OnAfterValueEntry2ModifyallOnAfterGetRecordItemLedgerEntry

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5879]
Could we please have an event OnAfterValueEntry2ModifyallOnAfterGetRecordItemLedgerEntry in report 1095 in DataItem Item Ledger Entry" OnAfterGetRecord?

Code Example:
                                AddJobCostValue(JobLedgerEntryCostValue, JobLedgerEntryCostValueACY, ValueEntry2, ValueEntry.Inventoriable);

                                ValueEntry2.SetRange("Job Ledger Entry No.", 0);
                                ValueEntry2.ModifyAll("Job No.", ValueEntry."Job No.");
                                ValueEntry2.ModifyAll("Job Task No.", ValueEntry."Job Task No.");
                                ValueEntry2.ModifyAll("Job Ledger Entry No.", ValueEntry."Job Ledger Entry No.");
                                // start kvspsa - Event Raiser
                                OnAfterValueEntry2ModifyallOnAfterGetRecordItemLedgerEntry(ValueEntry2, ValueEntry);
                                // stop kvspsa
                            end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterValueEntry2ModifyallOnAfterGetRecordItemLedgerEntry(var NewValueEntry: Record "Value Entry"; OldValueEntry: Record "Value Entry")
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
