### ISSUE TITLE
[Length of Field] Table 1003 Job Planning Line -  User ID

### ISSUE THREAD

**Issue by mynavblog** [Microsoft/ALAppExtensions#588]
Dear Team,

Could you change length of field User ID from 50 to 80 in  table 1003 Job Planning Line which should be a standard for UserId function

![image](https://user-images.githubusercontent.com/37371997/49806151-44059a00-fd57-11e8-9332-86ed026eab19.png)

Thank you in advance.

Best regards,
Krzysztof

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.

Extending the User ID appears to be a larger effort, as all User IDs in Business Central are of length 50. We can't just update a single length. When posting your idea to bcideas, please add a justification for why you think this would be a good idea. Thanks!
