### ISSUE TITLE
[Event Request] Report 1095 "Update Job Item Cost" - OnBeforePostTotalCostAdjustment

### ISSUE THREAD

**Issue by MiRo65** [microsoft/ALAppExtensions#5880]
Could we please have an event OnBeforePostTotalCostAdjustment in report 1095 in function PostTotalCostAdjustment?

Code Example:
    begin
        // start kvspsa - Event Raiser
        IsHandled := false;
        OnBeforePostTotalCostAdjustment(JobLedgEntry, "Item Ledger Entry", JobLedgerEntryCostValue, JobLedgerEntryCostValueACY, AdjustJobCost, AdjustJobCostLCY, NoOfJobLedgEntry, iNoOfNewJobLedgEntryGlob, IsHandled);
        if IsHandled then
            exit;
        // stop kvspsa
        if JobLedgEntry."Total Cost (LCY)" <> -JobLedgerEntryCostValue then begin

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostTotalCostAdjustment(var JobLedgEntry: Record "Job Ledger Entry"; ItemLedgerEntry: Record "Item Ledger Entry"; JobLedgerEntryCostValue: Decimal; JobLedgerEntryCostValueACY: Decimal; var AdjustJobCost: Decimal; var AdjustJobCostLCY: Decimal; var NoOfJobLedgEntry: Integer; var iNoOfNewJobLedgEntryGlob: Integer; var IsHandled: Boolean)
    begin
    end;

Thank you and kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
