### ISSUE TITLE
[Event Request] Table 37/39 OnShowItemChargeAssgntOnBeforeCalcItemCharge

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5881]
In table 37 we Need an addtional VAR Parameter ItemChargeAssgntSales in OnShowItemChargeAssgntOnBeforeCalcItemCharge:

old:
LOCAL [IntegrationEvent] OnShowItemChargeAssgntOnBeforeCalcItemCharge(VAR SalesLine : Record "Sales Line";VAR ItemChargeAssgntLineAmt : Decimal;Currency : Record Currency;VAR IsHandled : Boolean)
new:
LOCAL [IntegrationEvent] OnShowItemChargeAssgntOnBeforeCalcItemCharge(VAR SalesLine : Record "Sales Line";VAR ItemChargeAssgntSales : Record "Item Charge Assignment (Sales)";VAR ItemChargeAssgntLineAmt : Decimal;Currency : Record Currency;VAR IsHandled : Boolean)

we Need the same trigger in table 39 in ShowItemChargeAssgnt:
[External] ShowItemChargeAssgnt()
GET("Document Type","Document No.","Line No.");
TESTFIELD("No.");
TESTFIELD(Quantity);

IF Type <> Type::"Charge (Item)" THEN
  ERROR(ItemChargeAssignmentErr);

GetPurchHeader;
IF PurchHeader."Currency Code" = '' THEN
  Currency.InitRoundingPrecision
ELSE
  Currency.GET(PurchHeader."Currency Code");
IF ("Inv. Discount Amount" = 0) AND
   ("Line Discount Amount" = 0) AND
   (NOT PurchHeader."Prices Including VAT")
THEN
  ItemChargeAssgntLineAmt := "Line Amount"
ELSE
  IF PurchHeader."Prices Including VAT" THEN
    ItemChargeAssgntLineAmt :=
      ROUND(CalcLineAmount / (1 + "VAT %" / 100),Currency."Amount Rounding Precision")
  ELSE
    ItemChargeAssgntLineAmt := CalcLineAmount;

ItemChargeAssgntPurch.RESET;
ItemChargeAssgntPurch.SETRANGE("Document Type","Document Type");
ItemChargeAssgntPurch.SETRANGE("Document No.","Document No.");
ItemChargeAssgntPurch.SETRANGE("Document Line No.","Line No.");
ItemChargeAssgntPurch.SETRANGE("Item Charge No.","No.");
IF NOT ItemChargeAssgntPurch.FINDLAST THEN BEGIN
  ItemChargeAssgntPurch."Document Type" := "Document Type";
  ItemChargeAssgntPurch."Document No." := "Document No.";
  ItemChargeAssgntPurch."Document Line No." := "Line No.";
  ItemChargeAssgntPurch."Item Charge No." := "No.";
  ItemChargeAssgntPurch."Unit Cost" :=
    ROUND(ItemChargeAssgntLineAmt / Quantity,
      Currency."Unit-Amount Rounding Precision");
END;

//+++++++++++++++++++++++++++++++++++++++++
IsHandled := FALSE;
OnShowItemChargeAssgntOnBeforeCalcItemCharge(VAR Rec,VAR ItemChargeAssgntPurch,VAR ItemChargeAssgntLineAmt,Currency,IsHandled);
IF NOT IsHandled THEN
//-----------------------------------------

ItemChargeAssgntLineAmt :=
  ROUND(
    ItemChargeAssgntLineAmt * ("Qty. to Invoice" / Quantity),
    Currency."Amount Rounding Precision");

IF IsCreditDocType THEN
  AssignItemChargePurch.CreateDocChargeAssgnt(ItemChargeAssgntPurch,"Return Shipment No.")
ELSE
  AssignItemChargePurch.CreateDocChargeAssgnt(ItemChargeAssgntPurch,"Receipt No.");
CLEAR(AssignItemChargePurch);
COMMIT;

ItemChargeAssgnts.Initialize(Rec,ItemChargeAssgntLineAmt);
ItemChargeAssgnts.RUNMODAL;

CALCFIELDS("Qty. to Assign");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
