### ISSUE TITLE
[Event Request] Table 7302 - OnAfterCalcTotalQtyAvailToTake

### ISSUE THREAD

**Issue by murielaimar** [microsoft/ALAppExtensions#5882]
Please add a new integration event OnAfterCalcTotalQtyAvailToTake in Table 7302

procedure CheckDecreaseBinContent(Qty: Decimal; var QtyBase: Decimal; DecreaseQtyBase: Decimal)
…
QtyAvailToPickBase := CalcTotalQtyAvailToTake(DecreaseQtyBase);
'+ OnAfterCalcTotalQtyAvailToTake( WhseActivLine, QtyAvailToPickBase, DecreaseQtyBase)
if QtyAvailToPickBase < QtyBase then begin
  GetItem("Item No.");
  QtyAvailToPick :=
    Round(QtyAvailToPickBase / UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code"), UOMMgt.QtyRndPrecision);
   if QtyAvailToPick = Qty then
     QtyBase := QtyAvailToPickBase // rounding issue- qty is same, but not qty (base)
   else
     FieldError("Quantity (Base)", StrSubstNo(Text006, Abs(QtyBase)));
 end;

New integration event
[IntegrationEvent (false, false)]
Local procedure OnAfterCalcTotalQtyAvailToTake (WhseActivLine : Record "Warehouse Activity Line", var QtyAvailToPickBase: Decimal, DecreaseQtyBase : Decimal)
begin
end ;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
