### ISSUE TITLE
[Event Request] CodeUnit 228 OnAfterCalcPurchDiscount

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5885]
OnAfterCalcPurchDiscount from #4687 is not yet implemented in 15.2 nor 16 bc insider, please add the missing Event:

LOCAL CalcPurchDisc(VAR PurchHeader : Record "Purchase Header")
PurchSetup.GET;
IF PurchSetup."Calc. Inv. Discount" THEN BEGIN
PurchLine.RESET;
PurchLine.SETRANGE("Document Type",PurchHeader."Document Type");
PurchLine.SETRANGE("Document No.",PurchHeader."No.");
PurchLine.FINDFIRST;
OnCalcPurchDiscOnBeforeRun(PurchHeader,PurchLine);
CODEUNIT.RUN(CODEUNIT::"Purch.-Calc.Discount",PurchLine);
PurchHeader.GET(PurchHeader."Document Type",PurchHeader."No.");
COMMIT;
END;
//+++++++++++++++++++++++++++
OnAfterCalcPurchDiscount(VAR PurchHeader; PurchLine);
//----------------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
