### ISSUE TITLE
[Event Request] Codeunit 14 "Gen. Jnl.-Show Entries" - Show custom page

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#5886]
Dear BaseApp team,

I'd like to kindly ask you to review the following request.
In codeunit 14 (Gen. Jnl.-Show Entries) when page "Customer Ledger Entries" is about to be shown to the user we'd like to display a different custom page:
![OnBeforeShowCustomerLedgerEntries-01](https://user-images.githubusercontent.com/42442951/73660573-1b4e0b80-46a1-11ea-80d1-b17a0c922ee9.png)

The desired event signature is as follows:
![OnBeforeShowCustomerLedgerEntries-02](https://user-images.githubusercontent.com/42442951/73660606-3456bc80-46a1-11ea-8311-6698ab28ed10.png)

Please consider adding such a modification if it looks appropriate.

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
