### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134999 "ERM Excel Reports"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5889]
[Event Request] Application “Tests-ERM”, Codeunit 134999 "ERM Excel Reports"
![pic1](https://user-images.githubusercontent.com/45795262/73665644-be9f2080-46a1-11ea-8cfe-da8a64db14e3.png)

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73665653-c4950180-46a1-11ea-828c-30f95f72b804.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
