### ISSUE TITLE
[Event Request] Application “Tests-Job”, Codeunit 132521 "JOBs-60SP1-Scripts"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5890]
[Event Request] Application “Tests-Job”, Codeunit 132521 "JOBs-60SP1-Scripts"
![pic1](https://user-images.githubusercontent.com/45795262/73665850-1b024000-46a2-11ea-8e4c-063f8dac13f7.png)

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73665855-1e95c700-46a2-11ea-9635-fdca883fc3eb.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
