### ISSUE TITLE
[Event Request] Application “Tests-Job”, Codeunit 136300 "Job Consumption Basic"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5891]
[Event Request] Application “Tests-Job”, Codeunit 136300 "Job Consumption Basic"
![pic1](https://user-images.githubusercontent.com/45795262/73665976-53a21980-46a2-11ea-9aef-ad65f24c5449.png)

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73665982-569d0a00-46a2-11ea-902f-3b2f54f396ab.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
