### ISSUE TITLE
[Event Request] Application “Tests-Job”, Codeunit 134153 "Test Intrastat"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5892]
[Event Request] Application “Tests-Job”, Codeunit 134153 "Test Intrastat"
![pic1](https://user-images.githubusercontent.com/45795262/73666105-8a782f80-46a2-11ea-8cc5-8c674b319ae1.png)

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73666109-8d732000-46a2-11ea-9cb5-e17ec63fa789.png)

**Comment by JoergPernberg** [comment]
There is an error in the headline. The app is "Tests-Local" not "Tests-Job".
Sorry for the mistake

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
