### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 134163 "Company Init Unit Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5893]
[Event Request] Application “Tests-Misc”, Codeunit 134163 "Company Init Unit Test"
![pic1](https://user-images.githubusercontent.com/45795262/73666237-c3b09f80-46a2-11ea-80f9-d6a431a1ac25.png)

Could you please insert the OnTestInitialize Event at the beginning of the test procedure TestCompanyInitialize?
![pic2](https://user-images.githubusercontent.com/45795262/73666245-c90dea00-46a2-11ea-986f-69fc731d56fc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
