### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 134235 "Record Set UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5894]
[Event Request] Application “Tests-Misc”, Codeunit 134235 "Record Set UT"
![pic1](https://user-images.githubusercontent.com/45795262/73666397-0a9e9500-46a3-11ea-9cc9-e0c696804136.png)

Could you please insert the OnTestInitialize Event at the beginning of the test procedure FindRecordMgt_FindRecordByNo_GLAccountFilters?
![pic2](https://user-images.githubusercontent.com/45795262/73666407-0e321c00-46a3-11ea-8105-a00de8f10be1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
