### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 135302 "Corr. Credit Memo Notifcation"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5895]
[Event Request] Application “Tests-Misc”, Codeunit 135302 "Corr. Credit Memo Notifcation"
![pic1](https://user-images.githubusercontent.com/45795262/73666505-34f05280-46a3-11ea-830b-57202ee69031.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73666513-37eb4300-46a3-11ea-9447-94a887d0fa55.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
