### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 139033 "Test Job Queue Status"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5896]
[Event Request] Application “Tests-Misc”, Codeunit 139033 "Test Job Queue Status"
![pic1](https://user-images.githubusercontent.com/45795262/73666649-69fca500-46a3-11ea-8749-3270a0c875bd.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73666656-6cf79580-46a3-11ea-97e9-e62d0d4800d9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
