### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 138400 "RS Pack Content - Evaluation"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5897]
[Event Request] Application “Tests-Misc”, Codeunit 138400 "RS Pack Content - Evaluation"
![pic1](https://user-images.githubusercontent.com/45795262/73666993-ec856480-46a3-11ea-8425-0e18c89ae28f.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure PostSalesInvoices?
![pic2](https://user-images.githubusercontent.com/45795262/73667013-f1e2af00-46a3-11ea-9e1c-d88120d3e67b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
