### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 134449 "County Visibility Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5898]
[Event Request] Application “Tests-Misc”, Codeunit 134449 "County Visibility Test"
![pic1](https://user-images.githubusercontent.com/45795262/73667712-f5c30100-46a4-11ea-97d5-67148220b81e.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?
![pic2](https://user-images.githubusercontent.com/45795262/73667718-f8bdf180-46a4-11ea-9473-da0b5a6fecc1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
