### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 139151 DocumentSendingPostTests

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5899]
[Event Request] Application “Tests-Misc”, Codeunit 139151 DocumentSendingPostTests
![pic1](https://user-images.githubusercontent.com/45795262/73667844-3458bb80-46a5-11ea-9a44-a5c6c9b38bf1.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73667863-3c186000-46a5-11ea-93de-08ce3326e760.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
