### ISSUE TITLE
[Request for External] Codeunit 426 - Payment Tolerance Management change scope value

### ISSUE THREAD

**Issue by Nyryus** [microsoft/ALAppExtensions#5902]
Hi,
please, change function "Suppress Commit" scope from OnPrem to Cloud.
![immagine](https://user-images.githubusercontent.com/40896051/73767768-2d4ead80-4778-11ea-8e90-7bed10b04e27.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
