### ISSUE TITLE
[Enum Request] TableExtension 13620 "Payment Method" - Field "Payment Type Validation"

### ISSUE THREAD

**Issue by Avanti05** [microsoft/ALAppExtensions#5903]
[Enum Request] TableExtension 13620 "Payment Method" - Field "Payment Type Validation", and implemetation of Interface to extend new Validation types.

The table extension is a part of "Payment and Reconciliation Formats (DK)".

The field is mainly used for validating the content of the field "Payment Reference". 

Best regards 
Martin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
