### ISSUE TITLE
[Event Request] Table 7326 OnAutofillQtyToHandleOnbeforeModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#5904]
Please correct the Name of the trigger in table 7326 in 15.2.39040.0:

old:
OnAutofillQtyToHandleOnbeforeModift
new:
OnAutofillQtyToHandleOnbeforeModify

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
