### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 136149 "Chart Configuration Tool"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5905]
[Event Request] Application “Tests-Misc”, Codeunit 136149 "Chart Configuration Tool"
![pic1](https://user-images.githubusercontent.com/45795262/73825634-a09a0300-47fc-11ea-88fa-22a3dc5a04e8.png)
Could you please insert the OnTestInitialize Event at the beginning of each test procedure?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
