### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 133008 "Item Tracking Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5906]
[Event Request] Application “Tests-Misc”, Codeunit 133008 "Item Tracking Test"
![pic1](https://user-images.githubusercontent.com/45795262/73825734-d2ab6500-47fc-11ea-8ade-012b3d0ac368.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
