### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 138500 "Common Demodata"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5907]
[Event Request] Application “Tests-Misc”, Codeunit 138500 "Common Demodata"
![pic1](https://user-images.githubusercontent.com/45795262/73825827-fbcbf580-47fc-11ea-97ed-ec4f0f9e261f.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?

**Comment by JoergPernberg** [comment]
Will this event shipped in a future update?
