### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 134625 "Graph Subscription Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5908]
[Event Request] Application “Tests-Graph”, Codeunit 134625 "Graph Subscription Tests"
![pic1](https://user-images.githubusercontent.com/45795262/73826156-92001b80-47fd-11ea-88e0-48c68ce72afe.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73826164-9593a280-47fd-11ea-9062-490e1db692ab.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
