### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 134634 "Graph Collect Mgt Journal Line"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5909]
[Event Request] Application “Tests-Graph”, Codeunit 134634 "Graph Collect Mgt Journal Line"
![pic1](https://user-images.githubusercontent.com/45795262/73826235-bc51d900-47fd-11ea-9fec-22734dc07219.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
