### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 135514 "Sales Order Line E2E Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5911]
[Event Request] Application “Tests-Graph”, Codeunit 135514 "Sales Order Line E2E Test"
![pic1](https://user-images.githubusercontent.com/45795262/73826595-5d409400-47fe-11ea-8c1e-edea7ef37e3b.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
