### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 135515 "Customer Payments E2E Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5912]
[Event Request] Application “Tests-Graph”, Codeunit 135515 "Customer Payments E2E Test"
![pic1](https://user-images.githubusercontent.com/45795262/73826721-8eb95f80-47fe-11ea-956f-be7bdc956a12.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
