### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 135534 "Sales Cr. Memo Line E2E Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5913]
[Event Request] Application “Tests-Graph”, Codeunit 135534 "Sales Cr. Memo Line E2E Test"
![pic1](https://user-images.githubusercontent.com/45795262/73826841-bf00fe00-47fe-11ea-81b8-c988a54d4116.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
