### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 135538 "Purchase Invoice Line E2E Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5914]
[Event Request] Application “Tests-Graph”, Codeunit 135538 "Purchase Invoice Line E2E Test"
![pic1](https://user-images.githubusercontent.com/45795262/73826912-e6f06180-47fe-11ea-9b35-ba77444bcd2b.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
