### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138914 "O365 Sales Invoice Attachments"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5915]
[Event Request] Application “Tests-Graph”, Codeunit 138914 "O365 Sales Invoice Attachments"
![pic1](https://user-images.githubusercontent.com/45795262/73826997-1010f200-47ff-11ea-915d-37edee11a143.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
