### ISSUE TITLE
[BUG] Event OnBeforeInsertNewProdBOMLine Report 99001043

### ISSUE THREAD

**Issue by hhout** [microsoft/ALAppExtensions#5918]
We would like to use an event in report 99001043 “Exchange Production BOM Item” which has 2 Production BOM Lines as parameters. One of which is the new record you are inserting and one which should be the line you are coming from.

**Reference**
The integration event OnBeforeInsertNewProdBOMLine in Report 99001043 is requested via:
#625

**Scenario**
You have a Production BOM with multiple lines e.g. item 1000 and 2000. 
Run the report, filter on item 1000 and choose to not create a new version.

**Issue:**
Now you will get an incorrect FromProductionBOMLine record as parameter in the event, this is caused by a findlast on ProdBOMLine3 (which is passed in the event). We would expect ProdBOMLine to be passed as parameter instead here.

[IntegrationEvent(false, false)]
local procedure OnBeforeInsertNewProdBOMLine(var ProductionBOMLine: Record "Production BOM Line"; FromProductionBOMLine: Record "Production BOM Line"; QtyMultiply: Decimal)
begin
end;

Detailed report 99001043 code analysis in the attached file.
[Code analysis ProdBOMLine.docx](https://github.com/microsoft/ALAppExtensions/files/4158899/Code.analysis.ProdBOMLine.docx)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
