### ISSUE TITLE
[Event Request] Table 37 Sales Line: Be able to skip the line TESTFIELD("Unit Price");

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5919]
Hello.
In Table 37 when validating "Line Amount" there is a mandatory TESTFIELD on the "Unit Price" field.
For many of our customers, when selling stock, they also ship a little sample of a new item on a zero price. (It needs to be on documents to clear customs, etc.) So, we need to be able to validate the "Line Amount" field with a zero price.

Can we get an event with a Boolean VAR Parameter, where the returned value will dictate if the TESTFIELD of the "Unit Price" is done?

(Or can it be handled in a similar way that the StatusCheckSuspended variable is handled? ... That we call an [External] function that sets a global variable that suspends this check?)

**Comment by AlexanderYakunin** [comment]
Can you point to any place in the code? We cannot process this kind of requests.

**Comment by KristjanGaukur** [comment]
Sorry. Here is a better description.

![image](https://user-images.githubusercontent.com/57808351/74050376-d8a47000-49cd-11ea-9742-be292ef44026.png)

In Table 37, Field 103 "Line Amount": There are 3 TESTFIELD lines, and I need to be able to bypass the one with "Unit Price".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
