### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 136580 "Email Address Selection"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5920]
[Event Request] Application “Tests-Graph”, Codeunit 136580 "Email Address Selection"
![pic1](https://user-images.githubusercontent.com/45795262/73844277-8b36d000-4820-11ea-98c1-345c93087af9.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
