### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139050 "Add-in Hyperlink Purchasing"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5921]
[Event Request] Application “Tests-Graph”, Codeunit 139050 "Add-in Hyperlink Purchasing"
![pic1](https://user-images.githubusercontent.com/45795262/73844369-bde0c880-4820-11ea-951e-ee72014e56f1.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73844374-c1744f80-4820-11ea-9c36-dcc88cb11053.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
