### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139048 "SMB Office Pages"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5922]
[Event Request] Application “Tests-Graph”, Codeunit 139048 "SMB Office Pages"
![pic1](https://user-images.githubusercontent.com/45795262/73844963-e9b07e00-4821-11ea-835e-5f53c0369641.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73844966-ecab6e80-4821-11ea-8f8f-fbb2d5cd241f.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
