### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139051 "Add-in Hyperlink Sales"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5923]
[Event Request] Application “Tests-Graph”, Codeunit 139051 "Add-in Hyperlink Sales"
![pic1](https://user-images.githubusercontent.com/45795262/73845090-27ada200-4822-11ea-8236-bdfc53e18a9c.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845095-2a0ffc00-4822-11ea-8bbc-fb2d14263a77.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
