### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139052 "Office Addin Initiate Tasks"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5924]
[Event Request] Application “Tests-Graph”, Codeunit 139052 "Office Addin Initiate Tasks"
![pic1](https://user-images.githubusercontent.com/45795262/73845179-5a579a80-4822-11ea-9040-b3d9c149716f.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845185-5d528b00-4822-11ea-8a99-a9652de6a0de.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
