### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139053 "Office Addin Popout"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5925]
[Event Request] Application “Tests-Graph”, Codeunit 139053 "Office Addin Popout"
![pic1](https://user-images.githubusercontent.com/45795262/73845262-8b37cf80-4822-11ea-960a-26bf9e621f69.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845266-8d019300-4822-11ea-9029-2694f14e39e8.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
