### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139056 "Outlook Add-in Commands"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5926]
[Event Request] Application “Tests-Graph”, Codeunit 139056 "Outlook Add-in Commands"
![pic1](https://user-images.githubusercontent.com/45795262/73845359-b9b5aa80-4822-11ea-8a34-bb684750412f.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845364-bc180480-4822-11ea-9cfb-5e4d3cad118e.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
