### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139058 "Office OCR Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5927]
[Event Request] Application “Tests-Graph”, Codeunit 139058 "Office OCR Test"
![pic1](https://user-images.githubusercontent.com/45795262/73845426-e964b280-4822-11ea-88db-aacafde7e1c4.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845431-ec5fa300-4822-11ea-8a4f-2642fd3480ce.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
