### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 139062 "Add-in Automatic Line Gen."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5928]
[Event Request] Application “Tests-Graph”, Codeunit 139062 "Add-in Automatic Line Gen."
![pic1](https://user-images.githubusercontent.com/45795262/73845505-1add7e00-4823-11ea-9dfa-7db67797fd25.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845518-203ac880-4823-11ea-902b-c4fbf5dd431b.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Integration" should be the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
