### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138900 "O365 Test Email Setup"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5929]
[Event Request] Application “Tests-Graph”, Codeunit 138900 "O365 Test Email Setup"
![pic1](https://user-images.githubusercontent.com/45795262/73845609-4c564980-4823-11ea-86cb-2b473bf041e1.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Init?
![pic2](https://user-images.githubusercontent.com/45795262/73845625-51b39400-4823-11ea-8124-4144bc1eb86e.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Invoicing" is the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
