### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138901 "O365 Test Item Selection P2124"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5930]
[Event Request] Application “Tests-Graph”, Codeunit 138901 "O365 Test Item Selection P2124"
![pic1](https://user-images.githubusercontent.com/45795262/73845685-73ad1680-4823-11ea-94e6-90ea3217db05.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Init?
![pic2](https://user-images.githubusercontent.com/45795262/73845691-77d93400-4823-11ea-919a-0bfe6c3aeb56.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Invoicing" is the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
