### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138904 "O365 Sales Totals Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5931]
[Event Request] Application “Tests-Graph”, Codeunit 138904 "O365 Sales Totals Tests"
![pic1](https://user-images.githubusercontent.com/45795262/73845764-9a6b4d00-4823-11ea-9035-657358c18bf7.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845770-9d663d80-4823-11ea-8d47-b01bfc685aa6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
