### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138905 "O365 Combined Sales Doc. Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5932]
[Event Request] Application “Tests-Graph”, Codeunit 138905 "O365 Combined Sales Doc. Tests"
![pic1](https://user-images.githubusercontent.com/45795262/73845851-bff85680-4823-11ea-9257-62aaa94efff2.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845859-c25ab080-4823-11ea-9c8c-5cf0135dcc60.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Invoicing" is the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
