### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138920 "O365 Sales Discounts"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5933]
[Event Request] Application “Tests-Graph”, Codeunit 138920 "O365 Sales Discounts"
![pic1](https://user-images.githubusercontent.com/45795262/73845952-efa75e80-4823-11ea-9942-6ad92a5af969.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73845960-f209b880-4823-11ea-904b-b88dfbf8f271.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Invoicing" is the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
