### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138933 "O365 Contact Lookup"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5934]
[Event Request] Application “Tests-Graph”, Codeunit 138933 "O365 Contact Lookup"
![pic1](https://user-images.githubusercontent.com/45795262/73846048-19608580-4824-11ea-8ba6-0c0a7b22cca3.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73846052-1bc2df80-4824-11ea-9421-163e53b3af13.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Invoicing" is the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
