### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138942 "BC O365 Contact Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5935]
[Event Request] Application “Tests-Graph”, Codeunit 138942 "BC O365 Contact Tests"
![pic1](https://user-images.githubusercontent.com/45795262/73846219-6f352d80-4824-11ea-8e74-f86f9e0dcc78.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Init?
![pic2](https://user-images.githubusercontent.com/45795262/73846225-71978780-4824-11ea-8c03-c01eeb73ae6c.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Invoicing" is the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
