### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138963 "BC Test Send Customer Data"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5936]
[Event Request] Application “Tests-Graph”, Codeunit 138963 "BC Test Send Customer Data"
![pic1](https://user-images.githubusercontent.com/45795262/73846392-c0452180-4824-11ea-8a2e-0b46b307b432.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?
![pic2](https://user-images.githubusercontent.com/45795262/73846399-c3401200-4824-11ea-8782-61b8ee3f0501.png)
![pic3](https://user-images.githubusercontent.com/45795262/73846402-c63b0280-4824-11ea-9172-11b5c543f510.png)

**Comment by JoergPernberg** [comment]
Error in headline. "Tests-Invoicing" is the correct app. Sorry for this

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
