### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 142060 "ERM Sales/Purchase Report"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5937]
[Event Request] Application “Tests-Graph”, Codeunit 142060 "ERM Sales/Purchase Report"
![pic1](https://user-images.githubusercontent.com/45795262/73846523-f5517400-4824-11ea-85e0-6ee86a2ea5d2.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize
![pic2](https://user-images.githubusercontent.com/45795262/73846529-f7b3ce00-4824-11ea-9296-3b0919c883a4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
