### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 142061 "ERM Batch Reports DACH"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5938]
[Event Request] Application “Tests-Graph”, Codeunit 142061 "ERM Batch Reports DACH"
![pic1](https://user-images.githubusercontent.com/45795262/73847059-d6071680-4825-11ea-8eb0-c2dcc88c51ac.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73847066-d7d0da00-4825-11ea-8d6f-70d9e0147d68.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
