### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 142062 "ERM Reports DACH"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5939]
[Event Request] Application “Tests-Graph”, Codeunit 142062 "ERM Reports DACH"
![pic1](https://user-images.githubusercontent.com/45795262/73847158-02229780-4826-11ea-967c-c131f5058045.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73847161-03ec5b00-4826-11ea-97a4-825ca5fe5814.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
