### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 142076 "Payment Tolerance"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5940]
[Event Request] Application “Tests-Graph”, Codeunit 142076 "Payment Tolerance"
![pic1](https://user-images.githubusercontent.com/45795262/73847258-3007dc00-4826-11ea-80eb-4a4495f329b6.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedures SalesPmtDiscountDateWhenUseZeroPmtDisc, PurchPmtDiscountDateWhenUseZeroPmtDisc?
![pic2](https://user-images.githubusercontent.com/45795262/73847266-339b6300-4826-11ea-821c-370b95bbad91.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
