### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 142081 "Test Intrastat DACH"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#5941]
[Event Request] Application “Tests-Graph”, Codeunit 142081 "Test Intrastat DACH"
![pic1](https://user-images.githubusercontent.com/45795262/73847340-5af23000-4826-11ea-9e5b-d554ddd8e499.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/73847345-5cbbf380-4826-11ea-89ce-328e4d916268.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
