### ISSUE TITLE
[Event Request] Table 5409 "Prod. Order Routing Line"

### ISSUE THREAD

**Issue by ChMeinert** [microsoft/ALAppExtensions#5942]
Could you please insert the OnValidateRotuingStatus Event at the beginning of the Routing Status - OnValdiate Trigger? It is needed to Skip the Confirmation Dialog.

![image](https://user-images.githubusercontent.com/60700637/73848408-5fb7e380-4828-11ea-989a-27ae6f4e9673.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
