### ISSUE TITLE
[Event Request] Report 99001025 Refresh Production Order

### ISSUE THREAD

**Issue by ChMeinert** [microsoft/ALAppExtensions#5943]
Could you please expand the Publisher "OnBeforeCalcProdOrder" with the new Parameter "Direction".
The Parameter is set by OnInitReport or can be choosen by User on the Request Page.

![image](https://user-images.githubusercontent.com/60700637/73848903-4b281b00-4829-11ea-9cbd-2fc648033d96.png)

![image](https://user-images.githubusercontent.com/60700637/73848811-1c11a980-4829-11ea-8731-e66825e08509.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
