### ISSUE TITLE
[Event Request] Codeunit 99000774 "Calculate Routing Line"

### ISSUE THREAD

**Issue by ChMeinert** [microsoft/ALAppExtensions#5944]
Could you please insert the OnAfterCheckProdOrderStatus Event in the procedure CreateCapNeed?

![image](https://user-images.githubusercontent.com/60700637/73849272-f1742080-4829-11ea-9b90-273a174ebbaf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
