### ISSUE TITLE
[Event Request] Page 99000883 "Sales Order Planning"

### ISSUE THREAD

**Issue by ChMeinert** [microsoft/ALAppExtensions#5945]
Could you please insert the OnAfterCreateProdOrder Event at the ending of the procedure CreateProdOrder?
![image](https://user-images.githubusercontent.com/60700637/73849530-60517980-482a-11ea-9e2d-7febd822153b.png)

...

![image](https://user-images.githubusercontent.com/60700637/73849566-74957680-482a-11ea-9338-d3d24e01e435.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
