### ISSUE TITLE
[Request for external] Codeunit 1652 - multible procedures

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#5946]
We want to publish our own O365 AddIn with our App. To do we this used `codeunit 1652 "Add-in Manifest Management"` in the past. Would it be posible to remove the OnPrem Scope from these Procedures:

- `procedure AddRegExRuleNode(var ManifestText: Text; RegExName: Text; RegExText: Text)`
- `procedure CreateAddin(var OfficeAddin: Record "Office Add-in"; ManifestText: Text; AddinName: Text[50]; AddinDescription: Text[250]; AddinID: Text[50]; ManifestCodeunit: Integer)`
- `procedure SetCommonManifestItems(var ManifestText: Text)`
- `procedure RemoveAddInTriggersFromManifest(var ManifestText: Text)`
- `procedure SetSourceLocationNodes(var ManifestText: Text; URL: Text; FormType: Option ItemRead,ItemEdit)`
- `procedure RemoveAddInTriggersFromManifest(var ManifestText: Text)`

**Comment by AlexanderYakunin** [comment]
After long discussion. I can inform you that this work is planned for next release. We cannot make it for Wave 2 2021.

**Comment by ChrisBlankDe** [comment]
I hope you meant Wave 2 2020 :)
