### ISSUE TITLE
Codeunit 8 - AccSchedManagement

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#5947]
In the procedure CalcGLAcc(...) you have the code:
```
.
.
.
with GLEntry do begin
  SetGLAccGLEntryFilters(GLAcc, GLEntry, AccSchedLine, ColumnLayout, UseBusUnitFilter, UseDimFilter);
  case AmountType of
  AmountType::"Net Amount":
.
.
.
```
I need the same implementation with the Function **SetGLAccGLEntryFilters(...)** also for the procedure CalcCostType(...).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
