### ISSUE TITLE
[Event Request] Codeunit 408 DimensionManagement - UpdateJobTaskDim()

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#5948]
Dear BaseApp team,

Please consider adding "IsHandled" pattern to codeunit 408 DimensionManagement, procedure UpdateJobTaskDim, confirmation dialog Text019 "You have changed a dimension.\\Do you want to update the lines?":
![C408 - UpdateJobTaskDim](https://user-images.githubusercontent.com/42442951/73862351-1f1b9280-4847-11ea-871e-9d889eaeca74.png)
It would be very useful if we could suppress this confirmation and proceed as if user have pressed "yes".

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
