### ISSUE TITLE
[Enums] "Purchase Line"."Document Type " access

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/ALAppExtensions#595]
Hi,

I'm trying to convert some Options types into Enum type.

I don't know how I'm doing this wrong, but when I put an enum type in a table field, I don't have any intellisense proposal out of my enums.
If I put it manualy, I have this AL error
![image](https://user-images.githubusercontent.com/29598240/49861444-22aab980-fdfc-11e8-8f10-02640db20f7f.png)

Is it possible to call a standard enum like "Purchase Line"."Document Type" or do I have to create it ..?

I'm using 2.0.56865 version of AL Language in the W1 13.1 (26323) version of BC

Thanks for any help :)

**Comment by AlexanderYakunin** [comment]
You cannot convert option to enum, we have done it for you
