### ISSUE TITLE
[Event Request] Codeunit 1105 - Transfer GL Entries to CA

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#5953]
We have a lot of Changes in this Codeunit. Can you do something like

```
    trigger OnRun()
    begin
>>new Code
        IsHandled := false;
        OnBeforeRun(IsHandled);
        if IsHandled then
          exit;
<<
        ConfirmTransferGLtoCA;
    end;
```

This would help us very much.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
