### ISSUE TITLE
Missing RunPageView on pages while filtering on Ledger tables

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#5954]
We have found pages 99000778,99000773,99000846 are missing RunPageView while filtering and running ledger entry pages, leading to slow performance (see actions for detail).  Please address it in all supported versions of Dynamics NAV.  Our proposed changes are in the attachment with "//K3 Changes" as referance.

**Comment by Rama-M** [comment]
action("Ledger E&ntries")
                {
                    ApplicationArea = Manufacturing;
                    Caption = 'Ledger E&ntries';
                    Image = CustomerLedger;
                    Promoted = true;
                    PromotedCategory = Category6;
                    RunObject = Page "Capacity Ledger Entries";
			//K3 Changes -
                    RunPageView = SORTING("Order Type", "Order No.", "Order Line No.", "Routing No.", "Routing Reference No.", "Operation No.", "Last Output Line");
			//K3 Changes +
                    RunPageLink = "Order Type" = CONST(Production),
                                  "Order No." = FIELD("Order No.");
                    ShortCutKey = 'Ctrl+F7';
                    ToolTip = 'View the history of transactions that have been posted for the selected record.';
                }

**Comment by AlexanderYakunin** [comment]
Thanks, we will make this change for new version. Doing the same for older version is possible using hotfix request, you can create it here:

•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
