### ISSUE TITLE
Create Inventory Pick/Movement - OnBeforeMakeHeader

### ISSUE THREAD

**Issue by Nameyka-DC** [microsoft/ALAppExtensions#5955]
Hi, can we get the above added to codeunit 7322 "Create Inventory Pick/Movement" allow user to bypass this

```
local procedure MakeHeader()
var
	IsHandled: Boolean;
begin
	OnBeforeMakeHeader(WhseActivHeader, IsHandled, AutoCreation);
	if IsHandled then
		exit;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
