### ISSUE TITLE
[Event Request] Codeunit 424 "Export Analysis View"

### ISSUE THREAD

**Issue by AndreaAntolini** [microsoft/ALAppExtensions#5956]
Requested new IntegrationEvent:

```
[IntegrationEvent] OnBeforeCloseBook(VAR TempExcelBuffer : TEMPORARY Record "Excel Buffer";VAR AnalysisViewEntry : Record "Analysis View Entry")

ExportData()

GLAccountSource := Rec."Account Source" = Rec."Account Source"::"G/L Account";
```

...

```
TempExcelBuffer.SelectOrAddSheet(STRSUBSTNO('%1%2',Text031,Rec."Analysis View Code"));
TempExcelBuffer.WriteAllToCurrentSheet(TempExcelBuffer);

TempExcelBuffer.CloseBook;

IF NOT SkipDownload THEN
  TempExcelBuffer.OpenExcel;

//> New code
OnBeforeCloseBook(TempExcelBuffer,Rec);
//< New code  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
