### ISSUE TITLE
table 480 New event request - BeforeCheckDimensionSet

### ISSUE THREAD

**Issue by MarkusWinBI** [Microsoft/ALAppExtensions#596]
For a customer i need to make a "implicit dimension feature", which simply means: if i assign a Value "A" to Dimension "Dim1", then assign Value "B" to dimension "Dim2" which means I need to change the dimension set before it is processed by external function "GetDimensionSetID" of table 480.

To achieve this, I need a new event, for example called "OnBeforeCheckDimensionSet" which is fired at the first line of the external function "GetDimensionSetID" of table 480 with parameter VAR DimSetEntry : Record "Dimension Set Entry"

[External] [IntegrationEvent] OnBeforeCheckDimensionSet(VAR DimSetEntry : Record "Dimension Set Entry")

Thanks very much and warm greetings from cold Munich
Markus

**Comment by geeknikolai** [comment]
Yes please
