### ISSUE TITLE
[Event Request] Codeunit 5340 "CRM Integration Table Synch."

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#5962]
![image](https://user-images.githubusercontent.com/35260264/74013490-db32a580-498c-11ea-8c75-9dce91ec3fde.png)

![image](https://user-images.githubusercontent.com/35260264/74013458-c6561200-498c-11ea-8e48-e034611bfd67.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by DanielHaglo** [comment]
I cannot see the event in Original-16.0.11240.12474, when is this coming?
