### ISSUE TITLE
[Event Request] codeunit 1223"SEPA CT-Check Line"

### ISSUE THREAD

**Issue by Rick37-tech** [microsoft/ALAppExtensions#5964]
Hi, we need to skip some of the errors in this codeunit.

Modifications

```
 PROCEDURE CheckGenJnlLine(VAR GenJnlLine : Record 81);
 VAR
       GLSetup : Record 98;
       IsHandled: Boolean;
     begin

      //>>New Code
       OnBeforeCheckGenJnlLine(GenJnlLine, IsHandled);
       if not IsHandled then begin
      //<<New Code

          GLSetup.GET;
          WITH GenJnlLine DO BEGIN
             IF "Bal. Account Type" <> "Bal. Account Type"::"Bank Account" THEN
                 InsertPaymentFileError(MustBeBankAccErr);
```
```
       IF "Posting Date" < TODAY THEN
          InsertPaymentFileError(TransferDateErr);
         END;

      //>>New Code
      END;
      OnAfterCheckGenJnlLine(GenJnlLine);
      //<<New Code

    END;
```
```
PROCEDURE CheckCustVend(VAR GenJnlLine : Record 81);
    VAR
      Customer : Record 18;
      CustomerBankAccount : Record 287;
      Vendor : Record 23;
      VendorBankAccount : Record 288;
      IsHandled: Boolean;
    begin

      //>>New Code
      OnBeforeCheckCustVend(GenJnlLine , IsHandled);
      if not IsHandled then begin
      //<<New Code

	      WITH GenJnlLine DO BEGIN
		IF "Account No." = '' THEN BEGIN
		  InsertPaymentFileError(MustBeVendorOrCustomerErr);
		  EXIT;
```
		      IF "Recipient Bank Account" <> '' THEN BEGIN
		        VendorBankAccount.GET(Vendor."No.","Recipient Bank Account");
		        IF VendorBankAccount.IBAN = '' THEN
		          AddFieldEmptyError(
		            GenJnlLine,VendorBankAccount.TABLECAPTION,VendorBankAccount.FIELDCAPTION(IBAN),"Recipient Bank Account");
		      END;
		    END;
		END;
	      END;
      //>>New Code
      END;
      OnAfterCheckCustVend(GenJnlLine);
      //<<New Code
    END;

Events
```

LOCAL [IntegrationEvent] OnBeforeCheckGenJnlLine(VAR GenJnlLine : Record 81;VAR IsHandled : Boolean)

LOCAL [IntegrationEvent] OnBeforeCheckCustVend(VAR GenJnlLine : Record 81;VAR IsHandled : Boolean)

LOCAL [IntegrationEvent] OnAfterCheckGenJnlLine(VAR GenJnlLine : Record 81)

LOCAL [IntegrationEvent] OnAfterCheckCustVend(VAR GenJnlLine : Record 81)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
