### ISSUE TITLE
[Event Request] codeunit 5988 "Serv-Documents Mgt." function: FinalizeDeleteLines

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5966]
Could you please add a publisher in codeunit 5988 "Serv-Documents Mgt." function: FinalizeDeleteLines

```
    local procedure FinalizeDeleteLines()
    begin
        // delete Service Lines persistent and temporary
        PServLine.Reset;
        PServLine.SetRange("Document Type", ServHeader."Document Type");
        PServLine.SetRange("Document No.", ServHeader."No.");
        // New Event
        SetFilterOnFinalizeDeleteLinesBeforeDeletePServLine(PServLine);

        PServLine.DeleteAll;

        ServLine.Reset;
        ServLine.DeleteAll;
    end;
```

```
 [IntegrationEvent(false, false)]
 local procedure SetFilterOnFinalizeDeleteLinesBeforeDeletePServLine(var ServiceLine: record "Service Line");
 begin
 end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Schnieringer** [comment]
Hello,
I didn't get this event with the update to BC16/CU01, the other events in the same business call (set filter) were added... is it possible to get them with BC16 CU02?
