### ISSUE TITLE
[Event Request] C408 DimensionManagement - OnBeforeInsertDimSetEntryFromDimBuffer

### ISSUE THREAD

**Issue by WillemjanBarzilay** [microsoft/ALAppExtensions#5972]
Hi, we need an event in C.408 DimensionManagement in procedure GetDefaultDimID. We need it in the following place:
![image](https://user-images.githubusercontent.com/60778583/74023776-b6e0c400-49a0-11ea-9059-b35445c40458.png)

[IntegrationEvent] OnBeforeInsertDimSetEntryFromDimBuffer(var DimensionSetEntry: Record “Dimension Set Entry“,var DimensionBuffer: Record “Dimension Buffer“)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
