### ISSUE TITLE
[Event Request][New Trigger] report 5753 "Get Source Documents" DataItem: Purchase Header

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5973]
could you please add a publisher  and trigger in in report 5753 "Get Source Documents" for Dataitem: Purchase Header

 ```
// + New Code
 trigger OnAfterGetRecord() // Purchase Header
 var
     BreakReport: Boolean;
     SkipRecord: Boolean;
begin
    BreakReport := false;
    SkipRecord := false;
     // Event
     OnAfterPurchHeaderOnAfterGetRecord("Purchase Header", SkipRecord, BreakReport, "Warehouse Request");
    if BreakReport then
        CurrReport.Break;
    if SkipRecord then
        CurrReport.Skip;
end;
// - New Code
```
```
[IntegrationEvent(false, false)]
local procedure OnAfterPurchHeaderOnAfterGetRecord(PurchaseHeader: Record "Purchase Header"; var SkipRecord: Boolean; var BreakReport: Boolean; var WarehouseRequest: Record "Warehouse Request")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
