### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnBeforeUpdatePostingNos

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#5974]
Please add a new publisher event to the function UpdatePostingNos as follows:
	
```
LOCAL UpdatePostingNos(VAR PurchHeader : Record "Purchase Header") ModifyHeader : Boolean
//>> Start New Publisher Call
OnBeforeUpdatePostingNos(PurchHeader,NoSeriesMgt, ModifyHeader, IsHandled, SuppressCommit);
IF IsHandled THEN
  EXIT;
//<< End New Publisher Call

WITH PurchHeader DO BEGIN
  IF Receive AND ("Receiving No." = '') THEN
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeUpdatePostingNos(VAR PurchHeader : Record "Purchase Header";VAR NoSeriesMgt : Codeunit NoSeriesManagement;VAR ModifyHeader : Boolean;VAR IsHandled : Boolean;SuppressCommit : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
