### ISSUE TITLE
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" - CustPostApplyCustLedgEntry()

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#5975]
Dear BaseApp team,

It would be very useful if we could suppress the "Posting application..." message in CustPostApplyCustLedgEntry procedure :
![CustPostApplyCustLedgEntry01](https://user-images.githubusercontent.com/42442951/74029503-7c355680-49b5-11ea-91f1-e3e6f4047249.png)
![CustPostApplyCustLedgEntry02](https://user-images.githubusercontent.com/42442951/74029508-7dff1a00-49b5-11ea-90c4-3681fe968c65.png)

Please consider to add the "IsHandled" pattern to this dialog.

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
