### ISSUE TITLE
[Event Request] Codeunit 7000 "Sales Price Calc. Mgt." for Function CalcLineAmount

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#5976]
Hello.
In Codeunit 7000, in function CalcLineAmount we are checking for our own field for Table 7002 "Sales Price". (This field will be in a TableExtension in the future.) If our field is filled out, we want to exit from the function with that value, instead of the std. value.

So, we need an event publisher and a handling code for the results in the function:

...
**LOCAL CalcLineAmount**(SalesPrice : Record "Sales Price") : Decimal
WITH SalesPrice DO BEGIN
  **OnBeforeCalcLineAmountReturnUnitPrice(SalesPrice,HandledPrice);**
  **IF HandledPrice <> 0 THEN**
    **EXIT(HandledPrice);**
  IF "Allow Line Disc." THEN...
...
Where the local variable **HandledPrice** is a Decimal.
...
The IntegrationEvent is as follows:
**LOCAL [IntegrationEvent] OnBeforeCalcLineAmountReturnUnitPrice_u**(SalesPrice : Record "Sales Price";VAR HandledPrice : Decimal)
... and the variables are defined as:
SalesPrice **Record** "Sales Price"
**VAR** HandledPrice **Decimal**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
