### ISSUE TITLE
[Event Request] report 5753 "Get Source Documents" DataItem: Purchase Header

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5977]
could you please add a publisher and trigger in in report 5753 "Get Source Documents" for Dataitem: Purchase Header

```
trigger OnPreDataItem() // Purchase Header
begin
    if "Warehouse Request"."Source Type" <> DATABASE::"Purchase Line" then
        CurrReport.Break;
     // New Event
     OnAfterPurchaseHeaderOnPreDataItem("Purchase Header");
     
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterPurchaseHeaderOnPreDataItem(var PurchaseHeader: Record "Purchase Header")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
