### ISSUE TITLE
[Event Request] report 5753 "Get Source Documents" DataItem: Transfer Header

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5978]
could you please add a publisher and trigger in in report 5753 "Get Source Documents" for Dataitem: Transfer Header

```
trigger OnPreDataItem() // Transfer Header
begin
    if "Warehouse Request"."Source Type" <> DATABASE::"Transfer Line" then
        CurrReport.Break;

    // New Event
     OnAfterTransHeaderOnPreDataItem("Transfer Header");
    
end;
```
```
[IntegrationEvent(false, false)]
local procedure OnAfterTransHeaderOnPreDataItem(var TransferHeader: Record "Transfer Header")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
