### ISSUE TITLE
[Event Request] table 246 "Requisition Line"  procedure CopyFromItem

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5979]
could you please add some new parameters on the existing event:
OnBeforeCopyFromItem
new: TempPlanningErrorLog, PlanningResiliency,

```
local procedure CopyFromItem()
begin
    GetItem;
    //  Old Event
    //OnBeforeCopyFromItem(Rec, Item, xRec, CurrFieldNo);
    // New Event
    OnBeforeCopyFromItem(Rec, Item, xRec, TempPlanningErrorLog, PlanningResiliency, CurrFieldNo);
```

```
[IntegrationEvent(false, false)]
Record Item; xRequisitionLine: Record "Requisition Line"; FieldNo: Integer)
local procedure OnBeforeCopyFromItem(var RequisitionLine: Record "Requisition Line"; Item: Record Item; xRequisitionLine: Record "Requisition Line"; var TempPlanningErrorLog: Record "Planning Error Log" temporary; PlanningResiliency: Boolean ;FieldNo: Integer)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
