### ISSUE TITLE
[Event Request]table 336 "Tracking Specification" procedure InitExpirationDate

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5981]
Could you please add a publisher in table 336 "Tracking Specification" procedure InitExpirationDate

```
...
if IsReclass then begin
    "New Expiration Date" := "Expiration Date";
    "Warranty Date" := ItemTrackingMgt.ExistingWarrantyDate("Item No.", "Variant Code", "Lot No.", "Serial No.", EntriesExist);
end;
// New Event
OnAfterInitExpirationDate(Rec);

```

```
[IntegrationEvent(false, false)]
local procedure OnAfterInitExpirationDate(var TrackingSpecification: Record "Tracking Specification")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
