### ISSUE TITLE
[Event Request] table 39 "Purchase Line" trigger OnValidate() "Unit of Measure Code"

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#5983]
could you please change the existing event and insert new parameters:
table 39 "Purchase Line" trigger OnValidate() "Unit of Measure Code"
OnValidateUnitOfMeasureCodeOnBeforeDropShipmentError
new parametes: xRec, CurrFieldNo

```
...
IsHandled := false;
// Old Event
//OnValidateUnitOfMeasureCodeOnBeforeDropShipmentError(Rec, IsHandled);
// New Event
OnValidateUnitOfMeasureCodeOnBeforeDropShipmentError(Rec, xRec, CurrFieldNo, IsHandled);

if not IsHandled then
    if "Drop Shipment" then
        Error(Text001, FieldCaption("Unit of Measure Code"), "Sales Order No.");
...

```
```
[IntegrationEvent(false, false)]
Record "Purchase Line"; var IsHandled: Boolean)
local procedure OnValidateUnitOfMeasureCodeOnBeforeDropShipmentError(PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
