### ISSUE TITLE
[Event Request] Codeunit 99000854 - Inventory Profile Offsetting - OnBeforeInsertInitialSafetyStockWarningSupply

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#5984]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeInsertInitialSafetyStockWarningSupply` to be added to codeunit 99000854 Inventory Profile Offsetting, similar to the event in procedure `InsertEmergencyOrderSupply`.
The signature of this event publisher:
```pascal
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertInitialSafetyStockWarningSupply(var SupplyInventoryProfile: Record "Inventory Profile"; var DemandInventoryProfile: Record "Inventory Profile"; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in a new procedure `InsertInitialSafetyStockWarningSupply` (just like `InsertEmergencyOrderSupply` was turned into its own procedure):
```pascal
local procedure InsertInitialSafetyStockWarningSupply(var SupplyInvtProfile: Record "Inventory Profile"; var DemandInvtProfile: Record "Inventory Profile"; var LastAvailableInventory: Decimal; var LastProjectedInventory: Decimal; PlanningStartDate: Date)
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeInsertInitialSafetyStockWarningSupply(SupplyInvtProfile, DemandInvtProfile, IsHandled);
    if IsHandled then
        exit;

    ...
end;
```

**Comment by RomanZanizdra** [comment]
Hi @rvanbekkum .
Do you mean that code should go in a separate function?
                    if LastAvailableInventory < TempSKU."Safety Stock Quantity" then begin // Initial Safety Stock Warning
                        SupplyAvailableWithinLeadTime := SumUpAvailableSupply(SupplyInvtProfile, PlanningStartDate, PlanningStartDate);
                        InitialProjectedInventory := LastAvailableInventory + SupplyAvailableWithinLeadTime;
                        if InitialProjectedInventory < TempSKU."Safety Stock Quantity" then
                            CreateSupplyForInitialSafetyStockWarning(
                              SupplyInvtProfile,
                              InitialProjectedInventory, LastProjectedInventory, LastAvailableInventory,
                              PlanningStartDate, RespectPlanningParm, IsReorderPointPlanning);
                    end;

**Comment by rvanbekkum** [comment]
Hi @RomanZanizdra,
Yes, similarly to how this was recently done with `InsertEmergencyOrderSupply` (N.B., the code in that procedure was previously in the calling procedure).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
