### ISSUE TITLE
[Event Request] Table 1300/1303 - Mini Customer/Vendor Template - Add OnAfterInsertCustomerFromTemplate/OnAfterInsertVendorFromTemplate again

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#5987]
Dear ALAppExtensions team,
It appears the events that have been requested in #2555 (and implemented) have been removed.
Through this issue we would like to request to have these event publishers added back.

**Comment by AlexanderYakunin** [comment]
Mini templates will be deprecated and replaced by normal Item/Vendor/Customer templates, therefore we will not be adding more events to Mini objects
