### ISSUE TITLE
[Event Change] TAB 383 in Function InsertDtldCVLedgEntry

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#5989]
Hey,
please add CVLedgEntryBuf as Parameter to Event OnBeforeCreateDtldCVLedgEntryBuf.
![grafik](https://user-images.githubusercontent.com/34539583/74042662-42218000-49c8-11ea-87a4-ecbf71903c93.png)
![grafik](https://user-images.githubusercontent.com/34539583/74042772-7006c480-49c8-11ea-8ec7-f871bd323617.png)
Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
