### ISSUE TITLE
[Event Request] report 15000003 "Rem. payment order - import" (Norwegian Localization) - Update

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#5990]
Only one of three events was added from issue #3560.

Not created:
OnBeforeImportReturnFile(ReturnFiles,IsImported)
OnBeforeFindFiles(ReturnFileSetup,IsHandled)

Ref #3560

**Comment by AlexanderYakunin** [comment]
Sorry, you forgot to mention where we need to add event OnBeforeImportReturnFile(ReturnFiles,IsImported)? This is the reason only part of you ask have been implemented. Please create new request with more details, this one will be closed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
