### ISSUE TITLE
[Request for External] codeunit 5510 "Production Journal Mgt" - InsertOutputJnlLine, InsertConsumptionJnlLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#5991]
Can you change InsertOutputJnlLine and InsertConsumptionJnlLine to global and external, in codeunit 5510 "Production Journal Mgt"?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
