### ISSUE TITLE
[Request for External] codeunit 5510 "Production Journal Mgt" - GetTemplateAndBatchName

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#5992]
Can you add a procedure to codeunit 5510 "Production Journal Mgt" so I can get ToTemplateName and ToBatchName after calling procedure SetTemplateAndBatchName?

![image](https://user-images.githubusercontent.com/46031720/74083590-413f2b80-4a66-11ea-923d-e3cf3aa84104.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
