### ISSUE TITLE
[EventRequest] Codeunit 90 “Purch.-Post”, PostItemLine

### ISSUE THREAD

**Issue by AI-91** [microsoft/ALAppExtensions#5993]
Please add a new publisher event OnBeforeInsertDropShptBuffer in Codeunit 90 on function PostItemLine and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/41294390/74134266-868c6600-4bea-11ea-9025-5bc223e7dd7a.png)

Please add the corresponding Integration Event In the bottom of the codeunit
LOCAL [IntegrationEvent] OnBeforeInsertDropShptBuffer(VAR DropShptPostBuffer : Record "Drop Shpt. Post. Buffer";PurchLine : Record "Purchase Line")

**Comment by AlexanderYakunin** [comment]
This event already exist
OnBeforeTempDropShptPostBufferInsert(TempDropShptPostBuffer, PurchLine);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
