### ISSUE TITLE
event request cod365 FormatAddressOnAfterGetCountryRec

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#5994]
can the event FormatAddressOnAfterGetCountryRec be added to codeunit:365:"FormatAddr"?

With this event we can add for example the country.name to the "address array" for countrycode blank. Or the translation for the country.name (as request in #2244)

code::
[Modified.txt](https://github.com/microsoft/ALAppExtensions/files/4179818/Modified.txt)
[Original.txt](https://github.com/microsoft/ALAppExtensions/files/4179819/Original.txt)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
