### ISSUE TITLE
Event requests cod7000+7010

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#5995]
events changes requests:
in codeunit7000:"Sales Price Calc. Mgt.":
1) Extra parameter BestSalesPriceFound as var in publisher OnAfterCalcBestUnitPrice
2) New publisher OnBeforeCalcCalcBestLineDisc
3) New publisher OnAfterCalcCalcBestLineDisc

codeunit7010:"Purch. Price Calc. Mgt.":
4) new publisher OnBeforeCalcBestDirectUnitCost
5) new publisher OnAfterCalcBestDirectUnitCost
6) new publisher OnBeforeCalcCalcBestLineDisc
7) new publisher OnAfterCalcCalcBestLineDisc

code:
[Modified.txt](https://github.com/microsoft/ALAppExtensions/files/4179902/Modified.txt)
[Original.txt](https://github.com/microsoft/ALAppExtensions/files/4179903/Original.txt)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
