### ISSUE TITLE
[EventRequest] Codeunit 90 “Purch.-Post”, PostItemJnlLine

### ISSUE THREAD

**Issue by AI-91** [microsoft/ALAppExtensions#5996]
Please add a new publisher event OnBeforePostItemJnlLineJobConsumption in Codeunit 90 on function PostItemJnlLine and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/41294390/74136845-192f0400-4bef-11ea-9690-93b7b5ee57cb.png)

Please add the corresponding Integration Event In the bottom of the codeunit

LOCAL [IntegrationEvent] CGK_OnBeforePostItemJnlLineJobConsumption(VAR ItemJournalLine : Record "Item Journal Line";VAR PurchaseLine : Record "Purchase Line";PurchInvHeader : Record "Purch. Inv. Header";PurchCrMemoHdr : Record "Purch. Cr. Memo Hdr.";QtyToBeInvoiced : Decimal;QtyToBeInvoicedBase : Decimal;SourceCode : Code[10])

I know it already exists the event OnBeforePostItemJnlLineJobConsumption, but I would need to have it with the PurchaseLine paramenter by VAR; I don't know if it's possible to change the current event and making the parameter by VAR, or actually create a new event as suggested.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
