### ISSUE TITLE
[Event Request] Codeunit 5882 - OnAfterOnRun

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#5997]
Hey guys,

it looks like the event OnAfterOnRun() is not called in the OnRun() Trigger.

Build: 16.0.11037.

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
