### ISSUE TITLE
[EventRequest] Codeunit 1026 “Job Usage Link”, MatchUsageUnspecified

### ISSUE THREAD

**Issue by AI-91** [microsoft/ALAppExtensions#5998]
Please add a new publisher event OnBeforeConfirmMatchUsageUnspecified in Codeunit 1026 on function MatchUsageUnspecified and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/41294390/74139045-facb0780-4bf2-11ea-81a9-87b246654c43.png)

Please add the corresponding Integration Event In the bottom of the codeunit

LOCAL [IntegrationEvent] OnBeforeConfirmMatchUsageUnspecified(VAR JobPlanningLine : Record "Job Planning Line";JobLedgerEntry : Record "Job Ledger Entry";VAR Confirmed : Boolean;VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
