### ISSUE TITLE
[EventRequest] Codeunit 5813 “Undo Purchase Receipt Line”, PostItemJnlLine

### ISSUE THREAD

**Issue by AI-91** [microsoft/ALAppExtensions#5999]
Please add a new publisher event OnBeforePostItemJnlLine in Codeunit 5813 on function PostItemJnlLine and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/41294390/74139531-d91e5000-4bf3-11ea-96b6-43f03054c7d8.png)

Please add the corresponding Integration Event In the bottom of the codeunit

LOCAL [IntegrationEvent] OnBeforePostItemJnlLine(VAR PurchRcptLine : Record "Purch. Rcpt. Line";VAR ItemJnlLine : Record "Item Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
