### ISSUE TITLE
How to extend Default function with type of external from AL ?

### ISSUE THREAD

**Issue by TharunMuthu** [Microsoft/ALAppExtensions#600]
Hi all,

**Is it possible to extend  function from table with type of external from AL ?**
if possible can you please guide me !!

Thanks .
![capture](https://user-images.githubusercontent.com/44170162/49912977-d7111200-fec6-11e8-9088-9c94ece7f6a5.JPG)

**Comment by AskeHolst** [comment]
Add **[Scope('Personalization')]**

Like this:
```
[Scope('Personalization')]
procedure MyExternalProc()
begin
  DoSomething();
end;
```

**Comment by TharunMuthu** [comment]
> Add **[Scope('Personalization')]**
> 
> Like this:
> 
> ```
> [Scope('Personalization')]
> procedure MyExternalProc()
> begin
>   DoSomething();
> end;
> ```

Thanks for your reply .can you please explain bit more since i tried but i am sure something  i am missing . ie i am trying to extend highlighted function(UpdateReferencedIds)  from customer table 
![issue](https://user-images.githubusercontent.com/44170162/50270912-119e2000-046e-11e9-8621-830a13aa6fac.JPG)

**Comment by JesperSchulz** [comment]
The short answer is, that you cannot extend functions. You are probably looking for an event in function UpdateReferenceIds() for you to hook into? In order to assist you, we would need a little more context ;-)

**Comment by TharunMuthu** [comment]
> swer is, that you cannot extend functions. You are

ok .The reason i am asking is , In standard NAV many function don't have Integration event ,  that is reason i asked .! In t this case shall we create our own Integration then shall we subscribe  from AL ?
In other words **how to add  code in Standard NAV functions !**
if yes then please guide me !!

normal event subscription i know .

**Comment by JesperSchulz** [comment]
In this repo you will find many event requests, such as this one https://github.com/Microsoft/ALAppExtensions/issues/583. Please request the events you would like us to add, and we will process them as quickly as possible and release them in the next major and minor version of Business Central.
