### ISSUE TITLE
[EventRequest] Codeunit 5814 “Undo Return Shipment Line”, PostItemJnlLine

### ISSUE THREAD

**Issue by AI-91** [microsoft/ALAppExtensions#6000]
Please add a new publisher event OnBeforePostItemJnlLine in Codeunit 5814 on function PostItemJnlLine and call it as shown in the image below:

![image](https://user-images.githubusercontent.com/41294390/74139869-6366b400-4bf4-11ea-97b8-a23e6939ef36.png)

Please add the corresponding Integration Event In the bottom of the codeunit

LOCAL [IntegrationEvent] OnBeforePostItemJnlLine(VAR ReturnShipmentLine : Record "Return Shipment Line";VAR ItemJnlLine : Record "Item Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
