### ISSUE TITLE
[Event Request] Application “Tests-Rapid Start”, Codeunit 136611 "ERM RS Dimensions as Columns"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6001]
[Event Request] Application “Tests-Rapid Start”, Codeunit 136611 "ERM RS Dimensions as Columns"
![pic1](https://user-images.githubusercontent.com/45795262/74141881-053bd000-4bf8-11ea-93ed-ca66f2b97269.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?
![pic2](https://user-images.githubusercontent.com/45795262/74141886-0836c080-4bf8-11ea-9e65-1aa6bb182b24.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
