### ISSUE TITLE
[Event Request] Application “Tests-Report”, Codeunit 134422 "Rep. Selections - Std. Stmt."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6002]
[Event Request] Application “Tests-Report”, Codeunit 134422 "Rep. Selections - Std. Stmt."
![pic1](https://user-images.githubusercontent.com/45795262/74142520-644e1480-4bf9-11ea-991e-0309a431b6b3.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74142528-67490500-4bf9-11ea-9725-1583113fd6b2.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
