### ISSUE TITLE
[Event Request] Application “Tests-Report”, Codeunit 134761 "Test Custom Reports"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6003]
[Event Request] Application “Tests-Report”, Codeunit 134761 "Test Custom Reports"
![pic1](https://user-images.githubusercontent.com/45795262/74142669-a4ad9280-4bf9-11ea-8cf9-8e1b92ba6b21.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74142670-a70fec80-4bf9-11ea-962d-9e5e1a15cde3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
