### ISSUE TITLE
[Event Request] Application “Tests-Report”, Codeunit 134982 "ERM Financial Reports"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6004]
[Event Request] Application “Tests-Report”, Codeunit 134982 "ERM Financial Reports"
![pic1](https://user-images.githubusercontent.com/45795262/74142784-df172f80-4bf9-11ea-8d79-ea49ff6566cb.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74142791-e1798980-4bf9-11ea-8470-0069c5e93191.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
