### ISSUE TITLE
[Event Request] Application “Tests- Reverse”, Codeunit 134129 "ERM Reverse For Cust/Vendor"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6005]
[Event Request] Application “Tests- Reverse”, Codeunit 134129 "ERM Reverse For Cust/Vendor"
![pic1](https://user-images.githubusercontent.com/45795262/74142924-2ac9d900-4bfa-11ea-929b-807d186c2766.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74142934-2d2c3300-4bfa-11ea-949e-f8066020192a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
