### ISSUE TITLE
[Event Request] Application “Tests- SCM”, Codeunit 133504 "SCM Costing Performance"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6006]
[Event Request] Application “Tests- SCM”, Codeunit 133504 "SCM Costing Performance"
![pic1](https://user-images.githubusercontent.com/45795262/74143070-6795d000-4bfa-11ea-9b0c-cfdded4a4e5d.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74143075-6a90c080-4bfa-11ea-9c77-ab9092d6efe5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
