### ISSUE TITLE
[Event Request] Application “Tests- SCM”, Codeunit 137060 "SCM Inventory 7.0"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6007]
[Event Request] Application “Tests- SCM”, Codeunit 137060 "SCM Inventory 7.0"
![pic1](https://user-images.githubusercontent.com/45795262/74143208-af1c5c00-4bfa-11ea-88e9-adf1eafa8f77.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74143214-b0e61f80-4bfa-11ea-8577-6fda4990f03c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
