### ISSUE TITLE
[Event Request]Application “Tests-SCM”, Codeunit 137054 "SCM Supply Planning"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6008]
[Event Request]Application “Tests-SCM”, Codeunit 137054 "SCM Supply Planning"
![pic1](https://user-images.githubusercontent.com/45795262/74143392-06223100-4bfb-11ea-8538-89c08b58335e.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedures DemandSupplyWithReserveCancelReservationFromSupply and DemandSupplyWithReserveCancelReservationFromDemand?
![pic2](https://user-images.githubusercontent.com/45795262/74143398-09b5b800-4bfb-11ea-9324-0c8a978d8cf5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
