### ISSUE TITLE
[Event Request] Codeunit 7312 - OnBeforePickAccordingToFEFO

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/ALAppExtensions#6009]
```
local procedure PickAccordingToFEFO(LocationCode: Code[10]): Boolean
+ var
+     PickAccordingToFEFO: Boolean;
+     IsHandled: Boolean;
begin
+     IsHandled := false;
+     OnBeforePickAccordingToFEFO(LocationCode, SNRequired, LNRequired, PickAccordingToFEFO, IsHandled);
+     if IsHandled then
+         exit(PickAccordingToFEFO);
    GetLocation(LocationCode);
    exit(Location."Pick According to FEFO" and (SNRequired or LNRequired));
end;
```    

+ [IntegrationEvent(false, false)]
+ local procedure OnBeforePickAccordingToFEFO(LocationCode: Code[20]; SNRequired: Boolean; LNRequired: Boolean; var PickAccordingToFEFO: Boolean; var IsHandled: Boolean)
+ begin
+ end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
