### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. - Update: OnBeforeInsertToSalesLine

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#601]
[Note: I will mention sales only, but everything applies to purchase as well.]

We have developed custom tables with the same primary key as the sales tables (e.g. for Sales Header, Sales Shipment Line etc.) that need to be updated whenever the standard table is updated. Thus, we need to handle the "Copy Document" functionality for these tables ourselves.

In codeunit 6620, with the already published event
`OnCopySalesDocWithHeader(FromDocType,FromDocNo,ToSalesHeader,FromDocOccurrenceNo,FromDocVersionNo);`
we have access to all "from" information and to ToSalesHeader. When subscribing to the above mentioned event, we additionally fetch the source document, next fetch the corresponding records in our custome tables, and are able to transfer the field values.

[ISSUE]
For lines, the current subscribers work ONLY if the source document table is Sales Line or Sales Line Archive itself.

Posted source tables (e.g. Sales Invoice Line) will be passed through a buffer Sales Line record, where finally all PK fields will be empty --> no chance to fetch the source record

[PROPOSAL]
See [below](https://github.com/Microsoft/ALAppExtensions/issues/601#issuecomment-447378154).

**Comment by NKarolak** [comment]
Hold on, it seems like I must have misinterpreted something earlier. If I see it correctly, the PK fields of FromSalesLine should still exist after TRANSFERFIELDS, thus together with the FromSalesDocType, it should be enough to fetch the source record. I'll check.

**Comment by NKarolak** [comment]
Got it, there was an issue with the archived documents only. Thus, the request is the following:

Please update publisher
`OnBeforeInsertToSalesLine(ToSalesLine,FromSalesLine,FromSalesDocType,RecalculateLines,ToSalesHeader);`

to

`OnBeforeInsertToSalesLine(ToSalesLine,FromSalesLine,FromSalesDocType,RecalculateLines,ToSalesHeader,FromDocOccurenceNo,FromDocVersionNo);`

(the added variables are already global, hence no further code changes necessary)

**Comment by NKarolak** [comment]
@AlexanderYakunin  BTW, in codeunit 6620, all existing publisher parameters referring to the "Doc. No. Occurrence" field have a typo as they all contain a single r only.

**Comment by NKarolak** [comment]
I was finally able to modify codeunit 6620 in a way it would suite my needs without understanding how the passing of temporary data, line numbers etc. really works; please check whether there is a better way to solve it. Hence these are my changes, documented only for Sales, but necessary also for Purchase:

**OnBeforeInsertToSalesLine**
Add parameter `FromSalesLineKey : Record Sales Line` as last parameter

**CopySalesLine**
Add parameter `FromSalesLineKey : Record Sales Line` as second last parameter
```
IF CopyThisLine THEN BEGIN
  // >> CHANGE
  // OnBeforeInsertToSalesLine(ToSalesLine,FromSalesLine,FromSalesDocType,RecalculateLines,ToSalesHeader);
  OnBeforeInsertToSalesLine(ToSalesLine,FromSalesLine,FromSalesDocType,RecalculateLines,ToSalesHeader,FromSalesLineKey);
  // << CHANGE
  ToSalesLine.INSERT;
```

**CopySalesDocSalesLine**
```
IF CopySalesLine(
             ToSalesHeader,ToSalesLine,FromSalesHeader,FromSalesLine,
             NextLineNo,LinesNotCopied,FALSE,DeferralTypeForSalesDoc(FromSalesHeader."Document Type"),CopyPostedDeferral,
             FromSalesLine, // NEW
             FromSalesLine."Line No.")
        THEN BEGIN
```

**CopySalesShptLinesToDoc**
```
IF CopySalesLine(
               ToSalesHeader,ToSalesLine,FromSalesHeader,FromSalesLineBuf,NextLineNo,LinesNotCopied,
               FALSE,DeferralTypeForSalesDoc(SalesDocType::"Posted Shipment"),CopyPostedDeferral,
               FromSalesLineBuf, // NEW
               FromSalesLineBuf."Line No.")
          THEN
```

**CopySalesInvLinesToDoc**
```
IF CopySalesLine(ToSalesHeader,ToSalesLine,FromSalesHeader,FromSalesLine2,NextLineNo,LinesNotCopied,
           "Return Receipt No." = '',DeferralTypeForSalesDoc(SalesDocType::"Posted Invoice"),CopyPostedDeferral,
           TempDocSalesLine, // NEW
           GetSalesLineNo(TempDocSalesLine,FromSalesLine2."Line No."))
      THEN BEGIN
```

**CopySalesCrMemoLinesToDoc**
```
IF CopySalesLine(
           ToSalesHeader,ToSalesLine,FromSalesHeader,
           FromSalesLine2,NextLineNo,LinesNotCopied,"Return Receipt No." = '',
           DeferralTypeForSalesDoc(SalesDocType::"Posted Credit Memo"),CopyPostedDeferral,
           TempDocSalesLine, // NEW
           GetSalesLineNo(TempDocSalesLine,FromSalesLine2."Line No."))
      THEN BEGIN
```

**CopySalesReturnRcptLinesToDoc**
```
IF CopySalesLine(
               ToSalesHeader,ToSalesLine,FromSalesHeader,FromSalesLineBuf,NextLineNo,LinesNotCopied,
               FALSE,DeferralTypeForSalesDoc(SalesDocType::"Posted Return Receipt"),CopyPostedDeferral,
               FromSalesLineBuf, // NEW
               FromSalesLineBuf."Line No.")
          THEN
```

**Comment by NKarolak** [comment]
Merry Christmas @AlexanderYakunin, 

I suppose you answered to the original version of my request. Unfortunately my request has changed a lot in the meantime, thus the 4th parameter is not the issue nor the solution. 
Could you please read the current request again? Thank you

**Comment by NKarolak** [comment]
FYI, my suggestion does NOT cover scenarios when you cancel invoices or reverse posted documents, as the new parameter will not contain a valid line number.

You could check it with the following test functions (though many, many more are affected):
134327	CheckUnitCostLCYWithExchangeRate
137158	PostPurchaseReturnOrderWithReverseDocument
138015	TestCancelInvoice
134330    PostPurchaseCrMemoUsingGetPostedDocLines

**Comment by NKarolak** [comment]
@AlexanderYakunin Could you please check this request again? It is open since a long time.

**Comment by AlexanderYakunin** [comment]
From my view this is very specific problem of your solution which can be addressed by moving your extra tables back to original ones. I think you can add more fields in extension to existing base app fields. Anyway, we cannot solve any issues you report, this one is far too complex to be solved by our team as event request. We have another process for large changes, you need to post this on Yammer first and other partners should vote for it. If it get many votes, it will be included into our backlog of DCR's. I cannot prioritize this one over 50+ existing asks with 20+ votes.
