### ISSUE TITLE
[Event Request] Table 36 - OnBeforeGetShippingTime

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#6010]
Please add a new integration event **OnBeforeGetShippingTime** in **Table 36**.

```
    procedure GetShippingTime(CalledByFieldNo: Integer)
    var
        ShippingAgentServices: Record "Shipping Agent Services";
+       IsHandled: Boolean;
    begin
+       IsHandled := false;
+       OnBeforeGetShippingTime(Rec, CalledByFieldNo, IsHandled);
+       if IsHandled then
+           exit;
        [...]
```

New integration event
```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetShippingTime(var Rec: Record "Sales Header"; CalledByFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
