### ISSUE TITLE
[Event Change] Table 5050 - Contact - OnBeforeCreateSalesQuoteFromContact 

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#6011]
Hi AL-Team,

can you please add the variable SalesHeader by var to the following Publisher?

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateSalesQuoteFromContact(var Contact: Record Contact; **var** SalesHeader: Record "Sales Header")
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
