### ISSUE TITLE
[Event Change] Table 252 - General Posting Setup - OnAfterSuggestSalesAccounts 

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#6012]
Hi AL-Team,

can you please add the variable RecRef by var to the following Publisher?

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSuggestSalesAccounts(var GeneralPostingSetup: Record "General Posting Setup"; **var** RecRef: RecordRef);
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
