### ISSUE TITLE
[Event Request] report 15000050 "Remittance - export (bank)" (Norwegian Localization)

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#6013]
Can you add event OnBeforeGenJnlLineOnPreDataItem in report 15000050 "Remittance - export (bank)"?

![image](https://user-images.githubusercontent.com/46031720/74180610-23c5b980-4c40-11ea-8017-018a8ea27a69.png)

![image](https://user-images.githubusercontent.com/46031720/74181038-d269fa00-4c40-11ea-978f-191aaab3530f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
