### ISSUE TITLE
[Event Request] report 15000060 "Remittance - export (BBS)" (Norwegian Localization)

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#6014]
Can you add event OnBeforeGenJnlLineOnPreDataItem in report 15000060 "Remittance - export (BBS)"?

![image](https://user-images.githubusercontent.com/46031720/74180863-861eba00-4c40-11ea-9050-c8b574a25136.png)

![image](https://user-images.githubusercontent.com/46031720/74181023-cd0caf80-4c40-11ea-875b-10d8b5dd0f8d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
