### ISSUE TITLE
Bug in OnValidate trigger of Base Unit of Measure field

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#6016]
Excerpt from the OnValidate trigger of the Base Unit of Measure field in the Item table:

```
"Sales Unit of Measure" := "Base Unit of Measure";
"Purch. Unit of Measure" := "Base Unit of Measure";
if "Base Unit of Measure" <> '' then begin
  // If we can't find a Unit of Measure with a GET,
  // then try with International Standard Code, as some times it's used as Code
  if not UnitOfMeasure.Get("Base Unit of Measure") then begin
      UnitOfMeasure.SetRange("International Standard Code", "Base Unit of Measure");
      if not UnitOfMeasure.FindFirst then
          Error(UnitOfMeasureNotExistErr, "Base Unit of Measure");
      "Base Unit of Measure" := UnitOfMeasure.Code;
  end;
```
If the Base Unit of Measure code is changed because it was found with the International Standard Code, then you must change Sales Unit of Measure and Purch. Unit of Measure as well.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
