### ISSUE TITLE
OIOUBL PageExtension fields not showing on Sales order

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/ALAppExtensions#6017]
We have a customer running SaaS and have installed the OIOUBL extension.
The customer would like to see the OIOUBL-GLN field. This field is added in your PageExtension: PAG42-Ext13654.SalesOrder.al

The field is just not shown, as per attached image.
Does anyone have an idea why?
![image](https://user-images.githubusercontent.com/968411/74225338-cd499100-4cba-11ea-82b0-f222b5faa2ff.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
