### ISSUE TITLE
[Enum Request] TableExtension 1700 "Deferral Template" - Field "Start Date"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#6019]
[Enum Request] TableExtension 1700 "Deferral Template" 

- Field "Start Date"
- Field "Calc. Method" and implemetation of Interface to extend new "Calc. Method" types.

kind regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
