### ISSUE TITLE
[Event Request] Table 37 - "Sales Line" and Table 39 - "Purchase Line" and Table 81 - "Gen. Journal Line"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#6021]
```
    procedure GetDeferralAmount() DeferralAmount: Decimal
    begin
>>new Code
        IsHandled := false;
        OnBeforeGetDeferralAmount(Rec, DeferralAmount, IsHandled);
        if IsHandled then
          exit;
<<
        if "VAT Base Amount" <> 0 then
            DeferralAmount := "VAT Base Amount"
        else
            DeferralAmount := CalcLineAmount;
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
