### ISSUE TITLE
[Event Request] Codeunit 5836 OnAfterCalcShareOfTotalCapCost

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6022]
Please add a new Event trigger OnAfterCalcShareOfTotalCapCost in codeunit 5836:

[External] CalcShareOfTotalCapCost(ProdOrderLine : Record "Prod. Order Line";VAR ShareOfTotalCapCost : Decimal)
WITH ProdOrderLine DO BEGIN
  SETCURRENTKEY(Status,"Prod. Order No.","Routing No.","Routing Reference No.");
  SETRANGE(Status,Status);
  SETRANGE("Prod. Order No.","Prod. Order No.");
  SETRANGE("Routing Reference No.","Routing Reference No.");
  SETRANGE("Routing No.","Routing No.");
  ShareOfTotalCapCost := 0;
  IF Status = Status::Finished THEN BEGIN
    Qty := "Finished Quantity";
    CALCSUMS("Finished Quantity");
    IF "Finished Quantity" <> 0 THEN
      ShareOfTotalCapCost := Qty / "Finished Quantity";
  END ELSE BEGIN
    Qty := Quantity;
    CALCSUMS(Quantity);
    IF Quantity <> 0 THEN
      ShareOfTotalCapCost := Qty / Quantity;
  END;
END;
//++++++++++++++++++++++++++++++++
OnAfterCalcShareOfTotalCapCost(VAR ProdOrderLine : Record "Prod. Order Line";VAR ShareOfTotalCapCost : Decimal);
//--------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
