### ISSUE TITLE
[Event Request] Codeunit 5836 OnBeforeCalcQtyAdjdForBOMScrap and OnBeforeCalcQtyAdjdForRoutingScrap

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6023]
Please add two new Event trigger OnBeforeCalcQtyAdjdForBOMScrap and OnBeforeCalcQtyAdjdForRoutingScrap in codeunit 5836:

[External] CalcQtyAdjdForBOMScrap(Qty : Decimal;ScrapPct : Decimal) QtyAdjdForBomScrap : Decimal
//++++++++++++++++++++++++++++++++++++++++++++
IsHandled := FALSE;
OnBeforeCalcQtyAdjdForBOMScrap(Qty : Decimal;ScrapPct : Decimal;VAR QtyAdjdForBomScrap : Decimal; VAR IsHandled : Boolean);
IF NOT IsHandled THEN
//--------------------------------------------
QtyAdjdForBomScrap := Qty * (1 + ScrapPct / 100);

[External] CalcQtyAdjdForRoutingScrap(Qty : Decimal;ScrapFactorPctAccum : Decimal;FixedScrapQtyAccum : Decimal) QtyAdjdForRoutingScrap : Decimal
//++++++++++++++++++++++++++++++++++++++++++++
IsHandled := FALSE;
OnBeforeCalcQtyAdjdForRoutingScrap(Qty : Decimal;ScrapFactorPctAccum : Decimal;FixedScrapQtyAccum : Decimal;VAR QtyAdjdForRoutingScrap : Decimal; VAR IsHandled : Boolean);
IF NOT IsHandled THEN
//--------------------------------------------
QtyAdjdForRoutingScrap := Qty * (1 + ScrapFactorPctAccum) + FixedScrapQtyAccum;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
