### ISSUE TITLE
[Event Request] Codeunit 6503 OnCollectItemTrkgPerPostedDocLineBeforeInsert

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6024]
Please add a new Event trigger OnCollectItemTrkgPerPostedDocLineBeforeInsert in codeunit 6503:

[External] CollectItemTrkgPerPostedDocLine(VAR TempReservEntry : TEMPORARY Record "Reservation Entry";VAR TempItemLedgEntry : TEMPORARY Record "Item Ledger Entry";FromPurchase : Boolean;DocNo : Code[20];LineNo : Integer)
TempItemLedgEntry.RESET;
TempItemLedgEntry.DELETEALL;

WITH TempReservEntry DO BEGIN
  RESET;
  SETCURRENTKEY("Source ID","Source Ref. No.");
  SETRANGE("Source ID",DocNo);
  SETRANGE("Source Ref. No.",LineNo);
  IF FINDSET THEN
    REPEAT
      ItemLedgEntry.GET("Item Ledger Entry No.");
      TempItemLedgEntry := ItemLedgEntry;
      IF "Reservation Status" = "Reservation Status"::Prospect THEN
        TempItemLedgEntry."Entry No." := -TempItemLedgEntry."Entry No.";
      IF FromPurchase THEN
        TempItemLedgEntry."Remaining Quantity" := "Quantity (Base)"
      ELSE
        TempItemLedgEntry."Shipped Qty. Not Returned" := "Quantity (Base)";
      TempItemLedgEntry."Document No." := "Source ID";
      TempItemLedgEntry."Document Line No." := "Source Ref. No.";
      //++++++++++++++++++++++++++++++++++++++++
      OnCollectItemTrkgPerPostedDocLineBeforeInsert(VAR TempItemLedgEntry : TEMPORARY Record "Item Ledger Entry"; VAR TempReservEntry : TEMPORARY Record "Reservation Entry"; ItemLedgEntry : Record "Item Ledger Entry";FromPurchase : Boolean );
      //----------------------------------------
      TempItemLedgEntry.INSERT;
    UNTIL NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
