### ISSUE TITLE
[Event Request] Codeunit 7301 OnDeleteFromBinContentOnAfterSetFiltersForWhseEntry

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6025]
Please Change the last Parameter in OnDeleteFromBinContentOnAfterSetFiltersForWhseEntry in codeunit 7301 to VAR, because this is the Destination record to be modified:

old:
LOCAL [IntegrationEvent] OnDeleteFromBinContentOnAfterSetFiltersForWhseEntry(VAR WarehouseEntry2 : Record "Warehouse Entry";VAR BinContent : Record "Bin Content";WarehouseEntry : Record "Warehouse Entry")

new:
LOCAL [IntegrationEvent] OnDeleteFromBinContentOnAfterSetFiltersForWhseEntry(VAR WarehouseEntry2 : Record "Warehouse Entry";VAR BinContent : Record "Bin Content"; VAR WarehouseEntry : Record "Warehouse Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
