### ISSUE TITLE
[Event Request] Codeunit 7307 OnInitTempTrackingSpecificationBeforeModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6026]
Please add a new Event trigger OnInitTempTrackingSpecificationBeforeModify in codeunit 7307:

LOCAL InitTempTrackingSpecification(WhseActivLine2 : Record "Warehouse Activity Line";VAR TempTrackingSpecification : TEMPORARY Record "Tracking Specification") QtyToRegisterBase : Decimal
QtyToRegisterBase := WhseActivLine2."Qty. to Handle (Base)";
SetPointerFilter(WhseActivLine2,WhseItemTrkgLine);

WITH WhseItemTrkgLine DO BEGIN
  SETRANGE("Serial No.",WhseActivLine2."Serial No.");
  SETRANGE("Lot No.",WhseActivLine2."Lot No.");
  IF FINDSET THEN
    REPEAT
      IF "Quantity (Base)" > "Qty. Registered (Base)" THEN BEGIN
        IF QtyToRegisterBase > ("Quantity (Base)" - "Qty. Registered (Base)") THEN BEGIN
          QtyToHandleBase := "Quantity (Base)" - "Qty. Registered (Base)";
          QtyToRegisterBase := QtyToRegisterBase - QtyToHandleBase;
          "Qty. Registered (Base)" := "Quantity (Base)";
        END ELSE BEGIN
          "Qty. Registered (Base)" += QtyToRegisterBase;
          QtyToHandleBase := QtyToRegisterBase;
          QtyToRegisterBase := 0;
        END;
        IF NOT UpdateTempTracking(WhseActivLine2,QtyToHandleBase,TempTrackingSpecification) THEN BEGIN
          TempTrackingSpecification.SETCURRENTKEY("Lot No.","Serial No.");
          TempTrackingSpecification.SetTrackingFilter(WhseActivLine2."Serial No.",WhseActivLine2."Lot No.");
          IF TempTrackingSpecification.FINDFIRST THEN BEGIN
            TempTrackingSpecification."Qty. to Handle (Base)" += QtyToHandleBase;
            //++++++++++++++++++++++++++++++++++++
            OnInitTempTrackingSpecificationBeforeModify(VAR WhseItemTrkgLine;VAR TempTrackingSpecification; WhseActivLine2 : Record "Warehouse Activity Line");
            //------------------------------------
            TempTrackingSpecification.MODIFY;
          END;
        END;
        ItemTrackingMgt.SetRegistering(TRUE);
        ItemTrackingMgt.CalcWhseItemTrkgLine(WhseItemTrkgLine);
        MODIFY;
      END;
    UNTIL (NEXT = 0) OR (QtyToRegisterBase = 0);
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
