### ISSUE TITLE
[Event Request] Codeunit 7307 OnGroupWhseActivLinesByWhseDocAndSourceBeforeModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6027]
Please add a new Event trigger OnGroupWhseActivLinesByWhseDocAndSourceBeforeModify in codeunit 7307:

LOCAL GroupWhseActivLinesByWhseDocAndSource(VAR TempWarehouseActivityLine : TEMPORARY Record "Warehouse Activity Line";WarehouseActivityLine : Record "Warehouse Activity Line")
WITH TempWarehouseActivityLine DO BEGIN
  SETRANGE("Whse. Document Type",WarehouseActivityLine."Whse. Document Type");
  SETRANGE("Whse. Document No.",WarehouseActivityLine."Whse. Document No.");
  SETRANGE("Whse. Document Line No.",WarehouseActivityLine."Whse. Document Line No.");
  SETRANGE("Source Document",WarehouseActivityLine."Source Document");
  SetSourceFilter(
    WarehouseActivityLine."Source Type",WarehouseActivityLine."Source Subtype",WarehouseActivityLine."Source No.",
    WarehouseActivityLine."Source Line No.",WarehouseActivityLine."Source Subline No.",FALSE);
  SETRANGE("Action Type",WarehouseActivityLine."Action Type");
  SETRANGE("Original Breakbulk",WarehouseActivityLine."Original Breakbulk");
  SETRANGE("Breakbulk No.",WarehouseActivityLine."Breakbulk No.");
  IF FINDFIRST THEN BEGIN
    "Qty. to Handle" += WarehouseActivityLine."Qty. to Handle";
    "Qty. to Handle (Base)" += WarehouseActivityLine."Qty. to Handle (Base)";
    //+++++++++++++++++++++++++++++++++++++++
    OnGroupWhseActivLinesByWhseDocAndSourceBeforeModify(VAR TempWarehouseActivityLine : TEMPORARY Record "Warehouse Activity Line";WarehouseActivityLine : Record "Warehouse Activity Line");
    //---------------------------------------
    MODIFY;
  END ELSE BEGIN
    TempWarehouseActivityLine := WarehouseActivityLine;
    INSERT;
  END;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
