### ISSUE TITLE
[Event Request] Codeunit 99000830 OnAfterCopyFromInsertReservEntry

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6028]
Please add a new Parameter to OnAfterCopyFromInsertReservEntry. As the existing parameterrecord InsertReservEntry2 does only contain the sourcetype fields, but not the quantity and other content, the record ReservEntry is needed to fill the fields correctly:

old:
LOCAL [IntegrationEvent] OnAfterCopyFromInsertReservEntry(VAR InsertReservEntry : Record "Reservation Entry";VAR ReservEntry : Record "Reservation Entry")

New:
LOCAL [IntegrationEvent] OnAfterCopyFromInsertReservEntry(VAR InsertReservEntry : Record "Reservation Entry";VAR ReservEntry : Record "Reservation Entry"; VAR FromReservEntry : Record "Reservation Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
