### ISSUE TITLE
Event Request Codeunit 99000886 Capable to Promise - CreateReqLine

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6029]
In Function CreateReqLine we need a new Publisher

  IF SalesLine."Drop Shipment" THEN BEGIN
    ReqLine."Sales Order No." := SalesLine."Document No.";
    ReqLine."Sales Order Line No." := SalesLine."Line No.";
    ReqLine."Sell-to Customer No." := SalesLine."Sell-to Customer No.";
    ReqLine."Purchasing Code" := SalesLine."Purchasing Code";
  END;

**// => NEW
OnBeforeModifyReqLine(var ReqLine);
// <== NEW**

ReqLine.MODIFY;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
