### ISSUE TITLE
Event Request Codeunit 99000854 Inventory Profile Offsetting  - InsertTempSKU

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6030]
In function InsertTempSKU we need a new publisher

    IF "Reordering Policy" <> "Reordering Policy"::" " THEN
    **// ==> NEW
    BEGIN
      OnBeforeInsertTempSKU(TempSKU,PlanningGetParameters)
      INSERT;
    END;
    // <== NEW**
  END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
