### ISSUE TITLE
Event Request Codeunit 99000854 Inventory Profile Offsetting - MaintainPlanningLine

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6032]
In function  MaintainPlanningLine we need a publisher befor validation begins
"Variant Code" := SupplyInvtProfile."Variant Code";
....
....
**// ==> NEW
OnBeforeValidateNoinReqLine(ReqLine,SupplyInvtProfile,TempSKU);
// <== NEW**

 VALIDATE("No.");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
