### ISSUE TITLE
Event Request Codeunit 99000854 Inventory Profile Offsetting - AdjustTransferDates

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6033]
In function AdjustTransferDates new publisher

UpdateDatetime;

**// ==> NEW
OnBeforeModifyTransferReqLine(TransferReqLine);
// <==**

MODIFY;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
