### ISSUE TITLE
Event Request Codeunit 99000854 Inventory Profile Offsetting - InsertTempTransferSKU

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6034]
In function InsertTempTransferSKU new publisher to transfer Own fields

ELSE
  TempTransferSKU."Transfer-from Code" := '';

**// ==> NEW
OnBeforeTempTransferSKUInsert(TempTransferSKU,TransLine);
// <== NEW**

IF TempTransferSKU.INSERT THEN;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
