### ISSUE TITLE
Event Request Codeunit 99000854 Inventory Profile Offsetting - GetComponents

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6035]
In function GetComponents new Publisher

**In "Ref. Order Type"::"Prod. Order" AND "Ref. Order Type"::Assembly:**

              PlanComponent.TransferFromComponent(ProdOrderComp);

              **// ==> NEW
              OnBeforeInsertPlanComponent"REFORDERTYPE"(PlanComponent,ReqLine);
              // <== NEW**

              PlanComponent.INSERT;

Also, please expand the case structure with ELSE and also new publisher to handle the other Reference Types of ReqLine

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
