### ISSUE TITLE
[Event Request] Table 336 "Tracking Specification" 

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6036]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "CheckSerialNoQty":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339400-4a046a00-4da4-11ea-8ba5-a99c32467d0a.png)

shall be:
![image](https://user-images.githubusercontent.com/9529836/74339422-54266880-4da4-11ea-9a40-f174101482d7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
