### ISSUE TITLE
[Event Request] Table 6550 "Whse. Item Tracking Line"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6037]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "CheckSerialNoQty":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339481-74eebe00-4da4-11ea-810a-9aa5baff4183.png)

shall be:
![image](https://user-images.githubusercontent.com/9529836/74339495-7c15cc00-4da4-11ea-9a1c-de1bd13fb1b0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
