### ISSUE TITLE
[Event Request] Codeunit 22 "Item Jnl.-Post Line"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6038]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "InsertItemLedgEntry":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339538-918af600-4da4-11ea-8bbe-4a9a8d24f3e5.png)

shall be:
![image](https://user-images.githubusercontent.com/9529836/74339547-98196d80-4da4-11ea-9ca7-53a6f0837ef4.png)

**Comment by AlexanderYakunin** [comment]
We already have this code:
                    IsHandled := false;
                    OnInsertItemLedgEntryOnBeforeSNQtyCheck(ItemJnlLine, IsHandled);
                    if not IsHandled then
                        if not (ItemLedgEntry.Quantity in [-1, 0, 1]) then
                            Error(Text033);
