### ISSUE TITLE
[Event Request] Codeunit 6500 "Item Tracking Management"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6039]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "SplitWhseJnlLine":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339583-ae272e00-4da4-11ea-88e3-7fb3dbcd748d.png)

shall be like:
![image](https://user-images.githubusercontent.com/9529836/74339602-b5e6d280-4da4-11ea-86c1-ae481c98a36d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
