### ISSUE TITLE
[Event Request] Codeunit 7301 "Whse. Jnl.-Register Line"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6040]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "InsertWhseEntry":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339651-ca2acf80-4da4-11ea-9bb4-a25c8c1d415c.png)

shall be like:
![image](https://user-images.githubusercontent.com/9529836/74339662-d151dd80-4da4-11ea-8740-b723054f43a6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
