### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6041]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "CheckSerialNoQty":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339720-ed557f00-4da4-11ea-8c98-6259fc1cd97e.png)

Shall be:
![image](https://user-images.githubusercontent.com/9529836/74339738-f5adba00-4da4-11ea-85c9-dcbc46bc971e.png)

And in function "FindBWPickBin":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339757-00684f00-4da5-11ea-8e41-3deac588a80d.png)

Shall be:
![image](https://user-images.githubusercontent.com/9529836/74339777-0827f380-4da5-11ea-9e13-e9ac98a56511.png)

And in function "ItemTrackedQuantity":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339801-12e28880-4da5-11ea-9c6e-308aaf2d3d84.png)

Shall be like:
![image](https://user-images.githubusercontent.com/9529836/74339821-1b3ac380-4da5-11ea-91df-282251c9257d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
