### ISSUE TITLE
[Event Request] Page 6550 "Whse. Item Tracking Lines"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6042]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "InsertItemTrackingLine".

Currently:
![image](https://user-images.githubusercontent.com/9529836/74339880-39082880-4da5-11ea-8595-b71e30625d60.png)

shall be:
![image](https://user-images.githubusercontent.com/9529836/74339897-3f96a000-4da5-11ea-9595-851e07866455.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
