### ISSUE TITLE
[Event Request] Table 7332 OnOpenItemTrackingLinesOnBeforeSetSource

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6045]
Please Change the Parameter WhseWorksheetLine  to VAR, because it is used in OpenItemTrackingLines and WhseItemTrackingLines.SetSource(WhseWorksheetLine  ,DATABASE::"Whse. Internal Put-away Line");

old:
LOCAL [IntegrationEvent] OnOpenItemTrackingLinesOnBeforeSetSource(VAR WhseInternalPutAwayLine : Record "Whse. Internal Put-away Line";WhseWorksheetLine : Record "Whse. Worksheet Line")

new:
LOCAL [IntegrationEvent] OnOpenItemTrackingLinesOnBeforeSetSource(VAR WhseInternalPutAwayLine : Record "Whse. Internal Put-away Line";VAR WhseWorksheetLine : Record "Whse. Worksheet Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
