### ISSUE TITLE
[Event Request] Codeunit 99000809 - CheckMultiLevelStructure

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6046]
In function CheckMultiLevelStructure we need a publisher before validation of Quantity

    ReqLine3."Demand Date" := PlanningComp."Due Date";
    
    **// ==> NEW
    OnBeforeValidateQuantityForPlanningComponent(ReqLine3,PlanningComp);
    // <== NEW**

    ReqLine3.VALIDATE(Quantity,PlanningComp."Expected Quantity");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
