### ISSUE TITLE
[Event Request] Table 7332 OnSetItemTrackingLinesOnBeforeSetSource

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6047]
Please add a new trigger OnSetItemTrackingLinesOnBeforeSetSource similar to OnOpenItemTrackingLinesOnBeforeSetSource:

[External] SetItemTrackingLines(SerialNo : Code[50];LotNo : Code[50];ExpirationDate : Date;QtyToEmpty : Decimal)
TESTFIELD("Item No.");
TESTFIELD("Qty. (Base)");
TempWhseWorksheetLine.InitLineWithItem(
  TempWhseWorksheetLine."Whse. Document Type"::"Internal Put-away","No.","Line No.",
  "Location Code","Item No.","Variant Code",
  "Qty. (Base)","Qty. (Base)" - "Qty. Put Away (Base)" - "Put-away Qty. (Base)","Qty. per Unit of Measure");

//++++++++++++++++++++++++++++++++++++++++
OnSetItemTrackingLinesOnBeforeSetSource(VAR Rec,VAR TempWhseWorksheetLine);
//----------------------------------------
WhseItemTrackingForm.SetSource(TempWhseWorksheetLine,DATABASE::"Whse. Internal Put-away Line");
WhseItemTrackingForm.InsertItemTrackingLine(TempWhseWorksheetLine,SerialNo,LotNo,ExpirationDate,QtyToEmpty);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
