### ISSUE TITLE
[Event Request] Table 7334 OnOpenItemTrackingLinesOnBeforeSetSource

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6048]
Please add the same trigger OnOpenItemTrackingLinesOnBeforeSetSource from table 7332 also to table 7334:

[External] OpenItemTrackingLines()
TESTFIELD("Item No.");
TESTFIELD("Qty. (Base)");
WhseWorksheetLine.INIT;
WhseWorksheetLine."Whse. Document Type" :=
  WhseWorksheetLine."Whse. Document Type"::"Internal Pick";
WhseWorksheetLine."Whse. Document No." := "No.";
WhseWorksheetLine."Whse. Document Line No." := "Line No.";
WhseWorksheetLine."Location Code" := "Location Code";
WhseWorksheetLine."Item No." := "Item No.";
WhseWorksheetLine."Qty. (Base)" := "Qty. (Base)";
WhseWorksheetLine."Qty. to Handle (Base)" :=
  "Qty. (Base)" - "Qty. Picked (Base)" - "Pick Qty. (Base)";
//++++++++++++++++++++++++++++++++++++++++
OnOpenItemTrackingLinesOnBeforeSetSource(VAR Rec,VAR WhseWorksheetLine);
//----------------------------------------
WhseItemTrackingLines.SetSource(WhseWorksheetLine,DATABASE::"Whse. Internal Pick Line");
WhseItemTrackingLines.RUNMODAL;
CLEAR(WhseItemTrackingLines);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
