### ISSUE TITLE
Date / Century issue : how to overcome the rollover from 2030 to 1931

### ISSUE THREAD

**Issue by DPAMHellemons** [microsoft/ALAppExtensions#6049]
We need to know/ act upon how to overcome the rollover from 2030 to 1931. 
So if we use a date 10 years in the future it should be 2031 as-a-century/year instead of the rollover to 1931.

Is a patch available or a workaround to handle this?
Thanks in advance!
Greetings,
Danny

**Comment by dcenic** [comment]
This behavior is described here: https://docs.microsoft.com/en-us/dynamics-nav/ui-how-enter-date-time.
The cut-off date for entering years with two digits (31/12/2029) is becoming more recent, so we should consider moving the cut-off further in the future.

The workaround: enter the year with four digits.
