### ISSUE TITLE
[Event Request] Table 7347 OnSetItemTrackingLinesOnBeforeSetSource

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6050]
Please add the similar trigger OnSetItemTrackingLinesOnBeforeSetSource to table 7347 as in tables 7332 and 7334:

[External] SetItemTrackingLines(SerialNo : Code[50];LotNo : Code[50];ExpirationDate : Date;QtyToEmpty : Decimal)
TESTFIELD("Item No.");
TESTFIELD("Qty. (Base)");
WhseWorksheetLine.InitLineWithItem(
  WhseWorksheetLine."Whse. Document Type"::"Internal Movement","No.","Line No.",
  "Location Code","Item No.","Variant Code",
  "Qty. (Base)","Qty. (Base)","Qty. per Unit of Measure");
//++++++++++++++++++++++++++++++++++++++++
OnSetItemTrackingLinesOnBeforeSetSource(VAR Rec,VAR WhseWorksheetLine);
//----------------------------------------
WhseItemTrackingLinesForm.SetSource(WhseWorksheetLine,DATABASE::"Internal Movement Line");
WhseItemTrackingLinesForm.InsertItemTrackingLine(WhseWorksheetLine,SerialNo,LotNo,ExpirationDate,QtyToEmpty);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
