### ISSUE TITLE
[Event Request] Codeunit 23 Item Jnl.-Post Batch - HandleRecurringLine

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6051]
In function HandleRecurringLine
Please Redesign the Publisher  OnHandleRecurringLineOnBeforeModify and set this publisher outside of If ... Then Begin
**Or**
Insert a new one...

     OnHandleRecurringLineOnBeforeModify(ItemJnlLine2);
  END;

  **// ==> NEW
  OnBeforeModifyItemJnlLine2(ItemJnlLine2);
  // <== NEW**

  ItemJnlLine2.MODIFY;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
