### ISSUE TITLE
[Event Request] Codeunit 23 Item Jnl.-Post Batch - HandleNonRecurringLine

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6052]
In function HandleNonRecurringLine insert new Publisher
    
  ItemJnlLine3."Line No." := 10000;

    **// ==> NEW
    OnBeforeInsertItemJnlLine3(ItemJnlLine3);
    // <== NEW**

    ItemJnlLine3.INSERT;
    ItemJnlLine3.SetUpNewLine(ItemJnlLine2);

    **// ==> NEW
    OnBeforeModifyItemJnlLine3(ItemJnlLine3);
    // <== NEW**

    ItemJnlLine3.MODIFY;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
