### ISSUE TITLE
[Event Request] Codeunit 23 Item Jnl.-Post Batch - InsertTempSKU

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6053]
In function InsertTempSKU

  "Variant Code" := ItemJnlLine."Variant Code";

  **// ==> NEW
  OnBeforeInsertTempSKU(TempSKU,ItemJnlLine);
  // <== NEW**

  INSERT;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
