### ISSUE TITLE
[Event Request] Codeunit 5801 Show Applied Entries - InsertTempEntry

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6054]
In function InsertTempEntry

  TempItemEntry.Quantity := AppliedQty;

  **// ==> NEW
  OnBeforeInsertTempItemEntry(TempItemEntry,ItemLedgEntry);
  // <== NEW**

  TempItemEntry.INSERT;
END ELSE BEGIN
  TempItemEntry.Quantity := TempItemEntry.Quantity + AppliedQty;

  **// ==> NEW
  OnBeforeModifyTempItemEntry(TempItemEntry,ItemLedgEntry);
  // <== NEW**

  TempItemEntry.MODIFY;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
