### ISSUE TITLE
OnBeforeTestStatusOpen event in PurchaseLine table issue

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#6055]
In Purchase Line table, PurchHeader parameter in OnBeforeTestStatusOpen event is declared NOT "By Var":
![PurchaseLine](https://user-images.githubusercontent.com/45788765/74362059-a8dfd880-4dd0-11ea-9062-aeae6468cb23.jpg)
It Sales Line table, SalesHeader is declared "by var":
![SalesLine](https://user-images.githubusercontent.com/45788765/74362165-dfb5ee80-4dd0-11ea-90ab-232fa6f4c9a3.jpg)

Same story with "OnAfterTestStatusOpen" event.

I've already seen issue #4312 and totally agree with it, and I just want to say that it would be super if it will be applied both in "Sales Line", and "Purchase line" tables.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
