### ISSUE TITLE
[Event Request] Codeunit Gen. Jnl - Post Line, OnBeforeTempOldCustLedgEntryDelete

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [microsoft/ALAppExtensions#6056]
We are currently implementing a customer on BC14 (they want to use the windows client) 
 
They have a requirement to record shortpays (when the customer payment is less than invoice amount less any deductions/discounts). Earlier this has been done in codeunit 12, ApplyCustLedgEntry function, in a loop applying new payments.
 
There are currently several events in this function already. But not in the loop applying entries with the needed variables in this function.
 
In their 2009 code, they have the following function call:
CheckShortpay.Checkshortpay(TempOldCustLedgEntry, NewCVLedgEntryBuf."Document type", NewCVLedgEntryBuf."Document No.", 0, ApplyingDate,NewCVLedgEntryBuf."Entry No.");
 
this call comes just before the following in the standard code:
TempOldCustLedgEntry.DELETE;
 
The called function updates the shortpay records that our client has created and maintains. As you can see the call is accessing fields from TempOldCustLedgEntry, NewCVLedgEntryBuf as well as the General Journal.
 
Is it possible for you to add an event here OnBeforeTempOldCustLedgEntryDelete(TempOldCustLedgEntry, NewCVLedgEntryBuf,  General Journal) ?
 
Or what is the recommended solution?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
