### ISSUE TITLE
[Event Request] Codeunit 13 Gen. Jnl.-Post Batch - ProcessICLines

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6057]
In function ProcessICLines

        THEN BEGIN
          HandledICInboxTrans.LOCKTABLE;
          HandledICInboxTrans.Status := HandledICInboxTrans.Status::Posted;
          **// ==> NEW
          OnBeforeModifyHandledICInboxTrans(HandledICInboxTrans,GenJnlLine);
          // <== NEW**
          HandledICInboxTrans.MODIFY;
        END

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
