### ISSUE TITLE
[Enum Request] Table 99000880 "Order Promising Line"

### ISSUE THREAD

**Issue by SSZurmussen7112** [microsoft/ALAppExtensions#6058]
Hi Team,
In table 99000880 "Order Promising Line" the field 20 "Source Type" is still an Option field. To be able to include own tables to the order promising functionality it is needed to change it to an Enum.

Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
