### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post PostItemTrackingLine (and Codeunit 80)

### ISSUE THREAD

**Issue by sgregorio-adv** [microsoft/ALAppExtensions#6059]
Hi, it would be nice to have an event to prevent PostItemTrackingLine in Codeunit 90 "Purch.-Post" from happen.  There is an exception for this function, which is:

```
IF PurchLine."Prepayment Line" THEN
  EXIT;
```

I would like to have an event _OnBeforeItemTrackingLine(PurchLine, skip)_ before this if and modify the if.  Something like:

```
OnBeforeItemTrackingLine(PurchLine, Skip)
IF PurchLine."Prepayment Line" OR Skip THEN
  EXIT;
```

In Codeunit 80 Sales-Post the same modification is necessary.

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
