### ISSUE TITLE
[Event Request] Codeunit 99000854 "Inventory Profile Offsetting"  – OnBeforeUnfoldItemTracking

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6061]
[Event Request] Codeunit 99000854 "Inventory Profile Offsetting"  – OnBeforeUnfoldItemTracking

Could we please have a Supplement (var TempItemTrkgEntry) in publisher OnBeforeUnfoldItemTracking in Codeunit 99000854 "Inventory Profile Offsetting" ? 

```
    // >>>>>>>>
    [IntegrationEvent(true, false)]
    local procedure OnBeforeUnfoldItemTracking(var Item: Record Item; ToDate: Date; var InventoryProfile: Record "Inventory Profile" temporary; var TempItemTrkgEntry: Record "Reservation Entry"; var LineNo: Integer);
    begin
    end;    // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
