### ISSUE TITLE
[Event Request] Page402 “Sales Order Statistics”  – CheckAllowInvDisc

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6062]
[Event Request] Page402 “Sales Order Statistics”  – CheckAllowInvDisc

Could we please have a in publisher OnCheckAllowInvDisc in function CheckAllowInvDisc Page402 “Sales Order Statistics”? 

```
    local procedure CheckAllowInvDisc()
    begin
        if not AllowInvDisc then
            Error(Text005, "Invoice Disc. Code");

        // >>>>>>>>
        OnCheckAllowInvDisc(Rec);
        // <<<<<<<<  
    end;
..
   // >>>>>>>>
 [IntegrationEvent(false, false)]
 local procedure OnCheckAllowInvDisc(SalesHeader: Record "Sales Header");
 begin
 end;
   // <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
