### ISSUE TITLE
[Event Request] Page7504 "Item Attribute Value List" – "Attribute Name" Onvalidate

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6063]
[Event Request] Page7504 "Item Attribute Value List" – "Attribute Name" Onvalidate

Could we please have a in publisher OnBeforeValidateAttributeName in Onvalidate "Attribute Name" Page7504 "Item Attribute Value List"? 

```
                    trigger OnValidate()
                    var
                        ItemAttributeValue: Record "Item Attribute Value";
                        ItemAttributeValueMapping: Record "Item Attribute Value Mapping";
                    begin

                        // >>>>>>>>
                        OnBeforeValidateAttributeName(Rec, RelatedRecordCode);
                        // <<<<<<<<  

                        if xRec."Attribute Name" <> '' then

..
   // >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateAttributeName(var ItemAttributeValueSelection: Record "Item Attribute Value Selection"; RelatedRecordCode: Code[20])
    begin
    end;
 // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
