### ISSUE TITLE
[Event Request] Page7504 "Item Attribute Value List" – LoadAttributes

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6064]
[Event Request] Page7504 "Item Attribute Value List" – LoadAttributes

Could we please have a in publisher OnLoadAttributesOnBeforeTempItemAttributeValue in function LoadAttributes Page7504 "Item Attribute Value List"? 

```
            if ItemAttributeValueMapping.FindSet then
            repeat
                ItemAttributeValue.Get(ItemAttributeValueMapping."Item Attribute ID", ItemAttributeValueMapping."Item Attribute Value ID");
                TempItemAttributeValue.TransferFields(ItemAttributeValue);

                //>>>>>>>>                
     OnLoadAttributesOnBeforeTempItemAttributeValue( TempItemAttributeValue, ItemAttributeValueMapping, RelatedRecordCode);
                // <<<<<<<<  

                TempItemAttributeValue.Insert;
            until ItemAttributeValueMapping.Next = 0;


..
   // >>>>>>>>
      [IntegrationEvent(false, false)]
    local procedure OnLoadAttributesOnBeforeTempItemAttributeValue(var TempItemAttributeValue: Record "Item Attribute Value" temporary; ItemAttributeValueMapping: Record "Item Attribute Value Mapping"; RelatedRecordCode: Code[20])
    begin
    end;

 // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
