### ISSUE TITLE
[Event Request] Report 5185 "Log Segment" – "Segment Header" OnAfterGetRecord

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6065]
[Event Request] Report 5185 "Log Segment" – "Segment Header" OnAfterGetRecord

Could we please have a in publisher OnBeforeLogSegment in Trigger OnAfterGetRecord "Segment Header" Report 5185 "Log Segment"? 

```
            trigger OnAfterGetRecord()
            begin

                // >>>>>>>>
                OnBeforeLogSegment("Segment Header");
                // <<<<<<<<  

                SegManagement.LogSegment("Segment Header", Send, FollowUp);
            end;
..
// >>>>>>>>
[IntegrationEvent(false, false)]
local procedure OnBeforeLogSegment(var SegmentHeader: Record "Segment Header")
begin
end;
// <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
