### ISSUE TITLE
[Event Request] Report 5198 " Add Contacts" – OnPostReport

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6066]
[Event Request] Report 5198 " Add Contacts" – OnPostReport

Could we please have a in publisher OnPostReportOnBeforeUpdateSegLines in Trigger OnPostReport
Report 5198 " Add Contacts"? 

```
    trigger OnPostReport()
    begin
        if ExpandCompanies then
            AddPeople;
        if AllowCoRepdByContPerson then
            AddCompanies;

        UpdateSegLines;
        
        // >>>>>>>>
        OnPostReportOnBeforeUpdateSegLines("Segment Header");
        // <<<<<<<<  
    end;
..
// >>>>>>>>
[IntegrationEvent(false, false)]
local procedure OnPostReportOnBeforeUpdateSegLines(var SegmentHeader: Record "Segment Header")
begin
end;
// <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
