### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" – UpdatePurchAmountLines

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6069]
[Event Request] Table 38 "Purchase Header" – UpdatePurchAmountLines

Could we please have a publisher OnVATBaseDiscountPercentOnBeforeUpdateAmounts in function UpdatePurchAmountLines Table 38 "Purchase Header"? 

```
          PurchLine.LockTable;
        if PurchLine.FindSet then begin
            Modify;
            repeat
            // >>>>>>>>                    
                OnVATBaseDiscountPercentOnBeforeUpdateAmounts(PurchHeader,PurchLine,CurrFieldNo);
                // <<<<<<<<    
                PurchLine.UpdateAmounts;
                PurchLine.Modify;
            until PurchLine.Next = 0;
        end;

..

    // >>>>>>>>                    
    [IntegrationEvent(false, false)]
    local procedure OnVATBaseDiscountPercentOnBeforeUpdateAmounts(PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; CallingFieldNo: Integer)
    begin
    end;
   // <<<<<<<<  

```

**Comment by RomanZanizdra** [comment]
There is existing event with all required parameters OnBeforeUpdatePurchLineAmounts(Rec, xRec, CurrFieldNo, IsHandled); in this function.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
