### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" – "Blanket Order No." OnValidate

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6070]
[Event Request] Table 39 "Purchase Line" – "Blanket Order No." OnValidate

Could we please have a publisher OnValidateBlanketOrderNoOnAfterTestfieldQuantityReceived with Handled Pattern in OnValidate "Blanket Order No."  Table 39 "Purchase Line"? 

```
          trigger OnValidate()
            // >>>>>>>>
            var
                IsHandled: Boolean;
            // <<<<<<<<  
            begin
                TestField("Quantity Received", 0);

                // >>>>>>>>
                IsHandled := false;
                OnValidateBlanketOrderNoOnAfterTestfieldQuantityReceived(Rec, xRec, IsHandled);
                if IsHandled then
                    exit;
                // <<<<<<<<  

                if "Blanket Order No." = '' then
                    "Blanket Order Line No." := 0
                else
                    Validate("Blanket Order Line No.");
            end;


..
   // >>>>>>>>                    
   [IntegrationEvent(false, false)]
    local procedure OnValidateBlanketOrderNoOnAfterTestfieldQuantityReceived(var PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase line"; var IsHandled: Boolean)
    begin
    end;
   // <<<<<<<<  

```

**Comment by RomanZanizdra** [comment]
Hi @ttaeufer . Short question, why can't you use standard OnBefore/OnAfter validate trigger subscribers?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
