### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" – InitHeaderDefaults

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6071]
[Event Request] Table 39 "Purchase Line" – InitHeaderDefaults

Could we please have a publisher OnInitHeaderDefaultsOnBeforeTestfieldBuyfromVendorNo with Handled Pattern in function InitHeaderDefaults Table 39 "Purchase Line"? 

```
  local procedure InitHeaderDefaults(PurchHeader: Record "Purchase Header")
    
    // >>>>>>>>                    
    var 
        IsHandled: Boolean;
    // <<<<<<<<      
    begin
        
        // >>>>>>>>                            
        IsHandled := false;
        OnInitHeaderDefaultsOnBeforeTestfieldBuyfromVendorNo(Rec,PurchHeader,IsHandled);
        if not IsHandled then
        // <<<<<<<<  
        PurchHeader.TestField("Buy-from Vendor No.");

        "Buy-from Vendor No." := PurchHeader."Buy-from Vendor No.";

..

    // >>>>>>>>                    
    [IntegrationEvent(false, false)]
    local procedure OnInitHeaderDefaultsOnBeforeTestfieldBuyfromVendorNo(var PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header"; var  IsHandled: Boolean)
    begin
    end;
   // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
