### ISSUE TITLE
[Event Request] Table 77 "Report Selections" – SaveReportAsPDF

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6074]
[Event Request] Table 77 "Report Selections" – SaveReportAsPDF

Could we please have a in publisher OnAfterSaveReportAsPDF in function SaveReportAsPDF Table 77 "Report Selections"?

```
 local procedure SaveReportAsPDF(ReportID: Integer; RecordVariant: Variant; LayoutCode: Code[20]) FilePath: Text[250]
    var
        ReportLayoutSelection: Record "Report Layout Selection";
        FileMgt: Codeunit "File Management";
        IsHandled: Boolean;
    begin
        OnBeforeSetReportLayout(RecordVariant);
        FilePath := CopyStr(FileMgt.ServerTempFileName('pdf'), 1, 250);

        ReportLayoutSelection.SetTempLayoutSelected(LayoutCode);
        
        OnBeforeSaveReportAsPDF(ReportID, RecordVariant, LayoutCode, IsHandled, FilePath);
        if not IsHandled then
            REPORT.SaveAsPdf(ReportID, FilePath, RecordVariant);

        // >>>>>>>>
        OnAfterSaveReportAsPDF(ReportID, RecordVariant, LayoutCode, FilePath);
        // <<<<<<<<  

        ReportLayoutSelection.SetTempLayoutSelected('');

        Commit;
    end;


..
    // >>>>>>>>
 [IntegrationEvent(false, false)]
 local procedure OnAfterSaveReportAsPDF(ReportID: Integer; RecordVariant: Variant; LayoutCode: Code[20]; FilePath: Text[250])
 begin
 end;
  // <<<<<<<<  

```

**Comment by AlexanderYakunin** [comment]
Please use existing event instead
OnBeforeSaveReportAsPDF(ReportID, RecordVariant, LayoutCode, IsHandled, FilePath);

**Comment by ttaeufer** [comment]
We cannot execute the SaveAsPDF command (Method "SaveasPDF Can not used for Cloud Development, AL0296).

Therefore we cannot set the Handled and have to use your command SaveasPDF. 
But we have to reset parameters afterwards.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
