### ISSUE TITLE
[Event Request] Table 77 "Report Selections" – SaveReportAsPDF

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6075]
[Event Request] Table 77 "Report Selections" – SaveReportAsPDF

Could we please have a supplement (FilePath) in publisher OnBeforeSaveReportAsPDF in function SaveReportAsPDF Table 77 "Report Selections"?

```
    // >>>>>>>>
 [IntegrationEvent(false, false)]
 local procedure OnBeforeSaveReportAsPDF(ReportID: Integer; RecordVariant: Variant; LayoutCode: Code[20]; var IsHandled: Boolean; FilePath: Text[250])
 begin
 end;
  // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
