### ISSUE TITLE
[Event Request] Table 7501 "Item Attribute Value" – LoadItemAttributesFactBoxData

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6078]
[Event Request] Table 7501 "Item Attribute Value" – LoadItemAttributesFactBoxData

Could we please have a var at second Paraemeter in publisher OnLoadItemAttributesFactBoxDataOnBeforeInsert in function LoadItemAttributesFactBoxData
Table 7501 "Item Attribute Value"?

```
    // >>>>>>>>
 [IntegrationEvent(false, false)]
local procedure OnLoadItemAttributesFactBoxDataOnBeforeInsert(var ItemAttributeValueMapping: Record "Item Attribute Value Mapping"; var ItemAttributeValue: Record "Item Attribute Value")
 begin
 end;
// <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
