### ISSUE TITLE
OnPopulateApprovalEntryArgument 

### ISSUE THREAD

**Issue by dicksonkimeu** [Microsoft/ALAppExtensions#608]
Any code samples for OnPopulateApprovalEntryArgument ?

Am doing customer approvals, and i need to add a new document type in approvals table, and also i want to insert document no for my custom table. advice please.

Below code is not now working.

[EventSubscriber(ObjectType::Codeunit, Codeunit::"Approvals Mgmt.",
'OnPopulateApprovalEntryArgument', '', false, false)]
procedure PopulateApprovalEntryArgument(
RecRef: RecordRef;
ApprovalEntryArgument: Record "Approval Entry")
var
StoreReq: Record "Store Requisition";
begin
CASE RecRef.Number of
DATABASE::"Store Requisition":
begin
RecRef.SetTable(StoreReq);
ApprovalEntryArgument."Document Type" := StoreReq."Document Type";
ApprovalEntryArgument."Document No." := StoreReq."Requisition No.";
ApprovalEntryArgument.Amount := StoreReq."Expected Total Cost";
ApprovalEntryArgument."Currency Code" := StoreReq."Currency Code";
end
END
end;

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
