### ISSUE TITLE
[Function Request] Page7504 "Item Attribute Value List" 

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6083]
[Function Request] Page7504 "Item Attribute Value List" 

Could we please have a new Function GetRelatedRecordCode at Page7504 "Item Attribute Value List" to get value of global Variable RelatedRecordCode? 

```
   // >>>>>>>>
 procedure GetRelatedRecordCode(): Code[20];
 begin
   Exit(RelatedRecordCode);
 end;
 // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
