### ISSUE TITLE
[Function Request] Page 9652 "Report Layout Selection"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6084]
[Function Request] Page 9652 "Report Layout Selection"

Could we please have a new Function GetSelectedCompanyName at Page 9652 "Report Layout Selection" to get value of global Variable SelectedCompany? 

```
   // >>>>>>>>
 procedure GetSelectedCompanyName(): Text[30]
 begin
   Exit(SelectedCompany);
 end;
 // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
