### ISSUE TITLE
[Function Global] Codeunit 5580 "Phys. Invt. Order-Finish" – CreateReservEntries

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6085]
[Function Global] Codeunit 5580 "Phys. Invt. Order-Finish" – CreateReservEntries

Can you please set the function CreateReservEntries to Global Codeunit 5580 "Phys. Invt. Order-Finish"? 

```
//>>>>>>>>    
procedure CreateReservEntries(DocNo: Code[20]; LineNo: Integer; AllBufferLines: Boolean; MaxQtyToTransfer: Decimal)
// <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
