### ISSUE TITLE
[Event Request] Codeunit 221 “Resource-Find Price”  – FindResPrice

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6086]
[Event Request] Codeunit 221 “Resource-Find Price”  – FindResPrice

Could we please have a supplement (var ResourcePrice2) in publisher OnBeforeFindResPrice in function FindResPrice Codeunit 221 “Resource-Find Price” (because ResourcePrice2  is copied to ResourcePrice at OnRun)? 

```
    // >>>>>>>>
  [IntegrationEvent(false, false)]
  local procedure OnBeforeFindResPrice(var ResourcePrice: Record "Resource Price"; var ResourcePrice2: Record "Resource Price";var IsHandled: Boolean; var Result: Boolean)
  begin
  end;
    // <<<<<<<<  

```

**Comment by StanPesotskiy** [comment]
Already done in the scope of the request [5828](https://github.com/microsoft/ALAppExtensions/issues/5828)
