### ISSUE TITLE
[Event Request] Codeunit 7380 "Phys. Invt. Count.-Management"  – OnBeforeCalcInvtQtyOnHand

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6090]
[Event Request] Codeunit 7380 "Phys. Invt. Count.-Management"  – OnBeforeCalcInvtQtyOnHand

Could we please have a Supplement (var ItemJournalLine) in publisher OnBeforeCalcInvtQtyOnHand in Codeunit 7380 "Phys. Invt. Count.-Management"? 

```
    // >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcInvtQtyOnHand(DocNo: Code[20]; PostingDate: Date; ZeroQty: Boolean; var TempPhysInvtItemSelection: Record "Phys. Invt. Item Selection" temporary; var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;
    // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
