### ISSUE TITLE
[Function Request] Page 5734 "Item Category Attributes"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6091]
[Function Request] Page 5734 "Item Category Attributes"

Could we please have a new Function GetTempRecentlyItemAttributeValueMapping at Page 5734 "Item Category Attributes" to get value of global Variable ItemCategoryCode? 

```
   // >>>>>>>>
 procedure GetTempRecentlyItemAttributeValueMapping(var SaveTempRecentlyItemAttributeValueMapping: Record "Item Attribute Value Mapping" temporary)
 begin
     SaveTempRecentlyItemAttributeValueMapping.Reset;
     SaveTempRecentlyItemAttributeValueMapping.Copy(TempRecentlyItemAttributeValueMapping, true);
 end;
 // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
