### ISSUE TITLE
[Event Requests] Table 18 Customer : Affect Total Outstanding Amount.

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#6098]
Hello.

In Table 18 we need to affect the Total Amount LCY calculated in function GetTotalAmountLCYCommon. (Add our number to the otherwise calculated total.)
To do that we need the following 3 publishers (and one decimal variable addition to the total):

1:
In Function **GetTotalAmountLCY** we need:
    [External]
    PROCEDURE GetTotalAmountLCY@10() : Decimal;
    BEGIN
      CALCFIELDS("Balance (LCY)","Outstanding Orders (LCY)","Shipped Not Invoiced (LCY)","Outstanding Invoices (LCY)",
        "Outstanding Serv. Orders (LCY)","Serv Shipped Not Invoiced(LCY)","Outstanding Serv.Invoices(LCY)");
      **OnBeforeExitGetTotalAmountLCY(Rec); // New publisher**
      EXIT(GetTotalAmountLCYCommon);
    END;

2:
In Function **GetTotalAmountLCYUI** we need:
    [External]
    PROCEDURE GetTotalAmountLCYUI@16() : Decimal;
    BEGIN
      SETAUTOCALCFIELDS("Balance (LCY)","Outstanding Orders (LCY)","Shipped Not Invoiced (LCY)","Outstanding Invoices (LCY)",
        "Outstanding Serv. Orders (LCY)","Serv Shipped Not Invoiced(LCY)","Outstanding Serv.Invoices(LCY)");
      **OnBeforeExitGetTotalAmountLCYUI_u(Rec); // New publisher**
      EXIT(GetTotalAmountLCYCommon);
    END;

3:
In Function **GetTotalAmountLCYCommon** we need:
    LOCAL PROCEDURE GetTotalAmountLCYCommon@17() : Decimal;
    VAR
      SalesLine@1000 : Record 37;
      ServiceLine@1002 : Record 5902;
      SalesOutstandingAmountFromShipment@1001 : Decimal;
      ServOutstandingAmountFromShipment@1003 : Decimal;
      InvoicedPrepmtAmountLCY@1004 : Decimal;
      RetRcdNotInvAmountLCY@1006 : Decimal;
      **AdditionalAmount_lf@10004500 : Decimal;**  // New variable to fill in event and add to total.
    BEGIN
      SalesOutstandingAmountFromShipment := SalesLine.OutstandingInvoiceAmountFromShipment("No.");
      ServOutstandingAmountFromShipment := ServiceLine.OutstandingInvoiceAmountFromShipment("No.");
      InvoicedPrepmtAmountLCY := GetInvoicedPrepmtAmountLCY;
      RetRcdNotInvAmountLCY := GetReturnRcdNotInvAmountLCY;
      **OnBeforeExitGetTotalAmountLCYCommon_u(Rec,AdditionalAmount_lf); // New publisher**
      EXIT("Balance (LCY)" + "Outstanding Orders (LCY)" + "Shipped Not Invoiced (LCY)" + "Outstanding Invoices (LCY)" +
        "Outstanding Serv. Orders (LCY)" + "Serv Shipped Not Invoiced(LCY)" + "Outstanding Serv.Invoices(LCY)" -
        SalesOutstandingAmountFromShipment - ServOutstandingAmountFromShipment - InvoicedPrepmtAmountLCY - RetRcdNotInvAmountLCY **+** // change here too
        **AdditionalAmount_lf); // Add the event value to the total to be returned**
    END;

--- The 3 publishers in Table 18 are defined so:

    [Integration]
    LOCAL PROCEDURE OnBeforeExitGetTotalAmountLCY@10004500(VAR Customer_pr@10004500 : Record 18);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnBeforeExitGetTotalAmountLCYUI@10004501(VAR Customer_pr@10004500 : Record 18);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnBeforeExitGetTotalAmountLCYCommon@10004502(VAR Customer_pr@10004500 : Record 18;VAR AdditionalAmount_pf@10004501 : Decimal);
    BEGIN
    END;

--- Picture:
![image](https://user-images.githubusercontent.com/57808351/74427344-d1a6b300-4e4e-11ea-9eae-3206c2d69752.png)

**Comment by KristjanGaukur** [comment]
PS:
When we move to Extentions, then the field that we need to CALCFIELD/AUTOCALCFIELD will be in a TableExtension instead of added to Table 18.
I don't know if that affects how we will use the events in the first 2 functions.

**Comment by StanPesotskiy** [comment]
There is already the event called from GetTotalAmountLCYCommon. It should be enough to define an additional amount to add to the totals:
    [IntegrationEvent(false, false)]
    local procedure **OnBeforeGetTotalAmountLCYCommon**(var Customer: Record Customer; var AdditionalAmountLCY: Decimal)

```
    local procedure GetTotalAmountLCYCommon(): Decimal
    var
...
        AdditionalAmountLCY: Decimal;
    begin
        OnBeforeGetTotalAmountLCYCommon(Rec, **AdditionalAmountLCY**);
...
        exit("Balance (LCY)" + "Outstanding Orders (LCY)" + "Shipped Not Invoiced (LCY)" + "Outstanding Invoices (LCY)" +
          "Outstanding Serv. Orders (LCY)" + "Serv Shipped Not Invoiced(LCY)" + "Outstanding Serv.Invoices(LCY)" -
          SalesOutstandingAmountFromShipment - ServOutstandingAmountFromShipment - InvoicedPrepmtAmountLCY - RetRcdNotInvAmountLCY +
          **AdditionalAmountLCY**);
```
