### ISSUE TITLE
[Event Request] Table 37 "Sales Line" – "Line Amount" OnValidate

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6109]
[Event Request] Table 37 "Sales Line" – "Line Amount" OnValidate

Could we please have a publisher OnLineAmountOnBeforeTestfieldType with Handled Pattern in OnValidate "Line Amount" Table 37 "Sales Line"?

```
            trigger OnValidate()
            var
                MaxLineAmount: Decimal;
                // >>>>>>>>
                IsHandled: Boolean;
                // <<<<<<<<  
            begin
                // >>>>>>>>                    
                IsHandled := false;
                OnLineAmountOnBeforeTestfieldType(Rec, xRec, IsHandled);
                if IsHandled then
                    exit;
                // <<<<<<<<  

                TestField(Type);
                TestField(Quantity);

..

    // >>>>>>>>                    
    [IntegrationEvent(false, false)]
    local procedure OnLineAmountOnBeforeTestfieldType(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;
    // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
