### ISSUE TITLE
[Function Request] Codeunit 5510 ReservEntryExist as global function

### ISSUE THREAD

**Issue by sharkhpoenix** [Microsoft/ALAppExtensions#611]
Dear Microsoft Team,

could you please set the function ReservEntryExist as a global one?

We need it in several ways to check existing Reservation Entries to help our customers if there posting lines are correctly filled.

**Comment by darjoo** [comment]
Hi sharkhpoenix,
We have accepted your request. We usually include these types of changes in the next minor release, so look for it there.
