### ISSUE TITLE
[Event Request] Codeunit 99000773 OnAfterCalculate

### ISSUE THREAD

**Issue by RWeston6** [microsoft/ALAppExtensions#6112]
Can we please get a new event OnAfterCalculate at the end of the Calculate Function in Codeunit 99000773 Calculate Prod. Order? New Local Production Order var to be Got before so that the header can be passed through as well. 

ProdOrder.GET(ProdOrderLine.Status,ProdOrderLine."Prod. Order No.");
OnAfterCalculate(ProdOrder,ProdOrderLine,ErrorOccured);

LOCAL [IntegrationEvent] OnAfterCalculate(ProdOrder : Record "Production Order";ProdOrderLine : Record "Prod. Order Line";VAR ErrorOccurred : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
