### ISSUE TITLE
[Event Request] COD6661 Return Receipt Line - OnAfterDescriptionSalesLineInsert

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#6113]
Hi, could you please add the Event OnAfterDescriptionSalesLineInsert in TAB6661 simular to the Event in 110.

General also as code modifications the Event Publisher in TAB111 and TAB6661 should be held in parallel. That's like do a change on a sales order, but forgot the return order!

![image](https://user-images.githubusercontent.com/45033081/74435145-1557e780-4e64-11ea-8aa4-025b8b2fc0be.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
