### ISSUE TITLE
[Event Request] Page 6503 "Avail. - Item Tracking Lines": OnAfterUpdateReservMgt

### ISSUE THREAD

**Issue by SSZurmussen7112** [microsoft/ALAppExtensions#6114]
Hi Team,

In the past in page 99000896 the same publisher was already requested (https://github.com/microsoft/AL/issues/2251) and shipped. And in all other pages "Available - *" this publisher was inserted. But in Page 6503 "Avail. - Item Tracking Lines" this publisher is still missing (BC16). Please could you add this publisher in the same way as e.g. in page 99000896?

```
local procedure UpdateReservFrom()
begin
    SetReservSource(SourceRecRef, ReservEntry, ReservEntry."Source Subtype");

    // >> new
    OnAfterUpdateReservFrom(ReservEntry);
    // << new
end;
```

```
[IntegrationEvent(TRUE, false)]
local procedure OnAfterUpdateReservFrom(var ReservationEntry: Record "Reservation Entry")
begin
end;

```
Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
