### ISSUE TITLE
[Event Request] Table 37 "Sales Line": OnBeforeInitOutstandingAmount

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#6115]
Hello.
We have a change that checks if users are allowed to change prices.
To solve that we need a Publisher at the start of InitOutstandingAmount.
(I cannot use the On**After**InitOutstandingAmount as there I am missing both xRec and CurrFieldNo as parameters.)

**[External] InitOutstandingAmount()**
OnBeforeInitOutstandingAmount(Rec,xRec,CurrFieldNo); // New publisher at start of function.

---
**LOCAL [IntegrationEvent] OnBeforeInitOutstandingAmount_u(Rec : Record "Sales Line";xRec : Record "Sales Line";CurrFieldNo : Integer)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
