### ISSUE TITLE
[Event Request] Table 37 "Sales Line": OnUpdateUnitPriceItemResource.

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#6116]
Hello.
We are handling special sales discounts, and so need a Publisher in Table 37, function **UpdateUnitPrice** to fill out special fields when Type is Item, and after the FindSalesLinePrice has been run. I need to get Rec (VAR), xRec and the "Sales Price Calc. Mgt." (VAR) codeunit as parameters.

![image](https://user-images.githubusercontent.com/57808351/74448387-c49bbb00-4e72-11ea-9d15-79a83ec2b981.png)

---
**LOCAL [IntegrationEvent] OnUpdateUnitPrice**(**VAR** Rec_pr : Record "Sales Line";xRec_pr : Record "Sales Line";**VAR** PriceCalcMgt_pcu : **Codeunit "Sales Price Calc. Mgt."**)

**Comment by AlexanderYakunin** [comment]
We have changed this place and implemented Interface for Price Calculation, so you should be able to do your things without additional events. If something still needed, please create new request for this.

**Comment by KristjanGaukur** [comment]
Hello.
@AlexanderYakunin thank you for the tip. I have now solved my problem with the current events.
