### ISSUE TITLE
[Event Correction Request] Codeunit 5870 - OnBeforeTransferProdBOMLine

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#6117]
The event requested in #4106 was implemented incorrectly: 

In **codeunit 5870 "Calculate BOM Tree"**, event **OnBeforeTransferProdBOMLine**, the **var** before parameter ProdBOMLine is still missing.

Please change the event signature from 
`local procedure OnBeforeTransferProdBOMLine(var BOMBuffer: Record "BOM Buffer"; ProdBOMLine: Record "Production BOM Line"; var ParentItem: Record Item; var ParentBOMBuffer: Record "BOM Buffer"; var EntryNo: Integer; TreeType: Option " ",Availability,Cost; var IsHandled: Boolean)`
to
`local procedure OnBeforeTransferProdBOMLine(var BOMBuffer: Record "BOM Buffer"; var ProdBOMLine: Record "Production BOM Line"; var ParentItem: Record Item; var ParentBOMBuffer: Record "BOM Buffer"; var EntryNo: Integer; TreeType: Option " ",Availability,Cost; var IsHandled: Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
