### ISSUE TITLE
[External Function] COD "Transfer Extended Text" - function ReadLines

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#6118]
We would like to create some new functions following the same structure as the XXXCheckIfAnyExtText functions in codeunit 'Transfer Extended Text'. All follow the structure to first set filters on ExtendedTextHeader and then call ReadLines. However, **ReadLines** is not exposed yet. 

![image](https://user-images.githubusercontent.com/25268332/74451517-0aab4b80-4e80-11ea-900d-1127cbe89911.png)

_It would be great if this could still make the BC 16 / 2020 wave 1 release._

PS: ReadLines makes use of a global variable TempExtendedTextLine. The good thing is the global can be accessed already via GetTempExtTextLine.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
