### ISSUE TITLE
Codeunit 49 doesn't fire OnAfterOnDatabaseInsert when inserting records to table 21 

### ISSUE THREAD

**Issue by YuriyPopov** [microsoft/ALAppExtensions#6119]
Hello

When subscribing to the global event publisher OnAfterOnDatabaseInsert in the codeunit 49 it doesn't fire when a record is being inserted to the table 21. 

If the subscriber is set to the OnAfterInsertEvent event of the table 21 everything is working fine.

Is this the way it's supposed to be?

**Comment by YuriyPopov** [comment]
Eventually I found an answer to my question. There's another event publisher in the codeunit 49 which is called OnAfterGetDatabaseTableTriggerSetup. It's controlling the case whether a subscriber to a global database event should fire or not. It's possible to reassign one of the publisher variables (OnDatabaseInsert, OnDatabaseModify, OnDatabaseDelete, OnDatabaseRename) - true a global event will fire; false - it won't. Also there's a similar issue on [GitHub](https://github.com/Microsoft/AL/issues/1417)

**Comment by JesperSchulz** [comment]
Sounds as if this issue was "resolved". Closing it out.
