### ISSUE TITLE
Expose functions in Codeunit Flat File Management

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/ALAppExtensions#6121]
Hi,
Could you please make this codeunit:
12133	Flat File Management

Visible externally?
I've to implement the Withholding tax export and without this codeunit I'm stuck.

Thanks
Stefano

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
