### ISSUE TITLE
[Event Request] Codeunit 395 "FinChrgMemo-Issue" - OnRun() - OnBeforeGenJnlLinePost

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6122]
Dear BaseApp team,

There is a posting loop inside codeunit 395 "FinChrgMemo-Issue" - OnRun():
![OnRun - OnBeforeGenJnlLinePost - 01](https://user-images.githubusercontent.com/42442951/74457621-2ff48580-4e91-11ea-9b8e-ef5ceb2c0ea5.png)

We'd like to populate custom fields and do additional checks based on FinChrgeMemoHeader before sending the generated journal lines to posting. Please consider adding a new event that would allow such a thing. The desired event signature would be as follows:
![OnRun - OnBeforeGenJnlLinePost - 02](https://user-images.githubusercontent.com/42442951/74457689-4bf82700-4e91-11ea-9c6e-6941bc27b035.png)

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by MortenRa** [comment]
@AlexanderYakunin any updates on this one ?
