### ISSUE TITLE
[Extensibility enhancement] Pages 343 and 1871: Need to add own field into the check.

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#6123]
Hello.
We add our own FlowField to table 37 (that will go into a TableExtension), and need to include it into the fields in Page 1871 "Credit Limit Details", and affect the totals.
Can you add extension to pages 343 and 1871 so that we can have our field within the **PopulateDataOnNotification** and **InitializeFromNotificationVar** functions?
We also need a new function in Page 1871 to set the new field from additions in calls in Page 343.

Pictures of how we are currently doing this below (but maybe you have a better way of solving this?):

Page 1871:
1: New Variable:
![image](https://user-images.githubusercontent.com/57808351/74457123-bef8a200-4e7f-11ea-8232-063512225c0b.png)

2: New function:
![image](https://user-images.githubusercontent.com/57808351/74457186-d2a40880-4e7f-11ea-957d-56c061a8e8a8.png)

3: Changes in the Notification functions:
![image](https://user-images.githubusercontent.com/57808351/74457322-02531080-4e80-11ea-8634-936b1d38bd22.png)

4: The variable added to the ContentArea:
![image](https://user-images.githubusercontent.com/57808351/74457433-244c9300-4e80-11ea-90fb-f854a9eb10a4.png)

Page 343:
5: Handle the same value as in Page 1871 in Page 343.CalcCreditLimitLCY:
![image](https://user-images.githubusercontent.com/57808351/74457615-6a095b80-4e80-11ea-858c-b70baa515af0.png)

6: Add the field to function SetParametersOnDetails:
![image](https://user-images.githubusercontent.com/57808351/74457721-91f8bf00-4e80-11ea-9e97-7e95722c7c2e.png)

I hope this is clear enough, and that I am placing this request in the correct place.

**Comment by RomanZanizdra** [comment]
Hi @KristjanGaukur . Just for better understanding of what and how will be implemented, take a look at the code below. This is simple example of two fields from customer should be populated on credit limit details page.

tableextension 50101 CustExt extends Customer
{
    fields
    {
        field(50101; Field1; Decimal)
        {
            Caption = 'Field1';
            InitValue = 123.45;
        }
        field(50102; Field2; Decimal)
        {
            Caption = 'Field2';
            InitValue = 45.67;
        }
    }
}

pageextension 50101 CreditLimitDetailsExt extends "Credit Limit Details"
{
    layout
    {
        addafter(GetInvoicedPrepmtAmountLCY)
        {
            field(Field1; CreditLimitExt1)
            {
                Caption = 'Extension Field 1';
            }
            field(Field2; CreditLimitExt2)
            {
                Caption = 'Extension Field 2';
            }
        }
    }

    trigger OnOpenPage()
    begin
        GetExtensionAmounts(ExtensionAmounts);
        ExtensionAmounts.Get(1, CreditLimitExt1);
        ExtensionAmounts.Get(2, CreditLimitExt2);
    end;

    var
        CreditLimitExt1: Decimal;
        CreditLimitExt2: Decimal;
        ExtensionAmounts: List of [Decimal];
}

codeunit 50101 CreditLimitTransfer
{
    [EventSubscriber(ObjectType::Page, Page::"Check Credit Limit", 'OnAfterCalcCreditLimitLCY', '', true, true)]
    local procedure MyProcedure0(var Customer: Record Customer; var CustCreditAmountLCY: Decimal; var ExtensionAmounts: List of [Decimal])
    begin
        CustCreditAmountLCY := CustCreditAmountLCY + Customer.Field1 + Customer.Field2;
        ExtensionAmounts.Add(Customer.Field1);
        ExtensionAmounts.Add(Customer.Field2);
    end;

    [EventSubscriber(ObjectType::Page, Page::"Credit Limit Details", 'OnAfterPopulateDataOnNotification', '', true, true)]
    local procedure MyProcedure1(var CreditLimitNotification: Notification; var ExtensionAmounts: List of [Decimal])
    var
        ExtensionAmount: Decimal;
    begin
        if ExtensionAmounts.Get(1, ExtensionAmount) then
            CreditLimitNotification.SetData(Format(1), Format(ExtensionAmount));
        if ExtensionAmounts.Get(2, ExtensionAmount) then
            CreditLimitNotification.SetData(Format(2), Format(ExtensionAmount));
    end;

    [EventSubscriber(ObjectType::Page, Page::"Credit Limit Details", 'OnAfterInitializeFromNotificationVar', '', true, true)]
    local procedure MyProcedure2(CreditLimitNotification: Notification; var ExtensionAmounts: List of [Decimal])
    var
        ExtensionAmount: Decimal;
    begin
        Evaluate(ExtensionAmount, CreditLimitNotification.GetData(Format(1)));
        ExtensionAmounts.Add(ExtensionAmount);
        Evaluate(ExtensionAmount, CreditLimitNotification.GetData(Format(2)));
        ExtensionAmounts.Add(ExtensionAmount);
    end;
}

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
