### ISSUE TITLE
[Extensibility enhancement]: Page 343: GenJnlLineShowWarning (be able to get Error).

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#6124]
Hello.
We have a change where we, based on a setup, turn the Table::Field "Sales & Receivables Setup"::"Credit Warning" into an ERROR, for selected users. (I.e. the customer only want certain users to be able to overwrite the Credit Warning. Other salespersons are not allowed to overwrite.

Can we have a standard functionality change so that page 343 will not allow selected users to continue unless they are allowed by setup?

I hope that I am creating this request in the correct place.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
