### ISSUE TITLE
[Event Request] Codeunit 394 "FinChrgMemo-Make" - MakeHeader() - additional filters on header

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6125]
Dear BaseApp team,

In the MakeHeader() procedure of Codeunit 394 "FinChrgMemo-Make" the routine first tries to pick an existing FinChrgMemoHeader based on its "Customer No." and "Currency Code". We'd like to apply additional filters on possible headers that would include custom fields.

Please consider adding the following event:
![Codeunit 394 - MakeHeader - 01](https://user-images.githubusercontent.com/42442951/74495323-3a8a3b80-4ee0-11ea-936a-41489ce8a678.png)

The desired event signature is as follows:
![Codeunit 394 - MakeHeader - 02](https://user-images.githubusercontent.com/42442951/74495341-4675fd80-4ee0-11ea-8ec3-6ff5120f3fc8.png)

Thanks in advance.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by MortenRa** [comment]
@AlexanderYakunin any updates on this one ?
