### ISSUE TITLE
Salutation Formula enum for Name 1, Name 2, Name 3, Name 4, Name 5

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/ALAppExtensions#613]
Hi,

Can we have following option fields from **TAB5069 Salutation Formula**:

- Name 1, 
- Name 2, 
- Name 3, 
- Name 4, 
- Name 5

Converted into Enum type so we can extend that with additional options through extension?

Thanks,
Ivan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
