### ISSUE TITLE
[Event Request] Report 1095 "Update Job Item Cost"

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#6130]
In report 1095 "Update Job Item Cost", please 

1. Add trigger **OnPreReport** and a publisher **OnAfterPreReport**:
```
[...]
    labels
    {
    }

    // >> --- new
    trigger OnPreReport()
    begin
        OnAfterPreReport();
    end;
    // << --- new

    var
        Text001: Label 'The job ledger entry item costs have now been updated to equal the related item ledger entry actual costs.\\The number of job ledger entries modified = %1.', Comment = 'The Job Ledger Entry item costs have now been updated to equal the related item ledger entry actual costs.\\Number of Job Ledger Entries modified = 2.';
[...]    
```    
We don't need any parameters because we will check an internal flag set by #6129 in our extension only.

2. In function **PostTotalCostAdjustment**, please add publisher **OnPostTotalCostAdjustment_OnBeforeModifyJobLedgEntry** as follows:
```
[...]
            JobLedgEntry.Adjusted := true;
            JobLedgEntry."DateTime Adjusted" := CurrentDateTime;
            // >> ----- new
            OnPostTotalCostAdjustment_OnBeforeModifyJobLedgEntry(var JobLedgEntry, "Item Ledger Entry");
            // << ----- new
            JobLedgEntry.Modify();
[...]
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
