### ISSUE TITLE
[Extensibility Enhancement] Handle "Job Journal Line" in "Order Tracking" Page

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#6132]
In our app, we'd like to **extend page 99000822 "Order Tracking" with Job Journal Lines**, to which we have added additional fields.

This would require the following changes (including one event publisher):

**1. Table 210 "Job Journal Line"**

1.1 Add a new procedure GetSourceCaption:
```
    procedure GetSourceCaption(): Text
    begin
        exit(StrSubstNo('%1 %2 %3', "Journal Template Name", "Journal Batch Name", "No."));
    end;
```

**2. Codeunit 99000778 OrderTrackingManagement**

2.1 Add global variables:
```
        JobJnlLine: Record "Job Journal Line";
        ReserveJobJnlLine: Codeunit "Job Jnl. Line-Reserve";
```
2.2 Add procedure SetJobJnlLine:
```
    procedure SetJobJnlLine(var CurrentJobJnlLine: Record "Job Journal Line")
    begin
        CurrentJobJnlLine.TestField(Type, CurrentJobJnlLine.Type::Item);
        JobJnlLine := CurrentJobJnlLine;
        ReservEntry."Source Type" := DATABASE::"Job Journal Line";

        ReservEntry.InitSortingAndFilters(false);
        JobJnlLine.SetReservationFilters(ReservEntry);
        CaptionText := JobJnlLine.GetSourceCaption;
    end;
```

**3. Page 99000822 "Order Tracking"**

3.1 Add procedure SetJobJnlLine:
```
    procedure SetJobJnlLine(var CurrentJobJnlLine: Record "Job Journal Line")
    begin
        TrackingMgt.SetJobJnlLine(CurrentJobJnlLine);

        CurrItemNo := CurrentJobJnlLine."No.";
        OnAfterSetJobJnlLine(CurrQuantity, StartingDate, EndingDate);
    end;
```
3.2 Add event publisher OnAfterSetJobJnlLine
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetJobJnlLine(var CurrQuantity: Decimal; var StartingDate: Date; var EndingDate: Date)
    begin
    end;
```

**Comment by NKarolak** [comment]
About **2. Codeunit 99000778 OrderTrackingManagement** - this is only the "quick and dirty" approach for another standard table.
There is currently no "Set" function for any table, based on RecordRefs.

**Comment by AlexanderYakunin** [comment]
Should be already addressed by procedure SetVariantRec().
