### ISSUE TITLE
Modification of PEPPOL Documents (CU 1605)

### ISSUE THREAD

**Issue by eivindgiske** [microsoft/ALAppExtensions#6133]
When PEPPOL BIS EDI documents are used, there is often requirements to modify mapping of certain data.

Please add event publishers to all functions in Codeunit 1605 PEPPOL Management that map data. That way we can use the default XML Ports, and not have to Fork the codeunits and XMLports to an extension.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
