### ISSUE TITLE
Report 15000001 Suggest Remittance Payments (Norwegian Localization)

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#6135]
The report is missing the positive vendor ledger entries. This was working in previous versions. In the BC Spring release CU 04, it was removed and has not been working since.

OnAfterGetRecord=BEGIN
...
IF CheckLedgEntryType = CheckLedgEntryType::All THEN //Add line
  GetVendLedgEntries(TRUE,FALSE); //Add Line
GetVendLedgEntries(FALSE,FALSE);
...

**Comment by RomanZanizdra** [comment]
Hi @JonFjolnirAlbertsson . Looks like there was a bug reported for Norwegian version about suggestion of credit memos, it was fixed and now credit memos are not suggested. If you think this is a bug too or anything else please reach out the relevant support channel.

**Comment by hemmsi** [comment]
Hi @RomanZanizdra. Where would be the most appropriate place to raise issues related to the Norwegian version.

**Comment by RomanZanizdra** [comment]
Hi @hemmsi . Sorry for a little bit late reply and i'm not fully sure about relevant channels but here they are. Hope it helps.
Questions about local functionality should go to the community i suppose: https://community.dynamics.com/business/f/758

Bugs should reported in specified Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
