### ISSUE TITLE
[Event Request] Codeunit 1011 "Job Jnl.-Check Line" - RunCheck() - cancel a TestField

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6137]
Dear BaseApp team,

I'd like to kindly ask you to consider the following modification to the codeunit 1011 "Job Jnl.-Check Line", procedure RunCheck(), right before the Job.TestField(Status, Job.Status::Open):

![Codeunit 1011 -  RunCheck - 01](https://user-images.githubusercontent.com/42442951/74542841-0862f300-4f4d-11ea-849c-25f928ceddd2.png)

We have a special "mode" in the solution that allows for pulling big amounts of data from third-party systems to BC. The BC is run in this mode only once for a a customer when transitioning them from an old system to BC. The routine must push lots of data through BC's posting routines and we'd like to cancel some standard checks that usually take place in normal posting. 

There was another similar request partially fulfilled (sadly, not for the above TestField):
https://github.com/microsoft/ALAppExtensions/issues/2746

So please consider adding such a possibility for the above piece of code.

Thanks in advance.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
