### ISSUE TITLE
codeunit CRM Sales Order To Order Event request

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#6138]
is it possible to have an event in codeunit 5343 CRM Sales Order to Order in function CreateSalesOrderHeader:

local procedure CreateSalesOrderHeader(CRMSalesorder: Record "CRM Salesorder"; var SalesHeader: Record "Sales Header")
    var
        Customer: Record Customer;
    begin
        SalesHeader.Init;
        SalesHeader.Validate("Document Type", SalesHeader."Document Type"::Order);
        SalesHeader.Validate(Status, SalesHeader.Status::Open);
        SalesHeader.InitInsert;
        GetCoupledCustomer(CRMSalesorder, Customer);
        SalesHeader.Validate("Sell-to Customer No.", Customer."No.");
        SalesHeader.Validate("Your Reference", CopyStr(CRMSalesorder.OrderNumber, 1, MaxStrLen(SalesHeader."Your Reference")));
        SalesHeader.Validate("Currency Code", CRMSynchHelper.GetNavCurrencyCode(CRMSalesorder.TransactionCurrencyId));
        SalesHeader.Validate("Requested Delivery Date", CRMSalesorder.RequestDeliveryBy);
        CopyBillToInformationIfNotEmpty(CRMSalesorder, SalesHeader);
        CopyShipToInformationIfNotEmpty(CRMSalesorder, SalesHeader);
        CopyCRMOptionFields(CRMSalesorder, SalesHeader);
        SalesHeader.Validate("Payment Discount %", CRMSalesorder.DiscountPercentage);
        SalesHeader.Validate("External Document No.", CopyStr(CRMSalesorder.Name, 1, MaxStrLen(SalesHeader."External Document No.")));
        OnBeforeInsertSalesHeader(var SalesHeader,CRMSalesOrder); //new event
        SalesHeader.Insert;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by phil38000** [comment]
Dear,
I have an issue with this CU in Business Central SaaS 18.3
I subscribe to this publisher :
[EventSubscriber(ObjectType::Codeunit, Codeunit::"CRM Sales Order to Sales Order", 'OnCreateSalesOrderLinesOnBeforeSalesLineInsert', '', true, false)]
    local procedure OnCreateSalesOrderLinesOnBeforeSalesLineInsertExt(CRMSalesorderdetail: Record "CRM Salesorderdetail"; var SalesLine: Record "Sales Line")
    begin
        SalesLine.Validate("VAT Prod. Posting Group", CRMSalesorderdetail.DBEVATProdPostingGrp);        
    end;
    
   but when this event is triggered, Business Central crash with standard error "....Something Went Wrong..." :( 
   I tried without validate and same crash. I'm "SUPER" and ADMIN User.
   if someone has any idear, thanks by advance.
   have nice day
