### ISSUE TITLE
[Event Request] Recreate: Table 11400 CBG Statement - ProcessStatementASGenJournal (Dutch localisation)

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6139]
Hello,

Re: https://github.com/microsoft/ALAppExtensions/issues/3901

This event was marked as "already exists", but when checking BC15.2, it does NOT exist.

Could you please make sure it's reintroduced again?

Thanks,
Peter

![T11400 missing event](https://user-images.githubusercontent.com/18245218/74641727-0ded5280-5172-11ea-899f-58d3705ffd9f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
