### ISSUE TITLE
[Event Request] Codeunit 99000774, change Parameter of publisher to var

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#6140]
As already requested in https://github.com/microsoft/ALAppExtensions/issues/4227 we need Parameter "NextCapNeedLineNo" as VAR in Codeunit99000774 - Calculate Routing Line - Publisher "OnAfterCreateCapNeeded".

In Codeunit "Calculate Planning Route Line", 'OnAfterCreatePlanningCapNeed' the Parameter is implemented as VAR!

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
