### ISSUE TITLE
[Event Request] TAB 5405 - OnBeforeUpdateEndingDate - parameter CurrFieldNo

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#6142]
Can you add parameter CurrFieldNo to event OnBeforeUpdateEndingDate in table 5405 "Production Order"?

![image](https://user-images.githubusercontent.com/46031720/74649139-4c3d3e80-517f-11ea-9376-6852917bc5c6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
