### ISSUE TITLE
TAB37 - OnAfterCopyFromItem/OnAfterAssignItemUOM - AddCurrFieldNo-Parameter

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#6145]
Hi,

could you please add in TAB37 in the both existing events "OnAfterCopyFromItem" & "OnAfterAssignItemUOM" a CurrFieldNo-Parameter.

General It would be senseful if all table-integration-events have a CurrFieldNo-parameter by default (like the trigger-Events)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
