### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - CalcInvoice() - more control over Invoice flag

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6146]
Dear BaseApp team,

I'd like to kindly ask you to condider the following addition to the codeunit 80 "Sales-Post", procedure CalcInvoice():
![SalesPost - CalcInvoice - 01](https://user-images.githubusercontent.com/42442951/74668145-45c5bb80-51ad-11ea-8823-8c2d6111621d.png)

If the standard routine finds that NewInvoice = false, we'd like to make a check against some custom fields we have and possibly still set this flag to true in some cases.
The desirent event signature is as follows:
![SalesPost - CalcInvoice - 02](https://user-images.githubusercontent.com/42442951/74668171-55dd9b00-51ad-11ea-80e3-bb94fb9fb884.png)

Having a bit more control over this flag would be very useful.

Thanks.

**Comment by StanPesotskiy** [comment]
Please consider next time copying AL code from VSCode instead of posting screenshots. 
This would speed up the process.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
