### ISSUE TITLE
[Event Request] Codeunit 5802 Inventory Posting To G/L - OnAfterBufferSalesPosting - PostBufDimNo parameter passed by reference

### ISSUE THREAD

**Issue by KevRH** [microsoft/ALAppExtensions#6147]
Hi,

We have a requirement to post 4 G/L Entries when running Post Inventory Cost to G/L instead of the 2 that are currently posted.

We have a solution in place that subscribes to the OnAfterBufferSalesPosting event, which means we can insert an additional 2 records into the TempInvtPostingBuffer. However, we can't increase the value of the PostBufDimNo to get these entries to post to the G/L.

`    [IntegrationEvent(false, false)]
    local procedure OnAfterBufferSalesPosting(var TempInvtPostingBuffer: array[4] of Record "Invt. Posting Buffer" temporary; ValueEntry: Record "Value Entry"; PostBufDimNo: Integer)
    begin
    end;
`

Please could you change the event subscriber for OnAfterBufferSalesPosting to allow us to increase the value of the PostBufDimNo to get the additional lines posted.

I hope the above explains the issue that we have and the solution we require. Please let me know if you need any further information.

Many thanks,
Kevin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
