### ISSUE TITLE
[Exstensibility-Bug] Table 6302 - Power BI Report Buffer - Need to enlarge the field "EmbedUrl" to 1024

### ISSUE THREAD

**Issue by AI-91** [microsoft/ALAppExtensions#6148]
I've developed an easy report in PowerBI and published on my Business Central sandbox environment; I can see it successfully published on my Power BI workspace, but when I try to get it from the powerbi report i see the following error message:

![image](https://user-images.githubusercontent.com/41294390/74687906-111a2a00-51d6-11ea-8139-dffe5e10535e.png)

![image](https://user-images.githubusercontent.com/41294390/74687928-21caa000-51d6-11ea-804f-34c73bdcb58f.png)

So, it seems that the enbedUrl created  by the system is 288, while the maximum length is 250. For this reason, I would ask you to enlarge the field so to be able to use my custom reports on BC.
Also, I would suppose that the same change should be consequently applied to the following fields:
- Table 6301 - Power BI Report Configuration - Field "EmbedUrl"
- Table 6307 - Power BI Report Uploads - Field "Embed Url"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
