### ISSUE TITLE
[Event Request] Page 6550 "Whse. Item Tracking Lines"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6150]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "InsertItemTrackingLine".

Currently:
![image](https://user-images.githubusercontent.com/9529836/74338678-f1809d00-4da2-11ea-8d63-751499a17378.png)

shall be:
![image](https://user-images.githubusercontent.com/9529836/74338906-550aca80-4da3-11ea-9758-3b76d1c94833.png)

**Comment by StanPesotskiy** [comment]
Already done for [6042](https://github.com/microsoft/ALAppExtensions/issues/6042)
