### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6151]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "CheckSerialNoQty":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74336426-8634cc00-4d9e-11ea-81b1-0783bbdcb352.png)

Shall be:
![image](https://user-images.githubusercontent.com/9529836/74337217-2b03d900-4da0-11ea-943f-a6843ec7dc93.png)

And in function "FindBWPickBin":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74337324-5c7ca480-4da0-11ea-9506-1306c0d72eff.png)

Shall be:
![image](https://user-images.githubusercontent.com/9529836/74337448-96e64180-4da0-11ea-92db-2432e6885a9e.png)

And in function "ItemTrackedQuantity":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74337975-a023de00-4da1-11ea-98a3-4b9a6cd10fa9.png)

Shall be like:
![image](https://user-images.githubusercontent.com/9529836/74338199-03157500-4da2-11ea-96d7-3755cdcbf5fd.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.
