### ISSUE TITLE
[Event Request] Codeunit 7301 "Whse. Jnl.-Register Line"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6152]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "InsertWhseEntry":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74336028-cfd0e700-4d9d-11ea-980c-92b9edcab52b.png)

shall be like:
![image](https://user-images.githubusercontent.com/9529836/74336177-16bedc80-4d9e-11ea-83c1-f4339e6ba7db.png)

**Comment by StanPesotskiy** [comment]
Duplicate to [6040](https://github.com/microsoft/ALAppExtensions/issues/6040)
