### ISSUE TITLE
[Event Request] Codeunit 6500 "Item Tracking Management"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6153]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "SplitWhseJnlLine":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74335808-44efec80-4d9d-11ea-9177-f2be67667f00.png)

shall be like:
![image](https://user-images.githubusercontent.com/9529836/74335779-39042a80-4d9d-11ea-841d-ed62485704fc.png)

**Comment by StanPesotskiy** [comment]
Resolved in scope of [6039](https://github.com/microsoft/ALAppExtensions/issues/6039)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
