### ISSUE TITLE
[Event Request]Application “Tests-SCM”, Codeunit 137930 "SCM Item Charge Blocked Item"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6154]
[Event Request]Application “Tests-SCM”, Codeunit 137930 "SCM Item Charge Blocked Item"
![pic1](https://user-images.githubusercontent.com/45795262/74753014-cd73fe80-526f-11ea-850f-ecc6f71c2879.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedures Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74753024-d06eef00-526f-11ea-817d-da4ccb514010.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
