### ISSUE TITLE
[Event Request]Application “Tests-SCM”, Codeunit 137931 "SCM - Movement"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6155]
[Event Request]Application “Tests-SCM”, Codeunit 137931 "SCM - Movement"
![pic1](https://user-images.githubusercontent.com/45795262/74753142-fb594300-526f-11ea-9b87-ab64afce36cc.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedures Initialize?
![pic2](https://user-images.githubusercontent.com/45795262/74753148-fd230680-526f-11ea-82ac-40d289a5f21a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
