### ISSUE TITLE
[Event Request]Application “Tests-SMB”, Codeunit 138000 "O365 Simplify UI Sales Invoice"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6156]
[Event Request]Application “Tests-SMB”, Codeunit 138000 "O365 Simplify UI Sales Invoice"
![pic1](https://user-images.githubusercontent.com/45795262/74753361-4d9a6400-5270-11ea-99d0-fd6660ae9924.png)

We need the possibility to expand the excluded fields for the Sales Header and Sales Line in function VerifySalesDocumentsMatch.
As an example we switched from array to list and added an event for header and line.
Same also for Purchase Header and Purchase Line in function VerifyPurchaseDocumentsMatch.
![pic2](https://user-images.githubusercontent.com/45795262/74753377-55f29f00-5270-11ea-9ff6-6e961e70941d.png)
![pic3](https://user-images.githubusercontent.com/45795262/74753383-59862600-5270-11ea-971b-efbd8f22d602.png)
![pic4](https://user-images.githubusercontent.com/45795262/74753388-5be88000-5270-11ea-9317-1f4db990c941.png)
![pic5](https://user-images.githubusercontent.com/45795262/74753396-5e4ada00-5270-11ea-8f34-9c95b3270e04.png)
![pic6](https://user-images.githubusercontent.com/45795262/74753400-60ad3400-5270-11ea-9f50-67b024932c78.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
