### ISSUE TITLE
[Event Request] Codeunit 22 "Item Jnl.-Post Line"

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#6157]
To allow serial numbers with different quantity than -1, 0 or 1, I need a publisher in function "InsertItemLedgEntry":

Currently:
![image](https://user-images.githubusercontent.com/9529836/74335127-c21a6200-4d9b-11ea-8f2f-47d419e79263.png)

shall be:
![image](https://user-images.githubusercontent.com/9529836/74335098-b333af80-4d9b-11ea-8742-ab4f3c664bbf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
