### ISSUE TITLE
[Event Request]Application “Tests-SMB”, Codeunit 138050 "O365 Test Name Nearness"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6159]
[Event Request]Application “Tests-SMB”, Codeunit 138050 "O365 Test Name Nearness"
![pic1](https://user-images.githubusercontent.com/45795262/74753786-edf08880-5270-11ea-94cf-6fd25a09b3bd.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure:
![pic2](https://user-images.githubusercontent.com/45795262/74753789-efba4c00-5270-11ea-84e6-9c0a3410c084.png)
![pic3](https://user-images.githubusercontent.com/45795262/74753798-f21ca600-5270-11ea-8516-f89e81dd83e7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
