### ISSUE TITLE
[Event Request]Application “Tests-SMB”, Codeunit 138054 "O365 Test Update Cust. Addr."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6160]
[Event Request]Application “Tests-SMB”, Codeunit 138054 "O365 Test Update Cust. Addr."
![pic1](https://user-images.githubusercontent.com/45795262/74753887-15dfec00-5271-11ea-949c-06d95f4d0b69.png)

Could you please insert the OnTestInitialize Event at the beginning of each test procedure:
![pic2](https://user-images.githubusercontent.com/45795262/74753890-19737300-5271-11ea-82bd-986b7cafed1f.png)
![pic3](https://user-images.githubusercontent.com/45795262/74753899-1b3d3680-5271-11ea-9ab5-2c5d2fc0ee2f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
