### ISSUE TITLE
[Event Request]Application “Tests-SMB”, Codeunit 138100 "Streamline. Autofill No Series"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6161]
[Event Request]Application “Tests-SMB”, Codeunit 138100 "Streamline. Autofill No Series"
![pic1](https://user-images.githubusercontent.com/45795262/74754058-55a6d380-5271-11ea-9066-51303535ebb0.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize:
![pic2](https://user-images.githubusercontent.com/45795262/74754067-59d2f100-5271-11ea-925d-ddf307db4422.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
