### ISSUE TITLE
Page 6550 "Whse. Item Tracking Lines"

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#6162]
In order to create new Lines from a page action, and to show/hide fields based on parameters being passed from being opened Similiar to Item Tracking Lines.  Can you add the following function to Page 6550 Item Tracking Lines GetEditableSettings, GetVisibleSettings, and GetVariables. 

    // NEW
    procedure GetEditableSettings(var QtyToHandleBaseEditable2: Boolean; var NewSerialNoEditable2: Boolean; var NewLotNoEditable2: Boolean; var NewExpirationDateEditable2: Boolean; var ExpirationDateEditable2: Boolean)
    begin
        QtyToHandleBaseEditable2 := QtyToHandleBaseEditable;
        NewSerialNoEditable2 := NewSerialNoEditable;
        NewLotNoEditable2 := NewLotNoEditable;
        NewExpirationDateEditable2 := NewExpirationDateEditable;
        ExpirationDateEditable2 := ExpirationDateEditable;
    end;

    procedure GetVisibleSettings(var Handle1Visible2: Boolean; var Handle2Visible2: Boolean; var Handle3Visible2: Boolean; var QtyToHandleBaseVisible2: Boolean; var NewSerialNoVisible2: Boolean; var NewLotNoVisible2: Boolean; var NewExpirationDateVisible2: Boolean; var ButtonLineReclassVisible2: Boolean; var ButtonLineVisible2: Boolean)
    begin
        Handle1Visible2 := Handle1Visible;
        Handle2Visible2 := Handle2Visible;
        Handle3Visible2 := Handle3Visible;
        QtyToHandleBaseVisible2 := QtyToHandleBaseVisible;
        NewSerialNoVisible2 := NewSerialNoVisible;
        NewLotNoVisible2 := NewLotNoVisible;
        NewExpirationDateVisible2 := NewExpirationDateVisible;
        ButtonLineReclassVisible2 := ButtonLineReclassVisible;
        ButtonLineVisible2 := ButtonLineVisible;
    end;

    procedure GetVariables(var WhseWorksheetLine2: Record "Whse. Worksheet Line"; var Item2: Record Item; var UndefinedQtyArray2: array[2] of Decimal; var SourceQuantityArray2: array[2] of Decimal; var ColorOfQuantityArray2: array[2] of Integer; var FormSourceType2: Integer; var FormUpdated2: Boolean; var Reclass2: Boolean)
    begin
        WhseWorksheetLine2 := WhseWorksheetLine;
        Item2 := Item;
        CopyArray(UndefinedQtyArray2, UndefinedQtyArray, 1);
        CopyArray(SourceQuantityArray2, SourceQuantityArray, 1);
        CopyArray(ColorOfQuantityArray2, ColorOfQuantityArray, 1);
        FormSourceType2 := FormSourceType;
        FormUpdated2 :=  FormUpdated;
        Reclass2 := Reclass;
    end;  
    // NEW

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
