### ISSUE TITLE
[Event Request] OnAfterValidateCreateSalesInvoiceLine event

### ISSUE THREAD

**Issue by Killerkiwi2005** [microsoft/ALAppExtensions#6164]
JobCreateInvoice.Codeunit.al line CreateSalesInvoiceLines

Currently it validates JobPlanningLine."Job No." <> JobNo, we have a use case were we want to add multiple jobs from the same company/customer to an invoice

Adding an event after the validation allows custom validation while still defaulting to the current behavior

```
if JobPlanningLine."Job No." <> JobNo then
	LastError := StrSubstNo(Text009, JobPlanningLine.FieldCaption("Job No."));
OnAfterValidateCreateSalesInvoiceLine(JobPlanningLine, LastError);
if LastError <> '' then
	Error(LastError);
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterValidateCreateSalesInvoiceLine(var JobPlanningLine: Record "Job Planning Line"; var LastError: Text)
begin
end;
```

**Comment by Killerkiwi2005** [comment]
Also where is the code from Microsoft_Base Applicationin git hub? I would submit a pull request but my google skills are failing me, thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
