### ISSUE TITLE
[Enum Request] Various tables - "Entry Type" (Usage,Sale)

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#6165]
Please replace option field "Entry Type" with an extensible enum in the following tables:

- table 210 "Job Journal Line"
- table 169 "Job Ledger Entry"
- table 212 "Job Posting Buffer"
- table 207 "Res. Journal Line"
- table 203 "Res. Ledger Entry"
- table 5933 "Service Order Posting Buffer"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
