### ISSUE TITLE
[Event Change] Report 1003 - "Post Invt. Cost to G/L - Test" - OnBeforePreReport

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#6168]
Hi AL-Team,

can you please add the variable ItemValueEntry by var to the following Publisher?   

```
 [IntegrationEvent(false, false)]
    // local procedure OnBeforePreReport(var PostValueEntryToGL: Record "Post Value Entry to G/L"; ItemValueEntry: Record "Value Entry")
    local procedure OnBeforePreReport(var PostValueEntryToGL: Record "Post Value Entry to G/L"; var ItemValueEntry: Record "Value Entry")
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
