### ISSUE TITLE
[Function Request] Codeunit 5777 VerifyFieldNotChanged set to global

### ISSUE THREAD

**Issue by sharkhpoenix** [Microsoft/ALAppExtensions#617]
Dear Microsoft Team,

could you please set the function VerifyFieldNotChanged to a global one?

Otherwise we have to copy the function to our codeunit. I think a lot of developers would need it either because it is a general one.

**Comment by darjoo** [comment]
Hi sharkhpoenix,
This function has already been made external from another request. You should be able to view the change in the preview builds.
