### ISSUE TITLE
[Event Change] Table 5941 - "Service Item Component" - OnBeforeLookupVariantCode

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#6173]
Hi AL-Team,

can you please add the variable ServiceItemComponent by var to the following Publisher?

```
[IntegrationEvent(false, false)]
    // local procedure OnBeforeLookupVariantCode(ServiceItemComponent: Record "Service Item Component"; var IsHandled: Boolean)
    local procedure OnBeforeLookupVariantCode(var ServiceItemComponent: Record "Service Item Component"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
