### ISSUE TITLE
[Event Correction Request] Codeunit 6501 - "Item Tracking Data Collection" - OnRetrieveLookupDataOnBeforeTransferToTempRec #3904

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6175]
Hello,

The VAR for the ItemLedgerEntry parm in the requested publisher function is missing. This is essential for filtering.

Please change: 

`local procedure OnRetrieveLookupDataOnBeforeTransferToTempRec(var TempTrackingSpecification: Record "Tracking Specification" temporary; var TempReservationEntry: Record "Reservation Entry" temporary; ItemLedgerEntry: Record "Item Ledger Entry"; var FullDataSet: Boolean)
`
to

`local procedure OnRetrieveLookupDataOnBeforeTransferToTempRec(var TempTrackingSpecification: Record "Tracking Specification" temporary; var TempReservationEntry: Record "Reservation Entry" temporary; **var** ItemLedgerEntry: Record "Item Ledger Entry"; var FullDataSet: Boolean)
`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
