### ISSUE TITLE
[Enum Request] Table 5531 "Inventory Page Data": field 15 Type

### ISSUE THREAD

**Issue by SSZurmussen7112** [microsoft/ALAppExtensions#6180]
Hi team,

In table 5531 "Inventory Page Data" the field 15 Type is an Option field with a long list of tables.

I need to increase it to include own tables to this function. So please change the datatype from Option to Enum.

Thanks in advance!
Stephan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
