### ISSUE TITLE
[Event Request] Codeunit 211 "Res. Jnl.-Check Line" - CheckPostingDate() - override CheckAllowedPostingDate

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6181]
Dear BaseApp team,

It would be very useful if we could override the allowed posting date check in procedure CheckPostingDate of codeunit 211 "Res. Jnl.-Check Line":
![Codeunit 211 - CheckPostingDate - 01](https://user-images.githubusercontent.com/42442951/74850668-ec8f9080-5342-11ea-904b-14931c556505.png)

While it is possible to subscribe to corresponding event in "User Setup Management" codeunit (inside IsPostingDateValidWithSetup), we'd like to not to interfere with other uses of that procedure and handle the check on top of the call stack in codeunit 211.

The reason we we'd like to override the date check in the first place is that we need to check posting date against some of our custom setup fields.

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
