### ISSUE TITLE
[Event Request] OnBeforeOpenPage(record)

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [microsoft/ALAppExtensions#6182]
Scenario: 
We want to filter the cash receipt journal batch name (to match the username) before opening the page

Request:
Event with access to general journal line record before opening the page, e.g. OnInitPage or OnBeforeOpenPage.

**Comment by RomanZanizdra** [comment]
Hi @AbsolutelyFreeWeb . Could you be precise in your request, please let me know particular object, particular function and particular parameters for the event you needed.

**Comment by RomanZanizdra** [comment]
hi @AbsolutelyFreeWeb . Any update from your side?

**Comment by StanPesotskiy** [comment]
The detailed list of event's parameters was not provided.
