### ISSUE TITLE
salesOrderLines API endpoint should support Variant Codes

### ISSUE THREAD

**Issue by MBK75** [microsoft/ALAppExtensions#6183]
Hello, there is no Variant Code functionality in the salesOrderLines endpoint defined in SalesOrderLineEntity.Page.al.  We are having to copy the entire logic (parent page, other code, etc.) to a custom endpoint just to be able to expose this field.

Ideally, it would be nice simply to extend the subpage and then have events in the data registration functions.  At any rate, at least adding Variant Id would allow us to not have to implement customizations.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
