### ISSUE TITLE
[Event Request] Codeunit 13 "Gen. Jnl.-Post Batch" - CopyFields() - need additional filters

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6186]
Dear BaseApp team,

We'd like to be able to apply additional filters on both GenJnlLine4 and GenJnlLine6 in codeunit 13 "Gen. Jnl.-Post Batch", procedure CopyFields():
![GenJnlPostBatch - CopyFields - 01](https://user-images.githubusercontent.com/42442951/74938842-700ab980-53f7-11ea-9488-cdfe47cbc037.png)

The event signature is as follows:
![GenJnlPostBatch - CopyFields - 02](https://user-images.githubusercontent.com/42442951/74938857-79942180-53f7-11ea-9325-3a8475986057.png)

Please consider applying this modification to the BaseApp.

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
