### ISSUE TITLE
CSV Buffer Readlines

### ISSUE THREAD

**Issue by superjma** [microsoft/ALAppExtensions#6187]
Can you please update the ReadLine function in CSV Buffer table to the following, because I have many issues right now with quotes is being ignored. For instance if I want to import a file with mail and the customers have written "xx@xx.com;yy@yy.com" i the mail field my import will fail.

This should solve the issue.

IF StreamReader.EndOfStream THEN
  EXIT(FALSE);
REPEAT
  String := StreamReader.ReadLine;
  CurrentLineNo += 1;
  CurrentIndex := 0;
  REPEAT
    IF String.Substring(CurrentIndex,1) = '"' THEN BEGIN
      InQuotes := TRUE;
      CurrentIndex := CurrentIndex + 1;
    END ELSE
      InQuotes := FALSE;

    CurrentFieldNo += 1;
    INIT;
    "Line No." := CurrentLineNo;
    "Field No." := CurrentFieldNo;
    IF InQuotes THEN
      NextIndex := String.IndexOf('"',CurrentIndex)
    ELSE
      NextIndex := String.IndexOf(Separator,CurrentIndex);
    
    IF NextIndex = -1 THEN
      Length := String.Length - CurrentIndex
    ELSE
      Length := NextIndex - CurrentIndex;
    IF Length > 250 THEN
      Length := 250;

    IF InQuotes THEN BEGIN
      Value := String.Substring(CurrentIndex+1,Length-2);
      NextIndex := NextIndex + 1;
    END ELSE
      Value := String.Substring(CurrentIndex,Length);

    CurrentIndex := NextIndex + 1;
    INSERT;
  UNTIL NextIndex = -1;
  CurrentFieldNo := 0;
UNTIL StreamReader.EndOfStream OR (CurrentLineNo = NumberOfLines);
EXIT(TRUE);

**Comment by JesperSchulz** [comment]
We're going to fix this in the upcoming minor release. Thanks for reporting.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for releasee 17.

**Comment by superjma** [comment]
Here is an updated code.. maybe you can use it.
IF StreamReader.EndOfStream THEN
  EXIT(FALSE);
REPEAT
  String := StreamReader.ReadLine;
  CurrentLineNo += 1;
  CurrentIndex := 0;
  REPEAT
    //JMA-01:Start
    IF String.Length > CurrentIndex THEN BEGIN
      IF String.Substring(CurrentIndex,1) = '"' THEN BEGIN
        InQuotes := TRUE;
        CurrentIndex := CurrentIndex + 1;ReadLines(0);
      END ELSE
        InQuotes := FALSE;
    END;
    //JMA-01:End

    CurrentFieldNo += 1;
    INIT;
    "Line No." := CurrentLineNo;
    "Field No." := CurrentFieldNo;
    //JMA-01:Start
    //NextIndex := String.IndexOf(Separator,CurrentIndex);
    IF InQuotes THEN
      NextIndex := String.IndexOf('"',CurrentIndex)
    ELSE
      NextIndex := String.IndexOf(Separator,CurrentIndex);
    //JMA-01:End

    IF NextIndex = -1 THEN
      Length := String.Length - CurrentIndex
    ELSE
      Length := NextIndex - CurrentIndex;
    IF Length > 250 THEN
      Length := 250;

    //JMA-01:Start
    IF InQuotes THEN BEGIN
      //Value := String.Substring(CurrentIndex+1,Length-2);
      IF String.IndexOf(Separator,CurrentIndex) <> -1 THEN
        NextIndex := NextIndex + 1
      ELSE
        NextIndex := -1;
    END;
    //JMA-01:End

    Value := String.Substring(CurrentIndex,Length);
    CurrentIndex := NextIndex + 1;
    INSERT;
  UNTIL NextIndex = -1;
  CurrentFieldNo := 0;
UNTIL StreamReader.EndOfStream OR (CurrentLineNo = NumberOfLines);
EXIT(TRUE);
