### ISSUE TITLE
[Event Request] Codeunit 13 "Gen. Jnl.-Post Batch" - CheckAndCopyBalancingData() - additional checks

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6188]
Dear BaseApp team,

In codeunit 13 "Gen. Jnl.-Post Batch" procedure CheckAndCopyBalancingData() there is a loop on GenJnlLine6 where it collects TempGenJnlLines based on GenJnlLine6 and on balancing data from GenJnlLine4. Also, prior to copying there is a check for correct posting types in GenJnlLine6:

![GenJnlPostBatch - CheckAndCopyBalancingData - 01](https://user-images.githubusercontent.com/42442951/74952896-9afe0900-5409-11ea-9ea7-bf30c6dc1954.png)

It is possible to override that check with OnBeforeCheckGenPostingType() event:

![GenJnlPostBatch - CheckAndCopyBalancingData - 02](https://user-images.githubusercontent.com/42442951/74952942-a6513480-5409-11ea-88ad-0d326758469f.png)

It would be very useful if we could check GenJnlLine6 against additional fields from GenJnlLine4 (where we copy balancing data from). Unfortunately the GenJnlLine4 is currently not available neither for that event, nor inside CheckGenPostingType() procedure.

Please consider adding a modification that would push GenJnlLine4 to OnBeforeCheckGenPostingType event through CheckGenPostingType() parameters.

OR

A different option would fit if we could make additional checks in CheckAndCopyBalancingData() either before or after the CheckGenPostingType() call having GenJnlLine4, GenJnlLine6 and AccountType available.

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
