### ISSUE TITLE
Reset function in Codeunit 5465 "Graph Mgt - General Tools" has scope OnPrem

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#6189]
This code in Codeunit 6153 "API Webhook Notification Mgt." calls function IsApiSubscriptionEnabled in codeunit "Graph Mgt - General Tools" and then caches the value.

But IsApiSubscriptionEnabled supports an event OnGetAPISubscriptionsEnabled with handled pattern. So it we can temporarily suspend webhook subscriptions, for example when we initialize data.

However, because the value is cached, it will never revert back to the server setting during the user session. Obviously the Reset() function can be used to reset, but it has scope OnPrem. Please remove this, so we can temporarily disable webhook subscriptions.

```
    local procedure IsApiSubscriptionEnabled(): Boolean
    var
        GraphMgtGeneralTools: Codeunit "Graph Mgt - General Tools";
    begin
        if UseCachedApiSubscriptionEnabled then
            exit(CachedApiSubscriptionEnabled);

        CachedApiSubscriptionEnabled := GraphMgtGeneralTools.IsApiSubscriptionEnabled;
        UseCachedApiSubscriptionEnabled := true;

        exit(CachedApiSubscriptionEnabled);
    end;

    [Scope('OnPrem')]
    procedure Reset()
    begin
        UseCachedApiSubscriptionEnabled := false;
        Clear(CachedApiSubscriptionEnabled);
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
