### ISSUE TITLE
The type or method 'SetItemJnlLine' cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by sandeepchapte** [Microsoft/ALAppExtensions#619]
Hi Guys,
We are making our steps toward extension development. While converting our solution to AL extensions we made a list of functions that we would like to be exposed as external functions. Here's the list & need below methods to be opened for our app. Please check. 

Report 5899 Calculate Inventory Value
Functions : SetItemJnlLine and InitializeRequest
The type or method 'SetItemJnlLine' cannot be used for 'Extension' development.
The type or method 'InitializeRequest' cannot be used for 'Extension' development.

Table 5804 Avg. Cost Adjmt. Entry Point
Function : GetValuationPeriod
The type or method 'GetValuationPeriod' cannot be used for 'Extension' development.

AL Extension Version: 2.0.43900 (RC3)
Server Version: NL 13.0.24535

Regards
Sandeep

**Comment by darjoo** [comment]
Hi sandeepchapte,
The functions you're requesting have already been made external :) Please test against the preview build and you should have no issues developing against that. They will be available live in the next minor release. 

Darrick

**Comment by sandeepchapte** [comment]
Thanks Darrick.
