### ISSUE TITLE
[Event Request] Codeunit 7010 - Purch. Price Calc. Mgt.

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6190]
We kindly ask you to add one parameter "FoundPurchPrice" to event OnAfterFindPurchLinePrice in codeunit 7010 - Purch. Price Calc. Mgt.

**Event**
`OnAfterFindPurchLinePrice(VAR PurchaseLine : Record "Purchase Line";VAR PurchaseHeader : Record "Purchase Header";VAR PurchasePrice : Record "Purchase Price";CalledByFieldNo : Integer;FoundPurchPrice : Boolean)`

**Execution**
```
[External] FindPurchLinePrice(VAR PurchHeader : Record "Purchase Header";VAR PurchLine : Record "Purchase Line";CalledByFieldNo : Integer)
WITH PurchLine DO BEGIN
  SetCurrency(
    PurchHeader."Currency Code",PurchHeader."Currency Factor",PurchHeaderExchDate(PurchHeader));
  SetVAT(PurchHeader."Prices Including VAT","VAT %","VAT Bus. Posting Group");
.
.
.
          "Direct Unit Cost" := TempPurchPrice."Direct Unit Cost";
      END;
  END;
  OnAfterFindPurchLinePrice(PurchLine,PurchHeader,TempPurchPrice,CalledByFieldNo,FoundPurchPrice);
  
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
