### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnAfterSetUnitOfMeasureCode

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#6191]
Can you add event OnAfterSetUnitOfMeasureCode in table 83 to be able to override "Unit of Measure Code" before it is validated?

![image](https://user-images.githubusercontent.com/46031720/75030006-7eaeaa80-54a3-11ea-9e3c-22bf75bd48e4.png)

![image](https://user-images.githubusercontent.com/46031720/75030024-879f7c00-54a3-11ea-8c32-8193270d48d5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
