### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnAfterCalcInternalLeadTimeDays

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6192]
Requesting 1 new event publisher on table 39 - Purchase Line

**Event**
`LOCAL [IntegrationEvent] OnAfterCalcInternalLeadTimeDays(PurchaseLine : Record "Purchase Line";PurchDate : Date;VAR TotalDays : DateFormula)`

**Execution**
```
[External] InternalLeadTimeDays(PurchDate : Date) : Text[30]
EVALUATE(
  TotalDays,'<' + FORMAT(CALCDATE("Safety Lead Time",CALCDATE("Inbound Whse. Handling Time",PurchDate)) - PurchDate) + 'D>');

>>> New Code
OnAfterCalcInternalLeadTimeDays(Rec,PurchDate,TotalDays);
<<< New Code End

EXIT(FORMAT(TotalDays));
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
