### ISSUE TITLE
[Event Request] Table 83 - Item Journal Line - OnBeforeValidateLocationCode

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6193]
Requesting 1 new event publisher on table 83 - Item Journal Line with handled pattern

**Event**
`LOCAL [IntegrationEvent] OnBeforeValidateLocationCode(Rec : Record "Item Journal Line";xRec : Record "Item Journal Line";VAR IsHandled : Boolean)`

**Execution**
```
Location Code - OnValidate()
>>> New Code
IsHandled := FALSE;
OnBeforeValidateLocationCode(Rec,xRec,IsHandled);
IF IsHandled THEN
  EXIT;
<<< New Code End

IF "Entry Type" <= "Entry Type"::Transfer THEN
  TESTFIELD("Item No.");
.
.
.
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
