### ISSUE TITLE
Copy Item: Preset Target Item No, return new Item record

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#6194]
Talking about the "new" **Copy Item** page 729 and codeunit 730.

Am I right to see that, calling Copy Item from code **is not possible** with
1. presetting the target Item No. and/or other values (=presetting the CopyItemBuffer)
2.  not presenting the "request" page to the user
3. returning the new Item record,

at least without the need to activate manual event subscribers in point 3?

If so, I'd request that possibility. If not, please advise. Is there some code sample available?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
