### ISSUE TITLE
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" - PostUnApplyCustomerCommit() - suppress dialog

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6196]
Dear BaseApp team,

Is is possible that you add a possibility to suppress dialog window saying "Unapplying and posting..." in codeunit 226, procedure PostUnApplyCustomerCommit()?
![PostUnapplyCustomerCommit - 01](https://user-images.githubusercontent.com/42442951/75042346-ef1af300-54c6-11ea-9aa0-3771d9071f4f.png)

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
