### ISSUE TITLE
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" - ApplyCustEntryFormEntry() - additional filters

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6197]
Dear BaseApp team,

In codeunit 226 "CustEntry-Apply Posted Entries", procedure ApplyCustEntryFormEntry() before showing the "Apply Customer Entries" page, it would be very useful if we could set additional filters on CustLedgEntry based on some ApplyingCustLedgEntry fields:
![ApplyCustEntryFormEntry - 01](https://user-images.githubusercontent.com/42442951/75043491-d8759b80-54c8-11ea-88ea-aea13f40274e.png)

The desired event signature:
![ApplyCustEntryFormEntry - 02](https://user-images.githubusercontent.com/42442951/75043525-e4615d80-54c8-11ea-8c9f-b4bc6a7b72e0.png)

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
