### ISSUE TITLE
CHANGECOMPANY in "Job Queue Entry".ScheduleTask

### ISSUE THREAD

**Issue by larswestman** [microsoft/ALAppExtensions#6198]
Can we have COMPANYNAME changed to CURRENTCOMPANY in the function ScheduleTask so we can enable a Job Queue Entry in another company?

Today it's not possible to loop through companies and enable job queue entries.

**Comment by StanPesotskiy** [comment]
There is the event OnBeforeScheduleTask(Rec, TaskGUID);
you subscribe and do 
```
TaskGUID := 
     TASKSCHEDULER.CreateTask(
            CODEUNIT::"Job Queue Dispatcher",
            CODEUNIT::"Job Queue Error Handler",
            true, **Rec.CURRENTCOMPANY** , "Earliest Start Date/Time", Rec.RecordId));
```
Would it work for you?

**Comment by larswestman** [comment]
No. Note really. What I'm doing is that I'm managing Job Que Entries in multiple companies from one single company. 

Let's say you have fetched stopped job queue entries into a temporary table from other companies and you want to schedule them, Then you can do CHANGECOMPANY for each record you have fetched and call JobQueueEntry.ScheduleTask as you loop throught the fetched records.

The problem is that in the function ScheduleTask "COMPANYNAME" is used instead of "CURRENTCOMPANY" so my CHANGECOMPANY in my exection loop has no effect.

If I do this change is works just perfect

  TASKSCHEDULER.CREATETASK(
    CODEUNIT::"Job Queue Dispatcher",
    CODEUNIT::"Job Queue Error Handler",
//>>START
    //TRUE,COMPANYNAME,"Earliest Start Date/Time",RECORDID));
    TRUE,CURRENTCOMPANY,"Earliest Start Date/Time",RECORDID));
//<<STOP

With this change the function ScheduleTask is aware of the CHANGECOMPANY.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
