### ISSUE TITLE
[Event Request] Codeunit 5520 - Get Unplanned Demand

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6199]
Requesting 6 new event publisher on codeunit 5520 - Get Unplanned Demand

**Event 1**
`LOCAL [IntegrationEvent] OnBeforeGetUnplannedSalesLine(VAR SalesLine : Record "Sales Line";VAR UnplannedDemand : Record "Unplanned Demand")`

**Execution 1**
```
LOCAL GetUnplannedSalesLine(VAR UnplannedDemand : Record "Unplanned Demand")
>>> New Code
OnBeforeGetUnplannedSalesLine(SalesLine,UnplannedDemand);
<<< New Code End

WITH UnplannedDemand DO
.
.
.
```

**Event 2**
`LOCAL [IntegrationEvent] OnBeforeGetUnplannedProdOrderComp(VAR ProdOrderComp : Record "Prod. Order Component";VAR UnplannedDemand : Record "Unplanned Demand")`

**Execution 2**
```
LOCAL GetUnplannedProdOrderComp(VAR UnplannedDemand : Record "Unplanned Demand")
>>> New Code]
OnBeforeGetUnplannedProdOrderComp(ProdOrderComp,UnplannedDemand);
<<< New Code End
WITH UnplannedDemand DO
.
.
.

```
**Event 3**
`LOCAL [IntegrationEvent] OnBeforeGetUnplannedAsmLine(VAR AsmLine : Record "Assembly Line";VAR UnplannedDemand : Record "Unplanned Demand")`

**Execution 3**
```
LOCAL GetUnplannedAsmLine(VAR UnplannedDemand : Record "Unplanned Demand")
>>> New Code
OnBeforeGetUnplannedAsmLine(AsmLine,UnplannedDemand);
<<< New Code End
WITH UnplannedDemand DO
.
.
.
```

**Event 4**
`LOCAL [IntegrationEvent] OnBeforeGetUnplannedServLine(VAR ServiceLine : Record "Service Line";VAR UnplannedDemand : Record "Unplanned Demand")`

**Execution 4**
```
LOCAL GetUnplannedServLine(VAR UnplannedDemand : Record "Unplanned Demand")
>>> New Code
OnBeforeGetUnplannedServLine(ServLine,UnplannedDemand);
<<< New Code End
WITH UnplannedDemand DO
.
.
.
```

**Event 5**
`LOCAL [IntegrationEvent] OnBeforeGetUnplannedJobPlanningLine(VAR JobPlanningLine : Record "Job Planning Line";VAR UnplannedDemand : Record "Unplanned Demand")`

**Execution 5**
```
LOCAL GetUnplannedJobPlanningLine(VAR UnplannedDemand : Record "Unplanned Demand")
>>> New Code
OnBeforeGetUnplannedJobPlanningLine(JobPlanningLine,UnplannedDemand);
<<< New Code End
WITH UnplannedDemand DO
.
.
.
```

**Event 6 (With handled Pattern)**
`LOCAL [IntegrationEvent] OnBeforeGetProdOrderCompNeededQty(ProdOrderComp : Record "Prod. Order Component";VAR NeededQty : Decimal;VAR IsHandled : Boolean)`

**Execution 6**
```
LOCAL GetProdOrderCompNeededQty(ProdOrderComp : Record "Prod. Order Component") : Decimal
>>> New Code
OnBeforeGetProdOrderCompNeededQty(ProdOrderComp,NeededQty,IsHandled);
IF IsHandled THEN
  EXIT(NeededQty);
<<< New Code End

WITH ProdOrderComp DO BEGIN
.
.
.
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
