### ISSUE TITLE
EventRequest OnPopulateApprovalEntryArgument in CU1535 #1266

### ISSUE THREAD

**Issue by dicksonkimeu** [Microsoft/ALAppExtensions#620]
On NAV 2018 how can i make this work ? seems resolve BC.

**Comment by JesperSchulz** [comment]
Thanks for submitting your request. Unfortunately we cannot help you in this repository. Issues reported in this repository will only be addressed in the upcoming major release, as certain processes apply for changing code in versions released to market. For more information on our branching strategy, please read here: [AL Developer Previews, multiple releases, and GitHub](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github). 
For any changes to released versions you should contact our Support team. You can open Support Request to CSS through the [PartnerSource portal](https://mbs2.microsoft.com/Support/SupportRequestStep1.aspx) or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you step-by-step on how to open a support request or how to get credentials if this is the first time you or your company are engaging Support.
