### ISSUE TITLE
[Event Request] Codeunit 5836 - Cost Calculation Management

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6200]
Requesting 1 new event publisher on codeunit 5836 - Cost Calculation Management

**Event**
`LOCAL [IntegrationEvent] OnAfterRoutingCostPerUnit2(Type : 'Work Center,Machine Center';VAR DirUnitCost : Decimal;VAR IndirCostPct : Decimal;VAR OvhdRate : Decimal;VAR UnitCost : Decimal;VAR UnitCostCalculation : 'Time,Unit';WorkCenter : Record "Work `

**Execution**
```
[External] RoutingCostPerUnit2(Type : 'Work Center,Machine Center';VAR DirUnitCost : Decimal;VAR IndirCostPct : Decimal;VAR OvhdRate : Decimal;VAR UnitCost : Decimal;VAR UnitCostCalculation : 'Time,Unit';WorkCenter : Record "Work Center";MachineCenter
UnitCostCalculation := UnitCostCalculation::Time;
CASE Type OF
  Type::"Work Center":
    BEGIN
      UnitCostCalculation := WorkCenter."Unit Cost Calculation";
.
.
.
      UnitCost := MachineCenter."Unit Cost";
    END;
END;

>>> New Code
OnAfterRoutingCostPerUnit2(Type,DirUnitCost,IndirCostPct,OvhdRate,UnitCost,UnitCostCalculation,WorkCenter,MachineCenter);
<<< New Code End
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
