### ISSUE TITLE
[Event Request] Codeunit 5870 - Calculate BOM Tree

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6201]
Requesting 1 new event publisher on codeunit 5870 - Calculate BOM Tree

**Event**
`LOCAL [IntegrationEvent] OnCalcRoutingCostsOnBeforeBOMBufferAdd(RoutingLine : Record "Routing Line";LotSize : Decimal;ScrapPct : Decimal;VAR CapCost : Decimal;VAR SubcontractedCapCost : Decimal;VAR CapOverhead : Decimal)`

**Execution**
```
LOCAL CalcRoutingLineCosts(RoutingLine : Record "Routing Line";LotSize : Decimal;ScrapPct : Decimal;VAR BOMBuffer : Record "BOM Buffer";ParentItem : Record Item)
OnBeforeCalcRoutingLineCosts(RoutingLine,LotSize,ScrapPct,ParentItem);

CalcStdCost.SetProperties(WORKDATE,FALSE,FALSE,FALSE,'',FALSE);
CalcStdCost.CalcRtngLineCost(
  RoutingLine,CostCalculationMgt.CalcQtyAdjdForBOMScrap(LotSize,ScrapPct),CapCost,SubcontractedCapCost,CapOverhead);

>>> New Code
OnCalcRoutingCostsOnBeforeBOMBufferAdd(RoutingLine,LotSize,ScrapPct,CapCost,SubcontractedCapCost,CapOverhead);
<<< New Code End

BOMBuffer.AddCapacityCost(CapCost,CapCost);
BOMBuffer.AddSubcontrdCost(SubcontractedCapCost,SubcontractedCapCost);
BOMBuffer.AddCapOvhdCost(CapOverhead,CapOverhead);

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
