### ISSUE TITLE
[Event Request] Codeunit 99000774 - Calculate Routing Line

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6202]
Requesting 1 new event publisher on codeunit 99000774 - Calculate Routing Line 

**Event**
`LOCAL [IntegrationEvent] OnCalcRoutingLineBackOnBeforeGetQueueTime(VAR ProdOrderRoutingLine : Record "Prod. Order Routing Line";VAR ProdOrderRoutingLine2 : Record "Prod. Order Routing Line";VAR ProdOrderRoutingLine3 : Record "Prod. Order Routing Line"`

**Execution**
```
LOCAL CalcRoutingLineBack(CalculateEndDate : Boolean)
CalendarEntry.SETRANGE(Date,0D,ProdOrderRoutingLine."Ending Date");

ProdEndingTime := ProdOrderRoutingLine."Ending Time";
ProdEndingDate := ProdOrderRoutingLine."Ending Date";
.
.
.
      SetMinDateTime(ProdEndingDate,ProdEndingTime,ProdStartingDate,ProdStartingTime);
      ProdOrderRoutingLine3 := ProdOrderRoutingLine2;
    UNTIL ProdOrderRoutingLine2.NEXT = 0;

  >>> New Code
  OnCalcRoutingLineBackOnBeforeGetQueueTime(ProdOrderRoutingLine,ProdOrderRoutingLine2,ProdOrderRoutingLine3);
  <<< New Code End

  IF ProdOrderRoutingLine3."Prod. Order No." <> '' THEN BEGIN
.
.
.
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
