### ISSUE TITLE
[Event Request] Page 515 – Item Avail. By Location Lines

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6205]
Requesting 1 new event publisher on page 515 – Item Avail. By Location Lines

**Event**
`LOCAL [IntegrationEvent] OnSetBeforeCurrentPage(VAR Location : Record Location;VAR Item : Record Item;VAR NewItem : Record Item;NewAmountType : 'Net Change,Balance at Date')`

**Execution**
```
[External] Set(VAR NewItem : Record Item;NewAmountType : 'Net Change,Balance at Date')
Item.COPY(NewItem);
PeriodStart := Item.GETRANGEMIN("Date Filter");
PeriodEnd := Item.GETRANGEMAX("Date Filter");
AmountType := NewAmountType;

>>> New Code
OnSetBeforeCurrentPage(Rec,Item,NewItem,NewAmountType);
<<< New Code End

CurrPage.UPDATE(FALSE);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
