### ISSUE TITLE
[Event Request] Page 99000883 - Sales Order Planning

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6206]
Requesting 1 new event publisher on page 99000883 - Sales Order Planning

**Event**
`LOCAL [IntegrationEvent] OnCreateOrdersOnAfterTestCreateProdOrder(VAR SalesPlanningLine : Record "Sales Planning Line";VAR SalesLine : Record "Sales Line";VAR CreateProdOrder : Boolean)`

**Execution**
```
LOCAL CreateOrders() OrdersCreated : Boolean
xSalesPlanLine := Rec;

IF NOT FINDSET THEN
.
.
.
      CreateProdOrder := Item."Replenishment System" = Item."Replenishment System"::"Prod. Order";
    END;

    >>> New Code
    OnCreateOrdersOnAfterTestCreateProdOrder(Rec,SalesLine,CreateProdOrder);
    <<< New Code End

    IF CreateProdOrder THEN BEGIN
      OrdersCreated := TRUE;
      ProdOrderFromSale.CreateProdOrder(SalesLine,NewStatus,NewOrderType);
.
.
.
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
