### ISSUE TITLE
[Event Request] Report 6001 Batch Post Service Orders

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6207]
Could you please add the requested parameters to the publisher as requested in #4279? 
We need the parameters for our alternative posting. Also IsHandled shouldn't mean that we processed the posting, we would like to be able to skip posting of some type of service. In this case it would mean that the processed counter should not be updated by returning false.

    local procedure PostServiceHeader(var ServiceHeader: Record "Service Header"): Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        // START
        //OnBeforePostServiceHeader(ServiceHeader, IsHandled);
        //if IsHandled then
        //    exit(true);
        OnHandleServicePost(VAR "Service Header", VAR IsHandled, VAR IsSkipped, ReplacePostingDate, ReplaceDocumentDate, PostingDateReq, ShipReq, InvReq);
        if IsHandled then
            exit(NOT IsSkipped);
        // END

        Clear(ServPost);
        ServPost.SetPostingDate(ReplacePostingDate, ReplaceDocumentDate, PostingDateReq);
        ServPost.SetPostingOptions(ShipReq, false, InvReq);
        ServPost.SetHideValidationDialog(true);
        exit(ServPost.Run(ServiceHeader));
    end;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
