### ISSUE TITLE
[Event Request] Codeunit 99000787 - Create Prod. Order Lines

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#6208]
Requesting 1 new event publisher on codeunit 99000787 - Create Prod. Order Lines with handled pattern

**Event**
`LOCAL [IntegrationEvent] OnBeforeIsReplSystemProdOrder(SalesLine : Record "Sales Line";VAR IsReplSysProdOrder : Boolean;VAR IsHandled : Boolean)`

**Execution**
```
LOCAL IsReplSystemProdOrder(ItemNo : Code[20];VariantCode : Code[10];LocationCode : Code[10]) : Boolean
>>> New Code
OnBeforeIsReplSystemProdOrder(SalesLine,IsReplSysProdOrder,IsHandled);
IF IsHandled THEN
   EXIT(IsReplSysProdOrder);
<<< New Code End

IF SKU.GET(LocationCode,ItemNo,VariantCode) THEN
  EXIT(SKU."Replenishment System" = SKU."Replenishment System"::"Prod. Order");

Item.GET(ItemNo);
EXIT(Item."Replenishment System" = Item."Replenishment System"::"Prod. Order");
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
