### ISSUE TITLE
[Event Requests] Codeunit 5805 - "Item Charge Assgnt. (Purch.)".

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#6209]
Hello. 

We need to assign item charges to "Transfer Receipt Lines", which is not possible in the function "AssignByAmount" in codeunit 5805.

So, as per the picture added below, we need an "ELSE" part to the CASE expression where an Event Publisher is called, which we can subscribe to and handle our need for "Transfer Receipts":

**OnAssignByAmount(ItemChargeAssgntPurch,PurchHeader,TempItemChargeAssgntPurch);**

Note, that the last parameter is a VAR parameter.

---
The publisher is defined as:
LOCAL [IntegrationEvent] OnAssignByAmount(ItemChargeAssgntPurch : Record "Item Charge Assignment (Purch)";PurchHeader : Record "Purchase Header";**VAR** TempItemChargeAssgntPurch : TEMPORARY Record "Item Charge Assignment (Purch)")

![image](https://user-images.githubusercontent.com/57808351/75141841-bdce3d00-56e9-11ea-9bfb-7315c8b3b0ca.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
