### ISSUE TITLE
[Field Length] Table 5717, Item Cross Reference  [Code 20 -> Code 22] 

### ISSUE THREAD

**Issue by keshavopk** [microsoft/ALAppExtensions#6210]
Hello,

We need the  "Cross-Reference No." in  "Item Cross Reference" Table to be length of 22 in case of Barcode. As our renowned clients use the Barcode from 22 Character which are Provided by their multiple suppliers.
So we request you please increase the length of field "Cross-Reference No." [field No. 6, from 20 to 22 ] with in Standard BC itself.

Thank you.

**Comment by AlexanderYakunin** [comment]
We cannot increase length of fields included into primary key of table. This is known issue but we currently have no solution for this.

**Comment by keshavopk** [comment]
even, Is it not possible to consider this in upcoming version ?

**Comment by keshavopk** [comment]
even, Is it not possible to consider this in upcoming version ?
