### ISSUE TITLE
[Event Parameter Request] Codeunit 442 > OnBeforePostPrepayments > PreviewMode

### ISSUE THREAD

**Issue by supercruel** [microsoft/ALAppExtensions#6211]
We need the Parameter "PreviewMode" in the "OnBeforePostPrepayments" event in Codeunit 442.
Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
