### ISSUE TITLE
[Event Request] Codeunit 5979 > OnAfterPostAndSend

### ISSUE THREAD

**Issue by supercruel** [microsoft/ALAppExtensions#6212]
We need the following event in Codeunit 5979 for our AddOn:

```
LOCAL Code()
[...]
OnAfterPostAndBeforeSend(ServiceHeader);
Commit;

ServicePost.SendPostedDocumentRecord(ServiceHeader, TempDocumentSendingProfile);

//+New
OnAfterPostAndSend(ServiceHeader);
//-New
```

Thanks

**Comment by StanPesotskiy** [comment]
Already implemented for [339](https://github.com/Microsoft/ALAppExtensions/issues/339)

**Comment by supercruel** [comment]
It was not implemented with 339.
339 added On**Before**PostAndSend, we need On**After**PostAndSend

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
