### ISSUE TITLE
[Event Request] Codeunit 395 "FinChrgMemo-Issue" - OnRun(): GenJnlLine populate additional fields

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6213]
Dear BaseApp team,

It would be very useful if we could populate additional fields from FinChrgMemoHeader to GenJnlLine in codeunit 395 "FinChrgMemo-Issue", OnRun procedure, in the "Post Interest" block before the GenJnlLine is inserted:
![OnBeforePostInterestGenJnlLineInsert - 01](https://user-images.githubusercontent.com/42442951/75164476-8f705200-5729-11ea-9e07-596243130a9c.png)

The desired event signature:
![OnBeforePostInterestGenJnlLineInsert - 02](https://user-images.githubusercontent.com/42442951/75164528-9dbe6e00-5729-11ea-9f41-9b0e3d216941.png)

Thanks

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation. Please update the request.

**Comment by AndriiPochekailov** [comment]
Hi Stan,

Sorry if that caused troubles. Please ignore this request as we found a different way to handle the required modification. 
Thanks.
