### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting – 

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6224]
[Event Request] Codeunit 99000854 Inventory Profile Offsetting – OnMaintainPlanningLineOnBeforeReqLineInsert

Could we please a supplement at Publishers OnMaintainPlanningLineOnBeforeReqLineInsert in Codeunit 99000854 Inventory Profile Offsetting? 

```
    // >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnMaintainPlanningLineOnBeforeReqLineInsert(var RequisitionLine: Record "Requisition Line"; var SupplyInvtProfile: Record "Inventory Profile"; PlanToDate: Date; CurrentForecast: Code[10]; NewPhase: Option " ","Line Created","Routing Created",Exploded,Obsolete; Direction: Option Forward,Backward; DemandInvtProfile: Record "Inventory Profile"; ExcludeForecastBefore: Date)
    begin
    end;
    // <<<<<<<<

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
