### ISSUE TITLE
[Function Expose] Codeunit  99000854 "Inventory Profile Offsetting" - Fct. InsertSupplyProfile

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6227]
[Function Expose] Codeunit  99000854 "Inventory Profile Offsetting" - Fct. InsertSupplyProfile

Please change the Visibility of Function InsertSupplyProfile in Codeunit  99000854 "Inventory Profile Offsetting" to Global:

```
-     local procedure InsertSupplyProfile(var InventoryProfile: Record "Inventory Profile"; ToDate: Date)
+     procedure InsertSupplyProfile(var InventoryProfile: Record "Inventory Profile"; ToDate: Date)

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
