### ISSUE TITLE
[Enum Request] "Correspondence Type"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6229]
[Enum Request] "Correspondence Type"

Please change the Optionfield "Correspondence Type" to Enum.

```
table 5065 "Interaction Log Entry": field "Correspondence Type"
table 5064 "Interaction Template": field "Correspondence Type (Default)"
table 5076 "Segment Header": field "Correspondence Type (Default)"
table 5077 "Segment Line": field „Correspondence Type"

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
