### ISSUE TITLE
[Event Request] Report 7318 - OnAfterCalculateQuantityToPick

### ISSUE THREAD

**Issue by makuhn** [Microsoft/ALAppExtensions#623]
Add new integration event **OnAfterCalculateQuantityToPick** in Report 7318.

OnAfterGetRecord trigger of DataItem Table7321:
```
        QtyToPickBase := "Qty. (Base)" - ("Qty. Picked (Base)" + "Pick Qty. (Base)");
        QtyToPick := Quantity - ("Qty. Picked" + "Pick Qty.");
+       OnAfterCalculateQuantityToPick("Warehouse Shipment Line",QtyToPick,QtyToPickBase);
        IF QtyToPick > 0 THEN BEGIN
          IF "Destination Type" = "Destination Type"::Customer THEN BEGIN
```
New publisher function:
```
    [Integration]
    LOCAL PROCEDURE OnAfterCalculateQuantityToPick@5172322(WarehouseShipmentLine@5172322 : Record 7321;VAR QtyToPick@5172324 : Decimal;VAR QtyToPickBase@5172323 : Decimal);
    BEGIN
    END;
```

**Comment by ThomasBrodkorb** [comment]
Will this event have a VAR on the WhseShipmentLine as well?
I would else have to request another event at almost the same place!

**Comment by makuhn** [comment]
We requested it without VAR for WhseShipmentLine. Therefore I expect that Microsoft will add this event according to code listing above.

I think it is sufficient to create a new issue requesting to change the parameter declaration. We did this already in the past when we faced the same situation for events that did already exist.
