### ISSUE TITLE
[Enum Request] "Line Option"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6230]
[Enum Request] "Line Option"

Please change the Optionfield "Line Option" to Enum.

```
table 5821 "Item Statistics Buffer": field "Line Option"

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
