### ISSUE TITLE
[Enum Request] "Salutation Type"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6231]
[Enum Request] "Salutation Type"

Please change the Optionfield "Salutation Type" to Enum.

```
table 5069 "Salutation Formula": field "Salutation Type"

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
