### ISSUE TITLE
Extension from Event "OnAfterSetStartDate" in Codeunit 1720 "Deferral Utilities"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#6233]
Old:
OnAfterSetStartDate(DeferralTemplate, StartDate);

New:
OnAfterSetStartDate(DeferralTemplate, StartDate, AdjustedStartDate);
```

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetStartDate(DeferralTemplate: Record "Deferral Template"; var StartDate: Date; var AdjustedStartDate: Date)
    begin
    end;
```
DeferralStartDate is new an Enum so I need the posibility to change the AdjustedStartDate

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
