### ISSUE TITLE
Handling HideProgressWindow in CU 80

### ISSUE THREAD

**Issue by lexxsoul** [microsoft/ALAppExtensions#6234]
In the beginning of CU 80 we have an event which has sevaral flags
OnBeforePostSalesDoc(Rec,SuppressCommit,PreviewMode,HideProgressWindow); 

SuppressCommit and PreviewMode are locally saved, then CLEARALL wipes the variables and saved values are restored.

But HideProgressWindow value is not handled, so it is reset.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
