### ISSUE TITLE
Event "OnBeforeHandledChosenEntries" in pages 233 and 234 changed between version 14 and 15

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/ALAppExtensions#6235]
Why was the event "OnBeforeHandledChosenEntries" in pages 233 and 234 changed? In version 14 you could still work with it because there was "GlobalVarAccess". 

![image](https://user-images.githubusercontent.com/22373356/75321551-45928380-5871-11ea-9766-310841707528.png)

But the function where the event is called contains global variables, which are also displayed on the user interface. Because the property "GlobalVarAccess" has been removed now, this event is completely useless.

![image](https://user-images.githubusercontent.com/22373356/75321831-e5e8a800-5871-11ea-8e5d-aaec0171974b.png)

So you can't simply overwrite any logic here, because you don't have the chance to change the global variables.

What's the point of this?

**Comment by AlexanderYakunin** [comment]
Because GlobalVarAccess property is not supported anymore. We have Protected VAR concept instead. May partners requested new versions of events due to this. You can do the same.

**Comment by FSharpCSharp** [comment]
Thanks for the advice. But it doesn't change the fact that this is so very dangerous, because you don't notice it when compiling, but are just wondering why the result is different.

Do you have a suggestion how to solve this with the event here?

We have to reach this point because we changed something in the equalization logic. In C/AL it looks like this in a classic way:

![image](https://user-images.githubusercontent.com/22373356/75335761-4edc1a00-588a-11ea-976e-c651894d6c08.png)

As you can see, we're changing certain queries here so that different results come out. In other parts of the program this is not a problem, but this page gives us a headache.

How can we achieve something like this again? In version 14 the GlobalVarAccess was our salvation, because it gave us direct access to all variables available in the page.

**Comment by AlexanderYakunin** [comment]
You simply need to work with VSCode and 15.X+, you will see notification about all deprecated items. 
In your case you need to refactor part of code into local procedure and add OnBefore handled event to manage conditional logic.

**Comment by FSharpCSharp** [comment]
I have already worked with the V15 extension in VSCode and have not received any information about it. Therefore I am now surprised by this statement.

To your solution suggestion:

Unfortunately, it can't be implemented. It looks like you did not quite understand my problem. I can't just use the OnBefore-Event, make a copy of the function and put my logic there. Inside the page there are the global varialbs PossiblePmtdisc and AppliedAmount to which these conditions cause a change. Because I don't have a GlobalVarAccess anymore I can't set these parameters anywhere. This means that half of the function is not compilable because they are purely global variables within the page. And the OnBefore event does not help me at all, because I cannot change the result displayed there in any way.

**Comment by AlexanderYakunin** [comment]
Read this https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-protected-variables

**Comment by FSharpCSharp** [comment]
Have you ever actually looked at the affected pages? Then you would have seen that the article described in you does not apply to any of the global variables mentioned there.

![image](https://user-images.githubusercontent.com/22373356/75446073-fcbcf680-5966-11ea-9d2d-69f4538661d9.png)

Therefore, unfortunately, this does not help me at all.

**Comment by NKarolak** [comment]
@FSharpCSharp  What I think Alexander is meaning, is that you simply request those marked variables to be declared as protected.

**Comment by AlexanderYakunin** [comment]
Yes, we receive many requests of thus type now, so I expected this is straight forward. Anyway you can request t make some global variables to be protected and they will be available for you in extension.

**Comment by NKarolak** [comment]
@AlexanderYakunin I did not understand neither until you gave us the link ;-) 
There are many [Event Request] or [Function Exposure] issues, but I've never seen any [Protected Var Request] issues 🤷‍♀️

**Comment by AlexanderYakunin** [comment]
We still use label "Request-for-external" for it

**Comment by FSharpCSharp** [comment]
But that sounded anything but just like a simple request to me. Actually, I had hoped that Microsoft itself would think along with the conversion of such events and provide the variables all as protected if at least one event with GlobalVarAccess exists.

But this way it is very uncomfortable and also not target-oriented in the implementation.

Why wasn't there anything in the What's New documents for this version about the major changes that were made, and so on?

Oh yes, by the way, the solution is more than stupid in the implementation. I have to subscribe to the event in a PageExtension and set and adjust the global variables there. Why isn't there something like the possibility to overwrite whole functions directly, like in any other programming language. All in all, this is not very useful and not so great. My old computer science teacher would turn over in his grave with such logic.

**Comment by AlexanderYakunin** [comment]
We receive 500+ requests monthly for period of 1.5 years. We cannot add evens to ANY procedure and line of code as most of them will never be used. Please ask what you need and we will do it for you, but if you don't ask than we will do other requests.

**Comment by FSharpCSharp** [comment]
Then I hereby officially request that the following global variables be marked as protected in the two mentioned pages:

Customer (233):
- AppliedCustLedgEntry
- CustLedgEntry
- GenJnlLine2
- PmtDiscAmount
- AppliedAmount
- DifferentCurrenciesInAppln
- ApplnCurrencyCode

Vendor (234):
- AppliedVendLedgEntry
- VendLedgEntry
- GenJnlLine2
- PmtDiscAmount
- AppliedAmount
- DifferentCurrenciesInAppln
- ApplnCurrencyCode

I also apologize for the inconvenience. Unfortunately, all the communication here was a bit rough and that led to this little escalation. I am sorry about this.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
