### ISSUE TITLE
Refactor Table 39/37 Procedure GetDate

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#624]
The actual function getDate in Table 39 returns the "Posting Date" of PurchHeader.
But PurchHeader might not be read and cannot be set calling PurchLine.GetPurchHeader, as the function GetPurchHeader is only local.

I would suggest to call GetPurchHeader inside of GetDate. As an alternative GetPurchHeader might be declared as External. Same Behaviour and Suggestion for Table 37 and GetSalesHeader.

[External] GetDate() : Date
GetPurchHeader;  -- new call to guarantee the correct PurchaseHeader
IF PurchHeader."Posting Date" <> 0D THEN
  EXIT(PurchHeader."Posting Date");
EXIT(WORKDATE);

**Comment by miljance** [comment]
We need this as well!

**Comment by mazhelez** [comment]
Hi @miljance 

I believe the issue has been fixed. Expect it available in the Spring 19 release 😄
