### ISSUE TITLE
Posted Sales Invoices - No. Printed not counted for OIOUBL invoices (DK localization)

### ISSUE THREAD

**Issue by kvamsdal** [microsoft/ALAppExtensions#6240]
Hi, 

When sending invoices with Document Sending Profile OIOUBL the No. Printed on Posted Sales Invoice is not added one. 

The reason seems to be, that the EventSubscriber in the OIOUBL subscribers for OnBeforeSend is not increasing this value. 

We cannot fix this problem for our customer without modifying the OIOUBL extension since no integration events is available in the OIOUBL subscribers for onBeforeSend, and the procedure "send" in DocumentsSendingProfile never reaches the OnAfterSend event.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
