### ISSUE TITLE
[External] Table T36/38 Function ShouldLookFor

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#6241]
Please make Function ShouldLookForVendorByName in Table 38 externally available.
Please make Function ShouldLookForCustomerByName in Table 36 externally available.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
