### ISSUE TITLE
[Event Request] New Function CallReportCopySalesDocument  – Action "CopyDocument"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6248]
[Event Request] New Function CallReportCopySalesDocument  – Action "CopyDocument"

Can we please have a new function CallReportCopySalesDocument with Handled Pattern for the action "CopyDocument" of the sales document pages. 
Pages:
•	Page 41 "Sales Quote"
•	Page 42 "Sales Order"
•	Page 43 "Sales Invoice"
•	Page 44 "Sales Credit Memo"
•	Page 507 "Blanket Sales Order"
•	Page 6630 "Sales Return Order"

Alternatively, you could also include the handled patterns in every call.
We need the changes because the reports cannot be customized.

```
    // >>>>>>>>
    procedure CallReportCopySalesDocument(var SalesHeader: Record "Sales Header")
    var
        CopySalesDoc: Report "Copy Sales Document";
        IsHandled: Boolean;
    begin
        OnBeforeCallReportCopySalesDocument(SalesHeader, IsHandled);
        if IsHandled then begin
            CopySalesDoc.SetSalesHeader(SalesHeader);
            CopySalesDoc.RunModal();
            Clear(CopySalesDoc);
        end;
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallReportCopySalesDocument(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
   // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
