### ISSUE TITLE
[Event Request] New Function CallReportCopyPurchaseDocument  – Action "CopyDocument"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6249]
[Event Request] New Function CallReportCopyPurchaseDocument  – Action "CopyDocument"

Can we please have a new function CallReportCopyPurchaseDocument with Handled Pattern for the action "CopyDocument" of the purchase document pages. 
Pages:
•	Page 49 "Purchase Quote"
•	Page 50 "Purchase Order"
•	Page 51 "Purchase Invoice"
•	Page 52 "Purchase Credit Memo"
•	Page 509 "Blanket Purchase Order"
•	Page 6640 "Purchase Return Order"

Alternatively, you could also include the handled patterns in every call.
We need the changes because the reports cannot be customized.

Can you please have a look at the tooltips of the actions, some of them talk about sales document.

```
    // >>>>>>>>
    procedure CallReportCopyPurchaseDocument(var PurchhaseHeader: Record "Purchase Header")
    var
        CopyPurchDoc: Report „Copy Purchase Document“;
        IsHandled: Boolean;
    begin
        OnBeforeCallReportCopyPurchaseDocument(PurchhaseHeader, IsHandled);
        if IsHandled then begin
            CopyPurchDoc.SetPurchHeader(PurchhaseHeader);
            CopyPurchDoc.RunModal();
            Clear(CopyPurchDoc);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallReportCopyPurchaseDocument(var PurchhaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;
   // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
