### ISSUE TITLE
[Event Request] Table 37 - "Sales Line", Table 81 - "Gen. Journal Line" -> OnBeforeShowDeferrals

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#6250]
We need the Event "OnBeforeShowDeferrals" in Sales, Purchase and GL
Purchase OK:  
![grafik](https://user-images.githubusercontent.com/45654195/75363388-59aea300-58ba-11ea-8335-4af232f6fb13.png)  

Sales NOK:  
![grafik](https://user-images.githubusercontent.com/45654195/75363420-629f7480-58ba-11ea-81e6-cbe2b846e307.png)  

GL NOK:  
![grafik](https://user-images.githubusercontent.com/45654195/75363477-7519ae00-58ba-11ea-9e74-a69a54541008.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
