### ISSUE TITLE
[Event Request] Table 81 - Gen. Journal Line

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#6253]
[https://github.com/microsoft/ALAppExtensions/issues/3384](https://github.com/microsoft/ALAppExtensions/issues/3384)

I miss the Event on " Field 72 - "Bal. VAT Base Amount" , trigger OnValidate"

```
Field 72 - "Bal. VAT Base Amount" , trigger OnValidate
Event
LOCAL [IntegrationEvent] OnBeforeValidateAmount(VAR Rec: Record "Gen. Journal Line";Currency: Record "Currency" )
Code

.
.
.
        "VAT %" := 0;
      "VAT Amount" :=
        ROUND("VAT Amount",Currency."Amount Rounding Precision");
      Amount := "VAT Base Amount" + "VAT Amount";
    END;
END;
>>> New Code
OnBeforeValidateAmount(Rec, Currency);
<<< New Code End
VALIDATE(Amount);

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
