### ISSUE TITLE
[Event Request] Codeunit 87 Blanket Sales Order to Order - OnRun

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6255]
We would like to request the following publisher so we can have our own calculation if contract is exceeding, and also add possibility for user to ignore if the contract is exceeding. There is a simular request for purchase #6256.

                    if SalesLine.FindSet then
                        repeat
                            if (SalesLine."Document Type" = SalesLine."Document Type"::"Return Order") or
                               ((SalesLine."Document Type" = SalesLine."Document Type"::"Credit Memo") and
                                (SalesLine."Return Receipt No." = ''))
                            then
                                QuantityOnOrders := QuantityOnOrders - SalesLine."Outstanding Qty. (Base)"
                            else
                                if (SalesLine."Document Type" = SalesLine."Document Type"::Order) or
                                   ((SalesLine."Document Type" = SalesLine."Document Type"::Invoice) and
                                    (SalesLine."Shipment No." = ''))
                                then
                                    QuantityOnOrders := QuantityOnOrders + SalesLine."Outstanding Qty. (Base)";
                        until SalesLine.Next = 0;
                    /// START >>
                    SkipError := FALSE;
                    OnSkipDoContractExceedingCheck(BlanketOrderSalesLine, QuantityOnOrders, VAR SkipError);
                    IF NOT SkipError THEN
                    /// END <<
                      if (Abs(BlanketOrderSalesLine."Qty. to Ship (Base)" + QuantityOnOrders +
                            BlanketOrderSalesLine."Qty. Shipped (Base)") >
                          Abs(BlanketOrderSalesLine."Quantity (Base)")) or
                         (BlanketOrderSalesLine."Quantity (Base)" * BlanketOrderSalesLine."Outstanding Qty. (Base)" < 0)
                      then
                          Error(
                            QuantityCheckErr,
                            BlanketOrderSalesLine.FieldCaption("Qty. to Ship (Base)"),
                            BlanketOrderSalesLine.Type, BlanketOrderSalesLine."No.",
                            BlanketOrderSalesLine.FieldCaption("Line No."), BlanketOrderSalesLine."Line No.",
                            BlanketOrderSalesLine."Outstanding Qty. (Base)" - QuantityOnOrders,
                            StrSubstNo(
                              Text001,
                              BlanketOrderSalesLine.FieldCaption("Outstanding Qty. (Base)"),
                              BlanketOrderSalesLine.FieldCaption("Qty. to Ship (Base)")),
                            BlanketOrderSalesLine."Outstanding Qty. (Base)", QuantityOnOrders);
                    SalesOrderLine := BlanketOrderSalesLine;
                    ResetQuantityFields(SalesOrderLine);
                    SalesOrderLine."Document Type" := SalesOrderHeader."Document Type";
                    SalesOrderLine."Document No." := SalesOrderHeader."No.";
                    SalesOrderLine."Blanket Order No." := "No.";
                    SalesOrderLine."Blanket Order Line No." := BlanketOrderSalesLine."Line No.";

Many thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
