### ISSUE TITLE
[Event Request] Codeunit 97 Blanket Purch. Order to Order - OnRun

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6256]
We would like to request the following publisher so we can have our own calculation if contract is exceeding, and also add possibility for user to ignore if the contract is exceeding. There is a simular request for sales #6255.

                    if PurchLine.FindSet then
                        repeat
                            if (PurchLine."Document Type" = PurchLine."Document Type"::"Return Order") or
                               ((PurchLine."Document Type" = PurchLine."Document Type"::"Credit Memo") and
                                (PurchLine."Return Shipment No." = ''))
                            then
                                QuantityOnOrders := QuantityOnOrders - PurchLine."Outstanding Qty. (Base)"
                            else
                                if (PurchLine."Document Type" = PurchLine."Document Type"::Order) or
                                   ((PurchLine."Document Type" = PurchLine."Document Type"::Invoice) and
                                    (PurchLine."Receipt No." = ''))
                                then
                                    QuantityOnOrders := QuantityOnOrders + PurchLine."Outstanding Qty. (Base)";
                        until PurchLine.Next = 0;

                /// START >>
                SkipError := FALSE;
                OnSkipDoContractExceedingCheck(PurchBlanketOrderLine, QuantityOnOrders, VAR SkipError);
                IF NOT SkipError THEN
                /// END <<

                    if (Abs(PurchBlanketOrderLine."Qty. to Receive (Base)" + QuantityOnOrders +
                          PurchBlanketOrderLine."Qty. Received (Base)") >
                        Abs(PurchBlanketOrderLine."Quantity (Base)")) or
                       (PurchBlanketOrderLine."Quantity (Base)" * PurchBlanketOrderLine."Outstanding Qty. (Base)" < 0)
                    then
                        Error(
                          QuantityCheckErr,
                          PurchBlanketOrderLine.FieldCaption("Qty. to Receive (Base)"),
                          PurchBlanketOrderLine.Type, PurchBlanketOrderLine."No.",
                          PurchBlanketOrderLine.FieldCaption("Line No."), PurchBlanketOrderLine."Line No.",
                          PurchBlanketOrderLine."Outstanding Qty. (Base)" - QuantityOnOrders,
                          StrSubstNo(
                            Text001,
                            PurchBlanketOrderLine.FieldCaption("Outstanding Qty. (Base)"),
                            PurchBlanketOrderLine.FieldCaption("Qty. to Receive (Base)")),
                          PurchBlanketOrderLine."Outstanding Qty. (Base)", QuantityOnOrders);

                    PurchOrderLine := PurchBlanketOrderLine;
                    ResetQuantityFields(PurchOrderLine);
                    PurchOrderLine."Document Type" := PurchOrderHeader."Document Type";
                    PurchOrderLine."Document No." := PurchOrderHeader."No.";
                    PurchOrderLine."Blanket Order No." := "No.";
                    PurchOrderLine."Blanket Order Line No." := PurchBlanketOrderLine."Line No.";

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
