### ISSUE TITLE
Need to add SQL Server Name to Active Session Table

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#6257]
Can Microsoft add SQL Server name (including SQL Server instance) to Active Session Virtual Table. It will really help to workout the SQL Server name of the Database, which would be useful for many add-ons (extensions).

**Comment by jensmpmsft** [comment]
In general we do not want to expose 'environment information' in the Active Session Virtual table, so we currently do not have plans to expose that.
A workaround would be for you to call your own 'configuration service' / tenant to database mapping to get which database server is serving this tenant.

**Comment by Rama-M** [comment]
Hi Jens,

Can you please elaborate more with some detail code to extract the SQL details from AL code.

Also i do not see any security concerns as who ever have access to the active session table would have know about the SQL server to connect to it.

But exposing the SQL Name is a really important feature we all use at now using Dot net nowadays. Going forward we could not get this. This is my concern.

Thanks

Rama Mathanmohan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
