### ISSUE TITLE
[Reference Parameter Request] codeunit 1235 XML Buffer Writer

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#6258]
Ref. case https://github.com/microsoft/ALAppExtensions/issues/4173

Change ElementNameAndNameSpace and ElementValue to reference.

![image](https://user-images.githubusercontent.com/35260264/75425378-e00ec780-5942-11ea-84d7-fa9c4708763b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
