### ISSUE TITLE
HideValidationDialog in Events

### ISSUE THREAD

**Issue by michuanni** [microsoft/ALAppExtensions#6260]
Hi,

it will be nice to receive the value of HideValidationDialog variable e. g. in a global function like GetHideValidationDialog. This will help to skip some messages in events if this variable was set. 

Thanks in advance.

Yours Michael

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
