### ISSUE TITLE
[Request for External] Codeunit 12101 - Withholding - Contribution change scope value - SocSecLineFilter

### ISSUE THREAD

**Issue by Nyryus** [microsoft/ALAppExtensions#6264]
Please make external function "SocSecLineFilter" in the codeunit 12101 "Withholding - Contribution".

Localization: Italian

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
