### ISSUE TITLE
[Event Request] Codeunit 365 - Format Address - FormatAddressOnAfterGetCountryRec with LanguageCode parameter

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#6272]
Dear ALAppExtensions team,
Through this issue we would also like to request the event requested in #5994, _but_ with additional parameter `LanguageCode`, i.e.:
```pascal
FormatAddressOnAfterGetCountryRec(AddrArray,Name,Name2,Contact,Addr,Addr2,City,PostCode,County,CountryCode,Country,LanguageCode,Handled);
if Handled then
    exit;
```
We would like to have the same event publisher signature as described in #5994, but with the additional parameter `LanguageCode`.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
