### ISSUE TITLE
BE Localization latest Events missing

### ISSUE THREAD

**Issue by wbor-nvt** [microsoft/ALAppExtensions#6275]
Business Central 15.3 BE does not contain many events added to NAVBE Objects in the latest BC14 CU's. These are required to upgrade our extensions.
Some examples:
![image](https://user-images.githubusercontent.com/53901977/75539168-19fecd00-5a1a-11ea-898f-fd24e3543be4.png)
![image](https://user-images.githubusercontent.com/53901977/75539211-2e42ca00-5a1a-11ea-82ed-8292959c6766.png)
![image](https://user-images.githubusercontent.com/53901977/75539252-3c90e600-5a1a-11ea-8ded-abfd87b8484c.png)
![image](https://user-images.githubusercontent.com/53901977/75539655-e83a3600-5a1a-11ea-9c89-0d4d39ca4fbf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
