### ISSUE TITLE
[Enum Request] TAB256 VAT Statement Line - Amount Type

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#6278]
In Slovenian localization we need to extend the "Amount Type" filed in table 256 "VAT Statement Line".
Please convert this option to extendable enum.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by aobsgit** [comment]
@AlexanderYakunin How come this field is still an option instead of enum in 16.2?

**Comment by AlexanderYakunin** [comment]
We implement enum requests in next major version only. Therefore please expect it in 2020 Wave 2.

**Comment by aobsgit** [comment]
I was too excited I guess that this was closed just before the official release of 16 and would be included already :)
Thanks
