### ISSUE TITLE
[Event Request] Codeunit 431 - trigger OnRun

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#6279]
Hi!

We need an additional event before the ConfirmManagement.GetResponseOrDefault function call in the OnRun trigger in the IC Outbox Export codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/75547267-cba5fa00-5a2a-11ea-9a40-2e3e981e963d.png)

![image](https://user-images.githubusercontent.com/55734714/75547318-e6786e80-5a2a-11ea-8ce7-fd286bf9c505.png)

Thanks!

**Comment by andersnordmann** [comment]
Hi @AlexanderYakunin 
Do you know if this will be implemented, and when?
Best regards, Anders

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
