### ISSUE TITLE
[Function Expose] Access to UpdateShipToBillToGroupVisibility in page 42

### ISSUE THREAD

**Issue by ligoendeavor** [Microsoft/ALAppExtensions#628]
It seems like I can't access the field "Ship-to" in page 42, which source expression is a global variable (ShipToOptions), from an extension. I need to be able to change the selection in this field from my extension depending on the address fields that are changed from my extension. I think if I will be able to run UpdateShipToBillToGroupVisibility it will help to fix my issue. But that's a local function in the page that I can't access.

**Comment by darjoo** [comment]
Hi @ligoendeavor,
We have accepted your request and we usually include these types of changes in the next minor release, so look for it there!

**Comment by ligoendeavor** [comment]
Hi @darjoo,
Awesome, thank you!
