### ISSUE TITLE
[Event Request] Table 36 SalesHeader - OpenSalesOrderStatistics

### ISSUE THREAD

**Issue by ivohensgens** [microsoft/ALAppExtensions#6282]
Dear AlAppExtensions Team,

We would like to request the following event Publisher in table 36 - OpenSalesOrderStatistics (ofcourse without the prefix DIN)

![image](https://user-images.githubusercontent.com/44648582/75558424-1aab5980-5a42-11ea-8b11-ed3278dc69ff.png)

![image](https://user-images.githubusercontent.com/44648582/75558976-ee440d00-5a42-11ea-8ff1-37784cefe4f0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
