### ISSUE TITLE
[Event Request] Report 292/492 -  Copy Sales/Purchase Document

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#6283]
Related to issue #5495 and #3613.

For Report 492 "Copy Purchase document" add an event to LookupPostedReturn similar to the one in Copy Sales Document as done in #5495 
```
local procedure LookupPostedReturn()
    begin
    <<< NEW
    OnBeforeLookupPostedReturn(FromReturnShptHeader, PurchHeader);
    >>> NEW

    FromReturnShptHeader."No." := DocNo;
```
For Both Report 292/492 add an event to LookupPurchArchive and LookupSalesArchive after the Reset. This is the only Lookup function without a publisher.

```
    local procedure LookupSalesArchive()
    begin
        FromSalesHeaderArchive.Reset;
        <<< NEW
        OnBeforeLookupArchive(FromSalesHeaderArchive, SalesHeader);
        >>> NEW
```

```
    local procedure LookupPurchArchive()
    begin
        FromPurchHeaderArchive.Reset;
        <<< NEW
        OnBeforeLookupArchive(FromPurchHeaderArchive, PurchHeader);
        >>>
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
