### ISSUE TITLE
[Event Request] Table 37 Sales Line - UpdateItemChargeAssgnt

### ISSUE THREAD

**Issue by ivohensgens** [microsoft/ALAppExtensions#6284]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 37 – UpdateItemChargeAssgnt, ofcourse without the prefix DIN.

```
[External] UpdateItemChargeAssgnt()
// DINNL <<
DINOnBeforeUpdateItemChargeAssgnt(Rec,DINIsHandled);
IF DINIsHandled THEN
  EXIT; 
// DINNL >>
IF "Document Type" = "Document Type"::"Blanket Order" THEN
  EXIT;
```
```
LOCAL [IntegrationEvent] DINOnBeforeUpdateItemChargeAssgnt(SalesLine : Record "Sales Line";VAR IsHandeld : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
