### ISSUE TITLE
[Request for External/Coderefactoring] Page 6510 - "Item Tracking Lines"

### ISSUE THREAD

**Issue by SPinkow** [microsoft/ALAppExtensions#6286]
Hello,
I would like to create a pageextension of the Page 6510 "Item Tracking Line".
To access the temporary records of the global variables there are the functions GetVariables and SetVariables. The parameter "var SourceQuantityArray2: array[3] of Decimal" in the function GetVariables has only 3 dimensions. However, the global variable on page 6510 has the dimension 5, which means that there are constellations where the CopyArray command runs on a runtime error. The dimension of the parameter should be increased to 5.

![image](https://user-images.githubusercontent.com/45430404/75585798-37ac5080-5a73-11ea-9091-63b4dd3061d5.png)

As an even better alternative it would be useful to mark all global variables (or parts of them) as "protected var", so that they would be directly accessible from a page extension.

![image](https://user-images.githubusercontent.com/45430404/75586046-c7ea9580-5a73-11ea-9c45-c9067211ba57.png)

This would have the advantage that you could do everything without the functions GetVariables and SetVariables and you still have access to all necessary variables.

A consideration in one of the next cumulative updates would be great.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
