### ISSUE TITLE
[Reference Parameter Request] Codeunit 12 - Procedure OnBeforePostDtldCVLedgEntry

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#6287]
Hi,

could you change parameter **Unapply** reference to TRUE, please.

[IntegrationEvent(false, false)]
    local procedure OnBeforePostDtldCVLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var AccNo: Code[20]; **Unapply: Boolean**; var AdjAmount: array[4] of Decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
