### ISSUE TITLE
[Event Request] Codeunit 12 " Gen. Jnl.-Post Line" – Modify Event “OnBeforeCreateGLEntriesForTotalAmounts”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6288]
[Event Request] Codeunit 12 " Gen. Jnl.-Post Line" – Modify Event “OnBeforeCreateGLEntriesForTotalAmounts”

Could we please have the already existing publisher OnBeforeCreateGLEntriesForTotalAmounts in Codeunit 12 “Gen. Jnl.-Post Line” be extended?
The publisher offers a parameter “GLAccNo” which we would like to be a VAR-Parameter:

[IntegrationEvent(false, false)]
local procedure OnBeforeCreateGLEntriesForTotalAmounts(var InvoicePostBuffer: Record "Invoice Post. Buffer"; GenJournalLine: Record "Gen. Journal Line"; var GLAccNo: Code[20])
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
