### ISSUE TITLE
[Event Request] Codeunit 12 " Gen. Jnl.-Post Line" – Modify Event “OnPostDtldCVLedgEntryOnBeforeCreateGLEntryGainLoss”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6289]
[Event Request] Codeunit 12 " Gen. Jnl.-Post Line" – Modify Event “OnPostDtldCVLedgEntryOnBeforeCreateGLEntryGainLoss”

Could we please have the already existing publisher “OnPostDtldCVLedgEntryOnBeforeCreateGLEntryGainLoss” in Codeunit 12 “Gen. Jnl.-Post Line” be extended?
The publisher should implement a Handled Pattern. 
local procedure PostDtldCVLedgEntry(GenJnlLine: Record "Gen. Journal Line"; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; AccNo: Code[20]; var AdjAmount: array[4] of Decimal; Unapply: Boolean)
begin
    OnBeforePostDtldCVLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, AccNo, Unapply, AdjAmount);

    with DtldCVLedgEntryBuf do
        case "Entry Type" of
            "Entry Type"::"Initial Entry":
                ;
            "Entry Type"::Application:
                ;
            "Entry Type"::"Unrealized Loss",
            "Entry Type"::"Unrealized Gain",
            "Entry Type"::"Realized Loss",
            "Entry Type"::"Realized Gain":
                begin
                    // >>>>>>>> OLD CODE >>>>>>>>   
                    // OnPostDtldCVLedgEntryOnBeforeCreateGLEntryGainLoss(GenJnlLine, DtldCVLedgEntryBuf, Unapply, AccNo);
                    // CreateGLEntryGainLoss(GenJnlLine, AccNo, -"Amount (LCY)", "Currency Code" = AddCurrencyCode);
                    // >>>>>>>> NEW CODE >>>>>>>>   
                    IsHandled := false;
                    OnPostDtldCVLedgEntryOnBeforeCreateGLEntryGainLoss(GenJnlLine, DtldCVLedgEntryBuf, Unapply, AccNo,IsHandled);
                    
                    if not IsHandled then
                        CreateGLEntryGainLoss(GenJnlLine, AccNo, -"Amount (LCY)", "Currency Code" = AddCurrencyCode);
                    // <<<<<<<<  

[IntegrationEvent(false, false)]
local procedure OnPostDtldCVLedgEntryOnBeforeCreateGLEntryGainLoss(var GenJournalLine: Record "Gen. Journal Line"; DtldCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var Unapply: Boolean; var AccNo: Code[20];var IsHandled : Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
