### ISSUE TITLE
[Function Expose] Request multiple objects

### ISSUE THREAD

**Issue by picazin** [Microsoft/ALAppExtensions#629]
Hi

We need the following methods to be exposed. Most of them are from the Spanish Cartera module

Codeunit 7000000 - CarteraManagement
CheckFromRedrawnDoc
GetCombinedDimSetID
VendUnrealizedVAT2
GetDimSetIDFromCustLedgEntry
CustUnrealizedVAT2
GetDimSetIDFromCustPostDocBuffer
GetCurrFactorGainLoss
GetGainLoss

Codeunit 7000006 - Document-Post
PostSettlementForPostedPmtOrder
CheckPostingDate
PostSettlementForPostedBillGroup
FindDisctdAmt

Codeunit 12 - Gen. Jnl.-Post Line
VendFindVATSetup
CustFindVATSetup

Table 7000019 - FeeRange
CalcDiscExpensesAmt
CalcDiscInterestsAmt
CalcCollExpensesAmt
GetTotalDiscExpensesAmt
NoRegsDiscExpenses
GetDiscExpensesAmt
GetTotalUnriskFactExpensesAmt
NoRegUnriskFactExpenses
GetUnriskFactExpenses
GetTotalRiskFactExpensesAmt
NoRegRiskFactExpenses
GetRiskFactExpenses
GetTotalDiscInterestsAmt
NoRegsDiscInterests
GetDiscInterestsAmt
InitDiscExpenses
InitDiscInterests
InitCollExpenses
InitRiskFactExpenses
InitUnriskFactExpenses
GetTotalCollExpensesAmt
CalcRiskFactExpensesAmt
CalcUnriskFactExpensesAmt

Page 7000036 - Cartera Journal
SetJnlBatchName
AllowClosing

Thanks in advance!!

**Comment by IhorHandziuk** [comment]
Thank you for your request. All the functions above will be external in the next release.
