### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" – New Events “OnBeforePostUnrealVATByUnapply” and “OnAfterPostUnrealVATByUnapply”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6290]
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" – New Events “OnBeforePostUnrealVATByUnapply” and “OnAfterPostUnrealVATByUnapply”

Could we please have two new publisher OnBeforePostUnrealVATByUnapply and OnAfterPostUnrealVATByUnapply in Function PostUnrealVATByUnapply, Codeunit 12 " Gen. Jnl.-Post Line "?

local procedure PostUnrealVATByUnapply(GenJnlLine: Record "Gen. Journal Line"; VATPostingSetup: Record "VAT Posting Setup"; VATEntry: Record "VAT Entry"; NewVATEntry: Record "VAT Entry"): Integer
var
    VATEntry2: Record "VAT Entry";
    AmountAddCurr: Decimal;
    GLEntryNoFromVAT: Integer;
begin
    // >>>>>>>> 
    OnBeforePostUnrealVATByUnapply(GenJnlLine,VATPostingSetup,VATEntry,NewVATEntry);
    // <<<<<<<< 

    …

    // >>>>>>>>   
    OnAfterPostUnrealVATByUnapply(GenJnlLine,VATPostingSetup,VATEntry,NewVATEntry);
    // <<<<<<<< 
    exit(GLEntryNoFromVAT);
end;

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnBeforePostUnrealVATByUnapply (GenJnlLine: Record "Gen. Journal Line"; VATPostingSetup: Record "VAT Posting Setup"; VATEntry: Record "VAT Entry"; NewVATEntry: Record "VAT Entry")
begin
end;
// <<<<<<<<  

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnAfterPostUnrealVATByUnapply (GenJnlLine: Record "Gen. Journal Line"; VATPostingSetup: Record "VAT Posting Setup"; VATEntry: Record "VAT Entry"; NewVATEntry: Record "VAT Entry")
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
