### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" – New Event “OnGetSourceCode”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6291]
[Event Request] Codeunit 80 "Sales-Post" – New Event “OnGetSourceCode”

Could we please have an new publisher OnGetSource with Handled Pattern in Function CheckAndUpdate, Codeunit 80 "Sales-Post"?

…
LockTables(SalesHeader);
            
// >>>>>>>> 
OnGetSourceCode(SalesHeader,SrcCode,IsHandled);
if not IsHandled then begin
// <<<<<<<< 
    SourceCodeSetup.Get;
    SrcCode := SourceCodeSetup.Sales;
// >>>>>>>> 
end;
// <<<<<<<< 

InsertPostedHeaders(SalesHeader);
…

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnGetSourceCode (SalesHeader : Record “Sales Header”; var SrcCode : Code[10];var IsHandled : Boolean)
begin
end;
// <<<<<<<<

**Comment by StanPesotskiy** [comment]
There is already existing event where ScrCode can be re-assigned: `OnCheckAndUpdateOnAfterSetSourceCode(SalesHeader, SourceCodeSetup, SrcCode);`
