### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" – New Event “OnGetSourceCode”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6292]
[Event Request] Codeunit 90 "Purch.-Post" – New Event “OnGetSourceCode”

Could we please have an new publisher OnGetSource with Handled Pattern in Function CheckAndUpdate, Codeunit 90 "Purch.-Post"?

…
LockTables(PurchHeader);
            
// >>>>>>>> 
OnGetSourceCode(PurchHeader,SrcCode,IsHandled);
if not IsHandled then begin
// <<<<<<<< 
    SourceCodeSetup.Get;
    SrcCode := SourceCodeSetup.Purchases;
// >>>>>>>> 
end;
// <<<<<<<< 

InsertPostedHeaders(PurchHeader);
…

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnGetSourceCode (PurchHeader: Record “Purchase Header”; var SrcCode : Code[10];var IsHandled : Boolean)
begin
end;
// <<<<<<<<

**Comment by RomanZanizdra** [comment]
hi @ttaeufer . There is the event OnCheckAndUpdateOnAfterSetSourceCode(...) right after source code is get and with ScrCode as var parameter. So you can use it and re-assign ScrCode variable as you need it.
