### ISSUE TITLE
[Event Request] Codeunit 101 "Cust. Entry-SetAppl.ID" – New Event “OnCheckCustLedgEntryToApply”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6293]
[Event Request] Codeunit 101 "Cust. Entry-SetAppl.ID" – New Event “OnCheckCustLedgEntryToApply”

Could we please have a new publisher OnCheckCustLedgEntryToApply in Function SetApplId, Codeunit 101 "Cust. Entry-SetAppl.ID"?

if TempCustLedgEntry.FindSet then
    repeat
        CustLedgEntryToUpdate.Copy(TempCustLedgEntry);
        CustLedgEntryToUpdate.TestField(Open, true);
        // >>>>>>>>
        OnCheckCustLedgEntryToApply(CustLedgEntryToUpdate,ApplyingCustLedgEntry)
        // <<<<<<<<

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnCheckCustLedgEntryToApply (CustLedgEntryToApply: Record “Cust. Ledger Entry”; ApplyingCustLedgEntry: Record “Cust. Ledger Entry”)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
