### ISSUE TITLE
[Event Request] Codeunit 111 "Vend. Entry-SetAppl.ID" – New Event “OnCheckVendLedgEntryToApply”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6294]
[Event Request] Codeunit 111 "Vend. Entry-SetAppl.ID" – New Event “OnCheckVendLedgEntryToApply”

Could we please have a new publisher OnCheckVendLedgEntryToApply in Function SetApplId, Codeunit 111 "Vend. Entry-SetAppl.ID"?

if TempVendLedgEntry.FindSet then
    repeat
        VendLedgEntryToUpdate.Copy(TempVendLedgEntry);
        VendLedgEntryToUpdate.TestField(Open, true);
        // >>>>>>>>
        OnCheckVendLedgEntryToApply(VendLedgEntryToUpdate,ApplyingVendLedgEntry)
        // <<<<<<<<

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnCheckVendLedgEntryToApply (VendLedgEntryToApply: Record “Vendor Ledger Entry”; ApplyingVendLedgEntry: Record “Vendor Ledger Entry”)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
