### ISSUE TITLE
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" – New Event “OnBeforeUnApplyCheckDtldCustLedgEntry”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6295]
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" – New Event “OnBeforeUnApplyCheckDtldCustLedgEntry”

Could we please have a new publisher OnBeforeUnApplyCheckDtldCustLedgEntry in Function UnApplyCustomer, Codeunit 226 " CustEntry-Apply Posted Entries"?

local procedure UnApplyCustomer(DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry")
var
    UnapplyCustEntries: Page "Unapply Customer Entries";
begin
    with DtldCustLedgEntry do begin
        TestField("Entry Type", "Entry Type"::Application);
        TestField(Unapplied, false);
        // >>>>>>>> 
        OnBeforeUnApplyCheckDtldCustLedgEntry(DtldCustLedgEntry);
        // <<<<<<<<  

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnBeforeUnApplyCheckDtldCustLedgEntry (DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry")
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
