### ISSUE TITLE
[Event Request] Codeunit 227 "VendEntry-Apply Posted Entries" – New Event “OnBeforeUnApplyCheckDtldVendLedgEntry”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6296]
[Event Request] Codeunit 227 "VendEntry-Apply Posted Entries" – New Event “OnBeforeUnApplyCheckDtldVendLedgEntry”

Could we please have a new publisher OnBeforeUnApplyCheckDtldVendLedgEntry in Function UnApplyVendor, Codeunit 227 “VendEntry-Apply Posted Entries"?

local procedure UnApplyVendor(DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry")
var
    UnapplyVendEntries: Page "Unapply Vendor Entries";
begin
    with DtldVendLedgEntry do begin
        TestField("Entry Type", "Entry Type"::Application);
        TestField(Unapplied, false);
        // >>>>>>>> 
        OnBeforeUnApplyCheckDtldVendLedgEntry(DtldVendLedgEntry);
        // <<<<<<<<  

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnBeforeUnApplyCheckDtldVendLedgEntry (DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry")
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
