### ISSUE TITLE
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" – New Event “OnBeforePostUnapplyTestTransaction”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6297]
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" – New Event “OnBeforePostUnapplyTestTransaction”

Could we please have a new publisher OnBeforePostUnapplyTestTransaction with Handled Pattern in Function PostUnApplyCustomerCommit, Codeunit 226 " CustEntry-Apply Posted Entries"?

…
if DtldCustLedgEntry."Entry Type" = DtldCustLedgEntry."Entry Type"::Application then begin
    LastTransactionNo :=
      FindLastApplTransactionEntry(DtldCustLedgEntry."Cust. Ledger Entry No.");
    
    // >>>>>>>> 
    OnBeforePostUnapplyTestTransaction(DtldCustLedgEntry,LastTransactionNo,IsHandled);
    if not IsHandled then
    // <<<<<<<<  
        if (LastTransactionNo <> 0) and (LastTransactionNo <> DtldCustLedgEntry."Transaction No.") then
            Error(UnapplyAllPostedAfterThisEntryErr, DtldCustLedgEntry."Cust. Ledger Entry No.");
end;
…

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnBeforePostUnapplyTestTransaction (DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; LastTransactionNo:Integer; var IsHandled : Boolean)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
