### ISSUE TITLE
[Event Request] Codeunit 227 "VendEntry-Apply Posted Entries" – New Event “OnBeforePostUnapplyTestTransaction”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6298]
[Event Request] Codeunit 227 "VendEntry-Apply Posted Entries" – New Event “OnBeforePostUnapplyTestTransaction”

Could we please have a new publisher OnBeforePostUnapplyTestTransaction with Handled Pattern in Function PostUnApplyVendor, Codeunit 227 "VendEntry-Apply Posted Entries"?

…
if DtldVendLedgEntry."Entry Type" = DtldVendLedgEntry."Entry Type"::Application then begin
    LastTransactionNo :=
      FindLastApplTransactionEntry(DtldVendLedgEntry."Vendor Ledger Entry No.");
    // >>>>>>>> 
    OnBeforePostUnapplyTestTransaction(DtldVendLedgEntry,LastTransactionNo,IsHandled);
    if not IsHandled then
    // <<<<<<<<  
        if (LastTransactionNo <> 0) and (LastTransactionNo <> DtldVendLedgEntry."Transaction No.") then
            Error(UnapplyAllPostedAfterThisEntryErr, DtldVendLedgEntry."Vendor Ledger Entry No.");
end;
…

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnBeforePostUnapplyTestTransaction (DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; LastTransactionNo:Integer; var IsHandled : Boolean)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
