### ISSUE TITLE
[Event Request] Report 207 "Sales - Credit Memo" – New Event “OnBeforeGetDocumentCaption”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6299]
[Event Request] Report 207 "Sales - Credit Memo" – New Event “OnBeforeGetDocumentCaption”

Could we please have a new publisher OnBeforeGetDocumentCaption in Function GetDocumentNoLbl, Report 207 " Sales - Credit Memo ", as it already exists in Report 206 “Sales – Invoice”?

local procedure GetDocumentNoLbl(): Text
begin
    // >>>>>>>> 
    OnBeforeGetDocumentCaption("Sales Cr.Memo Header", DocCaption);
    if DocCaption <> '' then
        exit(DocCaption);
    // <<<<<<<<  
    if CompanyInfo."Country/Region Code" = 'DE' then
        exit(DESalesHeaderNoLbl);
    exit(SalesHeaderNoLbl);
end;

// >>>>>>>> 
[IntegrationEvent(false, false)]
local procedure OnBeforeGetDocumentCaption(SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var DocCaption: Text)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
