### ISSUE TITLE
[Event Request] Codeunit 87 Blanket Sales Order to Order - OnBeforeBlanketSalesOrderToOrder

### ISSUE THREAD

**Issue by fehebo** [Microsoft/ALAppExtensions#63]
Hi,
We need to implement additional business logic.
The following publisher is needed to be added:
Codeunit 87 Blanket Sales Order to Order - OnRun() trigger - 
[IntegrationEvent] OnBeforeBlanketSalesOrderToOrder(Rec : Record "Sales Header")
![codeunit87onbeforeblanketsalesordertoorder](https://user-images.githubusercontent.com/29135500/47088800-fe7d9280-d227-11e8-824e-b36d3dd5390e.png)

**Comment by AlexanderYakunin** [comment]
This event already exist for BC

**Comment by maksym-ch** [comment]
@fehebo 
The OnBeforeRun(Rec) event could be used for your purpose (25530 Build).
![126 c87onbeforeblanketsalesordertoorder](https://user-images.githubusercontent.com/44081671/48202509-cae8e080-e36d-11e8-9659-f664133039de.png)
