### ISSUE TITLE
Table 99000764 & 99000772

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/ALAppExtensions#630]
Hi,

In https://github.com/Microsoft/AL/issues/3045 I requested the function TestStatus in tables 99000764 & 99000772 should be global/external, and a check of IsTemporary at the beginning of those functions.
In the Current BC Version (CU2) I see that they are set to External, but there is no check of IsTemporary.
If we can´t get the check of IsTemporary, can we get an events with handler pattern instead so we can check for ourselves?

Thanks in advance

**Comment by IhorHandziuk** [comment]
Thank you for your request. Can you, please, explain in more details why it's desirable to skip execution of this function on temporary records?

**Comment by IhorHandziuk** [comment]
Thank you for explanation, you can expect the change in future update.
