### ISSUE TITLE
[Event Request] Report 595 "Adjust Exchange Rates" – New Event “OnAfterFindCustLedgerEntriesToAdjust”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6301]
[Event Request] Report 595 "Adjust Exchange Rates" – New Event “OnAfterFindCustLedgerEntriesToAdjust”

Could we please have a new publisher OnAfterFindCustLedgerEntriesToAdjust in Trigger Customer - OnAfterGetRecord, Report 595 "Adjust Exchange Rates"?

…
CustLedgerEntry.SetCurrentKey("Customer No.", Open);
CustLedgerEntry.SetRange("Customer No.", "No.");
CustLedgerEntry.SetRange(Open, true);
CustLedgerEntry.SetRange("Posting Date", 0D, EndDate);
if CustLedgerEntry.Find('-') then
    repeat
        TempCustLedgerEntry."Entry No." := CustLedgerEntry."Entry No.";
        if TempCustLedgerEntry.Insert then;
    until CustLedgerEntry.Next = 0;
CustLedgerEntry.Reset;
// >>>>>>>> 
OnAfterFindCustLedgerEntriesToAdjust(TempCustLedgerEntry);
// <<<<<<<<

// >>>>>>>> 
[IntegrationEvent(false, false)]
local procedure OnAfterFindCustLedgerEntriesToAdjust(var TempCustLedgerEntry Record "Cust. Ledger Entry" temporary)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
