### ISSUE TITLE
[Event Request] Report 595 "Adjust Exchange Rates" – New Event “OnAfterFindVendLedgerEntriesToAdjust”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6302]
[Event Request] Report 595 "Adjust Exchange Rates" – New Event “OnAfterFindVendLedgerEntriesToAdjust”

Could we please have a new publisher OnAfterFindVendLedgerEntriesToAdjust in Trigger Vendor - OnAfterGetRecord, Report 595 "Adjust Exchange Rates"?

…
VendorLedgerEntry.SetCurrentKey("Vendor No.", Open);
VendorLedgerEntry.SetRange("Vendor No.", "No.");
VendorLedgerEntry.SetRange(Open, true);
VendorLedgerEntry.SetRange("Posting Date", 0D, EndDate);
if VendorLedgerEntry.Find('-') then
    repeat
        TempVendorLedgerEntry."Entry No." := VendorLedgerEntry."Entry No.";
        if TempVendorLedgerEntry.Insert then;
    until VendorLedgerEntry.Next = 0;
VendorLedgerEntry.Reset;
// >>>>>>>> 
OnAfterFindVendLedgerEntriesToAdjust(TempVendorLedgerEntry);
// <<<<<<<<

// >>>>>>>> 
[IntegrationEvent(false, false)]
local procedure OnAfterFindVendLedgerEntriesToAdjust(var TempVendorLedgerEntry Record "Vendor Ledger Entry" temporary)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
