### ISSUE TITLE
[Reference Parameter Request] PurchPost.Codeunit.al - OnUpdateBlanketOrderLineOnBeforeCheck

### ISSUE THREAD

**Issue by TeusV** [microsoft/ALAppExtensions#6305]
In codeunit 90 "Purch.-Post", procedure procedure UpdateBlanketOrderLine(), five events are raised:
- OnBeforeUpdateBlanketOrderLine(PurchLine, Receive, Ship, Invoice, IsHandled)
- OnUpdateBlanketOrderLineOnBeforeInitOutstanding(BlanketOrderPurchLine, PurchLine, Ship, Receive, Invoice)
- OnUpdateBlanketOrderLineOnBeforeCheck(BlanketOrderPurchLine, PurchLine, IsHandled)
- OnBeforeBlanketOrderPurchLineModify(BlanketOrderPurchLine, PurchLine)
- OnAfterBlanketOrderPurchLineModify(BlanketOrderPurchLine, PurchLine, Ship, Receive, Invoice)

Since this procedure can be called from posting receipt or shipment and/or invoicing, three of these events have the parameters Ship, Receive, Invoice. They would make as much sense in the other two (OnUpdateBlanketOrderLineOnBeforeCheck being the one I'm particularly interested in).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
