### ISSUE TITLE
[Enum Request] RlshpMgtCommentLine.Table.al - Table Name

### ISSUE THREAD

**Issue by TeusV** [microsoft/ALAppExtensions#6306]
For our complaints module, we are integrating with relationship management. The only issue we're facing is that currently we can not store comment lines in table 5061 "Rlshp. Mgt. Comment Line", as we used to. If the "Table Name" field would be an enum, we could add our 'Complaint' to the current 'Contact,Campaign,To-do,Web Source,Sales Cycle,Sales Cycle Stage,Opportunity' options.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
