### ISSUE TITLE
[Request for External] Todo.Table.al - StartWizard()

### ISSUE THREAD

**Issue by TeusV** [microsoft/ALAppExtensions#6307]
In table 5080 "To-do", the StartWizard() is local. It is used by other procedures CreateTaskFromTask(), CreateTaskFromSalesHeader(), CreateTaskFromInteractLogEntry(). Because of that it is only to create a task using the wizard in these specific contexts. We would like to do this from other contexts as well. This would be possible if the StartWizard() procedure in this table were available externally (just like the StartWizard() in table 5077 "Segment Line").

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
