### ISSUE TITLE
[Request for External] Table 409 - SMTP Mail Setup

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#6309]
Hello,
unfortunately it is not possible to check if the password of the "SMTP Mail Setup" is filled or empty. This is because the function "HasPassword" is only enabled for OnPrem, just like the function "GetPassword". And I cannot directly check the IsolatedStorage from another app.
Therefore, can you please set one or both of the above functions to External?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
I am sorry, this issue was wrongly assigned and fell off the radar. My apologies. We will look into it asap.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
