### ISSUE TITLE
[Feature-Request]  GetSuspendStatusCheck procedure in T39-"Purchase Line"

### ISSUE THREAD

**Issue by KonstantinPap** [microsoft/ALAppExtensions#6310]
Can you please make the value of the global variable SuspendStatusCheck available with a getter in the Table 39-"Purchase Line"?

```
procedure GetSuspendStatusCheck(): Boolean
begin
    exit(StatusCheckSuspended);
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
