### ISSUE TITLE
[Event Request] Table 290 - UpdateLines

### ISSUE THREAD

**Issue by MegaLorm** [microsoft/ALAppExtensions#6311]
I need on table 290 on functions:

procedure **UpdateLines**

"VAT Calculation Type"::"Sales Tax":
begin
   "Amount Including VAT" := CalcLineAmount;
   if "Use Tax" then
       "VAT Base" := "Amount Including VAT"
   else
       "VAT Base" :=
           Round(
             SalesTaxCalculate.ReverseCalculateTax(
               TaxAreaCode, "Tax Group Code", TaxLiable, PostingDate, 
                 "Amount Including VAT", Quantity, CurrencyFactor),Currency.
                 "Amount Rounding Precision");
    OnAfterSalesTaxCalculateReverseCalculateTax(**TaxAreaCode, TaxLiable, PostingDate, CurrencyFactor**, Rec, Currency); _// I need the parameters **"TaxAreaCode", "TaxLiable", "PostingDate", "CurrencyFactor"**_
    "VAT Amount" := "VAT Difference" + "Amount Including VAT" - "VAT Base";
    if "VAT Base" = 0 then
       "VAT %" := 0
    else
        "VAT %" := Round(100 * "VAT Amount" / "VAT Base", 0.00001);
end;
end

[IntegrationEvent(false, false)]
local procedure OnAfterSalesTaxCalculateReverseCalculateTax(**TaxAreaCode: Code[20]; TaxLiable: Boolean; PostingDate: Date; CurrencyFactor: Decimal;** var VATAmountLine: Record "VAT Amount Line"; Currency: Record Currency)
begin
end;

----------------------------------------------------------------------------------------------

"VAT Calculation Type"::"Sales Tax":
    begin
        "VAT Base" := CalcLineAmount;
        if "Use Tax" then
            "VAT Amount" := 0
        else
            "VAT Amount" :=
                SalesTaxCalculate.CalculateTax(
                TaxAreaCode, "Tax Group Code", TaxLiable, PostingDate, "VAT Base", 
                 Quantity, CurrencyFactor);
        OnAfterSalesTaxCalculateCalculateTax(**TaxAreaCode, TaxLiable, PostingDate, CurrencyFactor**, Rec, Currency);_// I need the parameters **"TaxAreaCode", "TaxLiable", "PostingDate", "CurrencyFactor"**_
        if "VAT Base" = 0 then
            "VAT %" := 0
        else
            "VAT %" := Round(100 * "VAT Amount" / "VAT Base", 0.00001);
        "VAT Amount" :=
            "VAT Difference" +
            Round("VAT Amount", Currency."Amount Rounding Precision", 
             Currency.VATRoundingDirection);
        "Amount Including VAT" := "VAT Base" + "VAT Amount";
    end;
end;

[IntegrationEvent(false, false)]
local procedure OnAfterSalesTaxCalculateCalculateTax(**TaxAreaCode: Code[20];  TaxLiable: Boolean; PostingDate: Date; CurrencyFactor: Decimal;** var VATAmountLine: Record "VAT Amount Line"; Currency: Record Currency)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
