### ISSUE TITLE
[Event Request] Table 38 Purchase Header Function CreateDim

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6312]
Hello Team,

we need a new handle publisher in function CreateDim

---OLD

SourceCodeSetup.GET;
TableID[1] := Type1;
No[1] := No1;
TableID[2] := Type2;
No[2] := No2;
TableID[3] := Type3;

----NEW

handled := false;
OnBeforeCreateDim(handled)
if not handled then begin
   SourceCodeSetup.GET;
   TableID[1] := Type1;
   No[1] := No1;
   TableID[2] := Type2;
   No[2] := No2;
   TableID[3] := Type3;
...
...
....
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
