### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnValidatePostingDateOnBeforeValidateCurrencyCode

### ISSUE THREAD

**Issue by wbor-nvt** [microsoft/ALAppExtensions#6313]
We would like to ability to avoid triggering the Validate("Currency Code") (and recalculating Amount/ Amount (LCY)) during the OnValidate of the "Posting Date" on Table 81 - "Gen. Journal Line" when a parameter is set on the record. Could you provide an event to skip this line as shown below? 

        field(5; "Posting Date"; Date)
        {
            Caption = 'Posting Date';
            ClosingDates = true;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestField("Posting Date");
                Validate("Document Date", "Posting Date");
                IsHandled := false;
                OnValidatePostingDateOnBeforeValidateCurrencyCode(Rec, IsHandled);
                if not IsHandled then 
                    Validate("Currency Code");

                if ("Posting Date" <> xRec."Posting Date") and (Amount <> 0) then
                    PaymentToleranceMgt.PmtTolGenJnl(Rec);

                ValidateApplyRequirements(Rec);

                if JobTaskIsSet then begin
                    CreateTempJobJnlLine;
                    UpdatePricesFromJobJnlLine;
                end;

                if "Deferral Code" <> '' then
                    Validate("Deferral Code");
            end;
        }

    [IntegrationEvent(false,false)]
    local procedure OnValidatePostingDateOnBeforeValidateCurrencyCode(GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by StanPesotskiy** [comment]
Hi @wbor-nvt 
There are rare cases in W1 when GenJournalLine.Validate("Posting Date") used after "Amount" (for example, Standard Journal feature). Usually "Posting Date" is updated before "Amount". 

Can you share a scenario this event is needed for?

**Comment by wbor-nvt** [comment]
Hello @StanPesotskiy ,
We have an Action on the Page General Journal (and the BE Page Financial Journal) that creates Lines in the Batch based on some buffered data. The user still has to manually post these lines and can alter a bit of information, however the Amount / Amount (LCY) are not allowed to be changed for these lines. The user should be able to change the Posting Date without the Amount / Amount (LCY) being changed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
