### ISSUE TITLE
[Event Request] Codeunit 80 OnAfterInsertPostedHeaders

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6314]
Please add a new Event trigger OnAfterInsertPostedHeaders in codeunit 80 in procedure InsertPostedHeaders. This trigger exists already in codeunit 90:

LOCAL InsertPostedHeaders(VAR SalesHeader : Record "Sales Header")
OnBeforeInsertPostedHeaders(SalesHeader,TempWhseShptHeader,TempWhseRcptHeader);
IF PreviewMode THEN
  PostingPreviewEventHandler.PreventCommit;
WITH SalesHeader DO BEGIN
…

        GenJnlLineExtDocNo := SalesCrMemoHeader."External Document No.";
      END;
END;

//++++++++++++++++++++++++++++++++++++++++++++++++++
OnAfterInsertPostedHeaders(VAR SalesHeader,VAR SalesShptHeader,VAR SalesInvHeader,VAR SalesCrMemoHeader,VAR ReturnRcptHeader);
//--------------------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
