### ISSUE TITLE
[Event Request] Table 246 function UpdateReplenishmentSystem

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6319]
Hello Team,

we need a new handled publisher in this function:

--OLD
GetPlanningParameters.AtSKU(StockkeepingUnit,"No.","Variant Code","Location Code");
IF Subcontracting THEN
  StockkeepingUnit."Replenishment System" := StockkeepingUnit."Replenishment System"::"Prod. Order";
VALIDATE("Replenishment System",StockkeepingUnit."Replenishment System");

--NEW
GetPlanningParameters.AtSKU(StockkeepingUnit,"No.","Variant Code","Location Code");
IF Subcontracting THEN
  StockkeepingUnit."Replenishment System" := StockkeepingUnit."Replenishment System"::"Prod. Order";
handled := false;
onBeforeValidate(var Rec, StockkeepingUnit, handled);
if handled then
EXIT;
VALIDATE("Replenishment System",StockkeepingUnit."Replenishment System");

thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
