### ISSUE TITLE
[Event Request] Table 5409 OnInsert

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6320]
Hello Team,

we need a new handled Publisher in trigger OnInsert

---OLD
TESTFIELD("Routing No.");
IF Status = Status::Finished THEN

--NEW
handled := false;
onBeforeTestRoutingNo(var handled)
if not handled then
TESTFIELD("Routing No.");

thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
