### ISSUE TITLE
[Event Request] Table 5409 trigger OnInsert

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6321]
Hello Team,

we need a new handled publisher:

---OLD
IF "Next Operation No." = '' THEN
  SetNextOperations(Rec);

---NEW
handled := false;
onBeforeSetNextOperation(var handled);
if not handled then
IF "Next Operation No." = '' THEN
  SetNextOperations(Rec);

thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
