### ISSUE TITLE
[Event Request]Table 36 function CreateDim

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6322]
Hello Team,

we need a new handled Publisher at the begin of that function:

---OLD
SourceCodeSetup.GET;
TableID[1] := Type1;
No[1] := No1;
TableID[2] := Type2;

---NEW
handled := false
onBeforeCreateDim(var handled);
if handled then
EXIT;
SourceCodeSetup.GET;
TableID[1] := Type1;
No[1] := No1;
TableID[2] := Type2;

thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
