### ISSUE TITLE
[Event Request] Table 37 function UpdateVATOnLines

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6323]
Hello Team,

we need a new handled publisher to totally zero the function for one line.

--OLD
      IF NOT ZeroAmountLine(QtyType) THEN BEGIN
        DeferralAmount := GetDeferralAmount;
        VATAmountLine.GET("VAT Identifier","VAT Calculation Type","Tax Group Code",FALSE,"Line Amount" >= 0);
        IF VATAmountLine.Modified THEN BEGIN
.
.
.
END;

--NEW
      IF NOT ZeroAmountLine(QtyType) THEN BEGIN
         handled := false;
        onBeforeUpdateVAT(var handled)
        if not handled then begin

        DeferralAmount := GetDeferralAmount;
        VATAmountLine.GET("VAT Identifier","VAT Calculation Type","Tax Group Code",FALSE,"Line Amount" >= 0);
        IF VATAmountLine.Modified THEN BEGIN
.
.
END;  // end handled
END; //end Zeroamount

thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
