### ISSUE TITLE
[Event Request] Table 37 function CalcVATAmountLines

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6324]
Hello Team,

we need a new handled publisher to complete zero-out one line after the function
IF NOT ZeroAmountLine(QtyType) THEN BEGIN

--OLD
IF NOT ZeroAmountLine(QtyType) THEN BEGIN
.
.
.
END

--NEW
IF NOT ZeroAmountLine(QtyType) THEN BEGIN
handled := false;
onBeforeCalc(var Handled);
if NOT handled then begin
.
.
.
END;
END;

thanks

**Comment by StanPesotskiy** [comment]
Hi @ThomasBrendel 
Could you to use OnZeroAmountLine(Rec, QtyType, IsHandled) instead? Seems it does the same in a few more places.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
