### ISSUE TITLE
[Event Request] Table 951 function GetJobApproverID

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#6325]
Hello Team,

we need a new handled publisher:

-- OLD
Job.GET("Job No.");

Job.TESTFIELD("Person Responsible");
Resource.GET(Job."Person Responsible");
Resource.GET(TimeSheetHeader."Resource No.");
Resource.TESTFIELD("Time Sheet Owner User ID");
EXIT(Resource."Time Sheet Owner User ID");

--NEW
Job.GET("Job No.");
handled := false;
onBeforeGetJob(var handled);
if not handled then begin
Job.TESTFIELD("Person Responsible");
Resource.GET(Job."Person Responsible");
end;

thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
