### ISSUE TITLE
[Event Request] Report 493 Carry Out Action Msg. - Req. – OnPostReport

### ISSUE THREAD

**Issue by JordiCastell** [microsoft/ALAppExtensions#6327]
Hello everyone,

It would be nice to have the following event OnPostReport in Report 493 Carry Out Action Msg. - Req.

Kind regards,

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
