### ISSUE TITLE
[Event Request] Codeunit 7171 Sales Info-Pane Management – ConvertQty

### ISSUE THREAD

**Issue by Olli-GITHUB** [microsoft/ALAppExtensions#6329]
Dear ALAppExtensions Team,

we would like to request the following code extensions to be added in Codeunit 7171 Sales Info-Pane Management – ConvertQty.

Code Change as followed
```
LOCAL ConvertQty(Qty : Decimal;PerUoMQty : Decimal) : Decimal
//>> New Code
OnBeforeConvertQty(Qty,PerUoMQty,VAR ConvertedQty,VAR IsHandled);
IF IsHandled THEN
  EXIT(ConvertedQty);
//>> New Code

IF PerUoMQty = 0 THEN
  PerUoMQty := 1;
EXIT(ROUND(Qty / PerUoMQty,UOMMgt.QtyRndPrecision));
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
