### ISSUE TITLE
[Event Request] Codeunit 1393 "Cancel Issued Reminder": 

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#6333]
Hi,

we need a new Event in the Cancel Issued Reminder Codeunit :)

**Function**: CancelIssuedReminder
**Publisher**: OnCancelIssuedReminderOnBeforeProcessIssuedReminderLine
![grafik](https://user-images.githubusercontent.com/40355993/75883993-48b6e200-5e24-11ea-8965-709eba56d792.png)

**New Publisher:**
`[IntegrationEvent(false, false)]`
` local procedure OnCancelIssuedReminderOnBeforeProcessIssuedReminderLine(`
` var IssuedReminderLine: Record "Issued Reminder Line"; `
` var ReminderInterestAmount: Decimal; `
` var ReminderInterestVATAmount: Decimal; `
` DocumentNo: Code[20]; `
` PostingDate: Date; `
` var IsHandled: Boolean)`
`    begin`
`    end;`

Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
