### ISSUE TITLE
Codeunit 6500 - Item Tracking Management - change parameter of procedure CopyLotNoInformation 

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6336]
Hello AL-Team,
please change the NewLotNo parameter in function CopyLotNoInformation:

`procedure CopyLotNoInformation(LotNoInfo: Record "Lot No. Information"; NewLotNo: Code[50])`

to use the record instead of the New Lot No.:

`procedure CopyLotNoInformation(LotNoInfo: Record "Lot No. Information"; NewLotNoInfo: Record "Lot No. Information")
`

**Comment by AlexanderYakunin** [comment]
As CopyLotNoInformation is external function, we cannot simply make this change, it requires obsoleting of old procedure and implementation new one. Considering effect of this change and that you can easily do NewLotNoInfo.Get(NewLotNo), this request rejected.
