### ISSUE TITLE
[Event Request] Codeunit 6529 "Item Tracking Navigate Mgt." - OnBeforeInsertTempRecBuffer

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6339]
Hello AL-Team,

We would like to display some extra fields in the Item Tracking Navigate.
For this purpose it would be helpful to use the function **InsertBufferRec** in Codeunit 6529 "Item Tracking Navigate Mgt. To be called up with the Record Ref of the tracking record. 

As the InsertBufferRec is called from multiple code lines here is an example:

```
    local procedure InsertBufferRecFromItemLedgEntry()
    begin
        with ItemLedgEntry do
            // >> CHANGE (Example)
            // InsertBufferRec(RecRef, "Serial No.", "Lot No.", "Item No.", "Variant Code");
            TrackingRecRef.GetTable(ItemLedgEntry);
            InsertBufferRec(RecRef, TrackingRecRef);
            // << CHANGE (Example)
    end;

```
This would enable us to use the fields of the TrackingRecRef and add them to the TempRecordBuffer  before insert.

This requires a new Publisher Event in procedure InsertBufferRec:
```
    local procedure InsertBufferRec(RecRef: RecordRef; TrackingRecRef: RecordRef)
    […]
            // >> NEW
            OnBeforeInsertTempRecBuffer(TempRecordBuffer,TrackingRecRef);
            // << NEW
            TempRecordBuffer.Insert();
        end;
    end;

```
Publisher definition:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertTempRecBuffer(var TempRecordBuffer: Record "Record Buffer"; TrackingRecRef: RecordRef)

**Comment by AlexanderYakunin** [comment]
Can you be more specific and provide full solution you need? Are you going to use ItemLedgerEntry as tracking source or you also consider ReservationEntry?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
