### ISSUE TITLE
Integration is Turned on by default in Business Central

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#6341]
Integration is turned on by Default in Business central. 99% of installation would not require this integration feature, it locks and clogs up tables such as Integration Record.   We constantly have to perform the following subscription call to turn it off.  Can this be looked in.

 [EventSubscriber(ObjectType::Codeunit, Codeunit::"Graph Mgt - General Tools", 'OnGetISAPIEnabled', '', true, true)]
    local procedure OnIntegrationEnable(var Handled: Boolean; var IsAPIEnabled: Boolean)
    begin
        IsAPIEnabled := false;
        Handled := true;
    end;

**Comment by AlexanderYakunin** [comment]
We cannot disable integration by default as this is breaking change for many customers. You can disable this as you described above.
