### ISSUE TITLE
Slow Performance while loading Opening Inventory Balance

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#6342]
One of our retail customer  was having  slow posting while loading Opening inventory for their stores.  Analyzing the slowness, we have found the following code in function CalcRequiredQty in codeunit 23 was causing the issue.  Can you please amend the code see commend as //DOC K3-PERF in all the supportable and future versions of NAV and BC.

local procedure CalcRequiredQty(TempSKU: Record "Stockkeeping Unit" temporary; var ItemJnlLine: Record "Item Journal Line"): Decimal
    var
        SignFactor: Integer;
        QtyinItemJnlLine: Decimal;
    begin
        QtyinItemJnlLine := 0;
	ItemJnlLine.SETCURRENTKEY("Journal Template Name","Journal Batch Name","Item No.","Location Code","Variant Code"); //DOC K3-PERF
        ItemJnlLine.SetRange("Item No.", TempSKU."Item No.");
        ItemJnlLine.SetRange("Location Code", TempSKU."Location Code");
        ItemJnlLine.SetRange("Variant Code", TempSKU."Variant Code");
        ItemJnlLine.FindSet;
        repeat
            if (ItemJnlLine."Entry Type" in
                [ItemJnlLine."Entry Type"::Sale,
                 ItemJnlLine."Entry Type"::"Negative Adjmt.",
                 ItemJnlLine."Entry Type"::Consumption]) or
               (ItemJnlLine."Entry Type" = ItemJnlLine."Entry Type"::Transfer)
            then
                SignFactor := -1
            else
                SignFactor := 1;
            QtyinItemJnlLine += ItemJnlLine."Quantity (Base)" * SignFactor;
        until ItemJnlLine.Next = 0;
        exit(QtyinItemJnlLine);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
