### ISSUE TITLE
[Request for External] Set Function "CancelPostedInvoiceStartNewInvoice" in Codeunit 1303 "Correct Posted Sales Invoice" to external

### ISSUE THREAD

**Issue by TillZoell** [microsoft/ALAppExtensions#6343]
Hello Team, we would like to request function "CancelPostedInvoiceStartNewInvoice" in the Codeunit 1303 "Correct Posted Sales Invoice" to external to be made external. Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
