### ISSUE TITLE
[Event Request] Table 77 OnAfterGetEmailBodyCustomer

### ISSUE THREAD

**Issue by sharkphoenix** [microsoft/ALAppExtensions#6345]
Could you please add for the publisher the RecordVariant, IsHandled and make the CustEmailAddress and ServerEmailFilePath as VAR?

We want to add multiple CustomerAddresses and Change the Serveremailbody.
And we will change it in the dependens of the source of the record .
(Please do the same for the OnAfterGetEmailBodyVendor Publisher)

Example:
Function GetEmailBodyCustomText():
ServerEmailBodyFilePath := '';

OnBeforeGetEmailBodyCustomer;

IF CustEmailAddress = '' THEN
  CustEmailAddress := GetEmailAddressIgnoringLayout(ReportUsage,RecordVariant,CustNo);

IF NOT FindEmailBodyUsage(ReportUsage,CustNo,TempBodyReportSelections) THEN BEGIN
  IsHandled := FALSE;
  OnGetEmailBodyCustomerTextOnAfterNotFindEmailBodyUsage(
    ReportUsage,RecordVariant,CustNo,TempBodyReportSelections,IsHandled);

IF IsHandled THEN
  / EXIT(TRUE);
  EXIT(FALSE);
END;

CASE "Email Body Layout Type" OF
  "Email Body Layout Type"::"Custom Report Layout":
    ServerEmailBodyFilePath :=
      SaveReportAsHTML(TempBodyReportSelections."Report ID",RecordVariant,TempBodyReportSelections."Email Body Layout Code");
  "Email Body Layout Type"::"HTML Layout":
    ServerEmailBodyFilePath :=
      O365HTMLTemplMgt.CreateEmailBodyFromReportSelections(Rec,RecordVariant,CustEmailAddress,EmailBodyText);
END;

CustEmailAddress := GetEmailAddress(ReportUsage,RecordVariant,CustNo,TempBodyReportSelections);

// >>>
!!!CHANGE!!!
OnAfterGetEmailBodyCustomer(CustEmailAddress,ServerEmailBodyFilePath,RecordVariant,IsHandled);
If Not IsHandled then
  exit(false);
// <<<
EXIT(TRUE);

Publsiher: OnAfterGetEmailBodyCustomer(VAR CustEmailAddress,VAR ServerEmailBodyFilePath,RecordVariant,VAR IsHandled):

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
