### ISSUE TITLE
[Event Change] [local Functions] Codeunit 99000845 Reservation Management

### ISSUE THREAD

**Issue by SSZurmussen7112** [microsoft/ALAppExtensions#6346]
Hi Team,
I try to used the reservation technique for own tables and a lot of publishers were already created yet. But in my opinion it is still not useable for an extension. I am working on BC sandbox 16.0.11304.0-de.
Perhaps I try to use it in a wrong way. Do you have any kind of white paper which describes how to integrate an own table to the able to make reservations with it?

Otherwise here my requests:
The "local" must be deleted for the following functions to be available in own subscribers:

```
local procedure NarrowQtyToReserveDownToTrackedQuantity
local procedure MinAbs
local procedure Sign
local procedure CallCreateReservation

```
The already existing publisher **OnAfterAutoReserveOneLine** need one more parameter: **CalcReservEntry** (otherwise I have no information, for which item-item variant-location-combination a reservation should be done!)

old:

```
else
    OnAfterAutoReserveOneLine(
      ReservSummEntryNo, RemainingQtyToReserve, RemainingQtyToReserveBase, Description, AvailabilityDate, Search, NextStep);
```

`local procedure OnAfterAutoReserveOneLine(ReservSummEntryNo: Integer; var RemainingQtyToReserve: Decimal; var RemainingQtyToReserveBase: Decimal; Description: Text[100]; AvailabilityDate: Date; Search: Text[1]; NextStep: Integer)
`

new:

```
else
    OnAfterAutoReserveOneLine(
      ReservSummEntryNo, RemainingQtyToReserve, RemainingQtyToReserveBase, Description, AvailabilityDate, Search, NextStep, **CalcReservEntry**);
```

`local procedure OnAfterAutoReserveOneLine(ReservSummEntryNo: Integer; var RemainingQtyToReserve: Decimal; var RemainingQtyToReserveBase: Decimal; Description: Text[100]; AvailabilityDate: Date; Search: Text[1]; NextStep: Integer; **CalcReservEntry: Record "Reservation Entry"**)
`
Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
