### ISSUE TITLE
Unused Procedure SetDefaultType() in Sales Order Subform

### ISSUE THREAD

**Issue by markjinx** [microsoft/ALAppExtensions#6347]
The SetDefaultType procedure on the Sales Order Subform (PAG46) is defined but never called from the OnNewRecord trigger (like it is on the Purchase Order Subform.

*************************************************************
Sales Order Subform
*************************************************************
trigger OnNewRecord(BelowxRec: Boolean)
    begin
        InitType;

        // Default to Item for the first line and to previous line type for the others
        if ApplicationAreaMgmtFacade.IsFoundationEnabled then
            if xRec."Document No." = '' then
                Type := Type::Item;
        Clear(ShortcutDimCode);
        UpdateTypeText;
    end;

local procedure SetDefaultType()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetDefaultType(Rec, xRec, IsHandled);
        if not IsHandled then // Set default type Item
            if ApplicationAreaMgmtFacade.IsFoundationEnabled then
                if xRec."Document No." = '' then
                    Type := Type::Item;
    end;
*************************************************************
End Sales Order Subform
*************************************************************
*************************************************************
Purchase Order Subform
*************************************************************
trigger OnNewRecord(BelowxRec: Boolean)
    begin
        InitType;
        SetDefaultType();

        Clear(ShortcutDimCode);
        UpdateTypeText;
    end;

local procedure SetDefaultType()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetDefaultType(Rec, xRec, IsHandled);
        if not IsHandled then // Set default type Item
            if ApplicationAreaMgmtFacade.IsFoundationEnabled then
                if xRec."Document No." = '' then
                    Type := Type::Item;
    end;
*************************************************************
End Purchase Order Subform
*************************************************************

This pattern should be used on all purchase and sales subforms as I l know it is missing completely form the Sales Quote subform (PAG95) for example.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
