### ISSUE TITLE
[Event Change] Page 6550 Whse. Item Tracking Lines - OnBeforeItemTrackingLineInsert

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6348]
Hello Al Team,

please add WhseEntry as parameter to existing publisher OnBeforeItemTrackingLineInsert:

```
    procedure InsertItemTrackingLine(WhseWrkshLine: Record "Whse. Worksheet Line"; WhseEntry: Record 7312; QtyToEmpty: Decimal)

[...]
        if WhseItemTrackingLine2.FindLast then;
        "Entry No." := WhseItemTrackingLine2."Entry No." + 1;
        // >> UPDATE
        OnBeforeItemTrackingLineInsert(Rec, WhseWrkshLine**, WhseEntry**);
        // << UPDATE
        Insert();
    end;
```
Publisher signature:
local procedure OnBeforeItemTrackingLineInsert(var WhseItemTrackingLine: Record "Whse. Item Tracking Line"; WhseWorksheetLine: Record "Whse. Worksheet Line"; WhseEntry: Record "Warehouse Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
