### ISSUE TITLE
[Bug] page 6510 Item Tracking Lines - GetVariables

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6350]
Hello Al Team,

the GetVariable function in Page 6510 contains a little bug that is is preventing the use of the procedure:

The statement 
        CopyArray(SourceQuantityArray2, SourceQuantityArray, 1);

causes a run-time error because SourceQuantityArray is of dimension 5 and SourceQuantityArray2 is Dimension 3.

Please update the dimension value for "SourceQuantityArray2" in the parameters of the "GetVariables" function:

`procedure GetVariables(var TempTrackingSpecInsert2: Record "Tracking Specification" temporary; var TempTrackingSpecModify2: Record "Tracking Specification" temporary; var TempTrackingSpecDelete2: Record "Tracking Specification" temporary; var Item2: Record Item; var UndefinedQtyArray2: array[3] of Decimal; var SourceQuantityArray2: array[5] of Decimal; var CurrentSignFactor2: Integer; var InsertIsBlocked2: Boolean; var DeleteIsBlocked2: Boolean; var BlockCommit2: Boolean)
`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by IngoStender** [comment]
This issue still isn't fixed in preview version 16.4.14262.0, but in 17.0.14286.0. Can you confirm that the fix is really only available with the next major release?
