### ISSUE TITLE
[Event Request] WhseActivityPost.Codeunit – CU7324 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#6352]
We requested this on back in [3953](https://github.com/microsoft/ALAppExtensions/issues/3953)

we need Param SalesLine should be VAR declared

![image](https://user-images.githubusercontent.com/54017538/76082384-8abe6000-5fab-11ea-82f4-af400e55bdcf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
