### ISSUE TITLE
[Event Request] SalesLine.Table – TAB37 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#6353]
again this is one we have asked for in [4205](https://github.com/microsoft/ALAppExtensions/issues/4205) we are missing that IsHandled is VAR declared.

![image](https://user-images.githubusercontent.com/54017538/76082447-b93c3b00-5fab-11ea-8f74-c96dfa047216.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
