### ISSUE TITLE
[EventRequest] Table 39 “Puchase Line”, GetPurchHeader ()

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#6354]
the issue for us is that Rec, PurchHeader,Currency and IsHandled should be VAR declared (like on sales line tab37)

![image](https://user-images.githubusercontent.com/54017538/76082584-07513e80-5fac-11ea-9131-112938a4036d.png)

we have asked for this request back in [4207](https://github.com/microsoft/ALAppExtensions/issues/4207)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
