### ISSUE TITLE
[Event request] TransferLine.Table – TAB5741 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#6355]
Function GetTransferHeader should be set to Global/External, so it can be called from outside

![image](https://user-images.githubusercontent.com/54017538/76083780-a70fcc00-5fae-11ea-9dc3-276a745bd9f0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
