### ISSUE TITLE
[Event Request] Table 99000764 "Routing Line" - OnCertifiedRoutingVersionExistsOnBeforeCalculate, change paramter to var

### ISSUE THREAD

**Issue by IngoStender** [microsoft/ALAppExtensions#6356]
Please change the parameter RtngHeaderNo for the existing publisher OnCertifiedRoutingVersionExistsOnBeforeCalculate in table 99000764 "Routing Line" to var parameter.

```
Existing: local procedure OnCertifiedRoutingVersionExistsOnBeforeCalculate(var RtngVersionCode: Code[20]; RtngHeaderNo: Code[20]; CalculationDate: Date)
New:      local procedure OnCertifiedRoutingVersionExistsOnBeforeCalculate(var RtngVersionCode: Code[20]; var RtngHeaderNo: Code[20]; CalculationDate: Date)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
