### ISSUE TITLE
[Re-request]codeunit 7322 “Create Inventory Pick/Movement”, Code [Local]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#6357]
We have requested this one back in [3937](https://github.com/microsoft/ALAppExtensions/issues/3937)
But we are having the following issues:

This one can't be used as when is created. it can be that we are not finding it on the right version, but we haven't been able to locate this publisher.  Maybe it's okay in another build. 

the following image shows for a request based on version 15 
![image](https://user-images.githubusercontent.com/54017538/76191863-9a72ba00-61e0-11ea-8418-5f539019027f.png)

As it appears the Publisher was first created in top and did exit the whole function, which didn’t work as we also need the rest of the code in the function after creating the PickOrMove 

when requesting again in a a version 16 we get this 
![image](https://user-images.githubusercontent.com/54017538/76191907-b6765b80-61e0-11ea-9597-99f1f1dc111d.png)

This one we have a hard time understanding as AL does not except an option value outside the option field and the option field Source Document does not have option values outside the options already mentioned, so I have no chance to “grap” the last publisher (unless filed is ENUM).
However in our scenario the Source Document is set to “Prod. Consumption” so we need to exit before. 

Please let me know if this is sufficient, else leave a comment and I will answer quickly

**Comment by RomanZanizdra** [comment]
Hi @TjaTrimit .
For now code is looking like below. The question is why can't you process what you need in the event and leave IsHandled = false? In that case the flow is going to be as you requested.
...

        IsHandled := false;
        OnBeforeCreatePickOrMoveLines(WhseRequest, WhseActivHeader, LineCreated, IsHandled);
        if IsHandled then
            exit;

        GetSourceDocHeader();
        UpdateWhseActivHeader(WhseRequest);

        case WhseRequest."Source Document" of
...

**Comment by TjaTrimit** [comment]
We have found a workaround, so I will close this one.
