### ISSUE TITLE
Report layout orientation on preview

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#6358]
Hi,

we are facing issue with report layout orientation on preview. 
On version 16.x. reports with RDLC layout and landscape orientation renders now as portrait orientation on preview. Same reports works fine on 15.x.

Has there been any change from version 15.x to 16.x how does the preview work?

testing on version: 
W1 16.0 (Platform 15.0.39761.0 + Application 16.0.10855.0)

BR,
Bojan

**Comment by AlexanderYakunin** [comment]
This forum is for extensibility issues. You can report bug using following resouces:

•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
