### ISSUE TITLE
Codeunit 6500 Item Tracking Management - Function SplitWhseJnlLine - New Event Required

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#6361]
Hi

Can we please get a new event added to the SplitWhseJnlLine function in the Item Tracking Management Codeunit?

We have IP that calls the SetSourceFilter differently depending on whether a field is set or not.  If you can add an event after the Case Statement we can then override the filter setting if needed.  Example below:

        with TempWhseSplitTrackingSpec do begin
            Reset;
            case TempWhseJnlLine."Source Type" of
                DATABASE::"Item Journal Line",
              DATABASE::"Job Journal Line":
                    SetSourceFilter(
                      TempWhseJnlLine."Source Type", -1, TempWhseJnlLine."Journal Template Name", TempWhseJnlLine."Source Line No.", true);
                0: // Whse. journal line
                    SetSourceFilter(
                      DATABASE::"Warehouse Journal Line", -1, TempWhseJnlLine."Journal Batch Name", TempWhseJnlLine."Line No.", true);
                else
                    SetSourceFilter(
                      TempWhseJnlLine."Source Type", -1, TempWhseJnlLine."Source No.", TempWhseJnlLine."Source Line No.", true);
            end;
            SetFilter("Quantity actual Handled (Base)", '<>%1', 0);
            // NEW CODE STARTS
            OnSplitWhseJnlLineOnAfterSetFilter(var TempWhseSplitTrackingSpec, TempWhseJnlLine);
            // NEW CODE ENDS
            NonDistrQtyBase := TempWhseJnlLine."Qty. (Absolute, Base)";
            NonDistrCubage := TempWhseJnlLine.Cubage;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
