### ISSUE TITLE
T37 Sales Line - Procedure UpdateItemChargeAssgnt

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6364]
Please add the same Code in table 37 as in table 39 in procedure UpdateItemChargeAssgnt:

In Table 39 in Procedure UpdateItemChargeAssgnt is coded:

IF ItemChargeAssgntPurch.FINDSET(TRUE) AND (Quantity <> 0) THEN BEGIN
  GetPurchHeader;
  TotalAmtToAssign := CalcTotalAmtToAssign(TotalQtyToAssign);

in table 37 in the same procedure UpdateItemChargeAssgnt is coded:

IF ItemChargeAssgntSales.FINDSET(TRUE) THEN BEGIN
  GetSalesHeader;
  TotalAmtToAssign := CalcTotalAmtToAssign(TotalQtyToAssign);

This leads to division by Zero in our Extension at the Statement CaclTotalAmtToAssign, because quantity = 0, whereas purchase functions well:

LOCAL CalcTotalAmtToAssign(TotalQtyToAssign : Decimal) TotalAmtToAssign : Decimal
TotalAmtToAssign := CalcLineAmount * TotalQtyToAssign / Quantity;
IF SalesHeader."Prices Including VAT" THEN
  TotalAmtToAssign := TotalAmtToAssign / (1 + "VAT %" / 100) - "VAT Difference";

TotalAmtToAssign := ROUND(TotalAmtToAssign,Currency."Amount Rounding Precision");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
