### ISSUE TITLE
Table 37 and 39 OnDelete- and TestStatusOpen

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6365]
we cannot use SuspendStatusCheck to be valid in the OnDelete-Trigger, although the record is global. 

We want to delete lines even if the Status is "Released".

We cannot use the OnBeforeTestStatusOpen as mentioned in #4312 because this would apply to every Statuscheck, not only the specific check in the  OnDelete-Trigger.

both should be working for T37 and T39 in a way of:

if myconditionisvalid then begin
  rec.suspendstatuscheck(true);
  rec.delete(true);
end;

**Comment by RomanZanizdra** [comment]
Hi @GuntherGebauer . Sorry, but it's not fully clear where is the problem and what is not working. Below is simple extension I've tested. Sales line of "credit memo" type deleted from the released document.

codeunit 50101 SubCodeunit
{
    trigger OnRun()
    begin
    end;

    procedure DeleteSalesCrMemoLine()
    var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
    begin
        SalesHeader.SetRange("Document Type", SalesHeader."Document Type"::"Credit Memo");
        SalesHeader.SetRange(Status, SalesHeader.Status::Released);
        if SalesHeader.FindFirst() then begin
            SalesLine.SetRange("Document Type", SalesHeader."Document Type");
            SalesLine.SetRange("Document No.", SalesHeader."No.");
            if SalesLine.FindFirst() then begin
                SalesLine.SuspendStatusCheck(true);
                SalesLine.Delete(true);
                SalesLine.SuspendStatusCheck(false);
            end;
        end;
    end;
}

pageextension 50102 SalesCrMemoExt extends "Sales Credit Memos"
{
    layout
    {
        // Add changes to page layout here
    }

    actions
    {
        // Add changes to page actions here
        addlast(CreditMemo)
        {
            action(DeleteCrMemoLine)
            {
                Caption = 'DeleteCrMemoLine';

                trigger OnAction()
                var
                    SubCodeunit: Codeunit SubCodeunit;
                begin
                    SubCodeunit.DeleteSalesCrMemoLine();
                end;
            }
        }
    }
}

**Comment by GuntherGebauer** [comment]
@RomanZanizdra 👍 
Sorry, I have tested our Code as follows:

Codeunit 50101:

IF SalesLine.FIND('-') THEN BEGIN
    SalesLine.SuspendStatusCheck(TRUE);  <-- at this Point saleslines.Statuschecksuspended = true
    SalesLine.DELETEALL(TRUE); <-- at this Point saleslines.Statuschecksuspended = false
  END;
  
salesline.deletell(true) runs into

T37_OnBeforeDeleteEvent(VAR Rec : Record "Sales Line";RunTrigger : Boolean)

where already rec.Statuschecksuspended = false

and then after returning from this trigger into

Table 37
OnDelete()
  TestStatusOpen;


where now rec.Statuschecksuspended = false


and the lines could not be deleted

**Comment by RomanZanizdra** [comment]
Hi @GuntherGebauer . Yes, you will not be able to use DeleteAll in that case, I'm afraid there is nothing to do. Are there any problems that prevent you from using repeat..until and delete?

**Comment by GuntherGebauer** [comment]
Hi @RomanZanizdra 
Isn't that really bad Code with Findset, Repeat, delete(true) until next=0 ?
Why is deleteall(true) not triggered in the same way as delete(true) for a single record?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
