### ISSUE TITLE
[Event Request] Need an Event in service line - CheckifCanBeModified 

### ISSUE THREAD

**Issue by DeborahQin** [microsoft/ALAppExtensions#6368]
In OnModify trigger on Service Line table, it will check if allow modify or not when document type is service. If the service line has 'Contract No.' <> '' and 'Applied to service Entry' > 0, it is not allow to modify. But in real business, in some scenarios, the client need to modify the generated Description field. Now, it is not possible to do that. Suggest to add an Event in function CheckIfCanBeModified, So, it can be bypassed in same specific scenarioes.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
