### ISSUE TITLE
[Event Request] Codeunit 99000830 Create Reserv. Entry - OnAfterSetNewTrackingFromItemJnlLine

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6371]
Hallo Al Team,

please add a publisher in function SetNewTrackingFromitemJnlLine:

```
    procedure SetNewTrackingFromItemJnlLine(ItemJnlLine: Record "Item Journal Line")
    begin
        InsertReservEntry."New Serial No." := ItemJnlLine."Serial No.";
        InsertReservEntry."New Lot No." := ItemJnlLine."Lot No.";
        // >> NEW
        OnAfterSetNewTrackingFromItemJnlLine(InsertReservEntry,ItemJnlLine);
        // << NEW
    end;
```

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetNewTrackingFromItemJnlLine(var InsertReservEntry: Record "Reservation Entry"; ItemJnlLine: Record "Item Journal Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
