### ISSUE TITLE
[Event Request] Codeunit 99000830 Create Reserv. Entry - OnAfterSetNewTrackingFromNewWhseItemTrackingLine

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6372]
Hallo Al Team,

please add a publisher in function SetNewTrackingFromitemJnlLine:

```
        procedure SetNewTrackingFromNewWhseItemTrackingLine(WhseItemTrackingLine: Record "Whse. Item Tracking Line")
    begin
        InsertReservEntry."New Serial No." := WhseItemTrackingLine."New Serial No.";
        InsertReservEntry."New Lot No." := WhseItemTrackingLine."New Lot No.";
        // >> NEW
        OnAfterSetNewTrackingFromNewWhseItemTrackingLine(InsertReservEntry,WhseItemTrackingLine);
        // << NEW
    end;

```

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetNewTrackingFromNewWhseItemTrackingLine(var InsertReservEntry: Record "Reservation Entry"; WhseItemTrackingLine: Record "Whse. Item Tracking Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
