### ISSUE TITLE
[Event Request] Codeunit 5920 - ServItemManagement - Function DeleteServItemOnSaleCreditMemo- Event OnBeforeDeleteServItemOnSaleCreditMemo

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#6373]
Hi, we would need event OnBeforeDeleteServItemOnSaleCreditMemo in Codeunit 5920 - ServItemManagement in Function DeleteServItemOnSaleCreditMemo. We have logic to skip deleting Service Item in case of Trade-In

Implementation:
![image](https://user-images.githubusercontent.com/54843470/76404785-5c63ca80-6387-11ea-97c9-8008f2254993.png)

Publisher:

```
local procedure OnBeforeDeleteServItemOnSaleCreditMemo(SalesHeader:Record "Sales Header";var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
