### ISSUE TITLE
[Event Request] Codeunit 5812 "Calculate Standard Cost" - OnBeforeCalcRtngLineCost

### ISSUE THREAD

**Issue by IngoStender** [microsoft/ALAppExtensions#6374]
Please change the parameter RoutingLine for the existing publisher OnBeforeCalcRtngLineCost in codeunit 5812 "Calculate Standard Cost" to var parameter.

```
Existing:	local procedure OnBeforeCalcRtngLineCost(RoutingLine: Record "Routing Line"; MfgItemQtyBase: Decimal)
New:		local procedure OnBeforeCalcRtngLineCost(var RoutingLine: Record "Routing Line"; MfgItemQtyBase: Decimal)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
