### ISSUE TITLE
[Event Request] Codeunit 6620 OnCheckCopyFromxxx

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6375]
we Need an additional Parameters with the line in the OnCheckCopyFromxxx triggers because those trigger are executed inside the line loop e.g. for FromSalesShptLine, and we Need the data from thos lines in our Extension on this trigger:
Additional the ToSalesLine should be VAR parameter

1. old:
        OnCheckCopyFromSalesShptAvailOnAfterCheckItemAvailability(
          ToSalesHeader,ToSalesLine,FromSalesShptHeader,IncludeHeader);
1. New:
        OnCheckCopyFromSalesShptAvailOnAfterCheckItemAvailability(
          ToSalesHeader,VAR ToSalesLine,FromSalesShptHeader,FromSalesShptLine,IncludeHeader);

2. Old:
          OnCheckCopyFromSalesHeaderAvailOnAfterCheckItemAvailability(
            ToSalesHeader,ToSalesLine,FromSalesHeader,IncludeHeader);
2. New:
          OnCheckCopyFromSalesHeaderAvailOnAfterCheckItemAvailability(
            ToSalesHeader,VAR ToSalesLine,FromSalesHeader,FromSalesLine,IncludeHeader);

3. Old:
        OnCheckCopyFromSalesInvoiceAvailOnAfterCheckItemAvailability(
          ToSalesHeader,ToSalesLine,FromSalesInvHeader,IncludeHeader);
3. New:
        OnCheckCopyFromSalesInvoiceAvailOnAfterCheckItemAvailability(
          ToSalesHeader,VAR ToSalesLine,FromSalesInvHeader,FromSalesInvLine,IncludeHeader);

4. Old:
        OnCheckCopyFromSalesRetRcptAvailOnAfterCheckItemAvailability(
          ToSalesHeader,ToSalesLine,FromReturnRcptHeader,IncludeHeader);
4. New:
        OnCheckCopyFromSalesRetRcptAvailOnAfterCheckItemAvailability(
          ToSalesHeader,VAR ToSalesLine,FromReturnRcptHeader,FromReturnRcptLine,IncludeHeader);

5. Old:
        OnCheckCopyFromSalesCrMemoAvailOnAfterCheckItemAvailability(
          ToSalesHeader,ToSalesLine,FromSalesCrMemoHeader,IncludeHeader);

5. New:
        OnCheckCopyFromSalesCrMemoAvailOnAfterCheckItemAvailability(
          ToSalesHeader,VAR ToSalesLine,FromSalesCrMemoHeader,FromSalesCrMemoLine,IncludeHeader);

6. New Trigger OnCheckCopyFromSalesHeaderArchiveAvailOnAfterCheckItemAvailability
          IF FromSalesLineArchive.FINDSET THEN
            REPEAT
              IF FromSalesLineArchive.Quantity > 0 THEN BEGIN
                ToSalesLine."No." := FromSalesLineArchive."No.";
                ToSalesLine."Variant Code" := FromSalesLineArchive."Variant Code";
                ToSalesLine."Location Code" := FromSalesLineArchive."Location Code";
                ToSalesLine."Bin Code" := FromSalesLineArchive."Bin Code";
                ToSalesLine."Unit of Measure Code" := FromSalesLineArchive."Unit of Measure Code";
                ToSalesLine."Qty. per Unit of Measure" := FromSalesLineArchive."Qty. per Unit of Measure";
                ToSalesLine."Outstanding Quantity" := FromSalesLineArchive.Quantity;
                CheckItemAvailability(ToSalesHeader,ToSalesLine);
                OnCheckCopyFromSalesHeaderArchiveAvailOnAfterCheckItemAvailability(
                  ToSalesHeader,VAR ToSalesLine,FromSalesHeaderArchive,FromSalesLineArchive,IncludeHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
