### ISSUE TITLE
[Event Request] Multiple Events for Codeunit 365 

### ISSUE THREAD

**Issue by sharkphoenix** [microsoft/ALAppExtensions#6376]
Could you please add the following Events for the functions:
ServiceOrderSellto
ServContractSellto
ServiceInvBillTo
ServiceShptSellTo
ServiceShptBillTo
ServiceCrMemoBillTo
ServiceHeaderSellTo
ServiceHeaderBillTo
SalesHeaderArchBillTo
PurchHeaderBuyFromArch
PurchHeaderPayToArch

ServiceOrderSellTo:
[External] ServiceOrderSellto(VAR AddrArray : ARRAY [8] OF Text[100];ServHeader : Record "Service Header")

// >>>
OnBeforeServiceOrderSellTo(VAR AddrArray,VAR ServHeader,VAR isHandled)
If isHandled then
  exit;
// <<<
WITH ServHeader DO
  FormatAddr(
    AddrArray,Name,"Name 2","Contact Name",Address,"Address 2",
    City,"Post Code",County,"Country/Region Code");

ServContractSellto:
[External] ServContractSellto(VAR AddrArray : ARRAY [8] OF Text[100];ServContract : Record "Service Contract Header")
// >>>
OnBeforeServContractSellTo(VAR AddrArray,VAR ServContract, VAR isHandled)
if isHandled then
  exit;
// <<<
WITH ServContract DO BEGIN
  CALCFIELDS(Name,"Name 2",Address,"Address 2","Post Code",City,County,"Country/Region Code");
  FormatAddr(
    AddrArray,Name,"Name 2","Contact Name",Address,"Address 2",
    City,"Post Code",County,"Country/Region Code");
END;

ServiceInvBillTo:
[External] ServiceInvBillTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ServiceInvHeader : Record "Service Invoice Header")
// >>>
OnBeforeServiceInvBillTo(VAR AddrArray,VAR ServiceInvHeader,VAR IsHandled)
IF IsHandled then
  exit;
// <<<
WITH ServiceInvHeader DO
  FormatAddr(
    AddrArray,"Bill-to Name","Bill-to Name 2","Bill-to Contact","Bill-to Address","Bill-to Address 2",
    "Bill-to City","Bill-to Post Code","Bill-to County","Bill-to Country/Region Code");

ServiceShptSellTo:
[External] ServiceShptSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR ServiceShptHeader : Record "Service Shipment Header")
// >>>
OnBeforeServiceShptSellTo(VAR AddrArray,VAR ServiceShptHeader,VAR isHandled)
IF isHandled then
  exit;
// <<<
WITH ServiceShptHeader DO
  FormatAddr(
    AddrArray,Name,"Name 2","Contact Name",Address,"Address 2",
    City,"Post Code",County,"Country/Region Code");

ServiceShptBillTo:
[External] ServiceShptBillTo(VAR AddrArray : ARRAY [8] OF Text[100];ShipToAddr : ARRAY [8] OF Text[100];VAR ServiceShptHeader : Record "Service Shipment Header") : Boolean
// >>>
OnBeforeServiceShptBillTo(VAR AddrArray,VAR ShipToAddr,VAR ServiceShptHeader, VAR IsHandled)
IF isHandled then
  IF "Bill-to Customer No." <> "Customer No." THEN
    EXIT(TRUE);
  FOR i := 1 TO ARRAYLEN(AddrArray) DO
    IF ShipToAddr[i] <> AddrArray[i] THEN
      EXIT(TRUE);
// <<<
WITH ServiceShptHeader DO BEGIN
  FormatAddr(
    AddrArray,"Bill-to Name","Bill-to Name 2","Bill-to Contact","Bill-to Address","Bill-to Address 2",
    "Bill-to City","Bill-to Post Code","Bill-to County","Bill-to Country/Region Code");
  IF "Bill-to Customer No." <> "Customer No." THEN
    EXIT(TRUE);
  FOR i := 1 TO ARRAYLEN(AddrArray) DO
    IF ShipToAddr[i] <> AddrArray[i] THEN
      EXIT(TRUE);
END;
EXIT(FALSE);

----

Please do it for the following in the same style as before:
ServiceCrMemoBillTo
ServiceHeaderSellTo
ServiceHeaderBillTo
SalesHeaderArchBillTo
PurchHeaderBuyFromArch
PurchHeaderPayToArch

We need this subscriber to add different informations to the arrays :)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
