### ISSUE TITLE
New Event Subscription request

### ISSUE THREAD

**Issue by leachxpe** [microsoft/ALAppExtensions#6378]
I want to be able to update the parent reservation, during the posting process.  By adding Event subs OnbeforeupdateParentRecord, we could do this.

![CU](https://user-images.githubusercontent.com/50925206/76438656-2fc5a800-63b3-11ea-8bd3-b34d3b6202f5.gif)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
