### ISSUE TITLE
New Event Subscription - Sales-Quote to Order

### ISSUE THREAD

**Issue by leachxpe** [microsoft/ALAppExtensions#6379]
Hi, 
I want to update the salesquote before it gets archived with the order no. it was converted to.  Please could we have an event OnBefore the ArchivesalesDocument is called in CU86 
EXAMPLE
![image](https://user-images.githubusercontent.com/50925206/76509014-3271dd00-6447-11ea-9f50-d833de5a9a47.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
