### ISSUE TITLE
Table 5405 AdjustStartEndingDate

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#638]
Please make PROCEDURE AdjustStartEndingDate in table 5405 public and external

We need to call this function from outside without validating any of the starting/ending/duedate fields, because the Validation on thos fields disturb our calculation. We only want to adjust the date and datetimefields.

**Comment by darjoo** [comment]
Hi @GuntherGebauer, the function you're requesting has been made external recently. You should be able to view the changes on the preview build and it should be included in the next minor release.
