### ISSUE TITLE
[Event request] codeunit 5912 "ServLedgEntries-Post" - CreateCreditEntry

### ISSUE THREAD

**Issue by Ugniusi** [microsoft/ALAppExtensions#6380]
Hello,

In function "CreateCreditEntry" we need publisher:
![image](https://user-images.githubusercontent.com/62106013/76529037-6286a380-647a-11ea-9dec-e38ef98af638.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
