### ISSUE TITLE
[Event request] codeunit 5920 ServItemManagement - DeleteServItemOnSaleCreditMemo

### ISSUE THREAD

**Issue by Ugniusi** [microsoft/ALAppExtensions#6381]
Hello,

We need this handled event:
![image](https://user-images.githubusercontent.com/62106013/76529461-f9536000-647a-11ea-88b5-a30d8abea202.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
