### ISSUE TITLE
[Event Request] Page 6510 Item Tracking Lines - OnRegisterChangeOnBeforeResetExpirationDate

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#6382]
We need a new event function in Page 6510 "Item Tracking Lines", named OnRegisterChangeOnBeforeResetExpirationDate:

**LOCAL [IntegrationEvent] OnRegisterChangeOnBeforeResetExpirationDate(VAR OldTrackingSpecification : Record "Tracking Specification";VAR NewTrackingSpecification : Record "Tracking Specification";CurrentSignFactor : Integer;FormRunMode : ',Reclass,Combined Ship/Rcpt,Drop Shipment,Transfer';VAR IsHandled : Boolean)**

called from **RegisterChange** procedure, with a local variable of boolean type (IsHandled):

LOCAL RegisterChange(VAR OldTrackingSpecification : Record "Tracking Specification";VAR NewTrackingSpecification : Record "Tracking Specification";ChangeType : 'Insert,Modify,FullDelete,PartDelete,ModifyAll';ModifySharedFields : Boolean) OK : Boolean
OK := FALSE;

**//INIT-INSERT
OnRegisterChangeOnBeforeResetExpirationDate(OldTrackingSpecification,NewTrackingSpecification,CurrentSignFactor,FormRunMode,IsHandled);
IF NOT IsHandled THEN
//END-INSERT**
IF ((CurrentSignFactor * NewTrackingSpecification."Qty. to Handle") < 0) AND
   (FormRunMode <> FormRunMode::"Drop Shipment")
THEN BEGIN
  NewTrackingSpecification."Expiration Date" := 0D;
  OldTrackingSpecification."Expiration Date" := 0D;
END;

...
...
...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
