### ISSUE TITLE
[Enum Request] ReminderLine.Type and IssuedReminderLine.Type

### ISSUE THREAD

**Issue by ichladil** [microsoft/ALAppExtensions#6384]
[Enum Request] ReminderLine.Type and IssuedReminderLine.Type

Please change the Optionfield Type to Enum.

table 296 "Reminder Line": field "Type"
table 298 "Issued Reminder Line: field "Type"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
