### ISSUE TITLE
[Extensibility enhancement] codeunit 5920 ServItemManagement - CreateServItemOnSalesLineShpt

### ISSUE THREAD

**Issue by Ugniusi** [microsoft/ALAppExtensions#6385]
Function "CreateServItemOnSalesLineShpt" handled event can't be used, because there's missing global variable used and a some of "local" functions.

Handled publisher Old:
OnBeforeCreateServItemOnSalesLineShpt(SalesHeader, SalesLine, SalesShipmentLine, IsHandled);
Handled publisher New:
OnBeforeCreateServItemOnSalesLineShpt(SalesHeader, SalesLine, SalesShipmentLine, TempReservEntry, IsHandled);

Please make functions not local:
AmountToLCY()
CalcServiceItemWarrantyDates()
InsertServItemComponent()

![image](https://user-images.githubusercontent.com/62106013/76598147-e0928b00-650a-11ea-9166-a87a65714bcb.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
