### ISSUE TITLE
PEM to XML

### ISSUE THREAD

**Issue by GijsFranssens** [microsoft/ALAppExtensions#6387]
Hi,

I'm connecting to an API and I have to sign all my requests using a private key file (.PEM-file).

I would like to make use of the built-in function "Cryptography Management".SignData, but this requires a XmlString as "PrivateKeyFileInstr".
I have uploaded the PEM file into the database, but I need to convert this file to a XmlString to be able to use this function.

Example code:
`CryptographyMgt.SignData(SigningString, PrivateKeyFileInstr, HashAlgorithmType::SHA256, SignatureOutStream);`

Is this functionality already available in Business Central or will this be available in the near future?

What is the best option for me at this moment?

Thanks!

Kind regards,
Gijs

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Hi Gijs,
sorry, this issue somehow slipped through the cracks. My apologies.

I need to do a swift investigation to see what your options are. I am currently not aware of any functionality in the product, which could convert your certificate into a string - but that does not mean it does not exist ;-)

If it indeed doesn't exist, you always have the option to submit a pull request to update the cryptography module with the missing functionality, of course!

I will get back to you asap.

**Comment by JesperSchulz** [comment]
Hi Gijs,

I finally managed to track down a person, who knows a little something about your problem. He promised to take a look next week. Sorry that this issue dragged out for so long.

I wish you a great weekend.

Jesper

**Comment by GijsFranssens** [comment]
Hi Jesper,

Thank you, but I have already made some progress on this one..
You can use this function only with a key file in XML format.
So, you'll need to transform the .pem file to a .xml file and than you should be able to sign the data using Business Central Crypthography Mgt.

Kind regards,

**Comment by JesperSchulz** [comment]
Very glad to hear, that you made progress :-) If I may ask, how are you transforming the .pen file to an xml string? Are you planning on adding some functionality to enable that? Or did you find a suitable function to do so?

**Comment by GijsFranssens** [comment]
For this case we have used a separate c# project to transform the file, outside of Business Central.
We are not planning to include this functionality; if external parties require to sign the request with key files, I ask them to deliver us the key file in the correct format, in this case it has to be .xml.

**Comment by JesperSchulz** [comment]
Got it! Thanks :-) Should we close this issue then, or do you need any more help on this issue?
