### ISSUE TITLE
[Event Request] Table 37 Sales Line - OnValidateBinCodeOnBeforeFindBin

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6389]
Requesting 1 new event publisher on table 37 Sales Line

Event
LOCAL [IntegrationEvent] OnValidateBinCodeOnBeforeFindBin(VAR Rec : Record "Sales Line";VAR IsHandled : Boolean)

Code
**Bin Code - OnValidate()**
```
IF "Bin Code" <> '' THEN BEGIN
```
**>>> New Code**
 ```
  OnValidateBinCodeOnBeforeFindBin((Rec,IsHandled);
  IF NOT IsHandled THEN BEGIN
```
**<<< New Code End**
```
  IF NOT IsInbound AND ("Quantity (Base)" <> 0) AND ("Qty. to Asm. to Order (Base)" = 0) THEN
    WMSManagement.FindBinContent("Location Code","Bin Code","No.","Variant Code",'')
  ELSE
    WMSManagement.FindBin("Location Code","Bin Code",'');
END;
```
**>>> New Code**
```
END;
```
**<<< New Code End**

In our Solution we skip this code in Special Order scenarios.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
