### ISSUE TITLE
[EventRequest] Table 38 Purchase Header - OnValidateSellToCustomerNoOnBeforeCheckSpecialOrder

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6390]
Requesting 1 new event publisher on table 38 Purchase Header

Event
LOCAL [IntegrationEvent] OnValidateSellToCustomerNoOnBeforeCheckSpecialOrder(Rec   : Record "Purchase Header";VAR IsHandled : Boolean)

Code
**Sell-to Customer No. - OnValidate()**
```
IF ("Document Type" = "Document Type"::Order) AND
   (xRec."Sell-to Customer No." <> "Sell-to Customer No.")
THEN BEGIN
  PurchLine.SETRANGE("Document Type",PurchLine."Document Type"::Order);
  PurchLine.SETRANGE("Document No.","No.");
  PurchLine.SETFILTER("Sales Order Line No.",'<>0');
  IF NOT PurchLine.ISEMPTY THEN
    ERROR(
      YouCannotChangeFieldErr,
      FIELDCAPTION("Sell-to Customer No."));
```
**>>> New Code**
```
  OnValidateSellToCustomerNoOnBeforeCheckSpecialOrder(Rec,IsHandled);
  IF NOT IsHandled THEN BEGIN
```
**<<< New Code End**
```
    PurchLine.SETRANGE("Sales Order Line No.");
    PurchLine.SETFILTER("Special Order Sales Line No.",'<>0');
    IF NOT PurchLine.ISEMPTY THEN
      ERROR(
        YouCannotChangeFieldErr,
        FIELDCAPTION("Sell-to Customer No."));
```
**>>>New Code**
```
  END;
```
**<<<New Code End**
```
END;
```

In our Solution we need to skip this Check because we have scenarios where the Sell-to Customer No must be changed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
