### ISSUE TITLE
[EventRequest] Table 38 Purchase Header - OnValidateSellToCustomerNoOnBeforeValidateShipToCode

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6391]
Requesting 1 new event publisher on table 38 Purchase Header

Event
LOCAL [IntegrationEvent] OnValidateSellToCustomerNoOnBeforeValidateShipToCode(VAR Rec   : Record "Purchase Header";VAR IsHandled : Boolean)

Code
**Sell-to Customer No. - OnValidate()**
...
```
IF "Sell-to Customer No." = '' THEN
  UpdateLocationCode('')
```
**>>> New Code**
```
  OnValidateSellToCustomerNoOnBeforeValidateShipToCode(Rec,IsHandled)
  IF NOT IsHandled THEN
```
**<<< New Code End**
```
    VALIDATE("Ship-to Code",'');
```

In our Solution we need to skip the filling of Ship-to Code with Empty. We use Codes for DEFAULT, CUSTOM and use this for Correct processing of Warehouse Documents based on Address information.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
