### ISSUE TITLE
Page 43 Sales Invoice PostDocument function external access

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#6393]
In page 43 there is a function "PostDocument" which is only local.
 we would like to add a button "post&print" and would therefor need acces to this function.
 is it possible to make this function external?

**Comment by bartpattijn** [comment]
is this also possible on:
page 44 Sales Credit Memo
page 9302 Sales Credit Memos
page 9301 Sales Invoice List
page 9305 Sales Order List

**Comment by AlexanderYakunin** [comment]
I assume this is kind of request for additional functionality. I would suggest to publish this ask on Ideas site and we'd better implement it if request receive votes. If you timing allow to wait some time, please go this way. If not please implement your solution without dependency on this function, as it may be significantly updated in new release.
