### ISSUE TITLE
[EventRequest] Table 39 Purchase Line - OnValidateLocationCodeOnBeforeCheckSpecialOrder

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6394]
Requesting 1 new event publisher on table 39 Purchase Line

Event
LOCAL [IntegrationEvent] OnValidateLocationCodeOnBeforeCheckSpecialOrder(Rec   : Record "Purchase Line";CurrFieldNo : Integer;VAR IsHandled :   Boolean)

**Location Code - OnValidate()**
```
...
```
**>>>New Code**
```
OnValidateLocationCodeOnBeforeCheckSpecialOrder(Rec,CurrFieldNo,IsHandled)
IF NOT IsHandled THEN
```
**<<<New Code**
```
  IF "Special Order" THEN
      ERROR(
        Text001,
        FIELDCAPTION("Location Code"),"Special Order Sales No.");

...
```

In our Solution we only want to do this check when the Location Code is manually changed for Special orders, in all other cases we want to be able to skip this Check.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
