### ISSUE TITLE
[Enum Request] Table 5 "Finance Charge Terms" - Field 8 "Interest Calculation Method"

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6395]
Dear BaseApp team,

Please consider changing Option type to Enum in table 5 "Finance Charge Terms", field 8 "Interest Calculation Method".

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
