### ISSUE TITLE
[Enum Request] Table 81 "Gen. Journal Line" - Field 57 "Gen. Posting Type"

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6396]
Dear BaseApp team,

Please consider changing Option type to Enum in table 81 "Gen. Journal Line", field 57 "Gen. Posting Type".

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
