### ISSUE TITLE
[EventRequest] Table 39 Purchase Line - OnValidatePromisedReceiptDateOnBeforeFillDates

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6397]
Requesting a new event publisher on table 39 Purchase Line

Event
`LOCAL [IntegrationEvent] OnValidatePromisedReceiptDateOnBeforeFillDates(PurchLine : Record "Purchase Line",VAR IsHandled : Boolean)`

Code
## Promised Receipt Date - OnValidate()
**>>> New Code**
```
OnValidatePromisedReceiptDateOnBeforeFillDates(Rec, IsHandled)
IF NOT IsHandled THEN BEGIN
```
**<<< New Code**
```
  IF CurrFieldNo <> 0 THEN
    IF "Promised Receipt Date" <> 0D THEN
      VALIDATE("Planned Receipt Date","Promised Receipt Date")
    ELSE
      VALIDATE("Requested Receipt Date")
   ELSE
     VALIDATE("Planned Receipt Date","Promised Receipt Date");
```
**>>> New Code**
```
END;
```
**<<< New Code**

In our solution we want to be able to ***not*** execute this code.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
