### ISSUE TITLE
[EventRequest] Table 121 Purch. Rcpt Line - OnAfterDescriptionPurchaseLineInsert

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6398]
Requesting a new event publisher on table 121 Purch. Rcpt. Line

Event
`LOCAL [IntegrationEvent] OnAfterDescriptionPurchaseLineInsert(VAR PurchaseLine : Record "Purchase Line";PurchRcptLine : Record "Purch. Rcpt. Line";VAR NextLineNo : Integer)`

Code
## [External] InsertInvLineFromRcptLine(VAR PurchLine : Record "Purchase Line")
...

```
IF PurchLine."Receipt No." <> "Document No." THEN BEGIN
  PurchLine.INIT;
  PurchLine."Line No." := NextLineNo;
  PurchLine."Document Type" := TempPurchLine."Document Type";
  PurchLine."Document No." := TempPurchLine."Document No.";
  LanguageManagement.SetGlobalLanguageByCode(PurchInvHeader."Language Code");
  PurchLine.Description := STRSUBSTNO(Text000,"Document No.");
  LanguageManagement.RestoreGlobalLanguage;
  OnBeforeInsertInvLineFromRcptLineBeforeInsertTextLine(Rec,PurchLine,NextLineNo,Handled);
  IF NOT Handled THEN BEGIN
    PurchLine.INSERT;
```
**>>> New Code**
```
OnAfterDescriptionPurchaseLineInsert(PurchLine,Rec,NextLineNo);
```
**<<< New Code**
```
    NextLineNo := NextLineNo + 10000;
  END;
END;
```

Likewise in Table 111 Sales Shipment Line we need to add additional Text Lines with additional information, please add this Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
