### ISSUE TITLE
[EventRequest] Table 156 Resource - OnBeforeValidateTimeSheetApproverUserID

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6399]
Requesting a new event publisher on table 156 Resource

Event
`LOCAL [IntegrationEvent] OnBeforeValidateTimeSheetApproverUserID(VAR   Resource : Record Resource;VAR IsHandled : Boolean)`

**Code**

**Time Sheet Approver User ID - OnValidate()**
**>>>New Code**
```
OnBeforeValidateTimeSheetApproverUserID(Rec, IsHandled);
IF NOT IsHandled THEN
```
**<<< New Code End**
```
  IF "Time Sheet Approver User ID" <> xRec."Time Sheet Approver User ID" THEN
    IF ExistUnprocessedTimeSheets THEN
      ERROR(Text005,FIELDCAPTION("Time Sheet Approver User ID"));
```

In our solution we need to be able to switch between Time Sheet Approvers

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
