### ISSUE TITLE
[Event Request] Codeunit 1305 Sales-Quote to Invoice - OnBeforeSalesQuoteToInvoice

### ISSUE THREAD

**Issue by fehebo** [Microsoft/ALAppExtensions#64]
Hi,
We need to implement additional business logic.
The following publisher is needed to be added:
Codeunit 1305 Sales-Quote to Invoice - OnRun() trigger -
[IntegrationEvent] OnBeforeSalesQuoteToInvoice(Rec : Record "Sales Header")
![codeunit1305onbeforesalesquotetoinvoice](https://user-images.githubusercontent.com/29135500/47089925-78af1680-d22a-11e8-9fb1-a6d036ac3278.png)

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!
