### ISSUE TITLE
[EventRequest] Table 210 Job Journal Line - OnSelectItemEntryOnAfterSetItemLedgerEntryFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6401]
Requesting a new event publisher on table 210 Job Journal Line

Event
`LOCAL [IntegrationEvent] OnSelectItemEntryOnAfterSetItemLedgerEntryFilters(VAR ItemLedgEntry : Record "Item Ledger Entry", CurrentFieldNo : Integer)`

**Code**

**LOCAL SelectItemEntry(CurrentFieldNo : Integer)**
```
ItemLedgEntry.SETCURRENTKEY("Item No.",Open,"Variant Code");
ItemLedgEntry.SETRANGE("Item No.","No.");
ItemLedgEntry.SETRANGE(Correction,FALSE);

IF "Location Code" <> '' THEN
  ItemLedgEntry.SETRANGE("Location Code","Location Code");

IF CurrentFieldNo = FIELDNO("Applies-to Entry") THEN BEGIN
  ItemLedgEntry.SETRANGE(Positive,TRUE);
  ItemLedgEntry.SETRANGE(Open,TRUE);
END ELSE
  ItemLedgEntry.SETRANGE(Positive,FALSE);
```
**>>> New Code**
```
OnSelectItemEntryOnAfterSetItemLedgerEntryFilters(ItemLedgEntry, CurrentFieldNo)
```
**<<< New Code End**
```
IF PAGE.RUNMODAL(PAGE::"Item Ledger Entries",ItemLedgEntry) = ACTION::LookupOK THEN BEGIN
  JobJnlLine2 := Rec;
  IF CurrentFieldNo = FIELDNO("Applies-to Entry") THEN
    JobJnlLine2.VALIDATE("Applies-to Entry",ItemLedgEntry."Entry No.")
  ELSE
    JobJnlLine2.VALIDATE("Applies-from Entry",ItemLedgEntry."Entry No.");
  Rec := JobJnlLine2;
END;
```

In our Solution we need to set extra filters on Item Ledger Entries (Job Inventory related).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by fvanderhek** [comment]
Dear AL Team, I have changed this closed issue, i missed the current record in this code in the Requested Publisher. Do i need to make a new Issue or is editting the closed one enough to get the correct Publisher in a future release?
