### ISSUE TITLE
{EventRequest] Table 1003 Job Planning Line - OnBeforeHandleCostFactor

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6402]
Requesting a new event publisher on table 1003 Job Planning Line

Event
`LOCAL [IntegrationEvent] OnBeforeHandleCostFactor(VAR Rec : "Job Planning Line",xRec : Record : "Job Planning   Line", VAR IsHandled : Boolean)`

**Code**
#### LOCAL HandleCostFactor()
**>>> New Code**
```
OnBeforeHandleCostFactor(Rec, xRec, IsHandled)
IF IsHandled THEN
  EXIT;
```
**<<< New Code End
```
IF ("Cost Factor" <> 0) AND (("Unit Cost" <> xRec."Unit Cost") OR ("Cost Factor" <> xRec."Cost Factor")) THEN
  "Unit Price" := ROUND("Unit Cost" * "Cost Factor",UnitAmountRoundingPrecisionFCY)
ELSE
  IF (Item."Price/Profit Calculation" = Item."Price/Profit Calculation"::"Price=Cost+Profit") AND
     (Item."Profit %" < 100) AND
     ("Unit Cost" <> xRec."Unit Cost")
  THEN
    "Unit Price" := ROUND("Unit Cost" / (1 - Item."Profit %" / 100),UnitAmountRoundingPrecisionFCY);
```

In our Solution we also need to add more comparisons of fiels between Rec and xRec.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
