### ISSUE TITLE
[Event Request] Page 232 "Apply Customer Entries" - SetApplyingCustLedgEntry() - additional param on event

### ISSUE THREAD

**Issue by AndriiPochekailov** [microsoft/ALAppExtensions#6403]
Dear BaseApp team,

In page 232 "Apply Customer Entries", procedure SetApplyingCustLedgEntry(), event OnBeforeSetApplyingCustLedgEntry there are only two params: AppliedCustLedgEntry and GenJnlLine. However the following logic in that procedure also includes populating the ApplyingCustLedgEntry temporary record with values from Sales Header and Service Header:
![Page 232 - SetApplyingCustLedgEntry - 01](https://user-images.githubusercontent.com/42442951/76629639-469d0380-6547-11ea-9837-7c4d9aed541b.png)

It would be very useful if you add SalesHeader (non-var) to the parameters of the OnBeforeSetApplyingCustLedgEntry event:
![Page 232 - SetApplyingCustLedgEntry - 02](https://user-images.githubusercontent.com/42442951/76629696-5ddbf100-6547-11ea-827f-f006589a6356.png)

We'd like to set additional filters on the AppliedCustLedgEntry (which is later used in CalcApplnAmount) based on values from both GenJnlLine and SalesHeader which gives more control over entries that are allowed for application.

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
