### ISSUE TITLE
[EventRequest] Table 1003 Job Planning Line - OnBeforeControlUsageLink

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6404]
Requesting a new event publisher on table 1003 Job Planning Line

Event
`LOCAL [IntegrationEvent] OnBeforeControlUsageLink(Job : Record Job;VAR JobPlanningLine : Record "Job Planning Line";CurrFieldNo : Integer;VAR IsHandled : Boolean)`

**Code**
## LOCAL ControlUsageLink()
```
GetJob;
```
**>>>New Code**
```
OnBeforeControlUsageLink(Job, Rec, CurrFieldNo, IsHandled)
IF NOT IsHandled THEN BEGIN
```
**<<<New Code End**
```
IF Job."Apply Usage Link" THEN BEGIN
  IF "Schedule Line" THEN
    "Usage Link" := TRUE
  ELSE
    "Usage Link" := FALSE;
END ELSE BEGIN
  IF NOT "Schedule Line" THEN
    "Usage Link" := FALSE;
END;
```
**>>> New Code**
```
END;
```
**<<< New Code End**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
