### ISSUE TITLE
[EventRequest] Table 1013 Job Item Price - OnInsertOnBeforeTestItemNo

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6405]
Requesting a new event publisher on table 1013 Job Item Price

Event
`OnInsertOnBeforeTestItemNo(VAR Rec : Record "Job Item Price",VAR IsHandled : Boolean)`

**Code**
## OnInsert()
```
LOCKTABLE;
Job.GET("Job No.");
```
**>>> New Code**
```
OnInsertOnBeforeTestItemNo(Rec, IsHandled);
IF IsHandled THEN
  EXIT;
```
**<<< New Code End**
```
TESTFIELD("Item No.");
```

In our Solution we need to enter Prices for all items for a Job so the value of the field Item No. can also be empty.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
