### ISSUE TITLE
[EventRequest] Table 1014 Job G/L Account Price - OnInsertOnBeforeTestGLAccountNo

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6406]
Requesting a new event publisher on table 1014 Job G/L Account Price

Event
`OnInsertOnBeforeTestGLAccountNo(VAR Rec : Record "Job G/L Account Price",VAR IsHandled : Boolean)`

**Code**
## OnInsert()
```
LOCKTABLE;
Job.GET("Job No.");
```
**>>> New Code**
```
OnInsertOnBeforeTestGLAccountNo(Rec, IsHandled);
IF IsHandled THEN
  EXIT;
```
**<<< New Code End**
```
TESTFIELD("G/L Account No.");
```

In our Solution we need to enter Prices for all G/L Accounts for a Job so the value of the field G/L Account No. can also be empty.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
