### ISSUE TITLE
[EventRequest] 5077 Segment Line - OnStartWizardOnBeforeSendCreateOpportunityNotification

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6407]
Requesting a new event publisher on table 1013 Job Item Price

Event
`OnStartWizardOnBeforeSendCreateOpportunityNotification(VAR Rec : Record "Segment Line";VAR IsHandled : Boolean)`

**Code**

## [External] StartWizard()
```
OnBeforeStartWizard(Rec);

IF Campaign.GET("Campaign No.") THEN
  "Campaign Description" := Campaign.Description;
IF Opp.GET("Opportunity No.") THEN
  "Opportunity Description" := Opp.Description;
"Wizard Contact Name" := GetContactName;
"Wizard Step" := "Wizard Step"::"1";
"Interaction Successful" := TRUE;
VALIDATE(Date,WORKDATE);
"Time of Interaction" := DT2TIME(ROUNDDATETIME(CURRENTDATETIME + 1000,60000,'>'));
INSERT;

IF PAGE.RUNMODAL(PAGE::"Create Interaction",Rec,"Interaction Template Code") = ACTION::OK THEN;
IF "Wizard Step" = "Wizard Step"::"6" THEN
```
**>>> New Code**
```
  OnStartWizardOnBeforeSendCreateOpportunityNotification(Rec, IsHandled)
  IF IsHandled THEN
    EXIT;
```
**<<< New Code End**

We need the possibility to send a Opportunity Notification based on several conditions which is specified in the Segment Line by Custom Fields.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
