### ISSUE TITLE
[EventRequest] 5740 Transfer Header - OnBeforeCheckInvtPostingSetup

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6409]
Requesting a new event publisher on table 5740 Transfer Header

Event
`OnBeforeCheckInvtPostingSetup(Rec : Record "Transfer Header";VAR IsHandled : Boolean)`

**Code**
## [External] CheckInvtPostingSetup()
**>>> New Code**
```
OnBeforeCheckInvtPostingSetup(Rec, IsHandled);
IF IsHandled THEN
  EXIT;
```
**<<< New Code End**
```
InventoryPostingSetup.SETRANGE("Location Code", "Transfer-from Code");
InventoryPostingSetup.FINDFIRST;
InventoryPostingSetup.SETRANGE("Location Code", "Transfer-to Code");
InventoryPostingSetup.FINDFIRST;

```
We create a new Location for every new Job. This means we have to create lots of records in this table. Therefore we want to create Records without a location code so we can have a setup for all Job Locations.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
