### ISSUE TITLE
[Function Expose] Page 5907 Service Item Worksheet Subform - NoOnAfterValidate

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#641]
Can you please make function NoOnAfterValidate() in Page 5907 Service Item Worksheet Subform External/Global please?

**Comment by bleisibach** [comment]
Hi @darjoo 
In contrast to call a validate on a record/table, I don't know how to call a validate trigger of a page. Am I missing something?

**Comment by bleisibach** [comment]
Hi @darjoo, @JesperSchulz 
Sorry to nag on you here. But the workaround you proposed is not working on pages. Can you may be revaluate your decision?

**Comment by bleisibach** [comment]
Hi @darjoo 

Thank you for comming back on this. We fully understand that you hesitate to expose business logic on pages.

Your suggestion to build a copy of the function is ok, still we need to make a copy of  InsertExtendedText(Unconditionally : Boolean) also, because this function is not Global/External. Can you expose this function even it is on a page? If not, this is not a showstopper or us, we will find a way to copy the functionallity. Thank you.

**Comment by darjoo** [comment]
Hi @bleisibach,

The functions in `InsertExtendedText` are external, like `TransferExtendedText.ServCheckIfAnyExtText`, `TransferExtendedText.InsertServExtText` and `TransferExtendedText.MakeUpdate`. You would have no problems copying that function.

**Comment by bleisibach** [comment]
Hi @darjoo 
We will do so. Thank you!
