### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 134327 "ERM Purchase Order"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6410]
[Event Request]Application “Tests-ERM”, Codeunit 134327 "ERM Purchase Order"
![pic1](https://user-images.githubusercontent.com/45795262/76642449-84a02480-6553-11ea-95ae-346d8af3bd1f.png)

Could you please insert the OnTestInitialize Event at the beginning of the procedures:
•	PrintPurchOrderWithDropshipmentAndCommentLines
•	PrintPurchOrderWithoutDropshipmentLine

![pic2](https://user-images.githubusercontent.com/45795262/76642482-8ff35000-6553-11ea-954f-bb2142f8285f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
