### ISSUE TITLE
[EventRequest] TAB 472 - Job Queue Entry - OnAfterSetDefaultValues

### ISSUE THREAD

**Issue by codeunitone** [microsoft/ALAppExtensions#6414]
Hello,

I'm requesting a new publisher "OnAfterSetDefaultValues" at the end of Function "SetDefaultValues" of Table 472 Job Queue Entry.

![grafik](https://user-images.githubusercontent.com/15175001/76756442-f95aa500-6785-11ea-8741-6cf6c1d91c88.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
