### ISSUE TITLE
Assembly orders and calculation of availability for the reservation

### ISSUE THREAD

**Issue by jfpanarotto** [microsoft/ALAppExtensions#6417]
Hello,

On a sales order with an assembly order, **when the pick is registered and the warehouse shipment is not yet posted**, it seems that the quantity for the components of the assembly order is taken into account twice for the calculation of the unavailable quantities in the reservation function.

For example
We have a sales order with the item 10035E and an assembly order was created for this item with the component 10035. 
When the warehouse pick is registered, the quantity to use for the assembly is placed in the « To-assembly bin code » and is taken into account for the calculation of unavailable quantities (Qty. Allocated In Warehouse).
 
![image](https://user-images.githubusercontent.com/47528116/76764692-8fe29280-6795-11ea-86e5-965702aad2f1.png)
![image](https://user-images.githubusercontent.com/47528116/76764720-9a9d2780-6795-11ea-950f-4dab0c211639.png)
 

But the quantity is still reserved for the assembly order on ledger entries and is also taken into account for the calculation of unavailable quantities (Total Reserved Quantity).
 
![image](https://user-images.githubusercontent.com/47528116/76764759-aee12480-6795-11ea-98a9-124eb14fdb5f.png)
![image](https://user-images.githubusercontent.com/47528116/76764769-b4d70580-6795-11ea-8130-f75e7c413150.png)

 
Please, could you confirm us that there is a problem in the calculation of the availability for the reservation ?

**Comment by AlexanderYakunin** [comment]
Thank you for your feedback, but this channel is for extensibility and event requests. We cannot process functional of hotfix requests here. Can you please raise your concerns via regular support channel and create collaboration or hotfix request?
