### ISSUE TITLE
[EventRequest] Table 5741 TransferLine - OnSelectItemEntryOnAfterItemLedgerEntrySetFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6419]
Requesting a new event publisher on table 5741 Transfer Line

Event
`OnSelectItemEntryOnAfterItemLedgerEntrySetFilters(VAR ItemLedgEntry : Record "Item Ledger Entry";Rec : Record "Transfer Line")`

**Code**
## LOCAL SelectItemEntry(CurrentFieldNo : Integer)
```
ItemLedgEntry.SETRANGE("Item No.","Item No.");
IF "Transfer-from Code" <> '' THEN
  ItemLedgEntry.SETRANGE("Location Code","Transfer-from Code");
ItemLedgEntry.SETRANGE("Variant Code","Variant Code");

ItemLedgEntry.SETRANGE(Positive,TRUE);
ItemLedgEntry.SETRANGE(Open,TRUE);
```
**>>> New Code**
```
OnSelectItemEntryOnAfterItemLedgerEntrySetFilters(ItemLedgEntry, Rec)
```
**<<< New Code End**
```
IF PAGE.RUNMODAL(PAGE::"Item Ledger Entries",ItemLedgEntry) = ACTION::LookupOK THEN BEGIN
  TransferLine2 := Rec;
  TransferLine2.VALIDATE("Appl.-to Item Entry",ItemLedgEntry."Entry No.");
  CheckItemAvailable(CurrentFieldNo);
  Rec := TransferLine2;
END;
```
We need to set additional filters in this function. This way we can prevent users to select incorrect application Item Ledger Entries.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
