### ISSUE TITLE
[EventRequest] Codeunit 22 Item Jnl.-Post Line - OnBeforeCheckItemTracking

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6421]
Requesting a new event publisher on codeunit 22 Item Jnl.-Post Line

Event
`OnBeforeCheckItemTracking(ItemJnlLine : Record "Item Journal Line";VAR SNRequired : Boolean;VAR   LotRequired : Boolean)`

**Code**
## [External] CheckItemTracking()
**>>> New Code**
```
OnBeforeCheckItemTracking(ItemJnlLine, SNRequired, LotRequired)
```
**<<< New Code End**
```
IF SNRequired AND (ItemJnlLine."Serial No." = '') THEN
  ERROR(GetTextStringWithLineNo(SerialNoRequiredErr,ItemJnlLine."Item No.",ItemJnlLine."Line No."));
IF LotRequired AND (ItemJnlLine."Lot No." = '') THEN
  ERROR(GetTextStringWithLineNo(LotNoRequiredErr,ItemJnlLine."Item No.",ItemJnlLine."Line No."));
IF ItemJnlLine."Entry Type" = ItemJnlLine."Entry Type"::Transfer THEN BEGIN
  IF SNRequired THEN
    ItemJnlLine.TESTFIELD("New Serial No.");
  IF LotRequired THEN
    ItemJnlLine.TESTFIELD("New Lot No.");
END;

OnAfterCheckItemTracking(ItemJnlLine);
```

In our solution we also handle Bin to Bin transfers, so the Location Code and New Location Code is equal, Bin Code and New Bin Code are different. In the base app for this scenario we also need to handle Serial Nos and need to check this for this scenario.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
