### ISSUE TITLE
[Event Request] Table 130 OnBeforeCreatePurchHeaderFromIncomingDoc

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6422]
Similar to the existing Event OnBeforeCreateSalesHeaderFromIncomingDoc in table 130 we Need another new Event OnBeforeCreatePurchHeaderFromIncomingDoc in table 130 in procedure
CreatePurchDoc:

local procedure CreatePurchDoc(DocType: Option)
    var
        PurchHeader: Record "Purchase Header";
    begin
        TestReadyForProcessing;
        PurchHeader.SetRange("Incoming Document Entry No.", "Entry No.");
        if not PurchHeader.IsEmpty then begin
            ShowRecord;
            exit;
        end;
        PurchHeader.Reset();
        PurchHeader.Init();
        case DocType of
            DocumentType::Invoice:
                PurchHeader."Document Type" := PurchHeader."Document Type"::Invoice;
            DocumentType::"Credit Memo":
                PurchHeader."Document Type" := PurchHeader."Document Type"::"Credit Memo";
        end;
//++++++++++++++++++++++++++++++++
OnBeforeCreatePurchHeaderFromIncomingDoc(VAR PurchHeader);
//-------------------------------------------------------
        PurchHeader.Insert(true);
        OnAfterCreatePurchHeaderFromIncomingDoc(PurchHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
