### ISSUE TITLE
[EventRequest] Codeunit 365 Format Address - OnBeforeCompany

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6423]
Requesting a new event publisher on Codeunit 365 Format Address

Event
`OnBeforeCompany(VAR AddrArray : ARRAY [8] OF Text[100];VAR CompanyInfo : Record "Company   Information";VAR IsHandled : Boolean)`

**Code**
## [External] Company(VAR AddrArray : ARRAY [8] OF Text[100];VAR CompanyInfo : Record "Company Information")
**>>> New Code**
```
OnBeforeCompany(AddrArray, CompanyInfo, IsHandled);
IF IsHandled THEN 
  EXIT;
```
**<<< New Code End**
```
FormatAddr(
  AddrArray,Name,"Name 2",'',Address,"Address 2",
  City,"Post Code",County,'');
```

Similar to all other address functions we also need this one to handle Country/Region Code. We pass this field in our Solution.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
