### ISSUE TITLE
[EventRequest] Codeunit 950 Time Sheet Management - OnFillJobPlanningLineBufferOnBeforeInsert

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6424]
Requesting a new event publisher on Codeunit 950 Time Sheet Management

Event
`OnFillJobPlanningLineBufferOnBeforeInsert(JobPlanningLine : Record "Job Planning Line";VAR JobPlanningLineBuffer : TEMPORARY Record "Job Planning Line")`

**Code**
## LOCAL FillJobPlanningBuffer(TimeSheetHeader : Record "Time Sheet Header";VAR JobPlanningLineBuffer : TEMPORARY Record "Job Planning Line")
```
JobPlanningLine.SETRANGE(Type,JobPlanningLine.Type::Resource);
JobPlanningLine.SETRANGE("No.",TimeSheetHeader."Resource No.");
JobPlanningLine.SETRANGE("Planning Date",TimeSheetHeader."Starting Date",TimeSheetHeader."Ending Date");
IF JobPlanningLine.FINDSET THEN
  REPEAT
    SkipLine := FALSE;
    OnCheckInsertJobPlanningLine(JobPlanningLine,JobPlanningLineBuffer,SkipLine);
    IF NOT SkipLine THEN BEGIN
      JobPlanningLineBuffer.SETRANGE("Job No.",JobPlanningLine."Job No.");
      JobPlanningLineBuffer.SETRANGE("Job Task No.",JobPlanningLine."Job Task No.");
      IF JobPlanningLineBuffer.ISEMPTY THEN BEGIN
        JobPlanningLineBuffer."Job No." := JobPlanningLine."Job No.";
        JobPlanningLineBuffer."Job Task No." := JobPlanningLine."Job Task No.";
```
**>>> New Code**
```
        OnFillJobPlanningLineBufferOnBeforeInsert(JobPlanningLine, JobPlanningLineBuffer);
```
**<<< New Code End**
```
        JobPlanningLineBuffer.INSERT;
      END;
    END;
  UNTIL JobPlanningLine.NEXT = 0;
JobPlanningLineBuffer.RESET;
```

We need to set additional fields in the buffer which are going to be passed to Time Sheet Lines.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
