### ISSUE TITLE
[Event Request] Codeunit 353 Item Availability Forms Mgt – ShowItemAvailFromSalesLine

### ISSUE THREAD

**Issue by Olli-GITHUB** [microsoft/ALAppExtensions#6425]
Dear ALAppExtensions Team,

we would like to request again the following code extensions to be added in codeunit 353 Item Availability Forms Mgt – ShowItemAvailFromSalesLine.

[https://github.com/microsoft/ALAppExtensions/issues/4642](url)

Event has been shipped but without Handled Parameter.

Code Change as followed
```
WITH SalesLine DO BEGIN
  TESTFIELD(Type,Type::Item);
  TESTFIELD("No.");
  Item.RESET;
  Item.GET("No.");
  FilterItem(Item,"Location Code","Variant Code","Shipment Date");

// >> New Code
  //OnBeforeShowItemAvailFromSalesLine(Item,SalesLine);
  OnBeforeShowItemAvailFromSalesLine(Item,SalesLine,IsHandled);
  IF IsHandled THEN
    EXIT;
// >> New Code
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
