### ISSUE TITLE
[Event Request] Codeunit 353 Item Availability Forms Mgt – ShowItemAvailFromPurchLine

### ISSUE THREAD

**Issue by Olli-GITHUB** [microsoft/ALAppExtensions#6426]
Dear ALAppExtensions Team,

we would like to request again the following code extensions to be added in codeunit 353 Item Availability Forms Mgt – ShowItemAvailFromPurchLine.

[https://github.com/microsoft/ALAppExtensions/issues/4643](url)

Event has been shipped but without Handled Parameter.

Code Change as followed
```
WITH PurchLine DO BEGIN
  TESTFIELD(Type,Type::Item);
  TESTFIELD("No.");
  Item.RESET;
  Item.GET("No.");
  FilterItem(Item,"Location Code","Variant Code","Expected Receipt Date");

// >> New Code
  //OnBeforeShowItemAvailFromPurchLine(Item,PurchLine);
  OnBeforeShowItemAvailFromPurchLine(Item,PurchLine,IsHandled);
  IF IsHandled THEN
    EXIT;
// >> New Code
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
