### ISSUE TITLE
[Event Request] Codeunit 1373 Batch Posting Print Mgt. - PrintSalesDocument

### ISSUE THREAD

**Issue by Olli-GITHUB** [microsoft/ALAppExtensions#6427]
Dear ALAppExtensions Team,

we would like to request again the following code extensions to be added in codeunit 1373 Batch Posting Print Mgt. – PrintSalesDocument.

[https://github.com/microsoft/ALAppExtensions/issues/6261](url)
In this post we got the suggestion to use the event OnBeforePrintDocument. This event has no access to the sales header and the posting flags. 

Code change request as followed
```
WITH SalesHeader DO
  CASE "Document Type" OF
    "Document Type"::Order:
      BEGIN
        IF Ship THEN BEGIN
//>> New Code
          OnBeforePrintSalesShipmentHeader(SalesHeader,IsHandled);
          IF IsHandled THEN
            EXIT;
//>> New Code
          SalesShipmentHeader."No." := "Last Shipping No.";
          SalesShipmentHeader.SETRECFILTER;
          PrintDocument(ReportSelections.Usage::"S.Shipment",SalesShipmentHeader);
        END;
```

**Comment by StanPesotskiy** [comment]
For the event OnBeforePrintDocument  you can take SalesHeader from the parameter RecVar: Variant;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
