### ISSUE TITLE
[EventRequest] Codeunit 950 Time Sheet Management - OnAfterCreateTSPostingEntry

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6428]
Requesting a new event publisher on Codeunit 950 Time Sheet Management

Event
`OnAfterCreateTSPostingEntry(TimeSheetDetail : Record "Time Sheet Detail";TimeSheetPostingEntry : Record "Time Sheet Posting Entry")`

**Code**
## [External] CreateTSPostingEntry(TimeSheetDetail : Record "Time Sheet Detail";Qty : Decimal;PostingDate : Date;DocumentNo : Code[20];Desc : Text[100])
```
WITH TimeSheetPostingEntry DO BEGIN
  INIT;
  "Time Sheet No." := TimeSheetDetail."Time Sheet No.";
  "Time Sheet Line No." := TimeSheetDetail."Time Sheet Line No.";
  "Time Sheet Date" := TimeSheetDetail.Date;
  Quantity := Qty;
  "Document No." := DocumentNo;
  "Posting Date" := PostingDate;
  Description := Desc;
  INSERT;
END;
```
**>>> New Code**
```
OnAfterCreateTSPostingEntry(TimeSheetDetail, TimeSheetPostingEntry);
```
**<<< New Code End**

After this function we create Leave Entries and Over Time Pay Entries which are needed for payroll functionality. Can you please add this publisher ?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
