### ISSUE TITLE
[Enum Request]

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#643]
Hi,
we need some Enums, to extend Options:

Table 44 Sales Comment Line - Document Type
Table 97 Comment Line - Table Name
Table 279 Extended Text Header - Table Name
Table 280 Extended Text Line - Table Name
Table 7602 Customized Calendar Change - Source Type
Table 7603 Customized Calendar Entry - Source Type

Thanks in Advance

**Comment by JesperSchulz** [comment]
Just a quick heads-up: processing 6 enum requests is going to take a considerable amount of work. Expect this to take a while.

**Comment by LFlamme** [comment]
Hi, 
Thats not a problem for now, we will need them in approx 2-3 months.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
