### ISSUE TITLE
[EventRequest] Codeunit 1001 Job Post-Line - OnChangeGLNoOnBeforeGetCustomer

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6430]
Requesting a new event publisher on Codeunit 1001 Job Post-Line

Event
`OnChangeGLNoOnBeforeGetCustomer(VAR JobPlanningLine : Record "Job Planning Line";VAR Customer : Record Customer; VAR IsHandled :   Boolean)`

**Code**
## LOCAL ChangeGLNo(VAR JobPlanningLine : Record "Job Planning Line")
```
JT.GET(JobPlanningLine."Job No.",JobPlanningLine."Job Task No.");
Job.GET(JobPlanningLine."Job No.");
```
**>>> New Code**
```
OnChangeGLNoOnBeforeGetCustomer(JobPlanningLine, Cust, IsHandled);
IF NOT IsHandled THEN
```
**<<< New Code**
```
  Cust.GET(Job."Bill-to Customer No.");
IF JT."Job Posting Group" <> '' THEN
  JobPostingGr.GET(JT."Job Posting Group")
ELSE BEGIN
  Job.TESTFIELD("Job Posting Group");
  JobPostingGr.GET(Job."Job Posting Group");
END;
IF JobPostingGr."G/L Expense Acc. (Contract)" = '' THEN
  EXIT;
GLAcc.GET(JobPostingGr."G/L Expense Acc. (Contract)");
GLAcc.CheckGLAcc;
JobPlanningLine."No." := GLAcc."No.";
JobPlanningLine."Gen. Bus. Posting Group" := Cust."Gen. Bus. Posting Group";
JobPlanningLine."Gen. Prod. Posting Group" := GLAcc."Gen. Prod. Posting Group";
```

In Our Solution we have multiple Bill-to Customers linked to a Job. In this specific function the Bill-to Customer No. can be specified on the Job Planning line; When it's specified we need to get the Customer based on that field, when it is empty the normal code can be executed. Please add this Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
