### ISSUE TITLE
[EventRequest] Codeunit 1008 Job Calculate Statistics - OnCalcJobPlanAmountsAfterJobPlanningLineSetFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6432]
Requesting a new event publisher on Codeunit 1008 Job Calculate Statistics

Event
`OnCalcJobPlanAmountsAfterJobPlanningLineSetFilters(VAR JobPlanningLine : Record "Job Planning Line")`

**Code**
## LOCAL CalcJobPlanAmounts(PlanLineTypeParm : Option;TypeParm : Option)
```
JobPlanningLine2.COPY(JobPlanningLine);
WITH JobPlanningLine2 DO BEGIN
  SETRANGE("Schedule Line");
  SETRANGE("Contract Line");
  IF PlanLineTypeParm = PlanLineType::Schedule THEN
    SETRANGE("Schedule Line",TRUE)
  ELSE
    SETRANGE("Contract Line",TRUE);
  SETRANGE(Type,TypeParm);
```
**>>> New Code**
```
  OnCalcJobPlanAmountsAfterJobPlanningLineSetFilters(JobPlanningLine2);
```
**<<< New Code End**
```
  CALCSUMS("Total Cost (LCY)","Line Amount (LCY)","Total Cost","Line Amount");
  JobPlanAmounts[1 + PlanLineTypeParm,1 + TypeParm,1 + AmountType::TotalCostLCY] := "Total Cost (LCY)";
  JobPlanAmounts[1 + PlanLineTypeParm,1 + TypeParm,1 + AmountType::LineAmountLCY] := "Line Amount (LCY)";
  JobPlanAmounts[1 + PlanLineTypeParm,1 + TypeParm,1 + AmountType::TotalCost] := "Total Cost";
  JobPlanAmounts[1 + PlanLineTypeParm,1 + TypeParm,1 + AmountType::LineAmount] := "Line Amount";
END;
```

We need to set additional filters in this function. This way we can filter out the forecats planning Lines for example. Please add this Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
