### ISSUE TITLE
[EventRequest] Codeunit 1008 Job Calculate statistics - OnShowPlanningLineOnAfterJobPlanningLineSetFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6433]
Requesting a new event publisher on Codeunit 1008 Job Calculate Statistics

Event
`OnShowPlanningLineOnAfterJobPlanningLineSetFilters(VAR JobPlanningLine : Record "Job Planning Line")`

**Code**
## [External] ShowPlanningLine(JobType : ' ,Resource,Item,GL';Schedule : Boolean)
```
WITH JobPlanningLine DO BEGIN
  FILTERGROUP(2);
  SETRANGE("Contract Line");
  SETRANGE("Schedule Line");
  SETRANGE(Type);
  IF JobType > 0 THEN
    SETRANGE(Type,JobType - 1);
  IF Schedule THEN
    SETRANGE("Schedule Line",TRUE)
  ELSE
    SETRANGE("Contract Line",TRUE);
```
**>>> New Code**
```
  OnShowPlanningLineOnAfterJobPlanningLineSetFilters(JobPlanningLine);
```
**<<< New Code End**
```
  FILTERGROUP(0);
  PAGE.RUN(PAGE::"Job Planning Lines",JobPlanningLine);
END;
```

We need to set additional filters in this function to present the correct Job Planning Lines. In Function CalcJobPlanAmounts we have already requested a publisher to add the same filters we want also to set in this function. Please add this publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
