### ISSUE TITLE
Warning: Sales Price is obsolete

### ISSUE THREAD

**Issue by salgiza** [microsoft/ALAppExtensions#6435]
We see that BC16 implements Price Calculation using interfaces, which seems great but... does this mean that any changes to the price calculation must not use the Sales Price, Sales Line Discount tables at all? What is exactly the plan?

I mean: we have an app that alters how prices are calculated, so the interfaces are great. But to do so, we add a few new fields to the sales price/sales line discount tables... and those tables are also marked as obsolete. Are there any new tables that we should be aware of? We haven't seen anything mentioned in the Breakingchanges.md file.

**Comment by AlexanderYakunin** [comment]
We continue to support old pricing engine in parallel with new one. And this is not related to BreakingChanges file at all, this file is for System App only.

**Comment by salgiza** [comment]
Hi Alexander,

Sorry for the mistake. As this GitHub is used for new events requests for the whole BC app, regardless of the repository contents, I thought that breaking changes would also be for the whole BC.

Is there an equivalent to this system breakingchanges.md file for the base app? (Or are there any plans for that?)
