### ISSUE TITLE
Method IsInvoicing in “Env. Info Proxy” is Obsolete

### ISSUE THREAD

**Issue by salgiza** [microsoft/ALAppExtensions#6437]
One of our apps has a customized Sales Invoice report based on the standard one and in BC16 it is complaining that this method is now obsolete. The thing is, the only mention to this method in the Breakingchanges.md file is regarding the fact that we should use it instead of another method that is now obsolete.

![image](https://user-images.githubusercontent.com/6630306/76859850-5889e980-685a-11ea-827e-72f7f6aacd0c.png)

Is there anything we should know regarding this method? 😅

**Comment by AlexanderYakunin** [comment]
MS Invoicing is not supported anymore and we should not have IsInvoicing in BaseApp. You can safely remove this part of code from your extension.
