### ISSUE TITLE
[EventRequest] Codeunit 1313 Correct Posted Purch. Invoice - OnTestInventoryPostingSetupOnBeforeGetInventorySetup

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6439]
Requesting a new event publisher on Codeunit 1313 Correct Posted Purch. Invoice

Event
`OnTestInventoryPostingSetupOnBeforeGetInventorySetup((VAR PurchInvLine : Record "Purch. Inv. Line"; VAR InventoryPostingSetup : Record "Inventory Posting Setup";VAR IsHandled : Boolean)`

**Code**
## LOCAL TestInventoryPostingSetup(PurchInvLine : Record "Purch. Inv. Line")
```
WITH InventoryPostingSetup DO BEGIN
```
**>>> New Code**
```
  OnTestInventoryPostingSetupOnBeforeGetInventorySetup(PurchInvLine, InventoryPostingSetup, IsHandled);
  IF NOT IsHandled THEN
```
**<<< New Code End**
```
    GET(GET(PurchInvLine."Location Code",PurchInvLine."Posting Group");
  TESTFIELD("Inventory Account");
  TestGLAccount("Inventory Account",PurchInvLine);
END;
```

In Our Solution we create new Locations for evey Job (Job Locations). We do not want to create a new record for every new Job Location in combination to the Posting Group. Therefore we create just one per Posting group without a Location Code. So we can setup accounts per posting groups for all Job Locations with just one record. To Support this we need to get a Inventory Posting Setup Record with a blank Location Code in case of the current Location is a Job Location (Is specified by a field on the Location Table). Please add the Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
