### ISSUE TITLE
[EventRequest] Codeunit 1402 Cancel Posted Purch. Cr. Memo - OnTestInventoryPostingSetupOnBeforeGetInventorySetup

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6441]
Requesting a new event publisher on Codeunit 1402 Cancel Posted Purch. Cr, Memo

Event
`OnTestInventoryPostingSetupOnBeforeGetInventorySetup(VAR PurchCrMemoLine : Record "Purch. Cr. Memo Line"; VAR InventoryPostingSetup : Record "Inventory Posting Setup";VAR IsHandled : Boolean)`

**Code**
## LOCAL TestInventoryPostingSetup(PurchCrMemoLine : Record "Purch. Cr. Memo Line")
```
WITH InventoryPostingSetup DO BEGIN
```
**>>> New Code**
```
  OnTestInventoryPostingSetupOnBeforeGetInventorySetup(PurchCrMemoLine, InventoryPostingSetup, IsHandled);
  IF NOT IsHandled THEN
```
**<<< New Code End**
```
    GET(PurchCrMemoLine."Location Code",PurchCrMemoLine."Posting Group");
  TESTFIELD("Inventory Account");
  TestGLAccount("Inventory Account",PurchCrMemoLine);
END;
```

In Our Solution we create new Locations for evey Job (Job Locations). We do not want to create a new record for every new Job Location in combination to the Posting Group. Therefore we create just one per Posting group without a Location Code. So we can setup accounts per posting groups for all Job Locations with just one record. To Support this we need to get a Inventory Posting Setup Record with a blank Location Code in case of the current Location is a Job Location (Is specified by a field on the Location Table). Please add the Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
