### ISSUE TITLE
[EventRequest] Codeunit 5752 Get Source Doc. Outbound - OnCreateFromSalesOrderHideDialogOnAfterFindWhseRequest

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6442]
Requesting a new event publisher on Codeunit 5752 Get Source Doc. Outbound

Event
`OnCreateFromSalesOrderHideDialogOnAfterFindWhseRequest(SalesHeader : Record "Sales Header";WhseRqst : Record "Warehouse Request";VAR SkipWhseShipmentHeaderCreation : Boolean)`

**Code**
## [External] CreateFromSalesOrderHideDialog(SalesHeader : Record "Sales Header") : Boolean
```
IF NOT SalesHeader.IsApprovedForPosting THEN
  EXIT(FALSE);

FindWarehouseRequestForSalesOrder(WhseRqst,SalesHeader);

IF WhseRqst.ISEMPTY THEN
  EXIT(FALSE);
```
**>>> New Code**
```
OnCreateFromSalesOrderHideDialogOnAfterFindWhseRequest(SalesHeader, WhseRqst, SkipWhseShipmentHeaderCreation)
IF SkipWhseShipmentHeaderCreation THEN 
  EXIT(FALSE);
```
**<<< New Code End**
```
CreateWhseShipmentHeaderFromWhseRequest(WhseRqst);
EXIT(TRUE);
```

In Our Solution we create Warehouse Shipment Header per Ship-to Code, so that means we bundle Orders to open Warehouse Shipment Headers for processing. Therefore we need to have the possibility to determine when to create a new Warehouse Shipment Header and when not to. Please add the requested publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
