### ISSUE TITLE
[Function Expose] Table 5405 "Production Order" - "DeleteFnshdProdOrderRelations" and "DeleteRelations"

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6443]
Hello Al Team,

please expose the functions "DeleteFnshdProdOrderRelations" and "DeleteRelations" of Table 5405 "Production Order" to be used in a TableExtension as well.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
