### ISSUE TITLE
[Extensibility Enhancement] Codeunit 6620 Copy Document Mgt. and the use of Global variable CopyJobData

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6448]
Requesting an additional parameter CopyJobData (By Reference) to several existing Publishers in Codeunit 6620 Copy Document Mgt.

We would like the following Publishers to be expanded:

**Existing Signature:**
`LOCAL [IntegrationEvent] OnBeforeCopySalesDocForCrMemoCancelling(VAR ToSalesHeader : Record "Sales Header";FromDocNo : Code[20])`

**New Signature:**
`LOCAL [IntegrationEvent] OnBeforeCopySalesDocForCrMemoCancelling(VAR ToSalesHeader : Record "Sales Header";FromDocNo : Code[20], VAR CopyJobData : Boolean)`

**Existing Signature:**
`LOCAL [IntegrationEvent] OnCopySalesDocOnBeforeTransferPostedInvoiceFields(VAR ToSalesHeader : Record "Sales Header";SalesInvoiceHeader : Record "Sales Invoice Header")`

**New Signature:**
`LOCAL [IntegrationEvent] OnCopySalesDocOnBeforeTransferPostedInvoiceFields(VAR ToSalesHeader : Record "Sales Header";SalesInvoiceHeader : Record "Sales Invoice Header", VAR CopyJobData : Boolean)`

**Existing Signature:**
`LOCAL [IntegrationEvent] OnBeforeCopySalesInvLines(VAR TempDocSalesLine : TEMPORARY Record "Sales Line";VAR ToSalesHeader : Record "Sales Header";VAR FromSalesInvLine : Record "Sales Invoice Line")`

**New Signature:**
`LOCAL [IntegrationEvent] OnBeforeCopySalesInvLines(VAR TempDocSalesLine : TEMPORARY Record "Sales Line";VAR ToSalesHeader : Record "Sales Header";VAR FromSalesInvLine : Record "Sales Invoice Line", VAR CopyJobData : Boolean)`

**Existing Signature:**
`LOCAL [IntegrationEvent] OnBeforeCopySalesCrMemoLinesToDoc(VAR TempDocSalesLine : TEMPORARY Record "Sales Line";VAR ToSalesHeader : Record "Sales Header";VAR FromSalesCrMemoLine : Record "Sales Cr.Memo Line")`

**New Signature:**
`LOCAL [IntegrationEvent] OnBeforeCopySalesCrMemoLinesToDoc(VAR TempDocSalesLine : TEMPORARY Record "Sales Line";VAR ToSalesHeader : Record "Sales Header";VAR FromSalesCrMemoLine : Record "Sales Cr.Memo Line", VAR CopyJobData : Boolean)`

**Existing Signature:**
`LOCAL [IntegrationEvent] OnAfterTransferFieldsFromCrMemoToInv(VAR ToSalesHeader : Record "Sales Header";FromSalesCrMemoHeader : Record "Sales Cr.Memo Header")`

**New Signature:**
`LOCAL [IntegrationEvent] OnAfterTransferFieldsFromCrMemoToInv(VAR ToSalesHeader : Record "Sales Header";FromSalesCrMemoHeader : Record "Sales Cr.Memo Header", VAR CopyJobData : Boolean)`

Our Solution is mainly build around Jobs Management and so we need to copy specified Job information when users are copying Documents. Please expand the above mentioned Publishers.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
