### ISSUE TITLE
[Function Expose] Codeunit 1002 Job Create-Invoice - CreateSalesLine

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/ALAppExtensions#645]
Can you please make function CreateSalesLine in codeunit 1002 Job Create-Invoice External/Global please?

**Comment by mazhelez** [comment]
Hey @bleisibach and happy new year. Let it be a lovely one!

Regarding your request, can please elaborate a little bit more on why you want that particular function exposed?

**Comment by mazhelez** [comment]
Thank for your response!

The team will look into it.

**Comment by JesperSchulz** [comment]
Closing issue as it is a duplicate.
