### ISSUE TITLE
[Event Request] Codeunit 7000 SalesPrice Calc Mgt. - OnBeforeCopyJobItemPriceToJobJnlLine

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6451]
Requesting a new Event publisher on Codeunit 7000 Sales Price Calc Mgt.

Event
`OnBeforeCopyJobItemPriceToJobJnlLine(VAR JobJnlLine : Record "Job Journal Line";JobItemPrice : Record "Job Item Price"; VAR IsHandled : Boolean)`

**Code**
## LOCAL CopyJobItemPriceToJobJnlLine(VAR JobJnlLine : Record "Job Journal Line";JobItemPrice : Record "Job Item Price")
**>>> New Code**
```
IsHandled := FALSE;
OnBeforeCopyJobItemPriceToJobJnlLine(JobJnlLine, JobItemPrice, IsHandled);
IF IsHandled THEN
  EXIT;
```
**<<< New Code End**
```
WITH JobJnlLine DO BEGIN
  IF JobItemPrice."Apply Job Price" THEN BEGIN
    "Unit Price" := JobItemPrice."Unit Price";
    "Cost Factor" := JobItemPrice."Unit Cost Factor";
  END;
  IF JobItemPrice."Apply Job Discount" THEN
    "Line Discount %" := JobItemPrice."Line Discount %";
END;
```

In Our Solution we need to determine some additional situations wherein we copy Price information to Job Journal Lines or not. With this Publisher we have that flexibility.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
