### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnTransTransReqLineToProfileOnBeforeInsertInventoryProfile

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6455]
Requesting a new Event publisher on Codeunit 99000854 Inventory Profile Offsetting

Event
`OnTransTransReqLineToProfileOnBeforeInsertInventoryProfile(TransferReqLine : Record "Requisition Line"; VAR InsertLine : Boolean)`

**Code**
## LOCAL TransTransReqLineToProfile(VAR InventoryProfile : Record "Inventory Profile";VAR Item : Record Item;ToDate : Date)
```
TransferReqLine.SETCURRENTKEY("Replenishment System",Type,"No.","Variant Code","Transfer-from Code","Transfer Shipment Date");
TransferReqLine.SETRANGE("Replenishment System",TransferReqLine."Replenishment System"::Transfer);
TransferReqLine.SETRANGE(Type,TransferReqLine.Type::Item);
TransferReqLine.SETRANGE("No.",Item."No.");
Item.COPYFILTER("Location Filter",TransferReqLine."Transfer-from Code");
Item.COPYFILTER("Variant Filter",TransferReqLine."Variant Code");
TransferReqLine.SETFILTER("Transfer Shipment Date",'>%1&<=%2',0D,ToDate);
IF TransferReqLine.FINDSET THEN
  REPEAT
```
**>>>New Code**
```
    InsertLine := TRUE;
    OnTransTransReqLineToProfileOnBeforeInsertInventoryProfile(TransferReqLine, InsertLine)
    IF InsertLine THEN BEGIN
```    
**<<< New Code End**
```
      InventoryProfile.INIT;
      InventoryProfile."Line No." := NextLineNo;
      InventoryProfile."Item No." := Item."No.";
      InventoryProfile.TransferFromOutboundTransfPlan(TransferReqLine,TempItemTrkgEntry);
      IF InventoryProfile.IsSupply THEN
        InventoryProfile.ChangeSign;
      InventoryProfile.INSERT;
```
**>>> New Code**
```
    END;
```
**<<< New Code End**
```
  UNTIL TransferReqLine.NEXT = 0;
```

In Our Solution we need to be able to add Line to the Inventory Profile based on Conditions, with this Publisher we are able to do that, Please add the requested Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
