### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnBeforeAdjustTransferDates

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6456]
Requesting a new Event publisher on Codeunit 99000854 Inventory Profile Offsetting

Event
`OnBeforeAdjustTransferDates(TransferReqLine : Record "Requisition Line"; VAR IsHandled : Boolean)`

**Code**
## LOCAL AdjustTransferDates(VAR TransferReqLine : Record "Requisition Line")
```
// Used for planning lines handling transfer orders.
// "Ending Date", Starting Date and "Transfer Shipment Date" are calculated backwards from "Due Date".
```
**>>>New Code**
```
IsHandled := FALSE;
OnBeforeAdjustTransferDates(TransferReqLine,IsHandled)
IF IsHandled THEN
  EXIT;
```    
**<<< New Code End**
```
TransferReqLine.TESTFIELD("Ref. Order Type",TransferReqLine."Ref. Order Type"::Transfer);
WITH TransferReqLine DO BEGIN
  [...]
```

In Our Solution we need to be able to skip this function for Requisition lines which have Job Locations mentioned on it, with this Publisher we are able to do that, Please add the requested Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
