### ISSUE TITLE
Codeunit 5817 Undo Posting Management - Expose Function TestAllTransactions

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#6457]
Hi

Please can you expose the TestAllTransactions function in the Undo Posting Management Codeunit 5817?

That way when we create out own Tests we can then call this currently local function.

Thanks

**Comment by RomanZanizdra** [comment]
Hi @CnCollins . There are external functions which call the TestAllTransactions function. Why can't you use them to call in your tests instead of making TestAllTransaction external?

**Comment by CnCollins** [comment]
We need to call the function with our own parameters e.g. Transfer Shipment Line for the table parameter

**Comment by RomanZanizdra** [comment]
@CnCollins , ok, but still not clear how your own parameters are related to the functions inside TestAlltransaction and what they are testing? Because they are all have particular meaning and designed for particular purpose.

**Comment by CnCollins** [comment]
It's something we do with our IP.

**Comment by RomanZanizdra** [comment]
@CnCollins , below is TestAllTransactions with parameters. All parameters are supposed to be used in particular functions inside the procedure with particular purpose. Can you write an example of code with definite parameters how you are going to use this function?

TestAllTransactions(UndoType: Integer; UndoID: Code[20]; UndoLineNo: Integer; SourceType: Integer; SourceSubtype: Integer; SourceID: Code[20]; SourceRefNo: Integer)

**Comment by CnCollins** [comment]
Hi Roman

We are calling it with the Transfer Shipment Line, and there is not a external function to do this.

TestAllTransactions(Database::"Transfer Shipment Line", TransShptLine."Document No.", TransShptLine."Line No.", Database::"Transfer Line", 0, TransShptHdr."Transfer Order No.", TransShptLine."Line No.");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
