### ISSUE TITLE
[Event Request] Codeunit 56 OnBeforeApplyDefaultInvoiceDiscount

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6458]
We Need an additional Parameter InvoiceDiscountAmount in the existing Event OnBeforeApplyDefaultInvoiceDiscount:

old:
LOCAL [IntegrationEvent] OnBeforeApplyDefaultInvoiceDiscount(VAR SalesHeader : Record "Sales Header";VAR IsHandled : Boolean)
new:
LOCAL [IntegrationEvent] OnBeforeApplyDefaultInvoiceDiscount(VAR SalesHeader : Record "Sales Header";VAR IsHandled : Boolean;InvoiceDiscountAmount : Decimal)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
