### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 134893 "Background Document Posting"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6463]
[Event Request]Application “Tests-ERM”, Codeunit 134893 "Background Document Posting"
![pic1](https://user-images.githubusercontent.com/45795262/77057884-f0abde00-69d4-11ea-9958-d21f4e6b121e.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77057927-00c3bd80-69d5-11ea-81d7-2703b7b15de2.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
