### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138060 "Non-O365 Shipping Agent"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6464]
[Event Request]Application “Tests-ERM”, Codeunit 138060 "Non-O365 Shipping Agent"

![pic1](https://user-images.githubusercontent.com/45795262/77060335-b2182280-69d8-11ea-833f-53e74c3bf3f8.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77060342-b47a7c80-69d8-11ea-8add-ba06fe25541c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
