### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138070 "O365 Alt. Ship Addr. S. Ord."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6465]
[Event Request]Application “Tests-ERM”, Codeunit 138070 "O365 Alt. Ship Addr. S. Ord."
![pic1](https://user-images.githubusercontent.com/45795262/77060463-e55ab180-69d8-11ea-8986-fd5b6595834d.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77060474-e855a200-69d8-11ea-8176-d0032fc4f0a2.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
