### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138071 "O365 Alt. Ship Addr. S. Quo."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6466]
[Event Request]Application “Tests-ERM”, Codeunit 138071 "O365 Alt. Ship Addr. S. Quo."
![pic1](https://user-images.githubusercontent.com/45795262/77060584-1804aa00-69d9-11ea-94e4-630c8160291c.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77060591-1a670400-69d9-11ea-876e-ae60a73d8a7f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
