### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138072 "O365 Alt. Ship Addr. B. S. O."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6467]
[Event Request]Application “Tests-ERM”, Codeunit 138072 "O365 Alt. Ship Addr. B. S. O."
![pic1](https://user-images.githubusercontent.com/45795262/77060688-471b1b80-69d9-11ea-851e-6694b79f2589.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77060692-4a160c00-69d9-11ea-873a-6ce2ab2c3935.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
