### ISSUE TITLE
[Function Expose] WhseHandlingRequired in Codeunit 80 and 90

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6468]
Please make WhseHandlingRequired in codeunit 80 and 90 public and external, so that we can use the new trigger OnPostUpdateOrderLineOnSetDefaultQtyBlank
 similar to the Standard:

OnPostUpdateOrderLineOnSetDefaultQtyBlank
if WhseHandlingRequired(TempSalesLine) or SetDefaultQtyBlank then begin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
