### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138080 "O365 Ship-to Addr. P.I"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6469]
[Event Request]Application “Tests-ERM”, Codeunit 138080 "O365 Ship-to Addr. P.I"
![pic1](https://user-images.githubusercontent.com/45795262/77069566-eeec1580-69e8-11ea-91b2-62b6201da698.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77069571-f14e6f80-69e8-11ea-8ce8-1b849c2191b3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
