### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138083 "O365 Ship-to Addr. P.O"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6470]
[Event Request]Application “Tests-ERM”, Codeunit 138083 "O365 Ship-to Addr. P.O"
![pic1](https://user-images.githubusercontent.com/45795262/77070003-bf89d880-69e9-11ea-9ef9-ebaf93734c53.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070010-c1539c00-69e9-11ea-82ff-c32cc6062560.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
