### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138084 "O365 Pay-to & Order Addr. P.O"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6471]
[Event Request]Application “Tests-ERM”, Codeunit 138084 "O365 Pay-to & Order Addr. P.O"
![pic1](https://user-images.githubusercontent.com/45795262/77070101-ec3df000-69e9-11ea-8fbe-4e3d7a8cc101.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070103-eea04a00-69e9-11ea-95c5-dba0065c9c17.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
