### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138085 "O365 Ship-to Addr. P.Q"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6472]
[Event Request]Application “Tests-ERM”, Codeunit 138085 "O365 Ship-to Addr. P.Q"
![pic1](https://user-images.githubusercontent.com/45795262/77070272-37580300-69ea-11ea-9e6e-c305da2c8821.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070325-4e96f080-69ea-11ea-9e18-0dbb3c4bf8d9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
