### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138086 "O365 Pay-to & Order Addr. P.Q"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6473]
[Event Request]Application “Tests-ERM”, Codeunit 138086 "O365 Pay-to & Order Addr. P.Q"
![pic1](https://user-images.githubusercontent.com/45795262/77070415-7ab27180-69ea-11ea-918a-c23abb389955.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070423-7c7c3500-69ea-11ea-96c6-910b48137f4a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
