### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138087 "O365 Ship-to Addr. P.R.O"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6474]
[Event Request]Application “Tests-ERM”, Codeunit 138087 "O365 Ship-to Addr. P.R.O"
![pic1](https://user-images.githubusercontent.com/45795262/77070505-a33a6b80-69ea-11ea-8d88-337023c0985a.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070509-a5042f00-69ea-11ea-85de-ddce595d1ea9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
