### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 138088 "O365 Ship-to Addr. P.C.M"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6475]
[Event Request]Application “Tests-ERM”, Codeunit 138088 "O365 Ship-to Addr. P.C.M"
![pic1](https://user-images.githubusercontent.com/45795262/77070589-c8c77500-69ea-11ea-8d9b-44ae46c531b0.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070603-cc5afc00-69ea-11ea-9a43-edf6be5a042d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
