### ISSUE TITLE
[Event Request]Application “Tests-ERM”, Codeunit 139155 "PEPPOL Management Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6476]
[Event Request]Application “Tests-ERM”, Codeunit 139155 "PEPPOL Management Tests"
![pic1](https://user-images.githubusercontent.com/45795262/77070679-f7dde680-69ea-11ea-9a3b-a9c85b2b056f.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070684-f9a7aa00-69ea-11ea-86f2-7476d5ed41d4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
