### ISSUE TITLE
[Event Request]Application “Tests-General Journal”, Codeunit 134321 "General Journal Batch Approval"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6477]
[Event Request]Application “Tests-General Journal”, Codeunit 134321 "General Journal Batch Approval"
![pic1](https://user-images.githubusercontent.com/45795262/77070792-2bb90c00-69eb-11ea-95e4-20cf5ba8ac63.png)

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77070795-2d82cf80-69eb-11ea-92e1-368852966118.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
