### ISSUE TITLE
[Event Request]Application “Tests-General Journal”, Codeunit 135060 "Document Mailing Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6478]
[Event Request]Application “Tests-General Journal”, Codeunit 135060 "Document Mailing Tests"

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77074252-dc75da00-69f0-11ea-91dc-a598b4fd9934.png)

**Comment by JoergPernberg** [comment]
Sorry wrong test app. Correct one is Tests-Integration

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
