### ISSUE TITLE
[Event Request]Application “Tests-General Journal”, Codeunit 138907 "O365 Invoice Payment Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6479]
[Event Request]Application “Tests-General Journal”, Codeunit 138907 "O365 Invoice Payment Test"

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77074336-016a4d00-69f1-11ea-8116-fc98e806be97.png)

**Comment by JoergPernberg** [comment]
Sorry, wrong test app. Correct is Tests-Invoicing

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
