### ISSUE TITLE
[Event Request]Application “Tests-General Journal”, Codeunit 138916 "O365 Translation Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6480]
[Event Request]Application “Tests-General Journal”, Codeunit 138916 "O365 Translation Tests"

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77074465-31195500-69f1-11ea-8613-4a9c8b385312.png)

**Comment by JoergPernberg** [comment]
Sorry, I reported the wrong test app. Correct is Tests-Invoicing.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
