### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 133784 "Test Booking Invoicing"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6481]
[Event Request]Application “Tests-Misc”, Codeunit 133784 "Test Booking Invoicing"

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77074619-6160f380-69f1-11ea-920c-e239a2f2463f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
