### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 134164 "Company Init Unit Test II"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6482]
[Event Request]Application “Tests-Misc”, Codeunit 134164 "Company Init Unit Test II"

Could you please insert the OnTestInitialize Event at the beginning of the Test procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77074703-835a7600-69f1-11ea-911c-98b106745131.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
