### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 134320 "Record Restriction Mgt. Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6483]
[Event Request]Application “Tests-Misc”, Codeunit 134320 "Record Restriction Mgt. Tests"

Could you please insert the OnTestInitialize Event at the beginning of the Test procedure:
![pic2](https://user-images.githubusercontent.com/45795262/77074811-a84ee900-69f1-11ea-85c5-27302c5a78f3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
