### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 134338 "Copy Purch/Sales Doc UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6484]
[Event Request]Application “Tests-Misc”, Codeunit 134338 "Copy Purch/Sales Doc UT"

Could you please insert the OnTestInitialize Event at the beginning of each Test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77074931-d7655a80-69f1-11ea-89fa-f6b883da6b57.png)
![pic2](https://user-images.githubusercontent.com/45795262/77074937-d9c7b480-69f1-11ea-9c93-a7c24ed8d0bb.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
