### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 134348 "UT Page Actions & Controls - 2"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6485]
[Event Request]Application “Tests-Misc”, Codeunit 134348 "UT Page Actions & Controls - 2"

Could you please insert the OnTestInitialize Event at the beginning of each Test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77075034-04197200-69f2-11ea-926f-553cfbc0fc12.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
