### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 134421 "Report Selections Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6486]
[Event Request]Application “Tests-Misc”, Codeunit 134421 "Report Selections Tests"

Could you please insert the OnTestInitialize Event at the beginning of each Test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77075119-24e1c780-69f2-11ea-9fb8-25d795aabb0a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
