### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 134776 "Document Attachment Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6487]
[Event Request]Application “Tests-Misc”, Codeunit 134776 "Document Attachment Tests"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77075200-4478f000-69f2-11ea-9461-127e2bfc1c32.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
