### ISSUE TITLE
[Event Request]Application “Tests-Misc”, Codeunit 139003 "Test Instruction Mgt. PasS"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6488]
[Event Request]Application “Tests-Misc”, Codeunit 139003 "Test Instruction Mgt. PasS"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77075313-6d00ea00-69f2-11ea-97a9-248d8fc5657d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
