### ISSUE TITLE
[Function Expose] Table 1003 Job Planning Line - UpdateAllAmounts

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/ALAppExtensions#649]
Can you please make function UpdateAllAmounts in Table 1003 Job Planning Line External/Global please?

**Comment by darjoo** [comment]
Hi @bleisibach,
What is the reason you require UpdateAllAmounts to be made external? Is there a specific scenario you are trying to achieve?

**Comment by bleisibach** [comment]
Hi @darjoo 
We extended the table with fields that are influencing the pricing. On those fields we wish/need to call the UpdateAllAmounts function. Like we are able to call UpdateAmounts on Table 37 Sales Line.

**Comment by darjoo** [comment]
Sorry, after reviewing your suggestion we've decided that it isn't something we'll implement as we're trying to limit the amount of local functions being exposed. 
However, you may call UpdateAllAmounts by validating one of the other fields that already call UpdateAllAmounts like the following `VALIDATE("Unit Cost")`, `VALIDATE("Unit Price")`, `VALIDATE("Line Amount")`, `VALIDATE("Line Discount Amount")`, `VALIDATE("Cost Factor")`, `VALIDATE("Line Discount %")`.
