### ISSUE TITLE
[Event Request] CodeUnits 226 CustEntry-Apply Posted Entries and 227 VendEntry-Apply Posted Entries

### ISSUE THREAD

**Issue by NBOA** [microsoft/ALAppExtensions#6490]
We would like to add a filter in both codeUnit

**Comment by StanPesotskiy** [comment]
Hi @nboa
Please always put the full detailed signature of the requested events.
The best way is to copy the actual AL code you added. It will speed up the process of implementation.

**Comment by NBOA** [comment]
hi @StanPesotskiy 
I apologise, seem like i made 2 issues without realising it.
The Correct Issue can be found here
https://github.com/microsoft/ALAppExtensions/issues/6491

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
