### ISSUE TITLE
[Event Request] CodeUnits 226 CustEntry-Apply Posted Entries and 227 VendEntry-Apply Posted Entries

### ISSUE THREAD

**Issue by NBOA** [microsoft/ALAppExtensions#6491]
We would like to add a filter in both code Units to filter on the selected rec Currency Code when Action Applying Entries is called in both Vendor Ledger Entries or Customer Ledger Entries. Could you provide two events 

       - OnBeforeApplyCustEntries- 
       - OnBeforeApplyVendorEntries-

like shown below ?

In Code Unit 226 CustEntry-Apply Posted Entries :

[External] ApplyCustEntryFormEntry(VAR ApplyingCustLedgEntry : Record "Cust. Ledger Entry")
IF NOT ApplyingCustLedgEntry.Open THEN
  ERROR(CannotApplyClosedEntriesErr);
..............
CustLedgEntry.SETCURRENTKEY("Customer No.",Open,Positive);
CustLedgEntry.SETRANGE("Customer No.",ApplyingCustLedgEntry."Customer No.");
CustLedgEntry.SETRANGE(Open,TRUE);

**OnBeforeApplyCustEntries(CustLedgEntry, ApplyingCustLedgEntry);** 

IF CustLedgEntry.FINDFIRST THEN BEGIN
  ApplyCustEntries.SetCustLedgEntry(ApplyingCustLedgEntry);
  ApplyCustEntries.SETRECORD(CustLedgEntry);
  ApplyCustEntries.SETTABLEVIEW(CustLedgEntry);
  ApplyCustEntries.RUNMODAL;
..............
 
LOCAL [IntegrationEvent] OnBeforeApplyCustEntries(VAR CustLedgEntry : Record "Cust. Ledger Entry";ApplyingCustLedgeEntry : Record "Cust. Ledger Entry")

In Code Unit 227 VendEntry-Aplly Posted Entries: 

[External] ApplyVendEntryFormEntry(VAR ApplyingVendLedgEntry : Record "Vendor Ledger Entry")
IF NOT ApplyingVendLedgEntry.Open THEN
  ERROR(CannotApplyClosedEntriesErr);
.................
endLedgEntry.SETCURRENTKEY("Vendor No.",Open,Positive);
VendLedgEntry.SETRANGE("Vendor No.",ApplyingVendLedgEntry."Vendor No.");
VendLedgEntry.SETRANGE(Open,TRUE);

**OnBeforeApplyVendorEntries(VendLedgEntry, ApplyingVendLedgEntry);**    

IF VendLedgEntry.FINDFIRST THEN BEGIN
  ApplyVendEntries.SetVendLedgEntry(ApplyingVendLedgEntry);
  ApplyVendEntries.SETRECORD(VendLedgEntry);
  ApplyVendEntries.SETTABLEVIEW(VendLedgEntry);
  IF ApplyingVendLedgEntry."Applies-to ID" <> VendEntryApplID THEN
    ApplyVendEntries.SetAppliesToID(ApplyingVendLedgEntry."Applies-to ID");
  ApplyVendEntries.RUNMODAL;
..............................

LOCAL [IntegrationEvent] OnBeforeApplyVendorEntries(VAR VendLedgEntry : Record "Vendor Ledger Entry";ApplyingVendLedgEntry : Record "Vendor Ledger Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
