### ISSUE TITLE
[Event Request] Report 7391 OnBeforeInsertWWLine, OnBeforeInsertWIPLine, OnBeforeInsertTransferLine and OnBeforeInsertInternalMovementLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6492]
Please add a new Event trigger OnBeforeInsertWWLine, OnBeforeInsertWIPLine, OnBeforeInsertTransferLine and OnBeforeInsertInternalMovementLine in Report 7391 in Procedure InsertWWL, InsertWIPL, InsertTransferLine and InsertInternalMovementLine:

[External] InsertWWL()
WITH WWLine DO BEGIN
  INIT;
  "Line No." := "Line No." + 10000;
  VALIDATE("Location Code","Bin Content"."Location Code");
  VALIDATE("Item No.","Bin Content"."Item No.");
  VALIDATE("Variant Code","Bin Content"."Variant Code");
  VALIDATE("Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE("From Bin Code","Bin Content"."Bin Code");
  "From Zone Code" := "Bin Content"."Zone Code";
  VALIDATE("From Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE(Quantity,CalcQtyUOM(QtyToEmptyBase,"Qty. per From Unit of Measure"));
  IF QtyToEmptyBase <> (Quantity * "Qty. per From Unit of Measure") THEN BEGIN
    "Qty. (Base)" := QtyToEmptyBase;
    "Qty. Outstanding (Base)" := QtyToEmptyBase;
    "Qty. to Handle (Base)" := QtyToEmptyBase;
  END;
  "Whse. Document Type" := "Whse. Document Type"::"Whse. Mov.-Worksheet";
  "Whse. Document No." := Name;
  "Whse. Document Line No." := "Line No.";
  //+++++++++++++++++++++++++++++++
  OnBeforeInsertWWLine(VAR WWLine,"Bin Content");
  //-------------------------------
  INSERT;
END;

[External] InsertWIPL()
WITH WIPLine DO BEGIN
  INIT;
  "Line No." := "Line No." + 10000;
  VALIDATE("Location Code","Bin Content"."Location Code");
  VALIDATE("Item No.","Bin Content"."Item No.");
  VALIDATE("Variant Code","Bin Content"."Variant Code");
  VALIDATE("Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE("From Bin Code","Bin Content"."Bin Code");
  "From Zone Code" := "Bin Content"."Zone Code";
  VALIDATE("Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE(Quantity,CalcQtyUOM(QtyToEmptyBase,"Qty. per Unit of Measure"));
  IF QtyToEmptyBase <> (Quantity * "Qty. per Unit of Measure") THEN BEGIN
    "Qty. (Base)" := QtyToEmptyBase;
    "Qty. Outstanding (Base)" := QtyToEmptyBase;
  END;
  //++++++++++++++++++++++++++++++++
  OnBeforeInsertWIPLine(VAR WIPLine;"Bin Content"); 
  //--------------------------------
  INSERT;
END;

[External] InsertTransferLine()
WITH TransferLine DO BEGIN
  INIT;
  "Line No." := "Line No." + 10000;
  VALIDATE("Item No.","Bin Content"."Item No.");
  VALIDATE("Variant Code","Bin Content"."Variant Code");
  VALIDATE("Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE("Transfer-from Bin Code","Bin Content"."Bin Code");
  VALIDATE("Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE(Quantity,CalcQtyUOM(QtyToEmptyBase,"Qty. per Unit of Measure"));
  //++++++++++++++++++++++++++++++++++
  OnBeforeInsertTransferLine(VAR TransferLine; "Bin Content");
  //----------------------------------
  INSERT;
END;

[External] InsertIntMovementLine()
WITH InternalMovementLine DO BEGIN
  INIT;
  "Line No." := "Line No." + 10000;
  VALIDATE("Location Code","Bin Content"."Location Code");
  VALIDATE("Item No.","Bin Content"."Item No.");
  VALIDATE("Variant Code","Bin Content"."Variant Code");
  VALIDATE("Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE("From Bin Code","Bin Content"."Bin Code");
  VALIDATE("To Bin Code",InternalMovementHeader."To Bin Code");
  VALIDATE("Unit of Measure Code","Bin Content"."Unit of Measure Code");
  VALIDATE(Quantity,CalcQtyUOM(QtyToEmptyBase,"Qty. per Unit of Measure"));
  //+++++++++++++++++++++++++++++++++++++++++
  OnBeforeInsertInternalMovementLine(VAR InternalMovementLine;"Bin Content");
  //-----------------------------------------
  INSERT;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
