### ISSUE TITLE
Missing Call of new procedure in Report 1095 "Update Job Item Cost"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6494]
#5879 
While you have fixed the event request by adding a new procedure "ModifyAllValueEntries" in Preview of 16, you missed to call this procedure within the trigger "OnAfterGetRecord".
Please correct this.

Old Code of trigger OnAfterGetRecord:
```
      ValueEntry2.SetRange("Job Ledger Entry No.", 0);

      ValueEntry2.ModifyAll("Job No.", ValueEntry."Job No.");
      ValueEntry2.ModifyAll("Job Task No.", ValueEntry."Job Task No.");
      ValueEntry2.ModifyAll("Job Ledger Entry No.", ValueEntry."Job Ledger Entry No.");
    end;
end;
PostTotalCostAdjustment("Job Ledger Entry", JobLedgerEntryCostValue, JobLedgerEntryCostValueACY);
```

New Code by using the existing procedure:
```
      ValueEntry2.SetRange("Job Ledger Entry No.", 0);

      ModifyAllValueEntries(ValueEntry2,ValueEntry);  // this is an already existing procedure!
    end;
end;
PostTotalCostAdjustment("Job Ledger Entry", JobLedgerEntryCostValue, JobLedgerEntryCostValueACY);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
