### ISSUE TITLE
[New Event Request] Codeunit 392 "Reminder-Make", OnBeforeMakeReminderCustLedgEntryFindSet

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6497]
[New Event Request] Codeunit 392 "Reminder-Make", OnBeforeMakeReminderCustLedgEntryFindSet

The procedure MakeReminder in Codeunit "Reminder-Make" allows the creation of reminder lines from customer ledger entries. There are, however, app enhancements to the way reminder lines are or are not to be created which call for the possibility to set different filters on the customer ledger entries or to manipulate the value of the variable OverdueEntriesOnly in a more sophisticated way. 

We, thus, need the new integration event OnBeforeMakeReminderCustLedgEntryFindSet before the customer ledger entries are looped.

![image](https://user-images.githubusercontent.com/22153733/77103218-5a021000-6a1a-11ea-9e09-c9ee9d68ce0d.png)

**Integration Event:**
OnBeforeMakeReminderCustLedgEntryFindSet
**Signature:**
var CustLedgEntry: Record "Cust. Ledger Entry";
Cust: Record Customer;
ReminderHeader: Record "Reminder Header";
ReminderHeaderReq: Record "Reminder Header";
MaxReminderLevel: Integer;
var OverDueEntriesOnly: Boolean

To be inserted in procedure MakeReminder, immediately before "if CustLedgEntry.FindSet then".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
