### ISSUE TITLE
[Event Request]Application “Tests-Graph”, Codeunit 135528 "WFWH Subscription E2E Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6500]
[Event Request]Application “Tests-Graph”, Codeunit 135528 "WFWH Subscription E2E Tests"

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77148903-c28bd400-6a90-11ea-841a-298d94d88b7b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
