### ISSUE TITLE
167 Job - UpdateBillToCont

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6502]
We need to call the procedure "UpdateBillToCont" on Table 167 "Job" from outside.
Please change it from local to global.

OLD CODE:
```
local procedure UpdateBillToCont(CustomerNo: Code[20])
var
    ContBusRel: Record "Contact Business Relation";
    Cust: Record Customer;
```

NEW CODE:
```
procedure UpdateBillToCont(CustomerNo: Code[20])
var
    ContBusRel: Record "Contact Business Relation";
    Cust: Record Customer;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
