### ISSUE TITLE
Codeunit 6500 "Item Tracking Management" - OnBeforeInsertNewLotNoInfo

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#6503]
Hello Al Team,

in Codeunit 6500 "Item Tracking Management":
please provide a "Lot No. Information"  record instead of "NewLotNo" as parameter of function "CopyLotNoInformation" and a new publisher function:

```
procedure CopyLotNoInformation(LotNoInfo: Record "Lot No. Information"; **FromLotNoInfo: Record "Lot No. Information"**)
[...]
        end else begin
            NewLotNoInfo := LotNoInfo;
            NewLotNoInfo."Lot No." := FromLotNoInfo."Lot No.";

            // >> NEW
            OnBeforeInsertNewLotNoInfo(NewLotNoInfo,FromLotNoInfo);
            // << NEW
            NewLotNoInfo.Insert();
        end;
[...]
```

[IntegrationEvent(false, false)]
local procedure OnBeforeInsertNewLotNoInfo(var NewLotNoInfo: Record "Lot No. Information"; FromLotNoInfo: record "Lot No. Information")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by IngoStender** [comment]
The parameter is still not changed to a Lot No. Information record in the current BC preview (17.0.16010.0.).
