### ISSUE TITLE
[Event Request] T5077 OnCreateInteractionFromInteractLogEntryOnBeforeStartWizard

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#6504]
Can you please change the InteractionLogEntry param to var as we need the possibility to access the filters

local procedure OnCreateInteractionFromInteractLogEntryOnBeforeStartWizard(var SegmentLine: Record "Segment Line"; InteractionLogEntry: Record "Interaction Log Entry")

to

local procedure OnCreateInteractionFromInteractLogEntryOnBeforeStartWizard(var SegmentLine: Record "Segment Line"; Interhttps://guides.github.com/features/mastering-markdown/actionLogEntry: **var** Record "Interaction Log Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
