### ISSUE TITLE
[Exposure request] Function ShouldLookForCustomerByName in Sales Header

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#6506]
Please move or copy the function from ShouldLookForCustomerByName from Sales Header to Customer. I should not have the scope Scope('OnPrem') but should be externally accesible in a same way as the function LookupCustomer.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
