### ISSUE TITLE
[Exposure request] Publisher Event "OnBeforeCalculateSalesTax" for Report 1304 / 1305 / 1306 / 1307 same like 204 /205 / 296 /207

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/ALAppExtensions#6507]
Microsoft has marked reports (204, 205, 206, 207) as "Obsolete" with  Obsolete status "Pending" and Reason "Replaced with the report below Standard.

Report 204 will be replaced by Report 1304.
Report 205 will be replaced by Report 1305.
Report 206 will be replaced by Report 1306.
Report 207 will be replaced by Report 1307

As reports will be replaced and we do have integration earlier Report. 
Requesting the "**OnBeforeCalculateSalesTax**" Events here as Publisher Events to cater to the same feature/customization.

![image](https://user-images.githubusercontent.com/5293496/77157936-5927b780-6ac8-11ea-8ae6-7c4cd950981a.png)

Current "OnBeforeCalculateSalesTax" events available only for below two reports.

![image](https://user-images.githubusercontent.com/5293496/77158177-c89da700-6ac8-11ea-9a63-4c5a3542292e.png)

Versions:

AL Language: 5.0.219300
Business Central: Version: US Business Central 16.0 (Platform 15.0.39761.0 + Application 16.0.10855.0)

**Comment by StanPesotskiy** [comment]
Hi @chavansachin20,
Please provide the signature of the events along with the fragments of code that could define location of the event call unambiguously. 
The best way is to copy the actual AL code you would implement. It will speed up the process of implementation.

**Comment by chavansachin20** [comment]
@StanPesotskiy  , sorry for the delay in response, herewith sending Native object .al file along with modified object .al file, this will give you exact details for **signature of the events** along with the **fragments of code** 

The below list shows details of the report object with base and modified al file name. this file contains **Event signature** of event and **fragments of code** 


Object Type | Object ID | Native Object file name | Modified Object file name
-- | -- | -- | --
report | 1304 | report 1304 Standard Sales - Quote.al | report 1304report 1304 Standard Sales - Quote - Modified.al
report | 1305 | report 1306 Standard Sales - Invoice.al | report 1306report 204 Sales - Quote - Modified.al
report | 1306 | report 204 Sales - Quote.al | report 204 Sales - Quote - Modified.al
report | 1307 | report 206 Sales - Invoice.al | report 206 Sales - Invoice - Modified.al
report | 204 | Sales - Quote.al | Sales - Quote - Modified.al
report | 205 | Order Confirmation.al | Order Confirmation - Modified.al
report | 206 | Sales - Invoice.al | Sales - Invoice - Modified.al
report | 207 | Sales - Credit Memo.al | Sales - Credit Memo - Modified.al

Attached zip contains all base and modified files: 
![image](https://user-images.githubusercontent.com/5293496/83518876-a4af0680-a4f8-11ea-8aca-769caef67d87.png)


Zip file : 
[Modified AL Reports.zip](https://github.com/microsoft/ALAppExtensions/files/4717027/Modified.AL.Reports.zip)


Thanks 
Sachin Chavan
sachin.chavan@avalara.com

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
