### ISSUE TITLE
[Event Request] table 222 "Ship-to Address"

### ISSUE THREAD

**Issue by PatilloVolante** [microsoft/ALAppExtensions#6508]
Hi,

We need this modification in table 222 "Ship-to Address".

In the event OnBeforeLookupPostCode, we need "ShipToAddress" as VAR.

```
//>Old Code
[IntegrationEvent(false, false)]
local procedure OnBeforeLookupPostCode(ShipToAddress: Record "Ship-to Address"; var PostCodeRec: Record "Post Code");
begin
end;
//<Old Code
```

```
//>New Code
[IntegrationEvent(false, false)]
local procedure OnBeforeLookupPostCode(var ShipToAddress: Record "Ship-to Address"; var PostCodeRec: Record "Post Code");
begin
end;
//<New Code
```

Also, would it be possible to add the following event in trigger OnLookUp of "Post Code" field?

```
trigger OnLookup()
begin
OnBeforeLookupPostCode(Rec, PostCode);
PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");
//>New Code
OnAfterLookupPostCode(Rec, PostCode);
//<New Code
end;
```

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
