### ISSUE TITLE
[Event Request] table 18 "Customer"

### ISSUE THREAD

**Issue by PatilloVolante** [microsoft/ALAppExtensions#6509]
Hi,

Would it be possible to add the following event in trigger OnLookUp of "Post Code" field?

```
trigger OnLookup()
begin
OnBeforeLookupPostCode(Rec, PostCode);
PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");
//>New Code
OnAfterLookupPostCode(Rec, PostCode);
//<New Code
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
