### ISSUE TITLE
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" OnBeforeCustPostApplyCommit

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6510]
Because we some times need to apply customer ledger entries as part of a larger transaction, it would be very useful to be able to suppress the commit inside the function CustPostApplyCustLedgEntry.

For that reason, we request an event added before the commit, with an option to skip the commit.

Code snippet:

local procedure CustPostApplyCustLedgEntry(CustLedgEntry: Record "Cust. Ledger Entry"; DocumentNo: Code[20]; ApplicationDate: Date)
    var
        SourceCodeSetup: Record "Source Code Setup";
        GenJnlLine: Record "Gen. Journal Line";
        UpdateAnalysisView: Codeunit "Update Analysis View";
        GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line";
        GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
        Window: Dialog;
        EntryNoBeforeApplication: Integer;
        EntryNoAfterApplication: Integer;
        //>>L365
        SkipCommit: Boolean;
        //<<L365
        
    begin
...

EntryNoAfterApplication := FindLastApplDtldCustLedgEntry;
if EntryNoAfterApplication = EntryNoBeforeApplication then
    Error(NoEntriesAppliedErr, GenJnlLine.FieldCaption("Applies-to ID"));

 if PreviewMode then
    GenJnlPostPreview.ThrowError;

//>>L365
OnBeforeCustPostApplyCommit(SkipCommit);
if not SkipCommit then
//<<L365
        Commit();

Window.Close;
UpdateAnalysisView.UpdateAll(0, true);
end;

...

[IntegrationEvent(false, false)]
local procedure OnBeforeCustPostApplyCommit(VAR Handled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
