### ISSUE TITLE
[Event Request] Page 491 Items By Location - OnSetColumnsOnAfterSetLocationFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6511]
Requesting a new Event publisher on Page 491 Items by Location

Event
`OnSetColumnsOnAfterSetLocationFilters(VAR TempMatrixLocation: TEMPORARY Record Location)`

***We would like to have set the property IncludeSender to TRUE***

**Code**

## SetColumns(SetWanted : 'Initial,Previous,Same,Next')
```
TempMatrixLocation.SETRANGE("Use As In-Transit",ShowInTransit);
```
**>>> New Code**
```
OnSetColumnsOnAfterSetLocationFilters(TempMatrixLocation);
```
**<<< New Code End**
```
CLEAR(MATRIX_CaptionSet);
CLEAR(MatrixRecords);
CurrentMatrixRecordOrdinal := 1;

MatrixRecordRef.GETTABLE(TempMatrixLocation);
MatrixRecordRef.SETTABLE(TempMatrixLocation);

IF ShowColumnName THEN
  CaptionFieldNo := TempMatrixLocation.FIELDNO(Name)
ELSE
  CaptionFieldNo := TempMatrixLocation.FIELDNO(Code);

MatrixMgt.GenerateMatrixData(MatrixRecordRef,SetWanted,ARRAYLEN(MatrixRecords),CaptionFieldNo,MATRIX_PKFirstRecInCurrSet,
  MATRIX_CaptionSet,MATRIX_CaptionRange,MATRIX_CurrSetLength);

IF MATRIX_CaptionSet[1] = '' THEN BEGIN
  MATRIX_CaptionSet[1] := UnspecifiedLocationCodeTxt;
  MATRIX_CaptionRange := STRSUBSTNO('%1%2',MATRIX_CaptionSet[1],MATRIX_CaptionRange);
END;

IF MATRIX_CurrSetLength > 0 THEN BEGIN
  TempMatrixLocation.SETPOSITION(MATRIX_PKFirstRecInCurrSet);
  TempMatrixLocation.FIND;
  REPEAT
    MatrixRecords[CurrentMatrixRecordOrdinal].COPY(TempMatrixLocation);
    CurrentMatrixRecordOrdinal := CurrentMatrixRecordOrdinal + 1;
  UNTIL (CurrentMatrixRecordOrdinal > MATRIX_CurrSetLength) OR (TempMatrixLocation.NEXT <> 1);
END;

UpdateMatrixSubform;
```

We need the possibility to filter out the locations which are "Job Locations" based on a boolean on the Header of the page. To get to this setting we have created a Global Function which returns the value of the boolean, that is why we need the ***property IncludeSender*** set to ***Yes*** so we can reach this Global Function. Please add this Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
