### ISSUE TITLE
[Event Request] Table 454 Approval Entry - OnBeforeMarkAllWhereUserisApproverOrSender

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6512]
Requesting a new Event publisher on Table 454 Approval Entry

Event
`OnBeforeMarkAllWhereUserisApproverOrSender(VAR Rec : Record "Approval Entry";VAR IsHandled : Boolean)`

**Code**

## [External] MarkAllWhereUserisApproverOrSender()
```
IF UserSetup.GET(USERID) AND UserSetup."Approval Administrator" THEN
  EXIT;
```
**>>> New Code**
```
IsHandled := FALSE;
OnBeforeMarkAllWhereUserisApproverOrSender(Rec, IsHandled);
IF IsHandled THEN
  EXIT;
```
**<<< New Code End**
```
FILTERGROUP(-1); // Used to support the cross-column search
SETRANGE("Approver ID",USERID);
SETRANGE("Sender ID",USERID);
IF FINDSET THEN
  REPEAT
    MARK(TRUE);
  UNTIL NEXT = 0;
MARKEDONLY(TRUE);
FILTERGROUP(0);
```

We need the possibility to skip this code and present all the Approval Entries, In our Solution users have to go to the original document and Approve the Document via Custom made application which handles Document Statusses. Could you please add the requested Publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
