### ISSUE TITLE
[Event Request] Page 950 Time Sheet - OnSetColumnsOnAfterGetTimeSheetHeader

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6513]
Requesting a new Event publisher on Page 950 Time Sheet

Event
`OnSetColumnsOnAfterGetTimeSheetHeader(VAR TimeSheetHeader : Record "Time Sheet Header")`

**Code**

## [External] SetColumns()
```
CLEAR(ColumnCaption);
CLEAR(ColumnRecords);
CLEAR(Calendar);
CLEAR(NoOfColumns);

TimeSheetHeader.GET(CurrTimeSheetNo);
```
**>>> New Code**
```
OnSetColumnsOnAfterGetTimeSheetHeader(TimeSheetHeader);
```
**<<< New Code End**
```
Calendar.SETRANGE("Period Type",Calendar."Period Type"::Date);
Calendar.SETRANGE("Period Start",TimeSheetHeader."Starting Date",TimeSheetHeader."Ending Date");
IF Calendar.FINDSET THEN
  REPEAT
    NoOfColumns += 1;
    ColumnRecords[NoOfColumns]."Period Start" := Calendar."Period Start";
    ColumnCaption[NoOfColumns] := TimeSheetMgt.FormatDate(Calendar."Period Start",1);
  UNTIL Calendar.NEXT = 0;
```

We need the possibility to Calculate some additional Flowfields which are presented on the Page, Could you please add the requested Publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
