### ISSUE TITLE
[Event Request]Application “Tests-Bank”, Codeunit  134271 "Payment Recon. E2E Tests Perf."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6515]
[Event Request]Application “Tests-Bank”, Codeunit  134271 "Payment Recon. E2E Tests Perf."

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77178137-fb46a000-6ac6-11ea-8904-19be3fbb1139.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
