### ISSUE TITLE
[Enum Request] Table 7342 "Posted Invt. Pick Header" Field 7307 "Source Document"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6516]
Reference to #6367

Please also change the field 7307 "Source Document" at Table 7342 "Posted Invt. Pick Header" from Option to Enum in order to make it extensible.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
