### ISSUE TITLE
[Event Request]Application “Tests-Data Exchange”, 139154 "Incoming Doc. To Data Exch.UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6517]
[Event Request]Application “Tests-Data Exchange”, 139154 "Incoming Doc. To Data Exch.UT"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77178345-3ea10e80-6ac7-11ea-8b96-e2767c8e5e66.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
