### ISSUE TITLE
[Event Request]Application “Tests-ERM”, 134152 "ERM Intercompany II"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6518]
[Event Request]Application “Tests-ERM”, 134152 "ERM Intercompany II"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77178729-cab33600-6ac7-11ea-8001-78a18d67a7bf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
