### ISSUE TITLE
[Enum Request] Table 7343 "Posted Invt. Pick Line" Field 9 "Source Document"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6519]
Reference to #6367 and #6516

Please also change the field 9 "Source Document" at Table 7343 "Posted Invt. Pick Line" from Option to Enum in order to make it extensible.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
