### ISSUE TITLE
Publish localization extensions source code

### ISSUE THREAD

**Issue by Hornsyld** [Microsoft/ALAppExtensions#652]
Can you publish all of the localization extensions source code like you have done with 
C52012DataMigration, EssentialBusinessHeadlines, ImageAnalysis, SalesAndInventoryForecast at the Repository for collaboration on Microsoft AL application add-on and localization extensions for Microsoft Dynamics 365 Business Central
https://github.com/Microsoft/ALAppExtensions

I am especially missing looking at "Payment and Reconciliation Formats (DK)" or "FIK"

Thanks in advance,
would be useful.

**Comment by JesperSchulz** [comment]
We will soon be publishing local extensions as well! We just had to iron out some formalities before we do. Stay tuned for more extensions on https://github.com/Microsoft/ALAppExtensions.

**Comment by epernst** [comment]
Until then, then the APP (incl. the source) is available on the Danish DVD. Depending on what you need the code for.

**Comment by Hornsyld** [comment]
I am pretty sure that it’s only the .APP-file incl. In the DVD download. The source code is not on the DVD - only on NAV2018, but not for the business central dvd download. 

If you need to add code adjustment for ect. the OIOUBL-file format, how would you change this in business central? Assuming the source code is not availble?

**Comment by epernst** [comment]
If the app file is there, then the source code is also there. Just unzip the APP file.

**Comment by AndreiPanko** [comment]
Good news! FIK extension was added to the repo:
https://github.com/Microsoft/ALAppExtensions/tree/master/FIK

Looking forward to seeing your pull request :)
