### ISSUE TITLE
[Event Request]Application “Tests-ERM”, 138081 "O365 Pay-to Addr. P.I"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6520]
[Event Request]Application “Tests-ERM”, 138081 "O365 Pay-to Addr. P.I"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77178945-1bc32a00-6ac8-11ea-9d60-051e5b558df9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
