### ISSUE TITLE
[Event Request]Application “Tests-Job”, 136358 "UT T Purchase Line Usage Link"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6521]
[Event Request]Application “Tests-Job”, 136358 "UT T Purchase Line Usage Link"
Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77179053-3eedd980-6ac8-11ea-9322-53d091cff70e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
