### ISSUE TITLE
[Enum Request] Table 7323 "Posted Whse. Shipment Line" fields "Source Document", "Destination Type", "Posted Source Document"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6522]
Reference to #6367, #6516 and #6519

Please also change the Table 7323 "Posted Whse. Shipment Line" for following fields from Option to Enum in order to make it extensible:

-`field(9; "Source Document"; Option)`

-`field(39; "Destination Type"; Option)`

-`field(60; "Posted Source Document"; Option)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
