### ISSUE TITLE
[Event Request]Application “Tests-Misc”, 139480 "Notification Lifecycle Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6523]
[Event Request]Application “Tests-Misc”, 139480 "Notification Lifecycle Tests"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/77179289-90966400-6ac8-11ea-9d0a-013e69fbfd23.png)
![pic2](https://user-images.githubusercontent.com/45795262/77179297-93915480-6ac8-11ea-83e7-d86303c24d10.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
