### ISSUE TITLE
[New Event Request] Codeunit 392 "Reminder-Make", OnBeforeFindAndMarkReminderCandidates

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6525]
[New Event Request] Codeunit 392 "Reminder-Make", OnBeforeFindAndMarkReminderCandidates

There are a lot of enhancements to the way reminders are chosen and collected. We would, thus, need a Handled Pattern to be able to implement more sophisticated business logic in the procdure FindAndMarkReminderCandidates in the codeunit "Reminder-Make".

This is how we would like to have it implemented:

![image](https://user-images.githubusercontent.com/22153733/77201576-03b1d180-6aed-11ea-9589-f642eb9da4f4.png)

**Integration Event:**
OnBeforeFindAndMarkReminderCandidates
**Signature:**
var ReminderLevel: Record "Reminder Level";
ReminderHeaderReq: Record "Reminder Header";
ReminderTerms: Record "Reminder Terms";
var ReminderEntry: Record "Reminder/Fin. Charge Entry";
var CustLedgEntry: Record "Cust. Ledger Entry";
var TempCustLedgEntryOnHold: Record "Cust. Ledger Entry";
var CustLedgEntryLastIssuedReminderLevelFilter: Text;
var CustAmount: Decimal;
var MakeDoc: Boolean;
var MaxReminderLevel: Integer;
var MaxLineLevel: Integer;
OverdueEntriesOnly: Boolean;
IncludeEntriesOnHold: Boolean;
var IsHandled: Boolean

To be implemented right at the beginning of local procedure FindAndMarkReminderCandidates in codeunit "Reminder-Make".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
