### ISSUE TITLE
[Event Request] Table 179 "Reversal Entry" - OnAfterCheckEntries - Add new Parameter "MaxPostingDate"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6529]
Please add the global variable "MaxPostingDate" as parameter to the existing event publisher "OnAfterCheckEntries" in order to extend the calculation of the maximum possible posting date.

OLD CODE:
```
end;
OnAfterCheckEntries;
DateComprReg.CheckMaxDateCompressed(MaxPostingDate, 1);
```

NEW CODE:
```
end;
OnAfterCheckEntries(MaxPostingDate); // New parameter added!
DateComprReg.CheckMaxDateCompressed(MaxPostingDate, 1);
```

OLD PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnAfterCheckEntries()
begin
end;
```

NEW PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnAfterCheckEntries(var MaxPostingDate: Date)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
