### ISSUE TITLE
[Event Request] Table 5964 "Service Contract Line" - OnValidateServiceItemNoOnBeforeCheckSameCustomer - Change Parameter "ServContractHeader" to VAR

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6530]
Please change the parameter "ServContractHeader" within existing event publisher "OnValidateServiceItemNoOnBeforeCheckSameCustomer" to "var". We need to set some own field information on ContractHeader by Service Item.

OLD PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnValidateServiceItemNoOnBeforeCheckSameCustomer(ServItem: Record "Service Item"; ServContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
begin
end;
```

NEW PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnValidateServiceItemNoOnBeforeCheckSameCustomer(ServItem: Record "Service Item";var ServContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
