### ISSUE TITLE
[Function Request] Allow Copy Records in "Recurrence Schedule" table

### ISSUE THREAD

**Issue by mynavblog** [microsoft/ALAppExtensions#6533]
Dear Team,

Please allow copy records in the table "Recurrence Schedule". It is required to be able to copy data which use the "Recurrence Schedule" Guid. 

Business Case Scenario:
1. There is a line which allows to set the Recurrence Schedule and stores Guid in the field
2. User wants to copy the line and set new Recurrence Schedule.

This cannot be done because the same Guid is used it means that both lines are modify the same record in "Recurrence Schedule".

Thank you in advance.

**Comment by StanPesotskiy** [comment]
For the new features please submit a product suggestion on https://aka.ms/bcideas
