### ISSUE TITLE
[Event Request] Function "LogSegment" in Codeunit 5051 "SegManagement"

### ISSUE THREAD

**Issue by TillZoell** [microsoft/ALAppExtensions#6534]
Dear Team, we would like to have the following publisher added to the Function "LogSegment" in Codeunit 5051 "SegManagement":

```
procedure LogSegment(SegmentHeader: Record "Segment Header"; Deliver: Boolean; Followup: Boolean)
var
    [...]
begin
    [...]

    LoggedSegment.Reset;
    LoggedSegment.Init;
    [...]
    OnBeforeLoggedSegmentInsert(LoggedSegment);
    LoggedSegment.Insert;
    // START NEW EVENT 1
    OnAfterLoggedSegmentInsert(LoggedSegment, SegmentHeader);
    // END NEW EVENT 1

    [...]

    if SegmentLine.FindSet then begin
        [...]
        repeat
            [...]
            OnBeforeInteractLogEntryInsert(InteractLogEntry, SegmentLine);
            InteractLogEntry.Insert;
            // START NEW EVENT 2
            OnAfterInteractLogEntryInsert(InteractLogEntry, SegmentLine);
            // END NEW EVENT 2
            [...]
        until SegmentLine.Next = 0;
    end else
        Error(Text001, SegmentHeader."No.");

    [...]

    if Followup then begin
        Clear(SegmentHeader);
        SegmentHeader."Campaign No." := CampaignNo;
        SegmentHeader.Description := CopyStr(StrSubstNo(Text002, SegmentNo), 1, 50);
        // START NEW EVENT 3
        OnBeforeInsertFollowUpSegment(SegmentHeader, LoggedSegment);
        // END NEW EVENT 3
        SegmentHeader.Insert(true);
        SegmentHeader.ReuseLogged(LoggedSegment."Entry No.");
        OnAfterInsertFollowUpSegment(SegmentHeader);
    end;

    [...]
end;
```

```
// EVENT 1:
[IntegrationEvent(false, false)]
local procedure OnAfterLoggedSegmentInsert(var LoggedSegment: Record "Logged Segment"; SegmentHeader: Record "Segment Header")
begin
end;
```

```
// EVENT 2:
[IntegrationEvent(false, false)]
local procedure OnAfterInteractLogEntryInsert(var InteractionLogEntry: Record "Interaction Log Entry"; SegmentLine: Record "Segment Line")
begin
end;
```

```
// EVENT 3:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertFollowUpSegment(var SegmentHeader: Record "Segment Header"; LoggedSegment: Record "Logged Segment")
begin
end;
```

**Comment by RomanZanizdra** [comment]
Hi @TillZoell . Can you explain why do you need for example OnAfterLoggedSegmentInsert(LoggedSegment, SegmentHeader) if there are two lines above OnBeforeInsert event with LoggedSegment as var? Is it because of absence SegmentHeader as parameter in event before or there is any other deep meaning of having one by one events?

**Comment by TillZoell** [comment]
Hi @RomanZanizdra . We need the OnAfterLoggedSegmentInsert(...) there for two reasons. The first reason is as you mentioned the abesence of SegmentHeader in the OnBeforeLoggedSegmentInsert(..)-Event. The other reason is that for our logic we need the System-ID of the Logged Segment and the System ID of the Logged Segment is only filled after the Insert. That is why we need the OnAfterLoggedSegmentInsert(...) Event.

**Comment by RomanZanizdra** [comment]
Hi @TillZoell , thanks for clarification. Then one more question about third event, OnBeforeInsertFollowUpSegment. There is one more event two lines below, could it be enough if we add LoggedSegment as paramter in this event? If not then why?

**Comment by TillZoell** [comment]
Hi @RomanZanizdra , we need the OnBeforeInsertFollowUpSegment because we have created a subscriber to the OnAfterInsert Event of the Segment Header table. In this subscriber we fill some fields with some values. However, if the Segment Header is a FollowUp segment we do not want to execute the OnAfterInsert Event of the Segment Header table because in this case we want to fill some fields differently. So for this we need the OnBeforeInsertFollowUpSegment to fill the fields for the FollowUp Segment there and then simply skip the OnAfterInsert subscriber in the Segment Header table if the fields are already filled.

It would be ideal if the LoggedSegment parameter could be added to the OnAfterInsertFollowUp as you mentioned, because here too we need the System ID of the FollowUp Segment.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
