### ISSUE TITLE
… and also the parameter `HeaderExists` should be passed by reference (VAR).

### ISSUE THREAD

**Issue by lukas-pfeifhofer** [microsoft/ALAppExtensions#6535]
The integration event `OnAfterFindTempProdOrder`, was not implemented as requested, the parameters `ReqLine` and `ProdOrder` are passed by value instead by reference as requested.

… and also the parameter `HeaderExists` should be passed by reference (VAR).
The definition of the new event should looks like:

    [IntegrationEvent(false, false)]
    local procedure OnAfterFindTempProdOrder(var ReqLine: Record "Requisition Line"; var ProdOrder: Record "Production Order"; var HeaderExists: Boolean)
    begin
    end;

_Originally posted by @lukas-pfeifhofer in https://github.com/microsoft/ALAppExtensions/issues/5672#issuecomment-577136707_

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
