### ISSUE TITLE
[Event Request] Report 730 - Copy Item - OnAfterCopyItem with IncludeSender=true

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#6537]
Dear ALAppExtensions team,
Through this issue we would like to request event OnAfterCopyItem to be adjusted to have `IncludeSender=true` for this event.
That is, so that we can act on additional options added to the request page, which can hopefully be added in the future via report-extensions.

We want to be able to add options via extensions to the request page and subscribe to this event in the report. The subscriber can then use the sender and see if the added option was enabled or not (e.g., via a procedure `sender.CopyMySubsidiaryRecordsIsEnabled`).
If it was enabled, then the subscriber can trigger to also copy subsidiary records from our extension tables from the source item to the target item.

**Comment by rvanbekkum** [comment]
If you have other/better suggestions of how to let the event subscribers know which options (and additional options) were enabled, please feel free to share.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
