### ISSUE TITLE
[Event Request] Report 730 - Copy Item - OnBeforeCopyItem

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#6538]
Dear ALAppExtensions team,
Through this issue we would like to request event OnBeforeCopyItem to be added to report 730 "Copy Item" which would have the following signature:
```pascal
    [IntegrationEvent(true, false)]
    local procedure OnBeforeCopyItem(SourceItem: Record Item)
    begin
    end;
```
with `IncludeSender=true` (This is so that we can act on additional options added to the request page, that can hopefully be added in the future via report-extensions).

This event publisher would be called as follows in procedure `CopyItem`:
```pascal
    procedure CopyItem(CopyCounter: Integer)
    var
        TargetItem: Record Item;
    begin
        OnBeforeCopyItem(SourceItem); // << New event

        InsertTargetItem(TargetItem, CopyCounter);

        if not (CopySalesLineDisc or CopyPurchLineDisc) then begin
            TargetItem."Item Disc. Group" := '';
            TargetItem.Modify;
        end;

        CopyItemPicture(SourceItem, TargetItem);
        CopyItemComments(SourceItem."No.", TargetItem."No.");
        ...
    end;
```
This is so that we can add preliminary checks before the procedure goes through copying all records to the target item.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
