### ISSUE TITLE
Codeunit 5631 FA Jnl.-Check Line - CheckFAIntegration #5088

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#6539]
We have requested before an event in CU5631 (issue5088) that has been approved and provided in cu15.4.
we see we have forgotten to have the variable "GnlJnlPosting" also by reference (var).
could this parameter be made var?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
