### ISSUE TITLE
[Enum Request] Table 83 Field 90 "Order Type"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#654]
Please implement field 90 "Order Type" in table 83 and other tables (32, 5802, 5832) as enum

**Comment by GuntherGebauer** [comment]
Hello @DuttaSoumya,

that does not help if that is the only change. We Need more:
see e.g. table 83 - CreateDim

on several fields there is coded
IF ((NOT ("Order Type" IN ["Order Type"::Production,"Order Type"::Assembly])) OR ("Order No." = '')) AND NOT "Phys. Inventory"
THEN
  CreateDim(

has to be changed to 
if ((not (IsOrderTyperProduction OR IsOrderTypeAssembly))  ("Order No." = '')) AND NOT "Phys. Inventory"

additonal Event trigger OnBeforeCreateDim is needed

On field 91 and 92 "Order No." and "Order Line No." the coding has to bechanged as well and additional Event trigger are needed:

old:
CASE "Order Type" OF
  "Order Type"::Production,"Order Type"::Assembly:

new ??
case "Order Type" of

  IsOrderTypeProduction: ProdOrder.GET

  Is OrderTypeAssembly: AssemblyHeader.GET


  else
    OnIsOrderTypeElse ???


Actually we are using our own "Order Type"::Deboning which is the opposite type busniess compared with Assembly/production. You have 1 Item of consumption (e.g. Ham,Pork,Meat) and the Output are severel items as "Ham nut", "Ham lower Shell", "Ham bone", "Ham Skin" and so on.


with "Order type" as enum we can adapt table 83 with table Extension for OrderType=Deboning.

**Comment by DuttaSoumya** [comment]
Thanks @GuntherGebauer for your feedback. We agree to your comments and will make the implementation likewise.

Only one comment: we shall not be introducing new events in the OnValidate trigger for fields 91 and 92, simply because one can easily subscribe to TAB83::OnAfterValidateEvent for the correct field number and extend the implementation there.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
