### ISSUE TITLE
[Extensibility Enhancement] Report 730 - Copy Item - InitializeRequest

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#6542]
Dear ALAppExtension team,
Through this issue we would like to request a procedure `InitializeRequest` to be added to report 730 "Copy Item" that could be implemented similar to this:
```pascal
    procedure InitializeRequest(NewSourceItem: Record Item; NewTargetItemNo: Code[20]; NewTargetNoSeries: Code[20]; CopyAllSubsidiaryRecords: Boolean)
    begin
        SourceItem := NewSourceItem;
        TargetItemNo := NewTargetItemNo;
        TargetNoSeries := NewTargetNoSeries;
        if CopyAllSubsidiaryRecords then begin
            CopyGenItemInfo := true;
            CopyComments := true;
            CopyPic := true;
            CopyUnitOfMeasure := true;
            CopyVariants := true;
            CopyTranslations := true;
            CopyExtTxt := true;
            CopyBOM := true;
            CopyItemVendor := true;
            CopyDimensions := true;
            CopyTroubleshooting := true;
            CopyResourceSkills := true;
            CopySalesPrices := true;
            CopySalesLineDisc := true;
            CopyPurchPrices := true;
            CopyPurchLineDisc := true;
            CopyAttributes := true;
        end;

        OnAfterInitializeRequest(SourceItem, TargetItemNo, TargetNoSeries, CopyAllSubsidiaryRecords);
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterInitializeRequest(NewSourceItem: Record Item; NewTargetItemNo: Code[20]; NewTargetNoSeries: Code[20]; CopyAllSubsidiaryRecords: Boolean)
    begin
    end;
```
We would like to be able to run the report and set the settings externally instead of through the request page.
Additionally this procedure could have an event `OnAfterInitializeRequest` (with `IncludeSender=true`) so that options added by extensions can also be supported.

**Comment by RomanZanizdra** [comment]
Hi @rvanbekkum . Why can't you use "Copy Item" codeunit for non-UI run and copy?

**Comment by rvanbekkum** [comment]
Hi @RomanZanizdra, You are right, don't know how I could have missed that.
For 16.0 we can use that. I was checking both versions (15.x and 16.0) and somehow missed that codeunit 730 "Copy Item" was completely revised.

Will the requested events in #6538 and #6541 also be applied in codeunit 730?

**Comment by NKarolak** [comment]
Caution, it could be that, your your non-UI call, you are still missing some features that Microsoft is only about to prepare:
https://github.com/microsoft/ALAppExtensions/issues/6194 (but I did not check the latest insider build yet)

**Comment by RomanZanizdra** [comment]
@rvanbekkum , no, they are already checked-in. Please take a look at the codeunit and create a separate requests for the events you need there. 
Can we close current issue?

**Comment by rvanbekkum** [comment]
Yes, the issue can be closed. Thank you for your input!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
