### ISSUE TITLE
[New Event Request] Codeunit "Sales-Post", OnBeforePostATOAssocItemJnlLine

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6543]
[New Event Request] Codeunit 80 "Sales-Post", OnBeforePostATOAssocItemJnlLine

Some of our partners have greatly enhanced the Assembly-to-Order functionality and need to basically enhance all of the ATO functions in the codeunit "Sales-Post" with their own code. In a lot of cases the easiest approach is to replace the existing functions by implementing the Handled Pattern.

To be implemented right at the beginning of procedure PostATOAssocItemJnlLine:

![image](https://user-images.githubusercontent.com/22153733/77343518-18cb7200-6d32-11ea-82d4-d9b99ed4f0ff.png)

**Integration Event:**
OnBeforePostATOAssocItemJnlLine
**Signature:**
SalesHeader: Record "Sales Header";
SalesLine: Record "Sales Line";
var PostedATOLink: Record "Posted Assemble-to-Order Link";
var RemQtyToBeInvoiced: Decimal;
var RemQtyToBeInvoicedBase: Decimal;
var ItemLedgShptEntryNo: Integer;
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
