### ISSUE TITLE
[New Event Request] Codeunit "Sales-Post", OnBeforeInitPostATO

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6544]
[New Event Request] Codeunit 80 "Sales-Post", OnBeforeInitPostATO

Some of our partners have greatly enhanced the Assembly-to-Order functionality and need to basically enhance all of the ATO functions in the codeunit "Sales-Post" with their own code. In a lot of cases the easiest approach is to replace the existing functions by implementing the Handled Pattern.
To be implemented right at the beginning of procedure InitPostATO:

![image](https://user-images.githubusercontent.com/22153733/77344929-313c8c00-6d34-11ea-949c-678055631181.png)

**Integration Event:**
OnBeforeInitPostATO
**Signature:**
SalesHeader: Record "Sales Header";
var SalesLine: Record "Sales Line";
var AsmPost: Codeunit "Assembly-Post";
HideProgressWindow: Boolean;
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
