### ISSUE TITLE
[New Event Request] Codeunit "Sales-Post", OnBeforePostATO

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6545]
[New Event Request] Codeunit 80 "Sales-Post", OnBeforePostATO

Some of our partners have greatly enhanced the Assembly-to-Order functionality and need to basically enhance all of the ATO functions in the codeunit "Sales-Post" with their own code. In a lot of cases the easiest approach is to replace the existing functions by implementing the Handled Pattern.

To be implemented right at the beginning of procedure PostATO:

![image](https://user-images.githubusercontent.com/22153733/77353627-99459f00-6d41-11ea-8a0a-bfd25d8674f2.png)

**Integration Event:**
OnBeforePostATO
**Signature:**
SalesHeader: Record "Sales Header";
var SalesLine: Record "Sales Line";
var TempPostedATOLink: Record "Posted Assemble-to-Order Link" temporary;
var AsmPost: Codeunit "Assembly-Post";
var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line" ;
var ResJnlPostLine: Codeunit "Res. Jnl.-Post Line";
var WhseJnlPostLine: Codeunit "Whse. Jnl.-Register Line" ;
HideProgressWindow: Boolean;
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
