### ISSUE TITLE
[Event Request] Table 179 Reversal Entry - OnBeforeCheckCust

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6546]
Please add a new publisher event to the function CheckCust as follows:
	
```
LOCAL CheckCust(CustLedgEntry : Record "Cust. Ledger Entry")
//>> Start New Publisher Call
OnBeforeCheckCust(CustLedgEntry);
//<< End New Publisher Call

Cust.GET(CustLedgEntry."Customer No.");
.
.
```

New Publisher Event:

```
Property IncludeSender: Yes
LOCAL [IntegrationEvent] OnBeforeCheckCust(VAR CustLedgerEntry : Record "Cust. Ledger Entry")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
