### ISSUE TITLE
[Event Request] Table 179 Reversal Entry - OnBeforeCheckVend

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6547]
Please add a new publisher event to the function CheckVend as follows:
	
```
LOCAL CheckVend(VendLedgEntry : Record "Vendor Ledger Entry")
//>> Start New Publisher Call
OnBeforeCheckVend(VendLedgEntry);
//<< End New Publisher Call

Vend.GET(VendLedgEntry."Vendor No.");
.
.
```

New Publisher Event:

```
Property IncludeSender: Yes
LOCAL [IntegrationEvent] OnBeforeCheckVend(VAR VendorLedgerEntry : Record "Vendor Ledger Entry")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
