### ISSUE TITLE
[Event Request] Table 179 Reversal Entry - OnBeforeCheckVAT

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6549]
Please add a new publisher event to the function CheckVAT as follows:
	
```
LOCAL CheckVAT(VATEntry : Record "VAT Entry")
//>> Start New Publisher Call
OnBeforeCheckVAT(VATEntry);
//<< End New Publisher Call

IF VATEntry.Closed THEN
.
.
```

New Publisher Event:

```
Property IncludeSender: Yes
LOCAL [IntegrationEvent] OnBeforeCheckVAT(VAR VATEntry : Record "VAT Entry")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
