### ISSUE TITLE
[Enum Request] Table 27 Field 5419 "Replenishment System"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#655]
Please implement Field 5419 "Replenishment System" in table 27 and others (5700, as enum
Field 99000903 "Replenishment System"  in table 246  as well

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
