### ISSUE TITLE
[Event Change] Table 179 Reversal Entry - OnBeforeCheckGLAcc

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6550]
Please change the property **IncludeSender** of Event Publisher **OnBeforeCheckGLAcc** to **_Yes_**

This way we'll have access to the current record the publisher is fired from.

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
