### ISSUE TITLE
[Enum Request] Table 5767 "Warehouse Activity Line" Field 9"Source Document"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6553]
Reference to #6367, #6516, #6519, #6522 and #6524 

Please also change the field 9 "Source Document" of table 5767 "Warehouse Activity Line" from Option to Enum in order to make it extensible.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
