### ISSUE TITLE
[Enum Request] Table 7321 "Warehouse Shipment Line" Field 39 "Destination Type"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6555]
Please change the field 39 "Destination Type" of table 7321 "Warehouse Shipment Line" from Option to Enum in order to make it extensible.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
