### ISSUE TITLE
[Event Request] Table 7321 "Warehouse Shipment Line" - "CheckSourceDocLineQty" - Existing Event "OnCheckSourceDocLineQtyOnCaseSourceType" - New Parameter "QuantityBase"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6556]
Please add the local variable "QuantityBase" as new parameter to the existing event raiser and publisher "OnCheckSourceDocLineQtyOnCaseSourceType" in procedure "CheckSourceDocLineQty" of table 7321 "Warehouse Shipment Line".

The same as your code within the case, we need this variable to decide whether to throw a Fielderror.

OLD CODE:
```
    else
        OnCheckSourceDocLineQtyOnCaseSourceType(Rec, WhseQtyOutstandingBase, QtyOutstandingBase);
end;
```

NEW CODE:
```
    else
        OnCheckSourceDocLineQtyOnCaseSourceType(Rec, WhseQtyOutstandingBase, QtyOutstandingBase, QuantityBase);
end;
```

OLD PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnCheckSourceDocLineQtyOnCaseSourceType(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; WhseQtyOutstandingBase: Decimal; QtyOutstandingBase: Decimal)
begin
end;
```

NEW PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnCheckSourceDocLineQtyOnCaseSourceType(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; WhseQtyOutstandingBase: Decimal; QtyOutstandingBase: Decimal; QuantityBase: Decimal)
begin
end;
```

**Comment by StHillmann** [comment]
Additionally, "QtyOutstandingBase" has to be "var" in the Event publisher in order to make the following standard code work!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
