### ISSUE TITLE
[Enum Request] Table 27 Field 100 "Reserve"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#656]
Please implement Field 100 "Reserve" in table 27 and others as enum.
Field 96 "Reserve" in table 37, field 53 "Reserve" in table 901 as well (and others)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
