### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - procedure "PostSalesLine" - event "OnPostSalesLineOnBeforeInsertCrMemoLine" - Add new Parameters

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6564]
Due to handle our own logic, we need additional parameters for the standard event "OnPostSalesLineOnBeforeInsertCrMemoLine" in Codeunit 80 "Sales-Post", procedure "PostSalesLine".

OLD CODE:
```
end else begin
    OnPostSalesLineOnBeforeInsertCrMemoLine(SalesHeader, SalesLine, IsHandled);
    if not IsHandled then begin
```

NEW CODE:
```
end else begin
    OnPostSalesLineOnBeforeInsertCrMemoLine(SalesHeader, SalesLine, xSalesLine, SalesInvHeader, SalesCrMemoHeader, IsHandled); // start kvspsa - Added new parameters
    if not IsHandled then begin
```

OLD PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnPostSalesLineOnBeforeInsertCrMemoLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

NEW PUBLISHER:
```
[IntegrationEvent(false, false)]
// start kvspsa - New parameters added
local procedure OnPostSalesLineOnBeforeInsertCrMemoLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var xSalesLine: Record "Sales Line"; var SalesInvHeader: Record "Sales Invoice Header"; var SalesCrMemoHdr: Record "Sales Cr.Memo Header"; var IsHandled: Boolean)
// stop kvspsa
begin
end;
```

**Comment by StHillmann** [comment]
Sames as #6563 

Hi @RomanZanizdra you are totally right!
Our background processing has been one procedure which takes both parameters, but I already have divided it up.
@AlexanderYakunin 
Please remove "SalesInvHeader" as parameter and sorry for this...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
