### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - procedure "PostSalesLine" - event "OnAfterPostSalesLine" - Add new Parameters

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6565]
Due to handle our own logic, we need additional parameters for the standard event "OnAfterPostSalesLine" in Codeunit 80 "Sales-Post", procedure "PostSalesLine".

OLD CODE:
`OnAfterPostSalesLine(SalesHeader, SalesLine, SuppressCommit);`

NEW CODE:
`OnAfterPostSalesLine(SalesHeader, SalesLine, SalesInvLine, SalesCrMemoLine, xSalesLine, SuppressCommit);
`

OLD PUBLISHER:
```
[IntegrationEvent(false, false)]
local procedure OnAfterPostSalesLine(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; CommitIsSuppressed: Boolean)
begin
end;
```

NEW PUBLISHER:
```
[IntegrationEvent(false, false)]
// start kvspsa - Parameters added
local procedure OnAfterPostSalesLine(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var SalesInvLine: Record "Sales Invoice Line"; var SalesCrMemoLine: Record "Sales Cr.Memo Line"; var xSalesLine: Record "Sales Line"; CommitIsSuppressed: Boolean)
// stop kvspsa
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
