### ISSUE TITLE
[EventRequest] Report 202 "Sales Document - Test" - existing event "OnAfterCreateDimTableIDs" - change reference-type

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6568]
Please change the reference-type of the parameters "TableID" and "No" at event "OnAfterCreateDimTableIDs" of Report 202 "Sales Document - Test".

OLD CODE:
```
[IntegrationEvent(false, false)]
local procedure OnAfterCreateDimTableIDs(var SalesLine: Record "Sales Line"; TableID: array[10] of Integer; No: array[10] of Code[20])
begin
end;
```

NEW CODE:
```
[IntegrationEvent(false, false)]
local procedure OnAfterCreateDimTableIDs(var SalesLine: Record "Sales Line"; var TableID: array[10] of Integer; var No: array[10] of Code[20])
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
