### ISSUE TITLE
Vendor "Gen. Bus. Posting Group" is required when it shouldn't

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#6569]
In the OnValidate trigger for "Buy-from Vendor No." in Purchase Header (T38) the Vendor's "Gen. Bus. Posting Group" is unconditionally required in v16.0:
```
GetVend("Buy-from Vendor No.");
Vend.CheckBlockedVendOnDocs(Vend, false);
GLSetup.Get();
if GLSetup.Get then
    Vend.TestField("Gen. Bus. Posting Group");
OnAfterCheckBuyFromVendor(Rec, xRec, Vend);
```
I believe the code should be as follows (based on the obsolescence of GLSetup."VAT In Use"):
```
var
    ApplicationAreaMgmtFacade: Codeunit "Application Area Mgmt. Facade";
```
```
GetVend("Buy-from Vendor No.");
Vend.CheckBlockedVendOnDocs(Vend, false);
if ApplicationAreaMgmtFacade.IsVATEnabled() then
    Vend.TestField("Gen. Bus. Posting Group");
OnAfterCheckBuyFromVendor(Rec, xRec, Vend);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
