### ISSUE TITLE
[Enum Request] Table 27 field 99000773 "Order Tracking Policy"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#657]
Please implement field 99000773 "Order Tracking Policy" in table 27 and others as enum.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
