### ISSUE TITLE
[Event Request] Page 5077 Create Interaction - OnOpenPageOnAfterSetIsContactEditable

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6571]
Requesting a new Event Publisher on Page 5077 Create Interaction

Event
`OnOpenPageOnAfterSetIsContactEditable(VAR Rec : Record Segment Line; VAR IsContactEditable : Boolean)`

**Code**
## OnOpenPage()
```
CampaignDescriptionEditable := FALSE;
OpportunityDescriptionEditable := FALSE;
IsContactEditable := (GETFILTER("Contact No.") = '') AND (GETFILTER("Contact Company No.") = '');
```
**>>> New Code**
```
OnOpenPageOnAfterSetIsContactEditable(Rec, IsContactEditable)
```
**<<< New Code**
```
UpdateUIFlags;

IF SalesPurchPerson.GET(GETFILTER("Salesperson Code")) THEN
  SalespersonCodeEditable := FALSE;

AttachmentReload;

IsFinished := FALSE;

CurrPage.UPDATE(FALSE);
```

In Our Solution we set the Global variable IsContactEditable on some more scenarios and so we need to have the possibility to do so. Please add the requested publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
