### ISSUE TITLE
[Enum Request] Table 279/280 field 1 "Table Name"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#658]
Please implement field 1 "Table Name" in table 279/280 as enum

**Comment by frivadulla** [comment]
Is this going to be done? We need the same need ASAP.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
