### ISSUE TITLE
[Event Request] Codeunit 394 "FinChrgMemo-Make" - Code() - Additional filters on CustLedgEntry

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6581]
Dear BaseApp team,

In our vertical solution we need the possibility to set additional filters on Cust.Ledger Entry when creating Finance Charge Memos. The previously added events in the MakeLines function are very useful, but we also need to be able to set the filters already in the Code function.

Suggested Code in codeunit 394 "FinChrgMemo-Make":

procedure "Code"(): Boolean
    begin
        with FinChrgMemoHeader do
            if "No." <> '' then begin
                HeaderExists := true;
                TestField("Customer No.");
                Cust.Get("Customer No.");
                TestField("Document Date");
                TestField("Fin. Charge Terms Code");
                FinChrgMemoHeaderReq := FinChrgMemoHeader;
                FinChrgMemoLine.SetRange("Finance Charge Memo No.", "No.");
                FinChrgMemoLine.DeleteAll();
            end;

        OverDue := false;

        with Cust do begin
            TestField("Fin. Charge Terms Code");
            if HeaderExists then
                FinChrgMemoCheck(FinChrgMemoHeader."Currency Code")
            else begin
                if Blocked = Blocked::All then
                    exit(false);
                Currency.DeleteAll();
                TempCurrency.DeleteAll();
                CustLedgEntry2.CopyFilters(CustLedgEntry);
                CustLedgEntry.SetCurrentKey("Customer No.");
                CustLedgEntry.SetRange("Customer No.", "No.");
                //>>L365
                OnAfterSetCustLedgerEntryFilterL365(CustLedgEntry); 
                //<<L365
                if CustLedgEntry.Find('-') then
                    repeat
                        if CustLedgEntry."On Hold" = '' then begin
                            Currency.Code := CustLedgEntry."Currency Code";
                            if Currency.Insert() then;
                        end;
                    until CustLedgEntry.Next = 0;
...

[IntegrationEvent(false, false)]
local procedure OnAfterSetCustLedgerEntryFilterL365(VAR CustLedgerEntry: Record "Cust. Ledger Entry")
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
