### ISSUE TITLE
Using TranslationImplementation.Show insert records with TableID=0

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6583]
from BC160 using the new Translation codeunit
TranslationImplementation.Show(myrec,myfieldid) für own tables, the tableID is not set during inserting records on the page "Translation". So following TranslationImplementation.Showforallrecords(myTableID,myFieldID) will not return the correct value.

I assume that TableID is missing:

procedure Show(RecVariant: Variant; FieldId: Integer)
    var
        Translation: Record Translation;
        TranslationPage: Page Translation;
        SystemID: Guid;
        TableNo: Integer;
    begin
        GetSystemIdFromVariant(RecVariant, SystemID, TableNo);
        Translation.SetRange("System ID", SystemID);
        //+++++++++++++++++++++++++++++++++
        Translation.SetRange("Table ID", TableNo);
        //---------------------------------------------------------
        Translation.SetRange("Field ID", FieldId);
        TranslationPage.SetCaption(GetRecordIdCaptionFromVariant(RecVariant));
        TranslationPage.SetTableView(Translation);
        TranslationPage.Run();
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting! We'll of course get that fixed.

**Comment by DuttaSoumya** [comment]
Hi @GuntherGebauer 

You could, of course be, sure if the record is really there by making a call to the following,
procedure Get(RecVariant: Variant; FieldId: Integer; LanguageId: Integer): Text

You may also have noted in the documentation that translations will not be added for temporary records. 

Cheers.

**Comment by GuntherGebauer** [comment]
Hi @DuttaSoumya ,
yes, I have seen that the Set procedure inserts the records correctly with tableNo. And no, I am not using temporary records.
The error is the Standard call to tranlsation.show which allows to insert manually records on the page and the later call to Translation.showforallrecords will not Show those manually inserted records.
So i cannot call the set procedure because Show does the insert internally on the page

**Comment by DuttaSoumya** [comment]
We shall be fixing this problem in a future release. We shall disallow saving translations with Table ID = 0, as this can give intended results.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by darjoo** [comment]
Hi @GuntherGebauer,

Would it be possible for you provide us with a small test project to verify the issue? I'm unsure as to whether I understood the issue correctly and whether my colleague's fix addressed the issue.

-Darrick

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by GuntherGebauer** [comment]
pageextension 5040730 "M365 FB Return Reasons" extends "Return Reasons"
{
    actions
    {
        addlast(Navigation)
        {
            action(M365Translation)
            {
                ApplicationArea = All;
                Caption = 'translationMgmt.Show';
                Image = Translation;
                Promoted = true;
                PromotedCategory = Process;
                ToolTip = 'translationMgmt.Show';
                trigger OnAction()
                var
                    translationMgmt: Codeunit Translation;
                    recordVariant: Variant;
                begin
                    recordVariant := Rec;
                    translationMgmt.Show(recordVariant, FieldNo(Code));
                end;
            }
            action(M365TranslationforAll)
            {
                ApplicationArea = All;
                Caption = 'translationMgmt.ShowForAllRecords';
                Image = Translation;
                Promoted = true;
                PromotedCategory = Process;
                ToolTip = 'translationMgmt.ShowForAllRecords';
                trigger OnAction()
                var
                    translationMgmt: Codeunit Translation;
                    recordVariant: Variant;
                begin
                    recordVariant := Rec;
                    translationMgmt.ShowForAllRecords(Database::"Return Reason", FieldNo(Code));
                end;
            }
        }
    }
}


Run the Page and add translations for a ReturnreasonCode calling the Action "Translation". There you can add different translations for your ReturnReason for different languages.

Call the Action "TranslationForAllRecords" again, the translated values are not shown.

Clear the filter on "Table ID", then you see the translated values for your ReturnReasons.

You can check that also directly in SQLServer in table "Translation", to see that TableID is empty.

![image](https://user-images.githubusercontent.com/38500557/82436019-74498000-9a95-11ea-818c-5d9c7ace2080.png)

![image](https://user-images.githubusercontent.com/38500557/82436975-f1c1c000-9a96-11ea-9314-f6811b0f3bec.png)

**Comment by darjoo** [comment]
Thanks for providing that. I will take a look into it.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
