### ISSUE TITLE
Table 207 OnValidate Work Type Code

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#6588]
We don't need the Resource Unit of Measure in all occasions and therefor we have modified the table 207 with a small IF ... THEN construction on two places. 

Herewith the request to adopt this is in the Base App
![image](https://user-images.githubusercontent.com/32514251/77580866-fd509a80-6edc-11ea-9dc6-463c9a8f68ab.png)

and 
![image](https://user-images.githubusercontent.com/32514251/77580989-325ced00-6edd-11ea-9ea0-0079f1e33a7e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
