### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - Existing Event "OnBeforeDeleteSalesLines" - Add Handled-Pattern

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6589]
Dear ALAppExtensions team,

We need to handle the logic of procedure "DeleteSalesLines" in table 36 "Sales Header" by ourselves.

To work properly, our solution needs a parameter Handled added to the event OnBeforeDeleteSalesLines.

OLD CODE: 

    local procedure DeleteSalesLines()
    var
        ReservMgt: Codeunit "Reservation Management";
    begin
        OnBeforeDeleteSalesLines(SalesLine);

        if SalesLine.FindSet then begin
            ReservMgt.DeleteDocumentReservation(DATABASE::"Sales Line", "Document Type", "No.", GetHideValidationDialog);
            repeat
                SalesLine.SuspendStatusCheck(true);
                SalesLine.Delete(true);
            until SalesLine.Next = 0;
        end;
    end;

NEW CODE: 

    local procedure DeleteSalesLines()
    var
        ReservMgt: Codeunit "Reservation Management";
	IsHandled: Boolean; //new variable
    begin
	// start new code with handled added
        IsHandled := false;
	OnBeforeDeleteSalesLines(SalesLine, IsHandled);

	if IsHandled then 
	  exit;
	// stop new code 

        if SalesLine.FindSet then begin
            ReservMgt.DeleteDocumentReservation(DATABASE::"Sales Line", "Document Type", "No.", GetHideValidationDialog);
            repeat
                SalesLine.SuspendStatusCheck(true);
                SalesLine.Delete(true);
            until SalesLine.Next = 0;
        end;
    end;

OLD PUBLISHER: 

  [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteSalesLines(var SalesLine: Record "Sales Line");
    begin
    end;

NEW PUBLISHER 

  [IntegrationEvent(false, false)]
//start new code -- parameter added
    local procedure OnBeforeDeleteSalesLines(var SalesLine: Record "Sales Line"; var IsHandled: Boolean);
//stop new code
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
