### ISSUE TITLE
[Event Request] Table 38 - Purchase Header - DeletePurchaseLines

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6590]
Dear ALAppExtensions Team:

Through this issue we would like to request an event publisher OnBeforeDeletePurchaseLines to be added to the table 38 "Purchase Header" with the following signature:

[IntegrationEvent(false, false)]
local procedure OnBeforeDeletePurchaseLines(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;

with **VAR** parameters PurchaseLine and IsHandled.

this event would be called in the procedure DeletePurchaseLines as follows:

local procedure DeletePurchaseLines()
var
  ReservMgt: Codeunit "Reservation Management";
  // start new code
  IsHandled: Boolean;
  // stop new code
begin
   //start new code -- new event added
   IsHandled := false;

   OnBeforeDeletePurchaseLines(PurchLine,IsHandled);

   if IsHandled then
     exit;
   //stop new code

   if PurchLine.FindSet() then begin
     ReservMgt.DeleteDocumentReservation(DATABASE::"Purchase Line", "Document Type", "No.", GetHideValidationDialog);
     repeat
       PurchLine.SuspendStatusCheck(true);
       PurchLine.Delete(true);
     until PurchLine.Next() = 0;
   end;
end;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
