### ISSUE TITLE
[Event Request] Table 38 - "Purchase Header" - existing event "OnUpdatePurchLinesByFieldNoOnBeforeValidateFields" add parameter ChangedFieldNo

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6591]
Dear ALAppExtensions Team:

Through this issue we would like to request the addition of the parameter ChangedFieldNo to the event publisher OnUpdatePurchLinesByFieldNoOnBeforeValidateFields in the table 38 "Purchase Header". This way, our solution could additional code dependending on the field calling the procedure "UpdatePurchLinesByFieldNo".

The code in the procedure "UpdatePurchLinesByFieldNo" would be modified as follows:

OLD CODE:

PurchLine.Reset();
PurchLine.SetRange("Document Type", "Document Type");
PurchLine.SetRange("Document No.", "No.");
if PurchLine.FindSet() then
  repeat
    xPurchLine := PurchLine;
    OnUpdatePurchLinesByFieldNoOnBeforeValidateFields(PurchLine, xPurchLine);
    case ChangedFieldNo of
...

NEW CODE:

PurchLine.Reset();
PurchLine.SetRange("Document Type", "Document Type");
PurchLine.SetRange("Document No.", "No.");
if PurchLine.FindSet() then
  repeat
    xPurchLine := PurchLine;

    //start new code  -- add ChangedFieldNo	
    OnUpdatePurchLinesByFieldNoOnBeforeValidateFields(PurchLine, xPurchLine,ChangedFieldNo);
    // stop new code
    
    case ChangedFieldNo of
...

OLD PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnUpdatePurchLinesByFieldNoOnBeforeValidateFields(var PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line")
begin
end;

NEW PUBLISHER
[IntegrationEvent(false, false)]
//start new code -- add parameter
local procedure OnUpdatePurchLinesByFieldNoOnBeforeValidateFields(var PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line"; ChangedFieldNo: Integer)
//Stop new code
begin
end;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
