### ISSUE TITLE
[Event Request] Table 5740 - "Transfer Header" - new event "OnBeforeTransferRouteCalcReceiptDate_ShipmentDate" and "OnBeforeTransferRouteCalcShipmentDate_ReceiptDate"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6592]
Dear ALAppExtensions Team:

Through this issue we would like to request two new event publishers in table 5740 "Transfer Header".

We need to prevent the calculation of Receipt y shipment date in fields "Shipment date" and "Receipt date", so we need two new events:

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferRouteCalcReceiptDate_ShipmentDate(var IsHandled: Boolean)
begin
end;

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferRouteCalcShipmentDate_ReceiptDate(var IsHandled: Boolean)
begin
end;

The trigger Onvalidate in fields "Shipment Date" and "Receipt Date" would be modified as follows:

OLD CODE: 

   field(21; "Shipment Date"; Date)
        {
            Caption = 'Shipment Date';

            trigger OnValidate()
            begin
                TestStatusOpen;
                TransferRoute.CalcReceiptDate(
                  "Shipment Date",
                  "Receipt Date",
                  "Shipping Time",
                  "Outbound Whse. Handling Time",
                  "Inbound Whse. Handling Time",
                  "Transfer-from Code",
                  "Transfer-to Code",
                  "Shipping Agent Code",
                  "Shipping Agent Service Code");
                UpdateTransLines(Rec, FieldNo("Shipment Date"));
            end;
        }

  field(22; "Receipt Date"; Date)
        {
            Caption = 'Receipt Date';

            trigger OnValidate()
            begin
                TestStatusOpen;
                TransferRoute.CalcShipmentDate(
                  "Shipment Date",
                  "Receipt Date",
                  "Shipping Time",
                  "Outbound Whse. Handling Time",
                  "Inbound Whse. Handling Time",
                  "Transfer-from Code",
                  "Transfer-to Code",
                  "Shipping Agent Code",
                  "Shipping Agent Service Code");
                UpdateTransLines(Rec, FieldNo("Receipt Date"));
            end;
        }

NEW CODE:

   field(21; "Shipment Date"; Date)
        {
            Caption = 'Shipment Date';

            trigger OnValidate()
	    var
	      //Start new code -- add variable	 
	      IsHandled: Boolean;
             //Stop new code 	
            begin
                TestStatusOpen;
                
                //start new code
                IsHandled := false;
                OnBeforeTransferRouteCalcReceiptDate_ShipmentDate(IsHandled);
	        if not IsHandled then
	        //Stop new code
		
                TransferRoute.CalcReceiptDate(
                  "Shipment Date",
                  "Receipt Date",
                  "Shipping Time",
                  "Outbound Whse. Handling Time",
                  "Inbound Whse. Handling Time",
                  "Transfer-from Code",
                  "Transfer-to Code",
                  "Shipping Agent Code",
                  "Shipping Agent Service Code");

                UpdateTransLines(Rec, FieldNo("Shipment Date"));
            end;
        }

    field(22; "Receipt Date"; Date)
        {
            Caption = 'Receipt Date';

            trigger OnValidate()
            var
	      //Start new code -- add variable	 
	      IsHandled: Boolean;
             //Stop new code 	
            begin
                TestStatusOpen;

                //start new code
                IsHandled := false;
                OnBeforeTransferRouteCalcReceiptDate_ShipmentDate(IsHandled);
	        if not IsHandled then
	        //Stop new code	

                TransferRoute.CalcShipmentDate(
                  "Shipment Date",
                  "Receipt Date",
                  "Shipping Time",
                  "Outbound Whse. Handling Time",
                  "Inbound Whse. Handling Time",
                  "Transfer-from Code",
                  "Transfer-to Code",
                  "Shipping Agent Code",
                  "Shipping Agent Service Code");

                UpdateTransLines(Rec, FieldNo("Receipt Date"));
            end;
        }

Thanks!

**Comment by mcarmenvalera** [comment]
Sorry, 

the code in field "Receipt Date" should be:

field(22; "Receipt Date"; Date)
    {
        Caption = 'Receipt Date';

        trigger OnValidate()
        var
      //Start new code -- add variable	 
      IsHandled: Boolean;
         //Stop new code 	
        begin
            TestStatusOpen;

            //start new code
            IsHandled := false;
            **OnBeforeTransferRouteCalcShipmentDate_ReceiptDate(IsHandled);**
        if not IsHandled then
        //Stop new code	

            TransferRoute.CalcShipmentDate(
              "Shipment Date",
              "Receipt Date",
              "Shipping Time",
              "Outbound Whse. Handling Time",
              "Inbound Whse. Handling Time",
              "Transfer-from Code",
              "Transfer-to Code",
              "Shipping Agent Code",
              "Shipping Agent Service Code");

            UpdateTransLines(Rec, FieldNo("Receipt Date"));
        end;
    }

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
