### ISSUE TITLE
[Event Request] Table 5740 - "Transfer Header" - new event "OnBeforeDeleteTransferLines" 

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6593]
Dear ALAppExtensions Team:

Through this issue we would like to request a new event publisher in table 5740 "Transfer Header".

In order to work properly, our solution needs to manage by itself the deletion of the transfer lines. We think the best way to approach this would be adding an event before deleting transfer lines in the OnDelete trigger with a handled patron. 

The code of the trigger OnDelete in table "Transfer Header" would be modified as follows:

OLD CODE: 

    trigger OnDelete()
    var
        TransLine: Record "Transfer Line";
        InvtCommentLine: Record "Inventory Comment Line";
        ReservMgt: Codeunit "Reservation Management";
    begin
        TestField(Status, Status::Open);

        WhseRequest.SetRange("Source Type", DATABASE::"Transfer Line");
        WhseRequest.SetRange("Source No.", "No.");
        if not WhseRequest.IsEmpty then
            WhseRequest.DeleteAll(true);

        ReservMgt.DeleteDocumentReservation(DATABASE::"Transfer Line", 0, "No.", HideValidationDialog);

        TransLine.SetRange("Document No.", "No.");
        TransLine.DeleteAll(true);

        InvtCommentLine.SetRange("Document Type", InvtCommentLine."Document Type"::"Transfer Order");
        InvtCommentLine.SetRange("No.", "No.");
        InvtCommentLine.DeleteAll();
    end;

NEW CODE:

    trigger OnDelete()
    var
        TransLine: Record "Transfer Line";
        InvtCommentLine: Record "Inventory Comment Line";
        ReservMgt: Codeunit "Reservation Management";
	//Start new code -- add variable	 
	IsHandled: Boolean;
        //Stop new code 
    begin
        TestField(Status, Status::Open);

        WhseRequest.SetRange("Source Type", DATABASE::"Transfer Line");
        WhseRequest.SetRange("Source No.", "No.");
        if not WhseRequest.IsEmpty then
            WhseRequest.DeleteAll(true);

        ReservMgt.DeleteDocumentReservation(DATABASE::"Transfer Line", 0, "No.", HideValidationDialog);

        TransLine.SetRange("Document No.", "No.");

        //start new code
        IsHandled := false;
        OnBeforeDeleteTransferLines(TransLine, IsHandled);
	if not IsHandled then
	//Stop new code	
          TransLine.DeleteAll(true);

        InvtCommentLine.SetRange("Document Type", InvtCommentLine."Document Type"::"Transfer Order");
        InvtCommentLine.SetRange("No.", "No.");
        InvtCommentLine.DeleteAll();
    end;

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteTransferLines(var TransferLine: Record "Transfer Line"; var IsHandled: Boolean)
begin
end;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
