### ISSUE TITLE
[Event Request] Table 5741 - "Transfer Lines" - new events "OnBeforeTransferRouteCalcReceiptDate_ShipmentDate" and "OnBeforeTransferRouteCalcShipmentDate_ReceiptDate" 

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6594]
Dear ALAppExtensions Team:

Through this issue we would like to request two new event publishers in table 5741 "Transfer Line".

We need to prevent the calculation of Receipt y shipment date in fields "Shipment date" and "Receipt date", so we need two new events (I have asked for two similar events for table Transfer Header):

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferRouteCalcReceiptDate_ShipmentDate(var IsHandled: Boolean)
begin
end;

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferRouteCalcShipmentDate_ReceiptDate(var IsHandled: Boolean)
begin
end;

The trigger Onvalidate in fields "Shipment Date" and "Receipt Date" would be modified as follows:

OLD CODE:

        field(38; "Shipment Date"; Date)
        {
            Caption = 'Shipment Date';

            trigger OnValidate()
            begin
                if CurrFieldNo <> 0 then
                    TestStatusOpen;
                TransferRoute.CalcReceiptDate("Shipment Date", "Receipt Date",
                  "Shipping Time", "Outbound Whse. Handling Time", "Inbound Whse. Handling Time",
                  "Transfer-from Code", "Transfer-to Code", "Shipping Agent Code", "Shipping Agent Service Code");
                CheckItemAvailable(FieldNo("Shipment Date"));
                DateConflictCheck;
            end;
        }
        field(39; "Receipt Date"; Date)
        {
            Caption = 'Receipt Date';

            trigger OnValidate()
            begin
                if CurrFieldNo <> 0 then
                    TestStatusOpen;
                TransferRoute.CalcShipmentDate("Shipment Date", "Receipt Date",
                  "Shipping Time", "Outbound Whse. Handling Time", "Inbound Whse. Handling Time",
                  "Transfer-from Code", "Transfer-to Code", "Shipping Agent Code", "Shipping Agent Service Code");
                CheckItemAvailable(FieldNo("Shipment Date"));
                DateConflictCheck;
            end;
        }

NEW CODE:

        field(38; "Shipment Date"; Date)
        {
            Caption = 'Shipment Date';

            trigger OnValidate()
            //Start new code -- add variable	
            var
              IsHandled: Boolean;
            //Stop new code 
            begin
                if CurrFieldNo <> 0 then
                    TestStatusOpen;
        
                //start new code
                IsHandled := false;
                OnBeforeTransferRouteCalcReceiptDate_ShipmentDate(IsHandled);
                if not IsHandled then
                //Stop new code

                 TransferRoute.CalcReceiptDate("Shipment Date", "Receipt Date",
                  "Shipping Time", "Outbound Whse. Handling Time", "Inbound Whse. Handling Time",
                  "Transfer-from Code", "Transfer-to Code", "Shipping Agent Code", "Shipping Agent Service Code");
                CheckItemAvailable(FieldNo("Shipment Date"));
                DateConflictCheck;
            end;
        }
        field(39; "Receipt Date"; Date)
        {
            Caption = 'Receipt Date';

            trigger OnValidate()
              //Start new code -- add variable	 
              IsHandled: Boolean;
              //Stop new code 
            begin
                if CurrFieldNo <> 0 then
                    TestStatusOpen;

                //start new code
                IsHandled := false;
                OnBeforeTransferRouteCalcShipmentDate_ReceiptDate(IsHandled);
                if not IsHandled then
                //Stop new code

                TransferRoute.CalcShipmentDate("Shipment Date", "Receipt Date",
                  "Shipping Time", "Outbound Whse. Handling Time", "Inbound Whse. Handling Time",
                  "Transfer-from Code", "Transfer-to Code", "Shipping Agent Code", "Shipping Agent Service Code");
                CheckItemAvailable(FieldNo("Shipment Date"));
                DateConflictCheck;
            end;
        }

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
