### ISSUE TITLE
[Event Request] Table 6651 - "Return Shipment Line" - new event "OnBeforeInsertInvLineFromRetShptLineBeforeInsertTextLine"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6598]
Dear ALAppExtensions Team:

Through this issue we would like to request a new event publisher in table 6651 "Return Shipment Line".

This event would be similar to the event in table "Purch. Rcpt. Line", procedure "InsertInvLineFromRcptLine"

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertInvLineFromRetShptLineBeforeInsertTextLine(var RetShptLn: record "Return Shipment Line"; var PurchLine: Record "Purchase Line"; var NextLineNo: Integer; var Handled: Boolean)
begin
end;

The code in procedure "InsertInvLineFromRetShptLine" in table 6651 "Return Shipment Line" would be modified as follows:

OLD CODE:

....
   if PurchHeader."No." <> TempPurchLine."Document No." then
            PurchHeader.Get(TempPurchLine."Document Type", TempPurchLine."Document No.");

        if PurchLine."Return Shipment No." <> "Document No." then begin
            PurchLine.Init();
            PurchLine."Line No." := NextLineNo;
            PurchLine."Document Type" := TempPurchLine."Document Type";
            PurchLine."Document No." := TempPurchLine."Document No.";
            PurchLine.Description := StrSubstNo(Text000, "Document No.");
            PurchLine.Insert();
            NextLineNo := NextLineNo + 10000;
        end;

        TransferOldExtLines.ClearLineNumbers;

....

NEW CODE:

         if PurchHeader."No." <> TempPurchLine."Document No." then
            PurchHeader.Get(TempPurchLine."Document Type", TempPurchLine."Document No.");

        if PurchLine."Return Shipment No." <> "Document No." then begin
            PurchLine.Init();
            PurchLine."Line No." := NextLineNo;
            PurchLine."Document Type" := TempPurchLine."Document Type";
            PurchLine."Document No." := TempPurchLine."Document No.";
            PurchLine.Description := StrSubstNo(Text000, "Document No.");

	    //start new code
	    IsHandled := False;
            OnBeforeInsertInvLineFromRetShptLineBeforeInsertTextLine(Rec, PurchLine, NextLineNo, IsHandled);
	    if not IsHandled then begin
	    //stop new code

            PurchLine.Insert();
            NextLineNo := NextLineNo + 10000;
	    //star new code
            end;
            //stop new code
        end;

        TransferOldExtLines.ClearLineNumbers;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by mcarmenvalera** [comment]
Dear C/AL developers,

I'm revising the code in cu1 and this change in code it is not implemented. Could it be added in cu2? We are in process of upgrading a customer database and we this event asap.

Thanks in advance!
