### ISSUE TITLE
[Event Request] Table 7317 - "Warehouse Receipt Line" - new event "OnDeleteQtyToReceiveOnBeforeModify"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6602]
Dear ALAppExtensions Team:

We would like to request a new event publisher in table 7317 "Warehouse Receipt Line". This event is needed in order to modify values of fields of our solution.

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnDeleteQtyToReceiveOnBeforeModify(var WhseRcptLn: Record "Warehouse Receipt Line")
begin
end;

The parameter WhseRcptLn is referenced as VAR.

The code in procedure "DeleteQtyToReceive" in table 7317 "Warehouse Receipt Line" would be modified as follows:

OLD CODE:

    procedure DeleteQtyToReceive(var WhseReceiptLine: Record "Warehouse Receipt Line")
    begin
        with WhseReceiptLine do begin
            if Find('-') then
                repeat
                    Validate("Qty. to Receive", 0);
                    Modify;
                until Next = 0;
        end;
    end;

NEW CODE:

    procedure DeleteQtyToReceive(var WhseReceiptLine: Record "Warehouse Receipt Line")
    begin
        with WhseReceiptLine do begin
            if Find('-') then
                repeat
                    Validate("Qty. to Receive", 0);
                    
                    //start new code
	            OnDeleteQtyToReceiveOnBeforeModify(WhseReceiptLine);
                    //stop new code
                    Modify;
                until Next = 0;
        end;
    end;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
