### ISSUE TITLE
[Event Request] Table 7321 - "Warehouse Shipment Line" - new event "OnDeleteQtyToHandleOnBeforeModify"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6603]
Dear ALAppExtensions Team:

We would like to request a new event publisher in table 7321 - "Warehouse Shipment Line". This event is needed in order to modify values of fields of our solution.

NEW PUBLISHER
[IntegrationEvent(false, false)]
local procedure OnDeleteQtyToHandleOnBeforeModify(var WhseShptLn: Record "Warehouse Shipment Line")
begin
end;

The parameter WhseShptLn is referenced as VAR.

The code in procedure "DeleteQtyToHandle" in table 7321 "Warehouse Shipment Line" would be modified as follows:

OLD CODE:

    procedure DeleteQtyToHandle(var WhseShptLine: Record "Warehouse Shipment Line")
    begin
        with WhseShptLine do begin
            if Find('-') then
                repeat
                    Validate("Qty. to Ship", 0);
                    Modify;
                until Next = 0;
        end;
    end;

NEW CODE:

    procedure DeleteQtyToHandle(var WhseShptLine: Record "Warehouse Shipment Line")
    begin
        with WhseShptLine do begin
            if Find('-') then
                repeat
                    Validate("Qty. to Ship", 0); 
                    
                    //start new code
	            OnDeleteQtyToHandleOnBeforeModify(WhseShptLine);
                    //stop new code

                    Modify;
                until Next = 0;
        end;
    end;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
