### ISSUE TITLE
[Event Request] Table 36 Sales Header - handled pattern for UpdateBillToCust

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6604]
Dear BaseApp Team,

In our vertical we need an alternate handling of contacts on sales headers, to be able to send invoices to different recipients. To do that, we need the Handled pattern for the function UpdateBillToCust

Requested code in Table 36 "Sales Header":

local procedure UpdateBillToCust(ContactNo: Code[20])
    var
        ContBusinessRelation: Record "Contact Business Relation";
        Cust: Record Customer;
        Cont: Record Contact;
        CustTemplate: Record "Customer Template";
        SearchContact: Record Contact;
        ContactBusinessRelationFound: Boolean;
        IsHandled: Boolean;
    begin
        //>>L365
        IsHandled := false;
        OnBeforeUpdateBillToCustL365(Rec,ContactNo,IsHandled);
        if IsHandled then 
            exit;
        //<<L365

        if not Cont.Get(ContactNo) then begin
            "Bill-to Contact" := '';
            exit;
        end;
...

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateBillToCustL365(var SalesHeader: Record "Sales Header"; ContactNo: Code[20]; var Handled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
