### ISSUE TITLE
[event request] Codeunit 22 "Item Jnl.-Post Line" add parameter to OnBeforeInsertItemLedgEntry

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6605]
Dear ALAppExtensions Team:

Could you add to the event publisher "OnBeforeInsertItemLedgEntry" in codeunit 22 "Item Jnl.-Post Line" a new parameter OldItemLedgEntry?

OLD PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnBeforeInsertItemLedgEntry(var ItemLedgerEntry: Record "Item Ledger Entry"; ItemJournalLine: Record "Item Journal Line"; TransferItem: Boolean)
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnBeforeInsertItemLedgEntry(var ItemLedgerEntry: Record "Item Ledger Entry"; ItemJournalLine: Record "Item Journal Line"; TransferItem: Boolean; OldItemLedgerEntry: Record "Item Ledger Entry") //new parameter added
begin
end;

The code in procedure "InsertItemLedgEntry" in codeunit 22 would be modified as follows:

OLD CODE:
....
  OnBeforeInsertItemLedgEntry(ItemLedgEntry, ItemJnlLine, TransferItem);
  ItemLedgEntry.Insert(true);
  OnAfterInsertItemLedgEntry(ItemLedgEntry, ItemJnlLine, ItemLedgEntryNo, ValueEntryNo, ItemApplnEntryNo);
.....

NEW CODE:
....

  // start modification code
  OnBeforeInsertItemLedgEntry(ItemLedgEntry, ItemJnlLine, TransferItem, OldItemLedgEntry);
  // stop modification code

  ItemLedgEntry.Insert(true);
  OnAfterInsertItemLedgEntry(ItemLedgEntry, ItemJnlLine, ItemLedgEntryNo, ValueEntryNo, ItemApplnEntryNo);
.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
