### ISSUE TITLE
[Event Request] page 5856 "Get Post.Doc - P.RcptLn Sbfrm" - OnBeforeIsShowRec - More Parameters

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6607]
see #6489 

Unfortunately we need a correction of the event raiser and publisher.
Please extend it by 3 new parameters which are needed in order to set the global variables.

Old Event-Raiser (Issue 6489):
`OnBeforeIsShowRec(PurchRcptLine2, RevQtyFilter, ReturnValue, IsHandled);`

New Event-Raiser:
`OnBeforeIsShowRec(PurchRcptLine2, RevQtyFilter, ReturnValue, RemainingQty, RevUnitCostLCY, FillExactCostReverse, IsHandled);
`

Old Event-Publisher:
```
[IntegrationEvent(false, false)] 
local procedure OnBeforeIsShowRec(PurchRcptLine: Record "Purch. Rcpt. Line"; var RevQtyFilter: Boolean; var ReturnValue: Boolean; var IsHandled: Boolean);
begin
end;
```

New Event-Publisher:
```
[IntegrationEvent(false, false)] 
local procedure OnBeforeIsShowRec(PurchRcptLine: Record "Purch. Rcpt. Line"; var RevQtyFilter: Boolean; var ReturnValue: Boolean; var RemainingQty: Decimal; var RevUnitCostLCY: Decimal; ExactCostReverse: Boolean; var IsHandled: Boolean);
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
