### ISSUE TITLE
[Event Request] Codeunit 5601 "FA Insert G/L Account" - "OnInsertBufferBalAccOnAfterAssignFromFAPostingGrAcc" - Change reference type

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#6609]
Please change the reference type of parameter "FAGLPostBuf" at event publisher "OnInsertBufferBalAccOnAfterAssignFromFAPostingGrAcc" in Codeunit 5601 "FA Insert G/L Account" to "var".

Old Publisher:
`local procedure OnInsertBufferBalAccOnAfterAssignFromFAPostingGrAcc(FAAllocation: Record "FA Allocation"; FAGLPostBuf: Record "FA G/L Posting Buffer")`

New Publisher:
```
// start kvspsa - Event Publisher - Referencetype of parameter "FAGLPostBuf" changed
local procedure OnInsertBufferBalAccOnAfterAssignFromFAPostingGrAcc(FAAllocation: Record "FA Allocation"; var FAGLPostBuf: Record "FA G/L Posting Buffer")
// stop kvspsa
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
