### ISSUE TITLE
[event request] Codeunit 80 "Sales-Post" add parameter to event OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6611]
Dear ALAppExtensions Team:

Could you add to the event publisher "OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify" in codeunit 80 "Sales-Post" a new parameter SalesLine?

Our solution works with additional units of measure and needs to calculate extended fields based in extended fields in salesline.

OLD PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify(SalesHeader: Record "Sales Header"; var ReturnRcptLine: Record "Return Receipt Line")
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify(SalesHeader: Record "Sales Header"; var ReturnRcptLine: Record "Return Receipt Line"; SalesLine: Record "Sales Line") //New parameter
begin
end;

The code in procedure "PostItemTrackingForReceipt" in Codeunit 80 would be modified as follows:

....

  RemQtyToBeInvoiced := RemQtyToBeInvoiced - QtyToBeInvoiced;
  RemQtyToBeInvoicedBase := RemQtyToBeInvoicedBase - QtyToBeInvoicedBase;
  ReturnRcptLine."Quantity Invoiced" :=
                      ReturnRcptLine."Quantity Invoiced" + QtyToBeInvoiced;
  ReturnRcptLine."Qty. Invoiced (Base)" :=
                      ReturnRcptLine."Qty. Invoiced (Base)" + QtyToBeInvoicedBase;
  ReturnRcptLine."Return Qty. Rcd. Not Invd." :=
                      ReturnRcptLine.Quantity - ReturnRcptLine."Quantity Invoiced";

  OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify(SalesHeader, ReturnRcptLine);
  ReturnRcptLine.Modify();

.....

NEW CODE:

....

  RemQtyToBeInvoiced := RemQtyToBeInvoiced - QtyToBeInvoiced;
  RemQtyToBeInvoicedBase := RemQtyToBeInvoicedBase - QtyToBeInvoicedBase;
  ReturnRcptLine."Quantity Invoiced" :=
                      ReturnRcptLine."Quantity Invoiced" + QtyToBeInvoiced;
  ReturnRcptLine."Qty. Invoiced (Base)" :=
                      ReturnRcptLine."Qty. Invoiced (Base)" + QtyToBeInvoicedBase;
  ReturnRcptLine."Return Qty. Rcd. Not Invd." :=
                      ReturnRcptLine.Quantity - ReturnRcptLine."Quantity Invoiced";

  //start code modification  	
  OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify(SalesHeader, ReturnRcptLine, SalesLine);
  //end code modification
	
  ReturnRcptLine.Modify();

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
