### ISSUE TITLE
[event request] Codeunit 80 "Sales-Post" add events to PostUpdateInvoiceLine and PostUpdateReturnReceiptLine

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6612]
Dear ALAppExtensions Team:

Our solution works with additional units of measure, so we need to recalculate extendend fields in procedures PostUpdateInvoiceLine and PostUpdateReturnReceiptLine. We would need two new event publishers:

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnPostUpdateInvoiceLineOnBeforeInitQtyToInvoice(var SalesOrderLine: Record "Sales Line"; var TempSalesLine: Record "Sales Line" temporary) 
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure PostUpdateReturnReceiptLineOnBeforeInitQtyToInvoice(var SalesOrderLine: Record "Sales Line"; var TempSalesLine: Record "Sales Line" temporary) 
begin
end;

In both publishers, all parameters are referenced as VAR

The code in procedure "PostUpdateInvoiceLine" in Codeunit 80 would be modified as follows:

OLD CODE: 

....

if Type = Type::"Charge (Item)" then
   UpdateSalesOrderChargeAssgnt(TempSalesLine, SalesOrderLine);
SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
if Abs(SalesOrderLine."Quantity Invoiced") > Abs(SalesOrderLine."Quantity Shipped") then
  Error(InvoiceMoreThanShippedErr, SalesOrderLine."Document No.");
SalesOrderLine.InitQtyToInvoice;

.....

NEW CODE:

....

if Type = Type::"Charge (Item)" then
   UpdateSalesOrderChargeAssgnt(TempSalesLine, SalesOrderLine);
SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
if Abs(SalesOrderLine."Quantity Invoiced") > Abs(SalesOrderLine."Quantity Shipped") then
  Error(InvoiceMoreThanShippedErr, SalesOrderLine."Document No.");

//start code modification  	
OnPostUpdateInvoiceLineOnBeforeInitQtyToInvoice(SalesOrderLine, TempSalesLine)
//end code modification

SalesOrderLine.InitQtyToInvoice;

.....

The code in procedure "PostUpdateReturnReceiptLine" in Codeunit 80 would be modified as follows:

OLD CODE: 

....

SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
Abs(SalesOrderLine."Quantity Invoiced") > Abs(SalesOrderLine."Return Qty. Received") then
  Error(InvoiceMoreThanReceivedErr, SalesOrderLine."Document No.");
SalesOrderLine.InitQtyToInvoice();

....

NEW CODE:

....

SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
Abs(SalesOrderLine."Quantity Invoiced") > Abs(SalesOrderLine."Return Qty. Received") then
  Error(InvoiceMoreThanReceivedErr, SalesOrderLine."Document No.");

//start code modification  	
PostUpdateReturnReceiptLineOnBeforeInitQtyToInvoice(SalesOrderLine, TempSalesLine)
//end code modification

SalesOrderLine.InitQtyToInvoice();

....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
