### ISSUE TITLE
[event request] Codeunit 90 "Purch.-Post" new event in "PostItemJnlLine"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6613]
Dear ALAppExtensions Team:

Our solution extends the item charges funcionality. To do this, we would need a new event publisher:

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnPostItemJnlLineOnBeforePostItemJnlLineItemCharges(PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header"; var IsHandled: Boolean);
begin
end;

The parameter IsHandled is referenced as VAR

The code in procedure "PostItemJnlLine" in Codeunit 90 "Purch.-Post" would be modified as follows:

OLD CODE: 

....

if PostWhseJnlLine then begin
  PostItemJnlLineWhseLine(TempWhseJnlLine, TempWhseTrackingSpecification, PurchLine, PostJobConsumptionBeforePurch);
  OnAfterPostWhseJnlLine(PurchLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit);
end;
if (PurchLine.Type = PurchLine.Type::Item) and PurchHeader.Invoice then
  PostItemJnlLineItemCharges(
        PurchHeader, PurchLine, OriginalItemJnlLine, "Item Shpt. Entry No.", TempTrackingSpecificationChargeAssmt);

.....

NEW CODE:

....

if PostWhseJnlLine then begin
  PostItemJnlLineWhseLine(TempWhseJnlLine, TempWhseTrackingSpecification, PurchLine, PostJobConsumptionBeforePurch);
  OnAfterPostWhseJnlLine(PurchLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit);
end;

//start code modification  
IsHandled := false;	
OnPostItemJnlLineOnBeforePostItemJnlLineItemCharges(PurchLine, PurchHeader, IsHandled)
if not IsHandled then
//end code modification

  if (PurchLine.Type = PurchLine.Type::Item) and PurchHeader.Invoice then
    PostItemJnlLineItemCharges(
        PurchHeader, PurchLine, OriginalItemJnlLine, "Item Shpt. Entry No.", TempTrackingSpecificationChargeAssmt);

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
