### ISSUE TITLE
[event request] Codeunit 90 "Purch.-Post" new event in "PostUpdateOrderLine"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6614]
Dear ALAppExtensions Team:

Our solution works with additional units of measure , so when a line is posted, we need to update the extended fields before update the blanket order lines. In order to do this, we would need a new event publisher:

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnPostUpdateOrderLineOnBeforeUpdateBlanketOrderLine(var TempPurchLine: Record "Purchase Line" temporary; PurchHeader: Record "Purchase Header");
begin
end;

The parameter TempPurchLine is referenced as VAR

The code in procedure "PostUpdateOrderLine" in Codeunit 90 "Purch.-Post" would be modified as follows:

OLD CODE: 

....

   if "Qty. to Invoice" <> 0 then begin
     "Prepmt Amt Deducted" += "Prepmt Amt to Deduct";
     "Prepmt VAT Diff. Deducted" += "Prepmt VAT Diff. to Deduct";
     DecrementPrepmtAmtInvLCY(
                              TempPurchLine, "Prepmt. Amount Inv. (LCY)", "Prepmt. VAT Amount Inv. (LCY)");
                            "Prepmt Amt to Deduct" := "Prepmt. Amt. Inv." - "Prepmt Amt Deducted";
                            "Prepmt VAT Diff. to Deduct" := 0;
    end;
  end;

  UpdateBlanketOrderLine(TempPurchLine, PurchHeader.Receive, PurchHeader.Ship, PurchHeader.Invoice);

  OnPostUpdateOrderLineOnBeforeInitOutstanding(PurchHeader, TempPurchLine);

   InitOutstanding();

.....

NEW CODE:

....

   if "Qty. to Invoice" <> 0 then begin
     "Prepmt Amt Deducted" += "Prepmt Amt to Deduct";
     "Prepmt VAT Diff. Deducted" += "Prepmt VAT Diff. to Deduct";
     DecrementPrepmtAmtInvLCY(
                              TempPurchLine, "Prepmt. Amount Inv. (LCY)", "Prepmt. VAT Amount Inv. (LCY)");
                            "Prepmt Amt to Deduct" := "Prepmt. Amt. Inv." - "Prepmt Amt Deducted";
                            "Prepmt VAT Diff. to Deduct" := 0;
    end;
  end;

  //start code modification  
  OnPostUpdateOrderLineOnBeforeUpdateBlanketOrderLine(TempPurchLine, PurchHeader);
  //end code modification

  UpdateBlanketOrderLine(TempPurchLine, PurchHeader.Receive, PurchHeader.Ship, PurchHeader.Invoice);

  OnPostUpdateOrderLineOnBeforeInitOutstanding(PurchHeader, TempPurchLine);

   InitOutstanding();
 

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
