### ISSUE TITLE
[event request] Codeunit 90 "Purch.-Post" new parameters on event publisher "OnCopyAndCheckItemChargeOnBeforeLoop"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6615]
Dear ALAppExtensions Team:

Our solution extends the item charge funcionality, to do so we need a modification in the event publisher OnCopyAndCheckItemChargeOnBeforeLoop

OLD PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnCopyAndCheckItemChargeOnBeforeLoop(var TempPurchLine: Record "Purchase Line" temporary; PurchHeader: Record "Purchase Header")
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnCopyAndCheckItemChargeOnBeforeLoop(var TempPurchLine: Record "Purchase Line" temporary; PurchHeader: Record "Purchase Header";var TempItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)" temporary; var IsHandled: Boolean) //new parameters added
end;

The parameters TempItemChargeAssgntPurch and IsHandled are referenced as VAR

The code in procedure "CopyAndCheckItemCharge" in Codeunit 90 "Purch.-Post" would be modified as follows:

OLD CODE: 

....

SetFilter("Qty. to Invoice", '<>0');
if FindSet then
  repeat
    OnCopyAndCheckItemChargeOnBeforeLoop(TempPurchLine, PurchHeader);
    TestField("Job No.", '');
    if PurchHeader.Invoice and
      ("Qty. to Receive" + "Return Qty. to Ship" <> 0) and
                       ((PurchHeader.Ship or PurchHeader.Receive) or
                        (Abs("Qty. to Invoice") >
                         Abs("Qty. Rcd. Not Invoiced" + "Qty. to Receive") +
                         Abs("Ret. Qty. Shpd Not Invd.(Base)" + "Return Qty. to Ship")))
                    then
                        TestField("Line Amount");
      .
      .
      .

                        
      if QtyNeeded <> 0 then
        Error(CannotInvoiceItemChargeErr, "No.");
  until Next() = 0;

  // Check purchlines
  if AssignError then   

.....

NEW CODE:

....

  var
        TempPurchLine: Record "Purchase Line" temporary;
        PurchLine: Record "Purchase Line";
        InvoiceEverything: Boolean;
        AssignError: Boolean;
        QtyNeeded: Decimal;
	//New variable added
	IsHandled: Boolean;

....

SetFilter("Qty. to Invoice", '<>0');
if FindSet then
  repeat
  
    //start new code
    IsHandled := false;
    OnCopyAndCheckItemChargeOnBeforeLoop(TempPurchLine, PurchHeader, TempItemChargeAssgntPurch, IsHandled); //new parameters
    if not IsHandled then begin
    //stop new code

    TestField("Job No.", '');
    if PurchHeader.Invoice and
      ("Qty. to Receive" + "Return Qty. to Ship" <> 0) and
                       ((PurchHeader.Ship or PurchHeader.Receive) or
                        (Abs("Qty. to Invoice") >
                         Abs("Qty. Rcd. Not Invoiced" + "Qty. to Receive") +
                         Abs("Ret. Qty. Shpd Not Invd.(Base)" + "Return Qty. to Ship")))
                    then
                        TestField("Line Amount");
 
      .
      .
      .

                        
      if QtyNeeded <> 0 then
        Error(CannotInvoiceItemChargeErr, "No.");
    
    //start new code
    end;
    // end new code	 
  until Next() = 0;

  // Check purchlines
  if AssignError then

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
