### ISSUE TITLE
[event request] Codeunit 90 "Purch.-Post" new event publisher in procedure "PostItemChargeLine"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6616]
Dear ALAppExtensions Team:

Our solution extends the item charge funcionality, to do so, we need a new event publisher in procedure PostItemChargeLine

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnPostItemChargeLineOnBeforePosting(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;

The code in procedure "PostItemChargeLine" in Codeunit 90 "Purch.-Post" would be modified as follows:

OLD CODE: 

....

local procedure PostItemChargeLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line")
    var
        PurchaseLineBackup: Record "Purchase Line";
    begin
        if not (PurchHeader.Invoice and (PurchLine."Qty. to Invoice" <> 0)) then
            exit;

        ItemJnlRollRndg := true;
        PurchaseLineBackup.Copy(PurchLine); 
        .
        .
        .
.....

NEW CODE:

....

local procedure PostItemChargeLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line")
    var
        PurchaseLineBackup: Record "Purchase Line";
	//start new code
	IsHandled: Boolean;
        //end new code
    begin
        if not (PurchHeader.Invoice and (PurchLine."Qty. to Invoice" <> 0)) then
            exit;

        //start new code
	IsHandled := False;
        OnPostItemChargeLineOnBeforePosting(PurchHeader"Purchase Header",PurchLine, IsHandled);
        if IsHandled then
          exit;
	//stop new code		
        
        ItemJnlRollRndg := true;
        PurchaseLineBackup.Copy(PurchLine); 
        .
        .
        .

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
