### ISSUE TITLE
[Event Request] Table 37 Sales Line - function OnBeforeAutoReserve

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6617]
Dear,
I request for below Amendment for function OnBeforeAutoReserve

Definition of Integration as below

Make SalesLine Parameter as VAR.

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
