### ISSUE TITLE
[Parameter Amendment Request] Codeunit 6500 Item Tracking Management - function OnSplitWhseJnlLineOnAfterCheckWhseItemTrkgSetup

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6618]
Dear,
I request for below changes to Integration
Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77779585-c616f080-7078-11ea-8f90-d16ba5eee2b6.png)

thanks & regards
Ashwini Tripathi

**Comment by ashwinitripathi** [comment]
Dear Roman, sorry I didn't included the call code, since it is standard behaviour so skipped.

It will be as below:

![image](https://user-images.githubusercontent.com/45877379/78524641-1f59ef00-77f2-11ea-877d-0c38ea8c32a1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
