### ISSUE TITLE
[Field Length] Table 5717, Item Cross Reference  [Code 20 -> Code 22] 

### ISSUE THREAD

**Issue by keshavopk** [microsoft/ALAppExtensions#6619]
Hello,
We need the "Cross-Reference No." in "Item Cross Reference" Table to be length of 22 in case of Barcode. As our renowned clients use the Barcode from 22 Character which are Provided by their multiple suppliers.
So we request you please increase the length of field "Cross-Reference No." [field No. 6, from 20 to 22 ]with in Standard BC itself.

If  MS is not going to release this in 15's cumulative updates then which upcoming version we can expect this change.

Please consider it on priority as business is affecting because of this and if we do customization for this then all standard functionality become useless and big customization.
Thank you.

**Comment by AlexanderYakunin** [comment]
We are not allowed to do primary key changes in any table, therefore we cannot extend this field. This is current Azure SQL limitation. Instead we are working on replacement for Cross-reference feature which will support reference numbers up to 50 characters. It should be available in version 17.
