### ISSUE TITLE
[Function Request] SetSelectionFilter for more tables

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#662]
Can you please enhance Codeunit 46 SelectionFilterManagement to handle the following selections:

GetSelectionFilterForResponsibilityCenter(VAR ResponsibilityCenterR : Record "Responsibility Center") : Text

plus 
Page 5715 "Responsibility Center List"
new Procedure 
GetSelectionFilter() : Text
CurrPage.SETSELECTIONFILTER(ResponsibilityCenterL);
EXIT(SelectionFilterManagementL.GetSelectionFilterForResponsibilityCenter(ResponsibilityCenterL));

GetSelectionFilterForSalesPersonPurchaser(VAR Salesperson_PurchaserR : Record "Salesperson/Purchaser") : Text
RecRef.GETTABLE(Salesperson_PurchaserR);
EXIT(GetSelectionFilter(RecRef,Salesperson_PurchaserR.FIELDNO(Code)));

plus
Page 14 "Salespersons/Purchasers"
new procedure
GetSelectionFilter() : Text
CurrPage.SETSELECTIONFILTER(Salesperson_PurchaserL);
EXIT(SelectionFilterManagementL.GetSelectionFilterForSalesPersonPurchaser(Salesperson_PurchaserL));

GetSelectionFilterForItemVariant(VAR ItemVariantR : Record "Item Variant") : Text
RecRef.GETTABLE(ItemVariantR);
EXIT(GetSelectionFilter(RecRef,ItemVariantR.FIELDNO(Code)));

plus Page 5401 "Item Variants"
GetSelectionFilter() : Text
CurrPage.SETSELECTIONFILTER(ItemVariant);
EXIT(SelectionFilterManagement.GetSelectionFilterForItemVariant(ItemVariant));

GetSelectionFilterForFixedAsset(VAR FixedAsset : Record "Fixed Asset") : Text
RecRef.GETTABLE(FixedAsset);
EXIT(GetSelectionFilter(RecRef,FixedAsset.FIELDNO("No.")));

plus Page 5601 "Fixed Asset List"
GetSelectionFilter() : Text
CurrPage.SETSELECTIONFILTER(FixedAsset );
EXIT(SelectionFilterManagementL.GetSelectionFilterForFixedAsset(FixedAsset ));

**Comment by IhorHandziuk** [comment]
Thank you for your request, @GuntherGebauer 
As far as I can see all of this function can be added by extending the mentioned codeunit and pages with your own extension. Is there any reason why you can't do this?

**Comment by IhorHandziuk** [comment]
Thank you for explanation. 
We agree that these functions will be useful as part of the base application. They will be added in the future update.
