### ISSUE TITLE
[Event Request] Codeunit 6500 Item Tracking Management - function CalcQtyToHandleForTrackedQtyOnDocumentLine 

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6620]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77795815-2f582d00-7094-11ea-9b5d-805863cdf6a5.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77795843-397a2b80-7094-11ea-802e-e75da684d00f.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
