### ISSUE TITLE
[Parameter Ammendment Request] Codeunit 99000845 Reservation Management - function OnBeforeAutoReservePurchLine

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6621]
Dear,
I request for below Integration modification
Definition of Integration as below
Search & NextStep need by Var

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
