### ISSUE TITLE
[Event Request] Page 498 Reservation - function SetSalesLine(VAR CurrentSalesLine : Record "Sales Line")

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6622]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77796463-4ea38a00-7095-11ea-8de6-79b3015156ca.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77796485-595e1f00-7095-11ea-9b2e-3f0fe376333a.png)

thanks & regards
Ashwini Tripathi

**Comment by AlexanderYakunin** [comment]
New event OnAfterTestSourceTableFields(SalesLine) implemented in SalesLineReserve.Codeunit.al. Please check latest design in 16.x.

**Comment by ashwinitripathi** [comment]
We have started upgrade in 13 and have moved from 14 to 15 somewhere stability is required. I thing making same available in 15 too in next release should not be any issue.

**Comment by AlexanderYakunin** [comment]
Here is my recommendation. You should not order events based on old C/AL code, instead you should do this work OnPrem yourself. When you will have solution for 16.x or above, you need to request needed events to prepare your solution for cloud.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
