### ISSUE TITLE
[Event Request] Page 498 Reservation - function GetSerialLotNo

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6623]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77796623-ab06a980-7095-11ea-90bb-c8946ebeff39.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77796649-b4901180-7095-11ea-8a24-8c31c27c53bd.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
