### ISSUE TITLE
[Event Request] Page 498 Reservation - function AutoReserve()

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6624]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77796779-eef9ae80-7095-11ea-8f67-2ab966453df4.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77796804-f7ea8000-7095-11ea-9225-c6f7aea90822.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
