### ISSUE TITLE
[Event Request] Page 498 Reservation - function Reserve from Current Line - OnAction()

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6625]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77796917-33854a00-7096-11ea-96d2-807f30f911f5.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77796942-3c761b80-7096-11ea-9ddd-4e354d32db1a.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
