### ISSUE TITLE
[Event Request] Page 498 Reservation - function CancelReservationCurrentLine - OnAction()

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6626]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77797174-a262a300-7096-11ea-96aa-3868d59881f1.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77797194-adb5ce80-7096-11ea-8a36-4ec92378a2f9.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
