### ISSUE TITLE
[Event Request] Page 498 Reservation - function AutoReserve()

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6627]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77797332-e81f6b80-7096-11ea-8e0a-38867c36dd07.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77797362-f2416a00-7096-11ea-9e46-94a3bf081395.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
