### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. - function Function CheckItemAvailable

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6628]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77798891-bd82e200-7099-11ea-9edf-76a48ddc1eeb.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77798914-c70c4a00-7099-11ea-9fb2-29b86a7680d7.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
