### ISSUE TITLE
[Event Request] Codeunit 99000831 Reservation Engine Mgt. - function Function InitRecordset2

### ISSUE THREAD

**Issue by ashwinitripathi** [microsoft/ALAppExtensions#6629]
Dear,
I request for below Integration
![image](https://user-images.githubusercontent.com/45877379/77799100-10f53000-709a-11ea-9818-e3e6e6f26c64.png)

Definition of Integration as below
![image](https://user-images.githubusercontent.com/45877379/77799113-18b4d480-709a-11ea-9c71-ec9e732d202c.png)

thanks & regards
Ashwini Tripathi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
