### ISSUE TITLE
[New Event Request] Codeunit "Mail Management", OnAfterSentViaSMTP

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6630]
[New Event Request] Codeunit 9520 "Mail Management", OnAfterSentViaSMTP

Logging capabilities of mails sent via SMTP have been greatly enhanced. Thus we would need an event after the sending of a mail to supplement the existing event before sending the mail.

The event would need to be inserted just after the line "MailSent := SMTPMail.Send" in procedure SendViaSMTP:

![image](https://user-images.githubusercontent.com/22153733/77819550-e5933500-70db-11ea-82bf-0fd78555341b.png)

**Integration Event:**
OnAfterSentViaSMTP
**Signature:**
var TempEmailItem: Record "Email Item" temporary;
var SMTPMail: Codeunit "SMTP Mail";
var MailSent: Boolean;
HideSMTPError: Boolean

**Comment by StanPesotskiy** [comment]
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
