### ISSUE TITLE
[Enum Request] Table 18 Customer Field 39 "Blocked"

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6631]
We have additional conditiions for a customer to be blocked, and would request this field to be extensible. In our cases we do not require additional publishers to handle these new conditions.

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
