### ISSUE TITLE
[Event Request] Table 296 Reminder Line - CalcFinChrg

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6632]
We have a requirement to be able to change the calculated amount. This change in amount may affect t;he adjustment of the posting groups, so the position of this subscriber is important. Adding amount to OnAfterCalcFinChrg will not work.

            FinChrgTerms."Interest Calculation Method"::"Balance Due":
                if "Due Date" < ReminderHeader."Document Date" then
                    Amount := "Remaining Amount" * "Interest Rate" / 100;
        end;

        // >> START
        OnCalcFinChrgOnBeforeUpdatePostingGroups(VAR Rec, VAR ReminderHeader, VAR Amount);
        // << END

        if Amount <> 0 then begin
            CustPostingGr.Get(ReminderHeader."Customer Posting Group");
            GLAcc.Get(CustPostingGr.GetInterestAccount);
            GLAcc.TestField("Gen. Prod. Posting Group");
            "Gen. Prod. Posting Group" := GLAcc."Gen. Prod. Posting Group";
            Validate("VAT Prod. Posting Group", GLAcc."VAT Prod. Posting Group");
        end;

        OnAfterCalcFinChrg(Rec, ReminderHeader);

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
