### ISSUE TITLE
[Event Request] Table 5965 Service Contract Header - Expiration Date - Onvalidate

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6633]
We require the ability to handle our own way of expiration date error. To make this possible we would like to request the following publisher:

                CheckChangeStatus;

                if "Expiration Date" <> xRec."Expiration Date" then begin
                    // --> START
                    //if "Expiration Date" <> 0D then begin
                    OnExpirationDateCheck(VAR Rec, VAR IsHandled)
                    if "Expiration Date" <> 0D and NOT IsHandled then begin
                    // --> END
                        if "Expiration Date" < "Starting Date" then
                            Error(Text023, FieldCaption("Expiration Date"), FieldCaption("Starting Date"));
                        if "Last Invoice Date" <> 0D then
                            if "Expiration Date" < "Last Invoice Date" then
                                Error(
                                  Text023, FieldCaption("Expiration Date"), FieldCaption("Last Invoice Date"));
                    end;

                    ServContractLine.Reset();
                    ServContractLine.SetRange("Contract Type", "Contract Type");

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
