### ISSUE TITLE
New Paramater Request - OnAfterInsertTransShptLine

### ISSUE THREAD

**Issue by Vikrasans** [microsoft/ALAppExtensions#6634]
Hi,

In the current event

[EventSubscriber(ObjectType::Codeunit, Codeunit::"TransferOrder-Post Shipment", 'OnAfterInsertTransShptLine', '', true, true)]

I am looking for an additional parameter "TransferLine", in order to populate the new extension field in Transfer Line to the corresponding new extension field in the Transfer Shipment Line table. 

To explain my issue better, the following event have Parameters "TransferHeader" and "TransferShipmentHeader" Parameters.

[EventSubscriber(ObjectType::Codeunit, Codeunit::"TransferOrder-Post Shipment", 'OnAfterInsertTransShptHeader', '', true, true)]

Looking ahead for solution or guidance.

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

Please verify your request, the event OnAfterInsertTransShptLine already has a parameter TransLine (from version 14.x), but there are no parameters "TransferHeader" and "TransferShipmentHeader" that you mentioned:
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertTransShptLine(var TransShptLine: Record "Transfer Shipment Line"; TransLine: Record "Transfer Line"; CommitIsSuppressed: Boolean)
    begin
    end;
```

**Comment by Vikrasans** [comment]
Hi,

Thank you for your response.

I am sorry for the confusion caused by parameters "TransferHeader" and "TransferShipmentHeader". These 2 parameters are for 'OnAfterInsertTransShptHeader' and not for 'OnAfterInsertTransShptLine'. I was hoping that I am explaining better by adding this info but looks like it did not. So please ignore that.

I can see only 1 Parameter for OnAfterInsertTransShptLine whcih is TransShptLine. I noticed your comment that 'OnAfterInsertTransShptLine already has a parameter TransLine (from version 14.x) 

My Current AL Version is below and it says the latest version.

![image](https://user-images.githubusercontent.com/61160113/77928011-85cc9380-726d-11ea-898e-90ca6bbd7b52.png)
 
My Current VS Code version is blow

![image](https://user-images.githubusercontent.com/61160113/77925764-e3131580-726a-11ea-88ce-f245646c2766.png)

I hope I explain correctly. Looking ahead for answer.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
