### ISSUE TITLE
[Event Request] - Add an event to codeunit 10145 "E-Invoice Mgt." - SendEmail

### ISSUE THREAD

**Issue by DeborahQin** [microsoft/ALAppExtensions#6635]
Request an Event in codeunit 10145 "E-Invoice Mgt." - function 'SendEmail' before SendOK := SMTPMail.Send(),  to make it possible to add multiple attachments to the email.
Except the current invoice pdf file,  our client need to send the documents in attachment table to be sent together in the same email.

**Comment by AlexanderYakunin** [comment]
Please provide event definition with required parameters.

**Comment by DeborahQin** [comment]
> Add a new parameter  DocumentHeaderRef: RecordRef to SendEmail function. Using it to indicate which document Header record will be sent. 
>In SendMail function, add onBeforeSendEmail(SMTPMail,DocumentHeaderRef);
before SendOK := SMTPMail.Send(); 
>Event definition: onBeforeSendEmail(var SMTPMail: Codeunit "SMTP Mail", DocumentHeaderRef: RecordRef);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
