### ISSUE TITLE
[Event Request] Cancel Posted Cr. Memos

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/ALAppExtensions#6636]
Hello,

I need events in: 
codeunit 1339 "Cancel Posted Sales Cr. Memo", procedure TestCorrectCrMemoIsAllowed 
codeunit 1402 "Cancel Posted Purch. Cr. Memo", procedure TestCorrectCrMemoIsAllowed
same as 
Codeunit 1303 "Correct Posted Sales Invoice", procedure TestCorrectInvoiceIsAllowed, event OnAfterTestCorrectInvoiceIsAllowed

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by sdelikostov** [comment]
Codeunit 1339 "Cancel Posted Sales Cr. Memo"
procedure TestCorrectCrMemoIsAllowed(var SalesCrMemoHeader: Record "Sales Cr.Memo Header")
    begin
        TestIfPostingIsAllowed(SalesCrMemoHeader);
        TestIfCustomerIsBlocked(SalesCrMemoHeader, SalesCrMemoHeader."Sell-to Customer No.");
        TestIfCustomerIsBlocked(SalesCrMemoHeader, SalesCrMemoHeader."Bill-to Customer No.");
        TestIfInvoiceIsCorrectedOnce(SalesCrMemoHeader);
        TestIfCrMemoIsCorrectiveDoc(SalesCrMemoHeader);
        TestCustomerDimension(SalesCrMemoHeader, SalesCrMemoHeader."Bill-to Customer No.");
        TestDimensionOnHeader(SalesCrMemoHeader);
        TestSalesLines(SalesCrMemoHeader);
        TestIfAnyFreeNumberSeries(SalesCrMemoHeader);
        TestExternalDocument(SalesCrMemoHeader);
        TestInventoryPostingClosed(SalesCrMemoHeader);

	//new event request
	>> OnAfterTestCorrectCrMemoIsAllowed(SalesCrMemoHeader, Cancelling);
    end;

codeunit 1402 "Cancel Posted Purch. Cr. Memo"
    procedure TestCorrectCrMemoIsAllowed(var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr.")
    begin
        TestIfPostingIsAllowed(PurchCrMemoHdr);
        TestIfVendorIsBlocked(PurchCrMemoHdr, PurchCrMemoHdr."Buy-from Vendor No.");
        TestIfVendorIsBlocked(PurchCrMemoHdr, PurchCrMemoHdr."Pay-to Vendor No.");
        TestIfInvoiceIsCorrectedOnce(PurchCrMemoHdr);
        TestIfCrMemoIsCorrectiveDoc(PurchCrMemoHdr);
        TestVendorDimension(PurchCrMemoHdr, PurchCrMemoHdr."Pay-to Vendor No.");
        TestDimensionOnHeader(PurchCrMemoHdr);
        TestPurchLines(PurchCrMemoHdr);
        TestIfAnyFreeNumberSeries(PurchCrMemoHdr);
        TestExternalDocument(PurchCrMemoHdr);
        TestInventoryPostingClosed(PurchCrMemoHdr);

	//new event request
	>> OnAfterTestCorrectCrMemoIsAllowed(PurchCrMemoHdr, Cancelling);
    end;

**Comment by StanPesotskiy** [comment]
Originally you requested three events. Now I see just two.
You don' t need to paste the whole function here, it should be a minimal unique piece of code that would point to the right place.
Please provide the complete signature of parameters in of the events. It includes variable type and a VAR keyword, if needed.

**Comment by sdelikostov** [comment]
In the first message I requested 2 events (for sales and purchase cr.memo) and mention that has to be same as for invoices, that already exists.
However, here again:

Codeunit 1339 "Cancel Posted Sales Cr. Memo"
procedure TestCorrectCrMemoIsAllowed(var SalesCrMemoHeader: Record "Sales Cr.Memo Header")
begin
  ...
  TestInventoryPostingClosed(SalesCrMemoHeader);

  //new event request
  > OnAfterTestCorrectCrMemoIsAllowed(var SalesCrMemoHeader: : Record "Sales Cr.Memo Header"; Cancelling: Boolean);
end;

codeunit 1402 "Cancel Posted Purch. Cr. Memo"
procedure TestCorrectCrMemoIsAllowed(var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr.")
begin
  ...
  TestInventoryPostingClosed(PurchCrMemoHdr);

  //new event request
  > OnAfterTestCorrectCrMemoIsAllowed(var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr.", Cancelling: Boolean);
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
