### ISSUE TITLE
[Event Request] Service line OnModify

### ISSUE THREAD

**Issue by DeborahQin** [microsoft/ALAppExtensions#6637]
🛑🛑🛑This repo is no longer dedicated to handling application requests and enhancements 🛑🛑🛑
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
In OnModify trigger on Service Line table, it will check if allow modify or not when document type is service. If the service line has 'Contract No.' <> '' and 'Applied to service Entry' > 0, it is not allow to modify. But in real business, in some scenarios, the client need to modify the generated Description field. Now, it is not possible to do that. Suggest to add an Event in function CheckIfCanBeModified, So, it can be bypassed in same specific scenarioes.

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by StanPesotskiy** [comment]
The detailed list of event's parameters was not provided.
