### ISSUE TITLE
[Event Request] Report 5882 Copy Phys. Invt. Order procedure InsertNew

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#6638]
Hi all we have some functionality in the report 5882 "Copy Phys. Invt. Order" 

in that report, we have a function "InsertNewLine" 
I need two triggers in that function 
one is BeforeInsert, and another is afterInsert (After Dimension UPdate) see the screen shot:

![image](https://user-images.githubusercontent.com/38460823/73630608-95b86480-467c-11ea-9678-a7cf06a1ef85.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by StanPesotskiy** [comment]
The detailed list of event's parameters was not provided.
