### ISSUE TITLE
[EventRequest] Codeunit 1535 Approvals Mgmt. - Substitute approver ID

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6640]
In request #2610 you added a subscriber to BC14. However this subscriber disappeared in BC16. Please  introduce this event again in BC16.

    LOCAL PROCEDURE SubstituteUserIdForApprovalEntry@86(ApprovalEntry@1000 : Record 454);
    VAR
      UserSetup@1001 : Record 91;
      ApprovalAdminUserSetup@1002 : Record 91;
      Substitute@1003 : Code[50];
    BEGIN
      IF NOT UserSetup.GET(ApprovalEntry."Approver ID") THEN
        ERROR(ApproverUserIdNotInSetupErr,ApprovalEntry."Sender ID");

      // >> START (implementation in BC14)
      Substitute := '';
      OnSubstituteUserIdForApprovalEntry(ApprovalEntry, VAR Substitute);
      IF Substitute <> '' THEN BEGIN
        ApprovalEntry."Approver ID" := Substitute;
        ApprovalEntry.MODIFY(TRUE);
        OnDelegateApprovalRequest(ApprovalEntry);
        EXIT;
      END;
      // >> END (implementation in BC14)

      IF UserSetup.Substitute = '' THEN
        IF UserSetup."Approver ID" = '' THEN BEGIN
          ApprovalAdminUserSetup.SETRANGE("Approval Administrator",TRUE);
          IF ApprovalAdminUserSetup.FINDFIRST THEN
            UserSetup.GET(ApprovalAdminUserSetup."User ID")

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
