### ISSUE TITLE
[EventRequest] Codeunit 1535 Approvals Mgmt. - Approval Administrators

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6642]
In #2605 you added a subscriber. This was introduced in BC14, however missing in BC16. Please introduce this subscriber again in BC16. Please note ApprovalEntry is to be added as paramter to function CheckUserAsApprovalAdministrator.

    LOCAL PROCEDURE CheckUserAsApprovalAdministrator@116(ApprovalEntry@1002 : Record 454);
    VAR
      UserSetup@1000 : Record 91;
      IsHandled@1001 : Boolean;
    BEGIN
      // --> START  (BC14 implementation)
      IsHandled := FALSE;
      OnBeforeCheckUserAsApprovalAdministrator(ApprovalEntry, VAR IsHandled);
      IF IsHandled THEN
        EXIT;
      // --> END (BC14 implementation)

      UserSetup.GET(USERID);
      UserSetup.TESTFIELD("Approval Administrator");
    END;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by pranav4186** [comment]
Hello ,

One of our customization extension is also using this event, it would be nice if we would not have to wait till next major release. We have upgraded that customer to BC16 but they will not be able to use that customization because of the missing events.
Thank you.

**Comment by lv-janpieter** [comment]
@pranav4186 
The event is already available in the daily build, so it will be released next cummulative update. You dont have to wait for BC17.
