### ISSUE TITLE
[EventRequest] Page 9104 Approval Comments Factbox - Additional filtering

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6643]
In issue #2611 you added a subscriber in BC14, however is missing in BC16. Please introduce this subscriber again in BC16.

    [External]
    PROCEDURE SetFilterFromApprovalEntry@1(ApprovalEntry@1000 : Record 454) : Boolean;
    BEGIN
      SETRANGE("Record ID to Approve",ApprovalEntry."Record ID to Approve");
      SETRANGE("Workflow Step Instance ID",ApprovalEntry."Workflow Step Instance ID");
      // --> START (from BC14 implementation)
      OnAfterSetFilterFromApprovalEntry(VAR Rec,ApprovalEntry);
      // <-- END
      CurrPage.UPDATE(FALSE);
      EXIT(NOT ISEMPTY);
    END;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
