### ISSUE TITLE
[event request] Codeunit Codeunit 5763 "Whse.-Post Shipment" add parameter to event publisher in procedure "PostUpdateWhseDocuments"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6644]
Dear ALAppExtensions Team:

For our solution we need to update extended fields in table warehouse shipment line. In order to do this, we would need a new parameter in the event publisher "OnBeforePostUpdateWhseShptLineModify" in procedure "PostUpdateWhseDocuments":

OLD PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnBeforePostUpdateWhseShptLineModify(var WarehouseShipmentLine: Record "Warehouse Shipment Line")
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnBeforePostUpdateWhseShptLineModify(var WarehouseShipmentLine: Record "Warehouse Shipment Line";var WhseShptLineBuf: Record "Warehouse Shipment Line" temporary) //new parameter
begin
end;

The parameter WhseShptLineBuf is referenced as VAR

The code in procedure "PostUpdateWhseDocuments" in Codeunit 5763 "Whse.-Post Shipment" would be modified as follows:

OLD CODE: 

....

.
.
.

       with WhseShptLineBuf do
            if Find('-') then begin
                repeat
                    WhseShptLine2.Get("No.", "Line No.");
                    DeleteWhseShptLine := "Qty. Outstanding" = "Qty. to Ship";
                    OnBeforeDeleteUpdateWhseShptLine(WhseShptLine2, DeleteWhseShptLine);
                    if DeleteWhseShptLine then begin
                        ItemTrackingMgt.SetDeleteReservationEntries(true);
                        ItemTrackingMgt.DeleteWhseItemTrkgLines(
                          DATABASE::"Warehouse Shipment Line", 0, "No.", '', 0, "Line No.", "Location Code", true);
                        WhseShptLine2.Delete();
                    end else begin
                        OnBeforePostUpdateWhseShptLine(WhseShptLine2);
                        WhseShptLine2."Qty. Shipped" := "Qty. Shipped" + "Qty. to Ship";
                        WhseShptLine2.Validate("Qty. Outstanding", "Qty. Outstanding" - "Qty. to Ship");
                        WhseShptLine2."Qty. Shipped (Base)" := "Qty. Shipped (Base)" + "Qty. to Ship (Base)";
                        WhseShptLine2."Qty. Outstanding (Base)" := "Qty. Outstanding (Base)" - "Qty. to Ship (Base)";
                        WhseShptLine2.Status := WhseShptLine2.CalcStatusShptLine;
                        OnBeforePostUpdateWhseShptLineModify(WhseShptLine2);
                        WhseShptLine2.Modify();
                        OnAfterPostUpdateWhseShptLine(WhseShptLine2);
                    end;
                until Next = 0;

.
.
.

.....

NEW CODE:

....

.
.
.

       with WhseShptLineBuf do
            if Find('-') then begin
                repeat
                    WhseShptLine2.Get("No.", "Line No.");
                    DeleteWhseShptLine := "Qty. Outstanding" = "Qty. to Ship";
                    OnBeforeDeleteUpdateWhseShptLine(WhseShptLine2, DeleteWhseShptLine);
                    if DeleteWhseShptLine then begin
                        ItemTrackingMgt.SetDeleteReservationEntries(true);
                        ItemTrackingMgt.DeleteWhseItemTrkgLines(
                          DATABASE::"Warehouse Shipment Line", 0, "No.", '', 0, "Line No.", "Location Code", true);
                        WhseShptLine2.Delete();
                    end else begin
                        OnBeforePostUpdateWhseShptLine(WhseShptLine2);
                        WhseShptLine2."Qty. Shipped" := "Qty. Shipped" + "Qty. to Ship";
                        WhseShptLine2.Validate("Qty. Outstanding", "Qty. Outstanding" - "Qty. to Ship");
                        WhseShptLine2."Qty. Shipped (Base)" := "Qty. Shipped (Base)" + "Qty. to Ship (Base)";
                        WhseShptLine2."Qty. Outstanding (Base)" := "Qty. Outstanding (Base)" - "Qty. to Ship (Base)";
                        WhseShptLine2.Status := WhseShptLine2.CalcStatusShptLine;
                        
                        //start new code  
                        OnBeforePostUpdateWhseShptLineModify(WhseShptLine2, WhseShptLineBuf); //new parameter
                        //end new code

                        WhseShptLine2.Modify();
                        OnAfterPostUpdateWhseShptLine(WhseShptLine2);
                    end;
                until Next = 0;

.
.
.

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
