### ISSUE TITLE
Codeunit 87 Blanket Sales Order to Order - ResetQuantityFields

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6645]
In issue #3004 you introced a publisher in BC14, which is missing in BC16. Please reintroduce this publisher again in BC16.

    LOCAL PROCEDURE ResetQuantityFields@1(VAR SalesLine@1000 : Record 37);
    BEGIN
      SalesLine.Quantity := 0;
      SalesLine."Quantity (Base)" := 0;
      SalesLine."Qty. Shipped Not Invoiced" := 0;
      SalesLine."Quantity Shipped" := 0;
      SalesLine."Quantity Invoiced" := 0;
      SalesLine."Qty. Shipped Not Invd. (Base)" := 0;
      SalesLine."Qty. Shipped (Base)" := 0;
      SalesLine."Qty. Invoiced (Base)" := 0;
      SalesLine."Outstanding Quantity" := 0;
      SalesLine."Outstanding Qty. (Base)" := 0;

      // --> START  (BC14 implementation)
      OnAfterResetQuantityFields(VAR SalesLine);
      // <--END  (BC14 implementation)
    END;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
