### ISSUE TITLE
Codeunit 97 Blanket Purch. Order to Order - ResetQuantityFields

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#6646]
In issue #3005 you introced a publisher in BC14, which is missing in BC16. Please reintroduce this publisher again in BC16.

    LOCAL PROCEDURE ResetQuantityFields@1(VAR PurchLine@1000 : Record 39);
    BEGIN
      PurchLine.Quantity := 0;
      PurchLine."Quantity (Base)" := 0;
      PurchLine."Qty. Rcd. Not Invoiced" := 0;
      PurchLine."Quantity Received" := 0;
      PurchLine."Quantity Invoiced" := 0;
      PurchLine."Qty. Rcd. Not Invoiced (Base)" := 0;
      PurchLine."Qty. Received (Base)" := 0;
      PurchLine."Qty. Invoiced (Base)" := 0;

      // --> START  (BC14 implementation)
      OnAfterResetQuantityFields(VAR PurchLine);
      // <--END  (BC14 implementation)
    END;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
