### ISSUE TITLE
Cash Flow Worksheet Line (TAB840) / Cash Flow Worksheet Entry (TAB846) - Missing Source Document Line No. for Purchase / Sales / Service Lines

### ISSUE THREAD

**Issue by elweilando** [microsoft/ALAppExtensions#6647]
While creating Cash Flow Worksheet Lines with Report 840 "Suggest Worksheet Lines"  Sales Order Lines, Purchase Order Lines and service order lines will be collect only with Source Document No and Source Document Type. 

If "Group by Document Type" is not set in report settings, the single lines are collect but there is no possibility to map them against the source line. The relation to the source document line no. is lost.

Is it possible to add a new field "source line no." into "Cashflow Worksheet line" and "Cashflow Worksheet Entry" to keep the relation?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
