### ISSUE TITLE
[event request] Codeunit Codeunit 5763 "Whse.-Post Shipment" new event publishers in procedures "HandleSalesLine" and "HandlePurchaseLine"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6648]
Dear ALAppExtensions Team:

In our solution we need to update extended fields in tables "sales line" and "purchase line". In order to do this, we would need new event publishers for procedures "HandleSalesLine" and "HandlePurchaseLine":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnHandleSalesLineOnBeforeValidateQtytoShip(var SalesLine: Record "Sales Line"; var WhseShptLine: Record "Warehouse Shipment Line"; var ATOWhseShptLine: Record "Warehouse Shipment Line"; var NonATOWhseShptLine: Record "Warehouse Shipment Line"; var ATOLineFound: Boolean; var NonATOLineFound: Boolean; SumOfQtyToShip: Decimal; SumOfQtyToShipBase: Decimal; var IsHandled: Boolean);
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnHandleSalesLineOnAfterValidateRetQtytoReceive(var SalesLine: Record "Sales Line";var WhseShptLine: Record "Warehouse Shipment Line");
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnHandlePurchaseLineOnAfterValidateQtytoReceive(var PurchLine: Record "Purchase Line";var WhseShptLine: Record "Warehouse Shipment Line");
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnHandlePurchaseLineOnAfterValidateRetQtytoShip(var PurchLine: Record "Purchase Line";var WhseShptLine: Record "Warehouse Shipment Line");
begin
end;

All the parameters are referenced as VAR

The code in procedure "HandleSalesLine" in Codeunit 5763 "Whse.-Post Shipment" would be modified as follows:

OLD CODE: 

....

.
.
.

            if SalesLine.Find('-') then
                repeat
                    SetRange("Source Line No.", SalesLine."Line No.");
                    if Find('-') then begin
                        OnAfterFindWhseShptLineForSalesLine(WhseShptLine, SalesLine);
                        if "Source Document" = "Source Document"::"Sales Order" then begin
                            SumOfQtyToShip := 0;
                            SumOfQtyToShipBase := 0;
                            GetATOAndNonATOLines(ATOWhseShptLine, NonATOWhseShptLine, ATOLineFound, NonATOLineFound);
                            if ATOLineFound then begin
                                SumOfQtyToShip += ATOWhseShptLine."Qty. to Ship";
                                SumOfQtyToShipBase += ATOWhseShptLine."Qty. to Ship (Base)";
                            end;
                            if NonATOLineFound then begin
                                SumOfQtyToShip += NonATOWhseShptLine."Qty. to Ship";
                                SumOfQtyToShipBase += NonATOWhseShptLine."Qty. to Ship (Base)";
                            end;

                            ModifyLine := SalesLine."Qty. to Ship" <> SumOfQtyToShip;
                            if ModifyLine then begin
                                SalesLine.Validate("Qty. to Ship", SumOfQtyToShip);
                                SalesLine."Qty. to Ship (Base)" := SumOfQtyToShipBase;
                                if ATOLineFound then
                                    ATOLink.UpdateQtyToAsmFromWhseShptLine(ATOWhseShptLine);
                                if Invoice then
                                    SalesLine.Validate(
                                      "Qty. to Invoice",
                                      SalesLine."Qty. to Ship" + SalesLine."Quantity Shipped" - SalesLine."Quantity Invoiced");
                            end;
                        end else begin
                            ModifyLine := SalesLine."Return Qty. to Receive" <> -"Qty. to Ship";
                            if ModifyLine then begin
                                SalesLine.Validate("Return Qty. to Receive", -"Qty. to Ship");
                                if Invoice then

.
.
.

.....

NEW CODE:

....

  local procedure HandleSalesLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        SalesLine: Record "Sales Line";
        ATOWhseShptLine: Record "Warehouse Shipment Line";
        NonATOWhseShptLine: Record "Warehouse Shipment Line";
        ATOLink: Record "Assemble-to-Order Link";
        AsmHeader: Record "Assembly Header";
        ModifyLine: Boolean;
        ATOLineFound: Boolean;
        NonATOLineFound: Boolean;
        SumOfQtyToShip: Decimal;
        SumOfQtyToShipBase: Decimal;
        //start new code
	IsHandled: Boolean;
        // end new code

.
.
.
            if SalesLine.Find('-') then
                repeat
                    SetRange("Source Line No.", SalesLine."Line No.");
                    if Find('-') then begin
                        OnAfterFindWhseShptLineForSalesLine(WhseShptLine, SalesLine);
                        if "Source Document" = "Source Document"::"Sales Order" then begin
                            SumOfQtyToShip := 0;
                            SumOfQtyToShipBase := 0;
                            GetATOAndNonATOLines(ATOWhseShptLine, NonATOWhseShptLine, ATOLineFound, NonATOLineFound);
                            if ATOLineFound then begin
                                SumOfQtyToShip += ATOWhseShptLine."Qty. to Ship";
                                SumOfQtyToShipBase += ATOWhseShptLine."Qty. to Ship (Base)";
                            end;
                            if NonATOLineFound then begin
                                SumOfQtyToShip += NonATOWhseShptLine."Qty. to Ship";
                                SumOfQtyToShipBase += NonATOWhseShptLine."Qty. to Ship (Base)";
                            end;

                            ModifyLine := SalesLine."Qty. to Ship" <> SumOfQtyToShip;
                            if ModifyLine then begin

                                //start new code
                                IsHandled:= false;
                                OnHandleSalesLineOnBeforeValidateQtytoShip(SalesLine, WhseShptLine, ATOWhseShptLine, NonATOWhseShptLine, ATOLineFound, NonATOLineFound, SumOfQtyToShip, SumOfQtyToShipBase, IsHandled);
				if not IsHandled then begin				
                                //end new code

                                  SalesLine.Validate("Qty. to Ship", SumOfQtyToShip);
                                  SalesLine."Qty. to Ship (Base)" := SumOfQtyToShipBase;

                                //start new code
                                end;
                                //end new code

                                if ATOLineFound then
                                    ATOLink.UpdateQtyToAsmFromWhseShptLine(ATOWhseShptLine);
                                if Invoice then
                                    SalesLine.Validate(
                                      "Qty. to Invoice",
                                      SalesLine."Qty. to Ship" + SalesLine."Quantity Shipped" - SalesLine."Quantity Invoiced");
                            end;
                        end else begin
                            ModifyLine := SalesLine."Return Qty. to Receive" <> -"Qty. to Ship";
                            if ModifyLine then begin
                                SalesLine.Validate("Return Qty. to Receive", -"Qty. to Ship");
                                
                                //start new code
                                OnHandleSalesLineOnAfterValidateRetQtytoReceive(SalesLine, WhseShptLine);
                                // end new code

                                if Invoice then

.
.
.

The code in procedure "HandlePurchaseLine" in Codeunit 5763 "Whse.-Post Shipment" would be modified as follows:

OLD CODE: 

....

.
.
.

       with WhseShptLine do begin
            PurchLine.SetRange("Document Type", "Source Subtype");
            PurchLine.SetRange("Document No.", "Source No.");
            if PurchLine.Find('-') then
                repeat
                    SetRange("Source Line No.", PurchLine."Line No.");
                    if Find('-') then begin
                        OnAfterFindWhseShptLineForPurchLine(WhseShptLine, PurchLine);
                        if "Source Document" = "Source Document"::"Purchase Order" then begin
                            ModifyLine := PurchLine."Qty. to Receive" <> -"Qty. to Ship";
                            if ModifyLine then begin
                                PurchLine.Validate("Qty. to Receive", -"Qty. to Ship");
                                if Invoice then
                                    PurchLine.Validate(
                                      "Qty. to Invoice",
                                      -"Qty. to Ship" + PurchLine."Quantity Received" - PurchLine."Quantity Invoiced");
                            end;
                        end else begin
                            ModifyLine := PurchLine."Return Qty. to Ship" <> "Qty. to Ship";
                            if ModifyLine then begin
                                PurchLine.Validate("Return Qty. to Ship", "Qty. to Ship");
                                if Invoice then
.
.
.

.....

NEW CODE:

....

       with WhseShptLine do begin
            PurchLine.SetRange("Document Type", "Source Subtype");
            PurchLine.SetRange("Document No.", "Source No.");
            if PurchLine.Find('-') then
                repeat
                    SetRange("Source Line No.", PurchLine."Line No.");
                    if Find('-') then begin
                        OnAfterFindWhseShptLineForPurchLine(WhseShptLine, PurchLine);
                        if "Source Document" = "Source Document"::"Purchase Order" then begin
                            ModifyLine := PurchLine."Qty. to Receive" <> -"Qty. to Ship";
                            if ModifyLine then begin
                                PurchLine.Validate("Qty. to Receive", -"Qty. to Ship");

                                //start new code
                                OnHandlePurchaseLineOnAfterValidateQtytoReceive(PurchLine, WhseShptLine);
                                //end new code
  
                                if Invoice then
                                    PurchLine.Validate(
                                      "Qty. to Invoice",
                                      -"Qty. to Ship" + PurchLine."Quantity Received" - PurchLine."Quantity Invoiced");
                            end;
                        end else begin
                            ModifyLine := PurchLine."Return Qty. to Ship" <> "Qty. to Ship";
                            if ModifyLine then begin
                                PurchLine.Validate("Return Qty. to Ship", "Qty. to Ship");
                                  
                                //start new code
                                OnHandlePurchaseLineOnAfterValidateRetQtytoShip(PurchLine, WhseShptLine);
                                //end new code

                                if Invoice then

.
.
.

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
