### ISSUE TITLE
[event request] Codeunit Codeunit 6620 "Copy Document Mgt." new event publishers in procedures "RecalculateSalesLine" and "RecalculatePurchLine"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6649]
Dear ALAppExtensions Team:

In our solution we need to update extended fields in tables "sales line" and "puchase line" when copying documents. In order to do this, we would need new event publishers for procedures "RecalculateSalesLine" and "RecalculatePurchLine" in Codeunit 6620 "Copy Document Mgt.":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRecalculateSalesLineOnAfterValidateQuantity(var ToSalesLine: Record "Sales Line"; var FromSalesLine: Record "Sales Line")
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRecalculatePurchLineOnAfterValidateQuantity(var ToPurchLine: Record "Purchase Line"; var FromPurchLine: Record "Purchase Line")
begin
end;

All the parameters are referenced as VAR

The code in procedure "RecalculateSalesLine" in 6620 "Copy Document Mgt." would be modified as follows:

OLD CODE: 

....

.
.
.

                 if (FromSalesLine.Type <> 0) and (FromSalesLine."No." <> '') then begin
            if ToSalesLine.Type = ToSalesLine.Type::"G/L Account" then begin
                ToSalesLine."No." := FromSalesLine."No.";
                GLAcc.Get(FromSalesLine."No.");
                CopyThisLine := GLAcc."Direct Posting";
                if CopyThisLine then
                    ToSalesLine.Validate("No.", FromSalesLine."No.");
            end else
                ToSalesLine.Validate("No.", FromSalesLine."No.");
            ToSalesLine.Validate("Variant Code", FromSalesLine."Variant Code");
            ToSalesLine.Validate("Location Code", FromSalesLine."Location Code");
            ToSalesLine.Validate("Unit of Measure", FromSalesLine."Unit of Measure");
            ToSalesLine.Validate("Unit of Measure Code", FromSalesLine."Unit of Measure Code");
            ToSalesLine.Validate(Quantity, FromSalesLine.Quantity);

            if not (FromSalesLine.Type in [FromSalesLine.Type::Item, FromSalesLine.Type::Resource]) then begin
.
.
.

.....

NEW CODE:

....

        if (FromSalesLine.Type <> 0) and (FromSalesLine."No." <> '') then begin
            if ToSalesLine.Type = ToSalesLine.Type::"G/L Account" then begin
                ToSalesLine."No." := FromSalesLine."No.";
                GLAcc.Get(FromSalesLine."No.");
                CopyThisLine := GLAcc."Direct Posting";
                if CopyThisLine then
                    ToSalesLine.Validate("No.", FromSalesLine."No.");
            end else
                ToSalesLine.Validate("No.", FromSalesLine."No.");
            ToSalesLine.Validate("Variant Code", FromSalesLine."Variant Code");
            ToSalesLine.Validate("Location Code", FromSalesLine."Location Code");
            ToSalesLine.Validate("Unit of Measure", FromSalesLine."Unit of Measure");
            ToSalesLine.Validate("Unit of Measure Code", FromSalesLine."Unit of Measure Code");
            ToSalesLine.Validate(Quantity, FromSalesLine.Quantity);
            
	    //start new code
            OnRecalculateSalesLineOnAfterValidateQuantity(ToSalesLine, FromSalesLine);
            //end new code
	
            if not (FromSalesLine.Type in [FromSalesLine.Type::Item, FromSalesLine.Type::Resource]) then begin

.
.
.

The code in procedure "RecalculatePurchLine" in Codeunit 6620 "Copy Document Mgt." would be modified as follows:

OLD CODE: 

....

.
.
.
        if (FromPurchLine.Type <> 0) and (FromPurchLine."No." <> '') then begin
            if ToPurchLine.Type = ToPurchLine.Type::"G/L Account" then begin
                ToPurchLine."No." := FromPurchLine."No.";
                GLAcc.Get(FromPurchLine."No.");
                CopyThisLine := GLAcc."Direct Posting";
                if CopyThisLine then
                    ToPurchLine.Validate("No.", FromPurchLine."No.");
            end else
                ToPurchLine.Validate("No.", FromPurchLine."No.");
            ToPurchLine.Validate("Variant Code", FromPurchLine."Variant Code");
            ToPurchLine.Validate("Location Code", FromPurchLine."Location Code");
            ToPurchLine.Validate("Unit of Measure", FromPurchLine."Unit of Measure");
            ToPurchLine.Validate("Unit of Measure Code", FromPurchLine."Unit of Measure Code");
            ToPurchLine.Validate(Quantity, FromPurchLine.Quantity);
            if not (FromPurchLine.Type in [FromPurchLine.Type::Item, FromPurchLine.Type::Resource]) then begin
                ToPurchHeader.TestField("Currency Code", FromPurchHeader."Currency Code");
                ToPurchLine.Validate("Direct Unit Cost", FromPurchLine."Direct Unit Cost");
                ToPurchLine.Validate("Line Discount %", FromPurchLine."Line Discount %");
                if ToPurchLine.Quantity <> 0 then
                    ToPurchLine.Validate("Line Discount Amount", FromPurchLine."Line Discount Amount");
            end;

.
.

.....

NEW CODE:

....

        if (FromPurchLine.Type <> 0) and (FromPurchLine."No." <> '') then begin
            if ToPurchLine.Type = ToPurchLine.Type::"G/L Account" then begin
                ToPurchLine."No." := FromPurchLine."No.";
                GLAcc.Get(FromPurchLine."No.");
                CopyThisLine := GLAcc."Direct Posting";
                if CopyThisLine then
                    ToPurchLine.Validate("No.", FromPurchLine."No.");
            end else
                ToPurchLine.Validate("No.", FromPurchLine."No.");
            ToPurchLine.Validate("Variant Code", FromPurchLine."Variant Code");
            ToPurchLine.Validate("Location Code", FromPurchLine."Location Code");
            ToPurchLine.Validate("Unit of Measure", FromPurchLine."Unit of Measure");
            ToPurchLine.Validate("Unit of Measure Code", FromPurchLine."Unit of Measure Code");
            ToPurchLine.Validate(Quantity, FromPurchLine.Quantity);
           
            //start new code
            OnRecalculatePurchLineOnAfterValidateQuantity(ToPurchLine, FromPurchLine);
            //end new code
  
            if not (FromPurchLine.Type in [FromPurchLine.Type::Item, FromPurchLine.Type::Resource]) then begin
                ToPurchHeader.TestField("Currency Code", FromPurchHeader."Currency Code");
                ToPurchLine.Validate("Direct Unit Cost", FromPurchLine."Direct Unit Cost");
                ToPurchLine.Validate("Line Discount %", FromPurchLine."Line Discount %");
                if ToPurchLine.Quantity <> 0 then
                    ToPurchLine.Validate("Line Discount Amount", FromPurchLine."Line Discount Amount");
            end;

.
.
.

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
