### ISSUE TITLE
[Function Expose] Codeunit 57 Document Totals - Event OnAfterPurchaseLineSetFilters request-for-external

### ISSUE THREAD

**Issue by picazin** [Microsoft/ALAppExtensions#665]
Hi

Can you please make event OnAfterPurchaseLineSetFilters in Codeunit 57 Document Totals External/Global please?

**Comment by mazhelez** [comment]
@picazin, due to the lack of answer, I close the issue.

In case you have more queries, feel free to reopen it or create a new one 😄
