### ISSUE TITLE
Table 11401 CBG Statement Line Request for OnBeforeValidateAppliesToID with handled pattern

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#6650]
**Applies-to ID - OnValidate()**
_OnBeforeValidateAppliesToID(Rec, IsHandled);
IF IsHandled THEN
  EXIT;_

IF "Applies-to ID" <> '' THEN BEGIN
  CBGStatementln.SETCURRENTKEY("Journal Template Name","No.","Applies-to ID");
  CBGStatementln.SETRANGE("Journal Template Name","Journal Template Name");
  CBGStatementln.SETRANGE("No.","No.");
  CBGStatementln.SETRANGE("Applies-to ID","Applies-to ID");
  CBGStatementln.SETFILTER("Line No.",'<>%1',"Line No.");
  IF CBGStatementln.FINDFIRST THEN
    ERROR(Text1000001,
      FIELDCAPTION("Applies-to ID"),
      "Applies-to ID",
      CBGStatementln."Journal Template Name",
      CBGStatementln."No.",
      CBGStatementln."Line No.");
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
