### ISSUE TITLE
[event request] Codeunit 87 "Blanket Sales Order to Order" new event publishers

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6651]
Dear ALAppExtensions Team:

In our solution we need to update extended fields in table "sales line" when converting a blanket order into and order. In order to do this, we would need new event publishers in Codeunit 87 "Blanket Sales Order to Order.", trigger "OnRun" and procedure "ResetQuantityFields":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRunBlanketSalesOrdertoOrderLineOnBeforeValidateQuantity(var SalesOrderLine: Record "Sales Line"; BlanketOrderSalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRunBlanketSalesOrdertoOrderLineOnBeforeValidateQtytoShip(var BlanketOrderSalesLine: Record "Sales Line"; SalesOrderLine: Record "Sales Line"; SalesOrderHeader: Record "Sales Header"; BlanketOrderSalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnAfterResetQuantityFields(var TempSalesLine: Record "Sales Line")
begin
end;

The code in trigger "OnRun" in 87 "Blanket Sales Order to Order" would be modified as follows:

OLD CODE: 

....

.
.
.

                    if (SalesOrderLine."No." <> '') and (SalesOrderLine.Type <> 0) then begin
                        SalesOrderLine.Amount := 0;
                        SalesOrderLine."Amount Including VAT" := 0;
                        SalesOrderLine.Validate(Quantity, BlanketOrderSalesLine."Qty. to Ship");
                        SalesOrderLine.Validate("Shipment Date", BlanketOrderSalesLine."Shipment Date");
                        SalesOrderLine.Validate("Unit Price", BlanketOrderSalesLine."Unit Price");
                        SalesOrderLine."Allow Invoice Disc." := BlanketOrderSalesLine."Allow Invoice Disc.";
                        SalesOrderLine."Allow Line Disc." := BlanketOrderSalesLine."Allow Line Disc.";
                        SalesOrderLine.Validate("Line Discount %", BlanketOrderSalesLine."Line Discount %");
                        if SalesOrderLine.Quantity <> 0 then
                            SalesOrderLine.Validate("Inv. Discount Amount", BlanketOrderSalesLine."Inv. Discount Amount");
                        SalesLineReserve.TransferSaleLineToSalesLine(
                          BlanketOrderSalesLine, SalesOrderLine, BlanketOrderSalesLine."Qty. to Ship (Base)");
                    end;

                    if Cust."Prepayment %" <> 0 then
                        SalesOrderLine."Prepayment %" := Cust."Prepayment %";
                    PrepmtMgt.SetSalesPrepaymentPct(SalesOrderLine, SalesOrderHeader."Posting Date");
                    SalesOrderLine.Validate("Prepayment %");

                    SalesOrderLine."Shortcut Dimension 1 Code" := BlanketOrderSalesLine."Shortcut Dimension 1 Code";
                    SalesOrderLine."Shortcut Dimension 2 Code" := BlanketOrderSalesLine."Shortcut Dimension 2 Code";
                    SalesOrderLine."Dimension Set ID" := BlanketOrderSalesLine."Dimension Set ID";
                    if ATOLink.AsmExistsForSalesLine(BlanketOrderSalesLine) then begin
                        SalesOrderLine."Qty. to Assemble to Order" := SalesOrderLine.Quantity;
                        SalesOrderLine."Qty. to Asm. to Order (Base)" := SalesOrderLine."Quantity (Base)";
                    end;
                    SalesOrderLine.DefaultDeferralCode;
                    if IsSalesOrderLineToBeInserted(SalesOrderLine) then begin
                        OnBeforeInsertSalesOrderLine(SalesOrderLine, SalesOrderHeader, BlanketOrderSalesLine, Rec);
                        SalesOrderLine.Insert();
                        OnAfterInsertSalesOrderLine(SalesOrderLine, SalesOrderHeader, BlanketOrderSalesLine, Rec);
                    end;

                    if ATOLink.AsmExistsForSalesLine(BlanketOrderSalesLine) then
                        ATOLink.MakeAsmOrderLinkedToSalesOrderLine(BlanketOrderSalesLine, SalesOrderLine);

                    if BlanketOrderSalesLine."Qty. to Ship" <> 0 then begin
                        BlanketOrderSalesLine.Validate("Qty. to Ship", 0);
                        BlanketOrderSalesLine.Modify();
                        AutoReserve(SalesOrderLine, TempSalesLine);

.                   end;
.
.

.....

NEW CODE:

....

 trigger OnRun()
    var
        Cust: Record Customer;
        TempSalesLine: Record "Sales Line" temporary;
        SalesCommentLine: Record "Sales Comment Line";
        ATOLink: Record "Assemble-to-Order Link";
        PrepmtMgt: Codeunit "Prepayment Mgt.";
        RecordLinkManagement: Codeunit "Record Link Management";
        SalesCalcDiscountByType: Codeunit "Sales - Calc Discount By Type";
        SalesLineReserve: Codeunit "Sales Line-Reserve";
        Reservation: Page Reservation;
        ShouldRedistributeInvoiceAmount: Boolean;
        CreditLimitExceeded: Boolean;
        //start new code
	IsHandled: Boolean;
	//end new code

.
.
.

                    if (SalesOrderLine."No." <> '') and (SalesOrderLine.Type <> 0) then begin
                        SalesOrderLine.Amount := 0;
                        SalesOrderLine."Amount Including VAT" := 0;

			**//start new code
                        IsHandled:=false;
                        OnRunBlanketSalesOrdertoOrderLineOnBeforeValidateQuantity(SalesOrderLine, BlanketOrderSalesLine, IsHandled);
			if not IsHandled then
                        //end new code**
                          SalesOrderLine.Validate(Quantity, BlanketOrderSalesLine."Qty. to Ship");
                        
                        SalesOrderLine.Validate("Shipment Date", BlanketOrderSalesLine."Shipment Date");
                        SalesOrderLine.Validate("Unit Price", BlanketOrderSalesLine."Unit Price");
                        SalesOrderLine."Allow Invoice Disc." := BlanketOrderSalesLine."Allow Invoice Disc.";
                        SalesOrderLine."Allow Line Disc." := BlanketOrderSalesLine."Allow Line Disc.";
                        SalesOrderLine.Validate("Line Discount %", BlanketOrderSalesLine."Line Discount %");
                        if SalesOrderLine.Quantity <> 0 then
                            SalesOrderLine.Validate("Inv. Discount Amount", BlanketOrderSalesLine."Inv. Discount Amount");
                        SalesLineReserve.TransferSaleLineToSalesLine(
                          BlanketOrderSalesLine, SalesOrderLine, BlanketOrderSalesLine."Qty. to Ship (Base)");
                    end;

                    if Cust."Prepayment %" <> 0 then
                        SalesOrderLine."Prepayment %" := Cust."Prepayment %";
                    PrepmtMgt.SetSalesPrepaymentPct(SalesOrderLine, SalesOrderHeader."Posting Date");
                    SalesOrderLine.Validate("Prepayment %");

                    SalesOrderLine."Shortcut Dimension 1 Code" := BlanketOrderSalesLine."Shortcut Dimension 1 Code";
                    SalesOrderLine."Shortcut Dimension 2 Code" := BlanketOrderSalesLine."Shortcut Dimension 2 Code";
                    SalesOrderLine."Dimension Set ID" := BlanketOrderSalesLine."Dimension Set ID";
                    if ATOLink.AsmExistsForSalesLine(BlanketOrderSalesLine) then begin
                        SalesOrderLine."Qty. to Assemble to Order" := SalesOrderLine.Quantity;
                        SalesOrderLine."Qty. to Asm. to Order (Base)" := SalesOrderLine."Quantity (Base)";
                    end;
                    SalesOrderLine.DefaultDeferralCode;
                    if IsSalesOrderLineToBeInserted(SalesOrderLine) then begin
                        OnBeforeInsertSalesOrderLine(SalesOrderLine, SalesOrderHeader, BlanketOrderSalesLine, Rec);
                        SalesOrderLine.Insert();
                        OnAfterInsertSalesOrderLine(SalesOrderLine, SalesOrderHeader, BlanketOrderSalesLine, Rec);
                    end;

                    if ATOLink.AsmExistsForSalesLine(BlanketOrderSalesLine) then
                        ATOLink.MakeAsmOrderLinkedToSalesOrderLine(BlanketOrderSalesLine, SalesOrderLine);

                    **//start new code
		    IsHandled:= false;
                    OnRunBlanketSalesOrdertoOrderLineOnBeforeValidateQtytoShip(BlanketOrderSalesLine, SalesOrderLine, SalesOrderHeader, Rec, IsHandled);
                    if not IsHandled then	
                    //end new code**

                    if BlanketOrderSalesLine."Qty. to Ship" <> 0 then begin
                        BlanketOrderSalesLine.Validate("Qty. to Ship", 0);
                        BlanketOrderSalesLine.Modify();
                        AutoReserve(SalesOrderLine, TempSalesLine);

.                   end;

.
.
.

The code in procedure "ResetQuantityFields" in Codeunit 6620 "Copy Document Mgt." would be modified as follows:

OLD CODE: 

....
   
 local procedure ResetQuantityFields(var TempSalesLine: Record "Sales Line")
    begin
        TempSalesLine.Quantity := 0;
        TempSalesLine."Quantity (Base)" := 0;
        TempSalesLine."Qty. Shipped Not Invoiced" := 0;
        TempSalesLine."Quantity Shipped" := 0;
        TempSalesLine."Quantity Invoiced" := 0;
        TempSalesLine."Qty. Shipped Not Invd. (Base)" := 0;
        TempSalesLine."Qty. Shipped (Base)" := 0;
        TempSalesLine."Qty. Invoiced (Base)" := 0;
        TempSalesLine."Outstanding Quantity" := 0;
        TempSalesLine."Outstanding Qty. (Base)" := 0;
    end;

.....

NEW CODE:

....

    local procedure ResetQuantityFields(var TempSalesLine: Record "Sales Line")
    begin
        TempSalesLine.Quantity := 0;
        TempSalesLine."Quantity (Base)" := 0;
        TempSalesLine."Qty. Shipped Not Invoiced" := 0;
        TempSalesLine."Quantity Shipped" := 0;
        TempSalesLine."Quantity Invoiced" := 0;
        TempSalesLine."Qty. Shipped Not Invd. (Base)" := 0;
        TempSalesLine."Qty. Shipped (Base)" := 0;
        TempSalesLine."Qty. Invoiced (Base)" := 0;
        TempSalesLine."Outstanding Quantity" := 0;
        TempSalesLine."Outstanding Qty. (Base)" := 0;

	**//start new code
        OnAfterResetQuantityFields(TempSalesLine)
        //end new code**
    end;

.....

Thanks!

**Comment by mcarmenvalera** [comment]
Hi!

When I wrote The code in procedure "ResetQuantityFields" in Codeunit 6620 "Copy Document Mgt." would be modified as follows:

I intended to write:

The code in procedure "ResetQuantityFields" in Codeunit 87 "Blanket Sales Order to Order"  would be modified as follows:

My mistake!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
