### ISSUE TITLE
[event request] Page 232 "Apply Customer Entries" new event publisher in action "Post Application"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6653]
Dear ALAppExtensions Team:

we would need a new event publisher in Page 232 "Apply Customer Entries", action "Post Application":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnBeforePostApplicationAction(var IsHandled: Boolean)
begin
end;

All parameters are referenced as VAR

The code in action "Post Application " in Page 232 "Apply Customer Entries" would be modified as follows:

OLD CODE: 

....

  action("Post Application")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Post Application';
                    Ellipsis = true;
                    Image = PostApplication;
                    Promoted = true;
                    PromotedCategory = Process;
                    ShortCutKey = 'F9';
                    ToolTip = 'Define the document number of the ledger entry to use to perform the application. In addition, you specify the Posting Date for the application.';

                    trigger OnAction()
                    begin
                        PostDirectApplication(false);
                    end;
                }

.....

NEW CODE:

....

  action("Post Application")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Post Application';
                    Ellipsis = true;
                    Image = PostApplication;
                    Promoted = true;
                    PromotedCategory = Process;
                    ShortCutKey = 'F9';
                    ToolTip = 'Define the document number of the ledger entry to use to perform the application. In addition, you specify the Posting Date for the application.';

                    trigger OnAction()
		    //start new code
                    var
		      IsHandled: Boolean;
                    //end new code
                    begin
			//start new code
			IsHandled := false;
                        OnBeforePostApplicationAction(IsHandled);
			If not IsHandled then
                        //end new code
                          PostDirectApplication(false);
                    end;
                }

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
