### ISSUE TITLE
[event request] Page 397 “Sales Invoice Statistics” new event publisher in trigger "OnAfterGetRecord"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6654]
Dear ALAppExtensions Team:

we would need a new event publisher in Page 397 “Sales Invoice Statistics”, trigger "OnAftergetRecord":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnAfterCalculateAdjProfitLCY(var AdjProfitLCY: Decimal; Rec: Record "Sales Invoice Header")
begin
end;

The parameter AdjProfitLCY is referenced as VAR

The code in trigger "onaftergetrecord " in Page Page 397 “Sales Invoice Statistics” would be modified as follows:

OLD CODE: 

....

.
.
.
        ProfitLCY := AmountLCY - CostLCY;
        if AmountLCY <> 0 then
            ProfitPct := Round(100 * ProfitLCY / AmountLCY, 0.1);

        AdjProfitLCY := AmountLCY - TotalAdjCostLCY;
        if AmountLCY <> 0 then
            AdjProfitPct := Round(100 * AdjProfitLCY / AmountLCY, 0.1);

        if Cust.Get("Bill-to Customer No.") then
            Cust.CalcFields("Balance (LCY)")
        else
            Clear(Cust);
.
.
.

.....

NEW CODE:

....

.
.
.
        ProfitLCY := AmountLCY - CostLCY;
        if AmountLCY <> 0 then
            ProfitPct := Round(100 * ProfitLCY / AmountLCY, 0.1);

        AdjProfitLCY := AmountLCY - TotalAdjCostLCY;

        //start new code
        OnAfterCalculateAdjProfitLCY(AdjProfitLCY, Rec);
	//end new code

        if AmountLCY <> 0 then
            AdjProfitPct := Round(100 * AdjProfitLCY / AmountLCY, 0.1);

        if Cust.Get("Bill-to Customer No.") then
            Cust.CalcFields("Balance (LCY)")
        else
            Clear(Cust);
.
.
.

......

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
