### ISSUE TITLE
[event request] Page 398 “Sales Credit Memo Statistics” new event publisher in trigger "OnAfterGetRecord"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6655]
Dear ALAppExtensions Team:

we would need a new event publisher in Page 398 “Sales Credit Memo Statistics”, trigger "OnAftergetRecord":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnAfterCalculateAdjProfitLCY(var AdjProfitLCY: Decimal; Rec: Record "Sales Cr.Memo Header")
begin
end;

The parameter AdjProfitLCY is referenced as VAR

The code in trigger "onaftergetrecord " in Page Page 398 “Sales Credit Memo Statistics” would be modified as follows:

OLD CODE: 

....

.
.
.
       CustLedgEntry.SetCurrentKey("Document No.");
        CustLedgEntry.SetRange("Document No.", "No.");
        CustLedgEntry.SetRange("Document Type", CustLedgEntry."Document Type"::"Credit Memo");
        CustLedgEntry.SetRange("Customer No.", "Bill-to Customer No.");
        if CustLedgEntry.FindFirst then
            AmountLCY := -CustLedgEntry."Sales (LCY)";

        if AmountLCY <> 0 then
            ProfitPct := Round(100 * ProfitLCY / AmountLCY, 0.1);

        AdjProfitLCY := AmountLCY - TotalAdjCostLCY;
        if AmountLCY <> 0 then
            AdjProfitPct := Round(100 * AdjProfitLCY / AmountLCY, 0.1);

        if Cust.Get("Bill-to Customer No.") then
            Cust.CalcFields("Balance (LCY)")
        else
            Clear(Cust);

.
.
.

.....

NEW CODE:

....

.
.
.

       CustLedgEntry.SetCurrentKey("Document No.");
        CustLedgEntry.SetRange("Document No.", "No.");
        CustLedgEntry.SetRange("Document Type", CustLedgEntry."Document Type"::"Credit Memo");
        CustLedgEntry.SetRange("Customer No.", "Bill-to Customer No.");
        if CustLedgEntry.FindFirst then
            AmountLCY := -CustLedgEntry."Sales (LCY)";

        if AmountLCY <> 0 then
            ProfitPct := Round(100 * ProfitLCY / AmountLCY, 0.1);

        AdjProfitLCY := AmountLCY - TotalAdjCostLCY;

        //start new code
        OnAfterCalculateAdjProfitLCY(AdjProfitLCY, Rec);
	//end new code

        if AmountLCY <> 0 then
            AdjProfitPct := Round(100 * AdjProfitLCY / AmountLCY, 0.1);

        if Cust.Get("Bill-to Customer No.") then
            Cust.CalcFields("Balance (LCY)")
        else
            Clear(Cust);

.
.
.

......

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
