### ISSUE TITLE
[event request] Table 36 “Sales Header” new event publisher in procedure "RecreateReservEntryreqline"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6657]
Dear ALAppExtensions Team:

we would need a new event publisher in Table 36 “Sales Header”, procedure "RecreateReservEntryreqline":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRecreateReservEntryReqLineOnBeforeLoop(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;

Both parameters are referenced as VAR

The code in procedure "RecreateReservEntryreqline" in Table 36 “Sales Header” would be modified as follows:

OLD CODE: 

....
    local procedure RecreateReservEntryReqLine(var TempSalesLine: Record "Sales Line" temporary; var TempATOLink: Record "Assemble-to-Order Link" temporary; var ATOLink: Record "Assemble-to-Order Link")
    begin
        repeat
            TestSalesLineFieldsBeforeRecreate;
            if (SalesLine."Location Code" <> "Location Code") and (not SalesLine.IsNonInventoriableItem) then
                SalesLine.Validate("Location Code", "Location Code");
            TempSalesLine := SalesLine;
            if SalesLine.Nonstock then begin
                SalesLine.Nonstock := false;
                SalesLine.Modify();
            end;

            if ATOLink.AsmExistsForSalesLine(TempSalesLine) then begin
                TempATOLink := ATOLink;
                TempATOLink.Insert();
                ATOLink.Delete();
            end;

            TempSalesLine.Insert();
            OnAfterInsertTempSalesLine(SalesLine, TempSalesLine);
            SalesLineReserve.CopyReservEntryToTemp(TempReservEntry, SalesLine);
            RecreateReqLine(SalesLine, 0, true);
        until SalesLine.Next = 0;
    end;
.....

NEW CODE:

....

    local procedure RecreateReservEntryReqLine(var TempSalesLine: Record "Sales Line" temporary; var TempATOLink: Record "Assemble-to-Order Link" temporary; var ATOLink: Record "Assemble-to-Order Link")
    //start new code
    var
      IsHandled: Boolean;
    //end new code	
    begin
        repeat
            //start new code
	    IsHandled := false;
	    OnRecreateReservEntryReqLineOnBeforeLoop(SalesLine, IsHandled);
            if not IsHandled then begin
            //end new code
	
            TestSalesLineFieldsBeforeRecreate;
            if (SalesLine."Location Code" <> "Location Code") and (not SalesLine.IsNonInventoriableItem) then
                SalesLine.Validate("Location Code", "Location Code");
            TempSalesLine := SalesLine;
            if SalesLine.Nonstock then begin
                SalesLine.Nonstock := false;
                SalesLine.Modify();
            end;

            if ATOLink.AsmExistsForSalesLine(TempSalesLine) then begin
                TempATOLink := ATOLink;
                TempATOLink.Insert();
                ATOLink.Delete();
            end;

            TempSalesLine.Insert();
            OnAfterInsertTempSalesLine(SalesLine, TempSalesLine);
            SalesLineReserve.CopyReservEntryToTemp(TempReservEntry, SalesLine);
            RecreateReqLine(SalesLine, 0, true);
            
            //start new code
            end;
            //end new code
        until SalesLine.Next = 0;
    end;

......

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @mcarmenvalera . Actually the same question as for https://github.com/microsoft/ALAppExtensions/issues/6658. Could you be so kind to clarify it.

**Comment by mcarmenvalera** [comment]
Hi @RomanZanizdra 

I have clarified the request for #6658. The explanation for this request is the same: I have sales lines that have been automatically created and related to a line according to certain conditions. I need to skip the copy of the these lines in order to avoid having these lines duplicated.

As I suggested in #6658, if you find more accurate adding a new publisher and modify the code in "RecreateSalesLines", it would fit me too. The code in "RecreateSalesLines" would be modified as follows:

OLD CODE: 

....

.
.
      TempReservEntry.DeleteAll();
                RecreateReservEntryReqLine(TempSalesLine, TempATOLink, ATOLink);
                TransferItemChargeAssgntSalesToTemp(ItemChargeAssgntSales, TempItemChargeAssgntSales);
                IsHandled := false;
                OnRecreateSalesLinesOnBeforeSalesLineDeleteAll(Rec, SalesLine, CurrFieldNo, IsHandled);
                if not IsHandled then
                    SalesLine.DeleteAll(true);

                SalesLine.Init();
                SalesLine."Line No." := 0;
                TempSalesLine.FindSet;
                ExtendedTextAdded := false;
                SalesLine.BlockDynamicTracking(true);
                repeat
                    if TempSalesLine."Attached to Line No." = 0 then begin
                        CreateSalesLine(TempSalesLine);

.
.
.

.....


NEW CODE:

....

.
.
.

      TempReservEntry.DeleteAll();
                RecreateReservEntryReqLine(TempSalesLine, TempATOLink, ATOLink);
                TransferItemChargeAssgntSalesToTemp(ItemChargeAssgntSales, TempItemChargeAssgntSales);
                IsHandled := false;
                OnRecreateSalesLinesOnBeforeSalesLineDeleteAll(Rec, SalesLine, CurrFieldNo, IsHandled);
                if not IsHandled then
                    SalesLine.DeleteAll(true);

                SalesLine.Init();
                SalesLine."Line No." := 0;

                //start new code
                OnRecreateSalesLinesOnBeforeTempSaleslinefindset(var TempSalesLine: Record "Sales Line")
                //end newcode

                TempSalesLine.FindSet;
                ExtendedTextAdded := false;
                SalesLine.BlockDynamicTracking(true);
                repeat
                    if TempSalesLine."Attached to Line No." = 0 then begin
                        CreateSalesLine(TempSalesLine);
.
.
.

......

and the new publisher would be:

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRecreateSalesLinesOnBeforeTempSaleslinefindset(var TempSalesLine: Record "Sales Line")
begin
end;

This way I could filter the TempSaleslines in order to discard the automatically generated ones (which I know how to exclude).

Do you find this possible?

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
