### ISSUE TITLE
[event request] Table 38 “Purchase Header” new event publishers in procedure "RecreatePurchLines"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6658]
Dear ALAppExtensions Team:

we would need two new event publishers in Table 386 “Purchase Header”, procedure "RecreatePurchLines":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRecreatePurchLinesOnBeforeLoop(var PurchLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;

Both parameters are referenced as VAR

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRecreatePurchLinesOnBeforeRecreateItemChargeAssgntPurch(Rec: Record "Purchase Header")
begin
end;

The code in procedure "RecreatePurchLines" in Table 38 “Purchase Header” would be modified as follows:

OLD CODE: 

....

.
.
.

            PurchLine.Reset();
            PurchLine.SetRange("Document Type", "Document Type");
            PurchLine.SetRange("Document No.", "No.");
            if PurchLine.FindSet then begin
                repeat
                    PurchLine.TestField("Quantity Received", 0);
                    PurchLine.TestField("Quantity Invoiced", 0);
                    PurchLine.TestField("Return Qty. Shipped", 0);
                    PurchLine.CalcFields("Reserved Qty. (Base)");
                    PurchLine.TestField("Reserved Qty. (Base)", 0);
                    PurchLine.TestField("Receipt No.", '');
                    PurchLine.TestField("Return Shipment No.", '');
                    PurchLine.TestField("Blanket Order No.", '');
                    IsHandled := false;
                    OnRecreatePurchLinesOnDropShipmentSpecialOrder(PurchLine, IsHandled);
                    if not IsHandled then
                        if PurchLine."Drop Shipment" or PurchLine."Special Order" then begin
                            case true of
                                PurchLine."Drop Shipment":
                                    SalesHeader.Get(SalesHeader."Document Type"::Order, PurchLine."Sales Order No.");
                                PurchLine."Special Order":
                                    SalesHeader.Get(SalesHeader."Document Type"::Order, PurchLine."Special Order Sales No.");
                            end;
                            TestField("Sell-to Customer No.", SalesHeader."Sell-to Customer No.");
                            TestField("Ship-to Code", SalesHeader."Ship-to Code");
                        end;

                    PurchLine.TestField("Prepmt. Amt. Inv.", 0);
                    TempPurchLine := PurchLine;
                    if PurchLine.Nonstock then begin
                        PurchLine.Nonstock := false;
                        PurchLine.Modify();
                    end;
                    OnRecreatePurchLinesOnBeforeTempPurchLineInsert(TempPurchLine, PurchLine);
                    TempPurchLine.Insert();
                until PurchLine.Next = 0;

                TransferItemChargeAssgntPurchToTemp(ItemChargeAssgntPurch, TempItemChargeAssgntPurch);
.
.
.

                    end else
                        if not ExtendedTextAdded then begin
                            TransferExtendedText.PurchCheckIfAnyExtText(PurchLine, true);
                            TransferExtendedText.InsertPurchExtText(PurchLine);
                            OnAfterTransferExtendedTextForPurchaseLineRecreation(PurchLine, TempPurchLine);
                            PurchLine.FindLast();
                            ExtendedTextAdded := true;
                        end;
                    OnRecreatePurchLineOnAfterProcessAttachedToLineNo(TempPurchLine, PurchLine);
                until TempPurchLine.Next() = 0;

                RecreateItemChargeAssgntPurch(TempItemChargeAssgntPurch, TempPurchLine, TempInteger);

                TempPurchLine.SetRange(Type);
                TempPurchLine.DeleteAll();
                OnAfterDeleteAllTempPurchLines();
            end;
        end else
            Rec := xRec;

.
.
.

.....

NEW CODE:

....

.
.
.

            PurchLine.Reset();
            PurchLine.SetRange("Document Type", "Document Type");
            PurchLine.SetRange("Document No.", "No.");
            if PurchLine.FindSet then begin
                repeat

                    //start new code
		    IsHandled:=false;
                    OnRecreatePurchLinesOnBeforeLoop(PurchLine, IsHandled);
                    If not IsHandled then begin
                    // end new code

                    PurchLine.TestField("Quantity Received", 0);
                    PurchLine.TestField("Quantity Invoiced", 0);
                    PurchLine.TestField("Return Qty. Shipped", 0);
                    PurchLine.CalcFields("Reserved Qty. (Base)");
                    PurchLine.TestField("Reserved Qty. (Base)", 0);
                    PurchLine.TestField("Receipt No.", '');
                    PurchLine.TestField("Return Shipment No.", '');
                    PurchLine.TestField("Blanket Order No.", '');
                    IsHandled := false;
                    OnRecreatePurchLinesOnDropShipmentSpecialOrder(PurchLine, IsHandled);
                    if not IsHandled then
                        if PurchLine."Drop Shipment" or PurchLine."Special Order" then begin
                            case true of
                                PurchLine."Drop Shipment":
                                    SalesHeader.Get(SalesHeader."Document Type"::Order, PurchLine."Sales Order No.");
                                PurchLine."Special Order":
                                    SalesHeader.Get(SalesHeader."Document Type"::Order, PurchLine."Special Order Sales No.");
                            end;
                            TestField("Sell-to Customer No.", SalesHeader."Sell-to Customer No.");
                            TestField("Ship-to Code", SalesHeader."Ship-to Code");
                        end;

                    PurchLine.TestField("Prepmt. Amt. Inv.", 0);
                    TempPurchLine := PurchLine;
                    if PurchLine.Nonstock then begin
                        PurchLine.Nonstock := false;
                        PurchLine.Modify();
                    end;
                    OnRecreatePurchLinesOnBeforeTempPurchLineInsert(TempPurchLine, PurchLine);
                    TempPurchLine.Insert();

                    //start new code
                    end;
                    //end new code
                until PurchLine.Next = 0;

                TransferItemChargeAssgntPurchToTemp(ItemChargeAssgntPurch, TempItemChargeAssgntPurch);
.
.
.

                    end else
                        if not ExtendedTextAdded then begin
                            TransferExtendedText.PurchCheckIfAnyExtText(PurchLine, true);
                            TransferExtendedText.InsertPurchExtText(PurchLine);
                            OnAfterTransferExtendedTextForPurchaseLineRecreation(PurchLine, TempPurchLine);
                            PurchLine.FindLast();
                            ExtendedTextAdded := true;
                        end;
                    OnRecreatePurchLineOnAfterProcessAttachedToLineNo(TempPurchLine, PurchLine);
                until TempPurchLine.Next() = 0;

                //start new code
                OnRecreatePurchLinesOnBeforeRecreateItemChargeAssgntPurch(Rec);
                // end new code

                RecreateItemChargeAssgntPurch(TempItemChargeAssgntPurch, TempPurchLine, TempInteger);

                TempPurchLine.SetRange(Type);
                TempPurchLine.DeleteAll();
                OnAfterDeleteAllTempPurchLines();
            end;
        end else
            Rec := xRec;

.
.
.

......

Thanks!

**Comment by mcarmenvalera** [comment]
The referenced table is, obviously, 30 "Purchase Header", not table 386 "Purchase Header"

Sorry"

**Comment by RomanZanizdra** [comment]
Hi @mcarmenvalera . Short question on the requested change. As far as I understood you want to skip the cycle by purchline. Does it make sense to skip the whole block including set of filters on the purchline? Or set some additional filters on the purchline before the cycle starts and avoid adding event inside? Please let me know your thoughts on this.

**Comment by mcarmenvalera** [comment]
Hi @RomanZanizdra

I just wanna skip the cycle specifically for that repeat. Let me explain myself:

My code creates automatically additional lines related to a certain line depending on certain conditions. Basically, what I need is that when recreating lines, delete all the lines but in the proccess of copying the lines to the temporary ones in the repeat before deleting them, I need 
 the additional lines created by my code not be copied  to the temporary ones because my code will recreate those lines when inserting the new line. If those additional lines are not skipped, the outcome is that the resulting additional lines are duplicated.

An alternative solution to my request, if you find it more suitable, would be an additional event publisher that allows to filter the lines to be inserted after delete the lines. The code in "RecreatePurchLines"  would be resulting in this:

OLD CODE: 

....

.
.
.

                TransferItemChargeAssgntPurchToTemp(ItemChargeAssgntPurch, TempItemChargeAssgntPurch);

                PurchLine.DeleteAll(true);

                PurchLine.Init();
                PurchLine."Line No." := 0;
                TempPurchLine.FindSet();
                ExtendedTextAdded := false;
                repeat
                    if TempPurchLine."Attached to Line No." = 0 then begin
                        PurchLine.Init();
                        PurchLine."Line No." := PurchLine."Line No." + 10000

.
.
.

.....


NEW CODE:

....

.
.
.


                TransferItemChargeAssgntPurchToTemp(ItemChargeAssgntPurch, TempItemChargeAssgntPurch);

                PurchLine.DeleteAll(true);

                PurchLine.Init();
                PurchLine."Line No." := 0;

                //start new code
                OnRecreatePuchLinesOnBeforeTempurchlinefindset(TempPurchLine);
                //end new code

                TempPurchLine.FindSet();
                ExtendedTextAdded := false;
                repeat
                    if TempPurchLine."Attached to Line No." = 0 then begin
                        PurchLine.Init();
                        PurchLine."Line No." := PurchLine."Line No." + 10000
.
.
.

and the new publisher :


NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRecreatePuchLinesOnBeforeTempurchlinefindset(var TempPurchLine: Record "Purchase Line")
begin
end;

Let me know what you think or if you need me to clarify something.

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
