### ISSUE TITLE
[event request] Codeunit 90 “Purch.-Post” new event publisher in procedure "CheckAndUpdate"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#6661]
Dear ALAppExtensions Team:

Our solution extends the item charge funcionality, and needs copyandcheck the item charges if receive given certain conditions. In order to achieve this, we would need a new event publisher in Codeunit 90 “Purch.-Post” and modify the code in procedure "CheckAndUpdate":

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnCheckAndUpdateOnCopyChargesIfReceive(var Receive: Boolean; var CheckChargesifReceive: boolean)
begin
end;

Both parameters are referenced as VAR

The code in procedure "CheckAndUpdate" in Codeunit 90 “Purch.-Post” would be modified as follows:

OLD CODE: 

....

.
.
.
          if (Receive or Invoice) and (not IsCreditDocType) then begin
                TestField("Payment Method Code");
                TestField("Payment Terms Code");
            end;

            if Invoice then
                Invoice := CalcInvoice(PurchHeader);

            if Invoice then
                CopyAndCheckItemCharge(PurchHeader);

.
.
.

.....

NEW CODE:

....

    local procedure CheckAndUpdate(var PurchHeader: Record "Purchase Header")
    var
        TransportMethod: Record "Transport Method";
        GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
        CheckDimensions: Codeunit "Check Dimensions";
        ErrorContextElement: Codeunit "Error Context Element";
        ForwardLinkMgt: Codeunit "Forward Link Mgt.";
        SetupRecID: RecordID;
        ModifyHeader: Boolean;
        RefreshTempLinesNeeded: Boolean;
	//start new code
	CheckChargesifReceive: Boolean; //new variable
        //end new code
.
.
.

          if (Receive or Invoice) and (not IsCreditDocType) then begin
                TestField("Payment Method Code");
                TestField("Payment Terms Code");
            end;

            if Invoice then
                Invoice := CalcInvoice(PurchHeader);

            //start new code
            CheckChargesifReceive:=false;
	    OnCheckAndUpdateOnCopyChargesIfReceive(Receive, CheckChargesifReceive);
	    if CheckChargesifReceive then
               CopyAndCheckItemCharge(PurchHeader);
	    //end new code

            if Invoice then
                CopyAndCheckItemCharge(PurchHeader);

.
.
.

......

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @mcarmenvalera . Your request cannot be implemented in the way you asked for, this is not correct approach. Please let me know if you can process your requirements with existing events but there are lack of parameters or additional event can be added without calling a function as you asked.

**Comment by mcarmenvalera** [comment]
Hi @RomanZanizdra ,

sorry but I'm not sure that I'm understanding your suggestion. I'll explain what I need: 

Our solution extends the item charge funcionality. The standard funcionality calls the procedure CopyAndCheckItemCharge in codeunit 90 if Invoice, so we have this code:

       if Invoice then
                CopyAndCheckItemCharge(PurchHeader);

What I need, in addition, is to call procedure CopyAndCheckItemCharge is we are receiving and a extended boolean field in table "Purchases & Payables Setup" is set to true. In other words, what I need is code similar to this:

if (Receive and Extendedfield) or invoice then 
   CopyAndCheckItemCharge(PurchHeader);

hence my request. 

So, rewriting my request:

Could it be this modification in the  code in procedure "CheckAndUpdate":

OLD CODE: 

local procedure CheckAndUpdate(var PurchHeader: Record "Purchase Header")
var
    TransportMethod: Record "Transport Method";
    GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
    CheckDimensions: Codeunit "Check Dimensions";
    ErrorContextElement: Codeunit "Error Context Element";
    ForwardLinkMgt: Codeunit "Forward Link Mgt.";
    SetupRecID: RecordID;
    ModifyHeader: Boolean;
    RefreshTempLinesNeeded: Boolean;
.
.
.
            if Invoice then
                Invoice := CalcInvoice(PurchHeader);

            if Invoice then
                CopyAndCheckItemCharge(PurchHeader);

            if Invoice and not IsCreditDocType then begin
                TestField("Due Date");
                PaymentTerms.VerifyMaxNoDaysTillDueDate("Due Date", "Document Date", FieldCaption("Due Date"));
            end;

.
.
.

.....


NEW CODE:

local procedure CheckAndUpdate(var PurchHeader: Record "Purchase Header")
var
    TransportMethod: Record "Transport Method";
    GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
    CheckDimensions: Codeunit "Check Dimensions";
    ErrorContextElement: Codeunit "Error Context Element";
    ForwardLinkMgt: Codeunit "Forward Link Mgt.";
    SetupRecID: RecordID;
    ModifyHeader: Boolean;
    RefreshTempLinesNeeded: Boolean;
    //start new code
    ProcessItemCharges: Boolean; //new variable
    //end new code

.
.
.
            if Invoice then
                Invoice := CalcInvoice(PurchHeader);

	   //start new code
	   ProcessItemCharges:= Invoice;
	
         OnCheckAndUpdateOnBeforeCopyadnCheckItemCharge(Receive,Invoice,ProcessItemCharges);
           
           if ProcessItemCharges then
           //end new code
               CopyAndCheckItemCharge(PurchHeader);

            if Invoice and not IsCreditDocType then begin
                TestField("Due Date");
                PaymentTerms.VerifyMaxNoDaysTillDueDate("Due Date", "Document Date", FieldCaption("Due Date"));
            end;

.
.

......


NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnCheckAndUpdateOnBeforeCopyadnCheckItemCharge(var Receive: Boolean; var Invoice: Boolean; var ProcessItemCharges)
begin
end;


Let me know what you think about this.

Thanks!

**Comment by RomanZanizdra** [comment]
Let's do it in a little bit different way.
There will be new event with include sender = true
    _[IntegrationEvent(true, false)]
    local procedure OnCheckAndUpdateOnAfterCopyAndCheckItemCharge(PurchHeader: Record "Purchase Header")
    begin
    end;_

Also there will be an external function
    _procedure RunCopyAndCheckItemCharge(PurchaseHeader: Record "Purchase Header")
    begin
        CopyAndCheckItemCharge(PurchaseHeader);
    end;_

In that case you will subscribe on the new event and run new function via sender. That's the plan. 
Let me know if there are any concerns.

**Comment by mcarmenvalera** [comment]
Hi @RomanZanizdra ,

I'm ok with your proposal. 

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by mcarmenvalera** [comment]
Hi @RomanZanizdra,

When a request is labelled as ships-in-future-update, when will be exactly published? Next cumulative? next major?

I need to know when all my requests will be published because I need them for the code upgrading process of one of my customers database.

Sorry for bothering.

Thanks in advance.

**Comment by RomanZanizdra** [comment]
Hi @mcarmenvalera . 
I suppose it will be delivered in 16.2. And of course it will be in the next major.

**Comment by mcarmenvalera** [comment]
Ok.

Thank you!
