### ISSUE TITLE
Bug: in report 10153 "Picking List by Order", a wrong table is in use

### ISSUE THREAD

**Issue by DeborahQin** [microsoft/ALAppExtensions#6664]
The picking list report should be printed before sales order been shipped. But the Item Tracking data item is using table "Tracking Specification". At that point, there is no data in this table. It should use table 337 "Reservation Entry" instead.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
