### ISSUE TITLE
Hiding Base Reports

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#6665]
As we cannot extend base reports, we have to copy, customize and publish as our own report.  How can we then hide the base report, so that the end user is not confused as to which report to choose?

It would be great if we could minimally extend the base report to change the UsageCategory, Caption or something so that the end-user is not confused.

**Comment by jaytmalik** [comment]
We have the same problem with pages which we do not want to show in Tell Me...

**Comment by AlexanderYakunin** [comment]
You can use this https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-substituting-reports
