### ISSUE TITLE
Event Request]Application “Tests-VAT”, 134042 "ERM VAT Tolerance"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6668]
Event Request]Application “Tests-VAT”, 134042 "ERM VAT Tolerance"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78228226-b0695700-74ce-11ea-8ebc-9e6d5a7200d3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
