### ISSUE TITLE
[Event Request]Application “Tests-VAT”, 134045 "ERM VAT Sales/Purchase"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6669]
[Event Request]Application “Tests-VAT”, 134045 "ERM VAT Sales/Purchase"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78228456-02aa7800-74cf-11ea-8ed5-4e4dece3df29.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
