### ISSUE TITLE
[Event Request]Application “Tests-VAT”, 134051 "ERM VAT Tool - Sales Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6670]
[Event Request]Application “Tests-VAT”, 134051 "ERM VAT Tool - Sales Doc"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78228644-40a79c00-74cf-11ea-8e19-0474d0592946.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
