### ISSUE TITLE
[Event Request]Application “Tests-VAT”, 134052 "ERM VAT Tool - Purch. Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6671]
[Event Request]Application “Tests-VAT”, 134052 "ERM VAT Tool - Purch. Doc"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78228834-7a78a280-74cf-11ea-92c5-5b4dbbc367bd.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
