### ISSUE TITLE
[Event Request]Application “Tests-VAT”, 134060 "ERM VAT Reg. No Validity Check"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6672]
[Event Request]Application “Tests-VAT”, 134060 "ERM VAT Reg. No Validity Check"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78230946-5f5b6200-74d2-11ea-8962-7ee1c587f7d5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
