### ISSUE TITLE
[Event Request]Application “Tests-VAT”, 134061 "ERM VAT Tool - UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6673]
[Event Request]Application “Tests-VAT”, 134061 "ERM VAT Tool - UT"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78231181-b3fedd00-74d2-11ea-88b3-3da635586aa4.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
