### ISSUE TITLE
[Event Request]Application “Tests-VAT”, 134090 "ERM Pmt Disc And VAT Cust/Vend"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6674]
[Event Request]Application “Tests-VAT”, 134090 "ERM Pmt Disc And VAT Cust/Vend"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78231304-e3ade500-74d2-11ea-94d0-5c89d9e6472e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
