### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134170 "WF Demo Sales Inv. Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6675]
[Event Request]Application “Tests-Workflow”, 134170 "WF Demo Sales Inv. Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78231495-3091bb80-74d3-11ea-87b6-213716d52ddd.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
