### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134171 "WF Demo Sales CrMemo Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6676]
[Event Request]Application “Tests-Workflow”, 134171 "WF Demo Sales CrMemo Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78231816-ad249a00-74d3-11ea-90f0-321e0bf83f9c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
