### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134172 "WF Demo Sales Quote Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6677]
[Event Request]Application “Tests-Workflow”, 134172 "WF Demo Sales Quote Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78231932-d2b1a380-74d3-11ea-85af-52d1b6710fb9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
