### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134173 "WF Demo Sales RtOrder Approval"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6678]
[Event Request]Application “Tests-Workflow”, 134173 "WF Demo Sales RtOrder Approval"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78232025-fa087080-74d3-11ea-90b6-20c0f2e2d1e6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
