### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134174 "WF Demo Sales BOrder Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6679]
[Event Request]Application “Tests-Workflow”, 134174 "WF Demo Sales BOrder Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78232152-20c6a700-74d4-11ea-893a-912f5347d142.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
