### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134175 "WF Demo Sales Order Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6680]
[Event Request]Application “Tests-Workflow”, 134175 "WF Demo Sales Order Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78232262-45228380-74d4-11ea-988f-03789e94d3f6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
