### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134176 "WF Demo SalesInv CL Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6681]
[Event Request]Application “Tests-Workflow”, 134176 "WF Demo SalesInv CL Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78232379-6edbaa80-74d4-11ea-870c-48aade0bd2e6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
