### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134177 "WF Demo SalesOrder CL Approval"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6682]
[Event Request]Application “Tests-Workflow”, 134177 "WF Demo SalesOrder CL Approval"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78232467-97fc3b00-74d4-11ea-8aff-d9497c49814f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
