### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134180 "WF Demo Purch. Order Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6683]
[Event Request]Application “Tests-Workflow”, 134180 "WF Demo Purch. Order Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:

![pic1](https://user-images.githubusercontent.com/45795262/78232944-4b652f80-74d5-11ea-9bf8-c2eb62a18c1c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
