### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134181 "WF Demo Purch CrMemo Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6684]
[Event Request]Application “Tests-Workflow”, 134181 "WF Demo Purch CrMemo Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78234235-2b367000-74d7-11ea-87b5-1eecb7f75641.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
