### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134182 "WF Demo Purch Rtrn Order Appr."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6685]
[Event Request]Application “Tests-Workflow”, 134182 "WF Demo Purch Rtrn Order Appr."

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78234333-4f924c80-74d7-11ea-869d-718b12314c63.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
