### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134183 "WF Demo Purch BOrder Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6686]
[Event Request]Application “Tests-Workflow”, 134183 "WF Demo Purch BOrder Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78234714-d7785680-74d7-11ea-82df-1a9fd32cfd25.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
