### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134184 "WF Demo Purch Quote Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6688]
[Event Request]Application “Tests-Workflow”, 134184 "WF Demo Purch Quote Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78234827-01317d80-74d8-11ea-9b66-041aef3b3cbc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
