### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134185 "WF Demo Purch. Invoice"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6689]
[Event Request]Application “Tests-Workflow”, 134185 "WF Demo Purch. Invoice"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78234912-22926980-74d8-11ea-8133-7a716041081f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
