### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134186 "WF Demo Overdue Notifications"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6690]
[Event Request]Application “Tests-Workflow”, 134186 "WF Demo Overdue Notifications"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78234999-42c22880-74d8-11ea-8ad5-3d52fb5bcb39.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
