### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134205 "WF Demo Customer Approval"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6691]
[Event Request]Application “Tests-Workflow”, 134205 "WF Demo Customer Approval"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235085-64231480-74d8-11ea-95dd-20f350509132.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
