### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134209 "Workflow Overview Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6692]
[Event Request]Application “Tests-Workflow”, 134209 "Workflow Overview Tests"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235184-85840080-74d8-11ea-9e9b-fa67ab8d0881.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
