### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134215 "WFWH Purch. Document Approval"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6693]
[Event Request]Application “Tests-Workflow”, 134215 "WFWH Purch. Document Approval"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235256-a77d8300-74d8-11ea-8286-3ac358a0ef3d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
