### ISSUE TITLE
[Extensibility Enhancement] Codeunit 1002 - Custom invoice generation

### ISSUE THREAD

**Issue by Abstfahkl** [microsoft/ALAppExtensions#6694]
Consider removing local visibility to let us create custom invoice generation logic that uses these methods, allowing baseapp-triggers to fire and getting future hotfixes and updates.

> local procedure TestExchangeRate(var JobPlanningLine: Record "Job Planning Line"; PostingDate: Date)

- It would be a plus if we got a way to alter global variable UpdateExchangeRates since that is used in the method.

`local procedure CreateSalesHeader(Job: Record Job; PostingDate: Date)`

- Would require that we could alter document type of global variable SalesHeader2 since that is used in the method.

> local procedure CreateSalesLine(var JobPlanningLine: Record "Job Planning Line")

- Would require that we could alter document type of global variable SalesHeader2 since that is used in the method.
- This would require that we get a way to set global variable JobInvCurrency, since that is used in the method.
- Would be a plus if we could alter global variable SalesHeader to allow for appending to already created SalesHeaders.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
