### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134216 "WFWH Sales Document Approval"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6695]
[Event Request]Application “Tests-Workflow”, 134216 "WFWH Sales Document Approval"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235595-27a3e880-74d9-11ea-86f0-958f8fcb6327.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
