### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134218 "WFWH Entries Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6697]
[Event Request]Application “Tests-Workflow”, 134218 "WFWH Entries Test"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235691-4efab580-74d9-11ea-9303-974ee00b9eac.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
