### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134221 "WFWH Customer Approval"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6698]
[Event Request]Application “Tests-Workflow”, 134221 "WFWH Customer Approval"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235783-6e91de00-74d9-11ea-8bd3-7e0b8f8138ff.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
