### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134300 "Workflow Engine UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6699]
[Event Request]Application “Tests-Workflow”, 134300 "Workflow Engine UT"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235879-8e290680-74d9-11ea-8239-50e2d69cc965.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
