### ISSUE TITLE
Code Suggestion on table 7501

### ISSUE THREAD

**Issue by dksander** [Microsoft/ALAppExtensions#67]
On table 7501 Item Attribute Value there are two procedure for loading Item Attribute value.
Both procedure uses DELETEALL.
Before using DELETEALL, my suggesting would be to add 
IF NOT ISTEMPORARY THEN
error('some text');
![image](https://user-images.githubusercontent.com/9249578/47138976-04708380-d2bb-11e8-9229-3dc9c7282c35.png)

**Comment by JesperSchulz** [comment]
We would need a little more context to your request, as it is hard for us to understand what the purpose of this change is. Please provide.

**Comment by JesperSchulz** [comment]
Closing due to lack of reply.
