### ISSUE TITLE
Enum Requests

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#670]
Could you please consider to change Option into Enum following fields:

Table   Name                                 Field
43  	   Purch. Comment Line        Document Type          
48   	   Invt. Posting Buffer            Account Type
80       Gen. Journal Template        Type
81       Gen. Journal Line                FA Posting Type
82       Item Journal Template        Type
156     Resource                             Type
233     Item Journal Batch              Template Type
246     Requisition Line                   Replenishment System
5520   Unplanned Demand            Demand Type
5601   FA Ledger Entry                   FA Posting Type
5621   FA Journal Line                    FA Posting Type
5870   BOM Buffer                         Type
5956   Resource Skill                      Type
7311   Warehouse Journal Line      Source Subtype
99000760  Calendar Absence Entry     Capacity Type

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
