### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134303 "Workflow Event Response Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6700]
[Event Request]Application “Tests-Workflow”, 134303 "Workflow Event Response Tests"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78235977-adc02f00-74d9-11ea-8777-4a4035cd6f1b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
