### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134309 "Workflow Trigger/Event Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6701]
[Event Request]Application “Tests-Workflow”, 134309 "Workflow Trigger/Event Tests"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78236063-cf211b00-74d9-11ea-965f-e1ac81f5ae06.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
