### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134310 "Workflow Respo. Lib. Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6702]
[Event Request]Application “Tests-Workflow”, 134310 "Workflow Respo. Lib. Tests"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78236167-f0820700-74d9-11ea-8043-51b30fcc8980.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
