### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134317 "Workflow Additional Scenarios"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6703]
[Event Request]Application “Tests-Workflow”, 134317 "Workflow Additional Scenarios"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78236304-127b8980-74da-11ea-9910-94b0439caf71.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
