### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134318 "WF Credit Limit Exceeded Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6704]
[Event Request]Application “Tests-Workflow”, 134318 "WF Credit Limit Exceeded Tests"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78236393-38089300-74da-11ea-987a-b605ab72278c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
