### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 139027 "Test Background Posting"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6705]
[Event Request]Application “Tests-Workflow”, 139027 "Test Background Posting"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78236490-58d0e880-74da-11ea-9540-8c31ca57bf2c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
