### ISSUE TITLE
[Event Request]Application “Tests-Workflow”, 134307 "Workflow Cond. Eval. Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6706]
[Event Request]Application “Tests-Workflow”, 134307 "Workflow Cond. Eval. Tests"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/78236597-7ef68880-74da-11ea-9477-7944d4bdfbc2.png)
![pic2](https://user-images.githubusercontent.com/45795262/78236605-81f17900-74da-11ea-8765-2c651c52d2f3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
