### ISSUE TITLE
[Event Request Table 1300 "Mini Customer Template" - InsertCustomerFromTemplate

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#6707]
Hello, is it possible to get two event in InsertCustomerFromTemplate procedure, like shown in picture?
![TwoNewEvents](https://user-images.githubusercontent.com/54173532/78246744-ee27a900-74e9-11ea-8ed7-6d737f63c843.JPG)

Events:
OnBeforeInsertCustomer(var ConfigTemplateHeader: Record "Config. Template Header"; var Customer: Record Customer)

OnAfterInsertCustomerFromTemplate(ConfigTemplateHeader: Record "Config. Template Header"; var Customer: Record Customer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
