### ISSUE TITLE
No commit in codeunit 90 if SuppressCommit=TRUE just like codeunit 80

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#6708]
There are 4 commits in codeunit 90 which are beiing executed when the parameter:SuppressCommit  is set tot true. 
In codeunit:80 all the same commits are not executed if parameter:SuppressCommit  is set tot true.

Can you apply the code improvements of codeunit80 to codeunit90?
 
code:
[Original.txt](https://github.com/microsoft/ALAppExtensions/files/4421550/Original.txt)
[Modified.txt](https://github.com/microsoft/ALAppExtensions/files/4421552/Modified.txt)

![image](https://user-images.githubusercontent.com/16033297/78259097-7fa01680-74fc-11ea-9116-874b4b0f0270.png)

**Comment by AlexanderYakunin** [comment]
We do not provide such changes to 14.x versions, we only do it for Master. And this is already done here.
