### ISSUE TITLE
Item.ItemTrackingCodeUsesExpirationDate set to OnPrem

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#6710]
On the Item table, why is ItemTrackingCodeUsesExpirationDate set to OnPrem?
![image](https://user-images.githubusercontent.com/34504100/78334540-38616680-758c-11ea-8ed6-a985a51b4c0d.png)
Looks like it happened unintentionally.

BTW, it looks the same for the whole codeunit 8510 "Over-Receipt Mgt.". Every function there is set to OnPrem. Why?

I came across it only because I've copied the whole ItemCard in my extension for testing purposes.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
