### ISSUE TITLE
[Event Request] Codeunit 432 - OnBeforeCheckAmountArray

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6712]
Please add a new publisher event to the function ClearPreviousConsolidation as follows:
	
```
.
.
END;

//>> Start New Publisher Call
OnBeforeCheckAmountArray(DeletedAmounts, DeletedDates);
//<< End New Publisher Call
CheckAmountArray;

IF AnalysisView.FINDSET THEN
  REPEAT
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeCheckAmountArray(VAR DeletedAmountsArray : ARRAY [500] OF Decimal;VAR DeletedDatesArray : ARRAY [500] OF Date)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
