### ISSUE TITLE
[Event Request] Table 36 Sales Header - OnCopyShipToCustomerAddressFieldsFromCustomerOnBeforeValidateLocationCode

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6714]
Requesting a new Event Publisher on Table 36 Sales Header

Event
`OnCopyShipToCustomerAddressFieldsFromCustomerOnBeforeValidateLocationCode(VAR Rec : Record "Sales Header"; VAR IsHandled :   Boolean)`

**Code**
## LOCAL CopyShipToCustomerAddressFieldsFromCustomer(VAR SellToCustomer : Record Customer)
```
IsHandled := FALSE;
OnBeforeCopyShipToCustomerAddressFieldsFromCustomer(Rec,SellToCustomer,IsHandled);
IF IsHandled THEN
  EXIT;

"Ship-to Name" := Cust.Name;
"Ship-to Name 2" := Cust."Name 2";
IF SellToCustomerIsReplaced OR ShipToAddressEqualsOldSellToAddress THEN BEGIN
  "Ship-to Address" := SellToCustomer.Address;
  "Ship-to Address 2" := SellToCustomer."Address 2";
  "Ship-to City" := SellToCustomer.City;
  "Ship-to Post Code" := SellToCustomer."Post Code";
  "Ship-to County" := SellToCustomer.County;
  VALIDATE("Ship-to Country/Region Code",SellToCustomer."Country/Region Code");
END;
"Ship-to Contact" := Cust.Contact;
IF Cust."Shipment Method Code" <> '' THEN
  VALIDATE("Shipment Method Code",Cust."Shipment Method Code");
IF NOT SellToCustTemplate.GET("Sell-to Customer Template Code") THEN BEGIN
  "Tax Area Code" := Cust."Tax Area Code";
  "Tax Liable" := Cust."Tax Liable";
END;
```
**>>> New Code**
```
IsHandled := FALSE;
OnCopyShipToCustomerAddressFieldsFromCustomerOnBeforeValidateLocationCode(Rec, IsHandled);
IF NOT IsHandled THEN 
```
**<<< New Code End**  
```
  IF Cust."Location Code" <> '' THEN
    VALIDATE("Location Code",Cust."Location Code");
"Shipping Agent Code" := Cust."Shipping Agent Code";
"Shipping Agent Service Code" := Cust."Shipping Agent Service Code";

OnAfterCopyShipToCustomerAddressFieldsFromCustomer(Rec,SellToCustomer);
```

In Our Solution we use Job Deliveries (Based on Sales Header and Sales Lines). These Job Deliveries can only have special Job Locations in it and we don't want to set the Location Code based on a Customer, So we must have the possiblity to skip this. We cannot use the existing publisher **OnBeforeCopyShipToCustomerAddressFieldsFromCustomer** because the functions **SellToCustomerIsReplaced** and **ShipToAddressEqualsOldSellToAddress** are **LOCAL** functions. Can you please add this publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
