### ISSUE TITLE
Service Item Line "Document Type" should be Enum

### ISSUE THREAD

**Issue by romann4u** [microsoft/ALAppExtensions#6715]
_ServiceItemLine.Table.al_
Document Type = Option
_ServiceHeader.Table.al_
Document Type = Enum
Assignment of one document type to another one triggers AL0603 warning

Steps and to reproduce the behavior:
`var
ServHeader: Record "Service Header";
ServItemLine: Record "Service Item Line";

ServItemLine.Init();
ServItemLine."Document Type" := ServHeader."Document Type";
ServItemLine."Document No." := ServHeader."No.";`

Expected behavior - No AL0603 warning

![image](https://user-images.githubusercontent.com/54829279/78370853-39e35c80-7595-11ea-8874-ad7492715acc.png)

Versions of AL Language: 5.0.254558
Business Central: Version: US Business Central 16.0 (Platform 16.0.11233.12078 + Application 16.0.11240.11946)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
