### ISSUE TITLE
[Event Request] Table 37 Sales Line - Function TestJobPlanningLine existing Publisher OnBeforeTestJobPlanningLine

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6716]
Requesting an additional parameter CurrFieldNo to existing Publisher OnBeforeTestJobPlanningLine in Table 37 Sales Line

**Existing Signature:**
`OnBeforeTestJobPlanningLine(VAR SalesLine : Record "Sales Line";VAR IsHandled : Boolean)`

**New Signature:**
`OnBeforeTestJobPlanningLine(VAR SalesLine : Record "Sales Line";VAR IsHandled : Boolean,CurrFieldNo : Integer)`

In Our Solution it must be possible to change some fields on the Sales Line, even when a Job Planning Line is linked to it, We use the CurrFieldNo variable to determine if the check should be exited or must be handled. Please expand the above mentioned Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
