### ISSUE TITLE
Event Recorder not working

### ISSUE THREAD

**Issue by rishitiwari1109** [microsoft/ALAppExtensions#6718]
Hi I am unable to get anything in Event Recorder .

I started Event Recorder and then created a Sales Order and post it.

But nothing is shown in Event Recorder.

I am using Business Central Wave2 OnPrem and have only one user in the database
Version: W1 15.2 (Platform 15.0.38951.0 + Application 15.2.39040.0)

Please help

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
