### ISSUE TITLE
Gen. Journal Line "Recurring Method" should be Enum

### ISSUE THREAD

**Issue by Drakonian** [microsoft/ALAppExtensions#6719]
Hello,

Our customer needs to extend the field "Recurring Method" in "Gen. Journal Line", this is critical.

But this field still Option, could you please make transform field to Enum?

![image](https://user-images.githubusercontent.com/16802407/78458141-ca19c280-76b7-11ea-98ab-16f9c3a93de3.png)

Versions of AL Language: 5.0.254558
Business Central: Version: CA Business Central 16.0 (Platform 16.0.11233.12078 + Application 16.0.11240.11946)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
