### ISSUE TITLE
Caption for Amount “LCY” field

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#6720]
Hello Experts,
 
Can someone please help me on below issue?
On Payment Journal page we have a field called “Amount (LCY)” . So while running this page on web client it is showing caption as “Amount ($).
However there is no caption is used on page level to define this field caption as “Amount ($)”.
Even on the source table (Gen jnl line) we have caption “Amount (LCY)” for this field.
Than how this caption “Amount ($)” is calculating on this page.
If there anything that i am not getting please share.
I want to modify this caption for every field within the application
 
Thanks
Sud

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
