### ISSUE TITLE
[Event Request] JnlManagements

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/ALAppExtensions#6723]
Hello,

I need events:
codeunit 230 GenJnlManagement
    procedure OpenJnl(var CurrentJnlBatchName: Code[10]; var GenJnlLine: Record "Gen. Journal Line")
    begin
	//new event request, CurrentJnlBatchName must be var
	> OnBeforeOpenJnl(var CurrentJnlBatchName: Code[10]; var GenJnlLine: Record "Gen. Journal Line");

codeunit 240 ItemJnlManagement
    procedure OpenJnl(var CurrentJnlBatchName: Code[10]; var ItemJnlLine: Record "Item Journal Line")
    begin
	//new event request, CurrentJnlBatchName must be var
	> OnBeforeOpenJnl(var CurrentJnlBatchName: Code[10]; var GenJnlLine: Record "Gen. Journal Line");

similar already exists at OpenJnl in codeunit 330 ReqJnlManagement

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
