### ISSUE TITLE
[Event Request] CU 90 - PostWithhSocSec

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/ALAppExtensions#6725]
Hi,
We need a publisher within this procedure "PostWithhSocSec" in CU 90 like that:

![image](https://user-images.githubusercontent.com/36199751/78559559-dbc4ac80-7814-11ea-8f6c-2ea619051868.png)

I've already checked the latest docker image but still missing 
Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
