### ISSUE TITLE
[Event Request] Add parameter to OnBeforeWithholdingTaxInsert codeunit 12101

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/ALAppExtensions#6726]
Hi,
we need to add this parameter to the existing event in the codeunit 12101 "Withholding - Contribution".

the event is
`OnBeforeWithholdingTaxInsert(VAR WithholdingTax : Record "Withholding Tax";TmpWithholdingContribution : Record "Tmp Withholding Contribution")`

and we need also this parameter:  `GenJnlLine: Record "Gen. Journal Line"`
so something like that:
`OnBeforeWithholdingTaxInsert(VAR WithholdingTax: Record "Withholding Tax"; TempWithholdingSocSec: Record "Tmp Withholding Contribution"; GenJnlLine: Record "Gen. Journal Line")`

thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
