### ISSUE TITLE
[Event Request] Codeunit 8 - MoveAccSchedLines

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#6727]
Hello,

could you add publisher in procedure MoveAccSchedLines in codeunit 8 AccSchedManagement.

    local procedure MoveAccSchedLines(var AccSchedLine: Record "Acc. Schedule Line"; Place: Integer)
    var
        AccSchedLineNo: Integer;
        I: Integer;
    begin
        AccSchedLineNo := AccSchedLine."Line No.";
        AccSchedLine.SetRange("Schedule Name", AccSchedLine."Schedule Name");
        if AccSchedLine.Find('+') then
            repeat
                I := AccSchedLine."Line No.";
                if I > AccSchedLineNo then begin
                    AccSchedLine.Delete;

                    // new  begin         
                    OnBeforeInsertAccScheduleLineMove(AccSchedLine,Place);
                    // new  end

                    AccSchedLine."Line No." := I + 10000 * Place;
                    AccSchedLine.Insert;
                    OnAfterAccSchedLineInsert(AccSchedLine);
                end;
            until (I <= AccSchedLineNo) or (AccSchedLine.Next(-1) = 0);
    end;

 [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertAccScheduleLineMove(VAR AccSchedLine : Record "Acc. Schedule Line";Place : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
