### ISSUE TITLE
[Event Request] Codeunit 7000 publisher - OnBeforeFindSalesLineDisc

### ISSUE THREAD

**Issue by erwinvanroy** [microsoft/ALAppExtensions#6728]
Event change request in codeunit 7000.

Please set all the parameters in publisher OnBeforeFindSalesLineDisc as VAR (same as publisher OnBeforeFindSalesPrice) so we can alter these values. 

[CU7000 original.txt](https://github.com/microsoft/ALAppExtensions/files/4442969/CU7000.original.txt)
[CU7000 modified.txt](https://github.com/microsoft/ALAppExtensions/files/4442970/CU7000.modified.txt)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
