### ISSUE TITLE
[EventRequest] Codeunit 313 "Sales-Printed" - OnAfterCommit

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#6732]
Hello outthere,

please add an event "OnAfterCommit" to Codeunit 313 "Sales-Printed".
```
OnBeforeModify(Rec);
MODIFY;
COMMIT;
OnAfterCommit(Rec);
```
thanks in advanced,
Benjamin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
