### ISSUE TITLE
[Event Request] Codeunit 1535 Approvals Mgmt. - OnDelegateSelectedApprovalRequest

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6733]
Please add a new publisher event to the function DelegateSelectedApprovalRequest as follows:
	
```
.
.
IF CheckCurrentUser AND (NOT ApprovalEntry.CanCurrentUserEdit) THEN
  ERROR(NoPermissionToDelegateErr);

//>> Start New Publisher Call
OnDelegateSelectedApprovalRequest(ApprovalEntry, Handled);
IF Handled THEN
  EXIT;
//<< End New Publisher Call

SubstituteUserIdForApprovalEntry(ApprovalEntry)
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnDelegateSelectedApprovalRequest(VAR ApprovalEntry : Record "Approval Entry";VAR Handled : Boolean)
```

**Comment by StanPesotskiy** [comment]
Hi @ptijsma 
Could you use the existent event OnBeforeSubstituteUserIdForApprovalEntry instead?

**Comment by ptijsma** [comment]
> Hi @ptijsma
> Could you use the existent event OnBeforeSubstituteUserIdForApprovalEntry instead?

Hi StanPesotski,
Are you referring to this issue?
https://github.com/microsoft/ALAppExtensions/issues/6640

Because it is named a bit different from what you're describing above.
But if you're referring to this one, I can't use this since it's not implementing the handled pattern.
It does have an Exit based on the parameter "Substitute", but for me not usable since the record is then already changed.

If the above mentioned issue is handled in another way, could you please let me know where to find the source so I can investigate?

Thanks,
Peter

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
