### ISSUE TITLE
[External Request] Codeunit 10751 - SII Job Management

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#6735]
Hi everyone,

in order to make some custom development, it would be perfect if we cant access method "RenewJobQueueEntry" of this codeunit, just in order to launch SII process externally. Also, if its possible to make the procedures external it hink it would be perfect for more externalization options.

Kind regards.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
