### ISSUE TITLE
[External Request] Table 10752 - SII Doc. Upload State

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#6736]
Hi everyone,

in order to be allowed to create SII request it wuld be wonderful to have te following methods of this table accesible not only for onprem extensions. I dont know why this table functions are with scope onprem, but i think there its no need for that and i hope you can make them accesible for extension development.

Kind regards.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
