### ISSUE TITLE
[Event Request] Codeunit 6620 OnAfterCopyPurchLineFromPurchDocPurchLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6737]
we Need a new Event trigger OnAfterCopyPurchLineFromPurchDocPurchLine in codeunit 6620 in procedure CopyPurchDocPurchLine. The same trigger OnAfterCopySalesLineFromSalesDocSalesLine does already exist for Sales in CopySalesDocSalesLine:

LOCAL CopyPurchDocPurchLine(FromPurchHeader : Record "Purchase Header";ToPurchHeader : Record "Purchase Header";VAR LinesNotCopied : Integer;NextLineNo : Integer)
ItemChargeAssgntNextLineNo := 0;

WITH ToPurchHeader DO BEGIN
  FromPurchLine.RESET;
  FromPurchLine.SETRANGE("Document Type",FromPurchHeader."Document Type");
  FromPurchLine.SETRANGE("Document No.",FromPurchHeader."No.");
  IF MoveNegLines THEN
    FromPurchLine.SETFILTER(Quantity,'<=0');
  IF FromPurchLine.FIND('-') THEN
    REPEAT
      IF NOT ExtTxtAttachedToPosPurchLine(FromPurchHeader,MoveNegLines,FromPurchLine."Attached to Line No.") THEN
        IF CopyPurchLine(
             ToPurchHeader,ToPurchLine,FromPurchHeader,FromPurchLine,
             NextLineNo,LinesNotCopied,FALSE,DeferralTypeForPurchDoc(FromPurchHeader."Document Type"),CopyPostedDeferral,
             FromPurchLine."Line No.")
        THEN BEGIN
          IF FromPurchLine.Type = FromPurchLine.Type::"Charge (Item)" THEN
            CopyFromPurchDocAssgntToLine(
              ToPurchLine,FromPurchLine."Document Type",FromPurchLine."Document No.",FromPurchLine."Line No.",
              ItemChargeAssgntNextLineNo);
          //++++++++++++++++++++++++++++++++++++++++++++++
          OnAfterCopyPurchLineFromPurchDocSalesLine(
            ToPurchHeader,VAR ToPurchLine,VAR FromPurchLine,IncludeHeader,RecalculateLines);
          //----------------------------------------------
        END;
    UNTIL FromPurchLine.NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
