### ISSUE TITLE
Codeunit 6620 OnBeforeInsertToSalesLine and OnBeforeInsertToPurchLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6739]
We want to copy linerelated individuell data similar like "Sales Comment Lines" when copying data from source (Posted or not) Sales documents to actual Sales and purchase documents. This is done using triggers from CU6620 if RecalculateLine=false.
Executing "Get Posted Doc&ument Lines to Reverse" on Page "Sales Return Order" you can select different lines from different posted documents such as "Posted Sales Invoice Lines ". This runs into codeunit 6620 and the trigger OnBeforeInsertToSalesLine and OnBeforeInsertToPurchLine.
At this Point in this trigger FromDocType holds the correct source document type, but FromSalesLine."Document No." is empty and FromSalesLine."Line No." is Zero. Even DocLineNo is 1, because it is the "Line No." from FromSalesLineBuf or TempDocSalesLine, which is not the "Line No." from the "Posted Sales Invoice Line".
This is totally misleading and runs into Errors in our Extension, because the wrong or no "Source Document Line No." can be evauluated to copy from.
In this case FromSalesLine."Document No."  should be the "Posted Sales Invoice"."Document No." and FromSalesLine."Line No." should be the "Posted Sales Invoice"."Line No.". 
DocLineNo must be the "Posted Sales Invoice"."Line No.".  in this case, and not the BufferLineNo.

Selecting other posted documents as "Posted Shipments", "Posted Crédit Memos" and so on - must deliver the similar informations from "Posted Sales Shipment Line".

**Comment by StanPesotskiy** [comment]
Hi @GuntherGebauer 
Passing "Line No." through is not simple, it will require some redesign we would like to avoid if there is a workaround. Please try to use the existing events OnAfterCopySalesDocument and OnAfterCopyPurchaseDocument.
