### ISSUE TITLE
[Event Request] Codeunit 5056 CustCont-Update - OnAfterOnModify

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6740]
Please add a new publisher event to the function OnModify as follows:
	
```
.
.
Cont.OnModify(OldCont);
Cont.MODIFY(TRUE);
Cust.GET(Cust."No.");

//>> Start New Publisher Call
OnAfterOnModify(Cont, OldCont, Cust);
//<< End New Publisher Call
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnAfterOnModify(VAR Contact : Record Contact;VAR OldContact : Record Contact;VAR Customer : Record Customer)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
