### ISSUE TITLE
Application Area missing for Pages (Sales Order Shipment / Sales Order Invoicing)

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/ALAppExtensions#6742]
**Describe the bug**
We have an integration on the below pages and while performing testing found that the below page is not visible in Saas based docker container and the same is working properly on the OnPrem version.

Application Area is missing for below pages : 
10026 | Sales Order Shipment
10027 | Sales Order Shipment Subform
10028 | Sales Order Invoice
10029 | Sales Order Invoice Subform

**To Reproduce**
Steps and to reproduce the behavior: Open Pages with below links

- http://<container_name>/BC/?Page=36626 this open page "Sales Order Shipment List" (this looks ok). Once you landed on this page > now Open Card for any of the Order > which directs to Page 10026 "Sales Order Shipment"

- http://<container_name>/BC/?page=10026
- http://<container_name>/BC/?page=10028

**Expected behavior**
All fields should be visible the same as OnPrem version 
![image](https://user-images.githubusercontent.com/5293496/78779646-e5881480-79ba-11ea-8fac-d9a40459abd7.png)

**Screenshots (image from docker container)**
![image](https://user-images.githubusercontent.com/5293496/78779551-c1c4ce80-79ba-11ea-9059-259636c9fab6.png)

Version 
**Docker BC** 
Version: US Business Central 16.0 (Platform 16.0.11233.12078 + Application 16.0.11240.12085)
**OnPremise BC**
Version: NA Business Central 16.0 (Platform 16.0.11233.12061 + Application 16.0.12076.0)

**Comment by AlexanderYakunin** [comment]
Can you create bugs using Support? This forum is for extensibility requests related with events, enums etc. We do not resolve bugs here.

**Comment by chavansachin20** [comment]
**Fixed in 16.3** 
<img width="956" alt="Sales Order Invoice (10028, Document)" src="https://user-images.githubusercontent.com/5293496/87034453-78785b00-c205-11ea-840b-96b9e295eb62.png">
<img width="958" alt="Sales Order Shipment (10026, Document)" src="https://user-images.githubusercontent.com/5293496/87034455-79a98800-c205-11ea-9b90-0034e94e2b57.png">
