### ISSUE TITLE
[Event Request] Codeunit 5057 VendCont-Update - OnAfterOnModify

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6746]
Please add a new publisher event to the function OnModify as follows:
	
```
.
.
Cont.OnModify(OldCont);
Cont.MODIFY(TRUE);
Vend.GET(Vend."No.");

//>> Start New Publisher Call
OnAfterOnModify(Cont, OldCont, Vend); //C09032.n
//<< End New Publisher Call
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnAfterOnModify(VAR Contact : Record Contact;VAR OldContact : Record Contact;VAR Vendor : Record Vendor)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
