### ISSUE TITLE
page 113 Budget - enable access to variables (and procedures)

### ISSUE THREAD

**Issue by erolkunman** [microsoft/ALAppExtensions#6747]
Please enable access to variables on Base app page 113 Budget.

We just want to extend the page by adding few extra buttons (sample code below), but currently it's impossible, because global variables are not visible on Page extension.

            action("Next Year")
            {
                ApplicationArea = All;
                caption = 'Next Year';
                image = NextRecord;
                Promoted = true;
                PromotedCategory = Category7;
                PromotedOnly = true;
                ToolTip = 'Go to the next Year';
                trigger OnAction()
                var
                    StartDate: Date;
                    EndDate: Date;
                begin
                    startdate := calcdate('<CY>', Today) + 1;
                    endDate := calcdate('<CY>', StartDate);
                    PeriodType := PeriodType::year;
                    ValidateDateFilter(Format(startdate) + '..' + Format(enddate));
                    CurrPage.Update;
                    UpdateMatrixSubform;
                end;
            }

**Comment by AlexanderYakunin** [comment]
Please specify which variables do you need?

**Comment by erolkunman** [comment]
**Variables**:
PeriodType: Option Day,Week,Month,Quarter,Year,"Accounting Period";

**Procedures:**
ValidateDateFilter()
UpdateMatrixSubform()

If some variables are needed to run those procedures then we need them also.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
