### ISSUE TITLE
[Event Change] Codeunit 12: OnBeforeApplyCustLedgEntry / OnBeforeApplyVendLedgEntry

### ISSUE THREAD

**Issue by salgiza** [microsoft/ALAppExtensions#6749]
Would it be possible to add the codeunit raising these two events:

OnBeforeApplyCustLedgEntry
OnBeforeApplyVendLedgEntry

On codeunit 12?

Basically we need them to be defined as 
[IntegrationEvent(true, false)]
just as some other events in that codeunit.

Note: we don't need any more changes but, because of how that codeunit works (using globals and thus needing the codeunit instance if you need to call methods in it) it would probably be logical to pass the codeunit in all integration events (just thinking of partners that might need to use any of the events in that codeunit in the future).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
