### ISSUE TITLE
[EventRequest] Table 210 Job Journal Line - Expand requested publisher OnSelectItemEntryOnAfterSetItemLedgerEntryFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6750]
Dear AL Team, I requested a new publisher for Table 210 Job Journal Line:

`LOCAL [IntegrationEvent] OnSelectItemEntryOnAfterSetItemLedgerEntryFilters(VAR ItemLedgEntry : Record "Item Ledger Entry", CurrentFieldNo : Integer)`

It has already been appoved but reviewing my code again i forgot a parameter.

The signature i need is:
`LOCAL [IntegrationEvent] OnSelectItemEntryOnAfterSetItemLedgerEntryFilters(Rec : Record "Job Journal Line", VAR ItemLedgEntry : Record "Item Ledger Entry", CurrentFieldNo : Integer)`

I missed the current record which i need for the location code, can you please expand the approved Publisher ?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
