### ISSUE TITLE
[EventRequest] Table23 (Vendor.al) OnBeforeOpenVendorLedgerEntries

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#6751]
Hi MS,

Can you please help us by adding below event on **Vendor** table.
![image](https://user-images.githubusercontent.com/33481576/78895079-d329db80-7a8b-11ea-9c99-0d6a69df0d53.png)
![image](https://user-images.githubusercontent.com/33481576/78895105-dfae3400-7a8b-11ea-942c-72b5d924e23c.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SUD-D365** [comment]
This event yet not published.
Any specific release?
