### ISSUE TITLE
[EventRequest] Table36 (SalesHeader.al)

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#6752]
Hi MS,

Can you please help us by adding below events on **SalesHeader** table.
![image](https://user-images.githubusercontent.com/33481576/78896350-f9507b00-7a8d-11ea-9496-ac942a76daed.png)

![image](https://user-images.githubusercontent.com/33481576/78896434-184f0d00-7a8e-11ea-82ed-d5e6fe2128c7.png)

![image](https://user-images.githubusercontent.com/33481576/78896975-10439d00-7a8f-11ea-96ac-2b63ec034092.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
