### ISSUE TITLE
[Event Request] Codeunit 134 OnBeforeUploadFile

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#6755]
New Publisher needed:
OnBeforeUploadFile in function UploadFile

Signature:
[IntegrationEvent(false, false)]
procedure OnBeforeUploadFile(var IncomingDocumentAttachment: Record "Incoming Document Attachment")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
