### ISSUE TITLE
codeunit Reservation Management - DeleteDocumentReservation

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#6756]
we have encoutered what we believe is a bug in codeunit Reservation Management - DeleteDocumentReservation function

we have added an enum value to the enum "sales document type" to have a new type of "sales header".
when we do a delete of a sales header record with this new document type then we go into the function "DeleteSalesLines" of the sales header table.
in this function it goes to Reservation management function deletedocumentreservation
and there this errors on:
SelectStr(DocType + 1, FieldRef.OptionCaption)
because the DocType is not found in the optioncaption
we think this code is not jet adapted to the use of enums?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
