### ISSUE TITLE
[Event Request] Page 344 Function OnBeforeUpdateFormAfterFindRecords

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#6757]
Please extend the publisher signature for Function OnBeforeUpdateFormAfterFindRecords in PAge 344:

OnBeforeUpdateFormAfterFindRecords(var PostingDateFilter: Text)

since the GlobalVarAcces is goint to be an Error in the future.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
