### ISSUE TITLE
[Extensibility Enhancement] Page 113 Budget Filters should be editable

### ISSUE THREAD

**Issue by elweilando** [microsoft/ALAppExtensions#6759]
Business Central stores only the latest filter value in this page. If you use multiple budgets, with different filters you have to change the filters every time you change the budget.

The Filters
- DateFilter
- GLAccFilter
- GLAccCategoryFilter
- IncomeBalanceGLAccFilter
- GlobalDim1Filter
- GlobalDim2Filter
- BudgetDim1Filter
- BudgetDim2Filter
- BudgetDim3Filter
- BudgetDim4Filter

are defined in the OnOpenPage Trigger in Page 113 Budget. 
Only the GLAccFilter is editable from external.

All other filters should be definable from external too.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
