### ISSUE TITLE
[Event Request] Codeunit 12 "Gen.Jnl-Post Line" OnAfterApplyCustLedgerEntry

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6760]
Dear BaseApp team,

In our vertical we need to be able to do some updates after applying customer ledger entries, so we would like to request an event at the end of function "ApplyCustLedgerEntry" in codeunit 12 

Code:

...
if GLSetup."Unrealized VAT" or
           (GLSetup."Prepayment Unrealized VAT" and NewCVLedgEntryBuf.Prepayment)
        then
            if IsNotPayment(NewCVLedgEntryBuf."Document Type") and
               (NewRemainingAmtBeforeAppln - NewCVLedgEntryBuf."Remaining Amount" <> 0)
            then begin
                NewCustLedgEntry.CopyFromCVLedgEntryBuffer(NewCVLedgEntryBuf);
                CheckUnrealizedCust := true;
                UnrealizedCustLedgEntry := NewCustLedgEntry;
                UnrealizedCustLedgEntry.CalcFields("Amount (LCY)", "Original Amt. (LCY)");
                UnrealizedRemainingAmountCust := NewCustLedgEntry."Remaining Amount" - 
                NewRemainingAmtBeforeAppln;
            end;

        //>>L365
        OnAfterApplyCustLedgerEntry(GenJnlLine,NewCVLedgEntryBuf,OldCustLedgEntry);
        //<<L365
    end;

...

[IntegrationEvent(false, false)]
local procedure OnAfterApplyCustLedgerEntry(var GenJnlLine: Record "Gen. Journal Line"; var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var OldCustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
