### ISSUE TITLE
[Event Request] Codeunit 8616 "Config. Management" IsDefaultDimTable function

### ISSUE THREAD

**Issue by kmistryebecs** [microsoft/ALAppExtensions#6761]
Please can you add a new event to the IsDefaultDimTable function in Codeunit 8616 "Config. Management" so that it is possible to extend this function to work with custom tables as follows...

OLD CODE
------------
          ...
            else
                exit(false);
 
NEW CODE
------------
            ...
            else begin
                    IsHandled := false;
                    OnIsDefaultDimTable(TableId, IsHandled);
                    exit(IsHandled);
                end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
