### ISSUE TITLE
[Event Request] Codeunit 408 "DimensionManagement" TypeToTableID3

### ISSUE THREAD

**Issue by kmistryebecs** [microsoft/ALAppExtensions#6763]
Could an event be added to the TypeToTableID3 function in DimensionManagement codeunit.  With Enums and Interfaces it is now possible to extend the "Type" field on Sales/Purchase lines bit we also need the ability to set dimensions from the new table associated with the new enum value.  To be able to do this we need an event in this function.

In fact all the TypeToTableID? functions should be extended to have an event added.  An else should be added to the case statements as follows...

```
  else begin
        OnTypeToTableID3(Type, var TableID);
        exit(TableID);
  end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
