### ISSUE TITLE
[Function Expose] Codeunit 1522 "Workflow Request Page Handling" InsertReqPageField

### ISSUE THREAD

**Issue by kmistryebecs** [microsoft/ALAppExtensions#6764]
Please can you make the InsertReqPageField a global function which can be called externally to allow you to specify default fields that the user would likely want to filter on when creating a workflow.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
