### ISSUE TITLE
Table 5901 Service Item Line, CustomerNo check

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#6765]
Regarding to #3756 
I can see that you created procedure to handle this
![image](https://user-images.githubusercontent.com/54843470/78373313-be9c9d80-75ca-11ea-906a-b4099fb7ff9f.png)
But issue is that you did't call it 
![image](https://user-images.githubusercontent.com/54843470/78373417-decc5c80-75ca-11ea-8abc-a0ccfd852f88.png)
Can you please do it in next update?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
