### ISSUE TITLE
[Enum Request] Table 1701 "Deferral Header" Field  "Deferral Doc. Type"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#6766]
[Enum Request] Table 1701 "Deferral Header" Field  "Deferral Doc. Type"

We need the field "Deferral Doc. Type" as extendable enum in Table 1701 "Deferral Header". 
In this context, at least the same named field should also be extended in tables 1702 "Deferral Line", 5127 "Deferral Header Archive", 5128 "Deferral Line Archive".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
