### ISSUE TITLE
[Event Request] Table 36 "Sales Header" UpdateSalesLinesByFieldNo

### ISSUE THREAD

**Issue by kmistryebecs** [microsoft/ALAppExtensions#6767]
There is an event that is called for each Sales Line called OnBeforeSalesLineByChangedFieldNo and this event has an "IsHandled" parameter.  The "IsHandled" parameter should be set to false just before the call to OnBeforeSalesLineByChangedFieldNo

OLD CODE
------------
            repeat
                OnBeforeSalesLineByChangedFieldNo(Rec, SalesLine, ChangedFieldNo, IsHandled);
                if not IsHandled then

NEW CODE
------------
            repeat
                IsHandled := false;   // Added
                OnBeforeSalesLineByChangedFieldNo(Rec, SalesLine, ChangedFieldNo, IsHandled);
                if not IsHandled then

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
