### ISSUE TITLE
[Event Request] Codeunit 12 override vendor posting group

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6768]
Dear BaseApp Team,

In our vertical we sometimes need to override then information in the Vendor Posting Group. Therefore we need an event in three places in Codeunit 12 "Gen. Jnl-Post Line". The same event can be used in all three places.

The event signature we need is:
[IntegrationEvent(false, false)]
local procedure OnBeforeGetPayablesAccountL365(GenJnlLine : Record "Gen. Journal Line";var VendorPostingGroup : Record "Vendor Posting Group")
begin
end;

And we need it in the following places:
1) PostVend
local procedure PostVend(GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
       ...
    begin
        OnBeforePostVend(GenJnlLine);

        PurchSetup.Get();
        with GenJnlLine do begin
           ...
            
            VendPostingGr.Get("Posting Group");
//>>L365
            OnBeforeGetPayablesAccountL365(GenJnlLine,VendPostingGr); 
//<<L365
            PayablesAccount := VendPostingGr.GetPayablesAccount();

2) UnapplyVendLedgEntry
procedure UnapplyVendLedgEntry(GenJnlLine2: Record "Gen. Journal Line"; DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry")
    var
        ...
    begin
        ...

        Vend.Get(DtldVendLedgEntry."Vendor No.");
        Vend.CheckBlockedVendOnJnls(Vend, GenJnlLine2."Document Type"::Payment, true);

        OnUnapplyVendLedgEntryOnBeforeCheckPostingGroup(GenJnlLine, Vend);
        VendPostingGr.Get(GenJnlLine."Posting Group");
//>>L365
        OnBeforeGetPayablesAccountL365(GenJnlLine,VendPostingGr); 
//<<L365
        VendPostingGr.GetPayablesAccount();

3) VendPostApplyVendLedgEntry
procedure VendPostApplyVendLedgEntry(var GenJnlLinePostApply: Record "Gen. Journal Line"; var VendLedgEntryPostApply: Record "Vendor Ledger Entry")
    var
       ...
    begin
...
            Vend.Get(VendLedgEntry."Vendor No.");
            Vend.CheckBlockedVendOnJnls(Vend, "Document Type", true);

            OnVendPostApplyVendLedgEntryOnBeforeCheckPostingGroup(GenJnlLine, Vend);
            if "Posting Group" = '' then begin
                Vend.TestField("Vendor Posting Group");
                "Posting Group" := Vend."Vendor Posting Group";
            end;
            VendPostingGr.Get("Posting Group");
//>>L365
            OnBeforeGetPayablesAccountL365(GenJnlLine,VendPostingGr); 
//<<L365
            VendPostingGr.GetPayablesAccount();

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
