### ISSUE TITLE
[Event Request] Codeunit 378 - Transfer Extended Text: OnAfterSetAutoText

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/ALAppExtensions#6769]
To be able to handle a new/other entity with extended text, next to _Standard Text_, _Item_, _G/L Account_ and _Resource_ on sales lines, purchase lines, finance charge memos and reminders we need a new event publisher called **OnAfterSetAutoText** in the following functions in COD378:
- SalesCheckIfAnyExtText
- ReminderCheckIfAnyExtText
- FinChrgMemoCheckIfAnyExtText
- PurchCheckIfAnyExtText
- ServCheckIfAnyExtText

This publisher should be placed as shown below (code taken from SalesCheckIfAnyExtText(), but similar in the other functions):

```
AutoText := false;
if Unconditionally then
    AutoText := true
else
    case SalesLine.Type of
        ...
    end;
//Insert-Start
OnAfterSetAutoText(SalesLine, Unconditionally, AutoText);
//Insert-End
if AutoText then begin
```
Syntax of this new publisher (in SalesCheckIfAnyExtText but similar in the other functions metioned above) would be:
```
[IntegrationEvent(false, false)]
local procedure [IntegrationEvent] OnAfterSetAutoText(var SalesLine: Record "Sales Line"; Unconditionally: Boolean; var AutoText: Boolean)
```

**Comment by lvanvugt** [comment]
With this there should also be the following done (not sure if this is the right place to ask):
- **Table Name** option field on _Extended Text Header_ table (279) has to be converted into an Enum
- This also applies to same field on _Extended Text Line_ table (280)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
