### ISSUE TITLE
[Event Request] Extend OnBeforeFinishPosting

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/ALAppExtensions#6770]
Hello
Is it possible to add one additional parameter in event OnBeforeFinishPosting from Codeunit 12 "Gen. Jnl.-Post Line":
from 
OnBeforeFinishPosting(var GenJournalLine: Record "Gen. Journal Line")
to 
OnBeforeFinishPosting(var GenJournalLine: Record "Gen. Journal Line"; var TempGLEntryBuf: Record "G/L Entry" temporary)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
