### ISSUE TITLE
[Extensibility Enhancement] Report 292 "Copy Sales Document" OnPreReportOnBeforeCopySalesDoc event

### ISSUE THREAD

**Issue by kmistryebecs** [microsoft/ALAppExtensions#6771]
Please could you add extra parameters to the OnPreReportOnBeforeCopySalesDoc event in Report 292 "Copy Sales Document" for the following...

```
* DocType
* DocNo
* SalesHeader
```
This is to enable us to identify which documents are being copied from/to

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
