### ISSUE TITLE
[Function Expose] Codeunit 6620 UpdateCustLedgEntry

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6773]
Hello,

Could you please expose the function UpdateCustLedgEntry in Codeunit 6620 as global/external?
(like you did with the counterpart function UpdateVendLedgEntry)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SjoerddeClippelaar** [comment]
When can we expect this to be released? It is not in BC160 CU5. Thank you for your reply.
