### ISSUE TITLE
NAVDataUpgrade failed with "Object of type CodeUnit with ID 2 could not be found."

### ISSUE THREAD

**Issue by InnoNavSupport** [microsoft/ALAppExtensions#6774]
Hi Microsoft Team,

I try to update a Cronus Database with no customisations to BC16.
Is there any proper documentation updating from BC15 to BC16 available?
I am using  https://docs.microsoft.com/de-de/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15

**more details see below:**

**from OnPremise BC Version**
BC15.5 (15.5.41926.0)
**to OnPremise BC Version**
BC16.0 (16.0.11240.12076)

**from Docker Image:**
'mcr.microsoft.com/businesscentral/onprem:15.5.41926.0-w1-ltsc2019' 
**to Docker Image:**
'mcr.microsoft.com/businesscentral/onprem:w1'

The Cronus-DB is on a separate Local MS-SQL-Server 2019 installed.

The error occured after converting the database to BC16 and trying to upgrade the System Application with following cmdlet:

**#Upgrade System Application**
Publish-NAVApp -ServerInstance $navServerInstance1 -Path "C:\Applications\System Application\Source\Microsoft_System Application.app"
Sync-NAVApp -ServerInstance $navServerInstance1 -Tenant default -Name "System Application" -Version 16.0.11240.12076
Start-NAVDataUpgrade -ServerInstance $navServerInstance1 -Tenant default -FunctionExecutionMode Serial -SkipAppVersionCheck
Get-NAVDataUpgrade -ServerInstance $navServerInstance1 -ErrorOnly  
(see Screenshots below)

![image](https://user-images.githubusercontent.com/62563638/79359113-72dee200-7f42-11ea-91bb-80641d3a76ee.png)
![image](https://user-images.githubusercontent.com/62563638/79359126-77a39600-7f42-11ea-9f99-add56d8eed56.png)
![image](https://user-images.githubusercontent.com/62563638/79359137-7c684a00-7f42-11ea-812b-068f874c776e.png)

**Comment by AlexanderYakunin** [comment]
Hello! This forum is for extensibility requests for partner extension development. We have no support for addressing bugs here. Can you please submit request to Support instead?

**Comment by InnoNavSupport** [comment]
Hello!

Sorry, that was my fault.
Thanks for the answer.
