### ISSUE TITLE
[Event Request] Codeunit 393 "Reminder-Issue" - OnBeforeReminderEntryInsert

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#6775]
Can you add parameter ReminderLine to event OnBeforeReminderEntryInsert in codeunit "Reminder-Issue"?

![image](https://user-images.githubusercontent.com/46031720/79420754-da844400-7fb9-11ea-8bc3-c475afd65be1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
