### ISSUE TITLE
[Event Request] Codeunit 393 "Reminder-Issue" - OnBeforeCustLedgEntryModify

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#6776]
Can you add event OnBeforeCustLedgEntryModify in function UpdateCustLedgEntryLastIssuedReminderLevel in codeunit 393 "Reminder-Issue", with parameter "Cust. Ledger Entry" as reference?

![image](https://user-images.githubusercontent.com/46031720/79421135-77df7800-7fba-11ea-919b-4916d3a29381.png)

![image](https://user-images.githubusercontent.com/46031720/79421182-9180bf80-7fba-11ea-9f8b-af9c16a280cb.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
