### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeConfirmSellToContactNoChange

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#6780]
Dear ALAppExtensions team,
Through this issue we would like to request event `OnBeforeConfirmSellToContactNoChange` in table 36 Sales Header to be implemented.
The implementation would be similar to that for the existing event `OnBeforeConfirmBillToContactNoChange` in table 36 Sales Header, which was requested via #1665.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
