### ISSUE TITLE
[Event Request] Table 79 Company Information - OnBeforeIBANError

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#6781]
Please add a new publisher event to the function IBANError as follows:

```
.
.

LOCAL IBANError()
//>> Start New Publisher Call
OnBeforeIBANError(Rec, IsHandled);
IF IsHandled THEN
  EXIT;

//<< End New Publisher Call
IF NOT ConfirmManagement.ConfirmProcess(Text000,TRUE) THEN
  ERROR('');
.
.
```

New Publisher Event:
```
LOCAL [IntegrationEvent] OnBeforeIBANError(VAR Rec : Record "Company Information";VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
