### ISSUE TITLE
[Event Request] Codeunit 99000845 - Reservation Management - OnBeforeStopReservation

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#6783]
Dear ALAppExtensions team,
Through this issue we would like to request event publisher `OnBeforeStopReservation` to be added to codeunit 99000845 Reservation Management in procedure `AutoReserve` with the following signature:
```pascal
OnBeforeStopReservation(VAR CalcReservEntry : Record "Reservation Entry"; VAR FullAutoReservation : Boolean; VAR AvailabilityDate : Date; VAR MaxQtyToReserve : Decimal; VAR MaxQtyToReserveBase : Decimal; VAR StopReservation: Boolean)
```
with **VAR** parameters.

This event would then be called in procedure `AutoReserve` as follows:
```pascal 
        OnBeforeStopReservation(CalcReservEntry,FullAutoReservation,AvailabilityDate,MaxQtyToReserve,MaxQtyToReserveBase,StopReservation); // << New event
        if StopReservation then begin
            FullAutoReservation := true;
            exit;
        end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
