### ISSUE TITLE
Empty Subform Pages

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#6785]
Dear Base-App-Team,

there are a few empty pages (IDs 7172..7176 and 7182..7188) which seem to be legacy pages from back when doing page-Transformation from Classic Client forms to RTC pages.

![image](https://user-images.githubusercontent.com/35929603/79443808-9fded380-7fda-11ea-8e03-ea1bd4cebf20.png)

Maybe now, when we're all staying home, is the perfect time for some clean up? ;-)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
