### ISSUE TITLE
[Saas] Item Attribute Value Selection - function ValidateType - variable CultureInfo

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#6786]
We've duplicated the entire 'Item Attribute' framework to custom tables. When moving to cloud, we get compilation errors on DotNet CultureInfo. Since this is standard BC code, how can we make sure this code is cloud compatible?

```

local procedure ValidateType(Variant: Variant; ValueToValidate: Text; ItemAttribute: Record "Item Attribute")
    var
        TypeHelper: Codeunit "Type Helper";
        CultureInfo: DotNet CultureInfo;
    begin
        if (ValueToValidate <> '') and not TypeHelper.Evaluate(Variant, ValueToValidate, '', CultureInfo.CurrentCulture.Name) then
            Error(AttributeValueTypeMismatchErr, ValueToValidate, ItemAttribute.Type);
    end;
```

**Comment by AlexanderYakunin** [comment]
As we use DotNet CultureInfo in TypeHelper.Codeunit.al and dot net wrappers, it compiles without problems. I think something wrong with download of AL Symbols in your case, but if you do it, you should be able to compile.

**Comment by fvet** [comment]
@AlexanderYakunin My question was more about us having copied the 'Item Attribute' objects one on one and modifying some keys to make it more extensible. Since the BC objects still contain some 'dotnet' references, we encounter compilation error on our objects as well when targetting cloud.

Seems like I could indeed use codeunit DotNet_CultureInfo.CurrentCultureName; although it would have been better in the BC objects used the dotnet wrapper codeunits too.

![image](https://user-images.githubusercontent.com/25268332/80319232-b8878e80-880f-11ea-8bfd-8a01cfb24256.png)

![image](https://user-images.githubusercontent.com/25268332/80319242-c6d5aa80-880f-11ea-92c2-55bf63ff3960.png)
