### ISSUE TITLE
How to modify default reports from BC !

### ISSUE THREAD

**Issue by TharunMuthu** [Microsoft/ALAppExtensions#679]
Hi ,
I a trying to modify default report(Customer - Detail Trial Bal.) ? can you please guide 
Note:
i have exported the layout using below link but i did not get AL source code ! 
but i need to add one column in this default report ! bit confusing here !
since one project went live 2 weeks before now customer is pushing us !
can you please guide !!!

https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout#MakeChangesToLayout

**Comment by srenders** [comment]
Hi,

As you can clearly read in the documentation, you can not modify the dataset of an existing report!
You can change the layout, word and or rdlc, but not the dataset. To see how you can change the layout, you can have a look at the docs website as mentioned in your post. To have a look at how you can create a new report, have a look here: http://thinkaboutit.be/2017/08/how-do-i-create-a-report-and-layout-in-vscode/
I suggest you export the current report to .al, modify the number, add the field(s) to the dataset and layout(s) and upload it, in an extension, as a new report. Then you use the events, to have it replace the current one...

**Comment by TharunMuthu** [comment]
Hi ,

Thanks for your reply. **How do export report to .al ?** because in _**BC-OnCloud there is no development environment !only Client is available !!**_
Requirement: Need to add one extra field in default  **Customer - Detail Trial Bal. Report**

**Comment by srenders** [comment]
Your usage of exclamation marks tells me you are probably a bit frustrated. I also find it surprising how you are able to support a customer in an environment you are clearly not really familiar with...

You need to figure out the version of the product your customer is using. You can use the System Information page to do that:
http://thinkaboutit.be/2018/09/what-is-my-build-no-in-business-central/
http://www.waldo.be/2018/11/09/system-information-in-microsoft-dynamics-365-business-central/
https://blogs.msdn.microsoft.com/freddyk/2018/12/05/business-central-build-numbers/

Then you need to use either docker or the on premises development environment to export a version of that report to txt and convert it to al.
https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/

**Comment by TharunMuthu** [comment]
Thanks for your detailed explanation .**Finally i did !!** 
once again thanks for your valuable reply .Mary Christmas !
