### ISSUE TITLE
Report 6 Trial Balance - Save Values Property

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#6790]
We would like to be able to set the SaveValues property of the Request Page somehow in an ReportExtension of Report 6  Trial Balance. 
Not sure how to do this or how to request for this.

**Comment by AlexanderYakunin** [comment]
To my knowledge we do not support report extensions yet. Are you sure?

**Comment by mboon75** [comment]
Yes sure, but how can we get this fixed without having to copy the report to our own granule?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
