### ISSUE TITLE
Codeunit "Config. XML Exchange" - ExportPackage

### ISSUE THREAD

**Issue by demiliani** [microsoft/ALAppExtensions#6792]
Actually we have the possibility to import a RapidStart package in a SaaS environment by using two possible ways:
- Method ImportRapidStartPackageStream in Codeunit "Config. Package - Import"
- Method ImportPackageXMLFromStream in Codeunit "Config. XML Exchange"

But there are no methods available for exporting a Rapidstart Package dinamically from AL code.
Codeunit "Config. XML Exchange" has the following methods:
- ExportPackage
- ExportPackageXML
- ExportPackageXMLDocument
but they're all for on-premise usage (cannot be used on SaaS).
Can you add a new method called ExportPackageXMLFromStream that can be used on a SaaS environment to dinamically export a Configuration Package?
Thanks in advance.

**Comment by fvet** [comment]
Any plans on providing a powershell equivalent allowing to run 'Export-NavConfigurationPackage' to extract package data easily via scripts?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by demiliani** [comment]
Thanks @JesperSchulz
