### ISSUE TITLE
[EventRequest] 5705 OnBeforeGenNextNo

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#6793]
Hi,

please take a look to #2210 closed on **25 May 2019** as "ships-in-future-update" still not available in V150... is there anyone that manage these requests? If not, let do partners and start thinking to allows the upload of custom base application in SaaS.

S.

**Comment by StanPesotskiy** [comment]
On your initial request https://github.com/microsoft/ALAppExtensions/issues/2210 you asked to remove extra line with NoSeriesMgt.GetNextNo. It has already been removed.
You can use the existing event OnBeforeInsertTransRcptHeader to redefine value of "No." field.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by sgiordy** [comment]
@StanPesotskiy NO in #2210 I asked:

> In CU 5705 the OnBeforeGenNextNo event is missing and we request it like in Post-Shipment.

About using the "OnBeforeInsertTransRcptHeader" are you new with AL development? What about useless NoSeries incrementation?

![5705](https://user-images.githubusercontent.com/17341714/79790291-cf2f7080-834b-11ea-8086-03549b4937ae.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
