### ISSUE TITLE
Codeunit 6620 Copy Document Mgt. - OnAfterCopyPurchInvLine & similar

### ISSUE THREAD

**Issue by chris-amco** [microsoft/ALAppExtensions#6794]
Purchase Credit Memo --> "Get Posted Document Lines to Reverse" : 
I want to store the details (Doc No, Doc Type, Line No) of the copied line on the new line. 

I tried OnAfterCopyPurchInvLine() in codeunit 6620, but it did not work, presumably because parameter "ToPurchaseLine" is missing keyword "var".

Similar events that have the same issue are:
OnAfterCopyPurchInvLine
OnAfterCopyPurchCrMemoLine
OnAfterCopyPurchRcptLine
OnAfterCopyReturnShptLine

Thanks in advance !

**Comment by chris-amco** [comment]
I've since found that I can use OnBeforeInsertToPurchLine() for my requirement instead. But I still think the events I mentioned need "var" on "ToPurchaseLine".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
