### ISSUE TITLE
CPD414 - OnBeforeReleaseSalesDoc - Add IsHandled

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#6795]
Could you please add a IsHandled-Parameter to the OnBeforeReleaseSalesDoc-Event in COD414.

![image](https://user-images.githubusercontent.com/45033081/79545840-a8461580-8091-11ea-8056-94b3045dd41c.png)

Background is, that we want to delete empty Sales Headers at release.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
