### ISSUE TITLE
[Event Request] Table 18 Customer - OnValidatePrimaryContactNoOnBeforeCheckContactCompanyNo

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6800]
Requesting a new Event Publisher on Table 18 Customer

Event
`OnValidatePrimaryContactNoOnBeforeCheckContactCompanyNo(Contact   : Record Contact; ContactBusinessRelation : Record "Contact Business   Relation"; VAR IsHandled : Boolean)`

**Code**
## Primary Contact No. - OnValidate()
```
Contact := '';
IF "Primary Contact No." <> '' THEN BEGIN
  Cont.GET("Primary Contact No.");

  ContBusRel.FindOrRestoreContactBusinessRelation(Cont,Rec,ContBusRel."Link to Table"::Customer);
```
**>>> New Code**
```
  OnValidatePrimaryContactNoOnBeforeCheckContactCompanyNo(Cont,ContBusRel,IsHandled);
  IF NOT IsHandled THEN
```
**<<< New Code**
```
    IF Cont."Company No." <> ContBusRel."Contact No." THEN
      ERROR(Text003,Cont."No.",Cont.Name,"No.",Name);

  IF Cont.Type = Cont.Type::Person THEN
    Contact := Cont.Name;

  IF Cont.Image.HASVALUE THEN
    CopyContactPicture(Cont);

  IF Cont."Phone No." <> '' THEN
    "Phone No." := Cont."Phone No.";
  IF Cont."E-Mail" <> '' THEN
    "E-Mail" := Cont."E-Mail";
END ELSE
  IF Image.HASVALUE THEN
    CLEAR(Image);
```

In Our Solution we have customers which are linked to a Contact which is not linked to a Company. We can sell to private contacts / Customers. We need to be able to skip this check, please add the requested publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
