### ISSUE TITLE
[Event Request] extra parameter on OnBeforeInsertPmtDiscVATForGLEntry in codeunit 12

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6803]
Dear BaseApp team,

In our vertical solution we have to do some additional VAT handling, that requires changing Purchase VAT Account on VAT Posting Setup.

We would like to request adding VATPostingSetup as a Var parameter to the event OnBeforeInsertPmtDiscVATForGLEntry in Codeunit 12 Gen. Jnl.-Post Line

Suggested event signature:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertPmtDiscVATForGLEntry(var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; GenJournalLine: Record "Gen. Journal Line"; VATEntry: Record "VAT Entry"; var Record "VAT Posting Setup")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
