### ISSUE TITLE
[External Function] Table "Country/Region" procedure "IsIntrastat"

### ISSUE THREAD

**Issue by david-kovarik** [microsoft/ALAppExtensions#6804]
Hello everyone,

in Czech standard, there is a procedure called "IsIntrastat". Would it be possible to delete Scope declaring this function only for OnPrem? It would be great to be able to use this function in Extension development aswell.

Kind regards.

**Comment by AlexanderYakunin** [comment]
As I can see this procedure already [Obsolete('Moved to Core Localization Pack for Czech.', '18.0')]. Please use procedure from place instead
