### ISSUE TITLE
[External Function] Codeunit "FA General Report" procedure "SetFATaxDeprGroup"

### ISSUE THREAD

**Issue by david-kovarik** [microsoft/ALAppExtensions#6805]
Hello everyone,

in Czech standard, there is a procedure called "SetFATaxDeprGroup". Would it be possible to delete Scope declaring this function only for OnPrem? It would be great to be able to use this function in Extension development aswell.

Kind regards.

**Comment by AlexanderYakunin** [comment]
This procedure is [Obsolete('Moved to Fixed Asset Localization for Czech.', '18.0')], please use same from new place.
