### ISSUE TITLE
[Event Request] Report 1003 Post Invt. Cost to G/L - Test - OnBeforeCheckPostingSetup

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6807]
Requesting a new Event Publisher on Report 1003 Post Invt. Cost to G/L - Test

Event
`OnBeforeCheckPostingSetup(InvtPostToGLTestBuf : Record "Invt. Post to G/L Test Buffer";VAR HasError : Boolean;VAR IsHandled : Boolean)`

**Please set IncludeSender to Yes!**

**Code**
## LOCAL CheckPostingSetup(InvtPostToGLTestBuf : Record "Invt. Post to G/L Test Buffer") : Boolean
**>>> New Code**
```
OnBeforeCheckPostingSetup(InvtPostToGLTestBuf,HasError,IsHandled);
IF IsHandled THEN
  EXIT(HasError);
```
**<<< New Code**
```
WITH InvtPostToGLTestBuf DO
  IF "Invt. Posting Group Code" <> '' THEN BEGIN
    IF NOT InvtPostSetup.GET("Location Code","Invt. Posting Group Code") THEN BEGIN
      AddError(
        STRSUBSTNO(
          Text011,
          InvtPostSetup.TABLECAPTION,
          FIELDCAPTION("Location Code"),"Location Code",
          FIELDCAPTION("Invt. Posting Group Code"),"Invt. Posting Group Code"));
      EXIT(FALSE);
    END
  END ELSE
    IF NOT GenPostSetup.GET("Gen. Bus. Posting Group","Gen. Prod. Posting Group") THEN BEGIN
      AddError(
        STRSUBSTNO(
          Text011,
          GenPostSetup.TABLECAPTION,
          FIELDCAPTION("Gen. Bus. Posting Group"),"Gen. Bus. Posting Group",
          FIELDCAPTION("Gen. Prod. Posting Group"),"Gen. Prod. Posting Group"));
      EXIT(FALSE);
    END;
EXIT(TRUE);
```

In Our Solution we know Job locations, for these Job Lications we do not have a specific record in teh inventory Posting Setup. We define a record with a blank location code and then every possible Inventory Posting Group. So in this check report we also need to have the possibility to make that choise. As said we need to access some global functions, therefore we need the property **IncludeSender** set to **Yes**. Could you please add the requested Publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
