### ISSUE TITLE
[Event Request] table 18 Customer - OnBeforeCreateCustomerFromTemplate

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#6809]
Can you add customer rec and Customer variabel as reference parameters in event OnBeforeCreateCustomerFromTemplate in function CreateCustomerFromTemplate?

![image](https://user-images.githubusercontent.com/46031720/79728315-096a2500-82ee-11ea-9fa4-bbab9dbcdf25.png)

![image](https://user-images.githubusercontent.com/46031720/79728387-23a40300-82ee-11ea-8793-cfd49c9e16b1.png)

**Comment by RomanZanizdra** [comment]
Hi @auzhhv . It's not fully clear how these parameters are going to be used? Could you be so kind to describe a little. Also do we need "IsHandled" pattern here?

**Comment by auzhhv** [comment]
> Hi @auzhhv . It's not fully clear how these parameters are going to be used? Could you be so kind to describe a little. Also do we need "IsHandled" pattern here?

Hi @RomanZanizdra,

I can see that I have written table 18 customer, but the function is in Customer Card, sorry about that.

We have created an integration with Azure Service Bus. Updated info is sent to ASB when the customer is modified. As the template code does a lot of modifies we want to tell it not to send info when the customer is updated from a template. I'm going to use the info i set in OnAfterModify. In this function the Customer record is local, so I have no way to set a field or call a function to set a global variabel. I have also requested more events in the template code to be able to handle it there ref #6707. I dont ned the handled pattern, I want to run the same code, but set some info that I am going to use later.

**Comment by RomanZanizdra** [comment]
Hi again @auzhhv . Sorry but I still don't fully understand event parameters.
From my point of view you need either Rec parameter (which is "Customer") and "IsHandled" pattern because of the next code below or you need Customer parameter without Rec because it will be overwritten with again code below. Where am I wrong?
                Copy(Customer);
                CurrPage.Update;

**Comment by auzhhv** [comment]
Hei @RomanZanizdra, Yes, you are right. I see now that I only need the customer variabel :)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
