### ISSUE TITLE
[Event Request] Codeunit 99000792 - Function CreateProdOrder

### ISSUE THREAD

**Issue by wfelberbauer** [microsoft/ALAppExtensions#6810]
we need a ishandled pattern in the function "CreateProdOrder" befor the codelines:
**`//-NEW Line
**IsHandled := FALSE;
OnBeforeProcessItem(ProdOrder,SalesLine,IsHandled);
IF NOT IsHandled THEN BEGIN**
//+NEW LINE**
IF ProdOrder."Source Type" = ProdOrder."Source Type"::Item THEN BEGIN
  ProdOrderLine.SETRANGE(Status,ProdOrder.Status);
  ProdOrderLine.SETRANGE("Prod. Order No.",ProdOrder."No.");

  IF ProdOrderLine.FINDFIRST THEN BEGIN
    ProdOrderRowID 

....
**//-NEW Line
**END;**
//+NEW`**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
