### ISSUE TITLE
TempBlob.Blob in Report Column

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#6812]
Hey, I've got a further Question regarding Blob. 

We used to have a "Record TempBlob" variable HeaderBarcode, which we filled from a previously created Picture and then displayed in a report. The Code for displaying it was Pretty simple 

```
                column(HeaderBarcode; HeaderBarcode.Blob)
                {
                }
```

But the tempblob-Table was replaced by the "Temp Blob" codeunit and that codeunit doesn't have a function "Blob()" to simply get the binary value. 

What Kind of variable do we Need in a report to Display the Picture blob value and how do we get it from the tempblob-codeunit?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help with this question?

**Comment by JulianTillmann** [comment]
any news on that? we're trying to finish the product and this is a major issue for us right now

**Comment by JesperSchulz** [comment]
I am not sure that I get the full picture, but based on what you describe, you just need a record with a field of type blob for your purpose. As TempBlob isn't accessible any longer, you can either create your own table with a blob field in it, or use one of the many tables with blob fields already in the application. As you're only using the table as a temporary table, any table with blob field would do, really.
Would that work for you?

**Comment by JulianTillmann** [comment]
So I could in theory create my own "tempblob" table and use it's field? 

we would like to keep the dependencies on other apps as minimal as possible, of course

**Comment by JesperSchulz** [comment]
Correct, that would be the easiest solution. You don't need "our" TempBlob table to get a table with a blob field :-) I will close this ticket, as it sounds as if you're unblocked. If I'm mistaken, please reopen! Best of luck finishing your product!

**Comment by JulianTillmann** [comment]
seems to be working, thanks! 👍

**Comment by JulianTillmann** [comment]
@JesperSchulz 
unfortunately we need to re-open this case. for any PerTenantExtensions we cannot use our own TempBlob-table, as intended because of the .NET streaming methods. the Microsoft Base App TempBlob-Table is working for now, but is marked as obsolete. 

please provide a solution to use Blob-content directly in a report column as soon as possible.

`
column(BlobImage; TempBlob.Blob)
            {
            }`
`column(ShowBlobImage; NOT TempBlob.Blob.HasValue())
            {
            }
`

**Comment by GiorgosPa** [comment]
@JulianTillmann you should not require any .NET streaming methods, where exactly is using a different table lacking? What are you trying to achieve with the .NET methods?
