### ISSUE TITLE
[Event Request] Codeunit ReportManagement: Add RecordRef-Parameter on OnAfterDocumentPrintReady

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/ALAppExtensions#6813]
Please add a **RecordRef**-Parameter on **OnAfterDocumentPrintReady** in Codeunit ReportManagement.

Before:
`local procedure OnDocumentPrintReady(ObjectType: Option "Report","Page"; ObjectID: Integer; ObjectPayload: JsonObject; DocumentStream: InStream; var Success: Boolean);`

After:
`local procedure OnDocumentPrintReady(ObjectType: Option "Report","Page"; ObjectID: Integer; RecordRef: RecordRef; ObjectPayload: JsonObject; DocumentStream: InStream; var Success: Boolean);`

We are working on a Document Management Integration and there is currently no way to find you out which documents are get printed, if you select e.g. a few Posted Sales Invoices at the same time. The _filterviews_ in **ObjectPayload** only has a filter on the **Bill to Customer No.**, but does not represent the currently selected records.

**Comment by mazhelez** [comment]
Hi @DanielGoehler 

With the current design, it isn't possible to pass the record that is being passed.

Can you elaborate on the scenarios you want to support? Maybe there's a another way to achieve the desired behavior.

**Comment by DanielGoehler** [comment]
Hi @mazhelez,

to comply with legal requirements of archiving outgoing sales invoices and other bookkeeping related documents, we need to log which sales invoice is being printed, to reprint it as PDF and upload it to a [Document Management System](https://en.wikipedia.org/wiki/Document_management_system).

Since there is no way anymore customize existing reports in the BaseApp in the cloud, we tried to utilize the **OnDocumentPrintReady** event.

But we found out, that this event does not work as expected. E.g. if you select several documents in the "Posted Sales Invoices" Page, you cannot figure out which documents are being printed. _filterviews_ in **ObjectPayload** only has a filter on the **Bill to Customer No.**, but selected records are being missing.

**Comment by mazhelez** [comment]
Thanks a lot for the clarification!

**Comment by sorenfriisalexandersen** [comment]
> Hi @mazhelez,
> 
> to comply with legal requirements of archiving outgoing sales invoices and other bookkeeping related documents, we need to log which sales invoice is being printed, to reprint it as PDF and upload it to a [Document Management System](https://en.wikipedia.org/wiki/Document_management_system).
> 
> Since there is no way anymore customize existing reports in the BaseApp in the cloud, we tried to utilize the **OnDocumentPrintReady** event.
> 
> But we found out, that this event does not work as expected. E.g. if you select several documents in the "Posted Sales Invoices" Page, you cannot figure out which documents are being printed. _filterviews_ in **ObjectPayload** only has a filter on the **Bill to Customer No.**, but selected records are being missing.

Does the legislation specifically say what is the nature of a Document Management System? The definition above looks very broad and seems that BC could be that system. You could use the Attachment feature to automatically generate and store PDFs to an invoice to store them in a digital/non-editable way, with the added benefit of always having a printout of the sent invoice. 

Any elaboration is very welcome.
Thanks.

**Comment by DanielGoehler** [comment]
Hi @sorenfriisalexandersen,

if you print out an invoice in Business Central lets you delete that Sales Invoice. I suspect also the attached PDF will be deleted. In many country you are legally requirement to keep a copy of your invoices. You can keep it as hard copy or in a Document Management System.

![image](https://user-images.githubusercontent.com/9556549/86022301-76a2e080-ba2a-11ea-9a98-c4535e91fc98.png)

**Comment by sorenfriisalexandersen** [comment]
Hi @DanielGoehler 
I think you can safely store the documents in BC as attachments by configuring user rights to not allow deletion of posted invoices and/or their documents. The former is a change in the Sales & Receivables Setup (to disallow deleting posted documents after a certain date), and the latter could be changed by user rights. This would ensure that no one could tamper with generated/stored documents. You could then use a Job Queue job to auto generate attachments for all documents periodically.

**Comment by DanielGoehler** [comment]
Hi @sorenfriisalexandersen,

I'm sorry, but I think you are missing the point here. It is not up to you to decide, if a customer a Document Management System or not. And also how **I** implement the processes.
More importantly your suggestion doesn't even work with the current event parameters, because in a batch print situation, the system doesn't know which Invoices are being printed, so even if I want to, I can't reprint them and save as PDF them inside Business Central. 

**And this the hole point why I like to have the RecordRef-Parameter.**

**Comment by DanielGoehler** [comment]
Hi @mazhelez,

in **OnAfterSubstituteReport** (also Codeunit **ReportManagement**) I have the **RecordRef** and it works correctly in this process.

**Comment by sorenfriisalexandersen** [comment]
Hi @DanielGoehler 
I get the point. The thing is that it is the customer that has to be compliant - not the product. 
We can then choose how to support the customer in fulfilling compliance needs.
In some cases we would support with features, events, and in other cases with workarounds. 
One take on that could be that we consider BC to be considered a Document Management System when it comes to digital storage. That decision is up to us.

It seems we have a choice:

1. Make the change according to your request, which would be breaking.
2. Find a way to support you in using attachments as storage.

Will get back asap.

Thanks.

**Comment by DanielGoehler** [comment]
Hi @sorenfriisalexandersen,

Microsoft fundamentally changed the development architecture of Dynamics NAV/Business Central and therefor offered to help out with these Event Requests to transition the current solutions. So here is my wish for a tiny additional parameter.

Could you explain why this change would be breaking, since all event parameter are optional? Nobody would notice, right?

Workaround are also fine with me. E. g. **ObjectPayload** could also provide this information. Currently it doesn't. (See above.)

**Comment by DanielGoehler** [comment]
Hi @sorenfriisalexandersen,

regarding using attachments: How would I know if this file was printed or put purposely there from a user? I only need the first case.

**Comment by sorenfriisalexandersen** [comment]
@mazhelez to provide some information on the breaking nature of this.

**Comment by dtkb** [comment]
Isn't it as simple that adding a new parameter means subscribers using the old parameter list are no longer valid? I did not know that "all event parameter are optional". I'm not even allowed to change/fix argument names, as VS Code insists they must match.

**Comment by DanielGoehler** [comment]
Hi @dtkb,

you should not change the existing parameter (name or data type) of Publisher Events. That breaks the Subscriber Events.
But you can add new parameter as you like. Try it out. I only add the parameter I really need.

**Comment by DanielGoehler** [comment]
Hi @sorenfriisalexandersen,
Hi @mazhelez,

can **RecordRef** be added or is there an alternative?

**Comment by DanielGoehler** [comment]
Hi @sorenfriisalexandersen,
Hi @mazhelez,

is there any update on this?

**Comment by DanielGoehler** [comment]
Hi @AlexanderYakunin, can you say anything about this Event Request?
Didn't got an answer from @sorenfriisalexandersen and @mazhelez since June 30th.

**Comment by AlexanderYakunin** [comment]
Hi Daniel!

As I can see in our systems, this request is currently on regulatory feature ream and therefore @sorenfriisalexandersen is best person to reply on next steps. But he is currently on vacations.

**Comment by DanielGoehler** [comment]
Thanks @AlexanderYakunin

**Comment by JesperSchulz** [comment]
Hi Daniel,

sorry about the delay, but we had to asses the workload required to complete your request, as it unfortunately isn't trivial. Allow me to paste in the findings on one of our engineers:

"The OnDocumentPrintReady is not an archiving event, but an extension print event function. The request doesn't fit well with the current execution model, where we merge multiple invoices into one large output document. To be compliant to the request, we will have to change the model and render N separate PDF documents and add a new system trigger when each document is rendered (OnDoucmentRendered or something like it).
This is a larger feature request and will have a high impact on app code as well since most of the Document rendering takes place in app code."

What that means is, that we will have to add this effort to our backlog for our master releases, where it will have to get prioritized against other, larger work loads. We will not be able to process this as a "bug".

Unfortunately, I cannot predict, when we will have a solution to this problem, but you may have to wait a while.

Let me know, if you need more details. If not, kindly close this request - we now have it in our backlog :-)

**Comment by DanielGoehler** [comment]
Thanks!

Would it be possible to get the current Filters (CurrPage.SetSelectionFilter -> Rec.GetFilters()) in ObjectPayload?

**Comment by JesperSchulz** [comment]
We'll look into it :-)

**Comment by DanielGoehler** [comment]
Hi @StanPesotskiy, what is the solution? RecordRef or CurrPage.SetSelectionFilter in ObjectPayload?

**Comment by DanielGoehler** [comment]
Hi @JesperSchulz, do you know what the solution is?

**Comment by StanPesotskiy** [comment]
Let it keep open to get the answer when solution is ready.

**Comment by JesperSchulz** [comment]
We actually don't have a solution yet. That work item still lingers in our backlog, I noticed. We'll get this one prioritized, as it now missed the 18.0 release (for which I actually had planned this). We'll try to get this out with 18.1 instead.
