### ISSUE TITLE
BC160 - Dimension Management procedure TypeToTableID3 should NOT be Option but ENUM instead

### ISSUE THREAD

**Issue by eque2al** [microsoft/ALAppExtensions#6814]
In V16 Enums have replaced Options in a fair few places (great!) but it seems that Dimension Management codeunit has been missed..!  

In particular the procedure **TypeToTableID3** has the first parameter as Type: Option .. when will this be changed to Enum please as this is causing Errors (of type Warning) in our solution...

Thanks!

**Comment by AlexanderYakunin** [comment]
Conversion of Options to Enum is large effort and it will take good time. We are aware about all warnings and working to address them. Currently it should not affect your solutions.
