### ISSUE TITLE
[Event Request] Report 5753 Get Source Documents - OnAfterSalesLineOnAfterGetRecordOnBeforeVerifyItemNotBlocked

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6820]
Requesting a new Event Publisher on Report 5753 Get Source Documents

Event
`OnAfterSalesLineOnAfterGetRecordOnBeforeVerifyItemNotBlocked(SalesHeader : Record "Sales Header"; SalesLine : Record "Sales Line"; VAR IsHandled : Boolean)`

**Code**
## Sales Line - OnAfterGetRecord()
```
IsHandled := FALSE;
OnBeforeSalesLineOnAfterGetRecord("Sales Line","Warehouse Request",RequestType,IsHandled);
IF IsHandled THEN
  CurrReport.SKIP;
```
**>>> New Code**
```
IsHandled := FALSE;
OnAfterSalesLineOnAfterGetRecordOnBeforeVerifyItemNotBlocked("Sales Header","Sales Line",IsHandled);
IF NOT IsHandled THEN
  VerifyItemNotBlocked("No.");
```
**<<< New Code**

In Our Solution we know Job deliveries, these were build opun Sales Orders, for these Job deliveries  we proceed with lines which have a Qty. to ship > 0, Lines where Qty. to ship is zero we want to skip. Therefore we need the flexibility to skip the check in this scenario. Could you please add the requested Publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
