### ISSUE TITLE
Intercompany Posting Bug, Due to "Your Reference" Field Length

### ISSUE THREAD

**Issue by AbhishekSaini24** [microsoft/ALAppExtensions#6821]
There is a std bug in Intercompany posting.
I have created Intercompany Sales Invoice, entered the External Document No. of 34 Char and posted the sales invoice. In other company when I have tried to post the Purchase Invoice then system give the error "The Length of the string is 34, but it must be less than or equal to 20 characters".
 While debugging I found below code due to which error was coming.

Codeunit 90. Function-CheckICDocumentDuplicatePosting

      IF "Your Reference" <> '' THEN BEGIN
        PurchInvHeader.RESET;
        PurchInvHeader.SETRANGE("Order No.","Your Reference"); // Here Order No. field is of 20 Characters & Your Reference field length is 35, due to which error was coming.

        PurchInvHeader.SETRANGE("Buy-from Vendor No.","Buy-from Vendor No.");
        PurchInvHeader.SETRANGE("Pay-to Vendor No.","Pay-to Vendor No.");
        IF PurchInvHeader.FINDFIRST THEN
          IF NOT ConfirmManagement.ConfirmProcess(
               STRSUBSTNO(PostedInvoiceFromSameTransactionQst,PurchInvHeader."No.","No."),TRUE)
          THEN
            ERROR('');
      END;
So I request you to either increase the Order No. field length or change the strange to fix this issue.

**Comment by AlexanderYakunin** [comment]
This is fixed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
