### ISSUE TITLE
[Event Request] Report 5753 Get Source Documents - OnAfterPurchaseLineOnAfterGetRecordOnAfterCreateReceiptHeader

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#6826]
Requesting a new Event Publisher on Report 5753 Get Source Documents

Event
`OnAfterPurchaseLineOnAfterGetRecordOnAfterCreateReceiptHeader(PurchaseLine : Record "Purchase Line"; VAR WarehouseRcptHeader : Record "Warehouse Receipt Header")`

**Code**
## Purchase Line - OnAfterGetRecord()
```
IsHandled := FALSE;
OnBeforePurchaseLineOnAfterGetRecord("Purchase Line","Warehouse Request",RequestType,IsHandled);
IF IsHandled THEN
  CurrReport.SKIP;

VerifyItemNotBlocked("No.");
IF "Location Code" = "Warehouse Request"."Location Code" THEN
  CASE RequestType OF
    RequestType::Receive:
      IF WhseActivityCreate.CheckIfPurchLine2ReceiptLine("Purchase Line") THEN BEGIN
```
**>>> New Code**
```
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN BEGIN
          CreateReceiptHeader;
          OnAfterPurchaseLineOnAfterGetRecordOnAfterCreateReceiptHeader("Purchase Line", WhseReceiptHeader);
        END;
```
**<<< New Code End**
```
        IF NOT WhseActivityCreate.PurchLine2ReceiptLine(WhseReceiptHeader,"Purchase Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
    RequestType::Ship:
      IF WhseActivityCreate.CheckIfFromPurchLine2ShptLine("Purchase Line") THEN BEGIN
        IF NOT OneHeaderCreated AND NOT WhseHeaderCreated THEN
          CreateShptHeader;        
        IF NOT WhseActivityCreate.FromPurchLine2ShptLine(WhseShptHeader,"Purchase Line") THEN
          ErrorOccured := TRUE;
        LineCreated := TRUE;
      END;
  END;
```

In Our Solution we have to populate additional fields on the Warehouse Receipt Header based on Purchase Line but also on Sales Line (Return Order). Therefore we cannot use the existing publishers and need the above described Publisher. Could you please add the requested Publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
