### ISSUE TITLE
Apply Vendor Entries OnAfterCalcApplnAmountToApply() passes wrong AmountToApply

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#6828]
**Describe the bug**
This event should pass the global ApplnAmountToApply, as the Apply Customer Entries page does, but on the Vendor version is passes the local argument AmountToApply instead. Thus it's next to useless.

**To Reproduce**
Steps and to reproduce the behavior:
1. Look at the code. Then compare the Vendor page with the bug to the Customer page without it.

**Expected behavior**
I expect the ApplnAmountToApply to be passed, so that a subscriber can check/update it.

**Screenshots**
the bugged Vendor page:
![image](https://user-images.githubusercontent.com/63455896/78990385-38360d80-7b2e-11ea-98da-0ff41eb73def.png)

the correct Customer page:
![image](https://user-images.githubusercontent.com/63455896/78990417-4b48dd80-7b2e-11ea-9f2c-b2d61bbef64b.png)

**5. Versions:**

 - AL Language: 5.0.254558

 - Business Central: 16.0.11240.12076

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
