### ISSUE TITLE
Page 6550 - Whse. Item Tracking Lines

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6830]
New Publisher:
SourceSpecification.Description := SourceWhseItemTrkgLine.Description;
SourceSpecification."Qty. per Unit of Measure" := SourceWhseItemTrkgLine."Qty. per Unit of Measure";

**// ==> START**
OnBeforeSetGlobalParameters(SourceSpecification,SourceWhseItemTrkgLine);
**// ==> END**

ItemTrackingMgt.SetGlobalParameters

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
