### ISSUE TITLE
[Breaking Change] REP 2000019 - SetPaymJnlLine

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#6831]
When moving our 'BE' app to v16, I get breaking changes :

> The event 'OnBeforeSetPaymJnlLine' is not found in the target

Used Microsoft_Base Application_16.0.11240.12362 **BE** symbols

Seems like #2772 has dissappeared?

-----------

Please provide event publisher OnBeforeSetPaymJnlLine with Handled pattern in function SetPaymJnlLine, report 2000019.

SetPaymJnlLine()
OnBeforeSetPaymJnlLine(VendLedgEntry, Handled); // NVTBE
IF Handled THEN
  EXIT;

WITH PaymJnlLine DO BEGIN
Signature

LOCAL [IntegrationEvent] OnBeforeSetPaymJnlLine(VendorLedgerEntry : Record "Vendor Ledger Entry";VAR Handled : Boolean)

Event will be used to skip adding certain Payment Journal Lines._

**Comment by AlexanderYakunin** [comment]
We have this in Master and 16.x, but it was reimplemented AFTER branching for 16.0, so it will be available in 16.1.

**Comment by AlexanderYakunin** [comment]
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetPaymJnlLine(VendLedgEntry: Record "Vendor Ledger Entry"; var IsHandled: Boolean)
    begin
    end;
