### ISSUE TITLE
[Breaking Change] Report 2000019 Suggest Vendor Payments EB - OnBeforeSuggestPayments

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#6832]
When moving our 'BE' app to v16, I get breaking changes :

The member referenced by event subscriber 'OnBeforeSuggestPayments' parameter '**VendLedgEntry**' is not found.

Used Microsoft_Base Application_16.0.11240.12362 BE symbols

Seems like this is caused by deprecating the GlobalVarAccess requested by #6794 

--------

Can you please add **var access to VendLedgEntry in OnBeforeSuggestPayments** so we can run following code ...

```
VendLedgEntry.SETFILTER("Document Type", '<>%1&<>%2', VendLedgEntry."Document Type"::Invoice, VendLedgEntry."Document Type"::"Credit Memo");
            VendLedgEntry.SETRANGE("On Hold", '');
            VendLedgEntry.SETRANGE("Applies-to ID", '');
            IF VendLedgEntry.FINDSET THEN
                REPEAT
                    sender.SetPaymJnlLine(); // needs access to the Global VendLedgEntry
                UNTIL VendLedgEntry.NEXT = 0;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
