### ISSUE TITLE
[Breaking Change] REP 2000006 - PostPaymentJournal

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#6833]
When moving our 'BE' app to v16, I get breaking changes :

The event 'OnBeforePostPaymentJournal' is not found in the target

Used Microsoft_Base Application_16.0.11240.12362 BE symbols

Seems like #2776 has dissappeared?

Can you please add function PostPaymentJournal and publisher OnBeforePostPaymentJournal again?

**Comment by AlexanderYakunin** [comment]
We have this in Master and 16.x, but it was reimplemented AFTER branching for 16.0, so it will be available in 16.1.
