### ISSUE TITLE
[Breaking Change] REP 2000006 - OnAfterNewConsolidatedPayment

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#6834]
When moving our 'BE' app to v16, I get breaking changes :

The event 'OnAfterNewConsolidatedPayment' is not found in the target

Used Microsoft_Base Application_16.0.11240.12362 BE symbols

Seems like #4174 and / or #2777 have dissappeared?

Can you please add publisher OnAfterNewConsolidatedPayment again?

**Comment by AlexanderYakunin** [comment]
We have this in Master and 16.x, but it was reimplemented AFTER branching for 16.0, so it will be available in 16.1.
