### ISSUE TITLE
[Event Request] Codeunit 9 OnAfterCalcCellValue,OnAfterCalcCellValue add IncludeSender

### ISSUE THREAD

**Issue by hougaard** [microsoft/ALAppExtensions#6835]
Calculations cannot be done externally without access to the codeunit since the column start date is defined by global variables.

So all events that have **var Result : Decimal**  as a parameter should IncludeSender.

[IntegrationEvent(**TRUE**, false)]
local procedure OnBeforeCalcCellValue(var AccSchedLine: Record "Acc. Schedule Line"; var ColumnLayout: Record "Column Layout"; CalcAddCurr: Boolean; var Result: Decimal)
begin
end;

[IntegrationEvent(**TRUE**, false)]
local procedure OnAfterCalcCellValue(var AccSchedLine: Record "Acc. Schedule Line"; var ColumnLayout: Record "Column Layout"; CalcAddCurr: Boolean; var Result: Decimal)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
