### ISSUE TITLE
[Event Request] Codeunit 20 OnAfterShowAllEntries

### ISSUE THREAD

**Issue by Wiechardt** [microsoft/ALAppExtensions#6836]
I have extended the Post Preview functionality by binding to a new/custom Event Handler from the OnAfterBindSubscription Integration Event in codeunit 19.

I cannot unbind my handler using the "OnAfterUnbindSubscription" method as the events in my handler need to support the drilldown feature in the Post Preview page and this page is displayed from the ShowAllEntries method which is fired after the OnAfterUnbindSubscription method.

Please can I ask you to add a new Integration Event OnAfterShowAllEntries() in the ShowAllEntries method to allow me to safely unbind my new Event Handler.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
