### ISSUE TITLE
[Event Request] Codeunit 11000006 CBG Statement Reconciliation - OnAfterMatchCBGStatement

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6838]
Please add a new publisher event to the function MatchCBGStatement as follows:
	
```
MatchCBGStatement(CBGStatement : Record "CBG Statement")
.
.
  UNTIL CBGStatementLine.NEXT = 0;
  StatusWindowClose;
END;

//>> Start New Publisher Call
OnAfterMatchCBGStatement(CBGStatement);
//<< End New Publisher Call
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnAfterMatchCBGStatement(VAR CBGStatement : Record "CBG Statement")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
