### ISSUE TITLE
[Event Request] Codeunit 11000007 Check BTL91 - OnAfterOnRun

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6840]
Please add a new publisher event to the function OnRun as follows:
	
```
OnRun(VAR Rec : Record "Proposal Line")
.
.
  "Error Message" := STRSUBSTNO(Text1000007,FIELDCAPTION("Transfer Cost Domestic"),FIELDCAPTION("Transfer Cost Foreign"));
  EXIT;
END;

//>> Start New Publisher Call
OnAfterOnRun(Rec);
//<< End New Publisher Call
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnAfterOnRun(VAR ProposalLine : Record "Proposal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
