### ISSUE TITLE
[Event Request] Codeunit 11000010 Check SEPA ISO20022 - OnBeforeOnRun

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6841]
Please add a new publisher event to the function OnRun as follows:
	
```
OnRun(VAR Rec : Record "Proposal Line")
//>> Start New Publisher Call
OnBeforeOnRun(Rec);
//<< End New Publisher Call

// Check whether the currency being used is Euro
GLSetup.GET;
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeOnRun(VAR ProposalLine : Record "Proposal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
