### ISSUE TITLE
[Event Request] Codeunit 11000010 Check SEPA ISO20022 - OnAfterOnRun

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6842]
Please add a new publisher event to the function OnRun as follows:
	
```
OnRun(VAR Rec : Record "Proposal Line")
.
.
            FIELDCAPTION("Registration No. DNB"));
        EXIT;
      END;
  END;

//>> Start New Publisher Call
OnAfterOnRun(Rec);
//<< End New Publisher Call
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnAfterOnRun(VAR ProposalLine : Record "Proposal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
