### ISSUE TITLE
[Event Request] Codeunit 11000011 Check SEPA Pain 008.001.02 - OnBeforeCheckSepaRun

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6846]
Please add a new publisher event to the function OnRun as follows:
	
```
OnRun(VAR Rec : Record "Proposal Line")
.
.
  IF NOT CheckProposalPartnerType(Rec) THEN
    EXIT;
END;

//>> Start New Publisher Call
OnBeforeCheckSepaRun(Rec);
//<< End New Publisher Call

CheckSEPA.RUN(Rec);
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeCheckSepaRun(VAR ProposalLine : Record "Proposal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
