### ISSUE TITLE
[Enum Request] "Applies-to Doc. Type" in Tables Item Charge Assignment (Purch) and Item Charge Assignment (Sales)

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6849]
Please make "Applies-to Doc. Type" in Tables "Item Charge Assignment (Purch)" and "Item Charge Assignment (Sales)" an extendable enum.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
