### ISSUE TITLE
Codeunit 5772 "Whse.-Purch. Release" FilterWarehouseRequest Event Request

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#6850]
Hi

Please can you add an event to the end of the FilterWarehouseRequest procedure so that we can add our own filters to the standard ones?  Something similar to the below.  Thanks

local procedure FilterWarehouseRequest(var WarehouseRequest: Record "Warehouse Request"; PurchaseHeader: Record "Purchase Header"; DocumentStatus: Option)
    begin
        with WarehouseRequest do begin
            Reset;
            SetCurrentkey("Source Type", "Source Subtype", "Source No.");
            SetRange(Type, Type);
            SetRange("Source Type", Database::"Purchase Line");
            SetRange("Source Subtype", PurchaseHeader."Document Type");
            SetRange("Source No.", PurchaseHeader."No.");
            SetRange("Document Status", DocumentStatus);

            // Start of new code
           OnAfterFilterWarehouseRequest(var WarehouseRequest: Record "Warehouse Request"; PurchaseHeader: Record "Purchase Header"; DocumentStatus: Option);
            // End of new code
        end;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
