### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post PostCustomerEntry

### ISSUE THREAD

**Issue by SynPaul** [microsoft/ALAppExtensions#6851]
We'd like to prevent the standard PostCustomerEntry procedure from being run and handle it separately using our own logic.  

Could you please add an event at the very beginning of the procedure using the EventHandled pattern?  The name OnBeforePostCustomerEntry has already been used for another event so it needs to be different.

```
OnBeforeRunPostCustomerEntry(SalesHeader, TotalSalesLine2, TotalSalesLineLCY2, SuppressCommit, PreviewMode, DocType, DocNo, ExtDocNo, SourceCode, GenJnlPostLine, EventHandled);
If EventHandled then
  Exit;
```

With the event like this:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeRunPostCustomerEntry (var SalesHeader: Record "Sales Header"; var TotalSalesLine2: Record "Sales Line"; var TotalSalesLineLCY2: Record "Sales Line"; CommitIsSuppressed: Boolean; PreviewMode: Boolean; DocType: Option; DocNo: Code[20]; ExtDocNo: Code[35]; SourceCode: Code[10]; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var EventHandled: Boolean);
begin
end;
```

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
