### ISSUE TITLE
[Event Request] Codeunit 5760 Whse.-Post Receipt - OnAfterSetPutAwayRequired

### ISSUE THREAD

**Issue by Hilbekale** [microsoft/ALAppExtensions#6853]
Hi,

could you please consider the following event? We need to define on some rule, if a put away is created or not. Therefore we want to skip the Creation of Put Away documents directly. We saw that there is this event: "OnBeforeCreatePutAwayDoc", but this is not fitting with what we need.

```
  GetLocation("Location Code");
  PutAwayRequired := Location.RequirePutaway("Location Code");
  // >> New
  OnAfterSetPutAwayRequired(WhseRcptHeader,PutAwayRequired);
  // << New
  IF PutAwayRequired AND NOT Location."Use Put-away Worksheet" THEN
    CreatePutAwayDoc(WhseRcptHeader);
```
- PutAwayRequired should be changeable or GlobalVARAccess can be true:

`LOCAL [IntegrationEvent] OnAfterSetPutAwayRequired(WhseRcptHeader : Record "Warehouse Receipt Header";VAR PutAwayRequired : Boolean)`

Thank you for checking.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
