### ISSUE TITLE
Name 2 Feature Change in Cumulative Update?

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#6854]
Dear BC-Team, 

it seems that you have added the fields "Name 2" of the tables Customer and Vendor to 
- CustomerCard.Page.al
- CustomerList.Page.al
- VendorCard.Page.al
- VendorList.Page.al
sometime in a cumulative update. In the BC15-RTM BaseApp those fields are not there, but in 15.4.41023.41345 suddenly they appear. 

What's up with that? I thought "feature update" are not allowed in CUs and we only get bugfixes? how come this is the exception?

**Comment by StanPesotskiy** [comment]
This issue is not related to the AL extensibility. Please report it via the standard support channel.
