### ISSUE TITLE
[Event Request] Codeunit 32000000 "Ref. Payment Management" - SetLinesOnBeforeGenJnlLineInsert

### ISSUE THREAD

**Issue by diveshbora** [microsoft/ALAppExtensions#6855]
A new Event Publisher is need in the Codeunit 32000000 "Ref. Payment Management".

**Event:**
`local procedure SetLinesOnBeforeGenJnlLineInsert(CustLedgEntry: Record "Cust. Ledger Entry"; var GenJnlLine: Record "Gen. Journal Line")`

**Code**
```
[Scope('OnPrem')]
procedure SetLines(RefPaymentImported: Record "Ref. Payment - Imported"; JnlBatchName: Code[20]; JnlTemplateName: Code[20])
begin
                    if AccCode <> '' then
                        GenJnlLine.Validate("Bal. Account No.", AccCode)
                    else
                        GenJnlLine.Validate("Bal. Account No.", CustLedgEntry."Bal. Account No.");
                    SetLinesOnBeforeGenJnlLineInsert(CustLedgEntry,GenJnlLine);
                    GenJnlLine.Insert(true);
                    LineNro := LineNro + 10000;
                    LastDocNro := IncStr(LastDocNro);
                end;
            until RefPaymentImported.Next = 0;
end;
```
Need to update few fields from CustLedgEntry to GenJnlLine in the SetLines Procedure related to Combine SEPA Payments. The new event should be invoked before GenJnlLine.Insert(true); code. Could you please add the requested Publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
