### ISSUE TITLE
[Event Request] Table 1003 "Job Planning Line" - cancel test of "Qty. Transferred to Invoice"

### ISSUE THREAD

**Issue by Carnesor** [microsoft/ALAppExtensions#6859]
Dear BaseApp team,
Please consider the following modifications.
It is two new events with handled pattern on table 1003 Job Planning Line.
The reason is that some of our customers prefer a different process when creating invoices from jobs more practical. They want an invoice centric user interface, creating the invoice first and then add hours and expenses from one or more jobs to pre-created sales lines accumulated per resource no or account no. The standard system currently prevents this by throwing errors when modifying the Job Planning Line quantities if Sales Lines already exists with transferred amounts. This also indirectly happens when changing the Quantity field on an existing Sales Line with transferred quantities from Job Planning Lines.

So we need to bypass tests in two places.

Code changes requested:

![image](https://user-images.githubusercontent.com/43141133/80183991-1ea2c480-860a-11ea-9731-82b20b1e3d54.png)

![image](https://user-images.githubusercontent.com/43141133/80184338-af79a000-860a-11ea-9625-d6c680f066a4.png)

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
