### ISSUE TITLE
[Event Request] Add Qty Type parameter to SalesLine.Table.al OnBeforeUpdateVATOnLines

### ISSUE THREAD

**Issue by ryansysco** [microsoft/ALAppExtensions#6861]
Can QtyType parameter be added to OnBeforeUpdateVATOnLines. It will need passed into local procedure  IsUpdateVATOnLinesHandled

![image](https://user-images.githubusercontent.com/39119821/80231724-b1178800-864b-11ea-851c-0723142142c1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
