### ISSUE TITLE
[Event Request] Bypass Currency and Unit Cost tests on codeunit 1001 "Job Post-Line"

### ISSUE THREAD

**Issue by Carnesor** [microsoft/ALAppExtensions#6863]
Dear BaseApp team,
Please consider the following changes.
Two new events on codeunit 1001 "Job Post-Line"

**OnBeforeCurrencyCheck**
Need to disable the cross testing of currency code between Sales Header and JobPlanningLine, because our users need to be able to make one invoice with just one currency, but taking quantities from multiple Jobs having multiple currencies.

**OnBeforeValidateRelationship**
Similarly we need to be able to bypass the “Unit Cost (LCY)” check in function ValidateRelationship. Preferably we would like to be able to replace the ValidateRelationship function with a custom version. So one more added event OnBeforeValidateRelationship with handled pattern would be very appreciated.

See both event suggestions below:

![image](https://user-images.githubusercontent.com/43141133/80336330-489cf680-8857-11ea-8dca-9a993dbfcc95.png)

![image](https://user-images.githubusercontent.com/43141133/80336236-feb41080-8856-11ea-9224-cd41f83e59fa.png)

Thanks in advance

**Comment by RomanZanizdra** [comment]
@Carnesor , there is existing event OnBeforeValidateRelationship, it will be updated with IsHandled parameter.

**Comment by Carnesor** [comment]
That is even better, thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
