### ISSUE TITLE
[Event Request] Codeunit 86 Sales-Quote to Order - OnAfterInsertSalesOrderHeader

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#6864]
Can we get an Event `OnAfterCreateSalesHeader` after the creation of the new SalesOrderHeader:
```
    local procedure CreateSalesHeader(SalesHeader: Record "Sales Header"; PrepmtPercent: Decimal)
    begin
        OnBeforeCreateSalesHeader(SalesHeader);

        with SalesHeader do begin
            SalesOrderHeader := SalesHeader;
            
            ......

            OnBeforeModifySalesOrderHeader(SalesOrderHeader, SalesHeader);
            SalesOrderHeader.Modify();
        end;
        OnAfterCreateSalesHeader(SalesOrderHeader, SalesHeader); //NEW
    end;
```

Can we get an similiar event for codeunit 96 "Purch.-Quote to Order"
`OnAfterCreatePurchHeader(PurchOrderHeader, PurchHeader);`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
