### ISSUE TITLE
Table 904 Assemble-to-Order-Link - TransAvailSalesLineToAsmHeader

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6865]
New Publisher in TransAvailSalesLineToAsmHeader:
NewAsmHeader."Quantity (Base)" := SalesLine."Qty. to Asm. to Order (Base)" - AsmHeader."Assembled Quantity (Base)";

**==> START
OnBeforeInitRemainingQty(NewAsmHeader,SalesLine);
<== END**

NewAsmHeader.InitRemainingQty;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
