### ISSUE TITLE
[Event Request] Use handled pattern to allow "Bill-to Contact No." to other contacts

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6866]
In our vertical solution, we allow users to send invoices to invoice recipients outside the customers organisation - while still keeping the customer. We are blocked from this in standard BC because the OnValidate trigger in "Sales Header"."Bill-to Contact No." raises an error - even though table relation is not enforced.

Because of that, we would like to request an event - with "Handled-pattern" in the last part of the OnValidate trigger.

Suggested code:

trigger OnValidate()
var
...
begin
   ...

   //>>L365
   IsHandled := FALSE;
   OnBeforeUpdateBillToCust_L365(Rec, "Bill-to Contact No.", IsHandled);
   if IsHandled THEN
      EXIT;
    //<<L365

    if ("Bill-to Customer No." <> '') and ("Bill-to Contact No." <> '') then begin
        Cont.Get("Bill-to Contact No.");

    if ContBusinessRelation.FindByRelation(ContBusinessRelation."Link to Table"::Customer, "Bill-to 
       Customer No.") then
         if (ContBusinessRelation."Contact No." <> Cont."Company No.") and 
          (ContBusinessRelation."Contact No." <> Cont."No.") then
          Error(Text038, Cont."No.", Cont.Name, "Bill-to Customer No.");
  end;

  UpdateBillToCust("Bill-to Contact No.");
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by fvanderhek** [comment]
I also requested a quite similar publisher. Is it possible to give a more generic name to the publisher like **OnValidateBillToContactNoOnBeforeCheckContactNo**??
