### ISSUE TITLE
Table 904 Assemble-to-Order-Link - TransAvailBOMCompToAsmLine

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6867]
New Publisher in TransAvailBOMCompToAsmLine:

AsmLine."Qty. per Unit of Measure" := ItemUOM."Qty. per Unit of Measure";
**==> Start
OnAfterTransferAvailBOMCompToAsmLine(AsmLine,BOMComponent);
<==END**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
