### ISSUE TITLE
[Event Request] Table 11307 G/L Entry Application Buffer - OnGetAppliedEntriesOnAfterInsertTempGlEntryApplicationBuffer [NL Localisation]

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#6868]
Please add a new publisher event to the function GetAppliedEntries as follows:

GetAppliedEntries(VAR TempGLEntryApplicationBuffer : TEMPORARY Record "G/L Entry Application Buffer";OrgGLEntry : Record "G/L Entry")
IF OrgGLEntry."Closed by Entry No." <> 0 THEN BEGIN
  GLEntry.GET(OrgGLEntry."Closed by Entry No.");
  TempGLEntryApplicationBuffer.TRANSFERFIELDS(GLEntry);
  TempGLEntryApplicationBuffer.INSERT;
        //>> Start New Publisher Call
OnGetAppliedEntriesOnAfterInsertTempGlEntryApplicationBuffer(TempGLEntryApplicationBuffer, GLEntry, OrgGLEntry); 
//>> End New Publisher Call
END ELSE BEGIN
  GLEntry.SETCURRENTKEY("Closed by Entry No.");
  GLEntry.SETRANGE("Closed by Entry No.",OrgGLEntry."Entry No.");
  IF GLEntry.FINDSET THEN 
    REPEAT
      IF GLEntry."Entry No." <> OrgGLEntry."Entry No." THEN BEGIN
        TempGLEntryApplicationBuffer.TRANSFERFIELDS(GLEntry);
        TempGLEntryApplicationBuffer.INSERT;
        //>> Start New Publisher Call
OnGetAppliedEntriesOnAfterInsertTempGlEntryApplicationBuffer(TempGLEntryApplicationBuffer, GLEntry, OrgGLEntry); 
//>> End New Publisher Call

      END;
    UNTIL GLEntry.NEXT = 0;
END;

>> Publisher Definition
LOCAL [IntegrationEvent] OnGetAppliedEntriesOnAfterInsertTempGlEntryApplicationBuffer(VAR TempGLEntryApplicationBuffer : TEMPORARY Record "G/L Entry Application Buffer";GLEntry : Record "G/L Entry";OrgGLEntry : Record "G/L Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
