### ISSUE TITLE
[Event Request] Table 5771 "Whse Source Filter", New Event: OnBeforeCheckIfCanBeDeleted

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6870]
[Event Request] Table 5771 "Whse Source Filter", New Event: OnBeforeCheckIfCanBeDeleted

It needs to be possible to react more flexibly to the procedure CheckIfCanBeDeleted. Thus a Handled Pattern needs to be introduced.

    procedure CheckIfCanBeDeleted(): Text
    var
        ServiceLedgerEntry: Record "Service Ledger Entry";
        ReturnText: Text;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckIfCanBeDeleted(Rec, ReturnText, IsHandled);
        if IsHandled then
            exit(ReturnText);

        if ServItemLinesExist then

![image](https://user-images.githubusercontent.com/22153733/80473499-8462b980-8946-11ea-8bce-109a4d0906d5.png)

**Integration Event**

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIfCanBeDeleted(var ServiceItem: Record "Service Item"; var ReturnText: text; var IsHandled: Boolean)
    begin
    end;

**Name**:
OnBeforeCheckICanBeDeleted
**Signature:**
var ServiceItem: Record "Service Item"
var ReturnText: text
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
