### ISSUE TITLE
[Event Request] Table 11307 - G/L Entry Application Buffer - OnApplyOnBeforeUpdateTables

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#6871]
Please add a new publisher event to the function Apply as follows:

Apply(VAR GLEntryApplicationBuffer : Record "G/L Entry Application Buffer")
GLEntryApplicationBuffer.TESTFIELD("Applies-to ID");
BaseEntryNo := GLEntryApplicationBuffer."Entry No.";

RealEntryChanged(GLEntryApplicationBuffer,GLEntry);

GLEntryApplicationBuffer.SETRANGE("Applies-to ID",GLEntryApplicationBuffer."Applies-to ID");
GLEntryApplicationBuffer.SETFILTER("Entry No.",'<> %1',GLEntryApplicationBuffer."Entry No.");
IF GLEntryApplicationBuffer.FINDSET THEN BEGIN
  REPEAT
    GLEntryApplicationBuffer.TESTFIELD("G/L Account No.",GLEntryApplicationBuffer."G/L Account No.");
    GLEntryApplicationBuffer.TESTFIELD(Open,TRUE);
    AppliedAmount := -GLEntryApplicationBuffer."Remaining Amount";
    TotalAppliedAmount := TotalAppliedAmount + AppliedAmount;
    RealEntryChanged(GLEntryApplicationBuffer,GLEntry);
**//>> Start New Publisher Call
    OnApplyOnBeforeUpdateTables(Rec, GLEntryApplicationBuffer, GLEntry, AppliedAmount, TotalAppliedAmount, BaseEntryNo);
//<< End New Publisher Call**
    UpdateTempTable(GLEntryApplicationBuffer,0,FALSE,BaseEntryNo,"Posting Date",-AppliedAmount,'');
    UpdateRealTable(GLEntry,0,FALSE,BaseEntryNo,"Posting Date",-AppliedAmount,'');
  UNTIL GLEntryApplicationBuffer.NEXT = 0;
END ELSE
  EXIT;

// Update entry where cursor is on
// Update real Table
GLEntry.GET(BaseEntryNo);
UpdateRealTable(
    GLEntry,"Remaining Amount" - TotalAppliedAmount,
    ("Remaining Amount" - TotalAppliedAmount) <> 0,0,0D,0,'');

New Publisher Event:
**LOCAL [IntegrationEvent] OnApplyOnBeforeUpdateTables(VAR Rec : Record "G/L Entry Application Buffer";VAR GLEntryApplicationBuffer : Record "G/L Entry Application Buffer";GLEntry : Record "G/L Entry";AppliedAmount : Decimal;TotalAppliedAmount : Decimal**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
