### ISSUE TITLE
[Integration Event Enhancement] Codeunit 5981 "Service-Post (Yes/No)", OnAfterConfirmPost

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6872]
[Integration Event Enhancement] Codeunit 5981 "Service-Post (Yes/No)", Event OnAfterConfirmPost

Could you pass the parameter ServiceHeader by reference instead of just by value:

    [IntegrationEvent(false, false)]
    local procedure OnAfterConfirmPost(var ServiceHeader: Record "Service Header"; Ship: Boolean; Consume: Boolean; Invoice: Boolean)
    begin
    end;

![image](https://user-images.githubusercontent.com/22153733/80476239-6434f980-894a-11ea-9361-8be35df06816.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
