### ISSUE TITLE
Event Request Codeunit 5812 Calculate Standard Cost - OnAfterSetProperties

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6873]
Thanks for shipping the Puiblisher i have requested here:
#5602 https://github.com/microsoft/ALAppExtensions/issues/5602
but I miss the var expression of all the passing variables
==> Old
OnAfterSetProperties(NewCalculationDate : Date;NewCalcMultiLevel : Boolean;NewUseAssemblyList : Boolean;NewLogErrors : Boolean;NewStdCostWkshName : Text[50];NewShowDialog : Boolean)
<== Old
**==> New
OnAfterSetProperties(var NewCalculationDate : Date; var NewCalcMultiLevel : Boolean; var NewUseAssemblyList : Boolean; var NewLogErrors : Boolean; var NewStdCostWkshName : Text[50]; var NewShowDialog : Boolean)
<== New**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
