### ISSUE TITLE
Codeunit 12 Gen. Jnl. - Post Line - OnPostUnapplyOnAfterVATEntryInsert

### ISSUE THREAD

**Issue by beatriz-fores** [microsoft/ALAppExtensions#6874]
Please add a new publisher event to the function PostUnnaply as follows:

LOCAL PostUnapply(GenJnlLine : Record "Gen. Journal Line";VAR VATEntry : Record "VAT Entry";VATEntryType : Option;BilltoPaytoNo : Code[20];TransactionNo : Integer;UnapplyVATEntries : Boolean;VAR TempVATEntry : TEMPORARY Record "VAT Entry")
TempVATEntryNo := 1;
VATEntry.SETCURRENTKEY(Type,"Bill-to/Pay-to No.","Transaction No.");
VATEntry.SETRANGE(Type,VATEntryType);
VATEntry.SETRANGE("Bill-to/Pay-to No.",BilltoPaytoNo);
VATEntry.SETRANGE("Transaction No.",TransactionNo);
IF VATEntry.FINDSET THEN
  REPEAT
    VATPostingSetup.GET(VATEntry."VAT Bus. Posting Group",VATEntry."VAT Prod. Posting Group");
    IF UnapplyVATEntries OR (VATEntry."Unrealized VAT Entry No." <> 0) THEN BEGIN
      InsertTempVATEntry(GenJnlLine,VATEntry,TempVATEntryNo,TempVATEntry);
      IF VATEntry."Unrealized VAT Entry No." <> 0 THEN BEGIN
        VATPostingSetup.GET(VATEntry."VAT Bus. Posting Group",VATEntry."VAT Prod. Posting Group");
        IF VATPostingSetup."VAT Calculation Type" IN
           [VATPostingSetup."VAT Calculation Type"::"Normal VAT",
            VATPostingSetup."VAT Calculation Type"::"Full VAT"]
        THEN
          PostUnrealVATByUnapply(GenJnlLine,VATPostingSetup,VATEntry,TempVATEntry)
        ELSE
          IF VATPostingSetup."VAT Calculation Type" = VATPostingSetup."VAT Calculation Type"::"Reverse Charge VAT" THEN BEGIN
            PostUnrealVATByUnapply(GenJnlLine,VATPostingSetup,VATEntry,TempVATEntry);
            CreateGLEntry(
              GenJnlLine,VATPostingSetup.GetRevChargeAccount(TRUE),
              -VATEntry.Amount,CalcAddCurrForUnapplication(VATEntry."Posting Date",-VATEntry.Amount),FALSE);
            CreateGLEntry(
              GenJnlLine,VATPostingSetup.GetRevChargeAccount(FALSE),
              VATEntry.Amount,CalcAddCurrForUnapplication(VATEntry."Posting Date",VATEntry.Amount),FALSE);
          END ELSE
            PostUnrealVATByUnapply(GenJnlLine,VATPostingSetup,VATEntry,TempVATEntry);
        VATEntry2 := TempVATEntry;
        VATEntry2."Entry No." := NextVATEntryNo;
        OnPostUnapplyOnBeforeVATEntryInsert(VATEntry2,GenJnlLine,VATEntry);
        VATEntry2.INSERT;
	//>> Start New Publisher Call
	//OnPostUnapplyOnAfterVATEntryInsert(VATEntry2,GenJnlLine,VATEntry);
	//>> End New Publisher Call
        IF VATEntry2."Unrealized VAT Entry No." = 0 THEN
          GLEntryVATEntryLink.InsertLink(NextEntryNo,VATEntry2."Entry No.");
        TempVATEntry.DELETE;
        IncrNextVATEntryNo;
      END;

      .
      .
      .
New Publisher Event:
LOCAL [IntegrationEvent] OnPostUnapplyOnAfterVATEntryInsert(VAR VATEntry : Record "VAT Entry";GenJournalLine : Record "Gen. Journal Line";OrigVATEntry : Record "VAT Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
