### ISSUE TITLE
[Event Request] COD13 - OnBeforeCheckAccountType/OnBeforeCheckBalAccountType

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#6875]
Hello, 

we Need 2 Events in COD13. One Event in procedure CheckAccountNo and one Event in procedure CheckBalAccountNo.

![image](https://user-images.githubusercontent.com/45033081/80495442-35c61700-8968-11ea-8c00-b819e28e4509.png)

![image](https://user-images.githubusercontent.com/45033081/80495462-3eb6e880-8968-11ea-8002-44fbb179b1f5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
