### ISSUE TITLE
[Event Request] COD230 - OnBeforeGenJnlTemplateInsert

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#6876]
Hello,

we Need a new Event in Codeunit 230. Background is, that we have a additional Gen. Journal Page and want to handle it here. 

![image](https://user-images.githubusercontent.com/45033081/80495583-67d77900-8968-11ea-93e6-9ea0966ade20.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
