### ISSUE TITLE
[Event Request] TAB81 OnAfterUpdateSourceNo

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#6877]
Hello,

we Need a new Event in Table 81 after the souce no. and source type is set.

![image](https://user-images.githubusercontent.com/45033081/80495786-a9682400-8968-11ea-8821-4242000df3c6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
