### ISSUE TITLE
[Event Request] COD13 - OnBeforeINCJournalBatch

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#6878]
Hello,

we Need an Event in Codeunit 13 on procedure UpdateAndDeleteLines to skip the incrementation of a Journal Batch. Both Parameters should be VAR-Parameters (thats not totally correct in the Picture)

![image](https://user-images.githubusercontent.com/45033081/80497346-99e9da80-896a-11ea-82b5-43ccb84226bf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
