### ISSUE TITLE
[Event Request] Table 5050 Contact - OnBeforeCheckDupl

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#6888]
Please add a new publisher event to the function `CheckDupl` as follows:
                
```
.
.
LOCAL CheckDupl()
 
//>> Start New Publisher Call
OnBeforeCheckDupl(Rec, IsHandled);

IF IsHandled THEN
  EXIT;
//<< End New Publisher Call
 
IF RMSetup."Maintain Dupl. Search Strings" THEN
  DuplMgt.MakeContIndex(Rec);
IF GUIALLOWED THEN
.
.
```
 
New Publisher Event:
 
```
LOCAL [IntegrationEvent] OnBeforeCheckDupl(VAR Contact : Record Contact;VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
