### ISSUE TITLE
[Event Request] Table 5050 Contact - OnAfterProcessNameChange

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#6894]
Please add a new publisher event to the function `ProcessNameChange` as follows:
                
```
.
.
      IF Vend."Primary Contact No." = "No." THEN BEGIN
        Vend.Contact := Name;
        Vend.MODIFY;
      END;
END;

//>> Start New Publisher Call
OnAfterProcessNameChange(Rec, Cust, Vend);
//<< End New Publisher Call
.
.
```
 
New Publisher Event:
 
```
LOCAL [IntegrationEvent] OnAfterProcessNameChange(VAR Contact : Record Contact;Customer : Record Customer;Vendor : Record Vendor)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
