### ISSUE TITLE
[Event Request] Codeunit 6620 OnBeforeClearBlanketSalesOrderFields and OnBeforeClearBlanketPurchOrderFields

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6897]
We Need two new Event trigger OnBeforeClearBlanketSalesOrderFields and OnBeforeClearBlanketPurchOrderFields with IsHandled-function in codeunit 6620:

LOCAL SetDefaultValuesToSalesLine(VAR ToSalesLine : Record "Sales Line";ToSalesHeader : Record "Sales Header";VATDifference : Decimal)
InitSalesLineFields(ToSalesLine);

//+++++++++++++++++++++++++++++++++++++
IsHandled := FALSE;
OnBeforeClearBlanketSalesOrderFields(VAR ToSalesLine : Record "Sales Line";ToSalesHeader : Record "Sales Header";VAR IsHandled);
IF NOT IsHandled THEN
//-------------------------------------
IF ToSalesLine."Document Type" IN
   [ToSalesLine."Document Type"::"Blanket Order",
    ToSalesLine."Document Type"::"Credit Memo",
    ToSalesLine."Document Type"::"Return Order"]
THEN BEGIN
  ToSalesLine."Blanket Order No." := '';
  ToSalesLine."Blanket Order Line No." := 0;
END;

LOCAL SetDefaultValuesToPurchLine(VAR ToPurchLine : Record "Purchase Line";ToPurchHeader : Record "Purchase Header";VATDifference : Decimal)
InitPurchLineFields(ToPurchLine);

//+++++++++++++++++++++++++++++++++++++
IsHandled := FALSE;
OnBeforeClearBlanketPurchOrderFields(VAR ToPurchLine : Record "Purchase Line";ToPurchHeader : Record "Purchase Header";VAR IsHandled);
IF NOT IsHandled THEN
//-------------------------------------
IF ToPurchLine."Document Type" IN
   [ToPurchLine."Document Type"::"Blanket Order",
    ToPurchLine."Document Type"::"Credit Memo",
    ToPurchLine."Document Type"::"Return Order"]
THEN BEGIN
  ToPurchLine."Blanket Order No." := '';
  ToPurchLine."Blanket Order Line No." := 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
