### ISSUE TITLE
[Event Request] Add "RUMat" as argument to CodeUnit::"Calculate Standard Cost"::CalcMfgItem()::OnCalcMfgItemOnBeforeCalculateCosts()

### ISSUE THREAD

**Issue by fab-kuma** [microsoft/ALAppExtensions#6898]
Hi,

`local procedure CodeUnit::"Calculate Standard Cost"::CalcMfgItem(ItemNo: Code[20]; var Item: Record Item; Level: Integer)`

triggers following integration-event
```
OnCalcMfgItemOnBeforeCalculateCosts(
              SLMat, SLCap, SLSub, SLCapOvhd, SLMfgOvhd, Item, LotSize, MfgItemQtyBase, Level, CalculationDate);
```
Please also pass `RUMat` as an argument to the integration-event. I don't see a feasible way to compute `"Rolled-up Material Cost"` based on a modified/custom value for `RUMat` otherwise.

best
fabian

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
