### ISSUE TITLE
[Event Request] Custom computation of MfgItemQtyBase in CalcCompItemQtyBase()

### ISSUE THREAD

**Issue by fab-kuma** [microsoft/ALAppExtensions#6899]
Hi,

we are currently lacking means to customize computation of a component's item base-quantity in:
`Codeunit::"Cost Calculation Management"::CalcCompItemQtyBase(ProdBOMComponent: Record "Production BOM Line"; CalculationDate: Date; MfgItemQtyBase: Decimal; RtngNo: Code[20]; AdjdForRtngScrap: Boolean): Decimal`

I need to interfere computation of `MfgItemQtyBase` by means of:

**Pseude-code:**
IF `ProdBOMComponent.Quantity` = 0 THEN 
FINDFIRST related ITEM based on `ProdBOMComponent."Production BOM No."` WHERE some item condition applies THEN compute and assign custom value to `ProdBOMComponent.Quantity` and finally utilize this modified `Quantity` to compute `MfgItemQtyBase := CalcQtyAdjdForBOMScrap(MfgItemQtyBase * Quantity * GetQtyPerUnitOfMeasure,"Scrap %")` 

best
fabian

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
