### ISSUE TITLE
[Function Expose] Report 292 Copy Sales Document - SetSalesHeader(), InitializeRequest()

### ISSUE THREAD

**Issue by fehebo** [Microsoft/ALAppExtensions#69]
Hi,
We need to use the Report 292 Copy Sales Document in our business logic . 
Could you enable the following functions in extension development  in the Report 292 - Copy Sales Document :
- SetSalesHeader();
- InitializeRequest()

**Comment by maksym-ch** [comment]
@fehebo ,
The requested functions are already External (Build 25530)
