### ISSUE TITLE
[Event Request] PAG 232 - additional parameters to OnBeforeCalcApplnAmount

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#6900]
Dear BaseApp team,

In our vertical solutions we impose a few limits on application of cust.ledger entries. Because of that, we need to set a filter on AppliedCustLedgEntry in the procedure CalcApplnAmount on page 232.

Easiest way is to expand the existing OnBeforeCalcApplnAmount event with some extra parameters.

Requested code:

procedure CalcApplnAmount()
    begin
        OnBeforeCalcApplnAmount(Rec, GenJnlLine, SalesHeader, AppliedCustLedgEntry, CalcType, ApplnType); //L365

...

New event signature:
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcApplnAmount(var CustLedgerEntry: Record "Cust. Ledger Entry"; var GenJournalLine: Record "Gen. Journal Line"; SalesHdr: Record "Sales Header"; ; VAR AppliedCLE: Record "Cust. Ledger Entry"; CalculationType: Option; ApplicationType: Option)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
