### ISSUE TITLE
Rep 730 Copy Item - Event OnAfterCopyItem is not triggered anymore

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/ALAppExtensions#6901]
* In BC15, we have the Report 730 "Copy Item" that raises the event OnAfterCopyItem.
* In BC16.1, Report 730 "Copy Item" is marked as ObsoleteState = Pending because it is replaced by Page 729 "Copy Item" (+ Codeunit 730 "Copy Item" and the event OnAfterCopyItem).

The report Copy Item is no more available in the UI by default, already replaced by the page Copy Item.
The consequence is that the event Report::"Copy Item"::OnAfterCopyItem is never called because there no relay to this event in Codeunit::"Copy Item"::OnAfterCopyItem for backwards compatibility.

Base Application version : 16.1.12580.0

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
