### ISSUE TITLE
[Event Request] Codeunit 5780 Whse. Cross-Dock Management - InsertCrossDockLine

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#6904]
New Publisher needed in InsertCrossDockLine

"Picked Qty." := Maximum("Picked Qty." + QtyPicked, 0);
==> NEW
OnBeforeInsertCrossDockLine(CrossDockOpp);
<==NEW
Insert;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
