### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt." IsEntityBlocked function

### ISSUE THREAD

**Issue by kmistryebecs** [microsoft/ALAppExtensions#6905]
Please can we have the following event added at the start of the IsEntityBlocked function...

`OnIsEntityBlocked(TableNo: Integer; CreditDocType: Boolean; Type: Option; EntityNo: Code[20]; var Handled: Boolean)
`

...and then exit if the event subscription sets Handled to true.

The reason is that I would like to allow a "G/L Account" type Sales Line to be copied in the following scenario...

```
"Direct Posting" = No (on G/L Account)
"System-Created Entry" = Yes (on Sales Line)
```

i.e. normally the copy document won't copy G/L lines that do not have "Direct Posting" ticked but I want to allow that when the line is a "System-Created Entry" line

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
