### ISSUE TITLE
[Event Request] Report 7000099 Post Bill Group - OnBeforeWriteOnBGPOPostBuffer

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#6906]
We need a new event function in Report 7000099 "Post Bill Group", named OnBeforeWriteOnBGPOPostBuffer:

**LOCAL [IntegrationEvent] OnBeforeWriteOnBGPOPostBuffer(BillGr : Record "Bill Group";CarteraDoc : Record "Cartera Doc.";CustLedgerEntry : Record "Cust. Ledger Entry";VAR BGPOPostBuffer : TEMPORARY Record "BG/PO Post. Buffer";VAR AccountNo : Code[20];VAR BalanceAccount : Code[20];VAR IsHandled : Boolean)**

called from:

**Doc - OnAfterGetRecord()**
....
....
....
CustPostingGr.TESTFIELD("Bills Account");
BalanceAccount := CustPostingGr."Bills Account";
OnAfterGetBillsAccounts(Doc,CustLedgEntry,AccountNo,BalanceAccount);
**//INIT-INSERT
OnBeforeWriteOnBGPOPostBuffer(BillGr,Doc,CustLedgEntry,BGPOPostBuffer,AccountNo,BalanceAccount,IsHandled);
IF NOT IsHandled THEN
//END-INSERT**
IF BGPOPostBuffer.GET(AccountNo,BalanceAccount,CustLedgEntry."Entry No.") THEN BEGIN
  BGPOPostBuffer.Amount := BGPOPostBuffer.Amount + "Remaining Amount";
  IF "Currency Code" <> '' THEN
....
....
....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
