### ISSUE TITLE
[Event Request] Report 7000098 Settle Docs. in Post. Bill Gr. - OnBeforeLoopBankAccPostBuffer

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#6907]
We need a new event function in Report 7000099 "Settle Docs. in Post. Bill Gr.", named OnBeforeLoopBankAccPostBuffer:

**LOCAL [IntegrationEvent] OnBeforeLoopBankAccPostBuffer(VAR BankAccPostBuffer : TEMPORARY Record "BG/PO Post. Buffer";PostedDoc : Record "Posted Cartera Doc.";PostedBillGr : Record "Posted Bill Group";VAR GenJnlLine : Record "Gen. Journal Line";VAR GenJnlLineNextNo : Integer;VAR SumLCYAmt: Decimal;PostingDate : Date;SourceCode : Code[10]:VAR IsHandled : Boolean)**

called from:

**PostedDoc - OnPostDataItem()**
....
....
....
  ERROR(
    Text1100003 +
    Text1100005);
END;
**//INIT-INSERT
OnBeforeLoopBankAccPostBuffer(BankAccPostBuffer,PostedDoc,PostedBillGr,GenJnlLine,GenJnlLineNextNo,SumLCYAmt,PostingDate,SourceCode,IsHandled);
IF NOT IsHandled THEN
//END-INSERT**
  IF BankAccPostBuffer.FIND('-') THEN
    REPEAT
      CustLedgEntry2.GET(BankAccPostBuffer."Entry No.");
....
....
....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
