### ISSUE TITLE
[Event Request] Table 5741 TransferLine - OnBeforeDeleteOnAfterTestStatusEvent

### ISSUE THREAD

**Issue by smartinez-io** [microsoft/ALAppExtensions#6908]
Hi,
 
Could you please consider the following event? **We need to do some actions on custom tables before deleting a Transfer Line (table 5741) but after test actions on the OnDelete trigger.** We tried to copy the test status and testfields code but we saw that TestStatusOpen function is LOCAL (so we can't use it from the subscriber). We think the event that we're requesting shoud be like this:

```
TestStatusOpen;

TestField("Quantity Shipped", "Quantity Received");
TestField("Qty. Shipped (Base)", "Qty. Received (Base)");
CalcFields("Reserved Qty. Inbnd. (Base)", "Reserved Qty. Outbnd. (Base)");
TestField("Reserved Qty. Inbnd. (Base)", 0);
TestField("Reserved Qty. Outbnd. (Base)", 0);
// >> New
OnBeforeDeleteOnAfterTestStatusEvent(Rec);
// << New

ReserveTransferLine.DeleteLine(Rec);
WhseValidateSourceLine.TransLineDelete(Rec);
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteOnAfterTestStatusEvent(var Rec: Record "Transfer Line")
begin
end;
```

We also think that **making TestStatusOpen access global can solve our issue**.
 
Thank you for your attention.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
