### ISSUE TITLE
[Event Request] Codeunit 5700 User Setup Manageemnt - Additional parameter to OnBeforeIsPostingDateValidWithSetup

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6909]
Hello BaseApp team,

Codeunit 5700 contains an Event Publisher OnBeforeIsPostingDateValidWithSetup - thanks for this - but it is missing one important parameter namely "SetupRecordID"
Could you please add this parameter?

New Code lines:
	
```
[External] IsPostingDateValidWithSetup(PostingDate : Date;VAR SetupRecordID : RecordID) Result : Boolean
// OnBeforeIsPostingDateValidWithSetup(PostingDate,Result,IsHandled);               // Old Call
OnBeforeIsPostingDateValidWithSetup(PostingDate,SetupRecordID,Result,IsHandled);    // New Call

IF IsHandled THEN
  EXIT(Result);
.
.
```

Changed Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeIsPostingDateValidWithSetup(PostingDate : Date;VAR SetupRecordID : RecordID;VAR Result : Boolean;VAR IsHandled : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
