### ISSUE TITLE
[Event Request] Table 179 Reversal Entry - OnBeforeCheckEmpl

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6910]
Please add a new publisher event to the function CheckEmpl as follows:
	
```
LOCAL CheckEmpl(EmployeeLedgerEntry : Record "Employee Ledger Entry")
//>> Start New Publisher Call
OnBeforeCheckEmpl(EmployeeLedgerEntry);
//<< End New Publisher Call

Employee.GET(EmployeeLedgerEntry."Employee No.");
.
.
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeCheckEmpl(VAR EmployeeLedgerEntry : Record "Employee Ledger Entry")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
