### ISSUE TITLE
[event request] Codeunit 427 - ICInboxOutboxMgt - CreatePurchDocument

### ISSUE THREAD

**Issue by lucaeos** [microsoft/ALAppExtensions#6915]
Please add a new publisher event to function CreatePurchDocument

`[External] CreatePurchDocument(ICInboxPurchHeader : Record "IC Inbox Purchase Header";ReplacePostingDate : Boolean;PostingDate : Date)
//>> Start New Publisher Call
IsHandled := FALSE;
OnBeforeCreatePurchDocument(ICInboxPurchHeader,ReplacePostingDate,PostingDate,IsHandled);
IF IsHandled THEN
  EXIT;
//<< End New Publisher Call

WITH ICInboxPurchHeader DO BEGIN
  PurchHeader.INIT;
  PurchHeader."No." := '';
  PurchHeader."Document Type" := "Document Type";
  OnCreatePurchDocumentOnBeforePurchHeaderInsert(PurchHeader,ICInboxPurchHeader);
  PurchHeader.INSERT(TRUE);`

New Publisher Event:
`LOCAL [IntegrationEvent] OnBeforeCreatePurchDocument(ICInboxPurchHeader : Record "IC Inbox Purchase Header";ReplacePostingDate : Boolean;PostingDate : Date;VAR IsHandled : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
