### ISSUE TITLE
[Event Update Request]  ResevationManagement.OnBeforeAutoReserve<Table> : set var to Search and NextStep parameters

### ISSUE THREAD

**Issue by xgaronnat** [microsoft/ALAppExtensions#6916]
Hi,
Could you please set Search and NextStep parameters as **var** to let us change the reservation behaviour :

`local procedure OnBeforeAutoReserveTransLine(<...>; var Search: Text[1]; var NextStep: Integer)
`
Thanks a lot.
Original request : https://github.com/microsoft/ALAppExtensions/issues/497#issue-386269889

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
