### ISSUE TITLE
[Event Request] Codeunit 5882 - OnBeforeOnRun

### ISSUE THREAD

**Issue by khecova** [microsoft/ALAppExtensions#6920]
Please add new integration event **OnBeforeOnRun** to **Codeunit 5882**.

Suggested calls:

```
trigger OnRun()
begin
+   OnBeforeOnRun(Rec);

    PhysInvtOrderHeader.Copy(Rec);
    Code;
    Rec := PhysInvtOrderHeader;
end;
```

New Event Publisher:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnRun(var PhysInvtOrderHeader: Record "Phys. Invt. Order Header")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
