### ISSUE TITLE
[Event Request] Table 121 "Purch. Rcpt. Line", OnBeforeCheckPurchLineReceiptNoEqualsDocumentNo

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6921]
[Event Request] Table 121 "Purch. Rcpt. Line", OnBeforeCheckPurchLineReceiptNoEqualsDocumentNo

Code in the procedure InsertInvLineFromRcptLine checks whether the PurchLine."Receipt No." equals the "Document No." and processes code base on the result. We need to check the PurchLine."Shipment No." and the PurchLine."FO Source Document No." as well.

    procedure InsertInvLineFromRcptLine(var PurchLine: Record "Purchase Line")
    var
        PurchInvHeader: Record "Purchase Header";
        PurchOrderHeader: Record "Purchase Header";
        PurchOrderLine: Record "Purchase Line";
        TempPurchLine: Record "Purchase Line" temporary;
        TransferOldExtLines: Codeunit "Transfer Old Ext. Text Lines";
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        TranslationHelper: Codeunit "Translation Helper";
        NextLineNo: Integer;
        ExtTextLine: Boolean;
        IsHandled: Boolean;
        DirectUnitCost: Decimal;
    begin
        SetRange("Document No.", "Document No.");

        TempPurchLine := PurchLine;
        if PurchLine.Find('+') then
            NextLineNo := PurchLine."Line No." + 10000
        else
            NextLineNo := 10000;

        if PurchInvHeader."No." <> TempPurchLine."Document No." then
            PurchInvHeader.Get(TempPurchLine."Document Type", TempPurchLine."Document No.");

        OnBeforeCheckPurchLineReceiptNoEqualsDocumentNo(Rec, PurchLine, TempPurchLine, NextLineNo);

        if PurchLine."Receipt No." <> "Document No." then begin
            PurchLine.Init();

![image](https://user-images.githubusercontent.com/22153733/80987422-50016880-8e32-11ea-9b32-84ccaa82c8d6.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPurchLineReceiptNoEqualsDocumentNo(var PurchRcptLine: Record "Purch. Rcpt. Line"; var PurchLine: Record "Purchase Line"; var TempPurchLine: Record "Purchase Line"; var NextLineNo: Integer)
    begin
    end;

**Integration Event:**
OnBeforeCheckPurchLineReceiptNoEqualsDocumentNo
**Signature:**
var PurchRcptLine: Record "Purch. Rcpt. Line"
var PurchLine: Record "Purchase Line"
var TempPurchLine: Record "Purchase Line"
var NextLineNo: Integer

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
