### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnAfterInitGLRegister

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#6924]
We need a new call to event OnAfterInitGLRegister in CodeUnit 12 "Gen. Jnl.-Post Line", function ContinuePosting (the event already exists and implemented in StartPosting function) :

**[External] ContinuePosting(GenJnlLine : Record "Gen. Journal Line")**
OnBeforeContinuePosting(GenJnlLine,GLReg,NextEntryNo,NextTransactionNo);

IF NextTransactionNoNeeded(GenJnlLine) THEN BEGIN
  CheckPostUnrealizedVAT(GenJnlLine,FALSE);
  NextTransactionNo := NextTransactionNo + 1;
  InitLastDocDate(GenJnlLine);
  FirstNewVATEntryNo := NextVATEntryNo;

  LastTempTransNo := GenJnlLine."Transaction No.";
  IF IsGLRegInserted THEN
    GLReg.MODIFY
  ELSE
    GLReg.INSERT;

  GLReg.INIT;
  GLReg."No." += 1;
  GLReg."From Entry No." := NextEntryNo;
  GLReg."From VAT Entry No." := NextVATEntryNo;
  GLReg."Creation Date" := TODAY;
  GLReg."Source Code" := GenJnlLine."Source Code";
  GLReg."Journal Batch Name" := GenJnlLine."Journal Batch Name";
  GLReg."User ID" := USERID;
  GLReg."Posting Date" := GenJnlLine."Posting Date";
  IsGLRegInserted := FALSE;

  **_//INIT INSERT
  OnAfterInitGLRegister(GLReg,GenJnlLine);
  //END INSERT_**

END;

OnContinuePostingOnBeforeCalculateCurrentBalance(GenJnlLine,NextTransactionNo);

GetCurrencyExchRate(GenJnlLine);
TempGLEntryBuf.DELETEALL;
CalculateCurrentBalance(
  GenJnlLine."Account No.",GenJnlLine."Bal. Account No.",GenJnlLine.IncludeVATAmount,
  GenJnlLine."Amount (LCY)",GenJnlLine."VAT Amount");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
