### ISSUE TITLE
[Enum Request] Field Status in RoutingHeader, RoutingVersion, ProdBomHeader, ProdBomVersion

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6925]
Please make the field "Status" in tables RoutingHeader, RoutingVersion, ProdBomHeader, ProdBomVersion an enum, we would like to use the same enum for our apps.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
