### ISSUE TITLE
Codeunit 10753; “SII Job Upload Pending Docs.” 

### ISSUE THREAD

**Issue by prasadCherukumalli** [microsoft/ALAppExtensions#6926]
Hi,
I am working on Microsoft Spanish localization objects, SII integration area.
In this codeunit SII Job Upload Pending Docs. they are 2 Microsoft standard event subscription
1.OnCustomerLedgerEntryCreated 
2.OnDetailedCustomerLedgerEntryCreated 
they will create SIIRequests, I want to skip this creation based on some conditional checking.
I need events here, please refer my attachments.
![COD-10753-OnBeforeCreateNewCustPmtRequest](https://user-images.githubusercontent.com/64625818/81162009-190c8d80-8fbf-11ea-88df-dc7126740975.png)
![COD-10753-OnBeforeCreateNewRequest](https://user-images.githubusercontent.com/64625818/81162014-1ad65100-8fbf-11ea-9b4d-85559f7a3b1a.png)

Thank you,

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by prasadCherukumalli** [comment]
`OnBeforeCreateNewCustPmtRequest(DetailedCustLedgEntry; var IsHandled: Boolean)
If IsHandled then
  Exit;

OnBeforeCreateNewRequest(CustLedgEntry; var IsHandled: Boolean)
If IsHandled then
  Exit;
<img width="675" alt="AL-SIIJobUploadDocs-1" src="https://user-images.githubusercontent.com/64625818/82041870-76998c00-96db-11ea-9f36-0ec2ed7b5c72.png">
<img width="597" alt="AL-SIIJobUploadDocs-2" src="https://user-images.githubusercontent.com/64625818/82041876-78fbe600-96db-11ea-885d-c2c67654a49f.png">



[IntegrationEvent(false, false)]
    local procedure OnBeforeCreateNewCustPmtRequest(DetailedCustLedgEntry; var IsHandled: Boolean)
    begin
    end;
[IntegrationEvent(false, false)]
    local procedure OnBeforeCreateNewRequest(CustLedgEntry; var IsHandled: Boolean)
    begin
    end;`

**Comment by prasadCherukumalli** [comment]
> Please always put the full detailed signature of the requested events.
> If you use AL code copied from VSCode instead of screenshots it will 

Hi StanPesotskiy,
I have attached screenshots from Vs code and secured codes are added, is that what you are asking for?

**Comment by StanPesotskiy** [comment]
It is already implemented if you see the record:
  bc-ghost added the [ships-in-future-update] label 

For the next time, the best way to ask for an event is to implement it by yourself and copy&paste AL code into the request here. 
Screenshots are not effective. Put the definition of the event and some code lines that would identify the place of the call. That helps.

**Comment by prasadCherukumalli** [comment]
> It is already implemented if you see the record:
> bc-ghost added the [ships-in-future-update] label
> 
> For the next time, the best way to ask for an event is to implement it by yourself and copy&paste AL code into the request here.
> Screenshots are not effective. Put the definition of the event and some code lines that would identify the place of the call. That helps.

That's great, Do I get some notification when the next version released with this fix?

**Comment by StanPesotskiy** [comment]
I don't think we notify per each request. You will see it in the next update (16.2 as of now) or you can verify manually in the docker 16.x images one-two days after you got your request closed with the [ships-in-future-update] label.

**Comment by prasadCherukumalli** [comment]
Thank you StanPesotskiy
