### ISSUE TITLE
[Event Request] Table 9053 "Sales Cue", OnAfterCountSalesOrdersSetFilters

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6927]
[Event Request] Table 9053 "Sales Cue", OnAfterCountSalesOrdersSetFilters

It needs to be possible to set additional filters for counting sales orders.

    procedure CountOrders(FieldNumber: Integer): Integer
    var
        SalesHeader: Record "Sales Header";
        CountSalesOrders: Query "Count Sales Orders";
    begin
        CountSalesOrders.SetRange(Status, SalesHeader.Status::Released);
        CountSalesOrders.SetRange(Completely_Shipped, false);
        FilterGroup(2);
        CountSalesOrders.SetFilter(Responsibility_Center, GetFilter("Responsibility Center Filter"));
        OnAfterCountSalesOrdersSetFilter(CountSalesOrders);
        FilterGroup(0);

![image](https://user-images.githubusercontent.com/22153733/81073612-302c7c00-8ee8-11ea-861b-fa5a3b874e3f.png)

   [IntegrationEvent(false, false)]
    local procedure OnAfterCountSalesOrdersSetFilter(var CountSalesOrders: Query "Count Sales Orders")
    begin
    end;

**Integration Event:**
OnAfterCountSalesOrdersSetFilter
**Signature:**
var CountSalesOrders: Query "Count Sales Orders"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
