### ISSUE TITLE
codeunit 249 "VAT Registration Log Mgt."  - procedure PopulateFieldsFromVATRegLog

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#6929]
In cu 249 VAT Registration Log Mgt in procedure PopulateFieldsFromVATRegLog there is an issue when the name on the VIES is empty. the name then is cleared.

could this change be made:
local procedure PopulateFieldsFromVATRegLog(var RecordRef: RecordRef; RecordVariant: Variant; VATRegistrationLog: Record "VAT Registration Log")
    var
        Customer: Record Customer;
        FieldRef: FieldRef;
    begin
        DataTypeManagement.GetRecordRef(RecordVariant, RecordRef);

        if DataTypeManagement.FindFieldByName(RecordRef, FieldRef, Customer.FieldName(Name)) then
      if VATRegistrationLog."Verified Name" <> '' then //new code
            FieldRef.Validate(CopyStr(VATRegistrationLog."Verified Name", 1, FieldRef.Length));

        if VATRegistrationLog."Verified Postcode" <> '' then
            if DataTypeManagement.FindFieldByName(RecordRef, FieldRef, Customer.FieldName("Post Code")) then
                FieldRef.Value(CopyStr(VATRegistrationLog."Verified Postcode", 1, FieldRef.Length));

        if VATRegistrationLog."Verified Street" <> '' then
            if DataTypeManagement.FindFieldByName(RecordRef, FieldRef, Customer.FieldName(Address)) then
                FieldRef.Value(CopyStr(VATRegistrationLog."Verified Street", 1, FieldRef.Length));

        if VATRegistrationLog."Verified City" <> '' then
            if DataTypeManagement.FindFieldByName(RecordRef, FieldRef, Customer.FieldName(City)) then
                FieldRef.Value(CopyStr(VATRegistrationLog."Verified City", 1, FieldRef.Length));
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
