### ISSUE TITLE
[Event Request] Table 9053 "Sales Cue", OnAfterSalesHeaderSetFilter

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6930]
[Event Request] Table 9053 "Sales Cue", OnAfterSalesHeaderSetFilter

It needs to be possible to set additional filters on filtering orders.

    local procedure FilterOrders(var SalesHeader: Record "Sales Header"; FieldNumber: Integer)
    begin
        SalesHeader.SetRange("Document Type", SalesHeader."Document Type"::Order);
        SalesHeader.SetRange(Status, SalesHeader.Status::Released);
        SalesHeader.SetRange("Completely Shipped", false);
        case FieldNumber of
            FieldNo("Ready to Ship"):
                begin
                    SalesHeader.SetRange(Ship);
                    SalesHeader.SetFilter("Shipment Date", GetFilter("Date Filter2"));
                end;
            FieldNo("Partially Shipped"):
                begin
                    SalesHeader.SetRange(Shipped, true);
                    SalesHeader.SetFilter("Shipment Date", GetFilter("Date Filter2"));
                end;
            FieldNo(Delayed):
                begin
                    SalesHeader.SetRange(Ship);
                    SalesHeader.SetFilter("Date Filter", GetFilter("Date Filter"));
                    SalesHeader.SetRange("Late Order Shipping", true);
                end;
        end;
        FilterGroup(2);
        SalesHeader.SetFilter("Responsibility Center", GetFilter("Responsibility Center Filter"));
        OnAfterSalesHeaderSetFilter(SalesHeader);
        FilterGroup(0);
    end;

![image](https://user-images.githubusercontent.com/22153733/81074616-8948df80-8ee9-11ea-961d-8e243aa9dcc3.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterSalesHeaderSetFilter(var SalesHeader: Record "Sales Header")
    begin
    end;

**Integration Event:**
OnAfterSalesHeaderSetFilter
**Signature:**
var SalesHeader: Record "Sales Header"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
