### ISSUE TITLE
[Event Request] Page 256 "Payment Journal"

### ISSUE THREAD

**Issue by apbetts** [microsoft/ALAppExtensions#6933]
Could we get an event for raising/checking additional errors inside the ExportPaymentsToFile action on the "Payment Journal" page please.
IE:
action(ExportPaymentsToFile)
{
	ApplicationArea = Basic, Suite;
	Caption = 'E&xport';
	..........					
		if GenJnlLine.FindFirst then begin
			repeat
				GenJnlLine.DeletePaymentFileErrors;
				if GenJnlLine."Currency Code" <> BankAccount."Currency Code" then
					GenJnlLine.InsertPaymentFileError(NoExportDiffCurrencyErr);
				if ((GenJnlLine."Account Type" = GenJnlLine."Account Type"::"Bank Account") or
					(GenJnlLine."Bal. Account Type" = GenJnlLine."Bal. Account Type"::"Bank Account")) and
				   ((GenJnlLine."Bank Payment Type" <> GenJnlLine."Bank Payment Type"::"Electronic Payment") and
					(GenJnlLine."Bank Payment Type" <> GenJnlLine."Bank Payment Type"::"Electronic Payment-IAT"))
				then
					GenJnlLine.InsertPaymentFileError(StrSubstNo(WrongBankPaymentTypeErr, FieldCaption("Bank Payment Type"),
						"Bank Payment Type"::"Electronic Payment", "Bank Payment Type"::"Electronic Payment-IAT"));
				if not GenJournalBatch."Allow Payment Export" then
					PaymentExportGenJnlCheck.AddBatchEmptyError(GenJnlLine, GenJournalBatch.FieldCaption("Allow Payment Export"), '');
				if GenJnlLine.Amount < 0 then
					GenJnlLine.InsertPaymentFileError(NoExportNegativeErr);
				if GenJnlLine."Recipient Bank Account" = '' then
					GenJnlLine.InsertPaymentFileError(RecipientBankAccountEmptyErr)
				else
					if not UseForElecPaymentChecked(GenJnlLine) then
						GenJnlLine.InsertPaymentFileError(UseForElecPaymentCheckedErr);
						
				**/*Custom event start here*/**
				**OnCheckExportErrors(GenJnlLine);
			until GenJnlLine.Next = 0;**
		end;

	...
    **[IntegrationEvent(false, false)]
    local procedure OnCheckExportErrors(var GenJournalLine: Record "Gen. Journal Line") 
    begin
    end;**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
