### ISSUE TITLE
[Event Request] Table 9055 "Purchase Cue", OnAfterCountPurchOrdersSetFilters

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6934]
[Event Request] Table 9055 "Purchase Cue", OnAfterCountPurchOrdersSetFilters

It needs to be possible to set additional filters for counting purchase orders.

    procedure CountOrders(FieldNumber: Integer): Integer
    var
        PurchaseHeader: Record "Purchase Header";
        CountPurchOrders: Query "Count Purchase Orders";
        Result: Integer;
    begin
        case FieldNumber of
            FieldNo("Outstanding Purchase Orders"):
                begin
                    CountPurchOrders.SetRange(Status, PurchaseHeader.Status::Released);
                    CountPurchOrders.SetRange(Completely_Received, false);
                end;
            FieldNo("Not Invoiced"):
                begin
                    CountPurchOrders.SetRange(Completely_Received, true);
                    CountPurchOrders.SetRange(Partially_Invoiced, false);
                end;
            FieldNo("Partially Invoiced"):
                begin
                    CountPurchOrders.SetRange(Completely_Received, true);
                    CountPurchOrders.SetRange(Partially_Invoiced, true);
                end;
        end;
        FilterGroup(2);
        CountPurchOrders.SetFilter(Responsibility_Center, GetFilter("Responsibility Center Filter"));
        OnAfterCountPurchOrdersSetFilter(CountPurchOrders);
        FilterGroup(0);

        CountPurchOrders.Open;
        CountPurchOrders.Read;
        Result := CountPurchOrders.Count_Orders;

        exit(Result);
    end;

![image](https://user-images.githubusercontent.com/22153733/81116529-dc408800-8f25-11ea-9425-88c2fc3a2ed1.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterCountPurchOrdersSetFilter(var CountPurchOrders: Query "Count Purchase Orders")
    begin
    end;

**Integration Event:**
OnAfterCountPurchOrdersSetFilter
**Signature:**
var CountPurchOrders: Query "Count Purchase Orders"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
