### ISSUE TITLE
[Event Request] Table 9055 "Purchase Cue", OnAfterPurchHeaderSetFilter

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6935]
[Event Request] Table 9055 "Purchase Cue", OnAfterPurchHeaderSetFilter

It needs to be possible to set an additional filter on the PurchaseHeader when showing orders.

    procedure ShowOrders(FieldNumber: Integer)
    var
        PurchHeader: Record "Purchase Header";
    begin
        PurchHeader.SetRange("Document Type", PurchHeader."Document Type"::Order);
        case FieldNumber of
            FieldNo("Outstanding Purchase Orders"):
                begin
                    PurchHeader.SetRange(Status, PurchHeader.Status::Released);
                    PurchHeader.SetRange("Completely Received", false);
                    PurchHeader.SetRange(Invoice);
                end;
            FieldNo("Not Invoiced"):
                begin
                    PurchHeader.SetRange(Status);
                    PurchHeader.SetRange("Completely Received", true);
                    PurchHeader.SetRange(Invoice, false);
                end;
            FieldNo("Partially Invoiced"):
                begin
                    PurchHeader.SetRange(Status);
                    PurchHeader.SetRange("Completely Received", true);
                    PurchHeader.SetRange(Invoice, true);
                end;
        end;
        FilterGroup(2);
        PurchHeader.SetFilter("Responsibility Center", GetFilter("Responsibility Center Filter"));
        OnAfterPurchHeaderSetFilter(PurchHeader);
        FilterGroup(0);

        PAGE.Run(PAGE::"Purchase Order List", PurchHeader);
    end;

![image](https://user-images.githubusercontent.com/22153733/81116865-67218280-8f26-11ea-85f5-3a1b29e5984c.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterPurchHeaderSetFilter(var PurchHeader: Record "Purchase Header")
    begin
    end;

**Integration Event:**
OnAfterPurchHeaderSetFilter
**Signature:**
var PurchHeader: Record "Purchase Header"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
