### ISSUE TITLE
[Event Request] Codeunit 5900 ServOrderManagement OnBeforeLookupServItemNo

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#6936]
Can we add a new event in Codeunit 5900 ServOrderManagement before lookup of Service Item List.  

    procedure LookupServItemNo(var ServItemLine: Record "Service Item Line")
    var
        ServHeader: Record "Service Header";
        ServItem: Record "Service Item";
        ServContractLine: Record "Service Contract Line";
        ServItemList: Page "Service Item List";
        ServContractLineList: Page "Serv. Item List (Contract)";
    begin
        ServHeader.Get(ServItemLine."Document Type", ServItemLine."Document No.");

        if ServHeader."Contract No." = '' then begin
            if ServItem.Get(ServItemLine."Service Item No.") then
                ServItemList.SetRecord(ServItem);
            ServItem.Reset();
            ServItem.SetCurrentKey("Customer No.", "Ship-to Code");
            ServItem.SetRange("Customer No.", ServHeader."Customer No.");
            ServItem.SetRange("Ship-to Code", ServHeader."Ship-to Code");
            OnBeforeLookupServItemNo(ServItemLine, ServItem, ServHeader);     // NEW
            ServItemList.SetTableView(ServItem);
            ServItemList.LookupMode(true);
            if ServItemList.RunModal = ACTION::LookupOK then begin
                ServItemList.GetRecord(ServItem);
                ServItemLine.Validate("Service Item No.", ServItem."No.");
            end;
        end else begin
            if ServItemLine."Service Item No." <> '' then
                if ServContractLine.Get(
                     ServContractLine."Contract Type"::Contract,
                     ServItemLine."Contract No.", ServItemLine."Contract Line No.")
                then
                    ServContractLineList.SetRecord(ServContractLine);
            ServContractLine.Reset();
            ServContractLine.FilterGroup(2);
            ServContractLine.SetRange("Contract Type", ServContractLine."Contract Type"::Contract);
            ServContractLine.SetRange("Contract No.", ServHeader."Contract No.");
            ServContractLine.SetRange("Contract Status", ServContractLine."Contract Status"::Signed);
            ServContractLine.SetRange("Customer No.", ServHeader."Customer No.");
            ServContractLine.SetFilter("Starting Date", '<=%1', ServHeader."Order Date");
            ServContractLine.SetFilter("Contract Expiration Date", '>%1 | =%2', ServHeader."Order Date", 0D);
            ServContractLine.FilterGroup(0);
            ServContractLine.SetRange("Ship-to Code", ServHeader."Ship-to Code");
            ServContractLineList.SetTableView(ServContractLine);
            ServContractLineList.LookupMode(true);
            if ServContractLineList.RunModal = ACTION::LookupOK then begin
                ServContractLineList.GetRecord(ServContractLine);
                ServItemLine.Validate("Service Item No.", ServContractLine."Service Item No.");
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupServItemNo(var ServItemLine: Record "Service Item Line"; var ServItem: Record "Service Item"; ServiceHeader: Record "Service Header");
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
