### ISSUE TITLE
[Event Request] CU 1521 - GetDescription

### ISSUE THREAD

**Issue by msinha82** [microsoft/ALAppExtensions#6937]
The GetDescription Function return the Description (Text 250) of the Workflow Response.
In my development of a new Workflow, I was not able to prepare the response description properly. In my analysis I found this is needed change. Screen shot attached of the before & after outputs.
![Before](https://user-images.githubusercontent.com/43031379/81138957-3c2b4300-8fa7-11ea-968f-019f4aef3304.png)
![After](https://user-images.githubusercontent.com/43031379/81138958-3e8d9d00-8fa7-11ea-86df-386d5aacfaf9.png)

My request is to add an Event Publisher like below:
  // AC038b-Old Code
  //ELSE
  //  EXIT(WorkflowResponse.Description);
 // New Code
  ELSE BEGIN
    OnGetDescription(WorkflowResponse,WorkflowStepArgument);
    EXIT(WorkflowResponse.Description);
  END;
  // AC038e

Object CU 1521 attached in TXT format.
[CU 1521.txt](https://github.com/microsoft/ALAppExtensions/files/4584822/CU.1521.txt)

Thanks,
Manish Sinha

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
