### ISSUE TITLE
[EventRequest] Codeunit 2000042- Post Coded Bank Statement - DecodeVendLedgEntry

### ISSUE THREAD

**Issue by RishtaCader** [microsoft/ALAppExtensions#6938]
Hello,
We need new event in the Codeunit 2000042 (OnDecodeVendLedgEntryOnBeforePost) :

LOCAL DecodeVendLedgEntry()
CLEAR(VendLedgEntry);
WITH CodBankStmtLine DO BEGIN
  IF "Type Standard Format Message" = 107 THEN
    Message := DELCHR(COPYSTR("Statement Message",19,15),'<','0')
  ELSE
    Message := DELCHR(COPYSTR("Statement Message",1,50),'<','0');
  VendLedgEntry.SETCURRENTKEY(Open);
  IF "Statement Amount" > 0 THEN
    VendLedgEntry.SETRANGE("Document Type",VendLedgEntry."Document Type"::"Credit Memo")
  ELSE
    VendLedgEntry.SETRANGE("Document Type",VendLedgEntry."Document Type"::Invoice);

  VendLedgEntry.SETRANGE(Description,Message);
  // New event request >>
  OnDecodeVendLedgEntryOnBeforePost(VendLedgEntry,CodBankStmtLine,Message);
  // New event request <<
  IF VendLedgEntry.FINDFIRST THEN
    PostVendLedgEntry;
END

Signature :
LOCAL [IntegrationEvent] OnDecodeVendLedgEntryOnBeforePost(VAR VendLedgerEntry : Record "Vendor Ledger Entry";VAR CODAStatementLine : Record "CODA Statement Line";VAR Message : Text[50])

Thank you
Kind Regards
Rishta

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
