### ISSUE TITLE
[Extensibility enhancement] Table 81 InsertPaymentLines procedure

### ISSUE THREAD

**Issue by Serenissima1** [microsoft/ALAppExtensions#6939]
Hello,

could you change the scope of the InsertPaymentLines procedure in Table 81 from OnPrem to OnCloud? The requests is also for the subprocedures called from there. Below I have reported the affected code.

Thanks,

Luca

    [Scope('OnPrem')]
    procedure InsertPaymentLines()
    begin
        GenJnlTemplate.Get("Journal Template Name");

        PaymentTermsLine.Reset();
        PaymentTermsLine.SetRange("Sales/Purchase", PaymentTermsLine."Sales/Purchase"::" ");
        PaymentTermsLine.SetRange(Type, PaymentTermsLine.Type::"Payment Terms");
        PaymentTermsLine.SetRange(Code, "Payment Terms Code");

        if PaymentTermsLine.Find('-') then begin
            PaymentCounter := 0;
            repeat
                if "Account Type" = "Account Type"::Vendor then
                    PurchasePayment
                else
                    SalePayment;
            until PaymentTermsLine.Next = 0;
        end;
    end;

    [Scope('OnPrem')]
    procedure PurchasePayment()
    var
        Vend: Record Vendor;
    begin
        PaymentPurchase.Init();
        PaymentPurchase."Sales/Purchase" := PaymentPurchase."Sales/Purchase"::" ";
        PaymentPurchase.Type := PaymentPurchase.Type::"General Journal";
        PaymentPurchase."Journal Template Name" := "Journal Template Name";

        if "Line No." = 0 then
            PaymentPurchase."Journal Line No." := 10000
        else
            PaymentPurchase."Journal Line No." := "Line No.";

        PaymentPurchase.Code := "Journal Batch Name";
        PaymentCounter := PaymentCounter + 10000;
        PaymentPurchase."Line No." := PaymentCounter;
        PaymentPurchase."Payment %" := PaymentTermsLine."Payment %";
        PaymentPurchase."Due Date Calculation" := PaymentTermsLine."Due Date Calculation";
        PaymentPurchase."Discount Date Calculation" := PaymentTermsLine."Discount Date Calculation";
        PaymentPurchase."Discount %" := PaymentTermsLine."Discount %";
        PaymentPurchase."Due Date" := CalcDate(PaymentTermsLine."Due Date Calculation", "Document Date");

        if PaymentPurchase."Due Date" < "Document Date" then
            PaymentPurchase."Due Date" := "Document Date";

        FixedDueDate.Reset();
        Vend.Get("Account No.");
        if Vend."Apply Company Payment days" = true then begin
            FixedDueDate.SetRange(Type, FixedDueDate.Type::Company);
            FixedDueDate.SetRange(Code, '');
        end else begin
            FixedDueDate.SetRange(Type, FixedDueDate.Type::Vendor);
            FixedDueDate.SetRange(Code, "Account No.");
        end;

        if FixedDueDate.Count > 0 then begin
            FixedDueDate.SetRange("Payment Days", Date2DMY(PaymentPurchase."Due Date", 1), 99);
            if FixedDueDate.FindFirst then begin
                Day := FixedDueDate."Payment Days";
                MaximumDay := Date2DMY(CalcDate('CM', PaymentPurchase."Due Date"), 1);
                if Day > MaximumDay then
                    Day := MaximumDay;
                Month := Date2DMY(PaymentPurchase."Due Date", 2);
                Year := Date2DMY(PaymentPurchase."Due Date", 3);
                PaymentPurchase."Due Date" := DMY2Date(Day, Month, Year);
            end else begin
                FixedDueDate.SetRange("Payment Days");
                FixedDueDate.FindFirst;
                Day := FixedDueDate."Payment Days";
                MaximumDay := Date2DMY(CalcDate('CM+1M', PaymentPurchase."Due Date"), 1);
                if Day > MaximumDay then
                    Day := MaximumDay;
                Month := Date2DMY(PaymentPurchase."Due Date", 2) + 1;
                Year := Date2DMY(PaymentPurchase."Due Date", 3);
                if Month = 13 then begin
                    Month := 1;
                    Year := Year + 1;
                end;
                PaymentPurchase."Due Date" := DMY2Date(Day, Month, Year);
            end;
        end;

        if PaymentTerms.Get("Payment Terms Code") then;
        if not PaymentTerms."Calc. Pmt. Disc. on Cr. Memos" and ("Document Type" = "Document Type"::"Credit Memo") then begin
            PaymentPurchase."Discount %" := 0;
            Evaluate(PaymentPurchase."Discount Date Calculation", '<0D>');
            PaymentPurchase."Due Date" := "Posting Date";
        end else begin
            PaymentPurchase."Pmt. Discount Date" := CalcDate(PaymentTermsLine."Discount Date Calculation", "Document Date");
            if PaymentPurchase."Pmt. Discount Date" < "Document Date" then
                PaymentPurchase."Pmt. Discount Date" := "Document Date";
        end;

        PaymentPurchase.Insert();
    end;

    [Scope('OnPrem')]
    procedure SalePayment()
    begin
        PaymentSales.Init();
        PaymentSales."Sales/Purchase" := PaymentSales."Sales/Purchase"::" ";
        PaymentSales.Type := PaymentSales.Type::"General Journal";
        PaymentSales."Journal Template Name" := "Journal Template Name";

        if "Line No." = 0 then
            PaymentSales."Journal Line No." := 10000
        else
            PaymentSales."Journal Line No." := "Line No.";

        PaymentSales.Code := "Journal Batch Name";
        PaymentCounter := PaymentCounter + 10000;
        PaymentSales."Line No." := PaymentCounter;
        PaymentSales."Payment %" := PaymentTermsLine."Payment %";
        PaymentSales."Due Date Calculation" := PaymentTermsLine."Due Date Calculation";
        PaymentSales."Discount Date Calculation" := PaymentTermsLine."Discount Date Calculation";
        PaymentSales."Discount %" := PaymentTermsLine."Discount %";
        PaymentSales."Due Date" := CalcDate(PaymentTermsLine."Due Date Calculation", "Document Date");

        if PaymentSales."Due Date" < "Document Date" then
            PaymentSales."Due Date" := "Document Date";

        DefDueDates.SetCurrentKey("No.", "To-Date");
        DefDueDates.SetRange("No.", "Account No.");
        DefDueDates.SetFilter("To-Date", '%1..', PaymentSales."Due Date");

        if DefDueDates.FindFirst and
           (DefDueDates."From-Date" <= PaymentSales."Due Date")
        then begin
            if "Document Type" <> "Document Type"::"Credit Memo" then
                PaymentSales."Due Date Calculation" := DefDueDates."Due Date Calculation";
            PaymentSales."Due Date" := CalcDate(DefDueDates."Due Date Calculation", DefDueDates."To-Date");
            if PaymentSales."Due Date" < "Document Date" then
                PaymentSales."Due Date" := "Document Date";
        end;

        FixedDueDate.Reset();
        FixedDueDate.SetRange(Type, FixedDueDate.Type::Customer);
        FixedDueDate.SetRange(Code, "Account No.");

        if FixedDueDate.Count > 0 then begin
            FixedDueDate.SetRange("Payment Days", Date2DMY(PaymentSales."Due Date", 1), 99);
            if FixedDueDate.FindFirst then begin
                Day := FixedDueDate."Payment Days";
                MaximumDay := Date2DMY(CalcDate('CM', PaymentSales."Due Date"), 1);
                if Day > MaximumDay then
                    Day := MaximumDay;
                Month := Date2DMY(PaymentSales."Due Date", 2);
                Year := Date2DMY(PaymentSales."Due Date", 3);
                PaymentSales."Due Date" := DMY2Date(Day, Month, Year);
            end else begin
                FixedDueDate.SetRange("Payment Days");
                FixedDueDate.FindFirst;
                Day := FixedDueDate."Payment Days";
                MaximumDay := Date2DMY(CalcDate('CM+1M', PaymentSales."Due Date"), 1);
                if Day > MaximumDay then
                    Day := MaximumDay;
                Month := Date2DMY(PaymentSales."Due Date", 2) + 1;
                Year := Date2DMY(PaymentSales."Due Date", 3);
                if Month = 13 then begin
                    Month := 1;
                    Year := Year + 1;
                end;
                PaymentSales."Due Date" := DMY2Date(Day, Month, Year);
            end;
        end;

        if PaymentTerms.Get("Payment Terms Code") then;
        if not PaymentTerms."Calc. Pmt. Disc. on Cr. Memos" and ("Document Type" = "Document Type"::"Credit Memo") then begin
            PaymentSales."Discount %" := 0;
            Evaluate(PaymentSales."Discount Date Calculation", '<0D>');
            PaymentSales."Due Date" := "Posting Date"
        end else begin
            PaymentSales."Pmt. Discount Date" := CalcDate(PaymentTermsLine."Discount Date Calculation", "Document Date");
            if PaymentSales."Pmt. Discount Date" < "Document Date" then
                PaymentSales."Pmt. Discount Date" := "Document Date";
        end;

        PaymentSales.Insert();
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
