### ISSUE TITLE
[Event Request] TAB38 "Purchase Header", OnBeforeShowDocDim

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6940]
Hi,

We need a new event in Table 38, "Purchase Header" in Procedure "ShowDocDim".

![image](https://user-images.githubusercontent.com/64889775/81149343-5270d900-8f7e-11ea-90bc-078022c14012.png)

![image](https://user-images.githubusercontent.com/64889775/81149478-9368ed80-8f7e-11ea-9932-1b9d16145e11.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
