### ISSUE TITLE
[Event Request] TAB39 "Purchase Line", OnBeforeShowDimensions

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6941]
Hi,
We need a new event in Table 39, "Purchase Line" in Procedure "ShowDimenions".

![image](https://user-images.githubusercontent.com/64889775/81150633-7c2aff80-8f80-11ea-8144-660eb8ae8d42.png)

![image](https://user-images.githubusercontent.com/64889775/81150785-a1b80900-8f80-11ea-932a-b0cd2ebd1aa4.png)

**Comment by StanPesotskiy** [comment]
If you put AL code copied from VSCode or C/Side instead of screenshots it speeds up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
