### ISSUE TITLE
[Event Change Request] TAB39 "Purchase Line", OnBeforeCreateTempJobJnlLine with IsHandled

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6942]
Hi,

Is it possible to change the event in Table 39, "Purchase Line" in Procedure "CreateTempJobJnlLine" with a "IsHandled" variable and coding.

Situation now:
![image](https://user-images.githubusercontent.com/64889775/81151877-b1841d00-8f81-11ea-8e0b-884f982c88dd.png)

Situation desired:
![image](https://user-images.githubusercontent.com/64889775/81152045-dc6e7100-8f81-11ea-838a-d5225f26fb8b.png)

**Comment by StanPesotskiy** [comment]
Already done for https://github.com/microsoft/ALAppExtensions/issues/6570
