### ISSUE TITLE
[Event Request] TAB39 "Purchase Line", "Job No." OnValidate Trigger, OnValidateJobNoBeforeFieldErrorJobNo

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6943]
Hi,
We need a new event in Table 39 "Purchase Line", "Job No." OnValidate Trigger.

![image](https://user-images.githubusercontent.com/64889775/81152947-bb5a5000-8f82-11ea-82ad-c519756a3c40.png)

![image](https://user-images.githubusercontent.com/64889775/81153048-d2993d80-8f82-11ea-995a-55ba1e5ecfc0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
