### ISSUE TITLE
[Event Request] TAB39 "Purchase Line", "Promised Receipt Date" OnValidate Trigger, OnValidatePromisedReceiptDate

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6944]
Hi,
We need a new event in Table 39, "Purchase Line", "Promised Receipt Date" OnValidate Trigger.

![image](https://user-images.githubusercontent.com/64889775/81153511-49ced180-8f83-11ea-9ca5-a23eda2bc2bd.png)

![image](https://user-images.githubusercontent.com/64889775/81153676-71259e80-8f83-11ea-8b7c-f5cb8a664ada.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
