### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line", OnBeforeJobTaskIsSet

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6945]
Hi,
We need a new event in Table 81, "Gen. Journal Line" in Procedure "JobTaskIsSet".

![image](https://user-images.githubusercontent.com/64889775/81159109-ee9fdd80-8f88-11ea-8d23-517c9408ec80.png)

![image](https://user-images.githubusercontent.com/64889775/81159255-12632380-8f89-11ea-8898-e30c1ac79893.png)

**Comment by StanPesotskiy** [comment]
Already done for https://github.com/microsoft/ALAppExtensions/issues/6496
