### ISSUE TITLE
Unable to add 'Extension field' to 'Extension List Page' and 'Extension Card Page' with designer.

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#6946]
We are trying to add **Extension field** of type **Boolean** directly to **'Extension List Page'** and **'Extension Card Page'** using designer.

Getting error and docker logs me out, Please find the attached screens for the error. 
![Project Card](https://user-images.githubusercontent.com/57799519/81158629-cbcff200-8fa5-11ea-8cdf-99261e2c3a13.png)
![Projects List](https://user-images.githubusercontent.com/57799519/81158632-cbcff200-8fa5-11ea-89a3-0686ac59049b.png)
![Error](https://user-images.githubusercontent.com/57799519/81158623-ca062e80-8fa5-11ea-926b-df6b6a66e7c6.png)

**Comment by StanPesotskiy** [comment]
This issue is not related to the AL extensibility, it seems to be a platform (web client?) bug.
Please report it via the standard support channel.
