### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line", OnBeforeCopyDimensionsFromJobTaskLine

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6947]
Hi,
We need a new event in Table 81, "Gen. Journal Line" in Procedure "CopyDimensionsFromJobTaskLine".

![image](https://user-images.githubusercontent.com/64889775/81160068-ef853f00-8f89-11ea-9cdf-d322bf407398.png)

![image](https://user-images.githubusercontent.com/64889775/81160157-062b9600-8f8a-11ea-8864-3702b3a2d7d8.png)
![image](https://user-images.githubusercontent.com/64889775/81160210-13488500-8f8a-11ea-86d3-5a14791d0cab.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
