### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line", "Account No." and "Bal. Account No." OnValidate Triggers, OnBeforeValidateEmptyJobNo

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6948]
Hi,

We need a new event in Table 81, "Gen. Journal Line" for the validation trigger of Field "Account No." and "Bal. Account No.". So 1 event for 2 triggers.

Validation trigger field "Account No.":
![image](https://user-images.githubusercontent.com/64889775/81160985-1f811200-8f8b-11ea-9117-0ccb542054b5.png)

Validation trigger field "Bal. Account No.":
![image](https://user-images.githubusercontent.com/64889775/81161107-57885500-8f8b-11ea-8a68-cf176de82750.png)

![image](https://user-images.githubusercontent.com/64889775/81161158-6a028e80-8f8b-11ea-9d49-dbab7b99d826.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
