### ISSUE TITLE
Event request T36 field "Return Receipt No. Series"

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#6949]
Hi we have a need for event on table 36 in field "Return Receipt No. Series" before validation with handle and on lookup. We are using another type of documents on this field.
Example of refactured code:

![image](https://user-images.githubusercontent.com/53824412/81161276-9dddb400-8f8b-11ea-97f6-0355e8b8518e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
