### ISSUE TITLE
Please explain use of "SuppressCommit" in CU5763

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#695]
Hi,

you closed my previus issue #16 for this reason:

> After further discussions I am sorry to disappoint you, but currently we do not intend to make suppressing of commits generally available. We would still like to handle your specific issues though. Please just create a new issue for the individual requests.

Well. Please can you explain how we can use "SuppressCommit" in warehouse?

CU 5763 call CU80, CU90 and CU5704. All these CUs have "SuppressCommit" but CU 5763 not.

Maybe we have to develop our version of "Whse.-Post Shipment" ? Or "SuppressCommit" will be added to warehouse and we have to redefine all posting entry points? Or your "further discussions" should be more "further"?

**Please don't underestimate partner experience, the road ahead is long.**

S.

**Comment by grobyns** [comment]
Hi,

as mentioned before, the way to "fix" this would be to request that the SuppressCommit pattern be added to CU 5763 in the same way as it has been added to CU 80, CU 90 and CU 5704. You would then be able to create a variable of CU 5763 and call SetSuppressCommit on that. The SuppressCommit would get passed along to the relevant other cu's called in CU 5763.
I assume you would want us to also add this to CU 5760.

Would you like us to implement SuppressCommit in CU 5763 and CU 5760? 

br/Gert

**Comment by sgiordy** [comment]
Hi @grobyns 

> Would you like us to implement SuppressCommit in CU 5763 and CU 5760?

Yes please, warehouse is an important part of Dynamics BC!

In the future, when you want to talk about COMMITs, we are ready, nights and days :-)

S.

**Comment by JamesCarrSaunders** [comment]
I second this. There are many commits in the warehouse management system which I routinely remove on implementation. If we are now unable to remove them we require a pattern such as SupressCommit. It would be better if they were simply removed (they should never have been added)

**Comment by sgiordy** [comment]
@JesperSchulz 
@grobyns 

With extensions style development, COMMIT is an absolutely unsafe instruction! You will never be sure about database integrity. What about a crazy APP with COMMIT in the middle of a codeunit, raised by an event subscription, with show_my_code=false?

Simply a mess.

COMMIT must be removed from posting codeunits and generally you have to provide a global event to handle them (for example OnBeforeCommit with caller information and a variable by reference to skip the commit, but handled in a safe way: the first subscriber that want to skip, skip it for all).

I'm not sure that you would to manage your money savings with a random-commit software.

**Comment by JesperSchulz** [comment]
Doing some ticket inventory when I stumbled upon this open issue! Somehow the system did not report back, that the improvement request linked to this issue was resolved on the 15th of May. The changes should have shipped with the latest major release in October. I'm hence closing this issue. If you have further requests, please open a new ticket or, if the request is larger, log an Idea on [aka.ms/bcideas](aka.ms/bcideas). Sorry about the breach in communication - it would appear the link between tickets and our internal system failed for a few issues. My apologies.
