### ISSUE TITLE
[Event Change Request] Table 81 "Gen. Journal Line", OnBeforeCreateTempJobJnlLine with IsHandled

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6950]
Hi,

Is it possible to change the event in Table 81, "Gen. Journal Line" in Procedure "CreateTempJobJnlLine" with a "IsHandled" variable and coding.

Situation now:
![image](https://user-images.githubusercontent.com/64889775/81161648-2f4d2600-8f8c-11ea-89d8-63b8d84917cf.png)

Situation desired:
![image](https://user-images.githubusercontent.com/64889775/81161772-615e8800-8f8c-11ea-99b6-23bd9fbab719.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
