### ISSUE TITLE
[Event Request] Table 349 "Dimension  Value", OnDelete Trigger, OnDeleteBeforeDimValueUsed

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6951]
Hi,
We need a new event in Table 349, "Dimension  Value" in the OnDelete Trigger.

![image](https://user-images.githubusercontent.com/64889775/81162679-ded6c800-8f8d-11ea-9612-68e16d18dd63.png)

![image](https://user-images.githubusercontent.com/64889775/81162721-ee561100-8f8d-11ea-9490-c4b499eb55c3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
