### ISSUE TITLE
[Event Change] Codeunit 12 Gen. Jnl.-Post Line - OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToRevChargeAcc

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#6952]
Please make the 2 following parameters of event publisher OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToRevChargeAcc **ByVAR**:
- VATAmount
- VATAmountAddCurr

Like below:

```
LOCAL [IntegrationEvent] OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToRevChargeAcc(VAR GenJournalLine : Record "Gen. Journal Line";VATPostingSetup : Record "VAT Posting Setup";UnrealizedVAT : Boolean;VAR VATAmount : Decimal;VAR VATAmountAddCurr : Decimal;UseAmountAddCurr : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
