### ISSUE TITLE
[Event Request] Codeunit 8 "AccSchedManagement", OnAfterSetGLAccGLEntryFilters

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6953]
Hi,
We need a new event in Codeunit 8 "AccSchedManagement" in Procedure "SetGLAccGLEntryFilters".

![image](https://user-images.githubusercontent.com/64889775/81163573-43deed80-8f8f-11ea-92c0-0ed116b84f79.png)

![image](https://user-images.githubusercontent.com/64889775/81163652-61ac5280-8f8f-11ea-8940-53c74de4d327.png)

**Comment by StanPesotskiy** [comment]
Already implemented.
