### ISSUE TITLE
[Event Request] Codeunit 8 "AccSchedManagement", OnAfterSetGLAccAnalysisViewEntryFilters

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6954]
Hi,
We need a new event in Codeunit 8 "AccSchedManagement" in Procedure "SetGLAccAnalysisViewEntryFilters".

![image](https://user-images.githubusercontent.com/64889775/81164063-0169e080-8f90-11ea-8a4c-7ec441d08d74.png)

![image](https://user-images.githubusercontent.com/64889775/81164172-37a76000-8f90-11ea-9128-f4c99fd4593d.png)
![image](https://user-images.githubusercontent.com/64889775/81164203-44c44f00-8f90-11ea-8c1a-27a9f1b78236.png)

**Comment by StanPesotskiy** [comment]
Already implemented.
