### ISSUE TITLE
[Event Request] Codeunit 410 "Update Analysis View", FlushAnalysisViewEntry

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6955]
Hi,
We need a new event in Codeunit  410 "Update Analysis View" in Procedure "FlushAnalysisViewEntry".

![image](https://user-images.githubusercontent.com/64889775/81169021-645f7580-8f98-11ea-8c32-c00d8ec6eae8.png)

![image](https://user-images.githubusercontent.com/64889775/81169053-72ad9180-8f98-11ea-9c15-9bbd766de7c9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
