### ISSUE TITLE
[Event Request] Codeunit 5702 "Dist. Integration", EnterPurchaseItemCrossRef

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6956]
Hi,
We need a new event in Codeunit 5702 "Dist. Integration" in Procedure "EnterPurchaseItemCrossRef".

![image](https://user-images.githubusercontent.com/64889775/81169401-172fd380-8f99-11ea-9912-6ae6e329fb72.png)

![image](https://user-images.githubusercontent.com/64889775/81169464-2f9fee00-8f99-11ea-8973-d9e8a57fb020.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
