### ISSUE TITLE
[Event Request] Codeunit 1372 "Purchase Batch Post Mgt.", RunBatch

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6957]
Hi,
We need a new event in Codeunit 1372 "Purchase Batch Post Mgt." in Procedure "RunBatch".

![image](https://user-images.githubusercontent.com/64889775/81170192-89ed7e80-8f9a-11ea-839f-74b4c2fc1fdf.png)

![image](https://user-images.githubusercontent.com/64889775/81170245-a093d580-8f9a-11ea-95c9-8e9b5da2aeba.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
