### ISSUE TITLE
[Event Request] Codeunit 5601 "FA Insert G/L Account", CorrectBookValueEntry

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6958]
Hi,
We need 2 new events in Codeunit 5601 "FA Insert G/L Account" in Procedure "CorrectBookValueEntry".

Event 1:
![image](https://user-images.githubusercontent.com/64889775/81171089-164c7100-8f9c-11ea-98ed-4d0e6853a5b2.png)

Event 2:
![image](https://user-images.githubusercontent.com/64889775/81171162-3714c680-8f9c-11ea-8bb8-08d7ca68a263.png)

![image](https://user-images.githubusercontent.com/64889775/81171222-4f84e100-8f9c-11ea-8ff7-4b780de8aedb.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
