### ISSUE TITLE
[Event Request] Codeunit 5601 "FA Insert G/L Account", InsertBalAcc

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#6959]
Hi,
We need a new event in Codeunit 5601 "FA Insert G/L Account" in Procedure "InsertBalAcc".

![image](https://user-images.githubusercontent.com/64889775/81171543-d5089100-8f9c-11ea-94a8-1baf3a92c0e6.png)

![image](https://user-images.githubusercontent.com/64889775/81171706-2153d100-8f9d-11ea-9a79-aab40a21539a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
