### ISSUE TITLE
EventRequest CU 99000832 function VerifyChange

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#6960]
Hi, 
we need to check several conditions before entering VerifyChange in CU 99000832 like:
![image](https://user-images.githubusercontent.com/53824412/81174579-60d0ec00-8fa2-11ea-987f-a6ad44fdd402.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
