### ISSUE TITLE
Eventrequest on T37 OnDelete trigger

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#6961]
Hi,
we need to CleanPurchaseLineSpecialOrderFields on t37 OnDelete trigger. It should look like:

![image](https://user-images.githubusercontent.com/53824412/81175248-814d7600-8fa3-11ea-90ff-a9bdfd94216f.png)

**Comment by VladimirVeljovic** [comment]
Hi,
sorry i think i already requested this in https://github.com/microsoft/ALAppExtensions/issues/4996
so, you can use this as an example.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
