### ISSUE TITLE
Use of PageID from Journal Template in Codeunit 700

### ISSUE THREAD

**Issue by andersbering** [microsoft/ALAppExtensions#6965]
Having setup General Journal Templates

![image](https://user-images.githubusercontent.com/20658868/81188105-39cfe580-8fb5-11ea-96e9-cc8d42aeb877.png)

In codeunit 700 Page Management - function GetGenJournalLinePageID
![image](https://user-images.githubusercontent.com/20658868/81188334-7bf92700-8fb5-11ea-8439-e1b3a54a915b.png)

If the Page ID is specified it is not nessessary to run through the rest.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
