### ISSUE TITLE
Page 43 "SetDocumentIsPosted"

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/ALAppExtensions#697]
Hi,

previous issue #184 was closed with a refactor of "DocumentIsPosted" variable and with a new event "OnPostOnAfterSetDocumentIsPosted".

But this is not enough in some scenario, such as custom order posting.

Because "OnPostOnAfterSetDocumentIsPosted" is triggered by "Post" procedure, that is LOCAL, there is no way to skip confirmation on page closing.

We fixed in this way:

`[External] SetDocumentIsPosted(NewDocumentIsPosted : Boolean)
DocumentIsPosted := NewDocumentIsPosted;`

Thank you
S.

**Comment by IhorHandziuk** [comment]
Thank you for your request. If the problem is only with skipping confirmation dialog, will it be enough if we introduce new boolean variable (e. g. ShowConfirmationDialogIfDocumentIsNotPosted with setter and getter) and check it inside OnQueryClosePage?

**Comment by sgiordy** [comment]
Hi @IhorHandziuk yes the problem is only the confirmation dialog because, in case of custom posting, is misleading the user. Thank you.
