### ISSUE TITLE
[Event Request] Table 39 "Purchase Line", OnBeforeInitHeaderDefaults

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#6970]
[Event Request] Table 39 "Purchase Line", OnBeforeInitHeaderDefaults

The procedure InitHeaderDefaults starts with a TestField on the "Buy-from Vendor No.". I think that this is not even correct in all of the cases. But notwithstanding that assumption, some partners have allowed for a more differentiated treatment, especially in sales quotes. So we would need a Handled Pattern here to avoid the TestField if necessary.

    local procedure InitHeaderDefaults(PurchHeader: Record "Purchase Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInitHeaderDefaults(Rec, PurchHeader);
        if not IsHandled then
            PurchHeader.TestField("Buy-from Vendor No.");

        "Buy-from Vendor No." := PurchHeader."Buy-from Vendor No.";

![image](https://user-images.githubusercontent.com/22153733/81202934-93d9a680-8fc7-11ea-80a9-2bc431e35261.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitHeaderDefaults(var PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header")
    begin
    end;

**Integration Event:**
OnBeforeInitHeaderDefaults
**Signature:**
var PurchLine: Record "Purchase Line"
PurchHeader: Record "Purchase Header"

**Comment by StanPesotskiy** [comment]
Already done for https://github.com/microsoft/ALAppExtensions/issues/6071.
