### ISSUE TITLE
[Event Request] Codeunit 60 Sales-Calc. Discount – CalculateInvoiceDiscount -> OnBeforeCustInvDiscRecExists

### ISSUE THREAD

**Issue by Mfelice1975** [microsoft/ALAppExtensions#6971]
Please, could we have a publisher "OnBeforeCustInvDiscRecExists" in function CalculateInvoiceDiscount in Codeunit 60 "Sales-Calc. Discount"?

local procedure CalculateInvoiceDiscount(var SalesHeader: Record "Sales Header"; var SalesLine2: Record "Sales Line")
    var
        TempVATAmountLine: Record "VAT Amount Line" temporary;
        SalesSetup: Record "Sales & Receivables Setup";
        TempServiceChargeLine: Record "Sales Line" temporary;
        SalesCalcDiscountByType: Codeunit "Sales - Calc Discount By Type";
        DiscountNotificationMgt: Codeunit "Discount Notification Mgt.";
        IsHandled: Boolean;
    begin
        SalesSetup.Get();
        if UpdateHeader then
            SalesHeader.Find; // To ensure we have the latest - otherwise update fails

        IsHandled := false;
        OnBeforeCalcSalesDiscount(SalesHeader, IsHandled, SalesLine2, UpdateHeader);
        if IsHandled then
            exit;

        with SalesLine do begin
            LockTable();
            SalesHeader.TestField("Customer Posting Group");
            CustPostingGr.Get(SalesHeader."Customer Posting Group");

            SalesLine2.Reset();
            SalesLine2.SetRange("Document Type", "Document Type");
            SalesLine2.SetRange("Document No.", "Document No.");
            SalesLine2.SetRange("System-Created Entry", true);
            SalesLine2.SetRange(Type, SalesLine2.Type::"G/L Account");
            SalesLine2.SetRange("No.", CustPostingGr."Service Charge Acc.");
            if SalesLine2.FindSet(true, false) then
                repeat
                    SalesLine2."Unit Price" := 0;
                    SalesLine2.Modify();
                    TempServiceChargeLine := SalesLine2;
                    TempServiceChargeLine.Insert();
                until SalesLine2.Next = 0;

            SalesLine2.Reset();
            SalesLine2.SetRange("Document Type", "Document Type");
            SalesLine2.SetRange("Document No.", "Document No.");
            SalesLine2.SetFilter(Type, '<>0');
            SalesLine2.SetRange("Automatically Generated", false);
            if SalesLine2.FindFirst then;
            SalesLine2.CalcVATAmountLines(0, SalesHeader, SalesLine2, TempVATAmountLine);
            InvDiscBase :=
              TempVATAmountLine.GetTotalInvDiscBaseAmount(
                SalesHeader."Prices Including VAT", SalesHeader."Currency Code");
            ChargeBase :=
              TempVATAmountLine.GetTotalLineAmount(
                SalesHeader."Prices Including VAT", SalesHeader."Currency Code");

            if UpdateHeader then
                SalesHeader.Modify();

            if SalesHeader."Posting Date" = 0D then
                CurrencyDate := WorkDate
            else
                CurrencyDate := SalesHeader."Posting Date";

            CustInvDisc.GetRec(
              SalesHeader."Invoice Disc. Code", SalesHeader."Currency Code", CurrencyDate, ChargeBase);

            if CustInvDisc."Service Charge" <> 0 then begin
                Currency.Initialize(SalesHeader."Currency Code");
                if not UpdateHeader then
                    SalesLine2.SetSalesHeader(SalesHeader);
                if not TempServiceChargeLine.IsEmpty then begin
                    TempServiceChargeLine.FindLast;
                    SalesLine2.Get("Document Type", "Document No.", TempServiceChargeLine."Line No.");
                    SetSalesLineServiceCharge(SalesHeader, SalesLine2);
                    SalesLine2.Modify();
                end else begin
                    SalesLine2.Reset();
                    SalesLine2.SetRange("Document Type", "Document Type");
                    SalesLine2.SetRange("Document No.", "Document No.");
                    SalesLine2.FindLast;
                    SalesLine2.Init();
                    if not UpdateHeader then
                        SalesLine2.SetSalesHeader(SalesHeader);
                    SalesLine2."Line No." := SalesLine2."Line No." + 10000;
                    SalesLine2."System-Created Entry" := true;
                    SalesLine2.Type := SalesLine2.Type::"G/L Account";
                    SalesLine2.Validate("No.", CustPostingGr.GetServiceChargeAccount);
                    SalesLine2.Description := Text000;
                    SalesLine2.Validate(Quantity, 1);

                    OnAfterValidateSalesLine2Quantity(SalesHeader, SalesLine2, CustInvDisc);

                    if SalesLine2."Document Type" in
                       [SalesLine2."Document Type"::"Return Order", SalesLine2."Document Type"::"Credit Memo"]
                    then
                        SalesLine2.Validate("Return Qty. to Receive", SalesLine2.Quantity)
                    else
                        SalesLine2.Validate("Qty. to Ship", SalesLine2.Quantity);
                    SetSalesLineServiceCharge(SalesHeader, SalesLine2);
                    SalesLine2.Insert();
                end;
                SalesLine2.CalcVATAmountLines(0, SalesHeader, SalesLine2, TempVATAmountLine);
            end else
                if TempServiceChargeLine.FindSet(false, false) then
                    repeat
                        if (TempServiceChargeLine."Shipment No." = '') and (TempServiceChargeLine."Qty. Shipped Not Invoiced" = 0) then begin
                            SalesLine2 := TempServiceChargeLine;
                            SalesLine2.Delete(true);
                        end;
                    until TempServiceChargeLine.Next = 0;
			// >> NEW EVENT
			OnBeforeCustInvDiscRecExists(SalesHeader, IsHandled, SalesLine2, UpdateHeader, InvDiscBase, ChargeBase, TempVATAmountLine)
			if IsHandled then
				exit;
			// <<  NEW EVENT
            if CustInvDiscRecExists(SalesHeader."Invoice Disc. Code") then begin
                OnAfterCustInvDiscRecExists(SalesHeader);
                if InvDiscBase <> ChargeBase then
                    CustInvDisc.GetRec(
                      SalesHeader."Invoice Disc. Code", SalesHeader."Currency Code", CurrencyDate, InvDiscBase);

                DiscountNotificationMgt.NotifyAboutMissingSetup(
                  SalesSetup.RecordId, SalesHeader."Gen. Bus. Posting Group",
                  SalesSetup."Discount Posting", SalesSetup."Discount Posting"::"Line Discounts");

                SalesHeader."Invoice Discount Calculation" := SalesHeader."Invoice Discount Calculation"::"%";
                SalesHeader."Invoice Discount Value" := CustInvDisc."Discount %";
                if UpdateHeader then
                    SalesHeader.Modify();

                TempVATAmountLine.SetInvoiceDiscountPercent(
                  CustInvDisc."Discount %", SalesHeader."Currency Code",
                  SalesHeader."Prices Including VAT", SalesSetup."Calc. Inv. Disc. per VAT ID",
                  SalesHeader."VAT Base Discount %");

                SalesLine2.SetSalesHeader(SalesHeader);
                SalesLine2.UpdateVATOnLines(0, SalesHeader, SalesLine2, TempVATAmountLine);
                UpdatePrepmtLineAmount(SalesHeader);
            end;
        end;

        SalesCalcDiscountByType.ResetRecalculateInvoiceDisc(SalesHeader);
        OnAfterCalcSalesDiscount(SalesHeader);
    end;

### New Publisher Event: ###

[IntegrationEvent(false, false)]
    local procedure OnBeforeCustInvDiscRecExists(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean; var SalesLine2: Record "Sales Line"; var UpdateHeader: Boolean;var InvDiscBase: Decimal; var ChargeBase: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary)
    begin

    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
