### ISSUE TITLE
[Extensibility] Protection level for Direction on 5409 „Prod. Order Routing Line“ 

### ISSUE THREAD

**Issue by DThielmann** [microsoft/ALAppExtensions#6974]
Please set the global option-variable "Direction" on page 5409 "Prod. Order Routing Line" to protected for it's extensibility. 

Otherwise the following error appears and we have no way to access this variable:

![image](https://user-images.githubusercontent.com/61231007/81279872-f7abb000-9057-11ea-8e15-5af738b8ab8f.png)

We've tried it with BC14 CU8 and the current BC16.

There are many more non-protected variables, will there be an big update or something? At the moment, the extensibility if we want to use global-variable in standard-tables or pages is very restricted.

Regards
Dominic

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
