### ISSUE TITLE
[Event Request] OnAfterUpdateEditableOnRow in Pages "Sales Return Order Subform", "Purchase Return Order Subform", "Blanket Sales Order Subform", "Blanket Purchase Order Subform"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#6978]
Please add the trigger OnAfterUpdateEditableOnRow on the pages "Sales Return Order Subform", "Purchase Return Order Subform", "Blanket Sales Order Subform", "Blanket Purchase Order Subform"
. It is already implemented e.g. on pages "Sales Order Subform" and "Purchase Order Subform".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
