### ISSUE TITLE
[Event Request] CU 7171 Function GetItem

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#6979]
Hi,

We would like to extend in CU 7171 function GetItem like:

![image](https://user-images.githubusercontent.com/64962632/81289701-24b38f00-9067-11ea-8e25-3d2a541dfe60.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by MilosPetrovic1** [comment]
`LOCAL [EventSubscriber] C7171_OnBeforeGetItem(VAR SalesLine : Record "Sales Line";VAR Item : Record Item;VAR IsHandled : Boolean;VAR Handler : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
