### ISSUE TITLE
CU 22 function UpdateUnitCost event needed OnAfterUpdateUnitCost

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#6980]
regarding to this topic : https://github.com/microsoft/ALAppExtensions/issues/5363

here are requested parameters, no need for VAR:
![image](https://user-images.githubusercontent.com/53824412/81290282-187c0180-9068-11ea-8be9-ecfbe88a488a.png)

**Comment by StanPesotskiy** [comment]
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
