### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post / CheckAndUpdate: OnBeforeCheckCorrectDocNoMandatory

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#6983]
We need a new event function in Codeunit 90 "Purch.-Post", named OnBeforeCheckCorrectDocNoMandatory:

**LOCAL [IntegrationEvent] OnBeforeCheckCorrectDocNoMandatory(VAR PurchaseHeader : Record "Purchase Header";VAR IsHandled : Boolean)**

called from:

**LOCAL CheckAndUpdate(VAR PurchHeader : Record "Purchase Header")**
....
....
....
IF Invoice THEN
    CheckFAPostingPossibility(PurchHeader);

  CheckPostRestrictions(PurchHeader);

  CheckICDocumentDuplicatePosting(PurchHeader);

**//INIT-INSERT
OnBeforeCheckCorrectDocNoMandatory(PurchHeader,IsHandled);
  IF NOT IsHandled THEN
//END-INSERT**
    IF IsCreditDocType AND Invoice THEN BEGIN
      IF PurchSetup."Correct. Doc. No. Mandatory" THEN
        TESTFIELD("Corrected Invoice No.")
      ELSE BEGIN
....
....
....

Also let me request a change in the code of the same procedure:
....
....
....

IF PurchSetup."Correct. Doc. No. Mandatory" THEN
        TESTFIELD("Corrected Invoice No.")
      ELSE BEGIN
        IF "Corrected Invoice No." = '' THEN
          **//INIT PREVIOUS CODE
          //IF NOT CONFIRM(Text1100000,FALSE) THEN
          //END PREVIOUS CODE**

**//INIT NEW CODE
IF NOT ConfirmManagement.ConfirmProcess(Text1100000,FALSE) THEN
//END NEW CODE**
 ERROR(Text1100011);
      END;
      IF "Corrected Invoice No." <> '' THEN
....
....
....
To apply this code the next local var will be necessary:
Name	                        DataType	    Subtype	Length
ConfirmManagement	Codeunit	    Confirm Management

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
