### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" – New Event “OnBeforeInsertReturnShipmentLine”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#6984]
[Event Request] Codeunit 90 "Purch.-Post" – New Event “OnBeforeInsertReturnShipmentLine”

Could we please have an new publisher “OnBeforeInsertReturnShipmentLine” with Handled Pattern at the very beginning of the procedure InsertReturnShipmentLine in Codeunit 90 "Purch.-Post"?
The publisher should be modelled like the existing publisher "OnBeforeInsertReceiptLine".

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
