### ISSUE TITLE
[Event Request] Codeunit 5704 "TransferOrder-Post Shipment" – New Event “OnBeforeInsertTransShptLine”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#6987]
[Event Request] Codeunit 5704 "TransferOrder-Post Shipment" – New Event “OnBeforeInsertTransShptLine”

Could we please have an new publisher OnBeforeInsertTransShptLine with Handled Pattern?

A suitable example for the desired adaptation is the standard event OnBeforeInsertReceiptLine in Codeunit 90 (Purch.-Post)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
