### ISSUE TITLE
[Enum Request] Field Cross-Reference Type in Table Item Cross Reference

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/ALAppExtensions#6989]
It would be nice if **Cross-Reference Type** in Table **Item Cross Reference** would be a Enum.

**Comment by AlexanderYakunin** [comment]
We only add enums for master branch, and we already have obsoleted Cross reference feature (replaced by Item Reference which can support long 50 char item numbers). Enum Item Reference Type  already part of new feature. Do you still need this change?

**Comment by DanielGoehler** [comment]
Hi @AlexanderYakunin,
if "Item Cross Reference" gets replaced with "Item Reference", then no.
