### ISSUE TITLE
[EventRequest] Codeunit 5870 OnAfterFilterBOMBuffer

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/ALAppExtensions#699]
Hi,

previous issue #420 was closed with a refactor of "GenerateTreeForItemLocal" adding "OnBeforeFilterBOMBuffer" event.

But is not enough: standard procedures "GenerateItemSubTree" and "CalculateTreeType" are LOCAL, so there is no way to call them in custom code.

Please add also this event to control BOMBuffer after its standard creation

`OnAfterFilterBOMBuffer(ParentItem, BOMBuffer, DemandDate, TreeType);  `

Thank you
S.

**Comment by AlexanderYakunin** [comment]
You have [External] GenerateTreeForItems to do that. And event OnAfterFilterBOMBuffer(ParentItem,BOMBuffer,DemandDate,TreeType) already exist.

**Comment by sgiordy** [comment]
Event found in BC 14 RTM OnPrem, thank you.
