### ISSUE TITLE
[Event Request] Codeunit 5705 "TransferOrder-Post Receipt" – New Event “OnBeforeInsertTransRcptLine”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#6990]
[Event Request] Codeunit 5705 "TransferOrder-Post Receipt" – New Event “OnBeforeInsertTransRcptLine”

Could we please have an new publisher OnBeforeInsertTransRcptLine with Handled Pattern?

A suitable example for the desired adaptation is the standard event OnBeforeInsertReceiptLine in Codeunit 90 (Purch.-Post)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by prisma-chku** [comment]
In the bc17 preview version i have already seen the [OnBeforeInsertTransRcptLine] event. However, it has been incorporated there without a handled pattern. Is this still in progress or has it been dropped?

**Comment by StanPesotskiy** [comment]
We will add IsHandled parameter to the existing OnBeforeInsertReceiptLine event.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
