### ISSUE TITLE
[Event Request] Table 5902 OnDelete ServiceLine2OnAfterSetFilters

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#6991]
Hi,

We would like to extend Table 5902 Service Line OnDelete trigger like this:

![image](https://user-images.githubusercontent.com/64962632/81400440-69096280-912d-11ea-80e2-d271e24f2cfe.png)

```
[IntegrationEvent(false, false)]
    local procedure ServiceLine2OnAfterSetFilters(var ServiceLine2: Record "Service Line"; var Rec: Record "Service Line")
    begin
    end;
```

Best regards!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
