### ISSUE TITLE
[Event Request] Table 5901 Service Item No. OnValidate

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#6993]
Hi,

We would like to extend Service Item No. OnValidate Trigger with OnBeforeCheckShipToCode like this:

![image](https://user-images.githubusercontent.com/64962632/81403030-d10e7780-9132-11ea-8148-994e472a065b.png)

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckShipToCode(ServItem: Record "Service Item";ServHeader: Record "Service Header";var ServiceItemLine: Record "Service Item Line";var IsHandled:Boolean)
    begin
    end;
```

Best regards!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
