### ISSUE TITLE
[Event Request] table 5900 field 'Prices Including VAT' onValidate

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#6995]
Hi 
we need to skip ConfirmManagement. Example:
![image](https://user-images.githubusercontent.com/53824412/81405008-1f257a00-9137-11ea-9614-17839b5fc074.png)
Parameters:
Rec,
var HideValidationDialog
var RecalculatePrice
var isHandled

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
