### ISSUE TITLE
Deposit Header No. series is not extensible 

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#6996]
Deposit Header No. Series is extendable.
No. Series code is not following the pattern same as sales/purchase header.

We need the same functions an triggers.

We need the same functions an triggers.

Look for these triggers in Sales Header table
OnAfterGetNoSeriesCode
OnBeforeTestNoSeries
OnAfterInitRecord

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
