### ISSUE TITLE
[Event Request] table 1304 - FilterToActualRecords

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#6997]
Hi,
we need event in following place
![image](https://user-images.githubusercontent.com/53824412/81408521-ac6bcd00-913d-11ea-86d5-2f8f4e9c200e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
