### ISSUE TITLE
[Event Request] table 1304 - SetFiltersOnSalesPrice, SetFiltersOnSalesLineDiscountItem, SetFiltersOnSalesLineDiscountItemGroup

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#6998]
Hi,
we need event in following places 
![image](https://user-images.githubusercontent.com/53824412/81408796-28feab80-913e-11ea-97d1-515ccabb9326.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
