### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnBeforeSalesHeaderModify”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#6999]
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnBeforeSalesHeaderModify”

Could we please have an new publisher OnBeforeSalesHeaderModify with the following parameters:
 - WhseActivHeader
 - SalesHeader
 - ModifyHeader

It would be great if this event existed before the following line in the function "InitSourceDocument":
 - if ModifyHeader then SalesHeader.Modify();

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
