### ISSUE TITLE
[Global+External] CreateSalesInvoiceLines Codeunit 1002

### ISSUE THREAD

**Issue by BartPermentier** [Microsoft/ALAppExtensions#700]
Hey,

could you set the Function CreateSalesInvoiceLines Global and External please? Codeunit 1002.

I need this because in the function CreateSalesInvoice you call for a RunModal which is not possible during report/ job tasks.

Thanks!

**Comment by redIT-LoPf** [comment]
We need that Function also as Global and External. Please move the COMMIT and the MESSAGE code from the function after the calling line.

IF Done THEN BEGIN
  IF (PostingDate = 0D) AND NewInvoice THEN
    ERROR(Text007,SalesHeader.FIELDCAPTION("Posting Date"));
  IF (InvoiceNo = '') AND NOT NewInvoice THEN BEGIN
    IF CrMemo THEN
      ERROR(Text005);
    ERROR(Text004);
  END;
  CreateSalesInvoiceLines(
    JobPlanningLine."Job No.",JobPlanningLine,InvoiceNo,NewInvoice,PostingDate,CrMemo);

  // New Start
  COMMIT;

  IF CrMemo THEN
    MESSAGE(Text008)
  ELSE
    MESSAGE(Text000);
  // New End

**Comment by JesperSchulz** [comment]
@redIT-LoPf, please create a new issue with your request, as we don't revisit closed issues.
