### ISSUE TITLE
[Event Request] Report 202 "Sales Document - Test" - New Event “OnAfterCheckSalesDoc”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7000]
Could we please have a new publisher “OnAfterCheckSalesDoc” at the end of the “OnAfterGetRecord” Trigger of the Dataitem “Sales Header” with a VAR parameter for the global variable “ErrorText”?
This would allow us to add further checks to the report.

…
OnBeforeCheckDimValuePostingHeader("Sales Header", TableID, No);
if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
    AddError(DimMgt.GetDimValuePostingErr);
// >>>>>>>>
OnAfterCheckSalesDoc("Sales Header", ErrorText, ErrorCounter)
// <<<<<<<<
…

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnAfterCheckSalesDoc (SalesHeader: Record "Sales Header"; var ErrorText: array[99] of Text[250]; var ErrorCounter : Integer)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
