### ISSUE TITLE
[Event Request] Report 402 "Purchase Document - Test" - New Event “OnAfterCheckPurchaseDoc

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7002]
Could we please have a new publisher “OnAfterCheckPurchaseDoc” at the end of the “OnAfterGetRecord” Trigger of the Dataitem “Purchase Header” with a VAR parameter for the global variable “ErrorText”?
This would allow us to add further checks to the report.

…
OnBeforeCheckDimValuePostingHeader("Purchase Header", TableID, No);
if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
    AddError(DimMgt.GetDimValuePostingErr);
PricesInclVATtxt := Format("Prices Including VAT");
// >>>>>>>>
OnAfterCheckPurchaseDoc("Purchase Header",ErrorText, ErrorCounter)
// <<<<<<<<
…

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnAfterCheckPurchaseDoc (PurchaseHeader: Record "Purchase Header"; var ErrorText: array[99] of Text[250]; var ErrorCounter: Integer)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
