### ISSUE TITLE
[Event Request] Report 1302 "Standard Sales – Pro Forma Inv" – New Event “OnBeforeGetDocumentCaption”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7003]
Could we please have a new publisher OnBeforeGetDocumentCaption to determine the Document Caption in Report 1302 "Standard Sales – Pro Forma Inv", as it already exists in Report 1306 “Standard Sales – Invoice”?

// >>>>>>>> 
local procedure DocumentCaption(): Text[250]
var
    DocCaption: Text;
begin
    OnBeforeGetDocumentCaption(Header, DocCaption);
    if DocCaption <> '' then
        exit(DocCaption);
    exit(DocumentTitleLbl);
end;
// <<<<<<<<  

// >>>>>>>> 
[IntegrationEvent(false, false)]
local procedure OnBeforeGetDocumentCaption(SalesHeader: Record "Sales Header"; var DocCaption: Text)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
