### ISSUE TITLE
[Event Request] Codeunit 226 "CustEntry-Apply Posted Entries" - New Event “OnAfterCheckReversal”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7005]
Could we please have a new publisher “OnAfterCheckReversal” in the function “CheckReversal” of Codeunit 226 "CustEntry-Apply Posted Entries"?

procedure CheckReversal(CustLedgEntryNo: Integer)
var
    CustLedgEntry: Record "Cust. Ledger Entry";
begin
    CustLedgEntry.Get(CustLedgEntryNo);
    if CustLedgEntry.Reversed then
        Error(CannotUnapplyInReversalErr, CustLedgEntryNo);
    // >>>>>>>>>
    OnAfterCheckReversal(CustLedgEntry);
    // <<<<<<<<<
end;

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnAfterCheckReversal(CustLedgerEntry: Record "Cust. Ledger Entry")
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
