### ISSUE TITLE
[Event Request] Codeunit 227 "VendEntry-Apply Posted Entries" - New Event “OnAfterCheckReversal”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7006]
Could we please have a new publisher “OnAfterCheckReversal” in the function “CheckReversal” of Codeunit 227 "VendEntry-Apply Posted Entries"?

procedure CheckReversal(VendLedgEntryNo: Integer)
var
    VendLedgEntry: Record "Vendor Ledger Entry";
begin
    VendLedgEntry.Get(VendLedgEntryNo);
    if VendLedgEntry.Reversed then
        Error(CannotUnapplyInReversalErr, VendLedgEntryNo);
    // >>>>>>>>>
    OnAfterCheckReversal(VendLedgEntry);
    // <<<<<<<<<

end;
// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnAfterCheckReversal(VendLedgerEntry: Record "Vendor Ledger Entry")
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
