### ISSUE TITLE
[Event Request] Page 344 "Navigate" - New Event “OnAfterNavigateFindExtRecords”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7007]
Could we please have a new publisher “OnAfterNavigateFindExtRecords” at the end of the function “FindExtRecords” of Page 344 "Navigate"?

// >>>>>>>
OnAfterNavigateFindExtRecords(Rec,ContactType,ContactNo,ExtDocNo,FoundRecords);
// <<<<<<<
if not FoundRecords then begin
    SetSource(0D, '', '', 0, '');
    Message(Text001);
end;

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnAfterNavigateFindExtRecords(var DocumentEntry: Record "Document Entry"; ContactType: Enum "Navigate Contact Type"; ContactNo: Code[250]; ExtDocNo: Code[250]; var FoundRecords: Boolean)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
