### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnBeforeSalesLineModify”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7009]
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnBeforeSalesLineModify”

Could we please have an new publisher OnBeforeSalesLineModify with the following parameter:
 - SalesLine

It would be great if this event existed right before the "SalesLine.Modify()" in the function "InitSourceDocument"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
