### ISSUE TITLE
.Net Variable issue from AL?

### ISSUE THREAD

**Issue by TharunMuthu** [Microsoft/ALAppExtensions#701]
Hi,
Can you please help to me how to define .net variable in BC-OnPresmise ?
**DateType:DotNet
SubType:Microsoft.Office.Interop.Excel.ApplicationClass.'Microsoft.Office.Interop.Excel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'**
_Error message :
Tables/ExcelAdd.al(3,14): error AL0451: An assembly named 'Microsoft.Office.Interop.Excel, PublicKeyToken=null' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics 365 Business Central\130\Service\Add-Ins, C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\Microsoft Dynamics NAV\Add-Ins\13.0.26413.0'
Tables/ExcelAdd.al(22,16): error AL0185: DotNet 'xlapp' is missing_

and Is it possible  from BC-Oncloude ? (Because some blogs they mentioned it will  not support for 
BC-Oncloude ! is it true ? if yes than what is alternative option for this !
Thanks !
![capture](https://user-images.githubusercontent.com/44170162/50427666-24d74280-08e9-11e9-8be5-e2eedc28ce1b.JPG)

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
