### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - New Event “OnBeforeLookupAppliesToDocNo”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7011]
Could we please have a new publisher “OnBeforeLookupAppliesToDocNo” with Handled-Pattern in the OnLookup Trigger of Field 53 “Applies-to Doc. No.” for Table 38 “Purchase Header”, exactly as it already exists in Table 36 “Sales Header”?

trigger OnLookup()
var
    GenJnlLine: Record "Gen. Journal Line";
    GenJnlApply: Codeunit "Gen. Jnl.-Apply";
    ApplyCustEntries: Page "Apply Customer Entries";
    IsHandled: Boolean;
Begin
    // >>>>>>>>                    
    IsHandled := false;
    OnBeforeLookupAppliesToDocNo(Rec, VendLedgEntry, IsHandled);
    if IsHandled then
        exit;
    // <<<<<<<<  
    TestField("Bal. Account No.", '');
    …

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnBeforeLookupAppliesToDocNo(var PurchaseHeader: Record "Purchase Header"; VendorLedgEntry: Record "Vendor Ledger Entry"; var IsHandled: Boolean)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
