### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnUpdateSourceDocumentOnAfterGetSalesLine”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7012]
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnUpdateSourceDocumentOnAfterGetSalesLine”

Could we please have an new publisher OnUpdateSourceDocumentOnAfterGetSalesLine in the function "UpdateSourceDocument" with the following parameters:
 - SalesLine
 - TempWhseActivLine

This event would thus be equivalent to the already existing event "OnUpdateSourceDocumentOnAfterGetPurchLine" in the same function

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events along with the fragments of code that could define location of the event call unambiguously. 
The process of implementation will be faster if you put AL code copied from VSCode instead of screenshots.

**Comment by StanPesotskiy** [comment]
Already done for https://github.com/microsoft/ALAppExtensions/issues/6352
