### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnBeforePurchPostRun”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7014]
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnBeforePurchPostRun”

Could we please have an new publisher OnBeforePurchPostRun in the function "PostSourceDocument" with the following parameters:
- WhseActivHeader
- PurchHeader

The event should be called directly before the following line in function "PostSourceDocument":
- PurchPost.Run(PurchHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
