### ISSUE TITLE
[Event Request] Codeunit 7322 "Create Inventory Pick/Movement" – New Event “OnBeforeWhseActivHeaderModify”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7015]
[Event Request] Codeunit 7322 "Create Inventory Pick/Movement" – New Event “OnBeforeWhseActivHeaderModify” in function "Code"

Could we please have an new publisher OnBeforeWhseActivHeaderModify with the following parameters:
- WhseActivHeader
- WhseRequest

It would be great if this event existed before the following line in the function "Code":
- WhseActivHeader.Modify()

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events along with the fragments of code that could define location of the event call unambiguously. 
The process of implementation will be faster if you put AL code copied from VSCode instead of screenshots.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
