### ISSUE TITLE
[Event Request] Table 36 "Sales Header", OnBeforeQtyToShipIsZero

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7018]
[Event Request] Table 36 "Sales Header", OnBeforeQtyToShipIsZero

The procedure QtyToShipIsZero is called from the codeunit which converts blanket sales orders into sales orders. In some instances the quantity in question will need to be calculated in a more elaborate way. We therefore ask for a Handled Pattern.

    procedure QtyToShipIsZero(): Boolean
    var
        HandledQtyToShipIsZero: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeQtyToShipIsZero(Rec, SalesLine, HandledQtyToShipIsZero, IsHandled);
        if IsHandled then
            exit(HandledQtyToShipIsZero);

        SalesLine.Reset();
        SalesLine.SetRange("Document Type", "Document Type");
        SalesLine.SetRange("Document No.", "No.");
        SalesLine.SetFilter("Qty. to Ship", '<>0');
        exit(SalesLine.IsEmpty);
    end;

![image](https://user-images.githubusercontent.com/22153733/81497475-fb8d3b80-92be-11ea-8209-5591566a6b61.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeQtyToShipIsZero(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var HandledQtyToShipIsZero: Boolean; var IsHandled: Boolean)
    begin
    end;

**Integration Event:**
OnBeforeQtyToShipIsZero
**Signature:**
var SalesHeader: Record "Sales Header"
var SalesLine: Record "Sales Line"
var HandledQtyToShipIsZero: Boolean
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
