### ISSUE TITLE
[Event Request] Codeunit 5752 "Get Source Doc. Outbound", OnBeforeCreateFromSalesOrder

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7019]
[Event Request] Codeunit 5752 "Get Source Doc. Outbound", OnBeforeCreateFromSalesOrder

The codeunit has integration events for all sorts of document creation, just not for the creation of sales orders. This would need to be added.

    procedure CreateFromSalesOrder(SalesHeader: Record "Sales Header")
    begin
        OnBeforeCreateFromSalesOrder(SalesHeader);
        ShowResult(CreateFromSalesOrderHideDialog(SalesHeader));
    end;

![image](https://user-images.githubusercontent.com/22153733/81499779-49f60680-92ce-11ea-8740-062423fc98a1.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateFromSalesOrder(var SalesHeader: Record "Sales Header")
    begin
    end;

**Integration Event:**
OnBeforeCreateFromSalesOrder
**Signature:**
var SalesHeader: Record "Sales Header"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
