### ISSUE TITLE
[Function Expose]Request

### ISSUE THREAD

**Issue by kalyankandimalla** [Microsoft/ALAppExtensions#702]
Hi ,

  I saw a request https://github.com/Microsoft/AL/issues/4011 which is still not in recent releases. Can you please let us know when can those functions in #4011 be exposed as external.

Thanks
Kalyan

**Comment by darjoo** [comment]
As commented upon in #703 by Jesper, by default the requests are not backported and it has always been my understanding that these were being backported for the minor releases as seen in my reply in the issue you had referenced.
Currently we're working on backporting this request, others and moving forward. We ask for your understanding in the miscommunication.
As the next minor update window has closed, the earliest I can estimate is the update 23.
