### ISSUE TITLE
[Event Request] Codeunit 5895 Inventory Adjustment OnBeforeInsertValueEntryBuf and OnBeforeInsertCostElementBuffer 

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7021]
We Need two new Event trigger OnBeforeInsertValueEntryBuf and OnBeforeInsertCostElementBuffer in codeunit 5895:

LOCAL CopyCostElementBufToValueEntryBuf(VAR ValueEntryBuf : Record "Value Entry";CostElementBuffer : Record "Cost Element Buffer";ItemLedgEntryNo : Integer)
WITH ValueEntryBuf DO BEGIN
  RESET;
  IF FINDLAST THEN
    EntryNo := "Entry No.";

  INIT;
  "Entry No." := EntryNo + 1;
  "Entry Type" := CostElementBuffer.Type;
  "Variance Type" := CostElementBuffer."Variance Type";
  "Item Ledger Entry No." := ItemLedgEntryNo;
  "Cost Amount (Actual)" := CostElementBuffer."Actual Cost";
  "Cost Amount (Actual) (ACY)" := CostElementBuffer."Actual Cost (ACY)";
  "Cost Amount (Expected)" := CostElementBuffer."Expected Cost";
  "Cost Amount (Expected) (ACY)" := CostElementBuffer."Expected Cost (ACY)";
  "Cost Amount (Non-Invtbl.)" := CostElementBuffer."Rounding Residual";
  "Cost Amount (Non-Invtbl.)(ACY)" := CostElementBuffer."Rounding Residual (ACY)";
  "Invoiced Quantity" := CostElementBuffer."Invoiced Quantity";
  "Valued Quantity" := CostElementBuffer."Remaining Quantity";
  "Expected Cost" := CostElementBuffer."Inbound Completely Invoiced";
  //+++++++++++++++++++++++++++++++++++++++++
  OnBeforeInsertValueEntryBuf(VAR ValueEntryBuf : Record "Value Entry";CostElementBuffer : Record "Cost Element Buffer");
  //-----------------------------------------
  INSERT;
END;

LOCAL CopyValueEntryBufToCostElementBuf(VAR CostElementBuffer : Record "Cost Element Buffer";ValueEntryBuf : Record "Value Entry")
WITH CostElementBuffer DO BEGIN
  INIT;
  Type := ValueEntryBuf."Entry Type";
  "Variance Type" := ValueEntryBuf."Variance Type";
  "Actual Cost" := ValueEntryBuf."Cost Amount (Actual)";
  "Actual Cost (ACY)" := ValueEntryBuf."Cost Amount (Actual) (ACY)";
  "Expected Cost" := ValueEntryBuf."Cost Amount (Expected)";
  "Expected Cost (ACY)" := ValueEntryBuf."Cost Amount (Expected) (ACY)";
  "Rounding Residual" := ValueEntryBuf."Cost Amount (Non-Invtbl.)";
  "Rounding Residual (ACY)" := ValueEntryBuf."Cost Amount (Non-Invtbl.)(ACY)";
  "Invoiced Quantity" := ValueEntryBuf."Invoiced Quantity";
  "Remaining Quantity" := ValueEntryBuf."Valued Quantity";
  "Inbound Completely Invoiced" := ValueEntryBuf."Expected Cost";
  //+++++++++++++++++++++++++++++++++++++++++
  OnBeforeInsertCostElementBuffer(VAR CostElementBuffer : Record "Cost Element Buffer";ValueEntryBuf : Record "Value Entry");
  //-----------------------------------------
  INSERT;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
