### ISSUE TITLE
[Event Request] Codeunit 5895 "Inventory Adjustment" OnAfterGetOrigValueEntry

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7022]
We Need a new Event trigger OnAfterGetOrigValueEntry in codeunit 5895:

LOCAL GetOrigValueEntry(VAR OrigValueEntry : Record "Value Entry";ValueEntry : Record "Value Entry";ValueEntryType : Option)
WITH OrigValueEntry DO BEGIN
  SETCURRENTKEY("Item Ledger Entry No.","Document No.");
  SETRANGE("Item Ledger Entry No.",ValueEntry."Item Ledger Entry No.");
  SETRANGE("Document No.",ValueEntry."Document No.");

  IF FINDSET THEN
    REPEAT
      IF ("Expected Cost" = ValueEntry."Expected Cost") AND
         ("Entry Type" = ValueEntryType)
      THEN BEGIN
        Found := TRUE;
        "Valued Quantity" := ValueEntry."Valued Quantity";
        "Invoiced Quantity" := ValueEntry."Invoiced Quantity";
        //+++++++++++++++++++++++++++++++++++++++++++++++
        OnAfterGetOrigValueEntry(VAR OrigValueEntry : Record "Value Entry";ValueEntry : Record "Value Entry");
        //-----------------------------------------------
      END ELSE
        IsLastEntry := NEXT = 0;
    UNTIL Found OR IsLastEntry;

  IF NOT Found THEN BEGIN
    OrigValueEntry := ValueEntry;
    "Entry Type" := ValueEntryType;
    IF ValueEntryType = "Entry Type"::Variance THEN
      "Variance Type" := GetOrigVarianceType(ValueEntry);
  END;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
