### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnAfterPostInventoryToGL

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#7024]
Please add a new publisher event to the function PostInventoryToGL as follows:
	
```
LOCAL PostInventoryToGL(VAR ValueEntry : Record "Value Entry")
.
.
      SetValueEntry(ValueEntry,0,0,FALSE);
    END;
END;

//>> Start New Publisher Call
OnAfterPostInventoryToGL(ValueEntry);
//<< End New Publisher Call
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnAfterPostInventoryToGL(VAR ValueEntry : Record "Value Entry")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
