### ISSUE TITLE
[Event Request] codeunit 5988 Serv-Documents Mgt. - PostDocumentLines - OnBeforeServiceRoundAmmount

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7025]
Hi,

We would like to extend Serv-Document Mgt. PostDocumentLines procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81544193-7580fb80-9377-11ea-8b70-fef7c07e2d73.png)

``` al
[IntegrationEvent(false, false)]
     local procedure OnBeforeServiceRoundAmmount(var ServLine: Record "Service Line")
     begin
     end;
```

Best Regards!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
