### ISSUE TITLE
[Event Request] Table 1173 "Document Attachment", OnBeforeExportAttachment

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/ALAppExtensions#7026]
We are working on integration with Azure Storage. Our solution will store all attachments in Azure instead in local database, in local database will be stored only URL from the Azure file. 

When new record is inserted in "Document Attachment" table, file is sent to the Azure and URL is stored in "Document Reference ID" field. We are having issue with code from on OnDrillDown() trigger on "File Name" field from "Document Attachment Details" page.

![1](https://user-images.githubusercontent.com/31925856/81558424-ec28f380-938d-11ea-832e-863ad647560c.png)

We need to be able to download file content from Azure before file is downloaded for user.

![2](https://user-images.githubusercontent.com/31925856/81558447-f945e280-938d-11ea-8cd1-518bb8a115c9.png)

![3](https://user-images.githubusercontent.com/31925856/81558488-0e227600-938e-11ea-80f2-b5615a6b088a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
