### ISSUE TITLE
The type or method 'SetValueFilter' cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#7033]
In table **"Item Attribute Value"**, function **SetValueFilter** is set to Scope('OnPrem'), which seems to be a mistake. Could you please enable it for extension development?

See also https://github.com/microsoft/AL/issues/4953

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
