### ISSUE TITLE
[Event Request] COD5761 - Add IsHandled for OnAfterConfirmPost-Event

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#7037]
Hello,

we need a VAR IsHandled-parameter for the OnAfterConfirmPost to skip the Posting.

![image](https://user-images.githubusercontent.com/45033081/81583347-88182680-93b1-11ea-8f3b-e2e3dd64ddfb.png)

Best regards,
Sebastian

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
