### ISSUE TITLE
[Event Request] Codeunit 5985 Serv-Item Tracking Rsrv. Mgt. - TransferReservToItemJnlLine

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7039]
Hi,

We would like to extend CU Serv-Item Tracking Rsrv. Mgt. TransferReservToItemJnlLine procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81651093-bb4eca00-9432-11ea-9cef-9731ed84f4b6.png)

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservToItemJnlLine(var ServiceLine: Record "Service Line"; var ItemJnlLine: Record "Item Journal Line"; var QtyToBeShippedBase: Decimal; var CheckApplFromItemEntry: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
