### ISSUE TITLE
[Function Expose]Request: Codeunit 414

### ISSUE THREAD

**Issue by kalyankandimalla** [Microsoft/ALAppExtensions#704]
Hi ,
Regarding request #264 . For codeunit 414 please expose function 'PerformManualCheckAndRelease' as external. We cannot make use of function 'PerformManualRelease' (which is already exposed as External) in place of this function.

Thanks
Kalyan

**Comment by IhorHandziuk** [comment]
Thank you for your request. You can expect this function to be external in future update.
