### ISSUE TITLE
[Event Request] Codeunit 5063 "ArchiveManagement" – New Event “OnBeforeStorePurchDocument”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7041]
Could we please have a new publisher “OnBeforeStorePurchDocument” in Function “StorePurchDocument”, Codeunit 5063 "ArchiveManagement"?

    procedure StorePurchDocument(var PurchHeader: Record "Purchase Header"; InteractionExist: Boolean)
    var
        PurchLine: Record "Purchase Line";
        PurchHeaderArchive: Record "Purchase Header Archive";
        PurchLineArchive: Record "Purchase Line Archive";
    Begin
*** Start new code ***
        OnBeforeStorePurchDocument(PurchHeader);
*** Stop new code ***
        PurchHeaderArchive.Init();

*** Start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnBeforeStorePurchDocument(var PurchHeader: Record "Purchase Header")
    begin
    end;
*** Stop new code ***

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
