### ISSUE TITLE
[Event Request] Codeunit 5343 "CRM Sales Order to Sales Order" – Modify Event “ClearLastBackOfficeSubmitOnSalesHeaderDelete”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7042]
Could we please have the already existing subscriber “ClearLastBackOfficeSubmitOnSalesHeaderDelete” in Codeunit 5343 "CRM Sales Order to Sales Order" be extended?
The subscriber should check record to be not temporary.

[EventSubscriber] ClearLastBackOfficeSubmitOnSalesHeaderDelete(VAR Rec : Record "Sales Header";RunTrigger : Boolean)
*** Start new code ***
IF Rec.ISTEMPORARY THEN BEGIN
  EXIT;
END;
*** Stop new code ***

IF CRMIntegrationManagement.IsCRMIntegrationEnabled THEN
  IF CRMIntegrationRecord.FindIDFromRecordID(Rec.RECORDID,CRMSalesorder.SalesOrderId) THEN BEGIN

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
