### ISSUE TITLE
[Event Request] Codeunit 5403 "AddOnIntegrManagement" – New Event “OnBeforeAssignOverheadRate”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7043]
Could we please have a new publisher “OnBeforeAssignOverheadRate” in Function “TransferFromReqLineToPurchLine”, Codeunit 5403 "AddOnIntegrManagement"?

[External] TransferFromReqLineToPurchLine(VAR PurchOrderLine : Record "Purchase Line";ReqLine : Record "Requisition Line")
WITH ReqLine DO BEGIN
  PurchOrderLine."Routing No." := "Routing No.";
  PurchOrderLine."Routing Reference No." := "Routing Reference No.";
  PurchOrderLine."Operation No." := "Operation No.";
  PurchOrderLine.VALIDATE("Work Center No.","Work Center No.");
  IF "Prod. Order No." <> '' THEN
    IF "Work Center No." <> '' THEN BEGIN
      WorkCenter.GET(PurchOrderLine."Work Center No.");
*** Start new code ***
      OnBeforeAssignOverheadRate(WorkCenter,ReqLine.“Order Date“);
*** Stop new code ***
      IF WorkCenter."Unit Cost Calculation" = WorkCenter."Unit Cost Calculation"::Time THEN BEGIN
        ProdOrderRtngLine.GET(

*** Start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignOverheadRate(var WordCenter: Record "Work Center”; var OrderDate: date)
    begin
    end;
*** Stop new code ***

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
