### ISSUE TITLE
[Event Request] Codeunit 5982 Service-Post+Print - PostDocument

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7045]
Hi,

We would like to extend Service-Post+Print  PostDocument procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81658524-24394080-9439-11ea-82a4-b3e6c00a7934.png)

```
[IntegrationEvent(false, false)]
    local procedure OnBeforePostPrintServiceDoc(var ServiceHeader: Record "Service Header")
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
