### ISSUE TITLE
[Event Request] Codeunit 5981 Service-Post (Yes/No) - PreviewDocument - OnBeforePreviewDocument

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7047]
Hi,

We would like to extend Codeunint Service-Post (Yes/No) Preview Document procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81665760-66ff1680-9441-11ea-85d8-4fc7f1287c29.png)

``` al
[IntegrationEvent(false, false)]
    local procedure OnBeforePreviewDocument(var ServHeader: Record "Service Header"; IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
