### ISSUE TITLE
Event Request: Codeunit 90, Purch.-Post

### ISSUE THREAD

**Issue by Roberto-cyber** [microsoft/ALAppExtensions#7049]
We need the Event "OnBeforeCheckExternalDocNoOnUpdtPostingNo" in Codeunit 90, function "UpdatePostingNos"
...
THEN BEGIN
      IF PurchSetup."Ext. Doc. No. Mandatory" OR (GenJnlLineExtDocNo <> '') THEN BEGIN
        VendLedgEntry.RESET;
        VendLedgEntry.SETCURRENTKEY("External Document No.");
        IF ("Document Type" = "Document Type"::Invoice) OR ("Document Type" = "Document Type"::Order) THEN BEGIN
          TESTFIELD("Vendor Invoice No.");
          VendLedgEntry.SETRANGE("Document Type","Document Type"::Invoice);
          VendLedgEntry.SETRANGE("External Document No.","Vendor Invoice No.");
        END ELSE
          IF ("Document Type" = "Document Type"::"Credit Memo") OR ("Document Type" = "Document Type"::"Return Order") THEN BEGIN
            TESTFIELD("Vendor Cr. Memo No.");
            VendLedgEntry.SETRANGE("Document Type","Document Type"::"Credit Memo");
            VendLedgEntry.SETRANGE("External Document No.","Vendor Cr. Memo No.");
          END;
        VendLedgEntry.SETRANGE("Vendor No.","Pay-to Vendor No.");
        **OnBeforeCheckExternalDocNoOnUpdtPostingNo(VendLedgEntry,"Posting Date");** 
        IF VendLedgEntry.FINDFIRST THEN
          ERROR(PurchaseAlreadyExistsErr,VendLedgEntry."Document Type",GenJnlLineExtDocNo);
      END;
...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
