### ISSUE TITLE
[Event Request] CU12 function CalcPmtDiscIfAdjVAT

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#7050]
Hi,
we would like to to have an event in CU 12 function CalcPmtDiscIfAdjVAT before system do CalcPmtDiscVATAmounts. It would look like:

![image](https://user-images.githubusercontent.com/53824412/81669549-aa0fb880-9446-11ea-9a10-baf2deee1160.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by VladimirVeljovic** [comment]
Ok, sorry i usually do but i was in hurry. Will do in the future.

**Comment by StanPesotskiy** [comment]
Without the exact signature in the request you risk to get not what you wanted, so you will wait more until the requested event, as you imagined it, would be implemented.

**Comment by VladimirVeljovic** [comment]
OnBeforeCalcPmtDiscVATAmounts(VATEntry2, DtldCVLedgEntryBuf2, GenJnlLine);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcPmtDiscVATAmounts(var VATEntry2:: Record "VAT Entry"; var DtldCVLedgEntryBuf2: Record "Detailed CV Ledg. Entry Buffer"; var GenJnlLine: Record "Gen. Journal Line");
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
