### ISSUE TITLE
[Event Request] codeunit 5944 SignServContractDoc - CopyServComments - OnBeforeInsertCopyServCommentLine

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7052]
Hi,

We would like to extend Codeunit SignServContractDoc  CopyServComments  procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81672896-1e4c5b00-944b-11ea-8b1e-f40411154f14.png)

``` al
[IntegrationEvent(false, false)]
    local procedure OnBeforeInsertCopyServCommentLine(var FromServCommentLine: Record "Service Comment Line"; var ToServCommentLine: Record "Service Comment Line";)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
