### ISSUE TITLE
[Event Request] Codeunit 333 - ProcessReqLineActions / OnBeforeProcessReqLineActions

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#7053]
Hi,
Can you extend event OnBeforeProcessReqLineActions with global parameter PlanningResiliency so it will look like this:

OnBeforeProcessReqLineActions(ReqLine, SuppressCommit, **PlanningResiliency**);

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeProcessReqLineActions(var RequisitionLine: Record "Requisition Line"; CommitIsSuppressed: Boolean; PlanningResiliency: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
