### ISSUE TITLE
[Event Request] CU13 function UpdateAndDeleteLines

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#7054]
Hi,
we need on CU13 function UpdateAndDeleteLines function for modifyin some fields.

![image](https://user-images.githubusercontent.com/53824412/81676756-98331300-9450-11ea-9fe8-dac148fd62a9.png)

GenJnlLine2 should be VAR

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by VladimirVeljovic** [comment]
OnBeforeModifyRecurringJournal(GenJnlLine2);
    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyRecurringJournal(var GenJnlLine2: Record "Gen. Journal Line");
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
