### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - CreateDetailedServLine - OnAfterSetFirstLineAndNewContract

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7055]
Hi,

We would like to extend Codeunit ServContractManagement  CreateDetailedServLine  procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81682018-e1856180-9454-11ea-8ec2-e4cf05dc9822.png)

```
[IntegrationEvent(false, false)]
    local procedure OnAfterSetFirstLineAndNewContract(var FirstLine: Boolean; var NewContract: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
