### ISSUE TITLE
[Event Request] Codeunit 5708 - trigger OnRun

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#7056]
Hi!

We need an additional event before the transfer-from code & transfer-to code are compared in the OnRun trigger in the Release Transfer Document codeunit. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/81693586-6b86f780-9460-11ea-9ae6-5bda254b8515.png)

![image](https://user-images.githubusercontent.com/55734714/81693477-41cdd080-9460-11ea-8d66-d059e2d3d777.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
