### ISSUE TITLE
[Event Request] Table 5740 - procedure CheckBeforePost

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#7057]
Hi!

We need an additional event before the transfer-from code & transfer-to code are compared in the CheckBeforePost procedure on the Transfer Header table. We need the IsHandled pattern to be included.
![image](https://user-images.githubusercontent.com/55734714/81694027-1992a180-9461-11ea-9d1b-94fbe1563a2f.png)

![image](https://user-images.githubusercontent.com/55734714/81694057-244d3680-9461-11ea-8317-9d27b6cf6898.png)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
