### ISSUE TITLE
[Event Request] Codeunit 57 Handled Publishers needed

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#7059]
Following Publishers are desired in the Codeunit 57:

Start of the function CalculateSalesSubPageTotals:
`OnBeforeCalculateSalesSubPageTotals(TotalSalesHeader,TotalSalesLine,VATAmount,InvoiceDiscountAmount,InvoiceDiscountPct,IsHandled);
if IsHandled then
  exit;`
`OnBeforeCalculateSalesSubPageTotals(var TotalSalesHeader: Record "Sales Header"; var TotalSalesLine: Record "Sales Line"; var VATAmount: Decimal; var InvoiceDiscountAmount: Decimal; var InvoiceDiscountPct: Decimal; var IsHandled: Boolean)`

Start of the function CalculatePostedSalesInvoiceTotals:
`OnBeforeCalculateSalesSubPageTotals(SalesInvoiceHeader,VATAmount,SalesInvoiceLine,IsHandled);
if IsHandled then
  exit;`
`OnBeforeCalculatePostedSalesInvoiceTotals(var SalesInvoiceHeader: Record "Sales Invoice Header"; var VATAmount: Decimal; SalesInvoiceLine: Record "Sales Invoice Line"; var IsHandled: Boolean)`

Start of the function CalculatePostedSalesCreditMemoTotals:
`OnBeforeCalculatePostedSalesCreditMemoTotals(SalesCrMemoHeader,VATAmount,SalesCrMemoLine,IsHandled);
if IsHandled then
  exit;`
`OnBeforeCalculatePostedSalesCreditMemoTotals(var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var VATAmount: Decimal; SalesCrMemoLine: Record "Sales Cr.Memo Line"; var IsHandled: Boolean)`

Start of the function SalesUpdateTotalsControls:
`OnBeforeSalesUpdateTotalsControls(CurrentSalesLine,TotalSalesHeader,TotalsSalesLine,RefreshMessageEnabled,ControlStyle,RefreshMessageText,InvDiscAmountEditable,CurrPageEditable,VATAmount,IsHandled);
if IsHandled then
  exit;`
`OnBeforeSalesUpdateTotalsControls(CurrentSalesLine: Record "Sales Line"; var TotalSalesHeader: Record "Sales Header"; var TotalsSalesLine: Record "Sales Line"; var RefreshMessageEnabled: Boolean; var ControlStyle: Text; var RefreshMessageText: Text; var InvDiscAmountEditable: Boolean; CurrPageEditable: Boolean; var VATAmount: Decimal; var IsHandled: Boolean)`

Start of the function SalesRedistributeInvoiceDiscountAmounts:
`OnBeforeSalesRedistributeInvoiceDiscountAmounts(TempSalesLine,VATAmount,TempTotalSalesLine,IsHandled);
if IsHandled then
  exit;`
`OnBeforeSalesRedistributeInvoiceDiscountAmounts(var TempSalesLine: Record "Sales Line" temporary; var VATAmount: Decimal; var TempTotalSalesLine: Record "Sales Line" temporary; var IsHandled: Boolean)`

Start of the function PurchaseUpdateTotalsControls:
`OnBeforePurchaseUpdateTotalsControls(CurrentPurchaseLine,TotalPurchaseHeader,TotalsPurchaseLine,RefreshMessageEnabled,ControlStyle,RefreshMessageText,InvDiscAmountEditable,VATAmount,IsHandled);
if IsHandled then
  exit;`
`OnBeforePurchaseUpdateTotalsControls(CurrentPurchaseLine: Record "Purchase Line"; var TotalPurchaseHeader: Record "Purchase Header"; var TotalsPurchaseLine: Record "Purchase Line"; var RefreshMessageEnabled: Boolean; var ControlStyle: Text; var RefreshMessageText: Text; var InvDiscAmountEditable: Boolean; var VATAmount: Decimal; var IsHandled: Boolean)`

Start of the function PurchaseRedistributeInvoiceDiscountAmounts:
`OnBeforePurchaseRedistributeInvoiceDiscountAmounts(TempPurchaseLine,VATAmount,TempTotalPurchaseLine,IsHandled);
if IsHandled then
  exit;`
`OnBeforePurchaseRedistributeInvoiceDiscountAmounts(var TempPurchaseLine: Record "Purchase Line" temporary; var VATAmount: Decimal; var TempTotalPurchaseLine: Record "Purchase Line" temporary; var IsHandled: Boolean)`

Start of the function CalculatePurchaseSubPageTotals:
`OnBeforeCalculatePurchaseSubPageTotals(TotalPurchaseHeader,TotalPurchaseLine,VATAmount,InvoiceDiscountAmount,InvoiceDiscountPct,IsHandled);
if IsHandled then
  exit;`
`OnBeforeCalculatePurchaseSubPageTotals(var TotalPurchaseHeader: Record "Purchase Header"; var TotalPurchaseLine: Record "Purchase Line"; var VATAmount: Decimal; var InvoiceDiscountAmount: Decimal; var InvoiceDiscountPct: Decimal; var IsHandled: Boolean)`

Start of the function CalculatePostedPurchInvoiceTotals:
`OnBeforeCalculatePostedPurchInvoiceTotals(PurchInvHeader,VATAmount,PurchInvLine,IsHandled);
if IsHandled then
  exit;`
`OnBeforeCalculatePostedPurchInvoiceTotals(var PurchInvHeader: Record "Purch. Inv. Header"; var VATAmount: Decimal; PurchInvLine: Record "Purch. Inv. Line"; var IsHandled: Boolean)`

Start of the function CalculatePostedPurchCreditMemoTotals:
`OnBeforeCalculatePostedPurchCreditMemoTotals(PurchCrMemoHdr,VATAmount,PurchCrMemoLine,IsHandled);
if IsHandled then
  exit;`
`OnBeforeCalculatePostedPurchCreditMemoTotals(var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; var VATAmount: Decimal; PurchCrMemoLine: Record "Purch. Cr. Memo Line"; var IsHandled: Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
