### ISSUE TITLE
[Event Request] Page 99000883 Sales Order Planning - MakeLines

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#7062]
New Publisher needed in function MakeLines

                CalculateDisposalPlan(SalesLine."Variant Code", SalesLine."Location Code");
**==> NEW
OnBeforeInsertSalesOrderPlanningLine(Rec, SalesLine);
<== NEW**
                Insert();
            until SalesLine.Next() = 0;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
