### ISSUE TITLE
[Event Request] Table 36 Sales Header - OnBeforeInitFromSalesHeader

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#7064]
Requesting a new Event Publisher on Table 36 Sales Header

Event
`OnBeforeInitFromSalesHeader(VAR SalesHeader : Record "Sales Header",SourceSalesHeader : Record "Sales Header")`

**Code**
## [External] InitFromSalesHeader(SourceSalesHeader : Record "Sales Header")
**>>> New Code**
```
OnBeforeInitFromSalesHeader(Rec,SourceSalesHeader);
```
**<<< New Code End**
```
"Document Date" := SourceSalesHeader."Document Date";
"Shipment Date" := SourceSalesHeader."Shipment Date";

"Shortcut Dimension 1 Code" := SourceSalesHeader."Shortcut Dimension 1 Code";
"Shortcut Dimension 2 Code" := SourceSalesHeader."Shortcut Dimension 2 Code";
"Dimension Set ID" := SourceSalesHeader."Dimension Set ID";

"Location Code" := SourceSalesHeader."Location Code";
SetShipToAddress(
  SourceSalesHeader."Ship-to Name",SourceSalesHeader."Ship-to Name 2",SourceSalesHeader."Ship-to Address",
  SourceSalesHeader."Ship-to Address 2",SourceSalesHeader."Ship-to City",SourceSalesHeader."Ship-to Post Code",
  SourceSalesHeader."Ship-to County",SourceSalesHeader."Ship-to Country/Region Code");
"Ship-to Contact" := SourceSalesHeader."Ship-to Contact";

OnAfterInitFromSalesHeader(Rec,SourceSalesHeader);
```

In Our Solution we have a Dimension that is related to the Order (Order DImension). We need to be able to overwrite the dimension 1 or 2 (Based on setup) to the already defined Order DImension. In a subscriber based on the requested publisher we save the specific order dimension and in the already available Publisher OnAfterInitFromSalesHeader we can put it back on the SalesHeader. Can you please add the requested Publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
