### ISSUE TITLE
[Event Request] Codeunit 97 "Blanket Purch. Order to Order"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7066]
please implement the same trigger PurchOrderLineValidateQuantity with OnBeforePurchOrderLineValidateQuantity in codeunit 97. This Routine has just been implemented with 16.1 in codeunit 87 "Blanket Sales Order to Order":

OnRun:
...
      PurchOrderLine := PurchBlanketOrderLine;
      ResetQuantityFields(PurchOrderLine);
      PurchOrderLine."Document Type" := PurchOrderHeader."Document Type";
      PurchOrderLine."Document No." := PurchOrderHeader."No.";
      PurchOrderLine."Blanket Order No." := "No.";
      PurchOrderLine."Blanket Order Line No." := PurchBlanketOrderLine."Line No.";

      IF (PurchOrderLine."No." <> '') AND (PurchOrderLine.Type <> 0)THEN BEGIN
        PurchOrderLine.Amount := 0;
        PurchOrderLine."Amount Including VAT" := 0;
        PurchOrderLineValidateQuantity(PurchOrderLine ; BlanketOrderPurchLine)

LOCAL PurchOrderLineValidateQuantity(VAR PurchOrderLine : Record "Purchase Line";BlanketOrderPurchLine : Record "Purchase Line")
IsHandled := FALSE;
OnBeforePurchOrderLineValidateQuantity(PurchOrderLine, BlanketOrderPurchLine, IsHandled);
IF IsHandled THEN
    EXIT;

PurchOrderLine.VALIDATE(Quantity, BlanketOrderPurchLine."Qty. to Receive");

LOCAL [IntegrationEvent] OnBeforePurchOrderLineValidateQuantity(VAR PurchOrderLine : Record "Purchase Line";BlanketOrderPurchLine : Record "Purchase Line";VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
