### ISSUE TITLE
[Event Request] Codeunit 6620 OnSplitPstdPurchLinesPerILETransferFields

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7068]
Please add a new Event trigger OnSplitPstdPurchLinesPerILETransferFields in codeunit 6620 in procedure SplitPstdPurchLinesPerILETransferFields. This similar Event is already implemented in OnSplitPstdSalesLinesPerILETransferFields:

LOCAL SplitPstdPurchLinesPerILE(ToPurchHeader : Record "Purchase Header";FromPurchHeader : Record "Purchase Header";VAR ItemLedgEntry : Record "Item Ledger Entry";VAR FromPurchLineBuf : Record "Purchase Line";FromPurchLine : Record "Purchase Line";VAR
…
…
      IF NOT FromShptOrRcpt THEN
        UpdateRevPurchLineAmount(
          FromPurchLineBuf,OrgQtyBase,
          FromPurchHeader."Prices Including VAT",ToPurchHeader."Prices Including VAT");
      IF FromPurchLineBuf.Quantity <> 0 THEN BEGIN
        //++++++++++++++++++++++++++++++++++++++++++
        OnSplitPstdPurchLinesPerILETransferFields(VAR FromPurchHeader,VAR FromPurchLine,VAR FromPurchLineBuf,VAR ToPurchHeader);
        //------------------------------------------
        FromPurchLineBuf.INSERT;
        AddPurchDocLine(TempDocPurchaseLine,FromPurchLineBuf."Line No.","Document No.",FromPurchLineBuf."Line No.");
      END ELSE
        SkippedLine := TRUE;
    END ELSE
      IF "Remaining Quantity" = 0 THEN
        SkippedLine := TRUE;
  UNTIL (NEXT = 0) OR (FromPurchLine."Quantity (Base)" = 0);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
