### ISSUE TITLE
[Event Request] Codeunit 6620 OnBeforeModifyToAssemblyLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7069]
Please add anew Event OnBeforeModifyToAssemblyLine in codeunit 6620 in procedure CreateToAsmLines:

LOCAL CreateToAsmLines(ToAsmHeader : Record "Assembly Header";VAR FromAsmLine : Record "Assembly Line";VAR ToAssemblyLine : Record "Assembly Line";ToSalesLine : Record "Sales Line";BasicAsmOrderCopy : Boolean;AvailabilityCheck : Boolean)
IF FromAsmLine.FINDSET THEN
  REPEAT
    ToAssemblyLine.INIT;
    ToAssemblyLine."Document Type" := ToAsmHeader."Document Type";
    ToAssemblyLine."Document No." := ToAsmHeader."No.";
    ToAssemblyLine."Line No." := AssemblyLineMgt.GetNextAsmLineNo(ToAssemblyLine,AvailabilityCheck);
    ToAssemblyLine.INSERT(NOT AvailabilityCheck);
…
…
    END;
    CopyFromAsmOrderDimToLine(ToAssemblyLine,FromAsmLine,BasicAsmOrderCopy);
    //++++++++++++++++++++++++++++++++++++++++
    OnBeforeModifyToAssemblyLine(ToAsmHeader, VAR ToAssemblyLine,FromAsmLine,ToSalesLine, BasicAsmOrderCopy,AvailabilityCheck);
    //----------------------------------------
    ToAssemblyLine.MODIFY(NOT AvailabilityCheck);
  UNTIL FromAsmLine.NEXT = 0;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
