### ISSUE TITLE
[Function Expose] Table 5766 - SetActivityFilter

### ISSUE THREAD

**Issue by makuhn** [Microsoft/ALAppExtensions#707]
Change visibility of function **SetActivityFilter** of Table 5766 to External:
```
-    LOCAL PROCEDURE SetActivityFilter@18(VAR WhseActivLineFrom@1000 : Record 5767;VAR WhseActivLineTo@1001 : Record 5767);
+    [External]
+    PROCEDURE SetActivityFilter@18(VAR WhseActivLineFrom@1000 : Record 5767;VAR WhseActivLineTo@1001 : Record 5767);
```

**Comment by darjoo** [comment]
Hi makuhn, we've decided to go ahead with your request. We usually include these types of changes in the next minor release, so look for it there. The development preview will include the change in a day or two.
