### ISSUE TITLE
[Event Request] Codeunit 6620 OnBeforeTempTrackingSpecification

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7070]
Please add a new Event trigger OnBeforeTempTrackingSpecification in codeunit 6620:

LOCAL SetTrackingOnAssemblyReservation(AssemblyHeader : Record "Assembly Header";VAR TempItemLedgerEntry : TEMPORARY Record "Item Ledger Entry")
TempItemLedgerEntry.SETFILTER("Lot No.",'<>%1','');
IF TempItemLedgerEntry.ISEMPTY THEN
  EXIT;

ReservationEntry.SETRANGE("Source Type",DATABASE::"Assembly Header");
ReservationEntry.SETRANGE("Source Subtype",AssemblyHeader."Document Type");
ReservationEntry.SETRANGE("Source ID",AssemblyHeader."No.");
ReservationEntry.SETRANGE("Source Ref. No.",0);
ReservationEntry.SETRANGE("Reservation Status",ReservationEntry."Reservation Status"::Reservation);
IF ReservationEntry.FINDSET THEN
  REPEAT
    TempReservationEntry := ReservationEntry;
    TempReservationEntry.INSERT;
  UNTIL ReservationEntry.NEXT = 0;

IF TempItemLedgerEntry.FINDSET THEN
  REPEAT
    TempTrackingSpecification."Entry No." += 1;
    TempTrackingSpecification."Item No." := TempItemLedgerEntry."Item No.";
    TempTrackingSpecification."Location Code" := TempItemLedgerEntry."Location Code";
    TempTrackingSpecification."Quantity (Base)" := TempItemLedgerEntry.Quantity;
    TempTrackingSpecification."Serial No." := TempItemLedgerEntry."Serial No.";
    TempTrackingSpecification."Lot No." := TempItemLedgerEntry."Lot No.";
    TempTrackingSpecification."Warranty Date" := TempItemLedgerEntry."Warranty Date";
    TempTrackingSpecification."Expiration Date" := TempItemLedgerEntry."Expiration Date";
    //++++++++++++++++++++++++++++++++++++++++++
    OnBeforeTempTrackingSpecification(VAR TempTrackingSpecification,TempItemLedgerEntry);
    //------------------------------------------
    TempTrackingSpecification.INSERT;
  UNTIL TempItemLedgerEntry.NEXT = 0;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
