### ISSUE TITLE
[Event Request] Codeunit 5932 Service-Get Shipment - CreateInvLines - OnAfterTransferLine

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7071]
Hi.

We would like to extend Codeunit Service-Get Shipment CreateInvLines procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81791955-af810780-9507-11ea-9bf3-6b248edb633c.png)

```
[IntegrationEvent(false, false)]
    local procedure OnAfterTransferLine(var ServiceShptLine: Record "Service Shipment Line"; var ServiceShptLine2: Record "Service Shipment Line"; var ServiceShptHeader: Record "Service Shipment Header"; var ServiceLine: Record "Service Line"; var ServiceHeader: Record "Service Header")
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
