### ISSUE TITLE
[Event Request] Codeunit 5923 Service-Quote to Order - InsertServHeader - OnBeforeInsertServHeader

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7072]
Hi.

We would like to extend Codeunit Service-Quote to Order InsertServHeader procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81793437-a7c26280-9509-11ea-9ef3-c5b5685e986f.png)

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeInsertServHeader(var ServiceHeaderOrder: Record "Service Header"; ServiceHeaderQuote: Record "Service Header")
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
