### ISSUE TITLE
[Event Request] Codeunit 99000830 OnTransferReservEntryOnBeforeNewReservEntryModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7073]
We Need the new Event trigger OnTransferReservEntryOnBeforeNewReservEntryModify from 16.1 in codeunit 99000830 also in the other case the If sign has not swapped due to negative Posting:

[External] TransferReservEntry(NewType : Option;NewSubtype : Integer;NewID : Code[20];NewBatchName : Code[10];NewProdOrderLine : Integer;NewRefNo : Integer;QtyPerUOM : Decimal;OldReservEntry : Record "Reservation Entry";TransferQty : Decimal) : DecimalÄ
IF TransferQty = 0 THEN
  EXIT;
…
…
            if not ReservEntry.Get(NewReservEntry."Entry No.", NewReservEntry.Positive) then begin
                // Means that only one record exists = surplus or prospect
                NewReservEntry.Insert();
                OnTransferReservEntryOnAfterNewReservEntryInsert(NewReservEntry);
                // Delete the original record:
                NewReservEntry.Positive := not NewReservEntry.Positive;
                NewReservEntry.Delete();
            end else begin // A set of records exist = reservation or tracking
                OnTransferReservEntryOnBeforeNewReservEntryModify(NewReservEntry, false);
                NewReservEntry.Modify();
                // Get the original record and modify quantity:
                NewReservEntry.Get(NewReservEntry."Entry No.", not NewReservEntry.Positive); // Get partner-record
                NewReservEntry.Validate("Quantity (Base)", -TransferQty);
                OnTransferReservEntryOnBeforeNewReservEntryModify(NewReservEntry, true);
                NewReservEntry.Modify();
            end;
        end else
            if Abs(TransferQty) < Abs(OldReservEntry."Quantity (Base)") then begin
                OnBeforeUseOldReservEntry(OldReservEntry, InsertReservEntry);
                if OldReservEntry.Binding = OldReservEntry.Binding::"Order-to-Order" then
                    SetBinding(OldReservEntry.Binding::"Order-to-Order");
                if OldReservEntry."Disallow Cancellation" then
                    SetDisallowCancellation(OldReservEntry."Disallow Cancellation");
                if Abs(QtyToInvoiceThisLine) > Abs(TransferQty) then
                    QtyInvoiced := TransferQty
                else
                    QtyInvoiced := QtyToInvoiceThisLine;
                SetQtyToHandleAndInvoice(QtyToHandleThisLine - TransferQty, QtyToInvoiceThisLine - QtyInvoiced);
                CreateRemainingReservEntry(OldReservEntry,
                  0, (OldReservEntry."Quantity (Base)" - TransferQty) * CurrSignFactor);
                NewReservEntry.Validate("Quantity (Base)", TransferQty);
                +++++++++++++++++++++++++++++
                 OnTransferReservEntryOnBeforeNewReservEntryModify(NewReservEntry, FALSE);
                 ------------------------------------------------
                NewReservEntry.Modify();
                if NewReservEntry.Get(NewReservEntry."Entry No.", not NewReservEntry.Positive) then begin // Get partner-record
                    NewReservEntry.Validate("Quantity (Base)", -TransferQty);
                +++++++++++++++++++++++++++++
                 OnTransferReservEntryOnBeforeNewReservEntryModify(NewReservEntry, TRUE);
                 ------------------------------------------------
                    NewReservEntry.Modify();
                end;
            end else begin
                +++++++++++++++++++++++++++++
                 OnTransferReservEntryOnBeforeNewReservEntryModify(NewReservEntry, FALSE);
                 ------------------------------------------------
                NewReservEntry.Modify();
                TransferQty := NewReservEntry."Quantity (Base)";
                if NewReservEntry."Source Type" = DATABASE::"Item Ledger Entry" then begin
                    if NewReservEntry.Get(NewReservEntry."Entry No.", not NewReservEntry.Positive) then begin // Get partner-record
                        if NewReservEntry."Quantity (Base)" < 0 then
                            NewReservEntry."Expected Receipt Date" := 0D
                        else
                            NewReservEntry."Shipment Date" := DMY2Date(31, 12, 9999);
                        +++++++++++++++++++++++++++++
                        OnTransferReservEntryOnBeforeNewReservEntryModify(NewReservEntry, TRUE);
                        ------------------------------------------------
                        NewReservEntry.Modify();
                    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
