### ISSUE TITLE
[Event Request] Codeunit 86 "Sales-Quote to Order" – New Event “OnAfterModifySalesOrderHeader” in function "CreateSalesHeader"

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7075]
[Event Request] Codeunit 86 "Sales-Quote to Order" – New Event “OnAfterModifySalesOrderHeader” in function "CreateSalesHeader"

Could we please have an new publisher OnAfterModifySalesOrderHeader with the following parameters:

SalesOrderHeader
SalesHeader
It would be great if this event existed after the following line in the function "Code":

SalesOrderHeader.MODIFY;

t would be the suitable counterpart to the already existing event "OnBeforeModifySalesOrderHeader"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
