### ISSUE TITLE
[Event Request] Codeunit 86 "Sales-Quote to Order" – New Event “OnAfterCreateSalesHeader” in function "CreateSalesHeader"

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7076]
[Event Request] Codeunit 86 "Sales-Quote to Order" – New Event “OnAfterCreateSalesHeader” in function "CreateSalesHeader"

Could we please have an new publisher OnAfterCreateSalesHeader with the following parameters:

- SalesHeader

It would be great if this event existed at the end of the function CreateSalesHeader

t would be the suitable counterpart to the already existing event "OnBeforeCreateSalesHeader"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
