### ISSUE TITLE
[Event Request] Codeunit 80 OnBeforeArchivePurchOrderLine and 90 OnBeforeArchiveSalesOrderLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7077]
we Need a new Event OnBeforeArchivePurchOrderLine in codeunit 80 and OnBeforeArchiveSalesOrderLine in codeunit 90:

LOCAL ArchivePurchaseOrders(VAR TempDropShptPostBuffer : TEMPORARY Record "Drop Shpt. Post. Buffer")
IF TempDropShptPostBuffer.FINDSET THEN BEGIN
  REPEAT
    PurchOrderHeader.GET(PurchOrderHeader."Document Type"::Order,TempDropShptPostBuffer."Order No.");
    TempDropShptPostBuffer.SETRANGE("Order No.",TempDropShptPostBuffer."Order No.");
    REPEAT
      PurchOrderLine.GET(
        PurchOrderLine."Document Type"::Order,
        TempDropShptPostBuffer."Order No.",TempDropShptPostBuffer."Order Line No.");
      PurchOrderLine."Qty. to Receive" := TempDropShptPostBuffer.Quantity;
      PurchOrderLine."Qty. to Receive (Base)" := TempDropShptPostBuffer."Quantity (Base)";
      //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      OnBeforeArchivePurchOrderLine(VAR PurchOrderLine,TempDropShptPostBuffer);
      //---------------------------------------------------------
      PurchOrderLine.MODIFY;
    UNTIL TempDropShptPostBuffer.NEXT = 0;
    PurchPost.ArchiveUnpostedOrder(PurchOrderHeader);
    TempDropShptPostBuffer.SETRANGE("Order No.");
  UNTIL TempDropShptPostBuffer.NEXT = 0;
END;

LOCAL ArchiveSalesOrders(VAR TempDropShptPostBuffer : TEMPORARY Record "Drop Shpt. Post. Buffer")
IF TempDropShptPostBuffer.FINDSET THEN BEGIN
  REPEAT
    SalesOrderHeader.GET(
      SalesOrderHeader."Document Type"::Order,
      TempDropShptPostBuffer."Order No.");
    TempDropShptPostBuffer.SETRANGE("Order No.",TempDropShptPostBuffer."Order No.");
    REPEAT
      SalesOrderLine.GET(
        SalesOrderLine."Document Type"::Order,
        TempDropShptPostBuffer."Order No.",TempDropShptPostBuffer."Order Line No.");
      SalesOrderLine."Qty. to Ship" := TempDropShptPostBuffer.Quantity;
      SalesOrderLine."Qty. to Ship (Base)" := TempDropShptPostBuffer."Quantity (Base)";
     //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
     OnBeforeArchiveSalesOrderLine(VAR SalesOrderLine,TempDropShptPostBuffer);
     //---------------------------------------------------------
      SalesOrderLine.MODIFY;
    UNTIL TempDropShptPostBuffer.NEXT = 0;
    SalesPost.ArchiveUnpostedOrder(SalesOrderHeader);
    TempDropShptPostBuffer.SETRANGE("Order No.");
  UNTIL TempDropShptPostBuffer.NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
