### ISSUE TITLE
[Event Request] Codeunit 90 OnPostUpdateInvoiceLineOnBeforeInitQtyToInvoice and OnPostUpdateCrMemoLineOnBeforeInitQtyToInvoice

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7078]
we Need two new Event trigger OnPostUpdateInvoiceLineOnBeforeInitQtyToInvoice and OnPostUpdateCrMemoLineOnBeforeInitQtyToInvoice in codeunit 90. The similar trigger are just implemented in codeunit 80 in actual release 16.1:

LOCAL PostUpdateInvoiceLine()
ResetTempLines(TempPurchLine);
WITH TempPurchLine DO BEGIN
  SETFILTER("Receipt No.",'<>%1','');
  SETFILTER(Type,'<>%1',Type::" ");
  IF FINDSET THEN
    REPEAT
      PurchRcptLine.GET("Receipt No.","Receipt Line No.");
      PurchOrderLine.GET(
        PurchOrderLine."Document Type"::Order,
        PurchRcptLine."Order No.",PurchRcptLine."Order Line No.");
      IF Type = Type::"Charge (Item)" THEN
        UpdatePurchOrderChargeAssgnt(TempPurchLine,PurchOrderLine);
      PurchOrderLine."Quantity Invoiced" += "Qty. to Invoice";
      PurchOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
      //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      OnPostUpdateInvoiceLineOnBeforeInitQtyToInvoice(VAR PurchOrderLine, TempPurchLine);
      //---------------------------------------------------------

      IF ABS(PurchOrderLine."Quantity Invoiced") > ABS(PurchOrderLine."Quantity Received") THEN
        ERROR(InvoiceMoreThanReceivedErr,PurchOrderLine."Document No.");
      IF PurchOrderLine."Sales Order Line No." <> 0 THEN BEGIN // Drop Shipment
        SalesOrderLine.GET(
          SalesOrderLine."Document Type"::Order,
          PurchOrderLine."Sales Order No.",PurchOrderLine."Sales Order Line No.");
        IF ABS(PurchOrderLine.Quantity - PurchOrderLine."Quantity Invoiced") <
           ABS(SalesOrderLine.Quantity - SalesOrderLine."Quantity Invoiced")
        THEN
          ERROR(CannotPostBeforeAssosSalesOrderErr,PurchOrderLine."Sales Order No.");
      END;
      PurchOrderLine.InitQtyToInvoice;

LOCAL PostUpdateCreditMemoLine()
ResetTempLines(TempPurchLine);
WITH TempPurchLine DO BEGIN
  SETFILTER("Return Shipment No.",'<>%1','');
  SETFILTER(Type,'<>%1',Type::" ");
  IF FINDSET THEN
    REPEAT
      ReturnShptLine.GET("Return Shipment No.","Return Shipment Line No.");
      PurchOrderLine.GET(
        PurchOrderLine."Document Type"::"Return Order",
        ReturnShptLine."Return Order No.",ReturnShptLine."Return Order Line No.");
      IF Type = Type::"Charge (Item)" THEN
        UpdatePurchOrderChargeAssgnt(TempPurchLine,PurchOrderLine);
      PurchOrderLine."Quantity Invoiced" :=
        PurchOrderLine."Quantity Invoiced" + "Qty. to Invoice";
      PurchOrderLine."Qty. Invoiced (Base)" :=
        PurchOrderLine."Qty. Invoiced (Base)" + "Qty. to Invoice (Base)";
      //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      OnPostUpdateCrMemoLineOnBeforeInitQtyToInvoice(VAR PurchOrderLine, TempPurchLine);
      //---------------------------------------------------------

      IF ABS(PurchOrderLine."Quantity Invoiced") > ABS(PurchOrderLine."Return Qty. Shipped") THEN
        ERROR(InvoiceMoreThanShippedErr,PurchOrderLine."Document No.");
      PurchOrderLine.InitQtyToInvoice;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
