### ISSUE TITLE
[Event Request] Table 6661 "Return Receipt Line" – New Event “OnBeforeCodeInsertInvLineFromRetRcptLine” in function "InsertInvLineFromRetRcptLine"

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7079]
[Event Request] Table 6661 "Return Receipt Line" – New Event “OnBeforeCodeInsertInvLineFromRetRcptLine” in function "InsertInvLineFromRetRcptLine"

Could we please have an new publisher OnBeforeCodeInsertInvLineFromRetRcptLine with the following parameters (inclusive Handled-Pattern):
- Rec, 
- SalesLine,
- IsHandled

It would be great if this event exists at the beginning of the function InsertInvLineFromRetRcptLine

t would be the suitable counterpart to the already existing event "OnBeforeCodeInsertInvLineFromShptLine" in Table 111 "Sales Shipment Line" / Function: InsertInvLineFromShptLine

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
