### ISSUE TITLE
[Event Request] Page 11309 Apply General Ledger Entries - OnAfterActionPostApplication

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#7083]
Please add a new publisher event to the page action `PostApplication - OnAction()` as follows:
                
```
.
.
PostApplication - OnAction()
TempGLEntryBuf.COPY(Rec);
Apply(TempGLEntryBuf);
ShowTotalAppliedAmount := 0;
 
//>> Start New Publisher Call
OnAfterActionPostApplication(Rec, TempGLEntryBuf);
//<< End New Publisher Call
.
.
```
 
New Publisher Event:
 
```
LOCAL [IntegrationEvent] OnAfterActionPostApplication(VAR Rec : Record "G/L Entry Application Buffer";VAR TempGLEntryBuf : Record "G/L Entry Application Buffer")
```

We need access to TempGLEntryBuf, which is not possible with the default `OnActionEvent` publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
