### ISSUE TITLE
[Event Request] codeunit 5912 ServLedgEntries-Post - ReverseServLedgEntry - OnAfterInvertServLedgEntryBeforeInsert

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7084]
Hi,

We would like to extend Codeunit ServLedgEntries-Post ReverseServLedgEntry procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81814998-c0db0b80-9529-11ea-9120-d30dfb663a49.png)

``` al
[IntegrationEvent(false, false)]
local procedure OnAfterInvertServLedgEntryBeforeInsert(var NewServiceLedgerEntry: Record "Service Ledger Entry"; var ServiceLedgerEntry: Record "Service Ledger Entry")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
