### ISSUE TITLE
[Event Request] Codeunit 7301 OnModifyWhseJnlLineFromBinContent

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7085]
Please add a new Event trigger OnModifyWhseJnlLineFromBinContent in codeunit 7301 in procedure DeleteFromBinContent

local procedure DeleteFromBinContent(var WhseEntry: Record "Warehouse Entry")
…
…
            end else begin
                OnDeleteFromBinContentOnBeforeCheckQuantity(FromBinContent, WhseEntry);
                FromBinContent.CalcFields(Quantity);
                if FromBinContent.Quantity + Quantity = 0 then begin
                    "Qty. (Base)" := -FromBinContent."Quantity (Base)";
                    Sign := WhseJnlLine."Qty. (Base)" / WhseJnlLine."Qty. (Absolute, Base)";
                    WhseJnlLine."Qty. (Base)" := "Qty. (Base)" * Sign;
                    WhseJnlLine."Qty. (Absolute, Base)" := Abs("Qty. (Base)");
					//++++++++++++++++++++++++++++++++
					OnModifyWhseJnlLineFromBinContent(VAR FromBinContent,VAR WhseEntry,VAR WhseJnlLine,Sign);
					//--------------------------------
                end else

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
