### ISSUE TITLE
[Event Request] REP94 - OnPreReportBeforeCheckDimPostingRules

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#7086]
Hello,

we Need the following Event with a IsHandled-Parameter.
![image](https://user-images.githubusercontent.com/45033081/81817155-976faf00-952c-11ea-93bb-8e6edbf15dbf.png)

**Comment by RomanZanizdra** [comment]
Hi @SKeiler .
There is "IsHandled" pattern directly in CheckDimPostingRules function. You can return empty text and then followed checks will be skipped. Does it fit for you?

local procedure CheckDimPostingRules(var SelectedDim: Record "Selected Dimension"): Text[1024]
        OnBeforeCheckDimPostingRules(SelectedDim, ErrorText, Handled, GenJnlLine);
        if Handled then
            exit(ErrorText);

**Comment by SKeiler** [comment]
Unfortunaly not. There are 3 system spots which call the function, but we want only to disable it for one of this...

**Comment by RomanZanizdra** [comment]
No problem, we will implement it.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
