### ISSUE TITLE
[Event Request] Codeunit 7301 OnRegisterRoundResidualAfterGetBin

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7087]
Please add a new Event trigger OnRegisterRoundResidualAfterGetBin in Codeunit 7301:

    local procedure RegisterRoundResidual(var WhseEntry: Record "Warehouse Entry"; WhseEntry2: Record "Warehouse Entry")
    var
        WhseJnlLine2: Record "Warehouse Journal Line";
        WhseJnlRegLine: Codeunit "Whse. Jnl.-Register Line";
    begin
        with WhseEntry do begin
            WhseJnlLine2 := WhseJnlLine;
            GetBin(WhseJnlLine2."Location Code", Location."Adjustment Bin Code");
            WhseJnlLine2.Quantity := 0;
            WhseJnlLine2."Qty. (Base)" := WhseEntry2."Qty. (Base)" + "Qty. (Base)";
			//+++++++++++++++++++++++++++++++++++
			OnRegisterRoundResidualAfterGetBin(VAR WhseJnlLine2,WhseEntry,WhseEntry2);
			//-----------------------------------
            if WhseEntry2."Qty. (Base)" > Abs("Qty. (Base)") then begin
                WhseJnlLine2."To Zone Code" := Bin."Zone Code";
                WhseJnlLine2."To Bin Code" := Bin.Code;
            end else begin
                WhseJnlLine2."To Zone Code" := WhseJnlLine2."From Zone Code";
                WhseJnlLine2."To Bin Code" := WhseJnlLine2."From Bin Code";
                WhseJnlLine2."From Zone Code" := Bin."Zone Code";
                WhseJnlLine2."From Bin Code" := Bin.Code;
                WhseJnlLine2."Qty. (Base)" := -WhseJnlLine2."Qty. (Base)";
            end;
            WhseJnlLine2."Qty. (Absolute)" := 0;
            WhseJnlLine2."Qty. (Absolute, Base)" := Abs(WhseJnlLine2."Qty. (Base)");
            WhseJnlRegLine.SetWhseRegister(WhseReg);
            WhseJnlRegLine.Run(WhseJnlLine2);
            WhseJnlRegLine.GetWhseRegister(WhseReg);
            WhseEntryNo := WhseReg."To Entry No." + 1;
            "Entry No." := WhseReg."To Entry No." + 1;
        end;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
