### ISSUE TITLE
Report 846 - An implicit conversion is being performed from a value of type 'Enum "Cash Flow Source Type"' to a value of type 'Integer'

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/ALAppExtensions#7090]
A Warning "**An implicit conversion is being performed from a value of type 'Enum "Cash Flow Source Type"' to a value of type 'Integer'"** is thrown for **report 846 "Cash Flow Date List"**

![Cash Flow Date List](https://user-images.githubusercontent.com/48217797/81819163-3eede100-952f-11ea-922d-50e0a44a5348.gif)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
