### ISSUE TITLE
Report 840 - An implicit conversion is being performed from a value of type 'Enum "Cash Flow Source Type"' to a value of type 'Integer'

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/ALAppExtensions#7091]
A Warning **"An implicit conversion is being performed from a value of type 'Enum "Cash Flow Source Type"' to a value of type 'Integer'"** is thrown for **report 840 "Suggest Worksheet Lines"**

![Suggest Worksheet Lines](https://user-images.githubusercontent.com/48217797/81820442-eae3fc00-9530-11ea-94c4-10ef0a79d1ac.gif)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
