### ISSUE TITLE
Table 39 - An implicit conversion is being performed from a value of type 'Enum "Purchase Line Type"' to a value of type 'Option'

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/ALAppExtensions#7093]
A Warning **"An implicit conversion is being performed from a value of type 'Enum "Purchase Line Type"' to a value of type 'Option'"** is thrown for **table 39 "Purchase line**". 

This Warning is also thrown for other calls to the **function TypeToTableID3** in **DimensionManagement** where **an Enum is passed as parameter.**

![image](https://user-images.githubusercontent.com/48217797/81821830-a3f70600-9532-11ea-8927-bacf1b84829a.png)

**Comment by AlexanderYakunin** [comment]
Enum implementation is multi releases process, we need warnings to visualize conversion issues and currently working on them. As all enums use property AssignmentCompatibility, this is currently not an issue. If you want to remove this warning for your code, use Type.AsInteger().
