### ISSUE TITLE
[Event Request] Report 11517 OnBeforeUpdateTempItemStatisticsBuffer

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7094]
Please Change the Parameter ValueEntry2 to VAR, so we can use the filter from ValueEntry2 in our extension :

old:
local procedure OnBeforeUpdateTempItemStatisticsBuffer(var TempItemStatisticsBuffer: Record "Item Statistics Buffer"; var ValueEntry: Record "Value Entry"; ValueEntry2: Record "Value Entry"; ItemLedgEntry: Record "Item Ledger Entry");
new:
local procedure OnBeforeUpdateTempItemStatisticsBuffer(var TempItemStatisticsBuffer: Record "Item Statistics Buffer"; var ValueEntry: Record "Value Entry"; VAR ValueEntry2: Record "Value Entry"; ItemLedgEntry: Record "Item Ledger Entry");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
