### ISSUE TITLE
[Event  modification] Table 5740 "Transfer Header" - modify event "OnBeforeDeleteTransferLines"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#7095]
Dear AL Team,

I asked in event request #6593 a new event Publisher OnBeforeDeleteTransferLines. This publisher required as parameters "Transfer Line" and IsHandled, but checking the new event in the cu1, the publisher only has the parameter IsHandled.

I need a modification in the event publisher and code in the trigger (I need this modification urgently, please, if posible, I need it in cumulative 2):

OLD CODE:

 local procedure DeleteTransferLines()
    var
        TransLine: Record "Transfer Line";
        IsHandled: Boolean;
    begin
        OnBeforeDeleteTransferLines(IsHandled);
        if IsHandled then
            exit;

        TransLine.SetRange("Document No.", "No.");
        TransLine.DeleteAll(true);
    end;

NEW CODE

 local procedure DeleteTransferLines()
    var
        TransLine: Record "Transfer Line";
        IsHandled: Boolean;
    begin
       //start new code
      IsHandled:=false;
        OnBeforeDeleteTransferLines(Rec,IsHandled); //Add Transfer Header as parameter
      //end new code

       if IsHandled then
            exit;

        TransLine.SetRange("Document No.", "No.");
        TransLine.DeleteAll(true);
    end;
 
OLD PUBLISHER
[IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteTransferLines(var IsHandled: Boolean)
    begin
    end;

NEW PUBLISHER
[IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteTransferLines(Rec: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
