### ISSUE TITLE
[Event Request] Report 702 OnAfterCheckItemJnLLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7096]
We need a new Event OnAfterCheckItemJnLLine in report 702 at the end of AfterGetRecord, to check the ItemJnlLines in our extension:

Item Journal Line - OnAfterGetRecord()
  OnBeforeItemJournalLineOnAfterGetRecord("Item Journal Line",ErrorCounter,ErrorText);
  ….
  ….
  5:
    BEGIN
      TotalAm5 := TotalAm5 + Amount;
      TotalCostAm5 := TotalCostAm5 + CostAmount;
    END;
END;

//+++++++++++++++++++++++++++++++++++
OnAfterCheckItemJnLLine("Item Journal Line", Item, VAR ErrorCounter, VAR ErrorText);
//-----------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
