### ISSUE TITLE
[Event Request] Codeunit 5912 ServLedgEntries-Post - ReverseWarrantyEntry - OnAfterInvertWarrantyLedgEntryBeforeInsert

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7097]
Hi,

We would like to extend Codeunit ServLedgEntries-Post ReverseWarrantyEntry procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81907270-c8e98880-95c7-11ea-8be3-bc6e6406e76f.png)

``` al
[IntegrationEvent(false, false)]
local procedure OnAfterInvertWarrantyLedgEntryBeforeInsert(var NewWarrantyLedgerEntry: Record "Warranty Ledger Entry"; var WarrantyLedgerEntry: Record "Warranty Ledger Entry")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
