### ISSUE TITLE
[Event Request] Codeunit 5818 Undo Service Shipment Line - CheckComponentsAdjusted - OnAfterLocalServShptLineSetFilters

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7098]
Hi,

We would like to extend Codeunit Undo Service Shipment Line CheckComponentsAdjusted procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81913830-cb041500-95d0-11ea-9d34-7c51dfc0dd6d.png)

```al
[IntegrationEvent(false, false)]
local procedure OnAfterLocalServShptLineSetFilters(var ServiceShptLine : Record "Service Shipment Line")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
