### ISSUE TITLE
[Event Request] PAG9850 - OnBeforeTenantPermissionDeleteOnModify

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#7099]
Hello,

we Need a handled-Evennt on PAG9850 on ModifyRecord-procedure.

![image](https://user-images.githubusercontent.com/45033081/81916801-9abe7580-95d4-11ea-9774-5bf0b287c497.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
