### ISSUE TITLE
[Event Request] Codeunit 5807 Item Charge Assgnt. (Sales) - SuggestAssignment - OnSuggestAssignmentOnBeforeAssignItemCharges

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7100]
Hi,

We would like to extend Codeunint Item Charge Assgnt. (Sales) SuggestAssignment procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81920225-30f49a80-95d9-11ea-9f1d-501ed39df677.png)

```al
[IntegrationEvent(false, false)]
local procedure OnSuggestAssignmentOnBeforeAssignItemCharges(var SalesLine: Record "Sales Line"; ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
