### ISSUE TITLE
[Event Modification] to OnAfterGetInboundDocs & OnAfterGetSingleInboundDoc Events in Codeunit 5751 "Get Source Doc. Inbound"

### ISSUE THREAD

**Issue by NeilHalliday** [microsoft/ALAppExtensions#7101]
Hi,

The following two publishers in codeunit 5751 "Get Source Doc. Inbound" are not using vars for the WarehouseReceiptHeader records.

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetInboundDocs(WarehouseReceiptHeader: Record "Warehouse Receipt Header")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetSingleInboundDoc(WarehouseReceiptHeader: Record "Warehouse Receipt Header")
    begin
    end;

Can these be changed to vars so that they are consistent with their counterparts in codeunit 5752 "Get Source Doc. Outbound"?

Thanks
Neil.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
