### ISSUE TITLE
[Event Request] Codeunit 5815 Undo Sales Shipment Line - DeleteSalesShptLineServItems - OnBeforeDeleteSalesShptLineServitems

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7103]
Hi,

We would like to extend Codeunit Undo Sales Shipment Line DeleteSalesShptLineServItems  procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81922532-8d0cee00-95dc-11ea-8b5c-3ec07d7ae615.png)

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteSalesShptLineServitems(var SalesShptLine: Record "Sales Shipment Line"; IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
