### ISSUE TITLE
[Event Request] Codeunit 5805 Item Charge Assgnt. (Purch.) - SuggestAssgnt - OnSuggestAssignmentOnBeforeAssignItemCharges

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7104]
Hi,

We would like to extend Codeunit Item Charge Assgnt. (Purch.) SuggestAssgnt  procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81923425-f0e3e680-95dd-11ea-95bf-3fd7f61bff83.png)

```al
[IntegrationEvent(false, false)]
local procedure OnSuggestAssignmentOnBeforeAssignItemCharges(var PurchaseLine: Record "Purchase Line"; ItemChargeAssignmentPurch: Record "Item Charge Assignment (Purch)")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
