### ISSUE TITLE
[Bug] Codeunit 1303 "Correct Posted Sales Invoice" - wrong publisher call deleted

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#7105]
Hello Team,
I have just created a new container with BC version 16.01. Now some tests are failing because a publisher is not longer called.
In the earlier version you called two publishers, but one of them had a spelling mistake. 
**Problem: you have deleted the call of the correctly spelled publisher.** 

Publisher:
![image](https://user-images.githubusercontent.com/30338136/81924728-c8f58280-95df-11ea-9b27-864b16b5112e.png)

BC old:
![image](https://user-images.githubusercontent.com/30338136/81924870-fb9f7b00-95df-11ea-9405-18f39ac5eb6c.png)

BC new:
![image](https://user-images.githubusercontent.com/30338136/81924821-e62a5100-95df-11ea-8453-d8b53671d04c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
