### ISSUE TITLE
[Event Request] Codeunit 5790 Available to Promise - QtyAvailabletoPromise - OnBeforeQtyAvailableToPromise

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7106]
Hi,

We would like to extend the standard OnBeforeQtyAvailableToPromise like this:

![image](https://user-images.githubusercontent.com/64962632/81926106-c5fb9180-95e1-11ea-8399-07c57413a3de.png)

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeQtyAvailableToPromise(var Item: Record Item; AvailabilityDate: Date; var GrossRequirement: Decimal; var ScheduledReceipt: Decimal; PeriodType: Option Day,Week,Month,Quarter,Year; LookaheadDateFormula: DateFormula; var AvailableToPromise: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
