### ISSUE TITLE
[Event Request] Report 394 Suggest Employee Payments

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#7107]
Hello,
please add a new publisher events similar to Report Suggest Vendor Payments.

In function CopyTempEmpPaymentBuffersToGenJnlLines():
```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateGnlJnlLineDimensionsFromTempBuffer(var GenJournalLine: Record "Gen. Journal Line"; TempEmplPaymentBuffer: Record "Employee Payment Buffer" temporary)
    begin
    end;
```

In function MakeGenJnlLines():
```
[IntegrationEvent(false, false)]
local procedure OnUpdateTempBufferFromEmployeeLedgerEntry(var TempEmplPaymentBuffer: Record "Employee Payment Buffer" temporary; EmployeeLedgerEntry: Record "Employee Ledger Entry")
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
