### ISSUE TITLE
[Event Request] Codeunit 5790 Available to Promise - CalcAvailableInventory - OnBeforeCalcAvailableInventory

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7109]
Hi,

We would like to extend Codeunit Available to Promise CalcAvailableInventory procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81928936-5f2ca700-95e6-11ea-969e-e08da1eede7b.png)

```al
OnBeforeCalcAvailableInventory(Item, AvailableInventory, IsHandled);
if IsHandled then
    exit(AvailableInventory);
```

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcAvailableInventory(var Item: Record Item; var AvailableInventory: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
