### ISSUE TITLE
[Event Request] Codeunit 414 - Code OnCodeOnCheck

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#7110]
Hi, we would like to have following event: 
![image](https://user-images.githubusercontent.com/54843470/81932429-1677ec80-95ec-11ea-86a3-54aea4d2cb9e.png)

Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
