### ISSUE TITLE
[Event Request] Codeunit 5707 TransferOrder-Post + Print - PrintShipment - OnBeforePrintShipment

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7111]
Hi,

We would like to extend Codeunit TransferOrder-Post + Print PrintShipment procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81933585-f1847900-95ed-11ea-97df-40ef42cf91c4.png)

```al
OnBeforePrintReceipt(DocNo, IsHandled);
if IsHandled then
    exit;
```

```al
[IntegrationEvent(false, false)]
local procedure OnBeforePrintShipment(DocNo: Code[20]; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
