### ISSUE TITLE
[Event Request] Codeunit 5707 TransferOrder-Post + Print - PrintReceipt - OnBeforePrintReceipt

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7112]
Hi,

We would like to extend Codeunit TransferOrder-Post + Print PrintReceipt procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81934017-8a1af900-95ee-11ea-80d1-cb39340d1545.png)

```al
OnBeforePrintReceipt(DocNo, IsHandled);
if IsHandled then
    exit;
```

```al
[IntegrationEvent(false, false)]
local procedure OnBeforePrintReceipt(DocNo: Code[20]; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
