### ISSUE TITLE
Transfer header Table No. series is not extensible

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#7113]
Transfer header Table No. series is not extensible
No. Series code is not following the pattern same as sales/purchase header.

We need the same functions an triggers.

We need the same functions an triggers.

Look for these triggers in Sales Header table
OnAfterGetNoSeriesCode
OnBeforeTestNoSeries
OnAfterInitRecord

**Comment by AlexanderYakunin** [comment]
We already have all events mentioned before in Transfer Header. Please look into latest version (=v17). Request will be closed. If you need something on top of existing events, please create new request with definition of changes you need.

**Comment by shashiBssi** [comment]
we don't have this trigger in transfer header table(OnBeforeTestNoSeries)

Request to provide the same with handled pattern.

we need signature same as it is in sales header table.(please look into sales header table for this trigger)

OnBeforeTestNoSeries(Rec, IsHandled);
        if not IsHandled then
