### ISSUE TITLE
[Additional Parameter] CU 17 GLRegNo

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#7114]
Hi,
is it posible to add additional parameter to next functions in cu17 for GLRegNo. OR you can send your global parameter GenJnlPostLine to functions and we can get it like GenJnlPostLine.GetGLReg(GLReg);
We can use it in existing events like:
**procedure ReverseCustLedgEntry --> OnReverseCustLedgEntryOnBeforeInsertCustLedgEntry
procedure ReverseVendLedgEntry --> OnReverseVendLedgEntryOnBeforeInsertVendLedgEntry
procedure ReverseGLEntry -> OnReverseGLEntryOnBeforeLoop**

We need GLReg."No." to assign there

**Comment by RomanZanizdra** [comment]
Hi @VladimirVeljovic . 
Sorry missed the following thing. "From where" and "To where" you need to pass and assign GLRegNo?

**Comment by VladimirVeljovic** [comment]
> Hi @VladimirVeljovic .
> Sorry missed the following thing. "From where" and "To where" you need to pass and assign GLRegNo?

Hi Roman,
so we are starting for assigning GLRegNo := GLReg."No."; in procedure Reverse.
After that we use the same GLRegNo in procedures ReverseCustLedgEntry, ReverseVendLedgEntry and ReverseGLEntry. My recomendation was to use events in those procedures like OnReverseCustLedgEntryOnBeforeInsertCustLedgEntry, OnReverseVendLedgEntryOnBeforeInsertVendLedgEntry, OnReverseGLEntryOnBeforeLoop and extend it with existing  global  variable GenJnlPostLine, so we can collect GLReg via GenJnlPostLine.GetGLReg(GLReg);

is it possible?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
