### ISSUE TITLE
[Event Request] Codeunit 5703 Catalog Item Management - NonstockItemVend - OnBeforeNonstockItemVendInsert

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7115]
Hi,

We would like to extend Codeunit "Catalog Item Management" NonstockItemVend  procedure like this:

![image](https://user-images.githubusercontent.com/64962632/81936902-2810c280-95f3-11ea-81ed-f80274e2fd98.png)

```al
OnBeforeNonstockItemVendInsert(ItemVend, Nonstock2);
```

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeNonstockItemVendInsert(var ItemVend: Record "Item Vendor"; NonStockItem: Record "Nonstock Item")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
