### ISSUE TITLE
[Event Request] CU 23 function PostLines

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#7116]
Hi,
we need event in cu23 function PostLines Like:
![image](https://user-images.githubusercontent.com/53824412/81941135-b3408700-95f8-11ea-9145-453544c03068.png)

OnPostLinesOnAfterPostLine(ItemJnlLine, SuppressCommit);

    [IntegrationEvent(false, false)]
    local procedure OnPostLinesOnAfterPostLine(var ItemJournalLine: Record "Item Journal Line"; var SuppressCommit: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
