### ISSUE TITLE
[FunctionVisibilityRequest] Table 36 / 38 Sales / Purchase Header

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#7118]
Due to Polish Localization App building, we would like to use standard function ConfirmUpdateCurrencyFactor from table 36 Sales Header and table 38 Purchase Header. In our solution we currently invoke standard function UpdateCurrencyFactor and use OnBeforeUpdateCurrencyFactor event publisher to calculate currency factor for other date than Posting Date. Unfortunately we had to clone ConfirmUpdateCurrencyFactor because this function is local and we can't invoke it from other codeunit where we have event subscriber.

 

Function: ConfirmUpdateCurrencyFactor (the same in table 36 and 38)
Current function signature: local procedure ConfirmUpdateCurrencyFactor() (table 36 and 38)
Requested function signature: procedure ConfirmUpdateCurrencyFactor() (table 36 and 38)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
