### ISSUE TITLE
[Function Expose] Codeunit 7313 - GetSpecEquipmentCode

### ISSUE THREAD

**Issue by makuhn** [Microsoft/ALAppExtensions#712]
Declare function **GetSpecEquipmentCode** of Codeunit 7313 as external:
```
-    LOCAL PROCEDURE GetSpecEquipmentCode@3(BinCode@1000 : Code[20]) : Code[10];
+    [External]
+    PROCEDURE GetSpecEquipmentCode@3(BinCode@1000 : Code[20]) : Code[10];
```

**Comment by darjoo** [comment]
Hi @makuhn,
We have accepted your request and typically include these types of changes in the next minor release, so look for it there!
