### ISSUE TITLE
Contact Change request

### ISSUE THREAD

**Issue by stijn9830** [microsoft/ALAppExtensions#7120]
I'm writing an app for contact management.
I would like following changes:
T5050 : Type is now an option, can it be changed to extendable enum?
T5050 : Can we get round this test  on validation of Company No. : TESTFIELD(Type,Type::Person);
            This means we can only add persons to a company, I would like to extend that

Company No. - OnValidate()
IF Cont.GET("Company No.") THEN
  InheritCompanyToPersonData(Cont)
ELSE
  CLEAR("Company Name");

IF "Company No." = xRec."Company No." THEN
  EXIT;

//TESTFIELD(Type,Type::Person);

thanks
Stijn Mommerency

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
