### ISSUE TITLE
[EventRequest] Table 5740 - Transfer Header - DeleteOneTransferOrder

### ISSUE THREAD

**Issue by RishtaCader** [microsoft/ALAppExtensions#7121]
Hello,
We need new event in the Table 5740 (OnBeforeDeleteOneTransferOrder) :

procedure DeleteOneTransferOrder(var TransHeader2: Record "Transfer Header"; var TransLine2: Record "Transfer Line")
    var
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        WhseRequest: Record "Warehouse Request";
        InvtCommentLine: Record "Inventory Comment Line";
        No: Code[20];
    begin
        No := TransHeader2."No.";

        WhseRequest.SetRange("Source Type", DATABASE::"Transfer Line");
        WhseRequest.SetRange("Source No.", No);
        if not WhseRequest.IsEmpty then
            WhseRequest.DeleteAll(true);

        InvtCommentLine.SetRange("Document Type", InvtCommentLine."Document Type"::"Transfer Order");
        InvtCommentLine.SetRange("No.", No);
        InvtCommentLine.DeleteAll();

        ItemChargeAssgntPurch.SetCurrentKey(
          "Applies-to Doc. Type", "Applies-to Doc. No.", "Applies-to Doc. Line No.");
        ItemChargeAssgntPurch.SetRange("Applies-to Doc. Type", ItemChargeAssgntPurch."Applies-to Doc. Type"::"Transfer Receipt");
        ItemChargeAssgntPurch.SetRange("Applies-to Doc. No.", TransLine2."Document No.");
        ItemChargeAssgntPurch.DeleteAll();

        OnBeforeTransLineDeleteAll(TransHeader2, TransLine2);

        if TransLine2.Find('-') then
            TransLine2.DeleteAll();

        TransHeader2.Delete();
        // New event request >>
        OnBeforeDeleteOneTransferOrder(TransHeader2,HideValidationDialog);
        // New event request <<
        if not HideValidationDialog then
            Message(TransferOrderPostedMsg1, No);
    end;

Signature :
LOCAL [IntegrationEvent] OnBeforeDeleteOneTransferOrder(VAR TransHeader : Record "Transfer Header";VAR HideValidationDialog : Boolean)

Thank you
Kind Regards
Rishta

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
