### ISSUE TITLE
[Event Request] Codeunit 86 "Sales-Quote to Order" - CheckInProgressOpportunities - OnBeforeInsertTempOpportunityEntry

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7123]
Hi,

We would like to extend Codeunit "Sales-Quote to Order" CheckInProgressOpportunities procedure like this:

![image](https://user-images.githubusercontent.com/64962632/82029639-93ac6b80-9697-11ea-94ec-bb3bfbf422db.png)

```al
OnBeforeInsertTempOpportunityEntry(TempOpportunityEntry);
```

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertTempOpportunityEntry(var TempOpportunityEntry: Record "Opportunity Entry");
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
