### ISSUE TITLE
[Event Request] Cu 80 function FillInvoicePostingBuffer

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#7124]
Hi,
we would need in CU80 in function FillInvoicePostingBuffer next event:
![image](https://user-images.githubusercontent.com/53824412/82030245-79bf5880-9698-11ea-9732-34bbfb96bd00.png)

OnAfterSetSalesAccount(SalesAccount, SalesLine, GenPostingSetup);

[IntegrationEvent(false, false)]
local procedure OnAfterSetSalesAccount(var SalesAccount, SalesLine, GenPostingSetup)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
