### ISSUE TITLE
[Event Request] Codeunit 87 "Blanket Sales Order to Order" - OnRun - OnBeforeBlanketOrderToSalesOrder

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#7125]
Hi,

We would like to extend Codeunit "Blanket Sales Order to Order" OnRun procedure like this:

![image](https://user-images.githubusercontent.com/64962632/82031361-133b3a00-969a-11ea-9c26-8b624c829cd3.png)

```al
OnBeforeBlanketOrderToSalesOrder(BlanketOrderSalesLine);
```

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeBlanketOrderToSalesOrder(var BlanketOrderSalesLine: Record "Sales Line")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
