### ISSUE TITLE
Request to change "Replenishment System" Option field to an Enum field in Requisition Line table 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#7141]
Requisition Line table 

        field(99000903; "Replenishment System"; Option)
        {
            Caption = 'Replenishment System';
            OptionCaption = 'Purchase,Prod. Order,Transfer,Assembly, ';
            OptionMembers = Purchase,"Prod. Order",Transfer,Assembly," "

**Comment by AlexanderYakunin** [comment]
Already implemented:
        field(99000903; "Replenishment System"; Enum "Replenishment System")
