### ISSUE TITLE
[Event Request] COD 11 / Gen. Jnl.-Check Line IT localization OnBeforeCheckOperationOccurredDate/OnAfterCheckOperationOccurredDate

### ISSUE THREAD

**Issue by fastudio** [microsoft/ALAppExtensions#7142]
LOCAL CheckDates(VAR GenJnlLine : Record "Gen. Journal Line")
WITH GenJnlLine DO BEGIN
  TESTFIELD("Posting Date");
  IF "Posting Date" <> NORMALDATE("Posting Date") THEN BEGIN
    IF ("Account Type" <> "Account Type"::"G/L Account") OR
       ("Bal. Account Type" <> "Bal. Account Type"::"G/L Account")
    THEN
      FIELDERROR("Posting Date",Text000);
    IF NOT SkipFiscalYearCheck THEN BEGIN
      IsHandled := FALSE;
      OnBeforeCheckPostingDateInFiscalYear(GenJnlLine,IsHandled);
      IF NOT IsHandled THEN
        AccountingPeriodMgt.CheckPostingDateInFiscalYear("Posting Date");
    END;
  END;

  OnBeforeDateNotAllowed(GenJnlLine,DateCheckDone);
  IF NOT DateCheckDone THEN
    IF DateNotAllowed("Posting Date") THEN
      FIELDERROR("Posting Date",Text001);

  IF "Operation Occurred Date" = 0D THEN
    "Operation Occurred Date" := "Posting Date";
  OnBeforeCheckOperationOccurredDate(GenJnlLine);
  IF ("Operation Occurred Date" <= GLSetup."Last Gen. Jour. Printing Date") AND (Amount <> 0) THEN
    FIELDERROR("Operation Occurred Date", STRSUBSTNO(Text12001, GLSetup."Last Gen. Jour. Printing Date"));
  OnAfterCheckOperationOccurredDate(GenJnlLine);

  IF "Document Date" <> 0D THEN
    IF ("Document Date" <> NORMALDATE("Document Date")) AND
       (("Account Type" <> "Account Type"::"G/L Account") OR
        ("Bal. Account Type" <> "Bal. Account Type"::"G/L Account"))
    THEN
      FIELDERROR("Document Date",Text000);
END;

**Comment by fastudio** [comment]
the purpose is allowing filtering records of GenJnlLine to exclude from the comparison, for instance a specific Source Code. Before I apply a filter to GenJnlLine, After I remove it

**Comment by fastudio** [comment]
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckOperationOccurredDate(var GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

[IntegrationEvent(false, false)]
    local procedure OnAfterCheckOperationOccurredDate(var GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by fastudio** [comment]
Hi just realized that there is already the event OnBeforeCheckOperationOccurredDate On BC16, sorry for the false alarm.

Regards

Fabio
