### ISSUE TITLE
Field 105 "Shipping Agent" in table 114 "Sales Cr.Memo Header"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7143]
We would like to use the field 105 "Shipping Agent" in our Extension in the Sales area.
This field exists in table 36,110,112 and even in 5107 and 6660.
But in table 114 this field is missing.
Could you please add the field 105 to table 114 because this is conform to the process Order->Shipment-> Invoice and ReturnOrder->ReturnShipment->CreditMemo and the returned process to cancel invoices and credit memos.

If the field is not added we Need to create this field in our Extension and the field number gets a new number. So the TRANSFERFIELDS processes do not Transfer our Extension field to table 114 and back from table 114 to table 36 in case of cancelling a credit Memo. Then we Need additional Code to get the process valid.

**Comment by AlexanderYakunin** [comment]
We already have this field in table SalesCrMemoHeader.Table.al.

        field(105; "Shipping Agent Code"; Code[10])
        {
            AccessByPermission = TableData "Shipping Agent Services" = R;
            Caption = 'Shipping Agent Code';
            TableRelation = "Shipping Agent";
        }

**Comment by GuntherGebauer** [comment]
thanks
