### ISSUE TITLE
[Event Request] Page 5096 Task List- OnBeforeGenerateCaption

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#7148]
Hello,

Please add a new publisher event to the function **Caption** as follows:

    procedure Caption(): Text
    var
        CaptionStr: Text;
    begin
        // Start New Publisher Call
        OnBeforeGenerateCaption(Rec, Handled, CaptionStr);
        if Handled then
            exit(CaptionStr);
        // End New Publisher Call

        if Cont.Get(GetFilter("Contact Company No.")) then begin
            Contact1.Get(GetFilter("Contact Company No."));
            if Contact1."No." <> Cont."No." then
                CaptionStr := CopyStr(Cont."No." + ' ' + Cont.Name, 1, MaxStrLen(CaptionStr));
        end;
        if Cont.Get(GetFilter("Contact No.")) then
            CaptionStr := CopyStr(CaptionStr + ' ' + Cont."No." + ' ' + Cont.Name, 1, MaxStrLen(CaptionStr));
        if Salesperson.Get(GetFilter("Salesperson Code")) then
            CaptionStr := CopyStr(CaptionStr + ' ' + Salesperson.Code + ' ' + Salesperson.Name, 1, MaxStrLen(CaptionStr));
        if Team.Get(GetFilter("Team Code")) then
            CaptionStr := CopyStr(CaptionStr + ' ' + Team.Code + ' ' + Team.Name, 1, MaxStrLen(CaptionStr));
        if Campaign.Get(GetFilter("Campaign No.")) then
            CaptionStr := CopyStr(CaptionStr + ' ' + Campaign."No." + ' ' + Campaign.Description, 1, MaxStrLen(CaptionStr));
        if Opp.Get(GetFilter("Opportunity No.")) then
            CaptionStr := CopyStr(CaptionStr + ' ' + Opp."No." + ' ' + Opp.Description, 1, MaxStrLen(CaptionStr));
        if SegHeader.Get(GetFilter("Segment No.")) then
            CaptionStr := CopyStr(CaptionStr + ' ' + SegHeader."No." + ' ' + SegHeader.Description, 1, MaxStrLen(CaptionStr));
        if CaptionStr = '' then
            CaptionStr := Text001;

        exit(CaptionStr);
    end;

New Publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGenerateCaption(var ToDo: Record "To-do"; var Handled: Boolean; var CaptionStr: Text)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
