### ISSUE TITLE
[Event Request] Codeunit 5771 - OnAfterCheckCreateWhseRequest

### ISSUE THREAD

**Issue by makuhn** [Microsoft/ALAppExtensions#715]
Add new integration event **OnAfterCheckCreateWhseRequest** in Codeunit 5771.

Function Release:
```
            IF First OR (SalesLine."Location Code" <> OldLocationCode) OR (WhseType <> OldWhseType) THEN
              CreateWhseRqst(SalesHeader,SalesLine,WhseType);

+           OnAfterCheckCreateWhseRequest(SalesHeader, SalesLine, WhseType);

            First := FALSE;
            OldLocationCode := SalesLine."Location Code";
```
New publisher function:
```
    [Integration]
    LOCAL PROCEDURE OnAfterCheckCreateWhseRequest@100000000(SalesHeader@100000002 : Record 36;VAR SalesLine@100000001 : Record 37;WhseType@100000000 : 'Inbound,Outbound');
    BEGIN
    END;
```

**Comment by cosmo-skol** [comment]
Hi AL-Team,
sorry to revive this issue, but we would need the above publisher to be extended with additional parameters and "SalesHeader" as VAR, to perform additional checks and edit module tables:

`LOCAL [IntegrationEvent] OnAfterCheckCreateWhseRequest(VAR SalesHeader : Record "Sales Header";VAR SalesLine : Record "Sales Line";WhseType : 'Inbound,Outbound';First : Boolean;OldWhseType : 'Inbound,Outbound';OldLocationCode : Code[10])`

**Comment by NKarolak** [comment]
@jobulsin This event is still missing in the Business Central Insider. Wrong label?

**Comment by NKarolak** [comment]
Still not available in BC 15.
