### ISSUE TITLE
[EventRequest] Codeunit 5704 "TransferOrder-Post Shipment", OnRunOnBeforeCommit

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#7154]
Please add permission to global var for OnRunOnBeforeCommit publisher event as Sales-Post codeunit.

Alternatively I ask you to change the signature as follows
`
OnRunOnBeforeCommit(VAR TransferHeader : Record "Transfer Header";TransferShipmentHeader : Record "Transfer Shipment Header";PostedWhseShptHeader : Record "Posted Whse. Shipment Header")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
