### ISSUE TITLE
[EventRequest] codeunit 5705 "TransferOrder-Post Receipt", OnRun

### ISSUE THREAD

**Issue by Enomis82** [microsoft/ALAppExtensions#7155]
Please add a new publisher event OnBeforeRECORD50 in report 12172 on function RECORD50 and call it as shown below:
![image](https://user-images.githubusercontent.com/26144133/82312262-19495780-99c7-11ea-90c1-1edab60fe114.png)

Please add the corresponding Integration Event In the bottom of the object

`
    [IntegrationEvent(default, true)]
    local procedure OnRunOnBeforeCommit(var TransferHeader: Record "Transfer Header"; TransReceiptHeader: Record "Transfer Receipt Header")
    begin
    end;
`

if it's not possible to ave access to global var (as same function on Sales-Post Codeunit) please add on sign also PostedWhseRcptHeader : Record "Posted Whse. Receipt Header"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
