### ISSUE TITLE
[Event Request] Page 1173 - Document Attachment Details - OnBeforeUploadFile

### ISSUE THREAD

**Issue by ahenkel** [microsoft/ALAppExtensions#7159]
Please add the following Event to make it possible to customize the way how the user can add files.
We want to extend it by a method to import Mails from other applications.

In DrillDown of Field "Name"
``` al 
IF "Document Reference ID".HASVALUE THEN
  Export(TRUE)
ELSE BEGIN
+  OnBeforeUploadFile(TempBlob,FileName,Handled);
+  IF NOT Handled THEN
    FileName := FileManagement.BLOBImportWithFilter(TempBlob,ImportTxt,FileName,STRSUBSTNO(FileDialogTxt,FilterTxt),FilterTxt);

  IF FileName <> '' THEN
    SaveAttachment(FromRecRef,FileName,TempBlob);
  CurrPage.UPDATE(FALSE);
```
Event
```al
+    LOCAL PROCEDURE OnBeforeUploadFile(VAR TempBlob: Record TempBlob;VAR FileName: Text;VAR Handled: Boolean);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
