### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnCodeOnBeforeGetNextReference”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7160]
[Event Request] Codeunit 7324 "Whse.-Activity-Post" – New Event “OnCodeOnBeforeGetNextReference”

Could we please have an new publisher OnCodeOnBeforeGetNextReference with Handled Pattern?
It would be great if we could influence the next reference number ourselves.

local procedure "Code"()

    var
        TransferOrderPostPrint: Codeunit "TransferOrder-Post + Print";
        ItemTrackingRequired: Boolean;
        Selection: Option " ",Shipment,Receipt;
        ForceDelete: Boolean;
    begin
        OnBeforeCode(WhseActivLine, SuppressCommit);

//New Code Begin
        IsHandled := false;        
        OnCodeOnBeforeGetNextReference(PostingReference,IsHandled);
        If IsHandled = false then
//New Code End
        PostingReference := WhseSetup.GetNextReference;

        with WhseActivHeader do begin
            WhseActivLine.SetRange("Activity Type", WhseActivLine."Activity Type");
            WhseActivLine.SetRange("No.", WhseActivLine."No.");
            WhseActivLine.SetFilter("Qty. to Handle", '<>0');

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
