### ISSUE TITLE
Creation of ReserveEntry looks wrong

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#7161]
Hello Team,

following scenario:

You manually create a production order for item1 with "reordering policy" = BLANK. 
The component item2 "reordering policy" is set to "Order" and "Order Tracking Policy" is set to "Tracking & Action Msg."

if you manually create the production order of the item1, 
you get a reserve entry for the item2 of Reservationstatus = Surplus.

But you already have a need for that item2 in the production order of item1. 
So it is NO surplus!

If you calculate entries in a planning worksheet, the entry of item2 is vanished. So at the end all is fine.

In my opinion there is no need to create that "surplus-entry" beforehand and it should be handled accordingly.

**Comment by StanPesotskiy** [comment]
This issue is not related to the AL extensibility. Please report it via the standard support channel.
