### ISSUE TITLE
[Request for External] Table "Warehouse Receipt Header", "Warehouse Shipment Header", "Whse. Internal Put-away Header", "Whse. Internal Pick Header"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7162]
Please make MessageIfRcptLinesExist in "Warehouse Receipt Header" , MessageIfShptLinesExist in "Warehouse Shipment Header", MessageIfIntPutawayLinesExist in "Whse. Internal Put-away Header" and MessageIfIntPickLinesExist in "Whse. Internal Pick Header" public and external. The same functions are already public in T36 and T38.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
