### ISSUE TITLE
Requesting a new event publisher on Codeunit 365 Format Address / procedure RespCenter

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7164]
Requesting a new event publisher on Codeunit 365 Format Address / procedure RespCenter

Event
OnBeforeRespCenter(VAR AddrArray : ARRAY [8] OF Text[100];VAR RespCenter : Record "Responsibility Center";VAR IsHandled : Boolean)

Code

RespCenter(VAR AddrArray : ARRAY [8] OF Text[100];VAR RespCenter: Record "Responsibility Center")

> New Code Begin
OnBeforeRespCenter(AddrArray, RespCenter, IsHandled);
IF IsHandled THEN 
  EXIT;
> New Code End

FormatAddr(
  AddrArray,Name,"Name 2",'',Address,"Address 2",
  City,"Post Code",County,'');

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
