### ISSUE TITLE
Report "Consolidated Trial Balance" layout change

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#7165]
is it possible to have a minor change done to the layout of the report "consolidated trial balance"
in the BE version the title of the report is not completely shown:
![image](https://user-images.githubusercontent.com/45969156/82428887-727abf00-9a8b-11ea-9cc6-585fceac9e90.png)

**Comment by StanPesotskiy** [comment]
This issue is not related to the AL extensibility. Please report it via the standard support channel.
