### ISSUE TITLE
[Enum Request] Table 7355 Report Selection Warehouse - Usage Field

### ISSUE THREAD

**Issue by GaryFrostick** [microsoft/ALAppExtensions#7166]
Can we please make the Usage field on Table 7355 Report Selection Warehouse an enum so it is possible to specify custom warehouse documents and to make this consistent with the other report selections.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
