### ISSUE TITLE
[Event Request]  Table 5050 Contact - OnBeforeCreateVendor

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#7167]
Please add a new publisher event to the function `CreateVendor` as follows:
                
```
.
.
[External] CreateVendor() : Code[20]

//>> Start New Publisher Call
OnBeforeCreateVendor(Rec, IsHandled, ExitValue);
IF IsHandled THEN
  EXIT(ExitValue);
//<< End New Publisher Call
 
CheckForExistingRelationships(ContBusRel."Link to Table"::Vendor);
CheckIfPrivacyBlockedGeneric;
CheckCompanyNo;
RMSetup.GET;
.
.
```
 
New Publisher Event:
 
```
LOCAL [IntegrationEvent] OnBeforeCreateVendor(VAR Contact : Record Contact;VAR IsHandled : Boolean;VAR ExitValue : Code[20])
```

Please note that the return of the created Vendor No. was requested in #2644

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
