### ISSUE TITLE
[Event Request] Codeunit 5704 "TransferOrder-Post Shipment" – New Event “OnPostWIPItemJnlLineOnBeforeRunWithCheck"

### ISSUE THREAD

**Issue by Serenissima2** [microsoft/ALAppExtensions#7169]
Hello,

could you add a new publisher event in the following procedure inside Codeunit 5704 "TransferOrder-Post Shipment"?

    [Scope('OnPrem')]
    procedure PostWIPItemJnlLine(var TransLine3: Record "Transfer Line"; TransShptHeader2: Record "Transfer Shipment Header"; TransShptLine2: Record "Transfer Shipment Line")
    begin
        ItemJnlLine.Init();
        ItemJnlLine."Posting Date" := TransShptHeader2."Posting Date";
        ItemJnlLine."Document Date" := TransShptHeader2."Posting Date";
        ItemJnlLine."Document No." := TransShptLine2."Prod. Order No.";
        ItemJnlLine."Order Type" := ItemJnlLine."Order Type"::Production;
        ItemJnlLine."Order No." := TransShptLine2."Prod. Order No.";
        ItemJnlLine."External Document No." := TransShptHeader2."External Document No.";
        ItemJnlLine."Entry Type" := ItemJnlLine."Entry Type"::Output;
        ItemJnlLine."Item No." := TransShptLine2."Item No.";
        ItemJnlLine.Description := TransShptLine2.Description;
        ItemJnlLine."Shortcut Dimension 1 Code" := TransShptLine2."Shortcut Dimension 1 Code";
        ItemJnlLine."Shortcut Dimension 2 Code" := TransShptLine2."Shortcut Dimension 2 Code";
        ItemJnlLine."Source Code" := SourceCode;
        ItemJnlLine."Gen. Prod. Posting Group" := TransShptLine2."Gen. Prod. Posting Group";
        ItemJnlLine."Inventory Posting Group" := TransShptLine2."Inventory Posting Group";
        ItemJnlLine."Unit of Measure Code" := TransShptLine2."Unit of Measure Code";
        ItemJnlLine."Qty. per Unit of Measure" := TransShptLine2."Qty. per Unit of Measure";
        ItemJnlLine."Variant Code" := TransShptLine2."Variant Code";
        ItemJnlLine."Reason Code" := TransShptHeader2."Reason Code";
        ItemJnlLine."Order Line No." := TransShptLine2."Prod. Order Line No.";
        ItemJnlLine.Type := ItemJnlLine.Type::"Work Center";
        ItemJnlLine."No." := TransShptLine2."Work Center No.";
        ItemJnlLine."Routing No." := TransShptLine2."Routing No.";
        ItemJnlLine."Routing Reference No." := TransShptLine2."Routing Reference No.";
        ItemJnlLine."Source No." := TransShptHeader2."Source No.";
        ItemJnlLine."Source Type" := TransShptHeader2."Source Type";
        ItemJnlLine."Work Center No." := TransShptLine2."Work Center No.";
        ItemJnlLine."Operation No." := TransShptLine2."Operation No.";
        ItemJnlLine."WIP Quantity" := TransShptLine2."Quantity (Base)";
        if TransShptLine2."Return Order" then
            ItemJnlLine."WIP Quantity" := ItemJnlLine."WIP Quantity" * -1;
        ItemJnlLine."WIP Item" := TransShptLine2."WIP Item";
        ItemJnlLine."Subcontr. Purch. Order No." := TransShptLine2."Subcontr. Purch. Order No.";
        ItemJnlLine."Subcontr. Purch. Order Line" := TransShptLine2."Subcontr. Purch. Order Line";
        ItemJnlLine."Dimension Set ID" := TransShptLine2."Dimension Set ID";

        //>> Start New Publisher Call
        OnPostWIPItemJnlLineOnBeforeRunWithCheck(ItemJnlLine, TransShptHeader2,TransShptLine2); 
        //<< End New Publisher Call

        ItemJnlPostLine.RunWithCheck(ItemJnlLine);
    end;

New publisher event:

       LOCAL [IntegrationEvent] OnPostWIPItemJnlLineOnBeforeRunWithCheck(VAR ItemJnlLine: 
       Record "Item Journal Line";VAR TransShptHeader: Record "Transfer Shipment Header";VAR 
       TransShptLine: Record "Transfer Shipment Line)

Thanks! 
Fabio

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
