### ISSUE TITLE
[Event Request] Table 37 Sales Line, Function UpdateVATOnLines

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#7170]
Please add a new publisher event OnUpdateVATOnLinesOnAfterCalculateNewAmount ( in table 37 on function UpdateVATOnLines) as shown below:

![image](https://user-images.githubusercontent.com/64889775/82434818-b70a5880-9a93-11ea-88f4-65fde5c770a8.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATOnLinesOnAfterCalculateNewAmount(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; VATAmountLine: Record "VAT Amount Line"; VATAmountLineReminder: Record "VAT Amount Line"; NewAmountIncludingVAT:Decimal, VATAmount:decimal; var NewAmount: Decimal; var NewVATBaseAmount: Decimal,)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
