### ISSUE TITLE
[Event Request] Table 37 Sales Line, Function UpdateVATOnLines

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#7171]
Please add a new publisher event nUpdateVATOnLinesOnOnBeforeModifyVATAmountReminderLine ( in table 37 on function UpdateVATOnLines) as shown below:
![image](https://user-images.githubusercontent.com/64889775/82436242-cd191880-9a95-11ea-9c42-30f8518e339a.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATOnLinesOnOnBeforeModifyVATAmountReminderLine(SalesLine: Record "Sales Line"; var TempVATAmountLineRemainder: Record "VAT Amount Line"; VATAmount: Boolean; NewVATBaseAmount: decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
