### ISSUE TITLE
[Event Request] Table 39 Purchase Line, Function UpdateVATOnLines

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#7172]
Please add a new publisher event OnUpdateVATOnLinesOnAfterCalculateNewAmount ( in table 39 on function UpdateVATOnLines) as shown below:
![image](https://user-images.githubusercontent.com/64889775/82436839-bcb56d80-9a96-11ea-8ec5-e0acf5c5d326.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATOnLinesOnAfterCalculateNewAmount(var PurchaseLine: Record "Purchase Line"; PurchaseHeader: Record "Purchase Header"; VATAmountLine: Record "VAT Amount Line"; VATAmountLineReminder: Record "VAT Amount Line"; NewAmountIncludingVAT:Decimal, VATAmount:decimal; var NewAmount: Decimal; var NewVATBaseAmount: Decimal,)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
