### ISSUE TITLE
[Event Request] Table 39 Purchase Line, Function UpdateVATOnLines

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#7173]
Please add a new publisher event OnUpdateVATOnLinesOnOnBeforeModifyVATAmountReminderLine ( in table 39 on function UpdateVATOnLines) as shown below:

![image](https://user-images.githubusercontent.com/64889775/82437173-49602b80-9a97-11ea-8f96-2e12300c9c32.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATOnLinesOnOnBeforeModifyVATAmountReminderLine(PurchaseLine: Record "Purchase Line"; var TempVATAmountLineRemainder: Record "VAT Amount Line"; VATAmount: Boolean; NewVATBaseAmount: decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
