### ISSUE TITLE
[Event Request] Table 39 Purchase Line, Function CalcVATAmountLines

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#7174]
Please add a new publisher event OnUpdateVATOnLinesOnAfterCalculateNewAmount ( in table 39 on function CalcVATAmountLines) as shown below:

![image](https://user-images.githubusercontent.com/64889775/82438331-29316c00-9a99-11ea-89df-2066c2a621cf.png)

New publisher Event:
   [IntegrationEvent(false, false)]
    local procedure OnCalcVATAmountLinesOnBeforeVATAmountSumLine(PurchaseLine: Record "Purchase Line"; var VATAmountLine: Record "VAT Amount Line"; QtyType: Option General,Invoicing,Shipping)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
