### ISSUE TITLE
 [Event Request] Page 5104 Contact Picture - OnImportPictureBeforeStoreFile

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#7176]
Please add a new publisher event to the function `ImportPicture - OnAction()` as follows:
                
```
.
.
FileName := FileManagement.UploadFile(SelectPictureTxt,ClientFileName);
IF FileName = '' THEN
  EXIT;

//>> Start New Publisher Call
OnImportPictureBeforeStoreFile(Rec, FileName);
//<< End New Publisher Call
 
CLEAR(Image);
Image.IMPORTFILE(FileName,ClientFileName);
MODIFY(TRUE);
.
.
```
 
New Publisher Event:
 
```
LOCAL [IntegrationEvent] OnImportPictureBeforeStoreFile(VAR Contact : Record Contact;FileName : Text)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
