### ISSUE TITLE
[Event Modification] table 121 "Purch. Rcpt. Line" - OnBeforeInsertInvLineFromRcptLine()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#7182]
Could you please amend the insert() of the invoice line in InsertInvLineFromRcptLine() so it matches the pattern used in:

table 6661 "Return Receipt Line" InsertInvLineFromRetRcptLine()
table 6651 "Return Shipment Line" InsertInvLineFromRetShptLine()?

```
    procedure InsertInvLineFromRcptLine(var PurchLine: Record "Purchase Line")
    begin
            if "Sales Order No." = '' then
                PurchLine."Drop Shipment" := false
            else
                PurchLine."Drop Shipment" := true;

            // New IsHandled-Patter ...
            IsHandled := false;
            OnBeforeInsertInvLineFromRcptLine(Rec, PurchLine, PurchOrderLine, IsHandled);
            if not IsHandled then
                PurchLine.Insert();
            // ... New IsHandled-Patter
            OnAfterInsertInvLineFromRcptLine(PurchLine, PurchOrderLine, NextLineNo, Rec);

            ItemTrackingMgt.CopyHandledItemTrkgToInvLine(PurchOrderLine, PurchLine);

            NextLineNo := NextLineNo + 10000;
            if "Attached to Line No." = 0 then
                SetRange("Attached to Line No.", "Line No.");
        until (Next = 0) or ("Attached to Line No." = 0);
    end;
```

Publisher:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertInvLineFromRcptLine(var PurchRcptLine: Record "Purch. Rcpt. Line"; var PurchLine: Record "Purchase Line"; PurchOrderLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
        // added param IsHandled
    end;

This has also been requested for OnBeforeInsertInvLineFromShptLine(): https://github.com/microsoft/ALAppExtensions/issues/7181 

thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
