### ISSUE TITLE
Config. Template Management

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#7184]
At Codeunit Config. Template Management we have useless event OnBeforeUpdateWithSkipFields(var SkipFieldValidation : Boolean)

Can you add  TempDummyField parament by var, and RecRef parament, or make the function UpdateRecordWithSkipFields external.

Thank you)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
