### ISSUE TITLE
[Event Change] Report 493 - Carry Out Action Msg. - Req. - OnBeforePostReport

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#7185]
Hi AL-Team,

can you please add the global variable ReqWkshMakeOrders as var to Publisher OnBeforePostReport?

```
trigger OnPostReport()
    begin
        // OnBeforePostReport();
        OnBeforePostReport(ReqWkshMakeOrders);
    end;

```
```
[IntegrationEvent(TRUE, false)]
    // local procedure OnBeforePostReport()
    local procedure OnBeforePostReport(var ReqWkshMakeOrders: Codeunit "Req. Wksh.-Make Order")
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
