### ISSUE TITLE
Codeunit 2000020 DomiciliationJnlManagement "CreateDomiciliations" #5090

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#7186]
issue 5090 has been closed but it is not ok.

the function is just added als local function, it should be an event, the definition as event is missing:

[Scope('OnPrem')]
procedure ModifyPmtDiscDueDate(DomicJnlLine: Record "Domiciliation Journal Line")
var
    CustLedgEntry: Record "Cust. Ledger Entry";
begin
    with DomicJnlLine do begin
        CustLedgEntry.SetCurrentKey("Document No.");
        CustLedgEntry.SetRange("Document Type", "Applies-to Doc. Type");
        CustLedgEntry.SetRange("Document No.", "Applies-to Doc. No.");
        CustLedgEntry.SetRange("Customer No.", "Customer No.");
        if CustLedgEntry.FindLast then begin
            CustLedgEntry.Validate("Remaining Pmt. Disc. Possible", -"Pmt. Disc. Possible");
            CustLedgEntry.Validate("Pmt. Discount Date", "Posting Date");
            CustLedgEntry.Modify(true)
        end;
    end
end;

local procedure OnCreateDomiciliationsOnAfterSetFilters(var DomiciliationJournalLine: Record "Domiciliation Journal Line")
begin
end;

this is now not usable

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
