### ISSUE TITLE
[Event Request] Codeunit 99000793 - OnSetRecursiveLevelsOnItemBeforeModifyCompItem

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#7187]
Please add a new Integration Event OnSetRecursiveLevelsOnItemBeforeModifyCompItem in Codeunit 99000793 "Calculate Low-Level Code", Function SetRecursiveLevelsOnItem:

Code Adjustment in Fct. SetRecursiveLevelsOnItem:

````
             end;
+            OnSetRecursiveLevelsOnItemBeforeModifyCompItem(CompItem, IgnoreMissingItemsOrBOMs);
             CompItem.Modify();

````

Code for new Publisher Fct.:

````

+    [IntegrationEvent(false, false)]
+    local procedure OnSetRecursiveLevelsOnItemBeforeModifyCompItem(var CompItem: Record Item; IgnoreMissingItemsOrBOMs: Boolean)
+    begin
+    end;
````

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
