### ISSUE TITLE
[Event Request] Codeunit 17 Gen. Jnl.-Post Reverse - Reverse

### ISSUE THREAD

**Issue by Serenissima1** [microsoft/ALAppExtensions#7189]
Could you please add an event called OnPostReverse in the Reverse procedure of codeunit 17 as follows?

    procedure Reverse(var ReversalEntry: Record "Reversal Entry"; var ReversalEntry2: Record "Reversal Entry")

        [...]

        if FALedgEntry.FindSet then
            repeat
                FAInsertLedgEntry.CheckFAReverseEntry(FALedgEntry)
            until FALedgEntry.Next = 0;

        if MaintenanceLedgEntry.FindFirst then
            repeat
                FAInsertLedgEntry.CheckMaintReverseEntry(MaintenanceLedgEntry)
            until FALedgEntry.Next = 0;

        FAInsertLedgEntry.FinishFAReverseEntry(GLReg);

        if not TempCustLedgEntry.IsEmpty then
            Error(ReversalMismatchErr, CustLedgEntry.TableCaption);
        if not TempVendLedgEntry.IsEmpty then
            Error(ReversalMismatchErr, VendLedgEntry.TableCaption);
        if not TempEmployeeLedgerEntry.IsEmpty then
            Error(ReversalMismatchErr, EmployeeLedgerEntry.TableCaption);
        if not TempBankAccLedgEntry.IsEmpty then
            Error(ReversalMismatchErr, BankAccLedgEntry.TableCaption);

        OnReverseOnBeforeFinishPosting(ReversalEntry, ReversalEntry2, GenJnlPostLine, GLReg);

        GenJnlPostLine.FinishPosting(GenJnlLine);

        if GLReg2."No." <> 0 then
            if GLReg2.Find then begin
                GLReg2.Reversed := true;
                GLReg2.Modify();
            end;

        DeleteReversalEntries(TransactionKey);

        UpdateAnalysisView.UpdateAll(0, true);

        //>> Start New Publisher Call
        OnAfterReverse(GLReg);
        //<< End New Publisher Call
    end;

New publisher event

    local procedure OnAfterReverse(GLRegister: Record  "G/L Register");

Thanks,
Luca

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
