### ISSUE TITLE
[EventRequest] CU 391 OnBeforeTransferShptHeaderModify

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/ALAppExtensions#719]
Hi,

please add a new event in CU 391 for handling the modifies also on Transfer Shipment Header

`LOCAL [IntegrationEvent] OnBeforeTransferShptHeaderModify(VAR TransferShptHeader : Record "Transfer Shipment Header";FromTransferShptHeader : Record "Transfer Shipment Header")
`
Thank you
S.

**Comment by AlexanderYakunin** [comment]
COD391 is not intended for Edit of Transfer Shipment Header.

**Comment by sgiordy** [comment]
@AlexanderYakunin in the Italian localization YES... CU391 is intended also for editing of transfer shipment.

![cu](https://user-images.githubusercontent.com/17341714/50991684-98966380-1515-11e9-9554-05cdee5ab87d.png)
