### ISSUE TITLE
[EnumRequest] Table Prod. Order Routing Line - Field Routing Status

### ISSUE THREAD

**Issue by frobiii** [microsoft/ALAppExtensions#7191]
Can you please change the field "Routing Status" into an extensible enum. 
Thank you.

**Comment by AlexanderYakunin** [comment]
Why do you ask? This is already implemented.

**Comment by frobiii** [comment]
> Why do you ask? This is already implemented.

which release? i just updated my container - still an option

**Comment by AlexanderYakunin** [comment]
We implement Enums in Master (=17x). This enum have been implemented after release of 16.0 and only available in Master.
