### ISSUE TITLE
Enum Request / Table 5080 / Field Type

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#7194]
Hello, can you please convert the following Fields into ENUM:

Table 5080 To-do: Field 8 Type

Thanks

Regards

**Comment by bgonzalez-ib** [comment]
Sorry, also we would like to make it Extensible.

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
