### ISSUE TITLE
Parameters are mixed up "OnBeforeCommonBalancing", CU "Inventory Profile Offsetting"

### ISSUE THREAD

**Issue by AndreasGloeckner** [microsoft/ALAppExtensions#7195]
Hello,

according to the AL Repo, bugs related to the Base App can be posted here as well.

In the codeunit 99000854 "Inventory Profile Offsetting" is a publisher with the signature:

`local procedure OnBeforeCommonBalancing(var TempSKU: Record "Stockkeeping Unit" temporary; var DemandInvtProfile: Record "Inventory Profile"; var SupplyInvtProfile: Record "Inventory Profile"; PlanningStartDate: Date; ToDate: Date)`

First **DemandInvtProfile**, second **SupplyInvtProfile**, but the publisher is called with

`OnBeforeCommonBalancing(TempSKU, SupplyInvtProfile, DemandInvtProfile, PlanningStartDate, ToDate);`

The parameters are switched and I do not see any reason why.

Please tell me, if Github is the right way to report this bug and if it's really one :)

Thanks

Andreas

**Comment by AndreasGloeckner** [comment]
Is it right that this issue is labeled as "event-request"? It seems more like a bug.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
