### ISSUE TITLE
[Event Request] Table Cust. Ledger Entry - OnBeforeShowDoc

### ISSUE THREAD

**Issue by Zoltero** [microsoft/ALAppExtensions#7197]
In table 21 Cust. Ledger Entry is a function to show document. This function has a trigger OnAfterShowDoc, but this gives no control to overrule the page to be loaded.

Please add a OnBeforeShowDoc trigger as described below:

IsHandled: Boolean;
isPageCalled: Boolean;

OnBeforeShowDoc(Rec,IsPageCalled,IsHandled);
IF IsHandled then
  Exit(IsPageCalled);

Thanks,
Morten

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
