### ISSUE TITLE
[Event Request]. Codeunit 1002 Job Create-Invoice

### ISSUE THREAD

**Issue by simcrest** [Microsoft/ALAppExtensions#720]
Please add the following events in CreateSalesInvoiceJobTask function:
![image](https://user-images.githubusercontent.com/15910725/50525534-f94f8600-0aa9-11e9-9e57-4caac095d16a.png)

Also one here:
![image](https://user-images.githubusercontent.com/15910725/50525550-197f4500-0aaa-11e9-90fa-773745c7f8e5.png)

**Comment by AlexanderYakunin** [comment]
1. We already have event OnBeforeModifySalesHeader(SalesHeader,Job) in procedure CreateSalesHeader
2. Will be implemented
