### ISSUE TITLE
Already done for https://github.com/microsoft/ALAppExtensions/issues/6866.

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#7200]
Already done for https://github.com/microsoft/ALAppExtensions/issues/6866.

_Originally posted by @StanPesotskiy in https://github.com/microsoft/ALAppExtensions/issues/7046#issuecomment-630023343_

**Comment by fvanderhek** [comment]
Issue #7046 is about Sell-To Contact No. and not about Bill-To Contact No. So could you please review issue 7046 again because we really need the requested publisher...
Thanx.

**Comment by StanPesotskiy** [comment]
I have posted the answer in https://github.com/microsoft/ALAppExtensions/issues/7046
