### ISSUE TITLE
[Event Request] Page 42 Sales Order - OnAfterValidateShipToOptions

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#7202]
Requesting a new Event Publisher on Page 42 Sales Order

Event
`OnAfterValidateShipToOptions(VAR Rec : Record "Sales Header", ShipToOptions : Option "Default (Sell-to Address)","Alternate Shipping Address","Custom Address")`

**Code**
## ShippingOptions - OnValidate()
```
CASE ShipToOptions OF
  ShipToOptions::"Default (Sell-to Address)":
    BEGIN      
      VALIDATE("Ship-to Code",'');            
      CopySellToAddressToShipToAddress;
    END;
  ShipToOptions::"Alternate Shipping Address":
    BEGIN
      ShipToAddress.SETRANGE("Customer No.","Sell-to Customer No.");
      ShipToAddressList.LOOKUPMODE := TRUE;
      ShipToAddressList.SETTABLEVIEW(ShipToAddress);
      IF ShipToAddressList.RUNMODAL = ACTION::LookupOK THEN BEGIN
        ShipToAddressList.GETRECORD(ShipToAddress);
        VALIDATE("Ship-to Code",ShipToAddress.Code);
        IsShipToCountyVisible := FormatAddress.UseCounty(ShipToAddress."Country/Region Code");
      END ELSE      
        ShipToOptions := ShipToOptions::"Custom Address";
    END;
  ShipToOptions::"Custom Address":
    BEGIN
      VALIDATE("Ship-to Code",''); 
      IsShipToCountyVisible := FormatAddress.UseCounty("Ship-to Country/Region Code");
    END;
END;
```
**>>> New Code**
```
OnAfterValidateShipToOptions(Rec, ShipToOptions);
```
**<<< New Code End**

In Our Solution we handle the Ship-To Code because it cannot be empty in our solution. We beed this to handle Warehouse Shipments per ship-to Address. Can you please add this publisher?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
