### ISSUE TITLE
[Parameter Request] GenJnlPostLine.Codeunit.al (codeunit 12 "Gen. Jnl.-Post Line"), OnAfterVendLedgEntryInsert

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7203]
Hi MS,
Please help us in migrating our verticalized solution by adding below parameter by var in event **OnAfterVendLedgEntryInsert** in **GenJnlPostLine.Codeunit.al** codeunit.

Current Signature
![image](https://user-images.githubusercontent.com/33481576/82892315-e4ac4180-9f6c-11ea-8a73-58bf7f0ea51b.png)

Requested Signature
![image](https://user-images.githubusercontent.com/33481576/82892422-073e5a80-9f6d-11ea-953e-474f270ce29b.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
