### ISSUE TITLE
[EventRequest] FormatAddress.Codeunit.al

### ISSUE THREAD

**Issue by CptBlaubart** [microsoft/ALAppExtensions#7207]
Please implement more events into FormatAddress just like you already did for Purchase- and Sales-Documents.

At the moment, I need an event for all the reminders available. Sooner or later ppl. will request events for every function addressed from a Report in there. Don't stop half way.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
