### ISSUE TITLE
[EventRequest] Page 1042 Copy Job Planning Lines - OnCopyJobPlanningLinesOnBeforeCopyJobPlanningLines

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#7209]
Requesting a new event publisher on Page 1042 Copy Job Planning Lines

Event
`OnCopyJobPlanningLinesOnBeforeCopyJobPlanningLines(SourceJobNo : Code [20], SourceJobTaskNo : Code [20], PlanningLineType : Option "Budget+Billable,Budget,Billable", FromDate : Date, ToDate : Date, TargetJobNo : Code [20],TargetJobTaskNo : Code [20], CopyQuantity : Boolean)`

**Code**
## OnQueryClosePage(CloseAction : Action None) : Boolean
```
IF CloseAction IN [ACTION::OK,ACTION::LookupOK] THEN BEGIN
  ValidateUserInput;
  CopyJob.SetCopyQuantity(CopyQuantity);
  CopyJob.SetCopyJobPlanningLineType(PlanningLineType);
  CopyJob.SetJobTaskDateRange(FromDate,ToDate);
```
**>>> New Code**
```
  OnCopyJobPlanningLinesOnBeforeCopyJobPlanningLines(SourceJobNo,SourceJobTaskNo,PlanningLineType,FromDate,ToDate,TargetJobNo,TargetJobTaskNo,CopyQuantity);
```
**<<< New Code End**
```
  CopyJob.CopyJobPlanningLines(SourceJobTask,TargetJobTask);
  MESSAGE(Text001);
END
```

Based om 3 additional boolean request page setup fields we need to copy additional details/records based on this action. With this publisher we have that flexibility. Can you please add this publisher here?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
