### ISSUE TITLE
[Function Expose] Codeunit 1297 Http Web Request Mgt.

### ISSUE THREAD

**Issue by kwettermann** [Microsoft/ALAppExtensions#721]
Hi!

Is it possible to expose the following methods?

- Initialize
- SetMethod
- SetContentType
- SetReturnType
- AddHeader
- AddBodyBlob
- GetResponseStream

**Comment by IhorHandziuk** [comment]
Thank you for your request. 
Please, consider using native AL type HttpRequestMessage instead (if it's possible) as recommended in issue #315

**Comment by IhorHandziuk** [comment]
Closing assuming the native type was sufficient enough.
