### ISSUE TITLE
[Event Request] Codeunit 392 "Reminder-Make", codeunt 393 "Reminder-Issue", table 295 "Reminder Header"

### ISSUE THREAD

**Issue by adrogin** [microsoft/ALAppExtensions#7211]
Issue #1485 added some agility to handling blocked customers. Could you extent this logic to reminders as well? When a customer is blocked and no invoices or shipments can be created for this account, still there should be a possibility to issue a reminder for the same customer.

Codeunit 392 "Reminder-Make", function MakeReminder
```
if MakeDoc and (CustAmount > 0) and (CustAmountLCY(CurrencyCode, CustAmount) >= ReminderTerms."Minimum Amount (LCY)") then begin
    MakeDoc := Blocked <> Blocked::All;
    OnBeforeCheckCustomerBlocked("No.", MakeDoc);
    if not MakeDoc then
        exit(false);
```
Event publisher signature:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckCustomerBlocked(CustomerNo: Code[20]; var MakeDoc: Boolean)
begin
end;
```

Codeunt 393 "Reminder-Issue", function CheckIfBlocked
```
if Customer."Privacy Blocked" then
    Error(Text004, Customer.FieldCaption("Privacy Blocked"), Customer."Privacy Blocked", Customer.TableCaption, CustomerNo);

OnBeforeCheckCustomerBlocked(CustomerNo, IsHandled);
if not IsHandled then
    if Customer.Blocked = Customer.Blocked::All then
        Error(Text004, Customer.FieldCaption(Blocked), Customer.Blocked, Customer.TableCaption, CustomerNo);
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckCustomerBlocked(CustomerNo: Code[20]; IsHandled: Boolean)
begin
end;
```

Table 295 "Reminder Header", "Customer No." - OnValidate
```
if Cust."Privacy Blocked" then
    Cust.CustPrivacyBlockedErrorMessage(Cust, false);
                
OnBeforeCheckCustomerBlocked(CusomerNo, IsHandled);
if not IsHandled then
    if Cust.Blocked = Cust.Blocked::All then
        Cust.CustBlockedErrorMessage(Cust, false);
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckCustomerBlocked(CustomerNo: Code[20], var IsHandled: Boolean);
begin
end;
```
As an alternative to publishing duplicated events in multiple objects, the same could be achieved if reminders and finance charges were incorporated in the existing customer check - if the function CheckBlockedCustOnDocs on the Customer table could be extended to include the mentioned documents.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
