### ISSUE TITLE
[Event Request] TAB36 - OnBeforeGetShippingTime

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#7213]

**Comment by SKeiler** [comment]
Hello,

we Need the following Event in TAB36.
![image](https://user-images.githubusercontent.com/45033081/82990647-caba3f80-9ffc-11ea-9a17-3b23dcb37235.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
