### ISSUE TITLE
Contact table

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#7215]
is it possible to have the fields
first name
middle name
surname
extended to 50?

these fields are now 30 but the correspondig fields in CRM are 50.
so when contacts are imported from CRM then the fields get cut off.
it is not logical to have to make new fields in a table extension and change the default CRM field mapping to have the full name.

**Comment by AlexanderYakunin** [comment]
We are unfortunately not allowed to change field length anymore, see test log:

App\Views\AT\BaseApp\Contact.Table.al(335,21): error AS0004: Field 'First Name' has changed type from 'Text[30]' to 'Text[50]'. Type changes are not allowed.
App\Views\AT\BaseApp\Contact.Table.al(345,21): error AS0004: Field 'Middle Name' has changed type from 'Text[30]' to 'Text[50]'. Type changes are not allowed.
App\Views\AT\BaseApp\Contact.Table.al(355,21): error AS0004: Field 'Surname' has changed type from 'Text[30]' to 'Text[50]'. Type changes are not allowed.
