### ISSUE TITLE
[Application Bug] Page 9179 "Application Area" must be editable

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#7216]
Page 9179 "Application Area" is set to Editable = false;
There's some code to the 'Selected' field that calls 'CurrPage.Update(true);'
'OnQueryClosePage' also performs a 'TrySave' operation.

However, none of the above code is actually called, since the page is not editable. I'm looking for a solution to allow users to enable/disable applicationAreas (next to the normal 'User Experience' feature on the company information). Isn't the page meant to be editable instead (both OnPrem and Saas)?

Also see https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=533310825242624 where it seems like in the past the page used to be editable. I'd like to avoid having to duplicate standard pages ...

Duplicating the page fails on GetApplicationAreaBuffer / TrySaveApplicationAreaCurrentCompany not available for Cloud deployment too. Couldn't find alternative functions in the Facade codeunit.

**Comment by fvet** [comment]
@StanPesotskiy Is this 'feature request' considered for one of the next releases, and if yes, are you planning to allow disabling ApplicationAreas? It would be nice if the user would have more fine-grained access to disable certain applicationAreas (within the Experience Tier set). This would allow companies to hide / disable areas that are not used and **simplies the UI a lot** removing redundant controls.

As an ISV, we're looking into offering our 'full' solution to a variety of customers / industries / niche markets that don't want to be bothered the full set of features. Part of the issue is solved by offering solutions as separate extensions, others features can be hidden using profiles, but it would be nice if we could create custom 'Experience Tiers' (on top of the standard ones) to focus on different types of customers. In the end, this customer can then disable what is not applicable to their business needs.

Or do we need an Experience idea?

**Comment by grobyns** [comment]
Hi,

I don't know of any plans to open up for individual selection of application areas by users. 

Regarding the ability to create custom experience tiers, that is already possible. You need to add a field in the "Experience Tier Setup" table and by subscribing to the OnSetExperienceTier event you can set the application areas for your new Experience Tier.

br/Gert

**Comment by fvet** [comment]
I was not aware of the option to create new Experience Tiers, thanks for the hint! (https://github.com/microsoft/ALAppExtensions/issues/8444)

Nevertheless my guess is we'll eventually end up in creating various combinations of application areas, where eventually customers should have the option to disable application areas to limit the no. of combinations.

Example
- Basic
- Essentials
- Transport (new experience tier)
- Warehouse (possible future experience tier)
- Forwarding (possible future experience tier)
- Transport + Warehouse (possible future experience tier)
- Transport + Warehouse + Forwarding (possible future experience tier)
- ...

It would be better if we had 
- Basic 
- Essentials 
- Navitrans Basic (new experience tier) - with the option to finetune access by disabling Application Areas
- Navitrans Advanced (new experience tier) - with the option to finetune access by disabling Application Areas

**Comment by StanPesotskiy** [comment]
For the new features please submit a product suggestion on https://aka.ms/bcideas

**Comment by fvet** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=98f88069-8467-eb11-8fed-0003ff457c93
