### ISSUE TITLE
[extensibility-enhancement] - Codeunit 90 "Purch.-Post" - OnBeforeDivideAmount

### ISSUE THREAD

**Issue by SPinkow** [microsoft/ALAppExtensions#7219]
Hi,

could you please add a var for the variable "PurchLineQty" like in the analog Publisher OnBeforeDivideAmount in Codeunit 80 in order to access the Parameter as CallByReference.

Currently the publisher looks like the following:
`
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDivideAmount(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping; PurchLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary)
    begin
    end;
`

In the end it should be 
`
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDivideAmount(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping;`**var**` PurchLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary)
    begin
    end;
`

Thanks for a consideration in the future.
Best Regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
