### ISSUE TITLE
[Request for external] Page 510 "Blanket Purchase Order Subform" function DeltaUpdateTotals

### ISSUE THREAD

**Issue by SPinkow** [microsoft/ALAppExtensions#7221]
Hi,

could you please remove the local keyword for function DeltaUpdateTotals in Page 510 "Blanket Purchase Order Subform" in order to update the totals from extended fields too like in several other standard subforms in sales and purchase.

Thanks for a consideration in the future.
Best Regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
