### ISSUE TITLE
[Event Request] Codeunit 398 Sales Tax Calcuted (OnBeforeCalculateTax and OnBeforenitSalesTaxLines)

### ISSUE THREAD

**Issue by MateoPadiernaB** [microsoft/ALAppExtensions#7222]
Hi,
I'm a Colombian developer and in my region we should use the W1 version of Business Central. 
That's ok, but,  we always do a customization in the baseapp for a correct calculation of the tax in my country. 
So, I hope that with the events that i'm requiring, the customization isn't necessary anymore and we could use a baseapp without them.

**Comment by RomanZanizdra** [comment]
Hi @MateoPadiernaB .
Do you need any parameters in events? Please be precise in description of what and where do you want to get.

**Comment by RomanZanizdra** [comment]
Hi @MateoPadiernaB .
Any update from your side?

**Comment by MateoPadiernaB** [comment]
> Hi @MateoPadiernaB .
> Any update from your side?

Yes. I'm here. I need to filter the taxes based on the fields in Table Tax detail  any combination of Maximum Amount/Qty, Tax Below Maximum, Tax Above Maximum.

**Comment by RomanZanizdra** [comment]
Hi @MateoPadiernaB .
As I mentioned above we need clear explanation where particularly (lines of code) insert the event and its' parameters. Please take a look, for example, at this event request https://github.com/microsoft/ALAppExtensions/issues/7323 and give us similar description.

**Comment by RomanZanizdra** [comment]
Hi @MateoPadiernaB . Just a gentle ping.

**Comment by MateoPadiernaB** [comment]
Hi @RomanZanizdra , sorry for my lateness, I had spam problems with my notifications. I'm going to publish your request tomorrow.
Thank for your help.

**Comment by MateoPadiernaB** [comment]
Hi @romank-msft . I'm going to close this issue and plan it with my team, thanks for you help.
