### ISSUE TITLE
[Request for External] Table 36 "Sales Header" - CopyShipToCustomerAddressFieldsFromCustomer

### ISSUE THREAD

**Issue by robinfjelldal** [microsoft/ALAppExtensions#7223]
Hi, 
would like to know if its possible to get CopyShipToCustomerAddressFieldsFromCustomer global.
Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
