### ISSUE TITLE
[Event Enhancement] Codeunit 80 - OnAfterReturnRcptLineInsert

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/ALAppExtensions#724]
The OnAfterReturnRcptLineInsert event has missing parameters that are crucial to the posting process and must be available.

So far, the event has the following parameters:

| Var |        Name        | DataType |        Subtype        | Length |
|-----|--------------------|----------|-----------------------|--------|
| Yes | ReturnRcptLine     | Record   | Return Receipt Line   |        |
| No  | ReturnRcptHeader   | Record   | Return Receipt Header |        |
| No  | SalesLine          | Record   | Sales Line            |        |
| No  | ItemShptLedEntryNo | Integer  |                       |        |
| No  | WhseShip           | Boolean  |                       |        |
| No  | WhseReceive        | Boolean  |                       |        |
| No  | CommitIsSuppressed | Boolean  |                       |        |

It would be desirable if there were the following parameters:

| Var |        Name        | DataType |        Subtype        | Length |
|-----|--------------------|----------|-----------------------|--------|
| Yes | ReturnRcptLine     | Record   | Return Receipt Line   |        |
| No  | ReturnRcptHeader   | Record   | Return Receipt Header |        |
| No  | SalesCrMemoHeader | Record   | Sales Cr.Memo Header |        |
| No  | SalesLine          | Record   | Sales Line            |        |
| No  | ItemShptLedEntryNo | Integer  |                       |        |
| No  | WhseShip           | Boolean  |                       |        |
| No  | WhseReceive        | Boolean  |                       |        |
| No  | CommitIsSuppressed | Boolean  |                       |        |

**Comment by AlexanderYakunin** [comment]
SalesCrMemoHeader is not used in procedure InsertReturnRcptLine, why do you want to add it?

**Comment by esuarkfalo** [comment]
"SalesCreditMemo" is a global variable filled when invoicing a "Credit Memo" or a Return Order". Using the event mentioned above and if the invoicing is used (only then the global variable will be filled with values) we can directly assign the "Return Receipt Line" to the new "Credit Memo Line" (having the same line number as the "SalesLine") for further Analysis in separted new tables. We store the additional data (in our new tables) only if the variable "SalesCreditMemo" is filled.

There are several new oder changed events in the posting codeunits for sales, purchase and service we use for this functionality.
