### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnAfterPostSalesDoc - Add Parameters: WhseShip and WhseReceiv

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#7243]
Could you please extend the Event OnAfterPostSalesDoc to get access to the following two global variables:
- WhseShip 
- WhseReceiv
and to the  CustLedgerEntry, 
that the new Event Definition would be: 
```
[IntegrationEvent(false, false)]
local procedure OnAfterPostSalesDoc(var SalesHeader: Record "Sales Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var CustLedgerEntry: Record "Cust. Ledger Entry"; var SalesShptHdrNo: Code[20]; RetRcpHdrNo: Code[20]; SalesInvHdrNo: Code[20]; SalesCrMemoHdrNo: Code[20]; CommitIsSuppressed: Boolean; InvtPickPutaway: Boolean; WhseShip: Boolean; WhseReceiv: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
