### ISSUE TITLE
[EventRequest] Job.Table.al (table 167 Job)

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7244]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **Job.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83132327-da21b180-a0fe-11ea-9700-b6de3f30f2f7.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83132393-f6255300-a0fe-11ea-8f64-ca7c3e64734e.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83132450-0ccbaa00-a0ff-11ea-950b-374e59399504.png)

Thanks
SUD

**Comment by StanPesotskiy** [comment]
Use the event OnBeforeValidateShortcutDimCode() created for https://github.com/microsoft/ALAppExtensions/issues/6315
