### ISSUE TITLE
[EnumRequest] JobLedgerEntry.Table.al (table 169 "Job Ledger Entry")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7246]
Hi MS,
Please help us in migrating our verticalized solution by adding below **enums** in **JobLedgerEntry.Table.al** Table.

**Field "Type"**
![image](https://user-images.githubusercontent.com/33481576/83133821-0ccca980-a101-11ea-9c67-b5b9b864421c.png)

**Field "Entry Type"**
![image](https://user-images.githubusercontent.com/33481576/83133972-4ac9cd80-a101-11ea-929b-20138108be15.png)

Thanks
SUD

**Comment by AlexanderYakunin** [comment]
We implement enums in Master only, therefore recently implemented enums will not be available in BC 16 CU's. They are available in Insider builds and will be part of BC 17 release. This event already implemented.
