### ISSUE TITLE
[EnumRequest] JobJournalLine.Table.al (table 210 "Job Journal Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7247]
Hi MS,
Please help us in migrating our verticalized solution by adding below enums in **JobJournalLine.Table.al** Table.

**Field "Type"**
![image](https://user-images.githubusercontent.com/33481576/83134676-5073e300-a102-11ea-96b2-c5e6042e27d0.png)

**Field "Entry Type"**
![image](https://user-images.githubusercontent.com/33481576/83134737-68e3fd80-a102-11ea-9bac-dc0e44af4cf9.png)

Thanks
SUD

**Comment by NKarolak** [comment]
"Entry Type" was already handled here: https://github.com/microsoft/ALAppExtensions/issues/6165

**Comment by SUD-D365** [comment]
Is it published in any existing build or version of BC?

**Comment by NKarolak** [comment]
As far as I know, not yet in any released BC 16 version, but likely in the BC insider version (either next CU of BC 16, or BC 17). You'd need to check that yourself.

**Comment by AlexanderYakunin** [comment]
We implement enums in Master only, therefore recently implemented enums will not be available in BC 16 CU's. They are available in Insider builds and will be part of BC 17 release.
