### ISSUE TITLE
[EventRequest] RequisitionLine.Table.al (table 246 "Requisition Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7248]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **RequisitionLine.Table.al** Table.

Standard Code (Screenshot from **SetReplenishmentSystemFromProdOrder** )
![image](https://user-images.githubusercontent.com/33481576/83135140-093a2200-a103-11ea-94ad-5f84fa326392.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83135218-25d65a00-a103-11ea-8932-ab4a3628a823.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83135298-3d154780-a103-11ea-896a-aedcda3f6a3d.png)
![image](https://user-images.githubusercontent.com/33481576/83135318-48687300-a103-11ea-916b-ae12ccd0c336.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
