### ISSUE TITLE
[EventRequest] VatAmountLine.Table.al (table 290 "VAT Amount Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7249]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **VatAmountLine.Table.al** Table.

Standard Code (Screenshot from **UpdateLines** )
![image](https://user-images.githubusercontent.com/33481576/83138973-3be71900-a109-11ea-9b7c-b0bd35833178.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83139009-4ef9e900-a109-11ea-951d-fa1c28e25587.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83139039-5de09b80-a109-11ea-98a5-fc39e70be575.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
