### ISSUE TITLE
[EventRequest] VatAmountLine.Table.al (table 290 "VAT Amount Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7250]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **VatAmountLine.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83139267-b4e67080-a109-11ea-8af9-c215256506d1.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83139320-cdef2180-a109-11ea-83bb-19aecb6db302.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83139378-e3fce200-a109-11ea-877b-421484051ea8.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
