### ISSUE TITLE
[Event Request] Pages 41, 43, 49, 50, 51, 52, 507 and 6640 - OnBeforeValidateShipToOptions

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#7251]
Please add for all pages containing the ShipToOptions the same logic as for sales orders, especially the event OnBeforeValidateShipToOptions.

That is the structure of page 42 (Sales Order), which should be transfered to all pages using the ShipToOptions logic: 
![grafik](https://user-images.githubusercontent.com/2485163/83143043-a12f1000-a0f1-11ea-8589-d5d04d42fdbf.png)

Signature: 
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateShipToOptions(SalesHeader: Record "Sales Header"; ShipToOptions: Option "Default (Sell-to Address)","Alternate Shipping Address","Custom Address")
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
