### ISSUE TITLE
[EventRequest] IssuedReminderLine.Table.al (table 298 "Issued Reminder Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7253]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **IssuedReminderLine.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83228062-33dbb780-a1a3-11ea-9845-e61c150e847b.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83228094-4950e180-a1a3-11ea-9942-5e9eab122b59.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83228142-65548300-a1a3-11ea-981e-b95a5fbac0d4.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
