### ISSUE TITLE
[EventRequest] IssuedReminderLine.Table.al (table 298 "Issued Reminder Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7254]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **IssuedReminderLine.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83228280-a187e380-a1a3-11ea-80b7-04b29aa7795f.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83228306-b5cbe080-a1a3-11ea-9e20-97360b9cb4fe.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83228345-ca0fdd80-a1a3-11ea-86c2-95d9c6bf0be1.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
