### ISSUE TITLE
[EventRequest] SalesTaxCalculate.Codeunit.al (codeunit 398 "Sales Tax Calculate")

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#7255]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in SalesTaxCalculate.Codeunit.al codeunit.

Standard Code (Screenshot from CalculateTax)
![image](https://user-images.githubusercontent.com/66109755/83231076-9462f880-a193-11ea-9e88-4d657198c968.png)

Modified Code
![image](https://user-images.githubusercontent.com/66109755/83231484-384ca400-a194-11ea-9a07-fae321f0c28e.png)

Event Signature
![image](https://user-images.githubusercontent.com/66109755/83231670-89f52e80-a194-11ea-9b2e-d30a34f8a460.png)

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
