### ISSUE TITLE
[EventRequest] FinanceChargeMemoLine.Table.al (table 303 "Finance Charge Memo Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7256]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **FinanceChargeMemoLine.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83231693-8ae48b00-a1a9-11ea-9f5a-b4c218e82ec1.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83231730-9cc62e00-a1a9-11ea-8319-1e7c3d83335e.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83231784-b36c8500-a1a9-11ea-8cb5-d42d2e418cf1.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SUD-D365** [comment]
Any update on this event?

Thanks
SUD

**Comment by SUD-D365** [comment]
HI There,

I think the published event in Master branch have wrong second parameter.
![image](https://user-images.githubusercontent.com/33481576/87268318-ae5c5e80-c4e7-11ea-800b-8970d531b8e8.png)

It should be record parameter of Table 302 (Finance ChargeMemo Header).
Kindly Update!!

Thanks
SUD

**Comment by SUD-D365** [comment]
@bc-ghost 
@StanPesotskiy

**Comment by StanPesotskiy** [comment]
Please create a new request. Don't forget to mention the precise name of the object and the event. 
Please always put all details in text instead of screenshots.
