### ISSUE TITLE
[EventRequest] IssuedFinChargeMemoLine.Table.al (table 305 "Issued Fin. Charge Memo Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7257]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **IssuedFinChargeMemoLine.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83232594-0d217f00-a1ab-11ea-9460-e85b54fc407f.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83232646-1f032200-a1ab-11ea-9aa2-b26b80fe3792.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83232742-45c15880-a1ab-11ea-99a3-530bfaa25b9a.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
