### ISSUE TITLE
[EventRequest] IssuedFinChargeMemoLine.Table.al (table 305 "Issued Fin. Charge Memo Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7258]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **IssuedFinChargeMemoLine.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83232828-6a1d3500-a1ab-11ea-8b87-aaacc0a060b0.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83232869-7a351480-a1ab-11ea-8825-a29d2c0786af.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83232911-8c16b780-a1ab-11ea-9270-4b3a9b481726.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
