### ISSUE TITLE
[EnumRequest] ApprovalEntry.Table.al (table 454 "Approval Entry")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7259]
Hi MS,
Please help us in migrating our verticalized solution by adding below Enum in **ApprovalEntry.Table.al** Table.

**Field Status**
![image](https://user-images.githubusercontent.com/33481576/83233258-13fcc180-a1ac-11ea-8cba-1a1ce789a3c0.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
