### ISSUE TITLE
[EnumRequest] JobPlanningLine.Table.al (table 1003 "Job Planning Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7264]
Hi MS,
Please help us in migrating our verticalized solution by adding below Enum in **JobPlanningLine.Table.al** Table.

**Field "Type"**
![image](https://user-images.githubusercontent.com/33481576/83236876-e286f480-a1b1-11ea-9b37-f6830dd26920.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
