### ISSUE TITLE
[EventRequest] Contact.Table.al (table 5050 Contact)

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7265]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **Contact.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83237182-67720e00-a1b2-11ea-85b0-f5375b2eeb9c.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83237467-97b9ac80-a1b2-11ea-8dd7-353b7cb4afaa.png)

Event Signature
![Uploading image.png…]()

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
