### ISSUE TITLE
[EventRequest] SegmentLine.Table.al (table 5077 "Segment Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7266]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **SegmentLine.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83237868-32b28680-a1b3-11ea-916c-eb3b600ee871.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83237955-4fe75500-a1b3-11ea-8cf4-de6bb3530749.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83238008-64c3e880-a1b3-11ea-9188-8717ec97c4a9.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
