### ISSUE TITLE
[EventRequest] InventoryAdjmtEntryOrder.Table.al (table 5896 "Inventory Adjmt. Entry (Order)")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7267]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **InventoryAdjmtEntryOrder.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83238324-e87dd500-a1b3-11ea-9462-5be0caba3d5c.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83238398-021f1c80-a1b4-11ea-82cb-06856082d105.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83238467-19f6a080-a1b4-11ea-8712-e733e8e584a3.png)
![image](https://user-images.githubusercontent.com/33481576/83238513-2975e980-a1b4-11ea-98b4-b70c92b977f1.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
