### ISSUE TITLE
[EventRequest] InternalMovementHeader.Table.al (table 7346 "Internal Movement Header")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7268]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **InternalMovementHeader.Table.al** Table.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83238805-97baac00-a1b4-11ea-9cce-7e96c21c5354.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83238892-b6b93e00-a1b4-11ea-94f6-0ebce788b7b5.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83238968-cc2e6800-a1b4-11ea-82a4-05ae7e018b4f.png)
![image](https://user-images.githubusercontent.com/33481576/83239013-d8b2c080-a1b4-11ea-9cf1-b755c840a026.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SUD-D365** [comment]
Hi There,

I think you missed to pass **Rec** in event parameter.
Kindly update!!

Thanks
SUD
