### ISSUE TITLE
[extensibility-enhancement] - Page 9 Languages is not extensible

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#7271]
Please make Page 9 Languages extensible.

We want to add an action to the languages pages to create or data in our own tables based on the selected language record.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
