### ISSUE TITLE
[Event Request] codeunit 5642 "FA Reclass. Transfer Line" in procedure FAReclassLine

### ISSUE THREAD

**Issue by Djordje-Arsic** [microsoft/ALAppExtensions#7274]
Hello,

We would like to have an option to recalculate amounts based on our logic. Can you add new event publisher with Handle pattern like this:

![image](https://user-images.githubusercontent.com/12559226/83313713-aedeb580-a217-11ea-87da-100236d2af90.png)

Event signature: 

![image](https://user-images.githubusercontent.com/12559226/83313781-e9485280-a217-11ea-9435-3b1d9990fcce.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
