### ISSUE TITLE
[Feature Request] Access codeunit 3051-"DotNet_RegexOptions" without real .NET components

### ISSUE THREAD

**Issue by KonstantinPap** [microsoft/ALAppExtensions#7275]
How about of using Setter for all available regex options like `SetMultiline ` or `SetIgnoreCase ` etc. instead of a Getter/Setter to the RegexOptions .NET component.
So you will be able to get rid of these OnPrem scoped procedures:
```
[Scope('OnPrem')]
procedure GetRegexOptions(var DotNetRegexOptions2: DotNet RegexOptions)
begin
    DotNetRegexOptions2 := DotNetRegexOptions;
end;

[Scope('OnPrem')]
procedure SetRegexOptions(var DotNetRegexOptions2: DotNet RegexOptions)
begin
    DotNetRegexOptions := DotNetRegexOptions2;
end;
```

**Comment by JesperSchulz** [comment]
We're working on converting these .NET wrappers into System Application modules. If we've missed some setters/getters you need, you will be able to add them by submitting a simple PR :-) Stay tuned!

**Comment by KonstantinPap** [comment]
I will do that as soon as I find the time.

**Comment by aholstrup** [comment]
@KonstantinPap thank you for your feedback. As @JesperSchulz teased for, we recently launched a new System Application [module for regular expressions](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Regex) without those OnPrem-scoped procedures. If you feel anything is missing, you're very welcome to submit a PR to this new module :)
