### ISSUE TITLE
[EventRequest] CustomerStatistics.Page.al (page 151 "Customer Statistics")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7276]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **CustomerStatistics.Page.al** Page.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83382686-4eab6780-a401-11ea-8e0b-a84e9d3ca86f.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83382716-6256ce00-a401-11ea-8b71-a3f1902e0973.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83382756-73074400-a401-11ea-93a6-7e9c14a712e2.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
