### ISSUE TITLE
[EventRequest] VendorStatistics.Page.al (page 152 "Vendor Statistics")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7277]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **VendorStatistics.Page.al** Page.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83383227-51f32300-a402-11ea-9b16-43809ecf0e54.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83383253-61726c00-a402-11ea-8211-0aeed9f98bca.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83383279-6d5e2e00-a402-11ea-8ce5-087e43dc7e2e.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
