### ISSUE TITLE
[EventRequest] SalesStats.Page.al (page 10042 "Sales Stats.")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7284]
Hi MS,
Please help us in migrating our verticalized solution by adding below Event in **SalesStats.Page.al** Page.

Standard Code
![image](https://user-images.githubusercontent.com/33481576/83391331-f11f1700-a410-11ea-86a0-ba33903c53c9.png)

Modified Code
![image](https://user-images.githubusercontent.com/33481576/83391376-009e6000-a411-11ea-96ee-a6c52dfa38bc.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/83391425-13189980-a411-11ea-8d82-a8c447d0b06e.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
