### ISSUE TITLE
[External] CheckAccType on table 843 "Cash Flow Setup"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#7291]
We've extended the Cash Flow Setup table with a lot of similar CF account nos and would like to apply the same OnValidate rules as for the standard fields.

Can you please expose function 'CheckAccType' on table 'Cash Flow Setup'?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
