### ISSUE TITLE
[Access Request] Table 36 - Sales Header - Cust / Customer

### ISSUE THREAD

**Issue by robinfjelldal** [microsoft/ALAppExtensions#7298]
Hi,
Would it be possible to get the global Cust variable in a similar way like its done on Table 37 - "Sales Line" with the function GetSalesHeader
![image](https://user-images.githubusercontent.com/21332252/83527713-6f9ab800-a4e8-11ea-99e0-a1491a726150.png)

Thanks

**Comment by AlexanderYakunin** [comment]
Can you please be more specific and explain what exactly you need?

**Comment by AlexanderYakunin** [comment]
I have to close this request, as we have no information for implementation. If this is still needed, please create new request and describe how you want to get Cust variable with code.
