### ISSUE TITLE
[Event Modification] COD 7301 "Whse. Jnl.-Register Line" - OnBeforeUpdateBinEmpty()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#7299]
Could you please change the existing param "Bin" to var? "Bin" is a global variable in this codeunit. If you handle the bin update using this event then the codeunit will still use the "old" not updated record. Therefore "Bin" should be var.

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateBinEmpty(WarehouseEntry: Record "Warehouse Entry"; var Bin: Record Bin; var IsHandled: Boolean)
    begin
        // "Bin" to VAR
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
