### ISSUE TITLE
[Access Request] Page 5814 "Item Charge Assignment (Sales)": Variable UnitPrice

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#7300]
Hello.
I would like to access the following variable from the extension objects:

Page 5814 "Item Charge Assignment (Sales)":

protected var
UnitCost: Decimal;

Cheers,
Kristján Gaukur Kristjánsson

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
