### ISSUE TITLE
[Event Request] - Table 5900 Service Header - Ship-to Code - OnValidate Trigger

### ISSUE THREAD

**Issue by l-isidorinho** [microsoft/ALAppExtensions#7301]
Dear all,

In the course of a development in Business Central, related to Sales and Services modules regarding shipment adresses, we’ve became aware of the difference in the approach on the Sales Header table and Service Header table, on **Ship-to Code – OnValidate trigger**.
Fortunately the T36 had the events we needed to implement the customization for the Sales module, but the same approach isn’t available on the other module, for Service documents.
On the following pictures are presented the differences.
**Approach on T36**
(...)
![image](https://user-images.githubusercontent.com/66069119/83550924-826cb700-a4ff-11ea-97bb-78a3df906ec3.png)
(...)
Example of the function signed by the first red box on the image above
![image](https://user-images.githubusercontent.com/66069119/83550998-a16b4900-a4ff-11ea-8e26-e02ff687be7e.png)

**Current Approach on T5900**
(...)
![image](https://user-images.githubusercontent.com/66069119/83550961-90223c80-a4ff-11ea-9ca9-a87ba37ea77a.png)
(...)

We would like to have the same approach in table 5900, in order to have the same functionality in the two modules with the same solution. Next we present a possibility of solution, not only to provide us a way to solve it but also to harmonize the code on the different modules:
**New approach T5900:**
 (...)
![image](https://user-images.githubusercontent.com/66069119/83551284-0d4db180-a500-11ea-85f9-e462618593a7.png)
![image](https://user-images.githubusercontent.com/66069119/83551328-1c346400-a500-11ea-979a-8ffe39505f15.png)
(...)
 
With the definition of 2 functions to encapsulate the current standard code and 4 new integration events, 2 for each one of those new functions, and using the “IsHandled” mechanism similarly to the way we did on the Sales module
![image](https://user-images.githubusercontent.com/66069119/83551371-2eae9d80-a500-11ea-9188-b576530a8044.png)

**Integration Events**
![image](https://user-images.githubusercontent.com/66069119/83551796-c2806980-a500-11ea-9cd1-ac12c71821d6.png)
 
Waiting for your feedback…
Best regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
