### ISSUE TITLE
[Event Request] Table 27 - OnBeforeOnInsert

### ISSUE THREAD

**Issue by rodotto** [microsoft/ALAppExtensions#7306]
Please add a new integration event OnBeforeOnInsert in Table 27 (similar to vendor table).

 trigger OnInsert()
    **var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnInsert(Rec, IsHandled);
        if IsHandled then
            exit;**

 if "No." = '' then begin
            GetInvtSetup;
            InvtSetup.TestField("Item Nos.");
            NoSeriesMgt.InitSeries(InvtSetup."Item Nos.", xRec."No. Series", 0D, "No.", "No. Series");
            "Costing Method" := InvtSetup."Default Costing Method";
        end;

....

[IntegrationEvent(false, false)]
local procedure OnBeforeOnInsert(var Item: Record Item; var IsHandled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
