### ISSUE TITLE
[Code Change Request] Code Changes in Sales and Purchase Subpages

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7308]
In the "Sales Order Subform" a few procedures have been made global instead of local; these are:

- NoOnAfterValidate
- UpdateEditableOnRow
- DeltaUpdateTotals

These procedures also exist in other sales and purchase subpages, but are still local there. We would need them to be changed to global as well in order to implement consistent business functionality.

We would need the following procedures to be changed from local to global in analogy to the Sales Order Subform:

**Page "Blanket Sales Order Subform" (508):**
- procedure NoOnAfterValidate
- procedure UpdateEditableOnRow
- procedure DeltaUpdateTotals

**Page "Blanket Purchase Order Subform" (510):**
- procedure NoOnAfterValidate
- procedure UpdateEditableOnRow
- procedure DeltaUpdateTotals

**Page "Sales Return Order Subform" (6631):**
- procedure NoOnAfterValidate

**Page "Purchase Return Order Subform" (6641):**
- procedure NoOnAfterValidate

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
