### ISSUE TITLE
[Code Change Request] Code Changes in Sales and Purchase Pages

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7309]
The procedure PostDocument is global in the "Sales Order" page. It is, however, still local in similar pages. We need it to be global there as well in order to be able to provide a consistent business functionality in enhancements across the complete sales and purchase process.

Please turn the procedure **PostDocument** from local to **global** in the following pages as well:

- Page "Sales Invoice" (43)
- Page "Sales Credit Memo" (44)
- Page "Purchase Order" (50)
- Page "Purchase Invoice" (51)
- Page "Purchase Credit Memo" (52)
- Page "Sales Return Order" (6630)
- Page "Purchase Return Order" (6640)

**Comment by AlexanderYakunin** [comment]
If we add this procedure, does it help? We cannot simply remove local modifier as it can be breaking for existing extensions.

    protected procedure PostDocumentExt(PostingCodeunitID: Integer; Navigate: Option)
    begin
        PostDocument(PostingCodeunitID, Navigate);
    end;

**Comment by GaryWinter** [comment]
This would have the same effect. Just one line of code we would need to change. No problem. So, yes, this would help. Thanks a lot!

Just out of curiosity: How can removing a local modifier on a procedure break anything? It only adds possibilities, but doesn’t limit them in any way. What point do I miss here? Just to be better prepared for other requests that may come up.

Also: Could the different treatment of the PostDocument procedure in analogous pages (e.g. “Sales Order”, “Sales Invoice”), as we witness it today, not potentially even been seen as a bug?

Von: Alexander Yakunin <notifications@github.com>
Gesendet: Freitag, 5. Juni 2020 08:51
An: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
Cc: Gary Winter <Gary@cloud-ready-software.com>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/ALAppExtensions] [Code Change Request] Code Changes in Sales and Purchase Pages (#7309)


If we add this procedure, does it help? We cannot simply remove local modifier as it can be breaking for existing extensions.

protected procedure PostDocumentExt(PostingCodeunitID: Integer; Navigate: Option)

begin

    PostDocument(PostingCodeunitID, Navigate);

end;

**Comment by AlexanderYakunin** [comment]
If someone copied "local" procedure to extension code earlier and we enable same procedure, compiler can get error due to duplicated names. We recommend to use prefix in 3rd party extensions, although we've got many cases with such errors after checking PTE extensions. Use this approach to prevent this issue.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
