### ISSUE TITLE
[Event Request] New Event in Table 7302 "Bin Content", OnBeforeCheckWhseClass

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7310]
New Event in Table 7302 "Bin Content", OnBeforeCheckWhseClass

A new event with Handled Pattern is needed at the beginning of the CheckWhseClass. This is in analogy to the same procedure in the table Bin where the event is already implemented.

    procedure CheckWhseClass(IgnoreError: Boolean): Boolean
    var
        ResultValue: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckWhseClass(Rec, ResultValue, IsHandled);
        if IsHandled then
            exit(ResultValue);

        GetItem("Item No.");
        if IgnoreError then
            exit("Warehouse Class Code" = Item."Warehouse Class Code");
        TestField("Warehouse Class Code", Item."Warehouse Class Code");
        exit(true);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWhseClass(var BinContent: Record "Bin Content"; var ResultValue: Boolean; var IsHandled: Boolean)
    begin
    end;

![image](https://user-images.githubusercontent.com/22153733/83663638-39813500-a5c9-11ea-9e08-85e63a426b97.png)

**Integration Event:**
OnBeforeCheckWhseClass
**Signature:**
var BinContent: Record "Bin Content";
var ResultValue: Boolean
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
