### ISSUE TITLE
[Event Request] Codeunit 10202 GetAppliedCustEntries

### ISSUE THREAD

**Issue by pzentner** [microsoft/ALAppExtensions#7311]
Add an event

OnAfterPmtDtldCustLedgEntryFiltered(DtldCustLedgEntry, PmtDtldCustLedgEntry);

Right after line

PmtDtldCustLedgEntry.SETRANGE("Customer No.",DtldCustLedgEntry."Customer No.");

Purpose of this event is that we can adjust the entries that are part of the applied customer ledger entries

**Comment by StanPesotskiy** [comment]
Please provide the signature of the event along with the fragments of code that could define location of the event call unambiguously. 
I assume the PmtDtldCustLedgEntry should be passed by reference.

**Comment by pzentner** [comment]
Yes, you are correct. The signature would be as follows:

OnAfterPmtDtldCustLedgEntryFiltered(DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var PmtDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry);

And the code should be placed here:

    procedure GetAppliedCustEntries(var AppliedCustLedgEntry: Record "Cust. Ledger Entry" temporary; CustLedgEntry: Record "Cust. Ledger Entry"; UseLCY: Boolean)
    var
        DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        PmtDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        PmtCustLedgEntry: Record "Cust. Ledger Entry";
        ClosingCustLedgEntry: Record "Cust. Ledger Entry";
        AmountToApply: Decimal;
    begin
        // Temporary Table, AppliedCustLedgEntry, to be filled in with everything that CustLedgEntry applied to.
        // Note that within AppliedCustLedgEntry, the "Amount to Apply" field will be filled in with the Amount Applied.
        // IF UseLCY is TRUE, Amount Applied will be in LCY, else it will be in the application currency
        AppliedCustLedgEntry.Reset();
        AppliedCustLedgEntry.DeleteAll();

        DtldCustLedgEntry.SetCurrentKey("Cust. Ledger Entry No.");
        DtldCustLedgEntry.SetRange("Cust. Ledger Entry No.", CustLedgEntry."Entry No.");
        DtldCustLedgEntry.SetRange("Entry Type", DtldCustLedgEntry."Entry Type"::Application);
        DtldCustLedgEntry.SetRange(Unapplied, false);
        if DtldCustLedgEntry.Find('-') then
            repeat
                PmtDtldCustLedgEntry.SetFilter("Cust. Ledger Entry No.", '<>%1', CustLedgEntry."Entry No.");
                PmtDtldCustLedgEntry.SetRange("Entry Type", DtldCustLedgEntry."Entry Type"::Application);
                PmtDtldCustLedgEntry.SetRange("Transaction No.", DtldCustLedgEntry."Transaction No.");
                PmtDtldCustLedgEntry.SetRange("Application No.", DtldCustLedgEntry."Application No.");
                PmtDtldCustLedgEntry.SetRange("Customer No.", DtldCustLedgEntry."Customer No.");
//>> ADD EVENT
                OnAfterPmtDtldCustLedgEntryFiltered(DtldCustLedgEntry, PmtDtldCustLedgEntry);
//<< ADD EVENT
                PmtDtldCustLedgEntry.FindSet;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
