### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnCopyFromItemOnAfterCheck

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7312]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnCopyFromItemOnAfterCheck` in Table 39 Purchase Line to be changed such that the first parameter is passed by reference, i.e.:
```
    [IntegrationEvent(false, false)]
    local procedure OnCopyFromItemOnAfterCheck(var PurchaseLine: Record "Purchase Line"; Item: Record Item)
    begin
    end;
```

This way the event signature will be aligned with the event for table 37 Sales Line (see also the request in #2841).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
