### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeMessageIfSalesLinesExist

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7313]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeMessageIfSalesLinesExist` to be added to Table 36 Sales Header with the following signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMessageIfSalesLinesExist(SalesHeader: Record "Sales Header"; ChangedFieldCaption: Text; var IsHandled: Boolean)
    begin
    end;
```
with **VAR** parameter `IsHandled`.

which would be called as follows from `MessageIfSalesLinesExist`:
```pascal
    procedure MessageIfSalesLinesExist(ChangedFieldName: Text[100])
    var
        MessageText: Text;
        IsHandled: Boolean;
    begin
        // >> New event call
        OnBeforeMessageIfSalesLinesExist(Rec, ChangedFieldName, IsHandled);
        ifIsHandled then
          exit;
        // << New event call

        if SalesLinesExist and not GetHideValidationDialog then begin
            MessageText := StrSubstNo(LinesNotUpdatedMsg, ChangedFieldName);
            MessageText := StrSubstNo(SplitMessageTxt, MessageText, Text019);
            Message(MessageText);
        end;
    end;
```

The event already exists for the similar procedure `PriceMessageIfSalesLinesExist` requested in #3447.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
