### ISSUE TITLE
[Event Request] Codeunit 99000832 - Sales Line-Reserve - OnBeforeTransferSaleLineToSalesLine with VAR TransferQty parameter

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7314]
Dear ALAppExtensions team,
Through this issue we would like to request the event described in #7294, **but**
also with parameter `TransferQty` as **VAR** parameter.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
