### ISSUE TITLE
[Event Enhancement Request] Sender needs to be added in Codeunit 5802 Events

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7315]
Sender needs to be added in Codeunit 5802 Events

Three integeration events in codeunit 5802 "Inventory Posting to G/L" need to be enhanced by adding the sender.

These events are:

- OnAfterBufferOutputPosting
- OnAfterBufferConsumpPosting
- OnAfterBufferCapacityPosting

    [IntegrationEvent(true, false)]
    local procedure OnAfterBufferOutputPosting(var ValueEntry: Record "Value Entry"; var CostToPost: Decimal; var CostToPostACY: Decimal; var ExpCostToPost: Decimal; var ExpCostToPostACY: Decimal)
    begin
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterBufferConsumpPosting(var TempInvtPostingBuffer: array[4] of Record "Invt. Posting Buffer" temporary; ValueEntry: Record "Value Entry"; var PostBufDimNo: Integer; var CostToPost: Decimal; var CostToPostACY: Decimal)
    begin
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterBufferCapacityPosting(var ValueEntry: Record "Value Entry"; var CostToPost: Decimal; var CostToPostACY: Decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
