### ISSUE TITLE
[Event Enhancement Request] Sender needs to be added in Codeunit 23 Event

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7316]
Sender needs to be added in Codeunit 23 Event

The sender needs to be added to the Integration Event OnAfterUpdateAnalysisViews:

    [IntegrationEvent(true, false)]
    local procedure OnAfterUpdateAnalysisViews(var ItemRegister: Record "Item Register")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
