### ISSUE TITLE
[EventRequest] Table " PurchaseLine", Request for local procedure to Global instead

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#7318]
We would like to request that the following three local procedures in PurchaseLine table seen in the screenshot below to be tranformed to being global procedures instead.

local procedure IsPriceCalcCalledByField(CurrPriceFieldNo:Integer):boolean;
local procedure PlanPriceCalcByFild(CurrPriceFieldNo:integer)
local procedure ClearFieldCausedPriceCalculation()

![image](https://user-images.githubusercontent.com/54017538/83723905-ab946100-a63f-11ea-9b36-5bdf66904a62.png)

any information required please inform.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
