### ISSUE TITLE
Session Time out in Dynamics 365 OnCloud Version ?

### ISSUE THREAD

**Issue by TharunMuthu** [Microsoft/ALAppExtensions#732]
Hi All 
can you help me how to change default session timeout settings from BC On-cloud Version ?
Thanks

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
