### ISSUE TITLE
[Event Request] Application “Tests-Workflow” Codeunit 134204 "Document Approval - Requests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7320]
[Event Request] Application “Tests-Workflow”, 134204 "Document Approval - Requests"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/83733954-9a068580-a64e-11ea-9ac2-00eb6ae566ce.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
