### ISSUE TITLE
[Event Request] Application “Tests-Invoicing” Codeunit 138941 "BC O365 Test Quotes"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7321]
[Event Request]Application “Tests-Invoicing”, 138941 "BC O365 Test Quotes"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize:
![pic1](https://user-images.githubusercontent.com/45795262/83734209-fb2e5900-a64e-11ea-837c-f2d773a5c445.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
