### ISSUE TITLE
[Event Request] Application “Tests-ERM” Codeunit 134851 "Purchase Over Receipt"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7322]
[Event Request]Application “Tests-ERM”, 134851 "Purchase Over Receipt"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/83734520-69731b80-a64f-11ea-8a42-6f45f24a60de.png)
![pic2](https://user-images.githubusercontent.com/45795262/83734529-6bd57580-a64f-11ea-8b31-02999e00c480.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
