### ISSUE TITLE
Action Name inconsistencies in NO Base application

### ISSUE THREAD

**Issue by Avanti05** [microsoft/ALAppExtensions#7325]
Some of the Action names in the Payment Journal for the NO Base application are inconsistent with the names found in in Base App for other localizations. 

"ExportPaymentsToFile" and "VoidPayments" are two examples of this and makes it difficult to add pageextensions for Payment Journal, without having to created localized extensions that would otherwise not be necessary.

**Comment by Avanti05** [comment]
Any news on this issue or suggestions to a solution?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
