### ISSUE TITLE
Event Request Codeunit 22 OnAfterInitCapValueEntry

### ISSUE THREAD

**Issue by EasyStep2Lean** [microsoft/ALAppExtensions#733]
I would like to have the following event added in Function InsertCapValueEntry:

LOCAL InsertCapValueEntry(VAR CapLedgEntry : Record "Capacity Ledger Entry";ValueEntryType : Option;ValuedQty : Decimal;InvdQty : Decimal;AdjdCost : Decimal)
WITH ItemJnlLine DO BEGIN
  IF (InvdQty = 0) AND (AdjdCost = 0) THEN
    EXIT;

  ValueEntryNo := ValueEntryNo + 1;

  ValueEntry.INIT;
  ValueEntry."Entry No." := ValueEntryNo;
  ValueEntry."Capacity Ledger Entry No." := CapLedgEntry."Entry No.";
  ValueEntry."Entry Type" := ValueEntryType;
  ValueEntry."Item Ledger Entry Type" := ValueEntry."Item Ledger Entry Type"::" ";

  ValueEntry.Type := Type;
  ValueEntry."No." := "No.";
  ValueEntry.Description := Description;

  **// << EMFGW113.00.01 USe Capacity Ledger Entry Type for Tooling
  OnAfterInitCapValueEntry(ValueEntry,CapLedgEntry);
  // >>**

  ValueEntry."Order Type" := "Order Type";
  ValueEntry."Order No." := "Order No.";
  ValueEntry."Order Line No." := "Order Line No.";

![image](https://user-images.githubusercontent.com/17320737/50633789-e545d180-0f4c-11e9-932a-b050ccdaa9e6.png)

**Comment by AlexanderYakunin** [comment]
There are already several events here, use it.

**Comment by EasyStep2Lean** [comment]
Ha but not at the spot I need them:-)
