### ISSUE TITLE
[event request] Codeunit 80 "Sales-Post" add events to PostUpdateInvoiceLine and PostUpdateReturnReceiptLine

### ISSUE THREAD

**Issue by JJODonovan** [microsoft/ALAppExtensions#7332]
Could you please add the events OnAfterPostUpdateInvoiceLine(VAR TempSalesHeader : TEMPORARY Record "Sales Header") and PostUpdateReturnReceiptLine(VAR TempSalesHeader : TEMPORARY Record "Sales Header") to the Sales Post Codeunit?  OnAfterPostUpdateInvoiceLine should be called at the end of the PostUpdateInvoiceLine function (OnAfterPostUpdateInvoiceLine(TempSalesOrderHeader);)  and OnAfterPostUpdateReturnReceiptLine should be called at the end of the PostUpdateReturnReceiptLine function with a temporary table TempSalesReturnHeader containing the updated return orders - similar to how this is done in PostUpdateInvoiceLine.  

The same functionality is also needed on Codeunit 90 Purchase-Post.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
