### ISSUE TITLE
[Event Request] Table 37 Sales Line – CheckItemAvailable

### ISSUE THREAD

**Issue by ivohensgens** [microsoft/ALAppExtensions#7333]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 37 – CheckItemAvailable, ofcourse without the prefix DIN.

`// DINNL <<
DINOnBeforeCheckItemAvailableForSalesBlanketOrder(Rec,xRec,CalledByFieldNo,CurrFieldNo,DINIsHandled);
IF DINIsHandled THEN
  EXIT;
// DINNL >>`
`IF ((CalledByFieldNo = CurrFieldNo) OR (CalledByFieldNo = FIELDNO("Shipment Date"))) AND GUIALLOWED AND
   ("Document Type" IN ["Document Type"::Order,"Document Type"::Invoice]) AND
   (Type = Type::Item) AND ("No." <> '') AND`

`LOCAL [IntegrationEvent] DINOnBeforeCheckItemAvailableForSalesBlanketOrder(VAR SalesLine : Record "Sales Line";SalesLineXrec : Record "Sales Line";CalledByFieldNo : Integer;CurrFieldNo : Integer;VAR IsHandled : Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
