### ISSUE TITLE
codeunit 76 "Purch.-Get Drop Shpt." local procedure Code

### ISSUE THREAD

**Issue by RobertdeRoos** [microsoft/ALAppExtensions#7334]
In order to copy comment lines from the sales order and insert into the purchase order I would like to request an extension of the existing OnAfterPurchaseLineInsert event publisher and/or a new publisher just after the code for insert extended text.

    [IntegrationEvent(false, false)]
    local procedure OnAfterPurchaseLineInsert(var PurchaseLine: Record "Purchase Line")
    begin
    end;

Extend with SalesLine (var?) and NextLineNo:

    [IntegrationEvent(false, false)]
    local procedure OnAfterPurchaseLineInsert(var PurchaseLine: Record "Purchase Line"; SalesLine: Record "Sales Line";  var NextLineNo: Integer)
    begin
    end;

New event publisher (like the one used in GetSpecialOrders in codeunit 5702 "Dist. Integration"):

                    if TransferExtendedText.PurchCheckIfAnyExtText(PurchLine, true) then begin
                        TransferExtendedText.InsertPurchExtText(PurchLine);
                        PurchLine2.SetRange("Document Type", "Document Type");
                        PurchLine2.SetRange("Document No.", "No.");
                        if PurchLine2.FindLast then
                            NextLineNo := PurchLine2."Line No.";
                        NextLineNo := NextLineNo + 10000;
                    end;
                    **OnAfterTransferExtendedText(SalesLine, PurchHeader, NextLineNo);**
                until SalesLine.Next = 0

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferExtendedText(SalesLine: Record "Sales Line"; PurchaseHeader: Record "Purchase Header"; var NextLineNo: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
