### ISSUE TITLE
[Event Request] Table 37 Sales Line – No. - OnValidate()

### ISSUE THREAD

**Issue by ivohensgens** [microsoft/ALAppExtensions#7336]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 37 – No. - OnValidate(), ofcourse without the prefix DIN.

There is already an event, but we need an extra parameter:  xRec.

```
OnValidateNoOnBeforeInitRec(Rec,xRec,CurrFieldNo);
TempSalesLine := Rec;
INIT;
IF xRec."Line Amount" <> 0 THEN
  "Recalculate Invoice Disc." := TRUE;
Type := TempSalesLine.Type;
"No." := TempSalesLine."No.";
OnValidateNoOnCopyFromTempSalesLine(Rec,TempSalesLine);
// DINNL <<
DINOnValidateNoOnCopyFromTempSalesLine(Rec, TempSalesLine, xRec);
// DINNL >>
IF "No." = '' THEN
  EXIT;
```

`LOCAL [IntegrationEvent] DINOnValidateNoOnCopyFromTempSalesLine(VAR SalesLine : Record "Sales Line";VAR TempSalesLine : TEMPORARY Record "Sales Line";xSalesLine : Record "Sales Line")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
