### ISSUE TITLE
[Event Request] Table 37 Sales Line – Location Code - OnValidate()

### ISSUE THREAD

**Issue by ivohensgens** [microsoft/ALAppExtensions#7337]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 37 – Location Code - OnValidate(), ofcourse without the prefix DIN.

```
IF NOT "Drop Shipment" THEN BEGIN
  IF "Location Code" = '' THEN BEGIN
    IF InvtSetup.GET THEN
      "Outbound Whse. Handling Time" := InvtSetup."Outbound Whse. Handling Time";
  END ELSE
    IF Location.GET("Location Code") THEN
      "Outbound Whse. Handling Time" := Location."Outbound Whse. Handling Time";
END ELSE
  EVALUATE("Outbound Whse. Handling Time",'<0D>');
// DINNL <<
DINOnValidateLocationCodeOnAfterSetHandlingTime(Rec);
// DINNL >>
IF "Location Code" <> xRec."Location Code" THEN BEGIN
```

`LOCAL [IntegrationEvent] DINOnValidateLocationCodeOnAfterSetHandlingTime(VAR SalesLine : Record "Sales Line")
`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
