### ISSUE TITLE
[Event Request] New Event in Table 61 "Electronic Document Format", OnBeforeGetDocumentUsage

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7339]
New Event in Table 61 "Electronic Document Format", OnBeforeGetDocumentUsage

A new Integration Event including Handled Pattern needs to be added to procedure GetDocumentUsage in order to be able to enhance the feature with entities not covered by standard BC.

    procedure GetDocumentUsage(var DocumentUsage: Option; DocumentVariant: Variant)
    var
        DocumentRecordRef: RecordRef;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetDocumentUsage(Rec, DocumentVariant, DocumentUsage, IsHandled);
        if IsHandled then
            exit;

        DocumentRecordRef.GetTable(DocumentVariant);
        case DocumentRecordRef.Number of
            DATABASE::"Sales Invoice Header":
                DocumentUsage := Usage::"Sales Invoice";
            DATABASE::"Sales Cr.Memo Header":
                DocumentUsage := Usage::"Sales Credit Memo";
            DATABASE::"Service Invoice Header":
                DocumentUsage := Usage::"Service Invoice";
            DATABASE::"Service Cr.Memo Header":
                DocumentUsage := Usage::"Service Credit Memo";
            DATABASE::"Sales Header":
                GetDocumentUsageForSalesHeader(DocumentUsage, DocumentVariant);
            DATABASE::"Service Header":
                GetDocumentUsageForServiceHeader(DocumentUsage, DocumentVariant);
            DATABASE::Job:
                DocumentUsage := Usage::"Job Quote";
            else
                Error(UnSupportedTableTypeErr, DocumentRecordRef.Caption);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDocumentUsage(ElectronicDocumentFormat: Record "Electronic Document Format"; DocumentVariant: Variant; var DocumentUsage: Option; var IsHandled: Boolean)
    begin
    end;

![image](https://user-images.githubusercontent.com/22153733/83760592-7276e380-a675-11ea-95ac-5c001c4c3f6c.png)

**Integration Event:**
OnBeforeGetDocumentUsage
**Signature:**
ElectronicDocumentFormat: Record "Electronic Document Format"
DocumentVariant: Variant
var DocumentUsage: Option
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
