### ISSUE TITLE
Codeunit 12 "Gen. Jnl.-Post Line" OnInsertGLEntryOnBeforeCheckAmountRounding new var parameter "Gen. Journal Line"

### ISSUE THREAD

**Issue by kalinIliev** [microsoft/ALAppExtensions#7340]
Please add table "Gen. Journal Line" to the parameters for event procedure OnInsertGLEntryOnBeforeCheckAmountRounding  in Codeunit 12 "Gen. Jnl.-Post Line".

local procedure OnInsertGLEntryOnBeforeCheckAmountRounding(**var GenJournalLine: Record "Gen. Journal Line"**;var GLEntry: Record "G/L Entry"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by kalinIliev** [comment]
Thanks!
