### ISSUE TITLE
[Event Request] Table 5050 "Contact" – New Event “OnBeforeCreateCustomer”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7341]
Please add a new publisher event to the function CreateCustomer as follows:

.
.
procedure CreateCustomer(CustomerTemplate: Code[10]) CustNo: Code[20]

//>> Start New Publisher Call
OnBeforeCreateCustomer(Rec, IsHandled, ExitValue);
IF IsHandled THEN
  EXIT(ExitValue);
//<< End New Publisher Call
 
CheckForExistingRelationships(ContBusRel."Link to Table"::Customer);
CheckIfPrivacyBlockedGeneric;
CheckCompanyNo;
RMSetup.GET;
.
.
New Publisher Event:

LOCAL [IntegrationEvent] OnBeforeCreateCustomer(VAR Contact : Record Contact;VAR IsHandled : Boolean;VAR ExitValue : Code[20])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
