### ISSUE TITLE
CU 550 - VAT Rate Change Conversion - OnAfterAddNew*Line Events

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#7344]
Hello together,

please add `OnAfterAddNew*Line` Events at the end of the `AddNew*Line` funktions.

`OnAfterNew*Line(VAR Old*Line : Record "* Line";VAR New*Line : Record "* Line";VATProdPostingGroup : Code[20];GenProdPostingGroup : Code[20])`

Example for Service
Integration:
```
IF ABS(OldServiceLine."Qty. to Invoice") >
   (ABS(OldServiceLine."Quantity Shipped") - ABS(OldServiceLine."Quantity Consumed") - ABS(ServiceLine."Quantity Invoiced"))
THEN
  OldServiceLine.VALIDATE(
    "Qty. to Invoice",OldServiceLine."Qty. to Invoice" - ServiceLine."Quantity Shipped" - OldServiceLine."Quantity Consumed")
ELSE
  OldServiceLine.VALIDATE("Qty. to Invoice",OldServiceLine."Qty. to Invoice");

OnAfterNewServiceLine(OldServiceLine, NewServiceLine, VATProdPostingGroup GenProdPostingGroup);

OldServiceLine.MODIFY;
```
Event:
`LOCAL OnAfterNewServiceLine(VAR OldServiceLine : Record "Service Line";VAR NewServiceLine : Record "Service Line";VATProdPostingGroup : Code[20];GenProdPostingGroup : Code[20])
`

Thanks in advance,
Benjamin

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
The best way is to copy the actual AL code you would added. It will speed up the process of implementation. 

Are all parameters to be passed by reference or by value?

**Comment by BenjaminHochstetter** [comment]
Hi Stan,

I added the requested information into the request.
The lines should be passed as by reference.

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
