### ISSUE TITLE
JOB header Table No. series is not extensible

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#7348]
JOB Header No. Series is extendable.
No. Series code is not following the pattern same as sales/purchase header.

We need the same functions an triggers.

Look for these triggers in Sales Header table
OnAfterGetNoSeriesCode
OnBeforeTestNoSeries
OnAfterInitRecord

**Comment by AlexanderYakunin** [comment]
Job is master table, not a document header. We already have set of events for managing number series here.
