### ISSUE TITLE
Variable AutoDocNo Code[10]

### ISSUE THREAD

**Issue by jrmartinezrico** [microsoft/ALAppExtensions#7349]
Dear AL Team,

In the codeunit 444 "Purchase-Post Prepayments", we don't know if this is specific for Spanish functionality, the variable "AutoDocNo" is a Code[10], but is asigned to NoSeriesMgt.GetNextNo(...) that is a Code[20].

We correct this issue in NAV 2017 but we can't do it in our migration to Business Central 15.6.

Best Regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
