### ISSUE TITLE
[Enum request] Table 1875 Field 5 "Area"

### ISSUE THREAD

**Issue by KonstantinPap** [microsoft/ALAppExtensions#735]
Please implement Field 5 "Area" in Table 1875 "Business Setup" as enum

**Comment by AlexanderYakunin** [comment]
Table 1875 "Business Setup" is marked as obsolete because
'This table is being replaced by new table called Manual Setup.'

Instead there is the field(8; Category; Enum "Manual Setup Category") in table 3700 "Manual Setup" in the system module.
