### ISSUE TITLE
Codeunit 96 - CreatePurchHeader

### ISSUE THREAD

**Issue by TimExner** [microsoft/ALAppExtensions#7350]
Hello,
we have found an irritation of the Publishers in the function CreatePurchHeader of Codeunit 96.
There exists OnBeforePurchOrderHeader directly before the PurchOrderHeader.Modify.
An Publisher direct before the PurchOrderHeader.Insert is missing.
The same construct in Codeunit 86 for Sales is correct: OnBeforeInsert and OnBeforeModify.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
