### ISSUE TITLE
[Event Request] Codeunit 392 Reminder-Make - OnAfterCode

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#7353]
Please add a new publisher event to the function Code like this:

```
[External] Code() RetVal : Boolean
.
.
	IF NOT MakeReminder(Currency.Code) THEN
	  RetVal := FALSE;
  UNTIL Currency.NEXT = 0;
END;

//>> Start event publisher
OnAfterCode(RetVal);
//>> End event publisher
```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnAfterCode(VAR RetVal : Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
