### ISSUE TITLE
New event in codeunit 7021 "Purchase Line - Price"

### ISSUE THREAD

**Issue by Giumai** [microsoft/ALAppExtensions#7354]
We need a new event in codeunit 7021 "Purchase Line - Price" function SetPrice:

OnAfterSetPrice(PurchaseLine,PriceListLine,AmountType) like the equivalent event in codeunit 7020 "Sales Line - Price" function SetPrice:

![image](https://user-images.githubusercontent.com/66070271/83896892-1f745d80-a755-11ea-80fd-2fb34fd108ee.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
