### ISSUE TITLE
[Event Request/Bug] Codeunit 365 - Format Address - OnBeforeSalesInvShipTo add CustAddr parameter

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7359]
Dear ALAppExtensions team,
Could you please add parameter `CustAddr` to `OnBeforeSalesInvShipTo` in codeunit "Format Address"?
In #6280 we requested `CustAddr` and `Result` to be added, but it seems like the parameter `CustAddr` was forgotten.
Thank you in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
