### ISSUE TITLE
[Event Request/Bug] Codeunit 365 - Format Address - OnBeforeSalesCrMemoShipTo add CustAddr and Result

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7360]
Dear ALAppExtensions team,
Could you please add parameters `CustAddr` and `Result` to OnBeforeSalesCrMemoShipTo in codeunit "Format Address"?
Please check #7359 where a similar request was made.
Thank you in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
