### ISSUE TITLE
[Event Request/Bug] Codeunit 365 - Format Address - OnBeforeSalesShptBillTo add Result

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7362]
Dear ALAppExtensions team,
Could you please add parameter `Result` to OnBeforeSalesShptBillTo in codeunit "Format Address"?
Please check #6280 where a similar request was made.
Thank you in advance!

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
