### ISSUE TITLE
[Event Request] - Codeunit 9 - Acc. Sched. KPI Dimensions

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#7363]
Requesting 1 new event publisher on codeunit 9 - Acc. Sched. KPI Dimensions with handled pattern

**Event**
`LOCAL [IntegrationEvent] OnBeforeAddCostTypeDimensions(VAR CostType : Record "Cost Type";VAR AccSchedLine : Record "Acc. Schedule Line";ColumnLayout : Record "Column Layout";VAR AccSchedKPIBuffer : Record "Acc. Sched. KPI Buffer";VAR IsHandled : Boolean)`

**Execution**
```
LOCAL AddCostTypeDimensions(VAR CostType : Record "Cost Type";VAR AccSchedLine : Record "Acc. Schedule Line";ColumnLayout : Record "Column Layout";VAR AccSchedKPIBuffer : Record "Acc. Sched. KPI Buffer")
>>> New Code
OnBeforeAddCostTypeDimensions(CostType,AccSchedLine,ColumnLayout,AccSchedKPIBuffer,IsHandled);
IF IsHandled THEN
  EXIT;
<<< New Code End

IF ConflictAmountType(AccSchedLine,ColumnLayout."Amount Type",AmountType) THEN
  EXIT;
.
.
.
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
