### ISSUE TITLE
[Event Request] Codeunit 365 - Format Address - OnFormatAddrOnAfterGetCountry: Add Country VAR parameter

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7366]
Dear ALAppExtensions team,
We would like to request the event publisher `OnFormatAddrOnAfterGetCountry` in the Format Address codeunit to be extended with parameter `var Country: Record "Country/Region"`.
Please see #5994, where this was requested and marked as "ships-in-future-update", but were unfortunately it did not make it in anyway.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
