### ISSUE TITLE
Tables 37/39/etc: Sales/Purch/etc Lines: CalcVATAmountLines(): OnBefore event does not receive QtyType parameter

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#7369]
In any tables with a `CalcVATAmountLines()` that takes a `QtyType`, please also pass said `QtyType` to `OnBeforeCalcVATAmountLines()` subscribers, as they might need that in order to (re)implement how they override this function.

Pending addition of other events, we are having to effectively copy-and-paste the function into an event handler and have that set `IsHandled := true` in order to bypass the original code, in favour of our 99%-the-same version with a couple of small changes. However, we immediately hit this stumbling block.

How else should we determine the `QtyType` in the meantime?

![image](https://user-images.githubusercontent.com/63455896/84047035-beda6000-a9a2-11ea-81ce-c0a6a9befb81.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
