### ISSUE TITLE
[Event Request] Page 160 - Sales Statistics - OnAfterUpdateHeaderInfo

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#7370]
Hi AL team,

could you please pass the parameter "TotalSalesLineLCY" in event OnAfterUpdateHeaderInfo:

    [IntegrationEvent(true, false)]
    local procedure OnAfterUpdateHeaderInfo(TotalSalesLineLCY: Record "Sales Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
