### ISSUE TITLE
[Event Request] Page 402 - Sales Order Statistics - OnAfterUpdateHeaderInfo

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#7372]
Hi AL team,

please add the following parameters to the event OnAfterUpdateHeaderInfo:

    <<<Old
    [IntegrationEvent(true, false)]
    local procedure OnAfterUpdateHeaderInfo()
    >>>

    <<<New
    local procedure OnAfterUpdateHeaderInfo(var TotalSalesLineLCY: array[3] of Record "Sales Line"; 
    var IndexNo: Integer)
    >>>

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
