### ISSUE TITLE
[Event Request] Page 6030 - Service Statistics - OnAfterUpdateHeaderInfo

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#7377]
Hi AL team,

could you please add the following parameters to the event:

    [IntegrationEvent(true, false)]
    <<< Old
    local procedure OnAfterUpdateHeaderInfo()
    >>>

    <<<New
    local procedure OnAfterUpdateHeaderInfo(var TotalServLineLCY: array[7] of Record "Service Line"; 
    var IndexNo: Integer)
    >>>

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
