### ISSUE TITLE
[Event Request] Codeunit 5343 "CRM Sales Order to Sales Order" - CreateSalesOrderLines 

### ISSUE THREAD

**Issue by ahughesdxc** [microsoft/ALAppExtensions#7379]
is it possible to have an event in codeunit 5343 CRM Sales Order to Order in function CreateSalesOrderLines:

 local procedure CreateSalesOrderLines(CRMSalesorder: Record "CRM Salesorder"; SalesHeader: Record "Sales Header")
 var
  CRMSalesorderdetail: Record "CRM Salesorderdetail";
  SalesLine: Record "Sales Line";
 begin
  // If any of the products on the lines are not found in NAV, err
  CRMSalesorderdetail.SetRange(SalesOrderId, CRMSalesorder.SalesOrderId); // Get all sales order lines

  if CRMSalesorderdetail.FindSet then begin
   repeat
    InitializeSalesOrderLine(CRMSalesorderdetail, SalesHeader, SalesLine);
    **OnBeforeInsertSalesLine(CRMSalesorderdetail; var SalesLine);  //NEW EVENT**
    SalesLine.Insert();
    if SalesLine."Qty. to Assemble to Order" <> 0 then
     SalesLine.Validate("Qty. to Assemble to Order");
   until CRMSalesorderdetail.Next = 0;
  end else begin
   SalesLine.Validate("Document Type", SalesHeader."Document Type");
   SalesLine.Validate("Document No.", SalesHeader."No.");
  end;

  SalesLine.InsertFreightLine(CRMSalesorder.FreightAmount);
 end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
