### ISSUE TITLE
[Event Request] Codeunit 550 VAT Rate Change Conversion : OnBeforeStart…, OnAfterFinish…

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#7381]
**Function**: OnRun
Two publishers are required, one before the conversion is started and after it is finished.
**1st publisher**: OnBeforeStartConversion
**2nd publisher:** OnAfterFinishConversion

![grafik](https://user-images.githubusercontent.com/16236672/84261324-de48c880-ab1b-11ea-8288-8256898cccab.png)
Parameter in both publishers: 
VAR VATRateChangeSetup : Record "VAT Rate Change Setup"

![grafik](https://user-images.githubusercontent.com/16236672/84261349-e86ac700-ab1b-11ea-96c3-d1c6a15c07f1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
