### ISSUE TITLE
codeunit 5704 "TransferOrder-Post Shipment", local procedure CopyTransLine

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#7385]
In order to adapt the Line No. and set the NewLineNo with the new value for the transfer line that is inserted, I would like to request an extension of the existing OnBeforeNewTransferLineInsert event publisher.

    [IntegrationEvent(false, false)]
    local procedure OnBeforeNewTransferLineInsert(var NewTransferLine: Record "Transfer Line"; TransferLine: Record "Transfer Line")
    begin
    end;

Extended with var NextLineNo: 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeNewTransferLineInsert(var NewTransferLine: Record "Transfer Line"; TransferLine: Record "Transfer Line"; var NextLineNo)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
