### ISSUE TITLE
New event in codeunit 7021 "Purchase Line - Price"

### ISSUE THREAD

**Issue by developerchristiaens** [microsoft/ALAppExtensions#7389]
We could well use a new event in codeunit 7021 "Purchase Line - Price" function FillBuffer:

OnAfterFillBuffer(PriceCalculationBuffer, PurchaseHeader, PurchaseLine); similar to the event in the "Sales Line - Price" codeunit :

![image](https://user-images.githubusercontent.com/46530620/84354417-2110ac00-abc1-11ea-9cf8-12079c336520.png)

Just a general thought, but it might be a good idea to just mirror all events in both Sales as Purchase codeunit.

**Comment by dtkb** [comment]
> Just a general thought, but it might be a good idea to just mirror all events in both Sales as Purchase codeunit.

Yes, please! I would have hoped that after 30 years that would have become the First Rule. ;-)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
