### ISSUE TITLE
[Event Request] Table 5900 "Service Header" OnBeforeSetSalespersonCode

### ISSUE THREAD

**Issue by robinfjelldal** [microsoft/ALAppExtensions#7391]
Hi MS,

Requesting event "OnBeforeSetSalespersonCode" in "Service Header" in procedure "SetSalespersonCode":

   ```
 local procedure SetSalespersonCode(SalesPersonCodeToCheck: Code[20]; var SalesPersonCodeToAssign: Code[20])
    begin
        >>>>>>>>>>>>>>>>>>>>>>>>>
        OnBeforeSetSalespersonCode
        <<<<<<<<<<<<<<<<<<<<<<<<<
        if SalesPersonCodeToCheck <> '' then
            if Salesperson.Get(SalesPersonCodeToCheck) then
                if Salesperson.VerifySalesPersonPurchaserPrivacyBlocked(Salesperson) then
                    SalesPersonCodeToAssign := ''
                else
                    SalesPersonCodeToAssign := SalesPersonCodeToCheck;
    end;
```
Thanks,
Robin

**Comment by RomanZanizdra** [comment]
Hi @robinfjelldal .
When you ask for the event could you be precise in definition of event parameters and if it should be a var or not.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
