### ISSUE TITLE
[Event Modify] Table 7302 - OnCheckDecreaseBinContentOnAfterCalcTotalQtyAvailToTake

### ISSUE THREAD

**Issue by murielaimar** [microsoft/ALAppExtensions#7392]
This event 'OnCheckDecreaseBinContentOnAfterCalcTotalQtyAvailToTake' cannot be used, since we do not retrieve the filters from WhseActivLine

The event should be modified as follows:
IntegrationEvent (false, false)]
Local procedure OnCheckDecreaseBinContentOnAfterCalcTotalQtyAvailToTake (**var** WhseActivLine : Record "Warehouse Activity Line", var QtyAvailToPickBase: Decimal, DecreaseQtyBase : Decimal)
begin
end ;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
