### ISSUE TITLE
[extensibility-enhancement] Exposing Xml signing and encryption

### ISSUE THREAD

**Issue by kennetlindberg** [microsoft/ALAppExtensions#7393]
Exposing DotNet functionality to enable Xml signing and encryption (primarily from then System.Security.Cryptography.Xml namespace) would be enable more SOAP and other API interoperability. This is something that for example is widely used in banking and Customs API:s in Finland.

**Comment by JesperSchulz** [comment]
Do you have any concrete existing procedures, you would like us to expose? Would it be an option, that you submit a module which fulfills your requirements? Here' an [example of a recently submitted new module](https://github.com/microsoft/ALAppExtensions/pull/6862).

**Comment by kennetlindberg** [comment]
Hi, I realized that maybe I was a bit unclear as to what as was requesting.
I would need the mentioned functionality for Cloud. OnPrem I have solved this with a DotNet component but that of course isn't possible in the Cloud and it was a way of solving this I was looking for.
However, if submitting a module in any way would help creating said functionality in Cloud in some way I would be happy to do so.

**Comment by JesperSchulz** [comment]
By submitting a module, you _can_ actually run .NET in the cloud :-) We just can't allow .NET to run in add-on apps, as we need to be able to ensure that the usage is done in a secure and performant matter. That, we can only assure, if all .NET calls are isolated in the system application and we have verified the code. I absolutely think, that you should close this issue, and create a PR with your desired module instead. Very soon, we will be releasing a more detailed guide as to how to write a proper modules and how to submit them. Until then, please try to follow the architecture of already existing modules (like the one mentioned before).
From the sound of it, maybe this isn't even a new module, but rather functionality which would fit nicely into the Cryptography module? Looking forward to your suggested code additions!

**Comment by kennetlindberg** [comment]
Excellent, of course! I will look into this ASAP. Thank you for your help!

**Comment by JesperSchulz** [comment]
Very much looking forward to your PR :-)
