### ISSUE TITLE
[Request for External] Codeunit 5510 "Production Journal Mgt"

### ISSUE THREAD

**Issue by robinfjelldal** [microsoft/ALAppExtensions#7394]
Hi MS.
Have these requests for external i CU 5510:

local procedure InsertComponents,
local procedure InsertOutputJnlLine,
local procedure InsertComponents

Thanks,
Robin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
