### ISSUE TITLE
Codeunit 5902 - Service Inv.-Printed - OnRun

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#7396]
Could you implement the same way of supress commit in an OnBeforeRun publisher as all the codeunits is the link below for codeunit 5902?
https://github.com/microsoft/ALAppExtensions/issues/5720

We don't really need them however you might want to do the same to all codeunits that update the "No. Printed" like 5779, 5902, 5903, 5904, 5905, 6651, 6661.

Its just a matter of time before someone needs it.

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
