### ISSUE TITLE
Event/Code change Request on Codeunit 22 - Procedure ApplyItemLedgEntry

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#7400]
We need to extend the functionality of "Prevent negative inventory" to "Transfer orders". To do this we suggest you two ways:

1) Changue the core directly on Codeunits 22 and 5704:
  1.1) Codeunit 5704 TransferOrder-Post Shipment:
  On Procedure CheckItemInInventory add the next code:
   ...
   ...
   
   WITH Item DO BEGIN
    **//INIT INSERT
      IF PreventNegativeInventory THEN
        EXIT;
      //END INSERT**
      GET(TransLine."Item No.");
      SETRANGE("Variant Filter",TransLine."Variant Code");
    ...
    ...

     This code will let the system not showing the advice of negative inventory when posting Transfer 
     orders only if we have the system configured in that way.

  1.2) Codeunit 22 Item Jnl.-Post Line
   1.2.1) On Procedure ApplyItemLedgEntry add the next code:
      ...
      ...
         ((Item."Costing Method" = Item."Costing Method"::Specific) AND ItemLedgEntry.Positive) OR
         (ItemJnlLine."Direct Transfer" AND (ItemLedgEntry."Location Code" = '') AND 
      ItemLedgEntry.Positive)
      THEN
        EXIT;
      **//INIT INSERT
      CLEAR(NoPendingEntries);
      //END INSERT**
      ...
      ...
   1.2.2) On Procedure ApplyItemLedgEntry add the next code:
      ...
      ...
      ELSE
          EntryFindMethod := '-';
        IF NOT ItemLedgEntry2.FIND(EntryFindMethod) THEN
          **//INIT INSERT
          IF NOT Item.PreventNegativeInventory THEN BEGIN            
            CASE EntryFindMethod OF
             '-': NoPendingEntries := NOT ItemLedgEntry2.FINDFIRST;
             '+': NoPendingEntries := NOT ItemLedgEntry2.FINDLAST;
            END;            
          END ELSE
          //END INSERT**
      EXIT;
      END ELSE
        CASE EntryFindMethod OF
          '-':
            IF ItemLedgEntry2.NEXT = 0 THEN BEGIN
              **//INIT INSERT
              IF NOT Item.PreventNegativeInventory THEN BEGIN                
                IF (ItemLedgEntry."Entry Type" = ItemLedgEntry."Entry Type"::Transfer) THEN
                  ItemLedgEntry2.COPY(OldItemLedgEntry);
                NoPendingEntries := TRUE;
              END ELSE
              //END INSERT**
                EXIT;
            END;
      '+':
            IF ItemLedgEntry2.NEXT(-1) = 0 THEN
              **//INIT INSERT
              IF NOT Item.PreventNegativeInventory THEN BEGIN              
                IF (ItemLedgEntry."Entry Type" = ItemLedgEntry."Entry Type"::Transfer) THEN
                  ItemLedgEntry2.COPY(OldItemLedgEntry);
                NoPendingEntries := TRUE;
              END ELSE
              //END INSERT**
                EXIT;
        END;
      OldItemLedgEntry.COPY(ItemLedgEntry2)
      ...
      ...
      This code will make the system not to exit when no entries are found, but only if we configure 
      the Item or the system not to prevent negative inventory.

   1.2.3) On Procedure ApplyItemLedgEntry add the modifying next code:
      ...
      ...
      END;
      
        CheckIsCyclicalLoop(ItemLedgEntry,OldItemLedgEntry,PrevAppliedItemLedgEntry,AppliedQty);
        **//INIT MODIFY
        //IF AppliedQty <> 0 THEN BEGIN  
        IF (AppliedQty <> 0) OR ((AppliedQty = 0) AND ((NOT Item.PreventNegativeInventory) AND (NoPendingEntries))) THEN BEGIN
          IF AppliedQty <> 0 THEN BEGIN
        //CONTINUE MODIFY**
            IF NOT OldItemLedgEntry.Positive AND
               (OldItemLedgEntry."Remaining Quantity" = -AppliedQty) AND
               (OldItemLedgEntry."Entry No." = ItemLedgEntry."Applies-to Entry")
      ...
      ...

      ...
      ...
              IF ItemApplnEntry."Cost Application" THEN
                OldItemLedgEntry."Applied Entry to Adjust" := TRUE;
             END;
           **//CONTINUE MODIFY
           END;    
           IF ((AppliedQty = 0) AND ((NOT Item.PreventNegativeInventory) AND (NoPendingEntries))) THEN BEGIN
             IF (ItemLedgEntry."Entry Type" = ItemLedgEntry."Entry Type"::Transfer) AND
                (NOT CausedByTransfer)
             THEN BEGIN
               OldItemLedgEntry := ItemLedgEntry;
               InsertTransferEntry(ItemLedgEntry,OldItemLedgEntry,ItemLedgEntry."Remaining Quantity");
               EXIT;
             END ELSE
               EXIT;
           END;
           //END MODIFY**
      
          OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify(ItemLedgEntry,OldItemLedgEntry,ItemJnlLine);
          OldItemLedgEntry.MODIFY;
      ...
      ...

      This code will create the entry associated to In transit line of the transfer line, but only if we have configured the system not to prevent negative inventory.

      1.2.4) On Procedure CalcAdjustedCost add the next code:
      ...
      ...
      WITH PosValueEntry DO BEGIN
        SETCURRENTKEY("Item Ledger Entry No.");
        SETRANGE("Item Ledger Entry No.",PosItemLedgEntry."Entry No.");
        **//INIT INSERT  
        IF (NoPendingEntries) AND (NOT Item.PreventNegativeInventory) THEN BEGIN
          IF NOT FINDSET THEN
            EXIT;
        END ELSE
        //END INSERT**
        FINDSET;
        REPEAT
          IF "Partial Revaluation" THEN BEGIN
      ...
      ...

      This code will let the system not to crash when the entry is not found when calculating adjusted cost, but only if we have configured the system not to prevent negative inventory.

      1.2.5) On Globar vars add:
      Name		DataType	Subtype	Length
      NoPendingEntries	Boolean		
      	
2) Add events in Codeunits 22
  2.1) Codeunit 22 Item Jnl.-Post Line   
   2.1.1) On Procedure ApplyItemLedgEntry add the next code:
      ...
      ...
      ELSE
          EntryFindMethod := '-';
        IF NOT ItemLedgEntry2.FIND(EntryFindMethod) THEN	   
          **//INIT INSERT
          OnBeforeInsertFirstApplication(ItemLedgEntry2,ItemLedgEntry,ItemTrackingCode,NoPendingEntries,Handled);
          if not Handled then
          //END INSERT**
      EXIT;
      END ELSE
        **//INIT INSERT
	OnBeforeInsertNotFirstApplication(ItemLedgEntry2,ItemLedgEntry,ItemTrackingCode,NoPendingEntries,Handled);
          if not Handled then
        //END INSERT**
        CASE EntryFindMethod OF 
      ...
      ...
   2.1.2) On Procedure ApplyItemLedgEntry add the modifying next code:
      ...
      ...
      CheckIsCyclicalLoop(ItemLedgEntry,OldItemLedgEntry,PrevAppliedItemLedgEntry,AppliedQty);
      **//INIT INSERT
      OnBeforeManageAppliedQty(AppliedQty,NoPendingEntries,ItemLedgEntry,CausedByTransfer,OldItemLedgEntry,Handled);
      If Handled then
        exit
      else
      //END INSERT**
        IF AppliedQty <> 0 THEN BEGIN
      ...
      ...      

   2.1.3) On Procedure CalcAdjustedCost add the next code:
      **//INIT INSERT
      OnBeforeCalcAdjustedCost(PosItemLedgEntry,AppliedQty,AdjustedCostLCY,AdjustedCostACY,DiscountAmount)
        IF IsHandled THEN
          EXIT;
      //END INSERT**
      AdjustedCostLCY := 0;
      AdjustedCostACY := 0;
      DiscountAmount := 0;
      ...
      ...
   2.1.4) On Procedure CalcAdjustedCost add the next var:
	Name		DataType	Subtype	Length
	IsHandled	Boolean		

   2.1.5) On Globar vars add:
      Name		DataType	Subtype	Length
      NoPendingEntries	Boolean		

   2.1.6) Add public events:
	**LOCAL [IntegrationEvent] OnBeforeInsertFirstApplication(VAR ItemLedgEntry2 : Record "Item Ledger Entry";VAR ItemLedgEntry : Record "Item Ledger Entry";VAR ItemTrackingCode : Record "Item Tracking Code";VAR NoPendingEntries : Boolean;VAR IsHandled : Boolean)
        LOCAL [IntegrationEvent] OnBeforeInsertNotFirstApplication(VAR ItemLedgEntry2 : Record "Item Ledger Entry";VAR ItemLedgEntry : Record "Item Ledger Entry";VAR ItemTrackingCode : Record "Item Tracking Code";VAR NoPendingEntries : Boolean;VAR IsHandled : Boolean)
        LOCAL [IntegrationEvent] OnBeforeManageAppliedQty(VAR AppliedQty : Decimal;VAR NoPendingEntries : Boolean;VAR ItemLedgEntry : Record "Item Ledger Entry";VAR CausedByTransfer : Boolean;VAR OldItemLedgEntry : Record "Item Ledger Entry";VAR IsHandled : Boolean)
	LOCAL [IntegrationEvent] OnBeforeCalcAdjustedCost(VAR PosItemLedgEntry : Record "Item Ledger Entry";VAR AppliedQty : Decimal;VAR AdjustedCostLCY : Decimal;VAR AdjustedCostACY : Decimal;VAR DiscountAmount : Decimal)**

**Comment by bgonzalez-ib** [comment]
Sorry, I have noticed you have marked this issue as "extensibility-enchancement". I agree the option 1) should by marked like this, but let me remind you that the opcion 2) is an Event request.
Thank you

**Comment by bgonzalez-ib** [comment]
Sorry, when we were applying the code we noticed two mistakes in option 1) and section 1.2.2). So this section should be like this:

1.2.2) On Procedure ApplyItemLedgEntry add the next code:
...
...
ELSE
EntryFindMethod := '-';
//INIT MODIFY
//IF NOT ItemLedgEntry2.FIND(EntryFindMethod) THEN
//  EXIT;
IF NOT Item.PreventNegativeInventory THEN BEGIN
            CASE EntryFindMethod OF
              '-': 
                IF NOT ItemLedgEntry2.FINDFIRST 
                  THEN NoPendingEntries := TRUE;
              '+': 
                IF NOT ItemLedgEntry2.FINDLAST 
                  THEN NoPendingEntries := TRUE;
            END;                  
          END ELSE begin
            IF NOT ItemLedgEntry2.FIND(EntryFindMethod) THEN
              EXIT;
          END;
//END MODIFY

//INIT MODIFY
//END ELSE
END ELSE BEGIN
//CONTINUE MODIFY
CASE EntryFindMethod OF
'-':
IF ItemLedgEntry2.NEXT = 0 THEN BEGIN
//INIT INSERT
IF NOT Item.PreventNegativeInventory THEN BEGIN
IF (ItemLedgEntry."Entry Type" = ItemLedgEntry."Entry Type"::Transfer) THEN
ItemLedgEntry2.COPY(OldItemLedgEntry);
NoPendingEntries := TRUE;
END ELSE
//END INSERT
EXIT;
END;
'+':
IF ItemLedgEntry2.NEXT(-1) = 0 THEN
//INIT INSERT
IF NOT Item.PreventNegativeInventory THEN BEGIN
IF (ItemLedgEntry."Entry Type" = ItemLedgEntry."Entry Type"::Transfer) THEN
ItemLedgEntry2.COPY(OldItemLedgEntry);
NoPendingEntries := TRUE;
END ELSE
//END INSERT
EXIT;
END;
//CONTINUE MODIFY
END;
//END MODIFY
OldItemLedgEntry.COPY(ItemLedgEntry2)
...
...
This code will make the system not to exit when no entries are found, but only if we configure
the Item or the system not to prevent negative inventory.

Sorry about that

Regards

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot implement any of suggestions above. We need to understand your scenario to suggest feasible solution. Can you describe it, specifically why you want to do it on item application level?

**Comment by bgonzalez-ib** [comment]
I suppose you are refering to the code changin in Condeunit 22 ApplyItemLedgerEntry. 
The code suggested will make the system not to exit when no entries are found, but only if we configure
the Item or the system not to prevent negative inventory. If the system does not exist from than function, with the event suggested in point 2, we well be able to apply the "Prevent negative inventory" when a transfer order is posted.

**Comment by AndreiPanko** [comment]
@bgonzalez-ib - do you want to _allow_ negative inventory for transfer order?

**Comment by bgonzalez-ib** [comment]
Yes, but only if we have the system configured in that way, that is the modification and it is installed on the client database since June with no problems.

**Comment by AndreiPanko** [comment]
We are not very enthusiastic about enabling such tricks without very good purpose. There is a significant risk that it will affect inventory costing.
Could you please describe the scenario, why do you need to transfer goods before receiving them?
Maybe we can find another solution?

**Comment by bgonzalez-ib** [comment]
First of all sorry for delaying on answering.

Our client has two external programs where they manage product manufacturing. These fabrications cannot be integrated online in Business Central due to limitations in these external programs and they are carried out after (the next day). The outputs (sales and transfers) of these productions are only managed in Business Central, so the customer needs to output a finished product whose input will not be produced until the next day. In sales there is no problem since making the configuration to allow negative stocks is enough but in Transfers this configuration is not possible and there must be positive stocks of the product to be able to make the shipment.

**Comment by StanPesotskiy** [comment]
@bgonzalez-ib 
You have described a feature, and even if it works fine for one customer, it is not enough for us to simply put it in the code. There must be scenarios confirmed by automated tests. 
For the new features please submit a product suggestion on https://aka.ms/bcideas

Do the events of the option 2 make sense without implemented option 1?
