### ISSUE TITLE
Access Request Page 9245 - Demand Forecast Matrix

### ISSUE THREAD

**Issue by justinarnold112** [microsoft/ALAppExtensions#7403]
Hello,

I would like to request access to the following global variables in page 9245 - **Demand Forecast Matrix:**

- MatrixRecords: array[32] of Record Date;
- MATRIX_NoOfMatrixColumns: Integer;
- MATRIX_CaptionSet: arra[32] of Text[80];

Currently, when I attempt to extend this page, it tells me that the variables are "_inacessible due to their protection level._"

![9245 Demand Forecast - Page Extension](https://user-images.githubusercontent.com/46410986/84408905-92e8f580-abc1-11ea-8f24-c14f1eaa91b7.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by justinarnold112** [comment]
Wonderful.  Thanks!
