### ISSUE TITLE
[Event Request] Codeunit 550 VAT Rate Change Conversion: 7 new events  

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#7408]
**Function:** Convert
**Publisher:** OnBeforeFinishConvert
![grafik](https://user-images.githubusercontent.com/16236672/84480776-643c4f00-ac95-11ea-9f85-ea8e534ce80b.png)
Parameter 
VAR VATRateChangeSetup : Record "VAT Rate Change Setup"
![grafik](https://user-images.githubusercontent.com/16236672/84480748-571f6000-ac95-11ea-90a7-75b5e6599139.png)

For all of the following functions, a new local variable as boolean: **IsHandled**

**Function:** UpdateItem
**Publisher:** OnBeforeUpdateItem
![grafik](https://user-images.githubusercontent.com/16236672/84485344-4f16ee80-ac9c-11ea-8ad0-601149dc1436.png)
**Function:** UpdateGLacccount
**Publisher**: OnBeforeUpdateGLAccount
![grafik](https://user-images.githubusercontent.com/16236672/84485598-9d2bf200-ac9c-11ea-91d3-a0e69ef68046.png)
**Function:** UpdateRessource
**Publisher:** OnBeforeUpdateRessource
![grafik](https://user-images.githubusercontent.com/16236672/84485801-c8164600-ac9c-11ea-90ea-befa62d5e63f.png)
**Function:** UpdateSales
**Publisher:** OnBeforeUpdateSales
![grafik](https://user-images.githubusercontent.com/16236672/84486026-19263a00-ac9d-11ea-9b32-75d2665f6024.png)
**Function:** UpdatePurchase
**Publisher:** OnBeforeUpdatePurchase
![grafik](https://user-images.githubusercontent.com/16236672/84486422-b08b8d00-ac9d-11ea-9c84-297780d32a82.png)
**Function:** UpdateService
**Publisher:** OnBeforeUpdateService
![grafik](https://user-images.githubusercontent.com/16236672/84486747-1aa43200-ac9e-11ea-810c-662393a2d20c.png)
Full list of publishers
![grafik](https://user-images.githubusercontent.com/16236672/84486911-55a66580-ac9e-11ea-87fc-32a45565d526.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
