### ISSUE TITLE
Codeunit 5942 "ServContractQuote-Tmpl. Upd." : Update Service Contract Header Information

### ISSUE THREAD

**Issue by Ayman-AYDI** [microsoft/ALAppExtensions#7409]
For the following function, a new local variable as boolean: IsHandled

**Trigger** : OnRun()
**Publisher:** OnBeforeFilterTemplate
![image](https://user-images.githubusercontent.com/64891337/84490612-4e318d00-ac9b-11ea-8d4f-aecc0495a3c5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
