### ISSUE TITLE
[Event-Request] COD 12 "Gen. Jnl.-Post Line" in Function PrepareTempVendLedgEntry

### ISSUE THREAD

**Issue by sanjeevpandita** [microsoft/ALAppExtensions#7412]
Please create a new Event in function PrepareTempVendLedgEntry

There is already an Event OnPrepareTempVendLedgEntryOnAfterSetFilters but it only gets executed when GenJnlLine."Applies-to Doc. No." <> ''

New Event is required in else when filtering Vendor Ledger Entries based on "Apply To Oldest" but we have to exclude "On Hold" ledger entries and the event will help

![Annotation 2020-06-13 165418](https://user-images.githubusercontent.com/38876453/84573203-efe9d480-ad96-11ea-95f2-b1be72c0b38a.jpg)

   [IntegrationEvent(false, false)]
    local procedure OnPrepareTempVendLedgEntryOnAfterSetFiltersBlankAppliesToDocNo(var OldVendorLedgerEntry: Record "Vendor Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
