### ISSUE TITLE
[Event Request] Codeunit 1408 "Sales Credit Memo Hdr. - Edit" – New Event “OnBeforeSalesCrMemoHeaderModify(SalesCrMemoHeader,Rec);”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7413]
[Event Request] Codeunit 1408 "Sales Credit Memo Hdr. - Edit" – New Event “OnBeforeSalesCrMemoHeaderModify(SalesCrMemoHeader,Rec);”

Could we please have an new publisher OnBeforeSalesCrMemoHeaderModify?

`    trigger OnRun()`
`    var`
`        SalesCrMemoHeader: Record "Sales Cr.Memo Header";`
`    begin`
`        SalesCrMemoHeader := Rec;`
`        SalesCrMemoHeader.LockTable();`
`        SalesCrMemoHeader.Find();`
`        SalesCrMemoHeader."Shipping Agent Code" := "Shipping Agent Code";`
`        SalesCrMemoHeader."Shipping Agent Service Code" := "Shipping Agent Service Code";`
`        SalesCrMemoHeader."Package Tracking No." := "Package Tracking No.";`
        >>>> NEW CODE BEGIN >>>>>>
`        OnBeforeSalesCrMemoHeaderModify(SalesCrMemoHeader,Rec);`
        <<<< NEW CODE END <<<<<<<
`        SalesCrMemoHeader.TestField("No.", "No.");`
`        SalesCrMemoHeader.Modify();`
`        Rec := SalesCrMemoHeader;`
`    end;`

A suitable example for the desired adaptation is the standard event OnBeforeSalesShptHeaderModify in Codeunit 391 (Shipment Header - Edit)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
