### ISSUE TITLE
[Event Modification] Table 5741 Transfer Line, event publishers OnValidateReceiptDateOnBeforeCalcShipmentDate & OnValidateShipmentDateOnBeforeCalcReceiptDate

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#7415]
Hi
We'd appreciate if you could include the record in the events on the "Shipment Date" and "Receipt Date" fields.
So instead of only having the IsHandled parameter, each event publisher would also have the record as var parameter.

The event publishers would change from this:
_[IntegrationEvent(false, false)]
local procedure OnValidateReceiptDateOnBeforeCalcShipmentDate(var IsHandled: Boolean)
begin
end;_

_[IntegrationEvent(false, false)]
local procedure OnValidateShipmentDateOnBeforeCalcReceiptDate(var IsHandled: Boolean)
begin
end;_

to this:
_[IntegrationEvent(false, false)]
local procedure OnValidateReceiptDateOnBeforeCalcShipmentDate(**var TransferLine: Record "Transfer Line"**;  var IsHandled: Boolean)
begin
end;_

[IntegrationEvent(false, false)]
_local procedure OnValidateShipmentDateOnBeforeCalcReceiptDate(**var TransferLine: Record "Transfer Line"**;  var IsHandled: Boolean)
begin
end;_

Thanks!

**Comment by StanPesotskiy** [comment]
The IncludeSender will be changed:
[IntegrationEvent(**true**, false)]

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
