### ISSUE TITLE
Missing Integration Events in CU CRM Sales Order to Sales Order

### ISSUE THREAD

**Issue by GregorGrabner** [microsoft/ALAppExtensions#7417]
There are non Integration Event Publischers in CU CRM Sales Order to Sales Order
Therefore it is not possible to extand this CU

**Comment by StanPesotskiy** [comment]
Please provide the signature of the event along with the fragments of code that could define location of the event call unambiguously. 
The best way is to copy the actual AL code you would implement.

**Comment by GregorGrabner** [comment]
I was just analysing the code for a new project ... no customization have been done now ...
please Provide Publischer Events to add Field Transfers in SalesLines and Salesheader
pelase Provide Publischer Events to avoid changing Owner of the Document in CRM

**Comment by StanPesotskiy** [comment]
That kind of description is not enough. Please provide the exact signature of the events and places in code where they should be called from. 
If you don't have clear requirements now then close this request and open it when you know all details.

**Comment by StanPesotskiy** [comment]
Please create a new request when you know exactly what events are required.
