### ISSUE TITLE
Source code is excecuted properly only after restart of service tier

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#7419]
We have a strange issue in BC 14 on-prem with our implemented extension, where a specific functionality which is started by source code in table triggers in one of our own tables suddenly stops working. 

When we examine this with the debugger, it is evident that this existing code located in these
triggers is simply not executed any more. It is not user-specific, happens with all users who use that running service. 

The only cure in these cases is to restart the service tier, after which everything is back to normal. So it would seem that a lack of ressouces or maybe some approaching 'out of memory' state is reponsible for these inexplicable skips of written code.

Are there any known issues to explain this behaviour?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your suggestion seems to be a product bug. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
