### ISSUE TITLE
[Event-Request] Table 207 Res. Journal Line FindResUnitCost/FindResPrice

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#7427]
Please add the OnAfterResourseFindCost & OnAfterResourseFindPrice Events in table 207. just like in Table 210

LOCAL FindResUnitCost()
ResCost.INIT;
ResCost.Code := "Resource No.";
ResCost."Work Type Code" := "Work Type Code";
CODEUNIT.RUN(CODEUNIT::"Resource-Find Cost",ResCost);
**OnAfterResourseFindCost(Rec,ResCost);**
"Direct Unit Cost" := ResCost."Direct Unit Cost" * "Qty. per Unit of Measure";
"Unit Cost" := ResCost."Unit Cost" * "Qty. per Unit of Measure";
VALIDATE("Unit Cost");

LOCAL FindResPrice()
ResPrice.INIT;
ResPrice.Code := "Resource No.";
ResPrice."Work Type Code" := "Work Type Code";
**OnAfterResourseFindPrice(Rec,ResPrice);**
CODEUNIT.RUN(CODEUNIT::"Resource-Find Price",ResPrice);
"Unit Price" := ResPrice."Unit Price" * "Qty. per Unit of Measure";
VALIDATE("Unit Price");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
