### ISSUE TITLE
[Event Request] Codeunit 392 Reminder-Make OnMakeReminderOnBeforeInsertLines

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#7428]
Hi AL team,

we need the following event in function "MakeReminder":

    ...
    until ReminderLevel.Next(-1) = 0;
    ReminderHeader."Reminder Level" := MaxReminderLevel;
    ReminderHeader.Validate("Reminder Level");
    // new event begin
     OnMakeReminderOnBeforeInsertLines(ReminderHeader);
    // new event end
    ReminderHeader.InsertLines;
    ReminderLine.SetRange("Reminder No.", ReminderHeader."No.");
    ReminderLine.FindLast;
    NextLineNo := ReminderLine."Line No.";
    GetOpenEntriesNotDueOnHoldTranslated("Language Code", OpenEntriesNotDueTranslated, 
        OpenEntriesOnHoldTranslated);
    CustLedgEntry.SetRange("Last Issued Reminder Level");
    OnMakeReminderOnBeforeCustLedgEntryFindSet(CustLedgEntry, Cust, ReminderHeader, 
        MaxReminderLevel, OverdueEntriesOnly);
    if CustLedgEntry.FindSet then
    ...

and the event-publisher:

    [IntegrationEvent(false, false)]
    local procedure OnMakeReminderOnBeforeInsertLines(var ReminderHeader: Record "Reminder 
        Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
