### ISSUE TITLE
[EventRequest] Codeunit 54/43 GetDefaultApplicationLanguageId

### ISSUE THREAD

**Issue by rdebath** [microsoft/ALAppExtensions#7429]
Please add an event so that the default language (hard coded to 1033) can be overridden with a more reasonable local default.

**Comment by RomanZanizdra** [comment]
@rdebath , is OnGetUserLanguageCode() event available for you and can you use it?

**Comment by rdebath** [comment]
The event is available and could, probably, be used to complete forbid US English.
But the event I want to use is for the initial setup of the display language of a user, not overriding a user language choice.

Also, I don't really want to assume that US English is an "Evil and useless dialect that nobody ever needs".

**Comment by RomanZanizdra** [comment]
@rdebath , could you be so kind to describe the business case where and how you need to change the language? What is the initial setup of the display language?

**Comment by rdebath** [comment]
When a user is created the user personalisation gets the wrong language.
I also have reports of the language reverting without warning.

The (customer admin) users think this is really stupid. A simple fix is to hard code the language to that of the baseapp or put it in field somewhere like "Company Information". Based on past performance Microsoft will not accept a report to fix it correctly; they will normally accept a report to add an event so I can fix this.

**Comment by RomanZanizdra** [comment]
@rdebath I still cannot catch the whole case. Can you provide description in the such way:
1) admin create user
2) admin goes to personalization and set language = xxxx
3) user logs in to system and sees ... that goes wrong from your point of view
4) we would like to have this, this and this

Is it possible you give such description?

**Comment by rdebath** [comment]
1. Admin logs into Azure active directory and assigns license to user, Admin does NOT use "Update Users from Office 356" as this breaks the language for many users and is "not recommended" by MS Support.
2. User logs in to BC (with default en_US language) to create user record and personalization record.
3. Admin logs in to BC and changes personalisation record to correct language
4. User logs in again, or forces a full refresh.

**Comment by RomanZanizdra** [comment]
Hi @rdebath.
After some discussion inside the team I can suggest you to define the particular places in the application where you want to change the language (assisted setup? or something else) and we will provide an events for this. Or I suppose you can use the synchronization with Office 365, in the latest version it should work in the following way: when run "Update users from O365" the language will be taken from the O365 only if it set there.

**Comment by rdebath** [comment]
If the "Update users from O365" were usable that would probably solve the main problem 

The "Update users from O365" in the current SaaS version resets the language to en_US for many users.
Both on our tenant and our customers'.

Occasionally we get a user that is able to and has set the language in O365 and it does say that no change will be made, but this isn't common. The users will not have explicitly chosen American. However, even if the user has reset a correct value in O365 they are not expecting to have any local (to BC) choice they make overridden the next time the sysadmin adds or removes a user (ie **at random**).

But, I don't see you allowing any changes from us to that code as there's little distinction between the localisation and the license. 

Though, if you want the event required there, it would be one that includes the User ID the old value, the new value and if this is a new user. The event would need the ability to either veto the change or substitute a different change. Obviously you don't want us to change the license data so you'll have to filter it down to acceptable changes. (Probably in Codeunit 9017 Function "FetchUpdatesFromAzureGraph")

Alternatively, the simplest, and least intrusive, requirement would be a boolean attached to a user which records if the user has changed the language in BC and if so prevents any updates from Azure taking effect. Ideally this would be visible on the "User Personalization" table so it can be manually reset by the user.

**Comment by RomanZanizdra** [comment]
@rdebath , for current moment we are not ready to give an event for changing default application language. I suggest you to choose any option from the following ones:
1) "Update users from O365" is fixed in the 16.3 version and it's just around the corner. You can wait for it.
2) As I already mentioned, give us particular places in the application (not in Language module or not the "global" one like change everything) where you you need particular event with particular parameters, we will process it.
3) Create a topic on the ideas site if you need some changes in this area, describe it, let others to discuss and vote for it.
4) As it is Language module you can become a contributor and act as developer. So please create a pull request, write code and review it with the  team who is responsible for that. So finally your changes can be accepted and pass to the application.

So if your choice is not about option (2) then I suggest to close current issue.

**Comment by rdebath** [comment]
> "Update users from O365" is fixed in the 16.3 version and it's just around the corner. You can wait for it.

Ah, that's the **next** version not "latest" or "currently on SaaS", please be clear about the versions next time.

Thankyou, I'll reopen if it is still buggy.
