### ISSUE TITLE
Unable to raise public event in native table from extension

### ISSUE THREAD

**Issue by cvale** [Microsoft/ALAppExtensions#743]
There is an event in Table 81 - General Journal Line - OnMoveGenJournalLine:

![image](https://user-images.githubusercontent.com/4006668/50611787-f0aae580-0ed7-11e9-9c85-b92b4541d44d.png)

Before CU2 update it worked when called (raised) from AL code, but now it raises an error saying that "type or method OnMoveGenJournalLine cannot be used for extension development. [AL0296]":

![image](https://user-images.githubusercontent.com/4006668/50611866-441d3380-0ed8-11e9-86f3-7a2a285fbf48.png)

We do expect this code to work since the publisher is no local!

AL Extension version: 2.1.69331
Business Central: 26556

**Comment by JesperSchulz** [comment]
Closing issue due to lack of response. In general, we are hesitant to expose events. We will refactor this event to become local, as global events are no good.
