### ISSUE TITLE
Codeunit 5988 "Serv-Documents Mgt." : Update Service Line

### ISSUE THREAD

**Issue by Ayman-AYDI** [microsoft/ALAppExtensions#7430]
**Procedure:** PrepareDocument()
**Publisher:** OnBeforeServLineInsert
![image](https://user-images.githubusercontent.com/64891337/84764480-b4811d00-afc5-11ea-89a6-919432607277.png)

**Procedure:** CheckIfServDuplicateLine()
**Publisher:** OnCheckIfServDuplicateLineOnAfterServLedgEntryFilters
![image](https://user-images.githubusercontent.com/64891337/84764972-6caec580-afc6-11ea-9e5e-98057f143dad.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
