### ISSUE TITLE
[Event Request] Codeunit 12101 Withholding - Contribution OnCalculateWithholdingTaxOnRecalculate

### ISSUE THREAD

**Issue by kontax85** [microsoft/ALAppExtensions#7431]
Hi,
would it be possible to modify the event OnCalculateWithholdingTaxOnRecalculate in codeunit 12101 from this:
OnCalculateWithholdingTaxOnRecalculate(PurchWithSoc,PurchHeader);

to this:
OnCalculateWithholdingTaxOnRecalculate(PurchWithSoc,PurchHeader,TotalAmount);

with this signature:
[IntegrationEvent] OnCalculateWithholdingTaxOnRecalculate(VAR PurchWithhContribution : Record "Purch. Withh. Contribution";PurchaseHeader : Record "Purchase Header";VAR TotAmount : Decimal)

Thanks a lot!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
