### ISSUE TITLE
[Event Request] Codeunit 7153 Item Analysis Management OnAfterCalcActualAmount

### ISSUE THREAD

**Issue by kontax85** [microsoft/ALAppExtensions#7432]
Hi,
would it be possible to add an event OnAfterCalcActualAmount in codeunit 7153 function CalcActualAmount:

END;
OnAfterCalcActualAmount(ValueType ,ItemStatisticsBuffer .CurrentItemAnalysisViewCode,Amount ): //New event
EXIT(Amount);

 with this signature:
[IntegrationEvent] OnAfterCalcActualAmount(ValueType : 'Sales Amount,Cost Amount,Quantity';VAR ItemStatisticsBuffer : Record "Item Statistics Buffer";CurrentItemAnalysisViewCode : Code[10];VAR Amount : Decimal)

Thanks a lot!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by kontax85** [comment]
Hi, 
thanks for adding the event!

The event anyway has been added in function CalcAmount and not in CalcActualAmount - I think that it may be misleading there.

There may be two solutions, either:
- Change the name to OnAfterCalcAmount and add at least ShowActualBudget as a parmeter.
- Move the event in function CalcActualAmount.
- 
Thanks a lot!
