### ISSUE TITLE
Request to make local procedures global for CU 5895 Inventory Adjustment

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#7433]
![image](https://user-images.githubusercontent.com/49729094/84810033-c3bd9600-afd8-11ea-940b-58e2da55cca9.png)

Thanks very much

**Comment by AlexanderYakunin** [comment]
What is the purpose of this change? Are you going to extend our codeunit? Or use these procedures in you own codeunit?

**Comment by AlexanderYakunin** [comment]
Let me ask again. We cannot simply remove LOCAL attribute for all procedures in Inventory Adjustment, we need to understand which extensibility scenario you want us to address. And we have different options for implementation. Please provide more information.

**Comment by Teming** [comment]
So sorry – I will.

**Comment by Teming** [comment]
1.  How about adding a new event at where the red line is so we could add different types of Inventory Adjustment?    We will start from there.
  2.  The issue is once we add anything to an extension for this codeunit, we could not call any of the existing local functions.

[cid:image004.png@01D67569.9600D0A0]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
