### ISSUE TITLE
[Event Request] Codeunit 426 Payment Tolerance Management OnBeforeCheckPmtDiscTolCust

### ISSUE THREAD

**Issue by kontax85** [microsoft/ALAppExtensions#7434]
Hi,
would it be possible to add an event OnBeforeCheckPmtDiscTolCustin codeunit 426 function CheckPmtDiscTolCust:

LOCAL CheckPmtDiscTolCust(NewPostingdate : Date;NewDocType : ' ,Payment,Invoice,Credit Memo,Finance Charge Memo,Reminder,Refund';NewAmount : Decimal;OldCustLedgEntry : Record "Cust. Ledger Entry";ApplnRoundingPrecision : Decimal;MaxPmtTolAmount : Decimal) : Boolean
//BEGIN NEW EVENT
OnBeforeCheckPmtDiscTolCust(NewPostingdate,NewDocType,NewAmount,OldCustLedgEntry,ApplnRoundingPrecision,MaxPmtTolAmount,IsHandled,Result);
IF IsHandled THEN
  EXIT(Result);
//END NEW EVENT

IF ((NewDocType = NewDocType::Payment) AND

with this signature:
[IntegrationEvent] OnBeforeCheckPmtDiscTolCust(NewPostingdate : Date;NewDocType : ' ,Payment,Invoice,Credit Memo,Finance Charge Memo,Reminder,Refund';NewAmount : Decimal;OldCustLedgEntry : Record "Cust. Ledger Entry";ApplnRoundingPrecision : Decimal;MaxPmtTolAmount : Decimal;VAR IsHandled : Boolean;VAR Result : Boolean)

Thanks a lot!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
