### ISSUE TITLE
Extensibility Request: Change UpdatePropagation  to "Both" for Prod. Order Pages

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#7435]
Is it possible that you add `UpdatePropagation = Both` to the line parts of the following pages.

- [ ] page 99000912 "Simulated Production Order"
- [ ] page 99000813 "Planned Production Order"
- [ ] page 99000829 "Firm Planned Prod. Order"
- [ ] page 99000831 "Released Production Order"
- [ ] page 99000867 "Finished Production Order"

At the moment we have to copy these pages to get this behaviour.

Example for the change:
```
part(ProdOrderLines; "Released Prod. Order Lines")
{
    ApplicationArea = Manufacturing;
    SubPageLink = "Prod. Order No." = FIELD("No.");
    UpdatePropagation = Both; //New
}
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
