### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - SetupSplitJnlLine, OnBeforeAssignItemJnlLineToTemp

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#7437]
Please add a new publisher event to the function SetupSplitJnlLine as follows (see New marked):

    local procedure SetupSplitJnlLine(var ItemJnlLine2: Record "Item Journal Line"; TrackingSpecExists: Boolean): Boolean
    var
        LateBindingMgt: Codeunit "Late Binding Management";
        UOMMgt: Codeunit "Unit of Measure Management";
        NonDistrQuantity: Decimal;
        NonDistrAmount: Decimal;
        NonDistrAmountACY: Decimal;
        NonDistrDiscountAmount: Decimal;
        SignFactor: Integer;
        CalcWarrantyDate: Date;
        CalcExpirationDate: Date;
        Invoice: Boolean;
        SNInfoRequired: Boolean;
        LotInfoRequired: Boolean;
        ExpirationDateChecked: Boolean;
        PostItemJnlLine: Boolean;
        IsHandled: Boolean; //NEW
    begin
        ItemJnlLineOrigin := ItemJnlLine2;
        TempSplitItemJnlLine.Reset;
        TempSplitItemJnlLine.DeleteAll;

        DisableItemTracking := not ItemJnlLine2.ItemPosting;
        Invoice := ItemJnlLine2."Invoiced Qty. (Base)" <> 0;

        if (ItemJnlLine2."Entry Type" = ItemJnlLine2."entry type"::Transfer) and
           PostponeReservationHandling
        then
            SignFactor := 1
        else
            SignFactor := ItemJnlLine2.Signed(1);

        ItemTrackingCode.Code := Item."Item Tracking Code";
        ItemTrackingMgt.GetItemTrackingSettings(
          ItemTrackingCode, ItemJnlLine."Entry Type", ItemJnlLine.Signed(ItemJnlLine."Quantity (Base)") > 0,
          SNRequired, LotRequired, SNInfoRequired, LotInfoRequired);

        if Item."Costing Method" = Item."costing method"::Specific then begin
            Item.TestField("Item Tracking Code");
            ItemTrackingCode.TestField("SN Specific Tracking", true);
        end;

        OnBeforeSetupSplitJnlLine(ItemJnlLine2, TrackingSpecExists, TempTrackingSpecification);

        if not ItemJnlLine2.Correction and (ItemJnlLine2."Quantity (Base)" <> 0) and TrackingSpecExists then begin
            if DisableItemTracking then begin
                if not TempTrackingSpecification.IsEmpty then
                    Error(Text021, ItemJnlLine2.FieldCaption("Operation No."), ItemJnlLine2."Operation No.");
            end else begin
                if TempTrackingSpecification.IsEmpty then
                    Error(Text100);

                CheckItemTrackingIsEmpty(ItemJnlLine2);

                if Format(ItemTrackingCode."Warranty Date Formula") <> '' then
                    CalcWarrantyDate := CalcDate(ItemTrackingCode."Warranty Date Formula", ItemJnlLine2."Document Date");
                if Format(Item."Expiration Calculation") <> '' then
                    CalcExpirationDate := CalcDate(Item."Expiration Calculation", ItemJnlLine2."Document Date");

                if SignFactor * ItemJnlLine2.Quantity < 0 then // Demand
                    if ItemTrackingCode."SN Specific Tracking" or ItemTrackingCode."Lot Specific Tracking" then
                        LateBindingMgt.ReallocateTrkgSpecification(TempTrackingSpecification);

                TempTrackingSpecification.CalcSums(
                  "Qty. to Handle (Base)", "Qty. to Invoice (Base)", "Qty. to Handle", "Qty. to Invoice");
                TempTrackingSpecification.TestFieldError(TempTrackingSpecification.FieldCaption("Qty. to Handle (Base)"),
                  TempTrackingSpecification."Qty. to Handle (Base)", SignFactor * ItemJnlLine2."Quantity (Base)");

                if Invoice then
                    TempTrackingSpecification.TestFieldError(TempTrackingSpecification.FieldCaption("Qty. to Invoice (Base)"),
                      TempTrackingSpecification."Qty. to Invoice (Base)", SignFactor * ItemJnlLine2."Invoiced Qty. (Base)");

                NonDistrQuantity :=
                  UOMMgt.CalcQtyFromBase(
                    UOMMgt.RoundQty(
                      UOMMgt.CalcBaseQty(ItemJnlLine2.Quantity, ItemJnlLine2."Qty. per Unit of Measure")),
                    ItemJnlLine2."Qty. per Unit of Measure");
                NonDistrAmount := ItemJnlLine2.Amount;
                NonDistrAmountACY := ItemJnlLine2."Amount (ACY)";
                NonDistrDiscountAmount := ItemJnlLine2."Discount Amount";

                OnSetupSplitJnlLineOnBeforeSplitTempLines(TempSplitItemJnlLine, TempTrackingSpecification);

                TempTrackingSpecification.FindSet;
                repeat
                    if ItemTrackingCode."Man. Warranty Date Entry Reqd." then
                        TempTrackingSpecification.TestField("Warranty Date");

                    CheckExpirationDate(ItemJnlLine2, SignFactor, CalcExpirationDate, ExpirationDateChecked);

                    CheckItemTrackingInfo(
                      ItemJnlLine2, TempTrackingSpecification, SNInfoRequired, LotInfoRequired, SignFactor, ItemTrackingCode);

                    if TempTrackingSpecification."Warranty Date" = 0D then
                        TempTrackingSpecification."Warranty Date" := CalcWarrantyDate;

                    TempTrackingSpecification.Modify;
                    TempSplitItemJnlLine := ItemJnlLine2;
                    PostItemJnlLine :=
                      PostItemJnlLine or
                      SetupTempSplitItemJnlLine(
                        ItemJnlLine2, SignFactor, NonDistrQuantity, NonDistrAmount,
                        NonDistrAmountACY, NonDistrDiscountAmount, Invoice);
                until TempTrackingSpecification.Next = 0;
            end;
        end else begin
            //NEW Begin
            IsHandled = false;
            OnBeforeAssignItemJnlLineToTemp(ItemJnlLine2, IsServUndoConsumption, PostponeReservationHandling, TempSplitItemJnlLine, IsHandled);
            if not IsHandled then begin
            //NEW End
                TempSplitItemJnlLine := ItemJnlLine2;
                TempSplitItemJnlLine.Insert;
            end; //NEW
        end;

        exit(PostItemJnlLine);
    end;

New Publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignItemJnlLineToTemp(ItemJournalLine: Record "Item Journal Line"; IsServUndoConsumption: Boolean; PostponeReservationHandling: Boolean; var TempSplitItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
