### ISSUE TITLE
[Event Request] codeunit 5760 "Whse.-Post Receipt" 

### ISSUE THREAD

**Issue by iVervast** [microsoft/ALAppExtensions#7439]
Please implement change to be able to set suppresscommit in codeunit 5760. (as in line with other posting routines)

Extend the existing Event 'OnBeforeRun' with parameter 'SuppressCommit';
OnBeforeRun(Rec, SuppressCommit);

Or implement new event in 'local procedure "Code"()':
OnBeforeCode(WhseRcptLine, SuppressCommit, IsHandled);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
