### ISSUE TITLE
Codeunit 5900 ServOrderManagement OnBeforeLookupServItemNo fix Var

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#7440]
in request #6936 the ServiceItem Parameter was supposed to be a Var, but it is not.  Can you make the Service Item as a Var.  

**Existing**
    [IntegrationEvent(false, false)]
    local procedure OnLookupServItemNoOnAfterServItemSetFilters(var ServItemLine: Record "Service Item Line"; **ServItem: Record "Service Item"**; ServHeader: Record "Service Header");
    begin
    end;

**New** 
    [IntegrationEvent(false, false)]
    local procedure OnLookupServItemNoOnAfterServItemSetFilters(var ServItemLine: Record "Service Item Line"; ** var ServItem: Record "Service Item"**; ServHeader: Record "Service Header");
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
