### ISSUE TITLE
[Event Request] FR codeunit 10860 "Payment Management" - ProcessPaymentStep

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#7441]
procedure ProcessPaymentStep(PaymentHeaderNo: Code[20]; PaymentStep: Record "Payment Step");

Should be great to add an event so we can include more checks :
At beginning of the procedure
OnBeforeProcessPaymentStep(PaymentHeaderNo: Code[20]; PaymentStep: Record "Payment Step");

Could be useful to add an event so we can include more process:
At the end of the procedure
OnAfterProcessPaymentStep(PaymentHeaderNo: Code[20]; PaymentStep: Record "Payment Step");

Generally, there is **no event at all** in the French Payment Slip module. Could be really interesting to get some.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
