### ISSUE TITLE
[Event Request] Codeunit 60 Sales-Calc. Discount OnBeforeCalculateIncDiscForHeader event-request

### ISSUE THREAD

**Issue by kontax85** [microsoft/ALAppExtensions#7442]
Hi,
would it be possible to add an event OnBeforeCalculateIncDiscForHeader in codeunit 60 function CalculateIncDiscForHeader:

//New Event Begin
OnBeforeCalculateIncDiscForHeader(TempSalesHeader,IsHandled); 
IF IsHandled THEN
  EXIT;
//New Event End
SalesSetup.GET;

Thanks a lot!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
