### ISSUE TITLE
[Event Request] table 1226 "Payment Export Data" - OnAfterSetVendorAsRecipient

### ISSUE THREAD

**Issue by jwinberg** [microsoft/ALAppExtensions#7443]
Recently a new event (OnAfterSetCustomerAsRecipient) was added to Payment Export Data. This was related to issue #5988 request.
We are in urgent need for the same but for payments to vendors, so could you also add this event:

`local procedure OnAfterSetVendorAsRecipient(var PaymentExportData: Record "Payment Export Data"; var Vendor: Record Vendor; var VendorBankAccount: Record "Vendor Bank Account");
`

May I also suggest to add event for SetEmployeeAsRecipient as well at the same time (not that we need it right now but probably somebody will need in the future)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by dtkb** [comment]
Can I ask why these were released taking the source account records by `var`? I wouldn't think there is any legitimate reason to modify the sources during the copy.
