### ISSUE TITLE
[Request for External] Codeunit 9024 "Azure AD Graph User" - GetObjectId

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/ALAppExtensions#7444]
I'd like to access the user Object ID to help manage licensing at a seat level.

Can this method be exposed, or otherwise implemented in another way to get the same information? Because the User Security ID's might vary between instances (`LIVE`, `TEST `etc) it'd be useful to have it use the Object ID instead.

Pipes to `Codeunit 9011 "Azure AD Graph User Impl."`.

**Comment by IhorHandziuk** [comment]
Hi @ShadowXVII . The Object ID returned by the `GetObjectId` method is identical to the value stored in the table `"User Property"`.

So you can obtain the same value by calling:
```
 if UserProperty.Get(UserSecurityId) then
        AuthenticationObjectId := UserProperty."Authentication Object ID";
```

Please, let us know if this solves your issue

**Comment by ShadowXVII** [comment]
Hi Ihor,

Thanks -- yes I saw that has the same value, but wasn't sure if it was "OK" to grab it from there. If it's in sync with the User Object ID then that's fine.

Thanks,
Jake

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by ShadowXVII** [comment]
Actually @IhorHandziuk , the UserProperty table is only accessible OnPrem and won't work in a SaaS Environment?

**Comment by IhorHandziuk** [comment]
@ShadowXVII you are right, sorry for the confusion. Then I suggest using the "Authentication Email" field on the User table. It is unique for each user and identical for the same user across instances

**Comment by ShadowXVII** [comment]
I'd rather use pseudoanonymous identifiers than have end users emails stored in another system.

**Comment by IhorHandziuk** [comment]
If they need to be stored elsewhere, would obfuscating the emails or hashing them before storing in an external system work?

**Comment by ShadowXVII** [comment]
Well, I guess I could hash it in some form. Just seems a bit roundabout when there's a value right there.

Would have been nice to keep them consistent as object IDs/guide.

**Comment by IhorHandziuk** [comment]
We want to avoid exposing the functionality related to reading/writing data from graph, as it's not the user who is accessing it, it's the service.
In this particular case exposing the object ID might be safe, but there is no reason why it _should_ be the object ID. So we believe it's better to not expose it.

It seems like the last suggestion would work for your case. Thanks for the question :)

**Comment by ShadowXVII** [comment]
Yeah that's fair. We aren't the ones who's app was consented so we shouldn't be able to access it. We could either make our own app registration or leverage the identifiers that we can access.
