### ISSUE TITLE
[Event Request] Codeunit 1233 SEPA DD-Check Line / CheckCollectionEntry: OnBeforeCheckCollectionEntry

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#7445]
We need a new event function in Codeunit 1233 SEPA DD-Check Line, named OnBeforeCheckCollectionEntry:

LOCAL [IntegrationEvent] OnBeforeCheckCollectionEntry(VAR DirectDebitCollectionEntry : Record "Direct Debit Collection Entry";VAR IsHandled : Boolean)

called from:

LOCAL CheckCollectionEntry(DirectDebitCollectionEntry : Record "Direct Debit Collection Entry")
**//INIT-INSERT
IsHandled := FALSE;
OnBeforeCheckCollectionEntry(DirectDebitCollectionEntry, IsHandled);
IF IsHandled THEN
    EXIT;
//END-INSERT**

GLSetup.GET;
WITH DirectDebitCollectionEntry DO BEGIN
....
....
....

To apply this code the next local var will be necessary:
Name 			DataType 	Subtype 	Length
IsHandled		Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
