### ISSUE TITLE
Fix "Standard Service Line" Tablerelation of "Unit of Measure Code" 

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#7447]
Hello togehter,

the table relation of "Unit of Measure Code" in "Standard Service Line" should be:
IF (Type=CONST(Item)) "Item Unit of Measure".Code WHERE (Item No.=FIELD(No.)) ELSE IF (Type=CONST(Resource)) "Resource Unit of Measure".Code WHERE (Resource No.=FIELD(No.)) ELSE "Unit of Measure"

and not
IF (Type=CONST(Item)) "Item Unit of Measure".Code WHERE (Item No.=FIELD(No.)) ELSE "Unit of Measure"

Thanks in advanced,
Benjamin

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your suggestion seems to be a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
