### ISSUE TITLE
[Event Request] CU 99000773 "Calculate Prod. Order" - Function "Calculate"

### ISSUE THREAD

**Issue by wfelberbauer** [microsoft/ALAppExtensions#7448]
Is it  it possible that you can add the Publisher **OnBeforeCalculateRecalculate** and **OnAfterCalculateRecalculate** in de Function Calculate:
      
```
        //-New
        OnBeforeCalculateRecalculate(var ProdOrderLine, CalcRouting, CalcComponents);
        //+NEW
        Recalculate(ProdOrderLine, Direction, LetDueDateDecrease);
        //-New
        OnAfterCalculateRecalculate(var ProdOrderLine, CalcRouting, CalcComponents);
        //+NEW
        OnAfterCalculate(ProdOrderLine, ErrorOccured);

        exit(not ErrorOccured);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
