### ISSUE TITLE
CU 99000787 "Create Prod. Order lines" Publisher "OnCheckMakeOrderLineBeforeInsert" add new Parameter InsertNew

### ISSUE THREAD

**Issue by wfelberbauer** [microsoft/ALAppExtensions#7449]
is it possible to add the Variable InsertNew on the Publisher OnCheckMakeOrderLineBeforeInsert

OnCheckMakeOrderLineBeforeInsert(ProdOrderLine, ProdOrderComp, **var** **InsertNew);**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
