### ISSUE TITLE
Add Permission to objects to support Indirec permissions

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/ALAppExtensions#745]
Please add Read permission for tables 15 and 17 to Codeunit 12
Please add Read permission for table 15 to Codeunit 5802

By doing this we can have sales people able to post sales invoices without having direct access to G/L

**Comment by JesperSchulz** [comment]
Sounds like a reasonable request. I will log a bug for you. But in the future, please use this repo for extensibility issues only ;-) I will close this issue and convert it into a bug in our backlog. Thanks.
