### ISSUE TITLE
Page 1350 - French translation error ?

### ISSUE THREAD

**Issue by YannRobertCargo** [microsoft/ALAppExtensions#7451]
Hello,
I noticed that on the page 1350 used to edit information on a sales shipment header the two field "Shipping Agent Code" and "Service Agent Code" are both translated by "Agent" and "Service Agent" in French when other occurences of these fields are translated by "Transporteur" and "Prestation transporteur".

P1350 :
![image](https://user-images.githubusercontent.com/47186314/85000375-998fe380-b152-11ea-8d93-62fb38edca32.png)

P110 : 
![image](https://user-images.githubusercontent.com/47186314/85000426-ad3b4a00-b152-11ea-8244-60f86a2a166c.png)

Could you please correct those two translations ?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your suggestion seems to be a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
