### ISSUE TITLE
[Event Request] Report 99001020 "Carry Out Action msg.-Plan", Function: Requisition Line - OnAfterGetRecord()

### ISSUE THREAD

**Issue by wfelberbauer** [microsoft/ALAppExtensions#7453]
is it possible to get a publisher in the function Requisition Line - OnAfterGetRecord()

```
  ELSE
    CurrReport.SKIP;
END;
COMMIT;
//-New
OnAfterReqLineOnAfterGetRecord(var Requisition Line, ProdOrderChoice);
//+New

Requisition Line - OnPostDataItem()
Window.CLOSE;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
