### ISSUE TITLE
[Request For External] Table 5870 "BOM Buffer" - InitFromItem

### ISSUE THREAD

**Issue by smartinez-io** [microsoft/ALAppExtensions#7454]
Hi,
 
Could you please consider the following property modification? **We need to call the InitFromItem function from a _BOM Buffer_'s table extension object.** Now, this function is set to _local_:

Thank you for your attention.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
