### ISSUE TITLE
"var" missing in publisher of Codeunit 22 Item Jnl.-Post Line

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#7455]
Hello,
please change the parameter "TrackingSpecification" of publisher function "OnBeforeCheckExpirationDate" to VAR.

As the publisher function uses an IsHandled pattern with an "EXIT" statement it is necessary for us to make a copy of the complete function "CheckExpirationDate" that implies the changed code.

The "CheckExpirationDate" function changes the "TrackingSpecification" record multiple times. This makes it necessary to publish the record variable to the subcriber functions. Otherwise the changes to this records are lost.

`local procedure OnBeforeCheckExpirationDate(var ItemJournalLine: Record "Item Journal Line"; **var** TrackingSpecification: Record "Tracking Specification"; SignFactor: Integer; CalcExpirationDate: Date; var ExpirationDateChecked: Boolean; var IsHandled: Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
