### ISSUE TITLE
Base64 codeunit

### ISSUE THREAD

**Issue by hougaard** [microsoft/ALAppExtensions#7456]
The base64 codeunit is doing all string conventions with UTF8 as text encoding. 

I would like to be able to specify the TextEncoding to be used. This is required for handling base64 data from external sources.

**Comment by JesperSchulz** [comment]
Sounds like a valid suggestion! Any chance you could submit a PR to make that happen? As Base64 Convert is a module which is open sourced, you are welcome to suggest any changes you'd like, as long as you're not breaking the public API. You can change the internal implementation (codeunit 4111 "Base64 Convert Impl.") all you'd like, without introducing breaking changes just as you can introduce overloads in the modules facade (codeunit 4110 "Base64 Convert") - your changes should be rather straight forward to do :-)

**Comment by hougaard** [comment]
Here you go, https://github.com/microsoft/ALAppExtensions/pull/7676 

Let me know if this is usable?

**Comment by JesperSchulz** [comment]
Great work, Erik. We're on it! And thanks for explaining the process in your great [tutorial video](https://www.youtube.com/watch?v=3Q9ikdBYJvQ)!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
