### ISSUE TITLE
Event request for importing payroll transactions

### ISSUE THREAD

**Issue by cfrazierNAV** [microsoft/ALAppExtensions#7457]
I'm requesting a new event publisher on Page 1661 "Payroll Import Transactions"

The payroll import creates journal entries as part of the FinishAction() procedure.  It would be great if there was an event (maybe something like OnAfterGenJournalLineCreated) after NewGenJournalLine.Modify (line 350).  Additionally, it would be great if there was an event and IsHandled pattern before the FindSet on line 336.

Thanks :)
Chris

`
    local procedure FinishAction()
    var
        NewGenJournalLine: Record "Gen. Journal Line";
        AssistedSetup: Codeunit "Assisted Setup";
        Info: ModuleInfo;
        NextLinieNo: Integer;
    begin
        NextLinieNo := 0;
        NewGenJournalLine.SetRange("Journal Template Name", GenJournalLine."Journal Template Name");
        NewGenJournalLine.SetRange("Journal Batch Name", GenJournalLine."Journal Batch Name");
        if NewGenJournalLine.FindLast then
            NextLinieNo := NewGenJournalLine."Line No.";

        if FindSet then begin
            repeat
                NewGenJournalLine.Init;
                NewGenJournalLine."Journal Template Name" := GenJournalLine."Journal Template Name";
                NewGenJournalLine."Journal Batch Name" := GenJournalLine."Journal Batch Name";
                NextLinieNo += 10000;
                NewGenJournalLine."Line No." := NextLinieNo;
                NewGenJournalLine.Insert;
                NewGenJournalLine.SetUpNewLine(GenJournalLine, 0, false);
                NewGenJournalLine.Validate("Account Type", NewGenJournalLine."Account Type"::"G/L Account");
                NewGenJournalLine.Validate("Account No.", "G/L Account");
                NewGenJournalLine.Validate("Posting Date", "Transaction Date");
                NewGenJournalLine.Validate(Amount, Amount);
                NewGenJournalLine.Validate(Description, Description);
                NewGenJournalLine.Modify;
            until Next = 0;

            GenJournalLine := NewGenJournalLine;
            NavApp.GetCurrentModuleInfo(Info);
            AssistedSetup.Complete(Info.Id(), Page::"Payroll Import Transactions");

            Message(PayrollImportedMsg);
        end;

        CurrPage.Close;
    end;
`

**Comment by StanPesotskiy** [comment]
Please provide the signature of the event along with the fragments of code that could define location of the event call unambiguously. 
The best way is to copy the actual AL code you would implement.
