### ISSUE TITLE
Table 36 - SalesHeader - Add Parameter to OnCreateDimOnBeforeUpdateLines

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#7458]
On Event OnCreateDimOnBeforeUpdateLines can we add OldDimSetID as a parameter.

Before
OnCreateDimOnBeforeUpdateLines(Rec, xRec, CurrFieldNo);

    [IntegrationEvent(false, false)]
    local procedure OnCreateDimOnBeforeUpdateLines(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; CurrentFieldNo: Integer)
    begin
    end;

After
OnCreateDimOnBeforeUpdateLines(Rec, xRec, CurrFieldNo, OldDimSetID);

    [IntegrationEvent(false, false)]
    local procedure OnCreateDimOnBeforeUpdateLines(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; CurrentFieldNo: Integer; OldDimSetID: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
