### ISSUE TITLE
[EventRequest] Codeunit 1102 CA Jnl.-Post Line OnAfterBudgetCostEntryInsert,OnBeforeBudgetCostEntryInsert

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7460]
Events for CostEntry are there. But, same events for budget entries are misssing. Please, add two new events:
`[IntegrationEvent] OnAfterCostBugetEntryInsert(VAR CostBudgetEntry : Record "Cost Budget Entry";CostJournalLine : Record "Cost Journal Line")`
`[IntegrationEvent] OnBeforeCostBugetEntryInsert(VAR CostBudgetEntry : Record "Cost Budget Entry";CostJournalLine : Record "Cost Journal Line")`

calling in function **InsertBudgetEntries**
LOCAL InsertBudgetEntries(CT : Code[20];CC : Code[20];CO : Code[20];Amt : Decimal)
WITH CostJnlLine DO BEGIN
  CostBudgetEntry.INIT;
  CostBudgetEntry."Entry No." := NextCostBudgetEntryNo;
  CostBudgetEntry."Budget Name" := "Budget Name";
  CostBudgetEntry."Cost Type No." := CT;
  CostBudgetEntry.Date := "Posting Date";
  CostBudgetEntry."Document No." := "Document No.";
  CostBudgetEntry.Description := Description;
  CostBudgetEntry."Cost Center Code" := CC;
  CostBudgetEntry."Cost Object Code" := CO;
  CostBudgetEntry.Amount := Amt;
  CostBudgetEntry."Source Code" := "Source Code";
  CostBudgetEntry."System-Created Entry" := "System-Created Entry";
  CostBudgetEntry.Allocated := Allocated;
  CostBudgetEntry."Last Modified By User" := USERID;
  CostBudgetEntry."Allocation Description" := "Allocation Description";
  CostBudgetEntry."Allocation ID" := "Allocation ID";
  // new
  **OnBeforeCostBugetEntryInsert(CostBudgetEntry,CostJnlLine);**
  //
  CostBudgetEntry.INSERT;
  // new
  **OnAfterCostBugetEntryInsert(CostBudgetEntry,CostJnlLine)**;
  //
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
