### ISSUE TITLE
[EventReqest Change] C1101 CA Jnl.-Check Line, Add IsHandled to OnBeforeRunCheck(CostJnlLine)

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7461]
Please add Handled to OnBeforeRunCheck(CostJnlLine)to functioon RunCheck like

_procedure RunCheck(var CostJnlLine: Record "Cost Journal Line")_
 begin
**IsHandled := false;**
OnBeforeRunCheck(CostJnlLine,**IsHandled**);
**IF IsHandled THEN
  EXIT;**

WITH CostJnlLine DO BEGIN

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
