### ISSUE TITLE
Event Request - T5901- Service Item Line - OnCheckWarrantyOnAfterSetWarrantyPartsLabor

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#7462]
Can you add a new Event on Table 5901 to function CheckWarranty called OnCheckWarrantyOnAfterSetWarrantyPartsLabor

    procedure CheckWarranty(Date: Date)
    var
        WarrantyLabor: Boolean;
        WarrantyParts: Boolean;
        IsHandled: Boolean;
    begin
        if "Warranty Starting Date (Parts)" > "Warranty Ending Date (Parts)" then begin
            Validate("Warranty Starting Date (Parts)", 0D);
            Validate("Warranty Starting Date (Labor)", 0D);
            Error(Text059);
        end;

        if ((Date >= "Warranty Starting Date (Parts)") and (Date <= "Warranty Ending Date (Parts)")) or
           ((Date >= "Warranty Starting Date (Labor)") and (Date <= "Warranty Ending Date (Labor)"))
        then
            Warranty := true
        else
            Warranty := false;

        IsHandled := false;
        OnCheckWarrantyOnAfterSetWarranty(Rec, IsHandled);
        if IsHandled then
            exit;

        WarrantyParts := (Date >= "Warranty Starting Date (Parts)") and (Date <= "Warranty Ending Date (Parts)");
        WarrantyLabor := (Date >= "Warranty Starting Date (Labor)") and (Date <= "Warranty Ending Date (Labor)");

        **OnCheckWarrantyOnAfterSetWarrantyPartsLabor(Rec, Date, WarrantyParts, WarrantyLabor);  // NEW**

        ServLine.Reset();
        ServLine.SetCurrentKey("Document Type", "Document No.", "Service Item Line No.");
        ServLine.SetRange("Document Type", "Document Type");
        ServLine.SetRange("Document No.", "Document No.");
        ServLine.SetRange("Service Item Line No.", "Line No.");
        ServLine.SetFilter("Quantity Invoiced", '=0');

    **[IntegrationEvent(false, false)]
    local procedure OnCheckWarrantyOnAfterSetWarrantyPartsLabor(var ServiceItemLine: Record "Service Item Line"; Date: Date; var WarrantyParts: Boolean; var WarrantyLabor: Boolean)
    begin
    end;**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
