### ISSUE TITLE
[EventRequest] Codeunit 1105 Transfer GL Entries to CA; OnBeforeGetGLEntries

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7463]
Please, add an Event to funtion **GetGLEntries** with IsHandled.

`LOCAL [IntegrationEvent] OnBeforeGetGLEntries(VAR IsHandled : Boolean)`

_[External] GetGLEntries()_
// new
**IsHandled := FALSE;
OnBeforeGetGLEntries(IsHandled);
IF IsHandled THEN
  EXIT;**

GetCostAccSetup;
SourceCodeSetup.GET;
SourceCodeSetup.TESTFIELD("G/L Entry to CA");
...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
