### ISSUE TITLE
code change request for OnInsert Trigger Transfer Line table

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#7464]
Now in the OnInsert Trigger of the Transfer Line table always a value is assigned to the "Line No." field.
Because we want to adapt the value of the "Line No." field in the OnBeforeInsertEvent event subscriber we would request to make this assignment conditional. We would like this to happen only if the value of the "Line No." field has not been assigned before.

Current Code
![image](https://user-images.githubusercontent.com/48206764/85102884-d963d300-b205-11ea-92b7-f2fe1fafbc75.png)

Suggested Code
![image](https://user-images.githubusercontent.com/48206764/85102972-0f08bc00-b206-11ea-8c87-f4cecee4613f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
