### ISSUE TITLE
[Event-Request] Codeunit 213 - Res. Jnl.-Post Batch

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#7466]
Hi,

Codeunit 213 - Res. Jnl.-Post Batch has no events. Could you add at least the following events? I used  Codeunit 13/23 as a base. I need to know what lines have been posted. 

OnBeforeCode
OnAfterPostResJnlLines

Ans maybe add some more, but it looks like the CodeUnit needs some refactoring for this.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
