### ISSUE TITLE
[Event Request] Table 5814 - Inventory Period - OnBeforeIsValidDate

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7467]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeIsValidDate` to be added to Table 5814 Inventory Period with the following signature:
```pascal
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsValidDate(EndingDate: Date)
    begin
    end;
```

which would be called as follows from `IsValidDate`:
```pascal
    procedure IsValidDate(var EndingDate: Date): Boolean
    var
        InvtPeriod: Record "Inventory Period";
    begin
        OnBeforeIsValidDate(EndingDate);
        InvtPeriod.SetFilter("Ending Date", '>=%1', EndingDate);
        InvtPeriod.SetRange(Closed, true);
        if InvtPeriod.FindLast then
            EndingDate := InvtPeriod."Ending Date"
        else
            exit(true);
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
