### ISSUE TITLE
[Enum Request] Codeunit 1370 - "Batch Post Parameter Types"

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7472]
Dear ALAppExtensions team,

Through this issue we would like to request codeunit 1370 "Batch Post Parameter Types" to be transformed into an extensible enum.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by pri-kise** [comment]
@StanPesotskiy  it is nice to see that you added an enum for "Batch Posting Parameter Type", but at the moment you haven't changed the usage of the codeunit to use the enum instead in the preview of bc17. Is this planned for the next major release (bc17)?
