### ISSUE TITLE
[Event Request] Codeunit 73 - Purch.-Explode BOM - OnBeforeModifyToPurchLine

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7474]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeModifyToPurchLine` to be added to Codeunit 73 Purch.-Explode BOM with the following signature:
```pascal
    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyToPurchLine(var ToPurchLine: Record "Purchase Line"; RecPurchLine: Record "Purchase Line")
    begin
    end;
```
with VAR parameter `ToPurchLine`.

which would be called as follows from `OnRun`:
```pascal
        ToPurchLine := Rec;
        ToPurchLine.Init();
        ToPurchLine.Description := Description;
        ToPurchLine."Description 2" := "Description 2";
        OnBeforeModifyToPurchLine(ToPurchLine, Rec); // << New event
        ToPurchLine.Modify();
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
