### ISSUE TITLE
[EventRequest] Table 1109 Cost Budget Entry; OnBeforeCheckEntries, OnBeforeCompress

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7477]
Please add two new event to function **CheckEntries** and **CompressBudgetEntries** with **IsHandled**.

`LOCAL [IntegrationEvent] OnBeforeCompressBudgetEntries(VAR CostBudgetEntry : Record "Cost Budget Entry";BudName : Code[20];VAR IsHandled : Boolean)`

_[External] CompressBudgetEntries(BudName : Code[20])_
// new
**IsHandled := FALSE;
OnBeforeCompressBudgetEntries(Rec,BudName,IsHandled);
IF IsHandled THEN 
  EXIT;**
// 

IF BudName = '' THEN
  ERROR(Text000);

IF NOT CONFIRM(Text001,TRUE,BudName) THEN
  ERROR('');
...

`LOCAL [IntegrationEvent] OnBeforeCheckEntries(VAR CostBudgetEntry : Record "Cost Budget Entry";VAR IsHandled : Boolean)`

_[External] CheckEntries()_
// new
**IsHandled := FALSE;
OnBeforeCheckEntries(Rec,IsHandled);
IF IsHandled THEN
  EXIT;**
// 

TESTFIELD(Date);
TESTFIELD("Budget Name");
TESTFIELD("Cost Type No.");
...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
