### ISSUE TITLE
[Event Request]Table 5900 - RecreateServLines

### ISSUE THREAD

**Issue by kine** [microsoft/ALAppExtensions#7478]
Hello,
we need to have same events as are in the RecreateSalesLines in tab 36 (SalesHeader) even in the tab 5900 (Service header) on function RecreateServLines. There is no way how to handle related tables before they are cleaned (by calling delete on the lines) and return them back in the process. 

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @kine .
Please be precise, what particular events you want to have in RecreateServLines()?

**Comment by kine** [comment]
Hi @RomanZanizdra 
````
OnBeforeRecreateServLinesHandler - to catch beginning of the process, before confirm is displayed
OnRecreateServLinesOnBeforeConfirm - to handle it fully on our own if needed including hiding confirm etc.
OnRecreateServLinesOnAfterSetServLineFilters - analogy to the OnRecreateSaleslinesOnAfterSetSaesLineFilter to be consistent
OnRecreateServLinesOnBeforeServLineDeleteAll - to save own related entries
OnAfterRecreateServLine  - to add own related entries
OnAfterDeleteAllTempServLines - to clean own temp entries
````

All these are inspired by events in the RecreateSalesLines on SalesHeader (I expect similar parameters).

Thanks

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
