### ISSUE TITLE
[Event Request] Table 5741 - OnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by rodotto** [microsoft/ALAppExtensions#7479]
Please add a new integration event OnBeforeGetDefaultBin(Rec, IsHandled); in Table 5741 (similar to sales line table):

trigger GetDefaultBin(FromLocationCode: Code[10]; ToLocationCode: Code[10])
  var
     IsHandled: Boolean;    
  begin
        **IsHandled := false;
        OnBeforeGetDefaultBin(Rec, IsHandled);
        if IsHandled then
            exit;**

[IntegrationEvent(false, false)]
local procedure OnBeforeGetDefaultBin(var TransferLine: Record "Transfer Line"; var IsHandled: Boolean
begin
end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
