### ISSUE TITLE
[Function Expose] Table 39/5767 - CalcBaseQty

### ISSUE THREAD

**Issue by m2atrd594** [microsoft/ALAppExtensions#748]
Declare function CalcBaseQty of Table 39/5767 as external:

-    LOCAL PROCEDURE CalcBaseQty@14(Qty@1000 : Decimal) : Decimal;
+    [External]
+    PROCEDURE CalcBaseQty@14(Qty@1000 : Decimal) : Decimal;

**Comment by AlexanderYakunin** [comment]
This procedure does not exist anymore and replaced by UOMMgt.CalcBaseQty.
