### ISSUE TITLE
[Event Request] Table 38 - Purchase Header - OnValidate Receiving No. Series/Return Shipment No. Series

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#7483]
Hi Team,
can you please add OnBefore and OnAfter events in "Receiving No. Series" and "Return Shipment No. Series" fields validation? This will be helpful to use custom logics and avoid system to check no. series versus standard setup.
Thank you

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
