### ISSUE TITLE
[Event Request] Table 36 - Sales Header - OnBeforeAssistEdit event cannot return true/false

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#7486]
Hi Team, in case of using OnBeforeAssistEdit event on sales header, if I need to escape standard code using OnBeforeAssistEdit with IsHandled equals to TRUE, I'm not able to set true or false to the procedure's return parameter
![image](https://user-images.githubusercontent.com/49486284/85303150-6a5ad880-b4aa-11ea-9abe-2d57599ec3d1.png)

Thank you

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
