### ISSUE TITLE
[Event Request] Codeunit "Sales-Quote to Invoice" wrong position OnBeforeInsertSalesInvoiceHeader

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#7488]
Hi Team, in codeunit Sales-Quote to Invoice event OnBeforeInsertSalesInvoiceHeader is positioned AFTER record insert. Can you please fix it?
![image](https://user-images.githubusercontent.com/49486284/85303855-5499e300-b4ab-11ea-9103-934e6a220a76.png)

Thank you.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
