### ISSUE TITLE
Make Posting Buffer tables Extensible

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/ALAppExtensions#749]
Buffer tables used in posting are not extensible.

Example: Table 49 - Invoice Post. Buffer.

By Adding a GUID field to these tables and putting that field last in Primary Key these tables should be extensible.

**Comment by ikoletic** [comment]
Seems like this is a duplicate of this [idea](https://experience.dynamics.com/ideas/idea/?ideaid=1935a4ff-b040-e811-a822-0003ff68bbc0) and following conversation on [yammer](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1216893407).

**Comment by gunnargestsson** [comment]
Agreed.  By adding the GUID field we will be able to post-by-description from purchase lines.

**Comment by ikoletic** [comment]
Guess, we can close this one then?

**Comment by gunnargestsson** [comment]
Yes, we can. I need the group by description option as mentioned in the comments on Yammer.
