### ISSUE TITLE
Codeunit 7000 Sales Price Calc. Mgt./CopySalesPriceToSalesPrice procedure

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#7491]
Currently, it shows 

local procedure CopySalesPriceToSalesPrice(var FromSalesPrice: Record "Sales Price"; var ToSalesPrice: Record "Sales Price")
    begin
        with ToSalesPrice do
            if FromSalesPrice.FindSet then
                repeat
                    ToSalesPrice := FromSalesPrice;
                    Insert;
                until FromSalesPrice.Next = 0;
    end;

Is it possible to add an EVENT in the beginning of the procedure with FromSalesPrice,  ToSalesPrice and 'IsHandled' parameters so we could use our own procedure and skip the base BC procedure?  

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
