### ISSUE TITLE
[Event Request] Codeunit 8618 "Config. Excel Exchange": OnBeforeBLOBExport

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#7493]
[Event Request] Codeunit 8618 "Config. Excel Exchange": OnBeforeBLOBExport

We would need to get the InStream object before the exportation from a configuration package to be able to save the Excel to a third party service.

```
procedure ExportExcel(var FileName: Text; var ConfigPackageTable: Record "Config. Package Table"; ExportFromWksht: Boolean; SkipData: Boolean): Boolean
.
.
.
.
DurationAsInt := CurrentDateTime() - StartTime;
SendTraceTag('00009QB', RapidStartTxt, Verbosity::Normal, StrSubstNo(ExcelExportFinishMsg, DurationAsInt, FileName), DataClassification::SystemMetadata);
///////// START
OnBeforeBLOBExport(TempBlob);
///////// END
```

Signature:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeBLOBExport(var TempBlob: Codeunit "Temp Blob")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
