### ISSUE TITLE
Codeunit 60 - local procedure UpdatePrepmtLineAmount change to public procedure

### ISSUE THREAD

**Issue by Mfelice1975** [microsoft/ALAppExtensions#7495]
Please, could we have this change on CU 60: 

OLD:
local procedure UpdatePrepmtLineAmount(SalesHeader: Record "Sales Header")

NEW:
procedure UpdatePrepmtLineAmount(SalesHeader: Record "Sales Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
