### ISSUE TITLE
codeunit 99000813 "Carry Out Action", procedure InsertTransLine

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#7496]
In order to adapt the Line No. and set the NextLineNo with the new value for the transfer line that is inserted, I would like to request an extension of the existing OnInsertTransLineWithReqLine event publisher.

    [IntegrationEvent(false, false)]
    local procedure OnInsertTransLineWithReqLine(var TransferLine: Record "Transfer Line"; var RequisitionLine: Record "Requisition Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInsertTransLineWithReqLine(var TransferLine: Record "Transfer Line"; var RequisitionLine: Record "Requisition Line"; var NextLineNo: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
