### ISSUE TITLE
[Scope OnPrem] TAB 81 - ShowDeferralSchedule

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#7497]
_Method 'ShowDeferralSchedule' is marked for removal. Reason: Function scope will be changed to OnPrem. Tag: 15.1._

What is the alternative in SaaS implementations? How can we show the Deferral Schedules?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
