### ISSUE TITLE
[Event Request] Codeunit 5058 BankCont-Update - OnAfterTransferFieldsFromBankToCont

### ISSUE THREAD

**Issue by SCreanor** [Microsoft/ALAppExtensions#75]
Can an event please be added to codeunit 5057 - VendCont-Update

Event Signature:
**LOCAL [IntegrationEvent] OnAfterTransferFieldsFromBankToCont**(VAR Contact : Record Contact;BankAcc : Record "Bank Account")

Insert code as identified below
![image](https://user-images.githubusercontent.com/39544344/47201561-096e2980-d3c6-11e8-8583-e8f7fd99931b.png)

**Comment by AlexanderYakunin** [comment]
Please do not order events based on NAV 2018 code. We add events based on latest version of D365 BC, this event already exist there.

**Comment by SCreanor** [comment]
Okay, just confirmed, and closing the issue
