### ISSUE TITLE
[Event Request] Table 11000003 (NL) OnValidateSerialNoEntryOnBeforeValidateAmountFromEmplLedgEntry

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#7500]
Source: https://github.com/microsoft/ALAppExtensions/issues/4438

Please changed this Event Publisher so that the IsHandled parameter is  VAR.
Now it doesn't serve any function at all

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
