### ISSUE TITLE
[Event Request] Table 11401 (NL) OnDeleteAppliesToIDOnAfterSetXXXXLedgerEntryFilters

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#7501]
Source: https://github.com/microsoft/ALAppExtensions/issues/4500

Please change this Event Publisher so that the xxxxLedgEntry parameters are set to VAR.
This is a hard requirement to be able to set filters in the subscriber.

New publisher signatures as requested 
```
[IntegrationEvent(false, false)]
local procedure OnDeleteAppliesToIDOnAfterSetCustomerLedgerEntryFilters(var CBGStatementLine: Record "CBG Statement Line"; var CustLedgEntry: Record "Cust. Ledger Entry");

[IntegrationEvent(false, false)]
local procedure OnDeleteAppliesToIDOnAfterSetEmployeeLedgerEntryFilters(var CBGStatementLine: Record "CBG Statement Line"; var EmployeeLedgEntry: Record "Employee Ledger Entry");

[IntegrationEvent(false, false)]
local procedure OnDeleteAppliesToIDOnAfterSetVendorLedgerEntryFilters(var CBGStatementLine: Record "CBG Statement Line"; var VendorLedgEntry: Record "Vendor Ledger Entry");

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
