### ISSUE TITLE
[Event Request] Codeunit 7000006 Document-Post - OnCloseBillGroupIfEmptyOnAfterPostedCarteraDocSetFilter

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#7502]
We need a new event in Codeunit 7000006 "Document-Post":

**LOCAL [IntegrationEvent] OnCloseBillGroupIfEmptyOnAfterPostedCarteraDocSetFilter(VAR PostedCarteraDoc : Record "Posted Cartera Doc.")**

Called from:

_**[External] CloseBillGroupIfEmpty(PostedBillGroup : Record "Posted Bill Group";PostingDate : Date)**_
WITH PostedCarteraDoc DO BEGIN
  RESET;
  SETCURRENTKEY("Bill Gr./Pmt. Order No.",Status);
  SETRANGE("Bill Gr./Pmt. Order No.",PostedBillGroup."No.");
  SETRANGE(Type,Type::Receivable);
  SETRANGE(Status,Status::Open);
  **//INIT-INSERT  
  OnCloseBillGroupIfEmptyOnAfterPostedCarteraDocSetFilter(PostedCarteraDoc);
  //END-INSERT**
  IF NOT FIND('-') THEN BEGIN
    SETRANGE(Status);
    FIND('-');
    REPEAT
      ClosedCarteraDoc.TRANSFERFIELDS(PostedCarteraDoc);
      ClosedCarteraDoc.INSERT;
      CustLedgEntry.GET(ClosedCarteraDoc."Entry No.");
      CustLedgEntry."Document Situation" := CustLedgEntry."Document Situation"::"Closed BG/PO";
      CustLedgEntry.MODIFY;
    UNTIL NEXT = 0;
    DELETEALL;
    ClosedBillGroup.TRANSFERFIELDS(PostedBillGroup);
    ClosedBillGroup."Closing Date" := PostingDate;
    ClosedBillGroup.INSERT;
    PostedBillGroup.DELETE;
  END;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
