### ISSUE TITLE
[Event Modification] Table 37 - Sales Line OnBeforeCheckItemAvail()

### ISSUE THREAD

**Issue by NeilHalliday** [microsoft/ALAppExtensions#7503]
Hi,

Please can the OnBeforeCheckItemAvail() publisher be updated so that the SalesLine record is a var?

![image](https://user-images.githubusercontent.com/17927660/85404678-35f12600-b557-11ea-9c6d-b998b9ecb30c.png)

Thanks
Neil.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
