### ISSUE TITLE
[Event Request] Codeunit 5751 "Get Source Doc. Inbound", function: GetSingleInboundDoc

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#7504]
Could you please add a publisher in Codeunit 5751 "Get Source Doc. Inbound", function: GetSingleInboundDoc

    procedure GetSingleInboundDoc(var WhseReceiptHeader: Record "Warehouse Receipt Header")
    var
        WhseRqst: Record "Warehouse Request";
        SourceDocSelection: Page "Source Documents";
        IsHandled: Boolean;
    begin
        OnBeforeGetSingleInboundDoc(WhseReceiptHeader, IsHandled);
        if IsHandled then
            exit;

        Clear(GetSourceDocuments);
        WhseReceiptHeader.Find;

        WhseRqst.FilterGroup(2);
        WhseRqst.SetRange(Type, WhseRqst.Type::Inbound);
        WhseRqst.SetRange("Location Code", WhseReceiptHeader."Location Code");
        WhseRqst.FilterGroup(0);
        WhseRqst.SetRange("Document Status", WhseRqst."Document Status"::Released);
        WhseRqst.SetRange("Completely Handled", false);

        // New Event
        OnSetWhseRqstFilterForSourceDocSelection(WhseRqst, WhseReceiptHeader);

        SourceDocSelection.LookupMode(true);
        SourceDocSelection.SetTableView(WhseRqst);
        if SourceDocSelection.RunModal <> ACTION::LookupOK then
            exit;
        SourceDocSelection.GetResult(WhseRqst);

    [IntegrationEvent(false, false)]
    local procedure OnSetWhseRqstFilterForSourceDocSelection(var WhseRqst: Record "Warehouse Request"; var WhseReceiptHeader: Record "Warehouse Receipt Header");
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
