### ISSUE TITLE
[Event Request] Codeunit 7322 "Create Inventory Pick/Movement", function: GetWhseRequest

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#7505]
Could you please add a publisher in Codeunit 7322 "Create Inventory Pick/Movement", function: GetWhseRequest

    local procedure GetWhseRequest(var WhseRequest: Record "Warehouse Request"): Boolean
    begin
        with WhseRequest do begin
            FilterGroup := 2;
            SetRange(Type, Type::Outbound);
            SetRange("Location Code", WhseActivHeader."Location Code");
            SetRange("Document Status", "Document Status"::Released);
            if WhseActivHeader."Source Document" <> 0 then
                SetRange("Source Document", WhseActivHeader."Source Document")
            else
                if WhseActivHeader.Type = WhseActivHeader.Type::"Invt. Movement" then
                    SetFilter("Source Document", '%1|%2|%3',
                      WhseActivHeader."Source Document"::"Prod. Consumption",
                      WhseActivHeader."Source Document"::"Prod. Output",
                      WhseActivHeader."Source Document"::"Assembly Consumption");
            if WhseActivHeader."Source No." <> '' then
                SetRange("Source No.", WhseActivHeader."Source No.");
            SetRange("Completely Handled", false);

            // New Event
            OnSetWhseRqstFilterForGetWhseRequest(WhseRequest, WhseActivHeader);

            FilterGroup := 0;
            if PAGE.RunModal(PAGE::"Source Documents", WhseRequest, "Source No.") = ACTION::LookupOK then
                exit(true);
        end;
    end;

[IntegrationEvent(false, false)]
local procedure OnSetWhseRqstFilterForGetWhseRequest(var WhseRqst: Record "Warehouse Request"; var WhseActivHeader: Record "Warehouse Activity Header");
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
