### ISSUE TITLE
[Event Request] Report 7323 "Create Invt Put-away/Pick/Mvmt", DataItem "Warehouse Request"

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#7506]
Could you please add a publisher in Report 7323 "Create Invt Put-away/Pick/Mvmt", DataItem "Warehouse Request"

`    dataset
    {
        dataitem("Warehouse Request"; "Warehouse Request")
        {
            DataItemTableView = SORTING("Source Document", "Source No.");
            RequestFilterFields = "Source Document", "Source No.";

            trigger OnAfterGetRecord()
            var
                ATOMvmntCreated: Integer;
                TotalATOMvmtToBeCreated: Integer;
            begin
                Window.Update(1, "Source Document");
                Window.Update(2, "Source No.");

                case Type of
                    Type::Inbound:
                        TotalPutAwayCounter += 1;
                    Type::Outbound:
                        if CreatePick then
                            TotalPickCounter += 1
                        else
                            TotalMovementCounter += 1;
                end;

                if CheckWhseRequest("Warehouse Request") then
                    CurrReport.Skip();

                // New Event
                if CheckWhseRequestExternal("Warehouse Request") then
                    CurrReport.SKIP;

`

local procedure CheckWhseRequestExternal(var WarehouseRequest: Record "Warehouse Request") : Boolean;
    VAR
      SkipRecord: Boolean;
    begin
      SkipWhseRequestRecord(WarehouseRequest,SkipRecord);
      EXIT(SkipRecord);
    end;

[IntegrationEvent(false, false)]
local procedure SkipWhseRequestRecord(var WarehouseRequest: Record "Warehouse Request"; var SkipRecord: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
