### ISSUE TITLE
[Event Request]: Report 10406 "Bank Rec. Process Lines"

### ISSUE THREAD

**Issue by simcrest** [microsoft/ALAppExtensions#7507]
In Procedure SuggestLines() the following code is not allowing to do subscribers. The code needs to be rewritten so a subscriber can be used to include new fields to be added to the Bank Rec Lines from Bank Account Ledger entries and Check Ledger Entries.

The code below transfers information from the check ledger entries to the bank rec line:
![image](https://user-images.githubusercontent.com/15910725/85412549-b0aa4900-b537-11ea-9127-a20fd860c324.png)

The following code (just after the code above) transfers information from the Bank account ledger to the bank rec lines. 
![image](https://user-images.githubusercontent.com/15910725/85412927-22829280-b538-11ea-9e02-71edac5df88f.png)

We request that code is rewritten to allow custom transfer of information from bank and check ledger to bank rec lines. Thanks

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
