### ISSUE TITLE
[Event Request] - Codeunit 1005 on methods CreateJT and PostDiffBuffer

### ISSUE THREAD

**Issue by jorgecorreia27** [microsoft/ALAppExtensions#7508]
Dear all,
In the course of a development in Business Central related to Jobs, in the Job Journal there is an action to Calculate the Remaining Usage for the Jobs. This action calls the "Job Calc. Remaining Usage" Report (R1090) which, for each Job Planning Line, subsequently calls the Codeunit in question (Codeunit "Job Calculate Batches"), passing by parameter the Job Planning Line and assigning their values to a variable JobDiffBuffer (temporary) and then insert it. In this specific development it is asked that the quantity is calculated not from this standard process but from the subtraction of two fields wich were subsequently created in the "Job Planning Line". From the way the standard code is implemented now, the solution is to comment the standard code in the CreateJT function where the quantity is assigned the value from the field quantity in the Job Planning Line and then subtract the values of those two fields created in the Job Planning Lines. The goal would be to not comment standard code, so the request would be to add an Event after the insertion of those JobDiffBuffer where it would be passed by parameter the JobDiffBuffer variable in question and the current JobPlanningLine and then override the Quantity Value in the JobDiffBuffer with the one we would like it so that we could subscribe this event in a new codeunit and not interfering with the standard code.
In the images below there is a suggested example of a solution:
[Note]: Between the comment lines are the suggestion of changes made
![image](https://user-images.githubusercontent.com/37341299/85398571-57e5ab00-b54d-11ea-8706-1b865b6aa4d5.png)
And the subscriber of the publisher created above in a new Codeunit
![image](https://user-images.githubusercontent.com/37341299/85398677-819ed200-b54d-11ea-9dfd-0d7e096342e6.png)

The next request is related to this previous one. After the "Job Calc. Remaining Quantity" Report goes through all Job Planning Lines and execute the CreateJT method in the Job Calculate Batches Codeunit, on the OnPostReport trigger, it executes the PostDiffBuffer method in the same codeunit. In the standard Code, this method checks if are any Records of the JobDiffBuffer (filled in the CreateJT method) goes through the "Job Ledger Entries" Records which are applied a number of filters to check if for that Job there are have ben already any entries to, then, be subtracted to the quantity in the JobDiffBuffer. But we would like the code flow to have a different logic, so, in the below pictures there is an example of what could be a solution. Please note that IsHandled is a local variable.

[Note]: Between the comment lines are the suggestion of changes made
![image](https://user-images.githubusercontent.com/37341299/85398786-a2ffbe00-b54d-11ea-9637-1bc28395ed97.png)
And the subscriber of the publisher created above in a new Codeunit
![image](https://user-images.githubusercontent.com/37341299/85398853-b90d7e80-b54d-11ea-8a2d-756444411491.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
