### ISSUE TITLE
[Event Request]Application “Tests-User”, 134202 "Document Approval - Users"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7522]
Could you please insert the OnTestInitialize Event at the beginning of each test procedure (or a procedure called by it):

![pic1](https://user-images.githubusercontent.com/45795262/85574605-3660ee00-b637-11ea-8b52-c8b316dada19.png)
![pic2](https://user-images.githubusercontent.com/45795262/85574616-38c34800-b637-11ea-8528-d773bd15e44b.png)

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
