### ISSUE TITLE
[Event Request] Table 10740 No Taxable Entry (ES localization)

### ISSUE THREAD

**Issue by pjllaneras** [microsoft/ALAppExtensions#7529]
This table has some procedures to copy (or init) data from some sources (gen. journal line, Vendor Ledger Entry, Customer Ledger Entry, ...), but any of them has an event to interact with this table.

Please add events like OnAfterInitFromGenJnlLine(Rec, GenJournalLine) at the end of InitFromGenJnlLine procedure... and similar events in the other InitFrom[some table] procedures.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
