### ISSUE TITLE
[EventRequest] Codeunit 5631"FA Jnl.-Check Line" OnBeforeCheckJobNo

### ISSUE THREAD

**Issue by josnelissen** [microsoft/ALAppExtensions#7537]
For our cTrade solution we are in need of a new Event so we can skip the TestField on "Job No."

Code change:
![image](https://user-images.githubusercontent.com/30867508/85694049-1123bc80-b6d7-11ea-9813-6a32a57b4b83.png)

Event:
![image](https://user-images.githubusercontent.com/30867508/85694085-1aad2480-b6d7-11ea-938d-84ea880005e3.png)

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
