### ISSUE TITLE
[Event Request] Codeunit 5922 - OnRun OnBeforeShowMessageServiceQuoteToOrder

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#7538]
Hi, we would like to have event in the following place because we want to open Order instead of just showing the message.
Picture of implementation:
![image](https://user-images.githubusercontent.com/54843470/85694773-bb034900-b6d7-11ea-8660-c8a194d362d2.png)

Code implementation:
```
+++NEW
        OnBeforeShowMessageServiceQuoteToOrder(Rec, ServQuoteToOrder.ReturnOrderNo, HideMessage);
        if not HideMessage then
---NEW
            Message(Text001, "No.", ServQuoteToOrder.ReturnOrderNo);
```
Integration Event:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowMessageServiceQuoteToOrder(var Rec: Record "Service Header"; OrderNo: Code[20];var HideMessage: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
