### ISSUE TITLE
[EventRequest] Table 81 "Gen. Journal Line" OnBeforeCheckAccountType

### ISSUE THREAD

**Issue by josnelissen** [microsoft/ALAppExtensions#7539]
For our cTrade solution we are in need of a new Event so we can skip the TestField on "Account Type"

Code Change:
![image](https://user-images.githubusercontent.com/30867508/85696564-56e18480-b6d9-11ea-8e6c-8d2dc5e630e1.png)

Event:
![image](https://user-images.githubusercontent.com/30867508/85696604-5d6ffc00-b6d9-11ea-93d1-5e8920aa8ef5.png)

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
