### ISSUE TITLE
[Access Request] Page 161 Purchase Statistics

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#7544]
Hello,

We would like to have access to the following variables in the `Purchase Statistics` page;
```
protected var
    VATAmount: Decimal;
    TotalPurchLine: Record "Purchase Line";
    TotalPurchLineLCY: Record "Purchase Line";
```

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
