### ISSUE TITLE
[Access Request] Page 344 Navigation - SetSource

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#7547]
Hello, could you please make the `SetSource` procedure protected, so we can call it from our extension?

```
protected procedure SetSource(PostingDate: Date; DocType2: Text[100]; DocNo: Text[50]; SourceType2: Integer; SourceNo2: Code[20])
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
