### ISSUE TITLE
[Access Request] Page 344 Navigate - PstdPhysInvtOrderHdr

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#7548]
Hello, would you make the global variable `PstdPhysInvtOrderHdr` protected please? That way we can access it in out extension.

```
protected var
.
.
.
    [SecurityFiltering(SecurityFilter::Filtered)]
    PstdPhysInvtOrderHdr: Record "Pstd. Phys. Invt. Order Hdr";
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
