### ISSUE TITLE
[Function Expose] Codeunit 2616 - Printer Setup - Get "Printer Type" for Printer

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7549]
Dear ALAppExtensions team,
Through this issue we would like to ask whether it would be possible to have a procedure added to codeunit 2616 Printer Setup that allows you to check if a printer is a Local Printer or Cloud Printer, e.g., given the `PrinterName` as parameter.
More or less, what is done in codeunit 2617 "Printer Setup Impl." in procedure `GetPrinterCategory`.
We would like to be able to check, _in an on-premise installation_, whether we are dealing with a Cloud Printer, so if you don't want to expose it for target=Cloud, then [Scope('OnPrem')] would work fine for us.

**Comment by mazhelez** [comment]
Hey @rvanbekkum 

Since the function you want exposed lives in the System Application, how do you feel about going ahead and contributing with the solution you need?

It looks like a trivial thing to do so it'll be a tiny PR 😃

**Comment by rvanbekkum** [comment]
Dear @mazhelez,

Thank you for your reply and your suggestion. I will give making a PR for this a try 😉.

**Comment by mazhelez** [comment]
Awesome! 👍 Can't wait to see the result!

Documenting the process of contributing to the repo is on the way, but meanwhile, do not hesitate to ask questions.
