### ISSUE TITLE
[Enum/Usability Request] Table 7355 - Report Selection Warehouse - Usage

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#7550]
Dear ALAppExtensions team,
We have seen the request in issue #7166 and saw it is going to be available in a future release. In this issue we have an additional request related to this: could the enum members be integrated into the "Report Selection Usage" enum?
That is, the most probably reason it was moved to a different table (and now enum) was that the developers were running out of space for these new option members, but now with enums this shouldn't form an issue anymore.

We hope to see your thoughts on this. Thanks in advance for your reply or otherwise time and efforts.

**Comment by AlexanderYakunin** [comment]
This is large rework and breaking change for all partners and customers. It would be nice to have one enum instead of two, but considering all factors finally decided not doing this.
