### ISSUE TITLE
New procedure in Codeunit 3024 DotNet_URI 

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#7551]
Hi al-team,

I think it would be helpful if there was a "URL combine" function in the Base App. 
With the Uri class it is possible to realize something like this.
It would be great if you could add this or a similar function to the DotNet_URI codeunit.

```
procedure CombineUri(BaseUri: Text; ToCombineUri: Text): Text;
    var
        DotNetUri2: DotNet Uri;
    begin
        DotNetUri := DotNetUri.Uri(DotNetUri2.Uri(BaseUri),ToCombineUri);
        exit(DotNetUri.ToString());
    end;
```

**Comment by mazhelez** [comment]
Hey @MattiLE 

It's indeed a great idea 👍  However, it looks like this functionality is more suitable for the _System Application_. 
How do you feel about contributing by making a module that handles the .Net URI class?

Sure, most of the functionality already exists in the _Base Application_, but there's more that can added (`CombineUri` as a lead example).

**Comment by mazhelez** [comment]
@MattiLE there's a new URI module on the way in the new release (17.0)

Since the requested functionality isn't part of the .Net class itself (it's more like a helper function), it won't be included in the module. However, if you think there's value for the AL developers, you can still contribute by adding it!

**Comment by MattiLE** [comment]
Hi @mazhelez, thanks for the feedback.
I will take a look at the new module when it is released and then contribute an addition if necessary. :)

**Comment by mazhelez** [comment]
Sounds great!

I'll now close the issue. Feel free to reopen it if needed.
