### ISSUE TITLE
Event Requested for Codeunit 333 Req.Wksh - Make Order/Code Procedure 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#7553]
local procedure "Code"(var ReqLine: Record "Requisition Line")
                    .
                    .
                    .
                    ReqLine3.SetRange("Worksheet Template Name", "Worksheet Template Name");
                    ReqLine3.SetRange("Journal Batch Name", "Journal Batch Name");
--------------**We would like to add more SETRANGE filter here**  (ReqLine, ReqLine3) 
                    if not ReqLine3.FindLast then
                        if IncStr("Journal Batch Name") <> '' then begin
                            ReqWkshName.Get("Worksheet Template Name", "Journal Batch Name");
                            NewReqWkshName := true;
                            OnCheckNewNameNeccessary(ReqWkshName, NewReqWkshName);
                            if NewReqWkshName then begin
                                ReqWkshName.Delete();
                                ReqWkshName.Name := IncStr("Journal Batch Name");
                                if ReqWkshName.Insert() then;
                                "Journal Batch Name" := ReqWkshName.Name;
                            end;
                        end;

Thanks very much.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
