### ISSUE TITLE
[Event Request] Report “Calc. and Post VAT Settlement” - New Event “OnBeforePrintVATEntries”

### ISSUE THREAD

**Issue by StSdt** [microsoft/ALAppExtensions#7557]
Could we please have a new publisher “OnBeforePrintVATEntries” at the beginning of trigger “OnAfterGetRecord” for dataitem “VAT Entry” of Report 20 "Calc. and Post VAT Settlement"?

```
trigger OnAfterGetRecord()
  begin
    // >>>>>>>>
    OnBeforePrintVATEntries(“VAT Entry”);
    // <<<<<<<<
    if not PrintVATEntries then
      CurrReport.Skip();
    end;
  end;

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnBeforePrintVATEntries(var VATEntry: Record “VAT Entry”)
begin
end;
// <<<<<<<<  
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
