### ISSUE TITLE
[Extensibility enhancement] Codeunit 12 new parameters for OnBeforeInitGLEntry

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#7560]
Hello, please add the following parameters to the OnBeforeInitGLEntry event in codeunit 12 Gen Jnl. Post Line:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitGLEntry(var GenJournalLine: Record "Gen. Journal Line"; GLAccNo: Code[20]; SystemCreatedEntry: Boolean)
    begin
    end;
```

And modify the InitGLEntry procedure accordingly:

```

    procedure InitGLEntry(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; GLAccNo: Code[20]; Amount: Decimal; AmountAddCurr: Decimal; UseAmountAddCurr: Boolean; SystemCreatedEntry: Boolean)
    var
        GLAcc: Record "G/L Account";
    begin
        OnBeforeInitGLEntry(GenJnlLine, GLAccNo, SystemCreatedEntry);
        [...]
    end;
```

Thanks

**Comment by AlexanderYakunin** [comment]
We cannot change signature of public procedure InitGLEntry, so your request cannot be implemented. Please make another suggestion,

**Comment by f0ffee** [comment]
Hi there, I didn't suggest to change the signature of the InitGLEntry procedure; my suggestion regards the event OnBeforeInitGLEntry.

Here it is, from a recent daily:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitGLEntry(var GenJournalLine: Record "Gen. Journal Line")
    begin
    end;
```

And here's how I suggested it should become:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitGLEntry(var GenJournalLine: Record "Gen. Journal Line"; GLAccNo: Code[20]; SystemCreatedEntry: Boolean)
    begin
    end;
```

What should be changed in the InitGLEntry procedure is just how this event is raised.

I kindly ask you to please reconsider my proposal.

Thank you!

**Comment by AlexanderYakunin** [comment]
Clear, we will add parameters

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
