### ISSUE TITLE
[Event Request] Table 37 "Sales Line , function: CheckAsmToOrder

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#7561]
Could you please add a publisher in Table 37 "Sales Line , function: CheckAsmToOrder

    procedure CheckAsmToOrder(AsmHeader: Record "Assembly Header")
    begin
// New Event Start

        IsHandled := false;
        OnBeforeCheckAsmToOrder(Rec, IsHandled);
        if IsHandled then
            exit;
// New Event End

        TestField("Qty. to Assemble to Order", AsmHeader.Quantity);
        TestField("Document Type", AsmHeader."Document Type");
        TestField(Type, Type::Item);
        TestField("No.", AsmHeader."Item No.");
        TestField("Location Code", AsmHeader."Location Code");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckAsmToOrder(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
