### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" – New Event “OnRecreatePurchLinesOnBeforePurchLineFindSet”

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7562]
[Event Request] Table 38 "Purchase Header" – New Event “OnRecreatePurchLinesOnBeforePurchLineFindSet”

Could we please have an new publisher OnRecreatePurchLinesOnBeforePurchLineFindSet in Table 38 "Purchase Header" in Function "RecreatePurchLines"?

`PurchLine.Reset();`
`PurchLine.SetRange("Document Type", "Document Type");`
`PurchLine.SetRange("Document No.", "No.");`
New Event Begin
`OnRecreatePurchLinesOnBeforePurchLineFindSet(PurchLine);`
New Event End
`if PurchLine.FindSet then begin`
  `repeat`
  `PurchLine.TestField("Quantity Received", 0);`
 ` ...`

`[IntegrationEvent(false, false)]`
`local procedure OnRecreatePurchLinesOnBeforePurchLineFindSet(var PurchaseLine: Record "Purchase Line")`
`begin`
`end;`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
