### ISSUE TITLE
[Event Request] Codeunit Sales-Post Prepayments OnAfterPostPrepaymentsOnBeforeThrowPreviewModeError

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#7563]
Hi,
in prepayment posting I guess we have no chance to know if we're running in preview mode or not.

Can we add for example "PreviewMode" to OnAfterPostPrepaymentsOnBeforeThrowPreviewModeError event?
and something like "OnBeforeThrowPreviewError" used in codeunit 13?

Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
