### ISSUE TITLE
[Event Request] Codeunit 5611 Function TransferValues-->OnAfterTransferValues

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#7564]
Please add **DeprMethod** parameter under function TransferValues-->OnAfterTransferValues
.................
            AcquisitionDate := "Acquisition Date";
            DisposalDate := "Disposal Date";
            PercentBelowZero := "Depr. below Zero %";
            AmountBelowZero := "Fixed Depr. Amount below Zero";
            DaysInFiscalYear := DeprBook."No. of Days in Fiscal Year";
            if DaysInFiscalYear = 0 then
                DaysInFiscalYear := 360;
            Year365Days := DeprBook."Fiscal Year 365 Days";
            if Year365Days then begin
                DaysInFiscalYear := 365;
                DeprYears :=
                  DepreciationCalc.DeprDays(
                    "Depreciation Starting Date", "Depreciation Ending Date", true) / DaysInFiscalYear;
            end;
        end;
       **OnAfterTransferValues(FA, FADeprBook, Year365Days, DeprYears);**                          //Old
       **OnAfterTransferValues(FA, FADeprBook, Year365Days, DeprYears,DeprMethod);**    //New

[IntegrationEvent(false, false)]
local procedure OnAfterTransferValues(FixedAsset: Record "Fixed Asset"; FADepreciationBook: Record "FA Depreciation Book"; Year365Days: Boolean; var DeprYears: Decimal;**var DeprMethod : Option**)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
