### ISSUE TITLE
[Event Request] Page 5199 - Attendee Scheduling -> Add an event publisher on Page Action "Send Invitations"

### ISSUE THREAD

**Issue by KiazY** [microsoft/ALAppExtensions#7565]
Dear Microsoft,
I'm opening this issue to request an event publisher for the Page Action "Send Invitations" (Action43), Page 5199 (Attendee Scheduling), just before the function SendMAPIInvitations(Rec,FALSE) like shown in the picture:

![image](https://user-images.githubusercontent.com/37196811/86027918-2aa36c00-ba29-11ea-9646-7acc84823f90.png)

The purpose is to change the current behaviour of the Action and apply a different logic.

Thank you in advance.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
