### ISSUE TITLE
Table 172 - Standard Customer Sales Code - CreateSalesInvoice

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#7566]
We would like to request 2 publishers in function CreateSalesInvoice of table 172 standard customer sales code:

    procedure CreateSalesInvoice(OrderDate: Date; PostingDate: Date)
    var
        SalesHeader: Record "Sales Header";
    begin
        TestField(Blocked, false);
        SalesHeader.Init();
        SalesHeader."No." := '';
        SalesHeader."Document Type" := SalesHeader."Document Type"::Invoice;
        >>  OnCreatesalesInvoiceOnBeforeInsertSalesHeader(VAR SalesHeader, Rec);
        SalesHeader.Insert(true);
        SalesHeader.Validate("Sell-to Customer No.", "Customer No.");
        SalesHeader.Validate("Order Date", OrderDate);
        SalesHeader.Validate("Posting Date", PostingDate);
        SalesHeader.Validate("Document Date", OrderDate);
        if "Payment Method Code" <> '' then
            SalesHeader.Validate("Payment Method Code", "Payment Method Code");
        if "Payment Terms Code" <> '' then
            SalesHeader.Validate("Payment Terms Code", "Payment Terms Code");
        if "Direct Debit Mandate ID" <> '' then
            SalesHeader.Validate("Direct Debit Mandate ID", "Direct Debit Mandate ID");
        >> OnCreatesalesInvoiceOnBeforeModifySalesHeader(VAR SalesHeader, Rec);
        SalesHeader.Modify();

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
