### ISSUE TITLE
[Event Change] Document Attachment Details - OnAfterOpenForRecRec

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#7567]
Hello everyone, 

just in order to adapt our functionality to the standard procedure, it would be nice if you could pass in this event the FlowField "FlowFieldsEditable", just as follows:

**Event Position**

         
          SetRange("Line No.", LineNo);

                    FlowFieldsEditable := false;
                end;
        end;

        OnAfterOpenForRecRef(Rec, RecRef, FlowFieldsEditable);
    end;

**Event Declaration**

```
[IntegrationEvent(false, false)]
    local procedure OnAfterOpenForRecRef(var DocumentAttachment: Record "Document Attachment"; var RecRef: RecordRef; var FlowFieldsEditable: Boolean)
    begin
    end;

```

Kind regards.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
