### ISSUE TITLE
Table 36 "Sales Header" OnRename

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#7568]
We need a new Event Function in Table 36 “Sales Header”, named OnBeforeSalesHeaderRename.

We need this:

OnRename()
OnBeforeSalesHeaderRename(IsHandled);
IF IsHandled THEN
  EXIT;

ERROR(Text003,TABLECAPTION);

**Comment by SoniaIbermatica** [comment]
The event OnBeforesalesHeaderRename has to have two parameters:

OnRename()
OnBeforeSalesHeaderRename(SalesHeader,IsHandled);
IF IsHandled THEN
  EXIT;
ERROR (Text003,TABLECAPTION);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SoniaIbermatica** [comment]
Sorry. I have asked you wrongly for the parameters.
They should be like this:

OnRename()
OnBeforeSalesHeaderRename(Rec,xRec,IsHandled)
IF IsHandled THEN
  EXIT;
ERROR (Text003,TABLECAPTION);

**Comment by StanPesotskiy** [comment]
Please verify what was implemented in the latest build and create a new request for an additional parameter.
