### ISSUE TITLE
[Enum Request] Table 99000772 "Production BOM Line" Field 10 Type

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#757]
Please make field 10 Type in table 9900072 "Production BOM Line" an enum.

**Comment by AlexanderYakunin** [comment]
This is Option field. What is enum?

**Comment by GuntherGebauer** [comment]
?? You do not know, what an enum is ?
We want to add Option Type::=Blank to add Commentlines similar to SalesLine.Type and Purchline.Type, which is only possible if this field is changed from option to enum.

**Comment by GuntherGebauer** [comment]
??? Of Course in AL for BC the type Enum is available
![image](https://user-images.githubusercontent.com/38500557/51250794-dc66ee00-1997-11e9-8baf-a9472851ae80.png)


and Enumtypes can be used and added from table extensions whereas for optionfields new Options cannot be added

**Comment by JesperSchulz** [comment]
Sorry, the issue was tagger wrongly initially and ended at the wrong team. I'll do some housekeeping and make sure your request ends on the correct team. Sorry about the confusion!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
