### ISSUE TITLE
[Code Change Request] Codeunit 7322 "Create Inventory Pick/Movement" - procedure CreatePickOrMoveLine - Local to global

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#7570]
We need to call the procedure "CreatePickOrMoveLine" in Codeunit 7322 "Create Inventory Pick/Movement" from our own code.
Please change procedure from local to global.

OLD CODE:
`local procedure CreatePickOrMoveLine(NewWhseActivLine: Record "Warehouse Activity Line"; var RemQtyToPickBase: Decimal; OutstandingQtyBase: Decimal; ReservationExists: Boolean)`

NEW CODE:
`procedure CreatePickOrMoveLine(NewWhseActivLine: Record "Warehouse Activity Line"; var RemQtyToPickBase: Decimal; OutstandingQtyBase: Decimal; ReservationExists: Boolean)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
