### ISSUE TITLE
Table 210 - event request - OnValidate "Job Task No."

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#7571]
Requesting a new event in table 210 to control validation of Job Task No.

![image](https://user-images.githubusercontent.com/28901234/86132655-b7f0ca00-bad6-11ea-8bea-b00bbd3c7b5e.png)

**LOCAL [IntegrationEvent] OnBeforeValidateJobTaskNo(VAR JobJournalLine : Record "Job Journal Line";VAR xJobJournalLine : Record "Job Journal Line";VAR IsHandled : Boolean)**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
