### ISSUE TITLE
Please convert Option field Document Type to enum in Table Handled IC Outbox Trans.

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#7588]
Hi Team,

Please convert Option field "Document Type" to enum in Table "Handled IC Outbox Trans." in business central.

Also below all 4 Tables have same filed Document Type with same options. So for all please create a 1 enum. 

414 | IC Outbox Transaction
416 | Handled IC Outbox Trans.
418 | IC Inbox Transaction
420 | Handled IC Inbox Trans.

Best Regards,
Ratnesh Awasthi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
