### ISSUE TITLE
Codeunit 1012 "Job Jnl.-Post Line" - Integration Event "OnAfterCopyJobJnlLine" - Change Parameter to "var"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#7589]
According closed Issue #553, the parameter JobJournalLine2 needs to be "var" in order to make sense!

OLD CODE:
`local procedure OnAfterCopyJobJnlLine(var JobJournalLine: Record "Job Journal Line"; JobJournalLine2: Record "Job Journal Line")`

NEW CODE:
`local procedure OnAfterCopyJobJnlLine(var JobJournalLine: Record "Job Journal Line"; var JobJournalLine2: Record "Job Journal Line")`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
