### ISSUE TITLE
Enum required for Field  field "Del. Rem. Date Field"  in Table Delivery Reminder Line

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#7590]
Hi Team,

Please create enum for option  field "Del. Rem. Date Field"  in Table "Delivery Reminder Line" in business Central

Best Regards,
Ratnesh Awasthi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
