### ISSUE TITLE
Enum required for Field Blocked in Table Customer

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#7591]
Hi Team,

Please create Enum  for Field Blocked in Table Customer.

Best Regards,
Ratnesh Awasthi

**Comment by AlexanderYakunin** [comment]
This is already implemented, which version you are looking into?

**Comment by raawasthi** [comment]
I am using Business Central 2020 Wave 1 since Feb or March. I think I need to move it to latest update ?

**Comment by raawasthi** [comment]
Hi Alexander ,

I have checked in Business central 16.3 which is released 2 days before and it does not contain the mentioned enum.

In which version it is introduced according to you ?

Best Regards,
Ratnesh Awasthi

**Comment by raawasthi** [comment]
> This is already implemented, which version you are looking into?

16.3 Not available.

**Comment by AlexanderYakunin** [comment]
Check this https://github.com/Microsoft/ALAppExtensions/blob/master/FAQ.md#what-do-all-the-labels-assigned-to-issues-mean to get more information about implementation
