### ISSUE TITLE
Enum required in field "Cross-Reference Type"(Field 5707) in Table Sales Line

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#7593]
Hi Team,

Please create Enum for field "Cross-Reference Type"(Field 5707) in Table "Sales Line".

Also same option is used in field "Cross-Reference Type" of  table 5717 "Item Cross Reference" . Same enum can be used at two places.

Best Regards,
Ratnesh Awasthi

**Comment by AlexanderYakunin** [comment]
This feature is obsoleted and replaced by Item Reference for October release.  New Item Reference support 50 char numbers. We already have this enum in Item Reference, would you consider that for your extension?
