### ISSUE TITLE
Enum required in Option field "Default Del. Rem. Date" of Table "Purchases & Payables Setup"

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#7595]
Hi Team,

Enum is required in Option field "Default Del. Rem. Date" of Table "Purchases & Payables Setup"

Please create it.

Best Regards,
Ratnesh Awasthi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
