### ISSUE TITLE
Codeunit 1023 New event publisher "OnBeforeRunJobJnlPostBatch"

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#7597]
Requesting a new event publisher in codeunit 1023 "Job Jnl.-B.Post", function Code.

![image](https://user-images.githubusercontent.com/28901234/86233356-d1504f80-bb84-11ea-8be3-ea98f6e9106d.png)

**LOCAL [IntegrationEvent] OnBeforeRunJobJnlPostBatch(VAR JobJournalLine : Record "Job Journal Line";VAR JobJournalBatch : Record "Job Journal Batch")**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
