### ISSUE TITLE
Enum is required for option field "Sales Type" in Table 7023 "Sales Price Worksheet"   

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#7598]
Hi Team,

Enum is required for option field "Sales Type" in Table 7023 "Sales Price Worksheet"   

We need this while we are upgrading from CAL to AL.

Best Regards,
Ratnesh Awasthi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
