### ISSUE TITLE
Enum is required for option field "No. Format" in table 5719 "Nonstock Item Setup"

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#7599]
Hi Team,

Enum is required for option field "No. Format" in table 5719 "Nonstock Item Setup".

It is required for one of our customisation.

Best Regards,
Ratnesh Awasthi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
