### ISSUE TITLE
[Field Resquest] County Code - Table Post Code

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/ALAppExtensions#76]
Hi,

I can't find field County Code in the Table Post Code however I can see the County Code when I run the table Client table.

Using AL : al-2.0.43900
Docker image: mcr.microsoft.com/businesscentral/onprem:es

This field have been deleted from Post Code?

Thanks,

**Comment by AlexanderYakunin** [comment]
No, it is not deleted

**Comment by JesperSchulz** [comment]
I can verify, that the "County" field still exists in the lastest release in table 225 - Post Code:
{ 5   ;   ;County              ;Text30         }

Closing issue.
