### ISSUE TITLE
Codeunit 1024 New event publisher "OnBeforeRunJobJnlPostBatch"

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#7600]
Requesting a new publisher event in codeunit 1024 in function Code. New publisher "OnBeforeRunJobJnlPostBatch"

![image](https://user-images.githubusercontent.com/28901234/86235851-9d772900-bb88-11ea-91eb-6b07555d55f8.png)

**LOCAL [IntegrationEvent] OnBeforeRunJobJnlPostBatch(VAR JobJournalLine : Record "Job Journal Line";VAR JobJournalBatch : Record "Job Journal Batch")**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
