### ISSUE TITLE
Codeunit 1013 new event publisher OnAfterApplyJobJnlLineFilter

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#7602]
Requesting a new publisher event in codeunit 1013, function Code. New publisher event "OnAfterApplyJobJnlLineFilter"

![image](https://user-images.githubusercontent.com/28901234/86238463-11b3cb80-bb8d-11ea-970d-3662e6289d52.png)

**LOCAL [IntegrationEvent] OnAfterApplyJobJnlLineFilter(VAR JobJournalLine : Record "Job Journal Line";VAR JobJournalBatch : Record "Job Journal Batch")**

**Comment by StanPesotskiy** [comment]
What is the point to have JobJournalBatch in the event if it is overwritten three lines lower by:
` JobJnlBatch.Get("Journal Template Name", "Journal Batch Name");`?

**Comment by dagnybjork** [comment]
There is actually no point, my mistake. It would be sufficient to have only JobJournalLine as a parameter:

**LOCAL [IntegrationEvent] OnAfterApplyJobJnlLineFilter(VAR JobJournalLine : Record "Job Journal Line")**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
