### ISSUE TITLE
[Event Request] Table 5900 - Function UpdateCust - Add a new event publisher

### ISSUE THREAD

**Issue by KiazY** [microsoft/ALAppExtensions#7603]
Hi Microsoft,

I would like to request an Event Publisher for the Function "UpdateCust" as shown in the picture:

![image](https://user-images.githubusercontent.com/37196811/86237829-660e7980-bb94-11ea-8d52-637d37bbe8ce.png)

The event is to be placed at the beginning of the function (first line) with the parameters:
- Rec -> Service Header (5900) - Record
- ContactNo -> Code[20]
- isHandled -> Boolean

The purpose is to apply a different logic.

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
