### ISSUE TITLE
[Event Request] Table 7326 OnDeleteQtyToHandleOnBeforeModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7604]
Please add a new Event trigger OnDeleteQtyToHandleOnBeforeModify in table 7326. The similar Event does already exist in Table 7317 and 7321:

[External] DeleteQtyToHandle(VAR WhseWkshLine : Record "Whse. Worksheet Line")
WITH WhseWkshLine DO BEGIN
  LOCKTABLE;
  IF FIND('-') THEN
    REPEAT
      VALIDATE("Qty. to Handle",0);
      OnDeleteQtyToHandleOnBeforeModify(VAR WhseWkshLine );
      MODIFY;
    UNTIL NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
