### ISSUE TITLE
[Event Request] Table 36 "Sales Header", function: UpdateShipToContact

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#7607]
Could you please add a publisher in Table 36 "Sales Header", function: UpdateShipToContact

    local procedure UpdateShipToContact()
    begin
        if not (CurrFieldNo in [FieldNo("Sell-to Contact"), FieldNo("Sell-to Contact No.")]) then
            exit;

        if IsCreditDocType then
            exit;

      // Start kvs001.dde
      // New Event
      IsHandled := FALSE;
      OnUpdateShipToContactOnBeforeValidateShipToContact(Rec,xRec,CurrFieldNo,IsHandled);
      IF NOT IsHandled THEN
      // Stop kvs001.dde
        Validate("Ship-to Contact", "Sell-to Contact");
    end;

[IntegrationEvent(false, false)]
 local procedure OnUpdateShipToContactOnBeforeValidateShipToContact(var SalesHeader: Record "Sales Header";xSalesHeader: Record "Sales Header";CurrentFieldNo: Integer;var IsHandled: Boolean);
 begin
 end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
