### ISSUE TITLE
[Enum Request] Table 203 „Res. Ledger Entry“ Field „Source Type“

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7609]
We need to extend the „Source Type“ so please convert the option into an extensible enum.
Maybe you can use the Enum „Res. Journal Line Source Type“ used in Table 207 „Res. Journal Line“ Field „Source Type“

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
