### ISSUE TITLE
[Enum Request] Table 5530 „Inventory Event Buffer“ Field „Type“

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#7611]
We need to extend the „Type“ so please convert the option into an extensible enum.

**Comment by AlexanderYakunin** [comment]
This enum already implemented:

        field(15; Type; Enum "Inventory Event Buffer Type")
        {
            Caption = 'Type';
            DataClassification = SystemMetadata;
            Editable = false;
        }
