### ISSUE TITLE
[EventRequest] VendEntryEdit.Codeunit.al (codeunit 113 "Vend. Entry-Edit")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7626]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **VendEntryEdit.Codeunit.al** Table.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86340762-0a66ed80-bc73-11ea-8945-0d751596a21a.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86340899-371b0500-bc73-11ea-933b-16d5144a7b42.png)

Event Signature
![image](https://user-images.githubusercontent.com/33481576/86340986-5154e300-bc73-11ea-8323-a953710bdaa3.png)
![image](https://user-images.githubusercontent.com/33481576/86341020-5e71d200-bc73-11ea-9feb-2089f48f59fa.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
