### ISSUE TITLE
[EventRequest] ReminderIssue.Codeunit.al (codeunit 393 "Reminder-Issue")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7627]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **ReminderIssue.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86341935-8f9ed200-bc74-11ea-9bb3-4ea134ffd6f1.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86342040-ae9d6400-bc74-11ea-9c60-ac679c75455e.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86342118-cbd23280-bc74-11ea-9f5b-5d1bcebdc82a.png)
![image](https://user-images.githubusercontent.com/33481576/86342167-da204e80-bc74-11ea-93ff-8c9bd658023b.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
