### ISSUE TITLE
[EventRequest] FinChrgMemoMake.Codeunit.al (codeunit 394 "FinChrgMemo-Make")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7628]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **FinChrgMemoMake.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86344595-13a68900-bc78-11ea-8144-7c4e98534555.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86344672-2a4ce000-bc78-11ea-8596-262260e50fb5.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86344715-389afc00-bc78-11ea-995e-abc6cfd4f5df.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
