### ISSUE TITLE
Missing reference in event in report 99001017 "Calculate Plan - Plan. Wksh."

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#7629]
The OnAfterItemOnPreDataItem event in report 99001017 "Calculate Plan - Plan. Wksh." has no reference for the Item variable. It should work the same way as the OnAfterItemOnPreDataItem event in report 699 "Calculate Plan - Req. Wksh.".

This is neccessary because we need to apply additional filters to the Item variable. 

Thank you in advance.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
