### ISSUE TITLE
[Event Enhancement] Codeunit 5988 - OnBeforeFinalize

### ISSUE THREAD

**Issue by esuarkfalo** [Microsoft/ALAppExtensions#763]
In the event "OnBeforeFinalize" called in the procedure "Finalize" we need the additional parameter "CloseCondition".

The changes are as follow

**1. Call of the event in the procedure "Finalize"**

The event will be call in addition with the global variable "CloseCondition".

![event_usage](https://user-images.githubusercontent.com/42433112/50827275-5535cc80-133e-11e9-8bac-7808d822c6a5.PNG)

**2, Change of the Event**

The new parameter is the last parameter "CloseCondition" as shown. This is a "VAR" - parameter.

![event_change](https://user-images.githubusercontent.com/42433112/50827289-5961ea00-133e-11e9-85db-f4a7af200f9e.PNG)

**Comment by AlexanderYakunin** [comment]
Where you are going to use CloseCondition in COD5988?

**Comment by esuarkfalo** [comment]
At this late point while post a service document the variable "CloseCondition" is mainly used for service orders to check whether the service order can be removed or should be updated. At this point it is working like the variable "EverythingInvoiced" in codeunit 80. Our customers want to decide if a service order will be removed or not.


Perhaps this is not the correct way or place. Maybe we need a new boolean variable for that a an other event an little bit later in this function "Finalize" with the same event definition requested above

FinalizeWarrantyLedgerEntries(PassedServHeader,CloseCondition);

// EVENT BEGIN
// IF ((ServHeader."Document Type" = ServHeader."Document Type"::Order) AND CloseCondition) OR

**RemoveHeader := CloseCondition;
OnBeforeFinalize(PassedServHeader,RemoveHeader);**

IF ((ServHeader."Document Type" = ServHeader."Document Type"::Order) AND **RemoveHeader**) OR

// EVENT END

   (ServHeader."Document Type" <> ServHeader."Document Type"::Order)
THEN BEGIN
