### ISSUE TITLE
[Event Request] Table 454 Approval Entry OnBeforeMarkAllWhereUserisApproverOrSender event-request

### ISSUE THREAD

**Issue by kontax85** [microsoft/ALAppExtensions#7631]
Hi,
would it be possible to add an event OnBeforeMarkAllWhereUserisApproverOrSender in Table 454 function MarkAllWhereUserisApproverOrSender:

//New Event Begin
OnBeforeMarkAllWhereUserisApproverOrSender(Rec,IsHandled);
IF IsHandled THEN
 EXIT;
//New Event End
IF UserSetup.GET(USERID) AND UserSetup."Approval Administrator" THEN

Where Rec is a VAR reference to table 454?

Thanks a lot!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
