### ISSUE TITLE
[EventRequest] SalesHeaderApply.Codeunit.al (codeunit 401 "Sales Header Apply")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7634]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **SalesHeaderApply.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86351280-a1d33d00-bc81-11ea-97b1-7b3e2d201595.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86351319-b57ea380-bc81-11ea-9e64-532f672b486c.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86351349-c4fdec80-bc81-11ea-9e9a-d39c2a43af83.png)

Thanks
SUD

**Comment by dtkb** [comment]
With a proper, generalised name, this would also be useful to us in order to set extra filters.

Purchase and any other apply-able ledgers should get equivalent additions in all cases.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
