### ISSUE TITLE
[Visibility Request] Page 11309 General Ledger Entries

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#7636]
Please make the following variables protected:

* `TempGLEntryBuf`
* `ShowTotalAppliedAmount`
* `IncludeEntryFilter`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SjoerddeClippelaar** [comment]
In which version is this going to be shipped? Seems not to be in 16.4. Thanks in advanced.
