### ISSUE TITLE
[Event Request] In T5050 in procedure ProcessNameChange() 

### ISSUE THREAD

**Issue by NSilvergrund** [microsoft/ALAppExtensions#7642]
Hi!

In one of our upgrade Projects from onPrem to BC online, we need an event in Table 5050 Contact, in procedure ProcessNameChange with the handled pattern, to avoid the code updating the Customer. 

Something like this. 

LOCAL ProcessNameChange()
UpdateSearchName;

IF Type = Type::Company THEN
  "Company Name" := Name;

OnBeforeProcessNameChangePerson(Rec, Handled);
if Handled then
  exit;

IF Type = Type::Person THEN BEGIN
...

Regards! 
Niklas

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
