### ISSUE TITLE
Table 5700 Stockkeeping Unit - Reordering Policy - Option to Enum

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#7643]
Hi

Is it possible to have the Reordering Policy field (5440) changed from an Option to an Enum please?

We have functionality which uses a different reordering policy and would like the ability to add to this field.

Thanks

Chris

**Comment by CnCollins** [comment]
Also can the same change be done on the Item table?

**Comment by AlexanderYakunin** [comment]
This is already implemented:

        field(5440; "Reordering Policy"; Enum "Reordering Policy")
        {
            Caption = 'Reordering Policy';

**Comment by CnCollins** [comment]
Thanks, it's not currently in 16.2 but I can see it's in 17.
