### ISSUE TITLE
Codeunit 99000854 Inventory Profile Offsetting - Procedure PlanItem

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#7644]
Hi

Please can you add an event in the PlanItem procedure in the Inventory Profile Offsetting codeunit?  We require an advent after the IsReorderPointPlanning variable is set so that we can set it ourselves.

Example below (the IsReorderPointPlanning variable in the event would be a var):

        if TempSKU.Find('-') then
            repeat
                IsReorderPointPlanning :=
                  (TempSKU."Reorder Point" > TempSKU."Safety Stock Quantity") or
                  (TempSKU."Reordering Policy" = TempSKU."Reordering Policy"::"Maximum Qty.") or
                  (TempSKU."Reordering Policy" = TempSKU."Reordering Policy"::"Fixed Reorder Qty.");

                // New Code Starts
               OnAfterPopulatingIsReorderPointPlanning(IsReorderPointPlanning, TempSKU);
               // New Code Ends

                BucketSize := TempSKU."Time Bucket";

Thanks in advance

Chris

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
