### ISSUE TITLE
Codeunit 99000854 Inventory Profile Offsetting - Procedure CalcReorderQty

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#7646]
Hi

In anticipation of request #7643 (Table 5700 Stockkeeping Unit - Reordering Policy - Option to Enum), please can we have an event added to the case statement in the CalcReorderQty procedure in the Inventory Profile Offsetting codeunit?  This then allows us to facilitate our own reordering policy.

        case TempSKU."Reordering Policy" of
            TempSKU."Reordering Policy"::"Maximum Qty.":
                begin
                  ...
                end;
            TempSKU."Reordering Policy"::"Fixed Reorder Qty.":
                begin
                    ...
                end;
            // Old Code
            else
                QtyToOrder := NeededQty;
            // New Code
              else begin 
                  OnAfterReorderingPolicy(TempSku, PlanningResilicency, ProjectedInventory, SupplyLineNo, Handled);
                  if not handled then 
                    QtyToOrder := NeededQty;
           // End of New Code
        end;

Thanks in advance

Chris

**Comment by StanPesotskiy** [comment]
Please add the detailed signature for the event.
How will you set QtyToOrder if it is not passed by reference to this event?

**Comment by CnCollins** [comment]
Apologies you are correct.  I forgot to add the QtyToOrder as a var parameter to the event:

OnAfterReorderingPolicy(QtyToOrder, TempSku, PlanningResilicency, ProjectedInventory, SupplyLineNo, Handled);

**Comment by StanPesotskiy** [comment]
Are all others are passed by value? Could you please just put the full signature you require?

**Comment by CnCollins** [comment]
Sure, no problem.  See below:

procedure OnAfterCalcReorderQtyReorderingPolicy(var QtyToOrder: Decimal; NeededQty: Decimal; ProjectedInventory: Decimal; SupplyLineNo: Integer; TempSKU: Record "Stockkeeping Unit" temporary; PlanningResilicency: Boolean; var IsHandled: Boolean);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
