### ISSUE TITLE
[Event Change] Codeunit "Gen. Jnl.-Post Line" - Change Event “OnBeforeInsertPmtDiscVATForGLEntry”

### ISSUE THREAD

**Issue by StSdt** [microsoft/ALAppExtensions#7649]
Could you please change the publisher “OnBeforeInsertPmtDiscVATForGLEntry” of Codeunit 12 “Gen. Jnl.-Post Line” and include the sender? This change is needed to create additional G/L Entries for split VAT within the codeunit instance. 

If an event change is out of question, there could be new publishers with Sender included within the trailing case, e.g. “OnAfterInitGLEntryVAT(DtldCVLedgEntryBuf, GenJnlLine, VATEntry2);” immediately after each “InitGLEntryVAT”.

```
// >>>>>>>
//[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
// <<<<<<<
local procedure OnBeforeInsertPmtDiscVATForGLEntry(var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; GenJournalLine: Record "Gen. Journal Line"; VATEntry: Record "VAT Entry")
  begin
  end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
