### ISSUE TITLE
[EventRequest] PurchaseHeaderApply.Codeunit.al (codeunit 402 "Purchase Header Apply")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7654]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **PurchaseHeaderApply.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86385950-b37f0980-bcae-11ea-84ab-167880c751bd.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86386008-c72a7000-bcae-11ea-839d-a44807216f2e.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86386045-dad5d680-bcae-11ea-9751-e01de64c492f.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
