### ISSUE TITLE
[EventRequest] PurchaseHeaderApply.Codeunit.al (codeunit 402 "Purchase Header Apply")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7655]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **PurchaseHeaderApply.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86386199-12448300-bcaf-11ea-98d5-cfc01360b8e9.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86386272-2a1c0700-bcaf-11ea-81e3-ac7155b6b600.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86386331-399b5000-bcaf-11ea-93c4-dc65a6fd9da2.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
