### ISSUE TITLE
[EventRequest] AdjustGenJournalBalance.Codeunit.al (codeunit 407 "Adjust Gen. Journal Balance")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7656]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **AdjustGenJournalBalance.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86388896-27231580-bcb3-11ea-9cff-e216283ed76c.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86388974-4621a780-bcb3-11ea-8729-8c3efd0b62b8.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86389012-55a0f080-bcb3-11ea-9370-4601c3af2656.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
