### ISSUE TITLE
[EventRequest] JobTransferLine.Codeunit.al (codeunit 1004 "Job Transfer Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7657]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **JobTransferLine.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86390847-6e5ed580-bcb6-11ea-8aa6-3fb59f661e21.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86390919-89314a00-bcb6-11ea-81dd-6dc7b4a55c45.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86390968-9ea67400-bcb6-11ea-833b-72c646a89222.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
