### ISSUE TITLE
[EventRequest] JobTransferLine.Codeunit.al (codeunit 1004 "Job Transfer Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7658]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in **JobTransferLine.Codeunit.al** Codeunit.

**Standard Code**
![image](https://user-images.githubusercontent.com/33481576/86391088-d6152080-bcb6-11ea-97b1-7e01e082cadd.png)

**Modified Code**
![image](https://user-images.githubusercontent.com/33481576/86391138-e9c08700-bcb6-11ea-8a63-b9d59e9fc81a.png)

**Event Signature**
![image](https://user-images.githubusercontent.com/33481576/86391165-f9d86680-bcb6-11ea-861d-e0e52944d0ad.png)

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
