### ISSUE TITLE
[EventRequest] Page 490 Acc. Schedule Overview; OnAfterUpdateDimFilterControls

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7659]
Please add a new event to funciton **UpdateDimFIlterControls** to handle extension controls.

`LOCAL [IntegrationEvent] OnAfterUpdateDimFilterControls() ;IncludeSender=Yes and GLobalVarAccess=Yes` 

_LOCAL UpdateDimFilterControls()_
Dim1Filter := GETFILTER("Dimension 1 Filter");
Dim2Filter := GETFILTER("Dimension 2 Filter");
Dim3Filter := GETFILTER("Dimension 3 Filter");
Dim4Filter := GETFILTER("Dimension 4 Filter");
CostCenterFilter := '';
CostObjectFilter := '';
CashFlowFilter := '';
Dim1FilterEnable := AnalysisView."Dimension 1 Code" <> '';
Dim2FilterEnable := AnalysisView."Dimension 2 Code" <> '';
Dim3FilterEnable := AnalysisView."Dimension 3 Code" <> '';
Dim4FilterEnable := AnalysisView."Dimension 4 Code" <> '';
GLBudgetFilter := '';
CostBudgetFilter := '';
**// new
OnAfterUpdateDimFilterControls;
//** 
`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
