### ISSUE TITLE
IsCommentLine on Subpage 46 and others

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#766]
IsCommentLine is a boolean variable not accessible for extensions. It controls wether quantity fields and others are visible/editable.
We Need the same Control Mechanismus for our fields in page extensions for subpage 46 and others.
Can you provide an external  global procedure with the same informations as with IsCommetLine or Change IsCommentline to an external global procedure instead of boolean variable ?

**Comment by frivadulla** [comment]
> 
> 
> IsCommentLine is a boolean variable not accessible for extensions. It controls wether quantity fields and others are visible/editable.
> We Need the same Control Mechanismus for our fields in page extensions for subpage 46 and others.
> Can you provide an external global procedure with the same informations as with IsCommetLine or Change IsCommentline to an external global procedure instead of boolean variable ?

This is really interesting , i really support this feature.

**Comment by DuttaSoumya** [comment]
In PAG 46 and others (47, 6631, 95,  96 etc), IsCommentLine is assigned from the return value of an function TAB37: HasTypeToFillMandatoryFields and this function has now been made External. You may therefore use this function instead.

**Comment by JesperSchulz** [comment]
Closing issue as per @DuttaSoumya's comment. Please create a new issue if you believe, your requirements aren't met by the suggested solution. Thank you!
