### ISSUE TITLE
[EventRequest] Codeunit 8  AccSChedManafement; OnAfterSetCostRowRowFilters

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7660]
Please add a new event to function **SetCostRowRowFilters** to handle additional filters of an extension.

`LOCAL [IntegrationEvent] OnAfterSetCostRowRowFilters(VAR CostType : Record "Cost Type";VAR AccSchedLine2 : Record "Acc. Schedule Line")`

_[External] SetCostTypeRowFilters(VAR CostType : Record "Cost Type";VAR AccSchedLine2 : Record "Acc. Schedule Line";VAR ColumnLayout : Record "Column Layout")_
WITH AccSchedLine2 DO BEGIN
  CASE "Totaling Type" OF
    "Totaling Type"::"Cost Type":
      BEGIN
        CostType.SETFILTER("No.",Totaling);
        CostType.SETRANGE(Type,CostType.Type::"Cost Type");
      END;
    "Totaling Type"::"Cost Type Total":
      BEGIN
        CostType.SETFILTER("No.",Totaling);
        CostType.SETFILTER(Type,'<>%1',CostType.Type::"Cost Type");
      END;
  END;

  CostType.SETFILTER("Cost Center Filter",GETFILTER("Cost Center Filter"));
  CostType.SETFILTER("Cost Object Filter",GETFILTER("Cost Object Filter"));
  IF ColumnLayout."Ledger Entry Type" = ColumnLayout."Ledger Entry Type"::"Budget Entries" THEN
    CostType.SETFILTER("Budget Filter",GETFILTER("Cost Budget Filter"));
END;

**// new
OnAfterSetCostRowRowFilters(CostType,AccSchedLine2);
//**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by StefanMartinEnjoy** [comment]
Please rename the event to OnAfterSetCostTypeRowFilters and extend it by a third parameter **ColumnLayout** like **OnAfterSetCostTypeRowFilters(CostType,AccSchedLine2,ColumnLayout);**
