### ISSUE TITLE
[Event Request] Codeunit 10753 “SII Job Upload Pending Docs."

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#7661]
There are four events in the Codeunit 10753 “SII Job Upload Pending Docs." that we need to change the first parameter of type record as VAR:

Change:

LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForVendorLedgEntry(VendorLedgerEntry : Record "Vendor Ledger Entry";VAR IsHandled : Boolean)
LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForCustLedgEntry(CustLedgerEntry : Record "Cust. Ledger Entry";VAR IsHandled : Boolean)
LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForDtldVendLedgEntry(DetailedVendorLedgEntry : Record "Detailed Vendor Ledg. Entry";VAR IsHandled : Boolean)
LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForDtldCustLedgEntry(DetailedCustLedgEntry : Record "Detailed Cust. Ledg. Entry";VAR IsHandled : Boolean)

As:

LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForVendorLedgEntry(**_VAR_** VendorLedgerEntry : Record "Vendor Ledger Entry";VAR IsHandled : Boolean)
LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForCustLedgEntry(**_VAR_** CustLedgerEntry : Record "Cust. Ledger Entry";VAR IsHandled : Boolean)
LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForDtldVendLedgEntry(**_VAR_** DetailedVendorLedgEntry : Record "Detailed Vendor Ledg. Entry";VAR IsHandled : Boolean)
LOCAL [IntegrationEvent] OnBeforeCreateSIIRequestForDtldCustLedgEntry(**_VAR_** DetailedCustLedgEntry : Record "Detailed Cust. Ledg. Entry";VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
