### ISSUE TITLE
[Function Expose] "Power BI Report FactBox"

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#7663]
The in #68 procedures are where made public but got  prohibit for saas deplyoments in an later release again.

Is there any special reason for that or could you expose this functions again?

Page: "Power BI Report FactBox":
Procedures:

- SetNameFilter
- SetContext
- SetCurrentListSelection

**Comment by AlexanderYakunin** [comment]
SetCurrentListSelection is public, but other two procedures are not intended for public use and used internally.
