### ISSUE TITLE
Remittance Reports are an option on Purchase Report Selections but are hardcoded to use standard reports

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#7666]
Hi

As the title says, in the Purchase Report Selections there are Usage options for Vendor Remittance and Vendor Remittance - Posted Entries however when you print the Remittance report from the journal or the Vendor Ledger Entries it is still hardcoded to us the standard reports.

Can the standard code on the Vendor Ledger Entries Page and the Payment Journal Page be modified to use the report in the Report Selections please?

Thanks

Chris

**Comment by AlexanderYakunin** [comment]
Please clarify what version has this issue? I'm looking into next major release code base and cannot find hardcoding of such reports.

**Comment by CnCollins** [comment]
![image](https://user-images.githubusercontent.com/34585093/87300432-b2977480-c505-11ea-8043-97d9a8a5159e.png)

**Comment by AlexanderYakunin** [comment]
This is fixed for 17.0

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
