### ISSUE TITLE
[Event Request] Table 5740 - Tranfer Header - OnBeforeInitInsert missing

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#7671]
Hi,
in Transfer Header table it will be usefull to add events to customize record initialization, as in Sales or Purchase table.

![image](https://user-images.githubusercontent.com/49486284/86469007-d81fc380-bd38-11ea-804f-dbd6324c2c60.png)

Otherwise I cannot customize no. series assignement.

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
