### ISSUE TITLE
[Event Request] Table 5900 - Customer No. - OnValidate -> Add event before deleting service lines

### ISSUE THREAD

**Issue by KiazY** [microsoft/ALAppExtensions#7672]
Hi Microsoft,

I would like to apply some logic before deleting the Service Lines and Service Item Lines when validating the "Customer No.". For example: Asking the user if he really wants to delete the lines.

To do this I would like to have an Event placed right before deleting those lines:

![image](https://user-images.githubusercontent.com/37196811/86485496-bf230c80-bd50-11ea-8a21-4999c402893e.png)

Table -> 5900
Trigger -> Customer No. - OnValidate()
Event Publisher -> OnBeforeDeleteLines
Rec -> Record - Service Header (T5900)
isHandled ->Boolean

Thank you in advance

**Comment by KiazY** [comment]
I forgot to mention that the two parameters should be "Var".

Thank you once again.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
