### ISSUE TITLE
Can't add Enum to Sales Line Type (base code need refactor)

### ISSUE THREAD

**Issue by dkatson** [microsoft/ALAppExtensions#7674]
Hey team. 
The way how choose-line-type on sales/purchase orders - not compatible with Enums.

Here is a scenario.
1. I add new value to the "Sales Line Type" Enum.
![image](https://user-images.githubusercontent.com/29101017/86507245-ee915200-be00-11ea-8d0a-a6bcb9709133.png)

2. If I just go to Sales Order Line - it's not visible
![image](https://user-images.githubusercontent.com/29101017/86507268-26989500-be01-11ea-8ec1-01c744f57655.png)

It's because there is a middle logic to show only types that are available for the user
![image](https://user-images.githubusercontent.com/29101017/86507420-411f3e00-be02-11ea-83a7-5b6ad815b55f.png)

3. Technically I can subscribe to OnBeforeIncludeOption and add my Enum value there
![image](https://user-images.githubusercontent.com/29101017/86507436-6f9d1900-be02-11ea-93c9-0cf7a20be9b3.png)

4. However there is a problem
as a input parameter you pass Option Index, and not the Id.
I handle this by getting the index of my Enum value

![image](https://user-images.githubusercontent.com/29101017/86507486-c276d080-be02-11ea-8916-8efd2896640e.png)

5. But then what you are doing you try to get the value of my enum by the index and not by Id

![image](https://user-images.githubusercontent.com/29101017/86507507-eb976100-be02-11ea-84d7-e716367ad746.png)

6. That's why as a result user see
![image](https://user-images.githubusercontent.com/29101017/86507517-fe119a80-be02-11ea-8d40-d665df3ae1c4.png)

instead of the my enum value.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
