### ISSUE TITLE
[Key Request] Table 27 Item

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#7677]
We need a new Key in the table item. Our customers create sales lines from the GTIN instead of the item number. So we need to filter the table item for every sales line which is created manually. This takes some moments, if there is no key for the GTIN field. We would really appreciate if the performance for this function keeps high in BC 16.

Can you create a new key for field 1217 "GTIN"?

**Comment by AlexanderYakunin** [comment]
Yes, we can add this key

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
