### ISSUE TITLE
[Event Request] Codeunit 441 (Prepayment Mgt.), Function TestSalesPayment: OnBeforeTestSalesPayment

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#7678]
We suggest the following event to handle additional checks on paid sales prepayments:

![image](https://user-images.githubusercontent.com/47414309/86560570-e64f2900-bf5e-11ea-80fc-5177ea429fd5.png)

The signature of the event looks like this:
![image](https://user-images.githubusercontent.com/47414309/86560663-22828980-bf5f-11ea-9ffd-e8432baaae50.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
