### ISSUE TITLE
[Event Request] Codeunit 441 (Prepayment Mgt.), Function TestPurchasePayment: OnBeforeTestPurchasePayment

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#7679]
We would like to suggest the following event to check the vendor prepayments:

![image](https://user-images.githubusercontent.com/47414309/86561351-b7d24d80-bf60-11ea-944a-d34fe31f8752.png)

The signature of this new event looks like this:
![image](https://user-images.githubusercontent.com/47414309/86561547-2d3e1e00-bf61-11ea-8f80-4299e134acea.png)

Many Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
