### ISSUE TITLE
[Event Request] Codeunit 441 (Prepayment Mgt.), Function TestPurchasePayment: OnBeforeFilterVendLedgerEntry

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#7681]
To apply additional filters to the Vendor Ledger Entries, I suggest the following event:

![image](https://user-images.githubusercontent.com/47414309/86563159-2d8be880-bf64-11ea-9dc7-e305196f6bfa.png)

The signature looks like this:

[IntegrationEvent(false, false)]
local procedure OnBeforeFilterVendLedgerEntry(PurchaseHeader: Record "Purchase Header"; PurchInvHeader: Record "Purch. 
Inv. Header"; var VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
