### ISSUE TITLE
[Event Request] codeunit 5988 "Serv-Documents Mgt." function: FinalizeDeleteLines

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#7692]
Github Issue 5966 is set to Ship-In-Future-Update but is not implemented in the BC16CU03 or BC17 Insider.
When can we expect the event?

https://github.com/microsoft/ALAppExtensions/issues/5966

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
