### ISSUE TITLE
[Event Change] Codeunit "Gen. Jnl.-Post Line" - Change Event “OnAfterPostPmtDiscountVATByUnapply”

### ISSUE THREAD

**Issue by StSdt** [microsoft/ALAppExtensions#7698]
Could you please change the publisher “OnAfterPostPmtDiscountVATByUnapply” of Codeunit 12 “Gen. Jnl.-Post Line” and include the sender? This change is needed to create additional G/L Entries for split VAT within the codeunit instance. 

```
// >>>>>>>
//[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
// <<<<<<<
local procedure OnAfterPostPmtDiscountVATByUnapply(var GenJournalLine: Record "Gen. Journal Line"; var VATEntry: Record "VAT Entry")
  begin
  end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
