### ISSUE TITLE
[Enum Request] Item Substitution - "Substitute Type"

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/ALAppExtensions#7700]
Hi,

it would be awesome if you could consider converting the option field ID: 101; "Substitute Type" in table ID: 5715 "Item Substitution" into an extensible Enumeration.
This would enable us to differentiate multiple types of item substitutions.

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
