### ISSUE TITLE
CU 99000773 "Calculate Prod. Order" - OnBeforeCalculate

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#7701]
In Codeunit 99000773 "Calculate Prod. Order" in Function OnBeforeCalculate, can we add a new parameter var ProdOrderLine: Record "Prod. Order Line".

    procedure Calculate(ProdOrderLine2: Record "Prod. Order Line"; Direction: Option Forward,Backward; CalcRouting: Boolean; CalcComponents: Boolean; DeleteRelations: Boolean; LetDueDateDecrease: Boolean): Boolean
    var
        CapLedgEntry: Record "Capacity Ledger Entry";
        ItemLedgEntry: Record "Item Ledger Entry";
        ProdOrderRoutingLine3: Record "Prod. Order Routing Line";
        ProdOrderRoutingLine4: Record "Prod. Order Routing Line";
        RoutingHeader: Record "Routing Header";
        ProdOrderRoutingLine: Record "Prod. Order Routing Line";
        ErrorOccured: Boolean;
        IsHandled: Boolean;
    begin
        ProdOrderLine := ProdOrderLine2;

        IsHandled := false;
        OnBeforeCalculate(ItemLedgEntry, CapLedgEntry, Direction, CalcRouting, CalcComponents, DeleteRelations, LetDueDateDecrease, IsHandled, **ProdOrderLine**);
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculate(var ItemLedgerEntry: Record "Item Ledger Entry"; var CapacityLedgerEntry: Record "Capacity Ledger Entry"; Direction: Option Forward,Backward; CalcRouting: Boolean; CalcComponents: Boolean; DeleteRelations: Boolean; LetDueDateDecrease: Boolean; var IsHandled: Boolean; **var ProdOrderLine: Record "Prod. Order Line"**)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
