### ISSUE TITLE
Table 36 "Sales Header" OnRename

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#7703]
We need a new Event Function in Table 36 “Sales Header”, named OnBeforeSalesHeaderRename.

We need this:

OnRename()
OnBeforeSalesHeaderRename(Rec,xRec,IsHandled);
IF IsHandled THEN
EXIT;

ERROR(Text003,TABLECAPTION);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
