### ISSUE TITLE
Extensibility enhancement : CreditLimit and Overdue Balance checks

### ISSUE THREAD

**Issue by hhout** [microsoft/ALAppExtensions#7706]
We would like to request additional extensibility to functions SalesHeader.CustomerCreditLimitNotExceeded() and SalesHeader.CustomerCreditLimitExceeded() that are called from every Creditlimit and OverdueBalance Check.

The events in these functions are the perfect place to subscribe to for the Creditlimit and OverdueBalance Check, but they lack the differentiation between Creditlimit and/or Overduebalance, so they fire when one or both checks are exceeded.

On page 343 "Check Credit Limit", procedure ShowWarning(), the checks are separately executed and accordingly notifications are defined. But at the end only exit(true) is returned, although also the NotificationId is returned, passing them through to codeunit 312 "Cust-Check Cr. Limit".

        if ExitValue > 0 then begin
            case ExitValue of
                1:
                    begin
                        Heading := CopyStr(CustCheckCrLimit.GetCreditLimitNotificationMsg, 1, 250);
                        NotificationId := CustCheckCrLimit.GetCreditLimitNotificationId;
                    end;
                2:
                    begin
                        Heading := CopyStr(CustCheckCrLimit.GetOverdueBalanceNotificationMsg, 1, 250);
                        NotificationId := CustCheckCrLimit.GetOverdueBalanceNotificationId;
                    end;
                3:
                    begin
                        Heading := CopyStr(CustCheckCrLimit.GetCreditLimitNotificationMsg, 1, 250);
                        SecondHeading := CopyStr(CustCheckCrLimit.GetOverdueBalanceNotificationMsg, 1, 250);
                        NotificationId := CustCheckCrLimit.GetBothNotificationsId;
                    end;
            end;
            exit(true);
        end;

So we see several possibilities to resolve this:
1.	Return the exitvalue and passing that eventually to these SalesHeader.CustomerCreditLimitNotExceeded() and SalesHeader.CustomerCreditLimitExceeded() functions (or use overloading)
2.	Passing the NotificationId to these SalesHeader.CustomerCreditLimitNotExceeded() and SalesHeader.CustomerCreditLimitExceeded(). The NotificationId can than be compared with functions on codeunit 312 "Cust-Check Cr. Limit".

Placing events in ShowWarning() doesn’t seem the correct way because we want to be able to modify the Sales Header accordingly. The above described standard events on the Sales Header are a better place for this.
Additional complexity is added to this because both functions are not only called from codeunit 312 "Cust-Check Cr. Limit"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
