### ISSUE TITLE
GetPstdDocLinesToRevere Obsolete? 

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/ALAppExtensions#7707]
Hi!

I've just found out something strange.
The problem was: "I have to intercept the creation of the Sales Cr.Memo based on the posted document".
Easy. In the card of the Sales Cr.Memo, there is an action "Get Posted Doc&ument Lines to Reverse", I've only to find out the right event beneath this.
This action calls a function in the Sales Header called: "GetPstdDocLinesToRevere" but this function has the obsolete tag: 
" [Obsolete('Function scope will be changed to OnPrem', '15.1')] " 

**Currently, I'm working with this version: W1 16.2 (Platform 16.0.13440.13772 + Application 16.2.13509.13779).** 

Now my question is: What will replace this function (if any)? But most importantly is it the right thing to do setting this function obsolete? 

![Code](https://user-images.githubusercontent.com/36199751/86754050-dd368880-c040-11ea-8f2b-0f52be420e0c.png)
![Action](https://user-images.githubusercontent.com/36199751/86754056-ddcf1f00-c040-11ea-9c6c-2d322d646c5d.png)

**Comment by AlexanderYakunin** [comment]
Please check in 17.x build, this function replaced by GetPstdDocLinesToReverse, including all occurencies of old GetPstdDocLinesToRevere().

**Comment by stefanoPrimo** [comment]
So for now I cannot use this function?

**Comment by AlexanderYakunin** [comment]
You can use this function in 16.x. Obsoleted does not mean removed.

**Comment by stefanoPrimo** [comment]
Thanks, 
I will fix the code as you suggested!
