### ISSUE TITLE
[Event Change] Page 5914 - Service Order Statistics - OnAfterUpdateHeaderInfo

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#7708]
Hi AL-Team,

can you please set "Include sender"  to Publisher OnAfterUpdateHeaderInfo?

  ```
  // >>>
    [IntegrationEvent(true, false)]
    // [IntegrationEvent(false, false)]
    // <<<
    local procedure OnAfterUpdateHeaderInfo(var TotalServLineLCY: array[7] of Record "Service Line"; var IndexNo: Integer)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
