### ISSUE TITLE
[Event Request] Table 904 OnTransAvailSalesLineToAsmHeaderOnBeforeNewAsmHeaderInitRemainingQty

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7709]
We Need the original AsmHeader as additional Parameter in the new Event OnTransAvailSalesLineToAsmHeaderOnBeforeNewAsmHeaderInitRemainingQty from 16.3:

old:
local procedure OnTransAvailSalesLineToAsmHeaderOnBeforeNewAsmHeaderInitRemainingQty(var NewAsmHeader: Record "Assembly Header"; SalesLine: Record "Sales Line")
New:
local procedure OnTransAvailSalesLineToAsmHeaderOnBeforeNewAsmHeaderInitRemainingQty(var NewAsmHeader: Record "Assembly Header"; SalesLine: Record "Sales Line";AsmHeader: Record "Assembly Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
