### ISSUE TITLE
'Choose Columns' does not show table extension fields in List pages

### ISSUE THREAD

**Issue by VitalyLebedev** [microsoft/ALAppExtensions#771]
If table extension has fields with CaptionClass property, these fields appear in Choose Columns with blank captions. 
The issue is reproducible in Dynamics 365 Business Central W1 13.2 (13.0.26413) and earlier versions. 

Steps to repro:

1. Create simple table extension with a field which uses CaptionClass property: 

```
tableextension 99999 CustomerTestFields extends Customer
{
    fields
    {
        field(50001; "My Field"; Code[10])
        {
            CaptionClass = '1,1,1'; // Global Dim 1 code as example. Custom captions will not work either. 
        }
    }
}
```

2. Create page extension for list page:  

```
pageextension 99999 CustomerListTestFields extends "Customer List"
{
    layout
    {
        addlast(Control1)
        {

            field("My Field"; "My Field")
            {
                ApplicationArea = All;
                Visible = true;
            }
        }
    }
} 
```

After installing the extension, the column is shown correctly on the customer list page but when you try to Choose Columns to rearrange columns, the system shows the field as blank line at the end of the columns list:
![image](https://user-images.githubusercontent.com/46499611/50856891-922cae00-1394-11e9-8667-8625e0024f59.png)

_Note_, for **Card** pages customize page works fine and the field is correctly shown on a fastab and can be rearranged by user.

**Comment by StanPesotskiy** [comment]
It works fine in the RTC client version 14.0.32280. 
![image](https://user-images.githubusercontent.com/41332028/57688910-37a7a500-7647-11e9-8e7a-687881fd5cae.png)
