### ISSUE TITLE
[Event Change] CU 333 "Req. Wksh.-Make Order" / OnBeforeCheckInsertFinalizePurchaseOrderHeader

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7712]
Hello, please add the following parameters to the OnBeforeCheckInsertFinalizePurchaseOrderHeader event in codeunit 333 Req. Wksh.-Make Order:
- PrevPurchCode
- PrevLocationCode

Both values are global variables in the codeunit.

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckInsertFinalizePurchaseOrderHeader(RequisitionLine: Record "Requisition Line"; var PurchaseHeader: Record "Purchase Header"; var CheckInsert: Boolean; var OrderCounter: Integer; PrevPurchCode: Code[10]; PrevLocationCode: Code[10])
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
