### ISSUE TITLE
Copy document codeunit - FromDocType wrong  value + Event request

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#7717]
Hi,
it seems to me that FromDocType option value is not alligned with corresponding document. 
i.e.
if I select "copy from  Posted Credit Memo", when OnBeforeInsertToSalesLine if fired, FromDocType contains 8, but 8 is Posted Return Receipt and not Posted Credit Memo

SalesDocType option string: 
0 Quote,
1 Blanket Order,
2 Order,
3 Invoice,
4 Return Order,
5 Credit Memo,
6 Posted Shipment,
7 Posted Invoice,
8 Posted Return Receipt,
9 Posted Credit Memo,
10 Arch.Quote,
11 Arch.Order,
12 Arch.Blanket Order,
13 Arch.Return Order

Thank you.

Is it possible also FromSalesDocType param also in **OnAfterInsertToSalesLine** event?

AV

**Comment by RomanZanizdra** [comment]
Hi @alessandrovecchio . I suppose if the two options are not aligned there definitely should be a bug something like you copy from one document type but it actually copied from completely another one, isn't it? If so then please create a bug for support team and it will be fixed within the range of hotfix.
What about additional parameter in event, it will be implemented.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
