### ISSUE TITLE
[EventRequest] Page 228 Res. Gr. Allocated per Job - OnShowMatrixOnAfterSetJobFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#7718]
Requesting a new event publisher on Page 228 Res. Gr. Allocated per Job

Event
`OnShowMatrixOnAfterSetJobFilters(VAR JobRec : Record Job)`

**Code**
## ShowMatrix - OnAction()
```
HorizontalRecord.SETRANGE("Resource Group No.",ResourceGrFilter);
HorizontalRecord.SETRANGE(Type,HorizontalRecord.Type::Resource);
JobRec.SETRANGE("Resource Gr. Filter",ResourceGrFilter);
```
**>>> New Code**
```
OnShowMatrixOnAfterSetJobFilters(JobRec);
```
**<<< New Code End**
```
ResGrpPerJobFormWithMatrix.Load(JobRec,HorizontalRecord,MatrixColumnCaptions,MatrixRecords);
ResGrpPerJobFormWithMatrix.RUNMODAL;
```
In Our Solution we use Jobs also to make configurations. These are not real Jobs, so we need the flexibility to filter these Jobs out. Please add the requested Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
