### ISSUE TITLE
[EventRequest] Page 221 Resource allocated per Job - OnShowMatrixOnAfterSetJobFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#7719]
Requesting a new event publisher on Page 221 Resource allocated per Job

Event
`OnShowMatrixOnAfterSetJobFilters(VAR JobRec : Record Job)`

**Code**
## ShowMatrix - OnAction()
```
HorizontalRecord.SETRANGE("No.",ResourceFilter);
HorizontalRecord.SETRANGE(Type,HorizontalRecord.Type::Resource);
JobRec.SETRANGE("Resource Filter",ResourceFilter);
```
**>>> New Code**
```
OnShowMatrixOnAfterSetJobFilters(JobRec);
```
**<<< New Code End**
```
ResAllPerJobFormWithMatrix.Load(JobRec,HorizontalRecord,MatrixColumnCaptions,MatrixRecords,AmountType);
ResAllPerJobFormWithMatrix.RUNMODAL;
```
In Our Solution we use Jobs also to make configurations. These are not real Jobs, so we need the flexibility to filter these Jobs out. Please add the requested Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
