### ISSUE TITLE
OIOUBL-Check Sales Document not working (DK-localization)

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7720]
The OIOUBL tests on sales document is not made before the oioubl file is created.

CreateXML in codeunit 13636 "OIOUBL-Export Sales Invoice" calls "OIOUBL-Check Sales Invoice" before the file is created but "OIOUBL-Check Sales Invoice" skips all tests if customer isn't set to a document sending profile with OIOUBL.

How to reproduce:
Create order/invoice on customer with a Document Sending Profile not set to make OIOUBL. Blank Document Sending Profile will do.
Use Post&Send for posting and change sending options to Disk: Electronic Document, Format: OIOUBL
Document is posted and OIOUBL file is created but none of the tests in codeunit 13632 "OIOUBL-Check Sales Invoice" are done and you can create an invalid OIOUBL file.

Suggestion for fix:
Remove 
```
        if NOT OIOUBLManagement.IsOIOUBLCheckRequired("OIOUBL-GLN", "Sell-to Customer No.") then
            exit;
```
from codeunit 13632 "OIOUBL-Check Sales Invoice". This codeunit is only used in CreateXML.

Same problem for 
Credit Memo (codeunit 13633 "OIOUBL-Check Sales Cr. Memo")
Service Invoice (codeunit 13641 "OIOUBL-Check Service Invoice")
Service Credit Memo (codeunit 13642 "OIOUBL-Check Service Cr. Memo")

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your suggestion seems to be a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by ThomasRonn** [comment]
Can't see how this bug differs from all the issues marked extensibility-bug.
Maybe I should have asked for an event to skip those 2 lines of code??
