### ISSUE TITLE
[eventRequest]codeunit 7307 “WhseActivityRegister.al”, [New publisher]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#7721]
Hello 
In CU 7307 we would like to request a new publisher as seen in below screenshot
![image](https://user-images.githubusercontent.com/54017538/86803629-7633c680-c076-11ea-96a2-782204bef2f1.png)

and also its new trigger / intergration event in the bottom

![image](https://user-images.githubusercontent.com/54017538/86808815-7f736200-c07b-11ea-8e66-72b709388117.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
