### ISSUE TITLE
[eventRequest]codeunit 7322 Create Inventory Pick/Movement, [New publisher]

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#7722]
Hello 
We would like to request to make a local Function global used for integration

![image](https://user-images.githubusercontent.com/54017538/86809126-cf522900-c07b-11ea-9716-a4d875eceb47.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
