### ISSUE TITLE
[Event Request] Page 99000882 OnAfterInit with global variable access or a public function to do so

### ISSUE THREAD

**Issue by r2-4u** [microsoft/ALAppExtensions#7724]
As was described in [AL Issue 3442](https://github.com/Microsoft/AL/issues/3442); 
I am also in need of a way to set the ReqUpdUnitCost to true as a default value.

This is a general problem for Dialog pages, the Global variables used to set the defaults are not available to an extension, and there is no event publisher with global variable access.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
