### ISSUE TITLE
[Event Change] TAB18 Customer / OnBeforeGetTotalAmountLCYCommon

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7725]
I would like to ask you to extend the existing event [OnBeforeGetTotalAmountLCYCommon] in table 18 (Customer) with a Handled Pattern with return value.
Analog to event [OnBeforeGetTotalAmountLCY]

current:
`OnBeforeGetTotalAmountLCYCommon(Rec, AdditionalAmountLCY);`

suggestion:
```
IsHandled := false;
OnBeforeGetTotalAmountLCYCommon(Rec, AdditionalAmountLCY, IsHandled);
if IsHandled then
    exit(AdditionalAmountLCY);
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetTotalAmountLCYCommon(var Customer: Record Customer; var AdditionalAmountLCY: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
