### ISSUE TITLE
Codeunit 5801 Show Applied Entries - InsertTempEntry

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#7727]
two more publisher needed in function InsertTempEntry:

local procedure InsertTempEntry(EntryNo: Integer; AppliedQty: Decimal)
    var
        ItemLedgEntry: Record "Item Ledger Entry";
        IsHandled: Boolean;
    begin
        ItemLedgEntry.Get(EntryNo);

        IsHandled := false;
        OnBeforeInsertTempEntry(ItemLedgEntry, IsHandled);
        if IsHandled then
            exit;

        if AppliedQty * ItemLedgEntry.Quantity < 0 then
            exit;

        if not TempItemEntry.Get(EntryNo) then begin
            TempItemEntry.Init();
            TempItemEntry := ItemLedgEntry;
            TempItemEntry.Quantity := AppliedQty;
            **// ==> NEW
            OnBeforeInsertTempItemEntry(TempItemEntry, ItemLedgEntry, AppliedQty);
            // <== NEW**
            TempItemEntry.Insert();
        end else begin
            TempItemEntry.Quantity := TempItemEntry.Quantity + AppliedQty;
            **// ==> NEW
            OnBeforeModifyTempItemEntry(TempItemEntry, AppliedQty);
            // <== NEW**
            TempItemEntry.Modify();
        end;
    end;

**Comment by StanPesotskiy** [comment]
Hi @ThorstenEngelsGOB
I  would recommend to subscribe to the existing OnBeforeInsertTempEntry() and rewrite these 10 lines of code in the handler as you need. Do you see a problem doing it?

**Comment by ThorstenEngelsGOB** [comment]
No, no problem.

**Comment by StanPesotskiy** [comment]
I have found a small problem. 
OnBeforeInsertTempEntry() misses AppliedQty as a parameter. It will be added.

**Comment by ThorstenEngelsGOB** [comment]
Yeah, I had that out of my head just now. That was also the reason for the publishers' request

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
