### ISSUE TITLE
[Event Request] Codeunit 80 and 90 OnAfterGetLineDataFromOrder

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7728]
Please add a new Event trigger in codeunit 80 and 90 OnAfterGetLineDataFromOrder:

Codeunit 80:
    local procedure GetLineDataFromOrder(var SalesLine: Record "Sales Line")
    var
        SalesShptLine: Record "Sales Shipment Line";
        SalesOrderLine: Record "Sales Line";
    begin
        with SalesLine do begin
            SalesShptLine.Get("Shipment No.", "Shipment Line No.");
            SalesOrderLine.Get("Document Type"::Order, SalesShptLine."Order No.", SalesShptLine."Order Line No.");

            Quantity := SalesOrderLine.Quantity;
            "Qty. Shipped Not Invoiced" := SalesOrderLine."Qty. Shipped Not Invoiced";
            "Quantity Invoiced" := SalesOrderLine."Quantity Invoiced";
            "Prepmt Amt Deducted" := SalesOrderLine."Prepmt Amt Deducted";
            "Prepmt. Amt. Inv." := SalesOrderLine."Prepmt. Amt. Inv.";
            "Line Discount Amount" := SalesOrderLine."Line Discount Amount";
			//+++++++++++++++++++++++++++++++++++++++
			OnAfterGetLineDataFromOrder(var SalesLine: Record "Sales Line";SalesOrderLine: Record "Sales Line")
			//---------------------------------------
        end;
    end;

Codeunit 90:
    local procedure GetLineDataFromOrder(var PurchLine: Record "Purchase Line")
    var
        PurchRcptLine: Record "Purch. Rcpt. Line";
        PurchOrderLine: Record "Purchase Line";
    begin
        with PurchLine do begin
            PurchRcptLine.Get("Receipt No.", "Receipt Line No.");
            PurchOrderLine.Get("Document Type"::Order, PurchRcptLine."Order No.", PurchRcptLine."Order Line No.");

            Quantity := PurchOrderLine.Quantity;
            "Qty. Rcd. Not Invoiced" := PurchOrderLine."Qty. Rcd. Not Invoiced";
            "Quantity Invoiced" := PurchOrderLine."Quantity Invoiced";
            "Prepmt Amt Deducted" := PurchOrderLine."Prepmt Amt Deducted";
            "Prepmt. Amt. Inv." := PurchOrderLine."Prepmt. Amt. Inv.";
            "Line Discount Amount" := PurchOrderLine."Line Discount Amount";
			//+++++++++++++++++++++++++++++++++++++++
			OnAfterGetLineDataFromOrder(var PurchLine: Record "Purchase Line";PurchOrderLine: Record "Purchase Line")
			//---------------------------------------
        end;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
