### ISSUE TITLE
Page 522 View Applied Entries - InsertTempEntry

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#7729]
Publisher needed in function InsertTempEntry:
    local procedure InsertTempEntry(EntryNo: Integer; AppliedQty: Decimal; ShowQuantity: Boolean)
    var
        ItemLedgEntry: Record "Item Ledger Entry";
    begin
        ItemLedgEntry.Get(EntryNo);

        if ShowQuantity then
            if AppliedQty * ItemLedgEntry.Quantity < 0 then
                exit;

        if not TempItemLedgEntry.Get(EntryNo) then begin
            TempItemLedgEntry.Reset();
            TempItemLedgEntry := ItemLedgEntry;
            TempItemLedgEntry.CalcFields("Reserved Quantity");
            TempItemLedgEntry.Quantity := AppliedQty;
        **// ==> NEW
        OnBeforeInsertTempItemLedgEntry(TempItemLedgEntry, ItemLedgEntry, AppliedQty);
        // <== NEW**
            TempItemLedgEntry.Insert();
        end else begin
            TempItemLedgEntry.Quantity := TempItemLedgEntry.Quantity + AppliedQty;
        **// ==> NEW
        OnBeforeModifyTempItemLedgEntry(TempItemLedgEntry, AppliedQty);
        // <== NEW**
            TempItemLedgEntry.Modify();
        end;

        TotalApplied := TotalApplied + AppliedQty;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
