### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line. OnBeforeAddCustVendIC needed in IsCustVendICAdded

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#7730]
Dear BaseApp Team,

In our vertical solution we need a slightly different summation when posting invoices, and for that we need to control when customers are added in CU13 Gen. Journal Post Batch through the function GenJournalLine.IsCustVendICAdded.

For that reason, we would like to request an event with the Handled-pattern in T81 function IsCustVendICAdded

Code:
procedure IsCustVendICAdded(GenJournalLine: Record "Gen. Journal Line"): Boolean
    var 
        IsHandled: Boolean; //New var

    begin
        //>>New code begin
        IsHandled := false;
        OnBeforeAddCustVendIC(IsHandled,GenJournalLine);
        if IsHandled then
          exit;
        //<<New code end
        
        if (GenJournalLine."Account No." <> '') and
           (GenJournalLine."Account Type" in ["Account Type"::Customer, "Account Type"::Vendor, "Account Type"::"IC Partner"])
        then
            exit(AddCustVendIC(GenJournalLine."Account Type", GenJournalLine."Account No."));
...

Event signature:
[IntegrationEvent(false, false)]
local procedure  OnBeforeAddCustVendIC(var IsHandled: Boolean; GenJournalLine : Record "Gen. Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
