### ISSUE TITLE
[Event Request] CU 13643 OIOUBL-Export Service Invoice

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7733]
Requesting a new event in procedure CreateXml to allow editing the xml Document before it’s written to stream.
We would like to fill some optional tags in the document, like embed pdf and add more information on lines.

![image](https://user-images.githubusercontent.com/16342841/86893036-5695b000-c101-11ea-9576-c3d0b439f372.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
