### ISSUE TITLE
Excluding specific Transfer Order Lines from Planning / Requisition Worksheet and Item Availability

### ISSUE THREAD

**Issue by Rub19Luc21** [microsoft/ALAppExtensions#7736]
In one of the latest versions you introduced this beautiful code structure that gives us the opportunity to easily exclude some document lines (sales lines, purchase lines, item ledger entries, requisition lines, etc..) from the Planning / Requisition Worksheet calculations and Item Availability.
It's now very easy to implement this, I really like it.

Every table that is included in these calculations has a FilterLinesWithItemToPlan procedure and in that procedure a publisher exists.
OnAfterFilterLinesWithItemToPlan.

Unfortunately that publisher is missing on the Transfer Line table.
The FilterLinesWithItemToPlan procedures exists, but we need the event publisher to have better control over what is excluded (by placing a filter):
OnAfterFilterLinesWithItemToPlan(var: Transfer Line; var Item: Record Item; IsReceipt: Boolean; IsSupplyForPlanning: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
