### ISSUE TITLE
[Event Request] Codeunit::"Assembly-Post" - Function PostHeader - OnAfterPostItemOutput

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7738]
We like to request the following Event:
Object: Codeunit::"Assembly-Post"
Function: PostHeader
Publisher Event: OnAfterPostItemOutput
Reason: To implement custom business logic

Where is the event placed:
OnBeforePostItemOutput(QtyToOutput, QtyToOutputBase, AssemblyHeader);
ItemLedgEntryNo :=
PostItemOutput(
AssemblyHeader, "Posting No. Series",
QtyToOutput, QtyToOutputBase,
ItemJnlPostLine, WhseJnlRegisterLine, "Posting No.", false, 0);
**OnAfterPostItemOutput(QtyToOutput, QtyToOutputBase, AssemblyHeader);**

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterPostItemOutput(var HeaderQty: Decimal; var HeaderQtyBase: Decimal; var AssemblyHeader: Record "Assembly Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
