### ISSUE TITLE
[Event Request] Codeunit::"Carry Out Action" - Function InsertTransHeader - OnBeforeInsertTransHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7739]
We like to request the following Event:
Object: Codeunit::"Carry Out Action"
Function: InsertTransHeader
Publisher Event: OnBeforeInsertTransHeader
Reason: To implement custom buisness logic

Where is the event placed:
procedure InsertTransHeader(ReqLine: Record "Requisition Line"; var TransHeader: Record "Transfer Header")
    var
        InvtSetup: Record "Inventory Setup";
        IsHandled: Boolean;
    begin
        **OnBeforeInsertTransHeader(ReqLine, TransHeader, IsHandled);**
        **if IsHandled then
            exit;**
        InvtSetup.Get();
        InvtSetup.TestField("Transfer Order Nos.");

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeInsertTransHeader(ReqLine: Record "Requisition Line"; var TransHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
