### ISSUE TITLE
[Function Request] Codeunit 5801 - Show Applied Entries - GetAppliedEntries

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#774]
Dear AL team,

Through this issue I would like to request the following (external) global function to be added in codeunit 5801 - Show Applied Entries to allow reuse of the logic in this function:

```pascal
GetAppliedEntries(ItemLedgEntry : Record "Item Ledger Entry"; VAR TempItemLedgEntry : TEMPORARY Record "Item Ledger Entry")
BEGIN
  TempItemEntry.DELETEALL;
  FindAppliedEntry(ItemLedgEntry);
  
  IF TempItemEntry.FINDSET THEN REPEAT
    IF NOT TempItemLedgEntry.GET(TempItemEntry."Entry No.") THEN BEGIN
      TempItemLedgEntry := TempItemEntry;
      TempItemLedgEntry.INSERT;
    END;
  UNTIL TempItemEntry.NEXT = 0;
END
```

This uses the existing FindAppliedEntry function. This is one possible implementation.

**Comment by JesperSchulz** [comment]
Could you provide a scenario for why you need these changes? It's hard for us to evaluate what you are trying to achieve with no context. Thanks!

**Comment by rvanbekkum** [comment]
Sure. To summarize: We use this function to find the purch. invoices associated with service orders/shipments, which enables users to easily navigate to the associated documents.

**Comment by sboeve** [comment]
We also require this functionality unless the functions within this codeunit are changed to external.  Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
