### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function IsCopyItemTrkg - OnBeforeIsCopyItemTrkg

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7740]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: IsCopyItemTrkg
Publisher Event: OnBeforeIsCopyItemTrkg
Reason: To implement custom business logic

Where is the event placed:
local procedure IsCopyItemTrkg(var ItemLedgEntry: Record "Item Ledger Entry"; var CopyItemTrkg: Boolean; FillExactCostRevLink: Boolean): Boolean
    var
        IsHandled: Boolean;
        Result: Boolean;
    begin
        **OnBeforeIsCopyItemTrkg(ItemLedgEntry, CopyItemTrkg, FillExactCostRevLink, Result, IsHandled);**
        **if IsHandled then
            exit(Result);**
        with ItemLedgEntry do begin
            if IsEmpty then
                exit(true);
            SetFilter("Lot No.", '<>''''');

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeIsCopyItemTrkg(var ItemLedgEntry: Record "Item Ledger Entry"; var CopyItemTrkg: Boolean; var FillExactCostRevLink: Boolean; var Result: Boolean; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
