### ISSUE TITLE
[Event Request] Codeunit::"Create Pick" - Function UseForPick - OnBeforeUseForPick

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7741]
We like to request the following Event:
Object: Codeunit::"Create Pick"
Function: UseForPick
Publisher Event: OnBeforeUseForPick
Reason: To implement custom business logic

Where is the event placed:
local procedure UseForPick(FromBinContent: Record "Bin Content"): Boolean
    var
        IsHandled: Boolean;
        IsForPick: Boolean;
    begin
        **OnBeforeUseForPick(FromBinContent, IsForPick, IsHandled);**
        **if IsHandled then
            exit(IsForPick);**
        with FromBinContent do begin

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUseForPick(var FromBinContent: Record "Bin Content"; var IsForPick: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
