### ISSUE TITLE
[Event Request] Codeunit 13632 OIOUBL-Check Sales Invoice

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7742]
Requesting a new event to extend and skip current tests in codeunit.

Reason: 
We would like to do more tests, like testing the lines before oioubl file is created.
Handled-pattern is needed because we want to be able to use GLN as PartyIdentification (Customer.”Use GLN in Electronic Document”) and thus don’t want to do TESTFIELD(“VAT Registration No.”)

![image](https://user-images.githubusercontent.com/16342841/86898924-99f41c80-c109-11ea-8d51-1df26a554fea.png)

![image](https://user-images.githubusercontent.com/16342841/86898936-9f516700-c109-11ea-8d29-34926b89478f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
