### ISSUE TITLE
[Event Request] Codeunit 13633 OIOUBL-Check Sales Cr. Memo

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7743]
Requesting a new event to extend and skip current tests in codeunit.

Reason: 
We would like to do more tests, like testing the lines before oioubl file is created.
Handled-pattern is needed because we want to be able to use GLN as PartyIdentification (Customer.”Use GLN in Electronic Document”) and thus don’t want to do TESTFIELD(“VAT Registration No.”)

![image](https://user-images.githubusercontent.com/16342841/86899184-f48d7880-c109-11ea-88a4-b9087d28cdd5.png)

![image](https://user-images.githubusercontent.com/16342841/86899192-f8b99600-c109-11ea-87ef-4d012bba3edf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
