### ISSUE TITLE
[Event Request] Codeunit 13641 OIOUBL-Check Service Invoice

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7744]
Requesting a new event to extend and skip current tests in codeunit.

Reason: 
We would like to do more tests, like testing the lines before oioubl file is created.
Handled-pattern is needed because we want to be able to use GLN as PartyIdentification (Customer.”Use GLN in Electronic Document”) and thus don’t want to do TESTFIELD(“VAT Registration No.”)

![image](https://user-images.githubusercontent.com/16342841/86899236-0cfd9300-c10a-11ea-8d66-2ef36873dbc1.png)

![image](https://user-images.githubusercontent.com/16342841/86899252-1129b080-c10a-11ea-856d-61c78499d39e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
