### ISSUE TITLE
[Event Request] Codeunit 13642 OIOUBL-Check Service Cr. Memo

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7745]
Requesting a new event to extend and skip current tests in codeunit.

Reason: 
We would like to do more tests, like testing the lines before oioubl file is created.
Handled-pattern is needed because we want to be able to use GLN as PartyIdentification (Customer.”Use GLN in Electronic Document”) and thus don’t want to do TESTFIELD(“VAT Registration No.”)

![image](https://user-images.githubusercontent.com/16342841/86899337-2c94bb80-c10a-11ea-9d6d-e59126db2bbb.png)

![image](https://user-images.githubusercontent.com/16342841/86899348-30c0d900-c10a-11ea-823a-84851eb89ed7.png)

**Comment by ThomasRonn** [comment]
hmm.. VAT Registration No. isn't tested in this codeunit, so handled-pattern isn't needed (for now)
The missing test on VAT registration No. is another reason why we need to option to do more tests.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
