### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Blanket Order Line No." - OnValidate - OnBeforeValidateBlanketOrderLineNo

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7746]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Blanket Order Line No." - OnValidate
Publisher Event: OnBeforeValidateBlanketOrderLineNo
Reason: To implement custom business logic

Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                **OnBeforeValidateBlanketOrderLineNo(Rec, IsHandled);**
                **if IsHandled then
                    exit;**
                TestField("Quantity Received", 0);

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateBlanketOrderLineNo(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
