### ISSUE TITLE
[Event Request] Codeunit 13646 OIOUBL-Management – Function ExportXMLFile – Set filename

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7747]
We would like to be able to set a unique filename for the oioubl files. For Customer with multiple companies / tenants the <DocNo>.xml generates duplicated filenames.

![image](https://user-images.githubusercontent.com/16342841/86903519-b98e4380-c10f-11ea-93c1-993a84a5677d.png)

![image](https://user-images.githubusercontent.com/16342841/86903533-bdba6100-c10f-11ea-9157-291de914818b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
