### ISSUE TITLE
[Event Request] Codeunit 13629 OIOUBL-Check Sales Header

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7748]
Requesting a new event to extend and skip current tests in codeunit.
Reason:
We would like to do more tests.
Handled-pattern is needed because we want to be able to use GLN as PartyIdentification (Customer.”Use GLN in Electronic Document”) and thus don’t want to do TESTFIELD(“VAT Registration No.”)

![image](https://user-images.githubusercontent.com/16342841/86904546-2bb35800-c111-11ea-88e7-07945ec107e2.png)
![image](https://user-images.githubusercontent.com/16342841/86904559-2eae4880-c111-11ea-8a57-bc41fa893703.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
