### ISSUE TITLE
[Event Request] CU 13638 OIOUBL-Exp. Issued Fin. Chrg

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7749]
Requesting a new event in OnRun trigger to allow editing the xml Document before it’s written to stream.
We would like to fill some optional tags in the document, like embed pdf.

![image](https://user-images.githubusercontent.com/16342841/86906674-2e637c80-c114-11ea-9cba-acdb1f47b044.png)
![image](https://user-images.githubusercontent.com/16342841/86906685-30c5d680-c114-11ea-8b00-9eaec8e6d87d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
