### ISSUE TITLE
[Event Request] CU 13639 OIOUBL-Export Issued Reminder

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#7750]
Requesting a new event in OnRun trigger to allow editing the xml Document before it’s written to stream.
We would like to fill some optional tags in the document, like embed pdf.

![image](https://user-images.githubusercontent.com/16342841/86907156-e8f37f00-c114-11ea-9ad9-89909744dd01.png)
![image](https://user-images.githubusercontent.com/16342841/86907169-ec870600-c114-11ea-9ff2-87dfe1354e2f.png)

**Comment by RomanZanizdra** [comment]
Hi @ThomasRonn , I'm not sure we can provide you event with XmlDocument type as var. This relates to all your similar requests. Please let me know if you can redesign your requests in other way where we can help you.

**Comment by ThomasRonn** [comment]
@RomanZanizdra Why can't it be a var?
I don't care how the xml is exposed. You can put it in a Text variable or a File and load it back in after the event, but that will look silly. so why not a var XmlDocument?

**Comment by ThomasRonn** [comment]
Had a 2nd look and even if XmlDocument isn't var in publisher I can make changes to it in subscriber. Same as for the dotnet variables.
Meaning no need for var unless the that will be changed. 
But setting it to var shows developers that it can be changed. So still think var XmlDoc: XmlDocument is the nicest way of doing it.

**Comment by RomanZanizdra** [comment]
How you can make changes in XmlDocOut in subscriber if it will not passed by var? Actually you can but will not be returned back to function.

**Comment by ThomasRonn** [comment]
I can make changes because AL .net types (XmlDocument, Json, List etc)  is reference types. See https://www.kauffmann.nl/2019/10/11/net-types-in-al-are-reference-types/

But why can't it just be var?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
