### ISSUE TITLE
[Event Request] Table 5965 - Function "UpdateCust" -> Add publisher event "OnBeforeUpdateCust"

### ISSUE THREAD

**Issue by KiazY** [microsoft/ALAppExtensions#7751]
Dear Microsoft,

I would like to request an event at the beginning of the function "UpdateCust" in T5965 - "Service Contract Header":

![image](https://user-images.githubusercontent.com/37196811/86906530-98c3ef00-c10b-11ea-9edb-9595fb77c135.png)

Event Name -> OnBeforeUpdateCust
Rec -> (Var) Record - Service Contract Header (T5965)
ContactNo -> Code[20]
isHandled -> (Var) Boolean

The purpose is to be able to do some logic before updating the customer information.

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
