### ISSUE TITLE
Inventory Adjustment OnAfterMakeMultiLevelAdjmt event parameters.

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#7755]
Is it bug or "by design" that in On**Before**MakeMultiLevelAdjmt and On**After**MakeMultiLevelAdjmt we have different variables in Item parameter?

If it is "by design" Is it possible to add FilterItem parameter to the On**After**MakeMultiLevelAdjmt event?

![image](https://user-images.githubusercontent.com/45788765/86920345-53ff7e80-c132-11ea-8e30-a60a993b8861.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
