### ISSUE TITLE
[Event Request] Add parameter to OnAfterRunCode function in Codeunit 1012

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#7757]
This is how the OnAfterRunCode event is looking at the moment. 
LOCAL [IntegrationEvent] OnAfterRunCode(VAR JobJournalLine : Record "Job Journal Line";JobLedgEntryNo : Integer)

I would like tot add the JobRegister to this. We want to do a posting ourself based on the JobJournalLine, but we are unable to update the JobRegister. 

The new could look something like this.
LOCAL [IntegrationEvent] OnAfterRunCode(VAR JobJournalLine : Record "Job Journal Line";JobLedgEntryNo : Integer;**VAR JobRegister : Record "Job Register"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
