### ISSUE TITLE
Wrong call of ErrorMessageMgt.LogWarning

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/ALAppExtensions#7759]
Hello,
Tested in BC 16.3.
In codeunit 6620 "Copy Document Mgt." there is a line:
ErrorMessageMgt.LogWarning(0, **SourceVariant, Text019**, 0, '');

In codeunit 28 "Error Message Management" the procedures LogWarning has next definitions:
    procedure LogWarning(ContextFieldNo: Integer; **WarningMessage: Text; SourceVariant: Variant**; SourceFieldNo: Integer; HelpArticleCode: Code[30]) IsLogged: Boolean
    procedure LogWarning(WarningMessage: Text) IsLogged: Boolean

So, in 6620 the second and third parameter was swapped.

The error that we receive is:
The expression Microsoft.Dynamics.Nav.Runtime.NavIndirectValue cannot be type-converted to a Microsoft.Dynamics.Nav.Runtime.NavText value.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
