### ISSUE TITLE
[Event Request] CU 5880 Phys. Invt. Order-Finish and CU 5884 Phys. Invt. Order-Post

### ISSUE THREAD

**Issue by thunt79** [microsoft/ALAppExtensions#7760]
Requesting new events in codeunits 5880 Phys. Invt. Order-Finish and 5884 Phys. Invt. Order-Post.

For 5880 Phys. Invt. Order-Finish, I propose the following events in the Code() function: OnBeforeFinishPhysInvtOrder at the beginning of the function, and OnAfterFinishPhysInvtOrder at the end of the function. 

For 5884 Phys. Invt. Order-Post, I propose the following events:
- At the beginning of the Code function: OnBeforePostPhysInvtOrder
- At the end of the Code function: OnAfterPostPhysInvtOrder
- At the beginning of the InsertPostedHeader function: OnBeforeInsertPostedHeader
- At the end of the InsertPostedHeader function: OnAfterInsertPostedHeader
- At the beginning of the InsertPostedLine function: OnBeforeInsertPostedLine
- At the end of the InsertPostedLine function: OnAfterInsertPostedLine
- At the beginning of the InsertPostedRecordings function: OnBeforeInsertPostedRecordings
- At the end of the InsertPostedRecordings function: OnAfterInsertPostedRecordings
- Before inserting an individual posted recording header in the InsertPostedRecordings function, probably before line 350 of the codeunit: OnBeforeInsertPostedRecordingRecord
- After inserting an individual posted recording header in the InsertPostedRecordings function, probably after line 353 of the codeunit: OnBeforeInsertPostedRecordingRecord
- Before inserting an individual posted recording line in the InsertPostedRecordings function, probably before line 360 of the codeunit: OnBeforeInsertPostedRecordingLine
- After inserting an individual posted recording line in the InsertPostedRecordings function, probably after line 363 of the codeunit: OnAfterInsertPostedRecordingLine
- At the beginning of the InsertPostedCommentLine function: OnBeforeInsertPostedCommentLine
- At the end of the InsertPostedCommentLine function: OnAfterInsertPostedCommentLine

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.
