### ISSUE TITLE
[Enum Request] Table "Electronic Document Format" - Field Usage 

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#7781]
Hello there,

Could you please change the Usage field to Enum.
We would like to have possibility to prepare other document types as electronic invoice e.g.: Finance Charge Memo 

Thanks.

BR,
Bojan

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
