### ISSUE TITLE
[BUG] Change Global Dimensions

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/ALAppExtensions#7783]
Hi,
On table 483 "Change Global Dimension Entry" there is a function 
`FindDimensionSetIDField`
That has a very dangerous code:
In my case, I have an app that adds the fields "Global dimension 1 Code", "Global Dimension 2 Code" and the "Dimension Set ID".
In order, the fields had these ids: 480, 481, and 485.
The function Change Global dimension for this table results in this error:
![image](https://user-images.githubusercontent.com/36199751/86940273-e1e36580-c142-11ea-9512-512342a40348.png)

this is due to the standard function "FindDimensionSetIDField" that has this code:
```
    procedure FindDimensionSetIDField(RecRef: RecordRef): Boolean
    var
        "Field": Record "Field";
    begin
        if RecRef.FieldExist(480) then begin // W1 "Dimension Set ID" fields must have ID = 480
            "Dim. Set ID Field No." := 480;
            exit(true);
        end;
        Field.SetRange(TableNo, RecRef.Number);
        Field.SetRange(RelationTableNo, DATABASE::"Dimension Set Entry");
        Field.SetRange(FieldName, 'Dimension Set ID');
        Field.SetFilter(ObsoleteState, '<>%1', Field.ObsoleteState::Removed);
        if Field.FindFirst then begin
            "Dim. Set ID Field No." := Field."No.";
            exit(true);
        end;
    end;
```
This function is insecure for multiple reasons:

1. Is really ID 480 reserved for the field "Dimension Set ID"? if so, why not insert a compiler error if someone declares a field 480 that is different from "Dimension Set ID"?
2. Why adding this first condition if there is a more reliable code beneath it? 
3. Why not searching a field that is also of type Integer? If so, it will not throw an error like the ones in my example

In my opinion, I will rewrite this function in something like that
```
        procedure FindDimensionSetIDField(RecRef: RecordRef): Boolean
    var
        "Field": Record "Field";
    begin
        Field.SetRange(TableNo, RecRef.Number);
        Field.SetRange(RelationTableNo, DATABASE::"Dimension Set Entry");
        Field.SetRange(FieldName, 'Dimension Set ID');
        Field.SetFilter(ObsoleteState, '<>%1', Field.ObsoleteState::Removed);
        Field.SetRange(Type, Field.Type::Integer);
        if Field.FindFirst() then begin
            "Dim. Set ID Field No." := Field."No.";
            exit(true);
        end;
    end;
```

Now, returning to my app, I have tied hands because this app was already submitted to Appsource so I cannot either rename or renumber because it will appear as breaking change. Also, I cannot set this field obsolete because it will not find the right field because I have to obsolete the original ones and copy it, rename it and renumber it. 

How I am supposed to resolve this?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
