### ISSUE TITLE
Better control over Transfer Line "Line No."

### ISSUE THREAD

**Issue by Rub19Luc21** [microsoft/ALAppExtensions#7785]
Good evening,

I would like to ask for a very small code change that will give us more control over the "Line No." on the Transfer Line.
Currently the OnInsert trigger has the following code:

    trigger OnInsert()
    var
        TransLine2: Record "Transfer Line";
    begin
        TestStatusOpen;
        TransLine2.Reset();
        TransLine2.SetFilter("Document No.", TransHeader."No.");
        if TransLine2.FindLast then
            "Line No." := TransLine2."Line No." + 10000;
        ReserveTransferLine.VerifyQuantity(Rec, xRec);
    end;

Could you please change that into:

    trigger OnInsert()
    var
        TransLine2: Record "Transfer Line";
    begin
        TestStatusOpen;
        if "Line No." = 0 then begin //don't reassign line no. if it was already set
            TransLine2.Reset();
            TransLine2.SetFilter("Document No.", TransHeader."No.");
            if TransLine2.FindLast then
                "Line No." := TransLine2."Line No." + 10000;
        end;
        ReserveTransferLine.VerifyQuantity(Rec, xRec);
    end;

Thanks.
Kind Regards,
Ruben Schoester

**Comment by AlexanderYakunin** [comment]
This is duplicate for #7464

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
