### ISSUE TITLE
[Event Request] Codeunit 5763 OnBeforeDeleteUpdateWhseShptLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7787]
We Need an additional Parameter WarehouseShptLineBuf  in the existing Event trigger OnBeforeDeleteUpdateWhseShptLine. Additionial WhseShptLine  Needs to be a VAR parameter. The same Parameter Extension does already exist in Codenit 5760 in the same Eventtrigger OnBeforePostUpdateWhseRcptLine:

Old:
LOCAL [IntegrationEvent] OnBeforeDeleteUpdateWhseShptLine(WhseShptLine : Record "Warehouse Shipment Line";VAR DeleteWhseShptLine : Boolean)
New:
LOCAL [IntegrationEvent] OnBeforeDeleteUpdateWhseShptLine(VAR WhseShptLine : Record "Warehouse Shipment Line";VAR WarehouseShptLineBuf : Record "Warehouse Shipment Line";VAR DeleteWhseShptLine : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
