### ISSUE TITLE
[Event Request] Table 263 "Intrastat Jnl. Line" - OnBeforeTestfieldOnModify()

### ISSUE THREAD

**Issue by PieterJacob** [microsoft/ALAppExtensions#7788]
Dear Microsoft,

For table "Intrastat Jnl. Line", we like to have the ability to apply our own TESTFIELD and skip IntrastatJnlBatch.TESTFIELD(Reported,FALSE) for trigger OnModify().
Therefore we like to see the following publisher added:
```
trigger OnModify()
var
    IsHandled : boolean; //<< New local variable
begin
    IntrastatJnlBatch.Get("Journal Template Name", "Journal Batch Name");
//>> Start publisher
    OnBeforeTestfieldOnModify(Rec,xRec,IntrastatJnlBatch,IsHandled);
    if not IsHandled then
//>> End publisher
        IntrastatJnlBatch.TestField(Reported, false);
end;
```
New Publisher
```
[IntegrationEvent(false,false)]
local procedure OnBeforeTestfieldOnModify(IntrastatJnlLine : record "Intrastat Jnl. Line";xIntrastatJnlLine : record "Intrastat Jnl. Line"; IntrastatJnlBatch: Record "Intrastat Jnl. Batch";var IsHandled : boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
