### ISSUE TITLE
[Extensibility] Protection level for TotalPurchaseLine on Page 55 "Purch. Invoice Subform"

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#7790]
Please set global variable "TotalPurchaseLine" in Page 55 "Purch. Invoice Subform" as protected variable. This variable saves the totals of the purchase document.

I would need this as a protected variable because I have a custom field in the "Purchase Invoice Subform" and currently I cannot know what the totals are for doing the calculation on my custom field.

Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
