### ISSUE TITLE
{Event Request] Table 263 "Intrastat Jnl. Line" - OnBeforeGetItemDescription()

### ISSUE THREAD

**Issue by PieterJacob** [microsoft/ALAppExtensions#7791]
Dear Microsoft,

We like to have the ability to apply our own 'version' of GetItemDescription. Therefore we would appreciate that the following publisher is added:
```
local procedure GetItemDescription()
var
   IsHandled : boolean; //<< New local variable
begin
//<< Start Publisher
    OnBeforeGetItemDescription(Rec,IsHandled);
    if IsHandled then
        exit;
//<< End Publisher
    if "Tariff No." <> '' then begin
        TariffNumber.Get("Tariff No.");
        "Item Description" := TariffNumber.Description;
        "Supplementary Units" := TariffNumber."Supplementary Units";
    end else
        "Item Description" := '';
end;
```
New Publisher
```
[IntegrationEvent(false, false)]
OnBeforeGetItemDescription(var Rec record : "Instratstat Jnl. Line",var IsHandled : boolean)
begin
end;
```

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
