### ISSUE TITLE
Over-Quantity Base Translation

### ISSUE THREAD

**Issue by fmoric** [microsoft/ALAppExtensions#7793]
There is no tag for Over-Quantity trenslation in base app. I'm working with version 16.3.

**Comment by StanPesotskiy** [comment]
What tag, what object, what field are you talking about? Please provide all details.

**Comment by fmoric** [comment]
New feature in v16 recieve more items than ordered (https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave1/dynamics365-business-central/receive-more-items-than-ordered).
Translation for that feature is missing from base app translation. Purchase line is one table that shuld have Over-Receipt Quantity field to translate. I cannot find it in translatio file.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
