### ISSUE TITLE
[Event Request] Codeunit 5403 OnAfterResetReqLineFields

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7796]
We Need a new Event OnAfterResetReqLineFields in codeunit 5403 AddOnIntegrManagement to reset our Extension fields.

    procedure ResetReqLineFields(var ReqLine: Record "Requisition Line")
    begin
        with ReqLine do begin
            "Prod. Order Line No." := 0;
            "Routing No." := '';
            "Routing Reference No." := 0;
            "Operation No." := '';
            "Work Center No." := '';
            //++++++++++++++++++++++++++
            OnAfterResetReqLineFields(var ReqLine: Record "Requisition Line");
            //--------------------------
        end;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
