### ISSUE TITLE
[Event Request] Codeunit 550 OnAfterAddNewSalesLine and OnAfterAddNewPurchaseLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#7797]
In Codeunit 550 "VAT Rate Change Conversion" we Need additional Event trigger:

    local procedure AddNewSalesLine(SalesLine: Record "Sales Line"; VATProdPostingGroup: Code[20]; GenProdPostingGroup: Code[20])
BEGIN
…

        OldSalesLine.Modify();
        //++++++++++++++++++++++
        OnAfterAddNewSalesLine(VAR OldSalesLine,VAR NewSalesLine);
        //----------------------
    end;

    local procedure AddNewPurchaseLine(PurchaseLine: Record "Purchase Line"; VATProdPostingGroup: Code[20]; GenProdPostingGroup: Code[20])
BEGIN
…
        OldPurchaseLine.Modify();
        //++++++++++++++++++++++
        OnAfterAddNewPurchaseLine(VAR OldPurchaseLine,VAR NewPurchaseLine);
        //----------------------
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
