### ISSUE TITLE
[Event Request] Page 46 - Sales Order Subform 

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/ALAppExtensions#78]
Hello we need a new publisher on function RedistributeTotalsOnAfterValidateWithoutLimitByLineCount

```
LOCAL RedistributeTotalsOnAfterValidateWithoutLimitByLineCount()
CurrPage.SAVERECORD;

SalesHeader.GET("Document Type","Document No.");
DocumentTotals.SalesRedistributeInvoiceDiscountAmounts(Rec,VATAmount,TotalSalesLine);

//NEW CODE BEGIN>>
OnAfterRedistributeDiscAmounts(Rec)
//NEW CODE END<<

CurrPage.UPDATE;
```
with new publisher
`
LOCAL [IntegrationEvent] OnAfterRedistributeDiscAmounts(SalesLine : Record "Sales Line")`

**Comment by AlexanderYakunin** [comment]
Please check latest available D365 BC build and update your ask as code structure have been changed here

**Comment by AlexanderYakunin** [comment]
OnAfterSalesRedistributeInvoiceDiscountAmounts event can be implemented in COD57.

**Comment by InnovaACAdmin** [comment]
Hello, Does this new label means that my request on page 46 will be included in future versions?
Thanks,
