### ISSUE TITLE
[EventRequest] C5812 Calculate Standard Cost; OnAfterCalcRtngCostPerUnit; Extend CalcRtngLineCost, CalcRtngCost

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7800]
Please create a new event **OnAfterCalcRtngCostPerUnit**, called in function **CalcRtngLineCost**. Functions **CalcRtngLineCost** and **CalcRtngCost** are extendend by parameter **ParentItem**.

```
LOCAL [IntegrationEvent] OnAfterCalcRtngCostPerUnit(VAR RtngLine : Record "Routing Line";VAR DirUnitCost : Decimal;VAR IndirCostPct : Decimal;VAR OvhdRate : Decimal;VAR UnitCost : Decimal;VAR UnitCostCalculation : 'Time,Unit';VAR MfgItemQtyBase : Decimal;CalculationDate : Date;ParentItemNo : Code[20])
```

```
PROCEDURE CalcRtngLineCost@35(VAR RoutingLine@1000 : Record 99000764;MfgItemQtyBase@1009 : Decimal;VAR SLCap@1012 : Decimal;VAR SLSub@1011 : Decimal;VAR SLCapOvhd@1010 : Decimal;VAR ParentItem@5507400 : Record 27);
```

```
LOCAL PROCEDURE CalcRtngCost@3(RtngHeaderNo@1000 : Code[20];MfgItemQtyBase@1001 : Decimal;VAR SLCap@1002 : Decimal;VAR SLSub@1003 : Decimal;VAR SLCapOvhd@1004 : Decimal;VAR ParentItem@5507400 : Record 27);
```

--------------------------------------

_LOCAL PROCEDURE CalcMfgItem@2(ItemNo@1000 : Code[20];VAR Item@1001 : Record 27;Level@1002 : Integer);_
    VAR
      LotSize@1003 : Decimal;
      MfgItemQtyBase@1004 : Decimal;
      SLMat@1005 : Decimal;
      SLCap@1006 : Decimal;
      SLSub@1007 : Decimal;
      SLCapOvhd@1008 : Decimal;
      SLMfgOvhd@1009 : Decimal;
      RUMat@1010 : Decimal;
      RUCap@1011 : Decimal;
      RUSub@1012 : Decimal;
      RUCapOvhd@1013 : Decimal;
      RUMfgOvhd@1014 : Decimal;
    BEGIN
      IF Level > MaxLevel THEN
        ERROR(Text000,MaxLevel);
      ...
        IF IsMfgItem THEN BEGIN
          IF "Lot Size" <> 0 THEN
            LotSize := "Lot Size";
          MfgItemQtyBase := CostCalcMgt.CalcQtyAdjdForBOMScrap(LotSize,"Scrap %");
          **// changed
          //CalcRtngCost("Routing No.",MfgItemQtyBase,SLCap,SLSub,SLCapOvhd;
          CalcRtngCost("Routing No.",MfgItemQtyBase,SLCap,SLSub,SLCapOvhd,Item);
          //** 
          CalcProdBOMCost(
            Item,"Production BOM No.","Routing No.",
            MfgItemQtyBase,TRUE,Level,SLMat,RUMat,RUCap,RUSub,RUCapOvhd,RUMfgOvhd);

--------------------------------------

_LOCAL PROCEDURE CalcRtngCost@3(RtngHeaderNo@1000 : Code[20];MfgItemQtyBase@1001 : Decimal;VAR SLCap@1002 :_ Decimal;VAR SLSub@1003 : Decimal;VAR SLCapOvhd@1004 : Decimal;VAR ParentItem@5507400 : Record 27);
    VAR
      RtngLine@1007 : Record 99000764;
      RtngHeader@1005 : Record 99000763;
    BEGIN
      IF RtngLine.CertifiedRoutingVersionExists(RtngHeaderNo,CalculationDate) THEN BEGIN
        IF RtngLine."Version Code" = '' THEN BEGIN
          RtngHeader.GET(RtngHeaderNo);
          TestRtngVersionIsCertified(RtngLine."Version Code",RtngHeader);
        END;
        REPEAT
	  **// changed
	  //CalcRtngLineCost(RtngLine,MfgItemQtyBase,SLCap,SLSub,SLCapOvhd);
          CalcRtngLineCost(RtngLine,MfgItemQtyBase,SLCap,SLSub,SLCapOvhd,ParentItem);
	  //**
        UNTIL RtngLine.NEXT = 0;
      END;
    END;

--------------------------------------

_PROCEDURE CalcRtngLineCost@35(VAR RoutingLine@1000 : Record 99000764;MfgItemQtyBase@1009 : Decimal;VAR SLCap@1012 : Decimal;VAR SLSub@1011 : Decimal;VAR SLCapOvhd@1010 : Decimal;VAR ParentItem@5507400 : Record 27);_
    VAR
      WorkCenter@1002 : Record 99000754;
      CostCalculationMgt@1013 : Codeunit 5836;
      UnitCost@1008 : Decimal;
      DirUnitCost@1007 : Decimal;
      IndirCostPct@1006 : Decimal;
      OvhdRate@1005 : Decimal;
      CostTime@1004 : Decimal;
      UnitCostCalculation@1003 : Option;
    BEGIN
      **// change parameter Routingline to VAR** 
      WITH RoutingLine DO BEGIN
        IF (Type = Type::"Work Center") AND ("No." <> '') THEN
          WorkCenter.GET("No.");
        UnitCost := "Unit Cost per";
        CalcRtngCostPerUnit(Type,"No.",DirUnitCost,IndirCostPct,OvhdRate,UnitCost,UnitCostCalculation);
        **// new
        OnAfterCalcRtngCostPerUnit(RoutingLine,DirUnitCost,IndirCostPct,OvhdRate,UnitCost,UnitCostCalculation,
          MfgItemQtyBase,CalculationDate,ParentItem."No.");
        //** 
        CostTime :=
          CostCalculationMgt.CalcCostTime(
            MfgItemQtyBase,
            "Setup Time","Setup Time Unit of Meas. Code",
            "Run Time","Run Time Unit of Meas. Code","Lot Size",
            "Scrap Factor % (Accumulated)","Fixed Scrap Qty. (Accum.)",
            "Work Center No.",UnitCostCalculation,MfgSetup."Cost Incl. Setup",
            "Concurrent Capacities");
        IF (Type = Type::"Work Center") AND (WorkCenter."Subcontractor No." <> '') THEN
          IncrCost(SLSub,DirUnitCost,CostTime)
        ELSE
          IncrCost(SLCap,DirUnitCost,CostTime);
        IncrCost(SLCapOvhd,CostCalcMgt.CalcOvhdCost(DirUnitCost,IndirCostPct,OvhdRate,1),CostTime);
      END;
      OnAfterCalcRtngLineCost(RoutingLine,MfgItemQtyBase,SLCap,SLSub,SLCapOvhd);
    END;

**Comment by StanPesotskiy** [comment]
Method CalcRtngLineCost() is public. We cannot add new parameters (ParentItem), but can start passing the old parameter by reference (adding var for RoutingLine). Does it all make sense if ParentItem is not added?

**Comment by StefanMartinEnjoy** [comment]
What do you mean with "...start passing old parameter...". Which "old parameter"?
Do you mean I add "ParentItem" as a extended field to "RoutingLine" if this parameter is VAR?

**Comment by StanPesotskiy** [comment]
I mean I can add 'var' to the existing parameter in the public method, but I cannot add a new parameter.

**Comment by StefanMartinEnjoy** [comment]
OK. But in that case I ned a new event "OnBeforeCalcRtngLineCost".

LOCAL PROCEDURE CalcRtngCost@3(RtngHeaderNo@1000 : Code[20];MfgItemQtyBase@1001 : Decimal;VAR SLCap@1002 : Decimal;VAR SLSub@1003 : Decimal;VAR SLCapOvhd@1004 : Decimal;VAR ParentItem@5507400 : Record 27);
VAR
RtngLine@1007 : Record 99000764;
RtngHeader@1005 : Record 99000763;
BEGIN
IF RtngLine.CertifiedRoutingVersionExists(RtngHeaderNo,CalculationDate) THEN BEGIN
IF RtngLine."Version Code" = '' THEN BEGIN
RtngHeader.GET(RtngHeaderNo);
TestRtngVersionIsCertified(RtngLine."Version Code",RtngHeader);
END;
REPEAT
  **// changed
  OnBeforeCalcRtngLineCost(RtngLine,ParentItem);
  //**
  CalcRtngLineCost(RtngLine,MfgItemQtyBase,SLCap,SLSub,SLCapOvhd);
UNTIL RtngLine.NEXT = 0;
END;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
