### ISSUE TITLE
[EventRequest] C99000773 Calculate Prod. Order; OnAfterCalcRtngCostPerUnit

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7803]
Please add a new event **OnAfterCalcRtngCostPerUnit**.

```
LOCAL [IntegrationEvent] OnAfterCalcRtngCostPerUnit(VAR RtngLine : Record "Routing Line";VAR DirUnitCost : Decimal;VAR IndirCostPct : Decimal;VAR OvhdRate : Decimal;VAR UnitCost : Decimal;VAR UnitCostCalculation : 'Time,Unit';VAR MfgItemQtyBase : Decimal;CalculationDate : Date;ParentItemNo : Code[20])
````

_LOCAL TransferRouting()_
IsHandled := FALSE;
...
CostCalcMgt.RoutingCostPerUnit(
      ProdOrderRoutingLine.Type,
      ProdOrderRoutingLine."No.",
      ProdOrderRoutingLine."Direct Unit Cost",
      ProdOrderRoutingLine."Indirect Cost %",
      ProdOrderRoutingLine."Overhead Rate",
      ProdOrderRoutingLine."Unit Cost per",
      ProdOrderRoutingLine."Unit Cost Calculation");
    **// new
    OnAfterCalcRtngCostPerUnit(RoutingLine,ProdOrderRoutingLine."Direct Unit Cost",ProdOrderRoutingLine."Indirect Cost %",ProdOrderRoutingLine."Overhead Rate",ProdOrderRoutingLine."Unit Cost per",ProdOrderRoutingLine."Unit Cost Calculation",
      ProdOrderLine."Quantity (Base)",ProdOrderLine."Due Date",ProdOrderLine."Item No.");
    //** 
    ProdOrderRoutingLine.VALIDATE("Direct Unit Cost");
    ProdOrderRoutingLine."Starting Time" := ProdOrderLine."Starting Time";
    ProdOrderRoutingLine."Starting Date" := ProdOrderLine."Starting Date";
    ProdOrderRoutingLine."Ending Time" := ProdOrderLine."Ending Time";
    ProdOrderRoutingLine."Ending Date" := ProdOrderLine."Ending Date";
    ProdOrderRoutingLine.UpdateDatetime;

**Comment by StanPesotskiy** [comment]
Duplicate. There is already the event  
`OnTransferRoutingOnbeforeValidateDirectUnitCost(ProdOrderRoutingLine, ProdOrderLine, RoutingLine); `
added for request https://github.com/microsoft/ALAppExtensions/issues/5529

**Comment by StefanMartinEnjoy** [comment]
That is not the same. I need to call base method **CostCalcMgt.RoutingCostPerUnit** before and first, than to soemthing with that prices.

Otherwise If i do ot OnBefore. the base method **CostCalcMgt.RoutingCostPerUnit** overrides the values.
