### ISSUE TITLE
[EventRequest] C99000809 Planning Line Management; OnAfterCalcRtngCostPerUnit

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7804]
Please add a new event **OnAfterCalcRtngCostPerUnit**.

```
LOCAL [IntegrationEvent] OnAfterCalcRtngCostPerUnit(VAR RtngLine : Record "Routing Line";VAR DirUnitCost : Decimal;VAR IndirCostPct : Decimal;VAR OvhdRate : Decimal;VAR UnitCost : Decimal;VAR UnitCostCalculation : 'Time,Unit';VAR MfgItemQtyBase : Decimal;CalculationDate : Date;ParentItemNo : Code[20])
```

_LOCAL TransferRouting()_
IF ReqLine."Routing No." = '' THEN
  EXIT;
...
CostCalcMgt.RoutingCostPerUnit(
      PlanningRtngLine.Type,
      PlanningRtngLine."No.",
      PlanningRtngLine."Direct Unit Cost",
      PlanningRtngLine."Indirect Cost %",
      PlanningRtngLine."Overhead Rate",
      PlanningRtngLine."Unit Cost per",
      PlanningRtngLine."Unit Cost Calculation");
    **// new
    OnAfterCalcRtngCostPerUnit(RtngLine,PlanningRtngLine."Direct Unit Cost",PlanningRtngLine."Indirect Cost %",PlanningRtngLine."Overhead Rate",PlanningRtngLine."Unit Cost per",PlanningRtngLine."Unit Cost Calculation",
      ReqLine."Quantity (Base)",ReqLine."Due Date"),ReqLine."No.";
    //** 
    PlanningRtngLine.VALIDATE("Direct Unit Cost");
    PlanningRtngLine."Sequence No.(Forward)" := RtngLine."Sequence No. (Forward)";
    PlanningRtngLine."Sequence No.(Backward)" := RtngLine."Sequence No. (Backward)";
    PlanningRtngLine."Fixed Scrap Qty. (Accum.)" := RtngLine."Fixed Scrap Qty. (Accum.)";

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
