### ISSUE TITLE
[ExentEvent] C5870 Calculate BOM Tree; OnCalcRoutingLineCostsOnBeforeBOMBufferAdd by BOMBuffer

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#7807]
Please extend Event **OnCalcRoutingLineCostsOnBeforeBOMBufferAdd** by BOMBuffer.

```
LOCAL [IntegrationEvent] OnCalcRoutingLineCostsOnBeforeBOMBufferAdd(RoutingLine : Record "Routing Line";LotSize : Decimal;ScrapPct : Decimal;VAR CapCost : Decimal;VAR SubcontracedCapCost : Decimal;VAR CapOverhead : Decimal;VAR BOMBUffer : Record "BOM Buffer")
```

_LOCAL CalcRoutingLineCosts(RoutingLine : Record "Routing Line";LotSize : Decimal;ScrapPct : Decimal;VAR BOMBuffer : Record_ "BOM Buffer";ParentItem : Record Item)
OnBeforeCalcRoutingLineCosts(RoutingLine,LotSize,ScrapPct);
CalcStdCost.SetProperties(WORKDATE,FALSE,FALSE,FALSE,'',FALSE);
// changed #7800
//CalcStdCost.CalcRtngLineCost(
//  RoutingLine,CostCalculationMgt.CalcQtyAdjdForBOMScrap(LotSize,ScrapPct),CapCost,SubcontractedCapCost,CapOverhead);
CalcStdCost.CalcRtngLineCost(
  RoutingLine,CostCalculationMgt.CalcQtyAdjdForBOMScrap(LotSize,ScrapPct),CapCost,SubcontractedCapCost,CapOverhead,ParentItem);
// 
OnCalcRoutingLineCostsOnBeforeBOMBufferAdd(RoutingLine, LotSize, ScrapPct, CapCost, SubcontractedCapCost, CapOverhead,**BOMBuffer**);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by StefanMartinEnjoy** [comment]
Is there any date, when it will be shipped?
