### ISSUE TITLE
[Event Request] Codeunit "Job Post-Line" - New Event “OnAfterPostPurchaseGLAccounts”

### ISSUE THREAD

**Issue by StSdt** [microsoft/ALAppExtensions#7808]
Could we please have a new publisher “OnAfterPostPurchaseGLAccounts” for function “PostPurchaseGLAccounts” of Codeunit 1001 “Job Post-Line”? This publisher should enable access to the same instance of JobJnlPostLine for additional postings.

```

procedure PostPurchaseGLAccounts(TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; GLEntryNo: Integer)
:

            DeleteAll();
        end;
    end;
    // >>>>>>>
    OnAfterPostPurchaseGLAccounts(TempInvoicePostBuffer, JobJnlPostLine, GLEntryNo);
    // <<<<<<<
end;

// >>>>>>>>                    
[IntegrationEvent(true, false)]
local procedure OnAfterPostPurchaseGLAccounts(TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; var JobJnlPostLine: Codeunit "Job Jnl.-Post Line"; GLEntryNo: Integer)
begin
end;
// <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
