### ISSUE TITLE
UpdateAllLineDim HideValidationDialog doesnt work on TransferHeader, ServiceHeader and Service Item Line

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#7809]
Hi, you introduce in table 36 UpdateAllLineDim with GetHideValidationDialog and its working perfect for us. So the point is that we want to have a setup and on that setup we wont to auto update dimension without confirm dialog. For sales and purchase it works because you set Confirm after GetHideValidationDialog:
![image](https://user-images.githubusercontent.com/53824412/87127478-45c67500-c28e-11ea-9c6e-0ef7c0e486b1.png)

but problem is on TransferHeader, ServiceHeader and Service Item Line you have:
![image](https://user-images.githubusercontent.com/53824412/87127564-6262ad00-c28e-11ea-9a95-e5c9c008785b.png)

coulkd you refacture the same to work as it is working in purchase and sales???

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
