### ISSUE TITLE
[Event Request] Codeunit 5632 FA Jnl.-Post Line- New Event "OnBeforePostDisposalEntry"

### ISSUE THREAD

**Issue by ComsolLS** [microsoft/ALAppExtensions#7810]
Could we please have a new publisher in the Codeunit 5632 "5632 FA Jnl.-Post Line" in the procedure PostFixedAsset() with the option "IsHandled".  We need the publisher to realize the financial asset accounting.

local procedure PostFixedAsset()
..
       if FAPostingType = FAPostingType::Disposal then
//>>>>
       begin
          IsHandled := false;
         OnBeforePostDisposalEntry(FALedgEntry, DeprBook, FANo, ErrorEntryNo, IsHandled);
         if IsHandled then
             exit;
// <<<<<<<< 
        PostDisposalEntry(FALedgEntry);
      end;

// >>>>>>>>                    
[IntegrationEvent(true, false)]
local procedure OnBeforePostDisposalEntry(var FALedgEntry: Record "FA Ledger Entry"; DeprBook: Record "Depreciation Book"; FANo: code[20]; ErrorEntryNo: Integer; var IsHandled: Boolean)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
