### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" UpdatePostingNos; new event OnBeforeUpdatePostingNo

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7813]
Dear Microsoft,

We need to have new event: OnBeforeUpdatePostingNo on Purch-Post Codeunit in function:UpdatePostingNos 
Therefore we would appreciate your operation.
Thanks

local procedure UpdatePostingNos(var PurchHeader: Record "Purchase Header"; ReverseChargeVAT: Boolean) ModifyHeader: Boolean
    var
        NoSeriesMgt: Codeunit NoSeriesManagement;
        //> NEW CODE
        IsHandled: Boolean;
       //< NEW CODE
    begin
        with PurchHeader do begin
            if Receive and ("Receiving No." = '') then
                if ("Document Type" = "Document Type"::Order) or
                   (("Document Type" = "Document Type"::Invoice) and PurchSetup."Receipt on Invoice")
                then
                    if not PreviewMode then begin
                        TestField("Receiving No. Series");
                        "Receiving No." := NoSeriesMgt.GetNextNo("Receiving No. Series", "Posting Date", true);
                        ModifyHeader := true;
                    end else
                        "Receiving No." := PostingPreviewNoTok;

            if Ship and ("Return Shipment No." = '') then
                if ("Document Type" = "Document Type"::"Return Order") or
                   (("Document Type" = "Document Type"::"Credit Memo") and PurchSetup."Return Shipment on Credit Memo")
                then
                    if not PreviewMode then begin
                        TestField("Return Shipment No. Series");
                        "Return Shipment No." := NoSeriesMgt.GetNextNo("Return Shipment No. Series", "Posting Date", true);
                        ModifyHeader := true;
                    end else
                        "Return Shipment No." := PostingPreviewNoTok;

            //> NEW CODE
            IsHandled := false;
            OnBeforeUpdatePostingNo(PurchHeader, PreviewMode, ModifyHeader, IsHandled);
            if not IsHandled then 
             //< NEW CODE

                if Invoice and ("Posting No." = '') then begin
                    if ("No. Series" <> '') or
                       ("Document Type" in ["Document Type"::Order, "Document Type"::"Return Order"])
                    then
                        TestField("Posting No. Series");
                    NoSeriesMgt.TestDateOrder("Posting No. Series");
                    if ("No. Series" <> "Posting No. Series") or
                       ("Document Type" in ["Document Type"::Order, "Document Type"::"Return Order"])
                    then begin
                        if PurchSetup."Ext. Doc. No. Mandatory" or (GenJnlLineExtDocNo <> '') then begin
                            VendLedgEntry.Reset;
                            VendLedgEntry.SetCurrentKey("External Document No.");
                            if ("Document Type" = "Document Type"::Invoice) or ("Document Type" = "Document Type"::Order) then begin
                                TestField("Vendor Invoice No.");
                                VendLedgEntry.SetRange("Document Type", "Document Type"::Invoice);
                                VendLedgEntry.SetRange("External Document No.", "Vendor Invoice No.");
                            end else
                                if ("Document Type" = "Document Type"::"Credit Memo") or ("Document Type" = "Document Type"::"Return Order") then begin
                                    TestField("Vendor Cr. Memo No.");
                                    VendLedgEntry.SetRange("Document Type", "Document Type"::"Credit Memo");
                                    VendLedgEntry.SetRange("External Document No.", "Vendor Cr. Memo No.");
                                end;
                            VendLedgEntry.SetRange("Vendor No.", "Pay-to Vendor No.");
                            if VendLedgEntry.FindFirst then
                                Error(PurchaseAlreadyExistsErr, VendLedgEntry."Document Type", GenJnlLineExtDocNo);
                        end;
                        if not PreviewMode then begin
                            "Posting No." := NoSeriesMgt.GetNextNo("Posting No. Series", "Posting Date", true);
                            ModifyHeader := true;
                        end else
                            "Posting No." := PostingPreviewNoTok;
                    end;
                end;

            if Invoice and ReverseChargeVAT and ("Reverse Sales VAT No." = '') then
                if "Reverse Sales VAT No. Series" <> '' then
                    if not PreviewMode then begin
                        NoSeriesMgt.TestDateOrder("Reverse Sales VAT No. Series");
                        "Reverse Sales VAT No." :=
                          NoSeriesMgt.GetNextNo("Reverse Sales VAT No. Series", "Posting Date", true);
                        ModifyHeader := true;
                    end else
                        "Reverse Sales VAT No." := '***';
        end;

        OnAfterUpdatePostingNos(PurchHeader, NoSeriesMgt, SuppressCommit);
    end;

NEW PUBLISHER:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePostingNo(PurchHeader: Record "Purchase Header"; PreviewMode: Boolean; var ModifyHeader: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
