### ISSUE TITLE
Please add new events on Codeunit 12 

### ISSUE THREAD

**Issue by MCIngest** [microsoft/ALAppExtensions#7815]
Please we can add event to function HandleBill on codeunit 12 :

HandleBill(VAR CustLedgEntry : Record "Cust. Ledger Entry";IsUnApply : Boolean)

var
      IsHandled@1101340000 : Boolean;

IsHandled := FALSE;
OnHandleBillBeforeApplyEntries(CustLedgEntry, IsUnApply, IsHandled);
IF IsHandled THEN
  EXIT;

OldCustLedgEntry2.RESET;
OldCustLedgEntry2.SETCURRENTKEY("Document Type","Document No.","Document Occurrence","Customer No.",Open);
OldCustLedgEntry2.SETRANGE("Document Type",CustLedgEntry."Document Type to Close");
OldCustLedgEntry2.SETRANGE("Document No.",CustLedgEntry."Document No. to Close");
OldCustLedgEntry2.SETRANGE("Document Occurrence",CustLedgEntry."Document Occurrence to Close");
OldCustLedgEntry2.SETRANGE("Customer No.",CustLedgEntry."Customer No.");
OldCustLedgEntry2.SETRANGE(Open,TRUE);
IF OldCustLedgEntry2.FINDFIRST THEN BEGIN
  IF IsUnApply THEN BEGIN
    IF CustLedgEntry."Bank Receipt Issued" THEN BEGIN
    
      OnHandleBillBeforeUnApplyUpdateBankRcpt(OldCustLedgEntry2, CustLedgEntry);
      
      UpdateCustLedgEntryBankRcpt(OldCustLedgEntry2,CustLedgEntry);
      
      OnHandleBillAfterUnApplyUpdateBankRcpt(OldCustLedgEntry2, CustLedgEntry);

      OldCustLedgEntry2."Allow Issue" := TRUE;
      OldCustLedgEntry2.MODIFY;
      ClearCustLedgEntryBankRcpt(CustLedgEntry);
      CustLedgEntry.MODIFY;
      UpdDtldCustLedgEntryBankRcpt(OldCustLedgEntry2."Entry No.",TRUE);
    END;
  END ELSE BEGIN
    OnHandleBillBeforeApplyUpdateBankRcpt(CustLedgEntry, OldCustLedgEntry2);
  
    UpdateCustLedgEntryBankRcpt(CustLedgEntry,OldCustLedgEntry2);
    
    OnHandleBillAfterApplyUpdateBankRcpt(CustLedgEntry, OldCustLedgEntry2);
    
    CustLedgEntry.MODIFY;
    ClearCustLedgEntryBankRcpt(OldCustLedgEntry2);
    OldCustLedgEntry2."Allow Issue" := FALSE;
    OldCustLedgEntry2.MODIFY;
    UpdDtldCustLedgEntryBankRcpt(OldCustLedgEntry2."Entry No.",FALSE);
  END;
END;

OnHandleBillAfterApplyEntries(CustLedgEntry, IsUnApply);

----------------------------------- 

    [Integration]
    LOCAL PROCEDURE OnHandleBillBeforeApplyEntries@1101340006(VAR CustLedgEntry@1101340000 : Record 21;IsUnApply@1101340001 : Boolean;VAR IsHandled@1101340002 : Boolean);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnHandleBillAfterApplyEntries@1101340024(VAR CustLedgEntry@1101340002 : Record 21;IsUnApply@1101340001 : Boolean);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnHandleBillBeforeUnApplyUpdateBankRcpt@1101340019(VAR OldCustLedgEntry2@1101340000 : Record 21;VAR CustLedgEntry@1101340001 : Record 21);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnHandleBillAfterUnApplyUpdateBankRcpt@1101340020(VAR OldCustLedgEntry2@1101340000 : Record 21;VAR CustLedgEntry@1101340001 : Record 21);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnHandleBillBeforeApplyUpdateBankRcpt@1101340021(VAR CustLedgEntry@1101340000 : Record 21;VAR OldCustLedgEntry2@1101340001 : Record 21);
    BEGIN
    END;

    [Integration]
    LOCAL PROCEDURE OnHandleBillAfterApplyUpdateBankRcpt@1101340022(VAR CustLedgEntry@1101340001 : Record 21;VAR OldCustLedgEntry2@1101340000 : Record 21);
    BEGIN
    END;

Best Regards
Marianna

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
