### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" CheckAndUpdate; new event OnBeforePostedPaymentsInsert

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7817]
Dear Microsoft,

We need to have new event: OnBeforePostedPaymentsInsert on Purch-Post Codeunit in function: CheckAndUpdate
Therefore we would appreciate your operation.
Thanks

local procedure CheckAndUpdate(var PurchHeader: Record "Purchase Header")
    var
        VATExemption: Record "VAT Exemption";
        GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
        CheckDimensions: Codeunit "Check Dimensions";
        ErrorContextElement: Codeunit "Error Context Element";
        ForwardLinkMgt: Codeunit "Forward Link Mgt.";
        SetupRecID: RecordID;
        ModifyHeader: Boolean;
        RefreshTempLinesNeeded: Boolean;
        ReverseChargeVAT: Boolean;
        Check: Boolean;
        IsHandled: Boolean;
    begin
        with PurchHeader do begin
            // Check
            ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, CheckPurchHeaderMsg);
            CheckMandatoryHeaderFields(PurchHeader);
            if GenJnlCheckLine.IsDateNotAllowed("Posting Date", SetupRecID) then
                ErrorMessageMgt.LogContextFieldError(
                  FieldNo("Posting Date"), StrSubstNo(PostingDateNotAllowedErr, FieldCaption("Posting Date")),
                  SetupRecID, ErrorMessageMgt.GetFieldNo(SetupRecID.TableNo, GLSetup.FieldName("Allow Posting From")),
                  ForwardLinkMgt.GetHelpCodeForAllowedPostingDate);

            TestField("Operation Occurred Date");
            TestField("Operation Type");
            if not FindVATExemption(VATExemption, Check, true) then
                if Check then
                    Error(Text12100);

            if "Applies-to Doc. No." <> '' then
                if "Applies-to Occurrence No." = 0 then
                    Error(Text1130007, FieldCaption("Applies-to Occurrence No."));

            SetPostingFlags(PurchHeader);
            InitProgressWindow(PurchHeader);

            InvtPickPutaway := "Posting from Whse. Ref." <> 0;
            "Posting from Whse. Ref." := 0;

            CheckDimensions.CheckPurchDim(PurchHeader, TempPurchLineGlobal);

            if Invoice then
                CheckFAPostingPossibility(PurchHeader);

            if Invoice then
                if WithhSocSec.Get("Document Type", "No.") and
                   (WithhSocSec."Withholding Tax Code" <> '') and
                   (WithhSocSec."Total Amount" = 0) and
                   ("Document Type" = "Document Type"::Invoice)
                then
                    Error(Text1130006,
                      WithhSocSec.FieldCaption("Total Amount"), WithhSocSec.FieldCaption("Withholding Tax Code"));

            CheckPostRestrictions(PurchHeader);

            CheckICDocumentDuplicatePosting(PurchHeader);

            if Invoice then
                Invoice := CalcInvoice(PurchHeader, ReverseChargeVAT);

            if Invoice then
                ValidateIncludeInVATReport(PurchHeader);

            if Invoice then
                CopyAndCheckItemCharge(PurchHeader);

            if Receive then begin
                Receive := CheckTrackingAndWarehouseForReceive(PurchHeader);
                if (not InvtPickPutaway) and CheckIfInvPutawayExists(PurchHeader) then
                    Error(InvPutAwayExistsErr);
            end;

            if Ship then begin
                Ship := CheckTrackingAndWarehouseForShip(PurchHeader);
                if (not InvtPickPutaway) and CheckIfInvPickExists then
                    Error(InvPickExistsErr);
            end;

            if not (Receive or Invoice or Ship) then
                Error(NothingToPostErr);

            if Ship and
               ("Document Type" = "Document Type"::"Return Order") or
               (("Document Type" = "Document Type"::"Credit Memo") and PurchSetup."Return Shipment on Credit Memo")
            then
                CheckTDDData;

            CheckAssociatedOrderLines(PurchHeader);

            if Invoice and PurchSetup."Ext. Doc. No. Mandatory" then
                CheckExtDocNo(PurchHeader);

            OnAfterCheckPurchDoc(PurchHeader, SuppressCommit, WhseShip, WhseReceive);
            ErrorMessageMgt.Finish(RecordId);

            // Update
            if Invoice then
                CreatePrepmtLines(PurchHeader, true);

            ModifyHeader := UpdatePostingNos(PurchHeader, ReverseChargeVAT);

            if Invoice and ("Operation Occurred Date" < GLSetup."Last Gen. Jour. Printing Date") then
                FieldError("Operation Occurred Date", StrSubstNo(Text1130008, GLSetup."Last Gen. Jour. Printing Date"));

            DropShipOrder := UpdateAssosOrderPostingNos(PurchHeader);

            OnBeforePostCommitPurchaseDoc(PurchHeader, GenJnlPostLine, PreviewMode, ModifyHeader, SuppressCommit, TempPurchLineGlobal);
            if not PreviewMode and ModifyHeader then begin
                Modify;
                if not SuppressCommit then
                    Commit;
            end;

            OnCheckAndUpdateOnBeforeCalcInvDiscount(
              PurchHeader, TempWhseRcptHeader, TempWhseShptHeader, WhseReceive, WhseShip, RefreshTempLinesNeeded);
            if RefreshTempLinesNeeded then
                RefreshTempLines(PurchHeader, TempPurchLineGlobal);
            CalcInvDiscount(PurchHeader);
            ReleasePurchDocument(PurchHeader);

            if Receive or Ship then
                ArchiveUnpostedOrder(PurchHeader);

            CheckICPartnerBlocked(PurchHeader);
            SendICDocument(PurchHeader, ModifyHeader);
            UpdateHandledICInboxTransaction(PurchHeader);

            LockTables(PurchHeader);

            SourceCodeSetup.Get;
            SrcCode := SourceCodeSetup.Purchases;

            InsertPostedHeaders(PurchHeader);

            //> NEW CODE
            OnBeforePostedPaymentsInsert(PurchHeader, IsHandled);
            IF NOT IsHandled then 
            //< NEW CODE

                if Invoice then begin
                    PaymentTermsLine.Reset;
                    PaymentTermsLine.SetRange("Sales/Purchase", PaymentTermsLine."Sales/Purchase"::Purchase);
                    PaymentTermsLine.SetRange(Type, "Document Type");
                    PaymentTermsLine.SetRange(Code, "No.");
                    if PaymentTermsLine.Find('-') then
                        repeat
                            PostedPayments.Init;
                            PostedPayments."Sales/Purchase" := PaymentTermsLine."Sales/Purchase";
                            if "Document Type" in ["Document Type"::Order, "Document Type"::Invoice] then begin
                                PostedPayments.Type := PostedPayments.Type::Invoice;
                                PostedPayments.Code := PurchInvHeader."No.";
                            end else begin
                                PostedPayments.Type := PostedPayments.Type::"Credit Memo";
                                PostedPayments.Code := PurchCrMemoHeader."No.";
                            end;
                            PostedPayments."Line No." := PaymentTermsLine."Line No.";
                            PostedPayments."Payment %" := PaymentTermsLine."Payment %";
                            PostedPayments."Due Date Calculation" := PaymentTermsLine."Due Date Calculation";
                            PostedPayments."Discount Date Calculation" := PaymentTermsLine."Discount Date Calculation";
                            PostedPayments."Discount %" := PaymentTermsLine."Discount %";
                            PostedPayments."Due Date" := PaymentTermsLine."Due Date";
                            PostedPayments."Pmt. Discount Date" := PaymentTermsLine."Pmt. Discount Date";
                            PostedPayments.Insert;
                            PaymentJournalLine.Init;
                            PaymentJournalLine."Sales/Purchase" := 0;
                            PaymentJournalLine.Type := PaymentJournalLine.Type::"General Journal";
                            PaymentJournalLine."Line No." := PaymentTermsLine."Line No.";
                            PaymentJournalLine."Payment %" := PaymentTermsLine."Payment %";
                            PaymentJournalLine."Due Date Calculation" := PaymentTermsLine."Due Date Calculation";
                            PaymentJournalLine."Discount Date Calculation" := PaymentTermsLine."Discount Date Calculation";
                            PaymentJournalLine."Discount %" := PaymentTermsLine."Discount %";
                            PaymentJournalLine."Due Date" := PaymentTermsLine."Due Date";
                            PaymentJournalLine."Pmt. Discount Date" := PaymentTermsLine."Pmt. Discount Date";
                            PaymentJournalLine.Insert;
                        until PaymentTermsLine.Next = 0
                    else
                        if "Payment Terms Code" <> '' then
                            Error(Text1130003, FieldCaption("Payment Terms Code"), "Payment Terms Code");
                end;

            UpdateIncomingDocument("Incoming Document Entry No.", "Posting Date", GenJnlLineDocNo);
        end;

        OnAfterCheckAndUpdate(PurchHeader, SuppressCommit, PreviewMode);
    end;

**Comment by EleonoraLessCapBS** [comment]
NEW PUBLISHER:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostedPaymentsInsert(PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
