### ISSUE TITLE
[Event Request] Codeunit 80 "Sales.-Post" InsertPostedPayment; new event OnBeforeInsertPostedPayment

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7818]
Dear Microsoft,

We need to have new event: OnBeforeInsertPostedPaymenton Sales-Post Codeunit in function: InsertPostedPayment
Therefore we would appreciate your operation.
Thanks

local procedure InsertPostedPayment(SalesHeader: Record "Sales Header")
    var
        PaymentJournalLine: Record "Payment Lines";
        PaymentTermsLine: Record "Payment Lines";
        PostedPayments: Record "Posted Payment Lines";
	IsHandled: Boolean;
    begin
	//> NEW CODE
        OnBeforeInsertPostedPayment(SalesHeader, IsHandled);
        if IsHandled then
            exit;
	//< NEW CODE

        with SalesHeader do begin
            PaymentTermsLine.Reset;
            PaymentTermsLine.SetRange("Sales/Purchase", PaymentTermsLine."Sales/Purchase"::Sales);
            PaymentTermsLine.SetRange(Type, "Document Type");
            PaymentTermsLine.SetRange(Code, "No.");
            if PaymentTermsLine.Find('-') then
                repeat
                    PaymentTermsLine.TestField("Due Date");
                    PostedPayments.Init;
                    PostedPayments."Sales/Purchase" := PaymentTermsLine."Sales/Purchase";
                    if "Document Type" in ["Document Type"::Order, "Document Type"::Invoice] then begin
                        PostedPayments.Type := PostedPayments.Type::Invoice;
                        PostedPayments.Code := SalesInvHeader."No.";
                    end else begin
                        PostedPayments.Type := PostedPayments.Type::"Credit Memo";
                        PostedPayments.Code := SalesCrMemoHeader."No.";
                    end;
                    PostedPayments."Line No." := PaymentTermsLine."Line No.";
                    PostedPayments."Payment %" := PaymentTermsLine."Payment %";
                    PostedPayments."Due Date Calculation" := PaymentTermsLine."Due Date Calculation";
                    PostedPayments."Discount Date Calculation" := PaymentTermsLine."Discount Date Calculation";
                    PostedPayments."Discount %" := PaymentTermsLine."Discount %";
                    PostedPayments."Due Date" := PaymentTermsLine."Due Date";
                    PostedPayments."Pmt. Discount Date" := PaymentTermsLine."Pmt. Discount Date";
                    PostedPayments.Insert;
                    PaymentJournalLine.Init;
                    PaymentJournalLine."Sales/Purchase" := 0;
                    PaymentJournalLine.Type := PaymentJournalLine.Type::"General Journal";
                    PaymentJournalLine."Line No." := PaymentTermsLine."Line No.";
                    PaymentJournalLine."Payment %" := PaymentTermsLine."Payment %";
                    PaymentJournalLine."Due Date Calculation" := PaymentTermsLine."Due Date Calculation";
                    PaymentJournalLine."Discount Date Calculation" := PaymentTermsLine."Discount Date Calculation";
                    PaymentJournalLine."Discount %" := PaymentTermsLine."Discount %";
                    PaymentJournalLine."Due Date" := PaymentTermsLine."Due Date";
                    PaymentJournalLine."Pmt. Discount Date" := PaymentTermsLine."Pmt. Discount Date";
                    PaymentJournalLine.Insert;
                until PaymentTermsLine.Next = 0
            else
                if "Payment Terms Code" <> '' then
                    Error(Text1130003Err, FieldCaption("Payment Terms Code"), "Payment Terms Code");
        end;
    end;

NEW PUBLISHER:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertPostedPayment(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
