### ISSUE TITLE
[Event Request] Codeunit 5895 "Inventory Adjustment" UpdateItemUnitCost; new event OnBeforeUpdateItemUnitCost

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7819]
Dear Microsoft,

We need to have new event: OnBeforeUpdateItemUnitCost on "Inventory Adjustment" Codeunit in function: UpdateItemUnitCost
 Therefore we would appreciate your operation.
 Thanks

local procedure UpdateItemUnitCost(var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary)
    var
        AvgCostAdjmtPoint: Record "Avg. Cost Adjmt. Entry Point";
        FilterSKU: Boolean;
    begin
        with Item do begin
            if IsDeletedItem then
                exit;

            LockTable;
            Get("No.");

	    //> NEW CODE
	    OnBeforeUpdateItemUnitCost(Item);
	    //< NEW CODE

            if not LevelExceeded then begin
                "Allow Online Adjustment" := true;
                AvgCostAdjmtPoint.SetRange("Item No.", "No.");
                AvgCostAdjmtPoint.SetRange("Cost Is Adjusted", false);
                if "Costing Method" <> "Costing Method"::Average then begin
                    if AvgCostAdjmtPoint.FindFirst then
                        AvgCostAdjmtPoint.ModifyAll("Cost Is Adjusted", true);
                end;
                "Cost is Adjusted" := AvgCostAdjmtPoint.IsEmpty;
            end;

            if "Costing Method" <> "Costing Method"::Standard then begin
                if TempAvgCostAdjmtEntryPoint.FindSet then
                    repeat
                        FilterSKU := (TempAvgCostAdjmtEntryPoint."Location Code" <> '') or (TempAvgCostAdjmtEntryPoint."Variant Code" <> '');
                        ItemCostMgt.UpdateUnitCost(
                          Item, TempAvgCostAdjmtEntryPoint."Location Code", TempAvgCostAdjmtEntryPoint."Variant Code", 0, 0, true, FilterSKU, false, 0);
                    until TempAvgCostAdjmtEntryPoint.Next = 0
                else
                    Modify;
            end else
                Modify;
        end;

        TempAvgCostAdjmtEntryPoint.Reset;
        TempAvgCostAdjmtEntryPoint.DeleteAll;
    end;

NEW PUBLISHER:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateItemUnitCost(var Item: Record Item)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
