### ISSUE TITLE
[Event Request] Table 36 "Sales Header" SetOperationType; new event OnBeforeSetOperationType 

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7820]
Dear Microsoft,

We need to have new event: OnBeforeSetOperationType on "Sales Header" Table in function: SetOperationType
 Therefore we would appreciate your operation.
 Thanks

[Scope('OnPrem')]
    procedure SetOperationType()
    var
        IsHandled: Boolean;
    begin
	//> NEW CODE
	IsHandled := false;
	OnBeforeSetOperationType(Rec,IsHandled);
        if IsHandled then
            exit;
	//< NEW CODE

        if "Document Type" <> "Document Type"::"Credit Memo" then
            if "VAT Bus. Posting Group" <> '' then begin
                VATBusPostingGroup.Get("VAT Bus. Posting Group");
                if VATBusPostingGroup."Default Sales Operation Type" <> '' then
                    Validate("Operation Type", VATBusPostingGroup."Default Sales Operation Type");
            end;
    end;

NEW PUBLISHER:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetOperationType(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
