### ISSUE TITLE
[Event Request] Table 36 "Sales Header" InitInsert; new event OnAfterInitInsert 

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7821]
Dear Microsoft,

We need to have new event: OnAfterInitInsert  on "Sales Header" Table in function: InitInsert
 Therefore we would appreciate your operation.
 Thanks

    procedure InitInsert()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInitInsert(Rec, xRec, IsHandled);
        if not IsHandled then
            if "No." = '' then begin
                TestNoSeries;
                NoSeriesMgt.InitSeries(GetNoSeriesCode, xRec."No. Series", "Posting Date", "No.", "No. Series");
            end;

        OnInitInsertOnBeforeInitRecord(Rec, xRec);
        InitRecord;

        if "Document Type" = "Document Type"::Invoice then
            SetOperationType;

	//> NEW CODE
	OnAfterInitInsert(Rec);
	//< NEW CODE

    end;

NEW PUBLISHER:
    local procedure OnAfterInitInsert(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
