### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" GetNoSeriesCode; new event OnBeforeGetNoSeriesCode

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7823]
Dear Microsoft,

We need to have new event: OnBeforeGetNoSeriesCode on "Purchase Header" Table in function: GetNoSeriesCode
 Therefore we would appreciate your operation.
 Thanks

    procedure GetNoSeriesCode(): Code[20]
    var
        NoSeriesCode: Code[20];
        IsHandled: Boolean;
    begin
	//> NEW CODE
        IsHandled := false;
        OnBeforeGetNoSeriesCode(Rec, PurchSetup, NoSeriesCode, IsHandled);
        if IsHandled then
            exit;
	//< NEW CODE
        
	case "Document Type" of
            "Document Type"::Quote:
                NoSeriesCode := PurchSetup."Quote Nos.";
            "Document Type"::Order:
                NoSeriesCode := PurchSetup."Order Nos.";
            "Document Type"::Invoice:
                NoSeriesCode := PurchSetup."Invoice Nos.";
            "Document Type"::"Return Order":
                NoSeriesCode := PurchSetup."Return Order Nos.";
            "Document Type"::"Credit Memo":
                NoSeriesCode := PurchSetup."Credit Memo Nos.";
            "Document Type"::"Blanket Order":
                NoSeriesCode := PurchSetup."Blanket Order Nos.";
        end;
        OnAfterGetNoSeriesCode(Rec, PurchSetup, NoSeriesCode);
        exit(NoSeriesMgt.GetNoSeriesWithCheck(NoSeriesCode, SelectNoSeriesAllowed, "No. Series"));
    end;

NEW PUBLISHER:
    local procedure OnBeforeGetNoSeriesCode(var PurchaseHeader: Record "Purchase Header"; PurchSetup: Record "Purchases & Payables Setup"; var NoSeriesCode: Code[20]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
