### ISSUE TITLE
[Event Modify] Codeunit 90 "Purch.-Post" PostGLAndVendor; added parameter (IsHandled) on OnBeforePostGLAndVendor event 

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7824]
Dear Microsoft,

We need to add new paramenter to OnBeforePostGLAndVendor event on Purch-Post Codeunit in function: PostGLAndVendor
Therefore we would appreciate your operation.
Thanks

    local procedure PostGLAndVendor(var PurchHeader: Record "Purchase Header"; var TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary)
    var
        IsHandled: Boolean;
    begin

        //> NEW CODE      
        //OnBeforePostGLAndVendor(PurchHeader, TempInvoicePostBuffer, PreviewMode, SuppressCommit, GenJnlPostLine);
        IsHandled := false;
        OnBeforePostGLAndVendor(PurchHeader, TempInvoicePostBuffer, PreviewMode, SuppressCommit, GenJnlPostLine, IsHandled);
        if IsHandled then
            exit;
        //< NEW CODE
....

EVENT PUBLISHER MODIFIED:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostGLAndVendor(var PurchHeader: Record "Purchase Header"; var TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; PreviewMode: Boolean; CommitIsSupressed: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
