### ISSUE TITLE
[Event Modify] Codeunit 80 "Sales-Post" FinalizePosting; added parameter (Ship) on OnAfterFinalizePosting event  

### ISSUE THREAD

**Issue by EleonoraLessCapBS** [microsoft/ALAppExtensions#7825]
Dear Microsoft,

We need to add new paramenter to OnBeforePostGLAndVendor event on Purch-Post Codeunit in function: PostGLAndVendor
Therefore we would appreciate your operation.
Thanks

[Event Modify] Codeunit 80 "Sales-Post" FinalizePosting; added parameter (Ship) on OnAfterFinalizePosting event  
Dear Microsoft,

We need to add new paramenter to OnAfterFinalizePosting event on Sales-Post Codeunit in function: FinalizePosting
Therefore we would appreciate your operation.
Thanks

local procedure FinalizePosting(var SalesHeader: Record "Sales Header"; EverythingInvoiced: Boolean; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary)
    var
        TempSalesLine: Record "Sales Line" temporary;
        GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
        ICInboxOutboxMgt: Codeunit ICInboxOutboxMgt;
        WhseSalesRelease: Codeunit "Whse.-Sales Release";
        ArchiveManagement: Codeunit ArchiveManagement;
        IsHandled: Boolean;
    begin
        OnBeforeFinalizePosting(SalesHeader, TempSalesLineGlobal, EverythingInvoiced, SuppressCommit, GenJnlPostLine);

        with SalesHeader do begin
 …...………………………………………………………………………………………………………………………………………………………………………………...
            IsHandled := false;
            OnFinalizePostingOnBeforeCreateOutboxSalesTrans(SalesHeader, IsHandled);
            if not IsHandled then
                if Invoice and ("Bill-to IC Partner Code" <> '') then
                    if "Document Type" in ["Document Type"::Order, "Document Type"::Invoice] then
                        ICInboxOutboxMgt.CreateOutboxSalesInvTrans(SalesInvHeader)
                    else
                        ICInboxOutboxMgt.CreateOutboxSalesCrMemoTrans(SalesCrMemoHeader);

              //> NEW CODE
	      //OnAfterFinalizePosting(
              //SalesHeader, SalesShptHeader, SalesInvHeader, SalesCrMemoHeader, ReturnRcptHeader,
              //GenJnlPostLine, SuppressCommit, PreviewMode);
	      
 	      OnAfterFinalizePosting(
              SalesHeader, SalesShptHeader, SalesInvHeader, SalesCrMemoHeader, ReturnRcptHeader,
              GenJnlPostLine, SuppressCommit, PreviewMode,Ship);
	      //< NEE CODE

            ClearPostBuffers;
        end;
    end;

EVENT PUBLISHER MODIFIED:
  [IntegrationEvent(false, false)]
    local procedure OnAfterFinalizePosting(var SalesHeader: Record "Sales Header"; var SalesShipmentHeader: Record "Sales Shipment Header"; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var ReturnReceiptHeader: Record "Return Receipt Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; CommitIsSuppressed: Boolean; PreviewMode: Boolean; Ship: Boolean)
    begin
    end;

**Comment by RomanZanizdra** [comment]
Hi @EleonoraLessCapBS .
Could you give some explanation for the new parameter? Because according your code it is the field from SalesHeader which is accessible in the same event. If this is something else then please describe what is it.

**Comment by RomanZanizdra** [comment]
Hi @EleonoraLessCapBS , any update from side?

**Comment by EleonoraLessCapBS** [comment]
Good morning,

thanks for your reply.
I just verified and I saw, as you said, that “ship” is a field of Sales Header Table. Therefore I really thank you and I cancel this ticket request.

Have a nice day
Eleonora
____________________________________________________________________
Eleonora Less
Microsoft Dynamics NAV™ | Analyst Consultant - Developer

Capgemini Italia | Genova
Tel.: +39 010 846311 – Mob.: + 39 346 1882379
www.capgemini.com<http://www.capgemini.com/>

Piazza dello Zerbino, 3 – 16122 Genova
[https://visualidentity.capgemini.com/capgemini.png]
____________________________________________________________________
Connect with Capgemini:
[cid:image002.png@01D659D5.D1B34060]<https://www.capgemini.com/insights-and-resources/blogs> [cid:image003.png@01D659D5.D1B34060] <https://www.twitter.com/capgemini>  [cid:image004.png@01D659D5.D1B34060] <https://www.facebook.com/capgemini>  [cid:image005.png@01D659D5.D1B34060] <https://www.linkedin.com/company/capgemini>  [cid:image006.png@01D659D5.D1B34060] <https://www.youtube.com/capgeminimedia>  [cid:image007.png@01D659D5.D1B34060] <https://www.slideshare.net/capgemini>  [cid:image008.png@01D659D5.D1B34060] <https://plus.google.com/+CapgeminiGlobal>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.
