### ISSUE TITLE
[EventRequest] Codeunit 5817 Undo Posting Management - OnPostItemJnlLineOnBeforePostJobConsumption

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#7828]
Requesting a new event publisher on Codeunit 5817 Undo PostingManagement

Event
`OnPostItemJnlLineOnBeforePostJobConsumption(VAR ItemJnlLine : Record "Item Journal Line", VAR IsHandled : Boolean)`

**Code**
## [External] PostItemJnlLine(VAR ItemJnlLine : Record "Item Journal Line")
```
CLEAR(ItemJnlLine2);
ItemJnlLine2 := ItemJnlLine;

IF ItemJnlLine2."Job No." <> '' THEN
  PostJobConsumptionBeforePurch := PostItemJnlLineForJob(ItemJnlLine,ItemJnlLine2);

ItemJnlPostLine.RUN(ItemJnlLine);
```
**>>> New Code**
```
IsHandled := FALSE;
OnPostItemJnlLineOnBeforePostJobConsumption(ItemJnlLine2,IsHandled);
IF NOT IsHandled THEN
```
**<<< New Code End**
```
  IF ItemJnlLine2."Job No." <> '' THEN
    IF NOT PostJobConsumptionBeforePurch THEN BEGIN
      SetItemJnlLineAppliesToEntry(ItemJnlLine2,ItemJnlLine."Item Shpt. Entry No.");
      ItemJnlPostLine.RUN(ItemJnlLine2);
    END;
```
In Our Solution we know real Job Inventories. Which means in case of a Purchase Receipt The Receipt Item Ledger Entry is not directly negatively corrected. Also we do not Value this receipt, Unit Cost = 0 because the value will be posted via the Purchase Invoice and also then the Job Ledger Entry with Value will be posted. This means in the process of undo posting on this Job Purchase Receipt we do not have the Negative Adjustment Item Ledger Entry the system wants to find and also we do not have value that needs to be corrected. In this case we need the flexibility to skip this job correction past entirely. Please add the requested Publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
