### ISSUE TITLE
[Event Request] Codeunit 63 "Sales-Explode BOM" / OnAfterInsertOfExplodedBOMLineToSalesLine

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#7833]
I would like to ask you to build the event [OnAfterInsertOfExplodedBOMLineToSalesLine] in codeunit 63 (Sales-Explode BOM) in function ExplodeBOMCompLines.
It would be the "Event-Counterpart" for the existing event "OnInsertOfExplodedBOMLineToSalesLine"

```
local procedure ExplodeBOMCompLines(SalesLine: Record "Sales Line")
...
  OnInsertOfExplodedBOMLineToSalesLine(ToSalesLine, SalesLine, FromBOMComp);

  ToSalesLine.Insert();
  
  >>>>NEW BEGIN>>>>
  OnAfterInsertOfExplodedBOMLineToSalesLine(ToSalesLine, SalesLine, FromBOMComp);
  <<<<NEW END<<<<
...
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterInsertOfExplodedBOMLineToSalesLine(ToSalesLine: Record "Sales Line"; SalesLine: Record "Sales Line"; BOMComponent: Record "BOM Component")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
