### ISSUE TITLE
Attachements are not copying while creating Sales Order from Blanket Sales Order

### ISSUE THREAD

**Issue by MaheshUppala** [microsoft/ALAppExtensions#7835]
1.  Create a Blanket Sales Order with items.
2.  Add attachements using Attachments factbox.
3.  Click on Make Order action
4.  Now blanket sales order will convert to sales order, But attachements are not copying to created Sales order.
5.  This is working fine in Blanket Purchase Order.

I have checked in code and below are my findings

Codeunit 87 "Blanket Sales Order to Order"
Function CreateSalesHeader
![image](https://user-images.githubusercontent.com/34763546/87167753-1560f400-c2eb-11ea-8a15-5be0949ecc0c.png)

For above highlighted publisher there is a subscriber in codeunit 1173
![image](https://user-images.githubusercontent.com/34763546/87167808-2dd10e80-c2eb-11ea-93d4-d1b8c5fadfd7.png)

the above highlighted condition becomes true because of before calling publisher SalesOrderHeader No. is assigning with empty. see below image
![image](https://user-images.githubusercontent.com/34763546/87167831-36c1e000-c2eb-11ea-9653-54bec6947b8d.png)

beause of that it exists without executing rest of the code.

If you create a subscriber for OnBeforeSalesOrderHeaderModify then it will solve the issue.
![image](https://user-images.githubusercontent.com/34763546/87169221-42aea180-c2ed-11ea-9b45-7d3e3289fc28.png)

Could you please check and solve this.

**Comment by RomanZanizdra** [comment]
Hi @MaheshUppala .
Follow from you description it looks like a bug but not event request. Could be so kind to reach out to the relevant support channel for example https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f and create support request there?

**Comment by RomanZanizdra** [comment]
@MaheshUppala , any objections if we close current issue and you will open relevant support request?

**Comment by MaheshUppala** [comment]
No you can close it will create that issue in support link

**Comment by RomanZanizdra** [comment]
Ok, thanks for collaboration.
