### ISSUE TITLE
[Extensibility] SuppressCommit in Codeunit "Service-Post"

### ISSUE THREAD

**Issue by J-KVS** [microsoft/ALAppExtensions#7836]
I'd like to propose to introduce a variable to determine whether the Codeunit should omit the Commit as well as a public setter function as it is already implemented in the Sales and Purchase Posting Codeunits. Below is a suggestion for the implementation.

Please let me know if you need more information from me.

![grafik](https://user-images.githubusercontent.com/68116795/87166596-1a627b00-c2cc-11ea-8748-3d70e2db411e.png)
![grafik](https://user-images.githubusercontent.com/68116795/87166639-26e6d380-c2cc-11ea-815b-cfb219198f5a.png)
![grafik](https://user-images.githubusercontent.com/68116795/87166679-32d29580-c2cc-11ea-827e-249cbea9bd2b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
