### ISSUE TITLE
[Event Request] Database::"Item Vendor" - Function UpdateItemCrossReference - OnBeforeUpdateItemCrossReference

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7839]
We like to request the following Event:
Object: Database::"Item Vendor"
Function: UpdateItemCrossReference
Publisher Event: OnBeforeUpdateItemCrossReference
Reason: To implement custom business logic
Where is the event placed:
local procedure UpdateItemCrossReference()
    var
        IsHandled: Boolean;
    begin
        **OnBeforeUpdateItemCrossReference(Rec, IsHandled);
        if IsHandled then
            exit;**
        if ItemCrossReference.WritePermission then

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateItemCrossReference(var ItemVendor: Record "Item Vendor"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
