### ISSUE TITLE
[Event Request] Table 81 Field Gen Posting Type - OnValidate

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#784]
We need a new Handle Publisher on Field Gen Posting Type - OnValidate
--

![image](https://user-images.githubusercontent.com/42136602/50957445-89d09200-14be-11e9-95f0-658b0ae76116.png)

**Comment by AlexanderYakunin** [comment]
Can you explain purpose of this event?

**Comment by ThomasBrendel** [comment]
We have some sort of Code where it is not necessary to make this Testfield, instead in our solution it has to be filled instead. So we dont need the Testfield under specific circumstances.
