### ISSUE TITLE
[Event Request] Database::"Job Journal Line" - Function UpdateAmountsAndDiscounts - OnBeforeUpdateAmountsAndDiscounts

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7840]
We like to request the following Event:
Object: Database::"Job Journal Line"
Function: UpdateAmountsAndDiscounts
Publisher Event: OnBeforeUpdateAmountsAndDiscounts
Reason: To implement custom business logic
Where is the event placed:
local procedure UpdateAmountsAndDiscounts()
    var
        IsHandled: Boolean;
    begin
        **OnBeforeUpdateAmountsAndDiscounts(Rec, IsHandled);
        if IsHandled then
            exit;**
        if "Total Price" <> 0 then begin
            if ("Line Amount" <> xRec."Line Amount") and ("Line Discount Amount" = xRec."Line Discount Amount") then begin
                "Line Amount" := Round("Line Amount", AmountRoundingPrecisionFCY);
                "Line Discount Amount" := "Total Price" - "Line Amount";
                "Line Amount (LCY)" := Round("Line Amount (LCY)", AmountRoundingPrecision);
                "Line Discount Amount (LCY)" := "Total Price (LCY)" - "Line Amount (LCY)";
                "Line Discount %" := Round("Line Discount Amount" / "Total Price" * 100, 0.00001);

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateAmountsAndDiscounts(var JobJournalLine: Record "Job Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
