### ISSUE TITLE
[Event Request] Database::"Job Planning Line" - Function UpdateAmountsAndDiscounts - OnBeforeUpdateAmountsAndDiscounts

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7841]
We like to request the following Event:
Object: Database::"Job Planning Line"
Function: UpdateAmountsAndDiscounts
Publisher Event: OnBeforeUpdateAmountsAndDiscounts
Reason: To implement custom business logic
Where is the event placed:
local procedure UpdateAmountsAndDiscounts()
    var
        IsHandled: Boolean;
    begin
        **OnBeforeUpdateAmountsAndDiscounts(Rec, xRec, IsHandled);
        if IsHandled then
            exit;**
        if "Total Price" = 0 then begin
            "Line Amount" := 0;
            "Line Discount Amount" := 0;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateAmountsAndDiscounts(var JobPlanningLine: Record "Job Planning Line"; var xJobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
