### ISSUE TITLE
[Event Request] Database::"Payment Terms" - Function TranslateDescription - OnAfterTranslateDescription

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7842]
We like to request the following Event:
Object: Database::"Payment Terms"
Function: TranslateDescription
Publisher Event: OnAfterTranslateDescription
Reason: To implement custom business logic
Where is the event placed:
procedure TranslateDescription(var PaymentTerms: Record "Payment Terms"; Language: Code[10])
    var
        PaymentTermsTranslation: Record "Payment Term Translation";
    begin
        if PaymentTermsTranslation.Get(PaymentTerms.Code, Language) then
            PaymentTerms.Description := PaymentTermsTranslation.Description;
        **OnAfterTranslateDescription(PaymentTerms, Language);**
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterTranslateDescription(var PaymentTerms: Record "Payment Terms"; Language: Code[10])
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
