### ISSUE TITLE
[Event Request] Database::"Prepayment Inv. Line Buffer" - Function IncrAmounts - OnAfterIncrAmounts

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7843]
We like to request the following Event:
Object: Database::"Prepayment Inv. Line Buffer"
Function: IncrAmounts
Publisher Event: OnAfterIncrAmounts
Reason: To implement custom business logic
Where is the event placed:
procedure IncrAmounts(PrepmtInvLineBuf: Record "Prepayment Inv. Line Buffer")
    begin
        Amount := Amount + PrepmtInvLineBuf.Amount;
        "Amount Incl. VAT" := "Amount Incl. VAT" + PrepmtInvLineBuf."Amount Incl. VAT";
        "VAT Amount" := "VAT Amount" + PrepmtInvLineBuf."VAT Amount";
        "VAT Base Amount" := "VAT Base Amount" + PrepmtInvLineBuf."VAT Base Amount";
        "Amount (ACY)" := "Amount (ACY)" + PrepmtInvLineBuf."Amount (ACY)";
        "VAT Amount (ACY)" := "VAT Amount (ACY)" + PrepmtInvLineBuf."VAT Amount (ACY)";
        "VAT Base Amount (ACY)" := "VAT Base Amount (ACY)" + PrepmtInvLineBuf."VAT Base Amount (ACY)";
        "VAT Difference" := "VAT Difference" + PrepmtInvLineBuf."VAT Difference";
        **OnAfterIncrAmounts(Rec, PrepmtInvLineBuf);**
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterIncrAmounts(var PrepaymentInvLineBuffer: Record "Prepayment Inv. Line Buffer"; PrepmtInvLineBuf: Record "Prepayment Inv. Line Buffer")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
