### ISSUE TITLE
[Event Request] Database::"Prepayment Inv. Line Buffer" - Function ReverseAmounts - OnAfterReverseAmounts

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7844]
We like to request the following Event:
Object: Database::"Prepayment Inv. Line Buffer"
Function: ReverseAmounts
Publisher Event: OnAfterReverseAmounts
Reason: To implement custom business logic
Where is the event placed:
procedure ReverseAmounts()
    begin
        Amount := -Amount;
        "Amount Incl. VAT" := -"Amount Incl. VAT";
        "VAT Amount" := -"VAT Amount";
        "VAT Base Amount" := -"VAT Base Amount";
        "Amount (ACY)" := -"Amount (ACY)";
        "VAT Amount (ACY)" := -"VAT Amount (ACY)";
        "VAT Base Amount (ACY)" := -"VAT Base Amount (ACY)";
        "VAT Difference" := -"VAT Difference";
        **OnAfterReverseAmounts(Rec);**
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterReverseAmounts(var PrepaymentInvLineBuffer: Record "Prepayment Inv. Line Buffer")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
