### ISSUE TITLE
[Event Request] Database::"Prod. Order Line" - Function CheckEndingDate - OnBeforeCheckEndingDate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7845]
We like to request the following Event:
Object: Database::"Prod. Order Line"
Function: CheckEndingDate
Publisher Event: OnBeforeCheckEndingDate
Reason: To implement custom business logic
Where is the event placed:
procedure CheckEndingDate(ShowWarning: Boolean)
    var
        CheckDateConflict: Codeunit "Reservation-Check Date Confl.";
    begin
        **OnBeforeCheckEndingDate(Rec, ShowWarning);**
        if not Blocked then begin
            CheckDateConflict.ProdOrderLineCheck(Rec, ShowWarning);
            ReserveProdOrderLine.AssignForPlanning(Rec);
        end;
        OnAfterCheckEndingDate(Rec);
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckEndingDate(var ProdOrderLine: Record "Prod. Order Line"; var ShowWarning: Boolean);
    begin
    end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
