### ISSUE TITLE
[Event Request] Table 288 Vendor Bank Account - OnBeforeLookupName

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#7847]
Please add a new publisher event to the trigger OnLookup for Field with Id 3 "Name" like this:

```
Name - OnLookup()
//>> Start event publisher
OnBeforeLookupName(Rec, xRec);
//>> End event publisher

```

New Publisher Event:

```
LOCAL [IntegrationEvent] OnBeforeLookupName(VAR VendorBankAccount : Record "Vendor Bank Account";xVendorBankAccount : Record "Vendor Bank Account")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
