### ISSUE TITLE
[Event Request] New event in UpdateRecurringAmt in C13

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/ALAppExtensions#7848]
Hello,

I need event in Codeunit 13 in procedure UpdateRecurringAmt:

    local procedure UpdateRecurringAmt(var GenJnlLine2: Record "Gen. Journal Line"): Boolean
    begin
      //new event request
      > OnBeforeUpdateRecurringAmt(var GenJnlLine2: Record "Gen. Journal Line"; var IsModified; var Handled);
      > if Handled then
      >   exit(IsModified);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
