### ISSUE TITLE
[Function Global] table 5409 "Prod. Order Routing Line" - SubcontractPurchOrderExist()

### ISSUE THREAD

**Issue by andreas-koenig-kuma** [microsoft/ALAppExtensions#7849]
[Function Global] table 5409 "Prod. Order Routing Line" - SubcontractPurchOrderExist()

Can you please set the function SubcontractPurchOrderExist() to Global in table 5409 "Prod. Order Routing Line"? 

```
//>>>>>>>>    
procedure SubcontractPurchOrderExist(): Boolean
// <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
