### ISSUE TITLE
[Event Request] Table 81 Field Gen. Bus. Posting Group - OnValidate()

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#785]
We need a new handle publisher on field Gen. Bus. Posting Group - OnValidate()

![image](https://user-images.githubusercontent.com/42136602/50959968-893afa00-14c4-11e9-95ec-c63c05601626.png)

**Comment by AlexanderYakunin** [comment]
Can you explain purpose of this event?

**Comment by ThomasBrendel** [comment]
We have some sort of Code where it is not necessary to make this Testfield, instead in our solution it has to be filled instead. So we dont need the Testfield under specific circumstances.
