### ISSUE TITLE
[CorrectParameterRequest] FinanceChargeMemoLine.Table.al (table 303 "Finance Charge Memo Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7851]
HI MS,

Please add below requested parameter in given event in **FinanceChargeMemoLine.Table.al** table.

**Existing code**
[IntegrationEvent(false, false)]
    local procedure OnAfterSetCustLedgEntryView(var CustLedgEntry: Record "Cust. Ledger Entry"; FinChrgTerms: Record "Finance Charge Terms")
    begin
    end;

**Requested Parameter**
[IntegrationEvent(false, false)]
    local procedure OnAfterSetCustLedgEntryView(var CustLedgEntry: Record "Cust. Ledger Entry"; **_FinChrgMemoHeader: Record "Finance Charge Memo Header"_**)
    begin
    end;

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
