### ISSUE TITLE
[ParameterRequest] JobPlanningLine.Table.al (table 1003 "Job Planning Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7852]
HI MS,

Can you please help us by adding below parameter in given event in **JobPlanningLine.Table.al** table.

**Existing Event Signature**
 [IntegrationEvent(true, false)]
    local procedure OnBeforeFindPriceAndDiscount(CalledByFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Requested Event Signature**
 [IntegrationEvent(true, false)]
    local procedure OnBeforeFindPriceAndDiscount(CalledByFieldNo: Integer; var IsHandled: Boolean; **_var JobPlanningLine: Record "Job Planning Line"_**)
    begin
    end;

 if RetrieveCostPrice and ("No." <> '') then begin
            IsHandled := false;
            OnBeforeFindPriceAndDiscount(CalledByFieldNo, IsHandled,**_Rec_**);
            if IsHandled then
                exit;

Thanks
SUD

**Comment by StanPesotskiy** [comment]
OnBeforeFindPriceAndDiscount() already includes the sender. 

    [EventSubscriber(ObjectType::Table, Database::"Job Planning Line", 'OnBeforeFindPriceAndDiscount', '', false, false)]
    local procedure OnBeforeFindPriceAndDiscount(**var Sender: Record "Job Planning Line";** CalledByFieldNo: Integer; var IsHandled: Boolean);
