### ISSUE TITLE
[ParameterRequest] SalesTaxCalculate.Codeunit.al (codeunit 398 "Sales Tax Calculate")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7853]
Hi MS,

Please help us by adding below parameter in given event in **SalesTaxCalculate.Codeunit.al** codeunit.

**Existing Event signature**
OnDistTaxOverSalesLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(TempSalesTaxLine, SalesLine, SalesHeader);

[IntegrationEvent(false, false)]
    local procedure OnDistTaxOverSalesLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary; SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header")
    begin
    end;

**Requested Event Signature**
OnDistTaxOverSalesLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(**_Amount_**,TempSalesTaxLine, SalesLine, SalesHeader);

[IntegrationEvent(false, false)]
    local procedure OnDistTaxOverSalesLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(**_var Amount: Decimal_**;var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary; SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header")
    begin
    end;

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
