### ISSUE TITLE
[ParameterRequest] SalesTaxCalculate.Codeunit.al (codeunit 398 "Sales Tax Calculate")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7854]
Hi MS,

Please help us by adding below parameter in given event in **SalesTaxCalculate.Codeunit.al** codeunit.

**Existing Event Signature**
Amount := (PurchLine."Line Amount" - PurchLine."Inv. Discount Amount");
                                OnDistTaxOverPurchLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(TempSalesTaxLine, PurchLine, PurchHeader);

[IntegrationEvent(false, false)]
    local procedure OnDistTaxOverPurchLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary; PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header")
    begin
    end;

**Requested Event Signature**
 Amount := (PurchLine."Line Amount" - PurchLine."Inv. Discount Amount");
                                OnDistTaxOverPurchLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(**_Amount_**,TempSalesTaxLine, PurchLine, PurchHeader);

[IntegrationEvent(false, false)]
    local procedure OnDistTaxOverPurchLinesOnTempSalesTaxLineLoopOnAfterSetTempSalesTaxLineAmount(**_var Amount : Decimal_**;var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary; PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header")
    begin
    end;

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
