### ISSUE TITLE
[EventPropertyRequest] GenJnlPostLine.Codeunit.al (codeunit 12 "Gen. Jnl.-Post Line")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#7855]
Hi MS,

Please help us by adding below property on given event in **GenJnlPostLine.Codeunit.al** codeunit.

**Existing Event Signature**
[IntegrationEvent(false, false)]
    local procedure OnPostVendOnBeforeInitVendLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; var VendLedgEntry: Record "Vendor Ledger Entry"; var CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var VendPostingGr: Record "Vendor Posting Group")
    begin
    end;

**Requested Event Signature**
[IntegrationEvent(**_true_**, false)]
    local procedure OnPostVendOnBeforeInitVendLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; var VendLedgEntry: Record "Vendor Ledger Entry"; var CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var VendPostingGr: Record "Vendor Posting Group")
    begin
    end;

Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
