### ISSUE TITLE
[Event Request] Table 81 Field Gen. Prod. Posting Group - OnValidate

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#786]

**Comment by ThomasBrendel** [comment]
We need a new handle publisher for that field

![image](https://user-images.githubusercontent.com/42136602/50960970-e768dc80-14c6-11e9-8c27-daee94224dc5.png)

**Comment by AlexanderYakunin** [comment]
Can you explain purpose of this event?

**Comment by ThomasBrendel** [comment]
We have some sort of Code where it is not necessary to make this Testfield, instead in our solution it has to be filled instead. So we dont need the Testfield under specific circumstances.
