### ISSUE TITLE
[Extensibility Request]  table 1511 "Notification Entry" Change Type to Enum

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#7862]
Could you change the option `Type` to enum?

Some places that would need a new event are:

Codeunit 1509 Notification Entry Dispatcher:
 - procedure GetTargetRecRef:

In Codeunit 1510 the `procedure GetActionTextFor` already has an handled event that could be used to handle new enum values.
Other places where option should be changed to enum:

Codeunit 1509 Notification Entry Dispatcher:
 - procedure ScheduledInstantly

Codeunit 1510 Notification Management:
 - procedure CreateDefaultNotificationSetup
 - procedure DefaultNotificationEntryExists

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by pri-kise** [comment]
I'm not sure if I should create additional requests, but if this option will be updated the related tables should be changed to enum, too.
- `table 1512 "Notification Setup"`
- `table 1513 "Notification Schedule"`
