### ISSUE TITLE
Change Global Boolean Variables in Page Properties to protected var

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#7864]
Please set all global boolean variables that are used in Page Fields as Editable / Enabled / HideValue Properties to protected var.

I know this is a lot of work. It would be nice if you could already implement this for the following pages.
These are currently the showstoppers for my extension........

Item List
Reservation Entries
Production Journal
Whse. Receipt Subform
Whse. Put-Away Subform
Item Tracking Summary
Item Tracking Lines
Whse. Item Tracking Lines
Assembly Order
Assembly Quote
Blanket Assembly Order
Sales Quote Subform

**Comment by AlexanderYakunin** [comment]
Please explain why do you need all this? Cal you also provide name of your extension and partner?

**Comment by sschuh** [comment]
We are a gold partner from Herdecke in Germany.
www.mumdat.de

We are currently redesigning our industry solution.

We are active in the steel industry.
In the steel industry, additional "quantity fields" such as kilograms, meters and pieces are required.

For the new kilogram pieces and meters fields, the same visibilities / editabilities must be carried out as for the standard quantity fields.

**Comment by AlexanderYakunin** [comment]
Understand, we'll investigate what and how we can do for you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
