### ISSUE TITLE
Change several Page functions to global 

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#7865]
It would be super cool if you could set the following page functions on Global.
That would save me from duplicating these functions in my extension.

In detail....

**Page Job Planning Lines**
Function: QuantityOnAfterValidate

**Page Sales Order Subform**
Function: QuantityOnAfterValidate
Function: QtyToAsmToOrderOnAfterValidate

**Page Sales Invoice Subform**
Function: ValidateAutoReserve

**Page Reservation Entries**
Function: QuantityBaseOnAfterValidate

**Page Blanket Sales Order Subform**
Function: QuantityOnAfterValidate
Function: DeltaUpdateTotals

**Page Blanket Purchase Order Subform**
Function: DeltaUpdateTotals

**Page Whse. Receipt Subform**
Function: QtytoReceiveOnAfterValidate
Function: ShowCrossDockOpp

**Page Whse. Put-away Subform**
Function: QtytoHandleOnAfterValidate

**Page Whse. Pick Subform**
Function: QtytoHandleOnAfterValidate

**Page Service Item Worksheet Subform**
Function: QuantityOnAfterValidate

**Page Service Invoice Subform**
Function: QuantityOnAfterValidate

**Page Service Credit Memo Subform**
Function: QuantityOnAfterValidate

**Page Service Quote Lines**
Function: QuantityOnAfterValidate

**Page Item Tracking Summary**
Function: DrillDownEntries

**Page Item Tracking Lines**
Function: QuantityBaseOnValidate
Function: QuantityBaseOnAfterValidate
Function: QtytoHandleBaseOnAfterValidate
Function: QtytoInvoiceBaseOnAfterValidat

**Page Whse. Item Tracking Lines**
Function: QuantityBaseOnAfterValidate
Function: QtytoHandleBaseOnAfterValidate

**Page Sales Return Order Subform**
Function: QuantityOnAfterValidate

**Page Warehouse Movement Subform**
Function: QtytoHandleOnAfterValidate

**Page Whse. Shipment Subform**
Function: QuantityOnAfterValidate

**Page Pick Worksheet**
Function: QtytoHandleOnAfterValidate

**Page Movement Worksheet**
Function: QuantityOnAfterValidate

**Page Put-away Worksheet**
Function: QtytoHandleOnAfterValidate

**Page Invt. Put-away Subform**
Function: QtytoHandleOnAfterValidate

**Page Invt. Pick Subform**
Function: QtytoHandleOnAfterValidate

**Page Invt. Movement Subform**
Function: QtytoHandleOnAfterValidate

**Page Assembly Order Subform**
Function: ReserveItem

**Page Sales Quote Subform**
Function: QuantityOnAfterValidate

**Page Sales Cr. Memo Subform**
Function: QuantityOnAfterValidate

**Page Planned Prod. Order Lines**
Function: ReservedQuantityOnAfterValidat

**Page Prod. Order Components**
Function: QuantityperOnAfterValidate

**Comment by AlexanderYakunin** [comment]
Please explain why do you need all this? Cal you also provide name of your extension and partner?

**Comment by sschuh** [comment]
We are a gold partner from Herdecke in Germany. 
www.mumdat.de

We are currently redesigning our industry solution.

We are active in the steel industry.
In the steel industry, additional "quantity fields" such as kilograms, meters and pieces are required.

For the new kilogram pieces and meters fields, the same triggers must be carried out as for the standard quantity fields.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
