### ISSUE TITLE
Table 5406 Prod. Order Line - IsDynamicTrackingBlocked

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#7866]
Hello team,

please add the following function to read the "Blocked" value to table 5406 Prod. Order Line:

```
procedure IsDynamicTrackingBlocked(): Boolean
    begin
        exit(Blocked);
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
