### ISSUE TITLE
Report 10083 "Export Electronic Payments"

### ISSUE THREAD

**Issue by eclipses** [microsoft/ALAppExtensions#7867]
Hi, 

On the function ProcessVendor there is a check that only one Vendor Bank Account can be marked as "Use for Electronic Payments". 
I do not understand the reason why is limiting. In the general journal lines can be specified a different Bank Account in the field "Recipient Bank Account".
Being a report I know that I can make a copy of it and change the report selection to use my custom report but I would prefer it if Microsoft can reconsider this limitation. 
Multiple Vendor Bank Account can be set up as "Use for Electronic Payments", the error is coming only when running this report.

**Comment by AlexanderYakunin** [comment]
Hello, this forum is for requests related with extensibility for extension development. If you have suggestion, please publish it here: https://aka.ms/bcideas.

**Comment by eclipses** [comment]
This functionality is more extended than expected, there is a check also when Generating EFT files. I'd like to know the reason for these limitations and eventually, Microsoft should offer publishers to skip these checks.

**Comment by eclipses** [comment]
Submit an idea is useless because not considered before you receive a lot of votes. I submitted a few ideas and after months they are still in status NEW.

**Comment by eclipses** [comment]
Found the same limitation in the method CheckVendorTransitNum in the codeunit 10090 "Export Payments (ACH)"
