### ISSUE TITLE
General Ledger Setup and Posting Direct Applied Cost Account

### ISSUE THREAD

**Issue by kvamsdal** [microsoft/ALAppExtensions#7870]
Hi. 

Direct Applied Cost account should not be used unless Automatic Cost Posting is enabled. However, we cannot post without having a Direct Applied Cost account set up.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support:
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
