### ISSUE TITLE
Request for new table and page for posted Service Item Line

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#7874]
Hi,

There are a lot of needs and requests from market regarding posted service documents. Most of them are related to table Service Item Line. Is it possible that you can create a workflow for posting table service item line to new table "Pstd. Service Item Line".
We have concept to share with you if you like.
That would be very cool to have it on standard :)

Thank you in advance

**Comment by StanPesotskiy** [comment]
For the new features please submit a product suggestion on https://aka.ms/bcideas
