### ISSUE TITLE
Fix needed to requested event OnCheckOrderLineOnBeforeGetSamePhysInvtOrderLine in Codeunit PhysInvtOrderPost

### ISSUE THREAD

**Issue by ichladil** [microsoft/ALAppExtensions#7875]
Please fix the IsHandled pattern implementation of event requested in CheckOrderLine function in PhysInvtOrderPost.Codeunit.al as requested in https://github.com/microsoft/ALAppExtensions/issues/4440

The IsHandled value returned in CheckOrderLine is never used. Please add the missing   **if not IsHandled then** line in there. Thanks!

```
local procedure CheckOrderLine(PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; PhysInvtOrderLine: Record "Phys. Invt. Order Line"; var Item: Record Item)
var
    IsHandled: Boolean;
begin
    with PhysInvtOrderLine do begin
        CheckLine;
        Item.Get("Item No.");
        Item.TestField(Blocked, false);

        IsHandled := false;
        OnCheckOrderLineOnBeforeGetSamePhysInvtOrderLine(PhysInvtOrderHeader, PhysInvtOrderLine, PhysInvtOrderLine2, ErrorText, IsHandled);
        if not IsHandled then
            if PhysInvtOrderHeader.GetSamePhysInvtOrderLine(
                "Item No.", "Variant Code", "Location Code", "Bin Code", ErrorText, PhysInvtOrderLine2) > 1
            then
                Error(ErrorText);
    end;
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
