### ISSUE TITLE
Option Type of "Document Type" in Tables 900 and 901

### ISSUE THREAD

**Issue by Ayman-AYDI** [microsoft/ALAppExtensions#7879]
The "Document Type" field in tables 900 and 901 "Assembly Header" and "Assembly Line" has not a type Enum. It is always Option.
![2020-07-15_15h53_08](https://user-images.githubusercontent.com/64891337/87560930-e3b5a780-c6b3-11ea-834d-0c14cadd44a9.png)

**Comment by AlexanderYakunin** [comment]
We only implement enums in major versions, and this one already implemented.

**Comment by Ayman-AYDI** [comment]
When will the next major version be available?

**Comment by AlexanderYakunin** [comment]
October 2020

**Comment by lbuisson** [comment]
> 
> 
> October 2020

Dear Alexander
It is not possible to have this feature during or end of September?
Because we have NAV to BC customer migration which is blocked due to this limitation.
Thank you
Laurent
