### ISSUE TITLE
[Enum Request] table "Document Sending Profile" - Field E-Mail Attachment

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#7882]
Could you change the Field "E-Mail Attachment" to enum?

Some places where an event would be needed then:
 - procedure SendToEMail
 - procedure SendToEmailVendor

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
