### ISSUE TITLE
[Extensibility Request] table 1512 "Notification Setup", table 1513 "Notification Schedule" and table 1514 "Sent Notification Entry" Change Notification Type to Enum

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#7883]
Related to #7862 the Notification Type should be changed in tables 1512, 1513, 1514 too.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
