### ISSUE TITLE
[Function Change Request] COD 419 "File Management" - UploadFile() - Make ClientFileName passed by var

### ISSUE THREAD

**Issue by mtaanquist** [microsoft/ALAppExtensions#7884]
**Issue**
There is currently no way to get the client file name or path when working from a web client. In the normal NAV client, you could use `OpenFileDialog` to get the path of a file on the client system. 

The old function uses System.Windows.Forms components, which is not supported, so it correctly calls `UploadFile()` instead if you're using it from the web client, however, it no longer returns the client's file path now, but instead where it's uploaded to the server.

However, if you're sitting with an OnPrem installation, you may be storing files on a network share, in which case, you don't want to upload it to the service tier, but rather just let other users see where they can find the file.

**Proposed Solution**
Change the function signature of `UploadFile`, `UploadFileWithFilter`, and the application's `Upload` method, to have the parameter `ClientFileName` be passed by `var`.

New signature suggestions:
`procedure UploadFile(WindowTitle: Text[50], var ClientFileName: Text): Text`
`procedure UploadFileWithFilter(WindowTitle: Text[50], var ClientFileName: Text, FileFilter: Text, ExtFilter: Text): Text`
`procedure Upload(DialogTitle: Text, FromFolder: Text, FromFilter: Text, var FromFile: Text, var ToFile: Text): Boolean`

Please let me know if you require any additional information.

**Comment by GiorgosPa** [comment]
Hi @mtaanquist can't you use the platform functions Upload and UploadFromStream?

**Comment by mazhelez** [comment]
Hey @mtaanquist 

Do you think @GiorgosPa's suggestion will work for you case?

**Comment by mtaanquist** [comment]
Hi @mazhelez,

Thanks for the ping, and a happy New Year. It won't solve my problem, but I've also been made aware that it is an impossible problem to solve, so I'll close my issue.

Browsers don't have access to the filesystem of the OS they work with, and thus will never know the full path of the file you've uploaded to it. This is for security reasons. You'll never be able to open a browser dialog, point to a file on the host system, and then get that filepath in a browser.

Appreciate the eyes on this though.
