### ISSUE TITLE
Table 288 Vendor Bank Account - OnValidate "Use for Electronic Payments"

### ISSUE THREAD

**Issue by eclipses** [microsoft/ALAppExtensions#7888]
I need to override/handle the validation of this field.

`        field(10000; "Use for Electronic Payments"; Boolean)
        {
            Caption = 'Use for Electronic Payments';
            trigger OnValidate()
            var
                Vendor: Record Vendor;
                VendorBankAccount: Record "Vendor Bank Account";
            begin
                TestField(Code);
                TestField("Vendor No.");
                if "Use for Electronic Payments" then begin
                    VendorBankAccount.SetRange("Vendor No.", "Vendor No.");
                    VendorBankAccount.SetFilter(Code, '<>%1', Code);
                    VendorBankAccount.SetRange("Use for Electronic Payments", true);
                    if not VendorBankAccount.IsEmpty() then
                        Error(SingleUsageElectronicPaymentsErr,
                            VendorBankAccount.TableCaption, VendorBankAccount.FieldCaption("Use for Electronic Payments"),
                            Vendor.TableCaption, "Vendor No.");
                end;
            end;
        }
`

Related to #7867

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by eclipses** [comment]
```
trigger OnValidate()
  var
    Vendor: Record Vendor; 
    VendorBankAccount: Record "Vendor Bank Account";
    IsHandled: Boolean;
    begin
      IsHandled := false;
      OnValidateUseforElectronicPayments(Rec, xRec, IsHandled);
      if not IsHandled then begin
        TestField(Code); 
        TestField("Vendor No."); 
        if "Use for Electronic Payments" then begin 
          VendorBankAccount.SetRange("Vendor No.", "Vendor No."); 
          VendorBankAccount.SetFilter(Code, '<>%1', Code); 
          VendorBankAccount.SetRange("Use for Electronic Payments", true); 
          if not VendorBankAccount.IsEmpty() then 
            Error(SingleUsageElectronicPaymentsErr, VendorBankAccount.TableCaption, VendorBankAccount.FieldCaption("Use for Electronic Payments"), Vendor.TableCaption, "Vendor No.");
    end;
  end;
end;

**Signature** 
[IntegrationEvent(false, false)]
local procedure OnValidateUseforElectronicPayments(var VendorBankAccount: Record "Vendor Bank Account"; xVendorBankAccount: Record "Vendor Bank Account"; var IsHandled: Boolean)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
