### ISSUE TITLE
Extensions to handle new document as part of Order Tracking

### ISSUE THREAD

**Issue by Jackeoh** [Microsoft/ALAppExtensions#789]
We had a customer request & subsequent product that required we add a new document to BC. 
It is required that this document can be reserved to/from by other documents. In order to show the documents correctly in the 'Order Tracking' screen we had to make two modifications.

**CU99000778 OrderTrackingManagement**
Function 'DrillOrdersUp' has had the case statement extending to include a new event, so custom documents can be handled.
New 'Else' on case:
```
ELSE BEGIN
      OnDrillUp(Handled,ReservEntry3,ReservEntry2,SearchUp,ContiuneDrillUp,IncludePlanningFilter);
      IF ContiuneDrillUp THEN
        DrillOrdersUp(ReservEntry2,Level + 1);
      IF IncludePlanningFilter THEN
        IF DerivePlanningFilter(ReservEntry3,FilterReservEntry) THEN
          DrillOrdersUp(FilterReservEntry,Level + 1);
 END;
```

This allows for planning filters to be specified if required, and to stop the drill up if required.
Extension signature as follows:
` PROCEDURE OnDrillUp@1000000000(VAR Handled@1000000004 : Boolean;FromReservEntry@1000000000 : Record 337;VAR ToReservEntry@1000000001 : Record 337;VAR SearchUp@1000000002 : Boolean;VAR ContinueDrillUp@1000000003 : Boolean;VAR IncludePlanningFilter@1000000006 : Boolean);`

Function 'InsertTrackingEntry' extended for case statement to include new else
```
ELSE          
  OnInsertTrackingEntry(Handled,TrackingEntry,Type,ID,BatchName,Subtype,ProdOrderLineNo,RefNo);
```
This allows us to set relevant information (Starting/ending date as per standard documents)
function signature is : 
`OnInsertTrackingEntry@1000000001(VAR Handled@1000000007 : Boolean;VAR TrackingEntry@1000000006 : TEMPORARY Record 99000799;Type@1000000005 : Integer;ID@1000000004 : Code[20];BatchName@1000000003 : Code[20];Subtype@1000000002 : Integer;ProdOrderLineNo@1000000001 : Integer;RefNo@1000000000 : Integer);`

**Comment by JesperSchulz** [comment]
Again, please allow us to investigate and get back to you at a later time. Thanks!

**Comment by AlexanderYakunin** [comment]
Where do you use Handled parameter after return value from event? I don't see any use of it.

**Comment by Jackeoh** [comment]
I use it in the handler function, more as a precaution for two extensions trying to handle the same data type. I wouldn't say it was critical, as it would require multiple extensions to be trying to handle the same source, and would only occur on non-standard sources, so seems very unlikely.

![image](https://user-images.githubusercontent.com/43955934/52563952-b13ab780-2dfa-11e9-9cf5-c27e47ca408a.png)
