### ISSUE TITLE
Payment Journal - Bank\Export a file with the payment information on journal lines.

### ISSUE THREAD

**Issue by wakelek** [microsoft/ALAppExtensions#7891]
It is persisting Payment File Errors after they resolved. 

How to replicate:
1) create payment line with empty Document No. and Recipient Bank Account.
2) call Action from Bank\Export a file with the payment information on journal lines. It will create some validation errors in Payment File Errors
3) Fix validation errors and fill Document No.
4) call Action from Bank\Export a file with the payment information on journal lines. Error will persist

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
