### ISSUE TITLE
[Event Request] Codeunit 86 Sales-Quote to Order - OnBeforeModifySalesOrderHeader

### ISSUE THREAD

**Issue by elweilando** [Microsoft/ALAppExtensions#79]
At the position in Codeunit 86 "Sales-Quote to Order" is already an event named OnBeforeInsertSalesOrderHeader.
But this name for this event is wrong named. In context with https://github.com/Microsoft/ALAppExtensions/issues/77 there should be an OnBeforeModifySalesOrderHeader. And the OnBeforeInsertSalesOrderHeader at the right place.

It's completely confusing, if there is an event for OnBeforeInsert although the event fires OnBeforeModify

**Comment by AlexanderYakunin** [comment]
We cannot change it due to compatibility issue. In this case insert split into two parts, so this event works same way in any place before MODIFY.

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.

**Comment by pri-kise** [comment]
Maybe you should have mentioned that these event names did change and are now like requested:
See:
```
.....

SalesOrderLine.LockTable;
OnBeforeInsertSalesOrderHeader(SalesOrderHeader, SalesHeader);
SalesOrderHeader.Insert(true);

SalesOrderHeader."Order Date" := "Order Date";
if "Posting Date" <> 0D then
	SalesOrderHeader."Posting Date" := "Posting Date";

SalesOrderHeader.InitFromSalesHeader(SalesHeader);
SalesOrderHeader."Outbound Whse. Handling Time" := "Outbound Whse. Handling Time";
SalesOrderHeader.Reserve := Reserve;

SalesOrderHeader."Prepayment %" := PrepmtPercent;
if SalesOrderHeader."Posting Date" = 0D then
	SalesOrderHeader."Posting Date" := WorkDate;
OnBeforeModifySalesOrderHeader(SalesOrderHeader, SalesHeader);
SalesOrderHeader.Modify;
```

I accidently stumbled above this BREAKING Change.
