### ISSUE TITLE
Please add new event on Table 99000829 Planning Component

### ISSUE THREAD

**Issue by MSIngest** [microsoft/ALAppExtensions#7900]
Please we can add event to function FilterLinesWithItemToPlan on Table 99000829 Planning Component:

LOCAL PROCEDURE FilterLinesWithItemToPlan@70(VAR Item@1000 : Record 27);
    BEGIN
      RESET;
      SETCURRENTKEY("Item No.");
      SETRANGE("Item No.",Item."No.");
      SETFILTER("Variant Code",Item.GETFILTER("Variant Filter"));
      SETFILTER("Location Code",Item.GETFILTER("Location Filter"));
      SETFILTER("Due Date",Item.GETFILTER("Date Filter"));
      Item.COPYFILTER("Global Dimension 1 Filter","Shortcut Dimension 1 Code");
      Item.COPYFILTER("Global Dimension 2 Filter","Shortcut Dimension 2 Code");
      SETFILTER("Quantity (Base)",'<>0');

      OnAfterFilterLinesWithItemToPlan(Rec, Item);
    END;

    [Integration]
    LOCAL PROCEDURE OnAfterFilterLinesWithItemToPlan@1101340000(VAR PlanningComponent@1101340000 : Var Record 99000829;Item@1101340001 : Record 27);
    BEGIN
    END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
