### ISSUE TITLE
Please add new event on Codeunit 99000854 Inventory Profile Offsetting

### ISSUE THREAD

**Issue by MSIngest** [microsoft/ALAppExtensions#7901]
Please we can add event to function TransProdOrderCompToProfile on codeunit 99000854 Inventory Profile Offsetting:

LOCAL PROCEDURE TransProdOrderCompToProfile@70(VAR InventoryProfile@1001 : Record 99000853;VAR Item@1000 : Record 27);
    VAR
      ProdOrderComp@1004 : Record 5407;
      IsHandled@1101340000 : Boolean;
    BEGIN
      OnBeforeTransProdOrderCompToProfile(InventoryProfile, Item, IsHandled);
      IF IsHandled THEN
        EXIT;

      IF ProdOrderComp.FindLinesWithItemToPlan(Item,TRUE) THEN
        REPEAT
          IF ProdOrderComp."Due Date" <> 0D THEN BEGIN
            ReqLine.SetRefFilter(
              ReqLine."Ref. Order Type"::"Prod. Order",ProdOrderComp.Status,
              ProdOrderComp."Prod. Order No.",ProdOrderComp."Prod. Order Line No.");
            ReqLine.SETRANGE("Operation No.",'');
            IF NOT ReqLine.FINDFIRST THEN BEGIN
              InventoryProfile.INIT;
              InventoryProfile."Line No." := NextLineNo;
              InventoryProfile.TransferFromComponent(ProdOrderComp,TempItemTrkgEntry);
              IF InventoryProfile.IsSupply THEN
                InventoryProfile.ChangeSign;
              InventoryProfile.INSERT;
            END;
          END;
        UNTIL ProdOrderComp.NEXT = 0;
    END;

    [Integration]
    LOCAL PROCEDURE OnBeforeTransProdOrderCompToProfile@1101340000(VAR InventoryProfile@1101340000 : Record 99000853;VAR Item@1101340001 : Record 27;VAR IsHandled@1101340002 : Boolean);
    BEGIN
    END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
