### ISSUE TITLE
Please add new events on Table 5407 Prod. Order Component

### ISSUE THREAD

**Issue by MSIngest** [microsoft/ALAppExtensions#7902]
Please we can add event to function  FilterLinesWithItemToPlan on Table 5407 Prod. Order Component :

[External]
    PROCEDURE FilterLinesWithItemToPlan@70(VAR Item@1000 : Record 27;IncludeFirmPlanned@1001 : Boolean);
    BEGIN
      RESET;
      SETCURRENTKEY("Item No.","Variant Code","Location Code",Status,"Due Date");
      SETRANGE("Item No.",Item."No.");
      SETFILTER("Variant Code",Item.GETFILTER("Variant Filter"));
      SETFILTER("Location Code",Item.GETFILTER("Location Filter"));
      SETFILTER("Due Date",Item.GETFILTER("Date Filter"));
      SETFILTER("Shortcut Dimension 1 Code",Item.GETFILTER("Global Dimension 1 Filter"));
      SETFILTER("Shortcut Dimension 2 Code",Item.GETFILTER("Global Dimension 2 Filter"));
      SETFILTER("Remaining Qty. (Base)",'<>0');

      OnAfterFilterLinesWithItemToPlan(Rec,Item,IncludeFirmPlanned);
    END;

    [Integration]
    LOCAL PROCEDURE OnAfterFilterLinesWithItemToPlan@1101340000(VAR ProdOrderComponent@1101340000 : Record 5407;VAR Item@1101340001 : Record 27;IncludeFirmplanned@1101340002 : Boolean);
    BEGIN
    END;

Best Regards
Monica

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
