### ISSUE TITLE
Reminder - #5831 - Codeunit 950 "Time Sheet Management" - OnBeforeCopyTimeSheet

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#7905]
Regarding #5831 from January 2020, there is nothing to see in Insider Build 17.0.14751.0-W1.
Status since 07. Feb is "ships-in-future-update".
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
