### ISSUE TITLE
Phys inventory journal: Items without inventory or transactions not all variants are shown

### ISSUE THREAD

**Issue by Maranca** [microsoft/ALAppExtensions#7908]
7538 The Phys inventory journal is not working correct.
I calculate the inventory with the following field enabled:
items not on inventory 
Include item without transactions

For these items not all variants are shown. Even though you enable include item without transactions it does not show it for variants that have no transactions.

See attachement for more explanation:
[Phys inventory journal not all variants are shown.docx](https://github.com/microsoft/ALAppExtensions/files/4947108/Phys.inventory.journal.not.all.variants.are.shown.docx)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by Maranca** [comment]
thank you for the options but it was for the business central 16 version and on none of the links there was an option to log a product bug for business central.

**Comment by StanPesotskiy** [comment]
Version 16 has been shipped in April'20. Our support team accepts requests for version 16 as well for other older supported versions. If you represent an MS partner you should be able to create a hotfix request for version 16.

**Comment by Maranca** [comment]
we are a ms partner but have not the link to create a hotfix request for version 16. With the links you send me I could not find it. and here I can not enter it when I do not have code suggestions
