### ISSUE TITLE
[Extensibility Request/Bug] table 7316 "Warehouse Receipt Header" -OnSortWhseDocOnCaseSortingMethodElse

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#7909]
The event `OnSortWhseDocOnCaseSortingMethodElse` do miss mandatory variables for setting a sorting to the `WhseRcptLine`.
Could please update the event signature to include the `WhseRcptLine`
```al
[IntegrationEvent(false, false)]
local procedure OnSortWhseDocOnCaseSortingMethodElse(var WarehouseReceiptHeader: Record "Warehouse Receipt Header"; var WhseRcptLine: Record "Warehouse Receipt Line")
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
