### ISSUE TITLE
[Event Request] Codeunit::"Catalog Item Management" - Function CreateItemFromNonstock - OnBeforeCreateItemFromNonstock

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7911]
We like to request the following Event:
Object: Codeunit::"Catalog Item Management"
Function: CreateItemFromNonstock
Publisher Event: OnBeforeCreateItemFromNonstock
Reason: To implement custom business logic
Where is the event placed:
procedure CreateItemFromNonstock(Nonstock2: Record "Nonstock Item")
    begin
        **OnBeforeCreateItemFromNonstock(Nonstock2);**
        if NewItem.Get(Nonstock2."Item No.") then
            Error(Text000, Nonstock2."Item No.");
        Nonstock2."Item No." :=
          GetNewItemNo(
            Nonstock2, StrLen(Nonstock2."Vendor Item No."), StrLen(Nonstock2."Manufacturer Code"));

Event Code:
[IntegrationEvent(false, false)]
    procedure OnBeforeCreateItemFromNonstock(var NonstockItem: Record "Nonstock Item")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
