### ISSUE TITLE
[Event Request] Codeunit::"Catalog Item Management" - Function GetNewItemNo - OnBeforeGetNewItemNo

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7912]
We like to request the following Event:
Object: Codeunit::"Catalog Item Management"
Function: GetNewItemNo
Publisher Event: OnBeforeGetNewItemNo
Reason: To implement custom business logic
Where is the event placed:
local procedure GetNewItemNo(NonstockItem: Record "Nonstock Item"; Length1: Integer; Length2: Integer) NewItemNo: Code[20]
    var
        NonstockItemSetupMy: Record "Nonstock Item Setup";
        IsHandled: Boolean;
    begin
        **OnBeforeGetNewItemNo(NonstockItem, Length1, Length2, NewItemNo, IsHandled);
        if IsHandled then
            exit(NewItemNo);**
        NonstockItemSetupMy.Get();
        case NonstockItemSetupMy."No. Format" of

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetNewItemNo(NonstockItem: Record "Nonstock Item"; Length1: Integer; Length2: Integer; var NewItemNo: Code[20]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
