### ISSUE TITLE
[Event Request] Codeunit::"Catalog Item Management" - Function NonStockSales - OnBeforeNonStockSales

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7913]
We like to request the following Event:
Object: Codeunit::"Catalog Item Management"
Function: NonStockSales
Publisher Event: OnBeforeNonStockSales
Reason: To implement custom business logic
Where is the event placed:
procedure NonStockSales(var SalesLine2: Record "Sales Line")
    var
        IsHandled: Boolean;
    begin
        **OnBeforeNonStockSales(NonStock, SalesLine2, IsHandled);
        If IsHandled then
            exit;**
        if (SalesLine2."Document Type" in
            [SalesLine2."Document Type"::"Return Order", SalesLine2."Document Type"::"Credit Memo"])
        then
            Error(Text002, SalesLine2."Document Type");
        NonStock.Get(SalesLine2."No.");
        if NonStock."Item No." <> '' then begin
            SalesLine2."No." := NonStock."Item No.";
            exit;
        end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeNonStockSales(var NonStockItem: Record "Nonstock Item"; var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
