### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function CopyPurchHeaderFromPostedCreditMemo - OnAfterCopyPostedPurchCreditMemo

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7914]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: CopyPurchHeaderFromPostedCreditMemo
Publisher Event: OnAfterCopyPostedPurchCreditMemo
Reason: To implement custom business logic
Where is the event placed:
local procedure CopyPurchHeaderFromPostedCreditMemo(FromPurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; var ToPurchHeader: Record "Purchase Header")
    begin
        ToPurchHeader.Validate("Buy-from Vendor No.", FromPurchCrMemoHeader."Buy-from Vendor No.");
        ToPurchHeader.TransferFields(FromPurchCrMemoHeader, false);
        **OnAfterCopyPostedPurchCreditMemo(ToPurchHeader, FromPurchCrMemoHeader);**
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterCopyPostedPurchCreditMemo(var ToPurchaseHeader: Record "Purchase Header"; FromPurchCrMemoHeader: Record "Purch. Cr. Memo Hdr.")
    begin
    end;

**Comment by StanPesotskiy** [comment]
Duplicate to  https://github.com/microsoft/ALAppExtensions/issues/7175
