### ISSUE TITLE
[Event Request] Codeunit::"Correct Posted Purch. Invoice" - Function UnapplyCostApplication - OnBeforeUnAppyCostApplication

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7915]
We like to request the following Event:
Object: Codeunit::"Correct Posted Purch. Invoice"
Function: UnapplyCostApplication
Publisher Event: OnBeforeUnAppyCostApplication
Reason: To implement custom business logic
Where is the event placed:
local procedure UnapplyCostApplication(var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; InvNo: Code[20]): Boolean
    var
        TempItemLedgEntry: Record "Item Ledger Entry" temporary;
        TempItemApplicationEntry: Record "Item Application Entry" temporary;
        IsHandled: Boolean;
    begin
        **IsHandled := false;
        OnBeforeUnAppyCostApplication(InvNo, IsHandled);
        if IsHandled then
            exit(false);**
        FindItemLedgEntries(TempItemLedgEntry, InvNo);
        if FindAppliedInbndEntries(TempItemApplicationEntry, TempItemLedgEntry) then begin
            repeat
                ItemJnlPostLine.UnApply(TempItemApplicationEntry);
            until TempItemApplicationEntry.Next = 0;
            exit(true);
        end;
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUnAppyCostApplication(InvNo: Code[20]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
