### ISSUE TITLE
[Event Request] Codeunit::"Cust-Check Cr. Limit" - Function SalesLineCheck - OnBeforeSalesSalesLineCheck

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#7916]
We like to request the following Event:
Object: Codeunit::"Cust-Check Cr. Limit"
Function: SalesLineCheck
Publisher Event: OnBeforeSalesSalesLineCheck
Reason: To implement custom business logic
Where is the event placed:
procedure SalesLineCheck(SalesLine: Record "Sales Line")
    var
        SalesHeader: Record "Sales Header";
        AdditionalContextId: Guid;
        IsHandled: Boolean;
    begin
        **IsHandled := false;
        OnBeforeSalesSalesLineCheck(SalesLine, IsHandled);
        if IsHandled then
            exit;**
        if not SalesHeader.Get(SalesLine."Document Type", SalesLine."Document No.") then
            SalesHeader.Init();

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSalesSalesLineCheck(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
