### ISSUE TITLE
[Event Request] T37 Sales Line OnBeforeIsCreditDocType

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#7918]
Hello,
In Sales Header it is possible to specify custom document types as credit in OnBeforeIsCreditDocType, would it be possible to add same event in IsCredtiDocType on Sales Line?
Thanks,
Bartek

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
