### ISSUE TITLE
Conversion to Enum to allow for specifying custom document types in Item posting

### ISSUE THREAD

**Issue by Jackeoh** [microsoft/ALAppExtensions#792]
We had a customer request & subsequent product that required we add a new document to BC. 
In order to record this document type on the ILE when the document posts a change to inventory, it is required that the 'Document Type' on both the Item ledger Entry & Item Journal tables be converted to an enum.

The tables fields that need to be an enum are:
***Table 32 'Item Ledger Entry' - Field 79 'Document Type'
Table 83 'Item Journal Line' -  Field 79 'Document Type'***

**Comment by Jackeoh** [comment]
This should also be applied to the same field on value entries - a small oversight of mine to not include it in the first place

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
