### ISSUE TITLE
Serv-Documents Mgt. - OnAfterFinalizeInvoiceDocument

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/ALAppExtensions#7920]
Hi,
The event OnAfterFinalizeInvoiceDocument in the codeunit Serv-Documents Mgt. is missing the parameter for the Service Header. 

Now:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterFinalizeInvoiceDocument(var ServiceInvoiceHeader: Record "Service Invoice Header")
    begin
    end;
```

Request:
```
    [IntegrationEvent(false, false)]
     local procedure OnAfterFinalizeInvoiceDocument(var ServiceInvoiceHeader: Record "Service Invoice Header"; ServiceHeader: record "Service Header")
    begin
    end;

```
Is it possible? 

Version: W1 16.2 (Platform 16.0.13440.13772 + Application 16.2.13509.13779)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
