### ISSUE TITLE
[New Event] Table 39, Purchase Line, OnValidateQuantityOnBeforePurchaseLineVerifyChange

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7931]
[New Event], Table 39, Purchase Line, OnValidateQuantityOnBeforePurchaseLineVerifyChange

A new event implementing the handled pattern is needed in the trigger Quantity-OnValidate before WhseValidateSourceLine.PurchaseLineVerifyChange is called. This is in analogy to the Sales Line where the same integration event already exists.

                UpdateWithWarehouseReceive;
                if (xRec.Quantity <> Quantity) or (xRec."Quantity (Base)" <> "Quantity (Base)") then begin
                    OnBeforeVerifyReservedQty(Rec, xRec, FieldNo(Quantity));
                    ReservePurchLine.VerifyQuantity(Rec, xRec);
                    IsHandled := false;
                    OnValidateQuantityOnBeforePurchaseLineVerifyChange(Rec, StatusCheckSuspended, IsHandled);
                    if not IsHandled then
                        WhseValidateSourceLine.PurchaseLineVerifyChange(Rec, xRec);
                    CheckApplToItemLedgEntry;
                end;

![image](https://user-images.githubusercontent.com/22153733/88079622-45778500-cb7e-11ea-9cb2-dd400aefecf6.png)

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnBeforePurchaseLineVerifyChange(var PurchaseLine: Record "Purchase Line"; StatusCheckSuspended: Boolean; var IsHandled: Boolean);
    begin
    end;    

**Integration Event:**
OnValidateQuantityOnBeforePurchaseLineVerifyChange
**Signature:**
var PurchaseLine: Record "Purchase Line"
StatusCheckSuspended: Boolean
var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
