### ISSUE TITLE
[New Parameter for Event] Page 99000882, Change Status on Prod. Order, OnAfterSet

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7932]
[New Parameter for Event] Page 99000882, Change Status on Prod. Order, OnAfterSet

Integration Event OnAfterSet in procedure Set of page "Change Status on Prod. Order" needs a new parameter:

    procedure Set(ProdOrder: Record "Production Order")
    begin
        if ProdOrder.Status = ProdOrder.Status::Finished then
            ProdOrder.FieldError(Status);

        FirmPlannedStatusEditable := ProdOrder.Status < ProdOrder.Status::"Firm Planned";
        ReleasedStatusEditable := ProdOrder.Status <> ProdOrder.Status::Released;
        FinishedStatusEditable := ProdOrder.Status = ProdOrder.Status::Released;
        if ProdOrder.Status > ProdOrder.Status::Simulated then
            ProdOrderStatus.Status := ProdOrder.Status + 1
        else
            ProdOrderStatus.Status := ProdOrderStatus.Status::"Firm Planned";

        PostingDate := WorkDate;

        OnAfterSet(ProdOrder);
    end;

![image](https://user-images.githubusercontent.com/22153733/88081313-7f498b00-cb80-11ea-837c-bc67b42852e5.png)

    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterSet(ProdOrder: Record "Production Order")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
