### ISSUE TITLE
[Event Request] Codeunit 427, ICInboxOutboxMgt, OnForwardToOutBoxOnBeforeHndlInboxPurchLineInsert

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7935]
[Event Request] Codeunit 427, ICInboxOutboxMgt, OnForwardToOutBoxOnBeforeHndlInboxPurchLineInsert

New event in procedure OnForwardToOutbox

                                    HndlInboxPurchLine.TransferFields(InboxPurchLine);
                                    OnForwardToOutBoxOnBeforeHndlInboxPurchLineInsert(HndlInboxPurchLine, InboxPurchLine);
                                    HndlInboxPurchLine.Insert();

![image](https://user-images.githubusercontent.com/22153733/88093403-44e8e980-cb92-11ea-8beb-d2f351e0f1aa.png)

    [IntegrationEvent(false, false)]
    local procedure OnForwardToOutBoxOnBeforeHndlInboxPurchLineInsert(var HandledICInboxPurchLine: Record "Handled IC Inbox Purch. Line"; ICInboxPurchLine: Record "IC Inbox Purchase Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
