### ISSUE TITLE
[Event Request] Codeunit 427, ICInboxOutboxMgt, OnRecreateOutboxTransactionOnBeforeOutboxSalesLineInsert

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#7936]
[Event Request] Codeunit 427, ICInboxOutboxMgt, OnRecreateOutboxTransactionOnBeforeOutboxSalesLineInsert

New event in procedure RecreateOutboxTransaction:

                            if HandledOutboxSalesLine.Find('-') then
                                repeat
                                    OutboxSalesLine.TransferFields(HandledOutboxSalesLine);
                                    OnRecreateOutboxTransactionOnBeforeOutboxSalesLineInsert(OutboxSalesLine, HandledOutboxSalesLine);
                                    OutboxSalesLine.Insert();
                                    ICDocDim.Reset();

![image](https://user-images.githubusercontent.com/22153733/88093953-0b64ae00-cb93-11ea-8bad-139ffb17487e.png)

    [IntegrationEvent(false, false)]
    local procedure OnRecreateOutboxTransactionOnBeforeOutboxSalesLineInsert(var ICOutboxSalesLine: Record "IC Outbox Sales Line"; HandledICOutboxSalesLine: Record "Handled IC Outbox Sales Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
