### ISSUE TITLE
Void Check from Check Ledger Entry reverts entry without copy all the fields 

### ISSUE THREAD

**Issue by eclipses** [microsoft/ALAppExtensions#7939]
Standard BC when reverts a Vendor Ledger Entry creates a new line with the same fields, including custom fields.

I've noted that when you Void a Check from Check Ledger Entry, it has a different behavior, I tried, for example, changing the Posting Group for a Vendor adding the standard field in a Journal but when Void the Check it uses the Posting Group from the Vendor Card and not the one of the original transaction, same for document type and custom fields that are left blank.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
