### ISSUE TITLE
Event Request: Report 295 “Combine Shipments”, named OnAfterGetRecordSalesShipmentLine

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#7940]
We need a new Event Function in Report 295 “Combine Shipments”, named OnAfterGetRecordSalesShipmentLine. 
We need this

Sales Shipment Line - OnAfterGetRecord()
IF Type = 0 THEN BEGIN
  IF (NOT CopyTextLines) OR ("Attached to Line No." <> 0) THEN
    CurrReport.SKIP;
END;

IF "Authorized for Credit Card" THEN
  CurrReport.SKIP;

OnAfterGetRecordSalesShipmentLine(“Sales shipment line”,IsHandled);
IF IsHandled THEN 
  CurrReport.SKIP;

The event will be:

LOCAL [IntegrationEvent] OnAfterGetRecordSalesShipmentLine(VAR SalesShipmentLine : Record "Sales Shipment Line";VAR IsHandled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
