### ISSUE TITLE
[Event Request] Table 18 - "Customer" OnBeforeUpdateCustomerBankAccounts

### ISSUE THREAD

**Issue by DOuderling** [microsoft/ALAppExtensions#7941]
Hello,

We want to use our own logic for function UpdateCustomerBankAccounts in Customer table:

CURRENT CODE:

    local procedure UpdateCustomerBankAccounts(UseFieldCaption: Text[250])
    begin
        if not GuiAllowed then
            exit;
        CustBankAcc.SetRange("Customer No.", "No.");
        if CustBankAcc.Find('-') then begin
            if not Confirm(StrSubstNo(Text11000000, UseFieldCaption)) then
                exit;
            repeat
                CustBankAcc."Account Holder Name" := Name;
                CustBankAcc."Account Holder Address" := Address;
                CustBankAcc."Account Holder Post Code" := "Post Code";
                CustBankAcc."Account Holder City" := City;
                CustBankAcc."Acc. Hold. Country/Region Code" := "Country/Region Code";
                CustBankAcc.Modify();
            until CustBankAcc.Next = 0;
            Modify;
        end;
    end;

NEW CODE:

    local procedure UpdateCustomerBankAccounts(UseFieldCaption: Text[250])
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateCustomerBankAccounts(Rec,IsHandled);
        if (not GuiAllowed) OR IsHandled then
            exit;
        CustBankAcc.SetRange("Customer No.", "No.");
        if CustBankAcc.Find('-') then begin
            if not Confirm(StrSubstNo(Text11000000, UseFieldCaption)) then
                exit;
            repeat
                CustBankAcc."Account Holder Name" := Name;
                CustBankAcc."Account Holder Address" := Address;
                CustBankAcc."Account Holder Post Code" := "Post Code";
                CustBankAcc."Account Holder City" := City;
                CustBankAcc."Acc. Hold. Country/Region Code" := "Country/Region Code";
                CustBankAcc.Modify();
            until CustBankAcc.Next = 0;
            Modify;
        end;
    end;

NEW EVENT PUBLISHER:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateCustomerBankAccounts(var Customer : Record Customer; var IsHandled : Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by DOuderling** [comment]
Hi, 

Thanks for adding this, I see this is added in BC17. Great!

However, one question:

I asked for this change to be added in the Vendor table as well, and it has been.
However, it has been implemented differently. Customer table uses Rec as Parameter, Vendor table uses Sender.
Is there a reason for the two different implementations?

![image](https://user-images.githubusercontent.com/68635052/100212522-baccdb00-2f0d-11eb-8283-36ef2e6f4579.png)

No big deal, since both work, just interested.
