### ISSUE TITLE
[Event Request] Codeunit 5624 Function TransferLine

### ISSUE THREAD

**Issue by bstanienda** [microsoft/ALAppExtensions#7942]
Hello Team, we need a new handled publisher in codeunit 5624 function TransferLine:

Old Code:
      END;
      IF GLIntegration[ConvertPostingType + 1] AND NOT FA."Budgeted Asset" THEN
        InsertGenJnlLine(FALedgEntry,BalAccount)
      ELSE
        InsertFAJnlLine(FALedgEntry);

New Code:
      END;
      Handled := false;
      OnBeforeInsertJnlLine(FALedgEntry,BalAccount,FA."Budgeted Asset",VAR Handled);
      IF NOT Handled THEN
        IF GLIntegration[ConvertPostingType + 1] AND NOT FA."Budgeted Asset" THEN
          InsertGenJnlLine(FALedgEntry,BalAccount)
        ELSE
          InsertFAJnlLine(FALedgEntry);

[IntegrationEvent(false, false)]        IncludeSender=No
local procedure  OnBeforeInsertJnlLine(FALedgerEntry: Record "FA Ledger Entry"; BalAccount: Boolean; FABudgetedAsset: Boolean; var IsHandled: Boolean)
begin
end;
     
The functions "InsertGenJnlLine" and "InsertFAJnlLine" must be External functions.

Thank you!

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation. 

Also I don't get why do you need TmpConvertPostingType.

**Comment by bstanienda** [comment]
Dear Stan, you are right, I don't need the variable TmpComvertPostingType, because I can call the function "ConvertPostingType" in my publisher. So I changed the requested code.
What do you mean with the "full detailed signature of the requested events"? Do you mean the full code of the function? I thought this could be more confusing than the short part I requested for change. Sorry I have not so much practical knowledge with github.

**Comment by StanPesotskiy** [comment]
The signature is the list of parameters with all properties like **var** and type name on the parameters and **IncludeSender** on the method.

**Comment by bstanienda** [comment]
Dear Stan, now I added the full signature of the requested event and hopefully it is ok.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
