### ISSUE TITLE
[Event Request] Table 21 Cust. Ledger Entry - SetStyle

### ISSUE THREAD

**Issue by DOuderling** [microsoft/ALAppExtensions#7944]
We want to apply a different implementation of the styles in the Customer Ledger Entries page(s).
Therefore we want to request the following Event Request.

CURRENT CODE:

    procedure SetStyle(): Text
    begin
        if Open then begin
            if WorkDate > "Due Date" then
                exit('Unfavorable')
        end else
            if "Closed at Date" > "Due Date" then
                exit('Attention');
        exit('');
    end;

NEW CODE:

    procedure SetStyle(): Text
    var
    IsHandled: Boolean;
    Style: Text;
    begin
        OnBeforeSetStyle(Rec,Style,IsHandled);
        if IsHandled Then
            exit(Style);

        if Open then begin
            if WorkDate > "Due Date" then
                exit('Unfavorable')
        end else
            if "Closed at Date" > "Due Date" then
                exit('Attention');
        exit('');
    end;

NEW EVENT PUBLISHER:

        [IntegrationEvent(false, false)]
        local procedure OnBeforeSetStyle(var CustLedgEntry: record "Cust. Ledger Entry"; var Style : Text; var IsHandled : Boolean)
        begin
        end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
