### ISSUE TITLE
[Request for External] Codeunit 7301 "Whse. Jnl.-Register Line" - Get and Set WhseEntryNo

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/ALAppExtensions#7946]
Please add these procedures to **Get** and **Set** the global variable **WhseEntryNo** in Codeunit 7301 "Whse. Jnl.-Register Line".

Suggestion:
```
procedure SetWhseEntryNo(NewWhseEntryNo: Integer)
begin
    WhseEntryNo := NewWhseEntryNo;
end;

procedure GetWhseEntryNo() : Integer
begin
    exit(WhseEntryNo);
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
