### ISSUE TITLE
New procedures needed in Codeunit 730 "Copy Item"

### ISSUE THREAD

**Issue by SSZurmussen7112** [microsoft/ALAppExtensions#7947]
Hi Team,
The new Copy Item function with page 729 and codeunit 730 are pretty cool and easy to increase with own tables. But I need the possibility to copy an item out from own al-code and in my opinion two global procedures are missing in the codeunit 730:

```
    // First function to fill in all needed information to the CopyItemBuffer
    procedure SetCopyItemBuffer(var NewCopyItemBuffer: Record "Copy Item Buffer" temporary)
    begin
        CopyItemBuffer := NewCopyItemBuffer;
        SourceItem.Get(CopyItemBuffer."Source Item No.");
    end;

    // Second function to get the item numbers of the created items out from the codeunit, after the procedure CopyItem() was called
    procedure GetNewItemNo(var NewFirstItemNo: Code[20]; var NewLastItemNo: Code[20])
    begin
        NewFirstItemNo := FirstItemNo;
        NewLastItemNo := LastItemNo;
    end;

```
Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
