### ISSUE TITLE
Error on Cancel FA Ledg. Entries with type Proceeds on Disposal

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/ALAppExtensions#7948]
Hello
In 16.3 in codeunit 5600 "FA Insert Ledger Entry", function InsertFA is added a new code:

        if FALedgEntry."FA Posting Type" = FALedgEntry."FA Posting Type"::"Proceeds on Disposal" then begin
            TempFALedgerEntryReverse := FALedgEntry;
            TempFALedgerEntryReverse.Insert();
            ReverseFALedgerEntryAmounts(FALedgEntry);
        end;

this code cause an error when trying to cancel entries with FA Posting Type = Proceeds on Disposal:

Error: "FA Error Entry No. = 89 does not match the journal line for Fixed Asset No. = FA000010 in Depreciation Book Code = COMPANY"

The reason is in next code:

        if ErrorEntryNo > 0 then begin
            if not FALedgEntry2.Get(ErrorEntryNo) then
                Error(
                  Text000,
                  FAName(DeprBookCode), FALedgEntry2.FieldCaption("Entry No."), ErrorEntryNo);
            if (FALedgEntry2."Depreciation Book Code" <> FALedgEntry."Depreciation Book Code") or
               (FALedgEntry2."FA No." <> FALedgEntry."FA No.") or
               (FALedgEntry2."FA Posting Category" <> FALedgEntry."FA Posting Category") or
               (FALedgEntry2."FA Posting Type" <> FALedgEntry."FA Posting Type") or
               (FALedgEntry2.Amount <> -FALedgEntry.Amount) or
               (FALedgEntry2."FA Posting Date" <> FALedgEntry."FA Posting Date")
            then
                Error(
                  Text001,
                  FAName(DeprBookCode), FAJnlLine.FieldCaption("FA Error Entry No."), ErrorEntryNo);

The problem is that in the new code (shown in the beginnig) the Amount of the FALedgEntry was reversed and has same sign with FALedgEntry2.Amount (the entry that we want to cancel), so it not pass the check.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
