### ISSUE TITLE
[Event Request] COD13 - OnBeforeGenJnlTemplateINC

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#7949]
Hello,

we Need the following event in procedure UpdateAndDeleteLines.

![image](https://user-images.githubusercontent.com/45033081/88174078-ecfac300-cc23-11ea-8b0f-0a003fd1c279.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
