### ISSUE TITLE
[Event Request] table 1226 "Payment Export Data" - OnAfterSetEmployeeAsRecipient

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#7953]
https://github.com/microsoft/ALAppExtensions/issues/5988 added an event for Customers.

https://github.com/microsoft/ALAppExtensions/issues/7443 added one for Vendors.

Please add an equivalent `OnAfterSetEmployeeAsRecipient(var PaymentExportData, Employee)` to enable extending what gets copied from Employee to Payment Export Data.

Note that the Cust/Vend versions take the source records by `var`, but I can't see why that would be useful/legitimate, so I don't request it, unless there's a reason I should change my mind.

![image](https://user-images.githubusercontent.com/63455896/88180438-4b747100-cc25-11ea-9cb2-69cb164753d8.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by AldisB** [comment]
I'm also looking forward for this update...
