### ISSUE TITLE
[Event Request] table 1226 "Payment Export Data" - OnAfterSetBankAsSenderBank

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#7954]
Please add an event publisher `OnAfterSetBankAsSenderBank(var PaymentExportData, BankAccount)` to enable extending what gets copied from the Bank Account to the Payment Export Data.

Note that the Cust/Vend versions take the source records by `var`, but I can't see why that would be useful/legitimate, so I don't request it, unless there's a reason I should change my mind.

![image](https://user-images.githubusercontent.com/63455896/88180726-b9b93380-cc25-11ea-97b4-ddf56c58898d.png)

(This was also requested here but of course ignored because evidently an issue per event is insisted upon: https://github.com/microsoft/ALAppExtensions/issues/5988#issuecomment-645008471 )

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
If you use AL code copied from VSCode instead of screenshots it will speed up the process of implementation.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
