### ISSUE TITLE
[Event Request] Codeunit 5626 Function CalcGLPostedAmount

### ISSUE THREAD

**Issue by bstanienda** [microsoft/ALAppExtensions#7960]
Hello Team, we need a new handled publisher in codeunit 5626 function CalcGLPostedAmount:

Old Code:
            case PostingType of
                FADeprBook.FieldNo("Acquisition Cost"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Acquisition Cost");
                FADeprBook.FieldNo(Depreciation):
                    SetRange("FA Posting Type", "FA Posting Type"::Depreciation);
                FADeprBook.FieldNo("Write-Down"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Write-Down");
                FADeprBook.FieldNo(Appreciation):
                    SetRange("FA Posting Type", "FA Posting Type"::Appreciation);
                FADeprBook.FieldNo("Custom 1"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Custom 1");
                FADeprBook.FieldNo("Custom 2"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Custom 2");
                FADeprBook.FieldNo("Proceeds on Disposal"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Proceeds on Disposal");
                FADeprBook.FieldNo("Gain/Loss"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Gain/Loss");
                FADeprBook.FieldNo("Book Value on Disposal"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Book Value on Disposal");
            end;
            CalcSums(Amount);

New Code:
            case PostingType of
                FADeprBook.FieldNo("Acquisition Cost"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Acquisition Cost");
                FADeprBook.FieldNo(Depreciation):
                    SetRange("FA Posting Type", "FA Posting Type"::Depreciation);
                FADeprBook.FieldNo("Write-Down"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Write-Down");
                FADeprBook.FieldNo(Appreciation):
                    SetRange("FA Posting Type", "FA Posting Type"::Appreciation);
                FADeprBook.FieldNo("Custom 1"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Custom 1");
                FADeprBook.FieldNo("Custom 2"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Custom 2");
                FADeprBook.FieldNo("Proceeds on Disposal"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Proceeds on Disposal");
                FADeprBook.FieldNo("Gain/Loss"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Gain/Loss");
                FADeprBook.FieldNo("Book Value on Disposal"):
                    SetRange("FA Posting Type", "FA Posting Type"::"Book Value on Disposal");
            end;
            OnBeforeCalcGLPostedAmount(FALedgEntry, PostingType);
            CalcSums(Amount);

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
