### ISSUE TITLE
[Code Change Request] Codeunit 5601 Function GetPostingType

### ISSUE THREAD

**Issue by bstanienda** [microsoft/ALAppExtensions#7962]
Hello Team,

we need a Code Change in Codeunit 5601 Function GetPostingType.

Old Code:
        with FALedgEntry do begin
            if "FA Posting Type" >= "FA Posting Type"::"Gain/Loss" then begin
                if "FA Posting Type" = "FA Posting Type"::"Gain/Loss" then begin
                    if "Result on Disposal" = "Result on Disposal"::Gain then
                        exit(FAPostingType::Gain);

                    exit(FAPostingType::Loss);
                end;
                if "FA Posting Type" = "FA Posting Type"::"Book Value on Disposal" then begin
                    if "Result on Disposal" = "Result on Disposal"::Gain then
                        exit(FAPostingType::"Book Value Gain");

                    exit(FAPostingType::"Book Value Loss");
                end;
            end else
                exit(ConvertPostingType);
        end;

New Code:
        with FALedgEntry do begin
            case "FA Posting Type" of
              FA Posting Type"::"Gain/Loss":
              begin
                if "FA Posting Type" = "FA Posting Type"::"Gain/Loss" then begin
                    if "Result on Disposal" = "Result on Disposal"::Gain then
                        exit(FAPostingType::Gain);

                    exit(FAPostingType::Loss);
                end;
              end;
              "FA Posting Type"::"Book Value on Disposal":
              begin
                if "Result on Disposal" = "Result on Disposal"::Gain then
                  exit(FAPostingType::"Book Value Gain");

                exit(FAPostingType::"Book Value Loss");
              end;
            end else
                exit(ConvertPostingType);

Thank you!

**Comment by bstanienda** [comment]
So you mean the changing of the code from IF to CASE is already done in the CU03? I'm using BC16 CU01.

**Comment by AlexanderYakunin** [comment]
Can you describe what and why you want to change? How it will help you in extensibility, if you will not have options to change our code? 

Also I can see that you removed this statement: 

if "FA Posting Type" >= "FA Posting Type"::"Gain/Loss" then begin. Why?

**Comment by bstanienda** [comment]
Dear Alexander, 
in our solution we expanded the field "FA Posting Type" and the new options are greater than the option "Gain/Loss". The old code in our solution was: 

WITH FALedgEntry DO BEGIN
  // Our Code BEGIN
  IF "FA Posting Type" >= "FA Posting Type"::"ABGT HK" THEN
       EXIT(ConvertPostingType);
  // Our Code END
  IF "FA Posting Type" >= "FA Posting Type"::"Gain/Loss" THEN BEGIN
    IF "FA Posting Type" = "FA Posting Type"::"Gain/Loss" THEN BEGIN
      IF "Result on Disposal" = "Result on Disposal"::Gain THEN
        EXIT(FAPostingType::Gain);

      EXIT(FAPostingType::Loss);
    END;
    IF "FA Posting Type" = "FA Posting Type"::"Book Value on Disposal" THEN BEGIN
      IF "Result on Disposal" = "Result on Disposal"::Gain THEN
        EXIT(FAPostingType::"Book Value Gain");

      EXIT(FAPostingType::"Book Value Loss");
    END;
  END ELSE
    EXIT(ConvertPostingType);
END;
_______________________
In BC16 often the IF loops are changed to CASE loops and in this function we suggested to do this as well. Then we need no event/publisher and our options are used in the ELSE branch of the CASE loop.

Here's the full new demanded code:

WITH FALedgEntry DO BEGIN
  CASE "FA Posting Type" OF
    "FA Posting Type"::"Gain/Loss":
    BEGIN
      IF "Result on Disposal" = "Result on Disposal"::Gain THEN
        EXIT(FAPostingType::Gain);
      EXIT(FAPostingType::Loss);
    END;
    "FA Posting Type"::"Book Value on Disposal":
    BEGIN
      IF "Result on Disposal" = "Result on Disposal"::Gain THEN
        EXIT(FAPostingType::"Book Value Gain");
      EXIT(FAPostingType::"Book Value Loss");
    END;
  END ELSE
    EXIT(ConvertPostingType);
END;
_____________________
We hope it is possible to change the code like this.

Kind regards,
Bianca

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
