### ISSUE TITLE
Reminder - [Enum Request] Table 7323 "Posted Whse. Shipment Line"- field "Posted Source Document"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#7968]
Reminder regarding #6522

While the first two fields of the original request have already been converted to enum, the field "Posted Source Document" is still an option field in BCInsider version 17.0.14873.0.
Will it become an enum in BC 17 release, too?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
