### ISSUE TITLE
[Event Request] OnBeforeIncrementBatchName in Codeunit 13 "Gen. Jnl.-Post Batch"

### ISSUE THREAD

**Issue by Wiechardt** [Microsoft/ALAppExtensions#798]
Hi Team,

Is it possible to add the event OnBeforeIncrementBatchName to codeunit 13 "Gen. Jnl.-Post Batch"?

![image](https://user-images.githubusercontent.com/44084862/50970668-b26e8100-14ea-11e9-8bbf-75eed8964b3e.png)

This event can be called from the function UpdateAndDeleteLines before the increment of the batchname - I would like the option of preventing the batch name from incrementing.

![image](https://user-images.githubusercontent.com/44084862/50970659-ac78a000-14ea-11e9-9d4a-f85d052c1ae6.png)

Many thanks,

**Comment by AlexanderYakunin** [comment]
We already implemented new field Increment Batch Name in each template to control increment behavior. You don't need events for this anymore.

**Comment by Wiechardt** [comment]
Thanks Alexander, that's great news.
