### ISSUE TITLE
Reminder - #6578 - [Event Request] Table 37 "Sales Line" - OnLookup "IC Partner Reference" - "OnLookUpICPartnerReferenceTypeCaseElse"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#7984]
Regarding #6578 from March 2020, there is nothing to see in Insider Build 17.0.14873.0-W1.
Status is "ships-in-future-update".
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
