### ISSUE TITLE
[request for external] table Transformation Rule, procedure InsertFindAndReplaceRule()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#7987]
Just as `InsertRec()` is public and helps when inserting multiple rules during app installation, could you please make `InsertFindAndReplaceRule()` public too? It can save considerable spam in install codeunits, etc.

![image](https://user-images.githubusercontent.com/63455896/88303566-13416100-ccff-11ea-9e0f-441952bd3306.png)

**Comment by dtkb** [comment]
While here, looking for opinions: Doing the assignment/`Insert()` on the local `TransformationRule` record complicates calling these, because we don't get the modifications in the record we call the functions on, and instead have to get/find by code after inserting. That is not how all other Data Exch related `InsertRec*()` functions do things. Wouldn't it make more sense if only the test whether the rule already exists were done on the local record, and the `Init`/`Validate`/`Insert()`s were instead done on the current `Rec`? Or even just leave those to the caller...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
