### ISSUE TITLE
Event Request - Codeunit 10765 "Sales Invoice Header - Edit" - OnBeforeSalesInvoiceHeaderModify

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#7988]
We need a new Event Function in Codeunit 10765 “Sales Invoice Header - Edit”, named OnBeforeSalesInvoiceHeaderModify. 
We need this

OnRun(VAR Rec : Record "Sales Invoice Header")
SalesInvoiceHeader := Rec;
SalesInvoiceHeader.LOCKTABLE;
SalesInvoiceHeader.FIND;
SalesInvoiceHeader."Special Scheme Code" := "Special Scheme Code";
SalesInvoiceHeader."Invoice Type" := "Invoice Type";
SalesInvoiceHeader."ID Type" := "ID Type";
SalesInvoiceHeader."Succeeded Company Name" := "Succeeded Company Name";
SalesInvoiceHeader."Succeeded VAT Registration No." := "Succeeded VAT Registration No.";

OnBeforeSalesInvoiceHeaderModify(SalesInvoiceHeader,Rec);

SalesInvoiceHeader.TESTFIELD("No.","No.");
SalesInvoiceHeader.MODIFY;
Rec := SalesInvoiceHeader;
UpdateSIIDocUploadState(Rec);

The event will be:

LOCAL [IntegrationEvent] OnBeforeSalesInvoiceHeaderModify(VAR SalesInvoiceHeader : Record "Sales Invoice Header";FromSalesInvoiceHeader : Record "Sales Invoice Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
