### ISSUE TITLE
[EventRequest] Change place of event - T39 OnBeforeDelete event OnDeleteOnAfterSetPurchLineFilters

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#7993]
As already requested in [here](https://github.com/microsoft/ALAppExtensions/issues/5068) , we asked for event on before delete:
![image](https://user-images.githubusercontent.com/54843470/88367729-c310e000-cd8c-11ea-9514-206fb9090a00.png)
But we got it on the wrong place:
![image](https://user-images.githubusercontent.com/54843470/88367887-1edb6900-cd8d-11ea-8414-4a9fbb773825.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
