### ISSUE TITLE
[Extensibility Request] Table 5069 Salutation Formula - Change Salutation Type to Enum

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#7996]
Hi,

Could you please change field 3 "Salutation Type" from Option to Enum like you do with almost all other option fields?
We need to extend the options on this field, so an extensible enum would be very welcome.

```
table 5069 "Salutation Formula"
{
    Caption = 'Salutation Formula';

    fields
.
.
    { field(3; "Salutation Type"; Option)
        {
            Caption = 'Salutation Type';
            OptionCaption = 'Formal,Informal';
            OptionMembers = Formal,Informal;
        }
```
Thanks

**Comment by AlexanderYakunin** [comment]
We implemented this enum quite long time ago:

        field(3; "Salutation Type"; Enum "Salutation Formula Salutation Type")
        {
            Caption = 'Salutation Type';
        }

**Comment by ptijsma** [comment]
Hi Alexander,

Could you check if this has been pushed to the release branch?
When I check Cumulative Update 3 of the BC Spring 2020 release, it's still an option??

![image](https://user-images.githubusercontent.com/18245218/88632664-33cd3a80-d0b4-11ea-8003-edc3d4891901.png)

**Comment by AlexanderYakunin** [comment]
Please read Wiki for this forum, we NEVER implement events into release branch, we only do it for Master (or Major release).

**Comment by ptijsma** [comment]
Ah, sorry, didn't see that one.
So it'll be in the Wave 2 (Fall) BC 2020 update.

Thanks!
