### ISSUE TITLE
[Extensibility] ShortcutDimCode array should become a protected var in pages

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#7999]
Hi!

I need to access the ShortcutDimCode global variable on page extensions for the following pages.

Would you please make it a protected variable?

- General Journal
- Sales Order Subform
- Sales Invoice Subform
- Purchase Order Subform
- Purch. Invoice Subform
- Sales Quote Subform
- Sales Cr. Memo Subform
- Purchase Quote Subform
- Purch. Cr. Memo Subform
- Standard Sales Code Subform
- Standard Purchase Code Subform
- Sales Journal
- Purchase Journal
- Cash Receipt Journal
- Payment Journal
- Recurring General Journal
- Job G/L Journal
- Service Lines
- Service Invoice Subform
- Service Credit Memo Subform
- Standard Service Code Subform

Thanks!

**Comment by f0ffee** [comment]
Sorry, and these pages as well:

- Blanket Sales Order Subform
- Blanket Purchase Order Subform
- Sales Return Order Subform
- Purchase Return Order Subform

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
