### ISSUE TITLE
Enum HTTP Request Type is translated and returns wrong caption in Dutch version

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#8001]
I have used the Enum “HTTP Request Type” in my code but the enum is translated in the Dutch version to “OPSLAAN” which isn’t a correct HTTP command as you can imagine. Would be nice if we just simple can force the Name only. Saw some complex code how to but would be better if this Enum is not translated at all or translated to 'PUT', 'GET', 'DELETE', 'PATCH' and 'POST'.

<img width="819" alt="error" src="https://user-images.githubusercontent.com/17320737/88371826-1555ff00-cd95-11ea-8945-c1265360c83e.png">

Suggestion 2 is a simple way to use the Name instead of the Caption. when used in code. I saw an example but looks a bit complex [https://diveshboramsdnavblog.wordpress.com/2020/04/12/how-to-get-the-enum-value-name-in-dynamics-365-business-central/](url) but the translated versions are wrong anyway

**Comment by Easystep2** [comment]
Stan,

Are you sure this is a request? I personally think its a bug, You don't need to translate the enum, since "Put" is always a valid caption and OPSLAAN never, when posting a HTTP Request.

@StanPesotskiy

**Comment by StanPesotskiy** [comment]
@Easystep2
It is just an internal tag that will forward this item to the right person.

**Comment by Easystep2** [comment]
Great

Jesper is informed its coming;-)

**Comment by Easystep2** [comment]
Any news on the progress Stan?

**Comment by StanPesotskiy** [comment]
The fix is committed yesterday, in the build 17.0.15349.

**Comment by Easystep2** [comment]
Ok so we can close this one:-)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
