### ISSUE TITLE
Page 10765 " "Posted Sales Invoice - Update"

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#8002]
We need a new event in Page 10765 " "Posted Sales Invoice - Update".

The change will be in the function "RecordChanged":

**LOCAL RecordChanged() RecordIsChanged : Boolean**
{
EXIT(
  ("Special Scheme Code" <> xSalesInvoiceHeader."Special Scheme Code") OR
  ("Invoice Type" <> xSalesInvoiceHeader."Invoice Type") OR
  ("ID Type" <> xSalesInvoiceHeader."ID Type") OR
  ("Succeeded Company Name" <> xSalesInvoiceHeader."Succeeded Company Name") OR
  ("Succeeded VAT Registration No." <> xSalesInvoiceHeader."Succeeded VAT Registration No."));
}
RecordIsChanged := 
  ("Special Scheme Code" <> xSalesInvoiceHeader."Special Scheme Code") OR
  ("Invoice Type" <> xSalesInvoiceHeader."Invoice Type") OR
  ("ID Type" <> xSalesInvoiceHeader."ID Type") OR
  ("Succeeded Company Name" <> xSalesInvoiceHeader."Succeeded Company Name") OR
  ("Succeeded VAT Registration No." <> xSalesInvoiceHeader."Succeeded VAT Registration No.");

OnAfterRecordChanged(Rec,xSalesInvoiceHeader,RecordIsChanged);
EXIT(RecordIsChanged);

The new event will be:

**LOCAL [IntegrationEvent] OnAfterRecordChanged(VAR SalesInvoiceHeader : Record "Sales Invoice Header";xSalesInvoiceHeader : Record "Sales Invoice Header";VAR RecordIsChanged : Boolean)**

We need the same change in the pages 10766 and 10765.

Thank you.
Sonia Roca.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
