### ISSUE TITLE
[Event Request] codeunit 408 "DimensionManagement" - Change IntergrationEvent

### ISSUE THREAD

**Issue by osteeger** [microsoft/ALAppExtensions#8006]
Can we change the following event for the "DimensionManagement" Codeunit: **OnAfterDefaultDimObjectNoWithoutGlobalDimsList**
```
   ///
    // [IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)] ///NEW
    ///-
    local procedure OnAfterDefaultDimObjectNoWithoutGlobalDimsList(var TempAllObjWithCaption: Record AllObjWithCaption temporary)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
