### ISSUE TITLE
[Event Request] page 49 "Purchase Quote" - Event for procedure ActivateFields

### ISSUE THREAD

**Issue by TBannier** [microsoft/ALAppExtensions#8036]
Can we get the following event for the "Purchase Quote" page: **OnAfterActivateFields**

```
[…]
    //New Start
    //local procedure ActivateFields()
    procedure ActivateFields()
    //New End
    begin
        IsBuyFromCountyVisible := FormatAddress.UseCounty("Buy-from Country/Region Code");
        IsPayToCountyVisible := FormatAddress.UseCounty("Pay-to Country/Region Code");
        IsShipToCountyVisible := FormatAddress.UseCounty("Ship-to Country/Region Code");

        //New Start
        OnAfterActivateFields();
        //New End
    end;
[…]
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterActivateFields()
    begin
    end;
```

**Comment by StanPesotskiy** [comment]
We can make procedure ActivateFields() protected so you will be able to use it in your extension. Would it be ok?

**Comment by TBannier** [comment]
Hi Stan,

yes, this would be fine but 
we still need the Event "OnAfterActivateFields"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
