### ISSUE TITLE
[ParameterRequest] VendEntryEdit.Codeunit.al (codeunit 113 "Vend. Entry-Edit")

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#8051]
Hi MS,
Please help us in migrating our verticalized solution by adding below parameter by VAR in below event in **VendEntryEdit.Codeunit.al** Table.

**Requested Signature**
```
 [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeDtldVendLedgEntryModifyAll(FromVendLedgEntry: Record "Vendor Ledger Entry"; Var DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; var VendLedgEntry: Record "Vendor Ledger Entry")
    begin
    end;
```

**Existing Signature**
```
 [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeDtldVendLedgEntryModifyAll(FromVendLedgEntry: Record "Vendor Ledger Entry"; DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; var VendLedgEntry: Record "Vendor Ledger Entry")
    begin
    end;
```
Thanks
SUD

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
