### ISSUE TITLE
[Event Request] table 5902 "Service Line" - Event for trigger OnLookup() Field "No."

### ISSUE THREAD

**Issue by osteeger** [microsoft/ALAppExtensions#8061]
Can we change the following event for the "Service Line" table: **OnOnLookup**
```
            ///
            trigger OnLookup()
            begin
                OnOnLookup(Rec);
            end;
            ///-``

```

```
   [IntegrationEvent(false, false)]
    local procedure OnOnLookup(var Rec: Record "Service Line")
    begin
    end;
```

**Comment by StanPesotskiy** [comment]
We cannot add a Lookup trigger because it disables the internal lookup defined by the table relation.

There are 2 alternative ways to have your own lookup:
•	extend page by adding lookup trigger
•	extend table relation property of the field to get needed lookup
