### ISSUE TITLE
Event Request: Table 1650

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#807]
Please add event

    [Integration(TRUE)]
    LOCAL PROCEDURE OnAfterGetWebServiceURL@8(VAR ServiceURL@1000 : Text);
    BEGIN
    END;

Call from

    [External]
    PROCEDURE GetWebServiceURL@10(VAR ServiceURL@1002 : Text) WebServiceURL : Text;
    VAR
      InStream@1000 : InStream;
    BEGIN
      CALCFIELDS("Web Service URL");
      IF "Web Service URL".HASVALUE THEN BEGIN
        "Web Service URL".CREATEINSTREAM(InStream);
        InStream.READ(ServiceURL);
      END;

      WebServiceURL := ServiceURL;
      OnAfterGetWebServiceURL(ServiceURL);
    END;

**Comment by gunnargestsson** [comment]
This also requires one minor update to Page 1651 - GenerateXMLStructure
 
    LOCAL PROCEDURE GenerateXMLStructure@1();
    VAR
      **ServiceUrl@1000 : Text;**
    BEGIN
      TempXMLBuffer.RESET;
      TempXMLBuffer.DELETEALL;
      **GetWebServiceURL(ServiceUrl);**
      IF GetXMLStructure(TempXMLBuffer,**ServiceUrl**) THEN BEGIN
        TempXMLBuffer.RESET;
        CurrPage.SimpleDataExchSetup.PAGE.SetXMLDefinition(TempXMLBuffer);
      END ELSE
        ShowHttpError;
    END;

**Comment by gunnargestsson** [comment]
@jobulsin thank you for taking this request.
I am looking at your implementation and that is not as I requested and not usable.
Then change to function GetWebServiceURL in Table 1650 are not as requested
The integration invent added to Table 1650 does not include sender
No changes to Page 1651 have been made.

**Comment by JesperSchulz** [comment]
Reopening issue as per Gunnars comment.

**Comment by gunnargestsson** [comment]
Include Sender is still missing on the table event.

[Integration(TRUE)]

is

[Integration]

for AL 

[IntegrationEvent(false, false)]
local procedure OnAfterGetWebServiceURL(var ServiceURL: Text)
begin
end;

should be

[IntegrationEvent(true, false)]
local procedure OnAfterGetWebServiceURL(var ServiceURL: Text)
begin
end;
