### ISSUE TITLE
[Bug] Cannot create new companies in Insider builds

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#8077]
Hi MS Team,

I am a little lost in where to report this - so I am sorry, if this is the wrong place...

For at least the last week or so, the daily insider builds have crashed when trying create new companies.

If you go to the list Companies, click New, follow the wizard and click Finish, the client crashes every time with a "Something went wrong" splash screen.

![image](https://user-images.githubusercontent.com/33286030/88543305-0f238500-d018-11ea-97dd-63250338befb.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
