### ISSUE TITLE
[Event Request] page 344 "Navigat" - Change of Parameter for Event OnAfterGetDocumentCount

### ISSUE THREAD

**Issue by TBannier** [microsoft/ALAppExtensions#8079]
Can we get the following change for the "Navigat" page: Change of Parameter **OnAfterGetDocumentCount**

```
    // [IntegrationEvent(false, false)]    //Old
    [IntegrationEvent(true, false)]        //New
    local procedure OnAfterGetDocumentCount(var DocCount: Integer)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
