### ISSUE TITLE
[Event Change] Table 39 - "Purchase Line" UpdateBaseAmounts()

### ISSUE THREAD

**Issue by PieterJacob** [microsoft/ALAppExtensions#8080]
Dear Microsoft,

For "Purchase Line".UpdateVatOnlines we like to have the ability to assign a value for "VAT Base Amount" after UpdateBaseAmount(...). 

Publisher OnAfterUpdateBaseAmounts(...) already exists, however it does not contain the arguments we need to adjust "VAT Base Amount". Therefore  we hope to see an event change for integration event OnAfterUpdateBaseAmounts.

New Event Change. Arguments added : NewAmount: Decimal; NewAmountIncludingVAT: Decimal; NewVATBaseAmount: Decimal
```
[IntegrationEvent(false, false)]
local procedure OnAfterUpdateBaseAmounts(NewAmount: Decimal; NewAmountIncludingVAT: Decimal; NewVATBaseAmount: Decimal;var PurchLine: Record "Purchase Line"; var xPurchLine: Record "Purchase Line"; CurrFieldNo: Integer)
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
