### ISSUE TITLE
Codeunit 1502 Workflow Setup - Function exposure request

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#8085]
Hi

Please can the following functions be made global in the Workflow Setup coduenit (C1502) so we can use them with our extension rather than having to write a local copy of each:

    InsertEventArgument
    InsertEntryPointEventStep
    InsertApprovalArgument
    InsertNotificationArgument
    BuildNoPendingApprovalsConditions
    BuildPendingApprovalsConditions
    SetNextStep
    InsertMessageArgument

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
