### ISSUE TITLE
Codeunit 1521 Workflow Response Handling - AllowRecordUsage Event Request

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#8086]
Hi

Please can you add an event publisher to the case statement in the AllowRecordUsage(Variant: Variant) procedure so that we can add in our own checks please?  Example code below.

    local procedure AllowRecordUsage(Variant: Variant)
    var
        ApprovalEntry: Record "Approval Entry";
        WorkflowWebhookEntry: Record "Workflow Webhook Entry";
        GenJournalBatch: Record "Gen. Journal Batch";
        ItemJournalBatch: Record "Item Journal Batch";
        FAJournalBatch: Record "FA Journal Batch";
        RecordRestrictionMgt: Codeunit "Record Restriction Mgt.";
        RecRef: RecordRef;
    begin
        RecRef.GetTable(Variant);

        case RecRef.Number of
            DATABASE::"Approval Entry":
                begin
                    RecordRestrictionMgt.AllowRecordUsage(Variant);
                    RecRef.SetTable(ApprovalEntry);
                    RecRef.Get(ApprovalEntry."Record ID to Approve");
                    AllowRecordUsage(RecRef);
                end;
            DATABASE::"Workflow Webhook Entry":
                begin
                    RecRef.SetTable(WorkflowWebhookEntry);
                    RecRef.Get(WorkflowWebhookEntry."Record ID");
                    AllowRecordUsage(RecRef);
                end;
            DATABASE::"Gen. Journal Batch":
                begin
                    RecRef.SetTable(GenJournalBatch);
                    RecordRestrictionMgt.AllowGenJournalBatchUsage(GenJournalBatch);
                end;
            DATABASE::"Item Journal Batch":
                begin
                    RecRef.SetTable(ItemJournalBatch);
                    RecordRestrictionMgt.AllowItemJournalBatchUsage(ItemJournalBatch);
                end;
            DATABASE::"FA Journal Batch":
                begin
                    RecRef.SetTable(FAJournalBatch);
                    RecordRestrictionMgt.AllowFAJournalBatchUsage(FAJournalBatch);
                end
            else
                // New Code Starts
                OnAllowRecordUsage(Variant,Handled);
                    IF NOT Handled THEN
                // New Code Ends
                RecordRestrictionMgt.AllowRecordUsage(Variant);
               
        end;
    end;

LOCAL [IntegrationEvent] OnAllowRecordUsage(VAR Variant : Variant;VAR Handled : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
