### ISSUE TITLE
Codeunit 1522 Workflow Request Page Handling - Please can you add Events

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#8087]
Hi 

Please can you add events to the end of the following functions.  No parameters required:

    AssignEntitiesToWorkflowEvents
    InsertRequestPageEntities
    InsertRequestPageFields

Thanks in advance

Chris

**Comment by StanPesotskiy** [comment]
Please provide the signature of the event along with the fragments of code that could define location of the event call unambiguously.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
