### ISSUE TITLE
[External Function] Codeunit "Req. Wksh.-Make Order"

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8089]
Can you change these functions to not be local?

`procedure CheckAddressDetails(SalesOrderNo: Code[20]; SalesLineNo: Integer; UpdateAddressDetails: Boolean) Result: Boolean`

`procedure PurchaseOrderLineMatchReqLine(ReqLine: Record "Requisition Line"): Boolean`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
