### ISSUE TITLE
Reminder - #6069 [Event Request] Table 38 "Purchase Header" – UpdatePurchAmountLines

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8091]
Regarding [#6069](https://github.com/microsoft/ALAppExtensions/issues/6069) from March 2020, there is nothing to see in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update".
Will you still integrate it?

**Comment by StanPesotskiy** [comment]
It was the result of incorrect closing of the request. The automatic answer has made you think it had been implemented. 
Sorry for that.

You can see a comment there that suggests using the existing event:
"There is existing event with all required parameters OnBeforeUpdatePurchLineAmounts(Rec, xRec, CurrFieldNo, IsHandled); in this function."
Do you have a problem using it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by TMEKUMA** [comment]
Since I need to set something in context, the publisher would be fine. With the Handled Pattern at the beginning I have to copy your code and then skip the standard and I have a place to check regularly for changes in the standard.
