### ISSUE TITLE
[External Function] Codeunit "DimensionManagement"

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8095]
Please make this function accessible: 

`procedure DefaultDimInsertTempObject(var TempAllObjWithCaption: Record AllObjWithCaption temporary; TableID: Integer)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
