### ISSUE TITLE
Reminder -  #3737 [Event Request] Table 83 Item Journal Line – DisplayErrorIfItemIsBlocked

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8097]
Regarding [#3737](https://github.com/microsoft/ALAppExtensions/issues/3737) from August 2019, there is nothing to see about OnDisplayErrorIfItemIsBlockedOnAfterCheckError in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update".
Will you still integrate it? It is good to run the standard test first and then run your own tests without duplicating the standard code.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
