### ISSUE TITLE
Reminder - #1159 [Event Request] Table 7501 Item Attribute Value – LoadCategoryAttributesFactBoxData

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8099]
Regarding [#1159](https://github.com/microsoft/ALAppExtensions/issues/1159) from Februar 2019, there is nothing to see in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update".
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
