### ISSUE TITLE
[Event Request] Page 54 - Purchase Order Subform

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/ALAppExtensions#81]
we need new publisher on function RedistributeTotalsOnAfterValidate
```
LOCAL RedistributeTotalsOnAfterValidate()
CurrPage.SAVERECORD;

PurchaseHeader.GET("Document Type","Document No.");
IF DocumentTotals.PurchaseCheckNumberOfLinesLimit(PurchaseHeader) THEN
  DocumentTotals.PurchaseRedistributeInvoiceDiscountAmounts(Rec,VATAmount,TotalPurchaseLine);

//NEW CODE BEGIN>>
OnAfterRedistributeDiscAmounts(Rec)
//NEW CODE END<<

CurrPage.UPDATE;
```

with new publisher
`LOCAL [IntegrationEvent] OnAfterRedistributeDiscAmounts(PurchaseLine : Record "Purchase Line")`

**Comment by AlexanderYakunin** [comment]
Please check latest available D365 BC build and update your ask as code structure have been changed here

**Comment by AlexanderYakunin** [comment]
OnAfterPurchaseRedistributeInvoiceDiscountAmounts event can be implemented in COD57.
