### ISSUE TITLE
[Event Request] report 202 "Sales Document - Test" – OnBeforeCheckDimValuePostingHeader/OnBeforeCheckDimValuePostingLine

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8101]
for the functionality of the publishers OnBeforeCheckDimValuePostingHeader and OnBeforeCheckDimValuePostingLine var is necessary for TableID and No (like OnAfterCreateDimTableIDs)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDimValuePostingHeader(var SalesHeader: Record "Sales Header"; var TableID: array[10] of Integer; var No: array[10] of Code[20]);
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDimValuePostingLine(var SalesLine: Record "Sales Line"; var TableID: array[10] of Integer; var No: array[10] of Code[20]);
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
