### ISSUE TITLE
[Event Request] report 5855 "Implement Standard Cost Change" OnBeforeCalculateInventoryValue

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8103]
with the Publisher OnBeforeCalculateInventoryValue the variable ItemJournalBatch is missing, because the template name is not sufficient to address a Journal Line.

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateInventoryValue(var ItemJournalTemplate: Record "Item Journal Template"; var ItemJournalBatch: Record "Item Journal Batch"; var StandardCostWorksheet: Record "Standard Cost Worksheet"; PostingDate: Date; DocNo: Code[20]; HideDuplWarning: Boolean; var IsHandled: Boolean);
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
