### ISSUE TITLE
Reminder - #3743 [Event Request] Report 7315 Assemble-to-Order Link – CreateReservationEntry 

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8107]
Regarding [#3743](https://github.com/microsoft/ALAppExtensions/issues/3743) from August 2019, there is nothing to see in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update" (but wrong object name, the right one is 'Calculate Warehouse Adjustment').
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
