### ISSUE TITLE
Reminder - #6239 [Event Request] Page296 "Recurring Req. Worksheet" – Action "Carry &Out Action Message" 

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8109]
Regarding [#6239 ](https://github.com/microsoft/ALAppExtensions/issues/6239) from Februar 2020, there is nothing to see in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update" 
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
