### ISSUE TITLE
[Event Request] Table 96 function UpdateDimensionSetId

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#811]
We need a new publisher:

![image](https://user-images.githubusercontent.com/42136602/51021728-a8985c80-1582-11e9-823c-5dcd9dc191ec.png)

![image](https://user-images.githubusercontent.com/42136602/51021762-c5349480-1582-11e9-81a7-1c4f396d8c25.png)

**Comment by geeknikolai** [comment]
possibly the same as https://github.com/Microsoft/ALAppExtensions/issues/596

**Comment by ThomasBrendel** [comment]
Its not the same, because Table 408 is a standard function that gets called by many other tables.
here we have the rec = GL Budget Entry as Record and need it in that call
