### ISSUE TITLE
Reminder - #3745 [Event Request] Codeunit 80 Sales-Post – ReleaseSalesDocument 

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8111]
Regarding [#3745](https://github.com/microsoft/ALAppExtensions/issues/3745) from August 2019, there only parts to see in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update"
Will you still integrate it?

But I would also be satisfied if the existing Publisher OnReleaseSalesDocumentOnBeforeSetStatus is extended by the parameters SavedStatus, PreviewMode, SuppressCommit

```
    [IntegrationEvent(false, false)]
    local procedure OnReleaseSalesDocumentOnBeforeSetStatus(var SalesHeader: Record "Sales Header"; SavedStatus: Option; PreviewMode: Boolean; SuppressCommit: Boolean; var IsHandled: Boolean);
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
