### ISSUE TITLE
[EventRequest] Handle additional changes in CU20 "Posting Preview Event Handler"

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#8112]
Hi Base Team,

In our vertical for the legal market, we need to redirect some g/l postings to comply with legislation surrounding the way law firms post deposits of their clients money. We have it working in normal posting, but we need some extra features in the preview codeunit.

We need to update a few fields when GL Entries, Cust. Ledger Entries and Det. Cust. Ledger Entries are modified. For that we need two new event subscribers in codeunit 20, each with an event publisher.

**New event subscribers:**

[EventSubscriber(ObjectType::Table, 17, 'OnAfterModifyEvent', '', false, false)]
    local procedure OnModifyGLEntry(var Rec: Record "G/L Entry"; RunTrigger: Boolean)
    begin
        if Rec.IsTemporary then
            exit;

        TempGLEntry := Rec;
        TempGLEntry."Document No." := '***';

        OnBeforeModifyTempGLEntry(Rec, TempGLEntry);

        if TempGLEntry.Modify then
            PreventCommit();
    end;

    [EventSubscriber(ObjectType::Table, 379, 'OnAfterModifyEvent', '', false, false)]
    local procedure OnModifyDetailedCustLedgerEntry(var Rec: Record "Detailed Cust. Ledg. Entry"; RunTrigger: Boolean)
    begin
        if Rec.IsTemporary then
            exit;

        TempDtldCustLedgEntry := Rec;
        TempDtldCustLedgEntry."Document No." := '***';

        OnBeforeModifyTempDetCustLedgEntry(Rec, TempDtldCustLedgEntry);

        if TempCustLedgEntry.Modify then
            PreventCommit();
    end;

**Modified code**

[EventSubscriber(ObjectType::Table, 21, 'OnAfterModifyEvent', '', false, false)]
    local procedure OnModifyCustLedgerEntry(var Rec: Record "Cust. Ledger Entry"; RunTrigger: Boolean)
    begin
        if Rec.IsTemporary then
            exit;

        TempCustLedgEntry := Rec;
        TempCustLedgEntry."Document No." := '***';

        //>>New publisher
        OnBeforeModifyTempCustLedgEntry(Rec, TempCustLedgEntry);
        //<<New publisher
        
        if TempCustLedgEntry.Modify then
            PreventCommit();
    end;

**New publishers**

[IntegrationEvent(false, false)]
    local procedure OnBeforeModifyTempGLEntry(var Rec: Record "G/L Entry"; var TempCustLedgerEntry: Record "G/L Entry")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyTempCustLedgEntry(var Rec: Record "Cust. Ledger Entry"; var TempCustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyTempDetCustLedgEntry(var Rec: Record "Detailed Cust. Ledg. Entry"; var TempCustLedgerEntry: Record "Detailed Cust. Ledg. Entry")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
