### ISSUE TITLE
Reminder - #3753 [Event Request] Codeunit 414 Release Sales Document – PerformManualCheckAndRelease

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8113]
Regarding #3753 from August 2019, there only the first Publisher to see in Insider Build 17.0.14964.0-W1 (the Publisher OnAfterPerformManualRelease is not available). 
Status is "ships-in-future-update"
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
