### ISSUE TITLE
[External] Page 344 Navigate

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8114]
Please make these two functions external:

`procedure NoOfRecords(TableID: Integer): Integer`

`procedure SetSource(PostingDate: Date; DocType2: Text[100]; DocNo: Text[50]; SourceType2: Integer; SourceNo2: Code[20])`

**Comment by AlexanderYakunin** [comment]
We usually make such procedures as protected, to make them available in pageextension. Is it ok for you?

**Comment by achim-t** [comment]
Yes, that would work for us.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
