### ISSUE TITLE
[External] Page 5784 "Filters to Get Source Docs."

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8115]
Please make the global variable RequestType accessible in a page extension.

That should look like this, right?
```
protected var
   RequestType: Option Receive,Ship;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
