### ISSUE TITLE
[Event Request] codeunit 5880 "Phys. Invt. Order-Finish" OnCreateReservEntriesOnAfterTempPhysInvtTrackingBufferModify

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8117]
The Publisher OnCreateReservEntriesOnAfterTempPhysInvtTrackingBufferModify requires a var for the parameter MaxQtyToTransfer. 

```
    [IntegrationEvent(false, false)]
    local procedure OnCreateReservEntriesOnAfterTempPhysInvtTrackingBufferModify(AllBufferLines: Boolean; var MaxQtyToTransfer: Decimal; QtyToTransfer: Decimal)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
