### ISSUE TITLE
Reminder - #1975 [Event Request] Codeunit 7500 Item Attribute Management – InsertBufferedItemAttributeValueMapping 

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8118]
Regarding #1975 from April 2019, there is nothing to see in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update"
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
