### ISSUE TITLE
[External] Page 6510 "Item Tracking Lines"

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8119]
Please make this function external.

`procedure EntriesAreIdentical(var ReservEntry1: Record "Reservation Entry"; var ReservEntry2: Record "Reservation Entry"; var IdenticalArray: array[2] of Boolean): Boolean`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
