### ISSUE TITLE
[External] Page 5985 "Service Item Replacement"

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8120]
Please make these global variables accessible in a page extension.

```
VariantCode: Code[10];
NewSerialNo: Code[50];
CopyComponentsFrom: Option "None","Item BOM","Old Service Item","Old Service Item w/o Serial No.";
Replacement: Option "Temporary",Permanent;
ServItemNo: Code[20];
ItemNo: Code[20];
VariantCode: Code[10];
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
