### ISSUE TITLE
[Event Request] Codeunit::"Catalog Item Management" - Function NonstockAutoItem - OnBeforeNonstockAutoItem

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8122]
We like to request the following Event:
Object: Codeunit::"Catalog Item Management"
Function: NonstockAutoItem
Publisher Event: OnBeforeNonstockAutoItem
Reason: To implement custom business logic
Where is the event placed:
procedure NonstockAutoItem(NonStock2: Record "Nonstock Item")
    begin
        OnBeforeNonstockAutoItem(NonStock2);
        if NewItem.Get(NonStock2."Item No.") then
            Error(Text000, NonStock2."Item No.");
        NonStock2."Item No." :=
          GetNewItemNo(
            NonStock2, StrLen(NonStock2."Vendor Item No."), StrLen(NonStock2."Manufacturer Code"));
        NonStock2.Modify();
        OnBeforeInsertItemUnitOfMeasure(NonStock2);

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeNonstockAutoItem(var NonstockItem: Record "Nonstock Item")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
