### ISSUE TITLE
[Event Request] Codeunit::"Gen- Jnl.-Post Line" - Function GetDtldCustLedgEntryAccNo - OnBeforeGetDtldCustLedgEntryAccNo

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8123]
We like to request the following Event:
Object: Codeunit::"Gen- Jnl.-Post Line"
Function: GetDtldCustLedgEntryAccNo
Publisher Event: OnBeforeGetDtldCustLedgEntryAccNo
Reason: To implement custom business logic
Where is the event placed:
local procedure GetDtldCustLedgEntryAccNo(GenJnlLine: Record "Gen. Journal Line"; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; OriginalTransactionNo: Integer; Unapply: Boolean): Code[20]
    var
        GenPostingSetup: Record "General Posting Setup";
        Currency: Record Currency;
        AmountCondition: Boolean;
        AccNo: Code[20];
        Handled: Boolean;
    begin
        **OnBeforeGetDtldCustLedgEntryAccNo(GenJnlLine, DtldCVLedgEntryBuf, CustPostingGr, OriginalTransactionNo, Unapply, VATEntry, AccNo, Handled);
        if Handled then
            exit(AccNo);**
        with DtldCVLedgEntryBuf do begin
            AmountCondition := IsDebitAmount(DtldCVLedgEntryBuf, Unapply);

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetDtldCustLedgEntryAccNo(var GenJournalLine: Record "Gen. Journal Line"; var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var CustomerPostingGroup: Record "Customer Posti

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
