### ISSUE TITLE
[Event Request] Codeunit::"Gen- Jnl.-Post Line" - Function GetDtldVendLedgEntryAccNo - OnBeforeGetDtldVendLedgEntryAccNo

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8124]
We like to request the following Event:
Object: Codeunit::"Gen- Jnl.-Post Line"
Function: GetDtldVendLedgEntryAccNo
Publisher Event: OnBeforeGetDtldVendLedgEntryAccNo
Reason: To implement custom business logic
Where is the event placed:
local procedure GetDtldVendLedgEntryAccNo(GenJnlLine: Record "Gen. Journal Line"; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; VendPostingGr: Record "Vendor Posting Group"; OriginalTransactionNo: Integer; Unapply: Boolean): Code[20]
    var
        Currency: Record Currency;
        GenPostingSetup: Record "General Posting Setup";
        AmountCondition: Boolean;
        AccNo: Code[20];
        Handled: Boolean;
    begin
        **OnBeforeGetDtldVendLedgEntryAccNo(GenJnlLine, DtldCVLedgEntryBuf, VendPostingGr, OriginalTransactionNo, Unapply, VATEntry, AccNo, Handled);
        if Handled then
            exit(AccNo);**
        with DtldCVLedgEntryBuf do begin
            AmountCondition := IsDebitAmount(DtldCVLedgEntryBuf, Unapply);

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetDtldVendLedgEntryAccNo(var GenJournalLine: Record "Gen. Journal Line"; var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var VendorPostingGroup: Record "Vendor Posting G

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
