### ISSUE TITLE
Reminder - #2402 [Event Request] Codeunit 6620 Copy Document Mgt. – CopyPurchInvLinesToDoc #2402

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8125]
Regarding #2402 from May 019, there is nothing to see in Insider Build 17.0.14964.0-W1.
Status is "ships-in-future-update"
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
