### ISSUE TITLE
[Event Request] Codeunit::"Inventory Profile Offsetting" - Function ForecastInitDemand - OnAfterForecastInitDemand

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8126]
We like to request the following Event:
Object: Codeunit::"Inventory Profile Offsetting"
Function: ForecastInitDemand
Publisher Event: OnAfterForecastInitDemand
Reason: To implement custom business logic
Where is the event placed:
procedure ForecastInitDemand(var InventoryProfile: Record "Inventory Profile"; ProductionForecastEntry: Record "Production Forecast Entry"; ItemNo: Code[20]; LocationCode: Code[10]; TotalForecastQty: Decimal)
    begin
        with InventoryProfile do begin
            Init;
            "Line No." := NextLineNo;
            "Source Type" := DATABASE::"Production Forecast Entry";
            "Planning Flexibility" := "Planning Flexibility"::None;
            "Qty. per Unit of Measure" := 1;
            "MPS Order" := true;
            "Source ID" := ProductionForecastEntry."Production Forecast Name";
            "Item No." := ItemNo;
            if ManufacturingSetup."Use Forecast on Locations" then
                "Location Code" := ProductionForecastEntry."Location Code"
            else
                "Location Code" := LocationCode;
            "Remaining Quantity (Base)" := TotalForecastQty;
            "Untracked Quantity" := TotalForecastQty;
        end;
        **OnAfterForecastInitDemand(InventoryProfile, ProductionForecastEntry, ItemNo, LocationCode, TotalForecastQty);**
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterForecastInitDemand(var InventoryProfile: Record "Inventory Profile"; ProductionForecastEntry: Record "Production Forecast Entry"; ItemNo: Code[20]; LocationCode: Code[10]; TotalForecastQty: Decim

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
