### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Check Line" - Function CheckPhysInventory - OnBeforeCheckPhysInventory

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8127]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Check Line"
Function: CheckPhysInventory
Publisher Event: OnBeforeCheckPhysInventory
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckPhysInventory(ItemJnlLine: Record "Item Journal Line")
    var
        IsHandled: Boolean;
    begin
        **OnBeforeCheckPhysInventory(ItemJnlLine, IsHandled);
        if IsHandled then
            exit;**
        with ItemJnlLine do begin
            if not
               ("Entry Type" in
                ["Entry Type"::"Positive Adjmt.", "Entry Type"::"Negative Adjmt."])
            then begin

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPhysInventory(ItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
