### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Batch" - Function PostWhseJnlLines - OnBeforePostWhseJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8128]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Batch"
Function: PostWhseJnlLines
Publisher Event: OnBeforePostWhseJnlLine
Reason: To implement custom business logic
Where is the event placed:
local procedure PostWhseJnlLines(ItemJnlLine: Record "Item Journal Line"; var TempTrackingSpecification: Record "Tracking Specification" temporary; ItemJnlTemplateType: Option; ToTransfer: Boolean)
    var
        WhseJnlLine: Record "Warehouse Journal Line";
        TempWhseJnlLine: Record "Warehouse Journal Line" temporary;
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        IsHandled: Boolean;
    begin
        **IsHandled := false;
        OnBeforePostWhseJnlLine(ItemJnlLine, TempTrackingSpecification, ItemJnlTemplateType, ToTransfer, IsHandled);
        if IsHandled then
            exit;**
        with ItemJnlLine do
            if Location."Bin Mandatory" then

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePostWhseJnlLine(ItemJnlLine: Record "Item Journal Line"; var TempTrackingSpecification: Record "Tracking Specification" temporary; ItemJnlTemplateType: Option; ToTransfer: Boolean; var IsHandled

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
