### ISSUE TITLE
[Event Request] Codeunit::"Item Subst." - Function UpdateComponent - OnBeforeUpdateComponent

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8129]
We like to request the following Event:
Object: Codeunit::"Item Subst."
Function: UpdateComponent
Publisher Event: OnBeforeUpdateComponent
Reason: To implement custom business logic
Where is the event placed:
procedure UpdateComponent(var ProdOrderComp: Record "Prod. Order Component"; SubstItemNo: Code[20]; SubstVariantCode: Code[10])
    var
        TempProdOrderComp: Record "Prod. Order Component" temporary;
        ProdOrderCompReserve: Codeunit "Prod. Order Comp.-Reserve";
        IsHandled: Boolean;
    begin
        **OnBeforeUpdateComponent(ProdOrderComp, SubstItemNo, SubstVariantCode, IsHandled);
        if IsHandled then
            exit;**
        if (ProdOrderComp."Item No." <> SubstItemNo) or (ProdOrderComp."Variant Code" <> SubstVariantCode) then
            ProdOrderCompReserve.DeleteLine(ProdOrderComp);

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateComponent(var ProdOrderComp: Record "Prod. Order Component"; SubstItemNo: Code[20]; SubstVariantCode: Code[10]; var Ishandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
