### ISSUE TITLE
Events in OIOUBL app

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/ALAppExtensions#813]
Hi,

We would like to extend some of the functionality in the OIOUBL app.
Bu the app is not available in the repo right now.

**Comment by JesperSchulz** [comment]
We are working on getting the local extensions published on GitHub. Just a little more patience :-)

**Comment by AndreiPanko** [comment]
Good news! OIOUBL extension was added to the repo:
https://github.com/Microsoft/ALAppExtensions/tree/master/OIOUBL

Looking forward to seeing your pull request :)

**Comment by RasmusTidselbak** [comment]
Hehe I did just that as soon as I saw it :)
https://github.com/Microsoft/ALAppExtensions/pull/1247
