### ISSUE TITLE
[Event Request] Codeunit::"Item Tracking Management" - Function RetrieveSubcontrItemTracking - OnbeforeRetrieveSubcontrItemTracking

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8130]
We like to request the following Event:
Object: Codeunit::"Item Tracking Management"
Function: RetrieveSubcontrItemTracking
Publisher Event: OnbeforeRetrieveSubcontrItemTracking
Reason: To implement custom business logic
Where is the event placed:
local procedure RetrieveSubcontrItemTracking(ItemJnlLine: Record "Item Journal Line"; var TempHandlingSpecification: Record "Tracking Specification" temporary): Boolean
    var
        ReservEntry: Record "Reservation Entry";
        ProdOrderRoutingLine: Record "Prod. Order Routing Line";
        IsLastOperation: Boolean;
        IsHandled: Boolean;
        Success: Boolean;
    begin
        IsHandled := false;
        **OnBeforeRetrieveSubcontrItemTracking(ItemJnlLine, TempHandlingSpecification, Success, IsHandled);
        if IsHandled then
            exit(Success);**
        if not ItemJnlLine.Subcontracting then
            exit(false);

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeRetrieveSubcontrItemTracking(ItemJnlLine: Record "Item Journal Line"; var TempHandlingSpecification: Record "Tracking Specification" temporary; var Success: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
