### ISSUE TITLE
[Event Request] Codeunit::"Job Jnl.-Post Line" - Function PostWhseJnlLine - OnBeforePostWhseJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8131]
We like to request the following Event:
Object: Codeunit::"Job Jnl.-Post Line"
Function: PostWhseJnlLine
Publisher Event: OnBeforePostWhseJnlLine
Reason: To implement custom business logic
Where is the event placed:
local procedure PostWhseJnlLine(ItemJnlLine: Record "Item Journal Line"; OriginalQuantity: Decimal; OriginalQuantityBase: Decimal; var TempTrackingSpecification: Record "Tracking Specification" temporary)
    var
        WarehouseJournalLine: Record "Warehouse Journal Line";
        TempWarehouseJournalLine: Record "Warehouse Journal Line" temporary;
        ItemTrackingManagement: Codeunit "Item Tracking Management";
        WMSManagement: Codeunit "WMS Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        **OnBeforePostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, TempTrackingSpecification, IsHandled);
        if IsHandled then
            exit;**
        with ItemJnlLine do begin
            if "Entry Type" in ["Entry Type"::Consumption, "Entry Type"::Output] then
                exit;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePostWhseJnlLine(ItemJnlLine: Record "Item Journal Line"; OriginalQuantity: Decimal; OriginalQuantityBase: Decimal; var TempTrackingSpecification: Record "Tracking Specification" temporary; var I

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
