### ISSUE TITLE
Reminder - #2395 [Event Request] Codeunit 6620 Copy Document Mgt. – CopySalesShptLinesToDoc

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8133]
Reminder - #2395 [Event Request] Codeunit 6620 Copy Document Mgt. – CopySalesShptLinesToDoc 

Regarding #2395 from May 2019, there is only a part to see in Insider Build 17.0.14964.0-W1 (Publisher OnCopySalesShptLinesToDocOnAfterFromSalesHeaderTransferfields is missing).
Status is "ships-in-future-update"
Will you still integrate it?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
