### ISSUE TITLE
[External] Table 5902 "Service Line"

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8135]
Please make this function external.

`procedure GetDefaultBin()`

Also, please make these global variables protected:

```
ServHeader: Record "Service Header";
TempTrackingSpecification: Record "Tracking Specification" temporary;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by achim-t** [comment]
@StanPesotskiy 
Are there any updates on this?

**Comment by StanPesotskiy** [comment]
We have implemented just the first part - procedure GetDefaultBin().
The variables were not updated by mistake. 
Could you please create another request including the vars part there?
