### ISSUE TITLE
[EventRequest] codeunit 1208 "Pmt Export Mgt Cust Ledg Entry" - PreparePaymentExportDataCLE() - OnBeforeInsertPmtExportDataJnlFromCustLedgerEntry

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#8139]
`codeunit 1207 "Pmt Export Mgt Vend Ledg Entry"` provides an event here, emitted by `PreparePaymentExportDataVLE()` after populating `Payment Export Data` from a `Vendor Ledger Entry` but before inserting:

    procedure PreparePaymentExportDataVLE[...]
    begin
        [...]
            "Recipient Name" := CopyStr(Vendor.Name, 1, 35);
            "Recipient Address" := CopyStr(Vendor.Address, 1, 35);
            "Recipient City" := CopyStr(Vendor."Post Code" + ' ' + Vendor.City, 1, 35);
            "Transfer Date" := VendorLedgerEntry."Posting Date";
            "Message to Recipient 1" := CopyStr(VendorLedgerEntry."Message to Recipient", 1, 35);
            "Message to Recipient 2" := CopyStr(VendorLedgerEntry."Message to Recipient", 36, 70);
            "Document No." := VendorLedgerEntry."Document No.";
            "Applies-to Ext. Doc. No." := VendorLedgerEntry."Applies-to Ext. Doc. No.";
            "Short Advice" := VendorLedgerEntry."Applies-to Ext. Doc. No.";
            "Line No." := LineNo;
            "Payment Reference" := VendorLedgerEntry."Payment Reference";
            if PaymentMethod.Get(VendorLedgerEntry."Payment Method Code") then
                "Data Exch. Line Def Code" := PaymentMethod."Pmt. Export Line Definition";
            "Recipient Creditor No." := VendorLedgerEntry."Creditor No.";
    
            ***OnBeforeInsertPmtExportDataJnlFromVendorLedgerEntry(TempPaymentExportData, VendorLedgerEntry, GeneralLedgerSetup);***

            Insert(true);
        end;
    end;

where that event is:

    [IntegrationEvent(false, false)]
    [Scope('OnPrem')]
    procedure OnBeforeInsertPmtExportDataJnlFromVendorLedgerEntry(var PaymentExportData: Record "Payment Export Data"; VendorLedgerEntry: Record "Vendor Ledger Entry"; GeneralLedgerSetup: Record "General Ledger Setup")
    begin
    end;

***

Please add an equivalent event to `codeunit 1208 "Pmt Export Mgt Cust Ledg Entry"`, emitted by `PreparePaymentExportDataVLE()`, to be published as `OnBeforeInsertPmtExportDataJnlFromCustLedgerEntry()`

    procedure PreparePaymentExportDataCLE[...]
    begin
        [...]
            "Recipient Name" := CopyStr(Customer.Name, 1, 35);
            "Recipient Address" := CopyStr(Customer.Address, 1, 35);
            "Recipient City" := CopyStr(Customer."Post Code" + ' ' + Customer.City, 1, 35);
            "Transfer Date" := CustLedgerEntry."Posting Date";
            "Message to Recipient 1" := CopyStr(CustLedgerEntry."Message to Recipient", 1, 35);
            "Message to Recipient 2" := CopyStr(CustLedgerEntry."Message to Recipient", 36, 70);
            "Document No." := CustLedgerEntry."Document No.";
            "Applies-to Ext. Doc. No." := CustLedgerEntry."Applies-to Ext. Doc. No.";
            "Short Advice" := CustLedgerEntry."Applies-to Ext. Doc. No.";
            "Line No." := LineNo;
            if PaymentMethod.Get(CustLedgerEntry."Payment Method Code") then
                "Data Exch. Line Def Code" := PaymentMethod."Pmt. Export Line Definition";
    
            ***OnBeforeInsertPmtExportDataJnlFromCustLedgerEntry(TempPaymentExportData, CustLedgerEntry, GeneralLedgerSetup);***
    
            Insert(true);
        end;
    end;

like so:

(I'm not sure why the existing Vend/Cust events are `OnPrem` only? so I omit that and will search/open an existing Issue)

    [IntegrationEvent(false, false)]
    procedure OnBeforeInsertPmtExportDataJnlFromCustLedgerEntry(var PaymentExportData: Record "Payment Export Data"; CustLedgerEntry: Record "Customer Ledger Entry"; GeneralLedgerSetup: Record "General Ledger Setup")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
