### ISSUE TITLE
[Request for External/Cloud] Codeunits 1206/1207/1208: Pmt Export Mgt Gen Jnl Line / Vend / Cust Ledg Entry

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#8140]
This is a general request/question, but given the number of events/procedures - and perhaps the possibility of a simple reason they must be this way - I hope to get an informed answer, without having to ask/request for 10s or 100s of distinct symbols. Please attempt to do so 👍 

All/most public procedures and event publishers in these 3 Payment Export Management codeunits are marked as being for `OnPrem` only. Is this actually required? We would like to deliver our users the option to create payment files for upload/transfer elsewhere, regardless of whether or not they are using on-premise or in-cloud BC. It should be perfectly possible for BC to create a file on the server side and then send it to the client for download.

Please can `OnPrem` requirement be removed from all procedures and events that do not actually require it, so that these could be used in SaaS too?

Or is there some more fundamental reason that payment export is not possible from SaaS? I'm sure the idea is that we would use HTTP/XML/JSON to send electronic payments directly to web APIs, or suchlike, but the reality is that many, many users' banks are not that smart - and besides, we want to provide the option to our clients to produce bank files for later use.

**Comment by AlexanderYakunin** [comment]
We have legacy code here and therefore used 'OnPrem' to indicate this area is not yet designed for cloud use. Enabling for cloud cannot be done by simple remove of 'OnPrem', and we have no plans to do this in current design. Instead, this functionality will be updated consistently to provide cloud capabilities and extensibility. Please check our release plans to see when it will be possible.
