### ISSUE TITLE
[EventRequest] Table 18 Customer - OnBeforeUpdateCustomerBankAccounts

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#8141]
Please add a new event publisher to procedure `UpdateCustomerBankAccounts` as following:

```
    local procedure UpdateCustomerBankAccounts(UseFieldCaption: Text[250])
    // >> New publisher call
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateCustomerBankAccounts(Rec, IsHandled);
        if IsHandled then
            exit;
    // <<

        if not GuiAllowed then
            exit;
        CustBankAcc.SetRange("Customer No.", "No.");
        OnUpdateCustomerBankAccountsBeforeFindBankAccounts(Rec, CustBankAcc);
        if CustBankAcc.Find('-') then begin
```

New integration event:
```
    [IntegrationEvent(false,false)]
    local procedure OnBeforeUpdateCustomerBankAccounts(Rec: Record Customer; var IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
