### ISSUE TITLE
[Enum Request] Table 5901 "Service Item Line"

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#8142]
Please convert `field(43; "Document Type"; Option)` to an extensible enum.

**Comment by AlexanderYakunin** [comment]
This is already done

        field(43; "Document Type"; Enum "Service Document Type")
        {
            Caption = 'Document Type';
            Editable = false;
        }

**Comment by achim-t** [comment]
> This is already done

The change is not in BC 16.5.

**Comment by AlexanderYakunin** [comment]
We implement enum in actual vNext version (17.x in this case). We never add enums in PROD version (16.x in this case). All new enums will be available in 17.0.

**Comment by achim-t** [comment]
Ok, thanks for letting me know.
