### ISSUE TITLE
[Event Request] Table 23 Vendor - OnBeforeUpdateVendorBankAccounts

### ISSUE THREAD

**Issue by DOuderling** [microsoft/ALAppExtensions#8145]
Hello,

We want to use our own logic for function UpdateVendorBankAccounts in Vendor table:

CURRENT CODE:

    procedure UpdateVendorBankAccounts(UseFieldCaption: Text[250])
    begin
        if not GuiAllowed then
            exit;
        VendBankAcc.SetRange("Vendor No.", "No.");
        if VendBankAcc.Find('-') then begin
            if not Confirm(StrSubstNo(Text11000000, UseFieldCaption)) then
                exit;
            repeat
                VendBankAcc."Account Holder Name" := Name;
                VendBankAcc."Account Holder Address" := Address;
                VendBankAcc."Account Holder Post Code" := "Post Code";
                VendBankAcc."Account Holder City" := City;
                VendBankAcc."Acc. Hold. Country/Region Code" := "Country/Region Code";
                VendBankAcc.Modify();
            until VendBankAcc.Next = 0;
            Modify;
        end;
    end;

PROPOSED NEW CODE:

    procedure UpdateVendorBankAccounts(UseFieldCaption: Text[250])
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateVendorBankAccounts(Rec,IsHandled)
        if (not GuiAllowed) or IsHandled then
            exit;
        VendBankAcc.SetRange("Vendor No.", "No.");
        if VendBankAcc.Find('-') then begin
            if not Confirm(StrSubstNo(Text11000000, UseFieldCaption)) then
                exit;
            repeat
                VendBankAcc."Account Holder Name" := Name;
                VendBankAcc."Account Holder Address" := Address;
                VendBankAcc."Account Holder Post Code" := "Post Code";
                VendBankAcc."Account Holder City" := City;
                VendBankAcc."Acc. Hold. Country/Region Code" := "Country/Region Code";
                VendBankAcc.Modify();
            until VendBankAcc.Next = 0;
            Modify;
        end;
    end;

NEW EVENT PUBLISHER:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateVendorBankAccounts(var Vendor : Record Vendor; var IsHandled : Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
