### ISSUE TITLE
EventRequest XmlPort 1010 SEPA DD pain.008.001.02 fieldelement(Id; CompanyInformation."VAT Registration No.")

### ISSUE THREAD

**Issue by SjoerddeClippelaar** [microsoft/ALAppExtensions#8149]
Dear Microsoft,

We like to have the ability to have our own implementation of the fieldelement(Id; CompanyInformation."VAT Registration No.") in the XMLPort 1010. This concerning the Belgium Enterprise No. on the Company Information that we want to pass as the VAT Regitration No.

```
textelement(Id)
{
    textelement(OrgId)
    {
        textelement(Othr)
        {
            fieldelement(Id; VATRegNoEnterpriseNo) //new variable name for element Id
            //new start
            {
                trigger OnBeforePassField()
                begin
                    VATRegNoEnterpriseNo := CompanyInformation."VAT Registration No."
                    OnAfterOnBeforePassFieldVATRegistrationNo(CompanyInformation, VATRegNoEnterpriseNo);
                end;
            }
            //new end
        }
    }
}
```
New publisher in de XMLPort.

```
[IntegrationEvent(false, false)]
local procedure OnAfterOnBeforePassFieldVATRegistrationNo(var CompanyInformation: Record "Company Information"; var VATRegNoEnterpriseNo: Text)
begin
end;
```

**Comment by RomanZanizdra** [comment]
Hi @SjoerddeClippelaar .
This part is already localized in BE and uses "Enterprise No.". Do you still need the requested event?
                        textelement(Id)
                        {
                            textelement(OrgId)
                            {
                                textelement(Othr)
                                {
                                    fieldelement(Id; CompanyInformation."Enterprise No.")
                                    {
                                    }
                                }
                            }
                        }

**Comment by SjoerddeClippelaar** [comment]
Yes please. We want to have the BE localization and NL localization in 1 database. Thanks in advanced.

**Comment by SjoerddeClippelaar** [comment]
Hi @RomanZanizdra ,
What is the status of this issue?
Thanks in advanced.

**Comment by RomanZanizdra** [comment]
Hi @SjoerddeClippelaar .
It definitely will be in 17.1

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
