### ISSUE TITLE
Bug in CheckDimValue procedure (DimensionManagement codeunit)

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#8152]
Hi, I think there is a bug in the DimensionManagement codeunit!

```
    procedure CheckDimValue(DimCode: Code[20]; DimValCode: Code[20]): Boolean
    var
        DimVal: Record "Dimension Value";
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckDimValue(DimCode, DimValCode, Result, IsHandled);
        if IsHandled then
            exit;
      [...]
    end;
```

The variable Result is introduced to pass it when raising the OnBeforeCheckDimValue event. It's not used elsewhere in the procedure, so I'm assuming it is its sole purpose.

But exiting the procedure after the event is raised, the Result variable is forgotten, so after the custom code it can only ever return false.

The correct code should be:

```
        OnBeforeCheckDimValue(DimCode, DimValCode, Result, IsHandled);
        if IsHandled then
            exit(Result);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
