### ISSUE TITLE
[Event Extension] 303 "Finance Charge Memo Line" - OnValidateVATProdPostingGroupOnAfterVATPostingSetupGet

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#8155]
In our application we can store different VAT rates for each period. To get the right one we need an extension of the event.  

**Extension for Event OnValidateVATProdPostingGroupOnAfterVATPostingSetupGet**
```
    [IntegrationEvent(false, false)]
    local procedure OnValidateVATProdPostingGroupOnAfterVATPostingSetupGet(var VATPostingSetup: Record "VAT Posting Setup"; KeyDate: Date; PostingDate: Date)
    begin
    end;
```
**New Event call**
`OnValidateVATProdPostingGroupOnAfterVATPostingSetupGet(VATPostingSetup, 0D, FinChrgMemoHeader."Posting Date");`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
