### ISSUE TITLE
[New Event Request] Codeunit 8612 "Config. Template Management", OnAfterUpdateRecordWithSkipFields

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#8156]
[New Event Request] Codeunit 8612 "Config. Template Management", OnAfterUpdateRecordWithSkipFields

A new integration event is needed at the very end of the procedure UpdateRecordWithSkipFields:

    local procedure UpdateRecordWithSkipFields(ConfigTemplateHeader: Record "Config. Template Header"; var RecRef: RecordRef; SkipFields: Boolean; var TempSkipFields: Record "Field" temporary)
    begin
        if TestKeyFields(RecRef) then
            InsertTemplate(RecRef, ConfigTemplateHeader, SkipFields, TempSkipFields)
        else begin
            InsertRecordWithKeyFields(RecRef, ConfigTemplateHeader);
            if TestKeyFields(RecRef) then
                InsertTemplate(RecRef, ConfigTemplateHeader, SkipFields, TempSkipFields)
            else
                Error(NoSeriesErr, RecRef.Number, RecRef.Caption);
        end;
        OnAfterUpdateRecordWithSkipFields(ConfigTemplateHeader, RecRef, SkipFields, TempSkipFields)
    end;

**Integration Event:**

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateRecordWithSkipFields(ConfigTemplateHeader: Record "Config. Template Header"; var RecRef: RecordRef; SkipFields: Boolean; var TempSkipFields: Record "Field" temporary)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
