### ISSUE TITLE
[New Event Request] Table 36 Sales Header, OnBeforeUpdateOpportunity

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#8163]
[New Event Request] Table 36 Sales Header, OnBeforeUpdateOpportunity

We would need a new integration event at the very beginning of the local procedure UpdateOpportunity. This event needs to implement the Handled Pattern. The treatment of opportunities has been widely enhanced in a vertical, and the Exits and Errors thrown in the current procedure make it impossible to handle the enhancements in any other way but through a Handled Pattern.

    local procedure UpdateOpportunity()
    var
        Opp: Record Opportunity;
        OpportunityEntry: Record "Opportunity Entry";
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateOpportunity(SalesHeader, IsHandled);
        if IsHandled then
            exit;

        if not ("Opportunity No." <> '') or not ("Document Type" in ["Document Type"::Quote, "Document Type"::Order]) then
            exit;

**Integration Event:**

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateOpportunity(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
