### ISSUE TITLE
[External] GetHideValidationDialog in Service Header table

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#8165]
Hello, please add this procedure to the Service Header table to allow extensions to get the value of HideValidationDialog.

The same procedure is already present in Sales Header and Purchase Header.

```
    procedure GetHideValidationDialog(): Boolean
    begin
        exit(HideValidationDialog);
    end;
```

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
