### ISSUE TITLE
[New Event Request] Table 5767 "Warehouse Activity Line", OnBeforeSplitLinesOnBeforeTestAndError

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#8167]
[New Event Request] Table 5767 "Warehouse Activity Line", OnBeforeSplitLinesOnBeforeTestAndError

The procedure SplitLine starts with a few TestFields, Errors and FieldErrors. These need to be avoided or done differently, given an enhanced feature set by partner verticals. We need a Handled Pattern for this. This can be done in one of two ways: either by introducing a new integration event specific to this task, or by expanding an existing integration event. I will describe both variations; please, pick the one that you think is more suitable:

**FIRST POSSIBLE SOLUTION: New Integration Event**

    procedure SplitLine(var WhseActivLine: Record "Warehouse Activity Line")
    var
        NewWhseActivLine: Record "Warehouse Activity Line";
        LineSpacing: Integer;
        NewLineNo: Integer;
        IsHandled: Boolean;
    begin
        OnBeforeSplitLines(WhseActivLine);

        IsHandled := false;
        OnBeforeSplitLinesOnBeforeTestAndError(WhseActivLine, IsHandled);
        if not IsHandled then begin
            WhseActivLine.TestField("Qty. to Handle");
            if WhseActivLine."Activity Type" = WhseActivLine."Activity Type"::"Put-away" then begin
                if WhseActivLine."Breakbulk No." <> 0 then
                    Error(Text007);
                WhseActivLine.TestField("Action Type", WhseActivLine."Action Type"::Place);
            end;
            if WhseActivLine."Qty. to Handle" = WhseActivLine."Qty. Outstanding" then
                WhseActivLine.FieldError(
                "Qty. to Handle", StrSubstNo(Text003, WhseActivLine.FieldCaption("Qty. Outstanding")));
        end;

        NewWhseActivLine := WhseActivLine;
        NewWhseActivLine.SetRange("No.", WhseActivLine."No.");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSplitLinesOnBeforeTestAndError(var WhseActivLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
    begin
    end;

**SECOND POSSIBLE SOLUTION: Extending an Existing Integration Event**

    procedure SplitLine(var WhseActivLine: Record "Warehouse Activity Line")
    var
        NewWhseActivLine: Record "Warehouse Activity Line";
        LineSpacing: Integer;
        NewLineNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSplitLines(WhseActivLine, IsHandled);

        if not IsHandled then begin
            WhseActivLine.TestField("Qty. to Handle");
            if WhseActivLine."Activity Type" = WhseActivLine."Activity Type"::"Put-away" then begin
                if WhseActivLine."Breakbulk No." <> 0 then
                    Error(Text007);
                WhseActivLine.TestField("Action Type", WhseActivLine."Action Type"::Place);
            end;
            if WhseActivLine."Qty. to Handle" = WhseActivLine."Qty. Outstanding" then
                WhseActivLine.FieldError(
                "Qty. to Handle", StrSubstNo(Text003, WhseActivLine.FieldCaption("Qty. Outstanding")));
        end;

        NewWhseActivLine := WhseActivLine;
        NewWhseActivLine.SetRange("No.", WhseActivLine."No.");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSplitLines(var WarehouseActivityLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
