### ISSUE TITLE
[Event Request] OnBeforeCheckDimValuePosting in Serv-Documents Mgt.

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#8168]
Hello, please consider adding this event publisher to the Serv-Documents Mgt. codeunit:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDimValuePosting(var ServiceLine2: Record "Service Line")
    begin
    end;
```

and raise it at the beginning of the CheckDimValuePosting procedure:

```
    local procedure CheckDimValuePosting(var ServiceLine2: Record "Service Line")
    var
        TableIDArr: array[10] of Integer;
        NumberArr: array[10] of Code[20];
    begin
        OnBeforeCheckDimValuePosting(ServiceLine2);
        [...]
    end;
```

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
