### ISSUE TITLE
[ParameterRequest] Table 81 Gen. Ledger Entry - OnGetCustLedgerEntryOnAfterAssignCustomerNo

### ISSUE THREAD

**Issue by aaugustijn** [microsoft/ALAppExtensions#8169]
Please pass the parameter `CustLedgerEntry` as reference like so:

Old integration event:
```
    [IntegrationEvent(false, false)]
    local procedure OnGetCustLedgerEntryOnAfterAssignCustomerNo(var GenJournalLine: Record "Gen. Journal Line"; CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;
```

New integration event:
```
    [IntegrationEvent(false, false)]
    local procedure OnGetCustLedgerEntryOnAfterAssignCustomerNo(var GenJournalLine: Record "Gen. Journal Line"; var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
Why?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by aaugustijn** [comment]
Hi,

We are just getting our codebase working on CU4 right now, and I came across this request.
It seems that the implementation of this publisher does not pass the parameter `CustLedgerEntry` as a reference, as requested.
We need that functionality to modify a field in that record.
Is there a reason for this not being the case, or was it simply a mistake?

Best regards

**Comment by AlexanderYakunin** [comment]
16.4 code complete was 28/07, you can expect to get this in 16.5 only.
