### ISSUE TITLE
[Bug] Error while "Save as Template" on e.g. Customer

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#8173]
Hello Team,

to reproduce the error, take the following steps:
Navigate to Configuration Templates and add a new one
Use 'Z999999999' as Code, set Table Id to 18
Navigate to any Customer Card
Click Actions - Functions - Save as Template
Business Central will greet you with the error "The length of the string is 11, but it must be less than or equal to 10 characters. Value: Z1000000000"
Bug discovered on BC13CU4 but it is still in the sandbox of Version: DE Business Central 16.3 (Platform 16.0.14073.15022 + Application 16.3.14085.14287)
Error Code: StringLengthExceeded:TargetInvocation
Error Callstack: "Mini Customer Template"(Table 1300).SaveAsTemplate line 8 - Base Application by Microsoft
"Customer Card"(Page 21)."SaveAsTemplate - OnAction"(Trigger) line 4 - Base Application by Microsoft

Kind regards
sauerkreut

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
