### ISSUE TITLE
Expose functions NAV2018 for mailing 2

### ISSUE THREAD

**Issue by Chingyz** [Microsoft/ALAppExtensions#818]
@IhorHandziuk @JesperSchulz, Unfortunately the functions SendEmailToVendor, SendEmailToCust (Tab77) and CreateMessage(Cod397) are not external in the new update (CU13).
Can you make the functions above and function 'Send' (Cod397) external (NAV2018 NL)?

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for submitting your request. Unfortunately we cannot help you in this repository. Issues reported in this repository will only be addressed in the upcoming major release, as certain processes apply for changing code in versions released to market. For more information on our branching strategy, please read here: [AL Developer Previews, multiple releases, and GitHub](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github). 
For any changes to released versions (such as NAV2018) you should contact our Support team. You can open Support Request to CSS through the [PartnerSource portal](https://mbs2.microsoft.com/Support/SupportRequestStep1.aspx) or contact your Service Account Manager (SAM) in the local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you step-by-step on how to open a support request or how to get credentials if this is the first time you or your company are engaging Support.
