### ISSUE TITLE
[Change Request] Codeunit 5763 "Whse.-Post Shipment" – Procedure  “CreateWhseJnlLine”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8183]
Could we please have the existing procedure “CreateWhseJnlLine”, Codeunit 5763 "Whse.-Post Shipment” be set to global?

```

*** start old code ***
    //   local procedure CreateWhseJnlLine(var WhseJnlLine: Record "Warehouse Journal Line"; PostedWhseShptLine: Record "Posted Whse. Shipment Line")
*** stop old code ***
*** start new code ***
    procedure CreateWhseJnlLine(var WhseJnlLine: Record "Warehouse Journal Line"; PostedWhseShptLine: Record "Posted Whse. Shipment Line")
*** stop new code ***
    var
        SourceCodeSetup: Record "Source Code Setup";
    begin
        with PostedWhseShptLine do begin
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
