### ISSUE TITLE
[Change Request] Codeunit 5771 "Whse.-Sales Release" – Procedure  “CreateWhseRqst”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8185]
Could we please have the existing procedure “CreateWhseRqst”, Codeunit 5771 "Whse.-Sales Release” be set to global?
```

*** start old code ***
    //local procedure CreateWhseRqst(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; WhseType: Option Inbound,Outbound)
*** stop old code ***
*** start new code ***
    procedure CreateWhseRqst(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; WhseType: Option Inbound,Outbound)
*** stop new code ***
    var
        SalesLine2: Record "Sales Line";
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
