### ISSUE TITLE
[Event Request] Codeunit 5771 "Whse.-Sales Release" – New Event  “OnCreateWhseRqstOnBeforeCheckConditions”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8186]
Could we please have a new publisher “OnCreateWhseRqstOnBeforeCheckConditions” in Function “CreateWhseRqst”, Codeunit 5771 "Whse.-Sales Release” including a handled pattern?

```
    local procedure CreateWhseRqst(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; WhseType: Option Inbound,Outbound)
    var
        SalesLine2: Record "Sales Line";
*** start new code ***
        IsHandled: Boolean;
        ResultValue: Boolean;
*** stop new code ***
    begin
*** start new code ***
        ResultValue := false;
        IsHandled := false;
        OnCreateWhseRqstOnBeforeCheckConditions(Location, SalesLine, WhseType, ResultValue, IsHandled);
        if ishandled and not (resultvalue) then begin
            exit;
        end;
*** stop new code ***
        if ((WhseType = WhseType::Outbound) and
            (Location.RequireShipment(SalesLine."Location Code") or
             Location.RequirePicking(SalesLine."Location Code"))) or
           ((WhseType = WhseType::Inbound) and
            (Location.RequireReceive(SalesLine."Location Code") or
             Location.RequirePutaway(SalesLine."Location Code")))
*** start new code ***
           or ResultValue
*** stop new code ***
        then begin
            SalesLine2.Copy(SalesLine);
…
*** start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnCreateWhseRqstOnBeforeCheckConditions(var Location: Record Location; SalesLine: Record "Sales Line"; WhseType: Option Inbound,Outbound; var ResultValue: boolean; var IsHandled: Boolean)
    begin
    end;
*** stop new code ***```

**Comment by AlexanderYakunin** [comment]
Do you need to use alternative condition instead? If this case we'd better move this to procedure and add OnAfter event to change result?

        if ((WhseType = WhseType::Outbound) and
            (Location.RequireShipment(SalesLine."Location Code") or
             Location.RequirePicking(SalesLine."Location Code"))) or
           ((WhseType = WhseType::Inbound) and
            (Location.RequireReceive(SalesLine."Location Code") or
             Location.RequirePutaway(SalesLine."Location Code")))

**Comment by ttaeufer** [comment]
Thank you for your question. You are right.
We need an alternative condition instead of this code:

        if ((WhseType = WhseType::Outbound) and
            (Location.RequireShipment(SalesLine."Location Code") or
             Location.RequirePicking(SalesLine."Location Code"))) or
           ((WhseType = WhseType::Inbound) and
            (Location.RequireReceive(SalesLine."Location Code") or
             Location.RequirePutaway(SalesLine."Location Code")))
        then begin

But sorry, I’m not quit sure that I got you right how to manage this request.
If you mean to change the standard code in a way like given below, it would be sufficient  to handle our request and it is much more elegant than my suggestion.

        DoCreateWhseRequest :=
            ((WhseType = WhseType::Outbound) and
            (Location.RequireShipment(SalesLine."Location Code") or
             Location.RequirePicking(SalesLine."Location Code"))) or
            ((WhseType = WhseType::Inbound) and
            (Location.RequireReceive(SalesLine."Location Code") or
             Location.RequirePutaway(SalesLine."Location Code")));

        OnAfterAssignDoCreateWhseRequest(DoCreateWhseRequest);

        if DoCreateWhseRequest then begin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
