### ISSUE TITLE
[Event Request] Page 55 -  Purch. Invoice Subform

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/ALAppExtensions#82]
we need new publisher on function RedistributeTotalsOnAfterValidate

```
LOCAL RedistributeTotalsOnAfterValidate()
CurrPage.SAVERECORD;

DocumentTotals.PurchaseRedistributeInvoiceDiscountAmounts(Rec,VATAmount,TotalPurchaseLine);

//NEW CODE BEGIN>>
OnAfterRedistributeDiscAmounts(Rec)
//NEW CODE END<<

CurrPage.UPDATE;
```
with new publisher
`LOCAL [IntegrationEvent] OnAfterRedistributeDiscAmounts(PurchaseLine : Record "Purchase Line")`

**Comment by AlexanderYakunin** [comment]
Please check latest available D365 BC build and update your ask as code structure have been changed here

**Comment by AlexanderYakunin** [comment]
OnAfterPurchaseRedistributeInvoiceDiscountAmounts event can be implemented in COD57.
