### ISSUE TITLE
Event Request] Application “Tests-VAT” Codeunit 134053 "ERM VAT Tool - Serv. Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8209]
[Event Request]Application “Tests-VAT”, 134053 "ERM VAT Tool - Serv. Doc"

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize:
![pic1](https://user-images.githubusercontent.com/45795262/88938192-624e3f80-d285-11ea-90bd-efa2797bc54a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
