### ISSUE TITLE
[Event Request] Application “Tests-Resource” Codeunit 136500 "UT Time Sheets"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8211]
[Event Request]Application “Tests-Resource”, 136500 "UT Time Sheets"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/88938451-b1947000-d285-11ea-9099-8bb1baff62ad.png)
![pic2](https://user-images.githubusercontent.com/45795262/88938458-b3f6ca00-d285-11ea-9f56-14d16f3e36ae.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
