### ISSUE TITLE
[Event Request] Application “Tests-Misc” Codeunit 135000 "Error Message Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8212]
[Event Request]Application “Tests-Misc”, 135000 "Error Message Tests"

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize:
![pic1](https://user-images.githubusercontent.com/45795262/88938594-d4bf1f80-d285-11ea-96f1-181746a21202.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
