### ISSUE TITLE
[Event Request] Application “Tests-Job” Codeunit 136360 "UT T Service Line Usage Link"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8213]
[Event Request]Application “Tests-Job”, 136360 "UT T Service Line Usage Link"

Could you please insert the OnTestInitialize Event at the beginning of procedure Setup. Or insert a new initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/88938726-f7513880-d285-11ea-9849-ce61cd42c9c9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
