### ISSUE TITLE
[Event Request] Application “Tests-ERM” Codeunit 136142 "Service Warehouse Integration"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8214]
[Event Request]Application “Tests-ERM”, 136142 "Service Warehouse Integration"

Could you please insert the OnTestInitialize Event at the beginning each test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/88938851-1b147e80-d286-11ea-87f2-5c96a4ab47b0.png)
![pic2](https://user-images.githubusercontent.com/45795262/88938855-1cde4200-d286-11ea-8115-58866e054160.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
