### ISSUE TITLE
[Event Request] Application “Tests-ERM” Codeunit 136100 "Service Contract"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8215]
[Event Request]Application “Tests-ERM”, 136100 "Service Contract"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/88939010-4f883a80-d286-11ea-821e-5d1f1aaf3a04.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
