### ISSUE TITLE
[Event Request] Application “Tests-ERM” Codeunit 134149 "ERM Intrastat Propagation"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8216]
[Event Request]Application “Tests-ERM”, 134149 "ERM Intrastat Propagation"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/88939113-721a5380-d286-11ea-82bf-aa56033df566.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
