### ISSUE TITLE
[Event Request] Application “Tests-ERM” Codeunit 134027 "ERM Invoice Discount And VAT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8217]
[Event Request]Application “Tests-ERM”, 134027 "ERM Invoice Discount And VAT"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure (or a procedure called by it):
![pic1](https://user-images.githubusercontent.com/45795262/88939253-94ac6c80-d286-11ea-8365-fe3a1fc89332.png)

**Comment by AlexanderYakunin** [comment]
This is already done

**Comment by JoergPernberg** [comment]
Not for all test procedures. Example: AmountIncludingVATOnPurchaseLineWithEnablePricesIncludingVAT
In this procedure the event is not raised.

**Comment by JoergPernberg** [comment]
News for this event request? Still missing the OnTestInitialize for some tests in this codeunit in 17.1.

**Comment by JoergPernberg** [comment]
@AlexanderYakunin,
anything new on this event request? The Initialize function is still missing in the procedure AmountIncludingVATOnPurchaseLineWithEnablePricesIncludingVAT

**Comment by StanPesotskiy** [comment]
It was done in Master but was not ported down to 17.x. We will do this.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
