### ISSUE TITLE
[Event Request] OnBeforeGetDimensionSetID in codeunit DimensionManagement

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#8222]
Hello, could you please add an event like this one to the DimensionManagement codeunit?

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDimensionSetID(var TempDimSetEntry: Record "Dimension Set Entry")
    begin
    end;
```

It should be raised in the GetDeltaDimSetID procedure:

```
    procedure GetDeltaDimSetID(DimSetID: Integer; NewParentDimSetID: Integer; OldParentDimSetID: Integer): Integer
    var
        [...]
    begin
        [...]

        OnBeforeGetDimensionSetID(TempDimSetEntry);
        exit(GetDimensionSetID(TempDimSetEntry));
    end;
```

I'm not fond of the name, so here's hoping you'll find a better one.

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
