### ISSUE TITLE
[Event Request] OnBeforeEditDimSetEntriesRunmodal in codeunit DimensionManagement

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#8223]
Hello, please publish this event in the DimensionManagement codeunit:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeEditDimSetEntriesRunmodal(var EditDimSetEntries: Page "Edit Dimension Set Entries")
    begin
    end;
```

it should be raised in every overload of the EditDimensionSet procedure:

```
    procedure EditDimensionSet(DimSetID: Integer; NewCaption: Text[250] [...]): Integer
    var
        DimSetEntry: Record "Dimension Set Entry";
        EditDimSetEntries: Page "Edit Dimension Set Entries";
        NewDimSetID: Integer;
        IsHandled: Boolean;
    begin
        [...]
        EditDimSetEntries.SetTableView(DimSetEntry);
        EditDimSetEntries.SetFormCaption(NewCaption);
        OnBeforeEditDimSetEntriesRunmodal(EditDimSetEntries);
        EditDimSetEntries.RunModal;
        [...]
    end;
```

Thank you so much!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
