### ISSUE TITLE
[Event Request] OnBeforeDimValRunmodal in codeunit DimensionManagement

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#8224]
Hello, please publish this event in the DimensionManagement codeunit:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDimValRunmodal(var DimVal: Record "Dimension Value")
    begin
    end;
```

This should be raised in the LookupDimValueCode procedure:

```
    procedure LookupDimValueCode(FieldNumber: Integer; var ShortcutDimCode: Code[20])
    var
        [...]
    begin
        [...]
        DimVal.SetRange("Dimension Code", GLSetupShortcutDimCode[FieldNumber]);
        DimVal."Dimension Code" := GLSetupShortcutDimCode[FieldNumber];
        DimVal.Code := ShortcutDimCode;
        OnBeforeDimValRunmodal(DimVal);
        if PAGE.RunModal(0, DimVal) = ACTION::LookupOK then begin
            [...]
        end;
    end;
```

Thanks so much!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
