### ISSUE TITLE
[Enum-Request] "Document Type" on TAB900 "Assembly Header" should be Enum

### ISSUE THREAD

**Issue by alphaxandra** [microsoft/ALAppExtensions#8225]
Hi

I'm trying to transfer field from "Assembly Header" to "Assembly-to Order Link", but fields "Assembly Document Type" from "Assembly-to Order Link"and "Document Type" from "Assembly Header" have different types; enum, option respectively.

I'm requesting that the option field "document Type" is converted to an enum.

![CopyDocumentMgt CodeUnit al - workspace (Workspace) - Visual Studio Code 31_07_2020 12_34_05 (2)](https://user-images.githubusercontent.com/69038648/89027445-cecf4a00-d32a-11ea-9d92-764688009bcb.png)

Best regards,
Alexandra

**Comment by AlexanderYakunin** [comment]
This is already corrected

**Comment by alphaxandra** [comment]
On which version? "Document Type" is still an Option field of "Assembly Header" on V16. See below

![image](https://user-images.githubusercontent.com/69038648/89626075-20cb1f00-d899-11ea-9779-6eec96fbc63a.png)

**Comment by alphaxandra** [comment]
Update: Fixed the warning by writing this:

![image](https://user-images.githubusercontent.com/69038648/89632367-5d4f4880-d8a2-11ea-9d06-836a2c759901.png)
