### ISSUE TITLE
[Event Requests] Codeunit 260 Document-Mailing: GetToAddressFromCustomer() and GetToAddressFromVendor()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#8226]
We need to use different email addresses than standard to send documents, e.g. for clients who use standard Email for a general contact but must send invoices to accounts contacts.

***

Please add event publishers using the handled pattern as highlighted:

    procedure GetToAddressFromCustomer(BillToCustomerNo: Code[20]): Text[250]
    var
        Customer: Record Customer;
        ToAddress: Text;
    begin
        // *** start
        OnBeforeGetToAddressFromCustomer(BillToCustomerNo, ToAddress, IsHandled);

        if IsHandled then
            exit(ToAddress);
        // end ***

        if Customer.Get(BillToCustomerNo) then
            ToAddress := Customer."E-Mail";

        exit(ToAddress);
    end;

    procedure GetToAddressFromVendor(BuyFromVendorNo: Code[20]): Text[250]
    var
        Vendor: Record Vendor;
        ToAddress: Text;
    begin
        // *** start
        OnBeforeGetToAddressFromVendor(BuyFromVendorNo, ToAddress, IsHandled);

        if IsHandled then
            exit(ToAddress);
        // end ***

        if Vendor.Get(BuyFromVendorNo) then
            ToAddress := Vendor."E-Mail";

        exit(ToAddress);
    end;

***

where the event publishers are declared as

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetToAddressFromCustomer(BillToCustomerNo: Code[20]; var ToAddress: Text[250]; var IsHandled: Boolean);
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetToAddressFromVendor(BuyFromVendorNo: Code[20]; var ToAddress: Text[250]; var IsHandled: Boolean);

***

We'd also like the ability to change the receiving email depending on the type of document sent, but that seems like a larger request and must start in Codeunit 452 by the looks of it. The events requested here will at least let all sent documents go to a custom address field.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
