### ISSUE TITLE
[Event Requests] OnBeforeInsertInvLineFromRetShptLineBeforeInsertTextLine in Return Shipment Line

### ISSUE THREAD

**Issue by FabianBigler** [microsoft/ALAppExtensions#8227]
We need this event in order to achieve the same effect as on table 121 - Purch. Rcpt. Line: to change the text line's description before it is being inserted.

The event should be raised on this line:
```
IF PurchLine."Return Shipment No." <> "Document No." THEN BEGIN
  PurchLine.INIT;
  PurchLine."Line No." := NextLineNo;
  PurchLine."Document Type" := TempPurchLine."Document Type";
  PurchLine."Document No." := TempPurchLine."Document No.";
  PurchLine.Description := STRSUBSTNO(Text000,"Document No.");
 //New line to insert (event to be raised):
  OnBeforeInsertInvLineFromRetShptLineBeforeInsertTextLine (Rec,PurchLine,NextLineNo);
  PurchLine.INSERT;
  NextLineNo := NextLineNo + 10000;
END;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
