### ISSUE TITLE
Check spelling

### ISSUE THREAD

**Issue by SShadowS** [microsoft/ALAppExtensions#8228]
https://github.com/microsoft/ALAppExtensions/blob/bac4247e472d70056c0847f0fba11aa048253c8d/Modules/System%20Tests/XML%20Validation/src/XmlValidationTest.Codeunit.al#L59

Assert.IsFalse(Result, 'Xml **shoud** not validate successfully.');

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
