### ISSUE TITLE
[Event Request] - Table 77 Report Selections

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#8229]
Please enhance event OnBeforeSaveReportAsPDF, and pass parameters ReportID and LayoutCode by reference.

[IntegrationEvent(false, false)]
local procedure OnBeforeSaveReportAsPDF(**var** ReportID: Integer; RecordVariant: Variant; **var** LayoutCode: Code[20]; var IsHandled: Boolean; FilePath: Text[250])
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
