### ISSUE TITLE
[Event Request] Table 904 OnRollUpPriceOnBeforeFindSalesLinePrice

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8230]
We Need an additional Parameter AsmLine in OnRollUpPriceOnBeforeFindSalesLinePrice because this trigger is called for every AsmLine and we Need to update CompSalesLine with individual data from AsmLine:

old:
local procedure OnRollUpPriceOnBeforeFindSalesLinePrice(var SalesHeader: Record "Sales Header"; var CompSalesLine: Record "Sales Line")
new:
local procedure OnRollUpPriceOnBeforeFindSalesLinePrice(var SalesHeader: Record "Sales Header"; var CompSalesLine: Record "Sales Line"; AsmLine: Record "Assembly Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
