### ISSUE TITLE
[Event Request] Codeunit 90 OnCheckAssocOrderLinesOnBeforeCheckOrderLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8231]
We Need VAR PurchaseLine as Parameter in OnCheckAssocOrderLinesOnBeforeCheckOrderLine to upodate the purchaseline with individual values:

old:
local procedure OnCheckAssocOrderLinesOnBeforeCheckOrderLine(PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; SalesOrderLine: Record "Sales Line")
new:
local procedure OnCheckAssocOrderLinesOnBeforeCheckOrderLine(PurchaseHeader: Record "Purchase Header"; VAR PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; SalesOrderLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
