### ISSUE TITLE
[Event Request] Table ATO Sales Buffer 

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8233]
We Need four new Events in table "ATO Sales Buffer ":

procedure UpdateBufferWithComp(CompATOSalesBuffer: Record "ATO Sales Buffer"; ProfitPct: Decimal; IsTotal: Boolean)
    begin
        Init;
        if IsTotal then
            Type := Type::"Total Assembly"
        else
            Type := Type::Assembly;
        "Order No." := '';
        "Item No." := CompATOSalesBuffer."Item No.";
        if not IsTotal then
            "Parent Item No." := CompATOSalesBuffer."Parent Item No."
        else
            "Parent Item No." := '';
        if Find then begin
            Quantity += CompATOSalesBuffer.Quantity;
            "Sales Cost" += CompATOSalesBuffer."Sales Cost";
            "Sales Amount" += CalcSalesAmt(CompATOSalesBuffer."Sales Cost", ProfitPct);
            "Profit %" := CalcSalesProfitPct("Sales Cost", "Sales Amount");
            ++++++++++++++++++++++++++++++
             OnBeforeATOSalesBufferModifyfromCompATOBuffer(VAR rec; CompATOSalesBuffer: Record "ATO Sales Buffer");
             -------------------------------------------------
            Modify;
            exit;
        end;

        Quantity := CompATOSalesBuffer.Quantity;
        "Sales Cost" := CompATOSalesBuffer."Sales Cost";
        "Sales Amount" := CalcSalesAmt(CompATOSalesBuffer."Sales Cost", ProfitPct);
        "Profit %" := ProfitPct;
            ++++++++++++++++++++++++++++++
             OnBeforeATOSalesBufferInsertfromCompATOBuffer(VAR rec; CompATOSalesBuffer: Record "ATO Sales Buffer");
             -------------------------------------------------
        Insert;
    end;

procedure UpdateBufferWithItemLedgEntry(ItemLedgEntry: Record "Item Ledger Entry"; IsTotal: Boolean)
    begin
        ItemLedgEntry.CalcFields("Cost Amount (Expected)", "Cost Amount (Actual)", "Sales Amount (Actual)", "Sales Amount (Expected)");

        Init;
        "Item No." := ItemLedgEntry."Item No.";
        "Order No." := '';
        "Parent Item No." := '';
        case ItemLedgEntry."Entry Type" of
            ItemLedgEntry."Entry Type"::Sale:
                if IsTotal then
                    Type := Type::"Total Sale"
                else begin
                    Type := Type::Sale;
                    "Order No." := FindATO(ItemLedgEntry);
                end;
            ItemLedgEntry."Entry Type"::"Assembly Consumption":
                begin
                    if IsTotal then
                        Type := Type::"Total Assembly"
                    else
                        Type := Type::Assembly;
                    "Parent Item No." := ItemLedgEntry."Source No.";
                end;
        end;
        if Find then begin
            Quantity += -ItemLedgEntry.Quantity;
            "Sales Cost" += -(ItemLedgEntry."Cost Amount (Expected)" + ItemLedgEntry."Cost Amount (Actual)");
            "Sales Amount" += ItemLedgEntry."Sales Amount (Actual)" + ItemLedgEntry."Sales Amount (Expected)";
            "Profit %" := CalcSalesProfitPct("Sales Cost", "Sales Amount");
            ++++++++++++++++++++++++++++++
             OnBeforeATOSalesBufferModifyfromItemLedgEntry(VAR rec; ItemLedgEntry: Record "Item Ledger Entry");
             -------------------------------------------------
            Modify;
            exit;
        end;

        Quantity := -ItemLedgEntry.Quantity;
        "Sales Cost" := -(ItemLedgEntry."Cost Amount (Expected)" + ItemLedgEntry."Cost Amount (Actual)");
        "Sales Amount" := ItemLedgEntry."Sales Amount (Actual)" + ItemLedgEntry."Sales Amount (Expected)";
        "Profit %" := CalcSalesProfitPct("Sales Cost", "Sales Amount");
            ++++++++++++++++++++++++++++++
             OnBeforeATOSalesBufferInsertfromItemLedgEntry(VAR rec; ItemLedgEntry: Record "Item Ledger Entry");
             -------------------------------------------------
        Insert;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
