### ISSUE TITLE
codeunit 353 "Item Availability Forms Mgt" - OnBeforeShowItemAvailByEvent IncludeForecast

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#8234]
Could in codeunit 353 "Item Availability Forms Mgt" event `OnBeforeShowItemAvailByEvent` the parameter `IncludeForecast` also be passed through by VAR?
We would like to always view the forecast.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
