### ISSUE TITLE
[Event Request] Codeunit 80 OnSaveInvoiceSpecificationOnAfterUpdateTempTrackingSpecification

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8235]
We Need an additional Parameter TempInvoicingSpecification in OnSaveInvoiceSpecificationOnAfterUpdateTempTrackingSpecification in codeunit 80:

old:
local procedure OnSaveInvoiceSpecificationOnAfterUpdateTempTrackingSpecification(var TempTrackingSpecification: Record "Tracking Specification" temporary)
new:
local procedure OnSaveInvoiceSpecificationOnAfterUpdateTempTrackingSpecification(var TempTrackingSpecification: Record "Tracking Specification" temporary;TempInvoicingSpecification: Record "Tracking Specification" temporary);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
