### ISSUE TITLE
[EventRequest] OR [External] PAGE 9239 function DrillDown

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#8237]
Hi,
we would like to have in PAGE 9239 function DrillDown as **external** or **evented onBefore** with all included parameters that ItemBudgetManagement.BudgetDrillDown requires.
Also it should be the same for PAGE 9219 "Purch. Budget Overview Matrix"

**Comment by StanPesotskiy** [comment]
Hi @VladimirVeljovic
What scenario are you trying to enable?
Would it be enough if we make all parameters of BudgetDrillDown() that are global vars as Protected and add OnBeforeDrillDown() event passing the **Sender** page , **Rec**, and two local params **OnlyLines** and **ValueType**?

**Comment by VladimirVeljovic** [comment]
Hi Stan,

yes i think it will be enough. Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
