### ISSUE TITLE
Page 6510 - Function Scope Changes

### ISSUE THREAD

**Issue by abhishekv290691** [microsoft/ALAppExtensions#8238]
Please change the scope of the following functions to global in Page 6510

1.  WriteToDatabase
![image](https://user-images.githubusercontent.com/49511747/89374084-b2b61900-d72d-11ea-9f65-ca9b3a95a232.png)

2. UpdateUndefinedQty
![image](https://user-images.githubusercontent.com/49511747/89374162-ef821000-d72d-11ea-8cbc-f44271059e16.png)

3. IsorderToOrderBindingToTransfer
![image](https://user-images.githubusercontent.com/49511747/89374787-ac28a100-d72f-11ea-8646-e0bf8662e133.png)

**Comment by AlexanderYakunin** [comment]
Please provide additional information, are you going to extend this page and therefore can use protected procedures?

**Comment by abhishekv290691** [comment]
Yes we require it to extend the page and its functionality and the the moment these functions cannot be used due to their protected status.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
