### ISSUE TITLE
[Event Request] Codeunit 90 OnBeforeCreatePositiveEntry and OnBeforePostRevertedWarehouseEntry

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8241]
We Need two new Events in codeunit 90:

Codeunit 90:
local procedure RevertWarehouseEntry(var TempWhseJnlLine: Record "Warehouse Journal Line" temporary; JobNo: Code[20]; PostJobConsumptionBeforePurch: Boolean): Boolean
    var
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeRevertWarehouseEntry(TempWhseJnlLine, JobNo, PostJobConsumptionBeforePurch, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if PostJobConsumptionBeforePurch or (JobNo = '') or PositiveWhseEntrycreated then
            exit(false);

        with TempWhseJnlLine do begin
            "Entry Type" := "Entry Type"::"Negative Adjmt.";
            Quantity := -Quantity;
            "Qty. (Base)" := -"Qty. (Base)";
            "From Bin Code" := "To Bin Code";
            "To Bin Code" := '';
        end;
      +++++++++++++++++++++++++++  
      OnBeforePostRevertedWarehouseEntry(VAR TempWhseJnlLine: Record "Warehouse Journal Line" temporary);
      ------------------------------------------
        exit(true);
    end;

local procedure CreatePositiveEntry(WhseJnlLine: Record "Warehouse Journal Line"; JobNo: Code[20]; PostJobConsumptionBeforePurch: Boolean)
    begin
        if PostJobConsumptionBeforePurch or (JobNo <> '') then begin
            with WhseJnlLine do begin
                Quantity := -Quantity;
                "Qty. (Base)" := -"Qty. (Base)";
                "Qty. (Absolute)" := -"Qty. (Absolute)";
                "To Bin Code" := "From Bin Code";
                "From Bin Code" := '';
            end;
            //++++++++++++++++++++++++++++++
            OnBeforeCreatePositiveEntry(VAR WhseJnlLine: Record "Warehouse Journal Line");
            //----------------------------------------
            WhseJnlPostLine.Run(WhseJnlLine);
            PositiveWhseEntrycreated := true;
        end;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
