### ISSUE TITLE
Event OnBeforeGuiAllowed in Confirm Management not accessible 

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/ALAppExtensions#8243]
https://github.com/microsoft/ALAppExtensions/blob/bac4247e472d70056c0847f0fba11aa048253c8d/Modules/System/Confirm%20Management/src/ConfirmManagementImpl.Codeunit.al#L39

The Event OnBeforeGuiAllowed in the Confirm Management is not accessible because the Codeunit has set Access to Internal.
The event publisher should be moved to Codeunit 27 "Confirm Management"

**Comment by darjoo** [comment]
Hi @StefanMaron, 
What is the scenario you're trying to achieve with the event?

**Comment by StefanMaron** [comment]
In the function documentation is described that for testing it is possible to "overwrite" GuiAllowed
`/// Raises an event to be able to change the return of IsGuiAllowed function. Used for testing.`

I wanted to use it this way, but it es not possible as the codeunit is set to internal.

**Comment by darjoo** [comment]
@StefanMaron
Sorry for the late reply. But the event was added to allow us to test the module and not for partners to hook onto.
