### ISSUE TITLE
[Event Request] Pages "Blanket Sales Order Subform" and "Blanket Purchase Order Subform"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8245]
Please add IsCommentLine and IsBlankNumber to the existing trigger OnAfterUpdateEditableOnRow on Pages "Blanket Sales Order Subform" and "Blanket Purchase Order Subform" like it is realised on the other subpages (Sales and Purch and Return Subpages) as well:

    procedure UpdateEditableOnRow()
    begin
        IsCommentLine := Type = Type::" ";
        IsBlankNumber := IsCommentLine;

        CurrPageIsEditable := CurrPage.Editable;
        InvDiscAmountEditable := CurrPageIsEditable and not PurchasesPayablesSetup."Calc. Inv. Discount";

        OnAfterUpdateEditableOnRow(Rec, IsCommentLine, IsBlankNumber);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
