### ISSUE TITLE
[Event Request] codeunit 414 "Release Sales Document" – OnBeforeSalesLineFind

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8246]
[Event Request] codeunit 414 "Release Sales Document" – OnBeforeSalesLineFind

Can we please get a var extension in Publisher OnBeforeSalesLineFind for the record SalesHeader in the codeunit 414 "Release Sales Document"?

``` 
    // >>>>>>>>                    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineFind(var SalesLine: Record "Sales Line"; var SalesHeader: Record "Sales Header")
    begin
    end;
    // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
