### ISSUE TITLE
[EventPropertyRequest] GenJnlPostLine.Codeunit.al (codeunit 12 "Gen. Jnl.-Post Line") 

### ISSUE THREAD

**Issue by Wiechardt** [microsoft/ALAppExtensions#8247]
Hi Microsoft,

Please help us by adding below property on given event in GenJnlPostLine.Codeunit.al codeunit.

Existing Event Signature
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostDtldCVLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var AccNo: Code[20]; var Unapply: Boolean; var AdjAmount: array[4] of Decimal)
    begin
    end;

Requested Event Signature
    [IntegrationEvent(**true**, false)]
    local procedure OnBeforePostDtldCVLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var AccNo: Code[20]; var Unapply: Boolean; var AdjAmount: array[4] of Decimal)
    begin
    end;

Thanks,
Wiechardt

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
