### ISSUE TITLE
[EventPropertyRequest] GenJnlPostLine.Codeunit.al (codeunit 12 "Gen. Jnl.-Post Line")

### ISSUE THREAD

**Issue by Wiechardt** [microsoft/ALAppExtensions#8250]
Hi Microsoft,

Please help us by adding below property on given event in GenJnlPostLine.Codeunit.al codeunit.

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostCust(var GenJournalLine: Record "Gen. Journal Line"; Balancing: Boolean; var TempGLEntryBuf: Record "G/L Entry" temporary; var NextEntryNo: Integer; var NextTransactionNo: Integer)
    begin
    end;

    [IntegrationEvent(**true**, false)]
    local procedure OnAfterPostCust(var GenJournalLine: Record "Gen. Journal Line"; Balancing: Boolean; var TempGLEntryBuf: Record "G/L Entry" temporary; var NextEntryNo: Integer; var NextTransactionNo: Integer)
    begin
    end;

Thanks,
Wiechardt

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
