### ISSUE TITLE
CreateServiceLineWithQuantity in Library - Service should allow a decimal value for Quantity

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#8251]
In codeunit 131902 "Library - Service", the following procedure should be overloaded to allow decimal values for the quantity.

```
    procedure CreateServiceLineWithQuantity(var ServiceLine: Record "Service Line"; ServiceHeader: Record "Service Header"; Type: Option; No: Code[20]; Quantity: Integer)
    begin
        CreateServiceLine(ServiceLine, ServiceHeader, Type, No);
        ServiceLine.Validate(Quantity, Quantity);
        ServiceLine.Modify(true);
    end;
```

The Quantity field in the Service Line table is a decimal, so I should be able to test decimal values and not just integers.

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
