### ISSUE TITLE
[Event Request] COD 5704 TransferOrder-Post Shipment OnInsertTransShptLineOnBeforeInsertTransShptLine

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#8253]
In order to enable creating transfer shipment lines only for transfer lines that have a Qty. to Ship assigned we would request an event publisher with an ishandled parameter to make the insert of the transfer shipment line conditional (similar to OnPostSalesLineOnBeforeInsertInvoiceLine in COD 80 "Sales-Post"). 

Current Code
local procedure InsertTransShptLine(TransShptHeader: Record "Transfer Shipment Header")
begin
        OnBeforeInsertTransShptLine(TransShptLine, TransLine, SuppressCommit);
        TransShptLine.Insert();
        OnAfterInsertTransShptLine(TransShptLine, TransLine, SuppressCommit);
end;

Requested Code
local procedure InsertTransShptLine(TransShptHeader: Record "Transfer Shipment Header")
begin
        OnInsertTransShptLineOnBeforeInsertTransShptLine(TransferHeader, TransferLine, IsHandled);
        if not IsHandled then begin
                OnBeforeInsertTransShptLine(TransShptLine, TransLine, SuppressCommit);
                TransShptLine.Insert();
                OnAfterInsertTransShptLine(TransShptLine, TransLine, SuppressCommit);
        end;
end;

IntegrationEvent(false, false)]
local procedure OnInsertTransShptLineOnBeforeInsertTransShptLine(TransferHeader: Record "Transfer Header"; TransferLine: Record "Transfer Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
