### ISSUE TITLE
[Event Request] COD 5705 "TransferOrder-Post Receipt" InsertTransRcptLineOnBeforeInsertTransRcptLine

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#8254]
In order to enable creating transfer receipt lines only for transfer lines that have a Qty. to Receive assigned we would request an event publisher with an ishandled parameter to make the insert of the transfer receipt line conditional (similar to OnPostSalesLineOnBeforeInsertInvoiceLine in COD 80 "Sales-Post").

Current Code
local procedure InsertTransRcptLine(ReceiptNo: Code[20]; var TransRcptLine: Record "Transfer Receipt Line"; TransLine: Record "Transfer Line")
begin
    OnBeforeInsertTransRcptLine(TransRcptLine, TransLine, SuppressCommit);
    TransRcptLine.Insert();
    OnAfterInsertTransRcptLine(TransRcptLine, TransLine, SuppressCommit);
end;

Requested Code
local procedure InsertTransRcptLine(ReceiptNo: Code[20]; var TransRcptLine: Record "Transfer Receipt Line"; TransLine: Record "Transfer Line")
begin
    OnInsertTransRcptLineOnBeforeInsertTransRcptLine(TransferHeader, TransferLine, IsHandled);
    if not IsHandled then begin
        OnBeforeInsertTransRcptLine(TransRcptLine, TransLine, SuppressCommit);
        TransRcptLine.Insert();
        OnAfterInsertTransRcptLine(TransRcptLine, TransLine, SuppressCommit);
    end;
end;

IntegrationEvent(false, false)]
local procedure OnInsertTransRcptLineOnBeforeInsertTransRcptLine(TransferHeader: Record "Transfer Header"; TransferLine: Record "Transfer Line"; var IsHandled: Boolean)
begin
end;

**Comment by AlexanderYakunin** [comment]
We already have event with this possibility
