### ISSUE TITLE
Event Request in both Sales-Post and Purch.-Post Codeunit

### ISSUE THREAD

**Issue by sami3187** [microsoft/ALAppExtensions#8256]
Hi,
Requesting to add event in **PostItemLine** function both **Codeunit 80 Sales-Post**  and **codeunit 90 Purch.-Post** for BC 16.xx Version for next minor release to handle our custom program. 
Below screenshot for your reference the program to be added (See yellow highlighted) . the same program to be added for codeunit 90 Purch.-Post as well.

![image](https://user-images.githubusercontent.com/64240684/89559645-8b07a380-d848-11ea-95a9-5c963d0cbca4.png)

Thank you .

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
