### ISSUE TITLE
Event Request: Codeunit 226 CustEntry-Apply Posted Entries

### ISSUE THREAD

**Issue by sami3187** [microsoft/ALAppExtensions#8257]
Hi,
Pls add the following in event in **Codeunit 226 CustEntry-Apply Posted Entries**(see yellow highlighted in below screenshots) in upcoming minor release to handle custom filters. 

![image](https://user-images.githubusercontent.com/64240684/89707364-ce285a80-d99f-11ea-8736-fc66f4c8ccbc.png)

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
