### ISSUE TITLE
Field inconsistencies in NL Base Application

### ISSUE THREAD

**Issue by Avanti05** [microsoft/ALAppExtensions#8259]
In the Base Application for the NL artifact/image, the "Payment Method Code" field is missing in the "Purchase  Order" page and "Posted Purchase Invoice" page, when compared to Base Application for other localizations. 

As we have a dependency to these fields, I would like to request that they be added to the NL Base application in order for us to support the NL market.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
