### ISSUE TITLE
[Event Request] Table 38 procedure AddShipToAddress

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#8261]
Hi,

we need in event OnAfterAddShipToAddress to include boolean "ShowError" so we can hanle the event

![image](https://user-images.githubusercontent.com/53824412/89645602-6d732200-d8ba-11ea-920f-854535e598d0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
