### ISSUE TITLE
[Event Extension] Table 38 event OnAfterCopyAddressInfoFromOrderAddress

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#8262]
Hi,

in table OnAfterCopyAddressInfoFromOrderAddress we need additional parameter, var Record. Without that OrderAddr is useless.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
