### ISSUE TITLE
[Event Request] Table 38 fucntions HasBuyFromAddress, HasShipToAddress, HasPayToAddress

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#8263]
Hi, we need to handle this 3 functions in table 38 (HasBuyFromAddress, HasShipToAddress, HasPayToAddress) via events like:

    procedure HasBuyFromAddress(): Boolean
    begin
        **//>>
        OnBeforeHasBuyFromAddress(var Rec, returnValue, isHandled);
        if isHandled then
            exit; 
        //<<**
        case true of
            "Buy-from Address" <> '':
                exit(true);
            "Buy-from Address 2" <> '':
                exit(true);
            "Buy-from City" <> '':
                exit(true);
            "Buy-from Country/Region Code" <> '':
                exit(true);
            "Buy-from County" <> '':
                exit(true);
            "Buy-from Post Code" <> '':
                exit(true);
            "Buy-from Contact" <> '':
                exit(true);
        end;
    [IntegrationEvent(false, false)]
    local procedure OnBeforeHasBuyFromAddress(var Record: "Purchase Header", returnValue: Boolean, isHandled: Boolean;)
    begin
    end;

------------------------------------------
    procedure HasShipToAddress(): Boolean
    begin
        **//>>
        OnBeforeHasShipToAddress(var Rec, returnValue, isHandled);
        if isHandled then
            exit; 
        //<<**

    [IntegrationEvent(false, false)]
    local procedure OnBeforeHasShipToAddress(var Record: "Purchase Header", returnValue: Boolean, isHandled: Boolean;)
    begin
    end;
-------------------------------------------
    procedure HasPayToAddress(): Boolean
    begin
        **//>>
        OnBeforeHasPayToAddress(var Rec, returnValue, isHandled);
        if isHandled then
            exit; 
        //<<**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
