### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Prod. Order No." - OnValidate - OnValidateProdOrderNoOnBeforeDropShipmentError

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8265]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Prod. Order No." - OnValidate
Publisher Event: OnValidateProdOrderNoOnBeforeDropShipmentError
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                **IsHandled := false;
                OnValidateProdOrderNoOnBeforeDropShipmentError(Rec, IsHandled);
                if not IsHandled then**
                    if "Drop Shipment" then
                        Error(
                          Text001,
                          FieldCaption("Prod. Order No."), "Sales Order No.");
                AddOnIntegrMgt.ValidateProdOrderOnPurchLine(Rec);
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateProdOrderNoOnBeforeDropShipmentError(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
