### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function CheckAvailableCreditLimit - OnBeforeCheckAvailableCreditLimit

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8266]
We like to request the following Event:
Object: Database::"Sales Header"
Function: CheckAvailableCreditLimit
Publisher Event: OnBeforeCheckAvailableCreditLimit
Reason: To implement custom business logic
Where is the event placed:
procedure CheckAvailableCreditLimit(): Decimal
    var
        Customer: Record Customer;
        AvailableCreditLimit: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckAvailableCreditLimit(Rec, AvailableCreditLimit, IsHandled);
        if IsHandled then
            exit(AvailableCreditLimit);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckAvailableCreditLimit(var SalesHeader: Record "Sales Header"; var AvailableCreditLimit: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
