### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function "Requested Delivery Date" - OnValidate - OnValidateRequestedDeliveryDateOnBeforeCheckPromisedDeliveryDate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8267]
We like to request the following Event:
Object: Database::"Sales Header"
Function: "Requested Delivery Date" - OnValidate
Publisher Event: OnValidateRequestedDeliveryDateOnBeforeCheckPromisedDeliveryDate
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestStatusOpen;
                IsHandled := false;
                OnValidateRequestedDeliveryDateOnBeforeCheckPromisedDeliveryDate(Rec, IsHandled);
                if not IsHandled then
                    if "Promised Delivery Date" <> 0D then
                        Error(
                        Text028,
                        FieldCaption("Requested Delivery Date"),
                        FieldCaption("Promised Delivery Date"));
                if "Requested Delivery Date" <> xRec."Requested Delivery Date" then
                    UpdateSalesLinesByFieldNo(FieldNo("Requested Delivery Date"), CurrFieldNo <> 0);
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateRequestedDeliveryDateOnBeforeCheckPromisedDeliveryDate(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
