### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function CheckRetRcptRelation - OnBeforeCheckRetRcptRelation

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8268]
We like to request the following Event:
Object: Database::"Sales Line"
Function: CheckRetRcptRelation
Publisher Event: OnBeforeCheckRetRcptRelation
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckRetRcptRelation()
    var
        ReturnRcptLine: Record "Return Receipt Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckRetRcptRelation(Rec, IsHandled);
        if IsHandled then
            exit;
        ReturnRcptLine.Get("Return Receipt No.", "Return Receipt Line No.");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckRetRcptRelation(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
