### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function CheckShipmentRelation - OnBeforeCheckShipmentRelation

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8269]
We like to request the following Event:
Object: Database::"Sales Line"
Function: CheckShipmentRelation
Publisher Event: OnBeforeCheckShipmentRelation
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckShipmentRelation()
    var
        SalesShptLine: Record "Sales Shipment Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckShipmentRelation(Rec, IsHandled);
        if IsHandled then
            exit;
        SalesShptLine.Get("Shipment No.", "Shipment Line No.");
        if (Quantity * SalesShptLine."Qty. Shipped Not Invoiced") < 0 then
            FieldError("Qty. to Invoice", Text057);
        if Abs(Quantity) > Abs(SalesShptLine."Qty. Shipped Not Invoiced") then
            Error(Text058, SalesShptLine."Document No.");
        OnAfterCheckShipmentRelation(Rec, SalesShptLine);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckShipmentRelation(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
