### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function "Requested Delivery Date" - OnValidate - OnValidateRequestedDeliveryDateOnBeforeDeliveryDateError

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8271]
We like to request the following Event:
Object: Database::"Sales Line"
Function: "Requested Delivery Date" - OnValidate
Publisher Event: OnValidateRequestedDeliveryDateOnBeforeDeliveryDateError
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestStatusOpen();
                IsHandled := false;
                OnValidateRequestedDeliveryDateOnBeforeDeliveryDateError(SalesHeader, IsHandled);
                if not IsHandled then
                    if ("Requested Delivery Date" <> xRec."Requested Delivery Date") and
                    ("Promised Delivery Date" <> 0D)
                    then
                        Error(
                        Text028,
                        FieldCaption("Requested Delivery Date"),
                        FieldCaption("Promised Delivery Date"));
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateRequestedDeliveryDateOnBeforeDeliveryDateError(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
