### ISSUE TITLE
[Event Request] Database::"Transfer Header" - Function DeleteOneTransferOrder - OnBeforeDeleteOneTransferOrder

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8272]
We like to request the following Event:
Object: Database::"Transfer Header"
Function: DeleteOneTransferOrder
Publisher Event: OnBeforeDeleteOneTransferOrder
Reason: To implement custom business logic
Where is the event placed:
procedure DeleteOneTransferOrder(var TransHeader2: Record "Transfer Header"; var TransLine2: Record "Transfer Line")
    var
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        WhseRequest: Record "Warehouse Request";
        InvtCommentLine: Record "Inventory Comment Line";
        No: Code[20];
        IsHandled: Boolean;
    begin
        OnBeforeDeleteOneTransferOrder(TransHeader2, TransLine2, IsHandled);
        if IsHandled then
            exit;
        No := TransHeader2."No.";
        WhseRequest.SetRange("Source Type", DATABASE::"Transfer Line");
        WhseRequest.SetRange("Source No.", No);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteOneTransferOrder(var TransHeader2: Record "Transfer Header"; var TransLine2: Record "Transfer Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
