### ISSUE TITLE
[Event Request] Database::"Warehouse Activity Line" - Function ChangeUOMCode - OnBeforeChangeUOMCode

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8273]
We like to request the following Event:
Object: Database::"Warehouse Activity Line"
Function: ChangeUOMCode
Publisher Event: OnBeforeChangeUOMCode
Reason: To implement custom business logic
Where is the event placed:
procedure ChangeUOMCode(var WhseActivLine: Record "Warehouse Activity Line"; var WhseActivLine2: Record "Warehouse Activity Line")
    var
        IsHandled: Boolean;
    begin
        OnBeforeChangeUOMCode(WhseActivLine, WhseActivLine2, IsHandled);
        if IsHandled then
            exit;
        if "Breakbulk No." = 0 then
            if (Quantity <> "Qty. to Handle") or ("Qty. Handled" <> 0) then
                CreateNewUOMLine("Action Type", WhseActivLine, WhseActivLine2)
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeChangeUOMCode(var WhseActivLine: Record "Warehouse Activity Line"; var WhseActivLine2: Record "Warehouse Activity Line"; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
