### ISSUE TITLE
[Event Request] Database::"Warehouse Activity Line" - Function CheckBin - OnBeforeCheckBin

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8274]
We like to request the following Event:
Object: Database::"Warehouse Activity Line"
Function: CheckBin
Publisher Event: OnBeforeCheckBin
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckBin()
    var
        IsHandled: Boolean;
    begin
        OnBeforeCheckBin(Rec, Bin, IsHandled);
        if IsHandled then
            exit;
        GetLocation("Location Code");
        Location.TestField("Directed Put-away and Pick");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckBin(var Rec: Record "Warehouse Activity Line"; var Bin: Record Bin; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
