### ISSUE TITLE
[Event Request] Database::"Warehouse Receipt Line" - Function AutofillQtyToReceive - OnBeforeAutofillQtyToReceive

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8275]
We like to request the following Event:
Object: Database::"Warehouse Receipt Line"
Function: AutofillQtyToReceive
Publisher Event: OnBeforeAutofillQtyToReceive
Reason: To implement custom business logic
Where is the event placed:
procedure AutofillQtyToReceive(var WhseReceiptLine: Record "Warehouse Receipt Line")
    var
        IsHandled: Boolean;
    begin
        OnBeforeAutofillQtyToReceive(WhseReceiptLine, IsHandled);
	if IsHandled then
            exit;
        with WhseReceiptLine do begin
            if Find('-') then
                repeat
                    Validate("Qty. to Receive", "Qty. Outstanding");
                    OnAutoFillQtyToReceiveOnBeforeModify(WhseReceiptLine);
                    Modify;
                until Next = 0;
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeAutofillQtyToReceive(var WhseReceiptLine: Record "Warehouse Receipt Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
