### ISSUE TITLE
[Event Requests] Report 292 - "Copy Sales Document"

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#8276]
Hello.

We need to be able to affect the "Exact Cost Reversing Mandatory" in the OnPreReport trigger.

So in the OnPreReport trigger we need one new local variable:
**ExactCostRevMandatory : Boolean**

We need also one Publisher in the Report to handle this:
OnAfterExactCostRevMandatoryAssignment_u(DocType,DocNo,SalesHeader,ExactCostRevMandatory);
// Note that the last parameter is a VAR parameter - the new variable from above.
...
LOCAL [IntegrationEvent] OnAfterExactCostRevMandatoryAssignment_u(...)
...
In the OnPreReport we then need something similar to...

**OnPreReport()**
SalesSetup.GET;
_// >>T20-15890 MT.STB 05.08.2020 Conditional based exact cost reversing._
**ExactCostRevMandatory := SalesSetup."Exact Cost Reversing Mandatory";
OnAfterExactCostRevMandatoryAssignment_u(DocType,DocNo,SalesHeader,ExactCostRevMandatory);
CopyDocMgt.SetProperties(
  IncludeHeader,RecalculateLines,FALSE,FALSE,FALSE,ExactCostRevMandatory,FALSE);**
_// <<T20-15890 MT.STB 05.08.2020 Conditional based exact cost reversing._
CopyDocMgt.SetArchDocVal(DocNoOccurrence,DocVersionNo);
CopyDocMgt.CopySalesDoc(DocType,DocNo,SalesHeader);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
