### ISSUE TITLE
[Event Request] codeunit 7500 "Item Attribute Management" – OnInsertBufferedItemAttributeValueMappingOnBeforeItemAttributeValueMappingInsert

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#8277]
[Event Request] codeunit 7500 "Item Attribute Management" – OnInsertBufferedItemAttributeValueMappingOnBeforeItemAttributeValueMappingInsert

Can we please get a var extension in Publisher OnInsertBufferedItemAttributeValueMappingOnBeforeItemAttributeValueMappingInsert for the record ItemAttributeValueMapping in the codeunit 7500 "Item Attribute Management"?
This record is inserted after the Publisher and we have to assign values to it.

``` 
    // >>>>>>>>                    
    [IntegrationEvent(false, false)]
    local procedure OnInsertBufferedItemAttributeValueMappingOnBeforeItemAttributeValueMappingInsert(var TempItemAttributeValueToInsert: Record "Item Attribute Value" temporary; var ItemAttributeValueMapping: Record "Item Attribute Value Mapping")
    begin
    end;
    // <<<<<<<<  

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
