### ISSUE TITLE
Event Request: Table 81 Gen. Journal Line

### ISSUE THREAD

**Issue by sami3187** [microsoft/ALAppExtensions#8279]
Pls add the below event in Table 81 Gen. Journal Line in next minor CU to handle custom filters
1)Function name :SetApplyToAmount()
![image](https://user-images.githubusercontent.com/64240684/89825880-de029300-db87-11ea-9cf7-9de5b2f28bde.png)

2) Function Name: ValidateApplyRequirements()

![image](https://user-images.githubusercontent.com/64240684/89826479-e0192180-db88-11ea-943f-e3eaceffaf35.png)

3)Function Name: RenumberAppliesToID

![image](https://user-images.githubusercontent.com/64240684/89827052-b6acc580-db89-11ea-9903-b1106a2dd5d9.png)

4)Function Name: FindFirstCustLedgEntryWithAppliesToDocNo
![image](https://user-images.githubusercontent.com/64240684/89827510-481c3780-db8a-11ea-815e-adf030e08b1b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
