### ISSUE TITLE
Codeunit 5431 - procedure Code

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#8280]
Hi!

We need an additional event before the ReqLineExtern.Find('-') in the Code procedure in the Calc. Item Plan - Plan Wksh. codeunit. 
![image](https://user-images.githubusercontent.com/55734714/89883979-2e4e1500-dbc9-11ea-8824-40997cfc5f38.png)

![image](https://user-images.githubusercontent.com/55734714/89884026-3f972180-dbc9-11ea-9a02-918290938bc3.png)

Thanks!

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by andersnordmann** [comment]
No problem :)

The event publisher function:
[IntegrationEvent(false, false)]
local procedure OnBeforeReqLineExternFind(var ReqLine: Record "Requisition Line")
begin
end;

The call:
OnBeforeReqLineExternFind(ReqLineExtern);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
