### ISSUE TITLE
[Event Request] Report 10710 Make 349 Declaration [ES Localization]

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#8281]
Hello everyone,

in the past i´ve asked for a event on this function, just to skip functionality. Now i want to skip functionality but to return a value according to my custom comprobations.

**Event Location**
```
OnBeforeIncludeIn349(VATEntry,SkipEntry);
IF SkipEntry THEN
  EXIT(FALSE);

//-- EVENT LOCATION--
OnBeforeIncludeIn349Handled(VATEntry, AmountIn349, LocationDifferentCountryCode, IncludeIn349Result, IsHandled);
IF IsHandled THEN
  EXIT(IncludeIn349Result);   
//++ EVENT LOCATION ++

AmountIn349 := 0;
```

**Event Declaration**
`
LOCAL [IntegrationEvent] OnBeforeIncludeIn349Handled(VATEntry : Record "VAT Entry";VAR AmountIn349 : Decimal;VAR LocationDifferentCountryCode : Boolean;VAR IncludeIn349Result : Boolean;VAR IsHandled : Boolean)`

This event doesnt affect the other one so you can mantain the two events, but this one would be enough.
Kind regards.

**Comment by frivadulla** [comment]
This event is related with #1018

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
