### ISSUE TITLE
[Event Request] Table 38 Purchase Header- OnBeforeValidateDocumentDateFromPostingDate

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#8282]
Hello,

Please add a new publisher event to the OnValidate trigger from Posting Date as follows:

field(20; "Posting Date"; Date)
        {
            Caption = 'Posting Date';

            trigger OnValidate()
            var
                SkipJobCurrFactorUpdate: Boolean;
                IsHandled: Boolean;
            begin
                TestField("Posting Date");
                TestNoSeriesDate(
                  "Posting No.", "Posting No. Series",
                  FieldCaption("Posting No."), FieldCaption("Posting No. Series"));
                TestNoSeriesDate(
                  "Prepayment No.", "Prepayment No. Series",
                  FieldCaption("Prepayment No."), FieldCaption("Prepayment No. Series"));
                TestNoSeriesDate(
                  "Prepmt. Cr. Memo No.", "Prepmt. Cr. Memo No. Series",
                  FieldCaption("Prepmt. Cr. Memo No."), FieldCaption("Prepmt. Cr. Memo No. Series"));

                if "Incoming Document Entry No." = 0 then begin
                    OnBeforeValidateDocumentDateFromPostingDate(Rec, CurrFieldNo, IsHandled);
                    if not IsHandled then
                        Validate("Document Date", "Posting Date");
                end;

New Publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateDocDateFromPostingDate(PurchaseHeader: Record "Purchase Header"; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

The functional value of adding this event:

When a purchase invoice or purchase credit memo is created by a webservice (in our case mainly ABBYY), the document date on the document in BC is based on the actual document date mentioned on the invoice document. 

The posting date at first is equal to the system date at the moment of the document creation. 

The document date in this situation is a given. It is the date on the actual invoice. The posting date could still change. For example because after the document approval the posting date is not within the allowed posting period. In this case you have to change the posting date but the document date should remain the same.

As it is now (and how it has always been) the document date changes when you change the posting date. The user has to always change the document date back to the original value.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by CameliaPopescu** [comment]
Thank you! Do you know in which release will this event be delivered?
