### ISSUE TITLE
[Event Request] Table 381 - OnBeforeValidationCheck

### ISSUE THREAD

**Issue by JoseManuelSola** [microsoft/ALAppExtensions#8285]
Hello AL-team, 
In table 381 there is an external function that validates the VAT number by generating a confirmation message when it is incorrect. 

In Spain, with the sending of documents to the SII system, VAT number must always be correct and it is dangerous to let it be in the user's hands to introduce an erroneous VAT number because the documents sent from this custimer or vendor to the SII will be rejected. 

Would it be possible to create an OnBeforeValidationCheck event including Handle to change the confirmation message to an error where applicable?

Thanks in advance !!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
