### ISSUE TITLE
[NAV][ODataV4] Cannot Delete/Patch: Error in query syntax

### ISSUE THREAD

**Issue by hesa2020** [microsoft/ALAppExtensions#8286]
Hello i have been trying to debug this for the past 3 business days and i havent been able to figure out what is wrong.

I call delete and i get Error in query syntax as soon as i pass some parameters.

While looking at the metadata i get the following keys:
```
string Item_No
string Sales_Type
string Sales_Code
date Starting_Date
string Currency_Code
string Variant_Code
string Unit_of_Measure_Code
decimal Minimum_Quantity
```

So i call it like this:

`delete https://nav.domain.com:7048/NAV/ODataV4/Company('TESTJL')/SalesPrices('C-MONITORING','Customer','752','0001-01-01','','','UN',0)`

And I also tried like that:

`delete https://nav.domain.com:7048/NAV/ODataV4/Company('TESTJL')/SalesPrices(Item_No='CONSUL%20SENIOR',Sales_Type='Customer',Sales_Code='1537',Starting_Date='',Currency_Code='',Variant_Code='',Unit_of_Measure_Code='UN',Minimum_Quantity=0)`

But i always get **Bad Request - Error in query syntax.**

We are using Dynamics NAV 2018 v. 11.0.20783.0

PS: SalesPrices is a Page of Object ID 7002 with "All Tenants" checked.

**Comment by AlexanderYakunin** [comment]
Sorry, this forum is for extensibility requests for V16/V17, not for reporting bugs or requesting hotfixes. Please create request via technical support to get help.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
