### ISSUE TITLE
[Event Request] Database::"Warehouse Receipt Line" - Function DeleteQtyToReceive - OnBeforeDeleteQtyToReceive

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8290]
We like to request the following Event:
Object: Database::"Warehouse Receipt Line"
Function: DeleteQtyToReceive
Publisher Event: OnBeforeDeleteQtyToReceive
Reason: To implement custom business logic
Where is the event placed:
procedure DeleteQtyToReceive(var WhseReceiptLine: Record "Warehouse Receipt Line")
    var
        IsHandled: Boolean;
    begin
        OnBeforeDeleteQtyToReceive(WhseReceiptLine, IsHandled);
        if IsHandled then
            exit;
        with WhseReceiptLine do begin
            if Find('-') then
                repeat
                    Validate("Qty. to Receive", 0);
                    OnDeleteQtyToReceiveOnBeforeModify(WhseReceiptLine);
                    Modify;
                until Next = 0;
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteQtyToReceive(var WhseReceiptLine: Record "Warehouse Receipt Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
