### ISSUE TITLE
[Request for external] Procedures in test codeunit 141077, 134928, 137305, and 141041

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#8292]
Hi Microsoft AL Team,

Could you please change the scope of the following functions to External?
I would like to use them to set up test data without having to create a local copy of each function in my test suite.

**Codeunit** **141077**  "UT APAC Miscellaneous Reports"
- CreateBankAccount
- CreateSourceCode
- CreateGeneralJournalBatch
- CreateGeneralJournalLine

**Codeunit** **134928** "ERM MIR Reports" 
- CreateIssuedReminder
- CreateIssuedReminderHeader
- CreateIssuedReminderLine

**Codeunit** **137305** "SCM Warehouse Reports"
- CreateAndReleasePurchaseOrder
- FindWarehouseActivityLine
- FindWarehouseReceiptNo
- FindWhseWorkSheetLine
- InitWarehouse
- NoSeriesSetup
- CreateLocationSetup
- CreateFullWarehouseSetup
- CreateLocation
- CreateTransferOrderLocations
- CreateAndUpdateLocation
- CreateManufacturingItem
- FindBinContent
- FindFirstBinRankingForZone
- CreateBinContentForBin
- CreateWhseShipmentAndPick
- CreateMovementWorksheetLine
- UpdateRankingOnAllBins
- FindWarehouseShipmentNo
- CreateAndPostWarehouseReceiptFromPurchaseOrder
- PostWarehouseReceipt
- RegisterPutAway
- CreateWarehouseSetup
- CreateAndReleaseSalesOrder
- CreateSalesOrder
- CreateItem
- CreatePurchaseOrder
- CreateAndRealeaseTransferOrder

**Codeunit** **141041**  "UT AUNZ Statement Report"
- CreateCustomerLedgerEntries
- CreateDetailedCustomerLedgerEntry

Thank you.

Regards,
Tuan Nguyen

**Comment by AlexanderYakunin** [comment]
No, we never expose local procedures from test codeunits, we can only do it using test libraries. You should try to use test libraries for developing your tests.

**Comment by tuan-nguyen-fenwick** [comment]
@AlexanderYakunin Thank you for the information. Do you have any future plans to expose or potentially move any of these functions into test libraries?

**Comment by AlexanderYakunin** [comment]
Currently no.
