### ISSUE TITLE
[Event Request] Codeunit 21 "Item Jnl.-Post Line" OnAfterCalcCapQty

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#8294]
Can we add an event to Codeunit 21 "Item Jnl.-Post Line" called OnAfterCalcCapQty.

    local procedure CalcCapQty() CapQty: Decimal
    begin
        GetMfgSetup;

        with ItemJnlLine do begin
            if "Unit Cost Calculation" = "Unit Cost Calculation"::Time then begin
                if MfgSetup."Cost Incl. Setup" then
                    CapQty := "Setup Time" + "Run Time"
                else
                    CapQty := "Run Time";
            end else
                CapQty := Quantity + "Scrap Quantity";

            OnAfterCalcCapQty(ItemJnlLine, CapQty);   // NEW
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcCapQty(var ItemJournalLine: Record "Item Journal Line";var CapQty: Decimal);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
