### ISSUE TITLE
[Event Modification] Codeunit 1605 "PEPPOL Management" GetAdditionalDocRefInfo

### ISSUE THREAD

**Issue by markusfjolnisson** [microsoft/ALAppExtensions#8298]
The Sales Header from the XML port is needed as a parameter for this function. The AdditionalDocRef node in the EHF file is used to attach a base64 encoded pdf, but i cant generate a pdf through a bc report object without knowing the document number. Having the Sales Header when i subscribe to the GetAdditionalDocRefInfo procedure would solve this.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
