### ISSUE TITLE
[Event Request] Table 14 Location - OnAfterGetLocationSetup

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8299]
Hi team,

We want to request standard event publisher OnAfterGetLocationSetup there:

![image](https://user-images.githubusercontent.com/69669749/90227876-f390ea80-de1d-11ea-8dbd-fd6319f22a46.png)

We want to have possibility to assign InvtSetup or WhseSetup values to custom Location fields there in BC17.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
