### ISSUE TITLE
Missing Event Table 7317

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#830]
Hi,

in https://github.com/Microsoft/AL/issues/3646 I requested an event that should have been shipped. 
In BC CU2 it still ain´t there. Has this been forgotten or will it be implemented in an later update?

**Comment by JesperSchulz** [comment]
By default, we don't backport to already released versions. Issues reported in this repository will only be addressed in the upcoming major release, as certain processes apply for changing code in versions released to market. For more information on our branching strategy, please read here: [AL Developer Previews, multiple releases, and GitHub](https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github). 
However, we occasionally do bundle fixes and backport them to the current BC cloud release. That does not seem to have happened here. I will make sure, it is part of the next bundle. But again, normally issues reported on GitHub will only be addressed in the next major.
