### ISSUE TITLE
[Request for External] Table 167 "Job" - UpdateBillToCust

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#8300]
We need to call the procedure "UpdateBillToCust" on Table 167 "Job" from outside.
Please change it from local to global.

OLD CODE:
```
local procedure UpdateBillToCust(ContactNo: Code[20])
var
    ContBusinessRelation: Record "Contact Business Relation";
    Cust: Record Customer;
```

NEW CODE:
```
procedure UpdateBillToCust(ContactNo: Code[20])
var
    ContBusinessRelation: Record "Contact Business Relation";
    Cust: Record Customer;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
