### ISSUE TITLE
[Event Request] Table 36 Sales Header - OnValidateShipToCode

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8302]
Hi team,

In Table 36 we have heavily customized field 12 "Ship-to Code" OnValidate trigger.

To eliminate our customizations, we need custom publisher with IsHandled - then we would be able to replace standard code with our own.

local procedure OnValidateShipToCode(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; Customer: Record Customer; ShipToAddr: Record "Ship-to Address"; var IsHandled: Boolean)

Place of the publisher:
![image](https://user-images.githubusercontent.com/69669749/90246690-d0763300-de3d-11ea-9990-142e0d4a9313.png)

(But if it is better for everyone, publisher can be in the beginning of OnValidate trigger as well).

We need it in BC17.

**Comment by RomanZanizdra** [comment]
Hi @JonasMikalkenas . 
It's not fully clear about the "ShipToAddr" parameter you've requested in event because it started to be used in the code only after record is re-read several lines below. So even if you change the record in subscriber it will not have effect. Do you really need it in event?

**Comment by JonasMikalkenas** [comment]
Hi @RomanZanizdra,

You are completely right. ShipToAddr parameter can be removed as it is easy to get inside the subscriber when needed. 

My apologies for missing that in event verification phase before request.

We are going to simplify our request then:
local procedure OnValidateShipToCode(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; Customer: Record Customer; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
