### ISSUE TITLE
[Event Request] Table 36 Sales Header - OnValidateLocationCodeOnBeforeUpdateShipToAddress

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8303]
Hi team,

In table 36 we need possibility to customize field 28 "Location Code" OnValidate trigger: we want to have possibility to replace function UpdateShipToAddress with our own code or disable it (as we do the same things in another place in our customization)

Best way to manage this in our opinion is new publisher with IsHandled there:

![image](https://user-images.githubusercontent.com/69669749/90247855-28159e00-de40-11ea-8a7a-53940407405a.png)

Or just place publisher with IsHandled in the beginning of OnValidate.

**Comment by RomanZanizdra** [comment]
There is already IsHandled pattern in UpdateShipToAddress function. It will be extended with CurrFieldNo to identify if it was called from "Location Code" trigger and then you can use it.

    procedure UpdateShipToAddress()
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateShipToAddress(Rec, IsHandled);
        if IsHandled then
            exit;
...

**Comment by RomanZanizdra** [comment]
Hi @JonasMikalkenas , please see my comment above.

**Comment by JonasMikalkenas** [comment]
Hi @RomanZanizdra ,

Yes, if existing publisher in UpdateShipToAddress would be extended with CurrFieldNo in next releases, our customization easily can be reimplemented to use this event. We would be happy with such solution.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
