### ISSUE TITLE
[Event Request] Table 36 Sales Header - OnValidateSellToCountryRegionCodeOnBeforeUpdateShipToAddressFromSellToAddress

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8304]
Hi team,

In table 36 we need possibility to customize field 90 "Sell-to Country/Region Code" OnValidate trigger: we want to have possibility to replace function UpdateShipToAddressFromSellToAddress with our own code or disable it (as we do the same things in another place in our customization)

Best way to manage this in our opinion is new publisher with IsHandled there:
![image](https://user-images.githubusercontent.com/69669749/90248651-c9512400-de41-11ea-8cf7-2c636054b815.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
