### ISSUE TITLE
[Event Request] - Codeunit ServContractManagement (5940) in methods PostPartialServLedgEntry and CreateRemainingPeriodInvoice

### ISSUE THREAD

**Issue by jorgecorreia27** [microsoft/ALAppExtensions#8305]
Dear all,
In the course of a development in Business Central related to Services, there is a method n codeunit ServContractManagement (5940) called PostPartialServLedgerEntry which assigns values to a record ServLedgerEntry and afterwards inserts that same record. But we would like to do some more code after that insert, because the goal is that the ServLedgerEntry record could be modified with other values for the fields Unit Price and Amount (LCY). So I would like to request an event right before the INSERT, so that, by subscribing that event, the values on the Service Ledger Entry record could have the values in question.
[Note:] Below is a sugestion of an event which could solve this issue
![image](https://user-images.githubusercontent.com/37341299/90163410-f8a65900-dd8d-11ea-90eb-15664177f97b.png)

Another request is when we execute the function "Create Service Invoice" on page 6050 (Service Contract). By following the process, a function called CreateRemainingPeriodInvoice (also in codeunit ServContractManagement (5940)) is called, and at the end there is a MODIFY to a Record of type ServiceContractHeader. But we would like to some values from that Record with our own business logic. So the request is, again, to add an event afther the MODIFY, so that, by subscribing that event, we could also solve this issue.
[Note:] Below is a sugestion of an event which could solve this issue.
![image](https://user-images.githubusercontent.com/37341299/90164073-d82ace80-dd8e-11ea-9055-33f5155f33a9.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
