### ISSUE TITLE
Regarding #7637 - Table 210 "Job Journal Line" - OnValidate "Chargeable"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#8307]
Regarding #7637 

With BC 16 CU4 you`ve inserted a new procedure "ValidateChargeable" to handle validation of field "Chargeable", but you`ve missed to change the OnValidate-Trigger accordingly...

OLD CODE:
```
field(22; Chargeable; Boolean)
        {
            Caption = 'Chargeable';
            InitValue = true;

            trigger OnValidate()
            begin
                if Chargeable <> xRec.Chargeable then
                    if not Chargeable then
                        Validate("Unit Price", 0)
                    else
                        Validate("No.");
            end;
        }
```

NEW CODE:
```
field(22; Chargeable; Boolean)
        {
            Caption = 'Chargeable';
            InitValue = true;

            trigger OnValidate()
            begin
                // start kvspsa - Call already existent procedure!
                ValidateChargeable();
                // stop kvspsa
            end;
        }
```

**Comment by StHillmann** [comment]
In BCInsider-Preview of BC17, it is already fixed!

**Comment by RomanZanizdra** [comment]
Hi @StHillmann .
As you already see the requested change was not implemented to 16.x version. Unfortunately now we cannot downgrade events for 16.x version via github requests. Only for latest prod version. Could you be so kind to reach out product support channel and log a hotfix request for downgrading required change in 16.x version. Then it will be implemented.
Can we close current issue?

**Comment by StHillmann** [comment]
Sure
