### ISSUE TITLE
On the "Buy-from Vendor History" page, if the tile caption doesn't fit, it is not added in front of the ToolTip

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#8308]
Hello,

We created an extension for Buy-from Vendor History factbox page (Vendor Hist. Buy-from FactBox) and added a new field (Purchase Status Lines Maintenance Requests). The caption of this field is too long and it doesn't fit in the tile:
![image](https://user-images.githubusercontent.com/44637002/90257441-daa12d00-de4f-11ea-8d48-8fe82a9469d5.png)

When having a look at the ToolTip, it doesn't contain also the field caption as it happens in the Role Centers when the caption doesn't fit:
![image](https://user-images.githubusercontent.com/44637002/90259202-4daba300-de52-11ea-85ec-29af3112ac1a.png)

On Role Centers, the Ongoing Purchase Invoices caption doesn't fit and the ToolTip starts with the field caption:
![image](https://user-images.githubusercontent.com/44637002/90259265-6451fa00-de52-11ea-92b7-841485499e31.png)

Shouldn't the same behavior be present on the factbox page?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
