### ISSUE TITLE
[Event Request] Codeunit 1501 "Workflow Management" – EvaluateCondition

### ISSUE THREAD

**Issue by ampasc** [microsoft/ALAppExtensions#8309]
Could we please have a new Publisher "OnAfterEvaluateCondition" within the function "EvaluateCondition" of Codeunit 1501 "Workflow Management" exposing the return value of the function as a VAR-parameter?
This would enable us to add further checks to determine whether a workflow should be executed or not.

```
    local procedure EvaluateCondition(RecRef: RecordRef; xRecRef: RecordRef; ArgumentID: Guid; var WorkflowRule: Record "Workflow Rule"): Boolean
    begin
        ...
        
        Result := Result and EvaluateRules(RecRef, xRecRef, WorkflowRule);
        
        // >>>>>>>>
        OnAfterEvaluateCondition(RecRef,xRecRef,ArgumentID,WorkflowRule,Result):
        // <<<<<<<<

        exit(Result);
    end;

    ...

    // >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnAfterEvaluateCondition(RecRef: RecordRef; xRecRef: RecordRef; ArgumentID: Guid; var WorkflowRule: Record "Workflow Rule"; var Result: Boolean)
    begin
    end;
    // <<<<<<<<      
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
