### ISSUE TITLE
[Function Expose] CU 7000

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/ALAppExtensions#831]
Hi,

we need function ActivatedCampaignExists in CU 7000 Sales Price Calc. Mgt. to be global/external.

Thanks in advance

**Comment by DuttaSoumya** [comment]
Hi @LFlamme ,

The ActivatedCampaignExists function does quite a few things at the same time and as it was not deemed to be an API function, it was kept as a LOCAL function,

1. It creates a copy of the existing Campaign Target Group

2. It returns TRUE if the copy has records

3. Note that temporary records are passed on to this function.


We are curious to know what is your need and perhaps we may consider re-factoring the code to support that here.

Best regards

**Comment by LFlamme** [comment]
Hi,

we pass an empty "Campaign Target Group". The other parameters are not empty. 
we use the return value as well as the returned "Campaign Target Group".

**Comment by SirBETE** [comment]
Hello 
We also need `ActivatedCampaignExists`.
We use the No. of the first `ToCampaignTargetGr` from `ActivatedCampaignExists` to filter the sales codes if the sales type = Campaign so we can get the best sales price for it.
