### ISSUE TITLE
[Additional Parameter Request] Page 475 VAT Statement Preview Line

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8310]
Referenced to #6277

As shown in attached image, our extension needs access to marked variables.
Our suggestion is to extend OnBeforeCalcColumnValue event with these variables.

There are other similar issues regarding this, but none of them seems to be solving this issue as we are not extending this page, just calculating amount in our own way:

#7622
#5821
#1237
#7623

![image](https://user-images.githubusercontent.com/53556909/90373630-7dd18c80-e072-11ea-9ee0-54e4ba2c75a1.png)

**Comment by RomanZanizdra** [comment]
@aobsgit, please be precise in description how event publisher should be looking like. Especially it relates to the parameter which is called "false" and VATStmtName (may be it can be get from VATStatementLine).

**Comment by RomanZanizdra** [comment]
Hi @aobsgit . Any update from your side?

**Comment by aobsgit** [comment]
Hi

I'm sorry for late reply and again thank you for your engagement.
Practically we are calling our own VATStatement.CalcLineTotal function. However this functions depends on VATStatement.InitializeRequest function since it sets global parameters which we need in our calculations. New integration event should look like:

[IntegrationEvent(true, false)]
local procedure OnBeforeCalcColumnValue(
   VATStatementLine: Record "VAT Statement Line"; 
   var TotalAmount: Decimal; Level: Integer; 
   NewSelection: Option Open,Closed,"Open and Closed"; 
   NewPeriodSelection: Option "Before and Within Period","Within Period"; 
   NewPrintInIntegers: Boolean; 
   NewUseAmtsInAddCurr: Boolean, 
   var IsHandled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by aobsgit** [comment]
Hi
When can we expect this to be solved. v17 doesn't include this.
Thanks

**Comment by RomanZanizdra** [comment]
Hi @aobsgit , it will be available in 17.1.
Also it can be available in the latets docker i suppose.
