### ISSUE TITLE
[Event Request] - Table 36 Sales Header - OnBeforeSetSalespersonCode

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8311]
Hi Team,

In table 36 we need new custom publisher at the beginning of procedure SetSalespersonCode:

local procedure OnBeforeSetSalespersonCode(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)

![image](https://user-images.githubusercontent.com/69669749/90391904-9358ad80-e096-11ea-9ec0-928046b3b2ef.png)

We need to have possibility to skip this code section or replace it by our own code in our customizations. 

Thinking from global perspective, this event should be created in all (5) places where the same standard function SetSalesPersonCode exists:

Table 36 Sales Header
Table 5900 Service Header (i see it was already requested by other person there: #7391 )
Table 5968 Service Contract Header
Codeunit 5940 ServContractManagement
Report 6036 Create Contract Service Orders

If possible, create all 5 publishers (or just optimize code to call the same function with publisher from all 5 places). If not, then create only publisher in table 36, it is enough for our current customizations.

Thank you in advance.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
