### ISSUE TITLE
[Event Request] - Table 36 SalesHeader - OnAfterUpdateShipToAddressFromSellToAddress

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8312]
Hi Team,

In table 36 we need possibility to add our own code at the end of function UpdateShipToAddressFromSellToAddress - to assign some custom fields, for example. We cannot do it using table extension, as we need results of our customization before ModifyCustomerAddress procedure is called.

local procedure OnAfterUpdateShipToAddressFromSellToAddress(var SalesHeader: Record "Sales Header"; FieldNumber: Integer; var xSalesHeader: Record "Sales Header")

![image](https://user-images.githubusercontent.com/69669749/90394552-88ece280-e09b-11ea-9577-518a64a24544.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
