### ISSUE TITLE
[event request] table 77 "Report Selections" - PrintDocumentsWithCheckGUIYesNoCommon() - Add IsPreview parameter to OnBefore/AfterPrintDocument*()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#8313]
We want to be able to detect when a Report Selection is run and output to Print, Email, or really anything other than Preview. We want to then add a Comment Line to the Customer or other record to note that we produced/sent a report to them.

It's conceivable that we might also at some point want to prevent Email runs being done to Blocked customers, etc.

***

How can this be done? I found the below in "Report Selections", which seems apt, but it seems there is no way to determine whether the report is being run in Preview mode or not, and so we would get comments being added when previewing, which we don't want.

There are also no apparent ways to determine output/delivery method in the `Reporting Triggers` or `ReportManagement` codeunits, or did I miss them?

***

If there is no other/better way to do this, and the following is possible somehow: please can you add a Boolean argument named `IsPreview` or similar to all handlers prefix with `// ***` below, indicating whether or not the report is just being Previewed? If not, we would presume it was being sent or output for 'live' use, to the customer.

Alternatively, if you think it would be better for future extensibility, add an Enum covering all standard output methods available in the Report Selections / Custom Layout framework.

Thanks!

***

```
    local procedure PrintDocumentsWithCheckGUIYesNoCommon(ReportUsage: Integer; RecordVariant: Variant; IsGUI: Boolean; AccountNoFieldNo: Integer; WithCheck: Boolean; TableNo: Integer)
    var [...]
    begin
        // ***
        OnBeforeSetReportLayout(RecordVariant, ReportUsage);

        RecRef.GetTable(RecordVariant);
        GetUniqueAccountNos(TempNameValueBuffer, RecRef, AccountNoFieldNo);

        SelectTempReportSelectionsToPrint(TempReportSelections, TempNameValueBuffer, WithCheck, ReportUsage, TableNo);

        OnPrintDocumentsOnAfterSelectTempReportSelectionsToPrint(
          RecordVariant, TempReportSelections, TempNameValueBuffer, WithCheck, ReportUsage, TableNo);

        if TempReportSelections.FindSet then
            repeat
                if TempReportSelections."Custom Report Layout Code" <> '' then
                    ReportLayoutSelection.SetTempLayoutSelected(TempReportSelections."Custom Report Layout Code")
                else
                    ReportLayoutSelection.SetTempLayoutSelected('');

                TempNameValueBuffer.FindSet;
                AccountNoFilter := GetAccountNoFilterForCustomReportLayout(TempReportSelections, TempNameValueBuffer, TableNo);
                GetFilteredRecordRef(RecRefToPrint, RecRef, AccountNoFieldNo, AccountNoFilter);
                RecVarToPrint := RecRefToPrint;

                IsHandled := false;

                // ***
                OnBeforePrintDocument(TempReportSelections, IsGUI, RecVarToPrint, IsHandled);

                if not IsHandled then
                    REPORT.RunModal(TempReportSelections."Report ID", IsGUI, false, RecVarToPrint);

                // ***
                OnAfterPrintDocument(TempReportSelections, IsGUI, RecVarToPrint);

                ReportLayoutSelection.SetTempLayoutSelected('');
            until TempReportSelections.Next() = 0;

        // ***
        OnAfterPrintDocumentsWithCheckGUIYesNoCommon(ReportUsage, RecVarToPrint);
    end;
```

**Comment by RomanZanizdra** [comment]
Hi @dtkb . I see that we actually have several parts here, in your request.
So if you need enum for particular option field you can just create a separate github issue for it and it will be processed.
What about report selection and around ... I think you see there is no possibility to understand how report is run from the Report Selections. It just run the report and everything after this just out of Report Selections scope. The place where we can definitely say how report is run is just report as itself. There we call IsPreview function. Does it make sense for you to subscribe to required report and from there identify if you need to do something else or not?

**Comment by dtkb** [comment]
I don't think so because the report did need to be run via Report Selections / Custom Layout Reporting, and thus it could end up running different report objects depending on company/customer, so it would not be a general solution and may not be usable for standard reports since I don't think I've seen any of them exposing OnPreview events or such anyway.

In this case, we have buttons to run the required report selections on a custom page, and just added code to those actions that will assume the report is printed, and does the required thing there. Then if the user needs to avoid that code and 'preview', they just run the report the normal way... This is not very nice though.

I just thought there, that perhaps a way to do this is to have custom action code, and in the case of posted invoices/credits, compare "No. Printed" before and after the report is run, and if it was incremented then we know we were in Print mode and not Preview. This isn't as general but would have probably solved that use case better, in retrospect.

I'll say close for now, and if it becomes a pressing issue for us again, open a better request. Thanks!
