### ISSUE TITLE
[Additional Parameter Request] Table 39 Purchase Line in existing Publisher OnValidateLocationCodeOnBeforeSpecialOrderError

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#8317]
We would like to add **CurrFieldNo** to the existing Publisher OnValidateLocationCodeOnBeforeSpecialOrderError in Field **Location Code**

**Current Event Definition:**
`OnValidateLocationCodeOnBeforeSpecialOrderError(PurchaseLine : Record "Purchase Line";VAR IsHandled : Boolean)`

**Modified Event Definition:**
`OnValidateLocationCodeOnBeforeSpecialOrderError(PurchaseLine : Record "Purchase Line";CallingFieldNo : Integer; VAR IsHandled : Boolean)`

We use CurrFieldNo in our Solution to only do the check if CurrFieldNo equals the FieldNo of Location Code. Can you please add the additional Parameter?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
