### ISSUE TITLE
[Request for External] Report 1003 Post Invt. Cost to G/L - Test 

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#8318]
Could you please make the existing function **AddError** in Report 1003 Global so we can reach it via a subscriber.

In issue [#6807](https://github.com/microsoft/ALAppExtensions/issues/6807) we requested a publisher **OnBeforeCheckPostingSetup** this one has IncludeSender set to Yes.

We want to add an errortext in some scenarios to this report, therefore we need to have access to the existing function AddError.

**Comment by fvanderhek** [comment]
What is the status of this Request, can tou please update ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
