### ISSUE TITLE
[Additional Parameter Request] Codeunit 99000832 Sales Line-Reserve - OnBeforeVerifyChange

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8320]
Hi Team,

In Codeunit 99000832 we need to customize code in function VerifyChange. We found that event for this was already requested and approved (we do not see this event in BC16 RTM, but related ticket #6960 with the same publisher as we need is already closed, so we will find this event in BC17, right?)

But part of our customizations are field related (for example, part of customization code is actual only when VerifyChange is called from T37 "Location Code" OnValidate trigger).

Would you be able to add additional parameter CallingFieldNo to an existing OnBeforeVerifyChange event to manage this? Something like this:

![image](https://user-images.githubusercontent.com/69669749/90512581-0cbfd100-e167-11ea-99d2-f0fa4ff96c38.png)

**local procedure OnBeforeVerifyChange(var NewSalesLine: Record "Sales Line"; OldSalesLine:Record "Sales Line"; CallingFieldNo: Integer; var IsHandled: Boolean)**

This parameter should be added to the procedure VerifyChange of Codeunit 99000832 parameters list as well, and to all 9 calls from T37 fields to pass CurrFieldNo to the publisher.

OR, if solution above is not OK, then please just create custom publisher there:
Table 37 - Sales Line, field 7 "Location Code" - OnValidate trigger:
![image](https://user-images.githubusercontent.com/69669749/90512208-6ecc0680-e166-11ea-91f7-fc1e8c89e9d9.png)

with description:
**local procedure OnValidateLocationCodeOnBeforeVerifyChange(var SalesLine: Record "Sales Line"; FieldNo: Integer; var IsHandled: Boolean)**

**Comment by JonasMikalkenas** [comment]
Additional comment: 
We just found that we have the same problem in Table 37 Sales Line - OnModify trigger. There we also have a need to replace calling of ReserveSalesLine.VerifyChange with our own code (or possibility to have CallingFieldNo parameter there to manage our customization using OnBeforeVerifyChange event. 

So first solution with CallingFieldNo would resolve more than one problem without creating new publishers. Otherwise we should request several more publishers with handle before VerifyChange calls.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
