### ISSUE TITLE
Update on cases

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#8321]
Hi

Not trying to sound impatient but we're a little bit worried that some of our cases, which have been marked as Ships in Future Release, have slipped through the cracks.

They are only minor changes and they were changed to Ships in Future back in April.  I've just checked the latest release and the changes are not in there.  We've had other modifications done both before and after these which have turned up in the recent releases and just wanted to double-check that they haven't been missed.

Cases are:

https://github.com/microsoft/ALAppExtensions/issues/5854
https://github.com/microsoft/ALAppExtensions/issues/6457
https://github.com/microsoft/ALAppExtensions/issues/6764

Thanks in advance

**Comment by RomanZanizdra** [comment]
Hi @CnCollins .
As you see some event were not implemented in 16 version. Unfortunately we cannot downgrade events based on github request, only for the latest prod version witch will be 17. So if you really need these changes in 16.x version please reach out product support to log a hotfix request for downgrading events in required version. Or just wait for the latest version.
Can we close current issue?

**Comment by CnCollins** [comment]
Hi @RomanZanizdra 

I'm not sure what you mean about downgrading events?  We know you are normally pretty fast at turning requests around so wanted to make sure that these haven't been missed.  

Please go ahead and close the case.  It looks like they are in the latest insider 17.

Thanks

Chris

**Comment by RomanZanizdra** [comment]
Hi @CnCollins . I meant that we implement events for the latest prod version and now it will be 17.x and if you for some reasons need event to be implemented in 16.x version for example then it can be done via support and hotfix.
That's great that you fine with latest 17. Thank you for collaboration, I'll close the issue.
