### ISSUE TITLE
Business Central Does not Support Reversal of Reciepts and Shipments like Undo reciept\ Shipment process in Case of Stock and sell process in NAV

### ISSUE THREAD

**Issue by aroraankur4343** [microsoft/ALAppExtensions#8323]
under Business central for Trading Companies using Drop Shipment Undo receipt\ Shipment process is not avalible

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
