### ISSUE TITLE
[Field Length Increase] table 5777 "Item Reference" - Extend Field Length of "Reference Type No."

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#8324]
Is here the right place to ask for a increasement of the field length to Code[30] of the field "Reference Type No." in table 5777 "Item Reference"?
We would need a optional longer field length since our current Reference Table is using an Code[30] as primary key and we can only change to the standard reference structure if the "Reference Type No." can hold values with Code[30]

**Comment by StanPesotskiy** [comment]
Increasing a field length is a breaking change that will affect all our users. 
It can be pushed only by a very important business reason.
