### ISSUE TITLE
Attachment function preview not working for Service documents

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#8325]
Dear Team,

Application: Dynamics 365 Business Central 16.4 On-Prem/Cloud

This is official request to rectify attachment problem not working properly as expected on all service module document pages such as order/invoice pages. can you please look into this issue as soon as possible.

Service Order Attachment (Problematic):
![Services_AttachmentFactbox](https://user-images.githubusercontent.com/12932124/90621064-34d62f80-e24e-11ea-87b3-f991f387bf13.gif)

Sales Order Attachment (Correct):
![Sales_AttachmentFactbox](https://user-images.githubusercontent.com/12932124/90621092-3e5f9780-e24e-11ea-89fe-a0a67c360384.gif)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
