### ISSUE TITLE
[Additional Parameter Request] Table 37 Sales Line - OnValidatePurchasingCodeOnAfterAssignPurchasingFields - add IsHandled

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8326]
Hi Team,

In table 37 we need to have possibility to customize code in field 5711 "Purchasing Code" OnValidate trigger. Existing event OnValidatePurchasingCodeOnAfterAssignPurchasingFields perfectly fits for it, just we want to handle code below and replace it with our own code (as we have modified standard code after this publisher in many places)

Our suggestion to add IsHandled parameter:
**[IntegrationEvent(false, false)]
local procedure OnValidatePurchasingCodeOnAfterAssignPurchasingFields(var SalesLine: Record "Sales Line"; PurchasingCode: Record Purchasing; var IsHandled: Boolean);**

![image](https://user-images.githubusercontent.com/69669749/90625031-9d5ae780-e221-11ea-93f7-ea3e5ef79bbf.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
