### ISSUE TITLE
[Request for External] T5740 Transfer Header GetHideValidationDialog

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#8327]
Hello,
would it be possible to add get method for HideValidationDialog like
```
procedure GetHideValidationDialog(): Boolean
    begin
        exit(HideValidationDialog);
    end;
```

it would be really helpful when handling custom validation like for example in
```
OnBeforeValidateTransferFromCode
```

Thanks,
Bartek

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
