### ISSUE TITLE
[Event Request] Table 37 Sales Line - OnInitQtyToShipOnBeforeCheckServItemCreation

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8329]
Hi Team,

In table 37 we need new publisher in procedure InitQtyToShip:

**[IntegrationEvent(false, false)]
local procedure OnInitQtyToShipOnBeforeCheckServItemCreation(var SalesLine: Record "Sales Line")**

![image](https://user-images.githubusercontent.com/69669749/90633140-3132b080-e22e-11ea-873d-95cc690284a7.png)

We cannot use existing publisher OnAfterInitQtyToShip because our customizations are for Service Items and should be applied before calling CheckServItemCreation

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
