### ISSUE TITLE
[Event Request] table 36 "Sales Header" "VAT Registration No."

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#8330]
The event was labeled with "ships-in-future-update" but unfortunately I did not get it yet...
https://github.com/microsoft/ALAppExtensions/issues/6274

**Comment by RomanZanizdra** [comment]
Hi @Schnieringer , should be there. Please check again, at least latest 16.x

        field(70; "VAT Registration No."; Text[20])
        {
            Caption = 'VAT Registration No.';

            trigger OnValidate()
            var
                Customer: Record Customer;
                VATRegistrationLog: Record "VAT Registration Log";
                VATRegistrationNoFormat: Record "VAT Registration No. Format";
                VATRegNoSrvConfig: Record "VAT Reg. No. Srv Config";
                VATRegistrationLogMgt: Codeunit "VAT Registration Log Mgt.";
                ResultRecRef: RecordRef;
                ApplicableCountryCode: Code[10];
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateVATRegistrationNo(Rec, IsHandled);
                if IsHandled then
                    exit;

                "VAT Registration No." := UpperCase("VAT Registration No.");
                if "VAT Registration No." = xRec."VAT Registration No." then
                    exit;

**Comment by Schnieringer** [comment]
@RomanZanizdra 

Yes, it exists, I found it. Thanks for the hint. I close the issue.
