### ISSUE TITLE
[Event Request] T5740 TransferHeader OnBeforeValidateTransferToCode

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#8332]
Hello,
I would like to request an event in Transfer-to Code
```
field(2; "Transfer-to Code"; Code[10])
        {
            Caption = 'Transfer-to Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            var
                Location: Record Location;
                Confirmed: Boolean;
                IsHandled: Boolean;
            begin
                TestStatusOpen;

                IsHandled := false;
                OnBeforeValidateTransferToCode(Rec, xRec, IsHandled);
                if IsHandled then
                    exit;

              ...
```
just like it is in Transfer-from Code. This would allow to handle custom validation. Event is in the codebase but its never raised, looks like a bug.

Thanks,
Bartek

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
