### ISSUE TITLE
T5740 TransferHeader Excessive locktable

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#8333]
Hello,
in OnValidate trigger on fields
Transfer-from Code
Transfer-to Code

after succesful confirmation handling there are these two lines
```
TransLine.LockTable();
TransLine.SetRange("Document No.", "No.");
```

nothing happens after above filtering with these records, moreover function executed after this code
```
UpdateTransLines(Rec, FieldNo("Transfer-from Code"));
UpdateTransLines(Rec, FieldNo("Transfer-to Code"));
```
operates on its own local Transfer Line record variable.

Looks like a bug or is there a purpose behind it which I can't spot?

Thanks,
Bartek

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
