### ISSUE TITLE
Page 10039 Purchase Order Stats OnAfterGetRecord

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#8335]
Is it possible to add an EVENT at where the 3rd red line is with FromPurchaseHeader, TotalAmount1, TotalAmount2 and 'IsHandled' parameters  where two TotalAmount arrays of 3 will returns the value back to the 'OnAfterGetRecord?   The purpose is for use our own Tax calculation procedure to replace the FOR Loop and skip the base BC procedure.   Thank you very much!  

![image](https://user-images.githubusercontent.com/49729094/90648339-65df4180-e207-11ea-93ef-b667e7196ff0.png)

**Comment by AlexanderYakunin** [comment]
Can you simply replace our Purchase Stat with you own page in Purchase order? You can create you page from ours and link it Action item instead?

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
