### ISSUE TITLE
[Request for External] Document Service Management

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#8336]
OnPrem we use the "Document Service Management" (COD 9510) to store documents on Sharepoint and to call them up again. We would like to use these functions in the cloud as well.

- Can you allow access on table 2000000114 "Document Service" in scope "Cloud"?
- Remove [Scope('OnPrem')] on functions in codeunit 9510 "Document Service Management"?

Thank you!

**Comment by bleisibach** [comment]
@StanPesotskiy Is there any indication if and when we can expect this feature? Thank you.

**Comment by mazhelez** [comment]
@bleisibach Thank you for your suggestion!

However, the requested function operate with file paths and there are security concerns when opening such functions for cloud development. As for the table, we try to hide table behind APIs.

_Document Service_ is a great idea for a new system module! Would you interested in developing such a system module? I promise I'll help on the way.

**Comment by JesperSchulz** [comment]
If you want to learn more about what it takes to develop a new AL Module, you can read more here [aka.ms/NewALModule](http://aka.ms/NewALModule).

**Comment by mazhelez** [comment]
@bleisibach Just letting you know that we created a work item on our backlog to reenable Document Service for cloud.

Unfortunately, however, I cannot promise any delivery point in time.

**Comment by bleisibach** [comment]
Thank you @mazhelez for putting this on the list. 

The suggestion to advance the topic as an AL Module was tempting. Unfortunately, we currently lack the necessary resources.

We currently only need a minimally small part of the code unit:
- TestConnection
- SaveStream
- OpenDocument

And of course we need access to the table 2000000114 "Document Service" to save the setup. So everything without file access etc ...

Thank you anyway!

**Comment by JesperSchulz** [comment]
Enable "Document Service" for cloud is now set as candidate for 2021 Wave 2. We will have to do some work on the authentication bit as well to make this work properly in a cloud setting.

**Comment by redIT-LoPf** [comment]
@Jesper: thx for enabling the functionality. Unfortunately, all the functions in codeunit "Document Service Management" are still scoped to On-prem and are file based too. Why this? We want to use it on SaaS to upload our own documents as a stream.

**Comment by JesperSchulz** [comment]
I would have to get back to you on this one. We haven't gotten around to address this request yet and I'm not sure if we're going to, as we're working on a similar story around OneDrive. Those are the changes you're seeing in that codeunit! Let me ask someone who knows a little more about our plans to reply to this thread.

**Comment by JesperSchulz** [comment]
Discussion will continue in new issue created.
