### ISSUE TITLE
Reminder - #6610 - Codeunit 950 "Time Sheet Management" - OnBeforeFilterTimeSheets - Rename parameter "FieldNo"

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#8337]
Regarding #6610 from March 2020, there is nothing to see in Insider Build 17.0.15359.0-W1.
Status since 31. March is "ships-in-future-update".
Will you still integrate it?

It is not possible to subscribe to the event publisher and to use the parameter!

**Comment by RomanZanizdra** [comment]
Hi @StHillmann .
May be the question will be looking strange for you but what the problems did you meet with subscribing on the mentioned event? I did the following exercise: create simple table with 3 boolean fields, card page for it and codeunit with subscribers. In the table there is a function which takes FieldNo as parameter and pass this parameter to the event. This function called for different fields. Codenit subscribed on the event raised by function. There is a simple message shows number of field from which the function was called. There is also a function on the page which runs FilterTimeSheets function from codeunit 950 and even which is subscribed on the OnBeforeFilterTimeSheets and also shows message with field number passed to FilterTimeSheets function. I didn't find any problems with subscribers and around. The code is below. And of course I did it on the latest version (Version: !Build Version! (Platform 17.0.16018.0 + Application 18.0.16222.0)).

table 50101 TestTable
{
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "Primary Key"; Code[10])
        {
        }
        field(2; Field2; Boolean)
        {
            trigger OnValidate()
            begin
                GetFieldNo(FieldNo(Field2));
                GetCurrFieldNo(CurrFieldNo);
            end;
        }
        field(3; Field3; Boolean)
        {
            trigger OnValidate()
            begin
                GetFieldNo(FieldNo(Field3));
                GetCurrFieldNo(CurrFieldNo);
            end;
        }
        field(4; Field4; Boolean)
        {
            trigger OnValidate()
            begin
                GetFieldNo(FieldNo(Field4));
                GetCurrFieldNo(CurrFieldNo);
            end;
        }
    }

    keys
    {
        key(PK; "Primary Key")
        {
            Clustered = true;
        }
    }

    local procedure GetFieldNo(FieldNo: Integer)
    begin
        OnGetFieldNo(FieldNo);
    end;

    local procedure GetCurrFieldNo(CurrFieldNo: Integer)
    begin
        OnGetCurrFieldNo(CurrFieldNo);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnGetFieldNo(FieldNo: Integer)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnGetCurrFieldNo(CurrFieldNo: Integer)
    begin
    end;
}

codeunit 50101 TestTable
{
    trigger OnRun()
    begin

    end;

    [EventSubscriber(ObjectType::Table, Database::TestTable, 'OnGetFieldNo', '', false, false)]
    local procedure OnGetFieldNoHandler(FieldNo: Integer)
    begin
        Message('FielNo = %1', FieldNo);
    end;

    [EventSubscriber(ObjectType::Table, Database::TestTable, 'OnGetCurrFieldNo', '', false, false)]
    local procedure OnGetCurrFieldNoHandler(CurrFieldNo: Integer)
    begin
        Message('CurrFielNo = %1', CurrFieldNo);
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Time Sheet Management", 'OnBeforeFilterTimeSheets', '', false, false)]
    local procedure OnBeforeFilterTimeSheetsHandler(FieldNo: Integer; var IsHandled: Boolean)
    begin
        IsHandled := true;
        Message('Function parameter FieldNo = %1', FieldNo);
    end;
}

page 50101 TestTable
{
    PageType = Card;
    ApplicationArea = All;
    UsageCategory = Administration;
    SourceTable = TestTable;

    layout
    {
        area(Content)
        {
            group(GroupName)
            {
                field(Field2; Field2)
                {
                }
                field(Field3; Field3)
                {
                }
                field(Field4; Field4)
                {
                }
            }
        }
    }

    actions
    {
        area(Processing)
        {
            action(ValidateField4)
            {
                ApplicationArea = All;

                trigger OnAction()
                begin
                    Validate(Field4);
                end;
            }
            action(FilterTimeSheets)
            {
                ApplicationArea = All;

                trigger OnAction()
                var
                    TimeSheetHeader: Record "Time Sheet Header";
                    TimeSheetManagement: Codeunit "Time Sheet Management";
                begin
                    TimeSheetManagement.FilterTimeSheets(TimeSheetHeader, FieldNo(Field3));
                end;
            }
        }
    }

    trigger OnOpenPage()
    begin
        if not Get() then
            Insert();
    end;
}

**Comment by RomanZanizdra** [comment]
Hi @StHillmann . Any results/updates from your side?

**Comment by StHillmann** [comment]
Hi @RomanZanizdra, sorry for late reply...
It`s fixed.

Found out, that it was corresponding to an WITH-Clause around the code.

```
With TimeSheetHeader do begin
...
....
Case FieldNo of
```
If using this code, then AL compiler is giving an error as described above.
I`ve now removed the WITH-Clauses from code and everything is fine!!
