### ISSUE TITLE
[Extensibility Request] page 40 "Item Journal" Move Item No Validate to own function ItemNoOnAfterValidate

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#8341]
Could you move the `Item No.` Validate Processing into a extra function e.g. like it is done on the sales and purchase subforms, that an extension could validate the `Item No.` and call this new procedure `ItemNoOnAfterValidate`?
At the moment I have to call `CurrPage.Update(true)`
```al
field("Item No."; "Item No.")
{
    ApplicationArea = Basic, Suite;
    ToolTip = 'Specifies the number of the item on the journal line.';

    trigger OnValidate()
    begin
        //+new
        //-ItemJnlMgt.GetItem("Item No.", ItemDescription);
        //-ShowShortcutDimCode(ShortcutDimCode);
        ItemNoOnAfterValidate();
        //-new
    end;
}
```

```al

//Proposal for a new Procedure:
procedure ItemNoOnAfterValidate()
begin
        ItemJnlMgt.GetItem("Item No.", ItemDescription);
        ShowShortcutDimCode(ShortcutDimCode);
end;
```

This would be needed on the other journal pages, too:
- page 392 "Phys. Inventory Journal"
- page 393 "Item Reclass. Journal"
- page 286 "Recurring Item Jnl."
- page 5803 "Revaluation Journal"
- page 7326 "Whse. Phys. Invt. Journal"
- etc. ...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
