### ISSUE TITLE
[Event Request change] - Codeunit 5720 Item Reference Management

### ISSUE THREAD

**Issue by bachii1010** [microsoft/ALAppExtensions#8342]
Hi,

There is an event as below in the codeunit:

 **_[IntegrationEvent(false, false)]
    local procedure OnPurchaseReferenceNoLookUpOnAfterSetFilters(ItemReference: Record "Item Reference"; PurchaseLine: Record "Purchase Line")
    begin
    end;_**

Item Reference parameter in the above event should be as **_var_**.

Can you please look into this and change ASAP?

Thanks & regards 
Varun Reddy

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
