### ISSUE TITLE
[External Request] Report Selections Table helper functions for extending reporting functionality

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#8343]
Hi, we'd like the following functions to be exposed from Report Selections. It'd be helpful when we're overriding the standard report selection functionality but still want to use standard logic for some parts. Thanks

```
local procedure GetCustomReportSelectionByUsageOption(var CustomReportSelection: Record "Custom Report Selection"; AccountNo: Code[20]; ReportUsage: Integer; TableNo: Integer): Boolean

local procedure IsSalesDocument(RecordRef: RecordRef): Boolean

local procedure ShowNoBodyNoAttachmentError(ReportUsage: Integer; FoundBody: Boolean; FoundAttachment: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
