### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function ProcessToAsmHeader - OnAfterModifyToAssemblyHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8355]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: ProcessToAsmHeader
Publisher Event: OnAfterModifyToAssemblyHeader
Reason: To implement custom business logic
Where is the event placed:
CopyFromAsmOrderDimToHdr(ToAsmHeader, TempFromAsmHeader, ToSalesLine);
            Modify;
            OnAfterModifyToAssemblyHeader(ToAsmHeader, TempFromAsmHeader, ToSalesLine, BasicAsmOrderCopy, AvailabilityCheck);
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterModifyToAssemblyHeader(var ToAsmHeader: Record "Assembly Header"; TempFromAsmHeader: Record "Assembly Header" temporary; ToSalesLine: Record "Sales Line"; BasicAsmOrderCopy: Boolean; AvailabilityCheck: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
