### ISSUE TITLE
[Event Request] Codeunit::"Dist. Integration" - Function SetFiltersTypeAndTypeNoItemCrossRef - OnAfterSetFiltersTypeAndTypeNoItemCrossRef

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8356]
We like to request the following Event:
Object: Codeunit::"Dist. Integration"
Function: SetFiltersTypeAndTypeNoItemCrossRef
Publisher Event: OnAfterSetFiltersTypeAndTypeNoItemCrossRef
Reason: To implement custom business logic
Where is the event placed:
local procedure SetFiltersTypeAndTypeNoItemCrossRef(var ItemCrossReference: Record "Item Cross Reference"; CrossRefType: Integer; CrossRefTypeNo: Code[30])
    begin
        ItemCrossReference.SetRange("Cross-Reference Type", CrossRefType);
        ItemCrossReference.SetRange("Cross-Reference Type No.", CrossRefTypeNo);
        OnAfterSetFiltersTypeAndTypeNoItemCrossRef(ItemCrossReference, CrossRefType, CrossRefTypeNo);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterSetFiltersTypeAndTypeNoItemCrossRef(var ItemCrossReference: Record "Item Cross Reference"; CrossRefType: Integer; CrossRefTypeNo: Code[30])
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
