### ISSUE TITLE
[Event Request] Codeunit::"Output Jnl.-Expl. Route" - Function OnRun - OnAfterInsertOutputJnlLineWithoutRtngLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8359]
We like to request the following Event:
Object: Codeunit::"Output Jnl.-Expl. Route"
Function: OnRun
Publisher Event: OnAfterInsertOutputJnlLineWithoutRtngLine
Reason: To implement custom business logic
Where is the event placed:
InsertOutputJnlLine(
                      Rec, NextLineNo, LineSpacing,
                      ProdOrderLine."Line No.",
                      ProdOrderLine."Item No.",
                      ProdOrderLine."Variant Code",
                      ProdOrderLine."Location Code",
                      ProdOrderLine."Bin Code",
                      ProdOrderLine."Routing No.", ProdOrderLine."Routing Reference No.", '',
                      ProdOrderLine."Unit of Measure Code",
                      ProdOrderLine."Remaining Quantity",
                      true);
                    OnAfterInsertOutputJnlLineWithoutRtngLine(ItemJnlLine, ProdOrderLine, ProdOrderRtngLine, NextLineNo);
                    ItemTrackingMgt.CopyItemTracking(ProdOrderLine.RowID1, LastItemJnlLine.RowID1, false);
                end;
        until ProdOrderLine.Next = 0;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterInsertOutputJnlLineWithoutRtngLine(var ItemJournalLine: Record "Item Journal Line"; var ProdOrderLine: Record "Prod. Order Line"; var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var NextLineNo: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
