### ISSUE TITLE
[Event Request] Codeunit::"Prod. Order Line-Reserve" - Function TransferPOLineToItemJnlLine - OnBeforeHandleItemTrackingOnOutput

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8360]
We like to request the following Event:
Object: Codeunit::"Prod. Order Line-Reserve"
Function: TransferPOLineToItemJnlLine
Publisher Event: OnBeforeHandleItemTrackingOnOutput
Reason: To implement custom business logic
Where is the event placed:
procedure TransferPOLineToItemJnlLine(var OldProdOrderLine: Record "Prod. Order Line"; var NewItemJnlLine: Record "Item Journal Line"; TransferQty: Decimal)
    var
        OldReservEntry: Record "Reservation Entry";
        ItemTrackingFilterIsSet: Boolean;
        EndLoop: Boolean;
        ItemTrackingHandleNeeds: Boolean;
    begin
        if not FindReservEntry(OldProdOrderLine, OldReservEntry) then
            exit;
        OldReservEntry.Lock;
        ItemTrackingHandleNeeds := true;
        OnBeforeHandleItemTrackingOnOutput(OldProdOrderLine, NewItemJnlLine, OldReservEntry, ItemTrackingHandleNeeds);
        // Handle Item Tracking on output:
        Clear(CreateReservEntry);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeHandleItemTrackingOnOutput(var OldProdOrderLine: Record "Prod. Order Line"; var NewItemJnlLine: Record "Item Journal Line"; var OldReservEntry: Record "Reservation Entry"; var ItemTrackingHandleNeeds: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
