### ISSUE TITLE
[Event Request] Codeunit::"Production Journal Mgt" - Function InsertOutputJnlLine - OnBeforeHandleInsertOutputJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8361]
We like to request the following Event:
Object: Codeunit::"Production Journal Mgt"
Function: InsertOutputJnlLine
Publisher Event: OnBeforeHandleInsertOutputJnlLine
Reason: To implement custom business logic
Where is the event placed:
local procedure InsertOutputJnlLine(ProdOrderRtngLine: Record "Prod. Order Routing Line"; ProdOrderLine: Record "Prod. Order Line")
    var
        WorkCenter: Record "Work Center";
        MachineCenter: Record "Machine Center";
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        CostCalcMgt: Codeunit "Cost Calculation Management";
        QtyToPost: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeHandleInsertOutputJnlLine(ProdOrderRtngLine, ProdOrderLine, IsHandled);
        if IsHandled then
            exit;
        with ProdOrderLine do begin
            if ProdOrderRtngLine."Prod. Order No." <> '' then // Operation exist
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeHandleInsertOutputJnlLine(ProdOrderRtngLine: Record "Prod. Order Routing Line"; ProdOrderLine: Record "Prod. Order Line"; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
