### ISSUE TITLE
[Event Request] codeunit 333 "Req. Wksh.-Make Order" - Event OnFinalizeOrderHeaderOnAfterSetFiltersForNonRecurringReqLine

### ISSUE THREAD

**Issue by osteeger** [microsoft/ALAppExtensions#8362]
Can we change the following events for the "Req. Wksh.-Make Order" Codeunit: **OnFinalizeOrderHeaderOnAfterSetFiltersForNonRecurringReqLine**

```
    ///
    //[IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    ///-
    local procedure OnFinalizeOrderHeaderOnAfterSetFiltersForNonRecurringReqLine(var RequisitionLine: Record "Requisition Line"; PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
