### ISSUE TITLE
[Additional Parameter Request] Table 37 Sales Line - OnBeforeAutoReserve

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8363]
Hi Team,

In table 37 we need to add two additional parameters (FullAutoReservation and ReserveSalesLine) to standard event publisher OnBeforeAutoReserve - as we have important customization in our solution which can be moved to subscriber in easy way having additional parameters.

![image](https://user-images.githubusercontent.com/69669749/91044109-6ddf1d00-e61d-11ea-97d1-1bc60c487cca.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeAutoReserve(var SalesLine: Record "Sales Line"; var xSalesLine: Record "Sales Line"; var IsHandled: Boolean; **var FullAutoReservation: Boolean; var ReserveSalesLine: Codeunit "Sales Line-Reserve")**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
