### ISSUE TITLE
[Event Request] Table 37 Sales Line - OnBeforeCreateDim

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8364]
Hi Team,

In table 37 we need possibility to replace standard code with our own. Having event with handling in the beginning of procedure Create Dim would be perfect solution:

![image](https://user-images.githubusercontent.com/69669749/91044684-5c4a4500-e61e-11ea-9711-2397d68f506d.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeCreateDim(var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
