### ISSUE TITLE
[Event Request] Table 37/39/210/753/5406/5407/5902 - OnAfterGetSKU

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8365]
Hi team,

We need the same standard event publisher in a set of standard tables - as all these tables have identical GetSKU procedure. We need to add additional conditions when GetSKU procedure returns "true" in tables:

37 Sales Line
39 Purchase Line
210 Job Journal Line
753 Standard Item Journal Line
5406 Prod. Order Line
5407 Prod. Order Component
5902 Service Line
(there are are several more tables with the same GetSKU function in production module - but we do not use it in our customizations. From global point of view other tables with GetSKU function should have the same extensibility most probably).

Our proposed new publisher:
![image](https://user-images.githubusercontent.com/69669749/91048351-39bb2a80-e624-11ea-9608-0045f5232f0e.png)

and declarations:
local procedure OnAfterGetSKU(Rec: Record "Sales Line"; var IsHandled: Boolean)
local procedure OnAfterGetSKU(Rec: Record "Purchase Line"; var IsHandled: Boolean)
local procedure OnAfterGetSKU(Rec: Record "Job Journal Line"; var IsHandled: Boolean)
local procedure OnAfterGetSKU(Rec: Record "Standard Item Journal Line"; var IsHandled: Boolean)
local procedure OnAfterGetSKU(Rec: Record "Prod. Order Line"; var IsHandled: Boolean)
local procedure OnAfterGetSKU(Rec: Record "Prod. Order Component"; var IsHandled: Boolean)
local procedure OnAfterGetSKU(Rec: Record "Service Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by PerVL** [comment]
I can see, that something has changed so in the base app it now says : 

    procedure GetSKU(var StockkeepingUnit: Record "Stockkeeping Unit") Result: Boolean
    begin
        if (StockkeepingUnit."Location Code" = "Location Code") and
           (StockkeepingUnit."Item No." = "No.") and
           (StockkeepingUnit."Variant Code" = "Variant Code")
        then
            exit(true);

        if StockkeepingUnit.Get("Location Code", "No.", "Variant Code") then
            exit(true);

        Result := false;
        OnAfterGetSKU(Rec, Result, StockkeepingUnit);
    end;

But this way Result will always be FALSE, when the event trigger is raised, and it will only be triggered, when the SKU cannot be gotten.

So either the trigger should be renamed to OnAfterNotGetSKU, or the code should be something like : 

    procedure GetSKU(var StockkeepingUnit: Record "Stockkeeping Unit") Result: Boolean
    begin
        Result := false;
        if not((StockkeepingUnit."Location Code" = "Location Code") and
           (StockkeepingUnit."Item No." = "No.") and
           (StockkeepingUnit."Variant Code" = "Variant Code"))
        then
            if StockkeepingUnit.Get("Location Code", "No.", "Variant Code") then
                Result :=true;
        else
            Result := true;

        OnAfterGetSKU(Rec, Result, StockkeepingUnit);

        exit(Result);
    end;
