### ISSUE TITLE
Access to X509Certificate expiration date

### ISSUE THREAD

**Issue by ftornero9** [microsoft/ALAppExtensions#8366]
I need to check the expiration date of a digital certificate and looks like the codeunit 3043 (DotNet_X509Certificate2) could do the trick but the procedure X509Certificate2 below, need a third parameter refering to the codeunit 3041 (DotNet_X509KeyStorageFlags)

`procedure X509Certificate2(DotNet_Array: Codeunit DotNet_Array; Password: Text; DotNet_X509KeyStorageFlags: Codeunit DotNet_X509KeyStorageFlags)`

But it is not possible to use any of the procedures in this last codeunit for Extensions.

So I asking for one of these solutions or maybe the two:

- Allow to use the procedure Exportable in the codeunit 3041 (DotNet_X509KeyStorageFlags) for  Extensions.

- Create a new (or 2 to be on line with the 2 procedures that already are in the codeunit) procedure X509Certificate2 in the codeunit 3043 (DotNet_X509Certificate2) without the third parameter before mentioned.

Regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.
