### ISSUE TITLE
CODEUNIT 5982 - "Service-Post+Print" > OnBeforeConfirmPost : var ServiceLine is missing

### ISSUE THREAD

**Issue by BoulyFamily** [microsoft/ALAppExtensions#8369]
- AL Extension Version: 16.1.12629.12805

In Codeunit 5981 Event **OnBeforeConfirmPost** has these parameters:
     var ServiceHeader: Record "Service Header";
     var HideDialog: Boolean;
     var Ship: Boolean;
     var Consume: Boolean;
     var Invoice: Boolean;
     var IsHandled: Boolean;
     PreviewMode: Boolean;
     **var ServiceLine: Record "Service Line"**

In Codeunit 5982, Event **OnBeforeConfirmPost** ... Parameter ServiceLine is missing
     var ServiceHeader: Record "Service Header";      
     var HideDialog: Boolean; 
     var Ship: Boolean; var Consume: Boolean; 
     var Invoice: Boolean; 
     var IsHandled: Boolean

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
