### ISSUE TITLE
New Variable CU57 OnAfterCalcSalesSubPageTotals & OnAfterCalcPurchSubPageTotals

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#837]
**Before** on Function CalculateSalesSubPageTotals Add TotalSalesLine2 to Publisher OnAfterCalcSalesSubPageTotals
![image](https://user-images.githubusercontent.com/32099690/51132106-9e7a9600-17ee-11e9-9468-f7634e14792a.png)
![image](https://user-images.githubusercontent.com/32099690/51132118-a6d2d100-17ee-11e9-996d-13635872f081.png)

**After**
![image](https://user-images.githubusercontent.com/32099690/51132152-beaa5500-17ee-11e9-8ed6-93974266f9ee.png)
![image](https://user-images.githubusercontent.com/32099690/51132194-d8e43300-17ee-11e9-9ab2-06d4c940258d.png)

**Before** on Function CalculatePurchaseSubPageTotals Add TotalSalesLine2 to Publisher OnAfterCalcPurchaseSubPageTotals
![image](https://user-images.githubusercontent.com/32099690/51132276-121ca300-17ef-11e9-87a8-b74ef08eda1c.png)
![image](https://user-images.githubusercontent.com/32099690/51132316-295b9080-17ef-11e9-8748-7e51ed9a4ae0.png)

**After**
![image](https://user-images.githubusercontent.com/32099690/51132328-34162580-17ef-11e9-96b4-d1eaf34db5e0.png)
![image](https://user-images.githubusercontent.com/32099690/51132344-3ed0ba80-17ef-11e9-9088-3db3f63c9fbb.png)

**Comment by sradouan** [comment]
Hi ,
The Record TotalSalesLine is not accessible from the extension page of  "Sales Invoice Subform"
 addafter("Total Amount Incl. VAT")
        {
            field("Total ValueOfWork"; TotalSalesLine.ValueOfWork)
            {
                ApplicationArea = All;
            }
is there any solution for the new fileds added in sales line and we want to added in the total of Sales Invoice Subform?

Thanks,
