### ISSUE TITLE
Codeunit 99000845 "Reservation Management": OnAfterSetReservSource

### ISSUE THREAD

**Issue by SzabolcsGyorke** [microsoft/ALAppExtensions#8370]
Hi,

I was trying to integrate with the reservation system with a custom journal. However, I can`t finish the process with the current events. I`m trying to do a Positive allocation against Item Ledger Entries.

As standard in CU Reservation Management - function SetReservSource() all the nominated tables (Sales Line, Purchase Line) in the case statement ultimately calls the UpdateReservation() local function.

I can add my table with the event OnSetReservSource() but after that I can`t run the UpdateReservation() function.

My request would be a new event after the Case statement: 

 procedure SetReservSource(NewSourceRecref: RecordRef; Direction: Enum "Transfer Direction")
  //>>new
    var
       RunUpdateReservation: Boolean;
       UpdateReservationPositive: Boolen;
  //<<new  
  ...
  Case SouceRecRef.Number of
      ...
      DATABASE::"Assembly Line":
         SetSourceForAssemblyLine;
   end;
  //>>new
  OnAfterSetReservSource(SourceRecRef, CalcReservEntry, Direction, RunUpdateReservation, UpdateReservationPositive);
  if RunUpdateReservation then
    UpdateReservation(UpdateReservationPositive);
  //<<new
end; 

[IntegrationEvent(false, false)]
local procedure OnAfterSetReservSource(SourceRecRef: RecordRef; var ReservEntry: Record "Reservation Entry"; Direction: Enum "Transfer Direction"; var RunUpdateReservation: Boolean; var UpdateReservationPositive: Boolean)
begin
end;

**Comment by StanPesotskiy** [comment]
The code structure of function SetReservSource() has been already changed. 
Check if the existent event OnSetReservSource() is suitable or provide the suggestion with actual code version.

**Comment by SzabolcsGyorke** [comment]
Thanks, checked V16.4 it looks ok with the added overloads.
