### ISSUE TITLE
[Additional Parameter Request] Table 37 Sales Line - OnAfterInitHeaderDefaults

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8371]
Hi Team,

In Table 37 we need to customize standard procedure InitHeaderDefaults a little - standard event OnAfterInitHeaderDefaults fits perfectly for it, but we need to pass xRec parameter to be able to restore original value if our custom conditions are not met. Our proposal for additional parameter:

![image](https://user-images.githubusercontent.com/69669749/91276388-2aee8800-e78a-11ea-84c0-3a18aca79fac.png)

[IntegrationEvent(false, false)]
local procedure OnAfterInitHeaderDefaults(var SalesLine: Record "Sales Line"; **xRecSalesLine: Record "Sales Line";** SalesHeader: Record "Sales Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
