### ISSUE TITLE
[Event Request] Codeunit 6620 OnBeforeCleanSpecialOrderDropShipmentInSalesLine and OnBeforeCleanSpecialOrderDropShipmentInPurchLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8372]
We Need a two new Event trigger OnBeforeCleanSpecialOrderDropShipmentInSalesLine and OnBeforeCleanSpecialOrderDropShipmentInPurchLine in Codeunit 6620 "Copy Document Mgt.":

Procedure CopyArchSalesLine
…
  ToSalesLine."Appl.-from Item Entry" := 0;
  ToSalesLine."Appl.-to Item Entry" := 0;

  //+++++++++++++++++++++++++++++++++++++++++++
  OnBeforeCleanSpecialOrderDropShipmentInSalesLine(VAR ToSalesHeader : Record "Sales Header";VAR ToSalesLine : Record "Sales Line";VAR FromSalesHeader : Record "Sales Header";VAR FromSalesLine : Record "Sales Line";CreateToHeader : Boolean)
  //-------------------------------------------
  CleanSpecialOrderDropShipmentInSalesLine(ToSalesLine);

Procedure CopyArchPurchLine
…
  ToPurchLine."Appl.-to Item Entry" := 0;

  IF FromPurchLineArchive."Drop Shipment" OR FromPurchLineArchive."Special Order" THEN
    ToPurchLine."Purchasing Code" := '';
  //+++++++++++++++++++++++++++++++++++++++++++
  OnBeforeCleanSpecialOrderDropShipmentInPurchLine(VAR ToPurchHeader : Record "Purchase Header";VAR ToPurchLine : Record "Purchase Line";VAR FromPurchHeader : Record "Purchase Header";VAR FromPurchLine : Record "Purchase Line";CreateToHeader : Boolean)
  //-------------------------------------------
  CleanSpecialOrderDropShipmentInPurchLine(ToPurchLine);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
