### ISSUE TITLE
[Event Request] Base Application, Codeunit 134262 "Bank Pmt. Appl. Tolerance

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8379]
[Event Request] Base Application, Codeunit 134262 "Bank Pmt. Appl. Tolerance"
![pic1](https://user-images.githubusercontent.com/45795262/91329559-95beb400-e7c8-11ea-81d0-7ec84251f6fb.png)

Could you please insert an Initialize-Call at the beginning of all test procedures in the codeunit and an Initialize procedure like in other test codeunits?
![pic2](https://user-images.githubusercontent.com/45795262/91329581-9c4d2b80-e7c8-11ea-80a8-e396bc539dff.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
