### ISSUE TITLE
[Event Request] Application Tests-Local Codeunit 142076 "Payment Tolerance"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8381]
![pic1](https://user-images.githubusercontent.com/45795262/91330066-3ca35000-e7c9-11ea-9132-1554ccb05bf7.png)

[Event Request] Application “Tests-Graph”, Codeunit 142076 "Payment Tolerance"
Could you please insert the OnTestInitialize Event at the beginning of the procedures SalesPmtDiscountDateWhenUseZeroPmtDisc, PurchPmtDiscountDateWhenUseZeroPmtDisc?
![pic2](https://user-images.githubusercontent.com/45795262/91330082-40cf6d80-e7c9-11ea-8211-ed22faabd304.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
