### ISSUE TITLE
[Event Request] Application Tests-Misc Codeunit 134235 "Record Set UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8383]
![pic1](https://user-images.githubusercontent.com/45795262/91330530-da971a80-e7c9-11ea-928e-501f1bb1a1ac.png)

[Event Request] Application “Tests-Misc”, Codeunit 134235 "Record Set UT"

Could you please insert the OnTestInitialize Event at the beginning of the test procedure FindRecordMgt_FindRecordByNo_GLAccountFilters?
![pic2](https://user-images.githubusercontent.com/45795262/91330554-e256bf00-e7c9-11ea-9d61-44d32c5df15e.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
