### ISSUE TITLE
[Event Request] Application Tests-Misc Codeunit 138400 "RS Pack Content - Evaluation"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8384]
![pic1](https://user-images.githubusercontent.com/45795262/91330737-20ec7980-e7ca-11ea-98b5-4e24f1d02905.png)

[Event Request] Application “Tests-Misc”, Codeunit 138400 "RS Pack Content - Evaluation"

Could you please insert the OnTestInitialize Event at the beginning of the procedure PostSalesInvoices?
 
![pic2](https://user-images.githubusercontent.com/45795262/91330751-24800080-e7ca-11ea-961b-3f2fa882f3b5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
