### ISSUE TITLE
[Event Request] Application Tests-Rapid Start Codeunit 136611 "ERM RS Dimensions as Columns"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8385]
![pic1](https://user-images.githubusercontent.com/45795262/91330872-51341800-e7ca-11ea-82e5-6d4446ee21de.png)

[Event Request] Application “Tests-Graph”, Codeunit 136611 "ERM RS Dimensions as Columns"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure?
![pic2](https://user-images.githubusercontent.com/45795262/91330904-598c5300-e7ca-11ea-8b6e-bf19a8d5a386.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
