### ISSUE TITLE
[Event Request] CU 5987 PostSalesTaxToGL no events

### ISSUE THREAD

**Issue by MattR818** [microsoft/ALAppExtensions#8388]
PostSalesTaxToGL function in Codeunit 5987 which posts NA sales tax for service documents has no events at all.  Probably the only function like this I've seen lately where we cannot touch the GenJnlLine to add our custom posting values.  At least a CopyFromServiceHeader like there is in the PostCustomerEntry would be good.  Would also like some at the end to track the postings as well but anything would be a start thank you!

**Comment by RomanZanizdra** [comment]
Hi @MattR818 . Please be precise in description of what event should added, where it should be added and with which parameters.
You can take a look at this request for example https://github.com/microsoft/ALAppExtensions/issues/8389 or others.

**Comment by MattR818** [comment]
Thanks @RomanZanizdra  .

In ServPostingJournalsMgt.Codeunit.al , Codeunit 5987 "Serv-Posting Journals Mgt." , in function PostSalesTaxToGL , please add the the following event before the GenJnlLine is posted (this is similar to SalesPost codeunit 80):
```

                    if ServiceHeader."Currency Code" <> '' then
                        TotalServiceLineLCY."Amount Including VAT" :=
                          TotalServiceLineLCY."Amount Including VAT" + GenJnlLine."VAT Amount (LCY)";
+                   OnBeforePostSalesTaxToGL(GenJnlLine, ServiceHeader, TempSalesTaxAmtLine);
                    GenJnlPostLine.RunWithCheck(GenJnlLine);
                end;
            until TempSalesTaxAmtLine.Next = 0;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostSalesTaxToGL(var GenJnlLine: Record "Gen. Journal Line"; ServiceHeader: Record "Service Header"; SalesTaxAmountLine: Record "Sales Tax Amount Line")
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
