### ISSUE TITLE
[Event Request] Page 291 "Req. Worksheet" - OnBeforeGetSalesOrder

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#8396]
Can we get please the following event:

```al

    action(Action53)
    {
...
        trigger OnAction()
        begin
            GetSalesOrder.SetReqWkshLine(Rec, 1);
            OnGetSalesOrderSpecialOrderActionOnBeforeGetSalesOrderRunModal(GetSalesOrder, Rec);//new
            GetSalesOrder.RunModal;
            Clear(GetSalesOrder);
        end;
    }
```

```al
[IntegrationEvent(false,false)]
local procedure OnGetSalesOrderSpecialOrderActionOnBeforeGetSalesOrderRunModal(var GetSalesOrder: Report "Get Sales Orders";var RequisitionLine: Record "Requisition Line")
begin
end;
```

**Comment by pri-kise** [comment]
You could call the event you added for the other https://github.com/microsoft/ALAppExtensions/issues/7860
if you add an additional parameter `SpecOrder` ([0,1]) to show where this event is called. I don't know what's the best practice for such cases.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
