### ISSUE TITLE
[Event Request] Table 5900 - GetServiceSetup

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8397]
Could you please replace "ServiceSetup.get();" with appropriate function GetServiceSetup() as in sales/purchase, with integration event. We need this for allowing different setups for different user cases.

Thank you

local procedure GetServiceSetup()
begin
    ServiceSetup.Get();
    OnAfterGetServiceSetup(Rec, ServiceSetup, CurrFieldNo);
end;

[IntegrationEvent(false, false)]
local procedure OnAfterGetServiceSetup(ServiceHeader: Record "Service Header"; var ServiceSetup: Record "Service Setup"; CalledByFieldNo: Integer)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
