### ISSUE TITLE
[Event Request] codeunit 5988 "Serv-Documents Mgt." - Event for procedure Finalize

### ISSUE THREAD

**Issue by ysoldati** [microsoft/ALAppExtensions#8403]
Can we get the following event for the "Serv-Documents Mgt." **Codeunit: OnAfterFinalizeWarrantyLedgerEntries**
We want to implement our functionnality to archive service orders because it is not done in standard

    procedure Finalize(var PassedServHeader: Record "Service Header")
    begin
        OnBeforeFinalize(PassedServHeader, CloseCondition);

        // finalize codeunits calls
        ServPostingJnlsMgt.Finalize();

        // finalize posted documents
        FinalizeShipmentDocument();
        FinalizeInvoiceDocument();
        FinalizeCrMemoDocument();
        FinalizeWarrantyLedgerEntries(PassedServHeader, CloseCondition);

        OnAfterFinalizeWarrantyLedgerEntries(PassedServHeader, IsHandled);   //NEW

        if not IsHandled then begin //NEW
        if ((ServHeader."Document Type" = ServHeader."Document Type"::Order) and CloseCondition) or
           (ServHeader."Document Type" <> ServHeader."Document Type"::Order)
        then begin
            // Service Lines, Service Item Lines, Service Header
            FinalizeDeleteLines();
            FinalizeDeleteServOrdAllocat();
            FinalizeDeleteItemLines();
            FinalizeDeleteComments(PassedServHeader."Document Type");

            FinalizeDeleteHeader(PassedServHeader);
        end else begin
            // Service Lines, Service Item Lines, Service Header
            FinalizeLines();
            FinalizeItemLines();

            FinalizeHeader(PassedServHeader);
        end;
        end; //NEW

        OnAfterFinalize(PassedServHeader, CloseCondition);
    end;

```
[IntegrationEvent(false, false)]
    local procedure OnFinalizeOnAfterIfStatement(var PassedServHeader: Record "Service Header"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
