### ISSUE TITLE
[Event Request]  Codeunit 8800  Custom Layout Reporting, OnAfterGenerateFileNameForReport

### ISSUE THREAD

**Issue by simpson123** [microsoft/ALAppExtensions#8404]
When running batch reports (like Customer Statements) from BC Web Client, the output PDF files are zipped for download to client.  However the filenames (in the zip) are fixed format and can't be currently set. Which is a limitation.

Request to include integration event(s) to allow the Filenames to be set by new integration Event Handler

My suggestion is a new Integration Event(s) added to Codeunit 8800 Procedure "Custom Layout Reporting"  raised here:
///
local procedure GenerateFileNameForReport(ReportID: Integer; Extension: Text; FilePath: Text; DataRecRef: RecordRef): Text[250]

defined like this

///...
OnAfterGenerateFileNameForReport((ReportID: Integer; Extension: Text; FilePath: Text; DataRecRef: RecordRef): Text[250]; VAR GeneratedName: Text[250])
///...

Subscriber code can then change then optionally change the  GeneratedName   - For Example a subscriber - could then examine the DataRecRef and update the GeneratedName to include the Customer."No." in the Statement's PDF filename....

Thanks.  Simon Henson

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
