### ISSUE TITLE
[Event Request] table 5409 "Prod. Order Routing Line" - OnAfterCopyFromPlanningRoutingLine

### ISSUE THREAD

**Issue by HHynynen** [microsoft/ALAppExtensions#8405]
There is an event for OnAfterCopyFromRoutingLine(Rec, RoutingLine), 
but not for OnAfterCopyFromPlanningRoutingLine.

Could you please add that event, we have an urgent need for it. Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
