### ISSUE TITLE
[Event Request] Codeunit 90 "PostItemTrackingLine" - OnBeforePostItemTrackingLineOnPostPurchLine

### ISSUE THREAD

**Issue by rodotto** [microsoft/ALAppExtensions#8407]
The existing event should be supplemented with a var on the variable IsHandled.

so far:
 [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemTrackingLineOnPostPurchLine(PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; IsHandled: Boolean)
    begin
    end;

new:
 [IntegrationEvent(false, false)]
 local procedure OnBeforePostItemTrackingLineOnPostPurchLine(PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; **var** IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
