### ISSUE TITLE
Transfer of purchase return shipment lines to purchase invoice

### ISSUE THREAD

**Issue by rodotto** [microsoft/ALAppExtensions#8408]
Various of our customers receive monthly invoices, especially from pharmaceutical suppliers, which also contain credit items. 

In NAV2017 we have modified the code to be able to transfer and post return shipment lines in addition to receipt lines in a purchase invoice. 

From our point of view this corresponds to a general customer need and should actually be part of the standard.

Alternatively I tried to make the implementation individual:

- New menu item "Retrieve return delivery lines" created on P55
- Created a new CU similar to the standard code units 74/6648, which calls up a page to select the purchase returns to be inserted and then transmits the purchase invoice
- Subscribe Event OnAfterPostUpdateInvoiceLine on CU 90 to Update the Return Order Lines

To complete the Use Case the following adjustments would be necessary:

**Codeunit 90 Purch.-Post**
- Add new event OnBeforePostItemTrackingForShipment(var ReturnShptLine, PurchHeader) to procedure PostItemTrackingForShipment
```
local procedure PostItemTrackingForShipment(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; TrackingSpecificationExists: Boolean; var TempTrackingSpecification: Record "Tracking Specification" temporary)
    var
        ReturnShptLine: Record "Return Shipment Line";
        ItemEntryRelation: Record "Item Entry Relation";
        EndLoop: Boolean;
        QtyToBeInvoiced: Decimal;
        QtyToBeInvoicedBase: Decimal;
        IsHandled: Boolean;
    begin
        with PurchHeader do begin
            EndLoop := false;
            ReturnShptLine.Reset();
            OnBeforePostItemTrackingForShipment(ReturnShptLine, PurchHeader)
```
- In procedure PostItemTracking call function IsCreditDocType from Purchase Line instead of Purchase Head

   so far:
   `if IsCreditDocType then begin`

   new:
   `if PurchLine.IsCreditDocType then begin`

- Change Code in procedure TestPurchLine

   so far:
   ```
   if "Receipt No." = '' then
     TestField("Qty. to Receive", Quantity);
   ```

   new:
   ```
   if ("Receipt No." = '') and ("Return Shipment No." = '') then
     TestField("Qty. to Receive", Quantity);
   ```

**Table 39**
- Add new Event OnBeforeIsCreditDocType to procedure IsCreditDocType analogous to the corresponding function on table 38

so far:
```
procedure IsCreditDocType(): Boolean
    begin
        exit("Document Type" in ["Document Type"::"Return Order", "Document Type"::"Credit Memo"]);
    end;
```

new:
 ```
procedure IsCreditDocType(): Boolean
    var
        CreditDocType: Boolean;
    begin
        CreditDocType := "Document Type" in ["Document Type"::"Return Order", "Document Type"::"Credit Memo"];
        OnBeforeIsCreditDocType(Rec, CreditDocType);
        exit(CreditDocType);
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
