### ISSUE TITLE
[Extensibility enhancement] Table 36 - Delete Sales Lines

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#8409]
Could you move this code from the OnDelete-Trigger of Table 36 to a global function so that it can be called from an extension (would make life easier if I want to delete all lines that belong to a header):

![image](https://user-images.githubusercontent.com/46022628/91741827-8e771c00-ebb5-11ea-91d1-7b5bc8c8c99d.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
