### ISSUE TITLE
[Event Request] Codeunit 6500 "Item Tracking Management" OnBeforeCopyItemTracking3

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#8410]
Hello together,

in a manufacturing process it should be possible that within a predefined item tracking in the Prod. Order Line (same on Prod. Order Component), only a certain lot/serial number is finished or should be consumed.

To influence the filtering of the reservation entry, for example to enter a lot number, I need a publisher.
Otherwise a CalcSums of the quantity will be made on all lines of the Item Tracking later on and this quantity will not match the quantity of the Item Journal Line anymore, so that you are currently forced to finish the last operation completely (which actually does'nt always have to be the case.

![image](https://user-images.githubusercontent.com/9529836/91825516-ae055780-ec3c-11ea-91fa-66ac68d86e6b.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
