### ISSUE TITLE
[Event Request] Codeunit 5601 "FA Insert G/L Account" OnBeforeInsertBufferEntryMaintAccNo

### ISSUE THREAD

**Issue by rungis75** [microsoft/ALAppExtensions#8413]
Hello

My customer needs to change Account No. on FAGLPostBuffer before it is inserted.
So I need a new Event right before InsertBufferEntry is used.
Example in function InsertMaintenanceAccNo
  FAGLPostBuf."FA Entry Type" := FAGLPostBuf."FA Entry Type"::Maintenance;
  GLEntryNo := "G/L Entry No.";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  OnBeforeInsertBufferEntryMaintAccNo(FAGLPostBuf,MaintenanceLedgEntry);  
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  InsertBufferEntry;

LOCAL [IntegrationEvent] OnBeforeInsertBufferEntryMaintAccNo(VAR FAGLPostBuf : Record "FA G/L Posting Buffer";MaintenanceLedgEntry : Record "Maintenance Ledger Entry")

**Comment by RomanZanizdra** [comment]
Hi @rungis75 .
It's not clear if you need event in particular place before InsertBuffer or before all calls of InsertBuffer function. If before all then there is event OnInsertBufferEntryOnBeforeBufferInsert(TempFAGLPostBuf, FAGLPostBuf) in the InsertBufferEntry() function. Does it fit to you? Or please be precise where you it.

**Comment by rungis75** [comment]
Hi Roman

 

Sorry, this event should only be in function InsertMaintenanceAccNo

Because I need to have MaintenanceLedgEntry in my Event and use it in my subscriber

I can not use OnInsertBufferEntryOnBeforeBufferInsert(TempFAGLPostBuf,FAGLPostBuf)  because when I use it from InsertMaintenanceAccNo I can not get FAGLPostBuf because it is inserted after that.

 

Hope this will explain what I am talking about

 

Brg

Runar

 

 






Rúnar Birgir Gíslason
Hugbúnaðarsérfræðingur / Software Specialist
BC ráðgjöf – LV1 / Viðskiptalausnir

 





 <https://www.advania.is/disclaimer> Skilmálar/Disclaimer

**Comment by RomanZanizdra** [comment]
Hi again @rungis75 .
Please check at least the latest 16 version. I see the required event is already there. And if this is what you need than let's close current issue.

    procedure InsertMaintenanceAccNo(var MaintenanceLedgEntry: Record "Maintenance Ledger Entry")
    begin
        with MaintenanceLedgEntry do begin
            Clear(FAGLPostBuf);
            FAGLPostBuf."Account No." := FAGetGLAcc.GetMaintenanceAccNo(MaintenanceLedgEntry);
            FAGLPostBuf.Amount := Amount;
            FAGLPostBuf.Correction := Correction;
            FAGLPostBuf."Global Dimension 1 Code" := "Global Dimension 1 Code";
            FAGLPostBuf."Global Dimension 2 Code" := "Global Dimension 2 Code";
            FAGLPostBuf."Dimension Set ID" := "Dimension Set ID";
            FAGLPostBuf."FA Entry No." := "Entry No.";
            FAGLPostBuf."FA Entry Type" := FAGLPostBuf."FA Entry Type"::Maintenance;
            GLEntryNo := "G/L Entry No.";
            OnInsertMaintenanceAccNoOnBeforeInsertBufferEntry(FAGLPostBuf, MaintenanceLedgEntry);
            InsertBufferEntry;
            "G/L Entry No." := TempFAGLPostBuf."Entry No.";
        end;
    end;

**Comment by rungis75** [comment]
Thank you, I can use that.
I looked at build 13779 and it was not there.
You can close this ticket please
