### ISSUE TITLE
[Event Request] Table 98 General Ledger Setup - OnHandleFirstAllowedPostingDate

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8414]
Hi Team,

In table 98 we need possibility to replace standard code with our own. Having event with handling in the beginning of procedure `FirstAllowedPostingDate` would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/91842569-f7fe3580-ec5c-11ea-9435-ea8c99027b59.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnHandleFirstAllowedPostingDate(GeneralLedgerSetup: Record "General Ledger Setup"; var AllowedPostingDate: Date; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
