### ISSUE TITLE
[Event Request] Table 7320 - OnBeforeSortWhseDoc 

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#8415]
Add new integration event **OnBeforeSortWhseDoc** in Table 7320.

Function SortWhseDoc:

```
    VAR
      ...
+     IsHandled@100000000 : Boolean;
    BEGIN
+     IsHandled := FALSE;
+     OnBeforeSortWhseDoc(Rec, IsHandled);
+     IF IsHandled THEN
+       EXIT;

     ...
```

 New publisher function:
 
 ```
     [Integration]
     LOCAL PROCEDURE OnBeforeSortWhseDoc@100000000(WhseShptHeader@100000000 : Record 7320;VAR isHandled@100000001 : Boolean);
     BEGIN
     END;
 ```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
