### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnBeforeSetCurrencyCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8416]
Hi Team,

In table 81 we need possibility to replace standard code with our own. Having event with handling in the beginning of procedure `SetCurrencyCode` would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/91850791-cf7b3900-ec66-11ea-8ca5-ca63af41b072.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetCurrencyCode(AccType2: Option "G/L Account",Customer,Vendor,"Bank Account"; AccNo2: Code[20]; GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
