### ISSUE TITLE
[Additional Parameter Request] Table 81 Gen. Journal Line - OnBeforeCheckIfPostingDateIsEarlier

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8417]
Hi Team,
In table 81 we need possibility to have additional checks on the start of procedure `CheckIfPostingDateIsEarlier` . Standard publisher would suit us if it had additional parameter with record Customer Ledger Entry.  `OnBeforeCheckIfPostingDateIsEarlier` would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/91853814-6c3fd580-ec6b-11ea-90bf-8382e282d671.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeCheckIfPostingDateIsEarlier(**CustLedgEntry: Record "Cust. Ledger Entry"**; GenJournalLine: Record "Gen. Journal Line"; ApplyPostingDate: Date; ApplyDocType: Option " ",Payment,Invoice,"Credit Memo","Finance Charge Memo",Reminder,Refund; ApplyDocNo: Code[20]; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
