### ISSUE TITLE
[Event Request] Table 83 Item Journal Line - OnAfterGetLocation

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8418]
Hi Team,

In table 83 we need possibility to replace standard code with our own. Having event at the end of the procedure `GetLocation` would help us to have more checks before getting the correct Location as a record: 
![image](https://user-images.githubusercontent.com/70525691/91855331-b45ff780-ec6d-11ea-9466-d01137023a88.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetLocation(var Location: Record Location; LocationCode: Code[10])
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
