### ISSUE TITLE
[Event Request] Table 38 OnBeforeTestPurchLineFieldsBeforeRecreate

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8419]
We Need the same Event trigger OnBeforeTestPurchLineFieldsBeforeRecreate in table 38 as it is implemented in table 36 OnBeforeTestSalesLineFieldsBeforeRecreate.
To create this new trigger the procedure RecreatePurchLines should call 2 new local procedures with the already existent Code:

LOCAL RecreatePurchLines(ChangedFieldName : Text[100])
IF NOT PurchLinesExist THEN
  EXIT;

IsHandled := FALSE;
OnRecreatePurchLinesOnBeforeConfirm(Rec,xRec,ChangedFieldName,HideValidationDialog,Confirmed,IsHandled);
IF NOT IsHandled THEN
  IF GetHideValidationDialog THEN
    Confirmed := TRUE
  ELSE BEGIN
    IF HasItemChargeAssignment THEN
      ConfirmText := ResetItemChargeAssignMsg
    ELSE
      ConfirmText := RecreatePurchLinesMsg;
    Confirmed := ConfirmManagement.ConfirmProcess(STRSUBSTNO(ConfirmText,ChangedFieldName),TRUE);
  END;

IF Confirmed THEN BEGIN
  PurchLine.LOCKTABLE;
  ItemChargeAssgntPurch.LOCKTABLE;
  MODIFY;
  OnBeforeRecreatePurchLines(Rec);

  PurchLine.RESET;
  PurchLine.SETRANGE("Document Type","Document Type");
  PurchLine.SETRANGE("Document No.","No.");
  IF PurchLine.FINDSET THEN BEGIN
    //+++++++++++++++++++++++++++++++++
    RecreateTempPurchLines(VAR TempPurchLine);
    //---------------------------------
    TransferItemChargeAssgntPurchToTemp(ItemChargeAssgntPurch,TempItemChargeAssgntPurch);

    PurchLine.DELETEALL(TRUE);
…
End; //of Procedure RecreatePurchLines

//++++++++++++++++++++++++++++++++++++
LOCAL TestPurchLineFieldsBeforeRecreate()
IsHandled := FALSE;
**OnBeforeTestPurchLineFieldsBeforeRecreate(Rec,IsHandled,PurchLine);**
IF IsHandled THEN
  EXIT;

PurchLine.TESTFIELD("Quantity Received",0);
PurchLine.TESTFIELD("Quantity Invoiced",0);
PurchLine.TESTFIELD("Return Qty. Shipped",0);
PurchLine.CALCFIELDS("Reserved Qty. (Base)");
PurchLine.TESTFIELD("Reserved Qty. (Base)",0);
PurchLine.TESTFIELD("Receipt No.",'');
PurchLine.TESTFIELD("Return Shipment No.",'');
PurchLine.TESTFIELD("Blanket Order No.",'');
IF PurchLine."Drop Shipment" OR PurchLine."Special Order" THEN BEGIN
  CASE TRUE OF
    PurchLine."Drop Shipment":
      SalesHeader.GET(SalesHeader."Document Type"::Order,PurchLine."Sales Order No.");
    PurchLine."Special Order":
      SalesHeader.GET(SalesHeader."Document Type"::Order,PurchLine."Special Order Sales No.");
  END;
  TESTFIELD("Sell-to Customer No.",SalesHeader."Sell-to Customer No.");
  TESTFIELD("Ship-to Code",SalesHeader."Ship-to Code");
END;
PurchLine.TESTFIELD("Prepmt. Amt. Inv.",0);
//----------------------------------------

//++++++++++++++++++++++++++++++++++++++++
LOCAL Procedure RecreateTempPurchLines(VAR TempPurchLine);
BEGIN
    REPEAT
      TestPurchLineFieldsBeforeRecreate();
      TempPurchLine := PurchLine;
      IF PurchLine.Nonstock THEN BEGIN
        PurchLine.Nonstock := FALSE;
        PurchLine.MODIFY;
      END;
      OnRecreatePurchLinesOnBeforeTempPurchLineInsert(TempPurchLine,PurchLine);
      TempPurchLine.INSERT;
    UNTIL PurchLine.NEXT = 0;
//----------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
