### ISSUE TITLE
[Event Request] Table 6651 Return Shipment Line - OnInsertInvLineFromRetShptLineOnBeforeClearLineNumbers

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8421]
Hi Team,
In table 6651 we need possibility to add our own custom code. Having event on before clearing line numbers in procedure `InsertInvLineFromRetShptLine` would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/91861735-d493b480-ec75-11ea-9b3c-e221862a7f63.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnInsertInvLineFromRetShptLineOnBeforeClearLineNumbers(var Rec: Record "Return Shipment Line"; var PurchLine: Record "Purchase Line"; var NextLineNo: Integer; TempPurchLine: Record "Purchase Line" temporary)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
