### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnCheckWarehouseOnBeforeShowDialog

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#8423]
This is almost a exact copy of #1645 (except that it affects the purchase line instead of the sales line)

Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnCheckWarehouseOnBeforeShowDialog` in table 39 Purchase Line with the following signature:

```
LOCAL [IntegrationEvent] OnCheckWarehouseOnBeforeShowDialog(PurchLine : Record "Purchase Line"; Location2 : Record Location; VAR ShowDialog : ' ,Message,Error'; VAR DialogText : Text[50])
```

with **VAR** parameters `ShowDialog` and `DialogText`.

which would be called from `CheckWarehouse` as follows:

```pascal
LOCAL CheckWarehouse()
...

OnCheckWarehouseOnBeforeShowDialog(Rec, Location2, ShowDialog, DialogText); // << Call to new event
CASE ShowDialog OF
  ShowDialog::Message:
    MESSAGE(WhseRequirementMsg,DialogText);
  ShowDialog::Error:
    ERROR(Text016,DialogText,FIELDCAPTION("Line No."),"Line No.")
END;

HandleDedicatedBin(TRUE);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
