### ISSUE TITLE
[Event Request] Codeunit 6520 - Item Tracing Mgt. - OnBeforeNextLevel

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#8424]
Hello,

Can we add an event to Codeunit 6520 "Item Tracing Mgt." called OnBeforeNextLevel.

    local procedure NextLevel(var TempTrackEntry: Record "Item Tracing Buffer"; TempTrackEntry2: Record "Item Tracing Buffer"; Direction: Option Forward,Backward; ShowComponents: Option No,"Item-tracked only",All; ParentID: Integer)
    var
        ItemLedgEntry: Record "Item Ledger Entry";
        ItemApplnEntry: Record "Item Application Entry";
        TrackNo: Integer;
        IsHandled: Boolean;   // NEW
    begin
        with TempTrackEntry2 do begin
            if ExitLevel(TempTrackEntry) then
                exit;
            CurrentLevel += 1;

            // >> NEW
            IsHandled := False;
            OnBeforeNextLevel(TempTrackEntry, TempTrackEntry2, Direction, ShowComponents, ParentID, CurrentLevel, TempLineNo, IsHandled);
            if IsHandled then
                exit;
            // << NEW

    // >> NEW
    [IntegrationEvent(false, false)]
    local procedure OnBeforeNextLevel(var TempTrackEntry: Record "Item Tracing Buffer" temporary; var TempTrackEntry2: Record "Item Tracing Buffer" temporary; Direction: Option Forward,Backward; ShowComponents: Option No,"Item-tracked only",All; ParentID: Integer; var CurrentLevel: Integer;var TempLineNo: Integer; var IsHandled: Boolean)
    begin
    end;
    // << NEW

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
