### ISSUE TITLE
[Event Request] Table 39 Purchase Line - OnValidateExpectedReceiptDateOnBeforeValidatePlannedReceiptDate

### ISSUE THREAD

**Issue by JonasMikalkenas** [microsoft/ALAppExtensions#8425]
Hi Team,

In table 39 we need additional publisher in field 18 "Expected Receipt Date" OnValidate trigger - we want to handle "Planned Receipt Date" validation and replace it with our own code with more validation rules for our customization.

Our suggestion of placing new publisher:
![image](https://user-images.githubusercontent.com/69669749/91896712-f99e1c80-eca1-11ea-8366-de537824bd99.png)

local procedure OnValidateExpectedReceiptDateOnBeforeValidatePlannedReceiptDate(var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
