### ISSUE TITLE
[Change Event Request] Codeunit 6520 - Item Tracing Mgt. - OnBeforeFindComponents

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#8426]
Hello,

Can make parameters **CurrentLevel** and **TempLineNo** a Var in Codeunit 6520 "Item Tracing Mgt." publisher OnBeforeFindComponents.

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindComponents(var ItemLedgEntry2: Record "Item Ledger Entry"; var TempItemTracingBuffer: Record "Item Tracing Buffer" temporary; Direction: Option Forward,Backward; ShowComponents: Option No,"Item-tracked only",All; ParentID: Integer; **var** CurrentLevel: Integer; **var** TempLineNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
