### ISSUE TITLE
[Extensibility] Codeunit 6520 - Item Tracing Mgt. SetVariable & GetVariables

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#8427]
Hello,

Can we add 2 new Global Functions to Codeunit 6520 "Item Tracing Mgt." called SetVariables and GetVariables.

    // >> NEW
    procedure SetVariables(var TempLineNo2: Integer; var CurrentLevel2: Integer)
    begin
        TempLineNo := TempLineNo2;
        CurrentLevel := CurrentLevel2;
    end;

    procedure GetVariables(var TempLineNo2: Integer; var CurrentLevel2: Integer)
    begin
        TempLineNo2 := TempLineNo;
        CurrentLevel2 := CurrentLevel;
    end;
    // << NEW

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
