### ISSUE TITLE
[External] Codeunit 6520 - Item Tracing Mgt. - NextLevel, FindComponents, InsertRecord, and TransferData

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#8428]
Hello,

Can we make functions **NextLevel**, **FindComponents**, **InsertRecord**, and **TransferData** External in Codeunit 6520 "Item Tracing Mgt." called OnBeforeNextLevel.

procedure NextLevel(var TempTrackEntry: Record "Item Tracing Buffer"; TempTrackEntry2: Record "Item Tracing Buffer"; Direction: Option Forward,Backward; ShowComponents: Option No,"Item-tracked only",All; ParentID: Integer)

procedure FindComponents(var ItemLedgEntry2: Record "Item Ledger Entry"; var TempItemTracingBuffer: Record "Item Tracing Buffer" temporary; Direction: Option Forward,Backward; ShowComponents: Option No,"Item-tracked only",All; ParentID: Integer)

procedure InsertRecord(var TempTrackEntry: Record "Item Tracing Buffer"; ParentID: Integer): Boolean

procedure TransferData(var ItemLedgEntry: Record "Item Ledger Entry"; var TempTrackEntry: Record "Item Tracing Buffer")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
