### ISSUE TITLE
[Request for external] Procedures in codeunit 229 "Document-Print"

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#8429]
Hi Microsoft AL Team,

Could you please make the following procedures external in **codeunit 229 "Document-Print"**?
- GetPurchDocTypeUsage
- CalcPurchDisc
- GetServContractTypeUsage
- CalcServDisc
- GetServHeaderDocTypeUsage

Thank you very much.

Kind regards,
Tuan Nguyen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
