### ISSUE TITLE
[Event Requests] Codeunit "Document Attachment Mgmt" - OnBeforeDocAttachForPostedSalesDocs

### ISSUE THREAD

**Issue by Nyryus** [microsoft/ALAppExtensions#8430]
Hi,

please add the event OnBeforeDocAttachForPostedSalesDocs in Codeunit "Document Attachment Mgmt". 
And in the same way in the purchase procedure "DocAttachForPostedPurchaseDocs".

```
 [EventSubscriber(ObjectType::Codeunit, 80, 'OnBeforeDeleteAfterPosting', '', false, false)]
    local procedure DocAttachForPostedSalesDocs(var SalesHeader: Record "Sales Header"; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header")
    var
        FromRecRef: RecordRef;
        ToRecRef: RecordRef;
        Handled: Boolean;
    begin
        OnBeforeDocAttachForPostedSalesDocs(SalesHeader, SalesInvoiceHeader, SalesCrMemoHeader, Handled)
        // Triggered when a posted sales cr. memo / posted sales invoice is created
        if SalesHeader.IsTemporary then
            exit;

        if SalesInvoiceHeader.IsTemporary then
            exit;

        if SalesCrMemoHeader.IsTemporary then
            exit;

        FromRecRef.GetTable(SalesHeader);

        if SalesInvoiceHeader."No." <> '' then
            ToRecRef.GetTable(SalesInvoiceHeader);

        if SalesCrMemoHeader."No." <> '' then
            ToRecRef.GetTable(SalesCrMemoHeader);

        CopyAttachmentsForPostedDocs(FromRecRef, ToRecRef);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDocAttachForPostedSalesDocs(var SalesHeader: Record "Sales Header"; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var Handled: true)
    begin
    end;
```

The purpose of the event is to fix an error that returns in an extension. Because if a SalesInvoice doesn't exist it still tries to execute the CopyAttachmentsForPostedDocs and returns the error "the record is not open".

![image](https://user-images.githubusercontent.com/40896051/91941658-d56e2a00-ecf9-11ea-94ca-e69a90d86acc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by HubGitke** [comment]
Thank you for this valuable information.

Seems to be still in Version BC 18.02. Reproducable if you only want to post a shipment without invoice or cr. memo

![image](https://user-images.githubusercontent.com/31094883/123647401-5453c680-d828-11eb-8053-b6c6a313250d.png)
