### ISSUE TITLE
[Scope Change] Codeunit 443 - procedure Preview

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8431]
Please remove the scope OnPrem for procedure "Preview" in codeunit 443 "Sales-Post Prepayment (Yes/No)".
Thank you

**Comment by AlexanderYakunin** [comment]
Please explain how you are going to use it.

**Comment by aobsgit** [comment]
Our app is targeting cloud and we would like to post prepayment invoice from a quote with preview enabled.
Please note that purchase side (CU 445) has this same function without scope parameter.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
