### ISSUE TITLE
[Extensibility enhancement] Table 246 Requisition Line - procedure UpdateOrderReceiptDate

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#8432]
Hi!

Can you change the local procedure UpdateOrderReceiptDate in table 246 Requisition Line to global?
I'd like to use it from my tableextension which extends Requisition Line.

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
