### ISSUE TITLE
[Event Request] Table 5741 Transfer Line - OnBeforeInsertTransferLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8433]
Hi Team,

In table 5741 we need possibility to replace standard code with our own. Having event with handling in the beginning of trigger `OnInsert` would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/91970581-8be50580-ed20-11ea-806f-4da4219ee57e.png)

```
[IntegrationEvent(true, false)]
    local procedure OnBeforeInsertTransferLine(var xRec: Record "Transfer Line"; TransHeader: Record "Transfer Header"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
