### ISSUE TITLE
[Event Request] Table 5741 Transfer Line - OnBeforeVerifyQuantity

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8434]
Hi Team,

In table 5741 we need possibility to replace and avoid using standard code with our own. Having event with handling on the field `Quantity`, in `OnValidate` trigger,   would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/91971660-3c073e00-ed22-11ea-9d85-ad9166b0350c.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeVerifyQuantity(var TransferLine: Record "Transfer Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
