### ISSUE TITLE
[Event Request] Table 5802 Value Entry - OnSumCostsTillValuationDateOnBeforeCheckCostingMethod

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8436]
Hi Team,

In table 5802 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure `SumCostsTillValuationDate`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/91973828-8ccc6600-ed25-11ea-9660-dd8f5bce2455.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnSumCostsTillValuationDateOnBeforeCheckCostingMethod(var Rec: Record "Value Entry"; AccountingPeriod: Record "Accounting Period"; ValueEntry: Record "Value Entry"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
