### ISSUE TITLE
[Event Request] Table 5875/5876/5878 - OnBeforeValidateBinCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8438]
Hi team,

We need the same standard event publisher in a set of standard tables - as all these tables have identical field `Bin Code OnValidate` trigger. We need possibility to replace and avoid using standard code with our own in tables:

5875 Phys. Invt. Order Header
5876 Phys. Invt. Order Line
5878 Phys. Invt. Record Line

Our proposed new publisher:
![image](https://user-images.githubusercontent.com/70525691/91978061-2eef4c80-ed2c-11ea-972c-ef3d804a17e9.png)

and declarations:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateBinCode(PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; var IsHandled: Boolean)
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateBinCode(PhysInvtOrderLine: Record "Phys. Invt. Order Line"; var IsHandled: Boolean)
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateBinCode(var PhysInvtRecordLine: Record "Phys. Invt. Record Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
