### ISSUE TITLE
GetWebURL: allow to use own link

### ISSUE THREAD

**Issue by yuliia-biloklokova** [Microsoft/ALAppExtensions#844]
Hi,

we need to use our own link (public name) to open web client instead of standard MyWebServer:8080 
(example: http://MyWebServer:8080/nav_server_instance/?company=CRONUS%20International%20Ltd.&page=9305).

Please refactor the function  GetWebUrl in Codeunit 700 "Page Management" and add an event into it.
![image](https://user-images.githubusercontent.com/36188763/51200590-3e711600-18fa-11e9-925d-97d5eca9a41b.png)

**Comment by AndreiPanko** [comment]
Public external endpoints may differ from internal addressing. For example, an external port number could map to a different internal port number, or you may be using a domain name to identify your Business Central server. In such cases, the Business Central server instance cannot automatically identify your network configuration settings.
To solve this problem, find the server instance configuration file and update the configuration keys for base URLs, such as the following key:
   <add key="PublicWebBaseUrl" value="" />
You can set a Base URL for the Windows client, the web client, as well as SOAP and ODATA services, each independently. For example, you could set the Web Client Base URL to "cronus.nav.net/…/". From this point forward, the GETURL function will return URLs starting with this base address that you have specified.
Tips and Tricks:
– Remember to restart the server instance for your change to take effect.
– You can set server instance configuration keys also using the PowerShell commandlets or using the administration console snap-in.
– When installing Business Central using setup.exe, you can set the base URLs directly in the installation wizard.
– Take note of the examples provided in the configuration file to ensure you enter URLs using the correct format.
– In the majority of cases where you have installed the web client, you must set the PublicWebBaseUrl key.
