### ISSUE TITLE
[Event Request] Table 5876 Phys. Invt. Order Line - OnAfterGetFieldsFromSKU

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8440]
Hi Team,

In table 5876 we need new publisher in procedure GetFieldsFromSKU for more flexibility validating fields :

![image](https://user-images.githubusercontent.com/70525691/91979259-2ac42e80-ed2e-11ea-95d9-a5c7f44d24b9.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetFieldsFromSKU(var PhysInvtOrderLine: Record "Phys. Invt. Order Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
