### ISSUE TITLE
[Event Request] Table 7354 Bin - OnBeforeCheckMaxQtyBinContent

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8442]
Hi Team,

In table 7354 we need possibility to replace and avoid using standard code with our own. Having event at the beginning with handling in the procedure CheckMaxQtyBinContent, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/91985806-39621400-ed35-11ea-95a7-50bc168fa230.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckMaxQtyBinContent(var Rec: Record Bin; CheckWeight: Boolean; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
