### ISSUE TITLE
[Event Request] Table 7335 Bin Template - OnSetUpNewLineOnBeforeSetUpNewLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8443]
Hi Team,

In table 7335 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure `SetUpNewLine`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/91997467-cbbce480-ed42-11ea-898c-31d63bc5b565.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnSetUpNewLineOnBeforeSetUpNewLine(var BinTemplate: Record "Bin Template"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
