### ISSUE TITLE
[Application Bug] Overflow when extending the 'Experience Tier Setup'

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#8445]
Added a new field (with too large caption) to the 'Experience Tier Setup'
![image](https://user-images.githubusercontent.com/25268332/92014362-67ece880-ed4f-11ea-99bd-7f06f882ed67.png)

Changing the experience tier in the company information page, results in an error
![image](https://user-images.githubusercontent.com/25268332/92014371-6ae7d900-ed4f-11ea-84dc-d92dd2f46570.png)

Version: BC 16.3

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
