### ISSUE TITLE
[Event Request] table 5050 Contact - OnBeforeBankAccountInsert: additional parameter

### ISSUE THREAD

**Issue by PieterDeVriesAddIT** [microsoft/ALAppExtensions#8446]
Based on 16.03W1

Clear(BankAcc);
BankAcc.SetInsertFromContact(true);
//OnBeforeBankAccountInsert(BankAcc); Old Code
OnBeforeBankAccountInsert(BankAcc, Rec); New Code
BankAcc.Insert(true);

[IntegrationEvent(false, false)]
local procedure OnBeforeBankAccountInsert(var BankAccount: Record "Bank Account"; var Contact: Record Contact);
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
