### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt." purchaselines set filters

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#8447]
We want to filter the from records when copying documents in codeunit 6620 "Copy Document Mgt.".
In BC15 we only had the events for the sales documents.
For purchase, this was added in BC16.
However, these purchase events are way less intuitive compared to those of the sales side.
I had to actively search in the purchase copy document code for the needed event, and what's it name and parameters are.
Wouldn't it be nicer to also have those same events on the purchase side as in the sales side?

as requested by me in #4664 ?
```
    local procedure CopySalesDocSalesLine(FromSalesHeader: Record "Sales Header"; var ToSalesHeader: Record "Sales Header"; var LinesNotCopied: Integer; NextLineNo: Integer)
    var
        ToSalesLine: Record "Sales Line";
        FromSalesLine: Record "Sales Line";
        ItemChargeAssgntNextLineNo: Integer;
    begin
        ItemChargeAssgntNextLineNo := 0;

        with ToSalesHeader do begin
            FromSalesLine.Reset();
            FromSalesLine.SetRange("Document Type", FromSalesHeader."Document Type");
            FromSalesLine.SetRange("Document No.", FromSalesHeader."No.");
            if MoveNegLines then
                FromSalesLine.SetFilter(Quantity, '<=0');
            OnCopySalesDocSalesLineOnAfterSetFilters(FromSalesHeader, FromSalesLine, ToSalesHeader); //<<<<
            if FromSalesLine.Find('-') then
...

```
    local procedure CopyPurchDocInvLine(FromPurchInvHeader: Record "Purch. Inv. Header"; ToPurchHeader: Record "Purchase Header"; var LinesNotCopied: Integer; var MissingExCostRevLink: Boolean)
    var
        FromPurchInvLine: Record "Purch. Inv. Line";
    begin
        with ToPurchHeader do begin
            FromPurchInvLine.Reset();
            FromPurchInvLine.SetRange("Document No.", FromPurchInvHeader."No.");
            if MoveNegLines then
                FromPurchInvLine.SetFilter(Quantity, '<=0');
///////>>>>OnCopyPurchInvLinesToDocOnAfterSetFilters(ToPurchHeader, FromPurchInvLine, LinesNotCopied, MissingExCostRevLink);
            CopyPurchInvLinesToDoc(ToPurchHeader, FromPurchInvLine, LinesNotCopied, MissingExCostRevLink);
        end;
    end;

    procedure CopyPurchInvLinesToDoc(ToPurchHeader: Record "Purchase Header"; var FromPurchInvLine: Record "Purch. Inv. Line"; var LinesNotCopied: Integer; var MissingExCostRevLink: Boolean)
...
        OnBeforeCopyPurchInvLines(TempDocPurchaseLine, ToPurchHeader, FromPurchInvLine);

        // Fill purchase line buffer
        with FromPurchInvLine do
            if FindSet then
...
----
Now I have to subscribe to `OnBeforeCopyPurchInvLines` and put my filter there.
Yes it's the same result, except the subscribers look a complete mess code-wise.

(/rant)

Could these purchase filter events to all document source types be added please (cfr sales)?

code of BC16.3

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
