### ISSUE TITLE
[Request for External] table 7603 "Customized Calendar Entry" - UpdateExceptionEntry

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#8449]
Could procedure `UpdateExceptionEntry` in table 7603 "Customized Calendar Entry" be put to external, please?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
