### ISSUE TITLE
[Event Request] table 383 Detailed CV Ledg. Entry Buffer - OnInsertDtldCVLedgEntryOnAfterReset

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8451]
We woud like to insert data in the record DtldCVLedgEntryBuf after the reset method at the end of the procedure InsertDtldCVLedgEntry, table 383 "Detailed CV Ledg. Entry Buffer". In this purpose, we need an event at the end of this procedure, as follows : 

![image](https://user-images.githubusercontent.com/34645582/92103966-f65d7a80-ede0-11ea-97f9-948590f6d35c.png)

We would need these parameters : 
OnInsertDtldCVLedgEntryOnAfterReset(DtldCVLedgEntryBuf, CVLedgEntryBuf, NewDtldCVLedgEntryBuf, NextDtldBufferEntryNo, IsHandled)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
