### ISSUE TITLE
New event request for Report 202 "Sales Document - Test"

### ISSUE THREAD

**Issue by paragpardhi123** [microsoft/ALAppExtensions#8452]
Currently **OnAfterCalculateSalesTax** event is not available on report 202. We have integration on report 202 and we need to update 'VAT Amount' and 'VAT Base Amount' as per our integration calculated value.

Attaching reference files for the event details:

[report 202 Sales Document - Test - Modified.txt](https://github.com/microsoft/ALAppExtensions/files/5167921/report.202.Sales.Document.-.Test.-.Modified.txt)
[report 202 Sales Document - Test.txt](https://github.com/microsoft/ALAppExtensions/files/5167923/report.202.Sales.Document.-.Test.txt)

Versions:

AL Language: 5.0.320540

NA Business Central 16.4 (Platform 16.0.14648.15420 + Application 16.4.15445.0)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
