### ISSUE TITLE
Request to add parameter in event 'OnBeforeCalculateSalesTax' for Codeunit 5988 Serv-Documents Mgt.

### ISSUE THREAD

**Issue by paragpardhi123** [microsoft/ALAppExtensions#8453]
**Current Event parameter:**
EventSubscriber(ObjectType::Codeunit, 5988, 'OnBeforeCalculateSalesTax', '', false, false)]

local procedure SalesPostOnBeforeCalculateSalesTax(VAR SalesTaxCalculationOverridden: Boolean; VAR ServiceHeader: Record "Service Header"; VAR ServiceLine: Record "Service Line"; VAR TempSalesTaxAmountLine: Record "Sales Tax Amount Line"; var IsHandled: Boolean);

**Requested Event Parameter:**

[EventSubscriber(ObjectType::Codeunit, 5988, 'OnBeforeCalculateSalesTax', '', false, false)]

local procedure SalesPostOnBeforeCalculateSalesTax(VAR SalesTaxCalculationOverridden: Boolean; VAR ServiceHeader: Record "Service Header"; VAR ServiceLine: Record "Service Line"; VAR TempSalesTaxAmountLine: Record "Sales Tax Amount Line"; var IsHandled: Boolean; **Ship: Boolean; Consume: Boolean; Invoice: Boolean**);

Versions:

AL Language: 5.0.320540

NA Business Central 16.4 (Platform 16.0.14648.15420 + Application 16.4.15445.0)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by chavansachin20** [comment]
@StanPesotskiy / @bc-ghost   - issue is not fixed in below version. Please confirm the version where this is delivered.

**Version: NA Business Central 17.0 (Platform 17.0.16974.0 + Application 17.0.16993.0)**

![image](https://user-images.githubusercontent.com/5293496/96546567-247f1700-12c8-11eb-9de1-466c041811f5.png)

@paragpardhi123 - FYI.

**Comment by StanPesotskiy** [comment]
Hi, you are right, it was not part of 17.0 release. 
Will be shipped with 17.1.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.
