### ISSUE TITLE
[Event Request] Codeunit::"Assembly-Post" - Function PostHeader - OnBeforePostItemOutput

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8454]
We like to request the following Event:
Object: Codeunit::"Assembly-Post"
Function: PostHeader
Publisher Event: OnBeforePostItemOutput
Reason: To implement custom business logic
Where is the event placed:
local procedure PostHeader(var AssemblyHeader: Record "Assembly Header"; var PostedAssemblyHeader: Record "Posted Assembly Header"; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; var WhseJnlRegisterLine: Codeunit "Whse. Jnl.-Register Line"; NeedUpdateUnitCost: Boolean)
    var
        WhseAssemblyRelease: Codeunit "Whse.-Assembly Release";
        ItemLedgEntryNo: Integer;
        QtyToOutput: Decimal;
        QtyToOutputBase: Decimal;
    begin
        with AssemblyHeader do begin
            GetHeaderQtys(QtyToOutput, QtyToOutputBase, AssemblyHeader);
            if NeedUpdateUnitCost then
                if not IsStandardCostItem then
                    UpdateUnitCost;
            OnBeforePostItemOutput(QtyToOutput, QtyToOutputBase, AssemblyHeader);
            ItemLedgEntryNo :=
              PostItemOutput(
                AssemblyHeader, "Posting No. Series",
                QtyToOutput, QtyToOutputBase,
                ItemJnlPostLine, WhseJnlRegisterLine, "Posting No.", false, 0);
            OnAfterPostItemOutput(QtyToOutput, QtyToOutputBase, AssemblyHeader);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePostItemOutput(var HeaderQty: Decimal; var HeaderQtyBase: Decimal; var AssemblyHeader: Record "Assembly Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
