### ISSUE TITLE
[Event Request] Codeunit::"Req. Wksh.-Make Order" - Function OnRun - OnRunOnBeforeCarryOutReqLineAction

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8455]
We like to request the following Event:
Object: Codeunit::"Req. Wksh.-Make Order"
Function: OnRun
Publisher Event: OnRunOnBeforeCarryOutReqLineAction
Reason: To implement custom business logic
Where is the event placed:
trigger OnRun()
    var
        IsHandled: Boolean;
    begin
        if PlanningResiliency then
            LockTable();
        IsHandled := false;
        OnRunOnBeforeCarryOutReqLineAction(Rec, IsHandled);
        if not IsHandled then
            CarryOutReqLineAction(Rec);
    end;
Event Code:
[IntegrationEvent(true, false)]
    local procedure OnRunOnBeforeCarryOutReqLineAction(var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
