### ISSUE TITLE
[Event Request] Codeunit::"Reservation-Check Date Confl." - Function ProdOrderLineCheck - OnBeforeDateConflict

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8456]
We like to request the following Event:
Object: Codeunit::"Reservation-Check Date Confl."
Function: ProdOrderLineCheck
Publisher Event: OnBeforeDateConflict
Reason: To implement custom business logic
Where is the event placed:
procedure ProdOrderLineCheck(ProdOrderLine: Record "Prod. Order Line"; ForceRequest: Boolean)
    var
        ProdOrderLineReserve: Codeunit "Prod. Order Line-Reserve";
        IsHandled: Boolean;
        CheckDateConflict: Boolean;
    begin
        if not ProdOrderLineReserve.FindReservEntry(ProdOrderLine, ReservEntry) then
            exit;
        CheckDateConflict := true;
        OnBeforeDateConflict(ProdOrderLine."Due Date", ForceRequest, ReservEntry, CheckDateConflict);
        if DateConflict(ProdOrderLine."Due Date", ForceRequest, ReservEntry) and CheckDateConflict then
            if ForceRequest then
                IssueError(ProdOrderLine."Due Date");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeDateConflict(Date: Date; var ForceRequest: Boolean; var ReservationEntry: Record "Reservation Entry"; var CheckDateConflict: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
