### ISSUE TITLE
[Event Request] Codeunit::"Sales Post via Job Queue" - Function OnRun - OnAfterRunSalesPost

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8457]
We like to request the following Event:
Object: Codeunit::"Sales Post via Job Queue"
Function: OnRun
Publisher Event: OnAfterRunSalesPost
Reason: To implement custom business logic
Where is the event placed:
OnBeforeRunSalesPost(SalesHeader);
        if not Codeunit.Run(Codeunit::"Sales-Post", SalesHeader) then begin
            SetJobQueueStatus(SalesHeader, SalesHeader."Job Queue Status"::Error);
            BatchProcessingMgt.ResetBatchID;
            Error(GetLastErrorText);
        end;
        OnAfterRunSalesPost(SalesHeader);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterRunSalesPost(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
