### ISSUE TITLE
[Event Request] Codeunit::"Sales Post via Job Queue" - Function OnRun - OnBeforeRunSalesPost

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8458]
We like to request the following Event:
Object: Codeunit::"Sales Post via Job Queue"
Function: OnRun
Publisher Event: OnBeforeRunSalesPost
Reason: To implement custom business logic
Where is the event placed:
begin
        TestField("Record ID to Process");
        RecRef.Get("Record ID to Process");
        RecRef.SetTable(SalesHeader);
        SalesHeader.Find;
        BatchProcessingMgt.GetBatchFromSession("Record ID to Process", "User Session ID");
        SavedLockTimeout := LockTimeout;
        SetJobQueueStatus(SalesHeader, SalesHeader."Job Queue Status"::Posting);
        OnBeforeRunSalesPost(SalesHeader);
        if not Codeunit.Run(Codeunit::"Sales-Post", SalesHeader) then begin
            SetJobQueueStatus(SalesHeader, SalesHeader."Job Queue Status"::Error);
            BatchProcessingMgt.ResetBatchID;
            Error(GetLastErrorText);
        end;
        OnAfterRunSalesPost(SalesHeader);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeRunSalesPost(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
