### ISSUE TITLE
[Event Request] Table 7320 Warehouse Shipment Header - OnBeforeSortWhseDoc

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8459]
Hi Team,

In table 7320 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure `SortWhseDoc`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92113130-88707d80-edf7-11ea-8f16-3c15bcafc876.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSortWhseDoc(var WhseShptHeader: Record "Warehouse Shipment Header"; var SortWhseShipmentDoc: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
