### ISSUE TITLE
[Event Request] Codeunit::"TransferOrder-Post Shipment" - Function CheckWarehouse - OnBeforeCheckWarehouse

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8463]
We like to request the following Event:
Object: Codeunit::"TransferOrder-Post Shipment"
Function: CheckWarehouse
Publisher Event: OnBeforeCheckWarehouse
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckWarehouse(TransLine: Record "Transfer Line")
    var
        WhseValidateSourceLine: Codeunit "Whse. Validate Source Line";
        ShowError: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeCheckWarehouse(TransLine, IsHandled);
        if IsHandled then
            exit;
        GetLocation(TransLine."Transfer-from Code");
        if Location."Require Pick" or Location."Require Shipment" then begin
            if Location."Bin Mandatory" then
                ShowError := true
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWarehouse(TransferLine: Record "Transfer Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
