### ISSUE TITLE
[Event Request] Table 7320 Warehouse Shipment Header - OnBeforeWhseShptHeaderSetRange

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8464]
Hi Team,

In table 7320 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure `LookupWhseShptHeader`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92113436-fa48c700-edf7-11ea-9d5b-ce0059105402.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhseShptHeaderSetRange(var WhseShptHeader: Record "Warehouse Shipment Header"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
