### ISSUE TITLE
[Additional Parameter Request] Table 7321 Warehouse Shipment Line - OnBeforeTestReleased

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8465]
Hi Team,
In table 7321 we need possibility to have additional checks in the procedure `TestReleased`. Standard publisher would suit us if it had additional parameter with boolean `StatusCheckSuspended`. `OnBeforeTestReleased` would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92114503-9921f300-edf9-11ea-8b24-28e84564ead6.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeTestReleased(var WhseShptHeader: Record "Warehouse Shipment Header"; **var StatusCheckSuspended: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
