### ISSUE TITLE
[Event Request] Table 7321 Warehouse Shipment Line - OnBeforeCheckSourceDocLineQty

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8466]
Hi Team,

In table 7321 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure CheckSourceDocLineQty, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92115391-02563600-edfb-11ea-9507-88976a61ecce.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckSourceDocLineQty(var Rec: Record "Warehouse Shipment Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
