### ISSUE TITLE
[Event Request] Table 7321 Warehouse Shipment Line - OnBeforeAutofillQtyToHandle / OnAfterAutofillQtyToHandle

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8467]
Hi Team,

In table 7321 we need possibility to replace standard code with our own. Having event in beginning and at the end of procedure AutofillQtyToHandle, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92118158-c45b1100-edfe-11ea-995e-b1f7d78395cd.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAutofillQtyToHandle(var WhseShptLine: Record "Warehouse Shipment Line"; var HideValidationDialog: Boolean)
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterAutofillQtyToHandle(var WhseShptLine: Record "Warehouse Shipment Line"; var HideValidationDialog: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
