### ISSUE TITLE
[Event Request] Table 7321 Warehouse Shipment Line - OnCreatePickDoc

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8469]
Hi Team,

In table 7321 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure `CreatePickDoc`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92119725-dccc2b00-ee00-11ea-987d-9113af6ff90f.png)

    [IntegrationEvent(false, false)]
    local procedure OnCreatePickDoc(var Rec: Record "Warehouse Shipment Line"; var WhseShptLine: Record "Warehouse Shipment Line"; var WhseShptHeader2: Record "Warehouse Shipment Header"; HideValidationDialog: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
