### ISSUE TITLE
[Additional Parameter Request] Table 7326 Whse. Worksheet Line - OnBeforePutAwayCreate

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8470]
Hi Team,
In table 7326 we need possibility to have additional checks on the start of procedure PutAwayCreate. Standard publisher would suit us if it had additional parameter: `HideValidationDialog: Boolean`. `OnBeforeCheckIfPostingDateIsEarlier` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92131048-2a02c980-ee0e-11ea-8422-f6b4cde83865.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePutAwayCreate(var WhsePutAwayWkshLine: Record "Whse. Worksheet Line"; var IsHandled: Boolean; HideValidationDialog: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
