### ISSUE TITLE
[Event Request] Table 7326 Whse. Worksheet Line - OnLookupWhseWkshNameOnBeforeRunModal

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8471]
Hi Team,

In table 7326 we need possibility to add custom filters and modify record with our own. Having event in procedure `LookupWhseWkshName`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92132355-b9f54300-ee0f-11ea-9184-c12386314008.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnLookupWhseWkshNameOnBeforeRunModal(var WhseWkshName: Record "Whse. Worksheet Name")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
