### ISSUE TITLE
[Event Request] Table 7332 Whse. Internal Put-away Line - OnAfterCheckBlocking

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8472]
Hi Team,

In table 7332 we need possibility to add modify record with our own code. Having event at the end of `CheckBlocking`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92132779-41db4d00-ee10-11ea-9262-0218b878de9b.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckBlocking(var WhseInternalPutawayLine: Record "Whse. Internal Put-away Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
