### ISSUE TITLE
[Event Request] Table 7332 Whse. Internal Put-away Line - OnAfterLookUpBinContent

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8473]
Hi Team,

In table 7332 we need possibility to add modify record with our own code. Having event at the end of `LookUpBinContent`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92132945-75b67280-ee10-11ea-856f-849f995b044d.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterLookUpBinContent(var WhseInternalPutawayLine: Record "Whse. Internal Put-away Line"; Bin: Record "Bin"; BinContent: Record "Bin Content")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
