### ISSUE TITLE
[Additional Parameter Request]  publisher OnCheckWarehouseOnBeforeShowDialog Table 37-"Sales Line"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8474]
Can you please get the SalesLine parameter in the publisher OnCheckWarehouseOnBeforeShowDialog by reference? 
We pass some global variables in our tableextension which we have to retrieve via getter.

```
[IntegrationEvent(false, false)]
local procedure OnCheckWarehouseOnBeforeShowDialog(>>>var<<< SalesLine: Record "Sales Line"; Location: Record Location; ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
begin
end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
