### ISSUE TITLE
[Event Request] Page 490 Acc. Schedule Overview

### ISSUE THREAD

**Issue by AndreaCorneglioCapBS** [microsoft/ALAppExtensions#8492]
[IntegrationEvent(false, false)]
    local procedure OnBeforeCopyColumnsToTempCurrentColumnNameOnAfterValidate(var CurrentColumnName: Code[10])
    begin
    end;

[…]

        SetRange("Cost Budget Filter");
        SetRange("G/L Budget Filter");
        UpdateDimFilterControls;
        DateFilter := GetFilter("Date Filter");

        //> New code
        OnBeforeCopyColumnsToTempCurrentColumnNameOnAfterValidate(CurrentColumnName);
        //< New code
    end;

[…]

    local procedure CurrentColumnNameOnAfterValidate()
    begin
        //> New code
        OnBeforeCopyColumnsToTempCurrentColumnNameOnAfterValidate(CurrentColumnName);
        //< New code

        AccSchedManagement.CopyColumnsToTemp(CurrentColumnName, TempColumnLayout);
        AccSchedManagement.SetColumnName(CurrentColumnName, TempColumnLayout);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
