### ISSUE TITLE
[Question] Codeunit 7312 FindBWPickBin Event OnFindBWPickBinOnBeforeFindFromBinContent 

### ISSUE THREAD

**Issue by hindsight2020** [microsoft/ALAppExtensions#8497]
The event OnFindBWPickBinOnBeforeFindFromBinContent has the parameters
`local procedure OnFindBWPickBinOnBeforeFindFromBinContent(var FromBinContent: Record "Bin Content"; SourceType: Integer; var TotalQtyToPickBase: Decimal; var IsHandled: Boolean)` 
but it is called
`OnFindBWPickBinOnBeforeFindFromBinContent(FromBinContent, SourceType, TotalQtyPickedBase, IsHandled);`

so the TotalQtyToPickBase is actually the TotalQtyPickedBase. Is that an error or intended?

**Comment by RomanZanizdra** [comment]
@hindsight2020 , looks like a mistake. I'll add TotalQtyToPickBase as one more parameter in this event.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
