### ISSUE TITLE
[BUG] Error when Inviting External Accountant

### ISSUE THREAD

**Issue by achowtc** [microsoft/ALAppExtensions#8498]
Getting an error about .NET Framework with Microsoft.Dynamics.Nav.LicensingService.model error when I click on Invite External Accountant from the Users page:

![image](https://user-images.githubusercontent.com/34691006/92264920-db980e00-ee93-11ea-9521-1b71298e0d4b.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
