### ISSUE TITLE
Codeunit::"Reservation Management", 'OnBeforeDeleteDocumentReservation'

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#8499]
Can you allow for HideValidationDialog parameter to be 'var'? I would like to use this event to deliver a BulkDelete Action for a client. And the client does not want to confirm deletion of reservations dozens (or hundreds) of times. The architecture of the Action sets a condition on the Documents to be deleted; then inside of 'OnBeforeDeleteDocumentReservation', we check for that condition, and set HideValidationDialog to True. (but this will only work if HideValidationDialog is 'var'.)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
