### ISSUE TITLE
Codeunit 90 commit Handling

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#850]
Hello,

in Codeunit 90 the global variable Suppress Commit can be set via fct. SetSuppressCommit.
The Problem is, that not all commits are avoided. Can you please integrate the missing lines, where commits are not avoided?

Thank you,

K.

**Comment by JesperSchulz** [comment]
Could you be specific about the missing commits? Then we'll gladly add those.

**Comment by KReinmann** [comment]
Function FinalizePosting
![image](https://user-images.githubusercontent.com/46744680/51608186-04fe6300-1f17-11e9-9226-4cdd244576f5.png)

function ReleasePurchDocument
![image](https://user-images.githubusercontent.com/46744680/51608202-121b5200-1f17-11e9-8afe-4a88f9715eac.png)

function CheckAndUpdate
![image](https://user-images.githubusercontent.com/46744680/51608216-1d6e7d80-1f17-11e9-8c16-87ebca545180.png)

function CalcInvDiscount
![image](https://user-images.githubusercontent.com/46744680/51608231-27907c00-1f17-11e9-8bff-49fcbbabe030.png)

**Comment by JesperSchulz** [comment]
Great, thanks for clarifying! Just wanted to make sure we don't miss any local COMMITs.

**Comment by KReinmann** [comment]
Hi,
Are there new insights here?
Thanks in advance,
best regards,
Kathrin

**Comment by KReinmann** [comment]
@JesperSchulz

**Comment by mazhelez** [comment]
Hey, @KReinmann 

Thanks for hanging in there!

Your request has been approved and the solution is available in all releases after 14.5 (incl.) 👌
