### ISSUE TITLE
[Change Request] Table 900 "Assembly Header" – Existing function “GetUnitCost”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8508]
Could we please have the existing function “GetUnitCost”, Table 900 "Assembly Header" be set to global?
```

*** start old code ***
    //local procedure GetUnitCost(): Decimal
*** stop old code ***
*** start new code ***
    procedure GetUnitCost(): Decimal
*** stop new code ***
    var
        SkuItemUnitCost: Decimal;
    begin
        if "Item No." = '' then
            exit(0);
```

**Comment by AlexanderYakunin** [comment]
This function assign cost from either Item or SKU records, but SKU record is not retrieved in this procedure. We cannot make this global as there is risk of erroneous usage.
