### ISSUE TITLE
CU 5704 OnBeforeTransferOrderPostShipment - parameter SuppressCommit per VAR

### ISSUE THREAD

**Issue by KReinmann** [Microsoft/ALAppExtensions#852]
Hi, 

to be able to set the Parameter SuppressCommit in Codeunit 5704 the Parameter should be transfered as VAR (Event OnBeforeTransferOrderPostShipment)

Thank you,

K.

**Comment by AlexanderYakunin** [comment]
You need to use following function to set this variable:

[External] SetSuppressCommit(NewSuppressCommit : Boolean)
SuppressCommit := NewSuppressCommit;
