### ISSUE TITLE
[Event Request] Table 7316 Warehouse Receipt Header - OnBeforeSortWhseDocReceiptHeader

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8526]
Hi Team,

In table 7316 we need possibility to replace and avoid using standard code with our own. Having event with handling at the beginning of procedure `SortWhseDoc`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92381308-4145fd80-f113-11ea-9257-ca5994c14366.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSortWhseDocReceiptHeader(var WarehouseReceiptHeader: Record "Warehouse Receipt Header";var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
