### ISSUE TITLE
[Event Request] Table 7317 Warehouse Receipt Line - OnBeforeModifyOnDeleteQtyToReceive

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8527]
Hi Team,

In table 7317 we need possibility to add modify record with our own code. Having event on procedure `DeleteQtyToReceive`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92383311-c54db480-f116-11ea-880c-c04e70b3c3e2.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyOnDeleteQtyToReceive(var WarehouseReceiptLine: Record "Warehouse Receipt Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
