### ISSUE TITLE
[Additional Parameter Request] Table 7317 Warehouse Receipt Line - OnBeforeOpenItemTrackingLines

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8528]
Hi Team,
In table 7317 we need possibility to have additional checks on the start of procedure `OpenItemTrackingLines`. Standard publisher would suit us if it had additional parameter: `CurrFieldNo: Integer`. `OnBeforeOpenItemTrackingLines` would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92383828-a7cd1a80-f117-11ea-841f-e81298e73d92.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeOpenItemTrackingLines(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; var IsHandled: Boolean; **CurrFieldNo: Integer**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
