### ISSUE TITLE
[Event Request] Table 7317 Warehouse Receipt Line - OnAfterCheckIncreaseBin

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8529]
Hi Team,

In table 7317 we need possibility to add modify record with our own code. Having event on procedure `CheckBin`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92389441-bf110580-f121-11ea-8caf-81d47e7d9b95.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckIncreaseBin(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; var Bin: Record Bin; DeductCubage: Decimal; DeductWeight: Decimal; IgnoreErrors: Boolean; var ErrorOccured: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
