### ISSUE TITLE
[Event Request] Table 7338 Bin Creation Worksheet Line - OnTemplateSelectionOnBeforeFilterPageID

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8530]
Hi Team,

In table 7338 we need possibility to replace and avoid using standard code with our own. Having event with handling at the beginning of procedure `TemplateSelection`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92392796-8411d080-f127-11ea-98a4-a4a86cf902a8.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnTemplateSelectionOnBeforeFilterPageID(var BinCreateWkshTemplate: Record "Bin Creation Wksh. Template"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
