### ISSUE TITLE
[Event Request] Table 7334 Whse Internal Pick Line - OnBeforeCheckIncreaseBin

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8531]
Hi Team,

In table 7334 we need possibility to replace and avoid using standard code with our own. Having event with handling in the end of procedure `CheckBin`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92396130-28e2dc80-f12d-11ea-8dd8-630f096b3b08.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIncreaseBin(var Rec: Record "Whse. Internal Pick Line"; var Bin: Record Bin; WhseInternalPickLine: Record "Whse. Internal Pick Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
