### ISSUE TITLE
[Event Request] Table 7326 Whse Worksheet Line - OnBeforeCheckIncreaseBin

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8532]
Hi Team,

In table 7326 we need possibility to replace and avoid using standard code with our own. Having event with handling in the end of procedure `CheckBin`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92400432-99d9c280-f134-11ea-8525-c8dd30fd190e.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIncreaseBin(var WhseWorksheetLine: Record "Whse. Worksheet Line"; var Bin: Record Bin; BinCode: Code[20]; Cubage: Decimal; Weight: Decimal; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
