### ISSUE TITLE
[Event Request] Table 5895 Inventory Adjustment Buffer - OnSumCostsTillValuationDateOnBeforeCalcSums

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8533]
Hi Team,

In table 5895 we need possibility to add modify record with our own code. Having event on procedure `SumCostsTillValuationDate`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92400802-2d12f800-f135-11ea-851b-5344db75831a.png)

    [IntegrationEvent(false, false)]
    local procedure OnSumCostsTillValuationDateOnBeforeCalcSums(var Rec: Record "Inventory Adjustment Buffer"; var QtyFactor: decimal; FromDate: Date; ToDate: Date; ValueEntry: Record "Value Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
