### ISSUE TITLE
[Event Request] Codeunit 1535 Approvals Mgt. - PopulateApprovalEntryArgument

### ISSUE THREAD

**Issue by eque2al** [microsoft/ALAppExtensions#8534]
Often documents are created for large values and then small additions or changes are made (for example, adding shipping/freight charges or altering a VAT Product Posting Group).  With standard Microsoft Business Central Approvals functionality this means that a document has to pass all the way back through the approvals chain for each and every change.  

Our large customers won't accept this so I added an ‘Approval Type’ field to P&P Setup with the standard option of “Total” and a new option of “Movement” and added code so that during the Approval Request process this field is checked and if set to “Movement” then it works on the difference in the document value between approval requests.  If the Movement Amount falls within the Approval Limit for the Current User then it automatically approves the Document and if not then it will send a request for approval to whoever has a high-enough limit for the movement amount.  

This is impossible in V16 as the only event is **OnPopulateApprovalEntryArgument** and this is only called within a case statement when a non-standard table is being processed (ie. not Purchase Header!).

So please either move this integration event outside the case statement or better still add  **OnBeforePopulateApprovalEntryArgument** and **OnAfterPopulateApprovalEntryArgument** events.

This is absolutely critical for our product to be able to ship in 3 weeks time!  Please can you prioritise this?

code example:

![image](https://user-images.githubusercontent.com/57717503/92404166-d0aadb00-f12a-11ea-9ebc-c05cb949a4e4.png)

**Comment by StanPesotskiy** [comment]
We cannot move events. Please specify exact code for events OnBeforePopulateApprovalEntryArgument and OnAtterPopulateApprovalEntryArgument. Do you need IsHandled for both?

**Comment by eque2al** [comment]
No problem, yes to the question regarding "IsHandled" - it is always useful, thanks:

 OnBeforePopulateApprovalEntryArgument(WorkflowStepInstance: Record "Workflow Step Instance"; var ApprovalEntryArgument: Record "Approval Entry"; var IsHandled);

OnAfterPopulateApprovalEntryArgument(WorkflowStepInstance: Record "Workflow Step Instance"; var ApprovalEntryArgument: Record "Approval Entry"; var IsHandled);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
