### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnValidateVendorNoOnBeforeCheckVendBlocked

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8535]
Hi Team,

In table 246 Requisition Line field "Vendor No." OnValidate we would like to change how blocked vendors are handled, having a handler before the check would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/92445222-ac97da00-f1bc-11ea-977b-e918a3f23a48.png)

```
[IntegrationEvent(false, false)]
local procedure OnValidateVendorNoOnBeforeCheckVendBlocked(var RequisitionLine: Record "Requisition Line"; Vendor: Record Vendor; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
