### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnBeforeValidateQuantityBase

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8536]
Hi team,

In table 246 Requisition Line field Quantity (Base) OnValidate we would like to replace standard code with our own, adding a handler before code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/92447371-cd156380-f1bf-11ea-8189-744fa43e3c73.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateQuantityBase(var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
