### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnBeforeOnDelete

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8537]
HI Team,

In table 246 Requisition Line OnDelete we would like to change standard code with our own, adding a handler before the code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/92448783-ca1b7280-f1c1-11ea-88c2-166330165870.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnDelete(var ReqLine: Record "Requisition Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
