### ISSUE TITLE
[Event Request] Table 263 "Intrastat Jnl. Line" - OnValidateCountryRegionofOriginCode

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8538]
Hi team,

In table 263 "Intrastat Jnl. Line" field "Country/Region of Origin Code" OnValidate we would like to replace standard code with our own, adding an event before would be a good solution for this:
![image](https://user-images.githubusercontent.com/49302698/92460084-33a27d80-f1d0-11ea-846f-715864e636d6.png)

```
[IntegrationEvent(false, false)]
local procedure OnValidateCountryRegionofOriginCode(var IntrastatJnlLine: Record "Intrastat Jnl. Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
