### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnBeforeValidateVariantCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8539]
Hi Team,

In table 5767 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of `OnValidate` trigger on field `Variant code` :
![image](https://user-images.githubusercontent.com/70525691/92465923-f9d57500-f1d7-11ea-9ccb-8108d6daa1de.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateVariantCode(var Rec: Record "Warehouse Activity Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
