### ISSUE TITLE
Table 32 Item Ledger Entry Enable Key

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#854]
On table 32 Item Ledger Entry can you enable Key

Item No.,Open,Variant Code,Positive,Location Code,Posting Date,Expiration Date,Lot No.,Serial No.

**Comment by JesperSchulz** [comment]
Sorry about the delay on this one. We've tried to make this rather simple change for a while now, but somehow it seems to alter the behavior of the product, making a few of our internal tests fail. We're investigating why that it, as that should not be the case.

**Comment by AlexanderYakunin** [comment]
We have found the reason why we couldn't enable this key without failed tests. Required change is too complex and we cannot make it now. In order to understand your issue better - can you explain why do you need this specific key, if everything works without it?
