### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnValidateQtyToHandleOnBeforeCalcQtyToHandleBase

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8540]
Hi Team,

In table 5767 we need possibility to modify record with our own code. Having event in `OnValidate` trigger on field `Qty. to Handle`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92466850-6309b800-f1d9-11ea-9266-90fd7791bb0a.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateQtyToHandleOnBeforeCalcQtyToHandleBase(var WarehouseActivityLine: Record "Warehouse Activity Line"; var xWarehouseActivityLine: Record "Warehouse Activity Line"; Location: Record Location; CurrFieldNo: Integer)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
