### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnBeforeLookUpBinCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8541]
In table 5767 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of `OnLookup` trigger on field `Bin Code`, would be perfect solution :
![image](https://user-images.githubusercontent.com/70525691/92468076-47071600-f1db-11ea-84af-63c40becf9db.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookUpBinCode(var WarehouseActivityLine: Record "Warehouse Activity Line"; var Item: Record Item; var BinCode: Code[20]; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
