### ISSUE TITLE
[Event Request] Table 289 "Payment Method" - OnBeforeCheckGLAcc

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8542]
Hi team,

In table 289 "Payment Method" function CheckGLAcc we would like to replace standard code, to make it work depending on CurrFieldNo value, adding an event at start of function would be a good solution for this:
![image](https://user-images.githubusercontent.com/49302698/92461555-19699f00-f1d2-11ea-98a5-641d1667d617.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckGLAcc(PaymentMethod: Record "Payment Method"; CurrFieldNo: Integer; AccNo: Code[20]; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
