### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnBeforeLookUpBinCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8544]
In table 5767 we need possibility to replace and avoid using standard code with our own. Having event with handling in procedure `SplitLine`, would be perfect solution :
![image](https://user-images.githubusercontent.com/70525691/92474264-36a76900-f1e4-11ea-9b99-b455c02bb205.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeNewWhseActivLine(var WarehouseActivityLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
