### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnAfterShowDeleteMeassage

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8545]
Hi Team,

In table 5767 we need possibility to modify record with our own code. Having event in the end of procedure `ShowDeletedMessage`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92474827-217f0a00-f1e5-11ea-9bb3-3e8ae6dcfc00.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterShowDeleteMeassage(var WhseActivLine: Record "Warehouse Activity Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
