### ISSUE TITLE
[Additional Parameter Request] Table 5767 Warehouse Activity Line - OnBeforeDeleteWhseActivLine2

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8546]
Hi Team,
In table 5767 we need possibility to have additional checks in the procedure `DeleteRelatedWhseActivLines`. Standard publisher would suit us if it had additional parameter with boolean type IsHandled. OnBeforeDeleteWhseActivLine2 would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92476635-f518bd00-f1e7-11ea-95b4-7ee7ba6e2344.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteWhseActivLine2(var WarehouseActivityLine2: Record "Warehouse Activity Line"; CalledFromHeader: Boolean; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
