### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnDeleteRelatedWhseActivLinesBeforeFilterLineNo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8547]
Hi Team,

In table 5767 we need possibility to modify record with our own code. Having event in procedure `DeleteRelatedWhseActivLines` , would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92478206-7ffab700-f1ea-11ea-9683-de9e4f244b7b.png)

    [IntegrationEvent(false, false)]
    local procedure OnDeleteRelatedWhseActivLinesBeforeFilterLineNo(var WhseActivLine: Record "Warehouse Activity Line"; var WhseActivLine2: Record "Warehouse Activity Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
