### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnBeforeCheckIncreaseBin

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8548]
In table 5767 we need possibility to replace and avoid using standard code with our own. Having event with handling in procedure `CheckIncreaseCapacity`, would be perfect solution :
![image](https://user-images.githubusercontent.com/70525691/92479017-ad943000-f1eb-11ea-83c6-6c1a469070a3.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIncreaseBin(var WarehouseActivityLine: Record "Warehouse Activity Line"; var Bin: Record Bin; DeductCubage: Decimal; DeductWeight: Decimal; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
