### ISSUE TITLE
[Event Request] Table 296 "Reminder Line" - OnBeforeGetNoOfReminderForCustLedgEntry

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8549]
Hi team,

In table 296 "Reminder Line" function GetNoOfReminderForCustLedgEntry we would like to change how NoOfReminders is calculated, adding an event at start of function code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/92468787-63f01900-f1dc-11ea-84fb-b1ff45e69a51.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetNoOfReminderForCustLedgEntry(var ReminderLine: Record "Reminder Line"; var NoOfReminders: Integer; EntryNo: Integer; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
