### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnValidateBinCodeAfterCheckValidBinCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8550]
In table 5767 we need possibility to replace and avoid using standard code with our own. Having event with handling in trigger `OnValidate` on field `Bin Code`, would be perfect solution :

![image](https://user-images.githubusercontent.com/70525691/92485091-2e0a5f00-f1f3-11ea-96d8-85704a9f0891.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateBinCodeAfterCheckValidBinCode(var Rec: Record "Warehouse Activity Line"; var xRec: Record "Warehouse Activity Line"; CurrFieldNo: Integer; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
