### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnHandleActivityTypePick

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8551]
In table 5767 we need possibility to replace and avoid using standard code with our own. Having event with handling on procedure `ShowActivityDoc`, would be perfect solution :
![image](https://user-images.githubusercontent.com/70525691/92486328-a02f7380-f1f4-11ea-81dc-e044510c95a9.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnHandleActivityTypePick(var WarehouseActivityHeader: Record "Warehouse Activity Header"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
