### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnConfirmWhseActivLinesBeforeFilterLineNo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8552]
In table 5767 we need possibility to replace and avoid using standard code with our own. Having event with handling on procedure `ConfirmWhseActivLinesDeletionOutOfBalance`, would be perfect solution :
![image](https://user-images.githubusercontent.com/70525691/92491905-7168cb80-f1fb-11ea-8405-3d9d7d416c45.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnConfirmWhseActivLinesBeforeFilterLineNo(var WhseActivLine: Record "Warehouse Activity Line"; var WhseActivLine2: Record "Warehouse Activity Line"; var WhseActivLine3: Record "Warehouse Activity Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
