### ISSUE TITLE
[Event Request] Table 383 "Detailed CV Ledg. Entry Buffer" - OnBeforeInsertDtldCVLedgEntryBuf

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8553]
Hi team,

In table 383 "Detailed CV Ledg. Entry Buffer" function InsertDtldCVLedgEntry we would like to assign some custom fields to the DtldCVLedgEntryBuf record from CVLedgEntryBuf before code is ran, for this an event before NewDtldCVLedgEntryBuf.Init() would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/92566420-e3392780-f284-11ea-9ada-d90354e0f2b3.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertDtldCVLedgEntryBuf(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CVLedgEntryBuf: Record "CV Ledger Entry Buffer")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
