### ISSUE TITLE
[Event Request] Table 96 G/L Entry Budget - VerifyNoRelatedAnalysisViewBudgetEntries

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8554]
In the Table 96 G/L Entry Budget, there is the local procedure VerifyNoRelatedAnalysisViewBudgetEntries
It is filtering with a SETRANGE between the current Rec and xRec values for the fields "Budget name", "G/L Account No.", "Posting Date", "Business Unit Code".
What we used to do was to replace the xRec value by the Rec one, to only SETRANGE on the Rec value.

Ex. : 
AnalysisViewBudgetEntry.SETRANGE("Budget Name","Budget Name");
instead of 
AnalysisViewBudgetEntry.SETRANGE("Budget Name",GLBudgetEntry."Budget Name");
where GLBudgetEntry = xRec

We can't do it right now. Is it possible to raise an event here like that please : 
![image](https://user-images.githubusercontent.com/34645582/92569695-3a3cfd80-f281-11ea-8ec6-f77110d09696.png)

![image](https://user-images.githubusercontent.com/34645582/92571619-a15bb180-f283-11ea-90a2-efd1f2faaf94.png)

Thank you for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
