### ISSUE TITLE
[Additional Parameter Request] Table 383 "Detailed CV Ledg. Entry Buffer" - OnInsertDtldCVLedgEntryOnBeforeModify

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8555]
Hi team,

In table 383 "Detailed CV Ledg. Entry Buffer" function InsertDtldCVLedgEntry we would like to assign custom fields some values. For that we would need an extra parameter in `OnInsertDtldCVLedgEntryOnBeforeModify` event: 
![image](https://user-images.githubusercontent.com/49302698/92571896-5d20df00-f28c-11ea-8dd3-0b287a431de2.png)

[IntegrationEvent(false, false)]
local procedure OnInsertDtldCVLedgEntryOnBeforeModify(var DetailedCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; **NewDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
