### ISSUE TITLE
[Event Request] Codeunit 99000774 Function LoadCapForward

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#8563]
Hello Team,

we need a new publisher before calculating the Startingdate and Time

OLD CODE:
ProdOrderRoutingLine."Starting Date" := ProdEndingDate;
ProdOrderRoutingLine."Starting Time" := ProdEndingTime;

CalendarEntry.SetCapacityFilters(CapType,CapNo);

NEW CODE

OnBeforeSettingDateAndTimeForward(TimeType, var ProdStartingDate, var ProdStartingTime; ProdOrderRoutingLine, RemainNeedQty)
ProdOrderRoutingLine."Ending Date" := ProdStartingDate;
ProdOrderRoutingLine."Ending Time" := ProdStartingTime;

CalendarEntry.SetCapacityFilters(CapType,CapNo);

thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
