### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - OnCheckReservedItemTrkg

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8564]
Hi Team,

In table 5767 we need possibility to add modify record with our own code. Having event at the end of procedure `CheckReservedItemTrkg`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92588386-931c8e00-f2a1-11ea-9cdd-f8de5b29ac81.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnCheckReservedItemTrkg(var WarehouseActivityLine: Record "Warehouse Activity Line"; var xWarehouseActivityLine: Record "Warehouse Activity Line"; CurrFieldNo: Integer; var LineReservedQty: Decimal)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
