### ISSUE TITLE
[Event Request] Table 7331 Warehouse Journal Line - OnSetFiltersBeforeFindWhseJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8565]
Hi Team,

In table 7331 we need possibility to add modify record with our own code. Having event at the beginning of procedure `SetUpNewLine`, would be perfect solution:
![image](https://user-images.githubusercontent.com/70525691/92591670-01178400-f2a7-11ea-9f04-5b082c615621.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnSetFiltersBeforeFindWhseJnlLine(var Rec: Record "Warehouse Journal Line"; WhseJnlLine: Record "Warehouse Journal Line"; LastWhseJnlLine: Record "Warehouse Journal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
