### ISSUE TITLE
[Event Request] Table 7331 Warehouse Journal Line - OnTemplateSelectionOnBeforeCount

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8567]
Hi Team,

In table 7331 we need possibility to add modify record with our own code. Having event at the beginning of procedure `TemplateSelection`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92592520-5e600500-f2a8-11ea-8f9a-d89d0e2d7f05.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnTemplateSelectionOnBeforeCount(var WhseJnlLine: Record "Warehouse Journal Line"; var WhseJnlTemplate: Record "Warehouse Journal Template"; OpenFromBatch: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
