### ISSUE TITLE
[Event Request] Table 7331 Warehouse Journal Line - OnBeforeTemplateSelectionFromBatch

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8568]
Hi Team,

In table 7331 we need possibility to add modify record with our own code. Having event at the beginning of procedure `TemplateSelectionFromBatch`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92592793-cb739a80-f2a8-11ea-8b2d-00d44da66d4b.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTemplateSelectionFromBatch(var WhseJnlLine: Record "Warehouse Journal Line"; WhseJnlBatch: Record "Warehouse Journal Batch")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
