### ISSUE TITLE
[Event Request] Table 7331 Warehouse Journal Line - OnAfterOpenJnl

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8569]
Hi Team,

In table 7331 we need possibility to add modify record with our own code. Having event at the end of procedure `OpenJnl`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92592954-0249b080-f2a9-11ea-9694-749fb13e53d7.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterOpenJnl(var WhseJnlLine: Record "Warehouse Journal Line"; CurrentJnlBatchName: Code[10]; CurrentLocationCode: Code[10])
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
