### ISSUE TITLE
Func Expose Page Transfer Order (5740)

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/ALAppExtensions#857]
Can function IsPartiallyShipped be exposed as global/external?

**Comment by darjoo** [comment]
Hi @GreatScott000,

As it is a local function, we would like to avoid exposing it and it is a simple function which you could copy. Would that work for what you are trying to achieve?

**Comment by GreatScott000** [comment]
I am not quite I understand the reasoning here.  Yes, I can duplicate the code and yes it is a simple function but is one more piece of code I have keep synchronized with the base application.  Over time the base function could change for any number of reasons (like you add an event publisher to allow additional conditions to be checked to determine if the order is partially shipped) and then my copy of the function is out of date. 

I see no "harm" in exposing this function.  An argument could even be made this function should reside on the Transfer Header as a public function and not on the page at all.

**Comment by darjoo** [comment]
We’re still in the early stages of refactoring, and we’re focused on helping to unblock people who have an immediate need. You’re right, like a lot of other functions, IsPartiallyShipped might become an blocker in the future, but it isn’t right now.
