### ISSUE TITLE
[Event Request] Table 7331 Warehouse Journal Line - OnAfterSetName

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8570]
Hi Team,

In table 7331 we need possibility to add modify record with our own code. Having event at the end of procedure SetName, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92593223-6cfaec00-f2a9-11ea-9e37-af7474e16cd4.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetName(var WhseJnlLine: Record "Warehouse Journal Line"; var WhseJnlLine2: Record "Warehouse Journal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
