### ISSUE TITLE
[Event Request] Table 7331 Warehouse Journal Line - OnLookupNameOnRunModalOnBeforeSetName

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8572]
Hi Team,

In table 7331 we need possibility to add modify record with our own code. Having event at the end of procedure `LookupName`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92595501-24453200-f2ad-11ea-8c5d-67ff7730dd1e.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnLookupNameOnRunModalOnBeforeSetName(var WhseJnlLine: Record "Warehouse Journal Line"; WhseJnlBatch: Record "Warehouse Journal Batch")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
