### ISSUE TITLE
[Event Request] Table 7331 Warehouse Journal Line - OnAfterOpenItemTrackingLines

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8573]
Hi Team,

In table 7331 we need possibility to add modify record with our own code. Having event at the end of procedure `OpenItemTrackingLines`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92596003-c9600a80-f2ad-11ea-9195-4ad085375fa8.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterOpenItemTrackingLines(var WhseJnlLine: Record "Warehouse Journal Line"; var WhseItemTrackingLines: Page "Whse. Item Tracking Lines")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
