### ISSUE TITLE
[Event Request] Table 7311 Warehouse Journal Line - OnLookupBinCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8574]
Hi Team,

In table 7311 we need possibility to modify record with our own code. Having event with handling in the beginning of procedure `LookupBinCode`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92601752-e3055000-f2b5-11ea-9363-878df363dec8.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnLookupBinCode(var WhseJnlLine: Record "Warehouse Journal Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
