### ISSUE TITLE
[Event Request] Table 7321 Warehouse Shipment Line - OnBeforeCheckIncreaseBin

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8576]
In table 7321 we need possibility to replace and avoid using standard code with our own. Having event with handling on procedure `CheckBin`, would be perfect solution :

![image](https://user-images.githubusercontent.com/70525691/92606296-74c38c00-f2bb-11ea-9add-dbac0e793820.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIncreaseBin(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var Bin: Record Bin; DeductCubage: Decimal; DeductWeight: Decimal; IgnoreErrors: Boolean; var ErrorOccured: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
