### ISSUE TITLE
[Event Request] Table 7311 Warehouse Activity Line - OnBeforeCheckIncrease

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8577]
Hi Team,

In table 7311 we need possibility to modify record with our own code. Having event with handling on procedure `CheckBin`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92606643-d683f600-f2bb-11ea-93cf-65c947a98cbb.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIncrease(WhseJnlLine: Record "Warehouse Journal Line"; BinCode: Code[20]; StockProposal: Boolean; var Ishandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
