### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnAfterApplyVendEntries

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8578]
Hi Team,

In table 81 we need possibility to modify record with our own code. Having event in the procedure `LookUpAppliesToDocVend`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92613659-e1db1f80-f2c3-11ea-8cee-cfbd84f9e56d.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterApplyVendEntries(var GenJorunalLine: Record "Gen. Journal Line"; GenJnlLine: Record "Gen. Journal Line"; GenJnlApply: Codeunit "Gen. Jnl.-Apply"; PaymentToleranceMgt: Codeunit "Payment Tolerance Management"; VendLedgEntry: Record "Vendor Ledger Entry"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
