### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnAfterLookUpAppliesToDocVend

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8579]
Hi Team,

In table 81 we need possibility to modify record with our own code. Having event at the end of the procedure `LookUpAppliesToDocVend`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92613891-1fd84380-f2c4-11ea-86f9-b0381e546c34.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterLookUpAppliesToDocVend(var GenJournalLine: Record "Gen. Journal Line"; CustLedgEntry: Record "Cust. Ledger Entry"; VendLedgEntry: Record "Vendor Ledger Entry"; ApplyVendEntries: Page "Apply Vendor Entries")

**Comment by RomanZanizdra** [comment]
Hi @MantasGurinas . Why do you need ApplyVendEntries page as parameter in this event? Is it ok if you get it in event above?

**Comment by MantasGurinas** [comment]
Hi @RomanZanizdra , after inspecting more, it can be moved to event above or dismissed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
