### ISSUE TITLE
[Event Request] codeunit 333 "Req. Wksh.-Make Order" - Event for procedure Code 

### ISSUE THREAD

**Issue by osteeger** [microsoft/ALAppExtensions#8581]
Can you please change the procedure **FinalizeOrderHeader** to not local
```
   //
    //local procedure FinalizeOrderHeader(PurchOrderHeader: Record "Purchase Header"; var ReqLine: Record "Requisition Line")
    procedure FinalizeOrderHeader(PurchOrderHeader: Record "Purchase Header"; var ReqLine: Record "Requisition Line")
    //
```

And can you change the **OnCodeOnAfterProcessReqLineActions** event? We need the sender in the event.
```
    [IntegrationEvent(true, false)]
    local procedure OnCodeOnAfterProcessReqLineActions(var PurchOrderHeader: Record "Purchase Header"; var IsHandled: Boolean; var ReqLine: Record "Requisition Line")
    begin
    end;
```

**Comment by RomanZanizdra** [comment]
Hi @osteeger . Could you clarify the name of the event? I cannot find it in the codeunit and in the app.

**Comment by osteeger** [comment]
Hi @RomanZanizdra, the Event call **"OnCodeOnBeforeFinalizeOrderHeader"**.

For this Event we need IncludeSender:
 ```
 [IntegrationEvent(true, false)]
    local procedure OnCodeOnBeforeFinalizeOrderHeader(PurchOrderHeader: Record "Purchase Header"; var ReqLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
