### ISSUE TITLE
[Event Request] table 9053 "Sales Cue"

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#8584]
![image](https://user-images.githubusercontent.com/35260264/92704686-66c14a00-f353-11ea-9dad-0e8cf529b48d.png)

![image](https://user-images.githubusercontent.com/35260264/92704757-73de3900-f353-11ea-960b-fe93f64fb993.png)

![image](https://user-images.githubusercontent.com/35260264/92705380-f5ce6200-f353-11ea-8a4b-9338a937fa33.png)

**Comment by RomanZanizdra** [comment]
Hi @DanielHaglo .
Couple of questions regarding to your request. 
The first event: do I understand correctly that you need event for case else statement? Or you can use OnFilterOrdersOnAfterSalesHeaderSetFilters(SalesHeader)? We can add extra parameter FieldNumber there.
The second event: why do you need SalesHeader there? It is used only to set range on a Status, this is the only usage. What How you are going to use it, especially in the end of the function?

**Comment by RomanZanizdra** [comment]
Hi @DanielHaglo , any update from your side?

**Comment by DanielHaglo** [comment]
Hi,

Im sorry, have not have the time to respond you.
There are no needs for these events afterall :)
