### ISSUE TITLE
[Event Request] Table 5080 To do - OnValidateTeamCodeOnBeforeCheckIfWorkerAssigned

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8585]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of `OnValidate` trigger on field `Team Code` :

![image](https://user-images.githubusercontent.com/70525691/92721476-d2fd7700-f36e-11ea-8a2f-bb5b4a0fb6d2.png)

    [IntegrationEvent(false, false)]
    local procedure OnValidateTeamCodeOnBeforeCheckIfWorkerAssigned(var Todo: Record "To-do"; var xTodo: Record "To-do"; var isHandled: boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
