### ISSUE TITLE
[Event Request] Table 5080 To do - OnBeforeValidateContactNo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8587]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of `OnValidate` trigger on field `Contact No.` :

![image](https://user-images.githubusercontent.com/70525691/92723043-27095b00-f371-11ea-8851-22ff5bd3af75.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateContactNo(var Todo: Record "To-do"; var xTodo: Record "To-do"; var isHandled: boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
