### ISSUE TITLE
[Event Request] Table 5080 To do - OnBeforeValidateType

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8588]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of `OnValidate` trigger on field `Type` :

![image](https://user-images.githubusercontent.com/70525691/92723316-92ebc380-f371-11ea-803a-26e86aaa1546.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateType(var Todo: Record "To-do"; var isHandled: boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
