### ISSUE TITLE
[Event Request] Codeunit 99000810 Function CreatePlanningCapNeed

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#8589]
Hello Team,

we need a new Publisher to intercept the Needqty before in use:

OLD CODE:
ProdOrderCapNeed.INIT;
ProdOrderCapNeed."Worksheet Template Name" := ReqLine."Worksheet Template Name";

NEW CODE:
OnBeforeCreatePlanningCapNeed[PlanningRoutingLine; TimeType; var NeedQty);
ProdOrderCapNeed.INIT;
ProdOrderCapNeed."Worksheet Template Name" := ReqLine."Worksheet Template Name";

Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
