### ISSUE TITLE
[Event Request] Table 5080 To do - OnBeforeValidateType

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8590]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of procedure  `DeleteAttendeeTask`:

![image](https://user-images.githubusercontent.com/70525691/92726608-83bb4480-f376-11ea-86aa-4c0fef53abfb.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteAttendeeTask(var Todo: Record "To-do"; var isHandled: boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
