### ISSUE TITLE
[Event Request] Table 5080 To do - OnBeforeSetDuration

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8591]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of procedure `SetDuration`:

![image](https://user-images.githubusercontent.com/70525691/92728752-ff6ac080-f379-11ea-89a6-335433a4753e.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetDuration(Todo: Record "To-do"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
