### ISSUE TITLE
[Extensability Bug] Codeunit FileManagement

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8592]
The procedures BrowseForFolderDialog and SelectFolderDialog do not have the specification 
[Scope('OnPrem')]

and will crash when executing in the Cloud because they use dotnet.

To check alreday at designtime the [Scope('OnPrem')] should be added.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for releasee 17.

**Comment by JesperSchulz** [comment]
Update: we've decided to obsolete a few functions, rather than just changing scope. Further updates to the code are to be expected :-)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 17.

**Comment by JesperSchulz** [comment]
Final update: this effort snowballed and has led to the deprecation of many functions. Most changes will hence ship with the upcoming major rather than in a minor.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
