### ISSUE TITLE
[Event Request] Table 5080 To do - OnBeforeGetEndDateTime

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8593]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of procedure GetEndDateTime:

![image](https://user-images.githubusercontent.com/70525691/92730933-2080e080-f37d-11ea-95ac-66435107b5fd.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetEndDateTime(var Todo: Record "To-do"; var isHandled: Boolean; CurrFieldNo: Integer)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
