### ISSUE TITLE
[Event Request] Table 5080 To do - OnBeforeUpdateAttendeeTasks

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8594]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of procedure `UpdateAttendeeTasks`:

![image](https://user-images.githubusercontent.com/70525691/92731688-14495300-f37e-11ea-8d34-e61fb9d00d1b.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateAttendeeTasks(var Todo: Record "To-do"; var isHandled: boolea
```n)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
