### ISSUE TITLE
[Event Request] Table 5080 To do - OnChangeTeamOnBeforeModify

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8595]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of procedure ChangeTeam:

![image](https://user-images.githubusercontent.com/70525691/92732043-8cb01400-f37e-11ea-9916-0c11e88428dc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
