### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnBeforeInsertApplEntry

### ISSUE THREAD

**Issue by SjoerddeClippelaar** [microsoft/ALAppExtensions#8596]
Dear Microsoft,

The variables in this new event are not by var. Could you change that? We would like to reset the variables.

![image](https://user-images.githubusercontent.com/50202846/92741204-a9e4e280-f37e-11ea-8f1e-2cd88da3cefd.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
