### ISSUE TITLE
[EventRequest] Page 5915 Service Tasks - Function SetAllFilters, OnAfterSetAllFilters

### ISSUE THREAD

**Issue by rellorin** [microsoft/ALAppExtensions#8597]
Hi,

I am requesting a new event to add additional filtering to the SetAllFilters function on page 5915.

OnAfterSetAllFilters(var Rec: Record "Service Item Line")

#event-request

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by SebastiaanLubbers** [comment]
@bc-ghost please allow GlobalVarAccess thru this event so you can actually use it.

@rellorin you agree with this or do you have an example where you have added a functional filter?

**Comment by rellorin** [comment]
> @bc-ghost please allow GlobalVarAccess thru this event so you can actually use it.
> 
> @rellorin you agree with this or do you have an example where you have added a functional filter?

The addition of this event has satisfied my requirements. I don't need GlobalVarAccess to use the event. I just copied the same pattern as all the other Filter Functions (for example, look at SetServOrderFilter() on the same page)

**Comment by db-bc** [comment]
`GlobalVarAccess` is deprecated and will become an error, so it makes no sense to recommend it.
