### ISSUE TITLE
[Event Request] Table 5080 To do - OnStartWizardOnBeforeCreateTaskRunModal

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8598]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event in the end of procedure `StartWizard`:

![image](https://user-images.githubusercontent.com/70525691/92741719-91c59100-f387-11ea-9a26-bb2acf679887.png)

    [IntegrationEvent(false, false)]
    local procedure OnStartWizardOnBeforeCreateTaskRunModal(var Todo: Record "To-do")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
