### ISSUE TITLE
[Event Request] Table 5080 To do - OnValidateSalesPersonCodeOnBeforeReassignTeamTaskToSalesPerson

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8599]
Hi Team,

In table 5080 we need possibility to replace and avoid using standard code with our own. Having event in the end of `OnValidate` trigger on field `Salesperson Code` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92749499-d56fc900-f38e-11ea-979f-cb1554a307c2.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateSalesPersonCodeOnBeforeReassignTeamTaskToSalesPerson(var Rec: Record "To-do"; var isHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
