### ISSUE TITLE
[Event Request] Table 49 "Invoice Post. Buffer" - OnBeforeCalcDiscount

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8600]
We are migrating our NAV2018 code to BC 16.4. In the table 49 "Invoice Post. Buffer", we modified a lot the way discounts were calculated. We added parameters to the procedure CalcDiscount, and commented the end of the procedure.

In order to reproduce these changes in the BC version, we would need to have at the beginning of the procedure CalcDiscount an event raised and a switch IsHandled just after the event, like this : 

![image](https://user-images.githubusercontent.com/34645582/92753031-c4708900-f389-11ea-8ba5-bac52c3bb3a8.png)
With the event publisher : 
![image](https://user-images.githubusercontent.com/34645582/92753075-cf2b1e00-f389-11ea-867c-15c0d4023659.png)

Do you think it could be possible ? Thank you for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
