### ISSUE TITLE
Bug in the Caption with & Sign

### ISSUE THREAD

**Issue by pranav4186** [microsoft/ALAppExtensions#8601]
In our app we have pages with & sign in the caption. When we open the page from menu, BC adds another "&" in the caption, but the caption looks good if we open that page in separate window.
![image](https://user-images.githubusercontent.com/35543761/92827088-4a8ad080-f386-11ea-9e72-9083ada0a1b4.png)

same page in separate window
![image](https://user-images.githubusercontent.com/35543761/92827188-6bebbc80-f386-11ea-86af-141a26d749e1.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
