### ISSUE TITLE
[Event Request] Prepayment Posting events (Codeunit 442 and Codeunit 444)

### ISSUE THREAD

**Issue by JeremyVyska** [microsoft/ALAppExtensions#8602]
In the Sales and Purchase Codeunits ( 442 & 444 ), there are a lot of great functions that could use a bit more extensibility.

For example, in Purchase, the flow is to do 
- PostPrepmtInvLinebuffer
- PostVendorEntry
- PostBalancingEntry

Each of those functions at the end calls posting like so:

`OnBeforePostVendorEntry(GenJnlLine, TotalPrepmtInvLineBuffer, TotalPrepmtInvLineBufferLCY, SuppressCommit);
GenJnlPostLine.RunWithCheck(GenJnlLine);
OnAfterPostVendorEntry(GenJnlLine, TotalPrepmtInvLineBuffer, TotalPrepmtInvLineBufferLCY, SuppressCommit);`

It would greatly increase the value of this pattern if the OnBeforePost even had an IsHandled that was wrapped around the GenJnlPostLine.

Use case scenario:  
I have a customer that, pre BC, would have prepayments terms with their customers/vendors where they split their prepayments, such as 30% NET30, 30% NET180, and 40% NET360.  This is very common in the Wine trading industry where products are bought and sold a year in advance of production.

In older versions of NAV, I could disable the PostVendor  handling and replace it with 3 Vendor side posting steps.  This allows a single prepayment invoice to have an extended Payment Terms that results in 3 different Vendor Ledger Entries, each with the relevant amounts and due dates.

To my knowledge, this would not be possible.

Alternate solution if the Before/After pattern above is not acceptable:   In the main Code procedure of 442/444, having a similar OnBefore(...,IsHandled) pattern before PostVendorEntry (and the like from above).  This would equally allow intervention of posting and allow for refactoring in events.   

The GL Consistency check would still catch if an event fails to tally the correct invoicing lines - such as incorrectly disabling the event entirely without posting balancing entries.

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots or long textual descriptions.
