### ISSUE TITLE
[Event Request] Codeunit 367 - Check Management - 

### ISSUE THREAD

**Issue by Luca-Biundo** [microsoft/ALAppExtensions#8603]
Hi,

possibilty to filter de VendLedgEntry in the function FinancialVoidCheck

![image](https://user-images.githubusercontent.com/70574684/92896930-144c6000-f41d-11ea-8f99-4d9934a32c68.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by Luca-Biundo** [comment]
We need something like this event (**### _OnFinancialVoidCheckOnSetVendorLedgEntryFilter_**).

CheckLedgEntry."Bal. Account Type"::Vendor:
                begin
                    if ConfirmFinancialVoid.GetVoidType = 0 then begin    // Unapply entry
                        if UnApplyVendInvoices(CheckLedgEntry, ConfirmFinancialVoid.GetVoidDate) then
                            GenJnlLine2."Applies-to ID" := CheckLedgEntry."Document No.";
                    end;
                    with VendorLedgEntry do begin
                        SetCurrentKey("Transaction No.");
                        SetRange("Transaction No.", BankAccLedgEntry2."Transaction No.");
                        SetRange("Document No.", BankAccLedgEntry2."Document No.");
                        SetRange("Posting Date", BankAccLedgEntry2."Posting Date");
                         **### OnFinancialVoidCheckOnSetVendorLedgEntryFilter(var VendorLedgEntry ,BankAccLedgEntry2);**
                  if FindSet then
                            repeat
                                OnFinancialVoidCheckOnBeforePostVend(GenJnlLine2, VendorLedgEntry, BalanceAmountLCY);
                                CalcFields("Original Amount");
                                SetGenJnlLine(
                                  GenJnlLine2, -"Original Amount", "Currency Code", CheckLedgEntry."Document No.",
                                  "Global Dimension 1 Code", "Global Dimension 2 Code", "Dimension Set ID");
                                BalanceAmountLCY := BalanceAmountLCY + GenJnlLine2."Amount (LCY)";
                                OnFinancialVoidCheckOnBeforePostBalAccLine(GenJnlLine2, CheckLedgEntry);
                                GenJnlPostLine.RunWithCheck(GenJnlLine2);
                                OnFinancialVoidCheckOnAfterPostBalAccLine(GenJnlLine2, CheckLedgEntry, GenJnlPostLine);
                            until Next = 0;
                    end;
                end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
