### ISSUE TITLE
[Event Request] Table 5050 Contact - OnValidateCompanyNoOnBeforeCheckIfSegLineIsEmpty

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8605]
Hi Team,

In table 5050 we need possibility to replace and avoid using standard code with our own. Having event with handling in the on `OnValidate` trigger on field `Company No.`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/92921966-ad8b6e80-f43d-11ea-8795-ca89d021c829.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnValidateCompanyNoOnBeforeCheckIfSegLineIsEmpty(var SegLine: Record "Segment Line"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
