### ISSUE TITLE
[Additional Parameter Request] Codeunit 17 Gen. Jnl. - Post Reverse - OnReverseCustLedgEntryOnBeforeInsertDtldCustLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8606]
Hi Team,
In codeunit 17 we need possibility to have additional checks in the procedure `ReverseCustLedgEntry`. Standard publisher would suit us if it had additional parameter with boolean type IsHandled. `OnReverseCustLedgEntryOnBeforeInsertDtldCustLedgEntry` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92927655-a61c9300-f446-11ea-9849-167a8002fc91.png)

[IntegrationEvent(false, false)]
local procedure OnReverseCustLedgEntryOnBeforeInsertDtldCustLedgEntry(var NewDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
