### ISSUE TITLE
[Additional Parameter Request] Codeunit 17 Gen. Jnl. - Post Reverse - OnReverseVendLedgEntryOnBeforeInsertDtldVendLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8607]
Hi Team,
In codeunit 17 we need possibility to have additional checks in the procedure `ReverseVendLedgEntry`. Standard publisher would suit us if it had additional parameter with boolean type `IsHandled`. `OnReverseVendLedgEntryOnBeforeInsertDtldVendLedgEntry` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92927932-0dd2de00-f447-11ea-9f47-d257bda4e113.png)

[IntegrationEvent(false, false)]
local procedure OnReverseVendLedgEntryOnBeforeInsertDtldVendLedgEntry(var NewDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
