### ISSUE TITLE
[Additional Parameter Request] Codeunit 17 Gen. Jnl. - Post Reverse - OnApplyVendLedgEntryByReversalOnBeforeInsertDtldVendLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8609]
Hi Team,
In codeunit 17 we need possibility to have additional checks in the procedure `ApplyVendLedgEntryByReversal`. Standard publisher would suit us if it had additional parameter with boolean type IsHandled. `OnApplyVendLedgEntryByReversalOnBeforeInsertDtldVendLedgEntry` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92928570-f2b49e00-f447-11ea-99ed-591c8416fdb5.png)

[IntegrationEvent(false, false)]
local procedure OnApplyVendLedgEntryByReversalOnBeforeInsertDtldVendLedgEntry(var NewDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
