### ISSUE TITLE
Responsibility Center is not readily searchable

### ISSUE THREAD

**Issue by abvalenzona** [Microsoft/ALAppExtensions#861]
As per checking, though Responsibility Centres cannot be searched but, it is not entirely a missing feature.

Nevertheless, navigating to it is far from convenience where you need to go to the relevant field that calls the list of Responsibility Centres in such pages as customer card, vendor card, user setup.

Also, Company Information, Responsibility Centre no longer exists.

Can you please confirm if this will be fixed in the next BC update?

Version:
AU Dynamics NAV 13.1 (26534)

**Comment by JesperSchulz** [comment]
Let's get the issue to a team who will look into your question and maybe fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
