### ISSUE TITLE
[Event Request] Codeunit 57 Document Totals - OnSalesRedistributeInvoiceDiscountAmounts

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8610]
Hi Team,

In codeunit 57 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of procedure `SalesRedistributeInvoiceDiscountAmounts`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/92929451-3a87f500-f449-11ea-820c-27488c4dad54.png)

    [IntegrationEvent(false, false)]
    local procedure OnSalesRedistributeInvoiceDiscountAmounts(var TempSalesLine: Record "Sales Line"; var IsHandled: Boolean)

**Comment by StanPesotskiy** [comment]
Please use the existing event OnBeforeSalesRedistributeInvoiceDiscountAmounts().
