### ISSUE TITLE
[Event Request] Codeunit 76 Purch.-Get Drop Shpt. - OnCodeOnBeforeFindSalesLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8612]
Hi Team,

In codeunit 76 we need possibility to replace and avoid using standard code with our own. Having event in the procedure `Code` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92930671-0dd4dd00-f44b-11ea-8ff6-ea0e55765cc9.png)

    [IntegrationEvent(false,false)]
    local procedure OnCodeOnBeforeFindSalesLine(var SalesLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
