### ISSUE TITLE
Add reference to existing event - page 10810 "Generate EFT Files"

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#8613]
Hello,

Could you please add a reference to the existing publisher OnAfterOpenPage in OnOpenPage trigger but before UpdateSubForm procedure:

![image](https://user-images.githubusercontent.com/34686682/92929522-f85ab580-f440-11ea-91e5-c843a754262c.png)

There is already a similar code in a field BankAccountNo:

![image](https://user-images.githubusercontent.com/34686682/92930650-a3b83a00-f442-11ea-845a-058b6e26da84.png)

**Comment by radovandokic** [comment]
Hi @StanPesotskiy, this event already exists. We just need it to be called from the place as its name says - after OnOpenPage trigger.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by radovandokic** [comment]
Please consider making page variables as protected. In that case, we could use them in page extension.
