### ISSUE TITLE
[Event Request] Codeunit 229 Document-Print - OnBeforeGetSalesDocTypeUsage

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8615]
Hi Team,

In codeunit 229 we need possibility to replace and avoid using standard code with our own. Having event with handling in the begining of procedure `GetSalesDocTypeUsage`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/92932451-9a809a80-f44d-11ea-9736-42c52a28b07d.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetSalesDocTypeUsage(SalesHeader: Record "Sales Header"; var IsHandled: Boolean; var TypeUsage: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
