### ISSUE TITLE
[Event Request] Codeunit 231 Gen. Jnl.-Post - OnAfterPostBatch

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8616]
Hi Team,

In codeunit 231 we need possibility to replace and avoid using standard code with our own. Having event in the procedure `Code` on after `GenJnlPostBatch.Run`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/92933148-8c7f4980-f44e-11ea-9c2e-9da70c904c4f.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostBatch(var GenJnlLine: Record "Gen. Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
