### ISSUE TITLE
[Event Request] Codeunit 248 VAT Lookup Ext. Data Hndl - OnAfterOnRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8617]
Hi Team,

In codeunit 248 we need possibility to replace and avoid using standard code with our own. Having event in the trigger `OnRun`, would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/92933452-f0097700-f44e-11ea-918a-54f20ef3d688.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnRun(VATRegistrationLog: Record "VAT Registration Log"; var Rec: Record "VAT Registration Log")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
