### ISSUE TITLE
[Event Request] Codeunit 103 Cust. Entry-Edit - OnRunOnAftrerCustLedgEntryLockTable

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8618]
Hi Team,

In codeunit 103 we need possibility to replace and avoid using standard code with our own. Having event with handling in the  procedure `OnRun`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/92933975-99e90380-f44f-11ea-8d54-1aa81d8f3862.png)

    [IntegrationEvent(false, false)]
    local procedure OnRunOnAftrerCustLedgEntryLockTable(var Rec: Record "Cust. Ledger Entry"; var isHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
