### ISSUE TITLE
Filter counter in request page shows wrong values

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#8619]
With BC 16 (current SaaS system acting as our test environment) we have run into an issue that the counters for applied filters in the request page of reports do not work as expected.
At first, this came up in a report of our app but apparently the standard pages show this behaviour too.

Step 1: No filters applied
![grafik](https://user-images.githubusercontent.com/16236672/92936636-9d2dc080-f44a-11ea-8891-af6be2e18f74.png)
Step 2:  Filter is set on first data item (table  Customer)
![grafik](https://user-images.githubusercontent.com/16236672/92936663-a880ec00-f44a-11ea-8b1c-2fde8315fc26.png)
Step 3: Filter counter shows 0 filters for the customer table, instead the expected 1 for this table is shown for the next data items where actually no filters are applied at all.
![grafik](https://user-images.githubusercontent.com/16236672/92936692-b3d41780-f44a-11ea-8d21-e7bd04a9bf70.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
