### ISSUE TITLE
[Event Request] Table 352 - Default Dimension - OnBeforeUpdateGlobalDimCode

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#8621]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeUpdateGlobalDimCode` to be added to Table 352 Default Dimension with the following signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateGlobalDimCode(GlobalDimCodeNo: Integer; TableID: Integer; AccNo: Code[20]; NewDimValue: Code[20]; var IsHandled: Boolean)
    begin
    end;
```
with `VAR` parameter `IsHandled`.

which would be called as follows from `UpdateGlobalDimCode`:
```pascal
    local procedure UpdateGlobalDimCode(GlobalDimCodeNo: Integer; TableID: Integer; AccNo: Code[20]; NewDimValue: Code[20])
    var
        IsHandled: Boolean;
    begin
        // >> START
        OnBeforeUpdateGlobalDimCode(GlobalDimCodeNo, TableID, AccNo, NewDimValue, IsHandled);
        if IsHandled then
            exit;
        // << END  
        case TableID of
            ...
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
