### ISSUE TITLE
[Event Request] Codeunit 1221 "SEPA CT-Fill Export Buffer" - 

### ISSUE THREAD

**Issue by criorza** [microsoft/ALAppExtensions#8624]
Hi team,

In codeunit 1221 "SEPA CT-Fill Export Buffer" procedure FillExportBuffer we need to have  the following event available.

![image](https://user-images.githubusercontent.com/39953348/92947454-4f1fb980-f458-11ea-94c7-2f5d87d2f30b.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetMessageID(var MessageID: code [20],DocumentNo: code [20])
    begin
    end;

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
