### ISSUE TITLE
[Event Request] Codeunit 8800 Custom Layout Reporting, OnBeforeCallReportSaveAs

### ISSUE THREAD

**Issue by manishs-acumencentral** [microsoft/ALAppExtensions#8626]
Hi Team,

We are in a process to enhance Interaction Log capability. During this change/enhancement we came across new  event requirement as below:

Codeunit 8800 Custom Layout Reporting
    [External]
    PROCEDURE CallReportSaveAs@55(ReportID@1001 : Integer;RequestParameterText@1002 : Text;ReportFormatValue@1003 : ReportFormat;VAR FileStream@1004 : OutStream;VAR RecRef@1005 : RecordRef) : Boolean;
    VAR
      ReportSaved@1000 : Boolean;
    BEGIN
      //AC006b
      OnBeforeCallReportSaveAs(ReportID,ReportFormatValue);
      //AC006b

    [Integration]
    LOCAL PROCEDURE OnBeforeCallReportSaveAs@1000000001(ReportID@1000000000 : Integer;ReportFormatValue@1000000001 : ReportFormat);
    BEGIN
    END;

Thanks,
Manish Sinha

**Comment by StanPesotskiy** [comment]
Seems the requested code is copy&pasted from https://github.com/microsoft/ALAppExtensions/issues/8626. 
Could you please specify code for event OnBeforePrintReport mentioned in the header?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
