### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnSplitLineOnBeforeReNumberAllLines

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#8627]
Hi AL team,

we need a new event in table "Warehouse Activity Line", function "SplitLine":

    ...
    if LineSpacing = 0 then begin
    +++ OnSplitLineOnBeforeReNumberAllLines(NewWhseActivLine, WhseActivLine, NewLineNo, LineSpacing, 
            ReNumberingIsHandled);
    +++ if not ReNumberingIsHandled then begin
               ReNumberAllLines(NewWhseActivLine, WhseActivLine."Line No.", NewLineNo);
               WhseActivLine.Get(WhseActivLine."Activity Type", WhseActivLine."No.", NewLineNo);
               LineSpacing := 5000;
    +++ end;
    end;
    ...

And the event:
    
    ...
    +++ [IntegrationEvent(false, false)]
    +++ local procedure OnSplitLineOnBeforeReNumberAllLines(var NewWarehouseActivityLine: Record "Warehouse Activity 
             Line"; var WarehouseActivityLine: Record "Warehouse Activity Line"; var NewLineNo: Integer; var LineSpacing: Integer; var 
             ReNumberingIsHandled: Boolean)
    +++ begin
    +++ end;
    ...

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
