### ISSUE TITLE
[Additional Parameter Request] Report 12 "VAT Statement" - OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling

### ISSUE THREAD

**Issue by grabnar** [microsoft/ALAppExtensions#8628]
Problem: 
On VAT Statement report there is event **OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling**, which gave as possibility to modify calculation of amounts from VAT Entry.
But there is also **InitializeRequest** function which is used before report is run. In this function are some variables that have impact on calculations of total amounts, this means that user can select if report should be generated in local or additional currency for reporting. That information is lost through existing event, and is necessary to properly calculate amount on our own.

Suggestion:  
In evenet **OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling** also variable **UseAmtsInAddCurr** should be included:

_[IntegrationEvent(false, false)]_
_local procedure **OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling**(VATStmtLine: Record "VAT Statement Line"; var VATEntry: Record "VAT Entry"; var Amount: Decimal; **UseAmtsInAddCurr: Boolean**)
begin
end;_

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
