### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnBeforeItemLedgEntryCheckLocation

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8629]
Hi Team,

In codeunit 22 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure `InsertItemLedgEntry`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93084399-a3b37680-f69c-11ea-94ea-f518f8f573b5.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeItemLedgEntryCheckLocation(Location: Record Location; ItemLedgEntry: Record "Item Ledger Entry"; var IsHandled: Boolean)

**Comment by StanPesotskiy** [comment]
Can't you use the existing event OnBeforeVerifyOnInventory() of "Item Ledger Entry" table?

**Comment by MantasGurinas** [comment]
Hello @StanPesotskiy, after inspecting your suggestion, we agree to use Item Ledger Entry table, event OnbeforeVerifyOnInventory(), sorry for the late response.
