### ISSUE TITLE
CU6500 Make "GetLotSNDataSet" external

### ISSUE THREAD

**Issue by Bleika** [Microsoft/ALAppExtensions#863]
This function is used by the standard to access ItemLedgerEntries for a given Item Tracking Combination and in that way retrieve existing data. 
The standard uses this function to check for already defined Expiration/Warranty dates, but when adding fields to Item Tracking, this function should be reusable for Extension code.

**Comment by darjoo** [comment]
Hi @Bleika,
We have accepted your request and you'll see it in the next minor release.
