### ISSUE TITLE
[Event Request] Codeunit 11 "Gen. Jnl.-Check Line" - OnBeforeIsVendorPaymentToCrMemo

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8630]
Hi team,

In codeunit 11 "Gen. Jnl.-Check Line" function `IsVendorPaymentToCrMemo` we would like to add additional field check before checking GenJournalTemplate, for that a good solution would be an event before start of procedure code:
![image](https://user-images.githubusercontent.com/49302698/93082851-51715600-f69a-11ea-8d11-6cf99d6c22e8.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeIsVendorPaymentToCrMemo(GenJournalLine: Record "Gen. Journal Line"; var ReturnValue: Boolean; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
