### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnInsertItemLedgEntryCheckLocation

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8631]
Hi Team,

In codeunit 22 we need possibility to replace and avoid using standard code with our own. Having event with handling in the procedure `InsertItemLedgEntry`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93085603-78ca2200-f69e-11ea-853f-cba77ede488d.png)

    [IntegrationEvent(false, false)]
    local procedure OnInsertItemLedgEntryCheckLocation(Location: Record Location; ItemLedgEntry: Record "Item Ledger Entry"; var IsHandled: Boolean)

**Comment by StanPesotskiy** [comment]
Can't you use OnInsertItemLedgEntryOnBeforeReservationError? 
We better add the Location parameter, if needed there, than put another event on top of the existing one.

**Comment by MantasGurinas** [comment]
Hi @StanPesotskiy , 
Yes, you are correct, Location parameter would allow us to use OnInsertItemLedgEntryOnBeforeReservationError.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
