### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnAfterInsertPhysInventoryEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8632]
Hi Team,

In codeunit 22 we need possibility to replace and avoid using standard code with our own. Having event in the end of procedure `InsertPhysInventoryEntry`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93085799-cd6d9d00-f69e-11ea-9240-520b1b10565b.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertPhysInventoryEntry(var PhysInventoryLedgerEntry: Record "Phys. Inventory Ledger Entry"; ItemJournalLine: Record "Item Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
