### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnAfterGetAppliedFromValues

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8633]
Hi Team,

In codeunit 22 we need possibility to replace and avoid using standard code with our own. Having event in the end of procedure `GetAppliedFromValues`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93085886-f3933d00-f69e-11ea-9a98-458eab3213e1.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetAppliedFromValues(var ValueEntry: Record "Value Entry"; NegValueEntry: Record "Value Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
