### ISSUE TITLE
[Event Request] Codeunit 11 "Gen. Jnl.-Check Line" - OnRunCheckOnBeforeTestfieldAmount

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8634]
Hi team,

In codeunit 11 "Gen. Jnl.-Check Line" procedure RunCheck we would like to perform additional check before TestField(Amount), for that we would like to have a handler event:
![image](https://user-images.githubusercontent.com/49302698/93085286-09ecc900-f69e-11ea-9829-54d742e8e3d3.png)

```
[IntegrationEvent(false, false)]
local procedure OnRunCheckOnBeforeTestfieldAmount(GenJournalLine: Record "Gen. Journal Line"; IsRecurring: Boolean; IsBatchMode: Boolean; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
