### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnBeforeCheckItemTracking

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8635]
Hi Team,

In codeunit 22 we need possibility to replace and avoid using standard code with our own. Having event with handling in the beginning of procedure `CheckItemTracking`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93086579-022e2400-f6a0-11ea-8c4e-360253c28641.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckItemTracking(ItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
