### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnApplyItemLedgEntryOnBeforeFieldError

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8636]
Hi Team,

In codeunit 22 we need possibility to replace and avoid getting run-time error. Having event with handling in the  procedure `ApplyItemLedgEntry`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93087687-964cbb00-f6a1-11ea-89b3-d23cb3defaad.png)

    [IntegrationEvent(false, false)]
    local procedure OnApplyItemLedgEntryOnBeforeFieldError(var ItemLedgEntry: Record "Item Ledger Entry"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
