### ISSUE TITLE
[Event Request] CU 12 - "Gen. Jnl.-Post Line" - OnBeforeSetDeferralDetailDescription / OnPostDeferralOnBeforeInsertGLEntryDetailForGLAccount / OnPostDeferralOnBeforeInsertGLEntryDetailForDeferralAccount

### ISSUE THREAD

**Issue by wbor-nvt** [microsoft/ALAppExtensions#8637]
Hello,

CU 12 - "Gen. Jnl.-Post Line" - function PostDeferral

Currently, during the posting of deferrals: current events are already available:
![image](https://user-images.githubusercontent.com/53901977/93094353-18d57a80-f6a2-11ea-8a23-7b58e4001da3.png)
![image](https://user-images.githubusercontent.com/53901977/93093320-d65f6e00-f6a0-11ea-9d52-357806a41906.png)

However, these events are **not** available for the detail lines just below:
![image](https://user-images.githubusercontent.com/53901977/93094562-5934f880-f6a2-11ea-862f-4b6cad033818.png)

We would like to have the same events available here so we can do the same adjustments before posting.
New events:
`    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetDeferralDetailDescription(GenJournalLine: Record "Gen. Journal Line"; DeferralLine: Record "Deferral Line"; var DeferralDescription: Text[100]; var IsHandled: Boolean)
    begin
    end;`

`    [IntegrationEvent(false, false)]
    local procedure OnPostDeferralOnBeforeInsertGLEntryDetailForGLAccount(GenJournalLine: Record "Gen. Journal Line"; DeferralLine: Record "Deferral Line"; var GLEntry: Record "G/L Entry")
    begin
    end;`

`    [IntegrationEvent(false, false)]
    local procedure OnPostDeferralOnBeforeInsertGLEntryDetailForDeferralAccount(GenJournalLine: Record "Gen. Journal Line"; DeferralLine: Record "Deferral Line"; var GLEntry: Record "G/L Entry")
    begin
    end;`

Place in code:
![image](https://user-images.githubusercontent.com/53901977/93096138-4e7b6300-f6a4-11ea-9dce-785ca52e599f.png)

Adjusted function:
![image](https://user-images.githubusercontent.com/53901977/93095925-08260400-f6a4-11ea-9526-843856976e09.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
