### ISSUE TITLE
[Event Request]Application “Tests-User”, 134202 "Document Approval - Users"[Event Request]Application “Tests-User”, 134202 "Document Approval - Users"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8638]
Could you please insert the OnTestInitialize Event at the beginning the following test procedure:
-	ApproveRequestForPurchBlanketOrder
-	DelegateRequestForPurchBlanketOrder
-	DelegateRequestForPurchCrMemo
-	DelegateRequestForPurchInvoice
-	DelegateRequestForPurchOrder
-	DelegateRequestForPurchQuote
-	DelegateRequestForPurchReturnOrder
-	ModifyApprovedSalesQuote
-	ApproveRequestWithCommentForSalesQuoteAndMakeOrder

Could you please insert the OnTestInitialize Event at the beginning the following test procedure:
-	ApproveRequestForPurchBlanketOrder
-	DelegateRequestForPurchBlanketOrder
-	DelegateRequestForPurchCrMemo
-	DelegateRequestForPurchInvoice
-	DelegateRequestForPurchOrder
-	DelegateRequestForPurchQuote
-	DelegateRequestForPurchReturnOrder
-	ModifyApprovedSalesQuote
-	ApproveRequestWithCommentForSalesQuoteAndMakeOrder
![pic1](https://user-images.githubusercontent.com/45795262/93109286-2a278280-f6b4-11ea-8224-c09940421e6b.png)
![pic2](https://user-images.githubusercontent.com/45795262/93109295-2dbb0980-f6b4-11ea-9628-10c2cd050851.png)

**Comment by JoergPernberg** [comment]
Sorry, screenshots are wrong. Codeunit and procedures are correct.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
