### ISSUE TITLE
[New Event Request] - Page 7345 Pick Worksheet - OnAfterGetWarehouseDocumentsOnAction

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#8639]
is it possible to get an integration event at the end of the "Get Warehouse Documents" Action?

                    trigger OnAction()
                    var
                        RetrieveWhsePickDoc: Codeunit "Get Source Doc. Outbound";
                    begin
                        RetrieveWhsePickDoc.GetSingleWhsePickDoc(
                          CurrentWkshTemplateName, CurrentWkshName, CurrentLocationCode);
                        SortWhseWkshLines(
                          CurrentWkshTemplateName, CurrentWkshName, CurrentLocationCode, CurrentSortingMethod);

                        << --- NEW EVENT HERE --- >> 

                    end;

The client would like us to make some adjustments to the dataset in the Whse. Worksheet Line table after the Source Documents have been returned, but before presenting to the user. We looked for suitable events at the end of SortWhseWhshLines and could not find anything.

Thx.

**Comment by StanPesotskiy** [comment]
Please specify the full signature (list of required parameters) of the event.

**Comment by grantbrimhall** [comment]
I think something like this should work. thank you.

OnAfterGetWarehouseDocumentsOnAction(CurrentWkshTemplateName, CurrentWhshName, CurrentLocationCode, CurrentSortingMethod);

[IntegrationEvent(false, false)]
local procedure OnAfterGetWarehouseDocumentsOnAction(WhseWkshTemplate: Code[10]; WhseWkshName: Code[10]; LocationCode: Code[10]; SortingMethod: Option " ",Item,Document,"Shelf/Bin No.","Due Date","Ship-To")
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
