### ISSUE TITLE
[EventRequest] Table 5994 Service Cr.Memo Header - Function PrintRecords, OnBeforePrintRecords

### ISSUE THREAD

**Issue by rellorin** [microsoft/ALAppExtensions#8640]
In the PrintRecords function on the **Service Invoice Header table** Table 5992, we have available to us:

```
IsHandled := false;
OnBeforePrintRecords(Rec, ShowRequestPage, IsHandled);
if IsHandled then
    exit;
```

I'm requesting the same be added to the ServiceCrMemoHeader, Table 5994, in the PrintRecords function.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
