### ISSUE TITLE
[Event Request] Codeunit::"Unit of Measure Management" - Function CalcBaseQty - OnBeforeCalcBaseQtyForPurchaseLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8641]
We like to request the following Event:
Object: Codeunit::"Unit of Measure Management"
Function: CalcBaseQty
Publisher Event: OnBeforeCalcBaseQtyForPurchaseLine
Reason: To implement custom business logic
Where is the event placed:
procedure CalcBaseQty(var PurchaseLine: Record "Purchase Line"; Qty: Decimal) QtyRounded: Decimal
    begin
        OnBeforeCalcBaseQtyForPurchaseLine(PurchaseLine);
        QtyRounded := CalcBaseQty(PurchaseLine."No.", PurchaseLine."Variant Code", PurchaseLine."Unit of Measure Code", Qty, PurchaseLine."Qty. per Unit of Measure");
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCalcBaseQtyForPurchaseLine(var PurchaseLine: Record "Purchase Line")
    begin
    end;

**Comment by StanPesotskiy** [comment]
Codeunit::"Unit of Measure Management" does not have procedure with the parameter PurchaseLine. Please specify the code based on latest application version.
