### ISSUE TITLE
[Event Request] Codeunit::"Unit of Measure Management" - Function CalcBaseQty - OnBeforeCalcBaseQtyForSalesLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8642]
We like to request the following Event:
Object: Codeunit::"Unit of Measure Management"
Function: CalcBaseQty
Publisher Event: OnBeforeCalcBaseQtyForSalesLine
Reason: To implement custom business logic
Where is the event placed:
procedure CalcBaseQty(var SalesLine: Record "Sales Line"; Qty: Decimal) QtyRounded: Decimal
    begin
        OnBeforeCalcBaseQtyForSalesLine(SalesLine);
        QtyRounded := CalcBaseQty(SalesLine."No.", SalesLine."Variant Code", SalesLine."Unit of Measure Code", Qty, SalesLine."Qty. per Unit of Measure");
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCalcBaseQtyForSalesLine(var SalesLine: Record "Sales Line")
    begin
    end;

**Comment by StanPesotskiy** [comment]
Codeunit::"Unit of Measure Management" does not have procedure with the parameter SalesLine. Please specify the code based on latest application version.
