### ISSUE TITLE
[Event Request] Codeunit::"Update Prod. Order Cost" - Function UpdateUnitCostOnProdOrder - OnBeforeUpdateUnitCostOnProdOrder

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8643]
We like to request the following Event:
Object: Codeunit::"Update Prod. Order Cost"
Function: UpdateUnitCostOnProdOrder
Publisher Event: OnBeforeUpdateUnitCostOnProdOrder
Reason: To implement custom business logic
Where is the event placed:
procedure UpdateUnitCostOnProdOrder(var ProdOrderLine: Record "Prod. Order Line"; MultipleLevels: Boolean; UpdateReservation: Boolean)
    var
        Item: Record Item;
        ProdOrderComp: Record "Prod. Order Component";
        ReservEntry: Record "Reservation Entry";
        TotalCostQty: Decimal;
        TotalUnitCost: Decimal;
        UnitCost: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateUnitCostOnProdOrder(ProdOrderLine, MultipleLevels, UpdateReservation, Ishandled);
        if IsHandled then
            exit;
        if not Item.Get(ProdOrderLine."Item No.") then
            exit;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateUnitCostOnProdOrder(var ProdOrderLine: Record "Prod. Order Line"; MultipleLevels: Boolean; UpdateReservation: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
