### ISSUE TITLE
[Event Request] Codeunit::"VAT Rate Change Conversion" - Function OnRun - OnBeforeRun

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8644]
We like to request the following Event:
Object: Codeunit::"VAT Rate Change Conversion"
Function: OnRun
Publisher Event: OnBeforeRun
Reason: To implement custom business logic
Where is the event placed:
trigger OnRun()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeRun(IsHandled);
        If IsHandled then
            exit;
        if not VATRateChangeSetup.Get then begin
            VATRateChangeSetup.Init();
            VATRateChangeSetup.Insert();
        end;
        Convert;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeRun(var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
