### ISSUE TITLE
[Event Request] Codeunit::"Whse. Validate Source Line" - Function PurchaseLineVerifyChange - OnBeforePurchaseLineVerifyChange

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8645]
We like to request the following Event:
Object: Codeunit::"Whse. Validate Source Line"
Function: PurchaseLineVerifyChange
Publisher Event: OnBeforePurchaseLineVerifyChange
Reason: To implement custom business logic
Where is the event placed:
procedure PurchaseLineVerifyChange(var NewPurchLine: Record "Purchase Line"; var OldPurchLine: Record "Purchase Line")
    var
        NewRecRef: RecordRef;
        OldRecRef: RecordRef;
        OverReceiptMgt: Codeunit "Over-Receipt Mgt.";
        IsHandled: Boolean;
    begin
        OnBeforePurchaseLineVerifyChange(NewPurchLine, OldPurchLine, IsHandled);
        if IsHandled then
            exit;
        if not WhseLinesExist(
             DATABASE::"Purchase Line", NewPurchLine."Document Type", NewPurchLine."Document No.",
             NewPurchLine."Line No.", 0, NewPurchLine.Quantity)
        then
            exit;
Event Code:
[IntegrationEvent(false, false)]
    procedure OnBeforePurchaseLineVerifyChange(var NewPurchLine: Record "Purchase Line"; var OldPurchLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
