### ISSUE TITLE
[Event Request] Codeunit::"Whse. Validate Source Line" - Function SalesLineVerifyChange - OnBeforeSalesLineVerifyChange

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8646]
We like to request the following Event:
Object: Codeunit::"Whse. Validate Source Line"
Function: SalesLineVerifyChange
Publisher Event: OnBeforeSalesLineVerifyChange
Reason: To implement custom business logic
Where is the event placed:
procedure SalesLineVerifyChange(var NewSalesLine: Record "Sales Line"; var OldSalesLine: Record "Sales Line")
    var
        NewRecRef: RecordRef;
        OldRecRef: RecordRef;
        IsHandled: Boolean;
    begin
        OnBeforeSalesLineVerifyChange(NewSalesLine, OldSalesLine, IsHandled);
        if IsHandled then
            exit;
        if not WhseLinesExist(
             DATABASE::"Sales Line", NewSalesLine."Document Type", NewSalesLine."Document No.", NewSalesLine."Line No.", 0,
             NewSalesLine.Quantity)
        then
            exit;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineVerifyChange(var NewSalesLine: Record "Sales Line"; var OldSalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
