### ISSUE TITLE
[Event Request] Codeunit::"Whse. Validate Source Line" - Function TransLineVerifyChange - OnBeforeTransLineVerifyChange

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8647]
We like to request the following Event:
Object: Codeunit::"Whse. Validate Source Line"
Function: TransLineVerifyChange
Publisher Event: OnBeforeTransLineVerifyChange
Reason: To implement custom business logic
Where is the event placed:
procedure TransLineVerifyChange(var NewTransLine: Record "Transfer Line"; var OldTransLine: Record "Transfer Line")
    var
        IsHandled: Boolean;
    begin
        OnBeforeTransLineVerifyChange(NewTransLine, OldTransLine, IsHandled);
        if IsHandled then
            exit;
        with NewTransLine do begin
            if WhseLinesExist(DATABASE::"Transfer Line", 0, "Document No.", "Line No.", 0, Quantity) then begin
                TransLineCommonVerification(NewTransLine, OldTransLine);
                if "Qty. to Ship" <> OldTransLine."Qty. to Ship" then
                    FieldError("Qty. to Ship", StrSubstNo(Text000, TableCaptionValue, TableCaption));
            end;
Event Code:
[IntegrationEvent(false, false)]
    procedure OnBeforeTransLineVerifyChange(var NewTransLine: Record "Transfer Line"; var OldTransLine: Record "Transfer Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
