### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function CreatePostedRcptLine - OnBeforeCreatePostedRcptLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8648]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: CreatePostedRcptLine
Publisher Event: OnBeforeCreatePostedRcptLine
Reason: To implement custom business logic
Where is the event placed:
procedure CreatePostedRcptLine(var WhseRcptLine: Record "Warehouse Receipt Line"; var PostedWhseRcptHeader: Record "Posted Whse. Receipt Header"; var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var TempHandlingSpecification: Record "Tracking Specification")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreatePostedRcptLine(WhseRcptLine, PostedWhseRcptHeader, PostedWhseRcptLine, TempHandlingSpecification, IsHandled);
        if IsHandled then
            exit;
        UpdateWhseRcptLineBuf(WhseRcptLine);
        with PostedWhseRcptLine do begin
Event Code:
[IntegrationEvent(false, false)]
    procedure OnBeforeCreatePostedRcptLine(var WhseRcptLine: Record "Warehouse Receipt Line"; var PostedWhseRcptHeader: Record "Posted Whse. Receipt Header"; var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var TempHandlingSpecification: Record "Tracking Specification"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
