### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function GetFirstPutAwayDocument - OnBeforeGetFirstPutAwayDocument

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8649]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: GetFirstPutAwayDocument
Publisher Event: OnBeforeGetFirstPutAwayDocument
Reason: To implement custom business logic
Where is the event placed:
procedure GetFirstPutAwayDocument(var WhseActivHeader: Record "Warehouse Activity Header"): Boolean
    var
        IsHandled: Boolean;
        Success: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetFirstPutAwayDocument(WhseRcptHeader, WhseActivHeader, Success, IsHandled);
        if IsHandled then
            exit(Success);
        exit(CreatePutAway.GetFirstPutAwayDocument(WhseActivHeader));
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetFirstPutAwayDocument(var WhseReceiptHeader: Record "Warehouse Receipt Header"; var WhseActivHeader: Record "Warehouse Activity Header"; var Success: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
