### ISSUE TITLE
Event Request - Report 10748 "Vendor - Overdue Payments" - OnBeforeVendorLedgerEntryOnPreDataItem

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#8650]
We need a new Event Function in Report 10748 "Vendor - Overdue Payments" named OnBeforeVendorLedgerEntryOnPreDataItem.

This is what we need:

Vendor Ledger Entry - OnPreDataItem()
//INIT INSERT
OnAfterVendorLedgerEntryOnPreDataItem("Vendor Ledger Entry",Vendor,StartDate,EndDate,ShowPayments,Skip);
if Skip then
  CurrReport.SKIP;
//END INSERT

An this is the event:
[External] [BusinessEvent] OnAfterVendorLedgerEntryOnPreDataItem(VAR VendorLedgerEntry : Record "Vendor Ledger Entry";VAR Vendor : Record Vendor;VAR InitDate : Date;VAR EndDate : Date;VAR ShowPayments : Boolean;VAR Skip : Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
