### ISSUE TITLE
[Event Request] Codeunit 226 CustEntry-Apply Posted Entries - OnGetApplicationDateOnBeforeFilterApplyToCustLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8653]
Hi Team,

In codeunit 226 we need possibility to replace and avoid using standard code. Having event in the procedure `GetApplicationDate`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93205438-7cbe7880-f760-11ea-91dd-ea2debad63fa.png)

    [IntegrationEvent(false, false)]
    local procedure OnGetApplicationDateOnBeforeFilterApplyToCustLedgEntry(var ApplicationDate: Date)

**Comment by StanPesotskiy** [comment]
Please use the existing event OnBeforeGetApplicationDate().
