### ISSUE TITLE
[Additional Parameter Request] Codeunit 226 CustEntry-Apply Posted Entries - OnAfterPostUnapplyCustLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8655]
Hi Team,
In codeunit 226 we need possibility to have additional checks in the procedure `PostUnApplyCustomerCommit`. Standard publisher would suit us if it had additional standard parameter `CommitChanges` type `Boolean`. `OnAfterPostUnapplyCustLedgEntry` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93207566-d2e0eb00-f763-11ea-9da7-d1851bb74474.png)

[IntegrationEvent(false, false)]
local procedure OnAfterPostUnapplyCustLedgEntry(GenJournalLine: Record "Gen. Journal Line"; CustLedgerEntry: Record "Cust. Ledger Entry"; DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; **var CommitChanges: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
