### ISSUE TITLE
[Extensibility Request] Extend 'Option Lookup Buffer' to manage other types

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#8656]
We would like to adopt the standard 'Option Lookup Buffer' table/page/pattern to apply it to our own options / enums. The objects are currently not extensible enough to insert new options / enums, forcing us to duplicate the objects.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
