### ISSUE TITLE
[Event Request] Codeunit 311 Item-Check Avail. - OnBeforeSalesLineCheck

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8658]
Hi Team,

In codeunit 311 we need possibility to replace and avoid using standard code. Having event with handler in the procedure `SalesLineCheck`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93213693-e0e73980-f76c-11ea-9637-9c498f8a8100.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineCheck(SalesLine: Record "Sales Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
