### ISSUE TITLE
[Event Request] Codeunit 363 PostSales-Delete - OnBeforeInsertSalesShpHeaderInDeleteHeader

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8660]
Hi Team,

In codeunit 363 we need possibility to replace and avoid using standard code. Having event in the procedure `DeleteHeader`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93218097-82bd5500-f772-11ea-8746-dcd79845d4f9.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertSalesShpHeaderInDeleteHeader(var SalesShptHeader: Record "Sales Shipment Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
