### ISSUE TITLE
[Event Request] Codeunit 249 VAT Registration Log Mgt. - OnBeforeAssistEditCustomerVatRegPageRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8662]
Hi Team,

In codeunit 249 we need possibility to replace and avoid using standard code. Having event in the procedure `AssistEditCustomerVATReg`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93224435-c2d40600-f779-11ea-9ac8-82da6849326e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssistEditCustomerVatRegPageRun(var VATRegistrationLog: Record "VAT Registration Log"; VatRegNo: Text[20])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
