### ISSUE TITLE
[Event Request] Codeunit 249 VAT Registration Log Mgt. - OnBeforeAssistEditVendorVatRegPageRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8663]
Hi Team,

In codeunit 249 we need possibility to replace and avoid using standard code. Having event in the procedure `AssistEditVendorVATReg`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93224538-e1d29800-f779-11ea-8e4a-26259e19a2b0.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssistEditVendorVatRegPageRun(var VATRegistrationLog: Record "VAT Registration Log"; VatRegNo: Text[20])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
