### ISSUE TITLE
[Event Request] Codeunit 249 VAT Registration Log Mgt. - OnBeforeAssistEditContactVatRegPageRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8664]
Hi Team,

In codeunit 249 we need possibility to replace and avoid using standard code. Having event in the procedure `AssistEditContactVATReg`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93224631-fdd63980-f779-11ea-96d7-57888967aadd.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssistEditContactVatRegPageRun(var VATRegistrationLog: Record "VAT Registration Log"; VatRegNo: Text[20])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
