### ISSUE TITLE
[Event Request] Application “Tests-Workflow” Codeunit 134179 "WF Demo Purch. Inv. Approvals"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#8665]
[Event Request]Application “Tests-Workflow”, 134179 "WF Demo Purch. Inv. Approvals"

Could you please insert the OnTestInitialize Event at the beginning of Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/93225189-3d008c80-f772-11ea-9fc8-2e941f454a6f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
