### ISSUE TITLE
[Event Request] Codeunit 212 "Res. Jnl.-Post Line", OnAfterInsertResLedgerEntry

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#8666]
Good day, we are updating our customization on Jobs and we need to be able to get to the "Res. Ledger Entry" record after insert at the end of the local procedure "Code" to add values to our special fields that we have added to the record.

![image](https://user-images.githubusercontent.com/5692559/93204081-ff393f00-f744-11ea-9359-b9fc965e5847.png)

![image](https://user-images.githubusercontent.com/5692559/93204097-095b3d80-f745-11ea-976e-18e446e9dcfc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
