### ISSUE TITLE
[Event Request] Codeunit 1013 "Job Jnl.-Post Batch", OnBeforePostJobJnlBatch

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#8667]
Good day, we are updating our customization on Jobs and we need an new event to be able to add to "Job Journal Line" record before it is posted on the  local procedure "Code" . This is so we can continue to offer the option to bill a single job to more then one customer. 

![image](https://user-images.githubusercontent.com/5692559/93225395-b3e15980-f761-11ea-850f-d3dcfaf64c52.png)

![image](https://user-images.githubusercontent.com/5692559/93225439-bfcd1b80-f761-11ea-8a95-e4562df2c1a1.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
