### ISSUE TITLE
[Event Request] Codeunit 10320 Exp. Launcher EFT, procedure EFTPaymentProcess

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#8668]
Could we get an event just before line 57 (if BankExportImportSetup.FindFirst) so we choose a different BankExportImportSetup under certain conditions?

Parameters (TempEFTExportWorkset, var BankExportImportSetup)

We have a client that would like to use multiple Data Exchange Definitions on the same bank account. We would like BC to use a specific data exchange definition based on conditions in the TempEFTExportWorkset dataset. Only the first record in the TempEFTExportWorkset would be used to determine a new BankExportImportSetup (and therefore, all records in the TempEFTExportWorkset dataset would need to suggest the same Data Exchange Definition.)

Thx.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
