### ISSUE TITLE
[Event Request] Codeunit 99000830 OnUpdateItemTrackingAfterPostingOnBeforeReservEntryModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8669]
We Need a new Event OnUpdateItemTrackingAfterPostingOnBeforeReservEntryModify in codeunit 99000830:

[External] UpdateItemTrackingAfterPosting(VAR ReservEntry : Record "Reservation Entry")
IF NOT ReservEntry.FINDSET(TRUE) THEN
  EXIT;

REPEAT
  CurrSourceRefNo := ReservEntry."Source Ref. No.";

  REPEAT
    ReservEntry."Qty. to Handle (Base)" := ReservEntry."Quantity (Base)";
    ReservEntry."Qty. to Invoice (Base)" := ReservEntry."Quantity (Base)";
    //++++++++++++++++++++++++++++++++++++++
    OnUpdateItemTrackingAfterPostingOnBeforeReservEntryModify(VAR ReservEntry);
    //--------------------------------------
    ReservEntry.MODIFY;
    IF ReservEntry.NEXT = 0 THEN
      ReachedEndOfResvEntries := TRUE;
  UNTIL ReachedEndOfResvEntries OR (ReservEntry."Source Ref. No." <> CurrSourceRefNo);

  // iterate over each set of Source Ref No.
UNTIL ReservEntry."Source Ref. No." = CurrSourceRefNo;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
