### ISSUE TITLE
Codeunit 6620 CopySalesInvLinesToDoc

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#8670]
We need a new Event Function in Codeunit 6620 “Copy Document Mgt.”, named "OnCopySalesInvLinesToDocOnAfterCheckFirstLineShipped".

LOCAL [IntegrationEvent] OnCopySalesInvLinesToDocOnAfterCheckFirstLineShipped(ToSalesHeader : Record "Sales Header";OldDocType : Integer;ShptDocNo : Code[20];VAR OldShptDocNo : Code[20])

This event will be called from then function "CopySalesInvLinesToDoc":

      IF "Shipment No." <> OldInvDocNo THEN BEGIN
        OldInvDocNo := "Shipment No.";
        OldShptDocNo := '';
        FirstLineShipped := TRUE;
        InsertOldSalesDocNoLine(ToSalesHeader,OldInvDocNo,2,NextLineNo);
      END;
      CheckFirstLineShipped("Document No.","Shipment Line No.",SalesCombDocLineNo,NextLineNo,FirstLineShipped);

      // I-NEW CODE
      OnCopySalesInvLinesToDocOnAfterCheckFirstLineShipped(ToSalesHeader,2,"Document No.",OldShptDocNo);
      // F-END NEW CODE

      IF ("Document No." <> OldShptDocNo) AND ("Shipment Line No." > 0) THEN BEGIN
        IF FirstLineShipped THEN
          SalesCombDocLineNo := NextLineNo;
        OldShptDocNo := "Document No.";
        InsertOldSalesCombDocNoLine(ToSalesHeader,OldInvDocNo,OldShptDocNo,SalesCombDocLineNo,TRUE);
        NextLineNo := NextLineNo + 10000;
        FirstLineShipped := TRUE;
      END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
