### ISSUE TITLE
[BC17 preview] Email address validation 

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#8671]
In BC 17 (insider) preview, seems like mail addresses (EmailEdittor.page.al) are now validated via

```
trigger OnValidate()
                           var
                                EmailMessage: Codeunit "Email Message Impl.";
                            begin
                                EmailEdited := true;
                                EmailMessage.ValidateEmailAddress(ToRecipient)
                            end; 
```

Pre BC 17, we've been validating mail address using

```
trigger OnValidate()
            var
                MailManagement: Codeunit "Mail Management";
            begin
                if "E-Mail" = '' then
                    exit;
                MailManagement.CheckValidEmailAddresses("E-Mail");
            end;
```

In #5255 we've been asking for a OnAfterCheckValidEmailAddress publisher, to extend the current mail address check, something similar too ...

   ```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Mail Management", 'OnAfterCheckValidEmailAddress', '', false, false)]    
 local procedure CheckValidEmailAddress(Recipients: Text)
    var
        Regex: codeunit DotNet_Regex;
        RegexOptions: Codeunit DotNet_RegexOptions;
        InvalidEmailAddressErr: Label 'The email address "%1" is not valid.';
    begin
        RegexOptions.IgnoreCase();
        If not Regex.IsMatch(Recipients, '(?:[a-z0-9!#$%&''*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&''*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)', RegexOptions) then
            Error(InvalidEmailAddressErr, Recipients);
    end;
```

- [ ] Seems like the OnAfterCheckValidEmailAddress was never added, and now we've 2 places that test the validity of an email address, but we're still not able to improve the tests. Can you either still add the OnAfterCheckValidEmailAddress, or deprecate CheckValidEmailAddress and replace all reference with the new ValidateEmailAddress?

- [ ] ValidateEmailAddress is not accessible since it's part of the "Email Message Impl." codeunit. How can we make use of the new validation that uses the DotNet MailAddress?

- [ ] Can you add some more features to the new EmailMessage facade to also support **validation** of the Recipients / CC / BBC lists added?

**Comment by JesperSchulz** [comment]
Allow me to look into the solution. The code that you find in the insider previews is rather far from what we are going to release with 17.1. End of this week, we will update the code in the version 17 branch to be the code we expect to release. Based on that code, we will address your issue (which may or may not still be valid). Stay tuned! We'll get back to you with a solution.

**Comment by JesperSchulz** [comment]
And just like I added to your other issue, I'm happy to tell that we are going to open source the entire solution. We will happily accept any meaningful improvement you suggest - and again, those suggestions you mention sound meaningful indeed ;-)

**Comment by darjoo** [comment]
Hi @fvet, 
We have made a email validation function public in the Email Account facade linked below. Is this sufficient or are you looking for something more?
https://github.com/microsoft/ALAppExtensions/blob/2ce8069cae5e9ac3929998b57d6b2785a59e4572/Modules/System/Email/src/Account/EmailAccount.Codeunit.al#L63

**Comment by fvet** [comment]
@darjoo Looking at the function description, I think it's no validate candidate to replace the MailManagement.CheckValidEmailAddress**es**("E-Mail") we're currently using.

I know of scenarios where users are adding **multiple** mail addresses - separated by **';'** - in an 'E-mail' field. The CheckValidEmailAddresses splits the recipients on ';' as well. So I think we'd rather need an overloaded procedure in EmailAccount.Codeunit (instead of us having to create a wrapper around is):

procedure ValidateEmailAddress**es**(**Recipients**: Text; AllowEmptyValue: Boolean)

If that would be part of the System app, great, If not, we'll have to create our own.

**Comment by darjoo** [comment]
@fvet I'm in the process of adding this new function `ValidateEmailAddresses(EmailAddresses: Text; AllowEmptyValue: Boolean)` as well as the event mentioned #9616. 
The function `ValidateEmailAddress` overloads will be obsolete as the new function will work with as the replacement. This will unfortunately not get in for 17.1.

**Comment by darjoo** [comment]
Slight change after further discussion internally. `ValidateEmailAddress` overloads will not be obsolete and the event will be placed in it as `OnAfterValidateEmailAddress(EmailAddress:Text, AllowEmailValue: Boolean)`. `ValidateEmailAddresses` will split and use `ValidateEmailAddress` for validation of each email.

**Comment by fvet** [comment]
Make sense, thanks for the update.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.
