### ISSUE TITLE
[Event Request] Codeunit 5701 Item Subst. - OnItemSubstGet

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8673]
Hi Team,

In codeunit 5701 we need possibility to replace and avoid using standard code. Having event in the procedure `ItemSubstGet`, would be a perfect solution :
![image](https://user-images.githubusercontent.com/70525691/93341866-4bfd4280-f837-11ea-893c-d6b1d173faeb.png)

    [IntegrationEvent(false, false)]
    local procedure OnItemSubstGet(var ItemSubstitution: Record "Item Substitution")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
