### ISSUE TITLE
[Event Request] Codeunit 5701 Item Subst. - OnItemSubstGetAfterItemSubstitutionFind

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8674]
Hi Team,

In codeunit 5701 we need possibility to replace and avoid using standard code. Having event in the procedure `ItemSubstGet`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93342119-9ed6fa00-f837-11ea-82ae-49cb01239123.png)

    [IntegrationEvent(false, false)]
    local procedure OnItemSubstGetAfterItemSubstitutionFind(var TempItemSubstitution: Record "Item Substitution" temporary)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
