### ISSUE TITLE
[Parameter Request] Report 393 "Suggest Vendor Payments" - OnBeforeUpdateGnlJnlLineDimensionsFromTempBuffer() - SummarizePerVend

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#8675]
We are subscribing to `OnBeforeUpdateGnlJnlLineDimensionsFromTempBuffer()` as a sort of 'on before insert journal line', so that we can change how fields are set on the suggested payment journal lines - in this case, to get the old NAV behaviour of setting the `Description` to `Payment of DocType DocNo` when not in `SummarizePerVend` mode.

Currently, we can only 'guess' if we are in `SummarizePerVend` mode, by checking like so:

        SummarizePerVend := GenJournalLine."Applies-to ID" = TempPaymentBuffer."Document No.";

...since `Applies-to ID` is only set if `SummarizePerVend` is `true`, so they should correlate.

But it would seem far preferable to get passed `SummarizePerVend` to allow such branching

Thus, please update the available parameters to event subscribers, from:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateGnlJnlLineDimensionsFromTempBuffer(var GenJournalLine: Record "Gen. Journal Line"; TempPaymentBuffer: Record "Payment Buffer" temporary)
    begin
    end;

to

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateGnlJnlLineDimensionsFromTempBuffer(var GenJournalLine: Record "Gen. Journal Line"; TempPaymentBuffer: Record "Payment Buffer" temporary; SummarizePerVend: Boolean)
    begin
    end;

...or offer another event around here, which we could use to change the Description or other fields on the resulting payment journal lines.

Thanks!

**Comment by dtkb** [comment]
>>>
Currently, we can only 'guess' if we are in `SummarizePerVend` mode, by checking like so:

    SummarizePerVend := GenJournalLine."Applies-to ID" = TempPaymentBuffer."Document No.";
>>>

We also need to check whether the ID is blank. So it is actually quicker just to check

    SummarizePerVend := GenJournalLine."Applies-to ID" <> '';

Still, since the function raising the event has that option already known, it seems nicer to offer to pass it to subscribers, rather than making them 'reverse engineer' its value. :-)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
