### ISSUE TITLE
[Additional Parameter Request] Codeunit 5701 Item Subst. - OnItemSubstGetOnAfterSubstSalesLineItem

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8676]
Hi Team,
In codeunit 5701 we need possibility to have additional checks in the procedure `ItemSubstGet`. Standard publisher would suit us if it had additional standard parameters `SalesLine` type record and `TempItemSubstitution` type record. `OnItemSubstGetOnAfterSubstSalesLineItem` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93343057-b8c50c80-f838-11ea-9096-a4316f8de5da.png)

[IntegrationEvent(false, false)]
local procedure OnItemSubstGetOnAfterSubstSalesLineItem(var SalesLine: Record "Sales Line"; **var NewSalesLine: Record "Sales Line"; var TempItemSubstitution: Record "Item Substitution" temporary**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
