### ISSUE TITLE
[Event Request] Codeunit 5701 Item Subst. - OnAfterItemSubstGet

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8677]
Hi Team,

In codeunit 5701 we need possibility to replace and avoid using standard code. Having event in the procedure `ItemSubstGet`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93343398-1ce7d080-f839-11ea-82ac-6c0f017ba994.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterItemSubstGet(var SalesLine: record "Sales Line"; TempSalesLine: record "Sales Line" temporary)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
