### ISSUE TITLE
[Additional Parameter Request] Codeunit 5701 Item Subst. - OnCalcCustPriceOnBeforeCalcQtyAvail

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8679]
Hi Team,
In codeunit 5701 we need possibility to have additional checks in the procedure `CalcCustPrice`. Standard publisher would suit us if it had additional standard parameter ItemSubstitution type record. OnCalcCustPriceOnBeforeCalcQtyAvail would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93347469-ca5ce300-f83d-11ea-87f6-88a720ddf506.png)

[IntegrationEvent(false, false)]
local procedure OnCalcCustPriceOnBeforeCalcQtyAvail(var Item: Record Item; SalesLine: Record "Sales Line"; var TempItemSubstitution: Record "Item Substitution" temporary; **ItemSubstitution: Record "Item Substitution"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
