### ISSUE TITLE
[Event Request] Codeunit 5704 TransferOrder-Post Shipment - OnBeforeFinalizePosting

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8680]
Hi Team,

In codeunit 5704 we need possibility to replace and avoid using standard code. Having event in the procedure `OnRun`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93348746-4b68aa00-f83f-11ea-8943-639e8424f4df.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFinalizePosting(TransferHeader: Record "Transfer Header"; PostedWhseShptHeader: Record "Posted Whse. Shipment Header"; WhseShip: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
