### ISSUE TITLE
codeunit 7322 "Create Inventory Pick/Movement" function "CreateInvtMvntWithoutSource"

### ISSUE THREAD

**Issue by lucaeos** [microsoft/ALAppExtensions#8681]
We would like to have the starting Confirm request conditioned by the global variable "HideDialog".

```
 procedure CreateInvtMvntWithoutSource(var InternalMovementHeader: Record "Internal Movement Header")
    var
        InternalMovementLine: Record "Internal Movement Line";
        NewWhseActivLine: Record "Warehouse Activity Line";
        RemQtyToPickBase: Decimal;
    begin
// Added code --- Message only if Hidedialog = false
        if not HideDialog then 
// End Added Code
            if not Confirm(Text004, false) then
                exit;

        IsInvtMovement := true;
        IsBlankInvtMovement := true;
```

**Comment by AlexanderYakunin** [comment]
Please look into latest code base, this is already done

    procedure CreateInvtMvntWithoutSource(var InternalMovementHeader: Record "Internal Movement Header")
    var
        InternalMovementLine: Record "Internal Movement Line";
        NewWhseActivLine: Record "Warehouse Activity Line";
        RemQtyToPickBase: Decimal;
    begin
        if not HideDialog then
            if not Confirm(Text004, false) then
                exit;
