### ISSUE TITLE
[Event Request] Table 5740 TransferHeader - OnBeforeCheckTransferFromAndToCodesNotTheSameTransferFromCode / OnBeforeCheckTransferFromAndToCodesNotTheSameTransferToCode

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#8682]
Could you please add new integration events "OnBeforeCheckTransferFromAndToCodesNotTheSameTransferFromCode" and "OnBeforeCheckTransferFromAndToCodesNotTheSameTransferToCode" for the Transfer Header table (5740).  Also it looks like the publisher was created for #3925, but the actual code on the field was never created.  

        field(2; "Transfer-from Code"; Code[10])
        {
            Caption = 'Transfer-from Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            var
                Location: Record Location;
                Confirmed: Boolean;
                IsHandled: Boolean;
            begin
                TestStatusOpen;

                IsHandled := false;
                OnBeforeValidateTransferFromCode(Rec, xRec, IsHandled);
                if IsHandled then
                    exit;

                // >> NEW
                IsHandled := false;
                OnBeforeCheckTransferFromAndToCodesNotTheSameTransferFromCode(Rec, xRec, IsHandled);
                if not IsHandled then
                // << NEW
                    if ("Transfer-from Code" = "Transfer-to Code") and ("Transfer-from Code" <> '') then
                        Error(
                        Text001,
                        FieldCaption("Transfer-from Code"), FieldCaption("Transfer-to Code"),
                        TableCaption, "No.");

        field(11; "Transfer-to Code"; Code[10])
        {
            Caption = 'Transfer-to Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            var
                Location: Record Location;
                Confirmed: Boolean;
                IsHandled: Boolean;   // NEW
            begin
                TestStatusOpen;

                // >> NEW
                IsHandled := false;
                OnBeforeCheckTransferFromAndToCodesNotTheSameTransferToCode(Rec, xRec, IsHandled);
                if not IsHandled then
                // << NEW
                    if ("Transfer-from Code" = "Transfer-to Code") and
                    ("Transfer-to Code" <> '')
                    then
                        Error(
                        Text001,
                        FieldCaption("Transfer-from Code"), FieldCaption("Transfer-to Code"),
                        TableCaption, "No.");

    // >> NEW
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckTransferFromAndToCodesNotTheSameTransferFromCode(var TransferHeader: Record "Transfer Header"; var xTransferHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckTransferFromAndToCodesNotTheSameTransferToCode(var TransferHeader: Record "Transfer Header"; var xTransferHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;
    // << NEW

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
