### ISSUE TITLE
[Event Request] Report 190 "Issue Reminders"

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#8683]
Hi,

we need a new Event in the Issue Reminders Report :)

Trigger: Reminder Header - OnAfterGetRecord
Publisher: OnBeforeInsertTempIssuedReminderHeaderPrint
![grafik](https://user-images.githubusercontent.com/40355993/93430225-a0013900-f8c2-11ea-8054-92b63a6f36b2.png)

New Publisher:
![grafik](https://user-images.githubusercontent.com/40355993/93430339-d474f500-f8c2-11ea-8f7b-f05444e9f600.png)

`    [IntegrationEvent(false, false)]`
`    local procedure OnBeforeInsertTempIssuedReminderHeaderPrint(var TempIssuedReminderHeader: Record "Issued Reminder Header" temporary)`
`    begin`
`    end;`

Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
