### ISSUE TITLE
[Event Request] Codeunit 5751 Get Source Doc. Inbound - OnShowDialogOnBeforeOpenWarehouseReceiptPage

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8689]
Hi Team,

In codeunit 5751 we need possibility to replace and avoid using standard code. Having event with handling in procedure `ShowDialog`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93457557-ceddd600-f8e7-11ea-9b5a-81468a8798b8.png)

    [IntegrationEvent(false, false)]
    local procedure OnShowDialogOnBeforeOpenWarehouseReceiptPage(var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
