### ISSUE TITLE
[Event Request] Codeunit 5751 Get Source Doc. Inbound - OnCreateWhseReceiptHeaderFromWhseRequest

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8690]
Hi Team,

In codeunit 5751 we need possibility to replace and avoid using standard code. Having event with handling in procedure `CreateWhseReceiptHeaderFromWhseRequest`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93457648-efa62b80-f8e7-11ea-844f-e09def74fc59.png)

    [IntegrationEvent(false, false)]
    local procedure OnCreateWhseReceiptHeaderFromWhseRequest(WarehouseRequest: Record "Warehouse Request"; var GetSourceDocuments: Report "Get Source Documents"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
