### ISSUE TITLE
[Event Request] Codeunit 5760 Whse.-Post Receipt - OnInitSourceDocumentHeaderOnBeforeReopenPurchaseHeader

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8691]
Hi Team,

In codeunit 5760 we need possibility to replace and avoid using standard code. Having event in procedure `InitSourceDocumentHeader`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93459169-fd5cb080-f8e9-11ea-92ce-dc43da0d2f3b.png)

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnBeforeReopenPurchaseHeader(var WhseRcptLine: Record "Warehouse Receipt Line"; var PurchHeader: Record "Purchase Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
