### ISSUE TITLE
[Additional Parameter Request] Codeunit 5760 Whse.-Post Receipt - OnInitSourceDocumentLinesOnAfterSourcePurchLineFound

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8693]
Hi Team,
In codeunit 5760 we need possibility to have additional checks in the procedure `InitSourceDocumentLines`. Standard publisher would suit us if it had additional standard parameter `WhseRcptHeader` of type record and parameter `ModifyLine` set to pass by reference. `OnInitSourceDocumentLinesOnAfterSourcePurchLineFound` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93466989-c5f40100-f8f5-11ea-8d71-ee4c3fea5975.png)

[IntegrationEvent(false, false)]
local procedure OnInitSourceDocumentLinesOnAfterSourcePurchLineFound(var PurchaseLine: Record "Purchase Line"; WhseRcptLine: Record "Warehouse Receipt Line"; **WhseRcptHeader: Record "Warehouse Receipt Header"**;**var ModifyLine: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
