### ISSUE TITLE
[Additional Parameter Request] Codeunit 5760 Whse.-Post Receipt - OnInitSourceDocumentLinesOnAfterSourceSalesLineFound

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8694]
Hi Team,
In codeunit 5760 we need possibility to have additional checks in the procedure `InitSourceDocumentLines`. Standard publisher would suit us if it had additional standard parameter `WhseRcptHeader` of type record and parameter `WhseRcptLine` type record. `OnInitSourceDocumentLinesOnAfterSourceSalesLineFound` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93477860-2e49df00-f904-11ea-807b-4382f3953ffd.png)

[IntegrationEvent(false, false)]
local procedure OnInitSourceDocumentLinesOnAfterSourceSalesLineFound(var SalesLine: Record "Sales Line"; WhseRcptLine: Record "Warehouse Receipt Line"; **WhseRcptHeader: Record "Warehouse Receipt Header"; OldWhseRcptLine: Record "Warehouse Receipt Line"**; ModifyLine: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
