### ISSUE TITLE
[Additional Parameter Request] Codeunit 5760 Whse.-Post Receipt - OnBeforeTransLineModify

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8695]
Hi Team,
In codeunit 5760 we need possibility to have additional checks in the procedure `InitSourceDocumentLines`. Standard publisher would suit us if it had additional standard parameter `WhseRcptHeader` type record. `OnBeforeTransLineModify` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93479576-25a5d880-f905-11ea-8e56-b82cff803328.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeTransLineModify(var TransferLine: Record "Transfer Line"; WhseRcptLine: Record "Warehouse Receipt Line"; var ModifyLine: Boolean; **WhseRcptHeader: Record "Warehouse Receipt Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
