### ISSUE TITLE
[Additional Parameter Request] Codeunit 5765 Whse.-Post Shipment + Print - OnBeforeCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8696]
Hi Team,

In codeunit 5765 we need possibility to replace and avoid using standard code. Standard publisher would suit us if it had additional standard parameter `Selection` of type Integer set to pass by reference and parameter IsHandled of type boolean set to pass by reference :

![image](https://user-images.githubusercontent.com/70525691/93482746-b7631500-f908-11ea-9e64-c58053af2d24.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeCode(var WhseShptLine: Record "Warehouse Shipment Line"; var HideDialog: Boolean; var Invoice: Boolean; var IsPosted: Boolean; **var Selection: Integer**; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
