### ISSUE TITLE
Codeunit 311 - SetFilterOnItem - IsHandled

### ISSUE THREAD

**Issue by Arthurvdv** [microsoft/ALAppExtensions#8698]
![image](https://user-images.githubusercontent.com/44637996/93493477-3ad23580-f90c-11ea-8501-9d2a185fa853.png)

In the codeunit 311 "Item-Check Avail." on the event OnBeforeSetFilterOnItem I can set the IsHandled-flag, but the code is always executed.

I think there's a line of code missing?

```
if IsHandled then
   exit;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
