### ISSUE TITLE
[Code change] Remove line in Codeunit 212 "Res. Jnl.-Post Line"

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#8699]
Hi App Team,
Our vertical solution allows for recording time on other dates than the current workdate. A part of that is to handle changes in resource groups over time. So we have a resource group history table, that keeps track of historic resource groups on resources. We also have made sure that the job journal line gets the correct resource group, based on the history table. But when the job journal gets posted, the resource journal is automatically created and posted.

In codeunit 212, procedure Code, there is a single line where the "Resource Group No." is reset to the value from the resource, no matter what was in the journal. This is the only field that is recalculated, and we can't really see why this needs to be recalculated - since it is normally filled by validating the resource no. on the journal line.

So we suggest removing this line in "Res. Jnl.-Post Line".Code:
...
Res.Get("Resource No.");
Res.CheckResourcePrivacyBlocked(true);

IsHandled := false;
OnBeforeCheckResourceBlocked(Res, IsHandled);
if not IsHandled then
        Res.TestField(Blocked, false);

IsHandled := false;
OnBeforeGenPostingSetupGet(ResJnlLine, IsHandled);

"Resource Group No." := Res."Resource Group No.";  //DELETE THIS LINE

ResLedgEntry.Init();
ResLedgEntry.CopyFromResJnlLine(ResJnlLine);

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
