### ISSUE TITLE
Swapped parameters in the integration event OnCalcAvailQtyOnFindPickBin

### ISSUE THREAD

**Issue by dejfidson** [microsoft/ALAppExtensions#8700]
We encountered a bug in codeunit 7312 "Create Pick" in the integration event OnCalcAvailQtyOnFindPickBin. The parameters "Serial No." and "Lot No." are swapped here. When connected to an integration event with our own app, the event returns the value "Lot No." in the provided variable SerialNo and the value "Serial No." in the provided variable LotNo. They are swapped. Please could you resolve the issue? 
We encountered to this issue in 16.3 version.
It seems that the issue is related to: [[Event Request] Codeunit 7312 - OnCalcAvailQtyOnFindBWPickBin, OnCalcAvailQtyOnFindPickBin, OnCalcAvailQtyOnFindBreakBulkBin, OnCalcAvailQtyOnFindSmallerUOMBin ](https://github.com/microsoft/AL/issues/3499)
Thank you in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
