### ISSUE TITLE
Method 'ShowItemSub' obsolete

### ISSUE THREAD

**Issue by apoyas** [microsoft/ALAppExtensions#8702]
Hello Team!

BC16
There is function 'ShowItemSub' in table 37 "Sales Line".
Unfortunately it is marked as obsolete.
```AL
[Obsolete('Function scope will be changed to OnPrem', '15.1')]
procedure ShowItemSub()
```

Please advise what should be used as a replacement method for the function? When it is scheduled to be available?

Thanks!

**Comment by StanPesotskiy** [comment]
The method will not be removed, it will be OnPrem again in the next major version - 18.0 April 2021.
