### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnInsertVATOnAfterInitVATEntry

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8704]
Hi team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure InsertVAT we would like to assign additional fields to VATEntry before further code, for that an event after initing new line would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/93196327-ee8fc580-f752-11ea-8da8-63b29d71e076.png)

```
[IntegrationEvent(false, false)]
local procedure OnInsertVATOnAfterInitVATEntry(GenJnlLine: Record "Gen. Journal Line"; var VATEntry: Record "VAT Entry"; CurrExchRate: Record "Currency Exchange Rate")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
