### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnPostCustOnAfterCalcPmtTolerance

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8705]
Hi team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure  `PostCust` we would like to assign some custom fields to GenJnlLine before further code is run, for that an event publisher after checking Cust."Block Payment Tolerance" would be a good solution
![image](https://user-images.githubusercontent.com/49302698/93738316-292fad00-fbee-11ea-86e5-ebba12debebd.png)

```
[IntegrationEvent(false, false)]
local procedure OnPostCustOnAfterCalcPmtTolerance(var GenJnlLine: Record "Gen. Journal Line"; var CustLedgEntry: Record "Cust. Ledger Entry"; var Cust: Record Customer; GLReg: Record "G/L Register")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
