### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnPostCustOnAfterInsertTempDtldCVLedgEntryBuf

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8706]
HI team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure `PostCust` we would like to assign some additional fields to TempDtldCVLedgEntryBuf before further code is ran, for that an event publisher after creating new TempDtldCVLedgEntryBuf would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/93738649-fafe9d00-fbee-11ea-81c7-c66b4f31b698.png)

```
[IntegrationEvent(false, false)]
local procedure OnPostCustOnAfterInsertTempDtldCVLedgEntryBuf(var TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJnlLine: Record "Gen. Journal Line"; Customer: Record Customer)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
