### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnFinishPostingOnBeforeCheckIsTransactionConsistent

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8707]
Hi team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure `FinishPosting` we would like to modify how GLReg is handled, for that a good solution would be to add a handler before checking IsTransactionConsistent boolean:
![image](https://user-images.githubusercontent.com/49302698/93739002-e969c500-fbef-11ea-849c-a21ebf0de28f.png)

```
[IntegrationEvent(false, false)]
local procedure OnFinishPostingOnBeforeCheckIsTransactionConsistent(IsTransactionConsistent: Boolean; IsGLRegInserted: Boolean; var GLReg: Record "G/L Register"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
