### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnInitGLEntryVATOnBeforeSummarizeVAT

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8708]
Hi team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure procedure `InitGLEntryVAT` we would like to add a condition to check before running the `SummarizeVAT` procedure, for that a handler event would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/93739777-c213f780-fbf1-11ea-9a54-65b19f9bb708.png)

```
[IntegrationEvent(false, false)]
local procedure OnInitGLEntryVATOnBeforeSummarizeVAT(var GLEntry: Record "G/L Entry"; Amount: Decimal; var IsHandled: Boolean);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
