### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnCalcPmtDiscIfAdjVATOnBeforeInsertPmtDiscVATForGLEntry

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8710]
Hi team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure `CalcPmtDiscIfAdjVAT` we would like to assign additional fields to VATEntry before further code is ran for that we would like to have an event before `InsertPmtDiscVATForGLEntry` procedure is ran
![image](https://user-images.githubusercontent.com/49302698/93740464-34390c00-fbf3-11ea-9143-f2b27dc089b3.png)
```
[IntegrationEvent(false, false)]
local procedure OnCalcPmtDiscIfAdjVATOnBeforeInsertPmtDiscVATForGLEntry(var VATEntry: Record "VAT Entry"; VATEntry2: Record "VAT Entry"; DtldCVLedgEntryBuf2: Record "Detailed CV Ledg. Entry Buffer");
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
