### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnApplyCustLedgEntryOnBeforeDeleteTempOldCustLedgEntry

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8711]
Hi team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure `ApplyCustLedgEntry` we would like to run some code using the `TempOldCustLedgEntry` record before it gets deleted, for that an event publisher before `TempOldCustLedgEntry.Delete()` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/93752394-458c1380-fc07-11ea-8d62-87617ed2420b.png)
```
[IntegrationEvent(false, false)]
local procedure OnApplyCustLedgEntryOnBeforeDeleteTempOldCustLedgEntry(var GenJnlLine: Record "Gen. Journal Line"; var TempOldCustLedgEntry: Record "Cust. Ledger Entry" temporary; var Cust: Record Customer; CustLedgNo: Integer; GLReg: Record "G/L Register"; Amount: Decimal)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
