### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnPrepareTempCustLedgEntryOnAfterCheckCustApplicationMethod

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8712]
Hi team,

In codeunit 12 "Gen. Jnl.-Post Line" procedure `PrepareTempCustLedgEntry` we would like to add some additional filters on variable `OldCustLedgEntry`, for that an event before `OldCustLedgEntry.FindSet()` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/93760081-0912e480-fc14-11ea-894e-d289bd4df404.png)
```
[IntegrationEvent(false, false)]
local procedure OnPrepareTempCustLedgEntryOnAfterCheckCustApplicationMethod(var OldCustLedgEntry: Record "Cust. Ledger Entry"; Customer: Record Customer; GenJnlLine: Record "Gen. Journal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
