### ISSUE TITLE
[Event Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnUpdateAndDeleteLinesOnBeforeIncrementBatchName

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8713]
Hi team,

In Codeunit 13 "Gen. Jnl.-Post Batch" procedure `UpdateAndDeleteLines` we would like to we would like to perform additional checks before checking "Increment Batch Name" of GenJnlTemplate, for that a handler before checking the field would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/93762831-f2bb5780-fc18-11ea-8b41-f09d9ced2314.png)
```
[IntegrationEvent(false, false)]
local procedure OnUpdateAndDeleteLinesOnBeforeIncrementBatchName(var GenJnlBatch: Record "Gen. Journal Batch"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
