### ISSUE TITLE
[Event Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnUpdateAndDeleteLinesOnBeforeSetUpNewLine

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8714]
Hi team,

In Codeunit 13 "Gen. Jnl.-Post Batch" procedure `OnUpdateAndDeleteLines` we would like to we would like to perform additional checks before inserting new Gen. Journal Line, for that a handler before checking the field would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/93763002-4f1e7700-fc19-11ea-9118-8e984bdad54c.png)
```
[IntegrationEvent(false, false)]
local procedure OnUpdateAndDeleteLinesOnBeforeSetUpNewLine(var GenJnlBatch: Record "Gen. Journal Batch"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
