### ISSUE TITLE
[Additional Parameter Request] Codeunit 5772 Whse.-Purch Release - OnBeforeReopen

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8716]
Hi Team,
In codeunit 5772 we need possibility to have additional checks in the procedure `Reopen`. Standard publisher would suit us if it had additional standard parameter `WhseRqst: Record "Warehouse Request"` and IsHandled variable. `OnBeforeReopen` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93777522-90b91d00-fc2d-11ea-9251-81239e411f12.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeReopen(var PurchaseHeader: Record "Purchase Header"; **var WhseRqst: Record "Warehouse Request"; var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
