### ISSUE TITLE
[Event Request] Codeunit 5802 Inventory Posting To G/L - OnAfterPostInvtBuffUpdateGlobalDimFromDimSetID

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8717]
Hi Team,

In codeunit 5802 we need possibility to replace and avoid using standard code. Having event in procedure `PostInvtPostBuf`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93784556-d5e14d00-fc35-11ea-8f33-651501ea9d5a.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostInvtBuffUpdateGlobalDimFromDimSetID(var GenJnlLine: Record "Gen. Journal Line")

**Comment by StanPesotskiy** [comment]
Can't you use the existing events: OnPostInvtPostBufOnBeforeSetAmt, OnBeforePostInvtPostBuf, OnBeforeCheckInvtPostBuf?

**Comment by MantasGurinas** [comment]
Hi @StanPesotskiy , after OnPostInvtPostBufOnBeforeSetAmt publisher, GenJnlLine dimension set ID is overwritten from record GlobalInvtPostBuf, so this event does not suit us, unless it would have IsHandled param with extra params needed to execute whole block.

OnBeforePostInvtPostBuf and OnBeforeCheckInvtPostBuf events are within two booleans CalledFromTestReport and RunOnlyCheck, in bad scenario, code might be not executed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
