### ISSUE TITLE
[Event Request] Codeunit 5810 Change Average Cost Setting - OnProcessItemAvgCostPoint

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8718]
Hi Team,

In codeunit 5810 we need possibility to replace and avoid using standard code. Having event in procedure `ProcessItemAvgCostPoint`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93785661-037ac600-fc37-11ea-902a-877d3a45e7cc.png)

    [IntegrationEvent(false, false)]
    local procedure OnProcessItemAvgCostPoint(var ValueEntry: record "Value Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
