### ISSUE TITLE
[Event Request] Codeunit 5875 Phys. Invt. Rec.-Finish (Y/N) - OnBeforeOnRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8719]
Hi Team,

In codeunit 5875 we need possibility to replace and avoid using standard code. Having event with handling in procedure `OnRun`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93788295-738a4b80-fc39-11ea-8b04-7383dad020fd.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun(var PhysInvtRecordHeader: Record "Phys. Invt. Record Header"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
