### ISSUE TITLE
[Event Request] Codeunit 6620 OnAfterInitShipmentDateInLine(SalesHeader,SalesLine);

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8720]
We Need a new Event trigger OnAfterInitShipmentDateInLine(SalesHeader,SalesLine) similar to OnBeforeSetShipmentDateInLine(SalesHeader,SalesLine);

LOCAL InitShipmentDateInLine(SalesHeader : Record "Sales Header";VAR SalesLine : Record "Sales Line")
IF SalesHeader."Shipment Date" <> 0D THEN
  SalesLine."Shipment Date" := SalesHeader."Shipment Date"
ELSE
  SalesLine."Shipment Date" := WORKDATE;
//+++++++++++++++++++++++++++
OnAfterInitShipmentDateInLine(SalesHeader,VAR SalesLine);
//----------------------------------------------

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
