### ISSUE TITLE
[Event Request] Codeunit 6620 OnAfterSetDefaultValuesToPurchLine and OnAfterSetDefaultValuesToSalesLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8723]
We Need additional Parameter in the existing Events OnAfterSetDefaultValuesToPurchLine and OnAfterSetDefaultValuesToSalesLine

old:
local procedure OnAfterSetDefaultValuesToPurchLine(var ToPurchaseLine: Record "Purchase Line")
new:
local procedure OnAfterSetDefaultValuesToPurchLine(var ToPurchaseLine: Record "Purchase Line";ToPurchaseHeader: Record "Purchase Header";CreateToHeader : Boolean)

old:
local procedure OnAfterSetDefaultValuesToSalesLine(var ToSalesLine: Record "Sales Line"; ToSalesHeader: Record "Sales Header")
New:
local procedure OnAfterSetDefaultValuesToSalesLine(var ToSalesLine: Record "Sales Line"; ToSalesHeader: Record "Sales Header";CreateToHeader: Boolen;RecalculateLines: Boolean);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
