### ISSUE TITLE
[Event Request] Codeunit 99000830 OnAfterSetQtyToHandleAndInvoice

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#8724]
We Need a new Event OnAfterSetQtyToHandleAndInvoice in codeunit 99000830:

[External] SetQtyToHandleAndInvoice(QtyToHandleBase : Decimal;QtyToInvoiceBase : Decimal)
InsertReservEntry."Qty. to Handle (Base)" := QtyToHandleBase;
InsertReservEntry."Qty. to Invoice (Base)" := QtyToInvoiceBase;
//++++++++++++++++++++++++++++++
OnAfterSetQtyToHandleAndInvoice(VAR InsertReservEntry); 
//------------------------------
QtyToHandleAndInvoiceIsSet := TRUE;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
