### ISSUE TITLE
Unnecessary confirmation in (sales) "Post and send..." due to setting in CH-localization (onPrem)

### ISSUE THREAD

**Issue by CptBlaubart** [microsoft/ALAppExtensions#8725]
Found in BC16.1-CH but verified on BC 16.5-CH:
The Sales setup in the CH-Localization offers a boolean called "Shipment on Ship and Invoice" which had the purpose to also print the Shipment Reports in case someone posted a Sales Order with the "Ship and Invoice" option. - Even though confusingly translated, this worked fine in older NAV solutions.

Now, since "Post and print..." is getting replaced with "Post and send...", there is a confirm dialog in the function "SendPostedDocumentRecord" for DocType::"Order" which is kind of redundant to CH-setting. (And the confirmation is annoying our customers.)

There is an Event available in 16.5 to build you own workaround. But it still think it would be better to have it changed in the base code, as you'd need to create an unnecessairy amount of redundant code in your extensions which then has to get kept up to date with every new iteration of the Base App.

**Comment by CptBlaubart** [comment]
note: further debugging made me realize that the core issue, that made me find this difference, isnt the cause of the behaviour our customer is complaining about. - idk if you'd like to look into it. - I didn't check what code is processed behind reportselections. I just noticed the difference by accident and can't say for sure if the behaviour is actually different. - sorry.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
