### ISSUE TITLE
[Event Request] Table 472 "Job Queue Entry" - OnBeforeModifyLogEntry

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8726]
In Table 472 "Job Queue Entry", we used to skip the part of the procedure ScheduleTask where Guid is checked with the IsNullGuid method on NAV 2018. Now we are migrating to BC 16.4, we would like to be able to skip this verification too. Is it possible to add a IsHandled boolean in the procedure ScheduleTask in order to disable this verification please ?

The procedure would look like that after adding a IsHandled boolean :
![image](https://user-images.githubusercontent.com/34645582/93870064-f90b0b80-fccc-11ea-98ec-2da0731aba73.png)

And the integration event sending the IsHandled parameter would look like that.
![image](https://user-images.githubusercontent.com/34645582/93870233-2c4d9a80-fccd-11ea-892f-177100bcc69b.png)

Do you think it could be possible ?

Thanks for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
