### ISSUE TITLE
[Additional Parameter Request] Codeunit 5813 Undo Purchase Receipt Line - OnAfterInsertNewReceiptLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8727]
Hi Team,
In codeunit 5813 we need possibility to have additional checks in the procedure `Code`. Standard publisher would suit us if it had parameter `PostedWhseRcptLine` set as pass by reference. `OnAfterInsertNewReceiptLine` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93871260-07f6bb80-fcd7-11ea-8b53-ca178ad2e5dd.png)

[IntegrationEvent(false, false)]
local procedure OnAfterInsertNewReceiptLine(var PurchRcptLine: Record "Purch. Rcpt. Line"; **var PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"**; var PostedWhseRcptLineFound: Boolean; DocLineNo: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
