### ISSUE TITLE
[Event Request] Codeunit 5817 Undo Posting Management - OnAfterTestWarehouseActivityLine2

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8728]
Hi Team,

In codeunit 5817 we need possibility to replace and avoid using standard code. Having event with handling in procedure `TestWarehouseActivityLine2`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93871454-5ad07300-fcd7-11ea-95f9-c5d8de145bb8.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterTestWarehouseActivityLine2(var WarehouseActivityLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
