### ISSUE TITLE
[Event Request] Codeunit 5878 Phys. Invt. Rec.-Reopen - OnBeforeCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8729]
Hi Team,

In codeunit 5878 we need possibility to replace and avoid using standard code. Having event in procedure `Code`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93872096-52c50300-fcd8-11ea-8260-6c7fb3c50eb4.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCode(PhysInvtRecordHeader: Record "Phys. Invt. Record Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
