### ISSUE TITLE
[Event Request] Report 94 Close income Statement - OnBeforeGenJnlPost

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#8730]
We need a new event in Report 94 "Close income Statement":

**LOCAL [IntegrationEvent] OnBeforeGenJnlPost(VAR GenJournalLine : Record "Gen. Journal Line";VAR IsHandled : Boolean)**

called from "OnPostReport()", including a local boolean var named IsHandled:

**OnPostReport()**
InsBalLines;

IF NOT GenJnlLine.FIND('-') THEN
  EXIT;
**//INIT-INSERT
OnBeforeGenJnlPost(GenJnlLine,IsHandled);
IF IsHandled THEN 
  EXIT;
//END-INSERT**

Window.CLOSE;
Window.OPEN(
  Text1100100);
.........

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
