### ISSUE TITLE
[Event Request] Report 94 Close income Statement - OnInsBalLinesOnBeforeGenJnlLineInsert

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#8731]
We need a new event in Report 94 "Close income Statement":

**LOCAL [IntegrationEvent] OnInsBalLinesOnBeforeGenJnlLineInsert(VAR GenJournalLine : Record "Gen. Journal Line";BalLineBuffer : TEMPORARY Record "Inc. Stmt. Clos. Buffer")**

called from "InsBalLines()" function:

**InsBalLines()**
IF BalLineBuffer.FIND('-') THEN
  REPEAT
    GenJnlLine."Line No." := GenJnlLine."Line No." + 10000;
    GenJnlLine."Account No." := BalLineBuffer."Account No.";
    ..............
    ..............
    GenJnlLine."System-Created Entry" := TRUE;
    **//INIT-INSERT
    OnInsBalLinesOnBeforeGenJnlLineInsert(GenJnlLine,BalLineBuffer);
    //END-INSERT**
    GenJnlLine.INSERT;
  UNTIL BalLineBuffer.NEXT = 0;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
