### ISSUE TITLE
[Additional Parameter Request] Codeunit 5878 Phys. Invt. Rec.-Reopen - OnBeforePhysInvtOrderLineModify

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8732]
Hi Team,
In codeunit 5878 we need possibility to have additional checks in the procedure Reopen. Standard publisher would suit us if it had additional standard parameter `PhysInvtRecordHeader: Record "Phys. Invt. Record Header"` . `OnBeforePhysInvtOrderLineModify` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93874416-011e7780-fcdc-11ea-87e9-8ba00ce3e8d1.png)

[IntegrationEvent(false, false)]
local procedure OnBeforePhysInvtOrderLineModify(var PhysInvtOrderLine: Record "Phys. Invt. Order Line"; PhysInvtRecordLine: Record "Phys. Invt. Record Line"; **PhysInvtRecordHeader: Record "Phys. Invt. Record Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
