### ISSUE TITLE
[Event Request] Codeunit 5879 Phys. Invt. Order-Finish (Y/N) - OnBeforeConfirmOnRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8733]
Hi Team,

In codeunit 5879 we need possibility to replace and avoid using standard code. Having event with handling in procedure `OnRun`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93874655-59ee1000-fcdc-11ea-8439-10311f9bc582.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmOnRun(var PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
