### ISSUE TITLE
[Event Request] Codeunit 5884 Phys. Invt. Order-Post - OnBeforeCheckWhseJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8734]
Hi Team,

In codeunit 5884 we need possibility to replace and avoid using standard code. Having event in procedure `PostWhseJnlLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93878284-7ee58180-fce2-11ea-908d-1f6e33174d4f.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWhseJnlLine(var TempWhseJnlLine2: Record "Warehouse Journal Line" temporary; var Positive: boolean; Location: record Location; PhysInvtOrderLine: Record "Phys. Invt. Order Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
