### ISSUE TITLE
[Event Request] Codeunit 5884 Phys. Invt. Order-Post - OnPostPhysInventoryOrderLineOnBeforePostPositiveAmount

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8735]
Hi Team,

In codeunit 5884 we need possibility to replace and avoid using standard code. Having event in procedure `PostPhysInventoryOrderLines`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93878711-31b5df80-fce3-11ea-97dd-6c47523f2214.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostPhysInventoryOrderLineOnBeforePostPositiveAmount(var PhysInvtOrderLine: Record "Phys. Invt. Order Line"; WhsePosting: Boolean; var ItemJnlLine: Record "Item Journal Line"; var PstdPhysInvtOrderHdr: Record "Pstd. Phys. Invt. Order Hdr"; var PstdPhysInvtOrderLine: Record "Pstd. Phys. Invt. Order Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
