### ISSUE TITLE
[Event Request] Codeunit 5899 Calc. Inventory Value-Check - OnAfterCheckCalculatePerOnAfterSetFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8736]
Hi Team,

In codeunit 5899 we need possibility to replace and avoid using standard code. Having event with handling in procedure `CheckCalculatePer`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93879870-32e80c00-fce5-11ea-9e24-ffd2772e71d4.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckCalculatePerOnAfterSetFilters(var TempErrorBuf: Record "Error Buffer" temporary; var ErrorCounter: Integer; var Item2: Record Item; TestMode: Boolean;ByVariant: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
