### ISSUE TITLE
[Event Request] Codeunit 5772 Whse.-Transfer Release - OnCheckReopenOutbound

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8759]
Hi Team,

In codeunit 5772 we need possibility to replace and avoid using standard code. Having event in procedure `Reopen`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93887405-5617b900-fcef-11ea-8881-14dd4ae1ffd3.png)

    [IntegrationEvent(false, false)]
    local procedure OnCheckReopenOutbound(var TransHeader: Record "Transfer Header")

**Comment by StanPesotskiy** [comment]
Can't you use the existing OnAfterReopen()?

**Comment by MantasGurinas** [comment]
Moved to OnAfterReopen()
