### ISSUE TITLE
[Additional Parameter Request] Codeunit 5804 Item Cost Management - OnBeforeUpdateUnitCost

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8806]
Hi Team,
In codeunit 5804 we need possibility to have additional checks in the procedure `UpdateUnitCost`. Standard publisher would suit us if it had additional standard parameter `CalledFromAdjustment: Boolean` as pass by reference . `OnBeforeUpdateUnitCost` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/93893951-df7eb980-fcf6-11ea-80a0-fdf7139a6e05.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateUnitCost(var Item: Record Item; LocationCode: Code[10]; VariantCode: Code[10]; LastDirectCost: Decimal; NewStdCost: Decimal; UpdateSKU: Boolean; FilterSKU: Boolean; RecalcStdCost: Boolean; CalledByFieldNo: Integer; var UnitCostUpdated: Boolean; **var CalledFromAdjustment: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
