### ISSUE TITLE
[Event Request] Codeunit 5804 Item Cost Management - OnAfterUpdateUnitCost

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8811]
Hi Team,

In codeunit 5804 we need possibility to replace and avoid using standard code. Having event in the end of procedure `UpdateUnitCost`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93894657-a561e780-fcf7-11ea-8ff6-2ef74415ecc7.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateUnitCost(var Item: Record Item; CalledByFieldNo: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
