### ISSUE TITLE
[Event Request] Codeunit 5804 Item Cost management - OnUpdateUnitCostSKUOnBeforeCalledFromAdjustment

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8812]
Hi Team,

In codeunit 5804 we need possibility to replace and avoid using standard code. Having event with handling in procedure `UpdateUnitCostSKU`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93896970-3afe7680-fcfa-11ea-9322-465931bf0955.png)

    [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostSKUOnBeforeCalledFromAdjustment(CalledFromAdjustment: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
