### ISSUE TITLE
[Event Request] Codeunit 5804 Item Cost Management - OnFindUpdateUnitCostSKUOnBeforeUpdateUnitCostSKU

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8813]
Hi Team,

In codeunit 5804 we need possibility to replace and avoid using standard code. Having event in procedure `FindUpdateUnitCostSKU`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93897392-afd1b080-fcfa-11ea-83eb-3ddc499db455.png)

    [IntegrationEvent(false, false)]
    local procedure OnFindUpdateUnitCostSKUOnBeforeUpdateUnitCostSKU(var SKU: Record "Stockkeeping Unit"; FilterSKU: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
