### ISSUE TITLE
[Event Request] Codeunit 5706 TransferOrder-Post (Yes/No) - OnBeforeShowSelection

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8814]
Hi Team,

In codeunit 5706 we need possibility to replace and avoid using standard code. Having event with handling in procedure `Code`, allows us to adjust case scenario would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/93899029-8f0a5a80-fcfc-11ea-83e1-665b1ccc48c6.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowSelection(var TransHeader: Record "Transfer Header"; var DefaultNumber: Integer; var Selection: Option " ",Shipment,Receipt; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
