### ISSUE TITLE
[Event Request] Table 14 Location - WMSCheckWarehouse

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8815]
We need a new event and a IsHandled boolean in the procedure WMSCheckWarehouse of the table 14 Location, in order to add our own procudures inside this code with the event raised. Like this :

![image](https://user-images.githubusercontent.com/34645582/93904317-05598d80-fcfa-11ea-924b-6e1a591708f4.png)

And the integration event : 
![image](https://user-images.githubusercontent.com/34645582/93904359-14d8d680-fcfa-11ea-8a48-0185efc63cda.png)

Do you think it could be possible ?

Thank you for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
