### ISSUE TITLE
[Event Request] Table 2000041 "CODA Statement Line" – New event “OnUpdateStatusOnAfterUpdateApplicationFields”

### ISSUE THREAD

**Issue by vanmito** [microsoft/ALAppExtensions#8816]
Hello, 

**Could we please have a new event “OnUpdateStatusOnAfterUpdateApplicationFields” in function “UpdateStatus”, Table 2000041 "CODA Statement Line"?

    [Scope('OnPrem')]
    procedure UpdateStatus()
    var
        CODAStmtLine: Record "CODA Statement Line";
        CODAStmtLine2: Record "CODA Statement Line";
        StatusCount: array[4] of Integer;
    begin
        if "Account No." = '' then begin
            "Application Status" := "Application Status"::" ";
            Validate(Amount, 0);
            "Unapplied Amount" := "Statement Amount"
        end else
            if "System-Created Entry" = false then
                // set Application status to Partly applied if no application ledger entry is selected
                if "Applies-to ID" = '' then begin
                    "Application Status" := "Application Status"::"Partly applied";
                    "Unapplied Amount" := "Statement Amount";
                end else begin
                    "Application Status" := "Application Status"::Applied;
                    Validate(Amount, "Statement Amount");
                    Validate("Statement Amount", 0);
                    "Unapplied Amount" := 0
                end;

        // --- Begin New Code ---
        OnUpdateStatusOnAfterUpdateApplicationFields(Rec, xRec);
        // --- End New Code ---

        // Lines with global info and details
        if Type = Type::Global then begin
            // Modify all details
            CODAStmtLine.Reset();
            CODAStmtLine.SetRange("Bank Account No.", "Bank Account No.");
            CODAStmtLine.SetRange("Statement No.", "Statement No.");
            CODAStmtLine.SetRange(ID, ID);
            CODAStmtLine.SetRange("Attached to Line No.", "Statement Line No.");
            if CODAStmtLine.FindSet then
                repeat
....

...

    [IntegrationEvent(false, false)]
    local procedure OnUpdateStatusOnAfterUpdateApplicationFields(var CODAStatementLine: Record "CODA Statement Line"; xCODAStatementLine: Record "CODA Statement Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
