### ISSUE TITLE
[Event Request] Table 14 Location - "Bin Mandatory" field OnValidate trigger

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8817]
In table 14 Location, inside the trigger OnValide of the field "Bin Mandatory", we used to add some code on NAV 2018. We are now migrating our code to BC 16.4 and we would like to add our modification inside this trigger. OnBeforeValidate and OnAfterValidate don't allow us to do exactly what we want to, so we would like to raise these events inside the OnValidate trigger : 

![image](https://user-images.githubusercontent.com/34645582/93981657-85c2d180-fd80-11ea-8a0c-3d3f344f17f5.png)

With the integration events : 
![image](https://user-images.githubusercontent.com/34645582/93981425-41373600-fd80-11ea-948e-49e5583f860b.png)

Do you think it could be possible ?

Thank you for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
