### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnInitSourceDocumentHeaderOnBeforePurchaseHeaderReopen

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8819]
Hi Team,

In codeunit 5763 we need possibility to replace and avoid using standard code. Having event in procedure `InitSourceDocumentHeader`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94014941-e66c0180-fdb4-11ea-936f-9219c72a8a20.png)

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnBeforePurchaseHeaderReopen(var WhseShptLine: Record "Warehouse Shipment Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
