### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnBeforeSalesPostRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8820]
Hi Team,

In codeunit 5763 we need possibility to replace and avoid using standard code. Having event in procedure `PostSourceDocument`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94015705-e3bddc00-fdb5-11ea-99ab-c8a6d108c67e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesPostRun(var SalesPost: Codeunit "Sales-Post"; SalesHeader: Record "Sales Header"; WhseShptHeader: record "Warehouse Shipment Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
