### ISSUE TITLE
[Additional Parameter Request] Codeunit 5763 Whse.-Post Shipment - OnPostSourceDocumentOnBeforePrintSalesShipment

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8821]
Hi Team,
In codeunit 5763 we need possibility to have additional checks in the procedure `PostSourceDocument`. Standard publisher would suit us if it had additional standard parameter `WhseShptHeader: Record "Warehouse Shipment Header"` and `var SalesShptHeader: Record "Sales Shipment Header"` . `OnPostSourceDocumentOnBeforePrintSalesShipment`, would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94016151-7494b780-fdb6-11ea-9fb4-a098286ca4c7.png)

[IntegrationEvent(false, false)]
local procedure OnPostSourceDocumentOnBeforePrintSalesShipment(var SalesHeader: Record "Sales Header"; **WhseShptHeader: Record "Warehouse Shipment Header"; var SalesShptHeader: Record "Sales Shipment Header"**; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
