### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnAfterPurchPostRun

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8822]
Hi Team,

In codeunit 5763 we need possibility to replace and avoid using standard code. Having event in procedure `PostSourceDocument`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94016680-174d3600-fdb7-11ea-99d0-41a61baf4600.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterPurchPostRun(WhseShptHeader: Record "Warehouse Shipment Header"; PurchHeader: Record "Purchase Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
