### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnBeforeWhseShptHeaderParamModify

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8823]
Hi Team,

In codeunit 5763 we need possibility to replace and avoid using standard code. Having event in procedure `PostUpdateWhseDocuments`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94017055-9e021300-fdb7-11ea-9c55-8ef4fb82ff48.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhseShptHeaderParamModify(var WhseShptHeader: Record "Warehouse Shipment Header"; var WhseShptHeaderParam: Record "Warehouse Shipment Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
