### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnCheckHideConfirmRegPackingTable

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8824]
Hi Team,

In codeunit 5763 we need possibility to replace and avoid using standard code. Having event with handling in procedure `GetResultMessage`, allows us to adjust case scenario would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94020276-6b5a1980-fdbb-11ea-83ec-4d7823fea318.png)

    [IntegrationEvent(false, false)]
    local procedure OnCheckHideConfirmRegPackingTable(var IsHandled: Boolean; CounterSourceDocOK: Integer; CounterSourceDocTotal: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
