### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnBeforeFindSalesLineOnHandleSalesLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8825]
Hi Team,

In codeunit 5763 we need possibility to replace and avoid using standard code. Having event in procedure `HandleSalesLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94021978-4797d300-fdbd-11ea-9bcd-72ab2fee8f78.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindSalesLineOnHandleSalesLine(var SalesLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
