### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnSalesLinePostFromWhseItemSet

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8826]
Hi Team,

In codeunit 5763 we need possibility to replace and avoid using standard code. Having event in procedure `HandleSalesLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94023715-3780f300-fdbf-11ea-8422-21cc38e69f8f.png)

    [IntegrationEvent(false, false)]
    local procedure OnSalesLinePostFromWhseItemSet(var SalesLine: Record "Sales Line"; WhseShptLine: Record "Warehouse Shipment Line"; Invoice: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
