### ISSUE TITLE
[Event Request] Table 7302 Bin Content - OnBeforeCalcQtyAvailToPick

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8827]
Hi Team,

In table 7302, please provide the possibility to have event **OnBeforeCalcQtyAvailToPick**  in procedure **CalcQtyAvailToPick**

![image](https://user-images.githubusercontent.com/57799519/94033973-1cbe7680-fddf-11ea-84b2-58dd1546c926.png)

Event:
![image](https://user-images.githubusercontent.com/57799519/94033178-5347c180-fdde-11ea-82a8-493af0280595.png)

Please backport to BC14 also.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Rambabu-Billuri** [comment]
Can you backport the same to BC14 ?
