### ISSUE TITLE
[Event Request] Table 10866 Payment Line - OnAfterSetUpNewLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8828]
Hello, we would like to have the possibility to add code in the Table 1066 Payment Line, in the procedure SetUpNewLine. Is it possible to raise this event at this point of the procedure ?
![image](https://user-images.githubusercontent.com/34645582/94130663-3dc5ac80-fe5d-11ea-9c6b-c3d4338a8d22.png)

And here is the event integration.
![image](https://user-images.githubusercontent.com/34645582/94130600-2be40980-fe5d-11ea-8cfb-125c5280cc51.png)

Thanks for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
