### ISSUE TITLE
[Additional Parameter Request] Codeunit 333 Req. Wksh.-Make Order - OnBeforeCarryOutBatchActionCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8829]
Hi Team,
In codeunit 333 we need possibility to have additional checks in the procedure `CarryOutBatchAction`. Standard publisher would suit us if it had additional standard parameter `CreateAs: Option` . `OnBeforeCarryOutBatchActionCode` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94137999-044a6c80-fe70-11ea-8b23-fcdb3f6284f3.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeCarryOutBatchActionCode(var RequisitionLine: Record "Requisition Line"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
