### ISSUE TITLE
Report 5753 - suppress commit and hide dialog

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#883]
Hello,

for external use, we need a functionality to suppress commit and to set HideDialog externally. 
Is it possible to integrate these functions?

Thank you,
K.

**Comment by grobyns** [comment]
Hi,

The report already supports hiding the dialog through SetHideDialog which is marked as External.
Regarding suppressing the commit, please see comments on your other SuppressCommit requests #926 , #933 . We can look into adding the same pattern here if you like.

br/Gert

**Comment by KReinmann** [comment]
That would be perfect, if we can suppress commit by setting a global variable externally.
Thank you so much.

BR/Kathrin

**Comment by grobyns** [comment]
Hi,

we will add it to our backlog. We’re entering the endgame for the Spring ’19 release and we need to focus on finishing up so unfortunately I cannot promise what update this will ship in.

br/Gert

**Comment by KReinmann** [comment]
Hi,
Are there new insights here?
Thanks in advance,
best regards,
Kathrin

**Comment by KReinmann** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
And a third issue, where the system didn't report the status back. I've seen 4 occurrences of this happening, 3 of them were your requests. What are the odds?
But again, this issue appears to be resolved and has shipped with the fall 19 release in October. If you verify, I will close this issue.
Now I will look into, why in these cases the link between our system and GitHub was broken. My apologies for the radio silence on last time.

**Comment by JesperSchulz** [comment]
Assuming this was indeed addressed. If not, please open a new issue.
