### ISSUE TITLE
[Event Request] Codeunit 333 Req. Wksh.-Make Order - OnCodeOnBeforeCheckLines

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8830]
Hi Team,

In codeunit 333 we need possibility to replace and avoid using standard code. Having event with handling in procedure `Code`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94141784-f39cf500-fe75-11ea-9821-0666ba10cb3a.png)

    [IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeCheckLines(ReqTemplate: Record "Req. Wksh. Template"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
