### ISSUE TITLE
[Additional Parameter Request] Codeunit 333 Req. Wksh.-Make Order - OnBeforeDeleteReqLines

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8831]
Hi Team,
In codeunit 333 we need possibility to have additional checks in the procedure `Code`. Standard publisher would suit us if it had additional standard parameter `ReqLine2: Record "Requisition Line"` as pass by reference . `OnBeforeDeleteReqLines` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94142353-d157a700-fe76-11ea-903a-2ebd2f4c5d47.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteReqLines(var ReqLine: Record "Requisition Line"; var TempFailedReqLine: Record "Requisition Line" temporary; **var ReqLine2: Record "Requisition Line"**;var IsHandled: Boolean);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
