### ISSUE TITLE
[Event Request] Codeunit 333 Req. Wksh.-Make Order - OnBeforeValidateUnitCost

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8832]
Hi Team,

In codeunit 333 we need possibility to replace and avoid using standard code. Having event in procedure `InsertPurchOrderLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94142738-6a86bd80-fe77-11ea-91bd-6843987eb74e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateUnitCost(var PurchOrderLine: Record "Purchase Line"; SalesOrderLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
