### ISSUE TITLE
[Event Request] Codeunit 335 Req. Wksh.-Show card - OnBeforeRunItemCard

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8833]
Hi Team,

In codeunit 335 we need possibility to replace and avoid using standard code. Having event with handling in the beginning of procedure `OnRun`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94144028-504ddf00-fe79-11ea-8aed-a040152b3a53.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunItemCard(RequisitionLine: Record "Requisition Line"; Item: Record Item; GLAcc: Record "G/L Account"; IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
