### ISSUE TITLE
Table 10866 Payment Line - OnBeforeDimensionCreate

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8834]
Migrating our code NAV 2018 to BC 16.4, we would like to add some code in the procedure DimensionCreate, in the table 10866 Payment Line. Could you please add a IsHandled flag and raise an event in this procedure please, like this : 

![image](https://user-images.githubusercontent.com/34645582/94145040-3a88eb80-fe72-11ea-9d8a-45fadf07f93e.png)

With the integration event : 
![image](https://user-images.githubusercontent.com/34645582/94145081-4a083480-fe72-11ea-82ef-8f7c90c86dcc.png)

Thank you for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
