### ISSUE TITLE
[Event Request] Codeunit 12 CalcPmtTolerancePossible - Add OnBeforeCalcPmtTolerancePossible

### ISSUE THREAD

**Issue by Joneleth84** [microsoft/ALAppExtensions#8836]
Hello!

We would like to control how the payment discount tolerance date is calculated. Therefore we would need an additional trigger before the date is calculated. Ideally you would refactor function CalcPmtTolerancePossible() according to CalcPmtTolerance(), therefore adding:

`OnBeforeCalcPmtTolerancePossible(GenJnlLine: Record "Gen. Journal Line"; PmtDiscountDate: Date; var PmtDiscToleranceDate: Date; var MaxPaymentTolerance: Decimal, var IsHandled: Boolean)`

Thank you and best regards,
Johannes

![c12](https://user-images.githubusercontent.com/56401325/94155284-0f58c900-fe7f-11ea-9818-f9e0117550b5.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
