### ISSUE TITLE
[Additional Parameter Request] Codeunit 6500 Item Tracking Management - OnBeforeExistingExpirationDate

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8837]
Hi Team,
In codeunit 6500 we need possibility to have additional checks in the procedure `ExistingExpirationDate`. Standard publisher would suit us if it had additional standard parameter `ItemLedgEntry: Record "Item Ledger Entry"` as pass by reference . `OnBeforeExistingExpirationDate` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94160672-872df000-fe8d-11ea-93f9-6b72e92bd576.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeExistingExpirationDate(ItemNo: Code[20]; Variant: Code[20]; LotNo: Code[50]; SerialNo: Code[50]; TestMultiple: Boolean; var EntriesExist: Boolean; var ExpDate: Date; **var ItemLedgEntry: record "Item Ledger Entry"**;var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
