### ISSUE TITLE
[Event Request] Codeunit 6500 Item Tracking Management - OnGetWhseExpirationDate

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8838]
Hi Team,

In codeunit 6500 we need possibility to replace and avoid using standard code. Having event with handling in procedure `GetWhseExpirationDate`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94161545-75991800-fe8e-11ea-9cca-af58d4bc80c8.png)

    [IntegrationEvent(false, false)]
    local procedure OnGetWhseExpirationDate(var ExpDate: Date; ItemNo: Code[20]; LotNo: Code[50]; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
