### ISSUE TITLE
[Function Expose] Table 38 RecreatePurchLines

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/ALAppExtensions#884]
Hi,

we need function RecreatePurchlines in Table 38 Purchase Header to be Global/External.

Thanks

**Comment by Bleika** [comment]
Hi,
I've just noticed that this is still pending in the latest build - any news on this?
Thanks
@darjoo @LFlamme

**Comment by darjoo** [comment]
Hi @Bleika and @LFlamme,
There has been no progress on this front at the moment as we have been focused on preparing for the next major release. We will be proceeding on these requests as usual again soon!

**Comment by darjoo** [comment]
Closing this as we are tracking this issue through #1280 now.
