### ISSUE TITLE
Table 5407 Prod. Order Component - OnBeforeBinCodeOnValidate

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8843]
We used to modify the code inside the trigger OnValidate of field "Bin Code" in table 5407 "Prod. Order Component" when we were on NAV 2018. We would like to reproduce our code behavior in BC 16.4. Is it possible to add a IsHandled flag and to raise an event here : 

![image](https://user-images.githubusercontent.com/34645582/94162349-e5a3a000-fe86-11ea-86df-589b54325d87.png)

And the integration event : 
![image](https://user-images.githubusercontent.com/34645582/94162403-f3f1bc00-fe86-11ea-8064-dd5625012db1.png)

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
