### ISSUE TITLE
[Event Request] Codeunit 6500 Item Tracking Management - OnBeforeSetCalledFromSynchWhseItemTrkg

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8846]
Hi Team,

In codeunit 6500 we need possibility to replace and avoid using standard code. Having event in procedure `RegisterNewItemTrackingLines`, would be a perfect solution, because we need to set parameters in codeunit `ItemTrackingLines`, so standard event  OnBeforeRegisterItemTrackingLinesLoop can not be used, because after it the codeunit is cleared:

![image](https://user-images.githubusercontent.com/70525691/94164490-c4947c80-fe91-11ea-9da0-3d924a1d073b.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetCalledFromSynchWhseItemTrkg(var ItemTrackingLines: Page "Item Tracking Lines")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
