### ISSUE TITLE
[Event Request] Codeunit 6500 Item Tracking Management - OnBeforeCopyTrackingFromItemLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8847]
Hi Team,

In codeunit 6500 we need possibility to replace and avoid using standard code. Having event in procedure `InitReservEntry`, would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94164946-53a19480-fe92-11ea-812f-21d27d66a058.png)

    [IntegrationEvent(true, false)]
    local procedure OnBeforeCopyTrackingFromItemLedgEntry(var ReservEntry: Record "Reservation Entry"; var ItemLedgEntryBuf: Record "Item Ledger Entry"; var EntriesExist: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
