### ISSUE TITLE
New Function SetVariabel

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#885]
Hi,

we need a new Global/External function in codeunit 7000, wich allows us to set currency, vat and unit of measure.
![image](https://user-images.githubusercontent.com/41729653/51475351-5cb79580-1d82-11e9-9736-7f8fe4eeafb8.png)

parameters:
itemNoL : Code[20]
;currencyCodeL : Code[10]
;currencyfactorL : Decimal
;currencyDateL : Date;
qtyL : Decimal;
qtyPerUoML : Decimal

Thanks in advance

**Comment by JesperSchulz** [comment]
We're currently looking into the extensibility of our pricing module. We will consider your input.
