### ISSUE TITLE
[Event Request] Codeunit 5790 "Available to Promise" - OnBeforeQtyAvailableToPromise

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8850]
In the Codeunit 5790 "Available to Promise", in the procedure QtyAvailabletoPromise, which returns a Decimal value, there is a IsHandled flag. If I switch this flag to True, the procedure stops prematurely with an exit method. But this exit method doesn't return any value. Could it be possible to make this exit able to return a value ? Here is an example of what would be optimal for us : 

![image](https://user-images.githubusercontent.com/34645582/94164083-e3424580-fe88-11ea-8bf1-8640e5b5cf23.png)

And the integration event : 
![image](https://user-images.githubusercontent.com/34645582/94165624-b55e0080-fe8a-11ea-99d5-00de4b43ca03.png)

Do you think it could be possible ?

Thanks for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
