### ISSUE TITLE
[Event Request] Table 5407 "Prod. Order Component" - OnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8853]
We need a IsHandled flag and an event publisher in the procedure GetDefaultBin in the table 5407 Prod. Order Component. Like this : 

![image](https://user-images.githubusercontent.com/34645582/94170475-6a46ec00-fe90-11ea-92a1-414de74d7802.png)

The integration event : 
![image](https://user-images.githubusercontent.com/34645582/94170295-2f44b880-fe90-11ea-9e2f-45f29cd6882a.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
