### ISSUE TITLE
[Event Request] Table 5407 Prod. Order Component - OnBeforeUpdateUnitCost

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8854]
In table 5407 Prod. Order Component, in the local procedure UpdateUnitCost, we used to calculate "Unit Cost" and "Indirect Cost %" in another way than the standard one. In BC 16.4, we actually can't do what we want to. We need to have an event publisher at the beginning of this procedure and a IsHandled flag. Like this : 

![image](https://user-images.githubusercontent.com/34645582/94239460-25639980-ff12-11ea-9327-308bbb92aec9.png)

And the integration event : 
![image](https://user-images.githubusercontent.com/34645582/94239507-37453c80-ff12-11ea-8ea9-a8d14042be07.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
