### ISSUE TITLE
[EventRequest] Codeunit 1535 Approvals Mgmt. - CreateApprovalRequestForApproverChain

### ISSUE THREAD

**Issue by PieterDeVriesAddIT** [microsoft/ALAppExtensions#8855]
To make the approval framework and 'Approval User Setup' more extensible. We would like Integration Events to adjust the user setup. For example: to set a different 'Approver ID' and/or approval amount based upon a workflow category.

In the function CreateApprovalRequestForApproverChain a request for two integration events 'OnAfterGetUserSetupWorkflowStepArgument' (UserSetup as Var)

IF NOT UserSetup.GET(ApproverId) THEN
  ERROR(ApproverUserIdNotInSetupErr,ApprovalEntry."Sender ID");
**OnAfterGetUserSetupWorkflowStepArgument(UserSetup,WorkflowStepArgument,ApprovalEntryArgument); //CM00084.Event**

IF NOT IsSufficientApprover(UserSetup,ApprovalEntryArgument) THEN
  REPEAT
    ApproverId := UserSetup."Approver ID";

    IF ApproverId = '' THEN
      ERROR(NoSuitableApproverFoundErr);

    IF NOT UserSetup.GET(ApproverId) THEN
      ERROR(ApproverUserIdNotInSetupErr,UserSetup."User ID");
    **OnAfterGetUserSetupWorkflowStepArgument(UserSetup,WorkflowStepArgument,ApprovalEntryArgument); //CM00084.Event**

    // Approval Entry should not be created only when IsSufficientApprover is false and SufficientApproverOnly is true
    IF IsSufficientApprover(UserSetup,ApprovalEntryArgument) OR (NOT SufficientApproverOnly) THEN BEGIN
      SequenceNo := GetLastSequenceNo(ApprovalEntryArgument) + 1;
      MakeApprovalEntry(ApprovalEntryArgument,SequenceNo,ApproverId,WorkflowStepArgument);
    END;

  UNTIL IsSufficientApprover(UserSetup,ApprovalEntryArgument);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
