### ISSUE TITLE
[EventRequest] Codeunit 1535  Approvals Mgmt. - CreateApprovalRequestForApprover

### ISSUE THREAD

**Issue by PieterDeVriesAddIT** [microsoft/ALAppExtensions#8856]
To make the approval framework and 'Approval User Setup' more extensible. We would like Integration Events to adjust the user setup. For example: to set a different 'Approver ID' and/or approval amount based upon a workflow category.

In the function CreateApprovalRequestForApprover a request for an integration event 'OnAfterGetUserSetupWorkflowStepArgument' (UserSetup as Var)

IF NOT UserSetup.GET(USERID) THEN
  ERROR(UserIdNotInSetupErr,UsrId);
**OnAfterGetUserSetupWorkflowStepArgument(UserSetup,WorkflowStepArgument,ApprovalEntryArgument); //CM00084.Event**

UsrId := UserSetup."Approver ID";
IF NOT UserSetup.GET(UsrId) THEN BEGIN

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
