### ISSUE TITLE
codeunit 97 "Blanket Purch. Order to Order" OnCreatePurchHeaderOnBeforeInitRecord

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#8857]
Can a publisher OnCreatePurchHeaderOnBeforeInitRecord be added in codeunit 97 "Blanket Purch. Order to Order"?

![image](https://user-images.githubusercontent.com/16033297/94247088-f0107900-ff1c-11ea-956e-d8833f52aee6.png)

please make both variables var
![image](https://user-images.githubusercontent.com/16033297/94247187-11716500-ff1d-11ea-8022-9ee0bfee97b0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
