### ISSUE TITLE
[EventRequest] Codeunit 1535 Approvals Mgmt. - SubstituteUserIdForApprovalEntry

### ISSUE THREAD

**Issue by PieterDeVriesAddIT** [microsoft/ALAppExtensions#8858]
To make the approval framework and 'Approval User Setup' more extensible. We would like Integration Events to adjust the user setup. For example: to set a different 'Approver ID' and/or approval amount based upon a workflow category.

In the function SubstituteUserIdForApprovalEntry there is a integration event 'OnBeforeSubstituteUserIdForApprovalEntry' availble. But the function OnDelegateApprovalRequest(ApprovalEntry) is not global available, so not all code can be replaced with current event.

Therefore a request for an additional integration event after the UserSetup.GET: OnAfterGetUserSetupSubstituteUserIdForApprovalEntry (UserSetup as Var)

    begin
        IsHandled := false;
        OnBeforeSubstituteUserIdForApprovalEntry(ApprovalEntry, IsHandled);
        if IsHandled then
            exit;

        if not UserSetup.Get(ApprovalEntry."Approver ID") then
            Error(ApproverUserIdNotInSetupErr, ApprovalEntry."Sender ID");
        **OnAfterGetUserSetupSubstituteUserIdForApprovalEntry(UserSetup,ApprovalEntry); //CM00084.Event**

        if UserSetup.Substitute = '' then
            if UserSetup."Approver ID" = '' then begin
                ApprovalAdminUserSetup.SetRange("Approval Administrator", true);
                if ApprovalAdminUserSetup.FindFirst then
                    UserSetup.Get(ApprovalAdminUserSetup."User ID")
                else
                    Error(SubstituteNotFoundErr, UserSetup."User ID");
            end else
                UserSetup.Get(UserSetup."Approver ID")
        else
            UserSetup.Get(UserSetup.Substitute);

        ApprovalEntry."Approver ID" := UserSetup."User ID";
        ApprovalEntry.Modify(true);
        OnDelegateApprovalRequest(ApprovalEntry);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
