### ISSUE TITLE
[Event Request] Table 5406 Prod. Order Line - OnBeforeGetUpdateFromSKU

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8859]
In the table 5406 Prod. Order Line, in the procedure GetUpdateFromSKU, we would like to modify the way "Unit Cost is Calculated in the "else". The only way to do that is to have a IsHandled flag and an event publisher. Like this : 

![image](https://user-images.githubusercontent.com/34645582/94249574-61056000-ff20-11ea-8ec9-375a8e996e71.png)

Then event publisher should be here and not earlier because GetItem and GetSKU are local procedure, so can't be called from an event subscriber.

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/94247693-c441c300-ff1d-11ea-98fd-aff62cfb88ac.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
