### ISSUE TITLE
codeunit 86 "Sales-Quote to Order" change OnBeforeInsertSalesOrderHeader

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#8860]
can the variable SalesQuoteHeader in OnBeforeInsertSalesOrderHeader made var?

![image](https://user-images.githubusercontent.com/16033297/94249049-9e1d2280-ff1f-11ea-89ab-27cc0201cbd3.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
