### ISSUE TITLE
codeunit 87 "Blanket Sales Order to Order" change OnBeforeInsertSalesOrderHeader

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#8861]
can the variable SalesQuoteHeader in OnBeforeInsertSalesOrderHeader made var?

![image](https://user-images.githubusercontent.com/16033297/94250357-6c0cc000-ff21-11ea-865d-29fa33440674.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
