### ISSUE TITLE
event request - table 9657 "Custom Report Selection" - GetSendToEmail() - OnBeforeGetSendToEmail()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#8862]
It is desirable to be able to substitute other email addresses per Customer/Vendor, instead of the Document Layout "Send To Email", particularly when clients are already using e.g. fields on the Card and don't want to have to copy or synchronise those to the Doc Layouts.

So, please add the following event, emission, and Result name to enable it:

    procedure GetSendToEmail(Update: Boolean) Result: Text[250]
    var
        Contact: Record Contact;
    begin
        // +NEW
        OnBeforeGetSendToEmail(Result, IsHandled);

        if IsHandled then
            exit;
        // -NEW

        if "Use Email from Contact" then begin
            Contact.SetFilter("No.", GetSelectedContactsFilter());
            FillSendToEmail(Contact);

            if Update then
                Modify();
        end;

        exit("Send To Email");
    end;

    [IntegrationEvent(true, false)]
    local procedure OnBeforeGetSendToEmail(var Result: Text[250]; var IsHandled: Boolean);

Developers could then e.g. get the Customer from the Source No., and return the email addres through some other means, whether from the Customer Card or elsewhere.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
