### ISSUE TITLE
[Event Request] Codeunit 7308 Replenishment - OnBeforeFindFromBinContent

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8863]
Hi Team,

In codeunit 7308 we need possibility to replace and avoid using standard code. Having event in procedure `FindReplenishmtBin`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94255826-877fc700-ff31-11ea-8496-1154cca7d970.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindFromBinContent(var FromBinContent: Record "Bin Content"; var ToBinContent: Record "Bin Content")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
