### ISSUE TITLE
[Event Request] Codeunit 7308 Replenishment - OnCreateWhseWkshLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8864]
Hi Team,

In codeunit 7308 we need possibility to replace and avoid using standard code. Having event in procedure `CreateWhseWkshLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94255934-b007c100-ff31-11ea-8b67-7aac19a478a4.png)

    [IntegrationEvent(false, false)]
    local procedure OnCreateWhseWkshLine(var TempWhseWkshLine: Record "Whse. Worksheet Line"; ToBinContent: Record "Bin Content")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
