### ISSUE TITLE
[Event Request] Codeunit 7308 Replenishment - OnAfterInsertWhseWkshLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8865]
Hi Team,

In codeunit 7308 we need possibility to replace and avoid using standard code. Having event in procedure `InsertWhseWkshLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94256064-dfb6c900-ff31-11ea-9441-9b6dd74cc351.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
