### ISSUE TITLE
[Additional Parameter Request] Codeunit 7311 Whse. Worksheet-Create - OnAfterFromProdOrderCompLineCreateWhseWkshLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8866]
Hi Team,
In codeunit 7311 we need possibility to have additional checks in the procedure `FromProdOrderCompLine`. Standard publisher would suit us if it had additional standard parameter `LocationCode: Code[10]` and `ToBinCode: Code[20]`. `OnAfterFromProdOrderCompLineCreateWhseWkshLine` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94257293-bb5bec00-ff33-11ea-8764-999ea298f6e1.png)

[IntegrationEvent(false, false)]
local procedure OnAfterFromProdOrderCompLineCreateWhseWkshLine(var WhseWorksheetLine: Record "Whse. Worksheet Line"; ProdOrderComponent: Record "Prod. Order Component"; **LocationCode: Code[10]; BinCode: Code[20]**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
