### ISSUE TITLE
[Event Request] Page 21 Customer Card - OnBeforeOpenPage

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8867]
Hi Team,

In page 21 we need possibility to replace and avoid using standard code. Having event in the end of trigger `OnOpenPage`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94257985-d844ef00-ff34-11ea-8825-9ec61c8db3dd.png)

    [IntegrationEvent(true, false)]
    local procedure OnBeforeOpenPage(var Customer: Record Customer; xCustomer: Record Customer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
