### ISSUE TITLE
[Event Request] Page 21 Customer Card - OnAfterActivateFields

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8868]
Hi Team,

In page 21 we need possibility to replace and avoid using standard code. Having event in the end of procedure `ActivateFields`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94258165-19d59a00-ff35-11ea-8047-02e4e7f20c3c.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterActivateFields(var Rec: Record Customer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
