### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnSetFilterCustLedgEntryInValidateAppliesToDocNo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8869]
Hi Team,

In table 81 we need possibility to replace and avoid using standard code. Having event in trigger `OnValidate` of field `Applies-to Doc. No.`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94260672-44295680-ff39-11ea-84c7-709cc0c81fce.png)

    [IntegrationEvent(false, false)]
    local procedure OnSetFilterCustLedgEntryInValidateAppliesToDocNo(var CustLedgEntry: Record "Cust. Ledger Entry"; TempGenJnlLine: Record "Gen. Journal Line"; Rec: Record "Gen. Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
