### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnGetCustomerAccountOnBeforeConfirmCustUseJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8870]
Hi Team,

In table 81 we need possibility to replace and avoid using standard code. Having event with handling in procedure `GetCustomerAccount`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94261098-fcef9580-ff39-11ea-936b-0a1f9766c08e.png)

    [IntegrationEvent(false, false)]
    local procedure OnGetCustomerAccountOnBeforeConfirmCustUseJnlLine(var GenJorunalLine: Record "Gen. Journal Line"; Customer: Record Customer; CurrFieldNo: Integer; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
