### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnAfterGetCustJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8871]
Hi Team,

In table 81 we need possibility to replace and avoid using standard code. Having event with handling in procedure `GetCustomerBalAccount`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94261597-c8c8a480-ff3a-11ea-8d9c-590628107ce4.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetCustJnlLine(var GenJorunalLine: Record "Gen. Journal Line"; Customer: Record Customer; CurrFieldNo: Integer; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
