### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnAfterGetVendJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8872]
Hi Team,

In table 81 we need possibility to replace and avoid using standard code. Having event with handling in procedure `GetVendorBalAccount`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94262271-e5191100-ff3b-11ea-900f-edee195e504b.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetVendJnlLine(var GenJorunalLine: Record "Gen. Journal Line"; Vendor: Record Vendor; CurrFieldNo: Integer; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
