### ISSUE TITLE
[Event Request] Table 368 Dimension Selection Buffer - OnAfterSetDimSelectionChange

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8873]
Hi Team,

In table 368 we need possibility to replace and avoid using standard code. Having event in the end of procedure `SetDimSelectionChange`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94262829-c36c5980-ff3c-11ea-9caa-50527ef897a9.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetDimSelectionChange(var TheDimSelectionBuf: Record "Dimension Selection Buffer"; var GlobalDimSelectionBuf: Record "Dimension Selection Buffer")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
