### ISSUE TITLE
[Additional Parameter Request] Codeunit 60 Sales-Calc. Discount - OnAfterCalcSalesDiscount

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8876]
Hi Team,
In codeunit 60 we need possibility to have additional checks in the procedure `CalculateInvoiceDiscount`. Standard publisher would suit us if it had additional standard parameter `TempVATAmountLine: Record "VAT Amount Line"` and `SalesLine2: Record "Sales Line"`. `OnAfterCalcSalesDiscount` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94268811-61185680-ff46-11ea-97fc-5bf627151645.png)

[IntegrationEvent(false, false)]
local procedure OnAfterCalcSalesDiscount(var SalesHeader: Record "Sales Header"; **var TempVATAmountLine: Record "VAT Amount Line" temporary; var SalesLine2: Record "Sales Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
