### ISSUE TITLE
[Additional Parameter Request] Codeunit 74 Purch.-Get Receipt - OnCreateInvLinesOnBeforeFind

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8878]
Hi Team,
In codeunit 74 we need possibility to have additional checks in the procedure `CreateInvLines`. Standard publisher would suit us if it had additional standard parameter `IsHandled: Boolean` with exit functionality. `OnCreateInvLinesOnBeforeFind` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94272045-2f55be80-ff4b-11ea-850a-ec8350537589.png)

[IntegrationEvent(false, false)]
local procedure OnCreateInvLinesOnBeforeFind(var PurchRcptLine: Record "Purch. Rcpt. Line"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
