### ISSUE TITLE
GetODataV4Url from "Web Service Aggregate" not accessable

### ISSUE THREAD

**Issue by hendrik244** [Microsoft/ALAppExtensions#888]
**Is your feature request related to a problem? Please describe.**
Hi everyone,
i just noticed that i cannot use function "GetODataV4Url" of table "Web Service Aggregate" .
Same for "GetODataUrl". "GetSOAPUrl" is accessable.
So you can't get any WebService URL without bothering the user.

**Describe the solution you'd like**
Is it possible to make this function reachable?

Best Regards,

Hendrik

**Comment by darjoo** [comment]
Hi @hendrik244,
These functions were made external and will be available in the April release :)
