### ISSUE TITLE
New event in Codeunit Inventory Profile Offsetting - CalcOrderQty function

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#8880]
Hi, 

Please can we have an event adding to the CalcOrderQty function in the codeunit 99000854 Inventory Profile Offsetting?

This event will allow us to calculate the QtyToOrder differently based on new Reordering Policy.

Suggested format:

OnAfterCalcOrderQty(var QtyToOrder: Decimal; TempSKU: Record Stockkeeping Unit; NeededQty : Decimal;ProjectedInventory : Decimal;SupplyLineNo : Integer)

TIA

Chris

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
