### ISSUE TITLE
[Event Request] Table 121 Purch. Rcpt. Line - OnInsertInvLineFromRcptLineOnAfterCalculateLineDiscountPrct

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8883]
In table 121 Purch. Rcpt. Line, in the procedure InsertInvLineFromRcptLine, we would like to add some code just between PurchLine."Line Discount %" calculation and PurchLine.UpdatePrePaymentAmounts. The best would be an event publisher here : 

![image](https://user-images.githubusercontent.com/34645582/94281511-03d4d300-ff4f-11ea-8878-1551b8e9c880.png)

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/94281550-0d5e3b00-ff4f-11ea-9ff3-b3ec606dfeb1.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
