### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforePayToVendorNoValidate & OnAfterUpdateBuyFromCont

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8885]
In table 38 "Purchase Header", in the trigger OnValidate of field 2 Buy-from Vendor No.", we need two event publishers at some specific places. Exactly here : 

![image](https://user-images.githubusercontent.com/34645582/94288166-6762fe80-ff57-11ea-8944-55eb1c2e832d.png)

And there : 
![image](https://user-images.githubusercontent.com/34645582/94288241-7d70bf00-ff57-11ea-970c-370735b9166b.png)

And the integration events : 
![image](https://user-images.githubusercontent.com/34645582/94288303-8c577180-ff57-11ea-9cfc-e2bff552632d.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
