### ISSUE TITLE
[Event Request] Codeunit 7301 "Whse. Jnl.-Register Line" - OnCodeOnAfterGetLastEntryNo

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8886]
Hi team,

In Codeunit 7301 "Whse. Jnl.-Register Line" procedure `"Code"` we would like to run some additional checks before running further code, for that an event after `GetLastEntryNo` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94401113-c0f34500-0172-11eb-90f3-751bb3725715.png)
```
[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterGetLastEntryNo(WhseJnlLine: Record "Warehouse Journal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
