### ISSUE TITLE
[Event Request] Codeunit::"Inventory Profile Offsetting" - Function FindCombination - OnAfterFindSKUForCombination

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8887]
We like to request the following Event:
Object: Codeunit::"Inventory Profile Offsetting"
Function: FindCombination
Publisher Event: OnAfterFindSKUForCombination
Reason: To implement custom business logic
Where is the event placed:
if SKU.FindSet then begin
            repeat
                IsHandled := false;
                **OnAfterFindSKUForCombination(SKU, TempSKU, IsHandled);**
                if not IsHandled then begin
                    PlanningGetParameters.AdjustInvalidSettings(SKU);
                    if (SKU."Safety Stock Quantity" <> 0) or (SKU."Reorder Point" <> 0) or
                       (SKU."Reorder Quantity" <> 0) or (SKU."Maximum Inventory" <> 0)

Event Code:
**[IntegrationEvent(false, false)]
    local procedure OnAfterFindSKUForCombination(var SKU: Record "Stockkeeping Unit"; var TempSKU: Record "Stockkeeping Unit"; var IsHandled: Boolean)
    begin
    end;**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
