### ISSUE TITLE
[Event Request] Codeunit::"Inventory Profile Offsetting" - Function SyncTransferDemandWithReqLine - OnAfterSetTransferReqLineFilters

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8888]
We like to request the following Event:
Object: Codeunit::"Inventory Profile Offsetting"
Function: SyncTransferDemandWithReqLine
Publisher Event: OnAfterSetTransferReqLineFilters
Reason: To implement custom business logic
Where is the event placed:
local procedure SyncTransferDemandWithReqLine(var InventoryProfile: Record "Inventory Profile"; LocationCode: Code[10])
    var
        TransferReqLine: Record "Requisition Line";
    begin
        with TransferReqLine do begin
            SetRange("Ref. Order Type", "Ref. Order Type"::Transfer);
            SetRange("Ref. Order No.", InventoryProfile."Source ID");
            SetRange("Ref. Line No.", InventoryProfile."Source Ref. No.");
            SetRange("Transfer-from Code", InventoryProfile."Location Code");
            SetRange("Location Code", LocationCode);
            SetFilter("Action Message", '<>%1', "Action Message"::New);
            **OnAfterSetTransferReqLineFilters(TransferReqLine, InventoryProfile, LocationCode, CurrTemplateName, CurrWorksheetName);**
            if FindFirst then
                TransferReqLineToInvProfiles(InventoryProfile, TransferReqLine);
        end;
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterSetTransferReqLineFilters(var TransferReqLine: Record "Requisition Line"; var InventoryProfile: Record "Inventory Profile"; LocationCode: Code[10]; CurrTemplateName: Code[10]; CurrWorksheetName:

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
