### ISSUE TITLE
[Event Request] Codeunit::"Inventory Profile Offsetting" - Function PlanItem - OnAfterPlanSKU

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8889]
We like to request the following Event:
Object: Codeunit::"Inventory Profile Offsetting"
Function: PlanItem
Publisher Event: OnAfterPlanSKU
Reason: To implement custom business logic
Where is the event placed:
else
                                Error(Text001, SelectStr(NextState + 1, NextStateTxt));
                        end;
                end;
                **OnAfterPlanSKU(TempSKU, ReqLine);**
            until TempSKU.Next = 0;
        SetAcceptAction(TempSKU."Item No.");
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterPlanSKU(var TempSKU: Record "Stockkeeping Unit"; var ReqLine: Record "Requisition Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
