### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function GetNextPutAwayDocument - OnBeforeGetNextPutAwayDocument

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8890]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: GetNextPutAwayDocument
Publisher Event: OnBeforeGetNextPutAwayDocument
Reason: To implement custom business logic
Where is the event placed:
procedure GetNextPutAwayDocument(var WhseActivHeader: Record "Warehouse Activity Header"): Boolean
    var
        IsHandled: Boolean;
        Success: Boolean;
    begin
        **IsHandled := true;
        OnBeforeGetNextPutAwayDocument(WhseRcptHeader, WhseActivHeader, Success, IsHandled);
        if IsHandled then
            exit(Success);**
        exit(CreatePutAway.GetNextPutAwayDocument(WhseActivHeader));
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetNextPutAwayDocument(var WhseReceiptHeader: Record "Warehouse Receipt Header"; var WhseActivHeader: Record "Warehouse Activity Header"; var Success: Boolean; var IsHandled: Boolean)
    begin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
