### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function InitSourceDocumentLines - OnBeforeInitSourceDocumentLines

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8891]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: InitSourceDocumentLines
Publisher Event: OnBeforeInitSourceDocumentLines
Reason: To implement custom business logic
Where is the event placed:
local procedure InitSourceDocumentLines(var WhseRcptLine: Record "Warehouse Receipt Line")
    var
        WhseRcptLine2: Record "Warehouse Receipt Line";
        TransLine: Record "Transfer Line";
        SalesLine: Record "Sales Line";
        PurchLine: Record "Purchase Line";
        ModifyLine: Boolean;
        **IsHandled: Boolean;**
    begin
        **IsHandled := false;
        OnBeforeInitSourceDocumentLines(WhseRcptLine, IsHandled);
        if IsHandled then
            exit;**
        WhseRcptLine2.Copy(WhseRcptLine);
        with WhseRcptLine2 do begin

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeInitSourceDocumentLines(var WhseReceiptLine: Record "Warehouse Receipt Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
