### ISSUE TITLE
[Event Request] Codeunit::"WMS Management" - Function SetZoneAndBins - OnBeforeSetZoneAndBins

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8892]
We like to request the following Event:
Object: Codeunit::"WMS Management"
Function: SetZoneAndBins
Publisher Event: OnBeforeSetZoneAndBins
Reason: To implement custom business logic
Where is the event placed:
local procedure SetZoneAndBins(ItemJnlLine: Record "Item Journal Line"; var WhseJnlLine: Record "Warehouse Journal Line"; ToTransfer: Boolean)
    **var
        IsHandled: Boolean;**
    begin
        **IsHandled := false;
        OnBeforeSetZoneAndBins(ItemJnlLine, WhseJnlLine, ToTransfer, IsHandled);
        if IsHandled then
            exit;**
        with ItemJnlLine do

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetZoneAndBins(ItemJnlLine: Record "Item Journal Line"; var WhseJnlLine: Record "Warehouse Journal Line"; ToTransfer: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
