### ISSUE TITLE
[Event Request] Codeunit::"Workflow Response Handling" - Function ReleaseDocument - OnBeforeReleaseDocument

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8893]
We like to request the following Event:
Object: Codeunit::"Workflow Response Handling"
Function: ReleaseDocument
Publisher Event: OnBeforeReleaseDocument
Reason: To implement custom business logic
Where is the event placed:
local procedure ReleaseDocument(var Variant: Variant)
    var
        ApprovalEntry: Record "Approval Entry";
        WorkflowWebhookEntry: Record "Workflow Webhook Entry";
        ReleasePurchaseDocument: Codeunit "Release Purchase Document";
        ReleaseSalesDocument: Codeunit "Release Sales Document";
        ReleaseIncomingDocument: Codeunit "Release Incoming Document";
        RecRef: RecordRef;
        TargetRecRef: RecordRef;
        Handled: Boolean;
    begin
        **OnBeforeReleaseDocument(Variant);**
        RecRef.GetTable(Variant);
        case RecRef.Number of
            DATABASE::"Approval Entry":

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeReleaseDocument(var Variant: Variant)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.
