### ISSUE TITLE
[Event Request] Codeunit::AddOnIntegrManagement - Function TransferFromReqLineToPurchLine - OnBeforeTransferFromReqLineToPurchLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8894]
We like to request the following Event:
Object: Codeunit::AddOnIntegrManagement
Function: TransferFromReqLineToPurchLine
Publisher Event: OnBeforeTransferFromReqLineToPurchLine
Reason: To implement custom fields and functions
Where is the event placed:
procedure TransferFromReqLineToPurchLine(var PurchOrderLine: Record "Purchase Line"; ReqLine: Record "Requisition Line")
    var
        MfgSetup: Record "Manufacturing Setup";
        WorkCenter: Record "Work Center";
        ProdOrderRtngLine: Record "Prod. Order Routing Line";
        **IsHandled: Boolean;**
    begin
        **OnBeforeTransferFromReqLineToPurchLine(PurchOrderLine, ReqLine, IsHandled);
        if IsHandled then
            exit;**
        with ReqLine do begin

Event Code:
[IntegrationEvent(false, false)]
    procedure OnBeforeTransferFromReqLineToPurchLine(var PurchOrderLine: Record "Purchase Line"; var ReqLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
