### ISSUE TITLE
[Event Request] Codeunit::ArchiveManagement - Function CalcApplnAmount - OnBeforeGetNextVersionNo

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8895]
We like to request the following Event:
Object: Codeunit::ArchiveManagement
Function: CalcApplnAmount
Publisher Event: OnBeforeGetNextVersionNo
Reason: To implement custom business logic
Where is the event placed:
procedure GetNextVersionNo(TableId: Integer; DocType: Option Quote,"Order",Invoice,"Credit Memo","Blanket Order","Return Order"; DocNo: Code[20]; DocNoOccurrence: Integer): Integer
    var
        SalesHeaderArchive: Record "Sales Header Archive";
        PurchHeaderArchive: Record "Purchase Header Archive";
        **IsHandled: Boolean;**
        **CustomNextVersionNo: Integer;**
    begin
        **OnBeforeGetNextVersionNo(TableId, DocType, DocNo, DocNoOccurrence, IsHandled, CustomNextVersionNo);
        if IsHandled then
            exit(CustomNextVersionNo);**
        case TableId of
            DATABASE::"Sales Header":
                begin
                    SalesHeaderArchive.LockTable();

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetNextVersionNo(TableId: Integer; DocType: Option Quote,"Order",Invoice,"Credit Memo","Blanket Order","Return Order"; DocNo: Code[20]; DocNoOccurrence: Integer; var IsHandled: Boolean; var Next

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
