### ISSUE TITLE
[Event Request] Database::"Assemble-to-Order Link" - Function ChangeUOM - OnBeforeChangeUOM

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8896]
We like to request the following Event:
Object: Database::"Assemble-to-Order Link"
Function: ChangeUOM
Publisher Event: OnBeforeChangeUOM
Reason: To implement custom business logic
Where is the event placed:
local procedure ChangeUOM(NewUOMCode: Code[10])
    **var
        IsHandled: Boolean;**
    begin
        **OnBeforeChangeUOM(AsmHeader, NewUOMCode, IsHandled);
        if IsHandled then
            exit;**
        if AsmHeader."Unit of Measure Code" = NewUOMCode then
            exit;
        AsmHeader.Validate("Unit of Measure Code", NewUOMCode);
    end;

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeChangeUOM(var AssemblyHeader: Record "Assembly Header"; NewUOMCode: Code[10]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
