### ISSUE TITLE
[Event Request] Database::"Assemble-to-Order Link" - Function NeedsSynchronization - OnBeforeNeedsSynchronization

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#8897]
We like to request the following Event:
Object: Database::"Assemble-to-Order Link"
Function: NeedsSynchronization
Publisher Event: OnBeforeNeedsSynchronization
Reason: To implement custom business logic
Where is the event placed:
local procedure NeedsSynchronization(SalesLine: Record "Sales Line"): Boolean
    var
        IsHandled: Boolean;
        IsNeedSynchronization: Boolean;
    begin
        GetAsmHeader;
        AsmHeader.CalcFields("Reserved Qty. (Base)");
        **OnBeforeNeedsSynchronization(AsmHeader, SalesLine, IsNeedSynchronization, IsHandled);
        if IsHandled then
            exit(IsNeedSynchronization);**

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeNeedsSynchronization(AssemblyHeader: Record "Assembly Header"; SalesLine: Record "Sales Line"; var IsNeedSynchronization: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
