### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - field "Pay-to Vendor No." trigger OnValidate

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8898]
We are migrating our code from NAV 2018 to BC16.4, and we would like to add some code in the table 38 Purchase Header, in the trigger OnValidate of field 4 "Pay-to Vendor No.". To do so, we need two event publisher in this trigger, like this : 

![image](https://user-images.githubusercontent.com/34645582/94412393-0b2bf480-017a-11eb-8e38-9060ef55cee3.png)
![image](https://user-images.githubusercontent.com/34645582/94412456-197a1080-017a-11eb-8df4-daf1377c0d20.png)

With this integration events : 
![image](https://user-images.githubusercontent.com/34645582/94412515-28f95980-017a-11eb-8c21-602323e5c8ea.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
