### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnBeforeUpdateWhseDocuments

### ISSUE THREAD

**Issue by SCreanor** [Microsoft/ALAppExtensions#89]
As part of our extension we need to be notified before the Warehouse Receipt and Warehouse Shipment are updated in Codeunit 90.

Could a new event please be added as per shown below:

Event Signature:
**LOCAL [IntegrationEvent] OnBeforeUpdateWhseDocuments**(WhseReceive : Boolean;VAR WhseRcptHeader : Record "Warehouse Receipt Header";WhseShip : Boolean;VAR WhseShptHeader : Record "Warehouse Shipment Header")

Code Insertion:
![image](https://user-images.githubusercontent.com/39544344/47278576-d28e5280-d615-11e8-8107-9f4488c4ad4e.png)

**Comment by AlexanderYakunin** [comment]
You already have event OnBeforePostUpdateWhseDocuments(WhseRcptHeader) in WhsePostRcpt. Same for shipment.

**Comment by SCreanor** [comment]
Reviewed the code and agree that this event can be utilised, closing the request
