### ISSUE TITLE
[Event Request] Codeunit 7301 "Whse. Jnl.-Register Line" - OnInitWhseEntryOnAfterGetToBinContent

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8900]
Hi team,

in Codeunit 7301 "Whse. Jnl.-Register Line" procedure `InitWhseEntry` we would like to run some custom code after bin content is created, for that an event after checking if `ToBinContent` exists would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94403986-ed10c500-0176-11eb-8deb-ae78be477f02.png)
```
[IntegrationEvent(false, false)]
local procedure OnInitWhseEntryOnAfterGetToBinContent(var WhseEntry: Record "Warehouse Entry"; var ItemTrackingMgt: Codeunit "Item Tracking Management"; var WhseJnlLine: Record "Warehouse Journal Line"; var WhseReg: Record "Warehouse Register"; var WhseEntryNo: Integer; var Bin: Record Bin)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
