### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - field "Order Adress Code" trigger OnValidate

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8901]
In table 38 "Purchase header", in the trigger OnValidate of the field 95 "Order Adress Code", we would like to add some come at a very specific moment of the trigger. To do so, we need an event publisher (modestly called OnValidateOrderAddressCodeOnBeforeShipToNameUpdate) at this moment : 

![image](https://user-images.githubusercontent.com/34645582/94418417-ac6a7900-0181-11eb-96d2-6a6bdff49a84.png)

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/94418585-e176cb80-0181-11eb-8168-a663c906070b.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
