### ISSUE TITLE
bug in xml buffer 

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#8902]
i believe to have found a bug in the xml buffer.
when creating xml files with multiple namespaces, i add the elements with "namespace:elementname"
but when  creating the file, the namespace is not always added to the file.
the problem occurs when going in to level 3 of the xml structure.

the problem lies in this function:
 procedure GetNamespaceUriByPrefix(NamespacePrefix: Text): Text[250]
    var
        TempResultXMLBuffer: Record "XML Buffer" temporary;
    begin
        TempResultXMLBuffer.CopyImportFrom(Rec);

        TempResultXMLBuffer.SetRange(Type, TempResultXMLBuffer.Type::Attribute);
        TempResultXMLBuffer.SetRange(Name, 'xmlns:' + NamespacePrefix);
        if TempResultXMLBuffer.FindFirst then
            exit(TempResultXMLBuffer.Value);
    end;

when going in for the first level, there is no filter on "parent entry no."
when going in for the second level ,there is a filter on "parent entry no." = 1, so it still finds the namespaces
when going in for the third level, there is a filter on "parent entry no." = x, so it does not find namespaces anymore.

there should be a
TempResultXMLBuffer.reset
or
TempResultXMLBuffer.SetRange("parent entry no.")
before the setranges.
then the fitler on parent entry no. wil be cleared and the namespaces will be found.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
