### ISSUE TITLE
[Event Request] OnBeforeInsertTransferHeader in report "Create Subcontr. Return Order"

### ISSUE THREAD

**Issue by ghost** [microsoft/ALAppExtensions#8904]
Hello, please add the following event in the "Create Subcontr. Return Order" report (Italian localization).

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertTransferHeader(ToLocationCode: Code[10]; var TransferHeader: Record "Transfer Header"; Vendor: Record Vendor; var IsHandled: Boolean)
    begin
    end;
```

It should be raised in the InsertTransferHeader procedure, as follows

```
    procedure InsertTransferHeader(ToLocationCode: Code[10])
    var
        IsHandled: Boolean;
    begin
        OnBeforeInsertTransferHeader(ToLocationCode, TransferHeader, Vendor, IsHandled);
        if IsHandled then
          exit;
        [ ... ]
    end;
```

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
