### ISSUE TITLE
[Additional Parameter Request] Codeunit 7301 "Whse. Jnl.-Register Line" - OnDeleteFromBinContentOnAfterSetFiltersForBinContent

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8906]
Hi team,

In Codeunit 7301 "Whse. Jnl.-Register Line" procedure `DeleteFromBinContent` we would like to change some code to work with custom functionality. For that the event `OnDeleteFromBinContentOnAfterSetFiltersForBinContent` would be good if some additional parameters were added to be able to copy the functionality of standard code completely:
![image](https://user-images.githubusercontent.com/49302698/94425667-fad54300-0194-11eb-9c94-3be51cc5de6d.png)

[IntegrationEvent(false, false)]
local procedure OnDeleteFromBinContentOnAfterSetFiltersForBinContent(var BinContent: Record "Bin Content"; WarehouseEntry: Record "Warehouse Entry"**; var WhseJnlLine: Record "Warehouse Journal Line"; var WhseReg: Record "Warehouse Register"; var WhseEntryNo: Integer; var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
