### ISSUE TITLE
[Event Request] Codeunit 7301 "Whse. Jnl.-Register Line" - OnBeforeInsertBinContent

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8907]
Hi team,

In Codeunit 7301 "Whse. Jnl.-Register Line" procedure `InsertToBinContent` we would like to perform some additional checks before executing function code, for that an event at start of function would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94426998-13465d00-0197-11eb-95e8-0ca741458308.png)
```
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertBinContent(var WhseEntry: Record "Warehouse Entry")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
