### ISSUE TITLE
[Additional Parameter Request] Codeunit 7310 Whse.-Shipment Release - OnBeforeReopen

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8908]
Hi Team,

In codeunit 7310 we need possibility to have additional checks in the procedure `Reopen`. Standard publisher would suit us if it had additional standard parameter IsHandled: Boolean with exit functionality. `OnBeforeReopen` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94428156-e8f59f00-0198-11eb-88f1-3311e935f1ca.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeReopen(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
