### ISSUE TITLE
[Event Request] Codeunit 7310 Whse.-Shipment Release - OnBeforePickWkshLineCheckIfEmpty

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8909]
Hi Team,

In codeunit 7310 we need possibility to replace and avoid using standard code. Having event with handling in procedure `Reopen`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94430720-09bff380-019d-11eb-998a-35b9475dc939.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforePickWkshLineCheckIfEmpty(var WhseShptHeader: Record "Warehouse Shipment Header"; var PickWkshLine: Record "Whse. Worksheet Line"; var IsHandled: Boolean)

**Comment by StanPesotskiy** [comment]
Please use the existing event OnBeforeReopen(WhseShptHeader, IsHandled);
IsHandled will be added by https://github.com/microsoft/ALAppExtensions/issues/8908
