### ISSUE TITLE
[Event Request] codeunit 1250 "Match General Journal Lines": GetMatchScore

### ISSUE THREAD

**Issue by BartPermentier** [microsoft/ALAppExtensions#8910]
- Object: codeunit 1250 "Match General Journal Lines"

- Function: FindMatchingCustEntry

- Integration Event:

`OnAfterGetMatchScore(GenJournalLine: Record "Gen. Journal Line"; CustLedgerEntry: Record "Cust. Ledger Entry"; var Score: Integer);`

- Location: Just after the score is set

![image](https://user-images.githubusercontent.com/24684493/94435132-075c9a00-019b-11eb-98c3-d12bb7b50cb9.png)

**It's very important that the Score is var!**

Edit: Wrong Location

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
