### ISSUE TITLE
[Event Request] Codeunit 7302 "WMS Management" - OnBinLookUpOnAfterBinSetRange

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8911]
Hi team,

In Codeunit 7302 "WMS Management" procedure `BinLookUp` we would like to add some additional filters to `Bin` before `PAGE.RunModal(0, Bin)` for that an event before PAGE.RunModal would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94432370-573d6000-019f-11eb-9a22-6f74ff346a4a.png)
```
[IntegrationEvent(false, false)]
local procedure OnBinLookUpOnAfterBinSetRange(var Bin: Record Bin);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
