### ISSUE TITLE
[Additional Parameter Request] Codeunit 7310 Whse.-Shipment Release - OnBeforeWhsePickRequestInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8912]
Hi Team,

In codeunit 7310 we need possibility to have additional checks in the procedure `CreateWhsePickRequest`. Standard publisher would suit us if it had additional standard parameter `IsHandled: Boolean`. `OnBeforeWhsePickRequestInsert` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94437181-11d06100-01a6-11eb-8f7d-8f48fce2aaea.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeWhsePickRequestInsert(var WhsePickRequest: Record "Whse. Pick Request"; WarehouseShipmentHeader: Record "Warehouse Shipment Header"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
