### ISSUE TITLE
[Event Request] Codeunit 7303 "Whse. Jnl.-Register" - OnBeforeCode

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8913]
Hi team,

In Codeunit 7303 "Whse. Jnl.-Register" procedure `"Code"` we would like to run custom code instead of standard to register Whse. Journal, for that an event at start of procedure would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94434746-e9933300-01a2-11eb-937e-6a8c83fad213.png)
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCode(var WhseJnlLine: Record "Warehouse Journal Line"; var TempJnlBatchName: Code[10]; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
