### ISSUE TITLE
[Event Request] Codeunit 7304 "Whse. Jnl.-Register Batch" - OnCodeOnAfterWhseJnlBatchGet

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8915]
Hi team,

In Codeunit 7304 "Whse. Jnl.-Register Batch" procedure "Code" we would like to run some custom code after `WhseJnlBatch.Get`, for that an event would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94438569-f6feec00-01a7-11eb-9a86-134b4add625f.png)
```
[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterWhseJnlBatchGet(WhseJnlBatch: Record "Warehouse Journal Batch")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
