### ISSUE TITLE
[Event Request] Codeunit 7304 "Whse. Jnl.-Register Batch" - OnCodeOnBeforeCommit

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8916]
Hi team,

In Codeunit 7304 "Whse. Jnl.-Register Batch" procedure `"Code"` we would like to perform some additional checks before `Commit()`, for that an event handler would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94439310-ebf88b80-01a8-11eb-8cee-d617996d8f4d.png)
```
[IntegrationEvent(false, false)]
local procedure OnCodeOnBeforeCommit(var WhseJnlRegisterLine: Codeunit "Whse. Jnl.-Register Line"; var IsHandled:Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
