### ISSUE TITLE
[Event Request] Codeunit 7302 "WMS Management" - OnCheckPutAwayAvailabilityOnBeforeConfirm

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8919]
Hi team,

In Codeunit 7302 "WMS Management" procedure `CheckPutAwayAvailability` we would like to add additional checks before `Confirm`, for that an event handler would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94439749-78a34980-01a9-11eb-849a-d5eaea66923f.png)
```
[IntegrationEvent(false, false)]
local procedure OnCheckPutAwayAvailabilityOnBeforeConfirm(var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
