### ISSUE TITLE
[Event Request] Codeunit 7304 "Whse. Jnl.-Register Batch" - OnCheckLinesOnBeforeCheckBin

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8922]
Hi team,

In Codeunit 7304 "Whse. Jnl.-Register Batch" procedure `CheckLines` we would like to run some custom code before `CheckBin`, for that an event before `CheckBin` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94443833-4ea05600-01ae-11eb-84a5-57a88f87a637.png)
```
[IntegrationEvent(false, false)]
local procedure OnCheckLinesOnBeforeCheckBin(WhseJnlLine: Record "Warehouse Journal Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
