### ISSUE TITLE
[Event Request] Codeunit 7304 "Whse. Jnl.-Register Batch" - OnCheckBinOnBeforeCheckIncreaseBin

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8923]
Hi team,

In Codeunit 7304 "Whse. Jnl.-Register Batch" procedure `CheckBin` we would like to run some checks before `Bin.CheckIncreaseBin`, for that an event before `CheckIncreaseBin` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94444145-ab037580-01ae-11eb-8785-e211760821a8.png)
```
[IntegrationEvent(false, false)]
local procedure OnCheckBinOnBeforeCheckIncreaseBin(var TempBinContentBuffer: Record "Bin Content Buffer" temporary; var Bin: Record Bin; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
