### ISSUE TITLE
[Event Request] Codeunit 7304 "Whse. Jnl.-Register Batch" - OnCheckItemAvailabilityOnBeforeGetResponseOrDefault

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8924]
Hi team,

In Codeunit 7304 "Whse. Jnl.-Register Batch" procedure `CheckItemAvailability` we would like to perform additional checks before running `ConfirmManagement.GetResponseOrDefault`, for that an event before checking Qty on inventory would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94444686-3ed54180-01af-11eb-8f50-076a6c9690ec.png)
```
[IntegrationEvent(false, false)]
local procedure OnCheckItemAvailabilityOnBeforeGetResponseOrDefault(var ReservedQtyOnInventory: Decimal; var QtyOnWarehouseEntries: Decimal; var WhseJnlLineQty: Decimal; var TempSKU: Record "Stockkeeping Unit" temporary)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
