### ISSUE TITLE
[Additional Parameter Request] Codeunit 7313 Create Put-Away - OnCreateBinContentOnBeforeNewBinContentInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8925]
Hi Team,

In codeunit 7313 we need possibility to have additional checks in the procedure `CreateBinContent`. Standard publisher would suit us if it had additional standard parameter `var Bin: Record Bin` and `var OldBinContent: Record "Bin Content"`. `OnCreateBinContentOnBeforeNewBinContentInsert` would be perfect solution:

![image](https://user-images.githubusercontent.com/70525691/94448754-f66c5280-01b3-11eb-8d2a-25da9aa7a19b.png)

[IntegrationEvent(false, false)]
local procedure OnCreateBinContentOnBeforeNewBinContentInsert(var BinContent: Record "Bin Content"; PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; **var Bin: Record Bin; var OldBinContent: Record "Bin Content"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
