### ISSUE TITLE
[Event Request] codeunit 5616 "Depreciation Calculation" – New event "OnBeforeCalcDeprDays"

### ISSUE THREAD

**Issue by ubiznok** [microsoft/ALAppExtensions#8926]
Could we have a new event “OnAfterCalcDeprDays” in function “DeprDays”, Codeunit 5616 "Depreciation Calculation"?

    procedure DeprDays(StartingDate: Date; EndingDate: Date; Year365Days: Boolean): Integer
    var
        StartingDay: Integer;
        EndingDay: Integer;
        StartingMonth: Integer;
        EndingMonth: Integer;
        StartingYear: Integer;
        EndingYear: Integer;

        *** start new code ***
        IsHandled: Boolean;
        NumberOfDays: Integer;
        *** stop new code ***

    begin
	// Both days are inclusive
        if EndingDate < StartingDate then
            exit(0);
        if (StartingDate = 0D) or (EndingDate = 0D) then
            exit(0);
        if Year365Days then
            exit(DeprDays365(StartingDate, EndingDate));
        StartingDay := Date2DMY(StartingDate, 1);
        EndingDay := Date2DMY(EndingDate, 1);
        StartingMonth := Date2DMY(StartingDate, 2);
        EndingMonth := Date2DMY(EndingDate, 2);
        StartingYear := Date2DMY(StartingDate, 3);
        EndingYear := Date2DMY(EndingDate, 3);
        if Date2DMY(StartingDate, 1) = 31 then
            StartingDay := 30;
        if Date2DMY(EndingDate + 1, 1) = 1 then
            EndingDay := 30;

    *** start new code ***
        IsHandled := false;
        OnAfterCalcDeprDays(StartingDate; EndingDate; NumberOfDays; IsHandled)
        if IsHandled then
            exit(NumberOfDays);
    *** stop new code ***

        exit(1 + EndingDay - StartingDay + 30 * (EndingMonth - StartingMonth) +
          360 * (EndingYear - StartingYear));
    end;

    *** start new code ***
        [IntegrationEvent(false, false)]
        local procedure OnAfterCalcDeprDays(StartingDate: Date; EndingDate: Date; var NumberOfDays: Integer; var IsHandled: Boolean)
        begin
        end;
    *** stop new code ***

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
