### ISSUE TITLE
[Additional Parameter Request] Codeunit 7306 "Whse.-Act.-Register (Yes/No)" - OnBeforeCode

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8927]
Hi team,

In Codeunit 7306 "Whse.-Act.-Register (Yes/No)" procedure `"Code"` we would like to run custom code inplace of standard, for that we would like the `IsHandled: Boolean` variable to be added as parameter to standard event `OnBeforeCode`:
![image](https://user-images.githubusercontent.com/49302698/94520821-9fa75d00-0235-11eb-8465-703846b47e99.png)
[IntegrationEvent(false, false)]
local procedure OnBeforeCode(var WarehouseActivityLine: Record "Warehouse Activity Line"**; var IsHandled:Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
