### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnCodeOnBeforeCreateRegActivHeader

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8928]
Hi team,

In Codeunit 7307 "Whse.-Activity-Register" procedure `"Code"` we would like to run some custom code after warehosue activity lines are checked, for that an event after running `CheckLines` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94523447-e13a0700-0239-11eb-81ce-a6ea9ed4c675.png)
```
[IntegrationEvent(false, false)]
local procedure OnCodeOnBeforeCreateRegActivHeader(var WhseActivHeader: Record "Warehouse Activity Header")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
