### ISSUE TITLE
[Enum Request] for Incoming Documents

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#8929]
It would be nice If we somehow could extend the supported Documents in the Table Incoming Documents to “Sales Orders” or more.  At this point its very hard to use either the Incoming Documents and the data Exchange Framework. 

Only solutions is to read/pull the file as a Blob from Blob Storage and manually create the Incoming Document record, and add additional Actions for other workflows only, however the Option field cannot be extended, any chance this will be converted to Enums soon?
Its related to 

- Table 130 "Incoming Document" Field 15 "Document Type" -> Incoming Document Type 
  (However there is already a Enum with the same name but its not applied to Table 130??)

- Table 130 "Incoming Document" Field 18 Status -> Incoming Document Status Enum

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
