### ISSUE TITLE
[Event Request] New Event Codeunit Transfer Order Post "OnAfterPostItemJnlLine "

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#8930]
local procedure PostItemJnlLine(var TransLine3: Record "Transfer Line"; TransRcptHeader2: Record "Transfer Receipt Header"; TransRcptLine2: Record "Transfer Receipt Line")
    begin

        (...)
        OnBeforePostItemJournalLine(ItemJnlLine, TransLine3, TransRcptHeader2, TransRcptLine2, SuppressCommit);
        ItemJnlPostLine.RunWithCheck(ItemJnlLine);

        **OnAfterPostItemJnlLine(ItemJnlLine,TransLine3, TransRcptHeader2, TransRcptLine2);  //New Even**t
    end;

[IntegrationEvent(false, false)]
    local procedure OnAfterPostItemJnlLine (ItemJnlLine: Record "Item Journal Line";var TransLine: Record "Transfer Line";var TransRcptHeader: "Transfer Receipt Header";var TransRcptLine: "Transfer Receipt Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
