### ISSUE TITLE
[Change Request] module QR-Bill Management for Switzerland

### ISSUE THREAD

**Issue by JPicard90** [microsoft/ALAppExtensions#8931]
Hi team !
We need those procedures to be public on module in subject (so please remove the “internal” property from the declaration of the procedures) on the following objects:
 
Codeunit "Swiss QR-Bill Mgt.", procedures:
-	AllowedCurrencyCode
-	FindCustLedgerEntry
-	FilterCustLedgerEntry
-	GenerateImage
-	FormatPaymentReference
-	FormatIBAN
-	GetCreditorInfo
-	AddLine
-	GetUltimateDebitorInfo
-	AddLineIfNotBlanked

Table "Swiss QR-Bill Buffer", procedures:
-	InitBuffer
-	SetSourceRecord
-	AddBufferRecord
-	CheckLimitForUnstrAndBillInfoText
-	PrepareForPrint

we need this in order to replicate the QR code invoicing inside the invoice report
unfortunately we cannot made a workaround (both codeunit and table uses some dotnet function and our environment is SaaS)

thanks for your collaboration

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
