### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnCodeOnAfterUpdWhseActivHeader

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8932]
Hi team,

In Codeunit 7307 "Whse.-Activity-Register" procedure `"Code"` we would like to run some custom code before changes are commited, for that an event after updating `WhseActivHeader` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94529464-72ad7700-0242-11eb-8a66-37594420e22e.png)
```
[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterUpdWhseActivHeader(RegisteredWhseActivHeader: Record "Registered Whse. Activity Hdr."; RegisteredWhseActivLine: Record "Registered Whse. Activity Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
