### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnRecreatePurchLinesOnBeforePurchLineTestField

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8933]
We are migrating our code from NAV 2018 to BC16.4. In the table 38 Purchase Header, in the procedure RecreatePurchLines, we used to add a lot of our code. To do so, we need a IsHandled Flag and an event publisher here : 

![image](https://user-images.githubusercontent.com/34645582/94542948-b9529f80-0249-11eb-992c-67690d687190.png)

With the integration event : 
![image](https://user-images.githubusercontent.com/34645582/94542456-1f8af280-0249-11eb-87c1-c67476930d4f.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
