### ISSUE TITLE
[Event Request] handled pattern in CU 226 CustEntry-Apply Posted Entries

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#8935]
Hi App Team,

In our vertical solution we need to change some standard behaviour in application of cust.ledger entries. To that end we would like to apply the Handled-pattern in the procedure Apply.

Suggested code:
procedure Apply(CustLedgEntry: Record "Cust. Ledger Entry"; DocumentNo: Code[20]; ApplicationDate: Date): Boolean
    var
        PaymentToleranceMgt: Codeunit "Payment Tolerance Management";
        Handled: Boolean;
    begin

        with CustLedgEntry do begin
            Handled := false;
            OnBeforeApplyPaymentTolerancePmtTolCust(Handled, CustLedgEntry, PaymentToleranceMgt, PreviewMode);

            if not handled then
                if (not PreviewMode) then
                    if not PaymentToleranceMgt.PmtTolCust(CustLedgEntry) then
                        exit(false);

            Get("Entry No.");

            if ApplicationDate = 0D then
                ApplicationDate := GetApplicationDate(CustLedgEntry)
            else
...

Event signature:
[IntegrationEvent(false, false)]
local procedure OnBeforeApplyPaymentTolerancePmtTolCust(var Handled: boolean; CustLedgEntry: Record "Cust. Ledger Entry"; var PaymentToleranceMgt: Codeunit "Payment Tolerance Management"; PreviewMode: Boolean)
begin
end;

**Comment by RomanZanizdra** [comment]
Hi @tomddlc . Couple of questions.
1) What is the codeunit "Pmt. Tolerance Mgt. L365"? I cannot find it.
2) There is no SuppressCommit variable in Apply function.
3) Are you sure you don't need var for codeunit parameter? Then what is the purpose to pass it in event?

**Comment by tomddlc** [comment]
Hi Roman,
Sorry - I rreported that too fast...
You are absolutely right - the code has now been updated.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
