### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnRecreatePurchLinesOnAfterTempPurchLineInsert

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8936]
We are migrating our code from NAV 2018 to BC16.4. In the table 38 Purchase Header, in the procedure RecreatePurchLines, we used to add a lot of our code. To do so, we need an event publisher here :

![image](https://user-images.githubusercontent.com/34645582/94544146-2ca8e100-024b-11eb-85d7-77c98273a550.png)

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/94543997-02efba00-024b-11eb-9db3-62d3f9d790cc.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
