### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnRecreatePurchLinesOnBeforePurchLineInit

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8937]
We are migrating our code from NAV 2018 to BC16.4. In the table 38 Purchase Header, in the procedure RecreatePurchLines, we used to add a lot of our code. To do so, we need a IsHandled Flag and an event publisher here :

![image](https://user-images.githubusercontent.com/34645582/94547162-30d6fd80-024f-11eb-98f2-c16e1a2204ee.png)

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/94547194-3d5b5600-024f-11eb-8218-ca635584a055.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
