### ISSUE TITLE
[Event Request] Codeunit 7313 Create Put-away - OnBeforeCalcCubageAndWeight

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8938]
Hi Team,

In codeunit 7313 we need possibility to replace and avoid using standard code. Having event with handling in procedure `CalcAvailCubageAndWeight`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94548602-a2b44480-0259-11eb-8cac-deffe307f521.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcCubageAndWeight(var Bin: Record Bin; var AvailPerCubageBase: Decimal; var AvailPerWeightBase: Decimal; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
