### ISSUE TITLE
[Event Request] Codeunit 7318 Bin Create - OnBeforeBinCreate

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8939]
Hi Team,

In codeunit 7318 we need possibility to replace and avoid using standard code. Having event with handling in procedure `BinCreate`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94548771-e149ff00-0259-11eb-9ed6-7465de4bcda3.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeBinCreate(var Bin: Record Bin; BinCreationWorksheetLine: Record "Bin Creation Worksheet Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
