### ISSUE TITLE
[Event Request] Codeunit 7320 Whse. Undo Quantity - OnAfterUpdateWhseRcptLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8940]
Hi Team,

In codeunit 7320 we need possibility to replace and avoid using standard code. Having event in the end of procedure `UpdateWhseRcptLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94549111-5ddcdd80-025a-11eb-83dd-5feb4708aec3.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateWhseRcptLine(var PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; var WarehouseReceiptLine: Record "Warehouse Receipt Line")

**Comment by StanPesotskiy** [comment]
`        OnAfterUpdateWhseRcptLine(PostedWhseRcptLine, WhseRcptLine);`
