### ISSUE TITLE
[Event Request] Codeunit 8611 Config. Package Management - OnModifyRecordDataFieldsOnAfterRecRefModify

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8941]
Hi Team,

In codeunit 8611 we need possibility to replace and avoid using standard code. Having event in the procedure `ModifyRecordDataFields`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94549512-01c68900-025b-11eb-87cf-0c8f4998ad53.png)

    [IntegrationEvent(false, false)]
    procedure OnModifyRecordDataFieldsOnAfterRecRefModify(var RecRef: RecordRef)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
