### ISSUE TITLE
[Additional Parameter Request] Codeunit 99000830 Create Reserv. Entry - OnTransferReservEntryOnAfterUpdateItemTracking

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8944]
Hi Team,

In codeunit 99000830 we need possibility to have additional checks in the procedure `TransferReservEntry`. Custom publisher requested in ticket #8395 would suit us if it had additional parameter `TransferQty: Decimal`. 

![image](https://user-images.githubusercontent.com/70525691/94551060-6e428780-025d-11eb-9cb9-8348c0d649e0.png)

[IntegrationEvent(false, false)]
local procedure OnTransferReservEntryOnAfterUpdateItemTracking(var ReservationEntry: Record "Reservation Entry"; OldReservEntry: Record "Reservation Entry"; **TransferQty: Decimal**;var IsHandled: Boolean);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
