### ISSUE TITLE
[Event Request] Codeunit 99000831 Reservation Engine Mgt. - OnBeforeGetActivePointerFields

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8945]
Hi Team,

In codeunit 99000831 we need possibility to replace and avoid using standard code. Having event with handling in the procedure `GetActivePointerFields`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94551350-e315c180-025d-11eb-8238-e51d7704971f.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetActivePointerFields(TableID: Integer; var PointerFieldIsActive: Array[6] of Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
