### ISSUE TITLE
[Event Request] Codeunit 99000832 Sales Line-Reserve - OnSetupGetGetUserSetup

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8946]
Hi Team,

In codeunit 99000832 we need possibility to replace and avoid using standard code. Having event with handling in the procedure `CreateReservation`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94554385-a8faee80-0262-11eb-8ff3-b416ec010b66.png)

    [IntegrationEvent(false, false)]
    local procedure OnSetupGetGetUserSetup(var SalesLine: Record "Sales Line";var ShouldExit: boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
