### ISSUE TITLE
[Event Request] Codeunit 99000832 Sales Line-Reserve - OnBeforeVerifyQuantity

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8947]
Hi Team,

In codeunit 99000832 we need possibility to replace and avoid using standard code. Having event with handling in the procedure `VerifyQuantity`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94554522-de9fd780-0262-11eb-94bc-31ba966f224f.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeVerifyQuantity(var NewSalesLine: Record "Sales Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
