### ISSUE TITLE
[Event Request] Codeunit 99000832 Sales Line-Reserve - OnBeforeTransferSalesLineToItemJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8948]
Hi Team,

In codeunit 99000832 we need possibility to replace and avoid using standard code. Having event with handling in the procedure `TransferSalesLineToItemJnlLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94555086-b82e6c00-0263-11eb-9ec6-fb7c9cde0471.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferSalesLineToItemJnlLine(OldReservEntry: Record "Reservation Entry"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
