### ISSUE TITLE
[Event Request] Codeunit 99000832 Sales Line-Reserve - CallItemTracking

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8949]
Hi Team,

In codeunit 99000832 we need possibility to replace and avoid using standard code. Having event in the end of procedure `CallItemTracking`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94555544-69350680-0264-11eb-9901-8e3d4f9421d1.png)

    [IntegrationEvent(false, false)]
    local procedure OnCallItemTrackingOnBeforeItemTrackingLinesRunModal(var ItemTrackingLines: Page "Item Tracking Lines"; SalesLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
