### ISSUE TITLE
Event Request Codeunit 12 Function:InitGLEntry

### ISSUE THREAD

**Issue by krishnaGottuparthi** [Microsoft/ALAppExtensions#895]
Event Request in Codeunit 12 for Function:InitGLEntry

OnBeforeInitGLEntry(GLEntry,GenJnlLine);

![image](https://user-images.githubusercontent.com/35251581/51389968-f0efe580-1b53-11e9-8388-e385c267f8e2.png)

![image](https://user-images.githubusercontent.com/35251581/51389933-d453ad80-1b53-11e9-9c38-78525a052c2d.png)

It would be great if this event is added

Thanks & Regards,
Krishna

**Comment by AlexanderYakunin** [comment]
Please explain what you would like to do with this event? There is statement GLEntry.INIT below, so only GLEntry."Entry No." can be assigned by this event! This is already controlled by NextEntryNo, but you don't ask for this in your event?
