### ISSUE TITLE
[Event Request] Codeunit 99000833 Req. Line-Reserve - OnBeforeVerifyChangeReqLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8950]
Hi Team,

In codeunit 99000833 we need possibility to replace and avoid using standard code. Having event with handling in the procedure `VerifyChange`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94556299-861e0980-0265-11eb-86bd-0511ee3748fe.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeVerifyChangeReqLine(var NewReqLine: Record "Requisition Line"; var OldReqLine: Record "Requisition Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
