### ISSUE TITLE
[Event Request] Codeunit 99000834 Purch. Line-Reserve - OnCalcVerifyReservTaboo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8951]
Hi Team,

In codeunit 99000834 we need possibility to replace and avoid using standard code. Having event in the end of procedure `OnCalcVerifyReservTaboo`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94556660-1e1bf300-0266-11eb-80e0-020487138ea8.png)

    [IntegrationEvent(false, false)]
    local procedure OnCalcVerifyReservTaboo(var PurchLine: Record "Purchase Line"; var ItemTrackingForm: Page "Item Tracking Lines")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
