### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnRecreatePurchLinesOnBeforeTransferSavedFields

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8952]
We are migrating our code from NAV 2018 to BC16.4. In the table 38 Purchase Header, in the procedure RecreatePurchLines, we used to add a lot of our code. To do so, we need a IsHandled Flag and an event publisher here :

![image](https://user-images.githubusercontent.com/34645582/94556787-f4f76480-025d-11eb-964a-a081610262e6.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/94557045-54ee0b00-025e-11eb-95b4-1d66e1b8bc68.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
