### ISSUE TITLE
[Event Request] Codeunit 5063 ArchiveManagement - OnBeforeArchiveSalesDocument

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8953]
Hi Team,

In codeunit 5063 we need possibility to replace and avoid using standard code. Having event with handling in the procedure `ArchiveSalesDocument`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94564140-4c063500-0270-11eb-8e1d-2ff1ea2cfc48.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeArchiveSalesDocument(var SalesHeader: Record "Sales Header"; ConfirmText: Text; ArchivedText: Text; HideDialog: Boolean; IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
