### ISSUE TITLE
[Event Request] Codeunit 5459 JSON Management - OnBeforeAddJPropertyToJObject

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8954]
Hi Team,

In codeunit 5459 we need possibility to replace and avoid using standard code. Having event with handling in the procedure `AddJPropertyToJObject`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94565177-88866080-0271-11eb-9065-e64b3baf6e8d.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddJPropertyToJObject(var JProperty: DotNet "JProperty"; var JObject: DotNet "JObject"; propertyName: Text; value: Variant; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
