### ISSUE TITLE
[Change Request] Pricing Functionality 

### ISSUE THREAD

**Issue by ahughesdxc** [microsoft/ALAppExtensions#8962]
In V17 a new procedure TestHeadersValue has been added to table 7001 "Price List Line"
This procedure checks that certain fields on the line match the corresponding value from the header

This was not the case in V16
In V16 you could have one "Price List Header" record called SALESPRCIES with a 100,000 prices all with different Source Types and Source No. and starting dates and ending dates

Now in V17 it would seem you need to have a "Price List Header" for every grouping of the following fields
- Status
- "Currency Code"
- "Starting Date"
- "Ending Date"
- "Price Includes VAT"
- "VAT Bus. Posting Gr. (Price)"
- "Source Type"
- "Source No." 

For a customer with 100,00+ prices this means they will need 20,000 plus header records which will just make things really messy and hard to manage

You should be able to setup a price header with most field options being set to ALL or Blank
Any field on the header that has a value of ALL or Blank can then be changed on the lines which would drastically reduce the number of header records that will need to be created and make things easier to manage

**Comment by StanPesotskiy** [comment]
The purpose of the price list header is to combine similar price lines into groups that can be structured well and can help managing prices. Looks opposite what you claim. 
With your sample you expect to have 5 price lines per price list and 20000 price lists. That is a mess, I agree.
Though there is a way out. You can create an extension with a page like a price worksheet where no headers needed at all and which works for you. 
If you need some events that would help you avoid unnecessary checks in W1 code, you post a request here and we implement those events.
