### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnAfterUpdateWhseDocHeader

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8963]
Hi team,

In Codeunit 7307 "Whse.-Activity-Register" procedure `UpdateWhseDocHeader` we would like to run some custom code, for that an event at end of procedure code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94570123-27618b80-0277-11eb-8cae-ea9e7ce00765.png)
```
[IntegrationEvent(false, false)]
local procedure OnAfterUpdateWhseDocHeader(WhseActivLine: Record "Warehouse Activity Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
