### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnCheckBinOnBeforeCheckIncreaseBin

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8964]
Hi team,

In Codeunit 7307 "Whse.-Activity-Register" procedure `CheckBin` we would like to run some custom code before running `Bin.CheckIncreaseBin`, for that an event with handler before that procedure is ran would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94649378-3b4fd080-02fd-11eb-95ba-c2e4d5ce735d.png)
```
[IntegrationEvent(false, false)]
local procedure OnCheckBinOnBeforeCheckIncreaseBin(var TempBinContentBuffer: Record "Bin Content Buffer" temporary; var Bin: Record Bin; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
