### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnSetPointerOnAfterWhseItemTrkgLineSetSource

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8965]
Hi team,

In Codeunit 7307 "Whse.-Activity-Register" procedure `SetPointer` we would like to run some custom code, for that an event after `WhseItemTrkgLine.SetSource` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94650658-ce8a0580-02ff-11eb-947a-c058a01abfd0.png)
```
[IntegrationEvent(false, false)]
local procedure OnSetPointerOnAfterWhseItemTrkgLineSetSource(WhseActivLine: Record "Warehouse Activity Line"; WhseDocType2: Option; var WhseItemTrkgLine: Record "Whse. Item Tracking Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
