### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnAfterCheckLines

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#8966]
Hi team,

In Codeunit 7307 "Whse.-Activity-Register" procedure `CheckLines` we would like to run some custom code after the procedure code is done, for that an event at end of procedure would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/94652321-828c9000-0302-11eb-835a-bf79f70fab27.png)
```
[IntegrationEvent(false, false)]
local procedure OnAfterCheckLines(var WarehouseActivityHeader: Record "Warehouse Activity Header"; var WarehouseActivityLine: Record "Warehouse Activity Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
