### ISSUE TITLE
[Event request] Codeunit 7000 "Sales Price Calc. Mgt." - FindSalesLinePrice

### ISSUE THREAD

**Issue by criorza** [microsoft/ALAppExtensions#8968]
Hi team,

In codeunit 7000 "Sales Price Calc. Mgt." procedure FindSalesLinePrice we need the following event available.

![image](https://user-images.githubusercontent.com/39953348/94670540-fafb4d00-0312-11eb-9a4b-5212aceda84e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindSalesLineResPrice(var SalesLine: Record "Sales Line"; var ResPrice: Record "Resource Price")
    begin
    end;

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
