### ISSUE TITLE
[Event Request] Codeunit 400 "SMTP Mail" OnBeforeAddRecipients

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8970]
Hi Team,

In codeunit 400, please provide the possibility to have **Handler** on **OnBeforeAddRecipients** event in **AddRecipients** procedure

![image](https://user-images.githubusercontent.com/57799519/94675346-33ad1d80-0337-11eb-8d51-0e03830ffecc.png)

**Event**:
LOCAL   [IntegrationEvent] OnBeforeAddRecipients(VAR Recipients: Text;VAR IsHandled:   Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
