### ISSUE TITLE
[Event Request] Codeunit 408 "DimensionManagement" OnBeforeCheckDimValue

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8971]
Hi Team,

In codeunit 408, please provide the possibility to have **OnBeforeCheckDimValue** event in **CheckDimValue** procedure

![image](https://user-images.githubusercontent.com/57799519/94677270-42490400-033a-11eb-9b09-fe7b056d4048.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeCheckDimValue(DimCode : Code[20];DimValCode : Code[20];VAR IsChecked: Boolean;VAR IsHandled : Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
