### ISSUE TITLE
[Event Request] Codeunit 455 "Job Queue User Handler" OnBeforeJobShouldBeRescheduled

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8972]
Hi Team,

In codeunit 455, please provide the possibility to have **OnBeforeJobShouldBeRescheduled** event in **JobShouldBeRescheduled** procedure

![image](https://user-images.githubusercontent.com/57799519/94681351-eb92f880-0340-11eb-9ce9-c966b570af98.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeJobShouldBeRescheduled (VAR JobQueueEntry : Record "Job Queue Entry"; VAR ReturnVal: Boolean; VAR IsHandled : Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
