### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnBeforeCalcApplnAmount

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8973]
procedure CalcApplnAmount()
    begin

>>>OnBeforeCalcApplnAmount(Rec, GenJnlLine, AppliedEmplLedgEntry, CalcType, ApplnType);

        AppliedAmount := 0;
        PmtDiscAmount := 0;
        DifferentCurrenciesInAppln := false;
        .
        .
        .

>>>[IntegrationEvent(false, false)]
    local procedure OnBeforeCalcApplnAmount(var EmplLedgerEntry: Record "Employee Ledger Entry"; var GenJournalLine: Record "Gen. Journal Line"; var AppliedEmplLedgerEntry: Record "Employee Ledger Entry"; CalculationType: Option; ApplicationType: Option)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
