### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnAfterCalcApplnAmount

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8974]
procedure CalcApplnAmount()
.
.
.
                    end;
                end;
        end;

>>>OnAfterCalcApplnAmount(Rec, AppliedAmount, ApplyingAmount);

    end;

    local procedure CalcApplnRemainingAmount(Amt: Decimal): Decimal
    var
        ApplnRemainingAmount: Decimal;
    begin
        ValidExchRate := true;
        if ApplnCurrencyCode = "Currency Code" then
            exit(Amt);

.
.
.

>>>[IntegrationEvent(false, false)]
    local procedure OnAfterCalcApplnAmount(EmplLedgerEntry: Record "Employee Ledger Entry"; var AppliedAmount: Decimal; var ApplyingAmount: Decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
