### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnBeforeHandledChosenEntries

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8975]
local procedure HandlChosenEntries(Type: Option Direct,GenJnlLine; CurrentAmount: Decimal; CurrencyCode: Code[10]; PostingDate: Date)
    var
    .
    .
    .
    begin
>>>IsHandled := false;
        OnBeforeHandledChosenEntries(Type, CurrentAmount, CurrencyCode, PostingDate, AppliedEmplLedgEntry, IsHandled);
        if IsHandled then
            exit;

        if not AppliedCustLedgEntry.FindSet(false, false) then
            exit;
    .
    .
    .

>>>[IntegrationEvent(TRUE, false)]
    local procedure OnBeforeHandledChosenEntries(Type: Option Direct,GenJnlLine; CurrentAmount: Decimal; CurrencyCode: Code[10]; PostingDate: Date; var AppliedEmplLedgerEntry: Record "Employee Ledger Entry"; var IsHandled: Boolean)
    begin
    end;

**Comment by StanPesotskiy** [comment]
This is the method's signature as we see it now:
local procedure HandlChosenEntries(Type: Option Direct,GenJnlLine; CurrentAmount: Decimal)

Are you also asking for parameters CurrencyCode and PostingDate to be added?

**Comment by aobsgit** [comment]
I'm sorry, my mistake. No need for additional parameters:

>>>IsHandled := false;
OnBeforeHandledChosenEntries(Type, CurrentAmount, AppliedEmplLedgEntry, IsHandled);
if IsHandled then
exit;


>>>[IntegrationEvent(TRUE, false)]
local procedure OnBeforeHandledChosenEntries(Type: Option Direct,GenJnlLine; CurrentAmount: Decimal; var AppliedEmplLedgerEntry: Record "Employee Ledger Entry"; var IsHandled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
