### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnBeforePostDirectApplication

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8976]
local procedure PostDirectApplication(PreviewMode: Boolean)
    var
        .
        .
        .
>>>IsHandled: Boolean;
    
       begin

>>>IsHandled := false;
        OnBeforePostDirectApplication(Rec, PreviewMode, IsHandled);
        if IsHandled then
            exit;

        if CalcType = CalcType::Direct then begin
        .
        .
        .

>>>[IntegrationEvent(false, false)]
    local procedure OnBeforePostDirectApplication(var EmplLedgerEntry: Record "Employee Ledger Entry"; PreviewMode: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
