### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnAfterCalcApplnAmountToApply

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8977]
local procedure CalcApplnAmountToApply(AmountToApply: Decimal): Decimal
    var
        ApplnAmountToApply: Decimal;
    begin
        ValidExchRate := true;

        if ApplnCurrencyCode = "Currency Code" then
            exit(AmountToApply);

        if ApplnDate = 0D then
            ApplnDate := "Posting Date";
        ApplnAmountToApply :=
          CurrExchRate.ApplnExchangeAmtFCYToFCY(
            ApplnDate, "Currency Code", ApplnCurrencyCode, AmountToApply, ValidExchRate);

>>>OnAfterCalcApplnAmountToApply(Rec, ApplnAmountToApply);

        exit(ApplnAmountToApply);
    end;

>>> [IntegrationEvent(false, false)]
    local procedure OnAfterCalcApplnAmountToApply(EmplLedgerEntry: Record "Employee Ledger Entry"; var ApplnAmountToApply: Decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
