### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnAfterCalcApplnRemainingAmount

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8978]
local procedure CalcApplnRemainingAmount(Amt: Decimal): Decimal
    var
        ApplnRemainingAmount: Decimal;
    begin
        ValidExchRate := true;
        if ApplnCurrencyCode = "Currency Code" then
            exit(Amt);

        if ApplnDate = 0D then
            ApplnDate := "Posting Date";
        ApplnRemainingAmount :=
          CurrExchRate.ApplnExchangeAmtFCYToFCY(
            ApplnDate, "Currency Code", ApplnCurrencyCode, Amt, ValidExchRate);

>>>OnAfterCalcApplnRemainingAmount(Rec, ApplnRemainingAmount);

        exit(ApplnRemainingAmount);
    end;

>>>[IntegrationEvent(false, false)]
    local procedure OnAfterCalcApplnRemainingAmount(EmplLedgerEntry: Record "Employee Ledger Entry"; var ApplnRemainingAmount: Decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
