### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnBeforeSetApplyingEmplLedgEntry

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8981]
procedure SetApplyingEmplLedgEntry()
    var
        Employee: Record Employee;
    begin

>>>OnBeforeSetApplyingEmplLedgEntry(AppliedEmplLedgEntry, GenJnlLine);

        case CalcType of
            CalcType::Direct:
    .
    .
    .

>>>    [IntegrationEvent(true, false)]
    local procedure OnBeforeSetApplyingEmplLedgEntry(var ApplyingEmplLedgEntry: Record "Employee Ledger Entry"; GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
