### ISSUE TITLE
[Event Request] PAGE 234 "Apply Employee Entries" OnSetEmplApplIdAfterCheckAgainstApplnCurrency

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8982]
procedure SetEmplApplId()
    begin
        if (CalcType = CalcType::GenJnlLine) and (TempApplyingEmplLedgEntry."Posting Date" < "Posting Date") then
            Error(
              EarlierPostingDateErr, TempApplyingEmplLedgEntry."Document Type", TempApplyingEmplLedgEntry."Document No.",
              "Document Type", "Document No.");

        if TempApplyingEmplLedgEntry."Entry No." <> 0 then
            GenJnlApply.CheckAgainstApplnCurrency(
              ApplnCurrencyCode, "Currency Code", GenJnlLine."Account Type"::Employee, true);

>>>OnSetCustApplIdAfterCheckAgainstApplnCurrency(Rec, CalcType, GenJnlLine);
        
        EmplLedgEntry.Copy(Rec);
        CurrPage.SetSelectionFilter(EmplLedgEntry);

        if GenJnlLineApply then
            EmplEntrySetApplID.SetApplId(EmplLedgEntry, TempApplyingEmplLedgEntry, GenJnlLine."Applies-to ID")
        else
            EmplEntrySetApplID.SetApplId(EmplLedgEntry, TempApplyingEmplLedgEntry, '');

        ActionPerformed := EmplLedgEntry."Applies-to ID" <> '';
        CalcApplnAmount;
    end;

>>>   [IntegrationEvent(false, false)]
    local procedure OnSetEmplApplIdAfterCheckAgainstApplnCurrency(var EmplLedgerEntry: Record "Employee Ledger Entry"; CalcType: Option; GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
