### ISSUE TITLE
[Visibility change] PAGE 234 "Apply Employee Entries" method CalcApplnAmount

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8983]
>>>OLD CODE

    local procedure CalcApplnAmount()
    begin
    .
    .
    .

>>>NEW CODE

    procedure CalcApplnAmount()
    begin

    .
    .
    .

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
