### ISSUE TITLE
[Visibility change] PAGE 234 "Apply Employee Entries" method CheckRounding

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#8984]
>>>OLD CODE

    local procedure CheckRounding()
    begin

>>>NEW CODE

    procedure CheckRounding()
    begin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
