### ISSUE TITLE
[Additional Parameter Request] Codeunit 99000845 Reservation Management - OnBeforeAutoReserve

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8985]
Hi Team,

In codeunit 99000845 we need possibility to have additional checks in the procedure `AutoReserve`. Custom publisher requested in ticket #6782 would suit us if it had additional parameter `IsHandled: Boolean`.

OnBeforeAutoReserve(VAR CalcReservEntry : Record "Reservation Entry"; VAR FullAutoReservation : Boolean;VAR Description : Text[100];VAR AvailabilityDate : Date;VAR MaxQtyToReserve : Decimal;VAR MaxQtyToReserveBase : Decimal; **var IsHandled: Boolean**)

```pascal
    procedure AutoReserve(var FullAutoReservation: Boolean; Description: Text[100]; AvailabilityDate: Date; MaxQtyToReserve: Decimal; MaxQtyToReserveBase: Decimal)
    var
        SalesLine: Record "Sales Line";
        RemainingQtyToReserve: Decimal;
        RemainingQtyToReserveBase: Decimal;
        i: Integer;
        StopReservation: Boolean;
        IsHandled: Boolean;
    begin
        // 01 23.03.20 CZIE DEVOPS-1572 Remove dependency to diva 
        OnBeforeAutoReserveOnBeforeCheckSourceType(CalcReservEntry,FullAutoReservation,Description,AvailabilityDate,MaxQtyToReserve,MaxQtyToReserveBase, IsHandled);
        if IsHandled then
            exit;
        // 01 23.03.20 CZIE DEVOPS-1572 Remove dependency to diva end             

        CalcReservEntry.TestField("Source Type");
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
