### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - OnDeleteReservEntriesOnBeforeDeleteReservEntries

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8986]
Hi Team,

In codeunit 99000845 we need possibility to replace and avoid using standard code. Having event with handling in the beginning of procedure `DeleteReservEntries`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94698384-ef734a80-0341-11eb-833e-82f1631940de.png)

    [IntegrationEvent(false, false)]
    local procedure OnDeleteReservEntriesOnBeforeDeleteReservEntries(CalcReservEntry: Record "Reservation Entry"; var CalcReservEntry2: Record "Reservation Entry"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
