### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - OnBeforeDeleteItemTrackingConfirm

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8987]
Hi Team,

In codeunit 99000845 we need possibility to replace and avoid using standard code. Having event with handling in the beginning of procedure `DeleteItemTrackingConfirm`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94698764-4ed15a80-0342-11eb-964e-2e658c09444a.png)

    [IntegrationEvent(true, false)]
    local procedure OnBeforeDeleteItemTrackingConfirm(var CalcReservEntry2: Record "Reservation Entry";var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
