### ISSUE TITLE
parameter request - codeunit 12 "Gen. Jnl.-Post Line" - OnPostGLAccOnBeforeInsertGLEntry() - Balancing

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#8988]
In

    local procedure PostGLAcc(GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)

we see this event published:

            IsHandled := false;
            OnPostGLAccOnBeforeInsertGLEntry(GenJnlLine, GLEntry, IsHandled);
            if not IsHandled then
                InsertGLEntry(GenJnlLine, GLEntry, true);

We want to be able to set/unset fields on the `GLEntry` created from the `GenJnlLine`, but in a way that requires knowing whether it's going to the 'main' G/L `Account No.` or to the `Bal. Account No.` (e.g. so we only set a flag on the 'main' `GLEntry`). However, there seems to be no way to discern this, at least not easily.

Therefore, please pass `Balancing` to the subscribers, so we can use that to determine what to do (or not) - by updating the signature of `OnPostGLAccOnBeforeInsertGLEntry()` to

    [IntegrationEvent(true, false)]
    local procedure OnPostGLAccOnBeforeInsertGLEntry(var GenJournalLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; Balancing: Boolean; var IsHandled: Boolean)
    begin
    end;

and calling it like

            OnPostGLAccOnBeforeInsertGLEntry(GenJnlLine, GLEntry, Balancing, IsHandled);

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
