### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - OnSetSourceForSalesLineOnAfterUpdateReservation

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8989]
Hi Team,

In codeunit 99000845 we need possibility to replace and avoid using standard code. Having event in the end of procedure `SetSourceForSalesLine`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94699328-e0d96300-0342-11eb-94f2-fb85472db13a.png)

    [IntegrationEvent(true, false)]
    local procedure OnSetSourceForSalesLineOnAfterUpdateReservation(var CalcReservEntry: Record "Reservation Entry"; SalesLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
