### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" OnBeforePostItemLine

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8990]
Hi Team,

In codeunit 90, please provide the possibility to have **OnBeforePostItemLine** event in **PostItemLine** procedure

![image](https://user-images.githubusercontent.com/57799519/94698093-982ba500-0356-11eb-8f27-90dcfc94b738.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforePostItemLine(PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header"; PurchRcptHeader: Record “Purch. Rcpt. Header”; RemQtyToBeInvoiced: Decimal)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
