### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - OnBeforeUpdateReservation

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#8991]
Hi Team,

In codeunit 99000845 we need possibility to replace and avoid using standard code. Having event with handling in the beginning of procedure `UpdateReservation`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94699754-58a78d80-0343-11eb-9932-91ab6de527cb.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateReservation(var SourceRecRef: RecordRef; var ReservEntry: Record "Reservation Entry"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
