### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforeSetDefaultPurchaser

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#8992]
We are migrating our code from NAV 2018 to BC16.4. In the table 38 Purchase Header, in the procedure SetDefaultPurchaser, we used to add a lot of our code. To do so, we need a IsHandled Flag and an event publisher here :

![image](https://user-images.githubusercontent.com/34645582/94700906-4fff8900-033c-11eb-8418-95f880d7996f.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/94701397-e764dc00-033c-11eb-9f0d-8c003770e643.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
