### ISSUE TITLE
Page 768 "Aged Acc. Receivable Chart", UpdateChartForCustomer 

### ISSUE THREAD

**Issue by CnCollins** [microsoft/ALAppExtensions#8993]
Hi

Is it possible for the OnPrem scope restriction on the UpdateChartForCustomer procedure in the Aged Acc. Receivable Chart Page to be removed?
 
   [Scope('OnPrem')]
    procedure UpdateChartForCustomer(NewCustomerNo: Code[20])
    begin
        CustomerNo := NewCustomerNo;
        UpdateChart;
    end;

TIA

Chris

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
