### ISSUE TITLE
[Event Request] Codeunit 7010 "Purch. Price Calc. Mgt." - FindPurchLinePrice

### ISSUE THREAD

**Issue by criorza** [microsoft/ALAppExtensions#8994]
Hi team,

In codeunit 7010 "Purch. Price Calc. Mgt." procedure FindPurchLinePrice we need the following event available.

![image](https://user-images.githubusercontent.com/39953348/94710808-91496600-0347-11eb-9a48-566bee139e0a.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeResourceFindCost(var ResCost: record "Resource cost";)

Thanks in advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
