### ISSUE TITLE
[Event Request] Codeunit 5404 "Lead-Time Management" OnPlannedEndingDateAndOnBeforeFormatDateFormula & OnPlannedDueDateAndOnBeforeFormatDateFormula

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8995]
Hi Team,

In codeunit 5404, please provide the possibility to have **OnPlannedEndingDateAndOnBeforeFormatDateFormula** event in **PlannedEndingDate** procedure and **OnPlannedDueDateAndOnBeforeFormatDateFormula** event in **PlannedDueDate** procedure.

1. **OnPlannedEndingDateAndOnBeforeFormatDateFormula**
![image](https://user-images.githubusercontent.com/57799519/94773042-9c000b80-03d8-11eb-8931-0e4356918794.png)
**Event:**
LOCAL [Integration Event] OnPlannedEndingDateAndOnBeforeFormatDateFormula(VAR SKU: Record “Stockkeeping Unit”;RefOrderType: option;ItemNo: code[20];DueDate: Date)

2. **OnPlannedDueDateAndOnBeforeFormatDateFormula**
![image](https://user-images.githubusercontent.com/57799519/94773403-555ee100-03d9-11eb-92b5-5c78f9f65877.png)
**Event:**
LOCAL [IntegrationEvent] OnPlannedDueDateAndOnBeforeFormatDateFormula(VAR SKU: Record “Stockkeeping Unit”;RefOrderType: option;EndingDate: Date;ItemNo: Code[20];LocationCode: Code[10])

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
