### ISSUE TITLE
[Event Request] Codeunit 5431 "Calc. Item Plan - Plan Wksh." - OnBeforeGetPlanningComponents & OnAfterGetPlanningComponents

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8996]
Hi Team,

In codeunit 5431, please provide the possibility to have **OnBeforeGetPlanningComponents** and **OnAfterGetPlanningComponents** events in **Code** trigger.

![image](https://user-images.githubusercontent.com/57799519/94774341-5264f000-03db-11eb-9a36-d66d9c4c340d.png)

**Events:**
1. LOCAL [Integration Event] OnBeforeGetPlanningComponents(Item: Record Item)
2. LOCAL [Integration Event] OnAfterGetPlanningComponents(Item: Record Item)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
