### ISSUE TITLE
[Event Request] Codeunit 5777 "Whse. Validate Source Line" OnItemLineVerifyChangeAndOnAfterCalcQtyRemainingToBePicked

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8997]
Hi Team,

Please provide the possibility to have **OnItemLineVerifyChangeAndOnAfterCalcQtyRemainingToBePicked** event in **ItemLineVerifyChange** procedure.

![image](https://user-images.githubusercontent.com/57799519/94776385-44b16980-03df-11eb-9ec6-1ec7fac3ed4a.png)

**Event:**
LOCAL [Integration Event] OnItemLineVerifyChangeAndOnAfterCalcQtyRemainingToBePicked(ProdOrderComp: Record “Prod. Order Component”, VAR QtyRemainingToBePicked: Decimal) 

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
