### ISSUE TITLE
[Event Request] Codeunit 5895"Inventory Adjustment" - OnBeforeOpenWindow & OnBeforeUpdateWindow

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8998]
Hi Team,

Please provide the possibility to have **OnBeforeOpenWindow** event in **OpenWindow** procedure and **OnBeforeUpdateWindow** event in **UpdateWindow** procedure

1. **OnBeforeOpenWindow**
![image](https://user-images.githubusercontent.com/57799519/94777317-eb4a3a00-03e0-11eb-95b9-a7b239a97941.png)
**Event:**
LOCAL [Integration Event] OnBeforeOpenWindow(VAR IsHandled: Boolean)

2. **OnBeforeUpdateWindow**
![image](https://user-images.githubusercontent.com/57799519/94777514-395f3d80-03e1-11eb-942f-f5a7f463ec8a.png)
**Event:**
LOCAL [Integration Event] OnBeforeUpdateWindow(VAR IsHandled: Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
