### ISSUE TITLE
[Event Request] Codeunit 6501 "Item Tracking Data Collection" OnRetrieveLookupDataOnBeforeTransferToTempRec

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#8999]
Hi Team,

In codunit 6501, we have **OnRetrieveLookupDataOnBeforeTransferToTempRec** event in **RetrieveLookupData** procedure but **ItemLedgerEntry** is not coming with reference in the event. As per the clinet requirement we need to apply some additional filters on **ItemLedgerEntry** record.  So please provide the possibility to have "ItemLedgerEntry" with reference in the above specified event.

**Actual Event:**
OnRetrieveLookupDataOnBeforeTransferToTempRec(VAR TempTrackingSpecification : Record "Tracking Specification";VAR TempReservationEntry : Record "Reservation Entry";ItemLedgerEntry : Record "Item Ledger Entry";VAR FullDataSet : Boolean)

**Required Event:**
OnRetrieveLookupDataOnBeforeTransferToTempRec(VAR TempTrackingSpecification : Record "Tracking Specification";VAR TempReservationEntry : Record "Reservation Entry";VAR ItemLedgerEntry : Record "Item Ledger Entry";VAR FullDataSet : Boolean)

_Please backport the same to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
