### ISSUE TITLE
[Function Expose] CheckGLAcc on Table 252

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/ALAppExtensions#900]
We need to call the Function CheckGLAcc on an extension since we added a new configuration field on General Posting Setup. As all other account fields are caling this function, it makes sense to expose it for to be called by added configuration fields.

**Comment by IhorHandziuk** [comment]
Thank you for your request @martinhocosta88, we agree that this function should probably be called for the validation of introduced fields. However, we would prefer the API for codeunits to be as clean as possible to avoid confusion. Please, consider duplicating this function in your own extension.

**Comment by martinhocosta88** [comment]
@IhorHandziuk Is there any method we can use to track if you functions are changed so we can update our replicaded functions. We did that in many places of the code already but I guess it will be a problem to keep a track of MS changes in the future.

**Comment by fvet** [comment]
@IhorHandziuk, We - like other partners - have added extra 'Account' fields on the 'General Posting Setup' that follow the exact same BC pattern for validation:
```
CheckGLAcc(xxx);
IF xxx <> '' THEN BEGIN
  TESTFIELD(xxx)
END;
```
We would like to stay as close as possible to standard BC, thus by re-using the standard functions and avoiding to copy standard functions, not worrying about having to review our duplicated / renamed functions.

**Comment by JesperSchulz** [comment]
We're going to take this one afterall ;-)

**Comment by martinhocosta88** [comment]
Thanks @JesperSchulz
