### ISSUE TITLE
[Event Request] Codeunit 7303 "Whse. Jnl.-Register" OnBeforeRunWhseJnlRegisterBatch

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9000]
Hi Team,

In codeunit 7303, please provide the possibility to have **OnBeforeRunWhseJnlRegisterBatch** event in **Code** trigger. It will helps us on 'Auto Post' scenarios.

![image](https://user-images.githubusercontent.com/57799519/94779736-0fa81580-03e5-11eb-98c8-ca427be86b8e.png)

**Event:**
LOCAL [Integration Event] OnBeforeRunWhseJnlRegisterBatch(VAR IsHandled: Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
