### ISSUE TITLE
[Extensibility] Expose variables as protected in page 414 G/L Balance

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#9001]
In page 414 G/L Balance, the variable **DebitCreditTotals** should become a protected var, in order to be accessible from page extensions. Please consider exposing the other matrix filters too.

It would also be nice to have the variable **Emphasize** become a protected var as well; although it's not really necessary for our logic, it still helps to maintain uniformity in the UI.

Thanks.

**Comment by AndreaDiCeglie** [comment]
any update on this ?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by matteomontanari** [comment]
We found the changes in the daily branch but checking BC17.2 they are missing. 
When will they be available?
