### ISSUE TITLE
[Event Request] Table 18 Customer - OnBeforeValidateEmail

### ISSUE THREAD

**Issue by sukumar5893** [microsoft/ALAppExtensions#9002]
Hi Team,

In table 18, please provide the possibility to have event OnBeforeValidateEmail in field E-mail

![image](https://user-images.githubusercontent.com/26245501/94784050-32d5c380-03eb-11eb-9680-c833d6be0ef5.png)

Event:
![image](https://user-images.githubusercontent.com/26245501/94783156-e63db880-03e9-11eb-88b0-8d9272f02a93.png)

**Please backport to BC14 also.**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
