### ISSUE TITLE
[Event Request] Page 42 Sales Order - OnBeforeValidateShippingOptions

### ISSUE THREAD

**Issue by sukumar5893** [microsoft/ALAppExtensions#9003]
Hi Team,

In Page 42 please provide the possibility to have event **OnBeforeValidateShippingOptions** in field **ShippingOptions**

![image](https://user-images.githubusercontent.com/26245501/94791137-da0b2880-03f4-11eb-91ec-1bdd7f8c5cb9.png)

**Event:**
![image](https://user-images.githubusercontent.com/26245501/94791239-f73ff700-03f4-11eb-9feb-a25633a8d56c.png)

**Please backport to BC14 also.**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
