### ISSUE TITLE
[Event Request] Table 1003 "Job Planning Line" - UpdateUnitCost

### ISSUE THREAD

**Issue by criorza** [microsoft/ALAppExtensions#9004]
Hi team,

In Table 1003 "Job Planning Line" procedure UpdateUnitCost we need the following event available.

            if (Type = Type::Resource) and Res.Get("No.") then begin
                if RetrieveCostPrice then begin
                    ResCost.Init();
                    ResCost.Code := "No.";
                    ResCost."Work Type Code" := "Work Type Code";
                    //-Event-Request
                    OnBeforeResourceFindCost(Rec, ResCost);
                    //+Event-Request
                    CODEUNIT.Run(CODEUNIT::"Resource-Find Cost", ResCost);
                    OnAfterResourceFindCost(Rec, ResCost);
                    "Direct Unit Cost (LCY)" := Round(ResCost."Direct Unit Cost" * "Qty. per Unit of Measure", UnitAmountRoundingPrecision);
                    RetrievedCost := ResCost."Unit Cost" * "Qty. per Unit of Measure";
                    "Unit Cost" := Round(
                        CurrExchRate.ExchangeAmtLCYToFCY(
                          "Currency Date", "Currency Code",
                          RetrievedCost, "Currency Factor"),
                        UnitAmountRoundingPrecisionFCY);
                    "Unit Cost (LCY)" := Round(RetrievedCost, UnitAmountRoundingPrecision);
                end else
                    RecalculateAmounts(Job."Exch. Calculation (Cost)", xRec."Unit Cost", "Unit Cost", "Unit Cost (LCY)");
            end else
                RecalculateAmounts(Job."Exch. Calculation (Cost)", xRec."Unit Cost", "Unit Cost", "Unit Cost (LCY)");

![image](https://user-images.githubusercontent.com/39953348/94792778-c1d9e000-03d9-11eb-99ca-d7bdb8d7b1ba.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeResourceFindCost(var JobPlanningLine: Record "Job Planning Line"; var ResourceCost: Record "Resource Cost")
    begin
    end;

Thanks in advance

**Comment by RomanZanizdra** [comment]
Hi @criorza . 
Some changes came in part of mentioned code due to new sales prices/discounts engine (version 17.0). Could you be so kind to clarify where and what event you need in terms of new code.
