### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateNoOnAfterAssignQtyFromXRec

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9006]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in theField 7 "No.",In the trigger Validate, we need to modify a part of the code. To do so,  we need to add a IsHandled flag in the parameters of the already existing event publisher OnValidateNoOnAfterAssignQtyFromXRec. Like this : 

The declaration of the variable : 
![image](https://user-images.githubusercontent.com/34645582/94798422-e1750680-03e1-11eb-9c65-540e8b9dc0b2.png)

The use of the IsHandled flag : 
![image](https://user-images.githubusercontent.com/34645582/94797971-382e1080-03e1-11eb-8ee5-3f507c178579.png)

And the integration event : 
![image](https://user-images.githubusercontent.com/34645582/94796979-cb664680-03df-11eb-95eb-5deb86f00459.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
