### ISSUE TITLE
[Additional Parameter Request] Codeunit 99000845 Reservation Management - OnAfterAutoReserveOneLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9007]
Hi Team,

In codeunit 99000845 we need possibility to have additional checks in the procedure `AutoReserveOneLine`. Standard publisher `OnAfterAutoReserveOneLine` would suit us if it had additional parameter `CalcReservEntry2: Record "Reservation Entry"` and `Positive: Boolean`. We have noticed that `CalcReservEntry` was added in ticket #6346 , which is great . 

![image](https://user-images.githubusercontent.com/70525691/94800882-e8a21180-03ed-11eb-9d51-cc34ebe7cc81.png)

[IntegrationEvent(false, false)]
local procedure OnAfterAutoReserveOneLine(ReservSummEntryNo: Integer; var RemainingQtyToReserve: Decimal; var RemainingQtyToReserveBase: Decimal; Description: Text[100]; AvailabilityDate: Date; Search: Text[1]; NextStep: Integer; CalcReservEntry: Record "Reservation Entry"; **CalcReservEntry2: Record "Reservation Entry"; Positive: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
