### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnAfterInitVariables

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9008]
Hi Team,

In codeunit 99000854 we need possibility to replace and avoid using standard code. Having event in the end of procedure `InitVariables`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94804646-d4f9a980-03f3-11eb-9211-bd205cb4246f.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitVariables(var InventoryProfile: Record "Inventory Profile")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
