### ISSUE TITLE
COD80 - OnCheckAndUpdateOnAfterSetPostingFlags

### ISSUE THREAD

**Issue by SKeiler** [microsoft/ALAppExtensions#9009]
Hello,

we want to add new lines to a Sales invoice at release. For that the call of the release in COD80 is a little bit late (because before the Ship and Invoice-Flags are already updated). Because of we want to avoid source code duplicates we would need to little changes for Events in COD80.

1. Set the "IncludeSender"-Property for OnCheckAndUpdateOnAfterSetPostingFlags Event to Yes.
![image](https://user-images.githubusercontent.com/45033081/94809781-63216000-03f3-11eb-9903-714ff38e3e53.png)

2. Set the ReleaseSalesDocument-procedure in COD80 to Local = No
![image](https://user-images.githubusercontent.com/45033081/94809928-a085ed80-03f3-11eb-8436-f6a9385a5a31.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
