### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnAfterFindCombination

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9011]
Hi Team,

In codeunit 99000854 we need possibility to replace and avoid using standard code. Having event in the end of procedure `FindCombination`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94810632-f1e6aa80-03fc-11eb-8175-b9a1d15a2366.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterFindCombination(var DemandInvtProfile: Record "Inventory Profile"; var SupplyInvtProfile: Record "Inventory Profile")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
