### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnBeforeInsertTempSKU

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9012]
Hi Team,

In codeunit 99000854 we need possibility to replace and avoid using standard code. Having event with handling in the beginning of procedure `InsertTempSKU`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94810822-35d9af80-03fd-11eb-8ed2-203fe7bcd521.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertTempSKU(var TempSKU: Record "Stockkeeping Unit"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
