### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnAfterTransferPlanningParameters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9013]
Hi Team,

In codeunit 99000854 we need possibility to replace and avoid using standard code. Having event in the end of procedure `TransferPlanningParameters`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94811042-83eeb300-03fd-11eb-9354-906123d46a74.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferPlanningParameters(var SKU: Record "Stockkeeping Unit")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
