### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnPlanItemOnBeforeFindTempSKU

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9014]
Hi Team,

In codeunit 99000854 we need possibility to replace, change filters and avoid using standard code. Having event in the procedure `TransferPlanningParameters`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94811797-88679b80-03fe-11eb-9a3b-ee2b0e3f57ad.png)

    [IntegrationEvent(false, false)]
    local procedure OnPlanItemOnBeforeFindTempSKU(var TempSKU: Record "Stockkeeping Unit")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
