### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnAfterPlanItemSetInvtProfileFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9015]
Hi Team,

In codeunit 99000854 we need possibility to replace, change filters and avoid using standard code. Having event in the end of procedure `PlanItemSetInvtProfileFilters`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94812102-f14f1380-03fe-11eb-8bb6-e847b64d7510.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterPlanItemSetInvtProfileFilters(var DemandInvtProfile: Record "Inventory Profile"; var SupplyInvtProfile: Record "Inventory Profile")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
