### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnFindCombinationOnBeforeFilterDemandAndSupply

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9016]
Hi Team,

In codeunit 99000854 we need possibility to replace, change filters and avoid using standard code. Having event in procedure `FindCombination`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94812876-fc567380-03ff-11eb-8bdb-75711505a0bc.png)

    [IntegrationEvent(false, false)]
    local procedure OnFindCombinationOnBeforeFilterDemandAndSupply(var DemandInvtProfile: Record "Inventory Profile"; var SupplyInvtProfile: Record "Inventory Profile")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
