### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnFindCombinationOnBeforeSKUFindset

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9017]
Hi Team,

In codeunit 99000854 we need possibility to replace, change filters and avoid using standard code. Having event in the beginning of procedure `FindCombination`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94814206-af739c80-0401-11eb-9166-1a3fb8d94db1.png)

    [IntegrationEvent(false, false)]
    local procedure OnFindCombinationOnBeforeSKUFindset(var SKU: Record "Stockkeeping Unit"; var Item: Record Item)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
