### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateQuantityOnBeforeCheckReceiptRelation

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9018]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in theField 15 "Quantity", in the trigger Validate, we need to modify a part of the code. To do so, we need to add an event publisher, OnValidateQuantityOnBeforeCheckReceiptRelation, here :

![image](https://user-images.githubusercontent.com/34645582/94815155-84397f00-03fa-11eb-8665-dd6d31e12f95.png)

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/94814326-79cab580-03f9-11eb-8760-679b3fba688c.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
