### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateFieldQuantityOnAfterPlanPriceCalcByField

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9019]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in theField 15 "Quantity", in the trigger Validate, we need to modify a part of the code. To do so, we need to add an event publisher, OnValidateFieldQuantityOnAfterPlanPriceCalcByField, here :

![image](https://user-images.githubusercontent.com/34645582/94816208-c4e5c800-03fb-11eb-929d-d9ac194d80f9.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/94816419-15f5bc00-03fc-11eb-842e-3562cca778fc.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
