### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnFindCombinationOnBeforeSetState

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9021]
Hi Team,

In codeunit 99000854 we need possibility to replace, change filters and avoid using standard code. Having event in procedure `FindCombination`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94817537-c916e300-0405-11eb-9d85-80d77021cd04.png)

    [IntegrationEvent(false, false)]
    local procedure OnFindCombinationOnBeforeSetState(var TempSKU: Record "Stockkeeping Unit"; var Item: Record Item; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
