### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnBeforeOnValidateQtyToInvoice

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9022]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the trigger OnValidate in the field 17 "Qty. To Invoice", we used to add a lot of our code. To do so, we need a IsHandled Flag and an event publisher. We would prefer this to the trigger OnBeforeOnValidate because we would like to launch the trigger OnValidate on a condition. If the condition is not fulfilled, then we exit the trigger OnValidate thanks to IsHandled. Like this :

![image](https://user-images.githubusercontent.com/34645582/94819577-b6011480-03ff-11eb-8f45-3ff47ff100b2.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/94820137-653deb80-0400-11eb-92a3-aa663b6e7661.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
