### ISSUE TITLE
[Additional Parameter Request] Codeunit 7312 Create Pick - OnCreateWhseDocumentOnBeforeClearFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9023]
Hi Team,

In codeunit 7312 we need possibility to have additional checks in the procedure `CreateWhseDocument`. Standard publisher `OnCreateWhseDocumentOnBeforeClearFilters` would suit us if it had additional parameter `var WhseActivHeader: Record "Warehouse Activity Header"` .

![image](https://user-images.githubusercontent.com/70525691/94822620-83f5af80-040b-11eb-8f5e-a810726fc379.png)

[IntegrationEvent(false, false)]
local procedure OnCreateWhseDocumentOnBeforeClearFilters(var TempWarehouseActivityLine: Record "Warehouse Activity Line" temporary; **var WhseActivHeader: Record "Warehouse Activity Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
