### ISSUE TITLE
[Additional Parameter Request] Codeunit 7312 Create Pick - OnCreateTempActivityLineOnAfterTransferFrom

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9024]
Hi Team,

In codeunit 7312 we need possibility to have additional checks in the procedure `CreateTempActivityLine`. Standard publisher OnCreateTempActivityLineOnAfterTransferFrom would suit us if it had additional parameter `WhseSource: Option` .

![image](https://user-images.githubusercontent.com/70525691/94824931-3464b300-040e-11eb-88c0-92868b0a1b2d.png)

[IntegrationEvent(false, false)]
local procedure OnCreateTempActivityLineOnAfterTransferFrom(var TempWarehouseActivityLine: Record "Warehouse Activity Line" temporary; **WhseSource: Option "Pick Worksheet",Shipment,"Movement Worksheet","Internal Pick",Production,Assembly**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
