### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." OnCopySalesLineAndOnBeforeUpdateSalesLine & OnCopySalesInvLinesToDocAndOnBeforeCopyItemTracking

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9025]
Hi Team,

In codeunit 6620, please provide the possibility to have **OnCopySalesLineAndOnBeforeUpdateSalesLine** event in **CopySalesLine** procedure and **OnCopySalesInvLinesToDocAndOnBeforeCopyItemTracking** event in **CopySalesInvLinesToDoc** procedure

1.**OnCopySalesLineAndOnBeforeUpdateSalesLine**

![image](https://user-images.githubusercontent.com/57799519/94816974-24eb6700-041a-11eb-88b1-75c50aa96805.png)
**Event:**
LOCAL [Integration Event] OnCopySalesLineAndOnBeforeUpdateSalesLine(VAR SalesLine: Record "Sales Line";SalesHeader: Record "Sales Header")

2. **OnCopySalesInvLinesToDocAndOnBeforeCopyItemTracking**

![image](https://user-images.githubusercontent.com/57799519/94824824-0a69bb80-0423-11eb-8ce5-d1ce7a165113.png)
**Event:**
OnCopySalesInvLinesToDocAndOnBeforeCopyItemTracking(FromSalesLineBuf: Record “Sales Line”; ToSalesHeader: Record “Sales Header”; VAR FromSalesInvLine: Record “Sales Invoice Line”; VAR ItemLedgEntryBuf: Record “Item Ledger Entry”; VAR TempTrkgItemLedgEntry: Record “Item Ledger Entry”)

_Please backport the same events to BC14 also._

**Comment by RomanZanizdra** [comment]
Hi @Rambabu-Billuri . We do events only for the latest version which is 17 for now. If you really need event for version 14 please ask support channel for a hotfix.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
