### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateVariantCodeOnBeforeUpdateItemReference

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9026]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the Field 5402 "Variant Code", in the trigger Validate, we used to add our code. To do so, we need a IsHandled Flag and an event publisher here :

![image](https://user-images.githubusercontent.com/34645582/94835109-878c3500-0411-11eb-863a-36a6b19ddcfd.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/94834708-06cd3900-0411-11eb-88f2-0bdef56daf40.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
