### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateRequestedReceiptDateOnBeforeCustomCalendarChange

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9028]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the Field 5790 ""Requested Receipt Date", in the trigger OnValidate, we need to modify a part of the code. To do so, we need to add a IsHandled flag and event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/94899384-800d7000-0493-11eb-97e9-c4a70605c356.png)

And the integration event :
![image](https://user-images.githubusercontent.com/34645582/94899476-b34fff00-0493-11eb-934f-77b17d6cacc3.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by StanPesotskiy** [comment]
```
        field(5790; "Requested Receipt Date"; Date)
        {
            Caption = 'Requested Receipt Date';

            trigger OnValidate()
            var
                CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateRequestedReceiptDate(Rec, xRec, CustomCalendarChange, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
```
