### ISSUE TITLE
[Event Request] Database::"Assembly Line" - Function CheckItemAvailable - OnBeforeCheckItemAvailable

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9029]
We like to request the following Event:
Object: Database::"Assembly Line"
Function: CheckItemAvailable
Publisher Event: OnBeforeCheckItemAvailable
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckItemAvailable(CalledByFieldNo: Integer)
    var
        AssemblySetup: Record "Assembly Setup";
        ItemCheckAvail: Codeunit "Item-Check Avail.";
        IsHandled: Boolean;
    begin
        **OnBeforeCheckItemAvailable(Rec, CalledByFieldNo, IsHandled);
        if IsHandled then
            exit;**
        if not UpdateAvailWarning then
            exit;
        if "Document Type" <> "Document Type"::Order then
            exit;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckItemAvailable(var AssemblyLine: Record "Assembly Line"; CalledByFieldNo: Integer; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
