### ISSUE TITLE
[Event Parameters] OnAfterSetAccNo Cod 5802

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/ALAppExtensions#903]
The event OnAfterSetAccNo Should also send the SourceIsPurchCrMemo as a parameter.

We have the following sample where we need the value of that boolean inside an eventsub:

        CASE InvtPostingBuffer."Account Type" OF
            InvtPostingBuffer."Account Type"::"Direct Cost Applied":
                    IF **SourceIsPurchCrMemo** THEN BEGIN
                       GenPostingSetup.TESTFIELD("PTSS Cr.M Dir. Cost Appl. Acc.");
                       InvtPostingBuffer."Account No." := GenPostingSetup.GetDirectCostAppliedCMAccount;
                    END;

**Comment by AlexanderYakunin** [comment]
Is this country specific? I cannot see SourceIsPurchCrMemo or similar in W1 COD5802.

**Comment by martinhocosta88** [comment]
@AlexanderYakunin You're right is country specific. I'm closing the thread and sorry for the mistake.
