### ISSUE TITLE
[Event Request] Database::"Assembly Line" - Function CopyFromItem - OnBeforeCopyFromItem

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9030]
We like to request the following Event:
Object: Database::"Assembly Line"
Function: CopyFromItem
Publisher Event: OnBeforeCopyFromItem
Reason: To implement custom business logic
Where is the event placed:
local procedure CopyFromItem()
    begin
        **OnBeforeCopyFromItem(Rec);**
        GetItemResource;
        if IsInventoriableItem then begin
            "Location Code" := AssemblyHeader."Location Code";
            Item.TestField("Inventory Posting Group");
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCopyFromItem(var AssemblyLine: Record "Assembly Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
