### ISSUE TITLE
[Event Request] Database::"Assembly Line" - Function CopyFromResource - OnBeforeCopyFromResource

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9031]
We like to request the following Event:
Object: Database::"Assembly Line"
Function: CopyFromResource
Publisher Event: OnBeforeCopyFromResource
Reason: To implement custom business logic
Where is the event placed:
local procedure CopyFromResource()
    begin
        **OnBeforeCopyFromResource(Rec);**
        GetItemResource;
        Resource.TestField("Gen. Prod. Posting Group");
        "Gen. Prod. Posting Group" := Resource."Gen. Prod. Posting Group";
        "Inventory Posting Group" := '';
        Description := Resource.Name;
        "Description 2" := Resource."Name 2";
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCopyFromResource(var AssemblyLine: Record "Assembly Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
