### ISSUE TITLE
[Event Request] Database::"Item Journal Line" - Function InitRevalJnlLine - OnAfterInitRevalJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9032]
We like to request the following Event:
Object: Database::"Item Journal Line"
Function: InitRevalJnlLine
Publisher Event: OnAfterInitRevalJnlLine
Reason: To implement custom business logic
Where is the event placed:
"Location Code" := ItemLedgEntry2."Location Code";
        "Variant Code" := ItemLedgEntry2."Variant Code";
        "Applies-to Entry" := ItemLedgEntry2."Entry No.";
        CopyDim(ItemLedgEntry2."Dimension Set ID");
        **OnAfterInitRevalJnlLine(Rec, ItemLedgEntry2);**
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterInitRevalJnlLine(var ItemJournalLine: Record "Item Journal Line"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
