### ISSUE TITLE
[Event Request] Database::"Item Journal Line" - Function TrackingExists - OnBeforeTrackingExists

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9033]
We like to request the following Event:
Object: Database::"Item Journal Line"
Function: TrackingExists
Publisher Event: OnBeforeTrackingExists
Reason: To implement custom business logic
Where is the event placed:
procedure TrackingExists(): Boolean
    var
        IsTrackingExist: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        **OnBeforeTrackingExists(Rec, IsTrackingExist, IsHandled);
        if IsHandled then
            exit(IsTrackingExist);**
        IsTrackingExist := ("Serial No." <> '') or ("Lot No." <> '');
        exit(IsTrackingExist);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeTrackingExists(var ItemJournalLine: Record "Item Journal Line"; var IsTrackingExist: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by RomanZanizdra** [comment]
Hi @acadonAG-dev . There is already OnAfterTrackingExists(Rec, IsTrackingExist) event where you can update IsTrackingExist as you need.

    procedure TrackingExists() IsTrackingExist: Boolean
    begin
        IsTrackingExist := ("Serial No." <> '') or ("Lot No." <> '');

        OnAfterTrackingExists(Rec, IsTrackingExist);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
