### ISSUE TITLE
[Event Request] Database::"Posted Whse. Receipt Line" - Function CreatePutAwayDoc - OnBeforeCreatePutAwayDoc

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9034]
We like to request the following Event:
Object: Database::"Posted Whse. Receipt Line"
Function: CreatePutAwayDoc
Publisher Event: OnBeforeCreatePutAwayDoc
Reason: To implement custom business logic
Where is the event placed:
procedure CreatePutAwayDoc(var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; AssignedID: Code[50])
    var
        WhseSetup: Record "Warehouse Setup";
        CreatePutAwayFromWhseSource: Report "Whse.-Source - Create Document";
        IsHandled: Boolean;
    begin
        **OnBeforeCreatePutAwayDoc(PostedWhseRcptLine, AssignedID, HideValidationDialog, IsHandled);
        if IsHandled then
            exit;**
        GetLocation(PostedWhseRcptLine."Location Code");
        if not Location."Require Put-away" then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCreatePutAwayDoc(var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; AssignedID: Code[50]; HideValidationDialog: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
