### ISSUE TITLE
[Event Request] Database::"Prod. Order Line" - Function Quantity - OnValidate - OnBeforeQuantityValidate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9035]
We like to request the following Event:
Object: Database::"Prod. Order Line"
Function: Quantity - OnValidate
Publisher Event: OnBeforeQuantityValidate
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                **OnBeforeQuantityValidate(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;**
                "Quantity (Base)" := Quantity * "Qty. per Unit of Measure";
                "Remaining Quantity" := Quantity - "Finished Quantity";
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeQuantityValidate(var Rec: Record "Prod. Order Line"; var xRec: Record "Prod. Order Line"; CurrFieldNo: Integer; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
