### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function CheckReceiptRelation - OnBeforeCheckReceiptRelation

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9036]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: CheckReceiptRelation
Publisher Event: OnBeforeCheckReceiptRelation
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckReceiptRelation()
    var
        PurchRcptLine: Record "Purch. Rcpt. Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        **OnBeforeCheckReceiptRelation(Rec, IsHandled);
        if IsHandled then
            exit;**
        PurchRcptLine.Get("Receipt No.", "Receipt Line No.");
        if (Quantity * PurchRcptLine."Qty. Rcd. Not Invoiced") < 0 then
            FieldError("Qty. to Invoice", Text051);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckReceiptRelation(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
