### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function CheckRetShptRelation - OnBeforeCheckRetShptRelation

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9037]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: CheckRetShptRelation
Publisher Event: OnBeforeCheckRetShptRelation
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckRetShptRelation()
    var
        ReturnShptLine: Record "Return Shipment Line";
        IsHandled: Boolean;
    begin
        **IsHandled := false;
        OnBeforeCheckRetShptRelation(Rec, IsHandled);
        if IsHandled then
            exit;**
        ReturnShptLine.Get("Return Shipment No.", "Return Shipment Line No.");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckRetShptRelation(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
