### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function GetOverheadRateFCY - OnBeforeGetOverheadRateFCY

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9038]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: GetOverheadRateFCY
Publisher Event: OnBeforeGetOverheadRateFCY
Reason: To implement custom business logic
Where is the event placed:
local procedure GetOverheadRateFCY(): Decimal
    var
        Item: Record Item;
        QtyPerUOM: Decimal;
        IsHandled: Boolean;
        ExitValue: Decimal;
    begin
        IsHandled := false;
        **OnBeforeGetOverheadRateFCY(Rec, QtyPerUOM, ExitValue, IsHandled);
        if IsHandled then
            exit(ExitValue);**
        if "Prod. Order No." = '' then
            QtyPerUOM := "Qty. per Unit of Measure"
        else begin
            GetItem(Item);
            QtyPerUOM := UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code");
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetOverheadRateFCY(var PurchaseLine: Record "Purchase Line"; var QtyPerUOM: Decimal; var ExitValue: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
