### ISSUE TITLE
[Event Request] Database::"Job Journal Line" - Function "Variant Code" - OnValidate - OnValidateVariantCodeOnBeforeValidateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9039]
We like to request the following Event:
Object: Database::"Job Journal Line"
Function: "Variant Code" - OnValidate
Publisher Event: OnValidateVariantCodeOnBeforeValidateQuantity
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                if "Variant Code" = '' then begin
                    if Type = Type::Item then begin
                        Item.Get("No.");
                        Description := Item.Description;
                        "Description 2" := Item."Description 2";
                        GetItemTranslation;
                    end;
                    exit;
                end;
                TestField(Type, Type::Item);
                ItemVariant.Get("No.", "Variant Code");
                Description := ItemVariant.Description;
                "Description 2" := ItemVariant."Description 2";
                **IsHandled := false;
                OnValidateVariantCodeOnBeforeValidateQuantity(Rec, xRec, IsHandled);
                if not IsHandled then
                    Validate(Quantity);**
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateVariantCodeOnBeforeValidateQuantity(var JobJournalLine: Record "Job Journal Line"; xJobJournalLine: Record "Job Journal Line"; var IsHandled: Boolean)
    begin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
