### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnDeleteOnBeforePurchaseLineDelete

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9040]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the trigger OnDelete, we need to add a condition to the activation of the procedure WhseValidateSourceLine.PurchaseLineDelete(). To do so, we need to add a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/94902381-5acf3080-0498-11eb-8f53-cf2cccf76704.png)

And the integration event : 
![image](https://user-images.githubusercontent.com/34645582/94902406-63c00200-0498-11eb-9dfd-9d3c2acf994d.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
