### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnCopyFromItemOnBeforeCalcUnitPriceLCY

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9041]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the local procedure CopyFromItem, we need to modify the calculation of "Unit Price (LCY)". To do so, we need to add a IsHandled flag and an event publisher, like this :

The declaration of the variable : 
![image](https://user-images.githubusercontent.com/34645582/94908374-daadc880-04a1-11eb-81e8-ddc9339b1731.png)

The event publisher : 
![image](https://user-images.githubusercontent.com/34645582/94908526-16e12900-04a2-11eb-97cf-6210b171a5ac.png)

And the event integration : 
![image](https://user-images.githubusercontent.com/34645582/94908551-219bbe00-04a2-11eb-9153-acfc4162bc3f.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
