### ISSUE TITLE
[Event Request] - Database "Sales header" - function UpdateShipToAddressFromSellToAddress

### ISSUE THREAD

**Issue by pririis** [microsoft/ALAppExtensions#9046]
local procedure UpdateShipToAddressFromSellToAddress(FieldNumber: Integer)
    begin
        if ("Ship-to Code" = '') and ShipToAddressEqualsOldSellToAddress then
            case FieldNumber of
                FieldNo("Ship-to Address"):
                    "Ship-to Address" := "Sell-to Address";
                FieldNo("Ship-to Address 2"):
                    "Ship-to Address 2" := "Sell-to Address 2";
                FieldNo("Ship-to City"), FieldNo("Ship-to Post Code"):
                    begin
                        "Ship-to City" := "Sell-to City";
                        "Ship-to Post Code" := "Sell-to Post Code";
                        "Ship-to County" := "Sell-to County";
                        "Ship-to Country/Region Code" := "Sell-to Country/Region Code";
                    end;
                FieldNo("Ship-to County"):
                    "Ship-to County" := "Sell-to County";
                FieldNo("Ship-to Country/Region Code"):
                    "Ship-to Country/Region Code" := "Sell-to Country/Region Code";
            end;
    end;

In this function we would like to have an event so it will be possible to handle customer address fields.
F.I.
………
    FieldNo("Ship-to Country/Region Code"):
      "Ship-to Country/Region Code" := "Sell-to Country/Region Code";
    ELSE
      OnUpdateShipToAddressFromSellToAddress(Rec,FieldNumber);
  end;
end;

**Comment by RomanZanizdra** [comment]
Hi @pririis . There are already two events (before and after) fits to your requirement, you can use them.
    local procedure UpdateShipToAddressFromSellToAddress(FieldNumber: Integer)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateShipToAddressFromSellToAddress(Rec, FieldNumber, IsHandled);
        if IsHandled then
            exit;

        if ("Ship-to Code" = '') and ShipToAddressEqualsOldSellToAddress then
            case FieldNumber of
                FieldNo("Ship-to Address"):
                    "Ship-to Address" := "Sell-to Address";
                FieldNo("Ship-to Address 2"):
                    "Ship-to Address 2" := "Sell-to Address 2";
                FieldNo("Ship-to City"), FieldNo("Ship-to Post Code"):
                    begin
                        "Ship-to City" := "Sell-to City";
                        "Ship-to Post Code" := "Sell-to Post Code";
                        "Ship-to County" := "Sell-to County";
                        "Ship-to Country/Region Code" := "Sell-to Country/Region Code";
                    end;
                FieldNo("Ship-to County"):
                    "Ship-to County" := "Sell-to County";
                FieldNo("Ship-to Country/Region Code"):
                    "Ship-to Country/Region Code" := "Sell-to Country/Region Code";
            end;

        OnAfterUpdateShipToAddressFromSellToAddress(Rec, xRec, FieldNumber);
    end;

**Comment by pririis** [comment]
Hi, 
Sorry but i have looked in BC17 and BC16CU04 on premise. In which version do You find this.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by pririis** [comment]
Thanks, 
will it also be included in future CU's for BC16 ?

**Comment by RomanZanizdra** [comment]
@pririis , no. We do events for the latest version which is 17 for now. If you really need this event on the 16 version please reach out   support channel for a hotfix.
