### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnSelectItemEntryOnBeforeSetRangeLocationCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9047]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the local procedure SelectItemEntry, we need to add an ItemLedgEntry.SetRange. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/94923019-7ef03900-04bb-11eb-9ea9-eed4d7fead79.png)

And the event integration : 
![image](https://user-images.githubusercontent.com/34645582/94923054-89aace00-04bb-11eb-82f6-e52c2354fb0b.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
