### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9048]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the local procedure UpdateDirectUnitCostByField, we need to add our code at a specific moment. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/94940192-79065200-04d3-11eb-9d9b-967f87e152a8.png)

And the event integration :
![image](https://user-images.githubusercontent.com/34645582/94940168-6c81f980-04d3-11eb-9596-2cedde05c5bf.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
