### ISSUE TITLE
[Event Request] Table 39 Purchase Line - OnBeforeCheckWarehouse

### ISSUE THREAD

**Issue by sukumar5893** [microsoft/ALAppExtensions#9049]
Hi Team,

InTable 39 please provide the possibility to have event **OnBeforeCheckWarehouse** in procedure **CheckWarehouse**

![image](https://user-images.githubusercontent.com/26245501/94953578-67d63900-0505-11eb-9e9a-effb5381326c.png)

**Event:**
![image](https://user-images.githubusercontent.com/26245501/94953633-7e7c9000-0505-11eb-8e15-36b96fd9714b.png)

**Please backport to BC14 also.**

**Comment by RomanZanizdra** [comment]
Hi @sukumar5893 . There requested event is already there. We do events only for the latest version which is 17.0 for now. If you really need to event in 14 version, ask support channel to process it via hotfix.

    local procedure CheckWarehouse()
    var
        Location2: Record Location;
        WhseSetup: Record "Warehouse Setup";
        ShowDialog: Option " ",Message,Error;
        DialogText: Text[50];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckWarehouse(Rec, IsHandled);
        if IsHandled then
            exit;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
