### ISSUE TITLE
[Event Request] Page 54 Purchase Order Subform - OnBeforeOpenSalesOrderForm

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9050]
Hi Team,

In Page 54 we need possibility to replace, change filters and avoid using standard code. Having event in the beginning of procedure `OpenSalesOrderForm`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94988525-99d3b380-0576-11eb-8da0-3e8b135a940a.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenSalesOrderForm(var PurchaseLine: record "Purchase Line"; var SalesHeader: Record "Sales Header"; var SalesOrder: Page "Sales Order"; var isHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
