### ISSUE TITLE
[Event Request] Page 255 Cash Receipt Journal - OnOpenPageOnBeforeTemplateSelection

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9051]
Hi Team,

In Page 255 we need possibility to replace, change filters and avoid using standard code. Having event in the procedure `OnOpenPage`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94988659-85dc8180-0577-11eb-8ce1-019029f27e36.png)

    [IntegrationEvent(true, false)]
    local procedure OnOpenPageOnBeforeTemplateSelection(var GenJournalLine: Record "Gen. Journal Line"; var JnlSelected: Boolean; CurrentJnlBatchName: Code[10]; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
