### ISSUE TITLE
[Event Request] Page 262 Item Journal Batches - OnBeforeOpenPage

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9052]
Hi Team,

In Page 262 we need possibility to replace, change filters and avoid using standard code. Having event in the trigger `OnOpenPage`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94988688-d05dfe00-0577-11eb-8c54-ce35e7588ece.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenPage(var ItemJournalBatch: record "Item Journal Batch"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
