### ISSUE TITLE
[Event Request] Page 306 Report Selection - Sales - OnSetUsageFilter

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9053]
Hi Team,

In Page 306 we need possibility to have our additional checks with the case scenario. Having event in the end of procedure `SetUsageFilter` in the `else` state, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94988750-4498a180-0578-11eb-9561-81d0fea26f41.png)

    [IntegrationEvent(false, false)]
    local procedure OnSetUsageFilter(var ReportSelections: Record "Report Selections"; ReportUsage2: Option Quote,"Blanket Order","Order",Invoice,"Work Order","Return Order","Credit Memo",Shipment,"Return Receipt","Sales Document - Test","Prepayment Document - Test","Archived Quote","Archived Order","Archived Return Order","Pick Instruction","Customer Statement","Draft Invoice","Pro Forma Invoice","Archived Blanket Order",,"Proforma Invoice","Proforma Shipment",,,,,,,,,,,,,,,,,,,,,,"C.Statement","V.Remittance")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
