### ISSUE TITLE
[Event Request] Page 497 Reservation Entries - OnCancelReservationOnBeforeConfirm

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9054]
Hi Team,

In Page 497 we need possibility to have our additional checks . Having event in the trigger `OnAction` of action `CancelReservation` , would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94989086-c4277000-057a-11eb-9c48-7085a85812a5.png)

    [IntegrationEvent(false, false)]
    local procedure OnCancelReservationOnBeforeConfirm(var ReservEntry: Record "Reservation Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
