### ISSUE TITLE
[Event Request] Page 1160 Sales Documents - OnAfterGetRecordSetStyleTxt

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9055]
Hi Team,

In Page 1160 we need possibility to have our additional checks . Having event in the trigger `OnAfterGetRecord`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94989165-65aec180-057b-11eb-912a-7fa7ac35082e.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordSetStyleTxt(var StyleTxt: Text; CustLedEntry: Record "Cust. Ledger Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
