### ISSUE TITLE
[Event Request] Page 5700 Stockkeeping Unit Card - OnAfterGetRecordOnBeforeFilterItem

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9056]
Hi Team,

In Page 5700 we need possibility to have our additional checks . Having event with handler in the trigger `OnAfterGetRecord`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94989209-bd4d2d00-057b-11eb-9167-d1de0011c108.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordOnBeforeFilterItem(var SKU: Record "Stockkeeping Unit"; var Item: Record Item; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
