### ISSUE TITLE
[Event Request] Page 6510 Item Tracking Lines - OnBeforeUpdateExpDateEditable

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9057]
Hi Team,

In Page 6510 we need possibility to have our additional checks . Having event with handler in the procedure `UpdateExpDateEditable`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94989786-f4bdd880-057f-11eb-89a9-efa2915b16e6.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateExpDateEditable(var TrackingSpecification: Record "Tracking Specification"; var ExpirationDateEditable: Boolean; var ItemTrackingCode: Record "Item Tracking Code"; var NewExpirationDateEditable: Boolean; CurrentSignFactor: Integer; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
