### ISSUE TITLE
[Event Request] Page 6550 Whse. Item Tracking Lines - OnBeforeUpdateExpDateColor

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9058]
Hi Team,

In Page 6550 we need possibility to have our additional checks . Having event with handler in the procedure `UpdateExpDateColor`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94989850-53835200-0580-11eb-962d-8d08ed119e00.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateExpDateColor(var WhseItemTrackingLine: Record "Whse. Item Tracking Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
