### ISSUE TITLE
[Event Request] Page 35516 Cash Receipt Journal FactBox - OnAfterUpdateInfoBoxRepeat

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9059]
Hi Team,

In Page 35516 we need possibility to have our additional checks . Having event in the procedure `UpdateInfoBox`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/94989909-b2e16200-0580-11eb-9ab0-40fab18370ad.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateInfoBoxRepeat("Posting Date": Date; PostingDate: Date; CustLedgEntry: Record "Cust. Ledger Entry"; PmtDiscDate: Date; DueDate: Date; AgeDays: Integer; PaymDiscDays: Integer; DueDays: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
