### ISSUE TITLE
[Event Request] Report 2 General Journal Test - OnAfterCheckBalAccountNo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9060]
Hi Team,

In Report 2 we need possibility to have our additional checks . Having event in the trigger `OnAfterGetRecord`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95020810-126d6980-0676-11eb-9892-e14041383936.png)

    [IntegrationEvent(true, false)]
    local procedure OnAfterCheckBalAccountNo(GenJournalLine: Record "Gen. Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
