### ISSUE TITLE
[Event Request] Report 2 General Journal Test - OnAfterCheckAccountNo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9061]
Hi Team,

In Report 2 we need possibility to have our additional checks . Having event in the trigger OnAfterGetRecord, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95020837-3e88ea80-0676-11eb-9c18-cb4815cd2372.png)

    [IntegrationEvent(true, false)]
    local procedure OnAfterCheckAccountNo(GenJournalLine: Record "Gen. Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
