### ISSUE TITLE
[Event Request] Report 4 Detail Trial Balance - OnPreDataItemSetEntryNoFilter

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9062]
Hi Team,

In Report 4 we need possibility to have our additional checks . Having event in the trigger `OnPreDataItem`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95069737-c40ca900-070f-11eb-9dfc-e52e721028e4.png)

    [IntegrationEvent(false, false)]
    local procedure OnPreDataItemSetEntryNoFilter(var "G/L Entry": Record "G/L Entry")

**Comment by RomanZanizdra** [comment]
Hi @MantasGurinas . Could you clarify what is the GLEntryNoFilter variable? I cannot find it in the report.

**Comment by MantasGurinas** [comment]
Hi @RomanZanizdra , i made adjustments, GLEntryNoFilter is removed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
