### ISSUE TITLE
[Event Request] Report 4 Detail Trial Balance - OnPreReportGetEntryNoFilter

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9063]
Hi Team,

In Report 4 we need possibility to have our additional checks . Having event in the trigger `OnPreReport`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95020998-12ba3480-0677-11eb-879e-f45f4ae6714c.png)

    [IntegrationEvent(false, false)]
    local procedure OnPreReportGetEntryNoFilter("G/L Account": Record "G/L Account")

**Comment by RomanZanizdra** [comment]
Hi @MantasGurinas . The question is the same, what is the GLEntryNoFilter variable?

**Comment by MantasGurinas** [comment]
Hi @RomanZanizdra , i made adjustments, GLEntryNoFilter is removed.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
