### ISSUE TITLE
[Event Request] Report 202 Sales Document - Test - OnAfterGetRecordCheckIsHandled

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9064]
Hi Team,

In Report 202 we need possibility to have our additional checks . Having event with handling in the trigger `OnAfterGetRecord`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95021056-6036a180-0677-11eb-832f-07ea69052800.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordCheckIsHandled(var SalesLine: Record "Sales Line"; var GLAcc: Record "G/L Account"; var IsHandled: Boolean; OrigMaxLineNo: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
