### ISSUE TITLE
[Event Request] Report 299 Delete Invoiced Sales Orders - OnBeforeDeleteSalesLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9065]
Hi Team,

In Report 299 we need possibility to have our additional checks . Having event in the trigger `OnAfterGetRecord`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95021111-bd325780-0677-11eb-92cf-599b2e2f68f0.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteSalesLine(var SalesHeader: Record "Sales Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
