### ISSUE TITLE
[Event Request] Report 493 Carry Out Action Msg. - Req. - OnAfterUseOneJnlWithReqLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9066]
Hi Team,

In Report 493 we need possibility to have our additional checks . Having event in the procedure `UseOneJnl`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95021173-10a4a580-0678-11eb-822e-c632ef5ccda7.png)

    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterUseOneJnlWithReqLine(var ReqLine: Record "Requisition Line"; var ReqWkshMakeOrders: Codeunit "Req. Wksh.-Make Order"; PurchOrderHeader: Record "Purchase Header"; EndOrderDate: Date; PrintOrders: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
