### ISSUE TITLE
[Event Request] Report 790 Calculate Inventory - OnAfterReserveWarehouseWithItemJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9067]
Hi Team,

In Report 790 we need possibility to have our additional checks . Having event in the procedure `ReserveWarehouse`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95021380-57df6600-0679-11eb-9410-aea6b5cb78fe.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterReserveWarehouseWithItemJnlLine(var ItemJnlLine: Record "Item Journal Line"; var WhseEntry: Record "Warehouse Entry"; var WhseEntry2: Record "Warehouse Entry"; EntryType: Option "Negative Adjmt.","Positive Adjmt.")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
