### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnBeforeUpdateCustLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9068]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `UpdateCustLedgEntry`. Standard publisher `OnBeforeUpdateCustLedgEntry` would suit us if it had additional parameter `var IsHandled: Boolean` .

![image](https://user-images.githubusercontent.com/70525691/95021583-74c86900-067a-11eb-8e64-326395dcc619.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateCustLedgEntry(var ToSalesHeader: Record "Sales Header"; var CustLedgerEntry: Record "Cust. Ledger Entry"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
