### ISSUE TITLE
[Event Request] Codeunit 393 "Reminder-Issue" - OnRunOnBeforeGenJnlLineUpdateLineBalance

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9069]
Hi team,

In Codeunit 393 "Reminder-Issue" procedure `OnRun` we would like to run some custom code before `GenJnlLine.UpdateLineBalance`, for that an event would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95045968-d543be80-06eb-11eb-81d4-cef0c0a9a19e.png)
```
[IntegrationEvent(false, false)]
local procedure OnRunOnBeforeGenJnlLineUpdateLineBalance(var GenJnlLine: Record "Gen. Journal Line"; ReminderInterestVATAmount: Decimal; var TotalAmount: Decimal);
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
