### ISSUE TITLE
[Event Request] Codeunit 393 "Reminder-Issue" - OnBeforeInsertIssuedReminderLineOnDeleteHeader

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9070]
Hi team,

In Codeunit 393 "Reminder-Issue" procedure `DeleteHeader` we would like to run some custom code before Inserting new IssueReminderLine, for that an event publisher before the Insert would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95046715-68312880-06ed-11eb-8b24-531d2e298f74.png)
```
[IntegrationEvent(false, false)]
local procedure OnDeleteHeaderOnBeforeInsertIssuedReminderLine(var IssuedReminderLine: Record "Issued Reminder Line"; var IssuedReminderHeader: Record "Issued Reminder Header")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
