### ISSUE TITLE
[Event Request] Codeunit 396 NoSeriesManagement - OnAfterInitSeries

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9071]
Hi team,

Codeunit 396 NoSeriesManagement procedure `InitSeries` we would like to run some additional code at end of procedure, for that an event at the end of procedure code would be a good idea: 
![image](https://user-images.githubusercontent.com/49302698/95047725-3de06a80-06ef-11eb-9508-49cbc471829c.png)
```
[IntegrationEvent(false, false)]
procedure OnAfterInitSeries(var NoSeries: Record "No. Series"; DefaultNoSeriesCode: Code[20]; NewDate: Date; var NewNo: Code[20])
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
