### ISSUE TITLE
[Event Request] Codeunit 414 "Release Sales Document" - OnAfterCheckCustomerCreated

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9072]
Hi team,

In Codeunit 414 "Release Sales Document" procedure `"Code"`  we would like to perform additional checks before running code, for that an event with a handler before filtering SalesLine would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95048521-a1b76300-06f0-11eb-8250-fdd4b985dd28.png)
```
[IntegrationEvent(false, false)]
local procedure OnAfterCheckCustomerCreated(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean; PreviewMode: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
