### ISSUE TITLE
[Event Request] Table 36 Sales Header - Function OnBeforeOpenSalesOrderStatistics

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#9073]
Please add the parameter IsHandled to the function OnBeforeOpenSalesOrderStatistics:

OnBeforeOpenSalesOrderStatistics(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
