### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnUpdateVATAmountsOnBeforePurchaseLineModify

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9074]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the local procedure UpdateVATAmounts, we need to add our code at a specific moment. To do so, we need to add an event publisher here :

![image](https://user-images.githubusercontent.com/34645582/95062423-3b850d00-06fd-11eb-8c61-9e201ca87f4d.png)

And the event integration :
![image](https://user-images.githubusercontent.com/34645582/95062599-7edf7b80-06fd-11eb-8aac-3dd824790b5a.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
