### ISSUE TITLE
[Protected Var] IsSimplePage as Protected Var in page 39 General Journal

### ISSUE THREAD

**Issue by tomddlc** [microsoft/ALAppExtensions#9075]
Hi Extension team,

We have some fields in our vertical solution, that we would like to add to the General Journal, but only if the user is using the advanced view. So we would like to request that the global variable IsSimplePage is made protected so we can use in pageextensions.

Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
