### ISSUE TITLE
[Event Request] Codeunit 415 "Release Purchase Document" - OnReleasePurchaseDoc

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9076]
Hi team,

In Codeunit 415 "Release Purchase Document" procedure `"Code"` we would like to have the ability to perform additional checks, for that an event before filtering PurchLine would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95076860-346cf780-071b-11eb-975d-5a6310f52c82.png)
```
[IntegrationEvent(false, false)]
local procedure OnReleasePurchaseDoc(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
