### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnUpdateVATOnLinesOnBeforeWithPurchLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9077]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the local procedure UpdateVATOnLines, we need to replace the "with PurchLine do begin" by "with PurchLineTemp do begin" and to modify some of the standard code inside the "with". To do so, we need to add a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95079402-dd652380-0716-11eb-9472-509087feb593.png)

And the event integration :
![image](https://user-images.githubusercontent.com/34645582/95079924-97f52600-0717-11eb-8277-1c4de3bdae39.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
