### ISSUE TITLE
[Event Request] Report 5880 Calc. Phys. Invt. Order Lines - OnAfterOnOpenPageSetFilter

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9078]
Hi Team,

In Report 5880 we need possibility to have our additional checks . Having event in the trigger `OnOpenPage`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95080466-d0e5c880-0720-11eb-8c93-47ffc780be81.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnOpenPageSetFilter(var PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; var Item: Record Item)

**Comment by RomanZanizdra** [comment]
Hi @MantasGurinas . Please clarify what is the OnOpenPage trigger? I cannot find it.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
