### ISSUE TITLE
[Event Request] Report 5880 Calc. Phys. Invt. Order Lines - OnAfterSetPhysInvtOrderHeader

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9079]
Hi Team,

In Report 5880 we need possibility to have our additional checks . Having event in the procedure `SetPhysInvtOrderHeader`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95080628-0db1bf80-0721-11eb-9c60-69bf2e95ba30.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetPhysInvtOrderHeader(var PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; var Item: Record Item)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
