### ISSUE TITLE
[Event Request] Report 5880 Calc. Phys. Invt. Order Lines - OnBeforeOnPreDataItem

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9080]
Hi Team,

In Report 5880 we need possibility to have our additional checks . Having event in the procedure `OnPreDataItem`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95080714-2fab4200-0721-11eb-9113-91ddef9f14c1.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnPreDataItem(var PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; var Item: Record Item)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
