### ISSUE TITLE
[Additional Parameter Request] Codeunit 415 "Release Purchase Document" - OnBeforeReopenPurchaseDoc

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9081]
Hi team,

In Codeunit 415 "Release Purchase Document" procedure `Reopen` we would like to run some custom code for that we would need the ability to stop running the procedure code, a handler variable `IsHandled: Boolean` added to event `OnBeforeReopenPurchaseDoc ` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95077451-31263b80-071c-11eb-8117-fa90e2de02c2.png)
[IntegrationEvent(false, false)]
local procedure OnBeforeReopenPurchaseDoc(var PurchaseHeader: Record "Purchase Header"; PreviewMode: Boolean; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
