### ISSUE TITLE
[Event Request] Report 5885 Calc. Phys. Invt. Order (Bins) - OnAfterGetRecordCheckPhysInvtOrderBinFilter

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9082]
Hi Team,

In Report 5885 we need possibility to have our additional checks . Having event in the trigger `OnAfterGetRecord` , would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95089889-58393900-072d-11eb-81bd-57b10a78543a.png)

    [IntegrationEvent(true, false)]
    local procedure OnAfterGetRecordCheckPhysInvtOrderBinFilter(PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; Bin: Record Bin)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
