### ISSUE TITLE
[Event Request] Report 5885 Calc. Phys. Invt. Order (Bins) - OnAfterSetPhysInvtOrderHeaderSetRange

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9083]
Hi Team,

In Report 5885 we need possibility to have our additional checks . Having event in the procedure `SetPhysInvtOrderHeader`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95090100-8fa7e580-072d-11eb-8fa6-4d06fb78359d.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetPhysInvtOrderHeaderSetRange(var PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; var Location: Record Location; var Bin: Record Bin; NewPhysInvtOrderHeader: Record "Phys. Invt. Order Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
