### ISSUE TITLE
[Event Request] Report 7391 - OnInsertPurchaseReturnOrderLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9084]
Hi Team,

In Report 7391 we need possibility to have our additional checks . Having event in the trigger `OnPostDataItem`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95090754-51f78c80-072e-11eb-8a4b-efaf4a2a7bd0.png)

    [IntegrationEvent(false, false)]
    local procedure OnInsertPurchaseReturnOrderLine(var PurchaseLineTemp: Record "Purchase Line"; var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var SetBinCodeToPurchReturnOrder: Boolean; DestinationType2: Option MovementWorksheet,WhseInternalPutawayHeader,ItemJournalLine,TransferHeader,InternalMovementHeader,,,,,,,,,,,PurchReturnHeader)

**Comment by RomanZanizdra** [comment]
Hi @MantasGurinas . Please clarify parameters, looks like they have been taken from other place.

**Comment by RomanZanizdra** [comment]
Hi @MantasGurinas , any update from your side?

**Comment by MantasGurinas** [comment]
Hi @RomanZanizdra , it looks like it was a mistake. I'm closing this issue until we fix the issue.
