### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnAfterCopySalesLineFromSalesLineBuffer

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9085]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopySalesInvLinesToDoc`. Standard publisher `OnAfterCopySalesLineFromSalesLineBuffer` would suit us if it had additional parameter `FromSalesLine: Record "Sales Line"` .

![image](https://user-images.githubusercontent.com/70525691/95094934-21feb800-0733-11eb-9537-c8da332979f2.png)

[IntegrationEvent(false, false)]
local procedure OnAfterCopySalesLineFromSalesLineBuffer(var ToSalesLine: Record "Sales Line"; FromSalesInvLine: Record "Sales Invoice Line"; IncludeHeader: Boolean; RecalculateLines: Boolean; var TempDocSalesLine: Record "Sales Line" temporary; ToSalesHeader: Record "Sales Header"; FromSalesLineBuf: Record "Sales Line"; var FromSalesLine2: Record "Sales Line";**FromSalesLine: Record "Sales Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
