### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnCopyPurchDocRcptLineOnAfterSetFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9086]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopyPurchDocRcptLine`. Standard publisher `OnCopyPurchDocRcptLineOnAfterSetFilters` would suit us if it had additional parameter **var RecalculateLines: Boolean** .

![image](https://user-images.githubusercontent.com/70525691/95095257-7efa6e00-0733-11eb-8914-78d70b5beadc.png)

[IntegrationEvent(false, false)]
local procedure OnCopyPurchDocRcptLineOnAfterSetFilters(var ToPurchHeader: Record "Purchase Header"; var FromPurchRcptHeader: Record "Purch. Rcpt. Header"; var FromPurchRcptLine: Record "Purch. Rcpt. Line";**var RecalculateLines: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
