### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnCopySalesDocShptLineOnAfterSetFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9087]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopySalesDocShptLine`. Standard publisher `OnCopySalesDocShptLineOnAfterSetFilters` would suit us if it had additional parameter `var RecalculateLines: Boolean` .

![image](https://user-images.githubusercontent.com/70525691/95095801-2f687200-0734-11eb-944d-7b2cf24194c8.png)

[IntegrationEvent(false, false)]
local procedure OnCopySalesDocShptLineOnAfterSetFilters(var ToSalesHeader: Record "Sales Header"; var FromSalesShipmentHeader: Record "Sales Shipment Header"; var FromSalesShipmentLine: Record "Sales Shipment Line"; **var RecalculateLines: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
