### ISSUE TITLE
[Event Request] Codeunit 408 DimensionManagement - OnCheckDimValuePostingOnBeforeLogError

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9088]
Hi team,

In Codeunit 408 DimensionManagement procedure `CheckDimValuePosting` we would like to chane how Errors are logged depending on TempDefaultDim field "Value Posting", for that an event publisher before the `case "Value Posting" of` code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95095467-bff28280-0733-11eb-8bae-c8640f535316.png)
```
[IntegrationEvent(false, false)]
local procedure OnCheckDimValuePostingOnBeforeLogError(TempDefaultDim: Record "Default Dimension" temporary; DimSetEntry: Record "Dimension Set Entry"; var LastErrorMessage: Record "Error Message"; var ErrorMessageMgt: Codeunit "Error Message Management"; var isHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
