### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnCopySalesDocInvLineOnAfterSetFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9089]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopySalesDocInvLine`. Standard publisher `OnCopySalesDocInvLineOnAfterSetFilters` would suit us if it had additional parameter `var RecalculateLines: Boolean` and `var isHandled: Boolean` .

![image](https://user-images.githubusercontent.com/70525691/95096091-84a48380-0734-11eb-9128-5161dfe014bd.png)

[IntegrationEvent(false, false)]
local procedure OnCopySalesDocInvLineOnAfterSetFilters(var ToSalesHeader: Record "Sales Header"; var FromSalesInvoiceHeader: Record "Sales Invoice Header"; var FromSalesInvoiceLine: Record "Sales Invoice Line"; **var RecalculateLines: Boolean; var isHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
