### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnCopySalesDocCrMemoLineOnAfterSetFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9090]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopySalesDocCrMemoLine`. Standard publisher `OnCopySalesDocCrMemoLineOnAfterSetFilters` would suit us if it had additional parameter `var RecalculateLines: Boolean` .

![image](https://user-images.githubusercontent.com/70525691/95096334-ccc3a600-0734-11eb-97c5-0a2f377b19b3.png)

[IntegrationEvent(false, false)]
local procedure OnCopySalesDocCrMemoLineOnAfterSetFilters(var ToSalesHeader: Record "Sales Header"; var FromSalesCrMemoHeader: Record "Sales Cr.Memo Header"; var FromSalesCrMemoLine: Record "Sales Cr.Memo Line"; **var RecalculateLines: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
