### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnCopySalesDocWithHeader

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9091]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopySalesDocUpdateHeader`. Standard publisher `OnCopySalesDocWithHeader` would suit us if it had additional parameter `SalesDocType: Option` and `var FromSalesHeader: Record "Sales Header"`.

![image](https://user-images.githubusercontent.com/70525691/95096619-2deb7980-0735-11eb-8874-ad192632a958.png)

[IntegrationEvent(false, false)]
local procedure OnCopySalesDocWithHeader(FromDocType: Option; FromDocNo: Code[20]; var ToSalesHeader: Record "Sales Header"; FromDocOccurenceNo: Integer; FromDocVersionNo: Integer; **SalesDocType: Option Quote,"Blanket Order","Order",Invoice,"Return Order","Credit Memo","Posted Shipment","Posted Invoice","Posted Return Receipt","Posted Credit Memo","Arch. Quote","Arch. Order","Arch. Blanket Order","Arch. Return Order"; var FromSalesHeader: Record "Sales Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
