### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnCopyPurchDocPurchLineOnAfterSetFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9092]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopyPurchDocPurchLine`. Standard publisher `OnCopyPurchDocPurchLineOnAfterSetFilters` would suit us if it had additional parameter` var RecalculateLines: Boolean`.

![image](https://user-images.githubusercontent.com/70525691/95097072-ba963780-0735-11eb-90cf-2e78633788e0.png)

[IntegrationEvent(false, false)]
local procedure OnCopyPurchDocPurchLineOnAfterSetFilters(FromPurchHeader: Record "Purchase Header"; var FromPurchLine: Record "Purchase Line"; var ToPurchHeader: Record "Purchase Header"; **var RecalculateLines: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
