### ISSUE TITLE
[Additional Parameter Request] Codeunit 6620 Copy Document Mgt. - OnCopySalesDocSalesLineOnAfterSetFilters

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9093]
Hi Team,

In codeunit 6620 we need possibility to have additional checks in the procedure `CopySalesDocSalesLine`. Standard publisher `OnCopySalesDocSalesLineOnAfterSetFilters` would suit us if it had additional parameter `var RecalculateLines: Boolean`.

![image](https://user-images.githubusercontent.com/70525691/95097296-fcbf7900-0735-11eb-981a-b3436612bddb.png)

[IntegrationEvent(false, false)]
local procedure OnCopySalesDocSalesLineOnAfterSetFilters(FromSalesHeader: Record "Sales Header"; var FromSalesLine: Record "Sales Line"; var ToSalesHeader: Record "Sales Header"; **var RecalculateLines: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
