### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnBeforeInitType

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9094]
We are migrating our code from NAV 2018 to BC16.4. In the table 39 Purchase Line, in the local procedure InitType, we need to add a condition before the line "Type := xRec.Type;". To do so, we need to add a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95101278-41491580-0732-11eb-8651-beaba9691fad.png)

And the event integration :
![image](https://user-images.githubusercontent.com/34645582/95101321-4c03aa80-0732-11eb-8ca0-7431b0f06896.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
