### ISSUE TITLE
[EventChange] Table 81 OnBeforeLookUpAppliesToDocCust / OnBeforeLookUpAppliesToDocCust /OnBeforeLookUpAppliesToDocEmpl

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#9096]
Hi,
referring to this [Request](https://github.com/microsoft/ALAppExtensions/issues/1239)  we would like to ask you to define the record variables GenJournalLine as **Var**, as requested in the oringin request.

We suggest the following changes to the existing events: 
OnBeforeLookUpAppliesToDocCust(**Var** GenJournalLine: Record "Gen. Journal Line"; AccNo: Code[20]; var IsHandled: Boolean)
OnBeforeLookUpAppliesToDocEmpl(**Var** GenJournalLine: Record "Gen. Journal Line"; AccNo: Code[20]; var IsHandled: Boolean)
OnBeforeLookUpAppliesToDocVend(**Var** GenJournalLine: Record "Gen. Journal Line"; AccNo: Code[20]; var IsHandled: Boolean)

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
