### ISSUE TITLE
[Additional Parameter Request] Codeunit 408 DimensionManagement - OnBeforeGetDimensionSet

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9097]
Hi team,

In Codeunit 408 DimensionManagement procedure `GetDimensionSet` we would like to have the ability to customize how the code works, for that we would need some additional parameters added to event `OnBeforeGetDimensionSet`: `DimSetID: Integer` and `IsHandled: Boolean`, also `IsHandled: Boolean` would need to be added as local variable:
![image](https://user-images.githubusercontent.com/49302698/95166109-f244c400-07b5-11eb-986f-dca2b70ce98b.png)
[IntegrationEvent(false, false)]
local procedure OnBeforeGetDimensionSet(var TempDimensionSetEntry: Record "Dimension Set Entry" temporary; **var DimSetID: Integer; var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
