### ISSUE TITLE
[Event Request] Table 981 Payment Registration Buffer

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#9098]
Dear Team,

Please help me add events on Table 981-Payment Registration Buffer.
1. Method PopulateTable()
     OnBeforeInsertPaymentRegistrationBuffer(PaymentRegistrationBuffer, CustLedgEntry);
     
![image](https://user-images.githubusercontent.com/24407031/95172178-24b7e680-07e1-11eb-8a6e-aa2c4c6f269b.png)

2. Method RestoreUserValues()
     OnBeforeModifyPaymentRegistrationBuffer(PaymentRegistrationBuffer, TempSavePmtRegnBuf);
     
![image](https://user-images.githubusercontent.com/24407031/95172467-9001b880-07e1-11eb-87fa-4cee5d9fd1ae.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
