### ISSUE TITLE
[Function Expose] Codeuit 1502 Workflow Setup

### ISSUE THREAD

**Issue by GaryFrostick** [Microsoft/ALAppExtensions#91]
We need the following functions exposed I Codeunit 1502
	InsertEventStep() function to be Public & External
	InsertEventArgument() function to be Public & External

This is to allow additional workflows to be created for app functionally

**Comment by darjoo** [comment]
Hi, we've gone ahead with your request. We usually include these types of changes in the next minor release, so look for it there.
