### ISSUE TITLE
[Additional Parameter Request] Codeunit 11 Gen. Jnl.-Check Line - OnBeforeCheckPurchDocNoIsNotUsed

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#9101]
Could you please add additional parameter (Record "Gen. Journal Line") to OnBeforeCheckPurchDocNoIsNotUsed in CU11. Somehow related issue is #4332.

>>>OLD CODE

    procedure CheckPurchDocNoIsNotUsed(var GenJournalLine: Record "Gen. Journal Line")
    var
        OldVendLedgEntry: Record "Vendor Ledger Entry";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckPurchDocNoIsNotUsed(GenJournalLine."Document Type".AsInteger(), GenJournalLine."Document No.", IsHandled);
        if IsHandled then
            exit;
        .
        .
        .

>>>NEW CODE

    procedure CheckPurchDocNoIsNotUsed(var GenJournalLine: Record "Gen. Journal Line")
    var
        OldVendLedgEntry: Record "Vendor Ledger Entry";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckPurchDocNoIsNotUsed(GenJournalLine."Document Type".AsInteger(), GenJournalLine."Document No.", IsHandled,GenJournalLine);
        if IsHandled then
            exit;
        .
        .
        .

>>>OLD EVENT

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPurchDocNoIsNotUsed(DocType: Option; DocNo: Code[20]; var IsHandled: Boolean)
    begin
    end;

>>>NEW EVENT

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPurchDocNoIsNotUsed(DocType: Option; DocNo: Code[20]; var IsHandled: Boolean; GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
