### ISSUE TITLE
[Event Request] Table 295 Reminder Header - OnValidateCustomerNoOnBeforeCustBlocked

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9103]
We are migrating our code from NAV 2018 to BC16.4. In the table 295 Reminder Header, in the Field 2 "Customer No", in the trigger OnValidate, we need to modify a part of the code to be able to send reminder to blocked customers. To do so, we need to add a IsHandled flag and event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95184405-9a16bd80-07c7-11eb-9407-9b9aa05a5004.png)

And the integration event :
![image](https://user-images.githubusercontent.com/34645582/95184452-ac90f700-07c7-11eb-984e-1c40bcfcca58.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
