### ISSUE TITLE
[Event Request] Table 295 Reminder Header - OnDeleteOnBeforePrintRecords

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9104]
We are migrating our code from NAV 2018 to BC16.4. In the table 295 Reminder Header, in the trigger OnDelete, we need to add a condition. To do so, we need to add a IsHandled flag and event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95189073-a9006e80-07cd-11eb-9c94-dbc4dec3c066.png)

And the integration event : 
![image](https://user-images.githubusercontent.com/34645582/95189101-b158a980-07cd-11eb-84fe-a1f4b4ed6452.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
