### ISSUE TITLE
[Event Request] Report 7304 "Get Outbound Source Documents" – New Event “OnBeforeReport”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#9107]
Could we please have a new publisher “OnBeforeReport” in trigger “OnPreReport”, Report "Get Outbound Source Documents”?
```
    trigger OnPreReport()
    begin
*** start new code ***
        OnBeforeReport();
*** stop new code ***
        LineCreated := false;
    end;
…
*** start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnBeforeReport()
    begin
    end;
*** stop new code ***
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
