### ISSUE TITLE
[Event Request] Report 7304 "Get Outbound Source Documents" – New Event “OnBeforeWhsePickRequestOnPreDataItem”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#9110]
Could we please have a new publisher “OnBeforeWhsePickRequestOnPreDataItem” in the new trigger “OnPreDataItem” (DataItem “Whse. Pick Request”), Report "Get Outbound Source Documents”?
```
*** start new code ***
            trigger OnPreDataItem()
            begin
                OnBeforeWhsePickRequestOnPreDataItem("Whse. Pick Request");
            end;
*** stop new code ***
…
*** start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhsePickRequestOnPreDataItem(var WhsePickRequest: record "Whse. Pick Request")
    begin
    end;
*** stop new code ***
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
