### ISSUE TITLE
[Event Request] Table 12186 "VAT Exemption"; new event OnValidateVATExemptStartingDateOnBeforeError

### ISSUE THREAD

**Issue by AndreaCorneglioCapBS** [microsoft/ALAppExtensions#9111]
field(3; "VAT Exempt. Starting Date"; Date)
        {
            Caption = 'VAT Exempt. Starting Date';
            NotBlank = true;

            trigger OnValidate()
            ...
               if ("VAT Exempt. Ending Date" <> 0D) and ("VAT Exempt. Ending Date" < "VAT Exempt. Starting Date") then
                    Error(Text12100, FieldCaption("VAT Exempt. Ending Date"), FieldCaption("VAT Exempt. Starting Date"));
                //> NEW CODE
                IsHandled := FALSE;
                OnValidateVATExemptStartingDateOnBeforeError(IsHandled);
                IF NOT IsHandled THEN BEGIN
                //< NEW CODE
                    VATExemption.SetRange(Type, Type);
                    VATExemption.SetRange("No.", "No.");

        field(4; "VAT Exempt. Ending Date"; Date)
        {
            Caption = 'VAT Exempt. Ending Date';
            NotBlank = true;

            trigger OnValidate()
            ...
                if "VAT Exempt. Ending Date" < "VAT Exempt. Starting Date" then
                    Error(Text12100, FieldCaption("VAT Exempt. Ending Date"), FieldCaption("VAT Exempt. Starting Date"));
                //> NEW CODE
                IsHandled := FALSE;
                OnValidateVATExemptStartingDateOnBeforeError(IsHandled);
                IF NOT IsHandled THEN BEGIN
                //< NEW CODE
                    VATExemption.SetRange(Type, Type);
                    VATExemption.SetRange("No.", "No.");

    [IntegrationEvent(false, false)]
    local procedure OnValidateVATExemptStartingDateOnBeforeError(var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
