### ISSUE TITLE
[Event Request] Report 5753 "Get Source Documents" – New Event “OnAfterSalesHeaderOnPostDataItem”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#9115]
Could we please have a new publisher “OnAfterSalesHeaderOnPostDataItem” in the new trigger “OnPostDataItem” (DataItem “Sales Header”), Report "Get Source Documents”?
```
*** start new code ***
                trigger OnPostDataItem()
                begin
                    OnAfterSalesHeaderOnPostDataItem("Warehouse Request", "Sales Header");
                end;
*** stop new code ***
…
*** start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnAfterSalesHeaderOnPostDataItem(WhseRequest: Record "Warehouse Request"; SalesHeader: Record "Sales Header")
    begin
    end;
*** stop new code ***
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
