### ISSUE TITLE
[Function Expose] RedistributeTotalsOnAfterValidate on Sales Document Subform pages

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/ALAppExtensions#912]
Hi,

Can you expose RedistributeTotalsOnAfterValidate function in following objects:

- PAG46	Sales Order Subform
- PAG47	Sales Invoice Subform
- PAG95	Sales Quote Subform
- PAG96	Sales Cr. Memo Subform
- PAG508	Blanket Sales Order Subform
- PAG6641	Purchase Return Order Subform

**Comment by darjoo** [comment]
Hi @ivandjordjevic,
The functions you have requested have been exposed and will be available in a future release.
