### ISSUE TITLE
[Event Request] Page 436 Reminder List - OnBeforeIssueRemindersRunModal

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9122]
Hi Team,

In Page 436 we need possibility to have our additional checks . Having event with handling on trigger `OnAction` of action `Issue`, would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95201045-0bfeff00-07e8-11eb-884b-253c0855c098.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIssueRemindersRunModal(ReminderHeader: Record "Reminder Header"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
