### ISSUE TITLE
[Additional Parameter Request] Codeunit 90 Purch.-Post - OnPostCombineSalesOrderShipmentOnAfterUpdateBlanketOrderLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9123]
Hi Team,

In codeunit 90 we need possibility to have additional checks in the procedure `PostCombineSalesOrderShipment`. Standard publisher `OnPostCombineSalesOrderShipmentOnAfterUpdateBlanketOrderLine` would suit us if it had additional parameter with included from issue #8751 `SalesShptHeader: Record "Sales Shipment Header"`.

![image](https://user-images.githubusercontent.com/70525691/95209538-22f71e80-07f3-11eb-9b49-036e6a801ccd.png)

local procedure OnPostCombineSalesOrderShipmentOnAfterUpdateBlanketOrderLine(var PurchaseHeader: Record "Purchase Header"; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer"; var SalesOrderLine: Record "Sales Line"; **SalesShptHeader: Record "Sales Shipment Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
