### ISSUE TITLE
[Additional Parameter Request] Codeunit 90 Purch.-Post - OnBeforePurchRcptLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9124]
Hi Team,

In codeunit 90 we need possibility to have additional checks in the procedure `InsertReceiptLine`. Standard publisher `OnBeforePurchRcptLineInsert` would suit us if it had additional parameter `var IsHandled: Boolean`.

![image](https://user-images.githubusercontent.com/70525691/95210384-1e7f3580-07f4-11eb-80ef-fc54b7a2bced.png)

local procedure OnBeforePurchRcptLineInsert(var PurchRcptLine: Record "Purch. Rcpt. Line"; var PurchRcptHeader: Record "Purch. Rcpt. Header"; var PurchLine: Record "Purchase Line"; CommitIsSupressed: Boolean; PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
