### ISSUE TITLE
[Event Request] Codeunit 7302 "WMS Management" - OnCheckWhseJnlLineOnBeforeCheckSourceJrnl

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9125]
Hi team,

In Codeunit 7302 "WMS Management" procedure `CheckWhseJnlLine`, we would like to run some additional code when checking SourceJnl, for that an event with handler before performing the check would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95212904-e0374580-07f6-11eb-8008-b3b975eccac9.png)
```
[IntegrationEvent(false, false)]
local procedure OnCheckWhseJnlLineOnBeforeCheckSourceJrnl(var WhseJnlLine: Record "Warehouse Journal Line"; var Bin: Record Bin; SourceJnl: Option " ",ItemJnl,OutputJnl,ConsumpJnl,WhseJnl; var BinContent: Record "Bin Content"; Location: Record Location; DecreaseQtyBase: Decimal; var IsHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
