### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterReturnRcptLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9126]
Hi Team,

In codeunit 90 we need possibility to have additional checks in the procedure `InsertReturnReceiptLine`. Standard publisher `OnAfterReturnRcptLineInsert` would suit us if it had additional parameter `TempWhseShptHeader: Record "Warehouse Shipment Header"` and `TempWhseRcptHeader: Record "Warehouse Receipt Header"`.

![image](https://user-images.githubusercontent.com/70525691/95214296-715aec00-07f8-11eb-8838-0c4f92e3f07a.png)

local procedure OnAfterReturnRcptLineInsert(var ReturnRcptLine: Record "Return Receipt Line"; ReturnRcptHeader: Record "Return Receipt Header"; SalesLine: Record "Sales Line"; ItemShptLedEntryNo: Integer; WhseShip: Boolean; WhseReceive: Boolean; CommitIsSuppressed: Boolean; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; **TempWhseShptHeader: Record "Warehouse Shipment Header"; TempWhseRcptHeader: Record "Warehouse Receipt Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
