### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterSalesShptLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9127]
Hi Team,

In codeunit 90 we need possibility to have additional checks in the procedure `InsertShipmentLine`. Standard publisher `OnAfterSalesShptLineInsert` would suit us if it had additional parameter `TempWhseShptHeader: Record "Warehouse Shipment Header"` and `TempWhseRcptHeader: Record "Warehouse Receipt Header"`.

![image](https://user-images.githubusercontent.com/70525691/95215607-d2cf8a80-07f9-11eb-8140-54409854d8c2.png)

    local procedure OnAfterSalesShptLineInsert(var SalesShipmentLine: Record "Sales Shipment Line"; SalesLine: Record "Sales Line"; ItemShptLedEntryNo: Integer; WhseShip: Boolean; WhseReceive: Boolean; CommitIsSuppressed: Boolean; SalesInvoiceHeader: Record "Sales Invoice Header"; **TempWhseShptHeader: Record "Warehouse Shipment Header"; TempWhseRcptHeader: Record "Warehouse Receipt Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
