### ISSUE TITLE
[Event Request] Codeunit 7308 "Replenishment" - OnFindReplenishmtBinAndOnAfterApplyFiltersOnFromBinContent & OnFindReplinishmtBinAndOnBeforeCalcQtyAvailToTakeBase & OnBeforeInsertWhseWkshLine

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9128]
Hi Team,

In codeunit 7308, please provide the possibility to have **OnFindReplenishmtBinAndOnAfterApplyFiltersOnFromBinContent** and **OnFindReplinishmtBinAndOnBeforeCalcQtyAvailToTakeBase** events in **FindReplenishmtBin** procedure. 
Also provide **OnBeforeInsertWhseWkshLine** event in **InsertWhseWkshLine** procedure.

1.**OnFindReplenishmtBinAndOnAfterApplyFiltersOnFromBinContent**

![image](https://user-images.githubusercontent.com/57799519/95209746-51cbbf80-0808-11eb-82d3-d0da6d8d977b.png)

**Event:**
LOCAL [IntegrationEvent] OnFindReplenishmtBinAndOnAfterApplyFiltersOnFromBinContent(ToBinContent: Record "Bin Content",VAR FromBinContent: Record "Bin Content")

2.**OnFindReplinishmtBinAndOnBeforeCalcQtyAvailToTakeBase**

![image](https://user-images.githubusercontent.com/57799519/95210795-7b391b00-0809-11eb-981f-ba7791c7153c.png)

**Event:**
LOCAL [IntegrationEvent] OnFindReplenishmtBinAndOnBeforeCalcQtyAvailToTakeBase(FromBinContent:Record “Bin Content”,VAR IsHandled: Boolean)

3.**OnBeforeInsertWhseWkshLine**

![image](https://user-images.githubusercontent.com/57799519/95217304-aa9f5600-0810-11eb-8bc4-14f24633995d.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeInsertWhseWkshLine(VAR TempWhseWkshLine: Record “Whse. Worksheet Line”; DoNotFillQtytoHandle: Boolean;VAR IsHandled: Boolean;VAR IsChecked: Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
