### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnBeforeSalesShptLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9129]
Hi Team,

In codeunit 90 we need possibility to have additional checks in the procedure `InsertShipmentLine`. Standard publisher `OnBeforeSalesShptLineInsert` would suit us if it had additional parameter `var IsHandled: Boolean`.

![image](https://user-images.githubusercontent.com/70525691/95222432-27c2cf00-0801-11eb-9aec-579c272b1186.png)

local procedure OnBeforeSalesShptLineInsert(var SalesShptLine: Record "Sales Shipment Line"; SalesShptHeader: Record "Sales Shipment Header"; SalesLine: Record "Sales Line"; CommitIsSuppressed: Boolean; PostedWhseShipmentLine: Record "Posted Whse. Shipment Line"; SalesHeader: Record "Sales Header"; WhseShip: Boolean; WhseReceive: Boolean; ItemLedgShptEntryNo: Integer; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
