### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterPostSalesLines

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9130]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `OnRun`. Standard publisher `OnAfterPostSalesLines` would suit us if it had additional parameter `var TempSalesLineGlobal: Record "Sales Line"`.

![image](https://user-images.githubusercontent.com/70525691/95223994-de737f00-0802-11eb-9f4a-5024d27e842b.png)

local procedure OnAfterPostSalesLines(var SalesHeader: Record "Sales Header"; var SalesShipmentHeader: Record "Sales Shipment Header"; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var ReturnReceiptHeader: Record "Return Receipt Header"; WhseShip: Boolean; WhseReceive: Boolean; var SalesLinesProcessed: Boolean; CommitIsSuppressed: Boolean; EverythingInvoiced: Boolean; **var TempSalesLineGlobal: Record "Sales Line"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
