### ISSUE TITLE
[Event Request] 7302 "WMS Management" OnBeforeSetZoneAndBinsForConsumption

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9132]
Hi Team,

In codeunit 7302, please provide the possibility to have **OnBeforeSetZoneAndBinsForConsumption** event in **SetZoneAndBinsForConsumption** procedure.

![image](https://user-images.githubusercontent.com/57799519/95230644-c4946500-081f-11eb-82b8-37ac352bec68.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeSetZoneAndBinsForConsumption(ItmJnlLine : Record "Item Journal Line";VAR ProdOrderCompLine : Record "Prod. Order Component";VAR WhseJnlLine : Record "Warehouse Journal Line";Location : Record Location;VAR IsHandled: Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
