### ISSUE TITLE
Customer Statement. Standard report call defaults to hardcoded report instead of Report Selection's

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#9133]
It is required to allow custom report to be processing everything if Report Selection is used.

When run from Customer Card (screen from BC16, however BC17 does have the same behavior):
![image](https://user-images.githubusercontent.com/17279234/95230662-d4ee1500-080a-11eb-8b52-9da0b92bd612.png)
This leads to hardcoded definition in TableFilterTxt variable that is used when run Report Selection's report.
![image](https://user-images.githubusercontent.com/17279234/95230708-e6cfb800-080a-11eb-8668-06963337800c.png)
Thus, report other than standard receives wrong request page parameters, all becomes defaulted and no filters/options applied for actual report output.

Either this needs to be redesigned or explained how to use Report Selection properly. In my case it is required to have information from custom report request page (which is supposed to be specified on Report Selections) and now it is not possible - all filters and options are absent.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
