### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnAfterLookup

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9134]
We are migrating our code from NAV 2018 to BC16.4. In the Table 246 "Requisition Line", in the Field 9 "Vendor No.", we need to add our code after the trigger OnLookUp. To do so, we need to add an event publisher, OnAfterLookup, here :

![image](https://user-images.githubusercontent.com/34645582/95307980-98153300-0889-11eb-885b-db7b75e74672.png)

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/95307838-7451ed00-0889-11eb-85f0-b46d255f0a08.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
