### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnValidateVendorNoOnBeforeGetLocationCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9135]
We are migrating our code from NAV 2018 to BC16.4. In the Table 246 "Requisition Line", in the Field 9 "Vendor No.", in the trigger OnValidate, we need to use our own code instead of GetLocationCode. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95309461-74eb8300-088b-11eb-9d9e-57a35c88456a.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95309495-803eae80-088b-11eb-94a1-a4fe0bed44df.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by RomanZanizdra** [comment]
Hi @Magicrevette . There is "IsHandled" pattern in the GetLocationCode function with CurrFieldNo parameter. Doesn't it fit for purposes?

**Comment by Magicrevette** [comment]
Hi @RomanZanizdra . I missed this "IsHandled" in GetLocationCode procedure. Indeed, it fits for my prupose. I no longer need this new event. Thank you.
