### ISSUE TITLE
[Event Request] 7314 "Warehouse Availability Mgt." - OnBeforeCalcInvtAvailQty & OnBeforeCalcQtyAssgndtoPick

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9136]
Hi Team,

In codeunit 7314, please provide the possibility to have **OnBeforeCalcInvtAvailQty** event in **CalcInvtAvailQty** procedure and **OnBeforeCalcQtyAssgndtoPick** event in **CalcQtyAssgndtoPick** procedure.

1.**OnBeforeCalcInvtAvailQty** 

![image](https://user-images.githubusercontent.com/57799519/95309773-32d13a00-08a9-11eb-824c-631f83e306ac.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeCalcInvtAvailQty(Item : Record Item;Location: Record Location;VariantCode : Code[10];VAR WarehouseActivityLine : Record "Warehouse Activity Line";VAR ReturnVal: Decimal;VAR IsHandled: Decimal)

2.**OnBeforeCalcQtyAssgndtoPick**

![image](https://user-images.githubusercontent.com/57799519/95311007-b0497a00-08aa-11eb-945d-cc2a1237cf75.png)

**Event:**
LOCAL [IntegerationEvent] OnBeforeCalcQtyAssgndtoPick(VAR WhseActivLine: Record "Whse. Active Line";Location : Record Location;ItemNo : Code;VariantCode : Code;BinTypeFilter : Text)

_If possible, please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
