### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnBeforeOnValidateStartingTime

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9137]
We are migrating our code from NAV 2018 to BC16.4. In the Table 246 "Requisition Line", in the Field 99000895 "Starting Time", in the trigger OnValidate, we need to add some conditions on the first if. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95319051-aff3b380-0897-11eb-966c-b31bee337450.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95318976-92264e80-0897-11eb-8ef2-4adb449c870b.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
