### ISSUE TITLE
[Enum Request] Table 5717 "Item Cross Reference"

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#9138]
Please convert field(4; "Cross-Reference Type"; Option) to an extensible enum.

**Comment by AlexanderYakunin** [comment]
We are not going to support Cross Reference anymore, this feature replaced by Item Reference, please check 2020 Wave 2 release

**Comment by NKarolak** [comment]
Oh, that's also new to me.
https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave2/smb/dynamics365-business-central/write-longer-item-references
https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-use-item-cross-refs

Then why then is table Item Cross Reference not already marked as pending obsolete?

**Comment by AlexanderYakunin** [comment]
That's long story. We were not able to simple extend vendor item numbers (and therefore Item Cross-reference No.) to Code[50] as this field is in primary key for cross reference table.  In such case we made replacement solution, and introduced new set of tables with longer codes. As this is clearly breaking change for many partner extensions (and good time will be needed to adopt this change) we put Item Reference under feature key and let parallel use of both features depending on partner and customer needs. We will start obsoleting old Cross References with tag '18.0' soon so it will be visible in 2021 Wave 1.
