### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnRunOnBeforeFinalizePosting

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9139]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `OnRun`. Standard publisher `OnRunOnBeforeFinalizePosting` would suit us if it had additional parameters:
1. `GenJnlLineExtDocNo: Code[35]`
2. `var EverythingInvoiced: Boolean `
3. `GenJnlLineDocNo: Code[20] `
4. `SrcCode: Code[10]`

![image](https://user-images.githubusercontent.com/70525691/95329680-02d96500-08b0-11eb-94e8-6d085e8921b4.png)

[IntegrationEvent(false, false)]
local procedure OnRunOnBeforeFinalizePosting(var SalesHeader: Record "Sales Header"; var SalesShipmentHeader: Record "Sales Shipment Header"; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var ReturnReceiptHeader: Record "Return Receipt Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; CommitIsSuppressed: Boolean; **GenJnlLineExtDocNo: Code[35]; var EverythingInvoiced: Boolean; GenJnlLineDocNo: Code[20]; SrcCode: Code[10]**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
