### ISSUE TITLE
EventRequest Table 77 Report Selection OnAfterSaveReportAsPDF

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#914]
We would like to have the Option to handle Report-PDFs after they have been saved as PDF via Report Selection. So please add an OnAfterSaveReportAsPDF Event to table 77. 
 

```
LOCAL SaveReportAsPDF(ReportID : Integer;RecordVariant : Variant;LayoutCode : Code[20]) FilePath : Text[250]
OnBeforeSetReportLayout(RecordVariant);
FilePath := COPYSTR(FileMgt.ServerTempFileName('pdf'),1,250);

ReportLayoutSelection.SetTempLayoutSelected(LayoutCode);
REPORT.SAVEASPDF(ReportID,FilePath,RecordVariant);
ReportLayoutSelection.SetTempLayoutSelected('');

COMMIT;
// START
OnAfterSaveReportAsPDF(ReportID,FilePath,RecordVariant);
// END 

```

Publisher Event Signature

`LOCAL [IntegrationEvent] OnAfterSaveReportAsPDF(ReportID : Integer; FilePAth : Text; RecordVariant : Variant)`

And while you're at it, you could add the OnAfterSaveReportAsHTML() Event as well ;-)

**Comment by JesperSchulz** [comment]
We need to work around the FilePath thing, as we do not want to support files going forward. You may receive a tempblob or stream back.

**Comment by JesperSchulz** [comment]
This request will ship as part of the next major release due to aforementioned File refactoring.

**Comment by JulianTillmann** [comment]
okay, good to know. Then we'll wait what Kind of magic you'll deliver ;-)
