### ISSUE TITLE
[Bug] Table 7302 "Bin Content" - OnBeforeCalcQtyAvailToTake

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#9140]
Hi AL team,

with #8239  a new event "OnBeforeCalcQtyAvailToTake" has been implemented. This makes (as is) no sense for me. I would suggest, to check if IsHandled is true and then return the value of "QtyAvailToTake".

**Comment by RomanZanizdra** [comment]
Hi @bcmako . Looks like it's already there. Does it what you need?
    procedure CalcQtyAvailToTake(ExcludeQtyBase: Decimal): Decimal
    var
        QtyAvailToTake: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcQtyAvailToTake(Rec, ExcludeQtyBase, QtyAvailToTake, IsHandled);
        if IsHandled then
            exit(QtyAvailToTake);

        SetFilterOnUnitOfMeasure();
        CalcFields("Quantity (Base)", "Negative Adjmt. Qty. (Base)", "Pick Quantity (Base)", "ATO Components Pick Qty (Base)");
        exit(
          "Quantity (Base)" -
          (("Pick Quantity (Base)" + "ATO Components Pick Qty (Base)") - ExcludeQtyBase + "Negative Adjmt. Qty. (Base)"));
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
