### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnPostSalesLineOnAfterSetEverythingInvoiced

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9141]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `PostSalesLine`. Standard publisher `OnPostSalesLineOnAfterSetEverythingInvoiced` would suit us if it had additional `IsHandled` parameter.

![image](https://user-images.githubusercontent.com/70525691/95329927-6a8fb000-08b0-11eb-9d95-f779e06e5316.png)

local procedure OnPostSalesLineOnAfterSetEverythingInvoiced(SalesLine: Record "Sales Line"; var EverythingInvoiced: Boolean; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
