### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnBeforeSalesInvLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9142]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `PostSalesLine`. Standard publisher `OnBeforeSalesInvLineInsert` would suit us if it had additional `IsHandled` parameter.

![image](https://user-images.githubusercontent.com/70525691/95330086-b0e50f00-08b0-11eb-9202-370702e97f02.png)

local procedure OnBeforeSalesInvLineInsert(var SalesInvLine: Record "Sales Invoice Line"; SalesInvHeader: Record "Sales Invoice Header"; SalesLine: Record "Sales Line"; CommitIsSuppressed: Boolean; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
