### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterSalesInvLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9143]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `PostSalesLine`. Standard publisher `OnAfterSalesInvLineInsert` would suit us if it had additional parameter `var TempWhseShptHeader: Record "Warehouse Shipment Header"` and `var TempWhseRcptHeader: Record "Warehouse Receipt Header"`.

![image](https://user-images.githubusercontent.com/70525691/95330377-25b84900-08b1-11eb-86c7-c0b80cb38fb0.png)

local procedure OnAfterSalesInvLineInsert(var SalesInvLine: Record "Sales Invoice Line"; SalesInvHeader: Record "Sales Invoice Header"; SalesLine: Record "Sales Line"; ItemLedgShptEntryNo: Integer; WhseShip: Boolean; WhseReceive: Boolean; CommitIsSuppressed: Boolean; var SalesHeader: Record "Sales Header"; var TempItemChargeAssgntSales: Record "Item Charge Assignment (Sales)" temporary; **var TempWhseShptHeader: Record "Warehouse Shipment Header"; var TempWhseRcptHeader: Record "Warehouse Receipt Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
