### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnBeforeSalesCrMemoLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9145]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `PostSalesLine`. Standard publisher `OnBeforeSalesCrMemoLineInsert` would suit us if it had additional parameter `var IsHandled: Boolean`.

![image](https://user-images.githubusercontent.com/70525691/95331193-4df47780-08b2-11eb-8379-717428a715ae.png)

local procedure OnBeforeSalesCrMemoLineInsert(var SalesCrMemoLine: Record "Sales Cr.Memo Line"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; SalesLine: Record "Sales Line"; CommitIsSuppressed: Boolean; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
