### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterSalesCrMemoLineInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9146]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `PostSalesLine`. Standard publisher `OnAfterSalesCrMemoLineInsert` would suit us if it had additional parameters:

1. `WhseShip: Boolean `
2. `WhseReceive: Boolean `
3. `TempWhseShptHeader: Record "Warehouse Shipment Header" `
4. `TempWhseRcptHeader: Record "Warehouse Receipt Header"`

![image](https://user-images.githubusercontent.com/70525691/95332772-8b5a0480-08b4-11eb-9604-2d3fd0a6a52d.png)

local procedure OnAfterSalesCrMemoLineInsert(var SalesCrMemoLine: Record "Sales Cr.Memo Line"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var TempItemChargeAssgntSales: Record "Item Charge Assignment (Sales)" temporary; CommitIsSuppressed: Boolean; **WhseShip: Boolean; WhseReceive: Boolean; TempWhseShptHeader: Record "Warehouse Shipment Header"; TempWhseRcptHeader: Record "Warehouse Receipt Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
