### ISSUE TITLE
[Change Request] page 5703 "Location Card" procedure UpdateEnabled

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#9147]
Could you please make the procedure UpdateEnabled available for page extensions in page 5703 "Location Card"?
```
page 5703 "Location Card"   
   ...

    // >>>>>>>>>>>>>>>>>>
    //local procedure UpdateEnabled()
    procedure UpdateEnabled()
    // <<<<<<<<<<<<<<
    begin
        RequirePickEnable := not "Use As In-Transit" and not "Directed Put-away and Pick";
        RequirePutAwayEnable := not "Use As In-Transit" and not "Directed Put-away and Pick";
...
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
