### ISSUE TITLE
[Refactor Request] Codeunit 5802 "Inventory Posting To G/L"

### ISSUE THREAD

**Issue by Zoltero** [microsoft/ALAppExtensions#9150]
We are migrating our code from BC140 C/AL to BC160/170.
We have a routine to create fixed asset based on item no. from purchase order.
The function uses codeunit 22 and from there codeunit 5802 to post the G/L entry.
In old version we made a change in codeunit 5802, but this not allowed anymore.
Still we need to do the posting through codeunit 5802 to get the same initiation of variable to post general journal.
If not the next entry no. is being mixed up.

Can you move the call of GenJnlPostLine.RunWithCheck(GenJnlLine) to it's own global function ?

![image](https://user-images.githubusercontent.com/32673197/95336514-0f11f200-08b1-11eb-8f95-594d5e980188.png)

Below follows an example of how it can be solved:
![image](https://user-images.githubusercontent.com/32673197/95338152-e985e800-08b2-11eb-945f-3d03400251c5.png)

I hope this will be possible to solve.
Thank you ! :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
