### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterReturnRcptHeaderInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9153]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `InsertReturnReceiptHeader`. Standard publisher `OnAfterReturnRcptHeaderInsert` would suit us if it had additional parameters:

`WhseShip: Boolean, WhseReceive: Boolean, TempWhseShptHeader: Record "Warehouse Shipment Header", TempWhseRcptHeader: Record "Warehouse Receipt Header"`

![image](https://user-images.githubusercontent.com/70525691/95339681-fc9db580-08bc-11eb-8aad-71a96320ee87.png)

local procedure OnAfterReturnRcptHeaderInsert(var ReturnReceiptHeader: Record "Return Receipt Header"; SalesHeader: Record "Sales Header"; SuppressCommit: Boolean; **WhseShip: Boolean; WhseReceive: Boolean; TempWhseShptHeader: Record "Warehouse Shipment Header"; TempWhseRcptHeader: Record "Warehouse Receipt Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
