### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterPostGLAndCustomer

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9155]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `PostGLAndCustomer`. Standard publisher `OnAfterPostGLAndCustomer` would suit us if it had additional parameters:

1. `WhseShptHeader: Record "Warehouse Shipment Header"`
2. `WhseShip: Boolean`
3. `var TempWhseShptHeader: Record "Warehouse Shipment Header"`
4. `var SalesInvHeader: Record "Sales Invoice Header"`
5. `var CustLedgEntry: Record "Cust. Ledger Entry"`
6.` GenJnlLineDocNo: Code[20]`
7. `GenJnlLineExtDocNo: Code[35]`
8. `var SalesCrMemoHeader: Record "Sales Cr.Memo Header"`
9. `var SrcCode: Code[10]`
10. `var GenJnlLineDocType: Integer`

![image](https://user-images.githubusercontent.com/70525691/95340650-14296e00-08be-11eb-811b-ac8343312708.png)

local procedure OnAfterPostGLAndCustomer(var SalesHeader: Record "Sales Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; TotalSalesLine: Record "Sales Line"; TotalSalesLineLCY: Record "Sales Line"; CommitIsSuppressed: Boolean; **WhseShptHeader: Record "Warehouse Shipment Header"; WhseShip: Boolean; var TempWhseShptHeader: Record "Warehouse Shipment Header" temporary; var SalesInvHeader: Record "Sales Invoice Header"; var CustLedgEntry: Record "Cust. Ledger Entry"; GenJnlLineDocNo: Code[20]; GenJnlLineExtDocNo: Code[35]; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var SrcCode: Code[10]; var GenJnlLineDocType: Integer**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
