### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnValidateActionMessageOnBeforeTestField

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9156]
We are migrating our code from NAV 2018 to BC16.4. In the Table 246 "Requisition Line", in the field 99000916 "Action Message", in the trigger OnValidate, we need to add our code before the TestField(). To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95340670-b729ba00-08b5-11eb-8df8-7f2f0c453399.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95340608-a7aa7100-08b5-11eb-87f2-81e5018c90ef.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
