### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnDeleteRelationsOnBeforePlanningComponentDelete

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9159]
We are migrating our code from NAV 2018 to BC16.4. In the Table 246 "Requisition Line", in the procedure DeleteRelations, we need to add a condition before the procedure "PlanningComponent.Delete(true)". To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95353968-2ad2c380-08c4-11eb-931b-b068c614197c.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95353997-34f4c200-08c4-11eb-8e6e-a6c0519c1637.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
