### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnAfterSetUpNewLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9160]
We are migrating our code from NAV 2018 to BC16.4. In the Table 246 "Requisition Line", in the procedure SetUpNewLine, we need to add our code at the end of the procedure. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95358251-2361e900-08c9-11eb-9da4-639497d82b5e.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95358206-16dd9080-08c9-11eb-9032-a0c3fd44fdb6.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
