### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopySalesLineOnBeforeCheckLocationOnWMS

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9161]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopySalesLine` we would like to perform some additional checks before running `ToSalesLine.CheckLocationOnWMS`, for that a handler event would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95423107-36b49900-0949-11eb-905a-02210fbafefb.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopySalesLineOnBeforeCheckLocationOnWMS(var ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; var FromSalesLine: Record "Sales Line"; var isHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
