### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopySalesLineOnBeforeSalesLineAutoReserve

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9162]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopySalesLine` we would like to perform some additional checks before running `ToSalesLine.AutoReserve`, for that a handler event would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95423400-b0e51d80-0949-11eb-8207-ad3f69c172b4.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopySalesLineOnBeforeSalesLineAutoReserve(var ToSalesLine: Record "Sales Line"; var ToSalesHeader: Record "Sales Header"; var isHandled: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
