### ISSUE TITLE
Table 36 Sales Header OnBeforeGetNoSeriesCode event handling change

### ISSUE THREAD

**Issue by JalmarazMartn** [microsoft/ALAppExtensions#9163]
Good morning, in the function GetNoSeriesCode on Sales Header Table (36) we have this code:

  IsHandled := false;
        OnBeforeGetNoSeriesCode(Rec, SalesSetup, NoSeriesCode, IsHandled);
        if IsHandled then
            exit;

This doesn,t help much to the develop if you don´t return NoSeriesCode, this way:

  IsHandled := false;
        OnBeforeGetNoSeriesCode(Rec, SalesSetup, NoSeriesCode, IsHandled);
        if IsHandled then
            exit(**NoSeriesCode**);

Can you change the code? Regards.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by JalmarazMartn** [comment]
Thank you, have a nice day.

**Comment by JalmarazMartn** [comment]
> Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

Thank you, have a nice day.
