### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnUpdateSalesHeaderWhenCopyFromSalesHeaderOnAfterCopySellToAddressToShipToAddress

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9164]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `UpdateSalesHeaderWhenCopyFromSalesHeader` we would like to run some custom code before `Validate("Ship-to Code")`, for that an event would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95424315-200f4180-094b-11eb-820b-aee7cb7e5ef8.png)
```
[IntegrationEvent(false, false)]
local procedure OnUpdateSalesHeaderWhenCopyFromSalesHeaderOnAfterCopySellToAddressToShipToAddress(var SalesHeader: Record "Sales Header");
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
