### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnAfterCheckSalesRounding

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9165]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `OnAfterCheckSalesRounding` we would like to run some custom code after procedure code is executed, for that an event at the end of procedure code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95425018-4ed9e780-094c-11eb-86e3-6d098aae99f3.png)
```
[IntegrationEvent(false, false)]
local procedure OnAfterCheckSalesRounding(var FromSalesLine: Record "Sales Line"; var RoundingLineInserted: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
