### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopySalesInvLinesToDocOnAfterCopySalesLine

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9167]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopySalesInvLinesToDoc` we would like to run some custom code after saleslines are copied, for that an event at end of repeat code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95426563-c446b780-094e-11eb-860a-1f9212e758a9.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopySalesInvLinesToDocOnAfterCopySalesLine(ToSalesLine: Record "Sales Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
