### ISSUE TITLE
[Event Request] table 336 "Tracking Specification" procedure TrackingExists

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9168]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure TrackingExists in table 336 Tracking Specification

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnTrackingExistsOnBeforeExit(TrackingSpecification: record "Tracking Specification";var TrackExists: boolean; var IsHandled: boolean)
begin
end;

Both parameters TrackExists and IsHandled are referenced as var.

The code in procedure "TrackingExists" in table 336 "Tracking Specification" would be modified as follows:

OLD CODE:

....

procedure TrackingExists(): Boolean
begin
  exit(("Serial No." <> '') or ("Lot No." <> ''));
end;

NEW CODE:

....

procedure TrackingExists(): Boolean
//new code start
var
  IsHandled: boolean;
  TrackExists: boolean;
//new code end
begin
  //new code begin
  IsHandled := false;
  OnTrackingExistsOnBeforeExit(Rec,TrackExists,IsHandled);
  if IsHandled then 
    exit(TrackExists)
  else	
  //new code end
  
    exit(("Serial No." <> '') or ("Lot No." <> ''));
end;
.....

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @mcarmenvalera , at current time function looks like below. I suppose it fits your requirement, doesn't it?
    procedure TrackingExists() IsTrackingExist: Boolean
    begin
        IsTrackingExist := ("Serial No." <> '') or ("Lot No." <> '');

        OnAfterTrackingExist(Rec, IsTrackingExist);
    end;

**Comment by mcarmenvalera** [comment]
Hi Roman,

I have checked the code in a BC 16.5 version (sorry, it was the available version at that moment). If you mean that a version 16.6 (I’m going to download an image) already has this code then is ok with me.

Sorry for the inconvenience!

Best regards.


Mari Carmen Valera | NUNSYS
Dynamics Developer
Calle Gustave Eiffel, 3. Parque Tecnológico. Paterna, Valencia. 46980. Spain
+34 960 500 631www.nunsys.com
“El contenido de este correo electrónico y en su caso de sus ficheros adjuntos son de carácter PRIVADO y CONFIDENCIAL, siendo para uso exclusivo de su destinatario. Si usted no es el destinatario correcto, el empleado o agente responsable de entregar el mensaje al destinatario, o lo ha recibido por error, le advertimos que según la legislación vigente está totalmente prohibido divulgarlo, distribuirlo o reproducirlo y le rogamos nos avise de inmediato procediendo a su destrucción. De conformidad con lo dispuesto en las normativas vigentes en protección de datos personales, el Reglamento (UE) 2016/679 de 27 de abril de 2016 (GDPR) y la Ley Orgánica de Protección de Datos en España y sus normas de desarrollo, le informamos que El Responsable del tratamiento de sus datos, NUNSYS, S.L., tratará sus datos personales con la finalidad de gestionar las comunicaciones realizadas a través del email de los servicios prestados, información comercial o de las actividades realizadas por el Responsable. La legitimación para el uso de sus datos está basada en la ejecución de un contrato o prestación de servicios. No se cederán datos a terceros, salvo obligación legal. Los datos serán destruidos una vez comunique su baja y/o finalizados los períodos legales de conservación. Los interesados podrán ejercitar sus derechos de acceso, rectificación, supresión, olvido, portabilidad y limitación del tratamiento mediante notificación escrita a la dirección: NUNSYS C/. Gustave Eiffel 3, Parque Tecnológico 46980 Paterna-Valencia o por correo electrónico a: dpo@nunsys.com Info adicional: Política de privacidad”
 
De: RomanZanizdra [mailto:notifications@github.com]
Enviado el: miércoles, 14 de octubre de 2020 12:10
Para: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
CC: Mari Carmen Valera | NUNSYS <maricarmen.valera@nunsys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [microsoft/ALAppExtensions] [Event Request] table 336 "Tracking Specification" procedure TrackingExists (#9168)


Hi @mcarmenvalera<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcarmenvalera&data=02%7C01%7Cmaricarmen.valera%40nunsys.com%7Cef046f5d2b21432c128508d870295277%7Cd975a545c57145d782a8b50dabde283c%7C0%7C1%7C637382670083542208&sdata=DePJQn06mKux8GS7xIsYAbNg%2FOBk2XNBIlprJlDSE4c%3D&reserved=0> , at current time function looks like below. I suppose it fits your requirement, doesn't it?
procedure TrackingExists() IsTrackingExist: Boolean
begin
IsTrackingExist := ("Serial No." <> '') or ("Lot No." <> '');

    OnAfterTrackingExist(Rec, IsTrackingExist);

end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
