### ISSUE TITLE
[Event Request] table 337 "Reservation Entry" procedure TrackingExists

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9170]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure TrackingExists in table 337 Reservation Entry

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnTrackingExistsOnBeforeExit(TrackingSpecification: record "Tracking Specification";var TrackExists: boolean; var IsHandled: boolean)
begin
end;

Both parameters TrackExists and IsHandled are referenced as var.

The code in procedure "TrackingExists" in table 337 "Tracking Specification" would be modified as follows:

OLD CODE:

....

procedure TrackingExists(): Boolean
begin
  exit(("Serial No." <> '') or ("Lot No." <> ''));
end;

NEW CODE:

....

procedure TrackingExists(): Boolean
//new code start
var
  IsHandled: boolean;
  TrackExists: boolean;
//new code end
begin
  //new code begin
  IsHandled := false;
  OnTrackingExistsOnBeforeExit(Rec,TrackExists,IsHandled);
  if IsHandled then 
    exit(TrackExists)
  else	
  //new code end
  
    exit(("Serial No." <> '') or ("Lot No." <> ''));
end;
.....

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @mcarmenvalera , function looks like below. I suppose it fits your requirement, doesn't it?
    procedure TrackingExists() IsTrackingExists: Boolean
    begin
        IsTrackingExists := ("Serial No." <> '') or ("Lot No." <> '');

        OnAfterTrackingExists(Rec, IsTrackingExists);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
