### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnGetLocationOnBeforeLocationGet

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9171]
We are migrating our code from NAV 2018 to BC16.4. In the Table 246 "Requisition Line", in the procedure GetLocation, we need to modify the condition of the if inside the else, before "Location.Get". To do so, we need a IsHandled flag and an event publisher, like this : 

![image](https://user-images.githubusercontent.com/34645582/95428865-e2f67f80-0949-11eb-8a02-a83a7b6ea0df.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95428768-c3f7ed80-0949-11eb-9ca0-209f1110e252.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
```
    local procedure GetLocation(LocationCode: Code[10])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetLocation(Rec, Location, LocationCode, IsHandled);
        if IsHandled then
            exit;
```
