### ISSUE TITLE
[Event Request] table 5773 "Registered Whse. Activity Line" procedure SetTrackingFilterFromSpec

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9172]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure SetTrackingFilterFromSpec in table 5773 "Registered Whse. Activity Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnSetTrackingFilterFromSpecOnAfterSetFilters(var RegisteredWhseActivityLine: Record "Registered Whse. Activity Line";TrackingSpecification: Record "Tracking Specification")
begin
end;

The code in procedure "SetTrackingFilterFromSpec" in table 5773 "Registered Whse. Activity Line" would be modified as follows:

OLD CODE:

....

procedure SetTrackingFilterFromSpec(TrackingSpecification: Record "Tracking Specification")
    begin
        SetRange("Serial No.", TrackingSpecification."Serial No.");
        SetRange("Lot No.", TrackingSpecification."Lot No.");
    end;

NEW CODE:

....

procedure SetTrackingFilterFromSpec(TrackingSpecification: Record "Tracking Specification")
    begin
        SetRange("Serial No.", TrackingSpecification."Serial No.");
        SetRange("Lot No.", TrackingSpecification."Lot No.");

	//start new code
	OnSetTrackingFilterFromSpecOnAfterSetFilters(Rec,TrackingSpecification);
	//end new code
    end;
.....

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @mcarmenvalera , looks like you use not the latest version of app. Required event is already there.
    procedure SetTrackingFilterFromSpec(TrackingSpecification: Record "Tracking Specification")
    begin
        SetRange("Serial No.", TrackingSpecification."Serial No.");
        SetRange("Lot No.", TrackingSpecification."Lot No.");

        OnAfterSetTrackingFilterFromSpec(Rec, TrackingSpecification);
    end;

**Comment by mcarmenvalera** [comment]
Hi Roman,

Please, correct me if I’m wrong: I’ve checked that this event (and the two mentioned in previous mails) are in BC17 (2020 wave 2), but they are not in BC16 cu 6. This means that those events would not be available in the following cumulative updates for BC16 (cumulative 7 and up)?

Thanks in advance.

Best regards.


Mari Carmen Valera | NUNSYS
Dynamics Developer
Calle Gustave Eiffel, 3. Parque Tecnológico. Paterna, Valencia. 46980. Spain
+34 960 500 631www.nunsys.com
“El contenido de este correo electrónico y en su caso de sus ficheros adjuntos son de carácter PRIVADO y CONFIDENCIAL, siendo para uso exclusivo de su destinatario. Si usted no es el destinatario correcto, el empleado o agente responsable de entregar el mensaje al destinatario, o lo ha recibido por error, le advertimos que según la legislación vigente está totalmente prohibido divulgarlo, distribuirlo o reproducirlo y le rogamos nos avise de inmediato procediendo a su destrucción. De conformidad con lo dispuesto en las normativas vigentes en protección de datos personales, el Reglamento (UE) 2016/679 de 27 de abril de 2016 (GDPR) y la Ley Orgánica de Protección de Datos en España y sus normas de desarrollo, le informamos que El Responsable del tratamiento de sus datos, NUNSYS, S.L., tratará sus datos personales con la finalidad de gestionar las comunicaciones realizadas a través del email de los servicios prestados, información comercial o de las actividades realizadas por el Responsable. La legitimación para el uso de sus datos está basada en la ejecución de un contrato o prestación de servicios. No se cederán datos a terceros, salvo obligación legal. Los datos serán destruidos una vez comunique su baja y/o finalizados los períodos legales de conservación. Los interesados podrán ejercitar sus derechos de acceso, rectificación, supresión, olvido, portabilidad y limitación del tratamiento mediante notificación escrita a la dirección: NUNSYS C/. Gustave Eiffel 3, Parque Tecnológico 46980 Paterna-Valencia o por correo electrónico a: dpo@nunsys.com Info adicional: Política de privacidad”
 
De: RomanZanizdra [mailto:notifications@github.com]
Enviado el: miércoles, 14 de octubre de 2020 12:49
Para: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
CC: Mari Carmen Valera | NUNSYS <maricarmen.valera@nunsys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [microsoft/ALAppExtensions] [Event Request] table 5773 "Registered Whse. Activity Line" procedure SetTrackingFilterFromSpec (#9172)


Hi @mcarmenvalera<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcarmenvalera&data=02%7C01%7Cmaricarmen.valera%40nunsys.com%7C1a518c60af374ecb597a08d8702ebd94%7Cd975a545c57145d782a8b50dabde283c%7C0%7C0%7C637382693331062905&sdata=lqnj8VxyZxo0AE0WydbYSBPFx4T7V%2BYgvCgxqBCaFho%3D&reserved=0> , looks like you use not the latest version of app. Required event is already there.
procedure SetTrackingFilterFromSpec(TrackingSpecification: Record "Tracking Specification")
begin
SetRange("Serial No.", TrackingSpecification."Serial No.");
SetRange("Lot No.", TrackingSpecification."Lot No.");

    OnAfterSetTrackingFilterFromSpec(Rec, TrackingSpecification);

end;

**Comment by mcarmenvalera** [comment]
Hi Roman,

Ok then. I just wanted to confirm this.

Thank you!

Best regards


Mari Carmen Valera | NUNSYS
Dynamics Developer
Calle Gustave Eiffel, 3. Parque Tecnológico. Paterna, Valencia. 46980. Spain
+34 960 500 631www.nunsys.com
“El contenido de este correo electrónico y en su caso de sus ficheros adjuntos son de carácter PRIVADO y CONFIDENCIAL, siendo para uso exclusivo de su destinatario. Si usted no es el destinatario correcto, el empleado o agente responsable de entregar el mensaje al destinatario, o lo ha recibido por error, le advertimos que según la legislación vigente está totalmente prohibido divulgarlo, distribuirlo o reproducirlo y le rogamos nos avise de inmediato procediendo a su destrucción. De conformidad con lo dispuesto en las normativas vigentes en protección de datos personales, el Reglamento (UE) 2016/679 de 27 de abril de 2016 (GDPR) y la Ley Orgánica de Protección de Datos en España y sus normas de desarrollo, le informamos que El Responsable del tratamiento de sus datos, NUNSYS, S.L., tratará sus datos personales con la finalidad de gestionar las comunicaciones realizadas a través del email de los servicios prestados, información comercial o de las actividades realizadas por el Responsable. La legitimación para el uso de sus datos está basada en la ejecución de un contrato o prestación de servicios. No se cederán datos a terceros, salvo obligación legal. Los datos serán destruidos una vez comunique su baja y/o finalizados los períodos legales de conservación. Los interesados podrán ejercitar sus derechos de acceso, rectificación, supresión, olvido, portabilidad y limitación del tratamiento mediante notificación escrita a la dirección: NUNSYS C/. Gustave Eiffel 3, Parque Tecnológico 46980 Paterna-Valencia o por correo electrónico a: dpo@nunsys.com Info adicional: Política de privacidad”
 
De: RomanZanizdra [mailto:notifications@github.com]
Enviado el: miércoles, 14 de octubre de 2020 15:57
Para: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
CC: Mari Carmen Valera | NUNSYS <maricarmen.valera@nunsys.com>; Mention <mention@noreply.github.com>
Asunto: Re: [microsoft/ALAppExtensions] [Event Request] table 5773 "Registered Whse. Activity Line" procedure SetTrackingFilterFromSpec (#9172)


Hi @mcarmenvalera<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcarmenvalera&data=02%7C01%7Cmaricarmen.valera%40nunsys.com%7Cae916a75be4b4fbb1f7208d8704907fd%7Cd975a545c57145d782a8b50dabde283c%7C0%7C0%7C637382806248054859&sdata=t2iT1HjrP%2FzkUXrUmepgNzufzHQ9heEUQyLpiJuxtj0%3D&reserved=0> . Yes, you are right. We do events for the latest version, which is 17 for now. So mentioned events will be available in 17.1 I suppose, but not in any of 16 version. If you really need some events to be implemented from higher version, please reach out the support channel to process your request as a hotfix.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
