### ISSUE TITLE
[Event Request] table 6550 "Whse. Item Tracking Line" procedure InitExpirationDate

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9173]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure InitExpirationDate in table 6550 "Whse. Item Tracking Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnInitExpirationDateOnBeforeCheckTracking(WhseItemTrackingLine: Record "Whse. Item Tracking Line"; xRecWhseItemTrackingLine: Record "Whse. Item Tracking Line"; var IsHandled: boolean)
begin
end;

The code in procedure "InitExpirationDate" in table 6550 "Whse. Item Tracking Line" would be modified as follows:

OLD CODE:

....

    procedure InitExpirationDate()
    var
        Location: Record Location;
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        ExpDate: Date;
        WarDate: Date;
    begin
        if ("Serial No." = xRec."Serial No.") and ("Lot No." = xRec."Lot No.") then
            exit;

        "Expiration Date" := 0D;
        "Buffer Status2" := 0;

        Location.Init();
        if "Location Code" <> '' then
            Location.Get("Location Code");

        if ItemTrackingMgt.GetWhseExpirationDate("Item No.", "Variant Code", Location, "Lot No.", "Serial No.", ExpDate) then begin
            "Expiration Date" := ExpDate;
            "Buffer Status2" := "Buffer Status2"::"ExpDate blocked";
        end;

        if IsReclass("Source Type", "Source Batch Name") then begin
            "New Expiration Date" := "Expiration Date";
            if ItemTrackingMgt.GetWhseWarrantyDate("Item No.", "Variant Code", Location, "Lot No.", "Serial No.", WarDate) then
                "Warranty Date" := WarDate;
        end;
    end;

NEW CODE:

....

    procedure InitExpirationDate()
    var
        Location: Record Location;
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        ExpDate: Date;
        WarDate: Date;
	//new code
	IsHandled: boolean
	//new code
    begin
	//new code start
	IsHandled:=false;
        OnInitExpirationDateOnBeforeCheckTracking(Rec,xRec, IsHandled);
	if IsHandled then 
	  exit;
	//new code end

        if ("Serial No." = xRec."Serial No.") and ("Lot No." = xRec."Lot No.") then
            exit;

        "Expiration Date" := 0D;
        "Buffer Status2" := 0;

        Location.Init();
        if "Location Code" <> '' then
            Location.Get("Location Code");

        if ItemTrackingMgt.GetWhseExpirationDate("Item No.", "Variant Code", Location, "Lot No.", "Serial No.", ExpDate) then begin
            "Expiration Date" := ExpDate;
            "Buffer Status2" := "Buffer Status2"::"ExpDate blocked";
        end;

        if IsReclass("Source Type", "Source Batch Name") then begin
            "New Expiration Date" := "Expiration Date";
            if ItemTrackingMgt.GetWhseWarrantyDate("Item No.", "Variant Code", Location, "Lot No.", "Serial No.", WarDate) then
                "Warranty Date" := WarDate;
        end;
    end;
.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
