### ISSUE TITLE
[Event Request] Page 99000882 Change Status on Prod. Order - OnBeforeReturnPostingInfo

### ISSUE THREAD

**Issue by sukumar5893** [microsoft/ALAppExtensions#9177]
Hi Team,

In Page 99000882 please provide the possibility to have event **OnBeforeReturnPostingInfo** in procedure **ReturnPostingInfo**

![image](https://user-images.githubusercontent.com/26245501/95434675-2e6f5480-096f-11eb-8eef-7aaa5b6e7827.png)

**Event:**
![image](https://user-images.githubusercontent.com/26245501/95434839-5eb6f300-096f-11eb-9e5a-53ffb6261b1e.png)

**Please backport to BC14 also.**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
