### ISSUE TITLE
[Event Request] Report 11005 “VAT Statement Germany” - New Event “OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling”

### ISSUE THREAD

**Issue by StSdt** [microsoft/ALAppExtensions#9178]
Could we please have a new publisher “OnBeforeCalcTotalAmountVATEntryTotaling” for function “CalcLineTotal” of Report 11005 "VAT Statement Germany"?

procedure CalcLineTotal(VATStmtLine2: Record "VAT Statement Line"; var TotalAmount: Decimal; var TotalEmpty: Decimal; var TotalBase: Decimal; var TotalUnrealizedAmount: Decimal; var TotalUnrealizedBase: Decimal; Level: Integer): Boolean
begin
:
VATStmtLine2.Type::"VAT Entry Totaling":
begin
  :
  VATStmtLine2."Amount Type"::"Unrealized Base":
      begin
          VATEntry.CalcSums("Remaining Unrealized Base", "Add.-Curr. Rem. Unreal. Base");
          Amount := ConditionalAdd(0, VATEntry."Remaining Unrealized Base", VATEntry."Add.-Curr. Rem. Unreal. Base");
      end;
  end;
  // >>>>>>>
  OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling(VATStmtLine2, VATEntry, Amount, UseAmtsInAddCurr);
  // <<<<<<<
  CalcTotalAmount(VATStmtLine2, TotalAmount, TotalEmpty, TotalBase, TotalUnrealizedAmount, TotalUnrealizedBase);
end;
VATStmtLine2.Type::"Row Totaling":
:

// >>>>>>>>                    
[IntegrationEvent(false, false)]
local procedure OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling (VATStmtLine: Record "VAT Statement Line"; var VATEntry: Record “VAT Entry”; var Amount: Decimal; UseAmtsInAddCurr: Boolean)
begin
end;
// <<<<<<<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
