### ISSUE TITLE
Table 456 Posted Approval Entry doesnt have a LookupPageID & DrillDownPageID

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9179]
In NAV 2019 the table 456 Posted Approval Entry doesnt have a LookupPageID. In NAV2017 it does have the properties

See a below the properties in NAV2017. Can you also add them in NAV2019.

![image](https://user-images.githubusercontent.com/11609736/95442746-0e826580-095c-11eb-927b-7e055c35c1c6.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
