### ISSUE TITLE
[Event Request] Table 9053 "Sales Cue" - OnCalculateAverageDaysDelayedOnBeforeSumDelayDays

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9180]
We are migrating our code from NAV 2018 to BC16.4. In the Table 9053 "Sales Cue", in the procedure CalculateAverageDaysDelayed, we need to add a condition inside the repeat. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95443605-11ca2100-095d-11eb-807e-27f3b75c8da7.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95442932-3f629a80-095c-11eb-9c0c-937d73e0a047.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
