### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopyPurchInvLinesToDocOnBeforeCheckPurchLineType

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9181]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopyPurchInvLinesToDoc` we would like to run some custom code before running code depending on purchase line type, for that an event before checking line type would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95442801-7e94e980-0964-11eb-8315-4a50cd38aa9c.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopyPurchInvLinesToDocOnBeforeCheckPurchLineType(FromPurchInvLine: Record "Purch. Inv. Line"; NextLineNo: Integer)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
