### ISSUE TITLE
[Event Request] table 5767 "Warehouse Activity Line" procedure SetTrackingFilterFromBinContentBuffer

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9182]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure SetTrackingFilterFromBinContentBuffer in table 5767 "Warehouse Activity Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnAfterSetTrackingFilterFromBinContentBuffer(**var** WarehouseActivityLine: Record "Warehouse Activity Line"; BinContentBuffer: Record "Bin Content Buffer")
begin
end;

The code in procedure "SetTrackingFilterFromBinContentBuffer" in table 5767 "Whse. Item Tracking Line" would be modified as follows:

OLD CODE:

....

  procedure SetTrackingFilterFromBinContentBuffer(BinContentBuffer: Record "Bin Content Buffer")
    begin
        SetRange("Serial No.", BinContentBuffer."Serial No.");
        SetRange("Lot No.", BinContentBuffer."Lot No.");
    end;

....

NEW CODE:

...

  procedure SetTrackingFilterFromBinContentBuffer(BinContentBuffer: Record "Bin Content Buffer")
    begin
        SetRange("Serial No.", BinContentBuffer."Serial No.");
        SetRange("Lot No.", BinContentBuffer."Lot No.");

	//new code start
	OnAfterSetTrackingFilterFromBinContentBuffer(Rec, BinContentBuffer);
	//new code end
    end;

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
