### ISSUE TITLE
[Event Request] SetOperationType on Service Header (Italian localization)

### ISSUE THREAD

**Issue by gpintaudi** [microsoft/ALAppExtensions#9183]
It would be helpful if you could add events in SetOperationType procedure on Service Header table in this same way of Sales Header and Purchase Header.
In particular, event OnBeforeSetOperationType with IsHandled parameter is missing.
![image](https://user-images.githubusercontent.com/64265795/95447823-a71be400-0962-11eb-971a-8b7bbcf7ba55.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
