### ISSUE TITLE
[Event Request] table 5767 "Warehouse Activity Line" procedure SetTrackingFilterToWhseEntryIfRequired

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9184]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure SetTrackingFilterToWhseEntryIfRequired in table 5767 "Warehouse Activity Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnAfterSetTrackingFilterToWhseEntryIfRequired(**var** WarehouseEntry: Record "Warehouse Entry"; WhseActivityLine: Record "Warehouse Activity Line")
begin
end;

The code in procedure "SetTrackingFilterToWhseEntryIfRequired" in table 5767 "Whse. Item Tracking Line" would be modified as follows:

OLD CODE:

....

    procedure SetTrackingFilterToWhseEntryIfRequired(var WhseEntry: Record "Warehouse Entry"; WhseItemTrackingSetup: Record "Item Tracking Setup")
    begin
        if "Serial No." <> '' then
            if WhseItemTrackingSetup."Serial No. Required" then
                WhseEntry.SetRange("Serial No.", "Serial No.")
            else
                WhseEntry.SetFilter("Serial No.", '%1|%2', "Serial No.", '');
        if "Lot No." <> '' then
            if WhseItemTrackingSetup."Lot No. Required" then
                WhseEntry.SetRange("Lot No.", "Lot No.")
            else
                WhseEntry.SetFilter("Lot No.", '%1|%2', "Lot No.", '');
    end;

....

NEW CODE:

...

    procedure SetTrackingFilterToWhseEntryIfRequired(var WhseEntry: Record "Warehouse Entry"; WhseItemTrackingSetup: Record "Item Tracking Setup")
    begin
        if "Serial No." <> '' then
            if WhseItemTrackingSetup."Serial No. Required" then
                WhseEntry.SetRange("Serial No.", "Serial No.")
            else
                WhseEntry.SetFilter("Serial No.", '%1|%2', "Serial No.", '');
        if "Lot No." <> '' then
            if WhseItemTrackingSetup."Lot No. Required" then
                WhseEntry.SetRange("Lot No.", "Lot No.")
            else
                WhseEntry.SetFilter("Lot No.", '%1|%2', "Lot No.", '');

        //new code begin
	OnAfterSetTrackingFilterToWhseEntryIfRequired(WhseEntry, Rec)
	//new code end
    end;

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
