### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" procedure InsertTransferEntry

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9185]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure InsertTransferEntry in codeunit 22 "Item Jnl.-Post Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnInsertTransferEntryOnBeforeInitTransValueEntry(var TempItemEntryRelation: Record "Item Entry Relation" temporary; ItemLedgerEntry: Record "Item Ledger Entry";Item: Record Item)
begin
end;

The code in procedure "InsertTransferEntry" in codeunit 22 "Item Jnl.-Post Line" would be modified as follows:

OLD CODE:

....

    local procedure InsertTransferEntry(var ItemLedgEntry: Record "Item Ledger Entry"; var OldItemLedgEntry: Record "Item Ledger Entry"; AppliedQty: Decimal)
    var
        NewItemLedgEntry: Record "Item Ledger Entry";
        NewValueEntry: Record "Value Entry";
        ItemLedgEntry2: Record "Item Ledger Entry";
        IsReserved: Boolean;
    begin
        with ItemJnlLine do begin
            InitItemLedgEntry(NewItemLedgEntry);
            NewItemLedgEntry."Applies-to Entry" := 0;
            NewItemLedgEntry.Quantity := -AppliedQty;
            NewItemLedgEntry."Invoiced Quantity" := NewItemLedgEntry.Quantity;
            NewItemLedgEntry."Remaining Quantity" := NewItemLedgEntry.Quantity;
            NewItemLedgEntry.Open := NewItemLedgEntry."Remaining Quantity" <> 0;
            NewItemLedgEntry.Positive := NewItemLedgEntry."Remaining Quantity" > 0;
            NewItemLedgEntry."Location Code" := "New Location Code";
            NewItemLedgEntry."Country/Region Code" := "Country/Region Code";
            InsertCountryCode(NewItemLedgEntry, ItemLedgEntry);
            NewItemLedgEntry.CopyTrackingFromNewItemJnlLine(ItemJnlLine);
            NewItemLedgEntry."Expiration Date" := "New Item Expiration Date";
            OnInsertTransferEntryOnTransferValues(NewItemLedgEntry, OldItemLedgEntry, ItemLedgEntry, ItemJnlLine);

            if Item."Item Tracking Code" <> '' then begin
                TempItemEntryRelation."Item Entry No." := NewItemLedgEntry."Entry No."; // Save Entry No. in a global variable
                TempItemEntryRelation.CopyTrackingFromItemLedgEntry(NewItemLedgEntry);
                OnBeforeTempItemEntryRelationInsert(TempItemEntryRelation, NewItemLedgEntry);
                TempItemEntryRelation.Insert();
            end;
            InitTransValueEntry(NewValueEntry, NewItemLedgEntry);
		.
		.
		.
		.

....

NEW CODE:

...

    local procedure InsertTransferEntry(var ItemLedgEntry: Record "Item Ledger Entry"; var OldItemLedgEntry: Record "Item Ledger Entry"; AppliedQty: Decimal)
    var
        NewItemLedgEntry: Record "Item Ledger Entry";
        NewValueEntry: Record "Value Entry";
        ItemLedgEntry2: Record "Item Ledger Entry";
        IsReserved: Boolean;
    begin
        with ItemJnlLine do begin
            InitItemLedgEntry(NewItemLedgEntry);
            NewItemLedgEntry."Applies-to Entry" := 0;
            NewItemLedgEntry.Quantity := -AppliedQty;
            NewItemLedgEntry."Invoiced Quantity" := NewItemLedgEntry.Quantity;
            NewItemLedgEntry."Remaining Quantity" := NewItemLedgEntry.Quantity;
            NewItemLedgEntry.Open := NewItemLedgEntry."Remaining Quantity" <> 0;
            NewItemLedgEntry.Positive := NewItemLedgEntry."Remaining Quantity" > 0;
            NewItemLedgEntry."Location Code" := "New Location Code";
            NewItemLedgEntry."Country/Region Code" := "Country/Region Code";
            InsertCountryCode(NewItemLedgEntry, ItemLedgEntry);
            NewItemLedgEntry.CopyTrackingFromNewItemJnlLine(ItemJnlLine);
            NewItemLedgEntry."Expiration Date" := "New Item Expiration Date";
            OnInsertTransferEntryOnTransferValues(NewItemLedgEntry, OldItemLedgEntry, ItemLedgEntry, ItemJnlLine);

            if Item."Item Tracking Code" <> '' then begin
                TempItemEntryRelation."Item Entry No." := NewItemLedgEntry."Entry No."; // Save Entry No. in a global variable
                TempItemEntryRelation.CopyTrackingFromItemLedgEntry(NewItemLedgEntry);
                OnBeforeTempItemEntryRelationInsert(TempItemEntryRelation, NewItemLedgEntry);
                TempItemEntryRelation.Insert();
            end;

	    //new code start
	    OnInsertTransferEntryOnBeforeInitTransValueEntry(TempItemEntryRelation, NewItemLedgEntry,Item);
	    //new code end

            InitTransValueEntry(NewValueEntry, NewItemLedgEntry);
		.
		.
		.
		.
.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by mcarmenvalera** [comment]
Hi ALAppExtensions Team,

Sorry but I've just realised that a need the variable ItemJnlLine in the parameters in this event subscriber, the new event subscriber would be:

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnInsertTransferEntryOnBeforeInitTransValueEntry(var TempItemEntryRelation: Record "Item Entry Relation" temporary; ItemLedgerEntry: Record "Item Ledger Entry"; ItemJnlLine: Record "Item Journal Line"; Item: Record Item)
begin
end;

and the new code would be:

//new code start
    OnInsertTransferEntryOnBeforeInitTransValueEntry(TempItemEntryRelation, NewItemLedgEntry,ItemJnlLine, Item);
    //new code end

Could this be possible or do you need for me to open another request?

Sorry for the inconvenience.
