### ISSUE TITLE
[Event Request] Page 5830 Demand Overview - OnBeforeLookupDemandNoCtrl

### ISSUE THREAD

**Issue by sukumar5893** [microsoft/ALAppExtensions#9186]
Hi Team,

In Page 5830 please provide the possibility to have event **OnBeforeLookupDemandNoCtrl** in field **DemandNoCtrl** lookup

![image](https://user-images.githubusercontent.com/26245501/95451188-11458080-0985-11eb-89f3-84a05811566a.png)

**Event:**
**LOCAL [IntegrationEvent] OnBeforeLookupDemandNoCtrl(VAR Rec : Record "Availability Calc. Overview";DemandType : ' ,Sales,Production,Jobs,Services,Assembly';VAR IsChecked : Boolean;VAR IsHandled : Boolean)**

**Please backport to BC14 also.**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
