### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnAfterSalesInvHeaderInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9187]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `InsertInvoiceHeader`. Standard publisher `OnAfterSalesInvHeaderInsert` would suit us if it had additional parameters:

1. `WhseShip: Boolean`
2. `WhseReceive: Boolean`
3. `TempWhseShptHeader: Record "Warehouse Shipment Header"`
4. `TempWhseRcptHeader: Record "Warehouse Receipt Header"`

![image](https://user-images.githubusercontent.com/70525691/95452986-c7ec3580-0972-11eb-937a-8db624574b4e.png)

local procedure OnAfterSalesInvHeaderInsert(var SalesInvHeader: Record "Sales Invoice Header"; SalesHeader: Record "Sales Header"; CommitIsSuppressed: Boolean; **WhseShip: Boolean; WhseReceive: Boolean; TempWhseShptHeader: Record "Warehouse Shipment Header"; TempWhseRcptHeader: Record "Warehouse Receipt Header"**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
