### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" procedure IsNotInternalWhseMovement

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9189]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure IsNotInternalWhseMovement in codeunit 22 "Item Jnl.-Post Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure IsNotInternalWhseMovementOnBeforeCheckconditions(ItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean; var IsNotIntWhseJnlMnt: Boolean);
begin
end;

The code in procedure "IsNotInternalWhseMovement" in codeunit 22 "Item Jnl.-Post Line" would be modified as follows:

OLD CODE:

....

    local procedure IsNotInternalWhseMovement(ItemJnlLine: Record "Item Journal Line"): Boolean
    begin
        with ItemJnlLine do begin
            if ("Entry Type" = "Entry Type"::Transfer) and
               ("Location Code" = "New Location Code") and
               ("Dimension Set ID" = "New Dimension Set ID") and
               ("Value Entry Type" = "Value Entry Type"::"Direct Cost") and
               not Adjustment
            then
                exit(false);
            exit(true)
        end;
    end;

....

NEW CODE:

...

    local procedure IsNotInternalWhseMovement(ItemJnlLine: Record "Item Journal Line"): Boolean
    //new code
    IsHandled: boolean;
    IsNotIntWhseJnlMnt: boolean;
    //new code
    begin
        with ItemJnlLine do begin
	    //new code start
            IsHandled:=false;
	    IsNotIntWhseJnlMnt:=false;
            IsNotInternalWhseMovementOnBeforeCheckconditions(ItemJnlLine,IsHandled,IsNotIntWhseJnlMnt);
          
	    if IsHandled then 
	      exit(IsNotIntWhseJnlMnt);
            //new code end
            
           if ("Entry Type" = "Entry Type"::Transfer) and
               ("Location Code" = "New Location Code") and
               ("Dimension Set ID" = "New Dimension Set ID") and
               ("Value Entry Type" = "Value Entry Type"::"Direct Cost") and
               not Adjustment
            then
                exit(false);
            exit(true)
        end;
    end;

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
