### ISSUE TITLE
[Event Request] skip Job No. check in Sales Order with handled-Codeunit 80

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/ALAppExtensions#919]
we would like to handle below check with a handler to skip testfield

  IF NOT ("Document Type" IN ["Document Type"::Invoice,"Document Type"::"Credit Memo"]) THEN
    TESTFIELD("Job No.",'');

  **Handled := False;
  OnPostSalesLineOnBeforeJobNoCheck(SalesHeader,SalesLine,Handled);
  IF NOT Handled then** 
    IF NOT ("Document Type" IN ["Document Type"::Invoice,"Document Type"::"Credit Memo"]) THEN
      TESTFIELD("Job No.",'');

**Comment by AlexanderYakunin** [comment]
We already have this

  IsHandled := FALSE;
  OnPostSalesLineOnBeforeTestJobNo(SalesLine,IsHandled);
  IF NOT IsHandled THEN
    IF NOT ("Document Type" IN ["Document Type"::Invoice,"Document Type"::"Credit Memo"]) THEN
      TESTFIELD("Job No.",'');

**Comment by pmohanakrishna** [comment]
@AlexanderYakunin thank you.
Is it in Dev branch or Main (April'19)? when can we expect in Dev branch?

**Comment by AlexanderYakunin** [comment]
This events is included in March update
