### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnBeforeSalesCrMemoHeaderInsert

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9191]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `InsertCrMemoHeader`. Standard publisher `OnBeforeSalesCrMemoHeaderInsert` would suit us if it had additional parameter `var IsHandled: Boolean`.

![image](https://user-images.githubusercontent.com/70525691/95455746-ff5ce100-0976-11eb-8020-503b8c7d7c60.png)

local procedure OnBeforeSalesCrMemoHeaderInsert(var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; SalesHeader: Record "Sales Header"; CommitIsSuppressed: Boolean; **var IsHandled: Boolean**)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
