### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" procedure SplitWhseJnlLine

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9192]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure SplitWhseJnlLine in codeunit 6500 "Item Tracking Management"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure SplitWhseJnlLineOnBeforeCheckconditions(var TempWhseTrackingSpecification: Record "Tracking Specification" temporary;var TempWhseJnlLineTo: Record "Warehouse Journal Line" temporary;ToTransfer: Boolean);
begin
end;

The code in procedure "SplitWhseJnlLine" in codeunit 6500 "Item Tracking Management" would be modified as follows:

OLD CODE:

....
  procedure SplitWhseJnlLine(TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var TempWhseJnlLine2: Record "Warehouse Journal Line" temporary; var TempWhseSplitTrackingSpec: Record "Tracking Specification" temporary; ToTransfer: Boolean)
    var
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        NonDistrQtyBase: Decimal;
        NonDistrCubage: Decimal;
        NonDistrWeight: Decimal;
        SplitFactor: Decimal;
        LineNo: Integer;
        IsHandled: Boolean;
    begin
        .
	.
	.
	.
            SetFilter("Quantity actual Handled (Base)", '<>%1', 0);
            OnSplitWhseJnlLineOnAfterSetFilters(TempWhseSplitTrackingSpec, TempWhseJnlLine);
            NonDistrQtyBase := TempWhseJnlLine."Qty. (Absolute, Base)";
            NonDistrCubage := TempWhseJnlLine.Cubage;
            NonDistrWeight := TempWhseJnlLine.Weight;
            if FindSet() then
                repeat
                    LineNo += 10000;
                    TempWhseJnlLine2 := TempWhseJnlLine;
                    TempWhseJnlLine2."Line No." := LineNo;

                    if "Serial No." <> '' then begin
                        IsHandled := false;
                        OnSplitWhseJnlLineOnBeforeCheckSerialNo(TempWhseSplitTrackingSpec, IsHandled);
                        if not IsHandled then
                            if Abs("Quantity (Base)") <> 1 then
                                FieldError("Quantity (Base)");
                    end;

                    if ToTransfer then begin
                        SetWhseSerialLotNo(TempWhseJnlLine2."Serial No.", "New Serial No.", WhseItemTrackingSetup."Serial No. Required");
                        SetWhseSerialLotNo(TempWhseJnlLine2."Lot No.", "New Lot No.", WhseItemTrackingSetup."Lot No. Required");
                        if "New Expiration Date" <> 0D then
                            TempWhseJnlLine2."Expiration Date" := "New Expiration Date"
                    end else begin
                        SetWhseSerialLotNo(TempWhseJnlLine2."Serial No.", "Serial No.", WhseItemTrackingSetup."Serial No. Required");
                        SetWhseSerialLotNo(TempWhseJnlLine2."Lot No.", "Lot No.", WhseItemTrackingSetup."Lot No. Required");
                        TempWhseJnlLine2."Expiration Date" := "Expiration Date";
                    end;
                    SetWhseSerialLotNo(TempWhseJnlLine2."New Serial No.", "New Serial No.", WhseItemTrackingSetup."Serial No. Required");
                    SetWhseSerialLotNo(TempWhseJnlLine2."New Lot No.", "New Lot No.", WhseItemTrackingSetup."Lot No. Required");
                    TempWhseJnlLine2."New Expiration Date" := "New Expiration Date";
                    TempWhseJnlLine2."Warranty Date" := "Warranty Date";
                    TempWhseJnlLine2."Qty. (Absolute, Base)" := Abs("Quantity (Base)");
                    TempWhseJnlLine2."Qty. (Absolute)" :=
                      Round(
                        TempWhseJnlLine2."Qty. (Absolute, Base)" / TempWhseJnlLine."Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                    if TempWhseJnlLine.Quantity > 0 then begin
                        TempWhseJnlLine2."Qty. (Base)" := TempWhseJnlLine2."Qty. (Absolute, Base)";
                        TempWhseJnlLine2.Quantity := TempWhseJnlLine2."Qty. (Absolute)";
                    end else begin
                        TempWhseJnlLine2."Qty. (Base)" := -TempWhseJnlLine2."Qty. (Absolute, Base)";
                        TempWhseJnlLine2.Quantity := -TempWhseJnlLine2."Qty. (Absolute)";
                    end;
	.
	.
	.
	.
....

NEW CODE:

...

  procedure SplitWhseJnlLine(TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var TempWhseJnlLine2: Record "Warehouse Journal Line" temporary; var TempWhseSplitTrackingSpec: Record "Tracking Specification" temporary; ToTransfer: Boolean)
    var
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        NonDistrQtyBase: Decimal;
        NonDistrCubage: Decimal;
        NonDistrWeight: Decimal;
        SplitFactor: Decimal;
        LineNo: Integer;
        IsHandled: Boolean;
    begin
        .
	.
	.
	.
            SetFilter("Quantity actual Handled (Base)", '<>%1', 0);
            OnSplitWhseJnlLineOnAfterSetFilters(TempWhseSplitTrackingSpec, TempWhseJnlLine);
            NonDistrQtyBase := TempWhseJnlLine."Qty. (Absolute, Base)";
            NonDistrCubage := TempWhseJnlLine.Cubage;
            NonDistrWeight := TempWhseJnlLine.Weight;
            if FindSet() then
                repeat
                    LineNo += 10000;
                    TempWhseJnlLine2 := TempWhseJnlLine;
                    TempWhseJnlLine2."Line No." := LineNo;

                    if "Serial No." <> '' then begin
                        IsHandled := false;
                        OnSplitWhseJnlLineOnBeforeCheckSerialNo(TempWhseSplitTrackingSpec, IsHandled);
                        if not IsHandled then
                            if Abs("Quantity (Base)") <> 1 then
                                FieldError("Quantity (Base)");
                    end;

                    if ToTransfer then begin
                        SetWhseSerialLotNo(TempWhseJnlLine2."Serial No.", "New Serial No.", WhseItemTrackingSetup."Serial No. Required");
                        SetWhseSerialLotNo(TempWhseJnlLine2."Lot No.", "New Lot No.", WhseItemTrackingSetup."Lot No. Required");
                        if "New Expiration Date" <> 0D then
                            TempWhseJnlLine2."Expiration Date" := "New Expiration Date"
                    end else begin
                        SetWhseSerialLotNo(TempWhseJnlLine2."Serial No.", "Serial No.", WhseItemTrackingSetup."Serial No. Required");
                        SetWhseSerialLotNo(TempWhseJnlLine2."Lot No.", "Lot No.", WhseItemTrackingSetup."Lot No. Required");
                        TempWhseJnlLine2."Expiration Date" := "Expiration Date";
                    end;

		    //new code start
		    OnSplitWhseJnlLineOnAfterCheckToTransfer(TempWhseSplitTrackingSpec,TempWhseJnlLine2,ToTransfer);
	            //new code end
	
                    SetWhseSerialLotNo(TempWhseJnlLine2."New Serial No.", "New Serial No.", WhseItemTrackingSetup."Serial No. Required");
                    SetWhseSerialLotNo(TempWhseJnlLine2."New Lot No.", "New Lot No.", WhseItemTrackingSetup."Lot No. Required");
                    TempWhseJnlLine2."New Expiration Date" := "New Expiration Date";
                    TempWhseJnlLine2."Warranty Date" := "Warranty Date";
                    TempWhseJnlLine2."Qty. (Absolute, Base)" := Abs("Quantity (Base)");
                    TempWhseJnlLine2."Qty. (Absolute)" :=
                      Round(
                        TempWhseJnlLine2."Qty. (Absolute, Base)" / TempWhseJnlLine."Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                    if TempWhseJnlLine.Quantity > 0 then begin
                        TempWhseJnlLine2."Qty. (Base)" := TempWhseJnlLine2."Qty. (Absolute, Base)";
                        TempWhseJnlLine2.Quantity := TempWhseJnlLine2."Qty. (Absolute)";
                    end else begin
                        TempWhseJnlLine2."Qty. (Base)" := -TempWhseJnlLine2."Qty. (Absolute, Base)";
                        TempWhseJnlLine2.Quantity := -TempWhseJnlLine2."Qty. (Absolute)";
                    end;
	.
	.
	.
	.

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
