### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateSellToCustomerNoOnBeforeCheckBlockedCustOnDocs

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9193]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 2 "Sell-to Customer No.", in the trigger OnValidate, we need to add a condition to the use of Cust.CheckBlockedCustOnDocs() procedure. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95457082-a5f1b380-0970-11eb-8197-59d0471a5935.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95457041-92dee380-0970-11eb-8f41-94ffde06410a.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
