### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" procedure CollectItemTrkgInfWhseJnlLine

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9194]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure CollectItemTrkgInfWhseJnlLine in codeunit 6500 "Item Tracking Management"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnCollectItemTrkgInfWhseJnlLineOnAfterSetFilters(var WhseItemTrackingLine: Record "Whse. Item Tracking Line";WhseJnlLine: Record "Warehouse Journal Line");
begin
end;

The code in procedure "CollectItemTrkgInfWhseJnlLine" in codeunit 6500 "Item Tracking Management" would be modified as follows:

OLD CODE:

....
    
    procedure CollectItemTrkgInfWhseJnlLine(WhseJnlLine: Record "Warehouse Journal Line")
    var
        WhseItemTrackingLine: Record "Whse. Item Tracking Line";
    begin
        with WhseItemTrackingLine do begin
            SetSourceFilter(
              DATABASE::"Warehouse Journal Line", -1, WhseJnlLine."Journal Batch Name", WhseJnlLine."Line No.", true);
            SetSourceFilter(WhseJnlLine."Journal Template Name", -1);
            SetRange("Location Code", WhseJnlLine."Location Code");
            SetRange("Item No.", WhseJnlLine."Item No.");
            SetRange("Variant Code", WhseJnlLine."Variant Code");
            SetRange("Qty. per Unit of Measure", WhseJnlLine."Qty. per Unit of Measure");
            if FindSet then
                repeat
                    Clear(TempGlobalWhseItemTrkgLine);
                    TempGlobalWhseItemTrkgLine := WhseItemTrackingLine;
                    if TempGlobalWhseItemTrkgLine.Insert() then;
                until Next = 0;
        end;
    end;

....

NEW CODE:

...

    procedure CollectItemTrkgInfWhseJnlLine(WhseJnlLine: Record "Warehouse Journal Line")
    var
        WhseItemTrackingLine: Record "Whse. Item Tracking Line";
    begin
        with WhseItemTrackingLine do begin
            SetSourceFilter(
              DATABASE::"Warehouse Journal Line", -1, WhseJnlLine."Journal Batch Name", WhseJnlLine."Line No.", true);
            SetSourceFilter(WhseJnlLine."Journal Template Name", -1);
            SetRange("Location Code", WhseJnlLine."Location Code");
            SetRange("Item No.", WhseJnlLine."Item No.");
            SetRange("Variant Code", WhseJnlLine."Variant Code");
            SetRange("Qty. per Unit of Measure", WhseJnlLine."Qty. per Unit of Measure");
	
            //new code start
	    OnCollectItemTrkgInfWhseJnlLineOnAfterSetFilters(WhseItemTrackingLine,WhseJnlLine);
	    //new code end

            if FindSet then
                repeat
                    Clear(TempGlobalWhseItemTrkgLine);
                    TempGlobalWhseItemTrkgLine := WhseItemTrackingLine;
                    if TempGlobalWhseItemTrkgLine.Insert() then;
                until Next = 0;
        end;
    end;

.....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
