### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" procedure AssistEditTrackingNo

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9196]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure AssistEditTrackingNo in codeunit 6501 "Item Tracking Data Collection"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnAssistEditTrackingNoOnBeforeLookUpMode(var TempGlobalEntrySummary: Record "Entry Summary" temporary; var TempTrackingSpecification: Record "Tracking Specification" temporary);
begin
end;

The code in procedure "AssistEditTrackingNo" in codeunit 6501 "Item Tracking Data Collection" would be modified as follows:

OLD CODE:

....
  
	.
	.
	.
	.

  procedure AssistEditTrackingNo(var TempTrackingSpecification: Record "Tracking Specification" temporary; SearchForSupply: Boolean; CurrentSignFactor: Integer; LookupMode: Enum "Item Tracking Type"; MaxQuantity: Decimal)
    var
        ItemTrackingSummaryForm: Page "Item Tracking Summary";
        Window: Dialog;
        AvailableQty: Decimal;
        AdjustmentQty: Decimal;
        QtyOnLine: Decimal;
        QtyHandledOnLine: Decimal;
        NewQtyOnLine: Decimal;
        IsHandled: Boolean;
    begin
        OnBeforeAssistEditTrackingNo(TempTrackingSpecification, SearchForSupply, CurrentSignFactor, LookupMode, MaxQuantity);

        Window.Open(Text004);

        IsHandled := false;
        OnAssistEditTrackingNoOnBeforeRetrieveLookupData(TempTrackingSpecification, TempGlobalEntrySummary, FullGlobalDataSetExists, IsHandled);
        if not FullGlobalDataSetExists then
            RetrieveLookupData(TempTrackingSpecification, true);

        TempGlobalReservEntry.Reset();
        TempGlobalEntrySummary.Reset();

        // Select the proper key on form
        TempGlobalEntrySummary.SetCurrentKey("Expiration Date");
        TempGlobalEntrySummary.SetFilter("Expiration Date", '<>%1', 0D);
        if TempGlobalEntrySummary.IsEmpty then
            TempGlobalEntrySummary.SetCurrentKey("Lot No.", "Serial No.");
        TempGlobalEntrySummary.SetRange("Expiration Date");
        ItemTrackingSummaryForm.SetTableView(TempGlobalEntrySummary);

        TempGlobalEntrySummary.SetCurrentKey("Lot No.", "Serial No.");
        case LookupMode of
            LookupMode::"Serial No.":
                begin
                    if TempTrackingSpecification."Lot No." <> '' then
                        TempGlobalEntrySummary.SetRange("Lot No.", TempTrackingSpecification."Lot No.");
                    TempGlobalEntrySummary.SetRange("Serial No.", TempTrackingSpecification."Serial No.");
                    if TempGlobalEntrySummary.FindFirst then

	.
	.
	.
	.

....

NEW CODE:

...

	.
	.
	.
	.

  procedure AssistEditTrackingNo(var TempTrackingSpecification: Record "Tracking Specification" temporary; SearchForSupply: Boolean; CurrentSignFactor: Integer; LookupMode: Enum "Item Tracking Type"; MaxQuantity: Decimal)
    var
        ItemTrackingSummaryForm: Page "Item Tracking Summary";
        Window: Dialog;
        AvailableQty: Decimal;
        AdjustmentQty: Decimal;
        QtyOnLine: Decimal;
        QtyHandledOnLine: Decimal;
        NewQtyOnLine: Decimal;
        IsHandled: Boolean;
    begin
        OnBeforeAssistEditTrackingNo(TempTrackingSpecification, SearchForSupply, CurrentSignFactor, LookupMode, MaxQuantity);

        Window.Open(Text004);

        IsHandled := false;
        OnAssistEditTrackingNoOnBeforeRetrieveLookupData(TempTrackingSpecification, TempGlobalEntrySummary, FullGlobalDataSetExists, IsHandled);
        if not FullGlobalDataSetExists then
            RetrieveLookupData(TempTrackingSpecification, true);

        TempGlobalReservEntry.Reset();
        TempGlobalEntrySummary.Reset();

        // Select the proper key on form
        TempGlobalEntrySummary.SetCurrentKey("Expiration Date");
        TempGlobalEntrySummary.SetFilter("Expiration Date", '<>%1', 0D);
        if TempGlobalEntrySummary.IsEmpty then
            TempGlobalEntrySummary.SetCurrentKey("Lot No.", "Serial No.");
        TempGlobalEntrySummary.SetRange("Expiration Date");
        ItemTrackingSummaryForm.SetTableView(TempGlobalEntrySummary);

        TempGlobalEntrySummary.SetCurrentKey("Lot No.", "Serial No.");

	//new code start
	OnAssistEditTrackingNoOnBeforeLookUpMode(TempGlobalEntrySummary,TempTrackingSpecification);
	//new code end

        case LookupMode of
            LookupMode::"Serial No.":
                begin
                    if TempTrackingSpecification."Lot No." <> '' then
                        TempGlobalEntrySummary.SetRange("Lot No.", TempTrackingSpecification."Lot No.");
                    TempGlobalEntrySummary.SetRange("Serial No.", TempTrackingSpecification."Serial No.");
                    if TempGlobalEntrySummary.FindFirst then

	.
	.
	.
	.

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
