### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopyPurchDocInvLineOnBeforeCopyPurchInvLinesToDoc

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9198]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopyPurchDocInvLine` we would like to add some additional filters to `FromPurchInvLine` record before further code is ran, for that an event publisher after filtering the `FromPurchInvLine` record would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95463557-8f078d00-0981-11eb-8b23-09e37b0632c5.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopyPurchDocInvLineOnBeforeCopyPurchInvLinesToDoc(var FromPurchInvLine: Record "Purch. Inv. Line"; RecalculateLines: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
