### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" procedure AssistEditTrackingNo two new events

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9199]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need two new event publishers in procedure AssistEditTrackingNo in codeunit 6501 "Item Tracking Data Collection"

NEW PUBLISHERS:

[IntegrationEvent(false, false)]
local procedure OnAssistEditTrackingNoOnAfterSetTrackSpecification(var TempTrackingSpecification: Record "Tracking Specification" temporary;var TempGlobalEntrySummary: Record "Entry Summary" temporary);
begin
end;

[IntegrationEvent(false, false)]
local procedure OnAssistEditTrackingNoOnAfterSetTrackSpecReclass(var TempTrackingSpecification: Record "Tracking Specification" temporary);
begin
end;

The code in procedure "AssistEditTrackingNo" in codeunit 6501 "Item Tracking Data Collection" would be modified as follows:

OLD CODE:

....
  

  procedure AssistEditTrackingNo(var TempTrackingSpecification: Record "Tracking Specification" temporary; SearchForSupply: Boolean; CurrentSignFactor: Integer; LookupMode: Enum "Item Tracking Type"; MaxQuantity: Decimal)
    var
        ItemTrackingSummaryForm: Page "Item Tracking Summary";
        Window: Dialog;
        AvailableQty: Decimal;
        AdjustmentQty: Decimal;
        QtyOnLine: Decimal;
        QtyHandledOnLine: Decimal;
        NewQtyOnLine: Decimal;
        IsHandled: Boolean;
    begin
	.
	.
	.
	.
        Window.Close;
        if ItemTrackingSummaryForm.RunModal = ACTION::LookupOK then begin
            ItemTrackingSummaryForm.GetRecord(TempGlobalEntrySummary);

            if TempGlobalEntrySummary."Bin Active" then
                AvailableQty := MinValueAbs(TempGlobalEntrySummary."Bin Content", TempGlobalEntrySummary."Total Available Quantity")
            else
                AvailableQty := TempGlobalEntrySummary."Total Available Quantity";
            QtyHandledOnLine := TempTrackingSpecification."Quantity Handled (Base)";
            QtyOnLine := TempTrackingSpecification."Quantity (Base)" - QtyHandledOnLine;

            if CurrentSignFactor > 0 then begin
                AvailableQty := -AvailableQty;
                QtyHandledOnLine := -QtyHandledOnLine;
                QtyOnLine := -QtyOnLine;
            end;

            if MaxQuantity < 0 then begin
                AdjustmentQty := MaxQuantity;
                if AvailableQty < 0 then
                    if AdjustmentQty > AvailableQty then
                        AdjustmentQty := AvailableQty;
                if QtyOnLine + AdjustmentQty < 0 then
                    AdjustmentQty := -QtyOnLine;
            end else begin
                AdjustmentQty := AvailableQty;
                if AvailableQty < 0 then begin
                    if QtyOnLine + AdjustmentQty < 0 then
                        AdjustmentQty := -QtyOnLine;
                end else
                    AdjustmentQty := MinValueAbs(MaxQuantity, AvailableQty);
            end;
            if LookupMode = LookupMode::"Serial No." then
                TempTrackingSpecification.Validate("Serial No.", TempGlobalEntrySummary."Serial No.");
            TempTrackingSpecification.Validate("Lot No.", TempGlobalEntrySummary."Lot No.");

            TransferExpDateFromSummary(TempTrackingSpecification, TempGlobalEntrySummary);
            if TempTrackingSpecification.IsReclass then begin
                TempTrackingSpecification."New Serial No." := TempTrackingSpecification."Serial No.";
                TempTrackingSpecification."New Lot No." := TempTrackingSpecification."Lot No.";
            end;

            NewQtyOnLine := QtyOnLine + AdjustmentQty + QtyHandledOnLine;
            if TempTrackingSpecification."Serial No." <> '' then
                if Abs(NewQtyOnLine) > 1 then
                    NewQtyOnLine := NewQtyOnLine / Abs(NewQtyOnLine); // Set to a signed value of 1.

            TempTrackingSpecification.Validate("Quantity (Base)", NewQtyOnLine);

            OnAfterAssistEditTrackingNo(TempTrackingSpecification, TempGlobalEntrySummary);
        end;
    end;

	.
	.
	.
	.

....

NEW CODE:

...

  procedure AssistEditTrackingNo(var TempTrackingSpecification: Record "Tracking Specification" temporary; SearchForSupply: Boolean; CurrentSignFactor: Integer; LookupMode: Enum "Item Tracking Type"; MaxQuantity: Decimal)
    var
        ItemTrackingSummaryForm: Page "Item Tracking Summary";
        Window: Dialog;
        AvailableQty: Decimal;
        AdjustmentQty: Decimal;
        QtyOnLine: Decimal;
        QtyHandledOnLine: Decimal;
        NewQtyOnLine: Decimal;
        IsHandled: Boolean;
    begin
	.
	.
	.
	.
        Window.Close;
        if ItemTrackingSummaryForm.RunModal = ACTION::LookupOK then begin
            ItemTrackingSummaryForm.GetRecord(TempGlobalEntrySummary);

            if TempGlobalEntrySummary."Bin Active" then
                AvailableQty := MinValueAbs(TempGlobalEntrySummary."Bin Content", TempGlobalEntrySummary."Total Available Quantity")
            else
                AvailableQty := TempGlobalEntrySummary."Total Available Quantity";
            QtyHandledOnLine := TempTrackingSpecification."Quantity Handled (Base)";
            QtyOnLine := TempTrackingSpecification."Quantity (Base)" - QtyHandledOnLine;

            if CurrentSignFactor > 0 then begin
                AvailableQty := -AvailableQty;
                QtyHandledOnLine := -QtyHandledOnLine;
                QtyOnLine := -QtyOnLine;
            end;

            if MaxQuantity < 0 then begin
                AdjustmentQty := MaxQuantity;
                if AvailableQty < 0 then
                    if AdjustmentQty > AvailableQty then
                        AdjustmentQty := AvailableQty;
                if QtyOnLine + AdjustmentQty < 0 then
                    AdjustmentQty := -QtyOnLine;
            end else begin
                AdjustmentQty := AvailableQty;
                if AvailableQty < 0 then begin
                    if QtyOnLine + AdjustmentQty < 0 then
                        AdjustmentQty := -QtyOnLine;
                end else
                    AdjustmentQty := MinValueAbs(MaxQuantity, AvailableQty);
            end;
            if LookupMode = LookupMode::"Serial No." then
                TempTrackingSpecification.Validate("Serial No.", TempGlobalEntrySummary."Serial No.");
            TempTrackingSpecification.Validate("Lot No.", TempGlobalEntrySummary."Lot No.");

	   **_//New code start
	    OnAssistEditTrackingNoOnAfterSetTrackSpecification(TempTrackingSpecification,TempGlobalEntrySummary);
	    //New code end_**

            TransferExpDateFromSummary(TempTrackingSpecification, TempGlobalEntrySummary);
            if TempTrackingSpecification.IsReclass then begin
                TempTrackingSpecification."New Serial No." := TempTrackingSpecification."Serial No.";
                TempTrackingSpecification."New Lot No." := TempTrackingSpecification."Lot No.";

		**_//new code start
		OnAssistEditTrackingNoOnAfterSetTrackSpecReclass(TempTrackingSpecification);
		//new code end_**
            end;

            NewQtyOnLine := QtyOnLine + AdjustmentQty + QtyHandledOnLine;
            if TempTrackingSpecification."Serial No." <> '' then
                if Abs(NewQtyOnLine) > 1 then
                    NewQtyOnLine := NewQtyOnLine / Abs(NewQtyOnLine); // Set to a signed value of 1.

            TempTrackingSpecification.Validate("Quantity (Base)", NewQtyOnLine);

            OnAfterAssistEditTrackingNo(TempTrackingSpecification, TempGlobalEntrySummary);
        end;
    end;

	.
	.
	.
	.

.....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
