### ISSUE TITLE
[Event Request] Codeunt 1535 Approvals Mgmt.

### ISSUE THREAD

**Issue by GaryFrostick** [Microsoft/ALAppExtensions#92]
New event called OnSetStatusToPendingApproval to be added to the end of the SetStatusToPendingApproval function as follows…

>> OLD CODE 

  ELSE
    ERROR(UnsupportedRecordTypeErr,RecRef.CAPTION);

>> NEW CODE…

  ELSE BEGIN
    OnSetStatusToPendingApproval(Variant,RecRef,Handled);
    IF NOT Handled THEN
      ERROR(UnsupportedRecordTypeErr,RecRef.CAPTION);
  END;

This is to allow additional record types to be used with approvals. 

For completeness it would also be useful also add events to IsSufficientApprover() and InformUserOnStatusChange() functions in the same codeunit to allow us to extend the CASE statement usage

**Comment by AlexanderYakunin** [comment]
This is already done!

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
