### ISSUE TITLE
[Extensibility Enhancements] Table 36 "Sales Header" - OnAfterCopySellToCustomerAddressFieldsFromCustomer

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9201]
In Table 36 "Sales Header", at the end of the procedure CopySellToCustomerAddressFieldsFromCustomer, we use the event publisher OnAfterCopySellToCustomerAddressFieldsFromCustomer. But we need to have access to the standard global var SkipBillToContact, and to a global variable of the Table Extension of "Sales Header". To do so, we need to have the integration event OnAfterCopySellToCustomerAddressFieldsFromCustomer argument GlobalVarAccess set to TRUE, like this : 

![image](https://user-images.githubusercontent.com/34645582/95468986-5cf52b80-097f-11eb-933e-a6990f55e3e9.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by RomanZanizdra** [comment]
Hi @Magicrevette . We do not provide GlobalVarAccess. I can add "setter"/"getter" functions to manage the variable or add an event with this variable as parameter. Please let me know how can I help you here.

**Comment by Magicrevette** [comment]
Ok, so we would like to have the global variable SkipBillToContact as a parameter of the event OnAfterCopySellToCustomerAddressFieldsFromCustomer please, in order to modify this variable. Like this :
![image](https://user-images.githubusercontent.com/34645582/96225714-c71a5b80-0f91-11eb-980b-9c7e065a3bd1.png)

![image](https://user-images.githubusercontent.com/34645582/96235929-ac4ce480-0f9b-11eb-847d-fb376b4386bc.png)

We will call the variable of our table extension from our codeunit with a procedure.

Thank you.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
