### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnCheckPurchLineIsSetItem

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9202]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks . Having event with handling in procedure `InsertReceiptLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95469151-f7f20380-0987-11eb-9480-a04726c702d8.png)

    [IntegrationEvent(false, false)]
    local procedure OnCheckPurchLineIsSetItem(var PurchLine: Record "Purchase Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
