### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnAfterFinalizePostingOnDoCommit

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9203]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks . Having event with handling in procedure `FinalizePosting` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95470355-5e2b5600-0989-11eb-8113-7d9bd13665d2.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterFinalizePostingOnDoCommit(PreviewMode: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
