### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" procedure CreateEntrySummary2

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9204]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure CreateEntrySummary2 in codeunit 6501 "Item Tracking Data Collection"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnCreateEntrySummary2OnAfterSetFilters(var TempGlobalEntrySummary: Record "Entry Summary" temporary; var TempReservationEntry: Record "Reservation Entry" temporary);
begin
end;

The code in procedure "CreateEntrySummary2" in codeunit 6501 "Item Tracking Data Collection" would be modified as follows:

OLD CODE:

....
  

    local procedure CreateEntrySummary2(TrackingSpecification: Record "Tracking Specification" temporary; LookupMode: Enum "Item Tracking Type"; TempReservEntry: Record "Reservation Entry" temporary)
    var
        DoInsert: Boolean;
    begin
        OnBeforeCreateEntrySummary2(TempGlobalEntrySummary, TempReservEntry, TrackingSpecification);

        TempGlobalEntrySummary.Reset();
        TempGlobalEntrySummary.SetCurrentKey("Lot No.", "Serial No.");

        // Set filters
        case LookupMode of
            LookupMode::"Serial No.":
                begin
                    if TempReservEntry."Serial No." = '' then
                        exit;
                    TempGlobalEntrySummary.SetTrackingFilterFromReservEntry(TempReservEntry);
                end;
            LookupMode::"Lot No.":
                begin
                    TempGlobalEntrySummary.SetTrackingFilter('', TempReservEntry."Lot No.");
                    if TempReservEntry."Serial No." <> '' then
                        TempGlobalEntrySummary.SetRange("Table ID", 0)
                    else
                        TempGlobalEntrySummary.SetFilter("Table ID", '<>%1', 0);
                end;
        end;

        // If no summary exists, create new record
        if not TempGlobalEntrySummary.FindFirst then begin
            TempGlobalEntrySummary.Init();
            TempGlobalEntrySummary."Entry No." := LastSummaryEntryNo + 1;
            LastSummaryEntryNo := TempGlobalEntrySummary."Entry No.";

	.
	.
	.	
	.
....

NEW CODE:

...

    local procedure CreateEntrySummary2(TrackingSpecification: Record "Tracking Specification" temporary; LookupMode: Enum "Item Tracking Type"; TempReservEntry: Record "Reservation Entry" temporary)
    var
        DoInsert: Boolean;
    begin
        OnBeforeCreateEntrySummary2(TempGlobalEntrySummary, TempReservEntry, TrackingSpecification);

        TempGlobalEntrySummary.Reset();
        TempGlobalEntrySummary.SetCurrentKey("Lot No.", "Serial No.");

        // Set filters
        case LookupMode of
            LookupMode::"Serial No.":
                begin
                    if TempReservEntry."Serial No." = '' then
                        exit;
                    TempGlobalEntrySummary.SetTrackingFilterFromReservEntry(TempReservEntry);
                end;
            LookupMode::"Lot No.":
                begin
                    TempGlobalEntrySummary.SetTrackingFilter('', TempReservEntry."Lot No.");
                    if TempReservEntry."Serial No." <> '' then
                        TempGlobalEntrySummary.SetRange("Table ID", 0)
                    else
                        TempGlobalEntrySummary.SetFilter("Table ID", '<>%1', 0);
                end;
        end;

	//New code start
	OnCreateEntrySummary2OnAfterSetFilters(TempGlobalEntrySummary,TempReservEntry);
	//New code end

        // If no summary exists, create new record
        if not TempGlobalEntrySummary.FindFirst then begin
            TempGlobalEntrySummary.Init();
            TempGlobalEntrySummary."Entry No." := LastSummaryEntryNo + 1;
            LastSummaryEntryNo := TempGlobalEntrySummary."Entry No.";

        // If no summary exists, create new record
        if not TempGlobalEntrySummary.FindFirst then begin
            TempGlobalEntrySummary.Init();
            TempGlobalEntrySummary."Entry No." := LastSummaryEntryNo + 1;
            LastSummaryEntryNo := TempGlobalEntrySummary."Entry No.";

	.
	.
	.	
	.

.....

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
