### ISSUE TITLE
[Event Request] Table 7311 Warehouse Journal Line - OnBeforeCheckBin

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#9205]
Hi AL team,

could you please pass the Record "WarehouseJournalLine" by ref?

    [IntegrationEvent(false, false)]
    --- local procedure OnBeforeCheckBin(WarehouseJournalLine: Record "Warehouse Journal Line"; LocationCode: Code[10]; 
    +++ local procedure OnBeforeCheckBin(var WarehouseJournalLine: Record "Warehouse Journal Line"; LocationCode: Code[10]; 
        BinCode: Code[20]; Inbound: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
