### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopySalesDocSalesLineOnBeforeCopyFromSalesDocAssgntToLine

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9206]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopySalesDocSalesLine` we would like to run some custom code before running `CopyFromSalesDocAssgntToLine`, for that an event before executing the procedure would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95469194-09d3a680-0988-11eb-91f2-19a478649523.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopySalesDocSalesLineOnBeforeCopyFromSalesDocAssgntToLine(FromSalesLine: Record "Sales Line"; ToSalesLine: Record "Sales Line"; RecalculateLines: Boolean; NextLineNo: Integer)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
