### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnAfterCopySalesDocSalesLine

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9207]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopySalesDocSalesLine` we would like to have the ability to assign some custom fields, for that an event after copying sales lines would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95472327-92077b00-098b-11eb-9ce4-6b0707d35a52.png)
```
[IntegrationEvent(false, false)]
local procedure OnAfterCopySalesDocSalesLine(var ToSalesLine: Record "Sales Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
