### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopySalesLineOnBeforeCheckCopyThisLine

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9210]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopySalesLine` we would like to run some custom code before inserting `ToSalesLine`, for that an event would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95475079-8a95a100-098e-11eb-87ba-662c09a2534f.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopySalesLineOnBeforeCheckCopyThisLine(ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; FromSalesLine: Record "Sales Line")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
