### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" procedure FindRelatedParentTrkgSpec

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9214]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure FindRelatedParentTrkgSpec in codeunit 6501 "Item Tracking Data Collection"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnFindRelatedParentTrkgSpecOnAfterSetTrackingFilter(var TempTrackingSpecification: Record "Tracking Specification" temporary;ItemJnlLine: Record "Item Journal Line"; );
begin
end;

The code in procedure "FindRelatedParentTrkgSpec" in codeunit 6501 "Item Tracking Data Collection" would be modified as follows:

OLD CODE:

....
  
    local procedure FindRelatedParentTrkgSpec(ItemJnlLine: Record "Item Journal Line"; var TempTrackingSpecification: Record "Tracking Specification" temporary; SerialNo: Code[50]; LotNo: Code[50]): Boolean
    begin
        ItemJnlLine.TestField("Order Type", ItemJnlLine."Order Type"::Production);
        TempTrackingSpecification.Reset();
        case ItemJnlLine."Entry Type" of
            ItemJnlLine."Entry Type"::Consumption:
                begin
                    if ItemJnlLine."Prod. Order Comp. Line No." = 0 then
                        exit;
                    TempTrackingSpecification.SetSourceFilter(
                      DATABASE::"Prod. Order Component", 3, ItemJnlLine."Order No.", ItemJnlLine."Prod. Order Comp. Line No.", false);
                    TempTrackingSpecification.SetSourceFilter('', ItemJnlLine."Order Line No.");
                end;
            ItemJnlLine."Entry Type"::Output:
                begin
                    TempTrackingSpecification.SetSourceFilter(DATABASE::"Prod. Order Line", 3, ItemJnlLine."Order No.", -1, false);
                    TempTrackingSpecification.SetSourceFilter('', ItemJnlLine."Order Line No.");
                end;
        end;
        TempTrackingSpecification.SetTrackingFilter(SerialNo, LotNo);
        exit(TempTrackingSpecification.FindFirst);
    end;
....

NEW CODE:

...

    local procedure FindRelatedParentTrkgSpec(ItemJnlLine: Record "Item Journal Line"; var TempTrackingSpecification: Record "Tracking Specification" temporary; SerialNo: Code[50]; LotNo: Code[50]): Boolean
    begin
        ItemJnlLine.TestField("Order Type", ItemJnlLine."Order Type"::Production);
        TempTrackingSpecification.Reset();
        case ItemJnlLine."Entry Type" of
            ItemJnlLine."Entry Type"::Consumption:
                begin
                    if ItemJnlLine."Prod. Order Comp. Line No." = 0 then
                        exit;
                    TempTrackingSpecification.SetSourceFilter(
                      DATABASE::"Prod. Order Component", 3, ItemJnlLine."Order No.", ItemJnlLine."Prod. Order Comp. Line No.", false);
                    TempTrackingSpecification.SetSourceFilter('', ItemJnlLine."Order Line No.");
                end;
            ItemJnlLine."Entry Type"::Output:
                begin
                    TempTrackingSpecification.SetSourceFilter(DATABASE::"Prod. Order Line", 3, ItemJnlLine."Order No.", -1, false);
                    TempTrackingSpecification.SetSourceFilter('', ItemJnlLine."Order Line No.");
                end;
        end;
        TempTrackingSpecification.SetTrackingFilter(SerialNo, LotNo);

	//new code start
	OnFindRelatedParentTrkgSpecOnAfterSetTrackingFilter(TempTrackingSpecification,ItemJnlLine);
	//new code end

        exit(TempTrackingSpecification.FindFirst);
    end;
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
