### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopyPurchLineOnBeforeCheckCopyThisLine

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9215]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopyPurchLine` we would like to have the ability to set some custom fields before copying lines, for that an event before checking `CopyThisLine` boolean would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95476459-f1678a00-098f-11eb-947c-4243ba6d4671.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopyPurchLineOnBeforeCheckCopyThisLine(var ToPurchLine: Record "Purchase Line"; var FromPurchLine: Record "Purchase Line"; MoveNegLines: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
