### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopySalesInvLinesToDocOnAfterCopyPostedDeferral

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9216]
Hi team,

In Codeunit 6620 "Copy Document Mgt." procedure `CopySalesInvLinesToDoc` we would like to have the ability to run some custom code, for that and event before checking item line type would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95581176-3697c480-0a41-11eb-856d-0b85ba8da021.png)
```
[IntegrationEvent(false, false)]
local procedure OnCopySalesInvLinesToDocOnAfterCopyPostedDeferral(var FromSalesInvLine: Record "Sales Invoice Line"; NextLineNo: Integer)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
