### ISSUE TITLE
[Event Request] Database::"Requisition Line" - Function SetReplenishmentSystemFromProdOrder - OnBeforeSetReplenishmentSystemFromProdOrder

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9217]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: SetReplenishmentSystemFromProdOrder
Publisher Event: OnBeforeSetReplenishmentSystemFromProdOrder
Reason: To implement custom business logic
Where is the event placed:
local procedure SetReplenishmentSystemFromProdOrder()
    var
        NoSeriesMgt: Codeunit NoSeriesManagement;
        IsHandled: Boolean;
    begin
        **OnBeforeSetReplenishmentSystemFromProdOrder(Rec);**
        if ReqWkshTmpl.Get("Worksheet Template Name") and
           (ReqWkshTmpl.Type = ReqWkshTmpl.Type::"Req.") and (ReqWkshTmpl.Name <> '') and not SourceDropShipment
        then
            Error(ReplenishmentErr);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetReplenishmentSystemFromProdOrder(var Rec: Record "Requisition Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
