### ISSUE TITLE
Hoch [Event Request] Database::"Sales Header" - Function RecreateSalesLines - OnAfterRecreateSalesLines

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9218]
We like to request the following Event:
Object: Database::"Sales Header"
Function: RecreateSalesLines
Publisher Event: OnAfterRecreateSalesLines
Reason: To implement custom business logic
Where is the event placed:
end else
            Rec := xRec;
        SalesLine.BlockDynamicTracking(false);
        **OnAfterRecreateSalesLines(Rec, ChangedFieldName);**
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterRecreateSalesLines(var SalesHeader: Record "Sales Header"; ChangedFieldName: Text[100])
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
