### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function SetSellToCustomerFromFilter - OnAfterSetSellToCustomerFromFilter

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9219]
We like to request the following Event:
Object: Database::"Sales Header"
Function: SetSellToCustomerFromFilter
Publisher Event: OnAfterSetSellToCustomerFromFilter
Reason: To implement custom business logic
Where is the event placed:
procedure SetSellToCustomerFromFilter()
    var
        SellToCustomerNo: Code[20];
    begin
        SellToCustomerNo := GetFilterCustNo;
        if SellToCustomerNo = '' then begin
            FilterGroup(2);
            SellToCustomerNo := GetFilterCustNo;
            if SellToCustomerNo = '' then
                SellToCustomerNo := GetFilterCustNoByApplyingFilter;
            FilterGroup(0);
        end;
        if SellToCustomerNo <> '' then
            Validate("Sell-to Customer No.", SellToCustomerNo);
        OnAfterSetSellToCustomerFromFilter(Rec);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterSetSellToCustomerFromFilter(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
