### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function CalcInvDiscForHeader - OnBeforeCalcInvDiscForHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9220]
We like to request the following Event:
Object: Database::"Sales Header"
Function: CalcInvDiscForHeader
Publisher Event: OnBeforeCalcInvDiscForHeader
Reason: To implement custom business logic
Where is the event placed:
procedure CalcInvDiscForHeader()
    var
        SalesInvDisc: Codeunit "Sales-Calc. Discount";
    begin
        OnBeforeCalcInvDiscForHeader(Rec);
        GetSalesSetup;
        if SalesSetup."Calc. Inv. Discount" then
            SalesInvDisc.CalculateIncDiscForHeader(Rec);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCalcInvDiscForHeader(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
