### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function ValidateLineDiscountPercent - OnValidateLineDiscountPercentOnAfterUpdateAmounts

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9221]
We like to request the following Event:
Object: Database::"Sales Line"
Function: ValidateLineDiscountPercent
Publisher Event: OnValidateLineDiscountPercentOnAfterUpdateAmounts
Reason: To implement custom business logic
Where is the event placed:
[Scope('OnPrem')]
    procedure ValidateLineDiscountPercent(DropInvoiceDiscountAmount: Boolean)
    begin
        TestJobPlanningLine();
        TestStatusOpen();
        "Line Discount Amount" :=
          Round(
            Round(Quantity * "Unit Price", Currency."Amount Rounding Precision") *
            "Line Discount %" / 100, Currency."Amount Rounding Precision");
        if DropInvoiceDiscountAmount then begin
            "Inv. Discount Amount" := 0;
            "Inv. Disc. Amount to Invoice" := 0;
        end;
        OnValidateLineDiscountPercentOnBeforeUpdateAmounts(Rec);
        UpdateAmounts();
        OnValidateLineDiscountPercentOnAfterUpdateAmounts(Rec, CurrFieldNo)
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateLineDiscountPercentOnAfterUpdateAmounts(var SalesLine: Record "Sales Line"; CurrFieldNo: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
