### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateSellToCustomerNoOnBeforeRecallModifyAddressNotification

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9222]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 2 "Sell-to Customer No.", in the trigger OnValidate, we need to our code at a specific moment. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95477597-cf1e3e00-0988-11eb-88df-1971afcf9346.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95477640-db0a0000-0988-11eb-8047-61726d20f180.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
