### ISSUE TITLE
[Event Request] Database::"Warehouse Receipt Line"- Function GetWhseRcptLine OnGetWhseRcptLineOnAfterSetFilter

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9224]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Variant Code" - OnValidate
Publisher Event: OnValidateVariantCodeOnAfterUpdateItemReference
Reason: To implement custom business logic
Where is the event placed:
procedure GetWhseRcptLine(ReceiptNo: Code[20]; SourceType: Integer; SourceSubType: Option; SourceNo: Code[20]; SourceLineNo: Integer): Boolean
    begin
        SetRange("No.", ReceiptNo);
        SetSourceFilter(SourceType, SourceSubType, SourceNo, SourceLineNo, false);
        OnGetWhseRcptLineOnAfterSetFilter(Rec, ReceiptNo, SourceType, SourceSubType, SourceNo, SourceLineNo);
        if FindFirst then
            exit(true);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnGetWhseRcptLineOnAfterSetFilter(var WhseReceiptLine: Record "Warehouse Receipt Line"; ReceiptNo: Code[20]; SourceType: Integer; SourceSubType: Option; SourceNo: Code[20]; SourceLineNo: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
