### ISSUE TITLE
[Event Request] Database::"Warehouse Shipment Line" - Function AutofillQtyToHandle - OnBeforeAutofillQtyToHandle

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9225]
We like to request the following Event:
Object: Database::"Warehouse Shipment Line"
Function: AutofillQtyToHandle
Publisher Event: OnBeforeAutofillQtyToHandle
Reason: To implement custom business logic
Where is the event placed:
procedure AutofillQtyToHandle(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        NotEnough: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeAutofillQtyToHandle(WhseShptLine, IsHandled);
        if IsHandled then
            exit;
        with WhseShptLine do begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeAutofillQtyToHandle(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
