### ISSUE TITLE
[Event Request] Database::"Warehouse Shipment Line" - Function DeleteQtyToHandle - OnBeforeDeleteQtyToHandle

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9226]
We like to request the following Event:
Object: Database::"Warehouse Shipment Line"
Function: DeleteQtyToHandle
Publisher Event: OnBeforeDeleteQtyToHandle
Reason: To implement custom business logic
Where is the event placed:
procedure DeleteQtyToHandle(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeDeleteQtyToHandle(WhseShptLine, IsHandled);
        if IsHandled then
            exit;
        with WhseShptLine do begin
            if Find('-') then
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteQtyToHandle(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
