### ISSUE TITLE
[Event Request] Database::"Warehouse Shipment Line" - Function CheckSourceDocLineQty - OnCheckSourceDocLineQtyOnBeforeSetQuantityBase

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9227]
We like to request the following Event:
Object: Database::"Warehouse Shipment Line"
Function: CheckSourceDocLineQty
Publisher Event: OnCheckSourceDocLineQtyOnBeforeSetQuantityBase
Reason: To implement custom business logic
Where is the event placed:
procedure CheckSourceDocLineQty()
    var
        WhseShptLine: Record "Warehouse Shipment Line";
        SalesLine: Record "Sales Line";
        PurchaseLine: Record "Purchase Line";
        TransferLine: Record "Transfer Line";
        ServiceLine: Record "Service Line";
        WhseQtyOutstandingBase: Decimal;
        QtyOutstandingBase: Decimal;
        QuantityBase: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnCheckSourceDocLineQtyOnBeforeSetQuantityBase(Rec, QuantityBase, IsHandled);
        if not IsHandled then
            if "Qty. (Base)" = 0 then
                QuantityBase :=
                    UOMMgt.CalcBaseQty("Item No.", "Variant Code", "Unit of Measure Code", Quantity, "Qty. per Unit of Measure")
            else
                QuantityBase := "Qty. (Base)";
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCheckSourceDocLineQtyOnBeforeSetQuantityBase(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var QuantityBase: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
