### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateBillToCustomerNoOnBeforeCheckBlockedCustOnDocs

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9229]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 4 "Bill-to Customer No.", in the trigger OnValidate, we need to add a condition to the use of Cust.CheckBlockedCustOnDocs() procedure. To do so, we need a IsHandled flag and an event publisher, like this : 

![image](https://user-images.githubusercontent.com/34645582/95481510-5ec5eb80-098d-11eb-896f-8b3c1dfa9759.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95481593-73a27f00-098d-11eb-9ab9-464a45cd541b.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
