### ISSUE TITLE
[Event Request] Page 490 "Acc. Schedule Overview" OnBeforeUpdateDimFilterControles

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9230]
Hi Team,

In page 490, please provide the **OnBeforeUpdateDimFilterControles** event in **UpdateDimFilterControles** procedure

![image](https://user-images.githubusercontent.com/57799519/95481787-0271c480-09ab-11eb-8c00-950b71a4dee6.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeUpdateDimFilterControles(VAR Rec : Record "Acc. Schedule Line";AnalysisView : Record "Analysis View";VAR IsHandled : Boolean)

Reason: Client needs to limit the  empty values should not be assigned to (global variables) Dimension Filters 1 to 4. 

**Note:**
Also provide GlobalVarAccess to the same event
![image](https://user-images.githubusercontent.com/57799519/95482140-6bf1d300-09ab-11eb-9e97-bec7e962467d.png)

_If possible, please back port to BC14 aslo._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Rambabu-Billuri** [comment]
Hi Team, 

If you published a fix for this, it does not fulfill my requirement. We asked the above publisher with 'GlobalVarAccess' to **True** but we can see 'OnAfterUpdateDimFilterControls()' publisher with 'IncludeSender' to **True** in BC17.

![image](https://user-images.githubusercontent.com/57799519/102370570-35f05100-3fe3-11eb-8143-e4d2d7642ae7.png)

**OnBeforeUpdateDimFilterControls**
![image](https://user-images.githubusercontent.com/57799519/102371709-7d2b1180-3fe4-11eb-9f31-3e21a89deb38.png)

**OnAfterUpdateDimFilterControls**
![image](https://user-images.githubusercontent.com/57799519/102371811-97fd8600-3fe4-11eb-89eb-3ddbf89e99f8.png)

Please provide any one of the publisher with 'GlobalVarAccess' to True (or) Can you help me to access the global variables with given two publishers.

Thank You.
