### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeSetBillToCustomerAddressFieldsFromCustomer

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9231]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the procedure 2 SetBillToCustomerAddressFieldsFromCustomer, we need to add conditions and our code in several places. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95483439-80c06d80-098f-11eb-8993-aa9005e95c02.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95483509-946bd400-098f-11eb-898b-790d54e742db.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
