### ISSUE TITLE
event request - table 77 "Report Selections" - SendEmailInBackground() - OnAfterGetJobQueueParameters(..., var RecRef)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9233]
We need to be able to select Direct Debit Collections for which to produce notification statements to email to customers. We do this via the Document Sending Profile functions so that it works on premise and in SaaS. We only want to notify of specific DD Collections.

These functions require that the report being sent has a Customer or Vendor as the main DataItem that gets iterated. Therefore, in order to start from the list of DD Collections and get to a report running on a Customer, we added a "DD Collection No. Filter" FlowField to the Customer table and set that from the page selection filter, so that by the time the report is run once for each Customer, it knows which DD Collections we want to include.

However, because BC sends these emails via Job Queue, and only remembers a few parameters, our ability to stipulate that that email should later be sent only for the given collections is lost: the report gets run for the customer overall, showing all DDs that each customer has had, which obviously defeats the point: we want to run per DD on demand. So we need some way to store the DD Coll No filter in the JQE and restore before reporting

Please therefore add the following event to enable us to deliver this functionality.

    [Scope('OnPrem')]
    procedure SendEmailInBackground(JobQueueEntry: Record "Job Queue Entry")
    var
        RecRef: RecordRef;
        ReportUsage: Integer;
        DocNo: Code[20];
        DocName: Text[150];
        No: Code[20];
        ParamString: Text;
        WasSuccessful: Boolean; // NEW
    begin
        // Called from codeunit 260 OnRun trigger - in a background process.
        RecRef.Get(JobQueueEntry."Record ID to Process");
        RecRef.LockTable();
        RecRef.Find;
        RecRef.SetRecFilter;
        ParamString := JobQueueEntry."Parameter String";  // Are set in function SendEmailToCust
        WasSuccessful := GetJobQueueParameters(ParamString, ReportUsage, DocNo, DocName, No);

        // +NEW
        OnAfterGetJobQueueParameters(ParamString, ReportUsage, DocNo, DocName, No, RecRef, WasSuccessful);
        // Do something with the otherwise unused WasSuccessful, if you want
        // -NEW

        if ParamString = 'Vendor' then
            SendEmailToVendorDirectly(ReportUsage, RecRef, DocNo, DocName, false, No)
        else
            SendEmailToCustDirectly(ReportUsage, RecRef, DocNo, DocName, false, No);
    end;

where said new event has this signature, crucially enabling us to (a) get arbitrary subsequent parameters out of the JQ Entry Parameter String and (b) use one of those parameters to reapply a FlowFilter on the Customer/Vendor record as originally chosen.

    local procedure OnAfterGetJobQueueParameters(var ParameterString: Text; var RecRef: RecordRef; var WasSuccessful: Boolean)

We will then be doing something like this in a subscriber:

    local procedure ReportSelectionsOnAfterGetJobQueueParameters(var ParameterString: Text; var RecRef: RecordRef; var WasSuccessful: Boolean)
    var
        Customer: Record Customer;
        DDCollectionNoFilter: Text;
    begin
        if ReportUsage <> "Report Selection Usage"::"DD Collection Statement" then
            exit;

        WasSuccessful := WasSuccessful and Evaluate(DDCollectionNoFilter, GetNextJobQueueParam(ParameterString);
        RecRef.SetTable(Customer);
        Customer.SetFilter("DD Collection No. Filter", DDCollectionNoFilter);
        RecRef.GetTable(Customer);
    end;

As a result, it would also help if `GetNextJobQueueParam()` could be made public, so that we wouldn't have to copy-and-paste it.

Currently we have copied-and-pasted the code that sets the Parameter String on the JQE in the first place, so we can add whatever we want there, although we will also be requesting an event at that point separately to avoid having to do this, ideally.

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @dtkb . There will be a runner for GetNextJobQueueParam() function, don't miss it.

**Comment by dtkb** [comment]
@RomanZanizdra Not sure what you mean - do you mean it will be made public, or that some other function will be added to call it? Thanks!

Also, guessing that means the event additions are being considered, great news 👍

**Comment by RomanZanizdra** [comment]
Hi @dtkb . I mean other function will be added to run the GetNextJobQueueParam(). And yes, events will be implemented.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
