### ISSUE TITLE
event request - table 77 "Report Selections" - SendEmailToCust/Vendor() - OnAfterSetJobQueueEntryParameterString(RecRef, var ParameterString)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9234]
`SendEmailToCust()` and the equivalent `SendEmailToVendor()` will enqueue Job Queue Entries to send the emails later, and as per #9233 we need to be able to stash some extra info there, so that when the report is later run to produce the email, we can apply an extra filter to it.

Please therefore change both functions something like the below to let us append params:

    procedure SendEmailToCust(ReportUsage: Integer; RecordVariant: Variant; DocNo: Code[20]; DocName: Text[150]; ShowDialog: Boolean; CustNo: Code[20])
    var
        [...]
        ParameterString: Text;
        ParameterStringTxt: Label '%1|%2|%3|%4|', Locked = true, Comment = '%1, %2, %3, and %4 are the parameters.';
        [...]
        RecRef.GetTable(RecordVariant);
        if RecRef.FindSet() then
            repeat
                // -OLD: EnqueueMailingJob(RecRef.RecordId, StrSubstNo('%1|%2|%3|%4|', ReportUsage, DocNo, DocName, CustNo), DocName);

                // +NEW
                ParameterString := StrSubstNo(ParameterStringTxt, ReportUsage, DocNo, DocName, CustNo);
                OnAfterSetParameterString(RecRef, ParameterString);
                EnqueueMailingJob(RecRef.RecordId, ParameterString);
                // -NEW
            until RecRef.Next() = 0;
    end;

where we would subscribe and do:

    local procedure ReportSelectionsOnAfterSetParameterString(var RecRef: RecordRef; var ParameterString: Text)
    var
        Customer: Record Customer;
    begin
        RecRef.SetTable(Customer);
        ParameterString += Customer.GetFilter("DD Collection No. Filter") + '|';
    end;

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
