### ISSUE TITLE
Expand the size of field 6; "Cross-Reference No." in table 5717

### ISSUE THREAD

**Issue by carterusm** [microsoft/ALAppExtensions#9235]
this field is too small to handle complex part no's.  Can we increase the size of this field (and of course all the related fields in other tables), to at least 50,

**Comment by AlexanderYakunin** [comment]
Please be aware that extension of field included into primary key in any table is not possible anymore. Therefore please use new version of cross reference named Item Reference which is available from 17.0. This feature has same capabilities and support long 50 chars item references.

**Comment by carterusm** [comment]
Thank you.
