### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateBillToCustomerNoOnBeforeRecallModifyAddressNotification

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9236]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 4 "Bill-to Customer No.", in the trigger OnValidate, we need to add our code before the procedure RecallModifyAddressNotification(). To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95553794-72b23180-0a0f-11eb-898d-ff59bd91a3f4.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95553766-66c66f80-0a0f-11eb-8dfa-b5a26a202a36.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
