### ISSUE TITLE
[Event Request] Table 37 Sales Line - OnCrossReferenceNoLookUpAndOnAfterApplyFilters

### ISSUE THREAD

**Issue by sukumar5893** [microsoft/ALAppExtensions#9237]
Hi Team,

In Table 37 please provide the possibility to have event **OnCrossReferenceNoLookUpAndOnAfterApplyFilters** in procedure **CrossReferenceNoLookUp**

![image](https://user-images.githubusercontent.com/26245501/95554640-23c7c480-0a2e-11eb-80ac-9362c95c0b22.png)

**Event:**
![image](https://user-images.githubusercontent.com/26245501/95554666-3215e080-0a2e-11eb-81ee-26fa23d8ca1c.png)

**Please backport to BC14 also.**

**Comment by RomanZanizdra** [comment]
Hi @sukumar5893 . Mentioned event is already implemented, please check latest version. We do not downgrade events in older versions except the latest one which is 17.x for now. If your really need event for older version please reach out the support channel and ask for a hotfix for event implementation.

    procedure CrossReferenceNoLookUp()
    var
        ItemCrossReference: Record "Item Cross Reference";
        ICGLAcc: Record "IC G/L Account";
    begin
        case Type of
            Type::Item:
                begin
                    GetSalesHeader();
                    ItemCrossReference.Reset();
                    ItemCrossReference.SetCurrentKey("Cross-Reference Type", "Cross-Reference Type No.");
                    ItemCrossReference.SetFilter(
                      "Cross-Reference Type", '%1|%2',
                      ItemCrossReference."Cross-Reference Type"::Customer,
                      ItemCrossReference."Cross-Reference Type"::" ");
                    ItemCrossReference.SetFilter("Cross-Reference Type No.", '%1|%2', SalesHeader."Sell-to Customer No.", '');
                    OnCrossReferenceNoLookUpOnAfterSetFilters(ItemCrossReference, Rec);
                    if PAGE.RunModal(PAGE::"Cross Reference List", ItemCrossReference) = ACTION::LookupOK then begin
                        "Cross-Reference No." := ItemCrossReference."Cross-Reference No.";
                        ValidateCrossReferenceNo(ItemCrossReference, false);
                        UpdateReferencePriceAndDiscount();
                        OnCrossReferenceNoLookupOnBeforeValidateUnitPrice(SalesHeader, Rec);
                        Validate("Unit Price");
                    end;
                end;
            Type::"G/L Account", Type::Resource:
                begin
                    GetSalesHeader();
                    SalesHeader.TestField("Sell-to IC Partner Code");
                    if PAGE.RunModal(PAGE::"IC G/L Account List", ICGLAcc) = ACTION::LookupOK then
                        "Cross-Reference No." := ICGLAcc."No.";
                end;
        end;
        OnAfterCrossReferenceNoLookUp(Rec);
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
