### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeValidateBillToCustomerName

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9238]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 5 "Bill-to Name", in the trigger OnValidate, we need to add a condition to the use of Validate("Bill-to Customer No.") procedure. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95556962-6a102a00-0a14-11eb-8769-28fadfba46ad.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95556928-59f84a80-0a14-11eb-9f4e-737c5d09e041.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Magicrevette** [comment]
Hello. In the version 17.1, an event publisher and a IsHandled flag have been added in the trigger OnLookUp and not in the trigger OnValidate as asked here. Is it a mistake or an answer to another demand from another user ?

![image](https://user-images.githubusercontent.com/34645582/100433523-7ff8ad80-309b-11eb-86b4-40e6c595e8be.png)

Thank you for your work ?
