### ISSUE TITLE
[Request for External] Page "Sales Quote Subform" - global variable "ItemChargeStyleExpression"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#9239]
In Page "Sales Quote Subform" please make the variable "ItemChargeStyleExpression" accessible. (protected)
It is used in the "StyleExpr" Properties.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
