### ISSUE TITLE
[Request for External] Page "Item Tracking Summary" - global functions

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#9240]
Page "Item Tracking Summary"

the function "DrillDownBinContent" should be  accessible. (protected).

the function "SelectedQuantityOnAfterValidat" should be  accessible. (protected),

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
