### ISSUE TITLE
[Request for External] Page "Order Planning" - global variables

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#9242]
Page "Order Planning" 

please make the global variable "DemandQuantityHideValue" , "QuantityHideValue" and "DemandQtyAvailableHideValue" accessible. (protected)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
