### ISSUE TITLE
[Request for External] Page "Blanket Purchase Order Subform" - function "DeltaUpdateTotals"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#9243]
Page "Blanket Purchase Order Subform" 

please make the function "DeltaUpdateTotals" accessible. (protected)

**Comment by AlexanderYakunin** [comment]
We have this calling DeltaUpdateTotals:

  procedure CallDeltaUpdateTotals()
    begin
        DeltaUpdateTotals();
    end;

**Comment by sschuh** [comment]
thank you...
