### ISSUE TITLE
[Request for External] Page "Blanket Sales Order Subform" - function "DeltaUpdateTotals"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#9244]
Page "Blanket Sales Order Subform" 

please make the function "DeltaUpdateTotals" accessible. (protected)

**Comment by AlexanderYakunin** [comment]
Use
    procedure CallDeltaUpdateTotals()
    begin
        DeltaUpdateTotals();
    end;

**Comment by sschuh** [comment]
thank you...
