### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateShipToCodeOnBeforeValidateTaxLiable

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9246]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 12 "Ship-to Code", in the trigger OnValidate, we need to our code before the Validate("Tax Liable") procedure. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95562649-b7909500-0a1c-11eb-9b82-ca393ba5b140.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95562596-a8114c00-0a1c-11eb-8c60-f0cd6b960e55.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
