### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateShipmentMethodCodeOnBeforeTestStatusOpen

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9247]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 27 "Shipment Method Code", in the trigger OnValidate, we need to add a condition to the use of TestStatusOpen. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95563950-5f5a9280-0a1e-11eb-8368-c409a0a298cb.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95563912-51a50d00-0a1e-11eb-9684-6357357570d3.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by RomanZanizdra** [comment]
Hi @Magicrevette . There will be new a function that returns StatusCheckSuspended, don't miss it.

**Comment by Magicrevette** [comment]
Ok thank you. But we'll need to add a condition before TestStatusOpen. I don't think it's possible with another function.

**Comment by RomanZanizdra** [comment]
Hi @Magicrevette . There is a function SuspendStatusCheck you can use. I suppose the code in subscriber will be looking like below or something similar.
OnBeforeValidateShipmentCodeHandler(var SalesHeader; var IsHandled)
begin
    if not GetSomeStatus then
        SuspendStatusCheck(true);
end;

**Comment by Magicrevette** [comment]
In that case it will fit our purpose. Thank you for your time.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
