### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeValidateSellToCustomerName

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9248]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 79 "Sell-to Customer Name", in the trigger OnValidate, we need to add a condition. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95567005-a77bb400-0a22-11eb-9d17-d792526a3b84.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95566887-756a5200-0a22-11eb-887f-a59bfcd61273.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
