### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateShippingAgentCodeOnBeforeTestStatusOpen

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9249]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 105 "Shipping Agent Code", in the trigger OnValidate, we need to add a condition to the use of TestStatusOpen procedure. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95569664-27574d80-0a26-11eb-9b7f-bc3db318fc21.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95569599-1575aa80-0a26-11eb-981f-81ff861dcc69.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
