### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateRequestedDeliveryDateOnBeforeUpdateSalesLinesByFieldNo

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9250]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 5790 "Requested Delivery Date", in the trigger OnValidate, we need to add a condition to the use of UpdateSalesLinesByFieldNo. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95572597-799a6d80-0a2a-11eb-8220-510245049845.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95572619-84ed9900-0a2a-11eb-9d91-8eecbec1d2f8.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by RomanZanizdra** [comment]
Hi @Magicrevette . There is IsHandled pattern directly in UpdateSalesLinesByFieldNo function with ChangedFieldNo parameter, so you can skip this function if check for "Requested Delivery Date" field. Does it fit your needs?

**Comment by Magicrevette** [comment]
Sorry, I didn't notice. It fits my needs indeed. Thank you for your time.
