### ISSUE TITLE
[Event Request] Codeunit 7380 "Phys. Invt. Count.-Management" - OnBeforeRun & OnRunOnBeforeInsertTempPhysCountBuffer  & OnBeforeRunPhysInvtItemSelection

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9251]
Hi Team,

In codeunit 7380, please provide the possibility to have **OnBeforeRun** , **OnRunOnBeforeInsertTempPhysCountBuffer** and 
**OnBeforeRunPhysInvtItemSelection** events in OnRun() trigger,
**OnAfterInsertTempPhysCountBuffer** event in **InsertTempPhysCountBuffer** procedure,
**OnBeforeCreatePhysInvtWhseJnl** event in **CreatePhysInvtWhseJnl** procedure,
**OnBeforeUpdateSKUPhysInvtCount** and **OnAfterUpdateSKUPhysInvtCount** events in **UpdateSKUPhysInvtCount** procedure.

1.**OnBeforeRun**
![image](https://user-images.githubusercontent.com/57799519/95572667-ea03b780-0a47-11eb-9515-b7653c3a6b3a.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeRun(VAR WhseJnlLine: Record "Warehouse Journal Line";VAR SourceJnl: Option)

2.**OnRunOnBeforeInsertTempPhysCountBuffer**

![image](https://user-images.githubusercontent.com/57799519/95561351-41019080-0a38-11eb-9dcc-f94b00c1014d.png)

**Event:**
LOCAL [IntegrationEvent] OnRunOnBeforeInsertTempPhysCountBuffer(VAR Item: Record Item;SKU: Record "Stockkeeping Unit";VAR IsHandled: Boolean)

3.**OnBeforeRunPhysInvtItemSelection**

![image](https://user-images.githubusercontent.com/57799519/95564438-6c867a00-0a3c-11eb-9e63-575447ff82f0.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeRunPhysInvtItemSelection(TempPhysInvtItemSel: Record "Phys. Invt. Item Selection;VAR IsHandled: Boolean)

4.**OnAfterInsertTempPhysCountBuffer**

![image](https://user-images.githubusercontent.com/57799519/95565071-47ded200-0a3d-11eb-9a5a-96053bed3b4d.png)

**Event:**
LOCAL [IntegrationEvent] OnAfterInsertTempPhysCountBuffer(PhysInvtCountCode : Code[10])

5.**OnBeforeCreatePhysInvtWhseJnl**

![image](https://user-images.githubusercontent.com/57799519/95565988-9771cd80-0a3e-11eb-8a18-66100735aa5a.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeCreatePhysInvtWhseJnl(PhysInvtCountRep: Record "Calculate Phys. Invt. Counting";SortingMethod: Option;VAR IsHandled: Boolean)

6.**OnBeforeUpdateSKUPhysInvtCount**

![image](https://user-images.githubusercontent.com/57799519/95566664-7f4e7e00-0a3f-11eb-9d64-2dae76337542.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeUpdateSKUPhysInvtCount(VAR SKU: Record "Stockkeeping Unit")

7.**OnAfterUpdateSKUPhysInvtCount**
![image](https://user-images.githubusercontent.com/57799519/95568655-22a09280-0a42-11eb-829c-321adfc86cbb.png)

**Event:**
LOCAL [IntegrationEvent] OnAfterUpdateSKUPhysInvtCount(VAR SKU: Record "Stockkeeping Unit")

_If possible, Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
