### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidatePromisedDeliveryDateOnBeforeUpdateSalesLinesByFieldNo

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9252]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 5791 "Promised Delivery Date", in the trigger OnValidate, we need to add a condition to the use of UpdateSalesLinesByFieldNo. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95573060-2e348f00-0a2b-11eb-8fc8-2015b02dbf43.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95573096-37bdf700-0a2b-11eb-8f17-b822ac95dc50.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
use event in the function UpdateSalesLinesByFieldNo().
