### ISSUE TITLE
[Additional Parameter Request] Codeunit 90 Purch.-Post - OnFinalizePostingOnBeforeInsertTrackingSpec

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9253]
Hi Team,

In codeunit 90 we need possibility to have additional checks in the procedure `FinalizePosting`. New publisher requested in issue #8745 would suit us if it have more parameters:

1. `EverythingInvoiced: Boolean`
2. `var TempPurchLine: Record "Purchase Line"`
3. `TempPurchLineGlobal: Record "Purchase Line"`

![image](https://user-images.githubusercontent.com/70525691/95579391-3a761780-0a3e-11eb-9976-f2b4b51e2548.png)

local procedure OnFinalizePostingOnBeforeInsertTrackingSpec(var TempDropShptPostBuffer: record "Drop Shpt. Post. Buffer" temporary; PurchHeader: record "Purchase Header"; var TempTrackingSpecification: Record "Tracking Specification" temporary; **EverythingInvoiced: Boolean; var TempPurchLine: Record "Purchase Line" temporary; TempPurchLineGlobal: Record "Purchase Line" temporary**);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
