### ISSUE TITLE
[Event Request] Codeunit 10750 SII XML Creator

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#9254]
We need a new event function in Codeunit 10750 "SII XML Creator", named "OnBeforeFillFechaOperacion". It will be called from "FillFechaOperacion" procedure.

The event will be:
LOCAL [IntegrationEvent] OnBeforeFillFechaOperacion(VAR LastShptRcptDate : Date;PostingDate : Date)

LOCAL FillFechaOperacion(VAR XMLNode : DotNet "System.Xml.XmlNode";LastShptRcptDate : Date;PostingDate : Date)
IF (LastShptRcptDate = 0D) OR (LastShptRcptDate = PostingDate) THEN
  EXIT;

IF LastShptRcptDate > WORKDATE THEN
  LastShptRcptDate := PostingDate;

// INIT INSERT
OnBeforeFillFechaOperacion(LastShptRcptDate,PostingDate);
// F-END INSERT

XMLDOMManagement.AddElementWithPrefix(XMLNode,'FechaOperacion',FormatDate(LastShptRcptDate),'sii',SiiTxt,TempXMLNode);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
