### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateShippingTimeOnBeforeUpdateSalesLinesByFieldNo

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9256]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 5792 "Shipping Time", in the trigger OnValidate, we need to add a condition to the use of UpdateSalesLinesByFieldNo. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95585647-c89ecd80-0a3f-11eb-9fcf-f8db7f76a5b5.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95585614-bc1a7500-0a3f-11eb-8eec-bce58eae92c1.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
use event in the function UpdateSalesLinesByFieldNo()
