### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnSetPostingNoInUpdatePostingNos

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9257]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks . Having event with handling in procedure `UpdatePostingNos` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95587177-626b7800-0a4a-11eb-91da-51d9ca6943dd.png)

    [IntegrationEvent(false, false)]
    local procedure OnSetPostingNoInUpdatePostingNos(var PurchHeader: Record "Purchase Header"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
