### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnBeforeReleaseSalesHeaderForDropShipment

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9258]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks . Having event in procedure `UpdateAssosOrderPostingNos` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95587537-d148d100-0a4a-11eb-99a8-b64f79f2b50c.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeReleaseSalesHeaderForDropShipment(var PurchaseHeader: Record "Purchase Header"; var SalesHeader: Record "Sales Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
