### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnCheckAndUpdateBeforeArchive

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9259]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks . Having event with handling in procedure `CheckAndUpdate` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95589014-d3139400-0a4c-11eb-94f3-8102f9f36ab3.png)

    [IntegrationEvent(false, false)]
    local procedure OnCheckAndUpdateBeforeArchive(PurchHeader: Record "Purchase Header"; PreviewMode: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
