### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateShippingAgentServiceCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9260]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the field 5794 "Shipping Agent Service Code", in the trigger OnValidate, we need to add a condition before launching the rest of the code. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95593689-4a93f400-0a4a-11eb-916b-bd333106d16b.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95593530-1ddfdc80-0a4a-11eb-8eac-30a6ecb6e121.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
