### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeSalesHeaderInvoice

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9261]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `OnRun` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95599794-39eb7a00-0a5a-11eb-9072-5b87ccb1d1a0.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesHeaderInvoice(var SalesHeader: Record "Sales Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
