### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnPostGLAccICLineTestFields

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9262]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event with handling in procedure `PostGLAccICLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95600029-89ca4100-0a5a-11eb-9fc7-97a0e7b691c6.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostGLAccICLineTestFields(SalesLine: Record "Sales Line"; GLAcc: Record "G/L Account"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
