### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeInsertTempDropShptPostBuffer

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9263]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `PostItemLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95600349-dd3c8f00-0a5a-11eb-936e-9e62d2d73060.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertTempDropShptPostBuffer(var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; SalesLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
