### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnInitRecordOnBeforePostingDateWorkDate

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9264]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the procedure InitRecord, we need to add a condition before "Posting Date" := WorkDate . To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95600303-77e4a000-0a52-11eb-96b0-725c98cc395a.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95600178-60a5b280-0a52-11eb-844a-1ef519795feb.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
