### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeReleaseSalesDocument

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9266]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `ReleaseSalesDocument` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95600735-3ad0db80-0a5b-11eb-843e-a49e17830915.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeReleaseSalesDocument(SalesHeader: Record "Sales Header"; PreviewMode: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
