### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeTransferReservToItemJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9267]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event with handling in procedure `TransferReservToItemJnlLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95600956-84212b00-0a5b-11eb-91a2-a367b8ade908.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservToItemJnlLine(Var SalesOrderLine: Record "Sales Line"; var QtyToBeShippedBase: Decimal; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
