### ISSUE TITLE
[Additional Parameter Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnProcessLinesOnBeforeSetGLRegNoToZero 

### ISSUE THREAD

**Issue by gkulic** [microsoft/ALAppExtensions#9269]
Hi Team,

Could you please add a new parameter to the OnProcessLinesOnBeforeSetGLRegNoToZero event, codeunit 13 "Gen. Jnl.-Post Batch"? 
- var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"

We need that parameter to create new Gen. Jnl. Lines and post them in the same G/L Register as the other Gen. Jnl. Lines.

![NewParameter](https://user-images.githubusercontent.com/52541091/95603624-d14ece00-0a56-11eb-8e78-b47bff01630d.png)
![NewParameter2](https://user-images.githubusercontent.com/52541091/95603628-d3189180-0a56-11eb-8ed3-4c6bea1faae6.png)

Thanks,
Goran

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
