### ISSUE TITLE
EventRequest: Modification to an existing event "OnUpdatePostingNosOnBeforeCheckExternalDocNo" CU90

### ISSUE THREAD

**Issue by robertoscaringella** [microsoft/ALAppExtensions#9275]
Hi,
Already exist in PuchPost.codeunit.al "codeunit 90 Purch.-Post" the event OnUpdatePostingNosOnBeforeCheckExternalDocNo

...
VendLedgEntry.SetRange("Vendor No.", "Pay-to Vendor No.");
OnUpdatePostingNosOnBeforeCheckExternalDocNo(VendLedgEntry, "Posting Date");
if VendLedgEntry.FindFirst then
  Error(PurchaseAlreadyExistsErr, VendLedgEntry."Document Type", GenJnlLineExtDocNo);
...

I ask to modify the event and the code in this:

...
VendLedgEntry.SetRange("Vendor No.", "Pay-to Vendor No.");
OnUpdatePostingNosOnBeforeCheckExternalDocNo(VendLedgEntry, PurchHeader, IsHandled);

if not IsHandled then
  if VendLedgEntry.FindFirst then
    Error(PurchaseAlreadyExistsErr, VendLedgEntry."Document Type", GenJnlLineExtDocNo);
...

[IntegrationEvent(false, false)]
    local procedure OnUpdatePostingNosOnBeforeCheckExternalDocNo(var VendLedgEntry: Record "Vendor Ledger Entry"; PurchaseHeader: Record "Purchase Header";var IsHandled: Boolean )
    begin
    end;

Thank you,
Roberto.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
