### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnPostItemTrackingForReceiptOnBeforePurchRcptLineTestFields

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9276]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks and skip standard field testfield functionality.. Having event with handling in procedure `PostItemTrackingForReceipt` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/95740874-eebdab00-0c95-11eb-9383-ed363a5cffbb.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostItemTrackingForReceiptOnBeforePurchRcptLineTestFields(var PurchRcptLine: Record "Purch. Rcpt. Line"; PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
