### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnRunOnBeforeCommit

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9277]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks . Having event with handling in procedure `OnRun` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/95744122-870a5e80-0c9b-11eb-9425-5685ea53c2dd.png)

    [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeCommit(InvtPickPutaway: Boolean; SuppressCommit: Boolean; PreviewMode: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
