### ISSUE TITLE
[Event Request] Codeunit 12 PostDtldCVLedgEntry - Add OnPostDtldCVLedgEntryOnBeforeCreateGLEntryPaymentDiscTol

### ISSUE THREAD

**Issue by Joneleth84** [microsoft/ALAppExtensions#9278]
Hello!

We would like to control when the G/L Entry is created when the entry type of the buffer is payment discount. Therefore we would need an additional trigger before the entry is created. Ideally you would refactor function PostDtldCVLedgEntry() and add an additional event similar to the "Un/Realized Gain/Loss" case above:

`
local procedure OnPostDtldCVLedgEntryOnBeforeCreateGLEntryPaymentDiscTol(var GenJournalLine: Record "Gen. Journal Line"; DtldCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var Unapply: Boolean; var AccNo: Code[20]; var IsHandled: Boolean)
`

Alternatively, as a broader approach, you could create an IsHandled/Exit logic for the OnBeforePostDtldCVLedgEntry() function. There may be other partners that want to skip the standard logic that controls the way G/L Entries are created depending on the entry type.

Thank you and best regards,
Johannes

![PostDtldCVLedgEntry](https://user-images.githubusercontent.com/56401325/95744552-c765de80-0c93-11eb-9f94-7033d51ef667.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
