### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeDeleteTempInvoicePostBuffer

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9279]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `PostInvoicePostBuffer` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95745805-6394e300-0c9e-11eb-96ab-aff43095e63e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteTempInvoicePostBuffer(var SalesHeader: Record "Sales Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var TotalSalesLine: Record "Sales Line"; var TotalSalesLineLCY: Record "Sales Line"; GenJnlLineDocType: Integer; GenJnlLineDocNo: Code[20]; GenJnlLineExtDocNo: Code[35]; SrcCode: Code[10])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
