### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnPostStatisticLedgerGLEntryNo

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9280]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `PostInvoicePostBuffer` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95746310-401e6800-0c9f-11eb-8f89-288838aaf730.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostStatisticLedgerGLEntryNo("Sales Header": Record "Sales Header"; "Sales Line": Record "Sales Line"; var TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
