### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick" - OnAfterCheckOutBound

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9281]
Hi team,

In Codeunit 7312 "Create Pick" procedure `CheckOutBound` we would like to have the ability to run custom code based on SourceType variable, for that an event at the end of procedure code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95745836-74455900-0c9e-11eb-8263-36bccd68a096.png)
```
[IntegrationEvent(false, false)]
local procedure OnAfterCheckOutBound(SourceType: Integer; SourceSubType: Integer; SourceNo: Code[20]; SourceLineNo: Integer; var OutBoundQty: Decimal)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
