### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnAfterPurchPostUpdateBlanketOrderLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9282]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `PostDropOrderShipment` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95746823-1a459300-0ca0-11eb-9fa0-8455958c1150.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterPurchPostUpdateBlanketOrderLine(PurchOrderHeader: Record "Purchase Header"; PurchOrderLine: Record "Purchase Line"; TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; SalesShptHeader: Record "Sales Shipment Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
