### ISSUE TITLE
[Application Request] Multiple Email attachments

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#9283]
@JesperSchulz Can you please indicate where (which version / build) I can find the major refactoring (of the Base application) that was referred to in #3820?

I'm still looking for a way in the standard BC Application logic to insert additional attachments to an outgoing sales invoice. Apparently the EmailTable.AttachIncomingDocuments function still uses the Email item table, limited to 6 additional attachments only. 

In addition, seems all is heavily depending om server temp files and not on streams. How to make this (adding more than 6 attachments via streams on the standard sales invoice print / mail feature) to work (SaaS-proof)?

**Comment by darjoo** [comment]
The refactoring does not include adding additional attachments in baseapp.
I'll be looking into this of how we can attach more attachments (preferably without limitation) and #9292

**Comment by GiorgosPa** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version.

**Comment by JesperSchulz** [comment]
To answer the question, the release will be 17.2 :-)
