### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick" - OnCreateTempActivityLineOnAfterCheckWhseSource

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9284]
Hi team,

In Codeunit 7312 "Create Pick" procedure `CreateTempActivityLine` we would like to have the ability to run some code depending on WhseSource, for that an event after checking the WhseSource variable would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95747712-8c6aa780-0ca1-11eb-8319-49c31ee9d9a6.png)
```
[IntegrationEvent(false, false)]
local procedure OnCreateTempActivityLineOnAfterCheckWhseSource(var TempWhseActivLine: Record "Warehouse Activity Line" temporary; QtyToPick: Decimal; QtyToPickBase: Decimal; WhseSource: Option "Pick Worksheet",Shipment,"Movement Worksheet","Internal Pick",Production,Assembly,,,,,,,,,"Production DiVA","Production Rcpt. DiVA"; WhseSource2: Option)
```

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
