### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnInsertInsertReturnReceiptLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9285]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks, it can be done as a `new event` or as an `additional parameter request` to existing event `OnBeforeInsertReturnReceiptLine` . Having event with handling in procedure `InsertReturnReceiptLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95749041-a1483a80-0ca3-11eb-923b-095a6177ed7f.png)

    [IntegrationEvent(false, false)]
    local procedure OnInsertInsertReturnReceiptLine(SalesLine: Record "Sales Line"; ReturnRcptHeader: Record "Return Receipt Header"; WhseShip: Boolean; WhseReceive: Boolean; TempWhseRcptHeader: Record "Warehouse Receipt Header" temporary; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
