### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnInsertShipmentLineOnBeforePostWhseLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9287]
Hi Team,

In codeunit 80, procedure `InsertShipmentLine` we need to have additional checks and avoid using of standard code, we found that event in issue #8790 would suit us if it had additional parameters:

1. var SalesShptLine: Record "Sales Shipment Line"
2. WhseShptHeader: Record "Warehouse Shipment Header"
3. WhseRcptHeader: Record "Warehouse Receipt Header"
4. WhseShip: Boolean
5. WhseReceive: Boolean
6. var IsHandled: Boolean

```
*** start new code ***
        DoPostWhseLine := (SalesLine.Type = SalesLine.Type::Item) and (SalesLine."Qty. to Ship" <> 0);
        OnInsertShipmentLineOnBeforePostWhseLine(SalesLine,  SalesShptLine, WhseShptHeader, WhseRcptHeader, WhseShip, WhseReceive, IsHandled);
        if IsHandled then
            if DoPostWhseLine then begin
*** stop new code ***
                if WhseShip then
```

and publisher itself:
    [IntegrationEvent(false, false)]
    local procedure OnInsertShipmentLineOnBeforePostWhseLine(SalesLine: Record "Sales Line"; var DoPostWhseLine: Boolean;  var SalesShptLine: Record "Sales Shipment Line"; WhseShptHeader: Record "Warehouse Shipment Header"; WhseRcptHeader: Record "Warehouse Receipt Header"; WhseShip: Boolean; WhseReceive: Boolean; Var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
