### ISSUE TITLE
[Event Request] Codeunit 12 CreateGLEntriesForTotalAmounts - Add IsHandled to OnBeforeCreateGLEntriesForTotalAmounts

### ISSUE THREAD

**Issue by Joneleth84** [microsoft/ALAppExtensions#9288]
Hello!

We would like to control the way how entries for total amounts are created. Although we can change the invoice post buffer we can not prevent the insertion via PostCust, because a ledger entry is inserted and the therefore an entry for total amounts is also created.

We would favor an additonal IsHandled parameter in procedure OnBeforeCreateGLEntriesForTotalAmounts():

`
local procedure OnBeforeCreateGLEntriesForTotalAmounts(var InvoicePostBuffer: Record "Invoice Post. Buffer"; GenJournalLine: Record "Gen. Journal Line"; var GLAccNo: Code[20]; var IsHandled: Boolean)
`

Thank you and best regards,
Johannes

![CreateGLEntriesForTotalAmounts](https://user-images.githubusercontent.com/56401325/95759314-d3f53180-0ca9-11eb-959e-da625ee9a56d.jpg)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
