### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeFindCustLedgEntry

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9289]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `FindCustLedgEntry` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/95762128-f5f4b100-0cb5-11eb-82b6-d3c9bbfcfb4e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindCustLedgEntry(var CustLedgEntry: Record "Cust. Ledger Entry")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
