### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnUpdateSellToCustOnBeforeContactBusinessRelationFound

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9291]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the procedure UpdateSellToCust, we need to add our code at a specific moment. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95767336-e45ed980-0cb4-11eb-9339-1c9aaa965074.png)

With the integration event :
![image](https://user-images.githubusercontent.com/34645582/95767269-ca24fb80-0cb4-11eb-8df6-2aabaa1ce308.png)

Do you think it could be possible ?

Thanks for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
