### ISSUE TITLE
EmailItem / OnBeforeSendEmail - add support for streams (GetAttachmentAsStream)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#9292]
We've already spent tremenduous time in trying to keep our 'Advanced Mailing' solution working with extensions. (See #4349) We're especially trying to interfere in the standard BC sales invoice mailing process (as late as possible) to manipulate the generated sales invoice PDF (+ attachments) to be sent. Eventually, we ended up using the OnBeforeSendEmail event, which works fine ... in OnPrem only.

```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Document-Mailing", 'OnBeforeSendEmail', '', false, false)]
    local procedure OnBeforeSendEmail(var TempEmailItem: Record "Email Item" temporary; var IsFromPostedDoc: Boolean; var PostedDocNo: Code[20]; var HideDialog: Boolean; var ReportUsage: Integer; var EmailSentSuccesfully: Boolean; var IsHandled: Boolean)
    var
        MailTemplateFunc: Codeunit "NVT Mail Template Functions";
        SourceRecordRef: RecordRef;
    begin   
        MailTemplateFunc.BeforeSendMailMessage(SourceRecordRef, TempEmailItem."Attachment File Path", TempEmailItem."Attachment Name", HideDialog, IsHandled);
        if IsHandled then begin
            HideDialog := false;
            EmailSentSuccesfully := true;
        end;
    end;
```

The problem is that the above solution is NOT saas-proof. We do get access to the generated sales invoice PDF (the PDF is generated in standard BC via SaveAsPDF), but via server temp only (TempEmailItem."Attachment File Path"). This blocks us from further reading the file and adding watermarks, sales conditions, attachments and zipping the result.

With the new 'Email Feature' coming towards us in BC 17.1, what are the options in the Base App made available to fix the above problem. Can you at least provide access to the content of the TempEmailItem."Attachment File Path" via **streams**, so we can manipulate the file in OnBeforeSendEmail?

Having a function **EmailItem.GetAttachmentAsStream(var InStream) : boolean ** (and EmailItem.GetAttachment2AsStream(var InStream) .. to 6) would definitly help us moving forward with BC 17.1 untill the BC team has managed the Base App refactoring to full stream based mailing (and thus depecrate the tons on file based / OnPrem functions in Report Selections / Document-Mailing / ...) (or a similar function returning a temp array / temp table of Instreams for the attachments)

The function should read the tempserverfile EmailItem."Attachment File Path" and return map it to a stream. If this is to generic / exposes the server too much, then please at least provide a similar solution, but limited to the context where OnBeforeSendEmail is raised.

![image](https://user-images.githubusercontent.com/25268332/95778694-e9c61f00-0cc8-11eb-9210-8713bce793b1.png)

_A bit similar to how the GeneratePdf in PDF Document Management works, providing access to TempAttachmentEntityBuffer.Content._

@JesperSchulz Any thoughts, ideas, suggestions? This is one of the major blocking parts keeping us from moving towards Appsource, which Kurt Juvyns is pushing our management to ... :) We definitly should to be able to fix this in a next minor of BC 17.

**Comment by GiorgosPa** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version.
