### ISSUE TITLE
[Event Request] Page 30 Item Card - OnAfterCreateItemFromTemplate 

### ISSUE THREAD

**Issue by abhishekv290691** [microsoft/ALAppExtensions#9293]
We are modifying a record via a workflow , which uses the global database modify. The Page record here does not get updated as a result .

Could we get a event "OnAfterCreateItemFromTemplate "  within the function "CreateItemFromTemplate" after the CurrPage.Update.

![image](https://user-images.githubusercontent.com/49511747/95815133-c56d4f80-0d67-11eb-8515-6fff2dc1971e.png)

![image](https://user-images.githubusercontent.com/49511747/95814770-f5682300-0d66-11eb-9c2d-db4a8f7aade7.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
