### ISSUE TITLE
[Event Request] codeunit 7301 "Whse. Jnl.-Register Line" procedure DeleteFromBinContent

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9294]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure DeleteFromBinContent in codeunit 7301 "Whse. Jnl.-Register Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnDeleteFromBinContentOnAfterSetFiltersBeforeCalcfields(var BinContent: Record "Bin Content");
begin
end;

The code in procedure "DeleteFromBinContent" in codeunit 7301 "Whse. Jnl.-Register Line" would be modified as follows:

OLD CODE:

....

   local procedure DeleteFromBinContent(var WhseEntry: Record "Warehouse Entry")
    var
        FromBinContent: Record "Bin Content";
        WhseEntry2: Record "Warehouse Entry";
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        Sign: Integer;
        IsHandled: Boolean;
    begin
        with WhseEntry do begin
            FromBinContent.Get("Location Code", "Bin Code", "Item No.", "Variant Code", "Unit of Measure Code");
            ItemTrackingMgt.GetWhseItemTrkgSetup(FromBinContent."Item No.", WhseItemTrackingSetup);
            if WhseItemTrackingSetup."Lot No. Required" then
                FromBinContent.SetRange("Lot No. Filter", "Lot No.");
	.
	.
	.

                FromBinContent.SetRange("Lot No. Filter");
                FromBinContent.SetRange("Serial No. Filter");
                FromBinContent.CalcFields("Quantity (Base)");
                if FromBinContent."Quantity (Base)" + "Qty. (Base)" = 0 then
                    if (FromBinContent."Positive Adjmt. Qty. (Base)" = 0) and
                       (FromBinContent."Put-away Quantity (Base)" = 0) and
                       (not FromBinContent.Fixed)
	.
	.
	.

....

NEW CODE:

...

   local procedure DeleteFromBinContent(var WhseEntry: Record "Warehouse Entry")
    var
        FromBinContent: Record "Bin Content";
        WhseEntry2: Record "Warehouse Entry";
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        Sign: Integer;
        IsHandled: Boolean;
    begin
        with WhseEntry do begin
            FromBinContent.Get("Location Code", "Bin Code", "Item No.", "Variant Code", "Unit of Measure Code");
            ItemTrackingMgt.GetWhseItemTrkgSetup(FromBinContent."Item No.", WhseItemTrackingSetup);
            if WhseItemTrackingSetup."Lot No. Required" then
                FromBinContent.SetRange("Lot No. Filter", "Lot No.");
	.
	.
	.

                FromBinContent.SetRange("Lot No. Filter");
                FromBinContent.SetRange("Serial No. Filter");
		
		//new code start
		OnDeleteFromBinContentOnAfterSetFiltersBeforeCalcfields(FromBinContent);
		//new code end

                FromBinContent.CalcFields("Quantity (Base)");
                if FromBinContent."Quantity (Base)" + "Qty. (Base)" = 0 then
                    if (FromBinContent."Positive Adjmt. Qty. (Base)" = 0) and
                       (FromBinContent."Put-away Quantity (Base)" = 0) and
                       (not FromBinContent.Fixed)
	.
	.
	.
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
