### ISSUE TITLE
[Event Request] codeunit 7304 "Whse. Jnl.-Register Batch" procedure CreateItemJnlLine

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9295]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure CreateItemJnlLine in codeunit 7304 "Whse. Jnl.-Register Batch"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnCreateItemJnlLineOnBeforeExitQtytoHandle(WhseJnlLine2: Record "Warehouse Journal Line"; var ItemJnlLine: Record "Item Journal Line"; var QtytoHandleBase: Decimal);
begin
end;

The code in procedure "CreateItemJnlLine" in codeunit 7304 "Whse. Jnl.-Register Batch" would be modified as follows:

OLD CODE:

....

  local procedure CreateItemJnlLine(WhseJnlLine2: Record "Warehouse Journal Line"; var ItemJnlLine: Record "Item Journal Line"): Boolean
    var
        ReservEntry: Record "Reservation Entry";
        WhseItemTrkgLine: Record "Whse. Item Tracking Line";
        CreateReservEntry: Codeunit "Create Reserv. Entry";
        QtyToHandleBase: Decimal;
    begin
        WhseItemTrkgLine.SetCurrentKey(

	.
	.
	.
	
         if QtyToHandleBase <> 0 then begin
                    ItemJnlLine."Document No." := "Whse. Document No.";
                    ItemJnlLine.Validate("Posting Date", "Registering Date");
                    ItemJnlLine.Validate("Item No.", "Item No.");
                    ItemJnlLine.Validate("Variant Code", "Variant Code");
                    ItemJnlLine.Validate("Location Code", "Location Code");
                    ItemJnlLine.Validate("Unit of Measure Code", "Unit of Measure Code");
                    ItemJnlLine.Validate(Quantity, Round(QtyToHandleBase / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision));
                    ItemJnlLine.Description := Description;
                    ItemJnlLine."Source Type" := ItemJnlLine."Source Type"::Item;
                    ItemJnlLine."Source No." := "Item No.";
                    ItemJnlLine."Source Code" := "Source Code";
                    ItemJnlLine."Reason Code" := "Reason Code";
                    ItemJnlLine."Warehouse Adjustment" := true;
                    ItemJnlLine."Line No." := "Line No.";
                    OnAfterCreateItemJnlLine(ItemJnlLine, WhseItemTrkgLine, WhseJnlLine2);
                end;
            end;
        end;

        exit(QtyToHandleBase <> 0);
	
....

NEW CODE:

...

  local procedure CreateItemJnlLine(WhseJnlLine2: Record "Warehouse Journal Line"; var ItemJnlLine: Record "Item Journal Line"): Boolean
    var
        ReservEntry: Record "Reservation Entry";
        WhseItemTrkgLine: Record "Whse. Item Tracking Line";
        CreateReservEntry: Codeunit "Create Reserv. Entry";
        QtyToHandleBase: Decimal;
    begin
        WhseItemTrkgLine.SetCurrentKey(

	.
	.
	.
	
         if QtyToHandleBase <> 0 then begin
                    ItemJnlLine."Document No." := "Whse. Document No.";
                    ItemJnlLine.Validate("Posting Date", "Registering Date");
                    ItemJnlLine.Validate("Item No.", "Item No.");
                    ItemJnlLine.Validate("Variant Code", "Variant Code");
                    ItemJnlLine.Validate("Location Code", "Location Code");
                    ItemJnlLine.Validate("Unit of Measure Code", "Unit of Measure Code");
                    ItemJnlLine.Validate(Quantity, Round(QtyToHandleBase / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision));
                    ItemJnlLine.Description := Description;
                    ItemJnlLine."Source Type" := ItemJnlLine."Source Type"::Item;
                    ItemJnlLine."Source No." := "Item No.";
                    ItemJnlLine."Source Code" := "Source Code";
                    ItemJnlLine."Reason Code" := "Reason Code";
                    ItemJnlLine."Warehouse Adjustment" := true;
                    ItemJnlLine."Line No." := "Line No.";
                    OnAfterCreateItemJnlLine(ItemJnlLine, WhseItemTrkgLine, WhseJnlLine2);
                end;
            end;
        end;
	
	//new code start
	OnCreateItemJnlLineOnBeforeExitQtytoHandle((WhseJnlLine2, ItemJnlLine, QtyToHandleBase);
	//new code end

        exit(QtyToHandleBase <> 0);
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
