### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" procedure CalcQtyPickedNotShipped two new events

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9296]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need two new event publishers in procedure CalcQtyPickedNotShipped in codeunit 7307 "Whse.-Activity-Register"

NEW PUBLISHERS:

[IntegrationEvent(false, false)]
local procedure OnCalcQtyPickedNotShippedOnAfterSetTrackingFilter(var ReservEntry: Record "Reservation Entry"; WhseActivLine: Record "Warehouse Activity Line");
begin
end;

[IntegrationEvent(false, false)]
local procedure OnCalcQtyPickedNotShippedOnBeforeCheckWhseItemTrackingSetup(WhseActivLine: Record "Warehouse Activity Line"; WhseItemTrackingSetup: Record "Item Tracking Setup"; var QtyBasePicked: Decimal;var IsHandled: Boolean);
begin
end;

The code in procedure "CalcQtyPickedNotShipped" in codeunit 7307 "Whse.-Activity-Register" would be modified as follows:

OLD CODE:

....

    local procedure CalcQtyPickedNotShipped(WhseActivLine: Record "Warehouse Activity Line"; WhseItemTrackingSetup: Record "Item Tracking Setup") QtyBasePicked: Decimal
    var
        ReservEntry: Record "Reservation Entry";
        RegWhseActivLine: Record "Registered Whse. Activity Line";
        QtyHandled: Decimal;
    begin
        with WhseActivLine do begin
            ReservEntry.Reset();
            ReservEntry.SetCurrentKey("Item No.", "Variant Code", "Location Code", "Reservation Status");
            ReservEntry.SetRange("Item No.", "Item No.");
            ReservEntry.SetRange("Variant Code", "Variant Code");
            ReservEntry.SetRange("Location Code", "Location Code");
            ReservEntry.SetRange("Reservation Status", ReservEntry."Reservation Status"::Surplus);
            ReservEntry.SetTrackingFilterFromWhseActivityLineIfRequired(WhseActivLine, WhseItemTrackingSetup);
            if ReservEntry.Find('-') then
                repeat
                    if not ((ReservEntry."Source Type" = "Source Type") and
                            (ReservEntry."Source Subtype" = "Source Subtype") and
                            (ReservEntry."Source ID" = "Source No.") and
                            ((ReservEntry."Source Ref. No." = "Source Line No.") or
                             (ReservEntry."Source Ref. No." = "Source Subline No."))) and
                       not ReservEntry.Positive
                    then
                        QtyBasePicked := QtyBasePicked + Abs(ReservEntry."Quantity (Base)");
                until ReservEntry.Next = 0;

            if WhseItemTrackingSetup."Serial No. Required" or WhseItemTrackingSetup."Lot No. Required" then begin
                RegWhseActivLine.SetRange("Activity Type", "Activity Type");
                RegWhseActivLine.SetRange("No.", "No.");
                RegWhseActivLine.SetRange("Line No.", "Line No.");
                RegWhseActivLine.SetTrackingFilterFromWhseActivityLine(WhseActivLine);
                RegWhseActivLine.SetRange("Bin Code", "Bin Code");
                if RegWhseActivLine.FindSet then
                    repeat
                        QtyHandled := QtyHandled + RegWhseActivLine."Qty. (Base)";
                    until RegWhseActivLine.Next = 0;
                QtyBasePicked := QtyBasePicked + QtyHandled;
            end else
                QtyBasePicked := QtyBasePicked + "Qty. Handled (Base)";
        end;

        exit(QtyBasePicked);
    end;
	
....

NEW CODE:

...

    local procedure CalcQtyPickedNotShipped(WhseActivLine: Record "Warehouse Activity Line"; WhseItemTrackingSetup: Record "Item Tracking Setup") QtyBasePicked: Decimal
    var
        ReservEntry: Record "Reservation Entry";
        RegWhseActivLine: Record "Registered Whse. Activity Line";
        QtyHandled: Decimal;
	//new code start
	IsHandled: Boolean;
	//new code end
    begin
        with WhseActivLine do begin
            ReservEntry.Reset();
            ReservEntry.SetCurrentKey("Item No.", "Variant Code", "Location Code", "Reservation Status");
            ReservEntry.SetRange("Item No.", "Item No.");
            ReservEntry.SetRange("Variant Code", "Variant Code");
            ReservEntry.SetRange("Location Code", "Location Code");
            ReservEntry.SetRange("Reservation Status", ReservEntry."Reservation Status"::Surplus);
            ReservEntry.SetTrackingFilterFromWhseActivityLineIfRequired(WhseActivLine, WhseItemTrackingSetup);

	    //new code start
	    OnCalcQtyPickedNotShippedOnAfterSetTrackingFilter(ReservEntry,WhseActivLine);
	    //new code end

            if ReservEntry.Find('-') then
                repeat
                    if not ((ReservEntry."Source Type" = "Source Type") and
                            (ReservEntry."Source Subtype" = "Source Subtype") and
                            (ReservEntry."Source ID" = "Source No.") and
                            ((ReservEntry."Source Ref. No." = "Source Line No.") or
                             (ReservEntry."Source Ref. No." = "Source Subline No."))) and
                       not ReservEntry.Positive
                    then
                        QtyBasePicked := QtyBasePicked + Abs(ReservEntry."Quantity (Base)");
                until ReservEntry.Next = 0;

            //new code start
	    IsHandled:=false;
	    OnCalcQtyPickedNotShippedOnBeforeCheckWhseItemTrackingSetup(WhseActivLine,WhseItemTrackingSetup,QtyBasePicked,IsHandled);
	    If Not IsHandled then 
	    //new code end

            if WhseItemTrackingSetup."Serial No. Required" or WhseItemTrackingSetup."Lot No. Required" then begin
                RegWhseActivLine.SetRange("Activity Type", "Activity Type");
                RegWhseActivLine.SetRange("No.", "No.");
                RegWhseActivLine.SetRange("Line No.", "Line No.");
                RegWhseActivLine.SetTrackingFilterFromWhseActivityLine(WhseActivLine);
                RegWhseActivLine.SetRange("Bin Code", "Bin Code");
                if RegWhseActivLine.FindSet then
                    repeat
                        QtyHandled := QtyHandled + RegWhseActivLine."Qty. (Base)";
                    until RegWhseActivLine.Next = 0;
                QtyBasePicked := QtyBasePicked + QtyHandled;
            end else
                QtyBasePicked := QtyBasePicked + "Qty. Handled (Base)";
        end;

        exit(QtyBasePicked);
    end;
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
