### ISSUE TITLE
[Event Request] Table 5050 "Contact" - OnBeforeTestInteractLogEntry

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#9297]
Hello,

we are upgrading from an older NAV Version to BC16, is it possible to add a new Event and a "IsHandled" Boolean to the procedure "TypeChange" like it's been described below ?
I marked the new feature with a comment (//START - //END).

> >     var
> >         InteractLogEntry: Record Interaction Log Entry";
> >         Opp: Record Opportunity;
> >         Task: Record "To-do";
> >         Cont: Record Contact;
> >         CampaignTargetGrMgt: Codeunit Campaign Target Group Mgt";
> >         //START
> >         IsHandled: Boolean;
> >         //END
> >     begin
> >         RMSetup.Get();
> >
> >         //START
> >         OnBeforeTestInteractLogEntry(Rec, xRec, InteractLogEntry, Opp, Task, Cont, IsHandled);
> >         if not IsHandled then
> >         //END
> >             if Type <> xRec.Type then begin
> >                 InteractLogEntry.LockTable();
> >                 Cont.LockTable();
> >                 InteractLogEntry.SetCurrentKey(""Contact Company No."", ""Contact No."");
> >                 InteractLogEntry.SetRange(""Contact Company No."", ""Company No."");
> >                 InteractLogEntry.SetRange(""Contact No."", ""No."");
> >                 if InteractLogEntry.FindFirst then
> >                     Error(Text003, FieldCaption(Type));
> >                 OnTypeChangeOnAfterCheckInteractionLog(Rec, xRec);
> >                 Task.SetRange(""Contact Company No."", ""Company No."");
> >                 Task.SetRange(""Contact No."", ""No."");
> >                 if not Task.IsEmpty then
> >                     Error(CannotChangeWithOpenTasksErr, FieldCaption(Type));
> >                 Opp.SetRange(""Contact Company No."", ""Company No."");
> >                 Opp.SetRange(""Contact No."", ""No."");
> >                 if not Opp.IsEmpty then
> >                     Error(Text006, FieldCaption(Type));
> >             end;
> > 
> >             case Type of
> >             Type::Company:
> >                 begin
> >                     if Type <> xRec.Type then begin
> >                         TestField(""Organizational Level Code"", '');
> >                         TestField(""No. of Job Responsibilities"", 0);
> >                     end;
> >                     ""First Name"" := '';
> >                     ""Middle Name"" := '';
> >                     Surname := '';
> >                     ""Job Title"" := '';
> >                     ""Company No."" := ""No."";
> >                     ""Company Name"" := Name;
> >                     ""Salutation Code"" := RMSetup.""Def. Company Salutation Code"";
> >                 end;
> >             Type::Person:
> >                 begin
> >                     CampaignTargetGrMgt.DeleteContfromTargetGr(InteractLogEntry);
> >                     Cont.Reset();
> >                     Cont.SetCurrentKey(""Company No."");
> >                     Cont.SetRange(""Company No."", ""No."");
> >                     Cont.SetRange(Type, Type::Person);
> >                     if Cont.FindFirst then
> >                         Error(Text007, FieldCaption(Type));
> >                     if Type <> xRec.Type then begin
> >                         CalcFields(""No. of Business Relations"", ""No. of Industry Groups"");
> >                         TestField(""No. of Business Relations"", 0);
> >                         TestField(""No. of Industry Groups"", 0);
> >                         TestField(""Currency Code"", '');
> >                         TestField(""VAT Registration No."", '');
> >                     end;
> >                     if ""Company No."" = ""No."" then begin
> >                         ""Company No."" := '';
> >                         ""Company Name"" := '';
> >                         ""Salutation Code"" := RMSetup.""Default Person Salutation Code"";
> >                         NameBreakdown;
> >                     end;
> >                 end;
> >         end;
> >         OnAfterSetTypeForContact(Rec);
> >         Validate(""Lookup Contact No."");
> > 
> >         if Cont.Get(""No."") then begin
> >             if Type = Type::Company then
> >                 CheckDuplicates
> >             else
> >                 DuplMgt.RemoveContIndex(Rec, false);
> >         end;
> >     end;
> > 

Thanks in advance !

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
