### ISSUE TITLE
[Event Request] Page 6500 "Item Tracking Summary" procedure DrillDownEntries

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9298]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure DrillDownEntries in Page 6500 "Item Tracking Summary"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnDrillDownEntriesOnAfterSetFilters(var TempReservEntry: Record "Reservation Entry" temporary; EntrySummary; Record "Entry Summary" temporary);
begin
end;

The code in procedure "DrillDownEntries" in Page 6500 "Item Tracking Summary" would be modified as follows:

OLD CODE:

....

    local procedure DrillDownEntries(FieldNumber: Integer)
    var
        TempReservEntry2: Record "Reservation Entry" temporary;
    begin
        TempReservEntry.Reset();
        TempReservEntry.SetCurrentKey(
          "Item No.", "Source Type", "Source Subtype", "Reservation Status",
          "Location Code", "Variant Code", "Shipment Date", "Expected Receipt Date", "Serial No.", "Lot No.");

        TempReservEntry.SetRange("Lot No.", "Lot No.");
        if "Serial No." <> '' then
            TempReservEntry.SetRange("Serial No.", "Serial No.");

        case FieldNumber of
            FieldNo("Total Quantity"):
                begin
                    // An Item Ledger Entry will in itself be represented with a surplus TempReservEntry. Order tracking
                    // and reservations against Item Ledger Entries are therefore kept out, as these quantities would
                    // otherwise be represented twice in the drill down.

                    TempReservEntry.SetRange(Positive, true);
                    TempReservEntry2.Copy(TempReservEntry);  // Copy key
                    if TempReservEntry.FindSet then
                        repeat
                            TempReservEntry2 := TempReservEntry;
                            if TempReservEntry."Source Type" = DATABASE::"Item Ledger Entry" then begin
                                if TempReservEntry."Reservation Status" = TempReservEntry."Reservation Status"::Surplus then
                                    TempReservEntry2.Insert();
                            end else
                                TempReservEntry2.Insert();
                        until TempReservEntry.Next = 0;
                    TempReservEntry2.Ascending(false);
                    PAGE.RunModal(PAGE::"Avail. - Item Tracking Lines", TempReservEntry2);
                end;
            FieldNo("Total Requested Quantity"):
                begin
                    TempReservEntry.SetRange(Positive, false);
                    TempReservEntry.Ascending(false);
                    PAGE.RunModal(PAGE::"Avail. - Item Tracking Lines", TempReservEntry);
                end;
        end;
    end;
	
....

NEW CODE:

...

    local procedure DrillDownEntries(FieldNumber: Integer)
    var
        TempReservEntry2: Record "Reservation Entry" temporary;
    begin
        TempReservEntry.Reset();
        TempReservEntry.SetCurrentKey(
          "Item No.", "Source Type", "Source Subtype", "Reservation Status",
          "Location Code", "Variant Code", "Shipment Date", "Expected Receipt Date", "Serial No.", "Lot No.");

        TempReservEntry.SetRange("Lot No.", "Lot No.");
        if "Serial No." <> '' then
            TempReservEntry.SetRange("Serial No.", "Serial No.");

        //new code start
	OnDrillDownEntriesOnAfterSetFilters(TempReservEntry,Rec);
	//new code end

        case FieldNumber of
            FieldNo("Total Quantity"):
                begin
                    // An Item Ledger Entry will in itself be represented with a surplus TempReservEntry. Order tracking
                    // and reservations against Item Ledger Entries are therefore kept out, as these quantities would
                    // otherwise be represented twice in the drill down.

                    TempReservEntry.SetRange(Positive, true);
                    TempReservEntry2.Copy(TempReservEntry);  // Copy key
                    if TempReservEntry.FindSet then
                        repeat
                            TempReservEntry2 := TempReservEntry;
                            if TempReservEntry."Source Type" = DATABASE::"Item Ledger Entry" then begin
                                if TempReservEntry."Reservation Status" = TempReservEntry."Reservation Status"::Surplus then
                                    TempReservEntry2.Insert();
                            end else
                                TempReservEntry2.Insert();
                        until TempReservEntry.Next = 0;
                    TempReservEntry2.Ascending(false);
                    PAGE.RunModal(PAGE::"Avail. - Item Tracking Lines", TempReservEntry2);
                end;
            FieldNo("Total Requested Quantity"):
                begin
                    TempReservEntry.SetRange(Positive, false);
                    TempReservEntry.Ascending(false);
                    PAGE.RunModal(PAGE::"Avail. - Item Tracking Lines", TempReservEntry);
                end;
        end;
    end;
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
