### ISSUE TITLE
[Event Request] Page 6500 "Item Tracking Summary" procedure DrillDownBinContent

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9299]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure DrillDownBinContent in Page 6500 "Item Tracking Summary"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnDrillDownBinContentOnAfterSetFilters(var BinContent: Record "Bin Content"; EntrySummary; Record "Entry Summary" temporary);
begin
end;

The code in procedure "DrillDownBinContent" in Page 6500 "Item Tracking Summary" would be modified as follows:

OLD CODE:

....
    local procedure DrillDownBinContent(FieldNumber: Integer)
    var
        BinContent: Record "Bin Content";
    begin
        if CurrBinCode = '' then
            exit;
        TempReservEntry.Reset();
        if not TempReservEntry.FindFirst then
            exit;

        CurrItemTrackingCode.TestField(Code);

        BinContent.SetRange("Location Code", TempReservEntry."Location Code");
        BinContent.SetRange("Item No.", TempReservEntry."Item No.");
        BinContent.SetRange("Variant Code", TempReservEntry."Variant Code");
        if CurrItemTrackingCode."Lot Warehouse Tracking" then
            if "Lot No." <> '' then
                BinContent.SetRange("Lot No. Filter", "Lot No.");
        if CurrItemTrackingCode."SN Warehouse Tracking" then
            if "Serial No." <> '' then
                BinContent.SetRange("Serial No. Filter", "Serial No.");

        if FieldNumber = FieldNo("Bin Content") then
            BinContent.SetRange("Bin Code", CurrBinCode);

        PAGE.RunModal(PAGE::"Bin Content", BinContent);
    end;
	
....

NEW CODE:

...

    local procedure DrillDownBinContent(FieldNumber: Integer)
    var
        BinContent: Record "Bin Content";
    begin
        if CurrBinCode = '' then
            exit;
        TempReservEntry.Reset();
        if not TempReservEntry.FindFirst then
            exit;

        CurrItemTrackingCode.TestField(Code);

        BinContent.SetRange("Location Code", TempReservEntry."Location Code");
        BinContent.SetRange("Item No.", TempReservEntry."Item No.");
        BinContent.SetRange("Variant Code", TempReservEntry."Variant Code");
        if CurrItemTrackingCode."Lot Warehouse Tracking" then
            if "Lot No." <> '' then
                BinContent.SetRange("Lot No. Filter", "Lot No.");
        if CurrItemTrackingCode."SN Warehouse Tracking" then
            if "Serial No." <> '' then
                BinContent.SetRange("Serial No. Filter", "Serial No.");

        if FieldNumber = FieldNo("Bin Content") then
            BinContent.SetRange("Bin Code", CurrBinCode);

        //new code start
	OnDrillDownBinContentOnAfterSetFilters(BinContent,Rec);
	//new code end

        PAGE.RunModal(PAGE::"Bin Content", BinContent);
    end;
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
