### ISSUE TITLE
Codeunit 333 - Code Refactoring and Publisher Parameters

### ISSUE THREAD

**Issue by wweidl** [Microsoft/ALAppExtensions#930]
For our solution it is necessary that we move specific Requisition Lines to already existing Purchase Order instead of creating new Purchase Order. 
To integrate with other Extensions, which e.g. subscribe to the Publisher on Purchase Line Insertion in Codeunit 333 (OnBeforePurchOrderLineInsert, OnAfterPurchOrderLineInsert, OnAfterInsertPurchOrderLine)
we need either call the Function InsertPurchOrderLine or the Publishers in Codeunit 333.

Therefore I ask, if it is possible, if 

1. 

The glob. Variables PlanningResiliency, SuppressCommit, PrintPurchOrders and EndOrderDate can be added as new Parameters of the Publisher Function OnBeforeCode

2. 

To Integrate with other Extension which use the Publishers called in Function InsertPurchOrderLine:

Is it possible that the Function InsertPurchOrderLine is changed to global/external and 
additionally the Call of the CheckInsertFinalizePurchaseOrderHeader Function and Progress Window Update inside this Function can be skipped ?
e.g. by new Function Parameter (ExternalCall:Boolean)

```
+ IF NOT ExternalCall THEN
       IF CheckInsertFinalizePurchaseOrderHeader(ReqLine2,PurchOrderHeader,TRUE) THEN BEGIN

    ...
    
    
+ IF NOT ExternalCall THEN
      IF NOT PlanningResiliency THEN
    
```    
    
Alternative would be, if it would be possible to make the three Publisher Function OnBeforePurchOrderLineInsert, OnAfterPurchOrderLineInsert, OnAfterInsertPurchOrderLine 
callable by external Code.

**Comment by AlexanderYakunin** [comment]
Can we simply make this as regular feature in BaseApp? IF we add field Purchase Order No., for example?

**Comment by wweidl** [comment]
This would be the best Solution, if this Feature can be added in Standard Business Central.
