### ISSUE TITLE
[Additional Parameter Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnBeforeRaiseExceedLengthError

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#9304]
Hello,

we are upgrading from an older NAV Version to BC16, is it possible to add new parameters to the Event "OnBeforeRaiseExceedLengthError" like it's been described below ?

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeRaiseExceedLengthError(var GenJournalBatch: Record "Gen. Journal Batch"; var RaiseError: Boolean; var GenJnlLine: Record "Gen. Journal Line)
    begin
    end;
```

Thanks in advance !

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
