### ISSUE TITLE
[Event Request] Page 6510 "Item Tracking Lines" trigger OnModifyRecord two new events

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9305]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need two new event publishers in trigger OnModifyRecord in Page 6510 "Item Tracking Lines"

NEW PUBLISHERS:

[IntegrationEvent(false, false)]
local procedure OnBeforeOnModifyRecord(TrackingSpecification: Record "Tracking Specification" temporary; OldTrackingSpecification: Record "Tracking Specification" temporary; InsertIsBlocked: Boolean; var IsExit: Boolean);
begin
end;

	
[IntegrationEvent(false, false)]
local procedure OnModfiyRecordOnBeforeCheckItemTracking(TrackingSpecification: Record "Tracking Specification" temporary; OldTrackingSpecification: Record "Tracking Specification" temporary;  
	var xTempTrackingSpec: Record "Tracking Specification" temporary; CurrentSignFactor: Integer; var SourceQuantityArray: array[5] of Decimal; var IsHandled: Boolean);
begin
end;

The code in procedure "trigger OnModifyRecord" in Page 6510 "Item Tracking Lines" would be modified as follows:

OLD CODE:

....
    
    trigger OnModifyRecord(): Boolean
    var
        xTempTrackingSpec: Record "Tracking Specification" temporary;
    begin
        if InsertIsBlocked then
            if (xRec."Lot No." <> "Lot No.") or
               (xRec."Serial No." <> "Serial No.") or
               (xRec."Quantity (Base)" <> "Quantity (Base)")
            then
                exit(false);

        if not TestTempSpecificationExists then begin
            Modify;

            if (xRec."Lot No." <> "Lot No.") or (xRec."Serial No." <> "Serial No.") then begin
                xTempTrackingSpec := xRec;
                ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
                  xTempTrackingSpec, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 2);
            end;

            if TempItemTrackLineModify.Get("Entry No.") then
                TempItemTrackLineModify.Delete();
            if TempItemTrackLineInsert.Get("Entry No.") then begin
                TempItemTrackLineInsert.TransferFields(Rec);
                TempItemTrackLineInsert.Modify();
                ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
                  TempItemTrackLineInsert, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 1);
            end else begin
                TempItemTrackLineModify.TransferFields(Rec);
                TempItemTrackLineModify.Insert();
                ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
                  TempItemTrackLineModify, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 1);
            end;
        end;
        CalculateSums;

        exit(false);
    end;
	
....

NEW CODE:

...

    trigger OnModifyRecord(): Boolean
    var
        xTempTrackingSpec: Record "Tracking Specification" temporary;
	//new code start
	IsHandled: Boolean;
	IsExit: Boolean;
	//new code end
    begin
	//new code start
	IsExit:= false;
	OnBeforeOnModifyRecord(Rec, xRec, InsertIsBlocked, IsExit);
	if IsExit then
	  exit(false); 
	//new code end

        if InsertIsBlocked then
            if (xRec."Lot No." <> "Lot No.") or
               (xRec."Serial No." <> "Serial No.") or
               (xRec."Quantity (Base)" <> "Quantity (Base)")
            then
                exit(false);

        if not TestTempSpecificationExists then begin
            Modify;

            //New code start
            IsHandled:= false;
            OnModfiyRecordOnBeforeCheckItemTracking(Rec, xRec, xTempTrackingSpec, CurrentSignFactor, SourceQuantityArray, IsHandled);	
	    If not IsHandled then
	    //New code end
             			
            if (xRec."Lot No." <> "Lot No.") or (xRec."Serial No." <> "Serial No.") then begin
                xTempTrackingSpec := xRec;
                ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
                  xTempTrackingSpec, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 2);
            end;

            if TempItemTrackLineModify.Get("Entry No.") then
                TempItemTrackLineModify.Delete();
            if TempItemTrackLineInsert.Get("Entry No.") then begin
                TempItemTrackLineInsert.TransferFields(Rec);
                TempItemTrackLineInsert.Modify();
                ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
                  TempItemTrackLineInsert, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 1);
            end else begin
                TempItemTrackLineModify.TransferFields(Rec);
                TempItemTrackLineModify.Insert();
                ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
                  TempItemTrackLineModify, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 1);
            end;
        end;
        CalculateSums;

        exit(false);
    end;
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
