### ISSUE TITLE
[Additional Parameter Request] Codeunit 260 "Document-Mailing" - OnBeforeSendEmail

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#9307]
Hello,

we are upgrading from an older NAV Version to BC16, is it possible to add a new parameter "EmailDocName: Text[250]" to the Event "OnBeforeSendEmail" like it's been described below ?

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeSendEmail(var TempEmailItem: Record "Email Item" temporary; var IsFromPostedDoc: Boolean; var PostedDocNo: Code[20]; var HideDialog: Boolean; var ReportUsage: Integer; var EmailSentSuccesfully: Boolean; var IsHandled: Boolean; EmailDocName: Text[250])
    begin
    end;
```

Thanks in advance !

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
