### ISSUE TITLE
[Additional Parameter Request] Codeunit 64 "Sales-Get Shipment" - OnAfterInsertLines

### ISSUE THREAD

**Issue by LukasSchuetz95** [microsoft/ALAppExtensions#9308]
Hello,

we are upgrading from an older NAV Version to BC16, is it possible to add a new parameter "var SalesLine: Record "Sales Line"" to the Event "OnAfterInsertLines" like it's been described below ?

```
[IntegrationEvent(false, false)]
    local procedure OnAfterInsertLines(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line")
    begin
    end;
```

Thanks in advance !

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
