### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnCheckAndUpdateOnAfterCalcInvDiscount

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9313]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `CheckAndUpdate`. Standard publisher `OnCheckAndUpdateOnAfterCalcInvDiscount` would suit us if it had additional parameter `TempWhseShptHeader: Record "Warehouse Shipment Header"`.

![image](https://user-images.githubusercontent.com/70525691/95850341-57219080-0d59-11eb-86ae-c5553b1ff1d0.png)

    [IntegrationEvent(false, false)]
    local procedure OnCheckAndUpdateOnAfterCalcInvDiscount(SalesHeader: Record "Sales Header"; TempWhseShptHeader: Record "Warehouse Shipment Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
