### ISSUE TITLE
Report 15000003 "Rem. payment order - Import" (Norwegian Localization)

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#9314]
The following code in the function FindFiles will never find files from the payment return file setup. The reason is that the function FileMgt.ClientDirectoryExists always returns false if the client is not Windows. Could this be changed, so local files will be picked up, when importing data from files to the payment journal?

if FileMgt.ClientDirectoryExists(FilePath) then begin
            FileMgt.GetClientDirectoryFilesList(TempNameValueBuffer, FilePath);
            if TempNameValueBuffer.FindSet then
                repeat
                    FileCopy.Name := LowerCase(FileMgt.GetFileName(TempNameValueBuffer.Name));
                    FileMgt.GetClientFileProperties(TempNameValueBuffer.Name, FileCopy.Date, FileCopy.Time, FileSize);
                    FileCopy.Size := FileSize;
                    FileCopy.Insert();
                until TempNameValueBuffer.Next = 0;
        end;

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
