### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnCancelUndeliverableQuantity

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9315]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `PostSalesLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95850804-0d857580-0d5a-11eb-96c4-a3b13b2282cb.png)

    [IntegrationEvent(false, false)]
    local procedure OnCancelUndeliverableQuantity(var SalesLine: Record "Sales Line"; var SalesHeader: Record "Sales Header"; var WhseShptHeader: Record "Warehouse Shipment Header"; WhseShip: Boolean; PreviewMode: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
