### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnAfterCopyInPostItemJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9316]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `PostItemJnlLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95851090-72d96680-0d5a-11eb-812b-cc6cc01dffb7.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyInPostItemJnlLine(var SalesLineItem: Record "Sales Line"; SalesHeader: Record "Sales Header"; SalesInvHeader: Record "Sales Invoice Header"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var ItemJnlLine: Record "Item Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
