### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeSumSalesLines2

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9317]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure SumSalesLines2 would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95851907-97820e00-0d5b-11eb-905b-eb279b173d48.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSumSalesLines2(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; InsertSalesLine: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
