### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnBeforeLockTables

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9318]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `LockTables`. Standard publisher `OnBeforeLockTables `would suit us if it had additional parameter `var IsHandled: Boolean` with `exit` functionality.

![image](https://user-images.githubusercontent.com/70525691/95852285-2f7ff780-0d5c-11eb-97ad-4bf47ad0cf07.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLockTables(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; CommitIsSuppressed: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
