### ISSUE TITLE
[Event Request] Page 6510 "Item Tracking Lines" procedure WriteToDatabase

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9319]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure WriteToDatabase in Page 6510 "Item Tracking Lines"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnWriteToDatabaseOnModifyLoop(xTempItemTrackingLine: Record "Tracking Specification" temporary;  TempItemTrackLineModify: Record "Tracking Specification" temporary; var TrackValuesChanged: Boolean);
begin
end;

	
The code in procedure "WriteToDatabase" in Page 6510 "Item Tracking Lines" would be modified as follows:

OLD CODE:

....
    
local procedure WriteToDatabase()
    var
        Window: Dialog;
        ChangeType: Option Insert,Modify,Delete;
        EntryNo: Integer;
        NoOfLines: Integer;
        i: Integer;
        ModifyLoop: Integer;
        Decrease: Boolean;
    begin
        OnBeforeWriteToDatabase(Rec, CurrentPageIsOpen);
        if CurrentPageIsOpen then begin
            TempReservEntry.LockTable();
            TempRecValid;

            if Item."Order Tracking Policy" = Item."Order Tracking Policy"::None then
                QtyToAddAsBlank := 0
            else
                QtyToAddAsBlank := UndefinedQtyArray[1] * CurrentSignFactor;
	.
	.
	.
     for ModifyLoop := 1 to 2 do begin
                if TempItemTrackLineModify.Find('-') then
                    repeat
                        if xTempItemTrackingLine.Get(TempItemTrackLineModify."Entry No.") then begin
                            // Process decreases before increases
                            OnWriteToDatabaseOnBeforeRegisterDecrease(TempItemTrackLineModify);
                            Decrease := (xTempItemTrackingLine."Quantity (Base)" > TempItemTrackLineModify."Quantity (Base)");
                            if ((ModifyLoop = 1) and Decrease) or ((ModifyLoop = 2) and not Decrease) then begin
                                i := i + 1;
                                if (xTempItemTrackingLine."Serial No." <> TempItemTrackLineModify."Serial No.") or
                                   (xTempItemTrackingLine."Lot No." <> TempItemTrackLineModify."Lot No.") or
                                   (xTempItemTrackingLine."Appl.-from Item Entry" <> TempItemTrackLineModify."Appl.-from Item Entry") or
                                   (xTempItemTrackingLine."Appl.-to Item Entry" <> TempItemTrackLineModify."Appl.-to Item Entry")
                                then begin
                                    RegisterChange(xTempItemTrackingLine, xTempItemTrackingLine, ChangeType::Delete, false);
                                    RegisterChange(TempItemTrackLineModify, TempItemTrackLineModify, ChangeType::Insert, false);
                                    if (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Handle (Base)") or
                                       (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Invoice (Base)")
                                    then
                                        SetQtyToHandleAndInvoice(TempItemTrackLineInsert);
                                end else begin
                                    RegisterChange(xTempItemTrackingLine, TempItemTrackLineModify, ChangeType::Modify, false);
                                    SetQtyToHandleAndInvoice(TempItemTrackLineModify);
                                end;
                                TempItemTrackLineModify.Delete();
                            end;
                        end else begin
                            i := i + 1;
	.
	.
	.
	
....

NEW CODE:

...

local procedure WriteToDatabase()
    var
        Window: Dialog;
        ChangeType: Option Insert,Modify,Delete;
        EntryNo: Integer;
        NoOfLines: Integer;
        i: Integer;
        ModifyLoop: Integer;
        Decrease: Boolean;

	//new code start
	TrackValuesChanged: Boolean;
	//new code end

    begin
        OnBeforeWriteToDatabase(Rec, CurrentPageIsOpen);
        if CurrentPageIsOpen then begin
            TempReservEntry.LockTable();
            TempRecValid;

            if Item."Order Tracking Policy" = Item."Order Tracking Policy"::None then
                QtyToAddAsBlank := 0
            else
                QtyToAddAsBlank := UndefinedQtyArray[1] * CurrentSignFactor;
	.
	.
	.
     for ModifyLoop := 1 to 2 do begin
                if TempItemTrackLineModify.Find('-') then
                    repeat
                        if xTempItemTrackingLine.Get(TempItemTrackLineModify."Entry No.") then begin
                            // Process decreases before increases
                            OnWriteToDatabaseOnBeforeRegisterDecrease(TempItemTrackLineModify);
                            Decrease := (xTempItemTrackingLine."Quantity (Base)" > TempItemTrackLineModify."Quantity (Base)");
                            if ((ModifyLoop = 1) and Decrease) or ((ModifyLoop = 2) and not Decrease) then begin
                                i := i + 1;
		                
				//new code start
                                **TrackValuesChanged:=false;
                                OnWriteToDatabaseOnModifyLoop(xTempItemTrackingLine, TempItemTrackLineModify, TrackValuesChanged);**
                                //new code end

                                if (xTempItemTrackingLine."Serial No." <> TempItemTrackLineModify."Serial No.") or
                                   (xTempItemTrackingLine."Lot No." <> TempItemTrackLineModify."Lot No.") or
                                   (xTempItemTrackingLine."Appl.-from Item Entry" <> TempItemTrackLineModify."Appl.-from Item Entry") or
                                   (xTempItemTrackingLine."Appl.-to Item Entry" <> TempItemTrackLineModify."Appl.-to Item Entry")

				//new code begin
				**or TrackValuesChanged**
				//new code end	
		
                                then begin
                                    RegisterChange(xTempItemTrackingLine, xTempItemTrackingLine, ChangeType::Delete, false);
                                    RegisterChange(TempItemTrackLineModify, TempItemTrackLineModify, ChangeType::Insert, false);
                                    if (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Handle (Base)") or
                                       (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Invoice (Base)")
                                    then
                                        SetQtyToHandleAndInvoice(TempItemTrackLineInsert);
                                end else begin
                                    RegisterChange(xTempItemTrackingLine, TempItemTrackLineModify, ChangeType::Modify, false);
                                    SetQtyToHandleAndInvoice(TempItemTrackLineModify);
                                end;
                                TempItemTrackLineModify.Delete();
                            end;
                        end else begin
                            i := i + 1;
	.
	.
	.
....

Thanks!

**Comment by AlexanderYakunin** [comment]
I assume you code samples coming from older version. Please look into latest code in Master, we already have here function HasSameTracking() with OnAfterHasSameTracking event, so you can probably use it for your case. Please confirm if you still need this request after review latest code. 

                                if (not xTempItemTrackingLine.HasSameTracking(TempItemTrackLineModify)) or
                                   (xTempItemTrackingLine."Appl.-from Item Entry" <> TempItemTrackLineModify."Appl.-from Item Entry") or
                                   (xTempItemTrackingLine."Appl.-to Item Entry" <> TempItemTrackLineModify."Appl.-to Item Entry")
                                then begin
                                    RegisterChange(xTempItemTrackingLine, xTempItemTrackingLine, ChangeType::Delete, false);

**Comment by mcarmenvalera** [comment]
Hi Alexander,

You are right, I was checking code in a previous version.

The function HasSameTracking() works for me.

Sorry for the inconvenience!
