### ISSUE TITLE
CU 7301 new publisher OnAfterRegisterLine

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#932]
Hi,

we need a new publisher on CU 7301 OnAfterRegisterLine(WhseJnlLine) in the end of function Code().

Thank you in advance and best regards,
K.

**Comment by KReinmann** [comment]
Hi,
Are there new insights here?
Thanks in advance,
best regards,
Kathrin

**Comment by KReinmann** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
I am VERY sorry about the extremely late reply on this one! I'm not sure what happened here, but somehow this issue never made it into our system - which should have happened when I tagged it a year ago with "event-request". It hence completely fell of my radar :-( My apologies!
In the meantime an event seems to have made it into function code at the very end!
```
...
            end else
                InitWhseEntry(GlobalWhseEntry, "To Zone Code", "To Bin Code", 1);
            InsertWhseEntry(GlobalWhseEntry);
        end;
        OnAfterCode(WhseJnlLine);
    end;
```
Does that suffice? If not, I'll open a bug instantly. Again, I'm very sorry... Not sure how this happened!

**Comment by JesperSchulz** [comment]
Assuming issue was addressed. If not, please open new issue :-) Thanks!
