### ISSUE TITLE
[Event Request] Page 6510 "Item Tracking Lines" procedure TestTempSpecificationExists

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9320]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure TestTempSpecificationExists in Page 6510 "Item Tracking Lines"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnTestTempSpecificationExistsOnAfterSetFilters(var TrackingSpecification: Record "Tracking Specification" temporary);
begin
end;

	
The code in procedure "TestTempSpecificationExists" in Page 6510 "Item Tracking Lines" would be modified as follows:

OLD CODE:

....
    
    procedure TestTempSpecificationExists() Exists: Boolean
    var
        TrackingSpecification: Record "Tracking Specification";
    begin
        TrackingSpecification.Copy(Rec);
        SetCurrentKey("Lot No.", "Serial No.");
        SetRange("Serial No.", "Serial No.");
        if "Serial No." = '' then
            SetRange("Lot No.", "Lot No.");
        SetFilter("Entry No.", '<>%1', "Entry No.");
        SetRange("Buffer Status", 0);
        Exists := not IsEmpty;
        Copy(TrackingSpecification);
        if Exists and CurrentPageIsOpen then
            if "Serial No." = '' then
                Message(Text011, "Serial No.", "Lot No.")
            else
                Message(Text012, "Serial No.");
    end;
....

NEW CODE:

...

    procedure TestTempSpecificationExists() Exists: Boolean
    var
        TrackingSpecification: Record "Tracking Specification";
    begin
        TrackingSpecification.Copy(Rec);
        SetCurrentKey("Lot No.", "Serial No.");
        SetRange("Serial No.", "Serial No.");
        if "Serial No." = '' then
            SetRange("Lot No.", "Lot No.");
        SetFilter("Entry No.", '<>%1', "Entry No.");
        SetRange("Buffer Status", 0);

	//new code start
	OnTestTempSpecificationExistsOnAfterSetFilters(Rec);
	//new code end

        Exists := not IsEmpty;
        Copy(TrackingSpecification);
        if Exists and CurrentPageIsOpen then
            if "Serial No." = '' then
                Message(Text011, "Serial No.", "Lot No.")
            else
                Message(Text012, "Serial No.");
    end;
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
