### ISSUE TITLE
[Event Request] Page 6510 "Item Tracking Lines" procedure RegisterItemTrackingLines

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#9321]
Dear ALAppExtensions Team:

Our solution extends the tracking management funcionality.To do so, we need a new event publisher in procedure RegisterItemTrackingLines in Page 6510 "Item Tracking Lines"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnRegisterItemTrackingLinesOnAfterReclass(var TrackingSpecification: Record "Tracking Specification" temporary;var TempTrackingSpecification: Record "Tracking Specification" temporary);
begin
end;

	
The code in procedure "RegisterItemTrackingLines" in Page 6510 "Item Tracking Lines" would be modified as follows:

OLD CODE:

....
    
procedure RegisterItemTrackingLines(SourceSpecification: Record "Tracking Specification"; AvailabilityDate: Date; var TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
        SourceSpecification.TestField("Source Type"); // Check if source has been set.
        if not CalledFromSynchWhseItemTrkg then
            TempTrackingSpecification.Reset();
        if not TempTrackingSpecification.Find('-') then
            exit;

        IsCorrection := SourceSpecification.Correction;
        ExcludePostedEntries := true;
        SetSourceSpec(SourceSpecification, AvailabilityDate);
        Reset;
        SetCurrentKey("Lot No.", "Serial No.");

        repeat
            SetTrackingFilterFromSpec(TempTrackingSpecification);
            if Find('-') then begin
                if IsCorrection then begin
                    "Quantity (Base)" += TempTrackingSpecification."Quantity (Base)";
                    "Qty. to Handle (Base)" += TempTrackingSpecification."Qty. to Handle (Base)";
                    "Qty. to Invoice (Base)" += TempTrackingSpecification."Qty. to Invoice (Base)";
                end else
                    Validate("Quantity (Base)", "Quantity (Base)" + TempTrackingSpecification."Quantity (Base)");
                Modify;
            end else begin
                TransferFields(SourceSpecification);
                CopyTrackingFromTrackingSpec(TempTrackingSpecification);
                "Warranty Date" := TempTrackingSpecification."Warranty Date";
                "Expiration Date" := TempTrackingSpecification."Expiration Date";
                if FormRunMode = FormRunMode::Reclass then begin
                    "New Serial No." := TempTrackingSpecification."New Serial No.";
                    "New Lot No." := TempTrackingSpecification."New Lot No.";
                    "New Expiration Date" := TempTrackingSpecification."New Expiration Date"
                end;
                OnAfterCopyTrackingSpec(TempTrackingSpecification, Rec);
                Validate("Quantity (Base)", TempTrackingSpecification."Quantity (Base)");
                "Entry No." := NextEntryNo;
                Insert;
            end;
        until TempTrackingSpecification.Next = 0;
        OnAfterRegisterItemTrackingLines(SourceSpecification, TempTrackingSpecification, Rec, AvailabilityDate);

        Reset;
	.
	.
	.
....

NEW CODE:

...

procedure RegisterItemTrackingLines(SourceSpecification: Record "Tracking Specification"; AvailabilityDate: Date; var TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
        SourceSpecification.TestField("Source Type"); // Check if source has been set.
        if not CalledFromSynchWhseItemTrkg then
            TempTrackingSpecification.Reset();
        if not TempTrackingSpecification.Find('-') then
            exit;

        IsCorrection := SourceSpecification.Correction;
        ExcludePostedEntries := true;
        SetSourceSpec(SourceSpecification, AvailabilityDate);
        Reset;
        SetCurrentKey("Lot No.", "Serial No.");

        repeat
            SetTrackingFilterFromSpec(TempTrackingSpecification);
            if Find('-') then begin
                if IsCorrection then begin
                    "Quantity (Base)" += TempTrackingSpecification."Quantity (Base)";
                    "Qty. to Handle (Base)" += TempTrackingSpecification."Qty. to Handle (Base)";
                    "Qty. to Invoice (Base)" += TempTrackingSpecification."Qty. to Invoice (Base)";
                end else
                    Validate("Quantity (Base)", "Quantity (Base)" + TempTrackingSpecification."Quantity (Base)");
                Modify;
            end else begin
                TransferFields(SourceSpecification);
                CopyTrackingFromTrackingSpec(TempTrackingSpecification);
                "Warranty Date" := TempTrackingSpecification."Warranty Date";
                "Expiration Date" := TempTrackingSpecification."Expiration Date";
                if FormRunMode = FormRunMode::Reclass then begin
                    "New Serial No." := TempTrackingSpecification."New Serial No.";
                    "New Lot No." := TempTrackingSpecification."New Lot No.";
                    "New Expiration Date" := TempTrackingSpecification."New Expiration Date"
		    
                    //New code start
		    OnRegisterItemTrackingLinesOnAfterReclass(Rec,TempTrackingSpecification);
		    //New code end

                end;
                OnAfterCopyTrackingSpec(TempTrackingSpecification, Rec);
                Validate("Quantity (Base)", TempTrackingSpecification."Quantity (Base)");
                "Entry No." := NextEntryNo;
                Insert;
            end;
        until TempTrackingSpecification.Next = 0;
        OnAfterRegisterItemTrackingLines(SourceSpecification, TempTrackingSpecification, Rec, AvailabilityDate);

        Reset;
	.
	.
	.
....

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
