### ISSUE TITLE
[Event Request] Codeunit 99000845 "Reservation Management" - OnAfterCalcReservedQty

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9322]
Hi team,

In Codeunit 99000845 Reservation Management procedure `CalcReservedQtyOnPick` we would like to have the ability to run some custom code, for that an event at the end of procedure code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95855269-c8b10d00-0d60-11eb-8028-e195b510fe44.png)
```
[IntegrationEvent(true, false)]
local procedure OnAfterCalcReservedQty(var Item: Record Item; var WhseActivLine: Record "Warehouse Activity Line"; var AvailQty: Decimal; var CalcReservEntry: Record "Reservation Entry")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
