### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnRecreateReservEntryReqLineOnAfterRecreateReqLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9323]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the procedure RecreateReservEntryReqLine, we need to add our code at specific a place. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95862432-35c5a200-0d63-11eb-93f8-acb276a49af6.png)

With this integration event : 
![image](https://user-images.githubusercontent.com/34645582/95862369-1cbcf100-0d63-11eb-93d1-f4f846dafe33.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
