### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeSetDefaultSalesperson

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9333]
We are migrating our code from NAV 2018 to BC16.4. In the Table 36 "Sales Header", in the procedure SetDefaultSalesperson, we need to add our code at specific places. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95874453-32d1ae00-0d71-11eb-9529-4acb7c0be354.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95874502-3b29e900-0d71-11eb-8377-97c59cab0558.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
