### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnPostItemAfterGetSKU

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9335]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks, standard publisher `OnBeforePostItem`, can not be used, because standard code changes `SKUExists` boolean variable . Having event in procedure `PostItem` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/95875491-bd6adb00-0d7a-11eb-81e9-83708fb54764.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostItemAfterGetSKU(var SKUExists: Boolean; var ItemJnlLine: Record "Item Journal Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
