### ISSUE TITLE
[Event Request] Table 7002 "Sales Price" - OnValidateItemNoOnBefore

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9342]
We are migrating our code from NAV 2018 to BC16.4. In the Table 7002 "Sales Price", in the field 1 "Item No.", in the trigger OnValidate, we need to add our code at numerous places. To do so, the easier should be to add a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95881091-7f6cb780-0d78-11eb-91bf-97aeed815614.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95881062-7380f580-0d78-11eb-874a-589c00cec80e.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
