### ISSUE TITLE
[Event Request] Table 110 "Sales Shipment Header" -  OnBeforeStartTrackingSite

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9343]
We are migrating our code from NAV 2018 to BC16.4. In the Table 110 "Sales Shipment  Header", in the procedure StartTrackingSite, we need to add our code at the beginning of the procedure. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95883819-a2e53180-0d7b-11eb-9fe1-7ce01cb24acd.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95883733-8e089e00-0d7b-11eb-87c0-15d14c5d9ef7.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
