### ISSUE TITLE
[Event Request] codeunit "Job Link Usage" - OnAfterMatchUsageSpecified event-request

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#9344]
![image](https://user-images.githubusercontent.com/35260264/95896427-7f76b280-0d8c-11eb-9caf-d9b4c57316e7.png)

![image](https://user-images.githubusercontent.com/35260264/95896462-8a314780-0d8c-11eb-8c9f-0a2caa146e37.png)

And

![image](https://user-images.githubusercontent.com/35260264/95896693-f0b66580-0d8c-11eb-9997-ce8ec2b494c6.png)
![image](https://user-images.githubusercontent.com/35260264/95896706-f613b000-0d8c-11eb-835b-55f385ef1100.png)

The reason for the event request, is that after posting in job ledger entry, i want to set "qty to transfer to journal" so something else than remaning qty.

i dont need them both, but they are both nice to have.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
