### ISSUE TITLE
[Event Request] Table Service Contract Line

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#9346]
We need the sender in these events:

OnAfterCalculateNextServiceVisit
OnBeforeCheckServContractHeader
OnValidateServiceItemNoOnBeforeModify

Can you modify these to include the sender?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
