### ISSUE TITLE
[Event Request] Codeunit CopyDocument Mgt.

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#9347]
This was already requested in #2637

> current: OnAfterCopyPurchaseHeader(ToPurchHeader,OldPurchHeader)
> desired: OnAfterCopyPurchaseHeader(VAR ToPurchHeader,OldPurchHeader,FromPurchHeader)

Unfortunately, the event `OnAfterCopyPurchaseHeader` was never updated.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
