### ISSUE TITLE
[External] Table 5902 "Service Line"

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#9348]
Please make these global variables protected:

```
ServHeader: Record "Service Header";
TempTrackingSpecification: Record "Tracking Specification" temporary;
```

(I recreated this request as advised in https://github.com/microsoft/ALAppExtensions/issues/8135#issuecomment-708340111)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
