### ISSUE TITLE
[Event Request] Page 233 OnFindFindApplyingEntryOnAfterVendLedgEntrySetFilters

### ISSUE THREAD

**Issue by bstanienda** [microsoft/ALAppExtensions#9349]
Dear Team,

we need an event/publisher in page 233 OnFindFindApplyingEntryOnAfterVendLedgEntrySetFilters as in page 232.

Code in page 232 in local procedure FindApplyingEntry()
            CustLedgEntry.SetCurrentKey("Customer No.", "Applies-to ID", Open);
            CustLedgEntry.SetRange("Customer No.", "Customer No.");
            CustLedgEntry.SetRange("Applies-to ID", CustEntryApplID);
            CustLedgEntry.SetRange(Open, true);
            CustLedgEntry.SetRange("Applying Entry", true);
            OnFindFindApplyingEntryOnAfterCustLedgEntrySetFilters(Rec, CustLedgEntry);   --> This event
            if CustLedgEntry.FindFirst then begin
                CustLedgEntry.CalcFields(Amount, "Remaining Amount");

    [IntegrationEvent(false, false)]
    local procedure OnFindFindApplyingEntryOnAfterCustLedgEntrySetFilters(ApplyingCustLedgerEntry: Record "Cust. Ledger 
                              Entry"; var CustLedgerEntry: Record "Cust. Ledger Entry")

Please add the event/publisher in page 233 as in page 232. Thank you!

Kind regards,
Bianca Stanienda

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
