### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnGenVouchGenJnlLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9350]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks . Having event in procedure `OnRun` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95988566-bd79e200-0e31-11eb-8826-b51065ba5470.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesHeaderInvoice(var SalesHeader: Record "Sales Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
