### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnAfterSetProperties

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9351]
Hi team,

In Codeunit 6620 Copy Document Mgt. procedure `SetProperties` we woud like to run some custom code, for that an event at end of procedure code would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/95989442-f4042c80-0e32-11eb-88d9-5663e212e9d5.png)
```
[IntegrationEvent(false, false)]
local procedure OnAfterSetProperties(var IncludeHeader: Boolean; var RecalculateLines: Boolean; var MoveNegLines: Boolean; var CreateToHeader: Boolean; var HideDialog: Boolean; var ExactCostRevMandatory: Boolean; var ApplyFully: Boolean)
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
