### ISSUE TITLE
[Event Request] Table 5077  "Segment Line" - OnValidateInteractionTemplateCodeOnAfterCaseTrue

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9352]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5077 "Segment Line", in the field 7 "Interaction Template Code", in the trigger OnValidate, we need to add our code in the "case true of". To do so, we need a IsHandled flag and an event publisher juste before the "case true of", like this :

![image](https://user-images.githubusercontent.com/34645582/95989330-691f3400-0e2a-11eb-9ce3-377835c0837a.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95989108-20677b00-0e2a-11eb-88ce-397c6d1f337b.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
