### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeCheckShippingAdvice

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9353]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks and avoid using standard code. Having event in procedure `CheckAndUpdate` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95992351-8823c300-0e36-11eb-8905-131612e4005d.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckShippingAdvice(SalesHeader: Record "Sales Header"; WhseShip: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
