### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeCheckICPartnerBlocked

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9354]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks. Having event in procedure `CheckAndUpdate` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95993509-e0a79000-0e37-11eb-86d8-2141f98647ac.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckICPartnerBlocked(SalesHeader: Record "Sales Header"; PreviewMode: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
