### ISSUE TITLE
[Event Request] Page 233 OnSetVendApplIdAfterCheckAgainstApplnCurrency

### ISSUE THREAD

**Issue by bstanienda** [microsoft/ALAppExtensions#9355]
Dear Team,

we need a new event/publisher in page 233 OnSetCustApplIdAfterCheckAgainstApplnCurrency as in page 232.

Code in Page 232 in function SetCustApplId
...
        if ApplyingCustLedgEntry."Entry No." <> 0 then
            GenJnlApply.CheckAgainstApplnCurrency(
              ApplnCurrencyCode, "Currency Code", GenJnlLine."Account Type"::Customer, true);

        OnSetCustApplIdAfterCheckAgainstApplnCurrency(Rec, CalcType, GenJnlLine);
        CustLedgEntry.Copy(Rec);
...

    [IntegrationEvent(false, false)]
    local procedure OnSetCustApplIdAfterCheckAgainstApplnCurrency(var CustLedgerEntry: Record "Cust. Ledger Entry"; 
                                    CalcType: Option; GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

Please create this event/publisher as in page 232. Thank you!

Kind regards,
Bianca Stanienda

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
