### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnPostItemJnlLineSetControls

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9356]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks. Having event in procedure `PostItemJnlLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/95993953-63304f80-0e38-11eb-8c1d-b1bb88f0c971.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineSetControls(ItemJnlLine: Record "Item Journal Line"; SalesHeader: Record "Sales Header"; WhseShip: Boolean; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
