### ISSUE TITLE
[Event Request] Table 5965 "Service Contract Header" - OnValidateNextInvoicePeriodOnBeforeCalcContractAmount

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9357]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5965 "Service Contract Header", in the procedure ValidateNextInvoicePeriod, we need to replace the last two standard code lines in the last "else" by our own. . To do so, we need a a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/95996156-a687bf80-0e32-11eb-9051-c2952e886531.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/95996108-97a10d00-0e32-11eb-8a2a-822723faea4b.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
