### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnUpdateStatisticLegder / OnUpdateStatisticLegder2

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9358]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks. Having event in procedure `FillInvoicePostingBuffer` would be a perfect solution :

Created two identical events, because I do not think that it is in your policy to create same event and use it twice in a different place of code, if not, feel free to correct me.

![image](https://user-images.githubusercontent.com/70525691/96001759-0edd9d80-0e41-11eb-9cf4-dffdadc064d9.png)

![image](https://user-images.githubusercontent.com/70525691/96001772-143ae800-0e41-11eb-9d34-6ce29686e9ee.png)

    [IntegrationEvent(false, false)]
    local procedure OnUpdateStatisticLegder(TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line")
    [IntegrationEvent(false, false)]
    local procedure OnUpdateStatisticLegder2(TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
