### ISSUE TITLE
[Event Request] Table 5900 "Service Header" - OnInsertOnBeforeServShptHeaderSetRange

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9359]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5090 "Service Header", in the trigger OnInsert, we need to add a condition at a specific moment. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96001396-44ca5400-0e38-11eb-865a-1faec562ef3a.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96001330-32501a80-0e38-11eb-9b9d-2255147228ec.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
