### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeSetSalesLineQty

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9360]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks. Having event in procedure `SumSalesLines2` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96002899-53b60400-0e42-11eb-9804-09dfae71cb78.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetSalesLineQty(SalesLine: Record "Sales Line"; var SalesLineQty: Decimal; QtyType: Option General,Invoicing,Shipping; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
