### ISSUE TITLE
[Event Request] Codeunit 5063 ArchiveManagement - OnRestoreSalesLinesOnAfterFilterSalesLineArchive

### ISSUE THREAD

**Issue by DainiusJankevicius** [microsoft/ALAppExtensions#9361]
Hi team,

In Codeunit 5063 ArchiveManagement procedure `RestoreSalesLines` we would like to add some custom filters before running code, for that an event before `SalesLineArchive.FindSet` would be a good solution:
![image](https://user-images.githubusercontent.com/49302698/96003032-7a743a80-0e42-11eb-8de6-b41926ee9a97.png)
```
[IntegrationEvent(false, false)]
local procedure OnRestoreSalesLinesOnAfterFilterSalesLineArchive(var SalesLineArchive: Record "Sales Line Archive"; var SalesHeaderArchive: Record "Sales Header Archive"; SalesHeader: Record "Sales Header")
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
