### ISSUE TITLE
[Event Request] Table 5902 "Service Line" - OnBeforeUpdateLineDiscPct

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9362]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5902 "Service Line", in the procedure UpdateLineDiscPct, we need to modify the standard code by adding conditions in the first "if" . To do so, we need a a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96006810-26675700-0e3e-11eb-86b4-cd928613790d.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96006844-3121ec00-0e3e-11eb-9dcd-8550f254a4e8.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
