### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" procedure RetrieveLookupData

### ISSUE THREAD

**Issue by abhishekv290691** [microsoft/ALAppExtensions#9363]
We would like the following events in the codeunit 6501 "Item Tracking Data Collection" to enable filtering of record variables.

1. "**OnBeforeReserveEntryFindSetOnRetrieveLookupData**" in the procedure"RetrieveLookupData":

![image](https://user-images.githubusercontent.com/49511747/96079931-b15d5580-0f01-11eb-9d3a-55d70ee2d5d4.png)
![image](https://user-images.githubusercontent.com/49511747/96080200-46f8e500-0f02-11eb-87f5-7d8cd821c2de.png)

2.  "**OnBeforeTempGlobalEntrySummaryFind**" in the procedure "CreateEntrySummary2"
![image](https://user-images.githubusercontent.com/49511747/96081249-a5bf5e00-0f04-11eb-8837-3096225e12fb.png)
![image](https://user-images.githubusercontent.com/49511747/96081689-9bea2a80-0f05-11eb-8df2-3033c7d1d2ca.png)

3. "**OnAfterMaxDoubleEntryAdjustQty**"  in the procedure "CreateEntrySummary2"
![image](https://user-images.githubusercontent.com/49511747/96081765-be7c4380-0f05-11eb-9f2b-297bc22b70fd.png)
![image](https://user-images.githubusercontent.com/49511747/96081802-ce942300-0f05-11eb-93ea-4a4611cf64fc.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
