### ISSUE TITLE
[Event request] Two events in CU391

### ISSUE THREAD

**Issue by giann85** [Microsoft/ALAppExtensions#937]
Hi team, please i need to add  two events in Codeunit 391 : 

OnBeforeTransferShipmentModify(TransferShptHeader,Rec)    in   ModifyTransferShipment function, and

OnBeforeReturnShipmentModify(ReturnShptHeader,Rec) in ModifyReturnShipment function.

Thanks

**Comment by AlexanderYakunin** [comment]
I assume this is for IT version, already done.
