### ISSUE TITLE
[Event Request] Table 336 "Tracking Specification" - OnBeforeCheckItemTrackingQuantity

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9377]
We are migrating our code from NAV 2018 to BC16.4. In the Table 336 "Tracking Specification", in the procedure CheckItemTrackingQuantity, we would like to englobe the procedure in a repeat pattern. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96103034-7cd4a400-0ed7-11eb-8773-b886ca426c52.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96105791-b955cf00-0eda-11eb-82bb-b07b622bbcff.png)

To really do so, we also need the procedure CheckItemTrackingByType to become a global procedure, and not a local procedure, to be able to call it from an event subscriber (we asked for it here https://github.com/microsoft/ALAppExtensions/issues/9378).

Do you think it could be possible ?

Thank you for your work.

**Comment by AlexanderYakunin** [comment]
Yes, making procedure as global possible for Master. Not sure I understand why you want to have all parameters in event as VAR?  Are you going to change DocumentType and DocumentNo here? But you can call this procedure for needed documents without this? Please confirm.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by Magicrevette** [comment]
@AlexanderYakunin Indeed, I don't need all these parameters as VAR. It was a reflex when I wrote it. The parameters I need to be VAR are Rec, Handle, Invoice and IsHandled.
