### ISSUE TITLE
[Global procedure] Table 336 "Tracking Specification" - CheckItemTrackingByType

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9378]
We are migrating our code from NAV 2018 to BC16.4. In NAV 2018, we used to use the procedure CheckItemTrackingQuantity in a "repeat-until" pattern (we asked a IsHandled flag and an event publisher to do so here https://github.com/microsoft/ALAppExtensions/issues/9377). To do so in BC, we need to be able to call this procedure CheckItemTrackingByType from an event subscriber, so to have this procedure be a global one, and not a local procedure anymore.

Do you think it is possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
