### ISSUE TITLE
[Event Request] Table 336 "Tracking Specification" - OnCheckItemTrackingByTypeOnBeforeIfHandle

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9381]
We are migrating our code from NAV 2018 to BC16.4. In the Table 336 "Tracking Specification", in the procedure CheckItemTrackingByType, we would like to englobe the procedure in a repeat pattern. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96106057-06d23c00-0edb-11eb-913c-05d97a59a811.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96106295-57e23000-0edb-11eb-977e-8cdc4af5365a.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
