### ISSUE TITLE
Generated resource URLs for API pages can be inconsistent

### ISSUE THREAD

**Issue by charlespockert** [microsoft/ALAppExtensions#9384]
Not sure if this is the best place for this - but it relates to creating custom APIs which is an extension so maybe?

If you create a custom API page and use a capital letter for the `EntitySetName`, the generated resource URLs are inconsistent.

```
page 50000 "Some API"
{
    PageType = API;
    EntityName = 'SomeEntity';
    EntitySetName = 'SomeEntities';
```
e.g. when accessing the resource with a company in the querystring

`../api/mypublisher/mygroup/v1.0/someEntities?company=My Company` is valid, but
`../api/mypublisher/mygroup/v1.0/SomeEntities?company=My Company` is not

The opposite is true when accessing via the company resource:

`../api/mypublisher/mygroup/v1.0/companies(000000-abcdef-etc)/someEntities` is **not** valid, but
`../api/mypublisher/mygroup/v1.0/companies(000000-abcdef-etc)/SomeEntities` is

I'd expect both of them to follow the same casing conventions, given that we have case sensitive URLs, or as a worst case, for code-cop to complain about using a capital first letter in the entity set name.

You can't pass querystring params to the subscription API when trying to subscribe to webhooks, so having this inconsistency caused a bit of head-scratching..

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
