### ISSUE TITLE
[New Event Parameter] Table 5740 "Transfer Header" - OnBeforeValidateTransferFromCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9386]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5740 "Transfer Header", in the field 2 "Transfer-from Code", in trigger OnValidate, we would like to use the event publisher OnBeforeValidateTransferFromCode(), but it lacks a parameter we would liek to use : HideValidationDialog. Is It possible to add it to this already existing events, like this :

![image](https://user-images.githubusercontent.com/34645582/96111013-eefdb680-0ee0-11eb-9230-1a3c761ccfc9.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96110962-e1e0c780-0ee0-11eb-918a-88361bcc1f55.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
