### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnAfterInsertReturnReceiptLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9389]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks. Having event in procedure `PostSalesLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96112906-068e6c80-0eec-11eb-953f-f6f0f2010b73.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertReturnReceiptLine(var SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var xSalesLine: Record "Sales Line"; ReturnRcptHeader: Record "Return Receipt Header"; RoundingLineInserted: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
