### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnPostCustomerEntryBeforeUpdateSalesHeader

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9395]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks. Having event with handling in procedure `PostGLAndCustomer` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96114247-0b542000-0eee-11eb-8659-e2fa3a51197a.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostCustomerEntryBeforeUpdateSalesHeader(SalesHeader: Record "Sales Header"; var IsHandled: Boolean)

**Comment by StanPesotskiy** [comment]
Can't you use the existing event OnBeforeUpdateSalesHeader()?
