### ISSUE TITLE
[Event Request] Table 32/37/39/246/5902 - OnAfterFilterLinesWithItemToPlan

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#940]
Dear AL team,

Through this issue we would like to request the following event-publisher to be added in multiple tables, being table 32 Item Ledger Entry, table 37 Sales Line, table 39 Purchase Line, table 246 Requisition Line and table 5902 Service Line.
Here is an example of the signature for table 32:
```
OnAfterFilterLinesWithItemToPlan(VAR ItemLedgEntry : Record "Item Ledger Entry";VAR Item : Record Item; NetChange : Boolean)
```

Here is another example of the signature for table 37:
```
OnAfterFilterLinesWithItemToPlan(VAR SalesLine : Record "Sales Line";VAR Item : Record Item; DocumentType : Option)
```

In other words, including the current record, the item record, and additional parameters (NetChange, DocumentType) that are passed to the `FilterLinesWithItemToPlan` procedure.

Which would be called at the end of the `FilterLinesWithItemToPlan` procedures, as shown below for table 32:
```
[External] FilterLinesWithItemToPlan(VAR Item : Record Item;NetChange : Boolean)
RESET;
SETCURRENTKEY("Item No.",Open,"Variant Code",Positive,"Location Code","Posting Date");
SETRANGE("Item No.",Item."No.");
SETRANGE(Open,TRUE);
SETFILTER("Variant Code",Item.GETFILTER("Variant Filter"));
SETFILTER("Location Code",Item.GETFILTER("Location Filter"));
SETFILTER("Global Dimension 1 Code",Item.GETFILTER("Global Dimension 1 Filter"));
SETFILTER("Global Dimension 2 Code",Item.GETFILTER("Global Dimension 2 Filter"));
IF NetChange THEN
  SETFILTER("Posting Date",Item.GETFILTER("Date Filter"));
OnAfterFilterLinesWithItemToPlan(Rec, Item, NetChange); // <- Call to new event
```

Allowing for additional filters to be applied for other fields.

**Comment by NKarolak** [comment]
At least for table 32 (that's where I now need this event too), the event publisher has been already added to the "BC Insider" - though the labels of this Issue do not tell so, @JesperSchulz   ;-)

**Comment by sboeve** [comment]
I too need this event in Table 32.  Thanks!
