### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeCreateServItemOnSalesLineShpt

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9405]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks, standard publisher `OnInvoiceSalesShptLine` can not suit our needs, because it is called in two places, plus additional params would be required . Having event with handler in procedure `InsertShipmentLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96118652-799be100-0ef4-11eb-9979-37d2e6983793.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateServItemOnSalesLineShpt(var SalesHeader: Record "Sales Header"; var SalesShipmentLine: Record "Sales Shipment Line"; SalesShptHeader: Record "Sales Shipment Header"; xSalesLine: Record "Sales Line"; var IsHandled: Boolean)

**Comment by StanPesotskiy** [comment]
Is it possible to use the existing event OnBeforeCreateServItemOnSalesLineShpt of codeunit codeunit 5920 ServItemManagement?

**Comment by AlexanderYakunin** [comment]
I'm closing this request as no response have bene provided for 4 weeks. I assume you can use suggestion. If not please create new request.
