### ISSUE TITLE
[Additional Parameter Request] Codeunit 90 Purch.-Post - OnPostPurchLineOnBeforeInsertReturnShipmentLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9409]
Hi Team,

In codeunit 90 we need possibility to have additional checks in the procedure `PostPurchLine`. Standard publisher `OnPostPurchLineOnBeforeInsertReturnShipmentLine` would suit us if it had additional parameters:

1. `Purchaseheader` is set to pass by reference
2. `ReturnShptHeader: Record "Return Shipment Header"`
3. `TempPurchLineGlobal: Record "Purchase Line"`
4. `RoundingLineInserted: Boolean`

![image](https://user-images.githubusercontent.com/70525691/96122561-55db9980-0efa-11eb-8caa-c5f7ab539188.png)

    [IntegrationEvent(false, false)]
    local procedure OnPostPurchLineOnBeforeInsertReturnShipmentLine(var PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; ReturnShptHeader: Record "Return Shipment Header"; TempPurchLineGlobal: Record "Purchase Line"; RoundingLineInserted: Boolean;var IsHandled: Boolean);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
