### ISSUE TITLE
[New Event Parameter] Table 5740 "Transfer Header" - OnValidateTransferToCodeOnAfterTestStatusOpen

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9413]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5740 "Transfer Header", in the field 11 "Transfer-to Code", in trigger OnValidate, we would like to add our own code at numerous moments of the trigger. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96128381-92f15d00-0ef5-11eb-9a35-335c90e6f589.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96128423-a1d80f80-0ef5-11eb-9268-11cea2c37b76.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
