### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnTestQtyToReceiveOnWhseRcptLine

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9422]
Hi Team,

In Codeunit 90 we need possibility to have our additional checks. Having event with handling in procedure `InsertReceiptLine` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96131558-0305e000-0f02-11eb-9569-715136155c17.png)

    [IntegrationEvent(false, false)]
    local procedure OnTestQtyToReceiveOnWhseRcptLine(var PurchRcptLine: Record "Purch. Rcpt. Line"; var WhseRcptLine: Record "Warehouse Receipt Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
