### ISSUE TITLE
[Event Request] Table 5741 "Transfer Line" - OnValidateItemNoOnAfterGetTransHeader & OnValidateItemNoOnAfterItemTestFieldBlocked

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9435]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5741 "Transfer Line", in the field 11 "Item No", in trigger OnValidate, we would like to add our own code at numerous moments of the trigger. To do so, we need two events publisher, like these :

![image](https://user-images.githubusercontent.com/34645582/96141684-8d017900-0f01-11eb-9882-fbaa66778e9e.png)

With these integration events :
![image](https://user-images.githubusercontent.com/34645582/96142030-e669a800-0f01-11eb-917a-c870ff7f06ba.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
