### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeMakeInventoryAdjustment

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9438]
Hi Team,

In Codeunit 80 we need possibility to have our additional checks. Having event in procedure `OnRun` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96143860-3483a900-0f0c-11eb-94a0-41eef6156ddc.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeMakeInventoryAdjustment(SalesHeader: Record "Sales Header"; SalesInvHeader: Record "Sales Invoice Header")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
