### ISSUE TITLE
Codeunit 31020 "Purchase-Post Advances".PostInvLineCorrection

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#9440]
Please remove LOCAL from this fucntion.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for releasee 17.
