### ISSUE TITLE
Codeunit 31020 "Purchase-Post Advances".UnPostInvCorrGL

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#9441]
Please remove LOCAL from this function.

**Comment by mazhelez** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
