### ISSUE TITLE
[Event Request] Codeunit 12 IncludeSender in IntegrationEvent OnAfterCustLedgEntryInsert()

### ISSUE THREAD

**Issue by Joneleth84** [microsoft/ALAppExtensions#9448]
Hello!

Our customers use additional entry tables / detailled tables that are filled via Gen. Jnl.-Post Line routine, concerning customer ledger entries. In order to integrate this table we would need two changes:

Firstly, a global method to increase the NextEntryNo, similar to IncrNextVATEntryNo(). This function could also be internally used by your team, e.g. in all PostDtldLedgEntries() functions.

![15-10-_2020_20-38-27](https://user-images.githubusercontent.com/56401325/96172825-3f980280-0f27-11eb-9a83-a76dd526130f.jpg)

Secondly, in order to use this function and access var NextEntryNo via GetNextEntryNo() during the posting routine, we need access to the object, therefore IncludeSender would need to be set in OnAfterCustLedgEntryInsert()

![15-10-_2020_20-40-25](https://user-images.githubusercontent.com/56401325/96172770-2ee78c80-0f27-11eb-9d2d-bec60796df96.jpg)

Thank you and best regards,
Johannes

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
