### ISSUE TITLE
[Event Request] Codeunit 7326 "Whse. Item Tracking FEFO" - OnBeforeSummarizeInventoryFEFO

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9449]
Hi Team,

In codeunit 7326, please provide **TempGlobalEntrySummary**, **StrictExpirationPosting**, **LastSummaryEntryNo** and **HasExpiredItems** parameters to **OnBeforeSummarizeInventoryFEFO** event in procedure **SummarizeInventoryFEFO**

![image](https://user-images.githubusercontent.com/57799519/95883297-6542d180-0d98-11eb-902a-bc3d1ba049ed.png)

**Actual Event:**
LOCAL [IntegrationEvent] OnBeforeSummarizeInventoryFEFO(Location : Record Location;ItemNo : Code[20];VariantCode : Code[10];HasExpirationDate : Boolean;VAR IsHandled : Boolean)

**Required Event:**
LOCAL [IntegrationEvent] OnBeforeSummarizeInventoryFEFO(VAR TempGlobalEntrySummary: Record "Entry Summary";VAR StrictExpirationPosting: Boolean;VAR LastSummaryEntryNo: Integer;VAR HasExpiredItems: Boolean;Location : Record Location;ItemNo : Code[20];VariantCode : Code[10];HasExpirationDate : Boolean;VAR IsHandled : Boolean)

_Please backport to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
