### ISSUE TITLE
[Event Request] Table 5741 "Transfer Line" - OnValidateTransferFromCodeOnBeforeCheckItemAvailable

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9450]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5741 "Transfer Line", in the field 36 "Transfer-from Code", in trigger OnValidate, we would like to add our own code at a specific moment. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96242304-9cd19980-0fa3-11eb-9c0c-4b4cf9b974f6.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96242269-917e6e00-0fa3-11eb-9de8-4c21363a8a6f.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
