### ISSUE TITLE
[Event Request] Table 5741 "Transfer Line" - OnValidateTransferToCodeOnBeforeVerifyChange

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9451]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5741 "Transfer Line", in the field 37 "Transfer-to Code", in trigger OnValidate, we would like to add our own code at a specific moment. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96243157-a1e31880-0fa4-11eb-96d9-07dd6904a4b3.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96243184-a9a2bd00-0fa4-11eb-9667-e5068a6ff995.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
