### ISSUE TITLE
[Event Request] Table 5742 "Transfer Route" - OnBeforeInTransitCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9452]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5742 "Transfer Route", in the procedure GetTransferRoute, we would like to modify what is in the "else statement". To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96248171-70ba1680-0fab-11eb-920f-8bc599501586.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96248212-7dd70580-0fab-11eb-89f5-1cb5e56b5f31.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
