### ISSUE TITLE
[Bug] Renaming Item Attributes

### ISSUE THREAD

**Issue by DoFroetschel** [microsoft/ALAppExtensions#9454]
Hi,
I want to report a bug in the Item Attributes. In the following screenshots I will try to describe the problem as detailed as possible.
I found this bug in BC140 OnPrem CU7 and doublechecked in the newest versions if the problem still exists. And yes, it does.
I did tests in two current versions:
DE Business Central 17.0 (Platform 17.0.17020.17501 + Application 17.0.17126.17680) Sandbox
W1 17.0 (Platform 17.0.17020.17674 + Application 17.0.17126.17712) Sandbox
Step by step screenshots:
Open any item
 
![grafik](https://user-images.githubusercontent.com/44831089/96253295-a4993a00-0fb3-11eb-9120-18a8b2b2dd9c.png)

Open item attributes
 
![grafik](https://user-images.githubusercontent.com/44831089/96253311-abc04800-0fb3-11eb-89b1-33863de07719.png)

 
![grafik](https://user-images.githubusercontent.com/44831089/96253331-b2e75600-0fb3-11eb-8656-a094b9664466.png)

Rename any item attribute 
 
![grafik](https://user-images.githubusercontent.com/44831089/96254222-39e8fe00-0fb5-11eb-9fa7-f742ada1fbc7.png)

Accept renaming
 
![grafik](https://user-images.githubusercontent.com/44831089/96254233-3e151b80-0fb5-11eb-8f4b-39f7bed7ef75.png)

Now I changed "Höhe" into "Modelljahr"
 
![grafik](https://user-images.githubusercontent.com/44831089/96254248-41a8a280-0fb5-11eb-8b82-911eab532be8.png)

Then close the Page and open the item attributes again
 
![grafik](https://user-images.githubusercontent.com/44831089/96254260-479e8380-0fb5-11eb-9b9a-a2fa05c4d0be.png)

As you can see, both attributes are showing up again even though I renamed one in the page.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
