### ISSUE TITLE
[Visibility Request] Page 11309 General Ledger Entries - Update Requested

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#9455]
Hello,

Regarding: https://github.com/microsoft/ALAppExtensions/issues/7636

Can you tell me when this will be in? It's still not in CU5.
For now this is a serious issue for our application.

Thanks

**Comment by StanPesotskiy** [comment]
This change is available in version 17.0 and was not included into updates for version 16.
