### ISSUE TITLE
Codeunit 12104 - LocalApplicationManagement: change scope to procedure CheckDigit

### ISSUE THREAD

**Issue by demiliani** [microsoft/ALAppExtensions#9456]
Dynamics 365 Business Central IT Localization.
To validate the "Fiscal Code"field, the Base App does the following:
trigger OnValidate()
            var
                LocalAppMgt: Codeunit LocalApplicationManagement;
            begin            
                if "Fiscal Code" <> '' then
                    LocalAppMgt.CheckDigit("Fiscal Code");
            end;

But the CheckDigit procedure declared in the LocalApplicationManagement codeunit has the OnPrem scope:
![CheckDigit](https://user-images.githubusercontent.com/33155438/96262043-86d2d180-0fc1-11eb-8cb8-7af4c289c016.jpg)

and we cannot use the validation in SaaS extension. Can you please change the scope to be available also for SaaS?
Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
