### ISSUE TITLE
IT Localization: codeunit 12101 "Withholding - Contribution": change scope to PostPayments procedure

### ISSUE THREAD

**Issue by demiliani** [microsoft/ALAppExtensions#9457]
Dynamics 365 Business Central IT localization.
Codeunit 12101 "Withholding - Contribution" has the PostPayments procedure with Scope('OnPrem'):
![PostPayments](https://user-images.githubusercontent.com/33155438/96262720-7bcc7100-0fc2-11eb-815b-ec462869882a.jpg)

Can you please change the scope in order to use the method also for SaaS?
Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
