### ISSUE TITLE
[Event Request] Table 5742 "Transfer Route" - OnBeforeCalcShipmentDate

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9458]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5742 "Transfer Route", in the procedure CalcShipmentDate, we would like to add our code at the beginning of the procedure and a condition to the final "else" statement. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96261491-d06eec80-0fc0-11eb-946f-662d437d303d.png)

    OnBeforeCalcShipmentDate(Rec, ReceiptDate, InboundWhseTime, TransferToCode, ShippingAgentCode, ShippingAgentServiceCode, ShippingTime, TransferFromCode, ShipmentDate, OutboundWhseTime, IsHandled);

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96261527-db298180-0fc0-11eb-8645-ba173b44c91b.png)

    local procedure OnBeforeCalcShipmentDate(var TransferRoute: Record "Transfer Route"; 
    var ReceiptDate: Date; 
    var InboundWhseTime: DateFormula;
    var TransferToCode: Code[10];
    var ShippingAgentCode: Code[10];
    var ShippingAgentServiceCode: Code[10];
    var ShippingTime: DateFormula;
    var TransferFromCode: Code[10];
    var ShipmentDate: Date;
    var OutboundWhseTime: DateFormula;
    var IsHandled: Boolean)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
