### ISSUE TITLE
[Event Request] Codeunit 5940 ServContractManagement - CreateServiceLedgerEntry

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#9459]
I would like to be able to control the DataExpression that is parsed to the CalcDate function. For that I would like to request the following publisher, and slight code modification in function CreateServiceLedgerEntry:

            if ServContractLine.Find('-') then begin
                repeat
                    YearContractCorrection := false;
                    Days := 0;
                    WDate := CalcDate('<-CM>', InvFrom);
                    // ####### START >>
                    DateExpression := '<1M>';
                    OnCreateServiceLedgerEntryOnBeforeLoopPeriods(ServContractHeader, ServContractLine, InvFrom, VAR WDate, VAR DateExpression);
                    // ####### >> END
                    if (InvFrom <= ServContractLine."Contract Expiration Date") or
                       (ServContractLine."Contract Expiration Date" = 0D)
                    then begin
                        NoOfPayments := 0;
                        repeat
                            NoOfPayments := NoOfPayments + 1;
                            // ####### START >>
                            //WDate := CalcDate('<1M>', WDate); >> old code
                            WDate := CalcDate(DateExpression, WDate);
                            // ####### << END
                        until (WDate >= InvTo) or
                              ((WDate > ServContractLine."Contract Expiration Date") and
                               (ServContractLine."Contract Expiration Date" <> 0D));
                        CountOfEntryLoop := NoOfPayments;

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
