### ISSUE TITLE
[Event Request] Codeunit 5940 ServContractManagement - CreateServHeader

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#9460]
We would like to control the Contract Invoice Nos series however with the existing trigger it is kind of possible however we would still need to fill the Contract Invoice Nos in service mgt. setup, and the no series should be set up as manual nos. Which is not really the way it should be.

Therefore we would like to request a small modification to the existing publisher OnCreateServHeaderOnBeforeInitSeries. It would be enough if ServMgtSetup is parsed as a VAR parameter, and even better if the testfield of "Contract Invoice Nos." is moved after the publisher. Like the example below.

Also we need the Service Contract Header as a new parameter.

        ServMgtSetup.Get();
        // #### START >>
        //ServMgtSetup.TestField("Contract Invoice Nos.");
        //OnCreateServHeaderOnBeforeInitSeries(VAR ServHeader2, ServMgtSetup);
        OnCreateServHeaderOnBeforeInitSeries(VAR ServHeader2, VAR ServMgtSetup, ServContract2);
        ServMgtSetup.TestField("Contract Invoice Nos.");
        // #### << END
        NoSeriesMgt.InitSeries(
          ServMgtSetup."Contract Invoice Nos.", '',
          PostDate, ServHeader2."No.", ServHeader2."No. Series");
        InsertServiceHeader(ServHeader2, ServContract2);
        ServInvNo := ServHeader2."No.";

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
