### ISSUE TITLE
[Event Request] Codeunit 5940 ServContractManagement - ServLedgEntryToServiceLine

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#9461]
We would like to request to additional parameters InvFrom and InvTo to the existing publisher OnServLedgEntryToServiceLineOnBeforeServLineInsert. 

            "Shortcut Dimension 1 Code" := ServiceLedgerEntry."Global Dimension 1 Code";
            "Shortcut Dimension 2 Code" := ServiceLedgerEntry."Global Dimension 2 Code";
            "Dimension Set ID" := ServiceLedgerEntry."Dimension Set ID";

            IsHandled := false;
            // ##### START >>
            //OnServLedgEntryToServiceLineOnBeforeServLineInsert(ServLine, TotalServLine, TotalServLineLCY, ServHeader, ServLedgEntry, ServiceLedgerEntry, IsHandled);
            OnServLedgEntryToServiceLineOnBeforeServLineInsert(ServLine, TotalServLine, TotalServLineLCY, ServHeader, ServLedgEntry, ServiceLedgerEntry, IsHandled, InvFrom, InvTo);
            // ##### END <<
            if IsHandled then
                exit;

            Insert;
            CreateDim(
              DimMgt.TypeToTableID5(Type.AsInteger()), "No.",
              DATABASE::Job, "Job No.",
              DATABASE::"Responsibility Center", "Responsibility Center");

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
