### ISSUE TITLE
[Event Request] Codeunit 5940 ServContractManagement - CreateDetailedServLine

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#9462]
We would like to request an additional parameter ServContractHeader to the publisher OnCreateDetailedServLineOnAfterSetFirstLineAndNewContract:

        ServLineNo := 0;
        ServLine.SetRange("Document Type", ServLine."Document Type"::Invoice);
        ServLine.SetRange("Document No.", ServHeader."No.");
        if ServLine.FindLast then begin
            ServLineNo := ServLine."Line No.";
            NewContract := ServLine."Contract No." <> ServContractHeader."Contract No.";
            ServLine.Init();
        end else begin
            FirstLine := true;
            NewContract := true;
        end;

        // ####### START >>
        //OnCreateDetailedServLineOnAfterSetFirstLineAndNewContract(FirstLine, NewContract);
        OnCreateDetailedServLineOnAfterSetFirstLineAndNewContract(FirstLine, NewContract, ServContractHeader);
        // ####### END <<

        Cust.Get(ServContractHeader."Bill-to Customer No.");
        ServLine.Reset();

        if FirstLine or NewContract then
            ServMgtSetup.Get();

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
