### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - CreateDetailedServLine

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#9463]
We would like to request an additional publisher in function CreateDetailedServLine.

                      Format(StrLen(TempServLineDescription) - MaxStrLen(ServLine.Description)));
                ServLine.Description := CopyStr(TempServLineDescription, 1, MaxStrLen(ServLine.Description));
            end else
                ServLine.Description := StrSubstNo(Text002, ServContractHeader."Contract No.");
            OnCreateDetailedServLineOnBeforeServLineInsertNewContract(ServLine, ServContractHeader);
            ServLine.Insert();
        end;

        // ########## START >>
        OnCreateDetailedServLineOnBeforeCreateDescriptionServiceLines(ServContractHeader, ServContractLine, ServHeader);
        // ########## END <<

        CreateDescriptionServiceLines(ServContractLine."Service Item No.", ServContractLine.Description, ServContractLine."Serial No.");
    end;

Many thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
