### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - CreateAllCreditLines

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#9464]
We would like to request an additional publisher in function CreateAllCreditLines so we can overrule the value of the OldWDate variable:

            OldWDate := CalcDate('<CM>', WDate);
            if Days <> 1 then
                Days := 1
            else begin
                for i := 1 to InvPeriod do
                    OldWDate := CalcDate('<CM>', OldWDate) + 1;
                OldWDate := OldWDate - 1;
            end;

            // ##### START >>
            OnCreateAllCreditLinesOnAfterDetermineOldWDate(ServContract, InvPeriod, Days, WDate, VAR OldWDate);
            // ##### END <<

            if OldWDate >= PeriodStarts then begin
                if WDate < PeriodStarts then
                    WDate := PeriodStarts;
                if OldWDate > PeriodEnds then

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
