### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - InsertMultipleServLedgEntries

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#9465]
We would like to request an handled pattern to an already existing publisher and add an additional parameter. We sometimes need to stop the creation of service ledger entries before the loop ends.

            ServLedgEntry."Entry No." := NextEntry;
            UpdateServLedgEntryAmount(ServLedgEntry, ServHeader);
            ServLedgEntry."Posting Date" := DueDate;
            ServLedgEntry.Prepaid := true;
            // ###### START >>
            //OnInsertMultipleServLedgEntriesOnBeforeServLedgEntryInsert(ServLedgEntry, ServContractHeader, ServContractLine);
            OnInsertMultipleServLedgEntriesOnBeforeServLedgEntryInsert(ServLedgEntry, ServContractHeader, ServContractLine, NonDistrAmount, VAR IsHandled);
            IF IsHandled THEN
              EXIT;
            // ###### END <<
            ServLedgEntry.Insert();
            NextEntry += 1;
            DueDate := CalcDate('<1M>', DueDate);

Many thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
