### ISSUE TITLE
[Event Request] - Codeunit 12 - GetCurrencyExchRate

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/ALAppExtensions#9467]
In Hungary, we have to work with a special currency factor in case of VAT posting with additional currency. So, we would like to request a new integration event in codeunit 12 to manage a special way of the calculation of currency factor.

Please add a following piece of code at the beginning of the procedure GetCurrencyExchangeRate.

![image](https://user-images.githubusercontent.com/43200526/96447468-3aca9b80-1212-11eb-8a81-ebf23445e105.png)

        IsHandled := FALSE;
        OnBeforeGetCurrencyExchRate(GenJnlLine,AddCurrencyCode,UseCurrFactorOnly,CurrencyDate,CurrencyFactor,IsHandled);
        if IsHandled then
            exit;

And also please a new integration event to that codeunit.

![image](https://user-images.githubusercontent.com/43200526/96447657-88df9f00-1212-11eb-8f53-777161da0164.png)

    [IntegrationEvent(true, false)]
    local procedure OnBeforeGetCurrencyExchRate(VAR GenJournalLine: Record "Gen. Journal Line";
                                                VAR AddCurrencyCode: Code[10];
                                                VAR UseCurrFactorOnly: Boolean;
                                                VAR CurrencyDate: Date;
                                                VAR CurrencyFactor: Decimal;
                                                VAR IsHandled: Boolean)
    begin

    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
