### ISSUE TITLE
[Event Request][Request for External] Codeunit 99000845 Reservation Management - CalcReservedQtyOnPick

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9468]
Hi team,

In codeunit 99000845 procedure `CallCalcReservedQtyOnPick` we have a custom publisher in which if statements are correct, we would like to run standard procedure `CalcReservedQtyOnPick`, at this moment it is local so we are calling it after publisher passes `boolean type variable` as true. Could you please `expose CalcReservedQtyOnPick and CallCalcReservedQtyOnPick procedures globally`, so we could run the procedure in the publisher with `IncludeSender` and if not can you, please, add ability to call that procedure as shown in example below? :

![image](https://user-images.githubusercontent.com/70525691/96449519-a2d2af00-121d-11eb-8384-5ca2be582b8b.png)

The custom variable `DoCallCalcReservedQtyOnPick` allows us to run the procedure if needed and variable `IsHandled` helps to block using standard/custom code. 

If procedure will be exposed globally, we could modify the code to use only `IsHandled` variable, all needed procedures could be run inside the subscriber.

IntegrationEvent itself:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeCallCalcReservedQtyOnPick(var ReservEntry: Record "Reservation Entry"; var IsHandled: Boolean; var DoCallCalcReservedQtyOnPick: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
