### ISSUE TITLE
[Event Request] - Report 208 "Sales - Shipment" OnAfterOnPreReport() - Event

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/ALAppExtensions#9469]
Hello,

for our customer we need the possibility to set the parameters of the RequestPage constantly in certain automatisms.
 
In the concrete case the report "Sales - Shipment" should be sent as an attachment to an e-mail (Post and Send - button in the sales header) with the serial and lot number.

Because "Report.SaveAsPdf" is called instead of "Report.SaveAs(Report:: "Sales - Shipment", MyParameter, ReportFormat::Pdf, OutStream)" to create the attachment, there is currently no possibility to set the RequestPage parameters constantly, since the "Last used options and filters" of the user are always used. 

Therefore I want the event OnAfterOnPreReport() to set the parameters afterwards.  

![image](https://user-images.githubusercontent.com/63199461/96465585-6907a580-1229-11eb-865c-a83c27f6ce94.png)

![image](https://user-images.githubusercontent.com/63199461/96465552-5ee5a700-1229-11eb-87eb-ec2318fd761f.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
