### ISSUE TITLE
[Additional Parameter Request] Codeunit 80 Sales-Post - OnCheckAndUpdateOnAfterSetPostingFlags

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9470]
Hi Team,

In codeunit 80 we need possibility to have additional checks in the procedure `CheckAndUpdate`. Standard publisher `OnCheckAndUpdateOnAfterSetPostingFlags` would suit us if it had additional parameter `var ModifyHeader: Boolean`:

![image](https://user-images.githubusercontent.com/70525691/96465773-02d35080-1232-11eb-950a-d11bfcd70814.png)

    [IntegrationEvent(false, false)]
    local procedure OnCheckAndUpdateOnAfterSetPostingFlags(var SalesHeader: Record "Sales Header"; var TempSalesLineGlobal: Record "Sales Line" temporary; var ModifyHeader: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
