### ISSUE TITLE
[Event Request] Table 25 "Vendor Ledger Entry" - OnBeforeVendLedgEntrySetFilter

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9471]
We are migrating our code from NAV 2018 to BC16.4. In the Table 25 "Vendor Ledger Entry", in the procedure DrillDownOnOverdueEntries, we would like to not use the three "VendLedgEntry.SetFilter" lines of standard code. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96554713-30161200-12b7-11eb-97de-9bfddef75b3c.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96554679-255b7d00-12b7-11eb-9e6a-b0da0d8c1f27.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
