### ISSUE TITLE
[Event Request] Codeunit 22 OnSplitItemJnlLineOnBeforeInsertTempTrkgSpecification

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#9473]
We need an additional Parameter in the Event OnSplitItemJnlLineOnBeforeInsertTempTrkgSpecification in codeunit 22:

old:
local procedure OnSplitItemJnlLineOnBeforeInsertTempTrkgSpecification(var TempTrackingSpecification: Record "Tracking Specification" temporary; ItemJnlLine2: Record "Item Journal Line")
new:
local procedure OnSplitItemJnlLineOnBeforeInsertTempTrkgSpecification(var TempTrackingSpecification: Record "Tracking Specification" temporary; ItemJnlLine2: Record "Item Journal Line";SignFactor: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
