### ISSUE TITLE
[Event Request] Codeunit 6500 SynchronizeWhseActivItemTrkg

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#9474]
We need a new Event OnSyncActivItemTrkgOnBeforeModifyAbsQty in codeunit 6500 in at the end of procedure SynchronizeWhseActivItemTrkg:

[External] SynchronizeWhseActivItemTrkg(WhseActivLine : Record "Warehouse Activity Line")
…
IF TempTrackingSpec.FINDSET THEN
  REPEAT
    TempTrackingSpec."Quantity (Base)" := ABS(TempTrackingSpec."Qty. to Handle (Base)");
    TempTrackingSpec."Qty. to Handle (Base)" := ABS(TempTrackingSpec."Qty. to Handle (Base)");
    TempTrackingSpec."Qty. to Invoice (Base)" := ABS(TempTrackingSpec."Qty. to Invoice (Base)");
    //+++++++++++++++++++++++++++++++++++++++++++
    OnSyncActivItemTrkgOnBeforeModifyAbsQty(VAR TempTrackingSpec);
    //-------------------------------------------
    TempTrackingSpec.MODIFY;
  UNTIL TempTrackingSpec.NEXT = 0;

RegisterNewItemTrackingLines(TempTrackingSpec);

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
