### ISSUE TITLE
[Event Request] Database::"Whse. Worksheet Line" - Function GetItem - OnAfterGetItem

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9476]
We like to request the following Event:
Object: Database::"Whse. Worksheet Line"
Function: GetItem
Publisher Event: OnAfterGetItem
Reason: To implement custom business logic
Where is the event placed:
procedure GetItem(ItemNo: Code[20]; var ItemDescription: Text[100])
    begin
        if ItemNo = '' then
            ItemDescription := ''
        else
            if ItemNo <> Item."No." then begin
                ItemDescription := '';
                if Item.Get(ItemNo) then
                    ItemDescription := Item.Description;
            end else
                ItemDescription := Item.Description;
        **OnAfterGetItem(Rec, Item)**
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterGetItem(var WhseWorksheetLine: Record "Whse. Worksheet Line"; var Item: Record Item)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
