### ISSUE TITLE
[Event Request] Database::"Whse. Worksheet Line" - Function MovementCreate - OnBeforeMovementCreate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9477]
We like to request the following Event:
Object: Database::"Whse. Worksheet Line"
Function: MovementCreate
Publisher Event: OnBeforeMovementCreate
Reason: To implement custom business logic
Where is the event placed:
procedure MovementCreate(var WhseWkshLine: Record "Whse. Worksheet Line")
    var
        CreateMovFromWhseSource: Report "Whse.-Source - Create Document";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        **OnBeforeMovementCreate(WhseWkshLine, IsHandled);
        if IsHandled then
            exit;**
        CreateMovFromWhseSource.SetWhseWkshLine(WhseWkshLine);
        CreateMovFromWhseSource.RunModal;
        CreateMovFromWhseSource.GetResultMessage(3);
        Clear(CreateMovFromWhseSource);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeMovementCreate(var WhseWkshLine: Record "Whse. Worksheet Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
