### ISSUE TITLE
[Event Request] Database::"Whse. Worksheet Line" - Function "Unit of Measure Code" -OnValidate - OnValidateUnitofMeasureCodeOnBeforeValidateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9478]
We like to request the following Event:
Object: Database::"Whse. Worksheet Line"
Function: "Unit of Measure Code" -OnValidate
Publisher Event: OnValidateUnitofMeasureCodeOnBeforeValidateQuantity
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                if "Item No." <> '' then begin
                    GetItemUnitOfMeasure;
                    "Qty. per Unit of Measure" := ItemUnitOfMeasure."Qty. per Unit of Measure";
                end else
                    "Qty. per Unit of Measure" := 1;
                "From Unit of Measure Code" := "Unit of Measure Code";
                "Qty. per From Unit of Measure" := "Qty. per Unit of Measure";
                **IsHandled := false;
                OnValidateUnitofMeasureCodeOnBeforeValidateQuantity(Rec, IsHandled);
                if not IsHandled then
                    Validate(Quantity);**
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateUnitofMeasureCodeOnBeforeValidateQuantity(var WhseWorksheetLine: Record "Whse. Worksheet Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
