### ISSUE TITLE
[Event Request] Page::"Check Credit Limit - Function SalesHeaderShowWarning - OnBeforeSalesHeaderShowWarning

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9479]
We like to request the following Event:
Object: Page::"Check Credit Limit
Function: SalesHeaderShowWarning
Publisher Event: OnBeforeSalesHeaderShowWarning
Reason: To implement custom business logic
Where is the event placed:
[Scope('OnPrem')]
    procedure SalesHeaderShowWarning(SalesHeader: Record "Sales Header"): Boolean
    var
        OldSalesHeader: Record "Sales Header";
        AssignDeltaAmount: Boolean;
        IsHandled: Boolean;
        Result: Boolean;
    begin
        // Used when additional lines are inserted
        IsHandled := false;
        OnBeforeSalesHeaderShowWarning(SalesHeader, Result, IsHandled);
        If IsHandled then
            exit(Result);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSalesHeaderShowWarning(var SalesHeader: Record "Sales Header"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
