### ISSUE TITLE
[Event Request] Page::"Check Credit Limit - Function SalesLineShowWarning - OnBeforeSalesLineShowWarning

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9480]
We like to request the following Event:
Object: Page::"Check Credit Limit
Function: SalesLineShowWarning
Publisher Event: OnBeforeSalesLineShowWarning
Reason: To implement custom business logic
Where is the event placed:
[Scope('OnPrem')]
    procedure SalesLineShowWarning(SalesLine: Record "Sales Line"): Boolean
    var
        Result: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSalesLineShowWarning(SalesLine, Result, IsHandled);
        if IsHandled then
            exit(Result);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineShowWarning(var SalesLine: Record "Sales Line"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
