### ISSUE TITLE
[Event Request] Page::"Check Credit Limit - Function CalcOverdueBalanceLCY - OnCalcOverdueBalanceLCYAfterSetFilter

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9481]
We like to request the following Event:
Object: Page::"Check Credit Limit
Function: CalcOverdueBalanceLCY
Publisher Event: OnCalcOverdueBalanceLCYAfterSetFilter
Reason: To implement custom business logic
Where is the event placed:
local procedure CalcOverdueBalanceLCY()
    begin
        if GetFilter("Date Filter") = '' then
            SetFilter("Date Filter", '..%1', WorkDate);
        OnCalcOverdueBalanceLCYAfterSetFilter(Rec);
        CalcFields("Balance Due (LCY)");
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCalcOverdueBalanceLCYAfterSetFilter(var Customer: Record Customer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
