### ISSUE TITLE
[Event Request] Report::"Get Outbound Source Documents" - Function "Whse. Pick Request" - OnAfterGetRecord - OnBeforeWhseShipmentLineOnAfterGetRecord

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9482]
We like to request the following Event:
Object: Report::"Get Outbound Source Documents"
Function: "Whse. Pick Request" - OnAfterGetRecord
Publisher Event: OnBeforeWhseShipmentLineOnAfterGetRecord
Reason: To implement custom business logic
Where is the event placed:
trigger OnAfterGetRecord()
                    var
                        ATOLink: Record "Assemble-to-Order Link";
                        ATOAsmLine: Record "Assembly Line";
                        IsHandled: Boolean;
                    begin
                        IsHandled := false;
                        OnBeforeWhseShipmentLineOnAfterGetRecord("Warehouse Shipment Line", "Whse. Pick Request", IsHandled);
                        If IsHandled then
                            CurrReport.Skip;
                        if not "Assemble to Order" then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeWhseShipmentLineOnAfterGetRecord(var WhseShipmentLine: Record "Warehouse Shipment Line"; var WhsePickRequest: Record "Whse. Pick Request"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
