### ISSUE TITLE
[Event Request] Report::"Get Source Documents" - Function "Transfer Header" - OnPostDataItem - OnBeforePostDataItemTransferLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9483]
We like to request the following Event:
Object: Report::"Get Source Documents"
Function: "Transfer Header" - OnPostDataItem
Publisher Event: OnBeforePostDataItemTransferLine
Reason: To implement custom business logic
Where is the event placed:
trigger OnPostDataItem()
                    begin
                        **OnBeforePostDataItemTransferLine(WhseReceiptHeader, RequestType, OneHeaderCreated, WhseHeaderCreated, LineCreated, HideDialog);**
                        if OneHeaderCreated or WhseHeaderCreated then begin
                            UpdateReceiptHeaderStatus;
                            CheckFillQtyToHandle;
                        end;
                        OnAfterProcessDocumentLine(WhseShptHeader, "Warehouse Request", LineCreated);
                    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePostDataItemTransferLine(var WhseReceiptHeader: Record "Warehouse Receipt Header"; RequestType: Option Receive,Ship; OneHeaderCreated: Boolean; WhseHeaderCreated: Boolean; LineCreated: Boolean;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
