### ISSUE TITLE
[Event Request] Database::"Whse. Internal Put-away Line" - Function "Item No." - OnValidate - OnValidateOnBeforeSetItemFields

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9484]
We like to request the following Event:
Object: Database::"Whse. Internal Put-away Line"
Function: "Item No." - OnValidate
Publisher Event: OnValidateOnBeforeSetItemFields
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestReleased;
                TestField("Qty. Put Away", 0);
                if "Item No." <> xRec."Item No." then
                    "Variant Code" := '';
                **IsHandled := false;
                OnValidateOnBeforeSetItemFields(Rec, IsHandled);
                if not IsHandled then**
                    if "Item No." <> '' then begin
                        GetItemUnitOfMeasure;
                        Description := Item.Description;
                        "Description 2" := Item."Description 2";
                        "Shelf No." := Item."Shelf No.";
                        Validate("Unit of Measure Code", ItemUnitOfMeasure.Code);
                    end else begin
                        Description := '';
                        "Description 2" := '';
                        "Variant Code" := '';
                        "Shelf No." := '';
                        Validate("Unit of Measure Code", '');
                    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateOnBeforeSetItemFields(var WhseInternalPutAwayLine: Record "Whse. Internal Put-away Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
