### ISSUE TITLE
[Event Request] Database::"Sales Line" – CopyFromSalesLine - OnAfterCopyFromSalesLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9485]
We like to request the following Event:
Object: ] Database::"Sales Line"
Function: CopyFromSalesLine
Publisher Event: OnAfterCopyFromSalesLine
Reason: To implement custom business logic
Where is the event placed:
"[Scope('OnPrem')]
    procedure CopyFromSalesLine(FromSalesLine: Record ""Sales Line"")
    begin
        ""No."" := FromSalesLine.""No."";
        ""Variant Code"" := FromSalesLine.""Variant Code"";
        ""Location Code"" := FromSalesLine.""Location Code"";
        ""Bin Code"" := FromSalesLine.""Bin Code"";
        ""Unit of Measure Code"" := FromSalesLine.""Unit of Measure Code"";
        ""Qty. per Unit of Measure"" := FromSalesLine.""Qty. per Unit of Measure"";
        ""Outstanding Quantity"" := FromSalesLine.Quantity;
        ""Qty. to Assemble to Order"" := 0;
        ""Drop Shipment"" := FromSalesLine.""Drop Shipment"";
        **OnAfterCopyFromSalesLine(Rec, FromSalesLine);**
    end;"

Event Code:
"[IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromSalesLine(var SalesLine: Record ""Sales Line""; FromSalesLine: Record ""Sales Line"")
    begin
    end;"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
