### ISSUE TITLE
[Event Request] Database::"Warehouse Journal Line"	"Item No." - OnValidate	OnItemNoValidatateOnBeforeSetItemFields

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9486]
We like to request the following Event:
Object: ] Database::"Warehouse Journal Line"
Function: "Item No." - OnValidate
Publisher Event: OnItemNoValidatateOnBeforeSetItemFields
Reason: To implement custom business logic
Where is the event placed:
"trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                if not PhysInvtEntered then
                    TestField(""Phys. Inventory"", false);

                if ""Item No."" <> '' then
                    if ""Item No."" <> xRec.""Item No."" then
                        ""Variant Code"" := '';

                **IsHandled := false;
                OnItemNoValidatateOnBeforeSetItemFields(Rec, IsHandled);
                if not IsHandled then**
                    if ""Item No."" <> '' then begin
                        GetItemUnitOfMeasure;
                        Description := Item.Description;
                        Validate(""Unit of Measure Code"", ItemUnitOfMeasure.Code);
                    end else begin
                        Description := '';
                        ""Variant Code"" := '';
                        Validate(""Unit of Measure Code"", '');
                    end;
            end;"
Event Code:
" [IntegrationEvent(false, false)]
    local procedure OnItemNoValidatateOnBeforeSetItemFields(var WarehouseJournalLine: Record ""Warehouse Journal Line""; var IsHandled: Boolean)
    begin
    end;"

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
