### ISSUE TITLE
[Event Request] Database::"Purchase Line" - "Qty. to Receive" - OnValidate - OnQtyToReceiveOnValidateOnBeforeLocationRequiredCheck

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9487]
We like to request the following event:
Object: Database::"Purchase Line"
Function: "Qty. to Receive" - OnValidate
Publisher Event: OnQtyToReceiveOnValidateOnBeforeLocationRequiredCheck
Reason: To implement custom business logic 

Where is the event placed:
 trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                **IsHandled := false;
                OnQtyToReceiveOnValidateOnBeforeLocationRequiredCheck(Rec, IsHandled);
                if not IsHandled then**
                    if ("Qty. to Receive" <> 0) then
                        CheckLocationRequireReceive();
                OnValidateQtyToReceiveOnAfterCheck(Rec, CurrFieldNo);

                if "Qty. to Receive" = Quantity - "Quantity Received" then begin
                    IsHandled := false;
                    OnValidateQtyToReceiveOnBeforeInitQtyToReceive(Rec, CurrFieldNo, IsHandled);
                    if not IsHandled then
                        InitQtyToReceive;
                end else begin

Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnQtyToReceiveOnValidateOnBeforeLocationRequiredCheck(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
