### ISSUE TITLE
[Event Request] Report::"Get Source Documents" - Function "Purchase Header" - OnPostDataItem - OnAfterPostDataItemPurchaseHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9488]
We like to request the following Event:
Object: Report::"Get Source Documents"
Function: "Purchase Header" - OnPostDataItem
Publisher Event: OnAfterPostDataItemPurchaseHeader
Reason: To implement custom business logic
Where is the event placed:
**trigger OnPostDataItem()
                begin
                    OnAfterPostDataItemPurchaseHeader("Purchase Header", "Purchase Line", "Warehouse Request", WhseReceiptHeader);
                end;**
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterPostDataItemPurchaseHeader(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var WarehouseRequest: Record "Warehouse Request"; var WhseReceiptHeader: Record

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
