### ISSUE TITLE
[Event Request] Table 37 Sales-Line - OnValidateQuantityOnBeforeMakeDefaultQuantity

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9491]
Hi Team,

In Table 37 we need possibility to have our additional checks. Having event with handling on trigger `OnValidate` of field `Quantity` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96585757-b008a000-12e8-11eb-9965-64085c9869dd.png)

    [IntegrationEvent(true, false)]
    local procedure OnValidateQuantityOnBeforeMakeDefaultQuantity(var Rec: Record "Sales Line"; var xRec: Record "Sales Line"; IsAsmToOrderAllowed: Boolean; IsAsmToOrderRequired: Boolean; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
