### ISSUE TITLE
[Event Request] Table 37 Sales-Line - OnValidateQuantityOnAfterUpdatePrePaymentAmounts

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9493]
Hi Team,

In Table 37 we need possibility to have our additional checks. Having event in the end of procedure `UpdatePrePaymentAmounts` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96586574-db3fbf00-12e9-11eb-992a-f11a14b88d2f.png)

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnAfterUpdatePrePaymentAmounts(var Rec: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
