### ISSUE TITLE
[Event Request] Table 37 Sales-Line - OnDeleteOnBeforeTestfieldReservedQtyBase

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9494]
Hi Team,

In Table 37 we need possibility to have our additional checks. Having event with handling on trigger `OnDelete` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96588147-f3b0d900-12eb-11eb-9afd-0edc179ed134.png)

    [IntegrationEvent(false, false)]
    local procedure OnDeleteOnBeforeTestfieldReservedQtyBase(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
