### ISSUE TITLE
[Event Request] table 38 "Purchase Header": ConfirmResvDateConflict

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#9495]
Object: tabe 38 "Purchase Header"

Function: ConfirmResvDateConflict

Integration Event:

OnBeforeConfirmResvDateConflict(var IsHandled: Boolean);

![2020-10-20_15h11_59](https://user-images.githubusercontent.com/50943286/96591320-6c616680-12e7-11eb-98db-af9c61e23f35.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
