### ISSUE TITLE
[Event Request] Table 39 Purchase Line - OnBeforeInitOutstandingAmount

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9496]
Hi Team,

In Table 39 we need possibility to have our additional checks. Having event in procedure `InitOutstanding` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96592543-2dd0a980-12f1-11eb-9d75-7ffc629da95c.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitOutstandingAmount(var PurchaseLine: record "Purchase Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
