### ISSUE TITLE
[Event Request] codeunit 99000815 "Reservation-Check Date Confl.": DateConflict

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#9497]
Object: codeunit 99000815 "Reservation-Check Date Confl."

Function: DateConflict

Integration Event:

OnBeforeDateConflict(var Date: Date);

![image](https://user-images.githubusercontent.com/50943286/96595893-6fab2100-12ec-11eb-87fd-096b2dfb82b5.png)

**It's very important that the Date is var!**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
