### ISSUE TITLE
[Event Request] codeunit 99000815 "Reservation-Check Date Confl.": DateConflict

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#9498]
Object: codeunit 99000815 "Reservation-Check Date Confl."

Function: DateConflict

Integration Event:

OnAfterDateConflict(var IsConflict: Boolean);

![image](https://user-images.githubusercontent.com/50943286/96596244-c9135000-12ec-11eb-8dd5-50e7253bad56.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
