### ISSUE TITLE
[Event Request] Table 23 "Vendor" - OnBeforePurchOrderLineSetRange

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9499]
We are migrating our code from NAV 2018 to BC16.4. In the Table 23 "Vendor", in the trigger OnDelete, we would like to not use the lines "PurchOrderLine.SetCurrentKey" , "PurchOrderLine.SetRange", "PurchOrderLine.IsEmpty" and "PurchOrderLine.FindFirst" of standard code. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96596224-c6185f80-12ec-11eb-9488-c69bfd3f3a67.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96596149-b39e2600-12ec-11eb-9525-a4cd67edf37a.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
