### ISSUE TITLE
D365 Business Central App & Azure functions

### ISSUE THREAD

**Issue by Bssivivek** [Microsoft/ALAppExtensions#95]
Hi,

Currently we are working on a D365 Business central app and we have logic running in azure function which is hosted in US region.
Just to give quick overview about our app, we help users maintain their contract and it is date sensitive.
For example: When user create a contract from Jan 1 2018 to Dec 31 2018 with monthly frequency, we create billing detail from jan 1 - jan 31 , feb 1 - feb 28 and soon. The logic to create the billing detail is written in azure function.
 It works perfectly fine if we download BD docker image for US and region is US. (date format MM/dd/yyyy)
If we change the region (in business central) to English (united kingdom) or any other region where date format is DD/MM/YYYY it fails because Jan 31 2018 in DD/MM/YYYY format is 31/01/2018 and azure function is still considering it as MM/DD/YYYY (Don't know why..May be because Azure function is hosted in US region) and its erroring out.

How do we handle this situation. We don't want to duplicate the azure function for all the regions as it is redundant/duplication.

Do any one came across this situation and please suggest the right approach!!

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
This GitHub repository is dedicated to handling issues with published apps and extensibility requests for the latest release of Business Central.

To get help on general questions please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
