### ISSUE TITLE
Event/Code change Request on Codeunit 5510 Production Journal Mgt - Procedure SetTemplateAndBatchName

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#9500]
We need a new event function in Codeunit 5510 Production Journal Mgt - Procedure SetTemplateAndBatchName:

LOCAL [IntegrationEvent] OnBeforeSetTemplateAndBatchName(VAR ToTemplateName : Code [10];VAR ToBatchName: Code [10];VAR IsHandled : Boolean)

Called from: 

procedure SetTemplateAndBatchName()
    var
        PageTemplate: Option Item,Transfer,"Phys. Inventory",Revaluation,Consumption,Output,Capacity,"Prod. Order";
        User: Text;
    begin
        //INIT-INSERT
        IsHandled := FALSE;
        OnBeforeSetTemplateAndBatchName(ToTemplateName,ToBatchName, IsHandled);
        IF IsHandled THEN
          EXIT;
       //END-INSERT
        ItemJnlTemplate.Reset();
        ItemJnlTemplate.SetRange("Page ID", PAGE::"Production Journal");

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
