### ISSUE TITLE
[Event Request] Table 23 "Vendor" - OnBeforeExitAssistEdit

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9501]
We are migrating our code from NAV 2018 to BC16.4. In the Table 23 "Vendor", in the procedure AssistEdit, we would like to add our code at the end the "if" statement. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96598433-27413280-12ef-11eb-9baa-58698761a17a.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96598342-0d9feb00-12ef-11eb-88f6-e264e67db982.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
