### ISSUE TITLE
[Event Request] Table 39 Purchase Line - OnValidateUnitCostLCYOnBeforeUpdateSalesCost

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9502]
Hi Team,

In Table 39 we need possibility to have our additional checks. Having event with handling on trigger `OnValidate` of field `"Unit Cost (LCY)"` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96600452-9d4a9700-12f9-11eb-9257-6ae0b3661dcf.png)

    [IntegrationEvent(false, false)]
    local procedure OnValidateUnitCostLCYOnBeforeUpdateSalesCost(var Rec: Record "Purchase Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
