### ISSUE TITLE
[Event Request] Table 37 Sales-Line - OnValidateUnitOfMeasureCodeOnBeforeValidateQuantity

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9503]
Hi Team,

In Table 37 we need possibility to have our additional checks and avoid using standard validation. Having event with handling in the end of `OnValidate` trigger of field `"Unit of Measure Code"` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96601037-44c7c980-12fa-11eb-8de9-bfe60325b33a.png)

    [IntegrationEvent(false, false)]
    local procedure OnValidateUnitOfMeasureCodeOnBeforeValidateQuantity(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
