### ISSUE TITLE
[Event Request] Table 37 Sales-Line - OnValidateLineDiscountAmountOnBeforeTestFieldQuantity

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9504]
Hi Team,

In Table 37 we need possibility to have our additional checks. Having event with handling on `OnValidate` trigger of field `"Line Discount Amount"` would be a perfect solution :

![image](https://user-images.githubusercontent.com/70525691/96605352-c6b9f180-12fe-11eb-88d2-defde209e846.png)

    [IntegrationEvent(false, false)]
    local procedure OnValidateLineDiscountAmountOnBeforeTestFieldQuantity(var IsHandled: Boolean; var Rec: Record "Sales Line"; CurrFieldNo: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
