### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeCheckSNSpecificationExists

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9505]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the procedure CheckSNSpecificationExists, we would like to add a condition to the use of the procedure. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96611898-6fffe800-12fd-11eb-8e6f-a989ce4673d1.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96611857-65455300-12fd-11eb-8066-35c653b8fc35.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
