### ISSUE TITLE
[Extensibility Request] Make Copy Document Reports more extensible

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#9506]
To be able to copy documents, the "copy * document" reports must currently be copied and overwritten by report substitution.
For the copy item functionality microsoft has provided a great solution (using a extensible page instead of report requestpage) which makes this no longer necessary and makes the functionality customizable from multiple apps.

I therefore ask you to rebuild the copy document functionalities according to the same pattern.
A good Start would be the copy sales document and copy purchase document reports but all should follow.

**Comment by AlexanderYakunin** [comment]
We need to understand what kind of extensibility you expect from CopySalesDocuments report, for example. Do you need to add more parameters to request page? Or you need something else?

**Comment by ChrisBlankDe** [comment]
What we have changed:

- Added some fields to request page
- Added a `OnInitReport` trigger 
- Added some global vars to control visibility of custom controls on request page
- Also we added some code but we where already able to move this to event subscription

**Comment by AlexanderYakunin** [comment]
Report extensibility will be provided via platform improvements, so it should be possible to add fields to request page etc. We decided to wait until this platform feature will be implemented, as it can solve all issues above. If not we will review it again and decide on next steps.

**Comment by NKarolak** [comment]
@ChrisBlankDe  FYI
https://github.com/microsoft/AL/issues/1452#issuecomment-733709026
