### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeFindLotNoBySerialNo

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9507]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the procedure FindLotNoBySerialNo, we would like to add a condition to the use of the procedure. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96688608-aa12cd80-1381-11eb-9e82-7766ad1b7c1f.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96688563-9b2c1b00-1381-11eb-8087-bfc68868a1a9.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
