### ISSUE TITLE
Reminder: page 9192 "Company Creation Wizard" - OnAfterCompanyCreated

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#9509]
Regarding #5842 from Jan 2020, there is nothing to see in BC17 or  Insider Build 18.0.17898.0.
Status since 7. Feb is "ships-in-future-update".
Will you still integrate it?

**Comment by StanPesotskiy** [comment]
There had been added OnAfterCreateNewCompany event:
```
    local procedure FinishAction()
    var
        AssistedCompanySetup: Codeunit "Assisted Company Setup";
        PermissionManager: Codeunit "Permission Manager";
    begin
        AssistedCompanySetup.CreateNewCompany(NewCompanyName);
        **OnAfterCreateNewCompany(NewCompanyData, NewCompanyName);**
```

Does not it work?
In the original request wass mentioned 'UseKVSPSA' parameter, but it does not exist in this context.

**Comment by ChrisBlankDe** [comment]
We also need the `OnAfterCompanyCreated(NewCompanyData, NewCompanyName);` to run additional code after the company where setup and the permission where set.
In our special case we overwrite the NewCompanyData flag and run an new assistent which helps us to create more suitable setup or sample data. its important for us to run this code before the Company Creation Wizard gets closed.

Code could look like this:
```
    local procedure FinishAction()
    var
        AssistedCompanySetup: Codeunit "Assisted Company Setup";
        PermissionManager: Codeunit "Permission Manager";
    begin
        AssistedCompanySetup.CreateNewCompany(NewCompanyName);
        OnAfterCreateNewCompany(NewCompanyData, NewCompanyName);

        AssistedCompanySetup.SetUpNewCompany(NewCompanyName, NewCompanyData);

        if FindSet() then
            repeat
                PermissionManager.AddUserToDefaultUserGroupsForCompany("User Security ID", NewCompanyName);
            until Next = 0;

        CompanyCreated := true;
        OnAfterCompanyCreated(NewCompanyData, NewCompanyName);
        CurrPage.Close();
        if not (NewCompanyData in [NewCompanyData::None, NewCompanyData::"Full No Data"]) then
            Message(CompanySetUpInProgressMsg, NewCompanyName);
    end;

    [IntegrationEvent(true, false)] 
    local procedure OnAfterCompanyCreated(NewCompanyData: Option; NewCompanyName: Text[30])
    begin
    end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
