### ISSUE TITLE
[Enum Request] NewCompanyData in Page 9192 "Company Creation Wizard"

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#9510]
It would be nice if the option variable `NewCompanyData `would be converted into an extensible enum. 
The code would be much more extensible and would allow several extensions to be added to this page.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
