### ISSUE TITLE
remove local @ codeunit 550 "VAT Rate Change Conversion" 

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#9511]
Could you please remove the local flag from the following procedures in codeunit 550 "VAT Rate Change Conversion" 

- UpdateTable
- ConvertVATProdPostGrp
- ConvertGenProdPostGrp

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
