### ISSUE TITLE
[Event Request] Codeunit 6500 "Item Tracking Management" - OnBeforeGetWhseItemTrkgSetup

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9512]
We are migrating our code from NAV 2018 to BC16.4. In the Codeunit 6500 "Item Tracking Management", in the 
procedure GetWhseItemTrkgSetup(ItemNo: Code[20]; var WhseItemTrackingSetup: Record "Item Tracking Setup"): Boolean;
we would like to add our code before the excution of the procedure. To do so, we need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/96707048-a9853180-1397-11eb-95c7-11ce1e8d417c.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/96706871-6e82fe00-1397-11eb-846c-a3db07c4d43e.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
