### ISSUE TITLE
[Request for External]  table 60 "Document Sending Profile" - IsSingleRecordSelected

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#9514]
Could you make the following function made available to extensions by changing the access level to `protected`?
```al
protected procedure IsSingleRecordSelected(RecordVariant: Variant; CVNo: Code[20]; CVFieldNo: Integer): Boolean//NEW
//-local procedure IsSingleRecordSelected(RecordVariant: Variant; CVNo: Code[20]; CVFieldNo: Integer): Boolean
var
    RecRef: RecordRef;
    FieldRef: FieldRef;
begin
   
...

end;
```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
