### ISSUE TITLE
codeunit 8888 "Email Dispatcher" - OnAfterUpdateOutboxStatus

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#9527]
Can we please get the following event?
```al
local procedure UpdateOutboxStatus(var EmailOutbox: Record "Email Outbox"; Status: Enum "Email Status")
begin
    EmailOutbox.Status := Status;
    EmailOutbox.Modify();
    Commit();
    OnAfterUpdateOutboxStatus(EmailOutbox. Status);//NEW
end;

```

```al
[IntegrationEvent(false, false)]
local procedure  OnAfterUpdateOutboxStatus(EmailOutbox: Record "Email Outbox"; NewStatus: Enum "Email Status")
begin
end;
```

**Comment by pri-kise** [comment]
@StanPesotskiy  I dont't know if this event is even possible if the Codeunit is set to internal. Maybe the implementation Codeunit has to call the Event placed into another Codeunit with Access=Public....?

**Comment by darjoo** [comment]
@pri-kise Could you please let me know why you need this event? What is the scenario you're trying to achieve?

**Comment by pri-kise** [comment]
We want to send optional notifications to the user if the senidng of an e-mail outbox entry fails.
For this reason we need an event when the status is beeing updated. An since the property Status is to internal I request the new Status, too.

**Comment by darjoo** [comment]
I'll go ahead and put in an event that is triggered when the email fails to send.
It'll be something along the lines of `OnAfterEmailFailedToSend(Rec: Record 'Email Outbox')`

**Comment by JesperSchulz** [comment]
Sounds like this PR is linked together with #9613, which we're currently discussing. While we're doing so, this on should be set on hold as well. Let's get the design of this right.

**Comment by GiorgosPa** [comment]
@pri-kise thank you for your suggestion, we have implemented it a little bit differently. I hope it suits your needs.

```
    /// <summary>
    /// Integration event that notifies senders about whether their email was successfully sent in the background.
    /// </summary>
    /// <param name="MessageId">The ID of the email in the queue.</param>
    /// <param name="Status">True if the message was successfully sent.</param>
    [IntegrationEvent(false, false)]
    internal procedure OnAfterSendEmail(MessageId: Guid; Status: Boolean)
    begin
    end;
```
