### ISSUE TITLE
[Event Request] Page 5104 Contact Picture - OnBeforceTakePicture

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/ALAppExtensions#9529]
Please add a new publisher event to the function TakePicture - OnAction() as follows:

`
trigger OnAction()
begin
        TestField("No.");
        TestField(Name);

	//>> Start New Publisher Call
	OnBeforceTakePicture(Rec);
	//<< End New Publisher Call

	Camera.AddPicture(Rec, Rec.FieldNo(Image));
end;
`

New Publisher Event:
`LOCAL [IntegrationEvent] OnBeforceTakePicture(VAR Contact : Record Contact)`

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
