### ISSUE TITLE
[Event Request] Database::"Assemble-to-Order Link" - Function SynchronizeAsmFromSalesLine - OnBeforeChangeQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9530]
We like to request the following Event:
Object: Database::"Assemble-to-Order Link"
Function: SynchronizeAsmFromSalesLine
Publisher Event: OnBeforeChangeQty
Reason: To implement custom business logic
Where is the event placed:
ChangePostingDate(SalesHeader."Posting Date");
        ChangeDim(NewSalesLine."Dimension Set ID");
        ChangePlanningFlexibility;
        **OnBeforeChangeQty(AsmHeader, NewSalesLine);**
        ChangeQty(NewSalesLine."Qty. to Assemble to Order");
        if NewSalesLine."Document Type" <> NewSalesLine."Document Type"::Quote then
            ChangeQtyToAsm(MaxQtyToAsm(NewSalesLine, AsmHeader));
        OnBeforeAsmHeaderModify(AsmHeader, NewSalesLine);
        AsmHeader.Modify(true);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeChangeQty(var AssemblyHeader: Record "Assembly Header"; var SalesLine: Record "Sales Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
