### ISSUE TITLE
[Event Request] Database::"Assembly Header" - Function CreatePick - OnCreatePickOnBeforeWhseSourceCreateDocument

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9531]
We like to request the following Event:
Object: Database::"Assembly Header"
Function: CreatePick
Publisher Event: OnCreatePickOnBeforeWhseSourceCreateDocument
Reason: To implement custom business logic
Where is the event placed:
procedure CreatePick(ShowRequestPage: Boolean; AssignedUserID: Code[50]; SortingMethod: Option; SetBreakBulkFilter: Boolean; DoNotFillQtyToHandle: Boolean; PrintDocument: Boolean)
    var
        WhseSourceCreateDocument: Report "Whse.-Source - Create Document";
        IsHandled: Boolean;
    begin
        AssemblyLineMgt.CreateWhseItemTrkgForAsmLines(Rec);
        Commit();
        TestField(Status, Status::Released);
        if CompletelyPicked then
            Error(Text007);
        **IsHandled := false;
        OnCreatePickOnBeforeWhseSourceCreateDocument(Rec, AssignedUserID, SortingMethod, PrintDocument, DoNotFillQtyToHandle, SetBreakBulkFilter, ShowRequestPage, IsHandled);
        if not IsHandled then begin**
            WhseSourceCreateDocument.SetAssemblyOrder(Rec);
            if not ShowRequestPage then
                WhseSourceCreateDocument.Initialize(AssignedUserID, SortingMethod, PrintDocument, DoNotFillQtyToHandle, SetBreakBulkFilter);
            WhseSourceCreateDocument.UseRequestPage(ShowRequestPage);
            WhseSourceCreateDocument.RunModal;
            WhseSourceCreateDocument.GetResultMessage(2);
            Clear(WhseSourceCreateDocument);
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCreatePickOnBeforeWhseSourceCreateDocument(var Rec: Record "Assembly Header"; AssignedUserID: Code[50]; SortingMethod: Option; PrintDocument: Boolean; DoNotFillQtyToHandle: Boolean; SetBreakBulkFilter

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
