### ISSUE TITLE
[Event Request] Database::"Assembly Header" - Function Quantity - OnValidate - OnValidateQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9532]
We like to request the following Event:
Object: Database::"Assembly Header"
Function: Quantity - OnValidate
Publisher Event: OnValidateQuantityOnAfterCalcBaseQty
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                CheckIsNotAsmToOrder;
                TestStatusOpen;
                SetCurrentFieldNum(FieldNo(Quantity));
                RoundQty(Quantity);
                "Cost Amount" := Round(Quantity * "Unit Cost");
                if Quantity < "Assembled Quantity" then
                    Error(Text002, FieldCaption(Quantity), FieldCaption("Assembled Quantity"), "Assembled Quantity");
                "Quantity (Base)" := CalcBaseQty(Quantity);
                **OnValidateQuantityOnAfterCalcBaseQty(Rec, CurrFieldNo);**
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnAfterCalcBaseQty(var AssemblyHeader: Record "Assembly Header"; CallingFieldNo: Integer)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
