### ISSUE TITLE
[Event Request] Database::"Assembly Header" - Function Quantity - OnValidate - OnValidateQuantityOnBeforeUpdateAssemblyLines

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9533]
We like to request the following Event:
Object: Database::"Assembly Header"
Function: Quantity - OnValidate
Publisher Event: OnValidateQuantityOnBeforeUpdateAssemblyLines
Reason: To implement custom business logic
Where is the event placed:
InitRemainingQty;
                InitQtyToAssemble;
                Validate("Quantity to Assemble");
                **IsHandled := false;
                OnValidateQuantityOnBeforeUpdateAssemblyLines(Rec, xRec, CurrFieldNo, CurrentFieldNum, IsHandled);
                if not IsHandled then begin**
                    AssemblyLineMgt.UpdateAssemblyLines(Rec, xRec, FieldNo(Quantity), ReplaceLinesFromBOM, CurrFieldNo, CurrentFieldNum);
                    AssemblyHeaderReserve.VerifyQuantity(Rec, xRec);
                end;
                ClearCurrentFieldNum(FieldNo(Quantity));
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnBeforeUpdateAssemblyLines(var AssemblyHeader: Record "Assembly Header"; var xAssemblyHeader: Record "Assembly Header"; CurrFieldNo: Integer; CurrentFieldNum: Integer; var IsHandled:

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
