### ISSUE TITLE
[Event Request] Database::"Assembly Line" - Function Quantity - OnValidate - OnValidateQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9534]
We like to request the following Event:
Object: Database::"Assembly Line"
Function: Quantity - OnValidate
Publisher Event: OnValidateQuantityOnAfterCalcBaseQty
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            begin
                WhseValidateSourceLine.AssemblyLineVerifyChange(Rec, xRec);
                RoundQty(Quantity);
                "Quantity (Base)" := CalcBaseQty(Quantity);
                **OnValidateQuantityOnAfterCalcBaseQty (Rec, xRec, CurrFieldNo);**
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnAfterCalcBaseQty (var AssemblyLine: Record "Assembly Line"; xAssemblyLine: Record "Assembly Line"; CurrentFieldNo: Integer);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
