### ISSUE TITLE
[Event Request] Database::"Job Planning Line" - Function Quantity - OnValidate - OnValidateQuantityOnBeforeAssignQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9535]
We like to request the following Event:
Object: Database::"Job Planning Line"
Function: Quantity - OnValidate
Publisher Event: OnValidateQuantityOnBeforeAssignQuantity
Reason: To implement custom business logic
Where is the event placed:
case Type of
                    Type::Item:
                        if not Item.Get("No.") then
                            Error(MissingItemResourceGLErr, Type, Item.FieldCaption("No."));
                    Type::Resource:
                        if not Res.Get("No.") then
                            Error(MissingItemResourceGLErr, Type, Res.FieldCaption("No."));
                    Type::"G/L Account":
                        if not GLAcc.Get("No.") then
                            Error(MissingItemResourceGLErr, Type, GLAcc.FieldCaption("No."));
                end;
                **IsHandled := false;
                OnValidateQuantityOnBeforeAssignQuantity(Rec, xRec, CurrFieldNo, IsHandled);
                if not IsHandled then**
                    "Quantity (Base)" := UOMMgt.CalcBaseQty("No.", "Variant Code", "Unit of Measure Code", Quantity, "Qty. per Unit of Measure");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnBeforeAssignQuantity(var JobPlanningLine: Record "Job Planning Line"; var xJobPlanningLine: Record "Job Planning Line"; CurrFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
