### ISSUE TITLE
[Event Request] Database::"Prod. Order Component" - Function "Expected Quantity" - OnValidate - OnValidateExpectedQuantityOnBeforeRound

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9536]
We like to request the following Event:
Object: Database::"Prod. Order Component"
Function: "Expected Quantity" - OnValidate
Publisher Event: OnValidateExpectedQuantityOnBeforeRound
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                if Item.Get("Item No.") then
                    if Item."Rounding Precision" > 0 then begin
                        **OnValidateExpectedQuantityOnBeforeRound (Rec, IsHandled);
                        if not IsHandled then**
                            "Expected Quantity" := UOMMgt.RoundToItemRndPrecision("Expected Quantity", Item."Rounding Precision");
                        OnAfterRoundExpectedQuantity(Rec);
                    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateExpectedQuantityOnBeforeRound (var ProdOrderComponent: Record "Prod. Order Component"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
