### ISSUE TITLE
[Event Request] Database::"Prod. Order Line" - Function UpdateProdOrderComp - OnUpdateProdOrderCompOnBeforeLoop

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9537]
We like to request the following Event:
Object: Database::"Prod. Order Line"
Function: UpdateProdOrderComp
Publisher Event: OnUpdateProdOrderCompOnBeforeLoop
Reason: To implement custom business logic
Where is the event placed:
procedure UpdateProdOrderComp(QtyPerUnitOfMeasure: Decimal)
    var
        ProdOrderComp: Record "Prod. Order Component";
        ModifyRecord: Boolean;
        IsHandled: Boolean;
    begin
        ProdOrderComp.SetRange(Status, Status);
        ProdOrderComp.SetRange("Prod. Order No.", "Prod. Order No.");
        ProdOrderComp.SetRange("Prod. Order Line No.", "Line No.");
        if ProdOrderComp.FindSet then begin
            ModifyRecord := false;
            OnUpdateProdOrderCompOnAfterFind(Rec, ModifyRecord);
            if ModifyRecord then
                Modify;
            **OnUpdateProdOrderCompOnBeforeLoop (Rec, ProdOrderComp, QtyPerUnitOfMeasure, IsHandled);
            if IsHandled then
                exit;**
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnUpdateProdOrderCompOnBeforeLoop (var ProdOrderLine: Record "Prod. Order Line"; var ProdOrderComp: Record "Prod. Order Component"; QtyPerUnitOfMeasure: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by StanPesotskiy** [comment]
Please use the existing handled event OnBeforeUpdateProdOrderComp.
