### ISSUE TITLE
[Event Request] Database::"Production Order" - Function CreatePick - OnCreatePickOnBeforeCreatePickFromWhseSource

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9539]
We like to request the following Event:
Object: Database::"Production Order"
Function: CreatePick
Publisher Event: OnCreatePickOnBeforeCreatePickFromWhseSource
Reason: To implement custom business logic
Where is the event placed:
if ProdOrderCompLine.Find('-') then begin
            IsHandled := false;
            **OnCreatePickOnBeforeCreatePickFromWhseSource(Rec, AssignedUserID, SortingMethod, PrintDocument, DoNotFillQtyToHandle, SetBreakBulkFilter, HideValidationDialog, IsHandled);
            if not IsHandled then begin**
                CreatePickFromWhseSource.SetProdOrder(Rec);
                CreatePickFromWhseSource.SetHideValidationDialog(HideValidationDialog);
                if HideValidationDialog then
                    CreatePickFromWhseSource.Initialize(AssignedUserID, SortingMethod, PrintDocument, DoNotFillQtyToHandle, SetBreakBulkFilter);
                CreatePickFromWhseSource.UseRequestPage(not HideValidationDialog);
                CreatePickFromWhseSource.RunModal;
                CreatePickFromWhseSource.GetResultMessage(2);
                Clear(CreatePickFromWhseSource);
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCreatePickOnBeforeCreatePickFromWhseSource(var Rec: Record "Production Order"; AssignedUserID: Code[50]; SortingMethod: Option; PrintDocument: Boolean; DoNotFillQtyToHandle: Boolean; SetBreakBulkFilte

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
