### ISSUE TITLE
OnBeforeDeleteSalesQuoteData CU86

### ISSUE THREAD

**Issue by Joriek** [Microsoft/ALAppExtensions#954]
Hello,

Currently there is already an event like this but i think we need a some more parameters.
In a lot of cases our customers don't want to use the archive table for their quotes but use the actual quote. In the conversion of a quote to an order there is no way to work around this so a new event with handled pattern is needed.

Code snippit is from CU86 "Sales-Quote to Order" in the on run trigger

![image](https://user-images.githubusercontent.com/6583705/51748053-825adc80-20ab-11e9-84c5-2cf48b32796f.png)

Thanks in advance.

**Comment by AlexanderYakunin** [comment]
We already have this possibility here, please check latest code:

IsHandled := FALSE;
OnBeforeDeleteSalesQuote(Rec,SalesOrderHeader,IsHandled);
IF NOT IsHandled THEN BEGIN
  ApprovalsMgmt.DeleteApprovalEntries(RECORDID);
  DELETELINKS;
  DELETE;
  SalesQuoteLine.DELETEALL;
END;
