### ISSUE TITLE
[Event Request] Database::"Requisition Line" - Function "Unit of Measure Code" - OnValidate - OnValidateUnitofMeasureCodeOnBeforeGetDirectCost

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9540]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: "Unit of Measure Code" - OnValidate
Publisher Event: OnValidateUnitofMeasureCodeOnBeforeGetDirectCost
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            begin
                CheckActionMessageNew;
                if (Type = Type::Item) and
                   ("No." <> '') and
                   ("Prod. Order No." = '')
                then begin
                    GetItem;
                    "Unit Cost" := Item."Unit Cost";
                    "Overhead Rate" := Item."Overhead Rate";
                    "Qty. per Unit of Measure" := UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code");
                    if "Unit of Measure Code" <> '' then begin
                        "Qty. per Unit of Measure" := UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code");
                        "Unit Cost" := Round(Item."Unit Cost" * "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                    end else
                        "Qty. per Unit of Measure" := 1;
                end else
                    if "Prod. Order No." = '' then
                        "Qty. per Unit of Measure" := 1
                    else
                        "Qty. per Unit of Measure" := 0;

                **OnValidateUnitofMeasureCodeOnBeforeGetDirectCost(Rec, Item);**
                GetDirectCost(FieldNo("Unit of Measure Code"));
                if "Planning Line Origin" = "Planning Line Origin"::"Order Planning" then
                    SetSupplyQty("Demand Quantity (Base)", "Needed Quantity (Base)")
                else
                    Validate(Quantity);
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateUnitofMeasureCodeOnBeforeGetDirectCost(var RequisitionLine: Record "Requisition Line"; var Item: Record Item)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
