### ISSUE TITLE
[Event Request] Database::"Requisition Line" - Function SetReplenishmentSystemFromProdOrder - OnSetReplenishmentSystemFromProdOrderOnValidateUnitofMeasureCode

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9541]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: SetReplenishmentSystemFromProdOrder
Publisher Event: OnSetReplenishmentSystemFromProdOrderOnValidateUnitofMeasureCode
Reason: To implement custom business logic
Where is the event placed:
OnSetReplenishmentSystemFromProdOrderOnAfterSetProdFields(Rec, Item, Subcontracting);
        Validate("Transfer-from Code", '');
        **IsHandled := false;
        OnSetReplenishmentSystemFromProdOrderOnValidateUnitofMeasureCode(Rec, Item, Ishandled);
        if not IsHandled then**
            Validate("Unit of Measure Code", Item."Base Unit of Measure");
        if ("Planning Line Origin" = "Planning Line Origin"::"Order Planning") and ValidateFields then
            PlanningLineMgt.Calculate(Rec, 1, true, true, 0);
        OnAfterSetReplenishmentSystemFromProdOrder(Rec, Item);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnSetReplenishmentSystemFromProdOrderOnValidateUnitofMeasureCode(var Rec: Record "Requisition Line"; var Item: Record Item; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
