### ISSUE TITLE
[Event Request] Database::"Requisition Line" - Function SetReplenishmentSystemFromPurchase - OnSetReplenishmentSystemFromPurchaseOnBeforeValidateUnitofMeasureCode

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9542]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: SetReplenishmentSystemFromPurchase
Publisher Event: OnSetReplenishmentSystemFromPurchaseOnBeforeValidateUnitofMeasureCode
Reason: To implement custom business logic
Where is the event placed:
local procedure SetReplenishmentSystemFromPurchase(StockkeepingUnit: Record "Stockkeeping Unit")
    var
        IsHandled: Boolean;
    begin
        "Ref. Order Type" := "Ref. Order Type"::Purchase;
        Clear("Ref. Order Status");
        "Ref. Order No." := '';
        DeleteRelations;
        Validate("Production BOM No.", '');
        Validate("Routing No.", '');
        **IsHandled := false;
        OnSetReplenishmentSystemFromPurchaseOnBeforeValidateUnitofMeasureCode(Rec, Item, IsHandled);
        if not IsHandled then**
            if Item."Purch. Unit of Measure" <> '' then
                Validate("Unit of Measure Code", Item."Purch. Unit of Measure");
        Validate("Transfer-from Code", '');
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnSetReplenishmentSystemFromPurchaseOnBeforeValidateUnitofMeasureCode(var Rec: Record "Requisition Line"; var Item: Record Item; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
