### ISSUE TITLE
[Event Request] Database::"Warehouse Shipment Header" - Function SortWhseDoc - OnSortWhseDocCaseElse

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9543]
We like to request the following Event:
Object: Database::"Warehouse Shipment Header"
Function: SortWhseDoc
Publisher Event: OnSortWhseDocCaseElse
Reason: To implement custom business logic
Where is the event placed:
procedure SortWhseDoc()
    var
        WhseShptLine: Record "Warehouse Shipment Line";
        SequenceNo: Integer;
    begin
        WhseShptLine.SetRange("No.", "No.");
        case "Sorting Method" of
            "Sorting Method"::Item:
                WhseShptLine.SetCurrentKey("No.", "Item No.");
            "Sorting Method"::Document:
                WhseShptLine.SetCurrentKey("No.", "Source Document", "Source No.");
            "Sorting Method"::"Shelf or Bin":
                begin
                    GetLocation("Location Code");
                    if Location."Bin Mandatory" then
                        WhseShptLine.SetCurrentKey("No.", "Bin Code")
                    else
                        WhseShptLine.SetCurrentKey("No.", "Shelf No.");
                end;
            "Sorting Method"::"Due Date":
                WhseShptLine.SetCurrentKey("No.", "Due Date");
            "Sorting Method"::Destination:
                WhseShptLine.SetCurrentKey("No.", "Destination Type", "Destination No.");
            **else
                OnSortWhseDocCaseElse(Rec, WhseShptLine);**
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnSortWhseDocCaseElse(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseShipmentLine: Record "Warehouse Shipment Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
