### ISSUE TITLE
[Event Request] Database::"Whse. Internal Pick Line" - Function "Item No." - OnValidate - OnValidateItemNoOnBeforeSetItemFields

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9544]
We like to request the following Event:
Object: Database::"Whse. Internal Pick Line"
Function: "Item No." - OnValidate
Publisher Event: OnValidateItemNoOnBeforeSetItemFields
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
                **OnValidateItemNoOnBeforeSetItemFields(Rec, IsHandled);
                if not IsHandled then**
                    if "Item No." <> '' then begin
                        GetItemUnitOfMeasure;
                        Description := Item.Description;
                        "Description 2" := Item."Description 2";
                        "Shelf No." := Item."Shelf No.";
                        Validate("Unit of Measure Code", ItemUnitofMeasure.Code);
                    end else begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateItemNoOnBeforeSetItemFields(var WhseInternalPickLine: Record "Whse. Internal Pick Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
