### ISSUE TITLE
[Event Request] Database::"Whse. Internal Pick Line" - Function CreatePickDoc - OnCreatePickDockOnBeforeCreatePickFromWhseSource

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9545]
We like to request the following Event:
Object: Database::"Whse. Internal Pick Line"
Function: CreatePickDoc
Publisher Event: OnCreatePickDockOnBeforeCreatePickFromWhseSource
Reason: To implement custom business logic
Where is the event placed:
procedure CreatePickDoc(var WhseInternalPickLine: Record "Whse. Internal Pick Line"; WhseInternalPickHeader2: Record "Whse. Internal Pick Header")
    var
        CreatePickFromWhseSource: Report "Whse.-Source - Create Document";
        IsHandled: Boolean;
    begin
        WhseInternalPickHeader2.CheckPickRequired(WhseInternalPickHeader2."Location Code");
        WhseInternalPickHeader2.TestField(Status, WhseInternalPickHeader2.Status::Released);
        WhseInternalPickLine.SetFilter(Quantity, '>0');
        WhseInternalPickLine.SetFilter(
          Status, '<>%1', WhseInternalPickLine.Status::"Completely Picked");
        if WhseInternalPickLine.Find('-') then begin
            IsHandled := false;
            **OnCreatePickDockOnBeforeCreatePickFromWhseSource(WhseInternalPickLine, WhseInternalPickHeader2, HideValidationDialog, IsHandled);
            if not IsHandled then begin**
                CreatePickFromWhseSource.SetWhseInternalPickLine(
                WhseInternalPickLine, WhseInternalPickHeader2."Assigned User ID");
                CreatePickFromWhseSource.SetHideValidationDialog(HideValidationDialog);
                CreatePickFromWhseSource.UseRequestPage(not HideValidationDialog);
                CreatePickFromWhseSource.RunModal;
                CreatePickFromWhseSource.GetResultMessage(2);
                Clear(CreatePickFromWhseSource);
            end;
        end else
            if not HideValidationDialog then
                Message(Text005);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCreatePickDockOnBeforeCreatePickFromWhseSource(var WhseInternalPickLine: Record "Whse. Internal Pick Line"; var WhseInternalPickHeader2: Record "Whse. Internal Pick Header"; HideValidationDialog: Bool

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
