### ISSUE TITLE
[Event Request] Database::"Transfer Line" - CheckWarehouse- 	OnCheckWarehouseOnBeforeShowDialog

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9546]
We like to request the following Event:
Object: Database::"Transfer Line"
Function: CheckWarehouse
Publisher Event: OnCheckWarehouseOnBeforeShowDialog
Reason: To implement custom business logic
Where is the event placed:
        if Location."Require Shipment" then
                    DialogText := Location.GetRequirementText(Location.FieldNo("Require Shipment"))
                else
                    DialogText := Location.GetRequirementText(Location.FieldNo("Require Pick"));
            end;
        end;

        **OnCheckWarehouseOnBeforeShowDialog(Rec, Location, ShowDialog, DialogText);**

        case ShowDialog of
            ShowDialog::Message:
                Message(Text003 + Text004, DialogText, FieldCaption("Line No."), "Line No.");
            ShowDialog::Error:
                Error(Text003, DialogText, FieldCaption("Line No."), "Line No.");
        end;
    end;

Event Code:
    [IntegrationEvent(false, false)]
    local procedure OnCheckWarehouseOnBeforeShowDialog(TransferLine: Record "Transfer Line"; Location: Record Location; ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
