### ISSUE TITLE
[Event Request] Database::"Whse. Internal Put-away Line" - Function CreatePutAwayDoc - OnCreatePutAwayDocOnBeforeCreatePutAwayFromWhseSource

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9547]
We like to request the following Event:
Object: Database::"Whse. Internal Put-away Line"
Function: CreatePutAwayDoc
Publisher Event: OnCreatePutAwayDocOnBeforeCreatePutAwayFromWhseSource
Reason: To implement custom business logic
Where is the event placed:
procedure CreatePutAwayDoc(var WhseInternalPutAwayLine: Record "Whse. Internal Put-away Line")
    var
        CreatePutAwayFromWhseSource: Report "Whse.-Source - Create Document";
        IsHandled: Boolean;
    begin
        GetInternalPutAwayHeader("No.");
        WhseInternalPutAwayHeader.CheckPutawayRequired(WhseInternalPutAwayLine."Location Code");
        WhseInternalPutAwayHeader.TestField(
          Status, WhseInternalPutAwayHeader.Status::Released);
        WhseInternalPutAwayLine.SetFilter(Quantity, '>0');
        WhseInternalPutAwayLine.SetFilter(
          Status, '<>%1', WhseInternalPutAwayLine.Status::"Completely Put Away");
        if WhseInternalPutAwayLine.Find('-') then begin
            **IsHandled := false;
            OnCreatePutAwayDocOnBeforeCreatePutAwayFromWhseSource(WhseInternalPutAwayHeader, HideValidationDialog, IsHandled);
            if IsHandled then begin**
                CreatePutAwayFromWhseSource.SetWhseInternalPutAway(WhseInternalPutAwayHeader);
                CreatePutAwayFromWhseSource.SetHideValidationDialog(HideValidationDialog);
                CreatePutAwayFromWhseSource.UseRequestPage(not HideValidationDialog);
                CreatePutAwayFromWhseSource.RunModal;
                CreatePutAwayFromWhseSource.GetResultMessage(1);
                Clear(CreatePutAwayFromWhseSource);
            end;
        end else
            if not HideValidationDialog then
                Message(Text006);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCreatePutAwayDocOnBeforeCreatePutAwayFromWhseSource(var WhseInternalPutAwayHeader: Record "Whse. Internal Put-away Header"; HideValidationDialog: Boolean; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
