### ISSUE TITLE
[Event Request] Database::"Whse. Worksheet Line" - Function GetSortSeqNo - OnGetSortSeqNoOnCaseElse

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9548]
We like to request the following Event:
Object: Database::"Whse. Worksheet Line"
Function: GetSortSeqNo
Publisher Event: OnGetSortSeqNoOnCaseElse
Reason: To implement custom business logic
Where is the event placed:
SortMethod::"Due Date":
                WhseWorksheetLine2.SetCurrentKey(
                  "Worksheet Template Name", Name, "Location Code", "Due Date");
            SortMethod::"Ship-To":
                WhseWorksheetLine2.SetCurrentKey(
                  "Worksheet Template Name", Name, "Location Code", "Destination Type", "Destination No.")
            **else
                OnGetSortSeqNoOnCaseElse(WhseWorksheetLine2, SortMethod);**
        end;
      
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnGetSortSeqNoOnCaseElse(var WhseWorksheetLine: Record "Whse. Worksheet Line"; SortMethod: Option)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
