### ISSUE TITLE
[Event Request] Database::"Whse. Worksheet Line" - Function SortWhseWkshLines - OnSortWhseWkshLinesOnCaseElse

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9549]
We like to request the following Event:
Object: Database::"Whse. Worksheet Line"
Function: SortWhseWkshLines
Publisher Event: OnSortWhseWkshLinesOnCaseElse
Reason: To implement custom business logic
Where is the event placed:
SortingMethod::"Due Date":
                WhseWkshLine.SetCurrentKey(
                  "Worksheet Template Name", Name, "Location Code", "Due Date");
            SortingMethod::"Ship-To":
                WhseWkshLine.SetCurrentKey(
                  "Worksheet Template Name", Name, "Location Code", "Destination Type", "Destination No.");
            **else
                OnSortWhseWkshLinesOnCaseElse(WhseWkshLine, SortingMethod);**
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnSortWhseWkshLinesOnCaseElse(var WhseWorksheetLine: Record "Whse. Worksheet Line"; SortingMethod: Option)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
