### ISSUE TITLE
[Event Request] Codeunit 1002 - Job Create-Invoice - OnCreateSalesInvoiceLinesTestJob(Job)

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/ALAppExtensions#955]
Dear AL team,

Through this issue we would like to request the following event-publisher to be added in codeunit 1002 Job Create-Invoice:
```
OnCreateSalesInvoiceLinesTestJob(VAR Job : Record Job)
```
Which would be called from the `CreateSalesInvoiceLines` procedure, as shown below:
```pascal
[External] CreateSalesInvoiceLines(JobNo : Code[20];VAR JobPlanningLine : Record "Job Planning Line";InvoiceNo : Code[20];NewInvoice : Boolean;PostingDate : Date;CreditMemo : Boolean)
OnBeforeCreateSalesInvoiceLines(JobPlanningLine,InvoiceNo,NewInvoice,PostingDate,CreditMemo);

CLEARALL;
Job.GET(JobNo);
OnCreateSalesInvoiceLinesTestJob(Job); // <- Call to new event
IF Job.Blocked = Job.Blocked::All THEN
  Job.TestBlocked;
IF Job."Currency Code" = '' THEN
  JobInvCurrency := Job."Invoice Currency Code" <> '';
Job.TESTFIELD("Bill-to Customer No.");

IsHandled := FALSE;
OnCreateSalesInvoiceLinesOnBeforeGetCustomer(JobPlanningLine,Cust,IsHandled);
IF NOT IsHandled THEN
  Cust.GET(Job."Bill-to Customer No.");
```

**Edit**: I now see that `CreateSalesInvoice` passes JobPlanningLine."Job No." as well as the JobPlanningLine itself. If this is always expected to happen, then maybe the `CreateSalesInvoiceLines` parameter-list could be edited/simplified alternatively without introducing this event?

**Comment by AlexanderYakunin** [comment]
We already have this event

**Comment by rvanbekkum** [comment]
It's not there, at least not when looking at in application build 27306 (W1, 14.0.27164).
We need an event that gives us the **JobNo** passed to the procedure.

**Comment by rvanbekkum** [comment]
There is no event in place for this that gives access to the `JobNo` variable in the `CreateSalesInvoiceLines` procedure in application build 28593 (W1, 14.0.28496.0).
