### ISSUE TITLE
[Event Request] Page 407 Resource Picture - OnImportPictureBeforeStoreFile

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/ALAppExtensions#9551]
Please add a new publisher event to the function ImportPicture - OnAction() as follows:

.
.
FileName := FileManagement.UploadFile(SelectPictureTxt, ClientFileName);
if FileName = '' then
    exit;

//>> Start New Publisher Call
OnImportPictureBeforeStoreFile(Rec, FileName);
//<< End New Publisher Call
 
Clear(Image);
Image.IMPORTFILE(FileName, ClientFileName);
Modify(true);
.
.
New Publisher Event:

LOCAL [IntegrationEvent] OnImportPictureBeforeStoreFile(VAR Resource: Record Resource; FileName : Text)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
