### ISSUE TITLE
codeunit 8888 "Email Dispatcher" - OnAfterSendMail

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#9553]
Can we please get the following event?
I would really appreciate it if you add the Codeunit (where you place this event). If I understood the Access-Property correct then events of internal codeunits aren't availabe outside..?
```al
trigger OnRun()
var
    EmailMessage: Record "Email Message";
    SendEmail: Codeunit "Send Email";
begin
    
    ...

    if EmailMessageImpl.Get(Rec."Message Id") then begin
        LogAttachments();

        SendEmail.SetConnector(Rec.Connector);
        SendEmail.SetAccount(Rec."Account Id");

        EmailMessageImpl.GetEmailMessage(EmailMessage);
        Success := SendEmail.Run(EmailMessage);
        OnAfterSendMail(Rec, Success);
         ...

    end;
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnAfterSendMail(var EmailOutbox: Record "Email Outbox"; Status: Boolean )
begin
end;
```

**Comment by JesperSchulz** [comment]
Again, a little context would go a long way. Reason is, that we're trying to approach extensibility with a little more care in the new  modules, than we've been used to in the Base Application. Often, understanding the scenario allows for better extensibility design. Putting in events left, right and center in all of our code in the system application will quickly put us in a bad state again wrt. to refactoring of our implementation details etc.

**Comment by GiorgosPa** [comment]
A similar event was added
@pri-kise thank you for your suggestion, we have implemented it a little bit differently. I hope it suits your needs.

```
    /// <summary>
    /// Integration event that notifies senders about whether their email was successfully sent in the background.
    /// </summary>
    /// <param name="MessageId">The ID of the email in the queue.</param>
    /// <param name="Status">True if the message was successfully sent.</param>
    [IntegrationEvent(false, false)]
    internal procedure OnAfterSendEmail(MessageId: Guid; Status: Boolean)
    begin
    end;
```
