### ISSUE TITLE
[Event Request] Page 46 Sales Order Subform - OnNoAfterValidateCheckVariant

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9554]
Hi Team,

In Page 46 we need possibility to have our additional checks. Having event in procedure `NoOnAfterValidate` would be a perfect solution. Requesting additional parameters in existing publisher `OnNoOnAfterValidateOnBeforeSaveAndAutoAsmToOrder` does not suit us, because it is before SaveAndAutoAsmToOrder procedure :

![image](https://user-images.githubusercontent.com/70525691/96863692-ee7c9700-146f-11eb-90a0-20731b820b9e.png)

    [IntegrationEvent(false, false)]
    local procedure OnNoAfterValidateCheckVariant(var SalesLine: Record "Sales Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
