### ISSUE TITLE
New Event in Report 952 "Suggest Job Jnl. Lines"

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#9555]
Requesting a new event  in the trigger OnPostReport   
trigger OnPostReport()
    var
        NoSeriesMgt: Codeunit NoSeriesManagement;
        TimeSheetMgt: Codeunit "Time Sheet Management";
        NextDocNo: Code[20];
        LineNo: Integer;
        QtyToPost: Decimal;
    begin
        DateFilter := TimeSheetMgt.GetDateFilter(StartingDate, EndingDate);
        FillTimeSheetLineBuffer;

		...
                            OnAfterTransferTimeSheetDetailToJobJnlLine(JobJnlLine, JobJnlTemplate, TempTimeSheetLine, TimeSheetDetail, JobJnlBatch);
                            JobJnlLine.Insert();
                        end;
                    until TimeSheetDetail.Next = 0;
					OnAfterInsertJobJnlLine(JobJnlLine, NextDocNo, LineNo); //New Event
            until TempTimeSheetLine.Next = 0;
        end;
    end;

[IntegrationEvent] OnAfterInsertJobJnlLine(VAR JobJournalLine : Record "Job Journal Line";VAR NextDocNo : Code[20];VAR LineNo : Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
