### ISSUE TITLE
[Event Request] codeunit 4514 "SMTP Message" - OnBeforeAddToInternetAddressList

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#9557]
Can we please get the following event.
```al
local procedure AddToInternetAddressList(InternetAddressList: DotNet InternetAddressList; Recipients: List of [Text])
begin
        OnBeforeAddToInternetAddressList(Recipients); //NEW
	if not TryParseInternetAddressList(InternetAddressList, Recipients) then begin
		Session.LogMessage('0000B5M', StrSubstNo(RecipientErr, FormatListToString(Recipients)), Verbosity::Error, DataClassification::EndUserPseudonymousIdentifiers, TelemetryScope::ExtensionPublisher, 'Category', SmtpCategoryLbl);
		Error(RecipientErr, FormatListToString(Recipients));
	end;
end;
```

```al
[IntegrationEvent(false,false)]
local procedure OnBeforeAddToInternetAddressList(var Recipients: List of [Text])
begin
end;
```

**Comment by mazhelez** [comment]
Hey @pri-kise 

The event looks suspicious. If you want to modify the list of recipients, it's not a good idea to do it so late in the game.

What are your desired results? Maybe there's another way to achieve them. :)

**Comment by pri-kise** [comment]
We want to be able to change the recipients this late in one specific scenario:
For OnPrem Development to set a test@email and avoid emails are sent to real customers.

**Comment by JesperSchulz** [comment]
Related issue #9562 closed, as workaround was provided. If this issue persists, could you open a new issue for us? Then we'll give it another go.
