### ISSUE TITLE
[Extensibility Request] table 8888 "Email Outbox" - Add Getter Functions

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#9558]
Could you please add some Getter Functions to table "Email Outbox". and the Table "Sent Email"?

```al
procedure GetMessageId(var MessageId: Guid)
begin
    MessageId:= Rec."Account Id";
end;
procedure GetAccountId(var AccountId: Guid)
begin
    AccountId := Rec."Account Id";
end;
procedure GetUserSecurityId(var UserSecurityId: Guid)
begin
    UserSecurityId:= Rec."User Security Id";
end;
procedure GetConnector():Enum "Email Connector"
begin
    exit(Rec.Connector);
end;
procedure GetEmailStatus(): Enum "Email Status"
begin
    exit(Rec.Status);
end;
procedure GetDescription(): Text[2048]
begin
    exit(Rec.Description);
end;
procedure GetErrorMessage(): Text[2048]
begin
    exit(Rec."Error Message");
end;
procedure GetDateQueued(): DateTime
begin
    exit(Rec."Date Queued");
end;
procedure GetDateFailed(): DateTime
begin
    exit(Rec."Date Failed");
end;
procedure GetDateQueued(): DateTime
begin
    exit(Rec."Date Queued");
end;
procedure GetSendFrom(): Text[250]
begin
    exit(Rec."Send From");
end;
```

**Comment by dtkb** [comment]
What is the use of such getters on a record, where the fields are already publicly accessible?

**Comment by pri-kise** [comment]
I'm using the latest insider preview for BC17 (System.Application: 17.1.17933.0)  where those fields are set Access=Internal. 
https://github.com/microsoft/ALAppExtensions/blob/2ce8069cae5e9ac3929998b57d6b2785a59e4572/Modules/System/Email/src/Email/Outbox/EmailOutbox.Table.al#L22
The table is set to Access=Public (https://github.com/microsoft/ALAppExtensions/blob/2ce8069cae5e9ac3929998b57d6b2785a59e4572/Modules/System/Email/src/Email/Outbox/EmailOutbox.Table.al#L9), but the fields are accesibly for me
![image](https://user-images.githubusercontent.com/56249171/96961675-7365c000-1505-11eb-8799-199cd8041542.png)

If the Access=Internal is removed this would be fine, too.

**Comment by mazhelez** [comment]
Hey @pri-kise 

May I ask your intentions behind the getters? What is that you are trying to build? Do you really need to read all the fields or just the _Date Queued_?

**Comment by pri-kise** [comment]
We want to provide notifications to the user about faild outbox items and therefore we want to add some information about the specific entries that failed.

**Comment by mazhelez** [comment]
@pri-kise  Great! 👍 

And how do you feel about opening a PR with the desired getters? 😃

**Comment by pri-kise** [comment]
@mazhelez I will try my best.

**Comment by JesperSchulz** [comment]
As a PR was opened, we should continue discussion in the PR. Closing this issue to avoid parallel discussions.

**Comment by JesperSchulz** [comment]
Link to PR: #9613
