### ISSUE TITLE
Non-Inventoriable items on codeunit Release Service Document (COD 416)

### ISSUE THREAD

**Issue by jorgecorreia27** [microsoft/ALAppExtensions#9559]
Good afternoon. In the course of a development, we found an isue in the Service Module. When we try to release a Service Order the system will check for the Location Code in the Service Line table (5902). However, if we want to select for the Service Order an Item of type = Service (which is Non-Inventoriable) the validation for the Location Code does not make sense to be executed. Making a comparison with the action of release in the Release Sales Order action (COD414), the validation that is present is that the Location Code validation should only exist for items of type Inventoriable. In the ServiceLine table there is a function to check if the item is Non-Inventoriable, so, the soulution would be something like this:
[Behaviour of the Release Sales Order action with evidence to the Inventority of the Sales Header (COD414)] 
![image](https://user-images.githubusercontent.com/37341299/96888523-9ea4cc80-147d-11eb-9553-8aaddbad9546.png)
[The same behaviour does not exist int the Service Order Release Action (COD416)]
![image](https://user-images.githubusercontent.com/37341299/96888816-ec213980-147d-11eb-9779-181be60f2a9a.png)
[Suggested solution for the problem in evidence (COD416)]
![image](https://user-images.githubusercontent.com/37341299/96889009-17a42400-147e-11eb-840b-37adb758111e.png)
We would like to ask you if in a future release a fix like the suggested solution could be shipped.
Thank you and best regards
Jorge Correia

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
