### ISSUE TITLE
event request - codeunit 1210 "Payment Export Mgt" - ProcessColumnMapping() - OnAfterGetValueAsStringBeforeCheckLength(var ValueAs String...)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9560]
The Background/Rant
=

Codeunits implementing Data Exchange, such as the Mapping Codeunit filled out on the Data Exch Field Mappings page, all seem to reinvent the same wheels to just use the generic Data Exch features to map/transform text. This includes `Payment Export Mgt`, which is what converts a value from e.g. a Gen Journal Line to a Data Exch value to be exported to a file.

Each of these reinventions of the same wheel seems to be a slight copy of the others, but each missing some key bit. In this case, Payment Export Mgt, via `FormatToText()`, doesn't make any effort to apply whatever Transformation Rule we have set up on the Data Exch Field Mapping. We need this because we have to truncate text to 18 characters or get an error, at this precise moment in time, but it's likely we'll need other/'real' transformations.

The Actually Useful Bit
=

So, before all these similar-but-different implementations of using Data Exch setups to map/convert values are consolidated into one place ;-) ... please can you add the following event publisher?

    procedure ProcessColumnMapping(DataExch: Record "Data Exch."; RecRef: RecordRef; LineNo: Integer; DataExchLineDefCode: Code[20]; TableID: Integer)
    [...]
        DataExchFieldMapping.FindSet;

        repeat
            DataExchColumnDef.Get(DataExchDef.Code, DataExchLineDefCode, DataExchFieldMapping."Column No.");

            if DataExchFieldMapping."Use Default Value" then
                ValueAsString := DataExchFieldMapping."Default Value"
            else begin
                FieldRef := RecRef.Field(DataExchFieldMapping."Field ID");
                CheckOptional(DataExchFieldMapping.Optional, FieldRef);
                CastToDestinationType(ValueAsDestType, FieldRef.Value, DataExchColumnDef, DataExchFieldMapping.Multiplier);
                ValueAsString := FormatToText(ValueAsDestType, DataExchDef, DataExchColumnDef);
                if DataExchColumnDef."Text Padding Required" and (DataExchColumnDef."Pad Character" <> '') then
                    ValueAsString :=
                        StringConversionManagement.GetPaddedString(
                            ValueAsString,
                            DataExchColumnDef.Length,
                            DataExchColumnDef."Pad Character",
                            DataExchColumnDef.Justification);
            end;

            // <NEW>
            OnAfterGetValueAsStringBeforeCheckLength(ValueAsString, DataExchFieldMapping, DataExchColumnDef);
            // </NEW>

            CheckLength(ValueAsString, RecRef.Field(DataExchFieldMapping."Field ID"), DataExchDef, DataExchColumnDef);

            DataExchField.Get(DataExch."Entry No.", LineNo, DataExchFieldMapping."Column No.");
            DataExchField.Value := ValueAsString;
            DataExchField.Modify();
        until DataExchFieldMapping.Next = 0;
    end;

where that new event looks like

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetValueAsStringBeforeCheckLength(var ValueAsString: Text[250]; DataExchFieldMapping: Record "Data Exch. Field Mapping"; DataExchColumnDef: "Data Exch. Column Def")

i.e. passes `var ValueAsString` - so that we can intercept, check those Data Exchange setup recs, apply Transformation Rules, and whatever else was missed by the base code from the Data Exch tables, to ensure required transformations are made and/or avoid length errors.

Thanks!

**Comment by dtkb** [comment]
This could alternatively go after the assignment `ValueAsString := FormatAsText(...)` and be called e.g. `OnAfterFormatToTextBeforePadding()`. It depends what MS consider the 'correct' order for the various Data Exch operations, I guess. The differences there would be:
* The event would not be omitted if `Use Default Value` was `true`.
* The `Transformation Rule` would then be applied before adding `Text Padding`, not after.

That's where/how I did it in our current extension that 'overrides' these objects to make `Export Generic CSV` work how we want:

![image](https://user-images.githubusercontent.com/63455896/97010351-30274380-153d-11eb-9c3d-c7248879ccdd.png)

It would then be

    [IntegrationEvent(false, false)]
    local procedure OnAfterFormatToTextBeforePadding(var ValueAsString: Text[250]; DataExchFieldMapping: Record "Data Exch. Field Mapping"; DataExchColumnDef: "Data Exch. Column Def")

Any opinions on which approach is better? I think my vote would now go to _this_ one.

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
