### ISSUE TITLE
event request - xmlport 1230 "Export Generic CSV" - OnPreXmlPortOnAfterGetDataExchDef(var sender, DataExchDef)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9561]
related: #5477

We need a way to override properties such as `FieldDelimiter` and ideally others, initially just on a whole-database basis, but ideally per Data Exchange Def, to implement missing setup options/features that the standard object lacks

The current need is to avoid the double quotes around all fields, due to the standard not-set `FieldDelimiter` property, which [apparently](https://dynamicsuser.net/nav/f/developers/66844/variable-text-without-a-field-delimiter) means 'double-quote everything'... which will not work for various clients, whose systems are very picky and will barf on such quotes.

Please therefore let us configure `currXMLport` in `OnPreXmlPort()`, something like this:

    trigger OnPreXmlPort()
    begin
        InitializeGlobals;

        // <NEW>
        // Above sets DataExchEntryNo, then:
        if DataExch.Get(DataExchEntryNo) then
            if DataExchDef.Get(DataExch."Data Exch. Def Code") then
                OnPreXmlPortOnAfterGetDataExchDef(DataExchDef);
        // </NEW>
    end;

where that publisher will look like

    [IntegrationEvent(true, false)]
    local procedure OnPreXmlPortOnAfterGetDataExchDef(DataExchDef: Record "Data Exch. Def");

and we can then subscribe to it and do something like

    local procedure MySubscriberOnPreXmlPortOnAfterGetDataExchDef(var sender: XMLport "Export Generic CSV"; DataExchDef: Record "Data Exch. Def")
    begin
        sender.FieldDelimiter('<None>');
        // or, etc.
        sender.FieldDelimiter(DataExchDef."Field Delimiter");
    end;

**Comment by dtkb** [comment]
fixed the order: `InitializeGlobals()` sets `DataExchEntryNo`, which we then use to get the `DataExch`/`Def` that the subscriber will need

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
