### ISSUE TITLE
[Event Request]  codeunit 4509 "Email - Outlook API Helper" - OnAfterEmailMessageToJson

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#9562]
Can we please get the following event?
```al
procedure EmailMessageToJson(EmailMessage: Codeunit "Email Message"; Account: Record "Email - Outlook Account"): JsonObject
var
	EmailMessageJson: JsonObject;
	EmailAddressJson: JsonObject;
	FromJson: JsonObject;
	MessageJson: JsonObject;
	EmailBody: JsonObject;
begin
	
	....
	OnAfterEmailMessageToJson(EmailMessage, Account, MessageJson);
	exit(MessageJson);
end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnAfterEmailMessageToJson(EmailMessage: Codeunit "Email Message"; Account: Record "Email - Outlook Account"; var MessageJson: JsonObject)
begin
end;
```

**Comment by JesperSchulz** [comment]
Could you explain what you would need that event for? Intercepting the email sending process at this stage is rather late. Also, this event would only work if the email is sent through Exchange. If SMTP or any other connector would be used, this event would never be raised. A little context would be needed before we proceed here :-)

**Comment by pri-kise** [comment]
We want to have to possibilty to enable a test mode, where e-mails are sent to a fixed e-mail.
Escpecially for test instances that are copies of a production environment. 
In a test environment Mails should never being sent to real customers.
Therefore I requested one event for this default connector and one for the SMTP Connector (#9557);

**Comment by mazhelez** [comment]
@pri-kise would consider using a mock connector instead?

You can see how [ConnectorMock](https://github.com/microsoft/ALAppExtensions/blob/master/Modules/System%20Test%20Libraries/Email/src/ConnectorMock.Codeunit.al) was implemented and how it's used. It might help.

**Comment by pri-kise** [comment]
I thought about using a "Test/Mock Connecot", but to work with a copy of production environment as  test environment I would need any possiblity to bulk change the connector of existing email outbox entries.
At the moment it isn't possible to change the connector of still existing 
Since there might be still some when the database gets copied.
Or some way to change the connector that is used for any email outbox entry (https://github.com/microsoft/ALAppExtensions/blob/2ce8069cae5e9ac3929998b57d6b2785a59e4572/Modules/System/Email/src/Email/EmailDispatcher.Codeunit.al#L39)

**Comment by mazhelez** [comment]
Hi again @pri-kise 

So in SaaS, when copying production to sandbox environment, all the email outbox and sent email entries are deleted.
You can achieve the same, calling `OnAfterCopyEnvironmentToSandbox` from codeunit _Environment Triggers_. (see Sandbox Cleanup module).

And for tests you can generate email outbox entries that use the mock connector.

Let me know if I missed something!

**Comment by JesperSchulz** [comment]
Also related to #9557.

**Comment by darjoo** [comment]
Hi @pri-kise,
Does Maria's suggestion work for you? and would that work for you in regards to #9557 as well?

**Comment by pri-kise** [comment]
I haven't had the time to test this workaround, but I guess it should work.
I'm still struggling to find the the best place to replace the current connector of any E-Mail Scenario with a "Mock Connector".

**Comment by JesperSchulz** [comment]
Doing some house keeping... As the workaround _should_ work, I will go ahead and close this issue. If the issue persists, could you open a new issue for us? Then we'll give it another go. Will also close related issue #9557 for now.
