### ISSUE TITLE
Codeunit 1535 Approvals Mgmt - New Publisher OnBeforePostedApprovalCommentLineInsert

### ISSUE THREAD

**Issue by GertKr** [microsoft/ALAppExtensions#9563]
We would like to have a new publisher OnBeforePostedApprovalCommentLineInsert in procedure PostApprovalCommentLines to be able to fill a field we added in the Posted Approval Comment Lines (457) 

Signature:
LOCAL [IntegrationEvent] OnBeforePostedApprovalCommentLineInsert(VAR PostedApprovalCommentLine : Record "Posted Approval Comment Line";ApprovalCommentLine : Record "Approval Comment Line")

Procedure with publisher
![image](https://user-images.githubusercontent.com/69420950/96977584-9308e280-151d-11eb-95a5-ba54a77d8d1a.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
