### ISSUE TITLE
Migrate Status of 5875 "Phys. Invt. Order Header" from Option to Enum

### ISSUE THREAD

**Issue by ahenkel** [microsoft/ALAppExtensions#9564]
field(11; Status; Option)
        {
            Caption = 'Status';
            Editable = false;
            OptionCaption = 'Open,Finished';
            OptionMembers = Open,Finished;
        }

needs to be an enum to extend status with new options like release or canceled

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
