### ISSUE TITLE
[Event Request] OnBeforeSetInsertDocNoLine in Copy Document Mgt.

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#9566]
Please, add an event publisher like the following to the codeunit 6620 Copy Document Mgt.:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetInsertDocNoLine(FromSalesShptLine: Record "Sales Shipment Line"; var OldDocNo: Code[20]; var InsertDocNoLine: Boolean; var IsHandled: Boolean)
    begin
    end;
```

and raise it inside the CopySalesShptLinesToDoc procedure like so:

```
    procedure CopySalesShptLinesToDoc(...)
    var
        [...]
        IsDocNoLineHandled: Boolean;
    begin
        [...]
                    OnBeforeSetInsertDocNoLine(FromSalesShptLine, OldDocNo, InsertDocNoLine, IsDocNoLineHandled);
                    if (not IsDocNoLineHandled) then
                        if "Document No." <> OldDocNo then begin
                            OldDocNo := "Document No.";
                            InsertDocNoLine := true;
                        end;
        [...]
    end;
```

Consider doing the same thing for these procedures too:

- `CopySalesReturnRcptLinesToDoc`
- `CopyPurchRcptLinesToDoc`
- `CopyPurchReturnShptLinesToDoc`

Thank you

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
