### ISSUE TITLE
event request - codeunit 1277 "Exp. External Data Gen. Jnl." - OnRunOnBeforeExport(DataExch, var FileName, var Handled)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9567]
Please can we have a way to set the filename used here? We need this to overcome some problems/shortcomings:
* We would like the file to be named after the `Data Exch Def` and/or `Line Def` records' `Name`s instead of `Code`s.
* This hardcodes the file name extension to `.txt`, but we want it to default to `.csv` sometimes, for clients who can't or won't rename the file themselves; it shouldn't be needed
* We found that the `Line Def Code` may be empty, resulting in a space between `DEDEFCODE .txt`

It would also be nice to use the `Handled` pattern so that we could export via some means other than a file, although we don't have a use for that yet, but it seems worth adding.

Please therefore change from

    trigger OnRun()
    [...]
        if FileMgt.BLOBExport(TempBlob, "Data Exch. Def Code" + ' ' + "Data Exch. Line Def Code" + TxtExtTok, true) = '' then
            Error(DownloadFromStreamErr);
    end;

to something like 

    trigger OnRun()
    [...]
        FileName := "Data Exch. Def Code" + ' ' + "Data Exch. Line Def Code" + TxtExtTok;

        OnRunOnBeforeExport(Rec, FileName, Handled);

        if Handled then
            exit;

        if FileMgt.BLOBExport(TempBlob, FileName, true) = '' then
            Error(DownloadFromStreamErr);
    end;

where that event is published as

    [EventPublisher(false, false)]
    local procedure OnRunOnBeforeExport(DataExch: Record "Data Exch."; var FileName: Text; var Handled: Boolean);

thus letting us override the default `FileName` or do something else entirely via `Handled`.

Thanks!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
