### ISSUE TITLE
[Event Request] Table 36 Sales Header - OnHandleSupplementTypeOnRecreateSalesLines

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9568]
Hi Team,

In Table 36 we need possibility to have our additional checks and/or skip standard code. Having event with handling in procedure `RecreateSalesLines` would be a perfect solution : 

![image](https://user-images.githubusercontent.com/70525691/97009599-f5c5a280-154c-11eb-8ff9-ff696ddafac4.png)

    [IntegrationEvent(false, false)]
    local procedure OnHandleSupplementTypeOnRecreateSalesLines(var TempSalesLine: Record "Sales Line" temporary; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
