### ISSUE TITLE
[Event Request] Table 5965 "Service Contract Header" - OnBeforeGetNoSeries

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#9569]
Hi Team,

In table 5965 "Service Contract Header", we need to have additional check for No.Series in the "AssitEdit" procedure. Adding an event with handling in this procedure will work great for us.

![image](https://user-images.githubusercontent.com/61985025/97012488-bcfddd00-14fc-11eb-9aac-22f7c64d092b.png)

procedure AssistEdit(OldServContract: Record "Service Contract Header"): Boolean
 begin
        with ServContractHeader do begin
            ServContractHeader := Rec;
            if NoSeriesMgt.SelectSeries(GetNoSeriesCode(), OldServContract."No. Series", "No. Series") then begin
                NoSeriesMgt.SetSeries("Contract No.");
                Rec := ServContractHeader;
                exit(true);
            end;
        end;
        OnAfterAssistEdit(OldServContract);
  end;

  local procedure GetNoSeriesCode(): Code[20]
  var
        NoSeriesCode: Code[20];
        IsHandled: Boolean;
   begin
        IsHandled := false;
        OnBeforeGetNoSeries(Rec, NoSeriesCode, IsHandled);
        if IsHandled then
            exit(NoSeriesCode);
        ServMgtSetup.Get();
        ServMgtSetup.TestField("Service Contract Nos.");
        exit(ServMgtSetup."Service Contract Nos.");
   end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetNoSeries(var ServiceContractHeader: Record "Service Contract Header"; var NoSeriesCode: Code[20]; var IsHandled: Boolean)
begin
end;

Thanks.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
