### ISSUE TITLE
[Event Request] Table 39 Purchase Line - OnUpdateUnitCostAndAmountOnValidateLineDiscountAmount

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9570]
Hi Team,

In Table 39 we need possibility to have our additional checks and/or avoid using standard code. Having event with handling on `OnValidate` trigger on field `"Line Discount Amount"` would be a perfect solution: 

![image](https://user-images.githubusercontent.com/70525691/97014477-08db7100-1553-11eb-8144-0eea165e560d.png)

    [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostAndAmountOnValidateLineDiscountAmount(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
