### ISSUE TITLE
[Event Request] Table 39 Purchase Line - OnUpdateUnitCostAndAmountOnValidateLineDiscountPercent

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9571]
Hi Team,

In Table 39 we need possibility to have our additional checks and/or avoid using standard code. Having event with handling in procedure `ValidateLineDiscountPercent` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/97015625-74720e00-1554-11eb-87b1-a0d5532cf22c.png)

    [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostAndAmountOnValidateLineDiscountPercent(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
