### ISSUE TITLE
[Additional Parameter Request] Table 39, Purchase Line, OnValidateQuantityOnBeforePurchaseLineVerifyChange

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9572]
Hi Team,

In Table 39 we need possibility to have additional checks in the trigger Quantity-OnValidate before WhseValidateSourceLine.PurchaseLineVerifyChange is called. Standard publisher requested in issue #7931 would suit us if additional parameter  `var xRec: Record "Purchase Line"` is added:

![image](https://user-images.githubusercontent.com/70525691/97020304-0fb9b200-155a-11eb-9f15-94558d765257.png)

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnBeforePurchaseLineVerifyChange(var Rec: Record "Purchase Line"; StatusCheckSuspended: Boolean; var xRec: Record "Purchase Line"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
