### ISSUE TITLE
[Event Request] Report::"Calc. Consumption" - Function CreateConsumpJnlLine - OnBeforeSetQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9574]
We like to request the following Event:
Object: Report::"Calc. Consumption"
Function: CreateConsumpJnlLine
Publisher Event: OnBeforeSetQuantity
Reason: To implement custom business logic
Where is the event placed:
ItemJnlLine.Description := "Prod. Order Component".Description;
            IsHandled := false;
            OnBeforeSetQuantity(ItemJnlLine, "Prod. Order Component", QtyToPost, IsHandled);
            if not IsHandled then
                if Item."Rounding Precision" > 0 then
                    ItemJnlLine.Validate(Quantity, UOMMgt.RoundToItemRndPrecision(QtyToPost, Item."Rounding Precision"))
                else
                    ItemJnlLine.Validate(Quantity, UOMMgt.RoundQty(QtyToPost));
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetQuantity(var ItemJnlLine: Record "Item Journal Line"; ProdOrderComponent: Record "Prod. Order Component"; QtyToPost: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
