### ISSUE TITLE
[Event Request] Report::"Calc. Consumption" - Function CreateConsumpJnlLine - OnBeforeUpdateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9575]
We like to request the following Event:
Object: Report::"Calc. Consumption"
Function: CreateConsumpJnlLine
Publisher Event: OnBeforeUpdateQuantity
Reason: To implement custom business logic
Where is the event placed:
then begin
            **IsHandled := false;
            OnBeforeUpdateQuantity(ItemJnlLine, "Prod. Order Component", QtyToPost, IsHandled);
            if not IsHandled then**
                if Item."Rounding Precision" > 0 then
                    ItemJnlLine.Validate(Quantity, ItemJnlLine.Quantity + UOMMgt.RoundToItemRndPrecision(QtyToPost, Item."Rounding Precision"))
                else
                    ItemJnlLine.Validate(Quantity, ItemJnlLine.Quantity + UOMMgt.RoundQty(QtyToPost));
            OnBeforeItemJnlLineModify(ItemJnlLine, "Prod. Order Component");
            ItemJnlLine.Modify();
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateQuantity(var ItemJnlLine: Record "Item Journal Line"; ProdOrderComponent: Record "Prod. Order Component"; QtyToPost: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
