### ISSUE TITLE
[Event Request] Report::"Copy Purchase Document" - Function ValidateDocNo - OnValidateDocNoOnBeforeFindFromPuchaseHeaderArchive

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9576]
We like to request the following Event:
Object: Report::"Copy Purchase Document"
Function: ValidateDocNo
Publisher Event: OnValidateDocNoOnBeforeFindFromPuchaseHeaderArchive
Reason: To implement custom business logic
Where is the event placed:
DocType::"Arch. Quote",
                    DocType::"Arch. Order",
                    DocType::"Arch. Blanket Order",
                    DocType::"Arch. Return Order":
                        begin
                            **IsHandled := false;
                            OnValidateDocNoOnBeforeFindFromPuchaseHeaderArchive (FromPurchHeaderArchive, DocType, DocNo, DocNoOccurrence, DocVersionNo, IsHandled);
                            if not IsHandled then**
                                if not FromPurchHeaderArchive.Get(
                                     CopyDocMgt.ArchPurchHeaderDocType(DocType), DocNo, DocNoOccurrence, DocVersionNo)
                                then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateDocNoOnBeforeFindFromPuchaseHeaderArchive (var FromPurchHeaderArchive: Record "Purchase Header Archive"; DocType: Option Quote,"Blanket Order","Order",Invoice,"Return Order","Credit Memo","Posted Receipt","Post

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
