### ISSUE TITLE
[Event Request] Report::"Copy Sales Document" - Function ValidateDocNo - OnValidateDocNoOnBeforeFindFromSalesHeaderArchive

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9577]
We like to request the following Event:
Object: Report::"Copy Sales Document"
Function: ValidateDocNo
Publisher Event: OnValidateDocNoOnBeforeFindFromSalesHeaderArchive
Reason: To implement custom business logic
Where is the event placed:
DocType::"Arch. Quote",
                    DocType::"Arch. Order",
                    DocType::"Arch. Blanket Order",
                    DocType::"Arch. Return Order":
                        begin
                            **IsHandled := false;
                            OnValidateDocNoOnBeforeFindFromSalesHeaderArchive (FromSalesHeaderArchive, DocType, DocNo, DocNoOccurrence, DocVersionNo, IsHandled);
                            if not IsHandled then**
                                if not FromSalesHeaderArchive.Get(
                                     CopyDocMgt.ArchSalesHeaderDocType(DocType), DocNo, DocNoOccurrence, DocVersionNo)
                                then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateDocNoOnBeforeFindFromSalesHeaderArchive (var FromSalesHeaderArchive: Record "Sales Header Archive"; DocType: Option Quote,"Blanket Order","Order",Invoice,"Return Order","Credit Memo","Posted Shipment","Posted Invoi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
