### ISSUE TITLE
[Event Request] Report::"Get Source Documents" - Function "Purchase Header" - OnAfterGetRecord - OnPurchaseLineOnAfterGetRecordOnAfterCreateRcptHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9578]
We like to request the following Event:
Object: Report::"Get Source Documents"
Function: "Purchase Header" - OnAfterGetRecord
Publisher Event: OnPurchaseLineOnAfterGetRecordOnAfterCreateRcptHeader
Reason: To implement custom business logic
Where is the event placed:
VerifyItemNotBlocked("No.");
                        if "Location Code" = "Warehouse Request"."Location Code" then
                            case RequestType of
                                RequestType::Receive:
                                    if WhseActivityCreate.CheckIfPurchLine2ReceiptLine("Purchase Line") then begin
                                        OnPurchaseLineOnAfterGetRecordOnBeforeCreateRcptHeader(
                                          "Purchase Line", "Warehouse Request", WhseReceiptHeader, WhseHeaderCreated, OneHeaderCreated);
                                        if not OneHeaderCreated and not WhseHeaderCreated then begin
                                            CreateReceiptHeader;
                                            OnPurchaseLineOnAfterCreateRcptHeader(WhseReceiptHeader, WhseHeaderCreated, "Purchase Header");
                                        end;
                                        if not WhseActivityCreate.PurchLine2ReceiptLine(WhseReceiptHeader, "Purchase Line") then
                                            ErrorOccured := true;
                                        LineCreated := true;
                                        **OnPurchaseLineOnAfterGetRecordOnAfterCreateRcptHeader("Purchase Line", "Warehouse Request", WhseReceiptHeader, WhseHeaderCreated, OneHeaderCreated, ErrorOccured, LineCreated);**
                                    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPurchaseLineOnAfterGetRecordOnAfterCreateRcptHeader(var PurchaseLine: Record "Purchase Line"; var WarehouseRequest: Record "Warehouse Request"; var WarehouseReceiptHeader: Record "Warehouse Receipt He

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
