### ISSUE TITLE
[Event Request] Page::"Check Credit Limit - Function ShowWarning - OnShowWarningBeforeCheckCreditlimit

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9581]
We like to request the following Event:
Object: Page::"Check Credit Limit
Function: ShowWarning
Publisher Event: OnShowWarningBeforeCheckCreditlimit
Reason: To implement custom business logic
Where is the event placed:
NewOrderAmountLCY := NewOrderAmountLCY2;
        OldOrderAmountLCY := OldOrderAmountLCY2;
        Get(CustNo);
        SetRange("No.", "No.");
        Cust2.Copy(Rec);
        **OnShowWarningBeforeCheckCreditlimit(Rec, NewOrderAmountLCY, OldOrderAmountLCY, OrderAmountTotalLCY, ShippedRetRcdNotIndLCY, CustCreditAmountLCY, DeltaAmount, CheckOverDueBalance, Heading, Result, IsHandled);
        if IsHandled then
            exit(Result);**
        if (SalesSetup."Credit Warnings" in
            [SalesSetup."Credit Warnings"::"Both Warnings",
             SalesSetup."Credit Warnings"::"Credit Limit"]) and
           CustCheckCrLimit.IsCreditLimitNotificationEnabled(Rec)
        then begin
            CalcCreditLimitLCY;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnShowWarningBeforeCheckCreditlimit(Customer: Record Customer; var NewOrderAmountLCY: Decimal; OldOrderAmountLCY: Decimal; OrderAmountTotalLCY: Decimal; ShippedRetRcdNotIndLCY: Decimal; CustCreditAmount

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
