### ISSUE TITLE
[Event Request] Page::"Sales Line Discounts" - Function GetFilterDescription - OnGetFilterDescriptionItemTypeFilterCaseElse

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9582]
We like to request the following Event:
Object: Page::"Sales Line Discounts"
Function: GetFilterDescription
Publisher Event: OnGetFilterDescriptionItemTypeFilterCaseElse
Reason: To implement custom business logic
Where is the event placed:
case ItemTypeFilter of
            ItemTypeFilter::Item:
                begin
                    SourceTableName := ObjTranslation.TranslateObject(ObjTranslation."Object Type"::Table, 27);
                    Item.SetFilter("No.", CodeFilter);
                    if not Item.FindFirst then
                        Clear(Item);
                end;
            ItemTypeFilter::"Item Discount Group":
                begin
                    SourceTableName := ObjTranslation.TranslateObject(ObjTranslation."Object Type"::Table, 341);
                    ItemDiscGr.SetFilter(Code, CodeFilter);
                    if not ItemDiscGr.FindFirst then
                        Clear(ItemDiscGr);
                end;
            else begin
                    **IsHandled := false;
                    OnGetFilterDescriptionItemTypeFilterCaseElse(Item, ItemTypeFilter, SourceTableName, CodeFilter, IsHandled);**
                end;
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnGetFilterDescriptionItemTypeFilterCaseElse(var Item: Record Item; var ItemTypeFilter: Option; var SourceTableName: Text; var CodeFilter: Text; var IsHandled: Boolean)
    begin
    end;

**Comment by StanPesotskiy** [comment]
What is the purpose of IsHandled parameter? 
Did you miss 'if IsHandled then exit'?
