### ISSUE TITLE
[Event Request] Page::"Sales Line Discounts" - Function GetTypeFilter - OnGetTypeFilterCaseElse

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9583]
We like to request the following Event:
Object: Page::"Sales Line Discounts"
Function: GetTypeFilter
Publisher Event: OnGetTypeFilterCaseElse
Reason: To implement custom business logic
Where is the event placed:
local procedure GetTypeFilter(): Integer
    var
        IsHandled: Boolean;
        TypeFilter: Integer;
    begin
        case GetFilter(Type) of
            Format(Type::Item):
                exit(0);
            Format(Type::"Item Disc. Group"):
                exit(1);
            else begin
                    **IsHandled := false;
                    OnGetTypeFilterCaseElse(Rec, TypeFilter, IsHandled);
                    if IsHandled then
                        exit(TypeFilter);**
                end;
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnGetTypeFilterCaseElse(var SalesLineDiscount: Record "Sales Line Discount"; var TypeFilter: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
