### ISSUE TITLE
[Event Request] Page::"Transfer Routes Matrix" - Function ShowRouteSpecification - OnShowRouteSpecificationCaseElse

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9584]
We like to request the following Event:
Object: Page::"Transfer Routes Matrix"
Function: ShowRouteSpecification
Publisher Event: OnShowRouteSpecificationCaseElse
Reason: To implement custom business logic
Where is the event placed:
local procedure ShowRouteSpecification(MATRIX_ColumnOrdinal: Integer)
    var
        IsHandled: Boolean;
    begin
        if TransferRoute.Get(Code, MatrixRecords[MATRIX_ColumnOrdinal].Code) then begin
            case Show of
                Show::"Shipping Agent Code":
                    Specification := TransferRoute."Shipping Agent Code";
                Show::"Shipping Agent Service Code":
                    Specification := TransferRoute."Shipping Agent Service Code";
                Show::"In-Transit Code":
                    Specification := TransferRoute."In-Transit Code";
                else begin
                        OnShowRouteSpecificationCaseElse(TransferRoute, Show, Specification, IsHandled);
                        if IsHandled then
                            exit;
                        Specification := '';
                    end;
            end;
        end else
            Specification := '';
    end;
Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnShowRouteSpecificationCaseElse(var TransferRoute: Record "Transfer Route"; var Show: Option "In-Transit Code","Shipping Agent Code","Shipping Agent Service Code"; var SpecificationText: Text[80]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
