### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function AddBOMLine - OnAddBOMLineBeforeValidateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9585]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: AddBOMLine
Publisher Event: OnAddBOMLineBeforeValidateQuantity
Reason: To implement custom business logic
Where is the event placed:
AssemblyLine.Validate("Unit of Measure Code", BOMComponent."Unit of Measure Code");
            if AssemblyLine.Type <> AssemblyLine.Type::" " then
                AssemblyLine.Validate(
                  "Quantity per",
                  AssemblyLine.CalcQuantityFromBOM(
                    BOMComponent.Type, BOMComponent."Quantity per", 1, QtyPerUoM, AssemblyLine."Resource Usage Type"));
            OnAddBOMLineBeforeValidateQuantity(AssemblyHeader, AssemblyLine, BOMComponent);
            AssemblyLine.Validate(
                Quantity,
                AssemblyLine.CalcQuantityFromBOM(
                    BOMComponent.Type, BOMComponent."Quantity per", Quantity, QtyPerUoM, AssemblyLine."Resource Usage Type"));
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAddBOMLineBeforeValidateQuantity(AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; BOMComponent: Record "BOM Component")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
