### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function CopyAssemblyData - OnCopyAssemblyDataOnAfterInsert

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9586]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: CopyAssemblyData
Publisher Event: OnCopyAssemblyDataOnAfterInsert
Reason: To implement custom business logic
Where is the event placed:
procedure CopyAssemblyData(FromAssemblyHeader: Record "Assembly Header"; var ToAssemblyHeader: Record "Assembly Header"; var ToAssemblyLine: Record "Assembly Line") NoOfLinesInserted: Integer
    var
        AssemblyLine: Record "Assembly Line";
    begin
        ToAssemblyHeader := FromAssemblyHeader;
        ToAssemblyHeader.Insert();
        SetLinkToLines(FromAssemblyHeader, AssemblyLine);
        AssemblyLine.SetFilter(Type, '%1|%2', AssemblyLine.Type::Item, AssemblyLine.Type::Resource);
        ToAssemblyLine.Reset();
        ToAssemblyLine.DeleteAll();
        if AssemblyLine.Find('-') then
            repeat
                ToAssemblyLine := AssemblyLine;
                ToAssemblyLine.Insert();
                NoOfLinesInserted += 1;
                OnCopyAssemblyDataOnAfterInsert(AssemblyLine, ToAssemblyLine);
            until AssemblyLine.Next() = 0;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCopyAssemblyDataOnAfterInsert(var AssemblyLine: Record "Assembly Line"; var ToAssemblyLine: Record "Assembly Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
