### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function DoVerificationsSkippedEarlier - OnDoVerificationsSkippedEarlierOnAfterAsmLineModified

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9587]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: DoVerificationsSkippedEarlier
Publisher Event: OnDoVerificationsSkippedEarlierOnAfterAsmLineModified
Reason: To implement custom business logic
Where is the event placed:
if ReplaceLinesFromBOM then
                    case TempNewAsmLine.Type of
                        TempNewAsmLine.Type::Item:
                            TempNewAsmLine.CreateDim(DATABASE::Item, TempNewAsmLine."No.", NewHeaderSetID);
                        TempNewAsmLine.Type::Resource:
                            TempNewAsmLine.CreateDim(DATABASE::Resource, TempNewAsmLine."No.", NewHeaderSetID);
                    end
                else begin
                    if UpdateDimension then
                        TempNewAsmLine.UpdateDim(NewHeaderSetID, OldHeaderSetID);
                end;
                TempNewAsmLine.Modify();
                OnDoVerificationsSkippedEarlierOnAfterAsmLineModified(TempNewAsmLine);
            until TempNewAsmLine.Next() = 0;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnDoVerificationsSkippedEarlierOnAfterAsmLineModified(var AssemblyLine: Record "Assembly Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
