### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function ExplodeAsmList - OnExplodeAsmListBeforeAssemblyLinesInsert

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9589]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: ExplodeAsmList
Publisher Event: OnExplodeAsmListBeforeAssemblyLinesInsert
Reason: To implement custom business logic
Where is the event placed:
TempAssemblyLine.Reset();
            TempAssemblyLine.FindSet();
            ToAssemblyLine := TempAssemblyLine;
            ToAssemblyLine.Modify();
            OnExplodeAsmListBeforeAssemblyLinesInsert(TempAssemblyLine, ToAssemblyLine);
            while TempAssemblyLine.Next <> 0 do begin
                ToAssemblyLine := TempAssemblyLine;
                ToAssemblyLine.Insert();
                OnExplodeAsmListAfterAssemblyLineInsert(TempAssemblyLine, ToAssemblyLine);
                if ToAssemblyLine."Due Date" < WorkDate then begin
                    DueDateBeforeWorkDate := true;
                    NewLineDueDate := ToAssemblyLine."Due Date";
                end;
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnExplodeAsmListBeforeAssemblyLinesInsert(var FromAssemblyLine: Record "Assembly Line"; var ToAssemblyLine: Record "Assembly Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
