### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function ExplodeAsmList - OnExplodeAsmListBeforeSetQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9590]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: ExplodeAsmList
Publisher Event: OnExplodeAsmListBeforeSetQty
Reason: To implement custom business logic
Where is the event placed:
AddBOMLine(AssemblyHeader, TempAssemblyLine, true, FromBOMComp, false, 1);
                IsHandled := false;
                OnExplodeAsmListBeforeSetQty(AssemblyHeader, TempAssemblyLine, AsmLine, IsHandled);
                if not IsHandled then begin
                    TempAssemblyLine.Quantity := TempAssemblyLine.Quantity * "Quantity per" * "Qty. per Unit of Measure";
                    TempAssemblyLine."Quantity (Base)" := TempAssemblyLine."Quantity (Base)" * "Quantity per" * "Qty. per Unit of Measure";
                    TempAssemblyLine."Quantity per" := TempAssemblyLine."Quantity per" * "Quantity per" * "Qty. per Unit of Measure";
                    TempAssemblyLine."Remaining Quantity" := TempAssemblyLine."Remaining Quantity" * "Quantity per" * "Qty. per Unit of Measure";
                    TempAssemblyLine."Remaining Quantity (Base)" :=
                        TempAssemblyLine."Remaining Quantity (Base)" * "Quantity per" * "Qty. per Unit of Measure";
                    TempAssemblyLine."Quantity to Consume" :=
                        TempAssemblyLine."Quantity to Consume" * "Quantity per" * "Qty. per Unit of Measure";
                    TempAssemblyLine."Quantity to Consume (Base)" :=
                        TempAssemblyLine."Quantity to Consume (Base)" * "Quantity per" * "Qty. per Unit of Measure";
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnExplodeAsmListBeforeSetQty(AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; FromAssemblyLine: Record "Assembly Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
