### ISSUE TITLE
Found duplicated code in codeunit 13 about CheckCorrection function In Microsoft_Base Application_17.0.16993.0.app

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9591]
![Image cu13 bc17](https://user-images.githubusercontent.com/73465025/97149649-56cbc100-176d-11eb-9792-fc9cedf2f38f.jpg)

As we view in the attached image above the code between the lines 374 and 385 both included, is duplicated in the function CheckCorrection(GenJnlLine);

You must delete this lines and, additionally, to manage the event OnBeforeCheckCorrection(GenJournalLine, IsHandled) properly, we need to have access to the Global Vars or at least to the following vars:
LastDate, LastDocType, LastDocNo, LastTempTransNo and DocCorrection.

Thanks in advance for your answer.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
