### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function UpdateAssemblyLines - OnUpdateAssemblyLinesOnAfterReplaceLinesFromBOM

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9592]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: UpdateAssemblyLines
Publisher Event: OnUpdateAssemblyLinesOnAfterReplaceLinesFromBOM
Reason: To implement custom business logic
Where is the event placed:
if TempAssemblyLine.Find('-') then
            repeat
                if not ReplaceLinesFromBOM then
                    AssemblyLine.Get(TempAssemblyLine."Document Type", TempAssemblyLine."Document No.", TempAssemblyLine."Line No.");
                AssemblyLine := TempAssemblyLine;
                if ReplaceLinesFromBOM then
                    AssemblyLine.Insert(true)
                else
                    AssemblyLine.Modify(true);
                OnUpdateAssemblyLinesOnAfterReplaceLinesFromBOM (AssemblyLine, ReplaceLinesFromBOM);
                AsmHeader.AutoReserveAsmLine(AssemblyLine);
                if AssemblyLine."Due Date" < WorkDate then begin
                    DueDateBeforeWorkDate := true;
                    NewLineDueDate := AssemblyLine."Due Date";
                end;
            until TempAssemblyLine.Next() = 0;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnUpdateAssemblyLinesOnAfterReplaceLinesFromBOM (var AssemblyLine: Record "Assembly Line"; ReplaceLinesFromBOM: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
