### ISSUE TITLE
[EVENT REQUEST] Page 344 Navigate

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9593]
We use an extra sourcetype in the function SetSource. But there is no way to check for an extra value. Can you add an OnSetSource event so we can set the sourcename & SourceType.

LOCAL SetSource(PostingDate : Date;DocType2 : Text[100];DocNo : Text[50];SourceType2 : Integer;SourceNo2 : Code[20])
IF SourceType2 = 0 THEN BEGIN
  DocType := '';
  SourceType := '';
  SourceNo := '';
  SourceName := '';
END ELSE BEGIN
  DocType := DocType2;
  SourceNo := SourceNo2;
  SETRANGE("Document No.",DocNo);
  SETRANGE("Posting Date",PostingDate);
  DocNoFilter := GETFILTER("Document No.");
  PostingDateFilter := GETFILTER("Posting Date");
  CASE SourceType2 OF
    1:
      BEGIN
        SourceType := Cust.TABLECAPTION;
        IF NOT Cust.GET(SourceNo) THEN
          Cust.INIT;
        SourceName := Cust.Name;
      END;
    2:
      BEGIN
        SourceType := Vend.TABLECAPTION;
        IF NOT Vend.GET(SourceNo) THEN
          Vend.INIT;
        SourceName := Vend.Name;
      END;

  END;
END;

**OnSetSource(SourceType2,SourceType,SourceNo,SourceName);**
DocTypeEnable := SourceType2 <> 0;
SourceTypeEnable := SourceType2 <> 0;
SourceNoEnable := SourceType2 <> 0;
SourceNameEnable := SourceType2 <> 0;

**OnSetSource(SourceType2 : Integer;VAR SourceType : Text[30];SourceNo : Code[20];VAR SourceName : Text[50]);**

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
