### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function UpdateAssemblyLines - OnBeforeReplaceLinesFromBOM

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9594]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: UpdateAssemblyLines
Publisher Event: OnBeforeReplaceLinesFromBOM
Reason: To implement custom business logic
Where is the event placed:
NoOfLinesFound := CopyAssemblyData(AsmHeader, TempAssemblyHeader, TempAssemblyLine);
        OnBeforeReplaceLinesFromBOM(TempAssemblyLine, ReplaceLinesFromBOM);
        if ReplaceLinesFromBOM then begin
            TempAssemblyLine.DeleteAll();
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeReplaceLinesFromBOM(var AssemblyLine: Record "Assembly Line"; ReplaceLinesFromBOM: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
