### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function UpdateExistingLine - OnBeforeUpdateQtyToConsume

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9595]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: UpdateExistingLine
Publisher Event: OnBeforeUpdateQtyToConsume
Reason: To implement custom business logic
Where is the event placed:
if UpdateQtyToConsume then
                if not AssemblyLine.FixedUsage then begin
                    AssemblyLine.InitQtyToConsume;
                    QtyToConsume := AssemblyLine.Quantity * "Quantity to Assemble" / Quantity;
                    RoundQty(QtyToConsume);
                    IsHandled := false;
                    OnBeforeUpdateQtyToConsume(AsmHeader, AssemblyLine, QtyToConsume, IsHandled);
                    if not IsHandled then begin
                        if QtyToConsume <= AssemblyLine.MaxQtyToConsume then
                            AssemblyLine.Validate("Quantity to Consume", QtyToConsume);
                    end;
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateQtyToConsume(AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; var QtyToConsume: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
