### ISSUE TITLE
[Event Request] Codeunit::"Assembly Line Management" - Function UpdateExistingLine - OnBeforeUpdateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9596]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: UpdateExistingLine
Publisher Event: OnBeforeUpdateQuantity
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
                OnBeforeUpdateQuantity(AsmHeader, AssemblyLine, QtyRatio, IsHandled);
                if not IsHandled then begin
                    if AssemblyLine.FixedUsage then
                        AssemblyLine.Validate(Quantity)
                    else
                        AssemblyLine.Validate(Quantity, AssemblyLine.Quantity * QtyRatio);
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateQuantity(AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; var QtyRatio: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
