### ISSUE TITLE
[Additional Parameter] CU 80 Sales Post OnAfterPostItemJnlLine  

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#9597]
Hello, 
can we add param WhseJnlPostLine: Codeunit "Whse. Jnl.-Register Line" to this event? CU is needed when running custom posting from Sales Post.
Thanks,
Bartek

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
