### ISSUE TITLE
[Event Request] Codeunit 80: SalesPost - Function FinalizePosting

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9598]
Could You add the following event to the codeunit 80 to avoid the deletion of the approval entries?

Object: Codeunit 80 "Sales-Post"
Function: FinalizePosting

Publisher Event: OnBeforeSalesPostDeleteApprovalEntries
Reason: To implement custom business logic migrating from Dynamics NAV 2016 database.
Where is the event placed (see image attached):

![Image 6](https://user-images.githubusercontent.com/73465025/97171926-86d78c00-178e-11eb-9907-e95c93d604fa.jpg)

above the line: ApprovalsMgmt.DeleteApprovalEntries(RecordId);

insert the following lines: 

**IsHandled := false;
OnBeforeSalesPostDeleteApprovalEntries(SalesHeader, IsHandled);
if not IsHandled then** 

             ApprovalsMgmt.DeleteApprovalEntries(RecordId);

Event Code:
**[IntegrationEvent(false, false)]
local procedure OnBeforeSalesPostDeleteApprovalEntries(SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;**

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
