### ISSUE TITLE
[Event Request] Codeunit 5940 (ServContractManagement) in functions CreateServiceLedgerEntries and CreateAllServLines

### ISSUE THREAD

**Issue by jorgecorreia27** [microsoft/ALAppExtensions#9599]
Dear all
In the course of a development in Business Central related to the Services Module, when creating a Service Invoice, the standard code does de following 
![image](https://user-images.githubusercontent.com/37341299/97173804-0eba9780-1789-11eb-9dcb-ebd525077c5a.png)
However, to the development in question this code block is not needed to calculate the values for the Service Ledger Entry record. So we wold like a diferent approach to this issue. One of the requested solutions could be achieved with an Event/"IsHandled" login to bypass this code block. Something in the likes of:
![image](https://user-images.githubusercontent.com/37341299/97174050-71ac2e80-1789-11eb-81e6-3008e95d9a0a.png)
Another issue in question is in the function CreateAllServLines. After the code is completed there is a Modify to the record of the table "Service Contract Header" (ServContractToInvoice). But we would like to change some values before the record gets to the MODIFY instruction. So we would like to request an event right before the instruction. For example:
![image](https://user-images.githubusercontent.com/37341299/97174737-6574a100-178a-11eb-9d3d-8f27032a7ed7.png)
For both of these events requested, all variables should be passed as VAR.
Best regards,
Jorge Correia

**Comment by StanPesotskiy** [comment]
The code you mentioned does not exist in latest application version - please check 17.x.
To speed up the process it would be nice to have both edited code and requested events code copy/pasted as text (instead of pictures).

**Comment by AlexanderYakunin** [comment]
I'm closing this request due to comment above, If you still need something here, please create new request based on latest code.
