### ISSUE TITLE
[Event Request] Codeunit 90: Purch.-Post - Function FinalizePosting

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9600]
Could You please, add the following event to the codeunit 90 to avoid the deletion of the approval entries?

Object: Codeunit 90 "Purch.-Post"
Function: FinalizePosting

Publisher Event: OnBeforePurchPostDeleteApprovalEntries
Reason: To implement custom business logic migrating from Dynamics NAV 2016 database.
Where is the event placed (see image attached):

![Image 7](https://user-images.githubusercontent.com/73465025/97177947-213bcd80-1797-11eb-8f4e-5cd2805d3ffd.jpg)

above the line: ApprovalsMgmt.DeleteApprovalEntries(RecordId);

insert the following lines:

IsHandled := false;
OnBeforePurchPostDeleteApprovalEntries(PurchHeader, IsHandled);
if not IsHandled then

         ApprovalsMgmt.DeleteApprovalEntries(RecordId);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforePurchPostDeleteApprovalEntries(PurchHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
