### ISSUE TITLE
[Event Request] Codeunit 134: "Import Attachment - Inc. Doc." - Function CreateNewSalesPurchIncomingDoc

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9601]
Could You add the following event to the codeunit 134 to manage document attachments in additional tables?

Object: Codeunit 134 "Import Attachment - Inc. Doc."
Function: CreateNewSalesPurchIncomingDoc

Publisher Event: OnBeforeImportAttachmentCreateNewSalesPurchIncomingDoc
Reason: To implement custom business logic and manage document Attachments in additional tables
Where is the event placed (see image attached)?:
![Image 8](https://user-images.githubusercontent.com/73465025/97210364-c79ac980-17bd-11eb-9560-005d48532d09.jpg)

At the begining of the function CreateNewSalesPurchIncomingDoc insert the call to the event Function with the parameter Handled. 

IsHandled := false;
OnBeforeImportAttachmentCreateNewSalesPurchIncomingDoc(IncomingDocumentAttachment, IncomingDocEntryNo, IsHandled);
if IsHandled then
        exit(IncomingDocEntryNo);

with IncomingDocumentAttachment do begin

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeImportAttachmentCreateNewSalesPurchIncomingDoc(var IncomingDocumentAttachment: Record "Incoming Document Attachment";  var IncomingDocEntryNo: Integer, var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
