### ISSUE TITLE
[Event Request] Codeunit::"CustEntry-Apply Posted Entries" - Function PostUnApplyCustomerCommit - OnBeforeCheckDtldCustLedgEntryInitialDocType

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9602]
Could You please, add the following event to the codeunit 226 to manage the error shown in the image?

Object: Codeunit 226 "CustEntry-Apply Posted Entries"
Function: PostUnApplyCustomerCommit

Publisher Event: OnBeforeCheckDtldCustLedgEntryInitialDocType
Reason: To implement custom business logic and manage when the error must be thrown
Where is the event placed (see image attached)?:
![Image 9](https://user-images.githubusercontent.com/73465025/97275862-c194ff00-1836-11eb-8976-c12abbabfc90.jpg)

Above the Line:
if DtldCustLedgEntry."Initial Document Type" = DtldCustLedgEntry."Initial Document Type"::" " then

IsHandled := false;
OnBeforeCheckDtldCustLedgEntryInitialDocType(DtldCustLedgEntry,DocNo,PostingDate,CommitChanges,IsHandled);
if Not IsHandled then
    
if DtldCustLedgEntry."Initial Document Type" = DtldCustLedgEntry."Initial Document Type"::" " then
                    Error(Text1100003);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckDtldCustLedgEntryInitialDocType(var DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; DocNo: Code[20]; PostingDate: Date; var CommitChanges: Boolean; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
