### ISSUE TITLE
[IT] Use SetOperationType in VAT Bus. Posting Group validate for Sales/Purchase Header

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#9603]
Hi,
we need to handle in one of our custom operation type validation on Sales Header and Purchase Header. 
The function **SetOperationType** has all events we need but, as you can see from the code below, in one case system does a direct validation of the field without passing through **SetOperationType** function.

        field(116; "VAT Bus. Posting Group"; Code[20])
        {
            Caption = 'VAT Bus. Posting Group';
            TableRelation = "VAT Business Posting Group";

            trigger OnValidate()
            var
                VATBusinessPostingGroup: Record "VAT Business Posting Group";
            begin
                TestStatusOpen;
                if not CheckVATExemption then
                    "VAT Bus. Posting Group" := xRec."VAT Bus. Posting Group";
                if xRec."VAT Bus. Posting Group" <> "VAT Bus. Posting Group" then
                    RecreateSalesLines(FieldCaption("VAT Bus. Posting Group"));

                VATBusinessPostingGroup.Get("VAT Bus. Posting Group");
                _**Validate("Operation Type", VATBusinessPostingGroup."Default Sales Operation Type");**_
            end;
        }

Thank you

**Comment by StanPesotskiy** [comment]
so, do you mean that these two lines:
            VATBusinessPostingGroup.Get("VAT Bus. Posting Group");
            Validate("Operation Type", VATBusinessPostingGroup."Default Sales Operation Type");
should be replaced by one?
            SetOperationType()

**Comment by alessandrovecchio** [comment]
Yes, exactly.

Thank you

Da: Stan Pesotskiy <notifications@github.com>
Inviato: martedì 27 ottobre 2020 12:32
A: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
Cc: Alessandro Vecchio <alessandro.vecchio@eos-solutions.it>; Author <author@noreply.github.com>
Oggetto: Re: [microsoft/ALAppExtensions] Use SetOperationType in VAT Bus. Posting Group validate for Sales/Purchase Header (#9603)


so, do you mean that these two lines:
VATBusinessPostingGroup.Get("VAT Bus. Posting Group");
Validate("Operation Type", VATBusinessPostingGroup."Default Sales Operation Type");
should be replaced by one?
SetOperationType()

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
