### ISSUE TITLE
[Event Request] Codeunit::"VendEntry-Apply Posted Entries" - Function PostUnApplyVendor - OnBeforeCheckDtldVendLedgEntryInitialDocType 

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9604]
Could You please, add the following event to the codeunit 227 to manage the error shown in the image?

Object: Codeunit 227 "VendEntry-Apply Posted Entries"
Function: PostUnApplyVendor

Publisher Event: OnBeforeCheckDtldVendLedgEntryInitialDocType
Reason: To implement custom business logic and manage when the error must be thrown
Where is the event placed (see image attached)?:
![Image 11](https://user-images.githubusercontent.com/73465025/97277517-decacd00-1838-11eb-834b-a2ec7a7e38b1.jpg)

Above the Line:
if DtldVendLedgEntry."Initial Document Type" = DtldVendLedgEntry."Initial Document Type"::" " then

Insert the following 3 lines:

IsHandled := false;
OnBeforeCheckDtldVendLedgEntryInitialDocType(DtldVendLedgEntry,DocNo,PostingDate,IsHandled);
if Not IsHandled then
    
if DtldVendLedgEntry."Initial Document Type" = DtldVendLedgEntry."Initial Document Type"::" " then
                    Error(Text1100003);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckDtldVendLedgEntryInitialDocType(var DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; DocNo: Code[20]; PostingDate: Date; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
