### ISSUE TITLE
[Event Request] Codeunit::370 "Bank Acc. Reconciliation Post" - Function Post - OnAfterFilterBankAccRecLines

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9607]
Could You please, add the following event to the codeunit 370 "Bank Acc. Reconciliation Post" to manage the filters applied to record Bank Acc. Reconciliation line?

Object: codeunit 370 "Bank Acc. Reconciliation Post"
Function Post(BankAccRecon: Record "Bank Acc. Reconciliation")

Publisher Event: OnAfterFilterBankAccRecLines
Reason: To implement custom business logic and manage to place additional filters in Bank Acc. Reconciliation Lines table
Where is the event placed (see image attached)?:
![Image 13](https://user-images.githubusercontent.com/73465025/97283347-02dddc80-1840-11eb-9fb5-c35895c6b8a6.jpg)

below the line :
BankAccReconLine.FilterBankRecLines(BankAccRecon);

place the call to the event:
OnAfterFilterBankAccRecLines(BankAccReconLine,BankAccRecon);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterFilterBankAccRecLines(var BankAccReconLines: Record "Bank Acc. Reconciliation Line"; BankAccRecon: Record "Bank Acc. Reconciliation")
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
