### ISSUE TITLE
[Event Request] Codeunit::370 "Bank Acc. Reconciliation Post" - Function TransferToPostPmtAppln(BankAccRecon: Record "Bank Acc. Reconciliation") - OnBeforeTransferToPostPmtAppln

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9608]
Could You please, add the following event to the codeunit 370 "Bank Acc. Reconciliation Post" to manage the Transfer to Post Payment Application?

Object: codeunit 370 "Bank Acc. Reconciliation Post"
Function TransferToPostPmtAppln(BankAccRecon: Record "Bank Acc. Reconciliation")

Publisher Event: OnBeforeTransferToPostPmtAppln
Reason: To implement custom business logic and manage the  Transefer
Where is the event placed (see image attached)?:
![Image 14](https://user-images.githubusercontent.com/73465025/97285727-db3c4380-1842-11eb-81d7-df6d3ad048c0.jpg)

At the begining of the function TransferToPostPmtAppln(BankAccRecon: Record "Bank Acc. Reconciliation")

Insert the following 4 lines:

IsHandled := false;
OnBeforeTransferToPostPmtAppln(BankAccRecon,IsHandled);
if IsHandled then
  Exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferToPostPmtAppln(var BankAccRecon: Record "Bank Acc. Reconciliation"; var IsHandled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
