### ISSUE TITLE
[Event Request] Codeunit::370 "Bank Acc. Reconciliation Post" - Function TransferToBankStmt - OnBeforeTransferToBankStmt

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9609]
Could You please, add the following event to the codeunit 370 "Bank Acc. Reconciliation Post" to manage the Transfer to Bank Statement?

Object: codeunit 370 "Bank Acc. Reconciliation Post"
Function TransferToBankStmt(BankAccRecon: Record "Bank Acc. Reconciliation")

Publisher Event: OnBeforeTransferToBankStmt
Reason: To implement custom business logic and manage the  Transefer
Where is the event placed (see image attached)?:
![Image 15](https://user-images.githubusercontent.com/73465025/97287182-8ef20300-1844-11eb-9763-e5d513545388.jpg)

At the begining of the function TransferToBankStmt(BankAccRecon: Record "Bank Acc. Reconciliation")

Insert the following 4 lines:

IsHandled := false;
OnBeforeTransferToBankStmt(BankAccRecon,IsHandled);
if IsHandled then
  Exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferToBankStmt(var BankAccRecon: Record "Bank Acc. Reconciliation"; var IsHandled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
