### ISSUE TITLE
[Event Request] Codeunit::370 "Bank Acc. Reconciliation Post" - Function Post - OnBeforeCaseStatementTypePaymentAppln

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9610]
Could You please, add the following event to the codeunit 370 "Bank Acc. Reconciliation Post" to manage the Transfer to Bank Statement?

Object: codeunit 370 "Bank Acc. Reconciliation Post"
Function Post(BankAccRecon: Record "Bank Acc. Reconciliation")

Publisher Event: OnBeforeCaseStatementTypePaymentAppln
Reason: To implement custom business logic and manage 
Where is the event placed (see image attached)?:
![Image 16](https://user-images.githubusercontent.com/73465025/97292031-01fe7800-184b-11eb-9662-042deb019fd4.jpg)

In the case sentence "Statement Type"::"Payment Application":

Insert the following lines marked between +++++++++:

"Statement Type"::"Payment Application":
	begin
		//++++++++++++++++++++++++++++++++++++++++++++
		IsHandled := false;
		OnBeforeCaseStatementTypePaymentAppln(BankAccRecon,IsHandled);
		if Not IsHandled then begin
		//++++++++++++++++++++++++++++++++++++++++++++

	        TransferToPostPmtAppln(BankAccRecon);
	        if not "Post Payments Only" then
	            TransferToBankStmt(BankAccRecon);
	            
		//++++++++++++++++++++++++++++++++++++++++++++
		end;
		//++++++++++++++++++++++++++++++++++++++++++++	            
    end;		

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCaseStatementTypePaymentAppln(var BankAccRecon: Record "Bank Acc. Reconciliation"; var IsHandled: Boolean)
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
