### ISSUE TITLE
[Event Request] Codeunit::370 "Bank Acc. Reconciliation Post" - Function PostPaymentApplications - OnPostPaymentApplicationsOnBeforePostPaymentApplns

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9611]
Could You please, add the following event to the codeunit 370 "Bank Acc. Reconciliation Post" to manage the PostPaymentApplications

Object: codeunit 370 "Bank Acc. Reconciliation Post"
Function PostPaymentApplications(BankAccReconLine: Record "Bank Acc. Reconciliation Line"; var AppliedAmount: Decimal)

Publisher Event: OnPostPaymentApplicationsOnBeforePostPaymentApplns
Reason: To implement custom business logic and manage the PostPaymentApplications
Where is the event placed (see image attached)?:
![Image 17](https://user-images.githubusercontent.com/73465025/97294944-f9a83c00-184e-11eb-9e4f-201f140dd2ba.jpg)

at the begining of the function after the first error place the call to the event

OnPostPaymentApplicationsOnBeforePostPaymentApplns(BankAccReconLine,AppliedAmount,SourceCode);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnPostPaymentApplicationsOnBeforePostPaymentApplns(var BankAccRecon: Record "Bank Acc. Reconciliation"; var AppliedAmount: Decimal; SourceCode: Code[10])
begin
end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
