### ISSUE TITLE
[Event Request] Codeunit 365 Format Address - OnBeforeFormatAddr

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9614]
Hi Team,

In Codeunit 365 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure `FormatAddr` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/97302942-65e06b00-1862-11eb-9112-a64b39a24e22.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFormatAddr(var Country: Record "Country/Region"; var GLSetup: Record "General Ledger Setup"; CountryCode: Code[10])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
