### ISSUE TITLE
[Event Request] Codeunit::371 "Bank Acc. Recon. Post (Yes/No)" - Function BankAccReconPostYesNo - OnBeforeBankAccReconPostYesNo

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9615]
Could You please, add the following event to the codeunit 371 "Bank Acc. Recon. Post (Yes/No)"

Object: Codeunit 371 "Bank Acc. Recon. Post (Yes/No)"
Function: BankAccReconPostYesNo

Publisher Event: OnBeforeBankAccReconPostYesNo
Reason: To implement custom business logic and manage the previous posting taks
Where is the event placed (see image attached)?:
![Image 18](https://user-images.githubusercontent.com/73465025/97303811-30844f00-185b-11eb-9d9d-b0438523e6d1.jpg)

At the begining of the function BankAccReconPostYesNo(var BankAccReconciliation: Record "Bank Acc. Reconciliation"): Boolean

Insert the following 4 lines:

IsHandled := false;
OnBeforeBankAccReconPostYesNo(BankAccReconciliation,IsHandled);
if IsHandled then
   exit(true);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeBankAccReconPostYesNo(var BankAccReconciliation: Record "Bank Acc. Reconciliation"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
