### ISSUE TITLE
EmailAccount - OnAfterValidateEmailAddress(es)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#9616]
@darjoo Somewhat related with #8671 

We've added a feature to test on allowed domains when sending out emails. 

![image](https://user-images.githubusercontent.com/25268332/97305587-940f7c00-185d-11eb-86a6-7e4287c3f866.png)

This is especially usefull in sandboxes / test / dev environments that are copies from live environments, containing real end user mail addresses. During development, we often encountered mails being sent out to end user mail addresses. To block this, we added some checks in following subscribers:

```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Mail Management", 'OnBeforeCheckValidEmailAddresses', '', false, false)]
[EventSubscriber(ObjectType::Codeunit, Codeunit::Mail, 'OnBeforeCreateMessage', '', false, false)]
```

To ensure any outgoing mails are blocked from being sent, also via the new Email Feature, I'd like to move our test to the EmailAccount.ValidateEmailAddress(es). So having following publisher would probably help us moving the test:

`OnAfterValidateEmailAddress(EmailAddress: Text; AllowEmptyValue: Boolean) `

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for releasee 17.

**Comment by fvet** [comment]
related to #12537 

OnAfterValidateEmailAddress does not provide solution.
Submitted new event as alternative to the old OnBeforeCreateMessage
