### ISSUE TITLE
[Event Request] Codeunit 365 Format Address - OnBeforeGetSetup

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9617]
Hi Team,

In Codeunit 365 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure `FormatPostCodeCity` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/97307995-0a65ab80-1869-11eb-8ad5-bb808837c82e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetSetup(var Country: Record "Country/Region"; var GLSetup: Record "General Ledger Setup"; CountryCode: Code[10])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
