### ISSUE TITLE
[Event Request] Codeunit 365 Format Address - OnAfterGeneratePostCodeCity

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9618]
Hi Team,

In Codeunit 365 we need possibility to have our additional checks and/or avoid using standard code. Having event in the end of procedure `GeneratePostCodeCity` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/97308858-fff7e180-1869-11eb-8629-80b499b64f18.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterGeneratePostCodeCity(var Country: Record "Country/Region"; var PostCode: Code[20]; var PostCodeCityText: Text[100]; var City: Text[50]; var CountyText: Text[50]; var County: Text[50])

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
