### ISSUE TITLE
[Event Request] Codeunit::1255 "Match Bank Payments" - Function Code - OnAfterCode

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9619]
Could You please, add the following event to the codeunit 1255 "Match Bank Payments"

Object: Codeunit 1255 "Match Bank Payments"
Function: Code

Publisher Event: OnAfterCode
Reason: To implement custom business logic 
Where is the event placed (see image attached)?:
![Image 20](https://user-images.githubusercontent.com/73465025/97309693-a6d87f80-1862-11eb-8f2b-76126f310ffd.jpg)

At the end of the function Code

Insert the call to the event

OnAfterCode(BankAccReconciliationLine);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterCode(var BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line")
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
