### ISSUE TITLE
[Event Request] Codeunit::1255 "Match Bank Payments" - Function InitializeCustomerLedgerEntriesMatchingBuffer - OnInitCustomerLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9620]
Could You please, add the following event to the codeunit 1255 "Match Bank Payments"

Object: Codeunit 1255 "Match Bank Payments"
Function: InitializeCustomerLedgerEntriesMatchingBuffer

Publisher Event: OnInitCustomerLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode
Reason: To implement custom business logic and permit application in all currencies
Where is the event placed (see image attached)?:
![Image 21](https://user-images.githubusercontent.com/73465025/97312360-b0171b80-1865-11eb-87d1-5ee4f68f505c.jpg)

Above the line: 
if CustLedgerEntry.FindSet then

Insert the call to the event

OnInitCustomerLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode(CustLedgerEntry);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnInitCustomerLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode(var CustLedgerEntry: Record "Cust. Ledger Entry")
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
