### ISSUE TITLE
[Event Request] Codeunit::1255 "Match Bank Payments" - Function InitializeVendorLedgerEntriesMatchingBuffer - OnInitVendorLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9621]
Could You please, add the following event to the codeunit 1255 "Match Bank Payments"

Object: Codeunit 1255 "Match Bank Payments"
Function: InitializeVendorLedgerEntriesMatchingBuffer

Publisher Event: OnInitVendorLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode
Reason: To implement custom business logic and permit application in all currencies
Where is the event placed (see image attached)?:
![Image 22](https://user-images.githubusercontent.com/73465025/97313594-1cdee580-1867-11eb-8815-32950bcff909.jpg)

Insert the call to the event:

OnInitVendorLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode(VendorLedgerEntry);

Above the line 
if VendorLedgerEntry.FindSet then

Event Code:
[IntegrationEvent(false, false)]
local procedure OnInitVendorLedgerEntriesMatchingBufferAfterSetFilterCurrencyCode(var VendorLedgerEntry: Record "Vendor Ledger Entry")
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
