### ISSUE TITLE
[Event Request] Codeunit 7308 Replenishment - OnBeforeFindReplenishmtBin

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#9625]
Hi AL team,

we need the following event in function FindReplenishmentBin:

     ...
    begin
    +++    OnBeforeFindReplenishmtBin(TempWhseWkshLine, ToBinContent, AllowBreakBulk, NextLineNo, 
    +++        WhseWkshTemplateName, WhseWkshName, LocationCode, DoNotFillQtytoHandle, RemainQtyToReplenishBase, 
    +++       IsHandled);
    +++    if IsHandled then
    +++        exit;

        with ToBinContent do begin
            FromBinContent.Reset();
    ...

    +++ [IntegrationEvent(false, false)]
    +++ local procedure OnBeforeFindReplenishmtBin(var TempWhseWkshLine: Record "Whse. Worksheet Line" temporary; 
    +++    ToBinContent: Record "Bin Content"; AllowBreakBulk: Boolean; NextLineNo: Integer; WhseWkshTemplateName: 
    +++ Code[10]; WhseWkshName: Code[10]; LocationCode: Code[10]; DoNotFillQtytoHandle: Boolean; 
    +++ RemainQtyToReplenishBase: Decimal; var IsHandled: Boolean)
    +++ begin
    +++ end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
