### ISSUE TITLE
Codeunit 80 Sales-Post - Hide Dialog

### ISSUE THREAD

**Issue by mynavblog** [Microsoft/ALAppExtensions#963]
Dear Team,

One of our solution request that dialog box is not shown when posting Sales from Codeunit 80. I would like to ask you to:

1. Add to the Event - OnBeforePostSalesDoc(Rec,SuppressCommit,PreviewMode); additional parameter HideDialog as the event looks similar to this:

![image](https://user-images.githubusercontent.com/37371997/51812150-9ae81400-22b0-11e9-81d3-3708c0c1ac0b.png)

2. Before each Dialog (Window) add functionality to omit the showing Window. Example of one of the Window.Update (but it need to be done for all Window functions):

![image](https://user-images.githubusercontent.com/37371997/51812259-05994f80-22b1-11e9-8f5e-289a25078092.png)

Thank you in advance.

Best regards,
Krzysztof

**Comment by RomanZanizdra** [comment]
Hi Krzysztof. Short question. 
You mentioned in the second point that all window updates should be hide (I suppose you talk about the whole application). Is this ask of a particular customer on the particular project or you know more cases when window opens, updates are not required at all? And one more, does it make sense to have a setup flag for example which can enable/disable showing/updating windows for the whole application?

**Comment by AJasp** [comment]
Hi,
to migration our ISV solution we also need this event. Currently I can't find it in the Spring Release or in the current Developer Preview. Is there already more detailed information, when a solution is available for it?
Thanks in advance.
Best Regards
Andreas
