### ISSUE TITLE
[Event Request] Page 7335 "Warehouse Shipment" - OnBeforePickCreate / OnAfterPickCreate

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#9635]
Hi,
Would it be possible to have two new publishers, OnBeforePickCreate and OnAfterPickCreate in Action "Create Pick", Table 7335 Warehouse Shipment ? 
![image](https://user-images.githubusercontent.com/73548802/97335091-b913e700-187d-11eb-96a9-6c091f8d93c0.png)

With these integration events : 
![image](https://user-images.githubusercontent.com/73548802/97334939-908bed00-187d-11eb-8db0-565a3e742df3.png)

Thanks in advance
Regards

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
