### ISSUE TITLE
Common Data service connection setup issue in BC16.6

### ISSUE THREAD

**Issue by andrecavalcanti** [microsoft/ALAppExtensions#9636]
**Describe the bug**

I'm trying to set up common data services to connect to CRM. I'm using BC 16. 6 OnPrem. I enter the client id, client secret and I get the error below. I have tried it on BC16.3 and it works, as it uses user and password. BC16.6 uses client id and client secret.

**To Reproduce**

Go to Common Data service connection setup, enter the client id, client secret, and click on the enable.

**Expected behavior**
It should not give any error

**Screenshots**

![image](https://user-images.githubusercontent.com/6551266/97345883-0897ea00-1861-11eb-9025-a957c98ac7e9.png)

**5. Versions:**

AL Language:

Business Central: NA Business Central 16.6 (Platform 16.0.17024.0 + Application 16.6.17046.0)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
