### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeCreateInvtPutAwayPic & OnBeforeUpdateSalesLine & OnBeforeValidateShipToPostCode & OnBeforeLookupShipToPostCode & OnAfterUpdateSellToCont

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9637]
Hi Team,

In table 36, please provide the possibility to have **OnBeforeCreateInvtPutAwayPic** event in **CreateInvtPutAwayPic** procedure,
provide **OnBeforeUpdateSalesLine** event in **UpdateSalesLine** procedure,
provide **OnBeforeValidateShipToPostCode** event in **OnValidateShipToPostCode** trigger ,
provide **OnBeforeLookupShipToPostCode** event in **OnLookupShipToPostCode** trigger and
provide **OnAfterUpdateSellToCont** event in **OnValidateSellToCustomerNo** trigger

1. **OnBeforeCreateInvtPutAwayPic**
![image](https://user-images.githubusercontent.com/57799519/97388425-0afc5180-18fe-11eb-8c97-8543996a5f97.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeCreateInvtPutAwayPic(SalesHeader: Record "Sales Header")

2. **OnBeforeUpdateSalesLine**
![image](https://user-images.githubusercontent.com/57799519/97388914-287deb00-18ff-11eb-89e3-183dd26f0081.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeUpdateSalesLine(Rec: Record "Sales Header";ChangedFieldName: Text[100];VAR AskQuestion: Boolean)

Note: We have gone through updated code in **UpdateSalesLine** procedure, you can give event with "ChangedFieldNo" instead of "ChangedFieldName"

3. **OnBeforeValidateShipToPostCode**
![image](https://user-images.githubusercontent.com/57799519/97390033-df7b6600-1901-11eb-965d-d1fe792e0bd4.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeValidateShipToPostCode(var SalesHeader: Record "Sales Header"; var PostCodeRec: Record "Post Code"; CurrFieldNo: Integer; var IsHandled: Boolean)

4. **OnBeforeLookupShipToPostCode**
![image](https://user-images.githubusercontent.com/57799519/97390340-92e45a80-1902-11eb-98fd-8c62e43736a5.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeLookupShipToPostCode(var SalesHeader: Record "Sales Header"; var PostCodeRec: Record "Post Code"; var IsHandled: Boolean)

5. **OnAfterUpdateSellToCont**
![image](https://user-images.githubusercontent.com/57799519/97390722-798fde00-1903-11eb-8d5e-c9921b711979.png)

**Event:**
LOCAL [IntegrationEvent] OnAfterUpdateSellToCont(Rec: Record "Sales Header";HideValidationDialogue: Boolean)

_If possible, please backport the events to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
