### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - Function OnDelete - OnDeleteBeforeOnDeleteRecordInApprovalRequest

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9638]
Could You please, add the following event to the Table 36 "Sales Header"

Object: Table 36 "Sales Header"
Function: OnDelete

Publisher Event: OnDeleteBeforeOnDeleteRecordInApprovalRequest

Reason: To implement custom business logic and avoid deletion of approval request
Where is the event placed (see image attached)?:
![Image 27](https://user-images.githubusercontent.com/73465025/97418932-b9f25a80-1909-11eb-9bfa-82c5a3b34317.jpg)

Insert next 3 lines

IsHandled := false;
OnDeleteBeforeOnDeleteRecordInApprovalRequest(Rec, IsHandled);
if not IsHandled then

Above the line 
ApprovalsMgmt.OnDeleteRecordInApprovalRequest(RecordId);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnDeleteBeforeOnDeleteRecordInApprovalRequest(var SalesHeader: Record "Sales Header", var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
