### ISSUE TITLE
[Event Request] Page 7335 "Warehouse Shipment" - OnAfterRelease

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#9639]
Hi, would it be possible to have a new publisher OnAfterRelease in action Release, page 7335 "Warehouse Shipment" ? Like this  : 
![image](https://user-images.githubusercontent.com/73548802/97419582-86640000-190a-11eb-89c9-6fe27ab07f6b.png)
![image](https://user-images.githubusercontent.com/73548802/97419652-9845a300-190a-11eb-8065-143c2a7ccd24.png)

Thanks in advance

**Comment by RomanZanizdra** [comment]
Hi @VMotin . You can use excising event OnAfterRelease of the codeunit 7310 "Whse.-Shipment Release". Does it fit to your purpose?

**Comment by VMotin** [comment]
Hi Roman, thanks for your answer, I think your solution will do the trick !
