### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - Function OnDelete - OnDeleteBeforeOnDeleteRecordInApprovalRequest

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9640]
Could You please, add the following event to the Table 38 "Purchase Header"

Object: Table 38 "Purchase Header"
Function: OnDelete

Publisher Event: OnDeleteBeforeOnDeleteRecordInApprovalRequest

Reason: To implement custom business logic and pavoid deletion of approval request
Where is the event placed (see image attached)?:
![Image 30](https://user-images.githubusercontent.com/73465025/97422411-0e97d480-190e-11eb-8d8b-6f9841bf7c19.jpg)

Insert next 3 lines

IsHandled := false;
OnDeleteBeforeOnDeleteRecordInApprovalRequest(Rec, IsHandled);
if not IsHandled then

Above the line 
ApprovalsMgmt.OnDeleteRecordInApprovalRequest(RecordId);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnDeleteBeforeOnDeleteRecordInApprovalRequest(var PurchaseHeader: Record "Purchase Header", var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
