### ISSUE TITLE
[Event Request] Page 300 "Ship-To Address" - OnBeforeOnNewRecord

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9641]
Hi team,

In page 300, please provide the possibility to have the **OnBeforeOnNewRecord** event with 'IsHandled' in **OnNewRecord** trigger.

![image](https://user-images.githubusercontent.com/57799519/97423086-bcb67500-1934-11eb-9baa-1bf0462294a5.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeOnNewRecord(VAR Customer: Record Customer; VAR IsHandled: Boolean)

_If possible, Please backport the same change to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
