### ISSUE TITLE
[Event Request] Page 7365 "Whse. Reclassification Journal" - OnBeforeOpenJnl

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9642]
Hi Team,

In page 7365, please provide the possibility to have **OnBeforeOpenJnl** event in **OnOpenPage** trigger.

![image](https://user-images.githubusercontent.com/57799519/97429325-479b6d80-193d-11eb-8136-77e2e1bea205.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeOpenJnl(Rec: Record "Warehouse Journal Line"; VAR CurrentJnlBatchName: code[10])

_If possible, please backport the same event to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
