### ISSUE TITLE
[Event Request] Page 393 "Item Reclass. Journal" - OnBeforeOpenJnl

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#9643]
Hi Team,

In Page 393, please provide the possibility to have **OnBeforeOpenJnl** event in **OnOpenPage** trigger

![image](https://user-images.githubusercontent.com/57799519/97434448-09a24780-1945-11eb-9bb9-c7710ffafa54.png)

**Event:**
LOCAL [IntegrationEvent] OnBeforeOpenJnl(Rec: Record "Item Journal Line"; VAR CurrentJnlBatchName: Code[10])

_If possible, please backport the same event to BC14 also._

**Comment by RomanZanizdra** [comment]
Hi @Rambabu-Billuri . You can use existing event OnBeforeOpenJnl of codeunit 240 ItemJnlManagement. Does it fit to your need?

**Comment by Rambabu-Billuri** [comment]
Hi @RomanZanizdra . Yes we agree, OnBeforeOpenJnl  is satisfying our need. Thank You.
