### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - Function OnInitRecord - OnInitRecordOnBeforeAssigmentPostDescription

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9644]
Could You please, add the following event to the Table 36 "Sales Header"

Object: Table 36 "Sales Header"
Function: OnInitRecord

Publisher Event: OnInitRecordOnBeforeAssigmentPostDescription

Reason: To implement custom business logic and manage the field "Posting Description" externaly
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97443214-10bc5c00-192b-11eb-9811-7204dd1b0a71.png)

Insert next 3 lines

IsHandled := false;
OnInitRecordOnBeforeAssigmentPostDescription(Rec, IsHandled);
if not IsHandled then

Above the line 
"Posting Description" := Format("Document Type") + ' ' + "No.";

Event Code:
[IntegrationEvent(false, false)]
local procedure OnInitRecordOnBeforeAssigmentPostDescription(var SalesHeader: Record "Sales Header", var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
