### ISSUE TITLE
[Enum Request] Table 7134 "Budget Entry" - Field2 "Analysis Area" and Field6 "Source Type"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#9646]
Please implement "Analysis Area" and "Source Type" as extensable enums so we can use and enhance these values in our apps.

**Comment by AlexanderYakunin** [comment]
This is very large area, attempts to implement Analysis Area Type enum end up with huge volume of changes. A lot of global procedures should be overloaded with new set of parameters for this implementation.

I need to understand what kind of extension you need? Specifically, for Analysis Area field. Source Type create less problems.

**Comment by GuntherGebauer** [comment]
We want to use "Analysis Area" in our extension, which has its own forecast and the ability to export/import into/from Standard Item Budget Entries. Of course we can leave the "Analysis Area" also as an option and need to translate every occurence in our app on our own.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
