### ISSUE TITLE
[Event Request]Codeunit 1002 - CreateSalesInvoice

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/ALAppExtensions#9647]
Hi,

I want to create many Sales Invoices from Job Planning line using CreateSalesInvoice method. For each job planning Line I call this procedure but I receive the same number of Message() at the end of the process. 

As you can see, line 74 messages are displayed:
![image](https://user-images.githubusercontent.com/29598240/97459129-b8da2100-193b-11eb-85f7-82b65871bb22.png)

Is it possible to add an event just before the test of CrMemo in order to prevent these messages ?

We want something like this:

```
...
Commit();
// Add Event HERE
OnAfterCreateSalesInvoice(JobPlanningLine, CrMemo, Handled);
if not Handled then begin // Add this condition before displaying messages
    if CrMemo then
       Message(Text008)
     else
       Message(Text000);
end
...
```

Thanks !

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
