### ISSUE TITLE
Integration Event - Codeunit 396 NoSeriesManagement - IT Version

### ISSUE THREAD

**Issue by Giumai** [microsoft/ALAppExtensions#9648]
Is it possible to publish two new events in Cod 396 NoSeriesManagement?
One for the function CheckSalesDocNoGaps and one for the function CheckPurchDocNoGaps to skip in particular conditions these checks.

Thanks

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
