### ISSUE TITLE
Requirement. The ability to update Sales reservations, when a reservation change source type.

### ISSUE THREAD

**Issue by leachxpe** [microsoft/ALAppExtensions#9649]
My Users need to know how much stock is reserved on inventory and how much they are still waiting to come in.

Change Request.
A new EventSub on Codeunit CreateResrvEntry, Procedure TransferReservEntry. when the partner-record has it's quantity / Shipment Date updated (on code line 359 / line 379 / line 390)
OnBeforeModifyNewReservationEntry (Var OldReservEntry ; Var NewReservEntry ) {per each modify}
2nd event On Line 418 - OnAfterModifyNewReservationEntry (Var OldReservEntry ; Var NewReservEntry )

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
