### ISSUE TITLE
[Event Request] Codeunit 8611 "Config. Package Management" - OnBeforeSetFieldFilter 

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9650]
We are migrating our code from NAV 2018 to BC16.4. In the Codeunit 8611 "Config. Package Management", in the procedure
SetFieldFilter we would like to modify the code depending on the table that calls the procedure. To do so, we need
a IsHandled flag and an event publisher, like this :

![publisher](https://user-images.githubusercontent.com/34645582/97545829-db1b7f80-19cb-11eb-999d-54fa71c81234.png)

With this integration event :
![integration](https://user-images.githubusercontent.com/34645582/97545929-043c1000-19cc-11eb-8b88-964948709431.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
