### ISSUE TITLE
[Event Request] Table 81 "Gen. Lournal Line" - Function RenumberDocNoOnLines - OnBeforeRenumberDocNoOnLines

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9651]
Could You please, add the following event to the Table 38 "Purchase Header"

Object: Table 81 "Gen. Lournal Line" 
Function: RenumberDocNoOnLines

Publisher Event: OnBeforeRenumberDocNoOnLines

Reason: To implement custom business logic and pavoid deletion of approval request
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97555419-6438b380-19d8-11eb-9cd7-31c42cd9d87d.png)

At the begining of the function
Insert next 4 lines

IsHandled := false;
OnBeforeRenumberDocNoOnLines(DocNo, GenJnlLine2, IsHandled);
if IsHandled then
    exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeRenumberDocNoOnLines(var DocNo: Code[20]; var GenJnlLine2: Record "Gen. Journal Line"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
