### ISSUE TITLE
[EventRequest] Report 2000019- Suggest Vendor Payments EB - SetPaymJnlLine

### ISSUE THREAD

**Issue by RishtaCader** [microsoft/ALAppExtensions#9652]
Hello,
We need new event in the Report 2000019 (OnBeforeInsertSetPaymJnlLine) :

 procedure SetPaymJnlLine()
    var
        DimMgt: Codeunit DimensionManagement;
        DimSetIDArr: array[10] of Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetPaymJnlLine(VendLedgEntry, IsHandled);
        if IsHandled then
            exit;

        with PaymJnlLine do begin
            // if the invoice already is attached to an unposted Payment Line, we skip it
            PaymJnlLine2.Reset();
            PaymJnlLine2.SetCurrentKey("Account Type", "Account No.");
            PaymJnlLine2.SetRange("Account Type", PaymJnlLine2."Account Type"::Vendor);
            PaymJnlLine2.SetRange("Account No.", VendLedgEntry."Vendor No.");
            PaymJnlLine2.SetRange("Applies-to Doc. Type", VendLedgEntry."Document Type");
            PaymJnlLine2.SetRange("Applies-to Doc. No.", VendLedgEntry."Document No.");
            PaymJnlLine2.SetFilter(Status, '<>%1', PaymJnlLine2.Status::Posted);
            if not PaymJnlLine2.FindFirst then begin
                Init;
                "Journal Template Name" := PaymJnlTemplate.Name;
                "Journal Batch Name" := PaymJnlBatch.Name;
                "Line No." := "Line No." + 10000;
                .......
                if "Amount (LCY)" <> 0 then begin
                    CreateDim(
                      DimMgt.TypeToTableID2000001("Account Type"), "Account No.",
                      DATABASE::"Bank Account", "Bank Account",
                      DATABASE::"Salesperson/Purchaser", "Salespers./Purch. Code");
                    if "Dimension Set ID" <> VendLedgEntry."Dimension Set ID" then begin
                        DimSetIDArr[1] := "Dimension Set ID";
                        DimSetIDArr[2] := VendLedgEntry."Dimension Set ID";
                        "Dimension Set ID" :=
                            DimMgt.GetCombinedDimensionSetID(DimSetIDArr, "Shortcut Dimension 1 Code", "Shortcut Dimension 2 
                            Code");
                    end;
                   // New event request >>
                   OnBeforeInsertSetPaymJnlLine(PaymJnlLine,VendLedgEntry);
                   // New event request <<
                    Insert;
                end;

Signature :
LOCAL [IntegrationEvent] OnBeforeInsertSetPaymJnlLine(VAR PaymJnlLine : Record "Payment Journal Line"; VendorLedgEntry : Record "Vendor Ledger Entry")

Thank you
Kind Regards
Rishta

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
