### ISSUE TITLE
[Event Request] Table 130 "Incoming Document" - Function OnDelete - OnDeleteBeforeDeleteApprovalEntries

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9653]
Could You please, add the following event to the Table 130 "Incoming Document"

Object: Table 130 "Incoming Document"
Function: OnDelete

Publisher Event: OnDeleteBeforeDeleteApprovalEntries

Reason: To implement custom business logic and avoid deletion of approval request
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97563406-4a509e00-19e3-11eb-96d4-d4659abfe6ab.png)

Insert Above the line
ApprovalsMgmt.DeleteApprovalEntries(RecordId);

the next 3 lines:

IsHandled := false;
OnDeleteBeforeDeleteApprovalEntries(Rec, IsHandled);
if not IsHandled then

Event Code:
[IntegrationEvent(false, false)]
local procedure OnDeleteBeforeDeleteApprovalEntries(var IncomingDoc: Record "Incoming Document"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
