### ISSUE TITLE
[ENUM REQUEST] Table 210 Job Journal Line, Field 6: Type (Also T169)

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9654]
Can Field 6 from table 210 & 169 converted to ENUM. We want to extend on this Option Value.

field(6; Type; Option)
{
            Caption = 'Type';
            OptionCaption = 'Resource,Item,G/L Account';
            OptionMembers = Resource,Item,"G/L Account";
}

//BC160

**Comment by AlexanderYakunin** [comment]
We already have this enum in 17.0 and up

        field(6; Type; Enum "Job Journal Line Type")
        {
            Caption = 'Type';

**Comment by guidorobben** [comment]
Hi alexander,

Will this be ported back to 16?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AlexanderYakunin** [comment]
No, we do not downgrade enum implementations. More details available here: https://github.com/Microsoft/ALAppExtensions/blob/master/FAQ.md#what-do-all-the-labels-assigned-to-issues-mean

**Comment by guidorobben** [comment]
Thanks for your answer.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
