### ISSUE TITLE
[Event Request] Codeunit 99000845 "Reservation Management" - OnAfterCalcReservedQtyOnPick

### ISSUE THREAD

**Issue by nlajos** [microsoft/ALAppExtensions#9655]
Hi,

I would like to request for a new event at the end of the CalcReservedQtyOnPick function in Reservation Management codeunit (99000845). Please include AllocQty and AvailQty as Var, and the CalcReservEntry record.

Is it possible to include this event in BC 14 version also?

Thanks

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
