### ISSUE TITLE
[Event Request] Table 130 "Incoming Document" - Function CreateManually - OnBeforeCreateManually

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9656]
Could You please, add the following event to the Table 130 "Incoming Document"

Object: Table 130 "Incoming Document"
Function: CreateManually

Publisher Event: OnBeforeCreateManually

Reason: To implement custom business logic to replace the function CreateManually by other one.
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97564711-4756ad00-19e5-11eb-85e4-f18aa6df03cb.png)

At the begining of the function

Insert the next 4 lines:

IsHandled := false;
OnBeforeCreateManually(Rec, IsHandled);
if IsHandled then
    exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCreateManually(var IncomingDoc: Record "Incoming Document"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
