### ISSUE TITLE
[ENUM REQUEST] table 1003 "Job Planning Line"; Field 5

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9657]
Can Field 5 from table 1003 converted to ENUM. We want to extend on this Option Value.

field(5; Type; Option)
{
           Caption = 'Type';
            OptionCaption = 'Resource,Item,G/L Account,Text';
            OptionMembers = Resource,Item,"G/L Account",Text;
}

//BC160

**Comment by AlexanderYakunin** [comment]
We already have this enum in 17.0 and up

        field(5; Type; Enum "Job Planning Line Type")
        {
            Caption = 'Type';
