### ISSUE TITLE
[Event Request] Table 130 "Incoming Document" - Function CreateManually - OnAfterCreateManually 

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9658]
Could You please, add the following event to the Table 130 "Incoming Document"

Object: Table 130 "Incoming Document"
Function: CreateManually

Publisher Event: OnAfterCreateManually

Reason: To implement custom business logic to add functionality at the function CreateManually
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97568120-3313af80-19e7-11eb-8266-34ab9afe127b.png)

At the end of the function

Insert the call to the event

OnAfterCreateManually(Rec);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterCreateManually(var IncomingDoc: Record "Incoming Document")
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
