### ISSUE TITLE
[extensibility-bug] procedure FillBufferInternal Table "Option Lookup Buffer"

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#9659]
The function FillBufferInternal now uses FieldRef.EnumValueCount(). 
But this function returns only the number of Enum elements. This is not useful for the function IncludeOption.
The function IncludeOption must be called with the Enum Ordinal to enable Enum Values of a extension. 
Currently the function IncludeOption is called with 0,1,2,3,4,5,6,7,8. But the call 0,1,2,3,4,5,50xxxx0,50xxxx1,50xxxx2 is required.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
