### ISSUE TITLE
BaseApp cannot be published (BC170)

### ISSUE THREAD

**Issue by Pavel-Titov** [microsoft/ALAppExtensions#9660]
Hi, I have a problem to publish the BaseApp from BC170 (the customized one, after merge and upgrade to BC170).
I am getting these errors:

CustomerCard.Page.al(2268,16): error AL0122: Cannot implicitly convert type 'None' to 'Boolean'
CustomerCard.Page.al(2271,16): error AL0122: Cannot implicitly convert type 'None' to 'Boolean'
CustomerCard.Page.al(2274,16): error AL0122: Cannot implicitly convert type 'None' to 'Boolean'

Here is the code that stands in those lines:

```
            if TryGetDictionaryValueFromKey(Results, CustomerCardCalculations.GetAvgDaysPastDueDateLabel(), DictionaryValue) then
                Evaluate(DaysPastDueDate, DictionaryValue);

            if TryGetDictionaryValueFromKey(Results, CustomerCardCalculations.GetExpectedMoneyOwedLabel(), DictionaryValue) then
                Evaluate(ExpectedMoneyOwed, DictionaryValue);

            if TryGetDictionaryValueFromKey(Results, CustomerCardCalculations.GetAvgDaysToPayLabel(), DictionaryValue) then
                Evaluate(AvgDaysToPay, DictionaryValue);
```
The function is new and was introduced recently:

```
    [TryFunction]
    local procedure TryGetDictionaryValueFromKey(var DictionaryToLookIn: Dictionary of [Text, Text]; KeyToSearchFor: Text; var ReturnValue: Text)
    begin
        ReturnValue := DictionaryToLookIn.Get(KeyToSearchFor);
    end;

```
Interesting fact - if I change the function definition like this:

```
    [TryFunction]
    local procedure TryGetDictionaryValueFromKey(var DictionaryToLookIn: Dictionary of [Text, Text]; KeyToSearchFor: Text; var ReturnValue: Text): **Boolean**
    begin
        ReturnValue := DictionaryToLookIn.Get(KeyToSearchFor);
    end;

```
Then I am getting the compilation error, so I cannot build the BaseApp:
error AL0244: The signature of procedure 'TryGetDictionaryValueFromKey' does not match the signature required by attribute 'TryFunction': return value is expected to be of type 'None' but found type 'Boolean'. The expected signature is: TryGetDictionaryValueFromKey().

AL Extension Version: 6.1.359074
Server Version:
Version: (blank) (Platform 17.0.16974.0 + Application 17.0.16993.0)
Azure AD tenant: common, Environment: Production (Production)

**Comment by Pavel-Titov** [comment]
#6265

**Comment by Pavel-Titov** [comment]
https://github.com/microsoft/AL/issues/6265

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
