### ISSUE TITLE
[Event Request] Table 133 "Incoming Document Attachment" - Function SetFiltersFromMainRecord - OnBeforeSetFiltersFromMainRecord

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9661]
Could You please, add the following event to the Table 133 "Incoming Document Attachment"

Object: Table 133 "Incoming Document Attachment"
Function: SetFiltersFromMainRecord

Publisher Event: OnBeforeSetFiltersFromMainRecord

Reason: To implement custom business logic to replace the function SetFiltersFromMainRecord by other one.
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97586453-92c78600-19fa-11eb-821f-ca5b2ac1eac0.png)

At the begining of the function

Insert the next 4 lines:

IsHandled := false;
OnBeforeSetFiltersFromMainRecord(MainRecordRef, IncomingDocumentAttachment, IsHandled);
if IsHandled then
exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeSetFiltersFromMainRecord(var MainRecordRef: RecordRef; var IncomingDocumentAttachment: Record "Incoming Document Attachment"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
