### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeOnValidateBinCodeUOMCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9664]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the field 7300 "Bin Code", in the trigger OnValidate, we would like to add our code in the "if Location."Directed Put-away and Pick""satement. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/97596276-d7581f00-1a04-11eb-9ae4-8eb21370db22.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/97596175-bdb6d780-1a04-11eb-8439-09841268b80e.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
