### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnAfterOnValidateBinCodeBinContentGet

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9665]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the field 7300 "Bin Code", in the trigger OnValidate, we would like to add our code at the end of the "if BinContent.Get(...)"satement. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/97597140-cbb92800-1a05-11eb-905d-45357e687131.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/97597065-b643fe00-1a05-11eb-81bc-a6de510dc8f3.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by RomanZanizdra** [comment]
Hi @Magicrevette .
You asked "handled" event but did not specified how IsHandled should be used. Looks like you copy/pasted code from https://github.com/microsoft/ALAppExtensions/issues/9666. Please, recheck requirements.

**Comment by Magicrevette** [comment]
Indeed, it's an error of mine. We doesn't need a IsHandled flag here. There is what we really need :

![image](https://user-images.githubusercontent.com/34645582/98360029-6e3a6200-2029-11eb-8b21-0db2f7432835.png)

![image](https://user-images.githubusercontent.com/34645582/98358802-8ad59a80-2027-11eb-867d-3a57614ea151.png)

Sorry for that.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
