### ISSUE TITLE
CU1002 Requesting a new parameter to event OnCreateSalesInvoiceOnBeforeRunReport

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#9667]
Requesting that the parameter that is passed into the function "CreateSalesInvoice" will be added to the event function "OnCreateSalesInvoiceOnBeforeRunReport"

![image](https://user-images.githubusercontent.com/28901234/97598717-2733e780-19ff-11eb-8b7c-5e96b651f696.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
