### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeCheckInvalidBinCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9668]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the procedure CheckInvalidBinCode, we would like to condition the use of this procedure. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/97598689-839b0500-1a07-11eb-9027-4ab8c12d1718.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/97598627-754ce900-1a07-11eb-89ab-a4ba713dad17.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
