### ISSUE TITLE
[Event Request] Table 454 "Approval Entry" - Function ShowRecord - OnBeforeShowRecord

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9669]
Could You please, add the following event to the Table 454 "Approval Entry" 

Object: Table 454 "Approval Entry" 
Function: ShowRecord

Publisher Event: OnBeforeShowRecord

Reason: To implement custom business logic to replace the function ShowRecord by other one, I can not use the event OnAfterGetPageID in codeunit Page Management, because i need to run diferent pages for certain records only from this table.
I've decided to pass the Rec by reference if  someone need it in the future

Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97617634-4aba5a80-1a1e-11eb-998f-bb38ec20074e.png)

At the begining of the function

Insert the next 4 lines:

IsHandled := false;
OnBeforeShowRecord(Rec, IsHandled);
if IsHandled then
exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeShowRecord(var ApprovalEntry: Record "Approval Entry"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
