### ISSUE TITLE
[Function Request] Codeunit 3001 Matches and MatchesIgnoreCase

### ISSUE THREAD

**Issue by josnelissen** [Microsoft/ALAppExtensions#967]
Dear AL team,

we are in need for two functions in codeunit 3001: Matches and MatchesIgnoreCase to get a DotnetArray as result. Could you please add them to this codeunit?

![matches-machesignorecasre](https://user-images.githubusercontent.com/30867508/51820539-5ff8d700-22d6-11e9-9d17-1441b35737c5.jpg)

Best regards Jos Nelissen

**Comment by IhorHandziuk** [comment]
Hello @josnelissen and thank you for your request. Recently we added a lot of new functions to RegEx wrapper (as you can see in [this PR](https://github.com/Microsoft/cal-open-library/pull/118)), so now you should be able to use them
