### ISSUE TITLE
[Event Request] Table 454 "Approval Entry" - Function RecordCaption - OnBeforeRecordCaption

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9670]
Could You please, add the following event to the Table 454 "Approval Entry"

Object: Table 454 "Approval Entry"
Function: RecordCaption

Publisher Event: OnBeforeRecordCaption

Reason: To implement custom business logic to replace the function RecordCaption by other one,
I've decided to pass the Rec by reference if someone need it in the future

Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97619432-80f8d980-1a20-11eb-9724-23ea605502fd.png)

Declare the local Var:
ReturnCaption: Text

At the begining of the function
Insert the next 4 lines:

IsHandled := false;
RetTextOnBeforeRecCap := OnBeforeRecordCaption(Rec, ReturnCaption, IsHandled);
if IsHandled then
exit(ReturnCaption);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeRecordCaption(var ApprovalEntry: Record "Approval Entry"; var ReturnCaption: Text; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
