### ISSUE TITLE
[Access Request] Page 36642 Customer Credit Factbox CustLedgerEntry variable access 

### ISSUE THREAD

**Issue by rellorin** [microsoft/ALAppExtensions#9671]
We have the need to further filter the CustLedgerEntry records in our page extension of the Customer Credit Factbox page.

We request that you make the below variable Protected:
CustLedgerEntry: array[4] of Record "Cust. Ledger Entry";

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
