### ISSUE TITLE
[Event Request] Table 5612 "FA Depreciation Book" - Function OnDelete - OnBeforeOnDelete

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9672]
Could You please, add the following event to the Table 5612 "FA Depreciation Book"

Object: Table 5612 "FA Depreciation Book"
Function: OnDelete

Publisher Event: OnBeforeOnDelete

Reason: To implement custom business logic to replace the function OnDelete by other one,

Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/97675943-33b45080-1a90-11eb-81e8-04a73eb0d4b7.png)

At the begining of the function
Insert the next 4 lines:

IsHandled := false;
OnBeforeOnDelete(Rec, xRec, IsHandled);
if IsHandled then
    exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeOnDelete(var FADeprecBook: Record "FA Depreciation Book"; xFADeprecBook: Record "FA Depreciation Book"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
