### ISSUE TITLE
[ENUM REQUEST] table 49 "Invoice Post. Buffer"; Field 1

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9674]
Can Field 1 from table 49 converted to ENUM. We want to extend on this Option Value.

field(1; Type; Option)
        {
            Caption = 'Type';
            DataClassification = SystemMetadata;
            OptionCaption = 'Prepmt. Exch. Rate Difference,G/L Account,Item,Resource,Fixed Asset';
            OptionMembers = "Prepmt. Exch. Rate Difference","G/L Account",Item,Resource,"Fixed Asset";
        }

//BC160

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
