### ISSUE TITLE
CU 1002 Add Parameter to functions and event publishers

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#9675]
Can you add the JobPlanningLine as a parameter to the functions in CU 1002, Job Create-Invoice

- CreateSalesHeader
- TestSalesHeader

which are used in the function: **CreateSalesInvoiceLines** 

![image](https://user-images.githubusercontent.com/28901234/97721134-fb793600-1ac0-11eb-91fe-0a41233c6cce.png)

And to the publishers inside these functions (shown in yellow):

![image](https://user-images.githubusercontent.com/28901234/97721238-1ba8f500-1ac1-11eb-99d7-64adf750931a.png)

![image](https://user-images.githubusercontent.com/28901234/97721268-25325d00-1ac1-11eb-96db-55b300df0e4d.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by dagnybjork** [comment]
Can you add the JobPlanningLine as a parameter to the functions in CU 1002, Job Create-Invoice

CreateSalesHeader **
TestSalesHeader **

        if LineCounter = 0 then
                    Error(Text002,
                    JobPlanningLine.TableCaption,
                    JobPlanningLine.FieldCaption("Qty. to Transfer to Invoice"));


        if NewInvoice then
            **CreateSalesHeader(Job, PostingDate, JobPlanningLine)**
        else
            **TestSalesHeader(SalesHeader, Job, JobPlanningLine);**
        if JobPlanningLine.Find('-') then
            repeat
                if TransferLine(JobPlanningLine) then begin
                    if JobPlanningLine.Type in [JobPlanningLine.Type::Resource,
                                                JobPlanningLine.Type::Item,
                                                JobPlanningLine.Type::"G/L Account"]
                    then
                        JobPlanningLine.TestField("No.");

And to the publishers inside these functions:

        local procedure CreateSalesHeader(Job: Record Job; PostingDate: Date; JobPlanningLine: Record "Job Planning Line")
            var
                SalesSetup: Record "Sales & Receivables Setup";
                Cust: Record Customer;
                IsHandled: Boolean;
            begin
                OnBeforeCreateSalesHeader(Job, PostingDate, SalesHeader2, JobPlanningLine);

                SalesSetup.Get();
                SalesHeader.Init();
                SalesHeader."Document Type" := SalesHeader2."Document Type";
                if SalesHeader."Document Type" = SalesHeader."Document Type"::Invoice then
                    SalesSetup.TestField("Invoice Nos.");
                if SalesHeader."Document Type" = SalesHeader."Document Type"::"Credit Memo" then
                    SalesSetup.TestField("Credit Memo Nos.");
                SalesHeader."Posting Date" := PostingDate;
                OnBeforeInsertSalesHeader(SalesHeader, Job, JobPlanningLine);
                SalesHeader.Insert(true);
                Cust.Get(Job."Bill-to Customer No.");
                Cust.TestField("Bill-to Customer No.", '');
                SalesHeader.Validate("Sell-to Customer No.", Job."Bill-to Customer No.");
                if Job."Currency Code" <> '' then
                    SalesHeader.Validate("Currency Code", Job."Currency Code")
                else
                    SalesHeader.Validate("Currency Code", Job."Invoice Currency Code");
                if PostingDate <> 0D then
                    SalesHeader.Validate("Posting Date", PostingDate);

                IsHandled := false;
                OnCreateSalesHeaderOnBeforeUpdateSalesHeader(SalesHeader, Job, IsHandled, JobPlanningLine);
                if not IsHandled then
                    UpdateSalesHeader(SalesHeader, Job);
                OnBeforeModifySalesHeader(SalesHeader, Job, JobPlanningLine);
                SalesHeader.Modify(true);
            end;


    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateSalesHeader(Job: Record Job; PostingDate: Date; var SalesHeader2: Record "Sales Header"; JobPlanningLine: Record "Job Planning Line")
    begin
    end;


    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertSalesHeader(var SalesHeader: Record "Sales Header"; Job: Record Job; JobPlanningLine: Record "Job Planning Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateSalesHeaderOnBeforeUpdateSalesHeader(var SalesHeader: Record "Sales Header"; var Job: Record Job; var IsHandled: Boolean; JobPlanningLine: Record "Job Planning Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifySalesHeader(var SalesHeader: Record "Sales Header"; Job: Record Job; JobPlanningLine: Record "Job Planning Line")
    begin
    end;



    local procedure TestSalesHeader(var SalesHeader: Record "Sales Header"; var Job: Record Job; JobPlanningLine: Record "Job Planning Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeTestSalesHeader(SalesHeader, Job, IsHandled, JobPlanningLine);
        if IsHandled then
            exit;

        SalesHeader.TestField("Bill-to Customer No.", Job."Bill-to Customer No.");
        SalesHeader.TestField("Sell-to Customer No.", Job."Bill-to Customer No.");

        if Job."Currency Code" <> '' then
            SalesHeader.TestField("Currency Code", Job."Currency Code")
        else
            SalesHeader.TestField("Currency Code", Job."Invoice Currency Code");
        OnAfterTestSalesHeader(SalesHeader, Job, JobPlanningLine);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestSalesHeader(var SalesHeader: Record "Sales Header"; Job: Record Job; var IsHandled: Boolean; JobPlanningLine: Record "Job Planning Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterTestSalesHeader(var SalesHeader: Record "Sales Header"; Job: Record Job; JobPlanningLine: Record "Job Planning Line")
    begin
    end;

```

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
