### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeTestFieldWhseShptLineBinCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9677]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the procedure CheckWhseDocLine, we would like to add a condition to the call of "TestField("Bin Code", WhseShptLine."Bin Code")". To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/97724578-616bba80-1acd-11eb-8617-b4cf5f3491ca.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/97724427-2ec1c200-1acd-11eb-8f98-b0d54de0a9ad.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
