### ISSUE TITLE
CU1002 Funtion "FindInvoices" Add new publisher event

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#9678]
Requesting a new publisher event at the end of function "FindInvoices" in CU1002

Publisher event: 
OnFindInvoicesOnBeforeInsertTempJobPlanningLineInvoice

                    TempJobPlanningLineInvoice."Document No." := JobPlanningLineInvoice."Document No.";
                    TempJobPlanningLineInvoice."Quantity Transferred" := JobPlanningLineInvoice."Quantity Transferred";
                    TempJobPlanningLineInvoice."Invoiced Amount (LCY)" := JobPlanningLineInvoice."Invoiced Amount (LCY)";
                    TempJobPlanningLineInvoice."Invoiced Cost Amount (LCY)" := JobPlanningLineInvoice."Invoiced Cost Amount (LCY)";
                    TempJobPlanningLineInvoice."Invoiced Date" := JobPlanningLineInvoice."Invoiced Date";
                    TempJobPlanningLineInvoice."Transferred Date" := JobPlanningLineInvoice."Transferred Date";
                    OnFindInvoicesOnBeforeInsertTempJobPlanningLineInvoice(TempJobPlanningLineInvoice,JobPlanningLineInvoice);
                    TempJobPlanningLineInvoice.Insert();
                end;
            until JobPlanningLineInvoice.Next = 0;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnFindInvoicesOnBeforeInsertTempJobPlanningLineInvoice(var TempJobPlanningLineInvoice: Record "Job Planning Line Invoice"; JobPlanningLineInvoice: Record "Job Planning Line Invoice")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
