### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeTestFieldProdOrderCompLineBinCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9679]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the procedure CheckWhseDocLine, we would like to add a condition to the call of "TestField("Bin Code", WhseShptLine."Bin Code")". To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/97727191-6aaa5680-1ad0-11eb-8691-7603c6a45a09.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/97727330-93cae700-1ad0-11eb-9617-4937a8d62a11.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
