### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeWhseDocumentTypeShipment

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9680]
We are migrating our code from NAV 2018 to BC16.4. In the Table 5767 "Warehouse Activity Line", in the procedure UpdateRelatedItemTrkg, we would like to add a condition to the use of "WhseItemTrkgLine.SetRange()" methods in case of "WhseActivLine."Whse. Document Type"::Shipment". To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/97735056-1f954100-1ada-11eb-9645-43ebe7866484.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/97734963-12785200-1ada-11eb-8ea2-53de428718d6.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
