### ISSUE TITLE
AL Test Tool: "Update Test Methods" only on a selected/filtered number of test codeunits in the AL Test Tool

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/ALAppExtensions#9681]
As reported on yammer (https://www.yammer.com/dynamicsnavdev/threads/925303939506176) I was wondering:

`How do I get to work **Update Test Methods** only on a selected/filtered number of test codeunits in the AL Test Tool?`

It seems to always process all test codeunits in a suite, which is a nuisance if I only want a single or a couple of test codeunits to be updated.

I would like to suggest the following change:

`"Update Test Methods" should only operate on the test codeunits in the filtered view. If there is no filter it will operate on all test codeunits.`

As per the suggestion of @nikolakukrika I will implement it myself and provide a pull request.

### Note
In (CAL) Test Tool this is done only for the selected test codeunit (line).

**Comment by lvanvugt** [comment]
Hi @StanPesotskiy, (long-time-no-see ;-). Why is this closed and set to feature-request?

**Comment by StanPesotskiy** [comment]
Hi Luc! It was the result of a clean up. I marked it as a Feature-request but requests with such tags do not go to our backlog.
But your request is not a regular one as you suggest a solution. I would expect that you get some review comments  instead of a thread here. Do you expect some activity from MS here?

**Comment by lvanvugt** [comment]
Sure, I do expect activity. This thing is bugging me. ;-)

**Comment by JesperSchulz** [comment]
Following up on this active issue. What exactly is the request here? I'm slightly confused :-)

**Comment by lvanvugt** [comment]
The issue is that when I execute the **Update Test Methods** is updates _all_ test codeunits irrespective of having only selected one or put a filter on the suite. This is very annoying when I am working on tests and want to first work only on a subset of methods and later add the rest of the methods for one codeunit. If I recall right this is how the CAL Test Tool did do it.

**Comment by JesperSchulz** [comment]
Got it. I just needed to make sure I understand, because of the "i will implement it myself" vs. feature request. We'll see what we can do!

**Comment by lvanvugt** [comment]
Well, I did implement it and provided a pull request for that. Don't know what came of it eventually.

**Comment by JesperSchulz** [comment]
We're going to get this fixed from our end :-) Shouldn't be too hard, so let's just get it done.

**Comment by JesperSchulz** [comment]
Closing issue as "Won't Fix", as agreed upon with @nikolakukrika.
