### ISSUE TITLE
[Event Request] Codeunit::"Blanket Purch. Order to Order" - Function OnRun - OnRunOnBeforeCheckQtyOnOrders

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9685]
We like to request the following Event:
Object: Codeunit::"Blanket Purch. Order to Order"
Function: OnRun
Publisher Event: OnRunOnBeforeCheckQtyOnOrders
Reason: To implement custom business logic
Where is the event placed:
PurchBlanketOrderLine.Reset();
        PurchBlanketOrderLine.SetRange("Document Type", "Document Type");
        PurchBlanketOrderLine.SetRange("Document No.", "No.");
        if PurchBlanketOrderLine.FindSet then
            repeat
                if (PurchBlanketOrderLine.Type = PurchBlanketOrderLine.Type::" ") or
                   (PurchBlanketOrderLine."Qty. to Receive" <> 0)
                then begin
                    IsHandled := false;
                    OnRunOnBeforeCheckQtyOnOrders(PurchBlanketOrderLine, IsHandled);
                    if not IsHandled then begin
                        PurchLine.SetCurrentKey("Document Type", "Blanket Order No.", "Blanket Order Line No.");
                        PurchLine.SetRange("Blanket Order No.", PurchBlanketOrderLine."Document No.");
                        PurchLine.SetRange("Blanket Order Line No.", PurchBlanketOrderLine."Line No.");
                        QuantityOnOrders := 0;
                        if PurchLine.FindSet then
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeCheckQtyOnOrders(var BlanketOrderPurchLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by RomanZanizdra** [comment]
Hi @acadonAG-dev . Please specify, where do you need the "end" statement for "if not IsHandled then begin"

**Comment by acadonAG-dev** [comment]
We need the end statement after CheckBlanketOrderLineQuantity.
![image](https://user-images.githubusercontent.com/68000891/98515212-01160f00-226b-11eb-8182-714e8d900f53.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
