### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function CreateToAsmLines - OnCreateToAsmLinesOnAfterValidateQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9696]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: CreateToAsmLines
Publisher Event: OnCreateToAsmLinesOnAfterValidateQty
Reason: To implement custom business logic
Where is the event placed:
end else begin
                    ToAssemblyLine.Validate(Type, FromAsmLine.Type);
                    ToAssemblyLine.Validate("No.", FromAsmLine."No.");
                    ToAssemblyLine.Validate("Resource Usage Type", FromAsmLine."Resource Usage Type");
                    ToAssemblyLine.Validate("Unit of Measure Code", FromAsmLine."Unit of Measure Code");
                    if ToAssemblyLine.Type <> ToAssemblyLine.Type::" " then
                        ToAssemblyLine.Validate("Quantity per", FromAsmLine."Quantity per");
                    ToAssemblyLine.Validate(Quantity, GetAppliedQuantityForAsmLine(BasicAsmOrderCopy, ToAsmHeader, FromAsmLine, ToSalesLine));
                end;
                OnCreateToAsmLinesOnAfterValidateQty (ToAsmHeader, FromAsmLine, ToAssemblyLine, ToSalesLine, BasicAsmOrderCopy, AvailabilityCheck);
                ToAssemblyLine.ValidateDueDate(ToAsmHeader, ToAsmHeader."Starting Date", false);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCreateToAsmLinesOnAfterValidateQty (ToAsmHeader: Record "Assembly Header"; var FromAsmLine: Record "Assembly Line"; var ToAssemblyLine: Record "Assembly Line"; ToSalesLine: Record "Sales Line"; BasicAsmO

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
