### ISSUE TITLE
[Event Request] Record::"Sales Header" - OnLookup Trigger Payment Method Code

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#9701]
Another page is called (matrix) for appropriate payment choice.

**Comment by AlexanderYakunin** [comment]
We cannot accept requests with short text only. Please show the code and event specification.

**Comment by SWE-Tina** [comment]
local procedure "Sales Header_OnLookupPaymentMethodEvent"(var Rec: Record "Sales Header")

Code filters a matrix regarding circumstances of sales header data and opens a filtered matrix page. On this page you can choose (depending on set data) payment conditions fot the customer.

**Comment by AlexanderYakunin** [comment]
Asking again, can you provide this trigger code and event specification with list of parameters? Do you know what if we add code to this trigger, it will overwrite standard lookup behavior based on table relation?

**Comment by StanPesotskiy** [comment]
We are not adding an alternate OnLookup code to the table field. 
You can add OnLookup trigger by an extension to the pages where you need a special behavior.
