### ISSUE TITLE
[Event Request] [Function Request] Record::"Service Line" HideReplacementDialog Handling impossible

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#9706]
We need either a function "IsHideReplacementDialog() : Boolean" to get status of HideReplacementDialog or an integration event "OnAfterSetHideReplacementDialog(ServiceLine: Record “Service Line”; var HideReplacementDialog : Boolean)" to react after it is set 
- preferred both :).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
