### ISSUE TITLE
[Event Issue] Record::"Service Line" OnCheckItemAvailableOnBeforeCheckNonStock 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#9707]
IsHandled isn't handled :) ("if IsHandled than Exit();"  is missing).

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
