### ISSUE TITLE
[Protection Level] Record::"Cust. Ledger Entry" - Function ShowDocuments OnBeforeShowDoc and OnAfterShowDoc remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#9708]

**Comment by AlexanderYakunin** [comment]
OnBeforeShowDoc and OnAfterShowDoc are integration events and must be local. You can subscribe to these events but cannot call them directly.

**Comment by SWE-Tina** [comment]
You are right (sorry haven't checked the request of my colleague correctly). Event OnBeforeShowDoc can be used and code placed in the subscriber with setting Ishandled = true.
