### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function ProcessToAsmHeader - OnProcessToAsmHeaderOnAfterValidateQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9710]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: ProcessToAsmHeader
Publisher Event: OnProcessToAsmHeaderOnAfterValidateQty
Reason: To implement custom business logic
Where is the event placed:
end else begin
                if ToSalesLine."Shipment Date" <> 0D then
                    Validate("Due Date", ToSalesLine."Shipment Date");
                Quantity := QtyToAsmToOrder;
                "Quantity (Base)" := QtyToAsmToOrderBase;
            end;
            OnProcessToAsmHeaderOnAfterValidateQty (ToAsmHeader, TempFromAsmHeader, ToSalesLine, BasicAsmOrderCopy, AvailabilityCheck);
            "Bin Code" := TempFromAsmHeader."Bin Code";
            "Unit Cost" := TempFromAsmHeader."Unit Cost";
            RoundQty(Quantity);
            RoundQty("Quantity (Base)");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnProcessToAsmHeaderOnAfterValidateQty (var ToAsmHeader: Record "Assembly Header"; TempFromAsmHeader: Record "Assembly Header" temporary; ToSalesLine: Record "Sales Line"; BasicAsmOrderCopy: Boolean; AvailabilityCheck: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
