### ISSUE TITLE
[Event Request] Codeunit::"Create Pick" - Function CalcTotalAvailQtyToPick - OnCalcTotalAvailQtyToPickOnBeforeCalcSubTotal

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9711]
We like to request the following Event:
Object: Codeunit::"Create Pick"
Function: CalcTotalAvailQtyToPick
Publisher Event: OnCalcTotalAvailQtyToPickOnBeforeCalcSubTotal
Reason: To implement custom business logic
Where is the event placed:
if Location."Always Create Pick Line" or CrossDock then begin
            FilterWhsePickLinesWithUndefinedBin(
              WhseActivLine, ItemNo, LocationCode, VariantCode, LNRequired, LotNo, SNRequired, SerialNo);
            WhseActivLine.CalcSums("Qty. Outstanding (Base)");
            QtyAssignedPick := QtyAssignedPick - WhseActivLine."Qty. Outstanding (Base)";
        end;
        OnCalcTotalAvailQtyToPickOnBeforeCalcSubTotal(QtyInWhse, QtyOnPickBins, QtyOnPutAwayBins, QtyOnOutboundBins, QtyOnDedicatedBins, QtyBlocked, QtyOnReceiveBins, ReservedQtyOnInventory);
        SubTotal :=
          QtyInWhse - QtyOnPickBins - QtyOnPutAwayBins - QtyOnOutboundBins - QtyOnDedicatedBins - QtyBlocked -
          QtyOnReceiveBins - Abs(ReservedQtyOnInventory);
Event Code:
[IntegrationEvent(false,   false)]         local procedure   OnCalcTotalAvailQtyToPickOnBeforeCalcSubTotal(var QtyInWhse: Decimal; var   QtyOnPickBins: Decimal; var QtyOnPutAwayBins: Decimal; var QtyOnOutboundBins:   Decimal; var QtyOnDedicatedBins: Decimal; var QtyBlocked: Decimal; var   QtyOnReceiveBins: Decimal; var ReservedQtyOnInventory: Decimal)         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
