### ISSUE TITLE
[Event Request] Codeunit::"Create Pick" - Function CreateTempLine - OnCreateTempLineOnBeforeCreateTempLines

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9712]
We like to request the following Event:
Object: Codeunit::"Create Pick"
Function: CreateTempLine
Publisher Event: OnCreateTempLineOnBeforeCreateTempLines
Reason: To implement custom business logic
Where is the event placed:
OnCreateTempLineOnAfterCreateTempLineWithItemTracking(TotalQtytoPickBase, HasExpiredItems);
            IsHandled := false;
            OnCreateTempLineOnBeforeCreateTempLines(TotalQtytoPickBase, HasExpiredItems, LocationCode, ItemNo, VariantCode, UnitofMeasureCode, FromBinCode, ToBinCode, QtyPerUnitofMeasure, TempWhseActivLine, TempLineNo, IsHandled);
            if not IsHandled then
                if TotalQtytoPickBase <> 0 then
                    if not HasExpiredItems then begin
                        if SNRequired then begin
                            for i := 1 to TotalQtytoPick do begin
                                QtyToPick := 1;
                                QtyToPickBase := 1;
                                CreateTempLine(LocationCode, ItemNo, VariantCode, UnitofMeasureCode,
                                  FromBinCode, ToBinCode, QtyPerUnitofMeasure, QtyToPick, TempWhseItemTrackingLine, QtyToPickBase);
                            end;
                            TotalQtytoPick := 0;
                            TotalQtytoPickBase := 0;
                        end else
                            CreateTempLine(LocationCode, ItemNo, VariantCode, UnitofMeasureCode,
                              FromBinCode, ToBinCode, QtyPerUnitofMeasure, TotalQtytoPick, TempWhseItemTrackingLine, TotalQtytoPickBase);
                    end;
        end;
Event Code:
[IntegrationEvent(false,   false)]         local procedure   OnCreateTempLineOnBeforeCreateTempLines(var TotalQtytoPickBase: Decimal; var   HasExpiredItems: Boolean; LocationCode: Code[10]; ItemNo: Code[20];   VariantCode: Code[10]; UnitofMeasureCode: Code[10]; FromBinCode: Code[20];   ToBinCode: Code[20]; QtyPerUnitofMeasure: Decimal; var TempWhseActivLine:   Record "Warehouse Activity Line" temporary; var TempLineNo:   Integer; var IsHandled: Boolean)         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
