### ISSUE TITLE
[Event Request] Codeunit::"Create Pick" - Function CreateWhseDocPlaceLine - OnCreateWhseDocPlaceLineOnBeforeValidateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9713]
We like to request the following Event:
Object: Codeunit::"Create Pick"
Function: CreateWhseDocPlaceLine
Publisher Event: OnCreateWhseDocPlaceLineOnBeforeValidateQuantity
Reason: To implement custom business logic
Where is the event placed:
if WhseActivLine.Quantity > 0 then begin
                    TempWhseActivLine3 := WhseActivLine;
                    IsHandled := false;
                    OnCreateWhseDocPlaceLineOnBeforeValidateQuantity(WhseActivLine, IsHandled);
                    if not IsHandled then begin
                        WhseActivLine.Validate(Quantity);
                        WhseActivLine."Qty. (Base)" := TempWhseActivLine3."Qty. (Base)";
                        WhseActivLine."Qty. Outstanding (Base)" := TempWhseActivLine3."Qty. (Base)";
                        WhseActivLine."Qty. to Handle (Base)" := TempWhseActivLine3."Qty. (Base)";
                    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCreateWhseDocPlaceLineOnBeforeValidateQuantity(var WarehouseActivityLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
