### ISSUE TITLE
[Event Request] Codeunit::"Create Prod. Order Lines" - Function CopyFromSalesOrder - OnCopyFromSalesOrderOnBeforeValidateQtyBase

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9714]
We like to request the following Event:
Object: Codeunit::"Create Prod. Order Lines"
Function: CopyFromSalesOrder
Publisher Event: OnCopyFromSalesOrderOnBeforeValidateQtyBase
Reason: To implement custom business logic
Where is the event placed:
LocationCode := SalesLine."Location Code";
                OnCopyFromSalesOrderOnBeforeInitProdOrderLine(SalesLine, LocationCode);
                InitProdOrderLine(SalesLine."No.", SalesLine."Variant Code", LocationCode);
                ProdOrderLine.Description := SalesLine.Description;
                ProdOrderLine."Description 2" := SalesLine."Description 2";
                SalesLine.CalcFields("Reserved Qty. (Base)");
                IsHandled := false;
                OnCopyFromSalesOrderOnBeforeValidateQtyBase(ProdOrderLine, SalesLineIsSet, SalesLine, IsHandled);
                if not IsHandled then
                    ProdOrderLine.Validate("Quantity (Base)", SalesLine."Outstanding Qty. (Base)" - SalesLine."Reserved Qty. (Base)");
                if Location.Get(ProdOrderLine."Location Code") and not Location."Require Pick" and (SalesLine."Bin Code" <> '') then
                    ProdOrderLine."Bin Code" := SalesLine."Bin Code";
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCopyFromSalesOrderOnBeforeValidateQtyBase(var ProdOrderLine: Record "Prod. Order Line"; SalesLineIsSet: Boolean; var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
