### ISSUE TITLE
[Event Request] Codeunit::"Get Source Doc. Outbound" - Function FindWarehouseRequestForOutbndTransferOrder - OnFindWarehouseRequestForOutbndTransferOrderOnAfterSetFilter

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9715]
We like to request the following Event:
Object: Codeunit::"Get Source Doc. Outbound"
Function: FindWarehouseRequestForOutbndTransferOrder
Publisher Event: OnFindWarehouseRequestForOutbndTransferOrderOnAfterSetFilter
Reason: To implement custom business logic
Where is the event placed:
local procedure FindWarehouseRequestForOutbndTransferOrder(var WhseRqst: Record "Warehouse Request"; TransHeader: Record "Transfer Header")
    begin
        with TransHeader do begin
            TestField(Status, Status::Released);
            CheckTransferHeader(TransHeader, true);
            WhseRqst.SetRange(Type, WhseRqst.Type::Outbound);
            WhseRqst.SetSourceFilter(DATABASE::"Transfer Line", 0, "No.");
            WhseRqst.SetRange("Document Status", WhseRqst."Document Status"::Released);
            OnFindWarehouseRequestForOutbndTransferOrderOnAfterSetFilter(WhseRqst, TransHeader);
            GetRequireShipRqst(WhseRqst);
        end;
        OnAfterFindWarehouseRequestForOutbndTransferOrder(WhseRqst, TransHeader);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnFindWarehouseRequestForOutbndTransferOrderOnAfterSetFilter(var WhseRqst: Record "Warehouse Request"; var TransferOrder: Record "Transfer Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
