### ISSUE TITLE
[Event Request] Codeunit::"Get Source Doc. Outbound" - Function FindWarehouseRequestForPurchReturnOrder - OnFindWarehouseRequestForPurchReturnOrderOnAfterSetFilter

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9716]
We like to request the following Event:
Object: Codeunit::"Get Source Doc. Outbound"
Function: FindWarehouseRequestForPurchReturnOrder
Publisher Event: OnFindWarehouseRequestForPurchReturnOrderOnAfterSetFilter
Reason: To implement custom business logic
Where is the event placed:
local procedure FindWarehouseRequestForPurchReturnOrder(var WhseRqst: Record "Warehouse Request"; PurchHeader: Record "Purchase Header")
    begin
        with PurchHeader do begin
            TestField(Status, Status::Released);
            WhseRqst.SetRange(Type, WhseRqst.Type::Outbound);
            WhseRqst.SetSourceFilter(DATABASE::"Purchase Line", "Document Type", "No.");
            WhseRqst.SetRange("Document Status", WhseRqst."Document Status"::Released);
            OnFindWarehouseRequestForPurchReturnOrderOnAfterSetFilter(WhseRqst, PurchHeader);
            GetRequireShipRqst(WhseRqst);
        end;
        OnAfterFindWarehouseRequestForPurchReturnOrder(WhseRqst, PurchHeader);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnFindWarehouseRequestForPurchReturnOrderOnAfterSetFilter(var WhseRqst: Record "Warehouse Request"; var PurchaseReturnOrder: Record "Purchase Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
