### ISSUE TITLE
[Event Request] Codeunit::"Get Source Doc. Outbound" - Function FindWarehouseRequestForSalesOrder - OnFindWarehouseRequestForSalesOrderOnAfterSetFilter

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9717]
We like to request the following Event:
Object: Codeunit::"Get Source Doc. Outbound"
Function: FindWarehouseRequestForSalesOrder
Publisher Event: OnFindWarehouseRequestForSalesOrderOnAfterSetFilter
Reason: To implement custom business logic
Where is the event placed:
local procedure FindWarehouseRequestForSalesOrder(var WhseRqst: Record "Warehouse Request"; SalesHeader: Record "Sales Header")
    begin
        with SalesHeader do begin
            TestField(Status, Status::Released);
            if WhseShpmntConflict("Document Type", "No.", "Shipping Advice") then
                Error(Text003, Format("Shipping Advice"));
            CheckSalesHeader(SalesHeader, true);
            WhseRqst.SetRange(Type, WhseRqst.Type::Outbound);
            WhseRqst.SetSourceFilter(DATABASE::"Sales Line", "Document Type", "No.");
            WhseRqst.SetRange("Document Status", WhseRqst."Document Status"::Released);
            OnFindWarehouseRequestForSalesOrderOnAfterSetFilter(WhseRqst, SalesHeader);
            GetRequireShipRqst(WhseRqst);
        end;
        OnAfterFindWarehouseRequestForSalesOrder(WhseRqst, SalesHeader);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnFindWarehouseRequestForSalesOrderOnAfterSetFilter(var WhseRqst: Record "Warehouse Request"; var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
