### ISSUE TITLE
New Azure Blob Storage functionality in the System/Base App

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#9718]
Hi al-team, 
in your BC Tech Repo you have an Azure Blob Storage functionality. (BCTech/samples/AzureStorage/AzureStorageLibrary/)
Are you currently planning to include such functionality in the Business Central System/Base App?

If there is a chance that it will be accepted, I will rebuild the BC-Tech demo according to your system app rules and create a pull request.

**Comment by JesperSchulz** [comment]
We currently don't have any plans in that direction. Feel free to complete the prototype and to make a PR for a System Application module. We're looking forward to your contribution!

**Comment by JesperSchulz** [comment]
Btw. remember [aka.ms/NewALModule](http://aka.ms/NewALModule) if you're looking for guidance on the "how to" part!
