### ISSUE TITLE
BCPT: DrilldownPageId is missing on table 149002 "BCPT Log Entry"

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/ALAppExtensions#9719]
To enable drilldown of various FlowFields in the Performance Toolkit table 149002 "BCPT Log Entry" should be provided a DrillDownPageId .

`DrillDownPageId = "BCPT Log Entries";`

Will provide a PR for it.

**Comment by lvanvugt** [comment]
Oops, it seems I cannot create a pull request form the commit 57213cf in my forked branch. Can someone tip me on how to do that?

**Comment by stkillen** [comment]
Hi @lvanvugt, you have done both of the changes in your master branch. You should look into branches that will allow you to work on multiple changes at the same time. For example, you can submit this change in a separate branch by 1) undoing the change in your main branch, 2) creating a new branch `git checkout -b YourBranchName` from the master branch, 3) doing the change in the new branch and submitting a PR from that branch.

**Comment by lvanvugt** [comment]
@stkillen, thanx for the info. Will revert that change form my master branch. Starting to learn on Git (coming form TFVC). Always thought a PR was related to a committed and it seems to relate to the whole branch. Had clearly expected it differently.

**Comment by lvanvugt** [comment]
@stkillen I have reverted the change in my main branch. How do I get it "removed" from the PR #9682?
