### ISSUE TITLE
BUG: Codeunit 99000815 Reservation-Check Date Confl. SalesLineCheck  and PurchLineCheck

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#9722]
Procedure SalesLineCheck and PurchLineCheck are not calling the subscribers OnSalesLineCheckOnBeforeUpdateDate and OnPurchLineCheckOnBeforeUpdateDate and the IsHandled is declared not managed on both the functions..

 procedure SalesLineCheck(SalesLine: Record "Sales Line"; ForceRequest: Boolean)
    var
        SalesLineReserve: Codeunit "Sales Line-Reserve";
        IsHandled: Boolean;
    begin
        if not SalesLineReserve.FindReservEntry(SalesLine, ReservEntry) then
            exit;

        if DateConflict(SalesLine."Shipment Date", ForceRequest, ReservEntry) then
            if ForceRequest then
                IssueError(SalesLine."Shipment Date");
        
        //>MISSING CODE
        IsHandled := false;
        OnSalesLineCheckOnBeforeUpdateDate(ReservEntry, SalesLine, IsHandled);
        if IsHandled then
           exit;
        //<MISSING CODE        

        UpdateDate(ReservEntry, SalesLine."Shipment Date");

        ReservMgt.SetReservSource(SalesLine);
        ReservMgt.ClearSurplus();
        ReservMgt.AutoTrack(SalesLine."Outstanding Qty. (Base)");
    end;

   procedure PurchLineCheck(PurchLine: Record "Purchase Line"; ForceRequest: Boolean)
    var
        PurchLineReserve: Codeunit "Purch. Line-Reserve";
        IsHandled: Boolean;
    begin
        if not PurchLineReserve.FindReservEntry(PurchLine, ReservEntry) then
            exit;

        if DateConflict(PurchLine."Expected Receipt Date", ForceRequest, ReservEntry) then
            if ForceRequest then
                IssueError(PurchLine."Expected Receipt Date");

        //>MISSING CODE
        IsHandled := false;
        OnPurchLineCheckOnBeforeUpdateDate(ReservEntry, PurchLine, IsHandled);
        if IsHandled then
           exit;
        //<MISSING CODE        

        UpdateDate(ReservEntry, PurchLine."Expected Receipt Date");

        ReservMgt.SetReservSource(PurchLine);
        ReservMgt.ClearSurplus();
        ReservMgt.AutoTrack(PurchLine."Outstanding Qty. (Base)");
    end;

**Comment by aconcato** [comment]
procedure PurchLineCheck(PurchLine: Record "Purchase Line"; ForceRequest: Boolean)
    var
        PurchLineReserve: Codeunit "Purch. Line-Reserve";
        IsHandled: Boolean;
    begin
        if not PurchLineReserve.FindReservEntry(PurchLine, ReservEntry) then
            exit;

        if DateConflict(PurchLine."Expected Receipt Date", ForceRequest, ReservEntry) then
            if ForceRequest then
                IssueError(PurchLine."Expected Receipt Date");

        //>MISSING CODE
        IsHandled := false;
        OnPurchLineCheckOnBeforeUpdateDate(ReservEntry, PurchLine, IsHandled);
        if IsHandled then
           exit;
        //<MISSING CODE        

        UpdateDate(ReservEntry, PurchLine."Expected Receipt Date");

        ReservMgt.SetReservSource(PurchLine);
        ReservMgt.ClearSurplus();
        ReservMgt.AutoTrack(PurchLine."Outstanding Qty. (Base)");
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
