### ISSUE TITLE
Option to ENUM Record::"Default Dimension" Field ::"Value Posting"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#9723]
Field "Value Posting" is still an option but would be very useful to have as an enum as it is connected in several other objects in several kind of ways.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
