### ISSUE TITLE
[Protection Level] Codeunit::"DimensionManagement" - Function DefaultDimInsertTempObject remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#9747]
Due to the protection level the function and therefore the needed event isn't reachable.

**Comment by AlexanderYakunin** [comment]
This function is global in Master
    procedure DefaultDimInsertTempObject(var TempAllObjWithCaption: Record AllObjWithCaption temporary; TableID: Integer)
    begin
        if IsObsolete(TableID) then
            exit;
        if KeyContainsOneCodeField(TableID) or IsDefaultDimTable(TableID) then
            InsertObject(TempAllObjWithCaption, TableID);
    end;
