### ISSUE TITLE
[Event Request] Codeunit 370 "Bank Acc. Reconciliation Post" - Function PostPaymentApplications - OnBeforePostPaymentApplications

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9750]
Could You please, add the following event to the Codeunit 370 "Bank Acc. Reconciliation Post"

Object: Codeunit 370 "Bank Acc. Reconciliation Post"
Function: PostPaymentApplications

Publisher Event: OnBeforePostPaymentApplications

Reason: To implement custom business logic and replace the standard function
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98250086-51dded00-1f77-11eb-823d-b2e02d1d7f97.png)

At the begining of the function
Insert next 4 lines

IsHandled := false;
OnBeforePostPaymentApplications(BankAccReconLine; var AppliedAmount, IsHandled);
if IsHandled then
    exit;

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforePostPaymentApplications(BankAccReconLine: Record "Bank Acc. Reconciliation Line"; var AppliedAmount: Decimal; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by IgnacioPeq** [comment]
Hi again,
Sorry, I've opened other request in the same function (post #9611) and in order to avoid fill the base app with events is better forget the previous requested event and replace it by this one. This new post is designed for more general purposes than the #9611 

By my side you can delete the post #9611 and implement only this one. 

With only this last post I can do what I need to implement the business logic in my 2 customers DDBB. My second one needs to change the funcinality of the function completelly.

please, tell me if you need that I write something in the previous post comments.

Thanks in advance.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
