### ISSUE TITLE
[Event Request] Codeunit 7313 "Create Put-away" - OnBeforeGetPutAwayTemplate

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/ALAppExtensions#9751]
Hello,

we need an event in the "GetPutAwayTemplate" function to integrate our own fields into the logic.

![image](https://user-images.githubusercontent.com/63199461/98262911-71304680-1f86-11eb-9a0a-0872f3983497.png)

    [BusinessEvent(false)]
    local procedure OnBeforeGetPutAwayTemplate(SKU: Record "Stockkeeping Unit"; Item: Record Item; Location: Record Location; var PutAwayTemplHeader: Record "Put-away Template Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
