### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - FinishPosting

### ISSUE THREAD

**Issue by bstanienda** [microsoft/ALAppExtensions#9753]
Hello Team,

because of additional postings we need an event in Codeunit 12 - Function FinishPosting. The new code is signed with #######:

    procedure FinishPosting(GenJnlLine: Record "Gen. Journal Line") IsTransactionConsistent: Boolean
    var
        CostAccSetup: Record "Cost Accounting Setup";
        TransferGlEntriesToCA: Codeunit "Transfer GL Entries to CA";
    begin
        OnBeforeFinishPosting(GenJnlLine, TempGLEntryBuf);

        IsTransactionConsistent :=
          (BalanceCheckAmount = 0) and (BalanceCheckAmount2 = 0) and
          (BalanceCheckAddCurrAmount = 0) and (BalanceCheckAddCurrAmount2 = 0);

        OnAfterSettingIsTransactionConsistent(GenJnlLine, IsTransactionConsistent);

        if TempGLEntryBuf.FindSet() then begin
            repeat
                GlobalGLEntry := TempGLEntryBuf;
                if AddCurrencyCode = '' then begin
                    GlobalGLEntry."Additional-Currency Amount" := 0;
                    GlobalGLEntry."Add.-Currency Debit Amount" := 0;
                    GlobalGLEntry."Add.-Currency Credit Amount" := 0;
                end;
                GlobalGLEntry."Prior-Year Entry" := GlobalGLEntry."Posting Date" < FiscalYearStartDate;
                OnBeforeInsertGlobalGLEntry(GlobalGLEntry, GenJnlLine, GLReg);
                GlobalGLEntry.Insert(true);
                OnAfterInsertGlobalGLEntry(GlobalGLEntry, TempGLEntryBuf, NextEntryNo);
            until TempGLEntryBuf.Next() = 0;

            GLReg."To VAT Entry No." := NextVATEntryNo - 1;
            GLReg."To Entry No." := GlobalGLEntry."Entry No.";
            if IsTransactionConsistent then
		// ##############
		OnBeforeModifyOrInsertGLReg(GenJnlLine: Record "Gen. Journal Line; GLReg: Record "G/L Register; GlobalGLEntry: 
                                                                  Record "G/L Entry", var IsGLRegInserted:boolean);
		// ##############**
                if IsGLRegInserted then
                    GLReg.Modify()
                else begin
                    GLReg.Insert();
                    IsGLRegInserted := true;
		    // ################
		    OnAfterSetIsGLRegInserted(var GenJnlLine: Record "Gen. Journal Line; GLReg: Record "G/L Register; GlobalGLEntry: 
                                                                 Record "G/L Entry", IsGLRegInserted:boolean)
                    // ################**
                end;
        end;
        GlobalGLEntry.Consistent(IsTransactionConsistent);

        if CostAccSetup.Get() then
            if CostAccSetup."Auto Transfer from G/L" then
                TransferGlEntriesToCA.GetGLEntries;

        FirstEntryNo := 0;

        OnAfterFinishPosting(GlobalGLEntry, GLReg, IsTransactionConsistent, GenJnlLine);
    end;

Thank you! Kind Regards!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
