### ISSUE TITLE
[Event Request] report 5692 "Calculate Depreciation" - Trigger OnInitReport - OnBeforeInitReport

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9754]
Could You please, add the following event to the report 5692 "Calculate Depreciation"

Object: report 5692 "Calculate Depreciation"
Trigger: OnInitReport

Publisher Event: OnBeforeInitReport

Reason: To implement custom business logic and fix the DepreciationBookCode (We need to have exposed the var DeprBookCode by reference)
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98276446-477f1b80-1f96-11eb-876b-f61478e40acb.png)

First create the trigger OnIntReport and then 
At the begining of the trigger
Insert the call to the event

OnBeforeInitReport(DeprBookCode);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeInitReport(var DeprBookCode: Code [10])
begin
end;

Thanks in Advance

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
