### ISSUE TITLE
[Event Request] report 5692 "Calculate Depreciation" - Function OnPostReport - OnAfterPostReport

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9755]
Could You please, add the following event to the report 5692 "Calculate Depreciation"

Object: report 5692 "Calculate Depreciation"
Trigger: OnPostReport

Publisher Event: OnAfterPostReport

Reason: To implement custom business logic and do several actions after the finalization of the report
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98277198-5e723d80-1f97-11eb-891f-1ea33e5cab7a.png)

At the End of the trigger
Insert the call to the event

OnAfterPostReport();

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterPostReport()
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
