### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post (and codeunit 90 Purch.-Post) - new event OnAfterSetCompressPrepaymentFilters

### ISSUE THREAD

**Issue by AlexxBenn** [microsoft/ALAppExtensions#9756]
Hi Team,

**BC version** - 17;
**codeunit** - 80 **and** 90;
**procedure** - CreatePrepaymentLines;

We need the possibility to manage filters that applied when compress prepayment. Having a new event in the procedure CreatePrepaymentLines would be a suitable solution for **both** codeunits 80 and 90, below example for codeunit 80:
![image](https://user-images.githubusercontent.com/62009673/98291587-085fc300-1fb4-11eb-82dc-267eebff9a39.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetCompressPrepaymentFilters(var TempPrepmtSalesLine: Record "Sales Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
