### ISSUE TITLE
[Code defect] codeunit 426 "Payment Tolerance Management" / IsCustBlockPmtTolerance

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9758]
The function IsCustBlockPmtTolerance is Used in 

local procedure SalesPmtTolGenJnl(var GenJnlLine: Record "Gen. Journal Line"): Boolean
    var
        NewCustLedgEntry: Record "Cust. Ledger Entry";
        GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
        GenJnlLineApplID: Code[50];
    begin
        if **IsCustBlockPmtToleranceInGenJnlLine(GenJnlLine)** then
            exit(false);
 ...
end;

This would mean that if the function gives TRUE as a result it would exit the function SalesPmtTolGenJnl.

local procedure IsCustBlockPmtToleranceInGenJnlLine(var GenJnlLine: Record "Gen. Journal Line"): Boolean
    begin
        CheckAccountType(GenJnlLine, GenJnlLine."Account Type"::Customer);

        if GenJnlLine."Bal. Account Type" = GenJnlLine."Bal. Account Type"::Customer then
            CODEUNIT.Run(CODEUNIT::"Exchange Acc. G/L Journal Line", GenJnlLine);

        **exit(IsCustBlockPmtTolerance(GenJnlLine."Account No."));**
 end;

The Result is based on the result of function **IsCustBlockPmtTolerance**

Here is the problem. That function will always result in **FALSE**. It doesnt matter if the boolean "Customer."Block Payment Tolerance" is True or False. Because when it is on, it will exit the function with false. If not, it will exit the function and the result will also be FALSE. 

local procedure IsCustBlockPmtTolerance(AccountNo: Code[20]): Boolean
    var
        Customer: Record Customer;
    begin
        if not Customer.Get(AccountNo) then
            exit(false);
        if Customer."Block Payment Tolerance" then
            exit(false);
    end;

Looking at the name of the function I would appear that the  function returns TRUE when the "Customer."Block Payment Tolerance" is TRUE. But then we have a problem with IsCustBlockPmtToleranceInGenJnlLine because that function should Return true when IsCustBlockPmtTolerance=TRUE. But when it's true it doesnt exit in SalesPmtTolGenJnl.

I think naming of the functions are mixed up.  Customer."Block Payment Tolerance" =false it should exit the function SalesPmtTolGenJnl. At the current state it of the naming and the IF's it continues.

For now I think this should be the change as a quick fix:

local procedure IsCustBlockPmtTolerance(AccountNo: Code[20]): Boolean
    var
        Customer: Record Customer;
    begin
        if not Customer.Get(AccountNo) then
            exit(false);
        if Customer."Block Payment Tolerance" then
            exit(false);

       **exit(true);** //I Added this
    end;

**Comment by guidorobben** [comment]
Same applies for the Vendor.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
