### ISSUE TITLE
Data Upgrade From BC 14 to BC 17 - OnPremise

### ISSUE THREAD

**Issue by A-R-Shaji** [microsoft/ALAppExtensions#9774]
I had successfully converted my data from 2009 to BC 14 C/AL. Now I want to migrate from 14 to 17 On-premise. 

I am following below Microsoft doc. but I am stuck and confused in mid of the process.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app-v17.

Do any one have clear detailed level document for data migration from 14 C/AL to 17 BC on-premise.

Please help me out.

Thanks
Shaji D

**Comment by AlexanderYakunin** [comment]
Please be informed that we cannot answer this kind of questions in this forum. You can approach technical support with specific questions.

**Comment by hvandenborn** [comment]
after CAL BC14. upgrade first to a dummy app that contains all the tables as the are in BC14. so also your fields in the std nav tables. 
after that you can migrate to the base app of MS and your own apps.
see also this dummy upgrade 14 to 16 (its the same as 14 to 17)

https://github.com/microsoft/BCUpgrade/tree/master/Upgrade14To16ExtractFieldsToExtensions

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.

**Comment by dynamicssquareau** [comment]
Great work done by you on upgrading data 2009 to BC 14 C/A.

Now you are facing issues on Data upgrade from Business central 14 to Business Central 17 On-premise, Don’t take a risk on that. Lots of people are facing the same issues, so don’t worry about that. It has a solution.

These are helpful guides.

[ Technical Upgrade From Version 14 to Version 17](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v14-v17)

[Upgrade from BC14 to BC17 (OnPrem)](https://community.dynamics.com/business/f/dynamics-365-business-central-forum/424078/upgrade-from-bc14-to-bc17-onprem)

Still don't work.

You should take help from professionals who have immense experience on [Microsoft Business Central](https://www.dynamicssquare.com.au/dynamics-365-business-central/). They will help you with Solutions easily
