### ISSUE TITLE
[Event Request] Event trigger request on Vendor 1099  statistics

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#9775]
Hi

during my app development, I Need a event trigger on "Vendor 1099 Statistics" page. here is the screen shots where I need

![image](https://user-images.githubusercontent.com/38460823/98512093-b8228280-228b-11eb-989e-c6aceee02356.png)

I need to apply more filters here for my app.

Thanks
Sahil Gupta

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
