### ISSUE TITLE
critical logical issue in all 1099 reports

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#9776]
in all 1099 reports, it process all entries vendor by vendor and then we build an array of amounts and then we have a logic to decide that do we need to print this amounts accordingly to minimum amounts here is the logic for it by MS

![image](https://user-images.githubusercontent.com/38460823/98512322-27987200-228c-11eb-8fb7-3a0a6626ce45.png)

but the issues is when a vendor can have multiple ledger entries with multiple form 1099 codes look into following screen shot
![image](https://user-images.githubusercontent.com/38460823/98512353-34b56100-228c-11eb-9672-0b6f53a42c6b.png)

these are the multiple ledger entries of a one vendor . now if you run 1099 report then it will work in that way what i explained above.
where MS checking the minimum amount there is a variable "PrintThis" if that is true for one of the code and then later if we found another code then it will never set again and we are using this one variable for all amounts. which is wrong... i thing if it is less than minimum amount then we should set the amount =0 in array rather than print this.

example:
suppose in the screen shot, we have div-09 code which i set minimum amount 600 and originally we have 200 in ledger entry so for me it should not print but it is still printing in the reports because he set up the variable true for rest of the code which are prior to div-09 .

**Comment by sorenfriisalexandersen** [comment]
Thanks @SahilGuptaBS for suggesting this change.
You are suggesting to change a part of 1099 reporting that has worked fine for years, and to our knowledge customers are satisfied with the way it works. Recently we have had other partners test changes for upcoming forms changes with no issues found. Based on that, we will have to decline this suggestion. 
If you think this is incorrect, please provide some more background as to the legal nature of the suggestion.

Thanks again.

**Comment by AlexanderYakunin** [comment]
Let me add that this forum is not for reporting of bugs or requesting a fix. We have no possibility to triage functional issues or decide if this is regulatory requirement or not.  You should work with technical support to get solution for such issues.

**Comment by SahilGuptaBS** [comment]
do i need to do more anything for it ?
