### ISSUE TITLE
Event trigger request on Customer/Vendor entry statistics

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#9777]
Hi

during my app development, I Need a event trigger on "Vendor Entry Statistics" and "Customer Entry Statistics" page. here is the screen shots where I need trigger

vendor entry statistics
![image](https://user-images.githubusercontent.com/38460823/98512590-8d84f980-228c-11eb-81d6-7fec01d0529c.png)

Customer Entry statistics
image
![image](https://user-images.githubusercontent.com/38460823/98512821-f2405400-228c-11eb-9040-7d12c5001d64.png)

I need to apply more filters here for my app.

Thanks
Sahil Gupta

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
