### ISSUE TITLE
[Event Request] Codeunit::"Inventory Profile Offsetting" - Function AdjustPlanLine - OnAdjustPlanLineBeforeValidateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9780]
We like to request the following Event:
Object: Codeunit::"Inventory Profile Offsetting"
Function: AdjustPlanLine
Publisher Event: OnAdjustPlanLineBeforeValidateQuantity
Reason: To implement custom business logic
Where is the event placed:
if "Action Message" in
               ["Action Message"::New,
                "Action Message"::"Change Qty.",
                "Action Message"::Reschedule,
                "Action Message"::"Resched. & Chg. Qty.",
                "Action Message"::Cancel]
            then begin
                if "Qty. per Unit of Measure" = 0 then
                    "Qty. per Unit of Measure" := 1;
                IsHandled := false;
                OnAdjustPlanLineBeforeValidateQuantity(ReqLine, SupplyInventoryProfile, IsHandled);
                if not IsHandled then
                    ReqLine.Validate(
                        Quantity,
                        Round("Remaining Quantity (Base)" / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision));
                ReqLine."Original Quantity" := "Original Quantity";
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAdjustPlanLineBeforeValidateQuantity(var ReqLine: Record "Requisition Line"; var SupplyInventoryProfile: Record "Inventory Profile"; var IsHandled: Boolean);
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
