### ISSUE TITLE
[Event Request] Codeunit::"Inventory Profile Offsetting" - Function MaintainPlanningLine - OnAfterMaintainPlanningLineInit

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9781]
We like to request the following Event:
Object: Codeunit::"Inventory Profile Offsetting"
Function: MaintainPlanningLine
Publisher Event: OnAfterMaintainPlanningLineInit
Reason: To implement custom business logic
Where is the event placed:
Init();
                    "Worksheet Template Name" := CurrTemplateName;
                    "Journal Batch Name" := CurrWorksheetName;
                    "Line No." := PlanLineNo;
                    Type := Type::Item;
                    "No." := SupplyInvtProfile."Item No.";
                    "Variant Code" := SupplyInvtProfile."Variant Code";
                    "Location Code" := SupplyInvtProfile."Location Code";
                    "Bin Code" := SupplyInvtProfile."Bin Code";
                    "Planning Line Origin" := "Planning Line Origin"::Planning;
                    **OnAfterMaintainPlanningLineInit(ReqLine, SupplyInvtProfile, DemandInvtProfile, NewPhase, Direction, TempSKU);**
                    if SupplyInvtProfile."Action Message" = SupplyInvtProfile."Action Message"::New then begin
                        "Order Date" := SupplyInvtProfile."Due Date";
Event Code:
[IntegrationEvent(false,   false)]         local procedure   OnAfterMaintainPlanningLineInit(var ReqLine: Record "Requisition   Line"; var SupplyInvtProfile: Record "Inventory Profile";   DemandInvtProfile: Record "Inventory Profile"; NewPhase: Option   " ","Line Created","Routing   Created",Exploded,Obsolete; Direction: Option Forward,Backward; var   TempSKU: Record "Stockkeeping Unit")         begin         end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
