### ISSUE TITLE
[Event Request] Codeunit::"Item Subst." - Function ItemSubstGet - OnItemSubstGetOnBeforeFillTempSalesLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9782]
We like to request the following Event:
Object: Codeunit::"Item Subst."
Function: ItemSubstGet
Publisher Event: OnItemSubstGetOnBeforeFillTempSalesLine
Reason: To implement custom business logic
Where is the event placed:
f TempItemSubstitution."Substitute Type" =
                   TempItemSubstitution."Substitute Type"::"Nonstock Item"
                then begin
                    NonStockItem.Get(TempItemSubstitution."Substitute No.");
                    if NonStockItem."Item No." = '' then begin
                        CatalogItemMgt.CreateItemFromNonstock(NonStockItem);
                        NonStockItem.Get(TempItemSubstitution."Substitute No.");
                    end;
                    TempItemSubstitution."Substitute No." := NonStockItem."Item No."
                end;
                IsHandled := false;
                **OnItemSubstGetOnBeforeFillTempSalesLine (TempSalesLine, TempItemSubstitution, IsHandled);**
                if not IsHandled then begin
                    TempSalesLine."No." := TempItemSubstitution."Substitute No.";
                    TempSalesLine."Variant Code" := TempItemSubstitution."Substitute Variant Code";
                    SaveQty := TempSalesLine.Quantity;
                    SaveLocation := TempSalesLine."Location Code";
                    SaveDropShip := TempSalesLine."Drop Shipment";
                    TempSalesLine.Quantity := 0;
                    TempSalesLine.Validate("No.", TempItemSubstitution."Substitute No.");
                    TempSalesLine.Validate("Variant Code", TempItemSubstitution."Substitute Variant Code");
                    TempSalesLine."Originally Ordered No." := SaveItemNo;
                    TempSalesLine."Originally Ordered Var. Code" := SaveVariantCode;
                    TempSalesLine."Location Code" := SaveLocation;
                    TempSalesLine."Drop Shipment" := SaveDropShip;
                    TempSalesLine.Validate(Quantity, SaveQty);
                    TempSalesLine.Validate("Unit of Measure Code", OldSalesUOM);

                    TempSalesLine.CreateDim(
                      DimMgt.TypeToTableID3(TempSalesLine.Type.AsInteger()), TempSalesLine."No.",
                      DATABASE::Job, TempSalesLine."Job No.",
                      DATABASE::"Responsibility Center", TempSalesLine."Responsibility Center");

                    OnItemSubstGetOnAfterSubstSalesLineItem(TempSalesLine);
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnItemSubstGetOnBeforeFillTempSalesLine (var TempSalesline: Record "Sales Line" temporary; var TempItemSubstitution: Record "Item Substitution" temporary; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
