### ISSUE TITLE
[Event Request] Codeunit::"Job Calculate Batches" - Function PostDiffBuffer - OnPostDiffBufferOnBeforeModify

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9784]
We like to request the following Event:
Object: Codeunit::"Job Calculate Batches"
Function: PostDiffBuffer
Publisher Event: OnPostDiffBufferOnBeforeModify
Reason: To implement custom business logic
Where is the event placed:
JobLedgEntry.SetRange("Unit of Measure Code", JobDiffBuffer[1]."Unit of Measure code");
                JobLedgEntry.SetRange("Work Type Code", JobDiffBuffer[1]."Work Type Code");
                if JobLedgEntry.Find('-') then
                    repeat
                        JobDiffBuffer[1].Quantity := JobDiffBuffer[1].Quantity - JobLedgEntry.Quantity;
                    until JobLedgEntry.Next = 0;
                **OnPostDiffBufferOnBeforeModify(JobLedgEntry, JobDiffBuffer[1]);**
                JobDiffBuffer[1].Modify();
            until JobDiffBuffer[1].Next = 0;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostDiffBufferOnBeforeModify(var JobLedgEntry: Record "Job Ledger Entry"; var JobDiffBuffer: Record "Job Difference Buffer" temporary)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
