### ISSUE TITLE
[Event Request] Codeunit::"Output Jnl.-Expl. Route" - Function OnRun - OnRunOnAfterInsertOutputJnlLineWithRtngLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9785]
We like to request the following Event:
Object: Codeunit::"Output Jnl.-Expl. Route"
Function: OnRun
Publisher Event: OnRunOnAfterInsertOutputJnlLineWithRtngLine
Reason: To implement custom business logic
Where is the event placed:
OnBeforeInsertOutputJnlLineWithRtngLine(Rec, ProdOrderLine, SkipRecord, IsLastOperation, ProdOrderRtngLine);
                        if not SkipRecord then begin
                            InsertOutputJnlLine(
                              Rec, NextLineNo, LineSpacing,
                              ProdOrderLine."Line No.",
                              ProdOrderLine."Item No.",
                              ProdOrderLine."Variant Code",
                              ProdOrderLine."Location Code",
                              ProdOrderLine."Bin Code",
                              ProdOrderLine."Routing No.", ProdOrderLine."Routing Reference No.",
                              ProdOrderRtngLine."Operation No.",
                              ProdOrderLine."Unit of Measure Code",
                              BaseQtyToPost / ProdOrderLine."Qty. per Unit of Measure",
                              IsLastOperation);
                            OnRunOnAfterInsertOutputJnlLineWithRtngLine (ItemJnlLine, ProdOrderLine, ProdOrderRtngLine, NextLineNo);
                            if IsLastOperation then
                                ItemTrackingMgt.CopyItemTracking(ProdOrderLine.RowID1, LastItemJnlLine.RowID1, false);
                        end;
                    end;
Event Code:
[IntegrationEvent(false,   false)]         local procedure   OnAfterInsertOutputJnlLineWithRtngLine(var ItemJournalLine: Record "Item   Journal Line"; var ProdOrderLine: Record "Prod. Order Line";   var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var   NextLineNo: Integer)         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
