### ISSUE TITLE
[Event Request] Codeunit::"Prod. Order Status Management" - Function FlushProdOrder - OnFlushProdOrderOnBeforeFindProdOrderRtngLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9787]
We like to request the following Event:
Object: Codeunit::"Prod. Order Status Management"
Function: FlushProdOrder
Publisher Event: OnFlushProdOrderOnBeforeFindProdOrderRtngLine
Reason: To implement custom business logic
Where is the event placed:
 ProdOrderRtngLine.LockTable();

                IsHandled := false;
                OnFlushProdOrderOnBeforeFindProdOrderRtngLine(ProdOrderLine, ProdOrderRtngLine, PostingDate, IsHandled);
                if not IsHandled then
                    if ProdOrderRtngLine.Find('-') then begin
                        // First found operation
                        IsLastOperation := ProdOrderRtngLine."Next Operation No." = '';
                        OnFlushProdOrderOnAfterFindProdOrderRtngLine(ProdOrderRtngLine, IsLastOperation);
                        if ProdOrderRtngLine."Flushing Method" = ProdOrderRtngLine."Flushing Method"::Backward then begin
                            ActualOutputAndScrapQtyBase :=
                              CostCalcMgt.CalcActOperOutputAndScrap(ProdOrderLine, ProdOrderRtngLine);
                            ActualOutputAndScrapQty := ActualOutputAndScrapQtyBase / ProdOrderLine."Qty. per Unit of Measure";
                            PutawayQtyBaseToCalc := ActualOutputAndScrapQtyBase - CostCalcMgt.CalcActQtyBase(ProdOrderLine, ProdOrderRtngLine);
                        end;

                        if (ProdOrderRtngLine."Flushing Method" = ProdOrderRtngLine."Flushing Method"::Forward) or IsLastOperation then begin
                            OutputQty := ProdOrderLine."Remaining Quantity";
                            OutputQtyBase := ProdOrderLine."Remaining Qty. (Base)";
                        end else
                            if not IsLastOperation then begin // Not Last Operation
                                OutputQty := ActualOutputAndScrapQty;
                                OutputQtyBase := ActualOutputAndScrapQtyBase;
                                PutawayQtyBaseToCalc := 0;
                            end;

                        repeat
                            IsLastOperation := ProdOrderRtngLine."Next Operation No." = '';
                            **OnFlushProdOrderOnAfterFindProdOrderRtngLine(ProdOrderRtngLine, IsLastOperation);
                            InitItemJnlLineFromProdOrderLine(ItemJnlLine, ProdOrder, ProdOrderLine, ProdOrderRtngLine, PostingDate);**
                            if ProdOrderRtngLine."Concurrent Capacities" = 0 then
                                ProdOrderRtngLine."Concurrent Capacities" := 1;
                            SetTimeAndQuantityOmItemJnlLine(
                              ItemJnlLine, ProdOrderRtngLine, OutputQtyBase,
                              GetOutputQtyForProdOrderRoutingLine(ProdOrderLine, ProdOrderRtngLine, IsLastOperation, OutputQty),
                              PutawayQtyBaseToCalc);
                            ItemJnlLine."Source Code" := SourceCodeSetup.Flushing;
                            if not (ItemJnlLine.TimeIsEmpty and (ItemJnlLine."Output Quantity" = 0)) then begin
                                DimMgt.UpdateGlobalDimFromDimSetID(
                                  ItemJnlLine."Dimension Set ID", ItemJnlLine."Shortcut Dimension 1 Code", ItemJnlLine."Shortcut Dimension 2 Code");
                                OnAfterUpdateGlobalDim(ItemJnlLine, ProdOrderRtngLine, ProdOrderLine);
                                if IsLastOperation then
                                    ReserveProdOrderLine.TransferPOLineToItemJnlLine(ProdOrderLine, ItemJnlLine, ItemJnlLine."Output Quantity (Base)");
                                OnBeforePostFlushItemJnlLine(ItemJnlLine);
                                ItemJnlPostLine.RunWithCheck(ItemJnlLine);
                            end;

                            if (ProdOrderRtngLine."Flushing Method" = ProdOrderRtngLine."Flushing Method"::Backward) and IsLastOperation then begin
                                OutputQty += ActualOutputAndScrapQty;
                                OutputQtyBase += ActualOutputAndScrapQtyBase;
                                PutawayQtyBaseToCalc := 0;
                            end;
                        until ProdOrderRtngLine.Next = 0;
                    end;
                end;
            until ProdOrderLine.Next = 0;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnFlushProdOrderOnBeforeFindProdOrderRtngLine(var ProdOrderLine: Record "Prod. Order Line"; var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; PostingDate: Date; var IsHandled: Boolean)
    be

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
