### ISSUE TITLE
[Event Request] Codeunit::"Purch.-Get Drop Shpt." - Function "Code" - OnCodeOnBeforeChekSalesLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9788]
We like to request the following Event:
Object: Codeunit::"Purch.-Get Drop Shpt."
Function: "Code"
Publisher Event: OnCodeOnBeforeChekSalesLine
Reason: To implement custom business logic
Where is the event placed:
 OnAfterSetSalesLineFilters(PurchHeader, SalesLine);

            if SalesLine.Find('-') then
                repeat
                    **IsHandled := false;
                    OnBeforeChekSalesLine(PurchHeader, SalesLine, IsHandled);
                    if not IsHandled then**
                        if (SalesLine.Type = SalesLine.Type::Item) and ItemUnitofMeasure.Get(SalesLine."No.", SalesLine."Unit of Measure Code") then
                            if SalesLine."Qty. per Unit of Measure" <> ItemUnitofMeasure."Qty. per Unit of Measure" then
                                Error(Text001,
                                SalesLine.FieldCaption("Qty. per Unit of Measure"),
                                SalesLine.FieldCaption("Unit of Measure Code"),
                                SalesLine."Unit of Measure Code",
                                SalesLine."Qty. per Unit of Measure",
                                ItemUnitofMeasure."Qty. per Unit of Measure",
                                SalesLine.FieldCaption(Quantity));
                    end;
                    
                    PurchLine.Init();
[IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeChekSalesLine (var PurchaseHeader: Record "Purchase Header"; var SalesLine: Record "Sales Line"; var Handled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
