### ISSUE TITLE
[Event Request] Codeunit::"Purch.-Get Drop Shpt." - Function "Code" - OnCodeOnBeforeSalesLineValidateUnitCostLCY

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9789]
We like to request the following Event:
Object: Codeunit::"Purch.-Get Drop Shpt."
Function: "Code"
Publisher Event: OnCodeOnBeforeSalesLineValidateUnitCostLCY
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
                    OnCodeOnBeforeSalesLineValidateUnitCostLCY (PurchHeader, SalesLine, IsHandled);
                    if not IsHandled then begin
                        SalesLine."Unit Cost (LCY)" := PurchLine."Unit Cost (LCY)";
                        SalesLine.Validate("Unit Cost (LCY)");
                    end;
                    SalesLine."Purchase Order No." := PurchLine."Document No.";
                    SalesLine."Purch. Order Line No." := PurchLine."Line No.";
                    OnBeforeSalesLineModify(SalesLine, PurchLine);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeSalesLineValidateUnitCostLCY (var PurchaseHeader: Record "Purchase Header"; var SalesLine: Record "Sales Line"; var Handled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
