### ISSUE TITLE
[Event Request] Codeunit::"Req. Wksh.-Make Order" - Function InitPurchOrderLine - OnInitPurchOrderLineOnAfterPurchOrderLineAssignVariantCode

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9790]
We like to request the following Event:
Object: Codeunit::"Req. Wksh.-Make Order"
Function: InitPurchOrderLine
Publisher Event: OnInitPurchOrderLineOnAfterPurchOrderLineAssignVariantCode
Reason: To implement custom business logic
Where is the event placed:
OnAfterPurchOrderLineValidateNo(PurchOrderLine, RequisitionLine);
            PurchOrderLine."Variant Code" := "Variant Code";
            **OnInitPurchOrderLineOnAfterPurchOrderLineAssignVariantCode (PurchOrderLine, RequisitionLine);**
            PurchOrderLine.Validate("Location Code", "Location Code");
            PurchOrderLine.Validate("Unit of Measure Code", "Unit of Measure Code");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnInitPurchOrderLineOnAfterPurchOrderLineAssignVariantCode (var PurchOrderLine: Record "Purchase Line"; var RequisitionLine: Record "Requisition Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
