### ISSUE TITLE
[Event Request] Codeunit::"Req. Wksh.-Make Order" - Function InitPurchOrderLine - OnBeforePurchOrderLineValidateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9791]
We like to request the following Event:
Object: Codeunit::"Req. Wksh.-Make Order"
Function: InitPurchOrderLine
Publisher Event: OnBeforePurchOrderLineValidateQuantity
Reason: To implement custom business logic
Where is the event placed:
PurchOrderLine."Qty. per Unit of Measure" := "Qty. per Unit of Measure";
            PurchOrderLine."Prod. Order No." := "Prod. Order No.";
            PurchOrderLine."Prod. Order Line No." := "Prod. Order Line No.";
            IsHandled := false;
            OnBeforePurchOrderLineValidateQuantity(PurchOrderLine, RequisitionLine, IsHandled);
            if not IsHandled then
                PurchOrderLine.Validate(Quantity, Quantity);
            if PurchOrderHeader."Prices Including VAT" then
                PurchOrderLine.Validate("Direct Unit Cost", "Direct Unit Cost" * (1 + PurchOrderLine."VAT %" / 100))
            else
                PurchOrderLine.Validate("Direct Unit Cost", "Direct Unit Cost");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePurchOrderLineValidateQuantity(var PurchOrderLine: Record "Purchase Line"; var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
