### ISSUE TITLE
[Event Request] Codeunit::"TransferOrder-Post Receipt" - Function InsertTransRcptLine - OnBeforeWhsePosting

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9792]
We like to request the following Event:
Object: Codeunit::"TransferOrder-Post Receipt"
Function: InsertTransRcptLine
Publisher Event: OnBeforeWhsePosting
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
            OnBeforeWhsePosting(TransRcptLine, TransLine, SuppressCommit, WhsePosting, IsHandled);
            if not IsHandled then
                if WhsePosting then
                    PostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, TempWhseSplitSpecification);
            OnAfterTransRcptLineModify(TransRcptLine, TransLine, SuppressCommit);
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeWhsePosting(var TransRcptLine: Record "Transfer Receipt Line"; var TransLine: Record "Transfer Line"; SuppressCommit: Boolean; WhsePosting: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
