### ISSUE TITLE
[Event Request] Codeunit::"TransferOrder-Post Shipment" - Function InsertTransShptLine - OnBeforeWhsePosting

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9793]
We like to request the following Event:
Object: Codeunit::"TransferOrder-Post Shipment"
Function: InsertTransShptLine
Publisher Event: OnBeforeWhsePosting
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
            OnBeforeWhsePosting(TransShptLine, TransLine, SuppressCommit, WhsePosting, IsHandled);
            if WhsePosting and not IsHandled then
                PostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase);
        end;
        OnBeforeInsertTransShptLine(TransShptLine, TransLine, SuppressCommit);
        TransShptLine.Insert();
        OnAfterInsertTransShptLine(TransShptLine, TransLine, SuppressCommit);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeWhsePosting(TransShptLine: Record "Transfer Shipment Line"; TransLine: Record "Transfer Line"; SuppressCommit: Boolean; var WhsePosting: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
