### ISSUE TITLE
[Event Correction] Database::"Assemble-to-Order Link" - Function NeedsSynchronization - OnBeforeNeedsSynchronization

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9794]
We requested a new event https://github.com/microsoft/ALAppExtensions/issues/8897 but the event is placed in the wrong line.

In the newest version the code looks like this:
![image](https://user-images.githubusercontent.com/68000891/98559462-ed889980-22a6-11eb-8ef2-ddcaf1e92f21.png)

But we need to execute the procedure GetAsmHeader before the event is called:
![image](https://user-images.githubusercontent.com/68000891/98559273-b31efc80-22a6-11eb-852c-3b28a4499c1c.png)

Or the function needs an additional parameter(Record "Assemble-to-Order Link") so we can get the Header ourself in the subscriber function.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
