### ISSUE TITLE
Implement GUIALLOWED = False for UpdateRecordFromVATRegLog

### ISSUE THREAD

**Issue by kvamsdal** [microsoft/ALAppExtensions#9801]
It is not possible to Validate VAT Reg No. from an Odata Call. 

We would like that conditional code GUIALLOWED=FALSE is implemented for the function "UpdateRecordFromVATRegLog" in Code Unit 249 "VAT Registration Log Mgt.".

Use Case: use the VIES VAT registration validation on customers when creating new customer via call to Customer Page (VATRegistrationValidation) exposed as OData. 

When creating new customers via an call to Customer API we get the following Error.

"Microsoft Dynamics 365 Business Central Data Services attempted to issue a client callback to show a confirmation dialog box: The VAT registration number is valid. Do you want us to update the name? (CodeUnit 249 VAT Registration Log Mgt.). Client callbacks are not supported on Microsoft Dynamics 365 Business Central Data Services.  CorrelationId:  92689b33-b057-4c1d-83e7-830a4964fcee."

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-webservices

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 17.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 16.
