### ISSUE TITLE
[Event Request] Codeunit 10753 - "SII Job Upload Pending Docs." Add IsHandled to IntegrationEvents

### ISSUE THREAD

**Issue by evamariamartingomez** [microsoft/ALAppExtensions#9804]
Hello ,

In order to make some customizations in SII functionality, we need the adition of the paramter IsHandled in IntegrationEvents:

  - OnBeforeOnAfterPostSalesDoc
  - OnBeforeOnAfterPostPurchDoc

Just like in the attached images.
![OnAfterPostSalesDoc](https://user-images.githubusercontent.com/56435545/98686528-f80b6780-2368-11eb-8ade-cc6157bcdb89.png)
![OnAfterPostPurchaseDoc](https://user-images.githubusercontent.com/56435545/98686548-fb065800-2368-11eb-8101-7561da55325a.png)

Thank you in advanced!

Eva Maria

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
