### ISSUE TITLE
[Event Request] Codeunit Mail Management.SendViaEmailModule - OnAfterAddAttachmentToEmailMessage

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#9805]
@darjoo / @JesperSchulz 

Today we've upgraded our solution to BC 17.1 and wanted to disable direct 'Mail SMTP codeunit' dependencies and adopt the newest Email Feature. However, with the pending #9292 / #9283 issues, we're still blocked to build a SaaS solution and allow multiple attachments. I know you're working on a solution and will track status on these issues.

However, looking more in detail on how we used codeunit SMTP mail, we did had the option to include additional attachments using 'AddAttachment**Stream**'. Moving away from this codeunit, leaves a gap to be filled on the 'Email Item' pattern. As a - temporary - solution, we'd like to have a new event OnAfterAddAttachmentToEmailMessage or OnSendViaEmailModule_OnBeforeSend, providing var acccess to the **Message / TempEmailItem** variables.

```
local procedure SendViaEmailModule(): Boolean
    var
        Email: Codeunit Email;
        Message: Codeunit "Email Message";
        ErrorMessageManagement: Codeunit "Error Message Management";
        ToList: List of [Text];
        CcList: List of [Text];
        BccList: List of [Text];
    begin
        RecipientStringToList(TempEmailItem."Send to", ToList);
        RecipientStringToList(TempEmailItem."Send CC", CcList);
        RecipientStringToList(TempEmailItem."Send BCC", BccList);

        Message.Create(ToList, TempEmailItem.Subject, TempEmailItem.GetBodyText(), true, CcList, BccList);

        AddAttachmentToEmailMessage(Message, TempEmailItem."Attachment File Path", TempEmailItem."Attachment Name");
        AddAttachmentToEmailMessage(Message, TempEmailItem."Attachment File Path 2", TempEmailItem."Attachment Name 2");
        AddAttachmentToEmailMessage(Message, TempEmailItem."Attachment File Path 3", TempEmailItem."Attachment Name 3");
        AddAttachmentToEmailMessage(Message, TempEmailItem."Attachment File Path 4", TempEmailItem."Attachment Name 4");
        AddAttachmentToEmailMessage(Message, TempEmailItem."Attachment File Path 5", TempEmailItem."Attachment Name 5");
        AddAttachmentToEmailMessage(Message, TempEmailItem."Attachment File Path 6", TempEmailItem."Attachment Name 6");
        AddAttachmentToEmailMessage(Message, TempEmailItem."Attachment File Path 7", TempEmailItem."Attachment Name 7");

// >> Add event here ...

        ClearLastError();
        Cancelled := false;
        if not HideMailDialog then begin
            Commit();
            MailSent := Email.OpenInEditorModally(Message, TempEmailModuleAccount) = Enum::"Email Action"::Sent;
            Cancelled := not MailSent;
        end else
            MailSent := Email.Send(Message, TempEmailModuleAccount);

        if not MailSent and not Cancelled and not HideEmailSendingError then
            ErrorMessageManagement.LogSimpleErrorMessage(GetLastErrorText());

        exit(MailSent);
    end;
```
Since we store the attachments to be send as blobs in a single instance codeunits, we could subscribe to this event and then add custom attachments reading out the single instance content, via the Message.AddAttachment(AttachmentName: Text[250]; ContentType: Text[250]; AttachmentStream: InStream) procedure

This would at least help us moving forward to releasing our OnPrem solution on the next BC update (hopefully 17.2) and when the other issues are solved, take away the showstoppers to move our solution to AppSource.

**Comment by GiorgosPa** [comment]
Hello, we are currently working to provide a solution for the other two issues you already mentioned. In the meantime you don’t need to wait, you can achieve the desired result by creating a new connector for the email module. You can get access to the email message on the send function, where you can add your attachments and then pass it to an existing connector to send the updated message. There is a bit of glue code required to maintain a mapping between the different accounts for these two connectors but it will get the job done.
