### ISSUE TITLE
Request a new event for Codeunit 90 Purchase Post

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#9806]
Please see the attached screen shot.

Could you please add a new event OnPostItemTrackingForReceiptOnBeforePurchRcptLineFindSet to the red arrow line as  indicated?  We would like to use PurchLine."Document Type" and "Document No." to set more filters fo PurchRcptLine before doing the FINDSET.

![image](https://user-images.githubusercontent.com/49729094/98728192-25efac80-2367-11eb-8e58-a85a95ea6d15.png)

Thanks very much.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
