### ISSUE TITLE
[UI] "Untitled " caption in Opportunities List Page.

### ISSUE THREAD

**Issue by MRevanth96** [microsoft/ALAppExtensions#9807]
![bc_opportunity](https://user-images.githubusercontent.com/31589194/98745485-ad760380-23d9-11eb-801f-ecfdfaf7ce44.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
