### ISSUE TITLE
[Event Request] PAGE 654 "Requests to Approve" - OnAfterSetUserIdFilter

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#9810]
Hi

Could you please add an event on OnOpenPage trigger, sincer we want to modify default filters.

OLD CODE

    trigger OnOpenPage()
    begin
        FilterGroup(2);
        SetRange("Approver ID", UserId);
        FilterGroup(0);
        SetRange(Status, Status::Open);
    end;

NEW CODE

    trigger OnOpenPage()
    begin
        FilterGroup(2);
        SetRange("Approver ID", UserId);

        >>>
        OnAfterSetUserIdFilter(Rec);
        <<<

        FilterGroup(0);
        SetRange(Status, Status::Open);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetUserIdFilter(var ApprovalEntry: Record "Approval Entry")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
