### ISSUE TITLE
[EventRequest] Page 1007 Job Planning Lines - OnAfterNoOnAfterValidate

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#9811]
Requesting a new event publisher on Page 1007 Job Planning Lines

Event
`OnAfterNoOnAfterValidate(VAR JobPlanningLine : Record "Job Planning Line")`
**IMPORTANT we want to be able to access some external functions from the subsriber on this Publisher, so please set IncludeSender=TRUE**

**Code**
## LOCAL NoOnAfterValidate()
```
IF "No." <> xRec."No." THEN
  PerformAutoReserve;
```
**>>> New Code**
```
OnAfterNoOnAfterValidate(Rec);
```
**<<< New Code End**
```

In Our Solution we work with Extended Texts linked to Jobs. 
To handle the addition of extended texts in Job Planning Lines we need this publisher and IncludeSender = TRUE because we need to trigger it at the correct times and need to update the Page to present the possible added Text Lines. 
Please add the requested publisher.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
