### ISSUE TITLE
[Enum Request] Table 1523 "Workflow Step Argument" - "Approver Limit Type"

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#9812]
Hi

Could you please change this option to enum?

Of cource, same applies for tables:
- "Workflow Step Argument Archive"
- "Approval Entry"
- "Posted Approval Entry"
- "Overdue Approval Entry"

Thank you

**Comment by AlexanderYakunin** [comment]
Please be aware that fields Approver Limit Type exists in tables Workflow Step Argument and Workflow Step Argument Archive. This field has following set of options:  'Approver Chain,Direct Approver,First Qualified Approver,Specific Approver'.

Field Limit Type in table Approval entry contains different set of options 'Approval Limits,Credit Limits,Request Limits,No Limits'.

So these are two different enums.

**Comment by aobsgit** [comment]
Thank you for your feedback.
"Approver Limit Type" is what concerns me. "Limit type" is OK as it is.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
