### ISSUE TITLE
[Code enhancement] Report 11412 "Tax Authority - Audit File"

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9816]
Report 11412 Tax Authority - Audit File has the following lines of code:

TempAuditFileBuffer.Rectype::Vendor:
IF Vend.GET(TempAuditFileBuffer.Code) THEN BEGIN
  **IF STRLEN(Vend."VAT Registration No.") > 15 THEN**
    ERROR(Text008,Vend.FIELDCAPTION("VAT Registration No."),Vend.TABLECAPTION,Vend."No.");

The problem is the check of the length of the "VAT Registration No.". In the netherlands this can be entered with . in them something like NL.001234.567.B01. This causes the Length check to fail. 

Can you change the code in the following?

**IF STRLEN(DELCHR(Vend."VAT Registration No.",'=','.')) > 15 THEN**         
   ERROR(Text008,Vend.FIELDCAPTION("VAT Registration No."),Vend.TABLECAPTION,Vend."No.");

This will remove the . before the length is checked.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
