### ISSUE TITLE
[Event Request] report 595 "Adjust Exchange Rates" - Function AdjustCustomerLedgerEntry - OnAdjustCustomerLedgerEntryOnChangeCustomerPostGroup

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9817]
[Event Request] report 595 "Adjust Exchange Rates" - Function AdjustCustomerLedgerEntry - OnAdjustCustomerLedgerEntryOnChangeCustomerPostGroup

Could You please, add the following event to the report 595 "Adjust Exchange Rates"

Object: Report 595 "Adjust Exchange Rates"
Function: AdjustCustomerLedgerEntry 

Publisher Event: OnAdjustCustomerLedgerEntryOnChangeCustomerPostGroup

Reason: To implement custom business logic and change the Customer Posting Group to be taken into account when the adjust will be made
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98837498-50169c80-2443-11eb-99b1-7fc5de2fdfcf.png)

after the line 
if AdjAmount <> 0 then begin 

Insert the call to the event

OnAdjustCustomerLedgerEntryOnChangeCustomerPostGroup(Customer, CusLedgerEntry);

Note: Customer is the name of the DataItem for Table 18

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAdjustCustomerLedgerEntryOnChangeCustomerPostGroup(var Customer: Record "Customer"; CusLedgerEntry: Record "Cust. Ledger Entry")
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
