### ISSUE TITLE
[Event Request] report 595 "Adjust Exchange Rates" - Function AdjustVendorLedgerEntry - OnAdjustVendorLedgerEntryOnChangeVendorPostGroup

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9818]
Could You please, add the following event to the report 595 "Adjust Exchange Rates"

Object: Report 595 "Adjust Exchange Rates"
Function: AdjustVendorLedgerEntry

Publisher Event: OnAdjustVendorLedgerEntryOnChangeVendorPostGroup

Reason: To implement custom business logic and change the Vendor Posting Group to be taken into account when the adjust will be made
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98839049-56a61380-2445-11eb-9fec-307f97603467.png)

after the line
if AdjAmount <> 0 then begin

Insert the call to the event

OnAdjustVendorLedgerEntryOnChangeVendorPostGroup(Vendor, VendLedgerEntry);

Note: Vendor is the name of the DataItem for Table 23

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAdjustVendorLedgerEntryOnChangeVendorPostGroup(var Vendor: Record "Vendor"; VendLedgerEntry: Record "Vendor Ledger Entry");
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
