### ISSUE TITLE
need to clone the Magnetic Media 1099 report

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#9819]
hi
 do anyone any idea how can i make a clone of report "Magnetic Media 1099 report" ?
i tried to make it clone but it always gives error of filetype's functions
for example: 
file.open or file.seek methods can not be use in web client these can be use only in on premise

any idea ?

**Comment by AVentsel** [comment]
I just checked, this report works fine in SaaS version. Nobody complained about this. If you need to substitute the report you can use specific event - https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-substituting-reports.
