### ISSUE TITLE
[Event Request] report 595 "Adjust Exchange Rates" - Trigger OnPostReport - OnAfterPostReport

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9820]
Could You please, add the following event to the report 595 "Adjust Exchange Rates"

Object: Report 595 "Adjust Exchange Rates"
Trigger: OnPostReport

Publisher Event: OnAfterPostReport

Reason: To implement custom business logic and do additional actions at the end of the report
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98842864-755ad900-244a-11eb-9fce-a34116d64bad.png)

At the end of the report
Insert the call to the event

OnAfterPostReport(ExchRateAdjReg, PostingDate);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterPostReport(ExchRateAdjReg: Record "Exch. Rate Adjmt. Reg."; PostingDate: Date);
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
