### ISSUE TITLE
[Event Request] report 595 "Adjust Exchange Rates" - Trigger OnOpenPage - OnBeforeOpenPage

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9821]
Could You please, add the following event to the report 595 "Adjust Exchange Rates"

Object: Report 595 "Adjust Exchange Rates"
Trigger: OnOpenPage

Publisher Event: OnBeforeOpenPage

Reason: To implement custom business logic and propose default data when the Request page is open
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98844383-886ea880-244c-11eb-8a5b-800697ac5918.png)

At the begining of the trigger OnOpenPage
Insert the call to the event

OnBeforeOpenPage(AdjCustVendBank,AdjGLAcc,PostingDocNo);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeOpenPage(var AdjCustVendBank: Boolean; var AdjGLAcc: Boolean; var PostingDocNo: Code[20])
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
