### ISSUE TITLE
[Event Request] Codeunit 230 "GenJnlManagement" - Function OpenJnlBatch - OnAfterOpenJnlBatch 

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9822]
Could You please, add the following event to the Codeunit	230	GenJnlManagement

Object: Codeunit	230	GenJnlManagement
Function OpenJnlBatch 

Publisher Event: OnAfterOpenJnlBatch 

Reason: To implement custom business logic and do several actions after the Batch was opened
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98847274-50696480-2450-11eb-81d6-bc4aa07be50d.png)

At the end of the function OpenJnlBatch
Insert the call to the event

OnAfterOpenJournalBatch(GenJnlBatch, GenJnlTemplate)

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterOpenJournalBatch(GenJnlBatch: Record "Gen. Journal Batch"; GenJnlTemplate: Record "Gen. Journal Template")
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
