### ISSUE TITLE
ProcessReportData functon in CU8800 not available for CLOUD

### ISSUE THREAD

**Issue by EpicRiceBall** [microsoft/ALAppExtensions#9823]
Can you please make ProcessReportData ( CU 8800 ) available for cloud ?

We are trying to extend report selection to accommodate our custom report.
I tried to use the ProcessReportData function in CustomReportLayout, but got compiler error that this function cannot be used for cloud, i couldnt find any similar function for CLOUD, can you suggest alternative function or let me know if this will be made available in the future release?

"error AL0296: The type or method 'ProcessReportData' cannot be used for 'Extension' development."

![image](https://user-images.githubusercontent.com/34019630/98879437-679d5780-243a-11eb-87d3-62a5cf0b5443.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
