### ISSUE TITLE
Report Selection - Statement - filter does not work on custom report

### ISSUE THREAD

**Issue by EpicRiceBall** [microsoft/ALAppExtensions#9824]
We use a custom report on Statement setting up via Report Selection
![image](https://user-images.githubusercontent.com/34019630/98879611-cf53a280-243a-11eb-812e-88b1d63f1bfa.png)

When this report is run from the Customer Card, the No. filter is blank, the user expect the Customer No. to be sent to this report.

![image](https://user-images.githubusercontent.com/34019630/98879744-117ce400-243b-11eb-9146-587a92c2f29f.png)

i checked the codes and it shows that the codes sent the filter to the standard nav statement report instead of the report in Report Selection. Can you look into this please?
![image](https://user-images.githubusercontent.com/34019630/98879909-70425d80-243b-11eb-9813-0df765eea22c.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
