### ISSUE TITLE
[Event Request] OnBeforePostAdjustmentToGL() in Codeunit 10120 "Bank Rec.-Post".PostAdjustmentToGL()

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/ALAppExtensions#9826]
Can you please add new publisher in codeunit 10120 "Bank Rec.-Post", in PostAdjustmentToGL() function:

![image](https://user-images.githubusercontent.com/20359384/98941059-4dbc4d00-24ec-11eb-86ab-e2b12a9f85ac.png)

**Event Publisher:**
````
[IntegrationEvent(false, false)]
local procedure OnBeforePostAdjustmentToGL(var GenJnlLine: Record "Gen. Journal Line"; BankRecLine: Record "Bank Rec. Line")
begin
end;
````

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
