### ISSUE TITLE
[Additional Parameter Request] Table 37, Sales Line, OnBeforeTestStatusOpen

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#9827]
Hi Team,

In Table 37 we need possibility to have additional checks in the procedure `TestStatusOpen`. Standard publisher `OnBeforeTestStatusOpen` would suit us you could add `IsHandled boolean` param with following exit functionality:

![image](https://user-images.githubusercontent.com/70525691/98941796-b825bb00-24f5-11eb-8973-b48609373d8e.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestStatusOpen(var SalesLine: Record "Sales Line"; var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
