### ISSUE TITLE
[Event Request] Codeunit 1520 "Workflow Event Handling" - RunWorkflowOnSendPurchaseDocForApproval - OnBeforeRunWorkflowOnSendPurchaseDocForApproval

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9829]
Object: Codeunit 1520 "Workflow Event Handling"
Procedure RunWorkflowOnSendPurchaseDocForApproval

Publisher Event: OnBeforeRunWorkflowOnSendPurchaseDocForApproval

Reason: To implement custom business logic and do some actions before function was executed
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/98953061-7d735100-24fc-11eb-972e-a7cd1b0415ed.png)

At the begining of the function
Insert the call to the event

OnBeforeRunWorkflowOnSendPurchaseDocForApproval(PurchaseHeader);

Event Code:
    [TryFunction]
    [IntegrationEvent(TRUE, FALSE)]
    procedure OnBeforeRunWorkflowOnSendPurchaseDocForApproval(PurchaseHeader: Record "Purchase Header")
    begin
    end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
