### ISSUE TITLE
[Function Request] Table 37 - AutoReserve

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/ALAppExtensions#983]
Dear Microsoft Team,

please add a new boolean parameter to function AutoReserve, to manage the manual reservation, as you did before for the same function in table 5902.

I don't know exactly how it looks like, because it is only available in the SaaS version.

**Comment by JesperSchulz** [comment]
I am afraid we would need a few more details. Either acquire an insider build or retrieve the latest cumulative update for Business Central to get insights into our implementation and suggest which change you'd like us to make.

**Comment by HegedusZsolt** [comment]
We don't know how Microsoft exactly does it in case of Service Line, because it is available in sandbox environment only. The on-prem CU3 cumulative update dose not contain it.

Our expectation is a new parameter (e.g SkipManualReservation) for function AutoReserve() to manage the manual reservations.

//  IF (NOT FullAutoReservation) AND (NOT SalesSetup."Skip Manual Reservation") THEN BEGIN // OLD CODE
  IF (NOT FullAutoReservation) AND (NOT SalesSetup."Skip Manual Reservation") AND (NOT SkipManualReservation) THEN BEGIN // NEW CODE
    COMMIT;
      IF CONFIRM(ManualReserveQst,TRUE) THEN BEGIN
        ShowReservation;
        FIND;
      END;
  END;

**Comment by JesperSchulz** [comment]
I am afraid I cannot find what you are explaining. I just looked at table 5902 and found the following signature: [External] AutoReserve(). There is no parameter to be found. As a matter of fact, I cannot find a single AutoReserve function with that parameter! Are you using a local version?

**Comment by HegedusZsolt** [comment]
I have attached a screenshot from our sandbox environment. As you can see, the standard AutoReserve function in table 5902, has a parameter with name ShowReservationForm. It is works as expected, and we would like to have the sames for AutoReserve function in table 37 (Sales Line)

![autoreserve](https://user-images.githubusercontent.com/43200526/53638234-f0a03b00-3c25-11e9-9dc3-b20614a89f62.png)

**Comment by JesperSchulz** [comment]
Ah, got it! This is in the NA/US version only. I will look into it!

**Comment by HegedusZsolt** [comment]
Could you please put in all NAV version (W1 and all localization) in case of sales and service as well?

**Comment by AlexanderYakunin** [comment]
Currently we cannot change parameters for external method [External] AutoReserve(). It may be possible later after conversion to AL.
