### ISSUE TITLE
Algorithm parameters for signing data

### ISSUE THREAD

**Issue by Joriek** [microsoft/ALAppExtensions#9831]
Hello

Next to the Hash algorithm, I need to change some other the algorithm parameters in the SignData function of the Cryptography Management codeunit.

Current parameters:
•	Hash algorithm: SHA-256

Extra needed parameters: 
•	Mask generation function: MGF1
•	Salt length: 32 bytes
•	Trailer field: 1

Thank you in advance!

**Comment by JesperSchulz** [comment]
Please submit a PR with the required changes. If you don't know how, please visit [aka.ms/ChangeALModule](http://aka.ms/ChangeALModule). Also, there is an excellent session on the BC Launch Event. If you have further questions, please don't hesitate to reach out.

**Comment by iFactoInstall** [comment]
Was this eventually solved? (not closed) we are looking for the same solution

**Comment by Joriek** [comment]
I don't think it was solved in the base code. I created a custom Azure function to handle the hash.
