### ISSUE TITLE
SignData with PEM Private Key

### ISSUE THREAD

**Issue by Joriek** [microsoft/ALAppExtensions#9832]
Hello

Currently the SignData function in the Cryptography Management codeunit only accepts a private key in XML format.
It would be very useful if it also accept th key in PEM format.

Code examples in C#:
https://www.programmersought.com/article/7492692431/
Ruby example:
https://github.com/GHKEN/pem2xml

Thank you in advance.

**Comment by JesperSchulz** [comment]
Sounds very related to #6387. Could you take a look if that helps in any way? If not, could you be persuaded to create a PR to add support for your request?

**Comment by Joriek** [comment]
I saw that post while I was investigating my issue. The post doesn't really offer a solution.
I already contacted the person who issued that request via another blog and pushed me in the right direction.
Nevertheless it would be pretty useful to have this openSSL available from within BC itself.
If needed you can contact me and then I will provide the .NET code we currently run from an Azure function.

**Comment by JesperSchulz** [comment]
Good to hear, that you've unblocked yourself :-) And sure, having such helper function would come in handy. I am hoping that a partner, who has a use case for this, is going to submit a PR to this repo some day, to add this functionality for the entire communities benefit.
