### ISSUE TITLE
[Event Request] codeunit 980 "Payment Registration Mgt." - Function Post - OnBeforePost

### ISSUE THREAD

**Issue by cristinacarr** [microsoft/ALAppExtensions#9835]
Could You please, add the following event to the codeunit 980 "Payment Registration Mgt."

Object: codeunit 980 "Payment Registration Mgt."
Function: Post 

Publisher Event: OnBeforePost

Reason: To implement custom business logic and do several actions before  the execution of the function
Where is the event placed (see image attached)?:

![image](https://user-images.githubusercontent.com/74407941/99065052-1d85b480-25a7-11eb-9371-a9480d5291bc.png)

At the Beginning of the function
Insert the call to the event

OnBeforePost(var TempPaymentRegistrationBuffer: Record "Payment Registration Buffer" temporary);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforePost(var TempPaymentRegistrationBuffer: Record "Payment Registration Buffer" temporary)
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
