### ISSUE TITLE
[Event Request] Table 254 "VAT Entry" - Function UpdateRates - OnAfterUpdateRates

### ISSUE THREAD

**Issue by cristinacarr** [microsoft/ALAppExtensions#9836]
Could You please, add the following event to the table 254 "VAT Entry"

Object: table 254 "VAT Entry"
Function: UpdateRates 

Publisher Event: OnAfterUpdateRates

Reason: To implement custom business logic and do several actions after the execution of the function
Where is the event placed (see image attached)?:

![image](https://user-images.githubusercontent.com/74407941/99066284-0051e580-25a9-11eb-9d99-3daa73a9d97c.png)

At the end of the function
Insert the call to the event

OnAfterUpdateRates(Rec,VATPostingSetup);

Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterUpdateRates(var VATEntry: Record "VAT Entry"; VATPostingSetup: Record "VAT Posting Setup")
begin
end;

Thanks in Advance

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
