### ISSUE TITLE
[event request] codeunit::"OIOUBL-Management" IsOIOUBLSendingProfile

### ISSUE THREAD

**Issue by ThomasRonn** [microsoft/ALAppExtensions#9837]
Requesting a new event in IsOIOUBLSendingProfile.

We can extend the Document Sending Profile but unable to let new options send oioubl as the test in IsOIOUBLSendingProfile isn't extendable.
We would like a new event where we can tell that the Document Sending Profile should be handled as a OIOUBL profile
like this
![image](https://user-images.githubusercontent.com/16342841/99075700-36e42c00-25ba-11eb-9905-a0fe807f71d0.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
