### ISSUE TITLE
[Event Request] Codeunit Item Templ. Mgt. - function ApplyTemplate

### ISSUE THREAD

**Issue by mynavblog** [microsoft/ALAppExtensions#9838]
Dear Team,

I would like to ask you to add new event for Codeunit 1336 Item Templ. Mgt. In procedure ApplyTemplate before Item.Modify(true). 

It would be good to have similar to below. It will allow to add custom fields to the Item Templ. Table and apply them on Item Record when creating from template.

![image](https://user-images.githubusercontent.com/37371997/99080114-1e2b4480-25c1-11eb-882d-445591a5ea72.png)

The event should have below parameters:
var Item: Record Item; ItemTempl: Record "Item Templ."

Thank you in advance

Krzysztof

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
