### ISSUE TITLE
Codeunit 80 "Sales-Post" UpdateInvoicedQtyOnShipmentLine

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#9839]
We need a new event function in Codeunit 80 "Sales-Post", named "OnAfterUpdateInvoicedQtyOnShipmentLine". It will be called from "UpdateInvoicedQtyOnShipmentLine" procedure.

The event will be:
LOCAL [IntegrationEvent] OnAfterUpdateInvoicedQtyOnShipmentLine(VAR SalesShptLine : Record "Sales Shipment Line";QtyToBeInvoiced : Decimal;QtyToBeInvoicedBase : Decimal)

Called from:
LOCAL UpdateInvoicedQtyOnShipmentLine(VAR SalesShptLine : Record "Sales Shipment Line";QtyToBeInvoiced : Decimal;QtyToBeInvoicedBase : Decimal)
WITH SalesShptLine DO BEGIN
  "Quantity Invoiced" := "Quantity Invoiced" - QtyToBeInvoiced;
  "Qty. Invoiced (Base)" := "Qty. Invoiced (Base)" - QtyToBeInvoicedBase;
  "Qty. Shipped Not Invoiced" := Quantity - "Quantity Invoiced";

  // I-INIT INSERT
  OnAfterUpdateInvoicedQtyOnShipmentLine(SalesShptLine,QtyToBeInvoiced,QtyToBeInvoicedBase);
  // F-END INSERT
  MODIFY;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
