### ISSUE TITLE
Codeunit 80 "Sales-Post" OnBeforePostUpdateInvoiceLine

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#9840]
We need a new event function in Codeunit 80 "Sales-Post", named "OnBeforePostUpdateInvoiceLine". It will be called from "PostUpdateInvoiceLine" procedure.

The event will be:
LOCAL [IntegrationEvent] OnBeforePostUpdateInvoiceLine(VAR TempSalesLine : Record "Sales Line";VAR SalesOrderLine : Record "Sales Line")

Called from:
LOCAL PostUpdateInvoiceLine()
ResetTempLines(TempSalesLine);
WITH TempSalesLine DO BEGIN
  SETFILTER("Shipment No.",'<>%1','');
  SETFILTER(Type,'<>%1',Type::" ");
  IF FINDSET THEN
    REPEAT
      SalesShptLine.GET("Shipment No.","Shipment Line No.");
      SalesOrderLine.GET(
        SalesOrderLine."Document Type"::Order,
        SalesShptLine."Order No.",SalesShptLine."Order Line No.");
      IF Type = Type::"Charge (Item)" THEN
        UpdateSalesOrderChargeAssgnt(TempSalesLine,SalesOrderLine);

      // I-BEGIN INSERT
      OnBeforePostUpdateInvoiceLine(TempSalesLine,SalesOrderLine);
      // F-END INSERT

      SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
      SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
      IF ABS(SalesOrderLine."Quantity Invoiced") > ABS(SalesOrderLine."Quantity Shipped") THEN
        ERROR(InvoiceMoreThanShippedErr,SalesOrderLine."Document No.");
      SalesOrderLine.InitQtyToInvoice;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
