### ISSUE TITLE
[Event Request] [AU] reproduce "Purchase Header" Table OnBeforeShowPostedDocsToPrintCreatedMsg(ShowPostedDocsToPrint);

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#9841]
An event **OnBeforeShowPostedDocsToPrintCreatedMsg(ShowPostedDocsToPrint);** is existing in *"Purchase Header"* table.

Would be great to have the same event at least in *"Sales Header"* and *"Service Header"* tables.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
