### ISSUE TITLE
[Event Request] Table 37 Sales Line function ApplyPrice

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#9842]
Following publisher needed in Table 37:
- End of the function ApplyPrice
OnAfteApplyPrice(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CalledByFieldNo: Integer; CurrFieldNo: Integer)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
