### ISSUE TITLE
Codeunit 80 "Sales-Post" PostUpdateReturnReceiptLine

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#9844]
We need a new event function in Codeunit 80 "Sales-Post", named "OnBeforePostUpdateReturnReceiptLine". It will be called from "PostUpdateReturnReceiptLine" procedure.

The event will be:
LOCAL [IntegrationEvent] OnBeforePostUpdateReturnReceiptLine(VAR TempSalesLine : Record "Sales Line";VAR SalesOrderLine : Record "Sales Line")

Called from:
LOCAL PostUpdateReturnReceiptLine()
ResetTempLines(TempSalesLine);
WITH TempSalesLine DO BEGIN
  SETFILTER("Return Receipt No.",'<>%1','');
  SETFILTER(Type,'<>%1',Type::" ");
  IF FINDSET THEN
    REPEAT
      ReturnRcptLine.GET("Return Receipt No.","Return Receipt Line No.");
      SalesOrderLine.GET(
        SalesOrderLine."Document Type"::"Return Order",
        ReturnRcptLine."Return Order No.",ReturnRcptLine."Return Order Line No.");
      IF Type = Type::"Charge (Item)" THEN
        UpdateSalesOrderChargeAssgnt(TempSalesLine,SalesOrderLine);

      // I-INIT INSERT
      OnBeforePostUpdateReturnReceiptLine(TempSalesLine,SalesOrderLine);
      // F-END INSERT

      SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
      SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
      IF ABS(SalesOrderLine."Quantity Invoiced") > ABS(SalesOrderLine."Return Qty. Received") THEN
        ERROR(InvoiceMoreThanReceivedErr,SalesOrderLine."Document No.");
      SalesOrderLine.InitQtyToInvoice;
      SalesOrderLine.InitOutstanding;
      SalesOrderLine.MODIFY;
    UNTIL NEXT = 0;
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
