### ISSUE TITLE
Codeunit 80 "Sales-Post" PostItemTrackingForReceipt

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#9845]
We need a new event function in Codeunit 80 "Sales-Post", named "OnBeforeUpdateInvoicedQtyOnReturnShipmentLine". It will be called from "PostItemTrackingForReceipt" procedure.

The event will be:
LOCAL [IntegrationEvent] OnBeforeUpdateInvoicedQtyOnReturnShipmentLine(VAR ReturnRcptLine : Record "Return Receipt Line")

Called from:
LOCAL PostItemTrackingForReceipt(SalesHeader : Record "Sales Header";SalesLine : Record "Sales Line";TrackingSpecificationExists : Boolean;VAR TempTrackingSpecification : TEMPORARY Record "Tracking Specification")
WITH SalesHeader DO BEGIN
  EndLoop := FALSE;
  ReturnRcptLine.RESET;
  CASE "Document Type" OF
    "Document Type"::"Return Order":
      BEGIN
        ReturnRcptLine.SETCURRENTKEY("Return Order No.","Return Order Line No.");
        ReturnRcptLine.SETRANGE("Return Order No.",SalesLine."Document No.");
        ReturnRcptLine.SETRANGE("Return Order Line No.",SalesLine."Line No.");
      END;
    "Document Type"::"Credit Memo":
      BEGIN
        ReturnRcptLine.SETRANGE("Document No.",SalesLine."Return Receipt No.");
        ReturnRcptLine.SETRANGE("Line No.",SalesLine."Return Receipt Line No.");
      END;
  END;
  ReturnRcptLine.SETFILTER("Return Qty. Rcd. Not Invd.",'<>0');
  IF ReturnRcptLine.FIND('-') THEN BEGIN
    ItemJnlRollRndg := TRUE;
    REPEAT
      IF TrackingSpecificationExists THEN BEGIN  // Item Tracking
        ItemEntryRelation.GET(TempTrackingSpecification."Item Ledger Entry No.");
        ReturnRcptLine.GET(ItemEntryRelation."Source ID",ItemEntryRelation."Source Ref. No.");
      END ELSE
        ItemEntryRelation."Item Entry No." := ReturnRcptLine."Item Rcpt. Entry No.";
      ReturnRcptLine.TESTFIELD("Sell-to Customer No.",SalesLine."Sell-to Customer No.");
      ReturnRcptLine.TESTFIELD(Type,SalesLine.Type);
      ReturnRcptLine.TESTFIELD("No.",SalesLine."No.");
      ReturnRcptLine.TESTFIELD("Gen. Bus. Posting Group",SalesLine."Gen. Bus. Posting Group");
      ReturnRcptLine.TESTFIELD("Gen. Prod. Posting Group",SalesLine."Gen. Prod. Posting Group");
      ReturnRcptLine.TESTFIELD("Job No.",SalesLine."Job No.");
      ReturnRcptLine.TESTFIELD("Unit of Measure Code",SalesLine."Unit of Measure Code");
      ReturnRcptLine.TESTFIELD("Variant Code",SalesLine."Variant Code");
      IF SalesLine."Qty. to Invoice" * ReturnRcptLine.Quantity < 0 THEN
        SalesLine.FIELDERROR("Qty. to Invoice",ReturnReceiptSameSignErr);
      UpdateQtyToBeInvoicedForReturnReceipt(
        QtyToBeInvoiced,QtyToBeInvoicedBase,
        TrackingSpecificationExists,SalesLine,ReturnRcptLine,TempTrackingSpecification);

      IF TrackingSpecificationExists THEN BEGIN
        TempTrackingSpecification."Quantity actual Handled (Base)" := QtyToBeInvoicedBase;
        TempTrackingSpecification.MODIFY;
      END;

      IF TrackingSpecificationExists THEN
        ItemTrackingMgt.AdjustQuantityRounding(
          RemQtyToBeInvoiced,QtyToBeInvoiced,
          RemQtyToBeInvoicedBase,QtyToBeInvoicedBase);

      RemQtyToBeInvoiced := RemQtyToBeInvoiced - QtyToBeInvoiced;
      RemQtyToBeInvoicedBase := RemQtyToBeInvoicedBase - QtyToBeInvoicedBase;
      ReturnRcptLine."Quantity Invoiced" :=
        ReturnRcptLine."Quantity Invoiced" + QtyToBeInvoiced;
      ReturnRcptLine."Qty. Invoiced (Base)" :=
        ReturnRcptLine."Qty. Invoiced (Base)" + QtyToBeInvoicedBase;
      ReturnRcptLine."Return Qty. Rcd. Not Invd." :=
        ReturnRcptLine.Quantity - ReturnRcptLine."Quantity Invoiced";

      // I-INIT INSERT
      OnBeforeUpdateInvoicedQtyOnReturnShipmentLine(ReturnRcptLine);
      // F-END INSERT

      ReturnRcptLine.MODIFY;

      IF PostItemTrackingForReceiptCondition(SalesLine,ReturnRcptLine) THEN
        PostItemJnlLine(
          SalesHeader,SalesLine,0,0,QtyToBeInvoiced,QtyToBeInvoicedBase,
          ItemEntryRelation."Item Entry No.",'',TempTrackingSpecification,FALSE);

      OnAfterPostItemTrackingReturnRcpt(
        SalesInvHeader,SalesShptLine,TempTrackingSpecification,TrackingSpecificationExists,
        SalesCrMemoHeader,ReturnRcptLine,SalesLine,QtyToBeInvoiced,QtyToBeInvoicedBase);

      IF TrackingSpecificationExists THEN
        EndLoop := (TempTrackingSpecification.NEXT = 0) OR (RemQtyToBeInvoiced = 0)
      ELSE
        EndLoop :=
          (ReturnRcptLine.NEXT = 0) OR (ABS(RemQtyToBeInvoiced) <= ABS(SalesLine."Return Qty. to Receive"));
    UNTIL EndLoop;
  END ELSE
    ERROR(
      ReturnReceiptInvoicedErr,
      SalesLine."Return Receipt Line No.",SalesLine."Return Receipt No.");
END;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
