### ISSUE TITLE
[Event Request] Application “Tests-Permissions” Codeunit 139453 "O365 Customer Permission Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#9846]
[Event Request]Application “Tests-Permissions”, 139453 "O365 Customer Permission Test"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic1](https://user-images.githubusercontent.com/45795262/99228631-2c5da880-27ed-11eb-9e3d-2dea14bef5b5.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
