### ISSUE TITLE
[Event Request] Application “Tests-Permissions” Codeunit 139452 "O365 Vendor Permission Test"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#9847]
[Event Request]Application “Tests-Permissions”, 139452 "O365 Vendor Permission Test"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic1](https://user-images.githubusercontent.com/45795262/99228916-9aa26b00-27ed-11eb-8a19-77c8803d1a0c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
