### ISSUE TITLE
[Event Request] Codeunit 224 EmplEntry-Apply Posted Entries - OnBeforePostUnapplyEmployeeLedgEntry

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#9848]
Hi

Could you please new event OnBeforePostUnapplyEmployeeLedgEntry in procedure PostUnApplyEmployee?

OLD CODE
    
    GenJnlLine."Posting Group" := EmplLedgEntry."Employee Posting Group";
    GenJnlLine."Source Currency Code" := "Currency Code";
    GenJnlLine."System-Created Entry" := true;
    Window.Open(UnapplyingMsg);            
    GenJnlPostLine.UnapplyEmplLedgEntry(GenJnlLine, DtldEmplLedgEntry2);
    
    if PreviewMode then
      GenJnlPostPreview.ThrowError;
    ...

NEW CODE:
    
    GenJnlLine."Posting Group" := EmplLedgEntry."Employee Posting Group";
    GenJnlLine."Source Currency Code" := "Currency Code";
    GenJnlLine."System-Created Entry" := true;

    >>>
    OnBeforePostUnapplyEmployeeLedgEntry(GenJnlLine, EmplLedgEntry, DtldEmplLedgEntry2, GenJnlPostLine);            
    <<<

    Window.Open(UnapplyingMsg);
    GenJnlPostLine.UnapplyEmplLedgEntry(GenJnlLine, DtldEmplLedgEntry2);
    
    if PreviewMode then
      GenJnlPostPreview.ThrowError;
    ...

    >>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostUnapplyEmployeeLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; EmplLedgerEntry: Record " Employee Ledger Entry"; DetailedEmplLedgEntry: Record " Detailed Employee Ledger Entry"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
    begin
    end;
    <<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
