### ISSUE TITLE
[Event Request] Codeunit::"Whse. Jnl.-Register Line" - Function RegisterRoundResidual - OnRegisterRoundResidualOnBeforeWhseJnlRegSetWhseRegister

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9849]
We like to request the following Event:
Object: Codeunit::"Whse. Jnl.-Register Line"
Function: RegisterRoundResidual
Publisher Event: OnRegisterRoundResidualOnBeforeWhseJnlRegSetWhseRegister
Reason: To implement custom business logic
Where is the event placed:
WhseJnlLine2."Qty. (Absolute)" := 0;
            WhseJnlLine2."Qty. (Absolute, Base)" := Abs(WhseJnlLine2."Qty. (Base)");
            **OnRegisterRoundResidualOnBeforeWhseJnlRegSetWhseRegister (WhseEntry, WhseEntry2, WhseJnlLine, WhseJnlLine2);**
            WhseJnlRegLine.SetWhseRegister(WhseReg);
            WhseJnlRegLine.Run(WhseJnlLine2);
            WhseJnlRegLine.GetWhseRegister(WhseReg);
            WhseEntryNo := WhseReg."To Entry No." + 1;
            "Entry No." := WhseReg."To Entry No." + 1;
Event Code:

[IntegrationEvent(false,   false)]         local procedure   OnBeforeWhseJnlRegSetWhseRegister(var WhseEntry: Record "Warehouse   Entry"; WhseEntry2: Record "Warehouse Entry"; WhseJnlLine:   Record "Warehouse Journal Line"; WhseJnlLine2: Record   "Warehouse Journal Line")         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
