### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Act.-Register (Yes/No)" - Code- OnCodeOnCheckSourceDocumentIsSupportedForInvtMovement

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9850]
We like to request the following Event:
Object: Codeunit::"Whse.-Act.-Register   (Yes/No)"
Function: local   procedure "Code"
Publisher Event: OnCodeOnCheckSourceDocumentIsSupportedForInvtMovement
Reason: To implement custom business logic
Where is the event placed:

        OnBeforeCode(WhseActivLine);

        with WhseActivLine do begin
            OnCheckSourceDocumentIsSupportedForInvtMovement(WhseActivLine."Source Document", IsHandled);
            if not IsHandled then
                if ("Activity Type" = "Activity Type"::"Invt. Movement") and
                   not ("Source Document" in ["Source Document"::" ",
                                              "Source Document"::"Prod. Consumption",
                                              "Source Document"::"Assembly Consumption"])
                then
                    Error(Text002, "Source Document");
end;

            WMSMgt.CheckBalanceQtyToHandle(WhseActivLine);

[IntegrationEvent(false, false)]         local procedure   OnCheckSourceDocumentIsSupportedForInvtMovement(WhseActLineSourceDoc: Option;   var IsHandled: Boolean)         begin         end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
