### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Activity-Register"- CheckLines- 	OnCheckLinesOnBeforeCheckWhseActivLineBinCodeExpected

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9851]
We like to request the following Event:
Object: Codeunit::"Whse.-Activity-Register"
Function: CheckLines
Publisher Event: OnCheckLinesOnBeforeCheckWhseActivLineBinCodeExpected
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckLines()
    var
        IsHandled: Boolean;
    begin
        OnBeforeCheckLines(WhseActivHeader, WhseActivLine, TempBinContentBuffer);

        with WhseActivHeader do begin
            TempBinContentBuffer.DeleteAll();
            LineCount := 0;
            if WhseActivLine.Find('-') then
                repeat
                    LineCount := LineCount + 1;
                    UpdateWindow(2, '');
                    WhseActivLine.CheckBinInSourceDoc;
                    WhseActivLine.TestField("Item No.");
                    if (WhseActivLine."Activity Type" = WhseActivLine."Activity Type"::Pick) and
                       (WhseActivLine."Destination Type" = WhseActivLine."Destination Type"::Customer)
                    then begin
                        WhseActivLine.TestField("Destination No.");
                        Cust.Get(WhseActivLine."Destination No.");
                        Cust.CheckBlockedCustOnDocs(Cust, "Source Document", false, false);
                    end;
                    if Location."Bin Mandatory" then begin
                        **OnBeforeCheckWhseActivLineBinCodeExpected(WhseActivLine, IsHandled);
                        if not IsHandled then begin**
                            WhseActivLine.TestField("Unit of Measure Code");
                            WhseActivLine.TestField("Bin Code");
                            WhseActivLine.CheckWhseDocLine;
                            UpdateTempBinContentBuffer(WhseActivLine);
                        end;
                    end;
                    OnAfterCheckWhseActivLine(WhseActivLine);
    
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWhseActivLineBinCodeExpected(WhseActivityLine: Record "Warehouse Activity Line"; var Handled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
