### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Activity-Register" -RegisterWhseActivityLines 

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9853]
We like to request the following Event:
Object: Codeunit::"Whse.-Activity-Register"
Function: RegisterWhseActivityLines
Publisher Event: OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields
Reason: To implement custom business logic
Where is the event placed:
OnAfterFindWhseActivLine(WarehouseActivityLine);
                if "Qty. Outstanding" = "Qty. to Handle" then begin
                    SkipDelete := false;
                    OnBeforeWhseActivLineDelete(WarehouseActivityLine, SkipDelete);
                    if not SkipDelete then
                        Delete;
                end else begin
                    QtyDiff := "Qty. Outstanding" - "Qty. to Handle";
                    QtyBaseDiff := "Qty. Outstanding (Base)" - "Qty. to Handle (Base)";
                    **IsHandled := false;
                    OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields(WarehouseActivityLine, QtyDiff, QtyBaseDiff, HideDialog, IsHandled);
                    if not IsHandled then begin**
                        Validate("Qty. Outstanding", QtyDiff);
                        if "Qty. Outstanding (Base)" > QtyBaseDiff then // round off error- qty same, not base qty
                            "Qty. Outstanding (Base)" := QtyBaseDiff;

[IntegrationEvent(false, false)]
    local procedure OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields(var WarehouseActivityLine: Record "Warehouse Activity Line"; var QtyDiff: Decimal; var QtyBaseDiff: Decimal; HideDialog: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
