### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function PostUpdateWhseDocuments - OnPostUpdateWhseDocumentsBeforeValidateQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9854]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: PostUpdateWhseDocuments
Publisher Event: OnPostUpdateWhseDocumentsBeforeValidateQty
Reason: To implement custom business logic
Where is the event placed:
procedure PostUpdateWhseDocuments(var WhseRcptHeader: Record "Warehouse Receipt Header")
    var
        WhseRcptLine2: Record "Warehouse Receipt Line";
        WhsePutAwayRequest: Record "Whse. Put-away Request";
        DeleteWhseRcptLine: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforePostUpdateWhseDocuments(WhseRcptHeader);
        with WhseRcptLineBuf do
            if Find('-') then begin
                repeat
                    WhseRcptLine2.Get("No.", "Line No.");
                    DeleteWhseRcptLine := "Qty. Outstanding" = "Qty. to Receive";
                    OnBeforePostUpdateWhseRcptLine(WhseRcptLine2, WhseRcptLineBuf, DeleteWhseRcptLine, WhseRcptHeader);
                    if DeleteWhseRcptLine then
                        WhseRcptLine2.Delete
                    else begin
                        IsHandled := false;
                        OnPostUpdateWhseDocumentsBeforeValidateQty(WhseRcptLine2, WhseRcptLineBuf, IsHandled);
                        if not IsHandled then begin
                            WhseRcptLine2.Validate("Qty. Received", "Qty. Received" + "Qty. to Receive");
                            WhseRcptLine2.Validate("Qty. Outstanding", "Qty. Outstanding" - "Qty. to Receive");
                            WhseRcptLine2."Qty. to Cross-Dock" := 0;
                            WhseRcptLine2."Qty. to Cross-Dock (Base)" := 0;
                            WhseRcptLine2.Status := WhseRcptLine2.GetLineStatus;
                            WhseRcptLine2.Modify();
                            OnAfterPostUpdateWhseRcptLine(WhseRcptLine2);
                        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostUpdateWhseDocumentsBeforeValidateQty(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; var WarehouseReceiptLineBuf: Record "Warehouse Receipt Line"; var IsHandled: Boolean)
    begin

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
