### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function HandlePurchaseLine - OnBeforeFindWhseShptLineForPurchLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9855]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: HandlePurchaseLine
Publisher Event: OnBeforeFindWhseShptLineForPurchLine
Reason: To implement custom business logic
Where is the event placed:
local procedure HandlePurchaseLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        PurchLine: Record "Purchase Line";
        ModifyLine: Boolean;
        IsHandled: Boolean;
    begin
        with WhseShptLine do begin
            PurchLine.SetRange("Document Type", "Source Subtype");
            PurchLine.SetRange("Document No.", "Source No.");
            if PurchLine.Find('-') then
                repeat
                    SetRange("Source Line No.", PurchLine."Line No.");
                    IsHandled := false;
                    OnBeforeFindWhseShptLineForPurchLine(WhseShptLine, PurchLine, WhseShptHeader, ModifyLine, IsHandled);
                    if not IsHandled then begin
                        if Find('-') then begin
Event Code:

[IntegrationEvent(false,   false)]         local procedure   OnBeforeFindWhseShptLineForPurchLine(var WarehouseShipmentLine: Record   "Warehouse Shipment Line"; var PurchLine: Record "Purchase   Line"; WhseShptHeader: Record "Warehouse Shipment Header"; var   ModifyLine: Boolean; var IsHandled: Boolean)         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
