### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function HandleSalesLine - OnBeforeFindWhseShptLineForSalesLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9856]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: HandleSalesLine
Publisher Event: OnBeforeFindWhseShptLineForSalesLine
Reason: To implement custom business logic
Where is the event placed:
with WhseShptLine do begin
            SalesLine.SetRange("Document Type", "Source Subtype");
            SalesLine.SetRange("Document No.", "Source No.");
            if SalesLine.Find('-') then
                repeat
                    SetRange("Source Line No.", SalesLine."Line No.");
                    IsHandled := false;
                    OnBeforeFindWhseShptLineForSalesLine(WhseShptLine, SalesLine, SalesHeader, WhseShptHeader, ModifyLine, IsHandled);
                    if not IsHandled then begin
                        if Find('-') then begin
Event Code:

[IntegrationEvent(false,   false)]         local procedure   OnBeforeFindWhseShptLineForSalesLine(var WarehouseShipmentLine: Record   "Warehouse Shipment Line"; var SalesLine: Record "Sales   Line"; SalesHeader: Record "Sales Header"; WhseShptHeader:   Record "Warehouse Shipment Header"; var ModifyLine: Boolean; var   IsHandled: Boolean)         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
