### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function HandleTransferLine - OnBeforeFindWhseShptLineForTransLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9857]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: HandleTransferLine
Publisher Event: OnBeforeFindWhseShptLineForTransLine
Reason: To implement custom business logic
Where is the event placed:
with WhseShptLine do begin
            TransLine.SetRange("Document No.", "Source No.");
            TransLine.SetRange("Derived From Line No.", 0);
            if TransLine.Find('-') then
                repeat
                    SetRange("Source Line No.", TransLine."Line No.");
                    IsHandled := false;
                    OnBeforeFindWhseShptLineForTransLine(WhseShptLine, TransLine, WhseShptHeader, ModifyLine, IsHandled);
                    if not IsHandled then begin
                        if Find('-') then begin
                            OnAfterFindWhseShptLineForTransLine(WhseShptLine, TransLine);
Event Code:

[IntegrationEvent(false,   false)]         local procedure   OnBeforeFindWhseShptLineForTransLine(var WarehouseShipmentLine: Record   "Warehouse Shipment Line"; var TransLine: Record "Transfer   Line"; WhseShptHeader: Record "Warehouse Shipment Header"; var   ModifyLine: Boolean; var IsHandled: Boolean)         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
