### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function InitSourceDocumentHeader - OnInitSourceDocumentHeaderOnBeforeReleaseSalesHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9858]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: InitSourceDocumentHeader
Publisher Event: OnInitSourceDocumentHeaderOnBeforeReleaseSalesHeader
Reason: To implement custom business logic
Where is the event placed:
DATABASE::"Sales Line":
                    begin
                        OnInitSourceDocumentHeaderOnBeforeValidatePostingDate(SalesHeader, WhseShptLine, ValidatePostingDate);
                        if (SalesHeader."Posting Date" = 0D) or
                           (SalesHeader."Posting Date" <> WhseShptHeader."Posting Date") or ValidatePostingDate
                        then begin
                            OnInitSourceDocumentHeaderOnBeforeReopenSalesHeader(SalesHeader, Invoice);
                            SalesRelease.Reopen(SalesHeader);
                            SalesRelease.SetSkipCheckReleaseRestrictions;
                            SalesHeader.SetHideValidationDialog(true);
                            SalesHeader.Validate("Posting Date", WhseShptHeader."Posting Date");
                            OnInitSourceDocumentHeaderOnBeforeReleaseSalesHeader(SalesHeader, WhseShptHeader, WhseShptLine);
                            SalesRelease.Run(SalesHeader);
                            ModifyHeader := true;
                        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnBeforeReleaseSalesHeader(var SalesHeader: Record "Sales Header"; var WhseShptHeader: Record "Warehouse Shipment Header"; var WhseShptLine: Record "Warehouse Shipment Line")

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
