### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function PostUpdateWhseDocuments - OnPostUpdateWhseDocumentsBeforeValidateQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9859]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: PostUpdateWhseDocuments
Publisher Event: OnPostUpdateWhseDocumentsBeforeValidateQty
Reason: To implement custom business logic
Where is the event placed:
OnBeforeDeleteUpdateWhseShptLine(WhseShptLine2, DeleteWhseShptLine);
                    if DeleteWhseShptLine then begin
                        ItemTrackingMgt.SetDeleteReservationEntries(true);
                        ItemTrackingMgt.DeleteWhseItemTrkgLines(
                          DATABASE::"Warehouse Shipment Line", 0, "No.", '', 0, "Line No.", "Location Code", true);
                        WhseShptLine2.Delete();
                    end else begin
                        OnBeforePostUpdateWhseShptLine(WhseShptLine2);
                        IsHandled := false;
                        OnPostUpdateWhseDocumentsBeforeValidateQty(WhseShptLine2, WhseShptLineBuf, WhseShptHeaderParam, IsHandled);
                        if not IsHandled then begin
                            WhseShptLine2."Qty. Shipped" := "Qty. Shipped" + "Qty. to Ship";
                            WhseShptLine2.Validate("Qty. Outstanding", "Qty. Outstanding" - "Qty. to Ship");
                            WhseShptLine2."Qty. Shipped (Base)" := "Qty. Shipped (Base)" + "Qty. to Ship (Base)";
                            WhseShptLine2."Qty. Outstanding (Base)" := "Qty. Outstanding (Base)" - "Qty. to Ship (Base)";
                            WhseShptLine2.Status := WhseShptLine2.CalcStatusShptLine;
                            OnBeforePostUpdateWhseShptLineModify(WhseShptLine2, WhseShptLineBuf);
                            WhseShptLine2.Modify();
                            OnAfterPostUpdateWhseShptLine(WhseShptLine2);
                        end;
                    end;
Event Code:

[IntegrationEvent(false,   false)]         local procedure   OnPostUpdateWhseDocumentsBeforeValidateQty(var WarehouseShipmentLine: Record   "Warehouse Shipment Line"; var WarehouseShipmentLineBuf: Record "Warehouse   Shipment Line"; var WhseShptHeader: Record "Warehouse Shipment   Header"; var IsHandled: Boolean)         begin         end;
--

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
