### ISSUE TITLE
Sales/Purchase Blocked for G/L Accounts

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#986]
For Items the new fields "Sales Blocked" and "Purchase Blocked" were invented with BC130 and on Table 37/39 the field "No." has a modified table relation to allow the refering items only for sales or purchasing.

We have the same idea on items and on G/l accounts, too. So if thos two fields would be added to table 15 and the table realtion in T37/39 would be enhanced similar to items we could delete our Extension with this implementation.

**Comment by BenjaminHochstetter** [comment]
I agree please add the fields also to the G/L Accounts.
And please don't forget the "Service" with fields like:
- "Service Sales Blocked"
- "Service Consumption Blocked"

**Comment by AndreiPanko** [comment]
I'm closing the issue for two reasons:
1. it's not extensibility request but new functionality request
2. there are no plans to extends functionlaity for GLs. If advanced functionality is needed: attributes, prices, UoM, undo, etc (including extended blocking) - use Items (normal ones or of type Service).
