### ISSUE TITLE
event request - report 1316 "Standard Statement" - DtldCustLedgEntriesOnPreDataItemOnAfterSetFilters(var DetailedCustLedgEntry)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9860]
We frequently are asked to make the Standard Statement only show Open customer ledger entries, either as a 'hard-coded' change or via a request page option. Currently we have no events enabling us to do this via the standard report object, so we must copy-and-paste it, and that's obviously bad for plenty of reasons. Therefore, please help by adding events as needed.

This issue is for the addition of the following event emission:

                        dataitem(DtldCustLedgEntries; "Detailed Cust. Ledg. Entry")
                        {
                            DataItemTableView = SORTING("Customer No.", "Posting Date", "Entry Type", "Currency Code");
                            [...]
                            trigger OnPreDataItem()
                            begin
                                SetRange("Customer No.", Customer."No.");
                                SetRange("Posting Date", StartDate, EndDate);
                                SetRange("Currency Code", TempCurrency2.Code);

                                // +new
                                DtldCustLedgEntriesOnPreDataItemOnAfterSetFilters(DtldCustLedgEntries);
                                // +old

                                if TempCurrency2.Code = '' then begin
                                    GLSetup.TestField("LCY Code");
                                    CurrencyCode3 := GLSetup."LCY Code"
                                end else
                                    CurrencyCode3 := TempCurrency2.Code;

                                IsFirstPrintLine := true;
                            end;

declared as 

    [EventPublisher(false, false)]
    local procedure DtldCustLedgEntriesOnPreDataItemOnAfterSetFilters(var DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry")

where we need to do the following:

    local procedure SomeSubscriber(var DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry")
    begin
        if SomeOtherLogic() then
            DetailedCustLedgEntry.SetRange("Entry Type", DetailedCustLedgEntry."Entry Type"::"Initial Entry");
    end;

See also #9861, #9883

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
