### ISSUE TITLE
event request - report 1316 "Standard Statement" - DtldCustLedgEntriesOnAfterGetCustLedgerEntry(DetailedCustLedgEntry, CustLedgerEntry, var Skip)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9861]
We frequently are asked to make the Standard Statement only show Open customer ledger entries, either as a 'hard-coded' change or via a request page option. Currently we have no events enabling us to do this via the standard report object, so we must copy-and-paste it, and that's obviously bad for plenty of reasons. Therefore, please help by adding events as needed.

This issue is for the addition of the following event emission:

                        dataitem(DtldCustLedgEntries; "Detailed Cust. Ledg. Entry")
                        {
                            DataItemTableView = SORTING("Customer No.", "Posting Date", "Entry Type", "Currency Code");
                            [...]
                            trigger OnAfterGetRecord()
                            // +new
                            var
                                Skip: Boolean;
                            //- new
                            begin
                                if SkipReversedUnapplied(DtldCustLedgEntries) or (Amount = 0) then
                                    CurrReport.Skip();
                                RemainingAmount := 0;
                                PrintLine := true;
                                case "Entry Type" of
                                    "Entry Type"::"Initial Entry":
                                        begin
                                            CustLedgerEntry.Get("Cust. Ledger Entry No.");

                                            // +new
                                            DtldCustLedgEntriesOnAfterGetCustLedgerEntry(DtldCustLedgEntry, CustLedgerEntry, Skip);

                                            if Skip then
                                                CurrReport.Skip().
                                            // - new

                                            Description := CustLedgerEntry.Description;
                                            DueDate := CustLedgerEntry."Due Date";
                                            CustLedgerEntry.SetRange("Date Filter", 0D, EndDate);
                                            CustLedgerEntry.CalcFields("Remaining Amount");
                                            RemainingAmount := CustLedgerEntry."Remaining Amount";
                                            CustLedgerEntry.SetRange("Date Filter");
                                        end;
                                    "Entry Type"::Application:

to be declared as

    [EventPublisher(false, false)]
    local procedure DtldCustLedgEntriesOnAfterGetCustLedgerEntry(DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; CustLedgerEntry: Record "Cust. Ledger Entry"; var Skip: Boolean);

where in this case we will be subscribing as follows:

    local procedure SomeSubscriber(DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; CustLedgerEntry: Record "Cust. Ledger Entry"; var Skip: Boolean)
    begin
        Skip := not CustLedgerEntry.Open;
    end;

See also #9860, #9883

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
