### ISSUE TITLE
parameter request - table 77 "Report Selections" - OnBeforeGetEmailAddress() - CustNo

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9862]
Please pass to subscribers the CustNo parameter from the outer function, so we don't have to figure it out ourselves from the RecordVariant or whatever. This is the only argument to the outer function that doesn't get passed to the subscribers. Thanks!

    local procedure GetEmailAddress(ReportUsage: Enum "Report Selection Usage"; RecordVariant: Variant; CustNo: Code[20]; var TempBodyReportSelections: Record "Report Selections" temporary): Text[250]
    var
        DataTypeManagement: Codeunit "Data Type Management";
        RecordRef: RecordRef;
        FieldRef: FieldRef;
        DocumentNo: Code[20];
        EmailAddress: Text[250];
        IsHandled: Boolean;
    begin
        // old:
        // OnBeforeGetEmailAddress(ReportUsage.AsInteger(), RecordVariant, TempBodyReportSelections, EmailAddress, IsHandled);

        // new:
        OnBeforeGetEmailAddress(ReportUsage.AsInteger(), RecordVariant, CustNo,TempBodyReportSelections, EmailAddress, IsHandled);

        if IsHandled then
            exit(EmailAddress);

new event publisher declaration:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetEmailAddress(ReportUsage: Option; RecordVariant: Variant; CustNo: Code[20]; var TempBodyReportSelections: Record "Report Selections" temporary; var EmailAddress: Text[250]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
