### ISSUE TITLE
[Extensibility] OnLookupDimValueCodeOnBeforeDimValRunModal in codeunit DimensionManagement

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#9867]
Hi, please consider adding a new parameter for the event `OnLookupDimValueCodeOnBeforeDimValRunModal` in codeunit 408 `DimensionManagement`.

Current version:

```
    [IntegrationEvent(false, false)]
    local procedure OnLookupDimValueCodeOnBeforeDimValRunModal(var DimensionValue: Record "Dimension Value")
    begin
    end;
```

Proposed version:

```
    [IntegrationEvent(false, false)]
    local procedure OnLookupDimValueCodeOnBeforeDimValRunModal(var DimensionValue: Record "Dimension Value"; FieldNumber: Integer)
    begin
    end;
```

The `LookupDimValueCode` should be modified accordingly, passing the `FieldNumber` when raising the event.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
