### ISSUE TITLE
Suggesting updates to DotNet_Image and DotNet_ImageFormat

### ISSUE THREAD

**Issue by vjekob** [microsoft/ALAppExtensions#9868]
Hi,

I'd like to make some code suggestions to DotNet_Image and DotNet_ImageFormat wrapper codeunits. However, they are a part of the Base Application, rather than an app extension.

How should I proceed with this?

Thanks!

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
You've got mail ;-)

**Comment by JesperSchulz** [comment]
Closing this issue and hoping to receive a PR with a brand new Image Formatter module ;-)
