### ISSUE TITLE
[Event Request] Page 10767  "Posted Purch. Cr.Memo - Update" - OnAfterRecordChanged

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#9869]
Good morning everyone,

i asked for an event time ago. It was implemented in latest updates, but not on this page. It´s the same event as the other purchase pages, i dont understand why it wasnt added to the Posted Purchase Cr. Memos. I will add the code just in order to make your work easier.

**EVENT LOCALIZATION**
**Old Code**
```
local procedure RecordChanged(): Boolean
    begin
        exit(
          ("Special Scheme Code" <> xPurchCrMemoHdr."Special Scheme Code") or
          ("Cr. Memo Type" <> xPurchCrMemoHdr."Cr. Memo Type") or
          ("Correction Type" <> xPurchCrMemoHdr."Correction Type"));
    end;
```
**New Code**
```
local procedure RecordChanged() IsChanged: Boolean
    begin
        IsChanged :=
          ("Special Scheme Code" <> xPurchCrMemoHdr."Special Scheme Code") or
          ("Cr. Memo Type" <> xPurchCrMemoHdr."Cr. Memo Type") or
          ("Correction Type" <> xPurchCrMemoHdr."Correction Type");

        OnAfterRecordChanged(Rec, xRec, IsChanged);
    end;
```

**EVENT DECLARATION**
```
 [IntegrationEvent(false, false)]
    local procedure OnAfterRecordChanged(var PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; xPurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; var IsChanged: Boolean)
    begin
    end;
```

Kind regards.

**Comment by frivadulla** [comment]
related with this closed issue 
[https://github.com/microsoft/ALAppExtensions/issues/6149](url)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
