### ISSUE TITLE
codeunit 8800 "Custom Layout Reporting" - SetTableFilterForReportID() - does not honour report substitutions

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9871]
`SetTableFilterForReportID()` is called, for example, by the `Customer Card` as follows, to default the filter on the `Customer No.` to the record that was being viewed on the card:

![image](https://user-images.githubusercontent.com/63455896/99387548-170b7b80-28cc-11eb-8077-97dfeaac42d3.png)

***

The problem here is that if we subscribe to `ReportManagement.OnAfterSubstituteReport` and replace the `Standard Statement` with our customised one, then the above means the `Customer No.` filter is saved for the original report ID, not the one whose request page is actually opened by `Custom Layout Reporting`... so we lose the default filter on the `No.`. This annoys customers and seems like an obvious point of hard-coding where there shouldn't be.

This applies to anywhere else where this is happening, though I didn't go looking for cases.

***

Is there a way that `SetTableFilterForReportID()` can go via `SubstituteReport` and thus save the _new_ report ID after substitution, so the request page filters default in the same way, whether or not the report has been substituted?

Thanks!

*** 
For reference, that function currently looks like this:

    procedure SetTableFilterForReportID(ReportID: Integer; CustomerNo: Text);
    begin
        TableFilterForReportID := ReportID;
        TableFilterTxt := StrSubstNo(TableFilterTok, Format(ReportID), STRSUBSTNO(EscapeTok, ParseCustomerNo(CustomerNo)));
    end;

and those global variables will later be used here:

    [Scope('OnPrem')]
    procedure GetReportRequestPageParameters(ReportID: Integer) XMLTxt: Text
    [...]
        if IgnoreRequestParameters then
            exit('');
        If ReportId = TableFilterForReportID then
            exit(TableFilterTxt);
        if not ObjectOptions.Get(LastUsedTxt, ReportID, ObjectOptions."Object Type"::Report, UserId, CompanyName) then
            exit('');
        ObjectOptions.CalcFields("Option Data");
        ObjectOptions."Option Data".CreateInStream(InStr);
        InStr.ReadText(XMLTxt);
        exit(XMLTxt);
    end;

**Comment by dtkb** [comment]
workarounds for this that I've considered and failed:
* I can't use OnBeforeAction() in our page extension, because Custom Layout Reporting only saves 1 latest report ID/filter, so its one just overwrites ours from OnBeforeAction.
* I can't replace the entire trigger, because it calls OnPrem methods, which we can't do in a SaaS extension.

I guess we'd have to add our own single-instance codeunit, in which to stash the customer no, and reload it when opening the request page of our customised report... but I'm far from convinced it's worth that much hassle just to preserve standard functionality that shouldn't be broken by report substitutions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by dtkb** [comment]
@JesperSchulz How was this fixed, and in which version(s)? 17.5 doesn't seem to have it. I couldn't check 18.0 yet.

> We will update this issue with information about availability.

Yet no one who says this ever does! Can you either actually do it, or remove it from your stock message? ;-)

**Comment by JesperSchulz** [comment]
That "GitHub issue updating automation" is indeed not very robust. If developers deviate the slightest from our processes or fill in some not 100% accurate information in our internal work items, the automation breaks and doesn't report anything back. It is supposed to work like in this issue (#10481), but that seems to be the exception rather than the rule. I'll see what I can do about that.
Now to your actual question. I can see that a checkin was made on the 8th of February, meaning the fix has shipped with version 18. The changes made to the customer card look at little something like this:
![image](https://user-images.githubusercontent.com/19796701/113728366-565d2c00-96f6-11eb-94e2-7e15b192f4eb.png)

I hope that answers your question.

**Comment by dtkb** [comment]
Thanks for the info and investigation!

Can that be backported to BC17 and possibly earlier? Or do you confider it too 'large' to do so?

That said, I don't think the approach taken above can work fully, for several reasons...
1. If the Customer has no Custom Report Selection of their own, and will just use the one from the overall Report Selection - Sales page, that won't be acknowledged here.
2. Even if they do have a Custom Report Selection, that code just looks up the first for **any** customer, not necessarily the one being reported for... which can result in wrong IDs getting used and hence the functionality stopping working again.
3. It doesn't honour report substitution as requested! I'd expected that even if the report selections used the Standard Statement, if we were substituting that with something else in the AL code - *not* in the Report Selections - that said substitution would be honoured. Mind you, I don't know if that would work with Custom Layout Reporting for potentially innumerable other reasons... but it was what was requested ;-)

Just my thoughts - appreciate that _some_ effort has been made anyway - and by using the above setup, we could conceivably work around the problem for some cases - but it looks lacking and brittle at the moment.

**Comment by JesperSchulz** [comment]
I have forwarded your comment to the author of the code. As this case is closed, please create a new issue, if you have further requests, as closed issues disappear from our radar. Thanks for the input!
