### ISSUE TITLE
[Event requests] We need OnBeforeInitInsert and OnBeforeInitRecord events in Item and Resource tables

### ISSUE THREAD

**Issue by eque2al** [microsoft/ALAppExtensions#9872]
As per the title we need these urgently for our solution so that we can automatically choose a different number series when entering a new Item or Resource via our new App.  

We have used these events from the Purchase Header successfully - they are perfect for this purpose - so now require the same structure in the MS base app for the Item and Resource tables.

Please can you add these to the BC product **ASAP** as we can't complete our offering without these events.  An indication of timescale would be **very** much appreciated.

Many thanks in advance,
Al.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
