### ISSUE TITLE
[Event Request] Page 26 Vendor Card - Add new param in publisher OnBeforeCreateVendorFromTemplate

### ISSUE THREAD

**Issue by haynt** [microsoft/ALAppExtensions#9873]
Hi Team

In the Page 26 - Vendor Card, we need to customize some default values. Standard publisher OnBeforeCreateVendorFromTemplate would suit us you could add Vendor record param with following exit functionality. Please refer the red mark in the below image.

Thank Team.
![image](https://user-images.githubusercontent.com/74607740/99402687-316d4580-291c-11eb-828a-785cb9cf0d3c.png)

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
