### ISSUE TITLE
[Event Request] Codeunit 1381 "Customer Templ. Mgt." - OnBeforeModifyCustomerApplyTemplate

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#9881]
Hi

Could you please add an integration event in ApplyTemplate procedure.

OLD CODE

        ...
        Customer."VAT Bus. Posting Group" := CustomerTempl."VAT Bus. Posting Group";
        Customer."Block Payment Tolerance" := CustomerTempl."Block Payment Tolerance";
        Customer."Validate EU Vat Reg. No." := CustomerTempl."Validate EU Vat Reg. No.";
        Customer.Blocked := CustomerTempl.Blocked;
        Customer.Modify(true);
    end;
        ...

NEW CODE

        ...
        Customer."VAT Bus. Posting Group" := CustomerTempl."VAT Bus. Posting Group";
        Customer."Block Payment Tolerance" := CustomerTempl."Block Payment Tolerance";
        Customer."Validate EU Vat Reg. No." := CustomerTempl."Validate EU Vat Reg. No.";
        Customer.Blocked := CustomerTempl.Blocked;

        >>>
        OnBeforeModifyCustomerApplyTemplate(Customer,CustomerTempl);
        <<<

        Customer.Modify(true);
    end;
        ...

    >>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyCustomerApplyTemplate(var Customer: Record Customer; CustomerTempl: Record "Customer Templ.")
    begin
    end;
    <<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
