### ISSUE TITLE
[Event Request] Codeunit 1385 "Vendor Templ. Mgt." - OnBeforeModifyVendorApplyTemplate

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#9882]
Hi

Could you please add an integration event in ApplyTemplate procedure.

OLD CODE

    ...
        Vendor."Block Payment Tolerance" := VendorTempl."Block Payment Tolerance";
        Vendor."Validate EU Vat Reg. No." := VendorTempl."Validate EU Vat Reg. No.";
        Vendor.Blocked := VendorTempl.Blocked;
        Vendor.Modify(true);
    end;
    ...
NEW CODE

    ...
        Vendor."Block Payment Tolerance" := VendorTempl."Block Payment Tolerance";
        Vendor."Validate EU Vat Reg. No." := VendorTempl."Validate EU Vat Reg. No.";
        Vendor.Blocked := VendorTempl.Blocked;

    >>>
    OnBeforeModifyVendorApplyTemplate(Vendor,VendorTempl);
    <<<

        Vendor.Modify(true);
    end;
    ...

    >>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyVendorApplyTemplate(var Vendor: Record Vendor; VendorTempl: Record "Vendor Templ.")
    begin
    end;
    <<<

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
