### ISSUE TITLE
event request - report 1316 "Standard Statement" - OverdueCustLedgerEntryOnPreDataItemOnAfterSetFilters(var CustLedgerEntry)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#9883]
We frequently are asked to make the Standard Statement only show Open customer ledger entries, either as a 'hard-coded' change or via a request page option. Currently we have no events enabling us to do this via the standard report object, so we must copy-and-paste it, and that's obviously bad for plenty of reasons. Therefore, please help by adding events as needed.

This issue is for the addition of the following event emission:

                        dataitem(CustLedgEntry2; "Cust. Ledger Entry")
                        {
                            DataItemLink = "Customer No." = FIELD("No.");
                            DataItemLinkReference = Customer;
                            DataItemTableView = SORTING("Customer No.", Open, Positive, "Due Date");
                            [...]
                            trigger OnPreDataItem()
                            begin
                                if not IncludeAgingBand then
                                    SetRange("Due Date", 0D, EndDate - 1);

                                SetRange("Currency Code", TempCurrency2.Code);

                                // +new
                                OverdueCustLedgerEntryOnPreDataItemOnAfterSetFilters(CustLedgEntry2);
                                // +new

                                if (not PrintEntriesDue) and (not IncludeAgingBand) then
                                    CurrReport.Break();
                            end;
                        }

declared as 

    [EventPublisher(false, false)]
    local procedure OverdueCustLedgerEntryOnPreDataItemOnAfterSetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry")

where we need to do the following:

    local procedure SomeSubscriber(var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
        if SomeOtherLogic() then
            CustLedgerEntry.SetRange(Open, true);
    end;

See also #9860, #9861

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
