### ISSUE TITLE
[Event Request] Codeunit::"WMS Management" - Function CheckBalanceQtyToHandle - OnBeforeCheckErrorsInCheckBalanceQtyToHandle

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9887]
We like to request the following Event:
Object: Codeunit::"WMS Management"
Function: CheckBalanceQtyToHandle
Publisher Event: OnCheckBalanceQtyToHandleOnBeforeCheckErrors
Reason: To implement custom business logic
Where is the event placed:
    if QtyToPick <> QtyToPutAway then begin
                        IsHandled := false;
                        OnCheckBalanceQtyToHandleOnBeforeCheckErrors (WhseActivLine3, QtyToPick, QtyToPutAway, ErrorText, IsHandled);
                        if not IsHandled then
                            if WhseActivLine3.TrackingFilterExists() then
                                    ErrorText :=
                                    StrSubstNo(
                                        Text016,
                                    WhseActivLine.FieldCaption("Item No."), WhseActivLine."Item No.",
                                    WhseActivLine.FieldCaption("Variant Code"), WhseActivLine."Variant Code",
                                    WhseActivLine.FieldCaption("Lot No."), WhseActivLine."Lot No.",
                                    WhseActivLine.FieldCaption("Serial No."), WhseActivLine."Serial No.",
                                        QtyToPick, QtyToPutAway)
                                else
                                    ErrorText :=
                                    StrSubstNo(
                                        Text005,
                                    WhseActivLine.FieldCaption("Item No."), WhseActivLine."Item No.",
                                    WhseActivLine.FieldCaption("Variant Code"), WhseActivLine."Variant Code",
                                    QtyToPick, QtyToPutAway);
                            HandleError(ErrorText);
                    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCheckBalanceQtyToHandleOnBeforeCheckErrors (var WhseActivLine: Record "Warehouse Activity Line"; QtyToPick: Decimal; QtyToPutAway: Decimal; var ErrorTxt: Text; var IsHandled: Boolean)
    begin
    end

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
