### ISSUE TITLE
[Event Request] - Codeunit::"WMS Management" - BinContentLookUp -OnBeforeBinContentLookUp

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9888]
We like to request the following Event:
Object: Codeunit::"WMS Management"
Function: BinContentLookUp
Publisher Event: OnBeforeBinContentLookUp
Reason: To implement custom business logic
Where is the event placed:
procedure BinContentLookUp(LocationCode: Code[10]; ItemNo: Code[20]; VariantCode: Code[10]; ZoneCode: Code[10]; LotNo: Code[50]; SerialNo: Code[50]; CurrBinCode: Code[20]): Code[20]
    var
        BinContent: Record "Bin Content";
        BinCode: Code[20];
        IsHandled: Boolean;
    begin
        OnBeforeBinContentLookUp(LocationCode, ItemNo, VariantCode, ZoneCode, LotNo, SerialNo, CurrBinCode, BinCode, IsHandled);
        if IsHandled then
            exit(BinCode);

        GetItem(ItemNo);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeBinContentLookUp(LocationCode: Code[10]; ItemNo: Code[20]; VariantCode: Code[10]; ZoneCode: Code[10]; LotNo: Code[50]; SerialNo: Code[50]; CurrBinCode: Code[20]; BinCode: Code[20]; var IsHandled: Boolean)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
