### ISSUE TITLE
[Event Request] Codeunit::"WMS Management"- Function CheckBalanceQtyToHandle- OnBeforeCheckBalanceQtyToHandle

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9889]
We like to request the following Event:
Object: Codeunit::"WMS   Management"
Function: CheckBalanceQtyToHandle
Publisher Event: OnBeforeCheckBalanceQtyToHandle
Reason: To implement business logic
Where is the event placed:
procedure CheckBalanceQtyToHandle(var WhseActivLine2: Record "Warehouse Activity Line")
    var
        WhseActivLine: Record "Warehouse Activity Line";
        WhseActivLine3: Record "Warehouse Activity Line";
        TempWhseActivLine: Record "Warehouse Activity Line" temporary;
        QtyToPick: Decimal;
        QtyToPutAway: Decimal;
        ErrorText: Text[250];
        IsHandled: Boolean;
    begin
        OnBeforeCheckBalanceQtyToHandle(WhseActivLine2);
        WhseActivLine.Copy(WhseActivLine2);
        with WhseActivLine do begin
            SetCurrentKey("Activity Type", "No.", "Item No.", "Variant Code", "Action Type");
            SetRange("Activity Type", "Activity Type");
            SetRange("No.", "No.");
            SetRange("Action Type");
            if FindSet then
Event Code:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckBalanceQtyToHandle(var WhseActivityLine: Record "Warehouse Activity Line")
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
