### ISSUE TITLE
[Event Request] for Table 172 (Standard Customer Sales Code, Function ApplyStdCodesToSalesLines, OnAfterApplyStdCodesToSalesLinesLoop

### ISSUE THREAD

**Issue by dojab** [Microsoft/ALAppExtensions#989]
Hi,
to manage businiss logik after after inserting the lines in function "ApplyStdCodesToSalesLines" a new event "OnAfterApplyStdCodesToSalesLinesLoop" would be perfect. In addition to this function we shoud have a similar event in the function"InsertSalesLines".
Best Regards

**Comment by AlexanderYakunin** [comment]
Please specify event parameters you need

**Comment by dojab** [comment]
I would suggest the same parameters as used in the event "OnBeforeApplyStdCodesToSalesLinesLoop":
![eventparameter](https://user-images.githubusercontent.com/47024592/52038898-7354ae00-2533-11e9-957a-a1f7b4b6622d.png)

**Comment by AJasp** [comment]
Please reopen this request - we need this event

**Comment by AlexanderYakunin** [comment]
This event already implemented:

![image](https://user-images.githubusercontent.com/31849120/53403659-1975c580-39c5-11e9-8b68-fb7d80f6ea01.png)
