### ISSUE TITLE
[Event Request] Table 7310 "Warehouse Journal Batch" - OnBeforeOnValidateLocationCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9890]
We are migrating our code from NAV 2018 to BC16.4. In the Table 7310 "Warehouse Journal Batch", in the trigger OnValidate of the field 7 "Location Code", we need to add a condition to the use of the Get and Testfield methods. To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/99654309-68497580-2a5a-11eb-8381-ad3b4434c772.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/99654250-5536a580-2a5a-11eb-9675-f3fc39902b70.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
