### ISSUE TITLE
[Event Request] Codeunit::"Item Subst." - Function GetCompSubst - OnGetCompSubstBeforeUpdateComponent

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9892]
We like to request the following Event:
Object: Codeunit::"Item Subst."
Function: GetCompSubst
Publisher Event: OnGetCompSubstBeforeUpdateComponent
Reason: 
Where is the event placed:
procedure GetCompSubst(var ProdOrderComp: Record "Prod. Order Component")
    begin
        ProdOrderCompSubst := ProdOrderComp;
        if not PrepareSubstList(
             ProdOrderComp."Item No.",
             ProdOrderComp."Variant Code",
             ProdOrderComp."Location Code",
             ProdOrderComp."Due Date",
             true)
        then
            ErrorMessage(ProdOrderComp."Item No.", ProdOrderComp."Variant Code");
        OnGetCompSubstBeforeUpdateComponent(ProdOrderComp, TempItemSubstitution, Item, GrossReq, SchedRcpt);
        TempItemSubstitution.Reset();
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnGetCompSubstBeforeUpdateComponent(var ProdOrderComp: Record "Prod. Order Component"; var TempItemSubstitution: Record "Item Substitution" temporary; var Item: Record Item; var GrossReq: Decimal; var SchedRcpt: Decimal)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
