### ISSUE TITLE
[Event Request] Codeunit::"Item Subst." - Function GetCompSubst - OnAfterGetCompSubst

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9893]
We like to request the following Event:
Object: Codeunit::"Item Subst."
Function: GetCompSubst
Publisher Event: OnAfterGetCompSubst
Reason: 
Where is the event placed:
        if PAGE.RunModal(PAGE::"Item Substitution Entries", TempItemSubstitution) = ACTION::LookupOK then
            UpdateComponent(ProdOrderComp, TempItemSubstitution."Substitute No.", TempItemSubstitution."Substitute Variant Code");
        OnAfterGetCompSubst (ProdOrderComp, TempItemSubstitution);
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterGetCompSubst (var ProdOrderComp: Record "Prod. Order Component"; var TempItemSubstitution: Record "Item Substitution" temporary)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
