### ISSUE TITLE
[Event Request] Table 36 'Sales Header' OnBeforeCreateInvtPutAwayPick

### ISSUE THREAD

**Issue by sukumar5893** [microsoft/ALAppExtensions#9894]
Hi Team,

In Table 36, Please provide the possibility to have **OnBeforeCreateInvtPutAwayPick** event in at the beginning of  **CreateInvtPutAwayPick** procedure.

**Event**
LOCAL [INTEGRATIONEVENT] OnBeforeCreateInvtPutAwayPick(Rec: Record “Sales Header”)

_If possible, please back port the same to BC14 also._

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
