### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function  - OnInsertCapValueEntryOnAfterInsertCapValueEntryRelation

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9895]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: InsertCapValueEntry
Publisher Event: OnInsertCapValueEntryOnAfterInsertCapValueEntryRelation
Reason: 
Where is the event placed:
InsertItemReg(0, 0, ValueEntry."Entry No.", 0);
            InsertPostValueEntryToGL(ValueEntry);
            if Item."Item Tracking Code" <> '' then begin
                TempValueEntryRelation.Init();
                TempValueEntryRelation."Value Entry No." := ValueEntry."Entry No.";
                TempValueEntryRelation.Insert();
            end;
            OnAfterInsertCapValueEntryRelation(ValueEntry, ItemJnlLine, TempValueEntryRelation); Event Code:
  [IntegrationEvent(false, false)]
    local procedure OnAfterInsertCapValueEntryRelation(var ValueEntry: Record "Value Entry"; ItemJnlLine: Record "Item Journal Line"; TempValueEntryRelation: Record "Value Entry Relation" temporary)
    begin
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
