### ISSUE TITLE
[Event Request] Database::Vendor - Function  - GetVendorNoOpenCard OnGetVendorNoOpenCardOnAfterVendorFilterFromStart

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9897]
We like to request the following Event:
Object: Database::Vendor
Function: GetVendorNoOpenCard
Publisher Event: OnGetVendorNoOpenCardOnAfterVendorFilterFromStart
Reason: To implement custom business logic
Where is the event placed:
VendorFilterFromStart := '''@' + VendorWithoutQuote + '*''';

        Vendor.FilterGroup := -1;
        Vendor.SetFilter("No.", VendorFilterFromStart);
        Vendor.SetFilter(Name, VendorFilterFromStart);

        OnGetVendorNoOpenCardOnAfterVendorFilterFromStart(Vendor);

        if Vendor.FindFirst then
            exit(Vendor."No.");
Event Code:

[IntegrationEvent(false, false)]
    local procedure OnGetVendorNoOpenCardOnAfterVendorFilterFromStart(var Vendor: Record Vendor)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
