### ISSUE TITLE
[Event Request] Database::Vendor – Function GetVendorNoOpenCard  - OnGetVendorNoOpenCardOnAfterSetVendorWithoutQuote

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9898]
We like to request the following Event:
Object: Database::Vendor
Function: GetVendorNoOpenCard
Publisher Event: OnGetVendorNoOpenCardOnAfterSetVendorWithoutQuote
Reason: To implement custom business logic
Where is the event placed:
VendorWithoutQuote := ConvertStr(VendorText, '''', '?');
        Vendor.SetFilter(Name, '''@' + VendorWithoutQuote + '''');
        OnGetVendorNoOpenCardOnAfterSetVendorWithoutQuote (Vendor);
        if Vendor.FindFirst then
            exit(Vendor."No.");
        Vendor.SetRange(Name);

        VendorFilterFromStart := '''@' + VendorWithoutQuote + '*''';
Event Code:

[IntegrationEvent(false, false)]
    local procedure OnGetVendorNoOpenCardOnAfterSetVendorWithoutQuote (var Vendor: Record Vendor)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
