### ISSUE TITLE
Codeunit 419 UploadFileSilent

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#99]
If you can use this function "UploadFileSilent" in an Extension (AL dont throw an Error)
Why isnt the function "DeleteServerFile" available?

So you can pump up the Server with Files, without the chance to delete them correctly

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
UploadFileSilent should never have been exposed for extension development. The use of files should be avoided in the cloud for safety and performance reasons. The [External] property was removed in the latest release.
