### ISSUE TITLE
[Event Request] Table 7311 "Warehouse Journal Line" - OnBeforeOnValidateQuantityCheckBinToBinCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9901]
We are migrating our code from NAV 2018 to BC16.4. In the Table 7311 "Warehouse Journal Line", in the trigger OnValidate of the field 10 "Quantity", we need to add a condition to the use of the CheckBin("Location Code", "To Bin Code", true) procedure. I've thought about using the event publisher at the beginning of the local procedure CheckBin, but if I do, my event subscriber would be called everytime CheckBin is used. I only want to add a condition in this specific call in the OnValidate trigger of the field 1 "Quantity". To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/99678238-e453b580-2a7a-11eb-881b-e1df00558338.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/99678023-aa82af00-2a7a-11eb-90e1-482968676646.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by RomanZanizdra** [comment]
Hi @Magicrevette. Is it ok for you to use event OnBeforeCheckBin with new parameter CurrFieldNo?

**Comment by Magicrevette** [comment]
Hi @RomanZanizdra . It would fit to my need perfectly. Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
