### ISSUE TITLE
[Event Request] Table 7311 "Warehouse Journal Line" - OnBeforeSetUpNewLineWhseJnlBatchGet

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#9903]
We are migrating our code from NAV 2018 to BC16.4. In the Table 7311 "Warehouse Journal Line", in the procedure SetUpNewLine, we need to add a condition to the use of the WhseJnlBatch.Get(). To do so, we need a IsHandled flag and an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/99793805-7b774680-2b29-11eb-9d23-b90393284418.png)

With this integration event :
![image](https://user-images.githubusercontent.com/34645582/99793747-64d0ef80-2b29-11eb-9738-ef451d039dcc.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
