### ISSUE TITLE
[Bug / Application Refactoring] COD 5802 PostInvtPostBufPerEntry

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/ALAppExtensions#9904]
Procedure PostInvtPostBufPerEntry in codeunit 5802 "Inventory Posting To G/L" has different number of parameters in BE localization compared to W1:
BE: procedure PostInvtPostBufPerEntry(var ValueEntry: Record "Value Entry"; JnlTemplName: Code[10]; JnlBatchName: Code[10])
W1: procedure PostInvtPostBufPerEntry(var ValueEntry: Record "Value Entry")
and this prevents having the same app compiled against different locations (similar to #2882).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
