### ISSUE TITLE
[ELSTER] Breaking Changes in version for 2021

### ISSUE THREAD

**Issue by sirhc101** [microsoft/ALAppExtensions#9905]
Today the ERiC (ELSTER Rich Client) version 33.2.8.0 has been released by german tax authorities. Based on the current roadmap the current version is maintained and valid until April 2021:
![image](https://user-images.githubusercontent.com/39621236/99800610-eda15880-2b34-11eb-8225-a83ba53b1007.png)

Unfortunately the german tax authorities introduced some breaking changes into the new release of ERiC which is also effecting the ELSTER app. The breaking change is introduced in Sales VAT Adv. Notification (UStVA):

> Wichtig: Wegen der Umstellung auf die neue Nutzdatenstruktur hat sich für die Datenarten UStVA und LStA 2021 der Aufbau des XML-Datensatzes im Vergleich zu den Vorjahren stärker geändert: <br>- Beim Element "Anmeldungssteuern" muss nun im Attribut "version" der Wert "2021" angegeben werden.<br>- Beim Element "Anmeldungssteuern" darf nun das Attribut "art" nicht mehr angegeben werden.<br>- Beim Element "Anmeldungssteuern" muss nun mit xmlns="http://finkonsens.de/elster/elsteranmeldung/lsta/v2021" bzw. xmlns="http://finkonsens.de/elster/elsteranmeldung/ustva/v2021" der XML-Namensraum angegeben werden.<br>- Das Element "Erstellungsdatum" ist vor dem Element "DatenLieferant" anzugeben.

This changes require modifications in [CreateXMLFileVATAdvNotif.Report.al](https://github.com/microsoft/ALAppExtensions/blob/master/Apps/DE/Elster/app/src/Reports/CreateXMLFileVATAdvNotif.Report.al).

Attached you find two example XML-files provided by the german tax authorities:
[UStVA-2020-2021.zip](https://github.com/microsoft/ALAppExtensions/files/5573507/UStVA-2020-2021.zip)

- UStVA_2020.xml is showing the current valid XML format. This is how the ELSTER app in BC is creating the XML file.
- UStVA_2021.xml is showing the new XML format.

**Comment by sirhc101** [comment]
See PR #9919

**Comment by sorenfriisalexandersen** [comment]
Hi @sirhc101 
Thank you for submitting this suggestion for code changes and for letting us know about this important change.
We are evaluating the suggestion. It could be that we end up with another way of supporting this Elster change, but will let you know as soon as we have decided. In any case, thank you very much - and please stand by for clarification if needed.

Thanks
Best regards
Søren Alexandersen, Program Manager, Business Central Localization

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
