### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforeDeleteEvent

### ISSUE THREAD

**Issue by SweconThomasH** [microsoft/ALAppExtensions#9908]
BC17.1: Can we please have the "IsHandled" parameter in the OnBeforeDeleteEvent of table 38 "Purchase Header"? We have special logic where it is necessary to skip the whole OnDelete logic for temporary tables.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
