### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt."  FillExactCostRevLink

### ISSUE THREAD

**Issue by sybrenwille** [microsoft/ALAppExtensions#9910]
Hi Team,

To control boolean 'FillExactCostRevLink' in codeunit 6620 I would like the addition of two new events:

**Function IsPurchFillExactCostRevLink**
Start the function with the following:

```
OnBeforeIsPurchFillExactCostRevLink(ToPurchHeader, FromDocType, CurrencyCode, IsHandled, FillExactCost);
IF IsHandled THEN
  EXIT(FillExactCost);
```
_Event publisher:_

```
    [Integration]
    LOCAL PROCEDURE OnBeforeIsPurchFillExactCostRevLink@11169000(ToPurchHeader@1000 : Record 38;FromDocType@1001 : 'Purchase Receipt,Purchase Invoice,Purchase Return Shipment,Purchase Credit Memo';CurrencyCode@1002 : Code[10];VAR IsHandled@11169002 : Boolean;VAR FillExactCost@11169000 : Boolean);
    BEGIN
    END;
```

This allows us to control the outcome of this function in any desired way.
The same applies for Sales:

**Function IsSalesFillExactCostRevLink**
Start the function with the following:
```
OnBeforeIsSalesFillExactCostRevLink(ToSalesHeader, FromDocType, CurrencyCode, IsHandled, FillExactCost);
IF IsHandled THEN
  EXIT(FillExactCost);
```
_Event Publisher:_

```
    [Integration]
    LOCAL PROCEDURE OnBeforeIsSalesFillExactCostRevLink@11169002(ToSalesHeader@11169004 : Record 36;FromDocType@11169003 : 'Sales Shipment,Sales Invoice,Sales Return Receipt,Sales Credit Memo';CurrencyCode@11169001 : Code[10];VAR IsHandled@11169002 : Boolean;VAR FillExactCost@11169000 : Boolean);
    BEGIN
    END;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
