### ISSUE TITLE
[Event Request] Table Contact, Procedure CreateSalesQuoteFromContact

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#9916]
Hi,
we would like to request a event change or alternatively an additional event in the procedure CreateSalesQuoteFromContact.  

The current code looks like this (17.1)
![image](https://user-images.githubusercontent.com/47414309/99809245-49261300-2b42-11eb-9324-97637a0de1a8.png)
We want to use the existing event OnBeforeCreateSalesQuoteFromContact to transfer some additional information from the Contact to the Sales Header, so this event seems to be perfect.

A few lines later the line _SalesHeader.Init();_ clear all values that my the event subscriber had preset (except the primary key fields). In my Scenario, it is important to define the values before the SalesHeader is inserted. Therefore i can provide three solutions: 

1. Suggestion
Delete the line "SalesHeader.Init(), because this line is not neccessary (SalesHeader is local)
2. Suggestion 
Move the **_"SalesHeader.Init()"_** line before calling the existing event _**"OnBeforeCreateSalesQuoteFromContact(Rec, SalesHeader);"**_  
3. Suggestion
New Event OnBeforeInsertSalesQuote(Rec, SalesHeader) - please define both paramter as  **_Var_** 

I prefer the first suggestion.

Many thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
