### ISSUE TITLE
[Event Request] Codeunit 5944 "SignServContractDoc" CreateServiceLinesLedgerEntries

### ISSUE THREAD

**Issue by sybrenwille** [microsoft/ALAppExtensions#9918]
Hi Team,

To have more influence in outcome of function CreateServiceLinesLedgerEntries from Codeunit 5944, the following event would be really usefull:

**Function CreateServiceLinesLedgerEntries**

Add the end of the function:
`OnAfterCreateServiceLinesLedgerEntries(ServHeader,ServContractHeader); `

_Event Publisher:_
```
   [Integration]
    LOCAL PROCEDURE OnAfterCreateServiceLinesLedgerEntries@11169000(VAR ServiceHeader@11169000 : Record 5900;ServiceContractHeader@11169001 : Record 5965);
    BEGIN
    END;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
