### ISSUE TITLE
[Event Request] Codeunit 7008 "Price Calculation Buffer Mgt." - OnAfterSetLineDiscountPctForPickBestLine

### ISSUE THREAD

**Issue by mhoury** [microsoft/ALAppExtensions#9923]
Could we please have a new published event _OnAfterSetLineDiscountPctForPickBestLine_ in Codeunit 7008 "Price Calculation Buffer Mgt.", function "SetLineDiscountPctForPickBestLine"?

    procedure SetLineDiscountPctForPickBestLine(var PriceListLine: Record "Price List Line")
    begin
        if PriceCalculationBuffer."Allow Line Disc." and PriceListLine."Allow Line Disc." then
            PriceListLine."Line Discount %" := PriceCalculationBuffer."Line Discount %"
        else
            PriceListLine."Line Discount %" := 0;

    + OnAfterSetLineDiscountPctForPickBestLine(PriceCalculationBuffer, PriceListLine);
    end;

with the new event published as follows:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetLineDiscountPctForPickBestLine(PriceCalculationBuffer: Record "Price Calculation Buffer"; var PriceListLine: Record "Price List Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
