### ISSUE TITLE
[Event Request] Codeunit 7008 "Price Calculation Buffer Mgt." - OnAfterGetAssets

### ISSUE THREAD

**Issue by mhoury** [microsoft/ALAppExtensions#9925]
Could we please have a new published event _OnAfterGetAssets_ in Codeunit 7008 "Price Calculation Buffer Mgt.", function _GetAssets(var NewPriceAssetList: Codeunit "Price Asset List")_ ?

    procedure GetAssets(var NewPriceAssetList: Codeunit "Price Asset List")
    begin
        NewPriceAssetList.Copy(PriceAssetList);
    +   OnAfterGetAssets(PriceCalculationBuffer, NewPriceAssetList);
    end

with the new event published as follows:

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetAssets(PriceCalculationBuffer: Record "Price Calculation Buffer"; var NewPriceAssetList: Codeunit "Price Asset List")
    begin
    end;

**Comment by mhoury** [comment]
Hello @AlexanderYakunin ,
first time actually posting an issue. To your knowledge, is there anything missing in the request that I need to do for it to be considered by the BC team?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
