### ISSUE TITLE
[Event Request] Database::"Item Journal Line" - Function RecalculateUnitAmount - OnRecalculateUnitAmountOnAfterGetQtyperUnitMeasure

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9927]
We like to request the following Event:
Object: Database::"Item Journal Line"
Function: RecalculateUnitAmount
Publisher Event: OnRecalculateUnitAmountOnAfterGetQtyperUnitMeasure
Reason: To implement custom business logic
Where is the event placed:
procedure RecalculateUnitAmount()
    var
        ItemJnlLine1: Record "Item Journal Line";
        PriceType: Enum "Price Type";
    begin
        GetItem;
        if ("Value Entry Type" <> "Value Entry Type"::"Direct Cost") or
           ("Item Charge No." <> '')
        then begin
            "Indirect Cost %" := 0;
            "Overhead Rate" := 0;
        end else begin
            "Indirect Cost %" := Item."Indirect Cost %";
            "Overhead Rate" := Item."Overhead Rate";
        end;
        "Qty. per Unit of Measure" := UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code");
        OnRecalculateUnitAmountOnAfterGetQtyperUnitMeasure(Rec, xRec);
        GetUnitAmount(FieldNo("Unit of Measure Code"));
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnRecalculateUnitAmountOnAfterGetQtyperUnitMeasure(var ItemJournalLine: Record "Item Journal Line"; xItemJournalLine: Record "Item Journal Line");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
