### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Bin Code" - OnValidate - OnValidateBinCodeOnBeforeDropShipmentError

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9928]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Bin Code" - OnValidate
Publisher Event: OnValidateBinCodeOnBeforeDropShipmentError
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
                OnValidateBinCodeOnBeforeDropShipmentError(Rec, IsHandled);
                if not IsHandled then
                    if "Drop Shipment" then
                        Error(
                          Text001,
                          FieldCaption("Bin Code"), "Sales Order No.");
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateBinCodeOnBeforeDropShipmentError(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
