### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Order Date" - OnValidate - OnValidateOrderDateOnBeforeMessageOrderDate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9929]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Order Date" - OnValidate
Publisher Event: OnValidateOrderDateOnBeforeMessageOrderDate
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
                IsHandled: Boolean;
            begin
                TestStatusOpen;
                if (CurrFieldNo <> 0) and
                   ("Document Type" = "Document Type"::Order) and
                   ("Order Date" < WorkDate) and
                   ("Order Date" <> 0D)
                then begin
                    IsHandled := false;
                    OnValidateOrderDateOnBeforeMessageOrderDate(Rec, IsHandled);
                    if not IsHandled then
                        Message(
                          Text018,
                          FieldCaption("Order Date"), "Order Date", WorkDate);
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateOrderDateOnBeforeMessageOrderDate(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
