### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Qty. to Receive" - OnValidate - OnValidateQtyToReceiveOnBeforeInitQtyToInvoice

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9930]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Qty. to Receive" - OnValidate
Publisher Event: OnValidateQtyToReceiveOnBeforeInitQtyToInvoice
Reason: To implement custom business logic
Where is the event placed:
OnValidateQtyToReceiveOnAfterCheck(Rec, CurrFieldNo);
                if "Qty. to Receive" = Quantity - "Quantity Received" then begin
                    IsHandled := false;
                    OnValidateQtyToReceiveOnBeforeInitQtyToReceive(Rec, CurrFieldNo, IsHandled);
                    if not IsHandled then
                        InitQtyToReceive;
                end else begin
                    "Qty. to Receive (Base)" :=
                        UOMMgt.CalcBaseQty(Rec, "Qty. to Receive");
                    OnValidateQtyToReceiveOnBeforeInitQtyToInvoice(Rec, CurrFieldNo);
                    InitQtyToInvoice;
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQtyToReceiveOnBeforeInitQtyToInvoice(var PurchaseLine: Record "Purchase Line"; CurrFieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
