### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Qty. to Receive" - OnValidate - OnValidateQtyToReceiveOnBeforeVerifyPurchLineChange

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9931]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Qty. to Receive" - OnValidate
Publisher Event: OnValidateQtyToReceiveOnBeforeVerifyPurchLineChange
Reason: To implement custom business logic
Where is the event placed:
trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                GetLocation("Location Code");
                IsHandled := false;
                OnValidateQtyToReceiveOnBeforeCheck(Rec, IsHandled);
                if not IsHandled then
                    if (CurrFieldNo <> 0) and (Type = Type::Item) and (not "Drop Shipment") then begin
                        if Location."Require Receive" and ("Qty. to Receive" <> 0) then
                            CheckWarehouse;
                        IsHandled := false;
                        OnValidateQtyToReceiveOnBeforeVerifyPurchLineChange(Rec, xRec, IsHandled);
                        if not IsHandled then
                            WhseValidateSourceLine.PurchaseLineVerifyChange(Rec, xRec);
                    end;
                OnValidateQtyToReceiveOnAfterCheck(Rec, CurrFieldNo);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQtyToReceiveOnBeforeVerifyPurchLineChange(var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
