### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Unit of Measure Code" -OnValidate - OnValidateUnitOfMeasureCodeOnBeforeAssignItemUOM

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9932]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Unit of Measure Code" -OnValidate
Publisher Event: OnValidateUnitOfMeasureCodeOnBeforeAssignItemUOM
Reason: To implement custom business logic
Where is the event placed:
if "Prod. Order No." = '' then
                    case Type of
                        Type::Item:
                            begin
                                GetItem(Item);
                                IsHandled := false;
                                OnValidateUnitOfMeasureCodeOnBeforeAssignItemUOM(Rec, Item, CurrfieldNo, IsHandled);
                                if not IsHandled then begin
                                    "Qty. per Unit of Measure" := UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code");
                                    "Gross Weight" := Item."Gross Weight" * "Qty. per Unit of Measure";
                                    "Net Weight" := Item."Net Weight" * "Qty. per Unit of Measure";
                                    "Unit Volume" := Item."Unit Volume" * "Qty. per Unit of Measure";
                                    "Units per Parcel" := Round(Item."Units per Parcel" / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                                end;
                                OnAfterAssignItemUOM(Rec, Item, CurrFieldNo);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateUnitOfMeasureCodeOnBeforeAssignItemUOM(var PurchaseLine: Record "Purchase Line"; Item: Record Item; CurrfieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
