### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Unit Cost (LCY)" - OnValidate - OnValidateUnitCostLCYOnBeforeUpdateSalesCost

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9933]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Unit Cost (LCY)" - OnValidate
Publisher Event: OnValidateUnitCostLCYOnBeforeUpdateSalesCost
Reason: To implement custom business logic
Where is the event placed:
"Indirect Cost %" := 0;
                if ("Direct Unit Cost" <> 0) and
                   ("Direct Unit Cost" <> ("Line Discount Amount" / Quantity))
                then begin
                    IndirectCostPercent :=
                      Round(
                        (UnitCostCurrency - "Direct Unit Cost" + "Line Discount Amount" / Quantity) /
                        ("Direct Unit Cost" - "Line Discount Amount" / Quantity) * 100, 0.00001);
                    if IndirectCostPercent >= 0 then
                        "Indirect Cost %" := IndirectCostPercent;
                end;
                OnValidateUnitCostLCYOnBeforeUpdateSalesCost(Rec);
                UpdateSalesCost;
                if JobTaskIsSet then begin
                    CreateTempJobJnlLine(false);
                    TempJobJnlLine.Validate("Unit Cost (LCY)", "Unit Cost (LCY)");
                    UpdateJobPrices;
                end
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateUnitCostLCYOnBeforeUpdateSalesCost(var PurchaseLine: Record "Purchase Line")
    begin
    end;

**Comment by StanPesotskiy** [comment]
Existent event OnValidateUnitCostLCYOnBeforeUpdateSalesCost could be used
