### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function "Variant Code" - OnValidate - OnValidateVariantCodeOnAfterUpdateItemReference

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9934]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: "Variant Code" - OnValidate
Publisher Event: OnValidateVariantCodeOnAfterUpdateItemReference
Reason: To implement custom business logic
Where is the event placed:
UpdateLeadTimeFields;
                UpdateDates;
                GetDefaultBin;
                if Type = Type::Item then
                    UpdateItemReference;
                OnValidateVariantCodeOnAfterUpdateItemReference(Rec, CurrFieldNo);
                if JobTaskIsSet then begin
                    CreateTempJobJnlLine(true);
                    UpdateJobPrices;
                end;
                UpdateDirectUnitCostByField(FieldNo("Variant Code"));
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateVariantCodeOnAfterUpdateItemReference(var PurchaseLine: Record "Purchase Line"; CurrfieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
