### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function CheckWarehouse() - OnValidateVariantCodeOnAfterUpdateItemReference

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9935]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: local procedure CheckWarehouse()
Publisher Event: OnValidateVariantCodeOnAfterUpdateItemReference
Reason:  To   implement custom business logic
Where is the event placed:
else begin
                    DialogText := Text034;
                    DialogText :=
                      DialogText + Location2.GetRequirementText(Location2.FieldNo("Require Pick"));
                end;
            end;
        end;
        OnCheckWarehouseOnBeforeShowDialog(Rec, Location2, ShowDialog, DialogText);
        case ShowDialog of
            ShowDialog::Message:
                Message(WhseRequirementMsg, DialogText);
            ShowDialog::Error:
                Error(Text016, DialogText, FieldCaption("Line No."), "Line No.")
        end;
Event Code:

    [IntegrationEvent(false, false)]
    local procedure OnCheckWarehouseOnBeforeShowDialog(PurchaseLine: Record "Purchase Line"; Location: Record Location; ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
