### ISSUE TITLE
[Change Request] Sales Header - function CopyShipToCustomerAddressFieldsFromCust

### ISSUE THREAD

**Issue by robinfjelldal** [microsoft/ALAppExtensions#9936]
Could we get the function/procedure CopyShipToCustomerAddressFieldsFromCust to be global?

```
    //local procedure CopyShipToCustomerAddressFieldsFromCust(var SellToCustomer: Record Customer)
     procedure CopyShipToCustomerAddressFieldsFromCust(var SellToCustomer: Record Customer)
```

Thank you,

best regards,
Robin Fjelldal

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
