### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function Quantity - OnValidate - OnValidateQuantityOnBeforeInitOutstanding

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9937]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: Quantity - OnValidate
Publisher Event: OnValidateQuantityOnBeforeInitOutstanding
Reason: To implement custom business logic
Where is the event placed:
if (Type = Type::"Charge (Item)") and (CurrFieldNo <> 0) then begin
                    if (Quantity = 0) and ("Qty. to Assign" <> 0) then
                        FieldError("Qty. to Assign", StrSubstNo(Text011, FieldCaption(Quantity), Quantity));
                    if (Quantity * "Qty. Assigned" < 0) or (Abs(Quantity) < Abs("Qty. Assigned")) then
                        FieldError(Quantity, StrSubstNo(Text004, FieldCaption("Qty. Assigned")));
                end;
                if "Receipt No." <> '' then
                    CheckReceiptRelation
                else
                    if "Return Shipment No." <> '' then
                        CheckRetShptRelation;
                DoInitOutstanding := (xRec.Quantity <> Quantity) or (xRec."Quantity (Base)" <> "Quantity (Base)") or ("No." = xRec."No.");
                OnValidateQuantityOnBeforeInitOutstanding(Rec, xRec, CurrFieldNo, DoInitOutstanding);
                if DoInitOutstanding then begin
                    InitOutstanding;
                    if IsCreditDocType then
                        InitQtyToShip
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnBeforeInitOutstanding(var PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line"; CurrFieldNo: Integer; var DoInitOutstanding: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
