### ISSUE TITLE
[Event Request] Database::"Purchase Line" - Function UpdateSalesCost - OnUpdateSalesCostOnBeforeGetSalesOrderLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9938]
We like to request the following Event:
Object: Database::"Purchase Line"
Function: UpdateSalesCost
Publisher Event: OnUpdateSalesCostOnBeforeGetSalesOrderLine
Reason: To implement custom business logic
Where is the event placed:
local procedure UpdateSalesCost()
    var
        SalesOrderLine: Record "Sales Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnUpdateSalesCostOnBeforeGetSalesOrderLine(Rec, SalesOrderLine, IsHandled);
        if not IsHandled then
            case true of
                "Sales Order Line No." <> 0:
                    // Drop Shipment
                    SalesOrderLine.Get(SalesOrderLine."Document Type"::Order, "Sales Order No.", "Sales Order Line No.");
                "Special Order Sales Line No." <> 0:
                    // Special Order
                    begin
                        if not
                           SalesOrderLine.Get(SalesOrderLine."Document Type"::Order, "Special Order Sales No.", "Special Order Sales Line No.")
                        then
                            exit;
                    end;
                else
                    exit;
            end;
	end;

        IsHandled := false;
        OnBeforeUpdateSalesCost(Rec, SalesOrderLine, IsHandled);
        if IsHandled then
            exit;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnUpdateSalesCostOnBeforeGetSalesOrderLine(var PurchaseLine: Record "Purchase Line"; var SalesOrderLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
