### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function "Posting Date" - OnValidate - OnValidatePostingDateOnBeforeCheckCurrencyCode

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9939]
We like to request the following Event:
Object: Database::"Sales Header"
Function: "Posting Date" - OnValidate
Publisher Event: OnValidatePostingDateOnBeforeCheckCurrencyCode
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
                OnValidatePostingDateOnBeforeCheckCurrencyCode(Rec, Confirmed, IsHandled);
                if not IsHandled then
                    if "Currency Code" <> '' then begin
                        UpdateCurrencyFactor;
                        if "Currency Factor" <> xRec."Currency Factor" then
                            ConfirmUpdateCurrencyFactor;
                    end;
                if "Posting Date" <> xRec."Posting Date" then
                    if DeferralHeadersExist then
                        ConfirmUpdateDeferralDate;
                SynchronizeAsmHeader;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidatePostingDateOnBeforeCheckCurrencyCode(var SalesHeader: Record "Sales Header"; var Confirmed: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
