### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function "Ship-to Code" - OmVaildate - OnValidateShipToCodeOnBeforeCopyShipToAddress

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9940]
We like to request the following Event:
Object: Database::"Sales Header"
Function: "Ship-to Code" - OmVaildate
Publisher Event: OnValidateShipToCodeOnBeforeCopyShipToAddress
Reason: To implement custom business logic
Where is the event placed:
DoCopyShipToAddress := not IsCreditDocType;
                OnValidateShipToCodeOnBeforeCopyShipToAddress(Rec, xRec, DoCopyShipToAddress);
                if DoCopyShipToAddress then
                    if not IsCreditDocType then
                        if "Ship-to Code" <> '' then begin
                            if xRec."Ship-to Code" <> '' then begin
                                GetCust("Sell-to Customer No.");
                                if Cust."Location Code" <> '' then
                                    Validate("Location Code", Cust."Location Code");
                                "Tax Area Code" := Cust."Tax Area Code";
                            end;
                            ShipToAddr.Get("Sell-to Customer No.", "Ship-to Code");
                            SetShipToCustomerAddressFieldsFromShipToAddr(ShipToAddr);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateShipToCodeOnBeforeCopyShipToAddress(var SalesHeader: Record "Sales Header"; var xSalesHeader: Record "Sales Header"; var DoCopyShipToAddress: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
