### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function CreateSalesLine - OnCreateSalesLineOnBeforeValidateQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9941]
We like to request the following Event:
Object: Database::"Sales Header"
Function: CreateSalesLine
Publisher Event: OnCreateSalesLineOnBeforeValidateQuantity
Reason: To implement custom business logic
Where is the event placed:
end else begin
            SalesLine.Validate("No.", TempSalesLine."No.");
            if SalesLine.Type <> SalesLine.Type::" " then begin
                SalesLine.Validate("Unit of Measure Code", TempSalesLine."Unit of Measure Code");
                SalesLine.Validate("Variant Code", TempSalesLine."Variant Code");
                OnCreateSalesLineOnBeforeValidateQuantity(SalesLine, TempSalesLine);
                if TempSalesLine.Quantity <> 0 then begin
                    SalesLine.Validate(Quantity, TempSalesLine.Quantity);
                    SalesLine.Validate("Qty. to Assemble to Order", TempSalesLine."Qty. to Assemble to Order");
                end;
                SalesLine."Purchase Order No." := TempSalesLine."Purchase Order No.";
                SalesLine."Purch. Order Line No." := TempSalesLine."Purch. Order Line No.";
                SalesLine."Drop Shipment" := SalesLine."Purch. Order Line No." <> 0;
            end;
            SalesLine.Validate("Shipment Date", TempSalesLine."Shipment Date");
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCreateSalesLineOnBeforeValidateQuantity(var SalesLine: Record "Sales Line"; var TempSalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
