### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function "Qty. to Ship" - OnValidate - OnValidateQtyToShipOnBeforeUpdateQtyToAsm

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9942]
We like to request the following Event:
Object: Database::"Sales Line"
Function: "Qty. to Ship" - OnValidate
Publisher Event: OnValidateQtyToShipOnBeforeUpdateQtyToAsm
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
                OnValidateQtyToShipAfterInitQty(Rec, xRec, CurrFieldNo, IsHandled);
                if not IsHandled then begin
                    if ((("Qty. to Ship" < 0) xor (Quantity < 0)) and (Quantity <> 0) and ("Qty. to Ship" <> 0)) or
                       (Abs("Qty. to Ship") > Abs("Outstanding Quantity")) or
                       (((Quantity < 0) xor ("Outstanding Quantity" < 0)) and (Quantity <> 0) and ("Outstanding Quantity" <> 0))
                    then
                        Error(Text007, "Outstanding Quantity");
                    if ((("Qty. to Ship (Base)" < 0) xor ("Quantity (Base)" < 0)) and ("Qty. to Ship (Base)" <> 0) and ("Quantity (Base)" <> 0)) or
                       (Abs("Qty. to Ship (Base)") > Abs("Outstanding Qty. (Base)")) or
                       ((("Quantity (Base)" < 0) xor ("Outstanding Qty. (Base)" < 0)) and ("Quantity (Base)" <> 0) and ("Outstanding Qty. (Base)" <> 0))
                    then
                        Error(Text008, "Outstanding Qty. (Base)");
                end;
                if (CurrFieldNo <> 0) and (Type = Type::Item) and ("Qty. to Ship" < 0) then
                    CheckApplFromItemLedgEntry(ItemLedgEntry);
                IsHandled := false;
                OnValidateQtyToShipOnBeforeUpdateQtyToAsm(Rec, IsHandled);
                if not IsHandled then
                    ATOLink.UpdateQtyToAsmFromSalesLine(Rec);
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQtyToShipOnBeforeUpdateQtyToAsm(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
