### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function CheckWarehouse - OnCheckWarehouseOnAfterSetLocation2

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9943]
We like to request the following Event:
Object: Database::"Sales Line"
Function: CheckWarehouse
Publisher Event: OnCheckWarehouseOnAfterSetLocation2
Reason: To implement custom business logic
Where is the event placed:
GetLocation("Location Code");
        if "Location Code" = '' then begin
            WhseSetup.Get();
            Location2."Require Shipment" := WhseSetup."Require Shipment";
            Location2."Require Pick" := WhseSetup."Require Pick";
            Location2."Require Receive" := WhseSetup."Require Receive";
            Location2."Require Put-away" := WhseSetup."Require Put-away";
        end else
            Location2 := Location;
        OnCheckWarehouseOnAfterSetLocation2(Location2);
        DialogText := Text035;
        if ("Document Type" in ["Document Type"::Order, "Document Type"::"Return Order"]) and
           Location2."Directed Put-away and Pick"
        then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCheckWarehouseOnAfterSetLocation2(var Location2: Record Location)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
