### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function InitHeaderDefaults - OnInitHeaderDefaultsOnBeforeSetLocationCode

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9944]
We like to request the following Event:
Object: Database::"Sales Line"
Function: InitHeaderDefaults
Publisher Event: OnInitHeaderDefaultsOnBeforeSetLocationCode
Reason: To implement custom business logic
Where is the event placed:
"Sell-to Customer No." := SalesHeader."Sell-to Customer No.";
        "Currency Code" := SalesHeader."Currency Code";
        IsHandled := false;
        OnInitHeaderDefaultsOnBeforeSetLocationCode(Rec, IsHandled);
        if not IsHandled then
            if not IsNonInventoriableItem then
                "Location Code" := SalesHeader."Location Code";
        "Customer Price Group" := SalesHeader."Customer Price Group";
        "Customer Disc. Group" := SalesHeader."Customer Disc. Group";
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnInitHeaderDefaultsOnBeforeSetLocationCode(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
