### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function Quantity - OnValidate - OnValidateQuantityOnBeforeInitOutstanding

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9946]
We like to request the following Event:
Object: Database::"Sales Line"
Function: Quantity - OnValidate
Publisher Event: OnValidateQuantityOnBeforeInitOutstanding
Reason: To implement custom business logic
Where is the event placed:
OnValidateQuantityOnBeforeCheckReceiptOrderStatus(Rec, StatusCheckSuspended, IsHandled);
                if not IsHandled then
                    AddOnIntegrMgt.CheckReceiptOrderStatus(Rec);
                DoInitOutstanding := (xRec.Quantity <> Quantity) or (xRec."Quantity (Base)" <> "Quantity (Base)");
                OnValidateQuantityOnBeforeInitOutstanding(Rec, xRec, CurrFieldNo, DoInitOutstanding);
                if DoInitOutstanding then begin
                    InitOutstanding();
                    if IsCreditDocType() then
                        InitQtyToReceive()
                    else
                        InitQtyToShip();
                    InitQtyToAsm();
                    SetDefaultQuantity();
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnBeforeInitOutstanding(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CurrFieldNo: Integer; var DoInitOutstanding: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
