### ISSUE TITLE
[Event Request] Database::"Sales Line" - Function ShowNonstock - OnShowNonstockOnBeforeValidateUnitPrice

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#9947]
We like to request the following Event:
Object: Database::"Sales Line"
Function: ShowNonstock
Publisher Event: OnShowNonstockOnBeforeValidateUnitPrice
Reason: To implement custom business logic
Where is the event placed:
procedure ShowNonstock()
    var
        TempItemTemplate: Record "Item Template" temporary;
        IsHandled: Boolean;
    begin
        TestField(Type, Type::Item);
        if "No." <> '' then
            Error(SelectNonstockItemErr);
        if PAGE.RunModal(PAGE::"Catalog Item List", NonstockItem) = ACTION::LookupOK then begin
            NonstockItem.TestField("Item Template Code");
            ConfigTemplateHeader.SetRange(Code, NonstockItem."Item Template Code");
            ConfigTemplateHeader.FindFirst();
            TempItemTemplate.InitializeTempRecordFromConfigTemplate(TempItemTemplate, ConfigTemplateHeader);
            TempItemTemplate.TestField("Gen. Prod. Posting Group");
            TempItemTemplate.TestField("Inventory Posting Group");
            "No." := NonstockItem."Entry No.";
            CatalogItemMgt.NonStockSales(Rec);
            Validate("No.", "No.");
            IsHandled := false;
            OnShowNonstockOnBeforeValidateUnitPrice(Rec, NonstockItem, IsHandled);
            if not IsHandled then
                Validate("Unit Price", NonstockItem."Unit Price");
            OnAfterShowNonStock(Rec, NonstockItem);
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnShowNonstockOnBeforeValidateUnitPrice(var SalesLine: Record "Sales Line"; NonstockItem: Record "Nonstock Item"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
