### ISSUE TITLE
[Enum Request] Table 5062 Attachment Field 3 "Storage Type"

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9948]
Can you convert Field 3 from the Attachment Table 5062 to an Enum?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
