### ISSUE TITLE
[Even Request] Table 5062 Attachment ExportAttachmentToServerFile / ImportAttachmentFromServerFile

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9949]
Can you add events to the function ExportAttachmentToServerFile and ImportAttachmentFromServerFile

Maybe add before Events with a handled option? We want to add our own Storage Type (https://github.com/microsoft/ALAppExtensions/issues/9948) so we want to be able to control the way a file is exported/imported.

ExportAttachmentToServerFile(VAR ExportToFile : Text) : Boolean
_IsHandled := FALSE;
OnBeforeExportAttachmentToServerFile(Rec,ExportFile,IsHandled);
IF IsHandled THEN
  EXIT(TRUE);_
 

ImportAttachmentFromServerFile(VAR ExportToFile : Text) : Boolean
_IsHandled := FALSE;
OnBeforeImportAttachmentFromServerFile(Rec,ExportFile,IsHandled);
IF IsHandled THEN
  EXIT(TRUE);_
 
_OnBeforeExportAttachmentToServerFile(Rec : Record Attachment;ExportToFile : Text,Var IsHandeled: Boolean)
OnBeforeImportAttachmentFromServerFile(Var Rec : Record Attachment;ExportToFile : Text,Var IsHandeled: Boolean)_

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
