### ISSUE TITLE
[Event Request] Table 11401 "CBG Statement Line" in function CreateGenJournalLine

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9950]
Please add a OnAfterCreateGenJournalLine event in the function CreateGenJournalLine

procedure CreateGenJournalLine(var GenJnlLine: Record "Gen. Journal Line")
    var
        CBGStatement: Record "CBG Statement";
    begin
        TestField("Account No.");
        ...
        ...

    if GenJnlLine."VAT Calculation Type" <> GenJnlLine."VAT Calculation Type"::"Full VAT" then
            if ("Debit VAT" <> 0) and ("Debit VAT" <> GenJnlLine."VAT Amount") then
                GenJnlLine.Validate("VAT Amount", "Debit VAT")
            else
                if ("Credit VAT" <> 0) and (-"Credit VAT" <> GenJnlLine."VAT Amount") then
                    GenJnlLine.Validate("VAT Amount", -"Credit VAT");

  **OnAfterCreateGenJournalLine(GenJnlLine,Rec)**
end;

**[IntegrationEvent(false, false)]
local procedure OnAfterCreateGenJournalLine(var GenJnlLine: Record "Gen. Journal Line"; CBGStatementLine: Record "CBG Statement Line");
begin
end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
