### ISSUE TITLE
[Scope Change] Table 5992 and Table 5994, procedure SendRecords()

### ISSUE THREAD

**Issue by supercruel** [microsoft/ALAppExtensions#9951]
Would it be possible that you removed the [Scope('OnPrem')] from the SendRecords() procedure in table 5992 "Service Invoice Header" table  and 5994 "Service Cr.Memo Header"?
We need to call this function for sales and service documents. We currently only have access to the sales functions.
So sales is fine but for service it is not possible cause of the Scope.
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
