### ISSUE TITLE
Add parameter to OnInsertItemJournalLineOnBeforeInsert in report 7391 "Whse. Get Bin Content"

### ISSUE THREAD

**Issue by Joriek** [microsoft/ALAppExtensions#9952]
Hello

Can you add the "Bin Content" parameter to the 
InsertItemJournalLineOnBeforeInsert(var ItemJournalLine: Record "Item Journal Line") 
and 
OnAfterInsertItemJnlLine(var ItemJournalLine: Record "Item Journal Line")
event publishers in report 7391 "Whse. Get Bin Content".

Thank you in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
