### ISSUE TITLE
How to apply trigger when you have two dataitem

### ISSUE THREAD

**Issue by coderxvg** [microsoft/ALAppExtensions#9959]
I am creating a report and wanna apply OnAfterRecord() trigger on my first data item customer  , but  i am getting syntax error after applying trigger. What is the way to apply the trigger on my first data item Customer
![MicrosoftTeams-image](https://user-images.githubusercontent.com/51020514/100079015-31180180-2e6a-11eb-91df-ba0c43fd6602.png)

.

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
