### ISSUE TITLE
[extensibility-enhancement] Remove Local from function UpdateSegLinesByFieldNo in table 5076 "Segment Header"

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#9960]
Hi,

Can you remove the local property from the function UpdateSegLinesByFieldNo. I want to use the function in my tableextension for my own fields.

Old:
**local procedure UpdateSegLinesByFieldNo(ChangedFieldNo: Integer; AskQuestion: Boolean)**

New:
**procedure UpdateSegLinesByFieldNo(ChangedFieldNo: Integer; AskQuestion: Boolean)**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
