### ISSUE TITLE
[Event Request] Codeunit 1720 - Deferral Utilities - OnCalculateStraightlineOnBeforeInsertDeferralLine

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#9984]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnCalculateStraightlineOnBeforeInsertDeferralLine` to be added to Codeunit 1720 Deferral Utilities with the following signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnCalculateStraightlineOnBeforeInsertDeferralLine(var DeferralLine: Record "Deferral Line"; DeferralHeader: Record "Deferral Header")
    begin
    end;
```
with **VAR** parameter `DeferralLine`.

which would be called as follows from `CalculateStraightline`:
```pascal
            ...
            PerDiffSum := PerDiffSum + Round(AmountToDefer / DeferralHeader."No. of Periods", AmountRoundingPrecision);

            DeferralLine.Amount := AmountToDefer;

            OnCalculateStraightlineOnBeforeInsertDeferralLine(DeferralLine, DeferralHeader); // << CALL TO NEW EVENT
            DeferralLine.Insert();
        end;
```

Could you also add the same event for procedures `CalculateEqualPerPeriod`, `CalculateDaysPerPeriod` and `CalculateUserDefined`?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
