### ISSUE TITLE
[Event Request] Table 1003 - Job Planning Line - OnAfterGetRemainingQty

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#9990]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterGetRemainingQty` to be added to Table 1003 Job Planning Line with the following signature:
```
procedure OnAfterGetRemainingQty(JobPlanningLine: Record "Job Planning Line"; var RemainingQty: Decimal; var RemainingQtyBase: Decimal)
```
with **VAR** parameters `RemainingQty` and `RemainingQtyBase`

which would be called as follows from `GetRemainingQty`:
```pascal
    procedure GetRemainingQty(var RemainingQty: Decimal; var RemainingQtyBase: Decimal)
    begin
        CalcFields("Reserved Quantity", "Reserved Qty. (Base)");
        RemainingQty := "Remaining Qty." - Abs("Reserved Quantity");
        RemainingQtyBase := "Remaining Qty. (Base)" - Abs("Reserved Qty. (Base)");
        OnAfterGetRemainingQty(Rec, RemainingQty, RemainingQtyBase); // << CALL TO NEW EVENT
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
