### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnAfterGetReservationQty

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#9992]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterGetReservationQty` to be added to Table 39 Purchase Line with the following signature:
```
[IntegrationEvent(false, false)]
procedure OnAfterGetReservationQty(var PurchLine: Record "Purchase Line"; var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal)
begin
end;
```
(with **VAR** parameters)

which would be called at the end of procedure `GetReservationQty`.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
