### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnAfterShowItemChargeAssgnt

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#9993]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterShowItemChargeAssgnt` to be added to Table 39 Purchase Line with the following signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterShowItemChargeAssgnt(var PurchaseLine: Record "Purchase Line"; var ItemChargeAssgnmtPurch: Page "Item Charge Assignment (Purch)")
    begin
    end;
```
(with **VAR** parameters)

which would be called at the last line of procedure `ShowItemChargeAssgnt`.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
