### ISSUE TITLE
[Event Request] Table 6651 - Return Shipment Line - Add IsHandled to OnInsertInvLineFromRetShptLineOnBeforePurchLineInsert (like is done for the same event in the Sales Line table)

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#9995]
Dear ALAppExtensions team,
Through this issue we would like to request an `IsHandled` parameter to be added to event `OnInsertInvLineFromRetShptLineOnBeforePurchLineInsert` in table 6651 Return Shipment Line, resulting in the following code in procedure `InsertInvLineFromRetShptLine`:
```pascal
            IsHandled := false;
            OnInsertInvLineFromRetShptLineOnBeforePurchLineInsert(Rec, PurchLine, NextLineNo, IsHandled); // Add argumentIsHandled, like for Sales Line table event
            if not IsHandled then begin
                PurchLine.Insert();
                NextLineNo := NextLineNo + 10000;
            end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
