### ISSUE TITLE
[Event Request] report 291 "Delete Invd Blnkt Sales Orders" - Trigger OnAfterGetRecord() - OnSalesHeaderOnBeforeDeleteApprovalEntries

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#9996]
Could You please, add the following event to the report 291 "Delete Invd Blnkt Sales Orders"

Object: report 291 "Delete Invd Blnkt Sales Orders"
Trigger: OnAfterGetRecord()

Publisher Event: OnSalesHeaderOnBeforeDeleteApprovalEntries

Reason: To implement custom business logic and avoid the deletion of approval entries
Where is the event placed (see image attached)?:
![image](https://user-images.githubusercontent.com/73465025/100241671-3d689100-2f34-11eb-9dd5-1db85e2bda73.png)

before the calling to delete the approval entries: ApprovalsMgmt.DeleteApprovalEntries(RecordId);
Insert the next lines:

>>>>>>>>>>>>>>>>
IsHandled := false;
OnSalesHeaderOnBeforeDeleteApprovalEntries("Sales Header", IsHandled);
if not IsHandled then
<<<<<<<<<<<<<<<<

Event Code:
[IntegrationEvent(false, false)]
local procedure OnSalesHeaderOnBeforeDeleteApprovalEntries(SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
