### ISSUE TITLE
[Event Request] Codeunit 5895 - Inventory Adjustment - OnPostItemJnlLineOnAfterSetPostingDate

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#9999]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnPostItemJnlLineOnAfterSetPostingDate` to be added to Codeunit 5895 Inventory Adjustment with the following signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetItemJnlLinePostingDate(var ItemJnlLine: Record "Item Journal Line"; OrigValueEntry: Record "Value Entry")
    begin
    end;
```
with **VAR** parameter `ItemJnlLine`.

which would be called as follows from `PostItemJnlLine`:
```pascal
    local procedure PostItemJnlLine(ItemJnlLine: Record "Item Journal Line"; OrigValueEntry: Record "Value Entry"; NewAdjustedCost: Decimal; NewAdjustedCostACY: Decimal)
    var
        InvtPeriod: Record "Inventory Period";
    begin
        with OrigValueEntry do begin
            ItemJnlLine."Item No." := "Item No.";
            ItemJnlLine."Location Code" := "Location Code";
            ItemJnlLine."Variant Code" := "Variant Code";

            if GLSetup.IsPostingAllowed("Posting Date") and InvtPeriod.IsValidDate("Posting Date") then
                ItemJnlLine."Posting Date" := "Posting Date"
            else
                ItemJnlLine."Posting Date" := PostingDateForClosedPeriod;
            OnPostItemJnlLineOnAfterSetPostingDate(ItemJnlLine, OrigValueEntry); // << CALL TO NEW EVENT
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
